[LibOS] Report back the default permissions of a file consistently
gramineproject/gramine pull request #10
Opened 2021-09-09 10:58 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Graphene created the file with default permissions (0755), but it reported different permissions 0700 as it includes only user permissions to the returned permissions. This fix includes group and other permissions to the file permissions returned.

Fixes gramineproject/graphene#2543

## How to test this PR? 
Create a file with mode set as 0777 the permissions of this newly generated file will be 0755. Use stat to report back the file permissions it should report 0755 instead of 0700.

2021-09-10 09:43 UTC, pwmarcz requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MjE44p-8sMJasjhXAXb:b1081fi) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
> ```C
>     if (dent) {
>         dent->type = type;
>         dent->perm = pal_attr.share_flags & 0777;
> ```

Why the `& 0777`? Is it to strip the sticky/setuid/setgid bits?

Since we don't care in other places (`chmod` passes `flags & 07777` further down), I'd just use `pal_attr.share_flags` here.


<!-- Sent from Reviewable.io -->

2021-09-21 10:23 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-Mk6rucR7L5WN6Bl6yuZ:bfl1e9u) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Why the `& 0777`? Is it to strip the sticky/setuid/setgid bits?

Since we don't care in other places (`chmod` passes `flags & 07777` further down), I'd just use `pal_attr.share_flags` here.
</blockquote></details>

Before making these changes `perm` was populated with only user permissions hence modified like this.

I have addressed your comment.


<!-- Sent from Reviewable.io -->

2021-09-22 00:11 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/10#-Mk9pPye54eVbVY1UK_e:-Mk9pPyf3CGYXlSSJexY:b-66cxtw) ([raw file](https://github.com/gramineproject/gramine/blob/f64413046961aa51701c77d5c67f48d6168bc05f/LibOS/shim/src/fs/chroot/fs.c#L269)):*
> ```C
>     if (dent) {
>         dent->type = type;
>         dent->perm = pal_attr.share_flags;
> ```

To be honest I'm not sure what's the point. Gramine does not check any of the permissions, and if any applications make any decisions based on this, it's gonna have a bad time.


<!-- Sent from Reviewable.io -->

2021-09-24 11:24 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/10#-Mk9pPye54eVbVY1UK_e:-MkMXMVA80SeI9a_O5iO:b-egouxt) ([raw file](https://github.com/gramineproject/gramine/blob/f64413046961aa51701c77d5c67f48d6168bc05f/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To be honest I'm not sure what's the point. Gramine does not check any of the permissions, and if any applications make any decisions based on this, it's gonna have a bad time.
</blockquote></details>

Please close this PR and the issue gramineproject/graphene#2543 if this is not required.


<!-- Sent from Reviewable.io -->

2021-09-24 15:03 UTC, pwmarcz approved these changes
Can you rebase? This part of the code changed significantly, but a similar change should still apply.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10#-:-MkNICMyCUNiduRBOE_0:bc9pv17)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/10#-Mk9pPye54eVbVY1UK_e:-MkNHvPu1L6Cg-xXLqu-:b-b2lhue) ([raw file](https://github.com/gramineproject/gramine/blob/f64413046961aa51701c77d5c67f48d6168bc05f/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Please close this PR and the issue gramineproject/graphene#2543 if this is not required.
</blockquote></details>

I think it's still useful, because it causes Graphene to behave more consistently.


<!-- Sent from Reviewable.io -->

2021-09-24 15:35 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/10#-Mk9pPye54eVbVY1UK_e:-MkNRIAx533w1Mnw5HLU:b2szmxn) ([raw file](https://github.com/gramineproject/gramine/blob/f64413046961aa51701c77d5c67f48d6168bc05f/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think it's still useful, because it causes Graphene to behave more consistently.
</blockquote></details>

I think it is not required, but since it's correct, we can merge it anyway.


<!-- Sent from Reviewable.io -->

2021-09-28 06:54 UTC, dimakuv commented
Jenkins, test this please

2021-09-28 07:11 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-28 07:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkfFplI4Aa-tT_qCr9H:-MkfFplI4Aa-tT_qCr9I:b-ppwf84) (no related file):*
@sahason Graphene in non-SGX mode and in debug mode failed with the following error:
```
assert failed ../Pal/src/db_streams.c:141 WITHIN_MASK(share, PAL_SHARE_MASK)
```

Please debug this and fix.

---


<!-- Sent from Reviewable.io -->

2021-09-28 08:44 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkfFplI4Aa-tT_qCr9H:-MkfZYoC9tcPUPhivxeM:bgiije5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Graphene in non-SGX mode and in debug mode failed with the following error:
```
assert failed ../Pal/src/db_streams.c:141 WITHIN_MASK(share, PAL_SHARE_MASK)
```

Please debug this and fix.
</blockquote></details>

@dimakuv Which test to run to repro this?

---


<!-- Sent from Reviewable.io -->

2021-09-28 10:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkfFplI4Aa-tT_qCr9H:-Mkg-ie6-2k3w3C_CM53:biho7t6) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

@dimakuv Which test to run to repro this?
</blockquote></details>

Any regression test. An excerpt from the Jenkins run:
```
Test Result (91 failures / +91)
  test_libos.TC_00_Unittests.test_000_spinlock
  test_libos.TC_00_Unittests.test_010_shim_run_test
  test_libos.TC_01_Bootstrap.test_001_helloworld
```

So even the `helloworld` fails.

---


<!-- Sent from Reviewable.io -->

2021-09-29 06:05 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkfFplI4Aa-tT_qCr9H:-Mkk92Iy0PQzEv3H3dD9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any regression test. An excerpt from the Jenkins run:
```
Test Result (91 failures / +91)
  test_libos.TC_00_Unittests.test_000_spinlock
  test_libos.TC_00_Unittests.test_010_shim_run_test
  test_libos.TC_01_Bootstrap.test_001_helloworld
```

So even the `helloworld` fails.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-09-29 06:24 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkfFplI4Aa-tT_qCr9H:-MkkDOBh55WSV2NZ5VDB:b-gh9cyj) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would prefer some explanations why you re-added `& 07777` after your debugging session. See my other comment.

---
___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkkD0kw1-2EIUeIGmtD:b-z8mlu7) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Before making these changes `perm` was populated with only user permissions hence modified like this.

I have addressed your comment.
</blockquote></details>

@sahason Could you explain why you re-added `& 07777` (but now preserving sticky/setuid/setgid bits) after your debugging session? Why did it fail before? What other bits are returned in `pal_attr.share_flags` that broke the examples?


<!-- Sent from Reviewable.io -->

2021-09-29 06:24 UTC, dimakuv commented
Jenkins, test this please

2021-09-29 06:45 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkkE30728c2cXWrse8C:bmm3zj4) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Could you explain why you re-added `& 07777` (but now preserving sticky/setuid/setgid bits) after your debugging session? Why did it fail before? What other bits are returned in `pal_attr.share_flags` that broke the examples?
</blockquote></details>

`pal_attr.share_flag` is populated by  `st_mode` field of `struct stat` which is getting populated by a `stat` call. This `st_mode` field has two parts file type (MSB 
 6 bits) and mode (LSB 12 bits).  It was failing before as `_DkStreamOpen` compares `share` parameter with `PAL_SHARE_MASK` (07777), the `share` parameter is nothing but `pal_attr.share_flag` assigned via `dent->perm` and it also has the MSB 6 bits set as file type along with mode.


<!-- Sent from Reviewable.io -->

2021-09-29 06:59 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkkKWUeClP_TZWMPzry:bc52qpk) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

`pal_attr.share_flag` is populated by  `st_mode` field of `struct stat` which is getting populated by a `stat` call. This `st_mode` field has two parts file type (MSB 
 6 bits) and mode (LSB 12 bits).  It was failing before as `_DkStreamOpen` compares `share` parameter with `PAL_SHARE_MASK` (07777), the `share` parameter is nothing but `pal_attr.share_flag` assigned via `dent->perm` and it also has the MSB 6 bits set as file type along with mode.
</blockquote></details>

`_DkStreamOpen` checks if `share` parameter is within PAL_SHARE_MASK, not compare.


<!-- Sent from Reviewable.io -->

2021-09-29 07:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkkQkLbDALXtQtZFwmQ:bsi6nl0) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

`_DkStreamOpen` checks if `share` parameter is within PAL_SHARE_MASK, not compare.
</blockquote></details>

Thanks. @pwmarcz Does this change make sense to you?


<!-- Sent from Reviewable.io -->

2021-09-29 09:30 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-Mkkpuqd7KFTNB7O5tB0:bvcphy) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks. @pwmarcz Does this change make sense to you?
</blockquote></details>

Thanks @sahason for investigating.

It seems to me that PAL is wrong here. Although the documentation in `pal.h` doesn't _promise_ that `pal_attr.share_flags` is a combination of `PAL_SHARE_*`, it does require it for the `share_flags` parameter you mention, so it's unexpected so see this extra bits set. Also, the "file type" part is already reported separately in `pal_attr.handle_type`.

Instead of working around this problem here, I suggest setting `pal_attr.share_flags` to `st_mode & PAL_SHARE_MASK` (from a quick `git grep`, I see 6 assignments in PAL that need to be changed). I would do it in a separate commit, before this one.

Alternatively (or if the change turns out to be more difficult), please at least add a comment here explaining that `pal_attr.share_flags` contains file type bits.


<!-- Sent from Reviewable.io -->

2021-09-30 11:12 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkqO9btBjUJTlZ9leXx:bwz5a9f) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Thanks @sahason for investigating.

It seems to me that PAL is wrong here. Although the documentation in `pal.h` doesn't _promise_ that `pal_attr.share_flags` is a combination of `PAL_SHARE_*`, it does require it for the `share_flags` parameter you mention, so it's unexpected so see this extra bits set. Also, the "file type" part is already reported separately in `pal_attr.handle_type`.

Instead of working around this problem here, I suggest setting `pal_attr.share_flags` to `st_mode & PAL_SHARE_MASK` (from a quick `git grep`, I see 6 assignments in PAL that need to be changed). I would do it in a separate commit, before this one.

Alternatively (or if the change turns out to be more difficult), please at least add a comment here explaining that `pal_attr.share_flags` contains file type bits.
</blockquote></details>

@pwmarcz  Sure, once the PR you mentioned is submitted I will make the changes based on it. 


<!-- Sent from Reviewable.io -->

2021-09-30 11:30 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkqT0smDr_V73KNYAeT:b-s7y785) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

@pwmarcz  Sure, once the PR you mentioned is submitted I will make the changes based on it. 
</blockquote></details>

@sahason I'm pretty sure Pawel implied that you will do this in this PR (as a separate commit).


<!-- Sent from Reviewable.io -->

2021-09-30 16:21 UTC, pwmarcz requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/10#-MkrVKCs5LoS_9OzTDRX:-MkrVKCs5LoS_9OzTDRY:bc4dpxi) (no related file):*
@sahason Can you rebase the change on latest master? As mentioned before, this part of the code (`chroot/fs`) has significantly changed in the meantime (although the change still applies), so it would be better to test after rebasing.

---
___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkrTMcPBrIdiVI95D4X:b-9ttdzi) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Sure, will do it.
</blockquote></details>

Yes. Sorry if that wasn't clear. My reasoning is that the change is small enough that we can already do the non-hacky thing.

The change looks good to me now, but let's rebase and run tests.


<!-- Sent from Reviewable.io -->

2021-09-30 17:37 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-MkrllS0CbnA3Uw3tAmq:brkfnx) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. Sorry if that wasn't clear. My reasoning is that the change is small enough that we can already do the non-hacky thing.

The change looks good to me now, but let's rebase and run tests.
</blockquote></details>

Weren't these changes supposed to go into a new commit with a proper description?


<!-- Sent from Reviewable.io -->

2021-09-30 18:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @sahason)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/10#-MjE44p-8sMJasjhXAXa:-Mks0Emq5JxFk9kETuHl:bk5crqv) ([raw file](https://github.com/gramineproject/gramine/blob/b469209e0d64243478eab6fde8c4fe437226b576/LibOS/shim/src/fs/chroot/fs.c#L269)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Weren't these changes supposed to go into a new commit with a proper description?
</blockquote></details>

Yes. @sahason, can you do that while rebasing? The commit changing PAL should be *before* the commit fixing FS (so that commit fixing FS isn't broken).


<!-- Sent from Reviewable.io -->

2021-10-03 19:42 UTC, pwmarcz submitted a review, later dismissed
Jenkins, test this please

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10#-:-Ml6fTnT9zqmGQcS-yzm:bkop2df)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2021-10-03 19:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-10-03 20:30 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-03 21:41 UTC, dimakuv commented
Jenkins, test this please

2021-10-04 06:02 UTC, dimakuv commented
Jenkins, test this please

2021-10-04 06:03 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-10-04 09:00 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/10)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-04 10:00 UTC, merged