[Pal/Linux-SGX] Verify enclave measurements during SGX local/remote attestation
gramineproject/gramine pull request #100
Opened 2021-09-29 07:42 UTC by dimakuv

## Description of the changes 

This PR fixes two problems with SGX attestation (missing checks for `ATTRIBUTES`, `MRSIGNER`, etc.):

### Verify all enclave measurements during local attestation

Previously, only MRENCLAVE was verified during SGX local attestation (between parent enclave and the spawned child enclave). However, MRENCLAVE doesn't reflect e.g. ATTRIBUTES of the enclave. This could lead to situations where the parent has `ATTRIBUTES.DEBUG = 0` (production enclave) and communicates with the child that has `ATTRIBUTES.DEBUG = 1` (debug enclave).

This PR fixes this by verifying all relevant SGX enclave measurements, including MRENCLAVE, MRSIGNER, ATTRIBUTES, etc.

### Verify enclave attributes during remote attestation

Previously, ATTRIBUTES were not verified during SGX remote attestation in RA-TLS flows. However, MRENCLAVE doesn't reflect ATTRIBUTES of the enclave. This could lead to situations where the verifier doesn't notice `ATTRIBUTES.DEBUG = 1` (debug enclave) and releases secrets to this debug enclave.

This PR fixes this by verifying all relevant SGX enclave attributes, including DEBUG, INIT, etc. In particular, DEBUG=1 is only allowed if the verifier has set the environment variable `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1`.

## How to test this PR? 

CI was updated to test RA-TLS flows.

2021-09-29 18:14 UTC, boryspoplawski requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkm_obPDs9pUeqBBlxe):*
This (`releases`) sounds weird to me in this context. Maybe `shares secrets with`?
___
*[Pal/src/host/Linux-SGX/db_process.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmc-tu5cv7CAwkSPMw:-Mkmc-tu5cv7CAwkSPMx:b-p4c9af) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/db_process.c#L161)):*
> ```C
>         return false;
> 
>     /* do not verify config_id and config_svn -- they are set by the app enclave after EINIT and are
> ```

Actually, couldn't we collapse all of this function to `memcmp(peer_enclave_measurements, &g_pal_sec.enclave_measurements, sizeof())`? I'm not sure if that would be better or cleaner, but definitely it would be shorter and would make it pretty obvious that we verify **everything**. (I assume that `config_id` and `config_svn` are the same and currently not verified for simplicity only. Also I assume that reserved fields are zeroed.)
Just an idea, not blocking.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 954 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmcmoWE1G_vPVLgaw8:-MkmcmoWE1G_vPVLgaw9:bde4ht1) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L954)):*
> ```C
> 
> int init_enclave(void) {
>     /* initialize enclave measurements (MR_ENCLAVE, etc.) of my own enclave (via EREPORT) */
> ```

`my own` sounds weird here, maybe `current`?
(maybe too much of this: https://www.youtube.com/watch?v=NA-LNVbf10I)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 961 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmdLIW09cPeGRyLJL2:-MkmdLIW09cPeGRyLJL3:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L961)):*
> ```C
>     int ret = sgx_report(&targetinfo, &reportdata, &report);
>     if (ret) {
>         log_error("Failed to get my own SGX report");
> ```

ditto
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmgFjeEZne7afZFctI:-MkmgFjeEZne7afZFctJ:b-87xxkz) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L135)):*
> ```objc
>  *
>  * \param  peer_enclave_measurements  SGX measurements of the peer enclave.
>  * \param  expected_data              Expected SGX report data, contains SHA256(K_e || tag1).
> ```

What is `K_e` and `tag1`?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmgay7DBbLvIlZhv9-:-Mkmgay7DBbLvIlZhv90:b-6jh7yb) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/sgx_main.c#L252)):*
> ```C
> #ifdef DEBUG
>     if (enclave->profile_enable) {
>         if (!(enclave_token.body.attributes.flags & SGX_FLAGS_DEBUG)) {
> ```

Why not `g_pal_sec.enclave_measurements.attributes`?
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 183 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmj_cX5Nvp_1PGxeAp:-Mkmj_cX5Nvp_1PGxeAq:b7e1afm) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L183)):*
> ```C
>     bool allow_debug_enclave = false;
>     char* str = getenv(RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE);
>     if (str && (!strcmp(str, "1") || !strcmp(str, "true") || !strcmp(str, "TRUE")))
> ```

Why do we allow for 3 different values (e.g. instead of just `1`)?


<!-- Sent from Reviewable.io -->

2021-09-29 23:34 UTC, mkow requested changes
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmlSZr7usqo9e1tqYL:-MkmlSZr7usqo9e1tqYM:b8ndwuw) (no related file):*
> ```
> Verify enclave measurements during SGX local/remote attestation
> ```

The PR name is IMO misleading - we were already verifying enclave measurements, but it turned out that this is not enough in SGX, and that's what the whole fuss is about :)

---
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmllT46wfD9ybFE-K_):*
Hmm, you call "attributes" flag a measurement? It's a bit confusing, this is just a start configuration, not any measurement.
___
*[Pal/src/host/Linux-SGX/db_process.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmc-tu5cv7CAwkSPMw:-MkndKNG-cerZrGryzXB:b-xwxge) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/db_process.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, couldn't we collapse all of this function to `memcmp(peer_enclave_measurements, &g_pal_sec.enclave_measurements, sizeof())`? I'm not sure if that would be better or cleaner, but definitely it would be shorter and would make it pretty obvious that we verify **everything**. (I assume that `config_id` and `config_svn` are the same and currently not verified for simplicity only. Also I assume that reserved fields are zeroed.)
Just an idea, not blocking.
</blockquote></details>

+1, any reason not to compare everything?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 954 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkngWoE6ideUy_o5DfG:-MkngWoE6ideUy_o5DfH:bv37fdj) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L954)):*
> ```C
> 
> int init_enclave(void) {
>     /* initialize enclave measurements (MR_ENCLAVE, etc.) of my own enclave (via EREPORT) */
> ```

`MR_ENCLAVE` -> `MRENCLAVE`
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mknp18B2gaqaxfMgtqO:-Mknp18B2gaqaxfMgtqP:biw50ls) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L130)):*
> ```
> SGX measurements
> ```

ditto
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mknp6R17O8gDC5xJ-Iy:-Mknp6R17O8gDC5xJ-Iz:bxndyzw) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L131)):*
> ```
> all Gramine enclaves with the same configuration have the same measurements
> ```

ditto, especially here


<!-- Sent from Reviewable.io -->

2021-09-29 23:36 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-MknuQbB5Kpo0FaJEsXf:-MknuQbB5Kpo0FaJEsXg:b-gxs34j) (no related file):*
> CI was updated to test RA-TLS flows.

What do you mean? RA-TLS is already tested in CI.

---


<!-- Sent from Reviewable.io -->

2021-09-30 08:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 10 of 14 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmlSZr7usqo9e1tqYL:-MkpbXKp2sj8NkKDgSC-:b-cf7e8h) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Verify enclave measurements during SGX local/remote attestation
> ```

The PR name is IMO misleading - we were already verifying enclave measurements, but it turned out that this is not enough in SGX, and that's what the whole fuss is about :)
</blockquote></details>

Done. Yeah, `enclave measurements` is misleading. I looked at the official Intel documentation, and they simply call it `enclave information`. So that's what I use now.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-MknuQbB5Kpo0FaJEsXf:-MkpbgZg4yMgdHFe7ihL:bh7023w) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> CI was updated to test RA-TLS flows.

What do you mean? RA-TLS is already tested in CI.
</blockquote></details>

Done, changed the wording.

---
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmllT46wfD9ybFE-K_):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, you call "attributes" flag a measurement? It's a bit confusing, this is just a start configuration, not any measurement.
</blockquote></details>

Done. Using `enclave information` now.
___
*[-- commits, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkm_obPDs9pUeqBBlxe):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This (`releases`) sounds weird to me in this context. Maybe `shares secrets with`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_process.c, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkpgoa1DkOvkdmuiCHU:-Mkpgoa1DkOvkdmuiCHV:b-5q13ri) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/db_process.c#L30)):*
> ```C
> 
> /*
>  * For SGX, the creation of a child process requires a clean enclave and a secure channel between
> ```

@boryspoplawski Please read this to get an understanding about `K_e`
___
*[Pal/src/host/Linux-SGX/db_process.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmc-tu5cv7CAwkSPMw:-MkpgRX12q_JHxnBd1Ne:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/db_process.c#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, any reason not to compare everything?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 954 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmcmoWE1G_vPVLgaw8:-MkpeN780rM6ABFyvcCY:bhy3z32) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L954)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`my own` sounds weird here, maybe `current`?
(maybe too much of this: https://www.youtube.com/watch?v=NA-LNVbf10I)
</blockquote></details>

Done. I actually re-watched the first LotR recently :)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 954 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkngWoE6ideUy_o5DfG:-MkpeV_o5JiUlK3qgVsT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L954)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`MR_ENCLAVE` -> `MRENCLAVE`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 961 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmdLIW09cPeGRyLJL2:-MkpeWKpERZH4_8SssT_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L961)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mknp18B2gaqaxfMgtqO:-MkpgdEC-Tm7L74M5mBJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> SGX measurements
> ```

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mknp6R17O8gDC5xJ-Iy:-Mkpgdmw-Sq2HN_JQ_Nh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> all Gramine enclaves with the same configuration have the same measurements
> ```

ditto, especially here
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmgFjeEZne7afZFctI:-MkpiCpU0hDuvGFoReYG:b-wv9mdc) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/pal_linux.h#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is `K_e` and `tag1`?
</blockquote></details>

Done. Added some more pointers.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmgay7DBbLvIlZhv9-:-MkpiVBd4FHPYzUq4Ee3:b-l9jj30) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/sgx_main.c#L252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `g_pal_sec.enclave_measurements.attributes`?
</blockquote></details>

`g_pal_sec` is for in-enclave (trusted PAL) usage only. We can't use it here; it is not even initialized here yet. (Note that this `sgx_main.c` logic runs on startup in untrusted PAL.)
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkpcW1kAdrTmUu9YbM8:-MkpcW1kAdrTmUu9YbM9:b-7ra06e) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L84)):*
> ```C
>         return 0;
> 
>     if (!strcmp(str, "1") || !strcmp(str, "true") || !strcmp(str, "TRUE"))
> ```

FYI: @boryspoplawski Here is an example of another envvar where we check for `1`/`true`/`TRUE`.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 183 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmj_cX5Nvp_1PGxeAp:-Mkpcn2x8YbKc4s5_jdr:b-hjb7k0) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L183)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we allow for 3 different values (e.g. instead of just `1`)?
</blockquote></details>

T [...]

2021-09-30 16:47 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_process.c, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkpgoa1DkOvkdmuiCHU:-Mkr_JqQ3o5Uql6TBg9T:b-ca96py) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/db_process.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Please read this to get an understanding about `K_e`
</blockquote></details>

Ok, so this is just an ephemeral key from DH.
___
*[Pal/src/host/Linux-SGX/db_process.c, line 130 at r2](https://reviewable.io/reviews/gramineproject/gramine/100#-MkrZVct4iP679HnWAVT:-MkrZVct4iP679HnWAVU:b-jyoo8e) ([raw file](https://github.com/gramineproject/gramine/blob/33a5932dae222595aaf56472b7105c5d5de9560f/Pal/src/host/Linux-SGX/db_process.c#L130)):*
> ```C
>      * by the app enclave after EINIT and are thus not security-critical) */
>     if (memcmp(peer_enclave_info, &g_pal_sec.enclave_info,
>                offsetof(sgx_report_body_t, report_data)))
> ```

Please add an assert before this `if` statement:
`static_assert(offsetof(sgx_report_body_t, report_data) + sizeof(*expected_data) == sizeof(sgx_report_body_t), "msg");`
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 183 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmj_cX5Nvp_1PGxeAp:-Mkr_mLh3xPC0PluA_UY:b-p5qdwb) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L183)):*
This is weird...
> So I would say this is irrelevant to this PR and should stay as-is.

But you've introduced this env variable in this PR. I'm not say we should change the other place in this PR.
Unblocking, as this is not important.


<!-- Sent from Reviewable.io -->

2021-09-30 21:40 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-Mko7ltt1R_EDO8nrJXc:-Mko7ltt1R_EDO8nrJXd:b-cycku6) (no related file):*
I think you missed `Pal/src/host/Linux-SGX/tools/common/attestation.c` and everything which uses it (at least `verify-ias-report`).

---
___
*[Pal/src/host/Linux-SGX/db_process.c, line 130 at r2](https://reviewable.io/reviews/gramineproject/gramine/100#-MkrZVct4iP679HnWAVT:-MksVist9ZIBlKJp3viw:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/33a5932dae222595aaf56472b7105c5d5de9560f/Pal/src/host/Linux-SGX/db_process.c#L130)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add an assert before this `if` statement:
`static_assert(offsetof(sgx_report_body_t, report_data) + sizeof(*expected_data) == sizeof(sgx_report_body_t), "msg");`
</blockquote></details>

+1
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 954 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-MkmcmoWE1G_vPVLgaw8:-MksWaH-CQkjfm8FDwgq:bn1wz0t) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/enclave_framework.c#L954)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I actually re-watched the first LotR recently :)
</blockquote></details>

:thumbsup:


<!-- Sent from Reviewable.io -->

2021-10-01 08:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 9 of 18 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/100#-Mko7ltt1R_EDO8nrJXc:-MkuwiIBEmceO7s0q5KR:b-vypip7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think you missed `Pal/src/host/Linux-SGX/tools/common/attestation.c` and everything which uses it (at least `verify-ias-report`).
</blockquote></details>

Done. Refactored this part a bit as well.

---
___
*[Pal/src/host/Linux-SGX/db_process.c, line 130 at r2](https://reviewable.io/reviews/gramineproject/gramine/100#-MkrZVct4iP679HnWAVT:-MkumelBDBeZ0dxpCmkB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33a5932dae222595aaf56472b7105c5d5de9560f/Pal/src/host/Linux-SGX/db_process.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkv-YzlDDN2ZZArP2u5:-Mkv-YzlDDN2ZZArP2u6:b-z3pczc) ([raw file](https://github.com/gramineproject/gramine/blob/5c505d44ab6ffa6d303cde51b4ccf922c3eaab88/Pal/src/host/Linux-SGX/tools/common/attestation.h#L58)):*
> ```objc
>  *  \return 0 on successful verification, negative value on error.
>  */
> int verify_ias_report(const uint8_t* ias_report, size_t ias_report_size, uint8_t* ias_sig_b64,
> ```

FYI: This function wasn't needed at all, I just removed it.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h, line 55 at r2](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkv-gDl0l5G4Zhan1HZ:-Mkv-gDl0l5G4Zhan1H_:b-ozncb0) ([raw file](https://github.com/gramineproject/gramine/blob/33a5932dae222595aaf56472b7105c5d5de9560f/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h#L55)):*
> ```objc
> 
> __attribute__ ((visibility("hidden")))
> int verify_quote_enclave_attributes(const sgx_quote_t* quote);
> ```

FYI: Moved this function from RA-TLS to common attestation utils.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 183 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmj_cX5Nvp_1PGxeAp:-Mkuml3JAkBTk0df51Bw:b-oz7ovu) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L183)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is weird...
> So I would say this is irrelevant to this PR and should stay as-is.

But you've introduced this env variable in this PR. I'm not say we should change the other place in this PR.
Unblocking, as this is not important.
</blockquote></details>

I would still prefer to change this convention in one go (in a separate PR).


<!-- Sent from Reviewable.io -->

2021-10-01 13:13 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 90 at r3](https://reviewable.io/reviews/gramineproject/gramine/100#-MkvyoAv0TiOPvCLxW_C:-MkvyoAx49EtgCvuVsxj:b6yq11c) ([raw file](https://github.com/gramineproject/gramine/blob/bbfb1f39bd8cb690e6e377f70ca9cfe96ecb689d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L90)):*
> ```C
> }
> 
> int getenv_allow_debug_enclave(bool* allow_debug_enclave) {
> ```

What's the point of return value in this function?


<!-- Sent from Reviewable.io -->

2021-10-01 14:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 13 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 90 at r3](https://reviewable.io/reviews/gramineproject/gramine/100#-MkvyoAv0TiOPvCLxW_C:-Mkw8Qt87p0cUGCqyyyL:b-h9n7xx) ([raw file](https://github.com/gramineproject/gramine/blob/bbfb1f39bd8cb690e6e377f70ca9cfe96ecb689d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of return value in this function?
</blockquote></details>

Done. Ok, since these envvars and functions were some verbose, I also removed the `1/true/TRUE` convention and just kept `1`.


<!-- Sent from Reviewable.io -->

2021-10-01 14:19 UTC, mkow requested changes
> Reviewed 7 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 449 at r3](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkw86yK9ES8R_VEJmCS:-Mkw86yK9ES8R_VEJmCT:bsf63cz) ([raw file](https://github.com/gramineproject/gramine/blob/bbfb1f39bd8cb690e6e377f70ca9cfe96ecb689d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L449)):*
> ```
> const void* quote_data
> ```

Why not `sgx_quote_t*`? This function already assumes that it's `sgx_quote_t*` and can't really validate this, as it doesn't know the data size. So, it's just enforce this in the interface.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 183 at r1](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkmj_cX5Nvp_1PGxeAp:-MkwB7mI02IOfFYf_XI5:bo8rzge) ([raw file](https://github.com/gramineproject/gramine/blob/a8391e672ccbd9bee7e042fb659309075e6bce26/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would still prefer to change this convention in one go (in a separate PR).
</blockquote></details>

+1, let's keep this uniform with other similar variables, if we want to change this we need to do it everywhere (as this is a public API)
update: ah, seems you already changed it everywhere. resolving then.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 168 at r4](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwCvNs-pWQZMtfCr1V:-MkwCvNs-pWQZMtfCr1W:b-d4zy0j) ([raw file](https://github.com/gramineproject/gramine/blob/69d55999dcee3afe2d63b8e2bad492dca48cdf79/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L168)):*
> ```C
> 
>     uint8_t* report_quote = NULL;
>     size_t quote_size     = 0;
> ```

I'd either unalign this or align both the names and the values, the current version looks bad
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r4](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwCo9n04mM1Zz4S5lW:-MkwCo9o1ZaPb3IeGY_P:b8sm27a) ([raw file](https://github.com/gramineproject/gramine/blob/69d55999dcee3afe2d63b8e2bad492dca48cdf79/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
> ```C
>     ret = verify_ias_report_extract_quote(report, report_size, sig, sig_size,
>                                               allow_outdated_tcb, nonce, ias_pubkey,
>                                               &report_quote, &quote_size);
> ```

this is misaligned


<!-- Sent from Reviewable.io -->

2021-10-01 14:47 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 168 at r4](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwCvNs-pWQZMtfCr1V:-MkwJcrAAOa-XqDykB30:b-oyn2is) ([raw file](https://github.com/gramineproject/gramine/blob/69d55999dcee3afe2d63b8e2bad492dca48cdf79/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L168)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd either unalign this or align both the names and the values, the current version looks bad
</blockquote></details>

+1 to unalign


<!-- Sent from Reviewable.io -->

2021-10-01 14:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 14 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 449 at r3](https://reviewable.io/reviews/gramineproject/gramine/100#-Mkw86yK9ES8R_VEJmCS:-MkwJa1--I9aGXsoay8o:b-gvg01f) ([raw file](https://github.com/gramineproject/gramine/blob/bbfb1f39bd8cb690e6e377f70ca9cfe96ecb689d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L449)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> const void* quote_data
> ```

Why not `sgx_quote_t*`? This function already assumes that it's `sgx_quote_t*` and can't really validate this, as it doesn't know the data size. So, it's just enforce this in the interface.
</blockquote></details>

Done. Initially I did it that way because that was the signature of other funcs in `attestation.h`. But yes, this is better.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 168 at r4](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwCvNs-pWQZMtfCr1V:-MkwJoGp6jh0hM8Qfs2J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/69d55999dcee3afe2d63b8e2bad492dca48cdf79/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to unalign
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r4](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwCo9n04mM1Zz4S5lW:-MkwJqesASbP2XIdgnvw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/69d55999dcee3afe2d63b8e2bad492dca48cdf79/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is misaligned
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 15:00 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-01 15:04 UTC, mkow requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 236 at r5](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwMmby6IuK9XEjLbF3:-MkwMmby6IuK9XEjLbF4:b-jwgbvj) ([raw file](https://github.com/gramineproject/gramine/blob/4b15fae5743261bf3e5df265d0e6a043ee0269d1/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L236)):*
> ```
> (sgx_quote_t*)quote_from_ias
> ```

You should do this cast only after checking `quote_from_ias_size`, which happens a few lines below.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwN402D0UBLR6avHm3:-MkwN402D0UBLR6avHm4:b-qpy77w) ([raw file](https://github.com/gramineproject/gramine/blob/4b15fae5743261bf3e5df265d0e6a043ee0269d1/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
> ```C
>     ret = verify_ias_report_extract_quote(report, report_size, sig, sig_size,
>                                           allow_outdated_tcb, nonce, ias_pubkey,
>                                           &report_quote, &quote_size);
> ```

`quote_size` - ditto, but this function seem to lack this check altogether? This is quite important, because if I see correctly, this data are received over network and in current version can cause memory corruption.


<!-- Sent from Reviewable.io -->

2021-10-01 17:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 16 of 18 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 236 at r5](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwMmby6IuK9XEjLbF3:-Mkwv4TS5zO5py6cI-lx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b15fae5743261bf3e5df265d0e6a043ee0269d1/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> (sgx_quote_t*)quote_from_ias
> ```

You should do this cast only after checking `quote_from_ias_size`, which happens a few lines below.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/100#-MkwN402D0UBLR6avHm3:-MkwwfSc6Sz-chZl3rLM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b15fae5743261bf3e5df265d0e6a043ee0269d1/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`quote_size` - ditto, but this function seem to lack this check altogether? This is quite important, because if I see correctly, this data are received over network and in current version can cause memory corruption.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 18:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: 13 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r7](https://reviewable.io/reviews/gramineproject/gramine/100#-MkxBOZT4GT8vFu46IvU:-MkxBOZU3prelLHupkew:b-qimp9m) ([raw file](https://github.com/gramineproject/gramine/blob/b862166d8d604ebcc3db30fdef5a0e3b8c567142/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
FYI: These two signature-related fields are removed from the SGX Quote returned in the IAS attestation report. This is what the official `IAS-API-Spec-rev-5.0.pdf` tells us:
> isvEnclaveQuoteBody String Base 64-encoded BODY of QUOTE structure (i.e., QUOTE structure without signature related fields: SIG_LEN and SIG) as received in
Attestation Evidence Payload. See Quoting Data Structures for details
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 64 at r7](https://reviewable.io/reviews/gramineproject/gramine/100#-MkxBca-1TW1g6TJDC3x:-MkxBca-1TW1g6TJDC3y:b6y9xto) ([raw file](https://github.com/gramineproject/gramine/blob/b862166d8d604ebcc3db30fdef5a0e3b8c567142/Pal/src/host/Linux-SGX/sgx_attest.h#L64)):*
> ```objc
> } sgx_quote_t;
> 
> #define SGX_QUOTE_BODY_SIZE (offsetof(sgx_quote_t, signature_len))
> ```

FYI: Apparently there was already a convinience macro to calculate the "SGX Quote Body" size. I started using it everywhere.
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 75 at r7](https://reviewable.io/reviews/gramineproject/gramine/100#-MkxBpLsD9CUFVSS9xLE:-MkxBpLsD9CUFVSS9xLF:b-wnubu8) ([raw file](https://github.com/gramineproject/gramine/blob/b862166d8d604ebcc3db30fdef5a0e3b8c567142/Pal/src/host/Linux-SGX/sgx_attest.h#L75)):*
> ```objc
> 
> /* EPID SGX quotes are ~1K in size, DCAP SGX quotes ~4K, overapproximate to 8K */
> #define SGX_QUOTE_MAX_SIZE 8192
> ```

FYI: Apparently we already have a coninience macro with the max SGX quote size. I started using it everywhere.


<!-- Sent from Reviewable.io -->

2021-10-01 18:59 UTC, mkow submitted a review, later dismissed
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-10-01 19:16 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-10-01 20:30 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-10-01 20:37 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/100)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-01 21:18 UTC, merged