[common] Split `common_dep` into several dependencies
gramineproject/gramine pull request #1002
Opened 2022-10-21 06:46 UTC by kailun-qin

Currently, all `common/` source files are supplied via a single `common_dep`. However in some cases, we may only want to reuse the part of the utility functions in `common/` without importing the other part of Gramine-supplied mini-libc (which might lead to colliding issues).

This patch separates `common/` into several dependencies for more flexible usage.

The original requirement was from https://github.com/gramineproject/gramine/pull/937. For details, pls kindly refer to that PR thread.

2022-10-21 11:32 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEttIkT9WXVt2R3XnSs:-NEuISLzB13ttqnAbNF2:bfnolnl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should have given more explanations on how to do this PR.

Please fix the following main problem: all files in `common_src_utils` dependency **must be** Gramine-headers independent. In particular, you should remove dependencies on `api.h` and `assert.h` in these files.

This will also dictate which files *can* go into `common_src_utils` -- for example, AVL trees cannot go there because it requires `api.h`, `assert.h` and `avl_tree.h` (even if you would remove the first two, you'll still have a problem with the latter one).
</blockquote></details>

E.g. `path.c` and `network/inet_pton.c` both use libc functions like`memcpy()`, `strxxx()` in `api.h`, what's the exact rule to decide which one should go to `common_src_utils` (as you only suggested `path.c` to be in the utils list)? When you say `Gramine-headers independent`, does this include libc functions that Gramine supplied?

___


<!-- Sent from Reviewable.io -->

2022-10-21 11:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEttIkT9WXVt2R3XnSs:-NEuJl5D1QgqMw3WO9E0:bx0v8hc) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

E.g. `path.c` and `network/inet_pton.c` both use libc functions like`memcpy()`, `strxxx()` in `api.h`, what's the exact rule to decide which one should go to `common_src_utils` (as you only suggested `path.c` to be in the utils list)? When you say `Gramine-headers independent`, does this include libc functions that Gramine supplied?
</blockquote></details>

You can use libc functions in both Gramine-internal (what you call `common_src_libc` + `common_src_internal`) and Gramine-external (what you call `common_src_utils`) dependencies.

To distinguish which headers to include (`"api.h"` for Gramine-internal or `<string.h>` for Gramine-external), you can use the macro `USE_STDLIB`. We already use it for similar purposes: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/common/src/protected_files/protected_files_format.h#L9-L13

Does that explain my idea?

___


<!-- Sent from Reviewable.io -->

2022-10-21 13:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: 0 of 19 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEttIkT9WXVt2R3XnSs:-NEucvYO2XEzu-8PGvNz:by193t3) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Made a quick update, pls kindly take a look if it's sth you'd expect.
</blockquote></details>

Yes, this looks much better.

However, please change `include/utils/utils.h` into two files:
- `include/path_utils.h`
- `include/string_utils.h`

I also now realized that we don't need a separate `common_inc_utils`. Sorry, please remove it (and then you can have the two new header files simply under `common/include/`, as it was before).

It would be good to also rename `path.c` -> `path_utils.c` and `string.c` -> `string_utils.c`.

I think after these changes everything will be much cleaner.

___
___
*[`common/include/api.h` line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEucCEv7Pj-MTNFjSUw:-NEucCEv7Pj-MTNFjSUx:beypzvj) ([raw file](https://github.com/gramineproject/gramine/blob/6cf172432bfc183fc1d4bfb372dadd1198a9c56f/common/include/api.h#L378)):*
> ```objc
> extern const char* const* sys_errlist_internal;
> 
> /* Gramine functions */
> ```

Please remove this comment, not needed anymore


<!-- Sent from Reviewable.io -->

2022-10-24 02:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: 0 of 19 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEttIkT9WXVt2R3XnSs:-NF6htvfDnbGLil2itp_:bnga3yj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this looks much better.

However, please change `include/utils/utils.h` into two files:
- `include/path_utils.h`
- `include/string_utils.h`

I also now realized that we don't need a separate `common_inc_utils`. Sorry, please remove it (and then you can have the two new header files simply under `common/include/`, as it was before).

It would be good to also rename `path.c` -> `path_utils.c` and `string.c` -> `string_utils.c`.

I think after these changes everything will be much cleaner.
</blockquote></details>

Updated, PTAL, thanks!

___
___
*[`common/include/api.h` line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEucCEv7Pj-MTNFjSUw:-NF6hmAD3OVE218SEErq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6cf172432bfc183fc1d4bfb372dadd1198a9c56f/common/include/api.h#L378)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this comment, not needed anymore
</blockquote></details>

Done.
___
*[`common/src/string.c` line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/1002#-NEuYl5j3jN0MoqHNVLn:-NEuYl5k7gN4V6_9I8T8:buc7frq) ([raw file](https://github.com/gramineproject/gramine/blob/db27e6214f93ab025c400628be66a8b9695707c1/common/src/string.c#L52)):*
> ```C
>     const char* s = str;
>     while (*s != '\0') {
>         int digit = parse_digit(*s, base);
> ```

I inlined `parse_digit` previously


<!-- Sent from Reviewable.io -->

2022-10-24 08:38 UTC, dimakuv requested changes
> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/include/path_utils.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87vJ616VTWd0d4Nur:-NF87vJ616VTWd0d4Nus:b-a136wy) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L9)):*
> ```objc
> #include <stddef.h>
> 
> int get_norm_path(const char* path, char* buf, size_t* inout_size);
> ```

Please check all callers of this func and add `unix_to_pal_error()` in PAL code if needed, and remove `pal_to_unix_error()` in LibOS code.
___
*[`common/include/path_utils.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87mGn5udEqBLuBgZX:-NF87mGn5udEqBLuBgZY:b-a136wy) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L11)):*
> ```objc
> int get_norm_path(const char* path, char* buf, size_t* inout_size);
> 
> int get_base_name(const char* path, char* buf, size_t* inout_size);
> ```

Please check all callers of this func and add `unix_to_pal_error()` in PAL code if needed, and remove `pal_to_unix_error()` in LibOS code.
___
*[`pal/regression/normalize_path.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF869LD4g2rLXyY2GQL:-NF869LD4g2rLXyY2GQM:bfsq9mn) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/regression/normalize_path.c#L54)):*
> ```C
> 
>         if (ret < 0) {
>             print_err(func_name, i, "failed with error: %d\n", ret);
> ```

Here `ret` should be wrapped into `unix_to_pal_error()`
___
*[`pal/src/host/linux/pal_files.c` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87KKW8AHuKhSQpHra:-NF87KKW8AHuKhSQpHrb:b-hii458) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux/pal_files.c#L63)):*
> ```C
>         free(hdl);
>         free(path);
>         return ret;
> ```

`unix_to_pal_error`
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 720 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87QEp10VtNRh5NU54:-NF87QEp10VtNRh5NU55:bcnb3dg) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/enclave_framework.c#L720)):*
> ```C
>     size_t norm_path_size = norm_uri_size - URI_PREFIX_FILE_LEN;
>     ret = get_norm_path(uri + URI_PREFIX_FILE_LEN, norm_uri + URI_PREFIX_FILE_LEN, &norm_path_size);
>     if (ret < 0) {
> ```

    if (ret < 0) {
        ret = unix_to_pal_error(ret);
        log_error("Path (%s) normalization failed: %s", uri, pal_strerror(ret));
        goto out;
    }
___
*[`pal/src/host/linux-sgx/pal_files.c` line 53 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87cxL4h24wcQ7M45U:-NF87cxL4h24wcQ7M45V:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/pal_files.c#L53)):*
> ```C
> 
>     ret = get_norm_path(uri, normpath, &normpath_size);
>     if (ret < 0) {
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 399 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87eR84fVrdxkGCYw3:-NF87eR90NvXOXRy1wOD:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/pal_files.c#L399)):*
> ```C
>     }
>     ret = get_norm_path(uri, path, &path_size);
>     if (ret < 0) {
> ```

ditto
___
*[`common/src/string/util.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF86koXAdet5VIc_IQb:-NF86koXAdet5VIc_IQc:bi2vdwx) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/src/string/util.c#L64)):*
> ```C
> 
>     return !memcmp(&str[str_len - suffix_len], suffix, suffix_len);
> }
> ```

I would move `strstartswith()` and `strendswith()` into the non-libc (`string_utils.c`) part.


<!-- Sent from Reviewable.io -->

2022-10-24 10:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/include/path_utils.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87vJ616VTWd0d4Nur:-NF8NZ2k4XP_rKbPyhXJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please check all callers of this func and add `unix_to_pal_error()` in PAL code if needed, and remove `pal_to_unix_error()` in LibOS code.
</blockquote></details>

Done.
___
*[`common/include/path_utils.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87mGn5udEqBLuBgZX:-NF8NZIz2MSGqsozOnln:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please check all callers of this func and add `unix_to_pal_error()` in PAL code if needed, and remove `pal_to_unix_error()` in LibOS code.
</blockquote></details>

Done.
___
*[`pal/regression/normalize_path.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF869LD4g2rLXyY2GQL:-NF8NoGx-UCTXxbYqf6V:b1akxu5) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/regression/normalize_path.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here `ret` should be wrapped into `unix_to_pal_error()`
</blockquote></details>

Currently, `unix_to_pal_error()` is a static function defined separately for [`host/linux`](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux/pal_linux_error.h#L62) and [`host/linux-sgx`](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_linux_error.h#L62).

To wrap the `ret` here we need several changes e.g., to make `unix_to_pal_error()` non-static, to avoid colliding definitions, to adjus the meson build file etc. However, it's purely for the functional testing of these two common functions though put in `pal/regression` but whose outputs are unix errors (and we simply check the case of `ret < 0`). Do we really want to do this?
___
*[`pal/src/host/linux/pal_files.c` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87KKW8AHuKhSQpHra:-NF8MatB8tuThgorwgUG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux/pal_files.c#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`unix_to_pal_error`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 720 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87QEp10VtNRh5NU54:-NF8MljXDG08L2VJuqJg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/enclave_framework.c#L720)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

    if (ret < 0) {
        ret = unix_to_pal_error(ret);
        log_error("Path (%s) normalization failed: %s", uri, pal_strerror(ret));
        goto out;
    }

</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 53 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87cxL4h24wcQ7M45U:-NF8MrurEgGixgtyV83M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/pal_files.c#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 399 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87eR84fVrdxkGCYw3:-NF8Mw889W0eKOwKHXTR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/src/host/linux-sgx/pal_files.c#L399)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`common/src/string/util.c` line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF86koXAdet5VIc_IQb:-NF8BS_S0uT9TJtLZTvY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/src/string/util.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move `strstartswith()` and `strendswith()` into the non-libc (`string_utils.c`) part.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-24 11:00 UTC, dimakuv requested changes
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/include/path_utils.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87vJ616VTWd0d4Nur:-NF8dQiI7euMQ8neNQw_:b-gmfrbd) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you really check all callers of this func? I was expecting more places.
___
*[`common/include/path_utils.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87mGn5udEqBLuBgZX:-NF8dWcv5rt71bCdm0Or:b-gmfrbd) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L11)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you really check all callers of this func? I was expecting more places.
___
*[`pal/regression/normalize_path.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF869LD4g2rLXyY2GQL:-NF8dBgu7HRVrI1OxbpA:bz8nlov) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/pal/regression/normalize_path.c#L54)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Currently, `unix_to_pal_error()` is a static function defined separately for [`host/linux`](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux/pal_linux_error.h#L62) and [`host/linux-sgx`](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_linux_error.h#L62).

To wrap the `ret` here we need several changes e.g., to make `unix_to_pal_error()` non-static, to avoid colliding definitions, to adjus the meson build file etc. However, it's purely for the functional testing of these two common functions though put in `pal/regression` but whose outputs are unix errors (and we simply check the case of `ret < 0`). Do we really want to do this?
</blockquote></details>

Ok, fair enough, too much hussle. I unblock. Let's not do it in this PAL test.
___
*[`pal/regression/normalize_path.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF8daw4ASRtXBY37QIg:-NF8daw4ASRtXBY37QIh:bam3pz7) ([raw file](https://github.com/gramineproject/gramine/blob/e767fce7c403cfc0853937c79ecc7f7dc307198e/pal/regression/normalize_path.c#L54)):*
> ```C
> 
>         if (ret < 0) {
>             print_err(func_name, i, "failed with error: %d\n", ret);
> ```

Can you add a more specific: `failed with UNIX error: %d`


<!-- Sent from Reviewable.io -->

2022-10-24 11:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: 28 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/include/path_utils.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87vJ616VTWd0d4Nur:-NF8gaPJE72Fbu0ToLcY:b2cjvj0) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L9)):*
Yes, unless I missed sth. Pls kindly see below.

> kailun@kailun-dev:~/workspace/dev/gramine$ grep -riH get_norm_path
> // NOT RELEVANT
> common/src/path_utils.c:int get_norm_path(const char* path, char* buf, size_t* inout_size) {
> common/include/path_utils.h:int get_norm_path(const char* path, char* buf, size_t* inout_size);
>  
> **// CALLERS
> libos/src/fs/libos_fs_encrypted.c:    ret = get_norm_path(path, normpath, &normpath_size);
> libos/src/fs/libos_fs_encrypted.c:    ret = get_norm_path(new_path, new_normpath, &new_normpath_size);**
> 
> // NOT RELEVANT
> pal/regression/normalize_path.c:static const char* get_norm_path_cases[][2] = {
> pal/regression/normalize_path.c:    cases        = get_norm_path_cases;
> pal/regression/normalize_path.c:    cases_len    = ARRAY_SIZE(get_norm_path_cases);
> pal/regression/normalize_path.c:    func_to_test = get_norm_path;
> pal/regression/normalize_path.c:    func_name = "get_norm_path";
> 
> **// CALLERS
> pal/src/host/linux/pal_files.c:    ret = get_norm_path(uri, path, &uri_size);
> pal/src/host/linux-sgx/enclave_framework.c:    ret = get_norm_path(uri + URI_PREFIX_FILE_LEN, norm_uri + URI_PREFIX_FILE_LEN, &norm_path_size);
> pal/src/host/linux-sgx/pal_files.c:    ret = get_norm_path(uri, normpath, &normpath_size);
> pal/src/host/linux-sgx/pal_files.c:    ret = get_norm_path(uri, path, &path_size);**
___
*[`common/include/path_utils.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87mGn5udEqBLuBgZX:-NF8gp2X2gkV6xc6Jv-7:b-696mb) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L11)):*
Yes, unless I missed sth. Pls kindly see below.

> kailun@kailun-dev:~/workspace/dev/gramine$ grep -riH get_base_name
// ALL NOT RELEVANT
common/src/path_utils.c:int get_base_name(const char* path, char* buf, size_t* inout_size) {
common/include/path_utils.h:int get_base_name(const char* path, char* buf, size_t* inout_size);
pal/regression/normalize_path.c:static const char* get_base_name_cases[][2] = {
pal/regression/normalize_path.c:    cases        = get_base_name_cases;
pal/regression/normalize_path.c:    cases_len    = ARRAY_SIZE(get_base_name_cases);
pal/regression/normalize_path.c:    func_to_test = get_base_name;
pal/regression/normalize_path.c:    func_name = "get_base_name";
___
*[`pal/regression/normalize_path.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF8daw4ASRtXBY37QIg:-NF8h3wX7ip695eI7i9n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e767fce7c403cfc0853937c79ecc7f7dc307198e/pal/regression/normalize_path.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a more specific: `failed with UNIX error: %d`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-24 12:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`common/include/path_utils.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87vJ616VTWd0d4Nur:-NF9-pRZ6f72hbcjmozm:b-m8lf4w) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, unless I missed sth. Pls kindly see below.

> kailun@kailun-dev:~/workspace/dev/gramine$ grep -riH get_norm_path
> // NOT RELEVANT
> common/src/path_utils.c:int get_norm_path(const char* path, char* buf, size_t* inout_size) {
> common/include/path_utils.h:int get_norm_path(const char* path, char* buf, size_t* inout_size);
>  
> **// CALLERS
> libos/src/fs/libos_fs_encrypted.c:    ret = get_norm_path(path, normpath, &normpath_size);
> libos/src/fs/libos_fs_encrypted.c:    ret = get_norm_path(new_path, new_normpath, &new_normpath_size);**
> 
> // NOT RELEVANT
> pal/regression/normalize_path.c:static const char* get_norm_path_cases[][2] = {
> pal/regression/normalize_path.c:    cases        = get_norm_path_cases;
> pal/regression/normalize_path.c:    cases_len    = ARRAY_SIZE(get_norm_path_cases);
> pal/regression/normalize_path.c:    func_to_test = get_norm_path;
> pal/regression/normalize_path.c:    func_name = "get_norm_path";
> 
> **// CALLERS
> pal/src/host/linux/pal_files.c:    ret = get_norm_path(uri, path, &uri_size);
> pal/src/host/linux-sgx/enclave_framework.c:    ret = get_norm_path(uri + URI_PREFIX_FILE_LEN, norm_uri + URI_PREFIX_FILE_LEN, &norm_path_size);
> pal/src/host/linux-sgx/pal_files.c:    ret = get_norm_path(uri, normpath, &normpath_size);
> pal/src/host/linux-sgx/pal_files.c:    ret = get_norm_path(uri, path, &path_size);**

</blockquote></details>

Ok, good, thanks for double-checking.
___
*[`common/include/path_utils.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1002#-NF87mGn5udEqBLuBgZX:-NF9-sAJ8k5QUubSNXkF:b-m8lf4w) ([raw file](https://github.com/gramineproject/gramine/blob/ad0dd28fe6c89f2e94736db02fd8ea72ec15fb98/common/include/path_utils.h#L11)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, unless I missed sth. Pls kindly see below.

> kailun@kailun-dev:~/workspace/dev/gramine$ grep -riH get_base_name
// ALL NOT RELEVANT
common/src/path_utils.c:int get_base_name(const char* path, char* buf, size_t* inout_size) {
common/include/path_utils.h:int get_base_name(const char* path, char* buf, size_t* inout_size);
pal/regression/normalize_path.c:static const char* get_base_name_cases[][2] = {
pal/regression/normalize_path.c:    cases        = get_base_name_cases;
pal/regression/normalize_path.c:    cases_len    = ARRAY_SIZE(get_base_name_cases);
pal/regression/normalize_path.c:    func_to_test = get_base_name;
pal/regression/normalize_path.c:    func_name = "get_base_name";

</blockquote></details>

Ok, good, thanks for double-checking.


<!-- Sent from Reviewable.io -->

2022-10-25 01:45 UTC, boryspoplawski requested changes
> Reviewed 7 of 21 files at r4, 4 of 17 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/src/meson.build` line 38 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBhYAG8XPz4taOG_1f:-NFBhYAG8XPz4taOG_1g:bk696k0) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L38)):*
> ```Meson
> common_src_internal += common_src_arch
> 
> common_dep_utils = declare_dependency(
> ```

`_dep` should be a suffix
ditto all other places
___
*[`common/src/meson.build` line 83 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBd3p94oWmBbFD5sPs:-NFBd3pA5-sH85fg8y9t:b7plyxk) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L83)):*
> ```Meson
> )
> 
> common_dep = declare_dependency(
> ```

Why there are so many dependencies and sources list in here now? It was supposed to be two dependencies (and two sources lists, each for one dep)
___
*[`libos/src/libos_init.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBlZ6d3lnRLAPCKNGS:-NFBlZ6d3lnRLAPCKNGT:b-glnuhv) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/libos/src/libos_init.c#L28)):*
> ```C
> #include "pal.h"
> #include "pal_error.h"
> #include "string_utils.h"
> ```

Please include this in `api.h` and revert all these includes here.
`string_utils.h` does not provide all string related utilities, only a few (a pretty random subset).
___
*[`common/src/path_utils.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBcl9yC9oJ6IwskNYN:-NFBcl9yC9oJ6IwskNYO:bmon0xu) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L16)):*
> ```C
> #endif
> 
> #include <errno.h>
> ```

This file should not be included in core Gramine. Use `asm/errno.h` instead
___
*[`common/src/path_utils.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBjziI3pSFw6B0Z-1V:-NFBjziI3pSFw6B0Z-1W:b2nyiqv) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L16)):*
> ```C
> #endif
> 
> #include <errno.h>
> ```

Please move standard headers above the `ifdef`
___
*[`common/src/path_utils.c` line 72 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBg6E05ReH9TLR8cPq:-NFBg6E05ReH9TLR8cPr:b-3zl1e1) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L72)):*
> ```C
>     size_t size = *inout_size;
>     if (!size) {
>         return -EINVAL;
> ```

Hm, should we use Linux error codes in common code? How would those be translated on non-Linux PALs?
___
*[`common/src/string_utils.c` line 2 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBjlSlCqM4K3I6txJu:-NFBjlSlCqM4K3I6txJv:b-qftlnm) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2022 Intel Corporation
> ```

I don't think this copyright is correct, this code was just moved from other files.
ditto whole PR
___
*[`common/src/string_utils.c` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBnKBX9nP_FCOKSmar:-NFBnKBX9nP_FCOKSmas:b-pucexy) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L5)):*
> ```C
>  *                    Kailun Qin <kailun.qin@intel.com>
>  */
> ```

If you move functions between files, please change their order as little as possible - it's easier to review with fewer changes, since we have to diff manually, not in reviewable
___
*[`common/src/string_utils.c` line 12 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBk31i5nV9pwvgbwcp:-NFBk31i5nV9pwvgbwcq:b2nyiqv) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L12)):*
> ```C
> #endif
> 
> #include <stdint.h>
> ```

Please move standard headers above the `ifdef`
___
*[`common/src/string_utils.c` line 43 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBkfQk8xPwJASXgZru:-NFBkfQk8xPwJASXgZrv:b-nwmkzx) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L43)):*
> ```C
> 
>     uint64_t value = 0;
>     if (__builtin_add_overflow(size, 0, &value))
> ```

The original version had a nice feature of checking that `size` in fact does not overflow the type of `out_val` - now types of `value` and `out_val` must match for it to work.
I guess the prerequisite to this PR should have been splitting `api.h` into two files, e.g. common `utils.h` and `gramine_utils.h` with Gramine dependent stuff. Too late now, I guess


<!-- Sent from Reviewable.io -->

2022-10-25 02:04 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 (`fdatasync` failed, known issue)

2022-10-25 02:05 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 please (fdatasync failed, known issue)

2022-10-25 02:05 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (`fdatasync` failed, known issue)

2022-10-25 06:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/meson.build` line 38 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBhYAG8XPz4taOG_1f:-NFCb0wIDQf-G3cUX1rl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`_dep` should be a suffix
ditto all other places
</blockquote></details>

Done.
___
*[`common/src/meson.build` line 83 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBd3p94oWmBbFD5sPs:-NFCivUi4y5n6hIz0jB-:b-tbjiyg) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why there are so many dependencies and sources list in here now? It was supposed to be two dependencies (and two sources lists, each for one dep)
</blockquote></details>

The original intention was to have clearer separation and to support use them separately or in a compositional manner.

For example, `utils_dep` is relatively independent, `libc_dep` (which provides exactly libc APIs) only depends on `utils_dep` while`internal_dep` is kind of misc which may require more stuff. This may help with using/importing them separately. `san_dep` is for avoiding adding the same sanitizer related sources into the separate (two or more) deps multiple times, otherwise for instance if we depend on both `utils_dep` and `libc_dep` somewhere, then the meson build will fail. This gives some more flexibility, e.g., if we want to import `utils_dep` somewhere w/ sanitizers enabled, then only with two dependencies leads us to import all internal stuff etc.

Anyway, I'm open to the alternatives.
___
*[`libos/src/libos_init.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBlZ6d3lnRLAPCKNGS:-NFCiIy4-2R4QrTwU29a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/libos/src/libos_init.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please include this in `api.h` and revert all these includes here.
`string_utils.h` does not provide all string related utilities, only a few (a pretty random subset).
</blockquote></details>

Done.
___
*[`common/src/path_utils.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBcl9yC9oJ6IwskNYN:-NFCbbQABTIpoVEEfDkh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file should not be included in core Gramine. Use `asm/errno.h` instead
</blockquote></details>

Done.
___
*[`common/src/path_utils.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBjziI3pSFw6B0Z-1V:-NFCbfLF-1IGvAE0NL-Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move standard headers above the `ifdef`
</blockquote></details>

Done.
___
*[`common/src/path_utils.c` line 72 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBg6E05ReH9TLR8cPq:-NFCj6_-AIHTThAGg301:b-8jp4g4) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, should we use Linux error codes in common code? How would those be translated on non-Linux PALs?
</blockquote></details>

I think it's fine to use them in common. For translation, helper functions are usually available anyway. The other way is to simply remove error codes and just return 0 and -1.
___
*[`common/src/string_utils.c` line 2 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBjlSlCqM4K3I6txJu:-NFCgNek54ioFJHv1Wfc:bu4918c) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think this copyright is correct, this code was just moved from other files.
ditto whole PR
</blockquote></details>

I reverted and merged the copyrights from the original files.
___
*[`common/src/string_utils.c` line 12 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBk31i5nV9pwvgbwcp:-NFCcYonA5vb1-QTivxa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move standard headers above the `ifdef`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 08:24 UTC, dimakuv requested changes
> Reviewed 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/meson.build` line 83 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBd3p94oWmBbFD5sPs:-NFDAZq34m_ACXKAkOHV:bcwlke4) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L83)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The original intention was to have clearer separation and to support use them separately or in a compositional manner.

For example, `utils_dep` is relatively independent, `libc_dep` (which provides exactly libc APIs) only depends on `utils_dep` while`internal_dep` is kind of misc which may require more stuff. This may help with using/importing them separately. `san_dep` is for avoiding adding the same sanitizer related sources into the separate (two or more) deps multiple times, otherwise for instance if we depend on both `utils_dep` and `libc_dep` somewhere, then the meson build will fail. This gives some more flexibility, e.g., if we want to import `utils_dep` somewhere w/ sanitizers enabled, then only with two dependencies leads us to import all internal stuff etc.

Anyway, I'm open to the alternatives.
</blockquote></details>

Kailun is correct, but let me summarize it in my own way too.

We now have three main deps instead of one:
1. `common_libc_dep` -- contains only libc functions
2. `common_internal_dep` -- contains Gramine helper functions, not libc, but also not useful for non-Gramine programs (like `pf_crypt`)
3. `common_utils_dep` -- contains common helper functions, not libc, also useful for non-Gramine programs (like `pf_crypt`)

Initially, the request was to split only into items 1 and 3. But then we immediately hit the problem -- we have e.g. `toml_utils.c`, which doesn't fit any of 1 or 3:
- `toml_utils.c` has convinience wrappers around TOML functions from the `tomlc` library,
- it is clearly not part of libc,
- if it would go into `common_utils_dep`, then it would require to link against the `tomlc` library -- which is meaningless and ugly

So it was decided to introduce an "intermediate" dependency 2.

About sanitizers: this is purely for convinience and uniformity with the rest of the new code, as Kailun explained (I mean, we could figure out how to add sanitizers sources to one of the three deps, but making sanitizers a separate dependency makes it clean.)
___
*[`libos/src/libos_init.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBlZ6d3lnRLAPCKNGS:-NFDDmEo17sddgQjVSfL:b3yp3s4) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/libos/src/libos_init.c#L28)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@boryspoplawski But why reverting? One of the side-effects of this PR was to unclutter `api.h`, by splitting it into more and more files, with each next PR. At least that what was one of my goals. I actually liked that we started having more meaningful names for headers, and in some future we'll be able to remove this monstrosity `api.h`.

In a similar vein, we could say that `pal_error.h` and `toml_utils.h` and what-not also belong to `api.h`, so let's stash all of them in there and have nice-and-small include lists... I'm opposed to this.

And even if we're keeping everything in one `api.h` for now -- then we should also stash `path_utils.h` in there.
___
*[`common/src/path_utils.c` line 72 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBg6E05ReH9TLR8cPq:-NFDC7HmBxE_Ky-bZQIg:b5e4vzj) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L72)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think it's fine to use them in common. For translation, helper functions are usually available anyway. The other way is to simply remove error codes and just return 0 and -1.
</blockquote></details>

Yes, so this is an awkard one. For example, this `get_norm_path()` is intended for use in both Gramine code and non-Gramine (normal Linux apps like `pf_crypt`) code. The two cases have opposite ideas about error codes: Gramine technically should always use PAL error codes, but normal Linux apps should always use UNIX error codes.

As Kailun mentioned, another alternative is to simplify the error codes to `0` on success, and `-1` on error. Or introduce `#ifdef USE_STDLIB`, and choose the error code format at build time... @boryspoplawski What do you recommend?
___
*[`common/src/string_utils.c` line 43 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBkfQk8xPwJASXgZru:-NFDD300APF41D8QlpWe:b-m4ryft) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The original version had a nice feature of checking that `size` in fact does not overflow the type of `out_val` - now types of `value` and `out_val` must match for it to work.
I guess the prerequisite to this PR should have been splitting `api.h` into two files, e.g. common `utils.h` and `gramine_utils.h` with Gramine dependent stuff. Too late now, I guess
</blockquote></details>

Well, the idea of this PR was to start slow and with moving some specific functions. We have this problem of a kitchen-sink `api.h` for ages, and every (theoretical) attempt at splitting this header into several always failed, exactly because nobody saw where to start.

Even with this PR, the minimal task of splitting a couple string-related functions turned into a complicated matter. Let's do it slowly, one thing at a time...


<!-- Sent from Reviewable.io -->

2022-10-25 13:36 UTC, boryspoplawski requested changes
> Reviewed 2 of 17 files at r5, 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`common/src/meson.build` line 83 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBd3p94oWmBbFD5sPs:-NFEHfPc4E2UduxB4nAG:b-ajx8uu) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Kailun is correct, but let me summarize it in my own way too.

We now have three main deps instead of one:
1. `common_libc_dep` -- contains only libc functions
2. `common_internal_dep` -- contains Gramine helper functions, not libc, but also not useful for non-Gramine programs (like `pf_crypt`)
3. `common_utils_dep` -- contains common helper functions, not libc, also useful for non-Gramine programs (like `pf_crypt`)

Initially, the request was to split only into items 1 and 3. But then we immediately hit the problem -- we have e.g. `toml_utils.c`, which doesn't fit any of 1 or 3:
- `toml_utils.c` has convinience wrappers around TOML functions from the `tomlc` library,
- it is clearly not part of libc,
- if it would go into `common_utils_dep`, then it would require to link against the `tomlc` library -- which is meaningless and ugly

So it was decided to introduce an "intermediate" dependency 2.

About sanitizers: this is purely for convinience and uniformity with the rest of the new code, as Kailun explained (I mean, we could figure out how to add sanitizers sources to one of the three deps, but making sanitizers a separate dependency makes it clean.)
</blockquote></details>

What's wrong with having only 2 and 3 from this list? What is the place in Gramine you need to use 1 and cannot use 2?
___
*[`libos/src/libos_init.c` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBlZ6d3lnRLAPCKNGS:-NFEJ9-Y4qbDaSAnUkmr:b25ayx4) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/libos/src/libos_init.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski But why reverting? One of the side-effects of this PR was to unclutter `api.h`, by splitting it into more and more files, with each next PR. At least that what was one of my goals. I actually liked that we started having more meaningful names for headers, and in some future we'll be able to remove this monstrosity `api.h`.

In a similar vein, we could say that `pal_error.h` and `toml_utils.h` and what-not also belong to `api.h`, so let's stash all of them in there and have nice-and-small include lists... I'm opposed to this.

And even if we're keeping everything in one `api.h` for now -- then we should also stash `path_utils.h` in there.
</blockquote></details>

The problem is that `string_utils.h` are not really, well, string utils. If we moved **all** of the string util functions to that header, I would be more than fine with such change.

I guess we have to talk about this `api.h` split in issues or on some Gramine meeting.
___
*[`common/src/path_utils.c` line 72 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBg6E05ReH9TLR8cPq:-NFEEWTv6LLGsLPsgjq5:b-dnygg9) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L72)):*
> For translation, helper functions are usually available anyway.

Not sure on what this is based, we don't have any non-Linux PALs atm and I don't see a reason why would they handle UNIX error codes.

> Or introduce #ifdef USE_STDLIB, and choose the error code format at build time...

No `ifdef`s please. If you share code between different OSes, you usually introduce custom error codes, but it doesn't make sense to do so for 2 functions.

>  @boryspoplawski What do you recommend?

I guess just returning `bool` with success/failure is the easiest option. `int` with `0`, `-1` is another, but then call sites will miss that it does not return error code and pass that `-1` on failures, which could be weird when debugging.
___
*[`common/src/path_utils.c` line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEDYuG-Uk6OxBPEGc1:-NFEDYuG-Uk6OxBPEGc2:b-48peir) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/path_utils.c#L12)):*
> ```C
> #include <stddef.h>
> 
> #include "path_utils.h"
> ```

But this one is not standard, it was good before :)
___
*[`common/src/string_utils.c` line 43 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBkfQk8xPwJASXgZru:-NFEFgwp4Qz0DZQFu7J_:b-s27dcr) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/string_utils.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, the idea of this PR was to start slow and with moving some specific functions. We have this problem of a kitchen-sink `api.h` for ages, and every (theoretical) attempt at splitting this header into several always failed, exactly because nobody saw where to start.

Even with this PR, the minimal task of splitting a couple string-related functions turned into a complicated matter. Let's do it slowly, one thing at a time...
</blockquote></details>

I disagree. Splitting `api.h` doesn't sound complicated (and I've never tried it). The problem is that this PR introduces multiple headers, which I'm not sure we want - one small dumpster for utils is imo fine (as long as they are really standalone utils not related to the rest of the codebase).
Also the core of split is in `meson.build`, which is introduced in **this** PR, so the future split of `api.h` will have to follow and adhere to changes made here (or overwrite them).

I'm not opposing merging this one, but I think we started from a wrong place and it's hard for me to reason about splits made in this PR, without seeing other changes (mostly `api.h` split).
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFEFZVwBa_M700IQG41:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
> ```C
> #include <stddef.h>
> 
> #include "string_utils.h"
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-10-26 06:56 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/meson.build` line 83 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBd3p94oWmBbFD5sPs:-NFI3E2-2SQ1r06KmIjd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/meson.build#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. As discussed in the Gramine meeting, we should go with 2 and 3. In particular, we do **not** limit ourselves to "libc functions" vs "non-libc functions". Instead, we just have "gramine-specific" functions and "non-gramine-specific" functions. Basically, these are `common_internal_dep` (that includes libc funcs) and `common_utils_dep`.

Similarly, sanitizers do **not** need to be a separate dependency, and they should be merge into `common_internal_dep`.
</blockquote></details>

Done.
___
*[`common/src/path_utils.c` line 72 at r6](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFBg6E05ReH9TLR8cPq:-NFI3Hkc7ViKasYlDvV3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b18d20f9b018abd2bc6bf1a9f3c3a497385fb1f4/common/src/path_utils.c#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I agree with returning `bool`. @kailun-qin Could you change to `bool`?
</blockquote></details>

Done.
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFI3JJK1cXNNNjonKL6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-26 07:49 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[`common/include/path_utils.h` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIFXFO7qAJiOBrF8Zq:-NFIFXFO7qAJiOBrF8Zr:b6vyqim) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/include/path_utils.h#L3)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University */
> ```

We forgot to add `#pragma once` here
___
*[`common/src/meson.build` line 11 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIEbYZ5dMBL6aqIK9q:-NFIEbYZ5dMBL6aqIK9r:b97bcjv) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/src/meson.build#L11)):*
> ```Meson
>     'location.c',
>     'network/hton.c',
>     'printf.c',
> ```

This is not sorted.
___
*[`common/include/string_utils.h` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIFZl253VC-uXdxS5P:-NFIFZl253VC-uXdxS5Q:b6vyqim) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/include/string_utils.h#L3)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University */
> ```

We forgot to add `#pragma once` here
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFIFGJsDMzCPW4gpVXZ:b-bdep7p) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why did you remove the header? It should be here, otherwise in non-Gramine programs (where we have `USE_STDLIB`), this won't compile -- gcc will complain about "no previous declarations of these two functions".


<!-- Sent from Reviewable.io -->

2022-10-26 08:06 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/include/path_utils.h` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIFXFO7qAJiOBrF8Zq:-NFIIqjS8YCMDec1IXVk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/include/path_utils.h#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We forgot to add `#pragma once` here
</blockquote></details>

Done.
___
*[`common/src/meson.build` line 11 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIEbYZ5dMBL6aqIK9q:-NFIIstU6vkYRgZswU1D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/src/meson.build#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not sorted.
</blockquote></details>

Done.
___
*[`common/include/string_utils.h` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFIFZl253VC-uXdxS5P:-NFIIs609ODNlbC_1lc1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c5b98358fff64a9d157736ac38177d4876b5d3e9/common/include/string_utils.h#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We forgot to add `#pragma once` here
</blockquote></details>

Done.
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFIIuzcAzzy3s8Fnrqv:b-yg79oe) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove the header? It should be here, otherwise in non-Gramine programs (where we have `USE_STDLIB`), this won't compile -- gcc will complain about "no previous declarations of these two functions".
</blockquote></details>

Ah, yes, we need this. (Just saw borys's comment above and thought I missed one...)


<!-- Sent from Reviewable.io -->

2022-10-26 08:37 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-10-26 08:37 UTC, dimakuv commented
Jenkins, test this please

2022-10-26 16:57 UTC, boryspoplawski requested changes
> Reviewed 6 of 9 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/src/meson.build` line 59 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFK5e03EP9geYCymUhP:-NFK5e03EP9geYCymUhQ:b-jw62gy) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/meson.build#L59)):*
> ```Meson
> )
> 
> common_dep = declare_dependency(
> ```

Why `common_dep != common_internal_dep`?
___
*[`common/src/path_utils.c` line 2 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFK8bWc8lfaHKZCIIlI:-NFK8bWc8lfaHKZCIIlJ:b-f13pll) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/path_utils.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University */
> ```

I did some git archeology:
- `is_dot_or_dotdot` was introduced in https://github.com/gramineproject/graphene/pull/840
- rest was introduced in https://github.com/gramineproject/graphene/pull/894

So we should change it to:



_Suggestion:_
```C
/* Copyright (C) 2019 Invisible Things Lab
 *                    Borys Popławski <borysp@invisiblethingslab.com>
 */
```
___
*[`common/src/string_utils.c` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFKAPC77tYrVFbgkohi:-NFKAPC77tYrVFbgkohj:bf68ba9) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/string_utils.c#L9)):*
> ```C
>  * Copyright (C) 2020 Intel Corporation
>  *                    Vijay Dhanraj <vijay.dhanraj@intel.com>
>  */
> ```

Here I've also did some digging and this code originates and was rewritten by following entities: 



_Suggestion:_
```C
/* Copyright (C) 2014 Stony Brook University
 * Copyright (C) 2020 Invisible Things Lab
 *                    Michał Kowalczyk <mkow@invisiblethingslab.com>
 *                    Paweł Marczewski <pawel@invisiblethingslab.com>
 * Copyright (C) 2020 Intel Corporation
 */
```


<!-- Sent from Reviewable.io -->

2022-10-27 01:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: 25 of 32 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/meson.build` line 59 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFK5e03EP9geYCymUhP:-NFM64JZ92L6FmpEql9r:b-ozqavu) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/meson.build#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `common_dep != common_internal_dep`?
</blockquote></details>

I was trying to make `common_dep` = `common_internal_dep` + `common_utils_dep` + misc_deps (`uthash_dep` etc.). Anyway, I removed `common_dep` and switched all to `common_internal_dep` now.
___
*[`common/src/path_utils.c` line 2 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFK8bWc8lfaHKZCIIlI:-NFM6Qwz2loaZ3kUZYFR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/path_utils.c#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did some git archeology:
- `is_dot_or_dotdot` was introduced in https://github.com/gramineproject/graphene/pull/840
- rest was introduced in https://github.com/gramineproject/graphene/pull/894

So we should change it to:
</blockquote></details>

Done.
___
*[`common/src/string_utils.c` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFKAPC77tYrVFbgkohi:-NFM6bCF4a1QfftbE6Hg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/string_utils.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Here I've also did some digging and this code originates and was rewritten by following entities: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-27 07:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: 27 of 32 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/src/meson.build` line 59 at r9](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFK5e03EP9geYCymUhP:-NFNNLGF17wXaUHMIkQ-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0501e31ec54fca3882e67f6648b04ec460ad88e/common/src/meson.build#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's use the name `common_dep`. I see no reason to introduce a longer `common_internal_dep`.

So please rename `common_internal_dep` -> `common_dep` in the current revision; this will allow to revert some other meson.build file changes that you introduced.
</blockquote></details>

Done.
___
*[`libos/src/meson.build` line 171 at r10](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFNJVuvBhWHqK18_yAr:-NFNNPWyCmQ7XzGPkI2q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d704418c3eb11a957c990f43c10ba195069a6e76/libos/src/meson.build#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be reverted, see my other comment
</blockquote></details>

Done.
___
*[`pal/regression/meson.build` line 118 at r10](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFNJYSk2XeoD59-OD-r:-NFNNQ991nTsyf3Ue4tz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d704418c3eb11a957c990f43c10ba195069a6e76/pal/regression/meson.build#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be reverted, see my other comment
</blockquote></details>

Done.
___
*[`pal/src/host/linux/meson.build` line 75 at r10](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFNJZOIC7lFkOwrqUOf:-NFNNQhT4aHd1Vrdgq6i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d704418c3eb11a957c990f43c10ba195069a6e76/pal/src/host/linux/meson.build#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be reverted, see my other comment
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/meson.build` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFNJ_8eApSdMp4nUkt2:-NFNNR_SC4pF9wTvZ3mP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d704418c3eb11a957c990f43c10ba195069a6e76/pal/src/host/linux-sgx/meson.build#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be reverted, see my other comment
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/meson.build` line 162 at r10](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFNJ_XaCYK_WGyOgPGa:-NFNNS2B1_4ETt2q4JbY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d704418c3eb11a957c990f43c10ba195069a6e76/pal/src/host/linux-sgx/meson.build#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be reverted, see my other comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-27 07:54 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-10-27 10:53 UTC, boryspoplawski requested changes
> Reviewed 2 of 7 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/path_utils.c` line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEDYuG-Uk6OxBPEGc1:-NFO3ULa77VileZmJ7gh:b2nhswy) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/path_utils.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Is this still relevant now?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2022-10-28 03:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/path_utils.c` line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEDYuG-Uk6OxBPEGc1:-NFRd0tiDouCyk6ETSKH:bfpvtpn) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/path_utils.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Any suggestion to address this? Thanks!


<!-- Sent from Reviewable.io -->

2022-10-28 14:26 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`common/src/path_utils.c` line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEDYuG-Uk6OxBPEGc1:-NFTyzy49RUrHf1muSmY:b2iomay) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/path_utils.c#L12)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Any suggestion to address this? Thanks!
</blockquote></details>

Move it below standard includes (below ifdef) where it was originally (when I asked you to move the standard ones, you also moved this one)
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFTzE9k5y6OKs4L2-Qn:b-nhqpc0) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Ah, yes, we need this. (Just saw borys's comment above and thought I missed one...)
</blockquote></details>

@kailun-qin same here


<!-- Sent from Reviewable.io -->

2022-10-28 15:21 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/src/path_utils.c` line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEDYuG-Uk6OxBPEGc1:-NFUAM5-CEgwSxXOddCz:bbzx6g8) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/path_utils.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Move it below standard includes (below ifdef) where it was originally (when I asked you to move the standard ones, you also moved this one)
</blockquote></details>

Ah, got your point now. Updated, thanks!
___
*[`common/src/string_utils.c` line 14 at r7](https://reviewable.io/reviews/gramineproject/gramine/1002#-NFEFZVwBa_M700IQG40:-NFUAUod7Y8EeJtGTOR2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b2b5ff8225814ce35f2c2c63fe626fe851d6348/common/src/string_utils.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@kailun-qin same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-28 15:32 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-31 07:56 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-31 15:45 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1002)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-01 09:35 UTC, merged