[LibOS,PAL] Extend DNS runtime configuration
gramineproject/gramine pull request #1005
Opened 2022-10-23 17:40 UTC by oshogbo

## Description of the changes 

This commits mocks the `/etc/hosts`.
On my Ubuntu 20.10 default values from `/etc/hosts` are:
```
127.0.0.1 localhost

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
On other machine:
```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

So we generate us many IPv6 entries as we can.
We also set a current hostname to point to 127.0.0.1.

## How to test this PR? 

Jenkins should be enough.

2022-10-24 09:45 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NF8Llhk11ojfjkVWT7-:bu69rvs) (no related file):*
I also have this line in my dev machine's `/etc/hosts`:
```
127.0.1.1   <myhostname>
```

See https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

I suggest we should add this line as well. Hm, or it won't make sense because `<hostname>` will be now mapped to both 127.0.0.1 and 127.0.1.1? Meh, please check what the official docs say about the format of this file.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8MzxwEtOgK1ONxlXm:-NF8MzxwEtOgK1ONxlXn:b-tjpx2y) (no related file):*
Do we want this PR? I am in favor of this, because doing the tricks [like here](https://github.com/gramineproject/gramine/pull/962/files) is annoying for manifest writers. @mkow @boryspoplawski 

If we continue with this PR, then we need to revert my changes to `CI-Examples/`, like in the link above (where I add a hard-coded `sgx.trusted_files = "file:helper-files/hosts"`). So @oshogbo please go through all CI-Examples and remove this trick.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8K6MvCm8YxIAuQIDa):*
Why `PAL`?

I suggest a one-liner (without commit body message):
```
[LibOS] Extend DNS runtime configuration with `/etc/hosts`
```
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8K4G-16huUExPxBrv):*
`configuration`

Anyway, I would actually remove this commit body message.
___
*[`libos/src/fs/etc/fs.c` line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8KbNK7WvaaPotiShu:-NF8KbNK7WvaaPotiShv:b-q6qtbo) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L138)):*
> ```C
>     __UNUSED(dent);
> 
>     int ret = 0;
> ```

`int ret;` (no initialization)
___
*[`libos/src/fs/etc/fs.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8KtWH5Y7lRWKiq2gn:-NF8KtWH5Y7lRWKiq2go:blzesb0) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L150)):*
> ```C
>     size += strlen(ipv4_hosts_value);
> 
>     size += strlen(ipv4_hosts_value);
> ```

Typo? Should be `ipv4_hostname`, if I understand correctly.
___
*[`libos/src/fs/etc/fs.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8LzWK6K5ORPMJ0gd6:-NF8LzWK6K5ORPMJ0gd7:b-5yz98t) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L164)):*
> ```C
>     char* ptr = data;
> 
>     ret = put_string(&ptr, &space_left, "%s", ipv4_hosts_value);
> ```

Can't you just have `127.0.0.1 localhost <myhostname>` version? Why split into two lines? Does that truly work? From what I've seen, you're expected to have `ip-address name1 name2 ...` on one line.


<!-- Sent from Reviewable.io -->

2022-10-24 13:44 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NF9CYVV8oqjUilZUSGr:b-4hb5x4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also have this line in my dev machine's `/etc/hosts`:
```
127.0.1.1   <myhostname>
```

See https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

I suggest we should add this line as well. Hm, or it won't make sense because `<hostname>` will be now mapped to both 127.0.0.1 and 127.0.1.1? Meh, please check what the official docs say about the format of this file.
</blockquote></details>

Yea it seems like a mess.
It's seems debian/ubuntu specific:
https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

Unix maps hostname to 127.0.0.1, but we are implementing Linux here. The question is which distro should we follow here? 

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8MzxwEtOgK1ONxlXm:-NF9Cq39C83lUs3iOd7a:b55mqfz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want this PR? I am in favor of this, because doing the tricks [like here](https://github.com/gramineproject/gramine/pull/962/files) is annoying for manifest writers. @mkow @boryspoplawski 

If we continue with this PR, then we need to revert my changes to `CI-Examples/`, like in the link above (where I add a hard-coded `sgx.trusted_files = "file:helper-files/hosts"`). So @oshogbo please go through all CI-Examples and remove this trick.
</blockquote></details>

Can this be a next PR?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8K6MvCm8YxIAuQIDa):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `PAL`?

I suggest a one-liner (without commit body message):
```
[LibOS] Extend DNS runtime configuration with `/etc/hosts`
```
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8K4G-16huUExPxBrv):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`configuration`

Anyway, I would actually remove this commit body message.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 138 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8KbNK7WvaaPotiShu:-NF9DNFC15aYL2BltNnL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L138)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`int ret;` (no initialization)
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8KtWH5Y7lRWKiq2gn:-NF9DRm08iB6ABc_CYJE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo? Should be `ipv4_hostname`, if I understand correctly.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8LzWK6K5ORPMJ0gd6:-NF9DSqMAZgQot_61XBv:buugsyh) ([raw file](https://github.com/gramineproject/gramine/blob/395001fe32544f147929413162ae3ff3cc81aaf2/libos/src/fs/etc/fs.c#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can't you just have `127.0.0.1 localhost <myhostname>` version? Why split into two lines? Does that truly work? From what I've seen, you're expected to have `ip-address name1 name2 ...` on one line.
</blockquote></details>

I have changed it `127.0.1.1`.


<!-- Sent from Reviewable.io -->

2022-10-24 13:59 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NF9H3gcCqyR9pRYHQtL:b4mzl2w) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yea it seems like a mess.
It's seems debian/ubuntu specific:
https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

Unix maps hostname to 127.0.0.1, but we are implementing Linux here. The question is which distro should we follow here? 
</blockquote></details>

I would lean towards Debian/Ubuntu, in the hope that other distros do not care about this additional `127.0.1.1` mapping. @woju ?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8MzxwEtOgK1ONxlXm:-NF9HG-k59S1Exeq8orp:b753hwa) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Can this be a next PR?
</blockquote></details>

Yes, but please mark as a TODO somewhere for yourself. Otherwise we'll forget.

___
___
*[`libos/src/fs/etc/fs.c` line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF9HR73EPTfD3m8Ge_C:-NF9HR73EPTfD3m8Ge_D:b-pkpjui) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/libos/src/fs/etc/fs.c#L141)):*
> ```C
>     size_t size = 0;
>     const char* ipv4_hosts_value = "127.0.0.1 localhost\n";
>     const char* ipv4_hostname = "127.0.1.1 ";
> ```

Please add a comment with a link to Debian/Ubuntu specific hack.


<!-- Sent from Reviewable.io -->

2022-10-24 22:58 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NFB5GjMAifkhsvEadjW:b-sielnx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would lean towards Debian/Ubuntu, in the hope that other distros do not care about this additional `127.0.1.1` mapping. @woju ?
</blockquote></details>

I would vote for just a simple `localhost` - `127.0.0.1` mapping without any additional stuff (not even ipv6) and making users able to overwrite this `/etc/hosts`.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8MzxwEtOgK1ONxlXm:-NFB6F6J2pyMUubmLLmx:b-b0y3d5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, but please mark as a TODO somewhere for yourself. Otherwise we'll forget.
</blockquote></details>

Why next PR? It it will take some time, I don't see a problem with waiting with merging this PR a bit

___
___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFB9p3m42H8zYSN6ABp:b-vuhilj) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
> ```reStructuredText
> - Hostname (obtained by apps via `nodename` field in `uname` syscall),
>   set to the host's hostname at initialization.
> - Pseudo-file ``/etc/hosts``, with defined `localhost` and IPv6 defaults.
> ```

Actually I don't like this - we have providing host `resolv.conf` and default `hosts` hidden behind one switch. This means that users which want host `resolv.conf` are force to use our provided `hosts` without ability to overwrite it (because this option has priority over fs.mounts).
___
*[`libos/src/fs/etc/fs.c` line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF9HR73EPTfD3m8Ge_C:-NFBCKuAB52XDZ4aGPcB:b-9j1qep) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/libos/src/fs/etc/fs.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment with a link to Debian/Ubuntu specific hack.
</blockquote></details>

It's not Debian specific, some other distros do similar stuff and some Ubuntu machines don't have it.
___
*[`libos/src/fs/etc/fs.c` line 202 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFBD1Ku5Y_5AkO-qIrc:-NFBD1Ku5Y_5AkO-qIrd:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/libos/src/fs/etc/fs.c#L202)):*
> ```C
>         return ret;
> 
>     return ret = mount_fs(&(struct libos_mount_params){
> ```





_Suggestion:_
```C
return mount_fs(
```


<!-- Sent from Reviewable.io -->

2022-10-24 23:00 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFBDKfT2-JpizwNYi59:-NFBDKfT2-JpizwNYi5A:bu6tgvr) (no related file):*
Most of the CI failed

___


<!-- Sent from Reviewable.io -->

2022-10-25 02:41 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NFByvCC53AnXS-zGShz:ba9wsgk) (no related file):*
> 127.0.1.1
This item seems to be a very very old trick On Ubuntu 14.04. I only find it on a Ubuntu 2204 dist-upgraded from 14.04.  It's not align with my current hostname because I changed it years ago.
Better to not add 127.0.1.1.

___


<!-- Sent from Reviewable.io -->

2022-10-25 07:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1005#-NF8Llhk11ojfjkVWT6z:-NFD7MC9CyZL_exh5ilp:b-5e90t1) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

> 127.0.1.1
This item seems to be a very very old trick On Ubuntu 14.04. I only find it on a Ubuntu 2204 dist-upgraded from 14.04.  It's not align with my current hostname because I changed it years ago.
Better to not add 127.0.1.1.
</blockquote></details>

This escalated quickly. I'm now leaning to rejecting this PR (as being too complicated, and letting users to add their own `/etc/hosts` files as is currently done in CI-Examples). @mkow @woju 

___
___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFD6Yh90s4rkiH38UAX:b8177k8) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually I don't like this - we have providing host `resolv.conf` and default `hosts` hidden behind one switch. This means that users which want host `resolv.conf` are force to use our provided `hosts` without ability to overwrite it (because this option has priority over fs.mounts).
</blockquote></details>

Yes, but I also don't see a simple way to have both these options (to use this PR by default but be able to overwrite `/etc/hosts`).

I don't like adding a new manifest option, as it is already pretty complicated for users... A new option will make it even more complicated.

On the other hand, introducing some ad-hoc behavior that *some* files under `/etc/` are shadowed by `sys.enable_extra_runtime_domain_names_conf` and *some are not* -- this is very unintuitive.

Well, maybe we just **don't need this PR**?


<!-- Sent from Reviewable.io -->

2022-10-25 08:49 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @oshogbo, and @woju)

___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFDHOUp3WJck_5u_jva:b4iod7b) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, but I also don't see a simple way to have both these options (to use this PR by default but be able to overwrite `/etc/hosts`).

I don't like adding a new manifest option, as it is already pretty complicated for users... A new option will make it even more complicated.

On the other hand, introducing some ad-hoc behavior that *some* files under `/etc/` are shadowed by `sys.enable_extra_runtime_domain_names_conf` and *some are not* -- this is very unintuitive.

Well, maybe we just **don't need this PR**?
</blockquote></details>

Ok, this argument convinced me that we should rather wait with this feature until we find a stronger justification. I don't see how to nicely integrate it with the current configuration, as @dimakuv pointed out.


<!-- Sent from Reviewable.io -->

2022-10-25 08:55 UTC, closed without merging

2022-10-25 08:56 UTC, oshogbo commented
So I'm closing it.

2022-10-25 15:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @woju)

___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFEl9tN73bgMeFXseKK:bgre842) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, this argument convinced me that we should rather wait with this feature until we find a stronger justification. I don't see how to nicely integrate it with the current configuration, as @dimakuv pointed out.
</blockquote></details>

Maybe we shouldn't have made this option override files mounted manually in `fs.mounts`? I think I've proposed this at the beginning, but we decided not to do it (but I couldn't find any explanation written anywher)


<!-- Sent from Reviewable.io -->

2022-10-25 16:06 UTC, dimakuv commented
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFEspwA9ML5RByP1hIT:bve7u1i) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe we shouldn't have made this option override files mounted manually in `fs.mounts`? I think I've proposed this at the beginning, but we decided not to do it (but I couldn't find any explanation written anywher)
</blockquote></details>

@boryspoplawski This sounds non-obvious for users. For example, GSC mounts everything in the Docker container from `/`: https://github.com/gramineproject/gsc/blob/7d5ca56cdac3caa33193138d90593f1c63a88199/templates/entrypoint.common.manifest.template#L10

So if we would have `fs.mounts` *taking precedence* over `sys.enable_extra_runtime_domain_names_conf`, we'd need to do something to GSC...


<!-- Sent from Reviewable.io -->

2022-10-25 16:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @woju)

___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFEwBCV5vgl_ADyk43m:buu98g5) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski This sounds non-obvious for users. For example, GSC mounts everything in the Docker container from `/`: https://github.com/gramineproject/gsc/blob/7d5ca56cdac3caa33193138d90593f1c63a88199/templates/entrypoint.common.manifest.template#L10

So if we would have `fs.mounts` *taking precedence* over `sys.enable_extra_runtime_domain_names_conf`, we'd need to do something to GSC...
</blockquote></details>

Then maybe we should do something with GSC, e.g. have a list of excludes, idk. Or add argument to this `enable_extra_runtime_domain_names_conf` option, which would choose whether it shadows mounts or not.
IMO if you explicitly put a line mounting a file, the fact that it's magically overwritten anyway is non-obvious to users.


<!-- Sent from Reviewable.io -->

2022-10-25 16:26 UTC, dimakuv commented
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFExCRK8Ys9Mz0iwapH:b7qdfkl) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then maybe we should do something with GSC, e.g. have a list of excludes, idk. Or add argument to this `enable_extra_runtime_domain_names_conf` option, which would choose whether it shadows mounts or not.
IMO if you explicitly put a line mounting a file, the fact that it's magically overwritten anyway is non-obvious to users.
</blockquote></details>

Yes, we could change `enable_extra_runtime_domain_names_conf` to choose between three types:
```
extra_runtime_domain_names_conf = "disabled | enabled | override_mounts"
```

Where `enabled` doesn't override FS mounts. But not sure if this naming is good.


<!-- Sent from Reviewable.io -->

2022-10-28 00:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1005)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @oshogbo, and @woju)

___
*[`Documentation/manifest-syntax.rst` line 160 at r2](https://reviewable.io/reviews/gramineproject/gramine/1005#-NFB9p3m42H8zYSN6ABo:-NFR-3wj29tqKu9nFYUZ:b1bkrf9) ([raw file](https://github.com/gramineproject/gramine/blob/d5e8fb3d963412e543aedef1076bbed0d59ee7a0/Documentation/manifest-syntax.rst#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we could change `enable_extra_runtime_domain_names_conf` to choose between three types:
```
extra_runtime_domain_names_conf = "disabled | enabled | override_mounts"
```

Where `enabled` doesn't override FS mounts. But not sure if this naming is good.
</blockquote></details>

I tend to agree with Borys that it's GSC's problem to filter out these files if it includes it automatically. On Gramine side it sounds more reasonable to prefer mounts.

Three-options switch could also solve this, but we need a better naming. Disabled-enabled sound binary, and users reading/reviewing manifests will be surprised that there exists a third option.


<!-- Sent from Reviewable.io -->