[LibOS,PAL] Support TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT socket opts
gramineproject/gramine pull request #1007
Opened 2022-10-25 05:03 UTC by kailun-qin

Gramine currently doesn't support set (via `setsockopt()`) or get (via `getsockopt()`) `TCP_KEEPIDLE`, `TCP_KEEPINTVL` and `TCP_KEEPCNT` socket options. This may lead to some applications failures when they try to set these socket options but find out they are unsupported.

This patch implements support for the above TCP socket options.

Resolves https://github.com/gramineproject/gramine/issues/902.

2022-10-25 09:50 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUwPp-GgvbzjyR_F8):*
`Previously, Gramine didn't dupport set ...`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV-cy2BReCPYqXNiW):*
`may` -> `could`

`try` -> `tried`
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV4WUEJL1pmRn9etP):*
`find out` -> `found out`
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV6dKAn1rH6mpIqfs):*
This line is not needed at all.
___
*[`common/include/linux_socket.h` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDQon011-177hewFCg:-NFDQon011-177hewFCh:blz541c) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/common/include/linux_socket.h#L106)):*
> ```objc
> #define TCP_KEEPIDLE 4
> #define TCP_KEEPINTVL 5
> #define TCP_KEEPCNT 6
> ```

Can you add comments as in Linux to all these `TCP_` options? Sometimes I forget which is which, and comments really help.

Comments in Linux: https://elixir.bootlin.com/linux/latest/source/tools/include/uapi/linux/tcp.h#L95
___
*[`libos/src/net/ip.c` line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDTos9C2Z7yiRqDin2:-NFDTos9C2Z7yiRqDin3:b-cdpk6t) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/libos/src/net/ip.c#L269)):*
> ```C
>             break;
>         case TCP_KEEPIDLE:
>             attr.socket.tcp_keepidle = *(int*)optval;
> ```

We need to move the range checks on `optval` from PAL to here.
___
*[`libos/src/net/ip.c` line 386 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDVOAXBOKgxGtDQtzK:-NFDU1tH8kyQaFStT4gi:b-5fb4tz) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/libos/src/net/ip.c#L386)):*
> ```C
>         struct timeval tv;
>     } value = { 0 };
>     memcpy(&value, optval, required_len);
> ```

FYI: Please use smth like this to copy `optval` into `int val`.
___
*[`pal/include/pal/pal.h` line 482 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUUVrEpfnjnHdNMuc:-NFDUUVrEpfnjnHdNMud:b9r4ict) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/include/pal/pal.h#L482)):*
> ```objc
>             bool tcp_cork;
>             unsigned int tcp_keepidle;
>             unsigned int tcp_keepintvl;
> ```

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
___
*[`pal/src/host/linux/pal_host.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUdNLAsUiPWQTv014:-NFDUdNLAsUiPWQTv015:b9r4ict) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_host.h#L82)):*
> ```objc
>             bool tcp_cork;
>             unsigned int tcp_keepidle;
>             unsigned int tcp_keepintvl;
> ```

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
___
*[`pal/src/host/linux/pal_sockets.c` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDX8W0-TmaJusjmoKN:-NFDX8W0-TmaJusjmoKO:bpbt2t0) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L79)):*
> ```C
>     handle->sock.tcp_keepidle = 0;
>     handle->sock.tcp_keepintvl = 0;
>     handle->sock.tcp_keepcnt = 0;
> ```

These are wrong default values. Please set to something similar to what Linux has. It's not that straight-forward to find the correct values, but follow this path as an example for `keepcnt`:
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp.c#L4091
- https://elixir.bootlin.com/linux/latest/source/include/net/tcp.h#L1522
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp_ipv4.c#L3098
- https://elixir.bootlin.com/linux/latest/source/include/net/tcp.h#L156

Please note that `keepidle` and `keepintvl`, there are additional math operations with respect to `HZ`, so make sure to set up correct values.
___
*[`pal/src/host/linux/pal_sockets.c` line 495 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUg1p7s_xa3wdF6Yh:-NFDUg1qD4T8JJVJNo1b:balkada) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L495)):*
> ```C
>         if (attr->socket.tcp_keepidle < 1 || attr->socket.tcp_keepidle > MAX_TCP_KEEPIDLE) {
>             return -PAL_ERROR_INVAL;
>         }
> ```

You won't need this once you move it to LibOS

(Actually, you may add an assert here, to double-check that LibOS doesn't give some wrong values.)
___
*[`pal/src/host/linux/pal_sockets.c` line 507 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUj1nBgTwdwK_-PlF:-NFDUj1nBgTwdwK_-PlG:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L507)):*
> ```C
>         if (attr->socket.tcp_keepintvl < 1 || attr->socket.tcp_keepintvl > MAX_TCP_KEEPINTVL) {
>             return -PAL_ERROR_INVAL;
>         }
> ```

ditto
___
*[`pal/src/host/linux/pal_sockets.c` line 519 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUjgh6tqx0UHQr0eX:-NFDUjgh6tqx0UHQr0eY:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L519)):*
> ```C
>         if (attr->socket.tcp_keepcnt < 1 || attr->socket.tcp_keepcnt > MAX_TCP_KEEPCNT) {
>             return -PAL_ERROR_INVAL;
>         }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_host.h` line 105 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUmaUEuSERsMkyXm_:-NFDUmaUEuSERsMkyXma:b9r4ict) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_host.h#L105)):*
> ```objc
>             bool tcp_cork;
>             unsigned int tcp_keepidle;
>             unsigned int tcp_keepintvl;
> ```

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDY2f6D-3dWIPQK2gT:-NFDY2f6D-3dWIPQK2gU:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L88)):*
> ```C
>     handle->sock.tcp_keepidle = 0;
>     handle->sock.tcp_keepintvl = 0;
>     handle->sock.tcp_keepcnt = 0;
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUpBJBqfeW-4vM_7j:-NFDUpBKDHJEde4t-mQ2:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L448)):*
> ```C
>         if (attr->socket.tcp_keepidle < 1 || attr->socket.tcp_keepidle > MAX_TCP_KEEPIDLE) {
>             return -PAL_ERROR_INVAL;
>         }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUpp9BQJs4BnffcL7:-NFDUpp9BQJs4BnffcL8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L460)):*
> ```C
>         if (attr->soc [...]

2022-10-25 11:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUwPp-GgvbzjyR_F8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Previously, Gramine didn't dupport set ...`
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV-cy2BReCPYqXNiW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`may` -> `could`

`try` -> `tried`
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV4WUEJL1pmRn9etP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`find out` -> `found out`
</blockquote></details>

Done.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDV6dKAn1rH6mpIqfs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line is not needed at all.
</blockquote></details>

Done.
___
*[`common/include/linux_socket.h` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDQon011-177hewFCg:-NFDjtpT42krWvS4Mhkj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/common/include/linux_socket.h#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add comments as in Linux to all these `TCP_` options? Sometimes I forget which is which, and comments really help.

Comments in Linux: https://elixir.bootlin.com/linux/latest/source/tools/include/uapi/linux/tcp.h#L95
</blockquote></details>

Done.
___
*[`libos/src/net/ip.c` line 269 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDTos9C2Z7yiRqDin2:-NFDkI2j3YvG94BsUNHo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/libos/src/net/ip.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We need to move the range checks on `optval` from PAL to here.
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 482 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUUVrEpfnjnHdNMuc:-NFDkTjw7XCWHMzMcv5g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/include/pal/pal.h#L482)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_host.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUdNLAsUiPWQTv014:-NFDkX7_DeS6SYIpO2iK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_host.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_sockets.c` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDX8W0-TmaJusjmoKN:-NFDkYef5E7rOyObFuwE:b-ksknhq) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These are wrong default values. Please set to something similar to what Linux has. It's not that straight-forward to find the correct values, but follow this path as an example for `keepcnt`:
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp.c#L4091
- https://elixir.bootlin.com/linux/latest/source/include/net/tcp.h#L1522
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp_ipv4.c#L3098
- https://elixir.bootlin.com/linux/latest/source/include/net/tcp.h#L156

Please note that `keepidle` and `keepintvl`, there are additional math operations with respect to `HZ`, so make sure to set up correct values.
</blockquote></details>

Good catch! And thanks for the guides!
___
*[`pal/src/host/linux/pal_sockets.c` line 495 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUg1p7s_xa3wdF6Yh:-NFDkm681uVjShoV77qv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L495)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You won't need this once you move it to LibOS

(Actually, you may add an assert here, to double-check that LibOS doesn't give some wrong values.)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_sockets.c` line 507 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUj1nBgTwdwK_-PlF:-NFDkn78BaiIA8KfUVcp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_sockets.c` line 519 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUjgh6tqx0UHQr0eX:-NFDkntoCH4LC-L2AjRj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux/pal_sockets.c#L519)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 105 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUmaUEuSERsMkyXm_:-NFDkomX3EoYIucMx371:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_host.h#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `uint32_t` (I know you took this from Linuc, but here we can just use `uint32_t`) for both new fields
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDY2f6D-3dWIPQK2gT:-NFDkpWPC52jUJfVmSP3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUpBJBqfeW-4vM_7j:-NFDkqsy4LgVHAgXlhBI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L448)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDUpp9BQJs4BnffcL7:-NFDkrofE3zUGB4PYk9a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/pal/src/host/linux-sgx/pal_sockets.c#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto [...]

2022-10-25 15:09 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFE4D1A2cm2OAPHSmtB:-NFEfZfG3Fmjggboio0O:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `getsockopt(...)` for all these three opts to this LibOS regression test: `libos/test/regression/getsockopt.c`, just to have a sanity test.
</blockquote></details>

Done.

___
___
*[`common/include/linux_socket.h` line 106 at r1](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFDQon011-177hewFCg:-NFEfc8NBDLBwnHLoRf9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d9816ce9a27611ac377470ce3a32612a1d00a4e0/common/include/linux_socket.h#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you intend the comments so that they start at the same point? To make it more readable.

Like this:
```
#define TCP_NODELAY 1   /* Turn off Nagle's algorithm. */
#define TCP_CORK 3      /* Never send partially complete segments */
#define TCP_KEEPIDLE 4  /* Start keeplives after this period */
...
```
</blockquote></details>

Done.
___
*[`common/include/linux_socket.h` line 102 at r2](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFE2S7NCbADDE-vgO2u:-NFEf_QR4yvrHV_gZn-_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fa917dc09b406d6a03a295f0e9a2c7c68109e69/common/include/linux_socket.h#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the dot at the end
</blockquote></details>

Done.
___
*[`common/include/linux_socket.h` line 114 at r2](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFE2X1y6cf8U-_egFXZ:-NFEfdYW1AVm1yspq1Wa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fa917dc09b406d6a03a295f0e9a2c7c68109e69/common/include/linux_socket.h#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (intend the comments)
</blockquote></details>

Done.
___
*[`libos/src/net/ip.c` line 267 at r2](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFE2gp9AqF4B7kRbzqX:-NFEffPD710GhYtBLqaR:bu20k8g) ([raw file](https://github.com/gramineproject/gramine/blob/1fa917dc09b406d6a03a295f0e9a2c7c68109e69/libos/src/net/ip.c#L267)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We could simplify this to just `int value`, but I'm ok with the union as well.
</blockquote></details>

I left the union here as a reminder to follow this pattern but I'm open to it.


<!-- Sent from Reviewable.io -->

2022-10-25 16:34 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/regression/getsockopt.c` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEz5Pa-xxiuk417IL4:-NFEz5Pa-xxiuk417IL5:bhjxq48) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L1)):*
> ```C
> /* Unit test for issues #92 and #644 */
> ```

Let's remove this. Looks useless and stale.
___
*[`libos/test/regression/getsockopt.c` line 20 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEzAViErKVvuG2B-yY:-NFEzAViErKVvuG2B-yZ:b-oqlvdd) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L20)):*
> ```C
>     socklen_t optlen; /* Option length */
> 
>     int fd = socket(PF_INET, SOCK_STREAM, 0);
> ```

Can we update this whole test to use `CHECK()`, `err()` and `errx()`? We're slowly rewriting all tests like this.

Also, we can remove intermediate `printf`s and just have `puts("TEST OK");` at the very end.

See an example here: https://github.com/gramineproject/gramine/pull/996
___
*[`libos/test/regression/getsockopt.c` line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEyrI36m9PY7_JEmPg:-NFEyrI36m9PY7_JEmPh:bwm1tjq) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L35)):*
> ```C
> 
>     if (optlen != sizeof(so_type) || so_type != SOCK_STREAM) {
>         fprintf(stderr, "getsockopt(SOL_SOCKET, SO_TYPE) failed\n");
> ```

`failed` -> `returned unexpected value`
___
*[`libos/test/regression/getsockopt.c` line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEys1QBAHMsrfYQhlU:-NFEys1QBAHMsrfYQhlV:bwm1tjq) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L50)):*
> ```C
> 
>     if (optlen != sizeof(so_flags) || (so_flags != 0 && so_flags != 1)) {
>         fprintf(stderr, "getsockopt(SOL_TCP, TCP_NODELAY) failed\n");
> ```

`failed` -> `returned unexpected value`
___
*[`libos/test/regression/getsockopt.c` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEyo6m5MRbwEvz6ju4:-NFEyo6n8zEJhJ3BSI9c:bwm1tjq) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L65)):*
> ```C
> 
>     if (optlen != sizeof(tcp_keepidle) || (tcp_keepidle != DEFAULT_TCP_KEEPIDLE)) {
>         fprintf(stderr, "getsockopt(IPPROTO_TCP, TCP_KEEPIDLE) failed\n");
> ```

`failed` -> `returned unexpected value`
___
*[`libos/test/regression/getsockopt.c` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEywk58sEsXKxqJ6Xc:-NFEywk58sEsXKxqJ6Xd:bwm1tjq) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L80)):*
> ```C
> 
>     if (optlen != sizeof(tcp_keepintvl) || (tcp_keepintvl != DEFAULT_TCP_KEEPINTVL)) {
>         fprintf(stderr, "getsockopt(IPPROTO_TCP, TCP_KEEPINTVL) failed\n");
> ```

`failed` -> `returned unexpected value`


<!-- Sent from Reviewable.io -->

2022-10-25 21:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFG4en27nN2wo3fcRby:-NFG4en27nN2wo3fcRbz:brd2m2f) (no related file):*
Given that none of this options is really needed (see my comment in the postgress issue), do we want to proceed with this PR?

___


<!-- Sent from Reviewable.io -->

2022-10-26 05:42 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/getsockopt.c` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEz5Pa-xxiuk417IL4:-NFHmo708wmvvwCCDSLT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's remove this. Looks useless and stale.
</blockquote></details>

Done.
___
*[`libos/test/regression/getsockopt.c` line 20 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEzAViErKVvuG2B-yY:-NFHmovQ66e1wRlpBpBP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we update this whole test to use `CHECK()`, `err()` and `errx()`? We're slowly rewriting all tests like this.

Also, we can remove intermediate `printf`s and just have `puts("TEST OK");` at the very end.

See an example here: https://github.com/gramineproject/gramine/pull/996
</blockquote></details>

Done.
___
*[`libos/test/regression/getsockopt.c` line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEyrI36m9PY7_JEmPg:-NFHmpQ_4SofGhsfJJVs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`failed` -> `returned unexpected value`
</blockquote></details>

Done.
___
*[`libos/test/regression/getsockopt.c` line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEys1QBAHMsrfYQhlU:-NFHmqjfAUDkJCkt09ta:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`failed` -> `returned unexpected value`
</blockquote></details>

Done.
___
*[`libos/test/regression/getsockopt.c` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEyo6m5MRbwEvz6ju4:-NFHmrG91JD1Hf_00To9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`failed` -> `returned unexpected value`
</blockquote></details>

Done.
___
*[`libos/test/regression/getsockopt.c` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFEywk58sEsXKxqJ6Xc:-NFHmrtA9VuDylgiBp2l:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d864cf8985d5d813f3c599fb5cbf99ee1516448/libos/test/regression/getsockopt.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`failed` -> `returned unexpected value`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-26 05:51 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: 7 of 9 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFG4en27nN2wo3fcRby:-NFHoKJQ8n0VnDkh9-2D:b-c50r6i) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Given that none of this options is really needed (see my comment in the postgress issue), do we want to proceed with this PR?
</blockquote></details>

I don't have strong opinion on this, though these are rather common opts usually applied together w/ `SO_KEEPALIVE` (which's been already supported) that may benefit come apps. I'll let @dimakuv to provide more thoughts.

___


<!-- Sent from Reviewable.io -->

2022-10-26 07:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFG4en27nN2wo3fcRby:-NFI8ViA9Zi9kb_zxSxp:ben7vmd) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I don't have strong opinion on this, though these are rather common opts usually applied together w/ `SO_KEEPALIVE` (which's been already supported) that may benefit come apps. I'll let @dimakuv to provide more thoughts.
</blockquote></details>

@boryspoplawski I replied in that issue. I'm positive that the problem exists, so this PR is needed.

___


<!-- Sent from Reviewable.io -->

2022-10-26 07:18 UTC, dimakuv commented
Jenkins, test this please

2022-10-26 16:17 UTC, boryspoplawski requested changes
> Reviewed 6 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFIxWr139O0VvGPan1y):*




_Suggestion:_
```
 Previously, Gramine didn't support setting (via `setsockopt()`) or getting (via
```
___
*[`common/include/linux_socket.h` line 108 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFJ145Y7XkOVBSQcNxu:-NFJ145ZAl-SXaFEJOQt:b-ourtg2) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/common/include/linux_socket.h#L108)):*
> ```objc
> #define TCP_KEEPCNT 6   /* Number of keepalives before death */
> 
> #define MAX_TCP_KEEPIDLE 32767
> ```

Hmm, not sure where we want to keep these defaults and maxes. This header was supposed to hold standard types that are part of Linux interface (syscalls), but at the moment we don't have any good header for these macros.
___
*[`common/include/linux_socket.h` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFIziO39F7x1E5acbBI:-NFIziO39F7x1E5acbBJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/common/include/linux_socket.h#L112)):*
> ```objc
> #define MAX_TCP_KEEPCNT 127
> 
> #define DEFAULT_TCP_KEEPIDLE (120 * 60) /* two hours */
> ```





_Suggestion:_
```objc
2 * 60 * 60
```
___
*[`libos/src/net/ip.c` line 265 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFJ3uYG6QAqLtk73o1K:-NFJ3uYG6QAqLtk73o1L:bcj83e) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/src/net/ip.c#L265)):*
> ```C
>     }
> 
>     union {
> ```

uhhh, one element union?
___
*[`libos/test/regression/getsockopt.c` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3MjL5ie5LPKX3862:-NFK3MjMAejWUZ1MDEnp:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L13)):*
> ```C
> #define DEFAULT_TCP_KEEPCNT 9
> 
> int main(int argc, char** argv) {
> ```





_Suggestion:_
```C
main(void)
```
___
*[`libos/test/regression/getsockopt.c` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3EL6CcGT0hIyPv44:-NFK3EL6CcGT0hIyPv45:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L16)):*
> ```C
>     socklen_t optlen; /* Option length */
> 
>     int fd = CHECK(socket(PF_INET, SOCK_STREAM, 0));
> ```





_Suggestion:_
```C
AF_INET
```
___
*[`libos/test/regression/getsockopt.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3iNBCqUcuZgQgs5t:-NFK3iNBCqUcuZgQgs5u:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L28)):*
> ```C
>     int so_flags = 1;
>     optlen = sizeof(so_flags);
>     CHECK(getsockopt(fd, SOL_TCP, TCP_NODELAY, (void*)&so_flags, &optlen));
> ```





_Suggestion:_
```C
&so_flags
```
___
*[`libos/test/regression/getsockopt.c` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3siy5znxU0i-NmrD:-NFK3siy5znxU0i-NmrE:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L36)):*
> ```C
>     int tcp_keepidle;
>     optlen = sizeof(tcp_keepidle);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&tcp_keepidle, &optlen));
> ```





_Suggestion:_
```C
&tcp_keepidle
```
___
*[`libos/test/regression/getsockopt.c` line 38 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK40rKEZB5d0fRNzfS:-NFK40rKEZB5d0fRNzfT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L38)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&tcp_keepidle, &optlen));
> 
>     if (optlen != sizeof(tcp_keepidle) || (tcp_keepidle != DEFAULT_TCP_KEEPIDLE)) {
> ```





_Suggestion:_
```C
if (optlen != sizeof(tcp_keepidle) || tcp_keepidle != DEFAULT_TCP_KEEPIDLE) {
```
___
*[`libos/test/regression/getsockopt.c` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK49Ry9kxrg9pruXHe:-NFK49Ry9kxrg9pruXHf:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L44)):*
> ```C
>     int tcp_keepintvl;
>     optlen = sizeof(tcp_keepintvl);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void*)&tcp_keepintvl, &optlen));
> ```





_Suggestion:_
```C
&tcp_keepintvl,
```
___
*[`libos/test/regression/getsockopt.c` line 46 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK47IKCIMi8XhyykuK:-NFK47IKCIMi8XhyykuL:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L46)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void*)&tcp_keepintvl, &optlen));
> 
>     if (optlen != sizeof(tcp_keepintvl) || (tcp_keepintvl != DEFAULT_TCP_KEEPINTVL)) {
> ```





_Suggestion:_
```C
if (optlen != sizeof(tcp_keepintvl) || tcp_keepintvl != DEFAULT_TCP_KEEPINTVL) {
```
___
*[`libos/test/regression/getsockopt.c` line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK4EUo7EAy_olX9dIN:-NFK4EUo7EAy_olX9dIO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L52)):*
> ```C
>     int tcp_keepcnt;
>     optlen = sizeof(tcp_keepcnt);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void*)&tcp_keepcnt, &optlen));
> ```





_Suggestion:_
```C
&tcp_keepcnt,
```
___
*[`libos/test/regression/getsockopt.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK4Gkj3dy1WdofxK5-:-NFK4Gkj3dy1WdofxK50:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L54)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void*)&tcp_keepcnt, &optlen));
> 
>     if (optlen != sizeof(tcp_keepcnt) || (tcp_keepcnt != DEFAULT_TCP_KEEPCNT)) {
> ```





_Suggestion:_
```C
if (optlen != sizeof(tcp_keepcnt) || tcp_keepcnt != DEFAULT_TCP_KEEPCNT) {
```


<!-- Sent from Reviewable.io -->

2022-10-27 01:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFIxWr139O0VvGPan1y):*
Done.
___
*[`common/include/linux_socket.h` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFIziO39F7x1E5acbBI:-NFM4PNM7T5izYFefj9C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/common/include/linux_socket.h#L112)):*
> ```objc
> #define MAX_TCP_KEEPCNT 127
> 
> #define DEFAULT_TCP_KEEPIDLE (120 * 60) /* two hours */
> ```

Done.
___
*[`libos/src/net/ip.c` line 265 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFJ3uYG6QAqLtk73o1K:-NFM4e7EDWuga67FqVD2:b-czw5os) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/src/net/ip.c#L265)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

uhhh, one element union?
</blockquote></details>

I left the union here as a reminder to follow this pattern. Let me know if any concerns.
___
*[`libos/test/regression/getsockopt.c` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3MjL5ie5LPKX3862:-NFM4ht28SIRzRtcRXyi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L13)):*
> ```C
> #define DEFAULT_TCP_KEEPCNT 9
> 
> int main(int argc, char** argv) {
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3EL6CcGT0hIyPv44:-NFM4iIm9W1mKCHh-EEy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L16)):*
> ```C
>     socklen_t optlen; /* Option length */
> 
>     int fd = CHECK(socket(PF_INET, SOCK_STREAM, 0));
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3iNBCqUcuZgQgs5t:-NFM4qYN77scnq6wQBLJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L28)):*
> ```C
>     int so_flags = 1;
>     optlen = sizeof(so_flags);
>     CHECK(getsockopt(fd, SOL_TCP, TCP_NODELAY, (void*)&so_flags, &optlen));
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK3siy5znxU0i-NmrD:-NFM4qyNA2eFak_iYAVs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L36)):*
> ```C
>     int tcp_keepidle;
>     optlen = sizeof(tcp_keepidle);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&tcp_keepidle, &optlen));
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 38 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK40rKEZB5d0fRNzfS:-NFM4rWF5-tg3ECvd3EX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L38)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&tcp_keepidle, &optlen));
> 
>     if (optlen != sizeof(tcp_keepidle) || (tcp_keepidle != DEFAULT_TCP_KEEPIDLE)) {
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK49Ry9kxrg9pruXHe:-NFM4rrC7XRW7hIjtRXa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L44)):*
> ```C
>     int tcp_keepintvl;
>     optlen = sizeof(tcp_keepintvl);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void*)&tcp_keepintvl, &optlen));
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 46 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK47IKCIMi8XhyykuK:-NFM4sKd6BJHGjXu6BWG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L46)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void*)&tcp_keepintvl, &optlen));
> 
>     if (optlen != sizeof(tcp_keepintvl) || (tcp_keepintvl != DEFAULT_TCP_KEEPINTVL)) {
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK4EUo7EAy_olX9dIN:-NFM4sop9A-KXhrggLos:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L52)):*
> ```C
>     int tcp_keepcnt;
>     optlen = sizeof(tcp_keepcnt);
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void*)&tcp_keepcnt, &optlen));
> ```

Done.
___
*[`libos/test/regression/getsockopt.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFK4Gkj3dy1WdofxK5-:-NFM4tDIB1-XVysXJHHg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/test/regression/getsockopt.c#L54)):*
> ```C
>     CHECK(getsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void*)&tcp_keepcnt, &optlen));
> 
>     if (optlen != sizeof(tcp_keepcnt) || (tcp_keepcnt != DEFAULT_TCP_KEEPCNT)) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-10-27 07:17 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/src/net/ip.c` line 265 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFJ3uYG6QAqLtk73o1K:-NFNI3KUAmzbq8w8hsuH:bxhd6c4) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/src/net/ip.c#L265)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I left the union here as a reminder to follow this pattern. Let me know if any concerns.
</blockquote></details>

@boryspoplawski See my other comment. Kailun took the pattern from that other code, just for future extensibility (if we start supporting non-int options in this function). I had the same comment as you, but I don't care much. If you feel that this is unneeded eyebrow-raising snippet, then let's simplify to just `int value`.
___
*[`libos/src/net/ip.c` line 400 at r5](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFNI-sx5W6EMn1zvsd2:-NFNI-sx5W6EMn1zvsd3:b2r2igo) ([raw file](https://github.com/gramineproject/gramine/blob/0ce6f778c4b314b1312335da76154c0e5cb8a6c9/libos/src/net/ip.c#L400)):*
> ```C
>         struct linger linger;
>         struct timeval tv;
>     } value = { 0 };
> ```

FYI: @boryspoplawski Kailun took the pattern from here.


<!-- Sent from Reviewable.io -->

2022-10-27 10:39 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/include/linux_socket.h` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFO082JCKaN3RkENr5o:-NFO082JCKaN3RkENr5p:bc566i) ([raw file](https://github.com/gramineproject/gramine/blob/0ce6f778c4b314b1312335da76154c0e5cb8a6c9/common/include/linux_socket.h#L114)):*
> ```objc
> #define DEFAULT_TCP_KEEPIDLE (2 * 60 *60) /* two hours */
> #define DEFAULT_TCP_KEEPINTVL 75
> #define DEFAULT_TCP_KEEPCNT 9             /* Max of 9 keepalive probes */
> ```

This comment is wrong (this is not max), just remove it
___
*[`libos/src/net/ip.c` line 265 at r4](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFJ3uYG6QAqLtk73o1K:-NFO0Rp19sZzsYBX2u9L:b-dqb8o8) ([raw file](https://github.com/gramineproject/gramine/blob/b86653a00b427297290c7170007033f44c01027e/libos/src/net/ip.c#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski See my other comment. Kailun took the pattern from that other code, just for future extensibility (if we start supporting non-int options in this function). I had the same comment as you, but I don't care much. If you feel that this is unneeded eyebrow-raising snippet, then let's simplify to just `int value`.
</blockquote></details>

I'm sure I'll scratch my head each time I see it, but I don't care much (notice I didn't block :) )


<!-- Sent from Reviewable.io -->

2022-10-27 10:41 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/include/linux_socket.h` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFO082JCKaN3RkENr5o:-NFO0qqE-bhnBwYjYm-E:bfl5nv3) ([raw file](https://github.com/gramineproject/gramine/blob/0ce6f778c4b314b1312335da76154c0e5cb8a6c9/common/include/linux_socket.h#L114)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This comment is wrong (this is not max), just remove it
</blockquote></details>

I mean, it's more like confusing, not wrong (the whole option, that this is the default of, is a "max").


<!-- Sent from Reviewable.io -->

2022-10-28 03:27 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`common/include/linux_socket.h` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1007#-NFO082JCKaN3RkENr5o:-NFRcEb96QpjINImlZyP:botnp7r) ([raw file](https://github.com/gramineproject/gramine/blob/0ce6f778c4b314b1312335da76154c0e5cb8a6c9/common/include/linux_socket.h#L114)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I mean, it's more like confusing, not wrong (the whole option, that this is the default of, is a "max").
</blockquote></details>

Changed the wording a bit, hope it looks better.


<!-- Sent from Reviewable.io -->

2022-10-28 07:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-10-28 14:34 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-31 08:22 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1007)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-10-31 08:23 UTC, dimakuv commented
Jenkins, test this please

2022-10-31 15:34 UTC, merged