[tools/sgx] Remove unneeded include deps for RA-TLS and secret-prov libs
gramineproject/gramine pull request #1008
Opened 2022-10-25 08:19 UTC by kailun-qin

Gramine RA-TLS and Secret Provisioning libraries actually only need `sgx_arch.h` and `sgx_attest.h` from `PAL/Linux-SGX` (for some SGX-hardware-specific structs). However, `sgx_inc` which contains unnecessary includes e.g., `common_inc` is currently used for them.

This patch removes `sgx_inc` from RA-TLS and Secret Provisioning libs' include dependencies and includes only the needed from `PAL/Linux-SGX`.

Resolves https://github.com/gramineproject/gramine/issues/876.

2022-10-25 08:35 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/meson.build` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDF78e3fBa2Tdzc8Ex:-NFDF78e3fBa2Tdzc8Ey:bkysrr8) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L10)):*
> ```Meson
>     includes_pal_common,
>     include_directories(
>         '.',
> ```

You should remove this line and instead add `pal_sgx_inc` in the list
___
*[`pal/src/host/linux-sgx/meson.build` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDFx-LDjg2ydo2SZG1:-NFDFx-LDjg2ydo2SZG2:b7ejopn) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L16)):*
> ```Meson
> ]
> 
> pal_sgx_inc = [
> ```

I'm not happy with this name and that it includes *all* files under `linux-sgx/`. Technically we only need `sgx_attest.h` and `sgx_arch.h`.

But I also don't want to move these files in some separate directory (it just creates complications). Anyway, I don't find this solution very clean, but it's good enough to solve our functional problems. I'm not too happy, but I can't come up with something definitively better.
___
*[`pal/src/host/linux-sgx/meson.build` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDF4jd59HrxVzWDV6W:-NFDF4jd59HrxVzWDV6X:bcrvqyb) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L20)):*
> ```Meson
>         '.',
>     ),
> ]
> ```

Please move it before `sgx_inc`
___
*[`tools/sgx/common/meson.build` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGdLIDB6sFwnKkxLK:-NFDGdLIDB6sFwnKkxLL:b7fjxh8) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/common/meson.build#L16)):*
> ```Meson
> 
>     include_directories: [
>         pal_sgx_inc,
> ```

Please add a comment that this is only for `sgx_arch.h` and `sgx_attest.h` headers.
___
*[`tools/sgx/common/meson.build` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGaZq2afB_RzjKVl6:-NFDGaZq2afB_RzjKVl7:bmwl0rg) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/common/meson.build#L34)):*
> ```Meson
>     include_directories: [
>         include_directories('.'),
>         pal_sgx_inc, # this is for `sgx_attest.h`
> ```

Not for `sgx_arch.h` too? How did you check?
___
*[`tools/sgx/ra-tls/meson.build` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGlpX9_PhwSWWzeV-:-NFDGlpX9_PhwSWWzeV0:bmf8b65) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/ra-tls/meson.build#L14)):*
> ```Meson
>     'ra_tls_attest.c',
>     c_args: ra_tls_args,
>     include_directories: pal_sgx_inc,
> ```

Please add a comment that this is only for `sgx_arch.h` and `sgx_attest.h` headers.

One comment on this line is enough, I don't want to have the same comment everywhere in this file.


<!-- Sent from Reviewable.io -->

2022-10-25 09:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/meson.build` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDF78e3fBa2Tdzc8Ex:-NFDIYjwBOEHOyTcXhtL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should remove this line and instead add `pal_sgx_inc` in the list
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/meson.build` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDFx-LDjg2ydo2SZG1:-NFDIZz1E7XNI7ahUEUl:b-3ywi3n) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not happy with this name and that it includes *all* files under `linux-sgx/`. Technically we only need `sgx_attest.h` and `sgx_arch.h`.

But I also don't want to move these files in some separate directory (it just creates complications). Anyway, I don't find this solution very clean, but it's good enough to solve our functional problems. I'm not too happy, but I can't come up with something definitively better.
</blockquote></details>

Yeah, I felt exactly the same... Just don't come up a better one.
___
*[`pal/src/host/linux-sgx/meson.build` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDF4jd59HrxVzWDV6W:-NFDIqYD2qG4819OsHKS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/pal/src/host/linux-sgx/meson.build#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move it before `sgx_inc`
</blockquote></details>

Done.
___
*[`tools/sgx/common/meson.build` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGdLIDB6sFwnKkxLK:-NFDJU_18vDcp60COopP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/common/meson.build#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment that this is only for `sgx_arch.h` and `sgx_attest.h` headers.
</blockquote></details>

Done.
___
*[`tools/sgx/common/meson.build` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGaZq2afB_RzjKVl6:-NFDKKHlC1rV9vJr4UR0:bgwtbqu) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/common/meson.build#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not for `sgx_arch.h` too? How did you check?
</blockquote></details>

Yes, `sgx_arch.h` is indeed needed for `tools/sgx/common/quote.c` (only internally). But here it's a declared dependency for a shared lib, so my original thought was - pointing to `sgx_attest.h` (needed by the header`tools/sgx/common/quote.h`) should be enough.

Anyway, I changed the wording to avoid confusions.
___
*[`tools/sgx/ra-tls/meson.build` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFDGlpX9_PhwSWWzeV-:-NFDJrjV5jcrJ_o84tco:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64cccc138fc3abf877068ba0a6eca0e99cc8bd67/tools/sgx/ra-tls/meson.build#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment that this is only for `sgx_arch.h` and `sgx_attest.h` headers.

One comment on this line is enough, I don't want to have the same comment everywhere in this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 09:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-10-25 09:14 UTC, dimakuv commented
Jenkins, test this please

2022-10-25 12:57 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFEBZlV8WgFyInw-pwr):*




_Suggestion:_
```
and includes only the needed headers from `PAL/Linux-SGX`.
```


<!-- Sent from Reviewable.io -->

2022-10-25 15:46 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-10-25 17:06 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1008#-NFEBZlV8WgFyInw-pwr):*
Done. Also modified some sentences which sounded like broken English.


<!-- Sent from Reviewable.io -->

2022-10-25 17:06 UTC, dimakuv commented
Jenkins, test this please

2022-10-25 21:12 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-10-26 11:02 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1008)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-26 11:03 UTC, merged