[Pal/Linux-SGX] Add `sgx.protected_mr{enclave,signer}_files` manifest options
gramineproject/gramine pull request #101
Opened 2021-09-29 08:31 UTC by dimakuv

## Description of the changes 

Previously, only `sgx.protected_files` were available in the manifest. This kind of protected files needs a provisioned master (wrap) key. But sometimes it is enough to seal files on the same platform for later usage by the same enclave or by enclaves of the same signer: this is the SGX sealing feature.

This commit adds two more options to support SGX sealing: `sgx.protected_mrenclave_files` and `sgx.protected_mrsigner_files`.
Similarly to `sgx.protected_files`, these new options specify lists of files that are encrypted by the SGX key generated via SGX instruction `EGETKEY(SEAL_KEY)`, bound to the MRENCLAVE/MRSIGNER enclave measurement (so that only instances of the same enclave/only enclaves with the same signer may decrypt protected files).

References:
- https://github.com/gramineproject/graphene/pull/2484 -- same PR from the old repo (note that this current PR is slightly updated wrt to that old PR)
- Section 37.18 of the Intel SDM
- https://github.com/gramineproject/gramine/blob/5c505d44ab6ffa6d303cde51b4ccf922c3eaab88/Pal/src/host/Linux-SGX/sgx_arch.h#L395

## How to test this PR? 

A corresponding LibOS test is added and documentation is updated to reflect this.

2021-09-29 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 0 of 11 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 221 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkkfwqxEFeSWht7j1k4:-MkkfwqxEFeSWht7j1k5:b-fwiqd) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L221)):*
> ```C
>     key_request.attribute_mask.flags = SGX_FLAGS_MASK_CONST_HI << 32 | SGX_FLAGS_MASK_CONST_LO;
>     key_request.attribute_mask.xfrm  = SGX_XFRM_MASK_CONST_HI << 32 | SGX_XFRM_MASK_CONST_LO;
>     key_request.misc_mask            = SGX_MISCSELECT_MASK_CONST;
> ```

FYI: Note that we use our hard-coded masks (introduced in PR https://github.com/gramineproject/gramine/pull/44).

This prevents issues with e.g. "production enclave sealed the file and now debug enclave unseals this file".


<!-- Sent from Reviewable.io -->

2021-09-30 01:40 UTC, mkow requested changes
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 10 of 11 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/.gitignore, line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9pdiDOAglA_cc7xq:-Mko9pdj9Bw9as0ycxqN:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/.gitignore#L87)):*
> ```ignore
> /proc_cpuinfo
> /proc_path
> /sealed_file
> ```

please sort
___
*[LibOS/shim/test/regression/Makefile, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9zYg9ra-lb0QVlbT:-Mko9zYg9ra-lb0QVlbU:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/Makefile#L73)):*
> ```Makefile
> 	proc_cpuinfo \
> 	proc_path \
> 	sealed_file \
> ```

ditto
___
*[LibOS/shim/test/regression/Makefile, line 198 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoA2388ozxDRAtK4km:-MkoA2388ozxDRAtK4kn:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/Makefile#L198)):*
> ```Makefile
> 		*.tmp \
> 		*.token \
> 		*.dat \
> ```

ditto
___
*[LibOS/shim/test/regression/manifest.template, line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9uYJAulIi7muuod6:-Mko9uYJAulIi7muuod7:b-5hpfxc) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/manifest.template#L52)):*
> ```
> 
> # for sealed_file test
> sgx.protected_mrenclave_files = [
> ```

No test for mrsigner sealing?
___
*[LibOS/shim/test/regression/sealed_file.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAKia-HqNuFiT5Bge:-MkoAKia-HqNuFiT5Bgf:b-idk0a7) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L12)):*
> ```C
> #define SECRETSTRING "Secret string\n"
> 
> static ssize_t rw_file(const char* path, char* buf, size_t bytes, bool do_write) {
> ```

This is pretty large, could you move this to a common .c file? It's also used by `attestation.c` and `file_size.c`.
___
*[LibOS/shim/test/regression/sealed_file.c, line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoARod5J2ur1puQFB9:-MkoARoeEIjL0Z9Tf3Zp:bn4pa4f) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L93)):*
> ```C
>     buf[bytes - 1] = '\0';
> 
>     size_t size_to_cmp = sizeof(SECRETSTRING) < bytes ? sizeof(SECRETSTRING) : bytes;
> ```

Why do you do this `min()`? We want `bytes` to be exactly `sizeof(SECRETSTRING)`, all other results are wrong.
___
*[LibOS/shim/test/regression/sealed_file.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAWUq3WpuJxAfUWpm:-MkoAWUq3WpuJxAfUWpn:bgvgzcw) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L97)):*
> ```C
>         errx(EXIT_FAILURE, "Expected '%s' but read '%s'\n", SECRETSTRING, buf);
> 
>     printf("TEST OK\n");
> ```

I'd replace this with "READING OK", I was a bit confused after I read the asserts in Python first.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAy452L3W7ezRRt2f:-MkoAy452L3W7ezRRt2g:bqlcx28) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
> ```
> uint16_t
> ```

Not enum? Would be self-documenting.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoB-nL3728y_9pa5g0:-MkoB-nL3728y_9pa5g1:b-qu3mpj) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
> ```C
> }
> 
> int sgx_get_seal_key(uint16_t key_policy, sgx_key_128bit_t* seal_key) {
> ```

`seal_key` -> `out_seal_key`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoDhR8DylQoqfzJIPF:-MkoDhR9EC2S1F7GEtZU:b-dte10h) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L194)):*
> ```
> /* get our own SGX report to obtain this enclave's isv_svn, cpu_svn, config_svn */
> ```

After #100 we'll have all the needed info in `g_pal_sec.enclave_measurements`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoEKBj25KQQfnb_bs0:-MkoEKBk1WfsFq9Gd7oq:b-kwtnoa) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L213)):*
> ```
> key_request.key_policy = key_policy;
> ```

So, this is actually an SGX constant, not a custom Graphene enum? It should be prefixed with `SGX_` then. Until I read this line I thought it's just something you introduced for this very function.

Ditto for `SEAL_KEY`.
___
*[Pal/src/host/Linux-SGX/enclave_pf.h, line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoGMVj8QR4SYcHZqpj:-MkoGMVk1Pn_B3ZSnHfa:b7hkxyy) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.h#L48)):*
> ```
>  = 0
> ```

Why do you start your enums this way? a) Zero is already the default in C, b) We don't actually rely on this enum having any specific values.
___
*[Pal/src/host/Linux-SGX/enclave_pf.h, line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoGid1331lbdHUD7ft:-MkoGid23OuId8o24xLP:byx4puj) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.h#L61)):*
> ```
> int
> ```

Why not `enum`? You wouldn't need the comment then.
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 233 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoH23-15T4XFamAcsX:-MkoH23-15T4XFamAcsY:b-andtzc) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.c#L233)):*
> ```
> int key_type
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 292 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoH8FNBRr2NNN_80Pj:-MkoH8FNBRr2NNN_80Pk:b-andtzc) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.c#L292)):*
> ```
> int key_type
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 356 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoHS2W8RPqJhUyj1VP:-MkoHS2W8RPqJhUyj1VQ:b-andtzc) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.c#L356)):*
> ```
> int key_type
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 438 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoHgT1EN8USuN_HPRq:-MkoHgT1EN8USuN_HPRr:b-andtzc) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.c#L438)):*
> ```
> int key_type
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoIV_hBBWIkvHZr5ox:-MkoIV_hBBWIkvHZr5oy:bcagsni) ([raw file](https [...]

2021-09-30 09:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 2 of 16 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/.gitignore, line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9pdiDOAglA_cc7xq:-Mkpoaeb4GrBTergEAU7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/.gitignore#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/Makefile, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9zYg9ra-lb0QVlbT:-MkpohVV0OhCJpFj93_3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/Makefile#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/Makefile, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkq7EBo-8nz_Rc6z_vQ:-Mkq7EBpC7_M_f8pL4L1:b1cm0hn) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/Makefile#L169)):*
> ```Makefile
> endif
> 
> proc_common: proc_common.o dump.o
> ```

FYI: This was a bug to link `.o` files. The `cmulti` command in our Makefiles did not "see" e.g. `CFLAGS-sealed_file_mod` this way. So I changed everything to compile & link from `.c` files.
___
*[LibOS/shim/test/regression/Makefile, line 198 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoA2388ozxDRAtK4km:-MkpohsZ16sEtG4n7K4N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/Makefile#L198)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/manifest.template, line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9uYJAulIi7muuod6:-Mkq00wjBnUMIbaBJzRQ:b-80l441) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/manifest.template#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No test for mrsigner sealing?
</blockquote></details>

Done. Good point, it's pretty important to test it. Check my awesome trick to produce slightly-different MRENCLAVEs :)
___
*[LibOS/shim/test/regression/sealed_file.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAKia-HqNuFiT5Bge:-MkpwCHvCVsaER5xykgk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is pretty large, could you move this to a common .c file? It's also used by `attestation.c` and `file_size.c`.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoARod5J2ur1puQFB9:-MkpwRCJ6puY5Hfzi8F3:b-qq48jd) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do you do this `min()`? We want `bytes` to be exactly `sizeof(SECRETSTRING)`, all other results are wrong.
</blockquote></details>

Done. True.
___
*[LibOS/shim/test/regression/sealed_file.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAWUq3WpuJxAfUWpm:-MkpwWWj4ofUqED-QHyr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/sealed_file.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd replace this with "READING OK", I was a bit confused after I read the asserts in Python first.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAy452L3W7ezRRt2f:-Mkq3Cfl9g3tDZFNbUR9:b-ahh3vk) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> uint16_t
> ```

Not enum? Would be self-documenting.
</blockquote></details>

This is an SGX constant, it must be `uint16_t`, see Intel SDM, Table 37-25.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoB-nL3728y_9pa5g0:-Mkq3dGfEIDDgbR9__Or:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`seal_key` -> `out_seal_key`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoDhR8DylQoqfzJIPF:-Mkq3rZs4Lz3yP3839JK:b-l5juod) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> /* get our own SGX report to obtain this enclave's isv_svn, cpu_svn, config_svn */
> ```

After #100 we'll have all the needed info in `g_pal_sec.enclave_measurements`
</blockquote></details>

Done. Added a FIXME comment not to forget about this during rebase.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoEKBj25KQQfnb_bs0:-Mkq2aZF-mjNwLlaSoIw:b404p0b) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> key_request.key_policy = key_policy;
> ```

So, this is actually an SGX constant, not a custom Graphene enum? It should be prefixed with `SGX_` then. Until I read this line I thought it's just something you introduced for this very function.

Ditto for `SEAL_KEY`.
</blockquote></details>

Done.

Yes, these are SGX constants, see Intel SDM, Tables 37-26  and 37-27. For some reason they were not prefixed with `SGX_` in the `sgx_arch.h` file which we stole from the Intel SGX SDK.
___
*[Pal/src/host/Linux-SGX/enclave_pf.h, line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoGMVj8QR4SYcHZqpj:-Mkq0y0N6mCbdVR7sxpl:b1xhay0) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.h#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  = 0
> ```

Why do you start your enums this way? a) Zero is already the default in C, b) We don't actually rely on this enum having any specific values.
</blockquote></details>

Done. I guess I can't master enums :)
___
*[Pal/src/host/Linux-SGX/enclave_pf.h, line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoGid1331lbdHUD7ft:-Mkq0yoL8xQlbcDNV3NO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blo [...]

2021-09-30 12:12 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (`test-direct / apps.LTP.fdatasync01` timed out, not related)

2021-09-30 12:26 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (`test-direct / apps.LTP.sendfile09` timed out, not related, but it looks like we need to increase our timeouts for Sanitizers...)

2021-09-30 15:05 UTC, mkow requested changes
> Reviewed 14 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/manifest.template, line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-Mko9uYJAulIi7muuod6:-Mkr8yLN0FSQq3dn4xsH:bfxjq6w) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/LibOS/shim/test/regression/manifest.template#L52)):*
> Check my awesome trick to produce slightly-different MRENCLAVEs :)

hah, I'm already scared :) we'll see ;)
___
*[LibOS/shim/test/regression/rw_file.c, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr81rJ2CKKy59d-WWV:-Mkr81rJ2CKKy59d-WWW:bw95ieg) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L13)):*
> ```C
> #include <unistd.h>
> 
> #include "rw_file.h"
> ```

this should go first, see our styleguide
___
*[LibOS/shim/test/regression/rw_file.c, line 67 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr7mTX7HNYd8y3P1Kt:-Mkr7mTY-SM_ovEj2iEk:b5gxrw9) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L67)):*
> ```C
>     size_t ret = 0;
> 
>     FILE* f = fopen(path, do_write ? "w" : "r");
> ```

Why have you dropped "b"?
___
*[LibOS/shim/test/regression/test_libos.py, line 903 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-MkrCEty0hFgP20FXpd-:-MkrCEty0hFgP20FXpd0:bvxk7wj) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/test_libos.py#L903)):*
> ```Python
>         self.assertIn('CREATION OK', stdout)
>         stdout, _ = self.run_binary(['sealed_file_mod', pf_path])
>         self.assertIn('READING FROM MODIFIED ENCLAVE OK', stdout)
> ```

Now that we have this nice hack, could we also test the negative cases? At least that wrong MRENCLAVE can't open an MRENCLAVE-bound file.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAy452L3W7ezRRt2f:-MkrCb108ka6xU8pNjVy:b524prd) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is an SGX constant, it must be `uint16_t`, see Intel SDM, Table 37-25.
</blockquote></details>

Why? The _value_ is defined by the manual, the type doesn't matter here.
___
*[Pal/src/host/Linux-SGX/enclave_pf.h, line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoGMVj8QR4SYcHZqpj:-MkrCugk2kb-HuivKqi_:b32vhw) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_pf.h#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I guess I can't master enums :)
</blockquote></details>

:)
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 452 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-MkrDGE93wcOR6Vfn3nG:-MkrDGE93wcOR6Vfn3nH:b-uv3ivb) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/Pal/src/host/Linux-SGX/enclave_pf.c#L452)):*
> ```C
>             return 0;
>     }
>     log_error("Invalid key type when registering protected files!");
> ```

Waait, this isn't something that can happen in runtime? We're specifying this enum in our own callsites? I'd just change it to return `const char*` and assume/assert that the caller is sane.

Or am I missing something?


<!-- Sent from Reviewable.io -->

2021-10-01 06:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 11 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/rw_file.c, line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr81rJ2CKKy59d-WWV:-MkuTnSn4qUbXAlreMiG:b-j4uc50) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should go first, see our styleguide
</blockquote></details>

Done, sorry.
___
*[LibOS/shim/test/regression/rw_file.c, line 67 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr7mTX7HNYd8y3P1Kt:-MkuTsQ85Zy0lGi0dHVE:b-nfhgrz) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you dropped "b"?
</blockquote></details>

Because it is not needed at all. From `man fopen`:
```
       The mode string can also include the letter 'b' either as a last character or as a character between the characters
       in  any  of  the  two-character  strings  described  above.  This is strictly for compatibility with C89 and has no
       effect; the 'b' is ignored on all POSIX conforming systems, including Linux.
```
___
*[LibOS/shim/test/regression/test_libos.py, line 903 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-MkrCEty0hFgP20FXpd-:-MkuXDLvEsZkw94o3Mi1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/test_libos.py#L903)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now that we have this nice hack, could we also test the negative cases? At least that wrong MRENCLAVE can't open an MRENCLAVE-bound file.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAy452L3W7ezRRt2f:-Mku_OaVEhPIteEptzvv:bm0i8l0) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why? The _value_ is defined by the manual, the type doesn't matter here.
</blockquote></details>

I don't understand what you mean by this. The value for `key_policy` is not a normal integer 0,1,2,3... `key_policy` is actually a bitmask (bit 0 to bind to MRENCLAVE, bit 1 to bind to MRSIGNER, bit 2 to bind to PRODID, etc.). The values may be combined, i.e. it is perfectly legal to have `SGX_KEYPOLICY_MRENCLAVE | SGX_KEYPOLICY_MRSIGNER` value. We don't do we in our code, currently, because we don't have use cases for this.

But we cannot really use an enum here. Please check Table 37-25. I added some more explanations in `sgx_arch.h`.

Also note that this function `sgx_get_seal_key()` is low-level and very close to SGX hardware, so I don't want to abstract away the fact that `key_policy` is a bitmask.

If it's still confusing, how could I make the code clearer? I could add suffix `_BIT` to keypolicies but we don't have such a notation in any other places, so...
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 452 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-MkrDGE93wcOR6Vfn3nG:-Mku_NLJ2mU-DKR-Z42B:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/Pal/src/host/Linux-SGX/enclave_pf.c#L452)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Waait, this isn't something that can happen in runtime? We're specifying this enum in our own callsites? I'd just change it to return `const char*` and assume/assert that the caller is sane.

Or am I missing something?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 13:19 UTC, mkow reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/rw_file.c, line 67 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr7mTX7HNYd8y3P1Kt:-Mkvy9qQEFeI5SbV7qdA:bewpfif) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because it is not needed at all. From `man fopen`:
```
       The mode string can also include the letter 'b' either as a last character or as a character between the characters
       in  any  of  the  two-character  strings  described  above.  This is strictly for compatibility with C89 and has no
       effect; the 'b' is ignored on all POSIX conforming systems, including Linux.
```
</blockquote></details>

Yeah, I know, but on other systems (aka Windows) it's required and causes very weird behavior if not used, so I prefer to use "b"/no "b" correctly everywhere, just in case someone reuses this code in the future.
Also, something which I don't like much more: you made this small change silently while moving the function between files, it's super hard to notice in the diff (and it's unrelated to the PR).
Anyways, I won't block on this, but I don't like this change ;)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoAy452L3W7ezRRt2f:-MkvzKr69sZz0zJhCK2p:barlajj) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand what you mean by this. The value for `key_policy` is not a normal integer 0,1,2,3... `key_policy` is actually a bitmask (bit 0 to bind to MRENCLAVE, bit 1 to bind to MRSIGNER, bit 2 to bind to PRODID, etc.). The values may be combined, i.e. it is perfectly legal to have `SGX_KEYPOLICY_MRENCLAVE | SGX_KEYPOLICY_MRSIGNER` value. We don't do we in our code, currently, because we don't have use cases for this.

But we cannot really use an enum here. Please check Table 37-25. I added some more explanations in `sgx_arch.h`.

Also note that this function `sgx_get_seal_key()` is low-level and very close to SGX hardware, so I don't want to abstract away the fact that `key_policy` is a bitmask.

If it's still confusing, how could I make the code clearer? I could add suffix `_BIT` to keypolicies but we don't have such a notation in any other places, so...
</blockquote></details>

Ah, yup, this was confusing to me, I thought this is an enum, especially that you have that assert below which checks for the only 2 legal values.
I see you added a comment there, looks better now and I don't have better ideas how to make it clearer.


<!-- Sent from Reviewable.io -->

2021-10-01 13:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/rw_file.c, line 67 at r3](https://reviewable.io/reviews/gramineproject/gramine/101#-Mkr7mTX7HNYd8y3P1Kt:-Mkw6C_-9LJnoVHiZOnL:bvrsk1t) ([raw file](https://github.com/gramineproject/gramine/blob/e3b001f68eee461e88ed1319b6589a6f2fbf0243/LibOS/shim/test/regression/rw_file.c#L67)):*
> Also, something which I don't like much more: you made this small change silently while moving the function between files, it's super hard to notice in the diff (and it's unrelated to the PR).

True, I should have mentioned it as a comment in Reviewable. Sorry, will do in the future.


<!-- Sent from Reviewable.io -->

2021-10-02 21:42 UTC, pwmarcz requested changes
> Reviewed 2 of 11 files at r1, 8 of 14 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1tgmA8pqVgQlRL45n:-Ml1tgmB9pyfAQgwDWax:b7vzium) (no related file):*
These `read_write` functions are pretty bad (see multiple comments below). Maybe it's better not to touch them at all in this PR?

I remember writing a very similar test recently (`send_handle.c`), it has these "write N bytes to a file" and "read N bytes from a file" loops in-line, and they ended up being pretty simple (mostly because errors by `err` and `errx`...). Probably using a dedicated helper functions would be better, but using a _broken_ helper function sounds worse (and a function like `read_write` sounds like a bad abstraction anyway).

---
___
*[Documentation/manifest-syntax.rst, line 549 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1gAvL0sg_zuC-i_Y_:-Ml1gAvMDG5wNMGsjj77:bivefz1) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/Documentation/manifest-syntax.rst#L549)):*
> ```reStructuredText
>    :doc:`attestation`).
> 
> ``sgx.protected_files`` are encrypted using the wrap (master) encryption key;
> ```

Nitpick: this would be more readable as three different paragraphs, or even a bullet list with three bullet points.
___
*[LibOS/shim/test/regression/rw_file.c, line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1keVr8etkaoesQWaI:-Ml1keVs2zX47ERRnUv0:b-w0bz5e) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L36)):*
> ```C
>             /* end of file */
>             if (rv == 0)
>                 fprintf(stderr, "%s failed: unexpected end of file\n", do_write ? "write" : "read");
> ```

We print an error here, but we don't return failure. 

Also, why is this an error? I understand these functions are allowed to read less bytes than `bytes`, and also write less bytes than `bytes`. But then why is 0 bytes (empty file?) special?
___
*[LibOS/shim/test/regression/rw_file.c, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1m4u-95uI5y8TK0QW:-Ml1m4u-95uI5y8TK0QX:b14uapc) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L49)):*
> ```C
> 
> out:
>     if (ret < 0) {
> ```

This looks pretty bad: if we just came from `goto out`, we're basically on a separate path (so why not `goto err`?); and we fell through from above, it's hard to notice where `ret` came from.

How about something like this (and explicit -1 instead of error for `ret`, perhaps?):

```diff
         if (ret < 0) {
             ...
+            rv = -1;
             goto out;
         }
     }

 out:
     ret = close(fd);
     if (ret < 0) {
         fprintf(stderr, "closing %s failed\n", path);
         return -1;
     }
     return rv;
```

I think other functions would also benefit from refactoring them the same way, so that all three look similar.
___
*[LibOS/shim/test/regression/rw_file.c, line 88 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1ne8xEPC6gvpb0aZe:-Ml1ne8xEPC6gvpb0aZf:blwsn9c) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L88)):*
> ```C
>                 }
>                 assert(rv == 0);
>                 fprintf(stderr, "%s failed: unexpected end of file\n", do_write ? "write" : "read");
> ```

Same as above: why is this a failure? `rw_file.h` doesn't say anything about empty files not being allowed.
___
*[LibOS/shim/test/regression/rw_file.c, line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1oz7y0qHo3ZuBzz4C:-Ml1oz7y0qHo3ZuBzz4D:b-x0diq) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L129)):*
> ```C
>                 continue;
>             } else {
>                 fprintf(stderr, "%s failed:%s\n", do_write ? "write" : "read", strerror(errno));
> ```

And this one actually always fails for `ret == 0`, so I guess it's not allowed to process less than `bytes` bytes? But then on EOF it returns 0, not -1...

As said above: please at least make these three function behaves the same.
___
*[LibOS/shim/test/regression/sealed_file.c, line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1q-2WDivvzVlK2f1p:-Ml1q-2WDivvzVlK2f1q:b5tncxq) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L28)):*
> ```C
>         if (errno == ENOENT) {
>             /* file is not yet created, create with secret string */
>             bytes = rw_file_stdio(argv[1], SECRETSTRING, sizeof(SECRETSTRING), /*do_write=*/true);
> ```

You write the null terminator here, is it intentional?

I think it would be better to `#define SECRETSTRING_LEN (sizeof(SECRETSTRING) - 1)`, and then use that.
___
*[LibOS/shim/test/regression/sealed_file.c, line 42 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1pndJ5zx9zYOv-23x:-Ml1pndJ5zx9zYOv-23y:b-d4xnli) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L42)):*
> ```C
>     bytes = rw_file_stdio(argv[1], buf, sizeof(buf), /*do_write=*/false);
>     if (bytes <= 0) {
>         /* error is already printed by rw_file_f() */
> ```

As mentioned before, I don't think `bytes == 0` should be considered an error. Instead, you can check for `bytes < 0` and then if `bytes` is exactly the right length.
___
*[LibOS/shim/test/regression/sealed_file.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1r65v6lExzrUGB2NA:-Ml1r65v6lExzrUGB2NB:b5b2f98) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L45)):*
> ```C
>         return EXIT_FAILURE;
>     }
>     buf[bytes - 1] = '\0';
> ```

You're throwing away the last byte of file content, it's pretty confusing...

(My solution for that was: don't use `str(n)cmp` at all, check if `bytes` is exactly to the right length and then do `memcmp`).


<!-- Sent from Reviewable.io -->

2021-10-02 21:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1tgmA8pqVgQlRL45n:-Ml1zgI-8qKsYyu0oFui:b-p84k2q) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

These `read_write` functions are pretty bad (see multiple comments below). Maybe it's better not to touch them at all in this PR?

I remember writing a very similar test recently (`send_handle.c`), it has these "write N bytes to a file" and "read N bytes from a file" loops in-line, and they ended up being pretty simple (mostly because errors by `err` and `errx`...). Probably using a dedicated helper functions would be better, but using a _broken_ helper function sounds worse (and a function like `read_write` sounds like a bad abstraction anyway).
</blockquote></details>

Okay, as we just discussed with @mkow on Gitter, I agree actually fixing these functions might be a better way to go.

---


<!-- Sent from Reviewable.io -->

2021-10-03 10:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 10 of 16 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1tgmA8pqVgQlRL45n:-Ml4l-J52CzFiGwDdfDG:b-1v3da5) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, as we just discussed with @mkow on Gitter, I agree actually fixing these functions might be a better way to go.
</blockquote></details>

Done. As Michal mentioned, I just copied these functions as-is from respective test files. But yes, their quality was pretty bad. I rewrote them completely.

---
___
*[Documentation/manifest-syntax.rst, line 549 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1gAvL0sg_zuC-i_Y_:-Ml4TvZG8Sd--lflweye:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/Documentation/manifest-syntax.rst#L549)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nitpick: this would be more readable as three different paragraphs, or even a bullet list with three bullet points.
</blockquote></details>

Done
___
*[LibOS/shim/test/regression/rw_file.c, line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1keVr8etkaoesQWaI:-Ml4l8_C6VLEYMNRqvga:b-26obiv) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L36)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We print an error here, but we don't return failure. 

Also, why is this an error? I understand these functions are allowed to read less bytes than `bytes`, and also write less bytes than `bytes`. But then why is 0 bytes (empty file?) special?

</blockquote></details>

Done. We now always treat this as no error (and don't print any warnings as well).
___
*[LibOS/shim/test/regression/rw_file.c, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1m4u-95uI5y8TK0QW:-Ml4lDp65_8g6K132BMS:bz5rnvz) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This looks pretty bad: if we just came from `goto out`, we're basically on a separate path (so why not `goto err`?); and we fell through from above, it's hard to notice where `ret` came from.

How about something like this (and explicit -1 instead of error for `ret`, perhaps?):

```diff
         if (ret < 0) {
             ...
+            rv = -1;
             goto out;
         }
     }

 out:
     ret = close(fd);
     if (ret < 0) {
         fprintf(stderr, "closing %s failed\n", path);
         return -1;
     }
     return rv;
```

I think other functions would also benefit from refactoring them the same way, so that all three look similar.
</blockquote></details>

Done. Well, differently, but made it reasonable now (hopefully).
___
*[LibOS/shim/test/regression/rw_file.c, line 88 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1ne8xEPC6gvpb0aZe:-Ml4lIppE5__sDJjUeR0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L88)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Same as above: why is this a failure? `rw_file.h` doesn't say anything about empty files not being allowed.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.c, line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1oz7y0qHo3ZuBzz4C:-Ml4lJWhAIlpGLKugkxr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L129)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

And this one actually always fails for `ret == 0`, so I guess it's not allowed to process less than `bytes` bytes? But then on EOF it returns 0, not -1...

As said above: please at least make these three function behaves the same.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1q-2WDivvzVlK2f1p:-Ml4icN39H5k3bjAwc8p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L28)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You write the null terminator here, is it intentional?

I think it would be better to `#define SECRETSTRING_LEN (sizeof(SECRETSTRING) - 1)`, and then use that.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 42 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1pndJ5zx9zYOv-23x:-Ml4igFq53_jF_ZWDEyE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

As mentioned before, I don't think `bytes == 0` should be considered an error. Instead, you can check for `bytes < 0` and then if `bytes` is exactly the right length.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1r65v6lExzrUGB2NA:-Ml4kzG23iK7Ret19hYT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/sealed_file.c#L45)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You're throwing away the last byte of file content, it's pretty confusing...

(My solution for that was: don't use `str(n)cmp` at all, check if `bytes` is exactly to the right length and then do `memcmp`).


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-03 11:21 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`test-direct / apps.LTP.sendfile09` timed out, known issue)

2021-10-03 11:22 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (`test-direct / apps.LTP.fcntl14` and `test-direct / apps.LTP.sendfile09_64` timed out, known issue)

2021-10-03 12:09 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1tgmA8pqVgQlRL45n:-Ml52Zaa3b_ZDNUbv4dW:b-u0uyx2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. As Michal mentioned, I just copied these functions as-is from respective test files. But yes, their quality was pretty bad. I rewrote them completely.
</blockquote></details>

Thanks, that looks much better now! I left some nitpick comments, but nothing blocking.

---
___
*[LibOS/shim/test/regression/rw_file.c, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml1m4u-95uI5y8TK0QW:-Ml5021a18zqYtSh0aYh:bf7oesf) ([raw file](https://github.com/gramineproject/gramine/blob/60f382f0d73f1d0ab5d601da4344321228d4f4b4/LibOS/shim/test/regression/rw_file.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Well, differently, but made it reasonable now (hopefully).
</blockquote></details>

Looks much better, thanks! I like how you extracted file open/close to a separate function.
___
*[LibOS/shim/test/regression/rw_file.c, line 75 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml51c2j5h1in7y8apBa:-Ml51c2k7UxR8keQl0qU:bdv8hws) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/rw_file.c#L75)):*
> ```C
>     if (transferred < 0) {
>         int olderrno = errno;
>         close(fd);
> ```

Nice to have: a warning if `close()` fails here, and same for `fclose()` below. I don't think it's important, though.
___
*[LibOS/shim/test/regression/rw_file.c, line 96 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml51seGC8WN1x4ngL33:-Ml51seGC8WN1x4ngL34:bgdd63p) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/rw_file.c#L96)):*
> ```C
>     }
> ```

Nitpick: unnecessary extra line.
___
*[LibOS/shim/test/regression/sealed_file.c, line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5275c8J_4mck2vc4L:-Ml5275c8J_4mck2vc4M:bdd5nbs) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/sealed_file.c#L44)):*
> ```C
>     }
> 
>     char buf[128];
> ```

Nitpick: `buf[SECRETSTRING_LEN]`?


<!-- Sent from Reviewable.io -->

2021-10-03 12:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 14 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5AIfY5LEF5i8hiDPe):*
TODO: during final rebase, need to say something like `As a side effect, read/write utilities are extracted into a separate rw_file.c.`
___
*[LibOS/shim/test/regression/rw_file.c, line 75 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml51c2j5h1in7y8apBa:-Ml5ACr0Ako4G7Lff-Q0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/rw_file.c#L75)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nice to have: a warning if `close()` fails here, and same for `fclose()` below. I don't think it's important, though.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.c, line 96 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml51seGC8WN1x4ngL33:-Ml5ADzk5c78SEBtC_6E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/rw_file.c#L96)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nitpick: unnecessary extra line.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5275c8J_4mck2vc4L:-Ml5AFPwDbZUqslglLWt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a2b85b2bee2d57e92987e6fba6853d68c270798/LibOS/shim/test/regression/sealed_file.c#L44)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nitpick: `buf[SECRETSTRING_LEN]`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-03 12:52 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-03 14:09 UTC, mkow requested changes
> Reviewed 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/rw_file.h, line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5Oav0AtR6Nsdm-GBm:-Ml5Oav141xLTSCIw1hL:b-37ou05) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L16)):*
> ```objc
> 
> /* Open file `path`, read/write at most `count` bytes into/from buffer `buf`, and close the file.
>  * Use POSIX functions: open, read/write, close. */
> ```

`Open` -> `Opens`, `Use` -> `Uses`
___
*[LibOS/shim/test/regression/rw_file.h, line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OfNo0IoxvxSW0EIi:-Ml5OfNpC1cqjDSzEOmm:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L21)):*
> ```objc
> 
> /* Open file `path`, read/write at most `count` bytes into/from buffer `buf`, and close the file.
>  * Use stdio functions: fopen, fread/fwrite, fclose. */
> ```

ditto
___
*[LibOS/shim/test/regression/rw_file.h, line 25 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OhXn78BxdIJuUcMf:-Ml5OhXn78BxdIJuUcMg:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L25)):*
> ```objc
> ssize_t stdio_file_write(const char* path, char* buf, size_t count);
> 
> /* Read/write at most `count` bytes into/from buffer `buf`. Use POSIX functions: read/write. */
> ```

ditto
___
*[LibOS/shim/test/regression/rw_file.h, line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OiERC2Ys93UX46Zw:-Ml5OiERC2Ys93UX46Zx:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L29)):*
> ```objc
> ssize_t posix_fd_write(int fd, char* buf, size_t count);
> 
> /* Read/write at most `count` bytes into/from buffer `buf`. Use stdio functions: fread/fwrite. */
> ```

ditto
___
*[LibOS/shim/test/regression/rw_file.c, line 78 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5RJhN0DcyfTfsWzs_:-Ml5RJhN0DcyfTfsWzsa:b-kemz6e) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.c#L78)):*
> ```C
>         if (close_ret < 0)
>             warn("close (during error handling)");
>         errno = olderrno;
> ```

Do we actually use `errno` in the callsites and declare it as part of return values in this function? If so, then `warn()` below may override it in the other code path.
___
*[LibOS/shim/test/regression/rw_file.c, line 110 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5RcAY-wHmys2rv6rv:-Ml5RcAY-wHmys2rv6rw:b-w7khl0) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.c#L110)):*
> ```C
>     int close_ret = fclose(f);
>     if (close_ret < 0) {
>         warn("close");
> ```

ditto (`errno`)
___
*[LibOS/shim/test/regression/sealed_file.c, line 31 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5TUhQ9tqujoukiPhm:-Ml5TUhQ9tqujoukiPhn:b-lro0nx) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/sealed_file.c#L31)):*
> ```C
>             bytes = stdio_file_write(argv[1], SECRETSTRING, SECRETSTRING_LEN);
>             if (bytes < 0) {
>                 /* error is already printed by stdio_file_read() */
> ```

`read` -> `write`


<!-- Sent from Reviewable.io -->

2021-10-03 14:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 13 of 16 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/test/regression/rw_file.h, line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5Oav0AtR6Nsdm-GBm:-Ml5XIzI3zXOzW2m9A3r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Open` -> `Opens`, `Use` -> `Uses`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.h, line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OfNo0IoxvxSW0EIi:-Ml5XJIo9_Py1p6vcKao:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.h, line 25 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OhXn78BxdIJuUcMf:-Ml5XJg13sq6Ud0LLpxr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.h, line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5OiERC2Ys93UX46Zw:-Ml5XK279lhYXauT9Krr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.h#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rw_file.c, line 78 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5RJhN0DcyfTfsWzs_:-Ml5Y4bi1HvQ7Ihdtzp3:blrauo3) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.c#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we actually use `errno` in the callsites and declare it as part of return values in this function? If so, then `warn()` below may override it in the other code path.
</blockquote></details>

Done. Right. (And yes, we declare `errno` as part of a return value in these functions.)
___
*[LibOS/shim/test/regression/rw_file.c, line 110 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5RcAY-wHmys2rv6rv:-Ml5YA4LDUSPOU7oW6bU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/rw_file.c#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`errno`)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sealed_file.c, line 31 at r6](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5TUhQ9tqujoukiPhm:-Ml5YGhlELaW5KjfzhTg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee31745c4e753798860be398cab9decc6568c6f6/LibOS/shim/test/regression/sealed_file.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`read` -> `write`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-03 14:49 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-10-03 14:49 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`test-direct / apps.LTP.sendfile09` LTP test timed out, unrelated)

2021-10-03 15:11 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-10-03 18:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 9 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/101#-Ml5AIfY5LEF5i8hiDPe):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: during final rebase, need to say something like `As a side effect, read/write utilities are extracted into a separate rw_file.c.`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-03 19:12 UTC, mkow requested changes
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoDhR8DylQoqfzJIPF:-Ml6ZbiR2yY9GBGqpe-s:btfztha) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Added a FIXME comment not to forget about this during rebase.
</blockquote></details>

Forgot about this one? ;)


<!-- Sent from Reviewable.io -->

2021-10-03 19:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: 15 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/101#-MkoDhR8DylQoqfzJIPF:-Ml6aOdn6aSFPIW-14Z2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/178996fa8c2c679e6635aeded08f50ef7161523f/Pal/src/host/Linux-SGX/enclave_framework.c#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Forgot about this one? ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-03 19:39 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-03 20:00 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-10-03 20:03 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/101)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-03 21:41 UTC, merged