[PAL/Linux-SGX] Add Invariant TSC query fallback for hypervisors
gramineproject/gramine pull request #1012
Opened 2022-10-26 14:35 UTC by dimakuv

## Description of the changes 

Some hypervisors (like QEMU/KVM) do not expose CPUID leaves 0x15 and 0x16 (Core Crystal Clock/Process Frequency). Instead, hypervisor-specific CPUID leaf 0x40000010 shows TSC frequency.

Note that QEMU/VKM must start the VM with CPU flags `+invtsc,+vmware-cpuid-freq` to expose required CPUID leaves.

Fixes #1009.

See also https://lwn.net/Articles/301888/.

## How to test this PR? 

Need a VM. See https://github.com/gramineproject/gramine/issues/1009.

2022-10-26 14:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 266 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFJibIM5tMnil46nqZ3:-NFJibIM5tMnil46nqZ4:bgneyql) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L266)):*
> ```C
>  * through xfrm what extensions are enabled inside the enclave.
>  */
> static void sanitize_cpuid(uint32_t leaf, uint32_t subleaf, uint32_t values[4]) {
> ```

FYI: I was wondering if I should try to sanitize the new leaves 0x40000000 and 0x40000010, but didn't come up with any interesting checks for them.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 662 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFJisET-6490KhuR4EJ:-NFJisET-6490KhuR4EK:b-l57k36) ([raw file](https://github.com/gramineproject/gramine/blob/ef469815a743c17dbf192fdb19f18e5248720bb4/pal/src/host/linux-sgx/pal_misc.c#L662)):*
> ```C
> }
> 
> bool is_tsc_usable(void) {
> ```

FYI: I simply moved these functions above, to make them `static`. No changes in the code.


<!-- Sent from Reviewable.io -->

2022-10-26 22:50 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NFLThV16UCccKRdBFDn:b-1mvkoz) (no related file):*
After digging a bit into this:
- it was not merge to Linux (KVM)
- it's originally introduced by vmware
- emulation was added to QEMU in 2021
- it's purely hypervisor specific, i.e. you cannot assume that CPUID `0x40000010` such information (without checking 0x40000000 first)

Given the above, cant we obtain this information from some `/sys` interfaces? CPUID doesn't seem to be a good source...

___


<!-- Sent from Reviewable.io -->

2022-10-27 07:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NFNOa4y73Nnr8ZxZNZA:b-1jx3et) (no related file):*
> it's purely hypervisor specific, i.e. you cannot assume that CPUID 0x40000010 such information (without checking 0x40000000 first)

We do this check in this PR.

> Given the above, cant we obtain this information from some /sys interfaces?

I tried to look around, I don't see anything that would give us TSC frequency in the `sys/` interfaces.

FWIW, I was able to google that it's also used in:
- ACRN hypervisor, https://docs.kernel.org/virt/acrn/cpuid.html
- `raw_cpuid` crate (can't check where it's used but seems like a popular lib), https://docs.rs/crate/raw-cpuid/6.1.0/source/src/lib.rs

Cloud Hypervisor seems to just propagate all CPUID leaves, including 0x15 and 0x16, based on this code https://github.com/rust-vmm/vmm-reference/blob/5cde58bc955afca8a180585a9f01c82d6277a755/src/vm-vcpu-ref/src/x86_64/cpuid.rs#L66

All in all, this seems like a useful fallback to verify. I don't see other ways.

___


<!-- Sent from Reviewable.io -->

2022-10-27 11:33 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NFO4kcr6LJmE1pg3KYk:blaqlaw) (no related file):*
> We do this check in this PR.

No, we only check that `0x40000010` is a valid CPUID, not that current hypervisor is in list of hypervisors exposing TCS info in `0x40000010` (and how would you get such list is beyond me).

> Cloud Hypervisor seems to just propagate all CPUID leaves, including 0x15 and 0x16, based on this code https://github.com/rust-vmm/vmm-reference/blob/5cde58bc955afca8a180585a9f01c82d6277a755/src/vm-vcpu-ref/src/x86_64/cpuid.rs#L66

This code doesn't seem to be related to anything, just some random testing crate with "should NOT be used in production" disclaimer.

Generally I don't know anything about hypervisor standarizations and seems that at least a couple of major VM implementations/hypervisors support it, so I'm unblocking.

___
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO7l0xDoTIw3d44PUB):*
Maybe it does, maybe it doesn't, who knows
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO7ciL7WzUulAnVEwA):*
KVM does not expose it, as far as I know
also typo (`VKM`)
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO88ir6eek9dsbnbGu:-NFO88ir6eek9dsbnbGv:b-thf9js) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L32)):*
> ```C
> #define TSC_REFINE_INIT_TIMEOUT_USECS 50000
> 
> #define CPU_VENDOR_LEAF             0x0
> ```

Can we keep this list sorted by value? Otherwise I don't know how can we manage it
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFOCYGh28d7NRP1XsY8:-NFOCYGh28d7NRP1XsY9:b-gdnkj9) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L93)):*
> ```C
>      * We rely on the Generic CPUID space for hypervisors (KVM in particular):
>      *   - 0x40000000: EAX: The maximum input value for CPUID supported by the hypervisor
>      *   - 0x40000010: EAX: (Virtual) TSC frequency in kHz
> ```

This is not true for KVM, afaik
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFOCZyJBXg7eMdpiCbY:-NFOCZyJBXg7eMdpiCbZ:bls2l2u) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L95)):*
> ```C
>      *   - 0x40000010: EAX: (Virtual) TSC frequency in kHz
>      *
>      * See also https://lwn.net/Articles/301888.
> ```

This was never merged, afaik


<!-- Sent from Reviewable.io -->

2022-10-28 08:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NFSaIpr-SjwxWaHUzqx:bxgexec) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> We do this check in this PR.

No, we only check that `0x40000010` is a valid CPUID, not that current hypervisor is in list of hypervisors exposing TCS info in `0x40000010` (and how would you get such list is beyond me).

> Cloud Hypervisor seems to just propagate all CPUID leaves, including 0x15 and 0x16, based on this code https://github.com/rust-vmm/vmm-reference/blob/5cde58bc955afca8a180585a9f01c82d6277a755/src/vm-vcpu-ref/src/x86_64/cpuid.rs#L66

This code doesn't seem to be related to anything, just some random testing crate with "should NOT be used in production" disclaimer.

Generally I don't know anything about hypervisor standarizations and seems that at least a couple of major VM implementations/hypervisors support it, so I'm unblocking.
</blockquote></details>

Sorry, I didn't do my due diligence. I researched this question a bit and got even more confused with the current status...

I sent an email to several Intel VMM experts, I hope they can shed some light. Here is the content of my email:

---

We noticed that when running Gramine inside a VM, some CPUID leaves (0x15 and 0x16) are "hidden" by QEMU/KVM. So instead, we want to rely on hypervisor-provided information about TSC frequency, to get correct clock readings (if this Invariant TSC Frequency feature is available).

We found the proposal about using CPUID leaf 0x40000010 for exactly this purpose: https://lwn.net/Articles/301888/. At the same time, it looks like this proposal didn't make it into any standard and didn't make it into Linux (more specifically, into KVM).

At the same time, we know that QEMU implements it: https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.h#L1870-L1872

KVM itself seems to only implement CPUID leaves  0x40000000 and  0x40000001, if I understand the latest Linux docs correctly: https://www.kernel.org/doc/html/latest/virt/kvm/api.html#kvm-get-supported-hv-cpuid. But hypervisors may overwrite these leaves (again, if I understand it correctly).

CloudHypervisor seems to expose CPUID leaves 0x40000000 - 0x4000000a (https://github.com/cloud-hypervisor/cloud-hypervisor/blob/d4d0780b8906842baa7162d8efb1619dcf7d2cc9/arch/src/x86_64/mod.rs#L675-L720), but only leaves 0x40000000 - 0x40000003 contain some values. So in CloudHypervisor, leaf 0x40000010 seems to return all-zeros.

Also, Hypervisor Tol-Level Functional Specification from Microsoft (TLFS) mentions only leaves 0x40000000 - 0x40000009 (plus leaf 0x4000000a). From what I gather, many hypervisor implementations follow this spec, so it means that no one is mandated to implement 0x40000010 (only QEMU does it, and ACRN too).

---

Let's see if I get some definitive reply. I still think the PR is useful, but maybe it's QEMU-specific, and our comments should clearly state this.

___


<!-- Sent from Reviewable.io -->

2023-02-08 12:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NNl2okM3SyiAiz-XjjT:bmf33xl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I didn't do my due diligence. I researched this question a bit and got even more confused with the current status...

I sent an email to several Intel VMM experts, I hope they can shed some light. Here is the content of my email:

---

We noticed that when running Gramine inside a VM, some CPUID leaves (0x15 and 0x16) are "hidden" by QEMU/KVM. So instead, we want to rely on hypervisor-provided information about TSC frequency, to get correct clock readings (if this Invariant TSC Frequency feature is available).

We found the proposal about using CPUID leaf 0x40000010 for exactly this purpose: https://lwn.net/Articles/301888/. At the same time, it looks like this proposal didn't make it into any standard and didn't make it into Linux (more specifically, into KVM).

At the same time, we know that QEMU implements it: https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.h#L1870-L1872

KVM itself seems to only implement CPUID leaves  0x40000000 and  0x40000001, if I understand the latest Linux docs correctly: https://www.kernel.org/doc/html/latest/virt/kvm/api.html#kvm-get-supported-hv-cpuid. But hypervisors may overwrite these leaves (again, if I understand it correctly).

CloudHypervisor seems to expose CPUID leaves 0x40000000 - 0x4000000a (https://github.com/cloud-hypervisor/cloud-hypervisor/blob/d4d0780b8906842baa7162d8efb1619dcf7d2cc9/arch/src/x86_64/mod.rs#L675-L720), but only leaves 0x40000000 - 0x40000003 contain some values. So in CloudHypervisor, leaf 0x40000010 seems to return all-zeros.

Also, Hypervisor Tol-Level Functional Specification from Microsoft (TLFS) mentions only leaves 0x40000000 - 0x40000009 (plus leaf 0x4000000a). From what I gather, many hypervisor implementations follow this spec, so it means that no one is mandated to implement 0x40000010 (only QEMU does it, and ACRN too).

---

Let's see if I get some definitive reply. I still think the PR is useful, but maybe it's QEMU-specific, and our comments should clearly state this.
</blockquote></details>

Ok, I'm done with my explorations. Here are the results:
- VMWare was the first to introduce "TSC Frequency" synthetic CPUID leaf `0x40000010`
- QEMU with KVM implemented the same logic as in VMWare in 2017: https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2
- Microsoft Hyper-V does **not** implement CPUID leaf `0x40000010`
    - Moreover, because this leaf is not standardized, Hyper-V can use this leaf for something completely different (in the future, currently it doesn't use it at all)
- Cloud Hypervisor doesn't use this leaf, and it inits it to all-zeros
- I didn't check other popular hypervisors (VirtualBox, Xen), but I also didn't encounter people running Gramine on these VMMs

Related materials (sorry, just a dump):
- https://patchwork.kernel.org/project/qemu-devel/patch/1484749457-87117-1-git-send-email-phil@philjordan.eu/
- https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2
- https://github.com/qemu/qemu/commit/303752a9068bfe84b9b05f1cd5ad5ff65b7f3ea6
- https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.h
- https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.c
- https://github.com/qemu/qemu/blob/fcb7e040f5c69ca1f0678f991ab5354488a9e192/target/i386/kvm/kvm.c
- https://kb.vmware.com/s/article/1009458
- https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1372-L1377

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNl2id53m2O7QouAGfE:-NNl2id53m2O7QouAGfF:b6iropo) (no related file):*
I rebased to latest master to incorporate changes from https://github.com/gramineproject/gramine/commit/7f72f133d134cd1e11294209a3702d555837ccb9

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNl4LHf42PKoZnVLYNu:-NNl4LHgCjzHB8ZVRyKe:bspk46r) (no related file):*
@mkow @oshogbo I hope you can take over the review of this PR, since @boryspoplawski is not active in the project anymore.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNl4URA0XKGvz9lYSsy:-NNl4URA0XKGvz9lYSsz:b-exbf7k) (no related file):*
FYI: MS Hyper-V (used in MS Azure cloud) currently has the problem of **not** exposing Invariant TSC frequency info in CPUID leaves (nor in 0x15 neither in 0x40000010). This is a known issue, and it will hopefully be fixed soon in this hypervisor (by exposing CPUID leaf 0x15 for SGX-enabled VMs). We brought this to Microsoft's attention.

___
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO7l0xDoTIw3d44PUB):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe it does, maybe it doesn't, who knows
</blockquote></details>

Done. Added more explanations, plus added some checks in the code.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO7ciL7WzUulAnVEwA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

KVM does not expose it, as far as I know
also typo (`VKM`)
</blockquote></details>

Done. I removed the KVM part, but what I was trying to say was "QEMU's KVM support" (see https://github.com/qemu/qemu/blob/fcb7e040f5c69ca1f0678f991ab5354488a9e192/target/i386/kvm/kvm.c)
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFO88ir6eek9dsbnbGu:-NNkgufaDjtXvaZQeroh:b-wl1621) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can we keep this list sorted by value? Otherwise I don't know how can we manage it
</blockquote></details>

Done. Actually, I rebased, and because of https://github.com/gramineproject/gramine/commit/7f72f133d134cd1e11294209a3702d555837ccb9, these leaves were moved to `common/include/arch/x86_64/cpu.h`
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFOCYGh28d7NRP1XsY8:-NNl1LJK8YrUUth0eLsJ:b8i8y23) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not true for KVM, afaik
</blockquote></details>

Done. Completely rewritten.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFOCZyJBXg7eMdpiCbY:-NNl1MnI-aPS7-dBexNG:b-8q18hm) ([raw file](https://github.com/gramineproject/gramine/blob/a8bc821c8b23dd0a6f5bfeb544bbfe5472079c7d/pal/src/host/linux-sgx/pal_misc.c#L95)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This was never merged, afaik
</blockquote></details>

Done, not relevant anymore


<!-- Sent from Reviewable.io -->

2023-02-08 15:04 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on Blender download)

2023-02-08 17:19 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on Blender download)

2023-02-08 19:02 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on Blender download). We really need to fix this.

2023-02-09 14:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNqVgN95tB6d5Lcf9PW:-NNqVgN95tB6d5Lcf9PX:bn16dey) (no related file):*
UPDATE: I reported this issue to Cloud Hypervisor, and they created a PR that will fix it: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5179

So I changed my comments in the code to mention Cloud Hypervisor too.

___


<!-- Sent from Reviewable.io -->

2023-02-10 16:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NNwE-aPDcUgKU4X_wHL:b-padosj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'm done with my explorations. Here are the results:
- VMWare was the first to introduce "TSC Frequency" synthetic CPUID leaf `0x40000010`
- QEMU with KVM implemented the same logic as in VMWare in 2017: https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2
- Microsoft Hyper-V does **not** implement CPUID leaf `0x40000010`
    - Moreover, because this leaf is not standardized, Hyper-V can use this leaf for something completely different (in the future, currently it doesn't use it at all)
- Cloud Hypervisor doesn't use this leaf, and it inits it to all-zeros
- I didn't check other popular hypervisors (VirtualBox, Xen), but I also didn't encounter people running Gramine on these VMMs

Related materials (sorry, just a dump):
- https://patchwork.kernel.org/project/qemu-devel/patch/1484749457-87117-1-git-send-email-phil@philjordan.eu/
- https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2
- https://github.com/qemu/qemu/commit/303752a9068bfe84b9b05f1cd5ad5ff65b7f3ea6
- https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.h
- https://github.com/qemu/qemu/blob/e750a7ace492f0b450653d4ad368a77d6f660fb8/target/i386/cpu.c
- https://github.com/qemu/qemu/blob/fcb7e040f5c69ca1f0678f991ab5354488a9e192/target/i386/kvm/kvm.c
- https://kb.vmware.com/s/article/1009458
- https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1372-L1377
</blockquote></details>

I may be missing something, but why virtualizers add this special and not-standardized leaf instead of just providing the very same info in leaves 0x15/0x16, which are standard? It makes no sense to me...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNqVgN95tB6d5Lcf9PW:-NNwE_P_AEcxi4AOpHNA:b-1okp9h) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

UPDATE: I reported this issue to Cloud Hypervisor, and they created a PR that will fix it: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5179

So I changed my comments in the code to mention Cloud Hypervisor too.
</blockquote></details>

ditto, why the special leaf number?

___


<!-- Sent from Reviewable.io -->

2023-02-13 10:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NO9J4ZF55knoamAHc3f:b-ecxxa2) (no related file):*
> I may be missing something, but why virtualizers add this special and not-standardized leaf instead of just providing the very same info in leaves 0x15/0x16, which are standard?

I can see several reasons, but to get a proper answer, you'll need to ask some VMM guru.

First, "Invariant TSC" functionality (and thus CPUID leaves 0x15/0x16) were introduced by Intel around 2014. However, TSC frequency was used long before that: in the very old days, on bare metal, it was done by parsing the frequency from the name of the CPU (they typically have smth like `CPU @ 2GHz`). Then CPU vendors started implementing different MSRs containing TSC frequency. However, VMMs prefer to expose only a minimal set of MSRs, so these ad-hoc MSRs with TSC frequency were hidden, and instead VMMs (well, VMWare started this somewhere before 2008) decided to provide this info in a special leaf. QEMU adopted this (somewhere in 2017), but not MS Hyper-V.

Second, VM migration was problematic. Typically, applications cache CPUID leaves' values on startup/first use. But then imagine that your application is migrated together with its VM from one CPU (`@ 2GHz`) to another CPU (`@ 3GHz`). TSC frequency is suddenly changed, but the app doesn't know about this, so it continues doing e.g. `rdtsc` plus scaling `rdtsc-value * tsc-frequency`, which is wrong on the new CPU.
- To prevent "wrong scaling factor" when migrating between CPUs, it makes sense to introduce some unified synthetic TSC frequency. This synthetic TSC frequency is reported by the VMM, and when migration happens, the app still performs `rdtsc-value * tsc-frequency`. Of course, the VMM also needs to tweak the RDTSC values, and for this there is a CPU feature called *TSC Scaling* (*TSC Multiplier*), which VMM configures before resuming the migrated VM.
- You may ask, why not then modify the CPUID leaves 0x15 and 0x16 to report this synthetic TSC frequency? Well, iiuc, it is a bad smell to *modify CPUID leaves* -- VMMs either expose the leaf or hide it, but never modify it. So that's why the new synthetic leaf was introduced.

That's my understanding of the problem. See related materials:
- https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2 (check the commit message)
- https://lwn.net/Articles/301888/
- https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/timestamp-counter-scaling-virtualization-white-paper.pdf

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NNqVgN95tB6d5Lcf9PW:-NO9N2laC6r8YZoTVUqu:b-bicm4n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto, why the special leaf number?
</blockquote></details>

see my explanations above

___


<!-- Sent from Reviewable.io -->

2023-02-24 03:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/1012#-NP0A_1c6Qczf99DEIxn):*
-> `Cloud Hypervisor/KVM`



_Code quote:_
```
  "VMwareVMware". To date, we know that VMWare, QEMU/KVM and Cloud
  Hypervisor expose this TSC-frequency leaf 0x40000010. MS Hyper-V does
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 102 at r3](https://reviewable.io/reviews/gramineproject/gramine/1012#-NP08QVMB9r_SGroOO7p:-NP08QVN9K5Y6QYUtuYY:b-4jmevr) ([raw file](https://github.com/gramineproject/gramine/blob/bae1c6dffa4d6243579db7d20638385101fc0998/pal/src/host/linux-sgx/pal_misc.c#L102)):*
> ```C
>     hypervisor_id[2] = words[CPUID_WORD_EDX];
>     if (memcmp(hypervisor_id, "KVMKVMKVM\0\0\0", 12) && memcmp(hypervisor_id, "VMWareVMWare", 12)) {
>         /* QEMU/KVM, Cloud Hypervisor/KVM and VMWare expose TSC frequency in leaf 0x40000010 */
> ```

Should we put this comment outside the condition block?



_Code quote:_
```C
/* QEMU/KVM, Cloud Hypervisor/KVM and VMWare expose TSC frequency in leaf 0x40000010 */
```


<!-- Sent from Reviewable.io -->

2023-02-24 09:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 0 of 3 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/1012#-NP0A_1c6Qczf99DEIxn):*
Good point. Context for other reviewers:

> Cloud Hypervisor is an open source Virtual Machine Monitor (VMM) that runs on top of the KVM hypervisor and the Microsoft Hypervisor (MSHV).

@ https://github.com/cloud-hypervisor/cloud-hypervisor#1-what-is-cloud-hypervisor

This leaf `0x40000010` is exposed only when Cloud Hypervisor runs on KVM. I'll change this during final rebase.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 102 at r3](https://reviewable.io/reviews/gramineproject/gramine/1012#-NP08QVMB9r_SGroOO7p:-NP1fBxF7AWsJ6p4iSn4:b-ur1v8o) ([raw file](https://github.com/gramineproject/gramine/blob/bae1c6dffa4d6243579db7d20638385101fc0998/pal/src/host/linux-sgx/pal_misc.c#L102)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we put this comment outside the condition block?
</blockquote></details>

Done. I actually removed this comment and replaced it with the other one (since it was a repetition of the comment I have above).

Also, made the IF check more explicit. My brain hurts every time I see `memcmp` and `strcmp` :)


<!-- Sent from Reviewable.io -->

2023-07-25 00:07 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-Na8GxA0B5jXT0nt4XLi:buw8pd6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I may be missing something, but why virtualizers add this special and not-standardized leaf instead of just providing the very same info in leaves 0x15/0x16, which are standard?

I can see several reasons, but to get a proper answer, you'll need to ask some VMM guru.

First, "Invariant TSC" functionality (and thus CPUID leaves 0x15/0x16) were introduced by Intel around 2014. However, TSC frequency was used long before that: in the very old days, on bare metal, it was done by parsing the frequency from the name of the CPU (they typically have smth like `CPU @ 2GHz`). Then CPU vendors started implementing different MSRs containing TSC frequency. However, VMMs prefer to expose only a minimal set of MSRs, so these ad-hoc MSRs with TSC frequency were hidden, and instead VMMs (well, VMWare started this somewhere before 2008) decided to provide this info in a special leaf. QEMU adopted this (somewhere in 2017), but not MS Hyper-V.

Second, VM migration was problematic. Typically, applications cache CPUID leaves' values on startup/first use. But then imagine that your application is migrated together with its VM from one CPU (`@ 2GHz`) to another CPU (`@ 3GHz`). TSC frequency is suddenly changed, but the app doesn't know about this, so it continues doing e.g. `rdtsc` plus scaling `rdtsc-value * tsc-frequency`, which is wrong on the new CPU.
- To prevent "wrong scaling factor" when migrating between CPUs, it makes sense to introduce some unified synthetic TSC frequency. This synthetic TSC frequency is reported by the VMM, and when migration happens, the app still performs `rdtsc-value * tsc-frequency`. Of course, the VMM also needs to tweak the RDTSC values, and for this there is a CPU feature called *TSC Scaling* (*TSC Multiplier*), which VMM configures before resuming the migrated VM.
- You may ask, why not then modify the CPUID leaves 0x15 and 0x16 to report this synthetic TSC frequency? Well, iiuc, it is a bad smell to *modify CPUID leaves* -- VMMs either expose the leaf or hide it, but never modify it. So that's why the new synthetic leaf was introduced.

That's my understanding of the problem. See related materials:
- https://github.com/qemu/qemu/commit/9954a1582e18b03ddb66f6c892dccf2c3508f4b2 (check the commit message)
- https://lwn.net/Articles/301888/
- https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/timestamp-counter-scaling-virtualization-white-paper.pdf
</blockquote></details>

Modifying CPUID leaves is something that is done all the time by hypervisors (see: emulated / hidden features in feature sets, CPU name strings, etc). As far as I can tell, the reasons here are:

- the vmware TSC CPUID leaf actually pre-dates leaf `0x15`
- rightly or not, leaf `0x15` is considered Intel-specific (eg. the Linux kernel won't even try looking at it unless CPUID vendor is Intel, so hypervisors will want to advertise it elsewhere)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8IJrwAPP98HmLmshO:-Na8IJrwAPP98HmLmshP:b9j1bah) (no related file):*
Overall, my impression is that this PR is making the best of a bad situation. The real problem here is that Linux kernel (which definitely has the information we need, and is in much better position to obtain it) has no good API to expose TSC information.

___
___
*[`common/include/arch/x86_64/cpu.h` line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8BK4qCbfYiRcOvg9v:-Na8BK4qCbfYiRcOvg9w:b-uhw3pe) ([raw file](https://github.com/gramineproject/gramine/blob/a1f88f0276a1b2ce5f255007e10536e18791d9df/common/include/arch/x86_64/cpu.h#L48)):*
> ```objc
> #define AMX_TMUL_INFO_LEAF                     0x1E
> #define HYPERVISOR_INFO_LEAF             0x40000000
> #define HYPERVISOR_TIME_LEAF             0x40000010
> ```

Please rename this to something with `VMWARE` in name, since it's not a generic leaf.



_Suggestion:_
```objc
#define HYPERVISOR_VMWARE_TIME_LEAF      0x40000010
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 503 at r4](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8Rt_e16RMqaiwcLzh:-Na8Rt_e16RMqaiwcLzi:b2ni8l0) ([raw file](https://github.com/gramineproject/gramine/blob/a1f88f0276a1b2ce5f255007e10536e18791d9df/pal/src/host/linux-sgx/pal_misc.c#L503)):*
> ```C
> 
>     /* invalid CPUID leaf functions (no existing or future CPU will return any meaningful
>      * information in these leaves) occupy 0x40000100 - 0x4FFFFFFFH -- they are treated the same as
> ```

nit



_Suggestion:_
```C
   * information in these leaves) occupy 0x40000100 - 0x4FFFFFFF -- they are treated the same as
```


<!-- Sent from Reviewable.io -->

2023-07-25 06:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 1 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NFLThV16UCccKRdBFDm:-NaAjfC8ARDRZd5d8M5D:b-2nptkl) (no related file):*
> Modifying CPUID leaves is something that is done all the time by hypervisors (see: emulated / hidden features in feature sets, CPU name strings, etc).

Yes, you are right. I didn't realize that at the moment when I wrote that message ("Well, iiuc, it is a bad smell to modify CPUID leaves...").

I agree with the two reasons you provided.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8IJrwAPP98HmLmshO:-NaAjGOx6TnNXWJ47o6c:b-d1i0u0) (no related file):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

Overall, my impression is that this PR is making the best of a bad situation. The real problem here is that Linux kernel (which definitely has the information we need, and is in much better position to obtain it) has no good API to expose TSC information.
</blockquote></details>

Thanks, and I agree with your statement.

___
___
*[`common/include/arch/x86_64/cpu.h` line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8BK4qCbfYiRcOvg9v:-NaAkFYR4E-yAMtvPMKf:b-hz0rnv) ([raw file](https://github.com/gramineproject/gramine/blob/a1f88f0276a1b2ce5f255007e10536e18791d9df/common/include/arch/x86_64/cpu.h#L48)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

Please rename this to something with `VMWARE` in name, since it's not a generic leaf.
</blockquote></details>

Done.

I also changed the comments from `Timing Info` to a more specific `VMWare-style Timing Info`. I wanted to make it explicit that this time-info leaf was originated by VMWare but is currently used by other hypervisors, thus the `-style` addition. (If it would be simple `VMWare Timing Info`, this could confuse future readers as if this leaf would read as applicable only to VMWare, which is not the case.)

If you don't like the term `VMWare-style Timing Info`, please suggest an alternative.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 503 at r4](https://reviewable.io/reviews/gramineproject/gramine/1012#-Na8Rt_e16RMqaiwcLzh:-NaAktxd2F6s4TfwVooa:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a1f88f0276a1b2ce5f255007e10536e18791d9df/pal/src/host/linux-sgx/pal_misc.c#L503)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-07-25 13:10 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-Sanitizers please (pal.regression.test_pal.TC_20_SingleProcess.test_400_pipe failed on UBSan, seems completely irrelevant to this PR, and I have never seen that error)

2023-07-31 00:51 UTC, mkow requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadQ5bZ7QwgDZW2bBbp:-NadQ5bZ7QwgDZW2bBbq:bri3b0g) (no related file):*
Blocking until @mwkmwkmwk posts her notes here (she was researching whether there's a more portable way to get TSC freq on Linux).

___
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadIrINAbI6EQhp1557:-NadIrINAbI6EQhp1558:b-wuvrq0) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L40)):*
> ```C
>     uint32_t words[CPUID_WORD_NUM];
>     _PalCpuIdRetrieve(INVARIANT_TSC_LEAF, 0, words);
>     return words[CPUID_WORD_EDX] & 1 << 8;
> ```

I know it's well defined, but IMO precedence order between binary operators in C isn't very intuitive and I always have to check it.



_Suggestion:_
```C
return words[CPUID_WORD_EDX] & (1 << 8);
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadLvXn7GyBQHPd-kwX:-NadLvXn7GyBQHPd-kwY:b-e19eby) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L54)):*
> ```C
> 
>     if (words[CPUID_WORD_ECX] > 0) {
>         /* calculate TSC frequency as core crystal clock frequency (EAX) * EBX / EAX; cast to 64-bit
> ```

I'm super confused here. First, I can't parse this sentence, is this `core_crystal_clock_frequency_which_is_in_EAX * EBX / EAX` or maybe `core_crystal_clock_frequency == EAX * EBX / EAX`, or something else?
Also, the code doesn't match this description, which doesn't help either :)



_Code quote:_
```C
calculate TSC frequency as core crystal clock frequency (EAX) * EBX / EAX
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadMYFeBaARm313-VKI:-NadMYFeBaARm313-VKJ:b-m1i9uk) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L57)):*
> ```C
>          * first to prevent integer overflow */
>         uint64_t ecx_hz = words[CPUID_WORD_ECX];
>         return ecx_hz * words[CPUID_WORD_EBX] / words[CPUID_WORD_EAX];
> ```

Wouldn't the cast be more obvious if you wrote:
```C
return (uint64_t)words[CPUID_WORD_ECX] * words[CPUID_WORD_EBX] / words[CPUID_WORD_EAX];
```
?
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 69 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadN-Zs6TxDROUfLvNM:-NadN-Zs6TxDROUfLvNN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L69)):*
> ```C
>     }
> 
>     /* processor base frequency is in MHz but we need to return TSC frequency in Hz; cast to 64-bit
> ```

ditto



_Code quote:_
```C
cast to 64-bit
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-NadOJzhDxzJZbSlCwPb:bvspcap) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
> ```C
>     hypervisor_id[1] = words[CPUID_WORD_ECX];
>     hypervisor_id[2] = words[CPUID_WORD_EDX];
>     if (memcmp(hypervisor_id, "KVMKVMKVM\0\0\0", 12) != 0 &&
> ```

Please don't assume how integers are represented in memory unless really needed.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 119 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOhH84YMlg2VfBVez:-NadOhH84YMlg2VfBVf-:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L119)):*
> ```C
> 
>     /* TSC frequency is in kHz but we need to return TSC frequency in Hz; cast to 64-bit first to
>      * prevent integer overflow */
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 141 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadPXL1-T0b64agSAF3:-NadPXL1-T0b64agSAF4:bnms9ze) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L141)):*
> ```C
>     /* can't use log_warning because at this point we didn't parse the manifest yet */
>     log_error("Could not set up Invariant TSC (CPU is too old or you run on a VM that does not "
>               "expose corresponding CPUID leaves). This degrades performance.");
> ```

Can't we move the manifest parsing to before TSC init?


<!-- Sent from Reviewable.io -->

2023-07-31 09:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 2 of 4 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadIrINAbI6EQhp1557:-NaetCRN5Pi0-R9lZcx3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know it's well defined, but IMO precedence order between binary operators in C isn't very intuitive and I always have to check it.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadLvXn7GyBQHPd-kwX:-NaeuLS45oMNd-3XAHIE:b8e9pzn) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm super confused here. First, I can't parse this sentence, is this `core_crystal_clock_frequency_which_is_in_EAX * EBX / EAX` or maybe `core_crystal_clock_frequency == EAX * EBX / EAX`, or something else?
Also, the code doesn't match this description, which doesn't help either :)
</blockquote></details>

Oops, this was a typo (`(EAX)` should have been `(ECX)`).

Anyway, I rewrote this comment to make it more explicit. Also, the comment directly corresponds to the description of the CPUID instruction, see Intel SDM, Table 3-8, leaf 15H, or just here: https://www.felixcloutier.com/x86/cpuid
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadMYFeBaARm313-VKI:-NaeumSd9GHxha1AUe_C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't the cast be more obvious if you wrote:
```C
return (uint64_t)words[CPUID_WORD_ECX] * words[CPUID_WORD_EBX] / words[CPUID_WORD_EAX];
```
?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 69 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadN-Zs6TxDROUfLvNM:-Naeuu4d3glPRg70cWfD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-NaesWr23jOsAHJSntQK:b-op4lf) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't assume how integers are represented in memory unless really needed.
</blockquote></details>

I don't understand your comment. We are on the SGX PAL, so we know this is x86 and thus little endian.

Also, this is how the "CPUID leaves to a char string" translation is specified and implemented, see examples:
- https://github.com/qemu/qemu/blob/ccb86f079a9e4d94918086a9df18c1844347aff8/target/i386/kvm/kvm.c#L1904-L1910
- https://kb.vmware.com/s/article/1009458

What I could do is to add `#ifdef __x86_64__` around here, to maybe make it more visible to readers.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 119 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOhH84YMlg2VfBVez:-Naev0NV4P-_GTiGiq2-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L119)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 141 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadPXL1-T0b64agSAF3:-NaewpEoB5r2gTgps1x2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can't we move the manifest parsing to before TSC init?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-31 22:56 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-01 01:08 UTC, kailun-qin requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 58 at r6](https://reviewable.io/reviews/gramineproject/gramine/1012#-Naiabt_0kKl4Gfkclc4:-Naiabt_0kKl4Gfkclc5:b-6iitl5) ([raw file](https://github.com/gramineproject/gramine/blob/8ef291135e1916a5d8325c1b8a05fe4287ba5906/pal/src/host/linux-sgx/pal_misc.c#L58)):*
> ```C
>          *   - EAX is denominator of the TSC/"core crystal clock" ratio,
>          *   - EBX is numerator of the TSC/"core crystal clock" ratio,
>          *   - ECX is core crystal clock frequency in Hz.
> ```

If we really want to add the details of reg info, should we move them a bit earlier (maybe right before `_PalCpuIdRetrieve(TSC_FREQ_LEAF, ...)`) since`CPUID_WORD_EAX` and `CPUID_WORD_EBX` were already mentioned and checked above?



_Code quote:_
```C
         *   - EAX is denominator of the TSC/"core crystal clock" ratio,
         *   - EBX is numerator of the TSC/"core crystal clock" ratio,
         *   - ECX is core crystal clock frequency in Hz.
```


<!-- Sent from Reviewable.io -->

2023-08-01 06:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 3 of 4 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 58 at r6](https://reviewable.io/reviews/gramineproject/gramine/1012#-Naiabt_0kKl4Gfkclc4:-NajqZC63jOislzv6xou:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ef291135e1916a5d8325c1b8a05fe4287ba5906/pal/src/host/linux-sgx/pal_misc.c#L58)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

If we really want to add the details of reg info, should we move them a bit earlier (maybe right before `_PalCpuIdRetrieve(TSC_FREQ_LEAF, ...)`) since`CPUID_WORD_EAX` and `CPUID_WORD_EBX` were already mentioned and checked above?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 07:13 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 14 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-02 02:08 UTC, mkow requested changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 801 at r7](https://reviewable.io/reviews/gramineproject/gramine/1012#-NanzGlEBwV_K24D_ltd:-NanzGlEBwV_K24D_lte:b2l8z6d) ([raw file](https://github.com/gramineproject/gramine/blob/785e09387a199845030ae3cba45da0a22e4d2c0c/pal/src/host/linux-sgx/pal_main.c#L801)):*
> ```C
>     }
> 
>     /* FIXME: after rebase to latest master, move this to post_callback() */
> ```

Blocking, just to not forget.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-NanylCm2BVbUvmfnhPJ:bfgzroh) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand your comment. We are on the SGX PAL, so we know this is x86 and thus little endian.

Also, this is how the "CPUID leaves to a char string" translation is specified and implemented, see examples:
- https://github.com/qemu/qemu/blob/ccb86f079a9e4d94918086a9df18c1844347aff8/target/i386/kvm/kvm.c#L1904-L1910
- https://kb.vmware.com/s/article/1009458

What I could do is to add `#ifdef __x86_64__` around here, to maybe make it more visible to readers.
</blockquote></details>

I mean you assume little-endian here. I know we're always on x86 in this PAL, but such assumption is unnecessary, you can just compare each word to the desired value (you can even use the `'asdf'` notation in C to have nice ASCII letters).
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 141 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadPXL1-T0b64agSAF3:-NanzXJi8HJ59OG7P1TK:blxarbu) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant is: Why can't we just call `init_tsc()` _after_ the manifest is parsed? The new solution is OK-ish, but the warning is quite far away from the code which actually causes it (this wouldn't be the case if `init_tsc()` was called after logging has been initialized).


<!-- Sent from Reviewable.io -->

2023-08-02 08:24 UTC, mwkmwkmwk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadQ5bZ7QwgDZW2bBbp:-Nap1Hcs-VLaMvG4Y5tw:b5e2ka) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking until @mwkmwkmwk posts her notes here (she was researching whether there's a more portable way to get TSC freq on Linux).
</blockquote></details>

Notes about TSC on Linux:

Let's start with TSC frequency. Linux of course determines that at startup, and it's in a much better position to do it than gramine (having more access to the underlying hardware).  Specifically, it checks the following:

- [native, intel only] CPUID leaf 0x15
- [native] calibrate against a timer with a known frequency (HPET, ACPI, or PIT)
- [xen] grab frequency from hypervisor shared_info structure
- [kvm paravirt] grab frequency from pvclock_vcpu_time_info structure
- [jailhouse] grab frequency from jailhouse_setup_data structure
- [vmware] run the `GETHZ` hypercall
- [hyperv] read the frequency from a HV-specific MSR
- [acrn] read the frequency from CPUID (which seems to match the vmware CPUID, but is present in the kernel with acrn-specific name)

In addition to the frequency, it also tracks some other information about the TSC:

- `X86_FEATURE_CONSTANT_TSC`: whether the frequency is invariant (ie. if the TSC clock is ticking, it always ticks with the same frequency)
- `X86_FEATURE_NONSTOP_TSC`: whether the TSC is non-stop (ie. will not pause counting in per-cpu low power states)
- whether the TSC is synchronized across all CPUs in the system

The TSC is considered usable for timekeeping if the frequency is known, invariant, and synchronized across CPUs. Non-stop is not necessary.

Further, when TSC is suitable for timekeeping, it will be used to implement the `gettimeofday` syscall via a fastpath in vdso (without involving an *actual* syscall). This works as follows:

- the infrastructure in `kernel/time/timekeeping.c` is used to track of eg. NTP corrections and compute *refined* TSC frequency, which for obvious reasons is more accurate than the above
- the linear transformation parameters (scaling factor and offset) needed to compute wall time from TSC are stored in the `vvar` data page, which is mapped to the userspace; they are continuously updated by the kernel (in the event of eg. low power transitions or further NTP corrections)
- the `vdso` code for `gettimeofday` reads TSC, grabs the conversion parameters from `vvar`, and computes wall time without switching to the kernel
- the above is the usual case, but sometimes alternate fast path implementations are used in `gettimeofday`:
  - on xen, the PVTI structure from hypervisor (with different layout but pretty similar functions) is mapped to userspace and used instead of `vvar`
  - on hyperv, likewise the `ms_hyperv_tsc_page` structure is used instead
  - when a given process is inside a time namespace, another per-namespace page (`timens` page) is included in `vvar`, and the offset in it is used to further postprocess non-namespaced time obtained by one of the above means

So, in all circumstances where the kernel considers it possible, all necessary information to compute wall time is already available in our process, in the form of `vvar` or equivalent. However, it is not easily possible to use it!

- the `vvar` layout depends on kernel version, and is not considered to be public ABI
- the vdso code knows the `vvar` layout and can make use of it, but for obvious security reasons we cannot just call it from within the enclave
- even if we want to forgo the refined frequency and time offset information available to the timekeeping code, the raw TSC frequency (stored in the kernel in the `tsc_khz` variable) is not directly exposed to the userspace in any way

Having looked through kernel code, I've found several ways of accessing the `tsc_khz` frequency, but all of them are... lacking in various ways:

- open `/dev/kvm`, create a dummy virtual machine, run `KVM_GET_TSC_KHZ` ioctl on it (it'll return the default TSC frequency for VMs, which is equal to host TSC) — doesn't work inside VMs unless the hypervisor implements and exposes nested virtualization capability
- use `perf_event_open` to set up a dummy performance monitoring fd, mmap its control page, recover TSC frequency from `time_mult` and `time_shift` fields there — unfortunately, kernel only exposes these fields when sched clock in use is TSC, which is not the case for VMs with paravirtualized clock support
- use bpftrace (or some other means) to read the kernel's `tsc_khz` variable directly — requires root

In other words, if we're running in a VM, there's very likely no kernel interface to give us the information we want, even though it is present in the kernel.

I see three ways we could possibly improve on the state of the art as implemented in this commit:

- (requires simple kernel modification) introduce a kernel interface to expose the `tsc_khz` variable to userspace
- (requires complex kernel modification) introduce kernel interfaces to expose the `vvar` layout information to userspace in machine-readable way, so that we can essentially replicate `vdso_gettimeofday` in our own code; this will be a messy endeavor, since by necessity this will require exposing hyperv and KVM paravirtualized time structures and timens details, and getting kernel developers to agree to that may not be easy
- (horrible hack, high effort, brittle) extract `vvar` layout information from `vdso` ourselves, essentially by matching eg. sha1sum of vdso code against a list of known vdsos

Given the difficulties inherent in the above, I consider this commit to be the best available short-term (and even medium-term) solution.  It would perhaps be a good idea to copy the above notes (with minor edits) to a comment in our TSC code, to preserve this information.

___


<!-- Sent from Reviewable.io -->

2023-08-02 08:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 141 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadPXL1-T0b64agSAF3:-NapPsCqELZF4YBi9kpT:b-t7q2fw) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I meant is: Why can't we just call `init_tsc()` _after_ the manifest is parsed? The new solution is OK-ish, but the warning is quite far away from the code which actually causes it (this wouldn't be the case if `init_tsc()` was called after logging has been initialized).
</blockquote></details>

1. We want to put a `warning` message, not an `error` message.
2. This requires to parse not only the manifest, but also the `log_level` keyword.
3. The parsing of `log_level` keyword is done in general PAL code, not in Linux-SGX code: 
   - https://github.com/gramineproject/gramine/blob/7485c90b1cb5b54695a7dcab1cdcb6361d179777/pal/src/pal_main.c#L261
   - https://github.com/gramineproject/gramine/blob/7485c90b1cb5b54695a7dcab1cdcb6361d179777/pal/src/pal_main.c#L387

Also, we don't want to put this message on the terminal if the `log_file` keyword was specified in the manifest. Similar to `log_level`, this keyword is parsed only in the general PAL code (which runs **after** all Linux-SGX code is done, including `init_tsc()`).

So I don't think we have a choice...


<!-- Sent from Reviewable.io -->

2023-08-02 11:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 3 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-Naq3HeQ7Fzjv_5Oqh4M:b-6cdi6n) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean you assume little-endian here. I know we're always on x86 in this PAL, but such assumption is unnecessary, you can just compare each word to the desired value (you can even use the `'asdf'` notation in C to have nice ASCII letters).
</blockquote></details>

Done. I don't use `'asdf'` notation because it spits out a warning, is generally considered a bad practice, and also requires an inverse order of letters (see https://stackoverflow.com/questions/7755202/multi-character-constant-warnings).

I wrote a small test to compare the values, I'll post it here just for reference:
```
#include <stdio.h>
#include <stdint.h>

int main(void) {
    /* taken from
     * https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1408 */
    uint32_t ebx=0x4b4d564b, ecx=0x564b4d56, edx=0x0000004d;

    /* taken from
     * https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1375 */
    char s[12] = "KVMKVMKVM";

    /* trying multi-char constants */
    uint32_t bx='KVMK', cx='VMKV', dx='M\0\0\0';

    printf("int  hex: %x %x %x\n", ebx, ecx, edx);
    printf("str  hex: %x %x %x\n", *((uint32_t*)&s[0]), *((uint32_t*)&s[4]), *((uint32_t*)&s[8]));
    printf("char hex: %x %x %x (WRONG ENDIANNESS!)\n", bx, cx, dx);
    return 0;
}
```

When building this program, GCC outputs:
```
test.c: In function ‘main’:
test.c:14:17: warning: multi-character character constant [-Wmultichar]
   14 |     uint32_t bx='KVMK', cx='VMKV', dx='M\0\0\0';
...
```

Finally, the results of this test look like this:
```
int  hex: 4b4d564b 564b4d56 4d
str  hex: 4b4d564b 564b4d56 4d
char hex: 4b564d4b 564d4b56 4d000000 (WRONG ENDIANNESS!)
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 103 at r8](https://reviewable.io/reviews/gramineproject/gramine/1012#-Naq4VOs5N7Q9ZtiH48p:-Naq4VOs5N7Q9ZtiH48q:b-97bx4a) ([raw file](https://github.com/gramineproject/gramine/blob/8855520fd47f8f4d3b4800759f18f3f596cc4bc4/pal/src/host/linux-sgx/pal_misc.c#L103)):*
> ```C
>     bool is_kvm    = words[CPUID_WORD_EBX] == 0x4b4d564b
>                          && words[CPUID_WORD_ECX] == 0x564b4d56
>                          && words[CPUID_WORD_EDX] == 0x0000004d;
> ```

You can easily google these magic numbers. Here is one example: https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1408
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 106 at r8](https://reviewable.io/reviews/gramineproject/gramine/1012#-Naq4gEI7NiT_t8FtrEY:-Naq4gEI7NiT_t8FtrEZ:b3ew4pf) ([raw file](https://github.com/gramineproject/gramine/blob/8855520fd47f8f4d3b4800759f18f3f596cc4bc4/pal/src/host/linux-sgx/pal_misc.c#L106)):*
> ```C
>     bool is_vmware = words[CPUID_WORD_EBX] == 0x61774d56
>                          && words[CPUID_WORD_ECX] == 0x4d566572
>                          && words[CPUID_WORD_EDX] == 0x65726177;
> ```

You can easily google these magic numbers. Here is one example: https://www.unknowncheats.me/forum/general-programming-and-reversing/514916-vmware-__cpuid-change.html


<!-- Sent from Reviewable.io -->

2023-08-02 14:02 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-NaqY17G84Oh-uBXBCQV:b5rafxr) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I don't use `'asdf'` notation because it spits out a warning, is generally considered a bad practice, and also requires an inverse order of letters (see https://stackoverflow.com/questions/7755202/multi-character-constant-warnings).

I wrote a small test to compare the values, I'll post it here just for reference:
```
#include <stdio.h>
#include <stdint.h>

int main(void) {
    /* taken from
     * https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1408 */
    uint32_t ebx=0x4b4d564b, ecx=0x564b4d56, edx=0x0000004d;

    /* taken from
     * https://github.com/freebsd/freebsd-src/blob/9df6eeabb379b0816d58b05a4de24fc0478e1dba/sys/x86/x86/identcpu.c#L1375 */
    char s[12] = "KVMKVMKVM";

    /* trying multi-char constants */
    uint32_t bx='KVMK', cx='VMKV', dx='M\0\0\0';

    printf("int  hex: %x %x %x\n", ebx, ecx, edx);
    printf("str  hex: %x %x %x\n", *((uint32_t*)&s[0]), *((uint32_t*)&s[4]), *((uint32_t*)&s[8]));
    printf("char hex: %x %x %x (WRONG ENDIANNESS!)\n", bx, cx, dx);
    return 0;
}
```

When building this program, GCC outputs:
```
test.c: In function ‘main’:
test.c:14:17: warning: multi-character character constant [-Wmultichar]
   14 |     uint32_t bx='KVMK', cx='VMKV', dx='M\0\0\0';
...
```

Finally, the results of this test look like this:
```
int  hex: 4b4d564b 564b4d56 4d
str  hex: 4b4d564b 564b4d56 4d
char hex: 4b564d4b 564d4b56 4d000000 (WRONG ENDIANNESS!)
```
</blockquote></details>

agreed, let's not use the `'asdf'` notation, it's too horrible to rely on


<!-- Sent from Reviewable.io -->

2023-08-02 17:51 UTC, mkow reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadQ5bZ7QwgDZW2bBbp:-NarLomvBRvtFc1fJPQu:b4ongw4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome summary, thanks @mwkmwkmwk!

Some notes:
- I confirm the notes about MS Hyper-V. I researched this too.
- Regarding `vvar` page: I researched it in this PR https://github.com/gramineproject/gramine/pull/1154, and came to the same conclusions.

> It would perhaps be a good idea to copy the above notes (with minor edits) to a comment in our TSC code, to preserve this information.

I'm not sure we want this information in any of the our header/sources files... Sounds like way too much unrelated info. I would propose to copy this summary in GitHub Discussions or as a GitHub metaissue. What does @mkow think? (And if we want to put it in headers/sources, then in which file exactly and do we keep **all** information including e.g. Acrn specific notes?)
</blockquote></details>

No strong opinion here, I think I'd prefer to have it in the source, but it's also ok to just leave it here.
@mwkmwkmwk: Thanks for the great write-up! This is really terrible :|

___
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 101 at r5](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadOJzhDxzJZbSlCwPa:-NarMVVZ7Ag7-fPMXneo:b2vm1ht) ([raw file](https://github.com/gramineproject/gramine/blob/4e0c94b80ef891c46392e240cea43ce17343181b/pal/src/host/linux-sgx/pal_misc.c#L101)):*
> The value of an integer character constant containing more than one character (e.g., 'ab'), \[...\] is implementation-defined.

Oh, I didn't know that. Thanks C, so useful.


<!-- Sent from Reviewable.io -->

2023-08-02 18:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NadQ5bZ7QwgDZW2bBbp:-NarPzM9EfCtUBMuPebY:bfdm8b1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No strong opinion here, I think I'd prefer to have it in the source, but it's also ok to just leave it here.
@mwkmwkmwk: Thanks for the great write-up! This is really terrible :|
</blockquote></details>

I'll just leave it as a comment right now then. I don't want to add so much text in the sources.

___


<!-- Sent from Reviewable.io -->

2023-08-03 06:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 2 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/1012#-NP0A_1c6Qczf99DEIxn):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good point. Context for other reviewers:

> Cloud Hypervisor is an open source Virtual Machine Monitor (VMM) that runs on top of the KVM hypervisor and the Microsoft Hypervisor (MSHV).

@ https://github.com/cloud-hypervisor/cloud-hypervisor#1-what-is-cloud-hypervisor

This leaf `0x40000010` is exposed only when Cloud Hypervisor runs on KVM. I'll change this during final rebase.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_main.c` line 801 at r7](https://reviewable.io/reviews/gramineproject/gramine/1012#-NanzGlEBwV_K24D_ltd:-Nau2r2i3x1nGr6U2Zxv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/785e09387a199845030ae3cba45da0a22e4d2c0c/pal/src/host/linux-sgx/pal_main.c#L801)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Blocking, just to not forget.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-03 06:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: 2 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @kailun-qin, @mkow, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-Nau9susDHjGzjZDYLM8:-Nau9susDHjGzjZDYLM9:b4lcavc) (no related file):*
I tested the rebased version on a MS Azure VM, which doesn't have any leaves (nor bare-metal 0x15, nor hypervisor-specific 0x4000000), and it correctly shows us:
```
(pal_main.c:526:print_warning_on_invariant_tsc) warning: Could not set up Invariant TSC (CPU is too old or you run on a VM tha
t does not expose corresponding CPUID leaves). This degrades performance.
```

___


<!-- Sent from Reviewable.io -->

2023-08-03 10:15 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-03 10:15 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-03 13:54 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: all files reviewed, 6 unresolved discussions (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2023-08-03 19:04 UTC, dimakuv reviewed
> Dismissed @boryspoplawski from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1012#-NawmBB_7W2DEzXufx_T:-NawmBB_7W2DEzXufx_U:b-ks56sh) (no related file):*
@boryspoplawski asked to be dismissed from all discussions in this PR, which I did now.

___


<!-- Sent from Reviewable.io -->

2023-08-03 22:13 UTC, kailun-qin approved these changes
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-03 22:13 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1012)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-21 03:05 UTC, merged