[LibOS,PAL] Make logs more verbose
gramineproject/gramine pull request #1023
Opened 2022-10-31 20:10 UTC by oshogbo

## Description of the changes 

Let Gramine print messages instead of error codes.
This is more user-friendly.

## Future improvements

My propositions:
- Change values of PAL error codes (let's say let them start at 0x10000000) and introduce a single function to get an error message. Everything below the threshold is assumed to be a Unix error code, and everything above a PAL error. Ofc we should respect the negative values as well.
- Change error/debug/etc. to include `__FILE__`, `__LINE__`, and `__func__`, if the verbosity level is different than errors. Currently, many functions add this manually:
```
pal/src/host/linux/pal_sockets.c:            log_error("%s:%d closing socket fd failed: %s", __func__, __LINE__, unix_strerror(ret));
pal/src/host/linux/pal_sockets.c:            log_error("%s:%d closing socket fd failed: %s", __func__, __LINE__, unix_strerror(ret));
pal/src/host/linux-sgx/pal_sockets.c:            log_error("%s:%d closing socket fd failed: %d", __func__, __LINE__, ret);
pal/src/host/linux-sgx/pal_sockets.c:            log_error("%s:%d closing socket fd failed: %d", __func__, __LINE__, ret);
```

2022-11-03 12:06 UTC, oshogbo commented
Jenkins, retest Jenkins-SGX-Sanitizers please

2022-11-27 18:31 UTC, oshogbo commented
Jenkins, retest Jenkins-20.04 please (`libos.test.ltp.test_ltp.test_ltp[fdatasync01]` timed out, known and unrelated)

2022-12-08 00:28 UTC, mkow requested changes
> Reviewed 36 of 49 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuBo16_3za_47A1Rs:-NIiuBo16_3za_47A1Rt:b-dp6r2v) (no related file):*
> Change values of PAL error codes (let's say let them start at 0x10000000) and introduce a single function to get an error message. Everything below the threshold is assumed to be a Unix error code, and everything above a PAL error. Ofc we should respect the negative values as well.

Hmm, I don't like this, it will make accidentally mixing PAL and Linux error codes easier. They will work when printed, but not e.g. when checked with `if (ret == EINVAL)`. I'd prefer to somehow get these enums working and have compile-time checking.

___
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiubtU4_QmPyhOdz90):*
This could fit into the one-liner, also making it more precise (but still short)
___
*[`common/src/unix_error.c` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIizqAXDQ_PMJQ2WuZ7:-NIizqAXDQ_PMJQ2WuZ8:b-hl19ss) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L442)):*
> ```C
> #endif
> #ifdef EIEIO
>     [EIEIO] = "Computer bought the farm",
> ```

I didn't know this, lol.
___
*[`common/src/unix_error.c` line 459 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIixu31DtD6h9Eh37vk:-NIixu31DtD6h9Eh37vl:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L459)):*
> ```C
> 
> const char* unix_strerror(int err) {
>     static char buf[512];
> ```

ditto
___
*[`common/src/unix_error.c` line 462 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiyENg6Pn8ipSMMJ4z:-NIiyENg6Pn8ipSMMJ5-:b-wx4scz) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L462)):*
> ```C
>     unsigned err_idx = err >= 0 ? err : -err;
>     if (err_idx >= ARRAY_SIZE(g_unix_error_list) || !g_unix_error_list[err_idx]) {
>         snprintf(buf, sizeof(buf), "Unknown UNIX error (errcode = %d)", err);
> ```

I'd use this name for UNIX case, it's more popular there.



_Suggestion:_
```C
errno
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIj6Vln4eZj9uZPR17P:-NIj6Vln4eZj9uZPR17Q:buyu5vp) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/pal/src/host/linux-sgx/host_profile.c#L153)):*
> ```C
>         if (close_ret < 0) {
>             log_error("sgx_profile_init: pd_close failed: %s",
>                       unix_strerror(close_ret));
> ```

no need to wrap this one
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NIiuviOBFSifYaKz0B3:b-vk9w77) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
> ```C
> 
> const char* pal_strerror(int err) {
>     static char buf[512];
> ```

This isn't reentrant. The only feasible solution to this without blowing all the callsites I see is making this buffer thread-local, but not sure all users of this .c code support TLS.


<!-- Sent from Reviewable.io -->

2022-12-08 08:20 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkn3YO9LjlyCcBS-0e:-NIkn3YP5bXcjZNfk7pW:b-47ce8n) (no related file):*
I admire the effor, but what's the point? It's not like after reading a log you know what failed if you have a "short string" instead of error number...
Also for me this PR would make debugging worse: when I see an error like `error: something something happened: -14`, it gives me information that some function failed and returned `-14`. Most of the time I need to inspect that function (and recursively all it calls) to see in which cases it can return `-14`, which involves translating 14 to EFAULT and looking what could have possibly returned that. With this PR I would have to opened this magic table and search what the printed string error translates to.
Not blocking since I won't be doing much debugging on this project soon :)

___
___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NIkmZl-0TNu0v0v3H8c:b-r3jbw3) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
> ```C
>     [EHWPOISON] = "Memory page has hardware error",
> #endif
> #ifdef EBADRPC
> ```

Where did you get these values from (from this one onward)? There are no such error codes in Linux
___
*[`common/src/unix_error.c` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIizqAXDQ_PMJQ2WuZ7:-NIkmfViBLIJr4lAD8tH:b-mnrkz) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L442)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I didn't know this, lol.
</blockquote></details>

Afaik there's no such thing..
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NIknKxF4nSSNnoskjVm:b2ie3rs) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This isn't reentrant. The only feasible solution to this without blowing all the callsites I see is making this buffer thread-local, but not sure all users of this .c code support TLS.
</blockquote></details>

It's not about reentrancy. You cannot even call this function twice and use first return value.


<!-- Sent from Reviewable.io -->

2022-12-08 13:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkn3YO9LjlyCcBS-0e:-NIlsEwHE7gVWaxakHIP:bg481as) (no related file):*
> what's the point?

The point is that users often see errors like `some_internal_func() failed with ret = -12`, which is super confusing. If they see that it's actually an out-of-memory error, they will get a hint that they could e.g. try making the enclave bigger.

> Also for me this PR would make debugging worse [...]

But this is trivial to fix, we can just print both the number and the explanation string?

___
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NIlt9hC9aH8k1PD_Avk:bb3woyp) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not about reentrancy. You cannot even call this function twice and use first return value.
</blockquote></details>

This is error printing, if it gets interrupted in the middle by an exception, then the exception handler may use it for logging, resulting in another entry? But this part we cannot easily fix and should be rare, but we can at least make it thread-safe.


<!-- Sent from Reviewable.io -->

2022-12-09 11:55 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkn3YO9LjlyCcBS-0e:-NIqfeP_4lwbI8aXWlLP:b-qh3tt3) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> what's the point?

The point is that users often see errors like `some_internal_func() failed with ret = -12`, which is super confusing. If they see that it's actually an out-of-memory error, they will get a hint that they could e.g. try making the enclave bigger.

> Also for me this PR would make debugging worse [...]

But this is trivial to fix, we can just print both the number and the explanation string?
</blockquote></details>

So do we want to add number as well?
Or maybe instead of numbers we could print actually name representing the error. We don't really use numbers in code. So to avoid this translation (between messages->code or code->name) we could just print something like:
```
Operation not permitted (EPERM)
```
Or:
```
Operation not permitted (errno: EPERM)
```

___
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiubtU4_QmPyhOdz90):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This could fit into the one-liner, also making it more precise (but still short)
</blockquote></details>

Done.
___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NIqdRh_-diCgtU93MWp:bf0741l) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Where did you get these values from (from this one onward)? There are no such error codes in Linux
</blockquote></details>

From glibc:
https://elixir.bootlin.com/glibc/latest/source/sysdeps/gnu/errlist.h#L683



_Code quote:_
```C
EBADRPC
```
___
*[`common/src/unix_error.c` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIizqAXDQ_PMJQ2WuZ7:-NIqdZZa0B6-7QWYK2TI:bq49dtp) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L442)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Afaik there's no such thing..
</blockquote></details>

I generated the whole list from glibc: https://elixir.bootlin.com/glibc/latest/source/sysdeps/gnu/errlist.h



_Code quote:_
```C
EIEIO
```
___
*[`common/src/unix_error.c` line 462 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiyENg6Pn8ipSMMJ4z:-NIqgFuQEjRzGzzdk5-a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L462)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd use this name for UNIX case, it's more popular there.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 153 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIj6Vln4eZj9uZPR17P:-NIqhCFuELtJ4KVbrJiX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/pal/src/host/linux-sgx/host_profile.c#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need to wrap this one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 16:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: 47 of 49 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NIrfCd7EfmvkWNZBldU:bwg6u36) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

From glibc:
https://elixir.bootlin.com/glibc/latest/source/sysdeps/gnu/errlist.h#L683
</blockquote></details>

1. We are no emulating glibc.
2. These are literally used only in GNU hurd...
___
*[`common/src/unix_error.c` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIizqAXDQ_PMJQ2WuZ7:-NIrfKsE07LP46M3NVU8:b-u0kutb) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L442)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I generated the whole list from glibc: https://elixir.bootlin.com/glibc/latest/source/sysdeps/gnu/errlist.h
</blockquote></details>

Let's add HURD PAL that will be fun (gnu kind of fun)


<!-- Sent from Reviewable.io -->

2022-12-10 00:53 UTC, mkow reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkn3YO9LjlyCcBS-0e:-NItVLPtATBTO7yVQ7Ow:btnfox7) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So do we want to add number as well?
Or maybe instead of numbers we could print actually name representing the error. We don't really use numbers in code. So to avoid this translation (between messages->code or code->name) we could just print something like:
```
Operation not permitted (EPERM)
```
Or:
```
Operation not permitted (errno: EPERM)
```
</blockquote></details>

I prefer `Operation not permitted (EPERM)` format. The number doesn't seem useful, and you can easily find it with `errno --list | grep XYZ` if needed.

___
___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NItVrOVEw_O_ZXbSuGL:b-bw45ak) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. We are no emulating glibc.
2. These are literally used only in GNU hurd...
</blockquote></details>

Hard to say what list should be in `common/`, as it's not just for the LibOS. I guess some *BSDs may use these?
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NItVgKUDifzFUzWRLUQ:b6v8bp) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We don't use logging on async exceptions.
</blockquote></details>

Then TLS should do the work, assuming it works internally in Gramine.


<!-- Sent from Reviewable.io -->

2022-12-10 01:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NItel7l50uqD1IvLrM8:b-cpnz79) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
It definitely should not include GNU nonsense.

> I guess some *BSDs may use these?

No expert here, but I would bet a lot for: no.


<!-- Sent from Reviewable.io -->

2023-01-03 14:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuBo16_3za_47A1Rs:-NKs1waL3RoHPvoUzcBy:b-lzsc8l) (no related file):*
I don't like this as well.

> I'd prefer to somehow get these enums working and have compile-time checking.

This would be great. But even without this I'm fine.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkn3YO9LjlyCcBS-0e:-NKs2JxrB28I1DLstHMe:bh200kn) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer `Operation not permitted (EPERM)` format. The number doesn't seem useful, and you can easily find it with `errno --list | grep XYZ` if needed.
</blockquote></details>

I find this PR useful (more useful than #1040). Similarly to Michal, I think this PR is not really relevant to Gramine devs but to end users of Gramine -- sometimes knowing that `-12` is ENOMEM saves casual users from hours of experimenting, and us from answering trivial GitHub issues.

I also prefer `Operation not permitted (EPERM)` format.

___


<!-- Sent from Reviewable.io -->

2023-01-04 13:27 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: 46 of 49 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NKwxdD87PVQYRLQppCc:b-b0rwly) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It definitely should not include GNU nonsense.

> I guess some *BSDs may use these?

No expert here, but I would bet a lot for: no.
</blockquote></details>

I think this isn't BSD specific more GNU specific.
However as this is in common part I think it make sense to use extended version from glibc.
If you really object I can change that.
___
*[`common/src/unix_error.c` line 459 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIixu31DtD6h9Eh37vk:-NKwxpZ-5ZPdbjGmLTuW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NKwxSig-RY7IhanYrz1:b7u72zl) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then TLS should do the work, assuming it works internally in Gramine.
</blockquote></details>

Unfortunately TLS is not supported in Gramine.
I propose to just log an error and abort, as this situation is very unlikly.


<!-- Sent from Reviewable.io -->

2023-01-04 14:51 UTC, mkow requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`common/src/unix_error.c` line 415 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFclBE4URKbB3LnH9:-NKxFclC27jbaz0MLC3M:b32vhw) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L415)):*
> ```C
> #endif
> #ifdef EAUTH
>     [EAUTH] = "Authentication error (#)",
> ```

:)
___
*[`common/src/unix_error.c` line 433 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFj6W7TcIP87aTprN:-NKxFj6Y1RmWci8_4Xb_:b2nh4fp) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L433)):*
> ```C
> #endif
> #if defined(ENOTSUP) && ENOTSUP != EOPNOTSUPP
>     [ENOTSUP] = "Not supported (defined)",
> ```

:))
___
*[`common/src/unix_error.c` line 461 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFtt46MPlNB8VYOSL:-NKxFtt46MPlNB8VYOSM:b-m3ge2e) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L461)):*
> ```C
>     unsigned err_idx = err >= 0 ? err : -err;
>     if (err_idx >= ARRAY_SIZE(g_unix_error_list) || !g_unix_error_list[err_idx]) {
>         log_error("Unknown PAL error (errcode = %d)", err);
> ```

copy paste error?


<!-- Sent from Reviewable.io -->

2023-01-04 15:19 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: 48 of 49 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/unix_error.c` line 415 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFclBE4URKbB3LnH9:-NKxMGZm7SdVeo-SG6y9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L415)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

:)
</blockquote></details>

Done.
___
*[`common/src/unix_error.c` line 433 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFj6W7TcIP87aTprN:-NKxMGwY8eQmxLhwkt84:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

:))
</blockquote></details>

Done.
___
*[`common/src/unix_error.c` line 461 at r4](https://reviewable.io/reviews/gramineproject/gramine/1023#-NKxFtt46MPlNB8VYOSL:-NKxMVwI6B3iDqsFxe6l:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f448f3f0daa194453ccb2863975cfe76be5278c/common/src/unix_error.c#L461)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

copy paste error?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-04 16:21 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-05 09:06 UTC, dimakuv requested changes
> Reviewed 31 of 49 files at r1, 13 of 13 files at r2, 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`common/src/unix_error.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIkmZl-0TNu0v0v3H8b:-NL05ShPBpAL3pFKEUXp:b-4z9l9h) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/unix_error.c#L405)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think this isn't BSD specific more GNU specific.
However as this is in common part I think it make sense to use extended version from glibc.
If you really object I can change that.
</blockquote></details>

I guess nobody objects. Let's leave it as is.
___
*[`common/src/unix_error.c` line 424 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL05_rX022wWuuKvsoW:-NL05_rX022wWuuKvsoX:b6wugf4) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/common/src/unix_error.c#L424)):*
> ```C
> #endif
> #ifdef EGREGIOUS
>     [EGREGIOUS] = "You really blew it this time (EGREGIOUS)",
> ```

Oh, this one is also great
___
*[`libos/src/libos_malloc.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL06dBZ3NnHZkVj5F1k:-NL06dBZ3NnHZkVj5F1l:b-lqkgwk) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/libos/src/libos_malloc.c#L47)):*
> ```C
>     ret = PalVirtualMemoryAlloc(addr, alloc_size, PAL_PROT_WRITE | PAL_PROT_READ);
>     if (ret < 0) {
>         log_error("failed to allocate memory: %s", pal_strerror(ret));
> ```

I don't like this. It's impossible to deduce that the reported error is a PAL error, from `PalVirtualMemoryAlloc()`.

Two suggestions:
1. either change message to smth like `PalVirtualMemoryAlloc failed with: %s`,
2. or in the list of PAL errors, add to each string a suffix like `Function not implemented (PAL_NOTIMPLEMENTED)`

I would prefer the first solution.

Ditto for all other places in this PR.

UPDATE: Well, after looking through the whole PR, especially the PAL code, I lean to solution 2 now. It's really hard to mention in all log messages that "Something in PAL broke".
___
*[`pal/src/host/linux/pal_main.c` line 327 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL08alXBmvO98nG9ExL:-NL08alXBmvO98nG9ExM:bwpkn05) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux/pal_main.c#L327)):*
> ```C
>         ret = read_text_file_to_cstr(manifest_path, &manifest);
>         if (ret < 0) {
>             INIT_FAIL("Reading manifest failed: %s", unix_strerror(ret));
> ```

Meh, this mix of functions returning UNIX error codes and funcs returning PAL error codes is annoying.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 793 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL08s1F65EdSt2SGAPC:-NL08s1F65EdSt2SGAPD:b-fbpjj) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/enclave_framework.c#L793)):*
> ```C
>         if (ret < 0) {
>             log_error("normalize_and_register_file(\"%s\", \"%s\") failed with error code %d (%s)",
>                       toml_trusted_uri_str, toml_trusted_sha256_str, ret, pal_strerror(ret));
> ```

What's the point in printing `ret` here additionally? Remove it.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL097pS2VU6ZliCIJtS:-NL097pS2VU6ZliCIJtT:b-pdcad2) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L156)):*
> ```C
>         }
> 
>         log_error("ECREATE failed in allocating EPC memory: %s", unix_strerror(ret));
> ```

Can we remove ECREATE from this message? It's totally confusing (ECREATE is an SGX instruction, but here we fail on normal mmap syscall). I'd rephrase to: `Allocation of EPC memory failed: %s`
___
*[`pal/src/host/linux-sgx/host_framework.c` line 168 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09JdMBGohYgyNQGly:-NL09JdMBGohYgyNQGlz:b-sp62kr) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L168)):*
> ```C
> 
>     if (ret < 0) {
>         log_error("ECREATE failed in enclave creation ioctl: %s", unix_strerror(ret));
> ```

I'd rephrase to `Enclave creation IOCTL failed: %s`
___
*[`pal/src/host/linux-sgx/host_framework.c` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09TvpAipI2i8MdYtm:-NL09TvpAipI2i8MdYtn:b-sp62kr) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L173)):*
> ```C
> 
>     if (ret) {
>         log_error("ECREATE failed: %s", unix_strerror(ret));
> ```

I'd rephrase to `Enclave creation IOCTL failed: %s`
___
*[`pal/src/host/linux-sgx/host_framework.c` line 351 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09_RG-5a28l1ikDUo:-NL09_RG-5a28l1ikDUp:b3siave) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L351)):*
> ```C
>             if (ret == -EINTR)
>                 continue;
>             log_error("Enclave EADD failed: %s", unix_strerror(ret));
> ```

I'd rephrase to `Enclave add-pages IOCTL failed: %s`
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 694 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09ktADOWENwasKskC:-NL09ktADOWENwasKskD:bimvz3e) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_ocalls.c#L694)):*
> ```C
>     int ret = debug_map_add(ocall_debug_args->name, ocall_debug_args->addr);
>     if (ret < 0) {
>         log_error("debug_map_add(%s, %p): %s", ocall_debug_args->name, ocall_debug_args->addr,
> ```

Please add `failed` in the message
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 711 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09nhS1x6y0a7cuLtS:-NL09nhS1x6y0a7cuLtT:bimvz3e) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_ocalls.c#L711)):*
> ```C
>     int ret = debug_map_remove(ocall_debug_args->addr);
>     if (ret < 0) {
>         log_error("debug_map_remove(%p): %s", ocall_debug_args->addr,
> ```

Please add `failed` in the message
___
*[`pal/src/host/linux-sgx/pal_files.c` line 305 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL0A6wu5Vqjf4N59vEo:-NL0A6wu5Vqjf4N59vEp:b-na9wqe) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/pal_files.c#L305)):*
> ```C
>                                            handle->file.total);
>         if (ret < 0) {
>             log_error("file_map - copy & verify on trusted file: %s", pal_strerror(ret));
> ```

Please add `failed` somewhere here
___
*[`common/src/pal_error.c` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1023#-NIiuviNBGbhK4YJ7TcE:-NL03Th48h5ZZwiEjrNg:b8jl91o) ([raw file](https://github.com/gramineproject/gramine/blob/0dd0095debba786f8c94e18676ecbb5db637b0d6/common/src/pal_error.c#L53)):*
> Unfortunately TLS is not supported in Gramine.

Are we talking about Thread Local Storage? It is supported in Gramine (called TCB, which  [...]

2023-01-05 11:47 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: 44 of 49 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/libos_malloc.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL06dBZ3NnHZkVj5F1k:-NL0g3AQ3O5H3O0T8K-4:blevd44) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/libos/src/libos_malloc.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this. It's impossible to deduce that the reported error is a PAL error, from `PalVirtualMemoryAlloc()`.

Two suggestions:
1. either change message to smth like `PalVirtualMemoryAlloc failed with: %s`,
2. or in the list of PAL errors, add to each string a suffix like `Function not implemented (PAL_NOTIMPLEMENTED)`

I would prefer the first solution.

Ditto for all other places in this PR.

UPDATE: Well, after looking through the whole PR, especially the PAL code, I lean to solution 2 now. It's really hard to mention in all log messages that "Something in PAL broke".
</blockquote></details>

1. This will be addressed IMHO by: https://reviewable.io/reviews/gramineproject/gramine/1040#-
2. Done
___
*[`pal/src/host/linux/pal_main.c` line 327 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL08alXBmvO98nG9ExL:-NL0i-pN9zOmQ_fOYTLs:byqels2) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux/pal_main.c#L327)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh, this mix of functions returning UNIX error codes and funcs returning PAL error codes is annoying.
</blockquote></details>

Agree :)
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 793 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL08s1F65EdSt2SGAPC:-NL0i2wO0YLwZuwUzXAs:bw8vaii) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/enclave_framework.c#L793)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point in printing `ret` here additionally? Remove it.
</blockquote></details>

My bad.
Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL097pS2VU6ZliCIJtS:-NL0iDoV1yn2O9cMkJDi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove ECREATE from this message? It's totally confusing (ECREATE is an SGX instruction, but here we fail on normal mmap syscall). I'd rephrase to: `Allocation of EPC memory failed: %s`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 168 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09JdMBGohYgyNQGly:-NL0iLBiDCdYxYajwS5u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd rephrase to `Enclave creation IOCTL failed: %s`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 173 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09TvpAipI2i8MdYtm:-NL0iV5ADo7GRnY_5udY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd rephrase to `Enclave creation IOCTL failed: %s`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 351 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09_RG-5a28l1ikDUo:-NL0igNR6EseIMRlj2TL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_framework.c#L351)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd rephrase to `Enclave add-pages IOCTL failed: %s`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 694 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09ktADOWENwasKskC:-NL0ippFEVC4hjPa2_NE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_ocalls.c#L694)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `failed` in the message
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 711 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL09nhS1x6y0a7cuLtS:-NL0iq71EGI06_ZWo4Vt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/host_ocalls.c#L711)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `failed` in the message
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 305 at r5](https://reviewable.io/reviews/gramineproject/gramine/1023#-NL0A6wu5Vqjf4N59vEo:-NL0iwF63KvEVz0sfEMb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9ee0ff2886aa527d5f90ad37eb4c4822d37977d/pal/src/host/linux-sgx/pal_files.c#L305)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `failed` somewhere here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-05 12:49 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-11 15:25 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-11 20:13 UTC, oshogbo reviewed
It seems like a network issue:
```
[2023-01-11T17:53:41.728Z] git.kernel.org[0: 139.178.84.217]: errno=Connection timed out
[2023-01-11T17:53:41.728Z] git.kernel.org[1: 2604:1380:4641:c500::1]: errno=Network is unreachable
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023#-:-NLXS92e2q8WnkGqQcvj:biohd7n)* status: 33 of 55 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2023-01-11 20:14 UTC, oshogbo commented
Jenkins, retest Jenkins-18.04 please

2023-01-11 20:14 UTC, oshogbo commented
Jenkins, retest Jenkins-20.04 please

2023-01-11 20:15 UTC, oshogbo commented
Jenkins, retest Jenkins-Debug-20.04 please

2023-01-11 20:15 UTC, oshogbo commented
Jenkins, retest Jenkins-Direct-Sanitizers please

2023-01-12 01:55 UTC, mkow approved these changes
> Reviewed 22 of 22 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-01-12 08:41 UTC, dimakuv approved these changes
> Reviewed 1 of 49 files at r1, 22 of 22 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1023)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-12 08:42 UTC, merged