[LibOS,PAL] Avoid `g_pal_public_state` from being overwritten by LibOS
gramineproject/gramine pull request #1026
Opened 2022-11-02 08:18 UTC by kailun-qin

The `g_pal_public_state` global variable is supposed to be constant. However previously, some LibOS code overwrote it which violated the original intention.

This patch adds a new object namely `g_pal_public_initial_state` (containing just a subset of `g_pal_public_state` fields), which is copied into the LibOS, only used by the parent Gramine process and later checkpointed to the child process. This guarantees `g_pal_public_state` to be constant and not overwritten by LibOS any more.

Resolves https://github.com/gramineproject/gramine/issues/872.

2022-11-02 09:32 UTC, mkow requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFrfiiqAuPMu7TRyy1o:b-llq9wd) (no related file):*
I'm neutral on this change, but would like to hear @boryspoplawski and @dimakuv opinions before approving.

___
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFraaF_1fw_AUb5tMfx):*
(modulo rewrapping)



_Suggestion:_
```
  This commit extracts a few `g_pal_public_state` fields into a new struct 
  named `g_pal_public_initial_state`. These fields are
  copied into the LibOS, only used by the parent Gramine process and later
  checkpointed to the child process. This makes `g_pal_public_state`
  constant and not overwritten by LibOS anymore.
```
___
*[`libos/src/fs/etc/fs.c` line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrc80D84QZFqTMigHO:-NFrc80D84QZFqTMigHP:b-9y96rl) ([raw file](https://github.com/gramineproject/gramine/blob/0784c8bf101b38fa60b1171f63a07dc08bafc34b/libos/src/fs/etc/fs.c#L159)):*
> ```C
>     size_t off = ADD_CP_OFFSET(sizeof(g_pal_public_initial_state.dns_host));
>     struct dns_host* new_dns_host = (struct dns_host*)(base + off);
>     memcpy(new_dns_host, &g_pal_public_initial_state.dns_host, sizeof(g_pal_public_initial_state.dns_host));
> ```

This needs rewrapping.
___
*[`libos/src/fs/etc/fs.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrdCn24zz690cFWbfk:-NFrdCn24zz690cFWbfl:b-9y96rl) ([raw file](https://github.com/gramineproject/gramine/blob/0784c8bf101b38fa60b1171f63a07dc08bafc34b/libos/src/fs/etc/fs.c#L170)):*
> ```C
> 
>     const struct dns_host* dns_host = (const struct dns_host*)(base + GET_CP_FUNC_ENTRY());
>     memcpy(&g_pal_public_initial_state.dns_host, dns_host, sizeof(g_pal_public_initial_state.dns_host));
> ```

This needs rewrapping.


<!-- Sent from Reviewable.io -->

2022-11-02 09:58 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFraaF_1fw_AUb5tMfx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(modulo rewrapping)
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrc80D84QZFqTMigHO:-NFrlZoMCZ5NBWdaliI3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0784c8bf101b38fa60b1171f63a07dc08bafc34b/libos/src/fs/etc/fs.c#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This needs rewrapping.
</blockquote></details>

Done.
___
*[`libos/src/fs/etc/fs.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrdCn24zz690cFWbfk:-NFrl_LoDOfvYMqEwDvF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0784c8bf101b38fa60b1171f63a07dc08bafc34b/libos/src/fs/etc/fs.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This needs rewrapping.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 10:19 UTC, mkow reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-11-02 16:14 UTC, boryspoplawski requested changes
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFt5N7c-Z74l7nEZXYj:b-3bhy8i) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this change, but would like to hear @boryspoplawski and @dimakuv opinions before approving.
</blockquote></details>

Mixed feelings. I like the idea of this "PAL public state" being const, but I don't like the fact that we have two copies of that data, one of which (from PAL) is only there to be copied to LibOS. Unfortunately I don't have a better idea

___
___
*[`libos/src/fs/etc/fs.c` line 87 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFt4ZpX2oTI7q3iAiud:-NFt4ZpX2oTI7q3iAiue:b6lu33) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/src/fs/etc/fs.c#L87)):*
> ```C
>             goto out;
>         for (size_t i = 0; i < g_pal_public_initial_state.dns_host.dn_search_count; i++) {
>             ret = put_string(&ptr, &space_left, " %s", g_pal_public_initial_state.dns_host.dn_search[i]);
> ```

Line limit exceeded.
___
*[`pal/include/pal/pal.h` line 181 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFt2-TD-H2hh44ONQLL:-NFt2-TD-H2hh44ONQLM:b-h81djc) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/pal/include/pal/pal.h#L181)):*
> ```objc
> /* Part of PAL initial state which is copied into the LibOS, only used by the parent Gramine process
>  * and later checkpointed to the child process. */
> struct pal_public_initial_state {
> ```

Why this is inside PAL? This belongs to LibOS (and in fact it's only used in LibOS).


<!-- Sent from Reviewable.io -->

2022-11-02 16:40 UTC, dimakuv requested changes
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFswO0C92QKAdPETAqu:b-gwduc8) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this change, but would like to hear @boryspoplawski and @dimakuv opinions before approving.
</blockquote></details>

I'm ok with this change.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFswHjZ5_NXAIK2jgdG:-NFswHjZ5_NXAIK2jgdH:b-8w6jl4) (no related file):*
Can also @oshogbo review this, since he introduced `dns_host` info?

___
___
*[`libos/include/libos_internal.h` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFswm5OA98JBmdpH-uu:-NFswm5OA98JBmdpH-uv:b-4g5gaz) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/include/libos_internal.h#L27)):*
> ```objc
> 
> extern const struct pal_public_state* g_pal_public_state;
> extern struct pal_public_initial_state g_pal_public_initial_state;
> ```

I don't particularly like this name (though I suggested it in the first place in #872).

This object is used only in LibOS and is introduced because of LibOS checkpointing. So maybe `g_pal_checkpointed_state`? This name is also not good... @mkow @boryspoplawski Any ideas?
___
*[`libos/src/libos_init.c` line 375 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFtCGE59h6zNIvA13Le:-NFtCGE59h6zNIvA13Lf:b-o8hant) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/src/libos_init.c#L375)):*
> ```C
> 
>     memcpy(&g_pal_public_initial_state.topo_info, &g_pal_public_state->topo_info,
>            sizeof(g_pal_public_state->topo_info));
> ```

Here we perform a *shallow* copy of `topo_info`. It's ok because the original objects were already allocated and securely verified in trusted PAL. But it's still a bit weird that we only do a shallow copy. @mkow @boryspoplawski Do you think it's fine?
___
*[`libos/src/libos_init.c` line 378 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFsxH58ApnHJRLfCYyX:-NFsxH598PM1z-Ii3Orn:b8ccybp) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/src/libos_init.c#L378)):*
> ```C
>     memcpy(&g_pal_public_initial_state.dns_host, &g_pal_public_state->dns_host,
>            sizeof(g_pal_public_state->dns_host));
> ```

It would be good to somehow forbid the LibOS to use `g_pal_public_state->topo_info` and `g_pal_public_state->dns_host`. So that we're sure the LibOS code doesn't use these fields accidentally.

But I don't know how to do it... I don't want to `memset(0)` these fields; this looks wrong and also impossible (since these are `const` now). Whatever.
___
*[`pal/include/pal/pal.h` line 181 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFt2-TD-H2hh44ONQLL:-NFtBtzE62LJj7hm4vmX:b-54oq9p) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/pal/include/pal/pal.h#L181)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is inside PAL? This belongs to LibOS (and in fact it's only used in LibOS).
</blockquote></details>

+1, this should be declared in one of the LibOS headers. I guess https://github.com/gramineproject/gramine/blob/master/libos/include/libos_internal.h is the best place.


<!-- Sent from Reviewable.io -->

2022-11-02 17:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFtSG_g3ajkysyZrf8R:b-5mxh0n) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm ok with this change.
</blockquote></details>

Looking at all the discussions, the current state seems cumbersome a bit. Maybe we should introduce a new PAL API, like `PalGetHostInfo`, which would provide all this information? It would be called only once in LibOS init code.

___
___
*[`libos/include/libos_internal.h` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFswm5OA98JBmdpH-uu:-NFtR_yc2ZyCnZbLMXFi:bkve8a2) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/include/libos_internal.h#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't particularly like this name (though I suggested it in the first place in #872).

This object is used only in LibOS and is introduced because of LibOS checkpointing. So maybe `g_pal_checkpointed_state`? This name is also not good... @mkow @boryspoplawski Any ideas?
</blockquote></details>

I don't like it either. Actually, why do we have this as one struct? Now it's unrelated to PAL, we can have a couple of global objects, e.g. `g_topo_info` and `g_dns_something_something`.
___
*[`libos/src/libos_init.c` line 375 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFtCGE59h6zNIvA13Le:-NFtRsyf6UtsV4XLw1ZU:b5xwayf) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/libos/src/libos_init.c#L375)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we perform a *shallow* copy of `topo_info`. It's ok because the original objects were already allocated and securely verified in trusted PAL. But it's still a bit weird that we only do a shallow copy. @mkow @boryspoplawski Do you think it's fine?
</blockquote></details>

Actually it's not. These objects were allocated by PAL, and here we kind of take the ownership (since the new pointer is non-const). If we for example did `free` on them, hell would break loose.
___
*[`pal/include/pal/pal.h` line 181 at r2](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFt2-TD-H2hh44ONQLL:-NFtScWm3cwnOJGPN9AU:bx7oo30) ([raw file](https://github.com/gramineproject/gramine/blob/9092121bfd11ded51be4cda2117606418cad51f8/pal/include/pal/pal.h#L181)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, this should be declared in one of the LibOS headers. I guess https://github.com/gramineproject/gramine/blob/master/libos/include/libos_internal.h is the best place.
</blockquote></details>

See other discussions, imo we don't even need this at all.


<!-- Sent from Reviewable.io -->

2022-11-03 09:36 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFwpsfbDjX4YCdi_wZx:bsfrwm1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Looking at all the discussions, the current state seems cumbersome a bit. Maybe we should introduce a new PAL API, like `PalGetHostInfo`, which would provide all this information? It would be called only once in LibOS init code.
</blockquote></details>

To be honest, I don't like it at all now. We're introducing new hacks/APIs to hide a previous hack/bad API.

I think maybe we close this PR and don't get back to this, unless we really have a need? This now consumes too much time/discussions, and I don't think this cosmetic change is worth our time.

___


<!-- Sent from Reviewable.io -->

2022-11-03 10:13 UTC, kailun-qin commented
Closing as the solution is not favorable

2022-11-03 10:13 UTC, closed without merging

2022-11-03 13:54 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1026)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1026#-NFrfiiqAuPMu7TRyy1n:-NFxl5LW2McBz4Zl-YFP:b-1b0dv7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, I don't like it at all now. We're introducing new hacks/APIs to hide a previous hack/bad API.

I think maybe we close this PR and don't get back to this, unless we really have a need? This now consumes too much time/discussions, and I don't think this cosmetic change is worth our time.
</blockquote></details>

The problem with this approach is that we will keep adding stuff to that PAL public thing, which are changed by LibOS and it will just get harder and harder to untangle.

___


<!-- Sent from Reviewable.io -->