[Pal/Linux-SGX] Add uniform message on using insecure manifest options
gramineproject/gramine pull request #103
Opened 2021-09-29 17:48 UTC by dimakuv

## Description of the changes 

Previously, all insecure-manifest-option messages were scattered. Some insecure manifest options were not warned about at all (e.g. `sgx.debug`). This commit adds a uniform message with all insecure manifest options detected, and only prints this message for the SGX PAL.

## How to test this PR? 

Run smth manually. E.g.:
```
$ gramine-sgx ./helloworld
---------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

    - sgx.debug = true                             (this is a debug enclave)
    - loader.insecure__use_cmdline_argv = true     (forwarding command-line args to the app)
    - sys.insecure__allow_eventfd = true           (host-based eventfd is enabled)
    - sgx.allowed_files = [ ... ]                  (some files allowed for unrestricted access)

Gramine will continue application execution, but this configuration must not be used in production!
---------------------------------------------------------------------------------------------------

Hello world!
```

Note that the non-SGX version doesn't print warnings anymore (which I consider correct behavior):
```
$ gramine-direct ./helloworld
Hello world!
```

2021-09-29 20:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[common/src/stdlib/printfmt.c, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknEXk0BkngZxdHujNf:-MknEXk0BkngZxdHujNg:bqtbdje) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/common/src/stdlib/printfmt.c#L90)):*
> ```C
>             // flag to pad on the right
>             case '-':
>                 padc = '-';
> ```

FYI: This was a bug (typo)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 526 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknEakFDx6SOF8v7Ry8:-MknEakFDx6SOF8v7Ry9:b-cdl2ln) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/host/Linux-SGX/db_main.c#L526)):*
> ```C
>     log_always("-------------------------------------------------------------------------------"
>                "--------------------");
>     log_always("Gramine detected the following insecure configurations:\n");
> ```

Blocking myself: I need to print these only if there are actually any insecure configurations (probably need to call this func twice, once to gather info and next time to actually print stuff)


<!-- Sent from Reviewable.io -->

2021-09-29 21:47 UTC, boryspoplawski requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[common/src/stdlib/printfmt.c, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MkmqbmdD-1PzfEe0esq:-Mkmqbme2tc5naGkJHV_:b-zdcr6j) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/common/src/stdlib/printfmt.c#L90)):*
> ```C
>             // flag to pad on the right
>             case '-':
>                 padc = '-';
> ```

?
This is unrelated and incorrect. `-` here means to pad from the right using spaces (hence `padc` is reset to ` `).
___
*[Pal/src/db_main.c, line 470 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknRuG--9Muxt_V0FCJ:-MknRuG--9Muxt_V0FCK:b-fjgwwd) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/db_main.c#L470)):*
> ```C
>     }
> 
>     if (use_cmdline_argv) {
> ```

There is no point in keeping empty scope here, just negate the condition.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 526 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknEakFDx6SOF8v7Ry8:-MknTnO76QzFnnJoSlcr:btjwy64) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/host/Linux-SGX/db_main.c#L526)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: I need to print these only if there are actually any insecure configurations (probably need to call this func twice, once to gather info and next time to actually print stuff)
</blockquote></details>

+1, please gather everything (maybe just multiple boolean variables?) and print only if anything needs to be printed.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 764 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknWd8R5hFc2qdOhngs:-MknWd8S4uxmeLUXWhtB:bnsyy3a) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/host/Linux-SGX/enclave_framework.c#L764)):*
> ```C
> 
> static void maybe_warn_about_allowed_files_usage(void) {
>     if (!g_pal_state.parent_process && !g_allowed_files_warn)
> ```

Now the `&& !g_allowed_files_warn` is not needed.


<!-- Sent from Reviewable.io -->

2021-09-30 07:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: 1 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[common/src/stdlib/printfmt.c, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MkmqbmdD-1PzfEe0esq:-MkpKmusB4warpv0hs45:b-gwov6h) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/common/src/stdlib/printfmt.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
This is unrelated and incorrect. `-` here means to pad from the right using spaces (hence `padc` is reset to ` `).
</blockquote></details>

No, why, this is correct. `-` is the "Left-align the output of this placeholder." (https://en.wikipedia.org/wiki/Printf_format_string#Flags_field).

This code was shamelessly stolen from the MIT's JOS -- https://github.com/wh5a/jos/blob/8223e70a9e8c9942f2fd02b6d4e046c7e6da34ed/lib/printfmt.c#L118. As you can see, this particular copy-pasted line contained a bug in Gramine (for whatever weird reason; someone actually re-typed it char by char?!).

However, I see that there is a comment `// flag to pad on the right` a couple lines above. This comment is misleading, let me reword it (I think the comment is correct in the sense "start from the literal and then pad with spaces (on the right) until the required length").

Also, try my PR with this change to `padc = -` and without this change -- the output will be incorrectly aligned.
___
*[Pal/src/db_main.c, line 470 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknRuG--9Muxt_V0FCJ:-MkpNJGI3Lirh6DKHTUX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/db_main.c#L470)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is no point in keeping empty scope here, just negate the condition.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 526 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknEakFDx6SOF8v7Ry8:-MkpTHJHEWbEKJs-ToXr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/host/Linux-SGX/db_main.c#L526)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1, please gather everything (maybe just multiple boolean variables?) and print only if anything needs to be printed.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 764 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MknWd8R5hFc2qdOhngs:-MkpNR1aCzUzdA4J_WPn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/Pal/src/host/Linux-SGX/enclave_framework.c#L764)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now the `&& !g_allowed_files_warn` is not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-30 17:20 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/103#-MkrfdoHBEJtpffinSms:-MkrfdoHBEJtpffinSmt:br48po3) (no related file):*
BTW, did you debug the issue with allowed files warning sometimes being printed multiple times? If yes, what was it and does this PR solve it?

---
___
*[common/src/stdlib/printfmt.c, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MkmqbmdD-1PzfEe0esq:-MkrebML50rHK3wkEBiK:b-cg3m4l) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/common/src/stdlib/printfmt.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, why, this is correct. `-` is the "Left-align the output of this placeholder." (https://en.wikipedia.org/wiki/Printf_format_string#Flags_field).

This code was shamelessly stolen from the MIT's JOS -- https://github.com/wh5a/jos/blob/8223e70a9e8c9942f2fd02b6d4e046c7e6da34ed/lib/printfmt.c#L118. As you can see, this particular copy-pasted line contained a bug in Gramine (for whatever weird reason; someone actually re-typed it char by char?!).

However, I see that there is a comment `// flag to pad on the right` a couple lines above. This comment is misleading, let me reword it (I think the comment is correct in the sense "start from the literal and then pad with spaces (on the right) until the required length").

Also, try my PR with this change to `padc = -` and without this change -- the output will be incorrectly aligned.
</blockquote></details>

It's all incorrect (both the new and the old version).
Program:
```c
int main(void) {
    printf("0x%-8x|\n", 0x1337);
    myprintf(1, "0x%-8x|\n", 0x1337); // original version
    myprintf(0, "0x%-8x|\n", 0x1337); // patched version
    return 0;
}
```
Output:
```
0x1337    |
0x    1337|
0x----1337|
```

I have a plan to rewrite this function from scratch, but only after the release.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 564 at r2](https://reviewable.io/reviews/gramineproject/gramine/103#-Mkrgx1RAxI4WlFg_wJy:-Mkrgx1RAxI4WlFg_wJz:b46ma6x) ([raw file](https://github.com/gramineproject/gramine/blob/cd9c582e9c1c66484c52f6217b889f4ee911464f/Pal/src/host/Linux-SGX/db_main.c#L564)):*
> ```C
>     if (ret < 0)
>         goto out;
> ```

Please add a note to `CONTRIBUTING.rst` mentioning any new options should be added here.


<!-- Sent from Reviewable.io -->

2021-10-01 07:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/103#-MkrfdoHBEJtpffinSms:-MkuaoykCPErBOKYFF2i:b-il54wv) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

BTW, did you debug the issue with allowed files warning sometimes being printed multiple times? If yes, what was it and does this PR solve it?
</blockquote></details>

No, I didn't debug that issue. No, this PR doesn't solve it.

---
___
*[Pal/src/host/Linux-SGX/db_main.c, line 564 at r2](https://reviewable.io/reviews/gramineproject/gramine/103#-Mkrgx1RAxI4WlFg_wJy:-MkugxeP-sXY_eQ8p-bg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cd9c582e9c1c66484c52f6217b889f4ee911464f/Pal/src/host/Linux-SGX/db_main.c#L564)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a note to `CONTRIBUTING.rst` mentioning any new options should be added here.
</blockquote></details>

Done.
___
*[common/src/stdlib/printfmt.c, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/103#-MkmqbmdD-1PzfEe0esq:-MkuazPk-8wp8AWpJ2VV:b-33k090) ([raw file](https://github.com/gramineproject/gramine/blob/9cdafda62f243ab5b7a29644f7c858c69307ec6d/common/src/stdlib/printfmt.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's all incorrect (both the new and the old version).
Program:
```c
int main(void) {
    printf("0x%-8x|\n", 0x1337);
    myprintf(1, "0x%-8x|\n", 0x1337); // original version
    myprintf(0, "0x%-8x|\n", 0x1337); // patched version
    return 0;
}
```
Output:
```
0x1337    |
0x    1337|
0x----1337|
```

I have a plan to rewrite this function from scratch, but only after the release.
</blockquote></details>

You're right. I only tested with strings (`%s`). Apparently this function is broken.

Let me revert this change and do manual padding...


<!-- Sent from Reviewable.io -->

2021-10-01 13:18 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-10-01 14:57 UTC, mkow requested changes
I'm glad that someone finally implemented this, it's a much needed change :)

> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103#-:-MkwLP8e4V0ztcEU9wTI:bq3aimp)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 593 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwKQtz21ZlWFM4jHUE:-MkwKQu-0X8cCZUp-Dgp:b5jde7m) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L593)):*
> ```C
>     if (use_host_env)
>         log_always("    - loader.insecure__use_host_env = true        "
>                    "(forwarding host environment vars to the app)");
> ```

Here and one above: I'd change to "(forwarding environment vars from untrusted host to the app)" (I'd like to have that "untrusted" word)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 605 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwKvHd0vcJ_Fsvvhi1:-MkwKvHd0vcJ_Fsvvhi2:b1tebru) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L605)):*
> ```
> allowed for unrestricted access
> ```

It's not the issue actually here - the issue is that the access is "unprotected". Maybe something like "(all files are passed through from untrusted host, without verification)" would be better?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 609 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwLI7k2Gb5Y2XlSQ6w:-MkwLI7lBnqcFua7BC4F:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L609)):*
> ```C
>     if (use_allowed_files)
>         log_always("    - sgx.allowed_files = [ ... ]                 "
>                    "(some files allowed for unrestricted access)");
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-10-01 18:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 593 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwKQtz21ZlWFM4jHUE:-Mkwxeyh6N5tbwa4mG54:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L593)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Here and one above: I'd change to "(forwarding environment vars from untrusted host to the app)" (I'd like to have that "untrusted" word)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 605 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwKvHd0vcJ_Fsvvhi1:-Mkx-yzNCQUThjkxopis:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L605)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> allowed for unrestricted access
> ```

It's not the issue actually here - the issue is that the access is "unprotected". Maybe something like "(all files are passed through from untrusted host, without verification)" would be better?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 609 at r3](https://reviewable.io/reviews/gramineproject/gramine/103#-MkwLI7k2Gb5Y2XlSQ6w:-Mkx-zUwBJpIQNfoAmJw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ce8461935e48cb4477299ba4dd79e4638e8cd25/Pal/src/host/Linux-SGX/db_main.c#L609)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 18:04 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-01 18:52 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-10-01 19:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-10-01 19:09 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/103)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-01 20:13 UTC, merged