[CI] WIP: Add a VM-based Jenkins pipeline
gramineproject/gramine pull request #1032
Opened 2022-11-08 09:58 UTC by dimakuv

## Description of the changes 

**WORK IN PROGRESS!** I'm testing Jenkins.

New Jenkins pipeline runs a Docker container that creates a minimal VM based on https://github.com/gramineproject/device-testing-tools repo and runs a subset of Gramine tests, in particular, the device IOCTL tests. The pipeline uses Ubuntu 22.04 with modern Linux kernel (to have an upstream SGX driver and support for SGX in KVM) and QEMU/KVM to run the VM.

## How to test this PR? 

New pipeline in Jenkins.

2022-11-08 10:44 UTC, woju commented
Jenkins, test linux-sgx-vm-gcc-release please

2022-11-08 16:45 UTC, woju commented
Jenkins, test linux-sgx-vm-gcc-release please

2022-11-08 16:51 UTC, woju commented
Jenkins, test linux-sgx-vm-gcc-release please

2022-11-09 13:36 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-17 16:06 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-18 10:43 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-18 10:57 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-21 19:11 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-22 15:51 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-24 07:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 0 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "WIP" found in commit messages' one-liners

___
*[`.ci/ubuntu22.04.dockerfile` line 76 at r8](https://reviewable.io/reviews/gramineproject/gramine/1032#-NH_IGfB5hoZF0g0fmL4:-NHcchBm9Ohy8qR2s1Wt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fde56922d076fe49b2762b6f359be165c8b28fa7/.ci/ubuntu22.04.dockerfile#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe split "normal" dependencies (also found in Ubuntu 18.04 and 20.04 dockerfiles) from the "VM-specific" dependencies?
</blockquote></details>

Done.
___
*[`.ci/lib/config-docker.jenkinsfile` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/1032#-NH_HanI2kpsN25261h4:-NHcYZEeC4vGHQJtzUEF:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fde56922d076fe49b2762b6f359be165c8b28fa7/.ci/lib/config-docker.jenkinsfile#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I must move it to `.ci/linux-sgx-vm-gcc-release.jenkinsfile` file because `sgx_vepc` can anyway be accessed only by users with group `sgx`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-24 10:30 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-11-24 10:54 UTC, dimakuv commented
Jenkins, test this please

2022-11-24 12:00 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2022-12-01 09:22 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (I want to see the error, so need to kick Jenkins again)

2022-12-01 11:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 0 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`.ci/ubuntu22.04.dockerfile` line 21 at r9](https://reviewable.io/reviews/gramineproject/gramine/1032#-NHcfaGp9vesZoawNfPF:-NHcfaGp9vesZoawNfPG:b-xvfky8) ([raw file](https://github.com/gramineproject/gramine/blob/49e5fc873992510dbb3ef6d7b3b87e1c3d9e2f7c/.ci/ubuntu22.04.dockerfile#L21)):*
> ```Dockerfile
>     libaprutil1-dev \
>     libcjson-dev \
>     libcurl4-openssl-dev \
> ```

`libcurl4-openssl-dev` must be removed, see #773


<!-- Sent from Reviewable.io -->

2022-12-02 00:24 UTC, boryspoplawski requested changes
> Reviewed 1 of 5 files at r4, 1 of 5 files at r8, 2 of 5 files at r12, 8 of 10 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 12 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIExrORDnM1mKPYLT0M):*
Could we not give names to all features? :) Maybe just `ioctl passthrough`?
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 14 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEzFDP7wEzMogcftvz:-NIEzFDP7wEzMogcftw-:buzp35e) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L14)):*
> ```
>         " --security-opt seccomp=${env.WORKSPACE}/scripts/docker_seccomp_aug_2022.json"
> 
>     // Required by QEMU to run Linux kernel in VM
> ```

Well, it's because we use host kernel as guest kernel for simplicity. Worth noting here (current version very vague)
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 21 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEzoYJ5VoKEyVtO71Z:-NIEzoYJ5VoKEyVtO71_:b-ul2eqa) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L21)):*
> ```
>     env.DOCKER_ARGS_COMMON += ' --group-add ' + kvm_gid
> 
>     if (fileExists('/dev/kvm')) {
> ```

Why this is conditional? We always require this
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 29 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEztYr5pTI8M5LJvoA:-NIEztYr5pTI8M5LJvoB:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L29)):*
> ```
>     env.DOCKER_ARGS_SGX += ' --group-add ' + sgx_gid
> 
>     if (fileExists('/dev/sgx_vepc')) {
> ```

ditto
___
*[`.ci/ubuntu22.04.dockerfile` line 3 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF-Jzm9q1EjezKnfiq:-NIF-Jzm9q1EjezKnfir:bip5p4i) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L3)):*
> ```Dockerfile
> FROM ubuntu:22.04
> 
> # Add steps here to set up dependencies
> ```

? I don't understand this comment
___
*[`.ci/ubuntu22.04.dockerfile` line 93 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF3DmaE43zFC-tIRaR:-NIF-vkl5bSuX9IO8s92:btw4ng6) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L93)):*
> ```Dockerfile
>     qemu-kvm
> 
> # Kernel on the host machine is built with GCC-10, so we need to set it as default in Docker
> ```

TBH I've never understood the need for this. What is the problem with using different compiler?
___
*[`.ci/ubuntu22.04.dockerfile` line 121 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF49tI9ujTGjdLP6Pt:-NIF49tI9ujTGjdLP6Pu:b-lrbfhd) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L121)):*
> ```Dockerfile
> 
> # Set environment variables.
> ENV HOME /leeroy
> ```

Wouldn't this be enough?



_Suggestion:_
```Dockerfile
RUN adduser --disabled-password leeroy

# Make a directory for the intel driver
RUN mkdir -p /opt/intel && chown leeroy /opt/intel

WORKDIR /home/leeroy

USER leeroy
```
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 35 at r8](https://reviewable.io/reviews/gramineproject/gramine/1032#-NH_HqbE4NuQWLN_NSFM:-NIF8U4I7t1LVk58hC_4:bvj92d0) ([raw file](https://github.com/gramineproject/gramine/blob/fde56922d076fe49b2762b6f359be165c8b28fa7/.ci/lib/stage-build-sgx-vm.jenkinsfile#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I currently test only one program -- the `device_ioctl` LibOS test. So these Sanitizers are quite useless. Maybe I just remove from this job?
</blockquote></details>

Why useless? I don't understand this comment
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NIF7Zv004lzyH2U-XD3:b-wq1nck) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
> ```
> stage('build') {
>     // we add `/sbin` to PATH to find the `modprobe` program
> ```

Are you sure `sbin` is not already in PATH? It should be
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 8 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7dorCK7jW1rNFUZI:-NIF7dorCK7jW1rNFUZJ:b-wyz8k7) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L8)):*
> ```
>         git clone https://github.com/gramineproject/device-testing-tools.git
>         cd device-testing-tools
>         git checkout 3149060c5b4c69443954d020e25f00798a6da286
> ```

Why pin the commit? This is our repo, we should keep master working all the time.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 11 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7ns422SxZM0RmHYw:-NIF7ns422SxZM0RmHYx:b429omw) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L11)):*
> ```
> 
>         cd initramfs_builder
>         cp -f new_init_jenkins new_init
> ```

Please remove this and add as an argument to `make`
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 12 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF899GAT_0a8ygsoVp:-NIF899GAT_0a8ygsoVq:b1v66qr) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L12)):*
> ```
>         cd initramfs_builder
>         cp -f new_init_jenkins new_init
>         make
> ```

`${MAKEOPTS}`
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 15 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF89zp-b-LVNlhWWav:-NIF89zp-b-LVNlhWWaw:b1v66qr) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L15)):*
> ```
> 
>         cd ../gramine-device-testing-module
>         make
> ```

`${MAKEOPTS}`
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 18 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF8HxH53IwQd6jqmyF:-NIF8HxH53IwQd6jqmyG:bt9xm50) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L18)):*
> ```
>     '''
> 
>     sh '''
> ```

What on earth is this
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 52 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF8pwl3RpftRKBWq6M:-NIF8pwl3RpftRKBWq6N:be8a24u) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L52)):*
> ```
>                 -Dsgx=enabled \
>                 -Dtests=enabled \
>                 -Dsgx_driver_include_path="$PWD/driver" \
> ```

Why do we need this??
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 71 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF9SWK-nIvDngwVskq:-NIF9SWLC7fLAD0sgRJ0:bb742ow) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L71)):*
> ```
>     archiveArtifacts "usr/**/*"
> 
>     // Absolute path to libdir, as configured by Meson.
> ```

Shou
___
*[`.ci/lib/stage-test-v [...]

2023-01-17 16:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 8 of 15 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 12 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIExrORDnM1mKPYLT0M):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we not give names to all features? :) Maybe just `ioctl passthrough`?
</blockquote></details>

Done
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 14 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEzFDP7wEzMogcftvz:-NM-4fMO-KRaKyFfQ_lF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, it's because we use host kernel as guest kernel for simplicity. Worth noting here (current version very vague)
</blockquote></details>

Done.
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 21 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEzoYJ5VoKEyVtO71Z:-NM-4iHW3BBBBmZXq2YB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is conditional? We always require this
</blockquote></details>

Done.
___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 29 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIEztYr5pTI8M5LJvoA:-NM-4mpk3ALn_wgsy2US:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`.ci/ubuntu22.04.dockerfile` line 21 at r9](https://reviewable.io/reviews/gramineproject/gramine/1032#-NHcfaGp9vesZoawNfPF:-NM-4vWY5MtGUB_nOwjw:b-cgerfj) ([raw file](https://github.com/gramineproject/gramine/blob/49e5fc873992510dbb3ef6d7b3b87e1c3d9e2f7c/.ci/ubuntu22.04.dockerfile#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`libcurl4-openssl-dev` must be removed, see #773
</blockquote></details>

Will do during final rebase
___
*[`.ci/ubuntu22.04.dockerfile` line 3 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF-Jzm9q1EjezKnfiq:-NM-4nrA2spRcmZq10Qr:b-40lhi2) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

? I don't understand this comment
</blockquote></details>

Done. This Dockerfile is largely copy-pasted from other Dockerfiles in `.ci/`, and I didn't want to modify too much. But sure, can simplify here.
___
*[`.ci/ubuntu22.04.dockerfile` line 93 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF3DmaE43zFC-tIRaR:-NM-54_p4egD-1x1SGIc:bo0e3mg) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TBH I've never understood the need for this. What is the problem with using different compiler?
</blockquote></details>

The kernel-module `make` fails otherwise. The error message is like this one: https://bugzilla.redhat.com/show_bug.cgi?id=1684833
___
*[`.ci/ubuntu22.04.dockerfile` line 121 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF49tI9ujTGjdLP6Pt:-NM-5pVlBMdamDZSimtr:beswlkj) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wouldn't this be enough?
</blockquote></details>

This leeroy stuff should be removed from all Dockerfiles completely, it's not really useful for anything. But this is for a separate PR.

For now, I added a FIXME comment explaining this.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 35 at r8](https://reviewable.io/reviews/gramineproject/gramine/1032#-NH_HqbE4NuQWLN_NSFM:-NM-7AT799zaI097Xm08:b-agqwpm) ([raw file](https://github.com/gramineproject/gramine/blob/fde56922d076fe49b2762b6f359be165c8b28fa7/.ci/lib/stage-build-sgx-vm.jenkinsfile#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why useless? I don't understand this comment
</blockquote></details>

OK, then I'm keeping these sanitizers. The original question was -- if I only run a couple tests, do I really need to also test with Sanitizers (since this will have pretty low coverage). But I guess low coverage is better than no coverage.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NM-3ajC3040IR4illrJ:b-x7d9cw) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Are you sure `sbin` is not already in PATH? It should be
</blockquote></details>

No, it shouldn't. We use Debian 11 for this CI pipeline, which doesn't have `/sbin` in the PATH (for non-root users). See:
- https://unix.stackexchange.com/questions/232782/is-there-a-reason-i-would-not-add-usr-local-sbin-usr-sbin-sbin-to-my-path-o
- https://forums.debian.net/viewtopic.php?t=151543
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 8 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7dorCK7jW1rNFUZI:-NM-6HS89NfyzND24TZy:bolx3ez) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why pin the commit? This is our repo, we should keep master working all the time.
</blockquote></details>

I added a TODO comment -- will need to be fixed at final rebase (blocked myself on this). Currently I need to specify a specific commit because the required PR is not yet merged: https://github.com/gramineproject/device-testing-tools/pull/7
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 11 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7ns422SxZM0RmHYw:-NM-JTXL8mrVz-_3YbLC:b-vgzyt0) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove this and add as an argument to `make`
</blockquote></details>

Done in a different way: the `new_init` script is now for Jenkins by default, so no need to `cp` and to have an arg to `make`.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 12 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF899GAT_0a8ygsoVp:-NM-6z6T88KXZkjPhq0K:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`${MAKEOPTS}`
</blockquote></details>

Done.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 15 at r14](htt [...]

2023-01-17 23:22 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`.ci/ubuntu22.04.dockerfile` line 121 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF49tI9ujTGjdLP6Pt:-NM0zqyt3u3MUUAsyNDw:bdy7fc4) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/ubuntu22.04.dockerfile#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This leeroy stuff should be removed from all Dockerfiles completely, it's not really useful for anything. But this is for a separate PR.

For now, I added a FIXME comment explaining this.
</blockquote></details>

Well it changes user to unprivileged, so there is some point in it. Anyway unblocking
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NM1-8aV7ZhoMT0z6Klu:b-hzbhua) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, it shouldn't. We use Debian 11 for this CI pipeline, which doesn't have `/sbin` in the PATH (for non-root users). See:
- https://unix.stackexchange.com/questions/232782/is-there-a-reason-i-would-not-add-usr-local-sbin-usr-sbin-sbin-to-my-path-o
- https://forums.debian.net/viewtopic.php?t=151543
</blockquote></details>

What? This runs inside docker, which uses Ubuntu...
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 8 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7dorCK7jW1rNFUZI:-NM101zmEB4OGx2DuqHR:bg4rske) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I added a TODO comment -- will need to be fixed at final rebase (blocked myself on this). Currently I need to specify a specific commit because the required PR is not yet merged: https://github.com/gramineproject/device-testing-tools/pull/7
</blockquote></details>

One could argue that Jenkins specific init script should reside where rest of jenkins files are (.ci in this repo).
I'm not active anymore so don't care that much
cc @mkow 
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 11 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7ns422SxZM0RmHYw:-NM10FrI7yxsjRyMzSEk:bask375) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done in a different way: the `new_init` script is now for Jenkins by default, so no need to `cp` and to have an arg to `make`.
</blockquote></details>

IMO that's not a good idea - the defaults are better for running this manually (locally, not in jenkins).
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 18 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF8HxH53IwQd6jqmyF:-NM11S6C99-7FiVV5AG9:b-nwuw3d) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Our CI host for this pipeline doesn't have the `asm/sgx.h` header file for the Intel SGX driver. So I'm downloading it explicitly and specify during `meson setup`.
</blockquote></details>

Why it doesn't have it? How's that possible?
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 71 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF9SWK-nIvDngwVskq:-NM10fEZ7KwqBDWGAZss:b-c1kkvd) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is not finished :)

This was copied from our Jenkinsfiles in `.ci/`. This is some magic by Woju.
</blockquote></details>

I don't remember what this was about and have no time to dig into this.
cc @mkow 


<!-- Sent from Reviewable.io -->

2023-01-18 15:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 12 of 15 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 8 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7dorCK7jW1rNFUZI:-NM4aHbS888xO5o5Kv26:b920wht) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

One could argue that Jenkins specific init script should reside where rest of jenkins files are (.ci in this repo).
I'm not active anymore so don't care that much
cc @mkow 
</blockquote></details>

Done, I embedded the script right here, in Jenkinsfile
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 11 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7ns422SxZM0RmHYw:-NM4aMFM4XyzpSD_J4P-:b-qanxah) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO that's not a good idea - the defaults are better for running this manually (locally, not in jenkins).
</blockquote></details>

Done, again in a slightly different way


<!-- Sent from Reviewable.io -->

2023-01-19 10:28 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2023-01-19 16:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 12 of 15 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NM9XlC4AbaBqyK2BJs4:b-riph6u) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What? This runs inside docker, which uses Ubuntu...
</blockquote></details>

Fair enough.

I checked via `echo "========= $PATH ==========="` in CI, and this is what I got:
```
========= /home/jenkins/workspace/linux-sgx-vm-gcc-release/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/games ===========
```

Why does this happen? Because of this, iiuc: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/.ci/lib/config-docker.jenkinsfile#L5

In other words, we're overriding the Docker-image `PATH` with our Jenkins-environment `PATH` (+ some PREFIX), and our Jenkins environment is nothing else but the host OS (which is Debian 11).


<!-- Sent from Reviewable.io -->

2023-01-19 16:06 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 12 of 15 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NM9lpqc5soc_zIah8AD:beiy867) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough.

I checked via `echo "========= $PATH ==========="` in CI, and this is what I got:
```
========= /home/jenkins/workspace/linux-sgx-vm-gcc-release/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/games ===========
```

Why does this happen? Because of this, iiuc: https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/.ci/lib/config-docker.jenkinsfile#L5

In other words, we're overriding the Docker-image `PATH` with our Jenkins-environment `PATH` (+ some PREFIX), and our Jenkins environment is nothing else but the host OS (which is Debian 11).
</blockquote></details>

This is a very bad idea. Host OS and in-docker paths can be quite different.


<!-- Sent from Reviewable.io -->

2023-01-20 12:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 10 of 15 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`.ci/ubuntu22.04.dockerfile` line 98 at r19](https://reviewable.io/reviews/gramineproject/gramine/1032#-NME6dsg0VC-yVjXiLc9:-NME6dsg0VC-yVjXiLcA:b9qf2g9) ([raw file](https://github.com/gramineproject/gramine/blob/2265d20f8a7ecde06f1dfa413cdcba032fa3dffe/.ci/ubuntu22.04.dockerfile#L98)):*
> ```Dockerfile
>     update-alternatives --set g++ /usr/bin/g++-10
> 
> # FIXME: below commands for the user `leeroy` are useless, remove them in all Dockerfiles
> ```

TODO(myself): Remove all the below during final rebase, after https://github.com/gramineproject/gramine/pull/1131 is merged
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NME6k4oCbbQK0Vsh67A:bydafo0) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
Yeah... I asked @woju if this is really needed, and if we can avoid this. I don't want to touch that generic code, since it is orthogonal and I don't know why it was needed like that in the first place.

UPDATE: reply from @woju:

> we need this PATH assignment, because we `meson install` with non-standard prefix (we need to install inside `$WORKSPACE`)
> and PATH in Jenkins is magic, i.e. you can't just `sh '''PATH='''`
> even `env.PATH=` is broken
> same for ENV PATH= in Dockerfile and any other combination really
> yes, this is broken in a variety of ways, and the current situation is only slightly less broken than other options and we're quite fortunate we are still getting away with it

So I'm keeping my code as is.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 18 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF8HxH53IwQd6jqmyF:-NMECGq4BqClJsq8k3Iz:bozpxuy) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why it doesn't have it? How's that possible?
</blockquote></details>

Ok, you're right, I had to do two things:
- Install `apt-get install linux-libc-dev -t bullseye-backports` on the host (to get `/usr/include/x86_64-linux-gnu/asm/sgx.h`)
- Setup the Docker volume redirection in the main Jenkinsfile: `--volume=/usr/include/x86_64-linux-gnu/asm/sgx.h:/usr/include/asm/sgx.h:ro`
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 52 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF8pwl3RpftRKBWq6M:-NMED5zZ1695IBjRayeM:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my reply above.
</blockquote></details>

Done
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIFB--Q95-__3CyphCD:-NME76s60h39JHMprSKp:b-1mhttn) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, removed. This was set in other LibOS regression tests (and they also don't need it), so I wanted to be uniform. But yes, this is not needed.
</blockquote></details>

FYI: I re-added `sgx.nonpie_binary = true` again. Apparently this is needed, because we build all tests by default with `fno-PIE`, see https://github.com/gramineproject/gramine/blob/ff9ec79ab27fb4f95daa35656d1410c695264509/libos/test/regression/meson.build#L240


<!-- Sent from Reviewable.io -->

2023-01-20 13:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 10 of 15 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`scripts/gitignore-check-files` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/1032#-NH_I7Qi5TX2760pdR35:-NMELMfg5KQMk1CkNEZt:b-wy1c8e) ([raw file](https://github.com/gramineproject/gramine/blob/fde56922d076fe49b2762b6f359be165c8b28fa7/scripts/gitignore-check-files#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should move this in a separate PR
</blockquote></details>

Created a PR: https://github.com/gramineproject/gramine/pull/1137

That PR should be merged before this one (and then on rebase of this PR, this change will go away).


<!-- Sent from Reviewable.io -->

2023-01-23 00:02 UTC, boryspoplawski reviewed
> Reviewed 1 of 3 files at r18, 2 of 3 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NMQumsGDyv-EJR4nZiS:b-ifld2b) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah... I asked @woju if this is really needed, and if we can avoid this. I don't want to touch that generic code, since it is orthogonal and I don't know why it was needed like that in the first place.

UPDATE: reply from @woju:

> we need this PATH assignment, because we `meson install` with non-standard prefix (we need to install inside `$WORKSPACE`)
> and PATH in Jenkins is magic, i.e. you can't just `sh '''PATH='''`
> even `env.PATH=` is broken
> same for ENV PATH= in Dockerfile and any other combination really
> yes, this is broken in a variety of ways, and the current situation is only slightly less broken than other options and we're quite fortunate we are still getting away with it

So I'm keeping my code as is.
</blockquote></details>

This is wrong, but I don't have the resources to fight this.
Unblocking, cc @mkow 


<!-- Sent from Reviewable.io -->

2023-04-25 13:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 5 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 7 at r23](https://reviewable.io/reviews/gramineproject/gramine/1032#-NTsfmdyBZSWS8ehJrX0:-NTsfmdyBZSWS8ehJrX1:bcnbdy0) ([raw file](https://github.com/gramineproject/gramine/blob/39f485386e0231fc6012ca47a837eb3b65652ec1/.ci/lib/stage-build-sgx-vm.jenkinsfile#L7)):*
> ```
> 
>         git clone https://github.com/gramineproject/device-testing-tools.git
>         cd device-testing-tools
> ```

The PR https://github.com/gramineproject/device-testing-tools/pull/8 was merged, so I added a fixup commit here that removes `git checkout ...`, because we can now use the default `master` branch.


<!-- Sent from Reviewable.io -->

2023-04-26 00:13 UTC, mkow requested changes
> Reviewed 1 of 5 files at r4, 1 of 5 files at r12, 2 of 10 files at r13, 3 of 3 files at r14, 2 of 7 files at r15, 1 of 3 files at r18, 1 of 3 files at r19, 1 of 2 files at r20, 8 of 9 files at r22, 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 22 at r23](https://reviewable.io/reviews/gramineproject/gramine/1032#-NTuq7TC1Fhc77WU6I3V:-NTuq7TC1Fhc77WU6I3W:b-66g9ne) ([raw file](https://github.com/gramineproject/gramine/blob/39f485386e0231fc6012ca47a837eb3b65652ec1/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L22)):*
> ```
>     env.DOCKER_ARGS_COMMON += ' --volume=/boot:/boot:ro'
> 
>     // only root and `kvm` group can access /dev/kvm, so add `kvm` GID to the in-Docker user
> ```

FYI: We need to be careful with this, it removes the isolation between the Docker interior and the host. It will be possible to accidentally break something on the Jenkins worker if we won't be careful.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NTurBaW3m1lN_9cNksR:b4rxfah) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is wrong, but I don't have the resources to fight this.
Unblocking, cc @mkow 
</blockquote></details>

Can't we pass that non-standard installation prefix using a different variable and just append to `PATH` here?
___
*[`libos/test/regression/device_ioctl.c` line 14 at r21](https://reviewable.io/reviews/gramineproject/gramine/1032#-NMpI3qbBBEWQfjCmiEs:-NMpI3qc1PijtxMxJJ_f:b-fnzmr0) ([raw file](https://github.com/gramineproject/gramine/blob/57d7ab4d6fe98fae4a615314e434bf292e7a43b5/libos/test/regression/device_ioctl.c#L14)):*
> ```C
> #include "gramine_test_dev_ioctl.h" /* currently unused */
> 
> #define STRING_READWRITE      "Hello world via read/write\n"
> ```

why this weird spacing?


<!-- Sent from Reviewable.io -->

2023-04-26 11:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: 14 of 15 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`.ci/linux-sgx-vm-gcc-release.jenkinsfile` line 22 at r23](https://reviewable.io/reviews/gramineproject/gramine/1032#-NTuq7TC1Fhc77WU6I3V:-NTxDzch2maR6i9F3ZJT:b-f4zasg) ([raw file](https://github.com/gramineproject/gramine/blob/39f485386e0231fc6012ca47a837eb3b65652ec1/.ci/linux-sgx-vm-gcc-release.jenkinsfile#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: We need to be careful with this, it removes the isolation between the Docker interior and the host. It will be possible to accidentally break something on the Jenkins worker if we won't be careful.
</blockquote></details>

Yes, agreed.
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NTxFkOb-53TcPHZtolf:b-2cya2h) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can't we pass that non-standard installation prefix using a different variable and just append to `PATH` here?
</blockquote></details>

Working on this in a separate PR, let's see if it will work out.
___
*[`libos/test/regression/device_ioctl.c` line 14 at r21](https://reviewable.io/reviews/gramineproject/gramine/1032#-NMpI3qbBBEWQfjCmiEs:-NTxE8kn2J5kBFjQpveh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57d7ab4d6fe98fae4a615314e434bf292e7a43b5/libos/test/regression/device_ioctl.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why this weird spacing?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-27 01:12 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 2 at r14](https://reviewable.io/reviews/gramineproject/gramine/1032#-NIF7Zv004lzyH2U-XD2:-NU-G0cj-wsg51MZzF0s:b-54bpnw) ([raw file](https://github.com/gramineproject/gramine/blob/53591f99e5c49f8a8fab29ffd1d5b47f07a54c64/.ci/lib/stage-build-sgx-vm.jenkinsfile#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I give up, please check #1312 for details. Jenkins is cancer, and I don't want to look at it anymore.

I will insist on keeping this hack; I spent enough time on circumventing this bug.
</blockquote></details>

Uh, Jenkins strikes again :/ Ok, resolving then.


<!-- Sent from Reviewable.io -->

2023-04-28 12:48 UTC, mkow approved these changes
> Dismissed @boryspoplawski from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1032)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`.ci/ubuntu22.04.dockerfile` line 21 at r9](https://reviewable.io/reviews/gramineproject/gramine/1032#-NHcfaGp9vesZoawNfPF:-NU6ttNY8QBvXmOjzcYU:b-g7qfo7) ([raw file](https://github.com/gramineproject/gramine/blob/49e5fc873992510dbb3ef6d7b3b87e1c3d9e2f7c/.ci/ubuntu22.04.dockerfile#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Dismissing Borys, this issue was fixed and he unfortunately won't have time to re-review this PR.


<!-- Sent from Reviewable.io -->

2023-05-01 16:14 UTC, merged