[tools/sgx] WIP: Interoperable RA-TLS
gramineproject/gramine pull request #1039
Opened 2022-11-11 14:21 UTC by dimakuv

## Description of the changes 

There is a pending RA-TLS/RATS standard, with standardized OID and CBOR representation for attestation evidence (in particular SGX quote with attached claimes like certificate public key).

TODOs:
- libcbor package only has shared lib; use subproject to build static
- update TCG_DICE_TAGGED_EVIDENCE_CBOR_TAG to IANA tag once registered
- write ra_tls_verify_common.c:extract_quote_and_verify_claims()
- describe Interoperable RA-TLS (and how we preserve legacy OID) in docs
- split CBOR funcs in separate file?

## How to test this PR? 

Not yet implemented, but will be done in CI.

2022-11-16 15:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 13 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "WIP" found in commit messages' one-liners

___
*[`meson.build` line 265 at r2](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH06rxq4bWuqwyNMcjN:-NH06rxq4bWuqwyNMcjO:b-sf32i7) ([raw file](https://github.com/gramineproject/gramine/blob/ade87eef01916b235993b157263f7304baab8bee/meson.build#L265)):*
> ```Meson
>     protobuf_dep = dependency('libprotobuf-c')
> 
>     libcbor_dep = subproject('libcbor-0.9.0').get_variable('libcbor_dep')
> ```

FYI: I cannot use https://mesonbuild.com/CMake-module.html# because of this bug: https://github.com/mesonbuild/meson/issues/10764


<!-- Sent from Reviewable.io -->

2022-11-17 12:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4chM29VGknV4QrDaq:-NH4chM32oAjcApI0uIq:bjvzjhl) (no related file):*
For high-level overview of this proposal, I recommend to read this and look at the new RA-TLS diagram: https://github.com/gramineproject/gramine/blob/dimakuv/interoperable-ra-tls/Documentation/attestation.rst

___


<!-- Sent from Reviewable.io -->

2022-11-17 12:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 14 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dCHO1QJ0YJoO3iZW:-NH4dCHP7Z39nENdo1bx:b-bh4yot) (no related file):*
For Interoperable RA-TLS in other SGX frameworks, track these:
- https://github.com/inclavare-containers/librats/pull/70
- https://github.com/openenclave/openenclave/pull/4653

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dJEw51zbacAe1eYW:-NH4dJEw51zbacAe1eYX:b2okqw6) (no related file):*
This PR is **ready for review**.

However, to finalize the PR, we need a published Interoperable RA-TLS spec and registered CBOR tags. This is work in progress. But we can do reviews, testing and discussions in parallel.

___


<!-- Sent from Reviewable.io -->

2022-11-25 08:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NHhns5XCGLi_cVF7-yT:-NHhns5XCGLi_cVF7-yU:b-73i25w) (no related file):*
I rebased this PR now on top of current master because we merged a prerequisite PR https://github.com/gramineproject/gramine/pull/1038

___


<!-- Sent from Reviewable.io -->

2022-11-30 07:03 UTC, KB5201314 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 41 at r4](https://reviewable.io/reviews/gramineproject/gramine/1039#-NI6IqCe05VKpH9JtmT2:-NI6IqCe05VKpH9JtmT3:bx575l0) ([raw file](https://github.com/gramineproject/gramine/blob/cc4671c6d7d6862cb98d284ea9b6ff3671acca40/tools/sgx/ra-tls/ra_tls.h#L41)):*
> ```objc
> static const size_t g_quote_oid_size = sizeof(g_quote_oid);
> 
> /* standard TCG DICE "tagged evidence" OID (2.23.133.4.9) */
> ```

Hello Dmitrii 👋, I'm from librats. Where did you get this oid? According to the definition in the TCG DICE Attestation Architecture document, it should be  `2.23.133.5.4.9`. Please let me know if the document has been updated.


<!-- Sent from Reviewable.io -->

2022-12-01 09:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 16 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners (waiting on @KB5201314)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 41 at r4](https://reviewable.io/reviews/gramineproject/gramine/1039#-NI6IqCe05VKpH9JtmT2:-NIBu9PC6Qra41SSo_UI:bm43f5y) ([raw file](https://github.com/gramineproject/gramine/blob/cc4671c6d7d6862cb98d284ea9b6ff3671acca40/tools/sgx/ra-tls/ra_tls.h#L41)):*
<details><summary><i>Previously, KB5201314 (imlk) wrote…</i></summary><blockquote>

Hello Dmitrii 👋, I'm from librats. Where did you get this oid? According to the definition in the TCG DICE Attestation Architecture document, it should be  `2.23.133.5.4.9`. Please let me know if the document has been updated.
</blockquote></details>

Yes, indeed, this is a wrong OID. I'll need to fix it everywhere:
- In RA-TLS code itself (both in OID and in raw-OID)
- In Examples
- In Documentation (on the diagram)
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 227 at r4](https://reviewable.io/reviews/gramineproject/gramine/1039#-NIBuQFj6H2pF8ekD32n:-NIBuQFj6H2pF8ekD32o:b1s26rw) ([raw file](https://github.com/gramineproject/gramine/blob/cc4671c6d7d6862cb98d284ea9b6ff3671acca40/tools/sgx/ra-tls/ra_tls_attest.c#L227)):*
> ```C
> }
> 
> /*! generate claims -- CBOR map with { "pubkey" = <DER-formatted pubkey as CBOR bstr> } */
> ```

The new version of the standard proposes to use:
```
"pubkey-hash" = CBOR array of [ hash-algo-id, hash-value ]
```

See https://github.com/sacmwg/draft-ietf-sacm-coswid/blob/master/draft-ietf-sacm-coswid.md#the-hash-entry-array

Change my implementation to this.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 352 at r4](https://reviewable.io/reviews/gramineproject/gramine/1039#-NIBxk1O0V7A5xlj6Z25:-NIBxk1O0V7A5xlj6Z26:b-qbzdkv) ([raw file](https://github.com/gramineproject/gramine/blob/cc4671c6d7d6862cb98d284ea9b6ff3671acca40/tools/sgx/ra-tls/ra_tls_verify_common.c#L352)):*
> ```C
>         }
> 
>         if (strncmp((char*)cbor_string_handle(claims_pairs[i].key), "pubkey",
> ```

ditto (`"pubkey-hash"`)


<!-- Sent from Reviewable.io -->

2023-02-22 06:22 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 17 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrS-pQ7ojhS1kB-jUg):*
SGX/TDX



_Code quote:_
```
SGX
```
___
*[`Documentation/attestation.rst` line 251 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkH8j2SWGpLiRTqZz:-NOrkH8j2SWGpLiRTq_-:b-6i5xj3) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L251)):*
> ```reStructuredText
> SGX enclave (attester).
> 
> .. image:: ./img/ratls-interoperable.svg
> ```

Same question (see below) for the `pubkey` of claims in the diagram.



_Code quote:_
```reStructuredText
/img/ratls-interoperable.svg
```
___
*[`Documentation/attestation.rst` line 267 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOriNrABIbn413oZefr:-NOriNrABIbn413oZefs:b-uckxj7) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L267)):*
> ```reStructuredText
> the so-called evidence claims, with the most important one being the "pubkey"
> claim that contains the ephemeral public key (in DER format) generated by the
> enclavized application. For reasons of standardization, the OID object and all
> ```

Isn't it just `""pubkey-hash""` rather than the key itself?



_Code quote:_
```reStructuredText
the so-called evidence claims, with the most important one being the "pubkey"
claim that contains the ephemeral public key (in DER format) generated by the
enclavized application. For reasons of standardization, the OID object and all
```
___
*[`Documentation/attestation.rst` line 273 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrk3-v4rqZ7fqrmJVQ:-NOrk3-v4rqZ7fqrmJVR:b-n4w04m) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L273)):*
> ```reStructuredText
> complete claims buffer. This is how the RA-TLS certificate is tied to the
> enclavized application that generated it (through the claims buffer that
> contains the enclave-generated public key). In the end, the RA-TLS certificate
> ```

Same question as above.



_Code quote:_
```reStructuredText
contains the enclave-generated public key
```
___
*[`Documentation/attestation.rst` line 282 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkn7WCPXuSzRqNiFK:-NOrkn7WCPXuSzRqNiFL:bgvs3df) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L282)):*
> ```reStructuredText
> The diagram above shows the non-standard X.509 certificate generated by RA-TLS.
> This format, with a non-standard X.509 extension field (and a dummy OID), was
> developed prior to the "Interoperable RA-TLS" specification, and is deprecated.
> ```

will be?



_Code quote:_
```reStructuredText
is
```
___
*[`Documentation/attestation.rst` line 283 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkzPI2g7C1UiCkC99:-NOrkzPI2g7C1UiCkC9A:bmjrh58) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L283)):*
> ```reStructuredText
> This format, with a non-standard X.509 extension field (and a dummy OID), was
> developed prior to the "Interoperable RA-TLS" specification, and is deprecated.
> One can see that the non-standard OID directly embeds the SGX quote, doesn't
> ```

It's not accurate. The OID is just an identifier.



_Code quote:_
```reStructuredText
OID
```
___
*[`Documentation/attestation.rst` line 286 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrlC7y60uB2pINrLYu:-NOrlC7y60uB2pINrLYv:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L286)):*
> ```reStructuredText
> have the concept of claims and doesn't use the CBOR data format.
> 
> Gramine generates RA-TLS certificates that contain both the new standard OID and
> ```

ditto



_Code quote:_
```reStructuredText
OID
```
___
*[`subprojects/libcbor-0.9.0.wrap` line 2 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrT1GI6dbwoR_1gAgn:-NOrT1GI6dbwoR_1gAgo:bbc48eo) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/subprojects/libcbor-0.9.0.wrap#L2)):*
> ```
> [wrap-file]
> directory = libcbor-0.9.0
> ```

Note: there is a newer version of libcbor available.



_Code quote:_
```
libcbor-0.9.0
```
___
*[`subprojects/packagefiles/libcbor/meson.build` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH-nxw78TTL83gD8dXJ:-NOrTH7s7xcrIgvBTxAn:boyexn4) ([raw file](https://github.com/gramineproject/gramine/blob/349438f777706752226719be526067da779a02c9/subprojects/packagefiles/libcbor/meson.build#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: this hack is taken from https://github.com/gramineproject/gramine/pull/773/commits/c15ca888f3e7090841e9a97b2e21be223b178026 (PR #773). Thanks to Kailun for this!
</blockquote></details>

We eventually droped the hack in the merged version of https://github.com/gramineproject/gramine/pull/773. Does the solution applies to this PR as well?
___
*[`tools/sgx/ra-tls/ra_tls.h` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrltDO-Zgi2Upaa-nN:-NOrltDO-Zgi2Upaa-nO:b-tkmfky) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls.h#L46)):*
> ```objc
> /* standard TCG DICE "tagged evidence" OID (2.23.133.5.4.9) */
> #define TCG_DICE_TAGGED_EVIDENCE_OID { 0x67, 0x81, 0x05, 0x05, 0x04, 0x09 }
> #define TCG_DICE_TAGGED_EVIDENCE_OID_RAW { 0x06, 0x06, 0x67, 0x81, 0x05, 0x05, 0x04, 0x09 }
> ```

Where is this "raw" OID used?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 223 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrMlmB-c6G3Mj53diC:-NOrMlmCCBH0vks7PDkR:bknhzm8) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L223)):*
> ```C
> 
> /*! generate hash-entry -- CBOR array with [ hash-alg-id, hash-value -- hash of pubkey ] */
> static int generate_serialized_hash_entry(mbedtls_pk_context* pk, uint8_t** out_hash_entry_buf,
> ```

Suggest to rename to `generate_serialized_pk_hash_entry()` as this only works for `pk`.



_Code quote:_
```C
generate_serialized_hash_entry
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 282 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrPl7b-QPAAqe8yXBe:-NOrPl7c2-nPiQe3EjdP:bmiuy5e) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L282)):*
> ```C
> static int generate_serialized_claims(mbedtls_pk_context* pk, uint8_t** out_claims_buf,
>                                       size_t* out_claims_buf_size) {
>     cbor_item_t* cbor_claims = cbor_new_definite_map(1);
> ```

Looks like we do not support per-session nonce at this moment. But we do cite it in the format description comment below.

Should we just not mention it at all (until we extend the support) or we add a TODO w/ it?

Similar question for the endorsement extention.



_Code quote:_
```C
cbor_new_definite_map(1)
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 327 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrJZLU6Z8m-ARpZtYV:-NOrJZLU6Z8m-ARpZtYW:bniwev6) ([raw file](https://github.com/gramineproject/gramine/blob/d321063 [...]

2023-02-22 12:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 18 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dJEw51zbacAe1eYW:-NOsltLe7vqipAgiisTd:bcsi057) (no related file):*
> However, to finalize the PR, we need [...] registered CBOR tags. This is work in progress.

CBOR tags were registered, see here: https://github.com/CCC-Attestation/interoperable-ra-tls/blob/main/docs/Interoperable-RA-TLS-SGX-TDX-evidence-formats.md#sgx--tdx-evidence-cbor-tags-registration

This PR is updated with these new tags (in a fixup commit).

___
___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrS-pQ7ojhS1kB-jUg):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

SGX/TDX
</blockquote></details>

I don't want to mention TDX in this context. This will only confuse people. I'd like to concentrate on SGX.
___
*[`-- commits` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOt7J6f66wTZFnQ5rIx):*
I must change from `hash-entry` to `pubkey-hash` during final rebase
___
*[`Documentation/attestation.rst` line 251 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkH8j2SWGpLiRTqZz:-NOsuRY2-oQM4Ad2lKgB:bvla7j2) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L251)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Same question (see below) for the `pubkey` of claims in the diagram.
</blockquote></details>

Done. Thanks. This was on old spec.
___
*[`Documentation/attestation.rst` line 267 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOriNrABIbn413oZefr:-NOsuU407wZyIf3oDkLM:bvla7j2) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L267)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Isn't it just `""pubkey-hash""` rather than the key itself?
</blockquote></details>

Done. Thanks. This was on old spec.
___
*[`Documentation/attestation.rst` line 273 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrk3-v4rqZ7fqrmJVQ:-NOsuukWC588OqrERcxo:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L273)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

Done
___
*[`Documentation/attestation.rst` line 282 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkn7WCPXuSzRqNiFK:-NOsmLID8QdLrSnxAVT1:bh0h4rm) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L282)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

will be?
</blockquote></details>

But as soon as this PR is merged, the previous format **becomes deprecated**. So I think the current wording is correct.
___
*[`Documentation/attestation.rst` line 283 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrkzPI2g7C1UiCkC99:-NOsmThkDYe4XsqmMDXU:b-4f0isy) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L283)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's not accurate. The OID is just an identifier.
</blockquote></details>

True, but could you propose a better wording here? Maybe `...OID object directly embeds ...`?
___
*[`Documentation/attestation.rst` line 286 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrlC7y60uB2pINrLYu:-NOsv7VF8a7VM_cFvYcw:b-ttuvh5) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/Documentation/attestation.rst#L286)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

How should I rephrase? The text looks reasonable to me as is.
___
*[`subprojects/packagefiles/libcbor/meson.build` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH-nxw78TTL83gD8dXJ:-NOsme1xDDEEjQqCnT2C:b8qtg9n) ([raw file](https://github.com/gramineproject/gramine/blob/349438f777706752226719be526067da779a02c9/subprojects/packagefiles/libcbor/meson.build#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We eventually droped the hack in the merged version of https://github.com/gramineproject/gramine/pull/773. Does the solution applies to this PR as well?
</blockquote></details>

The solution from your dropped commit applies well here, whereas the actual merged solution doesn't apply. That's because RA-TLS sources are part of Gramine codebase itself, and not a subproject (like it was in your case of Curl + mbedTLS).
___
*[`tools/sgx/ra-tls/ra_tls.h` line 55 at r5](https://reviewable.io/reviews/gramineproject/gramine/1039#-NLfCoJEEtTc5S1xPUrv:-NOsoeln-q6S6AnXAQTx:b-nscngw) ([raw file](https://github.com/gramineproject/gramine/blob/af400b39b0872c971bb14364294397360ea856b4/tools/sgx/ra-tls/ra_tls.h#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Exact list of supported hash funcs is under discussion, see https://github.com/CCC-Attestation/interoperable-ra-tls/issues/6
</blockquote></details>

Done, this was already added in the spec: https://github.com/CCC-Attestation/interoperable-ra-tls/pull/7/files
___
*[`tools/sgx/ra-tls/ra_tls.h` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrltDO-Zgi2Upaa-nN:-NOsw4JK2nlIjyzdb1Cc:b25xwdd) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls.h#L46)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Where is this "raw" OID used?
</blockquote></details>

See my other comment.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 52 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOt5hyTAdYtSFGA416a:-NOt5hyTAdYtSFGA416b:b-kr823a) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls.h#L52)):*
> ```objc
> static const size_t g_evidence_oid_raw_size = sizeof(g_evidence_oid_raw);
> 
> #define TCG_DICE_TAGGED_EVIDENCE_CBOR_TAG 0x1A7501 /* FIXME: proper IANA tag once registered */
> ```

FYI: Renamed from `TCG_DICE_TAGGED_EVIDENCE_CBOR_TAG` to `TCG_DICE_TAGGED_EVIDENCE_TEE_QUOTE_CBOR_TAG`, now that this is registered with IANA.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 223 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrMlmB-c6G3Mj53diC:-NOsw_8E0_vmnqcK_IGW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L223)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to rename to `generate_serialized_pk_hash_entry()` as this only works for `pk`.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 282 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrPl7b-QPAAqe8yXBe:-NOswqJi3ogGSSPN1_TU:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L282)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Looks  [...]

2023-02-22 12:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 18 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 259 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrhCk0BLC9ItDrsNnM:-NOt9QHT7CX8_xxueFES:bfgcea3) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_verify_common.c#L259)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just wanted to assume something for ID=0. How do you think we should proceed?

Ok, I asked the question here: https://github.com/CCC-Attestation/interoperable-ra-tls/issues/6. Let's see what the result will be.
</blockquote></details>

Done, I removed the "RESERVED implies SHA256" logic. Now Gramine's RA-TLS fails on finding RESERVED hash alg id.


<!-- Sent from Reviewable.io -->

2023-02-27 07:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 18 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NPGrotb8N6jXvVfj6E2:-NPGrotc74Hhi0UEx2S9:b8il6t0) (no related file):*
TODO(myself): Experiment with `mbedtls_x509_crt_parse_der_with_ext_cb()` and will report on my results here.

See:
- https://github.com/Mbed-TLS/mbedtls/blob/a3b625b0a1139fe0b81c4b0a0b644473c94c5646/include/mbedtls/x509_crt.h#L441
- https://github.com/Mbed-TLS/mbedtls/blob/a3b625b0a1139fe0b81c4b0a0b644473c94c5646/include/mbedtls/x509_crt.h#L394

This can be done separately from Interoperable RA-TLS, in a new PR (enhancement to RA-TLS).

___


<!-- Sent from Reviewable.io -->

2023-02-27 12:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 18 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NPGrotb8N6jXvVfj6E2:-NPHpBVLA-K-UqnNqg_L:b-e7isbm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Experiment with `mbedtls_x509_crt_parse_der_with_ext_cb()` and will report on my results here.

See:
- https://github.com/Mbed-TLS/mbedtls/blob/a3b625b0a1139fe0b81c4b0a0b644473c94c5646/include/mbedtls/x509_crt.h#L441
- https://github.com/Mbed-TLS/mbedtls/blob/a3b625b0a1139fe0b81c4b0a0b644473c94c5646/include/mbedtls/x509_crt.h#L394

This can be done separately from Interoperable RA-TLS, in a new PR (enhancement to RA-TLS).
</blockquote></details>

Done. This callback doesn't help us. See my freshly opened issue for details: https://github.com/Mbed-TLS/mbedtls/issues/7182

___


<!-- Sent from Reviewable.io -->

2023-08-30 04:52 UTC, dimakuv commented
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 279 at r7](https://reviewable.io/reviews/gramineproject/gramine/1039#-Nd3licc6hE_5UzyaE1A:-Nd3licc6hE_5UzyaE1B:bu6fnr1) ([raw file](https://github.com/gramineproject/gramine/blob/f8d03e070b96e5530035bfa9ed055efe412e5ac9/tools/sgx/ra-tls/ra_tls_verify_common.c#L279)):*
> ```C
> 
>     switch (hash_alg_id) {
>         case IANA_NAMED_INFO_HASH_ALG_REGISTRY_RESERVED:
> ```

Oops, forgot this place (see https://github.com/CCC-Attestation/interoperable-ra-tls/issues/6). I must remove this line.


<!-- Sent from Reviewable.io -->

2023-08-30 05:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 20 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOt7J6f66wTZFnQ5rIx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I must change from `hash-entry` to `pubkey-hash` during final rebase
</blockquote></details>

Done
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 279 at r7](https://reviewable.io/reviews/gramineproject/gramine/1039#-Nd3licc6hE_5UzyaE1A:-Nd3nUGX1hqB-HL7r7Qe:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f8d03e070b96e5530035bfa9ed055efe412e5ac9/tools/sgx/ra-tls/ra_tls_verify_common.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, forgot this place (see https://github.com/CCC-Attestation/interoperable-ra-tls/issues/6). I must remove this line.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-30 06:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 23 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dJEw51zbacAe1eYW:-Nd4CVut1f_Hqw5_rkRv:b-xndz96) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> However, to finalize the PR, we need [...] registered CBOR tags. This is work in progress.

CBOR tags were registered, see here: https://github.com/CCC-Attestation/interoperable-ra-tls/blob/main/docs/Interoperable-RA-TLS-SGX-TDX-evidence-formats.md#sgx--tdx-evidence-cbor-tags-registration

This PR is updated with these new tags (in a fixup commit).
</blockquote></details>

I rebased this PR and tested it, it's ready for review.

___


<!-- Sent from Reviewable.io -->

2023-08-30 15:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 0 of 23 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`subprojects/packagefiles/libcbor/compile.sh` line 30 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-Nd65MEV9UIOd70ZGEsL:-Nd65MEV9UIOd70ZGEsM:b-yuo2nq) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/subprojects/packagefiles/libcbor/compile.sh#L30)):*
> ```Shell
>         -DCMAKE_BUILD_TYPE=Release \
>         -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
>         -DCMAKE_INSTALL_LIBDIR=lib \
> ```

FYI: CMake by default installs the required `libcbor.a` library under the OS-distro-specific path (`lib/` for Debian/Ubuntu/Alpine and `lib64/` for RHEL/CentOS/Alma).

This default behavior contradicts our `cp -ar "$CURRENT_BUILD_DIR"/lib/. "$CURRENT_BUILD_DIR"` (see below line).

So we force CMake to install `libcbor.a` always under `lib/`. Since this is a throw-away local directory, it's fine to do that.

Refs:
- https://stackoverflow.com/questions/49626164/make-install-installs-libraries-in-usr-lib-instead-of-usr-lib64
- https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html


<!-- Sent from Reviewable.io -->

2023-08-30 16:28 UTC, dimakuv commented
Jenkins, retest pkg-deb-debian12 please (was put on a bad Jenkins node, with wrong seccomp profile)

2023-09-26 04:33 UTC, kailun-qin requested changes
> Reviewed 1 of 7 files at r4, 3 of 9 files at r7, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 256 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEX7v8Da1kB2VmxW6t:-NfEX7v9EhFGcyGMNRfz:b53mft6) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L256)):*
> ```reStructuredText
> evidence" OID), which in turn embeds the SGX report and the complete Intel SGX
> certificate chain. In addition to the SGX quote, the certificate also contains
> the so-called evidence claims, with the most important one being the
> ```

I think we can remove this "so-called" (as "so-called" has a connotation that of skepticism - from Don in several other doc reviews).



_Code quote:_
```reStructuredText
so-called
```
___
*[`Documentation/attestation.rst` line 272 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEZ97TEWeza3evzV7i:-NfEZ97TEWeza3evzV7j:b-457tmk) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L272)):*
> ```reStructuredText
> 
> The diagram above shows the non-standard X.509 certificate generated by RA-TLS.
> This format, with a non-standard X.509 extension field (and a dummy OID), was
> ```

-> "legacy non-standard" (which is more correct and aligns w/ the other parts of code/docs)?



_Code quote:_
```reStructuredText
dummy
```
___
*[`Documentation/attestation.rst` line 274 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEYoP31sBwLVhjl86F:-NfEYoP31sBwLVhjl86G:b-y70jh3) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L274)):*
> ```reStructuredText
> This format, with a non-standard X.509 extension field (and a dummy OID), was
> developed prior to the "Interoperable RA-TLS" specification, and is deprecated.
> One can see that the non-standard OID object directly embeds the SGX quote,
> ```

But no OID object is reflected in the old `ratls.svg`.



_Code quote:_
```reStructuredText
One can see that the non-standard OID object directly embeds the SGX quote,
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 327 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrJZLU6Z8m-ARpZtYV:-NfEbWZc-BIXAy484uSf:b-ynoon9) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L327)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, there are issues with `goto cleanup` style... CBOR library (`libcbor`) has a complicated system of object ownership. Keeping track of what CBOR function incremented which object is complicated to implement in the `goto` style (I tried first).
</blockquote></details>

OK I see, thanks for the explanations!
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 426 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrPZ5g2PZl5xO-kE0G:-NfE__5h7Bw1avdsiUik:b-eslfxk) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_attest.c#L426)):*
> Is there anything I should do/change?

Nope, I'm fine w/ it.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 241 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrdCBeEivONZeznCWp:-NfEiVby1DZiwW8w6O-M:ba6dqm8) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_verify_common.c#L241)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have a check `if (cbor_bytestring_length(cbor_hash_value) != sha_size)` below already. Isn't it enough? What would the additional check bring?
</blockquote></details>

Ah I missed it , sorry.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 514 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrWzq_AAwVW-4rQxsY:-NfEh6nU9Uc9NpL2y1Ts:bnf2wtq) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_verify_common.c#L514)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, we don't need to verify the legacy quote. This is what the current code does already... Note the `if (!ret) return 0` line above -- this is exactly this.
</blockquote></details>

OK, then if we failed w/ `extract_standard_quote_and_verify_claims()` (which can be `MBEDTLS_ERR_X509_SIG_MISMATCH`) - we'll still continue to try w/ the legacy one? What if they have discrepancy in verification results?


<!-- Sent from Reviewable.io -->

2024-01-02 13:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 15 of 23 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dJEw51zbacAe1eYW:-Nn9Me-V8lESLL1x-_l9:buvxks2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I rebased this PR and tested it, it's ready for review.
</blockquote></details>

FYI: I rebased this PR again against latest Gramine (v1.6), it's ready for review.

Note that libcbor is still v0.10.2 -- the latest as of January 2024.

___
___
*[`Documentation/attestation.rst` line 256 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEX7v8Da1kB2VmxW6t:-Nn9Dzbp4YDQtiX6CiwH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L256)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think we can remove this "so-called" (as "so-called" has a connotation that of skepticism - from Don in several other doc reviews).
</blockquote></details>

Done.
___
*[`Documentation/attestation.rst` line 272 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEZ97TEWeza3evzV7i:-Nn9EAK45dx3SFB75wLg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L272)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> "legacy non-standard" (which is more correct and aligns w/ the other parts of code/docs)?
</blockquote></details>

Done.
___
*[`Documentation/attestation.rst` line 274 at r8](https://reviewable.io/reviews/gramineproject/gramine/1039#-NfEYoP31sBwLVhjl86F:-Nn9EAer9bj0Wj80FUD2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/845e948b230cfb125de8828dc5883b0f434d9789/Documentation/attestation.rst#L274)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But no OID object is reflected in the old `ratls.svg`.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 514 at r6](https://reviewable.io/reviews/gramineproject/gramine/1039#-NOrWzq_AAwVW-4rQxsY:-Nn9HOrl-OBcCksxvmfg:byphd7c) ([raw file](https://github.com/gramineproject/gramine/blob/d3210636e356d7ba1a4f3baf3ad1d0225488d23e/tools/sgx/ra-tls/ra_tls_verify_common.c#L514)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

OK, then if we failed w/ `extract_standard_quote_and_verify_claims()` (which can be `MBEDTLS_ERR_X509_SIG_MISMATCH`) - we'll still continue to try w/ the legacy one? What if they have discrepancy in verification results?
</blockquote></details>

Done. I see your point now.


<!-- Sent from Reviewable.io -->

2024-01-03 01:16 UTC, kailun-qin approved these changes
> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-06-18 23:00 UTC, mkow requested changes
> Reviewed 1 of 7 files at r4, 1 of 9 files at r7, 5 of 19 files at r8, 7 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 11 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`meson.build` line 265 at r2](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH06rxq4bWuqwyNMcjN:-O-hORdaDODPoIwoctKb:b23kger) ([raw file](https://github.com/gramineproject/gramine/blob/ade87eef01916b235993b157263f7304baab8bee/meson.build#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I cannot use https://mesonbuild.com/CMake-module.html# because of this bug: https://github.com/mesonbuild/meson/issues/10764
</blockquote></details>

Could you put this into a comment?
___
*[`.ci/ubuntu20.04.dockerfile` line 1 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-NzsiyF784UyHEsSroD9:-NzsiyF784UyHEsSroDA:b-8e6e2e) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/.ci/ubuntu20.04.dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:20.04
> ```

This will need to be synced with #1843.
___
*[`Documentation/attestation.rst` line 253 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hOzJC3wxTlvWWVi3N:-O-hOzJC3wxTlvWWVi3O:b-xdigen) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/Documentation/attestation.rst#L253)):*
> ```reStructuredText
> the actual chain of trust is stored in the Intel SGX certificates embedded in
> the SGX quote.
> ```

Could you explain somewhere (maybe in the SGX-intro.rst? or glossary?) all these terms used here? Evidence, claims, TCG DICE, endorsement, etc. They are used everywhere (here and in the linked materials), but I couldn't find any precise explanation of what they are.
___
*[`Documentation/attestation.rst` line 276 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hRDIyELNcnM3dkF1c:-O-hRDIyELNcnM3dkF1d:b-7ilvfu) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/Documentation/attestation.rst#L276)):*
> ```reStructuredText
> This format, with a non-standard X.509 extension field (and a legacy
> non-standard OID), was developed prior to the "Interoperable RA-TLS"
> specification, and is deprecated. One can see that the this old X.509
> ```

typo?



_Code quote:_
```reStructuredText
One can see that the this
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 281 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hVI5_7EcsHOaqF8Fm:-O-hVI5a9wn_u-YkKv_w:b-5dsqcy) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_attest.c#L281)):*
> ```C
> static int generate_serialized_claims(mbedtls_pk_context* pk, uint8_t** out_claims_buf,
>                                       size_t* out_claims_buf_size) {
>     /* TODO: currently implement only claim "pubkey-hash", but there may be more (e.g. "nonce") */
> ```

weird English tense (or a typo?), plz reword



_Code quote:_
```C
currently implement only
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 504 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hXNsD4IXY4p6yAKZj:-O-hXNsD4IXY4p6yAKZk:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_attest.c#L504)):*
> ```C
>         goto out;
> 
>     /* TODO: currently don't implement the Endorsement extension (contains TCB info, CRL, etc.) */
> ```

ditto
___
*[`tools/sgx/ra-tls/ra_tls_common.h` line 41 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hYBvF3kkZkV_kX83O:-O-hYBvF3kkZkV_kX83P:b-t7esmh) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_common.h#L41)):*
> ```objc
> static const size_t g_evidence_oid_size = sizeof(g_evidence_oid);
> static const uint8_t g_evidence_oid_raw[] = TCG_DICE_TAGGED_EVIDENCE_OID_RAW;
> static const size_t g_evidence_oid_raw_size = sizeof(g_evidence_oid_raw);
> ```

What's the point of declaring this? Why not just `sizeof()` at the site where this is used?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 526 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hZZiOEsrkdwSaHU1o:-O-hZZiOEsrkdwSaHU1p:b-26op87) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_verify_common.c#L526)):*
> ```C
>     bool found_oid = false;
>     int ret = extract_standard_quote_and_verify_claims(crt, &found_oid, out_quote, out_quote_size);
>     if (!ret)
> ```

just to not look like checking a result of a function returning the status in `bool`



_Suggestion:_
```C
if (ret == 0)
```


<!-- Sent from Reviewable.io -->

2024-06-24 13:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 16 of 25 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O08lZwM7oM5iw7cl7Aq:-O08lZwM7oM5iw7cl7Ar:b-yc523a) (no related file):*
- I'll need to rebase this PR to latest Gramine
- I'll need to update libcbor to latest version (v0.11 as of this writing)

___
___
*[`meson.build` line 265 at r2](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH06rxq4bWuqwyNMcjN:-O08mP5I1tigNHMWKFJ-:biloh7x) ([raw file](https://github.com/gramineproject/gramine/blob/ade87eef01916b235993b157263f7304baab8bee/meson.build#L265)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you put this into a comment?
</blockquote></details>

Done. I already have this comment elsewhere, but I also added it here.
___
*[`.ci/ubuntu20.04.dockerfile` line 1 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-NzsiyF784UyHEsSroD9:-O08luOD4zH8ImSTMlap:befa0lh) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/.ci/ubuntu20.04.dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will need to be synced with #1843.
</blockquote></details>

Yep, during next rebase
___
*[`Documentation/attestation.rst` line 253 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hOzJC3wxTlvWWVi3N:-O09L7IOEkK697nVbKBx:b4vracl) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/Documentation/attestation.rst#L253)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain somewhere (maybe in the SGX-intro.rst? or glossary?) all these terms used here? Evidence, claims, TCG DICE, endorsement, etc. They are used everywhere (here and in the linked materials), but I couldn't find any precise explanation of what they are.
</blockquote></details>

Done. Took some time...
___
*[`Documentation/attestation.rst` line 276 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hRDIyELNcnM3dkF1c:-O08nVXD4NTioqB8t98e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/Documentation/attestation.rst#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 281 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hVI5_7EcsHOaqF8Fm:-O08npF86YcR-kuSdoBP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_attest.c#L281)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

weird English tense (or a typo?), plz reword
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 504 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hXNsD4IXY4p6yAKZj:-O08o-MA4W2aS0maX_nk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_attest.c#L504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_common.h` line 41 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hYBvF3kkZkV_kX83O:-O08oVFa7QZ00ZzRbz9n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_common.h#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of declaring this? Why not just `sizeof()` at the site where this is used?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 526 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-O-hZZiOEsrkdwSaHU1o:-O08oaU-DiykRJ_IDa6P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/tools/sgx/ra-tls/ra_tls_verify_common.c#L526)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

just to not look like checking a result of a function returning the status in `bool`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-27 00:21 UTC, mkow requested changes
> Reviewed 1 of 19 files at r8, 3 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 19 of 25 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O08lZwM7oM5iw7cl7Aq:-O0Lp4Za9Jp_-lZYft8R:b-gvpo6e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- I'll need to rebase this PR to latest Gramine
- I'll need to update libcbor to latest version (v0.11 as of this writing)
</blockquote></details>

Could you do it now? (or maybe after the doc PR? see my comments below)

___
___
*[`.ci/ubuntu20.04.dockerfile` line 1 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-NzsiyF784UyHEsSroD9:-O0LpEDV9XZn0D561uDp:b-sn2w8e) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/.ci/ubuntu20.04.dockerfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, during next rebase
</blockquote></details>

Let's do the rebase now then :)
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 190 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M1rHICowvqoMoGrci:-O0M1rHICowvqoMoGrcj:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/CI-Examples/ra-tls-mbedtls/src/server.c#L190)):*
> ```C
>             /* user asks to maliciously modify the embedded SGX quote (for testing purposes); we
>              * have two quotes currently (with legacy OID and with standard TCG DICE OID), so we
>              * modify them both */
> ```





_Suggestion:_
```C
modify both of them
```
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 196 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M2RFS6IenwsTecOJJ:-O0M2RFS6IenwsTecOJK:bovyct0) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/CI-Examples/ra-tls-mbedtls/src/server.c#L196)):*
> ```C
>             uint8_t legacy_oid[] = {0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF8, 0x4D, 0x8A, 0x39,
>                                     0x06};
>             uint8_t standard_oid[] = { 0x06, 0x06, 0x67, 0x81, 0x05, 0x05, 0x04, 0x09 };
> ```

Could you move the OID definitions to `ra_tls.h`? This way you could use them here.
___
*[`Documentation/sgx-intro.rst` line 246 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-6Rz0VcjUrTilr0_:-O0M-6Rz0VcjUrTilr0a:bysbxtj) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L246)):*
> ```reStructuredText
> 
>          :term:`Remote Attestation`
> ```

What about _claims_? (but we probably should say `Claims (attestation)`, it's a very generic term.
___
*[`Documentation/sgx-intro.rst` line 269 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-hcB1SpMFCFVs2Sk:-O0M-hcB1SpMFCFVs2Sl:b-md4ary) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L269)):*
> ```reStructuredText
>       generates the evidence (SGX quote plus additional claims) and sends it to
>       the verifier (e.g., :term:`IAS`).
> ```

Now that I'm reading it, it's quite a lot, maybe you could make a separate PR out of it which we'd quickly review and merge separately?
It would make the review easier for me.


<!-- Sent from Reviewable.io -->

2024-06-27 09:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 7 of 27 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH4dJEw51zbacAe1eYW:-O0NwIQe-39tFmvazwzI:bh8qlom) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I rebased this PR again against latest Gramine (v1.6), it's ready for review.

Note that libcbor is still v0.10.2 -- the latest as of January 2024.
</blockquote></details>

FYI: Rebased against latest Gramine (v1.7), ready for review.

libcbor is now v0.11.0

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O08lZwM7oM5iw7cl7Aq:-O0NwGNxArkBqZ8F6rZn:bb6un1j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you do it now? (or maybe after the doc PR? see my comments below)
</blockquote></details>

Done

___
___
*[`.ci/ubuntu20.04.dockerfile` line 1 at r9](https://reviewable.io/reviews/gramineproject/gramine/1039#-NzsiyF784UyHEsSroD9:-O0NsOan6F6ZXggbD2sE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9f4863cabfa948a06ab80767cc40f8a5b7d36fd3/.ci/ubuntu20.04.dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's do the rebase now then :)
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 190 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M1rHICowvqoMoGrci:-O0NsaJsBugk8UB1pg4i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/CI-Examples/ra-tls-mbedtls/src/server.c#L190)):*
> ```C
>             /* user asks to maliciously modify the embedded SGX quote (for testing purposes); we
>              * have two quotes currently (with legacy OID and with standard TCG DICE OID), so we
>              * modify them both */
> ```

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 196 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M2RFS6IenwsTecOJJ:-O0Ntj5e6d7Xs5ulOFoj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/CI-Examples/ra-tls-mbedtls/src/server.c#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you move the OID definitions to `ra_tls.h`? This way you could use them here.
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 246 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-6Rz0VcjUrTilr0_:-O0NpGV9BmGTN8HEvSKb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L246)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about _claims_? (but we probably should say `Claims (attestation)`, it's a very generic term.
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 269 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-hcB1SpMFCFVs2Sk:-O0NpHIV28WMUpadRN4X:b-8j6rdb) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L269)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now that I'm reading it, it's quite a lot, maybe you could make a separate PR out of it which we'd quickly review and merge separately?
It would make the review easier for me.
</blockquote></details>

Done. See #1927 

Blocking myself on this prerequisite (this PR will need to be rebased on top of 1927).


<!-- Sent from Reviewable.io -->

2024-07-24 07:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 25 of 27 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2Q27wo01k0Sugb7W4D:-O2YaFGq2U1uQaCMOsmU:b-avwidv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No version number in the directory name? (`packagefiles/libcbor/`)
</blockquote></details>

I can add it. I didn't add the version because about half of our dependencies don't have the version number: https://github.com/gramineproject/gramine/tree/master/subprojects/packagefiles. Not sure what our policy in the directory names is.

___
___
*[`.ci/ubuntu22.04.dockerfile` line 58 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2Mizmr9bpH3zxtDzER:-O2Ya7vc2uSfz3d-myUS:bp4d0z1) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/.ci/ubuntu22.04.dockerfile#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this list of added libs so different than for 24.04?
</blockquote></details>

Looks like a merge fail that I didn't notice. I'll fix during rebase (once dependency PRs are merged)
___
*[`Documentation/sgx-intro.rst` line 269 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-hcB1SpMFCFVs2Sk:-O2Ya3_H6JZm76RnureC:b66tfqo) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. See #1927 

Blocking myself on this prerequisite (this PR will need to be rebased on top of 1927).
</blockquote></details>

Also blocking on https://github.com/gramineproject/gramine/pull/1947
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 102 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2UaXxL0-Xy2Lz-mTAD:-O2Y_XLS21lqt1WHe8pV:b-q4vcz2) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's an unrelated fix, right? Could you extract it to another PR, so we can quickly merge it?
</blockquote></details>

Done, see https://github.com/gramineproject/gramine/pull/1947
___
*[`tools/sgx/ra-tls/ra_tls_verify_epid.c` line 124 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2QMvw5D5YMfpUBekyQ:-O2Y_Yus0xsubl-fchyP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_verify_epid.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 07:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 22 of 27 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2ciPPu81PWysjJgb81:-O2ciPPu81PWysjJgb82:b3v9m9k) (no related file):*
FYI: Rebased to the latest master, at the request of @mkow, to incorporate the following prerequisite PRs:
- https://github.com/gramineproject/gramine/pull/1947
- https://github.com/gramineproject/gramine/pull/1927

___
___
*[`.ci/ubuntu22.04.dockerfile` line 58 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2Mizmr9bpH3zxtDzER:-O2cic3uAXHjg_Rn3iZf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/.ci/ubuntu22.04.dockerfile#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like a merge fail that I didn't notice. I'll fix during rebase (once dependency PRs are merged)
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 269 at r10](https://reviewable.io/reviews/gramineproject/gramine/1039#-O0M-hcB1SpMFCFVs2Sk:-O2cik6P7wy_h5F9j3LT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aa1ab3974132982b93de8d200f67945179ba4cc0/Documentation/sgx-intro.rst#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also blocking on https://github.com/gramineproject/gramine/pull/1947
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 10:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 17 of 27 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2Q27wo01k0Sugb7W4D:-O2dCVfp3lEl_iOhpbtS:b-cg3hay) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can add it. I didn't add the version because about half of our dependencies don't have the version number: https://github.com/gramineproject/gramine/tree/master/subprojects/packagefiles. Not sure what our policy in the directory names is.
</blockquote></details>

Done, now with version number

___
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 140 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2QKhR38dMi4edt6xLx:-O2dGA6K9XbnTdKEVFzq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_attest.c#L140)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you specify Gramine versions here then please specify them fully, i.e. also in TCG DICE.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 140 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2QKpYy1xpPkOhOYOIK:-O2dGDdU2su35X8-Prpf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_attest.c#L140)):*
> ```C
> 
>     /* embed the SGX quote into the generated certificate (as X.509 extension) in two formats:
>      *   - legacy non-standard "SGX quote" OID (used from Gramine v1.0)
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_common.h` line 27 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2QMO2J03FJtfr-TEKw:-O2dGhH23H3hv0UmXFFE:b-r4yjqj) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_common.h#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not including `ra_tls.h` instead of duplicating the constants?
</blockquote></details>

Done, yeah, agreed. Users of this header file will anyhow want to use `ra_tls.h` too.
___
*[`tools/sgx/ra-tls/ra_tls_common.h` line 31 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2QMaUw8JTEU5i0R9Uv:-O2dHhwG1x7HWFiVlzMm:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_common.h#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you prefix these with `g_ratls_` instead? I think this way is better, as they are in the global namespace.
</blockquote></details>

Done
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 102 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2UaXxL0-Xy2Lz-mTAD:-O2dIPe5C2uM-qTNsI9c:bwkd4hj) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, see https://github.com/gramineproject/gramine/pull/1947
</blockquote></details>

Also note that I already rebased this PR on top of #1947.
___
*[`subprojects/packagefiles/libcbor/compile.sh` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2Psegs8lQ9hF1y0ncZ:-O2dD1PS0i_SjJtBjB9q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/packagefiles/libcbor/compile.sh#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "current"? Are there any other source directories? Ditto for build dir.
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/libcbor/compile.sh` line 11 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2PsMqXB5mg1C_EM39C:-O2dFcxd2thGFoPSjON4:b-ttbc6n) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/packagefiles/libcbor/compile.sh#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please verify that the arguments were actually passed (and print usage info if not).
</blockquote></details>

Done.

Btw, this script is *not* supposed to be used by users. It's only supposed to be called by Meson.
___
*[`subprojects/packagefiles/libcbor/meson.build` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1039#-NH-npxwBugzNWmVMwv4:-O2dFpbM8giZShTSEGZZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/349438f777706752226719be526067da779a02c9/subprojects/packagefiles/libcbor/meson.build#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you link to it in the comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-28 01:30 UTC, mkow requested changes
> Reviewed 3 of 5 files at r12, 6 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 26 of 27 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qgM1n6IYnxnOcjxTZ:-O2qgM1n6IYnxnOcjxT_:bdnv9ku) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L231)):*
> ```C
>         return MBEDTLS_ERR_X509_ALLOC_FAILED;
> 
>     /* RA-TLS always generates SHA256 hash over pubkey */
> ```

Is this what you mean? Or something else? The current comment sounds weird to me.



_Suggestion:_
```C
/* RA-TLS always uses SHA256 */
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 280 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qjIKiECdcmj9gcMrN:-O2qjIKiECdcmj9gcMrO:b-kify2p) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L280)):*
> ```C
> }
> 
> /*! generate claims -- CBOR map with { "pubkey-hash" = <serialized CBOR array hash-entry> } */
> ```

What a weird format, why does this CBOR map contain a byte string with _serialized_ CBOR array, instead of a normal CBOR array?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 328 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qlvqw7pyk76THsv9w:-O2qlvqw7pyk76THsv9x:b66roz4) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L328)):*
> ```C
>     cbor_serialize_alloc(cbor_claims, &claims_buf, &claims_buf_size);
> 
>     cbor_decref(&cbor_pubkey_hash_val);
> ```

Please add a similar comment about references as in `generate_serialized_pk_hash_entry()`.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 340 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qmrQ27WQPTomc9cBh:-O2qmrQ27WQPTomc9cBi:bbw1kw5) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L340)):*
> ```C
> }
> 
> /*! generate evidence -- CBOR tag with CBOR array of CBOR bstrs: [ quote, claims ] */
> ```

whyyyy
This is `map("asdf": serialize(map("qwer": serialize("asdf"))` at this point... Is there any reason for such a weird format with nested serialization?



_Code quote:_
```C
CBOR array of CBOR bstrs
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 404 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qtUe313kUtLmFNFtN:-O2qtUe313kUtLmFNFtO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L404)):*
> ```C
> }
> 
> /*! generate SGX-quote evidence with \p pk as one of the embedded claims (standard format) */
> ```





_Suggestion:_
```C
SGX-quote evidence (a set of claims)
```
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 405 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qtbTf8eIh4lyA_bz1:-O2qtbTf8eIh4lyA_bz2:bniedc7) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L405)):*
> ```C
> 
> /*! generate SGX-quote evidence with \p pk as one of the embedded claims (standard format) */
> static int generate_evidence_with_claims(mbedtls_pk_context* pk, uint8_t** out_evidence,
> ```

Using TCG DICE meanings, "evidence with claims" is like saying "numbers with digits" ;P

Both this and the previous function have IMO very confusing names. Both return serialized evidence, but only `generate_serialized_evidence()` has that in its name. Both generate evidence with claims (obviously), but only `generate_evidence_with_claims()` has that in its name.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 489 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qwgjZEy0MpQWH92-m:-O2qwgjZEy0MpQWH92-n:blkp57w) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L489)):*
> ```C
>     int ret;
> 
>     /*
> ```

Weird comment formatting (empty first line, but not the last.
___
*[`subprojects/packagefiles/libcbor/compile.sh` line 11 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2PsMqXB5mg1C_EM39C:-O2qOpYg3s05W4mPGM15:b-63oi0y) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/packagefiles/libcbor/compile.sh#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Btw, this script is *not* supposed to be used by users. It's only supposed to be called by Meson.
</blockquote></details>

Yeah, but it could have been annoying to us when debugging / doing stuff manually.


<!-- Sent from Reviewable.io -->

2024-07-28 01:33 UTC, mkow commented
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, now with version number
</blockquote></details>

AFAIR Meson breaks if you don't do this (it doesn't track changes in subprojects, so it wouldn't recompile it after you e.g. checked out a branch with a different subproject version). They say it works as intended, as usual ¯\\\_(ツ)\_/¯




<!-- Sent from Reviewable.io -->

2024-07-28 23:58 UTC, mkow requested changes
> Reviewed 1 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 193 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vLy5_-hWHDSiM41yG:-O2vLy5_-hWHDSiM41yH:bchmtt6) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L193)):*
> ```C
> 
> /*! fill buffer \p pk_der with DER-formatted public key from \p crt */
> static int fill_crt_pk_der(mbedtls_x509_crt* crt, uint8_t* pk_der, size_t* pk_der_size) {
> ```

It's a bit confusing without it IMO.



_Suggestion:_
```C
size_t* inout_pk_der_size
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vSTiPE90YkfBTIze_:-O2vSTiPE90YkfBTIzea:b-qt4dk0) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L194)):*
> ```C
> /*! fill buffer \p pk_der with DER-formatted public key from \p crt */
> static int fill_crt_pk_der(mbedtls_x509_crt* crt, uint8_t* pk_der, size_t* pk_der_size) {
>     mbedtls_ecp_keypair* key = mbedtls_pk_ec(crt->pk);
> ```

FYI: `mbedtls_pk_ec()` may disappear in the future (see https://github.com/Mbed-TLS/mbedtls/issues/7572).
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vURwQ3w9d4BimnSoU:-O2vURwQ3w9d4BimnSoV:bq6d8ut) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L194)):*
I don't think it's legal to call `mbedtls_pk_ec()` just like that.

> Warning: You must make sure the PK context actually holds an EC context before using this function!

See https://arm-software.github.io/CMSIS-mbedTLS/latest/pk_8h.html#a4b9c1b47e90acc7c01800edbfb8cff56.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 197 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vUlBLAEi_MDjGHndP:-O2vUlBLAEi_MDjGHndQ:bcjgzhf) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L197)):*
> ```C
>     if (key == NULL ||
>             (key->MBEDTLS_PRIVATE(grp).id != MBEDTLS_ECP_DP_SECP384R1
>                 && key->MBEDTLS_PRIVATE(grp).id != MBEDTLS_ECP_DP_SECP256R1)) {
> ```

Is there any way to get this information without using mbedtls private APIs?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 342 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vdRCF9GWjxD-oQepj:-O2vdRCF9GWjxD-oQepk:bd77rli) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L342)):*
> ```C
>                                           &evidence_buf_size);
>     if (ret < 0)
>         return ret;
> ```

You leave `*out_found_oid` uninitialized here.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 376 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vgg7X0pt39pD4F_xv:-O2vgg7X0pt39pD4F_xw:b-sskq3j) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L376)):*
> ```C
>     cbor_quote = cbor_array_get(cbor_evidence, /*index=*/0);
>     if (!cbor_quote || !cbor_isa_bytestring(cbor_quote) || !cbor_bytestring_is_definite(cbor_quote)
>             || cbor_bytestring_length(cbor_quote) == 0) {
> ```

You already check this more precisely in the next `if`.



_Code quote:_
```C
cbor_bytestring_length(cbor_quote) == 0
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 446 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vj7d07rPlQPmM1Xah:-O2vj7d07rPlQPmM1Xai:b-o6n8nm) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L446)):*
> ```C
> 
>         if (strncmp((char*)cbor_string_handle(claims_pairs[i].key), "pubkey-hash",
>                     cbor_string_length(claims_pairs[i].key)) == 0) {
> ```

- I think CBOR strings are not NULL-terminated.
- Doesn't this also accept stuff like `"pubkey-hash\0dupa"`?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 461 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vlFeh8zS8bwBgaF9w:-O2vlFeh8zS8bwBgaF9x:bl8chhn) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L461)):*
> ```C
>             if (cbor_result.error.code != CBOR_ERR_NONE) {
>                 ERROR("Certificate: cannot parse 'pubkey-hash' array in CBOR format (error %d)\n",
>                         cbor_result.error.code);
> ```

wrong alignment


<!-- Sent from Reviewable.io -->

2024-07-29 09:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 25 of 27 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qgM1n6IYnxnOcjxTZ:-O2xM-5y06Xu4su4q0eS:b-g01ka4) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this what you mean? Or something else? The current comment sounds weird to me.
</blockquote></details>

Done. Yes, that's what I meant. The idea of the comment is to explain why we choose the SHA256 algorithm for the CBOR hash, and that's because RA-TLS uses this hash algo (at least currently) to do the only hashing operation it does -- a hash over the public key of the generated ephemeral X.509 certificate.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 280 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qjIKiECdcmj9gcMrN:-O2xPCzR1mxuQh1z_Nxy:b-djx9yt) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L280)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What a weird format, why does this CBOR map contain a byte string with _serialized_ CBOR array, instead of a normal CBOR array?
</blockquote></details>

Yes, you are right. This is weird, and I also mentioned this here: https://github.com/CCC-Attestation/interoperable-ra-tls/issues/2#issuecomment-1380240294

Generally, the reason is that taking a hash over "some in-memory representation of a CBOR array" is ambiguous. How do you deal with pointers in that representation? What do you do with little-endian vs big-endian? Basically, you need a set of rules to transform the "in-memory representation" of a CBOR object to a "uniform unambiguous representation". That's why we perform serialization.

Also, that's just generally the reason why everything in this PR is "serialized CBOR object". Almost any CBOR object used in this PR has the potential of being hashed. And Interoperable RA-TLS uses the CoSWID standard, which forces a special CBOR representation of the "hashed value", see https://datatracker.ietf.org/doc/rfc9393/, Chapter 2.9.1. So, anything that can be hashed, should be represented as a hash over a serialized object.

Finally, why embed serialized objects inside CBOR objects, and not directly the CBOR objects (and calculate serialized variants on the side, for hashing purposes)? (Now I realize that was the crux of @mkow's question.) From what I was told, it's just *more explicit* to represent it this way -- all the objects that are hashed must be present in the CBOR composite. One side effect is that we are guaranteed to catch bugs in the serialization logic of the CBOR implementation. Another side effect that the CBOR implementation in the verifier may only implement a subset of CBOR functionality (well, maybe?) -- even it only wants to check the hash, it can just extract the serialized value without any need to deserialize it.

Well, long story short: I'm not confident why it was done this way, but I was told that's typical.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 328 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qlvqw7pyk76THsv9w:-O2xVNw9EAqJV7FOVBMF:b-rshns3) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L328)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a similar comment about references as in `generate_serialized_pk_hash_entry()`.
</blockquote></details>

Done. Also split from `cbor_claims`, because that one's reference is decremented because we serialized this object into the `claims_buf` buffer.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 340 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qmrQ27WQPTomc9cBh:-O2xV_AL40ZlRb08rVU6:b-srzshi) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L340)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

whyyyy
This is `map("asdf": serialize(map("qwer": serialize("asdf"))` at this point... Is there any reason for such a weird format with nested serialization?
</blockquote></details>

See my answer above. But yes, you are right. Please also check https://github.com/CCC-Attestation/interoperable-ra-tls/issues/2 if that helps.

TLDR: serialized objects are used because hashes are taken over them.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 404 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qtUe313kUtLmFNFtN:-O2xW1rw8RIpGlpGfsXZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L404)):*
> ```C
> }
> 
> /*! generate SGX-quote evidence with \p pk as one of the embedded claims (standard format) */
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 405 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qtbTf8eIh4lyA_bz1:-O2xYPFjDj1coc9rY8Fw:b-io0zir) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Using TCG DICE meanings, "evidence with claims" is like saying "numbers with digits" ;P

Both this and the previous function have IMO very confusing names. Both return serialized evidence, but only `generate_serialized_evidence()` has that in its name. Both generate evidence with claims (obviously), but only `generate_evidence_with_claims()` has that in its name.
</blockquote></details>

Done. What about new names?
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 489 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qwgjZEy0MpQWH92-m:-O2xYTzABdv46uLyZKnk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L489)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Weird comment formatting (empty first line, but not the last.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 193 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vLy5_-hWHDSiM41yG:-O2xYi_t53a1b-Y4ZM4t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L193)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's a bit confusing without it IMO.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vSTiPE90YkfBTIze_:-O2xZmOq3loxSWR2BNKn:b-3nikir) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: `mbedtls_pk_ec()` may disappear in the future (see https://github.com/Mbed-TLS/mbedtls/issues/7572).
</blockquote></details>

Yes, but this discussion seems a long way from being finished: https://github.com/Mbed-TLS/mbedtls/issues/8452

Any reason you put this comment as blocking?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewa [...]

2024-07-30 09:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 25 of 27 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 280 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qjIKiECdcmj9gcMrN:-O31wlj71Zx-VxaGmcQz:brx6adc) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L280)):*
> > Generally, the reason is that taking a hash over "some in-memory representation of a CBOR array"
> 
> Yup, but that explains only the middle serialization, not the serialization of alg+hash.

Yes, that's probably "for future". I agree, it is redundant.

> Why would you hash a hash?

I mean, it's not really a hash, it's a hash over a non-trivial CBOR object ("hash-entry"). But yes, I understand your point, does sound a bit useless, even for future-proof.
___
*[`tools/sgx/ra-tls/ra_tls_attest.c` line 405 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2qtbTf8eIh4lyA_bz1:-O322cz_5oLNLesbE8yf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_attest.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still confusing, the comment on the other function says `/*! generate tagged evidence [...]`, and you renamed this function here to `generate_tcg_dice_tagged_evidence`. I'm really confused by this split and what are the roles of both.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vSTiPE90YkfBTIze_:-O31xKAX0vkcwW0-JqK9:b-pyjo1e) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L194)):*
> > Any reason you put this comment as blocking?
> 
> To ensure I get a response to this before merging.

In Reviewable, "FYI" at the beginning of the message implies "not blocking", so it was surprising to me that this comment blocks. Just a mental hiccup.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 342 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vdRCF9GWjxD-oQepj:-O31y2aQ42zjHE7PtyZm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L342)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, that's IMO confusing. I'd initialize it in both places, as there no clear convention what happens with out-args on function failure.
Or maybe @kailun-qin has an idea for a better convention?
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 451 at r14](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2zEzCXC3-_2e1jfSbM:-O31xmqE1P8WbD09506v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f8f868ac834ec4526230a24c0d0618b4fcce16a/tools/sgx/ra-tls/ra_tls_verify_common.c#L451)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

They are the same, but this one is a constant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-30 11:50 UTC, mkow reviewed
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 194 at r13](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2vSTiPE90YkfBTIze_:-O32Qnc_6_HoP7-vic36:b-uaz338) ([raw file](https://github.com/gramineproject/gramine/blob/394c206323474efe82e56df79d0a6348f3ac78d7/tools/sgx/ra-tls/ra_tls_verify_common.c#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> > Any reason you put this comment as blocking?
> 
> To ensure I get a response to this before merging.

In Reviewable, "FYI" at the beginning of the message implies "not blocking", so it was surprising to me that this comment blocks. Just a mental hiccup.
</blockquote></details>

It doesn't _imply_ that - it only sets that disposition as default, you can change it. And I even disabled this option of auto-selecting dispositions ;)


<!-- Sent from Reviewable.io -->

2024-07-30 13:50 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 247 at r15](https://reviewable.io/reviews/gramineproject/gramine/1039#-O32seeF1oLIO0kT8Bky:-O32seeF1oLIO0kT8Bkz:bz3868a) ([raw file](https://github.com/gramineproject/gramine/blob/8f5c24f8da60e1b60c626d1c0c0c739e7af4468e/Documentation/attestation.rst#L247)):*
> ```reStructuredText
> .. image:: ./img/ratls-interoperable.svg
>    :target: ./img/ratls-interoperable.svg
>    :alt: Figure: The X.509 certificate generated by RA-TLS (standardized)
> ```

Everything in this SVG overlaps (mostly text) with each other and some places are completely unreadable. I tried both Firefox and Chromium (on Linux).
___
*[`Documentation/img/ratls-interoperable.svg` line 1 at r15](https://reviewable.io/reviews/gramineproject/gramine/1039#-O32tFZeDNWx_G-QBh-O:-O32tFZeDNWx_G-QBh-P:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8f5c24f8da60e1b60c626d1c0c0c739e7af4468e/Documentation/img/ratls-interoperable.svg#L1)):*
> ```SVG
> <svg width="4025" height="2497" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" overflow="hidden"><defs><clipPath id="clip0"><rect x="383" y="64" width="4025" height="2497"/></clipPath><clipPath id="clip1"><rect x="-2770.55" y="-0.363636" width="822960" height="820189"/></clipPath><image width="225" height="225" xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADhAOEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9U6KKKACiivnL/goZ8Tr/AOE/7IPxC1jSpXg1S6tY9Kt5o2KNGbmVIHdWHKssbuwI6ECgD4d/bi/4Kra7e+JNR8D/AAT1OPTNFs3e2vPF0AWSe9kHDC0Y5CRA5HmgFm4KFQAW/OXxR428ReOL37Z4j1/VPEF5/wA/Gq3slzJz1+Z2JrFr9B/2U/8AgkzqPx1+FGleO/FnjRvCdtrUf2jTdNsrEXMzW5PySyuzqF34LBQG+UqSQSVFFH58UV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5O6Xq19ol5Heade3Gn3cZylxaytFIp9QykEV9i/sq/8FQPiZ8DdatNP8aalf8AxF8Du4W4tdSn87ULVCeZLe4c7mIHSORihA2gx53D37x1/wAERzaeF7648I/EyXUNehjMltZappixQXLAHEZkWQmMk4+bawHcc5H5bXVrNY3U1tcRPBcQu0ckUgwyMDgqR2IIoA/qE8GeMtG+IXhPSfEvh6/i1TQ9Vtku7O8hztkjcZBweQexBwQQQQCCK2q/OX/git8Ub3xH8IfG/ga7lkmi8MalDd2Zc8Rw3iyExL7CSCV/rKa/RqpJCiiigAooooAKKKKACiiigAr46/4Ky/8AJlfib/sI6d/6UpX2LXx1/wAFZf8AkyvxN/2EdO/9KUoA/CGv6PP2L/8Ak0v4Qf8AYraf/wCiFr+cOv6PP2L/APk0v4Qf9itp/wD6IWmxs9nooopCCiiigAooooAKKKKACiiigAooooAKKKKACv5h/i1/yVbxp/2G73/0e9f08V/MP8Wv+SreNP8AsN3v/o96aGj9H/8Aghv/AMf3xnP/AEz0f+d7X6s1+U//AAQ3B+2fGg9vL0b+d9X6sUMGFFFFIQUUUUAFFFFABRRRQAV8df8ABWX/AJMr8Tf9hHTv/SlK+xa+Ov8AgrL/AMmV+Jv+wjp3/pSlAH4Q1/R5+xf/AMml/CD/ALFbT/8A0Qtfzh1/R5+xf/yaX8IP+xW0/wD9ELTY2ez14t8cP2yPg/8As66tbaT478YwaXrFxH5yadb2013cCM9HdIUYoD2L4zg4zivaa/nk/wCCgng/xX4R/a7+JLeLEuGl1TVZdR0+7mUhJ7GQ5tvLYjDKkeyI4zhomXqpoEfrH/w9W/Zq/wCh4u//AARX3/xmj/h6t+zV/wBDxd/+CK+/+M1+Ce4etG4etMdj97P+Hq37NX/Q8Xf/AIIr7/4zR/w9W/Zq/wCh4u//AARX3/xmvwT3D1o3D1oCx+9n/D1b9mr/AKHi7/8ABFff/GaP+Hq37NX/AEPF3/4Ir7/4zX4J7h60bh60BY/ez/h6t+zV/wBDxd/+CK+/+M0f8PVv2av+h4u//BFff/Ga/BPcPWjcPWgLH72f8PVv2av+h4u//BFff/GaP+Hq37NX/Q8Xf/givv8A4zX4J7h60bh60BY/oa+Fv/BQb4C/GLxhZ+F/DnjuJtdvWCWlrqFlcWYuHJwI0eWNULkkAJncxOADX0VX8vXgHwr4h8ceNNF0HwlZ3WoeJb66SKwgsciUy5yGUj7u3G4tkBQpJIAzX9PmmxXEGnWsd3Ks92kSLNIowHcAbiPqc0gLNfzD/Fr/AJKt40/7Dd7/AOj3r+niv5h/i1/yVbxp/wBhu9/9HvQgR+kX/BDb/j5+NP8AuaN/O+r9Vq/Kr/ghr/r/AI1f7ui/zvq/VWhgwooopCCiiigAooooAKKKKACvjr/grL/yZX4m/wCwjp3/AKUpX2LXx1/wVl/5Mr8Tf9hHTv8A0pSgD8Ia/o8/Yv8A+TS/hB/2K2n/APoha/nDr+jz9i//AJNL+EH/AGK2n/8AohabGz2esjxF4R0Lxhbxwa9ouna3BE26OLUbSO4VD6gOCAa16KQjif8AhR/w4/6J/wCF/wDwTW3/AMRR/wAKP+HH/RP/AAv/AOCa2/8AiK7aigDif+FH/Dj/AKJ/4X/8E1t/8RR/wo/4cf8ARP8Awv8A+Ca2/wDiK7aigDif+FH/AA4/6J/4X/8ABNbf/EUf8KP+HH/RP/C//gmtv/iK7aigDif+FH/Dj/on/hf/AME1t/8AEUf8KP8Ahx/0T/wv/wCCa2/+IrtqKAOJ/wCFH/Dj/on/AIX/APBNbf8AxFH/AAo/4cf9E/8AC/8A4Jrb/wCIrtqKAOf8O/D3wt4QuJLjQfDWj6JPIux5dOsIrdmX0JRQSK6CiigAr+Yf4tf8lW8af9hu9/8AR71/TxX8w/xa/wCSreNP+w3e/wDo96aGj9JP+CGv+s+Nf00T/wBv6/VSvyt/4Iafe+Nn/cE/9v6/VKhgwooopCCiiigAooooAKKKKACvjr/grL/yZX4m/wCwjp3/AKUpX2LXx1/wVl/5Mr8Tf9hHTv8A0pSgD8Ia/o8/Yv8A+TS/hB/2K2n/APoha/nDr+jz9i//AJNL+EH/AGK2n/8AohabGz2evyG/bb/4Kh/E7QfjZ4l8E/C7Ubbwrovhq+k0yfUDYxXN1eXMTFJyfPRlSMSBlUKuTs3bsNtH681+a/7Y/wDwSb1X4yfFbWPHvw28S6RpFxrs32rUdH10SxwrcEfvJopYkc/OfmKMnDFjuwwVUI+J/wDh55+03/0U5/8AwR6b/wDI1H/Dzz9pv/opz/8Agj03/wCRq9Z/4cr/ABw/6Gn4f/8Agwvv/kOj/hyv8cP+hp+H/wD4ML7/AOQ6eg9Dyb/h55+03/0U5/8AwR6b/wDI1H/Dzz9pv/opz/8Agj03/wCRq9Z/4cr/ABw/6Gn4f/8Agwvv/kOj/hyv8cP+hp+H/wD4ML7/AOQ6NA0PJv8Ah55+03/0U5//AAR6b/8AI1H/AA88/ab/AOinP/4I9N/+Rq9Z/wCHK/xw/wChp+H/AP4ML7/5Do/4cr/HD/oafh//AODC+/8AkOjQNDyb/h55+03/ANFOf/wR6b/8jUf8PPP2m/8Aopz/APgj03/5Gr1n/hyv8cP+hp+H/wD4ML7/AOQ6P+HK/wAcP+hp+H//AIML7/5Do0DQ8m/4eeftN/8ARTn/APBHpv8A8jUf8PPP2m/+inP/AOCPTf8A5Gr1n/hyv8cP+hp+H/8A4ML7/wCQ6P8Ahyv8cP8Aoafh/wD+DC+/+Q6NA0Oc+EP/AAVq+OHg/wAaWN5421uHxz4ZMire6bNptrbS+Vn5mhkhjjIkA6bsqccjvX7h2V5FqFnBdW7+ZBPGssbYxlWGQfyNfkv8Hv8Agiv4qj8Z2Nz8TvF2gN4Yt5VlnsfDctxNPeKDkxb5IovKB6FhuOM4API/WyGJLeJIo0WONFCqijAUDgAD0pCH1/MP8Wv+SreNP+w3e/8Ao96/p4r+Yf4tf8lW8af9hu9/9HvTQ0fpN/wQ0+98bP8AuCf+39fqlX5W/wDBDT73xs/7gn/t/X6pUMGFFFFIQUUUUAFFFFABRRRQAV8df8FZf+TK/E3/AGEdO/8ASlK+xa+Ov+Csv/Jlfib/ALCOnf8ApSlAH4Q1/R5+xf8A8ml/CD/sVtP/APRC1/OHX9Hn7F//ACaX8IP+xW0//wBELTY2ez0UUUhBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABX8w/xa/5Kt40/wCw3e/+j3r+niv5h/i1/wAlW8af9hu9/wDR700NH6Tf8ENPvfGz/uCf+39fqlX5W/8ABDT73xs/7gn/ALf1+qVDBhRRRSEFFFFABRRRQAUUUUAFfHX/AAVl/wCTK/E3/YR07/0pSvsWvjr/AIKy/wDJlfib/sI6d/6UpQB+ENf0efsX/wDJpfwg/wCxW0//ANELX84df0efsX/8ml/CD/sVtP8A/RC02Nns9FFFIQUUUUAFFFFABRXm37R3xmtf2fPgf4v+IN1bC9GiWfmQ2rMVE87usUMZI6BpXQE9gSa/DHxB/wAFD/2hvEPiifXG+Juq6dLI5ZLLTgkNnEuThFhC7SAOMsGY4ySTzQB/QvWb4k8SaV4P0DUNc1zULfStI0+Fri6vbqQJFDGoyzMx6ACvw18G/wDBWf8AaJ8LZF9r+j+KkzkLrOkRDA9M2/lE/iSeetcN+0d+3h8XP2sNOs/D3iO5stP0QSow0Lw7bSQw3UwPyNIGd3kIOMKWKg4IXPNMZ3/7dn/BQzxD+0l4kuPD3g6/v/D/AMM7N2jit4ZGgm1Y9DNcYIOw/wAMR4A5Ybvu+Z/sk/tneNv2UfGdrd6ZeXGreEJH26l4ZuJ2+zzxk/M0YORFKOodR14bKkiuW8P/ALJnxr8URrLpnwn8ZXEDDcszaJcRxsPZ3QA/gata1+xv8dNAj8y8+EXjLy+7W+jTzgcZyfLVsD3NPQeh/QZ8HfjF4V+PHw/0zxl4O1JdS0a+Xj+GWCQY3wypn5JFJwV+hGQQT2tfzk/Af9pr4q/sc+ML9vDVxJpUkxC6n4d1y0Y29wQDt82FtrqwzkMpVu2dpIPtHi//AIK8/tCeJrYxafe+HfCjnH77R9IDsOf+nl5hz9O9IR+51fIH7UX/AATN+Fnx+0u+1DQNMtvAPjdt0sWq6RCIre4lOTi5gUbXDEkl1CyZwdzAFT+TN1+31+0Lea1DqknxY8QLcwtuWOKRI4Dzn5oFURsPYqa/ZD/gn/8AtRX/AO1Z8B4/EGuW0Vt4m0m9fSNUaBQkVxKkccizooJ2h0kXI4wyvgAYoA+Zv+CPvw71/wCEvjz9ofwf4osW07XtHuNFtrq3bkBh9vIZT/EjKVZWHBVgR1r9Lq5XSfh9p+jfErxL4xtkWO/17TtPsLraMb/sj3TI59Wxdbc+iKO1dVSEFFFFABRRRQAUUUUAFFFFABXx1/wVl/5Mr8Tf9hHTv/SlK+xa+Ov+Csv/ACZX4m/7COnf+lKUAfhDX9Hn7F//ACaX8IP+xW0//wBELX84df0efsX/APJpfwg/7FbT/wD0QtNjZ7PRRRSEFFFFABRRXKfEr4reEPg74am8QeNfEWn+G9Iiz/pF9ME3sBnZGv3pHx0VAWPYUAfJn/BYLxf/AMI5+yDJpgyW8Qa9ZafhSPup5lySRnpm3A+pFfh2iNI6oilnY4CqMkn0Ffan/BSH9ubS/wBqvWtD8O+DYLqHwR4flluBdXkf [...]

2024-07-31 09:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 26 of 27 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/attestation.rst` line 247 at r15](https://reviewable.io/reviews/gramineproject/gramine/1039#-O32seeF1oLIO0kT8Bky:-O37-Y2w1i9lHMJsh9EP:b-l2yrx1) ([raw file](https://github.com/gramineproject/gramine/blob/8f5c24f8da60e1b60c626d1c0c0c739e7af4468e/Documentation/attestation.rst#L247)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Everything in this SVG overlaps (mostly text) with each other and some places are completely unreadable. I tried both Firefox and Chromium (on Linux).
</blockquote></details>

To me, it rendered fine...

I changed the font from Calibri to Arial. See https://gramine--1039.org.readthedocs.build/en/1039/attestation.html

Is it better for you now?
___
*[`Documentation/img/ratls-interoperable.svg` line 1 at r15](https://reviewable.io/reviews/gramineproject/gramine/1039#-O32tFZeDNWx_G-QBh-O:-O371dcZ-tZn256x2KKc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8f5c24f8da60e1b60c626d1c0c0c739e7af4468e/Documentation/img/ratls-interoperable.svg#L1)):*
> ```SVG
> <svg width="4025" height="2497" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" overflow="hidden"><defs><clipPath id="clip0"><rect x="383" y="64" width="4025" height="2497"/></clipPath><clipPath id="clip1"><rect x="-2770.55" y="-0.363636" width="822960" height="820189"/></clipPath><image width="225" height="225" xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADhAOEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9U6KKKACiivnL/goZ8Tr/AOE/7IPxC1jSpXg1S6tY9Kt5o2KNGbmVIHdWHKssbuwI6ECgD4d/bi/4Kra7e+JNR8D/AAT1OPTNFs3e2vPF0AWSe9kHDC0Y5CRA5HmgFm4KFQAW/OXxR428ReOL37Z4j1/VPEF5/wA/Gq3slzJz1+Z2JrFr9B/2U/8AgkzqPx1+FGleO/FnjRvCdtrUf2jTdNsrEXMzW5PySyuzqF34LBQG+UqSQSVFFH58UV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5JUV+tv/Dj/wAN/wDRVtW/8FEX/wAdo/4cf+G/+irat/4KIv8A47RcLn5O6Xq19ol5Heade3Gn3cZylxaytFIp9QykEV9i/sq/8FQPiZ8DdatNP8aalf8AxF8Du4W4tdSn87ULVCeZLe4c7mIHSORihA2gx53D37x1/wAERzaeF7648I/EyXUNehjMltZappixQXLAHEZkWQmMk4+bawHcc5H5bXVrNY3U1tcRPBcQu0ckUgwyMDgqR2IIoA/qE8GeMtG+IXhPSfEvh6/i1TQ9Vtku7O8hztkjcZBweQexBwQQQQCCK2q/OX/git8Ub3xH8IfG/ga7lkmi8MalDd2Zc8Rw3iyExL7CSCV/rKa/RqpJCiiigAooooAKKKKACiiigAr46/4Ky/8AJlfib/sI6d/6UpX2LXx1/wAFZf8AkyvxN/2EdO/9KUoA/CGv6PP2L/8Ak0v4Qf8AYraf/wCiFr+cOv6PP2L/APk0v4Qf9itp/wD6IWmxs9nooopCCiiigAooooAKKKKACiiigAooooAKKKKACv5h/i1/yVbxp/2G73/0e9f08V/MP8Wv+SreNP8AsN3v/o96aGj9H/8Aghv/AMf3xnP/AEz0f+d7X6s1+U//AAQ3B+2fGg9vL0b+d9X6sUMGFFFFIQUUUUAFFFFABRRRQAV8df8ABWX/AJMr8Tf9hHTv/SlK+xa+Ov8AgrL/AMmV+Jv+wjp3/pSlAH4Q1/R5+xf/AMml/CD/ALFbT/8A0Qtfzh1/R5+xf/yaX8IP+xW0/wD9ELTY2ez14t8cP2yPg/8As66tbaT478YwaXrFxH5yadb2013cCM9HdIUYoD2L4zg4zivaa/nk/wCCgng/xX4R/a7+JLeLEuGl1TVZdR0+7mUhJ7GQ5tvLYjDKkeyI4zhomXqpoEfrH/w9W/Zq/wCh4u//AARX3/xmj/h6t+zV/wBDxd/+CK+/+M1+Ce4etG4etMdj97P+Hq37NX/Q8Xf/AIIr7/4zR/w9W/Zq/wCh4u//AARX3/xmvwT3D1o3D1oCx+9n/D1b9mr/AKHi7/8ABFff/GaP+Hq37NX/AEPF3/4Ir7/4zX4J7h60bh60BY/ez/h6t+zV/wBDxd/+CK+/+M0f8PVv2av+h4u//BFff/Ga/BPcPWjcPWgLH72f8PVv2av+h4u//BFff/GaP+Hq37NX/Q8Xf/givv8A4zX4J7h60bh60BY/oa+Fv/BQb4C/GLxhZ+F/DnjuJtdvWCWlrqFlcWYuHJwI0eWNULkkAJncxOADX0VX8vXgHwr4h8ceNNF0HwlZ3WoeJb66SKwgsciUy5yGUj7u3G4tkBQpJIAzX9PmmxXEGnWsd3Ks92kSLNIowHcAbiPqc0gLNfzD/Fr/AJKt40/7Dd7/AOj3r+niv5h/i1/yVbxp/wBhu9/9HvQgR+kX/BDb/j5+NP8AuaN/O+r9Vq/Kr/ghr/r/AI1f7ui/zvq/VWhgwooopCCiiigAooooAKKKKACvjr/grL/yZX4m/wCwjp3/AKUpX2LXx1/wVl/5Mr8Tf9hHTv8A0pSgD8Ia/o8/Yv8A+TS/hB/2K2n/APoha/nDr+jz9i//AJNL+EH/AGK2n/8AohabGz2esjxF4R0Lxhbxwa9ouna3BE26OLUbSO4VD6gOCAa16KQjif8AhR/w4/6J/wCF/wDwTW3/AMRR/wAKP+HH/RP/AAv/AOCa2/8AiK7aigDif+FH/Dj/AKJ/4X/8E1t/8RR/wo/4cf8ARP8Awv8A+Ca2/wDiK7aigDif+FH/AA4/6J/4X/8ABNbf/EUf8KP+HH/RP/C//gmtv/iK7aigDif+FH/Dj/on/hf/AME1t/8AEUf8KP8Ahx/0T/wv/wCCa2/+IrtqKAOJ/wCFH/Dj/on/AIX/APBNbf8AxFH/AAo/4cf9E/8AC/8A4Jrb/wCIrtqKAOf8O/D3wt4QuJLjQfDWj6JPIux5dOsIrdmX0JRQSK6CiigAr+Yf4tf8lW8af9hu9/8AR71/TxX8w/xa/wCSreNP+w3e/wDo96aGj9JP+CGv+s+Nf00T/wBv6/VSvyt/4Iafe+Nn/cE/9v6/VKhgwooopCCiiigAooooAKKKKACvjr/grL/yZX4m/wCwjp3/AKUpX2LXx1/wVl/5Mr8Tf9hHTv8A0pSgD8Ia/o8/Yv8A+TS/hB/2K2n/APoha/nDr+jz9i//AJNL+EH/AGK2n/8AohabGz2evyG/bb/4Kh/E7QfjZ4l8E/C7Ubbwrovhq+k0yfUDYxXN1eXMTFJyfPRlSMSBlUKuTs3bsNtH681+a/7Y/wDwSb1X4yfFbWPHvw28S6RpFxrs32rUdH10SxwrcEfvJopYkc/OfmKMnDFjuwwVUI+J/wDh55+03/0U5/8AwR6b/wDI1H/Dzz9pv/opz/8Agj03/wCRq9Z/4cr/ABw/6Gn4f/8Agwvv/kOj/hyv8cP+hp+H/wD4ML7/AOQ6eg9Dyb/h55+03/0U5/8AwR6b/wDI1H/Dzz9pv/opz/8Agj03/wCRq9Z/4cr/ABw/6Gn4f/8Agwvv/kOj/hyv8cP+hp+H/wD4ML7/AOQ6NA0PJv8Ah55+03/0U5//AAR6b/8AI1H/AA88/ab/AOinP/4I9N/+Rq9Z/wCHK/xw/wChp+H/AP4ML7/5Do/4cr/HD/oafh//AODC+/8AkOjQNDyb/h55+03/ANFOf/wR6b/8jUf8PPP2m/8Aopz/APgj03/5Gr1n/hyv8cP+hp+H/wD4ML7/AOQ6P+HK/wAcP+hp+H//AIML7/5Do0DQ8m/4eeftN/8ARTn/APBHpv8A8jUf8PPP2m/+inP/AOCPTf8A5Gr1n/hyv8cP+hp+H/8A4ML7/wCQ6P8Ahyv8cP8Aoafh/wD+DC+/+Q6NA0Oc+EP/AAVq+OHg/wAaWN5421uHxz4ZMire6bNptrbS+Vn5mhkhjjIkA6bsqccjvX7h2V5FqFnBdW7+ZBPGssbYxlWGQfyNfkv8Hv8Agiv4qj8Z2Nz8TvF2gN4Yt5VlnsfDctxNPeKDkxb5IovKB6FhuOM4API/WyGJLeJIo0WONFCqijAUDgAD0pCH1/MP8Wv+SreNP+w3e/8Ao96/p4r+Yf4tf8lW8af9hu9/9HvTQ0fpN/wQ0+98bP8AuCf+39fqlX5W/wDBDT73xs/7gn/t/X6pUMGFFFFIQUUUUAFFFFABRRRQAV8df8FZf+TK/E3/AGEdO/8ASlK+xa+Ov+Csv/Jlfib/ALCOnf8ApSlAH4Q1/R5+xf8A8ml/CD/sVtP/APRC1/OHX9Hn7F//ACaX8IP+xW0//wBELTY2ez0UUUhBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABX8w/xa/5Kt40/wCw3e/+j3r+niv5h/i1/wAlW8af9hu9/wDR700NH6Tf8ENPvfGz/uCf+39fqlX5W/8ABDT73xs/7gn/ALf1+qVDBhRRRSEFFFFABRRRQAUUUUAFfHX/AAVl/wCTK/E3/YR07/0pSvsWvjr/AIKy/wDJlfib/sI6d/6UpQB+ENf0efsX/wDJpfwg/wCxW0//ANELX84df0efsX/8ml/CD/sVtP8A/RC02Nns9FFFIQUUUUAFFFFABRXm37R3xmtf2fPgf4v+IN1bC9GiWfmQ2rMVE87usUMZI6BpXQE9gSa/DHxB/wAFD/2hvEPiifXG+Juq6dLI5ZLLTgkNnEuThFhC7SAOMsGY4ySTzQB/QvWb4k8SaV4P0DUNc1zULfStI0+Fri6vbqQJFDGoyzMx6ACvw18G/wDBWf8AaJ8LZF9r+j+KkzkLrOkRDA9M2/lE/iSeetcN+0d+3h8XP2sNOs/D3iO5stP0QSow0Lw7bSQw3UwPyNIGd3kIOMKWKg4IXPNMZ3/7dn/BQzxD+0l4kuPD3g6/v/D/AMM7N2jit4ZGgm1Y9DNcYIOw/wAMR4A5Ybvu+Z/sk/tneNv2UfGdrd6ZeXGreEJH26l4ZuJ2+zzxk/M0YORFKOodR14bKkiuW8P/ALJnxr8URrLpnwn8ZXEDDcszaJcRxsPZ3QA/gata1+xv8dNAj8y8+EXjLy+7W+jTzgcZyfLVsD3NPQeh/QZ8HfjF4V+PHw/0zxl4O1JdS0a+Xj+GWCQY3wypn5JFJwV+hGQQT2tfzk/Af9pr4q/sc+ML9vDVxJpUkxC6n4d1y0Y29wQDt82FtrqwzkMpVu2dpIPtHi//AIK8/tCeJrYxafe+HfCjnH77R9IDsOf+nl5hz9O9IR+51fIH7UX/AATN+Fnx+0u+1DQNMtvAPjdt0sWq6RCIre4lOTi5gUbXDEkl1CyZwdzAFT+TN1+31+0Lea1DqknxY8QLcwtuWOKRI4Dzn5oFURsPYqa/ZD/gn/8AtRX/AO1Z8B4/EGuW0Vt4m0m9fSNUaBQkVxKkccizooJ2h0kXI4wyvgAYoA+Zv+CPvw71/wCEvjz9ofwf4osW07XtHuNFtrq3bkBh9vIZT/EjKVZWHBVgR1r9Lq5XSfh9p+jfErxL4xtkWO/17TtPsLraMb/sj3TI59Wxdbc+iKO1dVSEFFFFABRRRQAUUUUAFFFFABXx1/wVl/5Mr8Tf9hHTv/SlK+xa+Ov+Csv/ACZX4m/7COnf+lKUAfhDX9Hn7F//ACaX8IP+xW0//wBELX84df0efsX/APJpfwg/7FbT/wD0QtNjZ7PRRRSEFFFFABRRXKfEr4reEPg74am8QeNfEWn+G9Iiz/pF9ME3sBnZGv3pHx0V [...]

2024-08-04 18:39 UTC, mkow reviewed
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 247 at r15](https://reviewable.io/reviews/gramineproject/gramine/1039#-O32seeF1oLIO0kT8Bky:-O3TfeQC3t4Jh0ipL8wI:b7o8mt5) ([raw file](https://github.com/gramineproject/gramine/blob/8f5c24f8da60e1b60c626d1c0c0c739e7af4468e/Documentation/attestation.rst#L247)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To me, it rendered fine...

I changed the font from Calibri to Arial. See https://gramine--1039.org.readthedocs.build/en/1039/attestation.html

Is it better for you now?
</blockquote></details>

Yup, works now.


<!-- Sent from Reviewable.io -->

2024-08-06 08:47 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`subprojects/libcbor-0.11.0.wrap` line 3 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2N0jjM1WWKjAySMLIT:-O3aqxqqCuJ-OmhQuQqK:b-g3123t) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/libcbor-0.11.0.wrap#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just a note: A significant (IMO) drawback of this PR is pulling some niche project into our TCB and exposing it to untrusted input.
</blockquote></details>

This is the only significant C implementation of CBOR, packaged in every major distro, I guess it gets as much eyeballs as it would. Not that CBOR is a widely used format though.
___
*[`subprojects/libcbor-0.11.0.wrap` line 4 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2PrxiO2SfazjY0Lm4U:-O3aq8Jh0QKWm6iX3SHG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/libcbor-0.11.0.wrap#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Please upload.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-06 22:32 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`subprojects/libcbor-0.11.0.wrap` line 3 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2N0jjM1WWKjAySMLIT:-O3doL9U-ujEmfm26wQa:b2nha9w) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/libcbor-0.11.0.wrap#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is the only significant C implementation of CBOR, packaged in every major distro, I guess it gets as much eyeballs as it would. Not that CBOR is a widely used format though.
</blockquote></details>

ACK
___
*[`subprojects/libcbor-0.11.0.wrap` line 4 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2PrxiO2SfazjY0Lm4U:-O3doTOq4akY58BJ-laM:b2nh05v) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/libcbor-0.11.0.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

404


<!-- Sent from Reviewable.io -->

2024-08-07 06:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: 26 of 27 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`subprojects/libcbor-0.11.0.wrap` line 4 at r11](https://reviewable.io/reviews/gramineproject/gramine/1039#-O2PrxiO2SfazjY0Lm4U:-O3f_Vmx8JCIBom1xrqG:b-pla4vh) ([raw file](https://github.com/gramineproject/gramine/blob/de28d4620c10dd4a6bdcc573c9e373af80cde829/subprojects/libcbor-0.11.0.wrap#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

404
</blockquote></details>

Done. Now should work.


<!-- Sent from Reviewable.io -->

2024-08-08 00:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1039)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-08 00:59 UTC, merged