Make logs more verbose
gramineproject/gramine pull request #1040
Opened 2022-11-11 15:54 UTC by oshogbo

## Description of the changes 

In many places Gramine developers adds manually information about file, line number, and function.
This isn't structured in any way.
Instead i propose to add these information always if the debug level is set.

Logs after this change:
```
(libos/src/ipc/libos_ipc_pid.c:329:ipc_release_id_range_callback) [P1:libos] debug: release_id_range(2..2)
(libos/src/sys/libos_exit.c:179:libos_syscall_exit_group) [P1:T1:a.out] debug: ---- exit_group (returning 0)
(libos/src/fs/libos_fs_lock.c:651:posix_lock_clear_pid) [P1:T1:a.out] debug: clearing POSIX locks for pid 1
(libos/src/sync/libos_sync_client.c:331:shutdown_sync_client) [P1:T1:a.out] debug: sync client shutdown: closing handles
(libos/src/sync/libos_sync_client.c:346:shutdown_sync_client) [P1:T1:a.out] debug: sync client shutdown: waiting for confirmation
(libos/src/sync/libos_sync_client.c:359:shutdown_sync_client) [P1:T1:a.out] debug: sync client shutdown: finished
(libos/src/ipc/libos_ipc_worker.c:284:ipc_worker_main) [P1:libos] debug: IPC worker: exiting worker thread
(libos/src/sys/libos_exit.c:58:libos_clean_and_exit) [P1:T1:a.out] debug: process 1 exited with status 0
```

This is simple aporach where we take the whole __FILE__ which is quite verbose. Maybe instead of full path we want to just print the filename?

2022-11-21 22:21 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 0 of 29 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NHRGGBG1UTSez1lgyVT:-NHRGGBG1UTSez1lgyVU:bop454m) (no related file):*
> This is a simple approach where we take the whole FILE, which is quite verbose. Maybe instead of the full path we just want to print the filename?

Alternative idea: Maybe we could print the additional info at the end of the line? This way the messages wouldn't get lost. In the current version it's hard to read them, because on each line you need to search for the beginning of the message (and the message is usually the most important information you're looking for).
Downside of this is that it makes the format a bit less consistent, because we'd have some info at the beginning of the line and some at the end. But I don't see any better way :(

___


<!-- Sent from Reviewable.io -->

2023-01-03 14:28 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 0 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKs0Qom6Y6iZ_5Crw0N:-NKs0Qom6Y6iZ_5Crw0O:b7l8vbw) (no related file):*
I don't find this readable at all :(

Do we really need this? I was totally fine with the current messages, and never needed additional info on filenames.

Note that I would be Ok with having a uniform `__func__` prefix for all `log_debug()`. Printing a func name is typically helpful.

___


<!-- Sent from Reviewable.io -->

2023-01-04 11:02 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 0 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NHRGGBG1UTSez1lgyVT:-NKwR8-s1BxLJhVyOvym:bb3j9e2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is a simple approach where we take the whole FILE, which is quite verbose. Maybe instead of the full path we just want to print the filename?

Alternative idea: Maybe we could print the additional info at the end of the line? This way the messages wouldn't get lost. In the current version it's hard to read them, because on each line you need to search for the beginning of the message (and the message is usually the most important information you're looking for).
Downside of this is that it makes the format a bit less consistent, because we'd have some info at the beginning of the line and some at the end. But I don't see any better way :(
</blockquote></details>

I don't really like the idea on the end of file.
I would prefer just to have the simpler version of it. Maybe like:
```
(llibos_ipc_pid.c:329:ipc_release_id_range_callback) [P1:libos] debug: release_id_range(2..2)
```

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKs0Qom6Y6iZ_5Crw0N:-NKwQqqXCJYN7M8_1mGG:b-dnxfjx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't find this readable at all :(

Do we really need this? I was totally fine with the current messages, and never needed additional info on filenames.

Note that I would be Ok with having a uniform `__func__` prefix for all `log_debug()`. Printing a func name is typically helpful.
</blockquote></details>

We can try making it more readable for example with truncating the file name or so.
I don't like the idea that some logs have implicite print of filename/function/line and some doesn't.
I think we are mixing the user logs with developer logs.
I think this should be unified instead of left developer to decide.

___


<!-- Sent from Reviewable.io -->

2023-01-04 14:23 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 0 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKs0Qom6Y6iZ_5Crw0N:-NKx8vLHEh-0JCYPdzVb:b-3ffgpz) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We can try making it more readable for example with truncating the file name or so.
I don't like the idea that some logs have implicite print of filename/function/line and some doesn't.
I think we are mixing the user logs with developer logs.
I think this should be unified instead of left developer to decide.
</blockquote></details>

Yeah, I also prefer to have filenames+functions attached to logs, but we need to figure out a better way to format them (and make them shorter). Or maybe it should depend on log level? Dunno...

___


<!-- Sent from Reviewable.io -->

2023-01-04 14:48 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 0 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKs0Qom6Y6iZ_5Crw0N:-NKxAhZM3Cv7L5Bl78rk:bt7im0q) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I also prefer to have filenames+functions attached to logs, but we need to figure out a better way to format them (and make them shorter). Or maybe it should depend on log level? Dunno...
</blockquote></details>

In current version we only add this information if somebody sets the log level to debug in the manifest.
I will try to truncate the filename.

@dimakuv One more idea: what if in separate PR I would add colours to logs (only for tty)? Would add readability?

___


<!-- Sent from Reviewable.io -->

2023-01-04 15:44 UTC, oshogbo reviewed
The style of logs now:
```
(libos_vma.c:616:init_vma) debug: Initial VMA region 0x1fc2e000-0x1fc31000 (PAL internal me) bookkeeped
(libos_vma.c:616:init_vma) debug: Initial VMA region 0x1fc2b000-0x1fc2e000 (PAL internal me) bookkeeped
(libos_vma.c:616:init_vma) debug: Initial VMA region 0x1fc29000-0x1fc2b000 (PAL internal me) bookkeeped
(libos_vma.c:616:init_vma) debug: Initial VMA region 0x1fc27000-0x1fc29000 (PAL internal me) bookkeeped
(libos_vma.c:616:init_vma) debug: Initial VMA region 0x1fc24000-0x1fc27000 (PAL internal me) bookkeeped
```

Information about __FILE_NAME__:
* https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html
* https://reviews.llvm.org/D61756
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42579

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040#-:-NKxRIN64QPwyAonPSnQ:b-ikh1fl)* status: 0 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2023-01-05 11:25 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 19 of 29 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NHRGGBG1UTSez1lgyVT:-NL0dIWv-2Hg0OBvZpsa:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, this looks much better to me!
</blockquote></details>

Done.

___
___
*[`common/include/callbacks.h` line 48 at r2](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKxeR69-DTUopQ_jKkV:-NKxgsdeEDKTZiLZT85P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55a422d323c4f7978ce27680c5aecfee81d117f5/common/include/callbacks.h#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`char *arg` -> `char* arg`

Everywhere in this PR.
</blockquote></details>

Done.
___
*[`libos/src/utils/log.c` line 89 at r2](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKxfGHm8M0NOC9QUiYW:-NL0eQ2m9PCyRG_LCNrl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55a422d323c4f7978ce27680c5aecfee81d117f5/libos/src/utils/log.c#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`%lu`?
</blockquote></details>

Done.
___
*[`pal/regression/utils.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKxfJmMAQt623oQMD5o:-NL0eSSn-3mEhHL9dPVD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55a422d323c4f7978ce27680c5aecfee81d117f5/pal/regression/utils.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`%lu`?
</blockquote></details>

Done.
___
*[`pal/src/printf.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKxfNDD12Ac9nXhYjnm:-NL0eZp93P1-NWk-S2B6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55a422d323c4f7978ce27680c5aecfee81d117f5/pal/src/printf.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`%lu`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_log.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1040#-NKxfTrZ33TH6YHV1MYj:-NL0ecTBBrny7AZo10NQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55a422d323c4f7978ce27680c5aecfee81d117f5/pal/src/host/linux-sgx/host_log.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`%lu`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-05 12:45 UTC, dimakuv submitted a review, later dismissed
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-01-11 14:17 UTC, mkow requested changes
> Reviewed 19 of 29 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9DTH6fEaiUld0647:-NLW9DTI2zu1ebfGE-sV:b-ha49bd) (no related file):*
There are still some places left:
- `#define refcount_dec(ref) _refcount_dec((ref), __FILE__, __LINE__)` in `libos_refcount.h`
- a few places in newly added `enclave_edmm.c` (this will require you to rebase this PR first)

In general, please wait for us finishing the review and then rebase and grep the whole repo again.

___
___
*[`common/include/log.h` line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW8oc46HdyqLTT59ek:-NLW8oc46HdyqLTT59el:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f2afca732f89f290d905ec15aca261306e4de008/common/include/log.h#L35)):*
> ```objc
> }
> 
> #define __FILE_NAME__ truncate_file_name(__FILE__)
> ```





_Suggestion:_
```objc
#define __FILE_NAME__ (truncate_file_name(__FILE__))
```
___
*[`tools/sgx/common/util.c` line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9zbLBLwIhtH8r6i_:-NLW9zbLBLwIhtH8r6ia:b-n6if5g) ([raw file](https://github.com/gramineproject/gramine/blob/f2afca732f89f290d905ec15aca261306e4de008/tools/sgx/common/util.c#L246)):*
> ```C
>     (void)file;
>     (void)line;
>     (void)func;
> ```

Why not printing them here?


<!-- Sent from Reviewable.io -->

2023-01-11 18:17 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: 27 of 30 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9DTH6fEaiUld0647:-NLWzBwr5hrEodq5T0XB:bwi8bcc) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There are still some places left:
- `#define refcount_dec(ref) _refcount_dec((ref), __FILE__, __LINE__)` in `libos_refcount.h`
- a few places in newly added `enclave_edmm.c` (this will require you to rebase this PR first)

In general, please wait for us finishing the review and then rebase and grep the whole repo again.
</blockquote></details>

Yes,  I will go over all this places one more time when I will rebase it.

___
___
*[`common/include/log.h` line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW8oc46HdyqLTT59ek:-NLX1u088xRy1eQaOCST:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afca732f89f290d905ec15aca261306e4de008/common/include/log.h#L35)):*
> ```objc
> }
> 
> #define __FILE_NAME__ truncate_file_name(__FILE__)
> ```

Done.
___
*[`tools/sgx/common/util.c` line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9zbLBLwIhtH8r6i_:-NLWy2bh2TYhPYWXsQ02:b-rgh2md) ([raw file](https://github.com/gramineproject/gramine/blob/f2afca732f89f290d905ec15aca261306e4de008/tools/sgx/common/util.c#L246)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not printing them here?
</blockquote></details>

I assumed (as the level is ignored here) that it doesn't make sens to add these information to log for tools. I'm not sure even if we can change a "current debug level" for tools? If you want I can investigate this furthermore or just simply print it anyhow.


<!-- Sent from Reviewable.io -->

2023-01-12 08:48 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`tools/sgx/common/util.c` line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9zbLBLwIhtH8r6i_:-NL_9aZJ1KqJmvRdEA9Q:bbqewd) ([raw file](https://github.com/gramineproject/gramine/blob/f2afca732f89f290d905ec15aca261306e4de008/tools/sgx/common/util.c#L246)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I assumed (as the level is ignored here) that it doesn't make sens to add these information to log for tools. I'm not sure even if we can change a "current debug level" for tools? If you want I can investigate this furthermore or just simply print it anyhow.
</blockquote></details>

From my side, I wouldn't care. These are stand-alone tools, and finding an exact func/line where the message is printed shouldn't be a big problem.


<!-- Sent from Reviewable.io -->

2023-01-15 16:27 UTC, mkow reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-18 14:51 UTC, dimakuv approved these changes
> Reviewed 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9DTH6fEaiUld0647:-NM4LYY10RWyxS3GeKpe:b-5chgrk) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes,  I will go over all this places one more time when I will rebase it.
</blockquote></details>

@oshogbo This was done, right?

___


<!-- Sent from Reviewable.io -->

2023-01-18 15:15 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9DTH6fEaiUld0647:-NM4RkMh-qKSQ6V5bWGw:bb77ufg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo This was done, right?
</blockquote></details>

Yes.

___


<!-- Sent from Reviewable.io -->

2023-01-18 15:22 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1040#-NLW9DTH6fEaiUld0647:-NM4T41T7I4UDzYYOtGC:b-8rsf7z) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Eh, thank you, I have double-checked and it turns out that I had some changes stashed.

___


<!-- Sent from Reviewable.io -->

2023-01-18 15:54 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-01-23 11:00 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-23 11:20 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-01-23 11:27 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1040)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-23 12:08 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (blender download timed out)

2023-01-23 12:52 UTC, merged