[CI-Examples] Update nginx version to 1.22.0
gramineproject/gramine pull request #1047
Opened 2022-11-16 04:05 UTC by anjalirai-intel

Nginx version 1.16.1 is not compatible with openssl version available for Ubuntu 22.04. Nginx make kept failing with deprecated errors.
So, in order to enable Nginx for Ubuntu 22.04 also, we need to upgrade nginx version.

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

## Description of the changes 

## How to test this PR?

2022-11-16 08:20 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWT2o4Iz8EyupdilC):*
`nginx` -> `Nginx`
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWG1y3podnONy94im):*
`OpenSSL v3.0.2`
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWJ2yEYSMR3YaBwHc):*
`for` -> `on`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWLTX3xW2_LIyaM92):*
I will remove this last sentence, it doesn't give any interesting information.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWQLk7zGY6x3f1RtR):*
I will remove this sentence since it's already in the commit title.


<!-- Sent from Reviewable.io -->

2022-11-16 08:20 UTC, dimakuv commented
Jenkins, test this plesae

2022-11-16 08:20 UTC, dimakuv commented
Jenkins, test this please

2022-11-16 16:21 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel)



<!-- Sent from Reviewable.io -->

2022-11-22 08:01 UTC, anjalirai-intel commented
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWG1y3podnONy94im):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`OpenSSL v3.0.2`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 08:01 UTC, anjalirai-intel commented
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWJ2yEYSMR3YaBwHc):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`for` -> `on`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 08:01 UTC, anjalirai-intel commented
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWLTX3xW2_LIyaM92):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will remove this last sentence, it doesn't give any interesting information.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 08:12 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1047#-NGzWLTX3xW2_LIyaM92):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. I meant the "Nginx make kept failing ..."


<!-- Sent from Reviewable.io -->

2022-11-22 09:08 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-11-22 09:08 UTC, dimakuv commented
Jenkins, test this please

2022-11-22 09:11 UTC, dimakuv commented
Jenkins, test this please

2022-11-22 10:24 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-22 11:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-11-22 11:55 UTC, dimakuv commented
Jenkins, test this please

2022-11-22 11:59 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-22 13:21 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1047)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-22 14:55 UTC, merged