Change the default from `sgx.debug = 1` to `sgx.debug = 0`
gramineproject/gramine pull request #105
Opened 2021-09-30 12:59 UTC by dimakuv

## Description of the changes 

From now on, Gramine creates manifest files with `sgx.debug = 0` by default, i.e., Gramine creates production enclaves by default.

All tests and examples that we frequently use for debugging are augmented with `sgx.debug = 1` for ease of debugging.

## How to test this PR? 

All tests should still pass (some tests explicitly depend on `sgx.debug = 1`).

2021-09-30 17:31 UTC, boryspoplawski requested changes
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkrjxq19La9LPEbsaFC):*
Shouldn't this be prefixed with `[Pal/Linux-SGX]` ?
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkrk6vl6f8shTwiEshC):*
s/1/true
s/0/false
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-MkrkARNCw9fmHF3OUak):*
ditto
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-MkrkB5HEdKeD5shwa_h):*
ditto


<!-- Sent from Reviewable.io -->

2021-10-01 07:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkrjxq19La9LPEbsaFC):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be prefixed with `[Pal/Linux-SGX]` ?
</blockquote></details>

Done.
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkrk6vl6f8shTwiEshC):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

s/1/true
s/0/false
</blockquote></details>

Done.
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-MkrkARNCw9fmHF3OUak):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/105#-MkrkB5HEdKeD5shwa_h):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 12:48 UTC, mkow submitted a review, later dismissed
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-10-01 13:02 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-01 13:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: 44 of 45 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Documentation/manifest-syntax.rst, line 370 at r3](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkw5inD-xhRTFzq632C:-Mkw5inD-xhRTFzq632D:b-y4se4p) ([raw file](https://github.com/gramineproject/gramine/blob/53395c6216a388b3533bfde1de39dff851097a7c/Documentation/manifest-syntax.rst#L370)):*
> ```reStructuredText
> 
>     sgx.debug = [true|false]
>     (Default: false)
> ```

FYI: Forgot to update before, so did it now during the final rebase.


<!-- Sent from Reviewable.io -->

2021-10-01 13:51 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-10-01 13:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/105)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Documentation/manifest-syntax.rst, line 370 at r3](https://reviewable.io/reviews/gramineproject/gramine/105#-Mkw5inD-xhRTFzq632C:-Mkw7IeY5Mp_QA_z6YzY:b-452plw) ([raw file](https://github.com/gramineproject/gramine/blob/53395c6216a388b3533bfde1de39dff851097a7c/Documentation/manifest-syntax.rst#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Forgot to update before, so did it now during the final rebase.
</blockquote></details>

Good catch, I also missed this.


<!-- Sent from Reviewable.io -->

2021-10-01 15:35 UTC, merged