[Libos,PAL] Reduce lock contention caused by malloc() in poll
gramineproject/gramine pull request #1051
Opened 2022-11-17 09:16 UTC by lejunzhu

## Description of the changes
Current implementation of poll syscall uses multiple malloc and free. When the number of threads calling poll is high, the lock contention limits the application performance. This PR tries to use stack space when the space being allocated is small, and reduces such lock contention.

## How to test this PR?
Run the MySQL example on one server and use Sysbench to test it from another. When the number of threads in Sysbench is set to 128, the result TPS is >50% better than the original code.

2022-11-17 10:39 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @lejunzhu)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49tIT5H7lobIek1wJ):*
`LibOS`
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49vTP8elnRiXPItkq):*
`poll/select syscalls`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49yr-Bq1wwmBCLAfS):*
`This commit uses the stack ...`
___
*[`common/include/api.h` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48NDYCR2TLVXjYlNB:-NH48NDYCR2TLVXjYlNC:bxwhnlo) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/common/include/api.h#L448)):*
> ```objc
>         if (sz > STACK_BUF_MAX) {               \
>             name##__on_stack = false;           \
>             name = malloc(sz);                  \
> ```

You're mixing `calloc` and `malloc`/`alloca` functionality -- these funcs have different semantics, and this may lead to hard-to-find bugs. Please don't do it.
___
*[`common/include/api.h` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48ANW3kdlQvHh1-gH:-NH48ANW3kdlQvHh1-gI:b-j428w) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/common/include/api.h#L460)):*
> ```objc
>             free(name);                 \
>         }                               \
>     } while (0)
> ```

Please remove it. I'm very much against such macros -- they are very hard to reason about (it introduces a helper `bool` object).
___
*[`libos/src/sys/libos_poll.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48XFb9kgGr03edlSc:-NH48XFb9kgGr03edlSd:bbebqec) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/libos/src/sys/libos_poll.c#L51)):*
> ```C
> 
>     /* nfds is the upper limit for actual number of handles */
>     CALLOC_STACK(PAL_HANDLE, pals, nfds);
> ```

Please inline the macro logic everywhere in this PR. Yes, it will be a bit redundant, but it will be much more readable and future-proof.

I would recommend smth like this:
```
PAL_HANDLE* pals = NULL;
struct fds_mapping_t* fds_mapping = NULL;
pal_wait_flags_t* pal_events = NULL;
bool allocated_on_stack = false;

/* please some comment on how the limit is chosen and how much stack will be consumed in the worst case */
if (nfds < SOME_MACRO_LIMIT) {
    pals = __builtin_alloca(nfds * sizeof(*pals));
    fds_mapping = __builtin_alloca(nfds * sizeof(*fds_mapping));
    pal_events = __builtin_alloca(nfds * sizeof(*pal_events) * 2);
    allocated_on_stack = true;
} else {
    pals = malloc(nfds * sizeof(*pals));
    fds_mapping = malloc(nfds * sizeof(*fds_mapping));
    pal_events = malloc(nfds * sizeof(*pal_events) * 2);
    if (!pals || !fds_mapping || !pal_events) {
        free(pals);
        free(fds_mapping);
        free(pal_events);
    }
}

... when need to remove, smth like this:
if (!allocated_on_stack) {
        free(pals);
        free(fds_mapping);
        free(pal_events);
}
```
___
*[`pal/src/host/linux/pal_object.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49nb0ALi9KT38aOiR:-NH49nb0ALi9KT38aOiS:bvzunou) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/pal/src/host/linux/pal_object.c#L23)):*
> ```C
>         return 0;
> 
>     CALLOC_STACK(struct pollfd, fds, count);
> ```

ditto (use proper code instead of the macro)
___
*[`pal/src/host/linux-sgx/pal_object.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49q_lBJ-Sfofz-ssM:-NH49q_lBJ-Sfofz-ssN:bvzunou) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/pal/src/host/linux-sgx/pal_object.c#L21)):*
> ```C
>         return 0;
> 
>     CALLOC_STACK(struct pollfd, fds, count);
> ```

ditto (use proper code instead of the macro)


<!-- Sent from Reviewable.io -->

2022-11-18 01:33 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 0 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49tIT5H7lobIek1wJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`LibOS`
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49vTP8elnRiXPItkq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`poll/select syscalls`
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49yr-Bq1wwmBCLAfS):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This commit uses the stack ...`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48XFb9kgGr03edlSc:-NH7MPNEDUciq5CkWFJ5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/libos/src/sys/libos_poll.c#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please inline the macro logic everywhere in this PR. Yes, it will be a bit redundant, but it will be much more readable and future-proof.

I would recommend smth like this:
```
PAL_HANDLE* pals = NULL;
struct fds_mapping_t* fds_mapping = NULL;
pal_wait_flags_t* pal_events = NULL;
bool allocated_on_stack = false;

/* please some comment on how the limit is chosen and how much stack will be consumed in the worst case */
if (nfds < SOME_MACRO_LIMIT) {
    pals = __builtin_alloca(nfds * sizeof(*pals));
    fds_mapping = __builtin_alloca(nfds * sizeof(*fds_mapping));
    pal_events = __builtin_alloca(nfds * sizeof(*pal_events) * 2);
    allocated_on_stack = true;
} else {
    pals = malloc(nfds * sizeof(*pals));
    fds_mapping = malloc(nfds * sizeof(*fds_mapping));
    pal_events = malloc(nfds * sizeof(*pal_events) * 2);
    if (!pals || !fds_mapping || !pal_events) {
        free(pals);
        free(fds_mapping);
        free(pal_events);
    }
}

... when need to remove, smth like this:
if (!allocated_on_stack) {
        free(pals);
        free(fds_mapping);
        free(pal_events);
}
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49nb0ALi9KT38aOiR:-NH7MSfbAe0C5eqPue2g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/pal/src/host/linux/pal_object.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (use proper code instead of the macro)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH49q_lBJ-Sfofz-ssM:-NH7MTIg-PqizBlipTSd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/pal/src/host/linux-sgx/pal_object.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (use proper code instead of the macro)
</blockquote></details>

Done.
___
*[`common/include/api.h` line 448 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48NDYCR2TLVXjYlNB:-NH7MVJ-8S04PlCEeS13:bkmenr0) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/common/include/api.h#L448)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're mixing `calloc` and `malloc`/`alloca` functionality -- these funcs have different semantics, and this may lead to hard-to-find bugs. Please don't do it.
</blockquote></details>

The macro is removed.
___
*[`common/include/api.h` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH48ANW3kdlQvHh1-gH:-NH7MUgpAncnyVXicvnL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d1787ea8c0aca4d995c703cf5baa31daf092ad0/common/include/api.h#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove it. I'm very much against such macros -- they are very hard to reason about (it introduces a helper `bool` object).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-18 10:17 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @lejunzhu)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9BjgADLcmRT4UEY-7):*
Reminder to myself: use this commit message instead of the first one during final rebase.
___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CIKgDbWJqR1Ne5Ui:-NH9CIKgDbWJqR1Ne5Uj:b-xqxaos) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
> ```C
>  * required space is small enough.
>  * Each fd will use 48 bytes in libos_syscall_select, _libos_syscall_poll and
>  * _PalStreamsWaitEvents, therefore 16 fd will use less than 1K stack space. */
> ```

```
/* To avoid expensive malloc/free (due to locking), use stack if the required space is small enough.
 * Each FD uses 48B of space, so 16 FDs use less than 1K stack space. */
```
___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DcXV1bEsZBD5H8OM:-NH9DcXV1bEsZBD5H8ON:b-szny37) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
> ```C
>  * required space is small enough.
>  * Each fd will use 48 bytes in libos_syscall_select, _libos_syscall_poll and
>  * _PalStreamsWaitEvents, therefore 16 fd will use less than 1K stack space. */
> ```

Actually, how is this calculation true for **all** cases in this PR? Clearly, `_libos_syscall_poll()` requires more memory than `libos_syscall_select`.

Please move this comment about "Each FD uses ..." to each actual usage, and count the number of bytes required for each usage.
___
*[`libos/src/sys/libos_poll.c` line 48 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9C9lPCj-QVPTIrkGH:-NH9C9lPCj-QVPTIrkGI:b-5fwmp0) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L48)):*
> ```C
>  * Each fd will use 48 bytes in libos_syscall_select, _libos_syscall_poll and
>  * _PalStreamsWaitEvents, therefore 16 fd will use less than 1K stack space. */
> #define MAX_FD_TO_USE_STACK     16
> ```

I suggest `NFDS_LIMIT_TO_USE_STACK 16`

Also, please remove redundant spaces
___
*[`libos/src/sys/libos_poll.c` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9Cq1Z3AOmHNA3LpXk:-NH9Cq1Z3AOmHNA3LpXl:bvfv8mc) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L70)):*
> ```C
>     if (nfds <= MAX_FD_TO_USE_STACK) {
>         allocated_on_stack = true;
>         pals = __builtin_alloca(nfds * sizeof(PAL_HANDLE));
> ```

`sizeof(*pals)`
___
*[`libos/src/sys/libos_poll.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CtH5-yAwCjy_MSw2:-NH9CtH5-yAwCjy_MSw3:b8k4zxi) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L71)):*
> ```C
>         allocated_on_stack = true;
>         pals = __builtin_alloca(nfds * sizeof(PAL_HANDLE));
>         fds_mapping = __builtin_alloca(nfds * sizeof(struct fds_mapping_t));
> ```

`sizeof(*fds_mapping)`
___
*[`libos/src/sys/libos_poll.c` line 76 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9D-wgDjnChoOp1leI:-NH9D-wgDjnChoOp1leJ:bp4mbjs) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L76)):*
> ```C
>         pals = malloc(nfds * sizeof(PAL_HANDLE));
>         if (!pals)
>             return -ENOMEM;
> ```

Why this? Just re-group as I showed in my code snippet (first all 3 mallocs, then all 3 checks). It's perfectly legal to group mallocs together.
___
*[`libos/src/sys/libos_poll.c` line 277 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DNuQ5COhE_s_tL1V:-NH9DNuQ5COhE_s_tL1W:bcddbjp) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L277)):*
> ```C
>     if (nfds <= MAX_FD_TO_USE_STACK) {
>         allocated_on_stack = true;
>         fds_poll = __builtin_alloca(nfds * sizeof(struct pollfd));
> ```

`sizeof(*fds_poll)`
___
*[`libos/src/sys/libos_poll.c` line 279 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DPqRDhd-gTCnrqg8:-NH9DPqSASCEAdyJMV6N:bcddbjp) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L279)):*
> ```C
>         fds_poll = __builtin_alloca(nfds * sizeof(struct pollfd));
>     } else {
>         fds_poll = malloc(nfds * sizeof(struct pollfd));
> ```

`sizeof(*fds_poll)`
___
*[`pal/src/host/linux/pal_object.c` line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DxpVC_GwnYTyqRS7:-NH9DxpVC_GwnYTyqRS8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L19)):*
> ```C
>  * Each fd will use 48 bytes in libos_syscall_select, _libos_syscall_poll and
>  * _PalStreamsWaitEvents, therefore 16 fd will use less than 1K stack space. */
> #define MAX_FD_TO_USE_STACK     16
> ```

ditto
___
*[`pal/src/host/linux/pal_object.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9E4AJ-hubfI9M294s:-NH9E4AJ-hubfI9M294t:by9t5as) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L31)):*
> ```C
>     struct pollfd* fds = NULL;
>     bool allocated_on_stack = false;
>     
> ```

Remove whitespace
___
*[`pal/src/host/linux/pal_object.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EOz85AT1iUs3PW0s:-NH9EOz85AT1iUs3PW0t:b-zhph0l) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L35)):*
> ```C
>         allocated_on_stack = true;
>         fds = __builtin_alloca(count * sizeof(*fds));
>         memset(fds, 0, count * sizeof(*fds));
> ```

I would suggest to move this out of the `if`, and replace `calloc()` with `malloc()`
___
*[`pal/src/host/linux-sgx/pal_object.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EBxF7_6fV73RTkxX:-NH9EBxF7_6fV73RTkxY:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L20)):*
> ```C
>  * Each fd will use 48 bytes in libos_syscall_select, _libos_syscall_poll and
>  * _PalStreamsWaitEvents, therefore 16 fd will use less than 1K stack space. */
> #define MAX_FD_TO_USE_STACK     16
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9ED4R3qbHysmzQo5O:-NH9ED4R3qbHysmzQo5P:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L29)):*
> ```C
>     struct pollfd* fds = NULL;
>     bool allocated_on_stack = false;
>     
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EVSG3Ww-2fR5KoTQ:-NH9EVSG3Ww-2fR5KoTR:b-zhph0l) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L33)):*
> ```C
>         allocated_on_stack = true;
>         fds = __builtin_alloca(count * sizeof(*fds));
>         memset(fds, 0, count * sizeof(*fds));
> ```

I would sugge [...]

2022-11-19 02:25 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 1 of 4 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DcXV1bEsZBD5H8OM:-NHCaj5w5xGxtJ-lGs8J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, how is this calculation true for **all** cases in this PR? Clearly, `_libos_syscall_poll()` requires more memory than `libos_syscall_select`.

Please move this comment about "Each FD uses ..." to each actual usage, and count the number of bytes required for each usage.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CIKgDbWJqR1Ne5Ui:-NHCh742CUy2CmF5cL4f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
/* To avoid expensive malloc/free (due to locking), use stack if the required space is small enough.
 * Each FD uses 48B of space, so 16 FDs use less than 1K stack space. */
```
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 48 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9C9lPCj-QVPTIrkGH:-NHCaiT205SWm6BOFxr2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest `NFDS_LIMIT_TO_USE_STACK 16`

Also, please remove redundant spaces
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9Cq1Z3AOmHNA3LpXk:-NHCakTCAJnYn1LpQ_hD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(*pals)`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CtH5-yAwCjy_MSw2:-NHCaky8-pmrVMLgB8FT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(*fds_mapping)`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 76 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9D-wgDjnChoOp1leI:-NHCalnYD0xsV21vqfdt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this? Just re-group as I showed in my code snippet (first all 3 mallocs, then all 3 checks). It's perfectly legal to group mallocs together.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 277 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DNuQ5COhE_s_tL1V:-NHCbIN_6k1Td08oeorF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L277)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(*fds_poll)`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 279 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DPqRDhd-gTCnrqg8:-NHCbJEb1JUQV0NypbvY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(*fds_poll)`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DxpVC_GwnYTyqRS7:-NHCbKJ113BWkZdJ3Cnh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9E4AJ-hubfI9M294s:-NHCbih79Rp0PPt8Pwmo:baza7ln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove whitespace
</blockquote></details>

Do you mean this line "bool allocated_on_stack = false;" has extra whitespace?
___
*[`pal/src/host/linux/pal_object.c` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EOz85AT1iUs3PW0s:-NHCc2Rc2x1T-ItTwNEj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would suggest to move this out of the `if`, and replace `calloc()` with `malloc()`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EBxF7_6fV73RTkxX:-NHCc1t6690O0asJdNKp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EVSG3Ww-2fR5KoTQ:-NHCc0me3aZfCjrWM8cu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would suggest to move this out of the `if`, and replace `calloc()` with `malloc()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-21 08:02 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)

___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CIKgDbWJqR1Ne5Ui:-NHOB7g229DxlOhqKGPg:b4mjtdr) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? The first sentence wasn't changed.
___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DcXV1bEsZBD5H8OM:-NHOBFDADJdPkNQA1j6F:b-7r90fl) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? I wanted you to also remove the second sentence ("Each FD uses ...") from this top-level comment.
___
*[`pal/src/host/linux/pal_object.c` line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DxpVC_GwnYTyqRS7:-NHOC14OA7i6AYGMdXgZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L19)):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[`pal/src/host/linux/pal_object.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9E4AJ-hubfI9M294s:-NHOC3FX6h3PCBwmx8q7:b-tpskso) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L31)):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Do you mean this line "bool allocated_on_stack = false;" has extra whitespace?
</blockquote></details>

No, that the empty line has extra whitespaces. If you use Reviewable, you see these whitespaces as red dots.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EBxF7_6fV73RTkxX:-NHOCM-r1BQHU-g1UJ_1:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L20)):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-11-21 08:17 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9CIKgDbWJqR1Ne5Ui:-NHOE7Br1q2ty6_x8R2G:b3jtibs) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done? The first sentence wasn't changed.
</blockquote></details>

Sorry I missed it. It is changed now.
___
*[`libos/src/sys/libos_poll.c` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DcXV1bEsZBD5H8OM:-NHOEXLu0a48u4osei8_:bpu9uz4) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done? I wanted you to also remove the second sentence ("Each FD uses ...") from this top-level comment.
</blockquote></details>

The second line is removed.
___
*[`pal/src/host/linux/pal_object.c` line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9DxpVC_GwnYTyqRS7:-NHOEfML8qaAlyasl1kJ:bbatxle) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

The first line is changed, and the second line is removed.
___
*[`pal/src/host/linux/pal_object.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9E4AJ-hubfI9M294s:-NHOFol38A1O-4zrkqKd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux/pal_object.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, that the empty line has extra whitespaces. If you use Reviewable, you see these whitespaces as red dots.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9EBxF7_6fV73RTkxX:-NHOElZ597AtmNBxjxRM:bbatxle) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

The first line is changed, and the second line is removed.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NH9ED4R3qbHysmzQo5O:-NHOFnbjCGmT-d4BR-Ll:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/pal/src/host/linux-sgx/pal_object.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-01 09:41 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "Merge branch '" found in commit messages' one-liners (waiting on @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIC2z-13TLfDr31DFdL:-NIC2z-13TLfDr31DFdM:b6dpdb6) (no related file):*
@lejunzhu @boryspoplawski Could you agree on how this PR should be connected to https://github.com/gramineproject/gramine/pull/1067 ?

___
___
*[`-- commits` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIC2Yyx-5epPYCDU9uN):*
Please never use a `git merge` flow! See https://gramine.readthedocs.io/en/latest/devel/onboarding.html#pre-requisite-knowledge (search for `merge` word).
___
*[`libos/src/sys/libos_poll.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgbNx5NaaSDmAdzGD:-NHOgbNx5NaaSDmAdzGE:b-3zknnk) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L62)):*
> ```C
>         struct libos_handle* hdl; /* NULL if no mapping (handle is not used in polling) */
>         nfds_t idx;               /* index from fds array to pals array */
>     };
> ```

Could you move this struct declaration before `/* nfds is the upper limit ... */`? Otherwise it breaks the flow.
___
*[`libos/src/sys/libos_poll.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgJkMBZIAq4F-R0yg:-NHOgJkMBZIAq4F-R0yh:b-6yswgj) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L64)):*
> ```C
>     };
>     struct fds_mapping_t* fds_mapping = NULL;
>     /* allocate one memory region to hold two pal_wait_flags_t arrays: events and revents */
> ```

Just noticed: this comment is stale now. Please rephrase to this:
```
    pal_wait_flags_t* pal_events = NULL; /* holds two arrays: events and revents */
```
___
*[`libos/src/sys/libos_poll.c` line 67 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgqiw5Eg_ugO4s08g:-NHOgqiw5Eg_ugO4s08h:bjp7fy1) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/libos/src/sys/libos_poll.c#L67)):*
> ```C
> 
>     if (nfds <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Here, each FD uses 8+16+4*2=32 bytes on stack */
> ```

Please remove `Here,`
___
*[`libos/src/sys/libos_poll.c` line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgzSk1HbS-qdOM2OV:-NHOgzSk1HbS-qdOM2OW:bjp7fy1) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/libos/src/sys/libos_poll.c#L268)):*
> ```C
> 
>     if (nfds <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Here, each FD uses 8 bytes on stack */
> ```

Please remove `Here,`
___
*[`pal/src/host/linux/pal_object.c` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOh4iq-vUoKJl1nXNb:-NHOh4iq-vUoKJl1nXNc:bjp7fy1) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/pal/src/host/linux/pal_object.c#L31)):*
> ```C
> 
>     if (count <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Here, each FD uses 8 bytes on stack */
> ```

Please remove `Here,`
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOhAO8ERQfQx7erJTl:-NHOhAO8ERQfQx7erJTm:bjp7fy1) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/pal/src/host/linux-sgx/pal_object.c#L29)):*
> ```C
> 
>     if (count <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Here, each FD uses 8 bytes on stack */
> ```

Please remove `Here,`


<!-- Sent from Reviewable.io -->

2022-12-01 10:44 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 1 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIC2Yyx-5epPYCDU9uN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please never use a `git merge` flow! See https://gramine.readthedocs.io/en/latest/devel/onboarding.html#pre-requisite-knowledge (search for `merge` word).
</blockquote></details>

Sorry I accidentally hit the button. I am trying to fix it by a force push.
___
*[`libos/src/sys/libos_poll.c` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgbNx5NaaSDmAdzGD:-NICBRf5BFeuyc7VqBxL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move this struct declaration before `/* nfds is the upper limit ... */`? Otherwise it breaks the flow.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgJkMBZIAq4F-R0yg:-NICBK6N0_9pQXZuZrlv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b2fbf07bdc6713a2075b9ef06223da3a66e13a9b/libos/src/sys/libos_poll.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed: this comment is stale now. Please rephrase to this:
```
    pal_wait_flags_t* pal_events = NULL; /* holds two arrays: events and revents */
```
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 67 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgqiw5Eg_ugO4s08g:-NICB-cE0sS4TRbYrueZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/libos/src/sys/libos_poll.c#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Here,`
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOgzSk1HbS-qdOM2OV:-NICB0VzAm6gkD2Zyfni:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/libos/src/sys/libos_poll.c#L268)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Here,`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOh4iq-vUoKJl1nXNb:-NICAr6MCtzxn79Cjh_t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/pal/src/host/linux/pal_object.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Here,`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r4](https://reviewable.io/reviews/gramineproject/gramine/1051#-NHOhAO8ERQfQx7erJTl:-NICAlCHAim3tJRO5qE_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/88bf9e8bbbd254dd0a21f3e231e62c34dec7b9db/pal/src/host/linux-sgx/pal_object.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Here,`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-01 11:10 UTC, lejunzhu commented
@boryspoplawski I just noticed you are changing select/poll with #1067. Is it possible to reduce malloc usage in your rewritten code? If so, I can drop this PR. I can also wait and rebase to the new code. What is your suggestion? Thanks.

2022-12-01 11:58 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)



<!-- Sent from Reviewable.io -->

2022-12-01 22:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIEsIrw0QtIe25NLjKs:-NIEsIrw0QtIe25NLjKt:bflszjb) (no related file):*
> @boryspoplawski I just noticed you are changing select/poll with #1067. Is it possible to reduce malloc usage in your rewritten code? If so, I can drop this PR. I can also wait and rebase to the new code. What is your suggestion? Thanks.

I did not touch that part at all (i.e. I've left simple `malloc` calls), so I guess we could rebase this PR after we merge 1067? Or we could proceed with this one and then I would pick them once 1067 is accepted and we rebase it.
I don't mind either.
BTW, I've not reviewed this PR yet, so no idea how for from merging it is

___


<!-- Sent from Reviewable.io -->

2022-12-02 05:43 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)

___
*[`libos/src/sys/libos_poll.c` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIGKiFm-duWd2_JAiCa:-NIGKiFm-duWd2_JAiCb:banl3jg) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/libos/src/sys/libos_poll.c#L46)):*
> ```C
> /* To avoid expensive malloc/free (due to locking), use stack if the required
>  * space is small enough. */
> #define NFDS_LIMIT_TO_USE_STACK 16
> ```

Although this is based on stack size, do you have (any rough) idea about the application use?
If useful app like mysql requires more  (too large to stack), for example per-thread buffer stashing would be better.


<!-- Sent from Reviewable.io -->

2022-12-02 06:23 UTC, lejunzhu commented
> Although this is based on stack size, do you have (any rough) idea about the application use? If useful app like mysql requires more (too large to stack), for example per-thread buffer stashing would be better.

From my test of MySQL using sysbench, nfds = 2 is the only case that leads to heavy lock contention in this code path.

2022-12-28 00:35 UTC, boryspoplawski requested changes
> Reviewed 1 of 4 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)

___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
These threads do not have to call `poll`, it's enough they call `malloc`/`free` in any syscall.
___
*[`-- commits` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5X8B6zWn1NJHL5ZA):*
This needs to be squashed
___
*[`libos/src/sys/libos_poll.c` line 66 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL6dTuB71Qz597eLuR:-NKL6dTuB71Qz597eLuS:b-l8ey6v) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/libos/src/sys/libos_poll.c#L66)):*
> ```C
> 
>     if (nfds <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8+16+4*2=32 bytes on stack */
> ```

Please add
`static_assert((sizeof(*pals) + sizeof(*fds_mapping) + sizeof(*pal_events) * 2) * NFDS_LIMIT_TO_USE_STACK <= X)`, where X is some constant value which is considered our threshold (idk what exact value we should use, current minimal is 0x200).
___
*[`libos/src/sys/libos_poll.c` line 267 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL7hpt2dTGKmeHgMmD:-NKL7hpt2dTGKmeHgMmE:b-bhfum9) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/libos/src/sys/libos_poll.c#L267)):*
> ```C
> 
>     if (nfds <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8 bytes on stack */
> ```

ditto (static_assert)
___
*[`pal/src/host/linux/pal_object.c` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL8MDn40Qb69zFfpqx:-NKL8MDn40Qb69zFfpqy:b-q8m9p3) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/pal/src/host/linux/pal_object.c#L17)):*
> ```C
> /* To avoid expensive malloc/free (due to locking), use stack if the required
>  * space is small enough. */
> #define NFDS_LIMIT_TO_USE_STACK 16
> ```

Note that the stack used by this and LibOS poll implementation is the very same stack.
___
*[`pal/src/host/linux/pal_object.c` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL80ye4a1jbKXXjTHW:-NKL80ye4a1jbKXXjTHX:b-bhfum9) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/pal/src/host/linux/pal_object.c#L31)):*
> ```C
> 
>     if (count <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8 bytes on stack */
> ```

ditto (static_assert)
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL8UMl51OUOA_V9CZw:-NKL8UMl51OUOA_V9CZx:b-bhfum9) ([raw file](https://github.com/gramineproject/gramine/blob/68496fe3bb0d881826bc8b91e10a041d372b8748/pal/src/host/linux-sgx/pal_object.c#L29)):*
> ```C
> 
>     if (count <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8 bytes on stack */
> ```

ditto (static_assert)


<!-- Sent from Reviewable.io -->

2022-12-28 07:08 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 1 of 4 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These threads do not have to call `poll`, it's enough they call `malloc`/`free` in any syscall.
</blockquote></details>

Yes. But my patch only works for threads calling poll. If they call malloc from another code path, they will not benefit from this patch.
___
*[`-- commits` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5X8B6zWn1NJHL5ZA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This needs to be squashed
</blockquote></details>

Should I squash all fixups now, or when all the reviews are done? I'm not familiar with the rule...
___
*[`libos/src/sys/libos_poll.c` line 66 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL6dTuB71Qz597eLuR:-NKMUEoZApW1dVx0pN7P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/libos/src/sys/libos_poll.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add
`static_assert((sizeof(*pals) + sizeof(*fds_mapping) + sizeof(*pal_events) * 2) * NFDS_LIMIT_TO_USE_STACK <= X)`, where X is some constant value which is considered our threshold (idk what exact value we should use, current minimal is 0x200).
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 267 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL7hpt2dTGKmeHgMmD:-NKMU_zC4yR2mSbN3vdn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/libos/src/sys/libos_poll.c#L267)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (static_assert)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL8MDn40Qb69zFfpqx:-NKMV5ma1CA5gtESeBwq:b-3j0zv4) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/pal/src/host/linux/pal_object.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Note that the stack used by this and LibOS poll implementation is the very same stack.
</blockquote></details>

For worst case, each FD will use 48 bytes (adding all functions in this patch together) on stack. So 16 FD are less than 1K bytes.
___
*[`pal/src/host/linux/pal_object.c` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL80ye4a1jbKXXjTHW:-NKMVht14J2qJLMtAbTL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/pal/src/host/linux/pal_object.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (static_assert)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL8UMl51OUOA_V9CZw:-NKMVjDT6As5WIuQB4qq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/pal/src/host/linux-sgx/pal_object.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (static_assert)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 14:49 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIEsIrw0QtIe25NLjKs:-NKmv9GKEWeUZMp8_M-B:b-eewm5t) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> @boryspoplawski I just noticed you are changing select/poll with #1067. Is it possible to reduce malloc usage in your rewritten code? If so, I can drop this PR. I can also wait and rebase to the new code. What is your suggestion? Thanks.

I did not touch that part at all (i.e. I've left simple `malloc` calls), so I guess we could rebase this PR after we merge 1067? Or we could proceed with this one and then I would pick them once 1067 is accepted and we rebase it.
I don't mind either.
BTW, I've not reviewed this PR yet, so no idea how for from merging it is
</blockquote></details>

We will do #1067 first, and then we can rebase this PR on top of that one.

Blocking until #1067 is merged.

___
___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Yes. But my patch only works for threads calling poll. If they call malloc from another code path, they will not benefit from this patch.
</blockquote></details>

I guess Borys just wanted to be more specific in this particular sentence. But I wouldn't modify the commit message, it's obvious what is meant here.
___
*[`-- commits` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5X8B6zWn1NJHL5ZA):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Should I squash all fixups now, or when all the reviews are done? I'm not familiar with the rule...
</blockquote></details>

Please do *not* squash now. Only after the reviews are done.
___
*[`libos/src/sys/libos_poll.c` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIGKiFm-duWd2_JAiCa:-NKmwMQ_AsBHiI_4vdh5:b-xb3s2v) ([raw file](https://github.com/gramineproject/gramine/blob/5919389f4c5f3c916b0a6677e57c40d2ac9d2341/libos/src/sys/libos_poll.c#L46)):*
@lejunzhu Please use Reviewable to reply to comments.

The reply that @lejunzhu left on GitHub is like this:

> From my test of MySQL using sysbench, nfds = 2 is the only case that leads to heavy lock contention in this code path.

So the typical "bad performance" case seems to be when there are 2-4 FDs.
___
*[`libos/src/sys/libos_poll.c` line 67 at r6](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKmwlwX3uSX7IJckzgO:-NKmwlwX3uSX7IJckzgP:bdxlzu3) ([raw file](https://github.com/gramineproject/gramine/blob/9e75e05731e6940515ef7ac23c9879614ec9f563/libos/src/sys/libos_poll.c#L67)):*
> ```C
>     if (nfds <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8+16+4*2=32 bytes on stack */
>         static_assert((sizeof(*pals) + sizeof(*fds_mapping) + sizeof(*pal_events) * 2) * 
> ```

Please remove redundant trailing whitespace.


<!-- Sent from Reviewable.io -->

2023-01-02 21:25 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lejunzhu)

___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess Borys just wanted to be more specific in this particular sentence. But I wouldn't modify the commit message, it's obvious what is meant here.
</blockquote></details>

But other code paths also befit from this if they call malloc anywhere, as long as at least one thread calls poll. It's not just (malloc in) poll vs poll, it's also poll vs other places.


<!-- Sent from Reviewable.io -->

2023-01-03 08:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lejunzhu)

___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But other code paths also befit from this if they call malloc anywhere, as long as at least one thread calls poll. It's not just (malloc in) poll vs poll, it's also poll vs other places.
</blockquote></details>

Yes, I understand your point. Just didn't feel like we need to be *that* pedantic here. But ok, maybe we rephrase to this:
```
  ...
  When there is at least one thread calling poll frequently and other threads calling
  malloc/free (possibly in other syscalls), the lock contention on malloc/free limits
  the application performance. This commit uses the stack space when the space
  ...
```


<!-- Sent from Reviewable.io -->

2023-01-04 06:49 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 3 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKL5m5D68OYCGi8OAy-):*
>   When there is at least one thread calling poll frequently and other threads calling
>   malloc/free (possibly in other syscalls), the lock contention on malloc/free limits
>   the application performance. This commit uses the stack space when the space

I've updated the commit message with this sentence. Please use this one.
___
*[`libos/src/sys/libos_poll.c` line 67 at r6](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKmwlwX3uSX7IJckzgO:-NKvXQX24X833nTw72nT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e75e05731e6940515ef7ac23c9879614ec9f563/libos/src/sys/libos_poll.c#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove redundant trailing whitespace.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-04 08:55 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @lejunzhu)

___
*[`-- commits` line 44 at r7](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKvzVOcDCDQbtMfPCSu):*
Reminder to myself: use this commit message during final rebase.


<!-- Sent from Reviewable.io -->

2023-01-06 09:49 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIEsIrw0QtIe25NLjKs:-NL5U1Y3BPoaJKhAVugH:bk00ybj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We will do #1067 first, and then we can rebase this PR on top of that one.

Blocking until #1067 is merged.
</blockquote></details>

@lejunzhu #1067 was merged now, could you rebase your PR on top of the latest master? Feel free to squash all fixup commits into one commit as well.

___


<!-- Sent from Reviewable.io -->

2023-01-10 03:17 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 1 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIEsIrw0QtIe25NLjKs:-NLOfklQ40586bXrjIa7:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@lejunzhu #1067 was merged now, could you rebase your PR on top of the latest master? Feel free to squash all fixup commits into one commit as well.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-01-10 09:56 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NIEsIrw0QtIe25NLjKs:-NLQ62UiBr5DUxl-eK3n:bbvb420) (no related file):*
<details><summary><i>Previously, lejunzhu wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, looks good to me

___
___
*[`-- commits` line 44 at r7](https://reviewable.io/reviews/gramineproject/gramine/1051#-NKvzVOcDCDQbtMfPCSu):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Reminder to myself: use this commit message during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-10 09:57 UTC, dimakuv commented
Jenkins, test this please

2023-01-12 02:30 UTC, mkow requested changes
> Reviewed 1 of 4 files at r2, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @lejunzhu)

___
*[`libos/src/sys/libos_poll.c` line 48 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYl1N2DmU-8fSmYQWV:-NLYl1N2DmU-8fSmYQWW:b-o05tfu) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L48)):*
> ```C
> #define POLLEX_SET (POLLPRI)
> /* To avoid expensive malloc/free (due to locking), use stack if the required
>  * space is small enough. */
> ```

we wrap on 100 chars
___
*[`libos/src/sys/libos_poll.c` line 58 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYjEu9C1hFijNXnai4:-NLYjEu9C1hFijNXnai5:b-ct7jae) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L58)):*
> ```C
>     bool allocated_on_stack = false;
> 
>     if (fds_len <= NFDS_LIMIT_TO_USE_STACK) {
> ```

Readability suggestion: This makes the IF more symmetric (in your version one side sets `allocated_on_stack` and the other not, which on first read looked like you forgot to set it.



_Suggestion:_
```C
    bool allocate_on_stack = fds_len <= NFDS_LIMIT_TO_USE_STACK;

    if (allocate_on_stack) {
```
___
*[`libos/src/sys/libos_poll.c` line 62 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYgjpsDo20Lk7i_auU:-NLYgjpsDo20Lk7i_auV:b-a7llu6) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L62)):*
> ```C
>         static_assert((sizeof(*libos_handles) + sizeof(*pal_handles) + sizeof(*pal_events) * 2) *
>                       NFDS_LIMIT_TO_USE_STACK <= 384,
>                       "use too much space on stack, reduce the limit");
> ```

"use too much space" is in imperative mood and means a different thing than you (as I guess) intended.



_Suggestion:_
```C
Would use too much space on stack, reduce the limit
```
___
*[`libos/src/sys/libos_poll.c` line 288 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYjv1xA1zbKcKcmaQV:-NLYjv1xA1zbKcKcmaQW:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L288)):*
> ```C
> 
>     struct pollfd* poll_fds = NULL;
>     bool allocated_on_stack = false;
> ```

ditto
___
*[`libos/src/sys/libos_poll.c` line 293 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYkJnb50MLr44f9Wz0:-NLYkJnb50MLr44f9Wz1:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L293)):*
> ```C
>         /* Each FD uses 8 bytes on stack */
>         static_assert(sizeof(*poll_fds) * NFDS_LIMIT_TO_USE_STACK <= 128,
>                       "use too much space on stack, reduce the limit");
> ```

ditto
___
*[`pal/src/host/linux/pal_object.c` line 16 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYkwQi2bjtLh63PUng:-NLYkwQi2bjtLh63PUnh:b-o05tfu) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L16)):*
> ```C
> 
> /* To avoid expensive malloc/free (due to locking), use stack if the required
>  * space is small enough. */
> ```

we wrap on 100 chars
___
*[`pal/src/host/linux/pal_object.c` line 25 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYlRooCQwgts_hbWwc:-NLYlRooCQwgts_hbWwd:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L25)):*
> ```C
> 
>     struct pollfd* fds = NULL;
>     bool allocated_on_stack = false;
> ```

ditto
___
*[`pal/src/host/linux/pal_object.c` line 28 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYluf04FEWdwZHFEub:-NLYluf04FEWdwZHFEuc:b-bvvg0b) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L28)):*
> ```C
> 
>     if (count <= NFDS_LIMIT_TO_USE_STACK) {
>         /* Each FD uses 8 bytes on stack */
> ```

I don't like these comments. I know they seem useful at first, but they aren't 100% right, what you described there is compiler/arch specific. And overall I don't like hardcoding sizes/offsets in comments.

Ditto for all other analogous places.
___
*[`pal/src/host/linux/pal_object.c` line 30 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYlSac709HnVYoL6Oo:-NLYlSac709HnVYoL6Op:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L30)):*
> ```C
>         /* Each FD uses 8 bytes on stack */
>         static_assert(sizeof(*fds) * NFDS_LIMIT_TO_USE_STACK <= 128,
>                       "use too much space on stack, reduce the limit");
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmhbu4dwGKDJfGKxQ:-NLYmhbu4dwGKDJfGKxR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L17)):*
> ```C
> 
> /* To avoid expensive malloc/free (due to locking), use stack if the required
>  * space is small enough. */
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 23 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmiUgAGdj5F84u5N8:-NLYmiUgAGdj5F84u5N9:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L23)):*
> ```C
>                           pal_wait_flags_t* ret_events, uint64_t* timeout_us) {
>     struct pollfd* fds = NULL;
>     bool allocated_on_stack = false;
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 28 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmjOC4YJ8X4BGuWnR:-NLYmjOC4YJ8X4BGuWnS:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L28)):*
> ```C
>         /* Each FD uses 8 bytes on stack */
>         static_assert(sizeof(*fds) * NFDS_LIMIT_TO_USE_STACK <= 128,
>                       "use too much space on stack, reduce the limit");
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-01-12 08:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @lejunzhu, and @mkow)

___
*[`libos/src/sys/libos_poll.c` line 58 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYjEu9C1hFijNXnai4:-NL_8UJG2y8JF8-ZythV:b6sgjd6) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Readability suggestion: This makes the IF more symmetric (in your version one side sets `allocated_on_stack` and the other not, which on first read looked like you forgot to set it.
</blockquote></details>

+1, looks nicer
___
*[`pal/src/host/linux/pal_object.c` line 28 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYluf04FEWdwZHFEub:-NL_8atGAXriQS6-MCtk:borwn09) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like these comments. I know they seem useful at first, but they aren't 100% right, what you described there is compiler/arch specific. And overall I don't like hardcoding sizes/offsets in comments.

Ditto for all other analogous places.
</blockquote></details>

I guess we can remove all these comments, since now we have `static_assert` which tells/checks more or less the same.


<!-- Sent from Reviewable.io -->

2023-01-13 07:02 UTC, lejunzhu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: 1 of 4 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @lejunzhu, and @mkow)

___
*[`libos/src/sys/libos_poll.c` line 48 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYl1N2DmU-8fSmYQWV:-NLdrJnO2d8QFGg5xGdX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we wrap on 100 chars
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 58 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYjEu9C1hFijNXnai4:-NLdrr5gEX0jVhWC3O9G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, looks nicer
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 62 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYgjpsDo20Lk7i_auU:-NLdrzbj3oaE9j1qpaS3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"use too much space" is in imperative mood and means a different thing than you (as I guess) intended.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 288 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYjv1xA1zbKcKcmaQV:-NLdsYqyBEvgyxHiomGC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L288)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 293 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYkJnb50MLr44f9Wz0:-NLdspTx8IVvAbEhLguT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/libos/src/sys/libos_poll.c#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 16 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYkwQi2bjtLh63PUng:-NLdsy6yA2KQ2ZXNcfX-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we wrap on 100 chars
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 25 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYlRooCQwgts_hbWwc:-NLdtIaw1D7Q--yvA4V1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 28 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYluf04FEWdwZHFEub:-NLdtJTYEc_JC6MVlx3a:b-wrq176) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess we can remove all these comments, since now we have `static_assert` which tells/checks more or less the same.
</blockquote></details>

I've removed all such comments.
___
*[`pal/src/host/linux/pal_object.c` line 30 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYlSac709HnVYoL6Oo:-NLdtMZg6MpfaK__Jnn5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux/pal_object.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmhbu4dwGKDJfGKxQ:-NLdtNxa8nBjgqOrU3KX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 23 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmiUgAGdj5F84u5N8:-NLdtOXTArLQf2BjsQSB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 28 at r8](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLYmjOC4YJ8X4BGuWnR:-NLdtPaC8g_TWRYPP9wv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46d7273cf20f3c903993e3e505243c36b3d9e7c0/pal/src/host/linux-sgx/pal_object.c#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-13 09:08 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @lejunzhu, and @mkow)



<!-- Sent from Reviewable.io -->

2023-01-13 15:05 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lejunzhu)



<!-- Sent from Reviewable.io -->

2023-01-13 19:11 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @lejunzhu)



<!-- Sent from Reviewable.io -->

2023-01-14 00:28 UTC, mkow approved these changes
> Reviewed all commit messages.
> Dismissed @boryspoplawski from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: all files reviewed, 1 unresolved discussion (waiting on @lejunzhu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1051#-NLhfCv97jX-A12dULft:-NLhfCv97jX-A12dULfu:b-pvx1rz) (no related file):*
I'm dismissing Borys' blocking comments with his approval. he won't have time to finish this review.

___


<!-- Sent from Reviewable.io -->

2023-01-16 09:08 UTC, dimakuv approved these changes
> Dismissed @yamahata from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-16 09:29 UTC, dimakuv approved these changes
> Dismissed @boryspoplawski from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1051)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-16 09:42 UTC, merged