[LibOS,PAL] Support TCP_USER_TIMEOUT socket opt
gramineproject/gramine pull request #1052
Opened 2022-11-17 13:49 UTC by dimakuv

## Description of the changes 

Previously, Gramine didn't support setting (via `setsockopt()`) or getting (via `getsockopt()`) `TCP_USER_TIMEOUT` socket option. This could lead to some applications failures (in particular, libpq) when they tried to get/set this socket option but found out it's unsupported.

This is requested by application devs that have to use `libpq` library. The offending code is here: https://github.com/postgres/postgres/blob/3d0c95bc8920f51f7d7685c622c9a75f59cf322f/src/backend/libpq/pqcomm.c#L1872-L1915

This PR is based on a prevoius similar PR: https://github.com/gramineproject/gramine/commit/bd977417363224906aba1d28ce14329ae37163c6

How Linux does it (very simply):
- https://elixir.bootlin.com/linux/latest/source/tools/include/uapi/linux/tcp.h#L108
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp.c#L3721
- https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp.c#L4240

Some man-page details:
- https://man7.org/linux/man-pages/man7/tcp.7.html (note that inside Linux, `TCP_USER_TIMEOUT` is simply an `int`)

## How to test this PR? 

Added a quick test in CI.

2022-11-23 18:08 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1052)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_aCSx9etJqW2BR6eW):*




_Suggestion:_
```
[LibOS,PAL] Support TCP_USER_TIMEOUT socket option
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_aOhmDJyC9tXhFVGB):*
Do we want to be so verbose? IMO the only valuable information here is that `libpq` requires this option



_Code quote:_
```
  Previously, Gramine didn't support setting (via `setsockopt()`) or
  getting (via `getsockopt()`) `TCP_USER_TIMEOUT` socket option. This
  could lead to some applications failures (in particular, libpq) when
  they tried to get/set this socket option but found out it's unsupported.
```
___
*[`pal/include/pal/pal.h` line 484 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_bh9PDQM5h6uJxCji:-NH_bh9PDQM5h6uJxCjj:b1luy2n) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/include/pal/pal.h#L484)):*
> ```objc
>             uint32_t tcp_keepintvl;
>             uint8_t tcp_keepcnt;
>             uint32_t tcp_user_timeout;
> ```

Please move it 1 item (or 2) above (now we waste space for padding)
___
*[`pal/src/host/linux/pal_host.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_bog81fNUk8h0NRfQ:-NH_bog81fNUk8h0NRfR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux/pal_host.h#L84)):*
> ```objc
>             uint32_t tcp_keepintvl;
>             uint8_t tcp_keepcnt;
>             uint32_t tcp_user_timeout;
> ```

ditto
___
*[`pal/src/host/linux/pal_sockets.c` line 80 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_evWw2d-WGelDOjWW:-NH_evWw2d-WGelDOjWX:b-2ztb4p) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux/pal_sockets.c#L80)):*
> ```C
>     handle->sock.tcp_keepintvl = DEFAULT_TCP_KEEPINTVL;
>     handle->sock.tcp_keepcnt = DEFAULT_TCP_KEEPCNT;
>     handle->sock.tcp_user_timeout = 0;
> ```

`define` in `common/include/linux_socket.h`?
___
*[`pal/src/host/linux-sgx/pal_host.h` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_f9fiAvb3inm3O5Hj:-NH_f9fjEP7aiXpgE9AH:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux-sgx/pal_host.h#L107)):*
> ```objc
>             uint32_t tcp_keepintvl;
>             uint8_t tcp_keepcnt;
>             uint32_t tcp_user_timeout;
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_fAsl1p8aJ7XNUvqP:-NH_fAsm74kdJxh-W_Ab:b-2ztb4p) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux-sgx/pal_sockets.c#L89)):*
> ```C
>     handle->sock.tcp_keepintvl = DEFAULT_TCP_KEEPINTVL;
>     handle->sock.tcp_keepcnt = DEFAULT_TCP_KEEPCNT;
>     handle->sock.tcp_user_timeout = 0;
> ```

`define` in `common/include/linux_socket.h`?


<!-- Sent from Reviewable.io -->

2022-11-24 08:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1052)* status: 2 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_aCSx9etJqW2BR6eW):*
Done. Did a rebase since the changes in the PR are minimal, and Reviewable can show them correctly.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_aOhmDJyC9tXhFVGB):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we want to be so verbose? IMO the only valuable information here is that `libpq` requires this option
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 484 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_bh9PDQM5h6uJxCji:-NHcmgsn9sqzLRCKnQsI:bdo5gbv) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/include/pal/pal.h#L484)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move it 1 item (or 2) above (now we waste space for padding)
</blockquote></details>

Done. To be honest, I didn't understand what you mean with padding, but I moved it before the whole `tcp_keep*` set of options.
___
*[`pal/src/host/linux/pal_host.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_bog81fNUk8h0NRfQ:-NHcmv4G-e3Hg3gmtGqD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux/pal_host.h#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_sockets.c` line 80 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_evWw2d-WGelDOjWW:-NHcmScn0JfPY8DdA2hh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux/pal_sockets.c#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`define` in `common/include/linux_socket.h`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_f9fiAvb3inm3O5Hj:-NHcn4t3EnoM-KMLtfs6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux-sgx/pal_host.h#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_fAsl1p8aJ7XNUvqP:-NHcmZ7ECmeO5ij0_wEX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/src/host/linux-sgx/pal_sockets.c#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`define` in `common/include/linux_socket.h`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-25 00:55 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1052)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`pal/include/pal/pal.h` line 484 at r1](https://reviewable.io/reviews/gramineproject/gramine/1052#-NH_bh9PDQM5h6uJxCji:-NHgGHxa-vm4OABv3UKh:b9echyw) ([raw file](https://github.com/gramineproject/gramine/blob/dffd12174ff26be8ee94505d9348e018797ed4fc/pal/include/pal/pal.h#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. To be honest, I didn't understand what you mean with padding, but I moved it before the whole `tcp_keep*` set of options.
</blockquote></details>

`u32` fields must be aligned to 4-bytes, so if you do `u32; u8; u32` you get 3 bytes of padding after `u8`.
It's not like we have no padding in this struct at all, but this new field can be logically put at any of these places, so better choose one without padding.


<!-- Sent from Reviewable.io -->

2022-11-26 21:34 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1052)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-27 00:40 UTC, mkow reviewed
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1052)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-27 00:41 UTC, merged