[PAL/Linux-SGX] Add EDMM support
gramineproject/gramine pull request #1054
Opened 2022-11-18 01:06 UTC by boryspoplawski

## Description of the changes 
Probably requires documentation and comments, but should be enough for beta testing.

## How to test this PR? 
Get a EDMM capable machine with EDMM capable SGX2 kernel driver and add `sgx.edmm_enable = true` to manifests.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1054)

2022-11-18 22:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 0 of 34 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NHBn-3z8qa03C9AbtOk:b-1kl3xe) (no related file):*
Jenkins failed because of `test_300_memory` in pal regression tests. This would need a new flag, but it's pointless until we have SGX2 capable CI

___


<!-- Sent from Reviewable.io -->

2022-11-22 14:54 UTC, dimakuv requested changes
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 31 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NHUeYX02r_Du4ZYZZzE:bxqv6u3) (no related file):*
> This would need a new flag, but it's pointless until we have SGX2 capable CI

Could you split this test into two (one that works in both cases, and one purely for EDMM)? Then you could introduce a new flag (envvar) to control the CI.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUoriL3_YqyoEZl_Xd:-NHUoriL3_YqyoEZl_Xe:b-fh64ln) (no related file):*
This will need documentation and some additional CI tests. Can be taken from Vijay's PR https://github.com/gramineproject/gramine/pull/1006, if we decide to go with this PR.

___
___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUetHD9r-wsu4cIkRn):*
`given`
___
*[`libos/include/libos_vma.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUf1rb34n8vklOJO9D:-NHUf1rb34n8vklOJO9E:b-1krszn) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/include/libos_vma.h#L82)):*
> ```objc
>  * atomically checks for overlaps and fails if one is found.
>  * If `overwriting` is not NULL, its content will be set to true iff this request overlapped
>  * an existing memory area. Obviously not meaningful with MAP_FIXED_NOREPLACE.
> ```

The comment doesn't say why this boolean is useful (without looking at the code itself). Maybe add some explanation?
___
*[`libos/src/libos_checkpoint.c` line 437 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfBBb1-1GifnIXaI0:-NHUfBBb1-1GifnIXaI1:b-jvzy7i) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/libos_checkpoint.c#L437)):*
> ```C
> 
>         if (bkeep_mmap_fixed(addr, size, PROT_READ | PROT_WRITE,
>                              CP_MMAP_FLAGS | MAP_FIXED_NOREPLACE, NULL, 0, "cpstore", NULL) < 0)
> ```

Adding inline comments with arg names would be nice
___
*[`libos/src/libos_checkpoint.c` line 682 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfFAF4v-NTxVQZ-ED:-NHUfFAF4v-NTxVQZ-EE:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/libos_checkpoint.c#L682)):*
> ```C
>             mapaddr + mapsize <= g_pal_public_state->memory_address_end) {
>         ret = bkeep_mmap_fixed(mapaddr, mapsize, PROT_READ | PROT_WRITE,
>                                CP_MMAP_FLAGS | MAP_FIXED_NOREPLACE, NULL, 0, "cpstore", NULL);
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 227 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfMkdDHX03l7Xp_Wr:-NHUfMkdDHX03l7Xp_Ws:bfjxmij) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L227)):*
> ```C
>  * Range [begin, end) can consist of multiple vmas even with holes in between, but they all must be
>  * either internal or non-internal.
>  * If `out_removed` is not NULL, it is set to `true` iff any memory range was actually removed.
> ```

Could you add a comment why this boolean is useful? What is the caller supposed to do with this info?
___
*[`libos/src/bookkeep/libos_vma.c` line 343 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfjoh2NURGx2uoFMM:-NHUfjoh2NURGx2uoFMN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L343)):*
> ```C
>         /* Since we are freeing a range we just created, additional vma is not needed. */
>         ret = _vma_bkeep_remove((uintptr_t)addr, (uintptr_t)addr + size, /*is_internal=*/true, NULL,
>                                 &vmas_to_free, NULL);
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 744 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUflUK7u1AaXlfmY2W:-NHUflUK7u1AaXlfmY2X:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L744)):*
> ```C
>     spinlock_lock(&vma_tree_lock);
>     int ret = _vma_bkeep_remove((uintptr_t)addr, (uintptr_t)addr + length, is_internal,
>                                 vma2 ? &vma2 : NULL, &vmas_to_free, NULL);
> ```

ditto
___
*[`libos/src/sys/libos_brk.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUg1hX3RNQrAxMu3cE:-NHUg1hX3RNQrAxMu3cF:b-ovej74) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/sys/libos_brk.c#L83)):*
> ```C
> 
>         ret = bkeep_mmap_fixed(brk_start, brk_max_size, PROT_NONE,
>                                MAP_FIXED_NOREPLACE | VMA_UNMAPPED, NULL, 0, "heap", NULL);
> ```

ditto (in this whole file)
___
*[`libos/src/sys/libos_mmap.c` line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhHcg4C1ijaqvyLRg:-NHUhHchEolctmbR2Qvr:bmzrhq1) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/sys/libos_mmap.c#L264)):*
> ```C
>         if (lookup_vma(addr, &vma_info) >= 0) {
>             assert(vma_info.addr <= addr);
>             length += addr - vma_info.addr;
> ```

What does this do? Also, looks like unrelated bug so maybe have a separate PR?
___
*[`pal/include/pal_internal.h` line 279 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhT-F7GLLtlEEDZI5:-NHUhT-F7GLLtlEEDZI6:bwr5x0y) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/include/pal_internal.h#L279)):*
> ```objc
>  */
> int pal_add_initial_range(uintptr_t addr, size_t size, pal_prot_flags_t prot, const char* comment);
> int pal_internal_memory_bkeep(size_t size, uintptr_t* out_addr);
> ```

Shouldn't we unify address types (`uintptr_t` vs `void*`) in these functions?
___
*[`pal/include/pal/pal.h` line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhm4SBZCiA2kYRB3S:-NHUhm4SBZCiA2kYRB3T:bhgntnl) ([raw file](https://github.com/gramineproject/gramine/blob/5bba58a902d099f9068e0f04b3c2a37e591a1d27/pal/include/pal/pal.h#L215)):*
> ```objc
>  *
>  * `addr` can be any valid address aligned at the allocation alignment. Any memory previously
>  * allocated at the same address will be discarded. Overwriting any part of PAL memory is forbidden.
> ```

The last sentence (about PAL memory) is stale for some time now. So if we drag this PR (or decide not to merge it), removing this last sentence would still be useful (in a new PR).
___
*[`pal/include/pal/pal.h` line 227 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUi-w0BWaDmvG9tuVG:-NHUi-w0BWaDmvG9tuVH:b-f7ggl8) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/include/pal/pal.h#L227)):*
> ```objc
>  *
>  * Both `addr` and `size` must be non-zero and aligned at the allocation alignment.
>  * Memory range `[addr; addr+size)` does not have to be continuous, i.e. it can have holes.
> ```

I hope we'll never hit any problems with this assumption (on some other, future PALs).
___
*[`pal/src/pal_memory.c` line 318 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUjFEhEa0Q6zmMUPJW:-NHUjFEhEa0Q6zmMUPJX:boipvxl) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/pal_memory.c#L318)):*
> ```C
>     ret = _PalVirtualMemoryAlloc((void*)addr, size, PAL_PROT_READ | PAL_PROT_WRITE);
>     if (ret < 0) {
>         if (!g_m [...]

2022-11-23 11:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NHYiEDZ8em1kU75pGIz:bmnp038) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This would need a new flag, but it's pointless until we have SGX2 capable CI

Could you split this test into two (one that works in both cases, and one purely for EDMM)? Then you could introduce a new flag (envvar) to control the CI.
</blockquote></details>

This test as a whole does not work with SGX1, so no need for splitting.

What I'm wondering is whether we should add something like
```
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
```
to every manifest, or generate that for tests in our python scripts and add it to just `CI-Examples/`

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHZ0tU-3Bx2AX5RnsCw:-NHZ0tU-3Bx2AX5RnsCx:b-azgnfj) (no related file):*
This PR depends on https://github.com/gramineproject/gramine/pull/1061 and https://github.com/gramineproject/gramine/pull/1060

___
___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUetHD9r-wsu4cIkRn):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`given`
</blockquote></details>

Done.
___
*[`libos/include/libos_vma.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUf1rb34n8vklOJO9D:-NHYjtEzAwaN0mWUat6d:b2ee1i7) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/include/libos_vma.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment doesn't say why this boolean is useful (without looking at the code itself). Maybe add some explanation?
</blockquote></details>

Why would it say so? It's up to the caller to decide whether this value is useful/needed.
___
*[`libos/src/libos_checkpoint.c` line 437 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfBBb1-1GifnIXaI0:-NHYkSwq63IiDkUhUA2b:b-b57lf9) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/libos_checkpoint.c#L437)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Adding inline comments with arg names would be nice
</blockquote></details>

Ugh, more changes to this beautiful file always make me happier
___
*[`libos/src/libos_checkpoint.c` line 682 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfFAF4v-NTxVQZ-ED:-NHYkzR86P7XvzDWXsuV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/libos_checkpoint.c#L682)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 227 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfMkdDHX03l7Xp_Wr:-NHYl0JfDSDhGuPTNQqD:bf1fd2r) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment why this boolean is useful? What is the caller supposed to do with this info?
</blockquote></details>

Whatever it wants, which most of the time is completely ignore it.
___
*[`libos/src/bookkeep/libos_vma.c` line 343 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUfjoh2NURGx2uoFMM:-NHYlYyx01-_sZEGRiFK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L343)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 744 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUflUK7u1AaXlfmY2W:-NHYlp4u3NX0V5VKiO6M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/bookkeep/libos_vma.c#L744)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_brk.c` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUg1hX3RNQrAxMu3cE:-NHYmadd9b52y7De-Vt6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/sys/libos_brk.c#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (in this whole file)
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_mmap.c` line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhHcg4C1ijaqvyLRg:-NHZ--iSEaFUNkxhceM6:buyjlgj) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/libos/src/sys/libos_mmap.c#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this do? Also, looks like unrelated bug so maybe have a separate PR?
</blockquote></details>

https://github.com/gramineproject/gramine/pull/1060
___
*[`pal/include/pal_internal.h` line 279 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhT-F7GLLtlEEDZI5:-NHZ153-0jeI0qgqLm4a:b-z0ww1q) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/include/pal_internal.h#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we unify address types (`uintptr_t` vs `void*`) in these functions?
</blockquote></details>

Some are for bookkeeping and use `uintptr_t` (some numerical arch dependent representation of a virtual memory address) and some for actual allocations and use `void*`, so I don't see what we could improve here
___
*[`pal/include/pal/pal.h` line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhm4SBZCiA2kYRB3S:-NHYnUdgAj2WJlFI2Rd6:bxlkbm0) ([raw file](https://github.com/gramineproject/gramine/blob/5bba58a902d099f9068e0f04b3c2a37e591a1d27/pal/include/pal/pal.h#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The last sentence (about PAL memory) is stale for some time now. So if we drag this PR (or decide not to merge it), removing this last sentence would still be useful (in a new PR).
</blockquote></details>

I feel like creating a PR just for this sentence would be an overkill, it's not really wrong (just pointless)
___
*[`pal/include/pal/pal.h` line 227 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUi-w0BWaDmvG9tuVG:-NHYnkuKDU0wgUyHzr6x:b-e9uyl3) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/include/pal/pal.h#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I hope we'll never hit any problems with this assumption (on some other, future PALs).
</blockquote></details>

We always had this assumption, I just documented it explicitly.
___
*[`pal/src/pal_rtld.c` line 382 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUjhC7BqOpahFSvQKJ:-NHZ0YV3Dxc7lbP7OKeE:b6wc84t) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/pal_rtld.c#L382)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote [...]

2022-11-24 09:26 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NHctqmv5ZSvjdleoff3:bvwi9p8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This test as a whole does not work with SGX1, so no need for splitting.

What I'm wondering is whether we should add something like
```
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
```
to every manifest, or generate that for tests in our python scripts and add it to just `CI-Examples/`
</blockquote></details>

Definitely not to every manifest (we also need to test the non-EDMM logic extensively).

I would this line to:
- `libos/test/regression/large_mmap.manifest.template`, just for perf reasons
- to a couple other regression tests, that do smth with mmap (including file-backed mmaps) where this could make sense
- to CI-Examples: `blender`, `memcached`, `python`, `redis`, `sqlite` (these are the ones that seem to make sense to have it)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHcwsS5BkWltD2Is3zh:-NHcwsS5BkWltD2Is3zi:b-wpczf9) (no related file):*
Since you now rely on `EDMM` envvar, do you want to introduce it in `.ci/`, otherwise we'll forget? Similar to this: https://github.com/gramineproject/gramine/blob/0916d2fd3dcd2af40f2170ac5ae313f1dc387e7c/.ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile#L4

___
___
*[`pal/include/pal_internal.h` line 279 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUhT-F7GLLtlEEDZI5:-NHcupWABnHovloXwn0l:b-lt0lyy) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/include/pal_internal.h#L279)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Some are for bookkeeping and use `uintptr_t` (some numerical arch dependent representation of a virtual memory address) and some for actual allocations and use `void*`, so I don't see what we could improve here
</blockquote></details>

I see, makes sense.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkabH5zSjkrPCuxbY:-NHcvV4GCbKufGEf_mJM:bn9yvbv) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_framework.c#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, I was supposed to leave a comment here to make sure it works everywhere.
I've tested:
- upstream with SGX2
- upstream without SGX2 (initial upstreamed driver)
- oot driver

Everything worked.
I guess some more testing wouldn't hurt. Also I'm not sure who uses DCAP or whether we still support it or dropped (because it was compatible  with some other driver or something)
</blockquote></details>

I can test it with Azure Ubuntu 18.04 which has DCAP driver. TODO.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkx0T62zYCGmNrTpV:-NHcw5YQC2f6To_uQic-:bfpbxgo) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_internal.h#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why it shouldn't?
And which header would be that other one?
</blockquote></details>

I would move here: `host_sgx_driver.h.in`

Because it's an interface with the driver... Doesn't feel like should be here.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 298 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUmgjRBss1kqUIx_p_:-NHcwNxN9zTSci9HSv5p:bq8lrqk) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/pal_files.c#L298)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, I'll split it if you write a commit message for it :)
(I tried but couldn't come up with anything better than `Cosmetic change needed by next commit`)
</blockquote></details>

You're right. It only makes sense with this change. Ignore me.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUoHke5gaiPU5FMH7I:-NHcwgrjCz3RUJ2D2cb4:bjp33rv) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/pal_streams.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yea, seems like nothing really uses it. Not sure if we want it - on PAL level mapping memory and a file are conceptually different operations (similar, but different), idk how we should treat unmapping.
</blockquote></details>

Whatever, unrelated to this PR anyway


<!-- Sent from Reviewable.io -->

2022-11-24 10:09 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkabH5zSjkrPCuxbY:-NHd6-I04SQknoflVvgr:b40udvo) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_framework.c#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can test it with Azure Ubuntu 18.04 which has DCAP driver. TODO.
</blockquote></details>

Well, it's not working on Azure CC 18.04... Could you please revert this change?


<!-- Sent from Reviewable.io -->

2022-11-25 01:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 34 of 36 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NHgI2oV6T3BDMh96kGw:b-x2ntg5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Definitely not to every manifest (we also need to test the non-EDMM logic extensively).

I would this line to:
- `libos/test/regression/large_mmap.manifest.template`, just for perf reasons
- to a couple other regression tests, that do smth with mmap (including file-backed mmaps) where this could make sense
- to CI-Examples: `blender`, `memcached`, `python`, `redis`, `sqlite` (these are the ones that seem to make sense to have it)
</blockquote></details>

Why not to every? As you can see it's controlled via env variable, which we would set only on some (new?) pipelines.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHZ0tU-3Bx2AX5RnsCw:-NHgK3L7DhsrwfhWgLk1:b1ridyk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This PR depends on https://github.com/gramineproject/gramine/pull/1061 and https://github.com/gramineproject/gramine/pull/1060
</blockquote></details>

#1060 was merged

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHcwsS5BkWltD2Is3zh:-NHgLxp13eI6w8FJ9zdu:b-udl4lb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since you now rely on `EDMM` envvar, do you want to introduce it in `.ci/`, otherwise we'll forget? Similar to this: https://github.com/gramineproject/gramine/blob/0916d2fd3dcd2af40f2170ac5ae313f1dc387e7c/.ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile#L4
</blockquote></details>

No, because we have no edmm ready CI machines.

___
___
*[`pal/src/host/linux-sgx/host_framework.c` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkabH5zSjkrPCuxbY:-NHgPj8UA5yIJA1lFNwl:bhf6jsk) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_framework.c#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, it's not working on Azure CC 18.04... Could you please revert this change?
</blockquote></details>

Hmm, but quoting https://github.com/gramineproject/gramine/pull/1027
"This is because the DCAP and the upstream drivers are API compatible"
What's the problem? How it fails?

Also it's not so easy, currently our defines are a mess. `SGX_DCAP` is defined for everything except oot (which means it's defined for upstream driver).
___
*[`pal/src/host/linux-sgx/host_internal.h` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkx0T62zYCGmNrTpV:-NHgP5it9Au_icWQfoC2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_internal.h#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move here: `host_sgx_driver.h.in`

Because it's an interface with the driver... Doesn't feel like should be here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-28 14:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 28 of 36 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHZ0tU-3Bx2AX5RnsCw:-NHygXqe5oKAc-tOzWK8:bwm71h5) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

#1060 was merged
</blockquote></details>

https://github.com/gramineproject/gramine/pull/1061 was merged
rebased this PR

___


<!-- Sent from Reviewable.io -->

2022-12-08 08:53 UTC, kailun-qin reviewed
> Reviewed 21 of 34 files at r1, 6 of 8 files at r2, 1 of 2 files at r3, 4 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 33 of 36 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NIkZe_j9v_r7PHagVMd:b-v9skx6) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not to every? As you can see it's controlled via env variable, which we would set only on some (new?) pipelines.
</blockquote></details>

If only for CI/testing purpose, I think it's technically fine to have env-controlled EDMM opt in every manifest (and have it set on some new pipelines). However, 1) CI-Examples are user-facing (which can cause some confusions and misuse); 2) EDMM does not always better suit or make sense for every application, so IMHO it's not a good idea to introduce it to every manifest.

___
___
*[`-- commits` line 15 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkaJMG0qAt2XfxoMMd):*
round trips



_Code quote:_
```
round-trips
```
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIke9WLDfnODLtiC01J:-NIke9WLDfnODLtiC01K:b-1mogbk) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L16)):*
> ```C
> #include "sgx_arch.h"
> 
> static int enclu(uint32_t eax, uint64_t rbx, uint64_t rcx) {
> ```

Should we move this (maybe below also?) to somewhere more generic like `sgx_arch.h`?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NIkhXOt9FEVJCwBew7c:b77ovqs) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
> ```C
>     for (size_t i = 0; i < count; i++) {
>         /* SGX2 HW requires initial page permissions to be RW. */
>         ret = sgx_eaccept(addr + i * PAGE_SIZE, (SGX_PAGE_TYPE_REG << SGX_SECINFO_FLAGS_TYPE_SHIFT)
> ```

Can we have these page types SECINFO flags defined in`sgx_arch.h`?



_Code quote:_
```C
SGX_PAGE_TYPE_REG << SGX_SECINFO_FLAGS_TYPE_SHIFT
```
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkgZQj0r52jh7hXzAq:-NIkgZQj0r52jh7hXzAr:b78jogq) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L54)):*
> ```C
>                                                 | SGX_SECINFO_FLAGS_R | SGX_SECINFO_FLAGS_W
>                                                 | SGX_SECINFO_FLAGS_PENDING);
>         if (ret < 0) {
> ```

`ENCLx` like`EACCEPT` have positive return code as far as I recall. So it's incorrect and pls kindly double check.



_Code quote:_
```C
ret < 0
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 376 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkiiqxA6FSf1qVbLMZ:-NIkiiqxA6FSf1qVbLM_:bhk4me2) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/host_framework.c#L376)):*
> ```C
>     size_t size = count * PAGE_SIZE;
> 
>     while (offset < size) {
> ```

Any special reason that we implement this with `size` but treat the below two with `count`?



_Code quote:_
```C
offset < size
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 353 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkvZt-7MkrVRzDnrgy:-NIkvZt-7MkrVRzDnrgz:bvchw9e) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L353)):*
> ```C
>     if (g_pal_linuxsgx_state.edmm_enabled && !(prot & PAL_PROT_WRITE)) {
>         /* Clear W permission, in case we added it artificially. */
>         ret = sgx_edmm_set_page_permissions((uintptr_t)addr, size / PAGE_SIZE,
> ```

uint64_t



_Code quote:_
```C
uintptr_t
```
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkqN1y1bt1OmaGwkxs:-NIkqN1y1bt1OmaGwkxt:b6y7idk) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L355)):*
> ```C
>         ret = sgx_edmm_set_page_permissions((uintptr_t)addr, size / PAGE_SIZE,
>                                             PAL_TO_SGX_PROT(prot));
>         if (ret < 0) {
> ```

Note: currently we return 0 or otherwise `BUG()` for all `sgx_edmm_xxx()`, i.e., this (and other similar) checks are not actually used.



_Code quote:_
```C
ret < 0
```
___
*[`pal/src/host/linux-sgx/pal_main.c` line 734 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkr5YdCyxKHSSPwkZr:-NIkr5YdCyxKHSSPwkZs:b-il4g9m) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_main.c#L734)):*
> ```C
>         if (g_pal_linuxsgx_state.edmm_enabled) {
>             log_error("'sgx.preheat_enclave' manifest option makes no sense with EDMM enabled!");
>             ocall_exit(1, /*is_exitgroup=*/true);
> ```

Is it necessary to exit? Or we just warn and skip it?



_Code quote:_
```C
ocall_exit
```


<!-- Sent from Reviewable.io -->

2022-12-14 16:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 23 of 39 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 3 at r6](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJGMwHrAomqtrpiz9H5):*
FYI: I reverted this commit below


<!-- Sent from Reviewable.io -->

2022-12-14 17:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 23 of 44 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @yamahata)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJGUtPU3RsGFxxGvBVx:-NJGfWKz1tjpdAWCnYxD:b-ib1byn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv @kailun-qin @mkow @yamahata  You opened reviewable on this PR:
I'll need to rebase this PR soon, to pick up changes from the latest master. Let me know when you check out the current state so I can do the rebase and not interfere with the review process.
</blockquote></details>

I'm fine with the rebase.

___


<!-- Sent from Reviewable.io -->

2022-12-14 17:57 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (LTP fcntl14_64 and fdatasync01 failed, unrelated)

2022-12-14 22:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 23 of 44 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJGUtPU3RsGFxxGvBVx:-NJHjWlI5hukFd3UM96w:bscdiw4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with the rebase.
</blockquote></details>

Feel free to rebase.

___


<!-- Sent from Reviewable.io -->

2022-12-15 00:47 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 23 of 44 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJGUtPU3RsGFxxGvBVx:-NJIEUZQ6RZ-xxntt9Hd:byh2lrs) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Feel free to rebase.
</blockquote></details>

Fine for me, pls go ahead.

___


<!-- Sent from Reviewable.io -->

2022-12-15 12:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 17 of 44 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJGUtPU3RsGFxxGvBVx:-NJKqsrrADrKqdpsuhgh:bmrgebu) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Fine for me, pls go ahead.
</blockquote></details>

All right, rebased, current revision has no additional changes (except fixing conflicts on rebase).

___


<!-- Sent from Reviewable.io -->

2022-12-15 14:53 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-15 15:37 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-15 18:06 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-15 22:16 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-15 22:27 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-19 19:13 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 19:15 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-EDMM please (testing)

2022-12-19 19:15 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 19:16 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 20:21 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 20:22 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 20:22 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 22:44 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 22:44 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 22:44 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-19 22:44 UTC, boryspoplawski commented
Jenkins, test Jenkins-SGX-18.04 please (testing)

2022-12-20 00:34 UTC, vijaydhanraj reviewed
> Reviewed 3 of 7 files at r4, 3 of 6 files at r5, 6 of 7 files at r6, 5 of 5 files at r7, 8 of 8 files at r8, 53 of 54 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 97 of 99 files reviewed, 31 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NJes62E42_Bpkjb_vB6:b-x5l6va) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> 1) CI-Examples are user-facing

And why is that a problem? We want this feature to be usable (so we need to test it in CI) and actually used (so users need to see it in examples).

> (which can cause some confusions and misuse);

Not sure what you mean. What misues?

> 2) EDMM does not always better suit or make sense for every application, so IMHO it's not a good idea to introduce it to every manifest.

As far as I understand, possible performance hit is the only why app wouldn't want to use EDMM - otherwise it's invisible to apps and possibly speeds them up. In CI we want to test as many configs as we can, that includes even the apps that are slower with it.
</blockquote></details>

Can't we run 2 CI pipelines one with EDMM=1 and other with EDMM=0? My testing of EDMM changes with our CI tests did help me fix issues even if the tests  (like `fork` and `exec` tests) weren't directly related to memory related ones like `mmap`. So, adding EDMM to every CI test will definitely add value.  

___
___
*[`CI-Examples/redis/redis-server.manifest.template` line 75 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJeviJg8kzaDpscZyE1:-NJeviJg8kzaDpscZyE2:b9kwfbe) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L75)):*
> ```
> # Enable Enclave Dynamic Memory Management (EDMM) feature based on EDMM
> # environment variable. This allows for addition of pages to enclave in runtime,
> # instead of alocating them upfront at startup. If this is enabled,
> ```

`allocating` -> `allocating`
___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NJewXRm7RplS8uVJS65:b-gzg2cw) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
> ```
> # instead of alocating them upfront at startup. If this is enabled,
> # `sgx.enclave_size` above describes a maximal enclave size and can usually be
> # increased without negative consequences.
> ```

If the enclave size can be increased then `sgx.enclave_size` doesn't describe a maximal enclave size, right? The comment seems to contradict.



_Code quote:_
```
# `sgx.enclave_size` above describes a maximal enclave size and can usually be
# increased without negative consequences.
```
___
*[`libos/src/sys/libos_mmap.c` line 297 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJf6kYKCYzAj8b4rPPd:-NJf6kYKCYzAj8b4rPPe:b-fy4wgu) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/src/sys/libos_mmap.c#L297)):*
> ```C
>     struct libos_vma_info* vmas;
>     size_t vmas_length;
>     ret = dump_vmas_in_range(addr, addr + length, /*include_unmapped=*/false, &vmas, &vmas_length);
> ```

Why do dumping of VMAs first and then call the bkeep_munmap sequence (munmap, pal_free and remove_tmp_vma) on each vma? why not use `bkeep_munmap?` Is this because `bkeep_munmap` doesn't return partial VMAs?
___
*[`libos/test/regression/openmp.manifest.template` line 12 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJfhoG09XTYiBaPp0Z3:-NJfhoG09XTYiBaPp0Z4:b-nxdpuv) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/test/regression/openmp.manifest.template#L12)):*
> ```
> # the manifest options below are added only for testing, they have no significance for OpenMP
> sys.enable_sigterm_injection = true
> # `sgx.preheat_enclave` is invalid with EDMM
> ```

Can we update the `manifest-syntax.rst` and `performance.rst` as well with this comment?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIke9WLDfnODLtiC01J:-NJfwtNgC-z_RwC4e9lq:b52l577) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, I was supposed to put a comment here and forgot.
Generally yes, this should be in some common header. I guess this is usable also in untrusted word, so we can put it into `sgx_arch.h`.
`eaccept` and `emodpe` are not really usable anywhere else, so I don't think we should move them.
</blockquote></details>

I see definition for other user leaf function definition in `enclave_api.S` why not define `EACCEPT` and `EMODPE` there?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NJfz8Wp3c7oBN5xp2vT:bm8p1ml) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Would that make the code more readable?
I originally had such flags, but removed them for some reason, I don't remember why...
</blockquote></details>

+1 to define in `sgx_arch.h`. Also, it will be consistent with other `flags` that we pass as an argument. Something like `SGX_SECINFO_FLAGS_REG` where
`SGX_SECINFO_FLAGS_REG  is (SGX_PAGE_TYPE_REG << 8)`.  A similar approach can be done even for other flags like `TRIM` and `TCS` as well.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkgZQj0r52jh7hXzAq:-NJg-ovo6jhopCdaf4jV:b-bqpko9) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Correct, good catch
</blockquote></details>

Is this not done? I see the code checking for negative value in case of `EACCEPT`.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NJg0Gja51V8sXjBNFqy:b8ty2b8) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about these? Is there anyway of restoring things to some sane state or we have no choice but to exit whole process?
</blockquote></details>

Would it be better to return an `-ENOMEM` error to the caller like `mmap`? 
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 9 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJg3R-oCyFpnTh2rJ3f:-NJg3R-oCyFpnTh2rJ3g:bp05juy) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/pal/src/host/linux-sgx/enclave_edmm.c#L9)):*
> ```C
> 
> #include "api.h"
> #include "cpu.h"
> ```

Is `cpu.h` header needed?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 33 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJg70siDukWmfVgULPD:-NJg70siD [...]

2022-12-21 01:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 87 of 99 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NJk2MR6AwlAwUciBvAp:b-cfur5c) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can't we run 2 CI pipelines one with EDMM=1 and other with EDMM=0? My testing of EDMM changes with our CI tests did help me fix issues even if the tests  (like `fork` and `exec` tests) weren't directly related to memory related ones like `mmap`. So, adding EDMM to every CI test will definitely add value.  
</blockquote></details>

If you look at the implementation, we've already added a new CI pipeline running on EDMM capable machine. And yes, it's running whole test suite there

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHcwsS5BkWltD2Is3zh:-NJk2ueSCH3ZmugMLtb3:b-6o3fte) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, because we have no edmm ready CI machines.
</blockquote></details>

New CI pipeline was added.

___
___
*[`-- commits` line 15 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkaJMG0qAt2XfxoMMd):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

round trips
</blockquote></details>

Forgot to fix that, will do on final rebase
___
*[`CI-Examples/redis/redis-server.manifest.template` line 75 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJeviJg8kzaDpscZyE1:-NJk48im70HG0PFXC4gw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L75)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`allocating` -> `allocating`
</blockquote></details>

Done.
___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NJk4BfX481XyaMssXz6:b-akv4xo) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If the enclave size can be increased then `sgx.enclave_size` doesn't describe a maximal enclave size, right? The comment seems to contradict.
</blockquote></details>

The manifest entry, `sgx.enclave_size`, can be increased and it describes the maximal enclave size. By maximal enclave size I mean upper bound to which enclave size and grow in runtime.
___
*[`libos/src/sys/libos_mmap.c` line 297 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJf6kYKCYzAj8b4rPPd:-NJk4VzD-Jwqd3-ZTAtO:bvmf5tk) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/src/sys/libos_mmap.c#L297)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why do dumping of VMAs first and then call the bkeep_munmap sequence (munmap, pal_free and remove_tmp_vma) on each vma? why not use `bkeep_munmap?` Is this because `bkeep_munmap` doesn't return partial VMAs?
</blockquote></details>

Because `PalVirtualMemoryFree` does not handle memory ranges with holes, so we need to find the appropriate VMAs (I tried to make `PalVirtualMemoryFree` hole aware, but current EDMM in-kernel driver design makes that impossible, which is a pity).
Why not `bkeep_munmap` once and just `PalVirtualMemoryFree` each range? That would be a possibility, but the current implementation is more forgiving to faulty user apps. Generally calling munmap on a range with holes is dubious practice - what if another allocation lands in that hole? With the current approach at least we have sanity in LibOS - LibOS view of memory matches host, even if app does faulty things.
___
*[`libos/test/regression/openmp.manifest.template` line 12 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJfhoG09XTYiBaPp0Z3:-NJkzGKB7ZTXJlrhqZ_0:b-e3hyhk) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/test/regression/openmp.manifest.template#L12)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can we update the `manifest-syntax.rst` and `performance.rst` as well with this comment?
</blockquote></details>

Yes, but as you can see I did not touch documentation in this PR yet. I wanted to test it and have approvals we go with this approach first (and there won't be a lot of docs, so decided this can wait).
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIke9WLDfnODLtiC01J:-NJlB5y7-muKgD764Y0J:bb3zttm) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L16)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I see definition for other user leaf function definition in `enclave_api.S` why not define `EACCEPT` and `EMODPE` there?
</blockquote></details>

Because these are EDMM specific functions, why would I move them to yet another file?
Besides they can be easily inlined now.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NJlC4812yUC0yenN2ro:b-suhhu0) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

+1 to define in `sgx_arch.h`. Also, it will be consistent with other `flags` that we pass as an argument. Something like `SGX_SECINFO_FLAGS_REG` where
`SGX_SECINFO_FLAGS_REG  is (SGX_PAGE_TYPE_REG << 8)`.  A similar approach can be done even for other flags like `TRIM` and `TCS` as well.
</blockquote></details>

I now remember why: if you see this hidden behind define, you have hard time spotting errors like `SGX_SECINFO_FLAGS_REG | SGX_SECINFO_FLAGS_TCS`, where as now it's easier to spot.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkgZQj0r52jh7hXzAq:-NJlNJB35aKYky6WG7Q4:blohyia) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Is this not done? I see the code checking for negative value in case of `EACCEPT`.
</blockquote></details>

It is done. `sgx_eaccept` returns negative (or 0) values
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NJlNTJY8GADo1sNPE1X:bkhqqr3) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Would it be better to return an `-ENOMEM` error to the caller like `mmap`? 
</blockquote></details>

But we have possibly allocated some pages already so we would have to undo it, which I'm not sure is worth it (or even possible)
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 9 at r10](https://reviewable.io/reviews/gramin [...]

2022-12-22 19:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 85 of 102 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHBn-3z8qa03C9AbtOj:-NJvMhvt8-F__ZhZR6Kc:byuilfx) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you look at the implementation, we've already added a new CI pipeline running on EDMM capable machine. And yes, it's running whole test suite there
</blockquote></details>

Seems like this issue was solved by adding a new CI pipeline and testing everything. I'm resolving on my side.

___


<!-- Sent from Reviewable.io -->

2022-12-23 07:46 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 84 of 103 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NJxXGDe4dsCgPHn9Px5:b-t6ydeo) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The manifest entry, `sgx.enclave_size`, can be increased and it describes the maximal enclave size. By maximal enclave size I mean upper bound to which enclave size and grow in runtime.
</blockquote></details>

Ah so you mean to say that even if the enclave size is increased there is no negative consequences with EDMM unlike the non-EDMM case where higher enclave size would impact the load time?
___
*[`libos/src/sys/libos_mmap.c` line 297 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJf6kYKCYzAj8b4rPPd:-NJxuws-0RYYC3G6cVI1:b-f5q900) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/src/sys/libos_mmap.c#L297)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because `PalVirtualMemoryFree` does not handle memory ranges with holes, so we need to find the appropriate VMAs (I tried to make `PalVirtualMemoryFree` hole aware, but current EDMM in-kernel driver design makes that impossible, which is a pity).
Why not `bkeep_munmap` once and just `PalVirtualMemoryFree` each range? That would be a possibility, but the current implementation is more forgiving to faulty user apps. Generally calling munmap on a range with holes is dubious practice - what if another allocation lands in that hole? With the current approach at least we have sanity in LibOS - LibOS view of memory matches host, even if app does faulty things.
</blockquote></details>

So, either case we have an issue when the application calls munmap on a range with holes. Instead, can't we change `bkeep_munmap` to account for holes? I do have this in my draft PR version.
___
*[`libos/test/regression/openmp.manifest.template` line 12 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJfhoG09XTYiBaPp0Z3:-NJxoG7a5f6X9SowLpZF:bujczlz) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/test/regression/openmp.manifest.template#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, but as you can see I did not touch documentation in this PR yet. I wanted to test it and have approvals we go with this approach first (and there won't be a lot of docs, so decided this can wait).
</blockquote></details>

OK will resolve it once we have documentation added.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NJxeBwi2YfMcR4mvnXc:b-qcev1v) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I now remember why: if you see this hidden behind define, you have hard time spotting errors like `SGX_SECINFO_FLAGS_REG | SGX_SECINFO_FLAGS_TCS`, where as now it's easier to spot.
</blockquote></details>

hmm, I think the instruction itself might throw an error if we pass incorrect flags. Also, if someone is doing this, then they could also do it with an expanded version. Not sure how this can help.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkgZQj0r52jh7hXzAq:-NJxg334-yP0dPBABFEw:bxzxlol) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L54)):*
But why do this trick of returning negative value from `sgx_eaccept` and then checking (ret < 0) ? We could simply check for `if (ret)`.  Now we are propagating negative `eaccept` error code to the user which might be confusing. 

Also, I don't understand the below comment in `sgx_eaccept()`
> ENCLU returns 0 or positive error code, but Gramine expects negative values on errors.

Why would Gramine expect negative value on errors? This is just an internal function.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NJxhz_e0_T2zyCNjdui:bbyu6z) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we have possibly allocated some pages already so we would have to undo it, which I'm not sure is worth it (or even possible)
</blockquote></details>

This doesn't seem like a graceful exit.  On failure `EACCEPT` can return either `SGX_PAGE_ATTRIBUTES_MISMATCH` but this should be Gramine error for passing incorrect flags. So, this wouldn't be the case most likely. The other reason can be `SGX_NOT_TRACKED`, meaning `OS did not complete an ETRACK on the target page`. For this case, does it make sense to do retry?

Also, I think we can undo the pages allocated as we know the start address and the count of pages successfully allocated.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 33 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJg70siDukWmfVgULPD:-NJxZbbHCUX07SIfZ_WU:b-vwz2dn) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/pal/src/host/linux-sgx/enclave_edmm.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> prot here is of PAL_PROT type.

No it's not.
</blockquote></details>

ah ok, I see you converting it using `PAL_TO_SGX_PROT`



_Code quote:_
```C
sgx_edmm_add_pages
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 382 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJg_Ycb7DXGLoL379AU:-NJxkGHy6ESw3qUQJutU:b-yfng3k) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/pal/src/host/linux-sgx/host_framework.c#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's only sometimes returned, i.e. when in-kernel `EMODPR` failed, but not faulted. I don't see any point in returning it (would need to define another translations, from SGX errors to LINUX), but printing it definitely makes sense.
</blockquote></details>

OK, that helps.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkqN1y1bt1OmaGwkxs:-NJxns4F9BT7YJf8PT6G:biy5kq4) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L355)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

-1 from my side - if I see a memory managing functions without checks for return value, it immediately rings bells (and we couldn't check them if it returned `void`)
</blockquote></details>

Please see my other comment. May be should we do a clean-up on failure of these sgx_edmm_xx functions and fail gracefully? This way everything falls in place.


<!-- Sent from Reviewable.io -->

2022-12-24 00:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 82 of 103 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NK0SDAU4JVoMR_lRUYv:b2nhswy) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Ah so you mean to say that even if the enclave size is increased there is no negative consequences with EDMM unlike the non-EDMM case where higher enclave size would impact the load time?
</blockquote></details>

Yes
___
*[`libos/src/sys/libos_mmap.c` line 297 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJf6kYKCYzAj8b4rPPd:-NK0Sd3B4_XnEIWhUeXM:b-me3fi6) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/src/sys/libos_mmap.c#L297)):*
> So, either case we have an issue when the application calls munmap on a range with holes.

? The current version handles it correctly, as long as the user app does not do racy mmap+munmap. If the user app does it, there is absolutely nothing we can do in LibOS/kernel (except for keeping a consistent state and returning errors).

> Instead, can't we change bkeep_munmap to account for holes?

I don't see a reason for such complication
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NK0VORM-muaIVrzBTnm:bietbh9) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

hmm, I think the instruction itself might throw an error if we pass incorrect flags. Also, if someone is doing this, then they could also do it with an expanded version. Not sure how this can help.
</blockquote></details>

If you see `SGX_SECINFO_FLAGS_REG | SGX_SECINFO_FLAGS_TCS` it looks quite legitimate, whereas `(SGX_PAGE_TYPE_REG << SGX_SECINFO_FLAGS_TYPE_SHIFT) | (SGX_PAGE_TYPE_TCS << SGX_SECINFO_FLAGS_TYPE_SHIFT)` raises suspicion (type set 2 times?) even if you are unfamiliar / do not remember each EDMM instruction details.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkgZQj0r52jh7hXzAq:-NK0W05a8NLrWteKjr1X:b-u16gg0) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L54)):*
> But why do this trick of returning negative value from sgx_eaccept and then checking (ret < 0) ? 

What trick? Nothing tricky here

> Now we are propagating negative eaccept error code to the user which might be confusing.

We are not propagating it, just printing. The user won't have a clue what it means unless they check the source, at which point they will know the exact meaning of the printed number, regardless whether it's positive or negative.

> Why would Gramine expect negative value on errors? This is just an internal function.

Because it's our convention, where we return `0` on success and negative number on error. There is no reason to break it here whatsoever.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NK0XYERETJD7LSJXuZR:b3h46dq) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This doesn't seem like a graceful exit.  On failure `EACCEPT` can return either `SGX_PAGE_ATTRIBUTES_MISMATCH` but this should be Gramine error for passing incorrect flags. So, this wouldn't be the case most likely. The other reason can be `SGX_NOT_TRACKED`, meaning `OS did not complete an ETRACK on the target page`. For this case, does it make sense to do retry?

Also, I think we can undo the pages allocated as we know the start address and the count of pages successfully allocated.
</blockquote></details>

As far as I know all errors here are either Gramine bug or malicious host OS, so it wouldn't make sense to unwind the changes and return an error to user, if we cannot do it easily.
I've put these comments to discuss the issue, now I thought about it a bit more I'm against: mainly because there is no genuine case where it can happen.
Let's hear from others


<!-- Sent from Reviewable.io -->

2022-12-26 02:48 UTC, mkow requested changes
> Reviewed 6 of 34 files at r1, 2 of 8 files at r2, 3 of 7 files at r4, 3 of 6 files at r5, 3 of 7 files at r6, 4 of 5 files at r7, 3 of 8 files at r8, 52 of 54 files at r9, 1 of 2 files at r10, 5 of 10 files at r11, 1 of 1 files at r12, 2 of 3 files at r13, 2 of 3 files at r14, 1 of 1 files at r15, 2 of 2 files at r18, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 99 of 103 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

___
*[`-- commits` line 15 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJuSdqPAjgmQvKklYh4):*




_Suggestion:_
```
an SGX2
```
___
*[`a.sh` line 1 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufYY85fBKIvWxRIo8:-NJufYY85fBKIvWxRIo9:bplk723) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/a.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Committed accidentally, I suppose?
___
*[`CI-Examples/redis/redis-server.manifest.template` line 78 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJuhiaXDbWKSYpitfwO:-NJuhiaXDbWKSYpitfwP:b-5b9p3x) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/CI-Examples/redis/redis-server.manifest.template#L78)):*
> ```
> # `sgx.enclave_size` above describes a maximal enclave size and can usually be
> # increased without negative consequences.
> sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
> ```

TODO in the docs:
- Specify whether it _forces_ Gramine to use EDMM, or maybe `sgx.edmm_enable = true` means "use EDMM if available"?
- Mention that in the future "use EDMM if available" will be the default (will it? I think it sounds like a reasonable default).
- Document relation between EDMM and `sgx.enclave_size` (also, maybe the default for `sgx.enclave_size` should depend on EDMM being used?).
___
*[`libos/src/bookkeep/libos_vma.c` line 887 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvQgoCEVcQ8aCDzeK4:-NJvQgoCEVcQ8aCDzeK5:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/src/bookkeep/libos_vma.c#L887)):*
> ```C
> 
>     if (!is_continuous) {
>         /* When Linux fails with such an error, it sill changes permissions of the first
> ```





_Suggestion:_
```C
it still
```
___
*[`libos/test/regression/test_libos.py` line 539 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvTar7AvZy0hitsPCR:-NJvTar7AvZy0hitsPCS:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/test/regression/test_libos.py#L539)):*
> ```Python
>         self.assertIn("Test quote interface... SUCCESS", stdout)
> 
>     @unittest.skipIf(HAS_EDMM, 'EDMM machines ues DCAP attestation')
> ```





_Suggestion:_
```Python
use
```
___
*[`libos/test/regression/test_libos.py` line 546 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvTcJQEo2qsG8uPoUA:-NJvTcJQEo2qsG8uPoUB:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/test/regression/test_libos.py#L546)):*
> ```Python
>         self.assertIn("Test quote interface... SUCCESS", stdout)
> 
>     @unittest.skipIf(HAS_EDMM, 'EDMM machines ues DCAP attestation')
> ```





_Suggestion:_
```Python
use
```
___
*[`pal/include/pal/pal.h` line 227 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufBCR-PvudWRNuZvs:-NJufBCR-PvudWRNuZvt:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L227)):*
> ```objc
>  *
>  * Both `addr` and `size` must be non-zero and aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```





_Suggestion:_
```objc
must be a continuous memory range
```
___
*[`pal/include/pal/pal.h` line 239 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufJ-zAYiPN3p5fJY3:-NJufJ-zAYiPN3p5fJY4:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L239)):*
> ```objc
>  *
>  * Both `addr` and `size` must be non-zero and aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```





_Suggestion:_
```objc
must be a continuous memory range
```
___
*[`pal/include/pal/pal.h` line 428 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufNS59DAHgSXK5Xib:-NJufNS59DAHgSXK5Xic:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L428)):*
> ```objc
>  *
>  * `addr` and `size` must be aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```





_Suggestion:_
```objc
must be a continuous memory range
```
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKB6w1UA8RM941pv1zr:b-rnae7y) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As far as I know all errors here are either Gramine bug or malicious host OS, so it wouldn't make sense to unwind the changes and return an error to user, if we cannot do it easily.
I've put these comments to discuss the issue, now I thought about it a bit more I'm against: mainly because there is no genuine case where it can happen.
Let's hear from others
</blockquote></details>

If there's no legitimate case when this could happen in runtime then I wouldn't bother with complications.
Just remember to fix up these comments (in this whole file) to explain why we don't need to handle these errors gracefully.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 20 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKB2w6p8gtdG4Ze4DUn:-NKB2w6p8gtdG4Ze4DUo:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c9aa443162415c4a9c76e35e64972ad236006c17/pal/src/host/linux-sgx/enclave_edmm.c#L20)):*
> ```C
>         .flags = flags,
>     };
>     /* ENCLU returns 0 or positive error code, but Gramine expect negative values on errors.
> ```





_Suggestion:_
```C
as a convention denotes errors using negative values.
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 376 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkiiqxA6FSf1qVbLMZ:-NKBITd93IfX1ZXcMTIZ:be5zn46) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/host_framework.c#L376)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I could swear I put a comment about it somewhere... Seems I forgot.
I couldn't decide which version looks better, so I wanted to present both to reviewers, so that we decide which one to use.
cc @dimakuv @mkow 
</blockquote></details>

I'm neutral on this, both look similar in terms of readability to me. Maybe a sliiight preference towards the `count` version.
Blocking until someone decides which version to pick and then you make it consistent in this file.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 384 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKBHODFA5x37oDU2lmk:-NKBHODFA5x37oDU2lml:b-iiqkib) ([raw file](https://github.com/gramineproject/gramine/blob/c9aa443162415c4a9c76e35e6 [...]

2022-12-26 16:36 UTC, mkow reviewed
> Reviewed 6 of 34 files at r1, 1 of 7 files at r4, 3 of 8 files at r8, 4 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 412 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKEH8sj-c1ornbEQqPG:-NKEH8sj-c1ornbEQqPH:bjns8f9) ([raw file](https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/pal/src/host/linux-sgx/sgx_arch.h#L412)):*
> ```objc
> #else /* !__ASSEMBLER__ */
> 
> /* microcode to call ENCLU */
> ```

Such a good comment, we'll miss it :( Seems Gramine was programming in microcode even before PT cracked it!



_Code quote:_
```objc
/* microcode to call ENCLU */
```


<!-- Sent from Reviewable.io -->

2022-12-27 13:04 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-EDMM please (testing)

2022-12-27 21:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 95 of 104 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKKO1FT7SOyEDzYEwMM:-NKKO1FT7SOyEDzYEwMN:b-t4efnr) (no related file):*
I squashed all commits, because I was getting lost in all these fixups (and what to fix in which commit). Did not rebase though, so it shouldn't be an issue.

___
___
*[`libos/src/bookkeep/libos_vma.c` line 887 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvQgoCEVcQ8aCDzeK4:-NKKFXPb7FIn95P9R6ss:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/src/bookkeep/libos_vma.c#L887)):*
> ```C
> 
>     if (!is_continuous) {
>         /* When Linux fails with such an error, it sill changes permissions of the first
> ```

Done.
___
*[`libos/test/regression/test_libos.py` line 539 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvTar7AvZy0hitsPCR:-NKKFole0_kIe3GMDbjS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/test/regression/test_libos.py#L539)):*
> ```Python
>         self.assertIn("Test quote interface... SUCCESS", stdout)
> 
>     @unittest.skipIf(HAS_EDMM, 'EDMM machines ues DCAP attestation')
> ```

Done.
___
*[`libos/test/regression/test_libos.py` line 546 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJvTcJQEo2qsG8uPoUA:-NKKFtXS8W-wuywQ1S0I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/libos/test/regression/test_libos.py#L546)):*
> ```Python
>         self.assertIn("Test quote interface... SUCCESS", stdout)
> 
>     @unittest.skipIf(HAS_EDMM, 'EDMM machines ues DCAP attestation')
> ```

Done.
___
*[`pal/include/pal/pal.h` line 227 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufBCR-PvudWRNuZvs:-NKKG8Lj1xViAlrBAE60:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L227)):*
> ```objc
>  *
>  * Both `addr` and `size` must be non-zero and aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```

Done.
___
*[`pal/include/pal/pal.h` line 239 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufJ-zAYiPN3p5fJY3:-NKKGD8n9XdVCONMCMWx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L239)):*
> ```objc
>  *
>  * Both `addr` and `size` must be non-zero and aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```

Done.
___
*[`pal/include/pal/pal.h` line 428 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufNS59DAHgSXK5Xib:-NKKHTKR8QPd8DAaY4ih:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/pal/include/pal/pal.h#L428)):*
> ```objc
>  *
>  * `addr` and `size` must be aligned at the allocation alignment.
>  * `[addr; addr+size)` must a continuous memory range without any holes.
> ```

Done.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKKL3bK3BZdv0V8gJA0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If there's no legitimate case when this could happen in runtime then I wouldn't bother with complications.
Just remember to fix up these comments (in this whole file) to explain why we don't need to handle these errors gracefully.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 20 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKB2w6p8gtdG4Ze4DUn:-NKKJeNX2Rwy-PWU834Y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c9aa443162415c4a9c76e35e64972ad236006c17/pal/src/host/linux-sgx/enclave_edmm.c#L20)):*
> ```C
>         .flags = flags,
>     };
>     /* ENCLU returns 0 or positive error code, but Gramine expect negative values on errors.
> ```

Done.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 376 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkiiqxA6FSf1qVbLMZ:-NKKLw8u-q-ZS1hm9Qe0:b-nfso6d) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/host_framework.c#L376)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this, both look similar in terms of readability to me. Maybe a sliiight preference towards the `count` version.
Blocking until someone decides which version to pick and then you make it consistent in this file.
</blockquote></details>

I went with `count` version, as I too prefer it (but too only very slightly).
___
*[`pal/src/host/linux-sgx/host_framework.c` line 384 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKBHODFA5x37oDU2lmk:-NKKMQtu03kHplvBy6O8:b1ghrk1) ([raw file](https://github.com/gramineproject/gramine/blob/c9aa443162415c4a9c76e35e64972ad236006c17/pal/src/host/linux-sgx/host_framework.c#L384)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rename this field to `modified_length`/`modified_bytes`/`modified_size` (with a comment how it was originally named in the kernel headers). `count` is confusing, especially in this callsite.
</blockquote></details>

We cannot do that, because at some point we will switch to upstream version of this struct. Even now we define it only if it's missing.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkqN1y1bt1OmaGwkxs:-NKKN3eTDLVlcLywZU0M:b-74tje0) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L355)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please see my other comment. May be should we do a clean-up on failure of these sgx_edmm_xx functions and fail gracefully? This way everything falls in place.
</blockquote></details>

cc @mkow @dimakuv 
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 412 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKEH8sj-c1ornbEQqPG:-NKKN9F318lpw-aLcOgs:b2nhn10) ([raw file](https://github.com/gramineproject/gramine/blob/6a13434ee71cc0e420f6cf95a789d941f0b328c2/pal/src/host/linux-sgx/sgx_arch.h#L412)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Such a good comment, we'll miss it :( Seems Gramine was programming in microcode even before PT cracked it!
</blockquote></details>

RIP
___
*[`python/graminelibos/sgx_sign.py` line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUodOq8T97xemaeo3v:-NKKNF_43myE7qv5n8i3:bq7duyd) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/python/graminelibos/sgx_sign.py#L281)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We have such a comment in C code (I believe). I guess I can also add it here, but do we want it? This is merely a tool for calculating mrenclave, which just follows whatever we have in C.
</blockquote></details>

cc @mkow 
___
*[`a.sh` line 1 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJufYY85fB [...]

2022-12-27 23:26 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 95 of 104 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 15 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkaJMG0qAt2XfxoMMd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Forgot to fix that, will do on final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 15 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJuSdqPAjgmQvKklYh4):*
Done.
___
*[`CI-Examples/redis/redis-server.manifest.template` line 78 at r15](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJuhiaXDbWKSYpitfwO:-NKKhMcV58g3NcoKxJV-:b-g7m98o) ([raw file](https://github.com/gramineproject/gramine/blob/0863b60750dd8f72be01b4c6c41cbee4bb91c64b/CI-Examples/redis/redis-server.manifest.template#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO in the docs:
- Specify whether it _forces_ Gramine to use EDMM, or maybe `sgx.edmm_enable = true` means "use EDMM if available"?
- Mention that in the future "use EDMM if available" will be the default (will it? I think it sounds like a reasonable default).
- Document relation between EDMM and `sgx.enclave_size` (also, maybe the default for `sgx.enclave_size` should depend on EDMM being used?).
</blockquote></details>

1. Done (it forces)
2. Not done. I'm not sure if it will be, so I did not mention it.
3. Done. (idk, maybe, but we cannot definitely make the default insanely big, until we support `MAP_NORESERVE`)
___
*[`libos/test/regression/openmp.manifest.template` line 12 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJfhoG09XTYiBaPp0Z3:-NKKewSpELdYPymLtxRw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/libos/test/regression/openmp.manifest.template#L12)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK will resolve it once we have documentation added.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-29 15:06 UTC, mkow reviewed
> Reviewed 2 of 4 files at r20, 2 of 2 files at r21, 5 of 5 files at r22, 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTHtRF0hMj6XCLqaLl:-NKTHtRG712dTfDNNmnq:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
> ```reStructuredText
> When this feature is enabled, Gramine does not add heap pages (uninitialized
> memory) to the enclave at creation time. Instead, memory is added to the enclave
> on demand. This can greatly reduce startup time for bigger enclave, reduces
> ```





_Suggestion:_
```reStructuredText
startup time for bigger enclaves
```
___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTM6IV8Beaf3vHn0ZH:-NKTM6IW7-tI9nGemAbB:b-o9hxpj) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
> ```reStructuredText
> When this feature is enabled, Gramine does not add heap pages (uninitialized
> memory) to the enclave at creation time. Instead, memory is added to the enclave
> on demand. This can greatly reduce startup time for bigger enclave, reduces
> ```

ditto later in this sentence



_Suggestion:_
```reStructuredText
reduce
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 384 at r19](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKBHODFA5x37oDU2lmk:-NKTO-QM-ttT68-M7yfD:bu1m3vp) ([raw file](https://github.com/gramineproject/gramine/blob/c9aa443162415c4a9c76e35e64972ad236006c17/pal/src/host/linux-sgx/host_framework.c#L384)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We cannot do that, because at some point we will switch to upstream version of this struct. Even now we define it only if it's missing.
</blockquote></details>

Ah, right, too bad.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkqN1y1bt1OmaGwkxs:-NKTP-HpDbA95sCo2OwQ:b-w1jvjz) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L355)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

cc @mkow @dimakuv 
</blockquote></details>

I didn't reply here because I'm not sure which version I prefer. But, what if we changed the names to something like `sgx_edmm_set_page_permissions_or_die()`?
___
*[`python/graminelibos/sgx_sign.py` line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUodOq8T97xemaeo3v:-NKTPZ8a3Z2OHbkuRrwN:bui69t6) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/python/graminelibos/sgx_sign.py#L281)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

cc @mkow 
</blockquote></details>

I'd add a comment at the top pointing at the C code for more documentation/explanations.


<!-- Sent from Reviewable.io -->

2022-12-29 15:13 UTC, vijaydhanraj reviewed
> Reviewed 2 of 4 files at r20, 4 of 5 files at r22, 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 16 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTFjMw-IMPhqlWSclJ):*
change page permissions
___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NKQU4eECY1YbmFd6Tcw:ba0psfo) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Can we reword this to be more explicit?
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKSmL2_CljiQQSdyH3S:bcs2qev) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
> ```reStructuredText
>     (Default: false)
> 
> This setting enables the :term:`EDMM` feature (after-enclave-creation memory
> ```

Why not simply call enclave dynamic memory as the acronymn stands for?



_Code quote:_
```reStructuredText
after-enclave-creation
```
___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmfY4C3Pd-LjDjVL-:-NKSmfY4C3Pd-LjDjVL0:b-l6sjth) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
> ```reStructuredText
> When this feature is enabled, Gramine does not add heap pages (uninitialized
> memory) to the enclave at creation time. Instead, memory is added to the enclave
> on demand. This can greatly reduce startup time for bigger enclave, reduces
> ```

reduce



_Code quote:_
```reStructuredText
reduces
```
___
*[`Documentation/manifest-syntax.rst` line 457 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSpDwU5DvIND2qEB1c:-NKSpDwU5DvIND2qEB1d:bzcwzt) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L457)):*
> allows for changing memory permissions (without this Gramine allocates all dynamic memory
as RWX).

Chaning page permission is a SGX2 feature and isn't related to adding memory dynamically and so it is better to decouple this statement when talking about EDMM.
___
*[`Documentation/manifest-syntax.rst` line 505 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSqgcM1kVtwhEdi1Uh:-NKSqgcM1kVtwhEdi1Ui:bkpab11) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L505)):*
> Note this not apply to the enclaves with :term:`EDMM` enabled, where memory is not reserved upfront and

Note this *does* not apply...
___
*[`Documentation/sgx-intro.rst` line 277 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSrPyaCnjwVTVsDJCB:-NKSrPyaCnjwVTVsDJCC:bgczq7) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/sgx-intro.rst#L277)):*
> ```reStructuredText
>    EDMM
>       A |~| hardware feature of :term:`SGX2`, allows for dynamic (in enclave
>       runtime) addition, removal and change of enclave memory, which in turn
> ```

you mean change page permission? If so, please add it as this looks little ambiguous.



_Code quote:_
```reStructuredText
change
```
___
*[`libos/src/bookkeep/libos_vma.c` line 769 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKT5WlOAXyboMAGtzGb:-NKT5WlOAXyboMAGtzGc:bgkc3hi) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/libos/src/bookkeep/libos_vma.c#L769)):*
> ```C
> }
> 
> void bkeep_convert_tmp_vma_to_user(void* _vma) {
> ```

Is this function introduced to fix any race condition during allocation of the requested range(MMAP_FIXED) ? or is this just an optimization?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NKTKB3uCU9ObgvWndZR:b-du5c9k) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If you see `SGX_SECINFO_FLAGS_REG | SGX_SECINFO_FLAGS_TCS` it looks quite legitimate, whereas `(SGX_PAGE_TYPE_REG << SGX_SECINFO_FLAGS_TYPE_SHIFT) | (SGX_PAGE_TYPE_TCS << SGX_SECINFO_FLAGS_TYPE_SHIFT)` raises suspicion (type set 2 times?) even if you are unfamiliar / do not remember each EDMM instruction details.
</blockquote></details>

I still don't see an issue as I read this as number of bits to shift to set the page type. If it is misleading, how about changing `SGX_SECINFO_FLAGS_TYPE_SHIFT` -> `PAGE_TYPE_SHIFT`. Also, this will be more consistent with in-kernel driver, https://elixir.bootlin.com/linux/latest/source/arch/x86/include/asm/sgx.h#L274.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKTPKWE7pUcrZ6a1XFY:b-nqwxt4) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
> I'm against: mainly because there is no genuine case where it can happen

I don't think we can generalize it. For example, for restrict IOCTL can return only with partial success. The in-kernel driver states that `It is possible for the permission change request to fail on any page within the provided range, either with an error encountered by the kernel or by the SGX hardware while running ENCLS[EMODPR]..`

This is also the case of remove IOCTL as well.


<!-- Sent from Reviewable.io -->

2022-12-29 16:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 16 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTFjMw-IMPhqlWSclJ):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

change page permissions
</blockquote></details>

Not only permissions but also types, which was generalized to simply "change of enclave pages". I guess I could add `enclave pages' permissions and types`, but should I?
___
*[`CI-Examples/redis/redis-server.manifest.template` line 77 at r10](https://reviewable.io/reviews/gramineproject/gramine/1054#-NJewXRm7RplS8uVJS64:-NKTbpNXBDArXBpE01CT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ecb1f8e229134f594a0f9c892067f46664e996c8/CI-Examples/redis/redis-server.manifest.template#L77)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can we reword this to be more explicit?
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKTTTKd26_GCVmZhIy0:b-79o9ki) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why not simply call enclave dynamic memory as the acronymn stands for?
</blockquote></details>

Part in parentheses is a short summary of what EDMM is (or actually what it is in Gramine currently). I feel like the current version is more explicit than "enclave dynamic memory".
___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTHtRF0hMj6XCLqaLl:-NKTURpH4LGjqY-5tLwX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
> ```reStructuredText
> When this feature is enabled, Gramine does not add heap pages (uninitialized
> memory) to the enclave at creation time. Instead, memory is added to the enclave
> on demand. This can greatly reduce startup time for bigger enclave, reduces
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTM6IV8Beaf3vHn0ZH:-NKTUUJGCdxN9gTRhlLb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto later in this sentence
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 455 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmfY4C3Pd-LjDjVL-:-NKTUVUH3FVLEVLZv8gI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L455)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

reduce
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 457 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSpDwU5DvIND2qEB1c:-NKTUuKZ2QthOPxv1LlV:b-obe43h) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L457)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> allows for changing memory permissions (without this Gramine allocates all dynamic memory
as RWX).

Chaning page permission is a SGX2 feature and isn't related to adding memory dynamically and so it is better to decouple this statement when talking about EDMM.
</blockquote></details>

There's `Memeory Management` in EDMM and changing memory permissions **is** memory management.
___
*[`Documentation/manifest-syntax.rst` line 505 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSqgcM1kVtwhEdi1Uh:-NKTVrO31o6oyxtJq7jF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L505)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> Note this not apply to the enclaves with :term:`EDMM` enabled, where memory is not reserved upfront and

Note this *does* not apply...
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 277 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSrPyaCnjwVTVsDJCB:-NKTWcKF8hASQ1AnWWq_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/sgx-intro.rst#L277)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

you mean change page permission? If so, please add it as this looks little ambiguous.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 769 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKT5WlOAXyboMAGtzGb:-NKTX4kODEGQXXVVJI9d:bh0sw0o) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/libos/src/bookkeep/libos_vma.c#L769)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Is this function introduced to fix any race condition during allocation of the requested range(MMAP_FIXED) ? or is this just an optimization?
</blockquote></details>

Neither. It's needed by new code, which does not support holes in memory passed to `PalMemoryFree`
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkhXOt9FEVJCwBew7b:-NKTY0xH5rsOsamWEiQM:b-14y097) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L51)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I still don't see an issue as I read this as number of bits to shift to set the page type. If it is misleading, how about changing `SGX_SECINFO_FLAGS_TYPE_SHIFT` -> `PAGE_TYPE_SHIFT`. Also, this will be more consistent with in-kernel driver, https://elixir.bootlin.com/linux/latest/source/arch/x86/include/asm/sgx.h#L274.
</blockquote></details>

1. `PAGE_TYPE_SHIFT` is more ambiguous, I don't see how's that better
2. I don't find in-kernel driver compelling, so I don't see a reason to be consistent with it in terms of naming and overall design.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKTYh-n44rCWOrx4w6a:b-wthaje) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> I'm against: mainly because there is no genuine case where it can happen

I don't think we can generalize it. For example, for restrict IOCTL can return only with partial success. The in-kernel driver states that `It is possible for the permission change request to fail on any page within the provided range, either with an error encountered by the kernel or by the SGX hardware while running ENCLS[EMODPR]..`

This is also the case of remove IOCTL as well.


</blockquote></details>

??? This is in-enclave code, it does not handle ioctls
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/ [...]

2022-12-29 23:53 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 21 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

___
*[`-- commits` line 16 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTFjMw-IMPhqlWSclJ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not only permissions but also types, which was generalized to simply "change of enclave pages". I guess I could add `enclave pages' permissions and types`, but should I?
</blockquote></details>

I'd keep the current wording. If you say "page types" then you need to also explain what are these "page types", which is an SGX-specific thing.
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKVHW_x9pq83_Sm7pco:byin4gn) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Part in parentheses is a short summary of what EDMM is (or actually what it is in Gramine currently). I feel like the current version is more explicit than "enclave dynamic memory".
</blockquote></details>

+1 to keep the current wording.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 355 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkqN1y1bt1OmaGwkxs:-NKVIKGJ10zCTcF83Cd4:b1ccc5m) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_files.c#L355)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

A bit log, but we we decide to set the return type to `void` that would be the way. So we have to options and different opinions:
1) Leave the current version - handle errors in callsites and leave return type as `int` (even though *in practice* this function always returns 0 and just dies on errors)
2) Remove error handling in callsites and change it to `void sgx_edmm_set_page_permissions_or_die(uint64_t addr, size_t count, uint64_t prot)`

I vote for 1
</blockquote></details>

I'm equally fine with both 1 and 2.


<!-- Sent from Reviewable.io -->

2023-01-02 12:51 UTC, dimakuv requested changes
> Reviewed 1 of 7 files at r4, 2 of 6 files at r5, 4 of 5 files at r7, 5 of 8 files at r8, 52 of 54 files at r9, 4 of 10 files at r11, 1 of 3 files at r13, 1 of 1 files at r15, 1 of 2 files at r18, 2 of 3 files at r19, 2 of 2 files at r21, 5 of 5 files at r22, 1 of 3 files at r23, 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 35 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUoriL3_YqyoEZl_Xd:-NKm61qz4d5zylDt8n2L:bpq3y4r) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will need documentation and some additional CI tests. Can be taken from Vijay's PR https://github.com/gramineproject/gramine/pull/1006, if we decide to go with this PR.
</blockquote></details>

This was done in the meantime, resolving.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKmC1qo6iJAzxaiQ6kR:b-ykm06g) (no related file):*
Actually, with EDMM enabled in the manifest, we may allow users to omit `sgx.enclave_size` and assign some large value to it like 64GB. Currently the default is 256MB, which is very small (it was intentionally chosen to decrease the enclave startup time).

So we could introduce the logic in our Python manifest-expansion script like this:
```
sgx.enclave_size = 256MB
if sgx.edmm_enable option is enabled and sgx.enclave_size is empty:
    sgx.enclave_size = 64GB
```

This is for a follow-up PR, if we ever feel the need for this simplication.

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
Technically, this PR adds only a subset of possible functionality. In particular, this PR doesn't add the ability to create new enclave threads dynamically. So it would be better to change the title to like `Add initial EDMM support (only enclave pages)`. Can we do it at final rebase?
___
*[`.ci/linux-sgx-edmm.jenkinsfile` line 12 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm8twB3MGBWJueRJCT:-NKm8twB3MGBWJueRJCU:bwjfby8) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/linux-sgx-edmm.jenkinsfile#L12)):*
> ```
> 
>     env.DOCKER_ARGS_SGX += '''
>         --volume=/usr/include/x86_64-linux-gnu/asm/sgx.h:/usr/include/asm/sgx.h:ro
> ```

Nice trick, but why do the paths differ? The host is not Ubuntu, and has a different idea about where to put `sgx.h` header?
___
*[`.ci/ubuntu20.04.dockerfile` line 75 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm9GhJBGftUpWtQgfb:-NKm9GhJBGftUpWtQgfc:btypwtj) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/ubuntu20.04.dockerfile#L75)):*
> ```Dockerfile
>     zlib1g-dev
> 
> # Needed by "CI-Examples/ra-tls-mbedtls"
> ```

Technically, this is needed only for DCAP scheme of attestation, so the comment is incomplete (also, `ra-tls-secret-prov` example needs this as well). But not blocking.
___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 122 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmABWD1Fv0ZwJq1Vxi:-NKmABWD1Fv0ZwJq1Vxj:bq9aos3) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/lib/stage-test-sgx.jenkinsfile#L122)):*
> ```
>                 make check_dcap_fail RA_TYPE=dcap; \
>             else \
>                 echo "Invalid RA_TYPE env varible: ${RA_TYPE}"; \
> ```

typo: `variable`
___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 142 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmAEE50fS3l68oUUNt:-NKmAEE50fS3l68oUUNu:bq9aos3) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/lib/stage-test-sgx.jenkinsfile#L142)):*
> ```
>                 make check_dcap RA_TYPE=dcap; \
>             else \
>                 echo "Invalid RA_TYPE env varible: ${RA_TYPE}"; \
> ```

typo: `variable`
___
*[`CI-Examples/redis/redis-server.manifest.template` line 71 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmBVwB-3z25KUCQCkK:-NKmBVwB-3z25KUCQCkL:b-7j1oac) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/CI-Examples/redis/redis-server.manifest.template#L71)):*
> ```
> # result in longer startup times, smaller enclave sizes are not enough for
> # typical Redis workloads.
> sgx.enclave_size = "1024M"
> ```

Btw, with EDMM introduced, we may want to rename this option to `sgx.max_size`, analogous to how we renamed `sgx.thread_num` to `sgx.max_threads`.
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKmCk-u38zJcsclE6ro:byin4gn) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to keep the current wording.
</blockquote></details>

+1 to keep the current wording.
___
*[`Documentation/manifest-syntax.rst` line 457 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSpDwU5DvIND2qEB1c:-NKmD4sK4kcoB8pRgJBb:b-fh3xk5) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L457)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There's `Memeory Management` in EDMM and changing memory permissions **is** memory management.
</blockquote></details>

I agree with Borys. I didn't understand @vijaydhanraj comment. By definition, memory management is about three things: adding memory, removing memory, changing memory characteristics (permissions, type). So the current wording looks right.
___
*[`Documentation/manifest-syntax.rst` line 459 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmDN7B6spqQT1_Dmdy:-NKmDN7B6spqQT1_Dmdz:bfpsbyq) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/Documentation/manifest-syntax.rst#L459)):*
> ```reStructuredText
> changing memory permissions (without this Gramine allocates all dynamic memory
> as RWX). Unfortunately it can negatively impact performance, as adding a page
> to the enclave is more expensive operation in runtime than before enclave
> ```

Strange English. I would rephrase to:
```
as RWX). Unfortunately it can negatively impact performance, as adding a page
to the enclave at runtime is a more expensive operation than adding the page
before enclave creation (because it involves more enclave exits and syscalls).
```
___
*[`Documentation/manifest-syntax.rst` line 812 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmE01R-gTSe8VuJr9n:-NKmE01R-gTSe8VuJr9o:b-cg0a10) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/Documentation/manifest-syntax.rst#L812)):*
> ```reStructuredText
> large enough to hold the whole heap area.
> 
> This option is invalid (i.e. must be ``false``) together with
> ```

Strange English. Suggestion: `if specified together with ...`
___
*[`Documentation/manifest-syntax.rst` line 813 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmE7Pv1BLeREiu5xrf:-NKmE7Pv1BLeREiu5xrg:b3yeg2f) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/Documentation/manifest-syntax.rst#L813)):*
> ```reStructuredText
> 
> This option is invalid (i.e. must be ``false``) together with
> ``sgx.edmm_enab [...]

2023-01-02 13:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 35 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @vijaydhanraj)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/1054#-NHUkabH5zSjkrPCuxbY:-NKmeHge9K936GNFWqlM:b-ma7o23) ([raw file](https://github.com/gramineproject/gramine/blob/a26d8af16df85a580742f0e4cec40eb4d81caa42/pal/src/host/linux-sgx/host_framework.c#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me check this now, after rebase...
</blockquote></details>

After rebase, it works fine!


<!-- Sent from Reviewable.io -->

2023-01-02 22:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKoPRLR2ox43EmJB_tu:b8ylza5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, with EDMM enabled in the manifest, we may allow users to omit `sgx.enclave_size` and assign some large value to it like 64GB. Currently the default is 256MB, which is very small (it was intentionally chosen to decrease the enclave startup time).

So we could introduce the logic in our Python manifest-expansion script like this:
```
sgx.enclave_size = 256MB
if sgx.edmm_enable option is enabled and sgx.enclave_size is empty:
    sgx.enclave_size = 64GB
```

This is for a follow-up PR, if we ever feel the need for this simplication.
</blockquote></details>

We shouldn't do this.
Some apps mmap huge parts of memory with MAP_NORESERVE and depend on lazy allocation/COW. Limiting the addres space (with `enclave_size`) is the only way to go currently.

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically, this PR adds only a subset of possible functionality. In particular, this PR doesn't add the ability to create new enclave threads dynamically. So it would be better to change the title to like `Add initial EDMM support (only enclave pages)`. Can we do it at final rebase?
</blockquote></details>

Is that part of EDMM or just SGX2 in general? (EDMM has memory management in the name)
___
*[`.ci/linux-sgx-edmm.jenkinsfile` line 12 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm8twB3MGBWJueRJCT:-NKoQEsC3V9nG2_NPnP-:bpsn06w) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/linux-sgx-edmm.jenkinsfile#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice trick, but why do the paths differ? The host is not Ubuntu, and has a different idea about where to put `sgx.h` header?
</blockquote></details>

Yes, the host is Debian
___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 122 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmABWD1Fv0ZwJq1Vxi:-NKoR04S2vknh5vvniyY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/lib/stage-test-sgx.jenkinsfile#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `variable`
</blockquote></details>

Done.
___
*[`.ci/lib/stage-test-sgx.jenkinsfile` line 142 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmAEE50fS3l68oUUNt:-NKoR3eI-MmmyXn_kK1U:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/.ci/lib/stage-test-sgx.jenkinsfile#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `variable`
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 459 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmDN7B6spqQT1_Dmdy:-NKoSUovEcW9N4rux_Xf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Strange English. I would rephrase to:
```
as RWX). Unfortunately it can negatively impact performance, as adding a page
to the enclave at runtime is a more expensive operation than adding the page
before enclave creation (because it involves more enclave exits and syscalls).
```
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 812 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmE01R-gTSe8VuJr9n:-NKoSbua2cQmO0jG8HXE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/Documentation/manifest-syntax.rst#L812)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Strange English. Suggestion: `if specified together with ...`
</blockquote></details>

Done.
___
*[`libos/include/libos_vma.h` line 72 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmGmpr26fMUyofnQyj:-NKoSlI-7Vr72d7pFJ2p:b-u042sx) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is purely a perf optimization, right? To not do the removal of the temporary VMA.
</blockquote></details>

No. This temporary VMA prevents other mmpas from aliasing with it (e.g. because we are in the middle of munmap or mmap_fixed)
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKoU1-rEIZOVH9OKFyB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh, we have differing function signatures for no good reason. Can we change this func to also have `include_unmapped`, `ret_infos`, `ret_count`?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1276 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmFAlFB2M7LmHeSLGZ:-NKoU_0t0CGeiURbOWYR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/src/bookkeep/libos_vma.c#L1276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_mmap.c` line 346 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmHWaI1UNAvZXR2EmU:-NKoUw_K80LrjP9OoGPQ:b2oyhw8) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/src/sys/libos_mmap.c#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have to do `bkeep_munmap()` and `bkeep_remove_tmp_vma()` inside the for loop? In the mmap code above, we do these ops outside the loop. This also enables to return an error if `bkeep_munmap()` failed, instead of the `BUG` as is here currently.
</blockquote></details>

See the closed discussion above
___
*[`libos/test/regression/test_libos.py` line 539 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIdNPBxg3DHerUKI2:-NKoV3Bp5Dzy7FjgbwNl:b-yyspzz) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we skip? These two tests can run Ok with DCAP-attestation machines.
</blockquote></details>

Then please debug why they fail, I don't have time for that :(
___
*[`libos/test/regression/test_libos.py` line 546 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIlFB13td_MeCt5WA:-NKoV8IiDcLnqCSlYc_4:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L546)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></sum [...]

2023-01-02 23:55 UTC, mkow reviewed
> Reviewed 8 of 8 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKosHO8D3ORSHpk--Qm:bh204xe) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We shouldn't do this.
Some apps mmap huge parts of memory with MAP_NORESERVE and depend on lazy allocation/COW. Limiting the addres space (with `enclave_size`) is the only way to go currently.
</blockquote></details>

But with EDMM we could implement `MAP_NORESERVE`? Maybe we should add a TODO somewhere then?

___
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKotITuEmcH0t65xdNP:b1e3ehu) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, why is it `ret_`, not `out_`?


<!-- Sent from Reviewable.io -->

2023-01-03 01:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 16 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKTFjMw-IMPhqlWSclJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd keep the current wording. If you say "page types" then you need to also explain what are these "page types", which is an SGX-specific thing.
</blockquote></details>

Yes, we can add change page permission and types as it is more explicit and clearer. But resolving it and will leave it to the maintainers.

One thing is we need not explain page types here but can simply add a pointer to the SDM.
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKoz-xAB8swMd3Poqll:bf7vawn) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to keep the current wording.
</blockquote></details>

But doesn't dynamic mean the same thing? If we read further, the text says `When this feature is enabled, Gramine does not add heap pages (uninitialized memory) to the enclave at creation time. Instead, memory is added to the enclave on demand....`

To be more explicit we could have just called it `runtime memory management` as well.

I feel like we are repeating ourselves. But resolving as maintainers feel otherwise.
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKp5vgl5nsfS6wZi8aa:b2iemky) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FWIW, I'm fine with the current "kill the process" logic. `SGX_NOT_TRACKED` error can only happen in malicious/broken OS kernel.
</blockquote></details>

 > error can only happen in malicious/broken OS kernel.

IOCTLs like restrict and remove can return with partial success which is a genuine case. But the value returned will be `-EFAULT` and so the current implementation will treat this as error and kill the process. @dimakuv, @boryspoplawski so do we want to abort and kill the process for such cases too?


<!-- Sent from Reviewable.io -->

2023-01-03 01:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKp9TYy8Bdkn9TM0La5:btm63yk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But with EDMM we could implement `MAP_NORESERVE`? Maybe we should add a TODO somewhere then?
</blockquote></details>

`MAP_NORESERVE` is only a part, not faulting the pages is also important.

___
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKpAHar4yycQc3UmCvw:b-9xu9zu) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why is it `ret_`, not `out_`?
</blockquote></details>

Because it predates this `out_` convention.


<!-- Sent from Reviewable.io -->

2023-01-03 01:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKpEOczAVEZI8qY1kGO:b-nlf51p) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`MAP_NORESERVE` is only a part, not faulting the pages is also important.
</blockquote></details>

You mean we shouldn't fault+allocate them during mmap? Sounds doable for this case, assuming that such mappings usually have a distinct set of flags passed to mmap (like `MAP_NORESERVE`). This will make Java (for example) slow, but at least it will be working correctly in the default config.
If that's right, then IMO it's worth a TODO.

___
___
*[`Documentation/manifest-syntax.rst` line 449 at r23](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKSmL2_CljiQQSdyH3R:-NKpFZ-MEEWBf4T-Ofj-:brue0d8) ([raw file](https://github.com/gramineproject/gramine/blob/8df8d06dc77f8781b3bfb2c3a48ab2c91e68b5c3/Documentation/manifest-syntax.rst#L449)):*
I still don't get what's wrong with the current version. It's short and precise, and the text below is a longer and more detailed version.

> To be more explicit we could have just called it `runtime memory management` as well.

I don't understand... "after-enclave-creation" is more precise than "runtime".

> But resolving as maintainers feel otherwise.

You're still blocking.
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKpGMXs5kn0uznObh-Q:b-u31yk9) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because it predates this `out_` convention.
</blockquote></details>

That's not an answer, but now I see that there are other functions in this file which have this, so you just followed the local style.
Not blocking, but I'd rather use the new style in new code (and you added/changed this one now).


<!-- Sent from Reviewable.io -->

2023-01-03 09:17 UTC, dimakuv requested changes
> Reviewed 5 of 8 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKqqWuTBKZwCpzpf1Bm:b-atf7n8) (no related file):*
> `MAP_NORESERVE` is only a part, not faulting the pages is also important.

I also didn't understand this comment. Do you mean that Gramine would need to somehow instruct the SGX driver to not fault-in such pages (i.e., SGX driver should raise a SIGSEGV that Gramine should not try to resolve but simply to forward to the app)?

Anyway, this deserves a TODO comment or a GitHub issue.

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is that part of EDMM or just SGX2 in general? (EDMM has memory management in the name)
</blockquote></details>

According to the original presentation on EDMM (https://caslab.csl.yale.edu/workshops/hasp2016/HASP16-16_slides.pdf), this is part of EDMM. See slide 10 for example.
___
*[`libos/include/libos_vma.h` line 72 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmGmpr26fMUyofnQyj:-NKqsHSl3TV_90MyWbHy:b-4hvi0m) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. This temporary VMA prevents other mmpas from aliasing with it (e.g. because we are in the middle of munmap or mmap_fixed)
</blockquote></details>

Got it.
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKqsPTMEIoKvkiTjGev:b-v2pbpm) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not an answer, but now I see that there are other functions in this file which have this, so you just followed the local style.
Not blocking, but I'd rather use the new style in new code (and you added/changed this one now).
</blockquote></details>

I don't care much about `ret_` vs `out_`, so I'm unblocking.
___
*[`libos/src/sys/libos_mmap.c` line 346 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmHWaI1UNAvZXR2EmU:-NKqtPBe807iajYQfiP3:b-pkw0ra) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/src/sys/libos_mmap.c#L346)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

See the closed discussion above
</blockquote></details>

Ok, so this implementation is to reduce the races (if the user app does munmap + mmap in parallel)? Like, with this implementation, the window between how Gramine LibOS sees VMAs (modified in `bkeep_munmap()`) and how host OS sees VMAs (modified in `PalVirtualMemoryFree()`) is minimal. Is my understanding correct?
___
*[`libos/test/regression/test_libos.py` line 539 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIdNPBxg3DHerUKI2:-NKqtvg12roYE49IFIjP:balwtdy) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L539)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please debug why they fail, I don't have time for that :(
</blockquote></details>

Ok, definitely not for this PR. Could you please create a GitHub issue to debug/fix this after this PR is merged and assign me?
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKquSJsEkC-0BvAEsGY:b-s6q4lh) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
> IOCTLs like restrict and remove can return with partial success which is a genuine case. But the value returned will be `-EFAULT` ...

Is this true? What are these cases when these IOCTLs return `-EFAULT`? This sounds very unnatural to me, could you provide links to the code?


<!-- Sent from Reviewable.io -->

2023-01-03 11:36 UTC, woju commented
Jenkins, test pkg-deb-debian11 please

2023-01-03 11:52 UTC, woju commented
Jenkins, test Docs please

2023-01-03 17:13 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKsYrjF9L3leGUU-J76:b187qpr) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> IOCTLs like restrict and remove can return with partial success which is a genuine case. But the value returned will be `-EFAULT` ...

Is this true? What are these cases when these IOCTLs return `-EFAULT`? This sounds very unnatural to me, could you provide links to the code?
</blockquote></details>

Please see this for restricting IOCTL: https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc

Snippet text from the commit log: `...To support partial success the ioctl() returns an error code based on failures encountered by the kernel as well as two result output parameters: one for the number of pages that were successfully changed and one for the SGX return code....`

Here is one case where the return value is updated as part of the `modp` struct: https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc#diff-561fefd75368bfd99ae276f6bae28dfa1e2507ea1b80ccdcb8866ee4012b0c23R793

And here is where the partial count on failure is updated: 
https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc#diff-561fefd75368bfd99ae276f6bae28dfa1e2507ea1b80ccdcb8866ee4012b0c23R812

Please see this for modify type IOCTL: (this IOCTL is invoked as part of the remove flow) https://github.com/rchatre/linux/commit/00bc55a4afdfc6188a66e1a9b57cd160b535a4ab


<!-- Sent from Reviewable.io -->

2023-01-03 17:27 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKrLsRT-ysMyU5ColZv:bhare4l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> `MAP_NORESERVE` is only a part, not faulting the pages is also important.

I also didn't understand this comment. Do you mean that Gramine would need to somehow instruct the SGX driver to not fault-in such pages (i.e., SGX driver should raise a SIGSEGV that Gramine should not try to resolve but simply to forward to the app)?

Anyway, this deserves a TODO comment or a GitHub issue.
</blockquote></details>

No, it should be Gramine emulating this completely (including allocating pages on faults if necessary).
Could you create a GH issue for this?

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

According to the original presentation on EDMM (https://caslab.csl.yale.edu/workshops/hasp2016/HASP16-16_slides.pdf), this is part of EDMM. See slide 10 for example.
</blockquote></details>

I guess there is no limit for threads except for TCS slots, which need to be allocated in memory, so it makes some sense.
So the new commit message could be `[PAL/Linux-SGX] Add initial EDMM support (only regular pages)`
___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKscp6fEOFD9WqeCWgM:b-3hwieg) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
> That's not an answer

It is, this function was created long time ago, when we didn't use `out_` convention.
Anyway, feel free to change it
___
*[`libos/src/sys/libos_mmap.c` line 346 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmHWaI1UNAvZXR2EmU:-NKsdiq39wcC5jidxKpU:bwjf1ql) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/src/sys/libos_mmap.c#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, so this implementation is to reduce the races (if the user app does munmap + mmap in parallel)? Like, with this implementation, the window between how Gramine LibOS sees VMAs (modified in `bkeep_munmap()`) and how host OS sees VMAs (modified in `PalVirtualMemoryFree()`) is minimal. Is my understanding correct?
</blockquote></details>

First part yes, but I did not understand the 2nd part.
The problem is that we have to dump the vmas (`dump_vmas_in_range`, because we can only call `PalVirtualMemoryFree` on actually allocated memory) and only then we can call `bkeep_munmap()`. If we called it on the whole range, then there would be a window (between `dump_...` and `bkeep_munmap`) where app could call `mmap(NULL, ...)` and get some memory from the range being freed. This is of course not possible in correctly written apps, nevertheless there is no reason for not removing that race window (implemented in the current version). Especially since freeing ranges with holes rarely happens, so performance is not an issue whatsoever.
___
*[`libos/test/regression/test_libos.py` line 539 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIdNPBxg3DHerUKI2:-NKsedwK1IUZ6eNAP81M:b2zr7m3) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, definitely not for this PR. Could you please create a GitHub issue to debug/fix this after this PR is merged and assign me?
</blockquote></details>

Please do that
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKpAlV5-o2rN00YjQAO:bhggewq) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please see this for restricting IOCTL: https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc

Snippet text from the commit log: `...To support partial success the ioctl() returns an error code based on failures encountered by the kernel as well as two result output parameters: one for the number of pages that were successfully changed and one for the SGX return code....`

Here is one case where the return value is updated as part of the `modp` struct: https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc#diff-561fefd75368bfd99ae276f6bae28dfa1e2507ea1b80ccdcb8866ee4012b0c23R793

And here is where the partial count on failure is updated: 
https://github.com/rchatre/linux/commit/c2b9e8a97e6f255569a8d4671ff4e11618770ebc#diff-561fefd75368bfd99ae276f6bae28dfa1e2507ea1b80ccdcb8866ee4012b0c23R812

Please see this for modify type IOCTL: (this IOCTL is invoked as part of the remove flow) https://github.com/rchatre/linux/commit/00bc55a4afdfc6188a66e1a9b57cd160b535a4ab
</blockquote></details>

All you linked does not happen on bug-free Gramine and non-malicious OS.


<!-- Sent from Reviewable.io -->

2023-01-04 14:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 8 files at r25.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 10 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmC1qo6iJAzxaiQ6kQ:-NKxA82rEhrWgOQ7Q17T:b-2e2488) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it should be Gramine emulating this completely (including allocating pages on faults if necessary).
Could you create a GH issue for this?
</blockquote></details>

https://github.com/gramineproject/gramine/issues/1099

Done. I hope I summarized correctly.

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess there is no limit for threads except for TCS slots, which need to be allocated in memory, so it makes some sense.
So the new commit message could be `[PAL/Linux-SGX] Add initial EDMM support (only regular pages)`
</blockquote></details>

This new commit message looks good to me, unblocking but please don't forget.
___
*[`libos/test/regression/test_libos.py` line 539 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIdNPBxg3DHerUKI2:-NKxB75LEllCJFBCurQ4:bxyddj5) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L539)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please do that
</blockquote></details>

Done https://github.com/gramineproject/gramine/issues/1100
___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKwwucK74kjcPlCBd4Q:b-e3zd3j) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All you linked does not happen on bug-free Gramine and non-malicious OS.
</blockquote></details>

Yep, if I understand correctly, there should never be the case of e.g. `emodpr` failing on a page, if Gramine did everything correctly.


<!-- Sent from Reviewable.io -->

2023-01-04 15:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/enclave_edmm.c` line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIs45j1AIS5co7OiVNq:-NKxKjk9AIVXJd9bmlYL:b-7lishy) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/enclave_edmm.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, if I understand correctly, there should never be the case of e.g. `emodpr` failing on a page, if Gramine did everything correctly.
</blockquote></details>

OK, resolving.


<!-- Sent from Reviewable.io -->

2023-01-05 01:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 10 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`libos/include/libos_vma.h` line 124 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmEiF-1i_Q_nvMTYUr:-NKzcdGM5mub2k8jVfPH:b-ivo2c) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/include/libos_vma.h#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, but it didn't have _any_ of {`ret_`, `out_`}, you added them in this PR, that's what I mean.
</blockquote></details>

It had `ret_`, but only in `.c`, from which I copied the signature (but seems that `.h` had it without the prefix, as you say)
___
*[`libos/test/regression/test_libos.py` line 539 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKmIdNPBxg3DHerUKI2:-NKzcm7X3G6Y2vks0xR-:b-zcjvte) ([raw file](https://github.com/gramineproject/gramine/blob/cffa1fb7fd855849da4e8cbc26a3027710724b2e/libos/test/regression/test_libos.py#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done https://github.com/gramineproject/gramine/issues/1100
</blockquote></details>

Thanks


<!-- Sent from Reviewable.io -->

2023-01-06 13:49 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-01-08 19:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: 107 of 109 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NLHlBrG7m-ydEyNgXaY:-NKKp1GL6DAfQkKwCyvA:bgg4eul) (no related file):*
@kailun-qin please check the newest PR version - it's close to being ready, but you are still blocking a few discussions

___
___
*[`-- commits` line 13 at r24](https://reviewable.io/reviews/gramineproject/gramine/1054#-NKm81hQ497hlcAijczE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This new commit message looks good to me, unblocking but please don't forget.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-09 00:03 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 9 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-01-09 09:10 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @kailun-qin)

___
*[`-- commits` line 23 at r26](https://reviewable.io/reviews/gramineproject/gramine/1054#-NLKmsYY24Br066k2_Xl):*
You forgot to add Vijay as a co-author. Let me do it.


<!-- Sent from Reviewable.io -->

2023-01-09 09:17 UTC, dimakuv approved these changes
> Reviewed 1 of 4 files at r20, 2 of 8 files at r25, 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 9 unresolved discussions (waiting on @kailun-qin)

___
*[`-- commits` line 23 at r26](https://reviewable.io/reviews/gramineproject/gramine/1054#-NLKmsYY24Br066k2_Xl):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to add Vijay as a co-author. Let me do it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-09 10:06 UTC, kailun-qin reviewed
> Reviewed 3 of 7 files at r4, 2 of 6 files at r5, 4 of 5 files at r7, 5 of 8 files at r8, 52 of 54 files at r9, 7 of 10 files at r11, 1 of 3 files at r13, 1 of 2 files at r18, 1 of 3 files at r19, 2 of 4 files at r20, 1 of 2 files at r21, 2 of 5 files at r22, 1 of 3 files at r23, 3 of 4 files at r24, 7 of 8 files at r25, 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1054#-NLHlBrG7m-ydEyNgXaY:-NLKzTiC6J4G66HIPZaI:bxlfew6) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@kailun-qin please check the newest PR version - it's close to being ready, but you are still blocking a few discussions
</blockquote></details>

Just gave another pass, LGTM, thanks!

___
___
*[`pal/src/host/linux-sgx/pal_main.c` line 734 at r4](https://reviewable.io/reviews/gramineproject/gramine/1054#-NIkr5YdCyxKHSSPwkZr:-NLKvJuv8MLZAjzvmWai:b-jc55b4) ([raw file](https://github.com/gramineproject/gramine/blob/9960d4102c0afba9facab9e82379903496ae806c/pal/src/host/linux-sgx/pal_main.c#L734)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To me, it's also unclear why we have to be so restrictive. Why not ignore `preheat_enclave` option in case EDMM is enabled?

UPDATE: Ok, actually, exiting makes sense. That's because `preheat_enclave` assumes that there are pages to preheat (allocated but not yet committed to memory). Whereas `edmm_enable` means that pages are not allocated at all.
</blockquote></details>

OK, make sense to me.


<!-- Sent from Reviewable.io -->

2023-01-09 12:26 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2023-01-09 12:40 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1054)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-09 13:21 UTC, merged