[LibOS,CI-Examples] Always expose SGX local attestation files
gramineproject/gramine pull request #1057
Opened 2022-11-21 12:45 UTC by dimakuv

## Description of the changes 

Previously, SGX local attestation files like `user_report_data` and `report` were exposed only if `sgx.remote_attestation` type was "epid" or "dcap". This is incorrect -- local attestation can be done completely independent of the remote-attestation scheme.

This PR always exposes all `/dev/attestation/` pseudo-files now, except for `quote` which is only exposed when `sgx.remote_attestation` is set.

See https://github.com/gramineproject/gramine/discussions/1055

## How to test this PR? 

A Python example for SGX reports is added and tested.

2022-11-21 19:20 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`CI-Examples/python/scripts/sgx-report.py` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1057#-NHQapUiDj2VesMmgA8Z:-NHQapUj8xwG2IgXiENP:b-g6mqx2) ([raw file](https://github.com/gramineproject/gramine/blob/0abfeffc29598d01cb7e1c5d0802925d5b8f3e15/CI-Examples/python/scripts/sgx-report.py#L6)):*
> ```Python
> import sys
> 
> def tohex(b):
> ```

? just remove it, it's not even used


<!-- Sent from Reviewable.io -->

2022-11-22 09:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: 4 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`CI-Examples/python/scripts/sgx-report.py` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1057#-NHQapUiDj2VesMmgA8Z:-NHTgFTx4yHTQq2tAxS2:b-wy0jij) ([raw file](https://github.com/gramineproject/gramine/blob/0abfeffc29598d01cb7e1c5d0802925d5b8f3e15/CI-Examples/python/scripts/sgx-report.py#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

? just remove it, it's not even used
</blockquote></details>

Done. Some random remnants (also removed in `sgx-quote.py`).


<!-- Sent from Reviewable.io -->

2022-11-22 10:25 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-22 20:18 UTC, mkow approved these changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-11-23 08:14 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`libos.test.ltp.test_ltp.test_ltp[fdatasync01]` and `libos.test.ltp.test_ltp.test_ltp[writev07]` timed out, known and unrelated)

2022-11-23 09:42 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-11-23 13:25 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1057)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-23 14:26 UTC, merged