Refactor sysfs to improve sanitization
gramineproject/gramine pull request #106
Opened 2021-09-30 13:52 UTC by vijaydhanraj

## Description of the changes 
This PR refactors sysfs to improve sanitization. It fixes issues 1, 2 listed as part of https://github.com/gramineproject/graphene/issues/2105.

This is a port of PR https://github.com/gramineproject/graphene/pull/2661 to gramine repo.

## How to test this PR? 
Please run `sysfs_common` and `proc_common` regression tests.

2021-10-01 10:39 UTC, dimakuv requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvKD4H5N9IidQH9Rwz):*
Please shift `to ...` to be under `Convert ...`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvKXGHDeE8VhtOL7xl:-MkvKXGIANOfheGe3wx8:b-84r4gj) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
> ```objc
>  *'K', 'M' or 'G' is passed, it is converted back to string and appended. When the size multiplier
>  * is `MULTIPLIER_NONE`, nothing is appended, and the integer is simply converted to a string. */
> int sys_convert_int_to_sizestr(uint64_t val, uint64_t size_mult, char* str, size_t max_size);
> ```

I now understand where Michal got confused. `uint64_t size_mult` is indeed confusing -- this type forces you to think about integer sizes (like 1, 1000, 1000000).

I know that I recommended you to use `int size_mult` (and you for some reason decided to change it to `uint64_t`), but let's make the type explicit now, since it causes so much confusion:
```
# in pal_arch.h
`enum multiplier {`

# in here and in fs.c
int sys_convert_int_to_sizestr(uint64_t val, enum multiplier size_mult, ...
```

See for example this PR: https://github.com/gramineproject/gramine/pull/101/files,  `enum pf_key_type`

Please also slightly update the comment now (no need to explain `integer representation (enum value)`, just remove that part).
___
*[LibOS/shim/src/fs/sys/fs.c, line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvM8Hw4oounZebR0cW:-MkvM8Hw4oounZebR0cX:b-5gacwp) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/src/fs/sys/fs.c#L17)):*
> ```C
> #include "stat.h"
> 
> int sys_convert_int_to_sizestr(uint64_t val, uint64_t size_mult, char* str, size_t max_size) {
> ```

`uint64_t size_mult` -> `enum multiplier`
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvMY4M23CmbSZVJNms:-MkvMY4M23CmbSZVJNmt:bfrj02w) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/src/fs/sys/fs.c#L81)):*
> ```C
>             ret = -EINVAL;
>             goto out;
>         }
> ```

What is the point in these checks against `INT64_MAX`? I think we can simply remove them.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvL5FDBUyGH_2m8O8V:-MkvL5FEEw3OLwDCV5jO:b-ii50b9) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L281)):*
> ```objc
> };
> 
> enum {
> ```

Let's make it an explicit type: `enum multiplier {`
___
*[Pal/include/arch/x86_64/pal-arch.h, line 288 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvL9D32O_HLuHnSlDf:-MkvL9D32O_HLuHnSlDg:b-mi706j) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L288)):*
> ```objc
> };
> 
> enum {
> ```

Let's make it an explicit type: `enum cache_type {`
___
*[Pal/include/arch/x86_64/pal-arch.h, line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvN0fVEQTqr4mHeBZi:-MkvN0fVEQTqr4mHeBZj:bybu21w) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L289)):*
> ```objc
> 
> enum {
>     CACHE_TYPE_DATA = 0,
> ```

No need for `= 0`, remove
___
*[Pal/include/arch/x86_64/pal-arch.h, line 336 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvN8k7AVam7qjR9ZOK:-MkvN8k7AVam7qjR9ZOL:b-i2lkxu) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L336)):*
> ```objc
>     PAL_RES_RANGE_INFO thread_siblings;
>     PAL_CORE_CACHE_INFO* cache; /* Array of size num_cache_index, owned by this struct */
>     PAL_NUM cpu_socket; /* array of "logical core -> socket" mappings; */
> ```

`a` -> `A` (start comment with capital letter)

Remove `;` in the comment
___
*[Pal/include/host/Linux-common/topo_info.h, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvNMJf15aKyFfbGVWi:-MkvNMJf15aKyFfbGVWj:b-6enuh5) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/host/Linux-common/topo_info.h#L21)):*
> ```objc
>  */
> int get_hw_resource(const char* filename, bool count, PAL_RES_RANGE_INFO* res_info,
>                     uint64_t* size_mult);
> ```

Please use `enum multiplier* size_mult`, and update the comment accordingly
___
*[Pal/src/host/Linux-common/topo_info.c, line 226 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvNjSsB0X6cEKkNlIc:-MkvNjSsB0X6cEKkNlId:b-x2he5h) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-common/topo_info.c#L226)):*
> ```C
>         }
> 
>         uint64_t size_mult;
> ```

`enum multiplier`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvO_nK-JJ3q-kZcj83:-MkvO_nK-JJ3q-kZcj84:bon0u86) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L169)):*
> ```C
>     uint64_t resource_count = res_info->resource_count;
>     if (!IS_IN_RANGE_INCL(resource_count, res_min_limit, res_max_limit)) {
>         log_error("Invalid resource count: %ld", resource_count);
> ```

Please fix everywhere: `%ld` -> `%lu`. You have this wrong printf specifier everywhere in this PR now.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvOvDG4S42XRp5HQhl:-MkvOvDG4S42XRp5HQhm:bety7t1) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L182)):*
> ```C
>         return -1;
> 
>     bool skip_overlap_check = true;
> ```

The logic is hard to read. Let's revert this whole thing:
```
bool check_for_overlaps = false;

if (check_for_overlaps  && previous_end >= start) {
   ...
}

/* start checking for overlaps after the first range */
check_for_overlaps = true;
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 189 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvOPLHAtdzBUbVjKU8:-MkvOPLHAtdzBUbVjKU9:bn30unc) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L189)):*
> ```C
>         uint64_t end = res_info->ranges[i].end;
> 
>         /* Ensure start and end fall within the max_limit value */
> ```

The comment is a bit wrong. It's not just `within the max_limit value`, it is `within the [min_limit, max_limit] region`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvPJCp9SRROOpQxfZq:-MkvPJCp9SRROOpQxfZr:bd45akg) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L210)):*
> ```C
> 
>         if (skip_overlap_check)
>             skip_overlap_check = false;
> ```

No need for `if` really, there is no change in logic if you just remove this `if` and leave only the assignment.

(See also my comment above with the proposed change.)
___
*[Pal/src/host/Linux-SGX/ [...]

2021-10-02 02:51 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: 12 of 18 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvKD4H5N9IidQH9Rwz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please shift `to ...` to be under `Convert ...`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvKXGHDeE8VhtOL7xl:-MkyZowd8Nmp9zhRcYlh:by3ql7h) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I now understand where Michal got confused. `uint64_t size_mult` is indeed confusing -- this type forces you to think about integer sizes (like 1, 1000, 1000000).

I know that I recommended you to use `int size_mult` (and you for some reason decided to change it to `uint64_t`), but let's make the type explicit now, since it causes so much confusion:
```
# in pal_arch.h
`enum multiplier {`

# in here and in fs.c
int sys_convert_int_to_sizestr(uint64_t val, enum multiplier size_mult, ...
```

See for example this PR: https://github.com/gramineproject/gramine/pull/101/files,  `enum pf_key_type`

Please also slightly update the comment now (no need to explain `integer representation (enum value)`, just remove that part).
</blockquote></details>

OK, done.

I had changed to `uint64_t` as we had declared size_multiplier as `PAL_NUM` type in `PAL_CORE_CACHE_INFO` and so wanted to be uniform.

 Also, I removed `'K', 'M' or 'G' ` as it was a little misleading.
___
*[LibOS/shim/src/fs/sys/fs.c, line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvM8Hw4oounZebR0cW:-MkyagaC-wPfGx7nI7S0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/src/fs/sys/fs.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`uint64_t size_mult` -> `enum multiplier`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvMY4M23CmbSZVJNms:-MkyatCS7DI-np20sgzg:b-oceygw) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/LibOS/shim/src/fs/sys/fs.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point in these checks against `INT64_MAX`? I think we can simply remove them.
</blockquote></details>

Yes, missed removing this.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 281 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvL5FDBUyGH_2m8O8V:-Mkyb-TfDYwiMuOgGNNe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L281)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's make it an explicit type: `enum multiplier {`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 288 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvL9D32O_HLuHnSlDf:-Mkyb2qR7AobGTi5_vvI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L288)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's make it an explicit type: `enum cache_type {`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvN0fVEQTqr4mHeBZi:-Mkyjt41ElkR7Ya-Rsfy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `= 0`, remove
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 336 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvN8k7AVam7qjR9ZOK:-MkybCLxAVXrxKJuPSlT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/arch/x86_64/pal-arch.h#L336)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`a` -> `A` (start comment with capital letter)

Remove `;` in the comment
</blockquote></details>

Done.
___
*[Pal/include/host/Linux-common/topo_info.h, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvNMJf15aKyFfbGVWi:-MkykOzO86-Czwjsj_eg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/include/host/Linux-common/topo_info.h#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `enum multiplier* size_mult`, and update the comment accordingly
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 226 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvNjSsB0X6cEKkNlIc:-MkykhpC5_xRkmVQTz2G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-common/topo_info.c#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`enum multiplier`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvO_nK-JJ3q-kZcj83:-MkykkrO-8SANSzskPOw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix everywhere: `%ld` -> `%lu`. You have this wrong printf specifier everywhere in this PR now.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvOvDG4S42XRp5HQhl:-MkynAG24n6X1GEx-qbL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The logic is hard to read. Let's revert this whole thing:
```
bool check_for_overlaps = false;

if (check_for_overlaps  && previous_end >= start) {
   ...
}

/* start checking for overlaps after the first range */
check_for_overlaps = true;
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 189 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvOPLHAtdzBUbVjKU8:-MkypDJVEcX-37svT1hj:beko8lf) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22b34c2462425e3c6f98948b6708/Pal/src/host/Linux-SGX/db_main.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is a bit wrong. It's not just `within the max_limit value`, it is `within the [min_limit, max_limit] region`.
</blockquote></details>

yes, fixed as `/* Ensure start and end fall within range limits */`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/106#-MkvPJCp9SRROOpQxfZq:-MkypJRuE2A5P3B1uefX:b3z2vru) ([raw file](https://github.com/gramineproject/gramine/blob/bde494c656ed22 [...]

2021-10-03 02:25 UTC, mkow requested changes
Partial review for now, will continue tomorrow.

> Reviewed 3 of 18 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106#-:-Ml2xQnGE3rtAIoRlqBF:bq2qy7)* status: 13 of 19 files reviewed, 33 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2YIR16YHAfp-Uq2ZH:-Ml2YIR28J7iOthq4A0Y:b-q6oi84) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
Please reword this to:

> Converts an integer to a string, optionally appending a given single-letter unit suffix (see `enum multiplier` for possible values).
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-Ml2Xvbq7xVsagZHT7N_:bt37fcl) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
> ```
> enum multiplier
> ```

This name is global, it should be more specific, like e.g. `size_multiplier`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2asYP-B2CrctjsToX:-Ml2asYP-B2CrctjsToY:b-tzvjbb) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
Please reword to:

> Converts PAL_RES_RANGE_INFO to a string representation. Example output for sep == ',': "10-63,68,70-127".
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2pus67jFIJhBHdZk4:-Ml2pus7DUU55YR4CuVR:b-pkk5mv) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
> ```
> res_range_info
> ```

I'd rename this to just `range_info`, this `res_` prefix is too confusing IMO - it may be read as a hint that this is an output variable, which is a popular pattern in C.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2fW9H7AF2YCfIhM_w:-Ml2fW9H7AF2YCfIhM_x:ba592bk) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
Please reword to:

> Converts PAL_RES_RANGE_INFO to a sysfs CPU bitmask representation and with respect to the possible cores count in the system. Example output for 64 cores in total and ranges 0-15,48-55: "ffff0000,0000ff00".
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2jbnA05uyqlViDnNx:-Ml2jbnB26UunrT8iCvV:b7tohm2) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
> ```
>  * res_range_info->ranges[0].start and res_range_info->ranges[0].end were 0 and 31 respectively,
>  * then `00000000,ffffffff` string is generated. */
> ```

Isn't this example wrong? On my system ones represent the positions _inside_ the ranges, not outside.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2kNV10328HYLAA3yC:-Ml2kNV10328HYLAA3yD:bhinlkk) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
> ```objc
> /* Converts array of integer range(s) to a cpu bitmap string. For example, if
>  * res_range_info->ranges[0].start and res_range_info->ranges[0].end were 0 and 31 respectively,
>  * then `00000000,ffffffff` string is generated. */
> ```

On my system `/sys/devices/system/cpu/cpu7/topology/core_siblings` outputs `ff`, but this function always outputs full 4-byte values. Please make sure the format used here is the same as in the kernel.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 226 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2q888180xheU5YmBT:-Ml2q888180xheU5YmBU:b-amf23) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L226)):*
> ```objc
>  * res_range_info->ranges[0].start and res_range_info->ranges[0].end were 0 and 31 respectively,
>  * then `00000000,ffffffff` string is generated. */
> int sys_convert_ranges_to_cpu_bitmap_str(const PAL_RES_RANGE_INFO* res_range_info, char* str,
> ```

ditto (`res_` prefix)
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-Ml2oH639OVDIsVrNRdf:bkfqqvv) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
> ```C
>         }
>     } else if (strcmp(name, "size") == 0) {
>         ret = sys_convert_int_to_sizestr(cache->size, cache->size_multiplier, str, sizeof(str));
> ```

You miss a newline in the output here (and probably in other similar places too). I'm quite unhappy that this wasn't detected by the tests, it seems that they aren't strong enough. Same for e.g. printing `00000088` instead of `88` I mentioned above - it was also not detected.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 281 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2qurF7GxbUJ45Zs_q:-Ml2qurGAxWpHen1Z6fV:b528his) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/Pal/include/arch/x86_64/pal-arch.h#L281)):*
Migrating the discussion from [the old PR](https://github.com/gramineproject/graphene/pull/2661):

@mkow:

> Why does this multiplier even exists? Wasn't the idea that what host passes should be as simple and normalized as possible? Why not just pass the number of bytes everywhere and just in that int->str function shorten it if it's divisible by some size unit? (for specific rounding rules please check the kernel source)
>
> With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".
>
> And another problem: what if the untrusted host gives you `LONG_MAX` gigabytes? I think in some places you'll just pass it to the app without erroring out, because you never needed to multiply it, so there was no chance for overflow detection (which will certainly happen in the user app then).

@vijaydhanraj:

> > Why does this multiplier even exists?
>
> We have a multiplier because we exactly need to know how the normal kernel is representing the strings. For example, on reading `/sys/devices/system/cpu/cpu2/cache/index3/size` we get `49152K`. Now this can be represented as `48M` or `49152K` and in this case, kernel chose the latter representation, and we need to give the same to the end-user.
> 
> > With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".
>
> Please see the earlier comment.
>
>    And another problem: what if the untrusted host gives you LONG_MAX gigabytes?
>
> Please see here (lines 263-267) https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R263, I do multiply the size qualifier and check the limits when sanitizing so we shouldn't be running into overflow issues in this case. If you see the issue somewhere, please point me to it.

And finally my next reply: (i.e. from this review iteration)

> in this case, kernel chose the latter repre [...]

2021-10-03 11:01 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-10-03 20:31 UTC, mkow requested changes
> Reviewed 4 of 18 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 18 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6MOFA4_d4QN33N8AZ:-Ml6MOFB0icUVl2TNjHN:bhzjp6s) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L18)):*
> ```C
> 
> int sys_convert_int_to_sizestr(uint64_t val, enum multiplier size_mult, char* str,
>                                size_t max_size) {
> ```

`max_size` -> `buf_size` ("max size" sounds a bit like a limit for the value, as this function works on size strings - "buf size" is much less ambiguous)
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-Ml6Ng_j5tonmvAfZ_AQ:b-naprmn) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
> ```C
>             break;
>     }
>     return ret;
> ```

we should fail if the result didn't fit into the buffer, now we're silently continuing
___
*[LibOS/shim/src/fs/sys/fs.c, line 38 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6MpQz64nlPdGLLmN0:-Ml6MpQz64nlPdGLLmN1:b-5kqfri) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L38)):*
> ```C
> }
> 
> int sys_convert_ranges_to_str(const PAL_RES_RANGE_INFO* res_range_info, char* str, size_t max_size,
> ```

`max_size` -> `buf_size`

ditto for the whole PR
___
*[LibOS/shim/src/fs/sys/fs.c, line 40 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6NzS51YKYv5o0-SP4:-Ml6NzS51YKYv5o0-SP5:b-ositwi) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L40)):*
> ```C
> int sys_convert_ranges_to_str(const PAL_RES_RANGE_INFO* res_range_info, char* str, size_t max_size,
>                               const char* sep) {
> ```

please remove this empty line
___
*[LibOS/shim/src/fs/sys/fs.c, line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6a5Qg1Gm9JfIY7bx0:-Ml6a5QhCORpPgKa7Dem:b-gzy9tp) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L50)):*
> ```
> "\0"
> ```

Why not just `""`?
___
*[LibOS/shim/src/fs/sys/fs.c, line 54 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6arNZ48s7JCUbauJU:-Ml6arNZ48s7JCUbauJV:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L54)):*
> ```C
>             ret = snprintf(str + offset, max_size - offset, "%lu-%lu%s",
>                            res_range_info->ranges[i].start, res_range_info->ranges[i].end,
>                            (i + 1 == range_cnt) ? "\0" : sep);
> ```

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6geCd2lPbM07ZHyCH:-Ml6geCd2lPbM07ZHyCI:b-naprmn) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L62)):*
> ```C
>         offset += ret;
>     }
>     return 0;
> ```

we should fail if the result didn't fit into the buffer, now we're silently continuing
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6eCdM-cdbqu_z6Iii:-Ml6eCdM-cdbqu_z6Iij:b-loxfcr) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L81)):*
> ```
> BITS_IN_TYPE(int)
> ```

This is different than `bitmap`'s element type
___
*[LibOS/shim/src/fs/sys/fs.c, line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6ebC9-CYY0BnAKQj1:-Ml6ebC9-CYY0BnAKQj2:b-b3gf5v) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L82)):*
> ```C
>         for (uint64_t j = start; j <= end; j++) {
>             uint64_t index = j / BITS_IN_TYPE(int);
>             if (index >= num_cpumask) {
> ```

This should be impossible? If so, it should either be deleted or turned into an assert.
___
*[LibOS/shim/src/fs/sys/fs.c, line 86 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6dyr59b0eAVZfpNlm:-Ml6dyr59b0eAVZfpNln:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L86)):*
> ```C
>                 goto out;
>             }
>             bitmap[index] |= 1U << (j % BITS_IN_TYPE(int));
> ```

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 92 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6fFFl0qS4lemqtawH:-Ml6fFFl0qS4lemqtawI:b-gj8ro5) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L92)):*
> ```C
>     /* Convert cpumask to strings */
>     size_t offset = 0;
>     for (uint64_t j = num_cpumask; j > 0; j--) {
> ```

Why do you print the chunks in reverse order?
___
*[LibOS/shim/src/fs/sys/fs.c, line 97 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6g2NgBgGi9a15VpHH:-Ml6g2NgBgGi9a15VpHI:b-x4qm95) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L97)):*
> ```
> "\0"
> ```

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 103 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6gi6L0wVO82M424or:-Ml6gi6L0wVO82M424os:b-naprmn) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L103)):*
> ```C
>     }
>     ret = 0;
> ```

we should fail if the result didn't fit into the buffer, now we're silently continuing
___
*[LibOS/shim/src/fs/sys/node_info.c, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6k0qi9ivv2nSzR9oU:-Ml6k0qi9ivv2nSzR9oV:b-9fmwap) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/node_info.c#L25)):*
> ```
> topo_info.nodes
> ```

This was previously called `online_nodes`, is now `topo_info` holding only online ones? Where do the offline nodes go?


<!-- Sent from Reviewable.io -->

2021-10-04 07:10 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2YIR16YHAfp-Uq2ZH:-Ml6KuvC-CQ_SX4ffLz-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please reword this to:

> Converts an integer to a string, optionally appending a given single-letter unit suffix (see `enum multiplier` for possible values).
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-Ml6KxHI7n-BDhIl7JWS:b-qg40qi) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> enum multiplier
> ```

This name is global, it should be more specific, like e.g. `size_multiplier`
</blockquote></details>

Changed it to `sz_multiplier`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2asYP-B2CrctjsToX:-Ml8QohLDDTvd0wW5lZT:bibbzw3) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please reword to:

> Converts PAL_RES_RANGE_INFO to a string representation. Example output for sep == ',': "10-63,68,70-127".
</blockquote></details>

Here we don't convert `PAL_RES_RANGE_INFO` but we convert `PAL_RANGE_INFO` which is part of it to string. So have modified the comment accordingly.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2pus67jFIJhBHdZk4:-Ml8SdSv7qEr5X0U05YO:b-nipbpq) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> res_range_info
> ```

I'd rename this to just `range_info`, this `res_` prefix is too confusing IMO - it may be read as a hint that this is an output variable, which is a popular pattern in C.
</blockquote></details>

There are 2 structs one `PAL_RES_RANGE_INFO` and as part of it, there is another struct `PAL_RANGE_INFO`. The latter is an array with a count equal to `range_count` (part of `PAL_RES_RANGE_INFO` as well) which we convert to string. But to this function, we pass the struct `PAL_RES_RANGE_INFO`. So, renaming it to `range_info` might look like we are referring to `PAL_RANGE_INFO` instead of `PAL_RES_RANGE_INFO`. 

To avoid confusion with `res_`, I have changed `res_` -> `resource`. This will make it more explicit.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2fW9H7AF2YCfIhM_w:-Ml8WRCgDpNgJcKMLgK9:b-ifb2u7) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
> PAL_RES_RANGE_INFO 
Please earlier comment on this. But I have reworded.

>0-15,48-55: "ffff0000,0000ff00".

At least on my system, I don't see the layout this way. LSB starts from the right. See the example below.
```
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list
0-31,64-95
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings                             
00000000,ffffffff,00000000,ffffffff
```
Do you see such a layout `0-15,48-55: "ffff0000,0000ff00"` in any system?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2jbnA05uyqlViDnNx:-Ml8_7ivA_QPeBRaFgJA:b-3nim7k) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  * res_range_info->ranges[0].start and res_range_info->ranges[0].end were 0 and 31 respectively,
>  * then `00000000,ffffffff` string is generated. */
> ```

Isn't this example wrong? On my system ones represent the positions _inside_ the ranges, not outside.
</blockquote></details>

On my ICX system running ubuntu18.04 with kernel 5.11, I see the following layout.
```
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list
0-31,64-95
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings                             
00000000,ffffffff,00000000,ffffffff
```

Can you please copy the same path info from your system?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2kNV10328HYLAA3yC:-Ml8_bMMAavANS2D7saD:b-gk0ofp) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

On my system `/sys/devices/system/cpu/cpu7/topology/core_siblings` outputs `ff`, but this function always outputs full 4-byte values. Please make sure the format used here is the same as in the kernel.
</blockquote></details>

Thanks for checking. I think I have fixed it. Can you please test on your system?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 226 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2q888180xheU5YmBT:-Ml8owGJ4BPsIGGXVCU0:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L226)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`res_` prefix)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-Ml8pUveDRqV4g185yfT:b58ae79) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
> You miss a newline in the output here (and probably in other similar places too).

Can you please clarify? In my system if I do `cat /sys/devices/system/cpu/cpu1/cache/index1/size` I get the value without a newline being added. See below,

```
vdhanraj@sdp cat /sys/devices/system/cpu/cpu1/cache/index1/size 
32K
vdhanraj@sdp
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 18 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6MOFA4_d4QN33N8AZ:-Ml8sTIR13zsLnbANTmk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`max_size` -> `buf_size` ("max size" sounds a bit like a limit for the value, as this function works on size strings - "buf size" is much less ambiguous)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-Ml8yY2xEhVAGo3nZUcF:bebvlev) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockqu [...]

2021-10-04 08:39 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-Ml9Lj2r5xGykmQgjYZz:bxngxug) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed it to `sz_multiplier`
</blockquote></details>

Not blocking, but why this fondness towards strange abbreviations? Why `sz_multiplier` instead of `size_multiplier` as requested? Given that we don't use `sz` abbreviation anywhere in our code base, and you only saved 2 letters on this... I would prefer to rename to a full form (`size_multiplier`).

Just curious, is this something that is common in some other project you previously worked on?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2asYP-B2CrctjsToX:-Ml9N-122RwwzxZz6FIX:b-wyeoqk) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here we don't convert `PAL_RES_RANGE_INFO` but we convert `PAL_RANGE_INFO` which is part of it to string. So have modified the comment accordingly.
</blockquote></details>

I don't understand your explanation, Vijay. We convert `PAL_RES_RANGE_INFO`, *not* `PAL_RANGE_INFO`.

If we would convert `PAL_RANGE_INFO`, we would only output one range (`"10-63"`). But we're actually outputting all the ranges, which is what `PAL_RES_RANGE_INFO` is about. So I agree with Michal's wording (and disagree with your wording).
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2pus67jFIJhBHdZk4:-Ml9NJkhD1Plh-9P8xJ2:byzybwl) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There are 2 structs one `PAL_RES_RANGE_INFO` and as part of it, there is another struct `PAL_RANGE_INFO`. The latter is an array with a count equal to `range_count` (part of `PAL_RES_RANGE_INFO` as well) which we convert to string. But to this function, we pass the struct `PAL_RES_RANGE_INFO`. So, renaming it to `range_info` might look like we are referring to `PAL_RANGE_INFO` instead of `PAL_RES_RANGE_INFO`. 

To avoid confusion with `res_`, I have changed `res_` -> `resource`. This will make it more explicit.
</blockquote></details>

I agree with your rename to `resource_`. But I disagree with your `PAL_RANGE_INFO ...` wording in the comment, please see above.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9OXYQBbMstiRTLTOW:-Ml9OXYQBbMstiRTLTOX:bqr52p4) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/include/shim_fs_pseudo.h#L224)):*
> ```objc
> /* Converts `PAL_RANGE_INFO` that is part of `PAL_RES_RANGE_INFO` to a sysfs CPU bitmask
>  * representation with bitmask size based on the possible cores count in the system. Example
>  * output for 64 cores in total and ranges 0-15,48-55: "00ff0000, 0000ffff". */
> ```

Please remove space in-between two hex strings in your example.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-Ml9Oxqo2lWRp3ozsmwW:bqd16e7) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
> I get the value without a newline being added

Why do you say so? Based on the command line output, there **is** a newline added. Otherwise you would see this:
```
vdhanraj@sdp cat /sys/devices/system/cpu/cpu1/cache/index1/size 
32Kvdhanraj@sdp
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-Ml9PQ_a-7nBd8nLoWBG:bgnhbft) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about adding a check like below?
```
if (ret >= buf_size)
    return -EOVERFLOW;
```
</blockquote></details>

Almost, but you should cast the the *wider* type, not the *narrower* one:
```
   return (size_t)ret >= buf_size ? -EOVERFLOW : ret;
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6ebC9-CYY0BnAKQj1:-Ml9QHvjBCGsFI-Knr4v:bavgmlx) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L82)):*
> I feel assert doesn't help with release build

Yes, that's the point of `assert`: it is removed from release builds (for performance reasons), but it helps catch errors early in debug builds (for ease of debugging). So please add an assert here.
___
*[LibOS/shim/src/fs/sys/fs.c, line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9PtEn3yHBQmKjoTkH:-Ml9PtEn3yHBQmKjoTkI:bk8x7x9) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L52)):*
> ```C
>         if (resource_range_info->ranges[i].end == resource_range_info->ranges[i].start) {
>             ret = snprintf(str + offset, buf_size - offset, "%lu%s",
>                            resource_range_info->ranges[i].start, (i + 1 == range_cnt) ? "\0" : sep);
> ```

You removed `"\0"` below but not here.
___
*[LibOS/shim/src/fs/sys/fs.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Q3DD9w0NMXlguTBB:-Ml9Q3DD9w0NMXlguTBC:bcrnr5k) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L60)):*
> ```C
> 
>         /* Truncation has occurred */
>         if (ret >= (int)buf_size)
> ```

`(size_t)ret >= buf_size` (wrong cast)
___
*[LibOS/shim/src/fs/sys/fs.c, line 99 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9RBgI-T4ut2NyXbzM:-Ml9RBgI-T4ut2NyXbzN:b-u3byug) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L99)):*
> ```C
>         }
> 
>         /* Print full 4-byte values for systems having greater than 32 cores.*/
> ```

This is obvious that you must print 4-byte values for 32+ cores. I think the comment will be more meaningful if we revert it:
```
/* Linux doesn't print leading zeroes for systems with less than 32 cores, e.g. "fff" for
 * 12 cores; we mimic this behavior */
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 100 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Rn5Y3XfkWOORWJDW:-Ml9Rn5Z3g4ktroMA_Ib:b-7tjdi7) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L100)):*
> ```C
> 
>         /* Print full 4-byte values for systems having greater than 32 cores.*/
>         if (possible_cores > 31) {
> ```

Can we make it more readable with `possible_cores >= 32`? Then it will reflect the comment exactly.
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/ [...]

2021-10-04 15:42 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: 13 of 19 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-MlAmh4X-ZgsM24z73Y_:b-hxwo6i) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but why this fondness towards strange abbreviations? Why `sz_multiplier` instead of `size_multiplier` as requested? Given that we don't use `sz` abbreviation anywhere in our code base, and you only saved 2 letters on this... I would prefer to rename to a full form (`size_multiplier`).

Just curious, is this something that is common in some other project you previously worked on?
</blockquote></details>

Yes I have used `sz` in other projects and I don't think is uncommon. Even in linux kernel we see such abbreviations. https://elixir.bootlin.com/linux/v5.11.22/source/arch/x86/kernel/setup.c#L410

But I have changed `sz_multiplier` ->`size_multiplier`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2asYP-B2CrctjsToX:-MlAnjZxDyOskj_iC1fo:b-3siteq) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand your explanation, Vijay. We convert `PAL_RES_RANGE_INFO`, *not* `PAL_RANGE_INFO`.

If we would convert `PAL_RANGE_INFO`, we would only output one range (`"10-63"`). But we're actually outputting all the ranges, which is what `PAL_RES_RANGE_INFO` is about. So I agree with Michal's wording (and disagree with your wording).
</blockquote></details>

When we say convert PAL_RES_RANGE_INFO` string, there is `resource_count` field that we don't use. So called out `PAL_RANGE_INFO`. But if both reviewers feel this way, I will change it back to as proposed.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2pus67jFIJhBHdZk4:-MlAoqPqB_z1d-yEcAO-:brzm3kb) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with your rename to `resource_`. But I disagree with your `PAL_RANGE_INFO ...` wording in the comment, please see above.
</blockquote></details>

I have reverted the comment as proposed.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9OXYQBbMstiRTLTOW:-MlAozQR5i7DFv5Z_1mk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/include/shim_fs_pseudo.h#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove space in-between two hex strings in your example.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-MlAp57D3ngA040bVbND:b5a2f4v) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I get the value without a newline being added

Why do you say so? Based on the command line output, there **is** a newline added. Otherwise you would see this:
```
vdhanraj@sdp cat /sys/devices/system/cpu/cpu1/cache/index1/size 
32Kvdhanraj@sdp
```
</blockquote></details>

I have added a new line.
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlApcDaEoBoyTYv_QbD:bylhwg7) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Almost, but you should cast the the *wider* type, not the *narrower* one:
```
   return (size_t)ret >= buf_size ? -EOVERFLOW : ret;
```
</blockquote></details>

With the proposed change, if `ret` was less than 0, we might catch it as an overflow error.

For example if `ret = -1`, typecasting this way will make it `4294967295` which will be greater than `buf_size`
___
*[LibOS/shim/src/fs/sys/fs.c, line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6ebC9-CYY0BnAKQj1:-MlAqGht3jv1XucUeLaV:b-wz7vbl) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I feel assert doesn't help with release build

Yes, that's the point of `assert`: it is removed from release builds (for performance reasons), but it helps catch errors early in debug builds (for ease of debugging). So please add an assert here.
</blockquote></details>

OK, added `assert`
___
*[LibOS/shim/src/fs/sys/fs.c, line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9PtEn3yHBQmKjoTkH:-MlArHAv11Bv2gRD-hEW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You removed `"\0"` below but not here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Q3DD9w0NMXlguTBB:-MlArK1v4YKG-y6zCk3c:b-v0jgyj) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`(size_t)ret >= buf_size` (wrong cast)
</blockquote></details>

Please see my earlier comment.
___
*[LibOS/shim/src/fs/sys/fs.c, line 99 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9RBgI-T4ut2NyXbzM:-MlAra1n0O30IUHa7sJE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is obvious that you must print 4-byte values for 32+ cores. I think the comment will be more meaningful if we revert it:
```
/* Linux doesn't print leading zeroes for systems with less than 32 cores, e.g. "fff" for
 * 12 cores; we mimic this behavior */
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 100 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Rn5Y3XfkWOORWJDW:-MlArgDj2knceGYwnRBw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we make it more readable with `possible_cores >= 32`? Then it will reflect the comment exactly.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9QkcbEjHdogQDxrJH:-MlArp-_4nGAlkufIFzz:b5pgvb1) ([raw file](https://github.com/gramineproj [...]

2021-10-05 07:47 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-MlELMZFCQZT6Vpakiz7:bx1pbov) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
Linux has all kinds of hacky code from the early 90s :) IIRC, Linux still can't fix all the occurences of `int` -> `long` in its code.

The Gramine coding style (https://gramine.readthedocs.io/en/latest/devel/coding-style.html#c) generally follows Google C++ styleguide: https://google.github.io/styleguide/cppguide.html#General_Naming_Rules. And the Google styleguide is very clear:

> Use names that describe the purpose or intent of the object. Do not worry about saving horizontal space as it is far more important to make your code immediately understandable by a new reader. Minimize the use of abbreviations that would likely be unknown to someone outside your project (especially acronyms and initialisms). **Do not abbreviate by deleting letters within a word.**

Also, this answer: https://qr.ae/pGJiYl
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-MlEN4dg2hBvqqSIQicq:bk641kz) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have added a new line.
</blockquote></details>

Could you add in the comment-description of `sys_convert_int_to_sizestr()` that it adds a newline at the end? Otherwise people may be tempted to (ab)use this function to e.g. concatenate two strings, which will lead to incorrect result.
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlENSZO407Id2RDmJc-:banm9kh) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

With the proposed change, if `ret` was less than 0, we might catch it as an overflow error.

For example if `ret = -1`, typecasting this way will make it `4294967295` which will be greater than `buf_size`
</blockquote></details>

Ah, I see. But then why so complicated? Your logic is very subtle: "If `ret` is negative, then let's play a trick of casting to a narrower `int` type so that we don't get into this IF". You will forget about this subtlety in a month...

I suggest to do this then:
```
    ...
}

if (ret < 0)
    return ret;

if ((size_t)ret >= buf_size)
    return -EOVERFLOW;

return ret;
```

This is very clear: "if I got error, return this error; if I wanted to write more than buf_size, then it is an overflow; otherwise I'm happy".

I generally thrown upon your tendency to play clever and subtle tricks :)
___
*[LibOS/shim/src/fs/sys/fs.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Q3DD9w0NMXlguTBB:-MlEPNjBEpEdJv-JovB1:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L60)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please see my earlier comment.
</blockquote></details>

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9QkcbEjHdogQDxrJH:-MlEPg2d2UXlvD5pqmgw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L109)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please see the earlier comment on this.
</blockquote></details>

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 41 at r5](https://reviewable.io/reviews/gramineproject/gramine/106#-MlEPRbv58SX9At0VFux:-MlEPRbv58SX9At0VFuy:b-v83al6) ([raw file](https://github.com/gramineproject/gramine/blob/799d3c7d32aded062c4032b110669295cf7882c7/LibOS/shim/src/fs/sys/fs.c#L41)):*
> ```C
> }
> 
> int sys_convert_ranges_to_str(const PAL_RES_RANGE_INFO* resource_range_info, char* str,
> ```

Please put in a comment-description of this function that it adds a newline.
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r5](https://reviewable.io/reviews/gramineproject/gramine/106#-MlEPe_o5sGcdqTZrole:-MlEPe_o5sGcdqTZrolf:b-v83al6) ([raw file](https://github.com/gramineproject/gramine/blob/799d3c7d32aded062c4032b110669295cf7882c7/LibOS/shim/src/fs/sys/fs.c#L70)):*
> ```C
> }
> 
> int sys_convert_ranges_to_cpu_bitmap_str(const PAL_RES_RANGE_INFO* resource_range_info, char* str,
> ```

Please put in a comment-description of this function that it adds a newline.


<!-- Sent from Reviewable.io -->

2021-10-05 21:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: 17 of 19 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-MlH4hwmEFW5FzkXwIkx:b-hbzzja) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Linux has all kinds of hacky code from the early 90s :) IIRC, Linux still can't fix all the occurences of `int` -> `long` in its code.

The Gramine coding style (https://gramine.readthedocs.io/en/latest/devel/coding-style.html#c) generally follows Google C++ styleguide: https://google.github.io/styleguide/cppguide.html#General_Naming_Rules. And the Google styleguide is very clear:

> Use names that describe the purpose or intent of the object. Do not worry about saving horizontal space as it is far more important to make your code immediately understandable by a new reader. Minimize the use of abbreviations that would likely be unknown to someone outside your project (especially acronyms and initialisms). **Do not abbreviate by deleting letters within a word.**

Also, this answer: https://qr.ae/pGJiYl
</blockquote></details>

OK, got it.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-MlH7F376DCsv5gMzIxN:bs8hn22) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add in the comment-description of `sys_convert_int_to_sizestr()` that it adds a newline at the end? Otherwise people may be tempted to (ab)use this function to e.g. concatenate two strings, which will lead to incorrect result.
</blockquote></details>

Done. Also added it for other `sys_convert_ranges_xx` functions.
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlH8yEf3MgOEnbIKVbT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I see. But then why so complicated? Your logic is very subtle: "If `ret` is negative, then let's play a trick of casting to a narrower `int` type so that we don't get into this IF". You will forget about this subtlety in a month...

I suggest to do this then:
```
    ...
}

if (ret < 0)
    return ret;

if ((size_t)ret >= buf_size)
    return -EOVERFLOW;

return ret;
```

This is very clear: "if I got error, return this error; if I wanted to write more than buf_size, then it is an overflow; otherwise I'm happy".

I generally thrown upon your tendency to play clever and subtle tricks :)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9Q3DD9w0NMXlguTBB:-MlH944UEmhCvDRkUoeE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml9QkcbEjHdogQDxrJH:-MlH8so-2TyrmUOykStJ:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fe83aa1438b03d6019e6b9e426849d9c0c75e73e/LibOS/shim/src/fs/sys/fs.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[LibOS/shim/src/fs/sys/fs.c, line 41 at r5](https://reviewable.io/reviews/gramineproject/gramine/106#-MlEPRbv58SX9At0VFux:-MlH8ot_3RETuiX4VEc0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/799d3c7d32aded062c4032b110669295cf7882c7/LibOS/shim/src/fs/sys/fs.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put in a comment-description of this function that it adds a newline.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r5](https://reviewable.io/reviews/gramineproject/gramine/106#-MlEPe_o5sGcdqTZrole:-MlH8q7iBf3z6-_n9mVN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/799d3c7d32aded062c4032b110669295cf7882c7/LibOS/shim/src/fs/sys/fs.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put in a comment-description of this function that it adds a newline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-06 06:29 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlJHG-d6s1qZwL0J_BJ:-MlJHG-e5PjHjSBxh1Uo:b-h7oxp5) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
> ```objc
> /* Converts an integer to a string, optionally appending a given single-letter unit suffix
>  * (see enum size_multiplier for possible values).
>  * Note: This function adds a newline at end of the string. */
> ```

`at end` -> `at the end`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlJHQ5x33QlpLiu86No:-MlJHQ5x33QlpLiu86Np:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
> ```objc
> /* Converts PAL_RES_RANGE_INFO to a string representation.
>  * Example output when sep == ',': "10-63,68,70-127".
>  * Note: This function adds a newline at end of the string. */
> ```

ditto
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 227 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlJHRzYAfINFv0fcW6A:-MlJHRzYAfINFv0fcW6B:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/include/shim_fs_pseudo.h#L227)):*
> ```objc
>  * possible cores count in the system.
>  * Example output for 64 cores in total and ranges 0-15,48-55: "00ff0000,0000ffff".
>  * Note: This function adds a newline at end of the string. */
> ```

ditto
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2oH639OVDIsVrNRde:-MlJHVK6633jpuPPby9c:b-zcjvte) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done. Also added it for other `sys_convert_ranges_xx` functions.
</blockquote></details>

Thanks
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlJHZ9d1vCndRehnp9R:b-ju3kiw) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change


<!-- Sent from Reviewable.io -->

2021-10-06 13:48 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlKpcFr7-NhofYNPhcY:b-bntn28) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see the change
</blockquote></details>

yes, here we don't have a check like `ret < 0` and so the error might be overwritten. So left it as is.
How about the below change? Is this better?

```
diff --git a/LibOS/shim/src/fs/sys/fs.c b/LibOS/shim/src/fs/sys/fs.c
index 11ff9bd24..c047d5cf8 100644
--- a/LibOS/shim/src/fs/sys/fs.c
+++ b/LibOS/shim/src/fs/sys/fs.c
@@ -16,7 +16,7 @@
 
 int sys_convert_int_to_sizestr(uint64_t val, enum size_multiplier size_mult, char* str,
                                size_t buf_size) {
-    int ret = 0;
+    int ret;
 
     switch (size_mult) {
         case MULTIPLIER_KB:
@@ -33,9 +33,13 @@ int sys_convert_int_to_sizestr(uint64_t val, enum size_multiplier size_mult, cha
             break;
     }
 
-    if (ret >= (int)buf_size)
-        ret = -EOVERFLOW;
-    return ret;
+    if (ret < 0)
+        return ret;
+
+    if ((size_t)ret >= buf_size)
+        return -EOVERFLOW;
+
+    return 0;
 }
```


<!-- Sent from Reviewable.io -->

2021-10-06 14:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6Ng_i7dKwGG8CGXvi:-MlKuWZoAz03Jf5pfCFE:b-b8wl0q) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, here we don't have a check like `ret < 0` and so the error might be overwritten. So left it as is.
How about the below change? Is this better?

```
diff --git a/LibOS/shim/src/fs/sys/fs.c b/LibOS/shim/src/fs/sys/fs.c
index 11ff9bd24..c047d5cf8 100644
--- a/LibOS/shim/src/fs/sys/fs.c
+++ b/LibOS/shim/src/fs/sys/fs.c
@@ -16,7 +16,7 @@
 
 int sys_convert_int_to_sizestr(uint64_t val, enum size_multiplier size_mult, char* str,
                                size_t buf_size) {
-    int ret = 0;
+    int ret;
 
     switch (size_mult) {
         case MULTIPLIER_KB:
@@ -33,9 +33,13 @@ int sys_convert_int_to_sizestr(uint64_t val, enum size_multiplier size_mult, cha
             break;
     }
 
-    if (ret >= (int)buf_size)
-        ret = -EOVERFLOW;
-    return ret;
+    if (ret < 0)
+        return ret;
+
+    if ((size_t)ret >= buf_size)
+        return -EOVERFLOW;
+
+    return 0;
 }
```
</blockquote></details>

Yes, that's exactly what I want.


<!-- Sent from Reviewable.io -->

2021-10-06 15:28 UTC, mkow requested changes
> Reviewed 2 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/106)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/106#-MlBJo2lEHjXJnlkl4Su:-MlBJo2m9jrKHe8btux5:burowmh) (no related file):*
I tested what happens if some cores are offline and right now Gramine just exits without any meaningful message. I know this is not supported, but at least we could fail gracefully.

---
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2Xvbp2D_EQyI1LP7w:-MlB99ffAIzqihDPO6Ab:b-xo6yf4) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L215)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes I have used `sz` in other projects and I don't think is uncommon. Even in linux kernel we see such abbreviations. https://elixir.bootlin.com/linux/v5.11.22/source/arch/x86/kernel/setup.c#L410

But I have changed `sz_multiplier` ->`size_multiplier`
</blockquote></details>

I also prefer "size" ;) Not much longer but easier to read.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2asYP-B2CrctjsToX:-MlBCMgj6SFHgHrfAsmu:bq1p3k4) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

When we say convert PAL_RES_RANGE_INFO` string, there is `resource_count` field that we don't use. So called out `PAL_RANGE_INFO`. But if both reviewers feel this way, I will change it back to as proposed.
</blockquote></details>

Isn't `resource_count` derived from the ranges? (i.e. it's just caching the sum or the ranges' lengths?)
If so, then I don't see a problem with calling this a "string representation" of `PAL_RES_RANGE_INFO`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2fW9H7AF2YCfIhM_w:-MlBOlacEv_XajrWqV3b:b-rptq3z) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> PAL_RES_RANGE_INFO 
Please earlier comment on this. But I have reworded.

>0-15,48-55: "ffff0000,0000ff00".

At least on my system, I don't see the layout this way. LSB starts from the right. See the example below.
```
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list
0-31,64-95
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings                             
00000000,ffffffff,00000000,ffffffff
```
Do you see such a layout `0-15,48-55: "ffff0000,0000ff00"` in any system?
</blockquote></details>

Huh, weird, indeed the bits are flipped. Maybe it even makes sense, that's the typical bit order when printing as a number.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2jbnA05uyqlViDnNx:-MlBPKOS-87CU00kH4f4:borggpy) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

On my ICX system running ubuntu18.04 with kernel 5.11, I see the following layout.
```
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list
0-31,64-95
 vdhanraj@sdp cat /sys/devices/system/cpu/cpu0/topology/core_siblings                             
00000000,ffffffff,00000000,ffffffff
```

Can you please copy the same path info from your system?



</blockquote></details>

I though you just flipped 0s and 1s by an accident, but your example was neg-palindromic, so I didn't notice what it really showed ;)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml2kNV10328HYLAA3yC:-MlBPjOhE1bzyZ_KVYJb:b-bk9chl) ([raw file](https://github.com/gramineproject/gramine/blob/fbf4d135a2b5795fe9662d227757f1b44e7b22c2/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks for checking. I think I have fixed it. Can you please test on your system?
</blockquote></details>

Works correctly now, thanks.
___
*[LibOS/shim/src/fs/sys/fs.c, line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6a5Qg1Gm9JfIY7bx0:-MlBVNV19B4Pt3PCr1wL:bmpxfuu) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L50)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, but any issue with having "\0"? Felt this to be more explicit.
</blockquote></details>

`"\0"` looks weird, if you want an empty string then why not use an empty string?
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6eCdM-cdbqu_z6Iii:-MlKbqKCBEgQ7jsENFQI:b-aatwmt) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L81)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here, I am using `BITS_IN_TYPE(int)` to get the bits in an integer. What is the issue you are pointing to? Can you please elaborate?
</blockquote></details>

The issue is that `bitmap` is not an array of `int`s.
___
*[LibOS/shim/src/fs/sys/fs.c, line 86 at r3](https://reviewable.io/reviews/gramineproject/gramine/106#-Ml6dyr59b0eAVZfpNlm:-MlKd_Ho52guI4vej3Zs:b-nl8v8c) ([raw file](https://github.com/gramineproject/gramine/blob/fdb946162b6feabed831447f2163b5bab5c951e9/LibOS/shim/src/fs/sys/fs.c#L86)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please elaborate.
</blockquote></details>

`bitmap` is not an array of `int`s.
___
*[LibOS/shim/src/fs/sys/fs.c, line 63 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlKbhXe42gQk-MaaPWv:-MlKbhXe42gQk-MaaPWw:b-ytg76t) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/src/fs/sys/fs.c#L63)):*
> ```C
> 
>         /* Truncation has occurred */
>         if ((size_t)ret >= buf_size)
> ```

This check is wrong, you need to account for `offset`.
___
*[LibOS/shim/src/fs/sys/fs.c, line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlL4e36-Dt4X606WNzW:-MlL4e36-Dt4X606WNzX:b-ej2g78) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/src/fs/sys/fs.c#L77)):*
> ```
> BITS_TO_INTS
> ```

ditto, not `int`
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlL4VGoBGWEt1KwH-3n:-MlL4VGoBGWEt1KwH-3o:b-9yau8e) ([raw file](https://github.com/gramineproject/gramine/blob/e0598eeb75c5e4e8115fb5bd0e0ed9a2dfd20fa0/LibOS/shim/src/fs/sys/fs.c#L109)):*
> ```
> j-1 == 0
> ```

Actually, this can't ever be false - in this whole case we just print a single `uint32_t`, so it could even be moved out of the loop (this may make the code simpler).
___
*[LibOS/shim/src/fs/sys/fs.c, line 116 at r6](https://reviewable.io/reviews/gramineproject/gramine/106#-MlL4LGdBtrSKqPu65ru:-MlL4LGeBIRgzPif9bF1:b-nmawbg) ([raw file](https://github.com/ [...]

2022-01-22 05:16 UTC, closed without merging