[LibOS,PAL] Avoid using double error in error logs
gramineproject/gramine pull request #1069
Opened 2022-11-30 15:56 UTC by oshogbo

## Description of the changes 

When Gramine logs something, the log level tag is added at the beginning of the message. This commit rephrases logs in which the tag and first word of the message are exactly the same.
Thanks to that user won't see logs like:
```
error: error mounting "/re" under "/xxx"
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1069)

2022-11-30 16:26 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1069#-NI8KQLpCUWDXtYsuVUP):*
Or something, to make it more clear



_Suggestion:_
```
[LibOS,PAL] Avoid using double "error" word in error logs
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/1069#-NI8Ll6q26yA204_69lw:-NI8Ll6q26yA204_69lx:br73jhn) ([raw file](https://github.com/gramineproject/gramine/blob/85a0c746ecb950e93da6fc39a4f02cad3cd3163a/pal/src/host/linux-sgx/host_profile.c#L192)):*
> ```C
> 
>     if (ret < 0) {
>         log_error("recording sample: %d", ret);
> ```

I would add `failed` before `:`. Also since there are multiple messages with same content, I would add __func__ or change the message
ditto whole file


<!-- Sent from Reviewable.io -->

2022-11-30 16:55 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/host_profile.c` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/1069#-NI8Ll6q26yA204_69lw:-NI8SOFIEUB0vmwhpYYs:b-lasszw) ([raw file](https://github.com/gramineproject/gramine/blob/85a0c746ecb950e93da6fc39a4f02cad3cd3163a/pal/src/host/linux-sgx/host_profile.c#L192)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
I'm trying to address the func name in a separate issue: https://github.com/gramineproject/gramine/pull/1040
</blockquote></details>

I don't like the idea of universally adding function name, especially before `[...]` prefix.


<!-- Sent from Reviewable.io -->

2022-12-01 09:21 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-12-02 03:48 UTC, yamahata reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069#-:-NIFwhvsEPN24TANrHy6:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-12-02 12:06 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-12-02 19:42 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-12-02 20:31 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-12-02 20:46 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1069)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-07 23:04 UTC, merged