[LibOS,PAL] Support `(E)POLLRDHUP` and treat error events separately
gramineproject/gramine pull request #1073
Opened 2022-12-07 07:27 UTC by kailun-qin

Previously, `(E)POLLRDHUP` was not reported and `(E)POLLHUP` was always reported together with `(E)POLLERR` due to the limitation of PAL API, which did not distinguish these conditions. This may cause some workloads to ignore the fact that the socket was closed by the peer and hence keep it in the `CLOSE-WAIT` state.

This commit adds support for `(E)POLLRDHUP` and treats the error events (`(E)POLLERR`, `(E)POLLHUP`, `(E)POLLNVAL`, `(E)POLLRDHUP`) separately.

2022-12-09 08:18 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`libos/src/sys/libos_epoll.c` line 671 at r1](https://reviewable.io/reviews/gramineproject/gramine/1073#-NIpxBFMBb2MEGiIHvKq:-NIpxBFMBb2MEGiIHvKr:b44113r) ([raw file](https://github.com/gramineproject/gramine/blob/8a36c461efa87bea5fb70ae98a533a1ac9755119/libos/src/sys/libos_epoll.c#L671)):*
> ```C
>             }
>             if (pal_ret_events[i] & PAL_WAIT_RDHUP) {
>                 this_item_events |= EPOLLRDHUP;
> ```

Pls kindly note that `EPOLLRDHUP` is not available in Windows. But I think it should be fine for now.


<!-- Sent from Reviewable.io -->

2022-12-09 08:20 UTC, kailun-qin reviewed
ping @boryspoplawski. This is a customer issue, pls kindly take a look when you get a chance and see if it makes sense to you. Thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073#-:-NIpxpHbEHI2Lkmtr2pb:by0fysk)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-12-10 00:44 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NItU2Yz7g20n8IeMBL2:-NItU2Z-E0qFsrMgYZwj:by0k9lz) (no related file):*
> ping @boryspoplawski. This is a customer issue, pls kindly take a look when you get a chance and see if it makes sense to you. Thanks!

Shouldn't you first fix the failing CI on this PR before pinging Borys to review it? ;)

___


<!-- Sent from Reviewable.io -->

2022-12-10 23:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NItU2Yz7g20n8IeMBL2:-NIySojF0jLmn-vkhj3T:bkfor9q) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks @mkow, still not accessible for now but I'll double check.

Fixed the issue (CI pytest run in parallel...) and the `pkg-deb-debian11` pipeline failure should be sth. irrelevant (I guess).

</blockquote></details>

Yeah, you'll need to rebase the PR on the current master to make it work. From what I see in Reviewable no one started the review yet, so it should be fine to rebase and force push.

___


<!-- Sent from Reviewable.io -->

2022-12-11 13:16 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NItU2Yz7g20n8IeMBL2:-NJ0K5-X-DWzNR4eGZZR:b-c47yrb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, you'll need to rebase the PR on the current master to make it work. From what I see in Reviewable no one started the review yet, so it should be fine to rebase and force push.
</blockquote></details>

Rebased, thanks!

___


<!-- Sent from Reviewable.io -->

2022-12-15 08:51 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJJyKGo2O7gNMKE7fTO:-NJJyKGo2O7gNMKE7fTP:b117xfe) (no related file):*
You can add `fixes #1034` to automatically close my issue.

___


<!-- Sent from Reviewable.io -->

2022-12-15 09:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJJyKGo2O7gNMKE7fTO:-NJK1xIqDdFca2r5EaiD:b-skcl5j) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

You can add `fixes #1034` to automatically close my issue.
</blockquote></details>

Added, thanks!

___


<!-- Sent from Reviewable.io -->

2022-12-22 00:35 UTC, boryspoplawski requested changes
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 3 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NJr8PP0CY28Jy7WIzZb:bh07rr1) (no related file):*
Wouldn't it be enough to report `EPOLLRDHUP | EPOLLHUP` or just never report `EPOLLRDHUP`, i.e. do not distinguish these two states (so basically this PR would split error from hup/socket close) ?
We should strive to keep the PAL API minimal

___
___
*[`libos/src/sys/libos_epoll.c` line 671 at r1](https://reviewable.io/reviews/gramineproject/gramine/1073#-NIpxBFMBb2MEGiIHvKq:-NJr9E1h756VharzSJcm:b191d3c) ([raw file](https://github.com/gramineproject/gramine/blob/8a36c461efa87bea5fb70ae98a533a1ac9755119/libos/src/sys/libos_epoll.c#L671)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls kindly note that `EPOLLRDHUP` is not available in Windows. But I think it should be fine for now.
</blockquote></details>

And if one was to add Windows PAL, how could they work around this?
___
*[`libos/test/regression/epoll_test.c` line 198 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrDTgjA1PMZfGzzxM3:-NJrDTgjA1PMZfGzzxM4:b3znbj) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/libos/test/regression/epoll_test.c#L198)):*
> ```C
>     }
>     CHECK(close(pipefd));
> ```

Shouldn't we wait for ack from client that it closed the socket and only then do `epoll_wait`?
Current version (timeout  > 0) can race so that client does not close the socket before epoll ends.
Setting infinite timeout could potentially deadlock the app.
So IMO the best option is to close the socket in client, then send ack to the server and only then do `epoll_wait` in server (with timeout = 0).
Note this would require changing pipes to socketpair
___
*[`libos/test/regression/epoll_test.c` line 249 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrEbcc59OQemz0sSu5:-NJrEbcc59OQemz0sSu6:bzhpp13) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/libos/test/regression/epoll_test.c#L249)):*
> ```C
>         CHECK(close(pipefds[1]));
>         client(pipefds[0]);
>         return;
> ```

The child should `exit(0)` here, not return to main.
___
*[`pal/include/pal/pal.h` line 808 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrFHegDEZAs5_dHysg:-NJrFHegDEZAs5_dHysh:b-ivcrcg) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/pal/include/pal/pal.h#L808)):*
> ```objc
> #define PAL_WAIT_READ   1
> #define PAL_WAIT_WRITE  2
> #define PAL_WAIT_ERR    4
> ```

What was wrong with `ERROR`? I don't feel like it was too long...
___
*[`pal/include/pal/pal.h` line 810 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrA57y62AN58gETbMk:-NJrA58-3vkoP51fVl-X:b-37rold) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/pal/include/pal/pal.h#L810)):*
> ```objc
> #define PAL_WAIT_ERR    4
> #define PAL_WAIT_HUP    8
> #define PAL_WAIT_NVAL   16
> ```

This flag makes no sense, LibOS must always pass correct handles. Please remove it.


<!-- Sent from Reviewable.io -->

2022-12-22 03:42 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 3 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NJrk91T4p9_ECFd1FAI:b-5eyvzf) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wouldn't it be enough to report `EPOLLRDHUP | EPOLLHUP` or just never report `EPOLLRDHUP`, i.e. do not distinguish these two states (so basically this PR would split error from hup/socket close) ?
We should strive to keep the PAL API minimal
</blockquote></details>

hmm... I think never reporting `EPOLLRDHUP` should not be a good idea as it's widely used and can be a potential cause of some workloads keeping the (half-closed) sockets in the `CLOSE-WAIT` state (the issue we saw in some customers' workloads). And `EPOLLRDHUP` and `EPOLLHUP` can be treated differently in workloads as `EPOLLRDHUP` is specifically for those half shutdown cases. I understand the intention to minimize the PAL API, but do we want to save the one here? Any thoughts?

___
___
*[`libos/src/sys/libos_epoll.c` line 671 at r1](https://reviewable.io/reviews/gramineproject/gramine/1073#-NIpxBFMBb2MEGiIHvKq:-NJrpklf6ExH9w_QweGO:b-z0bnug) ([raw file](https://github.com/gramineproject/gramine/blob/8a36c461efa87bea5fb70ae98a533a1ac9755119/libos/src/sys/libos_epoll.c#L671)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And if one was to add Windows PAL, how could they work around this?
</blockquote></details>

If so in the future, the Windows PAL can simply ignore/not report the `RDHUP` flag, any other concerns?
___
*[`libos/test/regression/epoll_test.c` line 198 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrDTgjA1PMZfGzzxM3:-NJrpesyEJfeowIUgfWQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/libos/test/regression/epoll_test.c#L198)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we wait for ack from client that it closed the socket and only then do `epoll_wait`?
Current version (timeout  > 0) can race so that client does not close the socket before epoll ends.
Setting infinite timeout could potentially deadlock the app.
So IMO the best option is to close the socket in client, then send ack to the server and only then do `epoll_wait` in server (with timeout = 0).
Note this would require changing pipes to socketpair
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 249 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrEbcc59OQemz0sSu5:-NJrpfJJ961GlkA7VB6t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/libos/test/regression/epoll_test.c#L249)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The child should `exit(0)` here, not return to main.
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 808 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrFHegDEZAs5_dHysg:-NJrpfmY8EFrwsou48Jn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/pal/include/pal/pal.h#L808)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What was wrong with `ERROR`? I don't feel like it was too long...
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 810 at r3](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJrA57y62AN58gETbMk:-NJrpgLA3blVWMsLTQ3v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ffb98d962926389f892838963840c89099b0c921/pal/include/pal/pal.h#L810)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This flag makes no sense, LibOS must always pass correct handles. Please remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 15:11 UTC, boryspoplawski requested changes
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 2 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NJuMJqT9F6kfAXosu9V:b-mzelg2) (no related file):*
> can be a potential cause of some workloads keeping the (half-closed) sockets in the CLOSE-WAIT state (the issue we saw in some customers' workloads). 

Is it really half-closed, i.e. app still writes to that socket after receiving `EPOLLRDHUP`? Or just getting `EPOLLHUP` would be enough, so that it notices other end closed the connection (basically we would pretend it was full shutdown)

___
___
*[`libos/test/regression/epoll_test.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJuNaz9Dk1cgJffjx3S:-NJuNaz9Dk1cgJffjx3T:bja6p0k) ([raw file](https://github.com/gramineproject/gramine/blob/4f785423c8fea6e8e49182e958f572e07a5bb470/libos/test/regression/epoll_test.c#L188)):*
> ```C
> 
>     memset(&event, 0, sizeof(event));
>     int r = CHECK(epoll_wait(epfd, &event, 1, 1));
> ```

Why did you remove this?


<!-- Sent from Reviewable.io -->

2022-12-23 02:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 0 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NJwjRC21QVKLWjT1_vo:bs9a8lh) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> can be a potential cause of some workloads keeping the (half-closed) sockets in the CLOSE-WAIT state (the issue we saw in some customers' workloads). 

Is it really half-closed, i.e. app still writes to that socket after receiving `EPOLLRDHUP`? Or just getting `EPOLLHUP` would be enough, so that it notices other end closed the connection (basically we would pretend it was full shutdown)
</blockquote></details>

Ah, good point. Make sense to me, I think getting `EPOLLHUP` would be enough.
Updated with a new version where we handle `EPOLLRDHUP` but report it as `EPOLLHUP`.

___
___
*[`libos/test/regression/epoll_test.c` line 188 at r2](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJuNaz9Dk1cgJffjx3S:-NJwuJAIAMvXNuNk8imO:b-p7b8qs) ([raw file](https://github.com/gramineproject/gramine/blob/4f785423c8fea6e8e49182e958f572e07a5bb470/libos/test/regression/epoll_test.c#L188)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove this?
</blockquote></details>

Just felt like it's not a necessary check... Anyway, added it back.


<!-- Sent from Reviewable.io -->

2022-12-23 17:29 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NJztxm9Dpq3yC2RMG9B:b-6qqz33) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Ah, good point. Make sense to me, I think getting `EPOLLHUP` would be enough.
Updated with a new version where we handle `EPOLLRDHUP` but report it as `EPOLLHUP`.
</blockquote></details>

Good, if it also works for the workload in practice, then let's keep the current version.

___
___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzvIifDPWPz2voCaz0):*
Actually, it's more of a `PalStreamsWaitEvents` events, not epoll
___
*[`libos/src/sys/libos_epoll.c` line 590 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzva1tEXPhE1QwM3xx:-NJzva1tEXPhE1QwM3xy:bjb3uuo) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L590)):*
> ```C
>             }
>             if (item->events & EPOLLRDHUP) {
>                 pal_events[items_count] |= PAL_WAIT_HUP;
> ```

Hmm, let's make `PAL_WAIT_HUP` a default just like `PAL_WAIT_ERR`, i.e. let's report it always, even if it's not in the requested flags (just like poll on Linux does). This would be a PAL change, but I put the comment here, so this line can be removed

Also this version does not support `EPOLLHUP`
___
*[`libos/src/sys/libos_epoll.c` line 667 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzxlPgANT38nRckROG:-NJzxbCJE8M3r-T-C-p8:b-l6i72a) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L667)):*
> ```C
>             }
>             if (pal_ret_events[i] & PAL_WAIT_HUP) {
>                 this_item_events |= EPOLLHUP;
> ```

Hmm, so we do not support `EPOLLRDHUP` at all? It's not what commit message says.
___
*[`libos/src/sys/libos_poll.c` line 152 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzxjwZB0-gZJhJ5Dyo:-NJzxjwZB0-gZJhJ5Dyp:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_poll.c#L152)):*
> ```C
> 
>         if (fds[i].events & POLLRDHUP)
>             allowed_events |= PAL_WAIT_HUP;
> ```

ditto
___
*[`pal/src/host/linux/pal_object.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyXbS9KH1mlvA1VHa:-NJzyXbS9KH1mlvA1VHb:b4txc5y) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L43)):*
> ```C
>             }
>             if (events[i] & PAL_WAIT_HUP) {
>                 fdevents |= POLLRDHUP;
> ```

ditto (default)
Also what I had in mind was reporting `POLLRDHUP` (if app requested id) whenever we report `POLLHUP`. PAL layer would be not aware of existence of `RDHUP` at all.
___
*[`pal/src/host/linux/pal_object.c` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyKWq5-ha2Nh4cwuy:-NJzyKWq5-ha2Nh4cwuz:bfkc9p) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L95)):*
> ```C
>         /* FIXME: something is wrong here, it reads and writes to flags without any locks... */
>         PAL_HANDLE handle = handle_array[i];
>         if (fds[i].revents & (POLLERR | POLLHUP | POLLNVAL | POLLRDHUP))
> ```

Why do we save `ERROR` even on `POLLHUP`?
Actually, I think `HUP` should be also saved, so that host OS cannot report `HUP` on one poll and do not report it on the next one (if for some reason app queries that fd again).
___
*[`pal/src/host/linux/pal_object.c` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--oPm1Yf_dNeqEB7K:-NK--oPm1Yf_dNeqEB7L:b-44zbqk) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L97)):*
> ```C
>         if (fds[i].revents & (POLLERR | POLLHUP | POLLNVAL | POLLRDHUP))
>             handle->flags |= PAL_HANDLE_FD_ERROR;
>         if (fds[i].revents & POLLERR)
> ```

Why did you change this? It's wrong
___
*[`pal/src/host/linux/pal_object.c` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--I4g2m8-oOqytAO5:-NK--I4g2m8-oOqytAO6:b-8geyeg) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L100)):*
> ```C
>             ret_events[i] |= PAL_WAIT_ERROR;
>         if (fds[i].revents & POLLHUP ||
>                 (fds[i].revents & POLLRDHUP && handle->hdr.type == PAL_TYPE_SOCKET))
> ```

Why only on sockets?
also see above
___
*[`pal/src/host/linux-sgx/pal_object.c` line 41 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--w6dAicEnBzqYL31:-NK--w6dAicEnBzqYL32:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L41)):*
> ```C
>             }
>             if (events[i] & PAL_WAIT_HUP) {
>                 fdevents |= POLLRDHUP;
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 81 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--yGP35YR5kHpbgtB:-NK--yGP35YR5kHpbgtC:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L81)):*
> ```C
>         PAL_HANDLE handle = handle_array[i];
>         if (fds[i].revents & (POLLERR | POLLHUP | POLLNVAL | POLLRDHUP))
>             handle->flags |= PAL_HANDLE_FD_ERROR;
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 82 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK-0gQl0LwtQdljAbrV:-NK-0gQm5dLxA-7kLv8l:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L82)):*
> ```C
>         if (fds[i].revents & (POLLERR | POLLHUP | POLLNVAL | POLLRDHUP))
>             handle->flags |= PAL_HANDLE_FD_ERROR;
>         if (fds[i].revents & POLLERR)
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_object.c` line 85 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK-0hHP4qWvqgdMFR7f:-NK-0hHP4qWvqgdMFR7g:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L85)):*
> ```C
>             ret_events[i] |= PAL_WAIT_ERROR;
>         if (fds[i].revents & POLLHUP ||
>                 (fds[i].revents & POLLRDHUP && handle->hdr.type == PAL_TYPE_SOCKET))
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-01-02 16:23 UTC, dimakuv requested changes
> Reviewed 6 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJr8PP0CY28Jy7WIzZa:-NKnBz7k2Ps67oMmcH4u:bpgqhpj) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Good, if it also works for the workload in practice, then let's keep the current version.
</blockquote></details>

+1 from my side too. "Merging" `EPOLLRDHUP` and reporting it as `EPOLLHUP` to the app should work correctly for all apps.

___
___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzvIifDPWPz2voCaz0):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, it's more of a `PalStreamsWaitEvents` events, not epoll
</blockquote></details>

But only poll and epoll use these error/hup events. So I wouldn't change the commit message, as the current title is concise and describes the original problem that was detected on workloads.
___
*[`libos/src/sys/libos_epoll.c` line 590 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzva1tEXPhE1QwM3xx:-NKnDzx14P0F4AtzREul:b5u4fa3) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L590)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, let's make `PAL_WAIT_HUP` a default just like `PAL_WAIT_ERR`, i.e. let's report it always, even if it's not in the requested flags (just like poll on Linux does). This would be a PAL change, but I put the comment here, so this line can be removed

Also this version does not support `EPOLLHUP`
</blockquote></details>

+1 to @boryspoplawski. Basically, we'll have PAL always report `PAL_WAIT_ERR` and `PAL_WAIT_HUP`, regardless of requested `item->events` flags (just like Linux does). And then at the end of this funciton, if user requested `EPOLLRDHUP` and PAL returned `PAL_WAIT_HUP`, then we'll also set `EPOLLRDHUP` as the event.
___
*[`libos/src/sys/libos_epoll.c` line 667 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzxlPgANT38nRckROG:-NKnEh5l6V_TOqyF49iX:blycqfq) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L667)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, so we do not support `EPOLLRDHUP` at all? It's not what commit message says.
</blockquote></details>

Agreed with @boryspoplawski . I would expect something like this here:
```
            if (pal_ret_events[i] & PAL_WAIT_HUP) {
                this_item_events |= EPOLLHUP;
                if (items[i]->events & EPOLLRDHUP) {
                    /* add  RDHUP event only if user requested for it to be reported */
                    this_item_events |= EPOLLRDHUP;
                }
            }
```
___
*[`libos/src/sys/libos_poll.c` line 183 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFFlM55vTpxdq70kk:-NKnFFlM55vTpxdq70kl:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_poll.c#L183)):*
> ```C
>                 fds[i].revents |= POLLERR;
>             if (ret_events[fds_mapping[i].idx] & PAL_WAIT_HUP)
>                 fds[i].revents |= POLLHUP;
> ```

ditto
___
*[`libos/test/regression/epoll_test.c` line 207 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFh0p-ozxKqCMflVE:-NKnFh0p-ozxKqCMflVF:b-t9mhh5) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/test/regression/epoll_test.c#L207)):*
> ```C
>     memset(&event, 0, sizeof(event));
>     r = CHECK(epoll_wait(epfd, &event, 1, 0));
>     if (r != 1 || event.events != (EPOLLIN | EPOLLHUP) || event.data.fd != client) {
> ```

Shouldn't it be `EPOLLRDHUP`?
___
*[`pal/src/host/linux/pal_object.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyXbS9KH1mlvA1VHa:-NKnG1Ht9eGaLr5u2m1X:b-qgwxiz) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (default)
Also what I had in mind was reporting `POLLRDHUP` (if app requested id) whenever we report `POLLHUP`. PAL layer would be not aware of existence of `RDHUP` at all.
</blockquote></details>

+1, exactly as Borys said.

Well, what I would do is:
1. Set `fdevents |= POLLRDHUP` unconditionally here, so that the host `ppoll()` always reports `POLLRDHUP` if it happened.
2. After `ppoll()`, I'd check:
```
if (fds[i].revents & POLLHUP || fds[i].revents & POLLRDHUP)
    ret_events[i] |= PAL_WAIT_HUP;
```
___
*[`pal/src/host/linux/pal_object.c` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyKWq5-ha2Nh4cwuy:-NKnHEZ512l_-RH5y8id:bc2w4m8) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L95)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we save `ERROR` even on `POLLHUP`?
Actually, I think `HUP` should be also saved, so that host OS cannot report `HUP` on one poll and do not report it on the next one (if for some reason app queries that fd again).
</blockquote></details>

+1 to Borys. We need to do like this:
```
        /* report error events on this FD */
        if (fds[i].revents & (POLLERR | POLLNVAL))
            handle->flags |= PAL_HANDLE_FD_ERROR;
        if (handle->flags & PAL_HANDLE_FD_ERROR)
            ret_events[i] |= PAL_WAIT_ERROR;

        /* report hup events on this FD */
        if (fds[i].revents & (POLLHUP | POLLRDHUP))
            handle->flags |= PAL_HANDLE_FD_HUP;
        if (handle->flags & PAL_HANDLE_FD_HUP)
            ret_events[i] |= PAL_WAIT_HUP;

```
___
*[`pal/src/host/linux/pal_object.c` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--I4g2m8-oOqytAO5:-NKnHX9V91U2BqtQoY48:brit4iq) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why only on sockets?
also see above
</blockquote></details>

+1 to the question, why only sockets?


<!-- Sent from Reviewable.io -->

2023-01-04 02:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[`libos/src/sys/libos_epoll.c` line 590 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzva1tEXPhE1QwM3xx:-NKuYAQV9wcwsvQOJ-7_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L590)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @boryspoplawski. Basically, we'll have PAL always report `PAL_WAIT_ERR` and `PAL_WAIT_HUP`, regardless of requested `item->events` flags (just like Linux does). And then at the end of this funciton, if user requested `EPOLLRDHUP` and PAL returned `PAL_WAIT_HUP`, then we'll also set `EPOLLRDHUP` as the event.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_epoll.c` line 667 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzxlPgANT38nRckROG:-NKuYE6y4tAkseT-eau4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_epoll.c#L667)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Agreed with @boryspoplawski . I would expect something like this here:
```
            if (pal_ret_events[i] & PAL_WAIT_HUP) {
                this_item_events |= EPOLLHUP;
                if (items[i]->events & EPOLLRDHUP) {
                    /* add  RDHUP event only if user requested for it to be reported */
                    this_item_events |= EPOLLRDHUP;
                }
            }
```
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 152 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzxjwZB0-gZJhJ5Dyo:-NKuYRG580YbzDw7Wec2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_poll.c#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_poll.c` line 183 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFFlM55vTpxdq70kk:-NKuYW7T3Z26MdfSYpCx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/src/sys/libos_poll.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 207 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFh0p-ozxKqCMflVE:-NKuYyhs8UYT0M1opFHl:bhunwzc) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it be `EPOLLRDHUP`?
</blockquote></details>

Yes, the latest version of PR should have `EPOLLRDHUP` (and also `EPOLLHUP`) as we requested it explicitly. Fixed now.

Just for explanation, in the previous version, I always only set `EPOLLHUP` even if user requested `EPOLLRDHUP` and PAL returned `PAL_WAIT_HUP` (i.e. not report `EPOLLRDHUP` to app at all, but I called this "supported" since it was still handled and returned by PAL).
___
*[`pal/src/host/linux/pal_object.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyXbS9KH1mlvA1VHa:-NKu_sdq8kQeyUQZD97_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, exactly as Borys said.

Well, what I would do is:
1. Set `fdevents |= POLLRDHUP` unconditionally here, so that the host `ppoll()` always reports `POLLRDHUP` if it happened.
2. After `ppoll()`, I'd check:
```
if (fds[i].revents & POLLHUP || fds[i].revents & POLLRDHUP)
    ret_events[i] |= PAL_WAIT_HUP;
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NJzyKWq5-ha2Nh4cwuy:-NKubDFwERcXYZ8S06T0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Borys. We need to do like this:
```
        /* report error events on this FD */
        if (fds[i].revents & (POLLERR | POLLNVAL))
            handle->flags |= PAL_HANDLE_FD_ERROR;
        if (handle->flags & PAL_HANDLE_FD_ERROR)
            ret_events[i] |= PAL_WAIT_ERROR;

        /* report hup events on this FD */
        if (fds[i].revents & (POLLHUP | POLLRDHUP))
            handle->flags |= PAL_HANDLE_FD_HUP;
        if (handle->flags & PAL_HANDLE_FD_HUP)
            ret_events[i] |= PAL_WAIT_HUP;

```
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--oPm1Yf_dNeqEB7K:-NKubF9aDMPugWZ4XZ0z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you change this? It's wrong
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--I4g2m8-oOqytAO5:-NKudQ-I3C2NDhQTfwqa:b-szn3gp) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to the question, why only sockets?
</blockquote></details>

Simply because in Linux, `POLLRDHUP` only works on sockets, not on fifos/pipes or ttys. Removing the check for now if both of you think it's not necessary.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 41 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--w6dAicEnBzqYL31:-NKuc6vWEOStI6uMDt4M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 81 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--yGP35YR5kHpbgtB:-NKucJgL6AN9V27nVKzW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 82 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK-0gQl0LwtQdljAbrV:-NKucK1L4vuTDA0IloCY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux-sgx/pal_object.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 85 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK-0hHP4qWvqgdMFR7f:-NKucKUECI2uXT7tXRsW:b-896fix) ([raw file](https://github.com/g [...]

2023-01-04 10:11 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKwFn3rA5WU-LwDHB4i:-NKwFn3rA5WU-LwDHB4j:bfitu4k) (no related file):*
Does this latest version still fix #1034? I'd like to double-check that the latest changes in this PR still solve that problem.

___
___
*[`libos/test/regression/epoll_test.c` line 207 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFh0p-ozxKqCMflVE:-NKwEJGV1OdhoYSAmAR-:b6qz70r) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, the latest version of PR should have `EPOLLRDHUP` (and also `EPOLLHUP`) as we requested it explicitly. Fixed now.

Just for explanation, in the previous version, I always only set `EPOLLHUP` even if user requested `EPOLLRDHUP` and PAL returned `PAL_WAIT_HUP` (i.e. not report `EPOLLRDHUP` to app at all, but I called this "supported" since it was still handled and returned by PAL).

</blockquote></details>

Another question: why do we get `EPOLLIN`? Is this how it works on Linux, or is it a quirk of Gramine implementation?

From what I see, the client side simply does `connect()` and then immediately `close()`, so there should be no data to read on the server side...
___
*[`pal/src/host/linux/pal_object.c` line 100 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NK--I4g2m8-oOqytAO5:-NKwF2br2EF4nX4fFh-6:b2t71qf) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/pal/src/host/linux/pal_object.c#L100)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Simply because in Linux, `POLLRDHUP` only works on sockets, not on fifos/pipes or ttys. Removing the check for now if both of you think it's not necessary.
</blockquote></details>

I would ignore this fact.


<!-- Sent from Reviewable.io -->

2023-01-04 12:21 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKwFn3rA5WU-LwDHB4i:-NKwfo4v-jQEevdSd3vf:b-xjwcj9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this latest version still fix #1034? I'd like to double-check that the latest changes in this PR still solve that problem.
</blockquote></details>

I don't have much context about https://github.com/gramineproject/gramine/issues/1034 but I think the latest version still fixes it. From the issue description, it seems that the Pytorch utility `TCPStoreWorkerDaemon` only expects **NO** events other than `POLLIN` and `POLLHUP`, i.e., to not report `POLLERR` together with `EPOLLHUP`. Since Pytorch does not explicitly request `POLLRDHUP` and we distinguish `ERR` and `HUP` now, I think the PR should do the trick.

@llly Would you pls kindly help double check? Thanks!

___
___
*[`libos/test/regression/epoll_test.c` line 207 at r5](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKnFh0p-ozxKqCMflVE:-NKwiGS70tqwcJ13rt5I:b-llj0sa) ([raw file](https://github.com/gramineproject/gramine/blob/d246038bb019da97d336e4f1bd4f7ef05e785cb6/libos/test/regression/epoll_test.c#L207)):*
> Is this how it works on Linux, or is it a quirk of Gramine implementation?

It's how it works on Linux - `EPOLLIN` is set together. Pls kindly refer to https://elixir.bootlin.com/linux/v6.1.3/source/net/ipv4/tcp.c#L545 for details.


<!-- Sent from Reviewable.io -->

2023-01-04 14:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKwFn3rA5WU-LwDHB4i:-NKxH195Ab1lMZEJyPiN:bjvaxak) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I don't have much context about https://github.com/gramineproject/gramine/issues/1034 but I think the latest version still fixes it. From the issue description, it seems that the Pytorch utility `TCPStoreWorkerDaemon` only expects **NO** events other than `POLLIN` and `POLLHUP`, i.e., to not report `POLLERR` together with `EPOLLHUP`. Since Pytorch does not explicitly request `POLLRDHUP` and we distinguish `ERR` and `HUP` now, I think the PR should do the trick.

@llly Would you pls kindly help double check? Thanks!
</blockquote></details>

Let me block until @llly replies.

___


<!-- Sent from Reviewable.io -->

2023-01-06 09:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NL5UPaVDsF6AeP1dtP3:-NL5UPaVDsF6AeP1dtP4:bizxx25) (no related file):*
A related PR #1067 was merged now. So we'll need to carefully rebase on top of that PR when the PR is ready for final rebase.

___


<!-- Sent from Reviewable.io -->

2023-01-08 22:35 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @llly, and @woju)

___
*[`libos/src/sys/libos_epoll.c` line 668 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIPRZ3-V_Zuaol_Cd1:-NLIPRZ3-V_Zuaol_Cd2:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/src/sys/libos_epoll.c#L668)):*
> ```C
>                     /* add RDHUP event only if user requested for it to be reported */
>                     this_item_events |= EPOLLRDHUP;
>                 }
> ```





_Suggestion:_
```C
                /* add RDHUP event only if user requested for it to be reported */
                this_item_events |= items[i]->events & EPOLLRDHUP;
```
___
*[`libos/src/sys/libos_poll.c` line 184 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIQ3J94Zba5Re9iy76:-NLIQ3J94Zba5Re9iy77:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/src/sys/libos_poll.c#L184)):*
> ```C
>                     /* add RDHUP event only if user requested for it to be reported */
>                     fds[i].revents |= POLLRDHUP;
>                 }
> ```





_Suggestion:_
```C
                /* add RDHUP event only if user requested for it to be reported */
                fds[i].revents |= fds[i].events & POLLRDHUP;
```
___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NLIUW1CDHHHQV_XEaAW:b9b1czr) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
> ```C
>     memset(&event, 0, sizeof(event));
>     r = CHECK(epoll_wait(epfd, &event, 1, 0));
>     if (r != 1 || event.events != (EPOLLIN | EPOLLHUP | EPOLLRDHUP) || event.data.fd != client) {
> ```

Does this test pass native?


<!-- Sent from Reviewable.io -->

2023-01-09 01:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @llly, and @woju)

___
*[`libos/src/sys/libos_epoll.c` line 668 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIPRZ3-V_Zuaol_Cd1:-NLJ508X87wpNEMfra84:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/src/sys/libos_epoll.c#L668)):*
> ```C
>                     /* add RDHUP event only if user requested for it to be reported */
>                     this_item_events |= EPOLLRDHUP;
>                 }
> ```

Done.
___
*[`libos/src/sys/libos_poll.c` line 184 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIQ3J94Zba5Re9iy76:-NLJ50pFBWvn1iVI66RO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/src/sys/libos_poll.c#L184)):*
> ```C
>                     /* add RDHUP event only if user requested for it to be reported */
>                     fds[i].revents |= POLLRDHUP;
>                 }
> ```

Done.
___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NLJ51zCCm8INrZqrruT:b-iqphue) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Does this test pass native?
</blockquote></details>

No, we won't get `EPOLLHUP` natively.


<!-- Sent from Reviewable.io -->

2023-01-09 09:15 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 7 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NKwFn3rA5WU-LwDHB4i:-NLKo30ZCq12TYrnKb0G:bb6ywmx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me block until @llly replies.
</blockquote></details>

LGTM

___


<!-- Sent from Reviewable.io -->

2023-01-09 09:40 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @woju)



<!-- Sent from Reviewable.io -->

2023-04-16 22:59 UTC, mkow reviewed
> Reviewed 1 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NL5UPaVDsF6AeP1dtP3:-NTBH_0cBlhybXL9HYvX:bj6gxmi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A related PR #1067 was merged now. So we'll need to carefully rebase on top of that PR when the PR is ready for final rebase.
</blockquote></details>

@kailun-qin: Could you do that rebase? This PR conflicts with #1067 in `poll()` code.
I can review it afterwards.

___


<!-- Sent from Reviewable.io -->

2023-04-17 01:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1073#-NL5UPaVDsF6AeP1dtP3:-NTBqiA28IPLK4shu7TQ:b-c47yrb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@kailun-qin: Could you do that rebase? This PR conflicts with #1067 in `poll()` code.
I can review it afterwards.
</blockquote></details>

Rebased, thanks!

___


<!-- Sent from Reviewable.io -->

2023-04-17 22:16 UTC, mkow requested changes
> Reviewed 2 of 8 files at r6, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`libos/src/sys/libos_epoll.c` line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGDGlW4ix16coYBoyY:-NTGDGlW4ix16coYBoyZ:b46uq5j) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/src/sys/libos_epoll.c#L17)):*
> ```C
>  * - adding an epoll to another epoll instance is not supported, but should be implementable without
>  *   design changes if need be,
>  * - `EPOLLRDHUP` is always reported as `EPOLLHUP` - this is current limitation of PAL API, which
> ```

Not `EPOLLRDHUP | EPOLLHUP`?



_Code quote:_
```C
`EPOLLRDHUP` is always reported as `EPOLLHUP`
```
___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NTGD1z37zvy85fTCGBL:bgu1nee) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

No, we won't get `EPOLLHUP` natively.
</blockquote></details>

Then I wouldn't test this, it's an incorrect behavior of Gramine. It's IMO useful to make the tests also work natively when possible.
___
*[`libos/test/regression/epoll_test.c` line 191 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGFbv40YYQvGbGewrK:-NTGFbv5DWseSxVdBXln:bho4t3t) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L191)):*
> ```C
>     int r = CHECK(epoll_wait(epfd, &event, 1, 0));
>     if (r != 0) {
>         ERR("epoll_wait returned: %d, events: %#x, data: %d", r, event.events, event.data.fd);
> ```

This is a file descriptor, not data?



_Code quote:_
```C
data: %d
```
___
*[`libos/test/regression/epoll_test.c` line 196 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGEt9YDzd7-jcL7cuR:-NTGEt9YDzd7-jcL7cuS:b7zi1bj) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L196)):*
> ```C
>     x = CHECK(write(sockfd, &c, sizeof(c)));
>     if (x != 1) {
>         CHECK(-1);
> ```

Why not `ERR()`?
___
*[`libos/test/regression/epoll_test.c` line 201 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGEz8S9u3H-jWC2YnU:-NTGEz8S9u3H-jWC2YnV:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L201)):*
> ```C
>     x = CHECK(read(sockfd, &c, sizeof(c)));
>     if (x != 1) {
>         CHECK(-1);
> ```

ditto
___
*[`libos/test/regression/epoll_test.c` line 208 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGFHiKEbkxE1ChNaQP:-NTGFHiLDZ6xQbf-VUJ8:bho4t3t) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L208)):*
> ```C
>     r = CHECK(epoll_wait(epfd, &event, 1, 0));
>     if (r != 1 || event.events != (EPOLLIN | EPOLLHUP | EPOLLRDHUP) || event.data.fd != client) {
>         ERR("epoll_wait returned: %d, events: %#x, data: %d", r, event.events, event.data.fd);
> ```

This is a file descriptor, not data?



_Code quote:_
```C
data: %d
```
___
*[`pal/include/pal/pal.h` line 812 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTG9gUbEWOOrBBlmwKx:-NTG9gUbEWOOrBBlmwKy:b-vl3cd0) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/include/pal/pal.h#L812)):*
> ```objc
> #define PAL_WAIT_WRITE  2
> #define PAL_WAIT_ERROR  4
> #define PAL_WAIT_HUP    8
> ```

Let's not cultivate that POSIX/Unix/Linux madness of creating undecodable abbreviations. Just `HUNG_UP`.



_Code quote:_
```objc
PAL_WAIT_HUP
```
___
*[`pal/src/host/linux/pal_host.h` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGBarh1BHosT2yuO09:-NTGBarh1BHosT2yuO0A:b-ty4981) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L117)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```

I'd drop this, such comments quite often silently turn incorrect after we add features, it's hard to keep them up to date and they aren't terribly useful even when still correct IMO.



_Code quote:_
```objc
Currently only set by `_PalStreamsWaitEvents`.
```
___
*[`pal/src/host/linux/pal_host.h` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGHYdY8ijAzpRHUOsV:-NTGHYdY8ijAzpRHUOsW:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L117)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```





_Suggestion:_
```objc
a hang-up was
```
___
*[`pal/src/host/linux/pal_host.h` line 118 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGB67N1wDP9qHmU-tf:-NTGB67O0SR9AH7ozKvI:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L118)):*
> ```objc
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_HUP       8
> ```

ditto
___
*[`pal/src/host/linux/pal_object.c` line 113 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGY_Z45whfMU7Ayp3:-NTGGY_Z45whfMU7Ayp4:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_object.c#L113)):*
> ```C
>             ret_events[i] |= PAL_WAIT_ERROR;
> 
>         /* report hup events on this FD */
> ```

ditto



_Code quote:_
```C
hup events
```
___
*[`pal/src/host/linux-sgx/pal_host.h` line 154 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGgaiBJrmR0w9NGko:-NTGGgaiBJrmR0w9NGkp:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_host.h#L154)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```





_Suggestion:_
```objc
a hang-up was
```
___
*[`pal/src/host/linux-sgx/pal_host.h` line 154 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGl5jBwsSGpv8jNl-:-NTGGl5jBwsSGpv8jNl0:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_host.h#L154)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```

ditto



_Code quote:_
```objc
Currently only set by `_PalStreamsWaitEvents`.
```
___
*[`pal/src/host/linux-sgx/pal_host.h` line 155 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGH50JBKH3pVQ [...]

2023-04-18 02:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_epoll.c` line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGDGlW4ix16coYBoyY:-NTGsRz--mxJpoKt1NEr:b4wuaen) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/src/sys/libos_epoll.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `EPOLLRDHUP | EPOLLHUP`?
</blockquote></details>

Yes, changed to "`EPOLLRDHUP` is always reported **together with** `EPOLLHUP`", done.
___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NTGyzCb7fawqOCqBZHh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then I wouldn't test this, it's an incorrect behavior of Gramine. It's IMO useful to make the tests also work natively when possible.
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 191 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGFbv40YYQvGbGewrK:-NTGtOL72FT5qL97PyB5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a file descriptor, not data?
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 196 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGEt9YDzd7-jcL7cuR:-NTGtQf82sbLkoFz2mno:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `ERR()`?
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 201 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGEz8S9u3H-jWC2YnU:-NTGtQO8DHox22Vw2RXy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L201)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/epoll_test.c` line 208 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGFHiKEbkxE1ChNaQP:-NTGtPyM-ldPjSyn6rIo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/libos/test/regression/epoll_test.c#L208)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a file descriptor, not data?
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 812 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTG9gUbEWOOrBBlmwKx:-NTH2Uzp-mndwOJntJSp:b-2143w6) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/include/pal/pal.h#L812)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's not cultivate that POSIX/Unix/Linux madness of creating undecodable abbreviations. Just `HUNG_UP`.
</blockquote></details>

I use `HANG_UP` instead of the proposed `HUNG_UP` (past tense) which seems more reasonable (since it aligns w/ all our comments where we put "hang-up" there and it's actually `HUP` stands for). Let me know if any concern. Thanks!
___
*[`pal/src/host/linux/pal_host.h` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGBarh1BHosT2yuO09:-NTH19Hq05-RPjpGaP5L:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop this, such comments quite often silently turn incorrect after we add features, it's hard to keep them up to date and they aren't terribly useful even when still correct IMO.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_host.h` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGHYdY8ijAzpRHUOsV:-NTH1KCw-n-_uNBzM1M3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L117)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```

Done.
___
*[`pal/src/host/linux/pal_host.h` line 118 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGB67N1wDP9qHmU-tf:-NTH1FdC7b92hGZL7UWB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_host.h#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_object.c` line 113 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGY_Z45whfMU7Ayp3:-NTH4RE-1xDxMjVkHCUB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux/pal_object.c#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 154 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGl5jBwsSGpv8jNl-:-NTH1ydB3p913XunsYar:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_host.h#L154)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 154 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGGgaiBJrmR0w9NGko:-NTH4dDR8aaJMQE44xYH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_host.h#L154)):*
> ```objc
> /* Set if an error was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> #define PAL_HANDLE_FD_ERROR     4
> /* Set if a hang up (HUP) was seen on this handle. Currently only set by `_PalStreamsWaitEvents`. */
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 155 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGH50JBKH3pVQ1FaKc:-NTH4e0y08XOXkJfJxw0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_host.h#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_object.c` line 99 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTGH8ckBqolIdzWPoML:-NTH4ila3PHMHh72pm3Q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/src/host/linux-sgx/pal_object.c#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 13:26 UTC, mkow requested changes
> Reviewed 7 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 2 at r9](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTJVx4lCY_RilfllnQI):*
Can be fixed at the final rebase.



_Suggestion:_
```
hang-up events
```
___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NTJWY-41yFFpeQOEHuP:b-w0r8y0) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But now you changed the code to ignore all other events also, not only `EPOLLHUP`?
___
*[`pal/include/pal/pal.h` line 812 at r8](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTG9gUbEWOOrBBlmwKx:-NTJXDI8BrLBJpa8gU6X:bygtg6h) ([raw file](https://github.com/gramineproject/gramine/blob/953f9093ceb1a821cc5f3de83747821c66e2f927/pal/include/pal/pal.h#L812)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I use `HANG_UP` instead of the proposed `HUNG_UP` (past tense) which seems more reasonable (since it aligns w/ all our comments where we put "hang-up" there and it's actually `HUP` stands for). Let me know if any concern. Thanks!
</blockquote></details>

Sure, makes sense.


<!-- Sent from Reviewable.io -->

2023-04-18 14:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/epoll_test.c` line 207 at r6](https://reviewable.io/reviews/gramineproject/gramine/1073#-NLIUW1CDHHHQV_XEaAV:-NTJmQsS5I9nbU8W0nm1:bx29h42) ([raw file](https://github.com/gramineproject/gramine/blob/9adbbc5a0dd4c4f24bd0ca498aed7124d706eaec/libos/test/regression/epoll_test.c#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you changed the code to ignore all other events also, not only `EPOLLHUP`?
</blockquote></details>

Yep, I only checked the events that should be reported natively (`EPOLLIN | EPOLLRDHUP`). But I agree it's better to not ignore the others. Updated.


<!-- Sent from Reviewable.io -->

2023-04-18 14:46 UTC, mkow approved these changes
> Reviewed 1 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`libos/test/regression/epoll_test.c` line 207 at r10](https://reviewable.io/reviews/gramineproject/gramine/1073#-NTJoQm48oY-9B3qIYv0:-NTJoQm48oY-9B3qIYv1:b-mexwpc) ([raw file](https://github.com/gramineproject/gramine/blob/f0a3d5643111cb73c76a8f71b22a94ea415beef3/libos/test/regression/epoll_test.c#L207)):*
> ```C
>     memset(&event, 0, sizeof(event));
>     r = CHECK(epoll_wait(epfd, &event, 1, 0));
>     /* `EPOLLRDHUP` is always reported together with `EPOLLHUP` in Gramine as a limitation. We thus
> ```

Limitation of what? This is quite ambiguous :) We can fix this on rebase.



_Suggestion:_
```C
as its limitation
```


<!-- Sent from Reviewable.io -->

2023-04-20 02:04 UTC, mkow approved these changes
FYI: Dismissing Borys, he won't have time to re-review this now and is ok with dismissing his blocking comments (but I checked that they all have been fixed).

> Reviewed 1 of 1 files at r11, all commit messages.
> Dismissed @boryspoplawski from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073#-:-NTROXMl1hcVRDyQH_Vf:b-x4wfbm)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-20 06:28 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1073)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-20 06:30 UTC, merged