[PAL/Linux-SGX] Retrieve fault address from SSA if available
gramineproject/gramine pull request #1075
Opened 2022-12-08 19:46 UTC by boryspoplawski

## Description of the changes 
If `miscselect & 1` then we can retrieve fault address on page faults from EXINFO structure (in SSA)

2022-12-10 18:37 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`Documentation/manifest-syntax.rst` line 588 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDby663u3Z7YDAqI-:-NIxDby663u3Z7YDAqI0:b-gugsft) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L588)):*
> ```reStructuredText
> on the platform, enclave initialization will fail. If the options are unset,
> enclave initialization will succeed even if these features are unavailable on
> the platform.
> ```

Did you forget to remove this copy-pasted paragraph?
___
*[`Documentation/manifest-syntax.rst` line 590 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDgUN7a81R8w9jh1F:-NIxDgUN7a81R8w9jh1G:b-y8h9af) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L590)):*
> ```reStructuredText
> the platform.
> If ``require_exinfo`` is set, user application can retrieve faulting address in
> signal handler in case of a page fault.
> ```

I'm not sure what happens if it is set to `false` (the enclave needs to rely on the possibly-malicious value of the faulting address from the host?). And what happens if it is set to `true` (the enclave won't start on older CPUs)?
___
*[`pal/regression/Exception.c` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDyRJD6Ow69J5suRk:-NIxDyRJD6Ow69J5suRl:b-6vud77) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/regression/Exception.c#L1)):*
> ```C
> /* TODO: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!! */
> ```

That's not 100 char limit :)

What exactly is the problem? The code doesn't look crazy.
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 514 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxH3mx57KLLe_VVdNY:-NIxH3mx57KLLe_VVdNZ:bjagh0j) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L514)):*
> ```
> 
>     # Save EXINFO - it's always at offset -16 from GPR in SSA.
>     # If EXINFO MISC component is not enabled, it will contain all 0.
> ```

Why would it contain all-zeros? If I understand correctly and looking at Intel SDM's table 34-8, if there is no MISCSELECT component enabled/existing on the CPU, then we'll copy 16 bytes from the end of the XSAVE area (these 16 bytes may be all-zeros because XSAVE area is padded to 4KB, but this is not required).

Hm, the Table 34-8 also says "Pad is Chosen by enclave writer". I guess you're using this trick, and I need to review further...

UPDATE: I finished reviewing the PR, but still don't understand how you make sure you don't use the end of the XSAVE area here.
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxHe_KE4Ta7rGP4_D3:-NIxHe_KE4Ta7rGP4_D4:bm24u3l) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L551)):*
> ```
>     jmp __restore_xregs
> 1:
>     leaq SGX_CPU_CONTEXT_SIZE + 16 + 8(%rsi), %rdi
> ```

Meh, we'll forget what this `16` means in this calculation. Either add a constant `MISCSELECT_EXINFO_SIZE`, or add a comment here.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 245 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxHu9W5TRngH_DlyTU:-NIxHu9W5TRngH_DlyTV:bxncw3c) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_framework.c#L245)):*
> ```C
> #define BYTES2HEX(bytes) (bytes2hex(bytes, sizeof(bytes), hex, sizeof(hex)))
>     log_debug("  cpu_svn:     %s",     BYTES2HEX(r->body.cpu_svn.svn));
>     log_debug("  misc_select: %08x",   r->body.misc_select);
> ```

Why `0x8`? Shouldn't it be `0x16`?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 259 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxIF0A0XgzdQVQ6sPC:-NIxIF0A0XgzdQVQ6sPD:b5s96ve) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/pal_exception.c#L259)):*
> ```C
>         }
>         if (ei.info.vector == SGX_EXCEPTION_VECTOR_PF) {
>             ctx.cr2 = exinfo->maddr;
> ```

Is it always the case that if we CPU supports reporting `SGX_EXCEPTION_VECTOR_PF`, then the CPU also supports MISCSELECT.EXINFO?

Otherwise don't we need to add an additional check that the CPU indeed supports EXINFO?

UPDATE: Ok, table 34-11 is explicit about this. So the answer to my first question is "YES".
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJ33l4KTa6aVYJ5L6:-NIxJ33m81PFHfoMazen:b-bpoo41) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L248)):*
> ```objc
> 
> typedef struct {
>     uint64_t maddr;
> ```

I would also add a comment from Table 34.13 ("If #PF: contains the page fault ..." and that it's clear on other exceptions)
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 260 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJJWF-KYb-nHg36-H:-NIxJJWG1BzplWAt4yCJ:b-gkmm8t) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L260)):*
> ```objc
>             uint32_t sgx:1;
>             uint32_t reserved2:16;
>         } errcd;
> ```

I would add comments from Table 34-14 here
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 261 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJeAD6cyI36puqQg8:-NIxJeAD6cyI36puqQg9:bjb5fc3) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L261)):*
> ```objc
>             uint32_t reserved2:16;
>         } errcd;
>         uint32_t error_code_val;
> ```

What's that? Is this for GP/CP exceptions? Intel SDM is vague on this...
___
*[`python/graminelibos/sgx_sign.py` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxFhSZDmb2Fp04GZwx:-NIxFhSZDmb2Fp04GZwy:b-jjuq8k) ([raw file](https://github.com/gramineproject/gramine/blob/43e2826cdfc5973c2662ab50817dbfc2db6343de/python/graminelibos/sgx_sign.py#L95)):*
> ```Python
> 
>     miscs_dict = {
>         'support_exinfo': offs.SGX_MISCSELECT_EXINFO,
> ```

This `support_exinfo` was never really used?
___
*[`tools/sgx/is-sgx-available/is_sgx_available.cpp` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxCxZeAQCjFWQo1eB3:-NIxCxZeAQCjFWQo1eB4:b17byg8) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/tools/sgx/is-sgx-available/is_sgx_available.cpp#L123)):*
> ```cpp
>         sgx_virt_supported_ = cpuid_12_0_eax & (1 << 5);
>         sgx_mem_concurrency_supported_ = cpuid_12_0_eax & (1 << 6);
>         supported_miscselect_ = cpuid_12_0_ebx;
> ```

This just gives you all MISCSELECT bits. At least currently, there are two bits (separate features): `EXINFO` and `CPINFO`. For the user, seeing `0x3` instead of `EXINFO CPINFO` is quite unintuitive...

Why not report the two fields separately, like we do it for `cpuid_12_0_eax`?
___
*[`tools/sgx/is-sgx-available/is_sgx_available.cpp` line 215 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDKsJ-H [...]

2022-12-12 14:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: 6 of 13 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 588 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDby663u3Z7YDAqI-:-NJ5QKHcDBY8G2f4jE7B:bkel8hr) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L588)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you forget to remove this copy-pasted paragraph?
</blockquote></details>

What do you mean? I indeed copied it from above
___
*[`Documentation/manifest-syntax.rst` line 590 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDgUN7a81R8w9jh1F:-NJ5QRFU3rceJ1yGHqK7:b891xt5) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L590)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure what happens if it is set to `false` (the enclave needs to rely on the possibly-malicious value of the faulting address from the host?). And what happens if it is set to `true` (the enclave won't start on older CPUs)?
</blockquote></details>

If it's set to `true`, then EINIT will fail if CPU does not support it. If set to `false`, then faulting address will be always `0` (there is no value we can forward from the host, even possibly malicious).
___
*[`pal/regression/Exception.c` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDyRJD6Ow69J5suRk:-NJ5Txfa8JYPFt0Sxx6P:b2dvq2e) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/regression/Exception.c#L1)):*
Ok, back to the usual :)

> The code doesn't look crazy.

It adds 1 to `rip` on exceptions, until it hits a `0x90` (be it a nop or part of another instruction)
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 514 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxH3mx57KLLe_VVdNY:-NJ5U_kq9Bnt3bPAnUsf:b-c2orku) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L514)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would it contain all-zeros? If I understand correctly and looking at Intel SDM's table 34-8, if there is no MISCSELECT component enabled/existing on the CPU, then we'll copy 16 bytes from the end of the XSAVE area (these 16 bytes may be all-zeros because XSAVE area is padded to 4KB, but this is not required).

Hm, the Table 34-8 also says "Pad is Chosen by enclave writer". I guess you're using this trick, and I need to review further...

UPDATE: I finished reviewing the PR, but still don't understand how you make sure you don't use the end of the XSAVE area here.
</blockquote></details>

The layout of SSA frame is as follows:
- XSAVE area (size based on enabled features)
- padding chosen by us
- MISC (size based on enabled features)
- GPRs (constant size)

Assuming the padding has size >= 16, reading `[GPR - 16]` always gives either zeroes or EXINFO (if it's enabled).

Would be good to assert this padding size at compile time somewhere, let me try to do that. Done in `pal_linux_defs.h`
If you would like some more explanation somewhere let me know. I have a feeling we should add it, but no idea where (actually, and what)
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxHe_KE4Ta7rGP4_D3:-NJ5Xds6DTj4mkP6FADC:b-imsgq8) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L551)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh, we'll forget what this `16` means in this calculation. Either add a constant `MISCSELECT_EXINFO_SIZE`, or add a comment here.
</blockquote></details>

I didn't want to introduce a constant, because this code assumes it's equal to 16, but I guess a constant + a comment describing this assumption would be cleaner.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 245 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxHu9W5TRngH_DlyTU:-NJ5ZPyKDwNtm5LhhT10:b-an84tb) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_framework.c#L245)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `0x8`? Shouldn't it be `0x16`?
</blockquote></details>

`0x16`? I guess you meant `%016x`?
`misc_select` is `uint32_t`, so at most 8 hexadecimal nibbles - `%08x` to pad with `0`.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 259 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxIF0A0XgzdQVQ6sPC:-NJ5ZxjW3ep4stIDRVHS:bhfergo) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/pal_exception.c#L259)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it always the case that if we CPU supports reporting `SGX_EXCEPTION_VECTOR_PF`, then the CPU also supports MISCSELECT.EXINFO?

Otherwise don't we need to add an additional check that the CPU indeed supports EXINFO?

UPDATE: Ok, table 34-11 is explicit about this. So the answer to my first question is "YES".
</blockquote></details>

Even if it wasn't explicit, we wouldn't need to add any more checks here, since `exinfo` is always valid (in a sense it contains address or all zeroes).
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJ33l4KTa6aVYJ5L6:-NJ5_HJQ4iZJ5N1zWeKW:b6vto7u) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also add a comment from Table 34.13 ("If #PF: contains the page fault ..." and that it's clear on other exceptions)
</blockquote></details>

Why is that important? I don't think we assume that anywhere
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 260 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJJWF-KYb-nHg36-H:-NJ5a9VeEKrKLKviQa9d:b-4c3y6d) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L260)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add comments from Table 34-14 here
</blockquote></details>

We don't use them and they are **not** self explanatory anyway, so I don't see much point. We could link to that table here, but that could be said about most of structs in this file, but for some reason we do not do that (assume it's obvious these structs have to match 1-1 what HW expects?) Also I guess the tables numbering can change between SDM versions?

TL;DR I don't see much point in adding these comments, but we could link to the appropriate table in SDM.
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 261 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJeAD6cyI36puqQg8:-NJ5_q7FBDp81PbDGSkM:b-kwj9nm) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L261)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's that? Is this for GP/CP except [...]

2022-12-12 18:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJ6AeEY8ACa5n4drzUi:-NJ6Z26k0hJmZwBCU4Qt:byas58x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to ask: what was the reason for this PR? Did you just notice that we don't check `EXINFO` and decided to add it? Or was there some workload failing?
</blockquote></details>

There were two things:
1) I was checking if we can remove this untrusted host exceptions passing into enclave (no, because CPUs not supporting EXINFO need it)
2) I was checking if it fixes some bug I was hitting with Java workload on EDMM (kind of educated guess, turned out I was right and it indeed fixed it)

So actually I have no idea why Java works without it, I guess without EDMM there are no PFs anyway and Java works just by some coincidence.

___
___
*[`Documentation/manifest-syntax.rst` line 588 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDby663u3Z7YDAqI-:-NJ6aLB46D8PzdRZjR75:bbqafdg) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L588)):*
> But why? 

Because it applies to this option as well and explains well.

> Maybe just move sgx.require_exinfo to the above "Optional CPU features" section?

I could do that, though I thought this is a separate feature, so making another paragraph made sense (miscselect vs xfrm).
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 514 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxH3mx57KLLe_VVdNY:-NJ6ef6GCMjfBJO_iP_c:bm85vot) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L514)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, this is clear to me now.
</blockquote></details>

Any good idea where to put that in code, so it stays for future?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxJ33l4KTa6aVYJ5L6:-NJ6ewE84YzmmHzP3kzM:b-drq659) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/sgx_arch.h#L248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't, but `maddr` is not an intuitive name... Whatever, I'm not blocking, it's easy to find explanations on this in Intel SDM.
</blockquote></details>

Lot's of names taken directly from SDM are not intuitive :)


<!-- Sent from Reviewable.io -->

2022-12-12 21:15 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Documentation/manifest-syntax.rst` line 588 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDby663u3Z7YDAqI-:-NJ7Ao747HTxsKBol5Iu:b-e16ltv) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L588)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But why? 

Because it applies to this option as well and explains well.

> Maybe just move sgx.require_exinfo to the above "Optional CPU features" section?

I could do that, though I thought this is a separate feature, so making another paragraph made sense (miscselect vs xfrm).
</blockquote></details>

Ok, I'm unblocking. I have no specific arguments either way.

Aren't you supposed to add an empty line in-between paragraphs?
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 514 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxH3mx57KLLe_VVdNY:-NJ7B08B1qyDA53AKuW1:bw7hrb3) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/pal/src/host/linux-sgx/enclave_entry.S#L514)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Any good idea where to put that in code, so it stays for future?
</blockquote></details>

But if one searches for `SSA_MISC_EXINFO_SIZE`, he immediately finds the header with static assert and comments. I think this is enough.


<!-- Sent from Reviewable.io -->

2022-12-14 19:14 UTC, mkow requested changes
> Reviewed 6 of 10 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`Documentation/manifest-syntax.rst` line 584 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGUaoL5Ek7ES4CsC82:-NJGUaoL5Ek7ES4CsC83:b-7cmjdr) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/Documentation/manifest-syntax.rst#L584)):*
> ```reStructuredText
>     (Default: false)
> 
> This syntax ensures that the CPU features are available and enabled for the
> ```

Which "CPU features"? At this point you didn't mention what features you mean.



_Code quote:_
```reStructuredText
the CPU features
```
___
*[`Documentation/manifest-syntax.rst` line 585 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGUlAHAcSfvDQYTZDu:-NJGUlAHAcSfvDQYTZDv:b-b332q) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/Documentation/manifest-syntax.rst#L585)):*
> ```reStructuredText
> 
> This syntax ensures that the CPU features are available and enabled for the
> enclave. If the options are set in the manifest but the features are unavailable
> ```

Plural? So, this is not about `sgx.require_exinfo`? About what, then?
Overall, you use a lot of "the", but it's unclear to me what it refers to.



_Code quote:_
```reStructuredText
If the options are
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGk5osEfXUxPu-CEy9:-NJGk5osEfXUxPu-CEyA:b-c9svpd) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/pal_exception.c#L255)):*
> ```C
>         ctx.trapno = ei.info.vector;
>         if (ei.info.vector == SGX_EXCEPTION_VECTOR_GP
>                 || ei.info.vector == SGX_EXCEPTION_VECTOR_PF) {
> ```

Could you add a comment explaining why only these two exceptions?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 224 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGla3X0I9gW8i6iJ0u:-NJGla3X0I9gW8i6iJ0v:b-tx42e1) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L224)):*
> ```objc
> enum sgx_arch_exception_vector {
>     SGX_EXCEPTION_VECTOR_DE = 0,    /* DIV and IDIV instructions */
>     SGX_EXCEPTION_VECTOR_DB = 1,    /* For Intel use only */
> ```

I think `int1` triggers it?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 231 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGmv3x71xZBFRLh3PS:-NJGmv3x71xZBFRLh3PT:b-7j7lin) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L231)):*
> ```objc
>     SGX_EXCEPTION_VECTOR_PF = 14,   /* #PF exception. Only reported if SECS.MISCSELECT.EXINFO = 1 */
>     SGX_EXCEPTION_VECTOR_MF = 16,   /* x87 FPU floating-point or WAIT/FWAIT instruction */
>     SGX_EXCEPTION_VECTOR_AC = 17,   /* Any data reference in memory */
> ```

These comments list the possible sources, but not precisely the causes of these exceptions? I.e. here only unaligned references can produce it (which additionally depend on a bunch of stuff).
Could you add a comment at the top explaining what these comments describe?

Update: ah, this was just moved from the bottom and updated. But would be nice to make it a bit more clear.



_Code quote:_
```objc
/* Any data reference in memory */
```
___
*[`tools/sgx/is-sgx-available/is_sgx_available.cpp` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJH14cz2XUXlZCZHiRg:-NJH14cz2XUXlZCZHiRh:bb6cwlo) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/tools/sgx/is-sgx-available/is_sgx_available.cpp#L77)):*
> ```cpp
>     bool kss_supported_ = false;
>     bool miscselect_exinfo_pfgp_supported_ = 0;
>     bool miscselect_exinfo_cp_supported_ = 0;
> ```

(x2)



_Suggestion:_
```cpp
bool miscselect_exinfo_cp_supported_ = false;
```


<!-- Sent from Reviewable.io -->

2022-12-14 21:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: 11 of 13 files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 588 at r1](https://reviewable.io/reviews/gramineproject/gramine/1075#-NIxDby663u3Z7YDAqI-:-NJHU5cD1AkgqqVJ3_JJ:b-ie24vi) ([raw file](https://github.com/gramineproject/gramine/blob/56265591677cc359934ab8fcb81f156c75213def/Documentation/manifest-syntax.rst#L588)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'm unblocking. I have no specific arguments either way.

Aren't you supposed to add an empty line in-between paragraphs?
</blockquote></details>

Ok, I'll just remove and add this to the above para
___
*[`Documentation/manifest-syntax.rst` line 584 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGUaoL5Ek7ES4CsC82:-NJHTs1Z5vP9UAEzNizB:ba3dfob) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/Documentation/manifest-syntax.rst#L584)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Which "CPU features"? At this point you didn't mention what features you mean.
</blockquote></details>

Removed
___
*[`Documentation/manifest-syntax.rst` line 585 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGUlAHAcSfvDQYTZDu:-NJHU447Bwpx85Fw-zsr:ba3dfob) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/Documentation/manifest-syntax.rst#L585)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Plural? So, this is not about `sgx.require_exinfo`? About what, then?
Overall, you use a lot of "the", but it's unclear to me what it refers to.
</blockquote></details>

Removed
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGk5osEfXUxPu-CEy9:-NJHUtX_1xk8YrdDT-S-:b35fjgu) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/pal_exception.c#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment explaining why only these two exceptions?
</blockquote></details>

You want me to add a comment saying this is how EXINFO feature works? Or link to SDM? Or what explanation you want me to put here exactly?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 224 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGla3X0I9gW8i6iJ0u:-NJHV8xj3pyOOQJfzOZ0:bpnaj0l) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `int1` triggers it?
</blockquote></details>

Idk, I just converted defines to enum, didn't change anything else
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 231 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGmv3x71xZBFRLh3PS:-NJHVK1c5CpOr_PjkGQC:bpvgyug) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These comments list the possible sources, but not precisely the causes of these exceptions? I.e. here only unaligned references can produce it (which additionally depend on a bunch of stuff).
Could you add a comment at the top explaining what these comments describe?

Update: ah, this was just moved from the bottom and updated. But would be nice to make it a bit more clear.
</blockquote></details>

Yes, I have no idea what is purpose of these comments, but we had them, so I did not touch anything. I can remove all of them if you want
___
*[`tools/sgx/is-sgx-available/is_sgx_available.cpp` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJH14cz2XUXlZCZHiRg:-NJHVl_f50DkjydSfueH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/tools/sgx/is-sgx-available/is_sgx_available.cpp#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(x2)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 21:52 UTC, mkow requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGk5osEfXUxPu-CEy9:-NJHbIR56y1Zq_5jAERL:b9v1l5g) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/pal_exception.c#L255)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You want me to add a comment saying this is how EXINFO feature works? Or link to SDM? Or what explanation you want me to put here exactly?
</blockquote></details>

Just something like "With EXINFO enabled only these two exceptions contain additional information".
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 231 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGmv3x71xZBFRLh3PS:-NJHbePPCEtsNYotv1dJ:bzdczd3) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L231)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, I have no idea what is purpose of these comments, but we had them, so I did not touch anything. I can remove all of them if you want
</blockquote></details>

Could you just fix `int1` (which is incorrect) and then add a short comment at the top saying that the comments contain possible sources of the exceptions? (but not the exact causes)


<!-- Sent from Reviewable.io -->

2022-12-14 23:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: 9 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGk5osEfXUxPu-CEy9:-NJHsS0b7zEc-fJ12grF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/pal_exception.c#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just something like "With EXINFO enabled only these two exceptions contain additional information".
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 231 at r2](https://reviewable.io/reviews/gramineproject/gramine/1075#-NJGmv3x71xZBFRLh3PS:-NJHxBb6B4N7hY5rgyo-:bykbjns) ([raw file](https://github.com/gramineproject/gramine/blob/ae8039691a4aa683f588973873b04847c11d34be/pal/src/host/linux-sgx/sgx_arch.h#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you just fix `int1` (which is incorrect) and then add a short comment at the top saying that the comments contain possible sources of the exceptions? (but not the exact causes)
</blockquote></details>

Done. Comments taken from Intel SDM


<!-- Sent from Reviewable.io -->

2022-12-14 23:38 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-12-14 23:42 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1075)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-15 00:35 UTC, merged