[LibOS] Make `get_new_id` immediately move ID ownership if needed
gramineproject/gramine pull request #109
Opened 2021-09-30 23:48 UTC by boryspoplawski

## Description of the changes 

Previously allocating ID for a new process did not immediately change the ownership of this ID (it happened later in the child process). This could cause a issues when one thread issues a `fork` syscall and another exits, releasing its own thread ID - IPC leader might get notified to release an ID range, which it thinks is a part of a bigger one, since it was not yet notified about the ID ownership change.
This commit causes allocating a new ID to also immediately notify IPC leader about ownership change, atomically w.r.t. other threads in the current process.

2021-10-01 09:26 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv8O_z5HOc0bjcPn-G:-Mkv8Oa-DChOcQgFX4Rn:bssau79) (no related file):*
For my own understanding, is this a scenario for the previous bug:
```
[P1 is the IPC leader]
P1 forks P2
P2 spawns new thread T3

P2 forks P4    simulteneously     T3 exits
[P2 now removes from owned P4 and T3, which triggers "release range 3-4" IPC msg]
P1 receives "release range 3-4" and marks these two as unused

P4 starts and performs `ipc_change_id_owner(4, <vmid>)`
P1 receives ipc_change_id_owner(4) and panics -- ID 4 unknown!
```

And now your PR fixes it like this:
```
[P1 is the IPC leader]
P1 forks P2
P2 spawns new thread T3

P2 forks P4    simulteneously     T3 exits
P2 removes from owned T3
P2 performs `ipc_change_id_owner(4, <child-vmid>)`

P1 never receives "release range 4" with this new PR, and ID 4 is always marked as used
```

Is my understanding correct?

---
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv5pWFDxgy-16HGdnv:-Mkv5pWFDxgy-16HGdnw:bcou17a) ([raw file](https://github.com/gramineproject/gramine/blob/addd1a506d4def71b4755c5fffe51af430b9fb46/LibOS/shim/src/ipc/shim_ipc_pid.c#L207)):*
> ```C
>     if (range->start != start || range->end != end) {
>         BUG();
>     }
> ```

Looks like a remnant from your gdb session? Not blocking though.


<!-- Sent from Reviewable.io -->

2021-10-01 12:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv8O_z5HOc0bjcPn-G:-MkvokCs2VvsvZWr_FRw:bex92ll) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For my own understanding, is this a scenario for the previous bug:
```
[P1 is the IPC leader]
P1 forks P2
P2 spawns new thread T3

P2 forks P4    simulteneously     T3 exits
[P2 now removes from owned P4 and T3, which triggers "release range 3-4" IPC msg]
P1 receives "release range 3-4" and marks these two as unused

P4 starts and performs `ipc_change_id_owner(4, <vmid>)`
P1 receives ipc_change_id_owner(4) and panics -- ID 4 unknown!
```

And now your PR fixes it like this:
```
[P1 is the IPC leader]
P1 forks P2
P2 spawns new thread T3

P2 forks P4    simulteneously     T3 exits
P2 removes from owned T3
P2 performs `ipc_change_id_owner(4, <child-vmid>)`

P1 never receives "release range 4" with this new PR, and ID 4 is always marked as used
```

Is my understanding correct?
</blockquote></details>

Almost. There is a difference between releasing and removing from owned IDs.
`[P2 now removes from owned P4 and T3, which triggers "release range 3-4" IPC msg]` - P4 was only removed from owned, while `T3` was marked as no longer used (hence releasable). This caused the range to be split locally into three ranges: `3-3`, `4-4` and `5-X` The message that went to IPC leader was `release range 3-3`, but the leader only knew about range `3-X`, and due to how range lookups currently work, it found this range and deleted it anyway.
Also note these steps happen under a lock:
```
P2 removes from owned T3
P2 performs `ipc_change_id_owner(4, <child-vmid>)`
```

---
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv5pWFDxgy-16HGdnv:-MkvnXa3-ZLWNIIXnouH:ba9rrn3) ([raw file](https://github.com/gramineproject/gramine/blob/addd1a506d4def71b4755c5fffe51af430b9fb46/LibOS/shim/src/ipc/shim_ipc_pid.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like a remnant from your gdb session? Not blocking though.
</blockquote></details>

I've actually debugged this purely by reading code :)

No, this change is intended. It's just like a release-build assert. I wanted to add this, since the culprit of the original issue was desynchronized state and this was the only place it could be detected (we had an assert, but seems bug reporters ran this in release build).


<!-- Sent from Reviewable.io -->

2021-10-01 12:54 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv8O_z5HOc0bjcPn-G:-Mkvucj2-BNA0AamkZX6:buoi6zg) (no related file):*
> but the leader only knew about range 3-X, and due to how range lookups currently work, it found this range and deleted it anyway.

Oooh! Ok. That's not a bug? Anyway, resolving.

---


<!-- Sent from Reviewable.io -->

2021-10-01 13:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv8O_z5HOc0bjcPn-G:-Mkvx5FD0JNVLnpzlZok:b9oym4d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> but the leader only knew about range 3-X, and due to how range lookups currently work, it found this range and deleted it anyway.

Oooh! Ok. That's not a bug? Anyway, resolving.
</blockquote></details>

What do you mean? There is nothing sensible we can do in case of a desync, so I've opted for a loud `BUG()`.

---


<!-- Sent from Reviewable.io -->

2021-10-01 13:50 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/109#-Mkv8O_z5HOc0bjcPn-G:-Mkw6dqVEccasfWh7tSP:bmkig1w) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean? There is nothing sensible we can do in case of a desync, so I've opted for a loud `BUG()`.
</blockquote></details>

Well, yes, true. Nevermind.

---


<!-- Sent from Reviewable.io -->

2021-10-01 18:29 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/109#-MkwtWXzBZbKIW4ldOGX):*
> ```
> a issues
> ```


<!-- Sent from Reviewable.io -->

2021-10-01 19:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/109#-MkwtWXzBZbKIW4ldOGX):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> a issues
> ```
</blockquote></details>

TODO: at rebase


<!-- Sent from Reviewable.io -->

2021-10-01 21:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/109#-MkwtWXzBZbKIW4ldOGX):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 21:33 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-10-01 21:56 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Direct-Sanitizers please (sendfile09 from LTP timed out, known issue)

2021-10-02 15:55 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/109)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-02 16:48 UTC, merged