[mbedtls] Use `pkg-config --cflags mbedtls_gramine`
gramineproject/gramine pull request #1106
Opened 2023-01-06 13:06 UTC by dimakuv

## Description of the changes 

Previously, Gramine didn't install the header files for the `mbedtls_gramine` package. This required e.g. the `ra-tls-mbedtls` example to download mbedTLS and use its headers. This PR copies the header files such that they can be accessed via pkg-config, and `ra-tls-mbedtls` example uses it now.

This PR is part of solving #1071.

## How to test this PR? 

CI is enough.

2023-01-06 13:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6BbrB4jvs2frqNJYs:-NL6BbrB4jvs2frqNJYt:b7xz77h) (no related file):*
@woju @mkow @kailun-qin Please review this PR.

___


<!-- Sent from Reviewable.io -->

2023-01-06 13:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6Cank3XSmpvrZIXwI:-NL6Cank3XSmpvrZIXwJ:b24d854) ([raw file](https://github.com/gramineproject/gramine/blob/f85c1f6e763b7e71e498d82bc91f4d7f37db36a6/subprojects/packagefiles/mbedtls/meson.build#L67)):*
> ```Meson
> # mbedTLS headers
> install_subdir('mbedtls-mbedtls-3.3.0/include/mbedtls', install_dir: 'include')
> install_subdir('mbedtls-mbedtls-3.3.0/include/psa', install_dir: 'include')
> ```

This results in installing mbedTLS 3.3.0 headers into `$prefix/include`, which on Debian/Ubuntu is `/usr/local/include`.

So this may overwrite already-existing `/usr/local/include/mbedtls/` and `/usr/local/include/psa/` dirs on the user's system. Do we care?

If we care, then I can introduce one additional level of indirection:
- install mbedTLS 3.3.0 headers under `$prefix/include/gramine/`, and
- adjust default `pkg-config` include dirs to be not `$prefix/include` but `$prefix/include/gramine`.


<!-- Sent from Reviewable.io -->

2023-01-09 01:52 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NLJ85d82kAl1tecUXGD):*
them



_Code quote:_
```
it
```
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6Cank3XSmpvrZIXwI:-NLJCTupC5VoC-pbwQDU:b-4ji7s4) ([raw file](https://github.com/gramineproject/gramine/blob/f85c1f6e763b7e71e498d82bc91f4d7f37db36a6/subprojects/packagefiles/mbedtls/meson.build#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This results in installing mbedTLS 3.3.0 headers into `$prefix/include`, which on Debian/Ubuntu is `/usr/local/include`.

So this may overwrite already-existing `/usr/local/include/mbedtls/` and `/usr/local/include/psa/` dirs on the user's system. Do we care?

If we care, then I can introduce one additional level of indirection:
- install mbedTLS 3.3.0 headers under `$prefix/include/gramine/`, and
- adjust default `pkg-config` include dirs to be not `$prefix/include` but `$prefix/include/gramine`.
</blockquote></details>

I'd prefer adding another level of indirection to avoid any overwriting (as it's cleaner and seems to only require small changes).


<!-- Sent from Reviewable.io -->

2023-01-09 09:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NLJ85d82kAl1tecUXGD):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

them
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6Cank3XSmpvrZIXwI:-NLKvmji2deikswEggrp:b-av0iqn) ([raw file](https://github.com/gramineproject/gramine/blob/f85c1f6e763b7e71e498d82bc91f4d7f37db36a6/subprojects/packagefiles/mbedtls/meson.build#L67)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'd prefer adding another level of indirection to avoid any overwriting (as it's cleaner and seems to only require small changes).
</blockquote></details>

Done. Yes, I agree. Also, it's very easy to add.

Now all Gramine-installed headers are found under `$prefix/include/gramine/`, which in the default case resolves to `/usr/local/include/gramine/`.


<!-- Sent from Reviewable.io -->

2023-01-09 10:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6BbrB4jvs2frqNJYs:-NLL2faOC1AY5v62x-Az:b2c0zcb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju @mkow @kailun-qin Please review this PR.
</blockquote></details>

LGTM, thanks!

___


<!-- Sent from Reviewable.io -->

2023-01-09 11:47 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`subprojects/packagefiles/mbedtls/meson.build` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/1106#-NL6Cank3XSmpvrZIXwI:-NLLK6bRDFoceyiXYRn0:besbvlv) ([raw file](https://github.com/gramineproject/gramine/blob/f85c1f6e763b7e71e498d82bc91f4d7f37db36a6/subprojects/packagefiles/mbedtls/meson.build#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Yes, I agree. Also, it's very easy to add.

Now all Gramine-installed headers are found under `$prefix/include/gramine/`, which in the default case resolves to `/usr/local/include/gramine/`.
</blockquote></details>

`install_dir:` needs to be `get_option('includedir') / 'gramine'`, because someone might change `-Dincludedir=`. Otherwise LGTM (I agree `'gramine'` is needed).


<!-- Sent from Reviewable.io -->

2023-01-09 18:23 UTC, woju requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1106#-NLMl2bH6surJh_G-UKH:-NLMl2bH6surJh_G-UKI:b-wd3ccn) (no related file):*
`pkg-deb-debian11` CI job failed, because you install the files in meson, but didn't add them to any of `debian/*.install` (nor `debian/not-installed`). If you want them to be shipped, plz choose appropriate package, or if not, then add `usr/include/gramine` to `not-installed`.

https://manpages.debian.org/bullseye-backports/debhelper/dh_install.1.en.html

___


<!-- Sent from Reviewable.io -->

2023-01-10 10:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1106#-NLMl2bH6surJh_G-UKH:-NLQHDzoBc36dRJ7lO-c:bde03a9) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`pkg-deb-debian11` CI job failed, because you install the files in meson, but didn't add them to any of `debian/*.install` (nor `debian/not-installed`). If you want them to be shipped, plz choose appropriate package, or if not, then add `usr/include/gramine` to `not-installed`.

https://manpages.debian.org/bullseye-backports/debhelper/dh_install.1.en.html
</blockquote></details>

Done, I hope this is good enough.

___


<!-- Sent from Reviewable.io -->

2023-01-10 10:48 UTC, woju approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1106#-NLMl2bH6surJh_G-UKH:-NLQHR2QB80NCoZBNSHv:bmk5ff2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I hope this is good enough.
</blockquote></details>

Yes, this is correct.

___


<!-- Sent from Reviewable.io -->

2023-01-10 11:50 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`writev06` LTP test timed out, known and unrelated)

2023-01-10 12:10 UTC, oshogbo reviewed
LGTM.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106#-:-NLQ_aFhB_GMwWtc7hkv:b-85i63v)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-10 12:20 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-01-11 00:43 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-01-11 11:06 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1106)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-11 13:09 UTC, merged