[LibOS] Use rwlock in libos handle map
gramineproject/gramine pull request #1109
Opened 2023-01-09 00:11 UTC by boryspoplawski

## Description of the changes 
Map of LibOS handles is mainly read, so using rwlocks should give some performance advantage.

## How to test this PR? 
CI.
I couldn't come up with a good and simple test for the locks themselves. Also we have no way of running "unit tests" in LibOS.

2023-01-09 00:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLIrhGN8h8DZr1Pmn_1:bkfuvg4) (no related file):*
This PR requires heavy testing (both correctness and performance wise), I just run LibOS regression.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrmdz0knsxYaxJ8qG:-NLIrmdz0knsxYaxJ8qH:byrqun5) (no related file):*
Somebody should takeover this PR. cc @mkow 

___


<!-- Sent from Reviewable.io -->

2023-01-09 15:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
Sure, plase do

> Otherwise it's unclear why we implemented a rwlock only in the handle-map struct.

We could use it in any other place that it would make sense. Just someone would need to analyze where it could be used
___
*[`libos/include/libos_rwlock.h` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKxe9-6hXp_dBNU57I:-NLM5Aok5YMbKDoJyeJ6:bgc1boi) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`2023`
</blockquote></details>

It was done in 2022
___
*[`libos/include/libos_rwlock.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLMOL5AjcfjYVQRl3i:-NLM5_4U3al0VGfOutqC:b2iw6gn) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L20)):*
> This implementation closely follows the description of 

1. Actually, it doesn't follow it closely.
2. I actually read https://go.dev/src/sync/rwmutex.go more carefully than the linked article
3. The linked code is in Go (completely different language with different memory model) and uses somewhat different primitives (we have PAL API + atomics + libos locks).

> Some important details on the implementation:

The description looks good, albeit I would not use word synchronize here and add another paragraph about actual synchronization on C+CPU level (atomics/synchronizing APIs/barriers).
___
*[`libos/include/libos_rwlock.h` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKaey9EP2N2tW0KM1:-NLM99HB8x-BVPZUOZXY:b-ht4g29) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, I don't get this case. What does the compiler do, that we need to prevent?
</blockquote></details>

Code could be reordered (both compile and CPU runtime) before the ifs and loads above (relaxed loads do not prevent that).
___
*[`libos/include/libos_rwlock.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKOseA2y22xwAh3vn:-NLM7edHBtxPkmWlRvgK:b-hiwdd3) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

IIUC, this read memory barrier is to have a correctly updated `departing_readers` value?
</blockquote></details>

No, it's to make sure are loads (that this lock guards) are done before we release it. Notice that state is modified below with RELAXED order.
___
*[`libos/include/libos_rwlock.h` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLLY4kBEUypNlmgYqG:-NLM8p8408FWwg2twjed:b-ht4g29) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, I don't get how this helps.
</blockquote></details>

Code could be reordered (both compile and CPU runtime) before the ifs and loads above (relaxed loads do not prevent that).
___
*[`libos/src/bookkeep/libos_handle.c` line 665 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLL6wl9BMv7tHa0zqNU:-NLM8GzX7R_17uUjQoRd:bfqo2hq) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/src/bookkeep/libos_handle.c#L665)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a heavy write-lock in this iterator function. So it's not suitable for (probably common) use cases when someone just want to check/dump handles in the map -- it will be an overkill (a reader-lock should be used in that case).

Since this function is used only in this file, I suggest to do two things:
1. Make it static (so there is no temptation in the future to use it as-is for other cases)
2. Rename it to reflect the "heavy write-lock" property -- e.g. `walk_handle_map_writable`. Its counterpart (if ever be needed) will be called e.g. `walk_handle_map_only_readable`.
</blockquote></details>

+1 makes sense


<!-- Sent from Reviewable.io -->

2023-01-09 15:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[`libos/include/libos_rwlock.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLMOL5AjcfjYVQRl3i:-NLM9xX87rm_zECmH4N-:bz1cmzp) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This implementation closely follows the description of 

1. Actually, it doesn't follow it closely.
2. I actually read https://go.dev/src/sync/rwmutex.go more carefully than the linked article
3. The linked code is in Go (completely different language with different memory model) and uses somewhat different primitives (we have PAL API + atomics + libos locks).

> Some important details on the implementation:

The description looks good, albeit I would not use word synchronize here and add another paragraph about actual synchronization on C+CPU level (atomics/synchronizing APIs/barriers).
</blockquote></details>

Sure, your comments make sense.
___
*[`libos/include/libos_rwlock.h` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKaey9EP2N2tW0KM1:-NLMA29i1bArv6Y58Fff:b2ug6h) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Code could be reordered (both compile and CPU runtime) before the ifs and loads above (relaxed loads do not prevent that).
</blockquote></details>

Ah, got it. So this is to prevent the code/data from the critical section (that this read-lock guards) to be read/executed too early (?).
___
*[`libos/include/libos_rwlock.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKOseA2y22xwAh3vn:-NLMB9YyCV9ZQhdFqxeo:b-o9u12c) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it's to make sure are loads (that this lock guards) are done before we release it. Notice that state is modified below with RELAXED order.
</blockquote></details>

Got it. So this is to prevent the code/data from the critical section (that this read-lock guards) from being read/executed too late.


<!-- Sent from Reviewable.io -->

2023-01-09 15:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`libos/include/libos_rwlock.h` line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKaey9EP2N2tW0KM1:-NLMEOjhEANw9Tl08LUr:b-vqh12x) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, got it. So this is to prevent the code/data from the critical section (that this read-lock guards) to be read/executed too early (?).
</blockquote></details>

Yes. There are multiple different ways we could do this, I believe this is the most lightweight option.
___
*[`libos/include/libos_rwlock.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLKOseA2y22xwAh3vn:-NLMEkGN1lQo4qYoHiJm:b2nih0v) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Got it. So this is to prevent the code/data from the critical section (that this read-lock guards) from being read/executed too late.
</blockquote></details>

yup


<!-- Sent from Reviewable.io -->

2023-01-13 18:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLgMOVi28Z6hvZIwqSo:b-pbqgze) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FWIW: I just tested it quickly with Memcached (local deployment of both server and client, both are with `--threads 4` on an 8-core machine, the exact details of the client workload are not interesting). I saw an improvement of ~3-4%. So yes, this helps a bit.
</blockquote></details>

That's not a lot, I expected much more...

___


<!-- Sent from Reviewable.io -->

2023-01-16 00:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLrqrcY0qreIi-1bEr6:b17pd3b) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That's not a lot, I expected much more...
</blockquote></details>

@dimakuv: How did you get these numbers? On ICX we see 29% on `gramine-direct` and 24% on `gramine-sgx` more requests/data being processed than on Gramine without this PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrmdz0knsxYaxJ8qG:-NLruHj91pFWSWB0m7_p:bayvbb3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Somebody should takeover this PR. cc @mkow 
</blockquote></details>

ACK, I can take it over.

___


<!-- Sent from Reviewable.io -->

2023-01-16 08:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLtk7PL1VpeVTM4fxA8:b-3xj26o) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: How did you get these numbers? On ICX we see 29% on `gramine-direct` and 24% on `gramine-sgx` more requests/data being processed than on Gramine without this PR.
</blockquote></details>

@mkow I used a rather weak ICX with 8 cores, but 64GB of EPC.

I think the difference in perf improvement that we see is due to me using only 4 cores for Memcached server (I can't use more because the other 4 cores I use for the client-benchmark). Surely the effect of this PR gets more pronounced with more cores. Unfortunately I didn't have a big machine to test with more cores yesterday. (And I wanted to do a sanity test for this PR -- I did `perf` analysis.)

___


<!-- Sent from Reviewable.io -->

2023-01-16 11:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLuFOzNEeVyXtagnB1D:b9p7zqu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I used a rather weak ICX with 8 cores, but 64GB of EPC.

I think the difference in perf improvement that we see is due to me using only 4 cores for Memcached server (I can't use more because the other 4 cores I use for the client-benchmark). Surely the effect of this PR gets more pronounced with more cores. Unfortunately I didn't have a big machine to test with more cores yesterday. (And I wanted to do a sanity test for this PR -- I did `perf` analysis.)
</blockquote></details>

Ok, we tested it on a 128-thread CPU, so this may be the difference, although we used only 16 threads for the server and 32 for the benchmark.
Was the original issue seen on a big or small CPU?

___


<!-- Sent from Reviewable.io -->

2023-01-16 12:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLuUx-dCltiNRjMvHKy:b-8o8kp6) (no related file):*
> Ok, we tested it on a 128-thread CPU, so this may be the difference, although we used only 16 threads for the server and 32 for the benchmark.

Pretty sure that is the difference.

> Was the original issue seen on a big or small CPU?

On a big CPU.

___


<!-- Sent from Reviewable.io -->

2023-01-16 22:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NLwePFY5cCt7QS9LS7d:b-3vwvr7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Ok, we tested it on a 128-thread CPU, so this may be the difference, although we used only 16 threads for the server and 32 for the benchmark.

Pretty sure that is the difference.

> Was the original issue seen on a big or small CPU?

On a big CPU.
</blockquote></details>

Then this PR solves a significant part of the issue, it seems. Although we probably could also hunt down the rest of the overhead, as it's exposed also without SGX.
But we still need someone to verify the correctness of this implementation, I'll try to find someone for this at ITL.

___


<!-- Sent from Reviewable.io -->

2023-01-16 22:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/include/libos_rwlock.h` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLwfukn0Dpn9qaBArly:-NLwfukn0Dpn9qaBArlz:b-xwl3wz) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L10)):*
> ```objc
>  * Inspired by https://eli.thegreenplace.net/2019/implementing-reader-writer-locks/.
>  */
> ```

Why a header-library instead of a normal header+object? These functions aren't trivial, not sure if we want them copied all over the place?


<!-- Sent from Reviewable.io -->

2023-01-16 22:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrmdz0knsxYaxJ8qG:-NLwhPq96CqQr5-duuYp:b2nhysk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ACK, I can take it over.
</blockquote></details>

ack

___
___
*[`libos/include/libos_rwlock.h` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLwfukn0Dpn9qaBArly:-NLwgon8-bGPhDJAe45s:b-alhlih) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why a header-library instead of a normal header+object? These functions aren't trivial, not sure if we want them copied all over the place?
</blockquote></details>

I was thinking about it, but started with just a header and had no time to finish the PR properly and just submitted what I got.

I think the proper split could be .h + .c, with `rwlock_read_lock` fast path in the header and cold path in .c (same for unlock). The fast path is literally just an atomic add, so its worth always being inlined


<!-- Sent from Reviewable.io -->

2023-01-16 23:14 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/include/libos_rwlock.h` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLwfukn0Dpn9qaBArly:-NLwqzPxD0lpUnHPiak0:b-mosdjx) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I was thinking about it, but started with just a header and had no time to finish the PR properly and just submitted what I got.

I think the proper split could be .h + .c, with `rwlock_read_lock` fast path in the header and cold path in .c (same for unlock). The fast path is literally just an atomic add, so its worth always being inlined
</blockquote></details>

Sounds good. I can do it after we review the correctness.


<!-- Sent from Reviewable.io -->

2023-01-18 02:09 UTC, DemiMarie-reviewable reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, plase do

> Otherwise it's unclear why we implemented a rwlock only in the handle-map struct.

We could use it in any other place that it would make sense. Just someone would need to analyze where it could be used
</blockquote></details>

Design questions:

1. Have you considered using RCU instead?
2. Could you use the application-layer futex code to implement an rwlock using e.g. Rust’s libstd rwlock?
___
*[`libos/include/libos_rwlock.h` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxp5iq4Jip34hXbbCL:-NLxp5iq4Jip34hXbbCM:b-b8c8h8) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L61)):*
> ```objc
>         return false;
>     }
>     return true;
> ```

This would be cleaner with less redundant error handling, perhaps using `goto`.  In any case this code is very obviously correct.



_Code quote:_
```objc
static inline bool create_rwlock(struct libos_rwlock* l) {
    l->state = 0;
    l->departing_readers = 0;
    if (PalEventCreate(&l->readers_wait, /*init_signaled=*/false, /*auto_clear=*/false) < 0) {
        return false;
    }
    if (PalEventCreate(&l->writer_wait, /*init_signaled=*/false, /*auto_clear=*/true) < 0) {
        PalObjectClose(l->readers_wait);
        return false;
    }
    l->readers_waiting = 0;
    if (!create_lock(&l->writers_lock)) {
        PalObjectClose(l->readers_wait);
        PalObjectClose(l->writer_wait);
        return false;
    }
    return true;
```
___
*[`libos/include/libos_rwlock.h` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0mKcQDW3ygi8IxOd6:-NM0mKcQDW3ygi8IxOd7:btm2xb8) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L75)):*
> ```objc
> 
> static inline void rwlock_read_lock(struct libos_rwlock* l) {
>     int64_t state = __atomic_fetch_add(&l->state, 1, __ATOMIC_ACQUIRE);
> ```

This seems wrong.  There is nothing preventing `state` from being bumped too many times
___
*[`libos/include/libos_rwlock.h` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0m-Yk0xyQHowjga6h:-NM0m-Yk0xyQHowjga6i:bcx8iyz) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L77)):*
> ```objc
>     int64_t state = __atomic_fetch_add(&l->state, 1, __ATOMIC_ACQUIRE);
>     if (state < 0) {
>         while (PalEventWait(l->readers_wait, /*timeout=*/NULL) < 0)
> ```

Does `PalEventWait` protect against spurious wakeups?
___
*[`libos/include/libos_rwlock.h` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxpYyr7xwo40vjrkvQ:-NLxpYyr7xwo40vjrkvR:bxe7m19) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L79)):*
> ```objc
>         while (PalEventWait(l->readers_wait, /*timeout=*/NULL) < 0)
>             /* nop */;
>         size_t readers_waiting = __atomic_sub_fetch(&l->readers_waiting, 1, __ATOMIC_RELAXED);
> ```

Is there a reason for using `__atomic_*` instead of C11 atomics?  Also, does `__ATOMIC_RELAXED` provide a noticeable benefit over `__ATOMIC_SEQ_CST` here?
___
*[`libos/include/libos_rwlock.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0l-Zv02WUWUWIBs3d:-NM0l-Zv02WUWUWIBs3e:bfpfufw) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L82)):*
> ```objc
>         if (readers_waiting == 0) {
>              PalEventSet(l->writer_wait);
>         }
> ```

I am confused by this code.  Why is `writer_wait` being set?



_Suggestion:_
```objc
        if (readers_waiting == 0) {
            /* This was the last reader.  Wake up the writer. */
            PalEventSet(l->writer_wait);
        }
```
___
*[`libos/include/libos_rwlock.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0le0r7SNM_ZsHL37W:-NM0le0r7SNM_ZsHL37X:bw8q8o0) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L84)):*
> ```objc
>         }
>         /* This prevents code hoisting. */
>         (void)__atomic_load_n(&l->state, __ATOMIC_ACQUIRE);
> ```

What does this synchronize against?
___
*[`libos/include/libos_rwlock.h` line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM135md8al9dJgoUAAr:-NM135md8al9dJgoUAAs:bmhoywb) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L117)):*
> ```objc
> 
> static inline void rwlock_write_unlock(struct libos_rwlock* l) {
>     int64_t state = __atomic_add_fetch(&l->state, WRITER_WEIGHT, __ATOMIC_RELEASE);
> ```

Any reader executing after this point will not enter the critical 
___
*[`libos/include/libos_rwlock.h` line 121 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM12ZA6E1mhWLV5ssLf:-NM12ZA6E1mhWLV5ssLg:b-6cp1q5) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L121)):*
> ```objc
> 
>     if (state) {
>         __atomic_store_n(&l->readers_waiting, state, __ATOMIC_RELAXED);
> ```

Worth noting that in this code, all writers will be blocked on `writers_lock`.  However, it is theoretically possible for `l->state` to overflow.  



_Code quote:_
```objc
    int64_t state = __atomic_add_fetch(&l->state, WRITER_WEIGHT, __ATOMIC_RELEASE);
    assert(state >= 0);

    if (state) {
        __atomic_store_n(&l->readers_waiting, state, __ATOMIC_RELAXED);
```


<!-- Sent from Reviewable.io -->

2023-01-23 00:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @DemiMarie-reviewable, @dimakuv, and @mkow)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Design questions:

1. Have you considered using RCU instead?
2. Could you use the application-layer futex code to implement an rwlock using e.g. Rust’s libstd rwlock?
</blockquote></details>

1. And how do you do RCU in ring3 with no trusted kernel? I'm not aware of any such way (so no, I did not consider it)
2. I don't understand this question, please elaborate. What is "application-layer futex code"?
___
*[`libos/include/libos_rwlock.h` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxp5iq4Jip34hXbbCL:-NMQyJyT2BIPQ1s8zz_P:b2cfw93) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L61)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

This would be cleaner with less redundant error handling, perhaps using `goto`.  In any case this code is very obviously correct.
</blockquote></details>

Like:
```
out_err_close_readers_wait:
        PalObjectClose(l->readers_wait);
out_err_close_writer_wait:
        PalObjectClose(l->writer_wait);
out_err:
        return false;
```
?
TBH I dislike both versions (including the current one)
___
*[`libos/include/libos_rwlock.h` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0mKcQDW3ygi8IxOd6:-NMQyfJQ4_IOd-_Ps6hL:b4jf8cl) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L75)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

This seems wrong.  There is nothing preventing `state` from being bumped too many times
</blockquote></details>

What is too many times? Overflowing int64? I guess the limit is the possible number of threads which should be enough™ 
___
*[`libos/include/libos_rwlock.h` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0m-Yk0xyQHowjga6h:-NMQz2xzAW72-6Zhp1FT:b-a1ourn) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L77)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Does `PalEventWait` protect against spurious wakeups?
</blockquote></details>

No, but we have a `while ()` here?
___
*[`libos/include/libos_rwlock.h` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxpYyr7xwo40vjrkvQ:-NMQzO9u0VnTtpfdiT_u:b-6vywpt) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L79)):*
We had discussions about C11 atomics many times, and decided not to swap to them.

> Also, does __ATOMIC_RELAXED provide a noticeable benefit over __ATOMIC_SEQ_CST here?

Yes. `__ATOMIC_SEQ_CST`  entails a full memory barrier.
___
*[`libos/include/libos_rwlock.h` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NMR-xGl7PG-zcD9g-SB:-NMR-xGl7PG-zcD9g-SC:b22hkbi) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L81)):*
> ```objc
>         size_t readers_waiting = __atomic_sub_fetch(&l->readers_waiting, 1, __ATOMIC_RELAXED);
>         if (readers_waiting == 0) {
>              PalEventSet(l->writer_wait);
> ```

TODO: one space too much
___
*[`libos/include/libos_rwlock.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0l-Zv02WUWUWIBs3d:-NMR-Fsc9UYnNBA30NOc:bvoopjx) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L82)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

I am confused by this code.  Why is `writer_wait` being set?
</blockquote></details>

To wake up the writer, which is waiting for the confirmation to clear `readers_wait` event. See `rwlock_write_unlock`.
This quirk is basically because of limitations of primitives we have (atomics + PAL API events + normal locks)
___
*[`libos/include/libos_rwlock.h` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0le0r7SNM_ZsHL37W:-NMR-don5olJnXdsm3C3:b1zgvq2) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L84)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

What does this synchronize against?
</blockquote></details>

Same thing as first line in this function.
___
*[`libos/include/libos_rwlock.h` line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM135md8al9dJgoUAAr:-NMQzlo05vPH3nGSxODh:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L117)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Any reader executing after this point will not enter the critical 
</blockquote></details>

?
___
*[`libos/include/libos_rwlock.h` line 121 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM12ZA6E1mhWLV5ssLf:-NMQzu1b4eapXEyIosFF:bapzran) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L121)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Worth noting that in this code, all writers will be blocked on `writers_lock`.  However, it is theoretically possible for `l->state` to overflow.  
</blockquote></details>

If we have 2**63 threads we have more problems, I guess...


<!-- Sent from Reviewable.io -->

2023-01-23 20:27 UTC, DemiMarie-reviewable reviewed
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NMGZOJ4529YTx6aB_fA:b-gxb44a) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then this PR solves a significant part of the issue, it seems. Although we probably could also hunt down the rest of the overhead, as it's exposed also without SGX.
But we still need someone to verify the correctness of this implementation, I'll try to find someone for this at ITL.
</blockquote></details>

I made a model at https://github.com/DemiMarie/rwlock-loom-model

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. And how do you do RCU in ring3 with no trusted kernel? I'm not aware of any such way (so no, I did not consider it)
2. I don't understand this question, please elaborate. What is "application-layer futex code"?
</blockquote></details>

1. RCU is already implemented by liburcu.  I believe that the lack of a trusted kernel can be worked around with memory barriers.
2. Gramine already implements futexes, and I was wondering if it could use those futexes internally.
___
*[`libos/include/libos_rwlock.h` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxp5iq4Jip34hXbbCL:-NMV9Gc8C-HFYbvGSfWf:b-i2i1) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Like:
```
out_err_close_readers_wait:
        PalObjectClose(l->readers_wait);
out_err_close_writer_wait:
        PalObjectClose(l->writer_wait);
out_err:
        return false;
```
?
TBH I dislike both versions (including the current one)
</blockquote></details>

Probably?
___
*[`libos/include/libos_rwlock.h` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0mKcQDW3ygi8IxOd6:-NMV9OG_0b2YKbYDxwgu:b9wvi6) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is too many times? Overflowing int64? I guess the limit is the possible number of threads which should be enough™ 
</blockquote></details>

Overflowing `WRITER_WEIGHT`, but that can only happen if there are a huge number of threads or if a thread fails to unlock an rwlock before terminating.
___
*[`libos/include/libos_rwlock.h` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0m-Yk0xyQHowjga6h:-NMV9bkcEi9ZmV2tbk8j:b-wnj2mo) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, but we have a `while ()` here?
</blockquote></details>

Will a spurious wakeup always return a negative number?
___
*[`libos/include/libos_rwlock.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0l-Zv02WUWUWIBs3d:-NMV9llVClMYHKYEkI0T:b-rb172m) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To wake up the writer, which is waiting for the confirmation to clear `readers_wait` event. See `rwlock_write_unlock`.
This quirk is basically because of limitations of primitives we have (atomics + PAL API events + normal locks)
</blockquote></details>

Why is it necessary for the writer to wait for confirmation, instead of the reader clearing the event here?
___
*[`libos/include/libos_rwlock.h` line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM135md8al9dJgoUAAr:-NMVALwLDQt-WlBVMdua:b2leaft) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Nevermind
___
*[`libos/include/libos_rwlock.h` line 121 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM12ZA6E1mhWLV5ssLf:-NMVA6SQ66IGes_m3nKW:biw2wt9) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If we have 2**63 threads we have more problems, I guess...
</blockquote></details>

Yeah, or if someone acquires the rwlock 2**60 times without unlocking it.


<!-- Sent from Reviewable.io -->

2023-01-23 21:44 UTC, DemiMarie-reviewable reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NMV_m_-6hjJYOMFsa4W:-NMV_m_01KJufZoyfG54:bivf63f) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L89)):*
> ```objc
> 
> static inline void rwlock_read_unlock(struct libos_rwlock* l) {
>     RMB();
> ```

What is this memory barrier for?


<!-- Sent from Reviewable.io -->

2023-02-12 22:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @DemiMarie-reviewable, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NMQwrXg6fJ2ab0RbDEp:b-n81te9) (no related file):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

I made a model at https://github.com/DemiMarie/rwlock-loom-model
</blockquote></details>

So I assume it did not find any issues?

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

1. RCU is already implemented by liburcu.  I believe that the lack of a trusted kernel can be worked around with memory barriers.
2. Gramine already implements futexes, and I was wondering if it could use those futexes internally.
</blockquote></details>

1. And I'm pretty sure liburcu requires trusted kernel. I don't see how memory barriers help here.
2. No, that's not possible
___
*[`libos/include/libos_rwlock.h` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0mKcQDW3ygi8IxOd6:-NO6k7UACIsNlICOKZDk:bvtnwi0) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L75)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Overflowing `WRITER_WEIGHT`, but that can only happen if there are a huge number of threads or if a thread fails to unlock an rwlock before terminating.
</blockquote></details>

Overflowing `WRITER_WEIGHT` is not a problem.
___
*[`libos/include/libos_rwlock.h` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0m-Yk0xyQHowjga6h:-NO6kCAIBy4_cZKZnwnL:ben9hsj) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L77)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Will a spurious wakeup always return a negative number?
</blockquote></details>

Yes. it returns `0` only if the event was actually triggered.
___
*[`libos/include/libos_rwlock.h` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM0l-Zv02WUWUWIBs3d:-NO6khdv0a0hxT34cI7p:b-e539p5) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L82)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Why is it necessary for the writer to wait for confirmation, instead of the reader clearing the event here?
</blockquote></details>

Because there are many readers. Also we must make sure that the next writer won't start executing before we clean up the state
___
*[`libos/include/libos_rwlock.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NMV_m_-6hjJYOMFsa4W:-NO6lUfY9_RxYmFLKEwe:bocasfo) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L89)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

What is this memory barrier for?
</blockquote></details>

See the closed thread above.
___
*[`libos/include/libos_rwlock.h` line 121 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NM12ZA6E1mhWLV5ssLf:-NO6letz1NmalcAOybrW:bf45dhh) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L121)):*
<details><summary><i>Previously, DemiMarie-reviewable wrote…</i></summary><blockquote>

Yeah, or if someone acquires the rwlock 2**60 times without unlocking it.
</blockquote></details>

1. These locks are not recursive.
2. They are only used by Gramine internally, so someone==we.


<!-- Sent from Reviewable.io -->

2023-02-13 01:06 UTC, DemiMarie-reviewable reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLIrhGN8h8DZr1Pmn_0:-NO73rJT7nM1Ke3Izuqs:bvyxy4r) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So I assume it did not find any issues?
</blockquote></details>

None that I could tell, but see https://github.com/tokio-rs/loom/issues/301.

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. And I'm pretty sure liburcu requires trusted kernel. I don't see how memory barriers help here.
2. No, that's not possible
</blockquote></details>

`liburcu-signal` and `liburcu` both require kernel support (POSIX signals and `sys_membarrier()` respectiely), but `liburcu-mb` does not as far as I can tell.  I don’t see how the kernel being trusted or not matters here.
___
*[`libos/include/libos_rwlock.h` line 79 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLxpYyr7xwo40vjrkvQ:-NO7IJ3xBR8JOqfjJkVU:b-scpbrt) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L79)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We had discussions about C11 atomics many times, and decided not to swap to them.

> Also, does __ATOMIC_RELAXED provide a noticeable benefit over __ATOMIC_SEQ_CST here?

Yes. `__ATOMIC_SEQ_CST`  entails a full memory barrier.
</blockquote></details>

Fair.  The reason I mentioned `__ATOMIC_SEQ_CST` is that formal verification of relaxed atomics is still a research-level problem, whereas formal verification of sequentially-consistent atomics is much simpler.  seKVM (now pKVM?) uses sequentially-consistent atomics exclusively for that reason.


<!-- Sent from Reviewable.io -->

2023-02-28 07:53 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NPLxPyT-vDJgbSaa0l4:-NPLxPyT-vDJgbSaa0l5:bacxvxz) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L7)):*
> ```objc
> 
> /*
>  * Readers-writer lock implemenation.
> ```

implementation



_Code quote:_
```objc
implemenation
```
___
*[`libos/include/libos_rwlock.h` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NPM-C9k7dV6btuYtsVo:-NPM-C9k7dV6btuYtsVp:bd5fsr2) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L43)):*
> ```objc
> /* This number must be greater than the maximal number of readers or writer starvation might
>  * happen. */
> #define WRITER_WEIGHT (1ul << 60)
> ```

Any special consideration on why we pick this value?


<!-- Sent from Reviewable.io -->

2023-02-28 12:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NPM-C9k7dV6btuYtsVo:-NPMxHO6E26O3GEZdmDx:bqf8tga) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L43)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Any special consideration on why we pick this value?
</blockquote></details>

Nothing except the comment above and that it must fit in `int64_t` when negated


<!-- Sent from Reviewable.io -->

2023-03-16 02:51 UTC, mkow reviewed
FYI: I'm taking over this PR, with Borys' approval. I rebased it (as it got a bit rusty) and will fix the outstanding issues next.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109#-:-NQcFYAb3-RQ3uYzFRjI:b-9w78o)* status: 3 of 7 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @DemiMarie-reviewable, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwQhM1ADxJx1JcOip):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add
```
[LibOS] Add readers-writer lock (rwlock) implementation
```
</blockquote></details>

Isn't this obvious, if you know what rwlock roughly is? Sounds like saying the same thing twice in a commit message one-liner, which should be concise.
But I can add it if you think it really helps.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwx-tC-FrI_aj5vPA):*
> Maybe we should a commit body that says something like [...]

Done.

@DemiMarie-reviewable: To be honest, I don't see how this could possibly work effectively in usermode. The main idea of RCU is that readers don't need any locks and thus are super-fast. And in usermode I think it's impossible to remove all the locks from the read section, because it's preemptible, so you have no way of waiting for the reader to exit it other than normal locks?


<!-- Sent from Reviewable.io -->

2023-03-16 08:40 UTC, dimakuv reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @kailun-qin)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLKwQhM1ADxJx1JcOip):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this obvious, if you know what rwlock roughly is? Sounds like saying the same thing twice in a commit message one-liner, which should be concise.
But I can add it if you think it really helps.
</blockquote></details>

I don't insist.


<!-- Sent from Reviewable.io -->

2023-03-19 04:24 UTC, boryspoplawski reviewed
I can finish this PR, but if @mkow takes over, he has my blessing ;)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109#-:-NQs5vgU0yPra-tFzF2d:b-dp98iv)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-04-02 16:46 UTC, mkow reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NRencCl7pNFXs4IzzIA:bkgwsm4) (no related file):*
@boryspoplawski: Do you have any draft of a unit test (+ a stress test probably) for these RW locks? IMO we should add it, I can implement it if you don't have anything.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NS1ocX37HViTQTmcObL:-NS1ocX37HViTQTmcObM:b-dbvwir) (no related file):*
Posting perf benchmarking results on @dimakuv's request for this PR:

Workload: memcached
Benchmark: memtier
HW: ICX (Xeon Platinum 8352Y, 64x2 threads), 128 GB RAM, 128 GB EPC
System: upstream SGX driver, Linux 5.15
commits: `master` (`634d0392c3acec724dad5a6af8e6305f166eca57`) vs this PR (`46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf`)
Request size on X, memcached threads on Y, each cell is difference in operations/s (higher = better).

`gramine-direct`:

![heatmap\_ICX\_30s\_direct\_master\_vs\_rwlock.png](https://files.reviewableusercontent.io/images/reviewable/5244565/eECZw8LIeUhxcQACWT4PHFye/heatmap_ICX_30s_direct_master_vs_rwlock.png)

`gramine-sgx`:

![heatmap\_ICX\_30s\_sgx\_master\_vs\_rwlock.png](https://files.reviewableusercontent.io/images/reviewable/5244565/ZZL60o83R_oIgiTDS5LWHqi2/heatmap_ICX_30s_sgx_master_vs_rwlock.png)

___


<!-- Sent from Reviewable.io -->

2023-04-02 21:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NS2xxTi3PKiebrTIYrk:bx9uo4v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Do you have any draft of a unit test (+ a stress test probably) for these RW locks? IMO we should add it, I can implement it if you don't have anything.
</blockquote></details>

No I do not

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NS1ocX37HViTQTmcObL:-NS2y0FuEZEuzzBFsfgZ:b-low3n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Posting perf benchmarking results on @dimakuv's request for this PR:

Workload: memcached
Benchmark: memtier
HW: ICX (Xeon Platinum 8352Y, 64x2 threads), 128 GB RAM, 128 GB EPC
System: upstream SGX driver, Linux 5.15
commits: `master` (`634d0392c3acec724dad5a6af8e6305f166eca57`) vs this PR (`46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf`)
Request size on X, memcached threads on Y, each cell is difference in operations/s (higher = better).

`gramine-direct`:

![heatmap\_ICX\_30s\_direct\_master\_vs\_rwlock.png](https://files.reviewableusercontent.io/images/reviewable/5244565/eECZw8LIeUhxcQACWT4PHFye/heatmap_ICX_30s_direct_master_vs_rwlock.png)

`gramine-sgx`:

![heatmap\_ICX\_30s\_sgx\_master\_vs\_rwlock.png](https://files.reviewableusercontent.io/images/reviewable/5244565/ZZL60o83R_oIgiTDS5LWHqi2/heatmap_ICX_30s_sgx_master_vs_rwlock.png)

</blockquote></details>

Cool!
Any idea what are these random -15% on direct?
Also how many times you ran each test? For how long?

___


<!-- Sent from Reviewable.io -->

2023-04-03 00:29 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NS1ocX37HViTQTmcObL:-NS3UX6b7s21dDQRAK97:b-4q20uu) (no related file):*
>  Any idea what are these random -15% on direct?

No idea, probably some random noise, but I don't have any good theory.

>  Also how many times you ran each test? For how long?

I ran each test only once, but for 30 seconds, with which generating this table already took a few hours. But modulo such isolated flukes it should be rather meaningful, because I randomized the experiments order. So, if there was some external noise, then it should get quite evenly spread throughout the table.

___


<!-- Sent from Reviewable.io -->

2023-04-11 01:06 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NSfdUjb4ZFljOt61_L7:bdllea7) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No I do not
</blockquote></details>

Note to myself: we can use https://github.com/eliben/code-for-blog/blob/master/2019/rwlocks/rwlock_test.go as inspiration to how  to test this.

___
___
*[`libos/include/libos_rwlock.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLMOL5AjcfjYVQRl3i:-NSfcZxd94s6ffpjTGNG:bqlggzu) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L20)):*
> The writer puts the number of currently-active readers into `departing_readers`

This is slightly misleading, it doesn't put the _current_ number of readers, but the number of readers at the time of the previous atomic addition. Ditto for other points in that description.
___
*[`libos/include/libos_rwlock.h` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSggT0hCtZrbkIp3-QV:-NSggT0hCtZrbkIp3-QW:b-m44z48) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L36)):*
> ```objc
>     PAL_HANDLE readers_wait;
>     /* Number of readers waiting on `readers_wait` after writer releases the lock. */
>     size_t readers_waiting;
> ```

The other variable is named `departing_readers`, I'd unify the convention (whichever way).



_Code quote:_
```objc
size_t readers_waiting
```
___
*[`libos/include/libos_rwlock.h` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSfeC1n5D6QIunlH_Fv:-NSfeC1n5D6QIunlH_Fw:b-yc8jnz) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L45)):*
> ```objc
> #define WRITER_WEIGHT (1ul << 60)
> 
> static inline bool create_rwlock(struct libos_rwlock* l) {
> ```

Not `rwlock_create`? Would be more consistent with the other calls. Same for `destroy_rwlock`.



_Code quote:_
```objc
create_rwlock
```
___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NShjBA9AkClyeosDiBE:b-p2pee2) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
> ```objc
>              PalEventSet(l->writer_wait);
>         }
>         /* This prevents code hoisting. */
> ```

You mean reordering? "code hoisting" is something slightly different? Why not just say that this is a memory barrier for a single variable?



_Code quote:_
```objc
/* This prevents code hoisting. */
```
___
*[`libos/include/libos_rwlock.h` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShm_-2EJXVzmhZ0-_g:-NShm_-2EJXVzmhZ0-_h:b-bhilri) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L85)):*
> ```objc
>         /* This prevents code hoisting. */
>         (void)__atomic_load_n(&l->state, __ATOMIC_ACQUIRE);
>     }
> ```

Maybe I'm misunderstanding the C11/GCC memory ordering modes, but I think there's a bug here: we're missing a memory read barrier.

Example of a race scenario:

start: `shared_struct = A`
thread1 code:
```
    write_lock()
    shared_struct = B
    write_unlock()
```
thread2 code:
```
    read_lock()
    x = shared_struct
    read_unlock()
```
race:
```
--- thread 1 ---   |   --- thread 2 ---
write_lock()
                     enters read_lock()
                     read from l->state stalls
shared_struct = B    CPU reorders code and executes x = shared_struct first
write_unlock()
                     read from l->state finishes with lock taken successfully, so the transient execution of "x = shared_struct" can be committed
```

In this scenario `shared_struct = B` races with `x = shared_struct`. If that's impossible, then what prevents it? Am I missing something?


<!-- Sent from Reviewable.io -->

2023-04-11 15:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NSkqii87zx0S-5JE7YV:b7q177b) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You mean reordering? "code hoisting" is something slightly different? Why not just say that this is a memory barrier for a single variable?
</blockquote></details>

Isn't "code hoisting" reordering in one specific direction? This prevents any code following it from being reordered to before it (both compile and run time). It also synchronizes on that variable, but I assumed it's obvious (since we use atomics).
___
*[`libos/include/libos_rwlock.h` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShm_-2EJXVzmhZ0-_g:-NSks2vE9LewcULm6Y5K:b-y5gyps) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe I'm misunderstanding the C11/GCC memory ordering modes, but I think there's a bug here: we're missing a memory read barrier.

Example of a race scenario:

start: `shared_struct = A`
thread1 code:
```
    write_lock()
    shared_struct = B
    write_unlock()
```
thread2 code:
```
    read_lock()
    x = shared_struct
    read_unlock()
```
race:
```
--- thread 1 ---   |   --- thread 2 ---
write_lock()
                     enters read_lock()
                     read from l->state stalls
shared_struct = B    CPU reorders code and executes x = shared_struct first
write_unlock()
                     read from l->state finishes with lock taken successfully, so the transient execution of "x = shared_struct" can be committed
```

In this scenario `shared_struct = B` races with `x = shared_struct`. If that's impossible, then what prevents it? Am I missing something?
</blockquote></details>

ACQUIRE load (on l->state) prevents it, as reordering code before it is not possible.
Thread 2 synchronizes in read_lock (on acquire load) with thread 1 on write_unlock (release store), so it must see all of the thread 1 critical section (all writes happening before release store).


<!-- Sent from Reviewable.io -->

2023-04-13 02:11 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NSsMMxXCwzzXtUHnOf7:b4c44ry) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
Ok, I read more and now I think it's correct. This release-acquire model is a bit confusing and not all descriptions in the documentation seem to match each other. E.g. from GCC docs:

> The acquire/release mode is similar to the sequentially consistent mode, except it only applies a happens-before relationship to **dependent** variables

So, this sounds like it doesn't have to order all accesses around it, only "dependent" ones, whatever it means. But cppreference.com says that all accesses are fenced, and I think this is the real definition?
___
*[`libos/include/libos_rwlock.h` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShm_-2EJXVzmhZ0-_g:-NSsMQVL5OvQnSon3W9b:b4c44ry) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L85)):*
Ok, I read more and now I think it's correct. This release-acquire model is a bit confusing and not all descriptions in the documentation seem to match each other. E.g. from GCC docs:

> The acquire/release mode is similar to the sequentially consistent mode, except it only applies a happens-before relationship to **dependent** variables

So, this sounds like it doesn't have to order all accesses around it, only "dependent" ones, whatever it means. But cppreference.com says that all accesses are fenced, and I think this is the real definition?


<!-- Sent from Reviewable.io -->

2023-04-25 22:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 5 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @DemiMarie-reviewable, @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NPLxPyT-vDJgbSaa0l4:-NTuP3jK2RI5UNuL66WU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L7)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

implementation
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLwfukn0Dpn9qaBArly:-NTuRYCx2zEFLONfrqmp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds good. I can do it after we review the correctness.
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NMR-xGl7PG-zcD9g-SB:-NTuV9grEbZAFKGEZZep:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: one space too much
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 92 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLM0zdExWLWwPm-b2n:-NTuXdGx9VglmWQfcICA:b44l4tw) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess we could add `assert(departing >= 0)` here, to be uniform with the function below.
</blockquote></details>

But that's not a correct assert. `departing` can be negative if reader leaves between the 2 atomic operations in `rwlock_write_lock`.
___
*[`libos/include/libos_rwlock.h` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSggT0hCtZrbkIp3-QV:-NTuTpxO5XD7g1tVlFD9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The other variable is named `departing_readers`, I'd unify the convention (whichever way).
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSfeC1n5D6QIunlH_Fv:-NTuU-HlEaSPoSWveNra:b-76ia7t) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `rwlock_create`? Would be more consistent with the other calls. Same for `destroy_rwlock`.
</blockquote></details>

I wanted to be consistent with normal locks, which use `create_lock`, but I guess I can change it
___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NTuVONs0BvxUCaTV5gL:b7luaq5) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I read more and now I think it's correct. This release-acquire model is a bit confusing and not all descriptions in the documentation seem to match each other. E.g. from GCC docs:

> The acquire/release mode is similar to the sequentially consistent mode, except it only applies a happens-before relationship to **dependent** variables

So, this sounds like it doesn't have to order all accesses around it, only "dependent" ones, whatever it means. But cppreference.com says that all accesses are fenced, and I think this is the real definition?
</blockquote></details>

I think it starts to matter when you have a third thread. In sequentially consistent model (if all threads do atomic accesses with SEQ_CST) all 3 threads synchronize on them (and all previous read/writes are done/visible), whereas in acquire/release, two threads can see different orderings, if they do not synchronize.
https://gcc.gnu.org/wiki/Atomic/GCCMM/AtomicSync this has a nice example with 4 threads.
___
*[`libos/include/libos_rwlock.h` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShm_-2EJXVzmhZ0-_g:-NTuX8Lp-SC6mXM6p4A6:b-z7ca7g) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I read more and now I think it's correct. This release-acquire model is a bit confusing and not all descriptions in the documentation seem to match each other. E.g. from GCC docs:

> The acquire/release mode is similar to the sequentially consistent mode, except it only applies a happens-before relationship to **dependent** variables

So, this sounds like it doesn't have to order all accesses around it, only "dependent" ones, whatever it means. But cppreference.com says that all accesses are fenced, and I think this is the real definition?
</blockquote></details>

Isn't this the exact same discussion as above?
___
*[`libos/src/bookkeep/libos_handle.c` line 665 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLL6wl9BMv7tHa0zqNU:-NTuayj85lIYbo41zMC_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/src/bookkeep/libos_handle.c#L665)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, good point
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSx-8ti3tseAH25xhZw:-NTuYXf-8Cc8G24Z7f3g:b-jzx3vg) ([raw file](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/bookkeep/libos_handle.c#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We could actually add `assert_{read,write}_locked`, not in owner-aware way, but just checking if lock is taken and in right mode.
</blockquote></details>

How would you do that?


<!-- Sent from Reviewable.io -->

2023-04-26 00:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 4 of 9 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @DemiMarie-reviewable, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTuiqtB6nd_J7qXict0:b-wr0c1h) (no related file):*
@stefanberger would you check this implementation on ppc64 before we merge it? Would be good to see how it behaves with ppc64 memory model.

___
___
*[`libos/include/libos_rwlock.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLMOL5AjcfjYVQRl3i:-NTuk2bY0xTSIeYC9c3U:b-sl76tr) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The writer puts the number of currently-active readers into `departing_readers`

This is slightly misleading, it doesn't put the _current_ number of readers, but the number of readers at the time of the previous atomic addition. Ditto for other points in that description.
</blockquote></details>

Actually upon re-reading this description just restates what the code does, line by line. Is this something we want to have?
Added some comments below and above, improvement suggestions are welcome.


<!-- Sent from Reviewable.io -->

2023-04-26 01:24 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 4 of 9 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @DemiMarie-reviewable, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTv6pxE3dDWGyfVHIKk:b4mz2z8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger would you check this implementation on ppc64 before we merge it? Would be good to see how it behaves with ppc64 memory model.
</blockquote></details>

Thanks for letting me know.

The current problem from the ppc64 perspective is this patch here: https://github.com/gramineproject/gramine/commit/a01265b22b20abe47f11968a2e35318866e5166f  [Treat (e)poll error and hang-up events separately ]   I need to revert it otherwise nginx test case doesn't work anymore... the client seems to get stuck and times out.

I am not sufficiently familiar with the details on the atomic operation parameters relaxed, acquire, and release and so on. The question becomes how often to run the test cases so that any issue would appear. So far regression tests as well as tests for busybox, nginx, lighttpd, redis, and ltp ran fine twice at least. I will keep them running for a couple more loops ... but occasionally issues may appear due to other reasons.

___


<!-- Sent from Reviewable.io -->

2023-04-26 04:36 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 4 of 9 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @DemiMarie-reviewable, @dimakuv, @mkow, and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTv_wHqCGUU4HVjgqoK:bieuyad) (no related file):*
> The current problem from the ppc64 perspective is this patch here: a01265b  [Treat (e)poll error and hang-up events separately ]   I need to revert it otherwise nginx test case doesn't work anymore... the client seems to get stuck and times out.

@stefanberger I don't have a ppc env to reproduce the issue but would be really interested to understand what's going on there. Pls kindly let me know if you have any findings. Thanks a lot!

___
___
*[`libos/include/libos_rwlock.h` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1109#-NLLMOL5AjcfjYVQRl3i:-NTvo6bA9X8yGzQ6Axbg:b-w6axjc) ([raw file](https://github.com/gramineproject/gramine/blob/de6c5cbf877316c514af7110348a95d4f720fd29/libos/include/libos_rwlock.h#L20)):*
> Actually upon re-reading this description just restates what the code does, line by line. Is this something we want to have?

I re-read this also. Personally I think this complements the "High level description" added above (which reads more like the "design essentials"). Also, it's not exactly some restating "line by line" but rather like "inter-procedure" reinterpretation. I may put it in `libos/src/libos_rwlock.c` which may facilitate some readers.
___
*[`libos/include/libos_rwlock.h` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvdBtD3bcF8IwEd7zh:-NTvdBtD3bcF8IwEd7zi:bmgde7r) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L13)):*
> ```objc
>  * The most important part is the `state` variable, which tracks the number of active readers. It
>  * also indicates whether a writer is active (waiting for the lock or already has it). Each reader
>  * increments this variable on lock and decrements on unlock. Writes decrements it by a large
> ```

A writer



_Code quote:_
```objc
Writes
```
___
*[`libos/include/libos_rwlock.h` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvc9M_AUXHTQ2buEit:-NTvc9M_AUXHTQ2buEiu:bp1vek7) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L16)):*
> ```objc
>  * value (bigger than maximal number of readers) on write lock, which also hints any incoming
>  * readers that a writer is pending (so they must wait for the writer to finish).
>  * Rest of the variables is used to signal waiting readers when the writer is finised and waiting
> ```

finished



_Code quote:_
```objc
finised
```
___
*[`libos/include/libos_rwlock.h` line 17 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvcPyTCPNApHqvPkvR:-NTvcPyTCPNApHqvPkvS:b-8zdqh1) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L17)):*
> ```objc
>  * readers that a writer is pending (so they must wait for the writer to finish).
>  * Rest of the variables is used to signal waiting readers when the writer is finised and waiting
>  * writer when all readers have released the lock.
> ```

writers



_Code quote:_
```objc
writer
```
___
*[`libos/include/libos_rwlock.h` line 35 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTveWRdC0Ko8C85eJ_c:-NTveWRdC0Ko8C85eJ_d:bx2s0xo) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L35)):*
> ```objc
>      * > 0 - read locked
>      *
>      * All accesses are acquire/release atomics, which also synchronize readers with writers.
> ```

acquiring/releasing?



_Code quote:_
```objc
acquire/release
```
___
*[`libos/include/libos_rwlock.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvh3be-R9mLPmOkXuO:-NTvh3be-R9mLPmOkXuP:b-pkw6q7) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L63)):*
> ```objc
>     int64_t state = __atomic_fetch_add(&l->state, 1, __ATOMIC_ACQUIRE);
>     if (state < 0) {
>         rwlock_read_lock_cold(l);
> ```

I didn't get the naming `_cold` when I first read it w/o any context. Maybe we should rename it to sth. like `rwlock_read_lock_slow_path()` or `rwlock_read_lock_bottom_half()`?



_Code quote:_
```objc
rwlock_read_lock_cold
```
___
*[`libos/src/libos_rwlock.c` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvjIwVDRUmXCJ2DKsc:-NTvjIwVDRUmXCJ2DKsd:b-l4u26t) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/src/libos_rwlock.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2022 Intel Corporation
> ```

2023 now? same for all the other files.



_Code quote:_
```C
2022
```
___
*[`libos/src/libos_rwlock.c` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvjZSs0aN3C3RJO5ut:-NTvjZSs0aN3C3RJO5uu:bgojtt1) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/src/libos_rwlock.c#L5)):*
> ```C
>  *                    Borys Popławski <borysp@invisiblethingslab.com>
>  */
> #include "pal.h"
> ```

Pls add a blank line above.


<!-- Sent from Reviewable.io -->

2023-04-26 04:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 4 of 9 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @DemiMarie-reviewable, @dimakuv, @mkow, and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NTvqxkP4laPNnQ_Fc2d:b-cvvg7x) (no related file):*
> Note to myself: we can use https://github.com/eliben/code-for-blog/blob/master/2019/rwlocks/rwlock_test.go as inspiration to how  to test this.

Do we still plan to add some tests for this? Or we do it separately in a follow-up PR?

___


<!-- Sent from Reviewable.io -->

2023-04-26 09:13 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 17 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvcPyTCPNApHqvPkvR:-NTwnjVZAfTytCbo_ak_:bz5tzsm) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L17)):*
> Here we want to highlight that there is a single writer at a time that is waiting for all current readers to release the lock.

Yes, I agree - technically this should be a single writer, though I'm not sure whether it's intentional for the highlight here.

Anyway, my suggestion is wrong -- but I would go w/ "and a/the waiting writer when ..." (this was actually my original point).
___
*[`libos/include/libos_rwlock.h` line 35 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTveWRdC0Ko8C85eJ_c:-NTwlwFS2wyLt67owf6D:bnkvpb1) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin No, I think the current sentence reads correctly in English. I don't see a need to modify.
</blockquote></details>

Ah right, I misread it.


<!-- Sent from Reviewable.io -->

2023-04-26 11:12 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTxFQ7S6L4MNFCILwuy:b-xkpa31) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> The current problem from the ppc64 perspective is this patch here: a01265b  [Treat (e)poll error and hang-up events separately ]   I need to revert it otherwise nginx test case doesn't work anymore... the client seems to get stuck and times out.

@stefanberger I don't have a ppc env to reproduce the issue but would be really interested to understand what's going on there. Pls kindly let me know if you have any findings. Thanks a lot!
</blockquote></details>

I ran the above mentioned tests now for several hours and they all worked fine.

___


<!-- Sent from Reviewable.io -->

2023-04-26 11:30 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTxJp0P7exOCDXj1wTG:bicvre) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I ran the above mentioned tests now for several hours and they all worked fine.
</blockquote></details>

@kailun-qin It's this line here in libos_epoll.c that I need to comment out to make it work again on ppc64: 

```
this_item_events |= items[i]->events & EPOLLRDHUP;
```

___


<!-- Sent from Reviewable.io -->

2023-04-26 12:12 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTxSR1eDZ7VAXJVZgef:bkgwjfq) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

@kailun-qin It's this line here in libos_epoll.c that I need to comment out to make it work again on ppc64: 

```
this_item_events |= items[i]->events & EPOLLRDHUP;
```
</blockquote></details>

We should discuss this elsewhere, but ... : epoll_wait() works a couple of times and then gets stuck in this call here with -1 parameter (previously was always 65000):

```
(libos_parser.c:1677:buf_write_all) [P5:T5:nginx] trace: ---- epoll_wait(14, 0x36f666438030, 512, -1) ...
```

___


<!-- Sent from Reviewable.io -->

2023-04-26 12:13 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTxToem6suapt_Fsea6:b1s32ij) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

We should discuss this elsewhere, but ... : epoll_wait() works a couple of times and then gets stuck in this call here with -1 parameter (previously was always 65000):

```
(libos_parser.c:1677:buf_write_all) [P5:T5:nginx] trace: ---- epoll_wait(14, 0x36f666438030, 512, -1) ...
```
</blockquote></details>

I am using the apache client, I think x86 may using something different:
```
ab -k -n 10000 -c 1 127.0.0.1:8002/random/10K.1.html
```

___


<!-- Sent from Reviewable.io -->

2023-04-26 12:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NTxZzDa4YS5lv0mNmaD:bqhz9y0) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Note to myself: we can use https://github.com/eliben/code-for-blog/blob/master/2019/rwlocks/rwlock_test.go as inspiration to how  to test this.

Do we still plan to add some tests for this? Or we do it separately in a follow-up PR?
</blockquote></details>

Yes, definitely. But I'm not sure if Borys will have time for this, he wasn't sure when we talked yesterday.

@boryspoplawski: What should we do with them?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NTx_GAk9Fxvq0EwmVm7:bgs733y) (no related file):*
> @kailun-qin It's this line here in libos_epoll.c that I need to comment out to make it work again on ppc64:

That's interesting. Could you and Kailun create an issue and check out what's going on? We should debug this, maybe that PR was bugged and we missed it.

> The question becomes how often to run the test cases so that any issue would appear

We'll ping you again when we add some stress tests for these locks, I think it will help the most to run them (once we have them) instead of full workloads.

___


<!-- Sent from Reviewable.io -->

2023-04-27 00:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NTuSjun5Z9QMjNVEv98:b-g5zd3e) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, definitely. But I'm not sure if Borys will have time for this, he wasn't sure when we talked yesterday.

@boryspoplawski: What should we do with them?
</blockquote></details>

I don't have any idea for a good quick test, so you can append a commit with one to this branch or we can try a follow up.

___
___
*[`libos/include/libos_rwlock.h` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvdBtD3bcF8IwEd7zh:-NU-2llx8JIQFBE4Z-Iu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvc9M_AUXHTQ2buEit:-NU-30VCBAFgsKEq2W2-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 17 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvcPyTCPNApHqvPkvR:-NU-3JYuEMEAD7wiEc8m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L17)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Here we want to highlight that there is a single writer at a time that is waiting for all current readers to release the lock.

Yes, I agree - technically this should be a single writer, though I'm not sure whether it's intentional for the highlight here.

Anyway, my suggestion is wrong -- but I would go w/ "and a/the waiting writer when ..." (this was actually my original point).
</blockquote></details>

Done.
___
*[`libos/include/libos_rwlock.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvh3be-R9mLPmOkXuO:-NU-3gIu-kYO2fjOhLMB:bp89vp5) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not against `_cold`, but `_slow_path` is slightly more preferrable to me.
</blockquote></details>

I don't mind either `_cold` or `_slow_path`, but I'm definitely against `_bottom_half`.
So which one should we use?
cc @mkow 
___
*[`libos/src/libos_rwlock.c` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvjIwVDRUmXCJ2DKsc:-NU-3vFl8WOIfIiyszC8:b-xdydyp) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/src/libos_rwlock.c#L2)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

2023 now? same for all the other files.
</blockquote></details>

Technically this code was written in `2022` and now I just moved it from one file to another.
___
*[`libos/src/libos_rwlock.c` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvjZSs0aN3C3RJO5ut:-NU-4JOs3UA-INq8svXx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/src/libos_rwlock.c#L5)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls add a blank line above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-27 08:26 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 17 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`libos/include/libos_rwlock.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvh3be-R9mLPmOkXuO:-NU0oWZh34JMsMnSXzyR:bj8uq2k) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't mind either `_cold` or `_slow_path`, but I'm definitely against `_bottom_half`.
So which one should we use?
cc @mkow 
</blockquote></details>

Let Michal decide. I'm neutral.


<!-- Sent from Reviewable.io -->

2023-04-27 08:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 12 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/libos_rwlock.c` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvjIwVDRUmXCJ2DKsc:-NU0rKcUEnXgHhJsNYvB:bwf0ggl) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/src/libos_rwlock.c#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Technically this code was written in `2022` and now I just moved it from one file to another.
</blockquote></details>

Sure :)


<!-- Sent from Reviewable.io -->

2023-04-27 22:44 UTC, mkow requested changes
> Reviewed 1 of 4 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NU3oJSy0dpdHWUwVvZ1:bs10f5s) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it starts to matter when you have a third thread. In sequentially consistent model (if all threads do atomic accesses with SEQ_CST) all 3 threads synchronize on them (and all previous read/writes are done/visible), whereas in acquire/release, two threads can see different orderings, if they do not synchronize.
https://gcc.gnu.org/wiki/Atomic/GCCMM/AtomicSync this has a nice example with 4 threads.
</blockquote></details>

Oops, seems like for some reason I accidentally pasted here a response to another discussion thread (which is also pasted to the discussion below). Here we were discussing just the naming, and I think "code hoisting" means "pulling code out of a loop" in compiler optimizer terminology?
___
*[`libos/include/libos_rwlock.h` line 85 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShm_-2EJXVzmhZ0-_g:-NU3p3t12bvllFiujJqY:bf41gl9) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't this the exact same discussion as above?
</blockquote></details>

Yeah, somehow I erased my original response to the above one, sorry.
___
*[`libos/include/libos_rwlock.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvh3be-R9mLPmOkXuO:-NU3o-MS1HydaMV3I47H:b-c79xjo) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let Michal decide. I'm neutral.
</blockquote></details>

+1 to `_slow_path`
___
*[`libos/src/libos_rwlock.c` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1109#-NU3pUPx7qKIE3KdOafU:-NU3pUPx7qKIE3KdOafV:b-da4d4b) ([raw file](https://github.com/gramineproject/gramine/blob/8777a3c2d2b0a475f0b43b83f0bba756a30b2cd0/libos/src/libos_rwlock.c#L8)):*
> ```C
> #include "pal.h"
> 
> #include "libos_rwlock.h"
> ```

Didn't you (@dimakuv and @boryspoplawski) want to remove this separate group for matching source/header includes?
See https://github.com/gramineproject/gramine/pull/861.
___
*[`libos/src/bookkeep/libos_handle.c` line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSx-8ti3tseAH25xhZw:-NU3rRP_37RMGYUJBcPO:b-i4hq3) ([raw file](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/bookkeep/libos_handle.c#L232)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How would you do that?
</blockquote></details>

Hmm, we can't check readers exactly, only for `state != 0`, but for writers we can do `state < 0`. This should in practice detect most cases where someone just forgot to call the locking function or something like that.
And should be super trivial to add.


<!-- Sent from Reviewable.io -->

2023-04-27 23:07 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NU3vaqP8klrDq5zF6Yc:b-2hhupn) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oops, seems like for some reason I accidentally pasted here a response to another discussion thread (which is also pasted to the discussion below). Here we were discussing just the naming, and I think "code hoisting" means "pulling code out of a loop" in compiler optimizer terminology?
</blockquote></details>

I think it means "pulling code" without "out of a loop".
From a quick google internet seems to use this term both implying it's out of a loop and not.
But see the definition of ACQUIRE here: https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
___
*[`libos/src/bookkeep/libos_handle.c` line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSx-8ti3tseAH25xhZw:-NU3xWdm-ATgiZjxJjt2:bsvuud6) ([raw file](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/bookkeep/libos_handle.c#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, we can't check readers exactly, only for `state != 0`, but for writers we can do `state < 0`. This should in practice detect most cases where someone just forgot to call the locking function or something like that.
And should be super trivial to add.
</blockquote></details>

Yup, we can just do a version with false positives (but no false negatives). I won't even try to guess how often these happen.
Do we want such version? I guess it's better than nothing and should be good enough for simple cases repeated many times (like libos/regression)


<!-- Sent from Reviewable.io -->

2023-04-27 23:14 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NShjBA9AkClyeosDiBD:-NU3zDbQ7pwPAnTZ37ce:be0ugns) ([raw file](https://github.com/gramineproject/gramine/blob/46c5b157012dce9c7cf943fc7fe9e4e27a20eeaf/libos/include/libos_rwlock.h#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it means "pulling code" without "out of a loop".
From a quick google internet seems to use this term both implying it's out of a loop and not.
But see the definition of ACQUIRE here: https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
</blockquote></details>

Ok, I won't block then, but this was quite confusing for me. I would prefer the straightforward "This prevents reordering code to before it".
___
*[`libos/src/bookkeep/libos_handle.c` line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSx-8ti3tseAH25xhZw:-NU3zce2DX5hFLsxCtxj:bdg6y89) ([raw file](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/bookkeep/libos_handle.c#L232)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yup, we can just do a version with false positives (but no false negatives). I won't even try to guess how often these happen.
Do we want such version? I guess it's better than nothing and should be good enough for simple cases repeated many times (like libos/regression)
</blockquote></details>

IMO yes, it's simple, there shouldn't be any drawbacks to having it and maybe someday it will save someone a long debugging session :)


<!-- Sent from Reviewable.io -->

2023-04-28 00:27 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 6 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, @mkow, and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTvh3be-R9mLPmOkXuO:-NU4DaPp59GUq-5fLFSv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3699aa7ce4279ebf0cbb1e4ec8301fcedb054c45/libos/include/libos_rwlock.h#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to `_slow_path`
</blockquote></details>

Done.
___
*[`libos/src/libos_rwlock.c` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1109#-NU3pUPx7qKIE3KdOafU:-NU49VCk5HEx954NhtQs:bwl8pee) ([raw file](https://github.com/gramineproject/gramine/blob/8777a3c2d2b0a475f0b43b83f0bba756a30b2cd0/libos/src/libos_rwlock.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Didn't you (@dimakuv and @boryspoplawski) want to remove this separate group for matching source/header includes?
See https://github.com/gramineproject/gramine/pull/861.
</blockquote></details>

Don't jump into conclusions, this was a copy paste mistake :)
___
*[`libos/src/bookkeep/libos_handle.c` line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/1109#-NSx-8ti3tseAH25xhZw:-NU4AGUD1KyWKQPtIzSW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/bookkeep/libos_handle.c#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO yes, it's simple, there shouldn't be any drawbacks to having it and maybe someday it will save someone a long debugging session :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-28 01:11 UTC, mkow reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/src/libos_rwlock.c` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1109#-NU3pUPx7qKIE3KdOafU:-NU4PCH9D4H2qZLDXrb6:b32vhw) ([raw file](https://github.com/gramineproject/gramine/blob/8777a3c2d2b0a475f0b43b83f0bba756a30b2cd0/libos/src/libos_rwlock.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't jump into conclusions, this was a copy paste mistake :)
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2023-04-28 04:24 UTC, kailun-qin reviewed
> Reviewed 2 of 7 files at r1, 2 of 4 files at r2, 1 of 4 files at r3, 1 of 3 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)



<!-- Sent from Reviewable.io -->

2023-04-28 07:37 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)



<!-- Sent from Reviewable.io -->

2023-04-28 17:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 5 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @DemiMarie-reviewable, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NU7zE_TAwrGCYqpwLL3:-NU7zE_U5zEFok-aMHUP:b-yz1f37) (no related file):*
FYI: I squashed + rebase this PR, as it's getting ready for finalization (waiting for a commit with tests from @mkow) and you all seen the latest (pre squash) version.

___


<!-- Sent from Reviewable.io -->

2023-05-01 17:01 UTC, mkow reviewed
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 9 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NRencCl7pNFXs4IzzI9:-NUNDYLy-vfVbuhJDa4H:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't have any idea for a good quick test, so you can append a commit with one to this branch or we can try a follow up.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUND_3V2A37I-e0QbUy:b-9f6bea) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> That's interesting. Could you and Kailun create an issue and check out what's going on? We should debug this, maybe that PR was bugged and we missed it.

Created an issue: https://github.com/gramineproject/gramine/issues/1314.

@stefanberger Thanks for all the info! Feel free to add any details and let's discuss there. I'll try to reproduce and debug it on x86.
</blockquote></details>

@stefanberger: I just added a test to this PR, could you run it on ppc64? You can play with the cmdline parameters, a quick test is e.g. `gramine-direct rwlock 5 100 10 3 100`, but you can try increasing the parallelism to pressure the cache more (`instances` param) or the number of iterations in each instance (`iterations`).

___


<!-- Sent from Reviewable.io -->

2023-05-01 17:32 UTC, boryspoplawski reviewed
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @stefanberger)

___
*[`libos/include/arch/x86_64/gramine_entry_api.h` line 53 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNEQNzEpCLeoFwTPah:-NUNEQNzEpCLeoFwTPai:be3d3mh) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/include/arch/x86_64/gramine_entry_api.h#L53)):*
> ```objc
>     GRAMINE_CALL_REGISTER_LIBRARY = 1,
>     GRAMINE_CALL_RUN_TEST,
>     GRAMINE_CALL_RWLOCK_CREATE,
> ```

I think a comment is due why we are not using `GRAMINE_CALL_RUN_TEST` but set of separate functions (I guess because we need full control over the locks from multiple threads).
___
*[`libos/src/libos_call.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFNDP9LGXwJh1n1zl:-NUNFNDP9LGXwJh1n1zm:b-q7agi0) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L112)):*
> ```C
>             struct libos_rwlock* lock = malloc(sizeof(*lock));
>             if (!lock)
>                 return 0;
> ```

Shouldn't this return some negative value?
___
*[`libos/src/libos_call.c` line 114 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNEzxW3VU5e4A7_6qO:-NUNEzxX9n3_Hy7ag4ts:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L114)):*
> ```C
>                 return 0;
>             *(struct libos_rwlock**)arg1 = lock;
>             return rwlock_create(lock);
> ```





_Suggestion:_
```C
            if (!rwlock_create(lock)) {
                free(lock);
                return -ESOMETHING ??;
            }
            *(void**)arg1 = lock;
            return 0;
```
___
*[`libos/src/libos_call.c` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFT5F936UsnH7ugx9:-NUNFT5F936UsnH7ugxA:b-d3teku) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L117)):*
> ```C
>         }
>         case GRAMINE_CALL_RWLOCK_DESTROY:
>             rwlock_destroy((struct libos_rwlock*)arg1);
> ```

`free(arg1)` ?
___
*[`libos/test/regression/meson.build` line 101 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNH6UxBr5hXhfTFDNT:-NUNH6UxBr5hXhfTFDNU:bnoz8yc) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/meson.build#L101)):*
> ```Meson
>     'rwlock': {
>         'include_directories': include_directories(
>             # for `libos_entry_api.h`
> ```

There is no such file?
___
*[`libos/test/regression/meson.build` line 102 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNH8rB9hLBVODvcyf5:-NUNH8rB9hLBVODvcyf6:by2tclk) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/meson.build#L102)):*
> ```Meson
>         'include_directories': include_directories(
>             # for `libos_entry_api.h`
>             '../../include',
> ```

Why do we need this path?
___
*[`libos/test/regression/rwlock.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFr-HCyRJ0K5NQ7Oi:-NUNFr-HCyRJ0K5NQ7Oj:b-kd5hnc) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L14)):*
> ```C
> #include "gramine_entry_api.h"
> 
> #define RUNTIME_ASSERT(x) do {if (!(x)) errx(1, "Assertion failure: `" #x "` is false"); } while (0)
> ```

I don't like the name, `assert` is also in runtime (just in debug builds).
Also you could `RUNTIME_ASSERT(x) CHECK((x) ? 0 : -1)` or even `CHECK(-!(x))`
___
*[`libos/test/regression/rwlock.c` line 34 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNHtq0-dEN2KJDs1FG:-NUNHtq0-dEN2KJDs1FH:bajeb3w) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L34)):*
> ```C
>     size_t writers_delay_us;
> };
> ```

I think we should have a global comment what these reads (senselessly looping to reach writers state) + writes (calculating two fibonacci sequences, 2nd moved by one step from the first?) do.
___
*[`libos/test/regression/rwlock.c` line 54 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJQ6s09WDIRbr4NJS:-NUNJQ6s09WDIRbr4NJT:b-qd5w9u) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L54)):*
> ```C
> }
> 
> static int reader_(void* args_) {
> ```

IMO we don't need this wrapper func, you could just unpack arguments directly in `reader`, like:
```
static int reader(void* args_) {
    struct reader_args* args = (struct reader_args*)args_;
    void* lock = args->lock;
    ...
```
___
*[`libos/test/regression/rwlock.c` line 66 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJmm56uVD9UePfdbY:-NUNJmm56uVD9UePfdbZ:b-udlaw8) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L66)):*
> ```C
>          * to be executed for testing. */
>         /* *= [0, 1] */
>         /*    [1, 1] */
> ```

Why 3 separate comments?
___
*[`libos/test/regression/rwlock.c` line 67 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNKES_C-jvvdQFq8R8:-NUNKESaE6qKa8eoql9w:b22sfhn) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L67)):*
> ```C
>         /* *= [0, 1] */
>         /*    [1, 1] */
>         *m = (struct matrix) {
> ```

I would even split this so 2 sequences are calculated separately, like
```
m->b += m->a;
m->a = m->b - m->a;
thrd_yield();
2nd sequence
```
wdyt?
___
*[`libos/test/regression/rwlock.c` line 72 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNL-nt5SsgNuS7hsvh:-NUNL-nt5SsgNuS7hsvi:b-9yq2np) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L72)):*
> ```C
>         };
>         gramine_rwlock_write_unlock(lock);
>         if (thrd_sleep(&(struct timespec){.tv_nsec = writers_delay_us * 1000}, NULL) < -1)
> ```

Isn't `usleep(writers_delay_us)` simpler? 
___
*[`libos/test/regression/rwlock.c` line 77 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNLBtWAYW2B_IA8BVQ:-NUNLBtWAYW2B_IA8BVR:bfm9vcz) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L77)):*
> ```C
> }
> 
> static int writer_(void* args_) {
> ```

Ditto (wrapper)
___
*[`libos/test/regression/rwlock.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNLhP26okIyISbANXZ:-NUNLhP26okIyISbANX_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L112)):*
> ```C
>             .writers_delay_us = writers_delay_us,
>         });
>         if (ret < 0)
> ```





_Suggestion:_
```C
 if (ret != thrd_success)
```
___
*[`libos/test/regression/rwlock.c` line 119 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNLvUx6h9ZGQ3MLkgB:-NUNLvUx6h9ZGQ3MLkgC:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L119)):*
> ```C
>     for (size_t i = 0; i < readers_num + writers_num; i++) {
>         int ret = thrd_join(threads[i], NULL);
>         if (ret < 0)
> ```



 [...]

2023-05-01 17:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @stefanberger)

___
*[`libos/include/libos_rwlock.h` line 69 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNNBq18QftdKrwenFl:-NUNNBq28fSSzOz_zarl:bg3l73q) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/include/libos_rwlock.h#L69)):*
> ```objc
> static inline void rwlock_read_unlock(struct libos_rwlock* l) {
>     RMB();
>     int64_t state = __atomic_sub_fetch(&l->state, 1, __ATOMIC_RELAXED);
> ```

Note to myself: rethink whether using acquire/release here isn't strictly better/faster (instead of fence + relaxed).


<!-- Sent from Reviewable.io -->

2023-05-01 17:40 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUNObXA5Ahcj8O9no1K:baxhedy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger: I just added a test to this PR, could you run it on ppc64? You can play with the cmdline parameters, a quick test is e.g. `gramine-direct rwlock 5 100 10 3 100`, but you can try increasing the parallelism to pressure the cache more (`instances` param) or the number of iterations in each instance (`iterations`).
</blockquote></details>

Looks good to me.
```
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 20 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 20 15 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 5 100 5 15 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 5 100 15 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 15 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
```

___


<!-- Sent from Reviewable.io -->

2023-05-03 15:49 UTC, mkow reviewed
> Reviewed 7 of 7 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUUIuAS4BFsbcgTuDCS:b-k69rxo) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Looks good to me.
```
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 20 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 20 15 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 5 100 5 15 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 5 100 15 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 15 5 100
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 100 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
```
</blockquote></details>

Could you try a bit longer runs? E.g. 50 instances with 1000 iterations, should take only a few minutes (but you may need to raise the descriptors number limit for the host part of Gramine if you have too many workers: `ulimit -n <fd_limit>`).

___
___
*[`libos/include/arch/x86_64/gramine_entry_api.h` line 53 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNEQNzEpCLeoFwTPah:-NUUKWvd8VFWvr7zaRK0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/include/arch/x86_64/gramine_entry_api.h#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think a comment is due why we are not using `GRAMINE_CALL_RUN_TEST` but set of separate functions (I guess because we need full control over the locks from multiple threads).
</blockquote></details>

Done.
___
*[`libos/src/libos_call.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFNDP9LGXwJh1n1zl:-NUUK_Ou-bD9-XQ2EYaE:b-wp2pvk) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this return some negative value?
</blockquote></details>

Nope, but it's a bit ugly and I didn't know what to do with it. The problem is that the original `rwlock_create()` returns a boolean. Here I can either keep the matching convention (but have this ugly bool passing as long) or return the standard int status, but then it differs from `rwlock_create()`.
What do you think?
___
*[`libos/src/libos_call.c` line 114 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNEzxW3VU5e4A7_6qO:-NUULMyo9KRLIVFtiqiY:b-2xcnte) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L114)):*
> ```C
>                 return 0;
>             *(struct libos_rwlock**)arg1 = lock;
>             return rwlock_create(lock);
> ```

That was on purpose, depends on the discussion above.
___
*[`libos/src/libos_call.c` line 117 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFT5F936UsnH7ugx9:-NUULZ-zAXF3BceTuLjO:b-9yy7en) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`free(arg1)` ?
</blockquote></details>

Right, done.
___
*[`libos/test/regression/meson.build` line 101 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNH6UxBr5hXhfTFDNT:-NUUM0tr674f5mG91wEG:b-mwmehv) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/meson.build#L101)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is no such file?
</blockquote></details>

Copied from above, indeed seems to be stale.
___
*[`libos/test/regression/meson.build` line 102 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNH8rB9hLBVODvcyf5:-NUUM87w5ipfFG6t95Ax:b-xt8too) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/meson.build#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this path?
</blockquote></details>

Seems not actually needed, looks like `run_test` got a bit stale (see above).
___
*[`libos/test/regression/rwlock.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFr-HCyRJ0K5NQ7Oi:-NUWO-Rl-ThbcMY6gtGQ:bwj29kj) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like the name, `assert` is also in runtime (just in debug builds).
Also you could `RUNTIME_ASSERT(x) CHECK((x) ? 0 : -1)` or even `CHECK(-!(x))`
</blockquote></details>

What about now?
___
*[`libos/test/regression/rwlock.c` line 34 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNHtq0-dEN2KJDs1FG:-NUWOYPR-ySqtK3ox5j6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we should have a global comment what these reads (senselessly looping to reach writers state) + writes (calculating two fibonacci sequences, 2nd moved by one step from the first?) do.
</blockquote></details>

Done.
___
*[`libos/test/regression/rwlock.c` line 54 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJQ6s09WDIRbr4NJS:-NUWOgblCFpSrXVrNSGJ:b-4uzqx3) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO we don't need this wrapper func, you could just unpack arguments directly in `reader`, like:
```
static int reader(void* args_) {
    struct reader_args* args = (struct reader_args*)args_;
    void* lock = args->lock;
    ...
```

</blockquote></details>

Yup, I know, but I slightly prefer the current way, because we have the worker function with a clear signature and the boilerplate is pushed away from it.
@dimakuv, @kailun-qin: Any preferences?
___
*[`libos/test/regression/rwlock.c` line 66 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJmm56uVD9UePfdbY:-NUWPInH8PgJc41O9lP-:b-47yzv) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why 3 separate comments?
</blockquote></details>

Check now.
___
*[`libos/test/regression/rwlock.c` line 67 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNKES_C-jvvdQFq8R8:-NUWQ0NTBrS5RMCBaxaR:b-ndbxh) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L67)):*
<details><summa [...]

2023-05-03 16:59 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUXM4NL6y7CLKST7Afz:b22avp6) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you try a bit longer runs? E.g. 50 instances with 1000 iterations, should take only a few minutes (but you may need to raise the descriptors number limit for the host part of Gramine if you have too many workers: `ulimit -n <fd_limit>`).
</blockquote></details>

```
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ ulimit -n 100000
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 60 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 5 10
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 5 10
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 15 10
TEST OK
```

The same test failure with 100 (and also 50 & 40) instances occurred when running `gramine-direct rwlock 100 100 20 5 100` in an x86_64 VM:

```
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ ulimit -n 100000
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 50 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 50 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 40 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 100 20 5 100
TEST OK
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 100 20 5 0
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
```

___


<!-- Sent from Reviewable.io -->

2023-05-03 18:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: 15 of 16 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUXtBFtCfibpkhWVLHq:bsuuj5r) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

```
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ ulimit -n 100000
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 200 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 10 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 60 1000 15 5 10
TEST OK
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 5 10
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 5 10
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@graphene-devel:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 1000 15 15 10
TEST OK
```

The same test failure with 100 (and also 50 & 40) instances occurred when running `gramine-direct rwlock 100 100 20 5 100` in an x86_64 VM:

```
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ ulimit -n 100000
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 100 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 50 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 50 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 40 100 20 5 100
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 100 20 5 100
TEST OK
stefanb@stefanb-Standard-PC-Q35-ICH9-2009:~/gramine4ppc64/libos/test/regression$ gramine-direct rwlock 30 100 20 5 0
rwlock: error at (current_it <= total_iterations) ? 0 : -1 (line 51): Success: Success
^C
```

</blockquote></details>

@stefanberger there was a bug in the test, should be fixed now, please retry

___
___
*[`libos/test/regression/rwlock.c` line 97 at r9](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUXtJJhEZDGIW7MsBM-:-NUXtJJhEZDGIW7MsBM0:b-k60ok8) ([raw file](https://github.com/gramineproject/gramine/blob/c554ac7a6e83a61df2872d4bdf77794c37e2f915/libos/test/regression/rwlock.c#L97)):*
> ```C
>     /* Spawn readers */
>     for (size_t i = 0; i < readers_num; i++) {
>         int ret = thrd_create(&threads[i], reader_, &(struct reader_args) {
> ```

FYI: the issue was with compound literal lifetime, which is the enclosing block scope. Here we were passing the address of it to another thread and exiting the block without waiting for the thread - UAF.


<!-- Sent from Reviewable.io -->

2023-05-04 01:04 UTC, mkow reviewed
> Reviewed 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/src/libos_call.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNFNDP9LGXwJh1n1zl:-NUYqEUzC7gX-TDYtMyt:b-v5e7l) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would use 0/negative int and actually change the convention so these lock constructors return `int` instead of `bool`, but this requires an uniform change, so definitely a separate commit or even PR.
If you want to leave it as is (even if for now), then please add a comment describing the situation, because right now this function has `long` as the return type and returns `0` on errors, which looks like a but (when you compare it to the rest of the code base).
</blockquote></details>

Let's do that change in a separate PR, this one is already big and changing different commits will be annoying to review. Added a comment.
___
*[`libos/src/libos_call.c` line 114 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNEzxW3VU5e4A7_6qO:-NUYyyT-AK_c9WflOcfr:b-lkg0vc) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/src/libos_call.c#L114)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Leaking `lock` on errors was on purpose? :)
(this was the main point of this suggestion/comment)
</blockquote></details>

Ah. Fixed.
___
*[`libos/test/regression/rwlock.c` line 67 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNKES_C-jvvdQFq8R8:-NUZ8Q6y11NrvSH6y0-U:bq5j2zm) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L67)):*
> I think the proposed version above is correct and doesn't use a tmp variable.

Ah, right, I missed that you also proposed how to assign it. Done.

> Missing yeah, but I wonder how would it behave when locks are slightly off, e.g. have wrong synchronization. Would be good to test by changing acquire/release to relaxed, on some arch that has weaker memory model than x86. ppc64 maybe? :)

@stefanberger: would you have time to play with it? It's very optional IMO, so only if you want to be very sure that it works well on ppc64.
___
*[`libos/test/regression/rwlock.c` line 72 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNL-nt5SsgNuS7hsvh:-NUZBgnv9xCheUxTwamC:bkksehj) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What? It does have it.
</blockquote></details>

Dunno, maybe we don't pass enough paths to the compiler... But it didn't work for me and I don't care that much about this change to debug our musl build config, but if you insist I can look closer at it.


<!-- Sent from Reviewable.io -->

2023-05-04 09:33 UTC, boryspoplawski reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/test/regression/rwlock.c` line 72 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNL-nt5SsgNuS7hsvh:-NUa48rp8-LV_aCHZ6HC:b2l8uac) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L72)):*
> Dunno, maybe we don't pass enough paths to the compiler...

It should be a standard path.

> But it didn't work for me and I don't care that much about this change to debug our musl build config, but if you insist I can look closer at it.

I don't really care about `usleep` vs `thrd_sleep`, but missing headers is not a good sign. Maybe it's better to debug it now with a clear repro, instead of waiting for it to blow up elsewhere?

Update: I just tested, it works correctly for me. Pushed a fixup (hope you don't mind). You probably did not set any feature macros (required for `usleep` declaration).


<!-- Sent from Reviewable.io -->

2023-05-04 11:54 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r7, 3 of 7 files at r8, 2 of 4 files at r9, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @stefanberger)

___
*[`libos/test/regression/rwlock.c` line 54 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJQ6s09WDIRbr4NJS:-NUaZJJH6enpm9l5ZiHd:bxkrfwu) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't might that much, so unblocking.
</blockquote></details>

I don't mind the current version.
___
*[`libos/test/regression/rwlock.c` line 38 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaZSM58vZQZ4gCCLQL:-NUaZSM68hvAlWzRvLkS:b7q5qon) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.c#L38)):*
> ```C
> };
> 
> /* Keeps its own fibonacci sequence and synchronizes it with the shared ones. */
> ```

`shared ones` -> `shared one`
___
*[`libos/test/regression/rwlock.manifest.template` line 4 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaY2Cj6xlOIquyWLui:-NUaY2Cj6xlOIquyWLuj:bhx3qp3) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.manifest.template#L4)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> 
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"
> ```

Please remove `arch_libdir` entries (2x)
___
*[`libos/test/regression/rwlock.manifest.template` line 11 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaY5fbD3Po6adhokXK:-NUaY5fbD3Po6adhokXL:bhx3qp3) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.manifest.template#L11)):*
> ```
>   { path = "/{{ entrypoint }}", uri = "file:{{ binary_dir }}/{{ entrypoint }}" },
>   { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
>   { path = "/usr/{{ arch_libdir }}", uri = "file:/usr/{{ arch_libdir }}" },
> ```

Please remove `arch_libdir` entries (2x)


<!-- Sent from Reviewable.io -->

2023-05-05 00:32 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NTukvz_1EyRmVEZhLPk:-NUdIpCI74GxgjZpW8K2:buvt1n6) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger there was a bug in the test, should be fixed now, please retry
</blockquote></details>

Retried... <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

___
___
*[`libos/test/regression/rwlock.c` line 67 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNKES_C-jvvdQFq8R8:-NUdIhMp5FLjbvypd-dY:b738ppz) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I think the proposed version above is correct and doesn't use a tmp variable.

Ah, right, I missed that you also proposed how to assign it. Done.

> Missing yeah, but I wonder how would it behave when locks are slightly off, e.g. have wrong synchronization. Would be good to test by changing acquire/release to relaxed, on some arch that has weaker memory model than x86. ppc64 maybe? :)

@stefanberger: would you have time to play with it? It's very optional IMO, so only if you want to be very sure that it works well on ppc64.
</blockquote></details>

Looks good. Previously failed test passed. <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2023-05-05 02:09 UTC, mkow reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NSs4sBlA5GAnr0iC2B3:be571us) (no related file):*
FYI: There's still some issue on 18.04:

```
11:38:58  ../libos/test/regression/rwlock.c:11:10: fatal error: threads.h: No such file or directory
11:38:58   #include <threads.h>
11:38:58            ^~~~~~~~~~~
```

I need to look into this, but maybe 18.04 is too old for this...

___
___
*[`libos/test/regression/rwlock.c` line 38 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaZSM58vZQZ4gCCLQL:-NUddbh95OBVG-sLWsn-:b-9l6cv5) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`shared ones` -> `shared one`
</blockquote></details>

That's intentional, there are 2 shared sequences (see the description of `shared_state`).
___
*[`libos/test/regression/rwlock.manifest.template` line 4 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaY2Cj6xlOIquyWLui:-NUdea_dC0PIRk5XuQCX:buexbv4) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `arch_libdir` entries (2x)
</blockquote></details>

What do you mean exactly? To just leave `/lib`? If so, why? I think these are pretty standard?


<!-- Sent from Reviewable.io -->

2023-05-05 05:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/rwlock.c` line 38 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaZSM58vZQZ4gCCLQL:-NUeToASEGOy7kyOt203:b-xlp235) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.c#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's intentional, there are 2 shared sequences (see the description of `shared_state`).
</blockquote></details>

Ah, that's what you meant.
___
*[`libos/test/regression/rwlock.manifest.template` line 4 at r12](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUaY2Cj6xlOIquyWLui:-NUeTv3nBv8mXOEKvX-y:b-oz42cy) ([raw file](https://github.com/gramineproject/gramine/blob/b1202cbf338cfd8969467e6755ce874cba85b817/libos/test/regression/rwlock.manifest.template#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean exactly? To just leave `/lib`? If so, why? I think these are pretty standard?
</blockquote></details>

Yes, I meant just keep the `/lib` dir. Why would we want unused paths (even if they are standard)? Let's keep this manifest minimal.


<!-- Sent from Reviewable.io -->

2023-05-05 10:55 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUfY7m40q3Fk1Eh66M3:b48mgvi) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: There's still some issue on 18.04:

```
11:38:58  ../libos/test/regression/rwlock.c:11:10: fatal error: threads.h: No such file or directory
11:38:58   #include <threads.h>
11:38:58            ^~~~~~~~~~~
```

I need to look into this, but maybe 18.04 is too old for this...
</blockquote></details>

`Jenkins-Debug-20.04` also failed

___


<!-- Sent from Reviewable.io -->

2023-05-05 10:59 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUfYz3w-W0Exdx5C9Cu:b4n4nk2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`Jenkins-Debug-20.04` also failed
</blockquote></details>

And seems C11 threads are available since glibc 2.28, iirc ubuntu18.04 had an older version. pthreads time?
But that doesn't explain the above 20.04 failure

___


<!-- Sent from Reviewable.io -->

2023-05-05 11:00 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 4 of 4 files at r7, 3 of 7 files at r8, 2 of 4 files at r9, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/rwlock.c` line 54 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNJQ6s09WDIRbr4NJS:-NUfNTZR-lzES0f2q4ON:bh90ix7) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/test/regression/rwlock.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't mind the current version.
</blockquote></details>

Yeah, I also slightly prefer the current way.


<!-- Sent from Reviewable.io -->

2023-05-05 11:42 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUfeJrj6M-DF9dGyWQ-:bz7fc38) (no related file):*
> And seems C11 threads are available since glibc 2.28, iirc ubuntu18.04 had an older version. pthreads time?

Yep, ubuntu18.04 uses glibc 2.27 by default (so pthreads time). But ubuntu20.04 has glibc 2.31 which should work fine.

___


<!-- Sent from Reviewable.io -->

2023-05-05 15:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUgWEz02N-XqYsbNirZ:b-w8e07s) (no related file):*
> Maybe time to remove 18.04 pipelines? We decided that we are dropping it after v1.4.

+1, I think we've made some decisions earlier that we'd drop ubuntu 18.04 -- no ubuntu18.04 packages, and only real Gramine issues will be fixed (i.e., ignoring any dependency issues)

___


<!-- Sent from Reviewable.io -->

2023-05-05 20:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUhVIL19gOq02eSLiTE:by498qj) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Maybe time to remove 18.04 pipelines? We decided that we are dropping it after v1.4.

+1, I think we've made some decisions earlier that we'd drop ubuntu 18.04 -- no ubuntu18.04 packages, and only real Gramine issues will be fixed (i.e., ignoring any dependency issues)
</blockquote></details>

Do we really want to drop 18.04 now? This would require adding 22.04 pipelines...

___


<!-- Sent from Reviewable.io -->

2023-05-07 19:38 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUri-QTBKdBLtaW_nl_:b-ltilka) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we really want to drop 18.04 now? This would require adding 22.04 pipelines...
</blockquote></details>

I wouldn't mind dropping 18.04 pipelines now and prioritizing adding 22.04 before the release. 18.04 is really too annoying to deal with it any longer...

___


<!-- Sent from Reviewable.io -->

2023-05-08 07:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NUu9hXN2zlKhhva0uF4:ba7ktw4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't mind dropping 18.04 pipelines now and prioritizing adding 22.04 before the release. 18.04 is really too annoying to deal with it any longer...
</blockquote></details>

Ok, I don't mind dropping 18.04. I guess we need an incentive to finally move away from 18.04.

Who's gonna do that?

___


<!-- Sent from Reviewable.io -->

2023-05-10 14:30 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NV53Td34texUgVDJ0Zx:bgbgf5w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I don't mind dropping 18.04. I guess we need an incentive to finally move away from 18.04.

Who's gonna do that?
</blockquote></details>

I did this: https://github.com/gramineproject/gramine/commit/a9c48a59fe4d82cb9a966b12080b08b1a2c4715f

Now we can proceed with this PR.

___


<!-- Sent from Reviewable.io -->

2023-05-10 14:35 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUddzeqEK8npM5U1MjL:-NV54b2c76seSULnp79b:b9x2p3v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I did this: https://github.com/gramineproject/gramine/commit/a9c48a59fe4d82cb9a966b12080b08b1a2c4715f

Now we can proceed with this PR.
</blockquote></details>

Rebased

___


<!-- Sent from Reviewable.io -->

2023-05-10 15:00 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @mkow)

___
*[`libos/include/libos_rwlock.h` line 69 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNNBq18QftdKrwenFl:-NV59LwL3IwT3FLb1_yf:b-fotdqc) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/include/libos_rwlock.h#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Note to myself: rethink whether using acquire/release here isn't strictly better/faster (instead of fence + relaxed).
</blockquote></details>

Is this still a blocking thing? I thought we wanted to merge now.


<!-- Sent from Reviewable.io -->

2023-05-10 15:56 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2023-05-10 17:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`libos/include/libos_rwlock.h` line 69 at r8](https://reviewable.io/reviews/gramineproject/gramine/1109#-NUNNBq18QftdKrwenFl:-NV5jis5C5Zli8gnQNTK:bz50vga) ([raw file](https://github.com/gramineproject/gramine/blob/f7b599bcd07e4ded0922218a356fe249b2516d66/libos/include/libos_rwlock.h#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this still a blocking thing? I thought we wanted to merge now.
</blockquote></details>

Done.
For some reason I thought that read mem barrier will be more lightweight here, which is not true.
Both version have the properties we want (synchronization with write_lock and code sinking prevention), but current one does not entail read mem barrier on some archs (where it's not needed, like x86).


<!-- Sent from Reviewable.io -->

2023-05-10 19:16 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-11 01:45 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-11 12:04 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-11 14:58 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1109)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-11 15:07 UTC, merged