[CI-Examples] Increase server wait time to 300
gramineproject/gramine pull request #1113
Opened 2023-01-11 14:14 UTC by anjalirai-intel

Workloads take 2x-5x times to execute with EDMM than non-EDMM's, and thus require larger timeouts, hence increasing the wait time for server.

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

## Description of the changes 

## How to test this PR?

2023-01-11 16:16 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWaZAFAzPWMKDHda2T):*
You forgot to mention CI itself. I suggest this phrase: `[CI,CI-Examples] Increase timeout for spawning SGX server apps`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWax5u3O3FN8aOEWbQ):*
Rephrasing:
```
SGX workloads are 2-5x slower when executed with EDMM than
without EDMM, thus startups of SGX server workloads require
larger timeouts.
```
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWbRZz3--uWSSm4xAy:-NLWbRZz3--uWSSm4xAz:b-lliqsu) ([raw file](https://github.com/gramineproject/gramine/blob/2bc7d62f3423210ec05ff9e10bffc1b14aa99a1f/CI-Examples/ra-tls-secret-prov/Makefile#L177)):*
> ```Makefile
> 	cd secret_prov_minimal; \
> 	./server_epid >/dev/null & SERVER_ID=$$!; \
> 	../../../scripts/wait_for_server 300 127.0.0.1 4433; \
> ```

Sorry, I misled you. Please revert all changes in this file, because here we wait for `server_epid` or `server_dcap` -- these are **not** SGX applications, so there is no difference for them, whether we have EDMM or not.


<!-- Sent from Reviewable.io -->

2023-01-12 06:51 UTC, anjalirai-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWaZAFAzPWMKDHda2T):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to mention CI itself. I suggest this phrase: `[CI,CI-Examples] Increase timeout for spawning SGX server apps`
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWax5u3O3FN8aOEWbQ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rephrasing:
```
SGX workloads are 2-5x slower when executed with EDMM than
without EDMM, thus startups of SGX server workloads require
larger timeouts.
```
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLWbRZz3--uWSSm4xAy:-NLZjgmTBLIA2bHAU3Sl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2bc7d62f3423210ec05ff9e10bffc1b14aa99a1f/CI-Examples/ra-tls-secret-prov/Makefile#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I misled you. Please revert all changes in this file, because here we wait for `server_epid` or `server_dcap` -- these are **not** SGX applications, so there is no difference for them, whether we have EDMM or not.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 08:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-01-12 09:01 UTC, dimakuv commented
Jenkins, test this please

2023-01-15 16:29 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @anjalirai-intel)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLqFn7EC5LNdCwZcLL2):*




_Suggestion:_
```
SGX workloads are currrently 2-5x slower
```


<!-- Sent from Reviewable.io -->

2023-01-23 14:32 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1113#-NLqFn7EC5LNdCwZcLL2):*
Done


<!-- Sent from Reviewable.io -->

2023-01-23 14:43 UTC, dimakuv commented
Jenkins, test this please

2023-01-23 22:28 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1113)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-23 22:30 UTC, merged