[LibOS] regression: Add few negative tests for EDMM feature
gramineproject/gramine pull request #1120
Opened 2023-01-16 06:42 UTC by vijaydhanraj

## Description of the changes 
As part of the SDL review for EDMM PR #1054, there were a few negative tests that were identified. This PR adds those tests cases to LibOS regression test suite.

## How to test this PR? 
Please run LibOS regression tests.

2023-01-16 13:19 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLu8Ih1BB93sIekFHh7):*
I would remove `few`
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLu8FhC0vgxE1Nh-8rD):*
`!` -> `.`
___
*[`libos/test/regression/edmm_tests.c` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufKy80rvWzZUiyWdz:-NLufKy80rvWzZUiyWe-:b-h5o908) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

Can we rename this file to simply `edmm.c`
___
*[`libos/test/regression/edmm_tests.c` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufZMk0VMDWdeSmtfz:-NLufZMl3FFe7lAUlIbx:b5cuun1) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L10)):*
> ```C
> #include <unistd.h>
> 
> static const char* message;
> ```

Please add an empty line after this, for readability.
___
*[`libos/test/regression/edmm_tests.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufbjmEUnWqC1mAaXL:-NLufbjmEUnWqC1mAaXM:b-9t72b0) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L11)):*
> ```C
> 
> static const char* message;
> static void  SIGSEGV_handler(int sig) {
> ```

You have double-space here
___
*[`libos/test/regression/edmm_tests.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufeVp46NW2RVVbXf6:-NLufeVp46NW2RVVbXf7:b5dub1y) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L11)):*
> ```C
> 
> static const char* message;
> static void  SIGSEGV_handler(int sig) {
> ```

`SIGSEGV_handler` -> `sigsegv_handler`
___
*[`libos/test/regression/edmm_tests.c` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugHlC16CghhuTnPXM:-NLugHlC16CghhuTnPXN:b-7mv71u) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L13)):*
> ```C
> static void  SIGSEGV_handler(int sig) {
>     puts(message);
>     exit(0);
> ```

You cannot use these functions as they are not async-signal-safe. Please see `man signal-safety`.

I suggest to use `_exit()` instead of `exit(0)`.

Also, do you really need this `puts(message)`? I would remove it, we typically prefer to not print any messages (other than `TEST OK`) in the new tests.
___
*[`libos/test/regression/edmm_tests.c` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugmqT552DICde7kqP:-NLugmqU2NP4RcUHG9U8:b5vcayo) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L34)):*
> ```C
> }
> 
> static void foo (void) {
> ```

`foo (void)` -> `foo(void)`
___
*[`libos/test/regression/edmm_tests.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugs4u5ncdiq7OxoMh:-NLugs4u5ncdiq7OxoMi:b-gqx9c6) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L38)):*
> ```C
> }
> 
> static int test_case1(void) {
> ```

Please rename to more meaningful name: `test_segfault_on_write_to_rx_page(void)`
___
*[`libos/test/regression/edmm_tests.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhMO351GXQ2KlhCWq:-NLuhMO351GXQ2KlhCWr:brsry5d) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L41)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         message = "edmm test 1 passed: Segfault writing to code(RX) section!";
> ```

I see no real need in these messages. It's easy to follow the test as is, and for debugging it's just better to use GDB (instead of relying on prints).
___
*[`libos/test/regression/edmm_tests.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhAnGApcth7tS32yY:-NLuhAnGApcth7tS32yZ:bphj0z5) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L42)):*
> ```C
>     if (child_pid == 0) {
>         message = "edmm test 1 passed: Segfault writing to code(RX) section!";
>         *(int*)foo = 0;
> ```

Please add afterwards `exit(1); /* child must not survive the write to RX page above */`
___
*[`libos/test/regression/edmm_tests.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuiQk_1xMZwQZ7xOKY:-NLuiQk_1xMZwQZ7xOKZ:b-vkznkm) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L42)):*
> ```C
>     if (child_pid == 0) {
>         message = "edmm test 1 passed: Segfault writing to code(RX) section!";
>         *(int*)foo = 0;
> ```

Compiler may optimize this assignment away... Please use `asm volatile` to make sure the compiler can't remove this memory access attempt.
___
*[`libos/test/regression/edmm_tests.c` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhkEZ6htCh3nOwzSF:-NLuhkEZ6htCh3nOwzSG:b-kkq2ug) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L48)):*
> ```C
> }
> 
> static int test_case2(void) {
> ```

`test_segfault_on_exec_rw_page(void)`
___
*[`libos/test/regression/edmm_tests.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhs240tfumO9gngpG:-NLuhs240tfumO9gngpH:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L51)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         message = "edmm test 2 passed: Segfault executing in data(RW) section!";
> ```

ditto
___
*[`libos/test/regression/edmm_tests.c` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhtST1m9dpzGtdMqb:-NLuhtST1m9dpzGtdMqc:b-m0k2vq) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L53)):*
> ```C
>         message = "edmm test 2 passed: Segfault executing in data(RW) section!";
>         int on_stack_var = 5;
>         int *rw_addr = &on_stack_var;
> ```

`int *` -> `int* `
___
*[`libos/test/regression/edmm_tests.c` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhxel-RgbZ9BUoPGh:-NLuhxel-RgbZ9BUoPGi:b1943sm) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L55)):*
> ```C
>         int *rw_addr = &on_stack_var;
> 
>         __asm__ volatile("jmp *%0" : : "r" (rw_addr));
> ```

Please add afterwards `exit(1); /* child must not survive exec attempt of RW page above */`
___
*[`libos/test/regression/edmm_tests.c` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLui7yx9m34jvlLqpMW:-NLui7yx9m34jvlLqpMX:bpc26ma) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L61)):*
> ```C
> }
> 
> static int test_case3(void) {
> ```

`test_segfault_on_write_ro_page(void)`
___
*[`libos/test/regression/edmm_tests.c` line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/1 [...]

2023-01-16 21:20 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLu8Ih1BB93sIekFHh7):*
Do we also need `feature`?
Maybe:
> Add negative tests for EDMM


<!-- Sent from Reviewable.io -->

2023-01-17 15:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: 0 of 5 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLu8Ih1BB93sIekFHh7):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Do we also need `feature`?
Maybe:
> Add negative tests for EDMM
</blockquote></details>

Done and have removed the `feature`.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLu8FhC0vgxE1Nh-8rD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`!` -> `.`
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuX61mBAE1gIjwfunq:-NLvWwhW0g3fQisczJnJ:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/test_libos.py#L1334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest rephrasing:
```
On SGX v1, SIGSEGV handler cannot be implemented correctly, for lack of
enclave page permissions (all pages are RWX). So run only on gramine-direct
and on gramine-sgx with EDMM. 
``

(Please re-wrap the above to 100 chars per line)
```

</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1336 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufTNq8z3wqR097biG:-NLvX0De7Gms4GpY2G_x:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/test_libos.py#L1336)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to simply `test_000_edmm`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufKy80rvWzZUiyWdz:-NLvB1TfEfRv60EgjB-r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename this file to simply `edmm.c`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufZMk0VMDWdeSmtfz:-NLvBVp87S1sT_ET_P8N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this, for readability.
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufbjmEUnWqC1mAaXL:-NLvBfvNCN6fHtW6mxNo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have double-space here
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLufeVp46NW2RVVbXf6:-NLvBw-J1boW8zvDpzvQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`SIGSEGV_handler` -> `sigsegv_handler`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugHlC16CghhuTnPXM:-NLvP90k-oMSrx22zjIQ:b-6j8an0) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You cannot use these functions as they are not async-signal-safe. Please see `man signal-safety`.

I suggest to use `_exit()` instead of `exit(0)`.

Also, do you really need this `puts(message)`? I would remove it, we typically prefer to not print any messages (other than `TEST OK`) in the new tests.
</blockquote></details>

Yes, it makes sense to use `_exit(0)` here but as expected with `_exit(0)` the process immediately terminates without flushing any buffer. So if we add any prints it will not be visible.

Regarding `puts(message)`, I added it as an indicator that the segfault was triggered but have removed it now. 
___
*[`libos/test/regression/edmm_tests.c` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugmqT552DICde7kqP:-NLvQtlI8BvY-Kggqcni:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`foo (void)` -> `foo(void)`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLugs4u5ncdiq7OxoMh:-NLvS4HJBjMPy4oWLjCo:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename to more meaningful name: `test_segfault_on_write_to_rx_page(void)`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhMO351GXQ2KlhCWq:-NLvS71W8SKQSfdT0dAh:b-j794qx) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no real need in these messages. It's easy to follow the test as is, and for debugging it's just better to use GDB (instead of relying on prints).
</blockquote></details>

I have removed the messages.
___
*[`libos/test/regression/edmm_tests.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhAnGApcth7tS32yY:-NLvSYHGDouEfb8qxvFC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add afterwards `exit(1); /* child must not survive the write to RX page above */`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuiQk_1xMZwQZ7xOKY:-NM-CuHu8gzKgz_boRjM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a34d706ca454a032f64b7/libos/test/regression/edmm_tests.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Compiler may optimize this assignment away... Please use `asm volatile` to make sure the compiler can't remove this memory access attempt.
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm_tests.c` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1120#-NLuhkEZ6htCh3nOwzSF:-NLvShQv6uRs7pWSsXdu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9676140629523df7411a [...]

2023-01-18 08:42 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM31d2H0kOEQUFKDNr_:-NM31d2H0kOEQUFKDNra:b8ourkn) (no related file):*
@oshogbo Could you check inline asm here? You're much more of an expert in this.

___
___
*[`libos/test/regression/edmm.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM3-vIM3lLsZD2f4U9n:-NM3-vIM3lLsZD2f4U9o:b-spi83n) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L41)):*
> ```C
>         int* ptr = (int*)foo;
> 
>         /* *ptr = 0;*/
> ```

Please add one space after `;`
___
*[`libos/test/regression/edmm.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM3-Lat5qVz700O1vtO:-NM3-Lat5qVz700O1vtP:bjwc6kz) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L44)):*
> ```C
>         __asm__ volatile(
>             "mov $0, %0\n"
>             : "=r"(*ptr)
> ```

But you're dereferencing `ptr` in the C code, before passing it to asm.

You should do like this:
```
        __asm__ volatile("mov $0, (%0)\n" : "=r"(ptr) : : "memory");
```
___
*[`libos/test/regression/edmm.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM30rTG47PsyKhPwB65:-NM30rTG47PsyKhPwB66:btoj8v1) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L80)):*
> ```C
>             :
>             : "memory"
>         );
> ```

You're dereferencing `str[3]` in the C code, before passing it to asm.

You should do like this:
```
        __asm__ volatile("mov $104, (%0)\n" : "=r"(str) : : "memory");
```

Note that I just do `str[0] = 'h'`, to avoid pointer arithmetic. It tests the same thing, so I don't see a need to `+ 3`.


<!-- Sent from Reviewable.io -->

2023-01-18 15:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/edmm.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM3-Lat5qVz700O1vtO:-NM4PFU9788CGpWPKtiF:b-uypac0) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you're dereferencing `ptr` in the C code, before passing it to asm.

You should do like this:
```
        __asm__ volatile("mov $0, (%0)\n" : "=r"(ptr) : : "memory");
```
</blockquote></details>

Unfortunately, this throws up the following 
```
[1/13] Compiling C object libos/test/regression/musl_edmm.p/edmm.c.o
../libos/test/regression/edmm.c: Assembler messages:
../libos/test/regression/edmm.c:42: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
../libos/test/regression/edmm.c:75: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
[2/13] Compiling C object libos/test/regression/edmm.p/edmm.c.o
../libos/test/regression/edmm.c: Assembler messages:
../libos/test/regression/edmm.c:42: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
../libos/test/regression/edmm.c:75: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
```
___
*[`libos/test/regression/edmm.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM30rTG47PsyKhPwB65:-NM4PPA5Beic-UJ7uR04:b-r90l7g) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're dereferencing `str[3]` in the C code, before passing it to asm.

You should do like this:
```
        __asm__ volatile("mov $104, (%0)\n" : "=r"(str) : : "memory");
```

Note that I just do `str[0] = 'h'`, to avoid pointer arithmetic. It tests the same thing, so I don't see a need to `+ 3`.
</blockquote></details>

Sure `str[0] = 'h'` looks fine but just that we have the below warnings

```
ninja: Entering directory `build/'
[1/13] Compiling C object libos/test/regression/musl_edmm.p/edmm.c.o
../libos/test/regression/edmm.c: Assembler messages:
../libos/test/regression/edmm.c:42: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
../libos/test/regression/edmm.c:75: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
[2/13] Compiling C object libos/test/regression/edmm.p/edmm.c.o
../libos/test/regression/edmm.c: Assembler messages:
../libos/test/regression/edmm.c:42: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
../libos/test/regression/edmm.c:75: Warning: no instruction mnemonic suffix given and no register operands; using default for `mov'
[5/13] Generating gramine_hash.h with a custom command
```


<!-- Sent from Reviewable.io -->

2023-01-18 17:10 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM3-Lat5qVz700O1vtO:-NM4qZOz9nN19mRK1DP9:b4gusr9) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L44)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Fixed the issue but, please review.
</blockquote></details>

`movq` is wrong (it moves 8 bytes). You must use `movl` (it moves 4 bytes, exactly the size of the `int` type).
___
*[`libos/test/regression/edmm.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM30rTG47PsyKhPwB65:-NM4r1PvBDOgz5HYLAJL:bc7l0mo) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L80)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Fixed the issue but, please review.
</blockquote></details>

`movq` is wrong (it moves 8 bytes). You must use `movb` (it moves 1 byte, exactly the size of the `char` type).


<!-- Sent from Reviewable.io -->

2023-01-19 05:40 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/edmm.c` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM3-Lat5qVz700O1vtO:-NM7XbYI3XcHH1ZQzagq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`movq` is wrong (it moves 8 bytes). You must use `movl` (it moves 4 bytes, exactly the size of the `int` type).
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM30rTG47PsyKhPwB65:-NM7XeJ0ENRkmSyjCrm3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`movq` is wrong (it moves 8 bytes). You must use `movb` (it moves 1 byte, exactly the size of the `char` type).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-19 09:05 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 69 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM8GW8lDG1Vg7LGrQVO:-NM8GW8lDG1Vg7LGrQVP:b26dqj7) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L69)):*
> ```C
>         char* str = (char*)"Hello World!"; /* suppress const warning by casting to char* */
> 
>         /* str[3] = 'L'; */
> ```

This comment is wrong now. Should be `str[0] = 'h'`


<!-- Sent from Reviewable.io -->

2023-01-19 09:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM8HVaO1Ke7P6IeuRb0:-NM8HVaO1Ke7P6IeuRb1:b-pwif7) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L81)):*
> ```C
>     if (signal(SIGSEGV, sigsegv_handler) == SIG_ERR) {
>         err(1, "setting signal handler failed");
>     }
> ```

I realized just now -- why do we have such inverted logic? Currently, we have a child process that will return `0` (success) if there was a segfault, and will return `1` if there wasn't a segfault.

Instead, we can simply remove this SIGSEGV handler and rely on the fact that the child's segfault (due to wrong page permissions) will return a `status` that indicates a SIGSEGV failure. So we can remove `sigsegv_handler()` and instead modify the logic of `wait_for_child()` a bit. I would also rename to `wait_for_failing_child()`.


<!-- Sent from Reviewable.io -->

2023-01-20 15:27 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: 4 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/edmm.c` line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMEiP-wCP6asCEVfKc5:-NMEiP-wCP6asCEVfKc6:bfjny8u) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L56)):*
> ```C
>         int* rw_addr = &on_stack_var;
> 
>         __asm__ volatile("jmp *%0" : : "r" (rw_addr));
> ```

Also fixed this instruction to jump to address.
___
*[`libos/test/regression/edmm.c` line 69 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM8GW8lDG1Vg7LGrQVO:-NMEiVEa7E0Hz_if8Eww:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is wrong now. Should be `str[0] = 'h'`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM8HVaO1Ke7P6IeuRb0:-NMEg_d59D-TXg6w7Zt7:b-403v3h) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I realized just now -- why do we have such inverted logic? Currently, we have a child process that will return `0` (success) if there was a segfault, and will return `1` if there wasn't a segfault.

Instead, we can simply remove this SIGSEGV handler and rely on the fact that the child's segfault (due to wrong page permissions) will return a `status` that indicates a SIGSEGV failure. So we can remove `sigsegv_handler()` and instead modify the logic of `wait_for_child()` a bit. I would also rename to `wait_for_failing_child()`.
</blockquote></details>

Let me know if the new logic makes more sense.


<!-- Sent from Reviewable.io -->

2023-01-23 10:11 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM8HVaO1Ke7P6IeuRb0:-NMT5qV82vPs8zQxeEGC:bcqeh3o) ([raw file](https://github.com/gramineproject/gramine/blob/1831607c112aae8ac7e649e609f15fa5e83f3b2e/libos/test/regression/edmm.c#L81)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Let me know if the new logic makes more sense.
</blockquote></details>

Thanks, this looks much easier to follow now, and shorter.
___
*[`libos/test/regression/edmm.c` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5wBDBQQN8BE6mnf_:-NMT5wBDBQQN8BE6mnfa:bzao8x) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L4)):*
> ```C
> #include <err.h>
> #include <errno.h>
> #include <signal.h>
> ```

This include is probably not needed now? In general, please check if some includes can be removed from here.
___
*[`libos/test/regression/edmm.c` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT4p8q1VFSjGFoKmuk:-NMT4p8q1VFSjGFoKmul:b7e8ya2) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L17)):*
> ```C
>         err(1, "waitpid");
>     } else if (child_pid != pid) {
>         errx(1, "wrong child pid %d\n", child_pid);
> ```

Just noticed: there is no need to add `\n` (newline) in `err`/`errx` functions -- they do it by themselves. Please remove everywhere in this file.
___
*[`libos/test/regression/edmm.c` line 23 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT4USZC8w7Pzue_ZvY:-NMT4US_5v_Ooo68u-88:b-et4vol) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L23)):*
> ```C
>         errx(1, "child %d not killed (%d)\n", child_pid, status);
>     }
>     if ((status & 0x7f) != SIGSEGV) {
> ```

Instead of this bit arithmetic, you should use `WTERMSIG(status)`
___
*[`libos/test/regression/edmm.c` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5Io23lhvv7zOxG01:-NMT5Io23lhvv7zOxG02:bi1a13y) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L26)):*
> ```C
>          errx(1, "child died in an unknown manner: %d\n", status);
>     }
>     if (WEXITSTATUS(status) != 0) {
> ```

What's this check for? Please remove it (read `man waitpid` for more info on when to use these macros).
___
*[`libos/test/regression/edmm.c` line 38 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5Y05-udeOKhsJ6zG:-NMT5Y05-udeOKhsJ6zH:b-1g3nnq) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L38)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         int* ptr = (int*)foo;
> ```

Actually, why do we need `foo` function? Just remove it and instead use `(int*)test_segfault_on_write_to_rx_page`
___
*[`libos/test/regression/edmm.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5iL85A_G_7j6NEpW:-NMT5iL85A_G_7j6NEpX:b-fffv1) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L43)):*
> ```C
>         __asm__ volatile("movl $0, (%0)\n" : "=r"(ptr) : : "memory");
> 
>         exit(1); /* child must not survive the write to RX page above */
> ```

You should change to `exit(0)` now, since we reverted the logic
___
*[`libos/test/regression/edmm.c` line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5lKlA75chaJr773L:-NMT5lKlA75chaJr773M:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L57)):*
> ```C
>         __asm__ volatile("jmp *(%0)" : : "r" (rw_addr));
> 
>         exit(1); /* child must not survive exec attempt of RW page above */
> ```

ditto
___
*[`libos/test/regression/edmm.c` line 71 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5mMPCoGypCXN8HIw:-NMT5mMPCoGypCXN8HIx:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L71)):*
> ```C
>         __asm__ volatile("movb $104, (%0)\n" : "=r"(str) : : "memory");
> 
>         exit(1); /* child must not survive the write to RO page above */
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-01-23 11:23 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: 4 of 5 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/edmm.c` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5wBDBQQN8BE6mnf_:-NMTFOUZ6AjSPpWcCaZz:b-ko6706) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This include is probably not needed now? In general, please check if some includes can be removed from here.
</blockquote></details>

Yes, have removed both `errno.h` and `signal.h`.
___
*[`libos/test/regression/edmm.c` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT4p8q1VFSjGFoKmuk:-NMTFZaMBgl7lJc_k5_e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed: there is no need to add `\n` (newline) in `err`/`errx` functions -- they do it by themselves. Please remove everywhere in this file.
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 23 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT4USZC8w7Pzue_ZvY:-NMTGoXI59ocC0edNmyj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of this bit arithmetic, you should use `WTERMSIG(status)`
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5Io23lhvv7zOxG01:-NMTGtIp5CMSojoA_sw7:bdo9fnk) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's this check for? Please remove it (read `man waitpid` for more info on when to use these macros).
</blockquote></details>

Yes, this is not needed. I have removed it.
___
*[`libos/test/regression/edmm.c` line 38 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5Y05-udeOKhsJ6zG:-NMTGzIu2_QJm9BDWeol:b-t1mmg4) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we need `foo` function? Just remove it and instead use `(int*)test_segfault_on_write_to_rx_page`
</blockquote></details>

We don't need it, but it looked cleaner rather than overriding the same function name to show that we are attempting to write to `RX` only page.
___
*[`libos/test/regression/edmm.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5iL85A_G_7j6NEpW:-NMTIesp2_xRuY8F3M9x:b883x34) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should change to `exit(0)` now, since we reverted the logic
</blockquote></details>

why?  I think this should not matter for 2 reasons:
1. This `exit()` should never be called if the process properly terminated with `SIGSEGV`
2. Anything other than `SIGSEGV` should be treated as incorrect in our test case.
___
*[`libos/test/regression/edmm.c` line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5lKlA75chaJr773L:-NMTMLpY25zOidX4RmaY:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`libos/test/regression/edmm.c` line 71 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5mMPCoGypCXN8HIw:-NMTMNkS3kKLzK4KJZil:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2023-01-23 11:35 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 38 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5Y05-udeOKhsJ6zG:-NMTP6rf0oCzuw8gf1uq:b-9uthhg) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L38)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We don't need it, but it looked cleaner rather than overriding the same function name to show that we are attempting to write to `RX` only page.
</blockquote></details>

Nah, I think the current code is also clean.
___
*[`libos/test/regression/edmm.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMT5iL85A_G_7j6NEpW:-NMTPAgm9YucKPN1P2vA:bi7iim9) ([raw file](https://github.com/gramineproject/gramine/blob/1ad206c4f8bef8265233d9e686c07aaa383857da/libos/test/regression/edmm.c#L43)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

why?  I think this should not matter for 2 reasons:
1. This `exit()` should never be called if the process properly terminated with `SIGSEGV`
2. Anything other than `SIGSEGV` should be treated as incorrect in our test case.
</blockquote></details>

I see your point. Ok, I'm unblocking.


<!-- Sent from Reviewable.io -->

2023-01-24 00:24 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM31d2H0kOEQUFKDNr_:-NMVxdWr8Fpa0-lLc3Xi:b-80tlqk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Could you check inline asm here? You're much more of an expert in this.
</blockquote></details>

Sure.

___
___
*[`libos/test/regression/test_libos.py` line 1335 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6fgYBlG32SQ2PGUd:-NMW6fgYBlG32SQ2PGUe:b6ow1yi) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1335)):*
> ```Python
>     'On SGX v1, SIGSEGV handler cannot be implemented correctly, for lack of enclave page '
>     'permissions (all pages are RWX). So run only on gramine-direct and on gramine-sgx with EDMM.')
> class TC_92_SGX2_edmm(RegressionTestCase):
> ```

Ditto about arch.
___
*[`libos/test/regression/edmm.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM0sGhJ9PhXpYbKthsL:-NM0sGhKE8GAMBCH1NhU:b-e0r1g6) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

Should we add copyrights?
___
*[`libos/test/regression/edmm.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6PDf9tfO_IjtAfc8:-NMW6PDf9tfO_IjtAfc9:b2355xp) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

If we want to have it with assembly, why it's under `test/regression`? I think in this format, this test is arch specific.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMVz77e146vvxaOYO82:b-h2qbzx) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         int* ptr = (int*)test_segfault_on_write_to_rx_page;
> ```

I don't want to be picky, but how do you know that this is actually rx page?
For example, in [1] it's not. It's still a seg fault, but it's an x_page.
Wouldn't it be more clear to use mmap(2)?

[1] https://marc.info/?l=openbsd-ports&m=167413805228363&w=2
___
*[`libos/test/regression/edmm.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVyRU6ALTf1elJ-Hh0:-NMVyRU6ALTf1elJ-Hh1:b-4tmmfr) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L32)):*
> ```C
> 
>         /* *ptr = 0; */
>         __asm__ volatile("movl $0, (%0)\n" : "=r"(ptr) : : "memory");
> ```

Do we have any specific style for __asm__?
I prefer
```
__asm__ volatile("..."
    : ....
    : ....
    : ....
)
```
Dunno its only me.
___
*[`libos/test/regression/edmm.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW-EVn87ezRpudSLm7:-NMW-EVn87ezRpudSLm8:b5g41vz) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L32)):*
> ```C
> 
>         /* *ptr = 0; */
>         __asm__ volatile("movl $0, (%0)\n" : "=r"(ptr) : : "memory");
> ```

Why do we need assembly here?
```
volatile int *ptr = (int*)test_segfault_on_write_to_rx_page;;
*ptr = 0x00;
```

Isn't the same result?
Wouldn't it be better to use mmap(2)?
___
*[`libos/test/regression/edmm.c` line 44 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW2gAA-zIqC4RoUr5S:-NMW2gAA-zIqC4RoUr5T:bwdk18e) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L44)):*
> ```C
>     if (child_pid == 0) {
>         int on_stack_var = 5;
>         int* rw_addr = &on_stack_var;
> ```

What if the stack is executable on some platforms?
Is that possible?
___
*[`libos/test/regression/edmm.c` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW0zASEH6NMGFRWeyJ:-NMW0zAT2WkxeBtuc5Qc:bk2y89q) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L46)):*
> ```C
>         int* rw_addr = &on_stack_var;
> 
>         __asm__ volatile("jmp *(%0)" : : "r" (rw_addr));
> ```

Why do we need assembly?
```
	int a = 0xCCCCCCCC;
	int (*volatile ptr)(void) = (int (*)(void))&a;
	ptr();
```
___
*[`libos/test/regression/edmm.c` line 57 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW5z3iCbD76UG_O9a9:-NMW5z3iCbD76UG_O9aA:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L57)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         char* str = (char*)"Hello World!"; /* suppress const warning by casting to char* */
> ```

Ditto.
___
*[`libos/test/regression/edmm.c` line 60 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW3UZH2RYOUZrtHqvY:-NMW3UZH2RYOUZrtHqvZ:b-5hczm5) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L60)):*
> ```C
> 
>         /* str[0] = 'h'; */
>         __asm__ volatile("movb $104, (%0)\n" : "=r"(str) : : "memory");
> ```

Can it still be done with plain C?
___
*[`libos/test/regression/edmm.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW7I5x04u53xsWZaY7:-NMW7I5x04u53xsWZaY8:b-gstv4u) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L69)):*
> ```C
> 
> int main(void) {
>     pid_t child_pid = test_segfault_on_write_to_rx_page();
> ```

I find this approach quite inconsistent.
Why not check the negative value in wait_for_failling_child or in the test itself?
Or why not include `wait_for_failing_child` in the "test_*"?


<!-- Sent from Reviewable.io -->

2023-01-24 00:59 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @oshogbo, and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMWGYte-Ejo-eVSZ1Vl:-NMWGYte-Ejo-eVSZ1Vm:baob06o) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
> ```C
>     pid_t child_pid = fork();
>     if (child_pid == 0) {
>         int* ptr = (int*)test_segfault_on_write_to_rx_page;
> ```

Such a cast is UB in C, AFAIR.



_Code quote:_
```C
(int*)test_segfault_on_write_to_rx_page
```
___
*[`libos/test/regression/edmm.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW-EVn87ezRpudSLm7:-NMWFo3N9Wrr3CBB-hQ5:b-zdgxwk) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L32)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why do we need assembly here?
```
volatile int *ptr = (int*)test_segfault_on_write_to_rx_page;;
*ptr = 0x00;
```

Isn't the same result?
Wouldn't it be better to use mmap(2)?
</blockquote></details>

I don't really like using `volatile` for such things, their precise semantic isn't really documented, especially for UB-like cases (which dereferencing illegal memory is).
___
*[`libos/test/regression/edmm.c` line 44 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW2gAA-zIqC4RoUr5S:-NMWH26K81s9sJzJ81li:bu7f0f6) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L44)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What if the stack is executable on some platforms?
Is that possible?
</blockquote></details>

I think that was the point of this test - to assert that it isn't. But it does it in a really wrong way.
___
*[`libos/test/regression/edmm.c` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW0zASEH6NMGFRWeyJ:-NMWG9s68OyxdRZOeM6f:b-82tplc) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L46)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why do we need assembly?
```
	int a = 0xCCCCCCCC;
	int (*volatile ptr)(void) = (int (*)(void))&a;
	ptr();
```
</blockquote></details>

You don't have any guarantee that `a` / `on_stack_var` is on the stack. This whole test is just one big UB... Also, `ptr()` is a high-level C function call, it may do unintended things, not just a jump.
___
*[`libos/test/regression/edmm.c` line 54 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMWGkwVDfxCtsx0eYML:-NMWGkwVDfxCtsx0eYMM:b-1or07e) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L54)):*
> ```C
> }
> 
> static int test_segfault_on_write_to_ro_page(void) {
> ```

We already test this in PAL regression.


<!-- Sent from Reviewable.io -->

2023-01-24 08:34 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @vijaydhanraj)

___
*[`libos/test/regression/meson.build` line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXtv5N6Nhf2FbA_h1V:-NMXtv5N6Nhf2FbA_h1W:bnja4o5) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/meson.build#L17)):*
> ```Meson
>     'device_passthrough': {},
>     'double_fork': {},
>     'edmm': {},
> ```

Please move under `if sgx`
___
*[`libos/test/regression/test_libos.py` line 1332 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXu80o3OypVB0suwW_:-NMXu80o3OypVB0suwWa:bj3r9yq) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1332)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
> @unittest.skipUnless(not HAS_SGX or HAS_EDMM,
> ```

Let's just keep `HAS_EDMM`, there's not much reason to test non-SGX (gramine-direct) case.
___
*[`libos/test/regression/test_libos.py` line 1334 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXuEtsCxeHmwP3Ap6c:-NMXuEtsCxeHmwP3Ap6d:blygr4w) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1334)):*
> ```Python
> @unittest.skipUnless(not HAS_SGX or HAS_EDMM,
>     'On SGX v1, SIGSEGV handler cannot be implemented correctly, for lack of enclave page '
>     'permissions (all pages are RWX). So run only on gramine-direct and on gramine-sgx with EDMM.')
> ```

Remove the note about `on gramine-direct`. Let's make it explicit that this test is used for EDMM testing, not for anything else.
___
*[`libos/test/regression/test_libos.py` line 1335 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6fgYBlG32SQ2PGUd:-NMXu-dT8vE06WZu0ON4:b-54okvo) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1335)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto about arch.
</blockquote></details>

I suggest to just build/run this test **only on SGX**. Since even the name of the test suggests it's all about SGX (and thus about x86-64).
___
*[`libos/test/regression/tests.toml` line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXtfX0E-1OVpwuC1GN:-NMXtfX0E-1OVpwuC1GO:baeiu6e) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/tests.toml#L17)):*
> ```TOML
>   "device_passthrough",
>   "double_fork",
>   "edmm",
> ```

Please move under `[sgx]`
___
*[`libos/test/regression/tests_musl.toml` line 19 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXtkh78iRMOUhulQaF:-NMXtkh78iRMOUhulQaG:bsivj3o) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/tests_musl.toml#L19)):*
> ```TOML
>   "device_passthrough",
>   "double_fork",
>   "edmm",
> ```

Ditto (create `[sgx]`)
___
*[`libos/test/regression/edmm.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM0sGhJ9PhXpYbKthsL:-NMXqJa80X_UIVmxv8L-:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we add copyrights?
</blockquote></details>

+1
___
*[`libos/test/regression/edmm.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6PDf9tfO_IjtAfc8:-NMXqTkWAMFMUrkfjdFj:b-afpol8) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If we want to have it with assembly, why it's under `test/regression`? I think in this format, this test is arch specific.
</blockquote></details>

@oshogbo Where do you suggest to put it? I don't see other good candidates.

Also, this test is SGX-only (even the name is SGX-only). Which implies that it's arch specific. So I think it's fine.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMWGYte-Ejo-eVSZ1Vl:-NMXqzR052hPp6NddBIE:b-1c91l3) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Such a cast is UB in C, AFAIR.
</blockquote></details>

Yeah, it's better to not have a cast to int, that's true. Let's just have a type of `ptr` being a proper function-pointer type.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMXr8Ym0uQgFWhozFrs:b-modjif) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't want to be picky, but how do you know that this is actually rx page?
For example, in [1] it's not. It's still a seg fault, but it's an x_page.
Wouldn't it be more clear to use mmap(2)?

[1] https://marc.info/?l=openbsd-ports&m=167413805228363&w=2
</blockquote></details>

Well, the main point is that this page is not writable. We can rename to `_x_page`, I don't mind.
___
*[`libos/test/regression/edmm.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVyRU6ALTf1elJ-Hh0:-NMXrIsY7jFojKWhNfMM:b5rzbiu) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L32)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Do we have any specific style for __asm__?
I prefer
```
__asm__ volatile("..."
    : ....
    : ....
    : ....
)
```
Dunno its only me.

</blockquote></details>

We don't have any specific style. But I don't see a need to write 5 lines for a simple one-liner asm.
___
*[`libos/test/regression/edmm.c` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW-EVn87ezRpudSLm7:-NMXrQYx4oy2PI3xl6_X:boedwe0) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't really like using `volatile` for such things, their precise semantic isn't really documented, especially for UB-like cases (which dereferencing illegal memory is).
</blockquote></details>

Yeah, `volatile` doesn't really have any semantics/guarantees these days. It's safer to write in asm.
___
*[`libos/test/regression/edmm.c` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW0zASEH6NMGFRWeyJ:-NMXrj_NA3qlZyjakiyC:b-lob20x) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You don't have any guarantee that `a` / `on_stack_var` is on the stack. This whole test is just one big UB... Also, `ptr()` is a high-level C function call, it may do unintended things, not just a jump.
</blockquote></details>

Why don't we have a guarantee that `on_stack_var` is on the stack? This var can b [...]

2023-01-24 09:40 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6PDf9tfO_IjtAfc8:-NMY7rqECT3igZPKoiq-:byqw3zb) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Where do you suggest to put it? I don't see other good candidates.

Also, this test is SGX-only (even the name is SGX-only). Which implies that it's arch specific. So I think it's fine.
</blockquote></details>

Something similar to `libos/test/abi/x86_64` ?
But I'm not blocking.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMY80cd4YAllmFoxetn:b8mj9yb) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, the main point is that this page is not writable. We can rename to `_x_page`, I don't mind.
</blockquote></details>

So maybe my main problem is - I don't know what this test test.
Does it test different segments of code - which code suggests, or different page flags which function name suggests?


<!-- Sent from Reviewable.io -->

2023-01-24 09:41 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMY8gz45DVyFOqu2sUa:b-b9goxh) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So maybe my main problem is - I don't know what this test test.
Does it test different segments of code - which code suggests, or different page flags which function name suggests?
</blockquote></details>

s/segment of code/segment of the process


<!-- Sent from Reviewable.io -->

2023-01-24 09:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6PDf9tfO_IjtAfc8:-NMYC1gc6den1xbP_uzA:b5246gs) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Something similar to `libos/test/abi/x86_64` ?
But I'm not blocking.
</blockquote></details>

Well, we didn't implement this hierarchy for `libos/test/regression` -- which is probably a bug on our side. But this is for an orthogonal separate PR.

Instead, in regression tests, we have `[sgx]` and `[arch.x86_64]` helpers...
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMYCNa441aeBVyA7V8O:bx1r2td) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
> different page flags which function name suggests?

This. The test tests page flags. Trying to write into a code segment is just a convenient simplification, to not deal with `mmap` + `mprotect`.


<!-- Sent from Reviewable.io -->

2023-01-24 13:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: 0 of 5 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @vijaydhanraj)

___
*[`libos/test/regression/test_libos.py` line 1332 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXu80o3OypVB0suwW_:-NMYkjQn7F9AXMeLVROj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's just keep `HAS_EDMM`, there's not much reason to test non-SGX (gramine-direct) case.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1334 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXuEtsCxeHmwP3Ap6c:-NMYki9K8DFb9ahyLmzE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove the note about `on gramine-direct`. Let's make it explicit that this test is used for EDMM testing, not for anything else.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1335 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW6fgYBlG32SQ2PGUd:-NMYkgqE6o-vosv7NiCR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/test_libos.py#L1335)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to just build/run this test **only on SGX**. Since even the name of the test suggests it's all about SGX (and thus about x86-64).
</blockquote></details>

Done.
___
*[`libos/test/regression/tests.toml` line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXtfX0E-1OVpwuC1GN:-NMYlIcr1eIDjH8xm_Ei:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/tests.toml#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move under `[sgx]`
</blockquote></details>

Done.
___
*[`libos/test/regression/tests_musl.toml` line 19 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMXtkh78iRMOUhulQaF:-NMYmQcy2F-483Aj8cvy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/tests_musl.toml#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ditto (create `[sgx]`)
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/1120#-NM0sGhJ9PhXpYbKthsL:-NMYZ6oxEShDHnGpb9ay:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c28bd65b56de91eb5e0ebeeacfbd3eb0b740e0f1/libos/test/regression/edmm.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMVz77e146vvxaOYO81:-NMYZpu2BHZXJfGuClVB:b-s3tw5i) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> different page flags which function name suggests?

This. The test tests page flags. Trying to write into a code segment is just a convenient simplification, to not deal with `mmap` + `mprotect`.
</blockquote></details>

Thanks @oshogbo for the link. I will rename this test to `_x_page` as suggested by Dmitrii.
___
*[`libos/test/regression/edmm.c` line 29 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMWGYte-Ejo-eVSZ1Vl:-NMYd80H6kbjC8XvPNDL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, it's better to not have a cast to int, that's true. Let's just have a type of `ptr` being a proper function-pointer type.
</blockquote></details>

Done.
___
*[`libos/test/regression/edmm.c` line 69 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW7I5x04u53xsWZaY7:-NMYjGkG2oHdesFSBQf9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, let's move these `wait_for_failing_child()` calls inside the tests themselves.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-24 13:42 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2023-01-27 00:26 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 31 at r7](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMkYpGQ4Kj_Kb57JWjN:-NMkYpGQ4Kj_Kb57JWjO:b-by2u1x) ([raw file](https://github.com/gramineproject/gramine/blob/08afd07f1a44521d26f1803ab83a249a808900d6/libos/test/regression/edmm.c#L31)):*
> ```C
> }
> 
> static void test_segfault_on_write_to_x_page(void) {
> ```

Ok, I would name this test  `test_segfault_on_execute_stack`.
___
*[`libos/test/regression/edmm.c` line 48 at r7](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMkZK-lDK6K__oLarY4:-NMkZK-lDK6K__oLarY5:bm4we2s) ([raw file](https://github.com/gramineproject/gramine/blob/08afd07f1a44521d26f1803ab83a249a808900d6/libos/test/regression/edmm.c#L48)):*
> ```C
> }
> 
> static void test_segfault_on_exec_to_rw_page(void) {
> ```

I would name this test_segfault_on_execute_stack;
___
*[`libos/test/regression/edmm.c` line 54 at r7](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMkZPYLB4_VUHpDe5yt:-NMkZPYLB4_VUHpDe5yu:bakuy1k) ([raw file](https://github.com/gramineproject/gramine/blob/08afd07f1a44521d26f1803ab83a249a808900d6/libos/test/regression/edmm.c#L54)):*
> ```C
>         int* rw_addr = &on_stack_var;
> 
>         __asm__ volatile("jmp *(%0)" : : "r" (rw_addr));
> ```

I think @mkow suggests that with a different set of compiler flags or something, the compiler can significantly change this part of the code, as this UB.
So maybe something like this?
```
	__asm__ volatile(
		"movq $0xCCCCCCCCCCCCCCCC, %rax\n"
		"pushq %rax\n"
		"movq %rsp, %rax\n"
		"jmp *%rax"
	);

```


<!-- Sent from Reviewable.io -->

2023-01-27 00:59 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW0zASEH6NMGFRWeyJ:-NMkiVnyE627VOUysXoc:b-sgxgf0) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L46)):*
> Why don't we have a guarantee that `on_stack_var` is on the stack? 

Where and who guarantees that it is? ;)

Anyways, the current version is completely broken, if I'm reading it correctly it throws an exception if no-exec works, but... also throws an exception when it doesn't, because we start executing random garbage from the stack (starting from 0x05, 0x00, 0x00...).
___
*[`libos/test/regression/edmm.c` line 54 at r7](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMkZPYLB4_VUHpDe5yt:-NMkhck0CcJA8dcR9Pu9:bjdwjr7) ([raw file](https://github.com/gramineproject/gramine/blob/08afd07f1a44521d26f1803ab83a249a808900d6/libos/test/regression/edmm.c#L54)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think @mkow suggests that with a different set of compiler flags or something, the compiler can significantly change this part of the code, as this UB.
So maybe something like this?
```
	__asm__ volatile(
		"movq $0xCCCCCCCCCCCCCCCC, %rax\n"
		"pushq %rax\n"
		"movq %rsp, %rax\n"
		"jmp *%rax"
	);

```
</blockquote></details>

See https://github.com/gramineproject/gramine/pull/1146, Dmitrii does it correctly there (and in a simpler way).


<!-- Sent from Reviewable.io -->

2023-01-27 09:21 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1120)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @vijaydhanraj)

___
*[`libos/test/regression/edmm.c` line 46 at r6](https://reviewable.io/reviews/gramineproject/gramine/1120#-NMW0zASEH6NMGFRWeyJ:-NMmWlUU9nw1v3hdH5Yq:bbkw0bv) ([raw file](https://github.com/gramineproject/gramine/blob/65f1fe9787d3b013a3b3731becec703efc22aaae/libos/test/regression/edmm.c#L46)):*
>  if I'm reading it correctly it throws an exception if no-exec works, but... also throws an exception when it doesn't

Yes, you're right, this "fails due to some other reasons" was a problem in this PR. Anyway, I'm closing this PR to not have any confusion, and we'll continue with #1146.


<!-- Sent from Reviewable.io -->

2023-01-27 09:21 UTC, dimakuv commented
Supersede by #1146, closing.

2023-01-27 09:21 UTC, closed without merging