[PAL/Linux-SGX] Set optional SGX features if available on machine
gramineproject/gramine pull request #1122
Opened 2023-01-16 12:09 UTC by dimakuv

## Description of the changes 

Commits https://github.com/gramineproject/gramine/commit/e73da5e2a0b77c5ea88585bb52a75b9d4e65c55b andhttps://github.com/gramineproject/gramine/commit/95d49502db1dd816fca0266fefb12c185269e7d3 removed/deprecated the call to `gramine-sgx-get-token` Python script on non-OOT platforms (i.e., on machines with SGX FLC).

However, that Python script doesn't only fetch the token from AESM but also sets optional SGX features if available on current machine, see `sgx_get_token.py:get_optional_sgx_features()`. With the two commits above, Gramine stopped setting these optional SGX features, making some apps slow and some apps faililing explicitly on e.g. AVX instructions (because their use was not enabled in XFRM attrs).

This commit fixes this bug, by reproducing
`sgx_get_token.py:get_optional_sgx_features()` functionality in Gramine C code for non-OOT (FLC) platforms.

Fixes #1121.

For context, see: https://github.com/gramineproject/gramine/blob/1aab0f79729f0c8a4852150a985be527991a06bc/python/graminelibos/sgx_get_token.py#L11-L41

## How to test this PR? 

I manually verified that previously-failing apps (like TensorFlow which required AVX) run correctly now.

2023-01-16 12:15 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLuV8Ch8pYerWbXjcGw:-NLuV8Ch8pYerWbXjcGx:b-xx33mf) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L90)):*
> ```C
>     ssize_t len;
> 
>     len = read_file_buffer("/proc/cpuinfo", buf, sizeof(buf) - 1);
> ```

Can't you get this info just from `cpuid()` function (like `is_wrfsbase_supported()` below)?


<!-- Sent from Reviewable.io -->

2023-01-16 12:34 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLuV8Ch8pYerWbXjcGw:-NLuWKHF41xTzSUs9OYC:b4yfuyb) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess I could, but why bother? This is untrusted part of PAL anyway, and I wanted to mirror the logic in `sgx_get_token.py:get_optional_sgx_features()`.
</blockquote></details>

To not parse files in C and not have to handle errors? The two things that C is worst at?

Here's a greppable list of those flags, if you need to check leafs, registers and bits: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/arch/x86/kcpuid/cpuid.csv.


<!-- Sent from Reviewable.io -->

2023-01-16 12:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLuV8Ch8pYerWbXjcGw:-NLudSlOAOKv8t0Yw1v2:b5frpwy) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L90)):*
Thanks for the list.

> To not parse files in C and not have to handle errors? The two things that C is worst at?

I wouldn't call my current code complex, the parsing of `/proc/cpuinfo` is pretty simple...

Let's wait on @mkow's opinion, and I will oblige.


<!-- Sent from Reviewable.io -->

2023-01-16 15:18 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv7gHD0FQeWeVRCcjd:-NLv7gHE-i5pv_Wr5dhP:b-mm4uw9) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L109)):*
> ```C
> 
>     /* make the end of "flags" line in the form of " \0" (space + end-of-string), for easy search */
>     char* end_of_flags_line = strchr(ptr, '\n');
> ```

Can `flags` be the last element in the file?


<!-- Sent from Reviewable.io -->

2023-01-16 15:20 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv9eAC3xo4y85tp5Vm:-NLv9eAC3xo4y85tp5Vn:bok4g2x) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L85)):*
> ```C
> 
> static int get_optional_sgx_features(uint64_t xfrm, uint64_t xfrm_mask, uint64_t* out_xfrm) {
>     /* Must find CPU features in "flags:" of /proc/cpuinfo. Although the whole file might not fit in
> ```

Can we read only part of `flags`?


<!-- Sent from Reviewable.io -->

2023-01-16 15:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv9eAC3xo4y85tp5Vm:-NLvA9mN4ExFXh6rmNWY:bf1my8j) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L85)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Can we read only part of `flags`?
</blockquote></details>

If we read only part of `flags`, then we won't find `\n` (so `end_of_flags_line == NULL`) and we kill Gramine.

I mean, theoretically we can, if `/proc/cpuinfo` has more than 2048 chars before the end of the `flags` line... This is not currently possible in practice, but in the future... Hm, maybe I really should move to querying CPUID leaves?
___
*[`pal/src/host/linux-sgx/host_framework.c` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv7gHD0FQeWeVRCcjd:-NLvAWLJ68KpS6FldT1l:bdafmf5) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L109)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Can `flags` be the last element in the file?
</blockquote></details>

But all lines in `/proc/cpuinfo` must end with `\n`, so it shouldn't matter.


<!-- Sent from Reviewable.io -->

2023-01-16 15:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv7gHD0FQeWeVRCcjd:-NLvB6Vl9lHKZGaLloWt:b-uyzqos) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But all lines in `/proc/cpuinfo` must end with `\n`, so it shouldn't matter.
</blockquote></details>

I guess the question is, what happens to `strstr(" flag ")` if the flag is the last one on the line: is there a right-hand space to match?


<!-- Sent from Reviewable.io -->

2023-01-16 15:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv7gHD0FQeWeVRCcjd:-NLvBrA378QUnL7Um4DV:b-aujr8o) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L109)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I guess the question is, what happens to `strstr(" flag ")` if the flag is the last one on the line: is there a right-hand space to match?
</blockquote></details>

Yes, that's why I have a line below: `end_of_flags_line[0] = ' ';`

So I add the space at the end of the `flags : ...` line, for exactly this reason.


<!-- Sent from Reviewable.io -->

2023-01-16 18:46 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @oshogbo, and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLvrtcX3oOSUh0fpY06):*
typo



_Code quote:_
```
faililing
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLuV8Ch8pYerWbXjcGw:-NLvtHaE79AA3JeGtC3P:b-62q2fu) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for the list.

> To not parse files in C and not have to handle errors? The two things that C is worst at?

I wouldn't call my current code complex, the parsing of `/proc/cpuinfo` is pretty simple...

Let's wait on @mkow's opinion, and I will oblige.
</blockquote></details>

I'd prefer CPUID, seems simpler and more solid - here there's a risk of hitting this hardcoded size limit, on one of the machines I'm already at 1.5 kB, so it could break in the future. Overall I agree with @woju, parsing files and error handling is a nightmare in C :)


<!-- Sent from Reviewable.io -->

2023-01-17 09:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLvrtcX3oOSUh0fpY06):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Will do at final rebase.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv9eAC3xo4y85tp5Vm:-NLyz1k0DlNF-0MA0L4Z:b316mee) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If we read only part of `flags`, then we won't find `\n` (so `end_of_flags_line == NULL`) and we kill Gramine.

I mean, theoretically we can, if `/proc/cpuinfo` has more than 2048 chars before the end of the `flags` line... This is not currently possible in practice, but in the future... Hm, maybe I really should move to querying CPUID leaves?
</blockquote></details>

I moved to CPUID, not relevant anymore
___
*[`pal/src/host/linux-sgx/host_framework.c` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLuV8Ch8pYerWbXjcGw:-NLyz4d-80k6sWqSAANF:bgrh9ao) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L90)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer CPUID, seems simpler and more solid - here there's a risk of hitting this hardcoded size limit, on one of the machines I'm already at 1.5 kB, so it could break in the future. Overall I agree with @woju, parsing files and error handling is a nightmare in C :)
</blockquote></details>

Done.

Ok, I admit the new code is much cleaner.

Why I objected that much is because now we have a discrepancy in logic between this C code and `sgx_get_token.py:get_optional_sgx_features()` Python code. But hopefully the latter will be removed completely one day.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLv7gHD0FQeWeVRCcjd:-NLyyzUeAFXiyg2b8efI:b316mee) ([raw file](https://github.com/gramineproject/gramine/blob/31f132a0dd8bb0026b6903bbb75d6251a2aed0fb/pal/src/host/linux-sgx/host_framework.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, that's why I have a line below: `end_of_flags_line[0] = ' ';`

So I add the space at the end of the `flags : ...` line, for exactly this reason.
</blockquote></details>

I moved to CPUID, not relevant anymore


<!-- Sent from Reviewable.io -->

2023-01-17 10:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLzC1Ab-J7KiZ_0SynF:-NLzC1Ab-J7KiZ_0SynG:bwpp0mb) (no related file):*
FYI: I verified that in our CI, only `edmm` pipeline executes the `avx` test (successfully), and the other pipelines skip this test.

___


<!-- Sent from Reviewable.io -->

2023-01-17 10:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 0 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLzEqWH6BUcm__sgBFN:-NLzEqWH6BUcm__sgBFO:brdq6mv) ([raw file](https://github.com/gramineproject/gramine/blob/f9e6222aa694dee7b34a87c8ee0735bb5f5ab146/pal/src/host/linux-sgx/host_framework.c#L99)):*
> ```C
>         {SGX_XFRM_AVX512, { .leaf = 7, .subleaf = 0, .reg = CPUID_WORD_EBX, .bit = 16 }},
>         {SGX_XFRM_PKRU,   { .leaf = 7, .subleaf = 0, .reg = CPUID_WORD_ECX, .bit = 3 }},
>         {SGX_XFRM_AMX,    { .leaf = 7, .subleaf = 0, .reg = CPUID_WORD_EDX, .bit = 24 }},
> ```

If #1125 is merged first, we should replace
- `1` -> `FEATURE_FLAGS_LEAF`
- `7` -> `EXTENDED_FEATURE_FLAGS_LEAF`

Also we should check if there are any other usages of `cpuid(1, ...)` or `cpuid(7, ...)` and also replace with macros.


<!-- Sent from Reviewable.io -->

2023-01-17 10:47 UTC, woju approved these changes
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-01-18 14:39 UTC, mkow requested changes
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`.ci/linux-sgx-edmm.jenkinsfile` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/1122#-NM4FN0a3g4hElDLgy15:-NM4FN0a3g4hElDLgy16:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f9e6222aa694dee7b34a87c8ee0735bb5f5ab146/.ci/linux-sgx-edmm.jenkinsfile#L4)):*
> ```
>     checkout scm
> 
>     env.AVX = '1'  // EDMM-capable machines in our CI always have Intel AVX
> ```





_Suggestion:_
```
have AVX
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 97 at r3](https://reviewable.io/reviews/gramineproject/gramine/1122#-NM4Irif2NAnXbp4vAyn:-NM4Irif2NAnXbp4vAyo:b-s9ouh) ([raw file](https://github.com/gramineproject/gramine/blob/f9e6222aa694dee7b34a87c8ee0735bb5f5ab146/pal/src/host/linux-sgx/host_framework.c#L97)):*
> ```C
>         {SGX_XFRM_AVX,    { .leaf = 1, .subleaf = 0, .reg = CPUID_WORD_ECX, .bit = 28 }},
>         {SGX_XFRM_MPX,    { .leaf = 7, .subleaf = 0, .reg = CPUID_WORD_EBX, .bit = 14 }},
>         {SGX_XFRM_AVX512, { .leaf = 7, .subleaf = 0, .reg = CPUID_WORD_EBX, .bit = 16 }},
> ```

This is actually AVX512F, we should rename it.



_Code quote:_
```C
SGX_XFRM_AVX512
```
___
*[`pal/src/host/linux-sgx/host_framework.c` line 110 at r3](https://reviewable.io/reviews/gramineproject/gramine/1122#-NM4JJaKB1nfUDK455Dh:-NM4JJaKB1nfUDK455Di:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f9e6222aa694dee7b34a87c8ee0735bb5f5ab146/pal/src/host/linux-sgx/host_framework.c#L110)):*
> ```C
>             uint32_t values[4];
>             cpuid(xfrm_flags[i].cpuid.leaf, xfrm_flags[i].cpuid.subleaf, values);
>             if (values[xfrm_flags[i].cpuid.reg] & (1 << xfrm_flags[i].cpuid.bit))
> ```





_Suggestion:_
```C
1u << xfrm_flags[i].cpuid.bit
```


<!-- Sent from Reviewable.io -->

2023-01-18 17:07 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (Blender download was too slow, timed out)

2023-01-23 11:37 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122#-:-NMTPoNhAsK0gOfhQWWb:bnfp4nl)* status: 6 of 8 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`libos/test/regression/avx.c` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1122#-NMTPTkFCsk1-D_60XxF:-NMTPTkFCsk1-D_60XxG:b-a2xouq) ([raw file](https://github.com/gramineproject/gramine/blob/a5a88db6355a24c06f4356a7e767e79c731c295d/libos/test/regression/avx.c#L1)):*
> ```C
> /*
> ```

Copyrights?


<!-- Sent from Reviewable.io -->

2023-01-23 11:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 5 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`libos/test/regression/avx.c` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1122#-NMTPTkFCsk1-D_60XxF:-NMTQpAH45IjVAImN2C_:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a5a88db6355a24c06f4356a7e767e79c731c295d/libos/test/regression/avx.c#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Copyrights?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-23 12:03 UTC, woju approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2023-01-24 10:04 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-01-24 10:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLvrtcX3oOSUh0fpY06):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do at final rebase.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_framework.c` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1122#-NLzEqWH6BUcm__sgBFN:-NMYFuTo1J3jf8XblxAm:bc8htwp) ([raw file](https://github.com/gramineproject/gramine/blob/f9e6222aa694dee7b34a87c8ee0735bb5f5ab146/pal/src/host/linux-sgx/host_framework.c#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If #1125 is merged first, we should replace
- `1` -> `FEATURE_FLAGS_LEAF`
- `7` -> `EXTENDED_FEATURE_FLAGS_LEAF`

Also we should check if there are any other usages of `cpuid(1, ...)` or `cpuid(7, ...)` and also replace with macros.
</blockquote></details>

So this PR will be merged now, before #1125. I will leave the comment in that other PR to update the leaf numbers on rebase.


<!-- Sent from Reviewable.io -->

2023-01-24 10:30 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1122)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-24 10:51 UTC, merged