[PAL/Linux-SGX] Enforce AES-NI, XSAVE and RDRAND
gramineproject/gramine pull request #1125
Opened 2023-01-17 02:33 UTC by mkow

## Description of the changes 

*This PR fixes a security issue*

These CPU features are required for correct and secure use of Gramine:
- XSAVE is used internally by Gramine,
- AES-NI and RDRAND are required, otherwise some crypto libraries (e.g. mbedtls) silently switch to side-channel-prone software implementations of crypto algorithms.

This PR ensures that we always have them enabled and report as such to the application running under Linux-SGX PAL. Additionally, it patches the mbedtls version we ship to refuse to ever use non-AES-NI (i.e. vulnerable) AES implementation.

Kudos to Corentin Lauverjat from Mithril Security for reporting the bug!

p.s. We don't have to fix `/proc/cpuinfo`, as it already gets the flags from CPUID. See: https://github.com/gramineproject/gramine/blob/1aab0f79729f0c8a4852150a985be527991a06bc/libos/src/arch/x86_64/libos_cpuid.c#L285

Fixes #1014.

## How to test this PR? 

Try faking CPUID results in `sgx_ocall_cpuid()`, then the same with disabled sanitization to check if the patched mbedtls fails (as it should now).

2023-01-17 02:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: 0 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLx_BeiDdP6V_OxoHJo):*
@clauverjat: Please check if that's how you want to be credited :)



_Code quote:_
```
Corentin Lauverjat from Mithril Security
```


<!-- Sent from Reviewable.io -->

2023-01-17 10:36 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzG34O6O0s2VAyAHLN):*
Is this PS important? I feel like it's redundant, since of course our LibOS emulation of `/proc/cpuinfo` populates the flags based on `PalGetCpuid()` (or however the func is called).
___
*[`common/include/arch/x86_64/cpu.h` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzGGpO-abP82mZEc-6:-NLzGGpO-abP82mZEc-7:b1ceqh5) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/common/include/arch/x86_64/cpu.h#L43)):*
> ```objc
> #define INTEL_SGX_LEAF              0x12 /* Intel SGX Capabilities */
> #define AMX_TILE_INFO_LEAF          0x1D
> #define AMX_TMUL_INFO_LEAF          0x1E
> ```

I feel like we have some hard-coded numbers (like `cpuid(7, ...)`) in our codebase, we could also fix those places in this PR.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1147 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzIHiLDOC1j_VNe2Am:-NLzIHiLDOC1j_VNe2An:b-xwar7v) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1147)):*
> ```C
>                   "in the host kernel. Please update your system.");
>         return -EINVAL;
>     }
> ```

I would prefer an empty line, since these are two independent checks.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHXCv2iXtnD7Aplw6:-NLzHXCv2iXtnD7Aplw7:br7yfes) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1157)):*
> ```C
>     else if (!(values[CPUID_WORD_ECX] & (1 << 30)))
>         missing = "RDRAND";
>     if (missing) {
> ```

Now you only report one of the instructions at a time. Could we concatenate strings, to report all missing features?
___
*[`pal/src/host/linux-sgx/host_main.c` line 1160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHiBL9bj1hdkWtzQQ:-NLzHiBL9bj1hdkWtzQR:b8lhi2l) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1160)):*
> ```C
>         log_error("Gramine with Linux-SGX backend requires %s CPU instruction(s). "
>                   "Please upgrade your hardware.", missing);
>         return -EINVAL;
> ```

Well, so what do we do with those CPUs that may have `AESNI` disabled? I mean this case: https://github.com/gramineproject/gramine/issues/1014#issuecomment-1300505308

The idea for now is to implement this hard requirement, and if there will be an issue with this (for some real customers and real workloads), relax it by adding `sgx.require_aesni` manifest option, as Borys suggested: https://github.com/gramineproject/gramine/issues/1014#issuecomment-1297345093

(If yes, then `sgx.require_aesni` should be `true` by default.)
___
*[`pal/src/host/linux-sgx/host_main.c` line 1188 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzH74o29LqaMKl2jXm:-NLzH74o29LqaMKl2jXn:bll37gz) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1188)):*
> ```C
>     probe_stack(THREAD_STACK_SIZE / PAGE_SIZE);
> ```

Since we're here, can we remove this empty line?
___
*[`pal/src/host/linux-sgx/host_main.c` line 1277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzICuM53zlstTjOaXn:-NLzICuN6CuYhg1t6n9A:bxa6jkw) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1277)):*
> ```C
>     if (ret < 0) {
>         log_error("load_enclave() failed with error: %s", unix_strerror(ret));
>         return ret;
> ```

Oh my.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzGvbl27oHDgJLQf8r:-NLzGvbl27oHDgJLQf8s:b-aoja6k) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/pal_misc.c#L197)):*
> ```C
>          *
>          * On hosts which really don't support these, the untrusted PAL should emit an error and
>          * refuse to start.
> ```

Maybe add `see host_main.c: verify_hw_requirements()`?


<!-- Sent from Reviewable.io -->

2023-01-17 15:17 UTC, mkow commented
Jenkins, retest this please (some weird FS issues triggered, seem unrelated to the PR - e.g. `rename_unlink: rename: Permission denied`)

2023-01-17 16:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: 9 of 16 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzG34O6O0s2VAyAHLN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this PS important? I feel like it's redundant, since of course our LibOS emulation of `/proc/cpuinfo` populates the flags based on `PalGetCpuid()` (or however the func is called).
</blockquote></details>

I think so, especially that AFAIR some time ago Gramine just forwarded these flags from the host's `/proc/cpuinfo` :) So, I had to check this part manually and ensure that it's secure when writing this PR.
___
*[`common/include/arch/x86_64/cpu.h` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzGGpO-abP82mZEc-6:-NM-Ofl5ECEeP4N5JGMA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/common/include/arch/x86_64/cpu.h#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I feel like we have some hard-coded numbers (like `cpuid(7, ...)`) in our codebase, we could also fix those places in this PR.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1147 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzIHiLDOC1j_VNe2Am:-NM-OrkXDgtAI_lfSKRZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer an empty line, since these are two independent checks.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHXCv2iXtnD7Aplw6:-NM-P2eD-BUBaZVlWuei:bc9o4vz) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you only report one of the instructions at a time. Could we concatenate strings, to report all missing features?
</blockquote></details>

I know, but string operations in C are so PITA that it's IMO not worth here.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHiBL9bj1hdkWtzQQ:-NM-PG-FDYmgW3v-vosm:bxf5b5h) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, so what do we do with those CPUs that may have `AESNI` disabled? I mean this case: https://github.com/gramineproject/gramine/issues/1014#issuecomment-1300505308

The idea for now is to implement this hard requirement, and if there will be an issue with this (for some real customers and real workloads), relax it by adding `sgx.require_aesni` manifest option, as Borys suggested: https://github.com/gramineproject/gramine/issues/1014#issuecomment-1297345093

(If yes, then `sgx.require_aesni` should be `true` by default.)
</blockquote></details>

We should refuse to start without AES-NI, as this PR does. If someone disabled AES-NI in the BIOS, then they should re-enable it to use Gramine.
There's no way really to use Gramine securely without AES-NI, as we learned from the discussion under #1014.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1188 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzH74o29LqaMKl2jXm:-NM-PevSC2jHWwJ-cb8Y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1188)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, can we remove this empty line?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzICuM53zlstTjOaXn:-NM-Pj9BBK5E9WSlcQtM:b32vhw) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1277)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh my.
</blockquote></details>

:)
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzGvbl27oHDgJLQf8r:-NM-PwHOAD-HQDQDXwpc:b-674ab8) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/pal_misc.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add `see host_main.c: verify_hw_requirements()`?
</blockquote></details>

I don't like linking to exact places in different files if not very needed, they quickly turn into dangling references :) But if you really prefer it then I can add it.


<!-- Sent from Reviewable.io -->

2023-01-17 19:03 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzG34O6O0s2VAyAHLN):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think so, especially that AFAIR some time ago Gramine just forwarded these flags from the host's `/proc/cpuinfo` :) So, I had to check this part manually and ensure that it's secure when writing this PR.
</blockquote></details>

OK
___
*[`pal/src/host/linux-sgx/host_main.c` line 1157 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHXCv2iXtnD7Aplw6:-NM062EiAJrTtNVkuewx:bqy67xj) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know, but string operations in C are so PITA that it's IMO not worth here.
</blockquote></details>

Fair enough
___
*[`pal/src/host/linux-sgx/host_main.c` line 1160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzHiBL9bj1hdkWtzQQ:-NM066B_2c-MAYwrDKuI:b-391un) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/host_main.c#L1160)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should refuse to start without AES-NI, as this PR does. If someone disabled AES-NI in the BIOS, then they should re-enable it to use Gramine.
There's no way really to use Gramine securely without AES-NI, as we learned from the discussion under #1014.
</blockquote></details>

Ok, agreed.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLzGvbl27oHDgJLQf8r:-NM06HqS9XPmPYe4zy7u:b-iaieta) ([raw file](https://github.com/gramineproject/gramine/blob/9672bf70f3014646bfbe5e302a8cc6b25394465d/pal/src/host/linux-sgx/pal_misc.c#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like linking to exact places in different files if not very needed, they quickly turn into dangling references :) But if you really prefer it then I can add it.
</blockquote></details>

Ok, I guess it's easy to find by grepping on e.g. `AESNI`.


<!-- Sent from Reviewable.io -->

2023-01-24 10:14 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 111 at r2](https://reviewable.io/reviews/gramineproject/gramine/1125#-NMYGG7058IE6exeg_L3:-NMYGG7058IE6exeg_L4:bj4g6z2) ([raw file](https://github.com/gramineproject/gramine/blob/0cc3d36e800eaea7b3d64f7cd2b6feac90d19955/pal/src/host/linux-sgx/host_framework.c#L111)):*
> ```C
> bool is_wrfsbase_supported(void) {
>     uint32_t cpuinfo[4];
>     cpuid(EXTENDED_FEATURE_FLAGS_LEAF, 0, cpuinfo);
> ```

On rebase, this file will have `xfrm_flags` with explicit `leaf = 1`, `leaf = 7`, etc. This is because of the PR #1122 

So on final rebase, these leaves should be changed from hard-coded numbers to use macros.


<!-- Sent from Reviewable.io -->

2023-01-27 10:17 UTC, clauverjat commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)_ status: 0 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)
> 
> _[`-- commits` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1125#-NLx_BeiDdP6V_OxoHJo):_ @clauverjat: Please check if that's how you want to be credited :)
> 
> _Code quote:_
> 
> ```
> Corentin Lauverjat from Mithril Security
> ```

It works for me! Glad to see that the vulnerability is being fixed.

2023-01-27 15:21 UTC, woju reviewed
> Reviewed 11 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: 11 of 27 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2023-01-27 16:20 UTC, dimakuv approved these changes
> Reviewed 11 of 27 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)

___
*[`pal/src/host/linux/pal_main.c` line 136 at r4](https://reviewable.io/reviews/gramineproject/gramine/1125#-NMo0lBb-CN5o9Z3BC2_:-NMo0lBb-CN5o9Z3BC2a:bg3cpi0) ([raw file](https://github.com/gramineproject/gramine/blob/3cda8edd5364e0fa45662ba4e7f4d3ce2b2d357f/pal/src/host/linux/pal_main.c#L136)):*
> ```C
>         missing = "AES-NI";
>     else if (!(values[CPUID_WORD_ECX] & (1 << 26)))
>         missing = "XSAVE";
> ```

Do you require `XSAVE` because LibOS uses xsave instructions anyway? Not blocking, so you can do final rebase.


<!-- Sent from Reviewable.io -->

2023-01-27 16:34 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: 10 of 27 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[`pal/src/host/linux/pal_main.c` line 136 at r4](https://reviewable.io/reviews/gramineproject/gramine/1125#-NMo0lBb-CN5o9Z3BC2_:-NMo1nE07NBIDFx0Z4PG:bwbc0u2) ([raw file](https://github.com/gramineproject/gramine/blob/3cda8edd5364e0fa45662ba4e7f4d3ce2b2d357f/pal/src/host/linux/pal_main.c#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you require `XSAVE` because LibOS uses xsave instructions anyway? Not blocking, so you can do final rebase.
</blockquote></details>

Yes, I noticed that we already require it there, so it would be nice to have an error message for older platforms instead of crashing.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 111 at r2](https://reviewable.io/reviews/gramineproject/gramine/1125#-NMYGG7058IE6exeg_L3:-NMo42sGAKo5XlhaBwkF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0cc3d36e800eaea7b3d64f7cd2b6feac90d19955/pal/src/host/linux-sgx/host_framework.c#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

On rebase, this file will have `xfrm_flags` with explicit `leaf = 1`, `leaf = 7`, etc. This is because of the PR #1122 

So on final rebase, these leaves should be changed from hard-coded numbers to use macros.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-27 17:44 UTC, mkow commented
Jenkins, retest Jenkins-Direct-Sanitizers please (Blender download timed out)

2023-01-27 18:40 UTC, dimakuv approved these changes
> Reviewed 1 of 17 files at r5, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1125)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-27 18:49 UTC, merged