Fix conflicting files in .deb packages
gramineproject/gramine pull request #1138
Opened 2023-01-20 15:49 UTC by woju

## How to test this PR? 

1) CI must pass (esp. no errors from `dh_missing` in `pkg-deb-debian11` pipeline)
2) Get packages from CI and try to install — there should be no error like this:

```
Selecting previously unselected package gramine-ratls-dcap.
Preparing to unpack .../25-gramine-ratls-dcap_1.3.1~post_amd64.deb ...
Unpacking gramine-ratls-dcap (1.3.1~post) ...
dpkg: error processing archive /tmp/apt-dpkg-install-Qg3vBm/25-gramine-ratls-dcap_1.3.1~post_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libra_tls_verify_dcap.so', which is also in package gramine 1.3.1~post
Selecting previously unselected package gramine-ratls-epid.
Preparing to unpack .../26-gramine-ratls-epid_1.3.1~post_amd64.deb ...
Unpacking gramine-ratls-epid (1.3.1~post) ...
dpkg: error processing archive /tmp/apt-dpkg-install-Qg3vBm/26-gramine-ratls-epid_1.3.1~post_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libra_tls_verify_epid.so', which is also in package gramine 1.3.1~post
```

2023-01-23 09:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-01-25 01:17 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`debian/gramine.install` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1138#-NMaUumR7gTKscOV5y7M:-NMaUumR7gTKscOV5y7N:bs68obo) ([raw file](https://github.com/gramineproject/gramine/blob/6d74ea9b32b768fb72784cde85fe8482644333a5/debian/gramine.install#L36)):*
> ```
> usr/lib/${DEB_HOST_MULTIARCH}/gramine/runtime/glibc/librt.so*
> usr/lib/${DEB_HOST_MULTIARCH}/gramine/runtime/glibc/libthread_db.so*
> usr/lib/${DEB_HOST_MULTIARCH}/gramine/runtime/glibc/libutil.so*
> ```

Why not just wildcard all `*.so*`?


<!-- Sent from Reviewable.io -->

2023-01-25 13:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`debian/gramine.install` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/1138#-NMaUumR7gTKscOV5y7M:-NMcppAsBthEAsANZNPr:b-k9r2ah) ([raw file](https://github.com/gramineproject/gramine/blob/6d74ea9b32b768fb72784cde85fe8482644333a5/debian/gramine.install#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just wildcard all `*.so*`?
</blockquote></details>

It was so previously (just the whole directory). But it also catched `libra_tls*` and `libsecret_*`, and those need to be packaged separately (or it causes conflicts). Added a comment.


<!-- Sent from Reviewable.io -->

2023-01-25 13:18 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-01-25 13:25 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-25 13:32 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-01-25 13:46 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1138)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-25 14:07 UTC, woju commented
Jenkins, test pkg-rpm-almalinux9 please

2023-01-25 14:31 UTC, merged