[python] Add API documentation
gramineproject/gramine pull request #114
Opened 2021-10-02 21:50 UTC by boryspoplawski

## Description of the changes 
Yeah, just that. Plus some minor bugfixes in python code.

## How to test this PR? 
To test SGX version (which is currently disabled) you can build Gramine, copy `_offsets.py` into `python/graminelibos/`, then uncomment stuff in `Documentation/python/api.rst` and add this patch:
```
diff --git a/python/graminelibos/__init__.py b/python/graminelibos/__init__.py
index 23177282..99a699cc 100644
--- a/python/graminelibos/__init__.py
+++ b/python/graminelibos/__init__.py
@@ -18,7 +18,7 @@ from .gen_jinja_env import make_env
 _env = make_env()
 
 from .manifest import Manifest, ManifestError
-if '@SGX_ENABLED@' == '1':
+if '@SGX_ENABLED@' == '1' or  _os.getenv('GRAMINE_IMPORT_FOR_SPHINX_ANYWAY') == '1':
     from .sgx_get_token import get_token
     from .sgx_sign import get_tbssigstruct, sign_with_local_key
     from .sigstruct import Sigstruct
```
then build documentation.

2021-10-02 22:33 UTC, woju requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml20aF7DJWDv6cxG39E:-Ml20aF7DJWDv6cxG39F:bd6csoe) (no related file):*
Please add `toml` and possibly `protobuf` to `Documentation/requirements.txt`, without this might break in RTD. (Or maybe leave protobuf as TODO until sgx).

Technically we should also add jinja2 and click, but jinja is a dependency of sphinx, and click is certainly also pulled by something, so in practice this won't break.

---
___
*[python/graminelibos/manifest.py, line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml2-MCr51wzkPuzY7M-:-Ml2-MCr51wzkPuzY7M0:b-oezcz2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L126)):*
> ```Python
>         Args:
>             template (str): jinja2 template of the manifest
>             variables (:obj:`dict`, optional): Dictionary of variables that are used in
> ```

Not blocking: don't you wan't to use `:class:`? `:obj:` is catch-all, I-dont-want-to-remember: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-obj.
___
*[python/graminelibos/manifest.py, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26SYJAJhyURFY1tJv:-Ml26SYJAJhyURFY1tJw:b2fv9j6) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L152)):*
> ```Python
> 
>         Collects all trusted files entries and all files from "loader.preload" entry, hashes each
>         of them (skipping these which already had a hash present) and updates "sgx.trusted_files"
> ```

<code>``</code> 2x
___
*[python/graminelibos/manifest.py, line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26KXo6P4CXfDKXc27:-Ml26KXo6P4CXfDKXc28:bs4onxg) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L177)):*
> ```Python
> 
>         Collects all trusted files that are yet not expanded (does not have a hash in the entry) and
>         all files from "loader.preload" entry and returns them.
> ```

<code>``</code>
___
*[python/graminelibos/sgx_sign.py, line 544 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26Zq93t40U3Xwd4g9:-Ml26Zq93t40U3Xwd4gA:b-j6d30j) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L544)):*
> ```Python
> 
> def sign_with_local_key(data, key):
>     """Signs `data` using `key`.
> ```

`*data* using *key*`. Single <code>\`</code> without role gets assigned `default_role` or `.. default-role::`: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-default_role https://docutils.sourceforge.io/docs/ref/rst/directives.html#setting-the-default-interpreted-text-role 
___
*[python/graminelibos/sgx_sign.py, line 547 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml260TgEEuOdB6pwEg7:-Ml260TgEEuOdB6pwEg8:b-v62qkk) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L547)):*
> ```Python
> 
>     Function used to generate a RSA signature over provided data using a key from local filesystem.
>     Suitable to be used as a callback to ``graminelibos.Sigstruct.sign()``.
> ```

`:py:func:`
___
*[python/graminelibos/sigstruct.py, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27Lo0DwPatgq0bZIW:-Ml27Lo0DwPatgq0bZIX:btkwfnt) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L84)):*
> ```Python
> 
>         You probably want to  set all required fields before calling this function. If you not wish
>         to do so, you can pass ``False`` as `verify` argument - in such case non-set fields will be
> ```

<code>:obj:\`False\` as *verify*</code>
___
*[python/graminelibos/sigstruct.py, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27TT43_Vj_a2ZfSCw:-Ml27TT5BEyy1A-k4Oa7:b2nhwoh) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L86)):*
> ```Python
>         to do so, you can pass ``False`` as `verify` argument - in such case non-set fields will be
>         implicitly ``0``-initialized. Some fields have default values and therefore not need to be
>         set (e.g. ``header``).
> ```

`*`
___
*[python/graminelibos/sigstruct.py, line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27WBR5ToYLMe0sfmd:-Ml27WBR5ToYLMe0sfme:b-um5y23) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L123)):*
> ```Python
>         Raises:
>             TypeError: `buffer` has a wrong type (is not bytes or bytearray).
>             ValueError: `buffer` not have required length or one of the headers does not match.
> ```

`*` 2x
___
*[python/graminelibos/sigstruct.py, line 153 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27YCJBmOiXAOZm9cd:-Ml27YCJBmOiXAOZm9ce:b2nhwoh) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L153)):*
> ```Python
> 
>         Signs this SIGSTRUCT in place (i.e. fills appropriate fields with the signing result) using
>         `do_sign_callback` function.
> ```

`*`
___
*[python/graminelibos/sigstruct.py, line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27ZwW1PObqJdB7VSg:-Ml27ZwW1PObqJdB7VSh:b-xwp7oi) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L157)):*
> ```Python
>         Args:
>             do_sign_callback: Function doing actual signing. Gets to-be-signed data as the first
>                 argument (bytearray), then optional `*args` and `**kwargs`. Must return a tuple
> ```

hehe IDK what to do here, `*` will be problematic. Probably double-backquote.
___
*[python/graminelibos/sigstruct.py, line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27hB4Ee0X4uVtO-9X:-Ml27hB4Ee0X4uVtO-9Y:b-um5y23) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L160)):*
> ```Python
>                 ``(int, int, int)`` containing exponent, modulus and signature respectively.
>             *args: Arbitrary arguments list passed to `do_sign_callback`.
>             **kwargs:  Arbitrary keyword arguments passed to `do_sign_callback`.
> ```

`*` 2x


<!-- Sent from Reviewable.io -->

2021-10-03 09:25 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Documentation/python/api.rst, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4MNHJ1PJsbru2gvIh:-Ml4MNHJ1PJsbru2gvIi:b-vgtnf4) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/Documentation/python/api.rst#L15)):*
> ```reStructuredText
> --------
> 
> To render a |~| manifest from a |~| template::
> ```

Don't we need to mention that we expect Jinja2 templates for input files? 
___
*[Documentation/python/api.rst, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4T3lz3fPQ89mQXbH0:-Ml4T3m--9RkZgRnwDZU:b-3nkixw) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/Documentation/python/api.rst#L26)):*
> ```reStructuredText
>    with open('some_output_file', 'w') as f:
>        manifest.dump(f)
> ```

Why don't you have any examples for creating SIGSTRUCT and SGX Token?
___
*[python/graminelibos/manifest.py, line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4NoOO3BZg_rtLKea1:-Ml4NoOO3BZg_rtLKea2:b-6p6qlh) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L176)):*
> ```Python
>         """Generate list of files which this manifest depends on.
> 
>         Collects all trusted files that are yet not expanded (does not have a hash in the entry) and
> ```

`yet not` -> `not yet`

`does not` -> `do not`
___
*[python/graminelibos/sgx_get_token.py, line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4OsQl0JiyPYsMprZm:-Ml4OsQl0JiyPYsMprZn:bjwk98) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L107)):*
> ```Python
> 
> def get_token(sig):
>     """Get SGX token.
> ```

I would also add ` (aka EINITTOKEN)` here, because this term is more familiar for SGX devs.
___
*[python/graminelibos/sgx_get_token.py, line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4O7Wu0nGNb9bBCzUs:-Ml4O7Wu0nGNb9bBCzUt:bu56mrg) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L109)):*
> ```Python
>     """Get SGX token.
> 
>     Generates a SGX token from the given SIGSTRUCT.
> ```

`a` -> `an`
___
*[python/graminelibos/sgx_get_token.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Oja_5X2R71NP6dtA:-Ml4Oja_5X2R71NP6dtB:beud7c2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L110)):*
> ```Python
> 
>     Generates a SGX token from the given SIGSTRUCT.
> ```

There is also a subtle difference in the output SGX token from the input SIGSTRUCT: the SGX token adds optional XFRM (XCR0) bits for features that are not "required" by SIGSTRUCT but available on this particular machine. E.g., if SIGSTRUCT doesn't care about AVX512 being off or on (this is determined via `SIGSTRUCT.ATTRIBUTEMASK.XFRM`), and the machine has AVX512, then the produced SGX token will have `EINITTOKEN.ATTRIBUTES.XFRM.AVX512 = 1`.

I would like to see this explanation somewhere, it's quite subtle.
___
*[python/graminelibos/sgx_sign.py, line 511 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Pr338pVSCgBVdPAP:-Ml4Pr338pVSCgBVdPAQ:b-o4xhws) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L511)):*
> ```Python
>     """Generate To Be Signed Sigstruct (TBSSIGSTRUCT).
> 
>     Generates a Sigstruct object using the provided data with all required fields initialized.
> ```

`with all required fields initialized` is ambigious. In reality, *almost all* SIGSTRUCT fields are initialized, except the actual signature fields -- `exponent`, `modulus`, `signature`, `q1`, `q2`. Please rephrase to highlight this.
___
*[python/graminelibos/sgx_sign.py, line 546 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4QJJJ-jBUNUQYwy9h:-Ml4QJJJ-jBUNUQYwy9i:bu56mrg) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L546)):*
> ```Python
>     """Signs `data` using `key`.
> 
>     Function used to generate a RSA signature over provided data using a key from local filesystem.
> ```

`a` -> `an`
___
*[python/graminelibos/sgx_sign.py, line 546 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Qf90ASMVPTi-TNYu:-Ml4Qf90ASMVPTi-TNYv:b-r2sp53) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L546)):*
> ```Python
>     """Signs `data` using `key`.
> 
>     Function used to generate a RSA signature over provided data using a key from local filesystem.
> ```

I would be more specific: `to generate an RSA signature ... using a 3072-bit private key with public exponent of 3 (hard Intel SGX requirement on key size and exponent)`.
___
*[python/graminelibos/sigstruct.py, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4R9S2ByswCGhWJY9h:-Ml4R9S2ByswCGhWJY9i:b-mp07fp) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L12)):*
> ```Python
> 
> class Sigstruct:
>     """Class for holding SGX SIGSTRUCT
> ```

Dot at the end
___
*[python/graminelibos/sigstruct.py, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4RBzn-yXVWFtyX6Or:-Ml4RBzn-yXVWFtyX6Os:bu8tnac) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L14)):*
> ```Python
>     """Class for holding SGX SIGSTRUCT
> 
>     Each filed can be accessed and modified using ``[]`` operator. Accessing or setting an unknown
> ```

`filed` -> `field`
___
*[python/graminelibos/sigstruct.py, line 83 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4RNOoAEGHhbTHAQRs:-Ml4RNOoAEGHhbTHAQRt:bdyv3no) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L83)):*
> ```Python
>         """Turn SIGSTRUCT into bytes.
> 
>         You probably want to  set all required fields before calling this function. If you not wish
> ```

Remove double space between `to` and `set`
___
*[python/graminelibos/sigstruct.py, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4RjiJDD7WlEPW1t_r:-Ml4RjiJDD7WlEPW1t_s:baxe1r8) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L90)):*
> ```Python
>         Args:
>             verify (bool): if ``True``, check if all fields were initialized.
>             verify_sig_fields (bool): if ``True``, don't skip signature fields in checks.
> ```

Can you add an explanation to `verify_sig_fields` like
```
Only used when `verify == True`.
```
___
*[python/graminelibos/sigstruct.py, line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4S9qyCfcHYGDcSMWS:-Ml4S9qyCfcHYGDcSMWT:b-2iywp3) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L123)):*
> ```Python
>         Raises:
>             TypeError: `buffer` has a wrong type (is not bytes or bytearray).
>             ValueError: `buffer` not have required length or one of the headers does not match.
> ```

`not have` -> `d [...]

2021-10-03 15:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 3 of 9 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml20aF7DJWDv6cxG39E:-Ml5J4obCkxTai_JL1T8:b-qrlj7c) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please add `toml` and possibly `protobuf` to `Documentation/requirements.txt`, without this might break in RTD. (Or maybe leave protobuf as TODO until sgx).

Technically we should also add jinja2 and click, but jinja is a dependency of sphinx, and click is certainly also pulled by something, so in practice this won't break.
</blockquote></details>

Added `toml`.
The problem with protobuf, jinja2 and click is that we install them via `apt`.

---
___
*[Documentation/python/api.rst, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4MNHJ1PJsbru2gvIh:-Ml5Kf4g7QhH3stvQZoy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/Documentation/python/api.rst#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we need to mention that we expect Jinja2 templates for input files? 
</blockquote></details>

Done.
___
*[Documentation/python/api.rst, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4T3lz3fPQ89mQXbH0:-Ml5KKM1CZoneZjzUtZp:b-xacwbe) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/Documentation/python/api.rst#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why don't you have any examples for creating SIGSTRUCT and SGX Token?
</blockquote></details>

Because SGX docs won't render atm (due to technical problems, that we need to install Gramine, which we do/can not on RTD).
But I guess I can add them nevertheless.
Done.
___
*[python/graminelibos/manifest.py, line 126 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml2-MCr51wzkPuzY7M-:-Ml5TkZk9gk6yCNKhGED:b5rccy9) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L126)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not blocking: don't you wan't to use `:class:`? `:obj:` is catch-all, I-dont-want-to-remember: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-obj.
</blockquote></details>

TBH this was https://miro.medium.com/max/910/1*snTXFElFuQLSFDnvZKJ6IA.png
I just looked at an example an they used `obj` everywhere: https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google
___
*[python/graminelibos/manifest.py, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26SYJAJhyURFY1tJv:-Ml5XnOr-1aXQZrqZCmh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L152)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

<code>``</code> 2x
</blockquote></details>

Done.
___
*[python/graminelibos/manifest.py, line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4NoOO3BZg_rtLKea1:-Ml5Xzg_2XjAJZoNN0rs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`yet not` -> `not yet`

`does not` -> `do not`
</blockquote></details>

Done.
___
*[python/graminelibos/manifest.py, line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26KXo6P4CXfDKXc27:-Ml5Y-5Z0v6kjFB1ez3b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L177)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

<code>``</code>
</blockquote></details>

Done.
___
*[python/graminelibos/sgx_get_token.py, line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4OsQl0JiyPYsMprZm:-Ml5YB5S2aGcDS17Z7zi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also add ` (aka EINITTOKEN)` here, because this term is more familiar for SGX devs.
</blockquote></details>

Done.
___
*[python/graminelibos/sgx_get_token.py, line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4O7Wu0nGNb9bBCzUs:-Ml5YJWXAj6l-2giLg4a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`a` -> `an`
</blockquote></details>

Done.
___
*[python/graminelibos/sgx_get_token.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Oja_5X2R71NP6dtA:-Ml5_Kkl9tB1hn2bIa1a:b-unr9j5) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is also a subtle difference in the output SGX token from the input SIGSTRUCT: the SGX token adds optional XFRM (XCR0) bits for features that are not "required" by SIGSTRUCT but available on this particular machine. E.g., if SIGSTRUCT doesn't care about AVX512 being off or on (this is determined via `SIGSTRUCT.ATTRIBUTEMASK.XFRM`), and the machine has AVX512, then the produced SGX token will have `EINITTOKEN.ATTRIBUTES.XFRM.AVX512 = 1`.

I would like to see this explanation somewhere, it's quite subtle.
</blockquote></details>

Done. Please check if the explanation makes sense.
___
*[python/graminelibos/sgx_sign.py, line 511 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Pr338pVSCgBVdPAP:-Ml5a0RG9qSELhdv-O5-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L511)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`with all required fields initialized` is ambigious. In reality, *almost all* SIGSTRUCT fields are initialized, except the actual signature fields -- `exponent`, `modulus`, `signature`, `q1`, `q2`. Please rephrase to highlight this.
</blockquote></details>

Done.
___
*[python/graminelibos/sgx_sign.py, line 544 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26Zq93t40U3Xwd4g9:-Ml5d8Rg33_RBB3LgLgP:b-c84kp6) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L544)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`*data* using *key*`. Single <code>\`</code> without role gets assigned `default_role` or `.. default-role::`: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-default_role https://docutils.sourceforge.io/docs/ref/rst/directives.html#setting-the-default-interpreted-text-role 
</blockquote></details>

Hm, how do you refer to function arguments then? I've followed https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google which did this.
___
*[python/graminelibos/sgx_sign.py, line 546 at r1](https://reviewable.io/reviews/gram [...]

2021-10-03 15:39 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 8 of 9 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[Documentation/python/api.rst, line 37 at r2](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml5mibm1KctyntNCkNm:-Ml5mibm1KctyntNCkNn:bgfgnj5) ([raw file](https://github.com/gramineproject/gramine/blob/d957c75fe2e01bda05a6add1101509b875bd17db/Documentation/python/api.rst#L37)):*
> ```reStructuredText
>     sigstruct.sign(sign_with_local_key, 'path_to_private_key')
> 
>     with open('path_to_signature_file', 'wb') as f:
> ```

This name is confusing, you're using `sigstruct` everywhere else. Moreover, you use `path_to_sigstruct` in the example below -- which is the same file as you're writing here.

So please change `path_to_signature_file` -> `path_to_sigstruct`.
___
*[python/graminelibos/sgx_get_token.py, line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml4Oja_5X2R71NP6dtA:-Ml5nQ054z7GLro8yYvp:bcsxih4) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_get_token.py#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done. Please check if the explanation makes sense.
</blockquote></details>

Ok, the text is perfect.


<!-- Sent from Reviewable.io -->

2021-10-03 15:56 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 8 of 9 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Documentation/python/api.rst, line 37 at r2](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml5mibm1KctyntNCkNm:-Ml5rfP-2EVzEkaF1eLE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d957c75fe2e01bda05a6add1101509b875bd17db/Documentation/python/api.rst#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This name is confusing, you're using `sigstruct` everywhere else. Moreover, you use `path_to_sigstruct` in the example below -- which is the same file as you're writing here.

So please change `path_to_signature_file` -> `path_to_sigstruct`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-03 17:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 8 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-10-04 15:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 7 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[python/graminelibos/sgx_sign.py, line 544 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26Zq93t40U3Xwd4g9:-MlAyun13tli0lD-Qt2D:b-9oskx2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sgx_sign.py#L544)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, how do you refer to function arguments then? I've followed https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google which did this.
</blockquote></details>

Done, per @woju request.
___
*[python/graminelibos/sigstruct.py, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27TT43_Vj_a2ZfSCw:-MlAz8PFCB7oxlF4aoyQ:b-9oskx2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, per @woju request.
___
*[python/graminelibos/sigstruct.py, line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27WBR5ToYLMe0sfmd:-MlAzSKr0S6UuXQ8bAfS:b-9oskx2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, per @woju request.
___
*[python/graminelibos/sigstruct.py, line 153 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27YCJBmOiXAOZm9cd:-MlAzVyM0oj-dNavz7gW:b-9oskx2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L153)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto 
</blockquote></details>

Done, per @woju request.
___
*[python/graminelibos/sigstruct.py, line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27ZwW1PObqJdB7VSg:-MlAzilTA51kD53zILeb:b-tzft8e) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L157)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I disagree, but done, per @woju request.
___
*[python/graminelibos/sigstruct.py, line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml27hB4Ee0X4uVtO-9X:-MlAzwDZDv0HeTcpTP6Z:b-9oskx2) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/sigstruct.py#L160)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, per @woju request.


<!-- Sent from Reviewable.io -->

2021-10-04 17:39 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 8 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-10-05 06:29 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: 8 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-10-05 11:17 UTC, woju requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml20aF7DJWDv6cxG39E:-Ml9m6BK23jNMhocp01i:bgkpe48) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Added `toml`.
The problem with protobuf, jinja2 and click is that we install them via `apt`.
</blockquote></details>

Not in RTD, and we don't install from `Documentaiton/requirement.txt` in docker, so I don't think this is a problem. But it'll work, so resolving.

---
___
*[python/graminelibos/manifest.py, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26SYJAJhyURFY1tJv:-Ml9mWOSDxd7L1e5w-6P:b-3ckh9n) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. This should be <code>``loader.preload``</code> (double backticks both sides) and same for sgx.trusted files.
___
*[python/graminelibos/manifest.py, line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26KXo6P4CXfDKXc27:-Ml9mdRL0DTxeo2zPWha:b-2zhriz) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L177)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

double backticks


<!-- Sent from Reviewable.io -->

2021-10-05 13:28 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[python/graminelibos/manifest.py, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/114#-Ml26SYJAJhyURFY1tJv:-MlFcsfb9HRM324KS-fE:bbtje94) ([raw file](https://github.com/gramineproject/gramine/blob/dc5c25ab044725469d0b7d4f680223c7c5b15caa/python/graminelibos/manifest.py#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've understood ``` `` ``` as ``` `abcd` ```.
Done.
</blockquote></details>

Sorry, I was writing too fast.


<!-- Sent from Reviewable.io -->

2021-10-05 13:44 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (GitHub glitched, and downloads failed)

2021-10-05 15:59 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-10-05 15:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-05 16:07 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski)

___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlACwSy5qfjrBCuz6-J):*
`python` -> `Python`
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlACyCkC94SU0zx7plw):*
ditto
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlAD0AxCoMluTOM8t-_):*
`[Documentation]` -> `[Docs]`


<!-- Sent from Reviewable.io -->

2021-10-05 16:16 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 5 unresolved discussions (waiting on @boryspoplawski)

___
*[Documentation/python/api.rst, line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/114#-MlGD8VzDssyAPEDAd-V:-MlGD8W-8Oc87EiGZUFH:bny182k) ([raw file](https://github.com/gramineproject/gramine/blob/7b62996550e18bf169d623d8ed9297e09e9b8c9a/Documentation/python/api.rst#L10)):*
> ```reStructuredText
> ------------
> 
> We expose a python API for manifest, SIGSTRUCT and SGX token management.
> ```

`python` -> `Python`
___
*[python/graminelibos/manifest.py, line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/114#-MlGE-CQ6HUG2RVAT1E7:-MlGE-CQ6HUG2RVAT1E8:b-9vnkux) ([raw file](https://github.com/gramineproject/gramine/blob/7b62996550e18bf169d623d8ed9297e09e9b8c9a/python/graminelibos/manifest.py#L8)):*
> ```Python
> #                    Borys Popławski <borysp@invisiblethingslab.com>
> 
> """
> ```

Why not `'''`? All other places use single quotes for everything and I definitely prefer them (easier to type and more uniform with the rest of our Python)


<!-- Sent from Reviewable.io -->

2021-10-05 16:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 5 unresolved discussions (waiting on @mkow)

___
*[-- commits, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlACwSy5qfjrBCuz6-J):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`python` -> `Python`
</blockquote></details>

Done.
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlACyCkC94SU0zx7plw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/114#-MlAD0AxCoMluTOM8t-_):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`[Documentation]` -> `[Docs]`
</blockquote></details>

Done.
___
*[Documentation/python/api.rst, line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/114#-MlGD8VzDssyAPEDAd-V:-MlGGXyzDY9lqyIq2Tw1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b62996550e18bf169d623d8ed9297e09e9b8c9a/Documentation/python/api.rst#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`python` -> `Python`
</blockquote></details>

Done.
___
*[python/graminelibos/manifest.py, line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/114#-MlGE-CQ6HUG2RVAT1E7:-MlGGpebEMyl6yNEyWnt:b-t9c5m) ([raw file](https://github.com/gramineproject/gramine/blob/7b62996550e18bf169d623d8ed9297e09e9b8c9a/python/graminelibos/manifest.py#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `'''`? All other places use single quotes for everything and I definitely prefer them (easier to type and more uniform with the rest of our Python)
</blockquote></details>

Ask PEP and Google python code style authors (both explicitly require docstrings to be in `"""`).


<!-- Sent from Reviewable.io -->

2021-10-05 16:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-10-05 16:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/114)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[python/graminelibos/manifest.py, line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/114#-MlGE-CQ6HUG2RVAT1E7:-MlGJ9ZTESCtQy7JzGQE:b-596dqo) ([raw file](https://github.com/gramineproject/gramine/blob/7b62996550e18bf169d623d8ed9297e09e9b8c9a/python/graminelibos/manifest.py#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ask PEP and Google python code style authors (both explicitly require docstrings to be in `"""`).
</blockquote></details>

Weird, I won't block on this, but I don't like it ;)


<!-- Sent from Reviewable.io -->

2021-10-05 17:04 UTC, merged