[PAL/Linux-SGX] Try old mmap flags if first mmap on SGX driver failed
gramineproject/gramine pull request #1145
Opened 2023-01-24 14:30 UTC by dimakuv

## Description of the changes 

Commit "[PAL/Linux-SGX] Add initial EDMM support (only regular pages)" simplified the initial mmap request to the SGX driver (to allocate EPC memory). However, this simplification broke the OOT DCAP driver v1.33.2, found on MS Azure VMs with Ubuntu 18.04: it fails with EACCES.

It turns out the OOT DCAP driver and the upstream driver are not 100% compatible because of this mmap. Hopefully we won't need to support the OOT DCAP driver for long, so this commit introduces a hack to revert to the old mmap flags on failure.

See https://github.com/gramineproject/gramine/pull/1054/files#diff-4e06cdb88e117895595e7b079d551cf389b3e0456635a9a8ca7d9da3552539bc -- this is the offender.

Without this PR, on a Ubuntu 18.04 system (MS Azure CC VM), I get the following error:
```
$ dmesg | grep -i sgx
[    5.407890] sgx: EPC section 0x30e0000000-0x4edfffffff
[    6.416713] sgx: intel_sgx: Intel SGX DCAP Driver v1.33.2

$ gramine/CI-Examples/helloworld$ gramine-sgx helloworld
error: Allocation of EPC memory failed: Permission denied (EACCES)
error: Creating enclave failed: Permission denied (EACCES)
error: load_enclave() failed with error: Permission denied (EACCES)
```

## How to test this PR? 

Test on as many different machines as possible. In particular, Ms Azure CC VM with Ubuntu 18.04.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1145)

2023-01-24 19:02 UTC, donporter requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 192 at r1](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMZBI_lCclOGZ_R-yHi:-NM_7rdaENS-DcJ_Fn_E:bnk0k5u) ([raw file](https://github.com/gramineproject/gramine/blob/6a7194c43b44bc64f8d9d87cc5d681c1cca88b02/pal/src/host/linux-sgx/host_framework.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I'll be honest, I don't understand why these combinations work on all SGX drivers. I didn't investigate the SGX drivers sources that much, I just reverted to the state that worked for us before EDMM PR.
</blockquote></details>

I'm ok with this as a short-term hack that we expect to retire soon.  
___
*[`pal/src/host/linux-sgx/host_framework.c` line 191 at r2](https://reviewable.io/reviews/gramineproject/gramine/1145#-NM_8wy5-w7Tb_fK6NPp:-NM_8wy5-w7Tb_fK6NPq:b-b70s2w) ([raw file](https://github.com/gramineproject/gramine/blob/1fa21109421e1ec63ebb8e1144c354095ac2e1bc/pal/src/host/linux-sgx/host_framework.c#L191)):*
> ```C
>     if (IS_PTR_ERR(addr) && PTR_TO_ERR(addr) == -EACCES) {
>         /* OOT DCAP driver (e.g. v1.33.2 found on MS Azure VMs with Ubuntu 18.04) requires
>          * different mmap flags */
> ```

Do we want to dynamically check whether we have the OOT driver loaded, if we only expect this case to happen with the OOT driver?
___
*[`pal/src/host/linux-sgx/host_framework.c` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1145#-NM_8sjp-ODl-qBV20gz:-NM_8sjp-ODl-qBV20h-:b-ik2ke5) ([raw file](https://github.com/gramineproject/gramine/blob/1fa21109421e1ec63ebb8e1144c354095ac2e1bc/pal/src/host/linux-sgx/host_framework.c#L197)):*
> ```C
>                           MAP_FIXED | MAP_SHARED, g_isgx_device, 0);
> #else
>                           MAP_FIXED | MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
> ```

Do we expect the #else case to ever happen?  As in, can we get here by the in-kernel driver at all?


<!-- Sent from Reviewable.io -->

2023-01-24 21:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 191 at r2](https://reviewable.io/reviews/gramineproject/gramine/1145#-NM_8wy5-w7Tb_fK6NPp:-NM_Ha5jBy0HmtY9FobM:bkruhuo) ([raw file](https://github.com/gramineproject/gramine/blob/1fa21109421e1ec63ebb8e1144c354095ac2e1bc/pal/src/host/linux-sgx/host_framework.c#L191)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we want to dynamically check whether we have the OOT driver loaded, if we only expect this case to happen with the OOT driver?
</blockquote></details>

Unfortunately there's no way to distuingish the OOT DCAP driver with the upstream Linux driver :(
___
*[`pal/src/host/linux-sgx/host_framework.c` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1145#-NM_8sjp-ODl-qBV20gz:-NM_OZ2v2g1R2ob-uP6k:b-1ni32g) ([raw file](https://github.com/gramineproject/gramine/blob/1fa21109421e1ec63ebb8e1144c354095ac2e1bc/pal/src/host/linux-sgx/host_framework.c#L197)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we expect the #else case to ever happen?  As in, can we get here by the in-kernel driver at all?
</blockquote></details>

Done (it's actually the other way around: at this point we know we have the OOT DCAP driver, so it means we need to go into the `else` branch). Recall that `CONFIG_SGX_DRIVER_OOT` means the **legacy non-FLC non-DCAP OOT driver**.


<!-- Sent from Reviewable.io -->

2023-01-25 01:05 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMaRK2K8HG0JyzUt_P-):*
> to allocate EPC memory

Enclave, not EPC? The mmap can be larger than EPC size, for example.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 191 at r3](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMaSA2U-P8xNXiRJJ-e:-NMaSA2U-P8xNXiRJJ-f:bqr6mne) ([raw file](https://github.com/gramineproject/gramine/blob/32454a63f01e7d8b443b7dc19b31b0f1495431a9/pal/src/host/linux-sgx/host_framework.c#L191)):*
> ```C
>     if (IS_PTR_ERR(addr) && PTR_TO_ERR(addr) == -EACCES) {
>         /* OOT DCAP driver (e.g. v1.33.2 found on MS Azure VMs with Ubuntu 18.04) requires
>          * different mmap flags */
> ```

Please add a TODO to remove this right after we drop 18.04.


<!-- Sent from Reviewable.io -->

2023-01-25 08:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMc2lxF0G1kNMjhGO11:-NMc2lxG30l8rQ1vmyKe:bye2jtg) (no related file):*
Ok, the current version was tested on MS Azure VM 18.04 (with OOT DCAP driver) and it works.

___
___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMaRK2K8HG0JyzUt_P-):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> to allocate EPC memory

Enclave, not EPC? The mmap can be larger than EPC size, for example.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_framework.c` line 191 at r3](https://reviewable.io/reviews/gramineproject/gramine/1145#-NMaSA2U-P8xNXiRJJ-e:-NMc2Q8q8XTdAOv-7N9U:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/32454a63f01e7d8b443b7dc19b31b0f1495431a9/pal/src/host/linux-sgx/host_framework.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a TODO to remove this right after we drop 18.04.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-25 11:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2023-01-25 12:47 UTC, donporter approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1145)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-25 13:15 UTC, merged