[tests] Add "execute" subtest to `memory` test
gramineproject/gramine pull request #1146
Opened 2023-01-25 18:11 UTC by dimakuv

## Description of the changes 

This increases test coverage for the EDMM SGX feature.

This is another approach instead of #1120: we just augment the already-existing PAL test `memory.c` instead of creating a new one.

Closes #1120.

## How to test this PR? 

CI and manually.

2023-01-26 16:53 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMish_735ddkCCftPkq):*




_Suggestion:_
```
for EDMM (SGX feature)
```
___
*[`pal/regression/memory.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMiyX610KPBVOLxm7Zy:-NMiyX610KPBVOLxm7Zz:bniaq4t) ([raw file](https://github.com/gramineproject/gramine/blob/6eb02496c1b0045d5d1515bf39c09d0c010ea3af/pal/regression/memory.c#L41)):*
> ```C
>     "movb (%rdi), %al\n"
>     "ret\n"
> "mem_exec:\n"
> ```

This can be written in C.
___
*[`pal/regression/test_pal.py` line 354 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMizdW27DaSxdfkUS_l:-NMizdW27DaSxdfkUS_m:b-hfanx4) ([raw file](https://github.com/gramineproject/gramine/blob/3d9f62f2da5c408a5a774edc19f76d6d951fea66/pal/regression/test_pal.py#L354)):*
> ```Python
>                 self.assertEqual(e.returncode, 1)
>                 stderr = e.stderr.decode()
>                 self.assertRegex(stderr, r'write to R mem at 0x[0-9a-f]+ unexpectedly succeeded')
> ```

Why have you _replaced_ this assert instead of adding / ORing another condition to the old one? From what I can see the old message is still used by this test in another place.


<!-- Sent from Reviewable.io -->

2023-01-27 09:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMish_735ddkCCftPkq):*
Will do at final rebase
___
*[`pal/regression/memory.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMiyX610KPBVOLxm7Zy:-NMmYu92E_vToW3qqJ2f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6eb02496c1b0045d5d1515bf39c09d0c010ea3af/pal/regression/memory.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This can be written in C.
</blockquote></details>

Done.
___
*[`pal/regression/test_pal.py` line 354 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMizdW27DaSxdfkUS_l:-NMmZCMY1caiBM-dVcQc:bdgz7h1) ([raw file](https://github.com/gramineproject/gramine/blob/3d9f62f2da5c408a5a774edc19f76d6d951fea66/pal/regression/test_pal.py#L354)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you _replaced_ this assert instead of adding / ORing another condition to the old one? From what I can see the old message is still used by this test in another place.
</blockquote></details>

I think my replacement makes sense.

When we are in this `else` branch, it means we execute **under SGX1**. So the expectation is that the test fails **on the first** (unexpectedly successful) access to restricted-permissions memory.

Previously the first such access was a write to R memory. Now the first such access is the exec on RW memory.

If we would OR, then this test will pass an incorrect execution run -- when for some reason an exec on RW memory succeeded, but then the second access -- write to R memory -- failed. So I think my current code (replacement) is correct.


<!-- Sent from Reviewable.io -->

2023-01-27 09:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: 1 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMma_4MAyE1TSC8m4q7):*
Forgot to add Vijay as a co-author. Do it at final rebase.


<!-- Sent from Reviewable.io -->

2023-01-27 11:18 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/regression/test_pal.py` line 354 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMizdW27DaSxdfkUS_l:-NMmwQ4T7Qjdp86JpH8B:bly8f01) ([raw file](https://github.com/gramineproject/gramine/blob/3d9f62f2da5c408a5a774edc19f76d6d951fea66/pal/regression/test_pal.py#L354)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think my replacement makes sense.

When we are in this `else` branch, it means we execute **under SGX1**. So the expectation is that the test fails **on the first** (unexpectedly successful) access to restricted-permissions memory.

Previously the first such access was a write to R memory. Now the first such access is the exec on RW memory.

If we would OR, then this test will pass an incorrect execution run -- when for some reason an exec on RW memory succeeded, but then the second access -- write to R memory -- failed. So I think my current code (replacement) is correct.
</blockquote></details>

Ah, I didn't notice that the test stops at the first failure and doesn't execute other sub-tests then.


<!-- Sent from Reviewable.io -->

2023-01-27 14:38 UTC, dimakuv commented
Jenkins, retest this please (no space was left on Jenkins nodes)

2023-01-31 08:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMish_735ddkCCftPkq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do at final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/1146#-NMma_4MAyE1TSC8m4q7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to add Vijay as a co-author. Do it at final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-31 11:53 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1146)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-31 11:57 UTC, dimakuv commented
Jenkins, retest pkg-rpm-almalinux9 please (`Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.almalinux.org/mirrorlist/9/appstream`)

2023-01-31 11:57 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (Blender download timed out)

2023-01-31 12:38 UTC, merged