[PAL/Linux-SGX] Print error message if no EDMM support
gramineproject/gramine pull request #1149
Opened 2023-01-27 10:28 UTC by dimakuv

## Description of the changes 

Fixes #1148

Some references:
- https://lore.kernel.org/lkml/6f8653a000c0fd670ea19337d1c744b28127be54.1644274683.git.reinette.chatre@intel.com/ (search for "Ensure kernel supports ...")
- https://lore.kernel.org/lkml/165721846417.15455.4074908162801839460.tip-bot2@tip-bot2/T/ (search for "sgx_ioc_sgx2_ready")
- https://patchwork.kernel.org/project/intel-sgx/patch/d787827dbfca6b3210ac3e432e3ac1202727e786.1616136308.git.kai.huang@intel.com/
- https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/cpu/sgx/ioctl.c#L1257
- Intel SDM, Table 3-8, CPUID leaf `0x12`.

## How to test this PR? 

Manually on different machines.

2023-01-27 14:38 UTC, dimakuv commented
Jenkins, retest this please (no space was left on Jenkins nodes)

2023-01-27 16:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1036 at r1](https://reviewable.io/reviews/gramineproject/gramine/1149#-NMo01Gf-tFHSYOSZo46:-NMo01Gf-tFHSYOSZo47:b-ddjiux) ([raw file](https://github.com/gramineproject/gramine/blob/7f5f029baf00177115a8eff4940e4504b9dbade1/pal/src/host/linux-sgx/host_main.c#L1036)):*
> ```C
>     if (enclave->edmm_enabled) {
>         uint32_t values[4];
>         cpuid(0x12, 0, values);
> ```

I can use `INTEL_SGX_LEAF` after #1125 is merged


<!-- Sent from Reviewable.io -->

2023-01-30 08:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/host_main.c` line 1036 at r1](https://reviewable.io/reviews/gramineproject/gramine/1149#-NMo01Gf-tFHSYOSZo46:-NN0kqkSEHpL3dOQFm7d:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/7f5f029baf00177115a8eff4940e4504b9dbade1/pal/src/host/linux-sgx/host_main.c#L1036)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can use `INTEL_SGX_LEAF` after #1125 is merged
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-30 09:37 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN115dz5xd1nNYx569j:b3vdd24) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
> ```C
>     struct sgx_enclave_remove_pages params = { 0 };
>     int ret = DO_SYSCALL(ioctl, g_isgx_device, SGX_IOC_ENCLAVE_REMOVE_PAGES, &params);
>     return ret != -ENOTTY;
> ```

What about other fails?
`EBADF`/`EFAULT` etc...


<!-- Sent from Reviewable.io -->

2023-01-30 11:00 UTC, mkow requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 505 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1G_llCleogorYKN7X:-NN1G_llCleogorYKN7Y:bmk5px9) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L505)):*
> ```C
> /* must be called after open_sgx_driver() */
> bool edmm_supported_by_driver(void) {
>     struct sgx_enclave_remove_pages params = { 0 };
> ```

Could you explicitly set all the fields? Right now it looks weird and like you were calling a syscall with random arguments (which could in theory do something bad with our process state, even if they are all zeros).
___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN1FOqhDuT6sUqJzv8u:b-woapwe) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What about other fails?
`EBADF`/`EFAULT` etc...
</blockquote></details>

Yup, this should be checked and we have to fail then (i.e. this function can return 3 results: no EDMM support, EDMM support, failed to check EDMM support).
___
*[`pal/src/host/linux-sgx/host_main.c` line 1042 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1KCGg5vEfBQ5ehqbl:-NN1KCGg5vEfBQ5ehqbm:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_main.c#L1042)):*
> ```C
>             return -EPERM;
>         }
>         if (!(edmm_supported_by_driver())) {
> ```





_Suggestion:_
```C
!edmm_supported_by_driver()
```


<!-- Sent from Reviewable.io -->

2023-01-30 11:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 505 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1G_llCleogorYKN7X:-NN1OCE8C8hsZr1HzJXB:b-uxdftg) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L505)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explicitly set all the fields? Right now it looks weird and like you were calling a syscall with random arguments (which could in theory do something bad with our process state, even if they are all zeros).
</blockquote></details>

Done.

Though we indeed call a syscall with random arguments, just to see if this particular IOCTL code (`SGX_IOC_ENCLAVE_REMOVE_PAGES`) exists.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN1L7KwELJVnmRwlZch:b-mmojdx) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, this should be checked and we have to fail then (i.e. this function can return 3 results: no EDMM support, EDMM support, failed to check EDMM support).
</blockquote></details>

But this is exactly the point of this check? Since I'm providing some dummy values in `params`, this IOCTL will fail with smth like `EFAULT`.

I'm relying on the semantics here that the very first thing that is checked on IOCTLs is whether this IOCTL exists (which is `ENOTTY` error).

But I agree that even before this check, we might fail with `EBADF` due to wrong `g_isgx_device`. Added this.
___
*[`pal/src/host/linux-sgx/host_main.c` line 1042 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1KCGg5vEfBQ5ehqbl:-NN1OOvn8nuGB5ZdTmjv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_main.c#L1042)):*
> ```C
>             return -EPERM;
>         }
>         if (!(edmm_supported_by_driver())) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 11:56 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 505 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1G_llCleogorYKN7X:-NN1VaFf3fBoi8J1pNca:bxwd0st) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L505)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Though we indeed call a syscall with random arguments, just to see if this particular IOCTL code (`SGX_IOC_ENCLAVE_REMOVE_PAGES`) exists.
</blockquote></details>

Yes, but you fire this logic, which does something on our process. Is it actually no-op with these arguments? It looks like it should be, because `length` is 0, but please ensure that this is really the case (and it's not e.g. trying to modify a page at address 0).
___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN1VyAFE4_ts-I3gMdR:boz56tb) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this is exactly the point of this check? Since I'm providing some dummy values in `params`, this IOCTL will fail with smth like `EFAULT`.

I'm relying on the semantics here that the very first thing that is checked on IOCTLs is whether this IOCTL exists (which is `ENOTTY` error).

But I agree that even before this check, we might fail with `EBADF` due to wrong `g_isgx_device`. Added this.
</blockquote></details>

This is a very bad practice. Remember e.g. our problems with Python exceptions, caused by buggy libunwind? They did exactly the same as you are doing here - firing a dummy syscall, but only checking `ret != EFAULT`. We failed with `ENOSYS` and the function silently treated this as a success.

We should have a set of errors which we know indicate that EDMM is supported, a set of errors indicating that it's not, and all others mean an error while checking the availability.

btw. Why do we even have this as a separate check? Starting the enclave will fail on these ioctls if EDMM is missing, we could just improve the error message there?
___
*[`pal/src/host/linux-sgx/host_framework.c` line 504 at r3](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1VpLQ-JrVb5QqmtMx:-NN1VpLQ-JrVb5QqmtMy:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f53fe1ccd86eae03804a9afe8123c9cba46a4d95/pal/src/host/linux-sgx/host_framework.c#L504)):*
> ```C
> 
> /* must be called after open_sgx_driver() */
> int edmm_supported_by_driver(bool *out_supported) {
> ```





_Suggestion:_
```C
bool* out_supported
```


<!-- Sent from Reviewable.io -->

2023-01-30 12:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 505 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1G_llCleogorYKN7X:-NN1ZU6QDFd2cpAT2Sel:bdvjz5j) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L505)):*
> Is it actually no-op with these arguments? It looks like it should be, because length is 0, but please ensure that this is really the case

Exactly, it is a no-op. See the flow here:
1. https://elixir.bootlin.com/linux/v6.1.8/source/arch/x86/kernel/cpu/sgx/ioctl.c#L1198
2. https://elixir.bootlin.com/linux/v6.1.8/source/arch/x86/kernel/cpu/sgx/ioctl.c#L1211
3. https://elixir.bootlin.com/linux/v6.1.8/source/arch/x86/kernel/cpu/sgx/ioctl.c#L356
___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN1Zqh6-neptvKmSrhn:b2ao91s) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
> We should have a set of errors which we know indicate that EDMM is supported, a set of errors indicating that it's not, and all others mean an error while checking the availability.

I do not understand what you mean by this. I'm relying on this behavior of the SGX driver: https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/cpu/sgx/ioctl.c#L1257 (note that `ENOIOCTLCMD` is transformed by Linux kernel into `ENOTTY`).

How else could I check whether EDMM is supported by the SGX driver or not? The SGX driver doesn't provide any functionality to check this. That's why SGX driver devs simply check for return values as well: https://lore.kernel.org/lkml/6f8653a000c0fd670ea19337d1c744b28127be54.1644274683.git.reinette.chatre@intel.com/ (search for "Ensure kernel supports ...")

> btw. Why do we even have this as a separate check? Starting the enclave will fail on these ioctls if EDMM is missing, we could just improve the error message there?

That's not how EDMM works. Currently Gramine just hangs, because the very first EDMM flow Gramine does is to relax page permissions, which is done via `EACCEPT` in-enclave instruction. This instruction fails, and Gramine goes into an infinite loop of trying to perform an exception handler, just to realize that there is no enclave memory available for it, so Gramine again tries to do an EDMM flow, and it gets completely stuck.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 504 at r3](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN1VpLQ-JrVb5QqmtMx:-NN1aijQ1AT61TlkxmCy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f53fe1ccd86eae03804a9afe8123c9cba46a4d95/pal/src/host/linux-sgx/host_framework.c#L504)):*
> ```C
> 
> /* must be called after open_sgx_driver() */
> int edmm_supported_by_driver(bool *out_supported) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 19:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN3BIT_9Fq8tUkJAjXb:b-ceoke6) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
> I do not understand what you mean by this.

`/* other errors mean that this IOCTL is supported */` <- this is wrong. Other errors may mean that e.g. we have a bug in Gramine in this checking logic, something unexpected happened or many other possible things. And here you're collapsing tens of possible ioctl errors into "EDMM is supported".


<!-- Sent from Reviewable.io -->

2023-01-30 19:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN3CtQb0_WIHhW-08AN:b2uk2h3) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I do not understand what you mean by this.

`/* other errors mean that this IOCTL is supported */` <- this is wrong. Other errors may mean that e.g. we have a bug in Gramine in this checking logic, something unexpected happened or many other possible things. And here you're collapsing tens of possible ioctl errors into "EDMM is supported".
</blockquote></details>

Fair enough. So do you think I should do the following:
1. `-EINVAL` -- this is what SGX driver with EDMM will return because `length == 0` (i.e. we return success and `true` in this func)
2. `-ENOTTY` -- this is what SGX driver without EDMM will return (i.e. we return success and `false` in this func)
3. everything else -- we fail (i.e. we return this error code)

Is this what you'd like me to do?


<!-- Sent from Reviewable.io -->

2023-01-30 19:53 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN3EN64DeG-wwp8Wj8q:b-hmils0) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough. So do you think I should do the following:
1. `-EINVAL` -- this is what SGX driver with EDMM will return because `length == 0` (i.e. we return success and `true` in this func)
2. `-ENOTTY` -- this is what SGX driver without EDMM will return (i.e. we return success and `false` in this func)
3. everything else -- we fail (i.e. we return this error code)

Is this what you'd like me to do?
</blockquote></details>

yup :)


<!-- Sent from Reviewable.io -->

2023-01-30 20:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 507 at r2](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN115dz5xd1nNYx569i:-NN3Q_Kt8f8-jXmbavAx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab63f31d7d52b0f4d56e9e3eb29bcfb761db49ff/pal/src/host/linux-sgx/host_framework.c#L507)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

yup :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 21:06 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-01-30 21:39 UTC, woju requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`Documentation/manifest-syntax.rst` line 462 at r6](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN3baQ4ECGMnyBSCPm0:-NN3baQ4ECGMnyBSCPm1:bcqww3x) ([raw file](https://github.com/gramineproject/gramine/blob/0a5cbe7929fd49a964a8b0db82c5cf0a8cc4dc5c/Documentation/manifest-syntax.rst#L462)):*
> ```reStructuredText
> before enclave creation (because it involves more enclave exits and syscalls).
> 
> .. note ::
> ```

no space before `::`


<!-- Sent from Reviewable.io -->

2023-01-30 21:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @oshogbo, and @woju)

___
*[`Documentation/manifest-syntax.rst` line 462 at r6](https://reviewable.io/reviews/gramineproject/gramine/1149#-NN3baQ4ECGMnyBSCPm0:-NN3cWGQ9ygMlAL8AXPa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0a5cbe7929fd49a964a8b0db82c5cf0a8cc4dc5c/Documentation/manifest-syntax.rst#L462)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

no space before `::`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 21:43 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-01-30 21:56 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-01-30 23:07 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1149#-:-NN3vta2AY0gRCkgeqhv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-31 07:47 UTC, dimakuv commented
Jenkins, retest pkg-rpm-almalinux9 please (`Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.almalinux.org/mirrorlist/9/appstream`, looks like some intermittent failure of Almalinux website)

2023-01-31 08:15 UTC, merged