[Pal] Emulate `iret` assembly instruction
gramineproject/gramine pull request #1166
Opened 2023-02-09 00:08 UTC by oshogbo

## Description of the changes 

Intel SGX prohibits the `iret` instruction; however, some applications (like ones based on ASP.NET) use it.
When `iret` is a used exception will be generated. This commit adds emulation of this instruction in the exception handler.

We assume that the `ss` and `cs` segments can't change. According to the amd64 documentation and my tests in 64-bit mode, `iret` always pops `ss` and `RSP`. 

I tried looking for the same info in Intel documentation, but it's more complex to understand this part.

## Useful links

* https://www.felixcloutier.com/x86/iret:iretd:iretq
* https://www.amd.com/system/files/TechDocs/24594.pdf

## How to test this PR? 

A new test is added.

2023-02-09 09:38 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpRQn3CcajugPZmc2v:-NNpRQn43s3EDrC2X2z4:b-yiepyg) (no related file):*
CI failed, please check

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpXUJv7B8XNp5VBGSd):*
The last two sentences seem redundant. I would remove them.
___
*[`libos/test/regression/iret_emulation.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWP0a8YKpkLLcuutQ:-NNpWP0a8YKpkLLcuutR:blc6nde) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L20)):*
> ```C
>         "pushq %%rax\n"
>         "pushq %0\n"
>         "pushq $0x00\n"
> ```

Why not push the RFLAGS itself? Is it to hide the effect of failing `idiv`?
___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNpWr2MAqfdQK9fIi-N:b-js5bdy) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
> ```C
>         "pushq %1\n"
>         "pushq %2\n"
>         "movq %3, %%rbp\n"
> ```

Why do we need to do this RBP re-assignment?
___
*[`libos/test/regression/iret_emulation.c` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpX0jf1ob7SJzhWmez:-NNpX0jf1ob7SJzhWmf-:b-nhbqoi) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L30)):*
> ```C
>           "r" (context->uc_mcontext.gregs[REG_RIP] + 3),
>           "r" (context->uc_mcontext.gregs[REG_RBP])
>         : "rax"
> ```

Shouldn't we also clobber `memory` (because of the stack pushes), `rsp` and `rbp`?
___
*[`libos/test/regression/iret_emulation.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpXCzv185oOyJXdxJZ:-NNpXCzv185oOyJXdxJ_:b-txclec) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L32)):*
> ```C
>         : "rax"
>     );
> }
> ```

Don't you want to `_exit(1)` or something in this sighandler, so we definitely fail (and not e.g. go into infinite #FP loop)
___
*[`libos/test/regression/iret_emulation.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVOSd4oTNTjuIanrb:-NNpVOSd4oTNTjuIanrc:bxeezed) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L38)):*
> ```C
> 
>     action.sa_sigaction = &sigfpe_handler;
>     action.sa_flags = SA_SIGINFO;
> ```

Why not just:
```
struct sigaction action = { .sa_sigaction = &sigfpe_handler, .sa_flags = SA_SIGINFO };
```
___
*[`libos/test/regression/iret_emulation.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVZkn9N5Vq1CGxv0h:-NNpVZkn9N5Vq1CGxv0i:bqxkke3) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L44)):*
> ```C
>     }
> 
>     __asm__ inline volatile (
> ```

Why `inline`?
___
*[`libos/test/regression/iret_emulation.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVvpn97rBiyA7Hw1h:-NNpVvpn97rBiyA7Hw1i:bu13jlo) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L47)):*
> ```C
>         "mov $0, %rax\n"
>         "mov $0, %rdx\n"
>         "idiv %rdx"
> ```

Shouldn't we have a clobber list with RAX and RDX here? How can the C code around this asm know that RAX and RDX must be "stashed"?
___
*[`libos/test/regression/tests.toml` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpRZX14udPTnLtezhQ:-NNpRZX14udPTnLtezhR:bu1aw0) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/tests.toml#L58)):*
> ```TOML
>   "host_root_fs",
>   "init_fail",
>   "iret_emulation",
> ```

Can we also test it in `tests_musl.toml`?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpURDl3NGgMeOOL3Jh:-NNpURDl3NGgMeOOL3Ji:b-l9acrn) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L120)):*
> ```C
>         log_warning("all RDTSC/RDTSCP instructions are emulated (imprecisely) via gettime() "
>                     "syscall.");
>     }
> ```

Could you add a one-time warning like this to your func?

I feel like if some app (like ASP.NET) uses `iretq`, it probably uses it quite frequently, and this will affect performance, so a warning would be really helpful.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpUWZe-5-W1dJbS3cW:-NNpUWZe-5-W1dJbS3cX:bwl9d2p) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L134)):*
> ```C
> 
> static void
> emulate_iret(sgx_cpu_context_t* uc)
> ```

Given my other comment above, I would rename to `emulate_iret_and_print_warning()`
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpSym_6nGSRwkGBP5R:-NNpSym_6nGSRwkGBP5S:b-x8jqv9) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L135)):*
> ```C
> static void
> emulate_iret(sgx_cpu_context_t* uc)
> {
> ```

Please use one line instead of three
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpUkM-3LWtrZtimnpy:-NNpUkM-3LWtrZtimnpz:b9z3yt1) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L140)):*
> ```C
> 
>         /* Assume that cs register doesn't change. */
> #ifdef __x86_64__
> ```

Too many ifdefs to my taste. I would move this ifdef to the very beginning of the func like this:
```
#ifndef __x86_64__
#error "cs and ss regs might change on this arch. Currently this is unsupported."
#endif
```

I'm not blocking though.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 144 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpTYNI-pidPxEOz2Pg:-NNpTYNI-pidPxEOz2Ph:b-n0ojaa) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L144)):*
> ```C
>             uint64_t cs = *(uint64_t*)(intptr_t)uc->rsp;
>             uint64_t curcs = 0;
>             __asm__ volatile inline (
> ```

What's this `inline` keyword? Why is this needed?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 166 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpU6zb5FeArLSjBTqi:-NNpU6zb5FeArLSjBTqj:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L166)):*
> ```C
>             uint64_t ss = *(uint64_t*)(intptr_t)uc->rsp;
>             uint64_t curss = 0;
>             __asm__ volatile inline (
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-02-09 11:44 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 3 of 6 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpRQn3CcajugPZmc2v:-NNpvScy6_Vc8DmkF8Tb:bg35vkl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI failed, please check
</blockquote></details>

Done. it is related to the inline asm.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpyzCD9fP5xK2M8SPy:-NNpyzCD9fP5xK2M8SPz:b-vjwi1n) (no related file):*
Sorry for the force push I'm trying to work with two repos (wips and push), and something went wrong.

___
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpXUJv7B8XNp5VBGSd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The last two sentences seem redundant. I would remove them.
</blockquote></details>

Done.
___
*[`libos/test/regression/iret_emulation.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWP0a8YKpkLLcuutQ:-NNpcGNI2BdxKqcNCXlJ:bojnxam) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not push the RFLAGS itself? Is it to hide the effect of failing `idiv`?
</blockquote></details>

Current RFLAGS contains the value of the exception/signal handler, not the main function.
As far as I know, the original RFLAGS isn't available in the context of the exception/singal handler.
___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNpbJgj1kWmweBBaB9F:b-f2t7es) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need to do this RBP re-assignment?
</blockquote></details>

After `iret` RBP will point to the stack of the exception/signal handler.
`iret` doesn't touch RBP.
___
*[`libos/test/regression/iret_emulation.c` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpX0jf1ob7SJzhWmez:-NNpe0uo2M8r9-QmVv72:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we also clobber `memory` (because of the stack pushes), `rsp` and `rbp`?
</blockquote></details>

Done.
___
*[`libos/test/regression/iret_emulation.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpXCzv185oOyJXdxJZ:-NNpe6oX4Pv4av4cimsj:b5ddlnd) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to `_exit(1)` or something in this sighandler, so we definitely fail (and not e.g. go into infinite #FP loop)
</blockquote></details>

Hmm, I think that this _exit(1) will be unreachable.
We are hijacking here a divide-by-zero signal.
I think if the "iret" won't recognized, it will throw other expectation that isn't handled, and the code will crash.
___
*[`libos/test/regression/iret_emulation.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVOSd4oTNTjuIanrb:-NNpeUUjDKLHvxv9EOAa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just:
```
struct sigaction action = { .sa_sigaction = &sigfpe_handler, .sa_flags = SA_SIGINFO };
```
</blockquote></details>

Done.
___
*[`libos/test/regression/iret_emulation.c` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVZkn9N5Vq1CGxv0h:-NNpcmoO6DOyHHD-JwpD:b-quera3) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `inline`?
</blockquote></details>

https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html
It's reduces the size. I will drop it. Its seems our CI doesn't like it.
___
*[`libos/test/regression/iret_emulation.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpVvpn97rBiyA7Hw1h:-NNpeZA99pTMhDF5MZ87:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we have a clobber list with RAX and RDX here? How can the C code around this asm know that RAX and RDX must be "stashed"?
</blockquote></details>

Done.
___
*[`libos/test/regression/tests.toml` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpRZX14udPTnLtezhQ:-NNpejTcC1QRrDKZNNcQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/tests.toml#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we also test it in `tests_musl.toml`?
</blockquote></details>

Done.



_Code quote:_
```TOML
iret_emulation
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpURDl3NGgMeOOL3Jh:-NNpfz1sAlX5dJi4sQbo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a one-time warning like this to your func?

I feel like if some app (like ASP.NET) uses `iretq`, it probably uses it quite frequently, and this will affect performance, so a warning would be really helpful.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpUWZe-5-W1dJbS3cW:-NNpfxCe-7j2XejncMjQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Given my other comment above, I would rename to `emulate_iret_and_print_warning()`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpSym_6nGSRwkGBP5R:-NNpfwyX3dey9ss3zvOr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/pal/src/host/linux-sgx/pal_exception.c#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use one line instead of three
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpUkM-3LWtrZtimnpy:-NNpfva65tB5JiHvj4kH:b-3e206n) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4d [...]

2023-02-09 13:15 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/iret_emulation.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWP0a8YKpkLLcuutQ:-NNqH3bL23T6kbFu_L2n:bl3gkm7) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Current RFLAGS contains the value of the exception/signal handler, not the main function.
As far as I know, the original RFLAGS isn't available in the context of the exception/singal handler.
</blockquote></details>

I don't understand what you mean. There is `uc_mcontext.gregs[REG_EFL]`.
___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNqHYGz6pNF6QKiZS6n:bzcq6gj) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

After `iret` RBP will point to the stack of the exception/signal handler.
`iret` doesn't touch RBP.
</blockquote></details>

Hm, that's right.

But don't we need to set **all GPRs** to values from `context`, so that `iret` returns to a correct state? I mean, you need to do a bunch of `movq <context-reg-rax>, %%rax`...
___
*[`libos/test/regression/iret_emulation.c` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpX0jf1ob7SJzhWmez:-NNqI-7C--AjlPUrIUYD:b-vpu1wa) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L30)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why you added `memory` but didn't add `rsp` and `rbp`?

Now that I think about your below comment, we actually don't care about the clobber list anyway, since after `iretq` we'll either jump to the new (constructed) context, or we'll fail. I mean, we'll never get past this inline-asm here, so the clobber list is redundant.
___
*[`libos/test/regression/iret_emulation.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpXCzv185oOyJXdxJZ:-NNqILUACabWAkpqPutO:bb74x83) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L32)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Hmm, I think that this _exit(1) will be unreachable.
We are hijacking here a divide-by-zero signal.
I think if the "iret" won't recognized, it will throw other expectation that isn't handled, and the code will crash.
</blockquote></details>

True
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNqIuVnCmyIkfhQMVv0:-NNqIuVnCmyIkfhQMVv1:b-383udx) ([raw file](https://github.com/gramineproject/gramine/blob/670e3b8f073b215d3590debd9969bec0f4b459da/pal/src/host/linux-sgx/pal_exception.c#L140)):*
> ```C
>     if (FIRST_TIME()) {
>         log_warning("Emulating a raw iret instruction. This degrades performance, consider"
>                     " patching your application to use Gramine syscall API.");
> ```

`consider patching your application ...` doesn't make sense for `iretq`. Please remove this part of the sentence.


<!-- Sent from Reviewable.io -->

2023-02-09 13:57 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/iret_emulation.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWP0a8YKpkLLcuutQ:-NNqNEjy6k4979Rw4U8j:b-zdeeo6) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand what you mean. There is `uc_mcontext.gregs[REG_EFL]`.
</blockquote></details>

Oh, I was looking for something more obvious...
Done.
___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNqMlz72F-fB_OoaRtm:bifgk4) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, that's right.

But don't we need to set **all GPRs** to values from `context`, so that `iret` returns to a correct state? I mean, you need to do a bunch of `movq <context-reg-rax>, %%rax`...
</blockquote></details>

In theory, yes, if we want to be super precise, then I thought if we care, in theory, the compilator can change an order of instructions to optimize some stuff, so dunno.
Maybe we can provide all GPPs as clabbered when we do division - it will be less work :)
___
*[`libos/test/regression/iret_emulation.c` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpX0jf1ob7SJzhWmez:-NNqMjFVAhiswLj4KDkG:b-ca8dp8) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why you added `memory` but didn't add `rsp` and `rbp`?

Now that I think about your below comment, we actually don't care about the clobber list anyway, since after `iretq` we'll either jump to the new (constructed) context, or we'll fail. I mean, we'll never get past this inline-asm here, so the clobber list is redundant.
</blockquote></details>

I agree this list doesn't make sense.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNqIuVnCmyIkfhQMVv0:-NNqMBxG6c34KGXzxrya:bv7od7n) ([raw file](https://github.com/gramineproject/gramine/blob/670e3b8f073b215d3590debd9969bec0f4b459da/pal/src/host/linux-sgx/pal_exception.c#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`consider patching your application ...` doesn't make sense for `iretq`. Please remove this part of the sentence.
</blockquote></details>

Why?
Originally this was my thought - it doesn't make sense because it's for an ASP.NET application, and then I thought that actually, other apps C/go/rust/whatever can still use it.

So I decided to do the message the same as in other emulated instructions.



_Code quote (from libos/test/regression/iret_emulation.c):_
```C
ucontext_t
```


<!-- Sent from Reviewable.io -->

2023-02-09 14:15 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNqWUO-4HtXVFTZwYnv:b-msjk7y) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
> Maybe we can provide all GPPs as clabbered when we do division - it will be less work :)

I like this trick, could we do it?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 140 at r3](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNqIuVnCmyIkfhQMVv0:-NNqWeeR772kDFdu3ZS6:bgit31) ([raw file](https://github.com/gramineproject/gramine/blob/670e3b8f073b215d3590debd9969bec0f4b459da/pal/src/host/linux-sgx/pal_exception.c#L140)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why?
Originally this was my thought - it doesn't make sense because it's for an ASP.NET application, and then I thought that actually, other apps C/go/rust/whatever can still use it.

So I decided to do the message the same as in other emulated instructions.
</blockquote></details>

Well... Yeah, I guess. Ok, resolving. Though I'd like to see that brave heart who would modify their app to use e.g. `rt_sigreturn()` syscall instead of the existing `iretq` :)


<!-- Sent from Reviewable.io -->

2023-02-09 14:52 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/iret_emulation.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNpWr2MAqfdQK9fIi-M:-NNqeSET3bY-porOSzRZ:bjwvzti) ([raw file](https://github.com/gramineproject/gramine/blob/c6d480073040ca4de27bc4cd85816cced54e4847/libos/test/regression/iret_emulation.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Maybe we can provide all GPPs as clabbered when we do division - it will be less work :)

I like this trick, could we do it?
</blockquote></details>

Done.

Please notice that rbp can't be clobbered.


<!-- Sent from Reviewable.io -->

2023-02-10 09:05 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/iret_emulation.c` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZHfl4zPmfDfXYBfp:-NNuZHfl4zPmfDfXYBfq:b-x743xt) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L31)):*
> ```C
>           "r" (context->uc_mcontext.gregs[REG_RIP] + 3),
>           "r" (context->uc_mcontext.gregs[REG_RBP])
>         : "rax"
> ```

Why did you reinstate `rax` in the clobber list? For sanity? If for sanity, then why not `rsp` and `memory`?
___
*[`libos/test/regression/iret_emulation.c` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZVVnDogSosS2gnhp:-NNuZVVnDogSosS2gnhq:bqufv19) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L48)):*
> ```C
>         :
>         :
>         : "rax", "rcx", "rdx", "rbx", "rsi", "rdi"
> ```

But why not `r8`, `r9`, etc. ?


<!-- Sent from Reviewable.io -->

2023-02-10 11:04 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/iret_emulation.c` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZHfl4zPmfDfXYBfp:-NNuxT-M-1bIQ6Z09mWw:bpous98) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you reinstate `rax` in the clobber list? For sanity? If for sanity, then why not `rsp` and `memory`?
</blockquote></details>

Because we use `rax` to read `ss`, without it `rax` might be used for providing one of the input variable "r".
___
*[`libos/test/regression/iret_emulation.c` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZVVnDogSosS2gnhp:-NNuxf8RBkHeRC6nv1Xc:b-rdworf) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why not `r8`, `r9`, etc. ?
</blockquote></details>

Ah sure.


<!-- Sent from Reviewable.io -->

2023-02-10 11:10 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/iret_emulation.c` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZHfl4zPmfDfXYBfp:-NNv-yLmEuTZ20XwOS64:b9psuy2) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L31)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Because we use `rax` to read `ss`, without it `rax` might be used for providing one of the input variable "r".
</blockquote></details>

Ah, of course.
___
*[`libos/test/regression/iret_emulation.c` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1166#-NNuZVVnDogSosS2gnhp:-NNv09dtB42YtftJ_09g:bq0dpet) ([raw file](https://github.com/gramineproject/gramine/blob/a0b1b152470d2e49e9d11081e22389ef3cd3c5c1/libos/test/regression/iret_emulation.c#L48)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ah sure.
</blockquote></details>

32-bit programming past? :)


<!-- Sent from Reviewable.io -->

2023-02-20 02:34 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/iret_emulation.c` line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOgdfdM1sF0WtbfbX38:-NOgdfdM1sF0WtbfbX39:b64c02b) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/libos/test/regression/iret_emulation.c#L40)):*
> ```C
>     if (sigaction(SIGFPE, &action, NULL) < 0) {
>         err(1, "unable to set singal handler");
>     }
> ```

CHECK(sigaction(SIGFPE, &action, NULL))



_Code quote:_
```C
    if (sigaction(SIGFPE, &action, NULL) < 0) {
        err(1, "unable to set singal handler");
    }
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOge1Ac1HQ02VruXfWt:b-64eu06) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
> ```C
>         uc->rcx = 0; /* dummy IA32_TSC_AUX; Linux encodes it as (numa_id << 12) | cpu_id */
>         return true;
>     } else if (0x40 <= instr[0] && instr[0] >= 0x48 && instr[1] == 0xcf) {
> ```

Sorry, I don't understand - shouldn't this be `40H to 4FH`, as the below cited?



_Code quote:_
```C
0x40 <= instr[0] && instr[0] >= 0x48
```


<!-- Sent from Reviewable.io -->

2023-02-20 05:47 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 139 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOhKAlJDmvKtcWw_Db2:-NOhKAlJDmvKtcWw_Db3:b-elz7fs) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L139)):*
> ```C
> 
>     if (FIRST_TIME()) {
>         log_warning("Emulating a raw iret instruction. This degrades performance, consider"
> ```

Rewrap to 100 chars?


<!-- Sent from Reviewable.io -->

2023-02-20 09:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`libos/test/regression/iret_emulation.c` line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOgdfdM1sF0WtbfbX38:-NOi6taqBh1Mc0qkdMKU:bbehj74) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/libos/test/regression/iret_emulation.c#L40)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

CHECK(sigaction(SIGFPE, &action, NULL))
</blockquote></details>

Good catch, we should use our own macros to make life easier
___
*[`libos/test/regression/iret_emulation.c` line 52 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOi707aCTX6PGQZPqBI:-NOi707aCTX6PGQZPqBJ:b-7dgq3a) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/libos/test/regression/iret_emulation.c#L52)):*
> ```C
>     );
> 
>     printf("TEST OK\n");
> ```

Btw, we typically use `puts()` for such no-variables strings.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 139 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOhKAlJDmvKtcWw_Db2:-NOi75Vh4eQX0HeCfEqg:b-1lojit) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L139)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Rewrap to 100 chars?
</blockquote></details>

Isn't it already wrapped? Well, let @oshogbo double-check -- maybe `patching` word can go to the first line.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOi7GuvDTCcx_Yb3VpK:btml5pl) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry, I don't understand - shouldn't this be `40H to 4FH`, as the below cited?
</blockquote></details>

Good catch, let me also block on @oshogbo's answer to this.


<!-- Sent from Reviewable.io -->

2023-02-20 12:50 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/test/regression/iret_emulation.c` line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOgdfdM1sF0WtbfbX38:-NOiqfwk14otDkUKBdD_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/libos/test/regression/iret_emulation.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good catch, we should use our own macros to make life easier
</blockquote></details>

Done.
___
*[`libos/test/regression/iret_emulation.c` line 52 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOi707aCTX6PGQZPqBI:-NOiqusQE25TaNLQeQtx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/libos/test/regression/iret_emulation.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, we typically use `puts()` for such no-variables strings.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 139 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOhKAlJDmvKtcWw_Db2:-NOirPtT5wNER3pJX-AM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it already wrapped? Well, let @oshogbo double-check -- maybe `patching` word can go to the first line.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOis0cA-2EFOqqiW4mz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good catch, let me also block on @oshogbo's answer to this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-20 13:19 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOiyAxU9rXwUoLBDbQz:bsf0kf6) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait what. This is not what we requested (we wanted `instr[0] <= 0x4F`), but now I'm wondering how your test successed at all, because this is the history of your changes:
- before you had `if (0x40 <= instr[0] && instr[0] >= 0x48 && instr[1] == 0xcf)` -- worked, which boils down to `instr[0] >= 0x48`
- now you have `if (0x40 <= instr[0] && instr[0] <= 0x48 && instr[1] == 0xcf)` -- works (??), which boils down to `instr[0] = 0x40..0x48`
- So where is `0x4F` in this equation??


<!-- Sent from Reviewable.io -->

2023-02-20 13:44 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOj-hnI60s8DxcLXaVs:brpyven) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait what. This is not what we requested (we wanted `instr[0] <= 0x4F`), but now I'm wondering how your test successed at all, because this is the history of your changes:
- before you had `if (0x40 <= instr[0] && instr[0] >= 0x48 && instr[1] == 0xcf)` -- worked, which boils down to `instr[0] >= 0x48`
- now you have `if (0x40 <= instr[0] && instr[0] <= 0x48 && instr[1] == 0xcf)` -- works (??), which boils down to `instr[0] = 0x40..0x48`
- So where is `0x4F` in this equation??
</blockquote></details>

The `iret` (in my test) generates `0x48`, which is why the previous code worked. But the condition is invalid. In the previous code:
```
0x40 <= instr[0] && instr[0] >= 0x48 
```
which is equivariant to:
```
instr[0] >= 0x40 && instr[0] >= 0x48 
```
Which gives everything above 0x48.

I wanted to use a syntax proposed by Michal in another PR, and I just broke it.

And the correct code, like in the comment, should look into: `0x40..0x4f`

Sorry I was sure I fixed both things.
Done.


<!-- Sent from Reviewable.io -->

2023-02-20 13:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOj6Feg2zD4Q_tOYkqW:b-b5fd7s) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
> Done.

Forgot to push?


<!-- Sent from Reviewable.io -->

2023-02-20 14:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOj8Q19E6cq0hVl0YcG:bb6ywmx) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Done.

Forgot to push?
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2023-02-20 15:00 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOjGVI_4xWc2IAoGNfB:bvuqzrw) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
> IRETQ
That makes sense.


<!-- Sent from Reviewable.io -->

2023-02-21 04:19 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 5 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 205 at r6](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOge1Ac1HQ02VruXfWs:-NOmBRti-hoIT003hpKM:b2c0zcb) ([raw file](https://github.com/gramineproject/gramine/blob/71fe7dbea7b0a9d74a677bf62bb70a2829ec2634/pal/src/host/linux-sgx/pal_exception.c#L205)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> IRETQ
That makes sense.
</blockquote></details>

LGTM, thanks!


<!-- Sent from Reviewable.io -->

2023-02-21 08:57 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 208 at r9](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOnAvbk-Bpni3zCl5JR:-NOnAvbk-Bpni3zCl5JS:b-kj9od2) ([raw file](https://github.com/gramineproject/gramine/blob/f1d8413b5299b35378938ab1f77bdffec4696fe5/pal/src/host/linux-sgx/pal_exception.c#L208)):*
> ```C
>         /*
>          * The IRETQ (interrupt return, 64-bit operand size), is prefixed with REX.W.
>          * The REX.W is the 3th bit (counting from 0).
> ```

`3th`? Did you mean `3rd`?

Also, this `counting from 0` is weird. Why not just:
```
The IRETQ (interrupt return, 64-bit operand size), is prefixed with REX.W (bit 3).
```


<!-- Sent from Reviewable.io -->

2023-02-21 09:27 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 208 at r9](https://reviewable.io/reviews/gramineproject/gramine/1166#-NOnAvbk-Bpni3zCl5JR:-NOnI4VT5r-zMeY1Nqga:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f1d8413b5299b35378938ab1f77bdffec4696fe5/pal/src/host/linux-sgx/pal_exception.c#L208)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`3th`? Did you mean `3rd`?

Also, this `counting from 0` is weird. Why not just:
```
The IRETQ (interrupt return, 64-bit operand size), is prefixed with REX.W (bit 3).
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-21 10:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-27 16:14 UTC, mkow requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIZgSo1qkzdOciVWLD):*
non-SGX PAL doesn't have this problem



_Suggestion:_
```
[PAL/Linux-SGX]
```
___
*[`libos/test/regression/iret_emulation.c` line 14 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIaKLV7ibj6bw76THr:-NPIaKLWCLak4StxqgSZ:b-p2nbw1) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/libos/test/regression/iret_emulation.c#L14)):*
> ```C
> 
> #include "common.h"
> ```

The way it's written this whole test is one huge UB:
- it manipulates stack from inline asm
- manually jumps back from an exception handler

This will be hell to maintain through GCC/glibc updates. This should rather be written like the ABI tests: just a few lines in assembly which try to use `iretq` to jump. Also, throwing an exception is not required to test `iretq`.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 139 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPI_xrr4g_S2bPYMXqN:-NPI_xrr4g_S2bPYMXqO:bgsz9b6) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L139)):*
> ```C
> 
>     if (FIRST_TIME()) {
>         log_warning("Emulating a raw iret instruction. This degrades performance, consider patching"
> ```

I guess this was just copy-pasted from somewhere? It doesn't make any sense here, what does `iret` has to do with syscalls?



_Code quote:_
```C
        log_warning("Emulating a raw iret instruction. This degrades performance, consider patching"
                    " your application to use Gramine syscall API.");
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 149 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPId5i7EqWC2PeoCvIl:-NPId5i88xl-QsE6c8Qs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L149)):*
> ```C
> #ifdef DEBUG
>     uint64_t cs = *(uint64_t*)(intptr_t)uc->rsp;
>     uint64_t curcs = 0;
> ```





_Suggestion:_
```C
uint64_t cur_cs
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 152 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPId2HP63NsoNZkMTNT:-NPId2HP63NsoNZkMTNU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L152)):*
> ```C
>     __asm__ volatile (
>         "movq %%cs, %0\n"
>         : "=r" (curcs)
> ```





_Suggestion:_
```C
"=r"(curcs)
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 167 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIdHOz3uTia7LfPVGT:-NPIdHOz3uTia7LfPVGU:b-tl63l7) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L167)):*
> ```C
> #ifdef DEBUG
>     uint64_t ss = *(uint64_t*)(intptr_t)uc->rsp;
>     uint64_t curss = 0;
> ```

ditto x2
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 207 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIbpE02vpUjt93OOh_:-NPIbpE02vpUjt93OOha:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L207)):*
> ```C
>     } else if (0x48 <= instr[0] && instr[0] <= 0x4F && instr[1] == 0xcf) {
>         /*
>          * The IRETQ (interrupt return, 64-bit operand size), is prefixed with REX.W (bit 3).
> ```





_Suggestion:_
```C
The IRETQ (interrupt return, 64-bit operand size), prefixed with REX.W (bit 3).
```


<!-- Sent from Reviewable.io -->

2023-03-01 15:42 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 0 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIZgSo1qkzdOciVWLD):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

non-SGX PAL doesn't have this problem
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 139 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPI_xrr4g_S2bPYMXqN:-NPIfIyzBf3rXyJ84RIq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this was just copy-pasted from somewhere? It doesn't make any sense here, what does `iret` has to do with syscalls?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 149 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPId5i7EqWC2PeoCvIl:-NPSnnMzAEDCyihndLIN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L149)):*
> ```C
> #ifdef DEBUG
>     uint64_t cs = *(uint64_t*)(intptr_t)uc->rsp;
>     uint64_t curcs = 0;
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 152 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPId2HP63NsoNZkMTNT:-NPSnnz86Cws7WPlhEfs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L152)):*
> ```C
>     __asm__ volatile (
>         "movq %%cs, %0\n"
>         : "=r" (curcs)
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 167 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIdHOz3uTia7LfPVGT:-NPSnrdh33ufpVUOL1je:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L167)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto x2
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 207 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIbpE02vpUjt93OOh_:-NPSnwvT1lROk45-zpiJ:bhmlmtf) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L207)):*
> ```C
>     } else if (0x48 <= instr[0] && instr[0] <= 0x4F && instr[1] == 0xcf) {
>         /*
>          * The IRETQ (interrupt return, 64-bit operand size), is prefixed with REX.W (bit 3).
> ```

Are you sure about removing `is`?
I think the comma is just an error here.
"The IRETQ is prefixed with REX.W"
___
*[`libos/test/regression/iret_emulation.c` line 14 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIaKLV7ibj6bw76THr:-NPSnZ-K4SUBOMNKl93N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/libos/test/regression/iret_emulation.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The way it's written this whole test is one huge UB:
- it manipulates stack from inline asm
- manually jumps back from an exception handler

This will be hell to maintain through GCC/glibc updates. This should rather be written like the ABI tests: just a few lines in assembly which try to use `iretq` to jump. Also, throwing an exception is not required to test `iretq`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-03 09:41 UTC, dimakuv requested changes
> Reviewed 5 of 16 files at r12, 10 of 10 files at r13, 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/test/regression/tests.toml` line 130 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPalcMqB4eU2oDddopQ:-NPalcMr0GhRziPJ2ctx:b124e1f) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/tests.toml#L130)):*
> ```TOML
>   "bootstrap_cpp",
>   "sighandler_divbyzero",
>   "x86_64/iret_emulation",
> ```

Well, technically we should move all manifests (and corresponding C files) that are listed here under that dir...

Could be done as a follow up PR. But could you add a TODO comment?

UPDATE: The current state (as of revision 16 of this PR) is very confusing. The new subdir `x86_64/` has only the sources + meson.build, but the rest of the infrastructure is in the top-level test dir. Also, only one x86-64-specific test (iretq emulation) is moved under the new dir, but not all the other ones (e.g. avx). We should make it uniform, or not make it at all.

I would actually prefer, at least for now, to keep the `iret_emulation` test in currently-existing dir (`libos/test/regression/`) and **remove x86_64 dir**. We can put a TODO to fix it later -- move all x86-64 tests under that new dir. But right now everything is confusing, and looks like not even working in our CI.

UPDATE 2: Ok, thought a bit more and I see your logic. Under `x86_64/`, you want to keep the pure-assembly tests. Still, I don't like the current ad-hoc placement of files. Could we make it more uniform?
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 13 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPaoWQqANmdY00lOBzQ:-NPaoWQqANmdY00lOBzR:bfooh5f) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L13)):*
> ```Assembly
> 
> %define NEW_RSP_VALUE   0x8811223344556677
> %define NEW_RFLAGS      0xED7
> ```

Could you put a comment why exactly this RFLAGS value? And why can't this value be in the RFLAGS before `test_rflags()` by accident?
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 23 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPaoI_O0EmFLIKvRgA4:-NPaoI_O0EmFLIKvRgA5:b1x0lbz) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L23)):*
> ```Assembly
> 
> test_rflags:
>     mov     rax, rsp
> ```

We're doing it first (before `push rdx` below) to land at the same stack address after `iretq` as we were at the start of this func, right? I.e., to not "lose" stack space.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 33 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPappP051eC14W63wj9:-NPappP112Eve_zUKEcC:b8mg4w0) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L33)):*
> ```Assembly
>     iretq
> 
> check_rsp:
> ```

Maybe put a comment that this func must **not** use the stack because RSP value is random garbage? Only after `mov rsp, rax` we can use the stack again.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 35 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPapjfZAczRpkR1070I:-NPaozek2_jZ2LtMmMFu:b-3okjhv) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L35)):*
> ```Assembly
> check_rsp:
>     mov     rdi, rsp
>     mov     rsp, rax
> ```

Could you put a comment that `rax` was assigned the "real" RSP in `test_rsp`'s first instruction?
___
*[`libos/test/regression/x86_64/meson.build` line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPanZGg5Ov4QASLf5Xx:-NPanZGg5Ov4QASLf5Xy:b-kqsb8x) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/meson.build#L11)):*
> ```Meson
> install_dir = pkglibdir / 'tests' / 'libos' / 'regression' / 'x86_64'
> 
> musl_execs = []
> ```

There seems to be no point in having Musl versions of asm tests, so please just remove this whole musl-specific logic.

My rationale is: the asm tests don't really use/stress libc functionality (other than `exit()` I guess), so what's the point of checking *two unused libcs*.
___
*[`libos/test/regression/x86_64/test_x86_64.py` line 7 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPamR9y1C2xl4f95xtI:-NPamR9y1C2xl4f95xtJ:b-gimaq3) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/test_x86_64.py#L7)):*
> ```Python
> class TC_00_X86_64(RegressionTestCase):
>     def test_010_iret_emulation(self):
>         self.run_binary(['x86_64/iret_emulation'])
> ```

I'm terribly confused. Who/when this script is called? I don't see any changes in the CI, so are you sure this test is even checked currently?


<!-- Sent from Reviewable.io -->

2023-03-05 18:31 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 16 of 17 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/tests.toml` line 130 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPalcMqB4eU2oDddopQ:-NPaqbvu8z7-ASbONTF5:b-wbln87) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/tests.toml#L130)):*

The main thing which might be confusing is that `gramine-test pytest` runs all tests from the given directory and all subdirectories.

Just as proof that it works with our CI:
https://leeroy.cs.unc.edu/job/graphene-18.04/9228/consoleText (this is for revision 16th):
```
[2023-03-01T21:09:09.019Z] test_libos.py::TC_91_RdtscSGX::test_000_rdtsc SKIPPED                    [ 98%]
[2023-03-01T21:09:09.019Z] test_libos.py::TC_92_avx::test_000_avx SKIPPED                           [ 99%]
[2023-03-01T21:09:09.019Z] x86_64/test_x86_64.py::TC_00_X86_64::test_010_iret_emulation PASSED      [100%]
```
(Please notice last line).

> I would actually prefer, at least for now, to keep the iret_emulation test in currently-existing dir (libos/test/regression/) and remove x86_64 dir. We can put a TODO to fix it later -- move all x86-64 tests under that new dir. But right now everything is confusing, and looks like not even working in our CI.

I didn't want to complicate `libos/test/regression/meson.build` for supporting assembly (it's already quite complex).
I also didn't want to mix C and asm tests.

I can move `iret_emulation` to its own `tests.toml`, however, this requires fixes in our `gramine-test` tool. The `gramine-test pytest` runs all tests in the directory and subdirectories. However, our manifest generator doesn't look for other `tests.toml` files in subdirectories.

We can generate manifests from `ci`, however then normal users would get an error while doing `gramine-test` manually, without prior generation of manifests.

I don't think you can include one toml from another one.

I can also move it outside the `regression` dir - which would be the most obvious solution. However, somehow, I like the logic that these tests are under the `regression` dir.

Maybe we should call it `asm/x86_64` or `asm_x86_64` or `asm:x86_64`?

Dunno.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 13 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPaoWQqANmdY00lOBzQ:-NPd4zqj24fkAS4U-3Z4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you put a comment why exactly this RFLAGS value? And why can't this value be in the RFLAGS before `test_rflags()` by accident?
</blockquote></details>

Done.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 23 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPaoI_O0EmFLIKvRgA4:-NPar7-E4e-ICf-gNyjw:bo2ysba) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We're doing it first (before `push rdx` below) to land at the same stack address after `iretq` as we were at the start of this func, right? I.e., to not "lose" stack space.
</blockquote></details>

Yes. Exactly.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 33 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPappP051eC14W63wj9:-NParAq27g6UIHfcXM54:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe put a comment that this func must **not** use the stack because RSP value is random garbage? Only after `mov rsp, rax` we can use the stack again.
</blockquote></details>

Done.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 35 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPapjfZAczRpkR1070I:-NParCni8HwZb2clruuA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/iret_emulation.nasm#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you put a comment that `rax` was assigned the "real" RSP in `test_rsp`'s first instruction?
</blockquote></details>

Done.
___
*[`libos/test/regression/x86_64/meson.build` line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPanZGg5Ov4QASLf5Xx:-NPd1p8K2qogSyvhuK_U:b-vu73xe) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/meson.build#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There seems to be no point in having Musl versions of asm tests, so please just remove this whole musl-specific logic.

My rationale is: the asm tests don't really use/stress libc functionality (other than `exit()` I guess), so what's the point of checking *two unused libcs*.
</blockquote></details>

My knowledge of `musl` is very limited.
If somebody runs tests with `musl`, does he also run tests with standard glibc?
___
*[`libos/test/regression/x86_64/test_x86_64.py` line 7 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPamR9y1C2xl4f95xtI:-NParHYq1OUMa9w3H7DN:b-6hkyjl) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/test_x86_64.py#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm terribly confused. Who/when this script is called? I don't see any changes in the CI, so are you sure this test is even checked currently?
</blockquote></details>

`gramine-test pytest` executes all subdirs.


<!-- Sent from Reviewable.io -->

2023-03-06 10:14 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/test/regression/tests.toml` line 130 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPalcMqB4eU2oDddopQ:-NPqPXc-BF0FOGj1411u:b-8lnvc8) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/tests.toml#L130)):*
> Maybe we should call it asm/x86_64 or asm_x86_64 or asm:x86_64?

+ 1 to `asm/x86_64`. Please do it.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 50 at r17](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPqNwZU3qcMNwPmCY-a:-NPqNwZU3qcMNwPmCY-b:b-tmewsp) ([raw file](https://github.com/gramineproject/gramine/blob/6cac9e808b9931519d48e537e6c9f46017481202/libos/test/regression/x86_64/iret_emulation.nasm#L50)):*
> ```Assembly
> test_rsp:
>     mov     rax, rsp           ; store current rsp in rax,
>                                ; this tests sets rsp to garbage value
> ```

`tests` -> `test`
___
*[`libos/test/regression/x86_64/meson.build` line 11 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPanZGg5Ov4QASLf5Xx:-NPqO2tS2GVy5IvCcX_X:btcdk1b) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/meson.build#L11)):*
> If somebody runs tests with musl, does he also run tests with standard glibc?

I don't understand this question. Do you mean what if someone built Gramine with `-Dglibc=disabled -Dmusl=enabled -Dtests=enabled`? Yeah, in this case I think this test will be skipped. But do we care? I wouldn't, since in our CI we always test with Glibc enabled.

To reiterate: I feel like the complexity of supporting musl gives zero benefit in terms of coverage.
___
*[`libos/test/regression/x86_64/test_x86_64.py` line 7 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPamR9y1C2xl4f95xtI:-NPqOSldBXJzkppqehTT:bu9bls7) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/x86_64/test_x86_64.py#L7)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

`gramine-test pytest` executes all subdirs.
</blockquote></details>

Got it, I didn't know this trick. Apparently this is how `pytest` works (https://docs.pytest.org/en/7.1.x/how-to/usage.html).


<!-- Sent from Reviewable.io -->

2023-03-06 13:22 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 10 of 20 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/tests.toml` line 130 at r16](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPalcMqB4eU2oDddopQ:-NPr4VPM4HQB-rTPnf2R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9b94fb20433b1fd62273c530985a1e931586f3e/libos/test/regression/tests.toml#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Maybe we should call it asm/x86_64 or asm_x86_64 or asm:x86_64?

+ 1 to `asm/x86_64`. Please do it.
</blockquote></details>

Done.
___
*[`libos/test/regression/x86_64/iret_emulation.nasm` line 50 at r17](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPqNwZU3qcMNwPmCY-a:-NPr4YMt71bqa-mrTphH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6cac9e808b9931519d48e537e6c9f46017481202/libos/test/regression/x86_64/iret_emulation.nasm#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tests` -> `test`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 17:30 UTC, dimakuv requested changes
> Reviewed 8 of 10 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/test/regression/asm/x86_64/Makefile` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxUMq-vjjJd-rdRAu:-NPrxUMs2btRxdsHFwaS:bskabmp) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/Makefile#L8)):*
> ```Makefile
> 	@echo "Use gramine-test for running tests."
> 
> # TODO: Python tests should not produce leftovers
> ```

Is this comment for `__pycache__`?
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 1 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPryJz_0Ga448IMiJTC:-NPryJz_0Ga448IMiJTD:bqq6hh) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

So having a separate `.py` pytest file works?
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxgQsC-G0Q94oK5Jn:-NPrxgQsC-G0Q94oK5Jo:b-iqnkt6) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L11)):*
> ```Python
> 
> class TC_00_X86_64(RegressionTestCase):
>     @unittest.skipIf(USES_MUSL, 'Assembly tests are disable with musl')
> ```

`disable` -> `disabled`
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxlQd7HdP81qMLPVP:-NPrxlQd7HdP81qMLPVQ:bhgo4ll) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L11)):*
> ```Python
> 
> class TC_00_X86_64(RegressionTestCase):
>     @unittest.skipIf(USES_MUSL, 'Assembly tests are disable with musl')
> ```

Won't this whole file be skipped if `USES_MUSL`? There should be a more generic way of skipping ALL tests in this file.


<!-- Sent from Reviewable.io -->

2023-03-09 13:03 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-04-09 16:40 UTC, mkow requested changes
> Reviewed 4 of 16 files at r12, 7 of 10 files at r13, 7 of 10 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 11 at r12](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPSqgjV6fmRlTowiVeU):*
?



_Code quote:_
```
squash! [python] Move graminelibos_offsets.py outside of graminelibos package
```
___
*[`libos/test/regression/Makefile` line 21 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSWNICTEr0mYKtq4ctv:-NSWNICTEr0mYKtq4ctw:b8ezgkh) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/Makefile#L21)):*
> ```Makefile
> 		tmp/* \
> 		tmp_enc/*
> 	$(MAKE) -C asm/x86_64 clean
> ```

I'd remove this (see the comment in that makefile)
___
*[`libos/test/regression/asm/x86_64/Makefile` line 12 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSWMner2Zo_pMNoRWbt:-NSWMner2Zo_pMNoRWbu:b-c5pei2) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/Makefile#L12)):*
> ```Makefile
> clean:
> 	$(RM) -r \
> 		__pycache__
> ```

If this is the only function of this makefile I'd just move it to the makefile in `regression` directory and remove this indirection.
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSalVrsBaNWcV_HtINo:-NSalVrsBaNWcV_HtINp:b-16hn0i) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
> ```Python
> )
> 
> @unittest.skipIf(USES_MUSL, 'Assembly tests are disabled with musl')
> ```

That's because they don't use libc at all, not because something doesn't work, right?
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaq_U562-3kr3Pslku:-NSaq_U562-3kr3Pslkv:bsk4dgv) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
> ```Python
> )
> 
> @unittest.skipIf(USES_MUSL, 'Assembly tests are disabled with musl')
> ```

It may be worth mentioning in a comment that this test actually tests Gramine emulation only on SGX, because `iret` doesn't case an exception in non-enclave ring3 and doesn't need emulation. But it doesn't hurt to run this test also on PAL/Linux to test the test itself.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 207 at r11](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPIbpE02vpUjt93OOh_:-NSalt3j2w7mdPCFm0_S:bn6h6x) ([raw file](https://github.com/gramineproject/gramine/blob/ef10c3bacdd3e566864354e693c7b4bb06c1d0e0/pal/src/host/linux-sgx/pal_exception.c#L207)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Are you sure about removing `is`?
I think the comma is just an error here.
"The IRETQ is prefixed with REX.W"
</blockquote></details>

Ah, that's what you meant. The updated version is good :)
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 136 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaosv-31wZzllnKuxU:-NSaosv-31wZzllnKuxV:bkfntqa) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/pal/src/host/linux-sgx/pal_exception.c#L136)):*
> ```C
> #ifndef __x86_64__
>     #error "cs and ss regs might change on this arch. Currently this is unsupported."
> #endif
> ```

I don't understand this message. If arch != x64 then `cs` and `ss` may change? This doesn't make any sense.



_Code quote:_
```C
#ifndef __x86_64__
    #error "cs and ss regs might change on this arch. Currently this is unsupported."
#endif
```
___
*[`libos/test/common/exit.nasm` line 1 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSam5TM3kkRTd0qKdVP:-NSam5TM3kkRTd0qKdVQ:b-kkcqgj) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/common/exit.nasm#L1)):*
> ```Assembly
> ; SPDX-License-Identifier: LGPL-3.0-or-later
> ```

Why did you move it out of `x86_64` directory? It's not portable outside x64. This can cause problems e.g. for stefanberger's ppc64 port.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTrA_BHRRYucbO-sg:-NSaTrA_BHRRYucbO-sh:bhvn33d) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
> ```Assembly
> 
> ; Turn on all EFLAGS.
> ; ABI x86_64 defines which are set and which are not.
> ```

Also, what does x86_64 ABI has to do with this test?



_Suggestion:_
```Assembly
x86_64 ABI defines
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NSaTv4rDV8Znp_a4Mnt:b-1b3yw6) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
> ```Assembly
> 
> ; Turn on all EFLAGS.
> ; ABI x86_64 defines which are set and which are not.
> ```

Which are set where/when? I don't understand what you mean here.



_Code quote:_
```Assembly
which are set and which are not
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 18 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaU3ss5mR8DK8GJSdb:-NSaU3ss5mR8DK8GJSdc:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L18)):*
> ```Assembly
> ; Please refer to x86_64 abi test for more details.
> ; In this test we set all of them, besides TF (trap flag),
> ; which can throw exception.
> ```





_Suggestion:_
```Assembly
which would cause an exception later.
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSagkoaCKAkavuoz20J:-NSagkoaCKAkavuoz20K:bzawsb0) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
> ```Assembly
> test_rflags:
>     mov     rax, rsp
>     mov     rdx, ss            ; ss register can't change
> ```

What do you mean? It definitely can change, it's writable.



_Code quote:_
```Assembly
ss register can't change
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 34 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSah-EYCstFItOaBkB0:-NSah-EZCF0zunEiVfqb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L34)):*
> ```Assembly
>     push    rax                ; new rsp
>     push    NEW_RFLAGS         ; new rflags
>     mov     rdx, cs            ; cs register can't change
> ```

ditto



_Code quote:_
```Assembly
cs register can't change
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 53 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSak8QS2hLC7KCXlUxv:-NSak8QS2hLC7KCXlUxw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L53)):*
> ```Assembly
>                                ; this  [...]

2023-04-13 14:32 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 13 of 21 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 11 at r12](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPSqgjV6fmRlTowiVeU):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Ofc wrong squash...
I will fix that on final rebase.
___
*[`libos/test/regression/Makefile` line 21 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSWNICTEr0mYKtq4ctv:-NSunyEH0E-_mOsSX8kU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/Makefile#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd remove this (see the comment in that makefile)
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/Makefile` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxUMq-vjjJd-rdRAu:-NQ10i3i-Xa8XJZmqjIu:b2637jv) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/Makefile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this comment for `__pycache__`?
</blockquote></details>

Yes.
And to be honest, the Makefile is copy pasted from:
`libos/test/regression/Makefile`
I just modified the list.
___
*[`libos/test/regression/asm/x86_64/Makefile` line 12 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSWMner2Zo_pMNoRWbt:-NSuipaJ-xRTXFh7FU91:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/Makefile#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this is the only function of this makefile I'd just move it to the makefile in `regression` directory and remove this indirection.
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 1 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPryJz_0Ga448IMiJTC:-NQ10yV43n_dg5YQh4Mn:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So having a separate `.py` pytest file works?
</blockquote></details>

Yes.
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxgQsC-G0Q94oK5Jn:-NQ14Psj0XOEOeDOhCfv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`disable` -> `disabled`
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1166#-NPrxlQd7HdP81qMLPVP:-NQ14QGY4izDD5boi-fb:bik5otc) ([raw file](https://github.com/gramineproject/gramine/blob/3ee95fefdf4a30965a9e6c57d94170764f961aab/libos/test/regression/asm/x86_64/test_x86_64.py#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Won't this whole file be skipped if `USES_MUSL`? There should be a more generic way of skipping ALL tests in this file.
</blockquote></details>

According to this https://docs.python.org/3/library/unittest.html
It should work now :)
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSalVrsBaNWcV_HtINo:-NSujAHq0KgJLzquM_Gn:b-7xt2jw) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's because they don't use libc at all, not because something doesn't work, right?
</blockquote></details>

Yes. 
___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaq_U562-3kr3Pslku:-NSuxhj60gmhXMck-EOP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It may be worth mentioning in a comment that this test actually tests Gramine emulation only on SGX, because `iret` doesn't case an exception in non-enclave ring3 and doesn't need emulation. But it doesn't hurt to run this test also on PAL/Linux to test the test itself.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 136 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaosv-31wZzllnKuxU:-NSujXhK-jNKnOgo_fGL:bjcmj1t) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/pal/src/host/linux-sgx/pal_exception.c#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this message. If arch != x64 then `cs` and `ss` may change? This doesn't make any sense.
</blockquote></details>

I changed it to that we don't support it.
___
*[`libos/test/common/exit.nasm` line 1 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSam5TM3kkRTd0qKdVP:-NSujpLlC8UIfVl7T1gh:bm7l83t) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/common/exit.nasm#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you move it out of `x86_64` directory? It's not portable outside x64. This can cause problems e.g. for stefanberger's ppc64 port.
</blockquote></details>

Do you mean you want `common/x86_64`? I like this idea.
I just moved to common as I assumed that each test would just include what it needs from this directory.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTrA_BHRRYucbO-sg:-NSuhee8Dg09Ky_pcbE1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Also, what does x86_64 ABI has to do with this test?
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NSuhioa7aRkXGs3vq7U:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Which are set where/when? I don't understand what you mean here.
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 18 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaU3ss5mR8DK8GJSdb:-NSuhmecCF63v4syxL0d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L18)):*
> ```Assembly
> ; Please refer to x86_64 abi test for more details. [...]

2023-04-13 23:31 UTC, mkow requested changes
> Reviewed 7 of 8 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSalVrsBaNWcV_HtINo:-NSwwPOo2sXj3yrmPkxk:b7zv885) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes. 
</blockquote></details>

Could you add this to the comment / error message? Will be clear why we didn't enabled it (and it's not obvious).
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NSwuCqPBsyKh396iDcu:b8py6ee) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, ok, now I understand this comment. But why does the value of eflags at the start matters at all for us? This comment seems weird and unrelated to anything in this test :)
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSagkoaCKAkavuoz20J:-NSwuv9p6b2g7NhKSsa8:b-37nywd) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
> We (me and you) decided this is a limitation of our implementation.

I know and you know, but some random user reading this comment won't know our discussions, review comments, etc.

If you want to explain this code then it should be rather something like "this test doesn't change ss, because Gramine doesn't support doing this through `iret`". This way it will be clear why this test doesn't change `ss`, instead of just stating this fact.


<!-- Sent from Reviewable.io -->

2023-04-14 08:33 UTC, dimakuv approved these changes
> Reviewed 4 of 8 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-04-14 08:33 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 8 files at r22.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-04-14 13:45 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 19 of 21 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/asm/x86_64/test_x86_64.py` line 10 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSalVrsBaNWcV_HtINo:-NSzz2196RsTbvwa_IqE:brp1594) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/test_x86_64.py#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add this to the comment / error message? Will be clear why we didn't enabled it (and it's not obvious).
</blockquote></details>

Yes, ofc.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NSzxbUW-j2-6R_DbQp1:b4iualr) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, ok, now I understand this comment. But why does the value of eflags at the start matters at all for us? This comment seems weird and unrelated to anything in this test :)
</blockquote></details>

Dima asked how we know what eflags values set, that we actually know that it was changed.
So I have added comment to highlight this part.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSagkoaCKAkavuoz20J:-NSzxtTeDSC_cvVeLN4a:b-87xsbq) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We (me and you) decided this is a limitation of our implementation.

I know and you know, but some random user reading this comment won't know our discussions, review comments, etc.

If you want to explain this code then it should be rather something like "this test doesn't change ss, because Gramine doesn't support doing this through `iret`". This way it will be clear why this test doesn't change `ss`, instead of just stating this fact.
</blockquote></details>

Sure make sense.
Thanks!


<!-- Sent from Reviewable.io -->

2023-04-14 13:55 UTC, mkow requested changes
> Reviewed 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NT-11Aj5q9-TPPCKghK:bmqu74h) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Dima asked how we know what eflags values set, that we actually know that it was changed.
So I have added comment to highlight this part.
</blockquote></details>

Oh, that's a good point, I missed this. This test should just set these flags explicitly before `iret` to something different, it's 2 more lines of code and 5 lines less of explaining why it works ;)

And relying on entrypoint rflags is very brittle, 1/4 of popular instructions on x86 change them...
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSagkoaCKAkavuoz20J:-NT-1k-u-20ChM4l9Z0D:b-z7k8l5) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sure make sense.
Thanks!
</blockquote></details>

I'd rather do it like this, because it's not obvious that these lines are a single paragraph (especially that below you treat each line separately).



_Suggestion:_
```Assembly
    mov     rdx, ss            ; this test doesn't change ss, because
                               ; Gramine doesn't support doing this through iret
    push    rdx
```


<!-- Sent from Reviewable.io -->

2023-04-14 14:56 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: 20 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 15 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSaTv4rDV8Znp_a4Mns:-NT-Cw5CCwjBzx6SSDKA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, that's a good point, I missed this. This test should just set these flags explicitly before `iret` to something different, it's 2 more lines of code and 5 lines less of explaining why it works ;)

And relying on entrypoint rflags is very brittle, 1/4 of popular instructions on x86 change them...
</blockquote></details>

Done.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r21](https://reviewable.io/reviews/gramineproject/gramine/1166#-NSagkoaCKAkavuoz20J:-NT-Cvji7TX0EIxjsmx1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9dab61c71500c1abdba32cee43b18360ba42c2dc/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather do it like this, because it's not obvious that these lines are a single paragraph (especially that below you treat each line separately).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-14 17:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r25](https://reviewable.io/reviews/gramineproject/gramine/1166#-NT-lNni2BET4bCGsN6f:-NT-lNni2BET4bCGsN6g:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d180dd4b8a5c7505355603c0422a6b05b0142a66/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
> ```Assembly
> 
> test_rflags:
>     push    ZERO_RFLAGS        ; make sure that current value of rflags is diffrent
> ```





_Suggestion:_
```Assembly
different
```
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 31 at r25](https://reviewable.io/reviews/gramineproject/gramine/1166#-NT-lTWz1PUt6nn_P7aK:-NT-lTX-9oiaTb777apX:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d180dd4b8a5c7505355603c0422a6b05b0142a66/libos/test/regression/asm/x86_64/iret_emulation.nasm#L31)):*
> ```Assembly
> test_rflags:
>     push    ZERO_RFLAGS        ; make sure that current value of rflags is diffrent
>                                ; then NEW_RFLAGS to verify that iret actually
> ```





_Suggestion:_
```Assembly
than
```


<!-- Sent from Reviewable.io -->

2023-04-14 17:24 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 30 at r25](https://reviewable.io/reviews/gramineproject/gramine/1166#-NT-lNni2BET4bCGsN6f:-NT-mv7NESDShyF38d1d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d180dd4b8a5c7505355603c0422a6b05b0142a66/libos/test/regression/asm/x86_64/iret_emulation.nasm#L30)):*
> ```Assembly
> 
> test_rflags:
>     push    ZERO_RFLAGS        ; make sure that current value of rflags is diffrent
> ```

Done.
___
*[`libos/test/regression/asm/x86_64/iret_emulation.nasm` line 31 at r25](https://reviewable.io/reviews/gramineproject/gramine/1166#-NT-lTWz1PUt6nn_P7aK:-NT-mvVg9YcVBiGfGpkq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d180dd4b8a5c7505355603c0422a6b05b0142a66/libos/test/regression/asm/x86_64/iret_emulation.nasm#L31)):*
> ```Assembly
> test_rflags:
>     push    ZERO_RFLAGS        ; make sure that current value of rflags is diffrent
>                                ; then NEW_RFLAGS to verify that iret actually
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-04-14 18:05 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-04-14 20:16 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r24, 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-14 23:36 UTC, merged