Enable unix domain socket between two different gramine instances
gramineproject/gramine pull request #1170
Opened 2023-02-13 05:56 UTC by ying2liu

Currently gramine only supports unix domain socket between child/parent within the same gramine instance, but some cloud use cases need unix domain socket between two different gramine instances. The commit enables this feature by removing namespace_id from namespace and adding manifest option to use sealing key as primary key.

Signed-off-by: Ying Liu <ying2.liu@intel.com>

## Description of the changes 

## How to test this PR
[uds_test.zip](https://github.com/gramineproject/gramine/files/10719125/uds_test.zips PR?

2023-02-13 11:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu)

___
*[`pal/src/pal_main.c` line 389 at r1](https://reviewable.io/reviews/gramineproject/gramine/1170#-NO9RLdiBXkij1TMumDx:-NO9RLdiBXkij1TMumDy:b-679kyc) ([raw file](https://github.com/gramineproject/gramine/blob/66e1527b0b99c50a084d387ffd0cfc97d548e346/pal/src/pal_main.c#L389)):*
> ```C
>     }
>     g_pal_common_state.parent_process = parent_process;
>     g_pal_public_state.namespace_id = instance_id;
> ```

Please rename `instance_id` to `namespace_id` everywhere, including in PAL code.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 677 at r1](https://reviewable.io/reviews/gramineproject/gramine/1170#-NO9QcA295Pk3hNR_eh5:-NO9QcA3EWNwdYhwG8ZW:buwqfhv) ([raw file](https://github.com/gramineproject/gramine/blob/66e1527b0b99c50a084d387ffd0cfc97d548e346/pal/src/host/linux-sgx/pal_main.c#L677)):*
> ```C
> +     * will be overwritten below in init_child_process() with inherited-from-parent master key if
> +     * this enclave is child */
>     if (g_pal_public_state.use_seal_key) {
> ```

Please remove this whole code that adds MRSIGNER-based sealing key. This PR was supposed to be an internal refactoring of Gramine code, without any new functionality.


<!-- Sent from Reviewable.io -->

2023-02-13 19:45 UTC, ying2liu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: 0 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/pal_main.c` line 389 at r1](https://reviewable.io/reviews/gramineproject/gramine/1170#-NO9RLdiBXkij1TMumDx:-NOBIZbs3C5JdOUYktuo:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/66e1527b0b99c50a084d387ffd0cfc97d548e346/pal/src/pal_main.c#L389)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `instance_id` to `namespace_id` everywhere, including in PAL code.
</blockquote></details>

done
___
*[`pal/src/host/linux-sgx/pal_main.c` line 677 at r1](https://reviewable.io/reviews/gramineproject/gramine/1170#-NO9QcA295Pk3hNR_eh5:-NOBIps3An8U8eINICg6:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/66e1527b0b99c50a084d387ffd0cfc97d548e346/pal/src/host/linux-sgx/pal_main.c#L677)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this whole code that adds MRSIGNER-based sealing key. This PR was supposed to be an internal refactoring of Gramine code, without any new functionality.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-02-20 06:50 UTC, llly reviewed
> Reviewed 4 of 13 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @ying2liu)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 668 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhVE3F-t9wNzGeblQ7:-NOhVE3G04gZBMGXQx4g:b-l41zuo) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L668)):*
> ```C
>     if (parent_stream_fd != -1) {
>         if ((ret = init_child_process(parent_stream_fd, &parent, &namespace_id)) < 0) {
>             log_error("Failed to initialize child process: %d", ret);
> ```

This error message seems to be changed by mistake.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 672 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOh_MjvAvtwtU-4ky6x:-NOh_MjvAvtwtU-4ky6y:bvm20ek) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L672)):*
> ```C
>         }
>     }
>     
> ```

Extra spaces.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 685 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhWpUfA9uNK2LGLd6v:-NOhWpUfA9uNK2LGLd6w:bvm20ek) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L685)):*
> ```C
>     g_pal_common_state.raw_manifest_data = manifest_addr;
>     g_pal_public_state.manifest_root = manifest_root;
>     
> ```

Extra spaces.


<!-- Sent from Reviewable.io -->

2023-02-20 09:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @ying2liu)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi3HVr5mhhtEyLCwnN):*
Suggest to also describe the changes (renaming) of `namespace_id`.
___
*[`libos/src/ipc/libos_ipc.c` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi-4gJ3eYGMAl_JoOx:-NOi-4gJ3eYGMAl_JoOy:b-o947vw) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/ipc/libos_ipc.c#L99)):*
> ```C
> 
> static int vmid_to_uri(IDTYPE vmid, char* uri, size_t uri_len) {
> ```

Pls kindly remove the blank line.
___
*[`pal/src/host/linux-common/gramine_unix_socket_addr.c` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2YC80Z5X3uxkMf5z:-NOi2YC80Z5X3uxkMf6-:bb3ms83) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-common/gramine_unix_socket_addr.c#L12)):*
> ```C
> 
> int get_gramine_unix_socket_addr(const char* name,
>                                   struct sockaddr_un* out_addr) {
> ```

Pls rewrap.
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 111 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhyRUB3RecDTkwgrnV:-NOhyRUB3RecDTkwgrnW:b-p7w920) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_pipes.c#L111)):*
> ```C
>  * \returns 0 on success, negative PAL error code otherwise.
>  *
>  * An abstract UNIX socket with name "/gramine/namespace_id>/<pipename>" is opened for listening. A
> ```

<namespace_id>



_Code quote:_
```C
namespace_id>
```


<!-- Sent from Reviewable.io -->

2023-02-20 09:14 UTC, dimakuv requested changes
> Reviewed 4 of 13 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @llly, and @ying2liu)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi223v2Jb4wsqb8Mek):*
`instance_id` should be in backticks
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2O9E6GDUPA1H-jdb):*
I would remove the word `cloud` -- who cares.
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2QPv2A-yX3qCKUl7):*
This last sentence seems wrong. We don't remove `instance_id`, we just push this logic (of creating UDSes in the same Gramine instance/namespace) from the PAL level to the LibOS level -- this will allow us in the future to have cross-namespace UDSes implemented purely at LibOS level.

Basically, the whole point of this PR is to make PAL "less knowledgeable' -- the PAL layer shouldn't be restricting what the LibOS layer can do.

So I would reword the last sentence like this:
```
This commit moves the current restriction of pipes + UDSes (that they can connect
to processes only within the same Gramine instances) from the PAL layer to LibOS
layer.
```

I would also add this side effect as a new paragraph:
```
As a side effect, this commit renames `instance_id` to a more appropriate
`namespace_id` ("Gramine instance" was a term we used to describe a set of
Gramine processes that can communicate with each other, but the better term
for this is "namespace").
```
___
*[`libos/include/libos_utils.h` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi3pqG5p5UmLYvtYEx:-NOi3pqG5p5UmLYvtYEy:b-m70iha) ([raw file](https://github.com/gramineproject/gramine/blob/aafaeb166e019f81322345df2cb8e4134cc07b33/libos/include/libos_utils.h#L53)):*
> ```objc
> 
> /* Get the IPC pipe uri associated with `vmid`. */
> int vmid_to_uri(IDTYPE vmid, char* uri, size_t uri_len);
> ```

For other reviewers: this is just a refactoring, because this function is used in a single file, so it can be declared as `static` in that file.
___
*[`libos/src/libos_init.c` line 549 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2E8f6NiXOCfRxRTk:-NOi2E8gDKUizrb2cy7L:b6lvzvr) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/libos_init.c#L549)):*
> ```C
>     while (true) {
>         if (use_vmid_for_name) {
>             len = snprintf(pipename, sizeof(pipename), "%lu/%u", g_pal_public_state->namespace_id, 
> ```

Trailing space
___
*[`libos/src/ipc/libos_ipc.c` line 100 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4UgQ7zApPGXYUJPj:-NOi4UgQ7zApPGXYUJPk:brnnrf7) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/ipc/libos_ipc.c#L100)):*
> ```C
> static int vmid_to_uri(IDTYPE vmid, char* uri, size_t uri_len) {
> 
>     int ret = snprintf(uri, uri_len, URI_PREFIX_PIPE "%lu/%u", g_pal_public_state->namespace_id, vmid);
> ```

Please rewrap to 100 char limit
___
*[`pal/include/pal/pal.h` line 177 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4dE_82KmlpWrpPtz:-NOi4dE_82KmlpWrpPu-:b-yqenhp) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/include/pal/pal.h#L177)):*
> ```objc
>     bool extra_runtime_domain_names_conf;
>     struct pal_dns_host_conf dns_host;
>     uint64_t namespace_id;
> ```

Actually, could you move this new field to the very beginning? It makes sense to make it more "visible" by having it as the very first item.
___
*[`pal/src/pal_main.c` line 377 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4lL401nwO5rc9Yfz:-NOi4lL401nwO5rc9Yg-:b-wygbbw) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/pal_main.c#L377)):*
> ```C
>  * configuration for early initialization.
>  */
> noreturn void pal_main(uint64_t namespace_id,       /* current namespace id */
> ```

The comment is misaligned now
___
*[`pal/src/host/linux/pal_pipes.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4v5W0zTT_MCV4Ytd:-NOi4v5W0zTT_MCV4Yte:b4rf15k) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux/pal_pipes.c#L33)):*
> ```C
>  * \returns 0 on success, negative PAL error code otherwise.
>  *
>  * An abstract UNIX socket with name "/gramine/<namespace_id>/<pipename>" is opened for listening. A
> ```

This is wrong now. PAL doesn't know about `namespace_id` -- this is done at the level of LibOS now.

So here you'll simply have `/gramine/<pipename>`
___
*[`pal/src/host/linux/pal_pipes.c` line 133 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi52fB1L5WZJ_cdrXJ:-NOi52fB1L5WZJ_cdrXK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux/pal_pipes.c#L133)):*
> ```C
>  *
>  * This function connects to the other end of the pipe, represented as an abstract UNIX socket
>  * "/gramine/<namespace_id>/<pipename>" opened for listening. When the connection succeeds, a new
> ```

ditto
___
*[`pal/src/host/linux-common/gramine_unix_socket_addr.c` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2YC80Z5X3uxkMf5z:-NOi59UP41fF4jCUpU21:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-common/gramine_unix_socket_addr.c#L12)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls rewrap.
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/pal_main.c` line 668 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhVE3F-t9wNzGeblQ7:-NOi1dPL1urkE6dZ40b0:b-qr4ssb) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L668)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

This error message seems to be changed by mistake.
</blockquote></details>

+1, this was a mistake
___
*[`pal/src/host/linux-sgx/pal_main.c` line 672 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOh_MjvAvtwtU-4ky6x:-NOi1gaZ3il3I_cnl8Q8:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L672)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Extra spaces.
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/pal_main.c` line 685 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhWpUfA9uNK2LGLd6v:-NOi1jHd16wFMphq5_kX:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L685)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Extra spaces.
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 111 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhyRUB3RecDTkwgrnV:-NOi5Iae3fg2_cCpSj7_:b-fufdry) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_pipes.c#L111)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

<namespace_id>
</blockquote></details>

No, this whole thing is wrong, please see my other comment (remove `namespace_id` completely from here)
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 245 at r2](https://reviewable.io/review [...]

2023-02-20 09:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @llly, and @ying2liu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiAYvQB6OkW1MN7Krl:-NOiAYvQB6OkW1MN7Krm:b-uthzxe) (no related file):*
Just noticed that the title is wrong. Once we finalize the PR, we should change the title (`Move instance_id from PAL to LibOS layer`?)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiAfyH8usKhtUgrT1p:-NOiAfyH8usKhtUgrT1q:bia0b43) (no related file):*
Let me explain some context of all this.

The idea of this PR is simple: it is a pure refactoring of the previous logic of "PAL puts a limitation on how pipes/UDSes are created" (previously PAL restricted them to only be visible to Gramine processes in the same "instance" aka "namespace").

This turned out to be a limitation for a Proof of Concept implementation of the inter-Gramine-instance communication on UDSes (two UDSes want to communicate in two different Gramine instances). There was a previous attempt at fixing this (https://github.com/gramineproject/gramine/pull/1132), but that attempt mixed independent things in one PR. So this new PR is a "clean" rewrite of one of the things from the previous PR.

The idea of this PR is to move the logic of "limitations on how pipes/UDSes are created" from PAL layer to the LibOS layer. This helps with inter-instance UDS communication mentioned above. But also in general -- this is the right approach for Gramine, because Gramine's PAL should not put unnecessary restrictions to what LibOS wants to do. If LibOS wants to talk to another Gramine instance (i.e., across namespaces), this should be allowed by PAL.

Finally, this looks like a good opportunity to remove the word instance from Gramine parlance, and replace it with a more familiar and wide-spread word namespace (which I think also reflects the "limitations" much better). This is a common term in Docker and Linux worlds, so we shouldn't invent our own glossary.

Note that https://github.com/gramineproject/gramine/issues/814 is partially related to this PR, but that issue is a hot mess of many different proposals, so one shouldn't pay much attention to that issue.

___


<!-- Sent from Reviewable.io -->

2023-02-20 10:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @ying2liu)

___
*[`pal/include/pal/pal.h` line 177 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4dE_82KmlpWrpPtz:-NOi9l_m4RXBYhcENo9X:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/include/pal/pal.h#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, could you move this new field to the very beginning? It makes sense to make it more "visible" by having it as the very first item.
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 111 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhyRUB3RecDTkwgrnV:-NOiANph3X7BEHy-Nr-i:b-hco108) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_pipes.c#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, this whole thing is wrong, please see my other comment (remove `namespace_id` completely from here)
</blockquote></details>

Right, `namespace_id` should be removed completely here.


<!-- Sent from Reviewable.io -->

2023-02-20 13:19 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, @llly, and @ying2liu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiAYvQB6OkW1MN7Krl:-NOiwfcR35fUlvCEgLna:bj8a1jd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed that the title is wrong. Once we finalize the PR, we should change the title (`Move instance_id from PAL to LibOS layer`?)
</blockquote></details>

+1, please fix the title and PR description, it's really misleading now.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiAfyH8usKhtUgrT1p:-NOixXzH0S8UjJpQf_uV:bk5akju) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me explain some context of all this.

The idea of this PR is simple: it is a pure refactoring of the previous logic of "PAL puts a limitation on how pipes/UDSes are created" (previously PAL restricted them to only be visible to Gramine processes in the same "instance" aka "namespace").

This turned out to be a limitation for a Proof of Concept implementation of the inter-Gramine-instance communication on UDSes (two UDSes want to communicate in two different Gramine instances). There was a previous attempt at fixing this (https://github.com/gramineproject/gramine/pull/1132), but that attempt mixed independent things in one PR. So this new PR is a "clean" rewrite of one of the things from the previous PR.

The idea of this PR is to move the logic of "limitations on how pipes/UDSes are created" from PAL layer to the LibOS layer. This helps with inter-instance UDS communication mentioned above. But also in general -- this is the right approach for Gramine, because Gramine's PAL should not put unnecessary restrictions to what LibOS wants to do. If LibOS wants to talk to another Gramine instance (i.e., across namespaces), this should be allowed by PAL.

Finally, this looks like a good opportunity to remove the word instance from Gramine parlance, and replace it with a more familiar and wide-spread word namespace (which I think also reflects the "limitations" much better). This is a common term in Docker and Linux worlds, so we shouldn't invent our own glossary.

Note that https://github.com/gramineproject/gramine/issues/814 is partially related to this PR, but that issue is a hot mess of many different proposals, so one shouldn't pay much attention to that issue.
</blockquote></details>

I still haven't seen a good design for inter-gramine UDSes, so no promise we'll ever have such a feature. But this PR makes sense on its own, so I'm fine with merging it.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOixqfbBnw1jrNvi5Bz):*




_Suggestion:_
```
UDS namespace
```
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiy75766JK0uExg3O1):*
This seems to be a quite misleading one-liner, this PR only refactors code, but it sounds like the UDSes will now work between Gramine namespaces.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiyNz7EoWfQEn0qdCu):*
I'd remove this part, we don't know if we'll be ever merging such functionality.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2O9E6GDUPA1H-jdb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove the word `cloud` -- who cares.
</blockquote></details>

And "cloud" has nothing to do with this case...


<!-- Sent from Reviewable.io -->

2023-02-20 13:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @llly, and @ying2liu)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiAfyH8usKhtUgrT1p:-NOj-H-ZDq2zGoAKo350:b6k8sts) (no related file):*
> I still haven't seen a good design for inter-gramine UDSes, so no promise we'll ever have such a feature.

I know, I know. I'm working on this now, so at some point I'll submit a PoC (or a GitHub issue for discussions, but I think it will be easier to just show real code). And then we'll discuss whether it's reasonable.

> But this PR makes sense on its own, so I'm fine with merging it.

Yep, that was the goal of splitting.

___


<!-- Sent from Reviewable.io -->

2023-02-28 01:00 UTC, ying2liu commented
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, please fix the title and PR description, it's really misleading now.
</blockquote></details>

Done.




<!-- Sent from Reviewable.io -->

2023-03-03 06:01 UTC, ying2liu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, @llly, and @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi223v2Jb4wsqb8Mek):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`instance_id` should be in backticks
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOixqfbBnw1jrNvi5Bz):*
Done.
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiy75766JK0uExg3O1):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems to be a quite misleading one-liner, this PR only refactors code, but it sounds like the UDSes will now work between Gramine namespaces.
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOiyNz7EoWfQEn0qdCu):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd remove this part, we don't know if we'll be ever merging such functionality.
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2O9E6GDUPA1H-jdb):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And "cloud" has nothing to do with this case...
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi3HVr5mhhtEyLCwnN):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to also describe the changes (renaming) of `namespace_id`.
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2QPv2A-yX3qCKUl7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This last sentence seems wrong. We don't remove `instance_id`, we just push this logic (of creating UDSes in the same Gramine instance/namespace) from the PAL level to the LibOS level -- this will allow us in the future to have cross-namespace UDSes implemented purely at LibOS level.

Basically, the whole point of this PR is to make PAL "less knowledgeable' -- the PAL layer shouldn't be restricting what the LibOS layer can do.

So I would reword the last sentence like this:
```
This commit moves the current restriction of pipes + UDSes (that they can connect
to processes only within the same Gramine instances) from the PAL layer to LibOS
layer.
```

I would also add this side effect as a new paragraph:
```
As a side effect, this commit renames `instance_id` to a more appropriate
`namespace_id` ("Gramine instance" was a term we used to describe a set of
Gramine processes that can communicate with each other, but the better term
for this is "namespace").
```
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 549 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi2E8f6NiXOCfRxRTk:-NP_u01O3c60OipD7c_c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/libos_init.c#L549)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Trailing space
</blockquote></details>

Done.
___
*[`libos/src/ipc/libos_ipc.c` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi-4gJ3eYGMAl_JoOx:-NP_u19i277fVCSq3iXC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/ipc/libos_ipc.c#L99)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls kindly remove the blank line.
</blockquote></details>

Done.
___
*[`libos/src/ipc/libos_ipc.c` line 100 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4UgQ7zApPGXYUJPj:-NP_u38wDkhExuo3Jw7B:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/libos/src/ipc/libos_ipc.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap to 100 char limit
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 177 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4dE_82KmlpWrpPtz:-NP_u4QZ4Nf-tXLNQav0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/include/pal/pal.h#L177)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pal/src/pal_main.c` line 377 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4lL401nwO5rc9Yfz:-NP_u5tP9Kk3VuZDrZ0C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/pal_main.c#L377)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is misaligned now
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_pipes.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi4v5W0zTT_MCV4Ytd:-NP_u6ulEPvdlGDHGpoh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux/pal_pipes.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong now. PAL doesn't know about `namespace_id` -- this is done at the level of LibOS now.

So here you'll simply have `/gramine/<pipename>`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_pipes.c` line 133 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOi52fB1L5WZJ_cdrXJ:-NP_u8Do50jyTFwrEOHF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux/pal_pipes.c#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_pipes.c` line 131 at r3](https://reviewable.io/reviews/gramineproject/gramine/1170#-NP_F6nC1X05qRG9L-zP:-NP_F6nC1X05qRG9L-zQ:b-ofcw9q) ([raw file](https://github.com/gramineproject/gramine/blob/2a8a02d42c11b732847199b1f2b3a8e1b5cb6482/pal/src/host/linux/pal_pipes.c#L131)):*
> backticks
___
*[`pal/src/host/linux-sgx/pal_main.c` line 668 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhVE3F-t9wNzGeblQ7:-NP_wlDjAT21Dox6XaNA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L668)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, this was a mistake
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 672 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOh_MjvAvtwtU-4ky6x:-NP_xxGF56sMn3M7tEEM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L672)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 685 at r2](https://reviewable.io/reviews/gramineproject/gramine/1170#-NOhWpUfA9uNK2LGLd6v:-NP_y5_W3kr6mFfxGYcX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e8d1c0675c26f80bea27a80bc1c560b305d4dda3/pal/src/host/linux-sgx/pal_main.c#L685)):*
<details><summary><i>Previously, dimakuv (Dmitrii Ku [...]

2023-03-03 08:54 UTC, dimakuv approved these changes
> Reviewed 9 of 9 files at r4, all commit messages.
> Dismissed @ying2liu from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @kailun-qin, @llly, @mkow, and @ying2liu)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
I would change the one liner to:
```
[LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS
```

Or should we keep the proposed ```[LibOS,PAL] Move `instance_id` from PAL to LibOS layer```? @mkow @kailun-qin 

Anyway, I can do it during final rebase
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeb020gKHllGFfn1Z):*
`instances`- > `instance`

I can do it during final rebase


<!-- Sent from Reviewable.io -->

2023-03-03 08:58 UTC, dimakuv commented
Jenkins, test this please

2023-03-06 07:40 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170#-:-NPprK_e25jW8UrFPgJb:bnfp4nl)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @llly, @mkow, and @ying2liu)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
> [LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS

+1 (to avoid further confusions on`instance_id` which we said to rename it to a more appropriate term).


<!-- Sent from Reviewable.io -->

2023-03-06 21:14 UTC, ying2liu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> [LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS

+1 (to avoid further confusions on`instance_id` which we said to rename it to a more appropriate term).
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeb020gKHllGFfn1Z):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`instances`- > `instance`

I can do it during final rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-07 10:12 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @mkow and @ying2liu)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeb020gKHllGFfn1Z):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2023-03-10 23:56 UTC, ying2liu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
> [LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS
Done
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeb020gKHllGFfn1Z):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

I thought you would do it during final rebase, but anyway I have modified it this time.


<!-- Sent from Reviewable.io -->

2023-03-13 09:04 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1170#-NPaeKA5Ec64opaU4pzs):*
<details><summary><i>Previously, ying2liu (Ying Liu) wrote…</i></summary><blockquote>

> [LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS
Done
</blockquote></details>

Ah, sorry, I misunderstood you. You wrote "Done" in this comment thread, even though you didn't actually do anything, and this confused me. Typically people don't leave the "Done" comment if the issue will be fixed later (e.g. at final rebase time). We keep these dangling comment threads specifically for the purpose of not forgetting to fix things during final rebase.


<!-- Sent from Reviewable.io -->

2023-03-13 09:04 UTC, dimakuv commented
Jenkins, test this please

2023-04-24 00:18 UTC, mkow requested changes
> Reviewed 2 of 13 files at r1, 4 of 12 files at r2, 5 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @ying2liu)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTk_emKCj3ao8LORoOQ):*
Hmm, I'm not sure if we want to do this rename, now it will be IMO quite confusing, because of Linux namespaces (to which this thing is unrelated). I preferred the old name, at least it didn't clash with anything else.
CC: @dimakuv

Also, even if, this shouldn't be done in this PR, now most of the changes in the diff is this renaming, not the real change it does.



_Code quote:_
```
`namespace_id`
```
___
*[`libos/src/ipc/libos_ipc.c` line 98 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTkafXn7bdxiwYuYTQB:-NTkafXn7bdxiwYuYTQC:bkrc7q8) ([raw file](https://github.com/gramineproject/gramine/blob/cd67fb79aa0f6df2335522522638b6c7aedaa859/libos/src/ipc/libos_ipc.c#L98)):*
> ```C
> }
> 
> static int vmid_to_uri(IDTYPE vmid, char* uri, size_t uri_len) {
> ```

While we are here, this is wrongly named. It's `uri`'s size, not length.



_Code quote:_
```C
size_t uri_len
```
___
*[`pal/src/pal_main.c` line 389 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTkbayN6AQcv12OVQxv:-NTkbZij6ah0fnwO7rhj:b-cgdxfk) ([raw file](https://github.com/gramineproject/gramine/blob/cd67fb79aa0f6df2335522522638b6c7aedaa859/pal/src/pal_main.c#L389)):*
> ```C
>     }
>     g_pal_common_state.parent_process = parent_process;
>     g_pal_public_state.namespace_id = namespace_id;
> ```

Why moving this line? It made more sense being first, right after the ID was generated. Now you put an unrelated line in between.


<!-- Sent from Reviewable.io -->

2023-04-24 07:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @ying2liu)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTk_emKCj3ao8LORoOQ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I'm not sure if we want to do this rename, now it will be IMO quite confusing, because of Linux namespaces (to which this thing is unrelated). I preferred the old name, at least it didn't clash with anything else.
CC: @dimakuv

Also, even if, this shouldn't be done in this PR, now most of the changes in the diff is this renaming, not the real change it does.
</blockquote></details>

Hm, ok, then we should stick with the old name `instance_id`, though I don't like it.


<!-- Sent from Reviewable.io -->

2023-04-25 18:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTk_emKCj3ao8LORoOQ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, ok, then we should stick with the old name `instance_id`, though I don't like it.
</blockquote></details>

@ying2liu Will you implement this requested change, or should I take over this PR? (If you won't answer until tomorrow's morning, then I'll take it over because I want to finish it quickly.)


<!-- Sent from Reviewable.io -->

2023-04-26 10:43 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @ying2liu)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/1170#-NTk_emKCj3ao8LORoOQ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@ying2liu Will you implement this requested change, or should I take over this PR? (If you won't answer until tomorrow's morning, then I'll take it over because I want to finish it quickly.)
</blockquote></details>

Ok, Ying timed out, so I am taking over this PR. I will fix according to @mkow's comment now.


<!-- Sent from Reviewable.io -->

2023-04-27 02:04 UTC, mkow approved these changes
> Reviewed 2 of 9 files at r4, 9 of 13 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-27 04:01 UTC, kailun-qin approved these changes
> Reviewed 2 of 13 files at r1, 3 of 9 files at r4, 9 of 13 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-27 08:37 UTC, dimakuv commented
Jenkins, test this please

2023-04-27 12:38 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-04-27 13:28 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-04-27 13:52 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1170)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-27 13:52 UTC, merged