[Docs] Mention `sgx.enclave_size` in EDMM enablement section
gramineproject/gramine pull request #1178
Opened 2023-02-15 08:30 UTC by dimakuv

## Description of the changes 

Many people have a feeling that when `sgx.edmm_enable = true`, they can remove `sgx.enclave_size`. Which is not true (the enclave size becomes the "maximum limit on the available enclave-memory space"). Let's make it more explicit in our documentation.

See #1174.

## How to test this PR? 

N/A.

2023-02-15 16:12 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpnna2yINx7_r6a5r):*
Sounds weird to me



_Suggestion:_
```
in "EDMM" section
```
___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOKpukB5XnkkdyBVZHs:b-mr5f9e) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
> ```reStructuredText
> Even when EDMM is enabled, it is still necessary to specify ``sgx.enclave_size``
> -- it specifies the *maximal* size that the enclave can grow to. In case of
> doubt, set this size to some large value like ``128G``.
> ```

What my proposal from this discussion under EDMM PR review? https://reviewable.io/reviews/gramineproject/gramine/1054#-NJuhiaXDbWKSYpitfwO (point 3)

Would be simpler for users and more intuitive.


<!-- Sent from Reviewable.io -->

2023-02-15 16:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpnna2yINx7_r6a5r):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds weird to me
</blockquote></details>

Will fix during final rebase
___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOKrZsDDJ-5gH39lvzC:b5le6jj) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
Do you mean this proposal:

> maybe the default for sgx.enclave_size should depend on EDMM being used?

We had a discussion with Borys on this (I suggested the same), but he argued that this is too much "magic". Actually, I'm even thinking -- maybe we should force users to specify `sgx.enclave_size` always, because the default `256MB` is also "magic" that only confuses people.

Also, what would be the default in case EDMM is enabled? How do we choose and justify this number? Won't it also be "magic" that will bite us on some unexpected workload?


<!-- Sent from Reviewable.io -->

2023-02-16 00:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOMVkHIC47eTBXDX5bd:b-z54ud5) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
> maybe we should force users to specify `sgx.enclave_size` always, because the default `256MB` is also "magic" that only confuses people.

I could agree with this, but only for the non-EDMM case.

> Also, what would be the default in case EDMM is enabled? How do we choose and justify this number? Won't it also be "magic" that will bite us on some unexpected workload?

Yeah, but I'm not sure you got my idea right. I'd like to set it to something really big, which should be enough for 99% of workloads. On x64 address space is cheap, and it's the address space of our own process, which we control. 1 TB maybe? That's 1/140 of the address space, so it sounds safe.

I just want to make configuring Gramine as simple as possible for majority of workloads.


<!-- Sent from Reviewable.io -->

2023-02-16 11:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOOsR5u9smrLDpWdEAC:bq4i950) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
> Yeah, but I'm not sure you got my idea right. I'd like to set it to something really big, which should be enough for 99% of workloads. On x64 address space is cheap, and it's the address space of our own process, which we control. 1 TB maybe? That's 1/140 of the address space, so it sounds safe.

We need to be careful with specifying such memory:
- https://github.com/gramineproject/gramine/blob/51f81f6f295fa4c33273029d505169c1a0534a4c/common/include/asan.h#L133
- https://github.com/gramineproject/gramine/blob/51f81f6f295fa4c33273029d505169c1a0534a4c/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.h#L7-L14

(These are the ones I remember about, I think there should be no other hard-coded memory areas.)

It actually may work fine with your suggested 1TB enclave size -- nothing will overlap. The only thing is that we need to make sure that in this case, we never perform this legacy hack: 
- https://github.com/gramineproject/gramine/blob/51f81f6f295fa4c33273029d505169c1a0534a4c/pal/src/host/linux-sgx/host_main.c#L277-L280
- https://github.com/gramineproject/gramine/blob/51f81f6f295fa4c33273029d505169c1a0534a4c/python/graminelibos/sgx_sign.py#L487-L488

@mkow Do you think we should go this route? I can create a PR then, instead of this one.


<!-- Sent from Reviewable.io -->

2023-02-16 14:00 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOPW16E7c3xzfnkuVg-:bo433na) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
> We need to be careful with specifying such memory:

We can just change this constant if it collides.

> @mkow Do you think we should go this route? I can create a PR then, instead of this one.

I don't see why not :)


<!-- Sent from Reviewable.io -->

2023-02-16 15:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1178)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 464 at r1](https://reviewable.io/reviews/gramineproject/gramine/1178#-NOKpukB5XnkkdyBVZHr:-NOPlx8j7v7BINqCCeSc:bb0x0xl) ([raw file](https://github.com/gramineproject/gramine/blob/27bb3af2b9fd13d868c1920e20c972d8f8a2e045/Documentation/manifest-syntax.rst#L464)):*
> We can just change this constant if it collides.

I wouldn't want to touch the ASan constant (1.5TB). It's nontrivial. You can read about the calculations in the comments here: https://github.com/gramineproject/gramine/blob/51f81f6f295fa4c33273029d505169c1a0534a4c/common/include/asan.h

That's why I wrote that whole comment before -- it's not as trivial as bumping these constants to some higher addresses.


<!-- Sent from Reviewable.io -->

2023-02-17 13:30 UTC, dimakuv commented
Superseded by another approach in https://github.com/gramineproject/gramine/pull/1187 and 
https://github.com/gramineproject/gramine/pull/1188

2023-02-17 13:30 UTC, closed without merging