[docker] Drop deprecated/unstable directives
gramineproject/gramine pull request #1181
Opened 2023-02-15 12:17 UTC by oshogbo

## Description of the changes 

Replace usage of `apt` with `apt-get`. The `apt` tool doesn't have a stable CLI interface, and it's not recommended to use it in Dockerfile.

Replace deprecated `apt-key` with `signed-by`.

As we are here - drop the `packaging` directory, as other packaging scripts (like `debian`) don't use it.

## How to test this PR? 

```
docker build .
```

2023-02-15 12:52 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOK6bQyD0CWONEwQh5t:-NOK6bQyD0CWONEwQh5u:budom86) ([raw file](https://github.com/gramineproject/gramine/blob/d7a6df78c8e5e1f782ac14e404838f5c56c4ce94/docker/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:20.04
> ```

Note on why we're using `20.04` and not the newer `22.04`:

This is because `az-dcap-client` package should be installed inside Docker containers based on this Docker image. And this package comes from Microsoft repositories (see our README on Dockerhub: https://hub.docker.com/r/gramineproject/gramine). Unfortunately, this particular package is still not available for `22.04`.

Even though it would be possible to still use the base image as `ubuntu:22.04` in this Dockerfile, **this would require hacks** to install the only available version of `az-dcap-client` (the one downloaded from `20.04` Microsoft repo).

So we decided *not* to mix 20.04 packages and 22.04 packages, and just keep the `20.04` base for now.


<!-- Sent from Reviewable.io -->

2023-02-15 16:33 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOKudBA2iT2SPLLr0xE):*
That's bad, we should do this. `debian/` was an exception because woju was willing to die for it, so we ended up with it in the toplevel, but there's no reason to start putting everything at toplevel now...
___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOK6bQyD0CWONEwQh5t:-NOKut_q3kf6Sl6vMLSt:b-jektur) ([raw file](https://github.com/gramineproject/gramine/blob/d7a6df78c8e5e1f782ac14e404838f5c56c4ce94/docker/Dockerfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note on why we're using `20.04` and not the newer `22.04`:

This is because `az-dcap-client` package should be installed inside Docker containers based on this Docker image. And this package comes from Microsoft repositories (see our README on Dockerhub: https://hub.docker.com/r/gramineproject/gramine). Unfortunately, this particular package is still not available for `22.04`.

Even though it would be possible to still use the base image as `ubuntu:22.04` in this Dockerfile, **this would require hacks** to install the only available version of `az-dcap-client` (the one downloaded from `20.04` Microsoft repo).

So we decided *not* to mix 20.04 packages and 22.04 packages, and just keep the `20.04` base for now.
</blockquote></details>

Could someone who has good contact to them go there and complain? This is blocking us from supporting 22.04.


<!-- Sent from Reviewable.io -->

2023-02-15 17:03 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOKudBA2iT2SPLLr0xE):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's bad, we should do this. `debian/` was an exception because woju was willing to die for it, so we ended up with it in the toplevel, but there's no reason to start putting everything at toplevel now...
</blockquote></details>

As always, I am neutral on this.
___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOK6bQyD0CWONEwQh5t:-NOL0qXN3pIwyva6jRTM:bjuxnlf) ([raw file](https://github.com/gramineproject/gramine/blob/d7a6df78c8e5e1f782ac14e404838f5c56c4ce94/docker/Dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could someone who has good contact to them go there and complain? This is blocking us from supporting 22.04.
</blockquote></details>

https://github.com/microsoft/Azure-DCAP-Client/issues/175 -- I created an issue. Maybe that's enough.


<!-- Sent from Reviewable.io -->

2023-02-15 20:58 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOKudBA2iT2SPLLr0xE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As always, I am neutral on this.
</blockquote></details>

I'm not planning to die for it :)
It's just a proposition to try to have everything in place.


<!-- Sent from Reviewable.io -->

2023-02-15 20:59 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1181#-NOK6bQyD0CWONEwQh5t:-NOLs0MEBZvXG5vy2jre:b-9755fn) ([raw file](https://github.com/gramineproject/gramine/blob/d7a6df78c8e5e1f782ac14e404838f5c56c4ce94/docker/Dockerfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/microsoft/Azure-DCAP-Client/issues/175 -- I created an issue. Maybe that's enough.
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2023-02-16 00:06 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-16 10:27 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-20 10:51 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-02-20 10:52 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1181)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-02-20 12:47 UTC, merged