Nirjhar royiitk/issue 1191 in out instruction throwing sigill
gramineproject/gramine pull request #1192
Opened 2023-02-21 09:31 UTC by NirjharRoyiitk

## Description of the changes  Fixes #1191 : in and out instruction causes SIGILL instead of SIGSEGV. in and out instructions aren't allowed inside SGX enclaves and hence throws SIGILL but native behavior of user applications is that in / out instructions throws SIGSEGV. ```lscpu``` is requires this fix and lscpu is sometimes used in tensorflow applications and that is why this was required.

 Fixes #1191

## How to test this PR?  ```cd libos/test/fs/ && gramine-test --sgx pytest  -v -k TC_11_Lscpu``` --> Run this command from Gramine root repo

2023-02-21 09:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 0 of 6 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NirjharRoyiitk)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNc8d808OgMfsTMHp):*
The two commits should be merged into one. There is no sense in splitting them.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNfzPB7mCOkTCwhCT):*
Also, please check out how we format commit message titles and bodies (just check the history of commits), and please apply the same rules here.

Feel free to force-push the changes, since noone is actively reviewing this PR yet.
___
*[`libos/src/bookkeep/libos_signal.c` line 503 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNtzK3m67k94QCe0Y:-NOnNtzLDQswFfGAMDUX:b6imu7t) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/src/bookkeep/libos_signal.c#L503)):*
> ```C
>          * https://c9x.me/x86/html/file_module_x86_id_222.html (for OUT instruction)
>          * 
>          * Some other releavant links 
> ```

I would remove all these "relevant links", they don't deserve to be in the codebase. Instead, you can put them as one of the Reviewable comments, or even just add them to the PR description.
___
*[`libos/src/bookkeep/libos_signal.c` line 525 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnO0kf9ZYU1cfGEAfM:-NOnO0kf9ZYU1cfGEAfN:bcziyew) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/src/bookkeep/libos_signal.c#L525)):*
> ```C
>         log_debug("Illegal instruction (or legal but unsupported instruction "\
>                   "inside enclave) during app execution at %p; delivering to app", rip);
>         
> ```

Please never leave trailing whitespaces in PRs.
___
*[`libos/test/fs/lscpu-test.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnO59R523HP5_7Ja80:-NOnO59S2RiF1Zzbua8B:b-69xc3n) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L17)):*
> ```C
> 
> #define EXPECTED_NUM_SIGSEGVS 2
> #define COMMAND "/usr/bin/lscpu"
> ```

Please remove the sub-test for `lscpu` from this test. This command may not be installed on many systems, and to test your added functionality, it is enough to have the synthetic `in`/`out` assembly snippets.
___
*[`libos/test/fs/lscpu-test.c` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOJfM3uDM53dHjiAE:-NOnOJfM3uDM53dHjiAF:b-icgd41) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L24)):*
> ```C
> 
> static void fault_handler(int ignored)
> {
> ```

Please read our coding guidelines: https://gramine.readthedocs.io/en/stable/devel/coding-style.html
___
*[`libos/test/fs/lscpu-test.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOIYZ7iseF2rX5kBT:-NOnOIYZ7iseF2rX5kBU:b-x2dezk) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L26)):*
> ```C
> {
>     g_sigsegv_triggered++;
>     siglongjmp(g_point, 1);
> ```

We'll need to review the use of longjmp here, I'm not a fan (and it's probably a UD?)
___
*[`libos/test/fs/lscpu-test.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOT7kCPF9qtQmn96D:-NOnOT7kCPF9qtQmn96E:bi71bdu) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L58)):*
> ```C
>     assert(ret == 0);
> 
>     printf("\nlscpu-test test passed\n");
> ```

Please check other tests, that's not how we print success.
___
*[`libos/test/fs/lscpu-test.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOXSd0s7Jkj0t3hGq:-NOnOXSd0s7Jkj0t3hGr:b-vxhp62) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.manifest.template#L1)):*
> ```
> loader.entrypoint = "file:{{ gramine.libos }}"
> ```

Why do you need a separate manifest for this test? Because of `lscpu`? I suggest to remove `lscpu` from this test completely, and instead just use the generic `manifest.template` (i.e., you won't need to add anything special to this PR)
___
*[`libos/test/fs/test_lscpu.py` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOl0x9-60IoNIm0tQ:-NOnOl0x9-60IoNIm0tR:b-11k9qb) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/test_lscpu.py#L11)):*
> ```Python
> 
>     def setUp(self):
>         pass
> ```

Why do you need these `setUpClass` and `setUp`?

Generally, please remove `lscpu` program from your test, and put this test under some already-existing class here.
___
*[`libos/test/fs/tests.toml` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOhr02QcLYFINIyM2:-NOnOhr02QcLYFINIyM3:bek8qt1) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/tests.toml#L21)):*
> ```TOML
>   "stat",
>   "truncate",
>   "lscpu-test"
> ```

You'll need to also add the test to `tests-musl.toml`


<!-- Sent from Reviewable.io -->

2023-02-21 12:34 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 0 of 7 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNc8d808OgMfsTMHp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The two commits should be merged into one. There is no sense in splitting them.
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNfzPB7mCOkTCwhCT):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, please check out how we format commit message titles and bodies (just check the history of commits), and please apply the same rules here.

Feel free to force-push the changes, since noone is actively reviewing this PR yet.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 503 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNtzK3m67k94QCe0Y:-NOnxT2kEAGYuClKSx_P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/src/bookkeep/libos_signal.c#L503)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove all these "relevant links", they don't deserve to be in the codebase. Instead, you can put them as one of the Reviewable comments, or even just add them to the PR description.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 525 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnO0kf9ZYU1cfGEAfM:-NOnxUq_5IzF4IB1HHIN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/src/bookkeep/libos_signal.c#L525)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please never leave trailing whitespaces in PRs.
</blockquote></details>

Done.
___
*[`libos/test/fs/tests.toml` line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOhr02QcLYFINIyM2:-NOnxe_4DBsTlheZxGjs:b-j1nszp) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/tests.toml#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You'll need to also add the test to `tests-musl.toml`
</blockquote></details>

This wasn't required for my test.
___
*[`libos/test/fs/lscpu-test.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOXSd0s7Jkj0t3hGq:-NOnxlWb4O4_COx11-Zh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need a separate manifest for this test? Because of `lscpu`? I suggest to remove `lscpu` from this test completely, and instead just use the generic `manifest.template` (i.e., you won't need to add anything special to this PR)
</blockquote></details>

Done.
___
*[`libos/test/fs/test_lscpu.py` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOl0x9-60IoNIm0tQ:-NOnxnmy8qBHKoJgqweE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/test_lscpu.py#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need these `setUpClass` and `setUp`?

Generally, please remove `lscpu` program from your test, and put this test under some already-existing class here.
</blockquote></details>

Done.
___
*[`libos/test/fs/lscpu-test.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnO59R523HP5_7Ja80:-NOnxWqEEpreRuMpMiDU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the sub-test for `lscpu` from this test. This command may not be installed on many systems, and to test your added functionality, it is enough to have the synthetic `in`/`out` assembly snippets.
</blockquote></details>

Done.
___
*[`libos/test/fs/lscpu-test.c` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOJfM3uDM53dHjiAE:-NOnxXqL3SpN_2TgQ_bu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please read our coding guidelines: https://gramine.readthedocs.io/en/stable/devel/coding-style.html
</blockquote></details>

Done.
___
*[`libos/test/fs/lscpu-test.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOT7kCPF9qtQmn96D:-NOnxaozCebSvdEpamMi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please check other tests, that's not how we print success.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-21 18:20 UTC, arai-fortanix commented on libos/test/fs/tests.toml
> +  "in_out_instruction_test"
The new test should probably be inserted in alphabetical order.

2023-02-21 18:28 UTC, arai-fortanix commented on libos/src/bookkeep/libos_signal.c
> +    unsigned char opcodes[] = {0xe4, 0xe5, 0xec, 0xed, 0xe6, 0xe7,
I think it's worth having comments to explain which instruction each opcode corresponds to.

2023-02-22 09:52 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 0 of 7 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix and @dimakuv)

___
*[`libos/src/bookkeep/libos_signal.c` line 468 at r2](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnJ1Hui1phZX2-Usu_-r2-468:-NOs5skIEoMx68G9_fZC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f436c12b62c34c66f07e79d9a6906ee90ddd4b8f/libos/src/bookkeep/libos_signal.c#L468)):*
<details><summary><i>Previously, arai-fortanix (Daniel Arai) wrote…</i></summary><blockquote>

I think it's worth having comments to explain which instruction each opcode corresponds to.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 471 at r2](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnJ1Hui1phZX2-Usu_-r2-471:-NOs9KxF9jV_iDCxL01K:b-3agjg4) ([raw file](https://github.com/gramineproject/gramine/blob/f436c12b62c34c66f07e79d9a6906ee90ddd4b8f/libos/src/bookkeep/libos_signal.c#L471)):*
<details><summary><i>Previously, arai-fortanix (Daniel Arai) wrote…</i></summary><blockquote>

I don't think the check here doesn't cover all possible encodings of these instructions. x86 typically allows things like segment overrides and opsize and code size overrides, even if they don't make sense for the instruction being encoded.
</blockquote></details>

Done. Took the prefix values from https://wiki.osdev.org/X86-64_Instruction_Encoding
___
*[`libos/test/fs/tests.toml` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnJ1Hui1phZX2-Usub-r2-21:-NOs61C1E3XwahAIPpgl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f436c12b62c34c66f07e79d9a6906ee90ddd4b8f/libos/test/fs/tests.toml#L21)):*
<details><summary><i>Previously, arai-fortanix (Daniel Arai) wrote…</i></summary><blockquote>

The new test should probably be inserted in alphabetical order.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-22 14:22 UTC, dimakuv requested changes
> Reviewed 4 of 7 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix and @NirjharRoyiitk)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNfzPB7mCOkTCwhCT):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still wrong:
- Should be `[LibOS]`
- The title is too long and doesn't start with a verb

I would suggest like this:
```
[LibOS] Emulate in/out instructions as if they generate SIGSEGV

Executing I/O instructions (e.g., in/out) inside an SGX enclave generates
a #UD fault. Gramine's PAL tries to handle this exception and propogates
it to LibOS/app as a SIGILL signal.

However, I/O instructions result in a #GP fault (which raises a SIGSEGV
signal) if I/O is not permitted. Let Gramine emulate these instructions as
if they end up in SIGSEGV. This helps some apps, e.g. `lscpu`.
```
___
*[`libos/src/bookkeep/libos_signal.c` line 465 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTyDNCne2hBq3EtYk:-NOtTyDNCne2hBq3EtYl:ba8c8kc) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L465)):*
> ```C
>     uint8_t prefix_list[] = {
>                              /* Group 0 */ 
>                              0xf0, /* LOCK prefix */
> ```

LOCK prefix is not allowed with IN/OUT/INS/OUTS instructions, so it's meaningless to check it here
___
*[`libos/src/bookkeep/libos_signal.c` line 476 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtU45JDtgHIOGUlsE7:-NOtU45JDtgHIOGUlsE8:b-yd46me) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L476)):*
> ```C
>                              0x65, /* GS segment override */
>                              0x2e, /* Branch not taken */
>                              0x3e, /* Branch taken */
> ```

I think this whole Group 1 of prefixes is useless for 64-bit IN/OUT/... instructions?
___
*[`libos/src/bookkeep/libos_signal.c` line 484 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUHUy8uiROJtn2wjs:-NOtUHUzDMJ1yWXynpLI:b-voiex6) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L484)):*
> ```C
>                               * for the instruction(s) we are checking.
>                               */
>                             };
> ```

Out of all these, I think only REP and 0x66 and 0x67 prefixes make sense with IN/OUT instructions
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUVv8BpgcOqcQrzdq:-NOtUVv8BpgcOqcQrzdr:b-yd8t6f) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
> ```C
>                             };
>     size_t num_prefixes = sizeof(prefix_list)/sizeof(*prefix_list);
>     for(int i = 0; i < num_prefixes; i++) {
> ```

In Gramine, for such cases we use `size_t` instead of `int`
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUZNAE5NL_dgyKy1l:-NOtUZNAE5NL_dgyKy1m:b-xjfhd2) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
> ```C
>                             };
>     size_t num_prefixes = sizeof(prefix_list)/sizeof(*prefix_list);
>     for(int i = 0; i < num_prefixes; i++) {
> ```

We have a 100 char limit, so you can remove helper var `num_prefixes` and just embed the equation
___
*[`libos/src/bookkeep/libos_signal.c` line 497 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUg9WC_iKjsG_UvqW:-NOtUg9WC_iKjsG_UvqX:bom8i89) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L497)):*
> ```C
>  * This function checks if the rip on which the exception is occuring is a valid 
>  * opcode for in or out instruction.
>  */
> ```

I would remove this whole comment -- the func is self explanatory.
___
*[`libos/src/bookkeep/libos_signal.c` line 499 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUl9n091pswcBBnWW:-NOtUl9n091pswcBBnWX:b-xuat5q) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L499)):*
> ```C
>  */
> static bool is_in_out(PAL_CONTEXT* context) {
>     unsigned char opcodes[] = {
> ```

`uint8_t` please
___
*[`libos/src/bookkeep/libos_signal.c` line 509 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTRg1BbNcTsVSOWdw:-NOtTRg1BbNcTsVSOWdx:bor33t0) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L509)):*
> ```C
>                                0xe7, /* OUT imm8, AX/EAX */
>                                0xee, /* OUT DX, AL */
>                                0xef, /* OUT DX, AX */
> ```

I would also add INS/... family of instructions, and OUTS/... family of instructions in this list.
___
*[`libos/src/bookkeep/libos_signal.c` line 516 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtV4rB94HkfISsGame:-NOtV4rB94HkfISsGamf:b-43tw4s) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L516)):*
> ```C
>     /* num_prefixes_found will store the actual opcode index in rip */
>     size_t num_prefixes_found = 0;
>     for(int i = 0; i < num_prefixes_to_check; i++) {
> ```

Please add a space after `for`

Also, please use `size_t`
___
*[`libos/src/bookkeep/libos_signal.c` line 522 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUy3p9iwPNHGNkT_w:-NOtUy3p9iwPNHGNkT_x:bl7g6d6) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L522)):*
> ```C
>             break;
>     }
>     assert(num_prefixes_found <= num_prefixes_to_check);
> ```

This assert is redundant -- the logic is 5 lines of trivial code, so it's clear this condition is always true.
___
*[`libos/src/bookkeep/libos_signal.c` line 523 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtV8Xv9XjplEOt1RKd:-NOtV8Xv9XjplEOt1RKe:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L523)):*
> ```C
>     }
>     assert(num_prefixes_found <= num_prefixes_to_check);
>     for(int i = 0; i < num_opcodes; i++) {
> ```

ditto
___
*[`libos/src/bookkeep/libos_signal.c` line 548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtQp2zEvCsmRfFZyGM:-NOtQp2zEvCsmRfFZyGN:be2rc8o) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L548)):*
> ```C
>     /* Emulate syscall instruction, which is prohibited in Linux-SGX PAL and raises a SIGILL. */
>     if (!maybe_emulate_syscall(context)) {
>         /* IN/OUT instruction aren't allowed in SGX enclaves. Usually #GP hardware exception
> ```

Please create a separate function for all this new code, called `bool maybe_raise_sigsegv()`. I can imagine that we'll have more than IN/OUT instructions with similar behavior, so it makes sense to have a more generic func for this behavior.

Basicall [...]

2023-02-23 03:04 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix, @dimakuv, and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOw6yih5RVOqEnXGDo6:-NOw6yih5RVOqEnXGDo7:bsez1t1) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L462)):*
> ```C
> }
> 
> static bool is_byte_prefix(uint8_t op) {
> ```

I would call the current version `is_legacy_prefix()`



_Code quote:_
```C
is_byte_prefix
```
___
*[`libos/src/bookkeep/libos_signal.c` line 465 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTyDNCne2hBq3EtYk:-NOw91NZDmK48p43itk8:b48hpx5) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L465)):*
> LOCK prefix is not allowed with IN/OUT/INS/OUTS instructions

+1
___
*[`libos/src/bookkeep/libos_signal.c` line 476 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtU45JDtgHIOGUlsE7:-NOw79gl1Txgj7AICc8J:b-2wxhlg) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L476)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this whole Group 1 of prefixes is useless for 64-bit IN/OUT/... instructions?
</blockquote></details>

Not really, I would say the branch hints prefixes do not make sense but may not for the segment override prefixes.

BTW, if we change the list, then we intend to implement this function non-generically (i.e., specific for `IN`/`OUT` now).
___
*[`libos/src/bookkeep/libos_signal.c` line 484 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUHUy8uiROJtn2wjs:-NOw7T4j2t0RboEgz6Y1:b-4oy39i) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Out of all these, I think only REP and 0x66 and 0x67 prefixes make sense with IN/OUT instructions
</blockquote></details>

Also `REPNx` and see my comments above.
___
*[`libos/src/bookkeep/libos_signal.c` line 497 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUg9WC_iKjsG_UvqW:-NOvjh3D-lDfUxkBaS8w:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L497)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this whole comment -- the func is self explanatory.
</blockquote></details>

+1
___
*[`libos/src/bookkeep/libos_signal.c` line 500 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOvp7OeDn1e8BnlVNWS:-NOvp7OeDn1e8BnlVNWT:bx148s8) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L500)):*
> ```C
> static bool is_in_out(PAL_CONTEXT* context) {
>     unsigned char opcodes[] = {
>                                /*imm8 is an immediate value denoting port address */
> ```

Suggest to have sth like the following where the instruction opcodes are ordered and grouped:
```
/* INS opcodes */
0x6c,
0x6d,
/* OUTS opcodes */
0x6e,
0x6f,
/* IN immediate opcodes */
0xe4,
0xe5,
/* OUT immediate opcodes */
0xe6,
0xe7,
/* IN register opcodes */
0xec,
0xed,
/* OUT register opcodes */
0xee,
0xef,
```

BTW IMO, no need to specify the exact instruction(s) for each like `IN AX/EAX,imm8`.
___
*[`libos/src/bookkeep/libos_signal.c` line 548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtQp2zEvCsmRfFZyGM:-NOvlcvlBw7FwQNjcpVG:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L548)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please create a separate function for all this new code, called `bool maybe_raise_sigsegv()`. I can imagine that we'll have more than IN/OUT instructions with similar behavior, so it makes sense to have a more generic func for this behavior.

Basically, this func will be a wrapper around your current `is_in_out()`.
</blockquote></details>

+1
___
*[`libos/test/fs/in_out_instruction_test.c` line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOwD1tN9aMnbFcaQrFi:-NOwD1tN9aMnbFcaQrFj:b-khjy31) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/test/fs/in_out_instruction_test.c#L18)):*
> ```C
> #define EXPECTED_NUM_SIGSEGVS 2
> int g_sigsegv_triggered = 0;
> jmp_buf g_point;
> ```

static
___
*[`libos/test/fs/in_out_instruction_test.c` line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOwBn0x1lG-o27mmn4o:-NOwBn0x1lG-o27mmn4p:bb70gss) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/test/fs/in_out_instruction_test.c#L30)):*
> ```C
>     struct sigaction int_handler = {.sa_handler=fault_handler,
>                                     .sa_flags = SA_RESTART};
>     sigaction(SIGSEGV, &int_handler, 0);
> ```

NULL



_Code quote:_
```C
0
```
___
*[`libos/test/fs/in_out_instruction_test.c` line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOwAvou3Q1Ob8AX2w8a:-NOwAvou3Q1Ob8AX2w8b:b-9oubl5) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/test/fs/in_out_instruction_test.c#L31)):*
> ```C
>                                     .sa_flags = SA_RESTART};
>     sigaction(SIGSEGV, &int_handler, 0);
>     if (sigsetjmp(g_point, 1) == 0) {
> ```

We should do `CHECK(sigsetjump())` to catch errors.



_Code quote:_
```C
sigsetjmp(g_point, 1) == 0
```
___
*[`libos/test/fs/lscpu-test.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOIYZ7iseF2rX5kBT:-NOwDHmx3KxfTwHGYqkA:b-ka87j) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L26)):*
> I'm not a fan

I'm fine w/ using it in tests.


<!-- Sent from Reviewable.io -->

2023-02-23 07:15 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 2 of 12 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOw6yih5RVOqEnXGDo6:-NOx5ccpBvmlQbP86is_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L462)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I would call the current version `is_legacy_prefix()`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 465 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTyDNCne2hBq3EtYk:-NOwfNYa3iiQElH41Y_K:bq20apl) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L465)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> LOCK prefix is not allowed with IN/OUT/INS/OUTS instructions

+1
</blockquote></details>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
___
*[`libos/src/bookkeep/libos_signal.c` line 476 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtU45JDtgHIOGUlsE7:-NOwh2hiBpvobTvaJztm:bq20apl) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L476)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not really, I would say the branch hints prefixes do not make sense but may not for the segment override prefixes.

BTW, if we change the list, then we intend to implement this function non-generically (i.e., specific for `IN`/`OUT` now).
</blockquote></details>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
___
*[`libos/src/bookkeep/libos_signal.c` line 484 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUHUy8uiROJtn2wjs:-NOwh42G36RDNlOCezfa:bq20apl) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L484)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Also `REPNx` and see my comments above.
</blockquote></details>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUVv8BpgcOqcQrzdq:-NOx5iGeCIKEgz_0qSg6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In Gramine, for such cases we use `size_t` instead of `int`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUZNAE5NL_dgyKy1l:-NOx5lGj7xxnIZt16T_O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a 100 char limit, so you can remove helper var `num_prefixes` and just embed the equation
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 497 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUg9WC_iKjsG_UvqW:-NOx5m9x9iw_PTXWTGNK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L497)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 499 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUl9n091pswcBBnWW:-NOx5mos2SLfp1d0JrdS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`uint8_t` please
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 500 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOvp7OeDn1e8BnlVNWS:-NOx5o7XAFzXkndX4P6q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L500)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to have sth like the following where the instruction opcodes are ordered and grouped:
```
/* INS opcodes */
0x6c,
0x6d,
/* OUTS opcodes */
0x6e,
0x6f,
/* IN immediate opcodes */
0xe4,
0xe5,
/* OUT immediate opcodes */
0xe6,
0xe7,
/* IN register opcodes */
0xec,
0xed,
/* OUT register opcodes */
0xee,
0xef,
```

BTW IMO, no need to specify the exact instruction(s) for each like `IN AX/EAX,imm8`.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 509 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTRg1BbNcTsVSOWdw:-NOx5pxgBmDGcKt4jocE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L509)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also add INS/... family of instructions, and OUTS/... family of instructions in this list.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 516 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtV4rB94HkfISsGame:-NOx5quuE4YhCF43-rV4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L516)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space after `for`

Also, please use `size_t`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 522 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUy3p9iwPNHGNkT_w:-NOx5rJc-hffSoitdMHm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L522)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This assert is redundant -- the logic is 5 lines of trivial code, so it's clear this condition is always true.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 523 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtV8Xv9XjplEOt1RKd:-NOx5s9K69RyiH4QmqB6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L523)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtQp2zEvCsmRfFZyGM:-NOx5t8T9aUb6B66QQoO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/li [...]

2023-02-23 07:16 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 2 of 12 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnNfzPB7mCOkTCwhCT):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still wrong:
- Should be `[LibOS]`
- The title is too long and doesn't start with a verb

I would suggest like this:
```
[LibOS] Emulate in/out instructions as if they generate SIGSEGV

Executing I/O instructions (e.g., in/out) inside an SGX enclave generates
a #UD fault. Gramine's PAL tries to handle this exception and propogates
it to LibOS/app as a SIGILL signal.

However, I/O instructions result in a #GP fault (which raises a SIGSEGV
signal) if I/O is not permitted. Let Gramine emulate these instructions as
if they end up in SIGSEGV. This helps some apps, e.g. `lscpu`.
```
</blockquote></details>

Changed the latest commit's commit message to this.
___
*[`libos/src/bookkeep/libos_signal.c` line 563 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtRVgh9LvmGWH7RU4L:-NOx7DZ53bOvgG00Fq5l:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L563)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's too much code, it could be written in a nicer way:
```
    siginfo_t info = {
        .si_signo = SIGILL,
        .si_code = ILL_ILLOPC,
        .si_addr = (void*)addr,
    };

    if (maybe_raise_sigsegv()) {
        info.si_signo = SIGSEGV;
        info.si_code = SEGV_MAPERR;
        log_debug("Illegal instruction during app execution at %p, emulated as if throwing SIGSEGV;"
                  " delivering to app", rip);
    } else {
        log_debug("Illegal instruction during app execution at %p; delivering to app", rip);
    }
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 566 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtSD0A5ieUk3d7qKsI:-NOx7CUU0ltRjrLE1H_z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L566)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this change to the log message. Please see my proposal in other comment.
</blockquote></details>

Done.
___
*[`libos/test/fs/lscpu-test.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOnOIYZ7iseF2rX5kBT:-NOx78ca6OVxi9XXuJ4X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d40594fdc7d8b41776ad4ac40d5d2fb405c86703/libos/test/fs/lscpu-test.c#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> I'm not a fan

I'm fine w/ using it in tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-23 09:59 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 34 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxYxN88_EKXfDJHJxT):*
Note to myself: don't forget to use this message when doing final rebase.
___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxYoFx9OApo4NdVAyh):*
typo: `propagates` (can be fixed during final rebase, no need to change now)
___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOw6yih5RVOqEnXGDo6:-NOxb_QzCG0Mcq9-2KHd:bkcz1pr) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L462)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would make it even more specific: `is_x86_instr_legacy_prefix()`
___
*[`libos/src/bookkeep/libos_signal.c` line 465 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtTyDNCne2hBq3EtYk:-NOxZ8PzA4xC3hQVxx-m:b-gxztsp) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L465)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
</blockquote></details>

Fair enough.
___
*[`libos/src/bookkeep/libos_signal.c` line 476 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtU45JDtgHIOGUlsE7:-NOxbhsT00nMD1wXz0BN:bv71pmo) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L476)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
</blockquote></details>

Ok, I don't mind keeping the whole list of prefixes. Indeed, maybe we'll use this helper function in other places.

But I just realized two things:
1. This generic func can be used by both LibOS code and PAL code, so it should be put under `common/`.
2. This is x86-64 specific. So it should be put under `arch/x86_64/`.

Given the above, I kindly ask to move this function to a new file `common/src/arch/x86_64/cpu.c` (you'll need to add this new file `cpu.c` to corresponding `meson.build`). And put the definition of this func into `common/include/arch/x86_64/cpu.h`, so it becomes the part of the "common" API.
___
*[`libos/src/bookkeep/libos_signal.c` line 484 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUHUy8uiROJtn2wjs:-NOxchZhBO-nmsI1CbTr:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L484)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

I kept this list of prefixes to be generic. In case it is required to check it for some other set of instructions and not specifically for IN/OUT family of instructions.
</blockquote></details>

OK
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUZNAE5NL_dgyKy1l:-NOxcysB9oCC1reIlx0h:b-6yvyw3) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? You still have `num_prefixes`.
___
*[`libos/src/bookkeep/libos_signal.c` line 500 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOvp7OeDn1e8BnlVNWS:-NOxb6Qy8mvZXGeO3ZXB:b-tv5bhx) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L500)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I agree with Kailun, but now this list is ridiculously long. Could we make it more succinct? Like this:
```
0x6c, 0x6d, /* INS opcodes */
0x6e, 0x6f, /* OUTS opcodes */
...
```
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxZqAi66DhrPFNEcRA:-NOxZqAi66DhrPFNEcRB:b-7burw7) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L464)):*
> ```C
> static bool is_legacy_prefix(uint8_t op) {
>     uint8_t prefix_list[] = {
>                              /* Group 0 */ 
> ```

Please remove all trailing whitespaces! Here you have a trailing space.

There are editors and tools that do this. Please run a command/tool to remove such trailing whitespace right before you push a new change. These whitespaces are very annoying.
___
*[`libos/src/bookkeep/libos_signal.c` line 514 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxd5NY7zpRA6Oqin-X:-NOxd5NY7zpRA6Oqin-Y:bgok8y0) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L514)):*
> ```C
>                         0xef,                        
>                         };
>     size_t num_opcodes = ARRAY_SIZE(opcodes);
> ```

Please remove `num_opcodes` and just directly use `ARRAY_SIZE`
___
*[`libos/src/bookkeep/libos_signal.c` line 516 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxdFIaAW1rDriMa-ku:-NOxdFIb1xZSP4bYvx1u:b5bwlar) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L516)):*
> ```C
>     size_t num_opcodes = ARRAY_SIZE(opcodes);
>     uint8_t* rip = (uint8_t*)context->rip;
>     size_t num_prefixes_to_check = 4;
> ```

Why do you need this helper var? Just use `4` directly, and you may put a comment that on x86-64, there is at most 4 prefixes before the instruction opcode.
___
*[`libos/src/bookkeep/libos_signal.c` line 517 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxd9Rf79YnhuMEd0i8:-NOxd9Rf79YnhuMEd0i9:b7zjf77) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L517)):*
> ```C
>     uint8_t* rip = (uint8_t*)context->rip;
>     size_t num_prefixes_to_check = 4;
>     /* num_prefixes_found will store the actual opcode index in rip */
> ```

What? I can't parse this comment. I would just remove it, since the code is pretty simple.
___
*[`libos/src/bookkeep/libos_signal.c` line 524 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxdSQn-hRQsd_4Vd5X:-NOxdSQn-hRQsd_4Vd5Y:b-yeamfg) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L524)):*
> ```C
>         if (!is_prefix) 
>             break;
>     }
> ```

Why this weirdly complicated logic? A simple while loop would suffice:
```
size_t idx = 0;
while (is_legacy_prefix(rip[idx]))
    idx++;
for (size_t i = 0; i < ARRAY_SIZE(opcodes); i++)
    if (rip[idx] == opcodes[i])
        return true;
return false;
```
___
*[`libos/src/bookkeep/libos_signal.c` line 536 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxe-VW3LKiBMRi_VQe:-NOxe-VW3LKiBMRi_VQf:b-9x93ex) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b [...]

2023-02-23 11:13 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`libos/test/regression/in_out_instruction_test.c` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxyZ_g7m9mMZTs8dLa:-NOxyZ_g7m9mMZTs8dLb:b-3ggodh) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L9)):*
> ```C
> 
> #include <assert.h>
> #include <setjmp.h>
> ```

Ok, I educated myself about `sigsetjmp` and `siglongjmp`. Bar my comments, I think the implementation is correct (given that this test is single-threaded).
___
*[`libos/test/regression/in_out_instruction_test.c` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxyOxI-TZHgmGgDnUf:-NOxyOxI-TZHgmGgDnUg:b-d1ce3j) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L17)):*
> ```C
> #define EXPECTED_NUM_SIGSEGVS 2
> static int g_sigsegv_triggered = 0;
> static jmp_buf g_point;
> ```

You're supposed to use `sigjmp_buf` instead of `jmp_buf`
___
*[`libos/test/regression/in_out_instruction_test.c` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxhPaQ22S8jibtKbOD:-NOxyAyj6r4Iyx2MKhrp:b-ekj8hb) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I don't think `sigsetjmp()` returns anything except 0 and 1? So the `CHECK()` macro is useless.

Please double-check my thinking and remove CHECK if the function never returns errors. Ditto everywhere else in this file.
</blockquote></details>

Double-checked myself: yes, in your program, `sigsetjmp()` can only return 0 or 1. So `CHECK()` is useless and can be removed.


<!-- Sent from Reviewable.io -->

2023-03-08 14:40 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 9 of 15 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOw6yih5RVOqEnXGDo6:-NQ0dWwr7nlQsIADBLLS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L462)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would make it even more specific: `is_x86_instr_legacy_prefix()`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 476 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtU45JDtgHIOGUlsE7:-NQ0dm3CBBAtn3t13xpT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L476)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I don't mind keeping the whole list of prefixes. Indeed, maybe we'll use this helper function in other places.

But I just realized two things:
1. This generic func can be used by both LibOS code and PAL code, so it should be put under `common/`.
2. This is x86-64 specific. So it should be put under `arch/x86_64/`.

Given the above, I kindly ask to move this function to a new file `common/src/arch/x86_64/cpu.c` (you'll need to add this new file `cpu.c` to corresponding `meson.build`). And put the definition of this func into `common/include/arch/x86_64/cpu.h`, so it becomes the part of the "common" API.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 486 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOtUZNAE5NL_dgyKy1l:-NQ0dnDM4dkPtbC9Ahax:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L486)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done? You still have `num_prefixes`.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 500 at r4](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOvp7OeDn1e8BnlVNWS:-NQ0dprO43cGGrwbUpBa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b11caadfac3fcbc616a2fde1f9995aac9dbccf04/libos/src/bookkeep/libos_signal.c#L500)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Kailun, but now this list is ridiculously long. Could we make it more succinct? Like this:
```
0x6c, 0x6d, /* INS opcodes */
0x6e, 0x6f, /* OUTS opcodes */
...
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxZqAi66DhrPFNEcRA:-NQ0dYXTDTlku9dtOBPH:b-cqxctz) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L464)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove all trailing whitespaces! Here you have a trailing space.

There are editors and tools that do this. Please run a command/tool to remove such trailing whitespace right before you push a new change. These whitespaces are very annoying.
</blockquote></details>

I used some settings in my editor to remove white spaces. Is it fine now?
___
*[`libos/src/bookkeep/libos_signal.c` line 514 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxd5NY7zpRA6Oqin-X:-NQ0dqYnAIJh6HcZRFlz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L514)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `num_opcodes` and just directly use `ARRAY_SIZE`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 516 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxdFIaAW1rDriMa-ku:-NQ0dsiCBMcttYm6CvUW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L516)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this helper var? Just use `4` directly, and you may put a comment that on x86-64, there is at most 4 prefixes before the instruction opcode.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 524 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxdSQn-hRQsd_4Vd5X:-NQ0dtQZAJ0b09liQ03W:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L524)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this weirdly complicated logic? A simple while loop would suffice:
```
size_t idx = 0;
while (is_legacy_prefix(rip[idx]))
    idx++;
for (size_t i = 0; i < ARRAY_SIZE(opcodes); i++)
    if (rip[idx] == opcodes[i])
        return true;
return false;
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 536 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxe-VW3LKiBMRi_VQe:-NQ0dv650vhK31bZ_z2D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L536)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line. We never use double-line delimiters.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 569 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxeAKs2I3BATJEzHBH:-NQ0dw2S15mCkAJlSEqT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L569)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You misunderstood my other comment. Please move this whole comment inside `maybe_raise_sigsegv()` function.

Think about it -- in this context, we don't know whether the instruction is IN/OUT or something else. All we know is that the instruction/GPR context for some reason forces us to raise a SIGSEGV instead of SIGILL. So we can't have a comment that talks about IN/OUT instructions here.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 572 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxeWTH2RCB1f8-XlIr:-NQ0dxON2s3IGJcjGUal:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L572)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap this to 100 chars per line (this is our limit in Gramine)
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxejiNCxuCyAXM8n6s:-NQ0dyn-BHCAk58CZZK6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why Capital Letters?
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 4 at r5](https://reviewable.io/reviews/gramineproject [...]

2023-03-10 09:42 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 2 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9nxMM0TVT-sbDj5N0:-NQ9nxMM0TVT-sbDj5N1:b-7w3o9h) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/common/src/arch/x86_64/cpu.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2022 Fortnanix Inc
> ```

Typo in Fortanix
___
*[`common/src/arch/x86_64/cpu.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9o43N82y88kt2J6h7:-NQ9o43N82y88kt2J6h8:b7d40w2) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/common/src/arch/x86_64/cpu.c#L8)):*
> ```C
> /* This file contains functions that check various features and flags
>  * specific to x86
>  */
> ```

We have a limit of 100 chars per line, so your sentence can fit into one line:
```
/* This file contains functions that check various features and flags specific to x86. */
```
___
*[`common/src/arch/x86_64/cpu.c` line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9oHvcERKQXQ3byj4K:-NQ9oHvcERKQXQ3byj4L:bp40pbe) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/common/src/arch/x86_64/cpu.c#L35)):*
> ```C
>                              0x67, /* Address-size override prefix  */
>                              /* The rest of the prefixes aren't really applicable
>                               * for the instruction(s) we are checking.
> ```

Wait, this is now wrong. This function is generic, so it must contain all the prefixes. Please add the rest of the prefixes here.
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxZqAi66DhrPFNEcRA:-NQ9oYgkCnJaMPqiNY0j:b-i3gwhz) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/src/bookkeep/libos_signal.c#L464)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

I used some settings in my editor to remove white spaces. Is it fine now?
</blockquote></details>

Yes, everything looks good now :)
___
*[`libos/src/bookkeep/libos_signal.c` line 489 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9pOCl6Z5jRpdd8mGU:-NQ9pOCl6Z5jRpdd8mGV:bgkcjcm) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/src/bookkeep/libos_signal.c#L489)):*
> ```C
>      * signal) if I/O is not permitted. Let Gramine emulate these instructions
>      * as if they end up in SIGSEGV. This helps some apps, e.g. `lscpu`.
>      */
> ```

This looks like it is 80-char-per-line limited. Please fix to 100-char-per-line (please also change your text editor's settings to use 100 limit by default).
___
*[`libos/test/regression/in_out_instruction_test.c` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxemdp9rxD9m2Qpt8p:-NQ9poaQ2ZUY4OCnASk8:b-2p1qrr) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L4)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

total 78 characters now
</blockquote></details>

Still not done.

This looks like it is 80-char-per-line limited. Please fix to 100-char-per-line (please also change your text editor's settings to use 100 limit by default).
___
*[`libos/test/regression/in_out_instruction_test.c` line 29 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxgeK2C12GQzIODy_5:-NQ9q-_rDTdMkWLkv-4H:b85kk9g) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L29)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? What about this line with `sigaction(...)`?

For an example, check this: https://github.com/gramineproject/gramine/blob/3d788aee1f7c0a245c686e397742c24bd7f27ebc/libos/test/regression/sigprocmask_pending.c#L33
___
*[`libos/test/regression/in_out_instruction_test.c` line 42 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxf7Rl0t1U2R_JGmFz:-NQ9s9QABdO3MOPz_kh0:bws8rj7) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L42)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done. Please let me know if the failure statement looks fine.
</blockquote></details>

No, you should fail, not just print a message and return zero (success). Like this:
```
    if (g_sigsegv_triggered != EXPECTED_NUM_SIGSEGVS)
        errx(1, "Expected %d number of SIGSEGVs, but got only %d", EXPECTED_NUM_SIGSEGVS, g_sigsegv_triggered);

    puts("SIGSEGV TEST OK");
    return 0;
```
___
*[`libos/test/regression/in_out_instruction_test.c` line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rMom7QyDC3KOaWNG:-NQ9rMom7QyDC3KOaWNH:bonj60n) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L30)):*
> ```C
>                                     .sa_flags = SA_RESTART};
>     int value = 0;
>     int port = 0;
> ```

Why not pretend that this port is something meaningful, like `0x3f8` (first serial port)?
___
*[`libos/test/regression/in_out_instruction_test.c` line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rVUo5eHfXg3v4szG:-NQ9rVUo5eHfXg3v4szH:bm9q6ho) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L30)):*
> ```C
>                                     .sa_flags = SA_RESTART};
>     int value = 0;
>     int port = 0;
> ```

Hm, this can't be true? `int` is a 4-byte type, but the port number should be `unsigned short` (2-byte type)?

Also, the `value` is 4-byte-sized, but I would prefer a byte-sized type (`unsigned char`).
___
*[`libos/test/regression/in_out_instruction_test.c` line 33 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rn0_3R_jBgcNu0T0:-NQ9rn0_3R_jBgcNu0T1:ba9xvd6) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L33)):*
> ```C
>     sigaction(SIGSEGV, &int_handler, 0);
>     if (sigsetjmp(g_point, 1) == 0) {
>         __asm__ volatile("in %1, %0" : "=a"(value) : "d"(port));
> ```

I think it's better to use `inb` (the 1-byte-sized variant of the instruction), for clarity
___
*[`libos/test/regression/in_out_instruction_test.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rJZG38_abaPfq-tH:-NQ9rJZG38_abaPfq-tI:b-ujoguc) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L37)):*
> ```C
>     puts("handled IN instruction");
>     if (sigsetjmp(g_point, 1) == 0) {
>         port = 0;
> ```

What's the point of resetting the port number? This line looks useless.
___
*[`libos/test/regression/in_out_instruction_test.c` line 38 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rsb-99-4922WpsJI:-NQ9rsb-99-4922WpsJJ:b-kz70hl) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test [...]

2023-03-13 09:44 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 4 of 15 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`common/src/arch/x86_64/cpu.c` line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9o43N82y88kt2J6h7:-NQAWukCETx6umehB60e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/common/src/arch/x86_64/cpu.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a limit of 100 chars per line, so your sentence can fit into one line:
```
/* This file contains functions that check various features and flags specific to x86. */
```
</blockquote></details>

Done.
___
*[`common/src/arch/x86_64/cpu.c` line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9oHvcERKQXQ3byj4K:-NQADLTZ1ctL8lT4HE5Q:b1m9s0w) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/common/src/arch/x86_64/cpu.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, this is now wrong. This function is generic, so it must contain all the prefixes. Please add the rest of the prefixes here.
</blockquote></details>

This function is named ```is_x86_instr_legacy_prefix``` , so shouldn't we have only the legacy prefixes? Yes this comment should be removed.
___
*[`libos/src/bookkeep/libos_signal.c` line 489 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9pOCl6Z5jRpdd8mGU:-NQAX4es69vUF_3DllU1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/src/bookkeep/libos_signal.c#L489)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks like it is 80-char-per-line limited. Please fix to 100-char-per-line (please also change your text editor's settings to use 100 limit by default).
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxemdp9rxD9m2Qpt8p:-NQAX5zw7CmU9Ny7bttC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still not done.

This looks like it is 80-char-per-line limited. Please fix to 100-char-per-line (please also change your text editor's settings to use 100 limit by default).
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 42 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxf7Rl0t1U2R_JGmFz:-NQAXHBaBxZpfZHGHDhQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, you should fail, not just print a message and return zero (success). Like this:
```
    if (g_sigsegv_triggered != EXPECTED_NUM_SIGSEGVS)
        errx(1, "Expected %d number of SIGSEGVs, but got only %d", EXPECTED_NUM_SIGSEGVS, g_sigsegv_triggered);

    puts("SIGSEGV TEST OK");
    return 0;
```
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rMom7QyDC3KOaWNG:-NQAX84a5U328RToG83J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not pretend that this port is something meaningful, like `0x3f8` (first serial port)?
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rVUo5eHfXg3v4szG:-NQAX8TT-0S04dT_0pXG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, this can't be true? `int` is a 4-byte type, but the port number should be `unsigned short` (2-byte type)?

Also, the `value` is 4-byte-sized, but I would prefer a byte-sized type (`unsigned char`).
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 33 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rn0_3R_jBgcNu0T0:-NQAXAScECi1U2KlGqu4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it's better to use `inb` (the 1-byte-sized variant of the instruction), for clarity
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rJZG38_abaPfq-tH:-NQAXDd_0Kz1k3uhDfNq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of resetting the port number? This line looks useless.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 38 at r6](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ9rtqs9L_OkLrbFvSI:-NQAXFKK0miNyiDiILaw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8e3be01748c73fcdd7cc923291a655d9fd1bfe9/libos/test/regression/in_out_instruction_test.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This makes no sense. `=a` means that the RAX register will contain the output, but the `out` instruction only gets the input, not the output.

Please educate yourself how `in` and `out` instruction work, and how to write inline asm for them. For example, check this: https://stackoverflow.com/questions/52355247/c-inline-asm-for-x86-in-out-port-i-o-has-operand-size-mismatch
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 09:01 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 2 at r7](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUJgzv8-pn9-_5y2rV:-NQUJgzv8-pn9-_5y2rW:b-lm0zcb) ([raw file](https://github.com/gramineproject/gramine/blob/fffa97f4c21d19aa2ba7110cd37439e66203f75f/common/src/arch/x86_64/cpu.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2022 Fortanix Inc
> ```

Should be 2023 now?
___
*[`common/src/arch/x86_64/cpu.c` line 15 at r7](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUKMm-37ej4aTPe3f9:-NQUKMm-37ej4aTPe3fA:b433tuw) ([raw file](https://github.com/gramineproject/gramine/blob/fffa97f4c21d19aa2ba7110cd37439e66203f75f/common/src/arch/x86_64/cpu.c#L15)):*
> ```C
> bool is_x86_instr_legacy_prefix(uint8_t op) {
>     uint8_t prefix_list[] = {
>                              /* Group 0 */
> ```

Why do you start with `Group 0`? In all documentation, I see that the prefix groups are started with `Group 1`. E.g. https://wiki.osdev.org/X86-64_Instruction_Encoding#Legacy_Prefixes


<!-- Sent from Reviewable.io -->

2023-03-14 09:08 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 14 of 15 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`common/src/arch/x86_64/cpu.c` line 2 at r7](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUJgzv8-pn9-_5y2rV:-NQUNE146oC86xVOp7v8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fffa97f4c21d19aa2ba7110cd37439e66203f75f/common/src/arch/x86_64/cpu.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should be 2023 now?
</blockquote></details>

Done.
___
*[`common/src/arch/x86_64/cpu.c` line 15 at r7](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUKMm-37ej4aTPe3f9:-NQUNGs64FVLACc4q3Hg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fffa97f4c21d19aa2ba7110cd37439e66203f75f/common/src/arch/x86_64/cpu.c#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you start with `Group 0`? In all documentation, I see that the prefix groups are started with `Group 1`. E.g. https://wiki.osdev.org/X86-64_Instruction_Encoding#Legacy_Prefixes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 11:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 14 of 15 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 6 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkICw9Bbr-0wz1R1S:-NQUkICx-9ezOEAH8aNb:b-ku54ij) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L6)):*
> ```C
>  */
> 
> /* This file contains functions that check various features and flags specific to x86 */
> ```

Not blocking... Just feel like this comment is a bit redundant as we put this file under `arch/x86` and we do have only one function here in this file.



_Code quote:_
```C
* This file contains functions that check various features and flags specific to x86 */
```
___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQUkobqBOYPB1awhzUm:b-yyi3zt) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
> ```C
> 
> bool is_x86_instr_legacy_prefix(uint8_t op) {
>     uint8_t prefix_list[] = {
> ```

The indentation is a bit weird IMO but it's not blocking...
___
*[`libos/src/bookkeep/libos_signal.c` line 483 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUmVOH1gaFtse3M5jV:-NQUmVOH1gaFtse3M5jW:bu3gppr) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/libos/src/bookkeep/libos_signal.c#L483)):*
> ```C
> static bool maybe_raise_sigsegv(PAL_CONTEXT* context) {
>     /* Executing I/O instructions (e.g., in/out) inside an SGX enclave generates a #UD fault.
>      * Gramine's PAL tries to handle this exception and propogates it to LibOS/app as a SIGILL
> ```

propagates



_Code quote:_
```C
propogates
```


<!-- Sent from Reviewable.io -->

2023-03-14 14:01 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 13 of 15 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, and @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 483 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUmVOH1gaFtse3M5jV:-NQVQB1o-OBXpYoqIor2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/libos/src/bookkeep/libos_signal.c#L483)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

propagates
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-15 07:40 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 6 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkICw9Bbr-0wz1R1S:-NQZCQBX0EE_Yp15LR9m:b3w5i0t) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L6)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not blocking... Just feel like this comment is a bit redundant as we put this file under `arch/x86` and we do have only one function here in this file.
</blockquote></details>

I agree, I would remove this comment alltogether. But I'm also not blocking because it's kinda a tradition in Gramine to have some top-level comment in each source file.


<!-- Sent from Reviewable.io -->

2023-03-15 12:01 UTC, oshogbo reviewed
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQZxz40-Due9OpC4qJK:b-bbjxmt) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The indentation is a bit weird IMO but it's not blocking...
</blockquote></details>

It is actually blocking, as this isn't the right style.
___
*[`common/src/arch/x86_64/cpu.c` line 13 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQZyxv32bdshlmJewY0:-NQZyxv32bdshlmJewY1:b-5m9izm) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/common/src/arch/x86_64/cpu.c#L13)):*
> ```C
> #include "cpu.h"
> 
> bool is_x86_instr_legacy_prefix(uint8_t op) {
> ```

These are x86_64 legacy prefixes, right?

Update: I see sometimes we use x86 and sometimes x86_64 to refer to 'x86_64' so not blocking.
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_1OIW41N-CQX4gPQa:-NQ_1OIW41N-CQX4gPQb:bl2xtj3) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L464)):*
> ```C
> static bool is_in_out(PAL_CONTEXT* context) {
>     uint8_t opcodes[] = {
>                         0x6c, 0x6d, /* INS opcodes */
> ```

Now it looks like this is a single opcode.
Maybe something like:
```
/* INS opcodes */
0x6c,
0x6d,
```
___
*[`libos/src/bookkeep/libos_signal.c` line 470 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_0sh40O8jEpabk5Ja:-NQZyE7n6PRKh1erINa6:bb1c4r9) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L470)):*
> ```C
>                         0xec, 0xed, /* IN register opcodes */
>                         0xee, 0xef, /* OUT register opcodes */
>                         };
> ```

Wrong style.
___
*[`libos/src/bookkeep/libos_signal.c` line 473 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_12Ts0ckCinZGw2ba:-NQ_12TtEplIrk5vxHvu:b-yn2s6z) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L473)):*
> ```C
>     uint8_t* rip = (uint8_t*)context->rip;
>     size_t idx = 0;
>     while (is_x86_instr_legacy_prefix(rip[idx]) && idx < 4)
> ```

Should we document why 4?
```
Each instruction can have up to four prefixes.
```
Or have a define for it?
___
*[`libos/test/regression/in_out_instruction_test.c` line 3 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_3nduEJsI2ndzYGSE:-NQ_3nduEJsI2ndzYGSF:b-a2xouq) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L3)):*
> ```C
> /* Test description: this test verifies that in and out instructions correctly generate SIGSEGV.
>  * This raises SIGSEGV once for IN and once for OUT and then counts if number of SIGSEGVs is 2.
>  */
> ```

Copyrights?
___
*[`libos/test/regression/in_out_instruction_test.c` line 19 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5XtmCqAMAOQSCwXq:-NQ_5XtmCqAMAOQSCwXr:b-mhfvx5) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L19)):*
> ```C
> static sigjmp_buf g_point;
> 
> static void fault_handler(int signum) {
> ```

Not blocking, however, do we want to check what caused SIGSEGV?
___
*[`libos/test/regression/in_out_instruction_test.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_3k2Y8yhAA5S3i4b9:-NQ_3k2Z8l7zYcHiT6Gs:b-bcch76) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L20)):*
> ```C
> 
> static void fault_handler(int signum) {
>     assert(signum == SIGSEGV);
> ```

CHECK?
___
*[`libos/test/regression/in_out_instruction_test.c` line 31 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5B4e4MH04b3peE7E:-NQ_5B4e4MH04b3peE7F:bj2i89j) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L31)):*
> ```C
>     unsigned short port = 0x3F8;
>     CHECK(sigaction(SIGSEGV, &int_handler, NULL));
>     if (sigsetjmp(g_point, 1) == 0) {
> ```

I think this is wrong.
If sigsetjmp fails, the test should just fail.
___
*[`libos/test/regression/in_out_instruction_test.c` line 34 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5QwSCHptV2QGZig9:-NQ_5QwT3aQt7JM2un-V:bh1xa6j) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L34)):*
> ```C
>         __asm__ volatile("inb %1, %0" : "=a"(value) : "d"(port));
>     }
>     puts("handled IN instruction");
> ```

This isn't necessary.
___
*[`libos/test/regression/in_out_instruction_test.c` line 35 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5IAz4BEqmgDflgEb:-NQ_5IAz4BEqmgDflgEc:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L35)):*
> ```C
>     }
>     puts("handled IN instruction");
>     if (sigsetjmp(g_point, 1) == 0) {
> ```

Ditto.
___
*[`libos/test/regression/in_out_instruction_test.c` line 38 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5NS4EIwf1T7I-uIZ:-NQ_5NS4EIwf1T7I-uI_:bh1xa6j) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L38)):*
> ```C
>         __asm__ volatile("outb %0, %1" : : "a"(value), "d"(port));
>     }
>     puts("handled OUT instruction");
> ```

This isn't necessary.
___
*[`libos/test/regression/in_out_instruction_test.c` line 41 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_7jTcAHE8V_g2tyOs:-NQ_7jTdD3_qpQQp7dju:b-uuimi) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L41)):*
> ```C
>     if (g_sigsegv_triggered != EXPECTED_NUM_SIGSEGVS)
>         errx(1, "Expected %d number of SIGSEGVs, but got only %d", EXPECTED_NUM_SIGSEGVS,
>              g_sigsegv_triggered);
> ```

I wonder if we should try to test something that for sure uses one of these prefixes we define?
___
*[`libos/test/regression/in_out_instruction_test.c` line 42 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_4c-pEJ36dPWC-bpQ:-NQ_4c-pEJ36dPWC-bpR:b8eciqc) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L42)):*
> ```C
>         errx(1, "Expected %d number of SIGSEGVs, but got only %d", EXPECTED_NUM_SIGSEGVS,
>              g_sigsegv_triggered);
>     puts("SIGSEGV TEST OK");
> ```

We just use: "TEST OK"
___
*[`libos/test/regression/meson.build` line 55 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5pkc1jwWrfsT7xVi:-NQ_5pkc1jwWrfsT7xVj:brj73f1) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/meson.build#L55)):*
> ```Meson
>     'hostname': {},
>     'init_fail [...]

2023-03-15 12:46 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 9 of 15 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, @kailun-qin, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQ_A1WK5F8i8j0xcCfP:b-d9pqsg) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It is actually blocking, as this isn't the right style.
</blockquote></details>

can you please specify the right style so that I can update accordingly?
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_1OIW41N-CQX4gPQa:-NQ_Hf5s40RyiifDSYpU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L464)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Now it looks like this is a single opcode.
Maybe something like:
```
/* INS opcodes */
0x6c,
0x6d,
```
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 473 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_12Ts0ckCinZGw2ba:-NQ_ILhz1q9v7Q1zfVGx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L473)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we document why 4?
```
Each instruction can have up to four prefixes.
```
Or have a define for it?
</blockquote></details>

Done.
___
*[`libos/test/regression/meson.build` line 55 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5pkc1jwWrfsT7xVi:-NQ_IcSNARhmniGWn1I2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/meson.build#L55)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We don't use `_test` suffix in the name of files.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1372 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_64uF7XrB12l6oKxG:-NQ_IeSp0qHZ-409EIgA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/test_libos.py#L1372)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Shouldn't this be run only on X86_64?
I'm not sure how in/out looks on other platforms.
Something like:
```
@unittest.skipUnless(ON_X86, 'x86-specific')
```
</blockquote></details>

Done.
___
*[`libos/test/regression/tests.toml` line 59 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_6gwD28lLxn19e1cv:-NQ_Ifcf3L9hwWXaC2uh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/tests.toml#L59)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This test is x86_64 specific, I think. Should we move it to `arch.x86_64` section? 
However I'm not sure how in/out looks on other platforms.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 3 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_3nduEJsI2ndzYGSE:-NQ_INx3BKpcmYiZzdWE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L3)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Copyrights?
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_3k2Y8yhAA5S3i4b9:-NQ_AQ_M4wsLlDbjDgxR:brjjdba) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

CHECK?
</blockquote></details>

didn't get this. Can you please elaborate?
___
*[`libos/test/regression/in_out_instruction_test.c` line 31 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5B4e4MH04b3peE7E:-NQ_ISGA8uhGmPY7-xZj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L31)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think this is wrong.
If sigsetjmp fails, the test should just fail.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 34 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5QwSCHptV2QGZig9:-NQ_ISwi8URzgKaG8NhW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L34)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This isn't necessary.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 35 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5IAz4BEqmgDflgEb:-NQ_ITH7E1PV6HOeS3pa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L35)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 38 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5NS4EIwf1T7I-uIZ:-NQ_IUtD-RdDD90kSOmx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L38)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This isn't necessary.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 42 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_4c-pEJ36dPWC-bpQ:-NQ_I_9C-L0h8_k4lMhu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L42)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We just use: "TEST OK"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-16 09:18 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, @NirjharRoyiitk, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQdd5JD5GyynaF0l7nP:b6t5ewm) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

can you please specify the right style so that I can update accordingly?
</blockquote></details>

@oshogbo Do we have a style for this case? You probably mean 4-space indentation, like this:
```
    uint8_t prefix_list[] = {
                                 /* Group 1 */
                                 0xf0, /* LOCK prefix */
```

I'm not sure our code style guidelines cover such cases, but if that's what you want, we can change it, no problem.
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_1OIW41N-CQX4gPQa:-NQdcv-B1bRmOgIQApf8:bogx245) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L464)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm, ok, I still feel like it occupies way too much space, but we've been bikeshedding on this tiny issue for too long. Let's keep the current version.
___
*[`libos/test/regression/in_out_instruction.c` line 4 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQddhqu-RJtLkbGgGBP:-NQddhqu-RJtLkbGgGBQ:b-d7veq6) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L4)):*
> ```C
> /* Copyright (C) 2023 Fortanix Inc
>  *                    Nirjhar Roy <nirjhar.roy@fortanix.com>
>  */
> ```

Please add an empty line after this, hard to read
___
*[`libos/test/regression/in_out_instruction.c` line 37 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdh6VL0iOu9ncSZPpG:-NQdh6VL0iOu9ncSZPpH:b5tkh3c) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L37)):*
> ```C
>     /* sigsetjmp returns 0 if it directly invocated, else it returns a non zero value if it
>      * from a call to siglongjmp()
>      */
> ```

No, let's not add this snippet from the man page. We should not add comments on how every standard function works.
___
*[`libos/test/regression/in_out_instruction.c` line 43 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdhKBqCy8FXexPFoBA:-NQdhKBqCy8FXexPFoBB:bc591uh) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L43)):*
> ```C
>         if (g_sigsegv_triggered < 1) {
>             errx(1, "sigsetjmp failed before inb instruction could have executed");
>         }
> ```

I think this won't be needed when you change the fault-handler code as I suggested.
___
*[`libos/test/regression/in_out_instruction.c` line 50 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdhOtT7woMlU5AXmI8:-NQdhOtT7woMlU5AXmI9:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L50)):*
> ```C
>         if (g_sigsegv_triggered < 2) {
>             errx(1, "sigsetjmp failed before outb instruction could have executed");
>         }
> ```

ditto
___
*[`libos/test/regression/in_out_instruction_test.c` line 19 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5XtmCqAMAOQSCwXq:-NQdeFku8dx_EIihfDnP:bsisjad) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L19)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Not blocking, however, do we want to check what caused SIGSEGV?
</blockquote></details>

Hm, this would be a good idea. But looks like we would need a more "heavy-weight" use of asm, to have global symbols that clearly demarkate the address at which `inb` instruction takes place.

Ok, actually, I think we need to do this properly. @NirjharRoyiitk Could you make `inb` and `outb` proper pure-assembly functions? You can take as an example this: `pal/regression/memory.c`. And then you will be able to verify where SIGSEGV actually happened like this:
```
void inb_func(...) __attribute__((visibility("internal")));
void outb_func(...) __attribute__((visibility("internal")));
__asm__ (
".pushsection .text\n"
".type inb_func, @function\n"
".type outb_func, @function\n"
"inb_func:\n"
    "inb ...\n"
    "ret\n"
"outb_func:\n"
    "outb ...\n"
    "ret\n"
".popsection\n"
);

static void fault_handler(int signum, siginfo_t* si, void* uc) {
    assert(signum == SIGSEGV);
    if (g_sigsegv_triggered == 0) {
        /* must be a fault on inb instruction */
        if ((ucontext_t*)uc)->uc_mcontext.gregs[REG_RIP] != (uintptr_t)inb_func)
            _Exit(1);
    } else if (g_sigsegv_triggered == 1) {
        /* must be a fault on outb instruction */
        if ((ucontext_t*)uc)->uc_mcontext.gregs[REG_RIP] != (uintptr_t)outb_func)
            _Exit(1);
    } else {
        /* too many segfaults?! */
        _Exit(1);
    }
    g_sigsegv_triggered++;
    siglongjmp(g_point, 1);
}
```

Something like this...
___
*[`libos/test/regression/in_out_instruction_test.c` line 20 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_3k2Y8yhAA5S3i4b9:-NQde6E8EwPQQ7XStd2k:b-vrf0cp) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L20)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

didn't get this. Can you please elaborate?
</blockquote></details>

@oshogbo Do you mean that we should do a proper runtime check instead of a debug-mode-only assert? I don't see a need for this, as in this test we clearly register only the `SIGSEGV` handler.
___
*[`libos/test/regression/in_out_instruction_test.c` line 31 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5B4e4MH04b3peE7E:-NQdgz44E-TL_ZcE5oO-:b-k90rjj) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L31)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@oshogbo What do you mean exactly? `sigsetjmp()` doesn't return any error codes, if that's what you implied. Please check its man page.
___
*[`libos/test/regression/in_out_instruction_test.c` line 41 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_7jTcAHE8V_g2tyOs:-NQdhV036LV8orVvKGvC:bhf2ix4) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L41)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I wonder if we should try to test something that for sure uses one of these prefixes we define?
</blockquote></details>

We could add another test... But I think we shouldn't complicate this particular test.


<!-- Sent from Reviewable.io -->

2023-03-16 18:56 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 12 of 15 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @dimakuv, @kailun-qin, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQflSAY0UUpGA1M4u5L:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes 4 spaces and the closing `}` on the end:
```
uint8_t prefix_list[] = {
    /* Group 1 */
    0xf0, /* LOCK prefix */
    0xf2, /* REPNE/REPNZ prefix */
    0xf3, /* REP or REPE/REPZ prefix */
...
};
```

I think most of our structures. examples:
https://github.com/gramineproject/gramine/blob/master/libos/test/regression/poll_many_types.c#L49
https://github.com/gramineproject/gramine/blob/master/libos/src/libos_parser.c#L71|
https://github.com/gramineproject/gramine/blob/master/libos/src/libos_parser.c#L747
https://github.com/gramineproject/gramine/blob/master/libos/src/fs/proc/thread.c#L76
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 464 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_1OIW41N-CQX4gPQa:-NQflWdD6lY280BH21y3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L464)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, ok, I still feel like it occupies way too much space, but we've been bikeshedding on this tiny issue for too long. Let's keep the current version.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 470 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_0sh40O8jEpabk5Ja:-NQflXgfDgC17vBQKAZq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L470)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Wrong style.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction.c` line 4 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQddhqu-RJtLkbGgGBP:-NQflb1n8YDEg3G6gtml:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this, hard to read
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction.c` line 37 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdh6VL0iOu9ncSZPpG:-NQflom21tsljow7UI6i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, let's not add this snippet from the man page. We should not add comments on how every standard function works.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction.c` line 43 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdhKBqCy8FXexPFoBA:-NQflqTG4wjjr-CiU_Xc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this won't be needed when you change the fault-handler code as I suggested.
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction.c` line 50 at r10](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQdhOtT7woMlU5AXmI8:-NQflr-kCunpVOfBfzDx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b5254a1eacf6af27a2acba04a43578edcc5c0112/libos/test/regression/in_out_instruction.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 19 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5XtmCqAMAOQSCwXq:-NQfld3A-pxzWNpRsXUi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L19)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yea seems complicated, however, it's SIGSEGV... So dunno..
</blockquote></details>

Done.
___
*[`libos/test/regression/in_out_instruction_test.c` line 31 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5B4e4MH04b3peE7E:-NQflpky-BbLjfNJyjrO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L31)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I'm thinking about something like.
Ah I see.
Ok sorry, that's was my bad.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 09:29 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, @NirjharRoyiitk, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQitAKV9QxA4Hn_j5wJ:bgdpnug) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, thanks for explanation. Agreed, this looks better now.
___
*[`libos/test/regression/in_out_instruction_test.c` line 19 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5XtmCqAMAOQSCwXq:-NQitVsL88lrJuFOZGtz:bct07vd) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L19)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, looks good to me!
___
*[`libos/test/regression/in_out_instruction_test.c` line 31 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_5B4e4MH04b3peE7E:-NQithSf1pW5Aq-eBszE:b-25emsw) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/test/regression/in_out_instruction_test.c#L31)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@oshogbo You're still blocking on this comment.


<!-- Sent from Reviewable.io -->

2023-03-17 09:31 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix, @kailun-qin, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQUkobqBOYPB1awhzUl:-NQiu3xv8IM651s74FvV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5add3021efd295918dca0dc6306d0bc8f438616e/common/src/arch/x86_64/cpu.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, thanks for explanation. Agreed, this looks better now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-19 09:38 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 473 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_12Ts0ckCinZGw2ba:-NQtDunr94P8GaPR6wic:b-deg3rf) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L473)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure of style of this comment: @dimakuv ? 
But not blocking.


<!-- Sent from Reviewable.io -->

2023-03-20 07:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 473 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_12Ts0ckCinZGw2ba:-NQxzMTm1R9h2N5HT_l2:b-yfq8dh) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L473)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I'm not sure of style of this comment: @dimakuv ? 
But not blocking.
</blockquote></details>

Yep, I guess this comment does not correspond to our style. I would prefer this:
```
    /* note that x86-64 instructions can have up to four legacy prefixes */
    size_t idx = 0;
    while (is_x86_instr_legacy_prefix(rip[idx]) && idx < 4)
        idx++;

```


<!-- Sent from Reviewable.io -->

2023-03-20 07:55 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 14 of 15 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix and @dimakuv)

___
*[`libos/src/bookkeep/libos_signal.c` line 473 at r9](https://reviewable.io/reviews/gramineproject/gramine/1192#-NQ_12Ts0ckCinZGw2ba:-NQy01QF5grdb6g6A4Qk:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/19c0b36a0fc0a0aa81b929fcd5937b52e8b4087e/libos/src/bookkeep/libos_signal.c#L473)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, I guess this comment does not correspond to our style. I would prefer this:
```
    /* note that x86-64 instructions can have up to four legacy prefixes */
    size_t idx = 0;
    while (is_x86_instr_legacy_prefix(rip[idx]) && idx < 4)
        idx++;

```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-03-20 08:22 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @arai-fortanix)



<!-- Sent from Reviewable.io -->

2023-04-19 06:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTNH_N81qkfrr1V9pkH:b-b3bbd6) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This name is misleading, it says that it may "throw a sigsegv or not", but in fact it doesn't make any changes to Gramine state (especially it can't send an exception to the app) and just returns a boolean.

This is even doubly-confusing, because 7 lines above you have `maybe_emulate_syscall(context)`, which has the same naming convention as you used here, but it _actually triggers the emulation_.
</blockquote></details>

Then maybe rename this function to `must_raise_sigsegv()`?


<!-- Sent from Reviewable.io -->

2023-04-19 10:58 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTO9BDiECxux6XC0mmV:b-gidiqk) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Then maybe rename this function to `must_raise_sigsegv()`?
</blockquote></details>

I don't like it, I'd rather say directly what it does: `is_at_io_insn()`.


<!-- Sent from Reviewable.io -->

2023-04-19 12:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTOQ1rj24xn5VsoCvxQ:b-g2c18v) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like it, I'd rather say directly what it does: `is_at_io_insn()`.
</blockquote></details>

@mkow So you suggest to remove one level of indirection? (The `maybe_raise_sigsegv()` function which is currently a wrapper around `is_in_out()`.)

I liked this indirection because we could have more instructions that we inject SIGSEGV into the application, and then handling of these additional instructions would go into this wrapper func.

But if you think that this wrapper func is an overkill, then I wouldn't mind to remove it.


<!-- Sent from Reviewable.io -->

2023-04-19 13:38 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTOi0uPA5HyBa_2t6RG:b-7cib91) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
I just wanted to rename `maybe_raise_sigsegv()` which currently has a name which suggests that it does something that it doesn't do. But yes, effectively it's just removing this function.
It's not a real indirection, it doesn't have any logic inside and the only thing it does is that it renames `is_in_out()` to something confusing.

> I liked this indirection because we could have more instructions that we inject SIGSEGV into the application, and then handling of these additional instructions would go into this wrapper func.

Are there any other instructions which behave like that? This is just some weird corner case of SGX, I don't see any gains from adding more indirections to its handling.


<!-- Sent from Reviewable.io -->

2023-04-19 13:48 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTOkvenCAR0Fox74_ja:bnh2ebh) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just wanted to rename `maybe_raise_sigsegv()` which currently has a name which suggests that it does something that it doesn't do. But yes, effectively it's just removing this function.
It's not a real indirection, it doesn't have any logic inside and the only thing it does is that it renames `is_in_out()` to something confusing.

> I liked this indirection because we could have more instructions that we inject SIGSEGV into the application, and then handling of these additional instructions would go into this wrapper func.

Are there any other instructions which behave like that? This is just some weird corner case of SGX, I don't see any gains from adding more indirections to its handling.
</blockquote></details>

Okay I will remove this one level of indirection


<!-- Sent from Reviewable.io -->

2023-04-19 13:51 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`libos/test/regression/test_libos.py` line 547 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTLYStp3bQbi5brme0H:-NTOluas0h6nSxxwC7_q:b-5qz98k) ([raw file](https://github.com/gramineproject/gramine/blob/299dde8f4c96d7a0e2d2ef1652c5a241777607e7/libos/test/regression/test_libos.py#L547)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Accidental change?
</blockquote></details>

Umm, which change? Sorry I am unable to view any unwanted change in git diff? Can you please point it out for me?


<!-- Sent from Reviewable.io -->

2023-04-19 14:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`libos/test/regression/test_libos.py` line 547 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTLYStp3bQbi5brme0H:-NTOoun4DwAu-LFSIjjX:bz0y1uq) ([raw file](https://github.com/gramineproject/gramine/blob/299dde8f4c96d7a0e2d2ef1652c5a241777607e7/libos/test/regression/test_libos.py#L547)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Umm, which change? Sorry I am unable to view any unwanted change in git diff? Can you please point it out for me?
</blockquote></details>

You removed one empty line here. You can drag the mouse in the "revision history" of this file from left (the "base" symbol) to right ("r12") -- this way you'll see all the changes that your PR introduced in this particular file, and you'll see this "removal of the empty line".


<!-- Sent from Reviewable.io -->

2023-04-20 07:03 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 13 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`libos/src/bookkeep/libos_signal.c` line 527 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTL_9LtBLMvItxaPU2e:-NTSTLoZA9U7wU-qDJ7r:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/ad4aa0e377406780b14774ed407b882ec1fe0945/libos/src/bookkeep/libos_signal.c#L527)):*
<details><summary><i>Previously, NirjharRoyiitk wrote…</i></summary><blockquote>

Okay I will remove this one level of indirection
</blockquote></details>

done
___
*[`libos/test/regression/test_libos.py` line 547 at r12](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTLYStp3bQbi5brme0H:-NTSTNQzAuoBArsCt-He:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/299dde8f4c96d7a0e2d2ef1652c5a241777607e7/libos/test/regression/test_libos.py#L547)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You removed one empty line here. You can drag the mouse in the "revision history" of this file from left (the "base" symbol) to right ("r12") -- this way you'll see all the changes that your PR introduced in this particular file, and you'll see this "removal of the empty line".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 11:42 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-04-23 17:40 UTC, mkow requested changes
> Reviewed 2 of 6 files at r6, 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjABM7CNzQIKT-TosW:-NTjABM7CNzQIKT-TosX:b-5n70hz) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L462)):*
> ```C
> }
> 
> static bool is_in_out(PAL_CONTEXT* context) {
> ```

This is x86-64 specific, should be in `arch/x86_64/`, same as `is_x86_instr_legacy_prefix()`, which you already placed there.
___
*[`libos/src/bookkeep/libos_signal.c` line 518 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjAUIv-5PwA0pkd2h9:-NTjAUIv-5PwA0pkd2hA:b-gbr6v5) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L518)):*
> ```C
>         };
>         if (is_in_out(context)) {
>            /* Executing I/O instructions (e.g., in/out) inside an SGX enclave generates a #UD fault.
> ```

Actually, this whole logic is x86-64+SGX-specific, shouldn't it go to Linux-SGX PAL, into the `arch/x86_64` dir?
This file should contain only architecture-agnostic and backend-agnostic code, otherwise people like @stefanberger will have problems with their ports to other architectures.

See https://github.com/gramineproject/gramine/pull/1166 for a reference how to implement such a change in a portable way.


<!-- Sent from Reviewable.io -->

2023-04-23 19:27 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @NirjharRoyiitk)

___
*[`libos/src/bookkeep/libos_signal.c` line 518 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjAUIv-5PwA0pkd2h9:-NTj_80jA6zcM7uJFajw:b-25m5l0) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L518)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, this whole logic is x86-64+SGX-specific, shouldn't it go to Linux-SGX PAL, into the `arch/x86_64` dir?
This file should contain only architecture-agnostic and backend-agnostic code, otherwise people like @stefanberger will have problems with their ports to other architectures.

See https://github.com/gramineproject/gramine/pull/1166 for a reference how to implement such a change in a portable way.
</blockquote></details>

Indeed, it would be nice if is_in_out() could become arch_is_in_out() and be handled in an x86-specific source file. On other archs this function would then become just an inline returning false.


<!-- Sent from Reviewable.io -->

2023-04-23 19:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @NirjharRoyiitk and @stefanberger)

___
*[`libos/src/bookkeep/libos_signal.c` line 518 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjAUIv-5PwA0pkd2h9:-NTjbdiP6XMTGqkuWlZG:b6cjp4y) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L518)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Indeed, it would be nice if is_in_out() could become arch_is_in_out() and be handled in an x86-specific source file. On other archs this function would then become just an inline returning false.
</blockquote></details>

IMO no reason to even implement it on other archs, as the logic using it would be placed in Linux-SGX PAL, which is x86-only.


<!-- Sent from Reviewable.io -->

2023-04-25 11:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @NirjharRoyiitk, and @stefanberger)

___
*[`libos/src/bookkeep/libos_signal.c` line 518 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjAUIv-5PwA0pkd2h9:-NTs95cNB-JvlR0AClv9:b-5cyady) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L518)):*
> I feel like the PAL code is not ready/suitable for such remapping

Why not? Right now PAL gets the all the exceptions, process them and then calls LibOS, passing information about what happened. What's the problem with SGX PAL passing more suitable information to LibOS, free from SGX-specific quirks?

> What our current PAL code can do is to:
> - either emulate the hardware exception inside PAL itself,

We can't do this, the app may want to handle it.

> I'm unsure whether `#UD -> #GP` is the job for PAL code...

It definitely is? PAL's role is to abstract out the specific backend (host OS, hardware quirks, etc).


<!-- Sent from Reviewable.io -->

2023-06-28 09:12 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @NirjharRoyiitk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1192#-NZ0GbrPAieRuk8nEHFO:-NZ0GbrPAieRuk8nEHFP:b1mo67j) (no related file):*
Quick update: we hit this problem on the latest PyTorch.

___


<!-- Sent from Reviewable.io -->

2024-02-22 08:22 UTC, NirjharRoyiitk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: 12 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1192#-NZ0GbrPAieRuk8nEHFO:-NrEtlBB0q0877DfGko9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Quick update: we hit this problem on the latest PyTorch.
</blockquote></details>

Done.

___
___
*[`libos/src/bookkeep/libos_signal.c` line 462 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjABM7CNzQIKT-TosW:-NrEtnTu8hyajpUh31cb:btmg31d) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L462)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is x86-64 specific, should be in `arch/x86_64/`, same as `is_x86_instr_legacy_prefix()`, which you already placed there.
</blockquote></details>

moved it to common/src/arch/x86_64/cpu.c
___
*[`libos/src/bookkeep/libos_signal.c` line 518 at r13](https://reviewable.io/reviews/gramineproject/gramine/1192#-NTjAUIv-5PwA0pkd2h9:-NrEtwde3H1jQGeQNdPC:b-6xcl19) ([raw file](https://github.com/gramineproject/gramine/blob/6c1d0bde7532db2dbca045e3c6282ce69d111761/libos/src/bookkeep/libos_signal.c#L518)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> It definitely is? PAL's role is to abstract out the specific backend (host OS, hardware quirks, etc).

Ok, I agree. @NirjharRoyiitk You'll need to move your code from LibOS to Linux-SGX PAL... Unfortunately, it will be a bit more involved than what you have now in LibOS.
</blockquote></details>

I am now detecting the opcode in pal_exception.c in PAL linux-sgx and sending the appropriate event/signal (SIGSEGV/mem fault)


<!-- Sent from Reviewable.io -->

2024-04-29 16:58 UTC, mkow requested changes
> Reviewed 1 of 3 files at r11, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @NirjharRoyiitk, and @oshogbo)

___
*[`common/src/arch/x86_64/cpu.c` line 27 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwehHhhBdcbnRq-Q8WA:-NwehHhhBdcbnRq-Q8WB:b-wrpzwg) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L27)):*
> ```C
>        0x2e, /* CS segment override */
>        0x3e, /* DS segment override */
> ```

> ```C
>        0x2e, /* Branch not taken */
>        0x3e, /* Branch taken */
> ```

duplicates?
___
*[`common/src/arch/x86_64/cpu.c` line 62 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nwefrv74gvzaMRLVP8_:-Nwefrv89fstACQxwSDh:bknyhi) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L62)):*
> x86-64 instructions can have up to four legacy prefixes

source?
___
*[`common/src/arch/x86_64/meson.build` line 5 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweWhD17JyyPDA1eosn:-NweWhD17JyyPDA1eoso:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/meson.build#L5)):*
> ```Meson
> )
> 
> common_src_arch_c = files('cpu.c')
> ```





_Suggestion:_
```Meson
common_src_arch_c = files(
    'cpu.c',
)
```
___
*[`libos/src/bookkeep/libos_signal.c` line 482 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwekpmJ7z-lvp6yR-Q8:-NwekpmJ7z-lvp6yR-Q9:bptrp5p) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/src/bookkeep/libos_signal.c#L482)):*
> ```C
>         siginfo_t info = {
>            .si_signo = SIGILL,
>            .si_code = ILL_ILLOPC,
> ```

why unindent?
___
*[`libos/src/bookkeep/libos_signal.c` line 485 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nweky2k31Y8YcH4QHhu:-Nweky2k31Y8YcH4QHhv:b8by07) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/src/bookkeep/libos_signal.c#L485)):*
> ```C
>             .si_addr = (void*)addr,
>         };
>         log_debug("Illegal instruction during app execution at %p; delivering to app", rip);
> ```

Any reason for this change?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 136 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweQLmcD1nqrbi265TX:-NweQLmd1SBgWDF57rZK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L136)):*
> ```C
> /* return value: true if #UD was handled and execution can be continued without propagating #UD;
>  *               false if #UD was not handled and exception needs to be raised up to LibOS/app */
> static bool handle_ud(sgx_cpu_context_t* uc, int *event_num_ptr) {
> ```





_Suggestion:_
```C
int* out_event_num
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 178 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwegNPMEzIXs4GqTDyF:-NwegNPMEzIXs4GqTDyG:bnqy1lz) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L178)):*
> ```C
>         /* Executing I/O instructions (e.g., in/out) inside an SGX enclave generates a #UD fault.
>          * Gramine's PAL tries to handle this exception and propagates it to LibOS/app as a
>          * SIGILL signal. However, I/O instructions result in a #GP fault (which raises a
> ```

PAL doesn't send SIGILL to LibOS, it uses PAL API, not Linux API.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 180 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwegbY6430A2H5BdN8r:-NwegbY6430A2H5BdN8s:b-4v4msv) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L180)):*
> ```C
>          * SIGILL signal. However, I/O instructions result in a #GP fault (which raises a
>          * SIGSEGV signal) if I/O is not permitted. Let Gramine emulate these instructions as if
>          * they end up in SIGSEGV. This helps some apps, e.g. `lscpu`.
> ```

No need to list this here for justification, it's obvious that we want to emulate the 1-1 behavior of the normal x86 environment.



_Code quote:_
```C
 This helps some apps, e.g. `lscpu`.
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwelSmZ0bkGwrOLeQQj:-NwelSmZ0bkGwrOLeQQk:bgpbbgv) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L183)):*
> ```C
>          */
>         log_debug("Illegal instruction during app execution at %p, emulated as if "
>                   "throwing SIGSEGV; delivering to app", instr);
> ```

We shouldn't print this on every instruction emulated, printing is slow.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nweldt98Q2IX0P4xcSZ:-Nweldt98Q2IX0P4xcS_:b-t4unt4) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L183)):*
> ```C
>          */
>         log_debug("Illegal instruction during app execution at %p, emulated as if "
>                   "throwing SIGSEGV; delivering to app", instr);
> ```

Please rewrite the warning text, it should say that we're sending SIGSEGV because an IN/OUT instruction was executed.
___
*[`libos/test/regression/in_out_instruction.c` line 7 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweRqOH-WppRGu_BtDL:-NweRqOI3DJENHHM5cz6:bey3ka) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/test/regression/in_out_instruction.c#L7)):*
> ```C
> 
> /* Test description: this test verifies that in and out instructions correctly generate SIGSEGV.
>  * This raises SIGSEGV once for IN and once for OUT and then counts if number of SIGSEGVs is 2.
> ```

- It's obvious that this is the test description from the first 3 words.
- This test doesn't send SIGSEGV, it executes IN/OUT and checks whether SIGSEGV arrived.
- In a single paragraph you are formatting in/out in two different ways.



_Suggestion:_
```C
/* This test verifies whether `in` and `out` instructions correctly generate SIGSEGV,
 * by executing `in` and `out` once and then counting if the number of SIGSEGVs received is 2.
```
___
*[`libos/test/regression/in_out_instruction.c` line 11 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweSTws7HhPhChiUxMT:-NweSTws7HhPhChiUxMU:b-hohshz) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/test/regression/in_out_instruction.c#L11)):*
> ```C
> 
> #define _GNU_SOURCE
> #define EXPECTED_NUM_SIGSEGVS 2
> ```

This should be after includes, together with global variables (now it looks like this was some macro to change the include mode, like `_GNU_SOURCE`).
___
*[`libos/test/regression/in_out_instruction.c` line 29 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweVrvc43UFVeqJXPN7:-NweVrvc43UFVeqJXPN8:b7ywywe) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/test/regression/in_out_instruction.c#L29)):*
> ```C
> 
> unsigned char inb_func(unsigned short port) __attribute__((visibility("internal")));
> void outb_func(unsigned char value, unsigned short port) __attribute__((visibilit [...]

2024-05-03 12:24 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @NirjharRoyiitk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwyPJG5C2XB3RGpEZYY:-NwyPJG5C2XB3RGpEZYZ:b-tk9i7) (no related file):*
@NirjharRoyiitk Will you work on this PR? Otherwise I can take over and finish it.

___


<!-- Sent from Reviewable.io -->

2024-05-14 09:13 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @NirjharRoyiitk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwyPJG5C2XB3RGpEZYY:-NxqG9Wr0EczkKqtx_F2:b-c8sa22) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@NirjharRoyiitk Will you work on this PR? Otherwise I can take over and finish it.
</blockquote></details>

There was no reply from @NirjharRoyiitk for 1 week, I will take over this PR to finish it up (I will add myself as a co-author, but the main author will still be @NirjharRoyiitk).

___


<!-- Sent from Reviewable.io -->

2024-05-14 10:35 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r14, 7 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NirjharRoyiitk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwyPJG5C2XB3RGpEZYY:-Nxqebyu1cauB2WOutIJ:b3uw5wl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There was no reply from @NirjharRoyiitk for 1 week, I will take over this PR to finish it up (I will add myself as a co-author, but the main author will still be @NirjharRoyiitk).
</blockquote></details>

Done, I took over this PR.

I decided that I won't add myself as a co-author, as my changes are minimal.

___
___
*[`common/src/arch/x86_64/cpu.c` line 27 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwehHhhBdcbnRq-Q8WA:-NxqRXbv2tzW7mK3n-6M:b-jfvmxo) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```C
>        0x2e, /* CS segment override */
>        0x3e, /* DS segment override */
> ```

> ```C
>        0x2e, /* Branch not taken */
>        0x3e, /* Branch taken */
> ```

duplicates?
</blockquote></details>

Done, yes, these are duplicates (which one is used depends on the opcode that follows the prefix). I removed the duplicated entries and instead augmented the comments.
___
*[`common/src/arch/x86_64/cpu.c` line 62 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nwefrv74gvzaMRLVP8_:-NxqRiup3q8xG7Mo_cDr:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> x86-64 instructions can have up to four legacy prefixes

source?
</blockquote></details>

Done
___
*[`common/src/arch/x86_64/meson.build` line 5 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweWhD17JyyPDA1eosn:-NxqRwiZ9zY8F_QFchJ_:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/meson.build#L5)):*
> ```Meson
> )
> 
> common_src_arch_c = files('cpu.c')
> ```

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 136 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweQLmcD1nqrbi265TX:-NxqTux64qMOkCkbp10u:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L136)):*
> ```C
> /* return value: true if #UD was handled and execution can be continued without propagating #UD;
>  *               false if #UD was not handled and exception needs to be raised up to LibOS/app */
> static bool handle_ud(sgx_cpu_context_t* uc, int *event_num_ptr) {
> ```

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 178 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwegNPMEzIXs4GqTDyF:-NxqV8EB7ivrb3dmcSip:b-ltrs5f) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

PAL doesn't send SIGILL to LibOS, it uses PAL API, not Linux API.
</blockquote></details>

Done, rephrased
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 180 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwegbY6430A2H5BdN8r:-NxqV96tCSXdqPfq2lkN:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need to list this here for justification, it's obvious that we want to emulate the 1-1 behavior of the normal x86 environment.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwelSmZ0bkGwrOLeQQj:-NxqV9atCQjWPzEejXfS:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L183)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We shouldn't print this on every instruction emulated, printing is slow.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nweldt98Q2IX0P4xcSZ:-NxqVA8LEKxw0mq4b-bB:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/pal/src/host/linux-sgx/pal_exception.c#L183)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please rewrite the warning text, it should say that we're sending SIGSEGV because an IN/OUT instruction was executed.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 232 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nxqern22HG1pzDlJgpS:-Nxqern22HG1pzDlJgpT:bohvj5n) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L232)):*
> ```C
>                 if (event_num_from_handle_ud != PAL_EVENT_ILLEGAL) {
>                     /* TODO: fix this after rebase, we must skip all verification and cr2/err logic
>                      *       and just call the LibOS upcall (probably with cr2 == 0x0) */
> ```

Blocking comment for myself: after a rebase, I'll need to analyze the flows in the current master branch, and figure out a correct way to change from UD to GP (it changed drastically since last year when this PR was started).
___
*[`libos/src/bookkeep/libos_signal.c` line 482 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NwekpmJ7z-lvp6yR-Q8:-NxqS28E1y3LjUB510tt:b-n42tuq) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/src/bookkeep/libos_signal.c#L482)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why unindent?
</blockquote></details>

Done, reverted
___
*[`libos/src/bookkeep/libos_signal.c` line 485 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nweky2k31Y8YcH4QHhu:-NxqS8UY7XjsUgBAvVFK:b-n42tuq) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/src/bookkeep/libos_signal.c#L485)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any reason for this change?
</blockquote></details>

Done, reverted
___
*[`libos/test/regression/install_musl_tests.sh` line 1 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NxqSQhv1jrRxQg5sABl:-NxqSQhv1jrRxQg5sABm:b6qj747) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/test/regression/install_musl_tests.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

There was an accidental change from a normal file to an executable file. I reverted this change.
___
*[`libos/test/regression/in_out_instruction.c` line 7 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-NweRqOH-WppRGu_BtDL:-NxqXKOm9Cp-ehRpkBJd:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/libos/test/regression/in_out_instruction.c#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i> [...]

2024-05-14 11:38 UTC, dimakuv commented
Jenkins, test this please

2024-05-19 21:58 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 7 files at r2, 4 of 11 files at r7, 2 of 6 files at r10, 1 of 2 files at r13, 4 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 62 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nwefrv74gvzaMRLVP8_:-NyHq-I16CzZufsmQR51:bh0dcyl) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

this is incorrect; while there can only be at most 4 *useful* ones, instructions can have redundant prefixes; the actual limit that should be implemented here is the 15-byte limit on total instruction size
___
*[`common/src/arch/x86_64/cpu.c` line 19 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHpVVn41141-C2usNw:-NyHpVVn41141-C2usNx:b-5uuox7) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/common/src/arch/x86_64/cpu.c#L19)):*
> ```C
>      * Vol. 2, Chapter 2.2.1 and Figure 2-3 "Prefix Ordering in 64-bit Mode".
>      */
>     uint8_t prefix_list[] = {
> ```

I think this should be a `switch (op) { ... }` instead of looping through an array
___
*[`common/src/arch/x86_64/cpu.c` line 53 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHpian0LofZYWlUMg1:-NyHpian0LofZYWlUMg2:bc6alpo) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/common/src/arch/x86_64/cpu.c#L53)):*
> ```C
> 
> bool is_in_out(uint8_t* rip) {
>     uint8_t opcodes[] = {
> ```

likewise, I believe a `switch` is better suited here
___
*[`libos/test/regression/in_out_instruction_test.c` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxyZ_g7m9mMZTs8dLa:-NyHqdiBBjXAyJQ53Vzc:b-qjdsux) ([raw file](https://github.com/gramineproject/gramine/blob/48834a770677960b2b7478abbd567b069f4d8128/libos/test/regression/in_out_instruction_test.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I educated myself about `sigsetjmp` and `siglongjmp`. Bar my comments, I think the implementation is correct (given that this test is single-threaded).
</blockquote></details>

I think this include is no longer necessary now


<!-- Sent from Reviewable.io -->

2024-05-19 22:00 UTC, mkow requested changes
> Reviewed 6 of 7 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mwkmwkmwk, and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 62 at r14](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nwefrv74gvzaMRLVP8_:-NyHU1io9qgIXdNFj9yi:b-t478lt) ([raw file](https://github.com/gramineproject/gramine/blob/c628bb4541c77903dc01a17dcffe8413bd34aa13/common/src/arch/x86_64/cpu.c#L62)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this is incorrect; while there can only be at most 4 *useful* ones, instructions can have redundant prefixes; the actual limit that should be implemented here is the 15-byte limit on total instruction size
</blockquote></details>

"x86-64 instructions can have up to four legacy prefixes" doesn't follow from the description you pasted (and AFAIK it's actually not true).
___
*[`common/src/arch/x86_64/cpu.c` line 21 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHUM4KDBXsfxF--R8d:-NyHUM4KDBXsfxF--R8e:b-eux70g) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/common/src/arch/x86_64/cpu.c#L21)):*
> ```C
>     uint8_t prefix_list[] = {
>         /* Group 1 */
>         0xf0, /* LOCK prefix */
> ```

Actually, this one used with in/out generates #UD instead of #GP.
___
*[`common/src/arch/x86_64/cpu.c` line 49 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHUHNl4K3FI9g8u5xT:-NyHUHNl4K3FI9g8u5xU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/common/src/arch/x86_64/cpu.c#L49)):*
> ```C
>      * any of 0x40-0x4f. For details, see Intel SDM, Vol. 2, Chapter 2.2.1 "REX Prefixes".
>      */
>     return (0x40 <= op && op <= 0x4f);
> ```





_Suggestion:_
```C
return 0x40 <= op && op <= 0x4f;
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 137 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHqktZ09TeHAnOCp6G:-NyHqktZ09TeHAnOCp6H:b6tg992) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L137)):*
> ```C
>  *               false if #UD was not handled and exception needs to be raised up to LibOS/app */
> static bool handle_ud(sgx_cpu_context_t* uc, int* out_event_num) {
>     /* most unhandled #UD faults raise up to LibOS/app as "Illegal instruction" signals; however
> ```

There are no signals in PAL<->LibOS API (or at least not in this flow?).



_Suggestion:_
```C
most unhandled #UD faults are translated and sent to LibOS/app as "Illegal instruction" exceptions
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 138 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHqcL9AZlSFwrLUr0L:-NyHqcL9AZlSFwrLUr0M:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L138)):*
> ```C
> static bool handle_ud(sgx_cpu_context_t* uc, int* out_event_num) {
>     /* most unhandled #UD faults raise up to LibOS/app as "Illegal instruction" signals; however
>      * some #UDs (e.g. triggered due to IN/OUT/INS/OUTS) must raise "Memory fault" signal */
> ```





_Suggestion:_
```C
must end up as "Memory fault" exceptions */
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 232 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nxqern22HG1pzDlJgpS:-NyHrCfT82dGPeVgAwFn:bb83bwp) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking comment for myself: after a rebase, I'll need to analyze the flows in the current master branch, and figure out a correct way to change from UD to GP (it changed drastically since last year when this PR was started).
</blockquote></details>

Can you please rebase now? I'll continue reviewing then.
___
*[`libos/test/regression/in_out_instruction.c` line 49 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHlx4REWthq6f7Fun3:-NyHlx4REWthq6f7Fun4:b-jmepyd) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/libos/test/regression/in_out_instruction.c#L49)):*
> ```C
> ".type outb_instruction_addr, @function\n"
> ".type ret, @function\n"
> ".type end_of_ret, @function\n"
> ```

unused
___
*[`libos/test/regression/in_out_instruction.c` line 87 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-NyHmVKx1A8KX-nskriz:-NyHmVKx1A8KX-nskrj-:bd5nha8) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/libos/test/regression/in_out_instruction.c#L87)):*
> ```C
>     g_sigsegv_triggered++;
> 
>     /* no need to fixup the context (other than RIP) as we only modified caller-saved RDI and RSI in
> ```

No, we didn't.
That's why we should finally stop using AT&T ;)



_Code quote:_
```C
we only modified caller-saved RDI and RSI
```


<!-- Sent from Reviewable.io -->

2024-06-05 00:28 UTC, mkow reviewed
> Reviewed 3 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk and @NirjharRoyiitk)

___
*[`common/src/arch/x86_64/cpu.c` line 71 at r16](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nz_fVdF7sxseiq7TZdj:-Nz_fVdF7sxseiq7TZdk:bp9no1f) ([raw file](https://github.com/gramineproject/gramine/blob/f2a50292010fa76684c683b891d1727ac1657b0a/common/src/arch/x86_64/cpu.c#L71)):*
> ```C
> 
>     /* skip over the optional REX prefix */
>     if (is_x86_instr_rex_prefix(rip[idx]))
> ```

this may already be over the limit (ditto below)
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 232 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nxqern22HG1pzDlJgpS:-Nz_mqPK-ImgdrLmqJgi:b-80tlqk) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we first finish up with the outstanding comments? @mkow @mwkmwkmwk
</blockquote></details>

Sure.


<!-- Sent from Reviewable.io -->

2024-06-05 13:09 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`common/src/arch/x86_64/cpu.c` line 71 at r16](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nz_fVdF7sxseiq7TZdj:-NzcVus15ik8H7GYRgnq:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f2a50292010fa76684c683b891d1727ac1657b0a/common/src/arch/x86_64/cpu.c#L71)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this may already be over the limit (ditto below)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-05 22:29 UTC, mkow reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-06-07 12:10 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxYxN88_EKXfDJHJxT):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note to myself: don't forget to use this message when doing final rebase.
</blockquote></details>

Done
___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1192#-NOxYoFx9OApo4NdVAyh):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `propagates` (can be fixed during final rebase, no need to change now)
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 232 at r15](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nxqern22HG1pzDlJgpS:-Nzm_1qHEZF_zz2k0f5H:bm7xhpq) ([raw file](https://github.com/gramineproject/gramine/blob/183635f6ad1e7dc349abf6f68ea27a8f7abcc40d/pal/src/host/linux-sgx/pal_exception.c#L232)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

acknowledged everything outstanding
</blockquote></details>

Done, rebased and fixed the crt2/err logic.


<!-- Sent from Reviewable.io -->

2024-06-07 12:10 UTC, dimakuv commented
Jenkins, test this please

2024-06-08 16:06 UTC, mkow requested changes
> Reviewed 8 of 8 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @NirjharRoyiitk)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQ0lBC6ueg6d7ObUP):*
I think that's the correct form?



_Suggestion:_
```
as if they generated SIGSEGV
```
___
*[`-- commits` line 8 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQEZF3wHI8xhuBK5U):*
without this it sounds like a direct contradiction to the previous paragraph



_Suggestion:_
```
However, I/O instructions result in a #GP fault outside SGX
```
___
*[`-- commits` line 10 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQQZY-sGXsR_VylJB):*




_Suggestion:_
```
as if they ended up in SIGSEGV
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 238 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsTTDn466Doco7fzgh:-NzsTTDn466Doco7fzgi:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L238)):*
> ```C
>          * fault. Without the below corner-case handling, PAL would propagate this fault to LibOS as
>          * an "Illegal instruction" Gramine exception. However, I/O instructions result in a #GP
>          * fault (which corresponds to "Memory fault" Gramine exception) if I/O is not permitted
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 243 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsTXML5zwb009QKHmx:-NzsTXML5zwb009QKHmy:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L243)):*
> ```C
>          *
>          * Note that I/O instructions with a LOCK prefix always result in a #UD fault, so they are
>          * special cased here.
> ```





_Suggestion:_
```C
special-cased
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 306 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsUEcx7xUnIAum6JSQ:-NzsUEcyA7nXNtIdx-Jz:b-ne9sow) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L306)):*
> ```C
>      */
> 
>     bool is_synthetic_gp = false; /* IN/OUT/INS/OUTS instructions morth #UD into a synthetic #GP */
> ```

morth?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 455 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nzs_lcGCXM7zAOCI8Jo:-Nzs_lcGCXM7zAOCI8Jp:b-jypirp) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L455)):*
> ```C
>             assert(event_num == PAL_EVENT_MEMFAULT);
>             ctx.trapno = SGX_EXCEPTION_VECTOR_GP;
>             ctx.err = 0x4; /* dummy sane value: P=0, W/R=0, U/S = 1, all the rest are zeros */
> ```

(just the order)



_Suggestion:_
```C
U/S = 1, W/R=0, P=0
```


<!-- Sent from Reviewable.io -->

2024-06-08 17:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQ0lBC6ueg6d7ObUP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think that's the correct form?
</blockquote></details>

Will fix during final rebase
___
*[`-- commits` line 8 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQEZF3wHI8xhuBK5U):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

without this it sounds like a direct contradiction to the previous paragraph
</blockquote></details>

Will fix during final rebase
___
*[`-- commits` line 10 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQQZY-sGXsR_VylJB):*
Will fix during final rebase
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 238 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsTTDn466Doco7fzgh:-Nzsx1j0BK1Hxnl17a1l:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 243 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsTXML5zwb009QKHmx:-NzswZPV0xrIab_7u6er:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L243)):*
> ```C
>          *
>          * Note that I/O instructions with a LOCK prefix always result in a #UD fault, so they are
>          * special cased here.
> ```

Done
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 306 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsUEcx7xUnIAum6JSQ:-Nzsx5RuDX8DPvQVa9Kp:b-opfgwx) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

morth?
</blockquote></details>

Done, typo
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 455 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nzs_lcGCXM7zAOCI8Jo:-Nzswfy212vXRlrHtCxO:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f4013245d62b158d7283c51695b4f3079bafd921/pal/src/host/linux-sgx/pal_exception.c#L455)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(just the order)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-08 19:21 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NirjharRoyiitk)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 457 at r19](https://reviewable.io/reviews/gramineproject/gramine/1192#-NztHiha4A5P08VHBd2P:-NztHiha4A5P08VHBd2Q:b2mljvu) ([raw file](https://github.com/gramineproject/gramine/blob/7506fac1acd1b0c0a74721ea8d7369d235319b5c/pal/src/host/linux-sgx/pal_exception.c#L457)):*
> ```C
>             ctx.err = 0x4; /* dummy sane value: U/S=1, W/R=0, P=0, all the rest are zeros */
>             ctx.cr2 = 0x0; /* on #GP, maddr = 0 */
>             has_hw_fault_address = true;
> ```

That's just plain false. Either the variable should be renamed, or this special path should be removed, changing the below code to accept `is_synthetic_gp` in addition to `has_hw_fault_address`. I'd prefer the latter.


<!-- Sent from Reviewable.io -->

2024-06-08 20:42 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 457 at r19](https://reviewable.io/reviews/gramineproject/gramine/1192#-NztHiha4A5P08VHBd2P:-NztXqb2EltKx400wpBt:b4rhesa) ([raw file](https://github.com/gramineproject/gramine/blob/7506fac1acd1b0c0a74721ea8d7369d235319b5c/pal/src/host/linux-sgx/pal_exception.c#L457)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

That's just plain false. Either the variable should be renamed, or this special path should be removed, changing the below code to accept `is_synthetic_gp` in addition to `has_hw_fault_address`. I'd prefer the latter.
</blockquote></details>

Done. I hope I understood your request correctly.

Note that now `ctx.cr2 == 0` because `ctx` is set to all-zeros. However, `ctx.err == 0`, so it's a dummy weird value (for example, it says that the error happened in ring-0 mode). I guess this is still fine: most apps won't bother to look at `err`.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 453 at r20](https://reviewable.io/reviews/gramineproject/gramine/1192#-Nzt_LcNEKWb4LkBPG6g:-Nzt_LcNEKWb4LkBPG6h:b-pwr8y9) ([raw file](https://github.com/gramineproject/gramine/blob/0b4535a0465c109d42e3c75314c4f55dd4be2fe7/pal/src/host/linux-sgx/pal_exception.c#L453)):*
> ```C
>         ctx.trapno = trusted_exit_info.vector;
>         /* Only these two exceptions save information in EXINFO. */
>         if (!is_synthetic_gp && (trusted_exit_info.vector == SGX_EXCEPTION_VECTOR_GP
> ```

FYI: this `!is_synthetic_gp` is not strictly needed because `trusted_exit_info.vector` is a SGX_EXCEPTION_VECTOR_UD... But I add it anyway just to make it explicit (in case we would decide to modify `trusted_exit_info` to _GP in the future).


<!-- Sent from Reviewable.io -->

2024-06-09 00:15 UTC, mkow reviewed
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk and @NirjharRoyiitk)



<!-- Sent from Reviewable.io -->

2024-06-26 22:56 UTC, mwkmwkmwk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r15, 7 of 8 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192#-:-O0LkykQ5KIVQtOdKcRE:bnfp4nl)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NirjharRoyiitk)



<!-- Sent from Reviewable.io -->

2024-06-27 06:34 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQ0lBC6ueg6d7ObUP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will fix during final rebase
</blockquote></details>

Done
___
*[`-- commits` line 8 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQEZF3wHI8xhuBK5U):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will fix during final rebase
</blockquote></details>

Done
___
*[`-- commits` line 10 at r18](https://reviewable.io/reviews/gramineproject/gramine/1192#-NzsQQZY-sGXsR_VylJB):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will fix during final rebase
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-27 06:34 UTC, dimakuv commented
Jenkins, test this please

2024-06-27 12:48 UTC, mwkmwkmwk reviewed
> Reviewed 4 of 4 files at r21.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-06-27 17:51 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-28 00:29 UTC, kailun-qin approved these changes
> Reviewed 2 of 7 files at r2, 4 of 11 files at r7, 3 of 7 files at r15, 3 of 8 files at r18, 1 of 1 files at r20, 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-28 07:50 UTC, merged