[Docs] Add "Gramine features" (in Markdown)
gramineproject/gramine pull request #1194
Opened 2023-02-21 13:54 UTC by dimakuv

## Description of the changes 

NOTE: It's unclear how to render this document in RestructedText / ReadTheDocs as it seems to not support nested inline markup. So the document is written in GitHub-flavoured Markdown format.

## How to test this PR? 

Read it.

2023-02-23 08:56 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/misc/features.md` line 631 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxKNlA1GaatkISU1kt:-NOxKNlA1GaatkISU1ku:b-iq1mcm) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L631)):*
> ```Markdown
>   <sup>[1](#file-system-operations)</sup>
> 
> - :x:`_sysctl()`
> ```

extra '_'
___
*[`Documentation/misc/features.md` line 1547 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxG0_62m0_1kq_iJKa:-NOxG0_62m0_1kq_iJKb:b2xqjlx) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L1547)):*
> ```Markdown
> ### Process and thread identifiers
> 
> Gramine fully supports the following indentifiers: Process IDs (PIDs), Parent Process IDs (PPIDs),
> ```

identifiers



_Code quote:_
```Markdown
indentifiers
```
___
*[`Documentation/misc/features.md` line 1897 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxS3igDeeLeBI6yCwR:-NOxS3igDeeLeBI6yCwS:b2xqjlx) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L1897)):*
> ```Markdown
> ### User and group identifiers
> 
> Gramine has dummy support for the following indentifiers:
> ```

identifiers



_Code quote:_
```Markdown
indentifiers
```
___
*[`Documentation/misc/features.md` line 2062 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxSpnh-TTO2xh2KNCB:-NOxSpnh-TTO2xh2KNCC:b8oq009) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L2062)):*
> ```Markdown
> currently not supported.
> 
> Gramine support file truncation (via `truncate()` and `ftruncate()`). There is one exception
> ```

supports



_Code quote:_
```Markdown
support
```


<!-- Sent from Reviewable.io -->

2023-02-23 09:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly)

___
*[`Documentation/misc/features.md` line 631 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxKNlA1GaatkISU1kt:-NOxXUu-C0hVGSLB_ih2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L631)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

extra '_'
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 1547 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxG0_62m0_1kq_iJKa:-NOxXXvHEbm45VvnrY6n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L1547)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

identifiers
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 1897 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxS3igDeeLeBI6yCwR:-NOxXYMQAPQJjzhtYwPS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L1897)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

identifiers
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 2062 at r1](https://reviewable.io/reviews/gramineproject/gramine/1194#-NOxSpnh-TTO2xh2KNCB:-NOxX_tYAJbYfLp9VhP-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/968fbe8d0b700d2d9e4c7030e076701f379f88a2/Documentation/misc/features.md#L2062)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

supports
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-24 00:47 UTC, llly reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-24 09:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/misc/features.md` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1S38q4Vpz9Dn-fN0M:-NP1S38q4Vpz9Dn-fN0N:b-imjhau) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1)):*
> ```Markdown
> # Gramine features
> ```

This is a great summary! But would still like to understand - what's the target audience? I would say it might be a bit technical for some. And if we do target different readers, we may add a section which can guide/point them to different sections quickly.

And why we put it in `misc`rather than somewhere looks to be more crucial?
___
*[`Documentation/misc/features.md` line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1RJ0qDy9_sm1osIed:-NP1RJ0qDy9_sm1osIee:bxcb6yd) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L11)):*
> ```Markdown
> Gramine **intercepts all application requests** to the host OS. Some of these requests are processed
> entirely inside Gramine, and some are forwarded to the host OS. Either way, each application's
> request and each host's reply is verified for correctness and consistency. For these verifications,
> ```

Mention Iago attacks here?



_Code quote:_
```Markdown
request and each host's reply is verified for correctness and consistency.
```
___
*[`Documentation/misc/features.md` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1RaMkEQz7iW8OTaxh:-NP1RaMkEQz7iW8OTaxi:b2xeik2) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L17)):*
> ```Markdown
> standards like POSIX ("bug-for-bug compatibility"). At the same time, Gramine is minimalistic, and
> implements **only the most important subset of Linux functionality**, enough to run typical
> cloud-native applications.
> ```

It's hard to classify which are "cloud-native" actually :).



_Code quote:_
```Markdown
cloud-native
```
___
*[`Documentation/misc/features.md` line 22 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Xm0E0ycnOW4MkLrN:-NP1Xm0E0ycnOW4MkLrO:b-vwvvjx) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L22)):*
> ```Markdown
> 
> - **Linux features**: features can be (1) supported, (2) generally supported, (3) with limited
>   support, or (4) not supported at all in Gramine. If the feature is not supported, we also specify
> ```

If we do categorize our feature support into these 4 levels, then for each feature below we should state its status by following these words.



_Code quote:_
```Markdown
- **Linux features**: features can be (1) supported, (2) generally supported, (3) with limited
  support, or (4) not supported at all in Gramine. If the feature is not supported, we also specify
```
___
*[`Documentation/misc/features.md` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1YMn-34Prwq_U2hFZ:-NP1YMn-34Prwq_U2hF_:bfxf1jg) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L23)):*
> ```Markdown
> - **Linux features**: features can be (1) supported, (2) generally supported, (3) with limited
>   support, or (4) not supported at all in Gramine. If the feature is not supported, we also specify
>   whether there are plans to support it in the future (and if not, the rationale why not).
> ```

We in fact also documented CANs and CAN'Ts of the partially supported features.
___
*[`Documentation/misc/features.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1lgXl0lW_4NCYsvwL:-NP1lgXl0lW_4NCYsvwM:b-701aay) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L32)):*
> ```Markdown
>     not detected).
> 
> - **Gramine-specific features**: additional features, e.g., attestation primitives.
> ```

GSC? existless ocalls? security features (ASLR etc.)?

Support on debugging, profiling, pluggable signing?

We do not consider these as features?
___
*[`Documentation/misc/features.md` line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Ta-F8XEHKWL96SJi:-NP1Ta-F8XEHKWL96SJj:b3kqx) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L60)):*
> ```Markdown
> - **Linux kernel-to-userspace ABI**, in particular, two standards:
> 
>   - **System V ABI**: defines how applications invoke system calls and receive signals,
> ```

.



_Code quote:_
```Markdown
,
```
___
*[`Documentation/misc/features.md` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1UVGd8hcl56N13s_B:-NP1UVGd8hcl56N13s_C:b8ntybd) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L63)):*
> ```Markdown
>   - **Executable and Linking Format (ELF)**: defines how applications are loaded from binary files.
> 
> <details><summary>Gramine also has internal APIs, used by Gramine developers</summary>
> ```

We mainly want to talk about Gramine features in this doc. Any special reason we mention internal APIs here? These terminologies seem also not be used in the following sections.



_Code quote:_
```Markdown
Gramine also has internal APIs, used by Gramine developers
```
___
*[`Documentation/misc/features.md` line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1kzvBDrEr-_d43g_Y:-NP1kzvBDrEr-_d43g_Z:bsizhj8) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L64)):*
> ```Markdown
> 
> <details><summary>Gramine also has internal APIs, used by Gramine developers</summary>
> ```

We also basically manage the structure of the doc by grouping syscalls. That maybe why checkpoints and ELF loader etc. are not mentioned. Do we want to include these?
___
*[`Documentation/misc/features.md` line 72 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Lcgh4EyF_eXEAsyK:-NP1Lcgh4EyF_eXEAsyL:bkj4qpo) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L72)):*
> ```Markdown
>   `lib_SHA256Init()`, `lib_AESGCMEncrypt()`, `lib_SSLRead()`, `lib_HKDF_SHA256()`.
> 
> - Data structures: doubly-linked lists, AVL trees, hash tables. Implemenations of lists and AVL
> ```

Implementations



_Code quote:_
```Markdown
Implemenations
```
___
*[`Documentation/misc/features.md` line 101 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1T8-W3909q3t4wxlR:-NP1T8-W3909q3t4wxlS:b-scjq0v) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L101)):*
> ```Markdown
> 6.0](https://github.com/torvalds/linux/blob/v6.0/arch/x86/entry/syscalls/syscall_64.tbl).
> 
> <details><summary>:blue_book: List of all system calls in Gramine</summary>
> ```

It's actually the status of system call support in Gramine (as it's seems to be a full list whether or not we support it).



_Code quote:_
```Markdown
List of all system calls in Gramine
```
___
*[`Documentation/misc/features.md` line 1456 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1WW3V7BZBhbXP17dJ:-NP1WW3V7BZBhbXP17dK:b-chbhw4) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527 [...]

2023-03-01 11:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 0 of 1 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @llly)

___
*[`Documentation/misc/features.md` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1S38q4Vpz9Dn-fN0M:-NPRgl7W7sYeu19Xv0zB:b-c3p9ca) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is a great summary! But would still like to understand - what's the target audience? I would say it might be a bit technical for some. And if we do target different readers, we may add a section which can guide/point them to different sections quickly.

And why we put it in `misc`rather than somewhere looks to be more crucial?
</blockquote></details>

Done, both comments.
___
*[`Documentation/misc/features.md` line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1RJ0qDy9_sm1osIed:-NPRh4fV89qegucMMCR9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L11)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Mention Iago attacks here?
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1RaMkEQz7iW8OTaxh:-NPRi6ij2XpEitArgcK_:b-1izwag) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L17)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's hard to classify which are "cloud-native" actually :).
</blockquote></details>

Done. I removed this word as it is heavily overused.

I used `cloud-native` term in the sense that is exemplified in "OS abstraction" item on this page: https://tanzu.vmware.com/cloud-native

Basically, Gramine targets applications that are portable (don't use super-fancy Linux features and can run even on older kernels) and hardware-independent (e.g., no special tricks with network card interfaces).
___
*[`Documentation/misc/features.md` line 22 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Xm0E0ycnOW4MkLrN:-NPRievL2a3VU7lSwsXN:b-aoug6w) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L22)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

If we do categorize our feature support into these 4 levels, then for each feature below we should state its status by following these words.
</blockquote></details>

Yeah. I had this distinction between **features** and **syscalls**:
- Features are supported/.../unsupported
- Syscalls are implemented/.../unimplemented

But I can see how this is confusing. I'll just use a single word `implemented` everywhere (I find "implemented" better fitting for both features and syscalls). Done.
___
*[`Documentation/misc/features.md` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1YMn-34Prwq_U2hFZ:-NPRkBNV-WWuxVMEINCH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L23)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We in fact also documented CANs and CAN'Ts of the partially supported features.
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1lgXl0lW_4NCYsvwL:-NPRk_9r9G-wg_2GmW7-:bvea40a) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L32)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

GSC? existless ocalls? security features (ASLR etc.)?

Support on debugging, profiling, pluggable signing?

We do not consider these as features?
</blockquote></details>

Done. I explained what I cover in this document.
___
*[`Documentation/misc/features.md` line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Ta-F8XEHKWL96SJi:-NPRkfM06y363dOURZpG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L60)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1UVGd8hcl56N13s_B:-NPRl9XI2Mqitplzvm2-:b-age3h) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We mainly want to talk about Gramine features in this doc. Any special reason we mention internal APIs here? These terminologies seem also not be used in the following sections.
</blockquote></details>

I liked the idea of keeping this info somewhere. But you're right, let me just remove this.
___
*[`Documentation/misc/features.md` line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1kzvBDrEr-_d43g_Y:-NPRkjr49p-8zcTT2Oku:b-mpl2te) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L64)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We also basically manage the structure of the doc by grouping syscalls. That maybe why checkpoints and ELF loader etc. are not mentioned. Do we want to include these?
</blockquote></details>

No, I don't want to include internal details of Gramine.

Note that the ELF loading quirks I explain in the corresponding section. So I **do include it**.

But e.g. checkpointing is an internal detail of Gramine that gives zero information to a software engineer who wants to figure out whether Gramine is able to run his/her application. Checkpointing is fully transparent to the application (well, it may be buggy, but it's a different story).
___
*[`Documentation/misc/features.md` line 72 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1Lcgh4EyF_eXEAsyK:-NPRlLoz3rxGz7Tb60Gz:b-7wso34) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L72)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Implementations
</blockquote></details>

Not relevant anymore
___
*[`Documentation/misc/features.md` line 101 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1T8-W3909q3t4wxlR:-NPRlef57ypHuW6Tw1dM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L101)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's actually the status of system call support in Gramine (as it's seems to be a full list whether or not we support it).
</blockquote></details>

Done.
___
*[`Documentation/misc/features.md` line 1456 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1WW3V7BZBhbXP17dJ:-NPRlpiU6FSc9ioRgdMX:b-5ejk9s) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1456)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summa [...]

2023-03-01 15:14 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 0 of 1 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @llly)

___
*[`Documentation/misc/features.md` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1RaMkEQz7iW8OTaxh:-NPSj1Y8AYceoKiYThZB:b-g0fmyw) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I removed this word as it is heavily overused.

I used `cloud-native` term in the sense that is exemplified in "OS abstraction" item on this page: https://tanzu.vmware.com/cloud-native

Basically, Gramine targets applications that are portable (don't use super-fancy Linux features and can run even on older kernels) and hardware-independent (e.g., no special tricks with network card interfaces).
</blockquote></details>

+1 to Kailun, "cloud-native" is rather a marketing term than anything technical.


<!-- Sent from Reviewable.io -->

2023-03-02 04:02 UTC, kailun-qin reviewed
Pls kindly update the link to https://github.com/gramineproject/gramine/blob/dimakuv/add-gramine-features-doc/Documentation/devel/features.md.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194#-:-NPVBMXk1itzCCXqx4qR:b3r82u)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`Documentation/devel/features.md` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVFx4DCGBxI2f1CbgJ:-NPVFx4DCGBxI2f1CbgK:b2nhz5b) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L16)):*
> ```Markdown
> Gramine **intercepts all application requests** to the host OS. Some of these requests are processed
> entirely inside Gramine, and some are forwarded to the host OS. Either way, each application's
> request and each host's reply is verified for correctness and consistency. For these verifications,
> ```

are



_Code quote:_
```Markdown
is
```
___
*[`Documentation/devel/features.md` line 1464 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVLYrwDugIJNCaHDwR:-NPVLYrwDugIJNCaHDwS:b-o70q1u) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L1464)):*
> ```Markdown
> Currently, Gramine does *not* fully support fork in multi-threaded applications. There is a known
> bug in Gramine that if one thread is performing fork and another thread modifies the internal
> Gramine state, the state may get corrupted (which may lead to failures).
> ```

Add a link to the tracking issue?



_Code quote:_
```Markdown
Currently, Gramine does *not* fully support fork in multi-threaded applications. There is a known
bug in Gramine that if one thread is performing fork and another thread modifies the internal
Gramine state, the state may get corrupted (which may lead to failures).
```
___
*[`Documentation/devel/features.md` line 2526 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVMso4-w1858abg4cV:-NPVMso4-w1858abg4cW:be3wjah) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L2526)):*
> ```Markdown
> - `SO_REUSEADDR` (ignored, same as in Linux).
> 
> <details><summary>:speech_balloon: Note on named UDSes</summary>
> ```

construction?



_Code quote:_
```Markdown
speech_balloon
```
___
*[`Documentation/devel/features.md` line 3155 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVSJLyBJQX_bzk-EUq:-NPVSJLyBJQX_bzk-EUr:b5xwwul) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L3155)):*
> ```Markdown
> Report* and *SGX Quote* accordingly, in case of SGX backend) through the `/dev/attestation/`
> pseudo-filesystem. Manipulating with the `/dev/attestation/` pseudo-files allows to program local
> attestation and remote attestation flows. Additionally, the `dev/attestation/` pseudo-filesystem
> ```

Should be`/dev/attestation/` (or more precisely `/dev/attestation/keys/`).



_Code quote:_
```Markdown
`dev/attestation/`
```
___
*[`Documentation/devel/features.md` line 3224 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVTfYe6uu315rLVip3:-NPVTfYe6uu315rLVip4:b-ovn94u) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L3224)):*
> ```Markdown
> In case of SGX backend, Gramine needs a hint whether the first loaded binary is PIE or non-PIE. This
> hint may be provided via the [`sgx.nonpie_binary` manifest
> option](https://gramine.readthedocs.io/en/stable/manifest-syntax.html#non-pie-binaries).
> ```

I understand this is a living doc (w/ the last major update happened in Feb 2023). But we just removed this and it seemed useless.



_Code quote:_
```Markdown
In case of SGX backend, Gramine needs a hint whether the first loaded binary is PIE or non-PIE. This
hint may be provided via the [`sgx.nonpie_binary` manifest
option](https://gramine.readthedocs.io/en/stable/manifest-syntax.html#non-pie-binaries).
```
___
*[`Documentation/misc/features.md` line 64 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1kzvBDrEr-_d43g_Y:-NPVCa_4BKjtAR2lpR4z:b-1lje90) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, I don't want to include internal details of Gramine.

Note that the ELF loading quirks I explain in the corresponding section. So I **do include it**.

But e.g. checkpointing is an internal detail of Gramine that gives zero information to a software engineer who wants to figure out whether Gramine is able to run his/her application. Checkpointing is fully transparent to the application (well, it may be buggy, but it's a different story).
</blockquote></details>

Gotcha, thanks for the explanation!
___
*[`Documentation/misc/features.md` line 1456 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1WW3V7BZBhbXP17dJ:-NPVCzN82lcnD5ZvLC8N:b-k614gu) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1456)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? That I need to add the info about Gramine backends in the intro? Ok, done.
</blockquote></details>

Yes, thanks!
___
*[`Documentation/misc/features.md` line 1664 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1bMSY87gvq8mJ4PXT:-NPVDhEp84-5v8q_bnHz:bf9qydw) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1664)):*
> We lose some "shades of implemented" by using this rigid terminology

;)
___
*[`Documentation/misc/features.md` line 1836 at r3](https://reviewable.io/reviews/gramineproject/gramine/1194#-NP1fRISA-sUhmCCrT5K:-NPVFP953h-wkH9jtAYU:b-hi8jm4) ([raw file](https://github.com/gramineproject/gramine/blob/3af1c91cc88b935527530b2ff07e46ef3a594ebc/Documentation/misc/features.md#L1836)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the exact question? I think core dump files are never used by normal users (only by developers during debug), and that's what I tried to convey in my phrasing.
</blockquote></details>

OK, thanks! I'm fine w/ it, resolving.


<!-- Sent from Reviewable.io -->

2023-03-02 15:26 UTC, woju requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 6 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXuOXY-f2sWr_dq1uL:-NPXuOXY-f2sWr_dq1uM:b-ceb87g) (no related file):*
Please add `python3-recommonmark` to `Build-Depends` and `BuildRequires` in `debian/control` and `gramine.spec`, respectively, this will fix CI for packaging pipelines.

Also, I thought about it a bit and I prefer that addition of recommonmark was a separate commit before the actual `features.md`, because if someone were to rewrite this to reST after all, then this separate commit would be easy to revert.

___
___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NPXn9cY0Z-mchQBRFg6:bkuu4w2) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
> ```reStructuredText
>    :maxdepth: 1
> 
>    devel/features
> ```

Are you sure this is for `devel/` ("Developing Gramine")? I thought this document was for prospective user, evaluating if his/her app will run. If I got to choose, I'd place it just in `Documentation/` (sphinx toplevel).


<!-- Sent from Reviewable.io -->

2023-03-07 12:53 UTC, dimakuv reviewed
@kailun-qin I did it already? Maybe it was an old comment...

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194#-:-NPw2e2z61qbW294NQY5:b-8l52sz)* status: 6 of 9 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin, @llly, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXuOXY-f2sWr_dq1uL:-NPw7M2a1NL2avR4djU0:bwktjm5) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please add `python3-recommonmark` to `Build-Depends` and `BuildRequires` in `debian/control` and `gramine.spec`, respectively, this will fix CI for packaging pipelines.

Also, I thought about it a bit and I prefer that addition of recommonmark was a separate commit before the actual `features.md`, because if someone were to rewrite this to reST after all, then this separate commit would be easy to revert.
</blockquote></details>

Done both. For the second part of the comment, I had to rebase (to re-arrange into two commits).

___
___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NPw3-3Y3Vv2LKf-7NBL:b-rbi1jl) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
> I thought this document was for prospective user, evaluating if his/her app will run.

This document is for very technical users (it's practically impossible for a casual user to figure out whether Gramine will support some app). So it feels strange to put it as top-level document.

But maybe we should add a new section in ToC? I don't know. I will leave the doc as is for now, there is anyway a parallel effort to rearrange the docs.
___
*[`Documentation/devel/features.md` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVFx4DCGBxI2f1CbgJ:-NPw3dtv4Lqli86oT0-1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

are
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 1464 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVLYrwDugIJNCaHDwR:-NPw4AFJEoFJx9gSjBkU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L1464)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Add a link to the tracking issue?
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 2526 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVMso4-w1858abg4cV:-NPw4Hai0I4BeA-fQYmW:b-18lop3) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L2526)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

construction?
</blockquote></details>

Not relevant anymore, I decided to remove these emojis/symbols all together, they are just complicating reading.
___
*[`Documentation/devel/features.md` line 3155 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVSJLyBJQX_bzk-EUq:-NPw4WkG-h0UuQVbZenP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L3155)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should be`/dev/attestation/` (or more precisely `/dev/attestation/keys/`).
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 3224 at r4](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPVTfYe6uu315rLVip3:-NPw4asV1-jztZFzAIkD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f69b68b06bcd59e172a0fef831814092b67276ac/Documentation/devel/features.md#L3224)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I understand this is a living doc (w/ the last major update happened in Feb 2023). But we just removed this and it seemed useless.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 11:34 UTC, woju submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 5 unresolved discussions (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NRh87Tp1FjQyORdtEAG:bkewxgd) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I thought this document was for prospective user, evaluating if his/her app will run.

This document is for very technical users (it's practically impossible for a casual user to figure out whether Gramine will support some app). So it feels strange to put it as top-level document.

But maybe we should add a new section in ToC? I don't know. I will leave the doc as is for now, there is anyway a parallel effort to rearrange the docs.
</blockquote></details>

OK. Let's think about this during/after rearranging the docs.


<!-- Sent from Reviewable.io -->

2023-03-29 19:24 UTC, monavij reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 5 unresolved discussions (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NRioQeE8-jhKb_-w-pP:bymwgou) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK. Let's think about this during/after rearranging the docs.
</blockquote></details>

I think this doc does belong in "Developing Gramine" as its mainly useful for someone interested in details of Gramine internals. The list of system calls is potentially useful for some users, but we can probably add a little blurb on  that to some top level page pointing to this document. 


<!-- Sent from Reviewable.io -->

2023-03-30 02:19 UTC, kailun-qin reviewed
> Maybe it was an old comment...

Yes, it was an old comment.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194#-:-NRkIiwO4Nonb3TosMm8:bt4q27w)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`Documentation/devel/features.md` line 26 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRkHd8C1bZ3YTxT7S7Z:-NRkHd8C1bZ3YTxT7S7_:be87182) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L26)):*
> ```Markdown
> Gramine currently has two backends: direct execution on the host Linux OS (called `gramine-direct`)
> and execution inside an Intel SGX enclave (called `gramine-sgx`). If some feature has quirks and
> pecularities in some backend, we describe it explicitly. More backends are possible in the future.
> ```

peculiarities



_Code quote:_
```Markdown
pecularities
```


<!-- Sent from Reviewable.io -->

2023-03-31 08:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`Documentation/devel/features.md` line 26 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRkHd8C1bZ3YTxT7S7Z:-NRqj2_cEUgxLCoyFGVI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

peculiarities
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-01 23:09 UTC, mkow requested changes
> Reviewed 6 of 7 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @monavij, and @woju)

___
*[`-- commits` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhoo_1-NRSLVP2MQjG):*




_Suggestion:_
```
reStructuredText
```
___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhozWyCxnFWmz9didW):*
I think there's no point to say this in the one-liner, it's an implementation detail. I'd move it to the message body.



_Code quote:_
```
 (in Markdown)
```
___
*[`-- commits` line 13 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhp7283sScx-CATgIy):*
ditto



_Code quote:_
```
RestructedText
```
___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NRk-o9p8mW-uo_Wn5Qr:b9e0k82) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
<details><summary><i>Previously, monavij (Mona Vij) wrote…</i></summary><blockquote>

I think this doc does belong in "Developing Gramine" as its mainly useful for someone interested in details of Gramine internals. The list of system calls is potentially useful for some users, but we can probably add a little blurb on  that to some top level page pointing to this document. 
</blockquote></details>

+1 to placing it under `devel/`.

One thing though: it IMO shouldn't be the first on the list, there are many more important documents for users which are reading this section (e.g. "Building") nor it seems to logically make sense to be the first entry.
___
*[`Documentation/devel/features.md` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnIV-E6dr_v1Z0C9wE:-NRnIV-FDEEMclfxV5Pd:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1)):*
> ```Markdown
> <!-- Cannot render this doc in RestructedText as it has no support for nested inline markup. -->
> ```

ditto



_Code quote:_
```Markdown
RestructedText
```
___
*[`Documentation/devel/features.md` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnJav14hA7Ek2LUBJ0:-NRnJav14hA7Ek2LUBJ1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L5)):*
> ```Markdown
> # Gramine features
> 
> > ⚠ Highly technical document intended for software engineers with knowledge of OS kernels.
> ```





_Suggestion:_
```Markdown
This is a highly technical document
```
___
*[`Documentation/devel/features.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRobxLm1OHszUUPn6Vg:-NRobxLm1OHszUUPn6Vh:btq6sul) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L9)):*
> ```Markdown
> > ⛏ This is a living document. The last major update happened in **March 2023**.
> 
> Gramine strives to **support native, unmodified Linux applications** on any platform. The SGX
> ```

(I think this explains better what we're actually doing)



_Suggestion:_
```Markdown
Gramine strives to **run
```
___
*[`Documentation/devel/features.md` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRocFpj49xEAFq9JYsK:-NRocFpk0yVm6SfAeYFf:brqhjq2) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L14)):*
> Gramine **intercepts all application requests** to the host OS. Some of these requests are processed
entirely inside Gramine, and some are forwarded to the host OS.

I don't like this wording, it will make people think that forwarding things to the host is ok in Gramine. We aren't really forwarding things, we're implementing them based on the small API to the host which provides I/O operations. Sometimes this is close to how literal forwarding would look like, but it's always (I think) just implementing something using PAL API.

This is especially confusing because some SGX frameworks actually _do_ forward syscalls to the host with some light filtering, but that is a completely different design than Gramine.
___
*[`Documentation/devel/features.md` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRodqyP-0pj1fhAdWuS:-NRodqyP-0pj1fhAdWuT:bq1r56b) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L24)):*
> ```Markdown
> hardware-independent applications.
> 
> Gramine currently has two backends: direct execution on the host Linux OS (called `gramine-direct`)
> ```

This sounds very misleading to me - sounds like in this mode we're just forwarding all syscalls directly to the host.



_Code quote:_
```Markdown
direct execution on the host Linux OS
```
___
*[`Documentation/devel/features.md` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoeR4N9MAI5--BpGVK:-NRoeR4ODcRlwJaDSvJx:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L32)):*
> ```Markdown
> - **Linux features**: features can be (1) implemented, (2) partially implemented, or (3) not
>   implemented at all in Gramine. If the feature is partially implemented, then we also document the
>   parts that are implemented and the parts that are implemented. If the feature is not implemented
> ```





_Suggestion:_
```Markdown
parts that are implemented and the parts that are not implemented
```
___
*[`Documentation/devel/features.md` line 62 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRofQxhBXvGPVHBBnfR:-NRofQxhBXvGPVHBBnfS:bxi97kk) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L62)):*
> ```Markdown
> Similarly to Linux, Gramine provides two interfaces to user applications:
> 
> - **Linux kernel-to-userspace API**, consisting of two sub-interfaces:
> ```

Not userspace-to-kernel?



_Code quote:_
```Markdown
Linux kernel-to-userspace API
```
___
*[`Documentation/devel/features.md` line 64 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRofw9A1ase75VSR4XY:-NRofiyB1BPwzFEHfMcm:bbx1e30) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L64)):*
> ```Markdown
> - **Linux kernel-to-userspace API**, consisting of two sub-interfaces:
> 
>   - **Linux System Call Interface**: a set of system calls which allow applications to access system
> ```

This is actually ABI, not API. Maybe list instead interfaces and then standards below? This split between API and ABI here seems weird.
___
*[`Documentation/devel/features.md` line 81 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoiRQ0-HVtG0xbI4no:-NRoiRQ0-HVtG0xbI4np:b-f9k7cq) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L81)):*
> ```Markdown
> 
> - ☑ implemented (no serious limitations)
> - ☐ partially implemented (serious limitations or quirks)
> ```

I find this empty box meaning "partial support" very confusing, I've read this legend but still got troubles when reading the list, which is mostly ☑ and ☐ interleaved - easy to forget that this is a tri-state box and the empty one doesn't actually mean "not implemented".
Any other ideas how could we mark partial support? Maybe one of ± ▣ ◫ ? (with the o [...]

2023-04-02 02:50 UTC, mkow requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 53 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @monavij)

___
*[`Documentation/devel/features.md` line 2231 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRz5VI7BJK8pCc1qM0p:-NRz5VI7BJK8pCc1qM0q:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2231)):*
> ```Markdown
>   - ☐ `F_GETLK`: see notes above
> 
> - ☒ `flock()`: may be implemented in future
> ```





_Suggestion:_
```Markdown
in the future
```
___
*[`Documentation/devel/features.md` line 2256 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRz5fY_Emq0gcAzG2YS:-NRz5fY_Emq0gcAzG2YT:b-iyc0ze) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2256)):*
> ```Markdown
> 
> 1. Host OS's links: Gramine sees them as normal files. These links are currently always followed
>    during directory/file lookup.
> ```

Ditto, as above. This depends both on the host and the mount type, it sounds like here you silently assumed allowed_files mount with the host being Linux?
___
*[`Documentation/devel/features.md` line 2422 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRz7g171uWbJsqKGafL:-NRz7g171uWbJsqKGafM:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2422)):*
> ```Markdown
> <details><summary>Note on domain names configuration</summary>
> 
> - To use name-resolving Berkeley socket APIs like `gethostbyname()`, `gethostbyaddr()`,
> ```





_Suggestion:_
```Markdown
To use libc name-resolving Berkeley socket APIs like
```
___
*[`Documentation/devel/features.md` line 2530 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzkCXP8zYxRKlI-ARd:-NRzkCXQ7X6j3uGohgV_:b-1ywc28) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2530)):*
> ```Markdown
> 
> - There is an effort to make named UDSes visible on the Gramine filesystem, see
>   https://github.com/gramineproject/gramine/pull/1021.
> ```

not clickable
___
*[`Documentation/devel/features.md` line 2666 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzmQb52AcmDRkJbEVg:-NRzmQb52AcmDRkJbEVh:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2666)):*
> ```Markdown
> 
> POSIX semaphores are technically not a Linux kernel API. Instead, they are implemented on top of the
> POSIX shared memory functionality of Linux (i.e., via `/dev/shm` pseudo-filesystem).
> ```





_Suggestion:_
```Markdown
POSIX shared memory functionality of Linux by libc
```
___
*[`Documentation/devel/features.md` line 3036 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzoGH6938MdciimVIZ:-NRzoGH6938MdciimVI_:bvkglqr) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L3036)):*
> ```Markdown
> </details><br />
> 
> ### Advanced (unimplemented) features
> ```

(some of them aren't really advanced, just infeasible to implement in Gramine)



_Suggestion:_
```Markdown
### Advanced/infeasible, unimplemented features
```
___
*[`Documentation/devel/features.md` line 3182 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzpxoW22q0D7NtgOFs:-NRzpxoW22q0D7NtgOFt:bigmt38) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L3182)):*
> ```Markdown
> > ⚠ Below description assumes x86-64 architecture.
> 
> Gramine implements the system-call entry point (analogous to the `SYSCALL` x86 instruction).
> ```

I don't understand this reference - how our entrypoint code can be similar to _an x86 instruction_?



_Code quote:_
```Markdown
system-call entry point (analogous to the `SYSCALL` x86 instruction)
```
___
*[`Documentation/devel/features.md` line 3217 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzrMvb-3VNLrmQFrJg:-NRzrMvcDnla4iFt6GNL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L3217)):*
> ```Markdown
> ## Notes on application loading
> 
> Gramine can execute only ELF binaries (executables and libraries) and scripts (aka shebangs). Other
> ```

ditto



_Code quote:_
```Markdown
scripts (aka shebangs)
```
___
*[`Documentation/devel/features.md` line 3220 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRzrXxR1OEPUNDTcpmN:-NRzrXxR1OEPUNDTcpmO:b-m4e0v4) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L3220)):*
> ```Markdown
> formats are not supported.
> 
> Gramine does *not* perform any dynamic linking during binary loading. Instead it just executes load
> ```

What's the point of this note? Linux does exactly the same.



_Code quote:_
```Markdown
Gramine does *not* perform any dynamic linking during binary loading.
```


<!-- Sent from Reviewable.io -->

2023-04-03 14:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 7 of 9 files reviewed, 53 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`-- commits` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhoo_1-NRSLVP2MQjG):*
Will do during final rebase
___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhozWyCxnFWmz9didW):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think there's no point to say this in the one-liner, it's an implementation detail. I'd move it to the message body.
</blockquote></details>

Will do during final rebase
___
*[`-- commits` line 13 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhp7283sScx-CATgIy):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Will do during final rebase
___
*[`Documentation/index.rst` line 95 at r5](https://reviewable.io/reviews/gramineproject/gramine/1194#-NPXn9cY0Z-mchQBRFg5:-NS6KzNLDUGHmOT1t2A3:b-sr9x62) ([raw file](https://github.com/gramineproject/gramine/blob/46ab452dd41df39fae2915176a57469d96fd9ebc/Documentation/index.rst#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to placing it under `devel/`.

One thing though: it IMO shouldn't be the first on the list, there are many more important documents for users which are reading this section (e.g. "Building") nor it seems to logically make sense to be the first entry.
</blockquote></details>

Done. Didn't know where to put exactly, so it seemed logical to me to move to the very end.
___
*[`Documentation/devel/features.md` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnIV-E6dr_v1Z0C9wE:-NS6LGve7gsgqbi6GyaN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 5 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnJav14hA7Ek2LUBJ0:-NS6LM6k1XuTRo5Q7GUA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L5)):*
> ```Markdown
> # Gramine features
> 
> > ⚠ Highly technical document intended for software engineers with knowledge of OS kernels.
> ```

Done.
___
*[`Documentation/devel/features.md` line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRobxLm1OHszUUPn6Vg:-NS6LOnJ12lnpbKQADt1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(I think this explains better what we're actually doing)
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRocFpj49xEAFq9JYsK:-NS6Lki1218mdZinkqz8:brosvtd) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Gramine **intercepts all application requests** to the host OS. Some of these requests are processed
entirely inside Gramine, and some are forwarded to the host OS.

I don't like this wording, it will make people think that forwarding things to the host is ok in Gramine. We aren't really forwarding things, we're implementing them based on the small API to the host which provides I/O operations. Sometimes this is close to how literal forwarding would look like, but it's always (I think) just implementing something using PAL API.

This is especially confusing because some SGX frameworks actually _do_ forward syscalls to the host with some light filtering, but that is a completely different design than Gramine.
</blockquote></details>

Done. What about the new wording, with a fancy `funnel through`?
___
*[`Documentation/devel/features.md` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRodqyP-0pj1fhAdWuS:-NS6M-HNEjqKmcF0bjx_:b9hq92c) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This sounds very misleading to me - sounds like in this mode we're just forwarding all syscalls directly to the host.
</blockquote></details>

Done. Couldn't come up with anything smart, so just deleted the word `direct`
___
*[`Documentation/devel/features.md` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoeR4N9MAI5--BpGVK:-NS6MBvq01es7pLDT72_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L32)):*
> ```Markdown
> - **Linux features**: features can be (1) implemented, (2) partially implemented, or (3) not
>   implemented at all in Gramine. If the feature is partially implemented, then we also document the
>   parts that are implemented and the parts that are implemented. If the feature is not implemented
> ```

Done.
___
*[`Documentation/devel/features.md` line 62 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRofQxhBXvGPVHBBnfR:-NS6MNwd264A-xArzPY4:boyr2vh) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not userspace-to-kernel?
</blockquote></details>

Done. Lol, nobody noticed this blooper till now
___
*[`Documentation/devel/features.md` line 64 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRofw9A1ase75VSR4XY:-NS6MdCB9Ptxi7pc7Oz-:bs2cck4) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is actually ABI, not API. Maybe list instead interfaces and then standards below? This split between API and ABI here seems weird.
</blockquote></details>

Done. I didn't intend to compare API vs ABI, that was just bad phrasing
___
*[`Documentation/devel/features.md` line 81 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoiRQ0-HVtG0xbI4no:-NS6N4S28B_1ao5SVJK_:b-tb38ak) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I find this empty box meaning "partial support" very confusing, I've read this legend but still got troubles when reading the list, which is mostly ☑ and ☐ interleaved - easy to forget that this is a tri-state box and the empty one doesn't actually mean "not implemented".
Any other ideas how could we mark partial support? Maybe one of ± ▣ ◫ ? (with the original ones potentially permuted)
</blockquote></details>

Done. I like ▣.  
___
*[`Documentation/devel/features.md` line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRogj7SBRrPveAscrp5:-NS6NPYG2WGEoNkpbMyo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L88)):*
<details><summar [...]

2023-04-04 13:17 UTC, mkow requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/devel/features.md` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnIV-E6dr_v1Z0C9wE:-NSBE49r-94kbLAtTHoe:b-yyjuqf) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed one more typo, look at the suggested diff in a discussion above :)
___
*[`Documentation/devel/features.md` line 14 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRocFpj49xEAFq9JYsK:-NSBERqm1cKPndK87A9A:b-sp1p9f) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. What about the new wording, with a fancy `funnel through`?
</blockquote></details>

I like the new phrasing :)
___
*[`Documentation/devel/features.md` line 64 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRofw9A1ase75VSR4XY:-NSBEn95EzXwxXuYtjQF:b-lshikb) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I didn't intend to compare API vs ABI, that was just bad phrasing
</blockquote></details>

Aaah, I see, now I understand this split.
___
*[`Documentation/devel/features.md` line 234 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoke7b9JVyphC2E-Hk:-NSBHUY-4FCt7lk8dFGW:b-k174h0) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L234)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh my. Do you **really** want this? I can do it, but it feels like a lot of manual work for small gains.
</blockquote></details>

Why manual? Just find & replace on the whole lines?
___
*[`Documentation/devel/features.md` line 1452 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoxU6_8j-D60K6AFWX:-NSBISvQDEnyG1Z8aQk8:bvgwg3k) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1452)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What should be the correct way? I'm not sure how to add Markdown links to sections in a relative RST file...
</blockquote></details>

The current way is really problematic, e.g. this document viewed at `latest` will now still link to `stable`. And rendered locally it links remotely. And many more issues...

Won't changing this to a relative link work?
___
*[`Documentation/devel/features.md` line 1456 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoxsL65-FRBdQIA50w:-NSBIsvNCCIDfIHFM3wo:b-lqbuhv) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1456)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is in the context of Processes (I have a similar note on `clone()` in the section about Threads). But I see that it is misleading... How can I make it obvious?
</blockquote></details>

Maybe just leave `clone()`?
___
*[`Documentation/devel/features.md` line 1506 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRy_JtI4p0NXaVJR53D:-NSBJR_V2X0wlP_VqTVR:b-u38rh6) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1506)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, libc allocates the stacks (other than the main thread's stack) and passes them to e.g. `clone()`, so Gramine does not **manage the lifetime of the child-threads' stacks**.

But what I meant is that Gramine is fully aware of stacks and signal stacks. How can I reformulate?
</blockquote></details>

But it's not aware of them, the only thing we know is what value to put into `RSP` when calling signal handlers? So, it's IMO very misleading when you say "Gramine implements [...] stack and signal (alternate) stack".
I'd just replace this point with "saved information about signal (alternate) stack".
___
*[`Documentation/devel/features.md` line 1812 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRylgdQDGBjH9hDVgvd:-NSBKsHk9rXafoMlrV6z:b2ni78k) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1812)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Pretty cool, they changed the whole website in February this year.
</blockquote></details>

lol
___
*[`Documentation/devel/features.md` line 1915 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRyvpwOBk2LcXxH_Xiw:-NSBL6KZ7nTlgd-HVlXo:bktzis5) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1915)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Does this read better?
</blockquote></details>

Yup, now it's good.
___
*[`Documentation/devel/features.md` line 1928 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRywhW_8o51lbyEj4y2:-NSBMCkiA7WlPvVmSAQw:bctdrse) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1928)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

 I mean these:
- https://github.com/gramineproject/gramine/blob/5154a5957c15bea1f84eef730fbf75829f37001b/libos/src/ipc/libos_ipc_child.c#L43
- https://github.com/gramineproject/gramine/blob/4f8d7446d25711a4983cdf6695f44e4c8a8e01d9/libos/src/bookkeep/libos_process.c#L116

This is simply for `siginfo_t::si_uid`, see https://man7.org/linux/man-pages/man2/sigaction.2.html. How should I rephrase?
</blockquote></details>

Hmm, so it's not used for injecting `SIGCHLD`, it's just passed to the user app receiving the signal as additional chunk of information? Or am I missing something? The current wording ("usages of user/group IDs in Gramine: [...] injecting SIGCHLD on terminated child processes" sounds like this user ID was somehow used to deliver the signal itself.
___
*[`Documentation/devel/features.md` line 2256 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRz5fY_Emq0gcAzG2YS:-NSBOU_6Ai3a7Ycbh3Uv:b4ndcwb) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L2256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I mention Linux now, but I don't get your comment about `allowed_files` -- trusted files are also just followed. How could I rephrase?
</blockquote></details>

I think it's good now, resolving.
___
*[`Documentation/devel/features.md` line 1979 at r8](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSBNKIBBCIziEsRFy2Q:-NSBNKIBBCIziEsRFy2R:beps79q) ([raw file](https://github.com/gramineproject/gramine/blob/dd4376af2e0c4eceedfc5951ab271da7266e241f/Documentation/devel/features. [...]

2023-04-05 12:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRnIV-E6dr_v1Z0C9wE:-NSGB0zK-bp-nAnCGjs-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You missed one more typo, look at the suggested diff in a discussion above :)
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 234 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoke7b9JVyphC2E-Hk:-NSGQMaGEGp3VR2sEfeT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L234)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why manual? Just find & replace on the whole lines?
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 1452 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoxU6_8j-D60K6AFWX:-NSGQSXL0b6ye52vIGxs:boq7tfw) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1452)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The current way is really problematic, e.g. this document viewed at `latest` will now still link to `stable`. And rendered locally it links remotely. And many more issues...

Won't changing this to a relative link work?
</blockquote></details>

Now that I dealt with your other comments, let me try this...
___
*[`Documentation/devel/features.md` line 1456 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoxsL65-FRBdQIA50w:-NSGCT937-lmuOt3kr6B:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1456)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just leave `clone()`?
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 1506 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRy_JtI4p0NXaVJR53D:-NSGCjrd1ZFl20c-_cSo:b-y22sch) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1506)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it's not aware of them, the only thing we know is what value to put into `RSP` when calling signal handlers? So, it's IMO very misleading when you say "Gramine implements [...] stack and signal (alternate) stack".
I'd just replace this point with "saved information about signal (alternate) stack".
</blockquote></details>

Done. Not sure why you had `saved` word in your proposal, so just removed it.
___
*[`Documentation/devel/features.md` line 1928 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRywhW_8o51lbyEj4y2:-NSGDF-f3AltGaHI3oIS:b-yeiara) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1928)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, so it's not used for injecting `SIGCHLD`, it's just passed to the user app receiving the signal as additional chunk of information? Or am I missing something? The current wording ("usages of user/group IDs in Gramine: [...] injecting SIGCHLD on terminated child processes" sounds like this user ID was somehow used to deliver the signal itself.
</blockquote></details>

Done. Your understanding is correct.
___
*[`Documentation/devel/features.md` line 1979 at r8](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSBNKIBBCIziEsRFy2Q:-NSGDYC18ch7xiH70FhQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dd4376af2e0c4eceedfc5951ab271da7266e241f/Documentation/devel/features.md#L1979)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't say secure/insecure, security is always relative to a threat model/app design. Allowed mounts may be secure if the app does the encryption by itself or the contents there doesn't matter for security. Same for trusted files, they may be insecure if you store some secrets there :)
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 1979 at r8](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSBNZGrC1msVi-R7v6w:-NSGDYlGCG_yezg6umcZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dd4376af2e0c4eceedfc5951ab271da7266e241f/Documentation/devel/features.md#L1979)):*
> ```Markdown
> In case of SGX backend, passthrough mounts must be of one of two kinds:
> - containing allowed files (insecure, not protected in any way, only for testing purposes),
> - containing trusted files (secure, cryptographically hashed).
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 12:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 1452 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRoxU6_8j-D60K6AFWX:-NSGSVb1E5z66qTXrcim:bfvu0mt) ([raw file](https://github.com/gramineproject/gramine/blob/1caa64b97aacd159c028a26a39522ced607c8096/Documentation/devel/features.md#L1452)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that I dealt with your other comments, let me try this...
</blockquote></details>

Done. Seems to be working.


<!-- Sent from Reviewable.io -->

2023-04-05 13:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 1988 at r11](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSGel2UAHovhWvxfh5V:-NSGel2UAHovhWvxfh5W:b-tvmfrd) ([raw file](https://github.com/gramineproject/gramine/blob/82c8100e514159de0afce464a6277a4b3b659c53/Documentation/devel/features.md#L1988)):*
> ```Markdown
> All files potentially used by the application must be specified in the manifest file. Instead of
> single files, whole directories can be specified. Refer to the [manifest documentation for more
> details](../manifest-syntax.html#manifest-syntax).
> ```

Relative linking is super-brittle in Recommonmark (that we use as a Sphinx plugin in our docs), see this: https://github.com/readthedocs/recommonmark/issues/130#issuecomment-573695079

That's why I added a dummy anchor here, instead of just the `manifest-syntax.html` target.


<!-- Sent from Reviewable.io -->

2023-04-05 14:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/devel/features.md` line 1506 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRy_JtI4p0NXaVJR53D:-NSGpty90cDrRUttTVev:bvw2c2v) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1506)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Not sure why you had `saved` word in your proposal, so just removed it.
</blockquote></details>

I wanted to stress that it's just one value saved once and that's all, i.e. we aren't doing anything active with these stacks. But that's not that important with the new wording.
___
*[`Documentation/devel/features.md` line 1928 at r7](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRywhW_8o51lbyEj4y2:-NSGqTsQ4vPFTRN4totc:b-4c6sis) ([raw file](https://github.com/gramineproject/gramine/blob/926bee41b28e703c2c450cb173668bf14670bf85/Documentation/devel/features.md#L1928)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Your understanding is correct.
</blockquote></details>

Now it's clear to me what this point means, thanks!
___
*[`Documentation/devel/features.md` line 104 at r11](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSGnlzgCBEDWQYNiTTU:-NSGnlzgCBEDWQYNiTTV:b-926irt) ([raw file](https://github.com/gramineproject/gramine/blob/82c8100e514159de0afce464a6277a4b3b659c53/Documentation/devel/features.md#L104)):*
> ```Markdown
> 
> - ☑ `read()`
>   <sup>[9.1](#file-system-operations)</sup>
> ```

Hmm, I don't like these sub-numbers, it's rather hard to read because these dots are pretty small when rendered. Maybe just use consecutive numbers?
What was the idea behind using them? To group similar issues together?



_Code quote:_
```Markdown
9.1
```


<!-- Sent from Reviewable.io -->

2023-04-06 06:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 104 at r11](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSGnlzgCBEDWQYNiTTU:-NSKEHlL88031-rCVJGf:b-qkfpuv) ([raw file](https://github.com/gramineproject/gramine/blob/82c8100e514159de0afce464a6277a4b3b659c53/Documentation/devel/features.md#L104)):*
> What was the idea behind using them? To group similar issues together?

Yes. Because e.g. `9.1`, `9.2`, etc are all subsections of one section "File Systems" (see the sections on the left pane in the rendered doc: https://gramine.readthedocs.io/en/dimakuv-add-gramine-features-doc/devel/features.html).

I could use consecutive numbers, but then it won't map nicely to Sections - Subsections in the document. Well, there are already some exceptions in the current mapping (e.g. `Attestation` section is marked consequtively even though it is located under `Gramine-specific features`). So whatever, I wouldn't mind changing `9.1` to `9`, `9.2` to `10`, etc, and shifting all other numbers too.

Alternatively, if the problem is in the dot only, I can suggest the following alternatives:
- `9-1`, `9-2`, etc
- `9(1)`, `9(2)`, etc


<!-- Sent from Reviewable.io -->

2023-04-06 12:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/devel/features.md` line 104 at r11](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSGnlzgCBEDWQYNiTTU:-NSLS4Ox1SRymEGpbLhz:b7ciyji) ([raw file](https://github.com/gramineproject/gramine/blob/82c8100e514159de0afce464a6277a4b3b659c53/Documentation/devel/features.md#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> What was the idea behind using them? To group similar issues together?

Yes. Because e.g. `9.1`, `9.2`, etc are all subsections of one section "File Systems" (see the sections on the left pane in the rendered doc: https://gramine.readthedocs.io/en/dimakuv-add-gramine-features-doc/devel/features.html).

I could use consecutive numbers, but then it won't map nicely to Sections - Subsections in the document. Well, there are already some exceptions in the current mapping (e.g. `Attestation` section is marked consequtively even though it is located under `Gramine-specific features`). So whatever, I wouldn't mind changing `9.1` to `9`, `9.2` to `10`, etc, and shifting all other numbers too.

Alternatively, if the problem is in the dot only, I can suggest the following alternatives:
- `9-1`, `9-2`, etc
- `9(1)`, `9(2)`, etc
</blockquote></details>

Hmm, maybe `9a`, `9b`, ...? That should be readable.


<!-- Sent from Reviewable.io -->

2023-04-06 14:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 8 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/features.md` line 104 at r11](https://reviewable.io/reviews/gramineproject/gramine/1194#-NSGnlzgCBEDWQYNiTTU:-NSM3cFeACQJbK5jnU0e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82c8100e514159de0afce464a6277a4b3b659c53/Documentation/devel/features.md#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, maybe `9a`, `9b`, ...? That should be readable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 15:03 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-04-11 07:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194)* status: 5 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`-- commits` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhoo_1-NRSLVP2MQjG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhozWyCxnFWmz9didW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 13 at r6](https://reviewable.io/reviews/gramineproject/gramine/1194#-NRhp7283sScx-CATgIy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-11 14:00 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1194#-:-NSkbT0g0q_HMv7DfO9u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-11 14:06 UTC, merged