Rewrite SGX signing in cryptography.io
gramineproject/gramine pull request #1197
Opened 2023-02-22 12:02 UTC by woju

## How to test this PR? 

For unencrypted keys, CI is OK. If you want to test encrypted keys, generate one manually (`gramine-sgx-gen-private-key` can't do that) and test also manually.

2023-02-22 13:16 UTC, woju commented
*[`python/graminelibos/sgx_sign.py` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOt-OmjDFZrPhcD9Stl:-NOt-OmjDFZrPhcD9Stm:b-mrsln2) ([raw file](https://github.com/gramineproject/gramine/blob/5730d09970f4881a24a7e60cc73d45e26ba4344b/python/graminelibos/sgx_sign.py#L585)):*
> ```Python
>         sys.exit(1)
> 
>     signature = private_key.sign(data, padding.PKCS1v15(), hashes.SHA256())
> ```

@mkow @dimakuv: `padding.PKCS1v15` is documented as "not constant time": https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.padding.PKCS1v15. Is this a problem? I think not, because 1) signing machine is assumed secure in SGX threat model, 2) the length is always the same (SHA256), but please someone better at crypto than me to check this.


<!-- Sent from Reviewable.io -->

2023-02-23 04:40 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[`python/graminelibos/sgx_sign.py` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOt-OmjDFZrPhcD9Stl:-NOwUu6L-z-dCUSbtAeA:b5xspvc) ([raw file](https://github.com/gramineproject/gramine/blob/5730d09970f4881a24a7e60cc73d45e26ba4344b/python/graminelibos/sgx_sign.py#L585)):*
> 1) signing machine is assumed secure in SGX threat model

Yes.

> 2) the length is always the same (SHA256)

The length of what? And how it's immune from the (original) problem?

Anyway, IMO it's not a problem.
___
*[`python/graminelibos/sgx_sign.py` line 607 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOwYTk248Xpj7lOrSyo:-NOwYTk248Xpj7lOrSyp:bcx73pa) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L607)):*
> ```Python
> 
> def sign_with_rsa_key(data, private_key):
>     """Signs *data* using *key*.
> ```

private_key



_Code quote:_
```Python
key
```


<!-- Sent from Reviewable.io -->

2023-02-23 11:51 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy0Z3R0GtbJmKO4I3L:-NOy0Z3S0u4N8x57OayL:bhpgb7) (no related file):*
Shouldn't there be a corresponding PR in GSC repo, that would:
- Remove https://github.com/gramineproject/gsc/blob/master/sign.sh
- Remove `passphrase` arg from GSC itself: https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/gsc.py#L504
- Fix around here: https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/gsc.py#L363
- Fix around here: https://github.com/gramineproject/gsc/blob/b7f0576219321c1b7d94b29661274419b009fc49/templates/Dockerfile.common.sign.template#L8

___
___
*[`python/graminelibos/sgx_sign.py` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOt-OmjDFZrPhcD9Stl:-NOy60eG6-P46Y9Y-b_Y:b-i4r33x) ([raw file](https://github.com/gramineproject/gramine/blob/5730d09970f4881a24a7e60cc73d45e26ba4344b/python/graminelibos/sgx_sign.py#L585)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> 1) signing machine is assumed secure in SGX threat model

Yes.

> 2) the length is always the same (SHA256)

The length of what? And how it's immune from the (original) problem?

Anyway, IMO it's not a problem.
</blockquote></details>

1 -- yes.
2 -- I din't understand the problem. SHA256 has the same length, yes, but how is this relevant?

Anyway, looks good to me.
___
*[`python/graminelibos/sgx_sign.py` line 555 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy4JQ5Ak6BLdHNdVDj:-NOy4JQ5Ak6BLdHNdVDk:b-p0jlg3) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L555)):*
> ```Python
>     default=os.fspath(SGX_RSA_KEY_PATH),
>     help='specify signing key (.pem) file')
> @click.option('--passphrase', '--password', '-p', metavar='PASSPHRASE',
> ```

These two options are for compatibility with GSC (which uses `--passphrase`)?
___
*[`python/graminelibos/sgx_sign.py` line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy5qfk8lKNhvRmdwuP:-NOy5qfl92r35R1R21Z0:b8uv8ib) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L584)):*
> ```Python
> 
> 
> def sign_with_local_key(data, key, passphrase=None):
> ```

I'm confused. Why do we need this one? How is it different from `sgx_with_rsa_key()`?


<!-- Sent from Reviewable.io -->

2023-02-23 18:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy0Z3R0GtbJmKO4I3L:-NOyHB6N5rJcZNnETJDM:b-pif4n) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't there be a corresponding PR in GSC repo, that would:
- Remove https://github.com/gramineproject/gsc/blob/master/sign.sh
- Remove `passphrase` arg from GSC itself: https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/gsc.py#L504
- Fix around here: https://github.com/gramineproject/gsc/blob/a60a4991d7351c1b7489444c694638ca9cc68e39/gsc.py#L363
- Fix around here: https://github.com/gramineproject/gsc/blob/b7f0576219321c1b7d94b29661274419b009fc49/templates/Dockerfile.common.sign.template#L8
</blockquote></details>

Yes, there should be, and it's part of a longer discussion about signing templates in gsc. Specifically, this is an attempt to make gsc working with signing plugins without regressing on features (here, `--passphrase`). I've commented in gramineproject/gsc#112 about this.

___
___
*[`python/graminelibos/sgx_sign.py` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOt-OmjDFZrPhcD9Stl:-NOyHrit4XjPKiq5KoxE:b-dx6xv4) ([raw file](https://github.com/gramineproject/gramine/blob/5730d09970f4881a24a7e60cc73d45e26ba4344b/python/graminelibos/sgx_sign.py#L585)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1 -- yes.
2 -- I din't understand the problem. SHA256 has the same length, yes, but how is this relevant?

Anyway, looks good to me.
</blockquote></details>

2) The length of SHA256 hash. Because padding depends on length of the data, so if the length is the same, then padding is the same and hopefully its manipulation takes the same time.

If it's good, then OK.
___
*[`python/graminelibos/sgx_sign.py` line 555 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy4JQ5Ak6BLdHNdVDj:-NOyHU5f3HYtwcg3vLMH:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L555)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two options are for compatibility with GSC (which uses `--passphrase`)?
</blockquote></details>

Yes.
___
*[`python/graminelibos/sgx_sign.py` line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy5qfk8lKNhvRmdwuP:-NOyHZnJ8jmrh0OBDAo_:brpzxiy) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L584)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm confused. Why do we need this one? How is it different from `sgx_with_rsa_key()`?
</blockquote></details>

This function accepts filename, `sign_with_rsa_key` accepts an object from `cryptography` module (same as `generate_private_key` return cryptography object vs `generate_private_key_pem` return PEM data ready to be written to a file). `sign_with_local_key` was exported in `__init__.py` so it should remain as is, though we (in gramine repo) don't need it and the name also should be unchanged. Otherwise I'd call it `sign_with_rsa_key_pem` or so.

Technically it wasn't documented, because autodoc doesn't work with `sgx_sign.py` (and some others) because of the import of the offsets, so we didn't publish the docs for it. So if you'll argue we can change it, I can do it, but I don't see a need for it. I can also add a "not to be confused with ..." note to docstrings.
___
*[`python/graminelibos/sgx_sign.py` line 607 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOwYTk248Xpj7lOrSyo:-NOzavevABfRgR89U-yM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L607)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

private_key
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 13:50 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NPI6meE9RlxjzPh27si:-NPI6meE9RlxjzPh27sj:b-k0518p) (no related file):*
WRT CI failure about `--passphrase` vs `--password` on 18.04: `click` 6.7 as shipped in `bionic` hasn't fixed this bug: pallets/click#793 https://github.com/pallets/click/commit/f15f425bc11a69a4dc856d43d25e223dcc15f0f2.

So I see two options: either I add explicit option name, or we drop `bionic` now and don't care anymore.

___


<!-- Sent from Reviewable.io -->

2023-05-17 11:26 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy0Z3R0GtbJmKO4I3L:-NVdQ92e4EgfylPPWiD6:bxkf4we) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, there should be, and it's part of a longer discussion about signing templates in gsc. Specifically, this is an attempt to make gsc working with signing plugins without regressing on features (here, `--passphrase`). I've commented in gramineproject/gsc#112 about this.
</blockquote></details>

I created an issue for this: https://github.com/gramineproject/gsc/issues/148

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NPI6meE9RlxjzPh27si:-NVdP0Mv4f04D8CvpHFR:bmkgb3x) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

WRT CI failure about `--passphrase` vs `--password` on 18.04: `click` 6.7 as shipped in `bionic` hasn't fixed this bug: pallets/click#793 https://github.com/pallets/click/commit/f15f425bc11a69a4dc856d43d25e223dcc15f0f2.

So I see two options: either I add explicit option name, or we drop `bionic` now and don't care anymore.
</blockquote></details>

We dropped bionic, so we don't care anymore.

___
___
*[`python/graminelibos/sgx_sign.py` line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy5qfk8lKNhvRmdwuP:-NVdRIM_7G8NmJyfGzb3:b-t89u4r) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L584)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This function accepts filename, `sign_with_rsa_key` accepts an object from `cryptography` module (same as `generate_private_key` return cryptography object vs `generate_private_key_pem` return PEM data ready to be written to a file). `sign_with_local_key` was exported in `__init__.py` so it should remain as is, though we (in gramine repo) don't need it and the name also should be unchanged. Otherwise I'd call it `sign_with_rsa_key_pem` or so.

Technically it wasn't documented, because autodoc doesn't work with `sgx_sign.py` (and some others) because of the import of the offsets, so we didn't publish the docs for it. So if you'll argue we can change it, I can do it, but I don't see a need for it. I can also add a "not to be confused with ..." note to docstrings.
</blockquote></details>

Could you a comment about this? That this name is historic and kept for compatibility, and that it differs from `sgx_with_rsa_key()` in the `key` argument type.
___
*[`python/graminelibos/sgx_sign.py` line 579 at r4](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVdRofZDTDW3ZCzTLQ7:-NVdRofZDTDW3ZCzTLQ8:b7qvp0p) ([raw file](https://github.com/gramineproject/gramine/blob/01fdc960070bfa41c5c3ff28640956054fa0daeb/python/graminelibos/sgx_sign.py#L579)):*
> ```Python
>     if exponent != SGX_RSA_PUBLIC_EXPONENT:
>         raise InvalidRSAKeyError(
>             f'invalid RSA key: expected exponent {SGX_RSA_PUBLIC_EXPONENT}, got {exponent}')
> ```

We typically start with a capital letter
___
*[`python/graminelibos/sgx_sign.py` line 611 at r4](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVdS12u7XPvKTYVeV8z:-NVdS12u7XPvKTYVeV9-:b2so3eg) ([raw file](https://github.com/gramineproject/gramine/blob/01fdc960070bfa41c5c3ff28640956054fa0daeb/python/graminelibos/sgx_sign.py#L611)):*
> ```Python
>     Function used to generate an RSA signature over provided data using a 3072-bit private key with
>     the public exponent of 3 (hard Intel SGX requirement on the key size and the exponent).
>     Suitable to be used as a callback to :py:func:`graminelibos.Sigstruct.sign()`.
> ```

Isn't it a bit weird that we have two funcs with different arguments that are suitable as a callback for `graminelibos.Sigstruct.sign()`:
- old `sign_with_local_key()` accepts `key` which is the path to a private key file
- new `sign_with_rsa_key()` accepts `private_key` which is the actual private key object

Or in Python this is considered normal?


<!-- Sent from Reviewable.io -->

2023-05-18 10:37 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @kailun-qin)

___
*[`python/graminelibos/sgx_sign.py` line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOy5qfk8lKNhvRmdwuP:-NViNB2T4j8xBzcU8H5T:b-4nijdw) ([raw file](https://github.com/gramineproject/gramine/blob/7a06af87ec1052ff15dd8cb2c14faf7a47e53f3d/python/graminelibos/sgx_sign.py#L584)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you a comment about this? That this name is historic and kept for compatibility, and that it differs from `sgx_with_rsa_key()` in the `key` argument type.
</blockquote></details>

Done.

I've also added "see also" for those functions. Here's how that would render, if it would render:

![image.png](https://files.reviewableusercontent.io/images/reviewable/1550337/TRWGA6A7InkhYZXGXCe7dOni/image.png)
___
*[`python/graminelibos/sgx_sign.py` line 579 at r4](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVdRofZDTDW3ZCzTLQ7:-NViQS2h9egABpB76ZND:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01fdc960070bfa41c5c3ff28640956054fa0daeb/python/graminelibos/sgx_sign.py#L579)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We typically start with a capital letter
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 611 at r4](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVdS12u7XPvKTYVeV8z:-NVdwFmI3MdhSDxfNTlH:b-gxy9k9) ([raw file](https://github.com/gramineproject/gramine/blob/01fdc960070bfa41c5c3ff28640956054fa0daeb/python/graminelibos/sgx_sign.py#L611)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it a bit weird that we have two funcs with different arguments that are suitable as a callback for `graminelibos.Sigstruct.sign()`:
- old `sign_with_local_key()` accepts `key` which is the path to a private key file
- new `sign_with_rsa_key()` accepts `private_key` which is the actual private key object

Or in Python this is considered normal?
</blockquote></details>

`private_key` is how cryptography.io calls the object in examples (they name their variable this way). `key` is from `--key` CLI argument, so you'd have to rename the variable somewhere in the middle of the call chain. IDK how to do this better. If I could, I would call the latter variable `key_path` or `keypath`. Or even mixed `pem` somewhere in there.

I've added "See also" (cf. other thread), maybe it will make it more clear which function to choose, were you a programmer that would need to choose one or another.


<!-- Sent from Reviewable.io -->

2023-05-19 12:01 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`python/graminelibos/sgx_sign.py` line 611 at r4](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVdS12u7XPvKTYVeV8z:-NVns_Al2nhmilPTrabj:b-6hxixp) ([raw file](https://github.com/gramineproject/gramine/blob/01fdc960070bfa41c5c3ff28640956054fa0daeb/python/graminelibos/sgx_sign.py#L611)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`private_key` is how cryptography.io calls the object in examples (they name their variable this way). `key` is from `--key` CLI argument, so you'd have to rename the variable somewhere in the middle of the call chain. IDK how to do this better. If I could, I would call the latter variable `key_path` or `keypath`. Or even mixed `pem` somewhere in there.

I've added "See also" (cf. other thread), maybe it will make it more clear which function to choose, were you a programmer that would need to choose one or another.
</blockquote></details>

Thanks, looks good to me now!


<!-- Sent from Reviewable.io -->

2023-05-21 17:19 UTC, mkow requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 10 unresolved discussions (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVz9ieMD3GcMDryimaI:-NVz9ieMD3GcMDryimaJ:b-vx8dc5) (no related file):*
Depends on https://github.com/gramineproject/gramine/pull/1118.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVz9qzPB1Xex3F8TOVV:-NVz9qzPB1Xex3F8TOVW:b8gpd1u) (no related file):*
TODO for myself: re-test this and play with it after #1118 gets merged in its final form.

___
___
*[`python/graminelibos/sgx_sign.py` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1197#-NOt-OmjDFZrPhcD9Stl:-NVzGfyN9V4bUCMc9ubc:b-ow2cy2) ([raw file](https://github.com/gramineproject/gramine/blob/5730d09970f4881a24a7e60cc73d45e26ba4344b/python/graminelibos/sgx_sign.py#L585)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

2) The length of SHA256 hash. Because padding depends on length of the data, so if the length is the same, then padding is the same and hopefully its manipulation takes the same time.

If it's good, then OK.
</blockquote></details>

Yup, IMO it's ok exactly because of the two arguments which woju pointed out.
___
*[`python/graminelibos/sgx_sign.py` line 573 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzB_384SIl0S_mKJUI:-NVzB_384SIl0S_mKJUJ:b-3h81bd) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L573)):*
> ```Python
>     with file:
>         private_key = serialization.load_pem_private_key(
>             file.read(), password=passphrase, backend=_cryptography_backend)
> ```

Isn't this the default? Actually, where is this documented? The examples in the docs doesn't use this argument when calling `load_pem_private_key()`.



_Code quote:_
```Python
, backend=_cryptography_backend
```
___
*[`python/graminelibos/sgx_sign.py` line 575 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzCEOe-514hPc9xsDF:-NVzCEOe-514hPc9xsDG:bn44pfu) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L575)):*
> ```Python
>             file.read(), password=passphrase, backend=_cryptography_backend)
> 
>     exponent = private_key.public_key().public_numbers().e
> ```

I think this will throw an exception if the loaded key is not RSA (e.g. DSA).
___
*[`python/graminelibos/sgx_sign.py` line 577 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzCvoXD-XL8liuEzbV:-NVzCvoXD-XL8liuEzbW:bbbrpir) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L577)):*
> ```Python
>     exponent = private_key.public_key().public_numbers().e
> 
>     if exponent != SGX_RSA_PUBLIC_EXPONENT:
> ```

What about checking `SGX_RSA_KEY_SIZE`? SGX doesn't work with other sizes.
___
*[`python/graminelibos/sgx_sign.py` line 584 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzDsXJCPF5EcCj0UEo:-NVzDsXJCPF5EcCj0UEp:b7nfgef) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L584)):*
> ```Python
> 
> 
> # NOTE: the name and argument name of this function is kept for compatibility, *key* is path to
> ```

I think we can break it, we have almost no users of this API currently. I.e. easier to break it now than in the future when it actually starts to be used widely.
Also, we have `sign_with_rsa_key()` (as you commented below) that has the same signature, but there `key` means a key object, not a path. Looks very confusing to me.



_Code quote:_
```Python
NOTE: the name and argument name of this function is kept for compatibility,
```
___
*[`python/graminelibos/sgx_sign.py` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzG4MB6s7oEyl04XyB:-NVzG4MB6s7oEyl04XyC:b-hgnwh3) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L629)):*
> ```Python
>     See Also:
>         :func:`sign_with_local_key`
>             This function also signs *data*, but the key argument is path to PEM-encoded file.
> ```

All these explanations could go away if we just removed this confusing compatibility.
___
*[`python/graminelibos/sgx_sign.py` line 633 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzHC4XCoOConYRVhjT:-NVzHC4XCoOConYRVhjU:b-4mnimb) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L633)):*
> ```Python
> 
>     public_numbers = private_key.public_key().public_numbers()
>     assert public_numbers.e == SGX_RSA_PUBLIC_EXPONENT
> ```

The documentation for this function mentions the 3072-bit requirement, but there's no assert for it anywhere.
___
*[`python/graminelibos/sgx_sign.py` line 634 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzJIZO6nJWxa7B35kd:-NVzJIZO6nJWxa7B35ke:brlcif6) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L634)):*
> ```Python
>     public_numbers = private_key.public_key().public_numbers()
>     assert public_numbers.e == SGX_RSA_PUBLIC_EXPONENT
>     signature = private_key.sign(data, padding.PKCS1v15(), hashes.SHA256())
> ```

PKCS1 is not great, but I assume we are forced to use it here because of the SGX ABI?


<!-- Sent from Reviewable.io -->

2023-05-22 19:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 10 unresolved discussions (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVz9ieMD3GcMDryimaI:-NW1pzLhB9Js3j_kL-Gu:bexmhsa) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Depends on https://github.com/gramineproject/gramine/pull/1118.
</blockquote></details>

Yes, this is reflected in base branch.

___
___
*[`python/graminelibos/sgx_sign.py` line 573 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzB_384SIl0S_mKJUI:-NW1q4wD9OZH7aF6YUGN:b-b3uji6) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L573)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this the default? Actually, where is this documented? The examples in the docs doesn't use this argument when calling `load_pem_private_key()`.
</blockquote></details>

- https://cryptography.io/en/latest/faq/#what-happened-to-the-backend-argument
- https://cryptography.io/en/2.8/hazmat/backends/
- https://cryptography.io/en/2.8/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_pem_private_key

This is required to run (to not throw TypeError on function signature) on 20.04, which has python3-cryptography 2.8. Would you like a `# TODO after deprecating 20.04: remove backend`?
___
*[`python/graminelibos/sgx_sign.py` line 575 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzCEOe-514hPc9xsDF:-NW3j4WGCZo_pa5T2gNs:bhrc4do) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L575)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this will throw an exception if the loaded key is not RSA (e.g. DSA).
</blockquote></details>

Done. Yes, it will. DSA has no `e` number.
___
*[`python/graminelibos/sgx_sign.py` line 577 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzCvoXD-XL8liuEzbV:-NW3mL0uEpunwiQVKs3y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L577)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about checking `SGX_RSA_KEY_SIZE`? SGX doesn't work with other sizes.
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 584 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzDsXJCPF5EcCj0UEo:-NW3mSIw7NXpPyxREnKt:b-u9j8x1) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L584)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we can break it, we have almost no users of this API currently. I.e. easier to break it now than in the future when it actually starts to be used widely.
Also, we have `sign_with_rsa_key()` (as you commented below) that has the same signature, but there `key` means a key object, not a path. Looks very confusing to me.
</blockquote></details>

OK, so how we name the functions and arguments?

- `private_key` for cryptography.io object
- `path` for path to file
- `file` for file-like object in python

Now the functions (which ones do we want/need)?
- `sign_with_private_key(private_key)`
- `sign_with_key_from_pem_file(file)`
- `sign_with_key_from_pem_path(path)`

? (or some other names?)

Also, we have two functions for generating keys, and they will remain, because sometimes you just need key object, but sometimes you need it serialised to PEM and it's quite an invocation there so it's very convenient to just put it into another function.
___
*[`python/graminelibos/sgx_sign.py` line 633 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzHC4XCoOConYRVhjT:-NW1poVmEf-v7TJz8Znu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L633)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The documentation for this function mentions the 3072-bit requirement, but there's no assert for it anywhere.
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 634 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzJIZO6nJWxa7B35kd:-NVzwXXXE4C3Reqixr4V:bgxoc15) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L634)):*
Yes, this is hardwired into silicon. SDM, vol. 3D, pt. 4, 38.13 describes SIGNATURE field:

> The (3072-bit integer) SIGNATURE should be an RSA signature, where: a) the RSA modulus (MODULUS) is a 3072-
bit integer; b) the public exponent is set to 3; c) the signing procedure uses the EMSA-PKCS1-v1.5 format with DER
encoding of the “DigestInfo” value as specified in of PKCS#1 v2.1/RFC 3447.

Also IACR 2016/086 6.5, and figure 76 for a nice block diagram.

I can put some references in the comments if you like.


<!-- Sent from Reviewable.io -->

2023-05-22 23:45 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 7 unresolved discussions (waiting on @kailun-qin and @woju)

___
*[`python/graminelibos/sgx_sign.py` line 573 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzB_384SIl0S_mKJUI:-NW4oAcUAA0K2OI3aWbU:blfh9zh) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L573)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

- https://cryptography.io/en/latest/faq/#what-happened-to-the-backend-argument
- https://cryptography.io/en/2.8/hazmat/backends/
- https://cryptography.io/en/2.8/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_pem_private_key

This is required to run (to not throw TypeError on function signature) on 20.04, which has python3-cryptography 2.8. Would you like a `# TODO after deprecating 20.04: remove backend`?
</blockquote></details>

Yes, please add.
___
*[`python/graminelibos/sgx_sign.py` line 584 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzDsXJCPF5EcCj0UEo:-NW4pQtPBWkpP2Ay-N65:b-kjtj2e) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L584)):*
I like the proposed names.

> Also, we have two functions for generating keys, and they will remain, because sometimes you just need key object, but sometimes you need it serialised to PEM and it's quite an invocation there so it's very convenient to just put it into another function.

I have no problem with this, looks reasonable.
___
*[`python/graminelibos/sgx_sign.py` line 634 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzJIZO6nJWxa7B35kd:-NW4qKNOBkC4GTdfyURe:b87cj6a) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L634)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, this is hardwired into silicon. SDM, vol. 3D, pt. 4, 38.13 describes SIGNATURE field:

> The (3072-bit integer) SIGNATURE should be an RSA signature, where: a) the RSA modulus (MODULUS) is a 3072-
bit integer; b) the public exponent is set to 3; c) the signing procedure uses the EMSA-PKCS1-v1.5 format with DER
encoding of the “DigestInfo” value as specified in of PKCS#1 v2.1/RFC 3447.

Also IACR 2016/086 6.5, and figure 76 for a nice block diagram.

I can put some references in the comments if you like.
</blockquote></details>

Yeah, putting some ref into a comment sounds useful.


<!-- Sent from Reviewable.io -->

2023-07-20 12:48 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`python/graminelibos/sgx_sign.py` line 573 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzB_384SIl0S_mKJUI:-N_mrsWUA68THYhjwZJ5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L573)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, please add.
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 584 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzDsXJCPF5EcCj0UEo:-N_mwKtW1vr2xziJuxAR:b969yb5) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L584)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like the proposed names.

> Also, we have two functions for generating keys, and they will remain, because sometimes you just need key object, but sometimes you need it serialised to PEM and it's quite an invocation there so it's very convenient to just put it into another function.

I have no problem with this, looks reasonable.
</blockquote></details>

OK, I think I got it right this time. It boils down to `{load,sign_with}_private_key{,_from_pem_file,_from_pem_path}` (not all of them) and `generate_private_key{,_pem}`. `_from_pem_*` take optional `passphrase` argument.
___
*[`python/graminelibos/sgx_sign.py` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzG4MB6s7oEyl04XyB:-N_nE20oBf-XFHo65zHL:b-a9cjbw) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L629)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

All these explanations could go away if we just removed this confusing compatibility.
</blockquote></details>

Those explanations are needed anyway, if we have three functions that do almost the same, you should be able to navigate the docs from one to another by clicking the link here.
___
*[`python/graminelibos/sgx_sign.py` line 634 at r5](https://reviewable.io/reviews/gramineproject/gramine/1197#-NVzJIZO6nJWxa7B35kd:-N_nKy0NDFXaol14W17V:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e5f1a3f190834620dd9b2ff93fd79daa5ca1c08/python/graminelibos/sgx_sign.py#L634)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, putting some ref into a comment sounds useful.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-25 08:31 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`python/graminelibos/sgx_sign.py` line 619 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8YLcEnJkc0wEsl7x:-NaB8YLd1wP5BqiQARxv:b-btgz) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L619)):*
> ```Python
>     # SDM vol. 3D pt. 4 38.13, description of SIGNATURE field:
>     #   The (3072-bit integer) SIGNATURE should be an RSA signature, where:
>     #   a) the RSA modulus (MODULUS) is a 3072- bit integer;
> ```

`3072-bit`
___
*[`python/graminelibos/sgx_sign.py` line 622 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8dPX41mWyO2PaAuf:-NaB8dPX41mWyO2PaAug:bp1f8r7) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L622)):*
> ```Python
>     #   b) the public exponent is set to 3;
>     #   c) the signing procedure uses the EMSA-PKCS1-v1.5 format with DER encoding of the
>     #      “DigestInfo” value as specified in of PKCS#1 v2.1/RFC 3447.
> ```

`in of` -> `in`
___
*[`python/graminelibos/sgx_sign.py` line 630 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8tb_-fQwsvPCxevr:-NaB8tb_-fQwsvPCxevs:b-4v97xh) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L630)):*
> ```Python
> 
> def sign_with_private_key_from_pem_file(data, file, passphrase=None):
>     """Signs *data* using key loaded from *path*.
> ```

Loaded from path? This is wrong.


<!-- Sent from Reviewable.io -->

2023-07-25 12:47 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 1 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`python/graminelibos/sgx_sign.py` line 619 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8YLcEnJkc0wEsl7x:-NaC1LuY5zmI_KBi3aE2:b-q9j2va) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L619)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`3072-bit`
</blockquote></details>

Done. Thanks, this was copy-paste failure. 
___
*[`python/graminelibos/sgx_sign.py` line 622 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8dPX41mWyO2PaAuf:-NaC1dMO4wGni6mqLNh6:bh1kld) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L622)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in of` -> `in`
</blockquote></details>

This is quoted as-is from SDM, only rewrapped. Please file a bug against SDM. :)
___
*[`python/graminelibos/sgx_sign.py` line 630 at r7](https://reviewable.io/reviews/gramineproject/gramine/1197#-NaB8tb_-fQwsvPCxevr:-NaC1zC98SpWpG7_Cn6b:b-senru) ([raw file](https://github.com/gramineproject/gramine/blob/bee589c243ec35881019ef925f5941e870c96e3d/python/graminelibos/sgx_sign.py#L630)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Loaded from path? This is wrong.
</blockquote></details>

Done. Also fixed `Args:` below.


<!-- Sent from Reviewable.io -->

2023-07-25 13:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 7 unresolved discussions (waiting on @kailun-qin, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2023-08-02 03:15 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 6 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2023-08-26 01:06 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`python/graminelibos/sgx_sign.py` line 607 at r9](https://reviewable.io/reviews/gramineproject/gramine/1197#-NcjHZ8q9YaQQMntxzvJ:-NcjHZ8q9YaQQMntxzvK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/753ba972acc3e0d98482f17a8c13eccdd0d62e96/python/graminelibos/sgx_sign.py#L607)):*
> ```Python
>         :func:`sign_with_private_key_from_pem_file`
>             This function also signs *data*, but the key argument is an already
>             opened file
> ```





_Suggestion:_
```Python
opened file.
```
___
*[`python/graminelibos/sgx_sign.py` line 610 at r9](https://reviewable.io/reviews/gramineproject/gramine/1197#-NcjH_FoAG8ROPqra677:-NcjH_FoAG8ROPqra678:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/753ba972acc3e0d98482f17a8c13eccdd0d62e96/python/graminelibos/sgx_sign.py#L610)):*
> ```Python
>         :func:`sign_with_private_key_from_pem_path`
>             This function also signs *data*, but the key argument is path to a file, not a file-like
>             object
> ```





_Suggestion:_
```Python
object.
```
___
*[`python/graminelibos/sgx_sign.py` line 673 at r9](https://reviewable.io/reviews/gramineproject/gramine/1197#-NcjHERE4FYEY4LHFkyj:-NcjHERE4FYEY4LHFkyk:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/753ba972acc3e0d98482f17a8c13eccdd0d62e96/python/graminelibos/sgx_sign.py#L673)):*
> ```Python
>         :func:`sign_with_private_key`
>             This function also signs *data*, but the key argument is
>             :class:`cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey` instance
> ```





_Suggestion:_
```Python
:class:`cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey` instance.
```
___
*[`python/graminelibos/sgx_sign.py` line 676 at r9](https://reviewable.io/reviews/gramineproject/gramine/1197#-NcjHHGO-gOajzP_Ye2z:-NcjHHGO-gOajzP_Ye3-:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/753ba972acc3e0d98482f17a8c13eccdd0d62e96/python/graminelibos/sgx_sign.py#L676)):*
> ```Python
>         :func:`sign_with_private_key_from_pem_file`
>             This function also signs *data*, but the key argument is an already
>             opened file
> ```





_Suggestion:_
```Python
opened file.
```


<!-- Sent from Reviewable.io -->

2023-08-29 10:26 UTC, kailun-qin approved these changes
> Reviewed 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-30 06:54 UTC, dimakuv approved these changes
> Reviewed 1 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: 2 of 13 files reviewed, 4 unresolved discussions (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-31 23:27 UTC, mkow approved these changes
> Reviewed 1 of 12 files at r10, 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-31 23:42 UTC, kailun-qin approved these changes
> Reviewed 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1197)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-01 15:11 UTC, merged