[CI] Run almalinux9 on hosts that support `clone3`
gramineproject/gramine pull request #1199
Opened 2023-02-22 17:27 UTC by oshogbo

## Description of the changes 

A new version of glibc uses `clone3` to create a thread, to resolve a hostname. almalinux9 uses a new version of this library. CI agents need to support `clone3 syscall` to test Gramine on this distribution.

The `clone3` syscall was introduced in the Linux kernel 5.3. Besides the kernel also userland utilities have to support it, like docker to create valid seccomp rules.

To indicate full support of this syscall new label `clone3` has been introduced.

## How to test this PR? 

CI should be sufficient.

2023-02-22 17:29 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-02-22 19:07 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuESqIArEMq3dUvntz):*




_Suggestion:_
```
Run almalinux9 only on hosts that support `clone3`
```
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVdFv6SvAisYcUxho):*
ditto for other places



_Suggestion:_
```
AlmaLinux 9
```
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVnJz-XTYbXNfFYUD):*




_Suggestion:_
```
A new version of glibc uses `clone3` to create a thread. To
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVsh0CX7Te1JKowxm):*
[...] because Docker uses the kernel from the host.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuW5pS8eqznHD5Pzkf):*




_Suggestion:_
```
Besides the kernel, userland utilities also have to support it,
```
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuW9mP3D0MP1d3aRJx):*




_Suggestion:_
```
Docker when creating valid seccomp rules
```


<!-- Sent from Reviewable.io -->

2023-02-22 19:11 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 6 unresolved discussions (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-02-22 21:27 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOv0Khj4AJSslKBs3vs:-NOv0Khj4AJSslKBs3vt:boxtxwm) (no related file):*
I used a force push, as I think there isn't any issue with the code, just with commit-msg, and to speed up a potential merge.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuESqIArEMq3dUvntz):*
This line would be too long for a oneliner.
Do we still want to add it?
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVdFv6SvAisYcUxho):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for other places
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVnJz-XTYbXNfFYUD):*
Won't this sentence be too fragmented?
Maybe something like this?
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVsh0CX7Te1JKowxm):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

[...] because Docker uses the kernel from the host.
</blockquote></details>

Done.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuW5pS8eqznHD5Pzkf):*
Done.j
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuW9mP3D0MP1d3aRJx):*
Done.


<!-- Sent from Reviewable.io -->

2023-02-23 08:16 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOv0Khj4AJSslKBs3vs:-NOxKOvpAHlDtgrgKPNG:b2d9mio) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I used a force push, as I think there isn't any issue with the code, just with commit-msg, and to speed up a potential merge.
</blockquote></details>

Yep, though this PR is two commits behind master :)

So when you amend the commit message again (see comments), please also git-rebase.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuESqIArEMq3dUvntz):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

This line would be too long for a oneliner.
Do we still want to add it?
</blockquote></details>

I would add it. We have many commit titles that are too long, and that's fine.


<!-- Sent from Reviewable.io -->

2023-02-23 09:47 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuESqIArEMq3dUvntz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add it. We have many commit titles that are too long, and that's fine.
</blockquote></details>

Then ok :)


<!-- Sent from Reviewable.io -->

2023-02-23 10:32 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-02-23 11:00 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-02-26 02:30 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1199)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuESqIArEMq3dUvntz):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Then ok :)
</blockquote></details>

Yeah, I also don't treat these limits are hard limits, more like a hint to try to be more concise when you cross it. If making it slightly longer makes it much more clear / self-explanatory then why not :)
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1199#-NOuVnJz-XTYbXNfFYUD):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Won't this sentence be too fragmented?
Maybe something like this?
</blockquote></details>

Still reads weirdly. Because of short sentences. Too many short sentences read unnaturally.
;P
But it's good enough, so I'm resolving. But please keep this in mind in the future.


<!-- Sent from Reviewable.io -->

2023-02-26 02:31 UTC, merged