[tools/sgx,CI-Examples] Expose RA-TLS verification error details via callback args
gramineproject/gramine pull request #1215
Opened 2023-03-06 11:38 UTC by kailun-qin

Previously, RA-TLS hid the details of errors in a dull and uninformative way. This was due to that `ra_tls_verify_callback()` is an mbedtls-adhering callback function, and we cannot simply return a non-mbedtls error code as a ret value.

This patch introduces `ra_tls_verify_callback_args` and a new RA-TLS API `ra_tls_verify_callback_extended_der()` to unhide the detailed error information (e.g. the original SGX-attestation-verification error code) from RA-TLS.

Resolves https://github.com/gramineproject/gramine/issues/1209.

2023-03-06 14:20 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 0 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPrFHcq283J68yyn679:-NPrFHcq283J68yyn67A:b-f8nmtt) ([raw file](https://github.com/gramineproject/gramine/blob/6e9fc1b751407bca6845bb914a92b771d1b61657/tools/sgx/verify-ias-report/verify_ias_report.c#L170)):*
> ```C
>     uint8_t* report_quote_body = NULL;
>     size_t quote_body_size = 0;
>     char* quote_status = NULL;
> ```

What is the point of fetching quota here?
Shouldn't it handle just NULL?
___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPrFBfdAgUKAHAi-h5b:-NPrFBfeCnNMdJsQjl4h:b-7nwjfd) ([raw file](https://github.com/gramineproject/gramine/blob/6e9fc1b751407bca6845bb914a92b771d1b61657/tools/sgx/verify-ias-report/verify_ias_report.c#L176)):*
> ```C
>                                           allow_outdated_tcb, nonce, ias_pubkey,
>                                           &report_quote_body, &quote_body_size, &quote_status);
>     if (ret < 0)
> ```

If ret == -1 you are not freeing the quota, and in each return -1.


<!-- Sent from Reviewable.io -->

2023-03-06 15:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 0 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPrFHcq283J68yyn679:-NPrRiFQAmHedEWy34xT:b-q8xacz) ([raw file](https://github.com/gramineproject/gramine/blob/6e9fc1b751407bca6845bb914a92b771d1b61657/tools/sgx/verify-ias-report/verify_ias_report.c#L170)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What is the point of fetching quota here?
Shouldn't it handle just NULL?
</blockquote></details>

Yes, it should. The previous version was an incomplete draft (missing NULL handling everywhere), updated now.
___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPrFBfdAgUKAHAi-h5b:-NPrRmUF44s8LObRreh4:bwd8vv8) ([raw file](https://github.com/gramineproject/gramine/blob/6e9fc1b751407bca6845bb914a92b771d1b61657/tools/sgx/verify-ias-report/verify_ias_report.c#L176)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If ret == -1 you are not freeing the quota, and in each return -1.
</blockquote></details>

Not relevant any more.


<!-- Sent from Reviewable.io -->

2023-03-07 11:21 UTC, dimakuv requested changes
> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnHyD1sgcilUhDliY:-NPvnHyD1sgcilUhDliZ:b-oz0576) (no related file):*
@kailun-qin Did you check this PR?

TODO(myself): verify that this PR works.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnKI91MU5gGFBRzJt:-NPvnKIA6icdnbTVpk0d:b-kuvln1) (no related file):*
Could you also modify the `ra-tls-secret-prov` example similarly? I think at least in one version there, we could do it.

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvfxSABz0xLtDQ1xIF:-NPvfxSABz0xLtDQ1xIG:bbkituk) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L41)):*
> ```C
> /* RA-TLS: on client, only need to register ra_tls_verify_callback_der() or
>  * ra_tls_verify_callback_extended_der() for cert verification.
>  * In this example, we use ra_tls_verify_callback_extended_der() for demonstration. */
> ```

I would just mention `ra_tls_verify_callback_extended_der()`, and not mention the old `ra_tls_verify_callback_der()`. I think we want to deprecate the latter, so no need to pay too much attention to it.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 373 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvn2iCBYe8KrlY0rRU:-NPvn2iCBYe8KrlY0rRV:b-a1ka35) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L373)):*
> ```C
>     mbedtls_printf("  . Performing the SSL/TLS handshake...");
>     fflush(stdout);
> ```

Actually, you would want to nullify `my_verify_callback_args` here. Because during TLS handshake this object will be populated.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 376 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnDN_3iPp6ON8k_Bi:-NPvnDNa1Zd8I1BvS56O:bklh097) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L376)):*
> ```C
>     while ((ret = mbedtls_ssl_handshake(&ssl)) != 0) {
>         if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
>             mbedtls_printf(" failed\n  ! mbedtls_ssl_handshake returned -0x%x\n\n", -ret);
> ```

Somewhere here you would want to print the values from `my_verify_callback_args`.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 451 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvgGf1AIthRNYAAJLY:-NPvgGf1AIthRNYAAJLZ:bvaboe4) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L451)):*
> ```C
>     }
> #endif
>     free(my_verify_callback_args.ias_enclave_quote_status);
> ```

Ouch, this is terrible. This is a really bad design -- users will forget about this, and it's just generally ugly and hard to support.

See my other comment.
___
*[`tools/sgx/common/ias.h` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvlvcB1UWYMaaEIuZk:-NPvlvcC9jTjdnEx4Dno:b-reu07k) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L117)):*
> ```objc
>  * \param enclave_quote_status   (Optional) If non-NULL, this contains the returned
>  *                               `isvEnclaveQuoteStatus` string on enclave quote status verification
>  *                               failure; user is responsible for freeing it.
> ```

I suggest to have a fixed-size array, so no need to free it. Please remove this last part.

Please also mention that the string may be truncated to fit into 128 bytes (including terminating NUL char).
___
*[`tools/sgx/common/ias.h` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvlrGCC5am6Fv7bs_7:-NPvlrGCC5am6Fv7bs_8:betr7tc) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L118)):*
> ```objc
>  *                               `isvEnclaveQuoteStatus` string on enclave quote status verification
>  *                               failure; user is responsible for freeing it.
>  *                               Otherwise this param is simply ignored and nothing contains.
> ```

This last sentence is useless; of course the NULL param is ignored...
___
*[`tools/sgx/common/ias.h` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvla7s4JLA61ncVfLZ:-NPvla7s4JLA61ncVfL_:b-1tm9f4) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L127)):*
> ```objc
>                                     uint8_t* ias_sig_b64, size_t ias_sig_b64_size,
>                                     bool allow_outdated_tcb, const char* nonce,
>                                     const char* ias_pub_key_pem, char** enclave_quote_status,
> ```

See my other comments. Should be `char (*enclave_quote_status)[128]`.
___
*[`tools/sgx/common/ias.c` line 631 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvm5vA3F7DI751zWOT:-NPvm5vA3F7DI751zWOU:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L631)):*
> ```C
>                                     uint8_t* ias_sig_b64, size_t ias_sig_b64_size,
>                                     bool allow_outdated_tcb, const char* nonce,
>                                     const char* ias_pub_key_pem, char** enclave_quote_status,
> ```

ditto
___
*[`tools/sgx/common/ias.c` line 735 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvmCUm9kYHZZk6s89T:-NPvmCUnDe-o8DkgrFyh:b-4fayz0) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L735)):*
> ```C
>     }
> 
>     quote_status = strdup(node->valuestring);
> ```

With my proposal, you won't need this scattered logic. You can do simply:
```
if (enclave_quote_status) {
    strncpy(enclave_quote_status, node->valuestring, sizeof(enclave_quote_status));
    enclave_quote_status[sizeof(enclave_quote_status) - 1] = '\0';
}
```
___
*[`tools/sgx/common/ias.c` line 840 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvme9-DaEoLM1dww7U:-NPvme9-DaEoLM1dww7V:b-apqndv) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L840)):*
> ```C
>     } else {
>         free(quote_status);
>     }
> ```

With my proposal, you won't need this logic at all.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvifIy9NXx1XYKTz2k:-NPvifIy9NXx1XYKTz2l:b-hyyydh) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/ra-tls/ra_tls.h#L35)):*
> ```objc
>     AT_INIT                        = 1,
>     AT_EXTRACT_QUOTE               = 2,
>     AT_IAS_VERIFY                  = 3,
> ```

Hm, I don't like that we have IAS/DCAP distinction here. It creates an illusion that the same RA-TLS library can return both of these errors (which is not true, one RA-TLS library can only work on IAS or only on DCAP).

So maybe we coalesce these two and rename to `AT_VERIFY_EXTERNAL`? Or some better name...
___
*[`tools/sgx/ra-tls/ra_tls.h` line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPviNyO5ndZ240WyP6d:-NPviNyO5ndZ240WyP6e:b-1 [...]

2023-03-07 13:43 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnHyD1sgcilUhDliY:-NPwGgxL89pL21BmDm_b:b-r4lbrq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Did you check this PR?

TODO(myself): verify that this PR works.
</blockquote></details>

Yes, I checked this manually in a DCAP env.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnKI91MU5gGFBRzJt:-NPwGlQ30j3UtaKdurRb:bfu0k7x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you also modify the `ra-tls-secret-prov` example similarly? I think at least in one version there, we could do it.
</blockquote></details>

Sorry, I don't quite get this one - do we set any verification callback in `ra-tls-secret-prov` example?

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvfxSABz0xLtDQ1xIF:-NPwHKtjCgRfELhcboLa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would just mention `ra_tls_verify_callback_extended_der()`, and not mention the old `ra_tls_verify_callback_der()`. I think we want to deprecate the latter, so no need to pay too much attention to it.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 373 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvn2iCBYe8KrlY0rRU:-NPwHLon3z3vy81lu35w:b8gj3mz) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L373)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, you would want to nullify `my_verify_callback_args` here. Because during TLS handshake this object will be populated.
</blockquote></details>

Good catch, fixed.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 376 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnDN_3iPp6ON8k_Bi:-NPwHOAu2b9iB4HsuofQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L376)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Somewhere here you would want to print the values from `my_verify_callback_args`.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 451 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvgGf1AIthRNYAAJLY:-NPwHPPq8DdQQO2tokm6:b-9vhyeg) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/CI-Examples/ra-tls-mbedtls/src/client.c#L451)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ouch, this is terrible. This is a really bad design -- users will forget about this, and it's just generally ugly and hard to support.

See my other comment.
</blockquote></details>

Indeed, fixed.
___
*[`tools/sgx/common/ias.h` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvlvcB1UWYMaaEIuZk:-NPwHTeu2Qwk8mGTeB2R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to have a fixed-size array, so no need to free it. Please remove this last part.

Please also mention that the string may be truncated to fit into 128 bytes (including terminating NUL char).
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvlrGCC5am6Fv7bs_7:-NPwHVCN0HpzZmlFEyop:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This last sentence is useless; of course the NULL param is ignored...
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 127 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvla7s4JLA61ncVfLZ:-NPwHWnF8bdWSGcv-FoF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.h#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comments. Should be `char (*enclave_quote_status)[128]`.
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 631 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvm5vA3F7DI751zWOT:-NPwHXT466BZR4-1Rb71:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L631)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 735 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvmCUm9kYHZZk6s89T:-NPwHYP-096e3TH2gxzj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L735)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With my proposal, you won't need this scattered logic. You can do simply:
```
if (enclave_quote_status) {
    strncpy(enclave_quote_status, node->valuestring, sizeof(enclave_quote_status));
    enclave_quote_status[sizeof(enclave_quote_status) - 1] = '\0';
}
```
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 840 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvme9-DaEoLM1dww7U:-NPwHYwZ7KUOIhGijlQ7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/common/ias.c#L840)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With my proposal, you won't need this logic at all.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvifIy9NXx1XYKTz2k:-NPwHbmrEFDzJYK_wktS:b-fpr1oz) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/ra-tls/ra_tls.h#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I don't like that we have IAS/DCAP distinction here. It creates an illusion that the same RA-TLS library can return both of these errors (which is not true, one RA-TLS library can only work on IAS or only on DCAP).

So maybe we coalesce these two and rename to `AT_VERIFY_EXTERNAL`? Or some better name...
</blockquote></details>

Yes, I think it's fine to coalesce (did not find a better name though). Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPviNyO5ndZ240WyP6d:-NPwHleiE4md6LLglRdw:br01qyq) ([raw file](https://github.com/gramineproject/gramine/blob/8e7cacb5496889cdefa645d928d1a746cecbc4ec/tools/sgx/ra-tls/ra_tls.h#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's that comment? I haven't seen such convention before.
</blockquote></details> [...]

2023-03-08 10:43 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnKI91MU5gGFBRzJt:-NQ-kLSl8nro9aFw_Dnn:b1efg8r) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry, I don't quite get this one - do we set any verification callback in `ra-tls-secret-prov` example?
</blockquote></details>

Hm, you're right. Secret Prov library hides all this information away from users/apps.

Could you check if we need to modify Secret Prov library internals then, to use the new function? In particular here: https://github.com/gramineproject/gramine/blob/361dfff60161550fd9c77164f42712a795410053/tools/sgx/ra-tls/secret_prov_verify.c#L243

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 380 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-mWgc6rPQ3iXB1zeu:-NQ-mWgd31bPcw99yxZk:be0dfci) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L380)):*
> ```C
>                            my_verify_callback_args.attestation_scheme,
>                            my_verify_callback_args.err_loc);
>             if (RA_TLS_ATTESTATION_SCHEME_EPID == my_verify_callback_args.attestation_scheme) {
> ```

Could you flip the two? I don't like this `const == variable` way.

UPDATE: Actually, I think a `switch` statement will be better here.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 383 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-mam16rKuBVK0OkUG:-NQ-mam16rKuBVK0OkUH:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L383)):*
> ```C
>                 mbedtls_printf("    epid.ias_enclave_quote_status=%s\n\n",
>                                my_verify_callback_args.epid.ias_enclave_quote_status);
>             } else if (RA_TLS_ATTESTATION_SCHEME_DCAP \
> ```

ditto
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 390 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-msOCBL-s8YpFXLGv:-NQ-msOCBL-s8YpFXLGw:b-q80son) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L390)):*
> ```C
>                                my_verify_callback_args.dcap.quote_verification_result);
>             } else {
>                 mbedtls_printf("  ! invalid attestation scheme!\n\n");
> ```

"Invalid" is a strong word. Maybe `unknown`?
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 396 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-m6KC0Oa_lHm2dFnD:-NQ-m6KC0Oa_lHm2dFnE:bgryj20) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L396)):*
> ```C
>         }
>         /* nullify callback args as it will get populated during TLS handshake */
>         memset(&my_verify_callback_args, 0, sizeof(my_verify_callback_args));
> ```

I meant right-before the while loop. This while loop around `mbedtls_ssl_handshake(&ssl)` is introduced because the TLS handshake is a long operation, and the host OS may choose to EINTR it in the middle. In this case, the callback args may have already been populated (in one of the many TLS-handshake steps), and you'll nullify it, which is wrong.
___
*[`tools/sgx/common/ias.c` line 735 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-nG2d2aQH77f62Ceo:-NQ-nG2d2aQH77f62Cep:b-hok3fw) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/tools/sgx/common/ias.c#L735)):*
> ```C
> 
>     if (enclave_quote_status) {
>         strncpy(*enclave_quote_status, node->valuestring, sizeof(enclave_quote_status));
> ```

Is this `sizeof(...)` correct? Won't it be 8 (the size of the **pointer**)? We need 128 here.

Since you don't have an EPID machine (I guess), you can check the resulting assembly I guess. And I can later test this PR on an EPID machine.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-nqZAEstud2EYoVTy:-NQ-nqZAEstud2EYoVTz:b-xadfbb) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/tools/sgx/ra-tls/ra_tls.h#L51)):*
> ```objc
>     union {
>         struct {
>             /* string returned in `isvEnclaveQuoteStatus`; possibly truncated (but NUL-terminated) */
> ```

1 char more than our limit of 100 chars per line :)

I suggest to change `string` -> `str` and then it will fit into one line


<!-- Sent from Reviewable.io -->

2023-03-08 12:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnKI91MU5gGFBRzJt:-NQ09_0N-WarwsR3O5Nn:bji4ewy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, you're right. Secret Prov library hides all this information away from users/apps.

Could you check if we need to modify Secret Prov library internals then, to use the new function? In particular here: https://github.com/gramineproject/gramine/blob/361dfff60161550fd9c77164f42712a795410053/tools/sgx/ra-tls/secret_prov_verify.c#L243
</blockquote></details>

OK, I actually kept Secret Prov library internals unchanged (w/ `args=NULL`) intentionally. Updated now by using callback args.

___
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 380 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-mWgc6rPQ3iXB1zeu:-NQ0AO3-1RqS9lWVGTpx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L380)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you flip the two? I don't like this `const == variable` way.

UPDATE: Actually, I think a `switch` statement will be better here.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 383 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-mam16rKuBVK0OkUG:-NQ0AOt_-xjFA7rPtXI9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L383)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 390 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-msOCBL-s8YpFXLGv:-NQ0APY_2-KJTxZFpogO:bgomejm) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L390)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

"Invalid" is a strong word. Maybe `unknown`?
</blockquote></details>

Done. Also renamed `RA_TLS_ATTESTATION_SCHEME_INVALID` to `RA_TLS_ATTESTATION_SCHEME_UNKNOWN`
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 396 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-m6KC0Oa_lHm2dFnD:-NQ0AWWV9O1guCq_YFfQ:bj4wiv) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/CI-Examples/ra-tls-mbedtls/src/client.c#L396)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I meant right-before the while loop. This while loop around `mbedtls_ssl_handshake(&ssl)` is introduced because the TLS handshake is a long operation, and the host OS may choose to EINTR it in the middle. In this case, the callback args may have already been populated (in one of the many TLS-handshake steps), and you'll nullify it, which is wrong.
</blockquote></details>

OK - I misunderstood, fixed.
___
*[`tools/sgx/common/ias.c` line 735 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-nG2d2aQH77f62Ceo:-NQ0A_qzAXi22IkGcqhp:bjgxw8y) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/tools/sgx/common/ias.c#L735)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this `sizeof(...)` correct? Won't it be 8 (the size of the **pointer**)? We need 128 here.

Since you don't have an EPID machine (I guess), you can check the resulting assembly I guess. And I can later test this PR on an EPID machine.
</blockquote></details>

You're definitely correct - it's wrong. This is a stupid mistake where I blindly copy-pasted your previous comment but only fixed partial of it.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ-nqZAEstud2EYoVTy:-NQ0Aq9QAL_LpzZ2QrfB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad07f13554f52d4cafa0f960b41268453f5fd64d/tools/sgx/ra-tls/ra_tls.h#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1 char more than our limit of 100 chars per line :)

I suggest to change `string` -> `str` and then it will fit into one line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-08 14:09 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 77 at r4](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ0XFXx2ZOsBbknjtEe:-NQ0XFXx2ZOsBbknjtEf:bh727f9) ([raw file](https://github.com/gramineproject/gramine/blob/e5c856e121b4f377d5ad96b6c88b4bd34d665ff1/tools/sgx/ra-tls/secret_prov_verify.c#L77)):*
> ```C
>     int ret;
>     struct thread_info* ti = (struct thread_info*)data;
>     struct ra_tls_verify_callback_args args = {0};
> ```

This is all wrong. Internally, RA-TLS will use the `args` object that was allocated on the stack of `secret_provision_start_server`.

So the `args` object in this `client_connection()` function will never be updated, and you'll print all zeros below, when you do `ERROR()`.

What you really need to do is to use the `ti` object -- it is used to pass the objects between the main thread (that starts the mbedTLS server socket) and these "client connection" threads.

So you should do something like this:
1. Keep `args` object in `secret_provision_start_server()` allocated on the stack, as you do now.
2. Pass it in `ti->args = &conf`.
3. Under the lock `&g_handshake_lock`, right-after `mbedtls_ssl_handshake()`, copy the contents of `ti->args` into some temporary variable (to be able to release the lock, because `ti->args` can be modified after the lock is released).
4. Use this temporary variable to print all these `ERROR()` messages.


<!-- Sent from Reviewable.io -->

2023-03-08 17:29 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ1GIcT0Y-6WpVfLfDV:-NQ1GIcT0Y-6WpVfLfDW:b-40ml6i) ([raw file](https://github.com/gramineproject/gramine/blob/e5c856e121b4f377d5ad96b6c88b4bd34d665ff1/tools/sgx/ra-tls/ra_tls.h#L45)):*
> ```objc
> 
> /* Verification callback arguments for retrieving additional information from RA-TLS */
> struct ra_tls_verify_callback_args {
> ```

Need to add a comment that this struct is (at least currently) an out-only struct (there can be no input fields, provided by the application/user)


<!-- Sent from Reviewable.io -->

2023-03-08 17:42 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 8 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ1GIcT0Y-6WpVfLfDV:-NQ1J96UE1klHXI8QNcy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5c856e121b4f377d5ad96b6c88b4bd34d665ff1/tools/sgx/ra-tls/ra_tls.h#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to add a comment that this struct is (at least currently) an out-only struct (there can be no input fields, provided by the application/user)
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 77 at r4](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQ0XFXx2ZOsBbknjtEe:-NQ1J9Z4DERx20i6VEBf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e5c856e121b4f377d5ad96b6c88b4bd34d665ff1/tools/sgx/ra-tls/secret_prov_verify.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is all wrong. Internally, RA-TLS will use the `args` object that was allocated on the stack of `secret_provision_start_server`.

So the `args` object in this `client_connection()` function will never be updated, and you'll print all zeros below, when you do `ERROR()`.

What you really need to do is to use the `ti` object -- it is used to pass the objects between the main thread (that starts the mbedTLS server socket) and these "client connection" threads.

So you should do something like this:
1. Keep `args` object in `secret_provision_start_server()` allocated on the stack, as you do now.
2. Pass it in `ti->args = &conf`.
3. Under the lock `&g_handshake_lock`, right-after `mbedtls_ssl_handshake()`, copy the contents of `ti->args` into some temporary variable (to be able to release the lock, because `ti->args` can be modified after the lock is released).
4. Use this temporary variable to print all these `ERROR()` messages.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 01:35 UTC, mkow requested changes
> Reviewed 2 of 9 files at r1, 4 of 7 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 373 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSZ3RfDIZHSKRyCwg6:-NQSZ3RfDIZHSKRyCwg7:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/CI-Examples/ra-tls-mbedtls/src/client.c#L373)):*
> ```C
>     fflush(stdout);
> 
>     /* nullify callback args as it will get populated during TLS handshake */
> ```





_Suggestion:_
```C
zero callback args as they will
```
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 374 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQScdij51Qyh4U5qOeu:-NQScdij51Qyh4U5qOev:bntzxdf) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/CI-Examples/ra-tls-mbedtls/src/client.c#L374)):*
> ```C
> 
>     /* nullify callback args as it will get populated during TLS handshake */
>     memset(&my_verify_callback_args, 0, sizeof(my_verify_callback_args));
> ```

Actually, could we move this to ra-tls, to ensure that all the not-filled fields are always zeroed? We set those fields conditionally based on the attestation scheme used, and this is a security critical code, so I'd prefer if a bug in user's code lead to reading zeros instead of uninitialized data.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSeEyM48BJVadq6S6E:-NQSeEyN80XlXHqrQB0n:b-67bqsg) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L44)):*
> ```objc
> } ra_tls_err_loc_t;
> 
> /* Verification callback arguments for retrieving additional information from RA-TLS.
> ```

Isn't this misleading for someone who won't read this code within the context of this PR and the corresponding issue? These are not really arguments for the verification, rather a struct where the verification can place the extended results of the verification.



_Code quote:_
```objc
Verification callback arguments
```
___
*[`tools/sgx/ra-tls/ra_tls.h` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSh5VfEwCdMtV-ZHqh:-NQSh5VfEwCdMtV-ZHqi:bo5ne7c) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L48)):*
> ```objc
>  * provided by the application/user) */
> struct ra_tls_verify_callback_args {
>     int attestation_scheme;   /* see macros RA_TLS_ATTESTATION_SCHEME_ */
> ```

Any reason for not making this an enum? You wouldn't need to explain anything in the comment then.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 49 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShHLG41bAjmO0QzCs:-NQShHLG41bAjmO0QzCt:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L49)):*
> ```objc
> struct ra_tls_verify_callback_args {
>     int attestation_scheme;   /* see macros RA_TLS_ATTESTATION_SCHEME_ */
>     ra_tls_err_loc_t err_loc; /* error location in RA-TLS */
> ```





_Suggestion:_
```objc
/* the step at which RA-TLS failed */
```
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQShWVq8p8AVuotKSz9:b-4xceam) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
> ```objc
>         struct {
>             char reserved[128];
>         } misc;
> ```

What's the point of this?
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 240 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShpc66xhxh2O6nouP:-NQShpc66xhxh2O6nouQ:b-xvj123) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls_verify_common.c#L240)):*
> ```C
> 
> int ra_tls_verify_callback_der(uint8_t* der_crt, size_t der_crt_size) {
>     return ra_tls_verify_callback_extended_der(der_crt, der_crt_size, /*unused args=*/NULL);
> ```

Maybe we should also print a deprecation warning here? Otherwise people will never notice.
___
*[`tools/sgx/ra-tls/ra_tls_verify_epid.c` line 230 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSja2sDqrRgot1OuVa:-NQSja2sDqrRgot1OuVb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls_verify_epid.c#L230)):*
> ```C
>                                           allow_outdated_tcb, nonce,
>                                           ias_pub_key_pem,
>                                           (args) ? &args->epid.ias_enclave_quote_status : NULL,
> ```





_Suggestion:_
```C
args ? &args->epid.ias_enclave_quote_status : NULL
```


<!-- Sent from Reviewable.io -->

2023-03-14 08:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 374 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQScdij51Qyh4U5qOeu:-NQUHi9J5zaMqI2jqxhE:bqs0g0d) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/CI-Examples/ra-tls-mbedtls/src/client.c#L374)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, could we move this to ra-tls, to ensure that all the not-filled fields are always zeroed? We set those fields conditionally based on the attestation scheme used, and this is a security critical code, so I'd prefer if a bug in user's code lead to reading zeros instead of uninitialized data.
</blockquote></details>

I remember discussing this with @kailun-qin, and I don't remember if we had any particular reason to implement it as it is currently (i.e., "resetting" the callback-args state in the user code). But I agree with @mkow that doing it inside RA-TLS code is less error-prone.

UPDATE: Ok, I think I remembered the logic: this is typically how `errno` is used in C applications, so we wanted to mimic this behavior:
```
errno = 0;
int ret = open();
if (ret == -1) {...check errno...};
```

But I'm preferring @mkow's proposal now.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSeEyM48BJVadq6S6E:-NQUIUT8BN3ezbDrTJ7G:b-h0w017) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this misleading for someone who won't read this code within the context of this PR and the corresponding issue? These are not really arguments for the verification, rather a struct where the verification can place the extended results of the verification.
</blockquote></details>

Probably the name `ra_tls_verify_callback_args` is bad? Maybe it should be more like `ra_tls_verify_callback_info` or even `ra_tls_verify_callback_results`?

The reason for `callback arguments` is because that's how mbedTLS calls it.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSh5VfEwCdMtV-ZHqh:-NQUInZO7CF7sMaJ3NIG:b-ubd37d) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any reason for not making this an enum? You wouldn't need to explain anything in the comment then.
</blockquote></details>

I guess no reason :) I'm also fine with an enum.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQUIvFAC-wtgRnQ8ohs:b-eu0pnm) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of this?
</blockquote></details>

To make it clear that we expect this inner object to be 128-byte-sized? Like, if some external plugin would want to use this struct, the plugin must know how many bytes it can put here.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 240 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShpc66xhxh2O6nouP:-NQUJEc52TzrqLJKdU9Q:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls_verify_common.c#L240)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe we should also print a deprecation warning here? Otherwise people will never notice.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-03-16 10:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 4 of 10 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 373 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSZ3RfDIZHSKRyCwg6:-NQdjOqyA7QR2360woCO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/CI-Examples/ra-tls-mbedtls/src/client.c#L373)):*
> ```C
>     fflush(stdout);
> 
>     /* nullify callback args as it will get populated during TLS handshake */
> ```

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 374 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQScdij51Qyh4U5qOeu:-NQdjPon54AHKn-4J9bV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/CI-Examples/ra-tls-mbedtls/src/client.c#L374)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> UPDATE: Ok, I think I remembered the logic: this is typically how `errno` is used in C applications, so we wanted to mimic this behavior:

This is not how you _typically_ use `errno`, it's a workaround for shitty APIs which doesn't always set `errno` and you can't deduce whether it's being set by looking at the return value. Also, overall, this is not a great interface which we should mimic...
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSeEyM48BJVadq6S6E:-NQdjRk04WdXgPchNjQ6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like `ra_tls_verify_callback_results`.

> The reason for `callback arguments` is because that's how mbedTLS calls it.

Yes, because the intended and the most common way to use them is to pass some arguments to the callback, which is _not_ what we are doing :)
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSh5VfEwCdMtV-ZHqh:-NQdjTfJ54W0aIkq9hPL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess no reason :) I'm also fine with an enum.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 49 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShHLG41bAjmO0QzCs:-NQdjrHh9M7E2ijvZtUr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L49)):*
> ```objc
> struct ra_tls_verify_callback_args {
>     int attestation_scheme;   /* see macros RA_TLS_ATTESTATION_SCHEME_ */
>     ra_tls_err_loc_t err_loc; /* error location in RA-TLS */
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQdk54s7hdH68tuRLpJ:b-dtf3j) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmmmm, not sure if I like this... Is writing to this struct actually pluginable in the current code?

Also, if we decide to keep it, we really need a comment explaining why there's a random unused struct here.
</blockquote></details>

I'm neutral on this. Added a comment for now.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 240 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShpc66xhxh2O6nouP:-NQdo-BJ0rK0rKdhRztf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls_verify_common.c#L240)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_epid.c` line 230 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQSja2sDqrRgot1OuVa:-NQdkWWs2Xsp7060bOke:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls_verify_epid.c#L230)):*
> ```C
>                                           allow_outdated_tcb, nonce,
>                                           ias_pub_key_pem,
>                                           (args) ? &args->epid.ias_enclave_quote_status : NULL,
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-03-16 14:29 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 148 at r6](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQeoIasCvr774Icp23d:-NQeoIasCvr774Icp23e:b-ms9pwa) ([raw file](https://github.com/gramineproject/gramine/blob/945e66f9015164cf057a103e4e59b5e2959684ac/CI-Examples/ra-tls-mbedtls/src/client.c#L148)):*
> ```C
>     void* ra_tls_verify_lib                                          = NULL;
>     ra_tls_verify_callback_extended_der_f                            = NULL;
>     ra_tls_set_measurement_callback_f                                = NULL;
> ```

This looks weird now, I would move these `= NULL` close to variables.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQVsJsB-LN7iPmSK-ei:b-bp3q5r) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
> Is writing to this struct actually pluginable in the current code?

Yes, because plugins provide their own `ra_tls_verify_callback()` function implementation in the `ra_tls_verify_xxx.c` file. So RA-TLS plugins have control over the struct.

But unfortunately, there is no way to use the plugins in Secret Prov code (where the struct is simply printed out for additional info). But I think that's ok since Secret Prov is close to being unusable...
___
*[`tools/sgx/ra-tls/ra_tls.h` line 50 at r6](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQeoBhP3zpDDlq4E-jr:-NQeoBhP3zpDDlq4E-js:bbkm9n6) ([raw file](https://github.com/gramineproject/gramine/blob/945e66f9015164cf057a103e4e59b5e2959684ac/tools/sgx/ra-tls/ra_tls.h#L50)):*
> ```objc
>  * provided by the application/user) */
> struct ra_tls_verify_callback_results {
>     ra_tls_attestation_scheme_t attestation_scheme;   /* attestation scheme of RA-TLS */
> ```

The comment looks useless, I would remove it


<!-- Sent from Reviewable.io -->

2023-03-16 23:46 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 148 at r6](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQeoIasCvr774Icp23d:-NQgnVUS3FU9aMadDEwv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/945e66f9015164cf057a103e4e59b5e2959684ac/CI-Examples/ra-tls-mbedtls/src/client.c#L148)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks weird now, I would move these `= NULL` close to variables.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 50 at r6](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQeoBhP3zpDDlq4E-jr:-NQgngF7D15jzYWCJsEh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/945e66f9015164cf057a103e4e59b5e2959684ac/tools/sgx/ra-tls/ra_tls.h#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment looks useless, I would remove it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 01:39 UTC, mkow requested changes
> Reviewed 4 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @oshogbo)

___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQhCir63FCq2SveWzCv):*
This will need an update (and the one-liner)



_Code quote:_
```
ra_tls_verify_callback_args
```
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQh9rtZAqCiXfIS0Yul:br4tvai) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
> this inner object is expected to be 128-byte-sized

That actually doesn't guarantee this :) It should say "at least 128-byte"
___
*[`tools/sgx/ra-tls/ra_tls.h` line 34 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQh6zom9943fBt7NISj:-NQh6zom9943fBt7NISk:b-wortue) ([raw file](https://github.com/gramineproject/gramine/blob/c3cff36a21f6dc1ab619b6c4298bf0cf7b09ccc2/tools/sgx/ra-tls/ra_tls.h#L34)):*
> ```objc
>     ATTESTATION_SCHEME_UNKNOWN = 0,
>     ATTESTATION_SCHEME_EPID    = 1,
>     ATTESTATION_SCHEME_DCAP    = 2,
> ```

These are still in the global namespace unfortunately, so please re-add the `RA_TLS_` prefix.


<!-- Sent from Reviewable.io -->

2023-03-17 03:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 5 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQhCir63FCq2SveWzCv):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will need an update (and the one-liner)
</blockquote></details>

Pls help update during rebase, thanks!
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQhbDmJ6V3ECT4hCvfK:b-180hif) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
> That actually doesn't guarantee this :) It should say "at least 128-byte"

Yep no guarantee indeed - but that's what "expected to be" implies I guess ;)
___
*[`tools/sgx/ra-tls/ra_tls.h` line 34 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQh6zom9943fBt7NISj:-NQh_I3x9wxtBEreGiFW:b-i4u593) ([raw file](https://github.com/gramineproject/gramine/blob/c3cff36a21f6dc1ab619b6c4298bf0cf7b09ccc2/tools/sgx/ra-tls/ra_tls.h#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These are still in the global namespace unfortunately, so please re-add the `RA_TLS_` prefix.
</blockquote></details>

Indeed... I was thinking about this actually. Updated.


<!-- Sent from Reviewable.io -->

2023-03-17 03:59 UTC, mkow requested changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @oshogbo)

___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQhCir63FCq2SveWzCv):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls help update during rebase, thanks!
</blockquote></details>

Ok, will do.
___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQhhSl081ar9Y4emP7m:b-liis0a) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> That actually doesn't guarantee this :) It should say "at least 128-byte"

Yep no guarantee indeed - but that's what "expected to be" implies I guess ;)
</blockquote></details>

Hmm, ok, I read this comment slightly differently... Also, it still doesn't explain why would you need such a guarantee. I'd instead just say that this is a buffer which could be used by plugins to store data specific to their implementations, it will be clear then what's it's purpose and intended usage.


<!-- Sent from Reviewable.io -->

2023-03-17 09:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 9 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQiqzd84wvM7oVt82U-:brg8lco) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, ok, I read this comment slightly differently... Also, it still doesn't explain why would you need such a guarantee. I'd instead just say that this is a buffer which could be used by plugins to store data specific to their implementations, it will be clear then what's it's purpose and intended usage.
</blockquote></details>

OK, updated the comment.


<!-- Sent from Reviewable.io -->

2023-03-17 09:32 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQiuK9c1sV_YPWmWnD5:bmi55g3) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

OK, updated the comment.
</blockquote></details>

The new comment looks good to me.


<!-- Sent from Reviewable.io -->

2023-03-17 13:23 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`tools/sgx/ra-tls/ra_tls.h` line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQShWVq8p8AVuotKSz8:-NQjjI4_9sDugdko6YMP:b-kp5a0r) ([raw file](https://github.com/gramineproject/gramine/blob/34354ada5eac90b66683cd05f9fc07e5c8a83c39/tools/sgx/ra-tls/ra_tls.h#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The new comment looks good to me.
</blockquote></details>

Yup, now it's clear what's it purpose :)


<!-- Sent from Reviewable.io -->

2023-03-17 13:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: 8 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1215#-NPvnHyD1sgcilUhDliY:-NQjnR8G4Et3ubzrMFHg:bvda8ei) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- Tested `ra-tls-mbedtls` example:
```
~/gramineproject/gramine/CI-Examples/ra-tls-mbedtls$ RA_TLS_EPID_API_KEY=<bla> ./client epid                                                                                                            

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok                                                                                      
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok                                                                                      
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake...IAS report: signature verified correctly                                               ias_verify_report_extract_quote: IAS report: quote status is not OK (GROUP_OUT_OF_DATE)
  ! mbedtls_ssl_handshake returned -0x3000
  ! ra_tls_verify_callback_args:
    attestation_scheme=1, err_loc=3,
    epid.ias_enclave_quote_status=GROUP_OUT_OF_DATE

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed
```

- Tested `ra-tls-secretprov` example:
```
~/gramineproject/gramine/CI-Examples/ra-tls-secret-prov/secret_prov_pf$ RA_TLS_EPID_API_KEY=<bla> ./server_epid wrap_key

--- Reading the master key for encrypted files from 'wrap_key' ---
--- Starting the Secret Provisioning server on port 4433 ---

IAS report: signature verified correctly
ias_verify_report_extract_quote: IAS report: quote status is not OK (GROUP_OUT_OF_DATE)
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
client_connection: ra_tls_verify_callback_args:
    attestation_scheme=1, err_loc=3,
client_connection:     epid.ias_enclave_quote_status=GROUP_OUT_OF_DATE
```

Everything seems to work! I'm unblocking.
</blockquote></details>

Squashed and rebased, thanks!

___
___
*[`-- commits` line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/1215#-NQhCir63FCq2SveWzCv):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, will do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 13:51 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-03-17 14:09 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1215)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-03-17 14:49 UTC, merged