[PAL/Linux-SGX] Mitigate CVE-2022-21166 aka INTEL-SA-00615
gramineproject/gramine pull request #1237
Opened 2023-03-17 07:54 UTC by kailun-qin

A malicious OS could map MMIO memory into the untrusted memory space of an enclave application (which can be used for e.g. parameter passing to/from ECALLs and OCALLs, or any external buffers that an enclave might use to communicate with its application). Then when the enclave writes to this memory, it could unintentionally propagate the stale (secret) data in its core fill buffers into the uncore, where it could later be extracted by malicious software.

Naturally aligned 8-byte writes are not affected by this vulnerability, so as SW mitigation, this commit makes all untrusted memory writes 8-byte wide and naturally aligned.

There is a side effect introduced to the Exitless (aka RPC-threads aka Switchless) feature by the fix of CVE-2022-21233 aka INTEL-SA-00657, which marks the feature as insecure and didn't fix it due to its complex usage of the untrusted memory. We assume the same for this fix.

Fixes https://github.com/gramineproject/gramine/issues/1235.

2023-03-17 13:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_api.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQiwmwP6DQfEXbFriW3:-NQj8aXMBoJuE7nMujwN:b-gke1hm) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_api.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not blocking, but this name is hard to understand (it should be read as "copy to untrusted memory the following value").

My suggestion would be `COPY_VALUE_TO_UNTRUSTED()`, but let's wait if anyone else has a strong opinion. If not, then I suggest to keep the current name.
</blockquote></details>

The proposed name looks better, will update.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQizTDl70AK6lXN2iUi:-NQj8Hi2EbHdkKx3Awma:bnjh14n) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_framework.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unfortunately, this whole PR looks wrong.

Consider what happened in the previous code, where we protected reads of untrusted memory from within the enclave:
1. `src` was the untrusted memory
2. `dest` was the enclave memory
3. The previous code correctly did the copying in two steps:
   1. First copy an 8B chunk from aligned-down `src` (untrusted memory) into temp var `prefix_val` (in-enclave) -- for this we must use the safe `copy_u64s()` func
   2. Then copy enclave-to-enclave, from `prefix_val` to `dest` -- for this we can use the unsafe `memcpy()` func

Now consider what happens with your new code, and the case of protected writes from enclave to untrusted memory:
1. `src` is the enclave memory
2. `dest` is the untrusted memory
3. Your new code does the copying in two steps:
   1. First copy an 8B chunk from aligned-down `src` (in-enclave) into temp var `prefix_val` (in-enclave) -- you could use an unsafe `memcpy()` here but you're using `copy_u64s()`
    2. Then copy enclave-to-untrusted, from `prefix_val` to `dest` -- for this you **must use the safe `copy_u64s()` func, but you're **wrongly using unsafe `memcpy()`**

---

I think you have no way but to write a similar function as `sgx_copy_to_enclave_verified()`, but with the order of `memcpy()` and `copy_u64s()` flipped.

Also, I would some quick comments about the usage of these two functions -- so that people in the future won't do the same mistake as you did now.
</blockquote></details>

Ah... So stupid! I did not audit the original function carefully (I made blind assumptions that it works safely as a whole).


<!-- Sent from Reviewable.io -->

2023-03-17 14:50 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_api.h` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQixJrH8EODGlezmDRQ:-NQk1xh33ygTMGxIVQMz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_api.h#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no reason to take `src_val` in parentheses, so you can just write the second arg as `&src_val`.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 125 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQiy5z-9w3Z4xLhzaM7:-NQk1zsdA7DSxkI1-bF3:bwd8vv8) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_framework.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rewrap to 100 chars per line
</blockquote></details>

Not relevant any more.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQizTDl70AK6lXN2iUi:-NQk21Kr-kuZXbKi3goX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_framework.c#L165)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Ah... So stupid! I did not audit the original function carefully (I made blind assumptions that it works safely as a whole).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 189 at r1](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQj-Zo-1NPHv81G4vHU:-NQk22LuDVD7WhFYnZNb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a79a60895adacc9e56c1df081537a819b4e0b026/pal/src/host/linux-sgx/enclave_framework.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, same **unsafe problem** as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 09:33 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyMN7t-5NBPoRq09Qf:-NQyMN7t-5NBPoRq09Qg:b-c1sv9c) (no related file):*
Looks good to me now!

___
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NQyL_Py2GL35AlwFDu4:b-3iu2nb) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
> ```C
>         copy_u64s_from_untrusted(prefix_val, (char*)uptr - prefix_misalignment, /*count=*/1);
>         memcpy(prefix_val + prefix_misalignment, ptr, copy_len);
>         copy_u64s_to_untrusted((char*)uptr - prefix_misalignment, prefix_val, /*count=*/1);
> ```

Ok, this part is a bit tricky: to not overwrite the first bytes in untrusted memory (which are not covered by the copied-from-enclave data), we must first copy these untrusted must-not-be-overwritten bytes together with the to-be-overwritten bytes inside of the temporary var `prefix_val`, then do a `memcpy()` on the latter bytes, and then write back from enclave to untrusted the resulting temporary var.

I first thought of adding a comment about this trick, but then I couldn't come up with a good simple wording. So I think we should keep the code as-is -- a thoughtful reader will understand what this code does.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyMEQk02c-fCnrx6bz:-NQyMEQk02c-fCnrx6c-:bmi4j9b) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L264)):*
> ```C
>         copy_u64s_from_untrusted(suffix_val, uptr, /*count=*/1);
>         memcpy(suffix_val, ptr, suffix_misalignment);
>         copy_u64s_to_untrusted(uptr, suffix_val, 1);
> ```

Here we have the same situation as I described above. Just a note for other reviewers, no need to modify anything.


<!-- Sent from Reviewable.io -->

2023-03-27 11:56 UTC, mgild commented
Thank you for the work on this issue. How soon will this reach production and are there similar mitigations in gramine for INTEL-SA-00334

2023-03-27 13:35 UTC, mgild commented
I am still looking into the security scope of all syscalls but could the runtime check `sched_getaffinity` be securely used to ensure hyperthreading is disabled for the runtime? Perhaps a manifest setting to check this with documentation pointing to the advisory would be helpful.

2023-03-27 14:14 UTC, mkow requested changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_api.h` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRYCCfX2ELaDV5wJRJa:-NRYCCfYDMNK97OMiahb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_api.h#L35)):*
> ```objc
> #define COPY_VALUE_TO_UNTRUSTED(untrusted_ptr, val) ({                            \
>     __typeof__(*(untrusted_ptr)) src_val = (val);                                 \
>     sgx_copy_from_enclave_verified((untrusted_ptr), &src_val, sizeof(src_val));   \
> ```





_Suggestion:_
```objc
sgx_copy_from_enclave_verified(untrusted_ptr, &src_val, sizeof(src_val));
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NRYL5_b7LXx_2CMCsfw:b-rkbe2j) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, this part is a bit tricky: to not overwrite the first bytes in untrusted memory (which are not covered by the copied-from-enclave data), we must first copy these untrusted must-not-be-overwritten bytes together with the to-be-overwritten bytes inside of the temporary var `prefix_val`, then do a `memcpy()` on the latter bytes, and then write back from enclave to untrusted the resulting temporary var.

I first thought of adding a comment about this trick, but then I couldn't come up with a good simple wording. So I think we should keep the code as-is -- a thoughtful reader will understand what this code does.
</blockquote></details>

Can we actually do that? This could cause a race-condition in the untrusted part: we first read some data placed before the buffer and then a moment later write them back. But this is some other memory and there could be concurrent writes there, which we just undid.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRYM_Rq8CjArGplfg_D:-NRYM_Rq8CjArGplfg_E:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L264)):*
> ```C
>         copy_u64s_from_untrusted(suffix_val, uptr, /*count=*/1);
>         memcpy(suffix_val, ptr, suffix_misalignment);
>         copy_u64s_to_untrusted(uptr, suffix_val, 1);
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-03-27 14:18 UTC, mkow reviewed
It can't, both `sched_getaffinity` and the CPU topology as seen from the inside of the enclave can be lied to by the host. But AFAIR HT state is reflected in the attestation, so you can check it there.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRYQO4oCV5rDpFVp4mv:b-5clpzc)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-03-27 14:44 UTC, dimakuv submitted a review, later dismissed
> But AFAIR HT state is reflected in the attestation, so you can check it there.

Yes, exactly: https://github.com/intel/linux-sgx/issues/340

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRYWEou8KBogZX5Eqi9:bpg7xxi)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NRYWQPR-QJTanNwUU5Q:bd3jrzy) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we actually do that? This could cause a race-condition in the untrusted part: we first read some data placed before the buffer and then a moment later write them back. But this is some other memory and there could be concurrent writes there, which we just undid.
</blockquote></details>

@mkow The only time this function is called is to copy from the enclave to the untrusted stack (afair, actually @kailun-qin could we check this assumption). So since the untrusted stack is per-thread (and signals use a dedicated alternate stack), we are free from data race in the benign case.


<!-- Sent from Reviewable.io -->

2023-03-28 03:55 UTC, kailun-qin reviewed
> I think the official mitigation for LVI was µC update + disabling hyper-threading?

Not exactly. CVE-2020-0551 aka INTEL-SA-00334 aka LVI may require SW-level hardening.

In short, Intel/Microsoft/upstream changed tools for LVI: GCC, Microsoft and LLVM, which include adding an LFENCE after every load. For example in Linux, we'll need GCC 7.3 or later and the patched GNU assembler (the fix was upstreamed to GBU Binutils). For convenience, SGX SDK provided the updated assembler binary along with all the "matching" tools/utilities needed from Binutils (ld, objdump etc.): https://download.01.org/intel-sgx/latest/linux-latest/as.ld.objdump.r4.tar.gz.

Additionally, on top of the above tools, SGX SDK provides several mitigation levels ("no mitigation", "indirects-only mitigation", "full mitigation"). Pls kindly see https://github.com/intel/linux-sgx/blob/d3fd8b45117bb656546cd088acfa16d353b322b4/buildenv.mk#L202-L216 and https://github.com/intel/linux-sgx/blob/d3fd8b45117bb656546cd088acfa16d353b322b4/buildenv.mk#L226-L248 for details.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NR_wwoeD-b_dk0WKeKJ:b-1d0wh3)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/enclave_api.h` line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRYCCfX2ELaDV5wJRJa:-NR_ykis0QRsO5yiheIO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_api.h#L35)):*
> ```objc
> #define COPY_VALUE_TO_UNTRUSTED(untrusted_ptr, val) ({                            \
>     __typeof__(*(untrusted_ptr)) src_val = (val);                                 \
>     sgx_copy_from_enclave_verified((untrusted_ptr), &src_val, sizeof(src_val));   \
> ```

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NR_yqlq8Wl834WU4aER:b6v1tfw) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
> The only time this function is called is to copy from the enclave to the untrusted stack (afair, actually @kailun-qin could we check this assumption)

Yes, most of the references of this function are copying to the untrusted stack for OCALL args (e.g. allocated via `sgx_alloc_on_ustack_aligned()`). The only concern might be here: https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_events.c#L27-L59. But since it's guaranteed with atomicity by the lock. I think it should be fine.

Pls kindly help double check.

> Can we actually do that? This could cause a race-condition in the untrusted part: we first read some data placed before the buffer and then a moment later write them back. But this is some other memory and there could be concurrent writes there, which we just undid.

Yeah, I had exatly the same concerns while making these changes. But I made the same assumption of the per-thread ustack as @dimakuv mentioned.


<!-- Sent from Reviewable.io -->

2023-03-28 07:51 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NRb7ZrAC4wFbyKAbm8x:b-p9sc4u) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> The only time this function is called is to copy from the enclave to the untrusted stack (afair, actually @kailun-qin could we check this assumption)

Yes, most of the references of this function are copying to the untrusted stack for OCALL args (e.g. allocated via `sgx_alloc_on_ustack_aligned()`). The only concern might be here: https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_events.c#L27-L59. But since it's guaranteed with atomicity by the lock. I think it should be fine.

Pls kindly help double check.

> Can we actually do that? This could cause a race-condition in the untrusted part: we first read some data placed before the buffer and then a moment later write them back. But this is some other memory and there could be concurrent writes there, which we just undid.

Yeah, I had exatly the same concerns while making these changes. But I made the same assumption of the per-thread ustack as @dimakuv mentioned.


</blockquote></details>

Agreed with @kailun-qin that these two locations should be safe:
1. Copying to the untrusted stack (as the stack is per-thread, so no data races with other threads/signals)
2. `alloc_untrusted_futex_word()` and `free_untrusted_futex_word()` -- these are protected by a global lock `g_untrusted_page_lock`, so no data races possible

But I found one other vulnerability -- in the `pal_events.c` logic, with futex ints. See my other comment.
___
*[`pal/src/host/linux-sgx/pal_events.c` line 118 at r3](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRb5fZW5mQ6bz9GKe5y:-NRb5fZW5mQ6bz9GKe5z:b-sswtxq) ([raw file](https://github.com/gramineproject/gramine/blob/bda2dc8ef28dcbc3334380dbf5aeda753e462597/pal/src/host/linux-sgx/pal_events.c#L118)):*
> ```C
>     handle->event.signaled = init_signaled;
>     handle->event.auto_clear = auto_clear;
>     __atomic_store_n(handle->event.signaled_untrusted, init_signaled ? 1 : 0, __ATOMIC_RELEASE);
> ```

Oops, looks like we still have a vulnerability in `signaled_untrusted` atomic accesses, like this one.

This is because `signaled_untrusted` is a 4-byte int, and so we perform 4-byte stores. I think we can more or less easily fix it as follows:
1. Change `signaled_untrusted` type to an 8-byte int
2. Change `alloc_untrusted_futex_word()` and `free_untrusted_futex_word()` to allocate 8-byte integers -- note that this will actually simplify the ASan logic (and will be uniform with ASan assumptions)
3. Now the ugly part is that we'll need to change `ocall_futex()` to accept an 8-byte integer, and in the untrusted part, we'll cast this 8-byte integer to a 4-byte int (to be compatible with `futex()` syscall signature).
   - Alternatively, we could keep `ocall_futex()` signature as is and just case the 8-byte integer to a 4-byte int here -- I actually prefer this approach, to touch less parts in the code.
4. We'll need to add VERY VISIBLE comments on why we use 8-byte ints instead of a classic 4-byte int for futexes.

Note that 8-byte ints returned by `alloc_untrusted_futex_word()` are guaranteed to be 8-byte aligned, so we don't need to care about alignment.

@kailun-qin Does that sound reasonable to you? Could you apply such a fix here?


<!-- Sent from Reviewable.io -->

2023-03-28 11:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: 5 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_events.c` line 118 at r3](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRb5fZW5mQ6bz9GKe5y:-NRbzU7R9mGUnWPlzMCK:b-juelf2) ([raw file](https://github.com/gramineproject/gramine/blob/bda2dc8ef28dcbc3334380dbf5aeda753e462597/pal/src/host/linux-sgx/pal_events.c#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, looks like we still have a vulnerability in `signaled_untrusted` atomic accesses, like this one.

This is because `signaled_untrusted` is a 4-byte int, and so we perform 4-byte stores. I think we can more or less easily fix it as follows:
1. Change `signaled_untrusted` type to an 8-byte int
2. Change `alloc_untrusted_futex_word()` and `free_untrusted_futex_word()` to allocate 8-byte integers -- note that this will actually simplify the ASan logic (and will be uniform with ASan assumptions)
3. Now the ugly part is that we'll need to change `ocall_futex()` to accept an 8-byte integer, and in the untrusted part, we'll cast this 8-byte integer to a 4-byte int (to be compatible with `futex()` syscall signature).
   - Alternatively, we could keep `ocall_futex()` signature as is and just case the 8-byte integer to a 4-byte int here -- I actually prefer this approach, to touch less parts in the code.
4. We'll need to add VERY VISIBLE comments on why we use 8-byte ints instead of a classic 4-byte int for futexes.

Note that 8-byte ints returned by `alloc_untrusted_futex_word()` are guaranteed to be 8-byte aligned, so we don't need to care about alignment.

@kailun-qin Does that sound reasonable to you? Could you apply such a fix here?
</blockquote></details>

Good catch! Yes, make sense to me, updated!


<!-- Sent from Reviewable.io -->

2023-03-28 19:48 UTC, mkow reviewed
> Not exactly. CVE-2020-0551 aka INTEL-SA-00334 aka LVI may require SW-level hardening.

> include adding an LFENCE after every load

Ok, now I remember that mitigation. As explained on the call, I think the history behind our LVI mitigation state is that when LVI went public Gramine still wasn't used in production anywhere and we weren't sure when that would happen, so we didn't implement such mitigations (which are inherently temporal, because new CPUs won't have such bugs).
This strategy seems to have worked, because server cores >= ICX were fixed and aren't susceptible to LVI (@kailun-qin: could you post a link here to that table with vulnerable CPUs you posted on the call?).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRcckTs3NxMJPQTS0A5:bbbgasq)* status: 5 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-03-28 20:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NQyL_Py2GL35AlwFDu3:-NRdpQAUEiN_w9HGVOQz:b-auowcv) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/enclave_framework.c#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Agreed with @kailun-qin that these two locations should be safe:
1. Copying to the untrusted stack (as the stack is per-thread, so no data races with other threads/signals)
2. `alloc_untrusted_futex_word()` and `free_untrusted_futex_word()` -- these are protected by a global lock `g_untrusted_page_lock`, so no data races possible

But I found one other vulnerability -- in the `pal_events.c` logic, with futex ints. See my other comment.
</blockquote></details>

Heh, I just wanted to point exactly this thing out, but then read @dimakuv's message :) These CPU bugs are really annoying to workaround...
___
*[`pal/src/host/linux-sgx/pal_events.c` line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRdpsPp-6XaQgMtp-hv:-NRdpsPqDFOtmIzrQ313:b-y3va5k) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/pal_events.c#L50)):*
> ```C
> #ifdef ASAN
>     /* ASAN requires 8-byte aligned addresses, so we need to pad. */
>     g_untrusted_page_next_entry += sizeof(uint32_t);
> ```

Hmm, maybe I'd leave this comment and code, just comment it out or something? Some day in the future we'll be removing this painful mitigation (after all then-supported CPUs will be shipped without this bug) and I can easily imagine breaking ASan here accidentally when doing so :)


<!-- Sent from Reviewable.io -->

2023-03-29 02:32 UTC, kailun-qin reviewed
> This strategy seems to have worked, because server cores >= ICX were fixed and aren't susceptible to LVI (@kailun-qin: could you post a link here to that table with vulnerable CPUs you posted on the call?).

Sure, pls kindly find below the list of affected processors for LVI (2018-2021 tab, Load Value Injection column):
https://www.intel.cn/content/www/cn/zh/developer/topic-technology/software-security-guidance/processors-affected-consolidated-product-cpu-model.html#tab-blade-1-1.

Note that this is an **updated** version of the original list of LVI affected processors (https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/resources/processors-affected-load-value-injection.html) that I posted on the call.

In this latest list, we can clearly find that all series of Ice Lake (i.e., not only Ice Lake client cores in the original list as questioned on the call) and Sapphire Rapids microarchitectures are stated to be **not affected** by CVE-2020-0551/INTEL-SA-00334/LVI.

@mkow @dimakuv We can also follow this latest list to check whether Gramine is susceptible to other vulnerabilites that we may've missed for recent cores (>= ICX).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRf1YfwBWxyWO4txxPp:b-jpkphr)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_events.c` line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRdpsPp-6XaQgMtp-hv:-NRf1WGX-aKcxuzuiLAY:ba2wsx5) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/pal_events.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, maybe I'd leave this comment and code, just comment it out or something? Some day in the future we'll be removing this painful mitigation (after all then-supported CPUs will be shipped without this bug) and I can easily imagine breaking ASan here accidentally when doing so :)
</blockquote></details>

Added back and commented out, done.


<!-- Sent from Reviewable.io -->

2023-03-29 08:04 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/pal_events.c` line 50 at r2](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRdpsPp-6XaQgMtp-hv:-NRgMUqW8FHFdIAYbjym:b-1gqge5) ([raw file](https://github.com/gramineproject/gramine/blob/d092e08451e57c9c18eec0a962c9ac5ed699a0e3/pal/src/host/linux-sgx/pal_events.c#L50)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Added back and commented out, done.
</blockquote></details>

I love the `painful mitigation` in the comment :)
___
*[`pal/src/host/linux-sgx/pal_host.h` line 139 at r5](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRgNjosCQUePBdyhLBH:-NRgNjosCQUePBdyhLBI:bf8x6oj) ([raw file](https://github.com/gramineproject/gramine/blob/d95795372a8ab2a340299e6b87e8d65af7430369/pal/src/host/linux-sgx/pal_host.h#L139)):*
> ```objc
>              * this futex word. This is to mitigate CVE-2022-21166 (INTEL-SA-00615) which requires
>              * all writes to untrusted memory from within the enclave to be done in 8-byte chunks
>              * aligned to 8-bytes boundary.*/
> ```

Please also add a sentence at the end is that "we can safely typecast this 8-byte int to a 4-byte futex word because Intel SGX implies a little-endian CPU".

Basically, we're using this property of little-endian machines: https://en.wikipedia.org/wiki/Endianness#Simplified_access_to_part_of_a_field. And we need to comment about this trick.

Also, add a space before the closing `*/`


<!-- Sent from Reviewable.io -->

2023-03-29 08:15 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_host.h` line 139 at r5](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRgNjosCQUePBdyhLBH:-NRgQI-R0SfWD043dvv9:b-7cqyw6) ([raw file](https://github.com/gramineproject/gramine/blob/d95795372a8ab2a340299e6b87e8d65af7430369/pal/src/host/linux-sgx/pal_host.h#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add a sentence at the end is that "we can safely typecast this 8-byte int to a 4-byte futex word because Intel SGX implies a little-endian CPU".

Basically, we're using this property of little-endian machines: https://en.wikipedia.org/wiki/Endianness#Simplified_access_to_part_of_a_field. And we need to comment about this trick.

Also, add a space before the closing `*/`
</blockquote></details>

Thanks for the reference! Done.


<!-- Sent from Reviewable.io -->

2023-03-29 08:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRgUEsz-YPyOU0jOQtA:-NRgUEsz-YPyOU0jOQtB:b-t08i66) (no related file):*
The change now looks good to me.

___


<!-- Sent from Reviewable.io -->

2023-03-29 12:58 UTC, mkow reviewed
> We can also follow this latest list to check whether Gramine is susceptible to other vulnerabilites that we may've missed for recent cores (>= ICX).

@dimakuv: You're our attestation expert, could you check this? :) I remember that ITL's ICX had some troubles with it.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRhRPZXDR2F48wb_lBN:bk10oaj)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-03-29 13:09 UTC, dimakuv approved these changes
@mkow Not sure I understood. What exactly do you mean by "check this"?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRhTppr7gg8ZL3s0AQW:b-x00moi)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-03-29 13:57 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_events.c` line 55 at r6](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRhQNrp5LOpxY-IBmAO:-NRhe88YEzY-ZlHvulEM:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/84b7c29bac1e6d072f6c3ed50e4013bde07e89ba/pal/src/host/linux-sgx/pal_events.c#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we can fix this during the final rebase
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-29 14:01 UTC, mkow approved these changes
Run an attestation on ICX and SPR and check what the attestation server says about it (i.e. whether it said "software mitigations required for <lits of advisories>".

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237#-:-NRheiIW25SSBKU0D95Q:b-kuqc8b)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-29 16:10 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (Jenkins job actually finished successfully, but this was result wasn't propagated to GitHub for some reason, so let's try to kick the flows again)

2023-03-29 16:31 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-Sanitizers please (same as above)

2023-03-30 01:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRhPX8j2TFnCLTdg23K:-NRk6uInDtwU_TToO9zH:bneogdu) (no related file):*
Thanks for the performance results!

> I think the main reason is using 8-byte-copy instead of rep movsb or AVX.

Maybe we can check this as a follow-up.

___


<!-- Sent from Reviewable.io -->

2023-03-30 07:07 UTC, merged

2023-03-30 16:27 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1237)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1237#-NRhPX8j2TFnCLTdg23K:-NRnKA-CEJtmSJ2uViqM:bq35wop) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Thanks for the performance results!

> I think the main reason is using 8-byte-copy instead of rep movsb or AVX.

Maybe we can check this as a follow-up.

</blockquote></details>

The problem is that AFAIR the advisory didn't say if `rep movsb` is ok or not assuming the addresses are aligned (despite it being the recommended implementation for memcpy) and I'm also not sure about 16 and 32 byte long accesses - I think they are fine, but implementing them would require a non-trivial effort. I.e. it's not that trivial to even check, we'd need to actually implement `memcpy()` using 8-byte and 16/32-byte accesses in assembly.

___


<!-- Sent from Reviewable.io -->

2023-04-17 20:34 UTC, mgild commented
how soon might we see an official release tag including this PR?

2023-04-17 22:45 UTC, mkow commented
We plan to do the next release at the end of May, see https://github.com/gramineproject/gramine/discussions/1278. If you think we should do it earlier then please argue there.

2023-06-09 00:44 UTC, mgild commented
@mkow Was checking in here on the 1.5 release. The benefit of an announced stable release is user confidence in having an azure supported machine with all current advisories mitigated (DCSv3 machines specifically) while still using Gramine.

2023-06-09 01:18 UTC, mkow commented
What do you mean exactly by "announced stable release"? Overall, I'm not sure what you wanted to say :)

btw.: Generally, I'd recommend using Gramine from +/- `master`, it's rather stable (in terms of regressions, we test each PR) and you'll get all the bugfixes sooner.

2023-06-09 02:54 UTC, kailun-qin commented
> Was checking in here on the 1.5 release

@mgild Yes, this fix will be included in the v1.5 release (which will happen soon).

> The benefit of an announced stable release is user confidence in having an azure supported machine with all current advisories mitigated (DCSv3 machines specifically) while still using Gramine.

I think you wanted to state that having a machine with all security advisories applied plus a Gramine release including the security fixes would increase users' confidence from a security perspective? Anyway, as stated, v1.5 will have it.

2023-06-09 02:58 UTC, mgild commented
Great to hear, thanks for the great product