[LibOS] Fix NULL pointer dereference in pseudo fs
gramineproject/gramine pull request #1238
Opened 2023-03-17 11:12 UTC by oshogbo

## Description of the changes 

`inode` in `data` field keep a specific file system data. In the case of pseudo fs it is a `pseudo_node`. However, when a lookup is done, the `dentry` might not be fully initialized. During mount, we are doing a lookup using [do_path_lookupat](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/fs/libos_namei.c#L266):
```c
   struct lookup lookup = {
        .flags = flags,
        .name = name,
        .has_slash = has_slash,
        .dent = dent,
        .link_depth = link_depth,
    };

    /* Main part of the algorithm. Repeatedly call `lookup_enter_dentry`, then `lookup_advance`,
     * until we have finished the path. */

    ret = lookup_enter_dentry(&lookup);
    if (ret < 0)
        goto err;
    while (*lookup.name != '\0') {
        ret = lookup_advance(&lookup);
        if (ret < 0)
            goto err;
        ret = lookup_enter_dentry(&lookup);
        if (ret < 0)
            goto err;
    }
```

For `/proc/net/route`, we first find a `/proc`, which is a pseudo FS. Next, we are doing a lookup for `/proc/net`, which doesn't exists. In this case, `lookup_advance` allocates a new `dentry` (`lookup_adbance` -> `lookup_dcache_or_create` -> `get_new_dentry`). The new `dentry` gets the same mount functions like the parent (`/proc` which is pseudo):
```c
struct libos_dentry* get_new_dentry(struct libos_mount* mount, struct libos_dentry* parent,                                                                                                    
                                    const char* name, size_t name_len) {                               
    ...
    if (mount) {                                                                                       
        get_mount(mount);                                                                              
        dent->mount = mount;                                                                           
    }                                                                                                  
```
And we do another lookup in `/proc/net` for the `route`. Now our `dentry` is `/proc/net`. Which has the same `lookup` function as `/proc` which is a lookup for a `pseudo file`. Now in lookup we use a `data` which is pseudo fs specific. However these data isn't copy while creating a new `dentry`. We ended up with `SEGFAULT`.
```c
static struct pseudo_node* pseudo_find(struct libos_dentry* dent) {                                 
    ...                                                                 
    assert(dent->parent->inode);                                                                       
                                                                                                       
    struct pseudo_node* parent_node = dent->parent->inode->data;                                       
```

The simplest solution is to check in `pseudo file` if the `data` is set. In this case we end up with a valid hierarchy:
```
[pseudo   2] 040555 dr-x        proc/ (pseudo "proc")                                                      
[ synth   2] 040555 dr-x          net/                                                                 
[ synth   2] 040555 dr-x M          route/                                                             
[chroot   1] 100444 -r--              route (chroot "file:/proc/net/route")                         
```
This was generated with `dentry_dump` function.

However we can consider other solutions as well:
- Test if we really need to do a recursive lookup if we haven't found the first node.
- Should we really copy a lookup function from a parent in this case?

Fixes #1101.

## How to test this PR? 

The test is added.

2023-03-20 10:23 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQyRBdl6Nbex5wngpNF:-NQyU1yvDE1nt3VoaeBD:b-tb7zdm) (no related file):*
Oh sorry.
When NULL is returned then the next lookup_entry_dentry/lookup_advance happens, until we find '\0' in the name:
```
    while (*lookup.name != '\0') {
        ret = lookup_advance(&lookup);
       ...
```
This creates all the "shadow" dentry cache (this part I'm not sure, if we really need to create all of these dentry caches).
While all of them fail, we do `mount_fs_at_dentry`, which creates a requested filesystem type:
```
    struct libos_fs* fs = find_fs(params->type);                                                    
    if ((ret = fs->fs_ops->mount(params, &mount_data)) < 0)                                         
        return ret;                                                                                 
```

> Also, I would feel more secure if your test would have at least two levels of pseudo-dirs. E.g. /proc/test/nested/dirs/exec. Currently I have a feeling that this nesting will break somehow?

Done.

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQyPPb_3GZFJlaEBchy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence reads weird. Maybe:
```
`inode::data` field keeps specific file system data.
```
</blockquote></details>

Done.
___
*[`libos/test/regression/open_file.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQyOdZI68zuD0aZnnFS:-NQyUNlN4ycn_-YNiM-r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34517143d94b648cca3955ee1b8a5f2e784b132c/libos/test/regression/open_file.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not:
```
    int fd = CHECK(open(argv[1], O_RDONLY));
    CHECK(close(fd));
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 15:33 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQyRBdl6Nbex5wngpNF:-NQzd33mBis5wizZtUR8:b8ova9x) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Oh sorry.
When NULL is returned then the next lookup_entry_dentry/lookup_advance happens, until we find '\0' in the name:
```
    while (*lookup.name != '\0') {
        ret = lookup_advance(&lookup);
       ...
```
This creates all the "shadow" dentry cache (this part I'm not sure, if we really need to create all of these dentry caches).
While all of them fail, we do `mount_fs_at_dentry`, which creates a requested filesystem type:
```
    struct libos_fs* fs = find_fs(params->type);                                                    
    if ((ret = fs->fs_ops->mount(params, &mount_data)) < 0)                                         
        return ret;                                                                                 
```

> Also, I would feel more secure if your test would have at least two levels of pseudo-dirs. E.g. /proc/test/nested/dirs/exec. Currently I have a feeling that this nesting will break somehow?

Done.
</blockquote></details>

Thanks, I understand the flow now!

___
___
*[`libos/test/regression/open_file.c` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdohq0U9lC6ZFnkwP:-NQzdohq0U9lC6ZFnkwQ:b-se0gfx) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/open_file.c#L21)):*
> ```C
>     CHECK(close(fd));
> 
>     printf("TEST OK\n");
> ```

Could use `puts()`, it adds the newline char automatically. But I don't care much.
___
*[`libos/test/regression/shadow_pseudo_fs.manifest.template` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdtwc0HT5--k9I2Wn:-NQzdtwc0HT5--k9I2Wo:bl8kx4f) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/shadow_pseudo_fs.manifest.template#L7)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib"
> loader.argv = [ "{{ entrypoint }}", "/proc/test/nasted/dirs/exec" ]
> ```

`nested` (typo)
___
*[`libos/test/regression/shadow_pseudo_fs.manifest.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdvbF1fDbMDzJVkD2:-NQzdvbF1fDbMDzJVkD3:bl8kx4f) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/shadow_pseudo_fs.manifest.template#L14)):*
> ```
> 
>   # Let's shadow some file in /proc as it is a pseudo fs.
>   { path = "/proc/test/nasted/dirs/exec", uri = "file:{{ binary_dir }}/{{ entrypoint }}" },
> ```

`nested` (typo)


<!-- Sent from Reviewable.io -->

2023-03-20 15:54 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/open_file.c` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdohq0U9lC6ZFnkwP:-NQziVIo9UgFN3-vORWW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/open_file.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could use `puts()`, it adds the newline char automatically. But I don't care much.
</blockquote></details>

Done.
___
*[`libos/test/regression/shadow_pseudo_fs.manifest.template` line 7 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdtwc0HT5--k9I2Wn:-NQzi_2d0AWC9JXP12wh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/shadow_pseudo_fs.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`nested` (typo)
</blockquote></details>

Done.
___
*[`libos/test/regression/shadow_pseudo_fs.manifest.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gramine/1238#-NQzdvbF1fDbMDzJVkD2:-NQzi_UwCvLudydGXeoD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4be9a813528154ddca6584358f9bb9ad0e24bdf9/libos/test/regression/shadow_pseudo_fs.manifest.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`nested` (typo)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 08:16 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-24 02:00 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238#-:-NRGL8Uy0NsM65hPKl-a:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-03 00:20 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 7 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-03 11:26 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-04-03 13:26 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1238)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-03 13:27 UTC, merged