Updating the documentation so it is consistent with my changes and th…
gramineproject/gramine pull request #1241
Opened 2023-03-17 18:57 UTC by Carteepaul

…e updates from the team.

## Description of the changes 

## How to test this PR? 

The documentation will be rearranged and contain all of the recent updates by the team.

2023-03-20 08:27 UTC, dimakuv commented
@woju @mkow @aneessahib This is a good starting point, but requires some modifications to adhere to our Gramine code style (and fixing typos, etc.). Could we find a volunteer who could do such amending of this PR to our standards?

2023-03-21 09:02 UTC, dimakuv requested changes
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 43 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @Carteepaul)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2JcOu0K4rTsYacmTq):*
This should have a sign-off line with your name and email. And the name and email should correspond to the ones in your GitHub account (you will need to update your GitHub account with this information).

You can browse the commits to see how other people do it: https://github.com/gramineproject/gramine/commits/master
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Jw-G9JdIwrFwFG9i):*
The title should be something like `[Docs] Reorganize documentation`
___
*[`Documentation/attestation.rst` line 485 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K2zF41CnpXOUGkgf:-NR2K2zF41CnpXOUGkgg:b-qyttu7) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/attestation.rst#L485)):*
> ```reStructuredText
>    self-written decoding logic or a standard library function).
> ```

This is a spurious change. Please revert it.
___
*[`Documentation/cloud-deployment.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K6-15jCZ3igKQE2a:-NR2K6-15jCZ3igKQE2b:b61a38p) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/cloud-deployment.rst#L32)):*
> ```reStructuredText
>    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ $(lsb_release -sc) main" \
>    | sudo tee /etc/apt/sources.list.d/gramine.list
>    
> ```

These are spurious changes, please revert them.
___
*[`Documentation/concepts-index.rst` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K9snB_fo5X-b_22Z:-NR2K9snB_fo5X-b_22_:b3ndopv) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/concepts-index.rst#L7)):*
> ```reStructuredText
>    :maxdepth: 1
> 
>    sgx-intro
> ```

Please add a newline here.
___
*[`Documentation/conf.py` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KE0B5Sb8ShV2ciah:-NR2KE0B5Sb8ShV2ciai:bksf2yt) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L50)):*
> ```Python
>     'sphinx.ext.todo',
>     'sphinx_rtd_theme',
>     'sphinx.ext.autosectionlabel',
> ```

Hm, what does this extension do? Do we need to install some additional package to have this extension?
___
*[`Documentation/conf.py` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KK9R98P-Z5ovTio2:-NR2KK9R98P-Z5ovTio3:b-c5hlpf) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L124)):*
> ```Python
>             subprocess.check_call(['doxygen', 'Doxyfile-{}'.format(p)])
> 
> html_css_files=['css/gramine.css']
> ```

Why did you replace it? What's the difference from `app.add_stylesheet`?
___
*[`Documentation/configuration-index.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KSld0t1MOcxlQ93k:-NR2KSld0t1MOcxlQ93l:b9aeooo) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/configuration-index.rst#L12)):*
> ```reStructuredText
>    attestation
>    performance
>    manpages/index.rst
> ```

A bit weird. Why do we have manpages under `Configuration`?
___
*[`Documentation/contributor-index.rst` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KZH74pxC6TzquvXQ:-NR2KZH8BZvfZtkJqLGp:bkgvg8) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L6)):*
> ```reStructuredText
> =======================
> 
> These articles contain helpful material for users who want to contribute to Gramine development. 
> ```

Please remove all trailing whitespaces from everywhere in your PR.
___
*[`Documentation/contributor-index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KbkB8Kqfxax5dc9B:-NR2KbkB8Kqfxax5dc9C:bp4ohhm) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L8)):*
> ```reStructuredText
> These articles contain helpful material for users who want to contribute to Gramine development. 
> 
> :doc:`devel/contributing` - Learn about how to report bugs, security vulnerabilities and perform pull requests. This section contains information for working with the Gramine project.
> ```

All RST documentation in Gramine should be wrapped at 80 chars per line. Please reformat your documents so.
___
*[`Documentation/curated-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KqDc-7v-d6N9w1tI:-NR2KqDc-7v-d6N9w1tJ:b-dpbm3m) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/curated-installation.rst#L4)):*
> ```reStructuredText
> 
> Ready-made confidential protected images
> ======================================
> ```

You must append two more `=` chars
___
*[`Documentation/custom-installation.rst` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2LG80A7WCDx5eFHUa:-NR2LG80A7WCDx5eFHUb:b-mr24s5) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/custom-installation.rst#L3)):*
> ```reStructuredText
> .. _custom_installation
> 
> Install Gramine on your server
> ```

I don't like the term `server`. I would prefer one of these:
- `system`
- `platform`
___
*[`Documentation/custom-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KzOp8jP3Pz5c5Tna:-NR2KzOp8jP3Pz5c5Tnb:bhbrund) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/custom-installation.rst#L4)):*
> ```reStructuredText
> 
> Install Gramine on your server
> =====================================
> ```

In RST, the correct formatting is to have as many `=`, `-`, etc. characters under the title as there are characters in the title. In this particular case, it should be like this:
```
Install Gramine on your server
==============================
```

Ditto for all other places in your PR.
___
*[`Documentation/developer-index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2LUixAZwwNErR73oX:-NR2LUixAZwwNErR73oY:bb5na9k) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/developer-index.rst#L14)):*
> ```reStructuredText
>    devel/new-syscall
>    pal/host-abi
>    python/api
> ```

I would rearrange in the order of usefulness:
```
   python/api
   devel/debugging
   devel/new-syscall
   pal/host-abi
```
___
*[`Documentation/environment-setup.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Lj3x42MuhnxEJO8F:-NR2Lj3x42MuhnxEJO8G:b-ew38w4) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/environment-setup.rst#L4)):*
> ```reStructuredText
> 
> Set up the Gramine environment
> -------------------------------
> ```

Please add a new empty line after this one.
___
*[`Documentation/environment-setup.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Lor928htOC0W11N1:-NR2Lor928htOC0W11N2:b-l6yc3h) ([r [...]

2023-04-12 19:16 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 12 of 36 files reviewed, 49 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/cloud-deployment.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K6-15jCZ3igKQE2a:-NSl0Td_8GlT7nOEl0HZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/cloud-deployment.rst#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These are spurious changes, please revert them.
</blockquote></details>

Done.
___
*[`Documentation/concepts-index.rst` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K9snB_fo5X-b_22Z:-NSCxWw5Ewkg5Ol5kR2k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/concepts-index.rst#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline here.
</blockquote></details>

Done.
___
*[`Documentation/conf.py` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NSlCu_L2tRkNnUrV_tM:-NSlCu_L2tRkNnUrV_tN:bymwi8t) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L48)):*
> ```Python
>     'sphinx.ext.intersphinx',
>     'sphinx.ext.napoleon',
>     'sphinx.ext.todo',
> ```

This extension enables the writer to refer to section headings throughout the document. No additional packages are needed. 
___
*[`Documentation/conf.py` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KE0B5Sb8ShV2ciah:-NSlDYAV6npql0wOKM4a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, what does this extension do? Do we need to install some additional package to have this extension?
</blockquote></details>

Done.
___
*[`Documentation/conf.py` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KK9R98P-Z5ovTio2:-NSqfhaW4NsMpBFgRG5l:bmag3hf) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you replace it? What's the difference from `app.add_stylesheet`?
</blockquote></details>

@deb-intel Is there a particular reason for doing that{
___
*[`Documentation/configuration-index.rst` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KSld0t1MOcxlQ93k:-NSqkjUm624mL0WVqj3x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/configuration-index.rst#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A bit weird. Why do we have manpages under `Configuration`?
</blockquote></details>

Done.
___
*[`Documentation/configuration-index.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1241#-NSqkdGI7iUVoFwPqB-l:-NSqkdGJ-puu68s-CgJ1:b-1rem1c) ([raw file](https://github.com/gramineproject/gramine/blob/a50d9b21cd4b63c8aa162d88de88bbec0fd70497/Documentation/configuration-index.rst#L11)):*
> ```reStructuredText
>    manifest-syntax
>    attestation
>    performance
> ```

I moved the manpages to their own section.
___
*[`Documentation/contributor-index.rst` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KZH74pxC6TzquvXQ:-NSC22bm4hl6dr_M2OPv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove all trailing whitespaces from everywhere in your PR.
</blockquote></details>

Done.



_Code quote (from Documentation/cloud-deployment.rst):_
```reStructuredText
···
```
___
*[`Documentation/contributor-index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KbkB8Kqfxax5dc9B:-NSC25HC8kSVDBfNBb8O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All RST documentation in Gramine should be wrapped at 80 chars per line. Please reformat your documents so.
</blockquote></details>

Done.
___
*[`Documentation/curated-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KqDc-7v-d6N9w1tI:-NSC3B2U8Ve0FXYE-cC3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/curated-installation.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You must append two more `=` chars
</blockquote></details>

Done.



_Code quote (from Documentation/contributor-index.rst):_
```reStructuredText
his page describes the knowledge 
```
___
*[`Documentation/custom-installation.rst` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2LG80A7WCDx5eFHUa:-NSC3QMQCqMpAbQ_qgjT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/custom-installation.rst#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the term `server`. I would prefer one of these:
- `system`
- `platform`
</blockquote></details>

Done.
___
*[`Documentation/custom-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KzOp8jP3Pz5c5Tna:-NS8O-zE5LuZXyYb9llf:b-ampq2l) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/custom-installation.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In RST, the correct formatting is to have as many `=`, `-`, etc. characters under the title as there are characters in the title. In this particular case, it should be like this:
```
Install Gramine on your server
==============================
```

Ditto for all other places in your PR.
</blockquote></details>

I fixed this for all the instances I came across. 
___
*[`Documentation/developer-index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2LUixAZwwNErR73oX:-NS8OK4I17mFk8JQA-M_:b-puwc4x) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/developer-index.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would rearrange in the order of usefulness:
```
   python/api
   devel/debugging
   devel/new-syscall
   pal/host-abi
```
</blockquote></details>

I rearranged this list in the order you suggested.
___
*[`Documentation/environment-setup.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Lj3x42MuhnxEJO8F:-NS8OT7F9clQzGSkyN2B:b-nz96ls) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/environment-setup.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a new empty line after this one.
</blockquote></details>

I added a the line you asked for. 
___
*[`Documentation/environment-setup.rst` line 32 at r1](https://reviewable.io/reviews/gr [...]

2023-04-12 19:50 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 12 of 36 files reviewed, 49 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2MsPC3QgJ5Vb2ypl9:-NSqvTWKEi9gnFPYeId0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/manifest-syntax.rst#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert all changes in this file. They look accidental.
</blockquote></details>

Done.
___
*[`Documentation/requirements.txt` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Nrq6Eu-XCuG7jRqo:-NSr-DCV46r8iP5ER3fW:b9kwsgh) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How could we ask Deb then?
</blockquote></details>

@deb-intel Why did we update the requirements?


<!-- Sent from Reviewable.io -->

2023-04-17 13:10 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 12 of 36 files reviewed, 48 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/configuration-index.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1241#-NSqkdGI7iUVoFwPqB-l:-NTEJtj32UVV7sl5NUPo:bozkit1) ([raw file](https://github.com/gramineproject/gramine/blob/a50d9b21cd4b63c8aa162d88de88bbec0fd70497/Documentation/configuration-index.rst#L11)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

I moved the manpages to their own section.
</blockquote></details>

I moved the manpages here because I thought having anything to do with help should be in the same section. In prior versions of the documentation, manpages had their own section. It seemed out of place. I moved the man pages to the bottom of the Table of Contents on the side so it would be similar to how it was before I reorganized the documentation. 


<!-- Sent from Reviewable.io -->

2023-04-17 13:11 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 12 of 36 files reviewed, 48 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/requirements.txt` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Nrq6Eu-XCuG7jRqo:-NTEKdDgBTU90WJ0pGhe:b48vet9) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

@deb-intel Why did we update the requirements?
</blockquote></details>

I followed up with Deb on this last week, 4/12. She will get back to me this week. 


<!-- Sent from Reviewable.io -->

2023-04-18 00:56 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 8 of 36 files reviewed, 48 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @BFuhry, @deb-intel, and @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Jw-G9JdIwrFwFG9i):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The title should be something like `[Docs] Reorganize documentation`
</blockquote></details>

Done. I renamed the PR to [Doc] Reorganized Documentation
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2bP0B1avcR5M2eR5x):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

Please also include Deb Taylor in the commit message. She played a vital role in the process and did many of the changes. Potentially, her sign-off would also be needed/wanted.
</blockquote></details>

Done. Deb has been included in this process.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2JcOu0K4rTsYacmTq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should have a sign-off line with your name and email. And the name and email should correspond to the ones in your GitHub account (you will need to update your GitHub account with this information).

You can browse the commits to see how other people do it: https://github.com/gramineproject/gramine/commits/master
</blockquote></details>

I reviewed these examples. I renamed the commit and will include a sign-off line in each future commit.
___
*[`Documentation/cloud-deployment.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K6-15jCZ3igKQE2a:-NTG_QNr2xyZbJHFQh3Q:b8tric0) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/cloud-deployment.rst#L32)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I reverted these commits.
___
*[`Documentation/concepts-index.rst` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2K9snB_fo5X-b_22Z:-NTGaApN5LzTF66maJyP:b-yv1wdd) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/concepts-index.rst#L7)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I added a new line.
___
*[`Documentation/conf.py` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KE0B5Sb8ShV2ciah:-NTGaHn3CCDkPpaehFTg:b-6j1nqf) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L50)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This extension enables you to reference a section using its title. We aren't using this, so I deleted it. 
___
*[`Documentation/conf.py` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KK9R98P-Z5ovTio2:-NTGjMdu3rErATwxERU1:b-vxhuyd) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L124)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

@deb-intel Is there a particular reason for doing that{
</blockquote></details>

I'm reaching out to Deb for an answer.
___
*[`Documentation/contributor-index.rst` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KZH74pxC6TzquvXQ:-NTGjZi2550dGiqkqNxH:bonb6jw) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L6)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Benny helped me configure VSCode to recognize unneeded white spaces. I have gone through all of the files to check for trailing whitespace and to check that each file is limited to 80 characters per line. 
___
*[`Documentation/contributor-index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KbkB8Kqfxax5dc9B:-NTGjwZQ8jfAWwkaYUQS:b-hlr24h) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/contributor-index.rst#L8)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I have reviewed all the files to check that each is limited to 80 characters per line. 
___
*[`Documentation/curated-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KqDc-7v-d6N9w1tI:-NTGkDs05hVhKVE3C6nU:b-f05xbl) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/curated-installation.rst#L4)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I have gone through each file to check that the heading markers are equal to the length of the heading. 
___
*[`Documentation/custom-installation.rst` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2LG80A7WCDx5eFHUa:-NTGkOWT-IlF2TR6jqKG:b-ac92) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/custom-installation.rst#L3)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I replace "server" with "system." 
___
*[`Documentation/gramine-users.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2M3681fJY8bR-28li:-NTGkcalCzBrM-3l2ivE:bdudtaa) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/gramine-users.rst#L4)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I reverted the changes in this file. 
___
*[`Documentation/Installation-index.rst` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2MDNK8jw3ofY24D7S:-NTGkgKOEQ5yx_-bE9O5:b-9i0y3l) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/Installation-index.rst#L8)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I removed the two empty lines. 
___
*[`Documentation/manifest-syntax.rst` line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2MsPC3QgJ5Vb2ypl9:-NTGntvC3SVZszWU8cX3:bgt0k1k) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/manifest-syntax.rst#L97)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I reverted all these changes. 
___
*[`Documentation/performance.rst` line 184 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2MyeO4g1HiylbASEC:-NTGpGvI5TpWOI2k6oFB:b9pgsrs) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/performance.rst#L184)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I reverted all these changes.
___
*[`Documentation/prerequisites.rst` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2NRaC1an79w1kWWNA:-NTGpLxeDDcUWjuv23AJ:bssbpqv) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa9 [...]

2023-04-18 21:12 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 4 of 38 files reviewed, 47 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @deb-intel and @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Jw-G9JdIwrFwFG9i):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Done. I renamed the PR to [Doc] Reorganized Documentation
</blockquote></details>

@dimakuv Before or during the merge, please include Deb Tyler (@deb-intel) in the PR message. 
___
*[`Documentation/manpages/index.rst` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2OZKS3QdggHD-KTdM:-NTLAM6T18VSFBgGpvem:b-z8bto6) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/manpages/index.rst#L9)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

I changed the "maxdepth:" to 1 to make it consistent with the rest of the documentation.
</blockquote></details>

@Carteepaul Please check if this change is still part of the repo as mist of your last changes were lost


<!-- Sent from Reviewable.io -->

2023-04-19 14:58 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 4 of 38 files reviewed, 46 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/manpages/index.rst` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2OZKS3QdggHD-KTdM:-NTP0BZz-sEYlUI4-ZS9:b-pgyzi1) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/manpages/index.rst#L9)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@Carteepaul Please check if this change is still part of the repo as mist of your last changes were lost
</blockquote></details>

@deb-intel  This change is still in the file. 


<!-- Sent from Reviewable.io -->

2023-05-03 11:38 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 20 of 38 files reviewed, 56 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul, @deb-intel, and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTrCXkH28LmkCTwjiNn:-NUW-p2773AGzLJCGTnw:b-tug4lf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there any website where we can see the rendering of this new version of documentation?

Is it this one: https://carteepaul.github.io/GramineTest/index.html ?

I didn't find manpages on that page.
</blockquote></details>

A rendered version can be found under: https://carteepaul.github.io/gramine/

You were right, the manpages were missing in the menu. I added the corresponding index.

___
___
*[`Documentation/cloud-deployment.rst` line 43 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr4Wbx5Ow3ksRvixH8:-NUW16-77tnLzKHn3Nbc:b-ojay0q) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/cloud-deployment.rst#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to remove the trailing `::`

Also, maybe put this sentence in brackets?
</blockquote></details>

@dimakuv Which sentence do you want in brackets and why?
___
*[`Documentation/concepts-index.rst` line 8 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr4gWDBl-2mo4i-HRF:-NUW1I7MBJpH_8prbjnm:b-7rl0kd) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/concepts-index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are three trailing spaces here now.
</blockquote></details>

done
___
*[`Documentation/configuration-index.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1241#-NSqkdGI7iUVoFwPqB-l:-NUWOnpl0lsZ3aNKzkMg:b-dzc1u7) ([raw file](https://github.com/gramineproject/gramine/blob/a50d9b21cd4b63c8aa162d88de88bbec0fd70497/Documentation/configuration-index.rst#L11)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

I moved the manpages here because I thought having anything to do with help should be in the same section. In prior versions of the documentation, manpages had their own section. It seemed out of place. I moved the man pages to the bottom of the Table of Contents on the side so it would be similar to how it was before I reorganized the documentation. 
</blockquote></details>

@dimakuv @Carteepaul This page is not linked from anywhere. Does it make any sense? I assume it should be removed
___
*[`Documentation/contributor-index.rst` line 3 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUW3TDq2wu0LgM88-zt:-NUW3TDq2wu0LgM88-zu:b-dzc1u7) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/contributor-index.rst#L3)):*
> ```reStructuredText
> .. _contributor_index
> 
> Contribution Guidelines
> ```

@dimakuv @Carteepaul This page is not linked from anywhere. Does it make any sense? I assume it should be removed
___
*[`Documentation/contributor-index.rst` line 6 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr55u_BAuwqI28NTKG:-NUW1hK756cWeiJTMjpG:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/contributor-index.rst#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line is not wrapped to 80 chars per line.
</blockquote></details>

done
___
*[`Documentation/contributor-index.rst` line 28 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5CiB5d-dbY8Rwd3A:-NUW1ioo93RtpYGO2Tuf:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/contributor-index.rst#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need to add a newline symbol.
</blockquote></details>

done
___
*[`Documentation/custom-installation.rst` line 13 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5SkSEa6OPrTRZTv3:-NUW1oRJ4wBb7kvYonDz:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have only one empty line between different sections in our docs. So please remove one line here.
</blockquote></details>

Done
___
*[`Documentation/custom-installation.rst` line 22 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5ZigBB250rbvwlU3:-NUW2Nli7II6HQe0CzuQ:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Cloud cloud`?
</blockquote></details>

Done
___
*[`Documentation/custom-installation.rst` line 27 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5kNX3CNPRr2m6Pc4:-NUW2Tj-6DxeurYaseTc:bigc2tr) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be moved to under `Gramine Docker image` section?
</blockquote></details>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere and the content is present on other pages
___
*[`Documentation/custom-installation.rst` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5tXg7NRWvBFY2IP6:-NUW6kpO-906KtiockcD:bigc2tr) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm a bit confused here. Does this sentence and the below list correspond to the `Cloud deployment` section? Looks like they shouldn't be. So maybe you need to create one more section here?
</blockquote></details>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere and the content is present on other pages
___
*[`Documentation/developer-index.rst` line 8 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr63elBiu893eHBTZ8:-NUW775E3PBKAO838UOY:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/developer-index.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Two trailing spaces
</blockquote></details>

Done
___
*[`Documentation/developer-index.rst` line 14 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr6DEZ9JVf_5Qfg0DO:-NUW7Oaf7xjJn9bg4X1x:bqttwdc) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/developer-index.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We're missing this new file now: https://gramine.readthedocs.io/en/latest/devel/features.html
</blockquote></details>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere
___
*[`Documentation/docker-image-installation.rst` line 26 at r13](https: [...]

2023-05-03 15:01 UTC, deb-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 20 of 38 files reviewed, 56 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul and @dimakuv)

___
*[`Documentation/conf.py` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KK9R98P-Z5ovTio2:-NUX1f-vB61prN1oOTct:bssse3f) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still no reply. I would prefer to revert this change.
</blockquote></details>

I'm mentioned to @Carteepaul that app.add_stylesheet() is going away. It will be removed in sphinx 4.0 so, at some point, your build will generate errors. Might not be a bad idea to get one of the guys to doublecheck this. Keeping your current preference is fine for now but just note that it might mess up things in the new future.
___
*[`Documentation/requirements.txt` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Nrq6Eu-XCuG7jRqo:-NTEaJlY7y3oWnJnl5wg:b-7u4xuo) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, Carteepaul (Paul Cartee) wrote…</i></summary><blockquote>

Deb changed the requirements in her repo because she needed those versions so she could build the website in her environment. Those requirements are very old and will create documentation issues at some point. I set the requirements back to the original version numbers. 
</blockquote></details>

@dimakuv, as @Carteepaul stated, I had updated the requirements in my repo so I could build the website in my environment. @Carteepaul can change it back to whatever requirements you had before. Be aware the your versions of breathe and (especially) sphinx are very old and will at some point create documentation generation issues. 


<!-- Sent from Reviewable.io -->

2023-05-04 20:34 UTC, Carteepaul reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 20 of 38 files reviewed, 55 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @deb-intel and @dimakuv)

___
*[`Documentation/conf.py` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2KK9R98P-Z5ovTio2:-NUcQFi-5ycUHp1FeM6V:b-jxkp29) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/conf.py#L124)):*
<details><summary><i>Previously, deb-intel (Deb Taylor) wrote…</i></summary><blockquote>

I'm mentioned to @Carteepaul that app.add_stylesheet() is going away. It will be removed in sphinx 4.0 so, at some point, your build will generate errors. Might not be a bad idea to get one of the guys to doublecheck this. Keeping your current preference is fine for now but just note that it might mess up things in the new future.
</blockquote></details>

Done. I reverted the changes to the original source.
___
*[`Documentation/configuration-index.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1241#-NSqkdGI7iUVoFwPqB-l:-NUcQmDlB5GeCUatlBUG:b-qpxsib) ([raw file](https://github.com/gramineproject/gramine/blob/a50d9b21cd4b63c8aa162d88de88bbec0fd70497/Documentation/configuration-index.rst#L11)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv @Carteepaul This page is not linked from anywhere. Does it make any sense? I assume it should be removed
</blockquote></details>

Done. I removed the page. It was a holdover from earlier discussions about reorganizing the docs. 
___
*[`Documentation/contributor-index.rst` line 3 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUW3TDq2wu0LgM88-zt:-NUcRmu41nvaKgC9_-u0:bqwsizw) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/contributor-index.rst#L3)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv @Carteepaul This page is not linked from anywhere. Does it make any sense? I assume it should be removed
</blockquote></details>

Done. I deleted this page. It was another holdover page from our earlier attempts at reorganizing the documentation. 
___
*[`Documentation/custom-installation.rst` line 27 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5kNX3CNPRr2m6Pc4:-NUcS2HIA5-hedzQ5zln:b-c8j24o) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L27)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere and the content is present on other pages
</blockquote></details>

Done. I deleted this file. This was another holdover file from our earlier attempts at reorganizing documentation.
___
*[`Documentation/custom-installation.rst` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr5tXg7NRWvBFY2IP6:-NUcSNQy3JyqVkm8q0D5:bdxha35) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/custom-installation.rst#L31)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere and the content is present on other pages
</blockquote></details>

Done. This file was removed. It was a holdover from our earlier attempts at reorganzing the docs. 
___
*[`Documentation/developer-index.rst` line 14 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr6DEZ9JVf_5Qfg0DO:-NUcS_qFApPV71Whtxhd:b-9wr3q8) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/developer-index.rst#L14)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv @Carteepaul I assume this entire file should be removed. It is not linked from anywhere
</blockquote></details>

Done. This file was removed. 
___
*[`Documentation/requirements.txt` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1241#-NR2Nrq6Eu-XCuG7jRqo:-NUcSvncBaCM1sEcg6GX:b1oxsd6) ([raw file](https://github.com/gramineproject/gramine/blob/f2afe88f1a9baa94323222d5adce3447fd522136/Documentation/requirements.txt#L2)):*
<details><summary><i>Previously, deb-intel (Deb Taylor) wrote…</i></summary><blockquote>

@dimakuv, as @Carteepaul stated, I had updated the requirements in my repo so I could build the website in my environment. @Carteepaul can change it back to whatever requirements you had before. Be aware the your versions of breathe and (especially) sphinx are very old and will at some point create documentation generation issues. 
</blockquote></details>

The requirements were rolled back. 


<!-- Sent from Reviewable.io -->

2023-05-05 12:12 UTC, dimakuv approved these changes
> Reviewed 9 of 15 files at r14, 1 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @BFuhry and @Carteepaul)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUfoueD81nMt-poI4Z2:-NUfoueD81nMt-poI4Z3:bw38gl0) (no related file):*
Looks good to me now.

We'll need to very carefully rebase this PR to the latest master and verify again that we didn't lose any updated to the documentation.

___
___
*[`Documentation/cloud-deployment.rst` line 43 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTr4Wbx5Ow3ksRvixH8:-NUfnHnWEDNuXa4jVQz9:bwjt2aa) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/cloud-deployment.rst#L43)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

@dimakuv Which sentence do you want in brackets and why?
</blockquote></details>

Ah, ignore me. That comment was not important.
___
*[`Documentation/manpages/index.rst` line 9 at r13](https://reviewable.io/reviews/gramineproject/gramine/1241#-NTrC5Lk7a7KyFJ0HDVL:-NUfoWHiAOhqbjvsbjmV:bqnpwm4) ([raw file](https://github.com/gramineproject/gramine/blob/1fa1c724a3797cfdcb0dffd6821d61f387f0bd56/Documentation/manpages/index.rst#L9)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

But the file describing `gramine-direct` and `gramine-sgx` is called `gramine`. Thus, this is correct
</blockquote></details>

Ah, ok


<!-- Sent from Reviewable.io -->

2023-05-05 12:13 UTC, dimakuv commented
Jenkins, test this please

2023-05-05 15:29 UTC, donporter requested changes
> Reviewed 2 of 35 files at r1, 1 of 15 files at r2, 1 of 11 files at r3, 1 of 4 files at r4, 1 of 21 files at r8, 1 of 11 files at r10, 1 of 18 files at r11, 11 of 24 files at r12, 9 of 15 files at r14, 1 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @BFuhry and @Carteepaul)

___
*[`Documentation/curated-installation.rst` line 7 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMp-11BnErBPN7Sb7:-NUgMp-11BnErBPN7Sb8:bd1a3ac) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L7)):*
> ```reStructuredText
> 
> Confidential Compute images with Gramine are ready-made solutions for popular
> open-source projects such as PyTorch and Redis. Customize your environment
> ```

Consider a comma before "such as"
___
*[`Documentation/curated-installation.rst` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMcM79s6wy5u3jkm8:-NUgMcM81-EvLyZKbB91:bokuu5j) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L8)):*
> ```reStructuredText
> Confidential Compute images with Gramine are ready-made solutions for popular
> open-source projects such as PyTorch and Redis. Customize your environment
> through Interactive scripts. The result is a curated, confidentially protected
> ```

Errant capitalization.   Unless "Interactive scripts" is a proper name.

"confidentially protected" -> "confidentiality-protected"; with the manifest discussion below, is this modifier even needed (or perhaps contradictory)?
___
*[`Documentation/curated-installation.rst` line 10 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgN2Mk1gwgl-0nXMhU:-NUgN2Mk1gwgl-0nXMhV:b5yydih) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L10)):*
> ```reStructuredText
> through Interactive scripts. The result is a curated, confidentially protected
> Gramine image that includes your specific machine-learning application, common
> dependencies, and a manifest file that specifies security policies to enforce
> ```

Consider linking to the documentation for policies here
___
*[`Documentation/docker-image-installation.rst` line 1 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgNCKX9ba9JZdyjUu-:-NUgNCKX9ba9JZdyjUu0:bksogq8) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/docker-image-installation.rst#L1)):*
> ```reStructuredText
> Gramine docker image
> ```

Capitalize Docker?
___
*[`Documentation/environment-setup.rst` line 14 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgTeCW5lLyb29ovS6k:-NUgTeCW5lLyb29ovS6l:b7pjn89) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/environment-setup.rst#L14)):*
> ```reStructuredText
> - The Intel SGX driver must be built in the Linux kernel;
> 
> - Intel SGX SDK/PSW and (optionally) Intel DCAP must be installed.
> ```

A little odd mix of optionally and must.  Consider splitting the bullet
___
*[`Documentation/manifest-syntax.rst` line 135 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgUcsj5zqj7vRbQNe2:-NUgUcsj5zqj7vRbQNe3:b-x93cub) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/manifest-syntax.rst#L135)):*
> ```reStructuredText
>   containing output of :ref:`gramine-argv-serializer<gramine-argv-serializer>`.
> 
> If none of the above arguments-handling manifest options are specified in the
> ```

arguments -> argument (more idiomatic, at least in US English)
___
*[`Documentation/prerequisites.rst` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgUoh94cikfsoovELZ:-NUgUohAEv2xMaqRhdqb:bgkfxjx) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/prerequisites.rst#L11)):*
> ```reStructuredText
> 
> - Linux kernel version at least 5.11 (with Intel® SGX driver enabled);
> - Intel SGX PSW and (optionally) Intel® DCAP must be installed and configured.
> ```

Odd mix of optionally and must.  Is this document redundant with environment-setup.rst?
___
*[`Documentation/devel/building.rst` line 276 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWbmR2CIIo7-ob4aZ:-NUgWbmR2CIIo7-ob4a_:b-60pkdq) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/devel/building.rst#L276)):*
> ```reStructuredText
> The following command generates an |~| RSA 3072 key suitable for signing SGX
> enclaves and stores it in :file:`{HOME}/.config/gramine/enclave-key.pem`.
> Protect this key and do not disclose it to anyone::
> ```

I count at least 3 instances of these instructions in the PR.  Is there any value in consolidating?  In the event we need to change something, fewer opportunites to get incoherent.
___
*[`Documentation/devel/debugging.rst` line 57 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWovJAeR9IvkT8Wga:-NUgWovJAeR9IvkT8Wgb:b-uyanb0) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/devel/debugging.rst#L57)):*
> ```reStructuredText
> 
> Building Gramine with ``--buildtype=debug`` enables debug symbols and GDB
> integration but disables optimizations. This is usually the right thing to do:
> ```

I think the comma helps, but your call.
___
*[`Documentation/pal/host-abi.rst` line 22 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWvNVCmfTdQBCl9R4:-NUgWvNVCmfTdQBCl9R5:b-31ek8o) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/pal/host-abi.rst#L22)):*
> ```reStructuredText
> 
> Regardless of the actual implementation, we require PAL to be able to load ELF-format binaries
> as executables or dynamic libraries and perform the necessary dynamic relocation. PAL needs
> ```

I would keep the comma to avoid ambiguity with two conjunctions in the same sentence.  Unlike arithmetic, english doesn't have good operator precedence rules :)


<!-- Sent from Reviewable.io -->

2023-05-08 18:02 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 8 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv and @donporter)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUfoueD81nMt-poI4Z2:-NUvq_t_0342fMb9F0FG:b51kisu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good to me now.

We'll need to very carefully rebase this PR to the latest master and verify again that we didn't lose any updated to the documentation.
</blockquote></details>

Rebased to newest master. Only conflicts were about maintainers and I (hopefully) adjusted the changes accordingly.

___
___
*[`Documentation/curated-installation.rst` line 7 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMp-11BnErBPN7Sb7:-NUvrNZqBxEAbYoXvex_:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L7)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider a comma before "such as"
</blockquote></details>

done
___
*[`Documentation/curated-installation.rst` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMcM79s6wy5u3jkm8:-NUvrMq9CRKyfHIFu0Q1:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L8)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Errant capitalization.   Unless "Interactive scripts" is a proper name.

"confidentially protected" -> "confidentiality-protected"; with the manifest discussion below, is this modifier even needed (or perhaps contradictory)?
</blockquote></details>

done
___
*[`Documentation/curated-installation.rst` line 10 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgN2Mk1gwgl-0nXMhU:-NUvrQtM8-zgFTnIeJAL:bhyg5k5) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L10)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider linking to the documentation for policies here
</blockquote></details>

@donporter Can you please elaborate on this request?
___
*[`Documentation/docker-image-installation.rst` line 1 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgNCKX9ba9JZdyjUu-:-NUvrc5hDXJPIdBbTrt5:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/docker-image-installation.rst#L1)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Capitalize Docker?
</blockquote></details>

done
___
*[`Documentation/environment-setup.rst` line 14 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgTeCW5lLyb29ovS6k:-NUwS7K7CbryBy3BfSEs:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/environment-setup.rst#L14)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

A little odd mix of optionally and must.  Consider splitting the bullet
</blockquote></details>

done
___
*[`Documentation/manifest-syntax.rst` line 135 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgUcsj5zqj7vRbQNe2:-NUwSHrpBjtq9n11s2Gz:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/manifest-syntax.rst#L135)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

arguments -> argument (more idiomatic, at least in US English)
</blockquote></details>

Done
___
*[`Documentation/prerequisites.rst` line 11 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgUoh94cikfsoovELZ:-NUwSs9CEpybQAkOq9mD:bn7x7kc) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/prerequisites.rst#L11)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Odd mix of optionally and must.  Is this document redundant with environment-setup.rst?
</blockquote></details>

done

Removed the file completely as it is not referenced anywhere and its content is present in `environment-setup.rst`.
___
*[`Documentation/devel/building.rst` line 276 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWbmR2CIIo7-ob4aZ:-NUwTToq00RuMyUu7THE:be086cm) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/devel/building.rst#L276)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I count at least 3 instances of these instructions in the PR.  Is there any value in consolidating?  In the event we need to change something, fewer opportunites to get incoherent.
</blockquote></details>

I just removed one occurrence by removing the file `Documentation/cloud-deployment.rst`, which was not referenced anywhere and does not contain information not present anywhere else.

As a result, the text is present once in the "Protect your application" and once in the "Develop Gramine" section. As these sections target different users groups, it might be fine. However, we can check consolidation of this after the PR merge.
___
*[`Documentation/devel/debugging.rst` line 57 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWovJAeR9IvkT8Wga:-NUwVWP_-UxS20y7N-UP:buvh54l) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/devel/debugging.rst#L57)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I think the comma helps, but your call.
</blockquote></details>

This is a grammar change done by one of the native speaking professional tech writers; so I would leave it as is.
___
*[`Documentation/pal/host-abi.rst` line 22 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWvNVCmfTdQBCl9R4:-NUwVtOf15szOf5o1td4:buvh54l) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/pal/host-abi.rst#L22)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I would keep the comma to avoid ambiguity with two conjunctions in the same sentence.  Unlike arithmetic, english doesn't have good operator precedence rules :)
</blockquote></details>

This is a grammar change done by one of the native speaking professional tech writers; so I would leave it as is.


<!-- Sent from Reviewable.io -->

2023-05-09 06:52 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 31 files at r21, 1 of 29 files at r24, 19 of 28 files at r25, 4 of 4 files at r26, 4 of 4 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @donporter)

___
*[`Documentation/curated-installation.rst` line 7 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMp-11BnErBPN7Sb7:-NUzGbC2226TuFPosPvM:b-hndcz9) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L7)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

done
</blockquote></details>

not done?
___
*[`Documentation/curated-installation.rst` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMcM79s6wy5u3jkm8:-NUzGc-dCGQfzIrz2R2F:b-hndcz9) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L8)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

done
</blockquote></details>

not done?


<!-- Sent from Reviewable.io -->

2023-05-09 10:02 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 37 of 38 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

___
*[`Documentation/curated-installation.rst` line 7 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMp-11BnErBPN7Sb7:-NUzxa-QCry2HoJzwUOi:bdnwdnu) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

Sry, don't know what happened to my changes before
___
*[`Documentation/curated-installation.rst` line 8 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgMcM79s6wy5u3jkm8:-NUzxX7T4pMWZUZcUnDM:b71et64) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

done

Sry, don't know what happened to my changes before


<!-- Sent from Reviewable.io -->

2023-05-09 11:23 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2023-05-09 12:39 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 36 of 38 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

___
*[`Documentation/curated-installation.rst` line 10 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgN2Mk1gwgl-0nXMhU:-NV-SYHt33-NW1FnLLGL:b-bemp6z) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L10)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

As in, create a link to the portion of the documentation that explains what sort of security policies one can enforce for a given workload.  Make sense?
</blockquote></details>

I did not write the text , but I assume you might be misled (due to imprecise text). Each Confidential Compute image has exactly one Gramine manifest file that is prepared, which provides a "specific security policy". We could link to the Gramine manifest syntax, but I don't think that this is what you want. There is no additional security policy mechanism anywhere.

I could change to "... a *Gramine* manifest file that specifies security policies to enforce for your workload."
___
*[`Documentation/docker-image-installation.rst` line 1 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgNCKX9ba9JZdyjUu-:-NV-TUZJ-E_FVwb32qYa:b-uol7c9) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/docker-image-installation.rst#L1)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I don't see the change...
</blockquote></details>

done

Sry, I had some issue with saving (and subsequently committing change)
___
*[`Documentation/pal/host-abi.rst` line 22 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgWvNVCmfTdQBCl9R4:-NV-UFFrBsZUwh8i1DHR:b-8hbprm) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/pal/host-abi.rst#L22)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Let me instead suggest reworking the sentence:

Each PAL implementation must support loading and dynamic relocation of ELF-format executables and dynamic libraries.
</blockquote></details>

I changes the sentence to what you (hopefully) wanted the change to be


<!-- Sent from Reviewable.io -->

2023-05-09 14:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 36 of 38 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul and @donporter)

___
*[`Documentation/curated-installation.rst` line 20 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-rYDlE3wmnoB5VrFF:-NV-rYDlE3wmnoB5VrFG:bsojeus) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/curated-installation.rst#L20)):*
> ```reStructuredText
> 
> - `Redis <https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/redis>`_
> - `PyTorch <https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/pytorch>`_
> ```

These two links are wrong now.
___
*[`Documentation/environment-setup.rst` line 34 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-qu3bEPj3mQNF_Cbx:-NV-qu3bEPj3mQNF_Cby:b-hxd80r) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/environment-setup.rst#L34)):*
> ```reStructuredText
> .. parsed-literal::
> 
> gramine-sgx-gen-private-key
> ```

This doesn't render correctly: https://carteepaul.github.io/gramine/environment-setup.html#prepare-a-signing-key

Please fix, I think like this is enough:
```
Only for SGX, and if you haven’t already, enter the following::

    gramine-sgx-gen-private-key
```

(The important parts are the double-colon `::` and the 4-spaces indentation.)
___
*[`Documentation/index.rst` line 31 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-rxWlBDb1rhDismKM:-NV-rxWlBDb1rhDismKN:bsojeus) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/index.rst#L31)):*
> ```reStructuredText
> Confidential compute images are ready-made solutions for popular open source
> projects such as `PyTorch <https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/pytorch>`_
> and `Redis <https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/redis>`_.
> ```

These two links are wrong now.


<!-- Sent from Reviewable.io -->

2023-05-09 14:22 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 36 of 38 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul, @dimakuv, and @donporter)

___
*[`Documentation/index.rst` line 30 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-szkM8ml1cSH1P7hz:-NV-szkM8ml1cSH1P7i-:b25qffx) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/index.rst#L30)):*
> ```reStructuredText
> 
> Confidential compute images are ready-made solutions for popular open source
> projects such as `PyTorch <https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/pytorch>`_
> ```

https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/workloads/pytorch



_Code quote:_
```reStructuredText
https://github.com/gramineproject/contrib/tree/master/Curated-Apps/workloads/pytorch
```
___
*[`Documentation/index.rst` line 31 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-rxWlBDb1rhDismKM:-NV-sq4q61pz0hv6kbrc:b1r8azy) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/index.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two links are wrong now.
</blockquote></details>

Pls kindly see https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/workloads/redis


<!-- Sent from Reviewable.io -->

2023-05-09 14:41 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 36 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul, @dimakuv, and @donporter)

___
*[`Documentation/docker-image-installation.rst` line 30 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-v9292siYcApiNZle:-NV-v9292siYcApiNZlf:b5808ar) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/docker-image-installation.rst#L30)):*
> ```reStructuredText
> You can download the profile file from:
> 
> https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json.
> ```

This is actually a wrapper of `docker_seccomp_mar_2021.json`.

Should we point to either `docker_seccomp_mar_2021.json` or `docker_seccomp_aug_2022.json` which are the real profile files (that people can download from)?



_Code quote:_
```reStructuredText
https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json
```


<!-- Sent from Reviewable.io -->

2023-05-09 17:25 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 33 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

___
*[`Documentation/curated-installation.rst` line 20 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-rYDlE3wmnoB5VrFF:-NV0Udp78YKgaA_0NI-9:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/curated-installation.rst#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two links are wrong now.
</blockquote></details>

Done
___
*[`Documentation/docker-image-installation.rst` line 30 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-v9292siYcApiNZle:-NV0UhdV9KDM7bMrnqn0:bn8cpta) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/docker-image-installation.rst#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is actually a wrapper of `docker_seccomp_mar_2021.json`.

Should we point to either `docker_seccomp_mar_2021.json` or `docker_seccomp_aug_2022.json` which are the real profile files (that people can download from)?
</blockquote></details>

Whatever is decided about this, please do such content changes after the PR is merged. This content was just moved, but (should be) unchanged (https://gramine.readthedocs.io/en/stable/container-integration.html).
___
*[`Documentation/environment-setup.rst` line 34 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-qu3bEPj3mQNF_Cbx:-NV0VIsj1BCg6yNsI1Uw:b-bp6j9k) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/environment-setup.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render correctly: https://carteepaul.github.io/gramine/environment-setup.html#prepare-a-signing-key

Please fix, I think like this is enough:
```
Only for SGX, and if you haven’t already, enter the following::

    gramine-sgx-gen-private-key
```

(The important parts are the double-colon `::` and the 4-spaces indentation.)
</blockquote></details>

I added a second `:`, I added the 4-spaces indentation, and I also removed `.. parsed-literal::` as you did not mention it. However, it is still not rendered properly.
___
*[`Documentation/index.rst` line 30 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-szkM8ml1cSH1P7hz:-NV0VjgV5OhoT_hi5a5t:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/index.rst#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/workloads/pytorch
</blockquote></details>

done
___
*[`Documentation/index.rst` line 31 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-rxWlBDb1rhDismKM:-NV0Vmk6Eh2v90OVV049:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/index.rst#L31)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls kindly see https://github.com/gramineproject/contrib/tree/master/Intel-Confidential-Compute-for-X/workloads/redis
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-09 17:37 UTC, BFuhry reviewed
I have done the structure changed discussed in the contributor meeting. See rendering of result using the usual link (https://carteepaul.github.io/gramine/)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241#-:-NV0_Z-N2uzM60rFybol:bnwro65)* status: 33 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv, @donporter, and @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-05-10 01:13 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 33 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @Carteepaul, @dimakuv, and @donporter)

___
*[`Documentation/curated-installation.rst` line 15 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV24caF7wBrYfm_vIRQ:-NV24caGBxIIEP0h2pa6:b-snyrx7) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/curated-installation.rst#L15)):*
> ```reStructuredText
> open-source projects, such as PyTorch and Redis.
> Customize your environment through interactive scripts.
> The result is a curated, confidentially-protected Gramine image that includes
> ```

"confidentially-protected" here sounds a bit wrong to me -- it's actually the Gramine instance which is confidentially-protected, rather than the image itself.



_Code quote:_
```reStructuredText
confidentially-protected Gramine image
```
___
*[`Documentation/docker-image-installation.rst` line 30 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-v9292siYcApiNZle:-NV20DMV83iNqf0H5EiY:brxkuje) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/docker-image-installation.rst#L30)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

Whatever is decided about this, please do such content changes after the PR is merged. This content was just moved, but (should be) unchanged (https://gramine.readthedocs.io/en/stable/container-integration.html).
</blockquote></details>

Right, let's do it in a separate PR (just noticed by chance). Resolving.
___
*[`Documentation/devel/building.rst` line 271 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV2A_ZY15TvOVljQKdY:-NV2A_ZY15TvOVljQKdZ:b-d5exwj) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/devel/building.rst#L271)):*
> ```reStructuredText
> ---------------------
> 
> These instructions are only required for systems using Intel® SGX that have not
> ```

We have TM indicator here for "Intel® SGX" (full name) but not anywhere else. If I remember correctly, lntel legal review would always require "Intel® SGX" (which is a registered trademark). But should we at least align here and there?



_Code quote:_
```reStructuredText
Intel® SGX
```


<!-- Sent from Reviewable.io -->

2023-05-10 10:10 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 33 of 38 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv, @donporter, and @kailun-qin)

___
*[`Documentation/curated-installation.rst` line 15 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV24caF7wBrYfm_vIRQ:-NV47yIW9QfHrNp5CcHn:b-3f96ml) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/curated-installation.rst#L15)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

"confidentially-protected" here sounds a bit wrong to me -- it's actually the Gramine instance which is confidentially-protected, rather than the image itself.
</blockquote></details>

This entire text has to be rewritten anyhow. But again, such content changes are for another PR.
___
*[`Documentation/devel/building.rst` line 271 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV2A_ZY15TvOVljQKdY:-NV47SBE7LGAAA94uZv-:bahfish) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/devel/building.rst#L271)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We have TM indicator here for "Intel® SGX" (full name) but not anywhere else. If I remember correctly, lntel legal review would always require "Intel® SGX" (which is a registered trademark). But should we at least align here and there?
</blockquote></details>

You are right. Legal even requires the following on every page where it is used for the first time: Intel® Software Guard Extensions (Intel® SGX)
But again, let's discuss this after the merge and unify it everywhere.


<!-- Sent from Reviewable.io -->

2023-05-10 15:00 UTC, donporter submitted a review, later dismissed
> Reviewed 2 of 2 files at r30, 1 of 2 files at r31, 1 of 1 files at r33, 1 of 1 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), period found at the end of a one-liner (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/curated-installation.rst` line 10 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgN2Mk1gwgl-0nXMhU:-NV59naf6uaRJGjK0hP7:bscnr6s) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L10)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I did not write the text , but I assume you might be misled (due to imprecise text). Each Confidential Compute image has exactly one Gramine manifest file that is prepared, which provides a "specific security policy". We could link to the Gramine manifest syntax, but I don't think that this is what you want. There is no additional security policy mechanism anywhere.

I could change to "... a *Gramine* manifest file that specifies security policies to enforce for your workload."

</blockquote></details>

The suggested change is clearer.  I like your suggestion.
___
*[`Documentation/curated-installation.rst` line 15 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV24caF7wBrYfm_vIRQ:-NV59yidCV-gw5rq-KeT:b-gba3li) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/curated-installation.rst#L15)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

This entire text has to be rewritten anyhow. But again, such content changes are for another PR.
</blockquote></details>

I agree with bounding the work on this PR.  But I also agree that it should be "confidentiality protected".  Note that -ly words are not hyphenated (for some idiosyncratic reason).


<!-- Sent from Reviewable.io -->

2023-05-11 11:35 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r30, 1 of 1 files at r33, 1 of 2 files at r35, 1 of 1 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @BFuhry, @Carteepaul, and @kailun-qin)

___
*[`Documentation/environment-setup.rst` line 34 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-qu3bEPj3mQNF_Cbx:-NV9_dfW8ni1CBkcT0KH:b-qj9vmr) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/environment-setup.rst#L34)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I added a second `:`, I added the 4-spaces indentation, and I also removed `.. parsed-literal::` as you did not mention it. However, it is still not rendered properly.
</blockquote></details>

You must add another empty line right after the `::` line.
___
*[`Documentation/index.rst` line 62 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9_pOi9rp2dlxKmv0S:-NV9_pOi9rp2dlxKmv0T:bybue8f) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/index.rst#L62)):*
> ```reStructuredText
> 
> .. note::  These confidential compute images only run on machines that support
>    Intel SGX.
> ```

Actually, what's the point of this note? First of all, it's kinda obvious, second of all, you have the same note in the corresponding file (this one: https://carteepaul.github.io/gramine/curated-installation.html).


<!-- Sent from Reviewable.io -->

2023-05-11 11:41 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r30.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @BFuhry, @Carteepaul, and @kailun-qin)

___
*[`Documentation/docker-image-installation.rst` line 20 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9aHjO7GzftCg9oRXC:-NV9aHjP72XaBapZIWzS:b-jmn5wy) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L20)):*
> ```reStructuredText
> To run the Gramine image via Docker, the recommended command is::
> 
> ``docker run --device /dev/sgx_enclave -it gramineproject/gramine``
> ```

This is wrong, check how it incorrectly renders: https://carteepaul.github.io/gramine/docker-image-installation.html

What you need to do is to remove backticks, always have `::` at the end of the previous paragraph, indent with 4 spaces these code blocks, and have empty lines around them.

In this case:
```
To run the Gramine image via Docker, the recommended command is::

    docker run --device /dev/sgx_enclave -it gramineproject/gramine

If you want...
```
___
*[`Documentation/docker-image-installation.rst` line 26 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9aY0WEDwxcy0USpF6:-NV9aY0WEDwxcy0USpF7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L26)):*
> ```reStructuredText
> profile using:
> 
> ``--security-opt seccomp=<profile_file>``
> ```

ditto
___
*[`Documentation/docker-image-installation.rst` line 29 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9abRQA6fMufhmPgcI:-NV9abRQA6fMufhmPgcJ:bde0wl9) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L29)):*
> ```reStructuredText
> 
> You can download the profile file from:
> ```

Why do you need an empty space here? This makes these two paragraphs, but it's actually a single paragraph. Please remove.
___
*[`Documentation/docker-image-installation.rst` line 34 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9agTdAD869PCR4Y5i:-NV9agTe5-3X6f-JtMpR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L34)):*
> ```reStructuredText
> Alternatively you can disable seccomp completely:
> 
> ``--security-optseccomp=unconfined``
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-05-11 12:34 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: 35 of 38 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

___
*[`Documentation/curated-installation.rst` line 10 at r20](https://reviewable.io/reviews/gramineproject/gramine/1241#-NUgN2Mk1gwgl-0nXMhU:-NV9E7mL5ghy1ovAkhd8:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/ea28a9439bb578debc0063217fbb973e664840c3/Documentation/curated-installation.rst#L10)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

The suggested change is clearer.  I like your suggestion.
</blockquote></details>

Done
___
*[`Documentation/curated-installation.rst` line 15 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV24caF7wBrYfm_vIRQ:-NV9E8op-XK4qz6q4Xd8:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/curated-installation.rst#L15)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I agree with bounding the work on this PR.  But I also agree that it should be "confidentiality protected".  Note that -ly words are not hyphenated (for some idiosyncratic reason).
</blockquote></details>

Done
___
*[`Documentation/docker-image-installation.rst` line 20 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9aHjO7GzftCg9oRXC:-NV9gwJlDppm73Y0VmNX:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong, check how it incorrectly renders: https://carteepaul.github.io/gramine/docker-image-installation.html

What you need to do is to remove backticks, always have `::` at the end of the previous paragraph, indent with 4 spaces these code blocks, and have empty lines around them.

In this case:
```
To run the Gramine image via Docker, the recommended command is::

    docker run --device /dev/sgx_enclave -it gramineproject/gramine

If you want...
```
</blockquote></details>

done
___
*[`Documentation/docker-image-installation.rst` line 26 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9aY0WEDwxcy0USpF6:-NV9gwrRDlAFPPUkIPFA:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[`Documentation/docker-image-installation.rst` line 29 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9abRQA6fMufhmPgcI:-NV9gxRzAi7hLyPxBGeV:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need an empty space here? This makes these two paragraphs, but it's actually a single paragraph. Please remove.
</blockquote></details>

done
___
*[`Documentation/docker-image-installation.rst` line 34 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9agTdAD869PCR4Y5i:-NV9gyAo5s-ogdgm_sz-:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/docker-image-installation.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[`Documentation/environment-setup.rst` line 34 at r30](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV-qu3bEPj3mQNF_Cbx:-NV9h--C-_sU7-pdOKaF:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/9e17b1f11a125f03fe0054f56d76c1506af3c544/Documentation/environment-setup.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You must add another empty line right after the `::` line.
</blockquote></details>

done
___
*[`Documentation/index.rst` line 62 at r36](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV9_pOi9rp2dlxKmv0S:-NV9guixBK_Xsx9-HFLA:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/fdcd33c9462b2873a89e814151f6589eccdf4a28/Documentation/index.rst#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what's the point of this note? First of all, it's kinda obvious, second of all, you have the same note in the corresponding file (this one: https://carteepaul.github.io/gramine/curated-installation.html).
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-11 14:48 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-05-11 15:01 UTC, donporter approved these changes
> Reviewed 1 of 2 files at r35, 3 of 3 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-05-11 16:12 UTC, kailun-qin approved these changes
> Reviewed 2 of 35 files at r1, 1 of 15 files at r2, 1 of 21 files at r8, 1 of 11 files at r10, 1 of 18 files at r11, 2 of 24 files at r12, 1 of 31 files at r21, 1 of 29 files at r24, 16 of 28 files at r25, 4 of 4 files at r26, 3 of 4 files at r27, 1 of 2 files at r30, 1 of 2 files at r35, 3 of 3 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, all discussions resolved, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners

___
*[`Documentation/devel/building.rst` line 271 at r34](https://reviewable.io/reviews/gramineproject/gramine/1241#-NV2A_ZY15TvOVljQKdY:-NVA_M_i8931H0NjTFWV:b-80tlqk) ([raw file](https://github.com/gramineproject/gramine/blob/9ba1e107e9ecd1d046f6ef27ea7e703984e30e00/Documentation/devel/building.rst#L271)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

You are right. Legal even requires the following on every page where it is used for the first time: Intel® Software Guard Extensions (Intel® SGX)
But again, let's discuss this after the merge and unify it everywhere.
</blockquote></details>

Sure.


<!-- Sent from Reviewable.io -->

2023-05-15 00:48 UTC, mkow requested changes
> Reviewed 1 of 21 files at r8, 1 of 11 files at r10, 2 of 24 files at r12, 8 of 28 files at r25, 4 of 4 files at r26, 1 of 4 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1241)* status: all files reviewed, 1 unresolved discussion, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @Carteepaul)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1241#-NVRq5Uy9QONzGgggEb7:-NVRq5Uy9QONzGgggEb8:b-3fsxqt) (no related file):*
I really don't like the state of this PR, it breaks all the rules we have about commits - it's basically a single commit described as "update documentation" changing 500 lines in 22 files, moving files around and doing a lot of unrelated things at the same time. This obscures the commit history and makes it hard to track changes (e.g. to check if we didn't drop some documentation entry accidentally).

So, @BFuhry: Could you split this PR into smaller ones? There are a lot of trivial changes here which will be easy to review and to quickly merge. It shouldn't take much time, but if you don't have enough time for this then we can do this ourselves (preserving proper authorship of the commits).
This way the more disputed changes (like some rewordings) could get a proper review, and it would take less time because we could focus on a single thing at once.

___


<!-- Sent from Reviewable.io -->

2023-06-09 00:36 UTC, closed without merging