[LibOS] Add support for `setsid()`/`getsid()`
gramineproject/gramine pull request #1264
Opened 2023-04-03 10:28 UTC by kailun-qin

## Description of the changes 
Previously, session-management syscalls e.g., `setsid()`, `getsid()`, were not supported in Gramine. However, they are required for many workloads, particularly the ones that use JVM.

This commit adds basic support for session-management syscalls and enables the related tests. As a side effect of the introduction of `setsid()`, `pgid` and `sid` in struct `libos_process` are now both not suitable for atomic access so we introduced a new global lock and used it everywhere where we access `pgid` and `sid`.

## How to test this PR? 
Newly enabled LTP tests + unit tests

## Useful references
How session-management syscalls work:
* https://man7.org/linux/man-pages/man2/setsid.2.html
* https://man7.org/linux/man-pages/man2/getsid.2.html
* https://www.andy-pearce.com/blog/posts/2013/Aug/process-groups-and-sessions/
* https://biriukov.dev/docs/fd-pipe-session-terminal/3-process-groups-jobs-and-sessions/#sessions

Linux source code on:
* `setsid`: https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1207
* `getsid`: https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1168

One of the typical usage example of `setsid()` for daemonising:
https://github.com/pasce/daemon-skeleton-linux-c

Reasons why `attached_to_other_pg` is introduced:
* When the process group having forked of a child and then it attached itself to another process group and tries to setsid, it should fail w/ `EPERM`, see the example of `setsid01` in LTP: https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176-L191
* The underlying kernel logic: `setsid()` should fail if a process group id already exists that equals the proposed session id (https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1222). This process group id is actually set on `setpgid()` when the specified `pgid` points to a different process group (https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1116) via `change_pid()` -> `attach_pid()` (https://elixir.bootlin.com/linux/v6.2/source/kernel/pid.c#L334).
* This is not clearly stated in the man page, but can be found in kernel impl. and the associated LTP test case.

2023-04-04 04:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`libos/include/libos_process.h` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6C5am-0FO4wLDtGdb:-NS9KeEx3epYkFIWLMdR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/include/libos_process.h#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Indicates`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_process.c` line 246 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CRANB9VaUNiXRR4g:-NS9KfaQ67YS3reFDtEf:b-4ku2qv) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/bookkeep/libos_process.c#L246)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we re-initialize this field to `false` in child processes?
</blockquote></details>

Because on fork, child processes are actually attached to the same process group of their parents (i.e., not attached to "another" process group).

Also pls kindly take a look at my newly added test -- a forked child of the session leader should still be able to create a new session (which requires this field to be re-initialized to `false`).
___
*[`libos/src/sys/libos_clone.c` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CeNM8rJA_gTDO5kB:-NS9Kntm-howFeyRuguh:b-qz3p20) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_clone.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, why `false`?
</blockquote></details>

Pls kindly see my comment above.
___
*[`libos/src/sys/libos_getpid.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6Cx515XbECjEqxFTv:-NS9M6fQAaXqXyjEFE4_:bpxjfhp) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_getpid.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Something is broken in this sentence. I think you should remove the word `must`?
</blockquote></details>

Added a "that" after "checking". See if reads more correct to you.
___
*[`libos/src/sys/libos_getpid.c` line 121 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6Di1d5NO6WwMXl81E:-NS9MHrCDnBJFti_LymB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_getpid.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're using `ESRCH` here, but in other parts of this file we use `EINVAL` for such cases. Could you check which error number should be used, and update uniformly?
</blockquote></details>

Done.
___
*[`libos/test/regression/sid.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6ERKo6w7oC7uPPM3t:-NS9MJQs5KKP8zZxwlB7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/test/regression/sid.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the space before `*/`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-04 07:27 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_process.c` line 246 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CRANB9VaUNiXRR4g:-NSA82hyCJCTpJJ9UngQ:b-78eeur) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/bookkeep/libos_process.c#L246)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Because on fork, child processes are actually attached to the same process group of their parents (i.e., not attached to "another" process group).

Also pls kindly take a look at my newly added test -- a forked child of the session leader should still be able to create a new session (which requires this field to be re-initialized to `false`).
</blockquote></details>

Please put what you said as a comment here (`on fork, child process is attached to the same process group as parent`)
___
*[`libos/src/sys/libos_clone.c` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CeNM8rJA_gTDO5kB:-NSA98BA156JkyRdjJg3:b-kir0ng) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_clone.c#L171)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls kindly see my comment above.
</blockquote></details>

Actually, what's going on here? Why do we need to set process fields here, in addition to setting them int the checkpointing function? Wouldn't the checkpointing function be called somewhere in this `clone` flow, and we'll do the same thing twice?


<!-- Sent from Reviewable.io -->

2023-04-04 08:29 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_clone.c` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CeNM8rJA_gTDO5kB:-NSAKn_d9v7V3RiqTuJG:b-iy2y11) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_clone.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what's going on here? Why do we need to set process fields here, in addition to setting them int the checkpointing function? Wouldn't the checkpointing function be called somewhere in this `clone` flow, and we'll do the same thing twice?
</blockquote></details>

hmm... I think the `process_description` here is just the one we passed into the checkpointing function, right? See:
https://github.com/gramineproject/gramine/blob/b74889710bbf6a5a620ff1e6742f3bd3df7a5a8a/libos/src/sys/libos_clone.c#L193-L194
https://github.com/gramineproject/gramine/blob/b74889710bbf6a5a620ff1e6742f3bd3df7a5a8a/libos/src/sys/libos_clone.c#L121
https://github.com/gramineproject/gramine/blob/b74889710bbf6a5a620ff1e6742f3bd3df7a5a8a/libos/src/sys/libos_clone.c#L100
https://github.com/gramineproject/gramine/blob/b74889710bbf6a5a620ff1e6742f3bd3df7a5a8a/libos/src/bookkeep/libos_process.c#L212


So it looks fine to me that we set process fields (from `g_process`) here and copy them to the cp offset in the checkpointing function: https://github.com/gramineproject/gramine/blob/b74889710bbf6a5a620ff1e6742f3bd3df7a5a8a/libos/src/bookkeep/libos_process.c#L225-L230.


Maybe I should do `new_process->attached_to_other_pg = process->attached_to_other_pg` instead of `new_process->attached_to_other_pg = false` in the checkpointing function to avoid confusions.


<!-- Sent from Reviewable.io -->

2023-04-04 09:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/sys/libos_clone.c` line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6CeNM8rJA_gTDO5kB:-NSAUeiN5_kGLzpwneI7:byonkat) ([raw file](https://github.com/gramineproject/gramine/blob/5710274f00ac5cbb16e80e29087e168c93c45855/libos/src/sys/libos_clone.c#L171)):*
> Maybe I should do new_process->attached_to_other_pg = process->attached_to_other_pg instead of new_process->attached_to_other_pg = false in the checkpointing function to avoid confusions.

Yes, please. And I would also put a comment like `attached_to_other_pg is set to false in libos/src/sys/libos_clone.c: do_clone_new_vm()`


<!-- Sent from Reviewable.io -->

2023-04-04 14:45 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-18 00:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6F66886kUlMSrp9fc:-NTGmyB_245szvuI7YdK:b1ogngl) (no related file):*
> Could we document somewhere what's missing from this support?

Yes we could.

> Maybe in that new "Gramine features" document?

Yes, it should be updated in the feature doc. But isn't the update supposed to happen in a longer cadence (and in a batch, e.g., before each release)?
https://github.com/gramineproject/gramine/blob/d51ff412bd9a0badf9d56adbe228a900bfeba5b2/Documentation/devel/features.md?plain=1#L10

___


<!-- Sent from Reviewable.io -->

2023-04-18 00:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6F66886kUlMSrp9fc:-NTGrLj-2i01CwoAZtm0:b-y9hhzg) (no related file):*
> isn't the update supposed to happen in a longer cadence (and in a batch, e.g., before each release)?

No, why?

CC: @dimakuv, maybe I'm missing something...

___


<!-- Sent from Reviewable.io -->

2023-04-18 02:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6F66886kUlMSrp9fc:-NTH9y1W2jBIwqWlk634:b-id3ia9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> isn't the update supposed to happen in a longer cadence (and in a batch, e.g., before each release)?

No, why?

CC: @dimakuv, maybe I'm missing something...
</blockquote></details>

Just for reference, we've added dummy ancillary data support for sockets (via this commit: https://github.com/gramineproject/gramine/commit/299dde8f4c96d7a0e2d2ef1652c5a241777607e7) but in the feature doc we still have:
https://github.com/gramineproject/gramine/blob/d51ff412bd9a0badf9d56adbe228a900bfeba5b2/Documentation/devel/features.md?plain=1#L2395-L2397
and
https://github.com/gramineproject/gramine/blob/d51ff412bd9a0badf9d56adbe228a900bfeba5b2/Documentation/devel/features.md?plain=1#L2515-L2517.

We may want to update that too then.

___


<!-- Sent from Reviewable.io -->

2023-04-19 07:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NS6F66886kUlMSrp9fc:-NTNOsRc5iHwxyzbMJ1T:b-2hrt4y) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Just for reference, we've added dummy ancillary data support for sockets (via this commit: https://github.com/gramineproject/gramine/commit/299dde8f4c96d7a0e2d2ef1652c5a241777607e7) but in the feature doc we still have:
https://github.com/gramineproject/gramine/blob/d51ff412bd9a0badf9d56adbe228a900bfeba5b2/Documentation/devel/features.md?plain=1#L2395-L2397
and
https://github.com/gramineproject/gramine/blob/d51ff412bd9a0badf9d56adbe228a900bfeba5b2/Documentation/devel/features.md?plain=1#L2515-L2517.

We may want to update that too then.
</blockquote></details>

Yes, the idea was to periodically update that document, not with every PR.

Let me create a meta-issue on this, and we'll add what changes must be added into that document. Here it is: https://github.com/gramineproject/gramine/issues/1295

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTBJwLbDRWZENGUeL0Y:-NTNQCFUCo7lgXnaGVvs:b-1nv1df) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems to be another good candidate for using rwlocks from #1109 (after we merge it) - these fields are almost never modified, and apps probably assume that `getsid()` is fast, so they may not care about calling it often.
</blockquote></details>

To be honest, I don't think apps call `getsid()` frequently. I suggest to only go with RWLocks if we ever root-cause a performance bottleneck to `getsid()`. Until then, let's just use normal locks.

___


<!-- Sent from Reviewable.io -->

2023-04-19 07:33 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (it failed but I don't know how, because Jenkins already erased this job)

2023-04-19 07:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTNTpZU4xLfmaYNUe7L:bu53c0w) (no related file):*
@kailun-qin For some reason, `Jenkins-Direct-Sanitizers` (`gramine-direct` with AddressSanitizer) failed like this:
```
[1.031] setsid01    1  TFAIL  :  /home/jenkins/workspace/graphene-direct-sanitizers/libos/test/ltp/src/testcases/kernel/syscalls/setsid/setsid01.c:189: setsid failed, expected -1,return 0
[1.031] setsid01    1  TPASS  :  setsid SUCCESS to set errno to EPERM
[1.031] setsid01    1  TPASS  :  all misc tests passed
```

Could you check what happens?

___


<!-- Sent from Reviewable.io -->

2023-04-19 08:29 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTN_P1fCbqOyowm9OAr:b-hk4cti) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin For some reason, `Jenkins-Direct-Sanitizers` (`gramine-direct` with AddressSanitizer) failed like this:
```
[1.031] setsid01    1  TFAIL  :  /home/jenkins/workspace/graphene-direct-sanitizers/libos/test/ltp/src/testcases/kernel/syscalls/setsid/setsid01.c:189: setsid failed, expected -1,return 0
[1.031] setsid01    1  TPASS  :  setsid SUCCESS to set errno to EPERM
[1.031] setsid01    1  TPASS  :  all misc tests passed
```

Could you check what happens?
</blockquote></details>

It's weird.

First I cannot reproduce this failure locally with `gramine-direct` + `asan` (using varied ways of running LTP tests, incl. the same parameters w/ CI). But it seems that CI fails it (only explicitly w/ this `Jenkins-Direct-Sanitizers`) every time.

Second, from the log I see both success
```
[1.031] setsid01    1  TFAIL  :  /home/jenkins/workspace/graphene-direct-sanitizers/libos/test/ltp/src/testcases/kernel/syscalls/setsid/setsid01.c:189: setsid failed, expected -1,return 0
```
and failure
```
[1.031] setsid01    1  TPASS  :  setsid SUCCESS to set errno to EPERM
```
, which appears to be in the same `IF-ELSE` (I don't understand how this could happen), see:
https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L184-L191.

Something I may have missed?

___


<!-- Sent from Reviewable.io -->

2023-04-19 08:35 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTNdgnR0hyXjA0eQLRf:btcgoqb) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's weird.

First I cannot reproduce this failure locally with `gramine-direct` + `asan` (using varied ways of running LTP tests, incl. the same parameters w/ CI). But it seems that CI fails it (only explicitly w/ this `Jenkins-Direct-Sanitizers`) every time.

Second, from the log I see both success
```
[1.031] setsid01    1  TFAIL  :  /home/jenkins/workspace/graphene-direct-sanitizers/libos/test/ltp/src/testcases/kernel/syscalls/setsid/setsid01.c:189: setsid failed, expected -1,return 0
```
and failure
```
[1.031] setsid01    1  TPASS  :  setsid SUCCESS to set errno to EPERM
```
, which appears to be in the same `IF-ELSE` (I don't understand how this could happen), see:
https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L184-L191.

Something I may have missed?

</blockquote></details>

I think you should GDB it. There are too many forks in that test, I got lost and don't want to reason about that. Most probably the test lands in that line of code twice, in parent and in one of the children, something like this.

___


<!-- Sent from Reviewable.io -->

2023-04-19 12:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTBJwLbDRWZENGUeL0Y:-NTOPcJq4HP34etgDr3X:ba0z4wy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is there any downside to using them here? The interface is almost as simple as normal locks and we'd have one more place using them, so they would be tested a bit better.
</blockquote></details>

No downside other than additional effort/PR to implement them. I mean, we can't implement them right now, because the RWLock PR is not yet merged (and the timeline is unclear -- when are we going to merge it?). So we'll need to create a GitHub issue to track it, then create a PR that will close this issue... Just too many movements.

___


<!-- Sent from Reviewable.io -->

2023-04-19 12:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTONO5y6WfAz6IgUnct:b-d2xbzy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should GDB it. There are too many forks in that test, I got lost and don't want to reason about that. Most probably the test lands in that line of code twice, in parent and in one of the children, something like this.
</blockquote></details>

I reproduced this issue on another machine and investigated a bit -- it seems that clang optimized out the `IF` here (https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L167-L175) and the test then goes into the `ELSE` (https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176) twice. And in the one which is actually `child_2`, `setpgid(0, getppid())` will not update its `pgid` (thus not attached to a new pg) and the following `setsid()` will succeed which'll (partially) fail the test.

Pls kindly see the `objdump -S` result below:
```
        if ((pid = FORK_OR_VFORK()) == -1) {
  403dbb:       e8 a0 b2 00 00          call   40f060 <tst_fork>
  403dc0:       83 f8 ff                cmp    $0xffffffff,%eax
  403dc3:       75 1e                   jne    403de3 <do_child_1+0x73>
                tst_brkm(TFAIL, NULL, "Fork failed");
  403dc5:       bf 0d 50 41 00          mov    $0x41500d,%edi
  403dca:       41 b8 71 50 41 00       mov    $0x415071,%r8d
  403dd0:       be a5 00 00 00          mov    $0xa5,%esi
  403dd5:       ba 01 00 00 00          mov    $0x1,%edx
  403dda:       31 c9                   xor    %ecx,%ecx
  403ddc:       31 c0                   xor    %eax,%eax
  403dde:       e8 ad b5 00 00          call   40f390 <tst_brkm_>
  403de3:       89 c5                   mov    %eax,%ebp
                retval = setpgid(0, getppid());
  403de5:       e8 96 fb ff ff          call   403980 <getppid@plt>
  403dea:       31 ff                   xor    %edi,%edi
  403dec:       89 c6                   mov    %eax,%esi
  403dee:       e8 4d fb ff ff          call   403940 <setpgid@plt>
                if (retval < 0) {
```

So we could either skip this test or skip it for clang (not sure if this requires a new LTP cfg).

___


<!-- Sent from Reviewable.io -->

2023-04-19 13:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTBJwLbDRWZENGUeL0Y:-NTOjhJY8fCWmrI3oIrg:bqyx1yw) (no related file):*
> I mean, we can't implement them right now, because the RWLock PR is not yet merged

Yeah, but we can wait for it, it's mostly ready.

> and the timeline is unclear -- when are we going to merge it?

Borys said that we can work on it around this weekend.

> So we'll need to create a GitHub issue to track it, then create a PR that will close this issue... Just too many movements.

Nah, I wanted to wait for RW locks.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOl13a1LRqDVJ8utg-:b-j8zj8d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is extremely weird, I can't understand why Clang would ignore this check (https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L167)

But based on the objdump, indeed, looks like the check was simply removed, and even for `pid==0` we end up calling `setpgid()`. I see no reason for Clang to optimize this out...

Could you investigate this case a bit more? What is the Clang version that you used?

I'd like to understand the root cause before we mark this test as "invalid for Gramine". And ideally we'd like to file a GitHub issue for LTP folks.
</blockquote></details>

Are you sure you're looking at the right place in the source? There's a similar one a few lines above with a bug which matches your description:

https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L95-L100

___


<!-- Sent from Reviewable.io -->

2023-04-19 13:55 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOjFMz9Fo03S5tMa0p:b-g25o37) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are you sure you're looking at the right place in the source? There's a similar one a few lines above with a bug which matches your description:

https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L95-L100
</blockquote></details>

FYI: I was able to replicate the objdump provided by Kailun, here is the relevant snippet:
```
~/gramineproject/gramine/libos/test/ltp/src/testcases/kernel/syscalls/setsid$ clang -O2 \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/build/include \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/src/include/old \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/src/include setsid01.c \
  /home/dimakuv/gramineproject/gramine/libos/test/ltp/src/lib/*.c -laio -pthread -lrt

objdump -D ./a.out | less
```

But I don't see anything special there, judging by `strace --ff ./a.out`. Everything looks fine. I do believe this test exposes some corner case in our Gramine dummy implementation.

___


<!-- Sent from Reviewable.io -->

2023-04-19 14:06 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOpeA_CPGqwO8gbufT:bcs48aw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I was able to replicate the objdump provided by Kailun, here is the relevant snippet:
```
~/gramineproject/gramine/libos/test/ltp/src/testcases/kernel/syscalls/setsid$ clang -O2 \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/build/include \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/src/include/old \
  -I/home/dimakuv/gramineproject/gramine/libos/test/ltp/src/include setsid01.c \
  /home/dimakuv/gramineproject/gramine/libos/test/ltp/src/lib/*.c -laio -pthread -lrt

objdump -D ./a.out | less
```

But I don't see anything special there, judging by `strace --ff ./a.out`. Everything looks fine. I do believe this test exposes some corner case in our Gramine dummy implementation.
</blockquote></details>

@dimakuv: What about the bug I pointed out above?

___


<!-- Sent from Reviewable.io -->

2023-04-19 14:09 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTBJwLbDRWZENGUeL0Y:-NTOqA2O8C80jCNhJYQj:b-s2kkth) (no related file):*
> Borys said that we can work on it around this weekend.

Ah, good, we can wait then.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOqGjF9R8SVhEKBm8r:b146fbs) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: What about the bug I pointed out above?
</blockquote></details>

I don't see a bug there? What do you mean by "bug"?

___


<!-- Sent from Reviewable.io -->

2023-04-19 14:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOqvMC1CZPIrdV1AkT:byqk6nl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see a bug there? What do you mean by "bug"?
</blockquote></details>

Ah, wait, I missed that this variable is reused there, sorry.
btw. `tst_resm()` is not exiting the test, just prints the results. Maybe that's an issue here? On a failure you still execute the ELSE branch, but that shouldn't confuse the optimizer...

Anyways, my guess is that there's an UB somewhere in that LTP code, seems more probable than a clang bug. We've hit many LTP bugs in the past.

___


<!-- Sent from Reviewable.io -->

2023-04-19 14:27 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOsjk2Dbpd0wUuvC67:b7z83bs) (no related file):*
> What is the Clang version that you used?

I did some quick testing -- it seems that clang-10 (default in ubuntu20.04) has this issue but with clang-12 and clang-14 it's fine.

___


<!-- Sent from Reviewable.io -->

2023-04-19 14:30 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTOukjw2k4LR6E1nup6:b-k0o4gw) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> What is the Clang version that you used?

I did some quick testing -- it seems that clang-10 (default in ubuntu20.04) has this issue but with clang-12 and clang-14 it's fine.
</blockquote></details>

Could you show straces for Clang 10 and Clang 12/14? I mean, I have Clang 10, and the test works fine on my machine, and I don't see anything special/any bug in the strace of Clang 10 compiled binary.

So still -- what is the bug? I can't wrap my head around this.

___


<!-- Sent from Reviewable.io -->

2023-04-19 18:30 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTPkhMcBSsg9MhPLR6m:buzeop7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you show straces for Clang 10 and Clang 12/14? I mean, I have Clang 10, and the test works fine on my machine, and I don't see anything special/any bug in the strace of Clang 10 compiled binary.

So still -- what is the bug? I can't wrap my head around this.
</blockquote></details>

The bug is a long-standing LLVM bug in handling infinite loops (namely, assuming them to be UB) regardless of what the source language thinks of it.  The bug has only been fixes as of LLVM 12.  There is such a loop in `do_child_2`.  The bug can be easily worked around by inserting `asm volatile ("");` into the loop body.

See also:

- https://bugs.llvm.org/show_bug.cgi?id=965 (the bug)
- https://lists.llvm.org/pipermail/llvm-dev/2015-July/088095.html (initial discussion about the issue)
- https://github.com/rust-lang/rust/issues/28728 (an issue in Rust triggered by the underlying bug)

___


<!-- Sent from Reviewable.io -->

2023-04-20 01:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTRDQPW3XFUnz9TobSl:b97ti6b) (no related file):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

The bug is a long-standing LLVM bug in handling infinite loops (namely, assuming them to be UB) regardless of what the source language thinks of it.  The bug has only been fixes as of LLVM 12.  There is such a loop in `do_check_2`.  The bug can be easily worked around by inserting `asm volatile ("");` into the loop body.

See also:

- https://bugs.llvm.org/show_bug.cgi?id=965 (the bug)
- https://lists.llvm.org/pipermail/llvm-dev/2015-July/088095.html (initial discussion about the issue)
- https://github.com/rust-lang/rust/issues/28728 (an issue in Rust triggered by the underlying bug)
</blockquote></details>

@mwkmwkmwk Cool! Thanks for the reference!

@dimakuv With the straces for Clang 10 and Clang 12 (sent to you offline), do they resolve your confusions above?

___


<!-- Sent from Reviewable.io -->

2023-04-20 06:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTSN9PR7b6xlUbcBrf6:b-wuiles) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@mwkmwkmwk Cool! Thanks for the reference!

@dimakuv With the straces for Clang 10 and Clang 12 (sent to you offline), do they resolve your confusions above?

</blockquote></details>

Ok, so it's a bug in Clang/LLVM. @kailun-qin Could you please skip `setsid01` LTP test then, and add the comment about breaking on Clang < 12, and add one of the web links above.

___


<!-- Sent from Reviewable.io -->

2023-04-20 08:09 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: 14 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NTNTpZT3KHR5BmMzl55:-NTSglOHC_vY4XsqffgN:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, so it's a bug in Clang/LLVM. @kailun-qin Could you please skip `setsid01` LTP test then, and add the comment about breaking on Clang < 12, and add one of the web links above.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-04-20 08:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-12 07:28 UTC, dimakuv approved these changes
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-16 07:22 UTC, jinengandhi-intel reviewed
@kailun-qin we had triggered a local CI nightly on this PR and found a regression with one of the `stress-ng daemon` test. It is failing with multiple `Failed to send IPC msg to 3: Broken pipe (EPIPE)` error messages which is not the case when we run the same test with the current master. It fails for both `gramine-direct` and gramine-sgx`. 

Log file attached: 
[gramine-direct-stress-ng-daemon-setsid_pr.txt](https://github.com/gramineproject/gramine/files/11485136/gramine-direct-stress-ng-daemon-setsid_pr.txt)

Steps to reproduce:
1. Install stress-ng: `sudo apt-get install stress-ng`
2. You can use the manifest template and Makefile from here: https://github.com/jinengandhi-intel/graphene_local_ci/tree/master/stress-ng
3. Run the make command: `make`
4. Command to run the test: `gramine-direct stress-ng --daemon 1 --timeout 60s --verbose --temp-path /tmp`

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264#-:-NVYO6F2-2G4yEdA4Tue:bwby8gs)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-16 11:18 UTC, kailun-qin reviewed
> but this test is successfully running with the current master
> When we enabled stress-ng, we just ran the full suite with gramine and the tests that were passing were enabled in local CI and this test has been running and passing since long

Yes, it's running successfully w/ the current master and it's not showing errors since long simply because the stresser child returns directly on `setsid()` failures and the error status is not captured/checked by the child nor by the parent.

Pls kindly see https://github.com/ColinIanKing/stress-ng/blob/09433fdf062c824152dd56ad94e9cea1c6a27ddf/stress-daemon.c#L51-L52 and https://github.com/ColinIanKing/stress-ng/blob/09433fdf062c824152dd56ad94e9cea1c6a27ddf/stress-daemon.c#L154 for details.

So in a so-called "successful" run, we'll see sth. like:
```
stress-ng: debug: [1] 1 stressor spawned
stress-ng: debug: [33] stress-ng-daemon: exited [33] (instance 0)
```
while in a failed run w/ this PR, we'll have:
```
stress-ng: debug: [1] 1 stressor spawned
[P4:T65:stress-ng] error: Failed to send IPC msg to 3: Broken pipe (EPIPE)
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264#-:-NVZCuaCDWzeMNywpkbg:b-jbj5t4)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-16 11:42 UTC, jinengandhi-intel reviewed
Got it. Thanks for the explanation. It seems like we just have to disable the test until the daemonization is enabled completely in Gramine.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264#-:-NVZMMtw0p8INpVNemD_:b-38pqv1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-16 11:42 UTC, jinengandhi-intel reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264#-:-NVZMc4M7UkXD89FRKCF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-11 02:39 UTC, mkow requested changes
> daemonization is enabled completely in Gramine

@jinengandhi-intel: Please stop using "enabled" in the meaning of "implemented". Each time I read anything coming from Intel employees I have to guess whether by "enabled" you mean "enabled" or "implemented" (and you use this word in both meanings, see e.g. that this PR's description uses the standard meaning). This is really confusing.
We could enable daemonization if it was disabled for some reason (e.g. a security issue). But that's _not_ the case, it's just not implemented at all in Gramine.

> Reviewed 1 of 15 files at r1, 1 of 1 files at r4, 11 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264#-:-NXbk3_sBf7tQy0eACPS:btzw7vh)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbj_4YAZkXcaqAV4Gg:-NXbj_4YAZkXcaqAV4Gh:beu7u4t) (no related file):*
TODO for myself: check locking on all accesses to the modified members in the final version of the PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbvQtdE7qrA3-hvSeG:-NXbvQtdE7qrA3-hvSeH:b-8zd2uk) (no related file):*

> Reasons why `attached_to_other_pg` is introduced:
> 
> -   When the process group having forked of a child and then it attached itself to another process group and tries to setsid, it should fail w/ `EPERM`, see the example of `setsid01` in LTP: [https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176-L191](https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176-L191)

As I understand, this fails because `setsid()` tries to create a process group with ID being `pid_of_the_caller` (by the definition of what `setsid()` does), but this group already exists, so it has to fail.

> -   The underlying kernel logic: `setsid()` should fail if a process group id already exists that equals the proposed session id ([https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1222](https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1222)).  This process group id is actually set on `setpgid()` when the specified `pgid` points to a different process group ([https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1116](https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1116)) via `change_pid()` -> `attach_pid()` ([https://elixir.bootlin.com/linux/v6.2/source/kernel/pid.c#L334](https://elixir.bootlin.com/linux/v6.2/source/kernel/pid.c#L334)).

I don't think that this `setpgid()` matters much here, it just forces the test to actually test a slightly more complicated case (where this ID is used by a different process than our own - it fails because the child is still using our PID as its PGID).

Anyways, I don't see how is this semantic relevant to this weird `attached_to_other_pg` boolean added in this PR. It feels to me more like IF-ing out the specific LTP test than implementing Linux' semantics.

___
___
*[`libos/include/libos_process.h` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbdWh7Dh-CFwMSdFPC:-NXbdWh7Dh-CFwMSdFPD:b-n3i4bq) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/include/libos_process.h#L46)):*
> ```objc
>     /* Indicates whether the process has been attached to another process group. Protected by
>      * `g_process_id_lock`. */
>     bool attached_to_other_pg;
> ```

Doesn't this just store the value of `this->pgid != this->pid`? If so, what's the point of storing it? If not, what's the value it stores?
___
*[`libos/src/bookkeep/libos_process.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXblpd8-QgdOIrgnOoT:-NXblpd9B1q4oJV7VK6a:bhcyjkk) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/bookkeep/libos_process.c#L254)):*
> ```C
>     new_process->ppid = process->ppid;
>     new_process->pgid = process->pgid;
>     /* attached_to_other_pg is set to false in libos/src/sys/libos_clone.c: do_clone_new_vm() */
> ```

What's the purpose of this comment?
I don't like it because I don't like duplicating the values set in one place in different places - if we change something in `do_clone_new_vm()` the chance that we'll notice that we also need to update this comment seems really small.
___
*[`libos/src/sys/libos_clone.c` line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiFAeEx5dd008gN-S:-NXbiFAeEx5dd008gN-T:b-gzh7e8) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_clone.c#L172)):*
> ```C
>         .ppid = g_process.pid,
>         .pgid = g_process.pgid,
>         /* on fork, child process is attached to the same process group as parent */
> ```

Why is this comment on `.attached_to_other_pg = false` line instead of `.pgid = g_process.pgid`? It's the `pgid` assignment which sets the group to the parent's group.
___
*[`libos/src/sys/libos_getpid.c` line 5 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiT2A1lk657H1-5WE:-NXbiT2A1lk657H1-5WF:b-841m6s) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L5)):*
> ```C
>  * Copyright (C) 2020 Intel Corporation
>  *                    Borys Popławski <borysp@invisiblethingslab.com>
>  */
> ```

Please add your copyright reminder here, that's IMO a significant change.
___
*[`libos/src/sys/libos_getpid.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbpf3U6Zd7P3Qz7S-v:-NXbpf3U6Zd7P3Qz7S-w:bf55lhb) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L47)):*
> ```C
>         /* TODO: Currently we do not support checking that the process group of the joining process
>          * (specified by `pid`) and the existing process group to be joined (specified by `pgid`)
>          * must have the same session ID. */
> ```

I think this is also missing verification whether the target `pgid` even at all exists.
___
*[`libos/src/sys/libos_getpid.c` line 89 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbqQKBASxNqEN0L1GO:-NXbqQKBASxNqEN0L1GP:b-u4y06g) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L89)):*
> If the caller is already a group leader or attached to another process group

I don't get this. You can sometimes be a leader or some process group and you're always a member of some process group. The quoted sentence seems to be true for all processes on Linux.
___
*[`libos/src/sys/libos_getpid.c` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbsZUe0xZ-_SIvzXig:-NXbsZUe0xZ-_SIvzXih:bbjtgds) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L105)):*
> ```C
>     g_process.sid = current_pid;
>     g_process.pgid = current_pid;
>     g_process.attached_to_other_pg = true;
> ```

Why is this set to `true` here? We're now the leader of our group, how can we be in "another" group at the same time? I'm really confused now.
___
*[`libos/test/regression/sid.c` line 18 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbr7hqBQnCCuWUxv_c:-NXbr7hqBQnCCuWUxv_d:b-7tq84h) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/test/regression/sid.c#L18)):*
> ```C
>     /* Parent is already a process group leader so setsid() should fail. */
>     errno = 0;
>     setsid();
> ```

Please also check the retval.
___
*[`li [...]

2023-06-11 14:39 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbvQtdE7qrA3-hvSeG:-NXepRv41menLDNf14pU:b-5gd5h3) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>


> Reasons why `attached_to_other_pg` is introduced:
> 
> -   When the process group having forked of a child and then it attached itself to another process group and tries to setsid, it should fail w/ `EPERM`, see the example of `setsid01` in LTP: [https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176-L191](https://github.com/linux-test-project/ltp/blob/7015b2e2c6c16f97fcfed29510b3ef67da7e2ebb/testcases/kernel/syscalls/setsid/setsid01.c#L176-L191)

As I understand, this fails because `setsid()` tries to create a process group with ID being `pid_of_the_caller` (by the definition of what `setsid()` does), but this group already exists, so it has to fail.

> -   The underlying kernel logic: `setsid()` should fail if a process group id already exists that equals the proposed session id ([https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1222](https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1222)).  This process group id is actually set on `setpgid()` when the specified `pgid` points to a different process group ([https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1116](https://elixir.bootlin.com/linux/v6.2/source/kernel/sys.c#L1116)) via `change_pid()` -> `attach_pid()` ([https://elixir.bootlin.com/linux/v6.2/source/kernel/pid.c#L334](https://elixir.bootlin.com/linux/v6.2/source/kernel/pid.c#L334)).

I don't think that this `setpgid()` matters much here, it just forces the test to actually test a slightly more complicated case (where this ID is used by a different process than our own - it fails because the child is still using our PID as its PGID).

Anyways, I don't see how is this semantic relevant to this weird `attached_to_other_pg` boolean added in this PR. It feels to me more like IF-ing out the specific LTP test than implementing Linux' semantics.
</blockquote></details>

I agree w/ all the above comments from @mkow (thanks!).

This `attached_to_other_pg` is actually more like a workaround for certain cases where we need to check whether a process group already exsits (which is currently unsupported in Gramine). It's confusing and does not make sense. I removed it and simply added more comments for this limitation.

___
___
*[`libos/include/libos_process.h` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbdWh7Dh-CFwMSdFPC:-NXeqPE67alWo2ooEEnS:b-lcil0a) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/include/libos_process.h#L46)):*
> Doesn't this just store the value of `this->pgid != this->pid`?

Not exactly, since `this->pgid != this->pid` is always true in case of forked childs but they should still be able to create new sessions (i.e., `setsid()` shouldn't fail in this case). Anyway, not relevant any more.
___
*[`libos/src/bookkeep/libos_process.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXblpd8-QgdOIrgnOoT:-NXepiDg147_s3w0jSDt:bwd8vv8) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/bookkeep/libos_process.c#L254)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the purpose of this comment?
I don't like it because I don't like duplicating the values set in one place in different places - if we change something in `do_clone_new_vm()` the chance that we'll notice that we also need to update this comment seems really small.
</blockquote></details>

Not relevant any more.
___
*[`libos/src/sys/libos_clone.c` line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiFAeEx5dd008gN-S:-NXeplbA8NBprrWzSSr_:bwd8vv8) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_clone.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this comment on `.attached_to_other_pg = false` line instead of `.pgid = g_process.pgid`? It's the `pgid` assignment which sets the group to the parent's group.
</blockquote></details>

Not relevant any more.
___
*[`libos/src/sys/libos_getpid.c` line 5 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiT2A1lk657H1-5WE:-NXepo5HBS_t-1c6T2fH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add your copyright reminder here, that's IMO a significant change.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_getpid.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbpf3U6Zd7P3Qz7S-v:-NXeposD8ndUPcEc7Yy9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this is also missing verification whether the target `pgid` even at all exists.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_getpid.c` line 89 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbqQKBASxNqEN0L1GO:-NXepqiY-kFg-H-cxr-j:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If the caller is already a group leader or attached to another process group

I don't get this. You can sometimes be a leader or some process group and you're always a member of some process group. The quoted sentence seems to be true for all processes on Linux.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_getpid.c` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbsZUe0xZ-_SIvzXig:-NXeprHv4TpXM3MjTsXD:bwd8vv8) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this set to `true` here? We're now the leader of our group, how can we be in "another" group at the same time? I'm really confused now.
</blockquote></details>

Not relevant any more.
___
*[`libos/test/regression/sid.c` line 18 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbr7hqBQnCCuWUxv_c:-NXeps9Q4gTPC3Sc1dQD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/test/regression/sid.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also check the retval.
</blockquote></details>

Done.
___
*[`libos/test/regression/sid.c` line 23 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbrMUs0NHbrSqZ5xE_:-NXepsqg5C11ZeQPQb8w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/test/regression/sid.c#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please check for errors (on Linux this probably can't fail, but the purpose of this test is to verify Gramine which may have such bugs).
</blockquote></details>

Done.
___
*[`libos/test/regression/sid.c` line 61 at r5](https://reviewabl [...]

2023-06-11 20:20 UTC, mkow requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbvQtdE7qrA3-hvSeG:-NXfVTdd3QbBDHlzF6oY:b-eyrlvj) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I agree w/ all the above comments from @mkow (thanks!).

This `attached_to_other_pg` is actually more like a workaround for certain cases where we need to check whether a process group already exsits (which is currently unsupported in Gramine). It's confusing and does not make sense. I removed it and simply added more comments for this limitation.
</blockquote></details>

Technically this _is_ supported in Gramine (see e.g. `ipc_get_id_owner()`), but would require a bunch of changes to support this weird semantics of process groups and sessions - for example, you'd need to add support for refcount-like semantics to the IDs, so that other processes using an ID for their process group ID would still hold the ID locked even if the leader already died.

Not sure if that's worth it though, we don't support many other things required for daemonization to work, we can implement this when (and if) we'll be working on that.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbj_4YAZkXcaqAV4Gg:-NXg5jtE8nNLN2_-151-:bzd8kfd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: check locking on all accesses to the modified members in the final version of the PR.
</blockquote></details>

Done, no bugs found.

___
___
*[`libos/include/libos_process.h` line 46 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbdWh7Dh-CFwMSdFPC:-NXfSciE53UeAWzTARXe:blh4y6d) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/include/libos_process.h#L46)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Doesn't this just store the value of `this->pgid != this->pid`?

Not exactly, since `this->pgid != this->pid` is always true in case of forked childs but they should still be able to create new sessions (i.e., `setsid()` shouldn't fail in this case). Anyway, not relevant any more.
</blockquote></details>

It can't _always_ be true, because the children can create their own groups? If that would be the case, then this would be always true for all Linux processes except `init`, because all processes are chlidren of some other process :)
___
*[`libos/src/sys/libos_getpid.c` line 5 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiT2A1lk657H1-5WE:-NXfTvqr3hb3cmsj4qg5:b330pkf) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L5)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

2020 -> 2023
___
*[`libos/test/ltp/ltp.cfg` line 2072 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg2BqhD5GGKfrUwYOe:-NXg2Bqi4a8Yqx9naI9L:b-tjn4iy) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/ltp/ltp.cfg#L2072)):*
> ```INI
> # still in use by `child_2`) and expects failure in that case. This is however unsupported in
> # Gramine. Note that the test is also broken on Clang < 12 where Clang/LLVM handles infinite loops
> # incorrectly. See https://bugs.llvm.org/show_bug.cgi?id=965.
> ```

This description is really confusing, I wouldn't understand it if I didn't already know how all of this works - it's not the test checking "if the proposed session id equals a process group id that already exists" - this is done by the tested kernel. The test tries to create such a session with a colliding ID. Also, the test is not proposing the session ID anywhere? `setsid()` doesn't allow for this.
___
*[`libos/test/regression/sid.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg36mr2JqFH2btkddo:-NXg36mr2JqFH2btkddp:b3wiom6) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L16)):*
> ```C
> 
> int main(int argc, const char** argv) {
>     /* Parent is already a process group leader so setsid() should fail. */
> ```

What parent?
___
*[`libos/test/regression/sid.c` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg3fGv1KuNo_-iGhSI:-NXg3fGv1KuNo_-iGhSJ:bl47jtw) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L20)):*
This seems to rely on some hidden assumptions. E.g. this fails natively:
```
> echo | ./sid
sid: Parent: unexpected setsid error (expected: 1, actual: 0)
```
If there's no simple way to remove these assumptions then please at least document them explicitly.
___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXg4mF36IotMmShAHW8:b-vxwnbh) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
> ```C
>          * process ID). */
>         sid = CHECK(setsid());
>         if (sid != getpid() || getpgid(0) != sid) {
> ```

Please also check `getsid(0)` here and in the analogous place below.


<!-- Sent from Reviewable.io -->

2023-06-12 01:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbvQtdE7qrA3-hvSeG:-NXh5CvTC0Oqgop-9XWx:b-plshlp) (no related file):*
> Technically this _is_ supported in Gramine (see e.g. `ipc_get_id_owner()`), but would require a bunch of changes.
> Not sure if that's worth it though, we don't support many other things required for daemonization to work, we can implement this when (and if) we'll be working on that.

Yeah, agree w/ both.

___
___
*[`libos/src/sys/libos_getpid.c` line 5 at r5](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXbiT2A1lk657H1-5WE:-NXh5bPq1Zao_ALRWjQp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01643ee34be0484488d080792df7bda03be04fe2/libos/src/sys/libos_getpid.c#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

2020 -> 2023
</blockquote></details>

Done.
___
*[`libos/test/ltp/ltp.cfg` line 2072 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg2BqhD5GGKfrUwYOe:-NXh5c9iDFqLPIy9rRuz:b-xp0109) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/ltp/ltp.cfg#L2072)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This description is really confusing, I wouldn't understand it if I didn't already know how all of this works - it's not the test checking "if the proposed session id equals a process group id that already exists" - this is done by the tested kernel. The test tries to create such a session with a colliding ID. Also, the test is not proposing the session ID anywhere? `setsid()` doesn't allow for this.
</blockquote></details>

I reworded a bit, pls see if it's a bit btter.
___
*[`libos/test/regression/sid.c` line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg36mr2JqFH2btkddo:-NXh5iSe19L4Lz8GLJmx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What parent?
</blockquote></details>

Done.
___
*[`libos/test/regression/sid.c` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg3fGv1KuNo_-iGhSI:-NXh5iwGCzciyJkc5b5n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems to rely on some hidden assumptions. E.g. this fails natively:
```
> echo | ./sid
sid: Parent: unexpected setsid error (expected: 1, actual: 0)
```
If there's no simple way to remove these assumptions then please at least document them explicitly.
</blockquote></details>

Done.
___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXh5vgy7Uyi5atjXnzx:b-l7f620) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also check `getsid(0)` here and in the analogous place below.
</blockquote></details>

I think you meant `getpgid(0)`? If so, then done.


<!-- Sent from Reviewable.io -->

2023-06-12 01:22 UTC, mkow requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/ltp/ltp.cfg` line 2072 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg2BqhD5GGKfrUwYOe:-NXhAx2OBMK-Znlg9IZ6:bx3ia3s) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/ltp/ltp.cfg#L2072)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I reworded a bit, pls see if it's a bit btter.
</blockquote></details>

Yup, now it's clear to me what it does and why it doesn't work :)
___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXhBBdx3tw59JfZ_Rzz:bx187dg) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think you meant `getpgid(0)`? If so, then done.
</blockquote></details>

That's also a good things (which I missed), but I meant calling `getsid(0)` to check if the returned value is  now different after `setsid()` ;) Right now you only check the retval from `setsid()`.


<!-- Sent from Reviewable.io -->

2023-06-12 01:50 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXhHxM89kNWfP_MSEqG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's also a good things (which I missed), but I meant calling `getsid(0)` to check if the returned value is  now different after `setsid()` ;) Right now you only check the retval from `setsid()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-12 02:13 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: 14 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXhMiRR3ACcHstAFWJz:bebke9t) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd rather make the check exact. Right now we fail only if `getsid(0) == sid`, but we can make this exact, i.e. fail if `getsid(0) != new_sid || new_sid == sid`.


<!-- Sent from Reviewable.io -->

2023-06-12 02:14 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/sid.c` line 37 at r6](https://reviewable.io/reviews/gramineproject/gramine/1264#-NXg4mF36IotMmShAHW7:-NXhNMCm3UEll-KPlzh3:b-qe04j7) ([raw file](https://github.com/gramineproject/gramine/blob/b40e72759787997cc4f38aac62cd3f860925d8f1/libos/test/regression/sid.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather make the check exact. Right now we fail only if `getsid(0) == sid`, but we can make this exact, i.e. fail if `getsid(0) != new_sid || new_sid == sid`.
</blockquote></details>

Ah, you just pushed exactly this in the meantime :)


<!-- Sent from Reviewable.io -->

2023-06-12 08:22 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-12 10:34 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1264)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-12 10:37 UTC, merged