[LibOS] Don't allow removal of pseudo-files
gramineproject/gramine pull request #1266
Opened 2023-04-04 08:52 UTC by dimakuv

## Description of the changes 

Pseudo-files under `/dev`, `/proc` and `/sys` should not be removable.

This was noticed by @mkow in #1249.

## How to test this PR? 

Added a quick sub-test in one of the LibOS regression tests. Also you can try manually via e.g. Busybox example.

2023-04-04 08:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1266#-NSATGFm6uMPl3eqiHno:-NSATGFm6uMPl3eqiHnp:b-ougccz) (no related file):*
The bug of removal of not-supposed-to-be-removed files happened because of this code snippet: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/libos/src/sys/libos_file.c#L65-L75

Basically, if the FS implementation doesn't expose the `unlink()` callback, then the generic implementation in `libos_syscall_unlinkat()` assumes that there are no FS-specific actions for unlinking, and continues with simply removing the `inode` of the dentry. This is probably meaningful for some in-Gramine removable FS implementations, so I didn't want to modify this part. Instead, this PR adds the `unlink()` callback to pseudo-FSes.

___
___
*[`libos/test/regression/proc_cpuinfo.c` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1266#-NSATAE2DJbQIqxCRGNi:-NSATAE2DJbQIqxCRGNj:b-ly7fm3) ([raw file](https://github.com/gramineproject/gramine/blob/580db78cfd74972b8276eedf5c2f83c69dc8bb3b/libos/test/regression/proc_cpuinfo.c#L2)):*
> ```C
> #define _GNU_SOURCE
> #include <err.h>
> ```

FYI: Decided to update the test as well to our newer guidelines.


<!-- Sent from Reviewable.io -->

2023-04-04 16:36 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/proc_cpuinfo.c` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/1266#-NSC6wIFEsw1NbaSKxso:-NSC6wIFEsw1NbaSKxsp:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/580db78cfd74972b8276eedf5c2f83c69dc8bb3b/libos/test/regression/proc_cpuinfo.c#L213)):*
> ```C
> 
>     rv = unlink(CPUINFO_FILE);
>     if (rv != -1 && errno != EACCES)
> ```





_Suggestion:_
```C
if (rv != -1 || errno != EACCES)
```


<!-- Sent from Reviewable.io -->

2023-04-05 07:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/proc_cpuinfo.c` line 213 at r1](https://reviewable.io/reviews/gramineproject/gramine/1266#-NSC6wIFEsw1NbaSKxso:-NSFPJhx6U6A807VvW5v:bm3117e) ([raw file](https://github.com/gramineproject/gramine/blob/580db78cfd74972b8276eedf5c2f83c69dc8bb3b/libos/test/regression/proc_cpuinfo.c#L213)):*
> ```C
> 
>     rv = unlink(CPUINFO_FILE);
>     if (rv != -1 && errno != EACCES)
> ```

Done. Oops, typo.


<!-- Sent from Reviewable.io -->

2023-04-05 12:39 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-05 12:56 UTC, dimakuv commented
Jenkins, retest all please (I forgot the correct form to trigger you, Jenkins?)

2023-04-06 01:13 UTC, kailun-qin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266#-:-NSJ74Jx51Qek0a2rM3x:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-12 01:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1266)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-12 01:42 UTC, merged