[PAL/Linux-SGX] Verify OCALL-obtained time against last RDTSC time
gramineproject/gramine pull request #1276
Opened 2023-04-11 05:53 UTC by kailun-qin

## Description of the changes 
Previously, Gramine did not verify the read-from-Linux-host timestamp against the last RDTSC time. So it is possible periodically that the previous timestamp (calculated via RDTSC) is greater than the current timestamp (read from Linux host via OCALLs), which can lead to the intermittent failure of LTP test `gettimeofday02` on some configurations with indication that "time is going backwards". This could be even security-relevant since the app running inside the enclave may behave unexpectedly if time teleports back.

This commit adds a sanity adjustment which guarantees no rewinding time is applied when the OCALL-obtained timestamp is "back in time" than the last recorded RDTSC timestamp.

Fixes https://github.com/gramineproject/gramine/issues/82.

## How to test this PR? 
CI + LTP tests on specific configs mentioned in the original issue.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1276)

2023-04-11 09:19 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjITEd508rLtl0LLTy:-NSjYLxJDjNnnee2GpHG:bb6xxxw) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L104)):*
> Why did you put the code under the else branch?

I was indeed hesitating when making this change. But otherwise, we would update `g_start_tsc -> tsc_cyc`but `g_start_usec -> last_usec_rdtsc`?


<!-- Sent from Reviewable.io -->

2023-04-11 09:33 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjITEd508rLtl0LLTy:-NSjdGwg2VSEJ8T81aNS:b9bo4w4) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L104)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Why did you put the code under the else branch?

I was indeed hesitating when making this change. But otherwise, we would update `g_start_tsc -> tsc_cyc`but `g_start_usec -> last_usec_rdtsc`?
</blockquote></details>

Yep, but it doesn't seem to be a problem? In fact, it's what we want I think.

- `g_start_usec` contains the last-baseline-timestamp, kept in microseconds
- `g_start_tsc` contains the last-baseline-timestamp, kept in TSC (cycles)

These two variables are used to calculate the "current timestamp in microseconds" from these two baseline values (by taking `g_start_usec`, and adding to it the "approx time passed in microseconds" based on `g_start_tsc` plus current TSC value).

So in your code, we update `g_start_tsc` to some timestamp in microseconds, and we must also associate a timestamp in TSC to it. We can think of your code as "update `g_start_tsc` to some kinda random value", and TSC value will be roughly the value at this update/assignment time. And `tsc_cyc` is exactly such a rough value.

(Hm, I have a hard time explaining this in words. I hope my text above makes sense to you.)


<!-- Sent from Reviewable.io -->

2023-04-11 09:56 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjITEd508rLtl0LLTy:-NSji3S29IiByEiE9XYY:b-l142ej) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L104)):*
> So in your code, we update g_start_tsc to some timestamp in microseconds, and we must also associate a timestamp in TSC to it. 

I think it's a typo here -- should be `g_start_usec`?

> We can think of your code as "update g_start_tsc to some kinda random value", and TSC value will be roughly the value at this update/assignment time. And tsc_cyc is exactly such a rough value.

Thanks for the explanation! It resolved my confusions. Updated.


<!-- Sent from Reviewable.io -->

2023-04-11 10:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjITEd508rLtl0LLTy:-NSjxUQy1iTcHQXGGe6y:bwbdiwo) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L104)):*
> I think it's a typo here -- should be `g_start_usec`?

Yes, sorry, this was a typo.


<!-- Sent from Reviewable.io -->

2023-04-12 23:01 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 80 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjIuY-D9RsMhzQX8NY:-NSraa0N-4X444ZWAjzv:b-4vj20t) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks brittle in terms of data races. But I thought about it a bit and couldn't come up with a multi-threaded scenario where something could go wrong in these store/load of `last_usec_rdtsc`. (One important thing to note is that if we hit this `atomic_store` line, then we will return from this function and won't go further into the OCALL invocation -- this seems to prevent data races I was thinking of.)

So I'm not blocking, but somehow I feel uneasy about this.
</blockquote></details>

Sample race:
1. thread 1 executes up until this store, but gets interrupted right before it
2. time passes and TSC for some reason gets ahead of host time
3. thread 2 calls `_PalSystemTimeQuery()`, gets time ahead of the host time
4. thread 2 hits `_PalSystemTimeQuery()` again, but this time `diff_usec >= TSC_REFINE_INIT_TIMEOUT_USECS`, so it has to recalculate.
5. thread 1 gets rescheduled and writes super-old value into `last_usec_rdtsc`
6. thread 2 hits #82 problem like this PR never existed :) (`_PalSystemTimeQuery()` returns a lower value than in the previous call)

@kailun-qin: Please take a look at how anti-rewinding protection is written in `ocall_gettime`, I think it's done correctly there (modulo that `*microsec_ptr = microsec` which should be `*microsec_ptr = max(microsec, expected_microsec)` ideally, but it's not incorrect).
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrKr1607IYOty4RDTF:-NSrKr1607IYOty4RDTG:b-ie6lmn) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L46)):*
> ```C
> }
> 
> /* TODO: result comes from the untrusted host, introduce some schielding */
> ```

I guess this is done now? (`ocall_gettime` has an anti-time-rewinding check inside)
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 66 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrZz6n5_su8-AAG7xw:-NSrZz6n5_su8-AAG7xx:b-8wnqdp) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L66)):*
> ```C
>     uint64_t usec = 0;
>     /* Last seen RDTSC time value. This guards against time rewinding. */
>     static uint64_t last_usec_rdtsc = 0;
> ```

You mean `last_used_rdtsc` or `last_usec`?



_Code quote:_
```C
last_usec_rdtsc
```
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrYH2JCRTXUsKjrIHB:-NSrYH2JCRTXUsKjrIHC:b-1dbwv9) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L80)):*
> ```C
>                     return -PAL_ERROR_OVERFLOW;
> 
>                 __atomic_store_n(&last_usec_rdtsc, usec, __ATOMIC_RELEASE);
> ```

I'd move this to `if (usec) {` below, it would be easier to understand IMO. Or that `IF` moved here.


<!-- Sent from Reviewable.io -->

2023-04-13 03:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 80 at r1](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSjIuY-D9RsMhzQX8NY:-NSsY4W38tR2eRuFLcuh:b-9wg2jw) ([raw file](https://github.com/gramineproject/gramine/blob/1f6149f9a45b969921890e256feb09bda6152772/pal/src/host/linux-sgx/pal_misc.c#L80)):*
Good sample! Make sense to me, updated.

> I think it's done correctly there (modulo that *microsec_ptr = microsec which should be *microsec_ptr = max(microsec, expected_microsec) ideally, but it's not incorrect).

Seems better to have `*microsec_ptr = max(microsec, expected_microsec)`. I'm also updating it.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrKr1607IYOty4RDTF:-NSsXeX7C5XEXuNm5QKV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this is done now? (`ocall_gettime` has an anti-time-rewinding check inside)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 66 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrZz6n5_su8-AAG7xw:-NSsXf7c0BlFstNt1RgD:b-tjyflp) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You mean `last_used_rdtsc` or `last_usec`?
</blockquote></details>

I intended to say "last recorded timestamp" in usec, calculated via RDTSC. Anyway, I updated the naming a bit -- see if it makes sense to me.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrYH2JCRTXUsKjrIHB:-NSsYJC01YsKAO6Ck_LP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd move this to `if (usec) {` below, it would be easier to understand IMO. Or that `IF` moved here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-13 03:15 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 66 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrZz6n5_su8-AAG7xw:-NSsayyLEL--lKu12g_q:b-rwpncp) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L66)):*
> see if it makes sense to me

to you ;) sorry


<!-- Sent from Reviewable.io -->

2023-04-13 07:41 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 80 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrYH2JCRTXUsKjrIHB:-NStY7R71GGOvybRUQcR:b-kq1hgu) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L80)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not wrong now, but it's superfluous check (see my other comment).

Previously, this `if (usec)` check was to make a decision -- did we calculate the time using RDTSC, or do we need to perform an OCALL. Now that you moved this `return 0`, there's no need in the check at all.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 79 at r3](https://reviewable.io/reviews/gramineproject/gramine/1276#-NStXrqQ2kdzgNoEnXDM:-NStXrqQ2kdzgNoEnXDN:b-yhf97j) ([raw file](https://github.com/gramineproject/gramine/blob/68621a567f1bd254dccfa63aff524eec7d7920e0/pal/src/host/linux-sgx/pal_misc.c#L79)):*
> ```C
>                     return -PAL_ERROR_OVERFLOW;
> 
>                 if (usec) {
> ```

What's the point in this `if`? `usec` seems to be guaranteed to have some value (plus we protected against integer overflow above).


<!-- Sent from Reviewable.io -->

2023-04-13 08:14 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 79 at r3](https://reviewable.io/reviews/gramineproject/gramine/1276#-NStXrqQ2kdzgNoEnXDM:-NStdPrvBhtSRThHDBEJ:b-xgpj37) ([raw file](https://github.com/gramineproject/gramine/blob/68621a567f1bd254dccfa63aff524eec7d7920e0/pal/src/host/linux-sgx/pal_misc.c#L79)):*
> usec seems to be guaranteed to have some value (plus we protected against integer overflow above).

Yep, I agree. But I did not make such assumption -- if `start_tsc = 0`, `get_tsc() = 0` (due to some issues w/ the TSC of the core), we may get `diff_tsc = 0` then `usec = 0`? In that case, we may want to go to recalculate instead of return sth.? But this seems to be theoretical, I'm fine w/ removing this IF.


<!-- Sent from Reviewable.io -->

2023-04-13 09:07 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 79 at r3](https://reviewable.io/reviews/gramineproject/gramine/1276#-NStXrqQ2kdzgNoEnXDM:-NStr_zzEWoeUmGYMLbl:b-ikfrrb) ([raw file](https://github.com/gramineproject/gramine/blob/68621a567f1bd254dccfa63aff524eec7d7920e0/pal/src/host/linux-sgx/pal_misc.c#L79)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> usec seems to be guaranteed to have some value (plus we protected against integer overflow above).

Yep, I agree. But I did not make such assumption -- if `start_tsc = 0`, `get_tsc() = 0` (due to some issues w/ the TSC of the core), we may get `diff_tsc = 0` then `usec = 0`? In that case, we may want to go to recalculate instead of return sth.? But this seems to be theoretical, I'm fine w/ removing this IF.
</blockquote></details>

@kailun-qin But `usec = start_usec + diff_usec`, and `start_usec` is always a positive number (never a zero, because we have a check in the very beginning). So I don't think this would be even theoretically possible.


<!-- Sent from Reviewable.io -->

2023-04-13 09:23 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-04-13 14:17 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 66 at r2](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSrZz6n5_su8-AAG7xw:-NSusUU-20i01AxFVSAV:b-8bicdh) ([raw file](https://github.com/gramineproject/gramine/blob/d5c2ce422c81f256ca866fd9a151334521513fc3/pal/src/host/linux-sgx/pal_misc.c#L66)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> see if it makes sense to me

to you ;) sorry
</blockquote></details>

Oh, I see, the comment previously suggested that this variable holds raw RDTSC value and I was confused how can it be in μs.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 79 at r4](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSuy9707ft9phjx4eAZ:-NSuy9707ft9phjx4eA_:bzgrfph) ([raw file](https://github.com/gramineproject/gramine/blob/c9e2adf7fb19ea3803aa87b2d16a87783971556f/pal/src/host/linux-sgx/pal_misc.c#L79)):*
> ```C
>                     return -PAL_ERROR_OVERFLOW;
> 
>                 uint64_t expected_usec = __atomic_load_n(&last_usec, __ATOMIC_ACQUIRE);
> ```

I'd add a comment here stating the intention of these complications: that it's simply `last_usec = max(last_usec, usec)`, but executed atomically.


<!-- Sent from Reviewable.io -->

2023-04-18 02:44 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 79 at r4](https://reviewable.io/reviews/gramineproject/gramine/1276#-NSuy9707ft9phjx4eAZ:-NTHDmkC9pwB-dUX6EYs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c9e2adf7fb19ea3803aa87b2d16a87783971556f/pal/src/host/linux-sgx/pal_misc.c#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add a comment here stating the intention of these complications: that it's simply `last_usec = max(last_usec, usec)`, but executed atomically.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 13:44 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-19 06:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1276)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-19 06:50 UTC, merged