[Pal/Linux-SGX] Add more envvars to verify SGX quote statuses
gramineproject/gramine pull request #1286
Opened 2023-04-13 09:17 UTC by dimakuv

## Description of the changes 

Intel IAS and ECDSA/DCAP verification procedures may return different SGX quote statuses, that can be roughly divided into three classes:
1. Outdated TCB (old hardware, needs an update),
2. HW configuration needed (good hardware, but must change some BIOS settings like Hyper-Threading enabled),
3. SW configuration needed (hardware is known to be vulnerable to some kinds of exploits and this could be fixed only by using good/patched software).

Previously, Gramine's RA-TLS had a single environment variable `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` to allow/disallow all three classes. This commit introduces two more envvars.

Note that `gramine-sgx-ias-verify-report` tool still uses a single command-line argument to allow/disallow all three classes. It would be too cumbersome to introduce two more command-line args to this tool; also this tool should be used only for testing/debugging purposes.

Kudos to @jkr0103 and @BFuhry for reporting this and discussions.

## How to test this PR? 

CI tests the Intel IAS part. I manually tested the DCAP part on Azure VMs.

2023-04-13 09:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStu8rg-YIEoRjvTATF:-NStu8rh2qTX1UBYkA0O:bln9dvk) (no related file):*
If you want to know the details of possible SGX quote statuses, check this code: https://github.com/gramineproject/gramine/blob/a2166216fd795adfa7391be7fb6398116c317ee3/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L41-L65

(And read the documentation; the links can be found in this PR)

___
___
*[`.ci/lib/config.jenkinsfile` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStuJGv4UTVYqVS70Nv:-NStuJGv4UTVYqVS70Nw:b-ksq0vz) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/.ci/lib/config.jenkinsfile#L12)):*
> ```
> env.RA_TLS_ALLOW_OUTDATED_TCB_INSECURE = '1'
> env.RA_TLS_ALLOW_HW_CONFIG_NEEDED = '1'
> env.RA_TLS_ALLOW_SW_HARDENING_NEEDED = '1'
> ```

Note that these new names don't have `_INSECURE`. Please check the documentation changes as to why I think there is no need for such a suffix.
___
*[`Documentation/manpages/gramine-sgx-ias-verify-report.rst` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStuSPK9TacUp7wKIX8:-NStuSPL5HB5K7zz_yF2:budro2) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L45)):*
> ```reStructuredText
> .. option:: -o, --allow-outdated-tcb
> 
>    Treat non-terminal IAS statuses as OK.
> ```

This is not good, I'm using the non-matching name of the command-line arg in this `gramine-sgx-ias-verify-report` tool. But I didn't want to add two more command-line args (we'll need to find alphabet letters for them, and this tool already uses all the good letters). And I also think nobody really uses this tool, other than maybe for testing?

Anyway, if anyone wants to force me to introduce 3 correct command-line args, then please give me the short and long names for them. I have no idea.


<!-- Sent from Reviewable.io -->

2023-04-13 09:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 0 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStv2K4Abf0MD-oDxBc:-NStv2K4Abf0MD-oDxBd:bcvo3fu) (no related file):*
@jkr0103 @BFuhry @kailun-qin @monavij Please check this PR, and if possible, also test it.

___


<!-- Sent from Reviewable.io -->

2023-04-13 12:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 0 of 13 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`tools/sgx/common/ias.h` line 112 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NSubusB7QzqwMTAD_a5:-NSufZ6q4G3CJaPfk-Gc:b-a6ic89) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/tools/sgx/common/ias.h#L112)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

CONFIGURATION_AND_HW_HARDENING_NEEDED?
</blockquote></details>

UPDATE: I reread it -- this is correct, just reads a bit weird
___
*[`tools/sgx/common/ias.c` line 766 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NSugAc7-84huc1T9cyl:-NSugAc7-84huc1T9cym:b-t4mnkx) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/tools/sgx/common/ias.c#L766)):*
> ```C
>         print_allowed_and_advisories(node->valuestring, json);
>     } else if (allow_hw_config_needed && allow_sw_hardening_needed
>                 && strcmp("CONFIGURATION_AND_SW_HARDENING_NEEDED", node->valuestring) == 0) {
> ```

align?



_Code quote:_
```C
                && strcmp("CONFIGURATION_AND_SW_HARDENING_NEEDED", node->valuestring) == 0) {
```


<!-- Sent from Reviewable.io -->

2023-07-01 00:33 UTC, mkow requested changes
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, @kailun-qin, and @monavij)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZD_AqI-CjzTk0QdvLZ):*




_Suggestion:_
```
[PAL/Linux-SGX]
```
___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDbZIc2paUlxWx-W1k):*




_Suggestion:_
```
settings like disabling Hyper-Threading),
```
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDeaNo0LUrpDdjWOIC:-NZDeaNo0LUrpDdjWOID:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/CI-Examples/ra-tls-mbedtls/README.md#L63)):*
> ```Markdown
> addressed (for example, when the microcode or architectural enclaves aren't
> fully up-to-date). Note that in production environments, you must carefully
> analyse whether to use these options!
> ```





_Suggestion:_
```Markdown
analyze
```
___
*[`Documentation/attestation.rst` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NSucZAcCCqOIiky84Zj:-NZDr2E_5k6PzEInjTlv:bao9eyk) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/attestation.rst#L350)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So you you say that this should be set by default?

This would mean that we'll revert the name of this environment variable: `RA_TLS_ALLOW_SW_HARDENING_NEEDED` -> `RA_TLS_FORBID_SW_HARDENING_NEEDED`. This way the "not set envvar" will mean that `SW_HARDENING_NEEDED` status is Ok.

I'm not sure about this. This is really obscure and cumbersome. What do others think? @monavij @mkow @jkr0103 
</blockquote></details>

IMO we shouldn't allow any errors by default.
___
*[`Documentation/attestation.rst` line 351 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDiWmo8lNUj4jo9GI8:-NZDiWmo8lNUj4jo9GI9:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/Documentation/attestation.rst#L351)):*
> ```reStructuredText
> set, and thus all not-OK statuses are disallowed; in other words, only
> strictly-compliant HW/SW SGX platforms can pass verification by default. For
> more information, please refer to official Intel documentation:
> ```





_Suggestion:_
```reStructuredText
to the official Intel documentation
```
___
*[`Documentation/manpages/gramine-sgx-ias-verify-report.rst` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStuSPK9TacUp7wKIX8:-NZDiwnG61JliwTLiYvJ:bo7c6tr) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not good, I'm using the non-matching name of the command-line arg in this `gramine-sgx-ias-verify-report` tool. But I didn't want to add two more command-line args (we'll need to find alphabet letters for them, and this tool already uses all the good letters). And I also think nobody really uses this tool, other than maybe for testing?

Anyway, if anyone wants to force me to introduce 3 correct command-line args, then please give me the short and long names for them. I have no idea.
</blockquote></details>

Actually, I'd say they _shouldn't_ have short options. It should be clearly visible wherever they are used.
If with going this way the change is simple then please add it to this PR :)
___
*[`tools/sgx/common/ias.h` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDlDvI-wdmNFzWB3_P:-NZDlDvI-wdmNFzWB3_Q:b-oznwtw) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/common/ias.h#L112)):*
> ```objc
>  * \param allow_outdated_tcb        Treat IAS status code GROUP_OUT_OF_DATE as OK.
>  * \param allow_hw_config_needed    Treat IAS status codes CONFIGURATION_NEEDED and
>  *                                  CONFIGURATION_AND_SW_HARDENING_NEEDED as OK.
> ```

The documentation above doesn't mention that it also whitelists `CONFIGURATION_NEEDED`.
Also, this doesn't seem to exactly correspond to the IFs in `ias.c`? All three places seem to slightly differ in details.
___
*[`tools/sgx/common/ias.c` line 638 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDmy5S96_bhgMfejL7:-NZDmy5S96_bhgMfejL8:bvrbtla) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/common/ias.c#L638)):*
> ```C
>         INFO("            [ advisory IDs: %s ]\n", ids_str);
>         free(ids_str);
>     }
> ```

We should fail loudly if the field was found, but has a wrong type - currently, if the format changes for some reason we'll start to silently ignore advisories. This of course is very unlikely, but it's IMO a bad practice to handle it this way.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 107 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpF_w3Gw1Yn2dLzBN:-NZDpF_xEd6R4cgppMrU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L107)):*
> ```C
> bool getenv_allow_hw_config_needed(void) {
>     char* str = getenv(RA_TLS_ALLOW_HW_CONFIG_NEEDED);
>     return (str && !strcmp(str, "1"));
> ```





_Suggestion:_
```C
return str && !strcmp(str, "1");
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpDxP1LutlYACX3Lz:-NZDpDxP1LutlYACX3M-:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L112)):*
> ```C
> bool getenv_allow_sw_hardening_needed(void) {
>     char* str = getenv(RA_TLS_ALLOW_SW_HARDENING_NEEDED);
>     return (str && !strcmp(str, "1"));
> ```





_Suggestion:_
```C
return str && !strcmp(str, "1");
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpBvxB182rQ1gUt5T:-NZDpBvxB182rQ1gUt5U:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L117)):*
> ```C
> bool getenv_allow_debug_enclave(void) {
>     char* str = getenv(RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE);
>     return (str && !strcmp(str, "1"));
> ```





_Suggestion:_
```C
return str && !strcmp(str, "1");
```
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpZ0YBmv8o5T_ThPM:-NZDpZ0YBmv8o5T_ThPN:bc31z7p) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L77)):*
> ```C
>     switch (verification_result) {
>         case SGX_QL_QV_RESULT_OK:
>             return "OK (but collateral out of date)";
> ```

This is really confusing, it's out-of-date only because that's the only execution path in the callsite which could call this function with `SGX_QL_QV_RESULT_OK`. But `SGX_QL_QV_RESULT_OK` on its own is a success and doesn't imply that the collateral is out of date.
So, we're kinda hardcoding here the exact logic of the caller.


<!-- Sent from Reviewable.io -->

2023-07-01 02:43 UTC, kailun-qin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, @mkow, and @monavij)

___
*[`Documentation/attestation.rst` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NSucZAcCCqOIiky84Zj:-NZE8tQi62R0ybXssoMV:b-ggv2h8) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/attestation.rst#L350)):*
> So you say that this should be set by default?

No, pls kindly see my concerns below.

> IMO we shouldn't allow any errors by default.

I totally agree and this whitelist style is great. Just then users of Gramine would always need to set `RA_TLS_ALLOW_SW_HARDENING_NEEDED` to get a successful verification.

Hence,
1. The statement of `only strictly-compliant HW/SW SGX platforms can pass verification by default` is not exactly true, because even `strictly-compliant HW/SW SGX platforms`'ll still meet the `SW_HARDENING_NEEDED` issue. IDK if there's one platform can be immune, but this sounds impossible to me because the attestation infra cannot easily tell whether the SW hardening is actually applied (in e.g., Gramine in our case).
2. Users already using `strictly-compliant HW/SW SGX platforms` can get confused to set this `RA_TLS_ALLOW_SW_HARDENING_NEEDED` option due to 1) and I think we need some explanations on it.
3. For users who might be tired of setting this `RA_TLS_ALLOW_SW_HARDENING_NEEDED` due to 1), we'd suggest/warn that they should always carefully check before they apply it when using Gramine in production, and maybe better w/ some actionable items (e.g., Gramine version).
___
*[`Documentation/manpages/gramine-sgx-ias-verify-report.rst` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStuSPK9TacUp7wKIX8:-NZEJgBgBXW8btY9YBOs:b-s044l7) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L45)):*
> Actually, I'd say they _shouldn't_ have short options

+1


<!-- Sent from Reviewable.io -->

2023-07-01 07:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 4 of 13 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, @mkow, and @monavij)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZD_AqI-CjzTk0QdvLZ):*
Will do during final rebase
___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDbZIc2paUlxWx-W1k):*
Will do during final rebase
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZFO9Lx7pF1eS-VKeQy):*
This para about the ias-verify-report tool is wrong now. The tool is correct. Will remove it.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDeaNo0LUrpDdjWOIC:-NZF60AoDpKu3Iy0koKl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/CI-Examples/ra-tls-mbedtls/README.md#L63)):*
> ```Markdown
> addressed (for example, when the microcode or architectural enclaves aren't
> fully up-to-date). Note that in production environments, you must carefully
> analyse whether to use these options!
> ```

Done.
___
*[`Documentation/attestation.rst` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NSucZAcCCqOIiky84Zj:-NZF7d9U037GTFZ13lvo:b-uneg9v) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/attestation.rst#L350)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> So you say that this should be set by default?

No, pls kindly see my concerns below.

> IMO we shouldn't allow any errors by default.

I totally agree and this whitelist style is great. Just then users of Gramine would always need to set `RA_TLS_ALLOW_SW_HARDENING_NEEDED` to get a successful verification.

Hence,
1. The statement of `only strictly-compliant HW/SW SGX platforms can pass verification by default` is not exactly true, because even `strictly-compliant HW/SW SGX platforms`'ll still meet the `SW_HARDENING_NEEDED` issue. IDK if there's one platform can be immune, but this sounds impossible to me because the attestation infra cannot easily tell whether the SW hardening is actually applied (in e.g., Gramine in our case).
2. Users already using `strictly-compliant HW/SW SGX platforms` can get confused to set this `RA_TLS_ALLOW_SW_HARDENING_NEEDED` option due to 1) and I think we need some explanations on it.
3. For users who might be tired of setting this `RA_TLS_ALLOW_SW_HARDENING_NEEDED` due to 1), we'd suggest/warn that they should always carefully check before they apply it when using Gramine in production, and maybe better w/ some actionable items (e.g., Gramine version).
</blockquote></details>

Done.

I don't know how to put it in text what @kailun-qin suggests. So I currently just removed the offending sentence about `strictly-compliant HW/SW SGX platforms`. If anyone has objections, then please provide me a text to use.
___
*[`Documentation/attestation.rst` line 351 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDiWmo8lNUj4jo9GI8:-NZF6xjB9keAp0li55xX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/Documentation/attestation.rst#L351)):*
> ```reStructuredText
> set, and thus all not-OK statuses are disallowed; in other words, only
> strictly-compliant HW/SW SGX platforms can pass verification by default. For
> more information, please refer to official Intel documentation:
> ```

Done.
___
*[`Documentation/manpages/gramine-sgx-ias-verify-report.rst` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1286#-NStuSPK9TacUp7wKIX8:-NZFKKvs1P_Wj3nAKImO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ccd6047c2c824d5d9dfd12cb6a656e4a826a3b8e/Documentation/manpages/gramine-sgx-ias-verify-report.rst#L45)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Actually, I'd say they _shouldn't_ have short options

+1
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.h` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDlDvI-wdmNFzWB3_P:-NZFBsTZBQJnWEwvPEsH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/common/ias.h#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The documentation above doesn't mention that it also whitelists `CONFIGURATION_NEEDED`.
Also, this doesn't seem to exactly correspond to the IFs in `ias.c`? All three places seem to slightly differ in details.
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 638 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDmy5S96_bhgMfejL7:-NZFE-k94PG-Lc6SCWi_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/common/ias.c#L638)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should fail loudly if the field was found, but has a wrong type - currently, if the format changes for some reason we'll start to silently ignore advisories. This of course is very unlikely, but it's IMO a bad practice to handle it this way.
</blockquote></details>

Done.
___
*[`tools/sgx/common/ias.c` line 777 at r3](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZFOjK75edz75gFXNjG:-NZFOjK75edz75gFXNjH:b-ym0jkq) ([raw file](https://github.com/gramineproject/gramine/blob/7fc5b0beaa2bb3d979bb700134447b9e35f8860d/tools/sgx/common/ias.c#L777)):*
> ```C
>                    && strcmp("CONFIGURATION_AND_SW_HARDENING_NEEDED", node->valuestring) == 0) {
>         ret = print_allowed_and_advisories(node->valuestring, json);
>     }
> ```

FYI: I didn't change this cascade of IFs to one huge IF because I tried it, and looked even uglier. So I kept this cascade.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 107 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpF_w3Gw1Yn2dLzBN:-NZF8jOj6VpPBf5L6iBx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L107)):*
> ```C
> bool getenv_allow_hw_config_needed(void) {
>     char* str = getenv(RA_TLS_ALLOW_HW_CONFIG_NEEDED);
>     return (str && !strcmp(str, "1"));
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpDxP1LutlYACX3Lz:-NZF8jreD70He_WKbjUi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L112)):*
> ```C
> bool getenv_allow_sw_hardening_needed(void) {
>     char* str = getenv(RA_TLS_ALLOW_SW_HARDENING_NEEDED);
>     return (str && !strcmp(str, "1"));
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_common.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpBvxB182rQ1gUt5T:-NZF8kGKCft9SvPyv-zT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra_tls_verify_common.c#L117)):*
> ```C
> bool getenv_allow_debug_enclave(void) {
>     char* str = getenv(RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE);
>     return (str && !strcmp(str, "1"));
> ```

Done.
___
*[`tools/sgx/ra-tls/ra_tls_verify_dcap.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDpZ0YBmv8o5T_ThPM:-NZFAPWP-XsmeeF64LeX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df6b50a00db26370bbfd2b371be44e633b934234/tools/sgx/ra-tls/ra [...]

2023-07-01 07:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 4 of 13 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103, @mkow, and @monavij)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZFP9eA3WCn0J7nlDS-:-NZFP9eA3WCn0J7nlDS0:b6w1on) (no related file):*
I manually tested on two of my machines:
- local machine with EPID
- VM azure machine with DCAP

In both cases everything works.

___


<!-- Sent from Reviewable.io -->

2023-07-01 11:07 UTC, mkow submitted a review, later dismissed
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @monavij)

___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZG7CwYBph3ch2LhLEc:-NZG7CwZ4pqvEElzROtk:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7fc5b0beaa2bb3d979bb700134447b9e35f8860d/tools/sgx/verify-ias-report/verify_ias_report.c#L58)):*
> ```C
>     INFO("  --allow-sw-hardening-needed  Treat IAS status code SW_HARDENING_NEEDED as OK\n");
>     INFO("\n");
>     INFO("To treat the IAS status code CONFIGURATION_AND_SW_HARDENING_NEEDED as OK, set both \n");
> ```





_Suggestion:_
```C
set both\n"
```


<!-- Sent from Reviewable.io -->

2023-07-01 13:24 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 4 of 13 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-07-01 14:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZD_AqI-CjzTk0QdvLZ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZDbZIc2paUlxWx-W1k):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZFO9Lx7pF1eS-VKeQy):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This para about the ias-verify-report tool is wrong now. The tool is correct. Will remove it.
</blockquote></details>

Done
___
*[`tools/sgx/verify-ias-report/verify_ias_report.c` line 58 at r3](https://reviewable.io/reviews/gramineproject/gramine/1286#-NZG7CwYBph3ch2LhLEc:-NZGkFR026JusKt8CvZG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7fc5b0beaa2bb3d979bb700134447b9e35f8860d/tools/sgx/verify-ias-report/verify_ias_report.c#L58)):*
> ```C
>     INFO("  --allow-sw-hardening-needed  Treat IAS status code SW_HARDENING_NEEDED as OK\n");
>     INFO("\n");
>     INFO("To treat the IAS status code CONFIGURATION_AND_SW_HARDENING_NEEDED as OK, set both \n");
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-07-01 17:10 UTC, dimakuv commented
Jenkins, retest pkg-deb-debian12 please (known problem with `clone3` syscall not recognized by Docker's seccomp)

2023-07-01 23:34 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-02 01:00 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1286)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-02 09:40 UTC, merged