[python] Fix wrong format of `SIGSTRUCT.date` field
gramineproject/gramine pull request #1287
Opened 2023-04-14 06:23 UTC by kailun-qin

## Description of the changes 
Previously, Gramine treated each `date` info on signing (`date_year`, `date_month`, `date_day`) in decimal and packed them into hex (in little-endian) separately in SIGSTRUCT. However, SIGSTRUCT following the generic CSS format requires the whole `date` field in CSS header (aka `SGX_ARCH_SIGSTRUCT_DATE`) to have its byte representation in a {0xYYYYMMDD} format (in little-endian). This commit fixes this issue.

## How to test this PR? 
CI

2023-04-14 09:14 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSywRLn0FsrGeaZfqA0:-NSywRLn0FsrGeaZfqA1:bj45ohc) (no related file):*
Isn't the whole problem in a single place -- in `sigstruct.py`? Why do you need to change the other places? See also my other comments.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSywYPJBsL9lqE5eDu2:-NSywYPJBsL9lqE5eDu3:bvsxu1f) (no related file):*
I don't know what "generic CSS format" is, but the Intel SDM document mentions the requirement for the date in SIGSTRUCT:

> Build date is yyyymmdd in hex: yyyy=4 digit year, mm=1-12, dd=1-31

See Table 34-21 in Chapter 33, Volume 3.

So the change in the PR itself is good.

___
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz0rB6527krfN9TlC2):*
What is "generic CSS format"? If you want to use this term, please provide some background info on this term.

But I would just refer to the Intel SDM and the official description of the SIGSTRUCT format there.
___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz12-i2i4JVD3Hhm3l:-NSz12-i2i4JVD3Hhm3m:bll3lvc) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
> ```
>         'attribute_xfrm_mask': hex(sig['attribute_xfrm_mask']),
>         'misc_mask': hex(sig['misc_mask']),
>         'date': f'{sig["date_year"]:x}-{sig["date_month"]:x}-{sig["date_day"]:x}',
> ```

This `sig_readable` format is for human readable output. I see no reason to show some weird hex numbers to people. Please revert this change.
___
*[`python/graminelibos/sgx_get_token.py` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1DOV4PpfpQy85wR1:-NSz1DOW8SOIpPefuCAT:b-cdk5em) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_get_token.py#L135)):*
> ```Python
>         print(f'    exponent:    {sig["exponent"]}')
>         print(f'    signature:   {sig["signature"].hex()[:32]}...')
>         print(f'    date:        {sig["date_year"]:x}-{sig["date_month"]:x}-{sig["date_day"]:x}')
> ```

This `verbose` print is for human readable output. I see no reason to show some weird hex numbers to people. Please revert this change.
___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NSz1G5PEOYhMvD2xsZz:b-am6krt) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
> ```Python
>     sig['date_year'] = int(f'{date.year}', 16)
>     sig['date_month'] = int(f'{date.month}', 16)
>     sig['date_day'] = int(f'{date.day}', 16)
> ```

What is the meaning of this change? Integers are integers anyway... I don't see how this "format as string, then back to integer" changes anything. Also, is this parsing as hex even legit? I think you're printing here `"2023"` and convert this as if it is a hex number?

Generally, this whole thing looks at best useless. I think you should revert it.
___
*[`python/graminelibos/sigstruct.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1ofE2wvB10HNleV-:-NSz1ofE2wvB10HNleV0:b-xvl9zr) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sigstruct.py#L23)):*
> ```Python
>         'date_year': (offs.SGX_ARCH_SIGSTRUCT_DATE + 2, '<H'),
>         'date_month': (offs.SGX_ARCH_SIGSTRUCT_DATE + 1, '<B'),
>         'date_day': (offs.SGX_ARCH_SIGSTRUCT_DATE, '<B'),
> ```

This looks like the real change in all this PR. I think you can only leave this one change, and revert everything else.


<!-- Sent from Reviewable.io -->

2023-04-14 10:35 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz0rB6527krfN9TlC2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is "generic CSS format"? If you want to use this term, please provide some background info on this term.

But I would just refer to the Intel SDM and the official description of the SIGSTRUCT format there.
</blockquote></details>

I agree - I'll update to refer to the Intel SDM.
___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz12-i2i4JVD3Hhm3l:-NSzHNXr3v0K_fkTXhj9:b1j2r85) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `sig_readable` format is for human readable output. I see no reason to show some weird hex numbers to people. Please revert this change.
</blockquote></details>

They're not weird hex numbers. Pls kindly see the current output:
```
kailun@sgx-WilsonCity:~/workspace/dev/sigstruct/gramine/CI-Examples/helloworld$ gramine-sgx-sigstruct-view helloworld.sig -v
Attributes:
    mr_signer: fc23a96a7d9dd7bd981a8734c7ae9e1492aa16d0fe9bc57af323c9c7b445aec0
    mr_enclave: 1337531c2c92552bc09d13d33399ac0a2c14b8f53887690b211505d530297dce
    isv_prod_id: 0
    isv_svn: 0
    attribute_flags: 0x6
    attribute_xfrms: 0x3
    misc_select: 0x0
    attribute_flags_mask: 0xffffffffffffffff
    attribute_xfrm_mask: 0xfffffffffff9ff1b
    misc_mask: 0xffffffff
    date: 2023-4-14
    debug_enclave: True
```
___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NSzHeiU8KyCpNagQ2YD:bdvq2bi) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
>  I think you're printing here "2023" and convert this as if it is a hex number?

Yes so it'll be turned into "8227" (in decimal).

This is needed so that eventually in the byte representation, we can get sth. like below (note **14 04 23 20**):
```
kailun@sgx-WilsonCity:~/workspace/dev/sigstruct/gramine/CI-Examples/helloworld$ hexdump -C helloworld.sig
00000000  06 00 00 00 e1 00 00 00  00 00 01 00 00 00 00 00  |................|
00000010  00 00 00 00 14 04 23 20  01 01 00 00 60 00 00 00  |......# ....`...|
00000020  60 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00  |`...............|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

SDM describes `SIGSTRUCT.DATE` as `Build date is yyyymmdd in hex: yyyy=4 digit year, mm=1-12, dd=1-31`. But it's actually a bit misleading. What we need is this **14 04 23 20** rather than **0e 04 e7 07** (which'll be the result if we only include the change in `sigstruct.py`). SGX SDK does the same and CSS (Code Signing System) seems to require the same as well. This is why I introduced this change.


<!-- Sent from Reviewable.io -->

2023-04-14 10:36 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NSzKZ2q-iegHKNW4-Dw:b-h87266) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

>  I think you're printing here "2023" and convert this as if it is a hex number?

Yes so it'll be turned into "8227" (in decimal).

This is needed so that eventually in the byte representation, we can get sth. like below (note **14 04 23 20**):
```
kailun@sgx-WilsonCity:~/workspace/dev/sigstruct/gramine/CI-Examples/helloworld$ hexdump -C helloworld.sig
00000000  06 00 00 00 e1 00 00 00  00 00 01 00 00 00 00 00  |................|
00000010  00 00 00 00 14 04 23 20  01 01 00 00 60 00 00 00  |......# ....`...|
00000020  60 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00  |`...............|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

SDM describes `SIGSTRUCT.DATE` as `Build date is yyyymmdd in hex: yyyy=4 digit year, mm=1-12, dd=1-31`. But it's actually a bit misleading. What we need is this **14 04 23 20** rather than **0e 04 e7 07** (which'll be the result if we only include the change in `sigstruct.py`). SGX SDK does the same and CSS (Code Signing System) seems to require the same as well. This is why I introduced this change.
</blockquote></details>

I was trying to explain this in commit description -- but looks like it does not work that well. :)


<!-- Sent from Reviewable.io -->

2023-04-14 11:11 UTC, woju requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz0rB6527krfN9TlC2):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I agree - I'll update to refer to the Intel SDM.
</blockquote></details>

Yes, and also please use somewhere the term "Binary-coded decimal" (this is what this encoding is, if I'm not mistaken), it will remove quite a bit of ambiguity. https://en.wikipedia.org/wiki/Binary-coded_decimal

And I argue SDM is awfully ambiguous with this description. It can be interpreted both as BCD and just packed struct. SDK does it as BCD: https://github.com/intel/linux-sgx/blob/1efe23c20e37f868498f8287921eedfbcecdc216/sdk/sign_tool/SignTool/manage_metadata.cpp#L252-L253
___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz12-i2i4JVD3Hhm3l:-NSzQTCc4UV2-8wguJsC:b-dw0qg7) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

They're not weird hex numbers. Pls kindly see the current output:
```
kailun@sgx-WilsonCity:~/workspace/dev/sigstruct/gramine/CI-Examples/helloworld$ gramine-sgx-sigstruct-view helloworld.sig -v
Attributes:
    mr_signer: fc23a96a7d9dd7bd981a8734c7ae9e1492aa16d0fe9bc57af323c9c7b445aec0
    mr_enclave: 1337531c2c92552bc09d13d33399ac0a2c14b8f53887690b211505d530297dce
    isv_prod_id: 0
    isv_svn: 0
    attribute_flags: 0x6
    attribute_xfrms: 0x3
    misc_select: 0x0
    attribute_flags_mask: 0xffffffffffffffff
    attribute_xfrm_mask: 0xfffffffffff9ff1b
    misc_mask: 0xffffffff
    date: 2023-4-14
    debug_enclave: True
```
</blockquote></details>

@kailun-qin is right. `{:x}` is a weasel out of BCD, because python stdlib lacks proper BCD encoder. The numeric representation is wrong, but the digits (characters in string) turn out correct.
___
*[`python/graminelibos/sgx_get_token.py` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1DOV4PpfpQy85wR1:-NSzQoNVDznxWakJi1zW:b-hx7k11) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_get_token.py#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `verbose` print is for human readable output. I see no reason to show some weird hex numbers to people. Please revert this change.
</blockquote></details>

No, it's correct, see other thread. Please keep.
___
*[`python/graminelibos/sgx_sign.py` line 528 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSzOQcD6vqaPL3BR5_p:-NSzOQcD6vqaPL3BR5_q:b-hhwqt5) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L528)):*
> ```Python
> 
>     # SIGSTRUCT following the generic CSS format requires the "date" field in CSS header (aka
>     # "SGX_ARCH_SIGSTRUCT_DATE") to have its byte representation in a {0xYYYYMMDD} format.
> ```

"Binary-coded decimal" plz.
___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NSzR-7a0PLTy7zpeuzs:b-wm9eot) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I was trying to explain this in commit description -- but looks like it does not work that well. :)
</blockquote></details>

I don't like the fact that numeric representations are wrong. I doubt this would be in scope, but `fields = {}` and `__getitem__` turns out to be a poor choice for this sigstruct implementation. It would be probably better to use properties/descriptors.
___
*[`python/graminelibos/sigstruct.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1ofE2wvB10HNleV-:-NSzSNYA73-sNQyyWbNF:b-cu3myq) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sigstruct.py#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks like the real change in all this PR. I think you can only leave this one change, and revert everything else.
</blockquote></details>

Nope, it's correct.


<!-- Sent from Reviewable.io -->

2023-04-14 13:00 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz0rB6527krfN9TlC2):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, and also please use somewhere the term "Binary-coded decimal" (this is what this encoding is, if I'm not mistaken), it will remove quite a bit of ambiguity. https://en.wikipedia.org/wiki/Binary-coded_decimal

And I argue SDM is awfully ambiguous with this description. It can be interpreted both as BCD and just packed struct. SDK does it as BCD: https://github.com/intel/linux-sgx/blob/1efe23c20e37f868498f8287921eedfbcecdc216/sdk/sign_tool/SignTool/manage_metadata.cpp#L252-L253
</blockquote></details>

Please also give the example that you had: `What we need is this 14 04 23 20 rather than 0e 04 e7 07`. Something like this. Without an example, it's hard to understand that this is a very special representation.
___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz12-i2i4JVD3Hhm3l:-NSznqPP8YoWPKz-4n1E:b6c5lk1) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@kailun-qin is right. `{:x}` is a weasel out of BCD, because python stdlib lacks proper BCD encoder. The numeric representation is wrong, but the digits (characters in string) turn out correct.
</blockquote></details>

Ok, misunderstood.
___
*[`python/graminelibos/sgx_get_token.py` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1DOV4PpfpQy85wR1:-NSznuiPCNvnUVNdQhut:b6c5lk1) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_get_token.py#L135)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, it's correct, see other thread. Please keep.
</blockquote></details>

Ok, misunderstood.
___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NSzo8QZ95dv1EfZxQgn:ba7wlqd) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
> What we need is this 14 04 23 20 rather than 0e 04 e7 07

Wow. Now I get it. This representation is very weird.


<!-- Sent from Reviewable.io -->

2023-04-17 02:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz0rB6527krfN9TlC2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also give the example that you had: `What we need is this 14 04 23 20 rather than 0e 04 e7 07`. Something like this. Without an example, it's hard to understand that this is a very special representation.
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 528 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSzOQcD6vqaPL3BR5_p:-NTBudNrC19MfdX4TSL1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L528)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"Binary-coded decimal" plz.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 09:38 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NT-XlyeCc2Ry8HZCk43:-NT-XlyeCc2Ry8HZCk44:bgtjlxx) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
> ```
>         'attribute_xfrm_mask': hex(sig['attribute_xfrm_mask']),
>         'misc_mask': hex(sig['misc_mask']),
>         'date': f'{sig["date_year"]:x}-{sig["date_month"]:x}-{sig["date_day"]:x}',
> ```

year: `:04x`, month and day: `:02x`, to have `2023-04-14`, not `-4-`
___
*[`python/graminelibos/sgx_get_token.py` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NT-XxwX4bhGrrTXRCmE:-NT-XxwX4bhGrrTXRCmF:bldf5ya) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_get_token.py#L135)):*
> ```Python
>         print(f'    exponent:    {sig["exponent"]}')
>         print(f'    signature:   {sig["signature"].hex()[:32]}...')
>         print(f'    date:        {sig["date_year"]:x}-{sig["date_month"]:x}-{sig["date_day"]:x}')
> ```

`:04x` and `:02x`
___
*[`python/graminelibos/sgx_sign.py` line 532 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NSz1G5PEOYhMvD2xsZy:-NT-TUQt1SmYHUn19yPm:b-gum90) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_sign.py#L532)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> What we need is this 14 04 23 20 rather than 0e 04 e7 07

Wow. Now I get it. This representation is very weird.
</blockquote></details>

It's not really weird, quite common in electronics, whenever you need to display something. Here you don't do anything with this value, so why not.


<!-- Sent from Reviewable.io -->

2023-04-17 10:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`python/gramine-sgx-sigstruct-view` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NT-XlyeCc2Ry8HZCk43:-NTDdJhl5g6WvG6YP_5i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/gramine-sgx-sigstruct-view#L37)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

year: `:04x`, month and day: `:02x`, to have `2023-04-14`, not `-4-`
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_get_token.py` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/1287#-NT-XxwX4bhGrrTXRCmE:-NTDdCs738KR3yCIaf0e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b0f9e11ceecfffb870ed65fc8c98f8f78c77348/python/graminelibos/sgx_get_token.py#L135)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`:04x` and `:02x`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 11:37 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-04-17 12:51 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-18 14:41 UTC, mkow requested changes
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 28 at r3](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTJdHk04RgmpLp0vGXF):*
(reads nicer this way, especially because now it matches better that "04" in hex above)



_Suggestion:_
```
"2023-04-14"
```
___
*[`python/graminelibos/sgx_sign.py` line 537 at r3](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTJeBBG-Ng9khPY2RI3:-NTJeBBG-Ng9khPY2RI4:b-ggit0o) ([raw file](https://github.com/gramineproject/gramine/blob/aae9ab40498a56d8d7dbc2acf6e0620904e5a429/python/graminelibos/sgx_sign.py#L537)):*
> ```Python
>     sig['date_year'] = int(f'{date.year}', 16)
>     sig['date_month'] = int(f'{date.month}', 16)
>     sig['date_day'] = int(f'{date.day}', 16)
> ```

I really don't like this. Now we have a field named `date_day` in our internal structure, which is an integer, but it's value is _not_ the day of signing, but some garbage. This is super misleading.
Why not just store the real value here and use BCD only when asked to serialize this to bytes?


<!-- Sent from Reviewable.io -->

2023-04-18 16:11 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 28 at r3](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTJdHk04RgmpLp0vGXF):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(reads nicer this way, especially because now it matches better that "04" in hex above)
</blockquote></details>

Done.
___
*[`python/graminelibos/sgx_sign.py` line 537 at r3](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTJeBBG-Ng9khPY2RI3:-NTK73xrBeABNfhfQWDe:b-ryfjwl) ([raw file](https://github.com/gramineproject/gramine/blob/aae9ab40498a56d8d7dbc2acf6e0620904e5a429/python/graminelibos/sgx_sign.py#L537)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I really don't like this. Now we have a field named `date_day` in our internal structure, which is an integer, but it's value is _not_ the day of signing, but some garbage. This is super misleading.
Why not just store the real value here and use BCD only when asked to serialize this to bytes?
</blockquote></details>

I swithed to another way of impl. Pls kindly see if it makes more sense to you.


<!-- Sent from Reviewable.io -->

2023-04-18 22:13 UTC, mkow approved these changes
Approving, we can do the comment fixes on the rebase before merging (or normally, depending on which will happen sooner ;) ).

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287#-:-NTLQ3619LbYAUUdfiIf:b4yuwbp)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`python/graminelibos/sigstruct.py` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPESk0Yeumm_2zYlM:-NTLPESk0Yeumm_2zYlN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L105)):*
> ```Python
>                     raise KeyError(f'{key} is not set')
>                 continue
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
> ```





_Suggestion:_
```Python
signing date
```
___
*[`python/graminelibos/sigstruct.py` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPIvs4nWtszHeC1eT:-NTLPIvs4nWtszHeC1eU:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L105)):*
> ```Python
>                     raise KeyError(f'{key} is not set')
>                 continue
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
> ```





_Suggestion:_
```Python
is stored in yyyymmdd format in hex
```
___
*[`python/graminelibos/sigstruct.py` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPSAD497HkvvCuqqQ:-NTLPSAD497HkvvCuqqR:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L107)):*
> ```Python
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
>             # mm=1-12, dd=1-31 according to Intel SDM (Table 35-21. Layout of Enclave Signature
>             # Structure (SIGSTRUCT), Chapter 34, Volume 3, Version March 2023). Further, SGX SDK and
> ```





_Suggestion:_
```Python
version March 2023
```
___
*[`python/graminelibos/sigstruct.py` line 148 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPi88AOdN-hftp_mM:-NTLPi88AOdN-hftp_mN:bu2fhdf) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L148)):*
> ```Python
>             # "Binary-coded decimal". See above explanation in `to_bytes()` for details.
>             # We thus turn this "Binary-coded decimal" of the date-related bytes back into their
>             # decimal values.
> ```

just "See the analogous place in to_bytes() method for explanation" instead of duplicating the description
___
*[`python/graminelibos/sgx_sign.py` line 537 at r3](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTJeBBG-Ng9khPY2RI3:-NTLOlaOC-C2Ni162Z1B:b-vj7c5o) ([raw file](https://github.com/gramineproject/gramine/blob/aae9ab40498a56d8d7dbc2acf6e0620904e5a429/python/graminelibos/sgx_sign.py#L537)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I swithed to another way of impl. Pls kindly see if it makes more sense to you.
</blockquote></details>

Looks much better now, and it's even simpler than the previous version :)


<!-- Sent from Reviewable.io -->

2023-04-19 06:56 UTC, dimakuv approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2023-04-19 07:00 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`python/graminelibos/sigstruct.py` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPESk0Yeumm_2zYlM:-NTNIrA43VKSwBarJvqU:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L105)):*
> ```Python
>                     raise KeyError(f'{key} is not set')
>                 continue
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
> ```

Done
___
*[`python/graminelibos/sigstruct.py` line 105 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPIvs4nWtszHeC1eT:-NTNIs0DBp1wwRPvROLI:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L105)):*
> ```Python
>                     raise KeyError(f'{key} is not set')
>                 continue
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
> ```

Done
___
*[`python/graminelibos/sigstruct.py` line 107 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPSAD497HkvvCuqqQ:-NTNIsd11Y3MTc5d_TD2:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L107)):*
> ```Python
>             # `SIGSTRUCT.DATE` (build date) is required to be yyyymmdd in hex: yyyy=4 digit year,
>             # mm=1-12, dd=1-31 according to Intel SDM (Table 35-21. Layout of Enclave Signature
>             # Structure (SIGSTRUCT), Chapter 34, Volume 3, Version March 2023). Further, SGX SDK and
> ```

Done
___
*[`python/graminelibos/sigstruct.py` line 148 at r5](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTLPi88AOdN-hftp_mM:-NTNJ2wy6J6IR19m8AKt:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a062a041bae166fc63cd25cf9977e33264c07ebc/python/graminelibos/sigstruct.py#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

just "See the analogous place in to_bytes() method for explanation" instead of duplicating the description
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-19 07:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-04-19 10:34 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-19 11:47 UTC, woju requested changes
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`python/graminelibos/sigstruct.py` line 147 at r6](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTOJrQkA9YD3PgZzMks:-NTOJrQkA9YD3PgZzMkt:b-cx7xb) ([raw file](https://github.com/gramineproject/gramine/blob/b9d1d42e0a2a3b0a05dc4542120960321c7add3d/python/graminelibos/sigstruct.py#L147)):*
> ```Python
>             # See the analogous place in to_bytes() method for explanation.
>             if key in ['date_year', 'date_month', 'date_day']:
>                 sig[key] = int(f'{struct.unpack_from(fmt, buffer, offset)[0]:x}')
> ```

This will crash on misencoded structs that might exist in the wild (for example, generated by previous versions of this code). Do we need to do something about it?


<!-- Sent from Reviewable.io -->

2023-04-19 12:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`python/graminelibos/sigstruct.py` line 147 at r6](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTOJrQkA9YD3PgZzMks:-NTOOLo05bLuoRzl9KXD:b-w20180) ([raw file](https://github.com/gramineproject/gramine/blob/b9d1d42e0a2a3b0a05dc4542120960321c7add3d/python/graminelibos/sigstruct.py#L147)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This will crash on misencoded structs that might exist in the wild (for example, generated by previous versions of this code). Do we need to do something about it?
</blockquote></details>

Good catch. Maybe we should wrap this line into try...except block and print a human-readable error message on failure?

I think it's Ok to fail loudly here, as we're not expecting someone to generate sigstructs in one Gramine version and parse them in another one. At least I don't know why anyone would want this (of course, inadvertantly this can happen, and that's why I'd prefer a clear error message).


<!-- Sent from Reviewable.io -->

2023-04-19 13:27 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[`python/graminelibos/sigstruct.py` line 147 at r6](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTOJrQkA9YD3PgZzMks:-NTOgWpK12UPiTWRzRd4:b3cbyyn) ([raw file](https://github.com/gramineproject/gramine/blob/b9d1d42e0a2a3b0a05dc4542120960321c7add3d/python/graminelibos/sigstruct.py#L147)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done. I'm currently re-raising the error instead of exiting as it might be more friendly for developers. Let me know if any concerns here. Thanks!
</blockquote></details>

Thanks, looks great


<!-- Sent from Reviewable.io -->

2023-04-19 14:04 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-04-19 14:21 UTC, woju requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`python/graminelibos/sigstruct.py` line 147 at r6](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTOJrQkA9YD3PgZzMks:-NTOrQ514mjVZXdZfgUR:bpqbw13) ([raw file](https://github.com/gramineproject/gramine/blob/b9d1d42e0a2a3b0a05dc4542120960321c7add3d/python/graminelibos/sigstruct.py#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, looks great
</blockquote></details>

`print(..., file=sys.stderr)` please and `import sys` at the start of the file. This should go to stderr, together with traceback.

Yes, I agree, it's probably correct that if there's any compatibility concern at all, then people generate structs here and load and sign elsewhere, not the other way around. If someone comes and complains, we can think about other solution.


<!-- Sent from Reviewable.io -->

2023-04-19 14:34 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

___
*[`python/graminelibos/sigstruct.py` line 147 at r6](https://reviewable.io/reviews/gramineproject/gramine/1287#-NTOJrQkA9YD3PgZzMks:-NTOw5et19tPww0YmDtF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b9d1d42e0a2a3b0a05dc4542120960321c7add3d/python/graminelibos/sigstruct.py#L147)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`print(..., file=sys.stderr)` please and `import sys` at the start of the file. This should go to stderr, together with traceback.

Yes, I agree, it's probably correct that if there's any compatibility concern at all, then people generate structs here and load and sign elsewhere, not the other way around. If someone comes and complains, we can think about other solution.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-19 14:36 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-04-19 14:44 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-04-19 14:45 UTC, woju approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1287)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-19 16:06 UTC, merged