Update LICENSE.addendum.txt with libcurl and libgomp
gramineproject/gramine pull request #1308
Opened 2023-04-26 05:18 UTC by kailun-qin

## Description of the changes 
As in the title, it seems that info about `libcurl` and `libgomp` are missing in the current `LICENSE.addendum.txt`.

2023-04-26 07:48 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`LICENSE.addendum.txt` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwXAZl7xIukzIAQCM3:-NTwXAZl7xIukzIAQCM4:b-equdyh) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L14)):*
> ```help
> tomlc99 - MIT
> uthash - BSD revised
> Ninja (python/graminelibos/ninja_syntax.py) - Apache 2.0
> ```

Should we sort this list?


<!-- Sent from Reviewable.io -->

2023-04-26 08:19 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @oshogbo)

___
*[`LICENSE.addendum.txt` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwb3aiByAI9iGRpSrt:-NTwb3aiByAI9iGRpSru:b-b32kx9) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L5)):*
> ```help
> Gramine also includes the following third party sources (and licenses):
> 
> mbedtls crypto libraries - Apache 2.0
> ```

The official name is "Mbed TLS"
___
*[`LICENSE.addendum.txt` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwb9cDBuemoxt3Y-Ks:-NTwb9cDBuemoxt3Y-Kt:bjezll) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L5)):*
> ```help
> Gramine also includes the following third party sources (and licenses):
> 
> mbedtls crypto libraries - Apache 2.0
> ```

Please move it to the list of other projects and sort
___
*[`LICENSE.addendum.txt` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwbliuAKAvFSDyj31z:-NTwbliuAKAvFSDyj32-:b-blxkpk) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L7)):*
> ```help
> mbedtls crypto libraries - Apache 2.0
> 
> Internet Software Consortium (permissive license): common/src/network/inet_pton.c
> ```

This file (functions in this file) seem to be not used at all -- can we remove them?

Please create a new PR that removes this file. And remove the mention from this file.
___
*[`LICENSE.addendum.txt` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwXAZl7xIukzIAQCM3:-NTwb-J_26Ls3PrxNHeD:b-qyavum) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L14)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we sort this list?
</blockquote></details>

+1, let's just make this file look nicer.
___
*[`LICENSE.addendum.txt` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwcJ6RDIZXB3MWR6yU:-NTwcJ6RDIZXB3MWR6yV:b-8e3np6) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L19)):*
> ```help
> * glibc - LGPL
>  ** pal/include/elf/elf.h
>  ** common/src/network/hton.c
> ```

Actually, can we remove this file? It's basically wrappers around `__builtin_bswap32()` and `__builtin_bswap16()` functions, which can be found in any C compiler. And the functions there are used only in non-important places like the syscall parser and in one regression test.


<!-- Sent from Reviewable.io -->

2023-04-26 09:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @oshogbo)

___
*[`LICENSE.addendum.txt` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwbliuAKAvFSDyj31z:-NTwyEFM-m8LvlFs9YCb:b-wliyyn) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This file (functions in this file) seem to be not used at all -- can we remove them?

Please create a new PR that removes this file. And remove the mention from this file.
</blockquote></details>

This was done in this PR: https://github.com/gramineproject/gramine/pull/1309
___
*[`LICENSE.addendum.txt` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwcJ6RDIZXB3MWR6yU:-NTwyH-e6o1RQmSrXSCf:b-wliyy1) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, can we remove this file? It's basically wrappers around `__builtin_bswap32()` and `__builtin_bswap16()` functions, which can be found in any C compiler. And the functions there are used only in non-important places like the syscall parser and in one regression test.
</blockquote></details>

This was done in this PR: https://github.com/gramineproject/gramine/pull/1310


<!-- Sent from Reviewable.io -->

2023-04-26 09:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`LICENSE.addendum.txt` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwb3aiByAI9iGRpSrt:-NTwxXDUAfVTrLHO32Bl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The official name is "Mbed TLS"
</blockquote></details>

Done.
___
*[`LICENSE.addendum.txt` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwb9cDBuemoxt3Y-Ks:-NTwxXl_6oGeM7uNvQn0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move it to the list of other projects and sort
</blockquote></details>

Done.
___
*[`LICENSE.addendum.txt` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwbliuAKAvFSDyj31z:-NTwzEFI8YzOFAziPvq7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was done in this PR: https://github.com/gramineproject/gramine/pull/1309
</blockquote></details>

Done.
___
*[`LICENSE.addendum.txt` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwXAZl7xIukzIAQCM3:-NTwxhiNDGuNE7pVQ7II:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, let's just make this file look nicer.
</blockquote></details>

Done.
___
*[`LICENSE.addendum.txt` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwcJ6RDIZXB3MWR6yU:-NTwzD7o5eFcFsQTGyAf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was done in this PR: https://github.com/gramineproject/gramine/pull/1310
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-26 10:31 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`LICENSE.addendum.txt` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwbliuAKAvFSDyj31z:-NTx6EXX8lkEh3SvjiEe:bpyfxuc) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L7)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'll keep this comment blocking so that we merge #1309 before this PR
___
*[`LICENSE.addendum.txt` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwcJ6RDIZXB3MWR6yU:-NTx6Ks4CrPtFBigJKib:b-hqfdfm) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L19)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'll keep this comment blocking so that we merge #1310 before this PR


<!-- Sent from Reviewable.io -->

2023-04-26 12:55 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`LICENSE.addendum.txt` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTxcH2hBFSq2-vf-Fgg:-NTxcH2i2exseeNkya5y:bze7r3o) ([raw file](https://github.com/gramineproject/gramine/blob/81fa1224a9bfaa6e77f2b60cc56738e7e4c753f8/LICENSE.addendum.txt#L6)):*
> ```help
> * cJSON - MIT
> * curl/libcurl - MIT derivative
> * GCC/libgomp - GPL v3.0
> ```

I'd add an after-line comment saying that this is built only optionally and not included by default.


<!-- Sent from Reviewable.io -->

2023-04-26 13:20 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`LICENSE.addendum.txt` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTxcH2hBFSq2-vf-Fgg:-NTxiAKoE9b6qPO7trhW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/81fa1224a9bfaa6e77f2b60cc56738e7e4c753f8/LICENSE.addendum.txt#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add an after-line comment saying that this is built only optionally and not included by default.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-26 13:21 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-04-27 12:33 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`LICENSE.addendum.txt` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwbliuAKAvFSDyj31z:-NU1grIA3YAdjxAAL4Mk:b-4z1oh4) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll keep this comment blocking so that we merge #1309 before this PR
</blockquote></details>

Rebased, thanks
___
*[`LICENSE.addendum.txt` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1308#-NTwcJ6RDIZXB3MWR6yU:-NU1gvNG9O3Mad5Whlhu:b-khanmn) ([raw file](https://github.com/gramineproject/gramine/blob/d54cdbbd40e50364324a0f8ad5282e412c75b5c6/LICENSE.addendum.txt#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll keep this comment blocking so that we merge #1310 before this PR
</blockquote></details>

Rebased, thanks!


<!-- Sent from Reviewable.io -->

2023-04-27 14:45 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-04-27 15:14 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-05-02 14:28 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308#-:-NURrRTb1zUkrHMnrF5G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-02 14:31 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1308)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 00:25 UTC, merged