[PAL/Linux] Do not call `pal_strerror` before/during/failed PAL relocation
gramineproject/gramine pull request #1317
Opened 2023-04-27 09:17 UTC by oshogbo

## Description of the changes 

We can't do that because the array which contains error strings might not be relocated yet. The error strings reside in .rodata segment. If we use `pal_strerror` and relocations are in use (default build), the function will return the offset instead of the real address. This will cause Gramine to segfault.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1317)

2023-04-27 09:34 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1317#-NU12umy-M0jkDVRLLkc):*
Does this impact `PAL/Linux-SGX` also?



_Code quote:_
```
PAL/Linux
```


<!-- Sent from Reviewable.io -->

2023-04-27 09:53 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1317#-NU12umy-M0jkDVRLLkc):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Does this impact `PAL/Linux-SGX` also?
</blockquote></details>

+1, I think this also applies to Linux-SGX: https://github.com/gramineproject/gramine/blob/8fe78a6752a86c91afe0552387bb1395b6d0c294/pal/src/host/linux-sgx/pal_main.c#L533
___
*[`pal/src/host/linux/pal_main.c` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1317#-NU17FoxCasz42xiFUsa:-NU17FoxCasz42xiFUsb:bor1swi) ([raw file](https://github.com/gramineproject/gramine/blob/dc03d35ef31bbc38fb2c159d8c6ef42c467f4ff2/pal/src/host/linux/pal_main.c#L173)):*
> ```C
>     ret = setup_pal_binary();
>     if (ret < 0)
>         INIT_FAIL("Relocation of the PAL binary failed: %d", ret);
> ```

Please add a short one-line comment that we can't use `pal_strerror()` here, otherwise we'll revert this accidentally in some future.


<!-- Sent from Reviewable.io -->

2023-04-27 10:44 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1317#-NU12umy-M0jkDVRLLkc):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, I think this also applies to Linux-SGX: https://github.com/gramineproject/gramine/blob/8fe78a6752a86c91afe0552387bb1395b6d0c294/pal/src/host/linux-sgx/pal_main.c#L533
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1317#-NU17FoxCasz42xiFUsa:-NU1J4fV4bkfubCG8xg4:b-lwu1fo) ([raw file](https://github.com/gramineproject/gramine/blob/dc03d35ef31bbc38fb2c159d8c6ef42c467f4ff2/pal/src/host/linux/pal_main.c#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a short one-line comment that we can't use `pal_strerror()` here, otherwise we'll revert this accidentally in some future.
</blockquote></details>

It's more then one-liner :)
But hopes its ok.


<!-- Sent from Reviewable.io -->

2023-04-27 11:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-04-27 11:51 UTC, kailun-qin submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-01 16:42 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, 3 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUNBGBn8GtkdezoSN3w):*




_Suggestion:_
```
Do not call `pal_strerror` before/during failed PAL relocation
```
___
*[`pal/src/host/linux/pal_main.c` line 175 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUN9DQ98BPHGRLYP697:-NUN9DQ98BPHGRLYP698:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/9a881633b9db9e6f2458011ec4b9faaedb8830d8/pal/src/host/linux/pal_main.c#L175)):*
> ```C
>         /* PAL relocation failed, so we can't use functions which use PAL .rodata (like
>          * pal_strerror or unix_strerror) to report an error because these functions will return
>          * offset instead of actual address, which will cause segfault. */
> ```





_Suggestion:_
```C
which will cause a segfault
```
___
*[`pal/src/host/linux-sgx/pal_main.c` line 535 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUNB2qeB_yTOYKsv8Bi:-NUNB2qeB_yTOYKsv8Bj:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9a881633b9db9e6f2458011ec4b9faaedb8830d8/pal/src/host/linux-sgx/pal_main.c#L535)):*
> ```C
>         /* PAL relocation failed, so we can't use functions which use PAL .rodata (like
>          * pal_strerror or unix_strerror) to report an error because these functions will return
>          * offset instead of actual address, which will cause segfault. */
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-05-01 17:25 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUNBGBn8GtkdezoSN3w):*
Done.
___
*[`pal/src/host/linux/pal_main.c` line 175 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUN9DQ98BPHGRLYP697:-NUNKy3q7EVeNOxpkxgB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a881633b9db9e6f2458011ec4b9faaedb8830d8/pal/src/host/linux/pal_main.c#L175)):*
> ```C
>         /* PAL relocation failed, so we can't use functions which use PAL .rodata (like
>          * pal_strerror or unix_strerror) to report an error because these functions will return
>          * offset instead of actual address, which will cause segfault. */
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 535 at r2](https://reviewable.io/reviews/gramineproject/gramine/1317#-NUNB2qeB_yTOYKsv8Bi:-NUNKze_D45UVnYbd-LX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a881633b9db9e6f2458011ec4b9faaedb8830d8/pal/src/host/linux-sgx/pal_main.c#L535)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-02 00:17 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-03 00:22 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: all files reviewed, all discussions resolved, "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-03 00:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 00:58 UTC, kailun-qin requested changes
Blocking for testing

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317#-:-NUU6VkOAtQaNV8vx1US:b-iemo0d)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2023-05-03 01:03 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1317)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 01:31 UTC, merged