[LibOS] Use dynamic allocation for `libos_process.cmdline`
gramineproject/gramine pull request #1320
Opened 2023-04-28 07:46 UTC by kailun-qin

## Description of the changes 
Previously Gramine had a static buffer of one page (4KB) in size to hold cmdline, which turns out to be not enough for Apache Kafka workloads (which is actually a `/bin/java` command line with many JAR files listed in the command line).

This commit changes to use dynamic allocation for it and propagates on fork/clone.

Fixes https://github.com/gramineproject/gramine/discussions/1303.

## How to test this PR? 
manual testing + CI

2023-04-28 08:17 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/include/libos_process.h` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU5v4ea8faQikW_hwWT:-NU5v4ea8faQikW_hwWU:b6tjwfl) ([raw file](https://github.com/gramineproject/gramine/blob/dd1d3dca50359d3a842cea7fb536896772438c12/libos/include/libos_process.h#L65)):*
> ```objc
>     /* Complete command line for the process, as reported by /proc/[pid]/cmdline; currently filled
>      * once during initialization, using static buffer and restricted to CMDLINE_SIZE. This is
>      * enough for current workloads but see https://github.com/gramineproject/gramine/issues/79. */
> ```

There is still another problem listed in issue 79 (about being able to modify the cmdline, which is not currently possible in Gramine). So please keep the link but rephrase.
___
*[`libos/src/bookkeep/libos_process.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU5v_Et67yPKpVKGqQq:-NU5v_Et67yPKpVKGqQr:b-jzeyh1) ([raw file](https://github.com/gramineproject/gramine/blob/d593fb1f47eab1d9f83b0cbb9a80e43eb6617886/libos/src/bookkeep/libos_process.c#L77)):*
> ```C
>     for (const char* const* a = argv; *a; a++) {
>         if (size + strlen(*a) + 1 > max) {
>             max *= 2;
> ```

What if there is a single argument that is greater than current `max`? Then we'll have buffer overwrite. I guess you should something like:
```
max = MAX(max * 2, size + strlen(*a) + 1);
```


<!-- Sent from Reviewable.io -->

2023-04-28 08:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_process.h` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU5v4ea8faQikW_hwWT:-NU63dvk7tqSzPNXMhUt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dd1d3dca50359d3a842cea7fb536896772438c12/libos/include/libos_process.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is still another problem listed in issue 79 (about being able to modify the cmdline, which is not currently possible in Gramine). So please keep the link but rephrase.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_process.c` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU5v_Et67yPKpVKGqQq:-NU63eIQ8_k8Wj4mY2w7:bves986) ([raw file](https://github.com/gramineproject/gramine/blob/d593fb1f47eab1d9f83b0cbb9a80e43eb6617886/libos/src/bookkeep/libos_process.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What if there is a single argument that is greater than current `max`? Then we'll have buffer overwrite. I guess you should something like:
```
max = MAX(max * 2, size + strlen(*a) + 1);
```
</blockquote></details>

Good catch! Fixed.


<!-- Sent from Reviewable.io -->

2023-04-28 09:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-28 10:56 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_process.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6V4TY6LyImhsAWgOV:-NU6V4TY6LyImhsAWgOW:bptouqa) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L69)):*
> ```C
> 
>     size_t size = 0, max = 256;
>     char* cmdline = malloc(max);
> ```

Why not calloc instead of malloc/memset?
___
*[`libos/src/bookkeep/libos_process.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6VHet1L8B4GKYAQ3m:-NU6VHeu-8S_BgzKSoSp:b-qf4au0) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L79)):*
> ```C
>             max = MAX(max * 2, size + strlen(*a) + 1);
>             /* TODO: use `realloc()` once it's available. */
>             char* new_cmdline = malloc(max);
> ```

calloc?


<!-- Sent from Reviewable.io -->

2023-04-28 11:07 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_process.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6Xtl0EuH7hrPWZwp2:-NU6Xtl0EuH7hrPWZwp3:bicgh2k) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L77)):*
> ```C
>     for (const char* const* a = argv; *a; a++) {
>         if (size + strlen(*a) + 1 > max) {
>             max = MAX(max * 2, size + strlen(*a) + 1);
> ```

Hym, instead of realloc, can't we just count first argv count?
I guess counting even long list will be faster then doing reallocs.


<!-- Sent from Reviewable.io -->

2023-04-28 13:15 UTC, mkow reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`libos/src/bookkeep/libos_process.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6V4TY6LyImhsAWgOV:-NU6z2Bc6-9W4WT37-3f:b-j0embo) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L69)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why not calloc instead of malloc/memset?
</blockquote></details>

+1, we call memset right below it, calloc will be just shorter
___
*[`libos/src/bookkeep/libos_process.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6Xtl0EuH7hrPWZwp2:-NU7-1s3A8X4544aZILc:b-wdcrln) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L77)):*
> count first argv count

? I guess you meant adding all the lengths first?


<!-- Sent from Reviewable.io -->

2023-04-28 13:27 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_process.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6Xtl0EuH7hrPWZwp2:-NU723907fjJV5XWYZ9i:b-waystc) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> count first argv count

? I guess you meant adding all the lengths first?
</blockquote></details>

Yes exactly.


<!-- Sent from Reviewable.io -->

2023-04-28 14:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`libos/src/bookkeep/libos_process.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6V4TY6LyImhsAWgOV:-NU7LcHADdfDU9vRBQpc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, we call memset right below it, calloc will be just shorter
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_process.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6Xtl0EuH7hrPWZwp2:-NU7LckX9o_-DQoi6JEE:b-1epib0) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L77)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes exactly.
</blockquote></details>

It actually depends. But I do agree "adding all the lengths first" can bring benefits in certain cases. PTAL, thanks!
___
*[`libos/src/bookkeep/libos_process.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1320#-NU6VHet1L8B4GKYAQ3m:-NU7Lbpy9gTchlxdCUp0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95310ecd535d702267c7a3e28f0d6b902d72c57c/libos/src/bookkeep/libos_process.c#L79)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

calloc?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-28 15:48 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-05-02 07:20 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320#-:-NUQKKeQArkIaQMH7g9m:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-04 08:57 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-04 12:12 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-04 12:46 UTC, dimakuv commented
Jenkins, retest Docs please (networking issues)

2023-05-04 12:48 UTC, dimakuv commented
Jenkins, retest check-python-platlib please (networking issues)

2023-05-04 23:27 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1320)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-04 23:32 UTC, merged