[PAL/Linux-SGX,Docs] Remove deprecated syntax for number of threads
gramineproject/gramine pull request #1331
Opened 2023-05-05 08:17 UTC by kailun-qin

## Description of the changes 

The syntax `sgx.thread_num = [NUM]` was deprecated in Gramine v1.4.

Now that the next version of Gramine will be v1.5, we can safely remove it.

## How to test this PR? 
CI

2023-05-05 10:50 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331#-:-NUfXDrY-_ajncyjAjpF:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-05-05 11:55 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUfktlq0gA8w6fItY7A):*
No need for two paragraphs. Can be fixed during final rebase.


<!-- Sent from Reviewable.io -->

2023-05-05 15:38 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUgYyt80QgMP9jhvVRz:-NUgYyt80QgMP9jhvVS-:b-y7fryz) (no related file):*
You missed `sgx_sign.py` which still uses the old syntax (`manifest_sgx.get('thread_num')`).

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUgYLD6-w6fv7q1GS3N):*




_Suggestion:_
```
[PAL/Linux-SGX] Remove deprecated syntax for number of threads
```


<!-- Sent from Reviewable.io -->

2023-05-05 15:47 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUgYyt80QgMP9jhvVRz:-NUga4U5A7YgdyloSwgf:b8gj3mm) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You missed `sgx_sign.py` which still uses the old syntax (`manifest_sgx.get('thread_num')`).
</blockquote></details>

Good catch, fixed!

___


<!-- Sent from Reviewable.io -->

2023-05-05 15:57 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-05-05 20:01 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-05-08 06:23 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUgYLD6-w6fv7q1GS3N):*
Done
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1331#-NUfktlq0gA8w6fItY7A):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for two paragraphs. Can be fixed during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-08 11:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1331)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-08 12:09 UTC, merged