[Docs] Work around the bug of urllib3 and OpenSSL incompatibility
gramineproject/gramine pull request #1335
Opened 2023-05-08 16:20 UTC by dimakuv

## Description of the changes 

The recent version of urllib3 (v2.0) only supports OpenSSL 1.1.1+. However, the ReadTheDocs engine that we use for generating our web documentation by default uses older OpenSSL. The workaround is to pin a specific OS distro and Python version.

## How to test this PR? 

Check RTD logs. (I will do it manually.)

2023-05-08 16:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwAr2j7Pt4OELGNUVE:-NUwAr2k4HXRFhWfke-q:b-ouzsne) (no related file):*
I checked manually -- RTD successfully builds with this patch.

___


<!-- Sent from Reviewable.io -->

2023-05-08 16:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NUwDxal1fY5xmJplyrC:b-1dv509) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
> ```YAML
> version: 2
> 
> build:
> ```

Could you add a short comment explaining why we need to specify this? (maybe just copy the commit message? or copy and shorten a bit?)


<!-- Sent from Reviewable.io -->

2023-05-08 16:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NUwFuqB9ro1ZwAIYAXb:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a short comment explaining why we need to specify this? (maybe just copy the commit message? or copy and shorten a bit?)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-08 17:54 UTC, mkow reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NUwUosf69f-lOXNLz5g:bzddoqe) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, maybe I should add the https://github.com/readthedocs/readthedocs.org/issues/10290 link to this comment?
</blockquote></details>

Sounds good, please do :)


<!-- Sent from Reviewable.io -->

2023-05-08 18:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NUwhVC12_gaeBLJJc8x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds good, please do :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-09 01:47 UTC, kailun-qin submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-09 10:57 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335#-:-NV-9CmI-2MNj_-pDnI5:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-09 14:53 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NV-zyILBzGQ0V4LjZdY:b-y7y4p2) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why `:` and indentation? Looks weird (like a point list with just one entry).


<!-- Sent from Reviewable.io -->

2023-05-09 18:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`.readthedocs.yaml` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1335#-NUwDxal1fY5xmJplyrB:-NV0fXJKDe58y_2wlhji:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7de15a8d693d4c220812252d0e1199eba4c20f3/.readthedocs.yaml#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `:` and indentation? Looks weird (like a point list with just one entry).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-09 21:45 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-05-10 00:15 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1335)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-10 00:24 UTC, merged