[Docs] Add scrollbar to the side navigation menu
gramineproject/gramine pull request #1346
Opened 2023-05-15 07:58 UTC by dimakuv

## Description of the changes 

Extracted from #1241.

## How to test this PR? 

I created a RTD job to see the rendering: XXX. Notice the scrollbar.

2023-05-15 09:37 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/_static/css/gramine.css` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTlGPY7BdYR9izeqe7:-NVTlGPY7BdYR9izeqe8:b-uh01re) ([raw file](https://github.com/gramineproject/gramine/blob/ccb6572b3bd86f2fba8a253c2b3b8bba21346bd4/Documentation/_static/css/gramine.css#L8)):*
> ```CSS
> .wy-side-scroll {
>     width: auto;
>     overflow-y: auto;
> ```

why not `overflow-y: scroll`?



_Code quote:_
```CSS
auto
```


<!-- Sent from Reviewable.io -->

2023-05-15 09:44 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTmiYnB9KOHeoV53Hg):*
[Docs] Add scrollbar to the side navigation menu when content overflows



_Code quote:_
```
[Docs] Add scrollbar to the side navigation menu
```
___
*[`Documentation/_static/css/gramine.css` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTlGPY7BdYR9izeqe7:-NVTm-DbE-feHDaotW2-:b9rm54m) ([raw file](https://github.com/gramineproject/gramine/blob/ccb6572b3bd86f2fba8a253c2b3b8bba21346bd4/Documentation/_static/css/gramine.css#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

why not `overflow-y: scroll`?
</blockquote></details>

UPDATE: OK I see, with `auto`, the scroll bar'll be displayed only if the content is overflowing (i.e., if content fits inside the element's padding box, it looks the same as with `visible`).


<!-- Sent from Reviewable.io -->

2023-05-15 09:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`Documentation/_static/css/gramine.css` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTlGPY7BdYR9izeqe7:-NVTmsuMCTaFVzrInIIF:bgr31v6) ([raw file](https://github.com/gramineproject/gramine/blob/ccb6572b3bd86f2fba8a253c2b3b8bba21346bd4/Documentation/_static/css/gramine.css#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

why not `overflow-y: scroll`?
</blockquote></details>

But why? `auto` seems like a meaningful default (only show the scrollbar when the table of contents really overflows).

For details, one can check https://www.w3schools.com/cssref/css3_pr_overflow-y.php


<!-- Sent from Reviewable.io -->

2023-05-15 09:46 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/_static/css/gramine.css` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTlGPY7BdYR9izeqe7:-NVTnAmsAvICxOygq_mv:b-9tjxxg) ([raw file](https://github.com/gramineproject/gramine/blob/ccb6572b3bd86f2fba8a253c2b3b8bba21346bd4/Documentation/_static/css/gramine.css#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why? `auto` seems like a meaningful default (only show the scrollbar when the table of contents really overflows).

For details, one can check https://www.w3schools.com/cssref/css3_pr_overflow-y.php
</blockquote></details>

Yes, `auto` makes better sense.


<!-- Sent from Reviewable.io -->

2023-05-15 09:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1346#-NVTmiYnB9KOHeoV53Hg):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

[Docs] Add scrollbar to the side navigation menu when content overflows
</blockquote></details>

Done (removed `the` to make the title char size smaller)


<!-- Sent from Reviewable.io -->

2023-05-15 09:54 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-05-16 00:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1346)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-16 00:03 UTC, merged