[Docs] Fix typos and improve wording
gramineproject/gramine pull request #1348
Opened 2023-05-15 10:07 UTC by dimakuv

## Description of the changes 

Extracted from https://github.com/gramineproject/gramine/pull/1241.

## How to test this PR? 

N/A. The changes are trivial, so I didn't enable a separate job to show the rendering.

2023-05-15 10:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Documentation/sgx-intro.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTt9yk2Xh7G_90KFaD:-NVTt9yk2Xh7G_90KFaE:b-52szr0) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/sgx-intro.rst#L13)):*
> ```reStructuredText
> off the CPU package (e.g., cold-boot attacks on RAM). Gramine is able to run
> unmodified applications inside SGX enclaves, without the toll of manually
> porting the application to the SGX environment.
> ```

I'm not sure we need all this text... Maybe only the first sentence? But this is how the tech writer wanted it.
___
*[`Documentation/pal/host-abi.rst` line 337 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTtMg2CrPxksG4dtJe:-NVTtMg2CrPxksG4dtJf:b-c7bsld) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/pal/host-abi.rst#L337)):*
> ```reStructuredText
> 
> The ABI includes calls to get wall clock time, generate cryptographically-strong
> random bits, to obtain an attestation report and quote, etc.
> ```

FYI: This file is ridiculously outdated...


<!-- Sent from Reviewable.io -->

2023-05-15 10:50 UTC, kailun-qin requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/devel/building.rst` line 364 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTw9On7ZBHyfZbytIS:-NVTw9On7ZBHyfZbytIT:b-d3tey4) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/devel/building.rst#L364)):*
> ```reStructuredText
> can skip this step. For older kernels it is available as `separate patches
> <https://github.com/oscarlab/graphene-sgx-driver/tree/master/fsgsbase_patches>`__.
> ```

What's the reason of this change?


<!-- Sent from Reviewable.io -->

2023-05-15 12:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/devel/building.rst` line 364 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTw9On7ZBHyfZbytIS:-NVUMzsk2CSaHJ6rzZJ_:b-57els7) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/devel/building.rst#L364)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What's the reason of this change?
</blockquote></details>

Done. I don't know why the original authors did this. But I agree, I see no reason to have it as a separate paragraph. So reverted the change.


<!-- Sent from Reviewable.io -->

2023-05-16 01:19 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-16 09:05 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-05-16 13:10 UTC, donporter requested changes
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 97 at r3](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVZe0gWCXZMO5Ffwb3a:-NVZe0gWCXZMO5Ffwb3b:b-njpn2k) ([raw file](https://github.com/gramineproject/gramine/blob/52d317f581872e490df62ec82b18b30e0b3c69e0/Documentation/manifest-syntax.rst#L97)):*
> ```reStructuredText
> default, or ``fs.start_dir`` if specified).
> 
> The recommended usage is to provide an absolute path and mount the executable
> ```

The "and" here is weird.  I think we mean that the executable must also be mounted.

Proposed edit:

"...absolute path.  This executable must also be in the library OS's file system, either directly mounted or within a directory that is mounted.  For example, if one wishes to execute the python 3.8 interpreter, one would specify this as the entrypoint and mount the python executable at the expected path within the libOS file system."
___
*[`Documentation/manifest-syntax.rst` line 697 at r3](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVZfCLh54jer-jPWoZt:-NVZfCLh54jer-jPWoZu:b-px3p90) ([raw file](https://github.com/gramineproject/gramine/blob/52d317f581872e490df62ec82b18b30e0b3c69e0/Documentation/manifest-syntax.rst#L697)):*
> ```reStructuredText
> 
> This syntax specifies the files to be cryptographically hashed at build time
> and allowed to be accessed by the app in runtime only if their hashes match.
> ```

I suggest we rework the second half of this sentence:

"...build time; at runtime, these files may only be accessed by the app if the files' hashes match what is stored in the manifest."


<!-- Sent from Reviewable.io -->

2023-05-16 15:53 UTC, donporter requested changes
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: 6 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/quickstart.rst` line 96 at r3](https://reviewable.io/reviews/gramineproject/gramine/1348#-NV_F7Xc4T0YY6nO_H6W:-NV_F7Xc4T0YY6nO_H6X:b-boyf8b) ([raw file](https://github.com/gramineproject/gramine/blob/52d317f581872e490df62ec82b18b30e0b3c69e0/Documentation/quickstart.rst#L96)):*
> ```reStructuredText
>    git clone --depth 1 |stable-checkout| \https://github.com/gramineproject/gramine.git
> 
> Don't build Gramine as it is already installed on the system. Instead,
> ```

I would put a comma after Gramine, although it is not strictly required.  Maybe change "as" to "because".
___
*[`Documentation/devel/debugging.rst` line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/1348#-NV_FiQX0ylK8kQF_zts:-NV_FiQX0ylK8kQF_ztt:b-dkt04y) ([raw file](https://github.com/gramineproject/gramine/blob/52d317f581872e490df62ec82b18b30e0b3c69e0/Documentation/devel/debugging.rst#L57)):*
> ```reStructuredText
> 
> Building Gramine with ``--buildtype=debug`` enables debug symbols and GDB
> integration but disables optimizations. This is usually the right thing to do:
> ```

i would recommend keeping the comma for clarity in parsing.
___
*[`Documentation/pal/host-abi.rst` line 77 at r3](https://reviewable.io/reviews/gramineproject/gramine/1348#-NV_Fw7lDWpkArWAskqT:-NV_Fw7lDWpkArWAskqU:b-xp294s) ([raw file](https://github.com/gramineproject/gramine/blob/52d317f581872e490df62ec82b18b30e0b3c69e0/Documentation/pal/host-abi.rst#L77)):*
> ```reStructuredText
> All PALs in Gramine expose a structure that provides static immutable
> information about the current process and its host. The address of the structure
> can be retrieved via :func:`PalGetPalPublicState()` and can be memorized in a
> ```

memorized -> memoized 


<!-- Sent from Reviewable.io -->

2023-05-16 15:54 UTC, donporter reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-05-16 22:37 UTC, mkow requested changes
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

___
*[`Documentation/manifest-syntax.rst` line 98 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVaaqvS429suiPEmAZ0:-NVaaqvS429suiPEmAZ1:bpf48j0) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/manifest-syntax.rst#L98)):*
> ```reStructuredText
> 
> The recommended usage is to provide an absolute path of the executable. This
> executable must also be in the Gramine's file system, either directly mounted or
> ```

ditto for the whole PR



_Suggestion:_
```reStructuredText
filesystem
```
___
*[`Documentation/manifest-syntax.rst` line 138 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVab4658cWZs7W_QfRs:-NVab466CXI5OCojjH6Q:b-peh234) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/manifest-syntax.rst#L138)):*
> ```reStructuredText
>   containing output of :ref:`gramine-argv-serializer<gramine-argv-serializer>`.
> 
> If none of the above argument-handling manifest options are specified in the
> ```

Is this change correct? You can only specify one of these options, not multiple of them.
___
*[`Documentation/sgx-intro.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTt9yk2Xh7G_90KFaD:-NVadNr2B4j7uj3G-HF3:bajw745) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/sgx-intro.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure we need all this text... Maybe only the first sentence? But this is how the tech writer wanted it.
</blockquote></details>

I don't understand this whole change here. This documentation page is an introduction to SGX, not to Gramine-on-SGX.
Also, half of the new text is basically "what is Gramine".
I'd revert this whole hunk.
___
*[`Documentation/devel/building.rst` line 22 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVafFre0zFoLkn8zDHW:-NVafFre0zFoLkn8zDHX:b-pyi371) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/devel/building.rst#L22)):*
> ```reStructuredText
> higher. If you find problems with Gramine on other Linux distributions, contact
> us with a |~| detailed `bug report
> <https://github.com/gramineproject/gramine/issues/new>`__.
> ```

Just noticed: The link should actually be `https://github.com/gramineproject/gramine/issues/new/choose` (the template picker).


<!-- Sent from Reviewable.io -->

2023-05-17 07:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: 4 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 98 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVaaqvS429suiPEmAZ0:-NVcXobI3QPqSpulYtrq:bcainla) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/manifest-syntax.rst#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for the whole PR
</blockquote></details>

Done (for our whole documentation). But why do you prefer this way of writing?
___
*[`Documentation/manifest-syntax.rst` line 138 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVab4658cWZs7W_QfRs:-NVcY8xk2GwFm0YdPiZQ:b1u5g96) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/manifest-syntax.rst#L138)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this change correct? You can only specify one of these options, not multiple of them.
</blockquote></details>

Done. This was suggested by Don (iirc), who is a native speaker. But I would be ok with any style here, I think both native and non-native speakers will understand the general idea of this sentence.
___
*[`Documentation/sgx-intro.rst` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVTt9yk2Xh7G_90KFaD:-NVcYqbKDYvM9pYef7fe:b-sf9bvr) ([raw file](https://github.com/gramineproject/gramine/blob/b3bd36e804cd7eceda0aabc67c6fae338e09538a/Documentation/sgx-intro.rst#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this whole change here. This documentation page is an introduction to SGX, not to Gramine-on-SGX.
Also, half of the new text is basically "what is Gramine".
I'd revert this whole hunk.
</blockquote></details>

Done. Kept only the introductory name of Intel SGX as the change.
___
*[`Documentation/devel/building.rst` line 22 at r5](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVafFre0zFoLkn8zDHW:-NVcZEWD5UnXOhZvvy6p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bda9ba35eb96c705719c3f5600e97b6689136589/Documentation/devel/building.rst#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed: The link should actually be `https://github.com/gramineproject/gramine/issues/new/choose` (the template picker).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 12:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: 9 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

___
*[`Documentation/sgx-intro.rst` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1348#-NVdS02x1GGpc4qZGtyf:-NVdiZ7I2G1lEsNdAWaZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8a0c0787314bddf8ef2962057af65946e6162ea/Documentation/sgx-intro.rst#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I really dislike such statements, because security is _always_ relative to some attacker model. The freestanding "running software securely" is meaningless here (e.g. Gramine nor SGX doesn't make apps harder to exploit remotely, it actually makes that easier).
I'd rather say "to protect software running on untrusted hosts".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 15:00 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2023-05-20 16:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 4 unresolved discussions (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2023-05-22 01:34 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 4 unresolved discussions (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2023-05-22 08:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1348)* status: all files reviewed, 5 unresolved discussions (waiting on @donporter)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1348#-NW1TApl9lpbXPN91s5L:-NW1TApl9lpbXPN91s5M:b-dic9i7) (no related file):*
A quick ping for @donporter, since he's the only one blocking on this PR.

___


<!-- Sent from Reviewable.io -->

2023-05-23 13:53 UTC, merged