[Docs] Reorganize pages
gramineproject/gramine pull request #1362
Opened 2023-05-19 08:41 UTC by dimakuv

## Description of the changes 

Re-creation of #1241, with small changes here and there.

Depends on #1348.

## How to test this PR? 

TODO.

2023-05-19 10:04 UTC, kailun-qin requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 11 of 12 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/curated-installation.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnLwc6BnsuhAE-4s6S:-NVnLwc6BnsuhAE-4s6T:b-rrt98a) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/curated-installation.rst#L1)):*
> ```reStructuredText
> Ready-made confidential protected images
> ```

We use everywhere below "confidential compute images" but here we introduced a different name?



_Code quote:_
```reStructuredText
protected
```
___
*[`Documentation/docker-image-installation.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGCfB6j-V-wS0Ck7P:-NVnGCfCCPpAt8TR4t5e:b5808ar) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/docker-image-installation.rst#L29)):*
> ```reStructuredText
> 
> You can download the profile file from
> https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json.
> ```

This is actually a wrapper of `docker_seccomp_mar_2021.json`.

Should we point to either `docker_seccomp_mar_2021.json` or `docker_seccomp_aug_2022.json` which are the real profile files (that people can download from)?



_Code quote:_
```reStructuredText
You can download the profile file from
https://github.com/gramineproject/gramine/blob/master/scripts/docker_seccomp.json.
```
___
*[`Documentation/gsc-installation.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMz9p4G-umtTGC57R:-NVnMz9p4G-umtTGC57S:b-pjsf2k) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/gsc-installation.rst#L16)):*
> ```reStructuredText
> Note that the GSC tool is split from core Gramine and is hosted here:
> 
> - https://github.com/gramineproject/gsc -- GitHub repository,
> ```

`,` -> `.`



_Code quote:_
```reStructuredText
,
```
___
*[`Documentation/index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnIorR0yV6QPXSsBGt:-NVnIorR0yV6QPXSsBGu:b-64q35w) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L14)):*
> ```reStructuredText
> (Software Guard Extensions) technology. Gramine is able to run unmodified
> applications inside SGX enclaves, without the toll of manually porting the
> application to the SGX environment. For more information, refer to the
> ```

We actually decided to remove this sentense from `sgx-intro` in https://github.com/gramineproject/gramine/pull/1348. Do we want to keep it here?



_Code quote:_
```reStructuredText
(Software Guard Extensions) technology. Gramine is able to run unmodified
applications inside SGX enclaves, without the toll of manually porting the
application to the SGX environment. For more information, refer to the
```
___
*[`Documentation/index.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnLb6--HM20yVuj4LU:-NVnLb6--HM20yVuj4LV:b-5g5s43) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L40)):*
> ```reStructuredText
> Docker images are used to run applications in the cloud. The Gramine Shielded
> Containers (GSC) tool transforms an original Docker image into a graminized
> Docker image that includes the Gramine Library OS and Intel SGX related data. It
> ```

What exactly is this SGX related data?



_Code quote:_
```reStructuredText
Intel SGX related data
```
___
*[`Documentation/index.rst` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMdjt3wJI5mNNaBUC:-NVnMdjt3wJI5mNNaBUD:bqa85fi) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L71)):*
> ```reStructuredText
>   from the repository of your operating system.
> - :doc:`Set up the environment<environment-setup>` - Set up the Gramine
>   environment to work with or without SGX and prepare a signing key.
> ```

prepare a signing key (only for SGX)?



_Code quote:_
```reStructuredText
prepare a signing key
```
___
*[`Documentation/index.rst` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnNK-g0yEY6_HT5k1p:-NVnNK-g0yEY6_HT5k1q:b-iru9iq) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L134)):*
> ```reStructuredText
>   Gramine user-groups page lists the user groups you can join to help you get up
>   to speed with developing Gramine.
> ```

What about the section of `GRAMINE DESIGN AND CONCEPTS` then?
___
*[`Documentation/index.rst` line 222 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGK-T70C8VSpNT9R0:-NVnP37MDgCKauulVJSI:b-wfjhip) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L222)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not sure whether `SGX intro` falls under `Gramine design and concepts`... Maybe move to  under `Resources`?
</blockquote></details>

+1 for `Resources`
___
*[`Documentation/index.rst` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGQBt179jO7q4ETOK:-NVnPE06BPS1FwrTYcgY:b9g10le) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L231)):*
> But where else?

Maybe under `devel`?
___
*[`Documentation/run-sample-application.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnQLoS8FsRuGu2cCKB:-NVnQLoS8FsRuGu2cCKC:b-iqg65l) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L11)):*
> ```reStructuredText
>    git clone --depth 1 |stable-checkout| \https://github.com/gramineproject/gramine.git
> 
> Don't build Gramine as it is already installed on the system.
> ```

I suggest `if` (since how can we assume readers pick up this page by following strictly the order of doc).



_Code quote:_
```reStructuredText
as
```
___
*[`Documentation/run-sample-application.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnRXJi37GRI2tE-0px:-NVnRXJi37GRI2tE-0py:b4k4jmh) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L42)):*
> ```reStructuredText
> :file:`CI-Examples` directory in the repository. Each application contains a
> short README file with instructions how to test it. We recommend starting with a
> simpler, thoroughly documented example of Redis to understand manifest options
> ```

meaning the docs of other examples are either complicated or not  well-documented? :)



_Code quote:_
```reStructuredText
simpler, thoroughly documented example of Redis
```
___
*[`Documentation/run-sample-application.rst` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnSBA63sgFqVCrqDms:-NVnSBA63sgFqVCrqDmt:b-dz9y45) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L46)):*
> ```reStructuredText
> 
> Additional sample configurations for applications enabled in Gramine are
> available in a separate repository https://github.com/gramineproject/examples.
> ```

repository:



_Code quote:_
```reStructuredText
repository
```
___
*[`Documentation/manpages/gramine.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnOtRc1vR [...]

2023-05-19 11:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/curated-installation.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnLwc6BnsuhAE-4s6S:-NVneCau-n_f05aF-7Fq:bnpoqvs) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/curated-installation.rst#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We use everywhere below "confidential compute images" but here we introduced a different name?
</blockquote></details>

Done. Good catch. I checked that we don't use `confidential protected` wording anywhere else in our documentation.
___
*[`Documentation/docker-image-installation.rst` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGCfB6j-V-wS0Ck7P:-NVnesMW0SKRRwu-tLz5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/docker-image-installation.rst#L29)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is actually a wrapper of `docker_seccomp_mar_2021.json`.

Should we point to either `docker_seccomp_mar_2021.json` or `docker_seccomp_aug_2022.json` which are the real profile files (that people can download from)?
</blockquote></details>

Done.
___
*[`Documentation/gsc-installation.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMz9p4G-umtTGC57R:-NVnewCSDK9_6AF4_S81:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/gsc-installation.rst#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`,` -> `.`
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnIorR0yV6QPXSsBGt:-NVneyxUDsCBJ0UhtAOt:beigoh8) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L14)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We actually decided to remove this sentense from `sgx-intro` in https://github.com/gramineproject/gramine/pull/1348. Do we want to keep it here?
</blockquote></details>

Yes, I thought that this sentence ("Gramine is able to run ...") fits well into this introductory page. So I did this on purpose.
___
*[`Documentation/index.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnLb6--HM20yVuj4LU:-NVnf83R-DOyzAyfOhHj:b-rh8wzq) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L40)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What exactly is this SGX related data?
</blockquote></details>

Done. Didn't know how to call it better, but now I went for `Gramine-specific app configuration`.
___
*[`Documentation/index.rst` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMdjt3wJI5mNNaBUC:-NVnfvPD49A-fkiTvaLp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L71)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

prepare a signing key (only for SGX)?
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnNK-g0yEY6_HT5k1p:-NVnjU-pDokeFKgooGmm:bitxvk0) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L134)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about the section of `GRAMINE DESIGN AND CONCEPTS` then?
</blockquote></details>

Done. Indeed, missed to describe it.
___
*[`Documentation/index.rst` line 222 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGK-T70C8VSpNT9R0:-NVnirOE8tKEDOUc96CC:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L222)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1 for `Resources`
</blockquote></details>

Done
___
*[`Documentation/index.rst` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGQBt179jO7q4ETOK:-NVnit7_Ab9VT8YnLt--:b-zh427o) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L231)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> But where else?

Maybe under `devel`?
</blockquote></details>

But this is not about development of Gramine? It's just another way to use Gramine.
___
*[`Documentation/run-sample-application.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnQLoS8FsRuGu2cCKB:-NVnj2Zg7CKBvArAB_Az:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L11)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I suggest `if` (since how can we assume readers pick up this page by following strictly the order of doc).
</blockquote></details>

Done.
___
*[`Documentation/run-sample-application.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnRXJi37GRI2tE-0px:-NVnj8u28qL8NcLl9xxd:bi5wxzk) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L42)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

meaning the docs of other examples are either complicated or not  well-documented? :)
</blockquote></details>

Done partially. I removed the word `simpler`. But in general, yes, Redis is the only example that is very thoroughly documented.
___
*[`Documentation/run-sample-application.rst` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnSBA63sgFqVCrqDms:-NVnjIRv-RlcC3bbbFqZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/run-sample-application.rst#L46)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

repository:
</blockquote></details>

Done.
___
*[`Documentation/manpages/gramine.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnOtRc1vR6VunZY0hB:-NVnjRna176xOJVbKLZo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/manpages/gramine.rst#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

applications
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-21 01:51 UTC, mkow requested changes
> Reviewed 3 of 12 files at r1, 3 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 10 of 12 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NVveu674_NimsFEXK_I:b-t5j4z5) (no related file):*
One problem I see with this reorganization is that as soon as we add support for any other TEE or compat backend we'll need to reorganize everything again - this reorg implicitly makes us an SGX-only framework, starting with sections like "Protect your container" without mentioning that this is just one of the available backends.

Not sure whether this is a good or bad direction, but IMO we should discuss this, especially considering any future plans.

___
___
*[`Documentation/cloud-deployment.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnG-EB148IMy1L0Z-4:-NVv3MOb50beYYLCNJPw:b-26xo9q) ([raw file](https://github.com/gramineproject/gramine/blob/ad393992a30b1383da1b017e4a6ccfa7d9feb27d/Documentation/cloud-deployment.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I removed this document, as there seems to be a lot of duplication from other pages.

The only interesting info is MS Azure VMs, but I think it's outdated and not that useful -- people can find this info by googling...
</blockquote></details>

+1 to this change
___
*[`Documentation/container-integration.rst` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGBkK7Nxhrf9-TXHd:-NVv3XKh9JhAhY1HOCTS:bqb0gl0) ([raw file](https://github.com/gramineproject/gramine/blob/ad393992a30b1383da1b017e4a6ccfa7d9feb27d/Documentation/container-integration.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I deleted this page, as its information is not scattered in other pages.
</blockquote></details>

I guess you meant "now", not "not".
+1 from my side.
___
*[`Documentation/curated-installation.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVv4qQHAVc7uuDXlkGy:-NVv4qQHAVc7uuDXlkGz:b-4jgsb6) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/curated-installation.rst#L9)):*
This whole paragraph is IMO terrible...

> These images enable you to customize

1. Please don't, this is not a marketing leaflet but technical documentation.
2. It's not the images which can customize something, it's the curated app script. The images are the _result_ of it.

Also, it doesn't work with the previous sentence, the overall construction is now like "ASDF is a ready made solution for [...]. ASDF allows customization of your environment". What environment? At this point it's not explained at any point what this thing is doing, but it already started to explain that it also allows customizations to whatever it is doing.
Dunno how to fix it without just rewriting the whole paragraph.
___
*[`Documentation/curated-installation.rst` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVv8D7yDhNhaTQMC_WN:-NVv8D7yDhNhaTQMC_WO:b-l3mfe8) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/curated-installation.rst#L16)):*
> ```reStructuredText
> 
> Note that these confidential compute images only run on machines that support
> Intel SGX.
> ```

Shouldn't this be in the title? That this is specific to SGX. E.g. by appending "for SGX". Or even better: "Ready-made SGX images". Now the title of this page takes 2 lines on the left sidebar, the proposed version would fit into one line and contains even more information.
___
*[`Documentation/environment-setup.rst` line 8 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvAZmH1X0AZSQrXC5l:-NVvAZmH1X0AZSQrXC5m:b-4vdgs6) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L8)):*
> ```reStructuredText
> Gramine with SGX support requires several features from your system:
> 
> - The FSGSBASE feature of recent processors must be enabled in the Linux kernel.
> ```

Not sure if you can enable or disable it, wasn't it just about having the right kernel version?



_Code quote:_
```reStructuredText
must be enabled in the Linux kernel.
```
___
*[`Documentation/environment-setup.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvAk_K0zaer-YAHbWj:-NVvAk_K0zaer-YAHbWk:b-a5seqr) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L9)):*
> ```reStructuredText
> 
> - The FSGSBASE feature of recent processors must be enabled in the Linux kernel.
> - The Intel SGX driver must be built in the Linux kernel.
> ```

This sounds weird and not easily verifiable by the user. Just say that the kernel must be at least in version XYZ to include the SGX driver.
___
*[`Documentation/environment-setup.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvB3bUDKxyY71qWufO:-NVvB3bUDKxyY71qWufP:b-qq1qld) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L11)):*
> ```reStructuredText
> - The Intel SGX driver must be built in the Linux kernel.
> - The Intel PSW must be installed.
> - The Intel DCAP must be installed if DCAP-based attestation will be used.
> ```

What about BIOS settings? It's missing from the list.
___
*[`Documentation/gsc-installation.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMz9p4G-umtTGC57R:-NVvQJ1ODlPV5kQVXIU9:b-c704s) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/gsc-installation.rst#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wasn't `,` intended here? These are not full sentences, it's a list with items.
___
*[`Documentation/gsc-installation.rst` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvC3dO-MzSUI1Y87Ev:-NVvC3dO-MzSUI1Y87Ew:b8dhded) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L4)):*
> ```reStructuredText
> ===========================
> 
> The Gramine Shielded Containers (GSC) tool transforms an original Docker image
> ```

What does "original" mean here?



_Code quote:_
```reStructuredText
transforms an original Docker image
```
___
*[`Documentation/gsc-installation.rst` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvQ05PDW8rO5RYgL70:-NVvQ05PDW8rO5RYgL71:bl31buf) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L7)):*
> ```reStructuredText
> into a new, "graminized" image which includes the Gramine Library OS and the
> Gramine-specific app configuration. It uses Gramine to execute the application
> inside an Intel SGX enclave. It follows the common Docker approach to first
> ```

? That's the _only_ "Docker approach", there's no other way to use Docker?



_Code quote:_
```reStructuredText
It follows the common Docker approach
```
___
*[`Documentation/gsc-installation.rst` line 10 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvQ5a6-L7237co2Avk:-NVvQ5a6-L7237co2Avl:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installa [...]

2023-05-21 16:13 UTC, mkow requested changes
> Reviewed 3 of 12 files at r1, 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 49 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/environment-setup.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVz0J8R7SYiuCuO_01R:-NVz0J8R7SYiuCuO_01S:bb4tl3m) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L1)):*
> Set up the Gramine environment

This is IMO a bad title, this whole section talks only about SGX-specific setup.
___
*[`Documentation/quickstart.rst` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyWxxw7UyW5zRFhzi7:-NVyWxxw7UyW5zRFhzi8:bpc2zlj) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L13)):*
> ```reStructuredText
> application.
> 
> - :doc:`Install Gramine<quickstart>` - This option is explained on this page.
> ```

Why is this document linking to itself?
___
*[`Documentation/quickstart.rst` line 14 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyXXeS4nidXyui0VIo:-NVyXXeS4nidXyui0VIp:b-bz0aib) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L14)):*
> ```reStructuredText
> 
> - :doc:`Install Gramine<quickstart>` - This option is explained on this page.
>   It involves installing the official Gramine packages from the repository of
> ```

"involves" sounds like this was one of many steps, while it's the _only_ step there.



_Code quote:_
```reStructuredText
It involves installing the official Gramine packages
```
___
*[`Documentation/quickstart.rst` line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyXuCo9e8dd9xr-pmb:-NVyXuCo9e8dd9xr-pmc:b-8cnw39) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L18)):*
> using a prepared Docker image

"prepared"? What does this mean here?
___
*[`Documentation/quickstart.rst` line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyY5CQCdFuuS5ibdSh:-NVyY5CQCdFuuS5ibdSi:b-oir3br) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L23)):*
> ```reStructuredText
> - :doc:`devel/building` - This option is mainly used for assisting in Gramine
>   development. This option is intended for Gramine developers and is much more
>   involved than the other two options.
> ```

This is not right, building from source is the recommended way for more advanced users (because you get all bugfixes and improvements faster that way).
___
*[`Documentation/run-sample-application.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVz2W8RCMOyI2-AMuGb:-NVz2W8SA4qaAvbyiSPa:b-s4cwz2) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/run-sample-application.rst#L47)):*
> ```reStructuredText
> Gramine features.
> 
> Additional sample configurations for applications enabled in Gramine are
> ```

ditto, what does this even mean?



_Code quote:_
```reStructuredText
applications enabled in Gramine
```
___
*[`Documentation/tutorials-index.rst` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGX1r515U7dhYN_aV:-NVz34a1-gyUPtg40L_t:bjutnzt) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/tutorials-index.rst#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want an intro text here? I couldn't come up with anything interesting.
</blockquote></details>

If we don't have anything to say then there's no point in writing anything.
___
*[`Documentation/manpages/gramine.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnOtRc1vR6VunZY0hB:-NVz3VcXB6qdH0x2NkCe:by7g5du) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/manpages/gramine.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It actually runs a single application, so IMO it should be "an application"?


<!-- Sent from Reviewable.io -->

2023-05-22 02:13 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/environment-setup.rst` line 8 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvAZmH1X0AZSQrXC5l:-NW08gSACTDQ-gzyjX9L:b-oxe62a) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure if you can enable or disable it, wasn't it just about having the right kernel version?
</blockquote></details>

I think we have a kernel parameter to control it, see https://github.com/torvalds/linux/blob/44c026a73be8038f03dbdeef028b642880cf1511/Documentation/admin-guide/kernel-parameters.txt#L3676.
___
*[`Documentation/environment-setup.rst` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvB3bUDKxyY71qWufO:-NW09A_zAO_XDkzaLzCD:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about BIOS settings? It's missing from the list.
</blockquote></details>

+1
___
*[`Documentation/gsc-installation.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMz9p4G-umtTGC57R:-NW09PB21uycG4FGUfZG:b-o8jb4t) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/gsc-installation.rst#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wasn't `,` intended here? These are not full sentences, it's a list with items.
</blockquote></details>

hmm... It's indeed a list but I just don't see anywhere in Gramine that we use `,` at the end of a such list item (i.e., we either use `.` or have no punctuation marks). Anyway, I don't insist, pls just pick one that looks more appropriate to you.
___
*[`Documentation/index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnIorR0yV6QPXSsBGt:-NW0BTl_02Xv0-21ZWKP:b-eal647) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L14)):*
> Is assuming that everyone knows what SGX is a good idea?

They're guided to take a look at the `sgx-intro` doc if they don't?
___
*[`Documentation/index.rst` line 140 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW0CcCz4ZUwka-6h0lz:-NW0CcCz4ZUwka-6h0m-:b36phn8) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L140)):*
> ```reStructuredText
> ---------------------------
> 
> The Gramine Library OS is a complex software. The below articles provide an
> ```

But only one article for now?



_Code quote:_
```reStructuredText
articles
```
___
*[`Documentation/index.rst` line 141 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW0ClgV0Sz0PIJ4Yw0a:-NW0ClgV0Sz0PIJ4Yw0b:b-673ulj) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L141)):*
> ```reStructuredText
> 
> The Gramine Library OS is a complex software. The below articles provide an
> overview of Gramine design and implemented/unimplemented features.
> ```

Maybe just remove this as it's elaborated below?



_Code quote:_
```reStructuredText
implemented/unimplemented
```
___
*[`Documentation/quickstart.rst` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyWxxw7UyW5zRFhzi7:-NW0D8Qd8en3m8C8LghM:bm7fm46) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this document linking to itself?
</blockquote></details>

Yeah, I had the same confusion actually :). But it looks like this doc is indeed the one that describes "installing Gramine from the package repo".
___
*[`Documentation/manpages/gramine.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnOtRc1vR6VunZY0hB:-NW0COAm1GTeUyHMzHmT:b-plnisx) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/manpages/gramine.rst#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It actually runs a single application, so IMO it should be "an application"?
</blockquote></details>

+1 for `an application`


<!-- Sent from Reviewable.io -->

2023-05-22 12:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 4 of 12 files reviewed, 43 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/index.rst` line 79 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvjEnZ8IgFE04zlH_h:-NW2M_NB1txkad4RP62Z:b-gmqoug) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Though `Configure Gramine` is ambiguous... People may read it as "Set up Gramine once", instead of the intended "Provide Gramine configuration for each specific application". But I also want the title to be short. How can we achieve it?
</blockquote></details>

Not relevant anymore (stashed manifest/attestation/perf pages under `Protect your application` section)
___
*[`Documentation/index.rst` line 82 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvicH6BVGNOjyZOR8J:-NW2MgDf39IQe0vZtx3b:b-j8c52f) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not applicable (rephrased).
</blockquote></details>

Not relevant anymore (simply removed.)
___
*[`Documentation/index.rst` line 82 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVviq2jD3SJ1Dmeeuys:-NW2MimCCTK9rTzgG3iw:b-j8c52f) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not applicable (rephrased).
</blockquote></details>

Not relevant anymore (simply removed.)
___
*[`Documentation/index.rst` line 82 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvj2FTAC28oB7nSYNm:-NW2MkYH39XKIzOIFjMh:b-j8c52f) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I rephrased. I think it's important to introduce the idea that Gramine must be configured for each application, and we have a general scheme in our documentation that each sub-section starts with a quick explanatory statement. I wanted to keep it here too.
</blockquote></details>

Not relevant anymore (simply removed.)
___
*[`Documentation/index.rst` line 140 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW0CcCz4ZUwka-6h0lz:-NW2MoH7EiSF-1YifjCn:b-j8c52f) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, the idea is that we'll have more articles here. I don't know how to reformulate it such that it reflects both what is currently here (one article about implemented features) and what we will have in the future (Gramine design, etc.). I prefer to keep as-is.
</blockquote></details>

Not relevant anymore (simply removed.)
___
*[`Documentation/index.rst` line 141 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW0ClgV0Sz0PIJ4Yw0a:-NW2MpjbD44KL8efKtI-:b-j8c52f) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (see my explanation)

If I would remove this, then it will be just `...provide an overview of Gramine design.`, which the linked page has *zero* information about...
</blockquote></details>

Not relevant anymore (simply removed.)
___
*[`Documentation/index.rst` line 204 at r6](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW2MtbX1YnLb8PhR1MK:-NW2MtbX1YnLb8PhR1ML:bcvfzta) ([raw file](https://github.com/gramineproject/gramine/blob/a38cc3c1489cad1385e35d5f48da3547d11f711b/Documentation/index.rst#L204)):*
> ```reStructuredText
>    sgx-intro
>    glossary
>    devel/features
> ```

Again, not sure if this is where we should put this `Gramine features` document. Just needed to put somewhere...
___
*[`Documentation/quickstart.rst` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyWxxw7UyW5zRFhzi7:-NW2Mz6I1MPKgoirVuQ7:bojcy1z) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow What do you recommend? We want to tell users that they can install Gramine in several simple ways, and we don't want to create just a "trampoline" page. So the idea here is to first list all 3 ways, then describe the "classic" way.
</blockquote></details>

Ok, this was reworked.


<!-- Sent from Reviewable.io -->

2023-05-22 14:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 4 of 12 files reviewed, 43 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NW23Hxi53Lt2dEkAdtq:b53b507) (no related file):*
> Even if we add VM-based TEE support, the core design of Gramine will most probably stay the same, right?

What I meant is rather how the documentation is structured, not how Gramine _design_ will change. Gramine is already designed as LibOS + PAL backends, but this design is not reflected in the new documentation. The old documentation was rather agnostic about this, but the new one is actively saying that "Gramine is an SGX framework".

> Does anyone care/need such functionality? I have no idea, and I haven't seen anyone asking for this.

I think we (ITL) had at least one potential client pursuing this in the past, but I think that nothing came out of this back then.

> Wouldn't it be a pretty much _different_ Gramine? In the sense that for this, it will maybe make more sense to have a completely separate set of documentation.

But it's just a matter of adding another PAL? The whole design seems to support this well.

> By the way, I think our current documentation is already **heavily biased towards SGX**. Just look at the `Building` page, 50% of it is about SGX.

I don't agree, it's clearly split into SGX and non-SGX parts. SGX part is longer because the setup is more complicated, but that doesn't mean that the documentation is somehow biased towards it.

> In my opinion, we'll probably have to split documentation into independent web sites if/when we introduce more backends.

No, I definitely disagree here. We'll just need sub-sections in the docs about different backends. How would you imagine having different web pages for every backend? We'd need to copy-paste 70% of the docs :) (e.g. the manifest syntax)

___


<!-- Sent from Reviewable.io -->

2023-05-23 05:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 4 of 12 files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`Documentation/index.rst` line 65 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW63KmXBLq-IFkJkUL_:-NW63KmXBLq-IFkJkULa:b-c0wsoc) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L65)):*
> ```reStructuredText
>   application to ensure your environment is configured correctly.
> - :doc:`Provide an application-specific configuration file<manifest-syntax>` -
>   Gramine requires a so-called manifest file for each application.
> ```

We have above `set up the SGX environment and prepare a signing key`. But we have nowhere except here: https://github.com/gramineproject/gramine/blob/ede508c69217477c1cd6fdb3e7689da824ba4ea7/Documentation/devel/building.rst#prepare-a-signing-key that mentions a bit how we use the signing key?

And in this top-level quick-start, after this `provide an application-specific configuration file`, it looks like a user is ready-to-go but it's actually not.



_Code quote:_
```reStructuredText
- :doc:`Provide an application-specific configuration file<manifest-syntax>` -
  Gramine requires a so-called manifest file for each application.
```


<!-- Sent from Reviewable.io -->

2023-05-23 06:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 4 of 12 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NW6GpAiAej8SwUDc3Gc:b4bs25t) (no related file):*
> What I meant is rather how the documentation is structured, not how Gramine _design_ will change. Gramine is already designed as LibOS + PAL backends, but this design is not reflected in the new documentation. The old documentation was rather agnostic about this, but the new one is actively saying that "Gramine is an SGX framework".

No, you misunderstood my point. What I talked about is that even when we add other-TEE support, the documentation will stay roughly the same. For example, imagine we add Intel TDX in the future. Then the doc structure will stay the same, but we'll have changes like this:
- The intro (`Gramine supports running Linux applications using the Intel SGX (Software Guard Extensions) technology...`) will have enough paragraph with description of TDX support.
- `Protect your container: Ready-made SGX images` section will become `Protect your container: Ready-made SGX/TDX images` (because the scripts will stay almost the same for TDX, i.e. the same project will be used for both SGX and TDX images)
- `Set up the SGX environment` section will become `Set up the SGX/TDX environment` (and that page will contain two subsections -- one for SGX, and one for TDX).
- And so on.

The only case where all this `Protect your container` and co. stuff is useless and only complicates reading documentation is **if Gramine is used as a non-security framework**. E.g., as a compatibility framework.

> I think we (ITL) had at least one potential client pursuing this in the past, but I think that nothing came out of this back then.

Interesting. In this case yes, the documentation would be only confusing. But I argue that this is a very seldom case.

> But it's just a matter of adding another PAL? The whole design seems to support this well.

Well, yes, but then what kind of documentation do you even need for this case of compatibility? 95% of documentation can be thrown away, leaving only "how to install" and "how to write a manifest file". I'd argue that it would be easier to add a separate page dedicated to the case of compatibility usage and direct interested users to this page only.

> I don't agree, it's clearly split into SGX and non-SGX parts. SGX part is longer because the setup is more complicated, but that doesn't mean that the documentation is somehow biased towards it.

I disagree. Just look at the ToC at https://gramine.readthedocs.io/en/stable/: `Attestation and secret provisioning` (pure SGX), `Performance tuning...` (almost pure SGX), `Cloud deployment` (pure SGX), `Users of Gramine` (pure SGX), `Introduction to SGX` (yeah), `Tutorials` (pure SGX), `Manual pages` (95% pure SGX). How is this "clearly split"?

> No, I definitely disagree here. We'll just need sub-sections in the docs about different backends. How would you imagine having different web pages for every backend? We'd need to copy-paste 70% of the docs :) (e.g. the manifest syntax)

Ok, yeah, agreed here. But I do believe we'll need separate landing (intro) pages for each backend... And we'll probably need to hide the complexity of ToC separately for each backend.

___
___
*[`Documentation/index.rst` line 65 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW63KmXBLq-IFkJkUL_:-NW6GKqTBlYskOXRCpGO:bn0j32q) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L65)):*
> We have above `set up the SGX environment and prepare a signing key`. But we have nowhere except here: [https://github.com/gramineproject/gramine/blob/ede508c69217477c1cd6fdb3e7689da824ba4ea7/Documentation/devel/building.rst#prepare-a-signing-key](https://github.com/gramineproject/gramine/blob/ede508c69217477c1cd6fdb3e7689da824ba4ea7/Documentation/devel/building.rst#prepare-a-signing-key) that mentions a bit how we use the signing key?

Done. Added some explanation to the `sgx-setup.rst` file.

> And in this top-level quick-start, after this `provide an application-specific configuration file`, it looks like a user is ready-to-go but it's actually not.

@kailun-qin I can't understand what you wrote. What exactly you want to be changed? (Also, please don't put two independent issues in one Reviewable comment -- please create two Reviewable comments, otherwise it's hard to track progress on each sub-item.)


<!-- Sent from Reviewable.io -->

2023-05-23 16:00 UTC, mkow reviewed
> Reviewed 2 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NW8IfGNBhNlswqCkNYb:bzhdu98) (no related file):*
> No, you misunderstood my point. What I talked about is that even when we add other-TEE support, the documentation will stay roughly the same. For example, imagine we add Intel TDX in the future. Then the doc structure will stay the same, but we'll have changes like this:
> [...]

That sounds optimistic, TDX is very different from SGX, I'm not convinced that we could (and should) just glue together the docs for it and SGX under the same documentation pages. Anyways, there are many more TEEs which we may be supporting in the future which will be even more different.

> Well, yes, but then what kind of documentation do you even need for this case of compatibility? 95% of documentation can be thrown away, leaving only "how to install" and "how to write a manifest file". I'd argue that it would be easier to add a separate page dedicated to the case of compatibility usage and direct interested users to this page only.

Nah, all the debugging, performance, packaging, containers, even the curated apps make perfect sense there? I'd say that 95% of the current docs are also meaningful for compatibility usages.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NW4Sl_YEuF2zXSYq1eY:b44vwxv) (no related file):*
What's the exact reason for the latest change which moves a lot of the docs to under "Protect your application"? Most of the moved pages apply equally to GSC (manifest syntax, attestation, SGX environment setup, ...), this grouping doesn't seem to make much sense/logic to me now.

___
___
*[`Documentation/gsc-installation.rst` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnMz9p4G-umtTGC57R:-NW3Y_24CDi_zIVZIm5o:b-ts6xnt) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/gsc-installation.rst#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Reverted to `,`.
</blockquote></details>

@kailun-qin: yeah, we likely didn't do this in other places, but I _think_ it's more grammatically correct in such cases.
___
*[`Documentation/gsc-installation.rst` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvC3dO-MzSUI1Y87Ev:-NW3Y1_T40bSM5nmTkad:bpfwk3d) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Is `regular` better? I actually didn't have any problems with `original` (in the sense the "base", the "native").
</blockquote></details>

If you want to say "base", then why not just say "base"? ;)
"regular" is fine here, but definitely has a very different meaning than "base". So, depends what you actually want to say here.
___
*[`Documentation/gsc-installation.rst` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvQ05PDW8rO5RYgL70:-NW3YP6TEYsyuM5HQeYK:b1pxbck) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Just removed this sentence. The original idea was to highlight that it's **not** Docker-runs-inside-Gramine (as people often assume, whatever this would mean). But I guess the next paragraph already covers this explanation.
</blockquote></details>

Huh, that was a very convoluted way of saying this :)
___
*[`Documentation/index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnIorR0yV6QPXSsBGt:-NW3Zeov-WEo7wULM77f:b-jqxm7q) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1. The current text is definitely better than the previous one (which was very low-level and technical).
2. I like this text, as currently Gramine is a very SGX-centric technology. Plus yes, we redirect people to the appropriate SGX intro page.
</blockquote></details>

Unblocking, as you think it's ok in the current form.
___
*[`Documentation/index.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvS1p-CwJ9PNPY6WmZ:-NW3Yksi6ESV1sRCjosD:b-q81o21) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think they are totally useless? In the sense that we don't really use them (and let's be honest, we'll never use them, as it is such a pain). So when changing the text, I just removed them.

I can revert it, but honestly -- this will be totally inconsistent and will only make writers hurt their eyes (when they work with the raw text).

Anyway, if you just want to reduce the amount of irrelevant diffs in this PR, I can revert this the change to this whole para.
</blockquote></details>

I'm also not a big fan of them, but it was more about unrelated changes included in this PR obscuring the diff ;) But I won't block about this if you want them removed now.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NW3ZtSFDQn4k_mXbGOc:b-3xwwux) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
> Also, if you read any CS scientific paper [...]

But papers are very different - they are like books, they have pages which are presented to you in order and the intended way of reading is going through all of them front to back. Papers usually don't even have an index/ToC with page numbers.

// Will keep this open until the end of review as I'm wondering about other's opinion (but if no one will say anything I'll just resolve it later).
___
*[`Documentation/index.rst` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4RbIK1BaOHzehiP5u:-NW4RbIK1BaOHzehiP5v:bja6p0k) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L59)):*
> ```reStructuredText
> 
> .. note ::
>    Confidential compute images is not an official part of Gramine.
> ```

Why did you remove this?
___
*[`Documentation/index.rst` line 41 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4PS3_9SV2wWfn-i8E:-NW4PS3_9SV2wWfn-i8F:b-s9atyq) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L41)):*
> and keep it protected

Again, protected from/against what? Without it it's just an empty word without any meaning.


<!-- Sent from Reviewable.io -->

2023-05-23 19:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @BFuhry, @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NW8mndR1brMnQ6TKH4u:b1oyh4s) (no related file):*
> That sounds optimistic, TDX is very different from SGX ...

It really depends on how you design your Gramine-TDX software. You can make it almost indistinguishable from Gramine-TDX, if you really want to :)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NW8nJ5i1bhdibALQyEu:b-fl0ylk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the exact reason for the latest change which moves a lot of the docs to under "Protect your application"? Most of the moved pages apply equally to GSC (manifest syntax, attestation, SGX environment setup, ...), this grouping doesn't seem to make much sense/logic to me now.
</blockquote></details>

Ah, I didn't explain the logic behind this, sorry:
1. Benny really wanted to have less 1-level sections (`Protect your container`, `Protect your application`, ...) . The original idea of the documentation re-write was to make it easier for the user with just several options, from easier to harder: section on ready-made or almost-ready containers, section on protecting applications from scratch, section on deep debug of failing applications and on production deployment strategies (this is `Develop Gramine`), and section for Gramine developers. And yeah, `Resources` for everything else that doesn't fit in above categories.
2. The `manifest syntax`, `attestation`, and `perf analysis` pages seemed to fall under the `protecting applications from scratch` category, that's why I moved them there.

What division would you propose?

___
___
*[`Documentation/gsc-installation.rst` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvC3dO-MzSUI1Y87Ev:-NW8yoXF2wrQyL0HcHpq:b-rlwicn) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you want to say "base", then why not just say "base"? ;)
"regular" is fine here, but definitely has a very different meaning than "base". So, depends what you actually want to say here.
</blockquote></details>

Well, ok, `base` is probably the best word. I'll fix it tomorrow.
___
*[`Documentation/index.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvS1p-CwJ9PNPY6WmZ:-NW8z4BN7tyNdU_8S9U0:bf90y2a) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm also not a big fan of them, but it was more about unrelated changes included in this PR obscuring the diff ;) But I won't block about this if you want them removed now.
</blockquote></details>

Fair enough, I'll restore them to remove the diff noise in the PR.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NW8zD1k4sGcFvizZvgE:b-sxjz0z) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Also, if you read any CS scientific paper [...]

But papers are very different - they are like books, they have pages which are presented to you in order and the intended way of reading is going through all of them front to back. Papers usually don't even have an index/ToC with page numbers.

// Will keep this open until the end of review as I'm wondering about other's opinion (but if no one will say anything I'll just resolve it later).
</blockquote></details>

@BFuhry @donporter I think you have the most experience with technical web documentation? Any thoughts?
___
*[`Documentation/index.rst` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4RbIK1BaOHzehiP5u:-NW8zNinC8CuYSxXC2iu:b-ehtq7g) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you remove this?
</blockquote></details>

Because I also removed any other links that jump directly to that "Confidentail Compute for X" (new name of "Curated Applications") from this documentation. I.e., the only way to jump to that project is through the `curated-installation.rst` document -- and that document contains this big note already.

So I thought that duplication (given that the reader will see the other note anyway) was unwarranted and only broke the flow of reading of this `index.rst` page.

Should I restore the note back anyway?
___
*[`Documentation/index.rst` line 41 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4PS3_9SV2wWfn-i8E:-NW9-0kW39RZydIVSvpi:b-kd1y84) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> and keep it protected

Again, protected from/against what? Without it it's just an empty word without any meaning.
</blockquote></details>

I'll add something here.


<!-- Sent from Reviewable.io -->

2023-05-23 22:06 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/index.rst` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGQBt179jO7q4ETOK:-NW9bYgh32bISM-gZj6m:bghe40) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this is not about development of Gramine? It's just another way to use Gramine.
</blockquote></details>

No longer valid. Text was moved to "Gramine installation options"
___
*[`Documentation/index.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvS1p-CwJ9PNPY6WmZ:-NW9_dSn3OQOFsu4jv5Y:bxa8yt8) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough, I'll restore them to remove the diff noise in the PR.
</blockquote></details>

By now, even this PR is full of changes unrelated to the restructuring. Especially Michal's comments at a few places were about text that was just moved. This is not necessarily bad as it had to be done anyhow. Consequentially, I would recommend to not undo work here you have already done, which should be done anyhow.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NW9a9TD1-mHAhMFoDr9:b-xviwgh) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@BFuhry @donporter I think you have the most experience with technical web documentation? Any thoughts?
</blockquote></details>

The new index page is one of the biggest improvements that was done by the restructuring. In the words of Deb: you have to take the reader by the hand and show him/her the path through the documentation. In fact that would be needed at many other places in the documentation, but the index is a good start. Gramine is not only for hard core developers or at least it should not be.
___
*[`Documentation/index.rst` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4RbIK1BaOHzehiP5u:-NW9bBuuAoJhUh-mrT6T:bphwsu9) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because I also removed any other links that jump directly to that "Confidentail Compute for X" (new name of "Curated Applications") from this documentation. I.e., the only way to jump to that project is through the `curated-installation.rst` document -- and that document contains this big note already.

So I thought that duplication (given that the reader will see the other note anyway) was unwarranted and only broke the flow of reading of this `index.rst` page.

Should I restore the note back anyway?
</blockquote></details>

I fully agree with Dmitrii's reasons and I would leave it as it is now.
___
*[`Documentation/index.rst` line 204 at r6](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW2MtbX1YnLb8PhR1MK:-NW9blALBhGPomszs_fj:bvc3mll) ([raw file](https://github.com/gramineproject/gramine/blob/a38cc3c1489cad1385e35d5f48da3547d11f711b/Documentation/index.rst#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Again, not sure if this is where we should put this `Gramine features` document. Just needed to put somewhere...
</blockquote></details>

I would move it further up in the resources section. Potentially even to the top of the section


<!-- Sent from Reviewable.io -->

2023-05-24 08:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 4 of 12 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/gsc-installation.rst` line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvC3dO-MzSUI1Y87Ev:-NWBsy5I63by_Zf135Qu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, ok, `base` is probably the best word. I'll fix it tomorrow.
</blockquote></details>

Done.
___
*[`Documentation/gsc-installation.rst` line 10 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvQ5a6-L7237co2Avk:-NWBsykP1_l4j-ZcM2Vb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/gsc-installation.rst#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnIorR0yV6QPXSsBGt:-NWBtCXfA7461p7RNKYd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unblocking, as you think it's ok in the current form.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGQBt179jO7q4ETOK:-NWBrbWh3msafg8YHzH6:b-ocnrkc) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/index.rst#L231)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

No longer valid. Text was moved to "Gramine installation options"
</blockquote></details>

Yes, not valid anymore.
___
*[`Documentation/index.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvS1p-CwJ9PNPY6WmZ:-NWBt4tEEB2TITx-Zy1e:b-ecl1u9) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L9)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

By now, even this PR is full of changes unrelated to the restructuring. Especially Michal's comments at a few places were about text that was just moved. This is not necessarily bad as it had to be done anyhow. Consequentially, I would recommend to not undo work here you have already done, which should be done anyhow.
</blockquote></details>

Ok, given Benny's comment and the fact that `index.rst` was anyhow 95% reworked, I'm keeping it as is.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NWBtHWV2nP9CEfA6Dyl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

The new index page is one of the biggest improvements that was done by the restructuring. In the words of Deb: you have to take the reader by the hand and show him/her the path through the documentation. In fact that would be needed at many other places in the documentation, but the index is a good start. Gramine is not only for hard core developers or at least it should not be.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4RbIK1BaOHzehiP5u:-NWBu8WD6n4-FE0YItjm:b9gbuat) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L59)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I fully agree with Dmitrii's reasons and I would leave it as it is now.
</blockquote></details>

Based on Benny's comment, I'm not restoring the note currently, and waiting for Michal's reply.
___
*[`Documentation/index.rst` line 204 at r6](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW2MtbX1YnLb8PhR1MK:-NWBuaZLDB940kpvci5t:b-wq2w0k) ([raw file](https://github.com/gramineproject/gramine/blob/a38cc3c1489cad1385e35d5f48da3547d11f711b/Documentation/index.rst#L204)):*
<details><summary><i>Previously, BFuhry wrote…</i></summary><blockquote>

I would move it further up in the resources section. Potentially even to the top of the section
</blockquote></details>

Done. Also updated the corresponding descriptive text.
___
*[`Documentation/index.rst` line 41 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4PS3_9SV2wWfn-i8E:-NWBtqT08QQxptTGNkPy:b-nqcr5v) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll add something here.
</blockquote></details>

Done.

I added the `protected against a malicious host` at the very beginning of the documentation on this page (to set the scene). I also added a similar text in this particular place.


<!-- Sent from Reviewable.io -->

2023-05-24 23:27 UTC, mkow reviewed
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWF20bC6B69WUd_XfTo:b1z41pi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I didn't explain the logic behind this, sorry:
1. Benny really wanted to have less 1-level sections (`Protect your container`, `Protect your application`, ...) . The original idea of the documentation re-write was to make it easier for the user with just several options, from easier to harder: section on ready-made or almost-ready containers, section on protecting applications from scratch, section on deep debug of failing applications and on production deployment strategies (this is `Develop Gramine`), and section for Gramine developers. And yeah, `Resources` for everything else that doesn't fit in above categories.
2. The `manifest syntax`, `attestation`, and `perf analysis` pages seemed to fall under the `protecting applications from scratch` category, that's why I moved them there.

What division would you propose?
</blockquote></details>

I like and agree with 1., but it was already like that before the most recent change, which is 2.

I don't see much logic with moving these documents there, as I said above, because they are generic and related to all use-cases. E.g. why is "Set up the SGX environment" relevant only to protecting an app, and not to protecting a Docker container? Same with other moved pages.

___
___
*[`Documentation/index.rst` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvS1p-CwJ9PNPY6WmZ:-NWF3DJmBXiG1wsHNi06:b-9mlgkx) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, given Benny's comment and the fact that `index.rst` was anyhow 95% reworked, I'm keeping it as is.
</blockquote></details>

As above, not blocking ;) But please don't do that in the future, if that was a bigger thing I'd block and ask for a split, especially that probably not everyone agrees with removing these. After all, someone has added them there in the first place.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NWF42GMBDCrnFkC-g_U:br8metv) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, thanks for the explanations! I'm still not convinced, but at least now I get the idea behind this :)
Tbh for me the biggest improvement is the clearer ToC. I'd assume it's much more used than the index.


<!-- Sent from Reviewable.io -->

2023-05-25 07:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 6 of 12 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWGtRkn7Yinrk9JVQPw:b-qstnf8) (no related file):*
> E.g. why is "Set up the SGX environment" relevant only to protecting an app, and not to protecting a Docker container?

Ok, looking at the contents of that page, I agree that it's generic to both app and Docker ways...

> Same with other moved pages.

I disagree. The `Manifest syntax` page is mostly applicable to "apps from scratch" way of doing things, because GSC (ideally) doesn't require any manifest options at all -- that's not true currently and probably will never be true, but we also don't have a proper page that describes what parts of the manifest syntax still required for GSC and which not. And with ready-made applications, users don't need to care about the manifest at all -- it is completely created on the fly and hidden from the user.

**Conclusion**: looks like we just need to spend a whole hour on documentation ToC discussion in the next Gramine meeting. Otherwise we'll never reach any form of consensus.

___


<!-- Sent from Reviewable.io -->

2023-05-25 10:29 UTC, kailun-qin reviewed
> Reviewed 2 of 7 files at r5, 1 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NWHRVrX2xlagiSrxTou:b-rv5vmm) (no related file):*
> By the way, I think our current documentation is already **heavily biased towards SGX**. Just look at the `Building` page, 50% of it is about SGX.

Looking back at Gramine's into: https://github.com/gramineproject/gramine#what-is-gramine. It looks like we really don't have much bias. ;)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWHOUdZ02Xc9mtnCNCx:bj8j8pm) (no related file):*
> I don't see much logic with moving these documents there

I see some logic behind this (but not that obvious).

> Benny really wanted to have less 1-level sections (`Protect your container`, `Protect your application`, ...)

This is fine, but what's wrong w/ just adding one more 1-level section (after `Protect your application`) that is `Configure Gramine` where we can put `manifest syntax`, `attestation`, and `perf analysis` there (like we did before in this PR)? In this way, it looks like we are following the logic #1 (from easier to harder) well.

As for `Set up the SGX environment`, technically it applies to both app and Docker ways, but I don't see a more proper place to put it -- IMO it's fine to have it in `Protect your application`.

> The `Manifest syntax` page is mostly applicable to "apps from scratch" way of doing things, because GSC (ideally) doesn't require any manifest options at all

Yep, I agree w/ this. But...

> -- that's not true currently and probably will never be true

since it's not the case at this moment, why not have it in `Configure Gramine`?

___
___
*[`Documentation/index.rst` line 65 at r7](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW63KmXBLq-IFkJkUL_:-NWHG24EBPIlfX6RLqef:bwtuxfw) ([raw file](https://github.com/gramineproject/gramine/blob/22b729abbd9c8111cccfa7d1409270e963e7ddca/Documentation/index.rst#L65)):*
> But really, I would postpone it to a future PR.

Sure, let's do it separtely if needed.


<!-- Sent from Reviewable.io -->

2023-05-26 00:07 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWKLEXA--9BD6uIl2Hc:b5vr6fh) (no related file):*

> > Same with other moved pages.
> 
> I disagree. The `Manifest syntax` page is mostly applicable to "apps from scratch" way of doing things, because GSC (ideally) doesn't require any manifest options at all -- that's not true currently and probably will never be true, but we also don't have a proper page that describes what parts of the manifest syntax still required for GSC and which not.

In ideal world yes, but as you say, currently writing a simple manifest is often required for GSC (see e.g. https://github.com/gramineproject/gsc/blob/9d3bc471c73d540e046ce72da5fcd1bcc29f7d2e/Examples/openvino/ubuntu20.04-openvino.manifest). So, in the current state of affairs this page is relevant to all sections.

It's similar with attestation and performance analysis - I don't see why they would be less relevant to GSC / curated apps.

> **Conclusion**: looks like we just need to spend a whole hour on documentation ToC discussion in the next Gramine meeting. Otherwise we'll never reach any form of consensus.

Sure, we can discuss this also on the call (although on 30.05 I'll be at least 30 min late, unfortunately I have a conflict).
Overall, the previous version of the grouping didn't seem controversial and I liked it, it's only about the recently pushed reshuffling.

> This is fine, but what's wrong w/ just adding one more 1-level section (after `Protect your application`) that is `Configure Gramine` where we can put `manifest syntax`, `attestation`, and `perf analysis` there (like we did before in this PR)? In this way, it looks like we are following the logic [#1](https://github.com/gramineproject/gramine/pull/1) (from easier to harder) well.

I really like this idea.

> As for `Set up the SGX environment`, technically it applies to both app and Docker ways, but I don't see a more proper place to put it -- IMO it's fine to have it in `Protect your application`.

Why not under "Configure Gramine"? IMO much more appropriate there, because both GSC and curated apps require this step.

___


<!-- Sent from Reviewable.io -->

2023-05-26 01:06 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWKVbes6B2lB3icvvqz:be8lzif) (no related file):*
> Why not under "Configure Gramine"?

I thought it was more about setting up SGX, not Gramine, strictly speaking. And setting up SGX should (user-friendly and technically) be in the very first steps if possible (otherwise it's a bit contradictive w/ "from easier to harder").

>  because both GSC and curated apps require this step.

Yeah, I agree w/ this. I re-think about it, it also makes some sense to have it under `Configure Gramine` considering users may not read our docs strictly following the order (i.e., instead, they may directly jump into one or more sections; in this case I believe it's appropriate to have it under `Configure Gramine`).

___


<!-- Sent from Reviewable.io -->

2023-05-26 10:30 UTC, BFuhry reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWMS3rQ63ZRqh59CYjl:bpqigbu) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Why not under "Configure Gramine"?

I thought it was more about setting up SGX, not Gramine, strictly speaking. And setting up SGX should (user-friendly and technically) be in the very first steps if possible (otherwise it's a bit contradictive w/ "from easier to harder").

>  because both GSC and curated apps require this step.

Yeah, I agree w/ this. I re-think about it, it also makes some sense to have it under `Configure Gramine` considering users may not read our docs strictly following the order (i.e., instead, they may directly jump into one or more sections; in this case I believe it's appropriate to have it under `Configure Gramine`).
</blockquote></details>

The high level idea is to restructure the TOC to make it easily consumable to end users. The end users should see the 1-level sections and easily decide on `how to use Gramine` from easy to hard. Based on the decision, the provided information should focus on the most important information. 

The original idea was:
1. Simplest: Ready-made apps
2. Simple: GSC
3. Hard: Manifest file related way (which we now call 'protect your application')

Due to discussions, the third section was split once more to:
1. Simplest: Ready-made apps
2. Simple: GSC
3. Hard: Manifest file related way (which we now call 'protect your application')
4. Hardest: develop Gramine

After doubts regarding ready-made apps, 1 and 2 was merged to:
1. Simple:  `protect your container`.
2. Hard: Manifest file related way (which we now call 'protect your application')
3. Hardest: develop Gramine

Adding a section called `Configure Gramine` does not at all fit into the idea of the TOC, because `Configure Gramine` is not a way to use Gramine. One big benefit of the new TOC is that end users that decide on a way to use Gramine are not required to look at other 1-level sections.

In my opinion, the `manifest syntax`, `attestation`, and `perf analysis` pages should be in the category to which it fits best - `protect your application`. I get the argument that they *might* have relevance to GSC, but we should not confuse people with that by default. `protect your application` should be presented as the easy/easier way to do things. However, nothing speaks again linking to `manifest syntax`, `attestation`, and `perf analysis` from the GSC documentation. Anyhow, the GSC documentation is pretty bad and does require a major rewrite. It should first explain the why, then the how, and then mention the more advanced topics that might be needed, e.g., `manifest syntax`, `attestation`, and `perf analysis`. Additionally, it should not be on a separate page (but that is a separate discussion on its own).

The situation is strongly comparable to the Gramine installation options page (https://gramine.readthedocs.io/en/dimakuv-docs-reorg/installation.html). The page only contains the two easy/easier ways to install Gramine and links to `Develop Gramine` for `Build and install Gramine from source`. Source installation fits in both categories, but it was moved to the section where it fits best - `Develop Gramine`. Many end users that want to protect their application will not care about installation from source (or at least not right from the start). Comparably, many end users that want to protect their container will not care about the manifest syntax, attestation, and performance analysis (or at least not right from the start). Once the end users starts to care, links will easily guide them to what they need. At no point will they have to look at other 1-level sections and this is how it should be.

In general, I'm strongly against adding another 1-level section - the number is already (too) high as it is now. 
I have a reasonably big 4k screen which seems to be the only possibility to see the entire toc at once.
In fact, we should rather remove 1-level sections if possible or at least reduce the number of 2-level links.

___


<!-- Sent from Reviewable.io -->

2023-05-26 13:42 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWN7s4x8tXXcSW4s9s4:b-h481sb) (no related file):*
Overall I agree with this design, but it can't go against reality :) E.g. if configuring SGX is required to use GSC, we can't just pretend that it's not required and simplify the documentation assuming that.

> Adding a section called `Configure Gramine` does not at all fit into the idea of the TOC, because `Configure Gramine` is not a way to use Gramine. One big benefit of the new TOC is that end users that decide on a way to use Gramine are not required to look at other 1-level sections.

But that's just not how it is right now. The sections I listed are required/shared by both use-cases, and in general, this seems to be a problem with this ToC design - it doesn't work well when a lot of information is shared between all use-cases. And I think it will always be the case with Gramine, so we need to find a structurization which supports that.

> In my opinion, the `manifest syntax`, `attestation`, and `perf analysis` pages should be in the category to which it fits best - `protect your application`. [...]

But these _are_ relevant to all use-cases. E.g. using GSC without attestation is pointless. Now we give an impression that attestation is only needed if you don't use containers. I mean, attestation is equally relevant to GSC and the standard usage. Same with SGX setup.

> The situation is strongly comparable to the Gramine installation options page ([https://gramine.readthedocs.io/en/dimakuv-docs-reorg/installation.html](https://gramine.readthedocs.io/en/dimakuv-docs-reorg/installation.html)). The page only contains the two easy/easier ways to install Gramine and links to `Develop Gramine` for `Build and install Gramine from source`. Source installation fits in both categories, but it was moved to the section where it fits best - `Develop Gramine`.

Hmm, I think I didn't get the comparison here. If you use GSC or curated apps then none of these instructions is relevant, because GSC is handling the Gramine building and installation? And also, you say that building from source is relevant to both (I don't think this is really the case) and thus was moved to another section. But that's exactly what I'm proposing - if something fits both usecases, then it should not be artificially assigned to one of them, but land in a separate group.

> Many end users that want to protect their application will not care about installation from source (or at least not right from the start). Comparably, many end users that want to protect their container will not care about the manifest syntax, attestation, and performance analysis (or at least not right from the start).

How is this relevant to all these sections being under "Protect your application", but not under "Protect your container"?

> Once the end users starts to care, links will easily guide them to what they need. At no point will they have to look at other 1-level sections and this is how it should be.

I agree with this idea, but it's not what the current structure leads to - you have a split into 2 very different use-cases, so why someone going the 1st way would look at the documentation for the 2nd way? It seems illogical that the documentation for a very different 2nd use-case contains required information for the 1st use-case.

> In general, I'm strongly against adding another 1-level section - the number is already (too) high as it is now.  
> In fact, we should rather remove 1-level sections if possible or at least reduce the number of 2-level links.

But why a single additional entry would be a problem? Why is there a difference between 1-level and 2-level sections? They take the same amount of the screen space. 1-level sections are IMO really nice, because they group things together and make finding stuff easier (assuming the grouping is logical).
Moreover, should we also restrain from adding new documentation pages in the future? Even if we agree to remove sections now, I don't see how this is supposed to work in the future.

> I have a reasonably big 4k screen which seems to be the only possibility to see the entire toc at once.  

The number of pages in the documentation will only keep growing and I wouldn't hope that it will fit on a single screen. I'd like the documentation to be short and precise, but not at the cost of removing useful things. After all, this is a technical documentation, not an entry-level-only tutorial which can omit more complicated details.

___


<!-- Sent from Reviewable.io -->

2023-05-31 12:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 10 of 12 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NWlpADL0kO6xPgUFZI5:b-8h83v6) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> By the way, I think our current documentation is already **heavily biased towards SGX**. Just look at the `Building` page, 50% of it is about SGX.

Looking back at Gramine's into: https://github.com/gramineproject/gramine#what-is-gramine. It looks like we really don't have much bias. ;)
</blockquote></details>

@mkow I got lost in this comment. Please check the latest version of the docs. Is there something that is still blocking in this comment?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4Sl_YEuF2zXSYq1eX:-NWlpI6k0VU3xFOa7kWv:b-148xx2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Overall I agree with this design, but it can't go against reality :) E.g. if configuring SGX is required to use GSC, we can't just pretend that it's not required and simplify the documentation assuming that.

> Adding a section called `Configure Gramine` does not at all fit into the idea of the TOC, because `Configure Gramine` is not a way to use Gramine. One big benefit of the new TOC is that end users that decide on a way to use Gramine are not required to look at other 1-level sections.

But that's just not how it is right now. The sections I listed are required/shared by both use-cases, and in general, this seems to be a problem with this ToC design - it doesn't work well when a lot of information is shared between all use-cases. And I think it will always be the case with Gramine, so we need to find a structurization which supports that.

> In my opinion, the `manifest syntax`, `attestation`, and `perf analysis` pages should be in the category to which it fits best - `protect your application`. [...]

But these _are_ relevant to all use-cases. E.g. using GSC without attestation is pointless. Now we give an impression that attestation is only needed if you don't use containers. I mean, attestation is equally relevant to GSC and the standard usage. Same with SGX setup.

> The situation is strongly comparable to the Gramine installation options page ([https://gramine.readthedocs.io/en/dimakuv-docs-reorg/installation.html](https://gramine.readthedocs.io/en/dimakuv-docs-reorg/installation.html)). The page only contains the two easy/easier ways to install Gramine and links to `Develop Gramine` for `Build and install Gramine from source`. Source installation fits in both categories, but it was moved to the section where it fits best - `Develop Gramine`.

Hmm, I think I didn't get the comparison here. If you use GSC or curated apps then none of these instructions is relevant, because GSC is handling the Gramine building and installation? And also, you say that building from source is relevant to both (I don't think this is really the case) and thus was moved to another section. But that's exactly what I'm proposing - if something fits both usecases, then it should not be artificially assigned to one of them, but land in a separate group.

> Many end users that want to protect their application will not care about installation from source (or at least not right from the start). Comparably, many end users that want to protect their container will not care about the manifest syntax, attestation, and performance analysis (or at least not right from the start).

How is this relevant to all these sections being under "Protect your application", but not under "Protect your container"?

> Once the end users starts to care, links will easily guide them to what they need. At no point will they have to look at other 1-level sections and this is how it should be.

I agree with this idea, but it's not what the current structure leads to - you have a split into 2 very different use-cases, so why someone going the 1st way would look at the documentation for the 2nd way? It seems illogical that the documentation for a very different 2nd use-case contains required information for the 1st use-case.

> In general, I'm strongly against adding another 1-level section - the number is already (too) high as it is now.  
> In fact, we should rather remove 1-level sections if possible or at least reduce the number of 2-level links.

But why a single additional entry would be a problem? Why is there a difference between 1-level and 2-level sections? They take the same amount of the screen space. 1-level sections are IMO really nice, because they group things together and make finding stuff easier (assuming the grouping is logical).
Moreover, should we also restrain from adding new documentation pages in the future? Even if we agree to remove sections now, I don't see how this is supposed to work in the future.

> I have a reasonably big 4k screen which seems to be the only possibility to see the entire toc at once.  

The number of pages in the documentation will only keep growing and I wouldn't hope that it will fit on a single screen. I'd like the documentation to be short and precise, but not at the cost of removing useful things. After all, this is a technical documentation, not an entry-level-only tutorial which can omit more complicated details.
</blockquote></details>

Done . I added a new fixup commit, based on the discussion described here: https://github.com/gramineproject/gramine/discussions/1372

___
___
*[`Documentation/environment-setup.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVz0J8R7SYiuCuO_01R:-NWlpYEe-HhBFb47cLQC:b-y2nls7) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/environment-setup.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done again :) Changed the title and added a note.


<!-- Sent from Reviewable.io -->

2023-06-01 02:22 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 10 of 12 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`Documentation/index.rst` line 73 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWojvqh3lMS9-UGrzdy:-NWojvqi16HXWcRLzLBO:bl4t37x) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/index.rst#L73)):*
> ```reStructuredText
> To achieve security and performance guarantees, Gramine must be configured
> appropriately for each application. Also, the host platform must be correctly
> set up.
> ```

I'd reverse the order, e.g., `To run an application with Gramine, the host platform must be correctly set up first. Further, to achieve security and performance guarantees, Gramine must be configured appropriately for each application.`



_Code quote:_
```reStructuredText
To achieve security and performance guarantees, Gramine must be configured
appropriately for each application. Also, the host platform must be correctly
set up.
```
___
*[`Documentation/sgx-setup.rst` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWokl369K8jVm96_sCN:-NWokl369K8jVm96_sCO:bt2jb8u) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/sgx-setup.rst#L5)):*
> ```reStructuredText
> 
> .. note ::
>    Currently, Gramine has only the SGX backend. This page describes how to set
> ```

But we do have two backends? See https://github.com/gramineproject/gramine/blob/e3ca2020d2cce5571011e03d9d7d083760af288b/Documentation/devel/features.md#L27-L29.



_Code quote:_
```reStructuredText
Currently, Gramine has only the SGX backend.
```


<!-- Sent from Reviewable.io -->

2023-06-01 07:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 10 of 12 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/index.rst` line 73 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWojvqh3lMS9-UGrzdy:-NWpld_U-TAFbnDueChz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/index.rst#L73)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'd reverse the order, e.g., `To run an application with Gramine, the host platform must be correctly set up first. Further, to achieve security and performance guarantees, Gramine must be configured appropriately for each application.`
</blockquote></details>

Done.
___
*[`Documentation/sgx-setup.rst` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWokl369K8jVm96_sCN:-NWpmzzrCk9xttS1nLFX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/sgx-setup.rst#L5)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But we do have two backends? See https://github.com/gramineproject/gramine/blob/e3ca2020d2cce5571011e03d9d7d083760af288b/Documentation/devel/features.md#L27-L29.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 09:18 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 26 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)



<!-- Sent from Reviewable.io -->

2023-06-03 23:39 UTC, mkow requested changes
> Reviewed 2 of 7 files at r5, 1 of 3 files at r6, 1 of 2 files at r7, 1 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVveu674_NimsFEXK_H:-NWmJFVS2imEf694aitf:bkbk3yy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I got lost in this comment. Please check the latest version of the docs. Is there something that is still blocking in this comment?
</blockquote></details>

There were two issues:
- What to do with pages shared between different workflows (already fixed)
- Have some more discussions about this overall design and how will it survive against the future changes (also done).

So, I'm unblocking now.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWmSXFt7HB7F08ifvSg:-NWmSXFt7HB7F08ifvSh:bqgdaa3) (no related file):*
TODO for myself: check if all .rst files are linked to in ToC _after rebasing to the current master_ (something might have been added in the meantime).

___
___
*[`Documentation/index.rst` line 59 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NW4RbIK1BaOHzehiP5u:-NWmLWFs8PRovdCD9a6L:b-nec2kw) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Based on Benny's comment, I'm not restoring the note currently, and waiting for Michal's reply.
</blockquote></details>

Ok, makes sense.
___
*[`Documentation/index.rst` line 122 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWmREhTAFDgaGFupqHE:-NWmREhTAFDgaGFupqHF:b-9zpzpj) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/index.rst#L122)):*
> If you prefer emails, send them to the Gramine Users mailing list.

Prefer it over what? It sounds like this was copied from a longer list of contact links, but now it's only this one left?
___
*[`Documentation/tutorials-index.rst` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVnGX1r515U7dhYN_aV:-NX2Vu7j-lZ9J7RInx-f:bsjr2hs) ([raw file](https://github.com/gramineproject/gramine/blob/9b3bbe8a91c656d21a9f177598f0c8aa9948c77a/Documentation/tutorials-index.rst#L3)):*
> I guess that's not how technical documentation works for most people :)

Being concise actually helps readability. Having walls of text everywhere makes people skip them and just  look at ToC instead.

> I guess that's not how technical documentation works for most people :) (What I mean is: as much as I hate all those `Introduction` and `The paper/blog/article is structured as follows...`, people continue to write this way, so I guess most folks find it easier to read?)

So, you have something to say here, which is the summary of the pages? But if that would be just listing the titles which are listed below, then it actually lowers readability - it bloats the text with useless duplications.
___
*[`Documentation/quickstart.rst` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVyWxxw7UyW5zRFhzi7:-NWmT4WzEm4_iXHxbe37:b-lgiavf) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/quickstart.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, this was reworked.
</blockquote></details>

Looks good now. No, I didn't want trampoline pages, just removal of those confusing links :) You clicked them, and the current page reloaded, and that was all. IMO super confusing.
___
*[`Documentation/sgx-setup.rst` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWokl369K8jVm96_sCN:-NX2X3FL9zJy2Vmipfm6:b4zsazh) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/sgx-setup.rst#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd use `Linux` and `Linux-SGX` names instead, using `sgx` and `direct` will be really confusing if we add any other platform. These are only command suffixes, not backend names and don't make much sense when used to describe backends in the general documentation. They make sense in the commands names, because there you have the host system already implicitly specified (that `Linux-` part of the name).
___
*[`Documentation/sgx-setup.rst` line 14 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2XeZj7muloJNmxQ2d:-NX2XeZj7muloJNmxQ2e:b-s5rbxv) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L14)):*
> starting from this version, Linux enables the FSGSBASE feature

But it wasn't disabled before, it just wasn't there at all?
___
*[`Documentation/sgx-setup.rst` line 41 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2Y0bQ-tpQwQ7ioW9H:-NX2Y0bQ-tpQwQ7ioW9I:b-q3m8pf) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L41)):*
> ```reStructuredText
> not disclose it to anyone. See also :doc:`manpages/gramine-sgx-gen-private-key`.
> 
> Signing an SGX enclave is critical to enforcing its security. First, only signed
> ```

But it's not? It matters only if you attest to `MRSIGNER`, if you attest to `MRENCLAVE` then this key doesn't matter at all.



_Code quote:_
```reStructuredText
Signing an SGX enclave is critical to enforcing its security.
```
___
*[`Documentation/sgx-setup.rst` line 45 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2YMHzDeZMgfTp3Bda:-NX2YMHzDeZMgfTp3Bdb:b-ji76bt) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L45)):*
> [SIGSTRUCT] includes a measurement of the enclave code (so-called MRENCLAVE) and metadata; thus, the process of enclave signing guarantees the expected initial state of the loaded enclave

I don't understand this sentence, signing has no relevance w.r.t. guaranteeing the initial state? The initial state and `SIGSTRUCT` can actually be maliciously modified, so you don't have that guarantee at all. It's the attestation which proves that you're talking with an enclave started from a specific initial state, not signing.


<!-- Sent from Reviewable.io -->

2023-06-05 07:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWmSXFt7HB7F08ifvSg:-NX9MPIF8AwDUZQqxfIZ:bssbyrp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: check if all .rst files are linked to in ToC _after rebasing to the current master_ (something might have been added in the meantime).
</blockquote></details>

Our `make html` and our CI actually complain about exactly this. But sure, please double-check this then.

___
___
*[`Documentation/index.rst` line 122 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWmREhTAFDgaGFupqHE:-NX9NBoA4GN4NLTt7SWV:b-2jzlit) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/index.rst#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If you prefer emails, send them to the Gramine Users mailing list.

Prefer it over what? It sounds like this was copied from a longer list of contact links, but now it's only this one left?
</blockquote></details>

Done. Yes, this was actually wrong.

Since we already have `Getting help` section in this file, I copy-pasted from our README, which anyway has a better and more up-to-date text. And removed from here to avoid duplication.
___
*[`Documentation/sgx-setup.rst` line 5 at r10](https://reviewable.io/reviews/gramineproject/gramine/1362#-NWokl369K8jVm96_sCN:-NX9Os1BEEmNY4qQ-SRV:bm7q6wr) ([raw file](https://github.com/gramineproject/gramine/blob/13d9a72b7f52b284aca7dffd77f76e73bfdd3c83/Documentation/sgx-setup.rst#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd use `Linux` and `Linux-SGX` names instead, using `sgx` and `direct` will be really confusing if we add any other platform. These are only command suffixes, not backend names and don't make much sense when used to describe backends in the general documentation. They make sense in the commands names, because there you have the host system already implicitly specified (that `Linux-` part of the name).
</blockquote></details>

Done. Fair enough.
___
*[`Documentation/sgx-setup.rst` line 14 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2XeZj7muloJNmxQ2d:-NX9P3q11wiipof3aUyx:b5edm1q) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> starting from this version, Linux enables the FSGSBASE feature

But it wasn't disabled before, it just wasn't there at all?
</blockquote></details>

Done. I think it's the Intel's habit of using "enable" as a synonym for "has"/"exists".
___
*[`Documentation/sgx-setup.rst` line 41 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2Y0bQ-tpQwQ7ioW9H:-NX9TJW2CootFwFHdC-g:b-ibr221) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it's not? It matters only if you attest to `MRSIGNER`, if you attest to `MRENCLAVE` then this key doesn't matter at all.
</blockquote></details>

Done. I rephrased this paragraph. Unfortunately, it's still too vague, and I don't want to go into details here. The idea of this paragraph is to briefly answer an obvious question: "Why do I need to sign the enclave, what is this key that I'm creating?". Previously we didn't have anything in this section, and now I added at least some explanation that this is indeed a needed thing.

By the way, this SIGSTRUCT story is *very convoluted*. It's always required to start the SGX enclave, though if you don't use SGX sealing and don't use `MRSIGNER`, you don't really need to have a SIGSTRUCT... Especially given that smth similar to SIGSTRUCT (to my knowledge) is not used by any other TEE technology. So explaining it is tough.
___
*[`Documentation/sgx-setup.rst` line 45 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2YMHzDeZMgfTp3Bda:-NX9TKH68sZNXYMAXpkf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [SIGSTRUCT] includes a measurement of the enclave code (so-called MRENCLAVE) and metadata; thus, the process of enclave signing guarantees the expected initial state of the loaded enclave

I don't understand this sentence, signing has no relevance w.r.t. guaranteeing the initial state? The initial state and `SIGSTRUCT` can actually be maliciously modified, so you don't have that guarantee at all. It's the attestation which proves that you're talking with an enclave started from a specific initial state, not signing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-05 07:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 10 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/index.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvSLZpAScwySn7zizJ:-NX9UXjU7lgroQMJF--G:b6onxsz) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, waiting for @donporter 
</blockquote></details>

@donporter ping?


<!-- Sent from Reviewable.io -->

2023-06-05 12:34 UTC, donporter requested changes
> Reviewed 4 of 12 files at r1, 2 of 7 files at r5, 1 of 3 files at r6, 1 of 2 files at r7, 2 of 3 files at r9, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/curated-installation.rst` line 16 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAUSiP3CImjJxBgTQr:-NXAUSiP3CImjJxBgTQs:b-6zllmd) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/curated-installation.rst#L16)):*
> ```reStructuredText
> end-to-end use cases. The interactive script asks users for necessary
> configurations, and provides these inputs to the :doc:`GSC<gsc-installation>`
> tool for the actual transformation. The result is a curated, confidentially
> ```

I think you want 'confidentiality' here.

Assuming there is a wider range of possible security policies, I might remove the modifier "confidentially protected" altogether, since the later clause about specifying security policies covers this anyway and the sentence is already pretty complex.
___
*[`Documentation/index.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvSLZpAScwySn7zizJ:-NXAVBE39G8InVWuKzi_:b-s9sfie) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@donporter ping?
</blockquote></details>

Contractions are discouraged in formal/technical writing.  "that is" would be better.  But this is correct English.
___
*[`Documentation/index.rst` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvYGy645ReoeecKhOA:-NXAVn3ZDrQEnQPtkKjZ:b-c7f97s) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, thanks for the explanations! I'm still not convinced, but at least now I get the idea behind this :)
Tbh for me the biggest improvement is the clearer ToC. I'd assume it's much more used than the index.
</blockquote></details>

FWIW, I approach documentation in two modes: either a total newbie wanting to get a handle on the basic ideas, or just spot checking a detail I mostly already understand.  
___
*[`Documentation/sgx-setup.rst` line 42 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAXi7H2NjVfnMh3bK9:-NXAXi7H2NjVfnMh3bKA:bfquxsi) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/sgx-setup.rst#L42)):*
> ```reStructuredText
> 
> Signing an SGX enclave is a required step in Intel SGX. First, only signed
> enclaves are allowed to be loaded on an SGX platform. Second, the enclave's
> ```

Consider rephrasing in active voice: First, SGX platforms only load signed enclave images.
___
*[`Documentation/sgx-setup.rst` line 43 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAXrQT59IrV3iWI-RU:-NXAXrQT59IrV3iWI-RV:bioxxdl) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/sgx-setup.rst#L43)):*
> ```reStructuredText
> Signing an SGX enclave is a required step in Intel SGX. First, only signed
> enclaves are allowed to be loaded on an SGX platform. Second, the enclave's
> signed structure (so-called SIGSTRUCT) includes a measurement of the enclave
> ```

"so-called" -> "called a"

"so-called" has a connotation that of skepticism.


<!-- Sent from Reviewable.io -->

2023-06-05 12:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: 9 of 12 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @mkow)

___
*[`Documentation/curated-installation.rst` line 16 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAUSiP3CImjJxBgTQr:-NXAZXIb0Cvq8zppoJoL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/curated-installation.rst#L16)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I think you want 'confidentiality' here.

Assuming there is a wider range of possible security policies, I might remove the modifier "confidentially protected" altogether, since the later clause about specifying security policies covers this anyway and the sentence is already pretty complex.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1362#-NVvSLZpAScwySn7zizJ:-NXAZdl2CFCv5_gpOUJz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25bed0c89a579a82584db68da2f8a775aa751189/Documentation/index.rst#L5)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Contractions are discouraged in formal/technical writing.  "that is" would be better.  But this is correct English.
</blockquote></details>

Done.
___
*[`Documentation/sgx-setup.rst` line 42 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAXi7H2NjVfnMh3bK9:-NXAZnhVCX-Q0ul9NTkL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/sgx-setup.rst#L42)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider rephrasing in active voice: First, SGX platforms only load signed enclave images.
</blockquote></details>

Done.
___
*[`Documentation/sgx-setup.rst` line 43 at r12](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXAXrQT59IrV3iWI-RU:-NXAZxPi7ugCSPKIhcnU:brsexp8) ([raw file](https://github.com/gramineproject/gramine/blob/9fa60a05da4a8608c0d60c43b88ad26463a73254/Documentation/sgx-setup.rst#L43)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

"so-called" -> "called a"

"so-called" has a connotation that of skepticism.
</blockquote></details>

Done. Didn't know this, thanks!


<!-- Sent from Reviewable.io -->

2023-06-06 14:06 UTC, donporter approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2023-06-06 14:29 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-07 15:02 UTC, mkow requested changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/sgx-setup.rst` line 14 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2XeZj7muloJNmxQ2d:-NXLJESw3rctWsaeaWl6:b51zw2r) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I think it's the Intel's habit of using "enable" as a synonym for "has"/"exists".
</blockquote></details>

And I really hate it :) It's ambiguous, because in technical context it usually has a different meaning, and also it sounds like a very corporate/marketing term (when used in this meaning). Sounds like something you'd write in a LinkedIn post, not on GitHub.
___
*[`Documentation/sgx-setup.rst` line 41 at r11](https://reviewable.io/reviews/gramineproject/gramine/1362#-NX2Y0bQ-tpQwQ7ioW9H:-NXLM9EU5IX2V6ucygFI:brzbr8e) ([raw file](https://github.com/gramineproject/gramine/blob/438bb063b28bf4699e52a745925e32ad395ae4ac/Documentation/sgx-setup.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I rephrased this paragraph. Unfortunately, it's still too vague, and I don't want to go into details here. The idea of this paragraph is to briefly answer an obvious question: "Why do I need to sign the enclave, what is this key that I'm creating?". Previously we didn't have anything in this section, and now I added at least some explanation that this is indeed a needed thing.

By the way, this SIGSTRUCT story is *very convoluted*. It's always required to start the SGX enclave, though if you don't use SGX sealing and don't use `MRSIGNER`, you don't really need to have a SIGSTRUCT... Especially given that smth similar to SIGSTRUCT (to my knowledge) is not used by any other TEE technology. So explaining it is tough.
</blockquote></details>

Yup. But IMO the description is good now, the argument that it's just required by the hardware is fine. I just don't want to say something which isn't true (that enclave signing is required for security).
___
*[`Documentation/sgx-setup.rst` line 43 at r13](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXLMPqS4UO-7S7-DOYv:-NXLMPqS4UO-7S7-DOYw:b-6k1r5t) ([raw file](https://github.com/gramineproject/gramine/blob/035e582360cd1084ff1caf798ec98d12aee10741/Documentation/sgx-setup.rst#L43)):*
> ```reStructuredText
> Signing an SGX enclave is a required step in Intel SGX. First, SGX platforms
> only load signed enclave images. Second, the enclave's signed structure (called
> a SIGSTRUCT) includes a measurement of the enclave code (called an MRENCLAVE),
> ```

These are proper names I think, so no "a"/"an".



_Suggestion (i):_
```reStructuredText
(called MRENCLAVE)
```



_Suggestion (ii):_
```reStructuredText
SIGSTRUCT
```



_Suggestion (iii):_
```reStructuredText
MRSIGNER
```


<!-- Sent from Reviewable.io -->

2023-06-07 17:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/sgx-setup.rst` line 43 at r13](https://reviewable.io/reviews/gramineproject/gramine/1362#-NXLMPqS4UO-7S7-DOYv:-NXLoYUmBDjqlrK9FPSS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/035e582360cd1084ff1caf798ec98d12aee10741/Documentation/sgx-setup.rst#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These are proper names I think, so no "a"/"an".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-08 01:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-08 03:21 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1362)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-09 00:36 UTC, merged