Drop 18.04, part 2: Use `MAP_FIXED_NOREPLACE` where possible
gramineproject/gramine pull request #1374
Opened 2023-05-26 17:11 UTC by mkow

## Description of the changes

This is a safer version of `MAP_FIXED` which fails instead of overwriting already allocated memory.

## How to test this PR?

Please review carefully, especially please check whether I missed something which could also be changed.

2023-05-26 17:13 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`libos/src/libos_parser.c` line 851 at r1](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWO24Tg63MOyKmYbuO9:-NWO24Tg63MOyKmYbuOA:bl8izcz) ([raw file](https://github.com/gramineproject/gramine/blob/0fb0c18af8aeba957c315d1e5d7e0725d80cdc61/libos/src/libos_parser.c#L851)):*
> ```C
>         buf_puts(buf, "|MAP_FIXED_NOREPLACE");
>         flags &= ~MAP_FIXED_NOREPLACE;
>     }
> ```

This is rather unrelated to the main change, should I split it into a separate commit?


<!-- Sent from Reviewable.io -->

2023-05-27 10:31 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NWRjn508dHaoFge8z3i:bb5wxwl) (no related file):*
Seems that some 20.04 non-SGX pipelines are failing on Jenkins, but I cannot reproduce this on my 20.04.
Both fail on the same PAL tests: `test_pal.py::TC_00_Basic::test_003_printf`, `test_pal.py::TC_00_BasicSet2::test_Pie` and `test_pal.py::TC_20_SingleProcess::test_300_memory`.
TODO: Debug this.

___


<!-- Sent from Reviewable.io -->

2023-05-27 10:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NWRkvct5hkhK0WzjaqL:b-p2cxf7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems that some 20.04 non-SGX pipelines are failing on Jenkins, but I cannot reproduce this on my 20.04.
Both fail on the same PAL tests: `test_pal.py::TC_00_Basic::test_003_printf`, `test_pal.py::TC_00_BasicSet2::test_Pie` and `test_pal.py::TC_20_SingleProcess::test_300_memory`.
TODO: Debug this.
</blockquote></details>

Btw. the tests ran on `slave-rowlf` and `slave-leeroy`.

___


<!-- Sent from Reviewable.io -->

2023-05-27 11:12 UTC, mkow commented
Jenkins, retest Jenkins-Debug-20.04 please (to see if the failure reproduces)

2023-05-27 11:36 UTC, mkow commented
Jenkins, retest Jenkins-Debug-20.04 please (to see if the failure reproduces)

2023-05-27 11:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NWRzQnN8fOKJOhScdfo:b4ufqxl) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Btw. the tests ran on `slave-rowlf` and `slave-leeroy`.
</blockquote></details>

`Jenkins-Debug-20.04` just succeeded on `slave-nigel` twice.

___


<!-- Sent from Reviewable.io -->

2023-05-27 14:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NWSZ6y0BbNWIHaxszQj:b2yv18z) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Jenkins-Debug-20.04` just succeeded on `slave-nigel` twice.
</blockquote></details>

Added an assert, now `slave-rowlf` says:
```
assert failed ../pal/src/host/linux/pal_memory.c:44 res_addr == addr
```

It seems it has a super-old kernel on the host and 20.04 is only inside Docker?

CC: @woju

___


<!-- Sent from Reviewable.io -->

2023-05-29 03:16 UTC, kailun-qin reviewed
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NW_U91-B9onu3ZwS36H:bifuu5o) (no related file):*
> but I cannot reproduce this on my 20.04.

I cannot reproduce it on my 20.04 setup neither.

The changes LGTM. Let's wait a bit and see how it goes w/ this CI failure.

___
___
*[`libos/src/libos_parser.c` line 851 at r1](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWO24Tg63MOyKmYbuO9:-NW_U0QR5Rau0lpVSgE2:bmq7uaf) ([raw file](https://github.com/gramineproject/gramine/blob/0fb0c18af8aeba957c315d1e5d7e0725d80cdc61/libos/src/libos_parser.c#L851)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is rather unrelated to the main change, should I split it into a separate commit?
</blockquote></details>

I'm neutral on this and I'm fine w/ having it here. :)


<!-- Sent from Reviewable.io -->

2023-05-30 07:05 UTC, dimakuv requested changes
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NWfQIZV34XRItPpQEJ4:b5hiv7w) (no related file):*
> It seems it has a super-old kernel on the host and 20.04 is only inside Docker?

Yep, I think that's what happens. The old Linux kernel (e.g. 4.15) ignores unknown-to-it `MAP_FIXED_NOREPLACE` flag and allocates memory wherever it wants.

Please add some startup checking code on this behavior, so that Gramine fails loudly on such old kernels, instead of hitting the assert (and in release mode, Gramine would go crazy and we'll spend a lot of time trying to debug this). I think you can just mmap a random 4KB page twice (once without the `MAP_FIXED_NOREPLACE` flag, and then with `MAP_FIXED_NOREPLACE` flag on the same address, and if the second one doesn't fail with `EEXIST` then the kernel is clearly bad).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfRh6_E10lRa_hRzT0:-NWfRh6_E10lRa_hRzT1:bgcu4r3) (no related file):*
Don't we want to `#error` here:
https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_linux.h#L126-L128

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfS3Zn1tjZRRwCozew:-NWfS3Zn1tjZRRwCozex:b-dwqo5t) (no related file):*
This looks useless now: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_memory.c#L195-L199

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSObu5rqjtbJRRATk:-NWfSObu5rqjtbJRRATl:bq5oxcd) (no related file):*
Why didn't you modify this place: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_files.c#L140

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSlf0AnQiTKvXazoL:-NWfSlf0AnQiTKvXazoM:b-oxjg9m) (no related file):*
What about this one: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux-sgx/host_framework.c#L417

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSwmB5SwXyUkDGZpd:-NWfSwmC-3OQ32r7Iv6b:b-iq302v) (no related file):*
What about this: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/libos/include/linux_abi/memory.h#L13

Aren't we guaranteed after this PR that Gramine is built on a Linux kernel that has `MAP_FIXED_NOREPLACE`? I'm actually not sure if we want to make this assumption, but on the other hand -- who would build Gramine on an older kernel to then run it on a newer kernel...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfT9k66BOOw9UCXAmn:-NWfT9k66BOOw9UCXAmo:bfe1hgy) (no related file):*
I think I checked all places in our Gramine codebase that use `MAP_FIXED`. Many places (or even all places?) inside the LibOS can continue using `MAP_FIXED` internally, so I didn't ask about them (e.g. brk logic).

___
___
*[`libos/src/libos_parser.c` line 851 at r1](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWO24Tg63MOyKmYbuO9:-NWfOYY5CNUr8EQfII6R:b-qtj66u) ([raw file](https://github.com/gramineproject/gramine/blob/0fb0c18af8aeba957c315d1e5d7e0725d80cdc61/libos/src/libos_parser.c#L851)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'm neutral on this and I'm fine w/ having it here. :)
</blockquote></details>

I think it's fine to have it in this PR.
___
*[`pal/src/host/linux/pal_main.c` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfPmOR6_WFU1ICiz5-:-NWfPmOR6_WFU1ICiz50:bv24z1v) ([raw file](https://github.com/gramineproject/gramine/blob/2bb5ecdbc26e7081bfb006ae10721279a23a97ee/pal/src/host/linux/pal_main.c#L116)):*
> ```C
>     int flags = MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE | MAP_FIXED_NOREPLACE;
>     void* addr = (void*)DO_SYSCALL(mmap, (void*)ASAN_SHADOW_START, ASAN_SHADOW_LENGTH, prot, flags,
>                                    /*fd=*/-1, /*offset=*/0);
> ```

We sometimes have `assert(addr = <requested addr>)`. Do you want to add such an assert everywhere in this PR?
___
*[`pal/src/host/linux-sgx/host_main.c` line 579 at r2](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfPTBqEQbePfq-qHVP:-NWfPTBqEQbePfq-qHVQ:b-yr5h7) ([raw file](https://github.com/gramineproject/gramine/blob/2bb5ecdbc26e7081bfb006ae10721279a23a97ee/pal/src/host/linux-sgx/host_main.c#L579)):*
> ```C
>         MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED_NOREPLACE,
>         -1,
>         0);
> ```

This looks pretty ugly. I would introduce a helper variable `int flags` and use it.


<!-- Sent from Reviewable.io -->

2023-06-05 15:32 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NXBAmQn2bVujS3ElKyK:buda2x9) (no related file):*
> It seems it has a super-old kernel on the host and 20.04 is only inside Docker?

Yes, rowlf has Ubuntu 18.04 with kernel `4.15.0-210-generic`. Will update in July, when we'll be moving CI.

___


<!-- Sent from Reviewable.io -->

2023-06-09 00:03 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NXSSTd90S0yi-zuLFiO:b-uqxoy1) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> It seems it has a super-old kernel on the host and 20.04 is only inside Docker?

Yes, rowlf has Ubuntu 18.04 with kernel `4.15.0-210-generic`. Will update in July, when we'll be moving CI.
</blockquote></details>

Can we disable `rowlf` until then?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfRh6_E10lRa_hRzT0:-NXSS_-KD7CZuvYteOvQ:b-cjfh50) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to `#error` here:
https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_linux.h#L126-L128
</blockquote></details>

No, why? This file is unrelated to this PR.

___


<!-- Sent from Reviewable.io -->

2023-06-09 03:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfRh6_E10lRa_hRzT0:-NXT4rbX1ZRDvQpUffa-:bsfguzh) (no related file):*
> No, why? This file is unrelated to this PR.

+1 (if it's due to the reason below, I think we can discuss and make it in a separate PR)

> Aren't we guaranteed after this PR that Gramine is built on a Linux kernel that has `MAP_FIXED_NOREPLACE`? I'm actually not sure if we want to make this assumption, but on the other hand -- who would build Gramine on an older kernel to then run it on a newer kernel...

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSwmB5SwXyUkDGZpd:-NXT6ITJ6nBQRJZwUvxO:bfnmnvk) (no related file):*
> who would build Gramine on an older kernel to then run it on a newer kernel

hmm.. I'm not sure but may be possible? People can have different environment for CI/CD (building) and deployment where building can simply reuse some deprecated machines with legacy setups (like our `rowlf`).

I think it's no harm to keep it and btw we have other similar places (macros not defined in older kernels) in Gramine.

___


<!-- Sent from Reviewable.io -->

2023-06-09 09:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSwmB5SwXyUkDGZpd:-NXUOw8ECJdVJbz5rEOw:bi38f16) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> who would build Gramine on an older kernel to then run it on a newer kernel

hmm.. I'm not sure but may be possible? People can have different environment for CI/CD (building) and deployment where building can simply reuse some deprecated machines with legacy setups (like our `rowlf`).

I think it's no harm to keep it and btw we have other similar places (macros not defined in older kernels) in Gramine.
</blockquote></details>

Ok, I'm unblocking.

___


<!-- Sent from Reviewable.io -->

2023-06-12 09:54 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NXj0Y9l3X9Qaz-v5Eb9:b-di989c) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we disable `rowlf` until then?
</blockquote></details>

Done. Plz ping me if you find other unsuitable nodes, I'll disconnect them, I don't have time to check or fix them now.

___


<!-- Sent from Reviewable.io -->

2023-06-12 11:11 UTC, mkow commented
Jenkins, retest this please

2023-08-25 13:46 UTC, mkow commented
Jenkins, retest this please (checking if Jenkins is fine now)

2023-08-26 22:57 UTC, mkow reviewed
I rebased the PR as it was missing some base commits to work in CI (and it's rather small, so it shouldn't be disruptive).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374#-:-Nco232TE4NYSnEWw02C:b-b7sy3m)* status: 3 of 7 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfS3Zn1tjZRRwCozew:-Nce8_Wq9pn8njIaCAiJ:b-ik5a2d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks useless now: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_memory.c#L195-L199
</blockquote></details>

Yeah, I wasn't sure what to do about such places, theoretically it's now safe, but will be hard to debug if someone actually uses an old kernel? Maybe it makes sense to leave the safeguards for some time?

___


<!-- Sent from Reviewable.io -->

2023-08-27 15:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 3 of 7 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWRjn508dHaoFge8z3h:-NcrYjhw758WHW2dsTBY:b-beemmk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. Plz ping me if you find other unsuitable nodes, I'll disconnect them, I don't have time to check or fix them now.
</blockquote></details>

@woju: another two with outdated kernel: slave-uncledeadly and slave-leeroy. Please either update or temporarily take out of CI.

___


<!-- Sent from Reviewable.io -->

2023-08-28 04:48 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfS3Zn1tjZRRwCozew:-NcuSw8E0Cf1kpPYX__d:b-iw047q) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I wasn't sure what to do about such places, theoretically it's now safe, but will be hard to debug if someone actually uses an old kernel? Maybe it makes sense to leave the safeguards for some time?
</blockquote></details>

Ok, but maybe then add a comment why this code is kept?

___


<!-- Sent from Reviewable.io -->

2023-09-11 11:55 UTC, mkow commented
Jenkins, retest this please (woju unplugged the old CI nodes)

2023-09-13 01:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 3 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfT9k66BOOw9UCXAmn:-NeBC9gdAFr-mpIgJgl-:bj6d4cp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think I checked all places in our Gramine codebase that use `MAP_FIXED`. Many places (or even all places?) inside the LibOS can continue using `MAP_FIXED` internally, so I didn't ask about them (e.g. brk logic).
</blockquote></details>

That's a harder case, depends what Linux does there (whether it actually uses `MAP_FIXED_NOREPLACE` when expanding brk). But I'd leave it for a separate PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSwmB5SwXyUkDGZpd:-NeBD1rmEqjwSWyaP7-S:b-2ei75c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'm unblocking.
</blockquote></details>

This will be fixed by my separate work (on importing Linux defs).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSlf0AnQiTKvXazoL:-NeBDS8h3OPjxlaEUcK1:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this one: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux-sgx/host_framework.c#L417
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfSObu5rqjtbJRRATk:-NeBDoWc3QKH6VTFQfIL:b-zcxi79) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why didn't you modify this place: https://github.com/gramineproject/gramine/blob/c9135adc981eff5e80b846a74fe2d8dc83bde8ab/pal/src/host/linux/pal_files.c#L140
</blockquote></details>

Done, somehow missed this while grepping.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfS3Zn1tjZRRwCozew:-NeBDuK47kYQFPxNcQvL:b-860m69) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, but maybe then add a comment why this code is kept?
</blockquote></details>

Changed to an assert, like in other places. Should be a good middle-ground IMO.

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeBBiL_DXCQ917CjKBw):*
I think I should add [PAL] here, the only LibOS change is that slightly offtopic syscall parser fixup.
___
*[`pal/src/host/linux/pal_main.c` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfPmOR6_WFU1ICiz5-:-NeAwDuj2XSmmD3O5fFi:bsq614u) ([raw file](https://github.com/gramineproject/gramine/blob/2bb5ecdbc26e7081bfb006ae10721279a23a97ee/pal/src/host/linux/pal_main.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We sometimes have `assert(addr = <requested addr>)`. Do you want to add such an assert everywhere in this PR?
</blockquote></details>

Why not, done. But here we cannot assert, it's too early in the initialization.
___
*[`pal/src/host/linux-sgx/host_main.c` line 579 at r2](https://reviewable.io/reviews/gramineproject/gramine/1374#-NWfPTBqEQbePfq-qHVP:-NeAvvjt9NgwoPBdBGIk:b6fufgv) ([raw file](https://github.com/gramineproject/gramine/blob/2bb5ecdbc26e7081bfb006ae10721279a23a97ee/pal/src/host/linux-sgx/host_main.c#L579)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks pretty ugly. I would introduce a helper variable `int flags` and use it.
</blockquote></details>

What about now? I don't like that way with storing just one argument in a variable too much...


<!-- Sent from Reviewable.io -->

2023-09-13 12:47 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeD_8j5CQRELEN32Svb:b-nqr97d) (no related file):*
Several pipelines failed. The PR itself looks good to me.

___


<!-- Sent from Reviewable.io -->

2023-09-14 14:04 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeIzdmoCsLsJLgTkz0s:b-ojt7xi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Several pipelines failed. The PR itself looks good to me.
</blockquote></details>

Missing cast in an assert, weird that it worked on 20.04 SGX pipelines. Probably older GCC?

___


<!-- Sent from Reviewable.io -->

2023-09-14 17:53 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeJon9Z3X8B-x-6fxW7:b-xdzekt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Missing cast in an assert, weird that it worked on 20.04 SGX pipelines. Probably older GCC?
</blockquote></details>

Still some pipelines failed...

___


<!-- Sent from Reviewable.io -->

2023-09-14 20:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeKLaWtCim_e_HIWipY:bhocrlj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still some pipelines failed...
</blockquote></details>

I have no idea what's wrong with `linux-sgx-vm-gcc-release`, seems unrelated to this PR?

```
**16:06:24**  + cd ../gramine-device-testing-module
**16:06:24**  + make -j8
**16:06:24**  make -C /lib/modules/6.1.0-11-amd64/build M=$PWD
**16:06:24**  make\[1\]: Entering directory '/usr/src/linux-headers-6.1.0-11-amd64'
**16:06:24**  /usr/src/linux-headers-6.1.0-11-common/Makefile:1108: /usr/src/linux-headers-6.1.0-11-common/scripts/Makefile.debug: No such file or directory
**16:06:24**  make\[1\]: \*\*\* No rule to make target '/usr/src/linux-headers-6.1.0-11-common/scripts/Makefile.debug'.  Stop.
**16:06:24**  make\[1\]: Leaving directory '/usr/src/linux-headers-6.1.0-11-amd64'
**16:06:24**  make: \*\*\* \[Makefile:5: default\] Error 2
```

The EDMM pipeline failed with:

```
**17:06:11**  \[0.003\] Gramine is starting. Parsing TOML manifest file, this may take some time...
**17:06:11**  \[0.007\] error: Cannot map enclave pages: File exists (EEXIST)
**17:06:11**  \[0.007\] error: Adding pages (manifest) to enclave failed: File exists (EEXIST)
**17:06:11**  \[0.007\] error: load\_enclave() failed with error: File exists (EEXIST)
```

on all tests (on `slave-whatnots`).

I guess this is caused by a different driver there, which doesn't accept `MAP_FIXED_NOREPLACE`? Or maybe it's also running an old kernel? CC: @woju

___


<!-- Sent from Reviewable.io -->

2023-09-14 22:29 UTC, woju commented
Jenkins, retest Jenkins-SGX-EDMM please

2023-09-14 22:38 UTC, woju commented
Jenkins, retest Jenkins-SGX-EDMM please

2023-09-14 22:53 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeKsNjCAwrSXEgU6uh3:b-81819w) (no related file):*
```
error: load\_enclave() failed with error: File exists (EEXIST)
```

This looks like legit error. Quoting from https://manpages.debian.org/bookworm/manpages-dev/mmap.2.en.html#MAP_FIXED_NOREPLACE:

> 
> MAP_FIXED_NOREPLACE (since Linux 4.17)
>    This flag provides behavior that is similar to MAP_FIXED with respect to the addr enforcement, but differs in that MAP_FIXED_NOREPLACE never clobbers a preexisting mapped range. If the requested range would collide with an existing mapping, then this call fails with the error EEXIST. This flag can therefore be used as a way to atomically (with respect to other threads) attempt to map an address range: one thread will succeed; all others will report failure.

And IMHO this happens, you get genuine EEXIST as documented. IDK why exactly this happens, but I see no reason to doubt behaviour of the underlying system.

WRT `/usr/src/linux-headers-6.1.0-11-common/scripts/Makefile.debug: No such file or directory` I think @dimakuv has fixed this error in some other PR, it was related to some mounting of paths inside docker, and the usage of symlinks by distro. I don't recall specifics, @dimakuv can you fill in?

___


<!-- Sent from Reviewable.io -->

2023-09-15 06:52 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-NeMatlWE110I0c6U_B0:b7yh3xk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```
error: load\_enclave() failed with error: File exists (EEXIST)
```

This looks like legit error. Quoting from https://manpages.debian.org/bookworm/manpages-dev/mmap.2.en.html#MAP_FIXED_NOREPLACE:

> 
> MAP_FIXED_NOREPLACE (since Linux 4.17)
>    This flag provides behavior that is similar to MAP_FIXED with respect to the addr enforcement, but differs in that MAP_FIXED_NOREPLACE never clobbers a preexisting mapped range. If the requested range would collide with an existing mapping, then this call fails with the error EEXIST. This flag can therefore be used as a way to atomically (with respect to other threads) attempt to map an address range: one thread will succeed; all others will report failure.

And IMHO this happens, you get genuine EEXIST as documented. IDK why exactly this happens, but I see no reason to doubt behaviour of the underlying system.

WRT `/usr/src/linux-headers-6.1.0-11-common/scripts/Makefile.debug: No such file or directory` I think @dimakuv has fixed this error in some other PR, it was related to some mounting of paths inside docker, and the usage of symlinks by distro. I don't recall specifics, @dimakuv can you fill in?
</blockquote></details>

Yes, the `linux-sgx-vm-gcc-release` pipeline is not yet fixed in this PR (I mean, the PR doesn't have the fixes that went into master branch, because this PR is too old). So don't pay attention to that pipeline.

But the EDMM pipeline seems to fail for real. Please analyze.

___


<!-- Sent from Reviewable.io -->

2023-10-18 00:11 UTC, mkow commented
Jenkins, retest Jenkins-SGX-EDMM please

2023-10-19 14:29 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: 4 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeD_8j5CQRELEN32Sva:-Nh7KVbc1n-70HhHNrv8:bkgx7f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the `linux-sgx-vm-gcc-release` pipeline is not yet fixed in this PR (I mean, the PR doesn't have the fixes that went into master branch, because this PR is too old). So don't pay attention to that pipeline.

But the EDMM pipeline seems to fail for real. Please analyze.
</blockquote></details>

Done. From what I see, in that case we were actually overwriting a driver mapping, which is intended. Some weird way of allocating enclave memory + SGX driver interaction.

___


<!-- Sent from Reviewable.io -->

2023-10-20 02:28 UTC, kailun-qin approved these changes
> Reviewed 2 of 5 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 407 at r6](https://reviewable.io/reviews/gramineproject/gramine/1374#-Nh9shNF7rWUhLBuNJnP:-Nh9shNF7rWUhLBuNJnQ:b-56hw5d) ([raw file](https://github.com/gramineproject/gramine/blob/23cdccc4d2ff66e65b50f7af785003967e708fdb/pal/src/host/linux-sgx/host_framework.c#L407)):*
> ```C
> 
>     /* ask Intel SGX driver to actually mmap the added enclave pages */
>     uint64_t mapped = DO_SYSCALL(mmap, addr, size, prot, MAP_FIXED | MAP_SHARED, g_isgx_device, 0);
> ```

So this is the place which caused the previous failure on EDMM pipeline? ("in that case we were actually overwriting a driver mapping, which is intended. Some weird way of allocating enclave memory + SGX driver interaction.")

Should we add some notes here?



_Code quote:_
```C
MAP_FIXED
```


<!-- Sent from Reviewable.io -->

2023-10-20 06:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1374#-NeBBiL_DXCQ917CjKBw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I should add [PAL] here, the only LibOS change is that slightly offtopic syscall parser fixup.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_framework.c` line 407 at r6](https://reviewable.io/reviews/gramineproject/gramine/1374#-Nh9shNF7rWUhLBuNJnP:-NhArsCP0_poGKcVExO0:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/23cdccc4d2ff66e65b50f7af785003967e708fdb/pal/src/host/linux-sgx/host_framework.c#L407)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

So this is the place which caused the previous failure on EDMM pipeline? ("in that case we were actually overwriting a driver mapping, which is intended. Some weird way of allocating enclave memory + SGX driver interaction.")

Should we add some notes here?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-20 07:01 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-10-20 09:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1374)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`pal/src/host/linux-sgx/host_framework.c` line 407 at r6](https://reviewable.io/reviews/gramineproject/gramine/1374#-Nh9shNF7rWUhLBuNJnP:-NhBTFXk0306GftssYYv:byrsxez) ([raw file](https://github.com/gramineproject/gramine/blob/23cdccc4d2ff66e65b50f7af785003967e708fdb/pal/src/host/linux-sgx/host_framework.c#L407)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

@kailun-qin: Yes


<!-- Sent from Reviewable.io -->

2023-10-20 10:44 UTC, merged