[python] Remove commented out lines from template before passing to render with jinja
gramineproject/gramine pull request #1381
Opened 2023-06-02 04:48 UTC by svenkata9

## Description of the changes 
If you have a manifest template that has lines that require defines/variables to be passed as arguments to gramine-manifest, but commented out, gramine-manifest command fails during jinja render because the variables are applied even for the commented-out lines first before passing on to toml.

For example, if you don't have -Dpythondistpath=... as part of gramine-manifest command, having the following lines in the manifest template will make gramine-manifest fail:

# fs.mount.pydistpath.type = "chroot"
    # fs.mount.pydistpath.path = "{{ pythondistpath }}"
 # fs.mount.pydistpath.uri = "file:{{ pythondistpath }}"

This PR fixes it by removing the commented out lines before passing to render with jinja

 Fixes #1380 

## How to test this PR?

2023-06-02 06:31 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1381)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[`python/graminelibos/manifest.py` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/1381#-NWumUW93evzMjmUpku9:-NWumUW93evzMjmUpkuA:bx5wq52) ([raw file](https://github.com/gramineproject/gramine/blob/0a13b0f3fd857b6bf7d3283369842ddb27df63b7/python/graminelibos/manifest.py#L150)):*
> ```Python
>         template = ''
>         for line in in_template.splitlines():
>             if line.lstrip().startswith('#'):
> ```

This won't work in all cases.

1. What if you have a case like this:
```toml
fs.mount.pydistpath.path = "dummy"  # previously it was "{{ pythondistpath }}"
```

2. What if you have a case like this:
```toml
some.toml.string = """
# this is part of the string, we want to preserve it
"""
```

In the first case, you miss to remove the comment, and you have the problem of #1380 again. In the second case, you remove a non-comment (because your trivial Python code thinks it's a comment).

See spec: https://toml.io/en/v1.0.0#comment

Please also see my comment here: https://github.com/gramineproject/gramine/issues/1380#issuecomment-1573220375


<!-- Sent from Reviewable.io -->

2023-06-02 06:36 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1381)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`python/graminelibos/manifest.py` line 150 at r1](https://reviewable.io/reviews/gramineproject/gramine/1381#-NWumUW93evzMjmUpku9:-NWuoB6T5HIOaHtjN1hf:b-ciyhm7) ([raw file](https://github.com/gramineproject/gramine/blob/0a13b0f3fd857b6bf7d3283369842ddb27df63b7/python/graminelibos/manifest.py#L150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This won't work in all cases.

1. What if you have a case like this:
```toml
fs.mount.pydistpath.path = "dummy"  # previously it was "{{ pythondistpath }}"
```

2. What if you have a case like this:
```toml
some.toml.string = """
# this is part of the string, we want to preserve it
"""
```

In the first case, you miss to remove the comment, and you have the problem of #1380 again. In the second case, you remove a non-comment (because your trivial Python code thinks it's a comment).

See spec: https://toml.io/en/v1.0.0#comment

Please also see my comment here: https://github.com/gramineproject/gramine/issues/1380#issuecomment-1573220375
</blockquote></details>

Right, these are valid tricky cases as well.


<!-- Sent from Reviewable.io -->

2023-06-04 01:32 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1381)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1381#-NX30XFREdGyOAuoFWfH:-NX30XFREdGyOAuoFWfI:bmnryaf) (no related file):*
This is a terrible hack, there's no way we'll be merging it. You are trying to somehow mend a user syntax mistake when writing manifest, but it's just not possible without breaking legit use-cases (and it also makes our manifests syntax not being actually in Jinja format, but some weird custom language which doesn't make sense).

___


<!-- Sent from Reviewable.io -->

2023-06-05 06:48 UTC, dimakuv commented
Closing this PR for now. I suggest to create another PR if you'll come up with a clean way to overcome this.

2023-06-05 06:48 UTC, closed without merging