[LibOS] regression: fix GDB tests
gramineproject/gramine pull request #1395
Opened 2023-06-15 12:49 UTC by dimakuv

## Description of the changes 

GDB tests expected `_start()` function in the backtrace. However, it depends on the GDB version and on the setting `backtrace past-main off|on`. For simplicity, this commit disables past-main traces. As a side effect, this also fixes Musl traces because Musl tends to have `??` traces when past-main is on.

I found this inconsistent behavior on Alpine 3.18.0. I couldn't find any discussions on the internet about it, so I just fixed as theoretically should be correct.

Check my experiment that proves that `past-main` behavior seems to be ignored on e.g. Ubuntu/GDB9 and honored on e.g. Alpine/GDB13:
- On Alpine 3.18.0:
```
$ gdb --version
GNU gdb (GDB) 13.2

...

(gdb) bt -past-main on
#0  main (argc=1, argv=0x615d388a2f08) at ../libos/test/regression/helloworld.c:4
#1  0x0000615d387a77bb in libc_start_main_stage2 (main=0x40114d <main>, argc=1, argv=0x615d388a2f08)
    at ../src/env/__libc_start_main.c:95
#2  0x0000615d387a776e in __libc_start_main (main=0x40114d <main>, argc=1, argv=0x615d388a2f08, init_dummy=0x401000 <_init>,
    fini_dummy=0x40116d <_fini>, ldso_dummy=0x0) at ../src/env/__libc_start_main.c:86
#3  0x0000000000401046 in _start ()
#4  0x0000000000000001 in ?? ()
#5  0x0000615d388a2ff5 in ?? ()
#6  0x0000000000000000 in ?? ()

(gdb) bt -past-main off
#0  main (argc=1, argv=0x615d388a2f08) at ../libos/test/regression/helloworld.c:4
```
- On Ubuntu 20.04:
```
$ gdb --version
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

...

(gdb) bt -past-main on
#0  main (argc=28897, argv=0x0) at ../libos/test/regression/helloworld.c:3
#1  0x000070e18a49d5bd in __libc_start_call_main (main=main@entry=0x401136 <main>, argc=argc@entry=1,
    argv=argv@entry=0x70e18a6c4ee8) at ../sysdeps/nptl/libc_start_call_main.h:58
#2  0x000070e18a49d680 in __libc_start_main_impl (main=0x401136 <main>, argc=1, argv=0x70e18a6c4ee8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x70e18a6c4ed8) at ../csu/libc-start.c:381
#3  0x000000000040107e in _start ()

(gdb) bt -past-main off
#0  main (argc=28897, argv=0x0) at ../libos/test/regression/helloworld.c:3
#1  0x000070e18a49d5bd in __libc_start_call_main (main=main@entry=0x401136 <main>, argc=argc@entry=1,
    argv=argv@entry=0x70e18a6c4ee8) at ../sysdeps/nptl/libc_start_call_main.h:58
#2  0x000070e18a49d680 in __libc_start_main_impl (main=0x401136 <main>, argc=1, argv=0x70e18a6c4ee8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x70e18a6c4ed8) at ../csu/libc-start.c:381
#3  0x000000000040107e in _start ()
```

References:
- https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html
- https://stackoverflow.com/questions/5461731/how-to-backtrace-how-mains-called-with-gdb
- https://bugzilla.redhat.com/show_bug.cgi?id=1461575

## How to test this PR? 

CI is enough.

2023-06-16 01:40 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/test_libos.py` line 1252 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-NY0prBMAnUnuwhhhcbX:-NY0prBMAnUnuwhhhcbY:bsv4e9g) ([raw file](https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/libos/test/regression/test_libos.py#L1252)):*
> ```Python
>         self.assertIn('debug.c', backtrace_1)
>         if not USES_MUSL:
>             self.assertNotIn('??', backtrace_1)
> ```

Sorry I don't understand why is this change -- we remove the check on `??` at all?



_Code quote:_
```Python
        if not USES_MUSL:
            self.assertNotIn('??', backtrace_1)
```


<!-- Sent from Reviewable.io -->

2023-06-16 06:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/test/regression/test_libos.py` line 1252 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-NY0prBMAnUnuwhhhcbX:-NY1zSyT8TGvN22IuPLY:bfcs79) ([raw file](https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/libos/test/regression/test_libos.py#L1252)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry I don't understand why is this change -- we remove the check on `??` at all?
</blockquote></details>

This `??` still appears on Ubuntu/GDB9 + Musl. This seems like a bug in GDB9.

I didn't want to have a check on what basically a bug in GDB. GDB13 (which I have on Alpine) doesn't exhibit this behavior, so we may want to re-add this check (`self.assertNotIn('??', backtrace_1)`) when we common GDB versions don't have the bug.


<!-- Sent from Reviewable.io -->

2023-06-16 09:40 UTC, dimakuv commented
Jenkins, test this please (we had some problems with Docs pipeline, seems to be fixed now)

2023-06-16 12:48 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-20.04-apps please (internet glitch: `ias_send_quote_get_report_raw: Failed to send request to IAS and receive its response`)

2023-07-20 23:45 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/test/regression/test_libos.py` line 1252 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-NY0prBMAnUnuwhhhcbX:-N_pe8AkB03fjp_3-7Mp:b-e2ax0) ([raw file](https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/libos/test/regression/test_libos.py#L1252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `??` still appears on Ubuntu/GDB9 + Musl. This seems like a bug in GDB9.

I didn't want to have a check on what basically a bug in GDB. GDB13 (which I have on Alpine) doesn't exhibit this behavior, so we may want to re-add this check (`self.assertNotIn('??', backtrace_1)`) when we common GDB versions don't have the bug.
</blockquote></details>

OK, fair enough. Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2023-10-10 15:53 UTC, stefanberger reviewed
Fixes the issue on Ubuntu 21.10 for me. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395#-:-NgPHUZrCKIJvnGQRRkv:b-qhohcf)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-10-18 00:05 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/debug.gdb` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-Nh-5NVW4Pl7WxTppF2u:-Nh-5NVW4Pl7WxTppF2v:b9ligax) ([raw file](https://github.com/gramineproject/gramine/blob/a73eee9c31f381f2658ceb0421d0ba4e5e0654f5/libos/test/regression/debug.gdb#L3)):*
> ```GDB
> set breakpoint pending on
> set pagination off
> set backtrace past-main off
> ```

Why not turning it `on`? The log you pasted indicates that this would fix the problem on Alpine?


<!-- Sent from Reviewable.io -->

2023-10-18 06:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`libos/test/regression/debug.gdb` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-Nh-5NVW4Pl7WxTppF2u:-Nh0Vv98-uvlh2QRydYN:bs7bx8t) ([raw file](https://github.com/gramineproject/gramine/blob/a73eee9c31f381f2658ceb0421d0ba4e5e0654f5/libos/test/regression/debug.gdb#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not turning it `on`? The log you pasted indicates that this would fix the problem on Alpine?
</blockquote></details>

Because I also wanted to removed the `??` traces in Musl.

Technically, a normal trace should **never** have `??` frames (if everything was built in debug mode, with debug symbols). So this `??` in Musl can be considered a bug in Musl/GDB (not sure which one).

But if you think we should keep this `??` strangeness, then I can put an explicit `set backtrace past-main on` and revert the other changes in this PR.

But also, what's the point in verifying the `_start()` frame? Isn't it an internal detail of the libc library?


<!-- Sent from Reviewable.io -->

2023-10-19 23:47 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/debug.gdb` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-Nh-5NVW4Pl7WxTppF2u:-Nh9JpUuC3JBa_O72qmI:bcr1ugf) ([raw file](https://github.com/gramineproject/gramine/blob/a73eee9c31f381f2658ceb0421d0ba4e5e0654f5/libos/test/regression/debug.gdb#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because I also wanted to removed the `??` traces in Musl.

Technically, a normal trace should **never** have `??` frames (if everything was built in debug mode, with debug symbols). So this `??` in Musl can be considered a bug in Musl/GDB (not sure which one).

But if you think we should keep this `??` strangeness, then I can put an explicit `set backtrace past-main on` and revert the other changes in this PR.

But also, what's the point in verifying the `_start()` frame? Isn't it an internal detail of the libc library?
</blockquote></details>

I'd rather keep it, to have more frames checked on non-musl configs. I don't like weakening a test because something doesn't work on musl :)


<!-- Sent from Reviewable.io -->

2023-10-20 08:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1395#-NhB361L3zFrC61LuMUC:-NhB361L3zFrC61LuMUD:bsjtb24) (no related file):*
I rebased this PR because it got very stale, and testing was (especially on Alpine) was a pain otherwise.

___
___
*[`libos/test/regression/debug.gdb` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1395#-Nh-5NVW4Pl7WxTppF2u:-NhB2so_573ZJoVktD-o:b-u2vc8s) ([raw file](https://github.com/gramineproject/gramine/blob/a73eee9c31f381f2658ceb0421d0ba4e5e0654f5/libos/test/regression/debug.gdb#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather keep it, to have more frames checked on non-musl configs. I don't like weakening a test because something doesn't work on musl :)
</blockquote></details>

Done.

Tested on Ubuntu 20.04, 22.04 and Alpine 3.18 (we should seriously fix the `tests` thingy in Alpine, I reverted to hacking Meson).

Example in Alpine 3.18, without this PR and with this PR:
```
# GRAMINE_MUSL=1 gramine-test pytest -v -k test_000_gdb_backtrace
FAILED test_libos.py::TC_50_GDB::test_000_gdb_backtrace - AssertionError: ' _start ()' not found in '#0  func () at debug.c:4\n#1  0x000031389e70f1e3 in main () at debug.c:11'


# GRAMINE_MUSL=1 gramine-test pytest -v -k test_000_gdb_backtrace
test_libos.py::TC_50_GDB::test_000_gdb_backtrace PASSED 
```


<!-- Sent from Reviewable.io -->

2023-10-20 09:48 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-20 12:17 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-20 14:24 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-20 23:35 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1395)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-22 22:11 UTC, merged