[PAL/Linux-SGX] Remove misleading print of `isvprodid` and `isvsvn`
gramineproject/gramine pull request #1396
Opened 2023-06-15 14:55 UTC by dimakuv

## Description of the changes 

At ECREATE time, `isvprodid` and `isvsvn` (and many other fields) are set to zero in the SECS page. These fields will be copied from SIGSTRUCT at EINIT time. So it's only misleading to print these fields' values at ECREATE time.

As a side effort, this commit cleans up `sgx_arch.h` header.

See Intel SDM documentation for reference. Or check these carefully:
- https://www.felixcloutier.com/x86/ecreate
- https://www.felixcloutier.com/x86/einit

## How to test this PR? 

N/A. This was detected by a customer who was confused why the fields showed `0` values in Gramine with debug prints.

2023-06-15 14:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NXzYhHZCARnoGKrvuQ_:-NXzYhH_59UaQsveGaor:b-v90mre) ([raw file](https://github.com/gramineproject/gramine/blob/8882c8adf60024780b3c2e7770cffc6bfec96917/pal/src/host/linux-sgx/sgx_arch.h#L129)):*
> ```objc
> 
> /* FIXME: SECS struct must also contain fields ISVEXTPRODID and ISVFAMILYID but they are not
>  *        described in Intel SDM (Vol. 3, Section 34.7, Table 34-2) which must be a bug */
> ```

FYI: I asked Intel SGX experts about this, awaiting their reply.


<!-- Sent from Reviewable.io -->

2023-06-16 02:20 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NY1-6bL27Da7UC8FzYj:-NY1-6bL27Da7UC8FzYk:bjnxk1s) ([raw file](https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/pal/src/host/linux-sgx/host_framework.c#L231)):*
> ```C
>     log_debug("    attr.xfrm:      0x%016lx", secs->attributes.xfrm);
>     log_debug("    ssa_frame_size: %d",       secs->ssa_frame_size);
>     log_debug("    isv_prod_id:    0x%08x",   secs->isv_prod_id);
> ```

Should we log them elsewhere, like in EINIT?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NXzYhHZCARnoGKrvuQ_:-NY0zQ8l25GMIuzGFrmM:b-lucb9g) ([raw file](https://github.com/gramineproject/gramine/blob/8882c8adf60024780b3c2e7770cffc6bfec96917/pal/src/host/linux-sgx/sgx_arch.h#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I asked Intel SGX experts about this, awaiting their reply.
</blockquote></details>

What do you mean by `not described`? Isn't it mentioned in the `reserved4[3834]`?
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NY0zryJBeCM7XpEnihi:-NY0zryJBeCM7XpEnihj:b-v6k874) ([raw file](https://github.com/gramineproject/gramine/blob/8882c8adf60024780b3c2e7770cffc6bfec96917/pal/src/host/linux-sgx/sgx_arch.h#L129)):*
> ```objc
> 
> /* FIXME: SECS struct must also contain fields ISVEXTPRODID and ISVFAMILYID but they are not
>  *        described in Intel SDM (Vol. 3, Section 34.7, Table 34-2) which must be a bug */
> ```

Pls add an SDM version to it, since the latest (March 2023) gives `Table 35-2`.



_Code quote:_
```objc
Intel SDM (Vol. 3, Section 34.7, Table 34-2)
```


<!-- Sent from Reviewable.io -->

2023-06-16 07:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NY1-6bL27Da7UC8FzYj:-NY22GyW4TKOJB1WRxF9:bl25q43) ([raw file](https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/pal/src/host/linux-sgx/host_framework.c#L231)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we log them elsewhere, like in EINIT?
</blockquote></details>

Done. This was also requested by a customer.
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NXzYhHZCARnoGKrvuQ_:-NY20lGYAEW9cctXlitJ:bjdx1sc) ([raw file](https://github.com/gramineproject/gramine/blob/8882c8adf60024780b3c2e7770cffc6bfec96917/pal/src/host/linux-sgx/sgx_arch.h#L129)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What do you mean by `not described`? Isn't it mentioned in the `reserved4[3834]`?
</blockquote></details>

Done. My bad, I was using the old Intel SDM.
___
*[`pal/src/host/linux-sgx/sgx_arch.h` line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/1396#-NY0zryJBeCM7XpEnihi:-NY20nZKDLxKIvB1Gsa7:b-l41f6f) ([raw file](https://github.com/gramineproject/gramine/blob/8882c8adf60024780b3c2e7770cffc6bfec96917/pal/src/host/linux-sgx/sgx_arch.h#L129)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls add an SDM version to it, since the latest (March 2023) gives `Table 35-2`.
</blockquote></details>

Yes, my bad, I was using the old Intel SDM.


<!-- Sent from Reviewable.io -->

2023-06-16 07:39 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-11 01:33 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1396#-N_-ZtJl5neXrVA--FdZ):*
> Not from `EINITTOKEN`?

It looks not.

From https://www.felixcloutier.com/x86/einit, the step 9 of `EINIT` is described as `Commits SECS.MRENCLAVE, and sets SECS.MRSIGNER, SECS.ISVSVN, and SECS.ISVPRODID based on SIGSTRUCT`. Also from the operation flow of `EINIT`, it has `TMP_SIG[14463:0] := DS:RBX[14463:0];` (RBX -- `SIGSTRUCT`), then `DS:RCX.ISVPRODID := TMP_SIG.ISVPRODID;` and `DS:RCX.ISVSVN := TMP_SIG.ISVSVN;` (RCX -- `SECS`).


<!-- Sent from Reviewable.io -->

2023-07-11 06:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1396#-N_-ZtJl5neXrVA--FdZ):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Not from `EINITTOKEN`?

It looks not.

From https://www.felixcloutier.com/x86/einit, the step 9 of `EINIT` is described as `Commits SECS.MRENCLAVE, and sets SECS.MRSIGNER, SECS.ISVSVN, and SECS.ISVPRODID based on SIGSTRUCT`. Also from the operation flow of `EINIT`, it has `TMP_SIG[14463:0] := DS:RBX[14463:0];` (RBX -- `SIGSTRUCT`), then `DS:RCX.ISVPRODID := TMP_SIG.ISVPRODID;` and `DS:RCX.ISVSVN := TMP_SIG.ISVSVN;` (RCX -- `SECS`).
</blockquote></details>

As Kailun answered -- no, not from EINITTOKEN.


<!-- Sent from Reviewable.io -->

2023-07-21 15:18 UTC, donporter approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-28 22:45 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1396#-N_-ZtJl5neXrVA--FdZ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As Kailun answered -- no, not from EINITTOKEN.
</blockquote></details>

Yeah, that makes sense, sorry, I'm not sure why I got confused, must have misread something :)


<!-- Sent from Reviewable.io -->

2023-08-30 00:14 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-30 04:05 UTC, merged