[LibOS] Ignore O_TRUNC flag for FIFO files
gramineproject/gramine pull request #1401
Opened 2023-06-19 05:21 UTC by sahason

## Description of the changes 

During enablement of mxnet-model-server in gramine one issue is observed that for FIFO files opening it with `O_TRUNC` returns `EINVAL`. In the native `O_TRUNC` flag for FIFO files is ignored. See `man 2 open`. This PR also emulates the same behaviour for gramine.

## How to test this PR? 

Modify this line https://github.com/gramineproject/gramine/blob/702ac42f81452b288b66b00308763584c3d115d3/libos/test/regression/mkfifo.c#L30  by adding `O_TRUNC` flag and replacing `O_RDONLY` by `O_RDWR` and test this PR by running regression test.

2023-06-19 07:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1401)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1401#-NYHUtleE5FlYHANzVDg:-NYHUtleE5FlYHANzVDh:bike8uj) (no related file):*
Thanks @sahason for the PR. The idea is correct, but I'll take over this PR and will fix it to be more "Gramine" standard.

___


<!-- Sent from Reviewable.io -->

2023-06-19 07:37 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1401)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1401#-NYHUtleE5FlYHANzVDg:-NYHZo0I9qp2zYr1uZr8:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks @sahason for the PR. The idea is correct, but I'll take over this PR and will fix it to be more "Gramine" standard.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1401#-NYH_QOd22Dh9ueTp1GK:-NYH_QOd22Dh9ueTp1GL:b-il4fl1) (no related file):*
I tested this PR.

- Before this change:
```
[P1:T1:mkfifo] trace: ---- openat(AT_FDCWD, "tmp/fifo", O_WRONLY|O_TRUNC|0x800, 0000) = -22
```

- After this change:
```
[P1:T1:mkfifo] trace: ---- openat(AT_FDCWD, "tmp/fifo", O_WRONLY|O_TRUNC|0x800, 0000) = 0x4
```

___
___
*[`libos/src/fs/pipe/fs.c` line 215 at r2](https://reviewable.io/reviews/gramineproject/gramine/1401#-NYHZqy78nkcqacJSHT9:-NYHZqy78nkcqacJSHTA:b-c6hmf2) ([raw file](https://github.com/gramineproject/gramine/blob/42bd145f2bc223b31fc3aee8048f4bbe9a9d3559/libos/src/fs/pipe/fs.c#L215)):*
> ```C
>          * covers most apps seen in the wild (in particular, LTP apps). */
>         log_warning("FIFO (named pipe) '%s' cannot be opened in read-write mode in Gramine. "
>                     "Treating it as read-only.", dent->name);
> ```

This is an unrelated change which I detected when playing with `libos/test/regression/mkfifo.c` and `open(O_RDWR)`.

Before this change Gramine would output:
```
warning: FIFO (named pipe) '/' cannot be opened in read-write mode in Gramine. Treating it
 as read-only.
```

After this change:
```
warning: FIFO (named pipe) 'fifo' cannot be opened in read-write mode in Gramine. Treating
 it as read-only.
```
___
*[`libos/test/regression/mkfifo.c` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/1401#-NYH_7SY390ymVNmd3Ir:-NYH_7SY390ymVNmd3Is:bvea5h7) ([raw file](https://github.com/gramineproject/gramine/blob/42bd145f2bc223b31fc3aee8048f4bbe9a9d3559/libos/test/regression/mkfifo.c#L65)):*
> ```C
>             /* wait until client is ready for read (O_TRUNC flag here is only for testing) */
>             errno = 0;
>             fd = open(FIFO_PATH, O_NONBLOCK | O_WRONLY | O_TRUNC);
> ```

I added `O_TRUNC` to this server part (opening the write end of the FIFO pipe) purely for testing this corner case.

Same could be added to the client part (as @sahason did in the PR description), but I found it too convoluted for a test -- I don't think applications really do RW on FIFO pipes. Or even if they do, that's technically incorrect.


<!-- Sent from Reviewable.io -->

2023-06-19 07:38 UTC, dimakuv commented
Jenkins, test this please

2023-06-20 03:02 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1401)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-06-20 06:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1401)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-09-27 14:10 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1401)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1401#-NfLyU9n1YjUyelWK4cc:-NfLyU9n1YjUyelWK4cd:b-r7df3n) (no related file):*
Incidentally, we implemented a similar fix in 1563. So when that one is merged, we can close this PR.

___


<!-- Sent from Reviewable.io -->

2023-09-28 07:15 UTC, dimakuv commented
This was fixed as part of #1563 (which will be merged today). Closing.

2023-09-28 07:15 UTC, closed without merging