[LibOS] Rename POSIX lock related structs and functions
gramineproject/gramine pull request #1406
Opened 2023-06-19 13:59 UTC by dimakuv

## Description of the changes 

This is a preparatory commit to introduce flock (BSD locks) support. Previously, Gramine supported only POSIX locks, which was reflected in struct and function names (the `posix_` prefix and the `pl` abbreviation). With BSD locks, the same structs and functions will be used for both lock types, so this commit renames `posix` to `file` and `pl` to `file_lock`. Additionally, misleadingly named `struct fs_lock` is renamed to `struct dent_file_locks` (means: association of a dentry with its file locks).

Created in response to the comments in #1212.

## How to test this PR? 

CI is enough. Pure renaming.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1406)

2023-06-19 14:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/include/libos_fs.h` line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/1406#-NYIxncQ-mXwLPWkIusV:-NYIxncQ-mXwLPWkIusW:b1qm32s) ([raw file](https://github.com/gramineproject/gramine/blob/cd1b7c5efd480230793b592f514358bea1f9b371/libos/include/libos_fs.h#L194)):*
> ```objc
> #define DENTRY_MAX_CHILDREN 1000000
> 
> struct fs_lock_info;
> ```

FYI: `fs_lock_info` was not used at all.
___
*[`libos/include/libos_fs.h` line 229 at r1](https://reviewable.io/reviews/gramineproject/gramine/1406#-NYIxq9F0kT4QIfXy1eA:-NYIxq9F0kT4QIfXy1eB:b-g38n7p) ([raw file](https://github.com/gramineproject/gramine/blob/10b25a6a1c520a0251e61eacd65fc2530890fc96/libos/include/libos_fs.h#L229)):*
> ```objc
> 
>     /* File locks information, stored only in the main process. Managed by `libos_fs_lock.c`. */
>     struct dent_file_locks* file_locks;
> ```

FYI: I tried many different variants of this name. In the end, `dent_file_locks` for the struct looked the best to me.
___
*[`libos/include/libos_fs_lock.h` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1406#-NYIy0MjDTdWFs7pjZWS:-NYIy0MjDTdWFs7pjZWT:bhgw3de) ([raw file](https://github.com/gramineproject/gramine/blob/10b25a6a1c520a0251e61eacd65fc2530890fc96/libos/include/libos_fs_lock.h#L40)):*
> ```objc
>  */
> 
> DEFINE_LISTP(libos_file_lock);
> ```

FYI: Note that `libos_file_lock` is the only struct that is **exported** to the LibOS namespace. That's why it's the only struct that I changed to have the `libos_` prefix.

The other structs are internal to the corresponding `.c` files, so I did **not** add the `libos_` prefix.


<!-- Sent from Reviewable.io -->

2023-06-20 02:01 UTC, kailun-qin approved these changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-06-27 01:35 UTC, mkow requested changes
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1406#-NYuHX2e0LczR-ZIg5e2:-NYuHX2fBC_JxiMw2FjP:b-2y68e5) (no related file):*
What about a few functions you left? Any reason to keep the old naming for them? (I found at least `clear_posix_locks()` and `_posix_lock_set()`)

___


<!-- Sent from Reviewable.io -->

2023-06-27 07:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1406#-NYuHX2e0LczR-ZIg5e2:-NYvi5q71AU8URyxX5kz:b-mwsbug) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about a few functions you left? Any reason to keep the old naming for them? (I found at least `clear_posix_locks()` and `_posix_lock_set()`)
</blockquote></details>

This was intentional. Please see #1416 diff for all details. I went through the list of functions again now, and I think these are the only two that still have POSIX in their names. (Note that other functions are renamed because they are at least 95% similar for POSIX and BSD locks, so they can be reused and their names should be generic.)

Your particular functions:

---

`clear_posix_locks()` applies only to POSIX locks -- they are cleared on process termination and on file descriptor close.
- This is in contrast to BSD locks which are cleared on the **file description** close (i.e., when the last FD is closed, no matter in which process).
- Follow-up PR #1416 introduces a BSD counterpart to this function: `clear_flock_locks()`. See [here](https://github.com/gramineproject/gramine/pull/1416/files#diff-0f721e8eb80a385723861d62e4a949b2480bc428a79aba02af84a71759d4b131).

---

`_posix_lock_set()` applies only to POSIX locks -- this is a complicated function that works on the **file ranges**, and may split or merge file ranges as a result of applying a lock. Look at [its code](https://github.com/gramineproject/gramine/blob/0684091aa1c95497f24dab9a060307b86fe3a713/libos/src/fs/libos_fs_lock.c#L182) to get the picture.
- This is in contrast to BSD locks which **don't have** the concept of file ranges -- they always operate on a whole file. Thus, the function is much simpler for BSD locks.
- Follow-up PR #1416 introduces a BSD counterpart to this function: `_flock_lock_set()`. See [here](https://github.com/gramineproject/gramine/pull/1416/files#diff-955680514c317797e0d43c2d6260e5003b0f62a264926c3b0fee648c7881f630).

___


<!-- Sent from Reviewable.io -->

2023-06-27 11:01 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-27 11:40 UTC, mkow approved these changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1406)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-27 12:35 UTC, merged