[Meson] Replace `combo` with `feature` where possible
gramineproject/gramine pull request #1414
Opened 2023-06-23 07:12 UTC by dimakuv

## Description of the changes 

The `combo` options were left from the times when Meson was v0.47 (default on Ubuntu 18.04). Since those times, we moved to Meson at least v0.56 which has better-suited `feature` options.

## How to test this PR? 

CI.

2023-06-23 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYb5W1A3vnvvk2RR_ef:-NYb5W1A3vnvvk2RR_eg:b-p9n8fx) (no related file):*
This is a partial recreation of https://github.com/gramineproject/gramine/pull/619. That PR had no movement for ~1 year already, so I decided to create a small PR with just this change.

It was also a request from a review of #1400.

___
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYb5laU8xAVEkfYSfGW):*
I can change this Signed-off-by to Woju, since he was the original author of this change. @woju Would you care?


<!-- Sent from Reviewable.io -->

2023-06-26 03:59 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYpqMY175LsErvsAxMW):*
But the `feature` option of Meson was introduced exactly since 0.47.0, and the default on Ubuntu18.04 is actually 0.45.1?



_Code quote:_
```
  The `combo` options were left from the times when Meson was v0.47
  (default on Ubuntu 18.04). Since those times, we moved to Meson at least
```


<!-- Sent from Reviewable.io -->

2023-06-26 10:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYpqMY175LsErvsAxMW):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But the `feature` option of Meson was introduced exactly since 0.47.0, and the default on Ubuntu18.04 is actually 0.45.1?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 02:26 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-03 03:18 UTC, eli-schwartz commented on meson.build
> +enable_musl = get_option('musl').enabled()
What's the expected behavior if someone configures these options with the value e.g. `-Dmusl=auto`?

2023-07-03 06:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-NZPRb2fBkoS6TavIZsg:bxqilz2) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, eli-schwartz (Eli Schwartz) wrote…</i></summary><blockquote>

What's the expected behavior if someone configures these options with the value e.g. `-Dmusl=auto`?
</blockquote></details>

Hm. To be honest, I don't know. I'm not sure I understand from documentation what `auto` means exactly. I'll need @woju's help here.


<!-- Sent from Reviewable.io -->

2023-07-03 11:18 UTC, eli-schwartz commented
Feature options are tristate, and get special treatment from some meson functions -- the "auto" value means to do system proves to determine whether enabled/disabled is the right value. For example, when looking up a pkg-config dependency auto means use it if it's available, while disabled means don't use it at all.

2023-08-23 07:47 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @eli-schwartz)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYb5laU8xAVEkfYSfGW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can change this Signed-off-by to Woju, since he was the original author of this change. @woju Would you care?
</blockquote></details>

Yes, please add S-o-b from me.
___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-NcWJe9N6vg-D4POLqeH:b-w0zqn9) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm. To be honest, I don't know. I'm not sure I understand from documentation what `auto` means exactly. I'll need @woju's help here.
</blockquote></details>

I'd say `musl`/`glibc` need to check what's the currently running libc and build only this variant.
For SGX and/or driver, it could check for SGX support (perhaps by checking for `/dev/sgx_enclave` device?).
For `direct` it can just default to enabled, and `skeleton` to disabled.
About sanitizers I would have to think some more, but it probably can be enabled on clang on non-release builds, or just default to disabled.

What really matters I think is that we end up with sane set of defaults when someone just clones the repo and *does not* specify any options. This needs to be thought through. Worst case, we could set project-wide default to `auto_features`.

Also, weren't libc-related options changed to `-Dlibc={glibc,musl}` just before 1.5 release? @dimakuv can you please rebase on latest master and we'll see what we can do there?


<!-- Sent from Reviewable.io -->

2023-08-23 15:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eli-schwartz and @kailun-qin)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1414#-NYb5laU8xAVEkfYSfGW):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, please add S-o-b from me.
</blockquote></details>

Done
___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-NcY2BSj30dpC6kl7r5s:bpkvt9h) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd say `musl`/`glibc` need to check what's the currently running libc and build only this variant.
For SGX and/or driver, it could check for SGX support (perhaps by checking for `/dev/sgx_enclave` device?).
For `direct` it can just default to enabled, and `skeleton` to disabled.
About sanitizers I would have to think some more, but it probably can be enabled on clang on non-release builds, or just default to disabled.

What really matters I think is that we end up with sane set of defaults when someone just clones the repo and *does not* specify any options. This needs to be thought through. Worst case, we could set project-wide default to `auto_features`.

Also, weren't libc-related options changed to `-Dlibc={glibc,musl}` just before 1.5 release? @dimakuv can you please rebase on latest master and we'll see what we can do there?
</blockquote></details>

Done, I rebased to latest master.

Now we need to write some rules for `auto`, right?

I like your proposed rules, except these notes:
- Sanitizers should be disabled by default. I frequently just want to GDB a debug version of Gramine, and I don't want sanitizers to mess with my debugging session.


<!-- Sent from Reviewable.io -->

2023-08-24 01:00 UTC, mkow reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eli-schwartz)

___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-Nc_2S6m19DcelG3woqD:b-ogue5y) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I rebased to latest master.

Now we need to write some rules for `auto`, right?

I like your proposed rules, except these notes:
- Sanitizers should be disabled by default. I frequently just want to GDB a debug version of Gramine, and I don't want sanitizers to mess with my debugging session.
</blockquote></details>

+1, sanitizers shouldn't be enabled by default (it's really a very special build type).


<!-- Sent from Reviewable.io -->

2023-08-29 10:43 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eli-schwartz and @mkow)

___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-Nd-gtkl9gGjBhtJD7ry:bdmne5y) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, sanitizers shouldn't be enabled by default (it's really a very special build type).
</blockquote></details>

```
option('option_no_default', type: 'feature')
option('option_default_enabled', type: 'feature', value: 'enabled')
option('option_default_disabled', type: 'feature', value: 'disabled')
```

```
project('testmesonfeatures',
    version: '0')

summary({
    'option_no_default': get_option('option_no_default'),
    'option_default_enabled': get_option('option_default_enabled'),
    'option_default_disabled': get_option('option_default_disabled'),
}, section: 'option values:')

summary({
    'option_no_default.auto()':                 get_option('option_no_default').auto(),
    'option_no_default.enabled()':              get_option('option_no_default').enabled(),
    'option_no_default.disabled()':             get_option('option_no_default').disabled(),
    'not option_no_default.enabled()':          not get_option('option_no_default').enabled(),
    'not option_no_default.disabled()':         not get_option('option_no_default').disabled(),
    'option_default_enabled.auto()':            get_option('option_default_enabled').auto(),
    'option_default_enabled.enabled()':         get_option('option_default_enabled').enabled(),
    'option_default_enabled.disabled()':        get_option('option_default_enabled').disabled(),
    'not option_default_enabled.enabled()':     not get_option('option_default_enabled').enabled(),
    'not option_default_enabled.disabled()':    not get_option('option_default_enabled').disabled(),
    'option_default_disabled.auto()':           get_option('option_default_disabled').auto(),
    'option_default_disabled.enabled()':        get_option('option_default_disabled').enabled(),
    'option_default_disabled.disabled()':       get_option('option_default_disabled').disabled(),
    'not option_default_disabled.enabled()':    not get_option('option_default_disabled').enabled(),
    'not option_default_disabled.disabled()':   not get_option('option_default_disabled').disabled(),
}, section: 'how it works:')
```

```
[x86_64 pts/3] user@gramine-devel ~/tmp/testmesonfeatures [12:09 5281]% rm -rf build && meson setup build                         
The Meson build system
Version: 1.0.0
Source dir: /home/user/tmp/testmesonfeatures
Build dir: /home/user/tmp/testmesonfeatures/build
Build type: native build
Project name: testmesonfeatures
Project version: 0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0

testmesonfeatures 0

  option values:
    option_no_default                     : auto
    option_default_enabled                : enabled
    option_default_disabled               : disabled

  how it works:
    option_no_default.auto()              : True
    option_no_default.enabled()           : False
    option_no_default.disabled()          : False
    not option_no_default.enabled()       : True
    not option_no_default.disabled()      : True
    option_default_enabled.auto()         : False
    option_default_enabled.enabled()      : True
    option_default_enabled.disabled()     : False
    not option_default_enabled.enabled()  : False
    not option_default_enabled.disabled() : True
    option_default_disabled.auto()        : False
    option_default_disabled.enabled()     : False
    option_default_disabled.disabled()    : True
    not option_default_disabled.enabled() : True
    not option_default_disabled.disabled(): False

Found ninja-1.10.1 at /usr/bin/ninja
[x86_64 pts/3] user@gramine-devel ~/tmp/testmesonfeatures [12:09 5282]% rm -rf build && meson setup build --auto-features disabled
The Meson build system
Version: 1.0.0
Source dir: /home/user/tmp/testmesonfeatures
Build dir: /home/user/tmp/testmesonfeatures/build
Build type: native build
Project name: testmesonfeatures
Project version: 0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0

testmesonfeatures 0

  option values:
    option_no_default                     : disabled
    option_default_enabled                : enabled
    option_default_disabled               : disabled

  how it works:
    option_no_default.auto()              : False
    option_no_default.enabled()           : False
    option_no_default.disabled()          : True
    not option_no_default.enabled()       : True
    not option_no_default.disabled()      : False
    option_default_enabled.auto()         : False
    option_default_enabled.enabled()      : True
    option_default_enabled.disabled()     : False
    not option_default_enabled.enabled()  : False
    not option_default_enabled.disabled() : True
    option_default_disabled.auto()        : False
    option_default_disabled.enabled()     : False
    option_default_disabled.disabled()    : True
    not option_default_disabled.enabled() : True
    not option_default_disabled.disabled(): False

  User defined options
    auto_features                         : disabled

Found ninja-1.10.1 at /usr/bin/ninja
```

So I guess if you want the auto feature to be enabled, you need `not get_option('option').disabled()`, and auto disabled is `not get_option('option').enabled()`. After meson 1.1.0 we can write `feature.{enable,disable}_auto_if` (https://mesonbuild.com/Reference-manual_returned_feature.html), which might be a `# TODO after meson 1.1.0:` (which is not in any currently supported distro, so it looks like in AD 2027?).

Further, there's a difference between `value: 'enabled'` and `value: 'auto'` and then this `not` logic because of this `--auto-features` switch, which packages like to set to `disabled` in packaging toolchains and then selectively enable the features. So we need to think extra, but I suppose we can do it. Here's a proposal, going through all options in order:

- `'sgx'`: `'enabled'` and `'disabled'` work as usual, `'auto'` means we autodetect if the build machine has SGX and enable if so. In packaging, we always enable and ship. Default is `'auto'` (no default in `meson_options.txt`);
- `'direct'`: `'auto' simply means `'enabled'`, no autologic there. We set `value: 'enabled'` in `meson_options.txt`;
- `'skeleton'`: `'auto` means `'disabled'`, default disabled;
- `'libc'` leave `type: 'combo'` as is, possibly (feature request, so maybe not now, but `# TODO`) add `'auto'` choice which would mean to autodetect currently running libc;
- `'tests'`: `'auto'` means to enable on non-release builds. Default `'auto'`.
- `'dcap'`: `'auto'` means to detect the presence of that `libsgx_something_i_dont_remember.so` which AFAIR is a dependency? (Dimakuv plz help here, I already forgot the details), default `'auto'`; it's an error to enable this while having `sgx` disabled for any reason;
- `'*san'`: `'auto'` means disabled, default disabled;
- `'libgomp'`: I don't recall, but if this refers to a library to be detected in a system, then we can detect it? Or if it's a submodule, then IDK, I see it's default disabled, so I guess we don't change;
- `'sgx_driver'`: either we don't touch at all or `#TODO` for `'auto'` that would autodetect based on known paths to the driver? I would have to think more about how this would interact with `-Dsgx=auto`, so no proposal here;
- `'vtune'`: IIRC this is some instrumentation for a specific profiler? so disabled like sanitizers?
- other no change.

That would mean:
- ` [...]

2023-08-29 19:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eli-schwartz)

___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-Nd1kRLF4eEOGx8z1ENG:b7g2ura) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
> `'libgomp'`: I don't recall, but if this refers to a library to be detected in a system, then we can detect it? Or if it's a submodule, then IDK, I see it's default disabled, so I guess we don't change;

This should be `no` by default. Building it takes an hour and is just a perf optimization for some specific workloads.

> `vtune': IIRC this is some instrumentation for a specific profiler? so disabled like sanitizers?

IMO yes, disabled by-default.

Otherwise LGTM, overall sounds like a very nice feature to have.


<!-- Sent from Reviewable.io -->

2023-08-31 03:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eli-schwartz and @mkow)

___
*[`meson.build` line 44 at r2](https://reviewable.io/reviews/gramineproject/gramine/1414#gh-1250111610:-Nd8brbo2IkWDFZRljLR:b-9i8kwk) ([raw file](https://github.com/gramineproject/gramine/blob/f219338a9fb6398cd4f1b713c708108f7717ea50/meson.build#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `'libgomp'`: I don't recall, but if this refers to a library to be detected in a system, then we can detect it? Or if it's a submodule, then IDK, I see it's default disabled, so I guess we don't change;

This should be `no` by default. Building it takes an hour and is just a perf optimization for some specific workloads.

> `vtune': IIRC this is some instrumentation for a specific profiler? so disabled like sanitizers?

IMO yes, disabled by-default.

Otherwise LGTM, overall sounds like a very nice feature to have.
</blockquote></details>

I agree with all rules @woju wrote, plus the two comments from @mkow.

However, I'm being preempted by other, higher-priority work. So if anyone has the time and will to proceed with this PR/task, feel free. I will put it on backburner for now.


<!-- Sent from Reviewable.io -->

2024-09-25 08:24 UTC, dimakuv commented
This change turned to be much more complicated than I thought, I'm closing it as it is extremely low priority.

2024-09-25 08:24 UTC, closed without merging