[Meson] Remove ambigious `prefix` variable
gramineproject/gramine pull request #1415
Opened 2023-06-23 07:31 UTC by dimakuv

## Description of the changes 

Instead, always use non-ambigious `get_option('prefix')`.

Extracted from #619. That PR had no movement for ~1 year already, so I decided to create a small PR with just this change.

It was also a request from a review of #619 (see top-level comments from Woju and Borys).

## How to test this PR? 

CI.

2023-06-26 04:04 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-23 07:29 UTC, woju requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1415#-NcWGRfM0YK-_4w7Iw_9):*
I disagree with the assessment that `prefix` variable is "ambiguous" and `get_option('prefix')` is somehow not. It's really not, in the context of build system unqualified "prefix" cam mean only one thing.

But the change is OK, if you like this style.

`pkgsomethingdir` probably need to remain as they are, which I think are only path.


<!-- Sent from Reviewable.io -->

2023-08-23 15:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1415#-NcWGRfM0YK-_4w7Iw_9):*
I can modify the commit message to simply
```
[Meson] Replace `prefix` variable with `get_option('prefix')`
```

> But the change is OK, if you like this style.

It was actually *you* who did this change in the first place, in #619 :) Should I replace myself with your name in the commit author + signed-off-by?


<!-- Sent from Reviewable.io -->

2023-08-24 00:56 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-08-26 00:27 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1415#-NcjE4Sj5NSSwZVcQbGx):*
ditto below



_Suggestion:_
```
ambiguous
```


<!-- Sent from Reviewable.io -->

2023-08-28 04:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1415#-NcjE4Sj5NSSwZVcQbGx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto below
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1415#-NcWGRfM0YK-_4w7Iw_9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can modify the commit message to simply
```
[Meson] Replace `prefix` variable with `get_option('prefix')`
```

> But the change is OK, if you like this style.

It was actually *you* who did this change in the first place, in #619 :) Should I replace myself with your name in the commit author + signed-off-by?
</blockquote></details>

Done. I added you as a co-author.


<!-- Sent from Reviewable.io -->

2023-08-28 05:04 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2023-08-28 12:26 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-08-29 09:38 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-30 04:10 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1415)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-30 05:15 UTC, merged