[LibOS] Add `flock` syscall
gramineproject/gramine pull request #1416
Opened 2023-06-23 09:47 UTC by dimakuv

## Description of the changes 

The `flock` implementation introduces flock (aka BSD) locks, in addition to already-existing fcntl (aka POSIX) locks. The flock heavily reuses the current logic of `libos_file_lock` and `dent_file_locks`.

Since flock locks are tied to the handle, we introduce a new field `struct libos_file_lock::handle_id` that serves to distinguish flock  locks from fcntl locks. Similarly to fcntl locks, interruptable flock locks are not supported.

This is a reincarnation of #1212. It was easier to make it a new PR, then to continue working on the old PR.

## How to test this PR? 

New tests are added.

2023-06-23 10:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/include/libos_fs_lock.h` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYbsEho3-fALTkV0nby:-NYbsEho3-fALTkV0nbz:bn0nhxz) ([raw file](https://github.com/gramineproject/gramine/blob/7a9d4ddbd27c568163f7c698c7cb9b3d9d656cf3/libos/include/libos_fs_lock.h#L142)):*
> ```objc
>  * subsequent behavior is undefined).
>  */
> bool has_flock_locks(struct libos_dentry* dent);
> ```

In review of #1212, @mkow raised a point whether it's ok to have UB when fcntl and flock locks are mixed. Linux actually allows the mix, by completely separating these two types of locks (i.e., one type of locks doesn't interact with the other type of locks in any way -- which is a split-brain behavior, but that's what Linux does).

If we'll go with the weird Linux behavior, it will be pretty simple (all conflict-finding logic should just have a clear split: iterate only on fcntl locks or iterate only on flock locks). Then we can remove this `has_flock_locks()` function and we'll also be bug-for-bug compatible with Linux.

It will also probably require a new LibOS test that mixes the two locks.

I'm not a big fan of introducing the weird Linux behavior... But what we currently have is also pretty bad -- we just UB in such case, with confusing semantics.


<!-- Sent from Reviewable.io -->

2023-06-26 13:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYrrRVj-14-DuDFhLTE:-NYrrRVj-14-DuDFhLTF:b-quqm7l) (no related file):*
I found a bug in this code, currently fixing it...

For info, I see this bogus output in `fcntl_lock` test:
```
1: fcntl(fd, F_SETLK, {F_UNLCK, SEEK_SET,    5,   10}) = 0

file_lock: fcntl (POSIX): pid=1: r[15..19]
file_lock:  flock (BSD): handle id=14757395258967641292: r[25..39]
file_lock: fcntl (POSIX): pid=1: r[1000..end]
```

I.e., after unsetting the lock, I somehow get a stray BSD lock. This is clearly wrong.

___


<!-- Sent from Reviewable.io -->

2023-06-26 14:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYrrRVj-14-DuDFhLTE:-NYs2sxTE47TXlQckEn-:bp335dl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I found a bug in this code, currently fixing it...

For info, I see this bogus output in `fcntl_lock` test:
```
1: fcntl(fd, F_SETLK, {F_UNLCK, SEEK_SET,    5,   10}) = 0

file_lock: fcntl (POSIX): pid=1: r[15..19]
file_lock:  flock (BSD): handle id=14757395258967641292: r[25..39]
file_lock: fcntl (POSIX): pid=1: r[1000..end]
```

I.e., after unsetting the lock, I somehow get a stray BSD lock. This is clearly wrong.
</blockquote></details>

Done, fixed (see the first fixup commit).

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYs2xdI8sWw6sqkQXXw):*
My bad, I forgot `[LibOS]` here. Will do at final rebase.


<!-- Sent from Reviewable.io -->

2023-06-26 17:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`libos/include/libos_fs_lock.h` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYbsEho3-fALTkV0nby:-NYsfLyJ14xJhI-Bj_QH:b-r4fbyc) ([raw file](https://github.com/gramineproject/gramine/blob/7a9d4ddbd27c568163f7c698c7cb9b3d9d656cf3/libos/include/libos_fs_lock.h#L142)):*
> I'm not a big fan of introducing the weird Linux behavior... But what we currently have is also pretty bad -- we just UB in such case, with confusing semantics.

By the way, another simple idea is to disallow POSIX and BSD locks to be used in one app. Basically, introduce two global booleans, one for POSIX and one for BSD, and make sure they are never true together. This will be a very quick fix to the problem, while we could work on the proper mixing of POSIX plus BSD locks in a future PR.


<!-- Sent from Reviewable.io -->

2023-06-27 12:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYs2xdI8sWw6sqkQXXw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My bad, I forgot `[LibOS]` here. Will do at final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-27 12:55 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYwuGDnB900XcGgGR3x):*
> `struct libos_file_lock::handle_id` that serves to distinguish flock locks from fcntl locks.

This is quite obscure. How would the code look like if we had an `enum LOCK_TYPE` + a union with the lock-type-specific fields? The checks between the locks needs IFs anyways.

How much logic will be shared between these two types, if we make them independent? I see that Linux also shares the code between them, but has an explicit flag for the lock type.
___
*[`libos/include/libos_fs_lock.h` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYbsEho3-fALTkV0nby:-NYwtm-l-BBAOAD76HWy:b-ostkdi) ([raw file](https://github.com/gramineproject/gramine/blob/7a9d4ddbd27c568163f7c698c7cb9b3d9d656cf3/libos/include/libos_fs_lock.h#L142)):*
> If we'll go with the weird Linux behavior, it will be pretty simple (all conflict-finding logic should just have a clear split: iterate only on fcntl locks or iterate only on flock locks).

I'd go with this if it's actually simple.


<!-- Sent from Reviewable.io -->

2023-06-28 06:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYwuGDnB900XcGgGR3x):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> How much logic will be shared between these two types, if we make them independent? I see that Linux also shares the code between them, but has an explicit flag for the lock type.

Yes, the implementation was actually inspired by Linux.

Let me make it more explicit with `enum LOCK_TYPE`. I can also use a union, though Linux doesn't do it. In case anyone wonders how it is implemented in Linux, start here: https://elixir.bootlin.com/linux/v6.4/source/include/linux/filelock.h
</blockquote></details>

UPDATE: I tried with a union, but it touches **a lot of unrelated code**. I will probably create a branch or a DONTMERGE PR with this change alone, just to show how ugly it looks.

So for this PR, I will **not introduce a union**.

Also, because `type` is already used for `RLCK`, `WLCK`, `UNLCK`, I am going with the word `family` (i.e. `enum LOCK_FAMILY`). This is currently the best I can come up with, without modifying 80% of the file-lock code. In the future, I plan to have a "rename" PR that will reshape all objects in file-locking code.
___
*[`libos/src/sys/libos_fcntl.c` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYyDqXA8cNHjTfa7rjL:-NYyDqXA8cNHjTfa7rjM:b3cbr2a) ([raw file](https://github.com/gramineproject/gramine/blob/fcc59370ffecc5273828f716be949a6dc7139742/libos/src/sys/libos_fcntl.c#L63)):*
> ```C
>  * positive overflow.
>  */
> static int flock_to_file_lock(struct flock* fl, struct libos_handle* hdl, uint64_t handle_id,
> ```

I should remove this change -- this func will be used purely for POSIX locks.
___
*[`libos/src/sys/libos_fcntl.c` line 318 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ-jzwW8jzZZp-2Piq7:-NZ-jzwW8jzZZp-2Piq8:bmz771f) ([raw file](https://github.com/gramineproject/gramine/blob/fcc59370ffecc5273828f716be949a6dc7139742/libos/src/sys/libos_fcntl.c#L318)):*
> ```C
> 
>     struct libos_file_lock file_lock;
>     ret = flock_to_file_lock(&fl, hdl, hdl->id, &file_lock);
> ```

I will remove call to this function -- I can just create `file_lock` object directly here.


<!-- Sent from Reviewable.io -->

2023-06-28 08:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYwuGDnB900XcGgGR3x):*
Done (`family` field).

> How much logic will be shared between these two types, if we make them independent?

Looks like I didn't answer this question before. A **lot** of logic is shared between the two types, I would say around 80% of the code is common for POSIX and BSD locks.
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ-wJ_1-CVruSYilf5K):*
TODO: modify the commit message to mention:
- flock locks and fcntl locks are distinguished via `struct libos_file_lock::family`
- currently flock and fcntl locks cannot be mixed -- Gramine will loudly fail if it detects such attempts
___
*[`libos/src/sys/libos_fcntl.c` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYyDqXA8cNHjTfa7rjL:-NZ-vhBu5QnuE2f6A9xN:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fcc59370ffecc5273828f716be949a6dc7139742/libos/src/sys/libos_fcntl.c#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should remove this change -- this func will be used purely for POSIX locks.
</blockquote></details>

Done
___
*[`libos/src/sys/libos_fcntl.c` line 318 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ-jzwW8jzZZp-2Piq7:-NZ-vgMuA9kVeMJDL3yt:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fcc59370ffecc5273828f716be949a6dc7139742/libos/src/sys/libos_fcntl.c#L318)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will remove call to this function -- I can just create `file_lock` object directly here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-28 08:18 UTC, dimakuv commented
*[`libos/include/libos_fs_lock.h` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYbsEho3-fALTkV0nby:-NZ02xXC1k1r_YsbYohr:b-4bs9nl) ([raw file](https://github.com/gramineproject/gramine/blob/7a9d4ddbd27c568163f7c698c7cb9b3d9d656cf3/libos/include/libos_fs_lock.h#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If we'll go with the weird Linux behavior, it will be pretty simple (all conflict-finding logic should just have a clear split: iterate only on fcntl locks or iterate only on flock locks).

I'd go with this if it's actually simple.
</blockquote></details>

So conforming to the Linux behavior turned out to be not so simple. The main obstacle is the fact that "list of locks" is shared between POSIX and BSD locks, and this list is supposed to be ordered in a special way (for POSIX locks). See:
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/fs/libos_fs_lock.c#L53-L55?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/fs/libos_fs_lock.c#L225?plain=1 (this whole func assumes the ordering)

This is not *that* hard to fix, there are two ways:
- Keep this single "list of locks", and just modify the POSIX ordering code to "jump over" BSD locks. Sounds a bit ugly.
- Split "list of locks" into two lists, one for POSIX locks (and ordered) and one for BSD locks (doesn't need to be ordered). Requires a lot of changes.

---

Given the above, I currently decided to go in another direction: **disallow POSIX and BSD locks to be used in the same app**. This is much easier to implement, and doesn't regress Gramine.


<!-- Sent from Reviewable.io -->

2023-06-28 12:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_fs_lock.h` line 142 at r1](https://reviewable.io/reviews/gramineproject/gramine/1416#-NYbsEho3-fALTkV0nby:-NZ0yvEO8jycurUVk68O:b-gt55zi) ([raw file](https://github.com/gramineproject/gramine/blob/7a9d4ddbd27c568163f7c698c7cb9b3d9d656cf3/libos/include/libos_fs_lock.h#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So conforming to the Linux behavior turned out to be not so simple. The main obstacle is the fact that "list of locks" is shared between POSIX and BSD locks, and this list is supposed to be ordered in a special way (for POSIX locks). See:
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/fs/libos_fs_lock.c#L53-L55?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/fs/libos_fs_lock.c#L225?plain=1 (this whole func assumes the ordering)

This is not *that* hard to fix, there are two ways:
- Keep this single "list of locks", and just modify the POSIX ordering code to "jump over" BSD locks. Sounds a bit ugly.
- Split "list of locks" into two lists, one for POSIX locks (and ordered) and one for BSD locks (doesn't need to be ordered). Requires a lot of changes.

---

Given the above, I currently decided to go in another direction: **disallow POSIX and BSD locks to be used in the same app**. This is much easier to implement, and doesn't regress Gramine.
</blockquote></details>

Done. This also lets us get rid of `has_flock_locks()` func.
___
*[`libos/include/libos_handle.h` line 152 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ0z3Hb4QdORfQBiL-u:-NZ0z3Hb4QdORfQBiL-v:b-628rzb) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_handle.h#L152)):*
> ```objc
>      *        tracking of handle FDs. On the other hand, Gramine anyway doesn't support the
>      *        "daemonization" case described above, so the assumption of "last" FD works fine.
>      */
> ```

FYI: This problem is a bit similar to "re-parenting":
- https://github.com/gramineproject/gramine/issues/21
- https://github.com/gramineproject/gramine/issues/1168

The thing is: we don't have a "master" process (like an `init` process) that would collect info from all processes and make decisions based on this system-wide knowledge.


<!-- Sent from Reviewable.io -->

2023-06-28 15:13 UTC, mkow requested changes
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 1 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_fs_lock.h` line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1Kxjf7FvpvZsCTdvl:-NZ1Kxjf7FvpvZsCTdvm:bqmsbas) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L36)):*
> ```objc
>  * - The main process has to be able to look up the same file, so locking will not work for files in
>  *   local-process-only filesystems (tmpfs).
>  * - There is no deadlock detection (EDEADLK).
> ```

This is only for fcntl-locks, flock doesn't have such thing.
___
*[`libos/include/libos_fs_lock.h` line 79 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1PoH36lHseQ2mLUXQ:-NZ1PoH36lHseQ2mLUXR:bswxzdf) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L79)):*
> remove all locks held by

All BSD locks? Or also POSIX?

(also for the sentence above)
___
*[`libos/include/libos_fs_lock.h` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1RBZf4u5PN87p8B2l:-NZ1RBZf4u5PN87p8B2m:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L86)):*
> ```objc
>  * - For POSIX (fcntl) locks, for the given PID and range, replace the existing locks held by the
>  *   given PID for that range.
>  * - for BSD (flock) locks, replace the existing locks held by the given handle ID.
> ```

ditto
___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ1SA8D9Gyz2KQTgWeG:bfcsphk) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*
> ```objc
>  * If the lock could be placed, `out_file_lock->type` is set to `F_UNLCK`. Otherwise,
>  * `out_file_lock` fields (`type`, `start, `end`, `pid`, `handle_id`) are set to details of a
>  * conflicting lock.
> ```

It was like this before, but how does this work? It sounds inherently racy - this function only checks whether you can place the lock, but what prevents the state from changing between the return form here and the setting of the lock?
___
*[`libos/src/fs/libos_fs_lock.c` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1TPNC4kvfeOSDOYjQ:-NZ1TPNC4kvfeOSDOYjR:b-cnaw5k) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/src/fs/libos_fs_lock.c#L20)):*
> ```C
> /* Used to disallow mixing of POSIX and BSD locks. Protected by `g_fs_lock_lock`. */
> static bool g_file_lock_posix_used = false;
> static bool g_file_lock_flock_used = false;
> ```

Oh, so this is global, not per-file? Why?
Also, does it detect the situation where process A creates an flock, and process B creates an fcntl lock?
___
*[`libos/src/fs/libos_fs_lock.c` line 185 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1YiT40TG4kAOhPcjg:-NZ1YiT40TG4kAOhPcjh:b-k0p7y0) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/src/fs/libos_fs_lock.c#L185)):*
> otherwise it may exhibit unexpected behavior

This is outdated, now we fail loudly.


<!-- Sent from Reviewable.io -->

2023-06-28 17:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 1 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_fs_lock.h` line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1Kxjf7FvpvZsCTdvl:-NZ1ujOd22sAv714SOty:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is only for fcntl-locks, flock doesn't have such thing.
</blockquote></details>

Done.
___
*[`libos/include/libos_fs_lock.h` line 79 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1PoH36lHseQ2mLUXQ:-NZ1uuMA7eySCMynd9K2:b-lt5wx0) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> remove all locks held by

All BSD locks? Or also POSIX?

(also for the sentence above)
</blockquote></details>

Done. POSIX and BSD locks cannot (currently) coexist in the same Gramine instance, so I thought it didn't need an explicit mention. But Ok.
___
*[`libos/include/libos_fs_lock.h` line 86 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1RBZf4u5PN87p8B2l:-NZ1v5BS5iFL2vTFCDC5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ1vRmcDqe1isQLRKTK:bwfomb4) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*


This method is inherently racy, yes.

Please read this snippet from `man 2 fcntl`:

>       **F\_GETLK** (_struct flock \*_)
>              On input to this call, _lock_ describes a lock we would like
>              to place on the file.  If the lock could be placed,
>              **fcntl**() does not actually place it, but returns **F\_UNLCK** in
>              the _l\_type_ field of _lock_ and leaves the other fields of
>              the structure unchanged.
>
>              If one or more incompatible locks would prevent this lock
>              being placed, then **fcntl**() returns details about one of
>              those locks in the _l\_type_, _l\_whence_, _l\_start_, and _l\_len_
>              fields of _lock_.  If the conflicting lock is a traditional
>              (process-associated) record lock, then the _l\_pid_ field is
>              set to the PID of the process holding that lock.  If the
>              conflicting lock is an open file description lock, then
>              _l\_pid_ is set to -1.  **Note that the returned information
>              may already be out of date by the time the caller inspects
>              it.**

Note the very last sentence. We adhere to the same semantics.
___
*[`libos/src/fs/libos_fs_lock.c` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1TPNC4kvfeOSDOYjQ:-NZ1wXEs0-bIgP9aoFMl:bs2ul79) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/src/fs/libos_fs_lock.c#L20)):*
> Oh, so this is global, not per-file? Why?

I can do it per-file (per dentry). Ok, actually, let me just do it.

> Also, does it detect the situation where process A creates an flock, and process B creates an fcntl lock?

Yes. Recall that all actual file-locking operations are done in the master (leader) process. And these variables are checked in the function `file_lock_set_or_add_request()` which is only called in the master process. So even if process A (leader) creates an flock and process B (child) creates an fcntl lock, the fcntl lock request will be sent to process A and processed in process A anyway.

I will add a comment and an additional test case for this.
___
*[`libos/src/fs/libos_fs_lock.c` line 185 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1YiT40TG4kAOhPcjg:-NZ1xLXH9f7pkkbLtj2c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/src/fs/libos_fs_lock.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> otherwise it may exhibit unexpected behavior

This is outdated, now we fail loudly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-28 17:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 0 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ-wJ_1-CVruSYilf5K):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: modify the commit message to mention:
- flock locks and fcntl locks are distinguished via `struct libos_file_lock::family`
- currently flock and fcntl locks cannot be mixed -- Gramine will loudly fail if it detects such attempts
</blockquote></details>

...cannot be mixed *on the same file*
___
*[`libos/src/fs/libos_fs_lock.c` line 20 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1TPNC4kvfeOSDOYjQ:-NZ24VaT87ViXSJWQSN7:bmfxg67) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/src/fs/libos_fs_lock.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Oh, so this is global, not per-file? Why?

I can do it per-file (per dentry). Ok, actually, let me just do it.

> Also, does it detect the situation where process A creates an flock, and process B creates an fcntl lock?

Yes. Recall that all actual file-locking operations are done in the master (leader) process. And these variables are checked in the function `file_lock_set_or_add_request()` which is only called in the master process. So even if process A (leader) creates an flock and process B (child) creates an fcntl lock, the fcntl lock request will be sent to process A and processed in process A anyway.

I will add a comment and an additional test case for this.
</blockquote></details>

Done 2x


<!-- Sent from Reviewable.io -->

2023-06-29 00:57 UTC, mkow requested changes
> Reviewed 3 of 6 files at r5, 2 of 5 files at r6, 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 7 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_fs_lock.h` line 79 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1PoH36lHseQ2mLUXQ:-NZ31T5t5aDKGyqkaIgQ:b32akqf) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. POSIX and BSD locks cannot (currently) coexist in the same Gramine instance, so I thought it didn't need an explicit mention. But Ok.
</blockquote></details>

Hmm, but in the discussion above you said "...cannot be mixed _on the same file_"?
___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ33waN5-b_Wh1aEs-W:bwxqzax) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>



This method is inherently racy, yes.

Please read this snippet from `man 2 fcntl`:

>       **F\_GETLK** (_struct flock \*_)
>              On input to this call, _lock_ describes a lock we would like
>              to place on the file.  If the lock could be placed,
>              **fcntl**() does not actually place it, but returns **F\_UNLCK** in
>              the _l\_type_ field of _lock_ and leaves the other fields of
>              the structure unchanged.
>
>              If one or more incompatible locks would prevent this lock
>              being placed, then **fcntl**() returns details about one of
>              those locks in the _l\_type_, _l\_whence_, _l\_start_, and _l\_len_
>              fields of _lock_.  If the conflicting lock is a traditional
>              (process-associated) record lock, then the _l\_pid_ field is
>              set to the PID of the process holding that lock.  If the
>              conflicting lock is an open file description lock, then
>              _l\_pid_ is set to -1.  **Note that the returned information
>              may already be out of date by the time the caller inspects
>              it.**

Note the very last sentence. We adhere to the same semantics.
</blockquote></details>

Ugh, weird but ok.
Btw. what's the difference between "a traditional (process-associated) record lock" and "an open file description lock"? Sounds like this sub-call should also look at BSD locks? I'm confused...
___
*[`libos/include/libos_handle.h` line 152 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ0z3Hb4QdORfQBiL-u:-NZ3P_bm0IaA2A_bvCAq:b-w1lve5) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_handle.h#L152)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This problem is a bit similar to "re-parenting":
- https://github.com/gramineproject/gramine/issues/21
- https://github.com/gramineproject/gramine/issues/1168

The thing is: we don't have a "master" process (like an `init` process) that would collect info from all processes and make decisions based on this system-wide knowledge.
</blockquote></details>

Ouch. This sounds bad, it's not just a leak, but we can incorrectly unlock the lock while it still should be locked?
I think I would prefer to leak resources or deadlock in this case than incorrectly unlock the lock.
___
*[`libos/src/bookkeep/libos_handle.c` line 357 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3SGCC-3yyVJRxjdaz:-NZ3SGCC-3yyVJRxjdb-:b-o7euuy) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/bookkeep/libos_handle.c#L357)):*
> ```C
>     static uint64_t local_counter = 0;
>     new_handle->id = ((uint64_t)g_process.pid << 32)
>                       | __atomic_add_fetch(&local_counter, 1, __ATOMIC_RELAXED);
> ```

Can we fail if the counter overflows?
Also, is it possible to overflow the PID in Gramine?

In any of these two cases it would lead to 2 different locks being aliased, which is potentially security-relevant.
___
*[`libos/src/fs/libos_fs_lock.c` line 56 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3XYYm8s4ZQKzlImWB:-NZ3XYYm8s4ZQKzlImWC:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/fs/libos_fs_lock.c#L56)):*
> ```C
>     /* Used to disallow mixing of POSIX and BSD locks on the same file (dentry). Note that all file
>      * locking requests are processed by the leader process, so even if POSIX and BSD locks are
>      * created in different processes, they will end up in leader and will update these fields. */
> ```





_Suggestion:_
```C
they will end up in the leader and it will update these fields
```
___
*[`libos/src/fs/libos_fs_lock.c` line 180 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3YafaDp9hcbtzVeYF:-NZ3YafaDp9hcbtzVeYG:b-lfohug) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/fs/libos_fs_lock.c#L180)):*
Migrating the discussion from the old PR:
> mkow:
> > at least one of them is a write lock
> 
> There are no write locks in flock? At least not in the part implemented in this PR.

> dimakuv:
>
> Why do you say it? Flock locks implement writes, by piggy-backing on already-implemented `F_WRLCK` logic.
>
> See handling of `LOCK_EX` (aka write lock aka exclusive lock) in `libos_syscall_flock()`.

But the flock API doesn't have write-locks, and this sentence is talking about flocks (not how we mapped it into the common struct inside LibOS). Flock API calls this "exclusive locks".
___
*[`libos/src/ipc/libos_ipc_fs_lock.c` line 155 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3d4eBCxIGM1uJftrW:-NZ3d4eBCxIGM1uJftrX:bms9dmj) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/ipc/libos_ipc_fs_lock.c#L155)):*
> ```C
>         .end = file_lock2.end,
>         .pid = file_lock2.pid,
>         .handle_id = file_lock2.handle_id,
> ```

TODO for myself after we have the final version of this PR: Check if all uses of these modified structures handle this new field.


<!-- Sent from Reviewable.io -->

2023-06-29 06:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 4 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_fs_lock.h` line 79 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1PoH36lHseQ2mLUXQ:-NZ4dzNz187P-H9gBFHL:bml35pk) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L79)):*
> Hmm, but in the discussion above you said "...cannot be mixed _on the same file_"?

Yes, true. I wrote my comment before I modified from "cannot be mixed in the same instance" to "cannot be mixed on the same file".
___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ4fIiz7UN2trDIioEk:b-bsj5m6) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*
> Btw. what's the difference between "a traditional (process-associated) record lock" and "an open file description lock"? Sounds like this sub-call should also look at BSD locks? I'm confused...

No, there are several "families" of locks. BSD (flock) locks have nothing to do with this man-page description.

I will only mention three families, not to confuse you even further:
1. POSIX (fcntl) locks aka "traditional (process-associated) record locks"
2. BSD (flock) locks
3. OFD (Open File Description) locks aka File-private POSIX locks (old name)

Gramine currently implements the first two and does **not** implement the third. Here are several good references on OFDs:
- https://www.gnu.org/software/libc/manual/html_node/Open-File-Description-Locks.html
- https://lwn.net/Articles/586904/
- https://gavv.net/articles/file-locks/#open-file-description-locks-fcntl

In the second (LWN) article, the author of this family of locks describes what OFDs are very well. (In the original patches, OFD locks were called "File-private POSIX locks".) Several snippets:

> File-private POSIX locks are an attempt to take elements of both BSD-style and POSIX locks and combine them into a more threading-friendly file locking API.

> The only real problem with BSD locks is that they are whole-file locks. POSIX locks, on the other hand can operate on arbitrary byte ranges within a file. While whole-file locks are useful (and indeed, many applications just lock entire files even with POSIX locks), they are not sufficient for many cases. Applications such as databases need granular locking in order to allow for better parallelism.

> I will assert that what is needed is a new type of lock that is a hybrid of the two — a byte-range lock that has BSD-like semantics for inheritance across fork() and on close().

---

Maybe one day we'll implement OFD locks in Gramine. Then the `If the conflicting lock is an open file description lock, then _l\_pid_ is set to -1.` will become relevant to us. For now, just ignore this.
___
*[`libos/include/libos_handle.h` line 152 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ0z3Hb4QdORfQBiL-u:-NZ4thFXEhQRa1TK-dlP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_handle.h#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ouch. This sounds bad, it's not just a leak, but we can incorrectly unlock the lock while it still should be locked?
I think I would prefer to leak resources or deadlock in this case than incorrectly unlock the lock.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 357 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3SGCC-3yyVJRxjdaz:-NZ4jROd1pH65aZASL0I:bzdpxfi) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/bookkeep/libos_handle.c#L357)):*
> Can we fail if the counter overflows?

Done.

> Also, is it possible to overflow the PID in Gramine?

I guess you mean "can PIDs be reused"? The answer is yes. The code is a bit complicated, but here it is: 
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/include/libos_types.h#L30-L31?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L59-L102?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L112-L117?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/bookkeep/libos_pid.c#L78?plain=1

In short, what happens with PIDs/TIDs is the following:
1. Gramine's IPC leader maintains a tree of ID ranges. Initially this tree is empty, and each new request (from the IPC leader process itself or from its child processes) creates a new ID range and adds it to the table. Each ID range is capped at `MAX_RANGE_SIZE` (32) IDs.
2. ID ranges start at ID=0 and grow in 32-ID chunks.
3. ID ranges grow until `PID_MAX` which is `2^22 - 1` (~4 million). Then Gramine tries to reuse them.
   - Even if some child processes released their ID ranges, the IPC leader does **not** "jump back" and re-use those ID ranges immediately.
   - Instead, the IPC leader waits until the ID rolling integer (`g_last_id`) exceeds `PID_MAX` and only then starts reusing ID ranges.
   - This logic is encapsulated in these snippets:
   - https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L66?plain=1
   - https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L114?plain=1

To achieve this max limit, we need to:
- either create ~4 million threads,
- or (the worst case) create `4194304 / 32 = 131072` single-thread processes.

After this limit, Gramine starts reusing PIDs.

**This was like this before. Do we care about fixing it in this PR?**
___
*[`libos/src/fs/libos_fs_lock.c` line 56 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3XYYm8s4ZQKzlImWB:-NZ4n3ec0axlOg9OWzGt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/fs/libos_fs_lock.c#L56)):*
> ```C
>     /* Used to disallow mixing of POSIX and BSD locks on the same file (dentry). Note that all file
>      * locking requests are processed by the leader process, so even if POSIX and BSD locks are
>      * created in different processes, they will end up in leader and will update these fields. */
> ```

Done.
___
*[`libos/src/fs/libos_fs_lock.c` line 180 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3YafaDp9hcbtzVeYF:-NZ4njWD4iTJ-tzPHpQJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/fs/libos_fs_lock.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Migrating the discussion from the old PR:
> mkow:
> > at least one of them is a write lock
> 
> There are no write locks in flock? At least not in the part implemented in this PR.

> dimakuv:
>
> Why do you say it? Flock locks implement writes, by piggy-backing on already-implemented `F_WRLCK` logic.
>
> See handling of `LOCK_EX` (aka write lock aka exclusive lock) in `libos_syscall_flock()`.

But the flock API doesn't have write-locks, and this sentence is talking about flocks (not how we mapped it into the common struct inside LibOS). Flock API calls this "exclusive locks".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 14:10 UTC, mkow requested changes
> Reviewed 1 of 4 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 7 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ5z8XREcNuDn0sa81l:b-scn2d9) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Btw. what's the difference between "a traditional (process-associated) record lock" and "an open file description lock"? Sounds like this sub-call should also look at BSD locks? I'm confused...

No, there are several "families" of locks. BSD (flock) locks have nothing to do with this man-page description.

I will only mention three families, not to confuse you even further:
1. POSIX (fcntl) locks aka "traditional (process-associated) record locks"
2. BSD (flock) locks
3. OFD (Open File Description) locks aka File-private POSIX locks (old name)

Gramine currently implements the first two and does **not** implement the third. Here are several good references on OFDs:
- https://www.gnu.org/software/libc/manual/html_node/Open-File-Description-Locks.html
- https://lwn.net/Articles/586904/
- https://gavv.net/articles/file-locks/#open-file-description-locks-fcntl

In the second (LWN) article, the author of this family of locks describes what OFDs are very well. (In the original patches, OFD locks were called "File-private POSIX locks".) Several snippets:

> File-private POSIX locks are an attempt to take elements of both BSD-style and POSIX locks and combine them into a more threading-friendly file locking API.

> The only real problem with BSD locks is that they are whole-file locks. POSIX locks, on the other hand can operate on arbitrary byte ranges within a file. While whole-file locks are useful (and indeed, many applications just lock entire files even with POSIX locks), they are not sufficient for many cases. Applications such as databases need granular locking in order to allow for better parallelism.

> I will assert that what is needed is a new type of lock that is a hybrid of the two — a byte-range lock that has BSD-like semantics for inheritance across fork() and on close().

---

Maybe one day we'll implement OFD locks in Gramine. Then the `If the conflicting lock is an open file description lock, then _l\_pid_ is set to -1.` will become relevant to us. For now, just ignore this.
</blockquote></details>

Uhhh, _third_ file locking mechanism? I'll just pretend I've never learned about this.
___
*[`libos/src/bookkeep/libos_handle.c` line 357 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3SGCC-3yyVJRxjdaz:-NZ6Sam0BFY2xczW3gho:b5x27il) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/bookkeep/libos_handle.c#L357)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Can we fail if the counter overflows?

Done.

> Also, is it possible to overflow the PID in Gramine?

I guess you mean "can PIDs be reused"? The answer is yes. The code is a bit complicated, but here it is: 
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/include/libos_types.h#L30-L31?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L59-L102?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L112-L117?plain=1
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/bookkeep/libos_pid.c#L78?plain=1

In short, what happens with PIDs/TIDs is the following:
1. Gramine's IPC leader maintains a tree of ID ranges. Initially this tree is empty, and each new request (from the IPC leader process itself or from its child processes) creates a new ID range and adds it to the table. Each ID range is capped at `MAX_RANGE_SIZE` (32) IDs.
2. ID ranges start at ID=0 and grow in 32-ID chunks.
3. ID ranges grow until `PID_MAX` which is `2^22 - 1` (~4 million). Then Gramine tries to reuse them.
   - Even if some child processes released their ID ranges, the IPC leader does **not** "jump back" and re-use those ID ranges immediately.
   - Instead, the IPC leader waits until the ID rolling integer (`g_last_id`) exceeds `PID_MAX` and only then starts reusing ID ranges.
   - This logic is encapsulated in these snippets:
   - https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L66?plain=1
   - https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/libos/src/ipc/libos_ipc_pid.c#L114?plain=1

To achieve this max limit, we need to:
- either create ~4 million threads,
- or (the worst case) create `4194304 / 32 = 131072` single-thread processes.

After this limit, Gramine starts reusing PIDs.

**This was like this before. Do we care about fixing it in this PR?**
</blockquote></details>

I think we should fix it, because this PR makes crossing this limit dangerous.
___
*[`libos/src/bookkeep/libos_handle.c` line 358 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6TpbN-vvPWIQ1bHjU:-NZ6TpbO1k6voPQjR38H:b-pk7da7) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L358)):*
> ```C
>     new_handle->id = ((uint64_t)g_process.pid << 32)
>                       | __atomic_add_fetch(&local_id_counter, 1, __ATOMIC_RELAXED);
>     if ((new_handle->id & 0xFFFFFFFF) == 0) {
> ```

I think it would be simpler if you assigned the result of `__atomic_add_fetch()` above to a variable?
___
*[`libos/src/bookkeep/libos_handle.c` line 499 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6UGHv6bnfdxypFXOe:-NZ6UGHwDOpgSseTmu7_:b-q4ptla) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L499)):*
> ```C
>             /* Do not perform an unlock operation if this process has children. This may leak
>              * resources or deadlock, but protects against unsafe behavior. See comments near
>              * `created_by_process` in libos_handle.h header. */
> ```

Does this also works if we had A->B->C, but process B died?


<!-- Sent from Reviewable.io -->

2023-06-29 14:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 7 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_fs_lock.h` line 109 at r6](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ1SA8D9Gyz2KQTgWeF:-NZ6V2XVA0Chx2uhpWai:b-i2vr12) ([raw file](https://github.com/gramineproject/gramine/blob/f0a282a818f8c738ec5c2ccf46428d659e0f7cec/libos/include/libos_fs_lock.h#L109)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Uhhh, _third_ file locking mechanism? I'll just pretend I've never learned about this.
</blockquote></details>

Well, then I won't suggest to search for `F_SETLEASE` :)
___
*[`libos/src/bookkeep/libos_handle.c` line 357 at r7](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ3SGCC-3yyVJRxjdaz:-NZ6VCJw64mWvjZpjDIy:b1ya3o) ([raw file](https://github.com/gramineproject/gramine/blob/520a0191cd97c6d2350642a9f3a1b7d141501c62/libos/src/bookkeep/libos_handle.c#L357)):*
> I think we should fix it, because this PR makes crossing this limit dangerous.

Quick clarification: do you want us to put a hard limit on the number of created IDs? I.e., we must fail instead of wrapping around? This is a regression from previous Gramine behavior...
___
*[`libos/src/bookkeep/libos_handle.c` line 499 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6UGHv6bnfdxypFXOe:-NZ6Vqqz6BG5PuHo6e84:b-8x5ctn) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L499)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this also works if we had A->B->C, but process B died?
</blockquote></details>

No, it doesn't. I don't know how to handle this case without a central authority that manages handles/objects.

I don't know what to do in this case.


<!-- Sent from Reviewable.io -->

2023-06-29 15:13 UTC, mkow reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 8 of 14 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 499 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6UGHv6bnfdxypFXOe:-NZ6hLbaCcWBDDJ2tH9g:b5u2au7) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Can't we use the central process which already manages the locks to check this condition? Or would it be too complex?

Which condition exactly? If we would implement in the central process, then we should implement the correct solution: which is to keep track of the number of references to each opened handle, and only fire some event (like `LOCK_UN`) when the refcount goes down to zero.

Basically, this will require system-wide refcounting. Which means a lot of IPC scaffolding: an IPC request when the ref to the handle is created in any process, an IPC request when the ref to the handle is closed in any process, an IPC request when the refs of handles are increased during fork (because it serves as a dup). This is a huge task.

Sorry, I don't think there is any simple fix to this.
</blockquote></details>

Maybe @kailun-qin has any ideas?


<!-- Sent from Reviewable.io -->

2023-06-29 19:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 9 of 17 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 12 at r9](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6g1La0pYFfaQH3bPm):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

interruptible
</blockquote></details>

Will do at final rebase
___
*[`libos/include/libos_fs_lock.h` line 86 at r9](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6h6wp5Va0jxPYxxb8:-NZ7_vNe1I6ypADYvIwh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b5a7e8b3e09303bd85c9da69d9beef19e3537fe/libos/include/libos_fs_lock.h#L86)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

For
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 499 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6UGHv6bnfdxypFXOe:-NZ7a_8_BSL-EWE2hkzO:bmeq2n8) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L499)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I agree that it sounds bad. But sorry that I don't see a simple fix that can be correct at the same time (as we've decided that we'd never want to incorrectly unlock the lock). :(
</blockquote></details>

Done, kinda. I tried different ideas, but I always end up with "system-wide handle refcounting". Which is not easy to implement, and can't be crammed into this PR for sure.

So I introduced `sys.experimental__enable_flock` and this feature becomes experimental. I don't know what else we can with this PR.
___
*[`libos/src/bookkeep/libos_handle.c` line 502 at r10](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ7b51w84IlFO_psJDp:-NZ7b51w84IlFO_psJDq:bdaradd) ([raw file](https://github.com/gramineproject/gramine/blob/ee9d4ad5cf593c676776df2ad3359b24a1fa0cb0/libos/src/bookkeep/libos_handle.c#L502)):*
> ```C
>             return -EBUSY;
>         }
>         unlock(&g_process.children_lock);
> ```

Btw, if we decide to go with this `sys.experimental__enable_flock` thing, then I can remove this whole hunk about `g_process.children` check. It works only in the simple cases anyway.


<!-- Sent from Reviewable.io -->

2023-06-29 22:01 UTC, mkow requested changes
> Reviewed 4 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 13 of 17 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/manifest-syntax.rst` line 607 at r10](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ88I1e0QGBep7TFG82:-NZ88I1e0QGBep7TFG83:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ee9d4ad5cf593c676776df2ad3359b24a1fa0cb0/Documentation/manifest-syntax.rst#L607)):*
> ```reStructuredText
> .. warning::
>    This syscall is still under development and may contain security
>    vulnerabilities. This is temporary; the syscall will be enabled in future
> ```





_Suggestion:_
```reStructuredText
the syscall will be enabled by default in the future
```
___
*[`libos/src/bookkeep/libos_handle.c` line 499 at r8](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6UGHv6bnfdxypFXOe:-NZ89ERB2QNrMdEOJBKr:b-nc4ji4) ([raw file](https://github.com/gramineproject/gramine/blob/eb9396e31a0dca3130da2ef9d4a9fcd740105878/libos/src/bookkeep/libos_handle.c#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, kinda. I tried different ideas, but I always end up with "system-wide handle refcounting". Which is not easy to implement, and can't be crammed into this PR for sure.

So I introduced `sys.experimental__enable_flock` and this feature becomes experimental. I don't know what else we can with this PR.
</blockquote></details>

Sounds like the only reasonable solution for now, I completely forgot we have such an option.
___
*[`libos/src/bookkeep/libos_handle.c` line 502 at r10](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ7b51w84IlFO_psJDp:-NZ8A8BnD0aHnr4ZoQuo:bxke4xl) ([raw file](https://github.com/gramineproject/gramine/blob/ee9d4ad5cf593c676776df2ad3359b24a1fa0cb0/libos/src/bookkeep/libos_handle.c#L502)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, if we decide to go with this `sys.experimental__enable_flock` thing, then I can remove this whole hunk about `g_process.children` check. It works only in the simple cases anyway.
</blockquote></details>

I'd remove it then.


<!-- Sent from Reviewable.io -->

2023-06-29 22:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 11 of 17 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 607 at r10](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ88I1e0QGBep7TFG82:-NZ8BMA-3B80SIUsVk94:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee9d4ad5cf593c676776df2ad3359b24a1fa0cb0/Documentation/manifest-syntax.rst#L607)):*
> ```reStructuredText
> .. warning::
>    This syscall is still under development and may contain security
>    vulnerabilities. This is temporary; the syscall will be enabled in future
> ```

Done.
___
*[`libos/src/bookkeep/libos_handle.c` line 502 at r10](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ7b51w84IlFO_psJDp:-NZ8BcI0BDqFw9bZfOia:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ee9d4ad5cf593c676776df2ad3359b24a1fa0cb0/libos/src/bookkeep/libos_handle.c#L502)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd remove it then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 22:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 11 of 17 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8MrHnA-pyCVnJA9qj:-NZ8MrHnA-pyCVnJA9qk:bo5z4sr) (no related file):*
I did a tentative rebase (squashed all fixup commits and updated to master)

___
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ-wJ_1-CVruSYilf5K):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...cannot be mixed *on the same file*
</blockquote></details>

Done
___
*[`-- commits` line 12 at r9](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ6g1La0pYFfaQH3bPm):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do at final rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 23:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 11 of 17 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8QYrz2A2mSElF-aF1:-NZ8QYs-4RjU8GEFn5KL:b462p5l) (no related file):*
Dump of notes and TODOs for the future:
- Allow mixing POSIX and BSD locks, like Linux does. The two families should basically ignore each other (as if they are acquired on different files). This should be simple to implement, but need to be careful with a "list of locks" -- it will have both, and at least POSIX locks are ordered in that list, so the ordering code should be complicated. Alternatively, we can have two "lists of locks", one for POSIX and one for BSD.
- Fix the problem described in `libos_handle.h`. This will require some sort of system-wide handle refcounting. There's also an interesting asymmetry, which was probably a bad idea after all: `handle_id` is easy to make unique and to inherit, but it's very hard to undo (in the sense of releasing locks implicitly, when handles are closed and processes terminated).
- `clear_flock_locks()` is called on every file-related handle close. This is very expensive, as it sends an IPC message to the leader. There should be optimizations to not send the IPC message. Just imagine a Python workload which opens and closes 1,000s of script files during its execution, each such close sending an IPC message to the leader (which will be most probably useless as there are no flocks on that file).
- Both commands ("acquire shared lock", "acquire exclusive lock", "release lock") and states ("this is an exclusive lock", "this is a shared lock") are represented by the same `libos_file_lock` struct. This is wrong -- they should actually be two different structs. Consider for example `F_UNLCK` -- it is a command only and never a state; this is easily confusing for readers. Also, because we decided to reuse fcntl's `flock` struct and its macros, we end up with bad field names -- the type of the lock is called `family`, whereas the command/state of the lock is called `type`.
- The currently enabled tests are trivial. We need 3-4 powerful tests that will cover complex flows: e.g. a test with 3 processes, where an intermediate process terminates. Or e.g. a test with a complex tree of processes, grabbing and releasing locks on different files. Maybe even a randomized version of such test.
- We may want to revert changes to `libos_ipc_pid.c` which we made to guarantee uniqueness of `handle_id`. This is in case we will replace `handle_id` with something that doesn't require such uniqueness.

___


<!-- Sent from Reviewable.io -->

2023-06-29 23:39 UTC, mkow requested changes
> Reviewed 4 of 13 files at r1, 1 of 4 files at r7, 4 of 8 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`libos/test/regression/flock_lock.c` line 50 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8SQne3RRg11E2wCWH:-NZ8SQne3RRg11E2wCWI:bl0b464) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L50)):*
> ```C
> }
> 
> static void try_flock(int fd, int operation, int expect_ret) {
> ```

ditto in all places below



_Suggestion:_
```C
expected_ret
```
___
*[`libos/test/regression/flock_lock.c` line 60 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8Tg9m3Udgtd1SMa5U:-NZ8Tg9m3Udgtd1SMa5V:bmiuim) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L60)):*
> ```C
> static void try_fcntl(int fd, int operation, int expect_ret, int expect_errno) {
>     struct flock fl = {
>         .l_type = F_RDLCK,
> ```

This should be a parameter of this function, it's a bit weird now.



_Code quote:_
```C
.l_type = F_RDLCK,
```
___
*[`libos/test/regression/flock_lock.c` line 103 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8VRfi0CUAsAHNrrxG:-NZ8VRfi0CUAsAHNrrxH:b-tw0k8v) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L103)):*
> ```C
>     do {
>         ret = read(pipe[0], &c, sizeof(c));
>     } while (ret == -1 && errno == EINTR);
> ```

What's actually causing these EINTRs in these tests? What are this function and the one above actually doing conceptually?


<!-- Sent from Reviewable.io -->

2023-06-30 02:02 UTC, kailun-qin requested changes
> Reviewed 1 of 6 files at r5, 1 of 3 files at r8, 1 of 2 files at r9, 6 of 8 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/include/libos_handle.h` line 151 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8paqU93hAAt-SRtig:-NZ8paqV-ihVmdeQfT6F:b-coapu0) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/include/libos_handle.h#L151)):*
> ```objc
>      *        P2. Unfortunately, Gramine lacks system-wide tracking of handle FDs. We currently err
>      *        on the side of caution and do *not* perform an operation if the process has children;
>      *        this may leak resources or deadlock but at least we don't introduce unsafe behavior.
> ```

Why do we still keep this?



_Code quote:_
```objc
     *        on the side of caution and do *not* perform an operation if the process has children;
     *        this may leak resources or deadlock but at least we don't introduce unsafe behavior.
```


<!-- Sent from Reviewable.io -->

2023-06-30 06:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: 15 of 18 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8MrHnA-pyCVnJA9qj:-NZ9ux6i-F3QILgKsrvj:b-pytink) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I did a tentative rebase (squashed all fixup commits and updated to master)
</blockquote></details>

And rebased again with small fixes.

___
___
*[`libos/include/libos_handle.h` line 151 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8paqU93hAAt-SRtig:-NZ9rsks8OJaumpthgX_:b6buv7n) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/include/libos_handle.h#L151)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why do we still keep this?
</blockquote></details>

Done. Thanks, this was outdated.
___
*[`libos/test/regression/fcntl_lock.c` line 24 at r13](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ9v0D24BBeNuVHzgn4:-NZ9v0D24BBeNuVHzgn5:b-12wfjv) ([raw file](https://github.com/gramineproject/gramine/blob/0665da5e373949043906355866e12cd1b60440b8/libos/test/regression/fcntl_lock.c#L24)):*
> ```C
> #include <unistd.h>
> 
> #include "common.h"
> ```

FYI: modifications to this file are purely for uniformity with `flock_lock.c`
___
*[`libos/test/regression/flock_lock.c` line 50 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8SQne3RRg11E2wCWH:-NZ9sFtVB681uVyfkd3p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto in all places below
</blockquote></details>

Done.
___
*[`libos/test/regression/flock_lock.c` line 60 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8Tg9m3Udgtd1SMa5U:-NZ9sge52z4k9gUp48JT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be a parameter of this function, it's a bit weird now.
</blockquote></details>

Done.
___
*[`libos/test/regression/flock_lock.c` line 103 at r12](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8VRfi0CUAsAHNrrxG:-NZ9ti-l1Q4t3cl2nd-V:beaspma) ([raw file](https://github.com/gramineproject/gramine/blob/6d084a21b8cf46801a0e286a9ea3573554b011d7/libos/test/regression/flock_lock.c#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's actually causing these EINTRs in these tests? What are this function and the one above actually doing conceptually?
</blockquote></details>

Done. You're right, there is no EINTR possible in this test (there are no signal handlers).

I simplified these helper functions. These functions are needed to synchronize several threads or several processes -- e.g. second thread waits on `read_pipe()` until the first thread finishes its stuff, then first thread performs `write_pipe()` to unblock the second thread. So a simple sync primitive.

This was taken from `fcntl_lock.c` test as-is. I changed that other test too, for uniformity.


<!-- Sent from Reviewable.io -->

2023-06-30 07:34 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-30 09:24 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-06-30 10:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1416)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1416#-NZ8QYrz2A2mSElF-aF1:-NZAnT_K6jYRX57v6LaX:b13fz40) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Dump of notes and TODOs for the future:
- Allow mixing POSIX and BSD locks, like Linux does. The two families should basically ignore each other (as if they are acquired on different files). This should be simple to implement, but need to be careful with a "list of locks" -- it will have both, and at least POSIX locks are ordered in that list, so the ordering code should be complicated. Alternatively, we can have two "lists of locks", one for POSIX and one for BSD.
- Fix the problem described in `libos_handle.h`. This will require some sort of system-wide handle refcounting. There's also an interesting asymmetry, which was probably a bad idea after all: `handle_id` is easy to make unique and to inherit, but it's very hard to undo (in the sense of releasing locks implicitly, when handles are closed and processes terminated).
- `clear_flock_locks()` is called on every file-related handle close. This is very expensive, as it sends an IPC message to the leader. There should be optimizations to not send the IPC message. Just imagine a Python workload which opens and closes 1,000s of script files during its execution, each such close sending an IPC message to the leader (which will be most probably useless as there are no flocks on that file).
- Both commands ("acquire shared lock", "acquire exclusive lock", "release lock") and states ("this is an exclusive lock", "this is a shared lock") are represented by the same `libos_file_lock` struct. This is wrong -- they should actually be two different structs. Consider for example `F_UNLCK` -- it is a command only and never a state; this is easily confusing for readers. Also, because we decided to reuse fcntl's `flock` struct and its macros, we end up with bad field names -- the type of the lock is called `family`, whereas the command/state of the lock is called `type`.
- The currently enabled tests are trivial. We need 3-4 powerful tests that will cover complex flows: e.g. a test with 3 processes, where an intermediate process terminates. Or e.g. a test with a complex tree of processes, grabbing and releasing locks on different files. Maybe even a randomized version of such test.
- We may want to revert changes to `libos_ipc_pid.c` which we made to guarantee uniqueness of `handle_id`. This is in case we will replace `handle_id` with something that doesn't require such uniqueness.
</blockquote></details>

Moved these items to a proper GitHub issue: https://github.com/gramineproject/gramine/issues/1433

___


<!-- Sent from Reviewable.io -->

2023-06-30 10:17 UTC, merged