[glibc] Bump version to 2.37
gramineproject/gramine pull request #1419
Opened 2023-06-23 20:30 UTC by mwkmwkmwk

2023-06-23 20:42 UTC, mkow commented
Jenkins, test this please

2023-06-26 01:15 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mwkmwkmwk)

___
*[`subprojects/glibc-2.37-1.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYpCEPM1wwFG7p4NAOe:-NYpCEPM1wwFG7p4NAOf:b3k7dd3) ([raw file](https://github.com/gramineproject/gramine/blob/6aaad47e154bd0787675c950eb2a909aded1ccfe/subprojects/glibc-2.37-1.wrap#L9)):*
> ```
> directory = glibc-2.37-1
> source_url = https://ftp.gnu.org/gnu/glibc/glibc-2.37.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/glibc-2.37.tar.gz
> ```

@woju: Plz upload.


<!-- Sent from Reviewable.io -->

2023-06-26 09:37 UTC, dimakuv commented
I manually checked for all places with `syscall` instruction.

I used this command to filter out clearly-wrong directories and places:
```
grep -rIw --exclude-dir="ChangeLog*" --exclude-dir=support --exclude-dir=mips --exclude-dir=m64k --exclude-dir=ia64 --exclude-dir=csky --exclude-dir=or1k --exclude-dir=nios2 --exclude-dir=loongarch --exclude-dir=s390 --exclude-dir=alpha --exclude-dir=microblaze --exclude-dir=i386 --exclude-dir=arc --exclude-dir=sparc --exclude-dir=riscv --exclude-dir=aarch64 --exclude-dir=arm --exclude-dir=hppa --exclude-dir=powerpc --exclude-dir=benchtests --exclude-dir=manual --exclude-dir=mach --exclude-dir=debug --exclude-dir=m68k syscall | grep -v "#include" 2>&1 | tee syscalls.log
```

Then I manually looked through `syscall.log` resulting file. Here is the list of possible hits, after manual weeding out:
```
sysdeps/x86_64/nptl/tls.h:     asm volatile ("syscall"                            \

sysdeps/unix/syscall.S:SYSCALL (syscall, 1)

sysdeps/unix/sysv/linux/x86_64/getcontext.S:    syscall
sysdeps/unix/sysv/linux/x86_64/getcontext.S:    syscall

sysdeps/unix/sysv/linux/x86_64/x32/times.c:    "syscall\n\t"                            \

sysdeps/unix/sysv/linux/x86_64/vfork.S: syscall

sysdeps/unix/sysv/linux/x86_64/syscall.S:   syscall         /* Do the system call.  */

sysdeps/unix/sysv/linux/x86_64/setcontext.S:    syscall

sysdeps/unix/sysv/linux/x86_64/____longjmp_chk.S:   syscall

sysdeps/unix/sysv/linux/x86_64/clone3.S:    syscall
sysdeps/unix/sysv/linux/x86_64/clone3.S:    syscall

sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall     rcx
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall;
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \

sysdeps/unix/sysv/linux/x86_64/clone.S: syscall
sysdeps/unix/sysv/linux/x86_64/clone.S: syscall

sysdeps/unix/sysv/linux/x86_64/swapcontext.S:   syscall
sysdeps/unix/sysv/linux/x86_64/swapcontext.S:   syscall

sysdeps/unix/sysv/linux/x86_64/__start_context.S:   syscall

sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:   "    syscall\n"                          \

sysdeps/unix/x86_64/sysdep.h:  syscall
```




<!-- Sent from Reviewable.io -->

2023-06-26 09:39 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqnX-TD8mQz7aMDFK7:-NYqnX-TD8mQz7aMDFK8:b-brsbeo) (no related file):*
Here is the list of changes from 2.36: https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=ad5196a5f1f3991624a9a6ebe7fa03f09fdfe5c5;hb=a704fd9a133bfb10510e18702f48a6a9c88dbbd5

From this list, the things  that I found important or interesting:

>   26   CVE-2022-39046: When the syslog function is passed a crafted input
  27   string larger than 1024 bytes, it reads uninitialized memory from the
  28   heap and prints it to the target log file, potentially revealing a
  29   portion of the contents of the heap.

Just for this CVE alone we need to update to this new version of Glibc.

>   86   [29611] string: Optimized AVX2 string functions unconditionally use
  87     BMI2 instructions

This may be interesting for Gramine as it may improve performance of some apps.

>  102   [29864] libc: __libc_start_main() should obtain program headers
 103     address (_dl_phdr) from the auxv, not the ELF header.

This we need to look into. I'm afraid Gramine doesn't provide such a `program headers address` in the auxv. This is our current code: https://github.com/gramineproject/gramine/blob/2ab91453374dc03a444e2940c295560ac9cbf178/libos/src/libos_rtld.c#L1115-L1147

UPDATE: Ok, we're good here:
- https://sourceware.org/bugzilla/show_bug.cgi?id=29864
- https://sourceware.org/bugzilla/attachment.cgi?id=14487&action=diff
- The auxv item is `AT_PHDR` which Gramine does expose (see snippet above)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYr-Fpf62ZdyZGORgXl:-NYr3Ez81dPKrU9aL0dq:b1f6plb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I manually checked for all places with `syscall` instruction.

I used this command to filter out clearly-wrong directories and places:
```
grep -rIw --exclude-dir="ChangeLog*" --exclude-dir=support --exclude-dir=mips --exclude-dir=m64k --exclude-dir=ia64 --exclude-dir=csky --exclude-dir=or1k --exclude-dir=nios2 --exclude-dir=loongarch --exclude-dir=s390 --exclude-dir=alpha --exclude-dir=microblaze --exclude-dir=i386 --exclude-dir=arc --exclude-dir=sparc --exclude-dir=riscv --exclude-dir=aarch64 --exclude-dir=arm --exclude-dir=hppa --exclude-dir=powerpc --exclude-dir=benchtests --exclude-dir=manual --exclude-dir=mach --exclude-dir=debug --exclude-dir=m68k syscall | grep -v "#include" 2>&1 | tee syscalls.log
```

Then I manually looked through `syscall.log` resulting file. Here is the list of possible hits, after manual weeding out:
```
sysdeps/x86_64/nptl/tls.h:     asm volatile ("syscall"                            \

sysdeps/unix/syscall.S:SYSCALL (syscall, 1)

sysdeps/unix/sysv/linux/x86_64/getcontext.S:    syscall
sysdeps/unix/sysv/linux/x86_64/getcontext.S:    syscall

sysdeps/unix/sysv/linux/x86_64/x32/times.c:    "syscall\n\t"                            \

sysdeps/unix/sysv/linux/x86_64/vfork.S: syscall

sysdeps/unix/sysv/linux/x86_64/syscall.S:   syscall         /* Do the system call.  */

sysdeps/unix/sysv/linux/x86_64/setcontext.S:    syscall

sysdeps/unix/sysv/linux/x86_64/____longjmp_chk.S:   syscall

sysdeps/unix/sysv/linux/x86_64/clone3.S:    syscall
sysdeps/unix/sysv/linux/x86_64/clone3.S:    syscall

sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall     rcx
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall;
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \
sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                           \

sysdeps/unix/sysv/linux/x86_64/clone.S: syscall
sysdeps/unix/sysv/linux/x86_64/clone.S: syscall

sysdeps/unix/sysv/linux/x86_64/swapcontext.S:   syscall
sysdeps/unix/sysv/linux/x86_64/swapcontext.S:   syscall

sysdeps/unix/sysv/linux/x86_64/__start_context.S:   syscall

sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:   "    syscall\n"                          \

sysdeps/unix/x86_64/sysdep.h:  syscall
```


</blockquote></details>

Ok, I analyzed all the code places in Glibc and compared with what we have in the patch in this PR. Here are the results:
```
YES: sysdeps/x86_64/nptl/tls.h:     asm volatile ("syscall"                           \

IGNORE: sysdeps/unix/syscall.S:SYSCALL (syscall, 1)

YES: sysdeps/unix/sysv/linux/x86_64/getcontext.S:   syscall
YES: sysdeps/unix/sysv/linux/x86_64/getcontext.S:   syscall

YES: sysdeps/unix/sysv/linux/x86_64/x32/times.c:    "syscall\n\t"                           \

YES: sysdeps/unix/sysv/linux/x86_64/vfork.S:    syscall

YES: sysdeps/unix/sysv/linux/x86_64/syscall.S:  syscall         /* Do the system call.  */

YES: sysdeps/unix/sysv/linux/x86_64/setcontext.S:   syscall

YES: sysdeps/unix/sysv/linux/x86_64/____longjmp_chk.S:  syscall

YES: sysdeps/unix/sysv/linux/x86_64/clone3.S:   syscall
YES: sysdeps/unix/sysv/linux/x86_64/clone3.S:   syscall

IGNORE: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall     rcx
IGNORE: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    syscall;
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
YES: sysdeps/unix/sysv/linux/x86_64/sysdep.h:    "syscall\n\t"                          \
```

So the patch is legit. It doesn't miss any syscalls, with high confidence.

(Interestingly, this looks like the first time I did this analysis for Glibc code. I remember doing the same for Musl, but not for Glibc. Well, now I have confidence in this part.)

___
___
*[`subprojects/packagefiles/glibc-2.37/hp-timing.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqkzBk4kOI0a3zr06R:-NYqkzBk4kOI0a3zr06S:bh7udwu) ([raw file](https://github.com/gramineproject/gramine/blob/6aaad47e154bd0787675c950eb2a909aded1ccfe/subprojects/packagefiles/glibc-2.37/hp-timing.patch#L1)):*
> ```Diff
> diff --git a/sysdeps/x86/hp-timing.h b/sysdeps/x86/hp-timing.h
> ```

Btw, I think we can safely remove this patch (not in this PR, just a note in general).

IIRC, the original idea was in ~2016, when RDTSC instruction was **forbidden** inside SGX enclaves (this was in the very first SGX hardware), and so this patch was used to force Glibc to slow path of calling `gettimeofday()`, which was intercepted by Gramine, and SGX PAL then performed `ocall_gettime()` -- which was faster than a trap-and-emulate behavior of RDTSC.

These days, SGX hardware from maybe ~2020 allows RDTSC instruction inside SGX enclaves, so for simplicity and cleanness we could assume that Gramine runs on rather new SGX hardware (also, we kinda assume it wrt hardware vulnerabilities). In the worst case, Gramine would become slower on old CPUs because it would always trap-and-emulate RDTSC.

On the other hand... In Gramine's inte [...]

2023-06-26 10:14 UTC, kailun-qin approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYr-Fpf62ZdyZGORgXl:-NYrAsB15_zBP4nOqAzO:bqjngtn) (no related file):*
> So the patch is legit. It doesn't miss any syscalls, with high confidence.
> (Interestingly, this looks like the first time I did this analysis for Glibc code. I remember doing the same for Musl, but not for Glibc. Well, now I have confidence in this part.)

I think we have some checks in CI (see https://github.com/gramineproject/gramine/blob/master/.ci/check-no-syscall.sh and https://github.com/gramineproject/gramine/blob/2ab91453374dc03a444e2940c295560ac9cbf178/.ci/lib/stage-test-sgx.jenkinsfile#L3-L7)?

Anyway, it's great that we also double check it manually.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqnX-TD8mQz7aMDFK7:-NYr9rS45luEcIO63VJK:b5rmp7e) (no related file):*
> 86 \[29611\] string: Optimized AVX2 string functions unconditionally use  
> 87 BMI2 instructions
> This may be interesting for Gramine as it may improve performance of some apps.

But this is a more like a compatibility fix rather than a perf fix (see https://sourceware.org/bugzilla/show_bug.cgi?id=29611)?

___
___
*[`subprojects/packagefiles/glibc-2.37/hp-timing.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqkzBk4kOI0a3zr06R:-NYrAk6D8BYSFW7bXJsv:bv0hitm) ([raw file](https://github.com/gramineproject/gramine/blob/6aaad47e154bd0787675c950eb2a909aded1ccfe/subprojects/packagefiles/glibc-2.37/hp-timing.patch#L1)):*
> On the other hand... In Gramine's interception of Glibc `gettimeofday()`, we have a sanitization of RDTSC -- we verify that RDTSC doesn't go backwards in time. If we would remove this patch here, we would lose this sanitization. So maybe we **do** want to keep the patch, for this sanitization reason.

Yep, make sense to me.


<!-- Sent from Reviewable.io -->

2023-06-26 11:27 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`subprojects/packagefiles/glibc-2.37/hp-timing.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqkzBk4kOI0a3zr06R:-NYrS25wDcWP86dVGcOU:b-85ra4j) ([raw file](https://github.com/gramineproject/gramine/blob/6aaad47e154bd0787675c950eb2a909aded1ccfe/subprojects/packagefiles/glibc-2.37/hp-timing.patch#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> On the other hand... In Gramine's interception of Glibc `gettimeofday()`, we have a sanitization of RDTSC -- we verify that RDTSC doesn't go backwards in time. If we would remove this patch here, we would lose this sanitization. So maybe we **do** want to keep the patch, for this sanitization reason.

Yep, make sense to me.
</blockquote></details>

Let's discuss it outside this PR, as we'd like to merge this one now and dropping this change is rather unrelated to the update itself.


<!-- Sent from Reviewable.io -->

2023-06-26 11:52 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-06-26 11:58 UTC, mkow commented
Jenkins, retest this please

2023-06-26 12:03 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1419#-NYqnX-TD8mQz7aMDFK7:-NYr__3oE1r4nZwKkJPL:ble2yh8) (no related file):*
> But this is a more like a compatibility fix rather than a perf fix (see [https://sourceware.org/bugzilla/show\_bug.cgi?id=29611](https://sourceware.org/bugzilla/show_bug.cgi?id=29611))?

True, I misinterpreted the change.

___


<!-- Sent from Reviewable.io -->

2023-06-26 12:09 UTC, kailun-qin approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1419)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-26 12:38 UTC, merged