Add build scripts for Alpine Linux
gramineproject/gramine pull request #1421
Opened 2023-06-27 00:30 UTC by amicrity

## Description of the changes
This PR adds build scripts with patches needed to run Gramine on Alpine Linux.

## Features
Everything works*

*YMMV, some test might still error you out since they usually have to assume a glibc-based host, SGX works only through Docker (for now), glibc apps don't work (and are not going to work; we should respect Alpine community's position on mixing glibc with musl; it is possible to build Gramine with glibc, but it's way more hacky than just running a different distro through chroot or Docker)

## How to test this PR?
NOTE: in order to use SGX, you have to run Docker on a host supported by SGX SDK (such as Ubuntu or Alma) and mount its SGX device to Docker, this changes only if PSW/DCAP gets officially released for musl-based distros.
- create a Docker instance of Alpine 3.18/edge with following flags: `--cap-add SYS_ADMIN --cap-add SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/sgx_enclave`
- add Alpine's main, community and testing repos to /etc/apk/repositories
- install doas, wget, alpine-sdk and perl-utils (and optionally git) through apk
- create a new user and assign it to the `wheel` and the `abuild` group
- remove -Wl,-z,pack-relative-relocs from /usr/share/abuild/default.conf
- pull the /alpine/ folder from this PR
- run `abuild-keygen -a -i`
- run `abuild -r checksum all` - this will compile Gramine from the main branch
- you might see an error `gramine*: ld-linux-x86-64.so.2: path not found`, ignore it
- packages got compiled to `~/packages/`, cd to that directory and install them using `apk`
For tests:
- compile Gramine repo and generate SGX privkey
- modify the example manifest.template from `gramine.runtimedir()` to `gramine.runtimedir(libc='musl')`

For bare metal running Alpine, you should set `-Dsgx=disabled` in the APKBUILD file.

Signed-off-by: Amie Raine <amie@invisiblethingslab.com>

2023-06-27 09:49 UTC, woju requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw9Y0b170EnW02XfNR:-NYw9Y0b170EnW02XfNS:b-dqx3nm) (no related file):*
There needs to be new pipeline which builds this on alpine-edge (probably `.ci/pkg-apk-alpine-edge.jenkinsfile`). Is it in scope for this PR?

___
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NYw9Hyz5913ZI387O9V:be79nd4) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We put all these files under top-level `alpine/`. Is it the same story as with Debian and RHEL-like distros? There Woju insisted that the corresponding files should be put under the top-level directory, otherwise the tools won't work (I still find it bizarre, but I gave up on packaging issues -- everything in that world seems to be a mess).

Otherwise I would put all these files under `packaging/alpine/`.
</blockquote></details>

APKBUILD should be put in toplevel directory, and patches upstreamed (or dropped if the problem was fixed another way).
___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NYw9vGm55UXiIkK4kwy:bs5rioe) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L5)):*
> I don't know how Alpine packages metadata works, so excuse my questions.

Here's the spec for you reference: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference

> Why do we set `0` in these two lines?

For `pkgrel`, same why we have `Release: 1%{?dist}` in spec, because you need to put something there. Debian understands the situation where packaging lives in upstream repo (so called "native" package), so in that case it drops the distinction of version vs release, but most package managers do require something in release field.

For `pkgver` this looks like an attempt to make packages versioned like `0_gitYYYMMDD`, which is common for temporary setups: those versions are 0-ish, so earlier than anything that you'll want to publish, so you don't risk painting yourself into a corner where the package you'd like to publish will sort earlier than you testing version. `pkgver=` should be same as what's in `meson.build` in `project()` (`1.4post~UNRELEASED` at this moment, soon `1.5`) and kept in sync (I'm blocking on this). @amicrity You can add sanity check somewhere in `prepare()`.
___
*[`alpine/APKBUILD` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2bzj6Ad5evdc2c6S:-NYwAgA90JA5czBoeU_-:b-fav7q1) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

(sorting I assume)
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NYwAturAKy5_3EX-c5i:b-hn3o7d) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you explain how to read this string?
</blockquote></details>

As part of packaging (the step that downloads and prepares the source) it downloads right-hand url (`https://github...`) and renames it to `gramine-master-YYYYMMDD.tar.gz` (`YYYYMMDD` being current `date`).

This is wrong for two reasons, 1) we don't want current date anywhere for reproducibility reasons, and 2) this requires Internet connection during builds. IIUC this should be done with `snapshot()` like here: https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Git_checkout, but not with `git archive`, but `meson dist` to create dist tarball. @amicrity see `Scripts/makedist.sh` and either use it directly or patch the problem and then use directly.
___
*[`alpine/APKBUILD` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw35Le9wqpSxM07XWY:-NYwEYXJ1Qh72v1fEsjj:bczeeba) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess ideally, in a follow up PR, we would add a patch with at least a couple tests modified for Musl, and then we could re-add this `check` target?
</blockquote></details>

I'm not sure, if we run tests anyway, then we can run only a simple sanity check here (helloworld maybe)? We have no tests in debian or spec either, because tests run in CI, not in packaging, though some helloworld we surely might add. For now I wouldn't block, but let's wait for @amicrity.
___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NYwFIiFElz5VBOsqxhJ:bwv43o6) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L71)):*
> ```abuild
> 	
> 	mbedtls_ver="$(cat meson.build | grep 'mbedtls_proj = ' | sed "s/.*mbedtls-//;;s/'.*//")"
> 	sed -i "s/Version: undefined/Version: $mbedtls_ver/" "$pkgdir"/usr/lib/pkgconfig/mbedtls_gramine.pc
> ```

How this `.pc` is created? It probably should be fixed in meson.build in subproject.
___
*[`alpine/APKBUILD` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3S812JfDphvb_2JZ:-NYw8vrL-L1MtQuLfrDL:b-fr45uv) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/APKBUILD#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is something new... Shouldn't we have the same for Debian and RHEL?
</blockquote></details>

This sed is invalid. The package vesion should be the same everywhere (incl. pkg-config files).
___
*[`alpine/mbedtls.patch` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3kC41dW-wXabt5Mu:-NYwD5rBEOtVCmczcA8e:b-q063qa) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/mbedtls.patch#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have three PRs that suggest different fixes to this problem, and then this patch won't be needed:
- https://github.com/gramineproject/gramine/pull/1400
- https://github.com/gramineproject/gramine/pull/1417
- https://github.com/gramineproject/gramine/pull/1420

I'm fine with having this patch for now, but in the long term, we should fix the root cause problem, not apply the patch here.
</blockquote></details>

I'm not fine at all, I don't want random patches unless absolutely necessary for technical reasons. Here we should fix the underlying problem "upstream", i.e. in the repo proper, not as patch. At worst in `meson.build` we can add a switch (two of @dimakuv's proposals do this) and in `.c`/`.h` at worst we can add `#ifdef`.
___
*[`alpine/sysinfo.patch` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw4CWp2NOCz1Sym4Bg:-NYw8ZQb4xe4IMYcf-Dc:b-vbjl7s) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/sysinfo.patch#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a hack, but I don't care for now. We will replace these host-level headers wi [...]

2023-06-27 12:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @woju)

___
*[`alpine/sysinfo.patch` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw4CWp2NOCz1Sym4Bg:-NYwmvoMCBBkc1P9glUE:b-jdg2r7) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/sysinfo.patch#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I think this header breaks compilation on Glibc (because of redefinition).

The root cause is `struct sysinfo` which is found in `sys/sysinfo.h` Musl header, but in Glibc it is found... well, somewhere else, I didn't go that deep.

So I like the https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerhas_header_symbol way of doing it: it will check if `struct sysinfo` exists, and if not, we can add it here.

Alternatively, one needs to understand why Glibc has `struct sysinfo` and where, and maybe add some ifdef magic to distinguish glibc vs musl.
</blockquote></details>

Let me try to quickly fix this as a continuation of #1275 and #1301.


<!-- Sent from Reviewable.io -->

2023-06-28 14:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)

___
*[`alpine/sysinfo.patch` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw4CWp2NOCz1Sym4Bg:-NZ1OL__5KjkNrQKI7E9:b-o8428c) ([raw file](https://github.com/gramineproject/gramine/blob/f082068b17467eb6b85b5c34b2ff3d8842fc69ce/alpine/sysinfo.patch#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let me try to quickly fix this as a continuation of #1275 and #1301.
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/1426


<!-- Sent from Reviewable.io -->

2023-06-29 09:38 UTC, amicrity reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: 1 of 3 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYvzxnz8jHf08BCP19J:-NZ5LOY44_SmW2xYBXVo:b-y52a7z) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@amicrity Could you add more details in the PR description? At least I will probably use the PR description as the reference point, so it should be as clear as possible.

> pull the /alpine/ folder from this PR

Pull to where? It doesn't matter? Or in the root dir of the Alpine Docker container?

Also, by "pull" do you mean "copy"?

> you might see an error `gramine*: ld-linux-x86-64.so.2: path not found`, ignore it

Do you know why this error happens? Why does Gramine build require a dynamic linker, and why it can be ignored?

> For tests:

This is not rendered as you expect.

> compile Gramine repo and generate SGX privkey

What do you mean by "compile Gramine repo"? Didn't you already build and install Gramine in the previous steps? Why compile it again?

> modify the example manifest.template from `gramine.runtimedir()` to `gramine.runtimedir(libc='musl')`

Which example manifest? Do you mean `Helloworld`? Because many example manifests, e.g. Python and Blender, will surely need more changes that this one.

> For bare metal running Alpine, you should set `-Dsgx=disabled` in the APKBUILD file.

Why? Why we can build Gramine with SGX enabled inside the Docker container, but cannot do the same outside? Is it because `this changes only if PSW/DCAP gets officially released for musl-based distros`? But then this also applies to Docker environment, so I don't see a difference...
</blockquote></details>

will do the changes in PR description
about the error, it happens because we're building gramine against musl entirely with no glibc in place
and about the last one, we can do the same outside but it's not a good practice (we'd be building gramine targeted for something that doesn't even exist yet), although i can live with that

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw9Y0b170EnW02XfNR:-NZ5N09035bUvMLpNp0L:b-gwyoix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There needs to be new pipeline which builds this on alpine-edge (probably `.ci/pkg-apk-alpine-edge.jenkinsfile`). Is it in scope for this PR?
</blockquote></details>

can be, will try adding to this PR

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYweJlC5ltJ4D1NuwhU:-NZ5NEb5Ekg--_vyKX_k:b-h9mv8p) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> we should respect Alpine community's position on mixing glibc with musl

But their position can only matter on what we link against on the host, it should have no bearing on what we run _inside_ Gramine. Think of Gramine same as of a VM.

I get the technical problems with building glibc, it's mostly a mixture of glibc being terribly written and C building ecosystem being crap, but design-wise what we support inside Gramine should be independent from the host.
</blockquote></details>

of course, but building glibc on alpine in order to build gramine not only is not upstreamable (ie, it's a huge mess and replacing alpine with for example wolfi works a lot better), but also violates most of the good practices

as long as we have to build glibc, it has no place on a musl-based host, however please let me know if the words i used in the description are misleading

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0kyA8JHntbiWPj6c):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We use `[packaging]` prefix for such commits. I think we want to use it here as well.
</blockquote></details>

will do
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NYwCn471zk1vSPcJB_8:bycveb1) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> APKBUILD should be put in toplevel directory

Why?

I'm strongly against this, as you may have already guessed.
</blockquote></details>

i really dislike the idea of putting it in the toplevel dir, can change the directory from /alpine/ to /packaging/alpine
___
*[`alpine/APKBUILD` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1nVo6C2qz3WNWTEj:-NYwDM3s0wF8grtY8col:b-d7bhn0) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not our usual string: https://github.com/gramineproject/gramine/blob/0684091aa1c95497f24dab9a060307b86fe3a713/gramine.spec#L7
</blockquote></details>

will do
___
*[`alpine/APKBUILD` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1rzx9sR1liTAwink:-NZ5QGHi5uLfxHvpOkgN:b-esi2hz) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess because it's too outdated, I prefer linking to the repo.
</blockquote></details>

I prefer linking directly to the repo instead of the (outdated) project site, can change if really needed, but I think it is better like that
___
*[`alpine/APKBUILD` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1ukD83uzFRGbcpNL:-NZ5QSdO5iVXrSpfopCt:b-d7bhn0) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not https://github.com/gramineproject/gramine/blob/0684091aa1c95497f24dab9a060307b86fe3a713/gramine.spec#L10

We don't officially support anything other than x86-64
</blockquote></details>

will do
___
*[`alpine/APKBUILD` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1ywBB9cuSEUssqrw:-NZ5QUV17tetrLAZT8hN:b-i0k4ks) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `only`? See https://github.com/gramineproject/gramine/blob/0684091aa1c95497f24dab9a060307b86fe3a713/gramine.spec#L8
</blockquote></details>

will do, didn't notice
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZ5QXvN0kSWCWYLUyfW:b-unmt1f) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no ninja for Alpine? Why samurai instead?
</blockquote></details>

will remove the dependency since meson itself has a hard depencency on samurai

why samurai? `ninja` is used as an alias for `samurai` on abuild and alpine community only wants samurai for aports (the only package containing actual ninja is unpathed `ninja-build`, `ninja` also conflicts with `samurai`)
___
*[`alpine/APKBUILD` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2AsNEC3euSHvNFwV:-NYwEfllClJY2A_BKJGJ:b-i4kvp) ([raw file](https://github.com/gramineproject/gramine/blob [...]

2023-06-29 11:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: 1 of 3 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @woju)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZ5x5kQ5uPrurnrVz1P:b-5bq97c) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

i really dislike the idea of putting it in the toplevel dir, can change the directory from /alpine/ to /packaging/alpine
</blockquote></details>

Please do it then :)
There was a lot of changes to the PR, including commit messages, so IMO it's ok if you rebase on master, clean up the commits and force-push it now.


<!-- Sent from Reviewable.io -->

2023-06-29 11:51 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYvzxnz8jHf08BCP19J:-NZ5rcF8ChxlufOsC0Qm:b-s0l775) (no related file):*
> about the error, it happens because we're building gramine against musl entirely with no glibc in place

Sure, but which part of the build process even looks for `ld-linux-x86-64.so.2`? When I was building Gramine under Alpine just yesterday, I didn't see any such warnings/errors.

> and about the last one, we can do the same outside but it's not a good practice (we'd be building gramine targeted for something that doesn't even exist yet), although i can live with that

I don't understand the difference between:
- building "Gramine targeted for something that doesn't exist yet" inside the Alpine Docker container, and
- building "Gramine targeted for something that doesn't exist yet" on bare metal Alpine.

Why is the first a good practice, and the second is a bad practice? There's no TODO here, I just want to understand the reasoning.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYweJlC5ltJ4D1NuwhU:-NZ5sr0k1qEfsay1fcaD:b-m3alyz) (no related file):*
> But their position can only matter on what we link against on the host, it should have no bearing on what we run _inside_ Gramine. Think of Gramine same as of a VM.

Yes, I agree with @mkow.

An analogy would be if Alpine would explicitly disallow building an initramfs with Glibc inside, for further use inside a guest VM. (I don't know, maybe Alpine indeed doesn't allow it, or it's such a pain to do it that Alpine is never used for such VM-creation tasks.)

Anyway, off-topic.

___
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZ5t_r9DMWVim8IlWqv:bp7llnx) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

i really dislike the idea of putting it in the toplevel dir, can change the directory from /alpine/ to /packaging/alpine
</blockquote></details>

I don't mind any solution here. I'm very far away from packaging, so whatever other maintainers agree upon.
___
*[`alpine/APKBUILD` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1rzx9sR1liTAwink:-NZ5trzV-MvkirquogsM:b32w1t) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L8)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

I prefer linking directly to the repo instead of the (outdated) project site, can change if really needed, but I think it is better like that
</blockquote></details>

Ok
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZ5u-3k9Gl79SIaPz3m:bkin52j) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will remove the dependency since meson itself has a hard depencency on samurai

why samurai? `ninja` is used as an alias for `samurai` on abuild and alpine community only wants samurai for aports (the only package containing actual ninja is unpathed `ninja-build`, `ninja` also conflicts with `samurai`)
</blockquote></details>

Thanks for explanations.
___
*[`alpine/APKBUILD` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2AsNEC3euSHvNFwV:-NZ5zLh0BirmhF7dSpko:bh2geo1) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L29)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

i couldn't build without it, i'll retry to provide you with logs
</blockquote></details>

Well, whatever, this is not important anyway. If you know that this package is required (for whatever reason), that's enough for me. I'm unblocking.
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NZ5uD2J16x25qeoYm4H:b-d6yhqr) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

can do commit hash instead, but it'll be a huge, huge pain (it's a build system, not a CI)

yeah, it does require internet connection, just like downloading the dependencies or even building gramine itself (we literally download stuff with wget while building)
there is a reason no one uses `snapshot()`, but if it's really needed then sure
</blockquote></details>

I'm fine with the explanations, thanks. I'm unblocking.
___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NZ5yfMI-2DXXUMXXbXq:b-e3oncb) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L71)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

you're the dev here @woju ;p
</blockquote></details>

I created a PR: https://github.com/gramineproject/gramine/pull/1430. @woju Is this what you'd expect?
___
*[`alpine/APKBUILD` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3S812JfDphvb_2JZ:-NZ5ypeXABi-eJ_awv0R:b7arebs) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L73)):*
> but abuild breaks when i do it in any different way

What does it mean exactly? Why `post~UNRELEASED` suffix is bad for abuild?
___
*[`alpine/APKBUILD` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3_Gu1--00CxQon5a:-NZ5z26c8M3h-dIOrBxa:b-r4nlw9) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L77)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

assuming we'll be doing `abuild -r checksum all` i can possibly remove it, will check

abuild requires the filehashes, hence why they are here
</blockquote></details>

But we'll have to update this date every time? I don't understand.
___
*[`alpine/mbedtls.patch` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3kC41dW-wXabt5Mu:-NZ5z8Sj5lEieZbrcrJV:b-lly60r) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/mbedtls.patch#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to what @woju said.
</blockquote></details>

This patch will be removed when we merge this PR: https://github.com/gramineproject/gramine/pull/1427


<!-- Sent from Reviewable.io -->

2023-06-30 04:05 UTC, kailun-qin reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2023-06-30 13:09 UTC, woju requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZBMGDS2vvkQD8AOiGR:b-5cl1ja) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't mind any solution here. I'm very far away from packaging, so whatever other maintainers agree upon.
</blockquote></details>

I prefer that you can `cd` to toplevel repo directory and issue packaging commands from there. Packagers don't want to look for some non-standard subdirectories.

So if this works:

```
git clone https://github.com/gramineproject/gramine
cd gramine
abuild ...
```

Then OK. If instead you need to `cd gramine/packaging/alpine` then no.
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZBNE488TGZEDmlb6mY:bwxabfn) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for explanations.
</blockquote></details>

`samurai` is in meson's dependencies, and you don't invoke it directly, but via `meson compile`, so technically you don't care about this. You can just remove it.
___
*[`alpine/APKBUILD` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2AsNEC3euSHvNFwV:-NZBNS8k-2PPPESQldxP:b-f6ojkh) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, whatever, this is not important anyway. If you know that this package is required (for whatever reason), that's enough for me. I'm unblocking.
</blockquote></details>

Please do provide logs, it might an upstream bug that was not caught elsewhere and we might want to fix it in other packaging dependencies.
___
*[`alpine/APKBUILD` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2kn-7smSx1ZHCxs2:-NZBNePb8q-njS2olPIO:b-y8r4fq) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L41)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

looks like required by an another dependency, doesn't need to be here
</blockquote></details>

We don't use protobuf from python anymore (only on OOT, which is not packaged). So this is correct. If we have `python3-protobuf` elsewhere, we need to remove it.
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NZBOCVa730NS0bpV6LR:b-eyaskf) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with the explanations, thanks. I'm unblocking.
</blockquote></details>

No, this is wrong. This packaging should build repo as is, from HEAD. You might need to commit all the changes, but there shouldn't be any requirements to push to GitHub first (and certainly not to the main repo). What's wrong with `snapshot()` exactly?
___
*[`alpine/APKBUILD` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw35Le9wqpSxM07XWY:-NZBOkkO74LoeeuWevwJ:b-k3ahrf) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L50)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

tests in gramine used to make a huge mess (especially since we have 3 different directories with tests with 3 different ways of running them), can be just `helloworld`
</blockquote></details>

Yes, `helloworld` in packaging will be enough, but it doesn't need to be part of this PR.
___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NZBOydM-O3IIDFZAJEQ:b-rjci4q) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I created a PR: https://github.com/gramineproject/gramine/pull/1430. @woju Is this what you'd expect?
</blockquote></details>

Something like that, but needs to carry mbedtls' version. I've commented there.

(Keeping this blocked until this snippet here will be adjusted.)
___
*[`alpine/APKBUILD` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3S812JfDphvb_2JZ:-NZBJtjb-HLKmzi20FR6:beiqfsl) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> but abuild breaks when i do it in any different way

What does it mean exactly? Why `post~UNRELEASED` suffix is bad for abuild?
</blockquote></details>

"Semantic versioning" as defined by javascript developers is insufficient, because we need -rc versions, which are effectively less than zero. In upstream Gramine we use versions compatible with both [Debian](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version) ([example](https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#name-version)) and [RPM](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_handling_non_sorting_versions_with_tilde_dot_and_caret), that is, we can use `~`.

How exactly abuild breaks on this?


<!-- Sent from Reviewable.io -->

2023-06-30 13:22 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @woju)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZBSKTA4fp85gSxLROV:b-e5894z) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I prefer that you can `cd` to toplevel repo directory and issue packaging commands from there. Packagers don't want to look for some non-standard subdirectories.

So if this works:

```
git clone https://github.com/gramineproject/gramine
cd gramine
abuild ...
```

Then OK. If instead you need to `cd gramine/packaging/alpine` then no.
</blockquote></details>

I'm strongly against having a top-level directory for each supported distro, this makes a huge mess from our repo. And all of this just so that people won't need to `cd`? (and we don't even have too many such people right now, I haven't heard about anyone other than us building our packages manually, people either use the released packages or build from sources using Meson)


<!-- Sent from Reviewable.io -->

2023-06-30 14:04 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZBbGXj8YDc2aa_h0cM:bsjf6ko) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm strongly against having a top-level directory for each supported distro, this makes a huge mess from our repo. And all of this just so that people won't need to `cd`? (and we don't even have too many such people right now, I haven't heard about anyone other than us building our packages manually, people either use the released packages or build from sources using Meson)
</blockquote></details>

https://github.com/gramineproject/gramine/issues/153#issuecomment-1442189616 is one example.

IIUC this won't be directory, but just `APKBUILD` file.


<!-- Sent from Reviewable.io -->

2023-06-30 14:29 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)

___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NZBgy-20S0OHp5zt7tI:b-hv0e59) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/APKBUILD#L71)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Something like that, but needs to carry mbedtls' version. I've commented there.

(Keeping this blocked until this snippet here will be adjusted.)
</blockquote></details>

I adjusted my PR. But we need to merge it first, then change this code snippet here, so let me also block.
___
*[`alpine/mbedtls.patch` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3kC41dW-wXabt5Mu:-NZBhF2mC04jtZujYzwS:bhhyy97) ([raw file](https://github.com/gramineproject/gramine/blob/13438b5a2c013d61a14a94d1204d7f49c05afa5b/alpine/mbedtls.patch#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This patch will be removed when we merge this PR: https://github.com/gramineproject/gramine/pull/1427
</blockquote></details>

The PR was removed, this whole patch can be removed.


<!-- Sent from Reviewable.io -->

2023-06-30 15:45 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)

___
*[`alpine/APKBUILD` line 45 at r3](https://reviewable.io/reviews/gramineproject/gramine/1421#-NZByibwAAe35Vsa0mZM:-NZByibwAAe35Vsa0mZN:bjxd7sb) ([raw file](https://github.com/gramineproject/gramine/blob/06249676d9d5179b52930cebe9ad37761253dca1/alpine/APKBUILD#L45)):*
> ```abuild
> source="
> 	gramine-master-$(date "+%Y%m%d").tar.gz::https://github.com/gramineproject/gramine/archive/$_commit.tar.gz
> 	mbedtls.patch
> ```

You still have `mbedtls.patch` here
___
*[`alpine/APKBUILD` line 77 at r3](https://reviewable.io/reviews/gramineproject/gramine/1421#-NZByfrQ9b_bda5uggj5:-NZByfrQ9b_bda5uggj6:bjxd7sb) ([raw file](https://github.com/gramineproject/gramine/blob/06249676d9d5179b52930cebe9ad37761253dca1/alpine/APKBUILD#L77)):*
> ```abuild
> sha512sums="
> efae80296f696426e31363b743901efcca54a32bd10efb859218145fe609f6ceed7027cabec2456f408a967fc7d81b03f3aae7fd1cc27aa9c184611cf0713e37  gramine-master-20230619.tar.gz
> 2cbcfa6cbe70a92100fdb8f4f169b4aef4aca04dc8d1cdf9987efb91948826ec6b885de3e066499aa7f1e1ac09b503716dc945c96a33df186b551d47c8557a12  mbedtls.patch
> ```

You still have `mbedtls.patch` here


<!-- Sent from Reviewable.io -->

2023-06-30 15:50 UTC, amicrity commented
yeah, i didn't finish yet ;p
i'm testing an apkbuild with all the suggestions mentioned earlier and it'll be the final version relying on `master`

2023-07-02 13:37 UTC, amicrity reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: 2 of 3 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYvzxnz8jHf08BCP19J:-NZLmyvo3cCjPnbhQ0zc:bzh5zn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> about the error, it happens because we're building gramine against musl entirely with no glibc in place

Sure, but which part of the build process even looks for `ld-linux-x86-64.so.2`? When I was building Gramine under Alpine just yesterday, I didn't see any such warnings/errors.

> and about the last one, we can do the same outside but it's not a good practice (we'd be building gramine targeted for something that doesn't even exist yet), although i can live with that

I don't understand the difference between:
- building "Gramine targeted for something that doesn't exist yet" inside the Alpine Docker container, and
- building "Gramine targeted for something that doesn't exist yet" on bare metal Alpine.

Why is the first a good practice, and the second is a bad practice? There's no TODO here, I just want to understand the reasoning.
</blockquote></details>

Looks like it's good when building without glibc ;3

The first is a good practice since we can use SGX on Docker (as long as the host is supported)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw9Y0b170EnW02XfNR:-NZLnDtcDU2Vq64WZzGu:b-ob1grq) (no related file):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

can be, will try adding to this PR
</blockquote></details>

follow up, can we actually (please) split this change to a new PR?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0kyA8JHntbiWPj6c):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`alpine/mbedtls.patch` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3kC41dW-wXabt5Mu:-NZLoXjx7_6ib199P5i_:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/mbedtls.patch#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR was removed, this whole patch can be removed.
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZLnfry1lv3ycXbZFU3:b-535ub6) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/issues/153#issuecomment-1442189616 is one example.

IIUC this won't be directory, but just `APKBUILD` file.
</blockquote></details>

done ;p
___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NZLno7Z2eSm9SCSlvjL:b-d7bhn0) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I don't know how Alpine packages metadata works, so excuse my questions.

Here's the spec for you reference: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference

> Why do we set `0` in these two lines?

For `pkgrel`, same why we have `Release: 1%{?dist}` in spec, because you need to put something there. Debian understands the situation where packaging lives in upstream repo (so called "native" package), so in that case it drops the distinction of version vs release, but most package managers do require something in release field.

For `pkgver` this looks like an attempt to make packages versioned like `0_gitYYYMMDD`, which is common for temporary setups: those versions are 0-ish, so earlier than anything that you'll want to publish, so you don't risk painting yourself into a corner where the package you'd like to publish will sort earlier than you testing version. `pkgver=` should be same as what's in `meson.build` in `project()` (`1.4post~UNRELEASED` at this moment, soon `1.5`) and kept in sync (I'm blocking on this). @amicrity You can add sanity check somewhere in `prepare()`.
</blockquote></details>

will do
___
*[`alpine/APKBUILD` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1nVo6C2qz3WNWTEj:-NZLnrDLCf7So-dySh9e:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L7)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1ukD83uzFRGbcpNL:-NZLnuFP2rl808EVjo0s:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L9)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1ywBB9cuSEUssqrw:-NZLnv8f4BKq5szLJLL2:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L10)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do, didn't notice
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZLnxPT8e4B9OHD2gBH:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`samurai` is in meson's dependencies, and you don't invoke it directly, but via `meson compile`, so technically you don't care about this. You can just remove it.
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2AsNEC3euSHvNFwV:-NZLnzYvATvZ_ejB_HKk:b-dmv2i1) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L29)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please do provide logs, it might an upstream bug that was not caught elsewhere and we might want to fix it in other packaging dependencies.
</blockquote></details>

done, it seems to not crash anymore
___
*[`alpine/APKBUILD` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2YORAeh1Xunp10mo:-NZLo7OV2JDOZwv43t8G:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L34)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2bzj6Ad5evdc2c6S:-NZLo9tL0QbDfmOAbbN-:bb7f2mf) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L42)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`alpine/APKBUILD` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3_Gu1--00CxQon5a:-NZLoJ2VAWoyIFPAnEHn:b-vkhzt1) ([raw file](https://github.com/gram [...]

2023-07-02 13:41 UTC, amicrity reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: 2 of 3 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NZLpTdb7X_PkVy5TjsW:bgvs53f) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I adjusted my PR. But we need to merge it first, then change this code snippet here, so let me also block.
</blockquote></details>

will do?


<!-- Sent from Reviewable.io -->

2023-07-02 13:43 UTC, amicrity commented
@woju @dimakuv @mkow does this APKBUILD look good enough?

I will also implement snapshot(), fix the versioning (since I see it's done properly now) and answer some leftover questions, the final version will be dropped to master instead of a branch with all the commits cleaned up

2023-07-02 17:26 UTC, dimakuv requested changes
> does this APKBUILD look good enough?

Looks good to me, bar the not-yet-finished comments.

> the final version will be dropped to master instead of a branch

I don't understand what this sentence means...

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421#-:-NZMbvw89tuHNtYK17fo:bj98bln)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @mkow, and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0kyA8JHntbiWPj6c):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done where? I don't see a difference.


<!-- Sent from Reviewable.io -->

2023-07-02 17:39 UTC, amicrity reviewed
honestly i don't know what I meant by that too ;p
in other words, I'll rebase on `master`, clean up lots of unnecessary commits and force-push it once ready

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421#-:-NZMeI3pDVhAdxnVqlNz:b-lzgqge)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0kyA8JHntbiWPj6c):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done where? I don't see a difference.
</blockquote></details>

oh, the main commit i see, i'll be dropping the whole branch once we come to an agreement on releasing it (so the issue will be irrelevant)


<!-- Sent from Reviewable.io -->

2023-07-03 00:53 UTC, mkow requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @woju)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZOD4Wp6Wp-EmjmsoMG:bhxnjd6) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

done ;p
</blockquote></details>

I'd prefer `packaging/alpine/`, "APKBUILD" doesn't say much for someone who never used Alpine. I'd like to have a clear structure "packaging/<distro_or_pkg_format>/".
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZOC_Wr5sypdx9wdIqW:btcdyqb) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L14)):*
> you don't invoke it directly, but via `meson compile`, so technically you don't care about this

We do run `ninja` manually. First, our building instructions asks to invoke `ninja` directly, second, see `python/graminelibos/util_tests.py`.
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NZODces2q3T0r8fq0se:b-axdmd0) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is wrong. This packaging should build repo as is, from HEAD. You might need to commit all the changes, but there shouldn't be any requirements to push to GitHub first (and certainly not to the main repo). What's wrong with `snapshot()` exactly?
</blockquote></details>

I agree with @woju, this seems super contrived now. If I check out `mkow/asdf` and then run the package build here I expect to get packages for `mkow/asdf`, not for `master`.


<!-- Sent from Reviewable.io -->

2023-07-03 01:01 UTC, kailun-qin reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @woju)



<!-- Sent from Reviewable.io -->

2023-07-04 09:20 UTC, woju requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw9Y0b170EnW02XfNR:-NZVBVzP4XgrFoKUMfsa:b-5z70lx) (no related file):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

follow up, can we actually (please) split this change to a new PR?
</blockquote></details>

Why we would want to separate those changes? We usually merge changes with their tests as 1 PR (either single commit or next commit in the same branch).

___
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZV64yeAXpkD0HCrY0s:b1vt154) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `packaging/alpine/`, "APKBUILD" doesn't say much for someone who never used Alpine. I'd like to have a clear structure "packaging/<distro_or_pkg_format>/".
</blockquote></details>

`packaging/APKBUILD` is correct, because:

1) Everyone [who cares about building for particular distro] knows what file (or directory) does s/he want.
2) Some of packaging formats are for multiple distros (`debian/` is for Debian, Ubuntu, Mint and others), often vastly different, like RPM's `.spec`, which is for both RedHat family (Fedora, CentOS Stream, RHEL, AlmaLinux etc.), for SUSE family and also you may try yet different distro like PLD which btw still lives. So there's not really anything that you can put as directory name.
3) Most package managers want a file, not a directory. `debian/` is kinda outlier (for techno-organisational reasons, i.e. their tooling and approach of many small tools and many config files reflects very loose organisation of the Debian Project), and Docker is also special, because it has "context", which is mostly implied by other tools to be root of repo or tarball.
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZV7lPB1WrFKiBmKNz_:b-psiv9z) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> you don't invoke it directly, but via `meson compile`, so technically you don't care about this

We do run `ninja` manually. First, our building instructions asks to invoke `ninja` directly, second, see `python/graminelibos/util_tests.py`.
</blockquote></details>

Not in this file. `makedepends=` apply only to this file, and if you don't invoke `ninja` directly in this script, it's perfectly fine to omit it. Building instructions are only guidelines and don't matter here.

It would matter if you wanted to rely on specific version though (like `ninja >= 1.10`), but I haven't seen this here.
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NZVAQiR83hYIuOy0Rmq:b-y0kd8n) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I agree with @woju, this seems super contrived now. If I check out `mkow/asdf` and then run the package build here I expect to get packages for `mkow/asdf`, not for `master`.
</blockquote></details>

Yep, and not even from my HEAD of `master`, but GitHub's. That's even worse to explain.


<!-- Sent from Reviewable.io -->

2023-07-04 13:18 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NZW-F2_4pgrekSLLPvQ:bkurvgv) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L5)):*
OK, I've found the issue:

```
>>> gramine: Building gramine/gramine 1.4post~UNRELEASED-r0 (using abuild 3.10.0-r0) started Tue, 04 Jul 2023 12:55:44 +0000
>>> gramine: Checking sanity of /gramine/packaging/APKBUILD...
>>> ERROR: gramine: 1.4post~UNRELEASED is not a valid version
```

So apk seems to require quite strict version format (https://wiki.alpinelinux.org/wiki/APKBUILD_Reference, `^F pkgver`; https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/23be7e321009b5c524ebb06746219760d9b40b6a/src/version.c).

There are some rules as to what can come after what, notably:
1. no `'~'` allowed, but there's `_rc#` suffix allowed, so that we can live with;
2. only lowercase letters allowed
3. after a letter, there needs to be a digit (if anything)

So unless I'm missing something, for 2. and 3., if we want to write "UNRELEASED" somewhere in the version, it needs to be `u0n0r0e0l0e0a0s0e0d`, and needs to come before `_suffix`.

```
# apk version --check 1.4u0n0r0e0l0e0a0s0e0d_p; echo $?
0
# apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.4
>
/gramine/packaging # apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.5_rc1
<
/gramine/packaging # apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.5
<
```

So let it be that way.


<!-- Sent from Reviewable.io -->

2023-07-04 13:19 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NZW2cSMBoLDtON-9C_o:bqqizn2) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, I've found the issue:

```
>>> gramine: Building gramine/gramine 1.4post~UNRELEASED-r0 (using abuild 3.10.0-r0) started Tue, 04 Jul 2023 12:55:44 +0000
>>> gramine: Checking sanity of /gramine/packaging/APKBUILD...
>>> ERROR: gramine: 1.4post~UNRELEASED is not a valid version
```

So apk seems to require quite strict version format (https://wiki.alpinelinux.org/wiki/APKBUILD_Reference, `^F pkgver`; https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/23be7e321009b5c524ebb06746219760d9b40b6a/src/version.c).

There are some rules as to what can come after what, notably:
1. no `'~'` allowed, but there's `_rc#` suffix allowed, so that we can live with;
2. only lowercase letters allowed
3. after a letter, there needs to be a digit (if anything)

So unless I'm missing something, for 2. and 3., if we want to write "UNRELEASED" somewhere in the version, it needs to be `u0n0r0e0l0e0a0s0e0d`, and needs to come before `_suffix`.

```
# apk version --check 1.4u0n0r0e0l0e0a0s0e0d_p; echo $?
0
# apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.4
>
/gramine/packaging # apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.5_rc1
<
/gramine/packaging # apk version --test 1.4u0n0r0e0l0e0a0s0e0d_p 1.5
<
```

So let it be that way.
</blockquote></details>

Oh, `1.4.u0n0r0e0l0e0a0s0e0d_p` seems to be also acceptable, and slightly more readable.


<!-- Sent from Reviewable.io -->

2023-07-04 13:56 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NZWArOp1TRdoSbscqwH:b98oyp) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh, `1.4.u0n0r0e0l0e0a0s0e0d_p` seems to be also acceptable, and slightly more readable.
</blockquote></details>

Oh x2, and you cannot put a git commit there. Because what if you have two hex digits > A one after another.

What a poor package manager.


<!-- Sent from Reviewable.io -->

2023-07-04 14:55 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZWOKMRDnmER9KwXyDe:b-9bjq04) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`packaging/APKBUILD` is correct, because:

1) Everyone [who cares about building for particular distro] knows what file (or directory) does s/he want.
2) Some of packaging formats are for multiple distros (`debian/` is for Debian, Ubuntu, Mint and others), often vastly different, like RPM's `.spec`, which is for both RedHat family (Fedora, CentOS Stream, RHEL, AlmaLinux etc.), for SUSE family and also you may try yet different distro like PLD which btw still lives. So there's not really anything that you can put as directory name.
3) Most package managers want a file, not a directory. `debian/` is kinda outlier (for techno-organisational reasons, i.e. their tooling and approach of many small tools and many config files reflects very loose organisation of the Debian Project), and Docker is also special, because it has "context", which is mostly implied by other tools to be root of repo or tarball.
</blockquote></details>

Looks like `packaging/alpine/APKBUILD` will be better, because `abuild` creates some files in `.` (like `$srcdir`), so this could use `.gitconfig`. So that would be the second file, so subdirectory is actually called for. @mkow is right here.


<!-- Sent from Reviewable.io -->

2023-07-04 17:28 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1421)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amicrity, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYvzxnz8jHf08BCP19J:-NZWwamODJu6TaktxNou:brfnsh7) (no related file):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

Looks like it's good when building without glibc ;3

The first is a good practice since we can use SGX on Docker (as long as the host is supported)
</blockquote></details>

IDK what's actionable in this thread, can you please come to #1439 and comment if there's anything left to do?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw9Y0b170EnW02XfNR:-NZWr8Q60BV8jaMIFe3V:b-i7771y) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why we would want to separate those changes? We usually merge changes with their tests as 1 PR (either single commit or next commit in the same branch).
</blockquote></details>

Done in #1439

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0kyA8JHntbiWPj6c):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

oh, the main commit i see, i'll be dropping the whole branch once we come to an agreement on releasing it (so the issue will be irrelevant)
</blockquote></details>

Done in #1439
___
*[`alpine/APKBUILD` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw1AYE62-2l-PlCiIg:-NZWrG4MD0EhS1sBwfEN:b-i7771y) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Looks like `packaging/alpine/APKBUILD` will be better, because `abuild` creates some files in `.` (like `$srcdir`), so this could use `.gitconfig`. So that would be the second file, so subdirectory is actually called for. @mkow is right here.
</blockquote></details>

Done in #1439
___
*[`alpine/APKBUILD` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw0twU78mZcliUEfkA:-NZWrIfr2rGHSdbK0a7h:b41pd5i) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh x2, and you cannot put a git commit there. Because what if you have two hex digits > A one after another.

What a poor package manager.
</blockquote></details>

Done in #1439 
___
*[`alpine/APKBUILD` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2NeyEv0GJ32Om2Pw:-NZWrLVh1K7wToccrqFx:b-i7771y) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not in this file. `makedepends=` apply only to this file, and if you don't invoke `ninja` directly in this script, it's perfectly fine to omit it. Building instructions are only guidelines and don't matter here.

It would matter if you wanted to rely on specific version though (like `ninja >= 1.10`), but I haven't seen this here.
</blockquote></details>

Done in #1439
___
*[`alpine/APKBUILD` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw2sPX0mwMxe79sqkd:-NZWrNga7lCaLEUySfSX:b-i7771y) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yep, and not even from my HEAD of `master`, but GitHub's. That's even worse to explain.
</blockquote></details>

Done in #1439
___
*[`alpine/APKBUILD` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYwFIiE4uJKX_i-8o3U:-NZWw8ml7x6P_2Q3G61r:b41pd5w) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L71)):*
<details><summary><i>Previously, amicrity (Amie Raine) wrote…</i></summary><blockquote>

will do?
</blockquote></details>

Done in #1439.
___
*[`alpine/APKBUILD` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1421#-NYw3S812JfDphvb_2JZ:-NZWwBBC4bWtDpD_7cqM:bluvmfl) ([raw file](https://github.com/gramineproject/gramine/blob/6a8afdb187c2dbbaff295e64fe41dcf0b74e61ac/alpine/APKBUILD#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"Semantic versioning" as defined by javascript developers is insufficient, because we need -rc versions, which are effectively less than zero. In upstream Gramine we use versions compatible with both [Debian](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version) ([example](https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#name-version)) and [RPM](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_handling_non_sorting_versions_with_tilde_dot_and_caret), that is, we can use `~`.

How exactly abuild breaks on this?
</blockquote></details>

(Breaks same as on `pkgver=` containing `~`, apparently abuild or one of related tools parses pc and checks version).

Changed in #1439 to subsititute compat `$pkgver`.


<!-- Sent from Reviewable.io -->

2023-07-04 17:30 UTC, woju commented
I'm closing this PR in favour of #1439, where I took over this Alpine effort. I won't continue in this PR, because it is based on a branch in another repo, where I won't push.

2023-07-04 17:30 UTC, closed without merging