[LibOS] Add SIGTERM signal to list of pending signals
gramineproject/gramine pull request #1424
Opened 2023-06-27 11:30 UTC by dimakuv

## Description of the changes 

Previously, `get_all_pending_signals()` helper function did not check for the SIGTERM signal (which has a special handling via `g_host_injected_signal`). Syscalls like `rt_sigsuspend()` and `rt_sigtimedwait()` use this helper function. Because of that erroneous behavior, apps like Nginx would wait for signals on one of these syscalls but would *not* react to SIGTERM (i.e., won't react to `kill <app>`).

This PR fixes this bug, which in turns fixes nginx and ra-tls-nginx examples.

## How to test this PR? 

Without this PR, ra-tls-nginx example (with `kill $pid`, i.e. without SIGKILL) would not kill Nginx at all. Running this example twice on the same machine would fail with `bind() to 0.0.0.0:8000 failed (98: Address already in use)`.

2023-06-27 11:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwbnrc-5j77d4nsCCm:-NYwbnrc-5j77d4nsCCn:b-b8p92z) (no related file):*
The same issue can be found on the `nginx` example too. Just start `gramine-sgx nginx`, try to send SIGTERM to it and observe that nothing happens.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwc5Bm6qor3SXrK3nG:-NYwc5Bm6qor3SXrK3nH:bh8lb7p) (no related file):*
I could add a simple test to our CI: just call `run.sh` **twice**. It will fail the second time. Without this PR it would fail (see PR desc), with this PR it will succeed.

Does anyone want me to add such a test?

___


<!-- Sent from Reviewable.io -->

2023-06-27 11:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYweBDW1Y_PK-7g2Mgx:-NYweBDW1Y_PK-7g2Mgy:bkujod9) (no related file):*
TODO(myself): ping Borys when he has some free time -- this PR is not urgent, and Borys was the one who wrote the whole signals subsystem, so his review would be perfect.

___


<!-- Sent from Reviewable.io -->

2023-06-30 02:45 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwc5Bm6qor3SXrK3nG:-NZ9AaRlE2SUO8eyJx_S:b-ur67sv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I could add a simple test to our CI: just call `run.sh` **twice**. It will fail the second time. Without this PR it would fail (see PR desc), with this PR it will succeed.

Does anyone want me to add such a test?
</blockquote></details>

A unit test would be perfect (though I don't insist). But a test of calling `run.sh` twice is not something I'd expect.

___
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1424#-NZ9AVIH5SyiXJwWiLxN):*
turn



_Code quote:_
```
turns
```


<!-- Sent from Reviewable.io -->

2023-06-30 09:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwc5Bm6qor3SXrK3nG:-NZA_a5H0mYH3QdzXylM:b-rhoy9e) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

A unit test would be perfect (though I don't insist). But a test of calling `run.sh` twice is not something I'd expect.
</blockquote></details>

I couldn't come up with a unit test, because our `gramine-test` infrastructure is too cumbersome to add the SIGTERM ability. See https://github.com/gramineproject/gramine/blob/master/python/graminelibos/regression.py

So instead I'm testing `ra-tls-nginx` example. Now the Bash script sends SIGTERM to Nginx. Without this PR, Gramine ignores SIGTERM and the script fails. With this PR, Gramine forwards SIGTERM to Nginx, which terminates itself properly.

Currently checking the CI...

___


<!-- Sent from Reviewable.io -->

2023-06-30 10:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwc5Bm6qor3SXrK3nG:-NZArWLK0jdC3tzVmRMF:b4n1s7u) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I couldn't come up with a unit test, because our `gramine-test` infrastructure is too cumbersome to add the SIGTERM ability. See https://github.com/gramineproject/gramine/blob/master/python/graminelibos/regression.py

So instead I'm testing `ra-tls-nginx` example. Now the Bash script sends SIGTERM to Nginx. Without this PR, Gramine ignores SIGTERM and the script fails. With this PR, Gramine forwards SIGTERM to Nginx, which terminates itself properly.

Currently checking the CI...
</blockquote></details>

CI correctly fails when my fix is commented out:
```
**11:44:23**  Gramine nginx server (PID=12923) is still running
**11:44:23**  FAIL
**11:44:23**  make: \*\*\* \[Makefile:34: check\] Error 1
```

Now I'll check the CI with my fix.

___


<!-- Sent from Reviewable.io -->

2023-06-30 13:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYwc5Bm6qor3SXrK3nG:-NZBaQrrEPtLfJcuSAG5:b4h97fl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI correctly fails when my fix is commented out:
```
**11:44:23**  Gramine nginx server (PID=12923) is still running
**11:44:23**  FAIL
**11:44:23**  make: \*\*\* \[Makefile:34: check\] Error 1
```

Now I'll check the CI with my fix.
</blockquote></details>

Ok, CI succeeds now, with my fix. Everything looks legit.

___


<!-- Sent from Reviewable.io -->

2023-07-19 14:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1424#-NYweBDW1Y_PK-7g2Mgx:-N_idXY98h6sb4nZl0Ma:b-bzc7fw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): ping Borys when he has some free time -- this PR is not urgent, and Borys was the one who wrote the whole signals subsystem, so his review would be perfect.
</blockquote></details>

@boryspoplawski Could I ping you?

___


<!-- Sent from Reviewable.io -->

2023-07-20 23:32 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-07-21 21:03 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-nginx/run.sh` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/1424#-N_uAP6XEd37uAiUx_dE:-N_uAP6Y8zFPLE0u4Z1l:b6wztmv) ([raw file](https://github.com/gramineproject/gramine/blob/9e2456544434ef66259d1d5ff169039bd97cc751/CI-Examples/ra-tls-nginx/run.sh#L15)):*
> ```Shell
> # verify that SIGTERM terminates nginx with all its sub-processes
> kill $pid
> sleep 1
> ```

Noooo, please don't.

Write a wrapper that would wait for the process with a timeout
Or trap SIGCHLD in bash
Or something, but don't just `sleep 1`
___
*[`libos/src/bookkeep/libos_signal.c` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1424#-N_uF4cu6XP0W1V_4W1f:-N_uF4cv5YeQTMJ0-8gC:b-93oj11) ([raw file](https://github.com/gramineproject/gramine/blob/9e2456544434ef66259d1d5ff169039bd97cc751/libos/src/bookkeep/libos_signal.c#L170)):*
> ```C
>     if (__atomic_load_n(&g_host_injected_signal, __ATOMIC_RELAXED))
>         __sigaddset(set, SIGTERM);
> }
> ```

I would suggsest this or something equivalent:



_Suggestion:_
```C
    struct libos_thread* current = get_cur_thread();

    __sigemptyset(set);

    int host_sig = __atomic_load_n(&g_host_injected_signal, __ATOMIC_RELAXED);
    if (host_sig && host_sig != 0xff) { // or host_sig < SIGS_CNT
        __sigaddset(set, host_sig);
    }

    if (__atomic_load_n(&current->pending_signals, __ATOMIC_ACQUIRE) == 0
            && __atomic_load_n(&g_process_pending_signals_cnt, __ATOMIC_ACQUIRE) == 0) {
        return;
    }

    lock(&current->lock);
    lock(&g_process_signal_queue_lock);

    __sigorset(set, &current->signal_queue.pending_mask, &g_process_signal_queue.pending_mask);

    unlock(&g_process_signal_queue_lock);
    unlock(&current->lock);
}
```


<!-- Sent from Reviewable.io -->

2023-07-25 18:43 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`CI-Examples/ra-tls-nginx/run.sh` line 17 at r4](https://reviewable.io/reviews/gramineproject/gramine/1424#-NaDLbG6DGhgi8MWbRM9:-NaDLbG6DGhgi8MWbRMA:b45h) ([raw file](https://github.com/gramineproject/gramine/blob/70d5590e63fb158d2ce4b4e443762f26a443d5fe/CI-Examples/ra-tls-nginx/run.sh#L17)):*
> ```Shell
> while $(kill -0 $pid 2> /dev/null); do
>     sleep 1
> done
> ```





_Suggestion:_
```Shell
wait $pid
```


<!-- Sent from Reviewable.io -->

2023-07-26 07:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`CI-Examples/ra-tls-nginx/run.sh` line 17 at r4](https://reviewable.io/reviews/gramineproject/gramine/1424#-NaDLbG6DGhgi8MWbRM9:-NaG3-B97wPeiVAsuVBM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/70d5590e63fb158d2ce4b4e443762f26a443d5fe/CI-Examples/ra-tls-nginx/run.sh#L17)):*
> ```Shell
> while $(kill -0 $pid 2> /dev/null); do
>     sleep 1
> done
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-07-26 16:30 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-07-27 06:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1424#-NZ9AVIH5SyiXJwWiLxN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-27 07:02 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1424)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-27 10:53 UTC, merged