[meson] Change -Dglibc and -Dmusl to -Dlibc
gramineproject/gramine pull request #1427
Opened 2023-06-28 15:58 UTC by woju

See commit message.

## How to test this PR? 

1. CI
2. Build gramine on Debian with `-Dlibc=musl` and try to run some tests.
3. Build gramine on Alpine with `-Dlibc=musl`.

(Don't try building gramine on Alpine with `-Dlibc=glibc`).

2023-06-28 18:05 UTC, dimakuv reviewed
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ26rR_-tLuL7v1Gwtu:-NZ26rR_-tLuL7v1Gwtv:bp31zrj) (no related file):*
> (Don't try building gramine on Alpine with `-Dlibc=glibc`).

I wanna try now :)

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ26vYq7ifKmrQYJJqX):*
Don't you want to take these in backticks?
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ27-S36WrAF6usobSG):*
`gets` -> `get`
___
*[`meson_options.txt` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ27uWACycjIGvojrnT:-NZ27uWACycjIGvojrnU:byiwg7k) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/meson_options.txt#L10)):*
> ```Meson
> 
> option('libc', type: 'combo', choices: ['none', 'glibc', 'musl'],
>     value: 'glibc', description: 'Choose libc that is to be built into runtime directory')
> ```

Do you want to add the `patched` word in description? Sounds useful. Maybe in parentheses.
___
*[`.ci/lib/stage-test.jenkinsfile` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29YOk7NFu5CLpmkTq:-NZ29YOk7NFu5CLpmkTr:b-mwuhel) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/.ci/lib/stage-test.jenkinsfile#L30)):*
> ```
>     }
> 
>     /*
> ```

Blocking so that we don't forget to resolve this.
___
*[`libos/test/regression/meson.build` line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29vT8BSvcos_EpRNF:-NZ29vT8BSvcos_EpRNG:ba8fxyo) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/libos/test/regression/meson.build#L210)):*
> ```Meson
>     }
> endif
> if get_option('libc') == 'musl'
> ```

This is what I meant when saying it's not a trivial change.

Right now this PR has two problems:
1. CI doesn't test musl tests on glibc-based distro. (You'll need to create one more CI job I guess.)
2. This code chunk will fail on musl-based distro (Alpine): meson will try `which musl-gcc` and fail, because there is no `musl-gcc` on Alpine.

Are you planning to fix this?
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ28wCCBT5ogEGTUkPy:-NZ28wCCBT5ogEGTUkPz:b-2cv95m) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/subprojects/packagefiles/mbedtls/meson.build#L61)):*
> ```Meson
> )
> 
> if get_option('libc') == 'glibc' and host_has_glibc
> ```

We could go even further, no?
```
if (get_option('libc') == 'glibc' and host_has_glibc) or
        (get_option('libc') == 'musl' and not host_has_glibc)
```

This way we put the correct libs under correct libc dir (no cross-compilation).

Ditto for all other places.

I'm not blocking since you specified in the commit message explicitly that you are not doing this.


<!-- Sent from Reviewable.io -->

2023-06-28 18:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ2BYm83VFMmZ-hTuHh:-NZ2BYm83VFMmZ-hTuHi:b-g6soeg) (no related file):*
Some experiments.

#### Debian

- `Dlibc=none`:
   - builds fine
   - installs fine
   - running Helloworld fails: `Mounting "file:/home/dimakuv/tmp/gramine/built-debug/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib failed: No such file or directory (ENOENT)`
   - after replacing `libc` dir with system-wide dirs in Helloworld manifest, works
   - LGTM

- `Dlibc=musl`
   - builds fine
   - installs fine
   - running Helloworld fails because it assumes Glibc libc
   - after adding `CC=musl-gcc` in Makefile and using `gramine.runtimedir('musl')` in manifest, works
   - `USES_MUSL=1 gramine-test -n tests_musl.toml pytest -v` in LibOS regression tests works
   - LGTM

- `Dlibc=glibc`
   - the usual, nothing interesting to report here.

___


<!-- Sent from Reviewable.io -->

2023-06-28 18:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ2BYm83VFMmZ-hTuHh:-NZ2EGGM176glslmb-sw:bn026u2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Some experiments.

#### Debian

- `Dlibc=none`:
   - builds fine
   - installs fine
   - running Helloworld fails: `Mounting "file:/home/dimakuv/tmp/gramine/built-debug/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib failed: No such file or directory (ENOENT)`
   - after replacing `libc` dir with system-wide dirs in Helloworld manifest, works
   - LGTM

- `Dlibc=musl`
   - builds fine
   - installs fine
   - running Helloworld fails because it assumes Glibc libc
   - after adding `CC=musl-gcc` in Makefile and using `gramine.runtimedir('musl')` in manifest, works
   - `USES_MUSL=1 gramine-test -n tests_musl.toml pytest -v` in LibOS regression tests works
   - LGTM

- `Dlibc=glibc`
   - the usual, nothing interesting to report here.
</blockquote></details>

* in the musl experiment, it should be `GRAMINE_MUSL=1` instead of `USES_MUSL=1`.

___


<!-- Sent from Reviewable.io -->

2023-06-28 18:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ2BYm83VFMmZ-hTuHh:-NZ2H1Q-EHZ89K6TzK-m:b-b9jnyc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

* in the musl experiment, it should be `GRAMINE_MUSL=1` instead of `USES_MUSL=1`.
</blockquote></details>

#### Alpine

- `Dlibc=none`:
   - builds fine
   - installs fine
   - running Helloworld fails (same as for Debian)
   - after replacing `libc` dir with system-wide dirs in Helloworld manifest, works (same as for Debian)
   - LGTM 

- `Dlibc=musl`
   - build with `-Dtests=enabled` fails (`failed to find musl-gcc, is it installed?`)
   - build with `-Dtests=disabled` fine
   - install fine
   - running Helloworld fails because it assumes Glibc libc (same as for Debian)
   - after using `gramine.runtimedir('musl')` in manifest, works
   - LGTM (**except that tests do not build**)

- `Dlibc=glibc`
   - build fails: Glibc build fails with errors like `"__BYTE_ORDER" redefined`
   - **Oops**, but expected: I don't think Glibc cannot be built as-is on Alpine

___


<!-- Sent from Reviewable.io -->

2023-06-28 18:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

___
*[`.ci/lib/stage-test.jenkinsfile` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29YOk7NFu5CLpmkTq:-NZ2K_8o1WraZ8LF-Vah:bv3isr2) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/.ci/lib/stage-test.jenkinsfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking so that we don't forget to resolve this.
</blockquote></details>

Actually, why did you comment it out? It works for me locally on my Ubuntu 20.04. See my top-level comments.


<!-- Sent from Reviewable.io -->

2023-06-28 18:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

___
*[`.ci/lib/stage-test.jenkinsfile` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29YOk7NFu5CLpmkTq:-NZ2Km4R4nexzV3fqw-H:b-fd1v1z) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/.ci/lib/stage-test.jenkinsfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why did you comment it out? It works for me locally on my Ubuntu 20.04. See my top-level comments.
</blockquote></details>

Ah, is it because of SGX-attestation tests? I didn't test them in my local setup.


<!-- Sent from Reviewable.io -->

2023-06-28 23:11 UTC, mkow reviewed
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-29 05:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ26rR_-tLuL7v1Gwtu:-NZ4d6aa3wbSnuI1xWiP:bvzbnmg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> (Don't try building gramine on Alpine with `-Dlibc=glibc`).

I wanna try now :)
</blockquote></details>

I tried, see my results in another comment.

___
___
*[`.ci/lib/stage-test.jenkinsfile` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29YOk7NFu5CLpmkTq:-NZ4dGlj8bnSxEXKpK-K:b-509tdl) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/.ci/lib/stage-test.jenkinsfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, is it because of SGX-attestation tests? I didn't test them in my local setup.
</blockquote></details>

Sorry, brain fart. The musl tests cannot work because you build Gramine with Glibc in this pipeline.

To run musl tests, Gramine should be built with Musl; most probably in another, new pipeline. I'm not sure if you want to implement it now. I can unblock if you say that it will be for later.


<!-- Sent from Reviewable.io -->

2023-06-29 12:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ66P6F1nhWAIBQm9fW:-NZ66P6F1nhWAIBQm9fX:b-xmzed8) (no related file):*
By the way, I took a look at other repos/projects:
- GSC doesn't require any changes because it doesn't specify anything explicitly: https://github.com/gramineproject/gsc/blob/0f4dbbcd182fce97cd306c86b77568d213960b44/templates/Dockerfile.common.compile.template#L30-L38?plain=1
- Contrib is also fine
- Examples are also fine

Looks like we're good.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ67DRhEzxBdYdbfAuI:-NZ67DRhEzxBdYdbfAuJ:bs304m4) (no related file):*
These places should be also fixed:
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/scripts/makedist.sh#L9
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L179
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L305
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L308

___


<!-- Sent from Reviewable.io -->

2023-06-29 13:55 UTC, woju commented
Jenkins, test Jenkins-SGX-20.04-musl please

2023-06-29 14:20 UTC, dimakuv reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2023-06-29 14:48 UTC, kailun-qin reviewed
> Reviewed 12 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2023-06-29 14:48 UTC, mkow reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-29 15:43 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: 12 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ2BYm83VFMmZ-hTuHh:-NZ5IjFLCravKAQ6AlJX:b-konu1i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

#### Alpine

- `Dlibc=none`:
   - builds fine
   - installs fine
   - running Helloworld fails (same as for Debian)
   - after replacing `libc` dir with system-wide dirs in Helloworld manifest, works (same as for Debian)
   - LGTM 

- `Dlibc=musl`
   - build with `-Dtests=enabled` fails (`failed to find musl-gcc, is it installed?`)
   - build with `-Dtests=disabled` fine
   - install fine
   - running Helloworld fails because it assumes Glibc libc (same as for Debian)
   - after using `gramine.runtimedir('musl')` in manifest, works
   - LGTM (**except that tests do not build**)

- `Dlibc=glibc`
   - build fails: Glibc build fails with errors like `"__BYTE_ORDER" redefined`
   - **Oops**, but expected: I don't think Glibc cannot be built as-is on Alpine
</blockquote></details>

For `-Dlibc=none` it's expected that you can't build manifests that contain `{{ gramine.runtimedir() }}`. All our manifests do it, and this is because the app inside actually requires libc, so this is not an error, i.e. we don't pull runtimedir into manifest for no reason. This is just how life is. If you build with `-Dlibc=none`, you're on your own.

This point about `-Dlibc=musl -Dtests=enabled` on alpine is I think out of scope for this PR (there's no regression). This optimally should be corrected by dropping this parsing of musl-gcc (which is debian specific). If we have just one libc, then I think it theoretically should be OK to just have user specify `CC=musl-gcc` or even `CC="gcc -specs /usr/lib/x86_64-linux-musl/musl-gcc.specs"` for whole Gramine (and if not, it's our bug).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ67DRhEzxBdYdbfAuI:-NZ6k736D3dcRJt7Fnes:b-mxquiz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These places should be also fixed:
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/scripts/makedist.sh#L9
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L179
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L305
- https://github.com/gramineproject/gramine/blob/fc242aa79dd3ca30dbd6274367b8921fa875b6fc/Documentation/devel/building.rst?plain=1#L308
</blockquote></details>

Done. I hope this is all.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ26vYq7ifKmrQYJJqX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to take these in backticks?
</blockquote></details>

IDK. Probably not, I'm used to plain text commit messages, not markdown.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ27-S36WrAF6usobSG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gets` -> `get`
</blockquote></details>

Done.
___
*[`meson_options.txt` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ27uWACycjIGvojrnT:-NZ6kMwrBLZjpyVtOLqO:b8q92v) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/meson_options.txt#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you want to add the `patched` word in description? Sounds useful. Maybe in parentheses.
</blockquote></details>

Done, but I'm not sure. See how you like it.
___
*[`libos/test/regression/meson.build` line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29vT8BSvcos_EpRNF:-NZ6kbniBjPKQjvV9sN3:b-guslqb) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/libos/test/regression/meson.build#L210)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is what I meant when saying it's not a trivial change.

Right now this PR has two problems:
1. CI doesn't test musl tests on glibc-based distro. (You'll need to create one more CI job I guess.)
2. This code chunk will fail on musl-based distro (Alpine): meson will try `which musl-gcc` and fail, because there is no `musl-gcc` on Alpine.

Are you planning to fix this?
</blockquote></details>

For now I don't want to fix this, but:

`musl-gcc` is a hack, debian-only (though propagates to debian-derived distros), and I don't want to rely on it, esp. on parsing it to get `-specs`. Ultimately there should be one CC=, and if you need it to be `CC=musl-gcc` then it should be supported. Or am I misunderstanding something?
___
*[`subprojects/packagefiles/mbedtls/meson.build` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ28wCCBT5ogEGTUkPy:-NZ5KlhlEnDjObk_dY_L:bbwxwgt) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/subprojects/packagefiles/mbedtls/meson.build#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We could go even further, no?
```
if (get_option('libc') == 'glibc' and host_has_glibc) or
        (get_option('libc') == 'musl' and not host_has_glibc)
```

This way we put the correct libs under correct libc dir (no cross-compilation).

Ditto for all other places.

I'm not blocking since you specified in the commit message explicitly that you are not doing this.
</blockquote></details>

We can, after release. Now I think we don't have time to do that. In this PR I think it should go as is, just because there's no regression.


<!-- Sent from Reviewable.io -->

2023-06-29 16:22 UTC, woju commented
Jenkins, test check-python-platlib please

2023-06-29 19:53 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ2BYm83VFMmZ-hTuHh:-NZ7fhG82Ha_u9rivb-J:b-cy6n3q) (no related file):*
I agree with all points.

> If we have just one libc, then I think it theoretically should be OK to just have user specify `CC=musl-gcc` or even `CC="gcc -specs /usr/lib/x86_64-linux-musl/musl-gcc.specs"` for whole Gramine (and if not, it's our bug).

I definitely agree with this point. But yes, I'm fine with this change being out of scope of this PR.

___
___
*[`meson_options.txt` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ27uWACycjIGvojrnT:-NZ7fvUa4vSd0TOjtDxX:b8eau52) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/meson_options.txt#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done, but I'm not sure. See how you like it.
</blockquote></details>

I like it.
___
*[`.ci/lib/stage-test.jenkinsfile` line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7hXwkChBdpR-a9yGF:-NZ7hXwkChBdpR-a9yGG:bza9lul) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/.ci/lib/stage-test.jenkinsfile#L23)):*
> ```
>                 cd libos/test/regression
>                 RA_TYPE=$RA_TYPE RA_CLIENT_SPID=${ra_client_spid} \
>                     gramine-test -n tests${GRAMINE_MUSL+_musl}.toml build -v
> ```

Smart!
___
*[`Documentation/devel/building.rst` line 15 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7g8cd8cQjm2WTmYgZ:-NZ7g8cd8cQjm2WTmYg_:b-zi8e89) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/Documentation/devel/building.rst#L15)):*
> ```reStructuredText
> Building Gramine implies building at least the first two components. The
> build of the patched C library is optional but highly recommended for
> performance reasons. You can to choose at most one of the libcs available. By
> ```

`can to choose` -> `can choose`
___
*[`Documentation/devel/building.rst` line 180 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7gHrAC8UKq80dfk8l:-NZ7gHrAC8UKq80dfk8m:bz6caky) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/Documentation/devel/building.rst#L180)):*
> ```reStructuredText
>    that ``/usr/local/bin`` is in your path (in ``PATH`` environment variable).
> 
> Set ``-Dlibc`` option to ``musl`` if you wish build musl instead of Glibc (which
> ```

`Glibc` -> `glibc` (all small letters)
___
*[`libos/test/regression/meson.build` line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ29vT8BSvcos_EpRNF:-NZ7giF6CV2D9K4hp3UA:b-by8o32) ([raw file](https://github.com/gramineproject/gramine/blob/0cacb921f58cf830ab213ac2cce3b38f5f17dbc6/libos/test/regression/meson.build#L210)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For now I don't want to fix this, but:

`musl-gcc` is a hack, debian-only (though propagates to debian-derived distros), and I don't want to rely on it, esp. on parsing it to get `-specs`. Ultimately there should be one CC=, and if you need it to be `CC=musl-gcc` then it should be supported. Or am I misunderstanding something?
</blockquote></details>

Yes, I agree that this whole `musl-gcc` dance is a hack. I'm fine with fixing it later.

Btw, you solved the first problem -- created the new CI job for testing musl on glibc-based distro. Thanks!


<!-- Sent from Reviewable.io -->

2023-06-29 20:59 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`.ci/lib/stage-test.jenkinsfile` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7wdBuClEdPKnY94X1:-NZ7wdBuClEdPKnY94X2:b-zexyf7) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/.ci/lib/stage-test.jenkinsfile#L47)):*
> ```
>             sh '''
>                 cd libos/test/fs
>                 gramine-test -n tests${GRAMINE_MUSL+_musl}.toml build -v
> ```

This doesn't really work, because you need a lot of additional hacks, similar to those `musl-gcc` hacks in regression tests. I suggest to just skip these FS tests in case `GRAMINE_MUSL=1`.
___
*[`libos/test/fs/manifest.template` line 8 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7ww9uCbhwYEUOgksR:-NZ7ww9uCbhwYEUOgksS:b-x6kvbb) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/manifest.template#L8)):*
> ```
> 
> fs.mounts = [
>   { path = "/lib", uri = "file:{{ gramine.runtimedir(libc) }}" },
> ```

ditto (this trick is not enough to run FS tests under musl)
___
*[`libos/test/fs/tests_musl.toml` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7wyvh1akkFi4bsesn:-NZ7wyvh1akkFi4bseso:b-x6kvbb) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/tests_musl.toml#L3)):*
> ```TOML
> binary_dir = "@GRAMINE_PKGLIBDIR@/tests/libos/fs"
> 
> libc = "musl"
> ```

ditto (this trick is not enough to run FS tests under musl)


<!-- Sent from Reviewable.io -->

2023-06-29 21:05 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`libos/test/fs/tests_musl.toml` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7yIhlAcx26TS0FUQ-:-NZ7yIhlAcx26TS0FUQ0:btbytx2) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/tests_musl.toml#L1)):*
> ```TOML
> binary_dir = "@GRAMINE_PKGLIBDIR@/tests/libos/fs"
> ```

This should point to musl-specific dir with musl-built tests.

In regression tests, see this: https://github.com/gramineproject/gramine/blob/72727a1fedfa8bae8b0321524caecfe50b32e5c5/libos/test/regression/tests_musl.toml#L1


<!-- Sent from Reviewable.io -->

2023-06-29 21:51 UTC, mkow reviewed
> Reviewed 3 of 4 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-30 05:21 UTC, jinengandhi-intel reviewed
Has anybody tried building gramine without prefix on an Alpine system? We tried it today and noticed that the `graminelibos` gets installed at `/usr/local/lib/python3.11/site-packages/graminelibos` but this path is not recognized by python, output of `python3 -m site`

```
alpine:~/anjali/gramine$ python3 -m site
sys.path = [
    '/home/intel/anjali/gramine',
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
    '/home/intel/.local/lib/python3.11/site-packages',
    '/usr/lib/python3.11/site-packages',
]
USER_BASE: '/home/intel/.local' (exists)
USER_SITE: '/home/intel/.local/lib/python3.11/site-packages' (exists)
ENABLE_USER_SITE: True
```

Due to this `graminelibos` is not found when building the manifest.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427#-:-NZ9iosxCI2TeCvnw7B7:brm44g8)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-30 07:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZA8bKkBos78xUsrQFJ:b-b5ewgx) (no related file):*
Trying to reproduce @jinengandhi-intel problem on a fresh Alpine Docker image. For context and reproducibility, started like this:
```
docker run --device /dev/sgx_enclave --cap-add SYS_ADMIN --cap-add SYS_PTRACE \
    --security-opt seccomp=unconfined -it alpine
```

Inside Docker container:
```bash
apk add doas wget alpine-sdk perl-utils git
apk add nasm meson py3-click py3-jinja2 py3-elftools bison autoconf linux-headers gawk grep \
    findutils gettext binutils-dev musl-dev openssl1.1-compat-dev coreutils xz py3-pytest \
    libunwind protobuf-c-compiler protobuf-c-dev
apk add py3-tomli py3-tomli-w py3-cryptography py3-elftools
git clone https://github.com/gramineproject/gramine.git
cd gramine/
git checkout woju/meson-libc
meson setup build-debug/ -Dlibc=musl --buildtype=debug \
    -Dskeleton=enabled -Ddirect=enabled -Dsgx=enabled -Dtests=disabled
ninja -C build-debug/
ninja -C build-debug/ install
```

I observe the same issue as @jinengandhi-intel :
```
/gramine # which gramine-direct
/usr/local/bin/gramine-direct

/gramine # pkgconf --cflags mbedtls_gramine
-I/usr/local/include/gramine

/gramine # gramine-manifest
Traceback (most recent call last):
  File "/usr/local/bin/gramine-manifest", line 8, in <module>
    from graminelibos import Manifest
ModuleNotFoundError: No module named 'graminelibos'
```

So PATH and PKGCONFIG work fine, the problem is only with PYTHONPATH. I'll read about it a bit now on Alpine.

___


<!-- Sent from Reviewable.io -->

2023-06-30 07:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZADHu58TeoGIZRpu6j:bdbftxg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Trying to reproduce @jinengandhi-intel problem on a fresh Alpine Docker image. For context and reproducibility, started like this:
```
docker run --device /dev/sgx_enclave --cap-add SYS_ADMIN --cap-add SYS_PTRACE \
    --security-opt seccomp=unconfined -it alpine
```

Inside Docker container:
```bash
apk add doas wget alpine-sdk perl-utils git
apk add nasm meson py3-click py3-jinja2 py3-elftools bison autoconf linux-headers gawk grep \
    findutils gettext binutils-dev musl-dev openssl1.1-compat-dev coreutils xz py3-pytest \
    libunwind protobuf-c-compiler protobuf-c-dev
apk add py3-tomli py3-tomli-w py3-cryptography py3-elftools
git clone https://github.com/gramineproject/gramine.git
cd gramine/
git checkout woju/meson-libc
meson setup build-debug/ -Dlibc=musl --buildtype=debug \
    -Dskeleton=enabled -Ddirect=enabled -Dsgx=enabled -Dtests=disabled
ninja -C build-debug/
ninja -C build-debug/ install
```

I observe the same issue as @jinengandhi-intel :
```
/gramine # which gramine-direct
/usr/local/bin/gramine-direct

/gramine # pkgconf --cflags mbedtls_gramine
-I/usr/local/include/gramine

/gramine # gramine-manifest
Traceback (most recent call last):
  File "/usr/local/bin/gramine-manifest", line 8, in <module>
    from graminelibos import Manifest
ModuleNotFoundError: No module named 'graminelibos'
```

So PATH and PKGCONFIG work fine, the problem is only with PYTHONPATH. I'll read about it a bit now on Alpine.
</blockquote></details>

Ok, resolved. @jinengandhi-intel Please check my explanation and apply.

So Meson by default installs everything under directories with the prefix `/usr/local`. See https://mesonbuild.com/Builtin-options.html.

This prefix is wrong for Alpine. Alpine installations should use the prefix `/usr`. Here are a couple of random examples of other projects:
- https://git.alpinelinux.org/aports/tree/main/meson/APKBUILD?h=3.12-stable
- https://github.com/OpenRC/openrc/issues/474

This is actually what is specified in the https://github.com/gramineproject/gramine/pull/1421 in `meson setup ...`.

So by adding `--prefix=/usr` to `meson setup ...` in my Bash snippet above, it starts working:
```
/gramine # gramine-manifest
Usage: gramine-manifest [OPTIONS] [INFILE] [OUTFILE]
...
```

And I can run e.g. Helloworld:
```
/gramine # cd CI-Examples/helloworld/
/gramine/CI-Examples/helloworld # gramine-sgx-gen-private-key
/gramine/CI-Examples/helloworld # make SGX=1

/gramine/CI-Examples/helloworld # gramine-sgx helloworld
Hello, world
```

(In the Helloworld example, need to add `'musl'` as the libc in the manifest template. Also, need to install `apk add bash` for Gramine to start.)

___


<!-- Sent from Reviewable.io -->

2023-06-30 08:17 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZAN-lh4qvdFfO3Qq9z:b8f47j9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, resolved. @jinengandhi-intel Please check my explanation and apply.

So Meson by default installs everything under directories with the prefix `/usr/local`. See https://mesonbuild.com/Builtin-options.html.

This prefix is wrong for Alpine. Alpine installations should use the prefix `/usr`. Here are a couple of random examples of other projects:
- https://git.alpinelinux.org/aports/tree/main/meson/APKBUILD?h=3.12-stable
- https://github.com/OpenRC/openrc/issues/474

This is actually what is specified in the https://github.com/gramineproject/gramine/pull/1421 in `meson setup ...`.

So by adding `--prefix=/usr` to `meson setup ...` in my Bash snippet above, it starts working:
```
/gramine # gramine-manifest
Usage: gramine-manifest [OPTIONS] [INFILE] [OUTFILE]
...
```

And I can run e.g. Helloworld:
```
/gramine # cd CI-Examples/helloworld/
/gramine/CI-Examples/helloworld # gramine-sgx-gen-private-key
/gramine/CI-Examples/helloworld # make SGX=1

/gramine/CI-Examples/helloworld # gramine-sgx helloworld
Hello, world
```

(In the Helloworld example, need to add `'musl'` as the libc in the manifest template. Also, need to install `apk add bash` for Gramine to start.)
</blockquote></details>

I re-tried `helloworld` by passing the prefix as `/usr` as it worked. Do we need to document this for Alpine?

___


<!-- Sent from Reviewable.io -->

2023-06-30 08:23 UTC, jinengandhi-intel reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427#-:-NZAOgTH023Y94FWuZoV:bnfp4nl)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-30 08:52 UTC, woju reviewed
> `graminelibos` gets installed at `/usr/local/lib/python3.11/site-packages/graminelibos` but this path is not recognized by python

This is WONTFIX, not our bug. If distro has different path requirements, it's user's responsibility to adjust options (either `--prefix` or maybe `-Dpython3.platlibdir=`, though I'm not sure if this option applies to us).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427#-:-NZAVHnb8cGNiZx70Cub:bunuymx)* status: 17 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZASkyR8MlnW5xINEYa:bgntq2b) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

I re-tried `helloworld` by passing the prefix as `/usr` as it worked. Do we need to document this for Alpine?
</blockquote></details>

We could do it, we already have a caveat against `/usr/local/bin` not being in `$PATH` on CentOS. Not in this PR. Please file a bug if you care enough, so we don't forget about it.

___
___
*[`.ci/lib/stage-test.jenkinsfile` line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7hXwkChBdpR-a9yGF:-NZATTDl7FVygK1XwJry:bvtk9y9) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/.ci/lib/stage-test.jenkinsfile#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Smart!
</blockquote></details>

Thanks :)
___
*[`.ci/lib/stage-test.jenkinsfile` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7wdBuClEdPKnY94X1:-NZAU8ydDjoGIyRYuBXl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/.ci/lib/stage-test.jenkinsfile#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't really work, because you need a lot of additional hacks, similar to those `musl-gcc` hacks in regression tests. I suggest to just skip these FS tests in case `GRAMINE_MUSL=1`.
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 15 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7g8cd8cQjm2WTmYgZ:-NZAUG6B3LYKgk5K_qtl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/Documentation/devel/building.rst#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`can to choose` -> `can choose`
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 180 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7gHrAC8UKq80dfk8l:-NZAUK8P4Z4p4E0eGbTe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/Documentation/devel/building.rst#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Glibc` -> `glibc` (all small letters)
</blockquote></details>

Done.
___
*[`libos/test/fs/manifest.template` line 8 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7ww9uCbhwYEUOgksR:-NZAUS5hCCXE5Ku_pdnF:bp3aow6) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (this trick is not enough to run FS tests under musl)
</blockquote></details>

Reverted.
___
*[`libos/test/fs/tests_musl.toml` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7yIhlAcx26TS0FUQ-:-NZAUNaR4wWwV0OQDpiT:bp3aow6) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/tests_musl.toml#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should point to musl-specific dir with musl-built tests.

In regression tests, see this: https://github.com/gramineproject/gramine/blob/72727a1fedfa8bae8b0321524caecfe50b32e5c5/libos/test/regression/tests_musl.toml#L1
</blockquote></details>

Reverted.
___
*[`libos/test/fs/tests_musl.toml` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZ7wyvh1akkFi4bsesn:-NZAUPFr9-T4lja8F9GL:bp3aow6) ([raw file](https://github.com/gramineproject/gramine/blob/2438a50357b354e8b50935e40ec23e6602975230/libos/test/fs/tests_musl.toml#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (this trick is not enough to run FS tests under musl)
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2023-06-30 08:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: 17 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZAVC2c1ar-uTknPOxy:b9i963t) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We could do it, we already have a caveat against `/usr/local/bin` not being in `$PATH` on CentOS. Not in this PR. Please file a bug if you care enough, so we don't forget about it.
</blockquote></details>

I think we should do this in a separate docs PR:
1. Always specify `--prefix` in all `meson setup` commands -- for clarity.
2. Add a note that `--prefix=/usr` on Alpine to install system-wide.

___


<!-- Sent from Reviewable.io -->

2023-06-30 08:56 UTC, jinengandhi-intel reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427#-:-NZAVtgCB03XOU6ZCU_4:bnfp4nl)* status: 17 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZAW421DVvrnvBOem3U:by7y79t) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we should do this in a separate docs PR:
1. Always specify `--prefix` in all `meson setup` commands -- for clarity.
2. Add a note that `--prefix=/usr` on Alpine to install system-wide.
</blockquote></details>

This will be appropriate.

___


<!-- Sent from Reviewable.io -->

2023-06-30 09:15 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-30 10:13 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 4 files at r3, 3 of 6 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow and @woju)

___
*[`Documentation/devel/building.rst` line 180 at r5](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZAmFIa--WT9UeNROnj:-NZAmFIb6bpHhBAqUE9m:bjh83k8) ([raw file](https://github.com/gramineproject/gramine/blob/16aa834a2565ae9b637ea99c7163265c44a8914b/Documentation/devel/building.rst#L180)):*
> ```reStructuredText
>    that ``/usr/local/bin`` is in your path (in ``PATH`` environment variable).
> 
> Set ``-Dlibc`` option to ``musl`` if you wish build musl instead of glibc (which
> ```

nit: wish to build



_Code quote:_
```reStructuredText
wish build
```


<!-- Sent from Reviewable.io -->

2023-06-30 10:16 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-06-30 10:31 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZA8bKkBos78xUsrQFI:-NZAqbVlDOFse6R_V1TJ:b-aos6m1) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

This will be appropriate.
</blockquote></details>

https://github.com/gramineproject/gramine/pull/1434 -- I created such a PR that changes documentation.

___
___
*[`Documentation/devel/building.rst` line 180 at r5](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZAmFIa--WT9UeNROnj:-NZAqu5-60RaF0koQtli:bjlq510) ([raw file](https://github.com/gramineproject/gramine/blob/16aa834a2565ae9b637ea99c7163265c44a8914b/Documentation/devel/building.rst#L180)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

nit: wish to build
</blockquote></details>

It actually sounded like proper English to me, but who knows


<!-- Sent from Reviewable.io -->

2023-06-30 10:35 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`Documentation/devel/building.rst` line 180 at r5](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZAmFIa--WT9UeNROnj:-NZArqWQ1QkB8RA90vyY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/16aa834a2565ae9b637ea99c7163265c44a8914b/Documentation/devel/building.rst#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It actually sounded like proper English to me, but who knows
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 10:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-30 10:40 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-06-30 10:42 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1427)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Documentation/devel/building.rst` line 180 at r5](https://reviewable.io/reviews/gramineproject/gramine/1427#-NZAmFIa--WT9UeNROnj:-NZAt8KmBXZbzFA6rXz2:b65tfw9) ([raw file](https://github.com/gramineproject/gramine/blob/16aa834a2565ae9b637ea99c7163265c44a8914b/Documentation/devel/building.rst#L180)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, it definitely requires "to" (IMO).


<!-- Sent from Reviewable.io -->

2023-06-30 11:59 UTC, woju commented
Jenkins, test pkg-deb-debian12 please

2023-06-30 13:39 UTC, merged