[LibOS,PAL] Fix wrong handling of sysfs NUMA nodes when nodes are offline
gramineproject/gramine pull request #1454
Opened 2023-07-12 09:01 UTC by dimakuv

## Description of the changes 

Previously, Gramine iterated through all NUMA nodes within the range obtained from the host's `/sys/devices/system/node/possible` file to get `cpulist` and `distance`. It also used the count of possible nodes to parse the `distance` between nodes.

However, there is no `/sys/devices/system/node/nodeX` directory when a node is not online. Also, `/sys/devices/system/node/nodeX/distance` lists distances between online nodes only (jumping over offline nodes).

This can lead to failures when Gramine tries to read values of `cpulist` and `distance` pseudo-files from the directory. Plus a correct parsing of `distance` should consider only online nodes.

For context, see https://github.com/gramineproject/gramine/issues/1452.

The main Linux source ref: https://github.com/torvalds/linux/blob/v6.4/drivers/base/node.c#L543-L564

## How to test this PR? 

Manually on weird NUMA platforms...

2023-07-12 09:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/fs/sys/node_info.c` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8KkgmBzt_jSVWNt0m:-N_8KkgmBzt_jSVWNt0n:bq1uf3r) ([raw file](https://github.com/gramineproject/gramine/blob/8f1b75ad9f9861c46992428d2e12c6f9e8318c40/libos/src/fs/sys/node_info.c#L81)):*
> ```C
>                 online_nodes_cnt++;
>         }
>         size_t* distances = topo->numa_distance_matrix + i_online * online_nodes_cnt;
> ```

When reviewing this code and this `i_online` variable, always keep in mind the following scenario:

- Node 0 is online
- Node 1 is offline
- Node 2 is online

In this case, the distances matrix "jumps over" Node 1, so e.g. `/sys/devices/system/node/node2/distance` will contain:
```
[at row 1 of numa_distance_matrix] node 2 -> node 0, node 2 -> node 2
```
___
*[`pal/src/host/linux-sgx/pal_main.c` line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8LIG-63YfrV5TUcEN:-N_8LIG-63YfrV5TUcEO:bvevbmv) ([raw file](https://github.com/gramineproject/gramine/blob/8f1b75ad9f9861c46992428d2e12c6f9e8318c40/pal/src/host/linux-sgx/pal_main.c#L209)):*
> ```C
>     for (size_t i = 0; i < online_nodes_cnt; i++) {
>         /* Note: distance i -> i is 10 according to the ACPI 2.0 SLIT spec, but to accomodate for
>          * weird BIOS settings we aren't checking this. */
> ```

See e.g. https://github.com/torvalds/linux/blob/6995e2de6891c724bfeb2db33d7b87775f913ad1/include/linux/topology.h#L49

Or if you're brave enough, Chapter "5.2.17 System Locality Distance Information Table (SLIT)" in https://uefi.org/sites/default/files/resources/ACPI_6_3_final_Jan30.pdf


<!-- Sent from Reviewable.io -->

2023-07-12 11:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/fs/sys/fs.c` line 257 at r2](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8sz0C4Qg4xc7Cp6NU:-N_8sz0C4Qg4xc7Cp6NV:bsy9h36) ([raw file](https://github.com/gramineproject/gramine/blob/db2a92e4e37acd7e5023cd728fb78df00527d14d/libos/src/fs/sys/fs.c#L257)):*
> ```C
> 
>     // TODO(mkow): Does this show up for offline nodes? I never succeeded in shutting down one, even
>     // after shutting down all CPUs inside the node it shows up as online on `node/online` list.
> ```

FYI: The answer to this question is "no", nothing shows up under offline nodes.


<!-- Sent from Reviewable.io -->

2023-07-12 12:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/fs/sys/node_info.c` line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8yVoTBCUSDBBFthGA:-N_8yVoTBCUSDBBFthGB:bm3valp) ([raw file](https://github.com/gramineproject/gramine/blob/27d00c5e5f6b7b1afe9d258ab7dc7d98d05ebcb2/libos/src/fs/sys/node_info.c#L69)):*
> ```C
>     const struct pal_numa_node_info* numa_node = &topo->numa_nodes[node_id];
>     if (!numa_node->is_online)
>         return -ENOENT;
> ```

I think we actually can never hit this case, because we don't even allow `/sys/devices/system/nodeX/` directories if `nodeX` is offline. But I keep it just in case.
___
*[`libos/src/fs/sys/node_info.c` line 133 at r3](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8yful-Bge2A0l0pLZ:-N_8yful-Bge2A0l0pL_:bm3valp) ([raw file](https://github.com/gramineproject/gramine/blob/27d00c5e5f6b7b1afe9d258ab7dc7d98d05ebcb2/libos/src/fs/sys/node_info.c#L133)):*
> ```C
>     const struct pal_numa_node_info* numa_node = &topo->numa_nodes[node_id];
>     if (!numa_node->is_online)
>         return -ENOENT;
> ```

I think we actually can never hit this case, because we don't even allow `/sys/devices/system/nodeX/` directories if `nodeX` is offline. But I keep it just in case.


<!-- Sent from Reviewable.io -->

2023-07-12 12:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 22 at r4](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_94Bre0wX_8-ZSb6Dd):*
This second commit is a bit unrelated, but I noticed that it's missing and it's very easy to add.

In particular, this broke the `lscpu` tool when put under Gramine. Here's a very simple diff to run `lscpu` under gramine-direct (on a RHEL-based system):
```diff
diff --git a/CI-Examples/helloworld/helloworld.manifest.template b/CI-Examples/helloworld/helloworld.manifest.template
index e15f0d2b..41a7f47f 100644
--- a/CI-Examples/helloworld/helloworld.manifest.template
+++ b/CI-Examples/helloworld/helloworld.manifest.template
@@ -1,14 +1,15 @@
 # Hello World manifest file example

 loader.entrypoint = "file:{{ gramine.libos }}"
-libos.entrypoint = "/helloworld"
+libos.entrypoint = "/lscpu"
 loader.log_level = "{{ log_level }}"

-loader.env.LD_LIBRARY_PATH = "/lib"
+loader.env.LD_LIBRARY_PATH = "/lib:/lib64"

 fs.mounts = [
   { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
-  { path = "/helloworld", uri = "file:helloworld" },
+  { path = "/lscpu", uri = "file:/usr/bin/lscpu" },
+  { path = "/lib64", uri = "file:/lib64" },
 ]

 sgx.debug = true
```

---

For `lscpu` code that uses `present` file, see:
- https://github.com/util-linux/util-linux/blob/0fc338b0360a2479cc4144aba481aae1aa240c3c/sys-utils/lscpu.c#L1019
- https://github.com/util-linux/util-linux/blob/0fc338b0360a2479cc4144aba481aae1aa240c3c/sys-utils/lscpu-cputype.c#L716-L717
___
*[`libos/src/fs/sys/cpu_info.c` line 41 at r4](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_94rDG5CL36bzbwtAP:-N_94rDG5CL36bzbwtAQ:bgfot2y) ([raw file](https://github.com/gramineproject/gramine/blob/2bbd9de9f991fee61bb9be523c4ad28bd444c61d/libos/src/fs/sys/cpu_info.c#L41)):*
> ```C
>         ret = sys_print_as_ranges(str, sizeof(str), topo->threads_cnt, is_offline, NULL);
>     } else if (strcmp(name, "possible") == 0 || strcmp(name, "present") == 0) {
>         /* we simplify and always output "present" CPUs same as "possible" CPUs */
> ```

If you wonder why we can assume that `present` is the same as `possible`: that's because `present` is always a subset of `possible`, and always a superset of `online`. See:
- https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu
- https://www.kernel.org/doc/Documentation/admin-guide/cputopology.rst

I only use `present` to fix `lscpu` tool output, see my other comment.


<!-- Sent from Reviewable.io -->

2023-07-12 13:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_9C9pA5gWcHkInK0Fs):*
Very simple commit, adds a hard-coded value typically found on systems (~8K).

Some refs:
- https://github.com/torvalds/linux/blob/3f01e9fed8454dcd89727016c3e5b2fbb8f8e50c/drivers/base/cpu.c#L217
- https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu


<!-- Sent from Reviewable.io -->

2023-07-12 17:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 0 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_A5DACAIPwHBcXU9Bq):*
Another very simple commit.

Unfortunately, I cannot show the source codes of offending libraries. But I debugged this lib: https://packages.ubuntu.com/search?keywords=libmkl-gnu-thread.

I tested manually on the offending machine, and it works fine now.


<!-- Sent from Reviewable.io -->

2023-07-13 03:15 UTC, kailun-qin requested changes
> Reviewed 3 of 4 files at r1, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/sys/fs.c` line 225 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C7UJ77WQkq2p4DImF:-N_C7UJ77WQkq2p4DImG:bbk9xfe) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/libos/src/fs/sys/fs.c#L225)):*
> ```C
>         log_warning("Actual number of CPUs (%lu) is greater than the value (%u) hard-coded into "
>                     "/sys/devices/system/cpu/kernel_max. This may confuse apps that rely on the "
>                     "value in this file.", g_pal_public_state->topo_info.threads_cnt,
> ```

This is not actionable for users. Besides, is this happening only w/ weird BIOS settings? If so, but we simply accomodate for them instead of checking/warning in the other places?



_Code quote:_
```C
                    "/sys/devices/system/cpu/kernel_max. This may confuse apps that rely on the "
                    "value in this file.", g_pal_public_state->topo_info.threads_cnt,
```
___
*[`pal/include/arch/x86_64/pal_topology.h` line 114 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C2tNU0pK9FTuIX1e0:-N_C2tNU0pK9FTuIX1e1:b-w2nchr) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/pal/include/arch/x86_64/pal_topology.h#L114)):*
> ```objc
> 
>     /*
>      * Has `online_numa_nodes_cnt * online_numa_nodes_cnt` elements, where `online_numa_nodes_cnt`
> ```

-> `non-zero/valid elements` (since it's actually an overapproximate)?



_Code quote:_
```objc
elements
```
___
*[`pal/include/arch/x86_64/pal_topology.h` line 121 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C5Gf0-JYP54EQsn7F:-N_C5Gf0-JYP54EQsn7G:bmrz1pc) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/pal/include/arch/x86_64/pal_topology.h#L121)):*
> ```objc
>      *
>      * It may be surprising that this array contains only online nodes, but this is what Linux does:
>      *   https://github.com/torvalds/linux/blob/v6.4/drivers/base/node.c#L543-L564
> ```

Are we more in favor of `bootlin` (https://elixir.bootlin.com/linux/v6.4/source/drivers/base/node.c#L543)?



_Code quote:_
```objc
https://github.com/torvalds/linux/blob/v6.4/drivers/base/node.c#L543-L564
```


<!-- Sent from Reviewable.io -->

2023-07-13 09:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 7 of 9 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/fs/sys/fs.c` line 225 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C7UJ77WQkq2p4DImF:-N_DUOcx11mP9sU7B2bH:b146cfg) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/libos/src/fs/sys/fs.c#L225)):*
Done. I just update this `kernel_max` value, since Gramine doesn't really have an upper limit on the number of CPU cores.

> If so, but we simply accomodate for them instead of checking/warning in the other places?

I didn't understand your question.
___
*[`pal/include/arch/x86_64/pal_topology.h` line 114 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C2tNU0pK9FTuIX1e0:-N_DUq16CZC4MBK-JnpD:b2nl9ah) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/pal/include/arch/x86_64/pal_topology.h#L114)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `non-zero/valid elements` (since it's actually an overapproximate)?
</blockquote></details>

Done. Added `valid` to make it more explicit (I hope, or is it confusing?)
___
*[`pal/include/arch/x86_64/pal_topology.h` line 121 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C5Gf0-JYP54EQsn7F:-N_DUzgiDdR3czMpUdgF:bs1vbdg) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/pal/include/arch/x86_64/pal_topology.h#L121)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Are we more in favor of `bootlin` (https://elixir.bootlin.com/linux/v6.4/source/drivers/base/node.c#L543)?
</blockquote></details>

Done. Right, though I started using GitHub much more actively because it now has the cool feature of finding symbols.


<!-- Sent from Reviewable.io -->

2023-07-14 01:15 UTC, kailun-qin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 7 of 9 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/sys/fs.c` line 225 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C7UJ77WQkq2p4DImF:-N_GjmYk-lCNgMxkX1QI:b-ft03xh) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/libos/src/fs/sys/fs.c#L225)):*
> I didn't understand your question.

Forget about it, it's not relevant anymore. I'm fine w/ the current approach, thanks!
___
*[`libos/src/fs/sys/fs.c` line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gu-E4CI_8YZp5tZ0E:-N_Gu-E4CI_8YZp5tZ0F:b-yt0oz6) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L16)):*
> ```C
> #include "libos_fs_pseudo.h"
> 
> #define DEFAULT_KERNEL_MAX_CPUS 8191
> ```

The name is a bit misleading as 8191 is actually the max **index**? I understand this follows Linux kernel and I don't insist.



_Code quote:_
```C
DEFAULT_KERNEL_MAX_CPUS
```
___
*[`libos/src/fs/sys/fs.c` line 229 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gr5Bl2-JeoxYgA0I-:-N_Gr5Bl2-JeoxYgA0I0:bgmuymg) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L229)):*
> ```C
> 
> static void init_cpu_dir(struct pseudo_node* cpu) {
>     if (g_pal_public_state->topo_info.threads_cnt > DEFAULT_KERNEL_MAX_CPUS) {
> ```

Here we compare `threads_cnt` w/ `kernel_max` which is the maximum cpu **index** allowed, shouldn't we compare w/ `max_index + 1`?
___
*[`libos/src/fs/sys/fs.c` line 229 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_GtBYI9_zFlanxndhH:-N_GtBYI9_zFlanxndhI:b-i8g4aa) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L229)):*
> ```C
> 
> static void init_cpu_dir(struct pseudo_node* cpu) {
>     if (g_pal_public_state->topo_info.threads_cnt > DEFAULT_KERNEL_MAX_CPUS) {
> ```

Actually, maybe we can even remove the IF?

Perhaps something like:
```
static void init_cpu_dir(struct pseudo_node* cpu) {
    uint32_t next_power_of_2 = DEFAULT_KERNEL_MAX_CPUS + 1;
    while (next_power_of_2 < g_pal_public_state->topo_info.threads_cnt) {
        /* this should never happen in real systems, so BUG() railguard is enough */
        if (__builtin_mul_overflow(next_power_of_2, 2, &next_power_of_2))
            BUG();
    }
    /* `- 1` because Linux always reports kernel_max like this */
    g_kernel_max_cpus = next_power_of_2 - 1;
}
```
___
*[`libos/src/fs/sys/fs.c` line 231 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gucrk3fmil16l_NRU:-N_Gucrk3fmil16l_NRV:b-983ife) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L231)):*
> ```C
>     if (g_pal_public_state->topo_info.threads_cnt > DEFAULT_KERNEL_MAX_CPUS) {
>         assert(g_kernel_max_cpus == DEFAULT_KERNEL_MAX_CPUS);
>         uint32_t next_power_of_2 = 1;
> ```

Can't we just start from `DEFAULT_KERNEL_MAX_CPUS + 1` (as we control it completely)?



_Code quote:_
```C
uint32_t next_power_of_2 = 1;
```
___
*[`pal/include/arch/x86_64/pal_topology.h` line 114 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_C2tNU0pK9FTuIX1e0:-N_GhQ05-C5Npp5yYrSI:b1r9tjg) ([raw file](https://github.com/gramineproject/gramine/blob/c194fc7ebfb9b5b03f67080fc03843a288bbf820/pal/include/arch/x86_64/pal_topology.h#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Added `valid` to make it more explicit (I hope, or is it confusing?)
</blockquote></details>

It's more explicit to me, thanks!


<!-- Sent from Reviewable.io -->

2023-07-17 10:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 7 of 9 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/fs/sys/fs.c` line 16 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gu-E4CI_8YZp5tZ0E:-N_YTPcM5EPiSFzj7jG_:b-hy76ue) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The name is a bit misleading as 8191 is actually the max **index**? I understand this follows Linux kernel and I don't insist.
</blockquote></details>

Done. I'm keeping the name but it's not refering to the **index** now, but instead to the **max number**.
___
*[`libos/src/fs/sys/fs.c` line 229 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_GtBYI9_zFlanxndhH:-N_YU5T1CVBxqUVf1NgX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L229)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Actually, maybe we can even remove the IF?

Perhaps something like:
```
static void init_cpu_dir(struct pseudo_node* cpu) {
    uint32_t next_power_of_2 = DEFAULT_KERNEL_MAX_CPUS + 1;
    while (next_power_of_2 < g_pal_public_state->topo_info.threads_cnt) {
        /* this should never happen in real systems, so BUG() railguard is enough */
        if (__builtin_mul_overflow(next_power_of_2, 2, &next_power_of_2))
            BUG();
    }
    /* `- 1` because Linux always reports kernel_max like this */
    g_kernel_max_cpus = next_power_of_2 - 1;
}
```
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/fs.c` line 229 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gr5Bl2-JeoxYgA0I-:-N_YU6qODf_QcBsah2RR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L229)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Here we compare `threads_cnt` w/ `kernel_max` which is the maximum cpu **index** allowed, shouldn't we compare w/ `max_index + 1`?
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/fs.c` line 231 at r7](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_Gucrk3fmil16l_NRU:-N_YU6AKDGVAmo45bfT9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/244f0bdf436493dce3afb93e8332074ca84980cd/libos/src/fs/sys/fs.c#L231)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Can't we just start from `DEFAULT_KERNEL_MAX_CPUS + 1` (as we control it completely)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-18 12:42 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 6 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-30 15:28 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/sys/fs.c` line 257 at r2](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8sz0C4Qg4xc7Cp6NU:-NabPQcoCGINepxvwVzy:bmw8mtt) ([raw file](https://github.com/gramineproject/gramine/blob/db2a92e4e37acd7e5023cd728fb78df00527d14d/libos/src/fs/sys/fs.c#L257)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: The answer to this question is "no", nothing shows up under offline nodes.
</blockquote></details>

So, how did you actually manage to shut down a NUMA node?


<!-- Sent from Reviewable.io -->

2023-07-31 06:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/sys/fs.c` line 257 at r2](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_8sz0C4Qg4xc7Cp6NU:-NaeeIPB6yOZ0f7EieCo:b-ysjkoj) ([raw file](https://github.com/gramineproject/gramine/blob/db2a92e4e37acd7e5023cd728fb78df00527d14d/libos/src/fs/sys/fs.c#L257)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, how did you actually manage to shut down a NUMA node?
</blockquote></details>

I didn't shut down NUMA nodes, the Linux kernel simply started on this platform with some NUMA nodes being offline.


<!-- Sent from Reviewable.io -->

2023-07-31 08:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 22 at r4](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_94Bre0wX_8-ZSb6Dd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This second commit is a bit unrelated, but I noticed that it's missing and it's very easy to add.

In particular, this broke the `lscpu` tool when put under Gramine. Here's a very simple diff to run `lscpu` under gramine-direct (on a RHEL-based system):
```diff
diff --git a/CI-Examples/helloworld/helloworld.manifest.template b/CI-Examples/helloworld/helloworld.manifest.template
index e15f0d2b..41a7f47f 100644
--- a/CI-Examples/helloworld/helloworld.manifest.template
+++ b/CI-Examples/helloworld/helloworld.manifest.template
@@ -1,14 +1,15 @@
 # Hello World manifest file example

 loader.entrypoint = "file:{{ gramine.libos }}"
-libos.entrypoint = "/helloworld"
+libos.entrypoint = "/lscpu"
 loader.log_level = "{{ log_level }}"

-loader.env.LD_LIBRARY_PATH = "/lib"
+loader.env.LD_LIBRARY_PATH = "/lib:/lib64"

 fs.mounts = [
   { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
-  { path = "/helloworld", uri = "file:helloworld" },
+  { path = "/lscpu", uri = "file:/usr/bin/lscpu" },
+  { path = "/lib64", uri = "file:/lib64" },
 ]

 sgx.debug = true
```

---

For `lscpu` code that uses `present` file, see:
- https://github.com/util-linux/util-linux/blob/0fc338b0360a2479cc4144aba481aae1aa240c3c/sys-utils/lscpu.c#L1019
- https://github.com/util-linux/util-linux/blob/0fc338b0360a2479cc4144aba481aae1aa240c3c/sys-utils/lscpu-cputype.c#L716-L717
</blockquote></details>

This second commit was extracted in a separate PR: https://github.com/gramineproject/gramine/pull/1476


<!-- Sent from Reviewable.io -->

2023-07-31 08:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_A5DACAIPwHBcXU9Bq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Another very simple commit.

Unfortunately, I cannot show the source codes of offending libraries. But I debugged this lib: https://packages.ubuntu.com/search?keywords=libmkl-gnu-thread.

I tested manually on the offending machine, and it works fine now.
</blockquote></details>

This fourth commit was extracted in a separate PR: https://github.com/gramineproject/gramine/pull/1477


<!-- Sent from Reviewable.io -->

2023-07-31 08:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_9C9pA5gWcHkInK0Fs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Very simple commit, adds a hard-coded value typically found on systems (~8K).

Some refs:
- https://github.com/torvalds/linux/blob/3f01e9fed8454dcd89727016c3e5b2fbb8f8e50c/drivers/base/cpu.c#L217
- https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu
</blockquote></details>

Extracted into a separate PR: https://github.com/gramineproject/gramine/pull/1478


<!-- Sent from Reviewable.io -->

2023-09-01 00:16 UTC, mkow reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 22 at r4](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_94Bre0wX_8-ZSb6Dd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This second commit was extracted in a separate PR: https://github.com/gramineproject/gramine/pull/1476
</blockquote></details>

@dimakuv: Could you rebase this PR to drop the commits which were already merged?


<!-- Sent from Reviewable.io -->

2023-09-03 08:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 4 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 22 at r4](https://reviewable.io/reviews/gramineproject/gramine/1454#-N_94Bre0wX_8-ZSb6Dd):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: Could you rebase this PR to drop the commits which were already merged?
</blockquote></details>

Done, rebased to latest master and dropped the unrelated commits.


<!-- Sent from Reviewable.io -->

2023-09-05 23:04 UTC, mkow requested changes
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 2 files at r7, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdXfw0Q4fY2TTPK3j6U:-NdXfw0Q4fY2TTPK3j6V:b-plhipe) (no related file):*
TODO for myself: test this on a system where this reproduces.

___
___
*[`pal/include/arch/x86_64/pal_topology.h` line 114 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbVfUnDeopJXzyiHqM:-NdbVfUnDeopJXzyiHqN:bb9mo71) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/include/arch/x86_64/pal_topology.h#L114)):*
> ```objc
> 
>     /*
>      * Has `online_numa_nodes_cnt * online_numa_nodes_cnt` valid elements, where
> ```

Valid? Does it also have some invalid elements?

// update: ok, it does, but this sentence is confusing (as it only mentions the _number_ of valid elements, not which are valid and which are not)



_Code quote:_
```objc
valid elements
```
___
*[`pal/include/arch/x86_64/pal_topology.h` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbW3T40rr5y8pb8HiE:-NdbW3T40rr5y8pb8HiF:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/include/arch/x86_64/pal_topology.h#L118)):*
> ```objc
>      *
>      * Value in `numa_distance_matrix[i*online_numa_nodes_cnt + j]` is a NUMA distance from online
>      * node i to online node j.
> ```





_Suggestion:_
```objc
node i to online node j (i.e. indexing only through the online nodes).
```
___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdbYjvK9ISUitSz7Izw:brx2szp) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
> ```C
>      *
>      *   [ node 0 -> node 0, node 0 -> node 2
>      *     node 2 -> node 0, node 2 -> node 2 ]
> ```

Wouldn't the code here and at the printing site be much easier if we stored `distances` in a non-crazy way (just setting entries for offline nodes to 0) and would do this weird stuff _only_ when printing it to sysfs? This would also remove the need for most of the explanation comments, only the printing side would need them :)


<!-- Sent from Reviewable.io -->

2023-09-06 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-Ndd_xR76rmdXEuVl_ye:bjg8nty) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't the code here and at the printing site be much easier if we stored `distances` in a non-crazy way (just setting entries for offline nodes to 0) and would do this weird stuff _only_ when printing it to sysfs? This would also remove the need for most of the explanation comments, only the printing side would need them :)
</blockquote></details>

Two counter-arguments to your proposal:
1. The host files `/sys/devices/system/node/nodeXXX/distance` have distances to online-only nodes. So in this code snippet, we'll have to (i) first read this file into a temporary string, (ii) then add `0`s to represent offline nodes, and (iii) save this constructed string into the `distances` array.
   - We will complicate this code snippet.
   - We can revert changes to `sanitize_topo_info()`. That's the only place that will get simplified.
   -  Is it really worth it? We exchange one complexity for another complexity.
2. With your proposed change, Gramine's `distance` is **not** the same as Linux's `distance`. Won't it be confusing for people that Gramine has a different representation of distances?


<!-- Sent from Reviewable.io -->

2023-09-07 00:16 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdgrIdv8sbMdBGiNk2w:b-awn103) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Two counter-arguments to your proposal:
1. The host files `/sys/devices/system/node/nodeXXX/distance` have distances to online-only nodes. So in this code snippet, we'll have to (i) first read this file into a temporary string, (ii) then add `0`s to represent offline nodes, and (iii) save this constructed string into the `distances` array.
   - We will complicate this code snippet.
   - We can revert changes to `sanitize_topo_info()`. That's the only place that will get simplified.
   -  Is it really worth it? We exchange one complexity for another complexity.
2. With your proposed change, Gramine's `distance` is **not** the same as Linux's `distance`. Won't it be confusing for people that Gramine has a different representation of distances?
</blockquote></details>

1. Hmm, no, I'd just change `read_numbers_from_file()` to skip writes (and rename it).
2. I think it's much more intuitive to have it stored normally (i.e. that indices in it are `node_id`s). Also, the description of the array would be much simpler.
3. We'll need to keep the whole table anyways if we ever add support for hot-plugging.
4. There are more places which gets simpler:
   - the printing in node_info.c - you don't need any calculations anymore, just skip printing offline entries.
   - less explanatory comments needed everywhere

The only thing I don't like about this idea is that change to `read_numbers_from_file()`, which sounds ugly. But it's untrusted code, and it makes trusted code a bit simpler...

I won't be blocking on this, but let's maybe also ask @kailun-qin what he thinks about it.


<!-- Sent from Reviewable.io -->

2023-09-07 07:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: 8 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/include/arch/x86_64/pal_topology.h` line 114 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbVfUnDeopJXzyiHqM:-NdiVy6w4fYAKU2n_lfE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/include/arch/x86_64/pal_topology.h#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Valid? Does it also have some invalid elements?

// update: ok, it does, but this sentence is confusing (as it only mentions the _number_ of valid elements, not which are valid and which are not)
</blockquote></details>

Done.
___
*[`pal/include/arch/x86_64/pal_topology.h` line 118 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbW3T40rr5y8pb8HiE:-NdiW59Y6CVDt2P_SMv0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/include/arch/x86_64/pal_topology.h#L118)):*
> ```objc
>      *
>      * Value in `numa_distance_matrix[i*online_numa_nodes_cnt + j]` is a NUMA distance from online
>      * node i to online node j.
> ```

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdiUdfL9swqDiToNj3Q:btsq72j) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
> Hmm, no, I'd just change `read_numbers_from_file()` to skip writes (and rename it).

I don't understand what you mean by this.

Let's wait for @kailun-qin's opinion.


<!-- Sent from Reviewable.io -->

2023-09-07 12:24 UTC, mkow reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-Ndj_v4n7t0LvZqJ5C6m:b-xx8lqd) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
> > Hmm, no, I'd just change `read_numbers_from_file()` to skip writes (and rename it).
> 
> I don't understand what you mean by this.

This was a response to "we'll have to (i) first read this file into a temporary string, (ii) then add `0`s to represent offline nodes, and (iii) save this constructed string into the `distances` array." - the alternative is to change the parsing function to write the results skipping offline nodes.


<!-- Sent from Reviewable.io -->

2023-09-08 10:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdoGNe93mJHBGDcHesN:b-4loo3x) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> the alternative is to change the parsing function to write the results skipping offline nodes.

Still doesn't make sense to me. Host files `/sys/devices/system/node/nodeXXX/distance` already do **not** have any offline nodes, so what's there to skip?
</blockquote></details>

I mean, you don't skip them when reading, but when writing the parsing results to the resulting array.


<!-- Sent from Reviewable.io -->

2023-09-10 09:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdyUX5i7NSyaxo-Dy2V:b-sl6gmb) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean, you don't skip them when reading, but when writing the parsing results to the resulting array.
</blockquote></details>

Done in separate PR: #1545. See there, if you like that definition of `distances` array better.


<!-- Sent from Reviewable.io -->

2023-09-10 16:48 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-NdzzVa-1lpUrWn8vbrz:b-7rgnl8) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done in separate PR: #1545. See there, if you like that definition of `distances` array better.
</blockquote></details>

I prefer #1545, mostly because it has simpler data representation. But let's wait for @kailun-qin's opinion :)


<!-- Sent from Reviewable.io -->

2023-09-11 04:01 UTC, kailun-qin reviewed
> Reviewed 1 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 387 at r9](https://reviewable.io/reviews/gramineproject/gramine/1454#-NdbYjvK9ISUitSz7Izv:-Ne1JNrB1gxv3GaY7ebx:bs2svx7) ([raw file](https://github.com/gramineproject/gramine/blob/ccd4e359734f06ecf020c3bf8496ee7698a6a4c6/pal/src/host/linux-common/topo_info.c#L387)):*
I vote for https://github.com/gramineproject/gramine/pull/1545 because the two counter-arguments do not really hold up IMO:
> We will complicate this code snippet. Is it really worth it? We exchange one complexity for another complexity.

Based on the lataest impl. from #1545, it seems to be not complex (and slightly easier to understand).

> Gramine's `distance` is **not** the same as Linux's `distance`. Won't it be confusing for people that Gramine has a different representation of distances?

Does Gramine's `distance` has to follow the same as Linux's `distance`? I suppose it's rather implementation dependent for what's the `distance` representation between nodes that have one or both offline.

However, we can still get below benefits if we go w/ #1545:
> It's much more intuitive to have it stored normally (i.e. that indices in it are `node_id`s). We'll need to keep the whole table anyways if we ever add support for hot-plugging. There are more places which gets simpler.


<!-- Sent from Reviewable.io -->

2023-09-11 06:58 UTC, closed without merging

2023-09-11 06:58 UTC, dimakuv commented
Everyone agreed to proceed with #1545, closing this PR