[PAL] Add `post_callback` function arg to `pal_main()`
gramineproject/gramine pull request #1467
Opened 2023-07-20 07:45 UTC by dimakuv

## Description of the changes 

This is useful so that the host-specific PAL can perform some post-initialization actions. In particular, the
`print_warnings_on_insecure_configs()` func in SGX PAL is moved to the post-initialization phase because this info should be logged into the `loader.log_file` (if it was specified in the manifest) instead of on the terminal.

## How to test this PR? 

Manually. E.g., add `loader.log_file = "gramine.log"` to the Helloworld example and observe the behavior under `gramine-sgx`.

2023-07-20 23:54 UTC, kailun-qin approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-23 23:07 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/include/pal_internal.h` line 151 at r1](https://reviewable.io/reviews/gramineproject/gramine/1467#-Na3zdjZDp4X42L6MeFL:-Na3zdjZDp4X42L6MeFM:b8359ut) ([raw file](https://github.com/gramineproject/gramine/blob/05c761458d3148da042ae6589fe9bd3882ea5ced/pal/include/pal_internal.h#L151)):*
> ```objc
>  * \param environments    Environment variables.
>  * \param post_callback   Callback into host-specific loader, useful for post-initialization actions
>  *                        like additional logging.
> ```

I'd note that it can be NULL.


<!-- Sent from Reviewable.io -->

2023-07-24 11:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/include/pal_internal.h` line 151 at r1](https://reviewable.io/reviews/gramineproject/gramine/1467#-Na3zdjZDp4X42L6MeFL:-Na6eKBx7YEBCZavYCPp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/05c761458d3148da042ae6589fe9bd3882ea5ced/pal/include/pal_internal.h#L151)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd note that it can be NULL.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-24 23:53 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-07-25 18:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-26 09:06 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1467)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-26 10:07 UTC, merged