[PAL] Fail if Gramine binaries are built with RELR relocs
gramineproject/gramine pull request #1473
Opened 2023-07-25 11:58 UTC by dimakuv

## Description of the changes 

RELR (relative relocs) is a new type of relocations recently added to compilers/linkers, e.g. glibc 2.36 and musl 1.2.4. These relocs are not enabled by default; however, if the system enables them during Gramine build, Gramine would segfault. This is because Gramine has its own self-relocation code that relocates the SGX PAL and the LibOS binaries. Before this commit, the code ignored RELR relocs, which led to some symbols being not relocated and ultimately to segfaults.

This commit makes Gramine aware of RELR relocs, though we simply loudly fail when we detect such type. Currently, Gramine build environment must disable such relocs.

Fixes #1446.

For the context, see #1446.

Good references:
- https://maskray.me/blog/2021-10-31-relative-relocations-and-relr
- https://git.musl-libc.org/cgit/musl/commit/?id=d32dadd60efb9d3b255351a3b532f8e4c3dd0db1
- https://reviews.llvm.org/D120701

The updates to `elf.h` were taken from this Glibc commit: https://github.com/bminor/glibc/commit/4610b24f5e4e6d2c4b769594efa6d460943163bb

## How to test this PR? 

Manually try building with `LDFLAGS="$LDFLAGS -Wl,-z,pack-relative-relocs"` on an OS with Glibc 2.36 (e.g. Ubuntu 23.04). I'll post my experiments soon.

2023-07-25 12:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaByqwAC1huNyUzrfP3:-NaByqwAC1huNyUzrfP4:b-mj364t) (no related file):*
I tested this on Ubuntu 23.04 docker container (it has the required glibc/ld versions). I asked the linker to produce RELR relocs for the SGX PAL:
```diff
diff --git a/pal/src/host/linux-sgx/meson.build b/pal/src/host/linux-sgx/meson.build
@@ -110,6 +110,7 @@ libpal_sgx = shared_library('pal',
         # PAL is expected to be linked with RELRO (Relocation Read-Only)
         '-Wl,-zrelro',
         '-Wl,-znow',
+        '-Wl,-z,pack-relative-relocs',

         '-Wl,-zcombreloc',
         '-Wl,-zdefs',
```

Then I built Gramine and tried to run it:
```bash
root@b6db211304ab:/gramine/CI-Examples/helloworld# gramine-sgx helloworld

Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Unsupported relocation type DT_RELR; you may need to rebuild Gramine with `-Wl,-z,nopack-relative-relocs` linker option
error: Relocation of the PAL binary failed: -6
```

I even added `-Wl,-z,nopack-relative-relocs` to the linker options, and Gramine started to work fine again. So this PR works as expected.

___
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaBubyg6aW9sN4Z9jGR):*
Actually, I don't think Gramine will ever need to take into account `RELR` relocations. I would simply force them to NOT be emitted, similarly how we do it with other linker configs e.g. here: https://github.com/gramineproject/gramine/blob/51d915ded30aa2ca55ad5c2e86075e95fe938ca2/libos/src/meson.build#L152-L165

These new RELR relocations can debloat the binaries' sizes about 5%. Given that this only concerns LibOS and Trusted-SGX PAL binaries, I just wouldn't care about this size improvement... We need to add more code (to work on these RELR relocs) for a dubious benefit of smaller Gramine executables. That's not the price I want to pay.


<!-- Sent from Reviewable.io -->

2023-07-26 03:01 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 232 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaF7Nlg7Gmzvza2BhYl:-NaF7Nlg7Gmzvza2BhYm:b-3cnieq) ([raw file](https://github.com/gramineproject/gramine/blob/53883da309814762ae06a3cb926f2ac1ff6e8c24/pal/src/pal_rtld.c#L232)):*
> ```C
>                 break;
>             case DT_RELR:
>             case DT_RELRSZ:
> ```

Any special reason to not have `DT_RELRENT` here?


<!-- Sent from Reviewable.io -->

2023-07-26 06:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`pal/src/pal_rtld.c` line 232 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaF7Nlg7Gmzvza2BhYl:-NaFwoCBAS0J3Zufnh_P:be5avwm) ([raw file](https://github.com/gramineproject/gramine/blob/53883da309814762ae06a3cb926f2ac1ff6e8c24/pal/src/pal_rtld.c#L232)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Any special reason to not have `DT_RELRENT` here?
</blockquote></details>

I didn't want to add it because:
1. This is more like a metadata (size of the RELR entry), so even if this field exists in the binary, it doesn't affect any actual relocations.
2. Musl doesn't use it at all, glibc uses it only as a sanity check:
   - https://github.com/search?q=repo%3Abminor%2Fmusl%20DT_RELRENT%20&type=code
   - https://github.com/search?q=repo%3Abminor%2Fglibc%20DT_RELRENT%20&type=code

So I would be against failing on `DT_RELRENT`.


<!-- Sent from Reviewable.io -->

2023-07-26 07:29 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/pal_rtld.c` line 232 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaF7Nlg7Gmzvza2BhYl:-NaG5KgC8ubKeDZIeejO:b-u7wv04) ([raw file](https://github.com/gramineproject/gramine/blob/53883da309814762ae06a3cb926f2ac1ff6e8c24/pal/src/pal_rtld.c#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't want to add it because:
1. This is more like a metadata (size of the RELR entry), so even if this field exists in the binary, it doesn't affect any actual relocations.
2. Musl doesn't use it at all, glibc uses it only as a sanity check:
   - https://github.com/search?q=repo%3Abminor%2Fmusl%20DT_RELRENT%20&type=code
   - https://github.com/search?q=repo%3Abminor%2Fglibc%20DT_RELRENT%20&type=code

So I would be against failing on `DT_RELRENT`.
</blockquote></details>

Great to know, thanks!


<!-- Sent from Reviewable.io -->

2023-07-30 15:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NabLI3f7bN_TrD1v2B2):*
And please change the PR accordingly :)



_Suggestion:_
```
[PAL] Fail if Gramine binaries were built with unknown relocs types
```


<!-- Sent from Reviewable.io -->

2023-07-30 15:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaBubyg6aW9sN4Z9jGR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I don't think Gramine will ever need to take into account `RELR` relocations. I would simply force them to NOT be emitted, similarly how we do it with other linker configs e.g. here: https://github.com/gramineproject/gramine/blob/51d915ded30aa2ca55ad5c2e86075e95fe938ca2/libos/src/meson.build#L152-L165

These new RELR relocations can debloat the binaries' sizes about 5%. Given that this only concerns LibOS and Trusted-SGX PAL binaries, I just wouldn't care about this size improvement... We need to add more code (to work on these RELR relocs) for a dubious benefit of smaller Gramine executables. That's not the price I want to pay.
</blockquote></details>

Yeah, IMO it's not that important.


<!-- Sent from Reviewable.io -->

2023-07-31 11:28 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NabLI3f7bN_TrD1v2B2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't know how to do it. There is no list of relocations that I can allow.

I mean, relocations are mixed together with other information about "dynamic entries" (the `DT_` entries). See this list: https://github.com/gramineproject/gramine/blob/4de6aa5fb939a129d3498e8fee432d2873924b4c/pal/include/elf/elf.h#L622-L656

As you can see, there is **no** separate list of relocation types. So the only thing I can do is to whitelist all the not-breaking-Gramine `DT_` entries, but it will look ugly and surprising-to-readers:
```c
    while (dynamic_section_entry->d_tag != DT_NULL) {
        switch (dynamic_section_entry->d_tag) {
            case DT_RELA:
            case DT_RELASZ:
            case DT_JMPREL:
            case DT_PLTRELSZ:
                ... actual good relocation entries, do some job ...

            case DT_NEEDED:
            case DT_HASH:
            case <and so on>:
                ... whitelisted good not-relocation-type entries, ignore them ...
                break;

            default:
                log_error("Unsupported relocation type %d, terminating", dynamic_section_entry->d_tag);
                return -PAL_ERROR_DENIED;
            }
    }
```

Is this what'd you want? I'm hesitant to add a whitelist of ~30 entries...
</blockquote></details>

Yes, that's what I'm asking for, otherwise we're just silently ignoring semantically important entries and hoping for the best.

btw. `DT_NEEDED` probably can't be ignored?


<!-- Sent from Reviewable.io -->

2023-08-01 07:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NabLI3f7bN_TrD1v2B2):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Not sure what you mean by this comment. Please see my comment in the source code, maybe this will explain the situation.

> /* benign -- LibOS and PAL tests have PAL shared lib here, PAL has nothing */

But you could have said exactly the same about `DT_RELR` before the GCC update and justify ignoring it "because PAL currently is not using it for anything important".
What I mean is that `DT_NEEDED` is semantically important for ELF loading and we have to either implement it or error out. Ignoring it seems to be a bug in Gramine which just doesn't trigger currently.
</blockquote></details>

Done, good point. Now we are hardcore -- we check all `DT_` entries. Except for versioning ones and flags -- I don't know how to verify them, and if their verification would actually bring anything.
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1473#-NagKrob5KtH0IWHiNyN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do this: use this commit message at final rebase.
</blockquote></details>

I will also need to rephrase `unrecognized dyn entries` -> `unrecognized or unexpected/malformed dyn entries`


<!-- Sent from Reviewable.io -->

2023-08-01 13:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1473#-NagLdVmBwTL1FkMuA5d:-NalFlyQE-eII2bHEjUt:b-f7mhvp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here is lists of all dynamic entries found in built Gramine binaries:

- LibOS:
```
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpal.so]
 0x000000000000000e (SONAME)             Library soname: [libsysdb.so]
 0x0000000000000004 (HASH)               0x1f0
 0x0000000000000005 (STRTAB)             0x8b0
 0x0000000000000006 (SYMTAB)             0x370
 0x000000000000000a (STRSZ)              1112 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xe5da8
 0x0000000000000002 (PLTRELSZ)           1248 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xc440
 0x0000000000000007 (RELA)               0xdd0
 0x0000000000000008 (RELASZ)             46704 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0xd78
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0xdb0
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0xd08
 0x000000006ffffff9 (RELACOUNT)          1944
 0x0000000000000000 (NULL)               0x0
```
- Linux PAL
```
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [libpal.so]
 0x0000000000000004 (HASH)               0x1f0
 0x0000000000000005 (STRTAB)             0x8b0
 0x0000000000000006 (SYMTAB)             0x370
 0x000000000000000a (STRSZ)              1010 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000007 (RELA)               0xd50
 0x0000000000000008 (RELASZ)             6168 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0xd18
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff0 (VERSYM)             0xca2
 0x000000006ffffff9 (RELACOUNT)          257
 0x0000000000000000 (NULL)               0x0
```
- Linux-SGX PAL (trusted part)
```
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [libpal.so]
 0x0000000000000004 (HASH)               0x618c8
 0x0000000000000005 (STRTAB)             0x730
 0x0000000000000006 (SYMTAB)             0x1f0
 0x000000000000000a (STRSZ)              1064 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x62fe0
 0x0000000000000002 (PLTRELSZ)           24 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2688
 0x0000000000000007 (RELA)               0xc00
 0x0000000000000008 (RELASZ)             6792 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0xbc8
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff0 (VERSYM)             0xb58
 0x000000006ffffff9 (RELACOUNT)          283
 0x0000000000000000 (NULL)               0x0
```
</blockquote></details>

When built with ASan, also `DT_INIT_ARRAY`, `DT_FINI_ARRAY`, `DT_INIT_ARRAYSZ`, `DT_FINI_ARRAYSZ` are added.

___


<!-- Sent from Reviewable.io -->

2023-08-03 00:50 UTC, mkow requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NabLI3f7bN_TrD1v2B2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, good point. Now we are hardcore -- we check all `DT_` entries. Except for versioning ones and flags -- I don't know how to verify them, and if their verification would actually bring anything.
</blockquote></details>

Ok, now we stopped ignoring semantically meaningful entries, but also try to check unused entries (like debug info) for specific values we expect from our current PAL binary. What's the point of that? This may actually change between compilers and fail our builds.

What I originally meant is that we cannot just ignore some DT entries if they are supposed to be interpreted by the loader (like `DT_NEEDED`). But I don't really see a point in hardcoding in the loader how the PAL binary should look like.
___
*[`pal/src/pal_rtld.c` line 270 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-NasqcgtB8aNWUskRBKg:-NasqcgtB8aNWUskRBKh:b47474j) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L270)):*
> ```C
>                  * relevant for our linker */
>                 if (dynamic_section_entry->d_un.d_val != 0) {
>                     log_error("Unexpected DT_DEBUG (must be zero)");
> ```

What's the point of failing here? We don't use it for anything anyways and it's semantically a no-op.
___
*[`pal/src/pal_rtld.c` line 317 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaspSTl7KPX9nrknvLs:-NaspSTm9CEtkjmoeumW:b-aajuou) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L317)):*
> ```C
> 
>     if (!string_table || !string_table_size) {
>         log_error("Loaded binary doesn't have string table or its empty (DT_STRTAB and DT_STRSZ)");
> ```

Is this a problem? I mean, wouldn't the loader clearly fail about this later, when actually trying to use it? And if it doesn't use it, then why failing here?
___
*[`pal/src/pal_rtld.c` line 326 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-Nasotqx8EpWjAtkXDuJ:-Nasotqx8EpWjAtkXDuK:b-po8ydd) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L326)):*
> ```C
>         const char* soname = string_table + soname_offset;
>         if (strcmp(soname, "libsysdb.so") != 0 && strcmp(soname, "libpal.so") != 0) {
>             log_error("Unexpected DT_SONAME (must be name of the LibOS or PAL library)");
> ```

What's the reason for having these checks? Do we rely on `DT_SONAME` being exactly that anywhere?


<!-- Sent from Reviewable.io -->

2023-08-03 07:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: 1 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1473#-NabLI3f7bN_TrD1v2B2):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, now we stopped ignoring semantically meaningful entries, but also try to check unused entries (like debug info) for specific values we expect from our current PAL binary. What's the point of that? This may actually change between compilers and fail our builds.

What I originally meant is that we cannot just ignore some DT entries if they are supposed to be interpreted by the loader (like `DT_NEEDED`). But I don't really see a point in hardcoding in the loader how the PAL binary should look like.
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 270 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-NasqcgtB8aNWUskRBKg:-NauCl3g2M4gI_xwlUXr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of failing here? We don't use it for anything anyways and it's semantically a no-op.
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 317 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-NaspSTl7KPX9nrknvLs:-NauAx381ZQOlf5w9F7w:b-ayw2bz) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this a problem? I mean, wouldn't the loader clearly fail about this later, when actually trying to use it? And if it doesn't use it, then why failing here?
</blockquote></details>

Yes, the loader would clearly fail about this later...

However, I added this check here because I am using `string_table` below, to verify `DT_NEEDED`.
___
*[`pal/src/pal_rtld.c` line 326 at r4](https://reviewable.io/reviews/gramineproject/gramine/1473#-Nasotqx8EpWjAtkXDuJ:-NauCvR11yaxaNfHGd9f:bd1j4ie) ([raw file](https://github.com/gramineproject/gramine/blob/f5799e2591f04a9488225ad9ad5a684ae7f79978/pal/src/pal_rtld.c#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the reason for having these checks? Do we rely on `DT_SONAME` being exactly that anywhere?
</blockquote></details>

Done.

I don't hard-code the SONAMEs anymore, but I memorize the SONAME of the PAL binary now (`libpal.so`), and I compare NEEDED against this SONAME.


<!-- Sent from Reviewable.io -->

2023-08-03 14:03 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 213 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-Navgbby9HbmfdgEGr4E:-Navgbby9HbmfdgEGr4F:bu8gjq6) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L213)):*
It should still be plural:

> The dynamic array can contain multiple entries of this type.



_Suggestion:_
```C
DT_NEEDED entries contain offsets
```
___
*[`pal/src/pal_rtld.c` line 732 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-NavgyOe6qN0kXLDsCha:-NavgyOe6qN0kXLDsChb:bfutn6j) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L732)):*
> ```C
>         return ret;
> 
>     /* find soname of the PAL binary -- will be used during DT_NEEDED verification of other binaries */
> ```

please wrap
___
*[`pal/src/pal_rtld.c` line 738 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-NavhGNF9q9-5wuqajMb:-NavhGNGDYg1AjXiz3Ox:b-gpvs6m) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L738)):*
> ```C
>     while (dynamic_section_entry->d_tag != DT_NULL) {
>         switch (dynamic_section_entry->d_tag) {
>             case DT_SONAME:
> ```

Why not just `if`?



_Code quote:_
```C
        switch (dynamic_section_entry->d_tag) {
            case DT_SONAME:
```


<!-- Sent from Reviewable.io -->

2023-08-03 14:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: 1 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/pal_rtld.c` line 213 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-Navgbby9HbmfdgEGr4E:-NavosJ185qOjyQ9JeSg:bid0dub) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It should still be plural:

> The dynamic array can contain multiple entries of this type.
</blockquote></details>

Done.

Ok, I added one more check to make sure that we only have one `DT_NEEDED` entry -- because in Gramine, we only have one dependency -- the PAL binary. If e.g. LibOS would have two dependencies, then this is not supported by our current loader (and generally I think it would go against the whole Gramine design).
___
*[`pal/src/pal_rtld.c` line 732 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-NavgyOe6qN0kXLDsCha:-Navp_wt8kCcYdNxT70H:b-l3mqsu) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L732)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap
</blockquote></details>

Done. Removed `the` instead because I don't like wrapping.
___
*[`pal/src/pal_rtld.c` line 738 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-NavhGNF9q9-5wuqajMb:-Navpmue9xoeP0z5VAnb:bc7c1r8) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L738)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just `if`?
</blockquote></details>

Done. Copy-paste fail.


<!-- Sent from Reviewable.io -->

2023-08-03 22:23 UTC, mkow reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 738 at r5](https://reviewable.io/reviews/gramineproject/gramine/1473#-NavhGNF9q9-5wuqajMb:-NaxUj7rBmpULYzI_L9O:bln74ba) ([raw file](https://github.com/gramineproject/gramine/blob/e18f91f36e7da2c9148d7b459375672fdc0a2454/pal/src/pal_rtld.c#L738)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Copy-paste fail.
</blockquote></details>

btw. the `break` also didn't work as intended there, it only jumped out of the switch, not the `while` loop.


<!-- Sent from Reviewable.io -->

2023-08-22 20:52 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1473)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv)

___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1473#-NagKrob5KtH0IWHiNyN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will also need to rephrase `unrecognized dyn entries` -> `unrecognized or unexpected/malformed dyn entries`
</blockquote></details>

Done, with slight shortening (it still exceeds the limit, but I don't have any further ideas).


<!-- Sent from Reviewable.io -->

2023-08-23 03:46 UTC, merged