[LibOS] Add "siblings" line to `/proc/cpuinfo`
gramineproject/gramine pull request #1477
Opened 2023-07-31 08:47 UTC by dimakuv

## Description of the changes 

Some libraries fail if they cannot find the "siblings" line (in particular, `libmkl-gnu-thread` aka "Intel MKL OpenMP threading library for GNU Fortran/C compilers"). This may ultimately lead to the application being run on only a subset of available CPUs, hampering performance.

Extracted from https://github.com/gramineproject/gramine/pull/1454.

## How to test this PR? 

Manually using Busybox:

- On original platform:
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
physical id     : 0
siblings        : 12
...
```

- `gramine-direct busybox cat /proc/cpuinfo`, Without this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
physical id     : 0
...   // NO SIBLINGS LINE
```

- `gramine-direct busybox cat /proc/cpuinfo`, With this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
physical id     : 0
siblings        : 12
...
```

2023-07-31 08:56 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-03 01:00 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NassHzTAwXX5AxuMYV_:-NassHzTAwXX5AxuMYVa:b-9yj86m) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L47)):*
> ```C
> 
>     size_t siblings_of_thread = 0;
>     for (size_t j = 0; j < topo->threads_cnt; j++) { // slow, but shouldn't matter
> ```

Why not `i`?



_Code quote:_
```C
size_t j
```
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NastSQ1-cWK590gRZ7b:-NastSQ1-cWK590gRZ7c:b82ya4q) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L51)):*
> ```C
>             siblings_of_thread++;
>     }
>     ADD_INFO("siblings\t: %zu\n", siblings_of_thread * cores_in_socket);
> ```

```C
siblings_of_thread * cores_in_socket
```

This is weeird. What does this number actually represent?


<!-- Sent from Reviewable.io -->

2023-08-03 06:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NassHzTAwXX5AxuMYV_:-Nau9EK-98NhT0f2xlap:bcza5o7) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `i`?
</blockquote></details>

Done. I just copied the logic 5 lines above, and that one used `j` for whatever reason. Fixed both places now.
___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NastSQ1-cWK590gRZ7b:-Nau8LVV9WkPrQBvMHad:bw1lq7c) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

```C
siblings_of_thread * cores_in_socket
```

This is weeird. What does this number actually represent?
</blockquote></details>

The `siblings` number represents the number of logical processors (also called "hardware threads", also called "siblings") on a single CPU package (i.e. on a single socket).

So this number is calculated as:
- Find how many logical processors belong to the same physical core (the loop above); this gives us the number of hyper-threads per core
- multiply by the number of cores on one socket

Linux does it in a more involved way; starting point is here: https://elixir.bootlin.com/linux/v5.14.13/source/arch/x86/kernel/cpu/common.c#L75

Also you can check replies here: https://serverfault.com/questions/326035/what-does-siblings-mean-in-proc-cpuinfo#


<!-- Sent from Reviewable.io -->

2023-08-03 14:18 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NastSQ1-cWK590gRZ7b:-Navji2U397e3AZ7tUpT:bxdrd0v) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `siblings` number represents the number of logical processors (also called "hardware threads", also called "siblings") on a single CPU package (i.e. on a single socket).

So this number is calculated as:
- Find how many logical processors belong to the same physical core (the loop above); this gives us the number of hyper-threads per core
- multiply by the number of cores on one socket

Linux does it in a more involved way; starting point is here: https://elixir.bootlin.com/linux/v5.14.13/source/arch/x86/kernel/cpu/common.c#L75

Also you can check replies here: https://serverfault.com/questions/326035/what-does-siblings-mean-in-proc-cpuinfo#
</blockquote></details>

This multiplication is suspicious, the Linux code you linked to does:
```C
smp_num_siblings = smp_num_siblings / c->x86_max_cores;
```

But in practice it seems to show the total count of threads on a core... What am I missing?

btw. I'd much more prefer if you didn't assume here that all cores have the same number of threads. It is currently true, but removing this assumption in calculations costs nothing - you just want to count all threads in the current socket, so you can just change the if in the counting loop.


<!-- Sent from Reviewable.io -->

2023-08-03 14:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/arch/x86_64/fs_proc/info.c` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1477#-NastSQ1-cWK590gRZ7b:-NavoHRa8Doa8meiWpit:bjtvg06) ([raw file](https://github.com/gramineproject/gramine/blob/77e2199d1557e8deab70d8c2574d2c088a063467/libos/src/arch/x86_64/fs_proc/info.c#L51)):*
> btw. I'd much more prefer if you didn't assume here that all cores have the same number of threads.

Yes, I agree, I currently have this assumption.

> It is currently true, but removing this assumption in calculations costs nothing - you just want to count all threads in the current socket, so you can just change the if in the counting loop.

Well yeah, you're right, this is easier and more readable. I don't know why I didn't consider this. I'll do this.


<!-- Sent from Reviewable.io -->

2023-08-03 15:39 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-22 14:27 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-22 14:28 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1477)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-22 15:33 UTC, merged