[LibOS] Add `/sys/devices/system/cpu/kernel_max` file
gramineproject/gramine pull request #1478
Opened 2023-07-31 08:54 UTC by dimakuv

## Description of the changes 

Extracted from https://github.com/gramineproject/gramine/pull/1454.

## How to test this PR? 

Manually:

- Original:
```
~/gramineproject/gramine/CI-Examples/busybox$ cat /sys/devices/system/cpu/kernel_max
8191
```

- Without this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /sys/devices/system/cpu/kernel_max
cat: can't open '/sys/devices/system/cpu/kernel_max': No such file or directory
```

- With this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /sys/devices/system/cpu/kernel_max
8191
```

2023-07-31 08:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1478#-Naf96ZC24-QN1O0qUhw:-Naf96ZC24-QN1O0qUhx:bq37cxp) (no related file):*
To be honest, in my experiments this pseudo-file turned out to not affect any workload (I was testing on `lscpu` and some proprietary workloads with OpenMP libs). But since this file is trivial to add, I created this PR.

___


<!-- Sent from Reviewable.io -->

2023-07-31 11:54 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/sys/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-NafmU6e39HbzWjIYhA-:-NafmU6e39HbzWjIYhA0:bzawc9w) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L17)):*
> ```C
> 
> #define DEFAULT_KERNEL_MAX_CPUS 8192
> static uint32_t g_kernel_max_cpus = DEFAULT_KERNEL_MAX_CPUS;
> ```

Shouldn't we read this from the original kernel? I believe users can have their own kernel configs with different values.

Not sure, however, what type of workload you think here to add this. 


<!-- Sent from Reviewable.io -->

2023-07-31 14:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`libos/src/fs/sys/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-NafmU6e39HbzWjIYhA-:-NagNuQc0ylbTYEhcsN9:b-i7zsi4) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L17)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Shouldn't we read this from the original kernel? I believe users can have their own kernel configs with different values.

Not sure, however, what type of workload you think here to add this. 
</blockquote></details>

I don't think the host's information is relevant? Gramine is like it's own virtual environment and can show whatever max number of CPUs it wants (as long as this number is internally consistent with the topology information, which I check in this PR too).

There is no workload that depends on this pseudo-file (that I know of). But I was experimenting with sysfs, and noticed that this file is missing. So I decided to add it, as it is very simple and doesn't seem to introduce any side effects.


<!-- Sent from Reviewable.io -->

2023-08-02 01:51 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/fs/sys/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-NafmU6e39HbzWjIYhA-:-Naggpj96vyWhl5Ir0Vk:b-y6nob2) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think the host's information is relevant? Gramine is like it's own virtual environment and can show whatever max number of CPUs it wants (as long as this number is internally consistent with the topology information, which I check in this PR too).

There is no workload that depends on this pseudo-file (that I know of). But I was experimenting with sysfs, and noticed that this file is missing. So I decided to add it, as it is very simple and doesn't seem to introduce any side effects.
</blockquote></details>

Yup, this is our own kernel and our own value.
___
*[`libos/src/fs/sys/fs.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-Nagj3PYCdlninMkI2zN:-Nagj3PYCdlninMkI2zO:b-6qoe5z) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L25)):*
> ```C
>     /* `- 1` because Linux always reports kernel_max like this */
>     int ret = snprintf(str, sizeof(str), "%u\n", g_kernel_max_cpus - 1);
>     if (ret < 0)
> ```

This check is not enough for `snprintf`.


<!-- Sent from Reviewable.io -->

2023-08-02 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @oshogbo)

___
*[`libos/src/fs/sys/fs.c` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-NafmU6e39HbzWjIYhA-:-NapMi3HEyMcqpTVQNcT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, this is our own kernel and our own value.
</blockquote></details>

Done.
___
*[`libos/src/fs/sys/fs.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-Nagj3PYCdlninMkI2zN:-NapMvtCDt37TkD2afCo:biy2850) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This check is not enough for `snprintf`.
</blockquote></details>

I guess you mean that `snprintf()` could also truncate the string to `sizeof(str)`, and we'll have a string without a null byte?

But I intentionally omitted the check for truncation -- we have a 32-byte string buffer, and we print into it a 32-bit unsigned integer + the newline symbol + null byte, which in total can be no more than `10 + 1 + 1 = 12` bytes. (I use `str[32]` as a gigantic over-approximation just in case.)

Or do you still want me to add an explicit truncation check? Or maybe a comment somewhere?


<!-- Sent from Reviewable.io -->

2023-08-03 00:20 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/fs/sys/fs.c` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/1478#-Nagj3PYCdlninMkI2zN:-NaskU6a7jS_zJjtdruC:b3sgn8z) ([raw file](https://github.com/gramineproject/gramine/blob/47865f60a5cea7690bb43887a283e83fbff32453/libos/src/fs/sys/fs.c#L25)):*
> But I intentionally omitted the check for truncation

But you do check for negative ret, so this is very misleading and looks like a bug, not an intentional "we know this function can't fail with these arguments". I'd either ignore `ret` or check it correctly.


<!-- Sent from Reviewable.io -->

2023-08-03 10:18 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2023-08-03 13:57 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-08-21 03:16 UTC, dimakuv reviewed
> Dismissed @oshogbo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2023-08-21 03:21 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1478)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-22 14:20 UTC, merged