[common] Add `onlyif` syntax to flexible IOCTLs
gramineproject/gramine pull request #1482
Opened 2023-08-01 11:59 UTC by dimakuv

## Description of the changes 

Continuation of #671. Last functionality part required.

Fixes #1378.

Depends on:
- https://github.com/gramineproject/device-testing-tools/pull/9
- https://github.com/gramineproject/gramine/pull/1481

## How to test this PR? 

Tests are augmented.

2023-08-10 15:51 UTC, donporter requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/ioctls/ioctls.c` line 219 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV7Exe4A-TlvLPEM_S:-NbV7Exe4A-TlvLPEM_T:b-1ithao) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L219)):*
> ```C
> }
> 
> static int get_sub_region_value(struct sub_region* all_sub_regions, size_t all_sub_regions_cnt,
> ```

Consider adding a comment to each of these new helpers explaining expected behavior?
___
*[`common/src/ioctls/ioctls.c` line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV7U6681k_ddG0HFoQ:-NbV7U6681k_ddG0HFoR:bumlfzk) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L255)):*
> ```C
>     char* cur = expr;
>     while (*cur == ' ' || *cur == '\t')
>         cur++;
> ```

Do we want to guard against reading past the end of the string, similar to strnlen vs strlen?  Or is there some invariant that the string is guaranteed to be null delimited at this point?
___
*[`common/src/ioctls/ioctls.c` line 333 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV8456714hjZ36OKCP:-NbV8456714hjZ36OKCQ:b-3ipc3y) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L333)):*
> ```C
> 
>     if (!(memcmp(compar, "==", 2))) {
>         *out_value = value1 == value2;
> ```

Check/assert out_value for non-null?  Or add a comment to the signature that this param may not be null?
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV6VKU5u1pteMx09mC:-NbV6VKV4STTcj_dhvkA:bi17i2f) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
> ```reStructuredText
>   expressions are ``token1 == token2`` and ``token1 != token2``, where
>   ``token1`` and ``token2`` may be constant non-negative integers or sub-region
>   names.
> ```

Consider showing an example snippet that uses this?


<!-- Sent from Reviewable.io -->

2023-08-21 06:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter)

___
*[`common/src/ioctls/ioctls.c` line 219 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV7Exe4A-TlvLPEM_S:-NcLoaQuCT6m3SOBDMRs:b25krnh) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L219)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider adding a comment to each of these new helpers explaining expected behavior?
</blockquote></details>

We don't have comments for such local functions generally in Gramine. Also, the name of the function (in the context of this file) should be self-explanatory. In this case, the functions "returns the value stored in the IOCTL sub region of the specified name".
___
*[`common/src/ioctls/ioctls.c` line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV7U6681k_ddG0HFoQ:-NcLov821pDcQnNm0y1d:bjvd32v) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L255)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we want to guard against reading past the end of the string, similar to strnlen vs strlen?  Or is there some invariant that the string is guaranteed to be null delimited at this point?
</blockquote></details>

`toml_string_in()` function is guaranteed to return a NULL-terminated string. This function is called in the second line of this function. I see no reason to add any additional checks.
___
*[`common/src/ioctls/ioctls.c` line 333 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV8456714hjZ36OKCP:-NcLpG_N7OtdLcjAotba:b4csosz) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L333)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Check/assert out_value for non-null?  Or add a comment to the signature that this param may not be null?
</blockquote></details>

This is a local function that is used in only place in the code, and it should be obvious from the func signature that it cannot work with `out_value = NULL`. So I don't think we need to do anything here.
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV6VKU5u1pteMx09mC:-NcLpZp77Y-Wgg_ftLvL:b2nnmxm) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider showing an example snippet that uses this?
</blockquote></details>

I already have a big example below for the IOCTL syntax, and I think adding more examples will only "add garbage" to this manifest-syntax page.

There is an example in the LibOS regression test that I added in this PR. We can always point readers to that example, when such a need will arise. Recall that this IOCTL syntax is for "advanced usage" of Gramine, so I doubt casual users will ever care about this `onlyif` stuff.


<!-- Sent from Reviewable.io -->

2023-08-22 19:25 UTC, donporter approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`common/src/ioctls/ioctls.c` line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NbV7U6681k_ddG0HFoQ:-NcThCuHAChcEK91bEEC:b-xyiidl) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`toml_string_in()` function is guaranteed to return a NULL-terminated string. This function is called in the second line of this function. I see no reason to add any additional checks.
</blockquote></details>

Thanks!  I suppose some of the review is getting me caught up :)


<!-- Sent from Reviewable.io -->

2023-08-22 23:59 UTC, mkow requested changes
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 4 unresolved discussions (waiting on @dimakuv)

___
*[`common/src/ioctls/ioctls.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUdKEa7lOvJ4d3LZEM:-NcUdKEa7lOvJ4d3LZEN:bwttipb) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.h#L89)):*
> ```objc
>  * 10. Sub-regions may be conditioned using `onlyif = "simple boolean expression"`. The only
>  *     currently supported format of expressions are (`token1` and `token2` may be constant
>  *     non-negative integers or sub-region names):
> ```

// Alternatively you can move the parenthesis to below the list if you like this idea.



_Suggestion:_
```objc
 *     currently supported format of expressions are: (`token1` and `token2` may be constant
 *     non-negative integers or sub-region names)
```
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUfQfZ0rnT5lhx_nyN:-NcUfQfZ0rnT5lhx_nyO:b-hshn7r) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
> or sub-region names.

How are they interpreted then? What if the name points to e.g. a 11-bytes-long buffer? The examples indicate that an integer is generated from them, but how exactly?
___
*[`libos/test/regression/device_ioctl.c` line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUewrS3rE-34iIwwbz:-NcUewrT68TmDmobyBxt:bo4im9z) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/libos/test/regression/device_ioctl.c#L152)):*
> ```C
>         .do_set = 1, /* set size to zero */
>         .size   = 0
>     };
> ```

Could you make the _set_ arg struct `static const`? It should land in `.rodata` then and we'll be able to detect when Gramine tries to write anything there (while it shouldn't).
___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUdnNo6CH8y_rAPA5K:-NcUdnNp7Ycyb58H8WMx:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/libos/test/regression/device_ioctl_parse_fail.manifest.template#L57)):*
> ```
> # Expression in `onlyif` field must be in format "token1 {== | !=} token2"
> sys.ioctl_structs.bad_onlyif_expr = [
>     { onlyif= "42 === 24", size = 1 },
> ```





_Suggestion:_
```
{ onlyif = "42 === 24", size = 1 },
```


<!-- Sent from Reviewable.io -->

2023-08-23 15:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: 4 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

___
*[`common/src/ioctls/ioctls.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUdKEa7lOvJ4d3LZEM:-NcXmM1F5C43ipOPXEBF:b6tadjx) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.h#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

// Alternatively you can move the parenthesis to below the list if you like this idea.
</blockquote></details>

Done. It looks weird to me, but ok.
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUfQfZ0rnT5lhx_nyN:-NcXmzil5Vgz3ynycUsa:b-8wovu) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> or sub-region names.

How are they interpreted then? What if the name points to e.g. a 11-bytes-long buffer? The examples indicate that an integer is generated from them, but how exactly?
</blockquote></details>

Done. Does that sound good?
___
*[`libos/test/regression/device_ioctl.c` line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUewrS3rE-34iIwwbz:-NcXu2O3AeakxLyLlV8_:bi3hcuw) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/libos/test/regression/device_ioctl.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you make the _set_ arg struct `static const`? It should land in `.rodata` then and we'll be able to detect when Gramine tries to write anything there (while it shouldn't).
</blockquote></details>

Done. I manually verified that the variable landed in `.rodata` now, using objdump.
___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUdnNo6CH8y_rAPA5K:-NcXuLP1AWISQY6hW19P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/libos/test/regression/device_ioctl_parse_fail.manifest.template#L57)):*
> ```
> # Expression in `onlyif` field must be in format "token1 {== | !=} token2"
> sys.ioctl_structs.bad_onlyif_expr = [
>     { onlyif= "42 === 24", size = 1 },
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 00:47 UTC, mkow requested changes
> Reviewed 1 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/ioctls/ioctls.h` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUdKEa7lOvJ4d3LZEM:-NcY48oM4Ljz01YhLVP6:b-7dftmv) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/common/src/ioctls/ioctls.h#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. It looks weird to me, but ok.
</blockquote></details>

The problem with the old version is that one (or at least me) read it like the parenthesis was part of the sentence and either expands on something mentioned already (as the usual parentheses do) or it was actually the syntax presented, but with weird formatting.
___
*[`common/src/ioctls/ioctls.c` line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYDsvz9BZaaunTVaQ7:-NcYDsw-2WPj34eLqPan:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L219)):*
> ```C
> }
> 
> static int get_sub_region_value(struct sub_region* all_sub_regions, size_t all_sub_regions_cnt,
> ```





_Suggestion:_
```C
get_sub_region_uint_value
```
___
*[`common/src/ioctls/ioctls.c` line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYMnB54PjdWWcdj1WM:-NcYMnB54PjdWWcdj1WN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L227)):*
> ```C
> 
>     void* addr_of_value_field  = all_sub_regions[found_idx].gramine_addr;
>     size_t size_of_value_field = all_sub_regions[found_idx].size;
> ```





_Suggestion:_
```C
    void*  addr_of_value_field = all_sub_regions[found_idx].gramine_addr;
    size_t size_of_value_field = all_sub_regions[found_idx].size;
```
___
*[`common/src/ioctls/ioctls.c` line 230 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYNF4E-rBHTJYlcGma:-NcYNF4F18gdw2miVoaX:bewutwl) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L230)):*
> ```C
>     uint64_t read_value;
> 
>     ret = copy_value(addr_of_value_field, size_of_value_field, &read_value);
> ```

Ok, now that I'm reading this code after some time after the original PR I really think that `copy_value()` is confusing - now I thought it just copies memory and that you leave some bytes in `read_value` uninitialized, while what it actually does is reading `size_of_value_field` bytes as native-endian and then zero-extending them to 64-bits.
Maybe at least rename to `copy_value_to_uint64()`?
___
*[`common/src/ioctls/ioctls.c` line 296 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZwZ33CrsJBR2blfYI:-NcZwZ33CrsJBR2blfYJ:bh19ihw) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L296)):*
> ```C
>     /* get actual values for two tokens */
>     char* endptr = NULL;
>     token1[token1_len] = '\0';
> ```

That's quite hacky, it will overwrite the first character of `compar` if there are no spaces. I know that you don't use it anymore, but looks quite contrived.
___
*[`common/src/ioctls/ioctls.c` line 315 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZzF4hDMxXZ1A8ASK6:-NcZzF4hDMxXZ1A8ASK7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L315)):*
> ```C
>     }
> 
>     token2[token2_len] = '\0';
> ```

ditto
___
*[`common/src/ioctls/ioctls.c` line 332 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZzJEo9ZnREQNuK1PV:-NcZzJEo9ZnREQNuK1PW:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L332)):*
> ```C
>     }
> 
>     if (!(memcmp(compar, "==", 2))) {
> ```





_Suggestion:_
```C
if (!memcmp(compar, "==", 2)) {
```
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUfQfZ0rnT5lhx_nyN:-NcY4kjX7DoDKEBdysLK:bqsm6ws) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Does that sound good?
</blockquote></details>

Yup, looks better, but maybe also mention endianess? It's always native or always little-endian?
___
*[`libos/test/regression/device_ioctl.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcY50Gi24G1dVsv4pm7:-NcY50Gj3NQwcMiDOw_q:b-8fpb76) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/libos/test/regression/device_ioctl.c#L151)):*
> ```C
>     /* use a static const variable so that it is put into the .rodata section and thus protected
>      * against writes -- this is to catch bugs if Gramine IOCTL logic tries to write into it */
>     static const struct gramine_test_dev_ioctl_get_set_size static_set_size = {
> ```

(the most important part about it is that it's const)



_Suggestion:_
```C
const_set_size
```


<!-- Sent from Reviewable.io -->

2023-08-24 04:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: 4 of 8 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

___
*[`common/src/ioctls/ioctls.c` line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYDsvz9BZaaunTVaQ7:-Nc_mYMb8xc4cKVh3LEL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L219)):*
> ```C
> }
> 
> static int get_sub_region_value(struct sub_region* all_sub_regions, size_t all_sub_regions_cnt,
> ```

Done.
___
*[`common/src/ioctls/ioctls.c` line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYMnB54PjdWWcdj1WM:-Nc_mLvO6m9kKiduEIFr:biq5uvk) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L227)):*
> ```C
> 
>     void* addr_of_value_field  = all_sub_regions[found_idx].gramine_addr;
>     size_t size_of_value_field = all_sub_regions[found_idx].size;
> ```

Done. And in other similar places too.
___
*[`common/src/ioctls/ioctls.c` line 230 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcYNF4E-rBHTJYlcGma:-Nc_mLKLE02keN-L1zxQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L230)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, now that I'm reading this code after some time after the original PR I really think that `copy_value()` is confusing - now I thought it just copies memory and that you leave some bytes in `read_value` uninitialized, while what it actually does is reading `size_of_value_field` bytes as native-endian and then zero-extending them to 64-bits.
Maybe at least rename to `copy_value_to_uint64()`?
</blockquote></details>

Done.
___
*[`common/src/ioctls/ioctls.c` line 296 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZwZ33CrsJBR2blfYI:-Nc_q0jQ2_4oma_FQ1-Q:bgdtjjj) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L296)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's quite hacky, it will overwrite the first character of `compar` if there are no spaces. I know that you don't use it anymore, but looks quite contrived.
</blockquote></details>

Done. It was actually a bug, because I'm using `compar` later, during memcmp. I checked, and indeed my test failed with `onlyif = "1==0"` spacing. I hardened the code and the test now, to catch these spacing problems.
___
*[`common/src/ioctls/ioctls.c` line 315 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZzF4hDMxXZ1A8ASK6:-Nc_qCyYA1IyHgegSvtc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L315)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`common/src/ioctls/ioctls.c` line 332 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZzJEo9ZnREQNuK1PV:-Nc_mc0ZEF_ICabtNylV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L332)):*
> ```C
>     }
> 
>     if (!(memcmp(compar, "==", 2))) {
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcUfQfZ0rnT5lhx_nyN:-Nc_ms1u5E6MMrh8UACu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/518d2985fb6f9a07e2be95a1f8f8e8e57c7339e3/Documentation/manifest-syntax.rst#L536)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, looks better, but maybe also mention endianess? It's always native or always little-endian?
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 151 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcY50Gi24G1dVsv4pm7:-Nc_ludI2KX9eXcvOFks:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/libos/test/regression/device_ioctl.c#L151)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(the most important part about it is that it's const)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 14:42 UTC, mkow requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/ioctls/ioctls.c` line 296 at r2](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcZwZ33CrsJBR2blfYI:-NcbxSlU-JIcbjhYmU-W:balgk4v) ([raw file](https://github.com/gramineproject/gramine/blob/7151c7a8470164a08e2ab182f80b6e47ed5a5653/common/src/ioctls/ioctls.c#L296)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. It was actually a bug, because I'm using `compar` later, during memcmp. I checked, and indeed my test failed with `onlyif = "1==0"` spacing. I hardened the code and the test now, to catch these spacing problems.
</blockquote></details>

Hah, nice :D
___
*[`common/src/ioctls/ioctls.c` line 341 at r3](https://reviewable.io/reviews/gramineproject/gramine/1482#-Ncbz3nAED9yHsOSCWKh:-Ncbz3nAED9yHsOSCWKi:b-ovwawk) ([raw file](https://github.com/gramineproject/gramine/blob/30bff30413b25c5f4c41ddb3ea87d2efb3618ae1/common/src/ioctls/ioctls.c#L341)):*
> ```C
>         *out_value = value1 != value2;
>     } else {
>         BUG();
> ```

Good idea!
___
*[`Documentation/manifest-syntax.rst` line 537 at r3](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcbzOTc6b326YAHzMal:-NcbzOTc6b326YAHzMam:b1wxioc) ([raw file](https://github.com/gramineproject/gramine/blob/30bff30413b25c5f4c41ddb3ea87d2efb3618ae1/Documentation/manifest-syntax.rst#L537)):*
> ```reStructuredText
>   ``token1`` and ``token2`` may be constant non-negative integers or sub-region
>   names (referenced sub-regions must contain a native-endian non-negative
>   integer value of size 1..8B).
> ```

Hmm, this "non-negative" is confusing IMO, it suggests that you interpret it as signed and then refuse negative values, while you actually just interpret it as unsigned.



_Code quote:_
```reStructuredText
  names (referenced sub-regions must contain a native-endian non-negative
  integer value of size 1..8B).
```


<!-- Sent from Reviewable.io -->

2023-08-24 16:06 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-08-24 16:28 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please (rebooted the machine, it got newer Linux kernel)

2023-08-24 18:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: 8 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1482#-Nccj87-293AJlyv0PxO:-Nccj87-293AJlyv0PxP:b-8t4ion) (no related file):*
I'll need to fix this error:
```
 ../libos/test/regression/gramine\_test\_dev\_ioctl.h:46:5: error: unknown type name uint8_t
```

Adding `#include <stdint.h>` to `device_ioctl_parse_fail.c` should be enough.

___
___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcciOil-Z-Q0OASucCg):*
I will need to extract this commit in a separate PR, and the current PR must be blocked on that new PR's merge.

This is because this PR fixes a rather-long-standing problem of `linux-sgx-vm-gcc-release` pipeline (which got broken maybe a month ago because of the mismatch between the host OS and the in-Docker OS). The mismatch got fixed by Woju by updating the host OS, but then we also need corresponding changes in CI files.


<!-- Sent from Reviewable.io -->

2023-08-25 03:22 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2023-08-25 03:38 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release  please

2023-08-25 03:39 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please

2023-08-29 03:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: 6 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @donporter and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1482#-Nccj87-293AJlyv0PxO:-NczMq7wDPMy4TWjCmW7:b-o841im) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll need to fix this error:
```
 ../libos/test/regression/gramine\_test\_dev\_ioctl.h:46:5: error: unknown type name uint8_t
```

Adding `#include <stdint.h>` to `device_ioctl_parse_fail.c` should be enough.
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/1512

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1482#-NczMv9p70eWZGQEdu3e:-NczMv9p70eWZGQEdu3f:b40igh3) (no related file):*
Rebased to latest master (that has the fix for `linux-sgx-vm-gcc-release` pipeline).

___
___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/1482#-NcciOil-Z-Q0OASucCg):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will need to extract this commit in a separate PR, and the current PR must be blocked on that new PR's merge.

This is because this PR fixes a rather-long-standing problem of `linux-sgx-vm-gcc-release` pipeline (which got broken maybe a month ago because of the mismatch between the host OS and the in-Docker OS). The mismatch got fixed by Woju by updating the host OS, but then we also need corresponding changes in CI files.
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/1512


<!-- Sent from Reviewable.io -->

2023-08-29 07:47 UTC, kailun-qin approved these changes
> Reviewed 2 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/ioctls/ioctls.h` line 88 at r7](https://reviewable.io/reviews/gramineproject/gramine/1482#-Nd-61RG7kwHWf40yuQR:-Nd-61RG7kwHWf40yuQS:b-7jwx6m) ([raw file](https://github.com/gramineproject/gramine/blob/e1d7c359fdef27d2c523bc321c68ef690a507e0b/common/src/ioctls/ioctls.h#L88)):*
> ```objc
>  *     is 1 byte and `adjustment` is 0. Note that `adjustment` may be a negative number.
>  * 10. Sub-regions may be conditioned using `onlyif = "simple boolean expression"`. The only
>  *     currently supported format of expressions are: (`token1` and `token2` may be constant
> ```

nit: formats



_Code quote:_
```objc
format
```


<!-- Sent from Reviewable.io -->

2023-08-29 18:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-08-29 18:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1482)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`common/src/ioctls/ioctls.h` line 88 at r7](https://reviewable.io/reviews/gramineproject/gramine/1482#-Nd-61RG7kwHWf40yuQR:-Nd1VB4X3gJqUvJmr-6F:b-uxm8aw) ([raw file](https://github.com/gramineproject/gramine/blob/e1d7c359fdef27d2c523bc321c68ef690a507e0b/common/src/ioctls/ioctls.h#L88)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

nit: formats
</blockquote></details>

I actually think that my version is correct English, so I won't change.


<!-- Sent from Reviewable.io -->

2023-08-29 18:17 UTC, merged