[Docs] Update installation steps for DCAP dependencies
gramineproject/gramine pull request #1500
Opened 2023-08-21 13:47 UTC by jkr0103

## Description of the changes 

Installation steps for DCAP dependencies were specific to Ubuntu 18.04 which is not supported now, hence updated the steps for Ubuntu 20.04 and 22.04.

## How to test this PR? 

Check the build section in Gramine documentation: https://gramine.readthedocs.io/en/latest/devel/building.html

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1500)

2023-08-21 16:26 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNu8BE81LK7NY9sp1n):*
Please add in the commit message what you wrote in the PR description (that the steps were written for 18.04 which is removed now)
___
*[`Documentation/devel/building.rst` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuKjQ6sCTbbR97K6e:-NcNuKjQ6sCTbbR97K6f:by5ray6) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L19)):*
> ```reStructuredText
> 
> Gramine currently only works on the x86_64 architecture. Gramine is currently
> tested on Ubuntu 18.04/20.04, along with Linux kernel version 5.x. We recommend
> ```

Could you fix this to `on Ubuntu 20.04/22.04`
___
*[`Documentation/devel/building.rst` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuQdf3W2TNEtnJOC_:-NcNuQdf3W2TNEtnJOCa:b-34m92t) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L111)):*
> ```reStructuredText
> 
> If you plan on enabling ``-Ddcap`` option, you need to install
> ``libsgx-dcap-quote-verify`` package (and it's development counterpart)::
> ```

Since we're here: `it's` -> `its`
___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-NcNuobdDMa1eWawbxzX:b-2yrxog) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
> ```reStructuredText
> ``libsgx-dcap-quote-verify`` package (and it's development counterpart)::
> 
>    # Below commands work on Ubuntu 22.04 LTS and 20.04 LTS
> ```

In the beginning of this doc, we already mention that we use Ubuntu 20.04 and 22.04, so I would remove this comment here.
___
*[`Documentation/devel/building.rst` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuaJxDN1cClEPTZmC:-NcNuaJxDN1cClEPTZmD:bwe0k7d) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L115)):*
> ```reStructuredText
>    # Below commands work on Ubuntu 22.04 LTS and 20.04 LTS
>    sudo curl -fsSLo /usr/share/keyrings/intel-sgx-deb.asc https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
>    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu $(lsb_release -sc) main" \
> ```

I'd like to summon @woju to check the correctness of using `sudo` and other stuff


<!-- Sent from Reviewable.io -->

2023-08-22 09:02 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @jkr0103)

___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-NcRQQYF1OwZ8doOnG5n:b3et9gy) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the beginning of this doc, we already mention that we use Ubuntu 20.04 and 22.04, so I would remove this comment here.
</blockquote></details>

Alternatively you can extend this comment to also describe Debian proper. The problem with Intel's repo is that it only provides Ubuntu codenames, so `$(lsb_release -sc)` does not work for debian. Instead you need to substitute respective Ubuntu release (`focal` for `bullseye` and `jammy` for `bookworm`, see 1.5 release notes for correct stanzas).

Your choice, I'm not insisting if you say it's out of scope.
___
*[`Documentation/devel/building.rst` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuaJxDN1cClEPTZmC:-NcRQBdc9ui6ZyZUOWdF:bbouwj6) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd like to summon @woju to check the correctness of using `sudo` and other stuff
</blockquote></details>

LGTM.

If you really want, you could avoid running `curl` with `sudo`, instead pipe the key to stdout and only run `sudo tee` like with repo line below:

```sh
curl -fsSL https://... | sudo tee /usr/share/keyrings/intel-sgx-deb.asc
```

I'm not sure how much of improvement that would be. Technically this avoids running network code with elevated privileges, but if attacker has capability to exploit curl, then s/he can make it output another key, and we don't instruct the user to verify, e.g. key fingerprint. We suggest `sudo curl` in release notes, so that would be a change from that. I think `sudo curl -o` is cleaner than `curl | sudo tee`, so if you don't know, I'd say we leave it like that. `echo | sudo tee` is unavoidable: `sudo echo >` won't work anyway, because you'd really need `sudo` to `>` operator, and it doesn't work that way.


<!-- Sent from Reviewable.io -->

2023-08-23 16:24 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)

___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-NcYCBFy3lQQjiULgp0W:b-8nnvct) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Alternatively you can extend this comment to also describe Debian proper. The problem with Intel's repo is that it only provides Ubuntu codenames, so `$(lsb_release -sc)` does not work for debian. Instead you need to substitute respective Ubuntu release (`focal` for `bullseye` and `jammy` for `bookworm`, see 1.5 release notes for correct stanzas).

Your choice, I'm not insisting if you say it's out of scope.
</blockquote></details>

Well, I'd say it's out of scope of this PR.
___
*[`Documentation/devel/building.rst` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuaJxDN1cClEPTZmC:-NcYCQ8F8f4YBzJ6eCcJ:b42188t) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L115)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

LGTM.

If you really want, you could avoid running `curl` with `sudo`, instead pipe the key to stdout and only run `sudo tee` like with repo line below:

```sh
curl -fsSL https://... | sudo tee /usr/share/keyrings/intel-sgx-deb.asc
```

I'm not sure how much of improvement that would be. Technically this avoids running network code with elevated privileges, but if attacker has capability to exploit curl, then s/he can make it output another key, and we don't instruct the user to verify, e.g. key fingerprint. We suggest `sudo curl` in release notes, so that would be a change from that. I think `sudo curl -o` is cleaner than `curl | sudo tee`, so if you don't know, I'd say we leave it like that. `echo | sudo tee` is unavoidable: `sudo echo >` won't work anyway, because you'd really need `sudo` to `>` operator, and it doesn't work that way.
</blockquote></details>

Ok, thanks for the review, let's leave it like that.


<!-- Sent from Reviewable.io -->

2023-08-24 02:08 UTC, mkow reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)



<!-- Sent from Reviewable.io -->

2023-08-24 04:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-Nc_tKiVEnQHJEc_OeJO:b-nzbi25) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, I'd say it's out of scope of this PR.
</blockquote></details>

On second thought, searching for Ubuntu mentions at the top of the document is cumbersome (and not something casual readers will do). I'm resolving my comment, I guess this comment line is useful.


<!-- Sent from Reviewable.io -->

2023-08-24 05:34 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNu8BE81LK7NY9sp1n):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add in the commit message what you wrote in the PR description (that the steps were written for 18.04 which is removed now)
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuKjQ6sCTbbR97K6e:-Nca1Fyl8wrufs7Mntpm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you fix this to `on Ubuntu 20.04/22.04`
</blockquote></details>

Done.
___
*[`Documentation/devel/building.rst` line 111 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuQdf3W2TNEtnJOC_:-Nca1Gca25L_xCxjaNWf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here: `it's` -> `its`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 14:27 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcbvHkD296LAVu8ggaG):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change to imperative mood.
</blockquote></details>

I'll do it during final rebase now.


<!-- Sent from Reviewable.io -->

2023-08-24 14:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-Ncbvrj2DoKPVCyfHvAD:b-zes9j3) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

On second thought, searching for Ubuntu mentions at the top of the document is cumbersome (and not something casual readers will do). I'm resolving my comment, I guess this comment line is useful.
</blockquote></details>

Well, this PR adds support for new supported Ubuntu version, so I think we should at least answer the question why it's out of scope to add also Debian, which is equally supported.


<!-- Sent from Reviewable.io -->

2023-08-24 14:31 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/building.rst` line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcNuobdDMa1eWawbxzW:-NcbwnYy3UMycqr5VJGw:b-5fh6ed) ([raw file](https://github.com/gramineproject/gramine/blob/17a73d1c5fc50046ee9d2f49eecbd44fe415d40c/Documentation/devel/building.rst#L113)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Well, this PR adds support for new supported Ubuntu version, so I think we should at least answer the question why it's out of scope to add also Debian, which is equally supported.
</blockquote></details>

@woju In my opinion, in this document we should concentrate on one OS distro, otherwise we would need to add explanations for RHEL/CentOS family of distros too, not only Debian. And probably even mention that there is no `libsgx-dcap-quote-verify` package for Alpine yet. So to me, it will introduce a lot of noise. And hopefully if a person lands on this page, she knows how to map commands from one distro to her own distro.


<!-- Sent from Reviewable.io -->

2023-08-24 14:32 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1500#-NcbvHkD296LAVu8ggaG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll do it during final rebase now.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-24 15:07 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-24 15:31 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1500)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-24 16:32 UTC, merged