[PAL] Recognize `DT_BIND_NOW` dynamic entry
gramineproject/gramine pull request #1508
Opened 2023-08-24 03:53 UTC by dimakuv

## Description of the changes 

Some compilers/linkers generate the `DT_BIND_NOW` entry instead of adding a flag `DF_BIND_NOW` to the `DT_FLAGS` entry. Since our linker anyway always performs all relocations immediately (not lazily), this entry is a no-op.

It looks like some compilers use `DT_BIND_NOW`, though this particular dynentry was superseded by a flag `DF_BIND_NOW`. At the same time, this dynentry simply means "use immediate binding instead of lazy binding" (lazy binding is the default for linkers). And our Gramine-internal linker always uses immediate binding. So we can simply ignore `DT_BIND_NOW` dynentry, as it just hints at what Gramine is doing anyway.

References:
- http://www.qnx.com/developers/docs/qnxcar2/index.jsp?topic=%2Fcom.qnx.doc.neutrino.prog%2Ftopic%2Fdevel_Lazy_binding.html
- https://github.com/gramineproject/gramine/blob/a8edb2e17d7b9e95ff46e8ee4dcee47447808f33/libos/src/meson.build#L159?plain=1
- https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-42444.html
- https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter3-29.html#chapter3-4

See also https://github.com/gramineproject/gramine/discussions/1487#discussioncomment-6808455 for the context and explanations.

See https://github.com/gramineproject/gramine/pull/1473 for the original version of the changes.

## How to test this PR? 

Find a compiler that generates `DT_BIND_NOW`. My GCC 10.5 doesn't generate it but instead it generates the flag:
```
$ readelf -a built-debug/lib/x86_64-linux-gnu/gramine/direct/libpal.so
...
Dynamic section at offset 0x3bec0 contains 16 entries:
  Tag        Type                         Name/Value
  ...
 0x000000000000001e (FLAGS)              BIND_NOW
```

2023-08-24 06:15 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-NcaAipRE51VQfg5j-5B:-NcaAipSC5PmPDsQEkhc:b-xzsxy0) ([raw file](https://github.com/gramineproject/gramine/blob/827a532c4db51c99a182cc3b36a59b75ce33ca36/pal/src/pal_rtld.c#L16)):*
> ```C
>  *     Corresponding linker flag is `-Wl,-zrelro`.
>  *
>  *   - They must be linked with immediate binding (in constrast to the linker's default lazy
> ```

-> `contrast`



_Code quote:_
```C
constrast
```


<!-- Sent from Reviewable.io -->

2023-08-24 13:43 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-NcblLtr4loh5BXPqQOg:-NcblLtr4loh5BXPqQOh:b-oxydc2) ([raw file](https://github.com/gramineproject/gramine/blob/a8edb2e17d7b9e95ff46e8ee4dcee47447808f33/pal/src/pal_rtld.c#L14)):*
> ```C
>  *     only R_X86_64_RELATIVE, R_X86_64_GLOB_DAT and R_X86_64_JUMP_SLOT reloc schemes are used. If
>  *     we add support for archs other than x86_64 in future, we need to add more reloc schemes.
>  *     Corresponding linker flags are `-Wl,-zrelro -Wl,-znow`.
> ```

Why have you removed `-znow` from here?
___
*[`pal/src/pal_rtld.c` line 271 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-Ncblhv32XZ-zTO0T1s0:-Ncblhv4AAyTX-_46-Uf:b-sfskqz) ([raw file](https://github.com/gramineproject/gramine/blob/827a532c4db51c99a182cc3b36a59b75ce33ca36/pal/src/pal_rtld.c#L271)):*
> ```C
>                 break;
>             case DT_BIND_NOW:
>                 /* unused, our code always uses immediate binding (doesn't support lazy binding) */
> ```

Just a note, not sure if worth adding anywhere to the comments: This isn't a performance-only flag, if we decide to have lazy bindings at some point then we'll need to implement it. RELRO changes page permissions after relocations, so this breaks lazy relocations.
But probably not worth commenting, I think it's rather obvious and would be detected if we were to implement laziness.


<!-- Sent from Reviewable.io -->

2023-08-24 14:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/pal_rtld.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-NcblLtr4loh5BXPqQOg:-Ncc-8hM3SVkevxKah9w:b9fhcmh) ([raw file](https://github.com/gramineproject/gramine/blob/a8edb2e17d7b9e95ff46e8ee4dcee47447808f33/pal/src/pal_rtld.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you removed `-znow` from here?
</blockquote></details>

Done. I didn't want duplication of flags. But I guess what you're asking is -- we're implementing Full RELRO, so both flags need to be specified in this comment.
___
*[`pal/src/pal_rtld.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-NcaAipRE51VQfg5j-5B:-Ncc-KGmB0Ij-XvwUM7d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/827a532c4db51c99a182cc3b36a59b75ce33ca36/pal/src/pal_rtld.c#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `contrast`
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 271 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-Ncblhv32XZ-zTO0T1s0:-NcbzIuJ5a4PbT3NM9Ak:bf4u3db) ([raw file](https://github.com/gramineproject/gramine/blob/827a532c4db51c99a182cc3b36a59b75ce33ca36/pal/src/pal_rtld.c#L271)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just a note, not sure if worth adding anywhere to the comments: This isn't a performance-only flag, if we decide to have lazy bindings at some point then we'll need to implement it. RELRO changes page permissions after relocations, so this breaks lazy relocations.
But probably not worth commenting, I think it's rather obvious and would be detected if we were to implement laziness.
</blockquote></details>

Yes, I agree that because of RELRO, we'll have read-only pages, and lazy relocations would need to temporarily change these permissions.

But also, sounds like a very technical detail; I don't see a reason to add this comment here.


<!-- Sent from Reviewable.io -->

2023-08-24 14:59 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-24 16:09 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/src/pal_rtld.c` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1508#-NcblLtr4loh5BXPqQOg:-NccI_Lx8qEc89d-xvF8:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/a8edb2e17d7b9e95ff46e8ee4dcee47447808f33/pal/src/pal_rtld.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I didn't want duplication of flags. But I guess what you're asking is -- we're implementing Full RELRO, so both flags need to be specified in this comment.
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2023-08-24 23:59 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-25 00:22 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1508)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-25 02:49 UTC, dimakuv commented
FYI: `pkg-deb-debian12` pipeline failed because of the Docker seccomp mismatch on the Jenkins worker (some Jenkins workers have a Linux host version that is incompatible with our Docker seccomp). This is unrelated to the PR.

2023-08-25 02:51 UTC, merged