[Pal] Rework ELF parsing/RTLD code
gramineproject/gramine pull request #152
Opened 2021-10-18 08:47 UTC by dimakuv

## Description of the changes 

This PR completely reworks the code to load ELF binaries into the memory and link them against each other. Note that PAL loads only two kinds of ELF binaries: the LibOS shared library and the PAL regression tests. This allows us to simplify the code by posing the following restrictions:

- ELF binaries must be linked with RELRO (Relocation Read-Only).
- They must have old-style hash (DT_HASH) table (new code doesn't use hashing at all; the table is needed solely to figure out the number of dynamic symbols in the SYMTAB).
- They must have DYN or EXEC object file type.

Closes #86.

## How to test this PR? 

All tests must pass. Also, try GDBing manually.

As a side effect, some previously-disabled PAL tests are enabled.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/152)

2021-10-18 15:20 UTC, mkow requested changes
> Reviewed 13 of 28 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/152)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/152#-MmInUDBCPo6mvtzEw7W:-MmIt3lc-B94PfDIIeYe:bpzu80z) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Great PR! It's really good to see these GNU parts finally gone.
</blockquote></details>

Finally!

---
___
*[LibOS/shim/src/meson.build, line 146 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIt_Ea3YcX-v6Y4aNy:-MmIt_Eb3r157BUk_Xwh:bo9qeoa) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/LibOS/shim/src/meson.build#L146)):*
> ```Meson
>     link_args: [
>         '-nostdlib',
>         '-Wl,--hash-style=both',
> ```

Could you document here why you need this flag? (just copying the relevant part from the commit message should suffice)
___
*[Pal/include/pal_rtld.h, line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIwGBREZsj0EAoHn84:-MmIwGBREZsj0EAoHn85:br9bny4) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/include/pal_rtld.h#L32)):*
> ```
> PRELOAD for LibOS lib
> ```

Why LibOS isn't an EXEC? We could get rid of PRELOAD support, plus it seems that it makes more sense this way.
___
*[Pal/include/elf/elf.h, line 2644 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmITOjMBVKW5qhoOOpw:-MmIwePW9cz8ICAtmnYL:b-8dwrzv) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/include/elf/elf.h#L2644)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What do you think about creating explicit typedefs? E.g. `ElfW_Addr` instead of `ElfW(Addr)`, or even [using the same names as Linux](https://elixir.bootlin.com/linux/latest/source/include/linux/elf.h).

I remember @mkow saying we should do it, and I think it would make some static analysis tools slightly happier (e.g. syntax highlighting).

I'm not blocking, and not saying we should do it right now, just curious about your opinion.
</blockquote></details>

+1, these typedef are super ugly and probably useful only for even worse macro hacking (like including one header twice with different macros defined :) )
___
*[Pal/regression/Makefile, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/152#-MmHbTl_DB_evvZHI-yz:-MmIx3O2-NtVj_7pgtdd:b9gghhq) ([raw file](https://github.com/gramineproject/gramine/blob/65ff3f587cf24d4a2629e6aa029fb5588c06d979/Pal/regression/Makefile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: GCC toolchain (and pretty sure Clang as well) generates `DT_GNU_HASH` by default, which is a super-complicated struct. In this PR, I abandon search-by-hash completely (because we only have like 40 Dk functions which we resolve at startup anyway) and thus I need legacy `DT_HASH` to extract "number of dynamic symbols". For more info, see https://flapenguin.me/elf-dt-hash and https://flapenguin.me/elf-dt-gnu-hash
</blockquote></details>

+1 to this decision
___
*[Pal/regression/Makefile, line 125 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIx7Xb6CcQ9R6W0DC4:-MmIx7Xc5KHKgQzoPbQX:b6r5wci) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/regression/Makefile#L125)):*
> ```Makefile
> LDLIBS-preloads = crt_init/user_shared_start.o utils.o $(common_objs) $(pal_lib)
> $(preloads): %.so: %.c $(LDLIBS-preloads)
> 	$(call cmd,csingle) -Wl,--hash-style=both -shared -fPIC $(LDLIBS-preloads)
> ```

ditto, please comment
___
*[Pal/regression/Makefile, line 129 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIx9E8EYcgYTyvhMqY:-MmIx9E8EYcgYTyvhMqZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/regression/Makefile#L129)):*
> ```Makefile
> LDLIBS-executables = crt_init/user_start.o utils.o $(common_objs) $(pal_lib) $(preloads)
> $(executables): %: %.c $(LDLIBS-executables)
> 	$(call cmd,csingle) -Wl,--hash-style=both -no-pie $(LDLIBS-executables)
> ```

ditto
___
*[Pal/src/db_rtld.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/152#-MmHaxhK9cnx8RXaWpv6:-MmIxjh_98nLUgulhZzu:bekb2uo) ([raw file](https://github.com/gramineproject/gramine/blob/65ff3f587cf24d4a2629e6aa029fb5588c06d979/Pal/src/db_rtld.c#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah... But looking at the code, supporting multiple loaded maps doesn't seem to change much.
</blockquote></details>

Can we simply drop these preload tests? This whole feature seems useless.
___
*[Pal/src/db_rtld.c, line 844 at r1](https://reviewable.io/reviews/gramineproject/gramine/152#-MmHa18w5xof8j6yNBmt:-MmIycTE3GbddzV0ZNmX:b-f2i798) ([raw file](https://github.com/gramineproject/gramine/blob/c998e52c933cbf46ae4ba9bbbd3a07ba15cf60a1/Pal/src/db_rtld.c#L844)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I didn't want to change this since this is unrelated. I can change this asm in a follow-up (small) PR, if needed.
</blockquote></details>

This may be relevant to the preload support, see the other discussion.
___
*[Pal/src/db_rtld.c, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIkMBu7420CCpzPrf5:-MmIxRiR-TtAnzlAJHpM:b-alf13k) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/src/db_rtld.c#L15)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Weird. I went back to check and [musl also does that](https://git.musl-libc.org/cgit/musl/tree/ldso/dynlink.c#n932), but [`readelf` checks a section header](https://github.com/bminor/binutils-gdb/blob/master/binutils/readelf.c#L6126). Do you do this because we should not depend on section headers in runtime?
</blockquote></details>

Section headers are only for linking / debugging purposes, they may be completely missing from final binaries.
___
*[Pal/src/host/Linux/db_rtld.c, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIyrzc9aZhavVfOPun:-MmIyrzc9aZhavVfOPuo:b-qg0jra) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/src/host/Linux/db_rtld.c#L3)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University  */
> /* Copyright (C) 2021 Intel Labs */
> ```

in other places we usually merge the copyrights into one comment block


<!-- Sent from Reviewable.io -->

2021-10-19 13:25 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/152)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/db_rtld.c, line 537 at r3](https://reviewable.io/reviews/gramineproject/gramine/152#-MmIfBGD0F4YUA0x-bJM:-MmNhO7E4lI8nvpuPIu_:b540kjr) ([raw file](https://github.com/gramineproject/gramine/blob/f8962738b820a67051321cb41a000fdfadc0b06d/Pal/src/db_rtld.c#L537)):*
>is something preventing the compiler from generating it?

Now that I think of it, yes, because if the reference was external to the library, we'd end up with a relocation inside text.

Still, all these considerations are probably x86-64 specific, and asm is less ambiguous. Thanks!


<!-- Sent from Reviewable.io -->

2021-10-19 17:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/152)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 844 at r1](https://reviewable.io/reviews/gramineproject/gramine/152#-MmHa18w5xof8j6yNBmt:-MmOUQVK306lXlkRnO9i:blilmx7) ([raw file](https://github.com/gramineproject/gramine/blob/c998e52c933cbf46ae4ba9bbbd3a07ba15cf60a1/Pal/src/db_rtld.c#L844)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Frankly, I don't understand this question. Shouldn't we call `shim_init()` to initialize the libOS? How else we will know where to call?
</blockquote></details>

I think that TODO question in the comment is because of the caller code: we call `CALL_ENTRY()` possibly multiple times, first on "preloaded" libraries and then on the "EXEC" binaries. So this is confusing and unorthodox -- we should simply preload the libraries, without jumping into their code, and then execute the EXEC binary.

The current code is a bit weird -- the LibOS library is called "preloaded" which kinda implies that LibOS library shouldn't have an entrypoint, and that we'll jump into some other EXEC binary. But this is not the case -- if we have the LibOS library, then this LibOS library is actually the entrypoint (the EXEC binary), and PAL simply passes control to `shim_init()` entrypoint of this LibOS library and never returns back.

Basically, a case of bad (confusing) naming.


<!-- Sent from Reviewable.io -->

2021-10-27 08:37 UTC, merged

2021-10-30 23:51 UTC, stefanberger commented
So this was a bit of a storm for ppc64 but the ship didn't sink... I have to do some odd offset calculations on the pal binary for which I don't have good explanations except that they seem to correspond to the differences between 'offset' and 'virtaddr' in the LOAD program headers.
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000010000 0x0000000000010000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x00000000000afcb0 0x00000000000afcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000

```

For addresses >= 0xafcb0 I need to add an offset of -0x20000 (= 0x8fcb0 - 0xafcb0; [offset - virt addr]) and for those >= 0x10000 but < 0xafcb0 I need to add an offset of -0x10000 (= 0x0 - 0x1000) and then everything miraculously works. Only the initial pal binary needs this odd offset  but I don't see why this is needed... Anyone good an idea?

2021-10-31 13:21 UTC, pwmarcz commented
Can you paste a diff of the changes you needed to make?

If I had to guess, it sounds like our code incorrectly uses file offset instead of virtual address somewhere.

2021-10-31 13:51 UTC, stefanberger commented
The field `in_memory` is only set for the pal binary:

```
diff --git a/Pal/include/pal_rtld.h b/Pal/include/pal_rtld.h
index 2f281af55..3561bcc20 100644
--- a/Pal/include/pal_rtld.h
+++ b/Pal/include/pal_rtld.h
@@ -32,6 +32,8 @@ struct link_map {
 
     /* Typical case: INTERNAL type is for PAL binary, PRELOAD for LibOS lib, EXEC for PAL test. */
     enum elf_object_type l_type;
+
+    int in_memory;
 };
 
 extern struct link_map* g_loaded_maps;
@@ -46,7 +48,8 @@ int load_elf_object(const char* uri, enum elf_object_type type);
 int setup_pal_binary(struct link_map* pal_map);
 int find_string_and_symbol_tables(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr,
                                   const char** out_string_table, ElfW(Sym)** out_symbol_table,
-                                  uint32_t* out_symbol_table_cnt);
+                                  uint32_t* out_symbol_table_cnt,
+                                  int in_memory);
 
 noreturn void start_execution(const char** arguments, const char** environs);
 
diff --git a/Pal/src/db_rtld.c b/Pal/src/db_rtld.c
index edfeebcb6..5784c289e 100644
--- a/Pal/src/db_rtld.c
+++ b/Pal/src/db_rtld.c
@@ -103,15 +103,39 @@ static int elf_segment_prot_to_pal_prot(int elf_segment_prot) {
     return pal_prot;
 }
 
+static long get_offset_by_vaddr(ElfW(Addr) ehdr_addr, ElfW(Addr) vaddr,
+                                int in_memory)
+{
+    if (!in_memory)
+        return 0;
+
+    const ElfW(Ehdr)* header = (void*)ehdr_addr;
+    const ElfW(Phdr)* phdr   = (void*)(ehdr_addr + header->e_phoff);
+    long offset = 0;
+
+    for (const ElfW(Phdr)* ph = phdr; ph < &phdr[header->e_phnum]; ph++) {
+        if (ph->p_type == PT_LOAD) {
+            if (vaddr < ph->p_vaddr)
+                break;
+            offset = ph->p_offset - ph->p_vaddr;
+        }
+    }
+    return offset;
+}
+
+
 /* iterate through DSO's program headers to find dynamic section (for dynamic linking) */
-static ElfW(Dyn)* find_dynamic_section(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr) {
+static ElfW(Dyn)* find_dynamic_section(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr,
+                                       int in_memory) {
     const ElfW(Ehdr)* header = (void*)ehdr_addr;
     const ElfW(Phdr)* phdr   = (void*)(ehdr_addr + header->e_phoff);
 
     ElfW(Dyn)* dynamic_section = NULL;
+    long offset;
     for (const ElfW(Phdr)* ph = phdr; ph < &phdr[header->e_phnum]; ph++) {
         if (ph->p_type == PT_DYNAMIC) {
-            dynamic_section = (void*)base_addr + ph->p_vaddr;
+            offset = get_offset_by_vaddr(ehdr_addr, ph->p_vaddr, in_memory);
+            dynamic_section = (void*)base_addr + ph->p_vaddr + offset;
             break;
         }
     }
@@ -121,12 +145,13 @@ static ElfW(Dyn)* find_dynamic_section(ElfW(Addr) ehdr_addr, ElfW(Addr) base_add
 
 int find_string_and_symbol_tables(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr,
                                   const char** out_string_table, ElfW(Sym)** out_symbol_table,
-                                  uint32_t* out_symbol_table_cnt) {
+                                  uint32_t* out_symbol_table_cnt,
+                                  int in_memory) {
     const char* string_table  = NULL;
     ElfW(Sym)* symbol_table   = NULL;
     uint32_t symbol_table_cnt = 0;
 
-    ElfW(Dyn)* dynamic_section = find_dynamic_section(ehdr_addr, base_addr);
+    ElfW(Dyn)* dynamic_section = find_dynamic_section(ehdr_addr, base_addr, in_memory);
     if (!dynamic_section) {
         log_error("Loaded binary doesn't have dynamic section (required for symbol resolution)");
         return -PAL_ERROR_DENIED;
@@ -134,18 +159,22 @@ int find_string_and_symbol_tables(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr,
 
     /* iterate through DSO's dynamic section to find the string table and the symbol table */
     ElfW(Dyn)* dynamic_section_entry = dynamic_section;
+    long offset;
     while (dynamic_section_entry->d_tag != DT_NULL) {
         switch (dynamic_section_entry->d_tag) {
             case DT_STRTAB:
-                string_table = (const char*)(dynamic_section_entry->d_un.d_ptr + base_addr);
+                offset = get_offset_by_vaddr(ehdr_addr, dynamic_section_entry->d_un.d_ptr, in_memory);
+                string_table = (const char*)(dynamic_section_entry->d_un.d_ptr + offset + base_addr);
                 break;
             case DT_SYMTAB:
-                symbol_table = (ElfW(Sym)*)(dynamic_section_entry->d_un.d_ptr + base_addr);
+                offset = get_offset_by_vaddr(ehdr_addr, dynamic_section_entry->d_un.d_ptr, in_memory);
+                symbol_table = (ElfW(Sym)*)(dynamic_section_entry->d_un.d_ptr + offset + base_addr);
                 break;
             case DT_HASH: {
                 /* symbol table size can only be found via ELF hash table's nchain (which is the
                  * second word in the ELF hash table struct) */
-                ElfW(Word)* ht = (ElfW(Word)*)(dynamic_section_entry->d_un.d_ptr + base_addr);
+                offset = get_offset_by_vaddr(ehdr_addr, dynamic_section_entry->d_un.d_ptr, in_memory);
+                ElfW(Word)* ht = (ElfW(Word)*)(dynamic_section_entry->d_un.d_ptr + offset + base_addr);
                 symbol_table_cnt = ht[1];
                 break;
             }
@@ -158,6 +187,23 @@ int find_string_and_symbol_tables(ElfW(Addr) ehdr_addr, ElfW(Addr) base_addr,
         return -PAL_ERROR_DENIED;
     }
 
+#if defined(__powerpc64__)
+    long start = ALIGN_DOWN_POW2((long)symbol_table, 65536);
+    long end = ALIGN_UP_POW2((long)symbol_table + symbol_table_cnt * sizeof(ElfW(Sym)), 65536);
+    int ret = _DkVirtualMemoryProtect((void*)start, end - start, PAL_PROT_READ | PAL_PROT_WRITE | PAL_PROT_EXEC);
+    if (ret)
+        log_error("BAD: ret=%d\n", ret);
+    /* adjust the symbol table */
+    uint32_t i;
+    for (i = 0; i < symbol_table_cnt; i++) {
+        offset = get_offset_by_vaddr(ehdr_addr, symbol_table[i].st_value, in_memory);
+        symbol_table[i].st_value += offset;
+    }
+    ret = _DkVirtualMemoryProtect((void*)start, end - start, PAL_PROT_READ | PAL_PROT_EXEC);
+    if (ret)
+        log_error("BAD: ret=%d\n", ret);
+#endif
+
     *out_string_table     = string_table;
     *out_symbol_table     = symbol_table;
     *out_symbol_table_cnt = symbol_table_cnt;
@@ -171,6 +217,7 @@ static int find_symbol_in_loaded_maps(struct link_map* map, ElfW(Rela)* rela,
         return -PAL_ERROR_DENIED;
 
     const char* symbol_name = map->string_table + map->symbol_table[symbol_idx].st_name;
+//    log_error("symbol_idx: %ld  name: %s\n", symbol_idx, symbol_name);
 
     /* first try to find in this ELF object itself */
     if (map->symbol_table[symbol_idx].st_value &&
@@ -191,6 +238,7 @@ static int find_symbol_in_loaded_maps(struct link_map* map, ElfW(Rela)* rela,
                 /* NOTE: we currently don't take into account weak symbols and return the first
                  *       symbol found (we don't have weak symbols in PAL and preloaded libs) */
                 *out_symbol_addr = loaded_map->l_base + loaded_map->symbol_table[i].st_value;
+//                log_error("--> 0x%lx\n", loaded_map->symbol_table[i].st_value);
                 return 0;
             }
         }
@@ -213,16 +261,20 @@ static int perform_relocations(struct link_map* map) {
     ElfW(Rela)* plt_relas_addr = NULL;
     ElfW(Xword) plt_relas_size = 0;
 
+    long offset;
+
     while (dynamic_section_entry->d_tag != DT_NULL) {
         switch (dynamic_section_entry->d_tag) {
             case DT_RELA:
-                relas_addr = (ElfW(Rela)*)(base_addr + dynamic_section_entry->d_un.d_ptr);
+                offset = get_offset_by_vaddr(base_addr, dynamic_section_entry->d_un.d_ptr, map->in_memory);
+                relas_addr = (ElfW(Rela)*)(base_addr + dynamic_section_entry->d_un.d_ptr + offset);
                 break;
             case DT_RELASZ:
                 relas_size = dynamic_section_entry->d_un.d_val;
                 [...]

2021-10-31 14:03 UTC, stefanberger commented
> If I had to guess, it sounds like our code incorrectly uses file offset instead of virtual address somewhere.

It actually seems the opposite...

Maybe it has something to do with this:

On x86_64:
```
(gdb) print /x &__ehdr_start
$1 = 0x7ffff3dcd000
(gdb) print /x &__text_start
$2 = 0x7ffff3dcd000
```

On ppc64:

```
(gdb) print /x &__text_start
$1 = 0x7ffff3f40000
(gdb) print /x &__ehdr_start
$2 = 0x7ffff3f50000
```

2021-11-01 08:15 UTC, pwmarcz commented
Thanks for the diff! I edited your comment to add syntax highlightling (```` ```diff ````).

Yeah, that looks fishy. We assumed `__ehdr_start` is going to be at virtual address 0, but clearly that's not true for ppc64. So we're computing load base wrong. Maybe we should define our own linker symbol at virtual address 0?

As for the rest, I'm not sure why the adjustment is necessary. AFAIK, the symbol value is a virtual address already, and we're modifying the mapped memory directly. Maybe @dimakuv will understand this better.

2021-11-01 13:35 UTC, stefanberger commented
And what's so odd also is that while the base is constant (of course) I still need two offsets, -0x10000 and -0x20000 depending on virtual address. If it was just one offset I would say the base is wrong, but there seems 'more' to it...

2021-11-02 07:53 UTC, dimakuv commented
@stefanberger Could you show the complete `readelf -a libpal.so`?

Clearly, the PAL binary on your PPC machine breaks our assumptions on the layout of the PAL binary. You have:
```
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000010000 0x0000000000010000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
```

Whereas in Gramine I wrote: https://github.com/gramineproject/gramine/blob/dfc2e93631364bf7c1314ee56c09cb9d32df004a/Pal/src/db_rtld.c#L578

In other words, Gramine assumes that the PAL binary's offset (related to `ehdr_addr`) and virtual address (related to `base_addr`) have the same value. But for your PPC binary, it is not the case.

I suspect that I'm incorrectly understanding the `B + A` formula of the `RELATIVE` relocation type. In my "System V Application Binary Interface. AMD64 Architecture Processor Supplement" document, the `R_X86_64_RELATIVE` relocation type is defined as `B + A`, where B is the base address at which a shared object is loaded and A is the addend.

In the PPC definition of `R_PPC64_RELATIVE`, it must be a similar formula (but *I couldn't find the PPC document, so I don't really know*). In this formula, I'm unclear what this A (addend) is. It looks like the addend is `A = ph->p_offset` where `ph` is the LOAD segment to which the relocated symbol belongs to.

Please note that to calculate the real address of `dynamic_section`, `string_table`, `symbol_table`, they all need to be relocated using this `RELATIVE` relocation type. So it's not surprise Stefan needs to adjust all of them.





<!-- Sent from Reviewable.io -->

2021-11-02 11:40 UTC, stefanberger commented
Here's the document for the relocations (section 3.5.x): http://cdn.openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655241_51269.html
I think the relocations are pretty much the same as on x86_64 with B being base addr and so on.

```
$ readelf --all /usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           PowerPC64
  Version:                           0x1
  Entry point address:               0x80000
  Start of program headers:          64 (bytes into file)
  Start of section headers:          966152 (bytes into file)
  Flags:                             0x2, abiv2
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             00000000000101c8  000001c8
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .hash             HASH             00000000000101f0  000001f0
       0000000000000160  0000000000000004   A       3     0     8
  [ 3] .dynsym           DYNSYM           0000000000010350  00000350
       0000000000000498  0000000000000018   A       4     3     8
  [ 4] .dynstr           STRTAB           00000000000107e8  000007e8
       000000000000032e  0000000000000000   A       0     0     1
  [ 5] .gnu.version      VERSYM           0000000000010b16  00000b16
       0000000000000062  0000000000000002   A       3     0     2
  [ 6] .gnu.version_d    VERDEF           0000000000010b78  00000b78
       0000000000000038  0000000000000000   A       4     2     8
  [ 7] .rela.dyn         RELA             0000000000010bb0  00000bb0
       00000000000012a8  0000000000000018   A       3     0     8
  [ 8] .text             PROGBITS         0000000000020000  00010000
       0000000000066f78  0000000000000000  AX       0     0     65536
  [ 9] .rodata           PROGBITS         0000000000086f78  00076f78
       0000000000004f5c  0000000000000000   A       0     0     8
  [10] .eh_frame_hdr     PROGBITS         000000000008bed4  0007bed4
       000000000000116c  0000000000000000   A       0     0     4
  [11] .eh_frame         PROGBITS         000000000008d040  0007d040
       00000000000049c4  0000000000000000   A       0     0     4
  [12] .dynamic          DYNAMIC          00000000000afcb0  0008fcb0
       0000000000000150  0000000000000010  WA       4     0     8
  [13] .got              PROGBITS         00000000000afe00  0008fe00
       00000000000001c8  0000000000000008  WA       0     0     256
  [14] .data             PROGBITS         00000000000b0000  00090000
       000000000000277c  0000000000000000  WA       0     0     8
  [15] .bss              NOBITS           00000000000b2780  0009277c
       0000000004000280  0000000000000000  WA       0     0     8
  [16] .comment          PROGBITS         0000000000000000  0009277c
       000000000000002a  0000000000000001  MS       0     0     1
  [17] .debug_aranges    PROGBITS         0000000000000000  000927b0
       0000000000000ba0  0000000000000000           0     0     16
  [18] .debug_info       PROGBITS         0000000000000000  00093350
       00000000000351f4  0000000000000000           0     0     1
  [19] .debug_abbrev     PROGBITS         0000000000000000  000c8544
       0000000000007b8b  0000000000000000           0     0     1
  [20] .debug_line       PROGBITS         0000000000000000  000d00cf
       000000000000fcf7  0000000000000000           0     0     1
  [21] .debug_str        PROGBITS         0000000000000000  000dfdc6
       0000000000005586  0000000000000001  MS       0     0     1
  [22] .debug_ranges     PROGBITS         0000000000000000  000e534c
       0000000000000530  0000000000000000           0     0     1
  [23] .gnu.attributes   GNU_ATTRIBUTES   0000000000000000  000e587c
       0000000000000010  0000000000000000           0     0     1
  [24] .symtab           SYMTAB           0000000000000000  000e5890
       00000000000043b0  0000000000000018          25   676     8
  [25] .strtab           STRTAB           0000000000000000  000e9c40
       00000000000020b6  0000000000000000           0     0     1
  [26] .shstrtab         STRTAB           0000000000000000  000ebcf6
       0000000000000110  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000010000 0x0000000000010000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x00000000000afcb0 0x00000000000afcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
  DYNAMIC        0x000000000008fcb0 0x00000000000afcb0 0x00000000000afcb0
                 0x0000000000000150 0x0000000000000150  RW     0x8
  NOTE           0x00000000000001c8 0x00000000000101c8 0x00000000000101c8
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x000000000007bed4 0x000000000008bed4 0x000000000008bed4
                 0x000000000000116c 0x000000000000116c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000008fcb0 0x00000000000afcb0 0x00000000000afcb0
                 0x0000000000000350 0x0000000000000350  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .hash .dynsym .dynstr .gnu.version .gnu.version_d .rela.dyn .text .rodata .eh_frame_hdr .eh_frame
   01     .dynamic .got .data .bss
   02     .dynamic
   03     .note.gnu.build-id
   04     .eh_frame_hdr
   05
   06     .dynamic .got

Dynamic section at offset 0x8fcb0 contains 17 entries:
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [libpal.so]
 0x0000000000000004 (HASH)               0x101f0
 0x0000000000000005 (STRTAB)             0x107e8
 0x0000000000000006 (SYMTAB)             0x10350
 0x000000000000000a (STRSZ)              814 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000070000003 (PPC64_OPT)          0x0
 0x0000000000000007 (RELA)               0x10bb0
 0x0000000000000008 (RELASZ)             4776 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0x10b78
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff0 (VERSYM)             0x10b16
 0x000000006ffffff9 (RELACOUNT)          199
 0x0000000000000000 (NULL)               0x0

Relocation section '.rela.dyn' at offset 0xbb0 contains 199 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
0000000afe08  000000000016 R_PPC64_RELATIVE   [...]

2021-11-02 12:19 UTC, dimakuv commented
@stefanberger Can you also show your `pal.lds` for your PPC?

You must have added a file similar to what we have for x86-64: `gramine/Pal/src/host/Linux/arch/x86_64/pal.lds`

2021-11-02 12:33 UTC, stefanberger commented
@dimakuv It's here: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20211029/Pal/src/host/Linux/arch/ppc64/pal.lds

2021-11-02 13:23 UTC, dimakuv commented
@stefanberger You have this line: https://github.com/stefanberger/graphene4ppc64/blob/9bf67566b41b3512de43ab291cb5b0481f4b5ddd/Pal/src/host/Linux/arch/ppc64/pal.lds#L14

Could you replace `0x10000` with `0x0` (twice)? This will force your PAL binary to have the first `LOAD` segment start with 0x0 virtaddr.

2021-11-03 04:15 UTC, stefanberger commented
> Could you replace `0x10000` with `0x0` (twice)? This will force your PAL binary to have the first `LOAD` segment start with 0x0 virtaddr.

I did that now. The test cases (PAL, LibOS, LTP) all run with the shown modifications as before. The PAL relocation now uses offsets 0x0 and -0x10000 [I ran it in gdb]. The relocation of the symbol table isn't necessary anymore since the offset at that time is 0x0. The -0x10000 applies to this here: `dynamic_section = (void*)base_addr + ph->p_vaddr + offset;`. Maybe I could replace the ph->p_vaddr with ph->p_offset and that would be the only necessary change now. But it doesn't seem correct to do this for the general case.

Thanks a lot for looking at this!

 ```
$ readelf --all /usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           PowerPC64
  Version:                           0x1
  Entry point address:               0x70000
  Start of program headers:          64 (bytes into file)
  Start of section headers:          966152 (bytes into file)
  Flags:                             0x2, abiv2
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             00000000000001c8  000001c8
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .hash             HASH             00000000000001f0  000001f0
       0000000000000160  0000000000000004   A       3     0     8
  [ 3] .dynsym           DYNSYM           0000000000000350  00000350
       0000000000000498  0000000000000018   A       4     3     8
  [ 4] .dynstr           STRTAB           00000000000007e8  000007e8
       000000000000032e  0000000000000000   A       0     0     1
  [ 5] .gnu.version      VERSYM           0000000000000b16  00000b16
       0000000000000062  0000000000000002   A       3     0     2
  [ 6] .gnu.version_d    VERDEF           0000000000000b78  00000b78
       0000000000000038  0000000000000000   A       4     2     8
  [ 7] .rela.dyn         RELA             0000000000000bb0  00000bb0
       00000000000012a8  0000000000000018   A       3     0     8
  [ 8] .text             PROGBITS         0000000000010000  00010000
       0000000000066f78  0000000000000000  AX       0     0     65536
  [ 9] .rodata           PROGBITS         0000000000076f78  00076f78
       0000000000004f5c  0000000000000000   A       0     0     8
  [10] .eh_frame_hdr     PROGBITS         000000000007bed4  0007bed4
       000000000000116c  0000000000000000   A       0     0     4
  [11] .eh_frame         PROGBITS         000000000007d040  0007d040
       00000000000049c4  0000000000000000   A       0     0     4
  [12] .dynamic          DYNAMIC          000000000009fcb0  0008fcb0
       0000000000000150  0000000000000010  WA       4     0     8
  [13] .got              PROGBITS         000000000009fe00  0008fe00
       00000000000001c8  0000000000000008  WA       0     0     256
  [14] .data             PROGBITS         00000000000a0000  00090000
       000000000000277c  0000000000000000  WA       0     0     8
  [15] .bss              NOBITS           00000000000a2780  0009277c
       0000000004000280  0000000000000000  WA       0     0     8
  [16] .comment          PROGBITS         0000000000000000  0009277c
       000000000000002a  0000000000000001  MS       0     0     1
  [17] .debug_aranges    PROGBITS         0000000000000000  000927b0
       0000000000000ba0  0000000000000000           0     0     16
  [18] .debug_info       PROGBITS         0000000000000000  00093350
       00000000000351f4  0000000000000000           0     0     1
  [19] .debug_abbrev     PROGBITS         0000000000000000  000c8544
       0000000000007b8b  0000000000000000           0     0     1
  [20] .debug_line       PROGBITS         0000000000000000  000d00cf
       000000000000fcf7  0000000000000000           0     0     1
  [21] .debug_str        PROGBITS         0000000000000000  000dfdc6
       0000000000005586  0000000000000001  MS       0     0     1
  [22] .debug_ranges     PROGBITS         0000000000000000  000e534c
       0000000000000530  0000000000000000           0     0     1
  [23] .gnu.attributes   GNU_ATTRIBUTES   0000000000000000  000e587c
       0000000000000010  0000000000000000           0     0     1
  [24] .symtab           SYMTAB           0000000000000000  000e5890
       00000000000043b0  0000000000000018          25   676     8
  [25] .strtab           STRTAB           0000000000000000  000e9c40
       00000000000020b6  0000000000000000           0     0     1
  [26] .shstrtab         STRTAB           0000000000000000  000ebcf6
       0000000000000110  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x000000000009fcb0 0x000000000009fcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
  DYNAMIC        0x000000000008fcb0 0x000000000009fcb0 0x000000000009fcb0
                 0x0000000000000150 0x0000000000000150  RW     0x8
  NOTE           0x00000000000001c8 0x00000000000001c8 0x00000000000001c8
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x000000000007bed4 0x000000000007bed4 0x000000000007bed4
                 0x000000000000116c 0x000000000000116c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000008fcb0 0x000000000009fcb0 0x000000000009fcb0
                 0x0000000000000350 0x0000000000000350  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .hash .dynsym .dynstr .gnu.version .gnu.version_d .rela.dyn .text .rodata .eh_frame_hdr .eh_frame
   01     .dynamic .got .data .bss
   02     .dynamic
   03     .note.gnu.build-id
   04     .eh_frame_hdr
   05
   06     .dynamic .got

Dynamic section at offset 0x8fcb0 contains 17 entries:
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [libpal.so]
 0x0000000000000004 (HASH)               0x1f0
 0x0000000000000005 (STRTAB)             0x7e8
 0x0000000000000006 (SYMTAB)             0x350
 0x000000000000000a (STRSZ)              814 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000070000003 (PPC64_OPT)          0x0
 0x0000000000000007 (RELA)               0xbb0
 0x0000000000000008 (RELASZ)             4776 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0xb78
 0x000000006ffffffd (VERDEFNUM)          2
  [...]

2021-11-03 10:11 UTC, dimakuv commented
Now we need to adjust the `RW` `LOAD` segment (2nd LOAD segment) so that its file-offset is the same as its virtual-address.

I think the culprit is this line in your linker script: https://github.com/stefanberger/graphene4ppc64/blob/9bf67566b41b3512de43ab291cb5b0481f4b5ddd/Pal/src/host/Linux/arch/ppc64/pal.lds#L94

I don't know what these `MAXPAGESIZE` and `COMMONPAGESIZE` are on PPC. Could you do some research on these, and play with these values such that in the end your 2nd LOAD segment doesn't have a discrepancy between `Offset` and `VirtAddr`? Reading through https://sourceware.org/binutils/docs/ld/Builtin-Functions.html (`DATA_SEGMENT_ALIGN`) may give some pointers.

2021-11-03 12:24 UTC, stefanberger commented
Page size on ppc64 is 64k.

I have tried a couple of things now. Replacing CONSTANT (COMMONPAGESIZE) with values for example. Only 0 doesn't seem to work breaking the build. If I put '1', '0x10000', or even '0x20000' in there I get:

 ```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x000000000009fcb0 0x000000000009fcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
```

For '0x30000' it produces:

```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x00000000000bfcb0 0x00000000000bfcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
```
There's this jump to `0xbfcb0`. 0x20000 did NOT produce `0xafcb0`. Odd.

Using 0x10000 for the 2nd value and modifying CONSTANT (MAXSIZE) replacing it with 0x0 leads to:

```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x000000000010fcb0 0x000000000010fcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
```

Setting it to 0x10000 leads to:

```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000081a04 0x0000000000081a04  R E    0x10000
  LOAD           0x000000000008fcb0 0x000000000009fcb0 0x000000000009fcb0
                 0x0000000000002acc 0x0000000004002d50  RW     0x10000
```


This is from x86 where the difference is 0x200000...
```
**Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000002e188 0x000000000002e188  R E    0x200000
  LOAD           0x000000000002eec0 0x000000000022eec0 0x000000000022eec0
                 0x0000000000002aa0 0x0000000004002dc8  RW     0x200000
```