[LibOS] Update mmapped regions when writing to encrypted files
gramineproject/gramine pull request #1523
Opened 2023-08-30 04:09 UTC by kailun-qin

## Description of the changes 
Previously, Gramine didn't propagate changes to a mmaped encrypted file back to the memory. This is unexpected for apps that use both mmap and read/write on the same file (e.g., etcd-io/bbolt has such implementation to write data via `write()` and read it via the mmaped memory).

This commit introduces overwriting of affected mmapped regions on encrypted file writes. To reduce performance penalty in normal cases (where apps use either `write()` or `mmap()`), this commit also creates a new field in the file handle to record the number of mmaped regions of this file. We hence simply check on this field to determine whether to perform the updates to make the overhead negligible if none mmapped.

Fixes https://github.com/gramineproject/gramine/issues/1432.

## How to test this PR? 
Newly introduced test + CI.

2023-08-30 06:09 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3y_KZ8WpZv5poYL4G):*
Why do you only concentrate on **encrypted** files? I think the same problem happens on `chroot` and `tmpfs` files. Please double-check these other files, and if the problem is there -- also update their code.
___
*[`libos/include/libos_vma.h` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3ysI02-jHtPToLLgy:-Nd3ysI18c8R99ihNDCR:b-cq7j8t) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/include/libos_vma.h#L134)):*
> ```objc
> 
> /* Call `read` for file mappings in given range (should be page-aligned) */
> int read_range(uintptr_t begin, uintptr_t end);
> ```

These names are way too generic, and they are global to the whole codebase.

So let's change to something more specific. I suggest `reload_mmaped_from_file_range()` and `reload_mmaped_from_file_handle()`
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3wfPLABZeKFpS-0ty:-Nd3wfPLABZeKFpS-0tz:b-p75gri) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L516)):*
> ```C
>     if (vma->file) {
>         put_handle(vma->file);
>         (void)__atomic_sub_fetch(&vma->file->num_mmapped, 1, __ATOMIC_RELEASE);
> ```

It can be simply `__ATOMIC_RELAXED`
___
*[`libos/src/bookkeep/libos_vma.c` line 804 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3woGR34mr1fl0Ww1i:-Nd3woGR34mr1fl0Ww1j:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L804)):*
> ```C
>     if (new_vma->file) {
>         get_handle(new_vma->file);
>         (void)__atomic_add_fetch(&new_vma->file->num_mmapped, 1, __ATOMIC_RELEASE);
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 1052 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3wpZFDygRSNm3sJI7:-Nd3wpZFDygRSNm3sJI8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L1052)):*
> ```C
>     if (new_vma->file) {
>         get_handle(new_vma->file);
>         (void)__atomic_add_fetch(&new_vma->file->num_mmapped, 1, __ATOMIC_RELEASE);
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 1368 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3zb431ddEyqzGfo_u:-Nd3zb431ddEyqzGfo_v:be1d8ja) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L1368)):*
> ```C
>     struct libos_handle* hdl = arg;
> 
>     if (vma->flags & (VMA_UNMAPPED | VMA_INTERNAL | MAP_ANONYMOUS))
> ```

I think you should also add `| MAP_PRIVATE`.

IIUC, privately-mapped pages are populated from file only once (on the first mmap), and then they are completely decoupled from a file.

Only shared-mapped pages track the changes in the file. Also, the case we're trying to fix has `MAP_SHARED`: https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L89
___
*[`libos/src/fs/chroot/encrypted.c` line 445 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3xgW-4qBqANYIj0SX:-Nd3xgW-4qBqANYIj0SY:b4bm6he) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/fs/chroot/encrypted.c#L445)):*
> ```C
>     if (ret < 0) {
>         unlock(&hdl->inode->lock);
>         goto out;
> ```

Because `out` now is only one line, I prefer here to simply `return ret`
___
*[`libos/src/fs/chroot/encrypted.c` line 459 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3xn1a8-Jvbcy_fbMd:-Nd3xn1a8-Jvbcy_fbMe:b-pbuscd) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/fs/chroot/encrypted.c#L459)):*
> ```C
>         ret = read_handle(hdl);
> out:
>     return ret < 0 ? ret : (ssize_t)actual_count;
> ```

Here I would prefer to remove `out:` and simply have `return (ssize_t)actual_count`
___
*[`libos/test/fs/read_write_mmap.c` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd40v4n0_AjpmtBFCSb:-Nd40v4n0_AjpmtBFCSc:b-5pswub) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L3)):*
> ```C
> #include "common.h"
> 
> static void read_write(const char* file_path) {
> ```

Better name `read_write_mmap()`
___
*[`libos/test/fs/read_write_mmap.c` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd419rIC_9oUB0IBZ1R:-Nd419rIC_9oUB0IBZ1S:b46pi8d) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L16)):*
> ```C
>     void* buf_read = alloc_buffer(size);
> 
>     void* m = mmap_fd(file_path, fd, PROT_READ | PROT_WRITE, 0, size);
> ```

`MAP_SHARED` must be added. UPDATE: It is already implicitly added: https://github.com/gramineproject/gramine/blob/10c2668e35b11eacc0182c831f285113eeedc2b9/libos/test/fs/common.c#L101
___
*[`libos/test/fs/read_write_mmap.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd41zWWAe_foWEk-Ddw:-Nd41zWWAe_foWEk-Ddx:b-j956j3) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L26)):*
> ```C
> 
>     read_fd(file_path, fd, buf_read, size);
>     printf("read(%s) RW (mmap) OK\n", file_path);
> ```

You have the exact same string repeating twice. Maybe add numbers to make strings unique, and check in `test_enc.py` with these numbers?

Like this:
```
    ...
    printf("read(%s) 1 RW (mmap) OK\n", file_path);
    ...
    printf("read(%s) 2 RW (mmap) OK\n", file_path);
```
___
*[`libos/test/fs/read_write_mmap.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42LHS1D5r-6lwM9Tv:-Nd42LHS1D5r-6lwM9Tw:bit3mb4) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L28)):*
> ```C
>     printf("read(%s) RW (mmap) OK\n", file_path);
>     if (memcmp(m, buf_read, size) != 0)
>         fatal_error("Read data is different from what was written in the mapping\n");
> ```

`Read data via read()`
___
*[`libos/test/fs/read_write_mmap.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42A4FAxO863Lk3zeL:-Nd42A4FAxO863Lk3zeM:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L32)):*
> ```C
>     fill_random(buf_write, size);
>     seek_fd(file_path, fd, 0, SEEK_SET);
>     printf("seek(%s) RW (mmap) OK\n", file_path);
> ```

ditto
___
*[`libos/test/fs/read_write_mmap.c` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42OsU5tiZvu07SAhQ:-Nd42OsU5tiZvu07SAhR:b-n23nwb) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L40)):*
> ```C
>     printf("read(%s) RW (mmap) OK\n", file_path);
>     if (memcmp(buf_write, buf_read, size) != 0)
>         fatal_error("Read data is different from what was written\n");
> ```

`Read data via read() is different from what was written via write()`
___
*[`libos/test/fs/read_write_mmap.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42YyBDvkA8YHk6uzS:-Nd42YyBDvkA8YHk6uzT:b-sey5 [...]

2023-08-30 08:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 3 of 12 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3y_KZ8WpZv5poYL4G):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you only concentrate on **encrypted** files? I think the same problem happens on `chroot` and `tmpfs` files. Please double-check these other files, and if the problem is there -- also update their code.
</blockquote></details>

Done.
___
*[`libos/include/libos_vma.h` line 134 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3ysI02-jHtPToLLgy:-Nd4UbY505SIYPfMm8rM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/include/libos_vma.h#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These names are way too generic, and they are global to the whole codebase.

So let's change to something more specific. I suggest `reload_mmaped_from_file_range()` and `reload_mmaped_from_file_handle()`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3wfPLABZeKFpS-0ty:-Nd4UcQ77X6WbMYDm6py:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It can be simply `__ATOMIC_RELAXED`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 804 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3woGR34mr1fl0Ww1i:-Nd4UcsFADFs53vhAXf0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L804)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1052 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3wpZFDygRSNm3sJI7:-Nd4UdB475kZr2QTwuWk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L1052)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1368 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3zb431ddEyqzGfo_u:-Nd4UeFn0TVPtty8Rq4p:b20m8gj) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/bookkeep/libos_vma.c#L1368)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should also add `| MAP_PRIVATE`.

IIUC, privately-mapped pages are populated from file only once (on the first mmap), and then they are completely decoupled from a file.

Only shared-mapped pages track the changes in the file. Also, the case we're trying to fix has `MAP_SHARED`: https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L89
</blockquote></details>

Correct, fixed.
___
*[`libos/src/fs/chroot/encrypted.c` line 445 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3xgW-4qBqANYIj0SX:-Nd4UhyhATmdTb4YsTgD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/fs/chroot/encrypted.c#L445)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because `out` now is only one line, I prefer here to simply `return ret`
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 459 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3xn1a8-Jvbcy_fbMd:-Nd4UiXjEfSEKX-WKkVw:bfihe9v) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/src/fs/chroot/encrypted.c#L459)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here I would prefer to remove `out:` and simply have `return (ssize_t)actual_count`
</blockquote></details>

OK, now I explicitly ignore the return of `reload_mmaped_from_file_handle()`.
___
*[`libos/test/fs/read_write_mmap.c` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd40v4n0_AjpmtBFCSb:-Nd4Uq840CdYQO9HwM7a:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Better name `read_write_mmap()`
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd41zWWAe_foWEk-Ddw:-Nd4UrpZ1bSG8F4otAZD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have the exact same string repeating twice. Maybe add numbers to make strings unique, and check in `test_enc.py` with these numbers?

Like this:
```
    ...
    printf("read(%s) 1 RW (mmap) OK\n", file_path);
    ...
    printf("read(%s) 2 RW (mmap) OK\n", file_path);
```
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42LHS1D5r-6lwM9Tv:-Nd4UsPf5RF6rTMdH1gv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Read data via read()`
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42A4FAxO863Lk3zeL:-Nd4UtE68VoN1J7Gmqhi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42OsU5tiZvu07SAhQ:-Nd4UyG92_qY6Z50Ne63:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Read data via read() is different from what was written via write()`
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd42YyBDvkA8YHk6uzS:-Nd4UxyK-C9elmSWnCgz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/read_write_mmap.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`... was written via write()`
</blockquote></details>

Done.
___
*[`libos/test/fs/test_enc.py` line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd40Bw8-IUwb5HMt-4-:-Nd4UxOe4eHikeug_K8w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90cdf134550962b6417305da01381870cfc9f93a/libos/test/fs/test_enc.py#L10 [...]

2023-08-30 08:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 3 of 12 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3y_KZ8WpZv5poYL4G):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One more note is that for `chroot`, there's no such issue w/ Gramine-direct while w/ Gramine-SGX, shared memory-mapped files with write permission (e.g., `mmap(PROT_WRITE, MAP_SHARED, fd)`) is not allowed. But I updated it anyway.


<!-- Sent from Reviewable.io -->

2023-08-30 15:22 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd6133t-pLtE78_6got:-Nd6133t-pLtE78_6gou:bccwy5f) (no related file):*
PR looks good to me. Just to be sure, can you run your newly added test on `chroot`, `enc` and `tmpfs` in direct and sgx modes and make sure that all 6 runs **fail without your fix**?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd3y_KZ8WpZv5poYL4G):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

One more note is that for `chroot`, there's no such issue w/ Gramine-direct while w/ Gramine-SGX, shared memory-mapped files with write permission (e.g., `mmap(PROT_WRITE, MAP_SHARED, fd)`) is not allowed. But I updated it anyway.
</blockquote></details>

Yes, you're right, that's correct. Thanks for updating it, that's exactly what I wanted.
___
*[`libos/src/bookkeep/libos_vma.c` line 1385 at r3](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd60J0T1Pv43tIDUkrc:-Nd60J0T1Pv43tIDUkrd:brx3b63) ([raw file](https://github.com/gramineproject/gramine/blob/afefbcc5209c8ddc5eb9c6095c22add9d44fb658/libos/src/bookkeep/libos_vma.c#L1385)):*
> ```C
> }
> 
> static int read_all(uintptr_t begin, uintptr_t end, struct libos_handle* hdl) {
> ```

Please also change this name, to `reload_mmaped_from_file_all()`
___
*[`libos/test/fs/test_fs.py` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd60oN1DUywHj-ybErI:-Nd60oN29_A3FyOtQ2yT:b-786g33) ([raw file](https://github.com/gramineproject/gramine/blob/afefbcc5209c8ddc5eb9c6095c22add9d44fb658/libos/test/fs/test_fs.py#L99)):*
> ```Python
> 
>     # Gramine's implementation of file_map doesn't currently support shared memory-mapped
>     # files with write permission in PAL/Linux-SGX (like mmap(PROT_WRITE, MAP_SHARED, fd)).
> ```

`files` -> `regular chroot files`


<!-- Sent from Reviewable.io -->

2023-08-30 15:52 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 10 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd6133t-pLtE78_6got:-Nd65CfQ18jijO_OqQrs:b-7fdk0v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

PR looks good to me. Just to be sure, can you run your newly added test on `chroot`, `enc` and `tmpfs` in direct and sgx modes and make sure that all 6 runs **fail without your fix**?
</blockquote></details>

Yes (actually 5 tests, 1 skipped), pls see below outputs tested based on commit 

gramine-direct:
```
==================================================== test session starts =====================================================
...
test_enc.py::TC_50_EncryptedFiles::test_111_read_write_mmap FAILED                                                     [ 33%]
test_fs.py::TC_00_FileSystem::test_111_read_write_mmap PASSED                                                          [ 66%]
test_tmpfs.py::TC_10_Tmpfs::test_111_read_write_mmap FAILED                                                            [100%]
...
========================================================== FAILURES ==========================================================
_______________________________________ TC_50_EncryptedFiles.test_111_read_write_mmap ________________________________________
...
---------------------------------------------------- Captured stdout call ----------------------------------------------------
[0.024] Random seed: 1693377998
[0.024] open(tmp/enc_output/test_111) RW (mmap) OK
[0.051] mmap_fd(1048576) OK
[0.109] read(tmp/enc_output/test_111) 1 RW (mmap) OK
[0.135] seek(tmp/enc_output/test_111) 1 RW (mmap) OK
[0.151] write(tmp/enc_output/test_111) RW (mmap) OK
[0.151] seek(tmp/enc_output/test_111) 2 RW (mmap) OK
[0.163] read(tmp/enc_output/test_111) 2 RW (mmap) OK
[0.163] ERROR: Read data in the mapping is different from what was written via write()
____________________________________________ TC_10_Tmpfs.test_111_read_write_mmap ____________________________________________
...
---------------------------------------------------- Captured stdout call ----------------------------------------------------
[0.018] Random seed: 1693377998
[0.018] open(/mnt-tmpfs/test_111) RW (mmap) OK
[0.020] mmap_fd(1048576) OK
[0.046] read(/mnt-tmpfs/test_111) 1 RW (mmap) OK
[0.071] seek(/mnt-tmpfs/test_111) 1 RW (mmap) OK
[0.071] write(/mnt-tmpfs/test_111) RW (mmap) OK
[0.071] seek(/mnt-tmpfs/test_111) 2 RW (mmap) OK
[0.071] read(/mnt-tmpfs/test_111) 2 RW (mmap) OK
[0.072] ERROR: Read data in the mapping is different from what was written via write()
===================================== 2 failed, 1 passed, 58 deselected in 0.87 seconds 
```

gramine-sgx:
```
==================================================== test session starts =====================================================
...
test_enc.py::TC_50_EncryptedFiles::test_111_read_write_mmap FAILED                                                     [ 33%]
test_fs.py::TC_00_FileSystem::test_111_read_write_mmap SKIPPED                                                         [ 66%]
test_tmpfs.py::TC_10_Tmpfs::test_111_read_write_mmap FAILED                                                            [100%]

========================================================== FAILURES ==========================================================
_______________________________________ TC_50_EncryptedFiles.test_111_read_write_mmap ________________________________________
...
---------------------------------------------------- Captured stdout call ----------------------------------------------------
[0.607] Random seed: 1693378128
[0.607] open(tmp/enc_output/test_111) RW (mmap) OK
[0.633] mmap_fd(1048576) OK
[0.683] read(tmp/enc_output/test_111) 1 RW (mmap) OK
[0.707] seek(tmp/enc_output/test_111) 1 RW (mmap) OK
[0.723] write(tmp/enc_output/test_111) RW (mmap) OK
[0.723] seek(tmp/enc_output/test_111) 2 RW (mmap) OK
[0.732] read(tmp/enc_output/test_111) 2 RW (mmap) OK
[0.732] ERROR: Read data in the mapping is different from what was written via write()
...
____________________________________________ TC_10_Tmpfs.test_111_read_write_mmap ____________________________________________
...
---------------------------------------------------- Captured stdout call ----------------------------------------------------
[0.591] Random seed: 1693378129
[0.591] open(/mnt-tmpfs/test_111) RW (mmap) OK
[0.598] mmap_fd(1048576) OK
[0.623] read(/mnt-tmpfs/test_111) 1 RW (mmap) OK
[0.648] seek(/mnt-tmpfs/test_111) 1 RW (mmap) OK
[0.648] write(/mnt-tmpfs/test_111) RW (mmap) OK
[0.648] seek(/mnt-tmpfs/test_111) 2 RW (mmap) OK
[0.648] read(/mnt-tmpfs/test_111) 2 RW (mmap) OK
[0.648] ERROR: Read data in the mapping is different from what was written via write()
===================================== 2 failed, 1 skipped, 58 deselected in 2.09 seconds =====================================
```

___
___
*[`libos/src/bookkeep/libos_vma.c` line 1385 at r3](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd60J0T1Pv43tIDUkrc:-Nd68D31EJC72F1HxNd1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/afefbcc5209c8ddc5eb9c6095c22add9d44fb658/libos/src/bookkeep/libos_vma.c#L1385)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also change this name, to `reload_mmaped_from_file_all()`
</blockquote></details>

Done.
___
*[`libos/test/fs/test_fs.py` line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd60oN1DUywHj-ybErI:-Nd68Bpv-RVXpOYAGSF5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/afefbcc5209c8ddc5eb9c6095c22add9d44fb658/libos/test/fs/test_fs.py#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`files` -> `regular chroot files`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-30 15:54 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 10 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd6133t-pLtE78_6got:-Nd68TyoCyYXvrFtqzje:bzebtgp) (no related file):*
> pls see below outputs tested based on commit

commit 02f7a8565fec54b5fa4e81c20e827cb954f2dff3, sorry about missing the ID somehow

___


<!-- Sent from Reviewable.io -->

2023-08-30 16:12 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nd6133t-pLtE78_6got:-Nd6CpUAE8E5jI23aNo4:b-uumv0h) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> pls see below outputs tested based on commit

commit 02f7a8565fec54b5fa4e81c20e827cb954f2dff3, sorry about missing the ID somehow
</blockquote></details>

Awesome, thanks for these logs! Everything looks good.

___


<!-- Sent from Reviewable.io -->

2023-11-04 19:20 UTC, dzobbe commented
Hi @kailun-qin @dimakuv what is your plan with regard to this PR? When do you plan to merge it? I am asking because I have the same exact issue and this PR helps :) 

Thanks a lot

2023-11-06 02:18 UTC, kailun-qin reviewed
@dzobbe Thanks for the information and great to know that it works!

We have at least two requests now :). @mkow: would you mind taking a look when you get a chance? Thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523#-:-NiXOfXzEE1QOnp5LdD6:b-3vvof1)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-07 00:36 UTC, mkow reviewed
Sure, but probably not this week, I'm sick :(

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523#-:-NibCH9g2-LiaUmNG0rN:bjzad02)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-07 11:57 UTC, dzobbe commented
Thanks @mkow much appreciated

2023-11-14 08:40 UTC, dzobbe commented
Hi @mkow this is just a reminder on this PR. If you could have a look, that would be great. Thanks a lot in advance ;)

2023-11-16 23:29 UTC, mkow requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/include/libos_handle.h` line 173 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPQ0oMCi4tRURhojfg:-NjPQ0oMCi4tRURhojfh:babehgh) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/include/libos_handle.h#L173)):*
> We hence simply check on this field to determine whether to perform the updates to make the overhead negligible if none mmapped.

What if someone wrote to the same file using a different handle than it was mapped from?
___
*[`libos/src/fs/chroot/encrypted.c` line 457 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPSXP-8mnFe3p5-FRg:-NjPSXP-8mnFe3p5-FRh:bmulu13) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/encrypted.c#L457)):*
> ```C
>     /* If there are any MAP_SHARED mappings for the file, this will read data from `enc`. */
>     if (__atomic_load_n(&hdl->num_mmapped, __ATOMIC_ACQUIRE) != 0)
>         (void)reload_mmaped_from_file_handle(hdl);
> ```

Shouldn't we fail here? (but probably without updating file position, in case the caller wants to retry? not sure)
The host on SGX can fail this single call, forcing the memory mappings to be outdated.


<!-- Sent from Reviewable.io -->

2023-11-17 06:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_handle.h` line 173 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPQ0oMCi4tRURhojfg:-NjQwgYD9gt--PO6Qq79:brhl5wd) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/include/libos_handle.h#L173)):*
> What if someone wrote to the same file using a different handle than it was mapped from?

Good question! Well, I think we can support it, albeit with certain complexities and overheads. Do we really want to do this?
___
*[`libos/src/fs/chroot/encrypted.c` line 457 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPSXP-8mnFe3p5-FRg:-NjQzEyY9s6Nj2kHQmCM:b-nzcbnk) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/encrypted.c#L457)):*
> Shouldn't we fail here? (but probably without updating file position, in case the caller wants to retry? not sure)

Not sure +1. But I'm fine w/ checking failure here.


<!-- Sent from Reviewable.io -->

2023-11-17 08:15 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/include/libos_handle.h` line 173 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPQ0oMCi4tRURhojfg:-NjRH19R7qsv16y2bsf9:bpt1yuk) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/include/libos_handle.h#L173)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> What if someone wrote to the same file using a different handle than it was mapped from?

Good question! Well, I think we can support it, albeit with certain complexities and overheads. Do we really want to do this?
</blockquote></details>

Actually, very good point.

Can't we move this field to the `inode`? All the FSes that we care about correctly support inodes now (tmpfs, chroot, encrypted).

Then we can do things like:
```
static bool vma_filter_needs_read(struct libos_vma* vma, void* arg) {
    struct libos_handle* hdl = arg;

    if (vma->flags & (VMA_UNMAPPED | VMA_INTERNAL | MAP_ANONYMOUS | MAP_PRIVATE))
        return false;

    assert(vma->file);

    if (hdl && hdl->inode && vma->file->inode && vma->file->inode != hdl->inode)
        return false;

    ...
}

...
    /* If there are any MAP_SHARED mappings for the file, this will read data from `enc`. */
    if (__atomic_load_n(&hdl->inode->num_mmapped, __ATOMIC_ACQUIRE) != 0)
        (void)reload_mmaped_from_file_handle(hdl);
...
```

This should be a very simple change. And given that `hdl->inode` is an immutable field, we don't need to do any additional locking.

@kailun-qin Please check whether it works (I think it should) and update the PR and the test correspondingly (make two sub-tests, one as you have currently, the other one with two opens of the same file).
___
*[`libos/src/bookkeep/libos_vma.c` line 1410 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRJKhRAYakIcN5g9Fl:-NjRJKhRAYakIcN5g9Fm:bwmk8ac) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/bookkeep/libos_vma.c#L1410)):*
> ```C
> 
>         ret = file->fs->fs_ops->read(file, (void*)read_begin, read_end - read_begin,
>                                      (file_off_t*)&vma_info->file_offset);
> ```

I just realized that we can be interrupted here (this func can return a benign PAL_ERROR_INTERRUPTED).

I think we should do a while loop like this: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/libos_utils.c#L10-L26

(Unfortunately can't reuse that `read_exact()` function as it doesn't support the offset, so need to write our own loop.)
___
*[`libos/src/fs/chroot/encrypted.c` line 457 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPSXP-8mnFe3p5-FRg:-NjRJa0cDCB14PTp1kUv:b-o00eq5) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/encrypted.c#L457)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Shouldn't we fail here? (but probably without updating file position, in case the caller wants to retry? not sure)

Not sure +1. But I'm fine w/ checking failure here.
</blockquote></details>

+1. But I'm not sure if we want to restore the file position... After all, the underlying file operation already happened, and there's no way to rewind this operation. So e.g. the underlying file size was already extended, and what do we do with `hdl->inode->size` in this case? We can't restore `hdl->inode->size` to the before-the-write value, because this will lead to discrepancy between the real on-the-host size and our in-gramine size...

So I currently vote for writing a `log_warning()` in the error case here, but keep `return actual_count` (i.e., the success of the write function itself).

We can even put a `BUG()` here, as I don't think there are legitimate benign cases where this reload could fail. @mkow WDYT?
___
*[`libos/src/fs/chroot/fs.c` line 325 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRK2H-3dj7VhzxzerS:-NjRK2H-3dj7VhzxzerT:bo6025e) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/fs.c#L325)):*
> ```C
>     /* If there are any MAP_SHARED mappings for the file, this will read data from `hdl`. */
>     if (__atomic_load_n(&hdl->num_mmapped, __ATOMIC_ACQUIRE) != 0)
>         (void)reload_mmaped_from_file_handle(hdl);
> ```

ditto (restore `pos` and `hdl->inode->size` on error)
___
*[`libos/src/fs/tmpfs/fs.c` line 272 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRKJkq7Pjjx1nbll1k:-NjRKJkq7Pjjx1nbll1l:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/tmpfs/fs.c#L272)):*
> ```C
>     /* If there are any MAP_SHARED mappings for the file, this will read data from `hdl`. */
>     if (__atomic_load_n(&hdl->num_mmapped, __ATOMIC_ACQUIRE) != 0)
>         (void)reload_mmaped_from_file_handle(hdl);
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-11-17 11:11 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_handle.h` line 173 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPQ0oMCi4tRURhojfg:-NjRyAoEAcpXpt_UDWHq:b7me3ml) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/include/libos_handle.h#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, very good point.

Can't we move this field to the `inode`? All the FSes that we care about correctly support inodes now (tmpfs, chroot, encrypted).

Then we can do things like:
```
static bool vma_filter_needs_read(struct libos_vma* vma, void* arg) {
    struct libos_handle* hdl = arg;

    if (vma->flags & (VMA_UNMAPPED | VMA_INTERNAL | MAP_ANONYMOUS | MAP_PRIVATE))
        return false;

    assert(vma->file);

    if (hdl && hdl->inode && vma->file->inode && vma->file->inode != hdl->inode)
        return false;

    ...
}

...
    /* If there are any MAP_SHARED mappings for the file, this will read data from `enc`. */
    if (__atomic_load_n(&hdl->inode->num_mmapped, __ATOMIC_ACQUIRE) != 0)
        (void)reload_mmaped_from_file_handle(hdl);
...
```

This should be a very simple change. And given that `hdl->inode` is an immutable field, we don't need to do any additional locking.

@kailun-qin Please check whether it works (I think it should) and update the PR and the test correspondingly (make two sub-tests, one as you have currently, the other one with two opens of the same file).
</blockquote></details>

Thanks for the great suggestion! I was overcomplicating things. Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1410 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRJKhRAYakIcN5g9Fl:-NjRyHT84iwI84Y9Hgdp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/bookkeep/libos_vma.c#L1410)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just realized that we can be interrupted here (this func can return a benign PAL_ERROR_INTERRUPTED).

I think we should do a while loop like this: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/libos_utils.c#L10-L26

(Unfortunately can't reuse that `read_exact()` function as it doesn't support the offset, so need to write our own loop.)
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 457 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPSXP-8mnFe3p5-FRg:-NjRyKk65e5ABlh5XZx1:bnz6bth) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/encrypted.c#L457)):*
> After all, the underlying file operation already happened, and there's no way to rewind this operation.

I'm do doing a warning log for now


<!-- Sent from Reviewable.io -->

2023-11-17 11:48 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1414 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS3S5q3LIPkpwE3-xh:-NjS36fz25uC-T6Wbpm7:b-6wsb7w) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/src/bookkeep/libos_vma.c#L1414)):*
> ```C
>             size_t to_read = size - read;
>             ret = file->fs->fs_ops->read(file, (void*)(read_begin + read), to_read,
>                                          (file_off_t*)&vma_info->file_offset);
> ```

Wait, this looks like a bug. The last argument is updated by the `read()` callback, but that is **not** what we want. This helper function must not update the current file offset.

I think you need to do smth like this:
```
        size_t size = read_end - read_begin;
        size_t read = 0;
        file_off_t file_offset = (file_off_t)vma_info->file_offset;
        while (read < size) {
            size_t to_read = size - read;
            ret = file->fs->fs_ops->read(file, (void*)(read_begin + read), to_read,
                                         &file_offset);
        ...
```

This way you'll start reading with the `vma_info->file_offset` and on each iteration of the while loop, the new helper variable `file_offset` will be updated to reflect from what file offset to read the next chunk.
___
*[`libos/src/bookkeep/libos_vma.c` line 1419 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS437uA6cVYbtOfRag:-NjS437uA6cVYbtOfRah:b-xnygvy) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/src/bookkeep/libos_vma.c#L1419)):*
> ```C
>                     continue;
>                 }
>                 goto out;
> ```

You also need to translate the PAL error code into the UNIX error code before going out:
```
ret = pal_to_unix_errno(ret);
goto out;
```
___
*[`libos/test/fs/read_write_mmap.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS58k_-wO4TsNqL4Jz:-NjS58k_-wO4TsNqL4K-:b91pepv) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L64)):*
> ```C
> 
>     int fd2 = open_output_fd(file_path, /*rdwr=*/true);
>     printf("open(%s) RW fd2 (mmap) OK\n", file_path);
> ```

Why do you say `(mmap)`? This fd2 is used for `write()`.
___
*[`libos/test/fs/read_write_mmap.c` line 69 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5bk8EG7HMlIPuXRF:-NjS5bk8EG7HMlIPuXRG:bf8zwyf) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L69)):*
> ```C
>         close(fd2);
>         fatal_error("ftruncate fd2\n");
>     }
> ```

Why do you need this "extend to 1MB size" operation on fd2? It will call `write()` which will automatically extend the file, so looks this code is redundant?
___
*[`libos/test/fs/read_write_mmap.c` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5lqCCfPprtrpDgFZ:-NjS5lqCCfPprtrpDgF_:b-t0ukru) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L77)):*
> ```C
>     fill_random(buf_write, size);
>     write_fd(file_path, fd2, buf_write, size);
>     printf("write(%s) RW fd2 (mmap) OK\n", file_path);
> ```

ditto (why `(mmap)`)
___
*[`libos/test/fs/read_write_mmap.c` line 88 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5naX3QtGXJUSP2ng:-NjS5naX3QtGXJUSP2nh:b-t0ukru) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L88)):*
> ```C
>     printf("close(%s) RW fd1 (mmap) OK\n", file_path);
>     close_fd(file_path, fd2);
>     printf("close(%s) RW fd2 (mmap) OK\n", file_path);
> ```

ditto (why `(mmap)`)


<!-- Sent from Reviewable.io -->

2023-11-17 12:59 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 8 of 13 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1414 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS3S5q3LIPkpwE3-xh:-NjSM1XWDKnZ-LuSwytu:b-4c5ezp) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/src/bookkeep/libos_vma.c#L1414)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, this looks like a bug. The last argument is updated by the `read()` callback, but that is **not** what we want. This helper function must not update the current file offset.

I think you need to do smth like this:
```
        size_t size = read_end - read_begin;
        size_t read = 0;
        file_off_t file_offset = (file_off_t)vma_info->file_offset;
        while (read < size) {
            size_t to_read = size - read;
            ret = file->fs->fs_ops->read(file, (void*)(read_begin + read), to_read,
                                         &file_offset);
        ...
```

This way you'll start reading with the `vma_info->file_offset` and on each iteration of the while loop, the new helper variable `file_offset` will be updated to reflect from what file offset to read the next chunk.
</blockquote></details>

Good catch, done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1419 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS437uA6cVYbtOfRag:-NjSM3gZDdn9E60r7khG:b-n63m34) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/src/bookkeep/libos_vma.c#L1419)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need to translate the PAL error code into the UNIX error code before going out:
```
ret = pal_to_unix_errno(ret);
goto out;
```
</blockquote></details>

It's actually returning unix error codes (the above is actually wrong). Done.
___
*[`libos/test/fs/read_write_mmap.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS58k_-wO4TsNqL4Jz:-NjSMGzL0z0bjT3JgHDC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say `(mmap)`? This fd2 is used for `write()`.
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 69 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5bk8EG7HMlIPuXRF:-NjSMHht60fCsZJt_PZv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this "extend to 1MB size" operation on fd2? It will call `write()` which will automatically extend the file, so looks this code is redundant?
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 77 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5lqCCfPprtrpDgFZ:-NjSMI_s1s98g2YAyqxd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why `(mmap)`)
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 88 at r5](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjS5naX3QtGXJUSP2ng:-NjSMItbDYQM5c-adsZz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae922b7e6f4a19a7909dfea8dc85eb0fb94c5059/libos/test/fs/read_write_mmap.c#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why `(mmap)`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-17 13:12 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-18 02:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 9 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/chroot/encrypted.c` line 457 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjPSXP-8mnFe3p5-FRg:-NjVB8UI1aSokXaJY9Od:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/encrypted.c#L457)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We can even put a `BUG()` here, as I don't think there are legitimate benign cases where this reload could fail. [@mkow](https://github.com/mkow) WDYT?

+1, I think this is a good idea. The main problem here is that the untrusted host can force it too fail, but in benign cases this shouldn't happen. And in case of the failure we end up with inconsistent state visible to the app.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/fs.c` line 325 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRK2H-3dj7VhzxzerS:-NjVBB7641XUvtqM0oVS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/chroot/fs.c#L325)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (restore `pos` and `hdl->inode->size` on error)
</blockquote></details>

Done.
___
*[`libos/src/fs/tmpfs/fs.c` line 272 at r4](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjRKJkq7Pjjx1nbll1k:-NjVBCDE2NYiHdg7NWg6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06dab283af535c66c2e30e3152b9fabc1e837261/libos/src/fs/tmpfs/fs.c#L272)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-19 16:43 UTC, mkow requested changes
> Reviewed 2 of 8 files at r1, 1 of 9 files at r2, 2 of 10 files at r5, 4 of 5 files at r6, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 12 of 13 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/include/libos_vma.h` line 133 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njbw7cQCGjy06L4ytr4:-Njbw7cQCGjy06L4ytr5:bc4nvud) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/include/libos_vma.h#L133)):*
> Call `read`

This IMO doesn't describe well what it does, the read itself is not the essence, but reading and writing the data to the mapped region? I.e. reloading.
___
*[`libos/include/libos_vma.h` line 136 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjbwVZsEpb7lI-wby-6:-NjbwVZsEpb7lI-wby-7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/include/libos_vma.h#L136)):*
> ```objc
> int reload_mmaped_from_file_range(uintptr_t begin, uintptr_t end);
> 
> /* Call `read` for file mappings of `hdl` */
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcHN_C3OylNoEA8ca6:-NjcHN_C3OylNoEA8ca7:bja9ayr) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
> ```C
>     if (vma->file) {
>         put_handle(vma->file);
>         (void)__atomic_sub_fetch(&vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

`inode` field is optional, I think you should IF on it?
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcHpx2CwvCpexOE0dH:-NjcHpx2CwvCpexOE0dI:blwtkq6) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
> ```C
>     if (vma->file) {
>         put_handle(vma->file);
>         (void)__atomic_sub_fetch(&vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

`vma->file` may have already been freed by this line.
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKIWK9EtDTjC5uYEN:-NjcJCIwA4ua7RpKG6JI:bp2fo5f) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
> ```C
>     if (vma->file) {
>         put_handle(vma->file);
>         (void)__atomic_sub_fetch(&vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

Can we assert here that it doesn't go below 0? (or rather: doesn't underflow)
___
*[`libos/src/bookkeep/libos_vma.c` line 804 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcJweV9ysqMpsnCm0H:-NjcJweV9ysqMpsnCm0I:bok06o1) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L804)):*
> ```C
>     if (new_vma->file) {
>         get_handle(new_vma->file);
>         (void)__atomic_add_fetch(&new_vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

ditto (`inode`)
___
*[`libos/src/bookkeep/libos_vma.c` line 1052 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKykr42SKUHsWtrNR:-NjcKykr42SKUHsWtrNS:bok06o1) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1052)):*
> ```C
>     if (new_vma->file) {
>         get_handle(new_vma->file);
>         (void)__atomic_add_fetch(&new_vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

ditto (`inode`)
___
*[`libos/src/bookkeep/libos_vma.c` line 1365 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcLVdVEPdSs5M7odzX:-NjcLVdVEPdSs5M7odzY:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1365)):*
> ```C
> }
> 
> static bool vma_filter_needs_read(struct libos_vma* vma, void* arg) {
> ```





_Suggestion:_
```C
vma_filter_needs_reload
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1454 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcEQoWCwRE3fVwCcP1:-NjcEQoWCwRE3fVwCcP2:b4we37p) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1454)):*
> ```C
> }
> 
> int reload_mmaped_from_file_range(uintptr_t begin, uintptr_t end) {
> ```

This looks unused? I guess we can simplify this whole code then?
___
*[`libos/test/fs/read_write_mmap.c` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcFdHx4NXPtjbL2Cdy:-NjcFdHx4NXPtjbL2Cdz:b1etyf4) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/test/fs/read_write_mmap.c#L19)):*
> ```C
>     printf("mmap_fd(%zu) OK\n", size);
>     fill_random(m, size);
>     int ret = msync(m, size, MS_SYNC);
> ```

Could you explain how does this case actually work with your PR? I could have missed something, but you didn't change anything in msync flow, and writing to memory is not triggering anything, so how is the writeback triggered? Was msync already doing that before the PR?


<!-- Sent from Reviewable.io -->

2023-11-20 02:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 11 of 13 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_vma.h` line 133 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njbw7cQCGjy06L4ytr4:-NjeXvNS3iRLT1V1AING:b-5c8xz4) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/include/libos_vma.h#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Call `read`

This IMO doesn't describe well what it does, the read itself is not the essence, but reading and writing the data to the mapped region? I.e. reloading.
</blockquote></details>

Not relevant any more. Done.
___
*[`libos/include/libos_vma.h` line 136 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjbwVZsEpb7lI-wby-6:-NjeXwaLAmpJbslYJe4L:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/include/libos_vma.h#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcHN_C3OylNoEA8ca6:-NjeY2ww7x4Sx-1u1gl4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`inode` field is optional, I think you should IF on it?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcHpx2CwvCpexOE0dH:-NjeY3Ot8-4toBJcljBD:b-o7vuhc) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`vma->file` may have already been freed by this line.
</blockquote></details>

Good catch! Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKIWK9EtDTjC5uYEN:-NjeY5e35YW-toGlXHRS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we assert here that it doesn't go below 0? (or rather: doesn't underflow)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 804 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcJweV9ysqMpsnCm0H:-NjeY6hk4p48Qaz3UQD3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L804)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`inode`)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1052 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKykr42SKUHsWtrNR:-NjeY8Cb5GfoL9mGizuA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1052)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`inode`)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1365 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcLVdVEPdSs5M7odzX:-NjeY8qD9G96Ks4q0Fpn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1365)):*
> ```C
> }
> 
> static bool vma_filter_needs_read(struct libos_vma* vma, void* arg) {
> ```

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1454 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcEQoWCwRE3fVwCcP1:-NjeYJRw9oxnmXFAsCVL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1454)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This looks unused? I guess we can simplify this whole code then?
</blockquote></details>

Done.
___
*[`libos/test/fs/read_write_mmap.c` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcFdHx4NXPtjbL2Cdy:-NjeYKyc5UMDq0fOfDJP:b-b539qr) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/test/fs/read_write_mmap.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain how does this case actually work with your PR? I could have missed something, but you didn't change anything in msync flow, and writing to memory is not triggering anything, so how is the writeback triggered? Was msync already doing that before the PR?
</blockquote></details>

`msync()` will eventually go to the `wirte()` callback: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/fs/libos_fs_util.c#L209. As we added the reloading logic into them, they should be triggered as expected.


<!-- Sent from Reviewable.io -->

2023-11-20 13:11 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njgqg-M5vMHlWW2uIfH:-Njgqg-M5vMHlWW2uIfI:b-wnwm4l) (no related file):*
Something goes wrong:
```
04:08:29  ________________________ TC_01_Bootstrap.test_200_exec _________________________
04:08:29  test_libos.py:201: in test_200_exec
04:08:29      stdout, _ = self.run_binary(['exec'])
04:08:29  ../../../usr/lib/python3.8/site-packages/graminelibos/regression.py:224: in run_binary
04:08:29      _returncode, stdout, stderr = run_command(cmd, timeout=timeout, **kwds)
04:08:29  ../../../usr/lib/python3.8/site-packages/graminelibos/regression.py:162: in run_command
04:08:29      raise subprocess.CalledProcessError(proc.returncode, cmd, raw_stdout, raw_stderr)
04:08:29  E   subprocess.CalledProcessError: Command '['/home/jenkins/workspace/graphene-direct-sanitizers/usr/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/jenkins/workspace/graphene-direct-sanitizers/usr/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'exec']' returned non-zero exit status 1.
04:08:29  ----------------------------- Captured stderr call -----------------------------
04:08:29  [0.012] [P1:T1:exec_victim] assert failed ../libos/src/bookkeep/libos_vma.c:518 num_mmapped < UINT64_MAX
```

Please debug and fix.

___
___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKIWK9EtDTjC5uYEN:-Njgo2-b2drFzt69BkhE:b-tbd5mw) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It would be easier to understand your assert if you would change to `__atomic_fetch_sub()` (then you would compare that "the previous value was greater than 0" in the assert).
___
*[`libos/src/bookkeep/libos_vma.c` line 1454 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcEQoWCwRE3fVwCcP1:-NjgocF12ULQ4ZzSLK6X:buqnvbm) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L1454)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For the context: we initially mimicked the `msync_all()` functions (see below), but yes, technically `reload_mmaped_from_file_range()` was unused. I'm fine with removing it and simplifying a bit, though we lost a nice readability uniformity here.
___
*[`libos/src/bookkeep/libos_vma.c` line 1425 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpcQlBUk2EAsGwMZx:-NjgpcQlBUk2EAsGwMZy:b-8c1rr6) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1425)):*
> ```C
>             if (ret < 0) {
>                 ret = pal_to_unix_errno(ret);
>                 break;
> ```

Why not `goto out`? Then you won't need a weird `&& !ret` in the for loop.
___
*[`libos/src/bookkeep/libos_vma.c` line 1439 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpLmj5HOw0d-TL_oh:-NjgpLmj5HOw0d-TL_oi:b8hjxhj) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1439)):*
> ```C
>                 break;
>             } else if (count == 0) {
>                 break;
> ```

Why did you remove `ret = -ENODATA`?
___
*[`libos/test/fs/read_write_mmap.c` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcFdHx4NXPtjbL2Cdy:-NjgqEGE8YvwulFaTgR5:bv66ehf) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/test/fs/read_write_mmap.c#L19)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`msync()` will eventually go to the `wirte()` callback: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/fs/libos_fs_util.c#L209. As we added the reloading logic into them, they should be triggered as expected.
</blockquote></details>

Yep, as @kailun-qin explained. `msync()` -> `write()` callback -> this PR updates this callback with `reload_mmaped_from_file_handle()`.


<!-- Sent from Reviewable.io -->

2023-11-20 15:32 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 12 of 13 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 516 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcKIWK9EtDTjC5uYEN:-NjhHcVP-en7heP4XiCO:bbxqdpj) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/src/bookkeep/libos_vma.c#L516)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It would be easier to understand your assert if you would change to `__atomic_fetch_sub()` (then you would compare that "the previous value was greater than 0" in the assert).
</blockquote></details>

Done again.
___
*[`libos/src/bookkeep/libos_vma.c` line 1425 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpcQlBUk2EAsGwMZx:-NjhKXzc8crxydWzqq0w:b-cqo9ui) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1425)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `goto out`? Then you won't need a weird `&& !ret` in the for loop.
</blockquote></details>

hmm... `&& !ret` servees for both the `break` here (outer loop) and the `break` below (inner loop). Note that here when mprotect fails we need to break the outer loop, while below when the read callback fails we need to break the inner loop. These two `break`s need to goto different places -- with the first goto `free_vma_info_array()` directly while the latter goto restore permission w/ `mprotect` (which is still within the outer loop). I just don't want to introduce two gotos, so I used this approach.
___
*[`libos/src/bookkeep/libos_vma.c` line 1439 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpLmj5HOw0d-TL_oh:-NjhHf_o-7Yllxm1Qq8w:b-5xrycb) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1439)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove `ret = -ENODATA`?
</blockquote></details>

This will cause tests like `test_204_copy_dir_mmap_whole` to fail when reloading on `munmap()`. The test copies `size` length of data (less than size of one page, say 256 bytes): https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/test/fs/copy_mmap_whole.c#L10-L14 wheras we align up to page-aligned (4K) on `munmap()`: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/sys/libos_mmap.c#L350. If we return `-ENODATA` when nothing to read, then `munmap()` fails.


<!-- Sent from Reviewable.io -->

2023-11-20 15:36 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 12 of 13 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njgqg-M5vMHlWW2uIfH:-NjhMNxq0nTMMdo-5US0:b-eec0vm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Something goes wrong:
```
04:08:29  ________________________ TC_01_Bootstrap.test_200_exec _________________________
04:08:29  test_libos.py:201: in test_200_exec
04:08:29      stdout, _ = self.run_binary(['exec'])
04:08:29  ../../../usr/lib/python3.8/site-packages/graminelibos/regression.py:224: in run_binary
04:08:29      _returncode, stdout, stderr = run_command(cmd, timeout=timeout, **kwds)
04:08:29  ../../../usr/lib/python3.8/site-packages/graminelibos/regression.py:162: in run_command
04:08:29      raise subprocess.CalledProcessError(proc.returncode, cmd, raw_stdout, raw_stderr)
04:08:29  E   subprocess.CalledProcessError: Command '['/home/jenkins/workspace/graphene-direct-sanitizers/usr/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/jenkins/workspace/graphene-direct-sanitizers/usr/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'exec']' returned non-zero exit status 1.
04:08:29  ----------------------------- Captured stderr call -----------------------------
04:08:29  [0.012] [P1:T1:exec_victim] assert failed ../libos/src/bookkeep/libos_vma.c:518 num_mmapped < UINT64_MAX
```

Please debug and fix.
</blockquote></details>

Trying to fix by adding the missing ref counter increase on `split_vma()`, let's give it another try.

___


<!-- Sent from Reviewable.io -->

2023-11-20 19:07 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1425 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpcQlBUk2EAsGwMZx:-Nji3u_w8AICFvdfijyG:b-lijoh4) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1425)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

hmm... `&& !ret` servees for both the `break` here (outer loop) and the `break` below (inner loop). Note that here when mprotect fails we need to break the outer loop, while below when the read callback fails we need to break the inner loop. These two `break`s need to goto different places -- with the first goto `free_vma_info_array()` directly while the latter goto restore permission w/ `mprotect` (which is still within the outer loop). I just don't want to introduce two gotos, so I used this approach.
</blockquote></details>

I'm sorry, but this is unreadable to me. Could you please split the body of this while loop (i.e., reloading a single VMA) into a helper static function? In ~2 years, when somebody will need to modify this code, they will definitely introduce a bug here...
___
*[`libos/src/bookkeep/libos_vma.c` line 1439 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpLmj5HOw0d-TL_oh:-Nji5yGX5FBgVtPIYZa9:bgh3sio) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1439)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This will cause tests like `test_204_copy_dir_mmap_whole` to fail when reloading on `munmap()`. The test copies `size` length of data (less than size of one page, say 256 bytes): https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/test/fs/copy_mmap_whole.c#L10-L14 wheras we align up to page-aligned (4K) on `munmap()`: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/sys/libos_mmap.c#L350. If we return `-ENODATA` when nothing to read, then `munmap()` fails.
</blockquote></details>

Thanks, it makes sense. We previously copy-pasted that code from `read_exact()`, but you're right, here we don't read the **exact** `size` -- it can be less than that.
___
*[`libos/src/bookkeep/libos_vma.c` line 214 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji35ro9tF8jiaj1gE1:-Nji35ro9tF8jiaj1gE2:bfn56es) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L214)):*
> ```C
>     if (new_vma->file) {
>         if (new_vma->file->inode)
>             (void)__atomic_add_fetch(&new_vma->file->inode->num_mmapped, 1, __ATOMIC_RELAXED);
> ```

Woudn't it make sense to move this inside `copy_vma()`?
___
*[`libos/src/bookkeep/libos_vma.c` line 1441 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji69EX72g1krrOP9DV:-Nji69EX72g1krrOP9DW:bao4mon) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L1441)):*
> ```C
>                 break;
>             } else if (count == 0) {
>                 break;
> ```

Ouch, @kailun-qin's comment made me realize that we have totally redundant paths like this:
- `munmap()` -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`
- `mmap(MAP_FIXED_NOREPLACE)` -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`
- `msync()` -> -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`

In other words, when VMA contents are being msynced, it calls the `write` callback which in turn blindly reloads the VMA contents. Which is totally bogus.

@kailun-qin What if we add some boolean flag to `struct libos_vma_info`, and we set this flag inside `msync_all()` and then unset it? And we'll check this flag here -- if it is set, then we skip all this reloading logic for the VMA.

Otherwise we are doomed to have these meaningless read/write operations on each munmap, which is a frequent op.


<!-- Sent from Reviewable.io -->

2023-11-20 23:35 UTC, mkow requested changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/include/libos_vma.h` line 133 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njj-oPl9o3QgwtgwNEL:-Njj-oPl9o3QgwtgwNEM:b-setyb1) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/include/libos_vma.h#L133)):*
> ```objc
> int msync_handle(struct libos_handle* hdl);
> 
> /* Call `reload` for file mappings of `hdl` */
> ```

There's no "reload" function or anything like that, so it shouldn't be backticked. Just use it as an English verb.



_Suggestion:_
```objc
/* Reload file mappings of `hdl` */
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1441 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji69EX72g1krrOP9DV:-Njj39bq3G1Y0M1pgIDQ:b-p10lxm) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L1441)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ouch, @kailun-qin's comment made me realize that we have totally redundant paths like this:
- `munmap()` -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`
- `mmap(MAP_FIXED_NOREPLACE)` -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`
- `msync()` -> -> `msync_all()` -> `fs_ops->msync()` -> `fs_ops->write()` -> `reload_mmaped_from_file_handle()`

In other words, when VMA contents are being msynced, it calls the `write` callback which in turn blindly reloads the VMA contents. Which is totally bogus.

@kailun-qin What if we add some boolean flag to `struct libos_vma_info`, and we set this flag inside `msync_all()` and then unset it? And we'll check this flag here -- if it is set, then we skip all this reloading logic for the VMA.

Otherwise we are doomed to have these meaningless read/write operations on each munmap, which is a frequent op.
</blockquote></details>

But this idea doesn't seem to be correct against race conditions? What in the meantime someone does something which actually should reload a mapping here? The msync-in-progress will turn the reloading into a no-op?
___
*[`libos/test/fs/read_write_mmap.c` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjcFdHx4NXPtjbL2Cdy:-Njj1NhF6pgka_byY2md:b-kufkxf) ([raw file](https://github.com/gramineproject/gramine/blob/85fd0fad860b4481845c0ceab00097b8bb2cba48/libos/test/fs/read_write_mmap.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, as @kailun-qin explained. `msync()` -> `write()` callback -> this PR updates this callback with `reload_mmaped_from_file_handle()`.
</blockquote></details>

I see, thanks!


<!-- Sent from Reviewable.io -->

2023-11-21 01:23 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 11 of 13 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_vma.h` line 133 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njj-oPl9o3QgwtgwNEL:-NjjSVY96FbOxEJO7obD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/include/libos_vma.h#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's no "reload" function or anything like that, so it shouldn't be backticked. Just use it as an English verb.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1425 at r9](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjgpcQlBUk2EAsGwMZx:-NjjSYxQCR3KucON6rJr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54e65411f82420dfdf21f2c7a804a8eb3f1d1cf7/libos/src/bookkeep/libos_vma.c#L1425)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm sorry, but this is unreadable to me. Could you please split the body of this while loop (i.e., reloading a single VMA) into a helper static function? In ~2 years, when somebody will need to modify this code, they will definitely introduce a bug here...
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 214 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji35ro9tF8jiaj1gE1:-NjjSXuoDG3CzGk2abkr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L214)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Woudn't it make sense to move this inside `copy_vma()`?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1441 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji69EX72g1krrOP9DV:-NjjSzhF-ELGe7MNnCDL:b9m6flr) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L1441)):*
> But this idea doesn't seem to be correct against race conditions? What in the meantime someone does something which actually should reload a mapping here?

Yes, it can be racy.

> The msync-in-progress will turn the reloading into a no-op?

Yes, I think this was what @dimakuv would like to propose.


<!-- Sent from Reviewable.io -->

2023-11-21 08:43 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njgqg-M5vMHlWW2uIfH:-NjkxqpL69X58dj8Bpv9:buqpckz) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Trying to fix by adding the missing ref counter increase on `split_vma()`, let's give it another try.
</blockquote></details>

Looks like problem solved, thanks.

___
___
*[`libos/src/bookkeep/libos_vma.c` line 1441 at r10](https://reviewable.io/reviews/gramineproject/gramine/1523#-Nji69EX72g1krrOP9DV:-Njl-_FP0hDutFEYJsdu:bq36y10) ([raw file](https://github.com/gramineproject/gramine/blob/547cb274e9d6ebe9c40b936bf5a60a0dc0928de9/libos/src/bookkeep/libos_vma.c#L1441)):*
> But this idea doesn't seem to be correct against race conditions? What in the meantime someone does something which actually should reload a mapping here? The msync-in-progress will turn the reloading into a no-op?

Yes, there is a possibility of data races. We even discussed it very long time ago with Pawel (when he implemented `msync()`, which structure Kailun took for this "reload VMAs"). Here's a relevant link: https://github.com/gramineproject/gramine/pull/550#pullrequestreview-954778149

Note that:
1. We already have possibility for data races in this func anyway, see the NOTE in the code.
2. It's impossible to take a global VMA lock here, because this lock is very widely used (e.g., if a `fs_ops->read()` callback wants to malloc, it will probably land into the VMA code and will try to re-acquire the VMA lock). In other words, we can't blindly protect with a global VMA lock because we'll have deadlocks due to nested locking.
3. An argument that it is fine: this `reload_mmaped_from_file_handle()` is always called from an operation on an active VMA (e.g. `write()` or `munmap()` syscalls). So at least the current VMA will *not* be freed/remaped while we're in this func. There is a possibility that another thread of the app will suddenly do something with other VMAs that are backed by this file handle, but it means a buggy application.

---

> Otherwise we are doomed to have these meaningless read/write operations on each munmap, which is a frequent op.

On a second thought, this munmap-of-file-backed-region shouldn't be a frequent operation. Typically apps load e.g. a binary image inside process memory and just keep it there forever, or load e.g. a database file and keep it there also forever. So munmap should be rare actually.

Moreover, if we imagine the same file mmapped twice (I don't know why anyone would do it), then the current munmap logic starts to make sense -- yes, the first mmapped region (the one that is being munmapped) will be redundantly reloaded, but the second mmapped region will correct be reloaded. So this looks reasonable after all.

@kailun-qin Can we add a `NOTE` comment describing this inefficiency?
___
*[`libos/src/bookkeep/libos_vma.c` line 1429 at r12](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njl-6qQE6KfZiJaytiC:-Njl-6qQE6KfZiJaytiD:b-y4ptot) ([raw file](https://github.com/gramineproject/gramine/blob/b6b5787c9f55158bd2849f4f20c7b18378237b77/libos/src/bookkeep/libos_vma.c#L1429)):*
> ```C
>             goto out;
>         } else if (count == 0) {
>             goto out;
> ```

Aren't you supposed to `break` here? Or at least specify `ret = 0` before.

Otherwise looks like you have undefined value of `ret` in this case.

Also, you could add a quick comment for this case, that it's possible that the underlying file contents do not cover the whole VMA region, and thus `count == 0`.


<!-- Sent from Reviewable.io -->

2023-11-21 11:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-22 15:55 UTC, mkow requested changes
> Reviewed 1 of 2 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_vma.c` line 1380 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjrfReQ-nY1dSfGhrQe:-NjrfReQ-nY1dSfGhrQf:b-ttnhz7) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1380)):*
> ```C
>         return false;
> 
>     assert(vma->file);
> ```

Actually, why is this true? Aren't we iterating over all VMAs, including the ones without a backing file?
___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-Njrfkhb49PmaYiktAfn:b-v8ouzn) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
> ```C
>     assert(vma->file);
> 
>     if (hdl && hdl->inode && vma->file->inode && vma->file->inode != hdl->inode)
> ```

Doesn't this check work a bit unexpectedly? I think that now, if you pass a handle without a file (`hdl->inode == NULL`), which is clearly expected/allowed by this function, it will reload all the mappings?


<!-- Sent from Reviewable.io -->

2023-11-22 16:51 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1380 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjrfReQ-nY1dSfGhrQe:-NjrtNST7UUbys-WyZyr:b-5c7ro1) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1380)):*
> Aren't we iterating over all VMAs, including the ones without a backing file?

For those VMAs w/o a backing file, shouldn't they contain `MAP_ANONYMOUS` and would return earlier? (Or am I missing sth?)
___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-Njrtmy77_PZoXm16qDw:b-2fdd0b) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Doesn't this check work a bit unexpectedly? I think that now, if you pass a handle without a file (`hdl->inode == NULL`), which is clearly expected/allowed by this function, it will reload all the mappings?
</blockquote></details>

But reload is invoked from the `write` callback where it's actually guaranteed to have `hdl->inode`?


<!-- Sent from Reviewable.io -->

2023-11-22 22:55 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_vma.c` line 1380 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-NjrfReQ-nY1dSfGhrQe:-NjtE_Go02bNWJ-DcQ2w:bcn3o5u) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1380)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Aren't we iterating over all VMAs, including the ones without a backing file?

For those VMAs w/o a backing file, shouldn't they contain `MAP_ANONYMOUS` and would return earlier? (Or am I missing sth?)
</blockquote></details>

Ah, right.
___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-NjtEQkB9mUf_6TIomCP:b-6jb58) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But reload is invoked from the `write` callback where it's actually guaranteed to have `hdl->inode`?
</blockquote></details>

Ok, but then why checking it in runtime? It looks like this was a valid and possible case. If it's impossible then it should be an assert.


<!-- Sent from Reviewable.io -->

2023-11-23 02:18 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-Njty8Jf7pM1j8qGdRjr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but then why checking it in runtime? It looks like this was a valid and possible case. If it's impossible then it should be an assert.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-23 07:06 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-Njuyhem4iOz1hs4ZW8m:b96067z) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@kailun-qin I think it's still a bit misleading.

I agree that `hdl->inode` must always exist (because this func is ultimately invoked from the `write()` callbacks that indeed have `hdl->inode`). The assert `assert(hdl && hdl->inode)` is fine with me.

However, I don't like the assert on `assert(vma->file->inode)`. In this code, we're just browsing through all file-backed VMA mappings, and since our documentation says that `libos_handle::inode` can be optional -- even though I think that's not true for files that can be mmapped -- we must not blindly assert on `vma->file->inode`. This will also be similar to how you check `vma->file->inode` in other places in this PR.

So in all, that's my suggestion:
```
    struct libos_handle* hdl = arg;
    assert(hdl && hdl->inode); /* guaranteed to have inode because invoked from `write` callback */

    if (vma->flags & (VMA_UNMAPPED | VMA_INTERNAL | MAP_ANONYMOUS | MAP_PRIVATE))
        return false;

    assert(vma->file); /* check above filtered out non-file-backed mappings */

    if (!vma->file->inode || vma->file->inode != hdl->inode)
        return false;
```


<!-- Sent from Reviewable.io -->

2023-11-23 07:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1382 at r13](https://reviewable.io/reviews/gramineproject/gramine/1523#-Njrfkhb49PmaYiktAfm:-Njv2hyc3cTHrEAC0NNn:bofcup1) ([raw file](https://github.com/gramineproject/gramine/blob/fd57351cd524739bd9fc373ba0c3f4b22458424c/libos/src/bookkeep/libos_vma.c#L1382)):*
Thanks for the suggestion!

> even though I think that's not true for files that can be mmapped

Yes, this was my previous assumption.

> since our documentation says that `libos_handle::inode` can be optional, ...,we must not blindly assert on `vma->file->inode`

Yes, I'm updating to the proposed version -- which makes more sense.


<!-- Sent from Reviewable.io -->

2023-11-23 08:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-23 11:07 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-23 11:33 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-11-23 11:54 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1523)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-23 19:02 UTC, merged