[LibOS] Remove assertion in `parse_mmap_flags()`
gramineproject/gramine pull request #1524
Opened 2023-08-30 06:31 UTC by kailun-qin

## Description of the changes 
In case of invalid MAP_TYPE flags in mmap requests (e.g., no or wrong mapping type specified), previously Gramine simply ran into assertion fails when parsing them in debug mode.

Instead, Gramine should parse the flags and fail with the same error on syscall handling as Linux does (on incorrect flags).

Fixes https://github.com/gramineproject/gramine/issues/1516.

## How to test this PR? 

CI

2023-08-30 06:35 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-08-31 23:24 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/src/libos_parser.c` line 837 at r1](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdCuD3Y88Od92O2o6J-:-NdCuD3Y88Od92O2o6J0:bomss2v) ([raw file](https://github.com/gramineproject/gramine/blob/10c2668e35b11eacc0182c831f285113eeedc2b9/libos/src/libos_parser.c#L837)):*
> ```C
>         flags &= ~MAP_SHARED;
>     } else {
>         assert(flags & MAP_PRIVATE);
> ```

But now the printing is wrong: it can print `MAP_PRIVATE` when it's not there.


<!-- Sent from Reviewable.io -->

2023-08-31 23:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`libos/src/libos_parser.c` line 837 at r1](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdCuD3Y88Od92O2o6J-:-NdCxpeI4mBU18OdvxDi:b8kyj9d) ([raw file](https://github.com/gramineproject/gramine/blob/10c2668e35b11eacc0182c831f285113eeedc2b9/libos/src/libos_parser.c#L837)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now the printing is wrong: it can print `MAP_PRIVATE` when it's not there.
</blockquote></details>

Yeah, I guess this was what I was asking here: https://github.com/gramineproject/gramine/issues/1516#issuecomment-1698478533. Maybe we should parse the flags "faithfully".


<!-- Sent from Reviewable.io -->

2023-09-01 00:03 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/src/libos_parser.c` line 837 at r1](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdCuD3Y88Od92O2o6J-:-NdD1FHLCenfZ1ZHQE5i:b-9h68yo) ([raw file](https://github.com/gramineproject/gramine/blob/10c2668e35b11eacc0182c831f285113eeedc2b9/libos/src/libos_parser.c#L837)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yeah, I guess this was what I was asking here: https://github.com/gramineproject/gramine/issues/1516#issuecomment-1698478533. Maybe we should parse the flags "faithfully".
</blockquote></details>

I think we should just skip printing of this flag if it's missing (i.e. change this `else` to `else-if`). For sure I don't like the current version which prints it when it's not actually there :)


<!-- Sent from Reviewable.io -->

2023-09-01 14:11 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdFTL1A7CW0_MG4JYy1):*
This is too low level for a one-liner, doesn't even say what component is modified and what flag is skipped.



_Suggestion:_
```
[LibOS] Fix flag printing in syscall parser
```
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdG2qa48lmSq4JznikZ):*
You actually listed all the cases here, so no "e.g." :)
___
*[`libos/src/libos_parser.c` line 697 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdG3XuK5xEpNfGOnMra:-NdG3XuLDyZRJQGOSQyU:b-87isph) ([raw file](https://github.com/gramineproject/gramine/blob/604245414001116dcc648c07841e258a797c8714/libos/src/libos_parser.c#L697)):*
> ```C
>         buf_puts(buf, "O_RDWR");
>         flags &= ~O_RDWR;
>     } else if (flags & O_RDONLY) {
> ```

Welcome to Linux!
https://elixir.bootlin.com/linux/v6.5/source/include/uapi/asm-generic/fcntl.h#L20
```C
#define O_RDONLY	00000000
```

:)

This whole check is wrong, it should switch on `flags & O_ACCMODE`, not bitmask them.


<!-- Sent from Reviewable.io -->

2023-09-01 15:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdFTL1A7CW0_MG4JYy1):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is too low level for a one-liner, doesn't even say what component is modified and what flag is skipped.
</blockquote></details>

Done.
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdG2qa48lmSq4JznikZ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You actually listed all the cases here, so no "e.g." :)
</blockquote></details>

Done.
___
*[`libos/src/libos_parser.c` line 697 at r2](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdG3XuK5xEpNfGOnMra:-NdGH0Ps3zFruBfoT0Cx:b-o7vuhc) ([raw file](https://github.com/gramineproject/gramine/blob/604245414001116dcc648c07841e258a797c8714/libos/src/libos_parser.c#L697)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Welcome to Linux!
https://elixir.bootlin.com/linux/v6.5/source/include/uapi/asm-generic/fcntl.h#L20
```C
#define O_RDONLY	00000000
```

:)

This whole check is wrong, it should switch on `flags & O_ACCMODE`, not bitmask them.
</blockquote></details>

Good catch! Done.


<!-- Sent from Reviewable.io -->

2023-09-01 15:27 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/libos_parser.c` line 694 at r3](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdGKpEc-mbqlL2FJJeS:-NdGKpEc-mbqlL2FJJeT:bjrvyo1) ([raw file](https://github.com/gramineproject/gramine/blob/62b51f87851afe1913321127effb72e7d817e9c0/libos/src/libos_parser.c#L694)):*
> ```C
>         case O_RDONLY:
>             buf_puts(buf, "O_RDONLY");
>             break;
> ```

I wouldn't silently assume that `O_RDONLY` is 0, and on some architectures/OSes it actually isn't.


<!-- Sent from Reviewable.io -->

2023-09-01 15:32 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/libos_parser.c` line 694 at r3](https://reviewable.io/reviews/gramineproject/gramine/1524#-NdGKpEc-mbqlL2FJJeS:-NdGMp1p1EmDcuzE8o_t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/62b51f87851afe1913321127effb72e7d817e9c0/libos/src/libos_parser.c#L694)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't silently assume that `O_RDONLY` is 0, and on some architectures/OSes it actually isn't.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-01 17:09 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-03 08:52 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-03 10:26 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-03 23:55 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-09-03 23:56 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1524)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-03 23:57 UTC, merged