[LibOS] Fix `ENOENT` error in `fchmod` on unlinked file
gramineproject/gramine pull request #1538
Opened 2023-09-06 03:28 UTC by sahason

## Description of the changes 
Fix `ENOENT` error when `fchmod` is called on unlinked file

## How to test this PR? 
`rename_unlink` regression test is extended to validate this implementation.

2023-09-06 13:49 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdekCsX5J2B2PtSE-60:-NdekCsX5J2B2PtSE-61:bi9aqxw) (no related file):*
Generally a good PR! What was the workload that failed on it, and why? (It's rather uncommon for application to remove the file, and then continue modifying its parameters.)

___
___
*[`libos/include/libos_fs.h` line 386 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdeiQTQ9rw64pwPqfJp:-NdeiQTR1hxFHUM325KA:b-yuruvy) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/include/libos_fs.h#L386)):*
> ```objc
>      * On success, the caller should update `hdl->inode->perm`.
>      */
>     int (*fchmod)(struct libos_handle* hdl, mode_t perm);
> ```

This callback should be declared in `libos_fs_ops`, not in `libos_d_ops`. Please move it there.
___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-NdejrKG9epP8hHxbO6y:brhdry3) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
> ```C
>     lock(&hdl->inode->lock);
>     hdl->inode->perm = perm;
>     unlock(&hdl->inode->lock);
> ```

You don't need these three lines, because you already have it in the `fchmod()` implementations.


<!-- Sent from Reviewable.io -->

2023-09-07 00:32 UTC, mkow reviewed
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-09-07 10:48 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 1 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdekCsX5J2B2PtSE-60:-Ndj9QZq-hRJPzRtt6fY:bksvcn1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Generally a good PR! What was the workload that failed on it, and why? (It's rather uncommon for application to remove the file, and then continue modifying its parameters.)
</blockquote></details>

Gunicorn workload failed on it. I assume this is the file (https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/workertmp.py).

___
___
*[`libos/include/libos_fs.h` line 386 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdeiQTQ9rw64pwPqfJp:-NdjB3FI3wREq6VBq_eM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/include/libos_fs.h#L386)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This callback should be declared in `libos_fs_ops`, not in `libos_d_ops`. Please move it there.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-NdjB6ez58tvympu4DOw:bbszou2) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need these three lines, because you already have it in the `fchmod()` implementations.
</blockquote></details>

These lines are not part of `fchmod` implementation for `tmpfs` if I remove this `chmod_stat` in `libos/fs/test` fails for `tmpfs` file. https://github.com/gramineproject/gramine/blob/94123cb244cf1b4dbfc0bfcb0805806ca6fcb1a5/libos/test/fs/chmod_stat.c#L35C1-L35C1. So, I have kept this part as this is common for all filesystems and removed from`fchmod` implementation of  `chroot` and `encrypted`.


<!-- Sent from Reviewable.io -->

2023-09-07 22:29 UTC, mkow requested changes
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 3 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`libos/include/libos_fs.h` line 192 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl6gOWBTMVRvuXO818:-Ndl6gOXBfgUUEqTTj0Y:b-z3mwdm) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L192)):*
> ```objc
>      * \brief Change file permissions.
>      *
>      * \param hdl  File handle.
> ```

Please fix the alignment.
___
*[`libos/include/libos_fs.h` line 195 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7DdOBh_6ASVqcluZ:-Ndl7DdOBh_6ASVqclu_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L195)):*
> ```objc
>      * \param perm  New permissions for the file.
>      *
>      * Changes the permissions of a file associated with a given file descriptor.
> ```





_Suggestion:_
```objc
associated with a given file handle
```
___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-Ndl7iVmCjp0fe6mutkL:benzm6y) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
> ```objc
>      * Changes the permissions of a file associated with a given file descriptor.
>      *
>      * On success, the caller should update `hdl->inode->perm`.
> ```

Hmm, why the caller, not this function? Seems error prone.



_Code quote:_
```objc
On success, the caller should update `hdl->inode->perm`.
```
___
*[`libos/src/fs/chroot/encrypted.c` line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdlBV-94NK-jt4k7yG2:-NdlBV-A8qS7DPhI-mpU:bke3hi8) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L236)):*
> ```C
>     hdl->type = TYPE_CHROOT_ENCRYPTED;
>     hdl->pos = 0;
>     hdl->pal_handle = enc->pal_handle;
> ```

Can you explain this change? What happens with the old `hdl->pal_handle`? Is it leaked? Or maybe it is guaranteed to always be `NULL` here?
___
*[`libos/src/fs/chroot/encrypted.c` line 386 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdljtGl4PhuwQsD86uE:-NdljtGl4PhuwQsD86uF:bbkyecp) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L386)):*
> ```C
> 
> out:
>     unlock(&hdl->inode->lock);
> ```

Where's the matching `lock()`?


<!-- Sent from Reviewable.io -->

2023-09-08 04:38 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 3 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_fs.h` line 192 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl6gOWBTMVRvuXO818:-NdmpQIf57DUaQeQBaq9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the alignment.
</blockquote></details>

Done.
___
*[`libos/include/libos_fs.h` line 195 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7DdOBh_6ASVqcluZ:-NdmnzY38LjFP4ILYc7l:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L195)):*
> ```objc
>      * \param perm  New permissions for the file.
>      *
>      * Changes the permissions of a file associated with a given file descriptor.
> ```

Done.
___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-NdmnwWvD-Jsys37n6x-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, why the caller, not this function? Seems error prone.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdlBV-94NK-jt4k7yG2:-Ndmr5oTCxN9ersQjFbY:b-anrdeh) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can you explain this change? What happens with the old `hdl->pal_handle`? Is it leaked? Or maybe it is guaranteed to always be `NULL` here?
</blockquote></details>

This associates the `PAL` handle with a `LibOS` handle. It is not leaked and it is guaranteed to be always `NULL` here. After this is set to `0` at the time of `LibOS` handle creation there is no other place where it is assigned to any value.
___
*[`libos/src/fs/chroot/encrypted.c` line 386 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdljtGl4PhuwQsD86uE:-NdmnPFw94t2tqIPLXRl:b4zp28j) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L386)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where's the matching `lock()`?
</blockquote></details>

Missed removing it in last commit. It is not required.


<!-- Sent from Reviewable.io -->

2023-09-08 07:54 UTC, dimakuv requested changes
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-NdnmA-p3-QJoSCmzU1O:bqdi07a) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, this function should update it. Not the caller. (Which was so in your first commit, but then you changed it in your fixup commits.)
___
*[`libos/src/fs/chroot/encrypted.c` line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdlBV-94NK-jt4k7yG2:-Ndni--FD-Mlm1nadLbE:b-jaigc1) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L236)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

This associates the `PAL` handle with a `LibOS` handle. It is not leaked and it is guaranteed to be always `NULL` here. After this is set to `0` at the time of `LibOS` handle creation there is no other place where it is assigned to any value.
</blockquote></details>

@mkow There is no "old" `pal_handle`. It was previously intentionally set to NULL. You can check the top-level comments in this file.

Pawel did it so to encapsulate operations with the "real host FD" (which is basically what `pal_handle` gives access to). The "real host FD" is supposed to be accessed only via the `struct libos_encrypted_file` object, to signify that all operations are supposed to go through the "encryption/decryption" layer of logic.

To get to the `pal_handle`, it typically looks like this:
```
struct libos_encrypted_file* enc = hdl->inode->data;
do_something_with(enc->pal_handle);
```

In here, @sahason added a shortcut to be able to directly access `hdl->pal_handle`. I first regarded it as fine, but now I think it's a slippery slope. I think we need to do the above, and **not touch `hdl->pal_handle`**.
___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-NdnlNi802CCwlPUGKdB:bklpm8t) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

These lines are not part of `fchmod` implementation for `tmpfs` if I remove this `chmod_stat` in `libos/fs/test` fails for `tmpfs` file. https://github.com/gramineproject/gramine/blob/94123cb244cf1b4dbfc0bfcb0805806ca6fcb1a5/libos/test/fs/chmod_stat.c#L35C1-L35C1. So, I have kept this part as this is common for all filesystems and removed from`fchmod` implementation of  `chroot` and `encrypted`.
</blockquote></details>

Well, it's a bug in tmpfs... I see that the same problem is with `chmod()` implementation, so this bug was already there.

Please revert your last change, and keep `hdl->inode->perm = perm;` line in each of the `fchmod()` callback implementations (and the surrounding locks and asserts, as it was before your fixup commit).

We can keep these three lines here for now, and we'll decide what to do with them in the next iteration of this PR.


<!-- Sent from Reviewable.io -->

2023-09-08 10:12 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 4 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-Ndo7iVU2ri_QPgwYYNp:b-1m64d0) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this function should update it. Not the caller. (Which was so in your first commit, but then you changed it in your fixup commits.)
</blockquote></details>

No Dmitrii it was there in first commit and for existing 'chmod' description.
___
*[`libos/src/fs/chroot/encrypted.c` line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdlBV-94NK-jt4k7yG2:-Ndo9vYa1y2OvTo4_XFU:b-co8psl) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L236)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow There is no "old" `pal_handle`. It was previously intentionally set to NULL. You can check the top-level comments in this file.

Pawel did it so to encapsulate operations with the "real host FD" (which is basically what `pal_handle` gives access to). The "real host FD" is supposed to be accessed only via the `struct libos_encrypted_file` object, to signify that all operations are supposed to go through the "encryption/decryption" layer of logic.

To get to the `pal_handle`, it typically looks like this:
```
struct libos_encrypted_file* enc = hdl->inode->data;
do_something_with(enc->pal_handle);
```

In here, @sahason added a shortcut to be able to directly access `hdl->pal_handle`. I first regarded it as fine, but now I think it's a slippery slope. I think we need to do the above, and **not touch `hdl->pal_handle`**.
</blockquote></details>

Thanks for the explanation. Updated it.
___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-NdoBNFXBHPX38PeFpoJ:bp3aow6) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, it's a bug in tmpfs... I see that the same problem is with `chmod()` implementation, so this bug was already there.

Please revert your last change, and keep `hdl->inode->perm = perm;` line in each of the `fchmod()` callback implementations (and the surrounding locks and asserts, as it was before your fixup commit).

We can keep these three lines here for now, and we'll decide what to do with them in the next iteration of this PR.
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2023-09-08 11:58 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-Ndod41v7Z9ycpVCuVoE:b8gzrnz) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> No Dmitrii it was there in first commit

But that's exactly what he said? It was in the first version of the PR, but then you removed it when changing code?

> this function should update

Now you're describing the function, not the caller, so it should be "this function updates".
</blockquote></details>

Ok. It is addressed.
___
*[`libos/src/fs/chroot/encrypted.c` line 386 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdljtGl4PhuwQsD86uE:-NdoZijRAi77_7bmeImt:b-419rug) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/src/fs/chroot/encrypted.c#L386)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It is definitely required, you can't have unmatched locks/unlocks.
</blockquote></details>

Wanted to remove both `lock()` and `unlcok()` as the `hdl->node->perm` was updated in the caller as well but missed removing`unlock()`.  But reverted the code as per the review comments.
___
*[`libos/src/fs/chroot/encrypted.c` line 375 at r4](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdoIZkI6VHM_rCUeur1:-NdobMD908frKy1t9pMx:bnunkcx) ([raw file](https://github.com/gramineproject/gramine/blob/767336fed4224954c9614c3fff9a21ac19f71719/libos/src/fs/chroot/encrypted.c#L375)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why the assert here?
</blockquote></details>

Before accessing `lock` checking if `hdl->inode` is non-null.
___
*[`libos/src/fs/chroot/fs.c` line 480 at r4](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdoIo-16ShZpcd5CqYt:-NdoawS81Hny9HQTqGCc:bnunkcx) ([raw file](https://github.com/gramineproject/gramine/blob/767336fed4224954c9614c3fff9a21ac19f71719/libos/src/fs/chroot/fs.c#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of this assert?
</blockquote></details>

Before accessing `lock` checking if `hdl->inode` is non-null.


<!-- Sent from Reviewable.io -->

2023-09-08 12:11 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-NdogM90CwtXAZ2feAMF:b-3f559e) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Ok. It is addressed.
</blockquote></details>

Hmm, it's not?
___
*[`libos/src/fs/chroot/encrypted.c` line 375 at r4](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdoIZkI6VHM_rCUeur1:-NdogSn43j9CVnZgR2hn:bu0a0mi) ([raw file](https://github.com/gramineproject/gramine/blob/767336fed4224954c9614c3fff9a21ac19f71719/libos/src/fs/chroot/encrypted.c#L375)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Before accessing `lock` checking if `hdl->inode` is non-null.
</blockquote></details>

I mean, I know what this line does, the question is _why_ you added it. No other function here asserts for this, and also there's no point in asserting all possible caller errors, only the likely ones (e.g. you don't assert here that `hdl != NULL`, but assert `hdl->inode` , why?).


<!-- Sent from Reviewable.io -->

2023-09-08 16:04 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 5 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/include/libos_fs.h` line 197 at r2](https://reviewable.io/reviews/gramineproject/gramine/1538#-Ndl7iVmCjp0fe6mutkK:-NdpWmh56mhYy771lp8y:b-6q4gt4) ([raw file](https://github.com/gramineproject/gramine/blob/7df3d00d3b160d9bda202d6bbcbecaaffd263509/libos/include/libos_fs.h#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, it's not?
</blockquote></details>

Ok. I thought it was about caller vs function. Updated it. 
___
*[`libos/src/fs/chroot/encrypted.c` line 375 at r4](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdoIZkI6VHM_rCUeur1:-NdpU43l7QW1Zgr_eqi7:b-6jdguy) ([raw file](https://github.com/gramineproject/gramine/blob/767336fed4224954c9614c3fff9a21ac19f71719/libos/src/fs/chroot/encrypted.c#L375)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean, I know what this line does, the question is _why_ you added it. No other function here asserts for this, and also there's no point in asserting all possible caller errors, only the likely ones (e.g. you don't assert here that `hdl != NULL`, but assert `hdl->inode` , why?).
</blockquote></details>

The `fchmod` is written `similarly` as `chmod` https://github.com/gramineproject/gramine/blob/8f65e6ad7444410d576a63fd0e5f443ced82830c/libos/src/fs/chroot/encrypted.c#L341. In `chmod` there is an assert for dent->inode. Hence added in `fchmod` as well. If it is unnecessary, I will remove it.


<!-- Sent from Reviewable.io -->

2023-09-08 23:44 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/chroot/encrypted.c` line 375 at r4](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdoIZkI6VHM_rCUeur1:-Ndqu5oj5sFlzmmqpFhJ:bohhp8a) ([raw file](https://github.com/gramineproject/gramine/blob/767336fed4224954c9614c3fff9a21ac19f71719/libos/src/fs/chroot/encrypted.c#L375)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The `fchmod` is written `similarly` as `chmod` https://github.com/gramineproject/gramine/blob/8f65e6ad7444410d576a63fd0e5f443ced82830c/libos/src/fs/chroot/encrypted.c#L341. In `chmod` there is an assert for dent->inode. Hence added in `fchmod` as well. If it is unnecessary, I will remove it.
</blockquote></details>

Ok, I see that `chmod` also does this, let's leave it then for consistency.


<!-- Sent from Reviewable.io -->

2023-09-09 17:34 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-Ndv-63IE19Nkmek77C7:btdix6p) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Reverted.
</blockquote></details>

Ok, sorry to go back and forth, but I did a deep dive, and the `perm` assignment should actually happen **in the caller**, not in this `fchmod()` callback.

Similarly to the case of `chmod()`, which I fixed in my PR: https://github.com/gramineproject/gramine/pull/1542

So actually we'll need to do the following:
1. Wait until that PR is merged (it becomes a prerequisite)
2. Rebase this PR.
3. Revert to the no-perm-assignment version (which will also have no lock/unlock).

I can take this PR over, and drive it to conclusion.


<!-- Sent from Reviewable.io -->

2023-09-11 02:01 UTC, kailun-qin reviewed
> Reviewed 1 of 6 files at r1, 2 of 5 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-09-11 05:08 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-Ne1b4l-23LwU59-OiRK:bhq8jnu) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, sorry to go back and forth, but I did a deep dive, and the `perm` assignment should actually happen **in the caller**, not in this `fchmod()` callback.

Similarly to the case of `chmod()`, which I fixed in my PR: https://github.com/gramineproject/gramine/pull/1542

So actually we'll need to do the following:
1. Wait until that PR is merged (it becomes a prerequisite)
2. Rebase this PR.
3. Revert to the no-perm-assignment version (which will also have no lock/unlock).

I can take this PR over, and drive it to conclusion.
</blockquote></details>

I have gone through PR #1542. I would like to finish this PR as we have one fixup commit like this. What do you say?


<!-- Sent from Reviewable.io -->

2023-09-11 07:13 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-Ne24YJH1xraLcMvXUh9:blpxla9) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have gone through PR #1542. I would like to finish this PR as we have one fixup commit like this. What do you say?
</blockquote></details>

@sahason Sure, you can continue with this PR then. You'll need to wait until #1542 is merged, then rebase your PR on top of it, and apply that fixup commit that does the same logic.


<!-- Sent from Reviewable.io -->

2023-09-19 14:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-Nehl-dx4fGVYBIwWwQA:b-vxsaga) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Sure, you can continue with this PR then. You'll need to wait until #1542 is merged, then rebase your PR on top of it, and apply that fixup commit that does the same logic.
</blockquote></details>

#1542 was just merged. @sahason Can you rebase this PR now?


<!-- Sent from Reviewable.io -->

2023-09-20 05:41 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: 2 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/sys/libos_file.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1538#-NdejrKG9epP8hHxbO6x:-Nel5jD4Awkfj-5lwAD5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f8a59b899c5345d62e47c5fefa814ddaca394462/libos/src/sys/libos_file.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

#1542 was just merged. @sahason Can you rebase this PR now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-20 11:09 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-20 11:09 UTC, dimakuv commented
Jenkins, test this please

2023-09-20 12:30 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-20 13:05 UTC, kailun-qin approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-20 14:56 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-20 15:20 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-20 16:53 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1538)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-20 22:07 UTC, merged