[LibOS] Fix a few user-pointer checking bugs in syscalls
gramineproject/gramine pull request #1544
Opened 2023-09-10 02:23 UTC by mkow

## Description of the changes 

Inspired by #1543, I went through all the syscalls implementations and verified if they actually check user pointers.

Additionally fixes a bug in gettimeofday() implementation which left timezone struct uninitialized.

## How to test this PR? 

CI, mostly LTP.

2023-09-10 07:58 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`libos/src/sys/libos_getpid.c` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ndy4OjGEMABEbIRmbmT:-Ndy4OjGEMABEbIRmbmU:b-o3gxga) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_getpid.c#L31)):*
> ```C
>     struct libos_thread* cur = get_cur_thread();
>     lock(&cur->lock);
>     cur->clear_child_tid = tidptr; // will be lazy-verified (before writing to it)
> ```

Do you mean this place in code: https://github.com/gramineproject/gramine/blob/8f65e6ad7444410d576a63fd0e5f443ced82830c/libos/src/sys/libos_futex.c#L981

If yes, then I agree with the comment, and I'll unblock this comment.
___
*[`libos/src/sys/libos_socket.c` line 1352 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ndy4pEH8OQmvzLYw-Co:-Ndy4pEH8OQmvzLYw-Cp:bo70goc) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_socket.c#L1352)):*
> ```C
>     }
> 
>     if (!is_user_memory_readable(optlen, sizeof(*optlen))) {
> ```

This double-check of `optlen` looks convoluted... But ok, if you think it's more correct.


<!-- Sent from Reviewable.io -->

2023-09-10 11:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_getpid.c` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ndy4OjGEMABEbIRmbmT:-Ndyjf713DUD22v5DtA9:btih660) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_getpid.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you mean this place in code: https://github.com/gramineproject/gramine/blob/8f65e6ad7444410d576a63fd0e5f443ced82830c/libos/src/sys/libos_futex.c#L981

If yes, then I agree with the comment, and I'll unblock this comment.
</blockquote></details>

Yes, exactly.
___
*[`libos/src/sys/libos_socket.c` line 1352 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ndy4pEH8OQmvzLYw-Co:-Ndyjiem04lQlVouRpVm:b-8f0j79) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_socket.c#L1352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This double-check of `optlen` looks convoluted... But ok, if you think it's more correct.
</blockquote></details>

This is actually required to be 100% correct, write permission doesn't have to imply read permission, at least on some architectures, I think. Also, what Linux does is that it only checks the permissions when actually trying to access the variables (through `put_user()` and similar).


<!-- Sent from Reviewable.io -->

2023-09-10 18:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-09-11 01:27 UTC, kailun-qin approved these changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_getpid.c` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ne0piwF6c2zbb1QHF2s:-Ne0piwG7pyGD1M5grfe:bhx12v6) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_getpid.c#L31)):*
> ```C
>     struct libos_thread* cur = get_cur_thread();
>     lock(&cur->lock);
>     cur->clear_child_tid = tidptr; // will be lazy-verified (before writing to it)
> ```

I understand this is single-line and I don't really care. Just wondering - aren't we more in favor of comments in C-styple (slash asterisk)?



_Code quote:_
```C
// will be lazy-verified (before writing to it)
```


<!-- Sent from Reviewable.io -->

2023-09-11 01:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_getpid.c` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ne0piwF6c2zbb1QHF2s:-Ne0rlRK8GVtlE0W0L6v:bkygw1e) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_getpid.c#L31)):*
> aren't we more in favor of comments in C-styple

Personally I'm not, but yes, we voted to use them. But there are some exceptions like after-line comments, where the space is very limited, so we usually use `//` comments there (it's 3 chars shorter).
But for large, freestanding comments we should use `/*`+`*/` comments.


<!-- Sent from Reviewable.io -->

2023-09-11 01:41 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_getpid.c` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/1544#-Ne0piwF6c2zbb1QHF2s:-Ne0tMbq9dWBR_gp1szK:bw10oo2) ([raw file](https://github.com/gramineproject/gramine/blob/4853f4e768e21d71e204b23575234f215db3ab63/libos/src/sys/libos_getpid.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> aren't we more in favor of comments in C-styple

Personally I'm not, but yes, we voted to use them. But there are some exceptions like after-line comments, where the space is very limited, so we usually use `//` comments there (it's 3 chars shorter).
But for large, freestanding comments we should use `/*`+`*/` comments.
</blockquote></details>

Got it, thanks for the explanations!


<!-- Sent from Reviewable.io -->

2023-09-11 07:12 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-11 07:23 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1544)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-11 10:21 UTC, merged