[LibOS,PAL] Fix wrong handling of sysfs NUMA nodes when nodes are offline
gramineproject/gramine pull request #1545
Opened 2023-09-10 09:48 UTC by dimakuv

## Description of the changes 

Previously, Gramine iterated through all NUMA nodes within the range obtained from the host's `/sys/devices/system/node/possible` file to get `cpulist` and `distance`. It also used the count of possible nodes to parse the `distance` between nodes. However, there is no `/sys/devices/system/node/nodeX` directory when a node is not online. Also, `/sys/devices/system/node/nodeX/distance` lists distances between online nodes only (jumping over offline nodes). This can lead to failures when Gramine tries to read values of `cpulist` and `distance` pseudo-files from the directory. Plus a correct parsing of `distance` should consider only online nodes.

**This is version 2 of #1454.** @mkow asked to keep an original definition of the `distances` array for NUMA nodes inside Gramine, and this PR reflects this. Since the change is rather drastic from the original #1454 code, I chose to create it as a separate PR.

Fixes #1452. For more context and discussions, see #1452 and #1454.

## How to test this PR? 

Manually on weird NUMA platforms...

2023-09-10 16:37 UTC, mkow requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/sys/node_info.c` line 94 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzvmes5LTfge72PBbe:-Ndzvmes5LTfge72PBbf:bwucq1z) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/libos/src/fs/sys/node_info.c#L94)):*
> ```C
>             return ret;
>         if ((size_t)ret >= sizeof(str) - str_pos)
>             return -EOVERFLOW;
> ```

Maybe just:
```C
if (str_pos >= sizeof(str) - 1)
    return -EOVERFLOW;
str[str_pos] = '\n';
```
___
*[`pal/include/arch/x86_64/pal_topology.h` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-NdzvRrZEAk9p49OkfNh:-NdzvRrZEAk9p49OkfNi:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/include/arch/x86_64/pal_topology.h#L115)):*
> ```objc
>     /* Has `numa_nodes_cnt * numa_nodes_cnt` elements.
>      * numa_distance_matrix[i*numa_nodes_cnt + j] is NUMA distance from node i to node j.
>      * If node i or node j are offline, then NUMA distance is zero. */
> ```





_Suggestion:_
```objc
node i or node j is offline
```
___
*[`pal/src/host/linux-common/topo_info.c` line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-NdzuIiZEJ0CpoXG9jYZ:-NdzuIiZEJ0CpoXG9jY_:b4v4q5a) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L383)):*
> ```C
> 
>     if (online_nodes_cnt < 1) {
>         ret = -EINVAL;
> ```

No need for this check, there has to be at least on online CPU thread, which implies at least one online NUMA node (because of the containing relation).
___
*[`pal/src/host/linux-common/topo_info.c` line 404 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzuirz3GGmDsA3aZEy:-Ndzuirz3GGmDsA3aZEz:b-bh46te) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L404)):*
> ```C
>         if (!numa_nodes[i].is_online) {
>             for (size_t j = 0; j < nodes_cnt; j++)
>                 distances[i * nodes_cnt + j] = 0;
> ```

Maybe just memset/calloc the whole array outside the loop? Perf-wise will be identical because this array is small, and the loop will be simpler. But not blocking on this.
___
*[`pal/src/host/linux-common/topo_info.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzv8IhDGBhOGk8Zydo:-Ndzv8IhDGBhOGk8Zydp:bidckae) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L416)):*
> ```C
>             goto fail;
> 
>         /* expand the compressed view: add 0s to represent offline nodes in corresponding cells */
> ```

Wouldn't modifying `read_numbers_from_file()` be easier than this? Just change it (and rename) to place the parsed numbers only in online nodes' entries. You also could then remove calculating `online_nodes_cnt`.


<!-- Sent from Reviewable.io -->

2023-09-10 17:03 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-NdzuIiZEJ0CpoXG9jYZ:-Ne-1hkI5vp9JE4nuN1j:b-eyqvsu) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for this check, there has to be at least on online CPU thread, which implies at least one online NUMA node (because of the containing relation).
</blockquote></details>

Actually, aren't we missing this check in `sanitize_topo_info()`? I think we should check that if a thread/cpu is online, then the sockets / cores it belongs to should also be online?


<!-- Sent from Reviewable.io -->

2023-09-10 18:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 1 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/sys/node_info.c` line 94 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzvmes5LTfge72PBbe:-Ne-Nux73kkYqjhP2WT1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/libos/src/fs/sys/node_info.c#L94)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just:
```C
if (str_pos >= sizeof(str) - 1)
    return -EOVERFLOW;
str[str_pos] = '\n';
```
</blockquote></details>

Done.
___
*[`pal/include/arch/x86_64/pal_topology.h` line 115 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-NdzvRrZEAk9p49OkfNh:-Ne-O05P0ZL34cFvsT9L:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/include/arch/x86_64/pal_topology.h#L115)):*
> ```objc
>     /* Has `numa_nodes_cnt * numa_nodes_cnt` elements.
>      * numa_distance_matrix[i*numa_nodes_cnt + j] is NUMA distance from node i to node j.
>      * If node i or node j are offline, then NUMA distance is zero. */
> ```

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-NdzuIiZEJ0CpoXG9jYZ:-Ne-O6Ic59pa9lrdo6Vf:b-7nk46p) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, aren't we missing this check in `sanitize_topo_info()`? I think we should check that if a thread/cpu is online, then the sockets / cores it belongs to should also be online?
</blockquote></details>

Done both (note that we don't have `online` fields for cores and sockets -- only for threads and NUMA nodes)
___
*[`pal/src/host/linux-common/topo_info.c` line 404 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzuirz3GGmDsA3aZEy:-Ne-Qg9ZBNeR8u7Mcbjk:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L404)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just memset/calloc the whole array outside the loop? Perf-wise will be identical because this array is small, and the loop will be simpler. But not blocking on this.
</blockquote></details>

Done
___
*[`pal/src/host/linux-common/topo_info.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzv8IhDGBhOGk8Zydo:-Ne-QpeL9ZNF4iHDNyx7:b6lsr3o) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L416)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't modifying `read_numbers_from_file()` be easier than this? Just change it (and rename) to place the parsed numbers only in online nodes' entries. You also could then remove calculating `online_nodes_cnt`.
</blockquote></details>

Either I don't understand your idea, or you're underestimating the complexity of your approach. Maybe you can give a pseudo-code for this?


<!-- Sent from Reviewable.io -->

2023-09-10 22:03 UTC, mkow requested changes
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne-ye-f7pkA6kNN0dao:-Ne-ye-f7pkA6kNN0dap:b-34mvub) ([raw file](https://github.com/gramineproject/gramine/blob/a32094bde79f2c380ddf64b50575517897ec00ad/pal/src/host/linux-common/topo_info.c#L405)):*
> ```C
>         if (ret < 0)
>             goto fail;
>         ret = read_numbers_from_file(path, distances + i * nodes_cnt, nodes_cnt);
> ```

Interesting, this shouldn't work - `read_numbers_from_file()` fails if it read less numbers than `nodes_cnt` (last arg). So, it either fails on that special machine with less online nodes than possible, or `read_numbers_from_file()` has a bug and actually doesn't fail in this case.


<!-- Sent from Reviewable.io -->

2023-09-11 00:13 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ndzv8IhDGBhOGk8Zydo:-Ne0ZbWpEavjtjp8Fzed:b243qsl) ([raw file](https://github.com/gramineproject/gramine/blob/5b11492329079fedd172d1891100882914a6377c/pal/src/host/linux-common/topo_info.c#L416)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Either I don't understand your idea, or you're underestimating the complexity of your approach. Maybe you can give a pseudo-code for this?
</blockquote></details>

https://github.com/mkow/gramine/commit/4942a6c2e76f7202b0d7f54571bd3bd7565df62a
What do you think? It's shorter and IMO simpler, but the latter is subjective.


<!-- Sent from Reviewable.io -->

2023-09-11 04:18 UTC, kailun-qin reviewed
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne-ye-f7pkA6kNN0dao:-Ne1RXKSEX66LGaIgjlO:b-qtb99b) ([raw file](https://github.com/gramineproject/gramine/blob/a32094bde79f2c380ddf64b50575517897ec00ad/pal/src/host/linux-common/topo_info.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Interesting, this shouldn't work - `read_numbers_from_file()` fails if it read less numbers than `nodes_cnt` (last arg). So, it either fails on that special machine with less online nodes than possible, or `read_numbers_from_file()` has a bug and actually doesn't fail in this case.
</blockquote></details>

+1, I guess this would actually fail (on that special machine)?


<!-- Sent from Reviewable.io -->

2023-09-11 09:58 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne2e92t0NPV541ZVkTs:-Ne2e92t0NPV541ZVkTt:bh68xa7) ([raw file](https://github.com/gramineproject/gramine/blob/a32094bde79f2c380ddf64b50575517897ec00ad/pal/src/host/linux-common/topo_info.c#L64)):*
> ```C
> 
> /* Read a space-separated list of numbers.
>  * The file has to contain at least `count` numbers, otherwise this function returns `-EINVAL`. */
> ```

But we can still have `-EINVAL` cases for this function?



_Code quote:_
```C
otherwise this function returns `-EINVAL`
```
___
*[`pal/src/host/linux-common/topo_info.c` line 400 at r3](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne2bxQYBG2CgnR8CTwg:-Ne2bxQYBG2CgnR8CTwh:b-a7u2k7) ([raw file](https://github.com/gramineproject/gramine/blob/2a2921ee5e5bcc7cf9eda65c823bf8684d078069/pal/src/host/linux-common/topo_info.c#L400)):*
> ```C
>      *
>      *   [ node 0 -> node 0,    0    , node 0 -> node 2
>      *            0,            0    ,        0
> ```

nit (align the comma):
 
    *   [ node 0 -> node 0,    0    , node 0 -> node 2
    *            0        ,    0    ,        0



_Code quote:_
```C
     *   [ node 0 -> node 0,    0    , node 0 -> node 2
     *            0,            0    ,        0
```


<!-- Sent from Reviewable.io -->

2023-09-11 10:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne2e92t0NPV541ZVkTs:-Ne2m9N729syvXbaN38B:bcmeghj) ([raw file](https://github.com/gramineproject/gramine/blob/a32094bde79f2c380ddf64b50575517897ec00ad/pal/src/host/linux-common/topo_info.c#L64)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But we can still have `-EINVAL` cases for this function?
</blockquote></details>

@kailun-qin I'm not sure what change you want?


<!-- Sent from Reviewable.io -->

2023-09-11 16:07 UTC, kailun-qin reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne2e92t0NPV541ZVkTs:-Ne3upYd47HLJXZCUZrH:b-l7302f) ([raw file](https://github.com/gramineproject/gramine/blob/a32094bde79f2c380ddf64b50575517897ec00ad/pal/src/host/linux-common/topo_info.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin I'm not sure what change you want?
</blockquote></details>

Excuse me for the confusions.

I saw you removed "The file has to contain at least `count` numbers, otherwise this function returns `-EINVAL`." explicitly from the comment. Since `-EINVAL` is still possible for files w/ invalid format, I wonder whether we should keep the explanations on negative return values (but I don't insist).


<!-- Sent from Reviewable.io -->

2023-09-11 16:30 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-12 00:01 UTC, mkow requested changes
> Reviewed 1 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 386 at r4](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne5g4mD3r_wJV1ofmy9:-Ne5g4mD3r_wJV1ofmyA:bcgbsmj) ([raw file](https://github.com/gramineproject/gramine/blob/0d71798b5c8a8d39f59792842ff49c0882c5da4f/pal/src/host/linux-common/topo_info.c#L386)):*
> ```C
>          * of zero */
>         numa_nodes[i].nr_hugepages[HUGEPAGES_2M] = 0;
>         numa_nodes[i].nr_hugepages[HUGEPAGES_1G] = 0;
> ```

Previous version of the code zeroed these also for offline nodes, just to not have uninitialized data in case someone accidentally reads these for an offline node.


<!-- Sent from Reviewable.io -->

2023-09-12 07:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 386 at r4](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne5g4mD3r_wJV1ofmy9:-Ne7DIck7Nte6NBk-8pR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d71798b5c8a8d39f59792842ff49c0882c5da4f/pal/src/host/linux-common/topo_info.c#L386)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Previous version of the code zeroed these also for offline nodes, just to not have uninitialized data in case someone accidentally reads these for an offline node.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 07:57 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-12 22:53 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 386 at r4](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne5g4mD3r_wJV1ofmy9:-NeA_sVS5ezfYW-eNn3B:b-74r73n) ([raw file](https://github.com/gramineproject/gramine/blob/0d71798b5c8a8d39f59792842ff49c0882c5da4f/pal/src/host/linux-common/topo_info.c#L386)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, my brainlag, this doesn't make sense, it's untrusted code anyways. See:
https://github.com/gramineproject/gramine/blob/058997e62fa60ab6805f421b10c1b8dda6524996/pal/src/host/linux-sgx/pal_main.c#L196-L199

Previous version made more sense.


<!-- Sent from Reviewable.io -->

2023-09-13 08:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 386 at r4](https://reviewable.io/reviews/gramineproject/gramine/1545#-Ne5g4mD3r_wJV1ofmy9:-NeCZO_Q6U6AKPtgxrVm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0d71798b5c8a8d39f59792842ff49c0882c5da4f/pal/src/host/linux-common/topo_info.c#L386)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sorry, my brainlag, this doesn't make sense, it's untrusted code anyways. See:
https://github.com/gramineproject/gramine/blob/058997e62fa60ab6805f421b10c1b8dda6524996/pal/src/host/linux-sgx/pal_main.c#L196-L199

Previous version made more sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-13 08:22 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 372 at r6](https://reviewable.io/reviews/gramineproject/gramine/1545#-NeCcJ8z4twbOHuv4XQq:-NeCcJ8z4twbOHuv4XQr:bfug2vc) ([raw file](https://github.com/gramineproject/gramine/blob/e32922c045cd9f44df8b94d128d92d2be361a7bc/pal/src/host/linux-common/topo_info.c#L372)):*
> ```C
>     for (size_t i = 0; i < nodes_cnt; i++) {
>         if (!numa_nodes[i].is_online)
>                 continue;
> ```

4-space indentation pls



_Code quote:_
```C
                continue;
```
___
*[`pal/src/host/linux-common/topo_info.c` line 384 at r6](https://reviewable.io/reviews/gramineproject/gramine/1545#-NeCc5GuAg10WIHQ2qj6:-NeCc5GuAg10WIHQ2qj7:by5vgtw) ([raw file](https://github.com/gramineproject/gramine/blob/e32922c045cd9f44df8b94d128d92d2be361a7bc/pal/src/host/linux-common/topo_info.c#L384)):*
> ```C
> 
>         /* Since our sysfs doesn't support writes, set persistent hugepages to their default value
>          * of zero (we set them even for offline nodes just to not expose uninitialized data) */
> ```

This is wrong (after reverting)?



_Code quote:_
```C
we set them even for offline nodes just to not expose uninitialized data
```


<!-- Sent from Reviewable.io -->

2023-09-13 08:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 372 at r6](https://reviewable.io/reviews/gramineproject/gramine/1545#-NeCcJ8z4twbOHuv4XQq:-NeCg9B31C_TjcCJKLUI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e32922c045cd9f44df8b94d128d92d2be361a7bc/pal/src/host/linux-common/topo_info.c#L372)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

4-space indentation pls
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 384 at r6](https://reviewable.io/reviews/gramineproject/gramine/1545#-NeCc5GuAg10WIHQ2qj6:-NeCg8PYCaMaTI-FqoDk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e32922c045cd9f44df8b94d128d92d2be361a7bc/pal/src/host/linux-common/topo_info.c#L384)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is wrong (after reverting)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-13 08:41 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-09-13 11:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-13 11:29 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-13 11:39 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-13 11:58 UTC, dimakuv reviewed
I just tested on a "weird" platform. Without this PR, it failed. With this PR, it works!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1545#-:-NeDP2ir7LY-9t9D7O9t:bdrgawr)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-13 14:05 UTC, merged