[PAL/Linux-SGX] Ignore spurious exceptions in exception-handling flow
gramineproject/gramine pull request #1570
Opened 2023-09-26 09:33 UTC by dimakuv

## Description of the changes 

When enabled, the SGX EXINFO feature forces the CPU core to report #PF exceptions to the SGX enclave (in the EXITINFO/EXINFO SSA fields) whenever #PFs occur in the hardware, even if these #PFs are benign. By benign page faults we mean the ones that are handled completely by the host Linux kernel (more specifically, by the Linux SGX kernel driver).

Such benign #PF exceptions should be considered spurious -- they are reported to the SGX enclave (when `sgx.use_exinfo = true`), but they are completely resolved by the host Linux kernel and must be ignored by Gramine.

To add such functionality of ignoring spurious exceptions, the SGX asm code must be modified to forward both the trusted EXITINFO value and the untrusted external-event value to the `_PalExceptionHandler()` function.

For more context, see https://github.com/gramineproject/gramine/issues/1514, in particular:
- https://github.com/gramineproject/gramine/issues/1514#issuecomment-1734997236
- https://github.com/gramineproject/gramine/issues/1514#issuecomment-1735021045

Fixes #1514

I think it also fixes the problems described in the comments here: https://github.com/gramineproject/gramine/pull/1562

## How to test this PR? 

See e.g. https://github.com/gramineproject/gramine/issues/1514#issuecomment-1734997236

Generally, apply this:
```diff
diff --git a/libos/test/regression/manifest.template b/libos/test/regression/manifest.template
@@ -1,6 +1,8 @@
 loader.entrypoint = "file:{{ gramine.libos }}"
 libos.entrypoint = "{{ entrypoint }}"

+sgx.require_exinfo = true
+
 loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"
 loader.insecure__use_cmdline_argv = true
```

and try LibOS regression tests. They will fail from time to time.

2023-09-26 09:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFpr5t428LFJiuNuZv:-NfFpr5t428LFJiuNuZw:b21r6ez) (no related file):*
This requires rather deep understanding of the EXINFO feature.

Check the Intel SDM manual, Vol.3D, Chapters 35.9.1 and 35.9.2.

___
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFpa6v0NLnq4OxJ8Fs:-NfFpa6v0NLnq4OxJ8Ft:b-5gkod9) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/enclave_entry.S#L218)):*
> ```
>     # _PalExceptionHandler() as 2nd arg
>     andl $0xff, %edi
>     movl %edi, %r15d
> ```

FYI: I decided to shift the logic of choosing the event (between trusted EXITINFO and untrusted "external event" in RDI) to the C code from this asm code. I think it's just generally more readable to do the checks in C rather than in asm.


<!-- Sent from Reviewable.io -->

2023-09-26 09:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFr5HA5oRF1aFldEuE:-NfFr5HB9Hi1YbQKpCj9:b-uhbfuo) (no related file):*
I asked @anjalirai-intel to test all the workloads that she reported as failing (in #1561 and #1562). Waiting for her summary.

___


<!-- Sent from Reviewable.io -->

2023-09-26 10:13 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 266 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFyPJr0KTS0wGvYbiX:-NfFyPJr0KTS0wGvYbiY:b-z76wkc) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L266)):*
> ```C
>                 break;
>             case SGX_EXCEPTION_VECTOR_PF:
>                 if (!exinfo->errcd.p) {
> ```

May be we should zeroize `trusted_exit_info` in such case? (related to the questions below)
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 299 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFyFFX4HL9NIbpo6v2:-NfFyFFYAQHj38nvZfBP:bklan4u) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L299)):*
> ```C
>         log_error("Unexpected %s occurred inside PAL (%s)", event_name, buf);
> 
>         if (trusted_exit_info.valid) {
> ```

For the benign #PF which we considered spurious and ignored, why do we still log info based on it?
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 315 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFwWwp1EKlLlPJpFYJ:-NfFwWwp1EKlLlPJpFYK:b-kwmwhl) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L315)):*
> ```C
>     bool has_hw_fault_address = false;
> 
>     if (trusted_exit_info.valid) {
> ```

For the benign #PF which we considered spurious and ignored, why do we still set context based on it?


<!-- Sent from Reviewable.io -->

2023-09-26 11:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 266 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFyPJr0KTS0wGvYbiX:-NfG9OnPD5_DN0nG0SG3:b-ydonir) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L266)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

May be we should zeroize `trusted_exit_info` in such case? (related to the questions below)
</blockquote></details>

Done. Good idea.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 299 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFyFFX4HL9NIbpo6v2:-NfG9QMj2hPiF6x6-h8X:b-bx2pfp) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L299)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

For the benign #PF which we considered spurious and ignored, why do we still log info based on it?
</blockquote></details>

Done, not relevant now that we zeroize this object.

But we would never get into this `if` on benign #PFs anyway -- because in this case the `event_num` is NOT an SGX-reported hardware exception, so it will be an asynchronous event (`PAL_EVENT_QUIT` or `PAL_EVENT_INTERRUPTED`).
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 315 at r1](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFwWwp1EKlLlPJpFYJ:-NfGA1T38KhFPxO7uYJe:b3r9d0i) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L315)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

For the benign #PF which we considered spurious and ignored, why do we still set context based on it?
</blockquote></details>

Done, not relevant now that zeroize the object.

But again, these `ctx.err` and `ctx.cr2` would be irrelevant anyway, because the only events in this case are `PAL_EVENT_QUIT` or `PAL_EVENT_INTERRUPTED` which do not use these context variables.


<!-- Sent from Reviewable.io -->

2023-09-27 00:48 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-09-27 05:02 UTC, anjalirai-intel commented
@dimakuv I have summarized the details in #1562

2023-09-27 12:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFr5HA5oRF1aFldEuE:-NfLcx2xBcX_jEQijkSL:b1j24wm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I asked @anjalirai-intel to test all the workloads that she reported as failing (in #1561 and #1562). Waiting for her summary.
</blockquote></details>

Ok, @anjalirai-intel reported several issues even with this PR. I updated with two new commits, now the issues should be resolved.

@anjalirai-intel Could you please test all your workloads again?

___
___
*[`-- commits` line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfLb_Ts1NcAY7nI5NLJ):*
FYI: I stashed this commit into this PR, as it is related. This could be a separate PR if anyone really wants.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfLbklUDaMwvtsdxtgJ:-NfLbklUDaMwvtsdxtgK:b-mnxhbv) ([raw file](https://github.com/gramineproject/gramine/blob/7ca19ae8174d472151e4fd5b44dad3ac0a6da1f8/pal/src/host/linux-sgx/pal_exception.c#L266)):*
> ```C
>                 break;
>             case SGX_EXCEPTION_VECTOR_PF:
>                 if (untrusted_external_event != PAL_EVENT_MEMFAULT && !exinfo->errcd.p) {
> ```

FYI: My previous attempt at guessing a benign #PF was like this:
```
if (!exinfo->errcd.p)
```

which means that the P(resent) bit is not set, i.e. the page entry is not present in the page tables.

This turned out to be a wrong assumption, because a #PF can legitimately happen on e.g. COW pages, when the page is allocated with RO permissions and on a first write to it, its permissions are modified to RW. So I hit this particular case in several LTP workloads (in particular, I debugged `mkdir09`).

Therefore, we can't really decide on a #PF based on the error code in this field. It seems the only reasonable way is to double-check the SGX-hardware-reported exception against a host-reported signal. If the host reports an async signal (and NOT a memory fault), then it surely means that a #PF was benign and handled by the host kernel.

Note that this raises security concerns -- we make a decision based on the input (`untrusted_external_event`) from the possibly malicious host. However, this looks benign in our SGX threat model: if the host modified a real memory fault to e.g. a SIGCONT event, then the app will not handle a real memory fault and will get stuck in the hardware exception (hang, i.e. a DoS attack).


<!-- Sent from Reviewable.io -->

2023-09-27 15:26 UTC, anjalirai-intel commented
@dimakuv I have started the run, will share the findings tomorrow

2023-09-28 01:46 UTC, kailun-qin reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfLbklUDaMwvtsdxtgJ:-NfOQEVZ6O_PA5ycHc3G:b-m2ti6q) ([raw file](https://github.com/gramineproject/gramine/blob/7ca19ae8174d472151e4fd5b44dad3ac0a6da1f8/pal/src/host/linux-sgx/pal_exception.c#L266)):*
OK, looks like the heuristics does not always work.

> It seems the only reasonable way is to double-check the SGX-hardware-reported exception against a host-reported signal.

Not sure if there's a better way... but probably not.

> Note that this raises security concerns -- we make a decision based on the input (`untrusted_external_event`) from the possibly malicious host.

Can we also put some brief notes about the security concerns (and analysis) in the comments?


<!-- Sent from Reviewable.io -->

2023-09-28 07:15 UTC, anjalirai-intel commented
@dimakuv I have made the fix for Out-of-tree driver and removed ex_info flag from manifest file.

Among all the issues we reported, almost all are fixed, only 1 issue remains with out-of-tree driver. The error states to use sgx.use_exinfo flag for ltp test `setrlimit01` but we cannot use it, because it is not supported by hardware.

**Issue LTP:**
```
**setrlimit01**
[23.398] error: Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest.
```

2023-09-28 07:44 UTC, dimakuv reviewed
@anjalirai-intel Thanks for testing! See also my other comment about the `setrlimit01` case.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570#-:-NfPiHSSEyMCeFjgHtar:bvnbl31)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfFr5HA5oRF1aFldEuE:-NfPfX7gAneLpfm04u5G:b-6z52wf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, @anjalirai-intel reported several issues even with this PR. I updated with two new commits, now the issues should be resolved.

@anjalirai-intel Could you please test all your workloads again?
</blockquote></details>

So @anjalirai-intel reported that everything is fine except the `setrlimit01` LTP test.

This test prints "Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest." However, that particular machine has an old OOT driver and an old Intel CPU that doesn't have the EXINFO feature. So the message is kinda misleading, but I'm not sure if we can do much more about the message.

This test actually started failing *not* on this PR, but after the commit https://github.com/gramineproject/gramine/commit/9f80c4245a8a852a2d6ac30c81840c94db447305, which disables segfault handling if there is no `sgx.use_exinfo`. (This commit is on master for several days already.)

This test worked fine before the aforementioned commit because this test causes a #GP, which is translated into a SIGSEGV, which is propagated through the PAL layer to the LibOS layer to the application handler. See the relevant sources of `setrlimit01` here: https://github.com/linux-test-project/ltp/blob/d4ca29c608bfd2eeb4ba6031057b7e1fc2d44fe9/testcases/kernel/syscalls/setrlimit/setrlimit01.c#L238-L285

To summarize:
- Gramine's master now refuses to deliver mem faults (like #GP, #PF, aka SIGSEGV/SIGBUS signals) to applications without `sgx.use_exinfo`, because Gramine wants to report the correct faulting address always.
- Some applications (like the LTP tests) don't care about the faulting address, they just care about the mem fault event itself.
- On older Intel CPUs, we cannot enable `sgx.use_exinfo`.
- So, some applications simply **cannot be run** on older CPUs.

Re-reading our discussions on exactly this question in https://github.com/gramineproject/gramine/pull/1502, I would like to say that **the above behavior is expected**. So I think the correct decision is **to disable `setrlimit01` test on old machines**.

___
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/1570#-NfLbklUDaMwvtsdxtgJ:-NfPjJZ7-NTiJW2-4mkm:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/7ca19ae8174d472151e4fd5b44dad3ac0a6da1f8/pal/src/host/linux-sgx/pal_exception.c#L266)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

OK, looks like the heuristics does not always work.

> It seems the only reasonable way is to double-check the SGX-hardware-reported exception against a host-reported signal.

Not sure if there's a better way... but probably not.

> Note that this raises security concerns -- we make a decision based on the input (`untrusted_external_event`) from the possibly malicious host.

Can we also put some brief notes about the security concerns (and analysis) in the comments?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-28 07:49 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-28 22:36 UTC, mkow requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)

___
*[`-- commits` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMqtefDp7e9bLoPS4_):*




_Suggestion:_
```
failed with the above message.
```
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 496 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMtSSfEl8mbb2HNZUf:-NkMtSSfEl8mbb2HNZUg:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/enclave_entry.S#L496)):*
> ```
>     addq $SGX_CPU_CONTEXT_SIZE, SGX_GPR_RCX(%rbx)
> 
>     # Continue rewire SSA0 (args to _PalExceptionHandler()):
> ```





_Suggestion:_
```
Continue rewiring
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 283 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMzzFW3TWJW1Do8tKS:-NkMzzFW3TWJW1Do8tKT:bwixann) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/pal_exception.c#L283)):*
> ```C
>                      * threat model: if the host modified a real memory fault (valid #PF) to e.g. a
>                      * SIGCONT event, then the app will not handle a real memory fault and will get
>                      * stuck in the #PF exception (hang, i.e. a DoS attack).
> ```

This note seems to be misleading, it misses the case where the host changes a benign #PF into an arbitrary exception delivered to the enclave.


<!-- Sent from Reviewable.io -->

2023-11-29 10:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 1 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @kailun-qin, and @mkow)

___
*[`-- commits` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMqtefDp7e9bLoPS4_):*
Not relevant anymore (see the last commit's proposed message)
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 496 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMtSSfEl8mbb2HNZUf:-NkP9UqO-iE5Hj8zYiVq:b-nsq7n0) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/enclave_entry.S#L496)):*
> ```
>     addq $SGX_CPU_CONTEXT_SIZE, SGX_GPR_RCX(%rbx)
> 
>     # Continue rewire SSA0 (args to _PalExceptionHandler()):
> ```

Done. (2x)
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 283 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMzzFW3TWJW1Do8tKS:-NkPej2l-dIclI8F1s-C:b-95vz9q) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/pal_exception.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This note seems to be misleading, it misses the case where the host changes a benign #PF into an arbitrary exception delivered to the enclave.
</blockquote></details>

Done. 

This comment led me to add the "cross verification" of reported-by-host vs reported-by-SGX events. With this, the PR became significantly more than a simple "fix the #PF case", but the code changes are pretty straightforward. Please review carefully. I guess it was long overdue to harden this code.


<!-- Sent from Reviewable.io -->

2023-11-29 15:59 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 283 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMzzFW3TWJW1Do8tKS:-NkQmvxYAYob9jLle7Md:bhazcfv) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/pal_exception.c#L283)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. 

This comment led me to add the "cross verification" of reported-by-host vs reported-by-SGX events. With this, the PR became significantly more than a simple "fix the #PF case", but the code changes are pretty straightforward. Please review carefully. I guess it was long overdue to harden this code.
</blockquote></details>

Now that we removed the whole paragraph/note, but a DoS attack is still possible?


<!-- Sent from Reviewable.io -->

2023-11-29 17:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: 2 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 283 at r4](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkMzzFW3TWJW1Do8tKS:-NkR4-X83ZGS6WI5J4Nd:b-o3zwj9) ([raw file](https://github.com/gramineproject/gramine/blob/64aadb1caf2ed3bee5e5297fb8d28ed39a7aa86d/pal/src/host/linux-sgx/pal_exception.c#L283)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Now that we removed the whole paragraph/note, but a DoS attack is still possible?
</blockquote></details>

Done. Good point, let's keep that note.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 260 at r5](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkQpt5d-zkDzM8CKXcJ:-NkR4phr7DO4QeSZdYBW:b46vyxn) ([raw file](https://github.com/gramineproject/gramine/blob/91ebe7e34792b5764fb229aadaaa1bc1d8395411/pal/src/host/linux-sgx/pal_exception.c#L260)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This also looks a bit weird (or is this intended maybe?)
</blockquote></details>

Done. It's not intended that way, it's just that ASCIIFlow that I use rendered like this. I fixed manually these weird cases.


<!-- Sent from Reviewable.io -->

2023-11-30 00:14 UTC, mkow requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @dimakuv, and @kailun-qin)

___
*[`pal/src/host/linux-sgx/pal_exception.c` line 267 at r6](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkSU9MfBuOp4UfxbpDJ:-NkSU9MfBuOp4UfxbpDK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ba2e22a00359557412034bc88fd5bd63af7eaa2e/pal/src/host/linux-sgx/pal_exception.c#L267)):*
> ```C
>      * h |                             |     |     |     |     |   (exceptions    | (malicious |
>      * r | PAL_EVENT_ARITHMETIC_ERROR  | no  | yes | no  | no  |    unsupported   |  host      |
>      * o |                             |     |     |     |     |    by Gramine)   |  injects   |
> ```





_Suggestion:_
```C
injected
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 276 at r6](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkSUCLMDrMl7sYGQFiD:-NkSUCLMDrMl7sYGQFiE:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/ba2e22a00359557412034bc88fd5bd63af7eaa2e/pal/src/host/linux-sgx/pal_exception.c#L276)):*
> ```C
>      * a | PAL_EVENT_QUIT              |                                          |    yes     |
>      * s |                             |          no, except #PF case*            |            |
>      * y +-----------------------------+  (malicious host ignores HW exception)   +------------+
> ```





_Suggestion:_
```C
ignored
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 330 at r6](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkSY9z38rfwfA31hiTj:-NkSY9z38rfwfA31hiTk:b6h2bre) ([raw file](https://github.com/gramineproject/gramine/blob/ba2e22a00359557412034bc88fd5bd63af7eaa2e/pal/src/host/linux-sgx/pal_exception.c#L330)):*
> note that `event_num` is already set

This is now stale.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 333 at r6](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkSYPMi8X093g_MwOwM:-NkSYPMi8X093g_MwOwN:bly1g8v) ([raw file](https://github.com/gramineproject/gramine/blob/ba2e22a00359557412034bc88fd5bd63af7eaa2e/pal/src/host/linux-sgx/pal_exception.c#L333)):*
> ```C
>                      * following we handle this external event and ignore the #PF info.
>                      *
>                      * Note that there is a possibility of DoS: if the host modified a real memory
> ```

I'd reverse the logic in this comment - we (and SGX) don't care about DoSes, so, a warning about potential DoS doesn't really make sense. What you wanted to actually say here (I think) is that modifying #PF into something else can _at most_ DoS the enclave, thus it's benign.
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 368 at r6](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkSZE9a77F8wh9tZsD8:-NkSZE9a77F8wh9tZsD9:bo7basp) ([raw file](https://github.com/gramineproject/gramine/blob/ba2e22a00359557412034bc88fd5bd63af7eaa2e/pal/src/host/linux-sgx/pal_exception.c#L368)):*
> ```C
>                           exception_name ? : "[unknown]");
>                 _PalProcessExit(1);
>                 /* NOTREACHED */
> ```

While we're here: we usually write `/* UNREACHABLE */`, it's more proper grammatically.


<!-- Sent from Reviewable.io -->

2023-11-30 09:29 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)



<!-- Sent from Reviewable.io -->

2023-11-30 11:46 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-30 11:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1570#-NkV3yNzDzQzJ7uTU5rw:-NkV3yNzDzQzJ7uTU5rx:b-z9pkhn) (no related file):*
I'm putting a blocking comment to wait for the validation run results from @anjalirai-intel (I asked privately to trigger a run on internal CI).

___


<!-- Sent from Reviewable.io -->

2023-12-01 09:10 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1570)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-01 10:38 UTC, merged