[PAL/Linux-SGX] Remove redundant `_PalHandleExternalEvent()`
gramineproject/gramine pull request #1571
Opened 2023-09-26 09:57 UTC by dimakuv

## Description of the changes 

The `_PalExceptionHandler()` function is a superset of the removed func.

## How to test this PR? 

CI is enough. No functional changes, just removing dead code.

2023-09-26 09:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfFv-U-1JFl01jNWgnl:-NfFv-U-1JFl01jNWgnm:b-ttbde) (no related file):*
Builds on top of https://github.com/gramineproject/gramine/pull/1570. Requires that PR to be merged first.

___
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 355 at r1](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfFv3Za7pOHBYL9o9XM:-NfFv3Za7pOHBYL9o9XN:b-ruadnp) ([raw file](https://github.com/gramineproject/gramine/blob/75fd6f9e53de6f9969c1139f676a62d8cea4e2ed/pal/src/host/linux-sgx/pal_exception.c#L355)):*
> ```C
> /* TODO: remove this function (SGX signal handling needs to be revisited)
>  * actually what is the point of this function?
>  * Tracked in https://github.com/gramineproject/gramine/issues/84. */
> ```

FYI: Borys left the TODO comment with a link to https://github.com/gramineproject/gramine/issues/84, but that GitHub issue doesn't have anything about this particular function. So I didn't change anything in that issue.


<!-- Sent from Reviewable.io -->

2023-09-26 10:26 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 758 at r1](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfG-dPy6BzTf07gSgsh:-NfG-dPy6BzTf07gSgsi:b-cmaoly) ([raw file](https://github.com/gramineproject/gramine/blob/921aeb513cb60f1b39b6252a04b2c850473e91b7/pal/src/host/linux-sgx/enclave_entry.S#L758)):*
> ```
> 
> 2:
>     # there was some event, call _PalExceptionHandler(0, event, uc, xregs_state, NULL)
> ```

_PalExceptionHandler(/*trusted_exit_info_=*/0, event, uc, xregs_state, /*exinfo=*/NULL)



_Code quote:_
```
_PalExceptionHandler(0, event, uc, xregs_state, NULL)
```
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 773 at r1](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfG0Vuk-dCVY6x6LiTh:-NfG0Vul1defRmTUA_un:b5ikxi6) ([raw file](https://github.com/gramineproject/gramine/blob/921aeb513cb60f1b39b6252a04b2c850473e91b7/pal/src/host/linux-sgx/enclave_entry.S#L773)):*
> ```
>     movq %rsp, %rdx                         # SGX context        (3rd arg)
>     leaq SGX_CPU_CONTEXT_SIZE(%rsp), %rcx   # xregs_state        (4th arg)
>     movq $0,   %r8                          # SGX EXINFO pointer (5th arg), not used
> ```

pointer to EXINFO



_Code quote:_
```
SGX EXINFO pointer
```


<!-- Sent from Reviewable.io -->

2023-09-26 11:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 758 at r1](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfG-dPy6BzTf07gSgsh:-NfGBFfJ1P2VqCgfrKKu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/921aeb513cb60f1b39b6252a04b2c850473e91b7/pal/src/host/linux-sgx/enclave_entry.S#L758)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

_PalExceptionHandler(/*trusted_exit_info_=*/0, event, uc, xregs_state, /*exinfo=*/NULL)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 773 at r1](https://reviewable.io/reviews/gramineproject/gramine/1571#-NfG0Vuk-dCVY6x6LiTh:-NfGBKlg9lP5TJNwIYQ0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/921aeb513cb60f1b39b6252a04b2c850473e91b7/pal/src/host/linux-sgx/enclave_entry.S#L773)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

pointer to EXINFO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 00:46 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-28 22:59 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 270 at r2](https://reviewable.io/reviews/gramineproject/gramine/1571#-NkN80s05z-OA-ZTrrsa:-NkN80s05z-OA-ZTrrsb:b-gpeprc) ([raw file](https://github.com/gramineproject/gramine/blob/0aee8a477033f5b54977af4d8bc2d4e16a12f13c/pal/src/host/linux-sgx/enclave_entry.S#L270)):*
> ```
>     # .Lcssa0_ocall_return_after_stack_restore. In other words, the stage-1 handler jumps to the
>     # regular returning-from-OCALL flow (CSSA=0) with RSI=<external event> which forces that flow
>     # to call the _PalExceptionHandler() before proceeding with normal enclave code.
> ```

it's a proper name



_Suggestion:_
```
_PalExceptionHandler()
```


<!-- Sent from Reviewable.io -->

2023-11-29 08:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: 2 of 3 files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/enclave_entry.S` line 270 at r2](https://reviewable.io/reviews/gramineproject/gramine/1571#-NkN80s05z-OA-ZTrrsa:-NkP8pSs-hV2MItaW97y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0aee8a477033f5b54977af4d8bc2d4e16a12f13c/pal/src/host/linux-sgx/enclave_entry.S#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

it's a proper name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-29 10:27 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-29 12:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-01 12:11 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-01 13:22 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1571)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-01 13:58 UTC, merged