[LibOS,PAL] Rename `PalObjectClose()` to `PalObjectDestroy()`
gramineproject/gramine pull request #1572
Opened 2023-09-26 12:55 UTC by dimakuv

## Description of the changes 

Previous name didn't make it clear that this PAL API not only closes the associated host resources, but also destroys/frees the PAL handle object itself. Also, this function and all its callbacks are of type `void` now and never return a value (as it's useless anyway).

This PR was a request from @mkow , see #827.

## How to test this PR? 

CI is enough, no functional changes.

2023-09-26 13:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: 0 of 53 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/include/pal_internal.h` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfGZhT15MBuOIohrW09:-NfGZhT15MBuOIohrW0A:b-zyhtm) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/include/pal_internal.h#L52)):*
> while 'delete' actually destroy the stream, such as deleting a file or shutting down a socket

:))
___
*[`pal/src/pal_object.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfG_0X64OOix6LR0NAm:-NfG_0X64OOix6LR0NAn:b1dtmx7) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/src/pal_object.c#L26)):*
>      *   _PalObjectClose will free the object, unless the handle has a 'close' operation, and the
>      *   operation returns a non-zero value (e.g., 1 for skipping free() or -ERRNO).

:)))
___
*[`pal/src/pal_object.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfG_DFa5AzFcXzC-7qW:-NfG_DFa5AzFcXzC-7qX:bwnzzud) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/src/pal_object.c#L38)):*
> ```C
>  * never fail (from a quick look at the code, seems like it cannot return errors in practice) or
>  * make this return an `int` and handle errors in all call sites (hard to do; in most places we
>  * cannot handle them in a meaningful way).
> ```

Borys left this comment two years ago. We finally fixed it.


<!-- Sent from Reviewable.io -->

2023-09-26 22:47 UTC, mkow requested changes
> Reviewed 52 of 53 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/include/pal_internal.h` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfGZhT15MBuOIohrW09:-NfIZnWH1mUhg6sJIXJU:bc2ws3h) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/include/pal_internal.h#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> while 'delete' actually destroy the stream, such as deleting a file or shutting down a socket

:))
</blockquote></details>

:face_with_head_bandage: 
___
*[`pal/src/pal_main.c` line 358 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfI_x4S-OMVDM5sKYxi:-NfI_x4S-OMVDM5sKYxj:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/pal_main.c#L358)):*
> ```C
> 
> out_fail:
>     (void)_PalObjectDestroy(hdl);
> ```





_Suggestion:_
```C
_PalObjectDestroy(hdl);
```
___
*[`pal/src/pal_object.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfG_0X64OOix6LR0NAm:-NfIaEVG2OMH3gAlZWGL:b32vk7) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/src/pal_object.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>      *   _PalObjectClose will free the object, unless the handle has a 'close' operation, and the
>      *   operation returns a non-zero value (e.g., 1 for skipping free() or -ERRNO).

:)))
</blockquote></details>

:|
___
*[`pal/src/pal_object.c` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfG_DFa5AzFcXzC-7qW:-NfIaK7i8T3YIZIOJ5rN:b2nigjw) ([raw file](https://github.com/gramineproject/gramine/blob/2ad54dd52426da115261a26244c10110840f9c83/pal/src/pal_object.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys left this comment two years ago. We finally fixed it.
</blockquote></details>

yay
___
*[`pal/src/host/linux/pal_devices.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIb7TO2_N4xDlZdN9y:-NfIb7TO2_N4xDlZdN9z:b5o6jtj) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_devices.c#L124)):*
> ```C
>         int ret = DO_SYSCALL(close, handle->dev.fd);
>         if (ret < 0) {
>             log_error("closing dev fd failed: %s", unix_strerror(ret));
> ```

Please also print the FD (and also "fd" -> "host fd").
ditto for all these prints
___
*[`pal/src/host/linux/pal_files.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIbwklBYwNWAsqmyE1:-NfIbwklBYwNWAsqmyE2:b-atlw3u) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L120)):*
> ```C
>     assert(handle->hdr.type == PAL_TYPE_FILE);
> 
>     if (handle->file.fd == PAL_IDX_POISON)
> ```

Now you skip `free(handle->file.realpath);` in this case.
___
*[`pal/src/host/linux/pal_files.c` line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIbtNi5uvnHs-SpaKa:-NfIbmQ1DmGcNZIXjOt2:bq57ht7) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L129)):*
> ```C
>     }
> 
>     free(handle->file.realpath);
> ```

Please overwrite with `NULL` afterwards, just to be safe (same as you do with the FD).
___
*[`pal/src/host/linux/pal_files.c` line 392 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIcMHAEV7P_B6f2HP0:-NfIcMHAEV7P_B6f2HP1:b85bhc5) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L392)):*
> ```C
>     assert(handle->hdr.type == PAL_TYPE_DIR);
> 
>     if (handle->dir.fd == PAL_IDX_POISON)
> ```

ditto, why skipping all the other freeing?
___
*[`pal/src/host/linux/pal_files.c` line 406 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIcXe702wp_yO495HB:-NfIcXe702wp_yO495HC:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L406)):*
> ```C
>     }
> 
>     free(handle->dir.realpath);
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_files.c` line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIeMp9EC9oBLB_Sf4e:-NfIeMp9EC9oBLB_Sf4f:bxlxw26) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L225)):*
> ```C
> 
>     if (handle->file.fd == PAL_IDX_POISON)
>         return;
> ```

ditto - why skipping the rest of destruction in the new version?
___
*[`pal/src/host/linux-sgx/pal_files.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIe_hp3phlPKpHHxw3:-NfIe_hp3phlPKpHHxw4:b-560k36) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L238)):*
> ```C
>     }
> 
>     free(handle->file.realpath);
> ```

ditto (overwriting)
___
*[`pal/src/host/linux-sgx/pal_files.c` line 645 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIeVZ44x1v1UOfXVcu:-NfIeVZ44x1v1UOfXVcv:bqoef9a) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L645)):*
> ```C
> 
>     if (handle->dir.fd == PAL_IDX_POISON)
>         return;
> ```

ditto, why skipping the rest?
___
*[`pal/src/host/linux-sgx/pal_files.c` line 658 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIebzl60JBqzgFNkyK:-NfIebzl60JBqzgFNkyL:b-560k36) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L658)):*
> ```C
>     }
> 
>     free(handle->dir.realpath);
> ```

ditto (overwriting)


<!-- Sent from Reviewable.io -->

2023-09-27 02:57 UTC, kailun-qin reviewed
> Reviewed 52 of 53 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-09-27 09:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfKsY2tEPZGmm37LNMR:-NfKsY2tEPZGmm37LNMS:b-ji3wr1) (no related file):*
I thought about this change a bit, and I think I stopped in the middle.

I propose to also rename all `close()` callbacks to `destroy()` callbacks. Because these callbacks do two things:
1. Close all the host-associated resources; almost always it is the host FD.
2. Free PAL handle-associated sub-resources, like filename strings.

So because of the item 2, we can consider the `close()` callbacks as really object-destroy callbacks (they destroy sub-objects). Moreover, these `close()` callbacks are called **only from** the `PalObjectDestroy()` function.

So my proposal is to:
- rename `close()` to `destroy()`; this will make clear that after calling this, the object cannot be accessed anymore
- move `free(handle)` from `PalObjectDestroy()` to each of the `destroy()` callbacks; this will make clear for future readers/reviewers where the PAL handle is destroyed, unlike the current split-brain situation where the handle is partially destroyed in the callback and partially in the PalObjectDestroy function.

@kailun-qin  @mkow What do you think about this proposal? Should I do a fixup commit like this?

___


<!-- Sent from Reviewable.io -->

2023-09-27 13:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfKsY2tEPZGmm37LNMR:-NfLofCX4AbcafBmocgj:b19fwqr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought about this change a bit, and I think I stopped in the middle.

I propose to also rename all `close()` callbacks to `destroy()` callbacks. Because these callbacks do two things:
1. Close all the host-associated resources; almost always it is the host FD.
2. Free PAL handle-associated sub-resources, like filename strings.

So because of the item 2, we can consider the `close()` callbacks as really object-destroy callbacks (they destroy sub-objects). Moreover, these `close()` callbacks are called **only from** the `PalObjectDestroy()` function.

So my proposal is to:
- rename `close()` to `destroy()`; this will make clear that after calling this, the object cannot be accessed anymore
- move `free(handle)` from `PalObjectDestroy()` to each of the `destroy()` callbacks; this will make clear for future readers/reviewers where the PAL handle is destroyed, unlike the current split-brain situation where the handle is partially destroyed in the callback and partially in the PalObjectDestroy function.

@kailun-qin  @mkow What do you think about this proposal? Should I do a fixup commit like this?
</blockquote></details>

An additional benefit of the proposed change is that `PAL_IDX_POISON` macro and all relevant checks will be removed -- a nice clean-up side effect.

___


<!-- Sent from Reviewable.io -->

2023-09-27 13:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: 30 of 55 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfKsY2tEPZGmm37LNMR:-NfLsJHaD3yLfHvySIU4:b-j931h9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

An additional benefit of the proposed change is that `PAL_IDX_POISON` macro and all relevant checks will be removed -- a nice clean-up side effect.
</blockquote></details>

Ok, I went ahead with my proposal: please see the fixup commit (2df1ec4). I think it's much cleaner now.

___


<!-- Sent from Reviewable.io -->

2023-09-27 13:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: 30 of 55 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/pal_main.c` line 358 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfI_x4S-OMVDM5sKYxi:-NfLtvkw1OJxRLOLi_Ks:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/pal_main.c#L358)):*
> ```C
> 
> out_fail:
>     (void)_PalObjectDestroy(hdl);
> ```

Done.
___
*[`pal/src/host/linux/pal_devices.c` line 124 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIb7TO2_N4xDlZdN9y:-NfLu-KABd_y4a0FDQY2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_devices.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also print the FD (and also "fd" -> "host fd").
ditto for all these prints
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIbwklBYwNWAsqmyE1:-NfLu4gMEnB4X07x8iVW:b-8q18hm) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now you skip `free(handle->file.realpath);` in this case.
</blockquote></details>

Done, not relevant anymore
___
*[`pal/src/host/linux/pal_files.c` line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIbtNi5uvnHs-SpaKa:-NfLu8Bb7YZRMi8MsMwP:b-lpf3sj) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please overwrite with `NULL` afterwards, just to be safe (same as you do with the FD).
</blockquote></details>

Done, not relevant anymore, because we free the whole object
___
*[`pal/src/host/linux/pal_files.c` line 392 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIcMHAEV7P_B6f2HP0:-NfLuCSY6KmbANf8q17R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L392)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto, why skipping all the other freeing?
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_files.c` line 406 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIcXe702wp_yO495HB:-NfLuECTBkJWlz8W9oJ6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux/pal_files.c#L406)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 225 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIeMp9EC9oBLB_Sf4e:-NfLuP2a7bX46kXi6Gbc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - why skipping the rest of destruction in the new version?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIe_hp3phlPKpHHxw3:-NfLuQGo7iyRTUsUcCAc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (overwriting)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 645 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIeVZ44x1v1UOfXVcu:-NfLuR1YCdhWGUVAX8XF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L645)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto, why skipping the rest?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_files.c` line 658 at r2](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfIebzl60JBqzgFNkyK:-NfLuRtJ8LIlnN5XXLAd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/808851aea77f4b0c3e369f528610cb5636f98392/pal/src/host/linux-sgx/pal_files.c#L658)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (overwriting)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 16:25 UTC, mkow submitted a review, later dismissed
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfKsY2tEPZGmm37LNMR:-NfLsGYL-aHbGLT5jlZc:b-ba7jdc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

An additional benefit of the proposed change is that `PAL_IDX_POISON` macro and all relevant checks will be removed -- a nice clean-up side effect.
</blockquote></details>

Sounds good to me!

___


<!-- Sent from Reviewable.io -->

2023-09-28 00:43 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 23 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1572#-NfKsY2tEPZGmm37LNMR:-NfODLhTD_6ZTmY2Qho5:b-85i63v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds good to me!
</blockquote></details>

LGTM.

___


<!-- Sent from Reviewable.io -->

2023-09-28 11:37 UTC, mkow approved these changes
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-09-28 13:42 UTC, kailun-qin approved these changes
> Reviewed 2 of 25 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1572)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-28 14:02 UTC, merged