[PAL] Enforce that device files are in the list of `sgx.allowed_files`
gramineproject/gramine pull request #1577
Opened 2023-09-29 08:04 UTC by dimakuv

## Description of the changes 

Previously, device files (like `dev:/dev/zero`) where enabled in Gramine via the FS-mounts syntax in manifest:

    fs.mounts = [ {path = "/dev/zero", uri = "dev:/dev/zero"} ]

However, devices are pass-through; Gramine doesn't add any protections to the app-to-device communication. Therefore, a careless usage of `write(device_fd)` may lead to data leaks and `read(device_fd)` may lead to injection attacks.

To make it more pronounced that Gramine doesn't provide any security guarantees to the device communication, this commit forces to specify devices as `sgx.allowed_files`. This is similar to how Gramine forces to specify device IOCTLs as `sys.allowed_ioctls`. **This is a breaking change!**

At the PAL level, this requires normalizing the device pathname and finding it in the list of allowed files. The device pathname must also be checkpointed and restored in the child processes. Finally, this commit also introduces previously-missing device operations like `unlink` (delete) and `ftruncate` (setlegth).

This was extracted from #827. I based the code in this PR on the code written by @llly, so he is a co-author here.

## How to test this PR? 

LibOS tests were modified.

One can manually test different failures in Gramine, using the `device_passthrough` LibOS regression test. Here's the diff for manual tests:
```diff
diff --git a/libos/test/regression/device_passthrough.manifest.template b/libos/test/regression/device_passthrough.manifest.template
@@ -1,5 +1,6 @@
 loader.entrypoint = "file:{{ gramine.libos }}"
 libos.entrypoint = "{{ entrypoint }}"
+loader.log_level = "warning"

 loader.env.LD_LIBRARY_PATH = "/lib"

@@ -17,3 +18,6 @@ sgx.trusted_files = [
   "file:{{ gramine.runtimedir(libc) }}/",
   "file:{{ binary_dir }}/{{ entrypoint }}",
 ]
+sgx.allowed_files = [ "dev:/dev/zero" ]
+# sgx.file_check_policy = "allow_all_but_log"
```

- Log level set to `warning` just to see the failure messages in Gramine.
- Comment out `sgx.allowed_files` to see how Gramine refuses to open the device (+ a warning).
- Uncomment `sgx.file_check_policy` to see how Gramine allows to open the device but prints a warning.

2023-09-29 08:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: 0 of 14 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux/pal_streams.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfUy_XS7srE2Dnrq2qE:-NfUy_XT53TKRcon94hj:b-32m0fd) ([raw file](https://github.com/gramineproject/gramine/blob/a60dcf78e9b5d9c4f1d315c63dd087592668b8e3/pal/src/host/linux/pal_streams.c#L47)):*
> ```C
>      * no handle type has more than one such field, and some have none */
>     switch (handle->hdr.type) {
>         case PAL_TYPE_FILE:
> ```

FYI: I moved `PAL_TYPE_FILE` handling closer to `DEV` and `DIR`, as they are very similar and should be grouped together.
___
*[`pal/src/host/linux/pal_streams.c` line 105 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfUyg4P-g8NVpyWBK-U:-NfUyg4P-g8NVpyWBK-V:b-32m0fd) ([raw file](https://github.com/gramineproject/gramine/blob/a60dcf78e9b5d9c4f1d315c63dd087592668b8e3/pal/src/host/linux/pal_streams.c#L105)):*
> ```C
>     /* update handle fields to point to correct contents */
>     switch (hdl->hdr.type) {
>         case PAL_TYPE_FILE: {
> ```

FYI: I moved `PAL_TYPE_FILE` handling closer to `DEV` and `DIR`, as they are very similar and should be grouped together.


<!-- Sent from Reviewable.io -->

2023-09-29 08:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: 0 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfUz8Pv6OZtgCkAq1ji:-NfUz8Pv6OZtgCkAq1jj:bif15fu) (no related file):*
@llly Please review this PR as you wrote very similar changes in your #827.

___


<!-- Sent from Reviewable.io -->

2023-09-30 15:28 UTC, mkow requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaN8n29N8y6JdGkKpx):*
Pleeease...



_Suggestion:_
```
Previously, device files (like `dev:/dev/zero`) were mounted in Gramine
```
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaNkVa5Gtc0Sblu5Qa):*
These are not injection attacks, rather just generic bugs in parsing logic or trusting untrusted data. 



_Code quote:_
```
to injection attacks.
```
___
*[`pal/src/host/linux/pal_devices.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaSb8i5qBaxYGx8kTf:-NfaSb8i5qBaxYGx8kTg:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_devices.c#L58)):*
> ```C
>     size_t normpath_size = strlen(uri) + 1;
>     normpath = malloc(normpath_size);
>     if (!normpath){
> ```





_Suggestion:_
```C
if (!normpath) {
```
___
*[`pal/src/host/linux/pal_streams.c` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaVLjP1vsn8O1oZASH:-NfaVLjP1vsn8O1oZASI:b2irtx3) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_streams.c#L96)):*
> ```C
> }
> 
> static char* malloc_and_copy(size_t size, const char* src) {
> ```

Maybe move to `util.c` and rename to `alloc_and_copy()`?
___
*[`pal/src/host/linux/pal_streams.c` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaVuiqCbFJjn0TJL24:-NfaVuiqCbFJjn0TJL25:b-mddfwm) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_streams.c#L96)):*
> ```C
> }
> 
> static char* malloc_and_copy(size_t size, const char* src) {
> ```

Usually you pass a pointer to a buffer and then the size.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 408 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfabzUi-4YToaXwjndb:-NfabzUi-4YToaXwjndc:bnelxov) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/enclave_framework.c#L408)):*
> ```C
> static int g_file_check_policy = FILE_CHECK_POLICY_STRICT;
> 
> static void path_from_uri(const char* uri, size_t uri_len, const char** out_path,
> ```

Please add at least a warning comment that this doesn't allocate the result - which is a deviation from the usual convention in such functions.
Or maybe instead rename to `find_path_in_uri()`?
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfadJJV-NxPmsv0tGBg:-NfadJJV-NxPmsv0tGBh:bfqvns2) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/enclave_framework.c#L416)):*
> ```C
>     }
> 
>     assert(strstartswith(uri, URI_PREFIX_DEV));
> ```

Why not make it work with any URI type? Would take roughly the same amount of code.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 175 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaaqALD-UjfyvxGo7l:-NfaaqALD-UjfyvxGo7m:b-j9qnw4) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/pal_streams.c#L175)):*
> ```C
>                 return -PAL_ERROR_NOMEM;
>             }
>             hdl->file.chunk_hashes = hdl->file.umem = NULL;
> ```

I'm not a fan of these multi-assignments, but won't block.


<!-- Sent from Reviewable.io -->

2023-10-02 07:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: 8 of 15 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaN8n29N8y6JdGkKpx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Pleeease...
</blockquote></details>

Will fix during final rebase
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaNkVa5Gtc0Sblu5Qa):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These are not injection attacks, rather just generic bugs in parsing logic or trusting untrusted data.
</blockquote></details>

Will fix during final rebase, to `... may lead to bugs in parsing logic or trusting untrusted data`
___
*[`pal/src/host/linux/pal_devices.c` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaSb8i5qBaxYGx8kTf:-NfjEh4dDQ5KjltwkMeW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_devices.c#L58)):*
> ```C
>     size_t normpath_size = strlen(uri) + 1;
>     normpath = malloc(normpath_size);
>     if (!normpath){
> ```

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaVLjP1vsn8O1oZASH:-NfjFRac3fETE7QmwDZB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_streams.c#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe move to `util.c` and rename to `alloc_and_copy()`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_streams.c` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaVuiqCbFJjn0TJL24:-NfjFS2n3c-EEIwOHM_Y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux/pal_streams.c#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Usually you pass a pointer to a buffer and then the size.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 408 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfabzUi-4YToaXwjndb:-NfjGCsTE1rYkOHuEXtX:b-ydonir) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/enclave_framework.c#L408)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add at least a warning comment that this doesn't allocate the result - which is a deviation from the usual convention in such functions.
Or maybe instead rename to `find_path_in_uri()`?
</blockquote></details>

Done. Good idea.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfadJJV-NxPmsv0tGBg:-NfjGYJW11CGmTK9ipqp:b-jjqvqb) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/enclave_framework.c#L416)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not make it work with any URI type? Would take roughly the same amount of code.
</blockquote></details>

Could it make it a separate PR? In this particular file, this particular function is used only to extract the path from the trusted/allowed files -- which can only be `file:` or `dev:`.

I agree that this function may be made generic, but then I would also prefer to use it in many other places in PAL (we have similar logic in many places).
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 175 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaaqALD-UjfyvxGo7l:-NfjEs8NBvavBw4nTXhz:b-ro04j3) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/pal_streams.c#L175)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not a fan of these multi-assignments, but won't block.
</blockquote></details>

I did it for two reasons:
1. To be uniform with the below `DIR` case which has: `hdl->dir.buf = hdl->dir.ptr = hdl->dir.end = NULL;`
2. And because in this particular place, it looks more readable -- nullify all pointers while serializing the object, not to have dangling pointers when transmitting this serialized object.

So I would keep like this.


<!-- Sent from Reviewable.io -->

2023-10-02 13:57 UTC, kailun-qin approved these changes
> Reviewed 14 of 14 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfkZkNZ7DRHLg3OxeRH):*
-. "setlength" (can be fixed during rebase)



_Code quote:_
```
setlegth
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 416 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfadJJV-NxPmsv0tGBg:-Nfk_ajs47MFI8li4YSJ:ba2d1y1) ([raw file](https://github.com/gramineproject/gramine/blob/38b6abbbced241d259100268d304f1a8ceddd761/pal/src/host/linux-sgx/enclave_framework.c#L416)):*
> Could it make it a separate PR?

Yeah, I'm fine w/ a separate PR.


<!-- Sent from Reviewable.io -->

2023-10-05 08:18 UTC, mkow requested changes
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaNkVa5Gtc0Sblu5Qa):*
This doesn't "lead to bugs in the parser", the bugs are already there, it just exposes them. Rather:

> [...] may expose app's vulnerable parsing logic to the attacker or lead to trusting untrusted data.
___
*[`common/include/api.h` line 278 at r2](https://reviewable.io/reviews/gramineproject/gramine/1577#-Nfyu2vgD-zOT1V683GA:-Nfyu2vgD-zOT1V683GB:b-prg2op) ([raw file](https://github.com/gramineproject/gramine/blob/a6221bb9854e0d75af1e3fa1fddcd01b0fa57424/common/include/api.h#L278)):*
> ```objc
> char* alloc_concat3(const char* a, size_t a_len, const char* b, size_t b_len,
>                     const char* c, size_t c_len);
> char* alloc_and_copy(const char* src, size_t size);
> ```

Not `void*`?


<!-- Sent from Reviewable.io -->

2023-10-07 02:36 UTC, llly reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577#-:-Ng6z_jFAImkv_Nn7Q1e:bnfp4nl)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-10-09 06:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: 13 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaNkVa5Gtc0Sblu5Qa):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't "lead to bugs in the parser", the bugs are already there, it just exposes them. Rather:

> [...] may expose app's vulnerable parsing logic to the attacker or lead to trusting untrusted data.
</blockquote></details>

Will do during final rebase.
___
*[`common/include/api.h` line 278 at r2](https://reviewable.io/reviews/gramineproject/gramine/1577#-Nfyu2vgD-zOT1V683GA:-NgI9-lP96Dm1jDNqYMV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6221bb9854e0d75af1e3fa1fddcd01b0fa57424/common/include/api.h#L278)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `void*`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 07:43 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-10-11 20:45 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-10-12 15:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 3 unresolved discussions (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaN8n29N8y6JdGkKpx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will fix during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfaNkVa5Gtc0Sblu5Qa):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase.
</blockquote></details>

Done.
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/1577#-NfkZkNZ7DRHLg3OxeRH):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do (typo, missing `n`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 15:53 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-10-12 23:01 UTC, kailun-qin approved these changes
> Reviewed 8 of 14 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1577)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-13 07:21 UTC, merged