Add Scaffolding For Gramine documentation
gramineproject/gramine pull request #1578
Opened 2023-09-29 08:46 UTC by oshogbo

## Description of the changes 

Add documentation for a new method of "graminizing" apps.

2023-09-29 09:15 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
Prefix must be `[Docs]`. Can be fixed during final rebase.

`For` -> `to`
___
*[`Documentation/index.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVB_SY0VSEyUQSa3ux:-NfVB_SY0VSEyUQSa3uy:bfgaz89) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L34)):*
> ```reStructuredText
> In this section, we describe how you can protect your Docker container using
> Gramine Shielded Containers (GSC) and how you can use ready-made SGX images for
> popular open source projects.
> ```

You need to add Scaffolding mentioning also here.
___
*[`Documentation/index.rst` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBg7t913fllwbbjl3:-NfVBg7t913fllwbbjl4:bkfxj2y) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L47)):*
> ```reStructuredText
> - **Scaffolding For Gramine**
> 
>   Unlock the full potential of your application with
> ```

This doesn't look like 80-char-per-line formatted?
___
*[`Documentation/index.rst` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVC-zLBIvW4iuOt6ZD:-NfVC-zLBIvW4iuOt6ZE:bde75ci) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L47)):*
> ```reStructuredText
> - **Scaffolding For Gramine**
> 
>   Unlock the full potential of your application with
> ```

Can we reword this marketing phrase "Unlock the full potential ..."?
___
*[`Documentation/index.rst` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBqXA3pX2Ff7xqRYr:-NfVBqXA3pX2Ff7xqRYs:bd447w1) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L54)):*
> ```reStructuredText
>   against malicious hosts.
> 
>   Setting itself apart from alternative solutions, ScAG doesn’t confine its
> ```

So is it `SCAG` or `ScAG`? Please be uniform.
___
*[`Documentation/index.rst` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVC9T225vxSf3oUlni:-NfVC9T225vxSf3oUlnj:b-14s6io) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L54)):*
> ```reStructuredText
>   against malicious hosts.
> 
>   Setting itself apart from alternative solutions, ScAG doesn’t confine its
> ```

Hm, maybe explain a difference from the GSC tool in 1-2 sentences here? Because we mention GSC tool above, so it would make sense to say to users "But GSC cannot do this and this and this, whereas Scaffolding can, though at a price of X".
___
*[`Documentation/index.rst` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCK_A7DyFssmqvwn0:-NfVCK_A7DyFssmqvwn1:bfwr995) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L55)):*
> ```reStructuredText
> 
>   Setting itself apart from alternative solutions, ScAG doesn’t confine its
>   operations to the Docker level—it delves deeper, functioning at
> ```

I have no idea what this sentence means :)

What do you mean by the "framework level"? I think you mean existing popular frameworks/runtime like the Python runtime, JVM, .NET, and so on? Then please be more specific.
___
*[`Documentation/index.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBzYy7XJF5_whRgiB:-NfVBzYy7XJF5_whRgiC:bqf4gwe) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L58)):*
> ```reStructuredText
>   the framework level. It offers seamless support for a variety of frameworks,
>   including but not limited to Flask and Express.js. For a more in-depth
>   exploration, visit :doc:`scag-installation`, or contribute to the
> ```

`visit` -> `see`
___
*[`Documentation/index.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCnYf3cbDP9Wpxo_f:-NfVCnYf3cbDP9Wpxo_g:b-65bspc) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L58)):*
> ```reStructuredText
>   the framework level. It offers seamless support for a variety of frameworks,
>   including but not limited to Flask and Express.js. For a more in-depth
>   exploration, visit :doc:`scag-installation`, or contribute to the
> ```

You're supposed to add `scag-installation` to https://github.com/gramineproject/gramine/blob/a60dcf78e9b5d9c4f1d315c63dd087592668b8e3/Documentation/index.rst#indices-and-tables
___
*[`Documentation/scag-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCxKpCD2Zo7mJ_Zbo:-NfVCxKpCD2Zo7mJ_Zbp:b-hw8ao6) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L4)):*
> ```reStructuredText
> =======================
> 
> The Scaffolding for Gramine (SCAG) tool SCAG meticulously transforms your
> ```

You mention SCAG twice
___
*[`Documentation/scag-installation.rst` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD9Ok57JCED9woOdO:-NfVD9Ok57JCED9woOdP:b-olayv3) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L9)):*
> ```reStructuredText
> Scaffolding project is to expedite the process of safeguarding applications
> against malicious hosts.
> ```

Can you add one paragraph that explains the technical details of SCAG? What exactly does it do, and why it's different (and beneficial) from porting the app yourself manually or using GSC.
___
*[`Documentation/scag-installation.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD0vK3C0eQDnrWPaB:-NfVD0vK3C0eQDnrWPaC:b-2t7bln) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L11)):*
> ```reStructuredText
> 
> To speed up the process, SCAG offers a single command - ``scag-quickstart``.
> This tool will also guides user interactively through the entire process of "graminizing"
> ```

Remove `will`
___
*[`Documentation/scag-installation.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD3mnCCuesgbx6d4S:-NfVD3mnCCuesgbx6d4T:b-5zke8k) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L14)):*
> ```reStructuredText
> application, from setting up the project to building it, and finally running it.
> For more advanced usage of the project, users are encouraged to refer to the documentation.
> ```

Please remove one empty line


<!-- Sent from Reviewable.io -->

2023-09-29 09:51 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 0 of 2 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Prefix must be `[Docs]`. Can be fixed during final rebase.

`For` -> `to`
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVB_SY0VSEyUQSa3ux:-NfVEHqmBWYsdBhZ4anM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to add Scaffolding mentioning also here.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBg7t913fllwbbjl3:-NfVEId4CUMX5d4MOBGT:bnxvwbd) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't look like 80-char-per-line formatted?
</blockquote></details>

Yea, but "article and name" I wanted to have in one line, but up to you.
___
*[`Documentation/index.rst` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVC-zLBIvW4iuOt6ZD:-NfVENooB0VPVmWQhPGH:b-lgthr) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we reword this marketing phrase "Unlock the full potential ..."?
</blockquote></details>

I was so proud of it :(
Done.
___
*[`Documentation/index.rst` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBqXA3pX2Ff7xqRYr:-NfVEX-E2FHU6BOCcIuX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So is it `SCAG` or `ScAG`? Please be uniform.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVC9T225vxSf3oUlni:-NfVEZ3P1IHvWAF6XnQt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, maybe explain a difference from the GSC tool in 1-2 sentences here? Because we mention GSC tool above, so it would make sense to say to users "But GSC cannot do this and this and this, whereas Scaffolding can, though at a price of X".
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCK_A7DyFssmqvwn0:-NfVFmJi2pjiMperxdkh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have no idea what this sentence means :)

What do you mean by the "framework level"? I think you mean existing popular frameworks/runtime like the Python runtime, JVM, .NET, and so on? Then please be more specific.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBzYy7XJF5_whRgiB:-NfVEdg40CO7QERArSa6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`visit` -> `see`
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCnYf3cbDP9Wpxo_f:-NfVEo8YDKtMc9NtrnkQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're supposed to add `scag-installation` to https://github.com/gramineproject/gramine/blob/a60dcf78e9b5d9c4f1d315c63dd087592668b8e3/Documentation/index.rst#indices-and-tables
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVCxKpCD2Zo7mJ_Zbo:-NfVFyMd8DBDH8mlvOfV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You mention SCAG twice
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD9Ok57JCED9woOdO:-NfVHyXZE0vN2OsuGbaA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add one paragraph that explains the technical details of SCAG? What exactly does it do, and why it's different (and beneficial) from porting the app yourself manually or using GSC.
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD0vK3C0eQDnrWPaB:-NfVF-iE8WpQSVL2Debx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `will`
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVD3mnCCuesgbx6d4S:-NfVF-H55B6qhnvFp9TA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/scag-installation.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove one empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-29 10:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, not what I meant. Please try again :)

`[Docs] Add Scaffolding to Gramine documentation`
___
*[`Documentation/index.rst` line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVC9T225vxSf3oUlni:-NfVPjkuBPfRzeB9oSBd:b-ko8joe) ([raw file](https://github.com/gramineproject/gramine/blob/b7662eedd20936124fbec624b0ed69a20d86b30b/Documentation/index.rst#L54)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, this description makes more sense to me!
___
*[`Documentation/index.rst` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPQYB2tFFRtZUrEFg:-NfVPQYB2tFFRtZUrEFh:bas5n0t) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L33)):*
> ```reStructuredText
> 
> In this section, we describe how you can protect your Docker container using
> Gramine Shielded Containers (GSC), Scaffolding For Gramine (SCAG), and how you
> ```

Why `For` with capital letter?
___
*[`Documentation/index.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPUq76Y_NfVJSaloz:-NfVPUq76Y_NfVJSalp-:bas5n0t) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L45)):*
> ```reStructuredText
>   article for more information.
> 
> - **Scaffolding For Gramine**
> ```

Why `For` with capital letter?
___
*[`Documentation/index.rst` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPXg59WHodlf9vvQc:-NfVPXg59WHodlf9vvQd:b-2tqa2m) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L47)):*
> ```reStructuredText
> - **Scaffolding For Gramine**
> 
>   The Scaffolding for Gramine (SCAG) tool is a diffrent approach for "graminizing"
> ```

`different`
___
*[`Documentation/scag-installation.rst` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPsQZ7VTGCipR6TKt:-NfVPsQZ7VTGCipR6TKu:bsbgrye) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L12)):*
> ```reStructuredText
> Setting itself apart from alternative solutions (like GSC), SCAG doesn't
> transform a Docker image, instead it generates a whole Docker image from
> the given projects. During the build process the required Dockerfile,
> ```

Maybe also add a sentence `A list of currently supported projects/frameworks can be found at <Github page>`?
___
*[`Documentation/scag-installation.rst` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVQ5045IaQKPB2sCXV:-NfVQ50585BRyllZNtOL:b-630hwm) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L18)):*
> ```reStructuredText
> To speed up the process, SCAG offers a single command - ``scag-quickstart``.
> This tool also guides user interactively through the entire process of
> "graminizing" application, from setting up the project to building it, and
> ```

`the application`
___
*[`Documentation/scag-installation.rst` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVQBM9Efcf5vg3BYf4:-NfVQBM9Efcf5vg3BYf5:blzykpm) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L23)):*
> ```reStructuredText
> 
> All web-based frameworks, such as Express.js and Flask, are preconfigured
> to operate behind a web server (nginx), with SSL/TLS and the RA-TLS extension.
> ```

This paragraph comes out of the blue. I think what you want to start with is `SCAG wraps the application with additional security measures, such as adding SSL/TLS to overwise plaintext-networking apps.`


<!-- Sent from Reviewable.io -->

2023-09-29 10:32 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, not what I meant. Please try again :)

`[Docs] Add Scaffolding to Gramine documentation`
</blockquote></details>

Yes, I know what you meant, but I think it's a little bit wrong :)

The name of the project is "Scaffolding for Gramine" :) not "Scaffolding".
So "Add Scaffolding for Gramine to documentation", where "Scaffolding for Gramine" is the name of the project.
I think "Gramine's documentation" is obvious as this is "Gramine" project and "documentation" so I didn't want to specify again which documentation it is.

<start joke>
So to be agreeable it should be:
"Add Scaffolding for Gramine to Gramine's documentation"
</end joke>

Maybe I should do:
```
Add `Scaffolding for Gramine` to the documentation
```
or
```
Add "Scaffolding for Gramine" to the documentation
```
To avoid misunderstanding?
___
*[`Documentation/index.rst` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPQYB2tFFRtZUrEFg:-NfVSLXZEHyK7iUtEQx4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `For` with capital letter?
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 45 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPUq76Y_NfVJSaloz:-NfVSM5P12LhFyl32GGh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `For` with capital letter?
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 47 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPXg59WHodlf9vvQc:-NfVSPmx8wW-2J5tvJK3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/index.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`different`
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 12 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVPsQZ7VTGCipR6TKt:-NfVT-ko-h_rlbeKoZ6r:bhg6zh8) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe also add a sentence `A list of currently supported projects/frameworks can be found at <Github page>`?
</blockquote></details>

Done.
Good idea thanks.
___
*[`Documentation/scag-installation.rst` line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVQ5045IaQKPB2sCXV:-NfVSc0bDn41OKO8KcCo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the application`
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 23 at r2](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVQBM9Efcf5vg3BYf4:-NfVTD1uD1uiBEG-xOqD:buu23v3) ([raw file](https://github.com/gramineproject/gramine/blob/6f44be554489598f9c9a9d0a9fe67a9c9be6c278/Documentation/scag-installation.rst#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This paragraph comes out of the blue. I think what you want to start with is `SCAG wraps the application with additional security measures, such as adding SSL/TLS to overwise plaintext-networking apps.`
</blockquote></details>

Thank you, stolen.


<!-- Sent from Reviewable.io -->

2023-09-29 10:34 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes, I know what you meant, but I think it's a little bit wrong :)

The name of the project is "Scaffolding for Gramine" :) not "Scaffolding".
So "Add Scaffolding for Gramine to documentation", where "Scaffolding for Gramine" is the name of the project.
I think "Gramine's documentation" is obvious as this is "Gramine" project and "documentation" so I didn't want to specify again which documentation it is.

<start joke>
So to be agreeable it should be:
"Add Scaffolding for Gramine to Gramine's documentation"
</end joke>

Maybe I should do:
```
Add `Scaffolding for Gramine` to the documentation
```
or
```
Add "Scaffolding for Gramine" to the documentation
```
To avoid misunderstanding?
</blockquote></details>

I'm not sure why reviowable removed my markers. But, this part:
So to be agreeable it should be: "Add Scaffolding for Gramine to Gramine's documentation"
Should be between:
[joke][/joke]


<!-- Sent from Reviewable.io -->

2023-09-29 11:09 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVBSSv094T_R8R1kko):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I'm not sure why reviowable removed my markers. But, this part:
So to be agreeable it should be: "Add Scaffolding for Gramine to Gramine's documentation"
Should be between:
[joke][/joke]
</blockquote></details>

Ah, ok, understood. I'm fine with the current title then.
___
*[`Documentation/scag-installation.rst` line 26 at r3](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVc7Is4m4UCth8cTIF:-NfVc7Is4m4UCth8cTIG:bidb6hx) ([raw file](https://github.com/gramineproject/gramine/blob/039ba3538491459e1270c8a0fe9c17a82072d1d8/Documentation/scag-installation.rst#L26)):*
> ```reStructuredText
> 
> SCAG wraps the application with additional security measures, such as adding
> SSL/TLS to overwise plaintext-networking apps. All web-based frameworks,
> ```

typo: `otherwise` (sorry, just noticed)


<!-- Sent from Reviewable.io -->

2023-09-29 15:47 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/scag-installation.rst` line 26 at r3](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfVc7Is4m4UCth8cTIF:-NfWbhGbAgFugZKnPYFz:bdxmy38) ([raw file](https://github.com/gramineproject/gramine/blob/039ba3538491459e1270c8a0fe9c17a82072d1d8/Documentation/scag-installation.rst#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `otherwise` (sorry, just noticed)
</blockquote></details>

thanks for noticing it!


<!-- Sent from Reviewable.io -->

2023-09-30 13:35 UTC, mkow requested changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NfaByoPDzJrq1Y6b_DC:bmmkx2c) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
> ```reStructuredText
> 
> In this section, we describe how you can protect your Docker container using
> Gramine Shielded Containers (GSC), Scaffolding for Gramine (SCAG), and how you
> ```

Not "and"?



_Suggestion:_
```reStructuredText
Gramine Shielded Containers (GSC) and Scaffolding for Gramine (SCAG)
```
___
*[`Documentation/index.rst` line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaCygI87ZeK3glWTGj:-NfaCygI87ZeK3glWTGk:bvo0reu) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L48)):*
> ```reStructuredText
> 
>   The Scaffolding for Gramine (SCAG) tool is a different approach for "graminizing"
>   your application. SCAG meticulously transforms your application into a
> ```

Less marketing please



_Suggestion:_
```reStructuredText
SCAG transforms
```
___
*[`Documentation/index.rst` line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaD8Tr1T3HJxPRJd0X:-NfaD8TsA2y_nIYTOec2:b249pw6) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L49)):*
> ```reStructuredText
>   The Scaffolding for Gramine (SCAG) tool is a different approach for "graminizing"
>   your application. SCAG meticulously transforms your application into a
>   Graminized Docker image, encapsulating both your application and the Gramine
> ```

In the previous sentence you started it with a lower-case "g"



_Suggestion:_
```reStructuredText
graminized Docker image
```
___
*[`Documentation/index.rst` line 50 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaDTNv2e5csJyglVGB:-NfaDTNv2e5csJyglVGC:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L50)):*
> ```reStructuredText
>   your application. SCAG meticulously transforms your application into a
>   Graminized Docker image, encapsulating both your application and the Gramine
>   Library OS. The primary objective of the Scaffolding project is to expedite
> ```





_Suggestion:_
```reStructuredText
The primary objective of the Scaffolding project is to simplify
```
___
*[`Documentation/index.rst` line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaFdXb7OogxpfFEzRV:-NfaFdXb7OogxpfFEzRW:b-usopye) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L58)):*
> ```reStructuredText
>   to Flask and Express.js. For a more in-depth exploration, see
>   :doc:`scag-installation`, or contribute to the
>   `GitHub project <https://github.com/intel/ScaffoldingForGramine>`.
> ```

This link doesn't render correctly.
___
*[`Documentation/scag-installation.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaF_jwDlvOMbeRZxvo:-NfaF_jwDlvOMbeRZxvp:b-tl63l7) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/scag-installation.rst#L5)):*
> ```reStructuredText
> 
> The Scaffolding for Gramine (SCAG) tool meticulously transforms your
> application into a Graminized Docker image, encapsulating both your
> ```

ditto x2
___
*[`Documentation/scag-installation.rst` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaG1Na5Tc7ca-qgfuZ:-NfaG1Na5Tc7ca-qgfu_:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/scag-installation.rst#L16)):*
> ```reStructuredText
> automatically for the user. A list of currently supported frameworks
> can be found in
> `documentation <https://gramine-scaffolding.readthedocs.io/en/latest/manpages/scag-setup.html#cmdoption-scag-setup-framework>`
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-10-02 06:54 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-10-02 08:49 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NfjSrfSCbuvG21WkChu:be9uu5u) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not "and"?
</blockquote></details>

I think we have 3 sections:
GSC, SCAG and ready-made SGX images
___
*[`Documentation/index.rst` line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaD8Tr1T3HJxPRJd0X:-NfjX-i9AUP7OS-vsbdZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In the previous sentence you started it with a lower-case "g"
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 50 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaDTNv2e5csJyglVGB:-NfjX7TN3cdMBfLlCLcw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L50)):*
> ```reStructuredText
>   your application. SCAG meticulously transforms your application into a
>   Graminized Docker image, encapsulating both your application and the Gramine
>   Library OS. The primary objective of the Scaffolding project is to expedite
> ```

Done.
___
*[`Documentation/index.rst` line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaFdXb7OogxpfFEzRV:-NfjYUhB4F8Gs6ZYYyif:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This link doesn't render correctly.
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaF_jwDlvOMbeRZxvo:-NfjYrip9A8ONx3B53DI:btfxvro) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/scag-installation.rst#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto x2
</blockquote></details>

Actually x3 :)
meticulously, Graminized and expedite, or have you thought about something else?
Done.
___
*[`Documentation/scag-installation.rst` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaG1Na5Tc7ca-qgfuZ:-NfjYbt6D9pxe5ewfHBf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/scag-installation.rst#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 15:01 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NfknkZl3POz1ae-CZ1Z:b-yhh2es) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think we have 3 sections:
GSC, SCAG and ready-made SGX images
</blockquote></details>

Sorry, but this reads a bit confusing to me (w/ and w/o "and").

"In this section, we describe how you can protect your Docker container using ... Scaffolding for Gramine (SCAG)" -- this sounds like the precondition is that the user already has a Docker container, but we claim that SCAG is for/operates on applications (as stated below).
___
*[`Documentation/index.rst` line 56 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktQH01Q1eo0j-xq7C:-NfktQH01Q1eo0j-xq7D:b-jye4nx) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/index.rst#L56)):*
> ```reStructuredText
>   Setting itself apart from alternative solutions (like GSC), SCAG doesn't
>   tranform a Docker image, instead it generates a whole Docker image from
>   the given projects.  It offers seamless support for a variety of frameworks,
> ```

What kinds of frameworks? It sounds a bit vague to me -- maybe web-based frameworks?



_Code quote:_
```reStructuredText
frameworks
```
___
*[`Documentation/scag-installation.rst` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktlVFDCrdPOfwMXuw:-NfktlVFDCrdPOfwMXux:b-x6xt3o) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L10)):*
> ```reStructuredText
> hosts.
> 
> Setting itself apart from alternative solutions (like GSC), SCAG doesn't
> ```

Isn't it just GSC as the alternative solution (or do we have others)?



_Code quote:_
```reStructuredText
alternative solutions (like GSC)
```
___
*[`Documentation/scag-installation.rst` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfkrPuT8fYrEKvNd31R:-NfkrPuU0zlAlbw0e_Mj:b-e7bbaj) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L26)):*
> ```reStructuredText
> 
> SCAG wraps the application with additional security measures, such as adding
> SSL/TLS to otherwise plaintext-networking apps. All web-based frameworks,
> ```

Sounds like w/o SCAG, the apps will always be plaintext-networking?



_Code quote:_
```reStructuredText
otherwise
```
___
*[`Documentation/scag-installation.rst` line 28 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks85M4hh4QjTRaWjB:-Nfks85M4hh4QjTRaWjC:bamn8c6) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L28)):*
> ```reStructuredText
> SSL/TLS to otherwise plaintext-networking apps. All web-based frameworks,
> such as Express.js and Flask, are preconfigured to operate behind
> a web server (nginx), with SSL/TLS and the RA-TLS extension.
> ```

-> "Nginx" (to align w/ other docs in Gramine)



_Code quote:_
```reStructuredText
nginx
```
___
*[`Documentation/scag-installation.rst` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks-LPDJ2nVASnEjxO:-Nfks-LPDJ2nVASnEjxP:b4r0tla) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L30)):*
> ```reStructuredText
> a web server (nginx), with SSL/TLS and the RA-TLS extension.
> 
> Note that the SCAG tool is split from core Gramine and is hosted here:
> ```

but it's a new project (which was never in core Gramine)?



_Code quote:_
```reStructuredText
is split from core Gramine
```


<!-- Sent from Reviewable.io -->

2023-10-03 13:09 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-Nfpb8iTBhrVzpx9QMYt:br5izq) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry, but this reads a bit confusing to me (w/ and w/o "and").

"In this section, we describe how you can protect your Docker container using ... Scaffolding for Gramine (SCAG)" -- this sounds like the precondition is that the user already has a Docker container, but we claim that SCAG is for/operates on applications (as stated below).
</blockquote></details>

Yes, but the result is still a docker container.
The difference is that in GSC you have to have a container, but in SCAG, the container will be generated for you.

I can also try and rewrite this section as "protect your application", but when I think more about it it seems to be to be to vouge. What do you think?
___
*[`Documentation/index.rst` line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaCygI87ZeK3glWTGj:-NfpbHcb5GKiu6wUcvT7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Less marketing please
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 56 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktQH01Q1eo0j-xq7C:-Nfkze-Z5OdS7GcihYkB:b-ww9mrk) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/index.rst#L56)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What kinds of frameworks? It sounds a bit vague to me -- maybe web-based frameworks?
</blockquote></details>

In this sentence, the example of frameworks are given as examples: Flask and Express.js.
It's vague as we are working on adding more and more frameworks.
It's not limited to web-based frameworks. We also support "plain" python, java (WIP), C#, etc.
___
*[`Documentation/scag-installation.rst` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktlVFDCrdPOfwMXuw:-NfpbZw53pz7s6HwvIOY:bsu5e5p) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L10)):*
We don't have, I didn't want to put the GSC in the spotlight, but I can also mention GSC directly if you prefer such a version:
>  SCAG doesn't transform a Docker image like GSC, ....
Or
> Setting itself apart from GSC...
___
*[`Documentation/scag-installation.rst` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfkrPuT8fYrEKvNd31R:-NfpcDEw2vg2A2BxOdZT:bjsgwbo) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L26)):*
What I was trying to say, is that with SCAG by default, you get an additional layer of protection, in other you have to add it manually. So for example, if you have an express.js app that by default doesn't have a tls, if you will run scag on it you will get SSL/TLS.

Would you prefer to skip the "otherwise" word:
> SCAG wraps the application with additional security measures, such as adding SSL/TLS to plaintext-networking apps.
___
*[`Documentation/scag-installation.rst` line 28 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks85M4hh4QjTRaWjB:-Nfpd8uo1rVBqfav0GhV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L28)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> "Nginx" (to align w/ other docs in Gramine)
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks-LPDJ2nVASnEjxO:-Nfl-6tA037vJR02nfMH:biajp5t) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

but it's a new project (which was never in core Gramine)?
</blockquote></details>

We are describing a project in Gramine that has a "Gramine" in its name. So, to avoid any confusion, I wanted to highlight that this isn't part of core Gramine, for less "SGX aware" people.
If you feel that this is unnecessary I can remove that.


<!-- Sent from Reviewable.io -->

2023-10-03 18:28 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @oshogbo)

___
*[`Documentation/index.rst` line 56 at r6](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfqmaia6l_f9D8XqFWj:-Nfqmaia6l_f9D8XqFWk:b9eeav) ([raw file](https://github.com/gramineproject/gramine/blob/c6920a51dcd1de0a320943e2bc3f0eaeb620fafc/Documentation/index.rst#L56)):*
> ```reStructuredText
>   Setting itself apart from alternative solutions (like GSC), SCAG doesn't
>   tranform a Docker image, instead it generates a whole Docker image from
>   the given projects.  It offers seamless support for a variety of frameworks,
> ```

Double-space between sentences.
___
*[`Documentation/scag-installation.rst` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktlVFDCrdPOfwMXuw:-NfqmluE-z2JUuBcJqAZ:bczbttn) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We don't have, I didn't want to put the GSC in the spotlight, but I can also mention GSC directly if you prefer such a version:
>  SCAG doesn't transform a Docker image like GSC, ....
Or
> Setting itself apart from GSC...
</blockquote></details>

@kailun-qin We don't have others, but I've seen people writing their own Docker/Kubernetes scripts around Gramine. They can also be considered alternative solutions.
___
*[`Documentation/scag-installation.rst` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks-LPDJ2nVASnEjxO:-Nfqn5RQAEkWAZ7B19Vq:b-74lw60) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L30)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We are describing a project in Gramine that has a "Gramine" in its name. So, to avoid any confusion, I wanted to highlight that this isn't part of core Gramine, for less "SGX aware" people.
If you feel that this is unnecessary I can remove that.
</blockquote></details>

We can also say `... the SCAG tool is standalone and not part of core Gramine, and is hosted here:`

But I also don't have problems with the current wording, so not blocking.


<!-- Sent from Reviewable.io -->

2023-10-03 23:31 UTC, kailun-qin reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NfrltKQ5VkWPw0K5rVr:b-yp6zu2) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
> I can also try and rewrite this section as "protect your application", but when I think more about it it seems to be to be to vouge. What do you think?

Yeah I understand. Ok, I'm fine w/ the current version (until a better idea :)).
___
*[`Documentation/index.rst` line 56 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktQH01Q1eo0j-xq7C:-Nfrn7au-KhrPr0ApOvH:b-kufkx2) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/index.rst#L56)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

In this sentence, the example of frameworks are given as examples: Flask and Express.js.
It's vague as we are working on adding more and more frameworks.
It's not limited to web-based frameworks. We also support "plain" python, java (WIP), C#, etc.
</blockquote></details>

I see, thanks.
___
*[`Documentation/scag-installation.rst` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfktlVFDCrdPOfwMXuw:-NfrnLlG53_fbcK9aUAP:b-auyk23) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L10)):*
> We don't have others, but I've seen people writing their own Docker/Kubernetes scripts around Gramine. They can also be considered alternative solutions.

Ok, then the current version looks good to me.
___
*[`Documentation/scag-installation.rst` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfkrPuT8fYrEKvNd31R:-Nfro1u112rHhjbmYZ1a:b-8s01tr) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L26)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What I was trying to say, is that with SCAG by default, you get an additional layer of protection, in other you have to add it manually. So for example, if you have an express.js app that by default doesn't have a tls, if you will run scag on it you will get SSL/TLS.

Would you prefer to skip the "otherwise" word:
> SCAG wraps the application with additional security measures, such as adding SSL/TLS to plaintext-networking apps.
</blockquote></details>

I slightly prefer the version that we skip "otherwise" (but I'm not blocking now as you explained).
___
*[`Documentation/scag-installation.rst` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks-LPDJ2nVASnEjxO:-NfromiPDo6c4hyp6-ge:bnwdtvb) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can also say `... the SCAG tool is standalone and not part of core Gramine, and is hosted here:`

But I also don't have problems with the current wording, so not blocking.
</blockquote></details>

I slightly prefer the version of "standalone" (but I don't really insist).


<!-- Sent from Reviewable.io -->

2023-10-04 09:16 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-Nfty-Z7ANgeU5sRSrST:bgbqcks) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> I can also try and rewrite this section as "protect your application", but when I think more about it it seems to be to be to vouge. What do you think?

Yeah I understand. Ok, I'm fine w/ the current version (until a better idea :)).
</blockquote></details>

So, I mark it as done.
___
*[`Documentation/index.rst` line 56 at r6](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfqmaia6l_f9D8XqFWj:-NftxVBH9StSgUvZG_hz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c6920a51dcd1de0a320943e2bc3f0eaeb620fafc/Documentation/index.rst#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Double-space between sentences.
</blockquote></details>

Done.
___
*[`Documentation/scag-installation.rst` line 26 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfkrPuT8fYrEKvNd31R:-Nftxf_3BrG2cI1N0XH6:b-hgseg6) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I slightly prefer the version that we skip "otherwise" (but I'm not blocking now as you explained).
</blockquote></details>

I have removed "otherwise".
___
*[`Documentation/scag-installation.rst` line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/1578#-Nfks-LPDJ2nVASnEjxO:-NftxnA81YphZBdeBsns:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9a180e7c9b1aa9c50996937d94bd5cd2b76031be/Documentation/scag-installation.rst#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I slightly prefer the version of "standalone" (but I don't really insist).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 10:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-10-04 13:09 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-10-05 08:12 UTC, mkow requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NfysJCZ6bO58k7ihwp0:b-7sbyqp) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So, I mark it as done.
</blockquote></details>

Hmm, IMO Kailun is right, this section is titled "Protect your container" while SCAG doesn't take "your container" as input, so it doesn't really fit here. I'd rather have that under the "protect your application" section, but why do you say it's vague then?
___
*[`Documentation/scag-installation.rst` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaF_jwDlvOMbeRZxvo:-Nfysu-W4SvM-VJKmgsL:b-q4pzuf) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/scag-installation.rst#L5)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Actually x3 :)
meticulously, Graminized and expedite, or have you thought about something else?
Done.
</blockquote></details>

Yes, right :)


<!-- Sent from Reviewable.io -->

2023-10-06 09:58 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-Ng3OJLK0CFXZX8eSiDD:b-90xjlw) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, IMO Kailun is right, this section is titled "Protect your container" while SCAG doesn't take "your container" as input, so it doesn't really fit here. I'd rather have that under the "protect your application" section, but why do you say it's vague then?
</blockquote></details>

The docker isn't required to "protect your application" and in this section, we describe 3 methods that use a docker as a "fronted" for securing your application. You can "protect your application" without docker (ie. run it write your manifest file and use gramine-sgx without docker). Section "protect your application" suggests that this is the only way.

So either we would need to describe also the "plain method" or come up with other names.
Maybe section could be named: "Automation of Graminzing application with docker" or "Graminzing application with docker", or something like that.
Then we can write if you have Dockerfile you can consider GSC, if you don't have you can consider SCAG and so on...


<!-- Sent from Reviewable.io -->

2023-10-06 13:55 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-Ng4FnIq8PxkgnDSrtbK:b41zp8) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The docker isn't required to "protect your application" and in this section, we describe 3 methods that use a docker as a "fronted" for securing your application. You can "protect your application" without docker (ie. run it write your manifest file and use gramine-sgx without docker). Section "protect your application" suggests that this is the only way.

So either we would need to describe also the "plain method" or come up with other names.
Maybe section could be named: "Automation of Graminzing application with docker" or "Graminzing application with docker", or something like that.
Then we can write if you have Dockerfile you can consider GSC, if you don't have you can consider SCAG and so on...
</blockquote></details>

But these pages names say "your application" and "your image" - they are not about the way you're protecting them, but about what is the input to the process? (i.e. what the user has at the start of the process)


<!-- Sent from Reviewable.io -->

2023-10-09 12:22 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NgJNvqgCgNHOd9gs11t:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But these pages names say "your application" and "your image" - they are not about the way you're protecting them, but about what is the input to the process? (i.e. what the user has at the start of the process)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 12:25 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NgJON5nD1AI4NYueIqM:bvpokln) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@oshogbo Now you have two `Protect your application` sections? This is clearly wrong, so I'm blocking. (I'll be fine with whatever you decide with Michal, but right now it's obviously incorrect.)


<!-- Sent from Reviewable.io -->

2023-10-09 14:48 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/index.rst` line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/1578#-NfaByoPDzJrq1Y6b_DB:-NgJuFX4D5yz3sit4w0H:b-81m6u3) ([raw file](https://github.com/gramineproject/gramine/blob/75845c2445da55bf691dd61c60da1b7ef142821d/Documentation/index.rst#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo Now you have two `Protect your application` sections? This is clearly wrong, so I'm blocking. (I'll be fine with whatever you decide with Michal, but right now it's obviously incorrect.)
</blockquote></details>

Oh sorry, I'm not sure what I was thinking about.


<!-- Sent from Reviewable.io -->

2023-10-09 17:09 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`Documentation/index.rst` line 68 at r9](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgKPDjRAqBrKNkLbXI7:-NgKPDjRAqBrKNkLbXI8:b-70aipk) ([raw file](https://github.com/gramineproject/gramine/blob/d8eaab42ac385a6041dd45c83a34a504bbcd1bf3/Documentation/index.rst#L68)):*
> ```reStructuredText
> You can also check :doc:`Gramine tutorials<tutorials-index>`.
> 
> As an simplified way of protecting your application you can use a Scaffolding
> ```

I think you should remove `a` before Scaffolding.


<!-- Sent from Reviewable.io -->

2023-10-10 13:45 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/index.rst` line 68 at r9](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgKPDjRAqBrKNkLbXI7:-NgOpPxR6KmuVYdd1FZC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8eaab42ac385a6041dd45c83a34a504bbcd1bf3/Documentation/index.rst#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should remove `a` before Scaffolding.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-10 13:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-10-11 02:20 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`Documentation/index.rst` line 68 at r10](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgRV5lk-N_lrzptIN0t:-NgRV5lk-N_lrzptIN0u:bgjih21) ([raw file](https://github.com/gramineproject/gramine/blob/db81d31c29378d8dcb559290f9308d0f707a252d/Documentation/index.rst#L68)):*
> ```reStructuredText
> You can also check :doc:`Gramine tutorials<tutorials-index>`.
> 
> As an simplified way of protecting your application you can use Scaffolding
> ```

-> "a"



_Code quote:_
```reStructuredText
an
```
___
*[`Documentation/index.rst` line 72 at r10](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgRWr4i1z8ASu6Kd7yz:-NgRWr4i1z8ASu6Kd7z-:b1f9ten) ([raw file](https://github.com/gramineproject/gramine/blob/db81d31c29378d8dcb559290f9308d0f707a252d/Documentation/index.rst#L72)):*
> ```reStructuredText
> a graminized Docker image, encapsulating both your application and
> the Gramine Library OS. The primary objective of the Scaffolding project is
> to simplify the process of safeguarding applications against malicious hosts.
> ```

```
The primary objective of the Scaffolding project is to simplify the process of safeguarding applications against malicious hosts.
```


This sentense seems to be a duplication of the first sentence of this section (plus that we already said that it's a simplified way):
```
Use this option to protect an existing application against a malicious host with Gramine.
```
Should we just remove it?


<!-- Sent from Reviewable.io -->

2023-10-16 11:55 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/index.rst` line 68 at r10](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgRV5lk-N_lrzptIN0t:-NgsKF0t9hq1oJPVbc-z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db81d31c29378d8dcb559290f9308d0f707a252d/Documentation/index.rst#L68)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> "a"
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 72 at r10](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgRWr4i1z8ASu6Kd7yz:-NgsKbgH5Ue6fE_w1Dib:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db81d31c29378d8dcb559290f9308d0f707a252d/Documentation/index.rst#L72)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

```
The primary objective of the Scaffolding project is to simplify the process of safeguarding applications against malicious hosts.
```


This sentense seems to be a duplication of the first sentence of this section (plus that we already said that it's a simplified way):
```
Use this option to protect an existing application against a malicious host with Gramine.
```
Should we just remove it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 22:57 UTC, mkow requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @oshogbo)

___
*[`Documentation/index.rst` line 71 at r11](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgzNfur1yOem2vodEnN:-NgzNfur1yOem2vodEnO:bm0wn7g) ([raw file](https://github.com/gramineproject/gramine/blob/f0eac04d55e97fcf853bcee617e62234100c40f7/Documentation/index.rst#L71)):*
> ```reStructuredText
> can use Scaffolding for Gramine (SCAG). It is a tool which transforms your
> application into a graminized Docker image, encapsulating both your application
> and the Gramine Library OS.  It offers seamless support for a variety of
> ```

double space


<!-- Sent from Reviewable.io -->

2023-10-18 08:10 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/index.rst` line 71 at r11](https://reviewable.io/reviews/gramineproject/gramine/1578#-NgzNfur1yOem2vodEnN:-Nh0p_W5A-XYlxCciXol:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f0eac04d55e97fcf853bcee617e62234100c40f7/Documentation/index.rst#L71)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 16:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-10-19 02:34 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-19 09:50 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-19 09:52 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-19 14:21 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1578)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-19 14:23 UTC, merged