[CI-Examples] Update version of Memcached
gramineproject/gramine pull request #1582
Opened 2023-10-02 12:07 UTC by dimakuv

## Description of the changes 

Previous version of Memcached (v1.5.21) failed on Ubuntu 22.04 and GCC 11.4.0 with a build error:

    ‘sigignore’ is deprecated: Use the signal function instead

This was fixed in v1.6.7. So let's update Memcached to the latest available version (v1.6.21 as of Oct 2023). This latest version uses eventfd, so we also update the manifest template.

### Details

The exact error:
```
gcc -DHAVE_CONFIG_H -I.  -DNDEBUG   -g -O2 -pthread -pthread -Wall -Werror -pedantic \
    -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls \
    -MT memcached-memcached.o -MD -MP -MF .deps/memcached-memcached.Tpo -c -o memcached-memcached.o
memcached.c: In function ‘main’:
memcached.c:9531:9: error: ‘sigignore’ is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
```

The exact GCC version:
```
$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

The GitHub thread where this bug is described: https://github.com/memcached/memcached/issues/707

The Release Notes where this bug was fixed: https://github.com/memcached/memcached/wiki/ReleaseNotes167#fixes

The Release Notes where `eventfd` was added: https://github.com/memcached/memcached/wiki/ReleaseNotes1611#fixes

## How to test this PR? 

This was found while testing Memcached on an Ubuntu 22.04 machine with GCC 11.4.0. So try that out manually.

2023-10-02 12:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkHmgx0MB3bjdHzjnx:-NfkHmgx0MB3bjdHzjny:b-fpas7k) (no related file):*
Blocking until @woju uploads v1.6.21 to https://packages.gramineproject.io/distfiles

___


<!-- Sent from Reviewable.io -->

2023-10-02 12:11 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkHmgx0MB3bjdHzjnx:-NfkI2W0-IvvOLywglm-:b-vwjlx3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking until @woju uploads v1.6.21 to https://packages.gramineproject.io/distfiles
</blockquote></details>

Uploaded.

___


<!-- Sent from Reviewable.io -->

2023-10-02 14:12 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-Nfkhk5y4awOzAyQHNM2):*
Does this issue have anything to do w/ the GCC version? Isn't it about the glibc version?



_Code quote:_
```
11.4.0
```
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkiF80257X81wxScZt):*
May I know the guideline for updating the versions of our CI-examples (e.g., when we update and to which version)?



_Code quote:_
```
  This was fixed in v1.6.7. So let's update Memcached to the latest
  available version (v1.6.21 as of Oct 2023). This latest version uses
```


<!-- Sent from Reviewable.io -->

2023-10-03 07:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-Nfkhk5y4awOzAyQHNM2):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Does this issue have anything to do w/ the GCC version? Isn't it about the glibc version?
</blockquote></details>

Ah, you're right, I was mistakenly thinking that it's all about GCC (and I thought that the author of https://github.com/memcached/memcached/pull/691 simply didn't look deeper at what exactly caused the build error).

But now I know:
- GCC has a special attribute `__attribute__((deprecated))`
- Any function marked with this attributed will trigger a warning if GCC compiles with `-Wdeprecated-declarations`
- This warning turns into an error if GCC has `Werror`
- Glibc marked `sigignore` as deprecated at some point

I'm still a bit puzzled why it looks like only me hit this Memcached issue only now.

I will fix the commit message to talk about Glibc v2.35 (the one on Ubuntu 22.04).
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkiF80257X81wxScZt):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

May I know the guideline for updating the versions of our CI-examples (e.g., when we update and to which version)?
</blockquote></details>

I don't think we have any guideline... Just update whenever we can. Is there some problem with this approach?


<!-- Sent from Reviewable.io -->

2023-10-03 08:48 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-Nfkhk5y4awOzAyQHNM2):*
> I'm still a bit puzzled why it looks like only me hit this Memcached issue only now.

I think we have (internal) CI for Ubuntu 22.04 that should cover this case?
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkiF80257X81wxScZt):*
> Is there some problem with this approach?

Generally no. I was just interested to know.

But for this specific case, it means that even if the user is using some older versions of Memcached, she/he may take our example manifest as a reference which includes `sys.insecure__allow_eventfd = true`. Is it better that to add a note/comment there?


<!-- Sent from Reviewable.io -->

2023-10-03 10:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-Nfkhk5y4awOzAyQHNM2):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> I'm still a bit puzzled why it looks like only me hit this Memcached issue only now.

I think we have (internal) CI for Ubuntu 22.04 that should cover this case?
</blockquote></details>

I just talked privately with the folks who support our internal CI -- they knew this problem, but they postponed testing/updating Memcached on Ubuntu 22.04, since this required adding `sys.insecure__allow_eventfd = true`.

I think it's fine to add this insecure manifest option to our Memcached example (I also added a comment as you requested). But this is the context why our internal CI doesn't test Memcached with Ubuntu 22.04.

But this reminds us -- yep, we need to implement a secure version of eventfd (the one that works only inside the Gramine enclaves).
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-NfkiF80257X81wxScZt):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Is there some problem with this approach?

Generally no. I was just interested to know.

But for this specific case, it means that even if the user is using some older versions of Memcached, she/he may take our example manifest as a reference which includes `sys.insecure__allow_eventfd = true`. Is it better that to add a note/comment there?
</blockquote></details>

Done, I added a comment.


<!-- Sent from Reviewable.io -->

2023-10-03 23:01 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1582#-Nfkhk5y4awOzAyQHNM2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just talked privately with the folks who support our internal CI -- they knew this problem, but they postponed testing/updating Memcached on Ubuntu 22.04, since this required adding `sys.insecure__allow_eventfd = true`.

I think it's fine to add this insecure manifest option to our Memcached example (I also added a comment as you requested). But this is the context why our internal CI doesn't test Memcached with Ubuntu 22.04.

But this reminds us -- yep, we need to implement a secure version of eventfd (the one that works only inside the Gramine enclaves).
</blockquote></details>

Thanks for checking!


<!-- Sent from Reviewable.io -->

2023-10-07 04:04 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-09 07:37 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1582)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-09 12:16 UTC, merged