[python] Add gramine-sgx-sign --chroot option
gramineproject/gramine pull request #1584
Opened 2023-10-02 15:41 UTC by woju

## Description of the changes 
see commit message

## How to test this PR? 

1. Checkout this branch and build gramine.
2. Install this to your system.
3. `sed -i -e 's@file:helloworld@file:/app/helloworld@g' path/to/gramine/CI-Examples/helloworld`
4. Build `helloworld` example (only the manifest and binary, signing will come later).
5. Deboostrap an example chroot, e.g. using mmdebstrap, and install the same gramine into your chroot; copy an example into the chroot and measure it from outside. The following is a heavily modified mmdebstrap invocation I have lying aroun d (my version compiles a package using `debuild`, this version is hopefully simpler and builds using only meson):
```sh
mmdebstrap \
    --customize-hook 'DESTDIR="$1" meson install -C path/to/the/build/dir' \
    --customize-hook 'cp -r path/to/repo/of/gramine/CI-Examples/helloworld "$1"/app' \
    --customize-hook 'gramine-sgx-sign --chroot "$1" --manifest /app/helloworld.manifest --output /helloworld.manifest.sgx' \
    bookworm rootfs.tar 'deb http://deb.debian.org/debian main'
```
(this invocation is possibly missing some gramine dependencies, didn't check directly; maybe add `--include $package` for each missing package — my version uses `apt-get install ./gramine_1.5post~UNRELEASED_amd64.deb` and installs dependencies automatically).
6. run Gramine from this chroot, e.g. by building a docker image from it:
```Dockerfile
FROM scratch
ADD rootfs.tar /
WORKDIR /app
CMD ["gramine-sgx", "helloworld"]
```
```sh
docker build .
docker run --rm -it --device /dev/sgx_enclave --volume /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket sha256:...
```

## FAQ

1. Why can't you just `chroot "$1" gramine-sgx-sign ...`

   Because sgx signing plugins might not be installed inside the image/chroot.

2. What could possibly go wrong?

   Most of the CI-Examples won't work out of the box because `--chroot` option requires the paths to be absolute (to avoid ambiguity about relative paths, what directory those are related to, and how to translate that into chroot). And CI-Examples have relative paths e.g. to the current directory (like `file:helloworld`, hence `sed` in the testing instruction).

2023-10-02 19:41 UTC, woju commented
Jenkins, test check-python-platlib please

2023-10-03 07:33 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoO1r20TbSM_wC2mRq):*
I'd prefer to have the command in backticks. Can be done at final rebase.
___
*[`python/graminelibos/manifest.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoS8K2-dNOGLYfAnHt:-NfoS8K2-dNOGLYfAnHu:bvspwy2) ([raw file](https://github.com/gramineproject/gramine/blob/94899398023e2dd2b9486aac03cc2996c2f1b13d/python/graminelibos/manifest.py#L42)):*
> ```Python
>     return pathlib.Path(uri[len('file:'):])
> 
> def append_tf(trusted_files, path, hash_=None):
> ```

I verified that these moved and inlined funcs are the same (bar my comments) in the new version as in the old version.
___
*[`python/graminelibos/manifest.py` line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoRTmY5i-tnCpk1dVC:-NfoRTmY5i-tnCpk1dVD:bmf3hvp) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L146)):*
> ```Python
>         hash present) and updates ``sgx.trusted_files`` manifest entry with the result.
> 
>         Returns a list of all expanded files, i.e. files that we need to hash, and directories that
> ```

`files that we need` -> `files that we needed`
___
*[`python/graminelibos/manifest.py` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoOZgT37vpSgVB9FQj:-NfoOZgT37vpSgVB9FQk:bx2qx4o) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L148)):*
> ```Python
>         Returns a list of all expanded files, i.e. files that we need to hash, and directories that
>         we needed to list.
> ```

Don't you want to add the `Args:` section in this comment?
___
*[`python/graminelibos/manifest.py` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoPDgj7sOJHlUU4FDb:-NfoPDgj7sOJHlUU4FDc:b-c48qv4) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L173)):*
> ```Python
>         def append_tf(chroot_path):
>             if path not in trusted_files:
>                 trusted_files[out_chroot(chroot_path)] = hash_file_contents(chroot_path)
> ```

How does this function work? It has a single arg `chroot_path`, but it uses both `path` and `chroot_path`?

UPDATE: Ok, I see the `path` variable in the caller function. Is this really how you want to write it? Very confusing.

UPDATE: No, something doesn't end up. `path` in the caller function (outer scope) is a **parent path**, not the current sub-path. How does all this work?

UPDATE: Ok, I think you wanted to do like this but something got missing during refactoring:
```python
        def append_tf(chroot_path):
            path = out_chroot(chroot_path)
            if path not in trusted_files:
                trusted_files[path] = hash_file_contents(chroot_path)
```


<!-- Sent from Reviewable.io -->

2023-10-03 13:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: 2 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[`python/graminelibos/manifest.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoS8K2-dNOGLYfAnHt:-NfpoMFB17LoLa83P33l:b-h5xis0) ([raw file](https://github.com/gramineproject/gramine/blob/94899398023e2dd2b9486aac03cc2996c2f1b13d/python/graminelibos/manifest.py#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I verified that these moved and inlined funcs are the same (bar my comments) in the new version as in the old version.
</blockquote></details>

I'm sorry, I have rewritten this all yet again. :/
___
*[`python/graminelibos/manifest.py` line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoRTmY5i-tnCpk1dVC:-NfpoZK5D0KEHYehDGYG:b-lc0zit) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`files that we need` -> `files that we needed`
</blockquote></details>

I have changed this to list only the files themselves, as included in the manifest. Is this still OK, and if so, how do I reword this comment?
___
*[`python/graminelibos/manifest.py` line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoOZgT37vpSgVB9FQj:-NfpoQtFEk13fkmmzUh_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L148)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to add the `Args:` section in this comment?
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoPDgj7sOJHlUU4FDb:-NfoVVUhAVi5Lfa43rVR:bk4aoht) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does this function work? It has a single arg `chroot_path`, but it uses both `path` and `chroot_path`?

UPDATE: Ok, I see the `path` variable in the caller function. Is this really how you want to write it? Very confusing.

UPDATE: No, something doesn't end up. `path` in the caller function (outer scope) is a **parent path**, not the current sub-path. How does all this work?

UPDATE: Ok, I think you wanted to do like this but something got missing during refactoring:
```python
        def append_tf(chroot_path):
            path = out_chroot(chroot_path)
            if path not in trusted_files:
                trusted_files[path] = hash_file_contents(chroot_path)
```
</blockquote></details>

Good catch. This was working correctly by accident. `path` ends up being a variable from closure (see [LOAD_DEREF](https://docs.python.org/3/library/dis.html#opcode-LOAD_DEREF) in line 172 in `dis` below), and at the time of the call, it is set in outer function, in `for tf in self['sgx']['trusted_files']`, as `path = uri2path(uri)`, about in the middle of the function.

Because of this bug, and ambiguity of those closures, I've rewritten all of trusted files measurement. Now every function fits one screen, doesn't rely on closured (instead uses explicit OOP) and I hope is generally easier to reason about.

Here's a disassembly for reference:

```
Disassembly of <code object append_tf at 0x7fecfa50ecd0, file "/usr/lib/python3/dist-packages/graminelibos/manifest.py", line 171>:
              0 COPY_FREE_VARS           3

171           2 RESUME                   0

172           4 LOAD_DEREF               2 (path)
              6 LOAD_DEREF               3 (trusted_files)
              8 CONTAINS_OP              1
             10 POP_JUMP_FORWARD_IF_FALSE    29 (to 70)

173          12 LOAD_GLOBAL              1 (NULL + hash_file_contents)
             24 LOAD_FAST                0 (chroot_path)
             26 PRECALL                  1
             30 CALL                     1
             40 LOAD_DEREF               3 (trusted_files)
             42 PUSH_NULL
             44 LOAD_DEREF               1 (out_chroot)
             46 LOAD_FAST                0 (chroot_path)
             48 PRECALL                  1
             52 CALL                     1
             62 STORE_SUBSCR
             66 LOAD_CONST               0 (None)
             68 RETURN_VALUE

172     >>   70 LOAD_CONST               0 (None)
             72 RETURN_VALUE
```


<!-- Sent from Reviewable.io -->

2023-10-03 18:07 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`python/graminelibos/manifest.py` line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoRTmY5i-tnCpk1dVC:-Nfqi0W86jZw2DDHvKXl:b-30rrsr) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L146)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I have changed this to list only the files themselves, as included in the manifest. Is this still OK, and if so, how do I reword this comment?
</blockquote></details>

Yes, this is ok to me. And it is used as a dep input, so looks legit to only have the files themselves, not directories.

Why not `Returns a list of all expanded files, as included in the manifest` ?
___
*[`python/graminelibos/manifest.py` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoPDgj7sOJHlUU4FDb:-NfqhYqWAzj8fWNSEevu:b-x5hyxb) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L173)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Good catch. This was working correctly by accident. `path` ends up being a variable from closure (see [LOAD_DEREF](https://docs.python.org/3/library/dis.html#opcode-LOAD_DEREF) in line 172 in `dis` below), and at the time of the call, it is set in outer function, in `for tf in self['sgx']['trusted_files']`, as `path = uri2path(uri)`, about in the middle of the function.

Because of this bug, and ambiguity of those closures, I've rewritten all of trusted files measurement. Now every function fits one screen, doesn't rely on closured (instead uses explicit OOP) and I hope is generally easier to reason about.

Here's a disassembly for reference:

```
Disassembly of <code object append_tf at 0x7fecfa50ecd0, file "/usr/lib/python3/dist-packages/graminelibos/manifest.py", line 171>:
              0 COPY_FREE_VARS           3

171           2 RESUME                   0

172           4 LOAD_DEREF               2 (path)
              6 LOAD_DEREF               3 (trusted_files)
              8 CONTAINS_OP              1
             10 POP_JUMP_FORWARD_IF_FALSE    29 (to 70)

173          12 LOAD_GLOBAL              1 (NULL + hash_file_contents)
             24 LOAD_FAST                0 (chroot_path)
             26 PRECALL                  1
             30 CALL                     1
             40 LOAD_DEREF               3 (trusted_files)
             42 PUSH_NULL
             44 LOAD_DEREF               1 (out_chroot)
             46 LOAD_FAST                0 (chroot_path)
             48 PRECALL                  1
             52 CALL                     1
             62 STORE_SUBSCR
             66 LOAD_CONST               0 (None)
             68 RETURN_VALUE

172     >>   70 LOAD_CONST               0 (None)
             72 RETURN_VALUE
```
</blockquote></details>

Looks good to me. I'm not sure how the Python disassembly helps in reviewing :)
___
*[`python/graminelibos/manifest.py` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqeqj05VEm9vEms7rX:-Nfqeqj05VEm9vEms7rY:b-5e7msj) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L105)):*
> ```Python
> 
>         Returns:
>             TrustedFile: a single instance of TrustedFile
> ```

Why the comment doesn't have the `Raises:` part?
___
*[`python/graminelibos/manifest.py` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfaUEDIYMshKn2S28:-NfqfaUEDIYMshKn2S29:b-d242bu) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L118)):*
> ```Python
>     def __repr__(self):
>         return (f'{type(self).__name__}('
>                 f'uri={self.uri!r}, sha256={self.sha256!r}, chroot={self.chroot!r})')
> ```

IIUC, this is the replicate the existing object.

But is this used anywhere?
___
*[`python/graminelibos/manifest.py` line 122 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqfh_h6kHytdMjFVW3:-Nfqfh_h6kHytdMjFVW4:btylzwu) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L122)):*
> ```Python
> 
>     def to_manifest(self):
>         """Returns the representation of the current file for manifest
> ```

Please add a dot at the end of the sentence.
___
*[`python/graminelibos/manifest.py` line 135 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfxST7PEnOeizQs42:-NfqfxST7PEnOeizQs43:b-y9iyk9) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L135)):*
> ```Python
> 
> 
>     def ensure_hash(self):
> ```

This name is weird. Maybe `calculate_hash`? Or `calculate_hash_if_none`?

I mean, 99% of the time this function will actually compute the hash, not just ensure that it exists.
___
*[`python/graminelibos/manifest.py` line 311 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqcwhz9m5bhj9LiBfw:-Nfqcwhz9m5bhj9LiBfx:b-3s1c37) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L311)):*
> ```Python
> 
>         Raises:
>             graminelibos.ManifestError: There was an error with the format of some trusted files in the manifest
> ```

Doesn't fit into 100 chars per line now
___
*[`python/graminelibos/manifest.py` line 320 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqddDY8mn8X07Qjxf6:-NfqddDY8mn8X07Qjxf7:b-auxy2x) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L320)):*
> ```Python
>                 if tf.uri in trusted_files:
>                     # On duplicate entries, pick the one that is already measured, preferring
>                     # existing one to avoid dict insertion. Accept double (matching) sha256
> ```

Don't you need a comma before `to avoid dict insertion`?
___
*[`python/graminelibos/manifest.py` line 326 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqdP-rEIagMAGEpyF0:-NfqdP-rEIagMAGEpyF1:bfx0bzm) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L326)):*
> ```Python
>                         if tf.sha256 is not None and tf.sha256 != tf_old.sha256:
>                             raise ManifestError(
>                                 f'Two different sha256 values ({tf2.sha256} and {tf.sha256}) '
> ```

`tf2`? Should be `tf_old`


<!-- Sent from Reviewable.io -->

2023-10-03 21:58 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: 3 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoO1r20TbSM_wC2mRq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer to have the command in backticks. Can be done at final rebase.
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoRTmY5i-tnCpk1dVC:-NfrTSDs4mU2N7vHMKzB:b-rz4yv2) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this is ok to me. And it is used as a dep input, so looks legit to only have the files themselves, not directories.

Why not `Returns a list of all expanded files, as included in the manifest` ?
</blockquote></details>

Done. Just to be sure: what happens if you have say `trusted_files = ["file:/a/"]`, and directories `/a`, `/a/b`, and a file `/a/b/c`. You measure, you end up with `trusted_files = [{uri = "file:/a/b/c", sha256 = "..."}]` and makedep `manifest.sgx: /a/b/c`. Then you add file `/a/b/d`, which on the next `gramine-sgx-sign` will end up in trusted_files, but the directory `/a/b` is not part of dependencies anymore (it was before this change). Does that change anything?
___
*[`python/graminelibos/manifest.py` line 173 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoPDgj7sOJHlUU4FDb:-NfrUc3H5ndDjNWFgKGF:bdc83go) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good to me. I'm not sure how the Python disassembly helps in reviewing :)
</blockquote></details>

This is about the only sure way to know where a variable value is sourced when evaluating an expression in a python function. Python has multitude of possibilities, cf. [global](https://docs.python.org/3/reference/simple_stmts.html#the-global-statement), [nonlocal](https://docs.python.org/3/reference/simple_stmts.html#the-nonlocal-statement) and this monstrosity: https://docs.python.org/3/reference/datamodel.html#code-objects, which purports to explain various code object attributes that hold them.
___
*[`python/graminelibos/manifest.py` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqeqj05VEm9vEms7rX:-NfrMJBLClN7pV48OBvk:b-effer) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why the comment doesn't have the `Raises:` part?
</blockquote></details>

Because I forgot, and nothing really checks this. Now that I think about this, I'm not sure if raising ManifestError would be the correct thing to do, because in normal operation this won't ever be a problem with manifest. I think I'll document this to ValueError, raised by `.relative_to()`, as this will only result from programming errors, not from manifest errors.
___
*[`python/graminelibos/manifest.py` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfaUEDIYMshKn2S28:-Nfr69j8Al9oc4VTe-CM:b-8qr0z3) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

IIUC, this is the replicate the existing object.

But is this used anywhere?
</blockquote></details>

I used it for debugging (let's call them "strategically placed `print(repr(self))` statements"). It doesn't hurt to leave it as is.

It's a textual representation of the instance, to be used in string formatting (not for serialisation). Sometimes reprs are shown as constructor invocations (which this one is), but sometimes they're not, like `<MyClass instance at 0xadd8e55 attr1=123 attr2=456>` and that's up to class author. https://docs.python.org/3/reference/datamodel.html#object.__repr__

In this case I see one degree of freedom: `self.realpath`, which is not part of constructor invocation, but is a relevant attribute of this class. If you think it should be part of this repr, I'll change to `<TrustedFile(uri='file:/a/b/c', sha256='0123', chroot=None) realpath='/a/b/c'>`, to be both copy-paste-able to construct from REPL, and include this realpath.
___
*[`python/graminelibos/manifest.py` line 122 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqfh_h6kHytdMjFVW3:-NfrPhup-a0-1U8NmEpc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end of the sentence.
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 135 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfxST7PEnOeizQs42:-NfrPk4F62Wt2a70F1CN:b-s386r3) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This name is weird. Maybe `calculate_hash`? Or `calculate_hash_if_none`?

I mean, 99% of the time this function will actually compute the hash, not just ensure that it exists.
</blockquote></details>

`calculate_hash` would suggest to recalculate it unconditionally (with option to fail, e.g. if the file is gone from fs, but will end up in the image some other way). And `calculate_hash_if_none` can be shortened to `ensure_hash`: "ensure" is a word used for this behaviour (idempotent fix for something, noop if already done). There are already things in other Python code, like functions: [[1]](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future) [[2]](https://docs.python.org/3/library/venv.html#venv.EnvBuilder.ensure_directories) [[3]](https://docs.python.org/3/library/optparse.html#adding-new-actions), commands: [[4]](https://docs.python.org/3/library/ensurepip.html#module-ensurepip), or even arguments: [[5]](https://docs.python.org/3/library/json.html#json.dump).

IDK about usage, if you did specify some trusted files' hashes manually, it ensures that sha256 is there? I think it might be relevant when you'll be assembling that list from different places (currently not supported by our tooling, but using this API you can do it yourself). Then it will very much ensure that all hashes are OK, some already present.

Usage in `expand_all_trusted_files` follows this pattern.
___
*[`python/graminelibos/manifest.py` line 311 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfqcwhz9m5bhj9LiBfw:-NfrUMa95TcdyIaSBfs1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Doesn't fit into 100 chars per line now
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 320 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqddDY8mn8X07Qjxf6:-NfrUXw0BFpSJWFGC8ji:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L320)) [...]

2023-10-04 06:41 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`python/graminelibos/manifest.py` line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfoRTmY5i-tnCpk1dVC:-NftP7e906AQ2ivWvcYX:b3jk81h) ([raw file](https://github.com/gramineproject/gramine/blob/b1b03eb6f95b0be0ea7fc1f1dfec4b267ce37b23/python/graminelibos/manifest.py#L146)):*
> Does that change anything?

Well, the re-build will not be triggered in this case, and running `gramine-sgx app` will result in an error "Cannot open this trusted file because it was not specified in the manifest". I think this is benign, as the user will be said what needs to be done.

Also, I'm not even sure if these deps work correctly. I always tend to do a clean re-build of applications/tests, because in many cases the deps are incomplete.
___
*[`python/graminelibos/manifest.py` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfaUEDIYMshKn2S28:-NftOQx5-qiiMTgAuWhq:bq1lq8o) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L118)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I used it for debugging (let's call them "strategically placed `print(repr(self))` statements"). It doesn't hurt to leave it as is.

It's a textual representation of the instance, to be used in string formatting (not for serialisation). Sometimes reprs are shown as constructor invocations (which this one is), but sometimes they're not, like `<MyClass instance at 0xadd8e55 attr1=123 attr2=456>` and that's up to class author. https://docs.python.org/3/reference/datamodel.html#object.__repr__

In this case I see one degree of freedom: `self.realpath`, which is not part of constructor invocation, but is a relevant attribute of this class. If you think it should be part of this repr, I'll change to `<TrustedFile(uri='file:/a/b/c', sha256='0123', chroot=None) realpath='/a/b/c'>`, to be both copy-paste-able to construct from REPL, and include this realpath.
</blockquote></details>

Ah, it was purely for debugging. I like your idea with the format that also has `realpath`, please add.
___
*[`python/graminelibos/manifest.py` line 135 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfxST7PEnOeizQs42:-NftOl6x40qutoBxLeiA:b-1kg8pr) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L135)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`calculate_hash` would suggest to recalculate it unconditionally (with option to fail, e.g. if the file is gone from fs, but will end up in the image some other way). And `calculate_hash_if_none` can be shortened to `ensure_hash`: "ensure" is a word used for this behaviour (idempotent fix for something, noop if already done). There are already things in other Python code, like functions: [[1]](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future) [[2]](https://docs.python.org/3/library/venv.html#venv.EnvBuilder.ensure_directories) [[3]](https://docs.python.org/3/library/optparse.html#adding-new-actions), commands: [[4]](https://docs.python.org/3/library/ensurepip.html#module-ensurepip), or even arguments: [[5]](https://docs.python.org/3/library/json.html#json.dump).

IDK about usage, if you did specify some trusted files' hashes manually, it ensures that sha256 is there? I think it might be relevant when you'll be assembling that list from different places (currently not supported by our tooling, but using this API you can do it yourself). Then it will very much ensure that all hashes are OK, some already present.

Usage in `expand_all_trusted_files` follows this pattern.
</blockquote></details>

LGTM, thanks for the references, interesting to see Python terminology.


<!-- Sent from Reviewable.io -->

2023-10-04 08:53 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`python/graminelibos/manifest.py` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfqfaUEDIYMshKn2S28:-Nftje-B0tIEzvzv7f4D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dad028217a0a435311b98577ae6eda2e06152e9a/python/graminelibos/manifest.py#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, it was purely for debugging. I like your idea with the format that also has `realpath`, please add.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 08:54 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-10-04 14:50 UTC, kailun-qin requested changes
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 5 unresolved discussions (waiting on @woju)

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfuqTxl4Kb3CHVceTv8:-NfuqTxl4Kb3CHVceTv9:b-67rmj1) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/Documentation/manpages/gramine-sgx-sign.rst#L63)):*
> ```reStructuredText
>     the directory specified as the value of the option.
> 
>     Note you need to be very careful that the gramine runtime binaries are
> ```

Gramine (to align w/ the other place inside this doc).



_Code quote:_
```reStructuredText
gramine
```
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv9MRs-U-CPPMKg3Ag:-Nfv9MRs-U-CPPMKg3Ah:by9wus6) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/Documentation/manpages/gramine-sgx-sign.rst#L63)):*
> ```reStructuredText
>     the directory specified as the value of the option.
> 
>     Note you need to be very careful that the gramine runtime binaries are
> ```

What if one is careless? Why this note specifically for this option?



_Code quote:_
```reStructuredText
Note you need to be very careful
```
___
*[`python/graminelibos/manifest.py` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfuvSUeETghqROxg-G7:-NfuvSUeETghqROxg-G8:btamc2z) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L44)):*
> ```Python
>         uri (str): URI
>         sha256 (str or None): sha256
>         chroot (pathlib.Path or None): optional path to chroot, if being measured in chroot dir
> ```

Do we want to add `Raises:` section in this comment?
___
*[`python/graminelibos/manifest.py` line 172 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv8Uie6GRkXJK9l3k6:-Nfv8Uie6GRkXJK9l3k7:btamc2z) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L172)):*
> ```Python
> 
>         Yields:
>             :py:class:`TrustedFile`: one object for each entry in the directory
> ```

Do we want to add `Raises:` section in this comment?
___
*[`python/graminelibos/manifest.py` line 321 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv6YX09s60kvltR4fa:-Nfv6YX09s60kvltR4fb:b-l4gvmq) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L321)):*
> ```Python
>             for tf in TrustedFile.from_manifest(data, chroot=chroot).expand_directory():
>                 if tf.uri in trusted_files:
>                     # On duplicate entries, pick the one that is already measured, preferring
> ```

Should we also add some notes for the case where none of the duplicate entries is measured?


<!-- Sent from Reviewable.io -->

2023-10-04 16:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: 2 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @donporter, and @kailun-qin)

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv9MRs-U-CPPMKg3Ag:-NfvCes0-bkDOWZiab_n:bt9ln7e) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/Documentation/manpages/gramine-sgx-sign.rst#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What if one is careless? Why this note specifically for this option?
</blockquote></details>

If one is careless, s/he gets this (`#` is because this is in docker):
```
# gramine-sgx app
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Enclave initialization IOCTL failed: Operation not permitted (EPERM)
error: Initializing enclave failed: Operation not permitted (EPERM)
error: load_enclave() failed with error: Operation not permitted (EPERM)
```

And one need to figure out what is `-EPERM` on `ioctl(..., SGX_IOC_ENCLAVE_INIT)` on `/dev/sgx_enclave`. https://elixir.bootlin.com/linux/v6.5.5/source/arch/x86/kernel/cpu/sgx/ioctl.c#L588 says it's "Invalid SIGSTRUCT", but to find it, you already need to kinda know where to look. Now what's invalid with this SIGSTRUCT? It's MRENCLAVE, because you loaded different `libsysdb.so` and possibly `runtime/` libs, so hash doesn't match, but this needs to be guessed entirely.

So to answer the first question: because of poor UX on our side.
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfuqTxl4Kb3CHVceTv8:-NfvPTJo8dDuiKrab2gP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/Documentation/manpages/gramine-sgx-sign.rst#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Gramine (to align w/ the other place inside this doc).
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-NfuvSUeETghqROxg-G7:-NfvHj6E4gBeUYSRHJ6e:ba0g9mv) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L44)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we want to add `Raises:` section in this comment?
</blockquote></details>

Hmm, yes. `ManifestError` is raised. Done.
___
*[`python/graminelibos/manifest.py` line 172 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv8Uie6GRkXJK9l3k6:-NfvOEm690rjKk--ZVZq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L172)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we want to add `Raises:` section in this comment?
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 321 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv6YX09s60kvltR4fa:-NfvKyi2EHRNBCevMBb6:bv7xfjq) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L321)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we also add some notes for the case where none of the duplicate entries is measured?
</blockquote></details>

It said so already, but I have reworded it to be simpler and more explicit (hopefully more clear). Is this version better?


<!-- Sent from Reviewable.io -->

2023-10-04 16:22 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 63 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv9MRs-U-CPPMKg3Ag:-NfvT0ys7wOL7KP279SC:b-lg05om) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/Documentation/manpages/gramine-sgx-sign.rst#L63)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If one is careless, s/he gets this (`#` is because this is in docker):
```
# gramine-sgx app
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Enclave initialization IOCTL failed: Operation not permitted (EPERM)
error: Initializing enclave failed: Operation not permitted (EPERM)
error: load_enclave() failed with error: Operation not permitted (EPERM)
```

And one need to figure out what is `-EPERM` on `ioctl(..., SGX_IOC_ENCLAVE_INIT)` on `/dev/sgx_enclave`. https://elixir.bootlin.com/linux/v6.5.5/source/arch/x86/kernel/cpu/sgx/ioctl.c#L588 says it's "Invalid SIGSTRUCT", but to find it, you already need to kinda know where to look. Now what's invalid with this SIGSTRUCT? It's MRENCLAVE, because you loaded different `libsysdb.so` and possibly `runtime/` libs, so hash doesn't match, but this needs to be guessed entirely.

So to answer the first question: because of poor UX on our side.
</blockquote></details>

I see, thanks for the explanation!
___
*[`python/graminelibos/manifest.py` line 321 at r4](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nfv6YX09s60kvltR4fa:-NfvTi-BEJTWtPU-p7a7:b1uxrt8) ([raw file](https://github.com/gramineproject/gramine/blob/33f2cced009ebddb94aed501326bdbb0694d72fd/python/graminelibos/manifest.py#L321)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It said so already, but I have reworded it to be simpler and more explicit (hopefully more clear). Is this version better?
</blockquote></details>

Ah indeed (sorry for my poor English). Yes, this is clearer to me, thanks!


<!-- Sent from Reviewable.io -->

2023-10-09 07:08 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-09 07:36 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-18 00:09 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nh-6FW68jvZ-N0c3xTI):*
> Also rewrite trusted files measurement.

Would it be possible to split this off as a separate PR? Right now it's hard to say what is refactoring and what is the core change here.


<!-- Sent from Reviewable.io -->

2023-10-18 06:43 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nh-6FW68jvZ-N0c3xTI):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Also rewrite trusted files measurement.

Would it be possible to split this off as a separate PR? Right now it's hard to say what is refactoring and what is the core change here.
</blockquote></details>

+1, agree, this PR ended up modifying the trusted files measurement code heavily.


<!-- Sent from Reviewable.io -->

2023-10-23 10:35 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nh-6FW68jvZ-N0c3xTI):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, agree, this PR ended up modifying the trusted files measurement code heavily.
</blockquote></details>

Not at this stage I'm afraid. The problem with the older implementation (which relied on closures) was that it wasn't easy to add this chroot option. Best I can do would be to split into two commits, first would rewrite to non-chroot version and the second one would add chroot. This would be much work, which I would instead like to spend on fixing CI.


<!-- Sent from Reviewable.io -->

2023-10-23 11:25 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nh-6FW68jvZ-N0c3xTI):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not at this stage I'm afraid. The problem with the older implementation (which relied on closures) was that it wasn't easy to add this chroot option. Best I can do would be to split into two commits, first would rewrite to non-chroot version and the second one would add chroot. This would be much work, which I would instead like to spend on fixing CI.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2023-12-08 01:50 UTC, mkow reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`python/graminelibos/manifest.py` line 155 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nl638e-B1TGbgo3DiLL:-Nl638e-B1TGbgo3DiLM:b-9xutop) ([raw file](https://github.com/gramineproject/gramine/blob/8b5ecdca772002f18b62d42a8fc19439e47fcd18/python/graminelibos/manifest.py#L155)):*
> ```Python
>                 for chunk in iter(lambda: file.read(128 * sha.block_size), b''):
>                     sha.update(chunk)
>                 self.sha256 = sha.hexdigest()
> ```

Could you rename this field to `sha256_hex`? Up until this line I didn't notice it's in hex, not a byte string, I think it's a bit unintuitive. Or maybe store in bytes, and only convert when outputting it?



_Code quote:_
```Python
self.sha256
```


<!-- Sent from Reviewable.io -->

2023-12-08 10:53 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`python/graminelibos/manifest.py` line 155 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nl638e-B1TGbgo3DiLL:-Nl7ye1D104dZDLfTwla:bpzgnnv) ([raw file](https://github.com/gramineproject/gramine/blob/8b5ecdca772002f18b62d42a8fc19439e47fcd18/python/graminelibos/manifest.py#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you rename this field to `sha256_hex`? Up until this line I didn't notice it's in hex, not a byte string, I think it's a bit unintuitive. Or maybe store in bytes, and only convert when outputting it?
</blockquote></details>

I would prefer not to, because in manifest (and consequently in the dict that the manifest gets parsed to) the key is also `sha256` and carries hex string. This correspondence seems nice to me. I think there's no use anywhere in Python for digest as `bytes`, so I don't want to decode to bytes on load and encode to hex on save.

I can explicitly document it in attribute doc comment.


<!-- Sent from Reviewable.io -->

2023-12-08 11:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-12-08 18:13 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`python/graminelibos/manifest.py` line 155 at r6](https://reviewable.io/reviews/gramineproject/gramine/1584#-Nl638e-B1TGbgo3DiLL:-Nl9XT1M5J7SucEFRzr2:b5iuwn6) ([raw file](https://github.com/gramineproject/gramine/blob/8b5ecdca772002f18b62d42a8fc19439e47fcd18/python/graminelibos/manifest.py#L155)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I would prefer not to, because in manifest (and consequently in the dict that the manifest gets parsed to) the key is also `sha256` and carries hex string. This correspondence seems nice to me. I think there's no use anywhere in Python for digest as `bytes`, so I don't want to decode to bytes on load and encode to hex on save.

I can explicitly document it in attribute doc comment.
</blockquote></details>

Ok, I won't block, but my problem / what I mean by "unintuitiveness" here is that string representation is not the native way of storing bytes.


<!-- Sent from Reviewable.io -->

2023-12-09 00:32 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-11 07:55 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-11 09:37 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1584)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-11 09:57 UTC, merged