[python] Add `gramine-sgx-sign --date` option
gramineproject/gramine pull request #1598
Opened 2023-10-09 15:48 UTC by woju

## Description of the changes 
See commit message.

## How to test this PR? 

1) Sign any SGX enclave using `gramine-sgx-sign` without `--date`, see that there is no regression (CI is sufficient for this)
2) Use `gramine-sgx-sign --date today` — should be the same SIGSTRUCT as in (1)
3) Use `gramine-sgx-sign --date YYYY-MM-DD` with valid date (e.g. 2023-10-09 for date of submitting this PR) — should include this date in SIGSTRUCT (you can inspect with `gramine-sgx-sigstruct-view`)
4) Use `gramine-sgx-sign --date 1234-56-78` or `0000-00-00` or any other invalid date — should still pass and include such invalid "date" into SIGSTRUCT.

2023-10-09 19:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgKzxg-64iKwVzwTJfU:-NgKzxg-64iKwVzwTJfV:b-f5ju76) (no related file):*
WRT `gramine-sgx-sigstruct-view`, when the year is &lt; 1000, then this happens:
```
% gramine-sgx-sigstruct-view -v helloworld.sig
Attributes:
    mr_signer: [...]
    mr_enclave: [...]
    [...]
    date: 0-00-00
    debug_enclave: True
```
(This is obviously from `--date 0000-00-00`). Do we need it to be zero padded to 4 digits? Curretntly`--date` requires it, you can't have it pasted `0-00-00` from here.

___


<!-- Sent from Reviewable.io -->

2023-10-10 08:14 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgKzxg-64iKwVzwTJfU:-NgNc-0L0CIxdAGlkv4g:bl4mt96) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

WRT `gramine-sgx-sigstruct-view`, when the year is &lt; 1000, then this happens:
```
% gramine-sgx-sigstruct-view -v helloworld.sig
Attributes:
    mr_signer: [...]
    mr_enclave: [...]
    [...]
    date: 0-00-00
    debug_enclave: True
```
(This is obviously from `--date 0000-00-00`). Do we need it to be zero padded to 4 digits? Curretntly`--date` requires it, you can't have it pasted `0-00-00` from here.
</blockquote></details>

Yes, please, let's zero-pad it (and please check if there are other Python scripts where we print the date, I think we have it as debug-level info somewhere else)

___
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcBAl0AJ8HqhzxEE3):*
`known`
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcDJ75weJbbcdtOT2):*
`--date option` -> ```the `--date` option``` (2x)
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcZzY9nNskPYdhBKq:-NgNcZzY9nNskPYdhBKr:bliur3g) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/Documentation/manpages/gramine-sgx-sign.rst#L42)):*
> ```reStructuredText
> 
>     Set specific date to be put into SIGSTRUCT. If not given, or the value is
>     literal ``today``, that current day according to system calendar is used.
> ```

`that` -> `than`
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcej5CyuT8xtDvlaO:-NgNcej5CyuT8xtDvlaP:bi19xdp) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/Documentation/manpages/gramine-sgx-sign.rst#L44)):*
> ```reStructuredText
>     literal ``today``, that current day according to system calendar is used.
>     Otherwise expects ``<YYYY>-<MM>-<DD>``. The date needs not to be a |~| valid
>     day, it will happily accept ``--date 0000-00-00``, e.g. for reproducible
> ```

Why this `e.g. for reproducible builds`? Why do you mention reproducible builds in the sentence where you talk about wrong date formats? Don't you want to have a separate sentence that says something like "This option is useful for reproducible builds."
___
*[`python/gramine-sgx-sign` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNd8347D2UFuY6YaV2:-NgNd8347D2UFuY6YaV3:bbopji5) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/python/gramine-sgx-sign#L49)):*
> ```
>     """Parse "today" or a date-like string YYYY-MM-DD, accepting invalid dates.
> 
>     This is needed to support dates like 0000-00-00, which are invalid days, but valid things to put
> ```

Exceeded our 100 char per line limit.


<!-- Sent from Reviewable.io -->

2023-10-13 15:10 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: 1 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgKzxg-64iKwVzwTJfU:-NgdY4iU76rbx11P_vl9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please, let's zero-pad it (and please check if there are other Python scripts where we print the date, I think we have it as debug-level info somewhere else)
</blockquote></details>

Done.

___
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcBAl0AJ8HqhzxEE3):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`known`
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcDJ75weJbbcdtOT2):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`--date option` -> ```the `--date` option``` (2x)
</blockquote></details>

Done.
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcZzY9nNskPYdhBKq:-NgdYUD-154hkj1Q3zUn:b32l9lp) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/Documentation/manpages/gramine-sgx-sign.rst#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`that` -> `than`
</blockquote></details>

Done. (then)
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcej5CyuT8xtDvlaO:-NgNhkLO5slDv-eAgKj0:bn1yow) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/Documentation/manpages/gramine-sgx-sign.rst#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this `e.g. for reproducible builds`? Why do you mention reproducible builds in the sentence where you talk about wrong date formats? Don't you want to have a separate sentence that says something like "This option is useful for reproducible builds."
</blockquote></details>

Because it's a common thing to put zeros in variable fields when const-ing them to remove unreproducibility. For time, there's a technically better solution, [$SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/), but you need to provide it in your build environment, so if you don't have it, then the next best option is to put 0 in the date. For simplicity I chose to mention 0 and didn't mention `$SOURCE_DATE_EPOCH`, since people who do reprobuilds already know about it and will be able to pick it themselves just fine.

For reprobuilds we probably need to write separate article, mentioning multiple ways that it could fail, not just mark different option as relevant. But this is obviously not in scope in this PR.
___
*[`python/gramine-sgx-sign` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNd8347D2UFuY6YaV2:-NgdZTZ6EJrNX96iOJOQ:bjrufu9) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/python/gramine-sgx-sign#L49)):*
It does not:
```
% python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> len('    This is needed to support dates like 0000-00-00, which are invalid days, but valid things to put')
100
```


<!-- Sent from Reviewable.io -->

2023-10-16 07:33 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNcej5CyuT8xtDvlaO:-NgrOgmS6ikZzPwJ23lE:b-wsvasg) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/Documentation/manpages/gramine-sgx-sign.rst#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because it's a common thing to put zeros in variable fields when const-ing them to remove unreproducibility. For time, there's a technically better solution, [$SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/), but you need to provide it in your build environment, so if you don't have it, then the next best option is to put 0 in the date. For simplicity I chose to mention 0 and didn't mention `$SOURCE_DATE_EPOCH`, since people who do reprobuilds already know about it and will be able to pick it themselves just fine.

For reprobuilds we probably need to write separate article, mentioning multiple ways that it could fail, not just mark different option as relevant. But this is obviously not in scope in this PR.
</blockquote></details>

Thanks for the explanation!
___
*[`python/gramine-sgx-sign` line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/1598#-NgNd8347D2UFuY6YaV2:-NgrOm1s8V1tFiuBZ7kE:b-n3y5up) ([raw file](https://github.com/gramineproject/gramine/blob/25f0d710e05ec40bae0bae05f1493ccde1df55f1/python/gramine-sgx-sign#L49)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It does not:
```
% python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> len('    This is needed to support dates like 0000-00-00, which are invalid days, but valid things to put')
100
```
</blockquote></details>

Yes, weird, sorry. I guess my Reviewable was glitchy.


<!-- Sent from Reviewable.io -->

2023-10-23 01:39 UTC, mkow requested changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhP8nQGAm6USbR8_av-):*




_Suggestion:_
```
keep the previous behaviour and set the current date.
```
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPA31377eoItn0VJ8t:-NhPA31377eoItn0VJ8u:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/Documentation/manpages/gramine-sgx-sign.rst#L41)):*
> ```reStructuredText
> .. option:: --date <YYYY-MM-DD>|today
> 
>     Set specific date to be put into SIGSTRUCT. If not given, or the value is
> ```





_Suggestion:_
```reStructuredText
``SIGSTRUCT``
```
___
*[`python/gramine-sgx-sign` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPAD_PDgvvcBhykJZV:-NhPAD_PDgvvcBhykJZW:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/python/gramine-sgx-sign#L6)):*
> ```
> #                    Borys Popławski <borysp@invisiblethingslab.com>
> # Copyright (C) 2023 Intel Corporation
> #                    Wojtek Porczyk <woju@invisiblethingslab.com>
> ```





_Suggestion:_
```
# Copyright (C) 2023 Intel Corporation
#                    Borys Popławski <borysp@invisiblethingslab.com>
#                    Wojtek Porczyk <woju@invisiblethingslab.com>
```


<!-- Sent from Reviewable.io -->

2023-10-27 14:33 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhP8nQGAm6USbR8_av-):*
Done.
___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPA31377eoItn0VJ8t:-NhlWVZIASjir85IXoVM:b-h0lv9c) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/Documentation/manpages/gramine-sgx-sign.rst#L41)):*
> ```reStructuredText
> .. option:: --date <YYYY-MM-DD>|today
> 
>     Set specific date to be put into SIGSTRUCT. If not given, or the value is
> ```

Everywhere it's without double backquotes. I would have to change the whole document.

Also, the theoretically correct thing to do would be to document this structure and put it as `:c:struct:` role, in single quotes.
___
*[`python/gramine-sgx-sign` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPAD_PDgvvcBhykJZV:-NhlYKHz9drcDfRDeb3P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/python/gramine-sgx-sign#L6)):*
> ```
> #                    Borys Popławski <borysp@invisiblethingslab.com>
> # Copyright (C) 2023 Intel Corporation
> #                    Wojtek Porczyk <woju@invisiblethingslab.com>
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-10-28 23:08 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPA31377eoItn0VJ8t:-NhsXRsb-nDPMye949WW:b-1ztz3z) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/Documentation/manpages/gramine-sgx-sign.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Everywhere it's without double backquotes. I would have to change the whole document.

Also, the theoretically correct thing to do would be to document this structure and put it as `:c:struct:` role, in single quotes.
</blockquote></details>

But it's just 4 places here? I think it doesn't hurt to fix it in this commit.

W.r.t. `:c:struct:`: yeah, but that's more work and it would make sense only if we documented other structs this way. Nice to have, but I guess for later, when someone gets bored :)


<!-- Sent from Reviewable.io -->

2023-10-31 12:44 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`Documentation/manpages/gramine-sgx-sign.rst` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1598#-NhPA31377eoItn0VJ8t:-Ni4kxbN8X2l_1KFTLBC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3d919aaec1f37c6878b87623fcc1febb2e19b905/Documentation/manpages/gramine-sgx-sign.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it's just 4 places here? I think it doesn't hurt to fix it in this commit.

W.r.t. `:c:struct:`: yeah, but that's more work and it would make sense only if we documented other structs this way. Nice to have, but I guess for later, when someone gets bored :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-31 12:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-16 23:38 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-16 23:44 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-17 06:22 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`python/gramine-sgx-sign` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1598#-NjQtoOU5Ujg4is10f1D:-NjQtoOVBErYHhT1ms4Z:beizkab) ([raw file](https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/python/gramine-sgx-sign#L3)):*
> ```
> #!/usr/bin/python3
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2023 Intel Corporation
> ```

Why do we need to update to `2023` here?



_Code quote:_
```
2023
```


<!-- Sent from Reviewable.io -->

2023-11-17 07:37 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-11-17 07:37 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-17 07:38 UTC, merged

2023-11-17 14:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`python/gramine-sgx-sign` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1598#-NjQtoOU5Ujg4is10f1D:-NjSie-E4-ju51im03mt:be8hmwm) ([raw file](https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/python/gramine-sgx-sign#L3)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why do we need to update to `2023` here?
</blockquote></details>

Because there was a significant change now and we decided to specify the latest time a copyrighted code was added to a file.
These copyright notices with years aren't legally binding in any way, it's just to warn/inform users "this file had the last copyrightable change from copyright owner ASDF in year XYZ, if you are waiting for copyright to expire, you need to wait X years from that year".
See https://gramine.readthedocs.io/en/latest/devel/contributing.html#copyrights-and-licenses.


<!-- Sent from Reviewable.io -->

2023-11-18 04:19 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1598)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`python/gramine-sgx-sign` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1598#-NjQtoOU5Ujg4is10f1D:-NjVdcet2cZUxVQUm6eW:b4io903) ([raw file](https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/python/gramine-sgx-sign#L3)):*
> it's just to warn/inform users "this file had the last copyrightable change from copyright owner ASDF in year XYZ, if you are waiting for copyright to expire, you need to wait X years from that year".

Thanks for the explanations!


<!-- Sent from Reviewable.io -->