[PAL] Refactor splitting of typed URI into type, URI and ops
gramineproject/gramine pull request #1607
Opened 2023-10-16 10:36 UTC by dimakuv

## Description of the changes 

Previously PAL code had a function `parse_stream_uri()` that returned the type, URI and corresponding handle operations based on the typed URI input. This function had confusing signature and semantics. This commit renames it to `split_uri_and_find_ops()` and makes it explicit that the input URI is a type-prefixed URI.

Fixes #1586. **NOTE**: I didn't make the `find_path_in_uri()` a generic func because it would become too complex. So I kept the `find_path_in_uri()` function as local to that file, and instead simply refactored the `parse_stream_uri()` code.

## How to test this PR? 

N/A.

2023-10-16 10:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`common/include/api.h` line 403 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngs2r489BPfDg9PCdQ0:-Ngs2r489BPfDg9PCdQ1:brmxei1) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/common/include/api.h#L403)):*
> ```objc
>                                             MAX(URI_PREFIX_DEV_LEN,           \
>                                                 MAX(URI_PREFIX_EVENTFD_LEN,   \
>                                                     URI_PREFIX_FILE_LEN)))))))
> ```

Heh, is there a better way?
___
*[`pal/include/pal/pal.h` line 514 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngs2vGx98CE049heqOh:-Ngs2vGx98CE049heqOi:bthppza) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/include/pal/pal.h#L514)):*
> ```objc
>  * \brief This API changes the name of an open stream.
>  */
> int PalStreamChangeName(PAL_HANDLE handle, const char* typed_uri);
> ```

FYI: These are the only three funcs that used `uri`, please double-check me when reviewing.


<!-- Sent from Reviewable.io -->

2023-10-17 22:28 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/include/api.h` line 403 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngs2r489BPfDg9PCdQ0:-NgzhgSy7MToyOkGhz7O:b-j0imqh) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/common/include/api.h#L403)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Heh, is there a better way?
</blockquote></details>

I don't think so :grimacing: 
___
*[`pal/src/pal_streams.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgzizUGCpbHAJpyut71:-NgzizUH3MYwhpS4I5Qr:btujqjh) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L39)):*
> ```C
> };
> 
> /* `out_type` should be stack-allocated by the caller; `out_uri` is the pointer inside `typed_uri`;
> ```

Why? It doesn't matter for the API where it is allocated.



_Code quote:_
```C
stack-allocated by the caller
```
___
*[`pal/src/pal_streams.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngzi8RL4YFJL3OvBO0f:-Ngzi8RMByNONiQEG3wz:bzab79u) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L88)):*
> ```C
>     struct handle_ops* ops;
> 
>     int ret = split_uri_and_find_ops(typed_uri, (char*)&type, &uri, &ops);
> ```

Why is this cast needed?



_Code quote:_
```C
(char*)&type
```
___
*[`pal/src/pal_streams.c` line 206 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgziQ2gEJvBE8Pxr5N6:-NgziQ2gEJvBE8Pxr5N7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L206)):*
> ```C
>     struct handle_ops* ops;
> 
>     int ret = split_uri_and_find_ops(typed_uri, (char*)&type, &uri, &ops);
> ```

ditto
___
*[`pal/src/pal_streams.c` line 390 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgziVR74vGwmeC666W2:-NgziVR74vGwmeC666W3:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L390)):*
> ```C
>     struct handle_ops* ops;
> 
>     int ret = split_uri_and_find_ops(typed_uri, (char*)&type, &uri, &ops);
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-10-18 01:27 UTC, kailun-qin reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`pal/src/pal_streams.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgzizUGCpbHAJpyut71:-Nh-OAjG--TtAKP5zLPM:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why? It doesn't matter for the API where it is allocated.
</blockquote></details>

+1
___
*[`pal/src/pal_streams.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngzi8RL4YFJL3OvBO0f:-Nh-NEaj5piSaD6S7WI5:b-ops5f3) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this cast needed?
</blockquote></details>

the input arg is acutally a pointer to char array (`char (*)[]`) but the compiler would expect char pointer (`char*`)?


<!-- Sent from Reviewable.io -->

2023-10-18 07:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/pal_streams.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgzizUGCpbHAJpyut71:-Nh0jBEXC2OVjCt4W23n:bwoj7uh) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L39)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. I wanted to be specific that we don't want to `malloc()` here, that's why such a weird signature of the function (one arg is fed into this func, another arg is a pointer in the middle of `typed_uri`). But let me just delete all these comments.
___
*[`pal/src/pal_streams.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngzi8RL4YFJL3OvBO0f:-Nh0jTde6wDJnKh8ZNep:b-89z4xt) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L88)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

the input arg is acutally a pointer to char array (`char (*)[]`) but the compiler would expect char pointer (`char*`)?
</blockquote></details>

Because the compiler complains:
```
../pal/src/pal_streams.c:87:49: warning: passing argument 2 of ‘split_uri_and_find_ops’ from incompatible pointer type [-Wincompatible-pointer-types]
   87 |     int ret = split_uri_and_find_ops(typed_uri, &type, &uri, &ops);
      |                                                 ^~~~~
      |                                                 |
      |                                                 char (*)[(sizetype)(__builtin_memcpy(&<U9090>, &({...})) + 1)]
../pal/src/pal_streams.c:40:64: note: expected ‘char *’ but argument is of type ‘char (*)[(sizetype)(__builtin_memcpy(&<U9090>, &({...})) + 1)]’
```

Alternatively to the current code, I can do this:
```diff
-    char type[URI_PREFIX_MAX_LEN + 1];
+    char* type = __alloca(URI_PREFIX_MAX_LEN + 1);

-    int ret = split_uri_and_find_ops(typed_uri, (char*)&type, &uri, &ops);
+    int ret = split_uri_and_find_ops(typed_uri, type, &uri, &ops);
```

@mkow Do you want me to change like this, with the `__alloca()`?


<!-- Sent from Reviewable.io -->

2023-10-18 16:37 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`pal/src/pal_streams.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngzi8RL4YFJL3OvBO0f:-Nh2dPVv0q28qZ3Yni5M:b-qjjwat) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because the compiler complains:
```
../pal/src/pal_streams.c:87:49: warning: passing argument 2 of ‘split_uri_and_find_ops’ from incompatible pointer type [-Wincompatible-pointer-types]
   87 |     int ret = split_uri_and_find_ops(typed_uri, &type, &uri, &ops);
      |                                                 ^~~~~
      |                                                 |
      |                                                 char (*)[(sizetype)(__builtin_memcpy(&<U9090>, &({...})) + 1)]
../pal/src/pal_streams.c:40:64: note: expected ‘char *’ but argument is of type ‘char (*)[(sizetype)(__builtin_memcpy(&<U9090>, &({...})) + 1)]’
```

Alternatively to the current code, I can do this:
```diff
-    char type[URI_PREFIX_MAX_LEN + 1];
+    char* type = __alloca(URI_PREFIX_MAX_LEN + 1);

-    int ret = split_uri_and_find_ops(typed_uri, (char*)&type, &uri, &ops);
+    int ret = split_uri_and_find_ops(typed_uri, type, &uri, &ops);
```

@mkow Do you want me to change like this, with the `__alloca()`?
</blockquote></details>

No, just remove the ampersand and then the cast is not needed?


<!-- Sent from Reviewable.io -->

2023-10-19 09:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: 2 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/pal_streams.c` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-Ngzi8RL4YFJL3OvBO0f:-Nh6FHNSELmdOj8QXbn5:b-ntcmqe) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, just remove the ampersand and then the cast is not needed?
</blockquote></details>

Done, well, stupid me.
___
*[`pal/src/pal_streams.c` line 206 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgziQ2gEJvBE8Pxr5N6:-Nh6FJV2AlR4Tzcq8pp2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L206)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/pal_streams.c` line 390 at r1](https://reviewable.io/reviews/gramineproject/gramine/1607#-NgziVR74vGwmeC666W2:-Nh6FJng2RSVfR8sCxJk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/011220a2db065c56b7cec65dcfd0dc0b5ed48306/pal/src/pal_streams.c#L390)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-19 14:17 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-20 01:54 UTC, kailun-qin approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-20 11:09 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-10-20 12:15 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1607)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-20 14:23 UTC, merged