Fix misspells in python
gramineproject/gramine pull request #1613
Opened 2023-10-18 11:03 UTC by oshogbo

## Description of the changes 

* I think that the variable is with the key is called `path` not `key`, this results in the fallowing python error:
```
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/bin/gramine-sgx-sign", line 74, in <module>                                                                                                                                       
    main() # pylint: disable=no-value-for-parameter                                                                                                                                            
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__                                                                                                                  
    return self.main(*args, **kwargs)                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main                                                                                                                      
    rv = self.invoke(ctx)                                                                                                                                                                      
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke                    
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                             
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke                     
    return __callback(*args, **kwargs)                                                                                                                                                         
  File "/usr/bin/gramine-sgx-sign", line 48, in main                                                                                                                                           
    sigstruct.sign(sign_with_local_key, key)                                                                                                                                                   
  File "/app/install/lib/python3.11/site-packages/graminelibos/sigstruct.py", line 191, in sign 
    exponent_int, modulus_int, signature_int = do_sign_callback(data, *args, **kwargs)                                                                                                         
  File "/app/install/lib/python3.11/site-packages/graminelibos/sgx_sign.py", line 724, in sign_with_local_key
    return sign_with_private_key_from_pem_path(data, key)                                                                                                                                      
  File "/app/install/lib/python3.11/site-packages/graminelibos/sgx_sign.py", line 717, in sign_with_private_key_from_pem_path                                                                  
    with open(key, 'rb') as file:                                                                                                                                                              
NameError: name 'key' is not defined                                                           
```

* I think that the name of the function is misspelled:
```
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/bin/gramine-sgx-sign", line 74, in <module>                                                                                                                                       
    main() # pylint: disable=no-value-for-parameter                                                                                                                                            
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__                                                                                                                  
    return self.main(*args, **kwargs)                                                          
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main                      
    rv = self.invoke(ctx)                                                                                                                                                                      
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke                                                                                                                    
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                             
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke                                                                                                                     
    return __callback(*args, **kwargs)                                                                                                                                                         
  File "/usr/bin/gramine-sgx-sign", line 48, in main                                                                                                                                           
    sigstruct.sign(sign_with_local_key, key)                                                                                                                                                   
  File "/app/install/lib/python3.11/site-packages/graminelibos/sigstruct.py", line 191, in sign                                                                                                
    exponent_int, modulus_int, signature_int = do_sign_callback(data, *args, **kwargs)         
  File "/app/install/lib/python3.11/site-packages/graminelibos/sgx_sign.py", line 724, in sign_with_local_key                                                                                  
    return sign_with_private_key_from_pem_path(data, key)                                      
  File "/app/install/lib/python3.11/site-packages/graminelibos/sgx_sign.py", line 718, in sign_with_private_key_from_pem_path                                                                  
    return sign_with_private_key_from_pem_file(data, file, passphrase)                                                                                                                         
  File "/app/install/lib/python3.11/site-packages/graminelibos/sgx_sign.py", line 690, in sign_with_private_key_from_pem_file                                                                  
    return sign_with_private_key(data, load_pem_private_key_from_file(file, passphrase))                                                                                                       
NameError: name 'load_pem_private_key_from_file' is not defined. Did you mean: 'load_private_key_from_pem_file'?                                                                               
```

2023-10-18 23:07 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-Nh41IJU1VUt0nEMyOPJ:b-5zplsw) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
> ```Python
>     """
> 
>     with open(key, 'rb') as file:
> ```

How did this even work before? Did anyone test this code before merging? This looks pretty bad...
@woju ^


<!-- Sent from Reviewable.io -->

2023-10-20 07:03 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @woju)

___
*[`-- commits` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-NhAsiDS-dneu4PTdBBd):*
Do we really need 5 one-line commits? I suggest to combine them into one commit with the title `[python,test,ci] Python code fixes reported by pylint`, and have a list of these separate issues in the commit body message.
___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhAtCi40rBTAXjtbU59:btezfph) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How did this even work before? Did anyone test this code before merging? This looks pretty bad...
@woju ^
</blockquote></details>

Can we add at least a fast & simple script to test this in our CI?


<!-- Sent from Reviewable.io -->

2023-10-23 10:49 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-NhAsiDS-dneu4PTdBBd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we really need 5 one-line commits? I suggest to combine them into one commit with the title `[python,test,ci] Python code fixes reported by pylint`, and have a list of these separate issues in the commit body message.
</blockquote></details>

What would you say to separate it as 2: [python] and [test,ci] ?
I think they are pretty different. One is basically broken functionality and the second is a "good practice". It might make more sense when somebody will do `git blame`.
What do you think?
___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhR89y44UG_d7s99thM:b-4cnvp3) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
> Can we add at least a fast & simple script to test this in our CI?
I can add it, but maybe as a separate PR? I would suggest not adding more to this PR as I would like to get it ASAP (as it seems to break the whole functionality), and adding a test will lengthen the review.


<!-- Sent from Reviewable.io -->

2023-10-23 11:24 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo and @woju)

___
*[`-- commits` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-NhAsiDS-dneu4PTdBBd):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What would you say to separate it as 2: [python] and [test,ci] ?
I think they are pretty different. One is basically broken functionality and the second is a "good practice". It might make more sense when somebody will do `git blame`.
What do you think?
</blockquote></details>

Ok, splitting into two commits sounds reasonable.
___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhRGgeQ9NF9BFJ4iTUP:b94whdq) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> Can we add at least a fast & simple script to test this in our CI?
I can add it, but maybe as a separate PR? I would suggest not adding more to this PR as I would like to get it ASAP (as it seems to break the whole functionality), and adding a test will lengthen the review.
</blockquote></details>

(Don't forget to add an empty line between the citation and your text :))

Ok, separate PR is good for me.


<!-- Sent from Reviewable.io -->

2023-10-26 09:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhfIY4j4PM1moaM1pqr:b8te33t) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

(Don't forget to add an empty line between the citation and your text :))

Ok, separate PR is good for me.
</blockquote></details>

I tested it, but might have refactored that as part of discussion "how we name things" (those functions). Something might have been lost in refactoring. Either way, my fault.


<!-- Sent from Reviewable.io -->

2023-10-26 09:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @oshogbo)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhfN05gBuPMmK4mbB9p:b-40fin1) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@oshogbo "Done" in which sense? I don't see a separate PR.


<!-- Sent from Reviewable.io -->

2023-10-26 10:21 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhfV3Sn0lhMsbgntlhD:bf440hd) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo "Done" in which sense? I don't see a separate PR.
</blockquote></details>

Done as this thread is solved. And we can get it merged. As nothing is blocking :)


<!-- Sent from Reviewable.io -->

2023-10-26 10:27 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @oshogbo)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NhfW_5C3-WqVFgPJ-fK:bfkwvsg) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done as this thread is solved. And we can get it merged. As nothing is blocking :)
</blockquote></details>

I was expecting a separate PR :( Or at least a GitHub issue, otherwise we'll forget.


<!-- Sent from Reviewable.io -->

2023-11-08 20:00 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`python/graminelibos/sgx_sign.py` line 717 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-Nh41IJU1VUt0nEMyOPI:-NikWJQ66l90mB8MOSGa:b-m3hvxq) ([raw file](https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/python/graminelibos/sgx_sign.py#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was expecting a separate PR :( Or at least a GitHub issue, otherwise we'll forget.
</blockquote></details>

I have added PR: https://github.com/gramineproject/gramine/pull/1646


<!-- Sent from Reviewable.io -->

2023-11-09 16:22 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2023-11-09 19:02 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-NhAsiDS-dneu4PTdBBd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, splitting into two commits sounds reasonable.
</blockquote></details>

@oshogbo This PR is ready for final rebase and merge -- could you do this split into two commits now?


<!-- Sent from Reviewable.io -->

2023-11-09 19:25 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/1613#-NhAsiDS-dneu4PTdBBd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@oshogbo This PR is ready for final rebase and merge -- could you do this split into two commits now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-09 19:54 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/1613#-NipdRH1DtZRMRfKkwD3):*
Typo: `addresses`

I'm not blocking as this is a small thing. But if @mkow wants, please fix and hard-push it agian, I'll re-approve in the morning and merge then.


<!-- Sent from Reviewable.io -->

2023-11-10 02:00 UTC, kailun-qin approved these changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-10 07:47 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-10 08:32 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-11-13 00:50 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-13 06:44 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1613)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-13 06:45 UTC, merged