[tools] common/util.h: Make INFO and DBG print to stderr
gramineproject/gramine pull request #1624
Opened 2023-10-25 16:13 UTC by woju

See commit message.

## Description of the changes 

So I'm writing a tool that relies of `ra_tls_verify_*` libraries and it turns out that I need to write some output to stdout. The verifier library garbles the output.

## How to test this PR? 

Write an attestor, run it, check that status info from `libra_tls_*` is not being printed to stdout.

2023-10-26 09:43 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1624#-NhfMFav89HLSxvXPuOv:-NhfMFaw8TyfgSO_4U35:b-k9dtqq) (no related file):*
Please check the failed SGX pipelines. I guess they have tests that expect some info on STDOUT, not STDERR.

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1624#-NhfMUOB6TS7a5KlLaPp):*
What is this `that INFO`? I can't parse your sentence.


<!-- Sent from Reviewable.io -->

2023-10-26 11:51 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-10-31 11:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1624)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1624#-NhfMFav89HLSxvXPuOv:-Ni4OevA2BO-A0ybdfYd:b-mg2k6x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please check the failed SGX pipelines. I guess they have tests that expect some info on STDOUT, not STDERR.
</blockquote></details>

I looked at the failing SGX pipelines. As guessed, the problem is that the test waits on STDOUT, not STDERR:
```
**18:12:35**  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ TC\_50\_EncryptedFiles.test\_000\_gen\_key \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
**18:12:35**  test_enc.py:71: in test_000_gen_key
**18:12:35**      self.assertIn('Wrap key saved to: ' + key_path, stdout)
**18:12:35**  E   AssertionError: 'Wrap key saved to: tmp/tmpkey' not found in ''
```

___


<!-- Sent from Reviewable.io -->

2023-10-31 11:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1624)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1624#-NhfMFav89HLSxvXPuOv:-Ni4RNKM2_xXrk193_Wb:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I looked at the failing SGX pipelines. As guessed, the problem is that the test waits on STDOUT, not STDERR:
```
**18:12:35**  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ TC\_50\_EncryptedFiles.test\_000\_gen\_key \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
**18:12:35**  test_enc.py:71: in test_000_gen_key
**18:12:35**      self.assertIn('Wrap key saved to: ' + key_path, stdout)
**18:12:35**  E   AssertionError: 'Wrap key saved to: tmp/tmpkey' not found in ''
```
</blockquote></details>

Done

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1624#-NhfMUOB6TS7a5KlLaPp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `that INFO`? I can't parse your sentence.
</blockquote></details>

Done, rephrased


<!-- Sent from Reviewable.io -->

2023-10-31 11:40 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1624)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-31 14:32 UTC, merged