Check old and new path are same in rename system call
gramineproject/gramine pull request #1627
Opened 2023-10-26 13:08 UTC by amathew3

## Description of the changes 
Gramine implementation of rename system call is failing if the old and new  path are same. 
Seen this issue while graminizing the harshulthakur/voice:latestforgsc  docker image.

## How to test this PR? 
 1. create a regular file, eg: touch /home/intel/test.txt
 2. Graminize and run the below sample python code 

import os
file = input('Enter a file name: ')
path = os.replace(file, file)
print("File %s is renamed successfully" % file)

2023-10-26 23:09 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @amathew3)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhiDScA1jLUxLnrZdfl:-NhiDScA1jLUxLnrZdfm:bedzu43) (no related file):*
@amathew3: Please use proper Markdown formatting when pasting code snippets on GitHub.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhiDgDZ-SsxooZQKh7f):*




_Suggestion:_
```
[LibOS] Fix handling of oldpath == newpath in rename syscall
```


<!-- Sent from Reviewable.io -->

2023-10-27 01:19 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @amathew3)



<!-- Sent from Reviewable.io -->

2023-10-27 06:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhjtRbVCVHy1PI5L2IA:-NhjtRbVCVHy1PI5L2IB:b1buuz3) (no related file):*
Yep, legitimate issue.

Man page `man 2 rename` mentions this case explicitly:

> If oldpath and newpath are existing hard links referring to the same file, then rename() does nothing, and  returns a success status.

I added a quick LibOS regression test for this case. Without this PR, it prints an error:
```
[0.002] test_rename_same_file...
[0.002] rename_unlink: rename: Invalid argument
```

With this PR, the test passes.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhiDgDZ-SsxooZQKh7f):*
Done, plus added sign-off line.


<!-- Sent from Reviewable.io -->

2023-10-27 07:00 UTC, dimakuv commented
Jenkins, test this please

2023-10-28 23:04 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @amathew3)

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-NhsWm8W5w4v92jdDcnY:b-o3cpcq) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
> ```C
>         err(1, "close %s", path);
> 
>     if (unlink(path) == -1)
> ```

Can we do `!= 0` instead? Just to fail if it returns some garbage values.


<!-- Sent from Reviewable.io -->

2023-10-30 07:45 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-NhzXdzW6Dsdu8JHF-2D:b-kbblha) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we do `!= 0` instead? Just to fail if it returns some garbage values.
</blockquote></details>


Done. Here and in other places in this file.


<!-- Sent from Reviewable.io -->

2023-10-30 07:46 UTC, dimakuv commented
Jenkins, test this please

2023-10-30 08:30 UTC, kailun-qin reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-NhzghBICkA-2aCcMjwR:b-58sbnx) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Here and in other places in this file.
</blockquote></details>

But our `CHECK()` macro (for regression tests) checks w/ `-1` only (pls see https://github.com/gramineproject/gramine/blob/f1781a0f92167a2fe9921502d8eabb613dacf43f/libos/test/regression/common.h#L18-L24)?


<!-- Sent from Reviewable.io -->

2023-10-30 09:41 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-NhzxKp_2t3Uc1vUhaKX:b-bei6pn) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But our `CHECK()` macro (for regression tests) checks w/ `-1` only (pls see https://github.com/gramineproject/gramine/blob/f1781a0f92167a2fe9921502d8eabb613dacf43f/libos/test/regression/common.h#L18-L24)?
</blockquote></details>

Fair enough, but I'd change it in a separate PR (the one that would refactor our tests)


<!-- Sent from Reviewable.io -->

2023-10-30 11:07 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-Ni-G3FO4a4uh5xcMdfM:b-5n3dni) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough, but I'd change it in a separate PR (the one that would refactor our tests)
</blockquote></details>

Sure, I'm fine w/ it.


<!-- Sent from Reviewable.io -->

2023-10-30 11:47 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/rename_unlink.c` line 117 at r2](https://reviewable.io/reviews/gramineproject/gramine/1627#-NhsWm8W5w4v92jdDcnX:-Ni-OdvPAKWbyLxg1LvW:brxp9sd) ([raw file](https://github.com/gramineproject/gramine/blob/b63f344290f3c13fa5af337281ef3f4702daa1c4/libos/test/regression/rename_unlink.c#L117)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sure, I'm fine w/ it.
</blockquote></details>

Sounds good!


<!-- Sent from Reviewable.io -->

2023-10-30 11:54 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1627#-Ni-PkH-DpdxajXnpEm-:-Ni-PkH-DpdxajXnpEm0:b-36uf4j) (no related file):*
@amathew3: In the future, please create PRs from branches in `<your-nick>/<change-descr>` format, even if it's from your private repo - this makes it a bit easier for us to pull and rebase it before merging without polluting our local branch namespaces.
See https://gramine.readthedocs.io/en/latest/devel/contributing.html#branch-names.

___


<!-- Sent from Reviewable.io -->

2023-10-30 12:17 UTC, dimakuv commented
Jenkins, test this please

2023-10-30 12:18 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-30 12:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1627)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-30 23:42 UTC, merged