[LibOS,PAL] Support `EINPROGRESS` on non-blocking sockets connect
gramineproject/gramine pull request #1643
Opened 2023-11-07 14:11 UTC by dimakuv

## Description of the changes 

Previously, Gramine transformed `connect()` of non-blocking sockets into a blocking operation and thus never returned -EINPROGRESS. This led to the connect operation being very slow (waiting for a host timeout) if a remote peer is unresponsive.

This commit fixes this and adds a LibOS regression test; unfortunately the test must be run manually with special network settings to properly test the EINPROGRESS behavior.

Fixes #1641.

## How to test this PR? 

A new test was added, but please test it also manually as described in #1641.

2023-11-07 14:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_socket.c` line 652 at r1](https://reviewable.io/reviews/gramineproject/gramine/1643#-Nie79S53ASLMp1a-ReG:-Nie79S53ASLMp1a-ReH:b9qah13) ([raw file](https://github.com/gramineproject/gramine/blob/9e1e0c879bd6c47803de944640724c5198c64ff7/libos/src/sys/libos_socket.c#L652)):*
> ```C
>     bool has_sendtimeout_set = !!sock->sendtimeout_us;
> 
>     ret = -((ssize_t)sock->last_error);
> ```

FYI: I detected this bug while testing this sockets subsystem (incorrect type expansion, leading to `ret` having a positive value). It is unrelated to this PR.
___
*[`libos/src/sys/libos_socket.c` line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/1643#-Nie7LBv-xo3wr4qCmsp:-Nie7LBv-xo3wr4qCmsq:b9qah13) ([raw file](https://github.com/gramineproject/gramine/blob/9e1e0c879bd6c47803de944640724c5198c64ff7/libos/src/sys/libos_socket.c#L815)):*
> ```C
>     lock(&sock->lock);
>     bool has_recvtimeout_set = !!sock->receivetimeout_us;
>     ret = -((ssize_t)sock->last_error);
> ```

FYI: I detected this bug while testing this sockets subsystem (incorrect type expansion, leading to `ret` having a positive value). It is unrelated to this PR.


<!-- Sent from Reviewable.io -->

2023-11-07 15:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 0 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieRHxZ4HTUGrMYLJIR:-NieRHxZ4HTUGrMYLJIS:bbr72wg) (no related file):*
Use an un-routable address 10.255.255.255 in the test.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieRVUGAPucY5fg0JFh:-NieRVUGAPucY5fg0JFi:b-iuln0n) (no related file):*
`send` and `recv` must return EAGAIN on sockets in CONNECTING state.

___


<!-- Sent from Reviewable.io -->

2023-11-07 16:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 0 of 20 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieWioT8oqIAZyubI4P:-NieWioU4dDkhe_96pmp:be9sx2z) (no related file):*
Add test for `poll` and for `epoll`. Note that `select()` is emulated by poll in Gramine anyway, so no sense in testing it.

___


<!-- Sent from Reviewable.io -->

2023-11-07 19:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieRHxZ4HTUGrMYLJIR:-NifAtsN50S8O8HVOTHH:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Use an un-routable address 10.255.255.255 in the test.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieRVUGAPucY5fg0JFh:-NifJpTs4Bd9uWxJF4HQ:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`send` and `recv` must return EAGAIN on sockets in CONNECTING state.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NieWioT8oqIAZyubI4P:-NifJq4NBPB3h5BnCQso:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add test for `poll` and for `epoll`. Note that `select()` is emulated by poll in Gramine anyway, so no sense in testing it.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-11-07 20:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 0 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifLZOV7WXLZsHAGV2q:-NifLZOV7WXLZsHAGV2r:bhbggne) (no related file):*
FYI: A couple links I found useful:
- https://stackoverflow.com/questions/17769964/linux-sockets-non-blocking-connect
- https://github.com/microsoft/WSL/issues/2412 (and other links from there)

___
___
*[`libos/src/sys/libos_epoll.c` line 690 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifLpw2B2rFj24w_3l9:-NifLpw39Vt0yPj9QyVL:befvrmy) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_epoll.c#L690)):*
> ```C
>                  */
>                 enum libos_sock_state state = __atomic_load_n(&items[i]->handle->info.sock.state,
>                                                               __ATOMIC_ACQUIRE);
> ```

I'm unsure here, that's a bit of a hack. Technically we should always take the lock `sock->lock` before accessing the `state` field (it's not supposed to be an atomic).

So I see three solutions here:
- Just take the lock immediately, don't play this dance with "check if state is CONNECTING in atomic manner for performance reasons". But perf will downgrade significantly I think...
- Keep like this. Technically, in real-world apps, the transition CONNECTING -> CONNECTED will happen only in one thread/case, so this hacky atomic load is fine.
- Introduce a new atomic field `bool sock->is_connecting`. It will be set to true when state is moved to CONNECTING, and then we'll do this atomic load but on `sock->is_connecting` instead of `sock->state`.
___
*[`libos/src/sys/libos_poll.c` line 229 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifMkB36VHmt79WanRm:-NifMkB36VHmt79WanRn:b-sbuib4) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_poll.c#L229)):*
> ```C
>              */
>             enum libos_sock_state state = __atomic_load_n(&libos_handles[i]->info.sock.state,
>                                                           __ATOMIC_ACQUIRE);
> ```

ditto (hacky atomic load?)
___
*[`libos/test/regression/tcp_einprogress.c` line 123 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifNV0f8UVHNzbPrvEk:-NifNV0f8UVHNzbPrvEl:b-kawxzl) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L123)):*
> ```C
>         CHECK(close(epfd));
>         pollout = !!(out_event.events & EPOLLOUT);
>     }
> ```

I think I need to extract the `ret == 0` case outside of these IFs. Otherwise it's complicated to read this `one interesting case`.
___
*[`libos/test/regression/test_libos.py` line 1432 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifNhYv1zRSTvgjYkku:-NifNhYv1zRSTvgjYkkv:b-47alr5) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1432)):*
> ```Python
>     def test_308_socket_tcp_einprogress_unresponsive_epoll(self):
>         # Test unresponsive peer: first connect() returns EINPROGRESS, then poll/epoll times out
>         # because the connection cannot be established
> ```

Oops, must remove this copy-pasted comment, it's redundant


<!-- Sent from Reviewable.io -->

2023-11-08 02:59 UTC, kailun-qin requested changes
> Reviewed 17 of 20 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifP6dEAc87nPdNqFQi:-NigrZEW2LTm7A-lks8r:b-2gj0s0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Repeating here, for manual testing of `tcp_einprogress`:

- Drop  SYN packets on 127.0.0.1:12345
   ```
   sudo iptables -A OUTPUT -p tcp --tcp-flags SYN,ACK,FIN,RST SYN -d 127.0.0.1 --dport 12345 -j DROP
   ```

- Re-establish all packets on 127.0.0.1:12345
   ```
   sudo iptables -D OUTPUT -p tcp --tcp-flags SYN,ACK,FIN,RST SYN -d 127.0.0.1 --dport 12345 -j DROP
   ```

Also, change `TIMEOUT_MS` to e.g. 10 seconds for manual testing.
</blockquote></details>

Should we point readers to these instructions/steps of running manual tests somewhere in the code/comment? (otherwise they could only search for the original issue/PR)

___
___
*[`libos/src/sys/libos_epoll.c` line 690 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifLpw2B2rFj24w_3l9:-Nig_NSV6OJlLgS6k8cr:b-423hi4) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_epoll.c#L690)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm unsure here, that's a bit of a hack. Technically we should always take the lock `sock->lock` before accessing the `state` field (it's not supposed to be an atomic).

So I see three solutions here:
- Just take the lock immediately, don't play this dance with "check if state is CONNECTING in atomic manner for performance reasons". But perf will downgrade significantly I think...
- Keep like this. Technically, in real-world apps, the transition CONNECTING -> CONNECTED will happen only in one thread/case, so this hacky atomic load is fine.
- Introduce a new atomic field `bool sock->is_connecting`. It will be set to true when state is moved to CONNECTING, and then we'll do this atomic load but on `sock->is_connecting` instead of `sock->state`.
</blockquote></details>

I vote for solution #3 which removes the hacky w/o introduing much complexity (IMO).
___
*[`libos/src/sys/libos_socket.c` line 31 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigPkfBBiGjoIEhW8NT:-NigPkfBBiGjoIEhW8NU:b-p6zsxm) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_socket.c#L31)):*
> ```C
>  *  |     |                        |         (if it was bound)  |            |
>  *  |     | connect()              |                            |            |
>  *  |     |                        +         select()/poll()/   |            |
> ```

why is this change?



_Code quote:_
```C
+
```
___
*[`libos/src/sys/libos_socket.c` line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigY1VJ1o6D5JZ-D4kH:-NigY1VJ1o6D5JZ-D4kI:b6utk20) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_socket.c#L33)):*
> ```C
>  *  |     |                        +         select()/poll()/   |            |
>  *  |     |                        V            epoll()         +            |
>  *  |     +---------------------> CONNECTING ---------------- CONNECTED <----+
> ```

Should we note that the `CONNECTING` state only applies to non-blocking sockets? (Otherwise the `selcect()`/`poll()`/`epoll()` transition doesn't make that much sense)



_Code quote:_
```C
CONNECTING
```
___
*[`libos/test/regression/tcp_einprogress.c` line 28 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-Nigc7lGBy8WAW3zy4mN:-Nigc7lGBy8WAW3zy4mO:bq59qm9) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L28)):*
> ```C
> 
>     if (argc != 3)
>         ERR("Usage: %s <IP address> poll|epoll\n(use 127.0.0.1 for responsive peer, 10.255.255.255"
> ```

Do we need `ERR()` here?



_Code quote:_
```C
ERR(
```
___
*[`libos/test/regression/tcp_einprogress.c` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigcI319jiEtq-rQcRd:-NigcI319jiEtq-rQcRe:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L32)):*
> ```C
> 
>     if (strcmp(argv[2], "poll") && strcmp(argv[2], "epoll"))
>         ERR("Usage: %s <IP address> poll|epoll\nerror: only poll/epoll allowed", argv[0]);
> ```

ditto
___
*[`libos/test/regression/test_libos.py` line 1415 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigV15t3zvJ7Xe0qIJD:-NigV15t3zvJ7Xe0qIJE:b-q312pj) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1415)):*
> ```Python
> 
>     def test_305_socket_tcp_einprogress_responsive_poll(self):
>         # Test responsive peer: first connect() returns EINPROGRESS, then poll/epoll immediately
> ```

Should we move the comment out of `def` so that it serves both tests.
___
*[`libos/test/regression/test_libos.py` line 1425 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigVP9h1sdPtwin9SbZ:-NigVP9h1sdPtwin9Sb_:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1425)):*
> ```Python
> 
>     def test_307_socket_tcp_einprogress_unresponsive_poll(self):
>         # Test unresponsive peer: first connect() returns EINPROGRESS, then poll/epoll times out
> ```

ditto
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1429 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigWW8d2IFuiHs5kSwU:-NigWW8d2IFuiHs5kSwV:b-xqslwa) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/enclave_ocalls.c#L1429)):*
> ```C
> }
> 
> int ocall_connect_simple(int fd, struct sockaddr_storage* addr, size_t* addrlen) {
> ```

I understand why we don't change `ocall_connect()`, but still find it a bit weird :).



_Code quote:_
```C
ocall_connect_simple
```
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1460 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigTxlxEYirhH7HjyI4:-NigTxlxEYirhH7HjyI5:b-scmw7c) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/enclave_ocalls.c#L1460)):*
> ```C
>         if (ret != -EACCES && ret != -EPERM && ret != -EADDRINUSE && ret != -EADDRNOTAVAIL
>                 && ret != -EAFNOSUPPORT && ret != -EAGAIN && ret != -EALREADY && ret != -EBADF
>                 && ret != -ECONNREFUSED && ret != -EINPROGRESS && ret != -EISCONN
> ```

I think we can remove this now



_Code quote:_
```C
&& ret != -EINPROGRESS
```
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 514 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigXAUE5U0-nDARxaRy:-NigXAUE5U0-nDARxaRz:bnmf90k) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/host_ocalls.c#L514)):*
> ```C
> 
>     /* Connect succeeded or in progress (EINPROGRESS); in both cases retrieve local name -- host
>      * Linux binds the socket to address even in case of EINPROGRESS */
> ```

pls add a `.` at the end of a sentence
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 275 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigTUnN2dMEm41EvqkD:-NigTUnN2dMEm41EvqkE:b-7roxra) ([raw file](https://github.com/gramineproject/gramine/blob [...]

2023-11-08 03:01 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/sys/libos_epoll.c` line 690 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifLpw2B2rFj24w_3l9:-Nigrwt2DcibcWZnkmU4:bpdp546) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_epoll.c#L690)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I vote for solution #3 which removes the hacky w/o introduing much complexity (IMO).
</blockquote></details>

oops... sorry for the unintentional link -- I meant the 3rd option


<!-- Sent from Reviewable.io -->

2023-11-08 08:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 11 of 20 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifP6dEAc87nPdNqFQi:-Nihp-Sx3G68sQSsyaEY:bo93jh1) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we point readers to these instructions/steps of running manual tests somewhere in the code/comment? (otherwise they could only search for the original issue/PR)
</blockquote></details>

I think it's not necessary. Users can figure out these commands themselves, if they really want to. Otherwise, they will do some GitHubbing and will find these instructions.

I put it here mainly for reviewers convenience, if they want to test these things manually.

___
___
*[`libos/src/sys/libos_epoll.c` line 690 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifLpw2B2rFj24w_3l9:-Niht4Nq78nGtE2YS9aK:bbe1gq0) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_epoll.c#L690)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

oops... sorry for the unintentional link -- I meant the 3rd option
</blockquote></details>

Done. Did solution 3.
___
*[`libos/src/sys/libos_poll.c` line 229 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifMkB36VHmt79WanRm:-Niht8cG7IOz0hgRUOR7:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_poll.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (hacky atomic load?)
</blockquote></details>

Done
___
*[`libos/src/sys/libos_socket.c` line 31 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigPkfBBiGjoIEhW8NT:-Niht_2S0R69UGn5yp73:b-gmwunw) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_socket.c#L31)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

why is this change?
</blockquote></details>

Done. That's because I use AsciiFlow to draw these diagrams, and AsciiFlow automatically replaced such places. Fixed manually now.
___
*[`libos/src/sys/libos_socket.c` line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigY1VJ1o6D5JZ-D4kH:-Nihu6-OES6S-pDOPKiL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/src/sys/libos_socket.c#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we note that the `CONNECTING` state only applies to non-blocking sockets? (Otherwise the `selcect()`/`poll()`/`epoll()` transition doesn't make that much sense)
</blockquote></details>

Done.
___
*[`libos/test/regression/tcp_einprogress.c` line 28 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-Nigc7lGBy8WAW3zy4mN:-NihvIJeBAbrMVvZi2X5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L28)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we need `ERR()` here?
</blockquote></details>

Done.
___
*[`libos/test/regression/tcp_einprogress.c` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigcI319jiEtq-rQcRd:-NihvIdT4WhfCmA3fyp9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L32)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/tcp_einprogress.c` line 123 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifNV0f8UVHNzbPrvEk:-NihyA9RDT0X2cSHaErm:b1181z6) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/tcp_einprogress.c#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think I need to extract the `ret == 0` case outside of these IFs. Otherwise it's complicated to read this `one interesting case`.
</blockquote></details>

Done. Also refactored other places in this test a bit.
___
*[`libos/test/regression/test_libos.py` line 1415 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigV15t3zvJ7Xe0qIJD:-NihyRD28icLTmSLnkuM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1415)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we move the comment out of `def` so that it serves both tests.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1425 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigVP9h1sdPtwin9SbZ:-NihyRZ3CDaz7C6GSP4I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1425)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1432 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifNhYv1zRSTvgjYkku:-NihySDW-UTZrUe1pfD3:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/libos/test/regression/test_libos.py#L1432)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, must remove this copy-pasted comment, it's redundant
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1429 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigWW8d2IFuiHs5kSwU:-NihpOChDxSTaS-KibRO:bux7zkp) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/enclave_ocalls.c#L1429)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I understand why we don't change `ocall_connect()`, but still find it a bit weird :).
</blockquote></details>

Do you mean our use of **two** connect functions: `ocall_connect()` and `ocall_connect_simple()`? Yes, it's a bit weird, and maybe in the future we'll refactor to have just one generic OCALL.
- `ocall_connect()` is currently used only for pipe emulation in Gramine (using host UNIX sockets).
- `ocall_connect_simple()` is currently used by TCP/UDP sockets.

The main difference between them is that `ocall_connect()` hides under the hood a bunch of operations: `socket()` -> `bind()` -> `connect()`. This is required because emulated pipes don't have the notion of "create, assign an address and connect to another address", so Gramine has to emulate a single "pipe create" with this series of operations.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1460 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigTxlxEYirhH7HjyI4:-Nihyftz2DdT5qWL4hbq:bc908h5) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/enclave_ocalls.c#L1460)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think we can remove this now
</blockquote></details>

Done. I was a bit reluctant, as we could easily miss this check if we ever refactor EINPROGRESS logic again. But I agree, it looks weird to  [...]

2023-11-09 08:23 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NifP6dEAc87nPdNqFQi:-Nin9BAm67j0UgsVjcCw:b-myrwz5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it's not necessary. Users can figure out these commands themselves, if they really want to. Otherwise, they will do some GitHubbing and will find these instructions.

I put it here mainly for reviewers convenience, if they want to test these things manually.
</blockquote></details>

Sure, I'm fine w/ this.

___
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1429 at r3](https://reviewable.io/reviews/gramineproject/gramine/1643#-NigWW8d2IFuiHs5kSwU:-Nin9bGh-rOVr-TbWzje:b75bij7) ([raw file](https://github.com/gramineproject/gramine/blob/3fdcd9b7d0769330a830cac84727534bfe9ee086/pal/src/host/linux-sgx/enclave_ocalls.c#L1429)):*
> Do you mean our use of **two** connect functions: `ocall_connect()` and `ocall_connect_simple()`? Yes, it's a bit weird, and maybe in the future we'll refactor to have just one generic OCALL.

Yes :).


<!-- Sent from Reviewable.io -->

2023-11-16 23:09 UTC, mkow requested changes
> Reviewed 8 of 20 files at r1, 4 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, 11 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjNSB4KD2HcnR0RnCJ7:-NjNSB4KD2HcnR0RnCJ8:b-xmj8o0) (no related file):*
> unfortunately the test must be run manually with special network settings to properly test the EINPROGRESS behavior.

This test passes for me without changing anything in iptables. Why? Is this intended? The description of the PR seem to suggest that it should fail then?

___
___
*[`libos/include/libos_handle.h` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjOLdJMBgUVxyabuI2T:-NjOLdJMBgUVxyabuI2U:bjdibjs) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/include/libos_handle.h#L103)):*
> ```objc
>     unsigned int last_error;
>     /* This field is an atomically-accessed version of the SOCK_CONNECTING state (for perf). */
>     bool connection_in_progress;
> ```

(otherwise it has a slightly different meaning and can be read as "it's still connected")



_Suggestion:_
```objc
bool connecting_in_progress;
```
___
*[`libos/src/net/ip.c` line 227 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjOMFC2CEXNkeb-ncvM:-NjOMFC3CSZ2eFlFRFf1:bs7dvac) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/net/ip.c#L227)):*
> ```C
>     if (ret < 0) {
>         if (ret == -PAL_ERROR_CONNFAILED) {
>             /* can't use pal_to_unix_errno() because it translates to ECONNRESET */
> ```

Why not change `pal_to_unix_errno()` translation instead? Does it break some other places?
___
*[`libos/src/net/ip.c` line 232 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjON6XP5BHUN08XJifs:-NjON6XP5BHUN08XJift:b-xtoc4g) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/net/ip.c#L232)):*
> ```C
>             assert(handle->flags & O_NONBLOCK);
>             ret = pal_to_unix_errno(ret);
>             goto out;
> ```

This execution path later uses `PalSocketConnect()`'s output (`pal_local_addr`), despite the function failure. Or at least it seems that it can use it? Isn't it uninitialized then?
___
*[`libos/src/sys/libos_epoll.c` line 676 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPLtT89dFIddEDT_YL:-NjPLtT89dFIddEDT_YM:b-nu74pb) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L676)):*
> ```C
>             }
> 
>             if (pal_ret_events[i] & PAL_WAIT_WRITE && items[i]->handle->type == TYPE_SOCK) {
> ```

Only write? What about reading?
___
*[`libos/src/sys/libos_epoll.c` line 677 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPM8gN1ZZ-DO5CR7YO:-NjPM8gN1ZZ-DO5CR7YP:bjs0nq7) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L677)):*
> ```C
> 
>             if (pal_ret_events[i] & PAL_WAIT_WRITE && items[i]->handle->type == TYPE_SOCK) {
>                 /*
> ```

Shouldn't this whole logic be a function in the socket code? We wouldn't have that big copy-paste then, and the socket-related logic would be in socket sources, not in epoll sources.
___
*[`libos/test/regression/tcp_einprogress.c` line 102 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKqsRu59TB9gG2YrSX:-NjKqsRu59TB9gG2YrSY:b-577la) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/tcp_einprogress.c#L102)):*
> ```C
>     if (bytes != -1 || errno != EAGAIN) {
>         ERR("[after EINPROGRESS] expected send to fail with EAGAIN but failed with %s",
>             strerror(errno));
> ```

This can also be reached if `send()` succeeded.
___
*[`libos/test/regression/tcp_einprogress.c` line 108 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKr2H66irOM1d3Riys:-NjKr2H66irOM1d3Riyt:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/tcp_einprogress.c#L108)):*
> ```C
>     if (bytes != -1 || errno != EAGAIN) {
>         ERR("[after EINPROGRESS] expected recv to fail with EAGAIN but failed with %s",
>             strerror(errno));
> ```

ditto
___
*[`libos/test/regression/test_libos.py` line 1415 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKsZOu20KlkeBpiEwv:-NjKsZOu20KlkeBpiEww:b-dxws2q) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/test_libos.py#L1415)):*
> ```Python
> 
>     # Two tests for a responsive peer: first connect() returns EINPROGRESS, then poll/epoll
>     # immediately returns because the connection is quickly established
> ```

Is it? There's nothing listening on this port on localhost...? The assert message seems to be correct though.



_Code quote:_
```Python
because the connection is quickly established
```
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 270 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPMxn72Bq1Ra8-2f8n:-NjPMxn72Bq1Ra8-2f8o:bctyc3f) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/pal/src/host/linux-sgx/pal_sockets.c#L270)):*
> ```C
> 
>     int ret = ocall_connect_simple(handle->sock.fd, &sa_storage, &linux_addrlen);
>     if (ret < 0 && ret != -EINPROGRESS) {
> ```

This shouldn't be allowed for non-blocking sockets (this probably should be verified in the ocall wrapper, as we do with other return values).



_Code quote:_
```C
ret != -EINPROGRESS
```
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 277 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPNH-H7TsWewIHXaU0:-NjPNH-IDDQAMB4llfyB:b-1u640c) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/pal/src/host/linux-sgx/pal_sockets.c#L277)):*
> ```C
>      * retrieved, must verify it. */
>     if (out_local_addr) {
>         int verify_ret = verify_ip_addr(handle->sock.domain, &sa_storage, linux_addrlen);
> ```

This is pretty bad, everywhere we use the convention that if a function failed, then the arg-returned values are undefined. Here it's the same, except for one specific error... This breaks the global convention we're using everywhere.


<!-- Sent from Reviewable.io -->

2023-11-17 07:37 UTC, vasanth-intel commented
Just FYI. We executed `Redis` and `Memcached` workloads on the PR to check if performance is impacted or not. We did not observe any regressions on perf front.

2023-11-17 08:34 UTC, dimakuv reviewed
Thank you @vasanth-intel ,this is really helpful!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643#-:-NjRP4CD-lEt1RGV3cQ4:b-4xxzn8)* status: all files reviewed, 11 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjNSB4KD2HcnR0RnCJ7:-NjRPXO6AeKVHp-5ZtPU:b90bz1f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> unfortunately the test must be run manually with special network settings to properly test the EINPROGRESS behavior.

This test passes for me without changing anything in iptables. Why? Is this intended? The description of the PR seem to suggest that it should fail then?
</blockquote></details>

Oops, I thought I fixed the PR description everywhere (e.g., I fixed the "How to test this PR?" section). Apparently forgot to change this text too.

___


<!-- Sent from Reviewable.io -->

2023-11-17 11:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 4 of 27 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjNSB4KD2HcnR0RnCJ7:-NjRQEBpBuUzCppx3Hrh:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, I thought I fixed the PR description everywhere (e.g., I fixed the "How to test this PR?" section). Apparently forgot to change this text too.
</blockquote></details>

Done

___
___
*[`libos/include/libos_handle.h` line 103 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjOLdJMBgUVxyabuI2T:-NjRU3i2CR2zN_P5OnFC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/include/libos_handle.h#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(otherwise it has a slightly different meaning and can be read as "it's still connected")
</blockquote></details>

Done.
___
*[`libos/src/net/ip.c` line 227 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjOMFC2CEXNkeb-ncvM:-NjRUPul1E9TiaWpoS8t:b-g39x6z) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/net/ip.c#L227)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not change `pal_to_unix_errno()` translation instead? Does it break some other places?
</blockquote></details>

Yes, it will break other places. Please note that it's not my change -- this was like this before this PR.

See https://github.com/search?q=repo%3Agramineproject%2Fgramine%20PAL_ERROR_CONNFAILED&type=code

In particular, this is the "other differing" code: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/net/unix.c#L240-L244

As you can see, `PAL_ERROR_CONNFAILED` has two meanings:
1. `ECONNREFUSED` for TCP/UDP sockets
2. `ENOENT` for UNIX sockets

(Why? That's because UNIX sockets are "like files" in Linux, but we emulate them as pipes inside PAL. So we have a mismatch in what "connection failed" means.)
___
*[`libos/src/net/ip.c` line 232 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjON6XP5BHUN08XJifs:-NjRpmqf-fbZTR1xeSuj:b-v39ufv) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/net/ip.c#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This execution path later uses `PalSocketConnect()`'s output (`pal_local_addr`), despite the function failure. Or at least it seems that it can use it? Isn't it uninitialized then?
</blockquote></details>

Done.

You already realized it yourself upon finishing the review, but just to reiterate: yes, POSIX/Linux considers `EINPROGRESS` as a **success of the connect operation**, even though it returns an error code. This is an odd semantics, and in the first revision of my PR, I inherited this semantics.

Now I modified the PR to have "sane" semantics, and propagate the "connecting-in-progress" condition in a separate boolean variable.

This by the way allowed me to remove the now-unused `PAL_ERROR_INPROGRESS`.
___
*[`libos/src/sys/libos_epoll.c` line 676 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPLtT89dFIddEDT_YL:-NjRVkgA9rx1-LCY0hMn:bwof7na) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L676)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Only write? What about reading?
</blockquote></details>

The man pages instruct the application to perform select/poll/epoll with the POLLOUT event:

```
   EINPROGRESS
          The socket is nonblocking and the connection cannot be
          completed immediately.  (UNIX domain sockets failed with
          EAGAIN instead.)  It is possible to select(2) or poll(2)
          for completion by selecting the socket for writing.  After
          select(2) indicates writability, use getsockopt(2) to read
          the SO_ERROR option at level SOL_SOCKET to determine
          whether connect() completed successfully (SO_ERROR is
          zero) or unsuccessfully (SO_ERROR is one of the usual
          error codes listed here, explaining the reason for the
          failure).
```

Using the read (POLLIN) event doesn't lead to anything, so we don't take it into account here.
___
*[`libos/src/sys/libos_epoll.c` line 677 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPM8gN1ZZ-DO5CR7YO:-NjRboToEXClF3GUEMm_:b734ri9) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L677)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this whole logic be a function in the socket code? We wouldn't have that big copy-paste then, and the socket-related logic would be in socket sources, not in epoll sources.
</blockquote></details>

Done, yes, looks much better now.
___
*[`libos/test/regression/tcp_einprogress.c` line 102 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKqsRu59TB9gG2YrSX:-NjRWKVrAaxfeY4GBmYX:b1t56sn) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/tcp_einprogress.c#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This can also be reached if `send()` succeeded.
</blockquote></details>

Done. I hope I understood you correctly. Fixed also all other such places.
___
*[`libos/test/regression/tcp_einprogress.c` line 108 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKr2H66irOM1d3Riys:-NjRWS_0-MRAj3gI1WAL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/tcp_einprogress.c#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1415 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjKsZOu20KlkeBpiEwv:-NjRXEwaAemGKdvd4WSF:bitca1n) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/test/regression/test_libos.py#L1415)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is it? There's nothing listening on this port on localhost...? The assert message seems to be correct though.
</blockquote></details>

Done. Oops, a typo.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 270 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPMxn72Bq1Ra8-2f8n:-NjRlVVx-kBLpwgWU-nA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/pal/src/host/linux-sgx/pal_sockets.c#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This shouldn't be allowed for non-blocking sockets (this probably should be verified in the ocall wrapper, as we do with other return values).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_sockets.c` line 277 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPNH-H7TsWewIHXaU0:-NjRi8Sv57SzRUWtIEa9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/pal/src/host/linux-sgx/pal_sockets.c#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquot [...]

2023-11-22 22:53 UTC, mkow requested changes
> Reviewed 1 of 9 files at r4, 23 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/net/ip.c` line 227 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjOMFC2CEXNkeb-ncvM:-NjsUmFu6I_q7v-TwtdA:btbgp51) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/net/ip.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it will break other places. Please note that it's not my change -- this was like this before this PR.

See https://github.com/search?q=repo%3Agramineproject%2Fgramine%20PAL_ERROR_CONNFAILED&type=code

In particular, this is the "other differing" code: https://github.com/gramineproject/gramine/blob/d052d1825ff19e5c9542c08b8fcd6fab90da9acd/libos/src/net/unix.c#L240-L244

As you can see, `PAL_ERROR_CONNFAILED` has two meanings:
1. `ECONNREFUSED` for TCP/UDP sockets
2. `ENOENT` for UNIX sockets

(Why? That's because UNIX sockets are "like files" in Linux, but we emulate them as pipes inside PAL. So we have a mismatch in what "connection failed" means.)
</blockquote></details>

I see, looks good then.
___
*[`libos/src/net/ip.c` line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjsoNpZ0WPnGL296Old:-NjsoNpZ0WPnGL296Ole:b-5bncmt) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/net/ip.c#L250)):*
> ```C
>     bool inprogress_unused;
>     int ret = PalSocketConnect(sock->pal_handle, &pal_ip_addr, /*local_addr=*/NULL,
>                                &inprogress_unused);
> ```

I think I forgot it, why do we have this weird way of disconnecting instead of just having `PalSocketDisconnect()` with simpler arguments?
___
*[`libos/src/sys/libos_epoll.c` line 676 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPLtT89dFIddEDT_YL:-NjsowI27ZVRNh-f1TMU:b-auaz69) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L676)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The man pages instruct the application to perform select/poll/epoll with the POLLOUT event:

```
   EINPROGRESS
          The socket is nonblocking and the connection cannot be
          completed immediately.  (UNIX domain sockets failed with
          EAGAIN instead.)  It is possible to select(2) or poll(2)
          for completion by selecting the socket for writing.  After
          select(2) indicates writability, use getsockopt(2) to read
          the SO_ERROR option at level SOL_SOCKET to determine
          whether connect() completed successfully (SO_ERROR is
          zero) or unsuccessfully (SO_ERROR is one of the usual
          error codes listed here, explaining the reason for the
          failure).
```

Using the read (POLLIN) event doesn't lead to anything, so we don't take it into account here.
</blockquote></details>

I'm not sure if this implies that this is the only way of checking it. What if someone connects and then polls for read, because in that specific protocol it's the server which sends the data first?
___
*[`libos/src/sys/libos_epoll.c` line 678 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjspPtkCV799FcHsQ1T:-NjspPtl1AlIwTHj_UDz:bm46r8i) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_epoll.c#L678)):*
> ```C
> 
>             if (items[i]->handle->type == TYPE_SOCK) {
>                 check_connect_inprogress_on_poll(items[i]->handle, pal_ret_events[i]);
> ```

Wouldn't the `pal_ret_events[i]` check be clearer and simpler if it was here? _This_ is the place which checks the conditions when to re-check the state anyways, and now this checking is split between two places and you need an additional argument in `check_connect_inprogress_on_poll()`.
___
*[`libos/src/sys/libos_poll.c` line 216 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjspqM26avAdu_-IDhd:-NjspqM26avAdu_-IDhe:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_poll.c#L216)):*
> ```C
>             fds[i].revents |= fds[i].events & (POLLOUT | POLLWRNORM);
> 
>         if (libos_handles[i]->type == TYPE_SOCK) {
> ```

ditto
___
*[`libos/src/sys/libos_socket.c` line 96 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt10GP4XTQizLEHXtY:-Njt10GP4XTQizLEHXtZ:b-5wx1py) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L96)):*
> ```C
>      * SOCK_CONNECTED state and clear SO_ERROR.
>      *
>      * This is only relevant if POLLOUT event was requested. See `man 2 connect`, EINPROGRESS case.
> ```

Just to not forget: if we decide to wait for more, then this will also need a change (and it's easy to miss).
___
*[`libos/src/sys/libos_socket.c` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt1bVuBdWbM1g8n6-H:-Njt1bVuBdWbM1g8n6-I:bgw1puo) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L114)):*
> ```C
>     if (sock->state != SOCK_CONNECTING) {
>         /* theoretically, another thread could be doing another select/poll on this socket and
>          * modify the state; we don't support this unlikely case */
> ```

Why not support it? Isn't it just unlock+return here? (and one change below, see my comment)
___
*[`libos/src/sys/libos_socket.c` line 117 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt0fjM4bmm_NjiqBDY:-Njt0fjM4bmm_NjiqBDZ:b-4bb43n) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L117)):*
> ```C
>         BUG();
>     }
>     if (pal_ret_events & (PAL_WAIT_ERROR | PAL_WAIT_HANG_UP)) {
> ```

Could you explain what's the logic behind this IF? Why does what we waited for influence `sock->last_error`?
___
*[`libos/src/sys/libos_socket.c` line 121 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt24z7AM9KHBYuiUin:-Njt24z7AM9KHBYuiUio:b-65lh2j) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L121)):*
> ```C
>     } else {
>         sock->last_error = 0;
>         __atomic_store_n(&sock->connecting_in_progress, false, __ATOMIC_RELEASE);
> ```

To fix concurrency I think we should move it to be the last step, so the fast-path never returns while the state is only half-updated to say it's connected. Not really dangerous because we have all of this under the lock, but IMO seems like a saner/safer version.
___
*[`libos/src/sys/libos_socket.c` line 259 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt2o89EZnP80vXrXCH:-Njt2o89EZnP80vXrXCI:b-zch183) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L259)):*
> ```C
>     bool inprogress;
>     ret = sock2->ops->connect(handle2, &addr, sizeof(addr), &inprogress);
>     assert(inprogress == false);
> ```

`inprogress` is initialized only on success.
___
*[`pal/include/pal/pal.h` line 599 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjtA0gqDAndFKN6wU2Z:-NjtA0gqDAndFKN6wU2_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/pal/include/pal/pal.h#L599)):*
> ```objc
>  *                             Can [...]

2023-11-23 08:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 17 of 27 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/src/net/ip.c` line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjsoNpZ0WPnGL296Old:-Njv0MlzEBD02AOLglTU:bxs3s5) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/net/ip.c#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I forgot it, why do we have this weird way of disconnecting instead of just having `PalSocketDisconnect()` with simpler arguments?
</blockquote></details>

This was implemented by @boryspoplawski : https://github.com/gramineproject/gramine/pull/579

I don't see any particular comments from my (or your) side on this.

I think Borys just followed the POSIX standard in this regard, see `man 2 connect`, search for `AF_UNSPEC`. 
___
*[`libos/src/sys/libos_epoll.c` line 676 at r4](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjPLtT89dFIddEDT_YL:-NjvCd6TCtZphlSyISf0:b-f1e36o) ([raw file](https://github.com/gramineproject/gramine/blob/725b89b69d32a6e23b504ac659911515e007d251/libos/src/sys/libos_epoll.c#L676)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if this implies that this is the only way of checking it. What if someone connects and then polls for read, because in that specific protocol it's the server which sends the data first?
</blockquote></details>

Done. You are right, I verified manually (using the test I added in this PR) that the native behavior of Linux works even on reads (POLLIN/EPOLLIN). I added a corresponding change to my test, and updated the logic in LibOS.
___
*[`libos/src/sys/libos_epoll.c` line 678 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjspPtkCV799FcHsQ1T:-NjvEhAw-GMTGaehXJki:buuhzp3) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_epoll.c#L678)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't the `pal_ret_events[i]` check be clearer and simpler if it was here? _This_ is the place which checks the conditions when to re-check the state anyways, and now this checking is split between two places and you need an additional argument in `check_connect_inprogress_on_poll()`.
</blockquote></details>

Done.

Note that we still need an additional argument, because we need to distinguish between success and error. I modified the argument though to be a boolean.
___
*[`libos/src/sys/libos_poll.c` line 216 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjspqM26avAdu_-IDhd:-NjvDV9A5TI32hTS63uf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_poll.c#L216)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_socket.c` line 96 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt10GP4XTQizLEHXtY:-NjvCa-X6m0M-LIJWVh4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just to not forget: if we decide to wait for more, then this will also need a change (and it's easy to miss).
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_socket.c` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt1bVuBdWbM1g8n6-H:-Njv6xmaApf982lZkcas:bv7yeg6) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L114)):*
Done, you're right.

> (and one change below, see my comment)

Why do you say that? That change seems to be irrelevant.
___
*[`libos/src/sys/libos_socket.c` line 117 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt0fjM4bmm_NjiqBDY:-Njv3UNx1CzRFE00MbLV:bt2dphp) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain what's the logic behind this IF? Why does what we waited for influence `sock->last_error`?
</blockquote></details>

The man page describes this:

   EINPROGRESS
          The socket is nonblocking and the connection cannot be
          completed immediately.  (UNIX domain sockets failed with
          EAGAIN instead.)  It is possible to select(2) or poll(2)
          for completion by selecting the socket for writing.  After
          select(2) indicates writability, use getsockopt(2) to read
          the SO_ERROR option at level SOL_SOCKET to determine
          whether connect() completed successfully (SO_ERROR is
          zero) or **unsuccessfully (SO_ERROR is one of the usual
          error codes listed here, explaining the reason for the
          failure)**.

In other words, if you are polling on an in-progress-connecting socket, and it returns POLLHUP or POLLERR (these are translated into PAL versions `PAL_WAIT_HANG_UP` and `PAL_WAIT_ERROR`), you can perform `getsockopt(socket_fd, SO_ERROR)` and you must get the error code (`ECONNREFUSED` in this case). See also the test that I added in this PR.
___
*[`libos/src/sys/libos_socket.c` line 121 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt24z7AM9KHBYuiUin:-Njv4S3GAh8MOPJx6g5i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L121)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To fix concurrency I think we should move it to be the last step, so the fast-path never returns while the state is only half-updated to say it's connected. Not really dangerous because we have all of this under the lock, but IMO seems like a saner/safer version.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_socket.c` line 259 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt2o89EZnP80vXrXCH:-Njv7JEWDVi5B0R66u8d:ben7dzt) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L259)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`inprogress` is initialized only on success.
</blockquote></details>

Done.

I first wanted to do a more complicated `assert(ret < 0 || inprogress == false)`, but then decide to just remove this assert, as this weak assert didn't deserve too much complexity. If you feel that the complicated assert should stay, I can change.
___
*[`pal/include/pal/pal.h` line 599 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjtA0gqDAndFKN6wU2Z:-Njv1pZa4js9rM63gD8G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/pal/include/pal/pal.h#L599)):*
> ```objc
>  *                             Can be NULL, to ignore the result.
>  * \param[out] out_inprogress  On success, returns true in special case of an in-progress connection
>  *                             on non-blocking socket.
> ```

Done.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.h` line 66 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjtC-Pu5bgYuqiyj3K6:-Njv23sB-DfH3vfBQuDy:b-u8klkm) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/pal/ [...]

2023-11-23 11:40 UTC, mkow approved these changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/src/net/ip.c` line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjsoNpZ0WPnGL296Old:-NjvsOV8DXvquZ7FylYM:b-nqf6mx) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/net/ip.c#L250)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was implemented by @boryspoplawski : https://github.com/gramineproject/gramine/pull/579

I don't see any particular comments from my (or your) side on this.

I think Borys just followed the POSIX standard in this regard, see `man 2 connect`, search for `AF_UNSPEC`.
</blockquote></details>

Weird, I'm pretty sure we had a discussion about this, but I don't remember the details... Anyways, it's not for this PR. But I'd change it, it's really weird.

And POSIX is not a good argument, it contains a lot of terrible APIs. But yeah, may explain the origin of this construction.
___
*[`libos/src/sys/libos_socket.c` line 114 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-Njt1bVuBdWbM1g8n6-H:-NjvvhW42eDuoB1JWesh:b-c5zaol) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/libos/src/sys/libos_socket.c#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, you're right.

> (and one change below, see my comment)

Why do you say that? That change seems to be irrelevant.
</blockquote></details>

When I wrote this comment I still thought it's required, but then I noticed that it's also ok without it and forgot to update.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.h` line 66 at r5](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjtC-Pu5bgYuqiyj3K6:-NjvyVDX1LP7VPp5x_VR:bls4ugk) ([raw file](https://github.com/gramineproject/gramine/blob/720924f85f7aba22b34cd0b7e033bb95926b7099/pal/src/host/linux-sgx/enclave_ocalls.h#L66)):*
> this header file didn't use `bool` before my change

Hmm, it did? E.g. in `ocall_get_quote()`. Not too many places (2?), but still :)


<!-- Sent from Reviewable.io -->

2023-11-23 12:07 UTC, kailun-qin approved these changes
> Reviewed 17 of 23 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-24 00:49 UTC, kailun-qin submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-24 03:19 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`libos/src/sys/libos_socket.c` line 98 at r7](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjzKCN_3jH8SllP0YyA:-NjzKCNb6Bc5XQ_lLR3O:bw79fx2) ([raw file](https://github.com/gramineproject/gramine/blob/a2e7d95750f95d1bb47db5314bcea7006be59dc4/libos/src/sys/libos_socket.c#L98)):*
> ```C
>      * the common case of an already-connected socket doing recv/send.
>      */
>      assert(handle->type == TYPE_SOCK);
> ```

This got indented by 5 spaces. Not blocking as the CI is very slow this week, but if you want then please fix. If not, then I'll add it to my "typo list" and fix someday in a single commit with other trivial stuff.


<!-- Sent from Reviewable.io -->

2023-11-24 07:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: 26 of 27 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`libos/src/sys/libos_socket.c` line 98 at r7](https://reviewable.io/reviews/gramineproject/gramine/1643#-NjzKCN_3jH8SllP0YyA:-Nk-JnzT17jijcvCZqof:b-w6qraw) ([raw file](https://github.com/gramineproject/gramine/blob/a2e7d95750f95d1bb47db5314bcea7006be59dc4/libos/src/sys/libos_socket.c#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This got indented by 5 spaces. Not blocking as the CI is very slow this week, but if you want then please fix. If not, then I'll add it to my "typo list" and fix someday in a single commit with other trivial stuff.
</blockquote></details>

Done. It's ok, we can wait for CI.


<!-- Sent from Reviewable.io -->

2023-11-24 09:19 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-11-24 11:45 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1643)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-24 11:50 UTC, merged