[python] Fix measuring absolute paths in chroots
gramineproject/gramine pull request #1679
Opened 2023-12-12 14:00 UTC by woju

## Description of the changes 

See commit message and comment.

## How to test this PR? 

use `gramine-sgx-sign --chroot` with some Debian-based image, measuring at least one file that is symlink to absolute path (e.g. `/usr/bin/uwsgi`: `mmdebstrap --include uwsgi`). The fail is more obvious when the link destination is not present on base system (e.g. `apt-get purge uwsgi`).

## Acknowledgements

Originally found by @bsulich2 and reported internally in Scaffolding project.

2023-12-12 14:05 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-12-12 14:14 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-12 17:37 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`python/graminelibos/manifest.py` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlU5SKa0HphPyZqk97f:-NlU5SKa0HphPyZqk97g:by113su) ([raw file](https://github.com/gramineproject/gramine/blob/ec3929ac5b47808277953a545ab3e452d27dd258/python/graminelibos/manifest.py#L74)):*
> ```Python
>             # relative to chroot. Therefore, we can't just open(2) it, because that will interpret
>             # paths relative to global VFS root, which it not what we want.
>             while path.is_symlink():
> ```

I think this doesn't work, it checks only the _final_ segment of the path, which might have been found using some directory symlinks in between resolved without the chroot. You need to check segment-by-segment starting from top-level (`/`, `/etc`, `/etc/asdf`, ...).


<!-- Sent from Reviewable.io -->

2023-12-13 11:05 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`python/graminelibos/manifest.py` line 74 at r1](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlU5SKa0HphPyZqk97f:-NlXq7Xw4gKJ9W6tB4Cq:bnus3lp) ([raw file](https://github.com/gramineproject/gramine/blob/ec3929ac5b47808277953a545ab3e452d27dd258/python/graminelibos/manifest.py#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this doesn't work, it checks only the _final_ segment of the path, which might have been found using some directory symlinks in between resolved without the chroot. You need to check segment-by-segment starting from top-level (`/`, `/etc`, `/etc/asdf`, ...).
</blockquote></details>

Done. I rewrote symlink resolution to traverse paths. Came up pretty OK, could have been worse. I also added tests for this, because at this point I feel there are too many cases to remember of.


<!-- Sent from Reviewable.io -->

2023-12-13 12:12 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`python/graminelibos/manifest.py` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY1Y_OD8E-udDJRIUW:-NlY1Y_OD8E-udDJRIUX:b-uot7py) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L58)):*
> ```Python
>     if seen is None:
>         # a mapping of linksrc -> linkdest (all within chroot), but can be None while recursing,
>         # and if None is encountered, then we'll know we have a loop
> ```

When you talk about `None` here, you actually mean the item in this dict being a None, not that `seen == None`, right? Can you reformulate then to talk explicitly about `items in this mapping can be None ...`
___
*[`python/graminelibos/manifest.py` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0BZi7jAM0bA2HCjP:-NlY0BZi7jAM0bA2HCjQ:btdf5jw) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L63)):*
> ```Python
>     # Current state. This is a path that is:
>     # - an instance of pathlib.Path;
>     # - absolute (stats with '/');
> ```

`stats`->`starts`
___
*[`python/graminelibos/manifest.py` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0VLKDSg1Uut07_-X:-NlY0VLKDSg1Uut07_-Y:b-5vucu5) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L64)):*
> ```Python
>     # - an instance of pathlib.Path;
>     # - absolute (stats with '/');
>     # - fully resolved path (contains no symlinks);
> ```

? But this function is about resolving the path (i.e. it may contain symlinks), so this text is wrong?
___
*[`python/graminelibos/manifest.py` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0T8SA-GTvjQ6-foV:-NlY0T8SA-GTvjQ6-foW:b-hpl898) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L65)):*
> ```Python
>     # - absolute (stats with '/');
>     # - fully resolved path (contains no symlinks);
>     # - inside chroot. (chroot_current_path is this path as seen from outside).
> ```

Remove the dot after `inside chroot`
___
*[`python/graminelibos/manifest.py` line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2P8846rECQXnyNIh:-NlY2P8846rECQXnyNIi:bt6w231) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L96)):*
> ```Python
>             # The following path concatenation is suboptimal, it will cause the recurring function
>             # to traverse and stat() all parts of current_path again, so it's easy to construct
>             # exploding O(n²) tree. However, to write this optimally, it would require to complicate
> ```

Please wrap by 100 chars per line
___
*[`python/graminelibos/manifest.py` line 97 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2RDG0Q7Krpm_3Eg5:-NlY2RDG0Q7Krpm_3Eg6:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L97)):*
> ```Python
>             # to traverse and stat() all parts of current_path again, so it's easy to construct
>             # exploding O(n²) tree. However, to write this optimally, it would require to complicate
>             # already convoluted logic. Trees that would trigger suboptimal complexity are uncommon,
> ```

ditto
___
*[`python/graminelibos/manifest.py` line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2eap4hIxsqfNGfk2:-NlY2eap4hIxsqfNGfk3:b-2aeu2b) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L106)):*
> ```Python
>         if seen[current_path] is None:
>             # we have a loop in symlinks
>             print(f'{current_path=}')
> ```

Debugging leftover?
___
*[`tests/test_chroot.py` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3XMg5qCxSHU0TqFM:-NlY3XMg5qCxSHU0TqFN:brb0t6) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L9)):*
> ```Python
> 
> 
> # TODO: use tmp_path after deprecating .el8
> ```

What do you mean by el8? RHEL 8? Can we spell it out then?
___
*[`tests/test_chroot.py` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3xCX5gdTs23zujjy:-NlY3xCX5gdTs23zujjz:b-c8i2tu) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L29)):*
> ```Python
>         file.write('pass')
>     (tmp_path / 'subdir/symlink').symlink_to('target')
>     assert (tmp_path / manifest.resolve_symlinks('/subdir/symlink', chroot=tmp_path).relative_to('/')
> ```

This doesn't wrap on 100 chars, but I'm not blocking
___
*[`tests/test_chroot.py` line 37 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY4-_S-bMZ-CYHcOPv:-NlY4-_S-bMZ-CYHcOPw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L37)):*
> ```Python
>         file.write('pass')
>     (tmp_path / 'subdir/symlink').symlink_to('../target')
>     assert (tmp_path / manifest.resolve_symlinks('/subdir/symlink', chroot=tmp_path).relative_to('/')
> ```

ditto
___
*[`tests/test_chroot.py` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY40v3Ao_8cAZvbPYn:-NlY40v3Ao_8cAZvbPYo:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L53)):*
> ```Python
>         file.write('pass')
>     (tmp_path / 'subdir/symlink').symlink_to('/subdir/target')
>     assert (tmp_path / manifest.resolve_symlinks('/subdir/symlink', chroot=tmp_path).relative_to('/')
> ```

ditto
___
*[`tests/test_chroot.py` line 61 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY41Vd5OC7f6cza0v0:-NlY41Vd5OC7f6cza0v1:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L61)):*
> ```Python
>         file.write('pass')
>     (tmp_path / 'subdir/symlink').symlink_to('/target')
>     assert (tmp_path / manifest.resolve_symlinks('/subdir/symlink', chroot=tmp_path).relative_to('/')
> ```

ditto
___
*[`tests/test_chroot.py` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY424O1TXbeML6KuTA:-NlY424O1TXbeML6KuTB:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L70)):*
> ```Python
>         file.write('pass')
>     (tmp_path / 'symlink').symlink_to('subdir')
>     assert (tmp_path / manifest.resolve_symlinks('/symlink/target', chroot=tmp_path).relative_to('/')
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-12-13 13:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: 0 of 2 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`python/graminelibos/manifest.py` line 58 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY1Y_OD8E-udDJRIUW:-NlYBXtf5jHTxDIXIVXu:b2x1vai) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When you talk about `None` here, you actually mean the item in this dict being a None, not that `seen == None`, right? Can you reformulate then to talk explicitly about `items in this mapping can be None ...`
</blockquote></details>

Done. (I mean "value", because in python's phraseology "item" is the tuple `(key, value)`).
___
*[`python/graminelibos/manifest.py` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0BZi7jAM0bA2HCjP:-NlYBu_I21mMh3PqzsiJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`stats`->`starts`
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0VLKDSg1Uut07_-X:-NlYAjSM4vgQtKh6cpeI:b-8igynz) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

? But this function is about resolving the path (i.e. it may contain symlinks), so this text is wrong?
</blockquote></details>

No, it's correct. `current_path` is the accumulator that keeps what this function already built. Not really an accumulator, if we encounter absolute symlink destination, it's swapped wholesale, but still, it's swapped for another resolved path. I added text in `()` in the first line.
___
*[`python/graminelibos/manifest.py` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0T8SA-GTvjQ6-foV:-NlYC9Tl1qp0FT0lP4Ue:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove the dot after `inside chroot`
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest.py` line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2P8846rECQXnyNIh:-NlYCGfD6trOcXPEh-Ho:byc4i4) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap by 100 chars per line
</blockquote></details>

I think it's OK. Trailing "e" is in exactly 100th column.
___
*[`python/graminelibos/manifest.py` line 97 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2RDG0Q7Krpm_3Eg5:-NlYCNJJELIx_K0eANz-:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`python/graminelibos/manifest.py` line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2eap4hIxsqfNGfk2:-NlYCOxy4yFs3rNY5puD:buqvb9e) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Debugging leftover?
</blockquote></details>

Yes, and also this triggered almalinux-8 fail, because .el8 has too old python to understand `{=}` syntax in f-strings.
___
*[`tests/test_chroot.py` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3XMg5qCxSHU0TqFM:-NlYCWSOEcfcEaxLWZA8:b-u3wt47) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by el8? RHEL 8? Can we spell it out then?
</blockquote></details>

".el8" is the content of `%{dist}` RPM macro (cf. `gramine.spec`, `Revision:`) and identifies distribution. It originates from RHEL, but is common to all variants and rebuilds (i.e. UBI8, AlmaLinux 8, Rocky Linux 8, etc.). Since we don't support RHEL directly, I won't write "RHEL", but if you prefer, I can write "*EL8".
___
*[`tests/test_chroot.py` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3xCX5gdTs23zujjy:-NlYFSraDN0oOAsWqOTC:b-kzb3cp) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't wrap on 100 chars, but I'm not blocking
</blockquote></details>

Done. I took liberty to simplify this and some other boilerplate. Hopefully the tests are even more readable.
___
*[`tests/test_chroot.py` line 37 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY4-_S-bMZ-CYHcOPv:-NlYFTfj9Asxwf20EdCQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tests/test_chroot.py` line 53 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY40v3Ao_8cAZvbPYn:-NlYFUbM2jmVyXg1dDFB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tests/test_chroot.py` line 61 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY41Vd5OC7f6cza0v0:-NlYFVWBAA-nSvHWxSQM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`tests/test_chroot.py` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY424O1TXbeML6KuTA:-NlYFVoU-Iws8dNflc-2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 13:15 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`python/graminelibos/manifest.py` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY0VLKDSg1Uut07_-X:-NlYI-ok43Xlrbfdt-bJ:blv4o5f) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L64)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, it's correct. `current_path` is the accumulator that keeps what this function already built. Not really an accumulator, if we encounter absolute symlink destination, it's swapped wholesale, but still, it's swapped for another resolved path. I added text in `()` in the first line.
</blockquote></details>

Thanks, now with the `already resolved` text it makes sense to me.
___
*[`python/graminelibos/manifest.py` line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY2P8846rECQXnyNIh:-NlYINoQ28usJU5OegCv:b6gdsma) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/python/graminelibos/manifest.py#L96)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think it's OK. Trailing "e" is in exactly 100th column.
</blockquote></details>

Ah, my Reviewable setting was wrong.
___
*[`tests/test_chroot.py` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3XMg5qCxSHU0TqFM:-NlYIY3_2k7KFJbHrAPD:b-bk5ip0) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

".el8" is the content of `%{dist}` RPM macro (cf. `gramine.spec`, `Revision:`) and identifies distribution. It originates from RHEL, but is common to all variants and rebuilds (i.e. UBI8, AlmaLinux 8, Rocky Linux 8, etc.). Since we don't support RHEL directly, I won't write "RHEL", but if you prefer, I can write "*EL8".
</blockquote></details>

Works for me.
___
*[`tests/test_chroot.py` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlY3xCX5gdTs23zujjy:-NlYJMEU4a3le6NW6GPi:bx5qykg) ([raw file](https://github.com/gramineproject/gramine/blob/92064c4d5ea64881e7e65eedfe0d3c3596d9e026/tests/test_chroot.py#L29)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. I took liberty to simplify this and some other boilerplate. Hopefully the tests are even more readable.
</blockquote></details>

Thanks, very readable now.


<!-- Sent from Reviewable.io -->

2023-12-13 14:36 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-12-13 16:11 UTC, mkow requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[`python/graminelibos/manifest.py` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlYuC5l0LHTe-OKpHj4:-NlYuC5l0LHTe-OKpHj5:b-sdy7wr) ([raw file](https://github.com/gramineproject/gramine/blob/2ed265ef8258d9a06648e477a0c08201ceb548ef/python/graminelibos/manifest.py#L68)):*
> ```Python
>     # Therefore it's safe to traverse '..' in current_path by just taking .parent attribute.
>     current_path = pathlib.Path('/')
>     chroot_current_path = chroot / current_path.relative_to('/')
> ```

This naming seems confusing, why host (non-chroot) path is named with `chroot_` prefix?
___
*[`python/graminelibos/manifest.py` line 99 at r5](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlYvjBV9xxXH0WC8_Io:-NlYvjBV9xxXH0WC8_Ip:b-nvx9vb) ([raw file](https://github.com/gramineproject/gramine/blob/2ed265ef8258d9a06648e477a0c08201ceb548ef/python/graminelibos/manifest.py#L99)):*
> ```Python
>             # exploding O(n²) tree. However, to write this optimally, it would require to complicate
>             # already convoluted logic. Trees that would trigger suboptimal complexity are uncommon,
>             # so I think it's a reasonable tradeoff.  --woju 12.12.2023
> ```

In other places we do `XXX(woju): asdfgsdsadsad`



_Code quote:_
```Python
  --woju 12.12.2023
```


<!-- Sent from Reviewable.io -->

2023-12-13 16:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`python/graminelibos/manifest.py` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlYuC5l0LHTe-OKpHj4:-NlZ5dkp58Go4dnmC6La:bumenem) ([raw file](https://github.com/gramineproject/gramine/blob/2ed265ef8258d9a06648e477a0c08201ceb548ef/python/graminelibos/manifest.py#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This naming seems confusing, why host (non-chroot) path is named with `chroot_` prefix?
</blockquote></details>

because it's `chroot / current_path`... I've renamed it to `inner_` and `outer_`, if that's better (I can revert this).
___
*[`python/graminelibos/manifest.py` line 99 at r5](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlYvjBV9xxXH0WC8_Io:-NlZ5cRH2ajL56uhXIvD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2ed265ef8258d9a06648e477a0c08201ceb548ef/python/graminelibos/manifest.py#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In other places we do `XXX(woju): asdfgsdsadsad`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 16:59 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`python/graminelibos/manifest.py` line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlYuC5l0LHTe-OKpHj4:-NlZ6F6S2DLNtl9sIU7z:b-h6lx44) ([raw file](https://github.com/gramineproject/gramine/blob/2ed265ef8258d9a06648e477a0c08201ceb548ef/python/graminelibos/manifest.py#L68)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

because it's `chroot / current_path`... I've renamed it to `inner_` and `outer_`, if that's better (I can revert this).
</blockquote></details>

Good idea, now it's obvious which one is which :)


<!-- Sent from Reviewable.io -->

2023-12-13 17:38 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`tests/test_chroot.py` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlZFK3f3EgKFqe47Wgm:-NlZFK3gB0CbRe9ipMcD:b-ofuacn) ([raw file](https://github.com/gramineproject/gramine/blob/b2915ea11e8f871d5386b0736576a48e3bcf4ba6/tests/test_chroot.py#L3)):*
> ```Python
> # TODO write tests:
> # - a/b/file/.. (should raise NotADirectoryError)
> # - a/b/file/. (same)
> ```

I thought that we still don't have such tests (well, the `.` one fails in this test, and we don't have the `..` one in the exact form described). But whatever, the tests seem comprehensive enough.


<!-- Sent from Reviewable.io -->

2023-12-13 19:04 UTC, merged

2023-12-15 10:25 UTC, woju commented
*[`tests/test_chroot.py` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1679#-NlZFK3f3EgKFqe47Wgm:-Nlh-_b60aWZWjVebmix:b-idlx3n) ([raw file](https://github.com/gramineproject/gramine/blob/b2915ea11e8f871d5386b0736576a48e3bcf4ba6/tests/test_chroot.py#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought that we still don't have such tests (well, the `.` one fails in this test, and we don't have the `..` one in the exact form described). But whatever, the tests seem comprehensive enough.
</blockquote></details>

These are "enotdir", I just forgot to remove last two TODO points.


<!-- Sent from Reviewable.io -->