[LibOS] Allow `madvise(MADV_DONTNEED)` on non-writable mappings
gramineproject/gramine pull request #1692
Opened 2023-12-21 15:17 UTC by dimakuv

## Description of the changes 

Previously, it was not implemented though there is no blocker for this (only need to temporarily change permissions on the mapping to be writable). This fixes Node.js v20 workloads.

Fixes #1469.

## How to test this PR? 

Added a LibOS test.

Also, test Node.js v20:

- Without PR:
```
gramineproject/examples/nodejs$ gramine-direct ./nodejs helloworld.js
# Fatal error in , line 0
# Check failed: 0 == ret.

gramineproject/examples/nodejs$ gramine-sgx ./nodejs helloworld.js
# Fatal error in , line 0
# Check failed: 0 == ret.
```

- With PR:
```
gramineproject/examples/nodejs$ gramine-direct ./nodejs helloworld.js
Hello World

gramineproject/examples/nodejs$ gramine-sgx ./nodejs helloworld.js
Hello World
```

To install Node.js v20 on Ubuntu 20.04, you can use this hacky approach: https://joshtronic.com/2023/04/23/how-to-install-nodejs-20-on-ubuntu-2004-lts/. Note that the binary was renamed from `nodejs` to `node`, so when running our Node.js example, to not modify the manifest template file, simply create a symlink: `ln -s /usr/bin/node /usr/bin/nodejs`.

2023-12-21 15:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-NmBywoKAZDWaZ0AvDZQ):*
For history, check the original PR https://github.com/gramineproject/graphene/pull/1883 and search for "This is for non-writable mappings, for which Linux madvise still works, but it would be harder to implement in Graphene." (I.e., we were lazy or didn't have the tools to do it easily, but we have now.)


<!-- Sent from Reviewable.io -->

2024-01-11 05:58 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nnr4RLI1r__P1PmGWdf):*
I think we need to also update: https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/Documentation/devel/features.md#L1731.
___
*[`libos/src/bookkeep/libos_vma.c` line 1345 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nnr-nS870fu2y7Uj6wC:-Nnr-nS870fu2y7Uj6wD:bdyeav8) ([raw file](https://github.com/gramineproject/gramine/blob/8750f1acf1f16b3cdc625996e281e87e663de958/libos/src/bookkeep/libos_vma.c#L1345)):*
> ```C
>     }
> 
>     memset((void*)zero_start, 0, zero_end - zero_start);
> ```

May I know the reason why `MADV_DONTNEED` on anonymous mappings is emulated as "zero filling" rather than discarding the pages (and allocating on demand for SGX2)? Is it for simplicity?


<!-- Sent from Reviewable.io -->

2024-01-11 07:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nnr4RLI1r__P1PmGWdf):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think we need to also update: https://github.com/gramineproject/gramine/blob/1f72aaf8148a7712c5c8bad1da9839e2bcc5c633/Documentation/devel/features.md#L1731.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1345 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nnr-nS870fu2y7Uj6wC:-NnrWIlf7O6g2BrllDBs:b-vdvebk) ([raw file](https://github.com/gramineproject/gramine/blob/8750f1acf1f16b3cdc625996e281e87e663de958/libos/src/bookkeep/libos_vma.c#L1345)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

May I know the reason why `MADV_DONTNEED` on anonymous mappings is emulated as "zero filling" rather than discarding the pages (and allocating on demand for SGX2)? Is it for simplicity?
</blockquote></details>


What do you mean by "allocating on demand"? This would imply allocating on #PF, which is not implemented in Gramine at all yet (your PR on lazy allocation is still pending). How else would we do this on-demand allocation?

So yes, you can say that it's currently for simplicity.


<!-- Sent from Reviewable.io -->

2024-01-11 10:29 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 1345 at r1](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nnr-nS870fu2y7Uj6wC:-Nnrl89t3gLEhy272vB2:b-eoka02) ([raw file](https://github.com/gramineproject/gramine/blob/8750f1acf1f16b3cdc625996e281e87e663de958/libos/src/bookkeep/libos_vma.c#L1345)):*
> This would imply allocating on #PF

Yes, this was what I meant.

> which is not implemented in Gramine at all yet (your PR on lazy allocation is still pending)

Ok then. I was thinking that it was actually possible to emulate the semantics more correctly (w/ allocating on #PF).
___
*[`libos/src/bookkeep/libos_vma.c` line 1349 at r2](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nns1qUt3eKkShJvuhv1:-Nns1qUt3eKkShJvuhv2:bjgech4) ([raw file](https://github.com/gramineproject/gramine/blob/48be1351da8226c3ea28d48508468c8f6bec606a/libos/src/bookkeep/libos_vma.c#L1349)):*
> ```C
>     if (pal_prot != pal_prot_writable) {
>         /* the area was made writable above; restore the original permissions */
>         int protect_ret = PalVirtualMemoryProtect((void*)zero_start, zero_end - zero_start,
> ```

It's a bit weird... why `protect_ret` here but `ret` above? We use the different name in the other place of this file for reasons (which are not applied here).



_Code quote:_
```C
protect_ret
```


<!-- Sent from Reviewable.io -->

2024-01-11 13:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: 2 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_vma.c` line 1349 at r2](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nns1qUt3eKkShJvuhv1:-NnsdTlN0mnjVWZ9wAbk:b3fx7uy) ([raw file](https://github.com/gramineproject/gramine/blob/48be1351da8226c3ea28d48508468c8f6bec606a/libos/src/bookkeep/libos_vma.c#L1349)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's a bit weird... why `protect_ret` here but `ret` above? We use the different name in the other place of this file for reasons (which are not applied here).
</blockquote></details>

Done. Yep, copy-paste failure.


<!-- Sent from Reviewable.io -->

2024-01-11 14:01 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-01-11 15:15 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-20.04-musl please (`test_sign_from_pem_path` failed again)

2024-01-11 15:16 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please (Busybox download failed)

2024-01-11 16:00 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please (Busybox download failed)

2024-02-07 19:11 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 1351 at r3](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nq3yEqA82OxrSgPpLFz:-Nq3yEqA82OxrSgPpLG-:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a3c07c1fe8fc9c67b269d38290e90e9e97142024/libos/src/bookkeep/libos_vma.c#L1351)):*
> ```C
>         int ret = PalVirtualMemoryProtect((void*)zero_start, zero_end - zero_start, pal_prot);
>         if (ret < 0) {
>             log_error("restore original permissions failed: %s", pal_strerror(ret));
> ```





_Suggestion:_
```C
log_error("restoring original permissions failed: %s", pal_strerror(ret));
```


<!-- Sent from Reviewable.io -->

2024-02-08 07:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1351 at r3](https://reviewable.io/reviews/gramineproject/gramine/1692#-Nq3yEqA82OxrSgPpLFz:-Nq6VbJn6lK4hN21QC_5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a3c07c1fe8fc9c67b269d38290e90e9e97142024/libos/src/bookkeep/libos_vma.c#L1351)):*
> ```C
>         int ret = PalVirtualMemoryProtect((void*)zero_start, zero_end - zero_start, pal_prot);
>         if (ret < 0) {
>             log_error("restore original permissions failed: %s", pal_strerror(ret));
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 07:07 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1692)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-02-08 20:14 UTC, merged