[LibOS] Wake up another thread on host-injected SIGTERM if can't handle
gramineproject/gramine pull request #1703
Opened 2024-01-05 14:11 UTC by dimakuv

## Description of the changes 

Some apps (e.g. MongoDB) create a separate thread that has a single job -- to wait for a SIGTERM signal and then perform graceful app termination. This special thread issues `sigtimedwait(SIGTERM)` and waits forever for this signal. Other threads instead block this signal (add it to their sigmask), so that they don't need to care about reacting to this signal.

Previously, our LibOS would try to handle SIGTERM on the thread that got chosen by the host Linux (the thread is arbitrarily chosen). But with high probability, on such apps this thread will be the not-special-one, and the app would effectively ignore SIGTERM.

## How to test this PR? 

This was detected on MongoDB. Snippet from MongoDB log on master branch (without this PR):
```sh
# T2 is a special thread that forever waits for SIGTERM (and other signals)
[P1:T2:mongod] trace: ---- rt_sigtimedwait([SIGHUP,SIGINT,SIGUSR1,SIGUSR2,SIGTERM,SIGXCPU,], 0x2df391648, NULL, 0x8) ...

# T1, T3 ... T33 are worker threads that block SIGTERM (never receive it)
[P1:T1:mongod] trace: ---- rt_sigprocmask(SETMASK, [SIGHUP,SIGINT,SIGUSR1,SIGTERM,SIGXCPU,], NULL, 0x8) = 0x0
...
[P1:T33:mongod] trace: ---- rt_sigprocmask(SETMASK, [SIGHUP,SIGINT,SIGUSR1,SIGTERM,SIGXCPU,], NULL, 0x8) = 0x0
```

I didn't know how to write a LibOS regression test for this special case, as this requires our Python PyTest harness to start the Gramine program AND send a signal to it in parallel (after the program is initialized completely and goes into some kind of infinite loop).

2024-01-05 14:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/bookkeep/libos_signal.c` line 732 at r1](https://reviewable.io/reviews/gramineproject/gramine/1703#-NnOyDW8BiwLotEJurVU:-NnOyDW9491G8qxZ_bXS:brsstyl) ([raw file](https://github.com/gramineproject/gramine/blob/af6c4cccc48c1777e1703e08ee9d801c01596ea9/libos/src/bookkeep/libos_signal.c#L732)):*
> ```C
>              * common case of one dedicated app thread doing sigtimedwait(SIGTERM) while other
>              * threads mark SIGTERM as blocked) */
>             int ret = walk_thread_list(wakeup_one_thread_on_sigterm, NULL, /*one_shot=*/true);
> ```

I based my code on this snippet (written by Borys long ago): https://github.com/gramineproject/gramine/blob/5d38bb14077cf87f1ddb3cef07f6f2ab70621276/libos/src/sys/libos_sigaction.c#L354


<!-- Sent from Reviewable.io -->

2024-01-12 03:22 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_signal.c` line 732 at r1](https://reviewable.io/reviews/gramineproject/gramine/1703#-NnvcIjO2DqqBekzw0JG:-NnvcIjO2DqqBekzw0JH:bfcx9ek) ([raw file](https://github.com/gramineproject/gramine/blob/af6c4cccc48c1777e1703e08ee9d801c01596ea9/libos/src/bookkeep/libos_signal.c#L732)):*
> ```C
>              * common case of one dedicated app thread doing sigtimedwait(SIGTERM) while other
>              * threads mark SIGTERM as blocked) */
>             int ret = walk_thread_list(wakeup_one_thread_on_sigterm, NULL, /*one_shot=*/true);
> ```

-> `/*arg=*/NULL`



_Code quote:_
```C
NULL
```
___
*[`libos/src/bookkeep/libos_signal.c` line 734 at r1](https://reviewable.io/reviews/gramineproject/gramine/1703#-NnvcYdA9OTO0fbH0Z7t:-NnvcYdA9OTO0fbH0Z7u:b-3iwvzr) ([raw file](https://github.com/gramineproject/gramine/blob/af6c4cccc48c1777e1703e08ee9d801c01596ea9/libos/src/bookkeep/libos_signal.c#L734)):*
> ```C
>             int ret = walk_thread_list(wakeup_one_thread_on_sigterm, NULL, /*one_shot=*/true);
>             if (ret < 0 && ret != -ESRCH) {
>                 log_error("failed to deliver a SIGTERM signal to any thread (%s)",
> ```

This error message seems to be misleading.

Shouldn't the condintion (`ret < 0 && ret != -ESRCH`) imply that "error occurred while trying to deliver a SIGTERM signal to a thread"? The phrase "failed to deliver a SIGTERM signal to any thread" sounds more like the opposite (the `-ESRCH` scenario) - it tried all threads but couldn’t find any suitable one to deliver the signal.



_Code quote:_
```C
failed to deliver a SIGTERM signal to any thread (%s)
```


<!-- Sent from Reviewable.io -->

2024-01-12 09:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 732 at r1](https://reviewable.io/reviews/gramineproject/gramine/1703#-NnvcIjO2DqqBekzw0JG:-NnwxENV7lFSH-L6fcY1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af6c4cccc48c1777e1703e08ee9d801c01596ea9/libos/src/bookkeep/libos_signal.c#L732)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `/*arg=*/NULL`
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_signal.c` line 734 at r1](https://reviewable.io/reviews/gramineproject/gramine/1703#-NnvcYdA9OTO0fbH0Z7t:-NnwxE8g0FMwmSbOnkII:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/af6c4cccc48c1777e1703e08ee9d801c01596ea9/libos/src/bookkeep/libos_signal.c#L734)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This error message seems to be misleading.

Shouldn't the condintion (`ret < 0 && ret != -ESRCH`) imply that "error occurred while trying to deliver a SIGTERM signal to a thread"? The phrase "failed to deliver a SIGTERM signal to any thread" sounds more like the opposite (the `-ESRCH` scenario) - it tried all threads but couldn’t find any suitable one to deliver the signal.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-12 11:13 UTC, dimakuv commented
Jenkins, retest linux-sgx-vm-gcc-release please (Busybox download failed)

2024-02-01 06:00 UTC, jkr0103 reviewed
This PR fixes issue for mongodb and mysql. Thanks for fixing this.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703#-:-NnSGCfV6wkW9ShoFy9b:bqw2rka)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 639 at r2](https://reviewable.io/reviews/gramineproject/gramine/1703#-NpYEpKd8f2R5aTmNXiq:-NpYEpKd8f2R5aTmNXir:bvauqcq) ([raw file](https://github.com/gramineproject/gramine/blob/118773cb37b80512c50923957b1f21c66a526ca6/libos/src/bookkeep/libos_signal.c#L639)):*
> ```C
> }
> 
> static int wakeup_one_thread_on_sigterm(struct libos_thread* thread, void* arg) {
> ```

We have similar function [here](https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_sigaction.c#L307). Should we reuse it?


<!-- Sent from Reviewable.io -->

2024-02-01 06:36 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`libos/src/bookkeep/libos_signal.c` line 639 at r2](https://reviewable.io/reviews/gramineproject/gramine/1703#-NpYEpKd8f2R5aTmNXiq:-NpYNT4f0qDGzAGYYv7z:b-7ggj65) ([raw file](https://github.com/gramineproject/gramine/blob/118773cb37b80512c50923957b1f21c66a526ca6/libos/src/bookkeep/libos_signal.c#L639)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We have similar function [here](https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_sigaction.c#L307). Should we reuse it?
</blockquote></details>

+1, I think we could


<!-- Sent from Reviewable.io -->

2024-02-02 13:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_signal.c` line 639 at r2](https://reviewable.io/reviews/gramineproject/gramine/1703#-NpYEpKd8f2R5aTmNXiq:-Npe4_NS-9CqC7G_9clI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/118773cb37b80512c50923957b1f21c66a526ca6/libos/src/bookkeep/libos_signal.c#L639)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1, I think we could
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 06:22 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-02-07 19:42 UTC, mkow requested changes
> I didn't know how to write a LibOS regression test for this special case, as this requires our Python PyTest harness to start the Gramine program AND send a signal to it in parallel (after the program is initialized completely and goes into some kind of infinite loop).

It shouldn't be that hard I think? It should be analogous to how `run_gdb()` uses `run_binary()` to run Gramine with a wrapper - in this case that wrapper would be a shell script starting gramine, waiting for it to start and then sending a signal?

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703#-:-Nq43a4g-yAo1DWU1U7E:b-gzhurj)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq4-7h4B97w4YjiiJ8S):*
> if can't handle

If what can handle what?
___
*[`libos/src/bookkeep/libos_signal.c` line 714 at r3](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq41dsS7irLMtyQKPOs:-Nq41dsS7irLMtyQKPOt:b-e8fzzo) ([raw file](https://github.com/gramineproject/gramine/blob/37064c715e7d530285c1154d0013cc1bdd99f5bb/libos/src/bookkeep/libos_signal.c#L714)):*
> ```C
>         unlock(&current->lock);
>     } else if (__atomic_load_n(&g_host_injected_signal, __ATOMIC_RELAXED) != 0) {
>         static_assert(SIGS_CNT < 0xff, "This code requires 0xff to be an invalid signal number");
> ```

Actually, why 0xff? `g_host_injected_signal` is a signed integer, why not just -1?


<!-- Sent from Reviewable.io -->

2024-02-08 07:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq4-7h4B97w4YjiiJ8S):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> if can't handle

If what can handle what?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 12:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: 3 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq7arc7DDmvdpl2hnNu:-Nq7arc7DDmvdpl2hnNv:bzcvit) (no related file):*
The newly added test `sigterm_multithread` fails with a timeout without this PR:

- `gramine-direct`:
```
~/gramineproject/gramine/libos/test/regression$ gramine-test pytest -k test_404_sigterm_multithread
python3 -m pytest -k test_404_sigterm_multithread
========================================================================================== FAILURES ==========================================================================================
________________________________________________________________________ TC_01_Bootstrap.test_404_sigterm_multithread ________________________________________________________________________
...
E   AssertionError: Command ['./test_sigterm.sh', '/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'sigterm_multithread'] timed out after 10 s
```

- `gramine-sgx`:
```
~/gramineproject/gramine/libos/test/regression$ SGX=1 gramine-test pytest -k test_404_sigterm_multithread
python3 -m pytest -k test_404_sigterm_multithread
========================================================================================== FAILURES ==========================================================================================
________________________________________________________________________ TC_01_Bootstrap.test_404_sigterm_multithread ________________________________________________________________________
...
E   AssertionError: Command ['./test_sigterm.sh', '/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/sgx/loader', '/home/dimakuv/gramineproject/gramine/built-debug/lib/x86_64-linux-gnu/gramine/sgx/libpal.so', 'init', 'sigterm_multithread'] timed out after 20 s
```

___
___
*[`libos/src/bookkeep/libos_signal.c` line 714 at r3](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq41dsS7irLMtyQKPOs:-Nq7bELK2Ok6vNu_3WaN:b-q4veer) ([raw file](https://github.com/gramineproject/gramine/blob/37064c715e7d530285c1154d0013cc1bdd99f5bb/libos/src/bookkeep/libos_signal.c#L714)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll do this in a separate PR (as it was already like this and not relevant to this PR).

I didn't find any particular reason why Borys used `0xff` instead of e.g. `-1`. I think it's just obvious that 255 is a "not a real signal" special value, and it is more beautiful than a negative number.
</blockquote></details>

Done, see https://github.com/gramineproject/gramine/pull/1766


<!-- Sent from Reviewable.io -->

2024-02-09 00:56 UTC, mkow requested changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/sigterm_multithread.c` line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqALflO1fv_89QK-SWC:-NqALflO1fv_89QK-SWD:b-fx68l9) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L59)):*
> ```C
> 
>     /* helper thread started and waits for SIGTERM; inform the wrapper shell script */
>     puts("READY");
> ```

missing `flush()`?
___
*[`libos/test/regression/sigterm_multithread.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqAM07tEDXvgcda3Axj:-NqAM07tEDXvgcda3Axk:b3enqhs) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L64)):*
> ```C
>      * threads would wait in blocking host syscalls indefinitely, and Gramine currently has a
>      * limitation that signals are delivered when some thread returns from syscall to the app */
>     for (int i = 0; i < 100; i++)
> ```

this loop should be infinite, otherwise the test can fail due to a race if we're super unlucky
___
*[`libos/test/regression/sigterm_multithread.c` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqALshu1udTVchPV5M6:-NqALshu1udTVchPV5M7:b-hhe11j) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L65)):*
> ```C
>      * limitation that signals are delivered when some thread returns from syscall to the app */
>     for (int i = 0; i < 100; i++)
>         sleep(1);
> ```

This probably adds a second to the test execution time, please use usleep() instead and wait shorter.
___
*[`libos/test/regression/sigterm_multithread.manifest.template` line 6 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq7ZA1q1OhO9if-LJr9:-NqAL8NW2meaMydjFs1G:b76r3e4) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.manifest.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This test-specific manifest template is needed purely for this `enable_sigterm_injection`.

Alternatively, I could add this line in the generic `manifest.template` and remove this file.
</blockquote></details>

Nah, I prefer the current way, IMO better if most tests run on defaults.
___
*[`libos/test/regression/test_libos.py` line 383 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq7ZJ3g3MxfWagQWstM:-NqAK_wZ5t067_GqlJGu:b-k0rc4h) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/test_libos.py#L383)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Please note that I redirect the output of the Gramine test in a temporary FIFO pipe in the bash script, so I can only check the outputs in the shell script itself.
</blockquote></details>

I think you could `tee` gramine instead of redirecting and you'd get the output here, but I guess it doesn't really matter.


<!-- Sent from Reviewable.io -->

2024-02-09 08:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/sigterm_multithread.c` line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqALflO1fv_89QK-SWC:-NqBjD4031umZEBao4yC:b-lou6zs) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing `flush()`?
</blockquote></details>

I have `setbuf(stdout, NULL);` above, which disables buffering, so it is analogous to including `flush()`.

But now I removed those lines -- they were used for my debugging, when I had many printfs in the test. Now that I only have one, I'll do the explicit `flush()` in this one place.
___
*[`libos/test/regression/sigterm_multithread.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqAM07tEDXvgcda3Axj:-NqBjkSBEFVjD2gs_Rgk:b-yz2wgz) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this loop should be infinite, otherwise the test can fail due to a race if we're super unlucky
</blockquote></details>

Done. The probability of another thread to be preempted for 100 seconds should be extremely low though :)
___
*[`libos/test/regression/sigterm_multithread.c` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqALshu1udTVchPV5M6:-NqBkjjn36d5_PQ_gZq5:bya55li) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This probably adds a second to the test execution time, please use usleep() instead and wait shorter.
</blockquote></details>

Done. We shouldn't use `usleep()` as it was deprecated (and even removed from POSIX 2008 standard), so using the recommended `nanosleep()` instead.
___
*[`libos/test/regression/test_libos.py` line 383 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-Nq7ZJ3g3MxfWagQWstM:-NqBidqv9aVTp9Qv4ug8:b9jfxhl) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/test_libos.py#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think you could `tee` gramine instead of redirecting and you'd get the output here, but I guess it doesn't really matter.
</blockquote></details>

Yes, I first did the `tee`, but then `pid=$!` command gives the PID of the `tee` program. I got lost how I could get the PID of the Gramine process itself, without resorting to things like `pgrep`. Then I got frustrated and decided to ignore the output of the Gramine test itself, relying only on its exit code.


<!-- Sent from Reviewable.io -->

2024-02-10 16:02 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/sigterm_multithread.c` line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/1703#-NqAM07tEDXvgcda3Axj:-NqIjtVu00Qsom9Bdt8l:b-savkfy) ([raw file](https://github.com/gramineproject/gramine/blob/726bf8e55a7983a32eb89d0d1db1633b9cd8b451/libos/test/regression/sigterm_multithread.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. The probability of another thread to be preempted for 100 seconds should be extremely low though :)
</blockquote></details>

Yes, but writing it correctly takes the same effort and space as incorrectly, so why not :P


<!-- Sent from Reviewable.io -->

2024-02-11 15:15 UTC, kailun-qin approved these changes
> Reviewed 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1703)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-02-12 10:28 UTC, merged