[LibOS] Have async thread set a callback on libos_handle to take it off the list before it is freed. [v2]
gramineproject/gramine pull request #1721
Opened 2024-01-16 21:18 UTC by stefanberger

## Description of the changes 

This PR fixes issue https://github.com/gramineproject/gramine/issues/1525 where a PAL_HANDLE was freed even though this PAL_HANDLE still had an async event associated with it.  The solution I am using now is to add support for a callback to libos_handle where that callback is called before the libos_handle is freed once its reference counter has reached 0, thus avoiding the issue. The callback will be set for as long as the async thread has a libos_handle on its list and once it is removed from the list the callback will be set to NULL. 

This PR is improvement to https://github.com/gramineproject/gramine/pull/1585

## How to test this PR? 

A test case is provided.

2024-01-19 10:09 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721)* status: 0 of 10 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWB-a57UxRN7VUJijE:-NoWB-a57UxRN7VUJijF:bdumxtn) (no related file):*
I definitely like this new fix, but see my comments.

___
___
*[`libos/include/libos_handle.h` line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWB4iR626a94Ho_JgI:-NoWB4iR626a94Ho_JgJ:b9n5wvv) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L160)):*
> ```objc
> 
>     refcount_t ref_count;
>     libos_handle_free_callback_t free_callback;
> ```

Actually, the name is too generic. This field is used particularly to set up the Async helper thread deletion event.

Otherwise, imagine we'll have a handle that can be both added to the Async helper thread (as done in this PR) **and** it needs some e.g. file-system cleanup. Then there should be **two events** called, but we have only one field, and one of the event setups' will override the other, and we have a "lost event".

So, let's make it very clear and call it `free_in_async_helper_thread_callback`. Or something equally clear.
___
*[`libos/include/libos_handle.h` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAwbJ8mLig9XrE42o:-NoWAwbJ8mLig9XrE42p:bjefn43) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L235)):*
> ```objc
> static inline libos_handle_free_callback_t
> set_handle_free_callback(struct libos_handle* hdl,
>                          libos_handle_free_callback_t cb)
> ```

This coding style is different from out classic style, please fix
___
*[`libos/include/libos_handle.h` line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWA_sUCT9wgz3k7JW0:-NoWA_sUCT9wgz3k7JW1:b-v2qg70) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L239)):*
> ```objc
>     libos_handle_free_callback_t ret = hdl->free_callback;
>     hdl->free_callback = cb;
>     return ret;
> ```

Why do you need this return? Why not make the function `void`? Looks like unnecessary complication.
___
*[`libos/src/libos_async.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAS6tD9aZFI1wkleP:-NoWAS6tD9aZFI1wkleQ:b-6kbhip) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L26)):*
> ```C
>     void (*callback)(IDTYPE caller, void* arg);
>     void* arg;
>     PAL_HANDLE object;    /* handle (async IO) to wait on */
> ```

There is no need for this explicit `object` field now. You can replace it with `hdl->pal_handle` everywhere.
___
*[`libos/src/libos_async.c` line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoW8PVrC1Nd2C_VoMHJ:-NoW8PVrC1Nd2C_VoMHK:b6t7z1y) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L56)):*
> ```C
>         if (tmp->object == hdl->pal_handle) {
>             LISTP_DEL(tmp, &async_list, list);
>             free(tmp);
> ```

This is a wrong logic, which leads to a **dangling pointer bug**.

Imagine we have two threads: one main thread and one Async helper thread.
- The main thread installs the Async I/O libos handle
- Async helper thread adds this libos handle's PAL handle to its list of handles-to-wait-on
- Async helper thread calls `PalStreamsWaitEvents()` and sleeps on it
- The main thread now deletes the libos handle and ends up in this `remove_pal_handle()`
- The main thread frees the object, and now the "PAL handle in the list of handles-to-wait-on" is a dangling pointer.
- Async helper thread will wake up in the future, and may accidentally touch this PAL handle and boom.

In other words, the object ownership here is incorrect: it is actually the Async helper thread who uses the LibOS handle object (and the embedded PAL handle object), so it must be the responsibility of the Async helper thread to get rid of this object (i.e. remove it from the `async_list`).

I think the solution is simple:
1. In this `remove_pal_handle()` callback you add this `hdl` to a list (you'll need a new global list "hlds-to-remove-from-list").
2. You call `set_pollable_event(&install_new_event)` to wake up the Async Helper thread.
3. You go into a busy loop waiting for the list to become empty.
4. You're done.

And in the Async helper thread context, you need the following:
1. Move your delete-from-async-list logic into `libos_async_worker()` function, somewhere after `PalStreamsWaitEvents()`.

All this logic should be correctly protected with the `async_worker_lock`.

Of course, the busy loop at step 3 is a potential performance problem. But I argue that this Async I/O deletion is so rare that we shouldn't care about performance of this logic.
___
*[`libos/src/libos_async.c` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAfwP2onHRQQGSFHC:-NoWAfwP2onHRQQGSFHD:bgufiyq) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L123)):*
> ```C
>                 LISTP_DEL(tmp, &async_list, list);
>                 if (tmp->hdl)
>                     assert(set_handle_free_callback(tmp->hdl, NULL) == remove_pal_handle);
> ```

What's the point of this? For alarms/timers, we don't have a libos handle, so you'll never get into here.

If you want to, you can add `assert(!tmp->hdl)` to be sure.


<!-- Sent from Reviewable.io -->

2024-01-19 13:13 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721)* status: 0 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`libos/include/libos_handle.h` line 160 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWB4iR626a94Ho_JgI:-NoWaCmWDTxGyC3uRPKe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, the name is too generic. This field is used particularly to set up the Async helper thread deletion event.

Otherwise, imagine we'll have a handle that can be both added to the Async helper thread (as done in this PR) **and** it needs some e.g. file-system cleanup. Then there should be **two events** called, but we have only one field, and one of the event setups' will override the other, and we have a "lost event".

So, let's make it very clear and call it `free_in_async_helper_thread_callback`. Or something equally clear.
</blockquote></details>

Done.
___
*[`libos/include/libos_handle.h` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAwbJ8mLig9XrE42o:-NoWbeYV1M2dm-dAoV1C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This coding style is different from out classic style, please fix
</blockquote></details>

Done.
___
*[`libos/include/libos_handle.h` line 239 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWA_sUCT9wgz3k7JW0:-NoWatSdDS832KU5fDTK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/include/libos_handle.h#L239)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this return? Why not make the function `void`? Looks like unnecessary complication.
</blockquote></details>

Done.
___
*[`libos/src/libos_async.c` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAS6tD9aZFI1wkleP:-NoWejfGDmfaKh5W9eSK:b4ohg6v) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need for this explicit `object` field now. You can replace it with `hdl->pal_handle` everywhere.
</blockquote></details>

Done. Using a static inline...
___
*[`libos/src/libos_async.c` line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoW8PVrC1Nd2C_VoMHJ:-NoWqL1c0owUu-hJN8yN:b1vnb3e) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a wrong logic, which leads to a **dangling pointer bug**.

Imagine we have two threads: one main thread and one Async helper thread.
- The main thread installs the Async I/O libos handle
- Async helper thread adds this libos handle's PAL handle to its list of handles-to-wait-on
- Async helper thread calls `PalStreamsWaitEvents()` and sleeps on it
- The main thread now deletes the libos handle and ends up in this `remove_pal_handle()`
- The main thread frees the object, and now the "PAL handle in the list of handles-to-wait-on" is a dangling pointer.
- Async helper thread will wake up in the future, and may accidentally touch this PAL handle and boom.

In other words, the object ownership here is incorrect: it is actually the Async helper thread who uses the LibOS handle object (and the embedded PAL handle object), so it must be the responsibility of the Async helper thread to get rid of this object (i.e. remove it from the `async_list`).

I think the solution is simple:
1. In this `remove_pal_handle()` callback you add this `hdl` to a list (you'll need a new global list "hlds-to-remove-from-list").
2. You call `set_pollable_event(&install_new_event)` to wake up the Async Helper thread.
3. You go into a busy loop waiting for the list to become empty.
4. You're done.

And in the Async helper thread context, you need the following:
1. Move your delete-from-async-list logic into `libos_async_worker()` function, somewhere after `PalStreamsWaitEvents()`.

All this logic should be correctly protected with the `async_worker_lock`.

Of course, the busy loop at step 3 is a potential performance problem. But I argue that this Async I/O deletion is so rare that we shouldn't care about performance of this logic.
</blockquote></details>

Done. Using a PalEvent to wait for the async worker to indicate that it is done, though.
___
*[`libos/src/libos_async.c` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAfwP2onHRQQGSFHC:-NoWqWIE3XydZxI7XQ4J:b-ohmpjq) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this? For alarms/timers, we don't have a libos handle, so you'll never get into here.

If you want to, you can add `assert(!tmp->hdl)` to be sure.
</blockquote></details>

Done. These asserts were due to the generic name of the field ...


<!-- Sent from Reviewable.io -->

2024-01-19 14:24 UTC, stefanberger commented
*[`libos/src/libos_async.c` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoX5tfY8Xqw0-HWneOv:-NoX5tfY8Xqw0-HWneOw:b-wcpl1n) ([raw file](https://github.com/gramineproject/gramine/blob/7846718b7f76683ae2bd365fa0ed375d26c218ef/libos/src/libos_async.c#L105)):*
> ```C
>     INIT_LIST_HEAD(&remove_event, list);
>     LISTP_ADD_TAIL(&remove_event, &hdls_to_remove_from_list, list);
>     assert(!PalEventCreate(&remove_event.done_notifier, /*init_signaled=*/false, /*auto_clear=*/false));
> ```

I thought using an event was better than polling on an empty list but then there's this assert due to potential OOM condition...


<!-- Sent from Reviewable.io -->

2024-01-19 14:28 UTC, stefanberger commented
*[`libos/include/libos_handle.h` line 233 at r2](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoX6enjBEjtWkDCuHvX:-NoX6enjBEjtWkDCuHvY:bix7hzq) ([raw file](https://github.com/gramineproject/gramine/blob/7846718b7f76683ae2bd365fa0ed375d26c218ef/libos/include/libos_handle.h#L233)):*
> ```objc
> 
> /* Callback to call before freeing libos_handle */
> static inline void set_handle_free_callback(struct libos_handle* hdl,
> ```

This function name may now also be a bit too generic though it becomes so long when I call it set_handle_free_async_helper_thread_callback().


<!-- Sent from Reviewable.io -->

2024-01-22 19:36 UTC, stefanberger reviewed
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-01-30 17:09 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_handle.h` line 233 at r2](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoX6enjBEjtWkDCuHvX:-NpQLDbv8zs3bDCXcjOk:ba2525q) ([raw file](https://github.com/gramineproject/gramine/blob/7846718b7f76683ae2bd365fa0ed375d26c218ef/libos/include/libos_handle.h#L233)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This function name may now also be a bit too generic though it becomes so long when I call it set_handle_free_async_helper_thread_callback().
</blockquote></details>

@dimakuv Should I use the above mentioned function name as well?


<!-- Sent from Reviewable.io -->

2024-03-06 22:37 UTC, stefanberger reviewed
Any more comments?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721#-:-NsKuaaB7dX_VyL3Z-Gb:bpcz3h5)* status: 5 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-08-12 20:35 UTC, mkow commented
*[`libos/src/libos_async.c` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O46LsDCDnOWNl9FDDat:-O46LsDCDnOWNl9FDDau:beziv4i) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L62)):*
> ```C
> /* Remove a libos_handle from the async_list; caller must hold async_worker_lock */
> static void async_list_remove_pal_handle(struct libos_handle* hdl) {
>     struct async_event* tmp, *n;
> ```

Multiple pointers in a single line are not allowed, because of the left-alignment of our asterisks: https://gramine.readthedocs.io/en/stable/devel/coding-style.html#code-formatting


<!-- Sent from Reviewable.io -->

2024-08-12 22:55 UTC, mkow commented
*[`libos/src/libos_async.c` line 105 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O47nI2C-Houm2CP7aiV:-O47nI2C-Houm2CP7aiW:b-ezdvwt) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L105)):*
> ```C
>     INIT_LIST_HEAD(&remove_event, list);
>     LISTP_ADD_TAIL(&remove_event, &hdls_to_remove_from_list, list);
>     assert(!PalEventCreate(&remove_event.done_notifier, /*init_signaled=*/false, /*auto_clear=*/false));
> ```

This call is completely erased from release builds.


<!-- Sent from Reviewable.io -->

2024-08-12 22:58 UTC, mkow commented
*[`libos/src/libos_async.c` line 105 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O47nI2C-Houm2CP7aiV:-O47nYEN8iXOBcf4BfFe:b-zen1qj) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This call is completely erased from release builds.
</blockquote></details>

Have you tested this code in Release mode? It should just crash just a few lines below, if any test uses this function (if not, then then it means that this PR doesn't include enough tests).


<!-- Sent from Reviewable.io -->

2024-08-14 04:41 UTC, kailun-qin requested changes
> Reviewed 3 of 10 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[`libos/src/libos_async.c` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/1721#-NoWAfwP2onHRQQGSFHC:-O4E5rW87CHTM5SXUHEh:bfhqmln) ([raw file](https://github.com/gramineproject/gramine/blob/e0472ecd28faaeec27da7b852a5feea300edb937/libos/src/libos_async.c#L123)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done. These asserts were due to the generic name of the field ...
</blockquote></details>

Not done?
___
*[`libos/src/libos_async.c` line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4Dz497CuWknjechx7T:-O4Dz497CuWknjechx7U:beqgzpj) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L60)):*
> ```C
> 
> 
> /* Remove a libos_handle from the async_list; caller must hold async_worker_lock */
> ```

Can we add it as asserts?



_Code quote:_
```C
caller must hold async_worker_lock
```
___
*[`libos/src/libos_async.c` line 105 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O47nI2C-Houm2CP7aiV:-O4DwkDD8wL2aZxWiEAx:bd6zuzw) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Have you tested this code in Release mode? It should just crash just a few lines below, if any test uses this function (if not, then then it means that this PR doesn't include enough tests).
</blockquote></details>

+1, the test only checks that no assertion occured (the one reported in the original issue: https://github.com/gramineproject/gramine/issues/1525) but does not check if the test would run successfully: https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/test/regression/test_libos.py#L1006
___
*[`libos/src/libos_async.c` line 115 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4E8acz7VH9iUmpVuQ3:-O4E8acz7VH9iUmpVuQ4:b-rfki8w) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L115)):*
> ```C
> }
> ```

redundant empty line?
___
*[`libos/src/libos_async.c` line 126 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4E9wN-AkrBcFqEu4eo:-O4E9wN-AkrBcFqEu4ep:bhlabpn) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L126)):*
> ```C
>  *   - alarm/timer events set object = NULL and time_us = microseconds
>  *     (time_us = 0 cancels all pending alarms/timers).
>  *   - async IO events set object = handle and time_us = 0.
> ```

Pls update this accordinly



_Code quote:_
```C
 *   - alarm/timer events set object = NULL and time_us = microseconds
 *     (time_us = 0 cancels all pending alarms/timers).
 *   - async IO events set object = handle and time_us = 0.
```
___
*[`libos/src/libos_async.c` line 131 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4E9rg67OBTKywlmKiR:-O4E9rg67OBTKywlmKiS:b-mfwcti) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/src/libos_async.c#L131)):*
> ```C
>  * or 0 for async IO events. On error, it returns a negated error code.
>  */
> int64_t install_async_event(struct libos_handle *hdl, uint64_t time_us,
> ```

Pls also update the comment here: https://github.com/gramineproject/gramine/blob/0c0971cd6930400b39b42eb92656b3968ae75698/libos/src/sys/libos_alarm.c#L69.
___
*[`libos/test/regression/async_task_shutdown.c` line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4DxkbbCaqzx6SW195j:-O4DxkbbCaqzx6SW195k:bfcmsrx) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/test/regression/async_task_shutdown.c#L12)):*
> ```C
> #include <stdio.h>
> #include <sys/ioctl.h>
> #include <sys/wait.h>
> ```

Can we sort the headers?
___
*[`libos/test/regression/async_task_shutdown.c` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4DylO748vXyQNe3-hm:-O4DylO748vXyQNe3-hn:bsksmf7) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/test/regression/async_task_shutdown.c#L13)):*
> ```C
> #include <sys/ioctl.h>
> #include <sys/wait.h>
> ```

Can we follow the conventions for testing here (e.g., using `CHECK()` macro, checking "TEST OK" etc.)?
___
*[`libos/test/regression/test_libos.py` line 1004 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4DxuZW6vsDusGRxfo3:-O4DxuZW6vsDusGRxfo4:bfsuqg7) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/test/regression/test_libos.py#L1004)):*
> ```Python
> 
>     def test_160_async_task_shutdown(self):
>         for i in range(0, 200):
> ```

I understand the assertion happens occasionally, only when async helper thread executes into it -- but this would run the test 200 times which would take quite amount of time



_Code quote:_
```Python
for i in range(0, 200):
```
___
*[`libos/test/regression/test_libos.py` line 1006 at r3](https://reviewable.io/reviews/gramineproject/gramine/1721#-O4DxoAf5arJvnkMob8g:-O4DxoAf5arJvnkMob8h:b-dpmap) ([raw file](https://github.com/gramineproject/gramine/blob/b19ba95232546afe04becd1a2bed160c0ae36205/libos/test/regression/test_libos.py#L1006)):*
> ```Python
>         for i in range(0, 200):
>             _, stderr = self.run_binary(['async_task_shutdown'])
>             self.assertNotIn('assert failed', stderr)
> ```

I think we should also check the test actually completes successfully



_Code quote:_
```Python
self.assertNotIn('assert failed', stderr)
```


<!-- Sent from Reviewable.io -->

2024-09-09 18:39 UTC, closed without merging

2024-09-11 23:42 UTC, monavij commented
@stefanberger Why did you close this PR? Is this issue resolved by some other PR?

2024-09-12 11:50 UTC, stefanberger commented
> @stefanberger Why did you close this PR? Is this issue resolved by some other PR?

I think https://github.com/gramineproject/gramine/pull/1992 solved it.

2024-09-24 23:05 UTC, kailun-qin commented
> I think https://github.com/gramineproject/gramine/pull/1992 solved it.

@jinengandhi-intel: can we check if https://github.com/gramineproject/gramine/pull/1992 resolves the original issue: https://github.com/gramineproject/gramine/issues/1525?

2024-09-25 03:15 UTC, jinengandhi-intel reviewed
This issue was consistently seen when we ran Syzkaller based fuzzing, we plan to trigger the fuzzing runs once we code freeze for Gramine v1.8, which should be in a  day or two, I will keep an eye out for this and update the same here.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1721#-:-O7b9dxo9FhkqYtizS7m:bxivzul)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)



<!-- Sent from Reviewable.io -->