WIP `gramine-manifest-check` tool
gramineproject/gramine pull request #1726
Opened 2024-01-19 23:31 UTC by woju

## Description of the changes 

Linter for gramine manifest. Parser in the actual application is permissive, silently ignores unknown keys in manifest. This optional tool will warn about unknown options (probably mistyped real things!).

## How to test this PR? 

Go get any manifest (and/or manifest.sgx) and feed it to this tool. If there's no output and 0 exit code, then manifest should be OK. If the manifest is not OK, exit code should be != 0 and some explanation should be written to stdout.

2024-01-22 07:49 UTC, dimakuv reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7ZsBEn60EnIBrkpz:-Nok7ZsBEn60EnIBrkq-:bucfyf7) (no related file):*
CI fails with:
```
make: gramine-manifest-check: Command not found
```

Aren't you supposed to change some `meson.build` to install this tool?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7czOC6QrSD-irSwq:-Nok7czOC6QrSD-irSwr:bthw85p) (no related file):*
Can we add the call to this tool into `gramine-manifest`? It should be a new argument, and it should be disabled by default.

And we enable it for all our CI examples and for all our PAL/LibOS tests. This will we have the testing for both the new tool and for the manifest schema.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok8BhA9KAmtczhaTa6:-Nok8BhA9KAmtczhaTa7:bclxxh1) (no related file):*
What about non-Debian distros? I guess you need to modify them too?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok8F6r3gJOixNmUnRX:-Nok8F6r3gJOixNmUnRY:b-rp930v) (no related file):*
Brilliant PR!

___
___
*[`CI-Examples/helloworld/Makefile` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7zwKE8K8sfeFanu2:-Nok7zwKE8K8sfeFanu3:b-5di2h3) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/CI-Examples/helloworld/Makefile#L28)):*
> ```Makefile
> 		-Dlog_level=$(GRAMINE_LOG_LEVEL) \
> 		$< $@
> 	gramine-manifest-check $@
> ```

I suggest to incorporate the check into `gramine-manifest`
___
*[`CI-Examples/helloworld/Makefile` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok82Xf2YJs33bMklQ1:-Nok82Xf2YJs33bMklQ2:bal34av) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/CI-Examples/helloworld/Makefile#L51)):*
> ```Makefile
> 		--manifest $< \
> 		--output $<.sgx
> 	gramine-manifest-check $<.sgx
> ```

Here I'm not sure, I would just remove this change.

We could check final `.sgx` manifests' schemas in LibOS regression tests, that should be enough coverage.
___
*[`python/graminelibos/manifest_check.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok2ZwU4gI3zKu3pEWd:-Nok2ZwU4gI3zKu3pEWe:b-wrp0wx) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L23)):*
> ```Python
>             },
>             {
>                 'type': Any('chroot', 'tmpfs', 'untrusted_shm'),
> ```

`tmpfs` doesn't have the `uri` (more correctly it's not required and always ignored), so it should be a separate item in the outer Any set
___
*[`python/graminelibos/manifest_check.py` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok3RKs6ZJeN_lq4TKw:-Nok3RKs6ZJeN_lq4TKx:b-rf3qj8) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L30)):*
> ```Python
>         'root': {
>             'type': Any('chroot', 'encrypted', 'tmpfs', 'untrusted_shm'),
>             'uri': str,
> ```

There is also `fs.root.key_name`: https://github.com/gramineproject/gramine/blob/a933017d35a7aa3330194521389838de6be53dc4/libos/src/fs/libos_fs.c#L128

Actually, `root` should be exactly like an item in the `fs.mounts` set. Is this possible to do in Voluptuous (declare the `fs.mounts` item description separately and use it in two places)?
___
*[`python/graminelibos/manifest_check.py` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok472p8K-mGSZki-x6:-Nok472p8K-mGSZki-x7:bpqarst) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L33)):*
> ```Python
>         },
>         'start_dir': str,
>         'insecure__keys': {str, str},
> ```

Is this a tuple syntax (array)? It should be a dict syntax:
```
fs.insecure__keys.[KEY_NAME] = "[32-character hex value]"
``` 
___
*[`python/graminelibos/manifest_check.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok4YpiB0eFGNon3Wky:-Nok4YpiB0eFGNon3Wkz:b1d4qj0) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L42)):*
> ```Python
>         Required('entrypoint'): str,
>         'argv': [str],
>         'argv_src_file': str,
> ```

Any way to specify a XOR in Voluptuous?

Here, `argv` and `argv_src_file` are mutually exclusive.
___
*[`python/graminelibos/manifest_check.py` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok5WEk5h3YDxNyRW5A:-Nok5WEk5h3YDxNyRW5B:ba6z8my) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L63)):*
> ```Python
>         'enable_stats': bool,
>         'enclave_size': _size,
>         'file_check_policy': Any('strict', 'allow_all_byt_log'),
> ```

Typo: `allow_all_but_log` (not `byt`)
___
*[`python/graminelibos/manifest_check.py` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok5yx21lfVQuOyljOx:-Nok5yx21lfVQuOyljOy:biomj3q) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L87)):*
> ```Python
>             'flags_mask': str,
>             'xfrm_mask': str,
>             'misc_mask': str,
> ```

These 3 have a specific format: https://gramine.readthedocs.io/en/stable/manifest-syntax.html#attribute-masks-for-sgx-sealing-key-derivation

Can we at least do the same as with `_size` -- create a global macro for them, and maybe later we'll add the proper formatting for them (a hex string with the `0x` prefix and exact number of digits)
___
*[`python/graminelibos/manifest_check.py` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6Ejz45PiMgQVucEE:-Nok6Ejz45PiMgQVucEF:b-578g95) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L89)):*
> ```Python
>             'misc_mask': str,
>         },
>         'trusted_files': [Any(str, {'uri': str, 'sha256': str})],
> ```

ditto for `sha256` (macro with specific format)
___
*[`python/graminelibos/manifest_check.py` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6hmFBvKxAdHTW3gh:-Nok6hmFBvKxAdHTW3gi:b-ub3135) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L96)):*
> ```Python
>         'allowed_ioctls': [{
>             Required('request_code'): int,
>             'struct': str,
> ```

This is also Required
___
*[`python/graminelibos/manifest_check.py` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6sYN63DJcOewEOCC:-Nok6sYN63DJcOewEOCD:botmrrb) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L104)):*
> ```Python
>         'experimental__enable_flock': bool,
>         'insecure__allow_eventfd': bool,
>         'ioctl_structs': {str: [{str: object}]}, # XXX: I'm afraid description of this thing is above my pay grade
> ```

Does the `object` mean "whatever"? You don't need the inner `str:`, and just in general, why not:
```
'ioctl_structs': {str: object}
```

That should be enough.


<!-- Sent from Reviewable.io -->

2024-01-24 00:07 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: 5 of 10 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7ZsBEn60EnIBrkpz:-NoscSmU7JEjlefUpLZt:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI fails with:
```
make: gramine-manifest-check: Command not found
```

Aren't you supposed to change some `meson.build` to install this tool?
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok8BhA9KAmtczhaTa6:-NosdQAp2RUiQX-k1GbU:bto0xvw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about non-Debian distros? I guess you need to modify them too?
</blockquote></details>

Done. For now it's WIP, so wasn't a priority, those other distros are not tested in CI.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok8F6r3gJOixNmUnRX:-NosdrJQBzC_iXA5whpE:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Brilliant PR!
</blockquote></details>

Thanks!

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7czOC6QrSD-irSwq:-NosduihBNGzTat2cTMZ:b-gu8k61) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add the call to this tool into `gramine-manifest`? It should be a new argument, and it should be disabled by default.

And we enable it for all our CI examples and for all our PAL/LibOS tests. This will we have the testing for both the new tool and for the manifest schema.
</blockquote></details>

That's a feature request. I'm not saying no, maybe I'll do it later, closer to finalising this PR. Plz keep this blocked.

(For the same reason I've left invocations in Makefile in helloworld example. I'll think what to do with examples later).

___
___
*[`python/graminelibos/manifest_check.py` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok2ZwU4gI3zKu3pEWd:-NoseNZm5nfC8_29dbnT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tmpfs` doesn't have the `uri` (more correctly it's not required and always ignored), so it should be a separate item in the outer Any set
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok3RKs6ZJeN_lq4TKw:-NoseWVy0TmBD5rz93O9:b-93ueht) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is also `fs.root.key_name`: https://github.com/gramineproject/gramine/blob/a933017d35a7aa3330194521389838de6be53dc4/libos/src/fs/libos_fs.c#L128

Actually, `root` should be exactly like an item in the `fs.mounts` set. Is this possible to do in Voluptuous (declare the `fs.mounts` item description separately and use it in two places)?
</blockquote></details>

Would be cleaner in JSON Schema, but here I can also do it, in global variable like `_size`.
___
*[`python/graminelibos/manifest_check.py` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok472p8K-mGSZki-x6:-NosjL8I0MsbjDpRt0qW:bemshpi) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a tuple syntax (array)? It should be a dict syntax:
```
fs.insecure__keys.[KEY_NAME] = "[32-character hex value]"
```
</blockquote></details>

This was a `set` (1-element at that). Meant "a `set` consisting of instances of `str`"). A mistake, should have been `dict`, so `:` instead of `,`.
___
*[`python/graminelibos/manifest_check.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok4YpiB0eFGNon3Wky:-NoshKw243jDHhRb01X0:b-vhnck1) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any way to specify a XOR in Voluptuous?

Here, `argv` and `argv_src_file` are mutually exclusive.
</blockquote></details>

Done.

It's ugly. Those are two separate validators, `All` means both of them needs to pass. Second one just checks this `Exclusive`, which I can't write in the first validator, because values have different types.

I think in JSON Schema this would be relatively nicer. It woudn't be prettier, but wouldn't stand out so much.
___
*[`python/graminelibos/manifest_check.py` line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok5WEk5h3YDxNyRW5A:-NoshR6hAPGMobfobdB7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `allow_all_but_log` (not `byt`)
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok5yx21lfVQuOyljOx:-Nosi7wX91_ms6XIaOsG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These 3 have a specific format: https://gramine.readthedocs.io/en/stable/manifest-syntax.html#attribute-masks-for-sgx-sealing-key-derivation

Can we at least do the same as with `_size` -- create a global macro for them, and maybe later we'll add the proper formatting for them (a hex string with the `0x` prefix and exact number of digits)
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 89 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6Ejz45PiMgQVucEE:-NosiDGd-TTecd2Uqcd_:bs593pp) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto for `sha256` (macro with specific format)
</blockquote></details>

This in only in 1 place, so probably won't be a type from global variable. I've added just a TODO for now.
___
*[`python/graminelibos/manifest_check.py` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6hmFBvKxAdHTW3gh:-NosiVjp7TlhyeQNgwyP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is also Required
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 104 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6sYN63DJcOewEOCC:-NosiWb37OB5_Ka_6Bgl:b4u1rz5) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does the [...]

2024-01-24 08:52 UTC, dimakuv reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7czOC6QrSD-irSwq:-Noueu9OBTOqOzmaboqJ:bsreadq) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

That's a feature request. I'm not saying no, maybe I'll do it later, closer to finalising this PR. Plz keep this blocked.

(For the same reason I've left invocations in Makefile in helloworld example. I'll think what to do with examples later).
</blockquote></details>

Yes, please think about this later, but after the discussion in the Gramine meeting, I'm neutral on this.

___
___
*[`CI-Examples/helloworld/Makefile` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7zwKE8K8sfeFanu2:-NoueXCT7__cwxKBA6Qq:b-e3cpju) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/CI-Examples/helloworld/Makefile#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to incorporate the check into `gramine-manifest`
</blockquote></details>

As discussed in the meeting: maybe it makes more sense to keep it only as a separate tool (as done now). People anyway write scripts/Makefiles to hide the complexity of building a manifest, so the tool invocation can be plugged in there. I'm unblocking.
___
*[`CI-Examples/helloworld/Makefile` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok82Xf2YJs33bMklQ1:-NouelxPDIPMSIBbOFOK:b-2sglrm) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/CI-Examples/helloworld/Makefile#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here I'm not sure, I would just remove this change.

We could check final `.sgx` manifests' schemas in LibOS regression tests, that should be enough coverage.
</blockquote></details>

ditto (unblocking)
___
*[`python/graminelibos/manifest_check.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok4YpiB0eFGNon3Wky:-Noucqr_2szMKZrFINJG:bl16okd) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.

It's ugly. Those are two separate validators, `All` means both of them needs to pass. Second one just checks this `Exclusive`, which I can't write in the first validator, because values have different types.

I think in JSON Schema this would be relatively nicer. It woudn't be prettier, but wouldn't stand out so much.
</blockquote></details>

Oh my. Can we revert this? Cognitive complexity of this outweighs the benefit.
___
*[`python/graminelibos/manifest_check.py` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nouc-5a50_MSUXdWQDX:-Nouc-5a50_MSUXdWQDY:b-td3k45) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L21)):*
> ```Python
>     },
>     {
>         'type': 'tmpfs',
> ```

This should also be `Required()`?
___
*[`python/graminelibos/manifest_check.py` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nouc1FQ85e5c52c5ciI:-Nouc1FQ85e5c52c5ciJ:b-6inis5) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L26)):*
> ```Python
>     },
>     {
>         'type': Any('chroot', 'untrusted_shm'),
> ```

This should also be `Required()`?

Or maybe even split into two items? Then we'll have a clear structure here -- every type of FS will have its own sub-schema. A bit redundant, but I think more readable.
___
*[`python/graminelibos/manifest_check.py` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-NoucULv1pgLKy6EsCRT:-NoucULw7pH8BXHKP6KH:bfjyoue) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L36)):*
> ```Python
> _size = str
> 
> # masks in for sgx.seal_key.*_mask fields
> ```

`in for`? Use just one of them.


<!-- Sent from Reviewable.io -->

2024-01-24 10:44 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: 9 of 12 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok7czOC6QrSD-irSwq:-Nov3RcUBl4uXq_JaxnZ:b-eh9vox) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please think about this later, but after the discussion in the Gramine meeting, I'm neutral on this.
</blockquote></details>

I've added a check to gramine-manifest, but I'm still not sure. Let's see what happens in CI.

___
___
*[`python/graminelibos/manifest_check.py` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok4YpiB0eFGNon3Wky:-NouzNe1D6r1D60zGOj0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh my. Can we revert this? Cognitive complexity of this outweighs the benefit.
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nouc-5a50_MSUXdWQDX:-Nouxwaf47SvfDlrXWGJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should also be `Required()`?
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nouc1FQ85e5c52c5ciI:-NouxydY-8TVdR3ZsrV3:bkrq5bf) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should also be `Required()`?

Or maybe even split into two items? Then we'll have a clear structure here -- every type of FS will have its own sub-schema. A bit redundant, but I think more readable.
</blockquote></details>

No, this shouldn't be `Required`: if type is missing, then it's `chroot`: https://github.com/gramineproject/gramine/blob/a933017d35a7aa3330194521389838de6be53dc4/libos/src/fs/libos_fs.c#L272.

Yes, at this point splitting is a very good idea.
___
*[`python/graminelibos/manifest_check.py` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1726#-NoucULv1pgLKy6EsCRT:-NouyvNGDapdPi3jgzhZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/62d2c37657e82f5a7a82a9d5dc4e2e52e2b0eaf3/python/graminelibos/manifest_check.py#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in for`? Use just one of them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 10:51 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-01-25 07:32 UTC, dimakuv reviewed
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pal/regression/tests.toml` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1726#-NozWkfz0efxlY7fl_1R:-NozWkg-DG6NlJBrkIgy:b-ii6y2x) ([raw file](https://github.com/gramineproject/gramine/blob/7b6af3ddc7f3b942d5fc3db95fbf03a137bdda1c/pal/regression/tests.toml#L2)):*
> ```TOML
> binary_dir = "@GRAMINE_PKGLIBDIR@/tests/pal"
> no-check = true
> ```

This deserves a comment why we disable `gramine-manifest-check` for PAL tests (because they don't contain certain fields that we consider required in normal, LibOS-based, application manifests).
___
*[`python/graminelibos/manifest_check.py` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1726#-NozX3iWAY7qzAmyGYrw:-NozX3iWAY7qzAmyGYrx:b-twh356) ([raw file](https://github.com/gramineproject/gramine/blob/7b6af3ddc7f3b942d5fc3db95fbf03a137bdda1c/python/graminelibos/manifest_check.py#L44)):*
> ```Python
> 
> _fs_root = Any(*_fs_base)
> _fs_mount = Any(*({**d, Required('path'): str} for d in _fs_base))
> ```

Awesome solution! I even understand it.


<!-- Sent from Reviewable.io -->

2024-01-25 08:41 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: 13 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[`pal/regression/tests.toml` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1726#-NozWkfz0efxlY7fl_1R:-Nozl_Z3EPtXJhR-evSf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b6af3ddc7f3b942d5fc3db95fbf03a137bdda1c/pal/regression/tests.toml#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This deserves a comment why we disable `gramine-manifest-check` for PAL tests (because they don't contain certain fields that we consider required in normal, LibOS-based, application manifests).
</blockquote></details>

Done.
___
*[`python/graminelibos/manifest_check.py` line 96 at r1](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nok6hmFBvKxAdHTW3gh:-NozjmAz7BFdk3gDLHTC:b-32wbj4) ([raw file](https://github.com/gramineproject/gramine/blob/cfe1527d49aad8147a7e8024a3339aafd7e6ebf7/python/graminelibos/manifest_check.py#L96)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@dimakuv is it really?

https://github.com/gramineproject/gramine/blob/36676a75e9897c9b7b183157a9d9fcdf2f668a13/libos/test/regression/device_ioctl.manifest.template#L61-L64
___
*[`python/graminelibos/manifest_check.py` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1726#-NozX3iWAY7qzAmyGYrw:-NozkDE2CQn_vtbU6S7a:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/7b6af3ddc7f3b942d5fc3db95fbf03a137bdda1c/python/graminelibos/manifest_check.py#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome solution! I even understand it.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2024-01-25 13:31 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/manpages/gramine-manifest-check.rst` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1726#-Np-o1nzApPwWMoUHI4T:-Np-o1o-EriuBDAuLorB:bvv2oic) ([raw file](https://github.com/gramineproject/gramine/blob/c95d611a7b212b8ff7bc2fdf05d82985157f0570/Documentation/manpages/gramine-manifest-check.rst#L28)):*
> ```reStructuredText
> implementation (``libsysdb.so``) are considered allowed/mandatory in schema.
> Therefore, if you have another LibOS implementation (like it happens in PAL
> test suite), the check may be wrong.
> ```

This is an internal detail that 99% of users will not understand... Do we really want it in this user-facing document?


<!-- Sent from Reviewable.io -->

2024-01-25 14:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/manpages/gramine-manifest-check.rst` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1726#-Np-o1nzApPwWMoUHI4T:-Np05sZ052O3gMqMEmX-:bzid2ff) ([raw file](https://github.com/gramineproject/gramine/blob/c95d611a7b212b8ff7bc2fdf05d82985157f0570/Documentation/manpages/gramine-manifest-check.rst#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is an internal detail that 99% of users will not understand... Do we really want it in this user-facing document?
</blockquote></details>

I want this written somewhere, for completeness. I will forget this in a month.


<!-- Sent from Reviewable.io -->

2024-01-25 15:20 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`Documentation/manpages/gramine-manifest-check.rst` line 28 at r6](https://reviewable.io/reviews/gramineproject/gramine/1726#-Np-o1nzApPwWMoUHI4T:-Np0BRSp8uulxZYNCCjv:b-dssqr5) ([raw file](https://github.com/gramineproject/gramine/blob/c95d611a7b212b8ff7bc2fdf05d82985157f0570/Documentation/manpages/gramine-manifest-check.rst#L28)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I want this written somewhere, for completeness. I will forget this in a month.
</blockquote></details>

Well, yeah, ok. Almost nobody (other than hard-core users) reads these manual pages anyway, so having such details is probably more useful than not.


<!-- Sent from Reviewable.io -->

2024-04-19 13:50 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-22 17:17 UTC, dimakuv approved these changes
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-22 23:57 UTC, mkow requested changes
> Reviewed 4 of 6 files at r1, 2 of 5 files at r2, 3 of 6 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 7 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw6vnLS58q9vcfFp23v:-Nw6vnLS58q9vcfFp23w:b-gxeugd) (no related file):*
TODO before merge: check commit split.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw7316P2g2jHYuMTPHA:-Nw7316P2g2jHYuMTPHB:bsvny44) (no related file):*
This PR failed to build on RTD: https://readthedocs.org/projects/gramine/builds/24147011/, please check.

___
___
*[`Documentation/conf.py` line 150 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw72WPR-Us3FDs6f_nd:-Nw72WPR-Us3FDs6f_ne:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/Documentation/conf.py#L150)):*
> ```Python
>     'click': ('https://click.palletsprojects.com/en/latest', None),
>     'cryptography': ('https://cryptography.io/en/latest', None),
>     'voluptuous': ('http://alecthomas.github.io/voluptuous/docs/_build/html', None),
> ```





_Suggestion:_
```Python
https://alecthomas.github.io/voluptuous/docs/_build/html
```
___
*[`pal/regression/tests.toml` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw76OvHCDrDDG87U08O:-Nw76OvI5LDycMk8Ef9-:bt06wr9) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/pal/regression/tests.toml#L7)):*
> ```TOML
> # do here is, we run libos replacements and manifests for those don't include entries that are
> # normally required by libsysdb. Therefore we need to disable schema checking.
> no-check = true
> ```

Just `no-check` as a global switch in `tests.toml` is too broad of a name IMO.



_Suggestion:_
```TOML
no-manifest-schema-check = true
```
___
*[`python/gramine-manifest-check` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw78n8s9E1OeY04SBwb:-Nw78n8s9E1OeY04SBwc:b69dong) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/gramine-manifest-check#L3)):*
> ```
> #!/usr/bin/python3
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2024 Wojtek Porczyk <woju@invisiblethingslab.com>
> ```

This should be Intel.
ditto for the whole PR
___
*[`python/gramine-manifest-check` line 4 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw79aKICx9Ai1ujL3Hk:-Nw79aKICx9Ai1ujL3Hl:b-pme2pg) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/gramine-manifest-check#L4)):*
> ```
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2024 Wojtek Porczyk <woju@invisiblethingslab.com>
> ```

I'd add a comment (or a doc paragraph) that this tool assumes that the input is a properly formatted TOML. Otherwise it prints an ugly stacktrace instead of a nice error to the user (which is probably ok here, because in normal flows it's being run on the output of `gramine-manifest`, which parses TOML and fails first (with an ugly stacktrace, so it should get a fix someday)).
___
*[`python/graminelibos/manifest_check.py` line 35 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw7BhEa2kyLz-VKw4oM:-Nw7BhEa2kyLz-VKw4oN:b-i94u6w) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/graminelibos/manifest_check.py#L35)):*
> ```Python
>     {
>         Required('type'): 'tmpfs',
>         'uri': str, # not _uri, this is ignored
> ```

It was a bit unclear to me at the first reading



_Suggestion:_
```Python
# not _uri, this field is ignored by Gramine
```


<!-- Sent from Reviewable.io -->

2024-04-23 08:04 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: 13 of 19 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw7316P2g2jHYuMTPHA:-Nw8tuQK4LBUyMz74Yap:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This PR failed to build on RTD: https://readthedocs.org/projects/gramine/builds/24147011/, please check.
</blockquote></details>

Done.

___
___
*[`Documentation/conf.py` line 150 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw72WPR-Us3FDs6f_nd:-Nw8twIP5meX_i1I_y_J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/Documentation/conf.py#L150)):*
> ```Python
>     'click': ('https://click.palletsprojects.com/en/latest', None),
>     'cryptography': ('https://cryptography.io/en/latest', None),
>     'voluptuous': ('http://alecthomas.github.io/voluptuous/docs/_build/html', None),
> ```

Done.
___
*[`pal/regression/tests.toml` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw76OvHCDrDDG87U08O:-Nw8xbLHEf3NDR1xPlAP:bywu1tp) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/pal/regression/tests.toml#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just `no-check` as a global switch in `tests.toml` is too broad of a name IMO.
</blockquote></details>

I did `gramine-manifest-no-check` to match the cli option.
___
*[`python/gramine-manifest-check` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw78n8s9E1OeY04SBwb:-Nw8ufmd0p8JV65JJmVM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/gramine-manifest-check#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be Intel.
ditto for the whole PR
</blockquote></details>

Done.
___
*[`python/gramine-manifest-check` line 4 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw79aKICx9Ai1ujL3Hk:-Nw8wjov1oFpSALMr48t:bnfkp22) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/gramine-manifest-check#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add a comment (or a doc paragraph) that this tool assumes that the input is a properly formatted TOML. Otherwise it prints an ugly stacktrace instead of a nice error to the user (which is probably ok here, because in normal flows it's being run on the output of `gramine-manifest`, which parses TOML and fails first (with an ugly stacktrace, so it should get a fix someday)).
</blockquote></details>

This is a trivial fix, so I'll fix here, and `gramine-manifest` we'll fix someday. Please file a bug if you care enough. :)
___
*[`python/graminelibos/manifest_check.py` line 35 at r8](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw7BhEa2kyLz-VKw4oM:-Nw8xDDj5GSxKzPer_ZX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64f857fe332b3094a7ca4bdd4fa3bdd79b49b452/python/graminelibos/manifest_check.py#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was a bit unclear to me at the first reading
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-23 08:26 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 7 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2024-04-23 12:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw9fchN1oPH-r6MGniZ:-Nw9jbGpBDz6ikB6Vltj:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add "Fixes https://github.com/gramineproject/gramine/issues/1336" to the PR description on GitHub.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-04-23 14:21 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-04-23 15:06 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1726)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-04-23 16:41 UTC, merged