[LibOS] Add secure implementation of eventfd
gramineproject/gramine pull request #1728
Opened 2024-01-23 12:59 UTC by dimakuv

## Description of the changes 

The previous implementation of eventfd was insecure and disabled by default (enabled via `sys.insecure__allow_eventfd` manifest option). The new implementation of eventfd is secure but currently restricted to a single process. Thus, Gramine fails by default if eventfd is used and fork is issued. However, sometimes it is possible to use this secure implementation of eventfd in multi-process apps (if child processes do not use the parent's eventfd object and vice versa); to support these cases, we introduce the `sys.experimental__allow_eventfd_fork` manifest option.

LibOS regression tests are added to test the secure implementation of eventfd. Memcached and Rust examples also use the secure eventfd now.

This eventfd implementation is an adaption of my tiny implementation of eventfd from Gramine-TDX PAL: https://github.com/gramineproject/gramine-tdx/blob/intel_tdx/pal/src/host/vm-common/pal_common_eventfd.c. A big difference is that I use host's eventfd object for notifications (e.g. for select/poll/epoll) in this PR.

## How to test this PR? 

LibOS tests included. Memcached and Rust Tokyo server are modified to not use the insecure eventfd version.

2024-01-23 13:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP-Ap2yUtpsGcb1r0:-NoqP-Aq2_l-U86NUhT6:bchte0u) (no related file):*
Blocked on prerequisite PR https://github.com/gramineproject/gramine/pull/1727

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP2xvExydRQBaCv_a:-NoqP2xvExydRQBaCv_b:b-1pt1q4) (no related file):*
TODO: Rebase to new version of https://github.com/gramineproject/gramine/pull/1727 when I'm done with changes/comments there.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP94D800f1I_bd0JB:-NoqP94E7pfR30UkP6vd:b6hx4cd) (no related file):*
See companion PR in examples repo: https://github.com/gramineproject/examples/pull/91

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP_d7-AwJ_5n4UiJ5:-NoqP_d7-AwJ_5n4UiJ6:b-fozn4f) (no related file):*
TODO: Temporarily enable ReadTheDocs and check how Documentation looks there.

___


<!-- Sent from Reviewable.io -->

2024-01-23 20:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoruNc_5KNxCfLN7OWp:-NoruNc_5KNxCfLN7OWq:b-n9kpg6) (no related file):*
FYI: Memcached usage of eventfd: https://github.com/memcached/memcached/commit/c25d0bd68ab0f6226c2d979bf0951923624926dd

Some context on how multithreading & notifications work in Memcached: https://holmeshe.me/understanding-memcached-source-code-VII/#Inter-thread-communication

So it's simple:
- A dispatcher thread creates as many eventfds as there are worker threads.
- Each eventfd is used by the dispatcher to send notifications, and each worker thread waits on epoll for notifications (including from this worker-thread's eventfd). The worker threads receive notifications via epoll and then perform `read()` to "flush" the notification state (reset eventfd integer to zero).

So from the security perspective, this PR should be good: this PR checks the state of eventfd during `read()` and will block if a malicious host injected an eventfd notification into epoll revents. Only when the dispatcher thread sends a `write()`, then `read()` will become unblocked.

___


<!-- Sent from Reviewable.io -->

2024-01-24 12:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 16 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NovVO_T8yOU7iKxgtMJ:-NovVO_T8yOU7iKxgtMK:b14f08l) (no related file):*
**TODO**: security bug in my PR.

I looked at Rust Tokio use of eventfd. More specifically, Tokio uses the `mio` (Metal I/O) library: https://github.com/tokio-rs/mio

So the relevant code starts here: https://github.com/tokio-rs/mio/blob/08ee541bf00c2cc81f9acc5486851ca1d59c25a3/src/sys/unix/waker.rs#L74

So, it looks like the `read()` on eventfd is basically unused/ignored. The only really used syscalls are `write()` (to trigger the thread wake up event) and `epoll_wait()` (to wait for a wake up).

Since this PR's security check happens inside `read()`, it may be *not called at all*, and a maliciously injected eventfd notification into `epoll_wait()` will remain un-checked by Gramine. But it will be delivered to the application as a result of `epoll_wait()`, potentially leading to incorrect synchronization. **I must fix this**!

Solution: introduce a `post_poll()` callback to `epoll_wait()` and `select()`. Each FS type that wants to verify polling of the object (e.g. an eventfd object) must implement this callback.

___


<!-- Sent from Reviewable.io -->

2024-01-24 14:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NovVO_T8yOU7iKxgtMJ:-NovqHoc8PmEs4XorJfs:b-tlczwh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

**TODO**: security bug in my PR.

I looked at Rust Tokio use of eventfd. More specifically, Tokio uses the `mio` (Metal I/O) library: https://github.com/tokio-rs/mio

So the relevant code starts here: https://github.com/tokio-rs/mio/blob/08ee541bf00c2cc81f9acc5486851ca1d59c25a3/src/sys/unix/waker.rs#L74

So, it looks like the `read()` on eventfd is basically unused/ignored. The only really used syscalls are `write()` (to trigger the thread wake up event) and `epoll_wait()` (to wait for a wake up).

Since this PR's security check happens inside `read()`, it may be *not called at all*, and a maliciously injected eventfd notification into `epoll_wait()` will remain un-checked by Gramine. But it will be delivered to the application as a result of `epoll_wait()`, potentially leading to incorrect synchronization. **I must fix this**!

Solution: introduce a `post_poll()` callback to `epoll_wait()` and `select()`. Each FS type that wants to verify polling of the object (e.g. an eventfd object) must implement this callback.
</blockquote></details>

Done, fixed in a fixup PR by introducing `post_poll()`.

___
___
*[`libos/src/sys/libos_epoll.c` line 682 at r2](https://reviewable.io/reviews/gramineproject/gramine/1728#-NovqZYOC6NJBUc1hCwn:-NovqZYOC6NJBUc1hCwo:blk8twj) ([raw file](https://github.com/gramineproject/gramine/blob/13c0224b943cf52abe2108a7b71983344fa3e277/libos/src/sys/libos_epoll.c#L682)):*
> ```C
>             }
> 
>             /* TODO: move this to socket FS's post_poll() callback */
> ```

Blocking myself not to forget to create such a PR when this PR will be ready for final merge.
___
*[`libos/src/sys/libos_poll.c` line 221 at r2](https://reviewable.io/reviews/gramineproject/gramine/1728#-Novqedu8nFR56kyyvKP:-Novqedu8nFR56kyyvKQ:blk8twj) ([raw file](https://github.com/gramineproject/gramine/blob/13c0224b943cf52abe2108a7b71983344fa3e277/libos/src/sys/libos_poll.c#L221)):*
> ```C
>             fds[i].revents |= fds[i].events & (POLLOUT | POLLWRNORM);
> 
>         /* TODO: move this to socket FS's post_poll() callback */
> ```

Blocking myself not to forget to create such a PR when this PR will be ready for final merge.


<!-- Sent from Reviewable.io -->

2024-01-24 14:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NovvKUDBxfuUkvU8_zK:-NovvKUDBxfuUkvU8_zL:b-1ivou9) (no related file):*
FYI: MongoDB usage of eventfd:
- https://github.com/mongodb/mongo/blob/332222f6b3614afab114af7d907f5643e04f4e30/src/mongo/transport/asio/asio_networking_baton.cpp#L68
- https://github.com/mongodb/mongo/blob/332222f6b3614afab114af7d907f5643e04f4e30/docs/baton.md?plain=1#L44

This usage is as trivial as it gets:
- Threads are blocked (waiting) and unblocked (notified) using eventfd
- Only `write(eventfd)` and `read(eventfd)` are used
- Only value of `1` is written, which means increments by one
- No select/poll/epoll is used

So our PR is good: we have validations on `write()` and `read()`.

___


<!-- Sent from Reviewable.io -->

2024-01-26 07:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 19 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-Np3f0PB5U3YZU2tm5-v:-Np3f0PB5U3YZU2tm5-w:bnwvp3y) (no related file):*
TODO: I think I have a data race in handling the dummy host-based eventfd object. This is because we do blocking `PalStreamRead()` and `PalStreamWrite()` without the spinlock, so e.g. two reader threads may race on the same eventfd event, one of them wins and updates `dummy_host_val` and the other one looses and gets an unexpected `dummy_host_val`.

I need to add one new LibOS regression test `eventfd_races.c` and add several sub-tests in there:
1. Two blocking readers and one writer: both block with `read()`
2. Two blocking readers and one writer: one blocks with `read()` and another one blocks with `poll()` or `epoll()`
3. Two blocking writers and one reader
4. Two blocking readers and two blocking writers

Each sub-test must run like 10,000 events, to trigger data races with high probability.

___


<!-- Sent from Reviewable.io -->

2024-01-26 12:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 21 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "WIP" found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-Np4nVtR6jCa2LzcGMBY:-Np4nVtR6jCa2LzcGMBZ:buib7lx) (no related file):*
Blocked on prerequisite PR https://github.com/gramineproject/gramine/pull/1736

For now, I'm cherry-picking that PR's commit into this PR.

___


<!-- Sent from Reviewable.io -->

2024-01-26 12:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 21 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "WIP" found in commit messages' one-liners

___
*[`-- commits` line 32 at r4](https://reviewable.io/reviews/gramineproject/gramine/1728#-Np4ngRL5yG8zLM6XlyY):*
FYI: I mean this PR: https://github.com/gramineproject/gramine/pull/1736


<!-- Sent from Reviewable.io -->

2024-01-26 14:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 28 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-Np3f0PB5U3YZU2tm5-v:-Np5Ghnp40G3IfaxASPX:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: I think I have a data race in handling the dummy host-based eventfd object. This is because we do blocking `PalStreamRead()` and `PalStreamWrite()` without the spinlock, so e.g. two reader threads may race on the same eventfd event, one of them wins and updates `dummy_host_val` and the other one looses and gets an unexpected `dummy_host_val`.

I need to add one new LibOS regression test `eventfd_races.c` and add several sub-tests in there:
1. Two blocking readers and one writer: both block with `read()`
2. Two blocking readers and one writer: one blocks with `read()` and another one blocks with `poll()` or `epoll()`
3. Two blocking writers and one reader
4. Two blocking readers and two blocking writers

Each sub-test must run like 10,000 events, to trigger data races with high probability.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-04-03 21:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 28 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP-Ap2yUtpsGcb1r0:-Nu_lCxd3YUAr2gGb9KZ:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocked on prerequisite PR https://github.com/gramineproject/gramine/pull/1727
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP2xvExydRQBaCv_a:-Nu_lDWYBYMsxNyWkK97:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: Rebase to new version of https://github.com/gramineproject/gramine/pull/1727 when I'm done with changes/comments there.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-Np4nVtR6jCa2LzcGMBY:-Nu_lEplDQnjIVtmK-SY:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocked on prerequisite PR https://github.com/gramineproject/gramine/pull/1736

For now, I'm cherry-picking that PR's commit into this PR.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-04-04 09:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NoqP_d7-AwJ_5n4UiJ5:-Nuc9bKL63BxK4xom1Yl:b-xlhutd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: Temporarily enable ReadTheDocs and check how Documentation looks there.
</blockquote></details>

Done, see:
- https://gramine.readthedocs.io/en/dimakuv-secure-eventfd-single-process/manifest-syntax.html#host-based-insecure-eventfd
- https://gramine.readthedocs.io/en/dimakuv-secure-eventfd-single-process/devel/features.html#event-notifications-eventfd

___


<!-- Sent from Reviewable.io -->

2024-04-04 09:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/test/ltp/ltp.cfg` line 264 at r7](https://reviewable.io/reviews/gramineproject/gramine/1728#-NucQA8cAf-KeZq6HXRS:-NucQA8cAf-KeZq6HXRT:b-wp54g9) ([raw file](https://github.com/gramineproject/gramine/blob/89dff01d8e270022e36ddcf229bfe9eaf041b5ad/libos/test/ltp/ltp.cfg#L264)):*
> ```INI
> 
> # test requires libaio
> [eventfd01]
> ```

FYI: If I try to enable the `eventfd01` test, that's what I get:
```
test_ltp.py::test_ltp[eventfd01] FAILED                                                                                [  9%]
test_ltp.py::test_ltp[eventfd2_01] PASSED                                                                              [ 10%]
test_ltp.py::test_ltp[eventfd2_02] PASSED                                                                              [ 10%]
test_ltp.py::test_ltp[eventfd2_03] PASSED  


____________________________________________________ test_ltp[eventfd01] _____________________________________________________
test_ltp.py:208: in test_ltp
    pytest.fail('{} exited with status {}'.format(full_cmd, returncode))
E   Failed: ['gramine-direct', 'eventfd01'] exited with status 127
---------------------------------------------------- Captured stdout call ----------------------------------------------------
[0.005] eventfd01: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
----------------------------------------------------- Captured log call ------------------------------------------------------
command: ['gramine-direct', 'eventfd01']
must_pass: all
returncode: 127
passed: []
failed: []
```


<!-- Sent from Reviewable.io -->

2024-04-05 20:38 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 348 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nujxv4Z48YO2OB0J1eJ:-Nujxv4Z48YO2OB0J1eK:b-noy6zu) ([raw file](https://github.com/gramineproject/gramine/blob/9084345234ad0cf97b97824f4100af2133019a55/Documentation/manifest-syntax.rst#L348)):*
> ```reStructuredText
> .. _eventfd-in-multi-process:
> 
> Allowing eventfd in multi-process applications
> ```

With the current code, `fork` is fine as long as you don't use any inherited `eventfd`s in the child process.  Both settings of this flag result in suboptimal outcomes:

- `false` disallows `fork` completely even if the process is just going to immediately `execve` or something
- `true` results in a lockup or `BUG` when the eventfd is actually used

We'd like to propose a different approach here:

- remove the `allow_eventfd_fork` option
- always allow `fork`
- on post-`fork` state deserialization, mark any deserialized `eventfd`s as "broken"
- when a "broken" `eventfd` is accessed, print the warning and return `-EIO`


<!-- Sent from Reviewable.io -->

2024-04-05 21:24 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/eventfd/fs.c` line 16 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuk80800rmO9iPiYwe1:-Nuk80800rmO9iPiYwe2:brg54so) ([raw file](https://github.com/gramineproject/gramine/blob/9084345234ad0cf97b97824f4100af2133019a55/libos/src/fs/eventfd/fs.c#L16)):*
> ```C
> #include "pal.h"
> 
> static void eventfd_dummy_host_read(struct libos_handle* hdl) {
> ```

I think implementing libos eventfd using host eventfd is not the best choice in this case — a better fit seems to be `PalEvent*`. This will also speed up the code a little, since it saves some syscalls in the optimistic case.


<!-- Sent from Reviewable.io -->

2024-04-08 08:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mwkmwkmwk)

___
*[`libos/src/fs/eventfd/fs.c` line 16 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuk80800rmO9iPiYwe1:-NuwkW07B-sKX6nY3ORC:bxoixis) ([raw file](https://github.com/gramineproject/gramine/blob/9084345234ad0cf97b97824f4100af2133019a55/libos/src/fs/eventfd/fs.c#L16)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I think implementing libos eventfd using host eventfd is not the best choice in this case — a better fit seems to be `PalEvent*`. This will also speed up the code a little, since it saves some syscalls in the optimistic case.
</blockquote></details>

I do not see how eventfd can be emulated via `PalEvent*`. Recall that `PalEvent*` is implemented via host futexes. But there is a contradiction:
- eventfd can be used in select/poll/epoll, so its emulation must have a simple and fast way to poll.
- futexes on Linux can **not** be used in select/poll/epoll; see in particular the history of `FUTEX_FD` which was briefly introduced in Linux (exactly for the purposes of polling) and then removed (https://man7.org/linux/man-pages/man2/futex.2.html)

Of course we could implement a complex emulation of futex polling -- when PAL wakes a futex, it also sends a special signal (or e.g. sends a byte on a special pipe), the corresponding host polls are interrupted, we check that the signal/byte corresponds to a particular futex (and thus to a particular eventfd), and mark the LibOS eventfd as "triggered". But this sounds super-complicated, why do this if we already have host-based eventfd that we can reuse.


<!-- Sent from Reviewable.io -->

2024-04-08 09:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 0 of 29 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`-- commits` line 12 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuwnZ2q1tqkUIUBSh1h):*
Will do: remove `to support ...` part.
___
*[`Documentation/manifest-syntax.rst` line 348 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nujxv4Z48YO2OB0J1eJ:-Nuwypzx7SpOkFy_645w:b-4exf0r) ([raw file](https://github.com/gramineproject/gramine/blob/9084345234ad0cf97b97824f4100af2133019a55/Documentation/manifest-syntax.rst#L348)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

With the current code, `fork` is fine as long as you don't use any inherited `eventfd`s in the child process.  Both settings of this flag result in suboptimal outcomes:

- `false` disallows `fork` completely even if the process is just going to immediately `execve` or something
- `true` results in a lockup or `BUG` when the eventfd is actually used

We'd like to propose a different approach here:

- remove the `allow_eventfd_fork` option
- always allow `fork`
- on post-`fork` state deserialization, mark any deserialized `eventfd`s as "broken"
- when a "broken" `eventfd` is accessed, print the warning and return `-EIO`
</blockquote></details>

Done. Great suggestion, the code is much simpler now.


<!-- Sent from Reviewable.io -->

2024-04-09 01:44 UTC, mkow requested changes
> Reviewed 3 of 16 files at r1, 1 of 10 files at r5, 11 of 19 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 9 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 23 of 29 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuyWxOP4A4JG-ER8RmI:-NuyWxOP4A4JG-ER8RmJ:b5ihimk) (no related file):*
There's also a mention of eventfd in nginx example Makefile, please update.

___
___
*[`libos/test/regression/eventfd_fork_allowed_failing.manifest.template` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuyf0DNEI40rDxzg0Qe:-Nuyf0DNEI40rDxzg0Qf:bpp6stj) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_fork_allowed_failing.manifest.template#L9)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib"
> loader.insecure__use_cmdline_argv = true
> ```

not needed
___
*[`libos/test/regression/eventfd_races.c` line 18 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuyfGDY0sH8Jll7zkeV:-NuyfGDY0sH8Jll7zkeW:b-d7kcjj) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L18)):*
> ```C
> static uint64_t g_write_events; /* atomic counter */
> static uint64_t g_total_events; /* atomic counter */
> static int g_stop_test;         /* atomic boolean */
> ```

Why not a `bool` then?
___
*[`libos/test/regression/eventfd_races.c` line 50 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymE3P7rHaAoIGNL0h:-NuymE3P7rHaAoIGNL0i:b-oyjpo1) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L50)):*
> ```C
>         if (curr_read_events == TEST_RUNS)
>             break;
>         if (read(g_efd, &val, sizeof(val)) != sizeof(val))
> ```

Could you also verify the value which was read?
ditto below
___
*[`libos/test/regression/eventfd_races.c` line 53 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuyi1g1-cEIa0VWlqpw:-Nuyi1g1-cEIa0VWlqpx:bf0om6c) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L53)):*
> ```C
>             errx(1, "eventfd read failed");
>         if (__atomic_load_n(&g_stop_test, __ATOMIC_SEQ_CST))
>             break;
> ```

Why do you have two different mechanisms to stop the test? (`g_read_events` counter and `g_stop_test` flag) Isn't this redundant?
ditto below
___
*[`libos/test/regression/eventfd_races.c` line 81 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymxDd2WQw_7toqWDe:-NuymxDd2WQw_7toqWDf:bbslnt2) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L81)):*
> ```C
>             continue;
>         /* below read may block because of the race: another thread can read first and reset the
>          * event value; we don't care as this is benign */
> ```

But won't this fail the test? If this thread gets switched out for a long time here and the other read thread will eat all the events in the meantime?
ditto below


<!-- Sent from Reviewable.io -->

2024-04-09 09:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 21 of 30 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuyWxOP4A4JG-ER8RmI:-Nv13Jgo8KT-gvbzl43i:bkac74s) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's also a mention of eventfd in nginx example Makefile, please update.
</blockquote></details>

You mean this: https://github.com/gramineproject/gramine/blob/bbc4068d3d907b72b02b2071fc1372555a7ddb88/CI-Examples/nginx/Makefile#L32-L40

I'm unsure what to do with this. I can remove the `sed` lines, but since Nginx is multi-process and uses eventfd for IPC, we'll need `sys.insecure__allow_eventfd = true` which is insecure. It seems better to compile Nginx without eventfd support, so that Nginx falls back to a different, secure IPC logic.

I updated the comment for now, to explain my reasoning.

___
___
*[`libos/test/regression/eventfd_fork_allowed_failing.manifest.template` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuyf0DNEI40rDxzg0Qe:-Nv1516M8tIlvs85F8hM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_fork_allowed_failing.manifest.template#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_races.c` line 18 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuyfGDY0sH8Jll7zkeV:-Nv17rI_BMBeOIQbF6KP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not a `bool` then?
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_races.c` line 50 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymE3P7rHaAoIGNL0h:-Nv16DGmAu_7Y4qvsyWH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also verify the value which was read?
ditto below
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_races.c` line 53 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuyi1g1-cEIa0VWlqpw:-Nv17s5C5WwKUzkrditB:b-mn0rdi) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do you have two different mechanisms to stop the test? (`g_read_events` counter and `g_stop_test` flag) Isn't this redundant?
ditto below
</blockquote></details>

Done.

It's not redundant, but its usage is indeed rather indirect. I added a comment to explain why I use this seemingly redundant boolean.
___
*[`libos/test/regression/eventfd_races.c` line 81 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymxDd2WQw_7toqWDe:-Nv16TM07HSaU7DsBW72:b-imwqbp) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L81)):*
> If this thread gets switched out for a long time here and the other read thread will eat all the events in the meantime?

Yes, this is a legit scenario. Why would it fail the test? It's completely normal that one thread will consume more events than another thread.


<!-- Sent from Reviewable.io -->

2024-04-09 16:45 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 19 files at r6, 3 of 12 files at r9, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 25 of 30 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/eventfd/fs.c` line 16 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nuk80800rmO9iPiYwe1:-Nv2jzCWCMyQcK8FqXCF:bna5ak1) ([raw file](https://github.com/gramineproject/gramine/blob/9084345234ad0cf97b97824f4100af2133019a55/libos/src/fs/eventfd/fs.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I do not see how eventfd can be emulated via `PalEvent*`. Recall that `PalEvent*` is implemented via host futexes. But there is a contradiction:
- eventfd can be used in select/poll/epoll, so its emulation must have a simple and fast way to poll.
- futexes on Linux can **not** be used in select/poll/epoll; see in particular the history of `FUTEX_FD` which was briefly introduced in Linux (exactly for the purposes of polling) and then removed (https://man7.org/linux/man-pages/man2/futex.2.html)

Of course we could implement a complex emulation of futex polling -- when PAL wakes a futex, it also sends a special signal (or e.g. sends a byte on a special pipe), the corresponding host polls are interrupted, we check that the signal/byte corresponds to a particular futex (and thus to a particular eventfd), and mark the LibOS eventfd as "triggered". But this sounds super-complicated, why do this if we already have host-based eventfd that we can reuse.
</blockquote></details>

ah yes, my bad, sorry


<!-- Sent from Reviewable.io -->

2024-04-09 16:58 UTC, mkow commented
*[`libos/src/fs/eventfd/fs.c` line 207 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2bjYUA8ME8F-wJXKg:-Nv2bjYUA8ME8F-wJXKh:b-gvw97m) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L207)):*
> for now we don't BUG but ignore it

Why not? And why do you say "for now"? Could you explain that in the comment?


<!-- Sent from Reviewable.io -->

2024-04-09 17:02 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 5 files at r2, 9 of 19 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 7 of 12 files at r9, 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 29 of 30 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/eventfd/fs.c` line 207 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2bjYUA8ME8F-wJXKg:-Nv2n3S83jy8PcWDmC0N:b26fkzt) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> for now we don't BUG but ignore it

Why not? And why do you say "for now"? Could you explain that in the comment?
</blockquote></details>

I think we shouldn't bug here — it's entirely reasonable to receive a "spurious" notification if another thread consumes an event between the wakeup and the `post_poll` callback. However, it's also not entirely clear what to do in this case — sensible options would include restarting the poll (requiring restructuring the code, probably) or just returning the spurious notification to the user.


<!-- Sent from Reviewable.io -->

2024-04-09 17:17 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 29 of 30 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/eventfd/fs.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2rBLRBffVhAyUOGJh:-Nv2rBLRBffVhAyUOGJi:b-5i077l) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L130)):*
> ```C
>     __UNUSED(pos);
> 
>     if (count < sizeof(uint64_t))
> ```

the kernel seems to validate this with `!=`, I think we should do the same


<!-- Sent from Reviewable.io -->

2024-04-09 17:27 UTC, mkow commented
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-Nv2r9vR4BQQyw9gFzui:b-8y65mn) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
> ```C
>                  * write - we assume that eventfd is not shared between processes.
>                  * Hopefully no app tries to increase the eventfd counter by 0...
>                  */
> ```

Can we instead nop-out on writing 0 to eventfd, or not call this function when writing 0? (with a comment why we _need_ to nop-out and it's not just an optimization)


<!-- Sent from Reviewable.io -->

2024-04-09 17:30 UTC, mkow commented
*[`libos/src/fs/eventfd/fs.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2rBLRBffVhAyUOGJh:-Nv2uJ9Z8XKdfHU3HJR7:biggako) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L130)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

the kernel seems to validate this with `!=`, I think we should do the same
</blockquote></details>

(but only here, not in `read()`)


<!-- Sent from Reviewable.io -->

2024-04-09 17:38 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 29 of 30 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-Nv2vndRC7CSbMkGXCJ-:bv6s46b) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
> ```C
>         }
>         spinlock_unlock(&hdl->info.eventfd.lock);
>         eventfd_dummy_host_wait(hdl, /*wait_for_read=*/false);
> ```

I don't think this is correct. The eventfd value on the host doesn't track the actual value within the enclave, so the host eventfd is effectively always ready (you cannot really do `UINT64_T - 1` writes to make it block), this function always returns immediately, and this effectively becomes a busyloop wait


<!-- Sent from Reviewable.io -->

2024-04-09 17:40 UTC, mkow requested changes
> Reviewed 1 of 5 files at r2, 2 of 19 files at r6, 3 of 12 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuyWxOP4A4JG-ER8RmI:-Nv2a00B4Pjc8muXad3e:bk4l3ri) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You mean this: https://github.com/gramineproject/gramine/blob/bbc4068d3d907b72b02b2071fc1372555a7ddb88/CI-Examples/nginx/Makefile#L32-L40

I'm unsure what to do with this. I can remove the `sed` lines, but since Nginx is multi-process and uses eventfd for IPC, we'll need `sys.insecure__allow_eventfd = true` which is insecure. It seems better to compile Nginx without eventfd support, so that Nginx falls back to a different, secure IPC logic.

I updated the comment for now, to explain my reasoning.
</blockquote></details>

Ok, updating the comment is ok then.

___
___
*[`libos/include/libos_fs.h` line 186 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2bEMb17NZg51cLvdo:-Nv2bEMb17NZg51cLvdp:b2ibk9k) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/include/libos_fs.h#L186)):*
> ```objc
> 
>     /* Verify a single handle after poll. Must update `pal_ret_events` in-place with only allowed
>      * ones. Used in e.g. secure eventfd FS. */
> ```

Or something like that, it was hard to understand its purpose without reading the eventfd code.



_Suggestion:_
```objc
Used in e.g. secure eventfd FS to verify if the host is not lying to us.
```
___
*[`libos/test/regression/eventfd_races.c` line 81 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymxDd2WQw_7toqWDe:-Nv2jfIS09UUMfbcTvGi:b-463egj) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> If this thread gets switched out for a long time here and the other read thread will eat all the events in the meantime?

Yes, this is a legit scenario. Why would it fail the test? It's completely normal that one thread will consume more events than another thread.
</blockquote></details>

Won't this `read()` block infinitely then?


<!-- Sent from Reviewable.io -->

2024-04-10 07:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 28 of 30 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/include/libos_fs.h` line 186 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2bEMb17NZg51cLvdo:-Nv5dfiw9fHR_ZNMq_2x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/include/libos_fs.h#L186)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Or something like that, it was hard to understand its purpose without reading the eventfd code.
</blockquote></details>

Done.
___
*[`libos/src/fs/eventfd/fs.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2rBLRBffVhAyUOGJh:-Nv5fOJ7-WnUnEHAi5xc:bl8gl45) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(but only here, not in `read()`)
</blockquote></details>

Interesting. I'm very uncomfortable with this change. Digging this in Linux kernel was quite interesting:

- Current Linux latest released version (v6.8.4) has a `<` check: https://elixir.bootlin.com/linux/v6.8.4/source/fs/eventfd.c#L254

- Latest WIP Linux version (v6.9-rc3) has a `!=` check: https://github.com/torvalds/linux/blob/fec50db7033ea478773b159e0e2efb135270e3b7/fs/eventfd.c#L254

- Here is the commit that introduced this single-line modification, from Feb 2024: https://github.com/torvalds/linux/commit/d31563b5f9bb601a805c4a1b491edf69ada79688

- Here is a (surprisingly short and uninformative) discussion of this patch: https://lore.kernel.org/all/tencent_10AAA44731FFFA493F9F5501521F07DD4D0A@qq.com/

Read the discussions in the last link. I feel very uncomfortable following a weird patch introduced in Linux 2 months ago and with a potential to be reverted (as it may break user apps). What do we do in this situation? I can also add a comment in our code with a quick explanation of the current situation.
___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-Nv5x1JE06zx5dChfPNu:bl03zq7) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I don't think this is correct. The eventfd value on the host doesn't track the actual value within the enclave, so the host eventfd is effectively always ready (you cannot really do `UINT64_T - 1` writes to make it block), this function always returns immediately, and this effectively becomes a busyloop wait
</blockquote></details>

You are right. My bug. This snippet degenerates to a busy loop, so I can as well just remove these three lines (unlock, host wait, lock) and replace with e.g. a `PalThreadYieldExecution()`.

Alternatively, we can use another host-based mechanism to sync between writers here. For example, I can introduce an additional futex sub-object to each eventfd (well, LibOS has a special notificator utility, I can use that).

However, the alternative approach seems like an overkill for this seemingly rare case of blocking writers. (I haven't observed applications that would use writer-blocking.) **So maybe just rewrite to a busy-loop?**
___
*[`libos/src/fs/eventfd/fs.c` line 207 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2bjYUA8ME8F-wJXKg:-Nv5t-dK7qAuhbbeV1Go:b-dyyely) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L207)):*
Indeed, as @mwkmwkmwk explains. It's possible to receive a spurious notification if another thread get in-between the wakeup and this callback. When I replace this line with a `BUG()`, I consistently get this in my `eventfd_races` test:
```
/gramineproject/gramine/libos/test/regression$ gramine-direct eventfd_races
------------------------
Read-only thread: read eventfd 6400 times
Read-only thread: read eventfd 3600 times
------------------------
[P1:T7:eventfd_races] error: BUG() ../libos/src/fs/eventfd/fs.c:209
```

Same applies for the `PAL_WAIT_WRITE` case below.

I modified the comment with expanded explanation. (Btw, "for now" phrase was clearly wrong and confusing)

> However, it's also not entirely clear what to do in this case — sensible options would include restarting the poll (requiring restructuring the code, probably) or just returning the spurious notification to the user.

Yes, agreed. My current code chooses the second option -- return a spurious notification.
___
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-Nv5mhyJ-18XmzgEWbZG:b-apuskh) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we instead nop-out on writing 0 to eventfd, or not call this function when writing 0? (with a comment why we _need_ to nop-out and it's not just an optimization)
</blockquote></details>

I don't think we can change anything here. There is a reason why Borys wrote this code and this comment as is.

Below is a long-ish explanation what is meant here and why we can't do anything about it (without overcomplicating our code).

First of all, pay attention that `write(event_fd, buf-with-zero-value)` is **not** a no-op on Linux. It actually triggers select/poll/epoll events: https://github.com/torvalds/linux/blob/v6.9-rc3/fs/eventfd.c#L273-L274

In other words, some applications may rely on this behavior of `write(0)` -- if the app doesn't want to increment the eventfd counter but wants to simply stop waiting on select/poll/epoll (if previously someone wrote into the eventfd counter already). Kinda like a "side-effect-free" notification to the waiters. (With eventfds that are waited with `EPOLLET` flag it's a bit different, see below.)

Now let's understand what this particular case is about. It has the following conditions:
1. It's an eventfd object
2. It's a write to the eventfd object (has two effects -- increments the counter by `value` and triggers select/poll/epoll)
3. The waiting is potentially done via epoll with `EPOLLET` (edge-triggered, i.e. epoll events are reported on this eventfd only when the eventfd counter really changed)

Now, we can easily check conditions (1) and (2) in `eventfd_write()` code. But there is *no* (simple) way  to check condition (3) -- this would require verifying whether this eventfd object is currently waited-upon in any of the epoll objects, and whether it is waited-upon with the `EPOLLET` flag. This in turn would require to traverse the list of epoll objects and traverse the list of waited-upon objects inside each epoll object -- too complex and too ineffective. Easier to just assume that apps don't perform `write(0)` in such a scenario (with 3 conditions described above).

Also, let me explain why we care about `EPOLLET` flag at all here. Imagine that there is some epoll that includes this eventfd object, but without the `EPOLLET` flag. This means that epoll events are reported on this eventfd **every time** when the eventfd counter **is not zero**. Now imagine that an app has the following situation:
```c
T1:
    epoll_wait(epoll_set_with_eventfd); /* waits */
T2:
    uint64_t increment_counter_by = 123;
    write(eventfd, &increment_counter_by);
T1:
   /* ... epoll_wait woken up (because counter is 123) */
   /* do some stuff but [...]

2024-04-10 14:12 UTC, mkow requested changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/fs/eventfd/fs.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2rBLRBffVhAyUOGJh:-Nv78hiHEN5ZNeOVl13o:b-ivgqlz) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting. I'm very uncomfortable with this change. Digging this in Linux kernel was quite interesting:

- Current Linux latest released version (v6.8.4) has a `<` check: https://elixir.bootlin.com/linux/v6.8.4/source/fs/eventfd.c#L254

- Latest WIP Linux version (v6.9-rc3) has a `!=` check: https://github.com/torvalds/linux/blob/fec50db7033ea478773b159e0e2efb135270e3b7/fs/eventfd.c#L254

- Here is the commit that introduced this single-line modification, from Feb 2024: https://github.com/torvalds/linux/commit/d31563b5f9bb601a805c4a1b491edf69ada79688

- Here is a (surprisingly short and uninformative) discussion of this patch: https://lore.kernel.org/all/tencent_10AAA44731FFFA493F9F5501521F07DD4D0A@qq.com/

Read the discussions in the last link. I feel very uncomfortable following a weird patch introduced in Linux 2 months ago and with a potential to be reverted (as it may break user apps). What do we do in this situation? I can also add a comment in our code with a quick explanation of the current situation.
</blockquote></details>

I'd vote for changing it into `!=`, the commit was already merged and IMO writing more bytes is a sign of a bug in the app. But I won't block on this.
___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-Nv79Hcp827BL84Q-_ra:buxrsf4) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You are right. My bug. This snippet degenerates to a busy loop, so I can as well just remove these three lines (unlock, host wait, lock) and replace with e.g. a `PalThreadYieldExecution()`.

Alternatively, we can use another host-based mechanism to sync between writers here. For example, I can introduce an additional futex sub-object to each eventfd (well, LibOS has a special notificator utility, I can use that).

However, the alternative approach seems like an overkill for this seemingly rare case of blocking writers. (I haven't observed applications that would use writer-blocking.) **So maybe just rewrite to a busy-loop?**
</blockquote></details>

Can't we keep the host value in-sync with in-LibOS value? I think it doesn't leak anything important and the host could only deadlock us by changing it?
___
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-Nv7Dz8AAokCumilkyeN:b-n98j6v) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
> Imagine that there is some epoll that includes this eventfd object, but without the `EPOLLET` flag.

> /\* ... epoll\_wait woken up (because counter is 123), even though the counter value didn't change \*/

But in this case `epoll_wait()` will wake up regardless of the write(0), because reading is possible right away? (and it's not edge-triggered, but value-triggered)

Anyways, what we want here is to have:
- any write waking up all `EPOLLET` listeners
- any write resulting in > 0 final value waking up all non-`EPOLLET` listeners

Right?

And the comment says that currently something is wrong with epoll if the user writes 0? What exactly?
___
*[`libos/test/regression/eventfd_races.c` line 81 at r9](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuymxDd2WQw_7toqWDe:-Nv7KrbU8FzJ-Bal8Yll:bcj2q6k) ([raw file](https://github.com/gramineproject/gramine/blob/ed65fe139b5f67ee6fae7faec644acbb739d8bb0/libos/test/regression/eventfd_races.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, please see the code under `/* send one last event to unblock the second reader */` in the `write_eventfd_thread()` function.

Basically, we set `g_stop_test = true` first and then perform an additional `write()` exactly to unblock the `read()` on the reader thread. And in the reader thread, write after an unblocked read, we break out of the loop because `g_stop_test == true` (and thus we both unblock the read and do *not* update the total-events counter).

I mean... I could raise a signal or smth to unblock the `read()`, but this would be more complicated that sending a end-the-loop eventfd notification. I.e. I'm reusing the same eventfd object to send a "stop the world" notification.
</blockquote></details>

Ok, I think it's indeed correct because the counter is limiting the reads to `TEST_RUNS+1` at most, although the logic here is quite convoluted.


<!-- Sent from Reviewable.io -->

2024-04-10 17:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 28 of 30 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/fs/eventfd/fs.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2rBLRBffVhAyUOGJh:-Nv8-oQKCG3xsx61EpIv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd vote for changing it into `!=`, the commit was already merged and IMO writing more bytes is a sign of a bug in the app. But I won't block on this.
</blockquote></details>

Done.
___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-Nv7VUWD1gb5UFWrwS5i:b-g3kb2v) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
> Can't we keep the host value in-sync with in-LibOS value? I think it doesn't leak anything important and the host could only deadlock us by changing it?

I'm against this solution because this would leak the eventfd counter value, i.e. confidentiality of the app would be violated. It's probably fine in 99.9% of the apps (they only use eventfd counters for sync, i.e. for correctness of synchronization which this PR satisfies anyway). But maybe there's a 0.1% of apps that communicate something interesting in the eventfd counter, and then confidentiality is important to keep.

So we must choose between two corner cases:
1. On `write(eventfd, ...)`, an overflow will not block (putting thread to sleep) but will busy loop (burning cycles). This should be a rare case; all apps that I looked at do not even check for overflows, and of course do not use blocking-eventfd-writes on purpose.
2. 0.1% of apps that put something interesting and secret in the eventfd counter. This should be a seemingly rare case.

After quick discussion with @mkow, we agreed to choose (1). I.e. keep the current code as-is but replace useless `eventfd_dummy_host_wait()` with `PalThreadYieldExecution()`, i.e. to make the busy loop explicit here.
___
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-Nv7TFIK1nRV6RJbGPVn:b7xcxqy) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
> But in this case `epoll_wait()` will wake up regardless of the write(0), because reading is possible right away? (and it's not edge-triggered, but value-triggered)

Yes, you are right, there is no need for an additional `write(0)` in my scenario... I can't come up with a plausible scenario where `write(0)` will do something additional. I'm not sure if I'm just not creative enough, or `write(0)` is really a no-op in all possible scenarios. (At the same time, I'd be scared to make it a no-op because that's not how Linux code works.)

> Anyways, what we want here is to have:
> 
> -   any write waking up all `EPOLLET` listeners
> -   any write resulting in > 0 final value waking up all non-`EPOLLET` listeners
> 
> Right?

Yes, almost. In the first case, `write(0)` should *not* wake up `EPOLLET` listeners, because there was **no change** to the eventfd counter value (so edge is not triggered).

> And the comment says that currently something is wrong with epoll if the user writes 0? What exactly?

Our current code here wakes up `EPOLLET` listeners even on `write(0)`. The correct code would **not** wake up `EPOLLET` listeners on `write(0)`.

That's the discrepancy from Linux/POSIX behavior, and that's what the comment says (ok, we can reformulate the comment, it's super-vague).

Note that this discrepancy in behavior is most probably benign, because this just means a spurious (too early) wake up of the `EPOLLET` reader. But at the same time, applications may rely on particular timings and wake ups for synchronization, in which case Gramine's incorrect behavior will result in some wrong sync.

(Again, as mentioned, we can't easily fix this discrepancy because we'd need to analyze all epoll sets with all `EPOLLET` eventfds.)

Thinking about it, maybe you're right and we can just special-case `write(0)` in eventfd code... Can we postpone this for later? It's not directly related to this PR. I added a FIXME comment.


<!-- Sent from Reviewable.io -->

2024-04-11 00:45 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-Nv9afiN4ABbldNF79Wj:b-vcyg6r) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
> First of all, pay attention that `write(event_fd, buf-with-zero-value)` is **not** a no-op on Linux. It actually triggers select/poll/epoll events: [https://github.com/torvalds/linux/blob/v6.9-rc3/fs/eventfd.c#L273-L274](https://github.com/torvalds/linux/blob/v6.9-rc3/fs/eventfd.c#L273-L274)

Ok, so that's what confused me initially ^ - you said that it actually does something ;)

> Thinking about it, maybe you're right and we can just special-case `write(0)` in eventfd code... Can we postpone this for later? It's not directly related to this PR. I added a FIXME comment.

Yeah, you can do it later, although it should be 2 simple lines in a function you basically rewrote here, i.e. it's shorter even than the comment you added here ;)


<!-- Sent from Reviewable.io -->

2024-04-11 02:13 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-Nv9vY2rDfaTjIT86_Fm:b-qyxiwe) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Can't we keep the host value in-sync with in-LibOS value? I think it doesn't leak anything important and the host could only deadlock us by changing it?

I'm against this solution because this would leak the eventfd counter value, i.e. confidentiality of the app would be violated. It's probably fine in 99.9% of the apps (they only use eventfd counters for sync, i.e. for correctness of synchronization which this PR satisfies anyway). But maybe there's a 0.1% of apps that communicate something interesting in the eventfd counter, and then confidentiality is important to keep.

So we must choose between two corner cases:
1. On `write(eventfd, ...)`, an overflow will not block (putting thread to sleep) but will busy loop (burning cycles). This should be a rare case; all apps that I looked at do not even check for overflows, and of course do not use blocking-eventfd-writes on purpose.
2. 0.1% of apps that put something interesting and secret in the eventfd counter. This should be a seemingly rare case.

After quick discussion with @mkow, we agreed to choose (1). I.e. keep the current code as-is but replace useless `eventfd_dummy_host_wait()` with `PalThreadYieldExecution()`, i.e. to make the busy loop explicit here.
</blockquote></details>

This approach will break `poll` for write — it'll always consider an eventfd available for writing.


<!-- Sent from Reviewable.io -->

2024-04-11 07:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 28 of 30 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/fs/eventfd/fs.c` line 168 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2vndRC7CSbMkGXCIz:-NvAxVVcAdxq40tO3PgZ:bqa8lgm) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/fs/eventfd/fs.c#L168)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

This approach will break `poll` for write — it'll always consider an eventfd available for writing.
</blockquote></details>

Done. I updated the comment to mention this too.

Again, the reasoning is that overflowing writes on eventfd are super-rare in real-world applications. So even if there is a `poll( {.fd = eventfd, .events = POLLOUT} )` in the app code, then we have two cases:
1. The eventfd counter is not overflowing, and this `poll()` will always return POLLOUT anyway (even in native app). I believe this is what 99.9% apps experience.
2. The eventfd counter is overflowing, and this `poll()` will block in native app, and will spuriously return (with no POLLOUT return event) in Gramine. I believe this is what at most 0.1% of apps will experience.

And don't forget that most apps don't wait for POLLOUT on eventfds anyway.

To check my speculation, I looked at several apps:
- Memcached: no POLLOUT requests, see https://github.com/memcached/memcached/commit/c25d0bd68ab0f6226c2d979bf0951923624926dd
- Rust Tokio `mio` library: no POLLOUT requests, see https://github.com/tokio-rs/mio/blob/master/src/waker.rs
- MongoDB: no `poll()` or similar at all, see https://github.com/mongodb/mongo/blob/332222f6b3614afab114af7d907f5643e04f4e30/docs/baton.md?plain=1#L44 and https://github.com/mongodb/mongo/blob/332222f6b3614afab114af7d907f5643e04f4e30/src/mongo/transport/asio/asio_networking_baton.cpp#L68

I also tried to find any usages of blocking writes on the internet, but failed. I do believe that this is a highly esoteric scenario. If you'll find counter-examples, I'll be happy to analyze them and reconsider the current design decision.
___
*[`libos/src/sys/libos_epoll.c` line 187 at r10](https://reviewable.io/reviews/gramineproject/gramine/1728#-Nv2r9vR4BQQyw9gFzuh:-NvB7wl30SZTyvjTl4h0:bg5rx3d) ([raw file](https://github.com/gramineproject/gramine/blob/25e3d78fe3b139476b935a9b6f7d2b3cce7a05bd/libos/src/sys/libos_epoll.c#L187)):*
> > Thinking about it, maybe you're right and we can just special-case `write(0)` in eventfd code... Can we postpone this for later? It's not directly related to this PR. I added a FIXME comment.
> 
> Yeah, you can do it later, although it should be 2 simple lines in a function you basically rewrote here, i.e. it's shorter even than the comment you added here ;)

Ok, after some more thinking, I went with your proposal. Now we special case `write(0)` on eventfd, and reverted comments here.


<!-- Sent from Reviewable.io -->

2024-04-11 15:52 UTC, mkow requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/fs/eventfd/fs.c` line 142 at r13](https://reviewable.io/reviews/gramineproject/gramine/1728#-NvCq8f8673SNiF59WkH:-NvCq8f995ntkSHFuqlY:bubqmyd) ([raw file](https://github.com/gramineproject/gramine/blob/13370d92e7cf5b51178d803f1ad2f02c34327645/libos/src/fs/eventfd/fs.c#L142)):*
> ```C
>     if (buf_val == 0) {
>         /* note: we consider eventfd write of zero as a no-op, even though Linux kernel doesn't have
>          * such early-return case (https://elixir.bootlin.com/linux/v6.8/source/fs/eventfd.c#L247);
> ```

Now it IMO sounds misleading, like we were behaving differently than Linux. Please reword the next sentence to say that Linux no-ops on write(0) despite the lack of this special IF (which is required in Gramine due to how our polling works).


<!-- Sent from Reviewable.io -->

2024-04-11 17:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 29 of 30 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/eventfd/fs.c` line 142 at r13](https://reviewable.io/reviews/gramineproject/gramine/1728#-NvCq8f8673SNiF59WkH:-NvD7YgSDPE2481WeVi4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13370d92e7cf5b51178d803f1ad2f02c34327645/libos/src/fs/eventfd/fs.c#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it IMO sounds misleading, like we were behaving differently than Linux. Please reword the next sentence to say that Linux no-ops on write(0) despite the lack of this special IF (which is required in Gramine due to how our polling works).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-11 22:28 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-04-12 03:57 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 16 files at r1, 2 of 19 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 7 of 12 files at r9, 3 of 3 files at r10, 1 of 2 files at r11, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-04-15 06:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 28 of 30 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`-- commits` line 12 at r8](https://reviewable.io/reviews/gramineproject/gramine/1728#-NuwnZ2q1tqkUIUBSh1h):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do: remove `to support ...` part.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-04-15 09:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: 28 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`libos/src/sys/libos_epoll.c` line 682 at r2](https://reviewable.io/reviews/gramineproject/gramine/1728#-NovqZYOC6NJBUc1hCwn:-NvW1bY2DMXZY4FzNSFf:bj0pfop) ([raw file](https://github.com/gramineproject/gramine/blob/13c0224b943cf52abe2108a7b71983344fa3e277/libos/src/sys/libos_epoll.c#L682)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself not to forget to create such a PR when this PR will be ready for final merge.
</blockquote></details>

Done: https://github.com/gramineproject/gramine/pull/1844
___
*[`libos/src/sys/libos_poll.c` line 221 at r2](https://reviewable.io/reviews/gramineproject/gramine/1728#-Novqedu8nFR56kyyvKP:-NvW1cSa5iwd5sdETVDm:bj0pfop) ([raw file](https://github.com/gramineproject/gramine/blob/13c0224b943cf52abe2108a7b71983344fa3e277/libos/src/sys/libos_poll.c#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself not to forget to create such a PR when this PR will be ready for final merge.
</blockquote></details>

Done: https://github.com/gramineproject/gramine/pull/1844


<!-- Sent from Reviewable.io -->

2024-04-15 12:48 UTC, mkow requested changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 328 at r15](https://reviewable.io/reviews/gramineproject/gramine/1728#-NvWma708GJOqU9CpZuN:-NvWczaYEry4JzOt4-4V:b-v2tmmp) ([raw file](https://github.com/gramineproject/gramine/blob/51e99f9880052c051f8774f63af5073d82503c7d/Documentation/manifest-syntax.rst#L328)):*
> ```reStructuredText
> a 1 |~| MiB brk size.
> 
> .. _allowing-eventfd:
> ```

Was not-changing this on purpose, missed this during rebase?


<!-- Sent from Reviewable.io -->

2024-04-15 13:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/manifest-syntax.rst` line 328 at r15](https://reviewable.io/reviews/gramineproject/gramine/1728#-NvWma708GJOqU9CpZuN:-NvWqDJn2oEWJVfz9lOv:bjxuh0m) ([raw file](https://github.com/gramineproject/gramine/blob/51e99f9880052c051f8774f63af5073d82503c7d/Documentation/manifest-syntax.rst#L328)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Was not-changing this on purpose, missed this during rebase?
</blockquote></details>

This was on purpose, because Woju already created the same ref anchor in the meantime and merged his PR before mine: https://github.com/gramineproject/gramine/commit/cb65b4260df3dcce8a0abd77d6838267b45efd7f


<!-- Sent from Reviewable.io -->

2024-04-15 13:07 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1728)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 328 at r15](https://reviewable.io/reviews/gramineproject/gramine/1728#-NvWma708GJOqU9CpZuN:-NvWqpnp9bLGFe2VKZ0S:b-cvscnr) ([raw file](https://github.com/gramineproject/gramine/blob/51e99f9880052c051f8774f63af5073d82503c7d/Documentation/manifest-syntax.rst#L328)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was on purpose, because Woju already created the same ref anchor in the meantime and merged his PR before mine: https://github.com/gramineproject/gramine/commit/cb65b4260df3dcce8a0abd77d6838267b45efd7f
</blockquote></details>

No, I mean whether _not-changing_ it, i.e. not updating the anchor name is intended. Woju added it when this section's name was "Allowing eventfd", but you renamed it to "Allowing host-based insecure eventfd" in this PR and didn't rename the anchor on rebase.
Not saying this is bad, just want to ensure that you noticed that and did this intentionally.


<!-- Sent from Reviewable.io -->

2024-04-15 13:41 UTC, merged