[LibOS] Do not perform `lock(&hdl->pos_lock)` on non-seeking handles
gramineproject/gramine pull request #1736
Opened 2024-01-26 12:45 UTC by dimakuv

## Description of the changes 

Handles can be file-like (allow seeking and thus have a file position) and stream-like (do not allow seeking and thus file position field `pos` is unused). Previously, LibOS emulations of `read()`, `write()`, `sendfile()`, etc. did not distinguish between file-like and stream-like handles and always acquired `hdl->pos_lock`.

This led to a bug on stream-like handles, in particular, on eventfd handles: `read()` and `write()` operations are blocking for eventfds, thus a blocking `read()` would acquire the `hdl->pos_lock` indefinitely and e.g. hang another thread that performs `write()` on same eventfd.

This commit fixes this bug by skipping this lock on stream-like handles. This has an additional performance benefit: stream-like handles like pipes, sockets and eventfds don't spend cycles in acquiring and releasing the lock inside the relevant (and very frequent) syscalls.

---

This bug was detected while working on https://github.com/gramineproject/gramine/pull/1728.

For context, this is the commit where this `pos_lock` was introduced: https://github.com/gramineproject/gramine/commit/e474134a4fd84fe72397e2f33a5a4e9950e06885#diff-d79d43998e924cff687e6a56d5f3b0643951f90b5b050730239d830e2f3e8b98

It's interesting to note that this bug does **not** exhibit itself on pipes, FIFOs and UNIX sockets (socketpairs). This is because these objects are unidirectional. I tried to write a test using a pipe or a socketpair first, but quickly realized that I can't write to and read from the same pipe/socket end even on normal Linux.

## How to test this PR? 

New LibOS regression test `eventfd_read_then_write` is added to test this bug fix.

2024-01-31 08:55 UTC, llly reviewed
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 485 at r1](https://reviewable.io/reviews/gramineproject/gramine/1736#-NpThSEu9q4uqh06iTSa:-NpThSEu9q4uqh06iTSb:b-711lmj) ([raw file](https://github.com/gramineproject/gramine/blob/322d9541131c9b76fc17b2f985fa7485f5a3f4ce/libos/src/fs/libos_fs_pseudo.c#L485)):*
> ```C
>         case PSEUDO_STR: {
>             assert(hdl->type == TYPE_STR);
>             lock_pos_handle(hdl);
> ```

Other pseudo functions don't lock the `pos_lock`. Callers lock `pos_lock` before calling them.
Should we also move this `lock_pos_handle(hdl);` to its caller function?


<!-- Sent from Reviewable.io -->

2024-01-31 10:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 1 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 485 at r1](https://reviewable.io/reviews/gramineproject/gramine/1736#-NpThSEu9q4uqh06iTSa:-NpU8mRF780NgqSTq5ra:b35wj2g) ([raw file](https://github.com/gramineproject/gramine/blob/322d9541131c9b76fc17b2f985fa7485f5a3f4ce/libos/src/fs/libos_fs_pseudo.c#L485)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Other pseudo functions don't lock the `pos_lock`. Callers lock `pos_lock` before calling them.
Should we also move this `lock_pos_handle(hdl);` to its caller function?
</blockquote></details>

Done. Good point.


<!-- Sent from Reviewable.io -->

2024-02-01 00:32 UTC, llly reviewed
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-03-29 21:56 UTC, mkow requested changes
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB7eUw0k8jKPxemDOQ:-NuB7eUw0k8jKPxemDOR:b-q6n46v) (no related file):*
Hmm, how does file position concurrency works on Linux when a handle is accessed from many threads? I think it doesn't block like Gramine? Is this whole concept of locking the position for the whole duration of read/write actually right?

___
___
*[`libos/include/libos_handle.h` line 297 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuBBDg8-ABdy0PLBWa4:-NuBBDg8-ABdy0PLBWa5:ba8cphy) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/include/libos_handle.h#L297)):*
> ```objc
> ssize_t do_handle_write(struct libos_handle* hdl, const void* buf, size_t count);
> 
> void lock_pos_handle(struct libos_handle* hdl);
> ```

ditto for unlock



_Suggestion:_
```objc
maybe_lock_pos_handle
```
___
*[`libos/test/regression/eventfd_read_then_write.c` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuAzV94366xFldexalN:-NuAzV95-U6qmi-JMbia:b-30o7gh) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L9)):*
> ```C
> #include <string.h>
> #include <unistd.h>
> #include <sys/eventfd.h>
> ```

Please sort.
___
*[`libos/test/regression/eventfd_read_then_write.c` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB17vH7V1DgGvSSPQS:-NuB17vI1BTC_-kiKBD4:b32vhv) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L27)):*
> ```C
>     while (__atomic_load_n(&g_read_thread_started, __ATOMIC_SEQ_CST) == false)
>         ;
>     sleep(1); /* make sure the other thread called the blocking read */
> ```

:(


<!-- Sent from Reviewable.io -->

2024-04-02 13:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 5 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB7eUw0k8jKPxemDOQ:-NuTwVKo3gsPJUl3YEaV:bck6zlb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, how does file position concurrency works on Linux when a handle is accessed from many threads? I think it doesn't block like Gramine? Is this whole concept of locking the position for the whole duration of read/write actually right?
</blockquote></details>

Yes, file position (aka file offset) is atomic in `read()`, `write()`, `seek()`, etc.

It was actually a bug in the Linux kernel. It was fun to dig it out (you probably remember the old days of Linux before 3.14?):
- https://man7.org/linux/man-pages/man2/read.2.html#BUGS
- https://man7.org/linux/man-pages/man2/write.2.html#BUGS
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html (Section 2.9.7)
- https://lore.kernel.org/lkml/53022DB1.4070805@gmail.com/ -- bug fixing thread

So the concept is correct.

___
___
*[`libos/include/libos_handle.h` line 297 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuBBDg8-ABdy0PLBWa4:-NuTxPfE0XzdYA1dyNpr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/include/libos_handle.h#L297)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for unlock
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_read_then_write.c` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuAzV94366xFldexalN:-NuTyR7_9Tr5QL6LCt9k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please sort.
</blockquote></details>

Done.
___
*[`libos/test/regression/eventfd_read_then_write.c` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB17vH7V1DgGvSSPQS:-NuTwvL_CvrFm4H8Zltr:bjlqd1m) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

:(
</blockquote></details>

But there's no other way... Am I mistaken?

Or maybe you don't like that we wait for **a whole second**? Is your comment about replacing with `nanosleep()`?


<!-- Sent from Reviewable.io -->

2024-04-02 13:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 5 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB7eUw0k8jKPxemDOQ:-NuU13-pDMZfHR3L0Xkz:b2rny62) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, file position (aka file offset) is atomic in `read()`, `write()`, `seek()`, etc.

It was actually a bug in the Linux kernel. It was fun to dig it out (you probably remember the old days of Linux before 3.14?):
- https://man7.org/linux/man-pages/man2/read.2.html#BUGS
- https://man7.org/linux/man-pages/man2/write.2.html#BUGS
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html (Section 2.9.7)
- https://lore.kernel.org/lkml/53022DB1.4070805@gmail.com/ -- bug fixing thread

So the concept is correct.
</blockquote></details>

And the commit by Linus itself: https://github.com/torvalds/linux/commit/9c225f2655e36a470c4f58dbbc99244c5fc7f2d4

___


<!-- Sent from Reviewable.io -->

2024-04-03 01:13 UTC, mkow requested changes
> Reviewed 1 of 2 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`libos/src/bookkeep/libos_handle.c` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuWSzhPDOZVCMKHHycX:-NuWSzhPDOZVCMKHHycY:bcy2zra) ([raw file](https://github.com/gramineproject/gramine/blob/dc407f47c8a9d11ce9e7359559efdc486e64494c/libos/src/bookkeep/libos_handle.c#L63)):*
> ```C
>         else
>             unlock(&hdl->pos_lock);
>     }
> ```

I don't like that this is decided here, I think it would be cleaner if that was a property of a handle type, declared in a corresponding file. What do you think about adding `bool seekable` field to `struct libos_handle` and locking based on it's value? Should be roughly the same amount of code.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 486 at r3](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuWU2uj5kCKnW2kJ4Cf:-NuWU2uj5kCKnW2kJ4Cg:b5jklvn) ([raw file](https://github.com/gramineproject/gramine/blob/dc407f47c8a9d11ce9e7359559efdc486e64494c/libos/src/fs/libos_fs_pseudo.c#L486)):*
> ```C
>             assert(hdl->type == TYPE_STR);
>             lock(&hdl->lock);
>             int ret = mem_file_poll(&hdl->info.str.mem, hdl->pos, events, out_events);
> ```

This field is not atomic, I don't think we can read it without the lock?
// Update: see below.



_Code quote:_
```C
hdl->pos
```
___
*[`libos/src/fs/libos_fs_util.c` line 104 at r3](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuWUIZdE-yMrQcM4tTz:-NuWUIZdE-yMrQcM4tU-:bbyypov) ([raw file](https://github.com/gramineproject/gramine/blob/dc407f47c8a9d11ce9e7359559efdc486e64494c/libos/src/fs/libos_fs_util.c#L104)):*
> ```C
> }
> 
> file_off_t generic_inode_seek(struct libos_handle* hdl, file_off_t offset, int origin) {
> ```

I guess here we could skip all the logic if we had `hdl->seekable == false`? And I guess it's also more in par with Linux, to always have pos==0 on non-seekable handles?
___
*[`libos/src/sys/libos_poll.c` line 134 at r3](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuWV8-15h3LLhDaHjHM:-NuWV8-15h3LLhDaHjHN:b19kzbb) ([raw file](https://github.com/gramineproject/gramine/blob/dc407f47c8a9d11ce9e7359559efdc486e64494c/libos/src/sys/libos_poll.c#L134)):*
> ```C
>             maybe_lock_pos_handle(handle);
>             ret = handle->fs->fs_ops->poll(handle, events, &events);
>             maybe_unlock_pos_handle(handle);
> ```

Ah, I see, you moved the locking here. Why? (I'm not against, but would like to know the reason)
___
*[`libos/test/regression/eventfd_read_then_write.c` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB17vH7V1DgGvSSPQS:-NuWLvWh5FYSvbmoJJ8q:b-h3u36i) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L27)):*
> But there's no other way... Am I mistaken?

Hmm, yeah, I couldn't come up with anything else :/ Maybe @kailun-qin has an idea?

If not, then please at least change the comment, it's not "making sure", it's just a heuristic because we don't have a better idea how to assert that.

Also, it would be nice to make this test a bit more generic, i.e. testing concurrency, not just a single read and a single write. This should be (I think) just a pair of loops and checks on the eventfd values?


<!-- Sent from Reviewable.io -->

2024-04-03 12:06 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-Sanitizers please (unrelated `tests.test_sgx_sign.test_sign_from_pem_path` problem)

2024-04-03 13:47 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 120 at r5](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuYus6aEbIp0bukmmIy:-NuZCPuG-9KT56KPaaON:bllaake) ([raw file](https://github.com/gramineproject/gramine/blob/4e13f396073c4ea03380218464380075feb5953c/libos/src/fs/libos_fs_pseudo.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I only set `seekable = true` explicitly, in those cases where it's needed (regular files: chroot files, tmpfs files, shm dev files, encrypted files).

In all other cases `seekable = false` implicitly, and I decided not to clog our code with this (just like we don't set `pos = 0` in those cases).

Do you dislike this implicit logic?
</blockquote></details>

Ah, I see. I think it's ok, but I'd prefer to someday clean it up, i.e. make it clearer that all the structures' fields are always initialized.


<!-- Sent from Reviewable.io -->

2024-04-03 14:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 11 of 17 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly and @mkow)

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuYHw2u6R_BQSVGWJ2d):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do: add that handles now have a new field `seekable`, and stream-like ones have it as `false` and file-like have it as `true`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-04-03 14:36 UTC, mkow requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/test_libos.py` line 898 at r6](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuZNhPw7QJ1zMyf_3qX:-NuZNhPw7QJ1zMyf_3qY:b9urueo) ([raw file](https://github.com/gramineproject/gramine/blob/79ff0e998dc5e256ae7ab25a67b11478460bc630/libos/test/regression/test_libos.py#L898)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
>     def test_071_eventfd_read_then_write(self):
> ```

Rebase fail here :) In the meantime another 071 test was added.


<!-- Sent from Reviewable.io -->

2024-04-03 14:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: 16 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`libos/test/regression/test_libos.py` line 898 at r6](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuZNhPw7QJ1zMyf_3qX:-NuZOZL8A4PUdBraLdbX:bm59k45) ([raw file](https://github.com/gramineproject/gramine/blob/79ff0e998dc5e256ae7ab25a67b11478460bc630/libos/test/regression/test_libos.py#L898)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Rebase fail here :) In the meantime another 071 test was added.
</blockquote></details>

Done.

Let me also kill all Jenkins jobs, and restart it. Otherwise it will take ages.


<!-- Sent from Reviewable.io -->

2024-04-03 14:58 UTC, kailun-qin approved these changes
> Reviewed 4 of 12 files at r1, 3 of 8 files at r3, 9 of 10 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`libos/test/regression/eventfd_read_then_write.c` line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/1736#-NuB17vH7V1DgGvSSPQS:-NuZRVxr5NIqgtJ56PiV:bdy0el2) ([raw file](https://github.com/gramineproject/gramine/blob/e129d57555bfc0a31d4163a1ee95eb4ace5b6242/libos/test/regression/eventfd_read_then_write.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done

1. I changed the comment.
2. I added 100 iterations, to test concurrency.
</blockquote></details>

yeah... I don't see a better solution w/o side effects


<!-- Sent from Reviewable.io -->

2024-04-03 20:00 UTC, merged