[Pal/Linux-SGX] Add `sgx.insecure__allow_memfaults_wo_exinfo` manifest option
gramineproject/gramine pull request #1744
Opened 2024-02-02 10:26 UTC by dimakuv

## Description of the changes 

Commits ["[PAL/Linux-SGX] Disallow memfault handling with no faulting address reported"](https://github.com/gramineproject/gramine/commit/9f80c4245a8a852a2d6ac30c81840c94db447305) and ["[PAL/Linux-SGX] Cross-verify SW signals vs HW exceptions"](https://github.com/gramineproject/gramine/commit/a390e33e16ed374a40de2344562a937f289be2e1) hardened Gramine's exception handling in the SGX PAL. In particular, memory faults (#PF and #GP) became allowed only when the SGX EXINFO feature is available on the CPU and is enabled in the manifest (via `sgx.use_exinfo`). Otherwise Gramine immediately terminated the SGX enclave.

However, some applications (Java runtimes in particular) rely on exception handling of memory faults, even if the related MADDR (faulting address) and ERRCD (error code) have dummy zero values. The two mentioned commits effectively forbade such applications from running on older CPUs that don't have EXINFO. This is unfortunate because frequently, the development/testing machines have old SGX CPUs.

To work around the problem of old CPUs, this PR introduces the `sgx.insecure__allow_memfaults_wo_exinfo` manifest option, that restores the previous (insecure) Gramine behavior. **This is only a temporary solution; it will be removed in release v1.8.**

Fixes #1587.

For more context, see:
- https://github.com/gramineproject/gramine/issues/1561
- https://github.com/gramineproject/gramine/pull/1570
- https://github.com/gramineproject/gramine/issues/1514
- https://github.com/gramineproject/gramine/discussions/1704
- https://github.com/gramineproject/gramine/discussions/1740

## How to test this PR? 

Try e.g. some Java workloads on old CPUs.

2024-02-10 02:07 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1744)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 800 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqFaqBIAl6WJ3SSxs1T:-NqFaqBIAl6WJ3SSxs1U:be58ds4) ([raw file](https://github.com/gramineproject/gramine/blob/847e90fefabf7ac279610fa33132d9a59683d149/Documentation/manifest-syntax.rst#L800)):*
> ```reStructuredText
>     (Default: false)
> 
>     sgx.insecure__allow_memfaults_wo_exinfo = [true|false]
> ```

I'd use "without", this "wo" is not too obvious without `/` IMO.
___
*[`Documentation/manifest-syntax.rst` line 822 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqFbTjX1hmHbHeyGv39:-NqFbTjX1hmHbHeyGv3A:b-k4grb2) ([raw file](https://github.com/gramineproject/gramine/blob/847e90fefabf7ac279610fa33132d9a59683d149/Documentation/manifest-syntax.rst#L822)):*
> ```reStructuredText
>    Without EXINFO support, a malicious host may attack the application by
>    injecting a memory fault. This option is thus insecure and must not be used
>    in production environments! It will be removed in v1.8.
> ```

Isn't this too early? These old CPU will still be in use for quite a while.



_Code quote:_
```reStructuredText
It will be removed in v1.8.
```


<!-- Sent from Reviewable.io -->

2024-02-11 14:57 UTC, kailun-qin reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1744)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqNf5Z107SPbzFBhMhb):*
PAL



_Code quote:_
```
Pal
```
___
*[`Documentation/manifest-syntax.rst` line 822 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqFbTjX1hmHbHeyGv39:-NqNcWFa0fp3qMIuASOD:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/847e90fefabf7ac279610fa33132d9a59683d149/Documentation/manifest-syntax.rst#L822)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this too early? These old CPU will still be in use for quite a while.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-02-12 08:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1744)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqNf5Z107SPbzFBhMhb):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

PAL
</blockquote></details>

Done
___
*[`Documentation/manifest-syntax.rst` line 800 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqFaqBIAl6WJ3SSxs1T:-NqRGFNQ3RDW7TUd3JqX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/847e90fefabf7ac279610fa33132d9a59683d149/Documentation/manifest-syntax.rst#L800)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd use "without", this "wo" is not too obvious without `/` IMO.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 822 at r1](https://reviewable.io/reviews/gramineproject/gramine/1744#-NqFbTjX1hmHbHeyGv39:-NqRGG0o1E-4hf6hdo6-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/847e90fefabf7ac279610fa33132d9a59683d149/Documentation/manifest-syntax.rst#L822)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-12 14:29 UTC, kailun-qin approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1744)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-02-12 15:27 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1744)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-12 17:05 UTC, merged