[glibc] Bump version to 2.39
gramineproject/gramine pull request #1745
Opened 2024-02-02 11:07 UTC by kailun-qin

## Description of the changes 
Drop the security fixes for CVE-2023-4527, CVE-2023-4806, CVE-2023-4911, CVE-2023-5156 and the fix for a performance regression (glibc bug 30723) applied to glibc 2.38, as they are included in the 2.39 release.

Besides the above fixes for CVEs, this version additionally includes fixes for CVE-2023-6246, CVE-2023-6779 and CVE-2023-6780.

## How to test this PR? 
CI

2024-02-02 12:21 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpdkD-KAr_MCTtrrK83:-NpdkD-L0_AO8RzZvKro:bnf4dyu) (no related file):*
FYI: The CVE numbers can be cross-checked in this document: https://lists.gnu.org/archive/html/info-gnu/2024-01/msg00017.html

___
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpdjgG_DgFyqPXCmdIh):*
`this version of Glibc` (otherwise I thought initially about the Gramine's version of the glibc patches)
___
*[`subprojects/packagefiles/glibc-2.39/gramine-syscall.patch` line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-Npdjxal3DTcjLq8IMZw:-Npdjxal3DTcjLq8IMZx:b-dcnjze) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/subprojects/packagefiles/glibc-2.39/gramine-syscall.patch#L82)):*
> ```Diff
> +	GRAMINE_SYSCALL
>  	testq	%rax, %rax
>  	jne	L(hlt)		/* This should never happen.  */
> ```

This chunk is removed. Is it because this code was removed from Glibc v2.39?

UPDATE: Yes, it was, see https://github.com/bminor/glibc/commit/edb5e0c8f915a798629717b5680a852c8bb3db25#diff-6e61a36108faa3bd2789ff376cd22d4a61ebf820267984cd058434da9dcf386d
___
*[`subprojects/packagefiles/glibc-2.39/gramine-syscall.patch` line 139 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-Npdk2z06z6uvevvfE4b:-Npdk2z11T4mpXGIJN88:b-lvkdm8) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/subprojects/packagefiles/glibc-2.39/gramine-syscall.patch#L139)):*
> ```Diff
> +	GRAMINE_SYSCALL
>  	testq	%rax, %rax
>  	jz	L(continue_no_err)
> ```

This chunk is removed. Is it because this code was removed from Glibc v2.39?

UPDATE: ditto
___
*[`subprojects/packagefiles/glibc-2.39/gramine-syscall.patch` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-Npdk4gMBgd-kkWVMGrf:-Npdk4gMBgd-kkWVMGrg:b-lvkdm8) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/subprojects/packagefiles/glibc-2.39/gramine-syscall.patch#L196)):*
> ```Diff
> +	GRAMINE_SYSCALL
>  	testq	%rax, %rax
>  	jz	L(continue_no_err)
> ```

This chunk is removed. Is it because this code was removed from Glibc v2.39?

UPDATE: ditto


<!-- Sent from Reviewable.io -->

2024-02-04 08:34 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpdjgG_DgFyqPXCmdIh):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`this version of Glibc` (otherwise I thought initially about the Gramine's version of the glibc patches)
</blockquote></details>

Done.
___
*[`subprojects/glibc-2.39-1.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpnFFcN8HTOG1Y7zuXl:-NpnFFcN8HTOG1Y7zuXm:b-on3i6b) ([raw file](https://github.com/gramineproject/gramine/blob/96f135ebbaf12f3e42daaf4cc4fb2deedc7e05a7/subprojects/glibc-2.39-1.wrap#L9)):*
> ```
> directory = glibc-2.39-1
> source_url = https://ftp.gnu.org/gnu/glibc/glibc-2.39.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/glibc-2.39.tar.gz
> ```

@woju: Would you pls help mirror this file? I'll test it later, thanks!



_Code quote:_
```
https://packages.gramineproject.io/distfiles/glibc-2.39.tar.gz
```


<!-- Sent from Reviewable.io -->

2024-02-05 01:47 UTC, mkow requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/1745#-Npqv2y9BC89-Z3xruH6):*
This should have been `squash!`, please be careful when doing autorebase - it will just drop the new commit message.


<!-- Sent from Reviewable.io -->

2024-02-05 07:28 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2024-02-05 16:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`subprojects/glibc-2.39-1.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpnFFcN8HTOG1Y7zuXl:-Npu3lgKB92zDGMkWNfD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/96f135ebbaf12f3e42daaf4cc4fb2deedc7e05a7/subprojects/glibc-2.39-1.wrap#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: Would you pls help mirror this file? I'll test it later, thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 16:56 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`subprojects/glibc-2.39-1.wrap` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1745#-NpnFFcN8HTOG1Y7zuXl:-NpuBdfA9ABRHkwboEm6:bx3ytax) ([raw file](https://github.com/gramineproject/gramine/blob/96f135ebbaf12f3e42daaf4cc4fb2deedc7e05a7/subprojects/glibc-2.39-1.wrap#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Just tested -- it works fine.


<!-- Sent from Reviewable.io -->

2024-02-05 19:07 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-02-08 20:47 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-02-09 07:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/1745#-Npqv2y9BC89-Z3xruH6):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should have been `squash!`, please be careful when doing autorebase - it will just drop the new commit message.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-10 01:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-12 07:28 UTC, merged