[tools] Surround mbedTLS's CTR_DRBG operations with spinlocks
gramineproject/gramine pull request #1746
Opened 2024-02-02 14:10 UTC by dimakuv

## Description of the changes 

mbedTLS explicitly says that CTR_DRBG operations are not thread-safe. Since we do not build mbedTLS with `MBEDTLS_THREADING_C`, we must introduce our own sync mechanism. For this, we use spinlocks.

The only identified mbedTLS function that needs this is `mbedtls_ctr_drbg_random()`. See also mbedTLS docs.

Kudos to Petr Evstifeev (Villain88) who reported this issue.

Closes #1742.

See also https://mbed-tls.readthedocs.io/projects/api/en/development/api/file/ctr__drbg_8h/#_CPPv423mbedtls_ctr_drbg_randomPvPh6size_t

## How to test this PR? 

CI is enough. Also can try the tool in #1742.

2024-02-02 14:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1746#-Npe9bPo9Fxke6SBc0I3:-Npe9bPo9Fxke6SBc0I4:b-vi681c) (no related file):*
FYI: I quickly looked through all other `mbedtls_***()` functions, and didn't find any other non-thread-safe operations.

**Please note** that RA-TLS and SecretProv related code is marked explicitly as **non-thread-safe** so we don't care if the underlying mbedTLS funcs are non-thread-safe. It is the responsibility of the user to perform synchronization of RA-TLS and SecretProv libs.

However, the PF (Protected Files) utilities are not marked as non-thread-safe, and there is no reason to mark them as such. So this PR just fixes a couple of function calls to make PF utilities thread-safe again.

___


<!-- Sent from Reviewable.io -->

2024-02-07 15:48 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1746#-Nq3F9EI8K4dqj83RvvJ):*
I'd add a note that this may have been a security issue, but we didn't analyze it's severity.


<!-- Sent from Reviewable.io -->

2024-02-07 16:00 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1746#-Nq3F9EI8K4dqj83RvvJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add a note that this may have been a security issue, but we didn't analyze it's severity.
</blockquote></details>

Ok, it's actually a bit different, please just follow the conclusions from https://github.com/gramineproject/gramine/discussions/1742#discussioncomment-8396909.


<!-- Sent from Reviewable.io -->

2024-02-07 21:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/1746#-Nq3F9EI8K4dqj83RvvJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, it's actually a bit different, please just follow the conclusions from https://github.com/gramineproject/gramine/discussions/1742#discussioncomment-8396909.
</blockquote></details>

Done, rewrote the commit message to make it more clear and to incorporate your feedback. Please check.


<!-- Sent from Reviewable.io -->

2024-02-07 22:10 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1746#-Nq4_x3QDk9blnT78xRh):*
I know it's nitpicking, but please say that we _now_ or with this commit use spinlocks. Otherwise it's confusing because it sounds like you say that we already do this.
You'll need to rebase anyways :)



_Code quote:_
```
To make CTR_DRBG thread-safe, we use spinlocks.
```


<!-- Sent from Reviewable.io -->

2024-02-08 07:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/1746#-Nq4_x3QDk9blnT78xRh):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know it's nitpicking, but please say that we _now_ or with this commit use spinlocks. Otherwise it's confusing because it sounds like you say that we already do this.
You'll need to rebase anyways :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 07:13 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-02-08 20:22 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-08 23:37 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1746)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-09 00:23 UTC, merged