Flush profile data on demand using `SIGUSR1` signal
gramineproject/gramine pull request #1751
Opened 2024-02-05 10:05 UTC by jkr0103

## Description of the changes 

Currently we don't support flushing sgx profiling data if user wants to collect only for a particular duraion (e.g., only during perf benchmarking runs). This PR add feature to flush the profile data on demand using `SIGUSR1` signal. That way user can collect data only for a particular duration. This also eliminates the noise added in profile data duing start and stop of the process.

Partially fixed issue #1711

## How to test this PR? 

Please follow the instruction [here](https://gramine.readthedocs.io/en/latest/performance.html#sgx-profiling) to enable SGX profiling. Now execute the workload in Gramine SGX. Send `SIGUSR1` signal using command `kill -SIGUSR1 <pid>` to flush the profile data. This should create a sgx profile data file which can be opened using `perf report` command.

2024-02-05 20:08 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpusYv2AhRtLmdT-DWr:-NpusYv2AhRtLmdT-DWs:bou4gle) (no related file):*
This PR looks surprisingly simple. Nice! Thanks for this.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpusbKI7REV4xMIDeeu:-NpusbKI7REV4xMIDeev:b-47xzoe) (no related file):*
Could you copy-paste some examples from your experiments? I'd like to see how things look like in reality (before testing myself locally).

Also, what applications would you recommend to test?

___
___
*[`Documentation/performance.rst` line 636 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-Npus9f0E7k3x51_OqdW:-Npus9f0E7k3x51_OqdX:b-7r768t) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/Documentation/performance.rst#L636)):*
> ```reStructuredText
> signal which would help in cases where user would like to collect profile data
> only for a particular period (e.g., during benchmarks run). Send SIGUSR1 signal
> using command ``kill -SIGUSR1 <pid>``.
> ```

You should also mention that sending multiple SIGUSR1 will create multiple files, each containing profile data collected after the previous SIGUSR1. And that this is helpful when the application runs in clearly separated stages.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqH0P4Mo1KA4sHN9N:-NpuqH0P4Mo1KA4sHN9O:b-xz0ths) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_exception.c#L191)):*
> ```C
> }
> 
> static void handle_async_sigusr1_signal(int signum, siginfo_t* info, struct ucontext* uc) {
> ```

That's a too long name. SIGUSR1 is already a "signal" and already a "asynchronous" one.

So just rename to `handle_sigusr1()`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 201 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqC5V7zeL7MyaVzpa:-NpuqC5WB_DBlY-hzFca:b-qw6kv) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_exception.c#L201)):*
> ```C
>         sgx_profile_init();
> 
>         struct debug_map* map = g_debug_map;
> ```

Please add the same comment from here: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/pal/src/host/linux-sgx/host_main.c#L314
___
*[`pal/src/host/linux-sgx/host_profile.c` line 127 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqfbG8P8pOOR7Jpad:-NpuqfbG8P8pOOR7Jpae:b-wvas5a) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L127)):*
> ```C
>     ret = DO_SYSCALL(clock_gettime, CLOCK_REALTIME, &ts);
>     if (ret < 0) {
>         log_error("sgx_profile_sample: clock_gettime failed: %s", unix_strerror(ret));
> ```

`sgx_profile_init:`
___
*[`pal/src/host/linux-sgx/host_profile.c` line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqdGR1sYtp04xeiC5:-NpuqdGR1sYtp04xeiC6:bbd323s) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L128)):*
> ```C
>     if (ret < 0) {
>         log_error("sgx_profile_sample: clock_gettime failed: %s", unix_strerror(ret));
>         return false;
> ```

What is this? Should be `goto out;`
___
*[`pal/src/host/linux-sgx/host_profile.c` line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurDS6BtbDHb3cewxz:-NpurDS6BtbDHb3cewy-:b-r7m8g) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L133)):*
> ```C
>     if (g_pal_enclave.profile_append_pid_to_filename) {
>         snprintf(g_pal_enclave.profile_filename, ARRAY_SIZE(g_pal_enclave.profile_filename),
>                  SGX_PROFILE_FILENAME_WITH_PID, (int)g_host_pid, ts.tv_sec);
> ```

`profile_filename` is 64 chars in size. Now that we also add the number of seconds, are we sure we still fit in 64 chars limit? Please check how many chars in the filenames you see in your experiments.

I think we can increase to 128 chars in size, and this will be more than enough.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-NpurvKED9s--KAHsvTu:bcgjvre) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
> ```C
>     g_mem_fd = -1;
> 
>     log_always("Profile data written to %s (%lu bytes)", g_pal_enclave.profile_filename, size);
> ```

Why this change?


<!-- Sent from Reviewable.io -->

2024-02-06 05:58 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpusbKI7REV4xMIDeeu:-NpwyS2T39b_LvGlj6Ai:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you copy-paste some examples from your experiments? I'd like to see how things look like in reality (before testing myself locally).

Also, what applications would you recommend to test?
</blockquote></details>

Done.

___
___
*[`Documentation/performance.rst` line 636 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-Npus9f0E7k3x51_OqdW:-NpwyTo-7v6wfT22N3j9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/Documentation/performance.rst#L636)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should also mention that sending multiple SIGUSR1 will create multiple files, each containing profile data collected after the previous SIGUSR1. And that this is helpful when the application runs in clearly separated stages.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqH0P4Mo1KA4sHN9N:-NpwyUxO1RSRNnUGai3q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_exception.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a too long name. SIGUSR1 is already a "signal" and already a "asynchronous" one.

So just rename to `handle_sigusr1()`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 201 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqC5V7zeL7MyaVzpa:-NpwyVuL8Sm3Y3lvg2R5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_exception.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the same comment from here: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/pal/src/host/linux-sgx/host_main.c#L314
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 127 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqfbG8P8pOOR7Jpad:-NpwyXqs110-ZdtHwgZB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sgx_profile_init:`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 128 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpuqdGR1sYtp04xeiC5:-NpwyYk608UVX4BNL0ND:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Should be `goto out;`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurDS6BtbDHb3cewxz:-Npwy_2A9JSpQND92VMJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`profile_filename` is 64 chars in size. Now that we also add the number of seconds, are we sure we still fit in 64 chars limit? Please check how many chars in the filenames you see in your experiments.

I think we can increase to 128 chars in size, and this will be more than enough.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-NpwyqDdD4I921CVgaGW:b-7nfjwk) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

User might not want to enable debug logs due to performance reasons in that case user won't know the file where profile data is written. Also this log is seen only when profiling is enabled, in that case we should always inform user about the file name where profile data is written.


<!-- Sent from Reviewable.io -->

2024-02-06 08:22 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpusbKI7REV4xMIDeeu:-NpxU7bRBQRwuZ7ZAhuR:b-5x9chr) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done where? UPDATE: You updated the PR description, I see now.

___
___
*[`pal/src/host/linux-sgx/host_exception.c` line 201 at r2](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpxUoqN1LsrYOSgnA93:-NpxUoqN1LsrYOSgnA94:b3jhgjx) ([raw file](https://github.com/gramineproject/gramine/blob/6ca2298a78a4b106fcd7cec280db72651a488270/pal/src/host/linux-sgx/host_exception.c#L201)):*
> ```C
>         sgx_profile_init();
> 
>         /* Report all ELFs already loaded (host part of PAL and dynamic libraries used by it) */
> ```

Ah, sorry, the text in parenthesis is incorrect in this case -- it's **not only** the PAL binary and its dynamic-lib dependencies. It's also the application executable itself, the LibOS binary, etc.

So please shorten to just: `/* Report all ELFs already loaded */`
___
*[`pal/src/host/linux-sgx/host_profile.c` line 133 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurDS6BtbDHb3cewxz:-NpxVAvTEoLKtbgoiqD_:b-gtlzoe) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L133)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Btw, I looked at the sizes of the longest possible strings (`sgx-perf-` prefix + PID + timestamp + `.data` suffix). Typically you'll get ~32 chars. So 64 chars would also be enough.

Nevertheless, I don't see any harm in increasing from 64 chars to 128 chars.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-NpxVY2R6zi2OR9qmitp:b-di2e63) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

User might not want to enable debug logs due to performance reasons in that case user won't know the file where profile data is written. Also this log is seen only when profiling is enabled, in that case we should always inform user about the file name where profile data is written.
</blockquote></details>

You're right, that's a good point.


<!-- Sent from Reviewable.io -->

2024-02-06 08:36 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 201 at r2](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpxUoqN1LsrYOSgnA93:-NpxYu2j6jZARH4e3Sve:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6ca2298a78a4b106fcd7cec280db72651a488270/pal/src/host/linux-sgx/host_exception.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, sorry, the text in parenthesis is incorrect in this case -- it's **not only** the PAL binary and its dynamic-lib dependencies. It's also the application executable itself, the LibOS binary, etc.

So please shorten to just: `/* Report all ELFs already loaded */`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 08:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-02-06 08:38 UTC, dimakuv commented
Jenkins, test this please

2024-02-06 09:01 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-Npxcp7S7dA5zl0zYNwu:-Npxcp7TCHkfUxef3zli:bpcoafv) (no related file):*
I tested the PR, looks like it's working. I followed the instructions in the PR description and tested Redis on my local machine.

I did 4 steps:
1. Start Redis and perform `kill -SIGUSR1` after 15 seconds; this is the enclave startup time.
2. Wait for 15 seconds and perform `kill -SIGUSR1` again; this is the do-nothing idle time.
3. Start `./src/src/redis-benchmark -t set,get`, wait till it finishes (around 15 seconds) and perform `kill -SIGUSR1` again; this is the actual benchmark-working time.
4. Wait for 15 seconds and finally terminate Redis via `kill -SIGTERM`; this is the do-nothing idle time.

So, a total of 1 minute.

### `sgx-perf-1707208751.data` (178147 bytes) -- startup (15s)

```
Samples: 21
-   76.19%  pal-sgx  libpal.so      [.] copy_u64s
     copy_u64s                                   
     copy_u64s_from_untrusted                    
     sgx_copy_to_enclave_verified                
   - sgx_copy_to_enclave                         
      + 66.67% load_trusted_or_allowed_file      
      + 9.52% copy_and_verify_trusted_file       
-   19.05%  pal-sgx  libpal.so      [.] memset   
     _real_memset (inlined)                      
     _PalVirtualMemoryAlloc                      
     PalVirtualMemoryAlloc                       
     libos_syscall_mmap                          
+    4.76%  pal-sgx  libsysdb.so    [.] snprintf_callback
```

### `sgx-perf-1707208766.data` (18547 bytes) -- idle before bench run (15s)

```
Samples: 2
-   50.00%  pal-sgx  libpal.so      [.] copy_u64s    
     copy_u64s                                       
     copy_u64s_from_untrusted                        
     sgx_copy_to_enclave_verified                    
     alloc_untrusted_futex_word                      
     _PalEventCreate                                 
     PalEventCreate                                  
     create_lock                                     
     get_new_handle                                  
     libos_syscall_openat                            
-   50.00%  pal-sgx  libpal.so      [.] slab_alloc   
     slab_alloc                                      
     malloc                                          
     calloc                                          
     _PalEventCreate                                 
     PalEventCreate                                  
     create_lock                                     
     get_new_handle                                  
     libos_syscall_openat                            
```

### `sgx-perf-1707208782.data` (2059747 bytes) -- benchmark run (15s)

```
Samples: 245
+   38.37%  pal-sgx  libpal.so         [.] enclave_entry
+    4.08%  pal-sgx  libpal.so         [.] copy_u64s
+    2.45%  pal-sgx  libpal.so         [.] sgx_ocall
+    2.04%  pal-sgx  libpal.so         [.] __save_xregs
+    2.04%  pal-sgx  redis-server      [.] je_malloc_usable_size
+    1.63%  pal-sgx  libpal.so         [.] __restore_xregs
+    1.63%  pal-sgx  libpal.so         [.] sgx_copy_from_enclave_verified
+    1.63%  pal-sgx  libsysdb.so       [.] _return_from_syscall
+    1.63%  pal-sgx  redis-server      [.] siphash_nocase
+    1.22%  pal-sgx  libpal.so         [.] sgx_exitless_ocall
+    1.22%  pal-sgx  libpal.so         [.] sgx_reset_ustack
+    1.22%  pal-sgx  libsysdb.so       [.] cmp_addr_to_vma
+    1.22%  pal-sgx  libsysdb.so       [.] libos_syscall_gettimeofday
+    1.22%  pal-sgx  libsysdb.so       [.] truncate_file_name
+    0.82%  pal-sgx  libc.so.6         [.] __GI___libc_write
+    0.82%  pal-sgx  libc.so.6         [.] __strcasecmp_l_avx2
+    0.82%  pal-sgx  libc.so.6         [.] read
+    0.82%  pal-sgx  libpal.so         [.] PalSocketSend
+    0.82%  pal-sgx  libpal.so         [.] copy_u64s_to_untrusted
+    0.82%  pal-sgx  libpal.so         [.] memcpy
+    0.82%  pal-sgx  libpal.so         [.] ocall_send
+    0.82%  pal-sgx  libpal.so         [.] sgx_is_valid_untrusted_ptr
+    0.82%  pal-sgx  libsysdb.so       [.] avl_tree_lower_bound_fn
```


### `sgx-perf-1707208796.data` (18547 bytes) -- idle after bench run (15s)

```
Samples: 2
-  100.00%  pal-sgx  libpal.so      [.] copy_u64s     
     copy_u64s                                        
     copy_u64s_from_untrusted                         
     sgx_copy_to_enclave_verified                     
     alloc_untrusted_futex_word                       
     _PalEventCreate                                  
     PalEventCreate                                   
     create_lock                                      
     get_new_handle                                   
     libos_syscall_openat 
```

___


<!-- Sent from Reviewable.io -->

2024-02-09 13:42 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r3](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqCyGRr20diiUYflYNO:-NqD5PtABb3J129TCTFW:budjv91) ([raw file](https://github.com/gramineproject/gramine/blob/43e83b20055dd80f7ac1623a12618e2c6dc032dd/pal/src/host/linux-sgx/host_exception.c#L198)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR breaks on multi-threaded apps. I tested on Memcached and got SIGSEGV.

That's because some other thread may be in the middle of saving something into the profile, and the profile data/metadata is "swept" from its feet.

We already have a global spinlock that protects all operations on profiling, so we just need to surround all this logic with a single lock/unlock. Let me prepare a fixup.
</blockquote></details>

Done. The code is pretty ugly and will need some re-arrangements, and because we don't protect `g_mem_fd` with a lock, we sometimes see (rather benign) error messages. Someone (me?) will need to make the code look better. But functionality-wise seems to be ok.


<!-- Sent from Reviewable.io -->

2024-02-12 17:16 UTC, mkow requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIE_K98g37RhGwW7a:-NqTIE_K98g37RhGwW7b:bkc0w39) (no related file):*
Why is this implemented in PAL-SGX? Profiling is a generic feature in Gramine, not SGX-specific.

___
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
missing component tag
___
*[`Documentation/performance.rst` line 639 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIhLP9jCVfaDVIMJ5:-NqTIhLQBfVZMRnxRifL:b-2zcklg) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/Documentation/performance.rst#L639)):*
> ```reStructuredText
> multiple files, each containing profile data collected after the previous
> ``SIGUSR1`` which is helpful when the application runs in clearly separated
> stages.
> ```

This has to be rewritten, it's hard to read.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTJBF56yiOfUuzyTQi:-NqTJBF56yiOfUuzyTQj:bxq9xoi) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/pal/src/host/linux-sgx/host_exception.c#L198)):*
> ```C
> #ifdef DEBUG
>     if (g_pal_enclave.profile_enable) {
>         sgx_profile_reinit();
> ```

You can't call this from a signal handler for like 10 different reasons, e.g. because it tries to take a lock which could have been already taken by the current thread when SIGUSR1 arrived, causing a deadlock.


<!-- Sent from Reviewable.io -->

2024-02-12 17:29 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTJBF56yiOfUuzyTQi:-NqTJmQW1Y4b8bRJPciQ:blmvl8m) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/pal/src/host/linux-sgx/host_exception.c#L198)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You can't call this from a signal handler for like 10 different reasons, e.g. because it tries to take a lock which could have been already taken by the current thread when SIGUSR1 arrived, causing a deadlock.
</blockquote></details>

Indeed. I think the best way would be to just set an atomic flag in the signal, and do the flush the next time profile data is collected (eg. in `sgx_profile_sample_aex`), which should happen often enough.


<!-- Sent from Reviewable.io -->

2024-02-12 18:12 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIE_K98g37RhGwW7a:-NqTVcY1AQ5JI2pYdY1L:b-a4dfk9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this implemented in PAL-SGX? Profiling is a generic feature in Gramine, not SGX-specific.
</blockquote></details>

There is nothing required for non-SGX PAL (`gramine-direct`). This kind of profiling just works, it doesn't require any additional features.

So we're augmenting already-existing SGX PAL support for profiling. See https://gramine.readthedocs.io/en/stable/performance.html#profiling-with-perf

___
___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTJBF56yiOfUuzyTQi:-NqTW1vI79U_IBCW7Vwy:b-souk0w) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/pal/src/host/linux-sgx/host_exception.c#L198)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

Indeed. I think the best way would be to just set an atomic flag in the signal, and do the flush the next time profile data is collected (eg. in `sgx_profile_sample_aex`), which should happen often enough.
</blockquote></details>

Yeah, I agree...

The code got super-ugly now, @jkr0103 or me will need to sort this all out.


<!-- Sent from Reviewable.io -->

2024-02-27 15:56 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 1 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTJBF56yiOfUuzyTQi:-NrfGp695Sv3bsqeiRJo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/pal/src/host/linux-sgx/host_exception.c#L198)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I agree...

The code got super-ugly now, @jkr0103 or me will need to sort this all out.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-29 05:43 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 3 of 6 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Previously we had a prefix like this: `[Pal/Linux-SGX] SGX perf: `

So I suggest to change the commit message to
```
[Pal/Linux-SGX] SGX perf: flush profile data on SIGUSR1 signal

This allows to collect profile data only for a particular period
(e.g., during Gramine startup or during an actual benchmark run).
```
</blockquote></details>

Could you please add it while rebasing the PR?
___
*[`Documentation/performance.rst` line 639 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIhLP9jCVfaDVIMJ5:-NrnMmxB94b0PazyzRpx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/134d730dde87e0189bf7c43e97844bf64570b8cd/Documentation/performance.rst#L639)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Proposed text:
```
It is also possible to flush the collected profile data interactively, using the
``SIGUSR1`` signal. This helps to collect profile data only for a particular
period, e.g., skipping the Gramine startup and application initialization time
and concentrating only on the actual application processing. Send ``SIGUSR1``
using command ``kill -SIGUSR1 <gramine-pid>``. Sending multiple ``SIGUSR1`` will
create multiple files, each containing profile data collected after the previous
``SIGUSR1``.
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r3](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqCyGRr20diiUYflYNO:-NrnMoep9mc0GBc5qE-y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43e83b20055dd80f7ac1623a12618e2c6dc032dd/pal/src/host/linux-sgx/host_exception.c#L198)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was fixed by @jkr0103
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 134 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-NrjuY3c3DForRYTZK4f:-NrnN-0O9rTMfGMvL3xX:bd3qxe5) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_internal.h#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Why is this needed in this header?
</blockquote></details>

It was required for `elf_ehdr_t` but not required anymore as those function declarations are moved out of this file.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 155 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-NrjwHj00n1FPy_1Vs5I:-NrnNHZ5-CDP5Qo_y7od:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_internal.h#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function must be declared as `static` in the `*.c` file, and removed from here.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 158 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-NrjwBxXCk7AAKOlx4Zu:-NrnNJAh9JdTOEmcfrpV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_internal.h#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function must be declared as `static` in the `*.c` file, and removed from here.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-Nrjw1P34XhtYnr0I_6P:-NrnNLDb7Yus94yRouNB:b9bciob) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_internal.h#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need to declare these 4 functions? You should just declare those functions as `static` in the `*.c` file, and remove from here.
</blockquote></details>

These functions are not required now, hence deleted.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 177 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-NrjwWOI5QmGT0K_x8WM:-NrnNWGb95YlS6VkmygK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`static void`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-NrjvtTrEZfuVr2vn7No:-NrnNXbRDhcAJ2KkOHcr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline after this
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 203 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-Nrjvv_A8BqOMpgNs4zp:-NrnNcPT174hkIHmpakt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove a newline
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 454 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-Nrjvzfj9LYCboWBy_Gc:-NrnNk8D9ezNkD-3sfRE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline after this
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 481 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-Nrjy4ng8O0P_GuKfkp8:-NrnNlgo2AQfV4y1h1M4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L481)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, this refactoring of `sgx_profile_report_elf()` turns out to be a complete mess...

I suggest to do the same you did with `sgx_profile_finish()` -- just remove the locks from the original function and rename it to `_thread_unsafe()`, and in the wrapper function add the locks. Yes, this will be less performant than the original code (because the critical section in-between lock and unlock becomes larger), but this function is called very rarely, only on new binaries/libraries loaded into the application.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 484 at r5](https://reviewable.io/reviews/gramineproject/gramine/1751#-Nrjv_GN4n1gf08oltU7:-NrnNmO_0ZDamPKegaUH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60892c31b14b5d902aa62d5b10de4b77f8ad1844/pal/src/host/linux-sgx/host_profile.c#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add in the very beginning: `assert(spinlock_is_locked(&g_perf_data_l [...]

2024-03-04 08:47 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Could you please add it while rebasing the PR?
</blockquote></details>

Yes I will
___
*[`pal/src/host/linux-sgx/host_internal.h` line 165 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7d9lx8R7rN63w0Fjx:-Ns7d9lx8R7rN63w0Fjy:by0m9p2) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/pal/src/host/linux-sgx/host_internal.h#L165)):*
> ```objc
> /* Record a sample during OCALL (function to be executed) */
> void sgx_profile_sample_ocall_outer(void* ocall_func);
> ```

Please re-add the accidentally removed line
___
*[`pal/src/host/linux-sgx/host_profile.c` line 206 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7d-wk3sirBmTnQ8ZZ:-Ns7d-wk3sirBmTnQ8Z_:bz02xrr) ([raw file](https://github.com/gramineproject/gramine/blob/ac13aa4b779aca8d2150ec253bd47d0699e2724e/pal/src/host/linux-sgx/host_profile.c#L206)):*
> ```C
> 
> static void sgx_profile_report_elf_thread_unsafe(const char* filename, void* addr) {
>     int ret;
> ```

Can you add `assert(spinlock_is_locked(&g_perf_data_lock));` as the very first line?
___
*[`pal/src/host/linux-sgx/host_profile.c` line 324 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7c1CY5RBzSvT1HX09:-Ns7c1CY5RBzSvT1HX0A:ba9o98n) ([raw file](https://github.com/gramineproject/gramine/blob/ac13aa4b779aca8d2150ec253bd47d0699e2724e/pal/src/host/linux-sgx/host_profile.c#L324)):*
> ```C
>     if (ret < 0) {
>         log_error("sgx_profile_reinit failed: %s", unix_strerror(ret));
>         goto out;
> ```

There seems to be no reason to have `out:` label. Just `return ret` here, and `return 0` at the end of the func.


<!-- Sent from Reviewable.io -->

2024-03-04 09:21 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 4 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 165 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7d9lx8R7rN63w0Fjx:-Ns7kbzv646hbc7V_3kX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/pal/src/host/linux-sgx/host_internal.h#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-add the accidentally removed line
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 206 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7d-wk3sirBmTnQ8ZZ:-Ns7kkK52NOOq3Si3xnq:bvj9k3l) ([raw file](https://github.com/gramineproject/gramine/blob/ac13aa4b779aca8d2150ec253bd47d0699e2724e/pal/src/host/linux-sgx/host_profile.c#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add `assert(spinlock_is_locked(&g_perf_data_lock));` as the very first line?
</blockquote></details>

This function is file-scope only and callers grabed or assert on lock, hence adding this assert seems redundant.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 324 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7c1CY5RBzSvT1HX09:-Ns7l3gnAnkj9obq3Cc1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ac13aa4b779aca8d2150ec253bd47d0699e2724e/pal/src/host/linux-sgx/host_profile.c#L324)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There seems to be no reason to have `out:` label. Just `return ret` here, and `return 0` at the end of the func.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-06 12:24 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_profile.c` line 206 at r6](https://reviewable.io/reviews/gramineproject/gramine/1751#-Ns7d-wk3sirBmTnQ8ZZ:-NsIgoHl7Wnj-4S9BFTs:b-roh8kt) ([raw file](https://github.com/gramineproject/gramine/blob/ac13aa4b779aca8d2150ec253bd47d0699e2724e/pal/src/host/linux-sgx/host_profile.c#L206)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This function is file-scope only and callers grabed or assert on lock, hence adding this assert seems redundant.
</blockquote></details>

LGTM, I'm ok with this explanation. (Indeed, very easy to verify that the lock is taken.)
___
*[`pal/src/host/linux-sgx/host_profile.c` line 57 at r7](https://reviewable.io/reviews/gramineproject/gramine/1751#-NsIh6Lw7jqrDQ6GOBDL:-NsIh6Lw7jqrDQ6GOBDM:b-l6lenl) ([raw file](https://github.com/gramineproject/gramine/blob/92cf0149aea7d6a5f5356eab825a2c77ce8b8325/pal/src/host/linux-sgx/host_profile.c#L57)):*
> ```C
> 
>     while (total < size) {
>         ret = DO_SYSCALL(pread64, g_mem_fd, (uint8_t*)dest + total, size - total,
> ```

Technically accessing `g_mem_fd` must be under the `g_perf_data_lock` spinlock, because this variable can become `-1` during re-opening of the file.

On the other hand, adding locking here would lead to tremendous overheads of profiling, which will seriously distort the perf results. So I'm very reluctant to do proper thread safety here...

In the worst case, `pread64()` will return smth like `EBADF`, and the sample will be lost. That's what I observe in practice when testing this PR. Sounds like a small correctness price to pay, so I would leave as is.


<!-- Sent from Reviewable.io -->

2024-03-08 11:34 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NsSpotq9hJY3ZieTPvf:-NsSpotq9hJY3ZieTPvg:b-xk1fdn) (no related file):*
Bar the (non-blocking) discussion point, I am fine with this PR.

I would like to test it again after all reviews are done and before merge.

___


<!-- Sent from Reviewable.io -->

2024-03-11 08:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_profile.c` line 57 at r7](https://reviewable.io/reviews/gramineproject/gramine/1751#-NsIh6Lw7jqrDQ6GOBDL:-NsgUlIw0H8OEwcrVg8T:b-4h2pgh) ([raw file](https://github.com/gramineproject/gramine/blob/92cf0149aea7d6a5f5356eab825a2c77ce8b8325/pal/src/host/linux-sgx/host_profile.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically accessing `g_mem_fd` must be under the `g_perf_data_lock` spinlock, because this variable can become `-1` during re-opening of the file.

On the other hand, adding locking here would lead to tremendous overheads of profiling, which will seriously distort the perf results. So I'm very reluctant to do proper thread safety here...

In the worst case, `pread64()` will return smth like `EBADF`, and the sample will be lost. That's what I observe in practice when testing this PR. Sounds like a small correctness price to pay, so I would leave as is.
</blockquote></details>

I thought about this a bit more, and I have the following compromise solution:

1. We introduce a global `g_null_mem_fd` which is opened at init time and points to the pseudo-file "/dev/null" (i.e., all writes to this FD are no-ops).
2. Instead of closing previous `g_mem_fd`, we `dup2()` the `g_null_mem_fd` into the previous mem FD. In other words, all writes to the previous mem FD **do not return with error**, but instead are silently dropped. Note that `dup2()` is an atomic operation, which is what we want.
3. So all threads that are still using the previous mem FD will **not fail** but instead just do nothing. At some point these threads will notice the new mem FD and will start writing their samples into this new mem FD.

This also solves the problem that I didn't realize when I wrote my previous comment (and that problem **is very serious**):
- One thread closes `g_mem_fd`, now the FD number (say `10`) that was used for mem FD is available to any other usage.
- Another thread still wants to use this old mem FD (i.e. `pread(10)`), and is preempted.
- Yet another thread wants to open some unrelated file. It notices that FD `10` is available and assigns `10` to this new file.
- Second thread is scheduled again. It now performs `pread()` from a completely irrelevant file. Gramine state becomes silently corrupted. Oops.

There is a problem that we will leak `g_mem_fd` and `g_perf_data::pd` on every SIGUSR1 signal, but it's a small price to pay. (I think the only alternative would be to use spinlocks everywhere, which is very expensive.)

---

All the above also applies to `g_perf_data::pd` FD.


<!-- Sent from Reviewable.io -->

2024-03-19 07:12 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_profile.c` line 57 at r7](https://reviewable.io/reviews/gramineproject/gramine/1751#-NsIh6Lw7jqrDQ6GOBDL:-NtKXtAaB7IN7WlQqeNO:b-pxaex3) ([raw file](https://github.com/gramineproject/gramine/blob/92cf0149aea7d6a5f5356eab825a2c77ce8b8325/pal/src/host/linux-sgx/host_profile.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought about this a bit more, and I have the following compromise solution:

1. We introduce a global `g_null_mem_fd` which is opened at init time and points to the pseudo-file "/dev/null" (i.e., all writes to this FD are no-ops).
2. Instead of closing previous `g_mem_fd`, we `dup2()` the `g_null_mem_fd` into the previous mem FD. In other words, all writes to the previous mem FD **do not return with error**, but instead are silently dropped. Note that `dup2()` is an atomic operation, which is what we want.
3. So all threads that are still using the previous mem FD will **not fail** but instead just do nothing. At some point these threads will notice the new mem FD and will start writing their samples into this new mem FD.

This also solves the problem that I didn't realize when I wrote my previous comment (and that problem **is very serious**):
- One thread closes `g_mem_fd`, now the FD number (say `10`) that was used for mem FD is available to any other usage.
- Another thread still wants to use this old mem FD (i.e. `pread(10)`), and is preempted.
- Yet another thread wants to open some unrelated file. It notices that FD `10` is available and assigns `10` to this new file.
- Second thread is scheduled again. It now performs `pread()` from a completely irrelevant file. Gramine state becomes silently corrupted. Oops.

There is a problem that we will leak `g_mem_fd` and `g_perf_data::pd` on every SIGUSR1 signal, but it's a small price to pay. (I think the only alternative would be to use spinlocks everywhere, which is very expensive.)

---

All the above also applies to `g_perf_data::pd` FD.
</blockquote></details>

`g_mem_fd` need not be closed/open again and again on `SIGUSR1`, we can keep it open for the lifetime of the process. @dimakuv do you see any issue with this approach?

I have implemented the solution (using `dup2`) suggestion above for `g_perf_data::pd`.


<!-- Sent from Reviewable.io -->

2024-04-04 13:10 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 155 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudBCNEAxPq8ZTmuXfV:-NudBCNEAxPq8ZTmuXfW:bj8vqqk) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L155)):*
> ```C
>     }
> 
>     // File `/dev/null` is open once and remain open during the lifecycle of the process
> ```

I would rephrase to this:
```
/* `/dev/null` is opened once and is kept open for the whole runtime of Gramine */
```
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 158 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudCiv96GvKFOSoTn_K:-NudCiv96GvKFOSoTn_L:b-wsdorb) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L158)):*
> ```C
>     if (g_dev_null_fd < 0) {
>         ret = DO_SYSCALL(open, "/dev/null",
>                             O_WRONLY | O_TRUNC | O_CREAT | O_CLOEXEC, PERM_rw_r__r__);
> ```

Please align `O_WRONLY ...` line to be exactly under `open, ...`
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 158 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudCuhCACV-AXuzXiDF:-NudCuhCACV-AXuzXiDG:bwrei1h) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L158)):*
> ```C
>     if (g_dev_null_fd < 0) {
>         ret = DO_SYSCALL(open, "/dev/null",
>                             O_WRONLY | O_TRUNC | O_CREAT | O_CLOEXEC, PERM_rw_r__r__);
> ```

Please remove `O_TRUNC` and `O_CREAT` -- they don't make sense in this context
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 160 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudDACl8_jJsVVePrkd:-NudDACl8_jJsVVePrke:b-ahfm5o) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L160)):*
> ```C
>                             O_WRONLY | O_TRUNC | O_CREAT | O_CLOEXEC, PERM_rw_r__r__);
>         if (ret < 0) {
>             log_error("pd_open: cannot open `/dev/null` for writing: %s", unix_strerror(fd));
> ```

Not `fd` but `ret`
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 298 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudDfAyDS-tRgAVA3zK:-NudDfAyDS-tRgAVA3zL:bfbjwq7) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L298)):*
> ```C
> 
> out:
>     if ((dup2_ret = dup2(g_dev_null_fd, pd->fd)) < 0)
> ```

We don't use Glibc wrappers here (`dup2()`) but instead raw syscalls (`DO_SYSCALL(dup2, g_dev_null_fd, pd->fd)`). Please fix.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 57 at r7](https://reviewable.io/reviews/gramineproject/gramine/1751#-NsIh6Lw7jqrDQ6GOBDL:-NudAlN58QVa2AfHmpwb:b-tdqnca) ([raw file](https://github.com/gramineproject/gramine/blob/92cf0149aea7d6a5f5356eab825a2c77ce8b8325/pal/src/host/linux-sgx/host_profile.c#L57)):*
> `g_mem_fd` need not be closed/open again and again on `SIGUSR1`, we can keep it open for the lifetime of the process. [@dimakuv](https://github.com/dimakuv) do you see any issue with this approach?

Yes, you are right. This is good how you implemented it.

> I have implemented the solution (using `dup2`) suggestion above for `g_perf_data::pd`.

Yes, looks like what I wanted.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 116 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudAUHp10VCdiRNvga8:-NudAUHq8SdLBstNB7P_:bfz2sze) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_profile.c#L116)):*
> ```C
>     g_profile_mode = g_pal_enclave.profile_mode;
> 
>     // File `/proc/self/mem` is open once and remain open during the lifecycle of the process
> ```

I would rephrase to this:
```
/* `/proc/self/mem` is opened once and is kept open for the whole runtime of Gramine */
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 121 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudAGrs1olVqWjln3AG:-NudAGrs1olVqWjln3AH:bhtyvqb) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_profile.c#L121)):*
> ```C
>         if (ret < 0) {
>             log_error("sgx_profile_init: opening /proc/self/mem failed: %s", unix_strerror(ret));
>             return ret;
> ```

Why did you replace all `goto out` with `return ret`? This looked reasonable before. Now we have sometimes `return ret` and sometimes `goto out`, which is more confusing.


<!-- Sent from Reviewable.io -->

2024-04-15 10:48 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 155 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudBCNEAxPq8ZTmuXfV:-NvWKvwJ-hMnK_kRlvoe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would rephrase to this:
```
/* `/dev/null` is opened once and is kept open for the whole runtime of Gramine */
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 158 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudCiv96GvKFOSoTn_K:-NvWKyCQ3zAwNwXz1M0U:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please align `O_WRONLY ...` line to be exactly under `open, ...`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 158 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudCuhCACV-AXuzXiDF:-NvWKyiHE5pEFNTMqQ0u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `O_TRUNC` and `O_CREAT` -- they don't make sense in this context
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 160 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudDACl8_jJsVVePrkd:-NvWL-6J7864BZ3UgQ4G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not `fd` but `ret`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 298 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudDfAyDS-tRgAVA3zK:-NvWL0lm8os9H3PZoBzQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_perf_data.c#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't use Glibc wrappers here (`dup2()`) but instead raw syscalls (`DO_SYSCALL(dup2, g_dev_null_fd, pd->fd)`). Please fix.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 116 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudAUHp10VCdiRNvga8:-NvWL3PH1J7T8wnjS8OX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_profile.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would rephrase to this:
```
/* `/proc/self/mem` is opened once and is kept open for the whole runtime of Gramine */
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 121 at r9](https://reviewable.io/reviews/gramineproject/gramine/1751#-NudAGrs1olVqWjln3AG:-NvWL5jzAR0MUQfxzWOg:b-zc4x1s) ([raw file](https://github.com/gramineproject/gramine/blob/57c61d3508a4527852815c91aa61b91fbe1646c9/pal/src/host/linux-sgx/host_profile.c#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you replace all `goto out` with `return ret`? This looked reasonable before. Now we have sometimes `return ret` and sometimes `goto out`, which is more confusing.
</blockquote></details>

reverted now.


<!-- Sent from Reviewable.io -->

2024-04-15 11:10 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)



<!-- Sent from Reviewable.io -->

2024-05-18 12:10 UTC, mkow requested changes
> Reviewed 1 of 5 files at r5, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes I will
</blockquote></details>

`[Pal/Linux-SGX] SGX perf` -> `[Pal/Linux-SGX] perf`
___
*[`Documentation/performance.rst` line 638 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyAaYTX4Whky96L1SAi:-NyAaYTX4Whky96L1SAj:b-wyv5bw) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/Documentation/performance.rst#L638)):*
> ```reStructuredText
> initialization time and concentrating only on the actual application processing.
> Send ``SIGUSR1`` using command ``kill -SIGUSR1 -<gramine-pid>``
> (note the minus sign before <gramine-pid>). Sending multiple ``SIGUSR1`` will
> ```

Do we want this? Why?
Also, then it's not `gramine-pid`, but PGID.



_Code quote:_
```reStructuredText
(note the minus sign before <gramine-pid>).
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 164 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyA_Ghq6gFEscbTFh10:-NyA_Ghq6gFEscbTFh11:bgqsnek) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L164)):*
> ```C
> }
> 
> static void sgx_profile_finish_thread_unsafe(void) {
> ```

What does "unsafe" mean in this context?
___
*[`pal/src/host/linux-sgx/host_profile.c` line 186 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyAZxT03auOdDTgZHEC:-NyAZxT03auOdDTgZHED:bf2fq61) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L186)):*
> ```C
> }
> 
> static void sgx_profile_report_elf_thread_unsafe(const char* filename, void* addr) {
> ```

Could you move this function down where it was before? It obscures the diff and it's hard to review. If you want to move functions around, I'd prefer if you did that in a follow-up PR where you only change the order of them.


<!-- Sent from Reviewable.io -->

2024-05-29 06:31 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`[Pal/Linux-SGX] SGX perf` -> `[Pal/Linux-SGX] perf`
</blockquote></details>

will be done while rebasing.
___
*[`Documentation/performance.rst` line 638 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyAaYTX4Whky96L1SAi:-Nz2-y6R6BeDs211O3na:b-6pyqde) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/Documentation/performance.rst#L638)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we want this? Why?
Also, then it's not `gramine-pid`, but PGID.
</blockquote></details>

Some workloads create multiple child process e.g. nginx have option `worker_processes 4;` which means it will create 4 child process. Minus sign is required to send the signal to all the processes in the group.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 164 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyA_Ghq6gFEscbTFh10:-Nz218zB8hOdfQC0Ry7s:b-79exnd) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does "unsafe" mean in this context?
</blockquote></details>

`unsafe` means it's not safe for multiple thread, hence require locking,. User of this function should take care of locking before using this function if expecting multiple threads to enter at the same time.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 186 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyAZxT03auOdDTgZHEC:-Nz21sbtDRHAH_7yZKyp:b-hnumji) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L186)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you move this function down where it was before? It obscures the diff and it's hard to review. If you want to move functions around, I'd prefer if you did that in a follow-up PR where you only change the order of them.
</blockquote></details>

That required forward declaration. Anyways moved it down and added forward declaration.


<!-- Sent from Reviewable.io -->

2024-06-03 00:28 UTC, mkow requested changes
> Reviewed 1 of 5 files at r5, 1 of 4 files at r8, 1 of 2 files at r10, 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 6 of 7 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCTgSC8P7xUpxcD6r:-NzQCTgSC8P7xUpxcD6s:b-9fu2s0) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L196)):*
> ```C
>     __UNUSED(uc);
> 
> #ifdef DEBUG
> ```

Please move it up to `#ifdef` the whole function.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 241 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCOvuEdvVBLLjauYV:-NzQCOvuEdvVBLLjauYW:b-xqnfmk) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L241)):*
> ```C
>         goto err;
> 
>     ret = set_signal_handler(SIGUSR1, handle_sigusr1);
> ```

Please also wrap this is `#ifdef DEBUG`.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOzhI-mIsDgT70QXq:-NzQOzhI-mIsDgT70QXr:btnxctq) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
> ```C
> 
> out:
>     if ((dup2_ret = DO_SYSCALL(dup2, g_dev_null_fd, pd->fd)) < 0)
> ```

Please keep it in a separate line, like other places in our code do.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQPWJ-06Jco5JmGw9r:-NzQPWJ-06Jco5JmGw9s:b76bawe) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
> ```C
> 
> out:
>     if ((dup2_ret = DO_SYSCALL(dup2, g_dev_null_fd, pd->fd)) < 0)
> ```

What is the exact race this change tries to prevent? And how could it possibly work if there's no synchronization point between closing/swapping this descriptor and freeing the memory holding `pd`?

It seems to me that if `close(...)` was racy before, then `free(pd)` still is.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOA7x-S3Zpk5FOVz5:-NzQOA7x-S3Zpk5FOVz6:blnvuwu) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
> ```C
>         log_error("pd_close: dup2 failed: %s", unix_strerror(dup2_ret));
> 
>     free(pd);
> ```

`pd->fd` leaks here
___
*[`pal/src/host/linux-sgx/host_profile.c` line 164 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyA_Ghq6gFEscbTFh10:-NzQQ1Bd6_Ls3m5c2pA3:bh9jx91) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L164)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

`unsafe` means it's not safe for multiple thread, hence require locking,. User of this function should take care of locking before using this function if expecting multiple threads to enter at the same time.
</blockquote></details>

Ah, ok, but no other function in this file (nor any other in Gramine) uses such naming convention. I thought it's "finish thread" with an "unsafe" suffix, not "thread unsafe" suffix.
If you want to require locking by the caller then just assert the relevant lock state.

Update:
Hmm, I guess you used this name because there exists also `sgx_profile_finish` with the locking, which is public. We prepend a single underscore for such cases + assert, see e.g.:
https://github.com/gramineproject/gramine/blob/929bb9d156597bca0694d36fe10559555322d7a1/libos/src/sys/libos_futex.c#L175-L199
___
*[`pal/src/host/linux-sgx/host_profile.c` line 40 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQSTR583ZgmeDA6cHY:-NzQSTR583ZgmeDA6cHZ:b-gdtt3b) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L40)):*
> `_WITH_PID`

This suffix only made sense before, when there were more possible names. And it's even misleading now, it mentions the PID but not the time.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 178 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQUDdi9HBJmyKbaULj:-NzQUDdi9HBJmyKbaULk:b-5unkeu) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L178)):*
> ```C
>     log_always("Profile data written to %s (%lu bytes)", g_pal_enclave.profile_filename, size);
> 
>     g_profile_enabled = false;
> ```

This variable is read in many places without a lock because it was assumed to be constant after initialization, you cannot change it here.


<!-- Sent from Reviewable.io -->

2024-06-03 00:29 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 6 of 7 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

will be done while rebasing.
</blockquote></details>

(and also, `Pal` -> `PAL`)


<!-- Sent from Reviewable.io -->

2024-06-05 04:13 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 4 of 7 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCTgSC8P7xUpxcD6r:-NzaY0n002muZcnuKAdV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please move it up to `#ifdef` the whole function.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 241 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCOvuEdvVBLLjauYV:-NzaY26OA8-hZ1Qwi4Pg:b87ar7c) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also wrap this is `#ifdef DEBUG`.
</blockquote></details>

Do we really want to force use of `SIGUSR1` only in `DEBUG` mode? I thought `SIGUSR1` might me used in non-debug mode as well in future.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOzhI-mIsDgT70QXq:-NzaYdoA54hkhqLcXVjs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please keep it in a separate line, like other places in our code do.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQPWJ-06Jco5JmGw9r:-NzaYxTqCbR3kGZhuuzZ:bj60lj7) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is the exact race this change tries to prevent? And how could it possibly work if there's no synchronization point between closing/swapping this descriptor and freeing the memory holding `pd`?

It seems to me that if `close(...)` was racy before, then `free(pd)` still is.
</blockquote></details>

Original issue was while `pd->fd` is closed but at the same time other thread might be writing  on it as there is time gap between `close` and `open` of new `pd->fd`. `dup2` does two things, `close` and `swap` of `pd->fd` value atomically, hence writing by other thread won't fail as it actually be wring to `/dev/null`.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOA7x-S3Zpk5FOVz5:-Nza_wCQ4QyHoabMkYAe:bj79sq5) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`pd->fd` leaks here
</blockquote></details>

yes, leak is there but it's small price to pay over expensive locking, also it's used only for debug purpose.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 164 at r10](https://reviewable.io/reviews/gramineproject/gramine/1751#-NyA_Ghq6gFEscbTFh10:-Nzaa9mwDK8mfju_q8B2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9438252c63ab53ce8f4e4dc9894b7faea6e504b0/pal/src/host/linux-sgx/host_profile.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, ok, but no other function in this file (nor any other in Gramine) uses such naming convention. I thought it's "finish thread" with an "unsafe" suffix, not "thread unsafe" suffix.
If you want to require locking by the caller then just assert the relevant lock state.

Update:
Hmm, I guess you used this name because there exists also `sgx_profile_finish` with the locking, which is public. We prepend a single underscore for such cases + assert, see e.g.:
https://github.com/gramineproject/gramine/blob/929bb9d156597bca0694d36fe10559555322d7a1/libos/src/sys/libos_futex.c#L175-L199
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 40 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQSTR583ZgmeDA6cHY:-Nzaa5Q7Cu_DlKxmESdL:b-p0ydt5) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `_WITH_PID`

This suffix only made sense before, when there were more possible names. And it's even misleading now, it mentions the PID but not the time.
</blockquote></details>

Added TIME as well to var name.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 178 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQUDdi9HBJmyKbaULj:-NzaaEjR3tpymnDm6OVX:bxkrwcw) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This variable is read in many places without a lock because it was assumed to be constant after initialization, you cannot change it here.
</blockquote></details>

Earlier init was done once but now it's not the case. Also it's updated with locks.


<!-- Sent from Reviewable.io -->

2024-06-05 18:58 UTC, mkow requested changes
> Reviewed 1 of 4 files at r8, 2 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 6 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCTgSC8P7xUpxcD6r:-NzdhZqc-sqMgeQ8-RD5:bkw2ygt) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L196)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The whole function please, not only the function's body.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 241 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCOvuEdvVBLLjauYV:-Nzdhfxr5EzmX3eZmO_P:b-y4ojyh) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L241)):*
> Do we really want to force use of `SIGUSR1` only in `DEBUG` mode?

But you already do that? In release mode you just install a handler which does nothing.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQPWJ-06Jco5JmGw9r:-NzdkK0L2tjH1jm8yRR7:bbfga1n) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Original issue was while `pd->fd` is closed but at the same time other thread might be writing  on it as there is time gap between `close` and `open` of new `pd->fd`. `dup2` does two things, `close` and `swap` of `pd->fd` value atomically, hence writing by other thread won't fail as it actually be wring to `/dev/null`.
</blockquote></details>

How can another thread get `pd->fd` value concurrently to the execution of this function?
If it can't, then there's no race, if it can, then what if it reads it slightly later, after `free(pd)` line?
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOA7x-S3Zpk5FOVz5:-Nzdke0M2Et7hzLIWKgt:baqb7x1) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

yes, leak is there but it's small price to pay over expensive locking, also it's used only for debug purpose.
</blockquote></details>

I don't understand. Why not just close it here?
___
*[`pal/src/host/linux-sgx/host_profile.c` line 178 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQUDdi9HBJmyKbaULj:-Nzdkyhn7rwcjILFdaVZ:bmxerur) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L178)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Earlier init was done once but now it's not the case. Also it's updated with locks.
</blockquote></details>

It's still a race condition if you write with locks, but read without.


<!-- Sent from Reviewable.io -->

2024-06-06 06:51 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 4 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCTgSC8P7xUpxcD6r:-NzgHuLd2XXizHSCSQBs:b-xyomr5) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The whole function please, not only the function's body.
</blockquote></details>

Done, we can put in inside function when need arise.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 241 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQCOvuEdvVBLLjauYV:-NzgI5KV0JezxgekZO34:b-5p26rx) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_exception.c#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Do we really want to force use of `SIGUSR1` only in `DEBUG` mode?

But you already do that? In release mode you just install a handler which does nothing.
</blockquote></details>

Agree, we can revert it in case this handler is required in `release` also.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQPWJ-06Jco5JmGw9r:-NzgIJhA8uqiUBVkgJFj:bz4wwqa) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How can another thread get `pd->fd` value concurrently to the execution of this function?
If it can't, then there's no race, if it can, then what if it reads it slightly later, after `free(pd)` line?
</blockquote></details>

Dmitrii and I have seen with `memcached` worklaod where on thread was trying to write but FD was already close, that's why we introduced `dup2` which does two operations atomically `close` and swap the value of old to new FD.

You are right on `free`,  hence removed free.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOA7x-S3Zpk5FOVz5:-NzgIzUtBqPHttaleipZ:b-hcw65j) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand. Why not just close it here?
</blockquote></details>

We repalced `close` with `dup2` to workaround the race condition. Please see above comments for more info on race condition.


<!-- Sent from Reviewable.io -->

2024-06-06 09:16 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzgjFH24jV6Yt4vFb00:-NzgjFH3-2aqbT7G7LM_:b-14r071) (no related file):*
I think the cognitive complexity of this PR is too high now. I propose the following.

### Observations on current code in `master`

1. The code is split into two logical parts:
   - The high-level glue between Gramine, SGX and perf events is encapsulated in `host_profile.c`
   - The low-level perf-specific formatting, writing to a temp buffer and flushing to the actual `sgx-perf-*.data` file is encapsulated in `host_perf_data.c`

2. Names convention:
   - The high-level glue code in `host_profile.c` contains funcs with the prefix `sgx_profile_*()`
   - The low-level code in `host_perf_data.c` contains funcs with the prefix `pd_*()`

3. The high-level glue code in `host_profile.c` always operates on a single global object `static struct perf_data* g_perf_data`.
   - This global object is allocated once in `pd_open()` and assigned to `g_perf_data` in `sgx_profile_init()`
   - This global object has fields `fd` (opened file `sgx-perf-*.data`) and `buf` (temp buffer in memory for batching of perf events).
   - At the same time, the low-level code in `host_perf_data.c` operates on a pointer to `struct perf_data*`, so gives the (unused) flexibility to operate on several objects simultaneously. Technically, `host_perf_data.c` could just always operate on global `g_perf_data`, but the current way the code is written is nicer and more extensible.

4. **All operations** on `g_perf_data` are protected using a global lock `g_perf_data_lock`.
   - These operations include the "record perf events on each AEX of each thread" code, see `sample_simple()` and `sample_stack()`. Interestingly, I didn't realize that previously, incorrectly assuming that the on-AEX code path is lockless for performance reasons.
   - The only exception that doesn't use the global lock is `sgx_profile_init()`, as it is only executed at the startup of Gramine.

### Ugly parts in the current PR

- `g_pal_enclave.profile_filename` was previously immutable. This PR makes it mutable. But this contradicts the definition of `g_pal_enclave` -- it is supposed to hold unmodifiable data. So I think this "filename" string must be moved out of `g_pal_enclave` and made a static global variable inside `host_profile.c`
- Same issue with `g_pal_enclave.profile_delayed_reinit` -- it should be made a static global variable inside `host_profile.c`
- The complexity of `sgx_profile_init()` and `sgx_profile_finish()` and their corresponding `pd_open()` and `pd_close()` is too high in this PR. 

### Solution

1. Revert all changes to `sgx_profile_init()`,`sgx_profile_finish()`, `pd_open()`, `pd_close()` 
 functions, and instead introduce `sgx_profile_reinit()` and `pd_reopen()` -- the new funcs will have only the relevant parts from the other 4 functions and will have proper global lock.
   - The `malloc()` inside `pd_open()` will stay as is. But there will be no malloc in `pd_reopen(struct perf_data* pd)`, it will only update the fields in `pd` argument.
   - All logic around `g_mem_fd` will stay as is. The new func `pd_reopen()` will not touch this variable at all.
   - All logic around `g_profile_enabled` will stay as is. It will be set to true in `sgx_profile_init()` and set to false in `sgx_profile_finish()`. The new func `sgx_profile_reinit()` will *not* touch this variable.
   - I think there's no other way to make `sgx_profile_report_elf()` globally locked, other than the way implemented in this PR. So this change should be copied into the new solution.

2. With the changes changes above and with the observation 4, I think there's no need for a `dup2()` at all. There are no data races anymore:
   - All global variables are either immutable once set (like `g_profile_enabled` and `g_mem_fd`), 
   - Or they are protected by a global lock `g_perf_data_lock` (like `g_perf_data`).

3. For ease of review and merge, we can split the proposed solution into several PRs:
   a. Move `profile_filename` from a field to a static global var in `host_profile.c`
   b. Split `sgx_profile_report_elf()` into two funcs -- one without locks and one (wrapper) with locking -- just like in this PR.
   c. All the rest of the changes.

___


<!-- Sent from Reviewable.io -->

2024-06-06 19:31 UTC, mkow reviewed
> Reviewed 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzgjFH24jV6Yt4vFb00:-Nzj-cogBrx4dUZ1w8AK:behuk2v) (no related file):*
> At the same time, the low-level code in `host_perf_data.c` operates on a pointer to `struct perf_data*`, so gives the (unused) flexibility to operate on several objects simultaneously. Technically, `host_perf_data.c` could just always operate on global `g_perf_data`, but the current way the code is written is nicer and more extensible.

I think the reason for this being a pointer is to allocate this struct only when it's actually used - because the buffer inside it takes 32MB.

> For ease of review and merge, we can split the proposed solution into several PRs:

I think we could keep it as a single PR? It's just 100 lines diff now, and probably won't be much more with this proposal? But I don't care about that too much, we can as well split.

Otherwise I like the proposal.

___


<!-- Sent from Reviewable.io -->

2024-06-07 07:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 5 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzgjFH24jV6Yt4vFb00:-NzldpOL2BfOLq-9g1ey:b-fgybiq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> At the same time, the low-level code in `host_perf_data.c` operates on a pointer to `struct perf_data*`, so gives the (unused) flexibility to operate on several objects simultaneously. Technically, `host_perf_data.c` could just always operate on global `g_perf_data`, but the current way the code is written is nicer and more extensible.

I think the reason for this being a pointer is to allocate this struct only when it's actually used - because the buffer inside it takes 32MB.

> For ease of review and merge, we can split the proposed solution into several PRs:

I think we could keep it as a single PR? It's just 100 lines diff now, and probably won't be much more with this proposal? But I don't care about that too much, we can as well split.

Otherwise I like the proposal.
</blockquote></details>

Ok, then let's keep as one PR.

@jkr0103 Will you do this new approach?

___


<!-- Sent from Reviewable.io -->

2024-06-11 06:06 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 2 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzgjFH24jV6Yt4vFb00:-O-4t_YPAcNSExtI_NGA:bb7f2mf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, then let's keep as one PR.

@jkr0103 Will you do this new approach?
</blockquote></details>

done

___
___
*[`pal/src/host/linux-sgx/host_profile.c` line 178 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQUDdi9HBJmyKbaULj:-O-4tkiLDDthJ3GbjjF4:b-1d67tq) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_profile.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's still a race condition if you write with locks, but read without.
</blockquote></details>

Reverted the changes here based on new approach discussed above.


<!-- Sent from Reviewable.io -->

2024-06-11 07:13 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 59 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52JDLAv3uyeKG70ee:-O-52JDLAv3uyeKG70ef:bfzw9lq) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L59)):*
> ```objc
> 
> extern struct pal_enclave g_pal_enclave;
> extern bool trigger_profile_reinit;
> ```

Please add `g_` prefix -- all global (non-function-scope) variables must have this prefix.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 60 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52NwREg21aQY4kTzR:-O-52NwREg21aQY4kTzS:bqnts7e) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L60)):*
> ```objc
> extern struct pal_enclave g_pal_enclave;
> extern bool trigger_profile_reinit;
> extern char profile_filename[128];
> ```

ditto (prefix)
___
*[`pal/src/host/linux-sgx/host_internal.h` line 177 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-55Toz7iJpQBaSiVkA:-O-55Toz7iJpQBaSiVkB:b-oo0mme) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L177)):*
> ```objc
> struct perf_data* pd_open(const char* file_name, bool with_stack);
> 
> ssize_t pd_close_file(struct perf_data* pd);
> ```

Can you group the new helper functions together? Like this:
```
int pd_open_file(struct perf_data* pd, const char* file_name);
ssize_t pd_close_file(struct perf_data* pd);

struct perf_data* pd_open(const char* file_name, bool with_stack);
...
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 780 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52WIH2OENbf_RjiOa:-O-52WIIB3ZpRyTa9voB:bw9pdbh) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_main.c#L780)):*
> ```C
> #ifdef DEBUG
>     enclave_info->profile_enable = false;
>     profile_filename[0] = '\0';
> ```

I think you can safely remove this line, it's not needed. (The global variable that you declare is already initialized to all zeros by the compiler.)
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 144 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52le07kt7-TWJi48K:-O-52le07kt7-TWJi48L:b-y0hoeg) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L144)):*
> ```C
> 
> int pd_open_file(struct perf_data* pd, const char* file_name) {
>     int ret, close_ret;
> ```

Please move `close_ret` to where it is used:
```
fail:
    int close_ret = DO_SYSCALL(close, fd);
    ...
```

It's just easier to read that way -- there's only one place where it is used, so it doesn't have to be declared at the top of the func.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 148 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53JT75xvbdxg01s3g:-O-53JT75xvbdxg01s3h:b2co3xr) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L148)):*
> ```C
>     int fd = DO_SYSCALL(open, file_name, O_WRONLY | O_TRUNC | O_CREAT | O_CLOEXEC, PERM_rw_r__r__);
>     if (fd < 0) {
>         log_error("pd_open: cannot open %s for writing: %s", file_name, unix_strerror(fd));
> ```

`pd_open` -> `pd_open_file`
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 149 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-530uDElJv_DCtOYkI:-O-530uDElJv_DCtOYkJ:b-4holcf) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L149)):*
> ```C
>     if (fd < 0) {
>         log_error("pd_open: cannot open %s for writing: %s", file_name, unix_strerror(fd));
>         return -EINVAL;
> ```

You can just `return fd;`
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 171 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53Lhr24BRJiJ_vKw8:-O-53Lhr24BRJiJ_vKw9:b8dacf0) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L171)):*
> ```C
>     close_ret = DO_SYSCALL(close, fd);
>     if (close_ret < 0)
>         log_error("pd_reopen: close failed: %s", unix_strerror(close_ret));
> ```

`pd_reopen` -> `pd_open_file`
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 176 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53mjD7TvNBOwWeKhm:-O-53mjD7TvNBOwWeKhn:b5pw7qo) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L176)):*
> ```C
> 
> struct perf_data* pd_open(const char* file_name, bool with_stack) {
>     int ret;
> ```

Please move `ret` directly to where it's used:
```
    int ret = pd_open_file(pd, file_name);
    ...
```
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 182 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53_Zg7WzkAR2I59Cf:-O-53_Zg7WzkAR2I59Cg:b-mrgj8i) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L182)):*
> ```C
>         log_error("pd_open: out of memory");
>         return NULL;
>     }
> ```

Please add an empty line after this one
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 185 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53bmu1Z6gTqwW-IrL:-O-53bmu1Z6gTqwW-IrM:bxwqtsf) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L185)):*
> ```C
>     ret = pd_open_file(pd, file_name);
>     if (ret < 0) {
>         log_error("pd_open: close failed: %s", unix_strerror(ret));
> ```

The error message is wrong. I think you can just remove this line, because `pd_open_file()` already prints an error message.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 186 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53hNZC7dZz6AQqhPc:-O-53hNZC7dZz6AQqhPd:bbm9std) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L186)):*
> ```C
>     if (ret < 0) {
>         log_error("pd_open: close failed: %s", unix_strerror(ret));
>         return NULL;
> ```

You forgot to `free(pd);` before returning
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 282 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-5430ECuOMcubwgIp5:-O-5430ECuOMcubwgIp6:b225y8) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L282)):*
> ```C
> 
> ssize_t pd_close_file(struct perf_data* pd) {
>     ssize_t ret = 0;
> ```

Please remove `= 0`. Because this variable will be re-assigned anyway in the next line. I don't know why it was here in the first place.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 283 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-56nyPEM8BQq5EVZqk:-O-540AH8yLamCFifj9n:b5xi5bz) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L283)):*
> ```C
> ssize_t pd_close_file(struct perf_data* pd) {
>     ssize_t ret = 0;
>     int close_ret;
> ```

ditto (move to w [...]

2024-06-11 07:52 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 2 of 7 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 59 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52JDLAv3uyeKG70ee:-O-5Gonl7VYj_bMxKPDQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `g_` prefix -- all global (non-function-scope) variables must have this prefix.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 60 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52NwREg21aQY4kTzR:-O-5GpKE4MfUdPTjM6eb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (prefix)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 177 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-55Toz7iJpQBaSiVkA:-O-5Gqw_6BwNC7QMHh-g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you group the new helper functions together? Like this:
```
int pd_open_file(struct perf_data* pd, const char* file_name);
ssize_t pd_close_file(struct perf_data* pd);

struct perf_data* pd_open(const char* file_name, bool with_stack);
...
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 780 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-52WIH2OENbf_RjiOa:-O-5Gs5I20Ek6K3VKJ4D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_main.c#L780)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you can safely remove this line, it's not needed. (The global variable that you declare is already initialized to all zeros by the compiler.)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 148 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53JT75xvbdxg01s3g:-O-5Gve40fHambJ9VISl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L148)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`pd_open` -> `pd_open_file`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 149 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-530uDElJv_DCtOYkI:-O-5Gw7w4r19XyZxVdJt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can just `return fd;`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 171 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53Lhr24BRJiJ_vKw8:-O-5GxSY039Q50Qdd1Cj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`pd_reopen` -> `pd_open_file`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 176 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53mjD7TvNBOwWeKhm:-O-5H-8IBC9djCC8syK9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move `ret` directly to where it's used:
```
    int ret = pd_open_file(pd, file_name);
    ...
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 182 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53_Zg7WzkAR2I59Cf:-O-5H0U8-r4siObEZiXd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this one
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 185 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53bmu1Z6gTqwW-IrL:-O-5H1j_11ZNNw2U_SUC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The error message is wrong. I think you can just remove this line, because `pd_open_file()` already prints an error message.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 186 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-53hNZC7dZz6AQqhPc:-O-5H2R27soRTXG6t_Vx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to `free(pd);` before returning
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 282 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-5430ECuOMcubwgIp5:-O-5H3zpEkvr0KpoqXUa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `= 0`. Because this variable will be re-assigned anyway in the next line. I don't know why it was here in the first place.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 283 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-56nyPEM8BQq5EVZqk:-O-5H5Kv0ERoB-s-SB_u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L283)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (move to where it's used)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-54lMU0AjYRVWByOl-:-O-5H6jC4nNPUQMPa6pH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`pf_close_file:`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 302 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-56srI3n28Un_l2Rn_:-O-5H7Vp2q7gVWGAz-EN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/sr [...]

2024-06-11 08:09 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 177 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-55Toz7iJpQBaSiVkA:-O-5KTLt0TS_f2cZtKtg:b-jaiej4) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L177)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, that's not what I suggested.


<!-- Sent from Reviewable.io -->

2024-06-11 08:29 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 6 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 177 at r14](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-55Toz7iJpQBaSiVkA:-O-5PayY5S9MCEwpRSOF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1152d53d89aef2ae8dee45804ff00998d3a9e65a/pal/src/host/linux-sgx/host_internal.h#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, that's not what I suggested.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-11 08:43 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-5SiC_5tXnC9q2taAM:-O-5SiCa8HTm1-V0a1m4:b-2gae03) (no related file):*
I will test this PR when other reviewers also approve and before the merge. Otherwise looks good to me.

___


<!-- Sent from Reviewable.io -->

2024-06-17 01:17 UTC, mkow requested changes
> Reviewed 4 of 5 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 59 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YUZQQ5Ps1OGIB3Iij:-O-YUZQR6rRq0LEAtv6v:b-z3ipdb) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L59)):*
> ```objc
> 
> extern struct pal_enclave g_pal_enclave;
> extern bool g_trigger_profile_reinit;
> ```

These two should be in `#ifdef DEBUG`.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Y_zBqD-DoETXWkgcL:-O-Y_zBqD-DoETXWkgcM:b-nfjcqj) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L176)):*
> ```objc
> ssize_t pd_close_file(struct perf_data* pd);
> 
> struct perf_data* pd_open(const char* file_name, bool with_stack);
> ```

I'd list this function first, the order would be more logical then.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 297 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQPWJ-06Jco5JmGw9r:-O-YSGwe2f6e3TQ0p-rg:b1onoah) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L297)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Dmitrii and I have seen with `memcached` worklaod where on thread was trying to write but FD was already close, that's why we introduced `dup2` which does two operations atomically `close` and swap the value of old to new FD.

You are right on `free`,  hence removed free.
</blockquote></details>

This hack was deleted, resolving.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 300 at r11](https://reviewable.io/reviews/gramineproject/gramine/1751#-NzQOA7x-S3Zpk5FOVz5:-O-YSC505kj8Cc5ZnpOA:b1onoah) ([raw file](https://github.com/gramineproject/gramine/blob/3890c3b73724fa173f836893724f8f61a91156b4/pal/src/host/linux-sgx/host_perf_data.c#L300)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We repalced `close` with `dup2` to workaround the race condition. Please see above comments for more info on race condition.
</blockquote></details>

This hack was deleted, resolving.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 165 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWb7z9V6WLs3gB2ij:-O-YWb8-51CK4SQUPolh:b-xqlfj8) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L165)):*
> ```C
>         goto fail;
> 
>     pd->fd = fd;
> ```

`assert(pd->fd == -1)` before overwriting this
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 168 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWrMPBgB58CBSyec1:-O-YWrMPBgB58CBSyec2:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L168)):*
> ```C
>     return 0;
> 
> fail: ;
> ```





_Suggestion:_
```C
fail:;
```
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 299 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWVAc8i7nWtvEkirj:-O-YWVAc8i7nWtvEkirk:b-i6x54s) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L299)):*
> ```C
>     if (close_ret < 0)
>         log_error("pd_close_file: close failed: %s", unix_strerror(close_ret));
> ```

Just to be sure, please set `pd->fd` to -1.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-O-YdhXo483LktI7o8Ss:b-ga784a) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're right, that's a good point.
</blockquote></details>

Then please make it `log_error` or `log_warning`. `log_always` prints even if the user set `loader.log_level = "none"`.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 39 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YcEfwA8wE0leSRDMo:-O-YcEfx7NAIpdS2RZo1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L39)):*
> ```C
> #define NSEC_IN_SEC 1000000000
> 
> /* Filenames for saved data */
> ```





_Suggestion:_
```C
/* Filename for saved data */
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 156 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Yckhh-BnmyJIfgEoL:-O-Yckhh-BnmyJIfgEoM:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L156)):*
> ```C
> 
> out:
>     if (g_mem_fd > 0) {
> ```





_Suggestion:_
```C
if (g_mem_fd >= 0) {
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 213 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YiP3H2HMPIok0ib39:-O-YiP3I21kXksLHlfBv:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L213)):*
> ```C
>     }
> 
>     log_always("Profile data written to %s (%lu bytes)", g_profile_filename, size);
> ```

ditto
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O-YkQ_EDtGDXIBA_duR:b-c10szg) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
> ```C
>     spinlock_lock(&g_perf_data_lock);
>     if (__atomic_exchange_n(&g_trigger_profile_reinit, false, __ATOMIC_ACQ_REL) == true)
>         sgx_profile_reinit();
> ```

missing result check
___
*[`pal/src/host/linux-sgx/host_profile.c` line 272 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkTAYD_aexocUPdIu:-O-YkTAYD_aexocUPdIv:b-c10szg) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L272)):*
> ```C
>     spinlock_lock(&g_perf_data_lock);
>     if (__atomic_exchange_n(&g_trigger_profile_reinit, false, __ATOMIC_ACQ_REL) == true)
>         sgx_profile_reinit();
> ```

missing result check


<!-- Sent from Reviewable.io -->

2024-06-20 06:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Y_zBqD-DoETXWkgcL:-O-oPvNC8Chriaq0xlLb:bb9nlhr) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L176)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd list this function first, the order would be more logical then.
</blockquote></details>

It was me who wanted the order differently, but Ok, both Michal and Jitender think it's better to reorder. I am Ok with this.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-O-oQDq7Ctj_5ubwrX6H:b-ypj8ek) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then please make it `log_error` or `log_warning`. `log_always` prints even if the user set `loader.log_level = "none"`.
</blockquote></details>

One issue with `log_error` and `log_warning` is that they will prepend `error: ` or `warning: ` words to the string. It's a bit misleading, as there is nothing wrong with the execution. It's more like `info: `, but we currently don't have this convenience function. Maybe we should add it.

Anyway, I think we can go with `log_error()` for now, and then add `log_info()` in another PR.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O-oQ_e36onxEU250NtZ:b-w06h99) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing result check
</blockquote></details>

Yeah, since we're in the exception handler and there's no reason to terminate the whole application, I think we can just print `log_error()`, see several lines below for how we treat errors in `pd_event_sample_simple()`.


<!-- Sent from Reviewable.io -->

2024-06-20 08:18 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-O-ohYoA7lujId0R6-4u:b7lqv9j) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One issue with `log_error` and `log_warning` is that they will prepend `error: ` or `warning: ` words to the string. It's a bit misleading, as there is nothing wrong with the execution. It's more like `info: `, but we currently don't have this convenience function. Maybe we should add it.

Anyway, I think we can go with `log_error()` for now, and then add `log_info()` in another PR.
</blockquote></details>

This log is printed in non-production case only and that too when a file is being create and this info must be passed to the user. We still can have it  even if user set `loader.log_level = "none"`.

If you still disagree, I'll make the changes.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O-ohHv074Tl2nhR6p8z:b3wae3h) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, since we're in the exception handler and there's no reason to terminate the whole application, I think we can just print `log_error()`, see several lines below for how we treat errors in `pd_event_sample_simple()`.
</blockquote></details>

we already print error message inside `sgx_profile_reinit` in all errors cases, do we really want to print error message again?


<!-- Sent from Reviewable.io -->

2024-06-20 08:33 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: 4 of 7 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 59 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YUZQQ5Ps1OGIB3Iij:-O-olHpD-w6aIF04YoO4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

These two should be in `#ifdef DEBUG`.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Y_zBqD-DoETXWkgcL:-O-olKAL-Rddelg79FjN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It was me who wanted the order differently, but Ok, both Michal and Jitender think it's better to reorder. I am Ok with this.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 165 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWb7z9V6WLs3gB2ij:-O-olKw45j9Hco4T5Axo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`assert(pd->fd == -1)` before overwriting this
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 168 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWrMPBgB58CBSyec1:-O-olLHx4h9mIWAYMuNg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L168)):*
> ```C
>     return 0;
> 
> fail: ;
> ```

Done.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 299 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YWVAc8i7nWtvEkirj:-O-olP5YDIiZuWeLAv9S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_perf_data.c#L299)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just to be sure, please set `pd->fd` to -1.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 39 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YcEfwA8wE0leSRDMo:-O-olQgM2uHzzOutwWPl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L39)):*
> ```C
> #define NSEC_IN_SEC 1000000000
> 
> /* Filenames for saved data */
> ```

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 156 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Yckhh-BnmyJIfgEoL:-O-olTpY-Jk5t6sOsFJ2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L156)):*
> ```C
> 
> out:
>     if (g_mem_fd > 0) {
> ```

Done.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 213 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YiP3H2HMPIok0ib39:-O-olZqI7roLTfRMnBLv:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L213)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O-olbw6CZTGcCrLJ-Ik:b-s83wl2) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

we already print error message inside `sgx_profile_reinit` in all errors cases, do we really want to print error message again?
</blockquote></details>

Added a comment before calling `sgx_profile_reinit`.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 272 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkTAYD_aexocUPdIu:-O-olkp8-xSYOUq3wIxK:b-s83wl2) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L272)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing result check
</blockquote></details>

Added a comment before calling `sgx_profile_reinit`.


<!-- Sent from Reviewable.io -->

2024-06-20 09:22 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)



<!-- Sent from Reviewable.io -->

2024-06-21 12:02 UTC, mkow requested changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Y_zBqD-DoETXWkgcL:-O-uUxeU3jbeAWPQV94x:bcmjmfe) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L176)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But not like that - `pd_open()` is the function creating `perf_data` object and it's always called first, it should be listed before `pd_open_file`.
___
*[`pal/src/host/linux-sgx/host_perf_data.c` line 301 at r17](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-uVNbd4RoKNn5hHuQ6:-O-uVNbd4RoKNn5hHuQ7:bd9dkhr) ([raw file](https://github.com/gramineproject/gramine/blob/a1af2a62994af7ab0585d8de5aa5e751c25eadb1/pal/src/host/linux-sgx/host_perf_data.c#L301)):*
> ```C
>         log_error("pd_close_file: close failed: %s", unix_strerror(close_ret));
> 
>     pd->fd = -1;
> ```

Should be before `if`, even a failed `close()` makes the descriptor unusable (see the corresponding manpage).
___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-O-uXEKe91NFuyKgkbBI:bfsuhw3) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
> this info must be passed to the user

It doesn't have to, it's just some useful debug information.

> We still can have it even if user set `loader.log_level = "none"`.

Yeah, and that's the very problem - it breaks the explicit user choice to stop Gramine from printing logs. All other places in our codebase respect this settings (except places before log_level is initialized).

I'm not sure what's the best solution here, I'd probably just go with `log_debug` or `log_error` with added `[INFO]`.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O-ueBDM2xRYaRcq_3Cc:bcb7ibh) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
But we cannot continue just ignoring the failure, the whole profiling state is inconsistent?

> there's no reason to terminate the whole application

I don't agree, the user wanted to perf-trace the whole app, doing that completely failed and is unusable after this point. I don't see why a user would want to continue execution in this state.
___
*[`pal/src/host/linux-sgx/host_profile.c` line 247 at r17](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-udkqiEXxfIHWpV9qK:-O-udkqiEXxfIHWpV9qL:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a1af2a62994af7ab0585d8de5aa5e751c25eadb1/pal/src/host/linux-sgx/host_profile.c#L247)):*
> ```C
>     if (__atomic_exchange_n(&g_trigger_profile_reinit, false, __ATOMIC_ACQ_REL) == true) {
>         /* No error checking since we're in exception handler and the function already prints
>            errors */
> ```





_Suggestion:_
```C
 * errors */
```


<!-- Sent from Reviewable.io -->

2024-06-24 09:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`pal/src/host/linux-sgx/host_profile.c` line 197 at r1](https://reviewable.io/reviews/gramineproject/gramine/1751#-NpurvKED9s--KAHsvTt:-O08cYBG0ERnKsrfQ5Yp:b-9lp5r1) ([raw file](https://github.com/gramineproject/gramine/blob/c62a5b9addb198fd2e205174ac8bf3e859b64cb8/pal/src/host/linux-sgx/host_profile.c#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> this info must be passed to the user

It doesn't have to, it's just some useful debug information.

> We still can have it even if user set `loader.log_level = "none"`.

Yeah, and that's the very problem - it breaks the explicit user choice to stop Gramine from printing logs. All other places in our codebase respect this settings (except places before log_level is initialized).

I'm not sure what's the best solution here, I'd probably just go with `log_debug` or `log_error` with added `[INFO]`.
</blockquote></details>

Ok, then I suggest to follow @mkow's advice and do:
```
    log_error("[INFO] Profile data written to %s (%lu bytes)", g_profile_filename, size);
```
___
*[`pal/src/host/linux-sgx/host_profile.c` line 246 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-YkQ_EDtGDXIBA_duQ:-O08cnux88SoncZzYNxj:bqajbba) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_profile.c#L246)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we cannot continue just ignoring the failure, the whole profiling state is inconsistent?

> there's no reason to terminate the whole application

I don't agree, the user wanted to perf-trace the whole app, doing that completely failed and is unusable after this point. I don't see why a user would want to continue execution in this state.
</blockquote></details>

Hm, actually @mkow is right. The perf becomes unusable. Let's do this forceful termination then:
```
    if (__atomic_exchange_n(&g_trigger_profile_reinit, false, __ATOMIC_ACQ_REL) == true) {
        ret = sgx_profile_reinit();
        if (ret < 0) {
            /* no need to print error message since sgx_profile_init() already prints it */
            BUG();
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-06-24 13:13 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-06-25 21:19 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`pal/src/host/linux-sgx/host_internal.h` line 176 at r16](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-Y_zBqD-DoETXWkgcL:-O0GEx09DvQ1W6ADqOu4:be0n2mv) ([raw file](https://github.com/gramineproject/gramine/blob/72a6399efb0dffc225e907ea105a311faf308c82/pal/src/host/linux-sgx/host_internal.h#L176)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Usually `callee` is added before `caller`, hence made the change accordingly. Anyways I updated based on the comments.
</blockquote></details>

That's mostly for `static` functions I think, because C is old and annoying, and you either need a forward declaration or declare all the functions in their dependency order. But in the headers I prefer a more logical grouping, so that it's easier to read by the function's user.


<!-- Sent from Reviewable.io -->

2024-06-26 08:01 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1751#-O-5SiC_5tXnC9q2taAM:-O0IYPWZBsR2POFoGOra:briedx0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will test this PR when other reviewers also approve and before the merge. Otherwise looks good to me.
</blockquote></details>

Tested on Redis and Memcached. Things look good to me.

Gotcha: If there's nothing to process, all Memcached threads go into sleep waiting on `epoll_wait(<forever>)`. This means that a SIGUSR1 signal will set the flag to `g_trigger_profile_reinit`, but the actual write-to-perf-file will happen only on the next SGX enclave exit, which will happen only after `epoll_wait()` returns, i.e. on a next send/recv request from the client (or on SIGTERM). I don't consider it a problem, as this is anyway what we want to measure.

___
___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/1751#-NqTIP1g-PME3rKFehM_):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(and also, `Pal` -> `PAL`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-26 08:02 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-06-26 08:03 UTC, dimakuv commented
Jenkins, test this please

2024-06-26 11:11 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1751)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-26 12:58 UTC, merged