[common] Add explicit fsync callback to Protected Files
gramineproject/gramine pull request #1753
Opened 2024-02-05 14:43 UTC by dimakuv

## Description of the changes 

Previously, Protected Files didn't have a way to ensure that the data is physically stored on disk (aka fsync). This is in contrast to the "file flush" operation, which only flushes user-space buffers to the OS kernel buffers. (Gramine confusingly uses the term "flush" to mean flush and fsync, depending on the context.)

This explicit fsync is important in e.g. persistent database workloads. It was detected on a RocksDB workload.

## How to test this PR? 

Unfortunately I don't know how to test this, without failing the system somehow...

2024-02-05 14:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/fs/libos_fs_encrypted.c` line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/1753#-NptijHp5INN4kfE4MYT:-NptijHp5INN4kfE4MYU:bomddf1) ([raw file](https://github.com/gramineproject/gramine/blob/5daf36b2afc3d2a157c1c055619210334eed1568/libos/src/fs/libos_fs_encrypted.c#L97)):*
> ```C
>     PAL_HANDLE pal_handle = (PAL_HANDLE)handle;
> 
>     int ret = PalStreamFlush(pal_handle);
> ```

Other reviewers: note that we have confusing namings in Gramine.

- `flush()` callback in LibOS FS operations is actually called by `fsync()` and `fdatasync()`.
- `PalStreamFlush()` function is also called on `fsync()` and `fdatasync()`.
- I chose `cb_fsync()` in my PR as it correctly reflects what *NIX systems do -- store the file contents on the hard disk.

So ideally I would rename all these `flush()` and `PalStreamFlush()` APIs to one of these:
- `fsync()` and `PalStreamSync()` -- similar to *NIX naming
- `flush_file_buffers` and `PalFlushFileBuffers()` -- similar to Windows naming.

For this PR, I didn't do any renames. Not sure if anyone cares about this. But if we care, then I can prepare a preliminary PR that renames all APIs to something sane and unambigious.

---

For diffs between `fflush()` and `fsync()`, see discussions https://stackoverflow.com/questions/33133222/alternative-to-fsync-for-windows-c and also NOTES in https://man7.org/linux/man-pages/man3/fflush.3.html


<!-- Sent from Reviewable.io -->

2024-02-05 17:10 UTC, ynonflumintel commented
Thank you for fixing this issue.

2024-02-07 19:59 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 1357 at r1](https://reviewable.io/reviews/gramineproject/gramine/1753#-Nq46wGmA8vsW_XikCh7:-Nq46wGmA8vsW_XikCh8:b-bo4kbc) ([raw file](https://github.com/gramineproject/gramine/blob/5daf36b2afc3d2a157c1c055619210334eed1568/common/src/protected_files/protected_files.c#L1357)):*
> ```C
>         return pf->last_error;
> 
>     /* perform a synchronous fsync only when explicitly asked for */
> ```

Why do you mean? There's no IF below, it's always called?


<!-- Sent from Reviewable.io -->

2024-02-08 07:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 1357 at r1](https://reviewable.io/reviews/gramineproject/gramine/1753#-Nq46wGmA8vsW_XikCh7:-Nq6ZsM6CR4jIVEwk_D8:bhrkmvh) ([raw file](https://github.com/gramineproject/gramine/blob/5daf36b2afc3d2a157c1c055619210334eed1568/common/src/protected_files/protected_files.c#L1357)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do you mean? There's no IF below, it's always called?
</blockquote></details>

Done. Hopefully the comment is better now.


<!-- Sent from Reviewable.io -->

2024-02-08 20:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`common/src/protected_files/protected_files.c` line 1357 at r1](https://reviewable.io/reviews/gramineproject/gramine/1753#-Nq46wGmA8vsW_XikCh7:-Nq9PsfKE1onLlInNzw_:bd4339x) ([raw file](https://github.com/gramineproject/gramine/blob/5daf36b2afc3d2a157c1c055619210334eed1568/common/src/protected_files/protected_files.c#L1357)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Hopefully the comment is better now.
</blockquote></details>

Ah, ok, now I understand this, thanks!


<!-- Sent from Reviewable.io -->

2024-02-09 00:27 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-02-09 04:00 UTC, kailun-qin approved these changes
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-02-10 01:10 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1753)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-10 01:12 UTC, merged