[LibOS] Return `0` on zero-sized `read()` syscalls on sockets
gramineproject/gramine pull request #1760
Opened 2024-02-06 10:31 UTC by dimakuv

## Description of the changes 

On Linux, `read(socket-fd, buf, /*count=*/0)` has a special case of returning zero, after all checks. Same applies for `readv()`. However, this does *not* apply to `recvfrom()`, `recvmsg()`, `recvmmsg()`.

Linux code simply says "Match SYS5 behavior" in this corner case: https://github.com/torvalds/linux/blob/99bd3cb0d12e85/net/socket.c#L1136-L1136

Apparently some applications/libraries rely on this behavior. Without this corner case, these apps would hang (if the socket is blocking) or unexpectedly return -EAGAIN (if the socket is non-blocking). Note that the underlying PalSocketRecv() uses `recvmsg()` syscall, at least on Linux-based PALs, so a simple fall-through to PAL would change the semantics of `read()`/`readv()` issued by the app.

## How to test this PR? 

Found on a closed-source app.

Not sure if this deserves a separate regression test. If anyone wants, I can add one.

2024-02-06 10:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxymX2D_tl8VRtSHXn:-NpxymX2D_tl8VRtSHXo:bjw8ije) (no related file):*
Relevant Linux sources:

- for `read()` family of syscalls:
  - https://github.com/torvalds/linux/blob/99bd3cb0d12e85/net/socket.c#L1135-L1136
  - https://github.com/torvalds/linux/blob/99bd3cb0d12e85d5114425353552121ec8f93adc/include/linux/uio.h#L292-L295
- for `recv()` family of syscalls:
  - https://github.com/torvalds/linux/blob/99bd3cb0d12e85d5114425353552121ec8f93adc/net/socket.c#L1064
  - https://github.com/torvalds/linux/blob/99bd3cb0d12e85d5114425353552121ec8f93adc/net/ipv4/tcp.c#L2562
  - (I didn't specify all the call chains, just a few examples. One can browse through the code and make sure there is no such thing as in `read()` for the `recv()` syscalls.)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxzLxk6QyVTVcgBVZ5:-NpxzLxk6QyVTVcgBVZ6:b-ja0fmp) (no related file):*
Can't show the code, but here's the strace that shows the problem in Gramine (without this PR):

### Native good case

```
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 7
connect(7, {sa_family=AF_INET, sin_port=htons(...), sin_addr=inet_addr(...)}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=7, events=POLLOUT}], 1, 10000) = 1 ([{fd=7, revents=POLLOUT}])
read(7, "", 0)              = 0
... app considers the connection established and proceeds ...
```

### Bad no-this-PR Gramine case

```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 59
connect(59, {sa_family=AF_INET, sin_port=htons(...), sin_addr=inet_addr(...)}, 16) = -1 EINPROGRESS (Operation now in progress)
ppoll([{fd=59, events=POLLOUT|POLLRDHUP}], 1, {tv_sec=10, tv_nsec=0}, NULL, 0) = 1 ([{fd=59, revents=POLLOUT}]
recvmsg(59, {…}, 0) = -1 EAGAIN (Resource temporarily unavailable)
... app doesn't expect EAGAIN and terminates loudly ...
```

___


<!-- Sent from Reviewable.io -->

2024-02-22 02:21 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxzLxk6QyVTVcgBVZ5:-NrDaWXC9LHrUQNFcO6a:b1ih5kn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can't show the code, but here's the strace that shows the problem in Gramine (without this PR):

### Native good case

```
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 7
connect(7, {sa_family=AF_INET, sin_port=htons(...), sin_addr=inet_addr(...)}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=7, events=POLLOUT}], 1, 10000) = 1 ([{fd=7, revents=POLLOUT}])
read(7, "", 0)              = 0
... app considers the connection established and proceeds ...
```

### Bad no-this-PR Gramine case

```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 59
connect(59, {sa_family=AF_INET, sin_port=htons(...), sin_addr=inet_addr(...)}, 16) = -1 EINPROGRESS (Operation now in progress)
ppoll([{fd=59, events=POLLOUT|POLLRDHUP}], 1, {tv_sec=10, tv_nsec=0}, NULL, 0) = 1 ([{fd=59, revents=POLLOUT}]
recvmsg(59, {…}, 0) = -1 EAGAIN (Resource temporarily unavailable)
... app doesn't expect EAGAIN and terminates loudly ...
```
</blockquote></details>

Why both traces show different syscalls being used by the app? (`poll` vs `ppoll` and `read vs `readmsg`)

___
___
*[`libos/include/libos_socket.h` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/1760#-NrDbCHF6gDEKgf6F28n:-NrDbCHG079Kw-01lcsr:b-amzk9a) ([raw file](https://github.com/gramineproject/gramine/blob/6d3185c82176f10e864fd5d1a3579f359c4ee59f/libos/include/libos_socket.h#L131)):*
> ```objc
> ssize_t do_recvmsg(struct libos_handle* handle, struct iovec* iov, size_t iov_len,
>                    void* msg_control, size_t* msg_controllen_ptr, void* addr, size_t* addrlen_ptr,
>                    unsigned int* flags, bool is_recv_syscall_family);
> ```

Maybe something like that instead, to explain the purpose of this flag more explicitly?



_Suggestion:_
```objc
bool emulate_recv_error_semantics
```


<!-- Sent from Reviewable.io -->

2024-02-22 08:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxzLxk6QyVTVcgBVZ5:-NrEtfHA05ey22k7Fcfj:b-j5h24f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why both traces show different syscalls being used by the app? (`poll` vs `ppoll` and `read vs `readmsg`)
</blockquote></details>

Because these are `strace` collected logs on the host. So the second log is **not** the application-to-Gramine log, it is Gramine-to-host log.

Recall that Gramine multiplexes families of syscalls into a single host syscall. In particular:
- `poll()`, `ppoll()` and `epoll_wait()` are multiplexed on a single `ppoll()` host syscall
- `read()`, `readv()`, `recv()`, `recvmsg()`, etc. are multiplexed on a single `recvmsg()` host syscall.

___


<!-- Sent from Reviewable.io -->

2024-02-22 10:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_socket.h` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/1760#-NrDbCHF6gDEKgf6F28n:-NrFJ0CbAzwrjEnwCy4S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d3185c82176f10e864fd5d1a3579f359c4ee59f/libos/include/libos_socket.h#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe something like that instead, to explain the purpose of this flag more explicitly?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 00:14 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxzLxk6QyVTVcgBVZ5:-NrXiMnK8uhSm0I7Rx70:b-ij2e9e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because these are `strace` collected logs on the host. So the second log is **not** the application-to-Gramine log, it is Gramine-to-host log.

Recall that Gramine multiplexes families of syscalls into a single host syscall. In particular:
- `poll()`, `ppoll()` and `epoll_wait()` are multiplexed on a single `ppoll()` host syscall
- `read()`, `readv()`, `recv()`, `recvmsg()`, etc. are multiplexed on a single `recvmsg()` host syscall.
</blockquote></details>

Still, why do you compare both? It seems meaningless, shouldn't you compare native strace with in-gramine gramine trace logs?

___


<!-- Sent from Reviewable.io -->

2024-02-26 09:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1760#-NpxzLxk6QyVTVcgBVZ5:-NrZbvd61HJi1S6Unbov:bkjpu9f) (no related file):*
> It seems meaningless, shouldn't you compare native strace with in-gramine gramine trace logs?

No, in this particular case this was exactly the clue to the bug.

The in-Gramine trace log shows that the app calls the exact same `read(socket-fd)` syscall. But in reality, this syscall fails. Looking at what **really happens** at the host level gave me a clue -- `read()` is transformed by Gramine into `recvmsg()`, and these  two 
 syscalls have a difference in that corner case that I explain the PR description. And that's how I learnt the real problem.

___


<!-- Sent from Reviewable.io -->

2024-02-26 09:11 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1760)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-26 14:24 UTC, merged