[LibOS] Make all pipe and UDS names Gramine-instance-specific
gramineproject/gramine pull request #1761
Opened 2024-02-06 13:37 UTC by dimakuv

## Description of the changes 

Commit ["[LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS"](https://github.com/gramineproject/gramine/commit/dd1d3dca50359d3a842cea7fb536896772438c12) had a small bug: the new LibOS logic lost the Gramine-instance-specific part of the name for some pipes and all UNIX Domain Sockets (UDSes).

This led to a benign but annoying bug of e.g. two `gramine-direct` Gramine instances being able to establish a common UDS. This could have been considered a feature, but two `gramine-sgx` Gramine instances would (correctly) fail to establish a common UDS, because each `gramine-sgx` instance has its own encryption key, and thus two UDSes would not be able to establish a secure TLS channel (even though they see each other because of this bug).

To make behavior of `gramine-direct` and `gramine-sgx` uniform, this commit forces all pipe names and UDS names to have the Gramine-instance-specific part in the name. I.e., previously UDSes had names on the host Linux like `@/gramine/<hash-of-uds-name>` and now they have names like `@/gramine/<gramine-instance-id>/<hash-of-uds-name>`.

References:
- https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-common/gramine_unix_socket_addr.c
- https://github.com/gramineproject/gramine/blob/master/libos/src/net/unix.c
- https://github.com/gramineproject/gramine/blob/master/libos/src/libos_init.c
- https://github.com/gramineproject/gramine/commit/dd1d3dca50359d3a842cea7fb536896772438c12

## How to test this PR? 

Run two Gramine instances, one creating and listening on the UDS, another connecting to the same UDS.
- Without this PR, two `gramine-direct` instances will establish a connection. (`gramine-sgx` instances won't because of failed TLS handshake.)
- With this PR, two `gramine-direct` instances will **not** be able to establish a connection.

2024-04-30 13:51 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/libos_init.c` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1761#-NwjFCFX-vRoXSVSrtwp:-NwjFCFX-vRoXSVSrtwq:b-k7cq45) ([raw file](https://github.com/gramineproject/gramine/blob/b9f1c99c2186ed6ddde3c601d2447e1103c48f07/libos/src/libos_init.c#L585)):*
> ```C
>     *hdl = pipe;
>     len = snprintf(uri, size, URI_PREFIX_PIPE "%lu/%s", g_pal_public_state->instance_id, pipename);
>     assert(len < size); /* must hold because above we did the same but with longer prefix */
> ```

I don't like this, it silently assumes that one prefix is longer than the other and will silently turn into a bug if we rename the prefixes.
Please either add a static assert for the lengths or just turn this into a normal `if`.


<!-- Sent from Reviewable.io -->

2024-05-02 08:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/libos_init.c` line 585 at r1](https://reviewable.io/reviews/gramineproject/gramine/1761#-NwjFCFX-vRoXSVSrtwp:-NwsMImy9urV-kktRmiJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b9f1c99c2186ed6ddde3c601d2447e1103c48f07/libos/src/libos_init.c#L585)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like this, it silently assumes that one prefix is longer than the other and will silently turn into a bug if we rename the prefixes.
Please either add a static assert for the lengths or just turn this into a normal `if`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 11:28 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/libos_init.c` line 586 at r2](https://reviewable.io/reviews/gramineproject/gramine/1761#-Nwt2jcR5fFfkdpiiMo-:-Nwt2jcS2PN4G6kwihse:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/995fb9d9950b2717f6c2614e408aa38b30a8e85f/libos/src/libos_init.c#L586)):*
> ```C
>     len = snprintf(uri, size, URI_PREFIX_PIPE "%lu/%s", g_pal_public_state->instance_id, pipename);
>     static_assert(static_strlen(URI_PREFIX_PIPE) < static_strlen(URI_PREFIX_PIPE_SRV),
>                   "pipe prefixes are wrong");
> ```





_Suggestion:_
```C
"without this condition the assert below should be changed into an `if`"
```


<!-- Sent from Reviewable.io -->

2024-05-02 12:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/libos_init.c` line 586 at r2](https://reviewable.io/reviews/gramineproject/gramine/1761#-Nwt2jcR5fFfkdpiiMo-:-NwtK1hBCSUzcsnQBMQs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/995fb9d9950b2717f6c2614e408aa38b30a8e85f/libos/src/libos_init.c#L586)):*
> ```C
>     len = snprintf(uri, size, URI_PREFIX_PIPE "%lu/%s", g_pal_public_state->instance_id, pipename);
>     static_assert(static_strlen(URI_PREFIX_PIPE) < static_strlen(URI_PREFIX_PIPE_SRV),
>                   "pipe prefixes are wrong");
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 12:51 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-02 14:22 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-03 22:14 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-04 02:03 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1761)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-04 12:00 UTC, merged