[common] Add 4KB slab size to slab allocator
gramineproject/gramine pull request #1763
Opened 2024-02-06 17:04 UTC by kailun-qin

## Description of the changes 
An encrypted file is split into equally-sized (4KB) chunks (nodes). The first node is the file metadata node, and the other nodes are stored as a variant of Merkle Hash Tree (MHT). In this MHT variant, MHT nodes host the crypto metadata like the encryption keys and MACs of the child nodes; data nodes host the actual encrypted data and are linked to MHT nodes.

Allocation of these 4KB file nodes can be one source of overhead for certain workloads (e.g., RocksDB compaction). To address this performance bottleneck, this commit introduces a new slab size of 4KB and therefore a new free list for 4KB blocks managed by the slab allocator.

Note that while this change can improve performance for certain memory allocation patterns, it may increase memory overhead and external fragmentation if the application rarely makes allocations of 4KB.

Fixes https://github.com/gramineproject/gramine/issues/1714.
Related to https://github.com/gramineproject/gramine/pull/1723.

## How to test this PR? 
CI

2024-02-07 08:15 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq1cOdr80XSwUGPgclr):*
I obviously don't like this, as this is special-casing the encrypted file logic into the generic slab allocator.

Moreover, objects in Gramine that take e.g. 2KB or 4KB will occupy slab slots of ~8KB, so the fragmentation of memory will be terrible.


<!-- Sent from Reviewable.io -->

2024-02-08 12:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq7ccwVDCjnHT3oKt3h:-Nq7ccwVDCjnHT3oKt3i:bvwazvd) (no related file):*
CI fails on LibOS regression tests:
```
__________________ TC_30_Syscall.test_055_mmap_emulated_tmpfs __________________
...
E   subprocess.CalledProcessError: Command '['/home/jenkins/workspace/graphene-20.04/usr/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/jenkins/workspace/graphene-20.04/usr/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file_emulated', '/mnt/tmpfs/test_mmap']' returned non-zero exit status 1.
----------------------------- Captured stdout call -----------------------------
[0.002] CREATE OK
[0.002] mmap_file_emulated: unexpected non-zero byte at addr_shared[16]
```

@kailun-qin Could you take a look?

___


<!-- Sent from Reviewable.io -->

2024-02-08 14:31 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`libos/src/fs/libos_fs_mem.c` line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq873su68JAmkpbYuZD:-Nq873su68JAmkpbYuZE:b-o9e2it) ([raw file](https://github.com/gramineproject/gramine/blob/08008552a7e0f8fee144b23508f9fae85f89c0e2/libos/src/fs/libos_fs_mem.c#L21)):*
> ```C
> 
>     size_t min_size = MIN(buf_size, (size_t)mem->size);
>     memcpy(buf, mem->buf, MIN(buf_size, min_size));
> ```

Why do you have this `MIN()` here? This should be just `min_size`


<!-- Sent from Reviewable.io -->

2024-02-08 14:45 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8AIUq6dtoFURqIybf):*
I'm confused by all these numbers. How did you arrive at 8256 bytes?
___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-Nq8A0fV4wdCiWxwA81f:bck1i6o) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
> ```objc
> #define SLAB_LEVEL_SIZES                                                       \
>     16, 32, 64, 128 - SLAB_HDR_SIZE, 256 - SLAB_HDR_SIZE, 512 - SLAB_HDR_SIZE, \
>         1024 - SLAB_HDR_SIZE, 2048 - SLAB_HDR_SIZE, 8288 - SLAB_HDR_SIZE
> ```

We *may* want to add one more level, that will cover 4KB objects, otherwise we have a huge gap between ~2KB and ~8KB, and memory fragmentation can be significant.


<!-- Sent from Reviewable.io -->

2024-02-09 05:27 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8AIUq6dtoFURqIybf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm confused by all these numbers. How did you arrive at 8256 bytes?
</blockquote></details>

hmm... the size of `file_node_t` is 8235B, the `SLAB_HDR_SIZE` is 32B, so we need at least 8267B for a slab object for our case. While drafting this code, I tried to pick a value that is aligned to 32B (a multiple of 32) for the size of slab object , so this was where 8288B came from. And 8256B (8288 - 32) is thus the user buffer size.


<!-- Sent from Reviewable.io -->

2024-02-09 07:13 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq7ccwVDCjnHT3oKt3h:-NqBgyMZBp4F6l52BTjG:b-fb1x6c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI fails on LibOS regression tests:
```
__________________ TC_30_Syscall.test_055_mmap_emulated_tmpfs __________________
...
E   subprocess.CalledProcessError: Command '['/home/jenkins/workspace/graphene-20.04/usr/lib/x86_64-linux-gnu/gramine/direct/loader', '/home/jenkins/workspace/graphene-20.04/usr/lib/x86_64-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file_emulated', '/mnt/tmpfs/test_mmap']' returned non-zero exit status 1.
----------------------------- Captured stdout call -----------------------------
[0.002] CREATE OK
[0.002] mmap_file_emulated: unexpected non-zero byte at addr_shared[16]
```

@kailun-qin Could you take a look?
</blockquote></details>

This was fixed, see change in `libos_fs_mem.c` file. (I would prefer to move it as a separate commit or even a PR, but can decide later when we have enough approvals.)

___
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq1cOdr80XSwUGPgclr):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I obviously don't like this, as this is special-casing the encrypted file logic into the generic slab allocator.

Moreover, objects in Gramine that take e.g. 2KB or 4KB will occupy slab slots of ~8KB, so the fragmentation of memory will be terrible.
</blockquote></details>

The other reviewers are leaning towards this PR instead of the previous attempt in https://github.com/gramineproject/gramine/pull/1723.

Since both patches are supposed to be only a **temporary solution** (the final solution will be using a new proper memory allocator), I'm fine with merging this PR.
___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8AIUq6dtoFURqIybf):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

hmm... the size of `file_node_t` is 8235B, the `SLAB_HDR_SIZE` is 32B, so we need at least 8267B for a slab object for our case. While drafting this code, I tried to pick a value that is aligned to 32B (a multiple of 32) for the size of slab object , so this was where 8288B came from. And 8256B (8288 - 32) is thus the user buffer size.
</blockquote></details>

Thanks, I understand the reasoning now.
___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-NqBhTpt9_hqcdsOMUU5:b-4rh5o1) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We *may* want to add one more level, that will cover 4KB objects, otherwise we have a huge gap between ~2KB and ~8KB, and memory fragmentation can be significant.
</blockquote></details>

We should probably do a couple experiments, whether we want to add yet another slab level.

I'm not blocking here though.


<!-- Sent from Reviewable.io -->

2024-02-12 10:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1763#-NqRs9_w0YxHOJ50d4a5:-NqRs9_w0YxHOJ50d4a6:bjokjxl) (no related file):*
This PR was tested independently by two Intel teams: validation team and a team that found this perf bug & required this.

The PR improves performance of Encrypted Files and is even better than #1723 in terms of resulting latency/throughput.

The PR also doesn't result in any significant performance changes (neither perf degradation nor perf improvement) in our other CI workloads.

The PR looks good to go.

___
___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-NqRsbjl4R6njM3vaD1O:b-7v5emt) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should probably do a couple experiments, whether we want to add yet another slab level.

I'm not blocking here though.
</blockquote></details>

@mkow What do you think? We can merge the PR as-is, as it was validated by two Intel teams, and no perf issues were detected. See my other comment.


<!-- Sent from Reviewable.io -->

2024-02-12 15:42 UTC, mkow reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-NqSyoBq1kQNfVr-fpVQ:b6vl18n) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow What do you think? We can merge the PR as-is, as it was validated by two Intel teams, and no perf issues were detected. See my other comment.
</blockquote></details>

// we talked about this in private and Dmitrii will do some stats to check whether this may be worth adding.
___
*[`libos/src/fs/libos_fs_mem.c` line 20 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-NqSyZWm7ODOG6q43BIt:-NqSyZWm7ODOG6q43BIu:bsbznbh) ([raw file](https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/libos/src/fs/libos_fs_mem.c#L20)):*
> ```C
>         return -ENOMEM;
> 
>     memcpy(buf, mem->buf, MIN(buf_size, (size_t)mem->size));
> ```

ouch :grimacing: 


<!-- Sent from Reviewable.io -->

2024-02-12 18:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-NqTWbZk2IFkgU0LW7J5:b-17yyl2) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

// we talked about this in private and Dmitrii will do some stats to check whether this may be worth adding.
</blockquote></details>

Ok, based on results reported in https://github.com/gramineproject/gramine/pull/1768, we are adding one additional (intermediate) slab level -- around 4KB.


<!-- Sent from Reviewable.io -->

2024-02-12 18:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`common/include/slabmgr.h` line 97 at r5](https://reviewable.io/reviews/gramineproject/gramine/1763#-Nq8A0fV4wdCiWxwA81e:-NqTZsl-CJl_aSWcO1kV:biv7ljs) ([raw file](https://github.com/gramineproject/gramine/blob/aa4c2b4982e8f374daf40b0650c3f155ea63552e/common/include/slabmgr.h#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, based on results reported in https://github.com/gramineproject/gramine/pull/1768, we are adding one additional (intermediate) slab level -- around 4KB.
</blockquote></details>

Done, also adjusted the commit message, please take a look.


<!-- Sent from Reviewable.io -->

2024-02-12 18:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-12 18:44 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-12 18:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1763#-NqRs9_w0YxHOJ50d4a5:-NqTczOi766IS18TcUef:brc2o4w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR was tested independently by two Intel teams: validation team and a team that found this perf bug & required this.

The PR improves performance of Encrypted Files and is even better than #1723 in terms of resulting latency/throughput.

The PR also doesn't result in any significant performance changes (neither perf degradation nor perf improvement) in our other CI workloads.

The PR looks good to go.
</blockquote></details>

I'm blocking for now. I asked the two Intel teams to re-do the validation again (on the new version of the PR -- finalized and rebased). Let's wait for their replies, just to be sure we didn't run into any perf regressions.

___


<!-- Sent from Reviewable.io -->

2024-02-14 00:22 UTC, kailun-qin reviewed
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-02-14 20:51 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1763)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1763#-NqRs9_w0YxHOJ50d4a5:-NqdNp7L0gWi-ffc74aJ:b-59punv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm blocking for now. I asked the two Intel teams to re-do the validation again (on the new version of the PR -- finalized and rebased). Let's wait for their replies, just to be sure we didn't run into any perf regressions.
</blockquote></details>

Done. Both teams reported no issues with the latest revision of the PR.

___


<!-- Sent from Reviewable.io -->

2024-02-14 20:52 UTC, merged