Page Cache support for trusted files
gramineproject/gramine pull request #1776
Opened 2024-02-22 11:57 UTC by jkr0103

## Description of the changes 

Please check issue #1712 for details.

Below are the results with and without this PR for nginx run:

Marit | Threads | Native| SGX (without page cache)  | SGX (with page cache) | Degradation without page cache | Degradation with page cache
-- | -- | -- | -- | -- | -- | -- |
Requests/sec  | 64 | 930275.54 | 356786.79 | 817008.28 | 97% | 12%

Fixes #1712 

## How to test this PR? 

cd gramine/CI-Examples/nginx
`make clean && make SGX=1`

### Native run:
```
./install/sbin/nginx -c conf/nginx-gramine.conf
wrk -t64 -c300 -d30s http://127.0.0.1:8002/random/10K.1.html
```
### SGX run:

```
gramine-sgx nginx
wrk -t64 -c300 -d30s http://127.0.0.1:8002/random/10K.1.html
```

Initial 1-3 run with gramine-sgx might give low performance results as trusted file chuks are added to the page cache for the first time. After 1-3 iterations results become consistent.

2024-02-23 02:25 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 697 at r1](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrIkde-0NJNmsYMXV9D:-NrIkde-0NJNmsYMXV9E:b-h2vln4) ([raw file](https://github.com/gramineproject/gramine/blob/a0740847ed6d11281399e59707629210868d388f/pal/src/host/linux-sgx/enclave_framework.c#L697)):*
> ```C
>                 buf_pos += chunk_size;
>             } else {
>                 memcpy(tmp_chunk, chunk->data, chunk_size);
> ```

Don't need to use `tmp_chunk` and this `memcpy` since we don't SHA256Update the chunk.


<!-- Sent from Reviewable.io -->

2024-02-23 02:52 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 690 at r1](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrIr0Gk9c82s2KXOcTr:-NrIr0Gk9c82s2KXOcTs:b-lshx86) ([raw file](https://github.com/gramineproject/gramine/blob/a0740847ed6d11281399e59707629210868d388f/pal/src/host/linux-sgx/enclave_framework.c#L690)):*
> ```C
> 
>         if (lruc_find(tf->cache, chunk_number) != NULL) {
>             tf_chunk_t* chunk = lruc_get(tf->cache, chunk_number);
> ```

Can move `lruc_get` to `if()` and remove the `lruc_find`.


<!-- Sent from Reviewable.io -->

2024-02-23 07:52 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 0 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 690 at r1](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrIr0Gk9c82s2KXOcTr:-NrJwuYL9ED6j5PnTCt-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0740847ed6d11281399e59707629210868d388f/pal/src/host/linux-sgx/enclave_framework.c#L690)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Can move `lruc_get` to `if()` and remove the `lruc_find`.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 697 at r1](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrIkde-0NJNmsYMXV9D:-NrJwxae9t310iTzXNoG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0740847ed6d11281399e59707629210868d388f/pal/src/host/linux-sgx/enclave_framework.c#L697)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Don't need to use `tmp_chunk` and this `memcpy` since we don't SHA256Update the chunk.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-23 08:37 UTC, llly reviewed
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 653 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK4GVH4QGq6gjPF-Aw:-NrK4GVH4QGq6gjPF-Ax:b-vwovaw) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L653)):*
> ```C
>             if (g_tf_max_chunks_in_cache > 0 && ++lcu_remove_count == 100) {
>                 log_always("High frequenty of this log indicates Trusted files chunks exceed the"
>                           " `tf_max_chunks_in_cache` limit. Please increase it in the manifest"
> ```

sgx.tf_max_chunks_in_cache



_Code quote:_
```C
tf_max_chunks_in_cache
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 714 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK5Kea8V6n4OwYpck5:-NrK5Kea8V6n4OwYpck6:b-b98eud) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L714)):*
> ```C
>                 * directly copy into buf (without a scratch buffer) and hash in-place */
>                 if (!sgx_copy_to_enclave(buf_pos, chunk_size, umem + chunk_offset, chunk_size)) {
>                     goto failed;
> ```

`ret` is not set before `goto failed`. Seems to be a bug in current code.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 733 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK572G4HkLLPlvwaYZ:-NrK572G4HkLLPlvwaY_:b-rqxvo7) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L733)):*
> ```C
>                 * needed by the caller */
>                 if (!sgx_copy_to_enclave(tmp_chunk, chunk_size, umem + chunk_offset, chunk_size)) {
>                     goto failed;
> ```

ditto.


<!-- Sent from Reviewable.io -->

2024-02-23 10:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 714 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK5Kea8V6n4OwYpck5:-NrKRL5d-Y_BCz10BKMP:b-q2mq45) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L714)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

`ret` is not set before `goto failed`. Seems to be a bug in current code.
</blockquote></details>

+1. Should set smth like `ret = -PAL_ERROR_DENIED;`
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 733 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK572G4HkLLPlvwaYZ:-NrKRawN8qnffixFzVcE:b-q2mq45) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L733)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

+1. Should set smth like `ret = -PAL_ERROR_DENIED;`


<!-- Sent from Reviewable.io -->

2024-02-23 10:24 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 653 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK4GVH4QGq6gjPF-Aw:-NrKUDFc7mFoASMghjSR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L653)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

sgx.tf_max_chunks_in_cache
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 714 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK5Kea8V6n4OwYpck5:-NrKUXfd1cuw7t2fogjK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L714)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. Should set smth like `ret = -PAL_ERROR_DENIED;`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 733 at r2](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK572G4HkLLPlvwaYZ:-NrKUYXr6oe7ZUQs4oXu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/10b9b7352bcb509de2a5cd6e2b6d40ba40105d65/pal/src/host/linux-sgx/enclave_framework.c#L733)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. Should set smth like `ret = -PAL_ERROR_DENIED;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-23 12:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 10 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @llly)

___
*[`common/src/protected_files/meson.build` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrKZUQ4-wNN-FTQu4jd:-NrL-RGj-QExCyk1GRix:b4ueec0) ([raw file](https://github.com/gramineproject/gramine/blob/7df6e85835f5b0ce7eab49fc6872921ede57d6da/common/src/protected_files/meson.build#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this required? This is wrong, common code must not depend on PAL at all.
</blockquote></details>

Done. I fixed it myself in the fixup commit (since it was a bit non-trivial to do).


<!-- Sent from Reviewable.io -->

2024-02-23 13:49 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 8 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 702 at r3](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrKZtYh8Ck6EZ6XWMRB:-NrLDOmg7hyWc2Qkiuin:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df6e85835f5b0ce7eab49fc6872921ede57d6da/pal/src/host/linux-sgx/enclave_framework.c#L702)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, this `if {} else {}` looks ugly. Why not just `continue`?
```
for (...) {
    if (g_tf_max_chunks_in_cache > 0 && (chunk = lruc_get(tf->cache, chunk_number)) != NULL) {
        ...
        continue;
    }
    
    /* we didn't find the chunk in the TF cache, must copy into enclave and add to the TF cache */
    ... old code plus your `tf_append_chunk()` ...
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 774 at r3](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrKZaVo9a5bqo6lrnT2:-NrLDTp44pHa1AYui3E6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df6e85835f5b0ce7eab49fc6872921ede57d6da/pal/src/host/linux-sgx/enclave_framework.c#L774)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add here before `free()` the following line:
```
assert(ret < 0);
```

This way we'll always immediately know about the problems with "forgotten" `ret` values.
</blockquote></details>

Done.
___
*[`CI-Examples/nginx/nginx-gramine.conf.template` line 43 at r3](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrKZDRrByututn7VaX7:-NrLDX3_3_n98QJ0fyFp:b-hfpv0l) ([raw file](https://github.com/gramineproject/gramine/blob/7df6e85835f5b0ce7eab49fc6872921ede57d6da/CI-Examples/nginx/nginx-gramine.conf.template#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you modify this file?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-02-26 06:25 UTC, llly reviewed
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)



<!-- Sent from Reviewable.io -->

2024-02-26 09:36 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_tf.h` line 92 at r3](https://reviewable.io/reviews/gramineproject/gramine/1776#-NrK_TEtDz0x7Q6mpKNS:-NrZlMIh9l-D9ie98jEN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7df6e85835f5b0ce7eab49fc6872921ede57d6da/pal/src/host/linux-sgx/enclave_tf.h#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this declaration? This func is a helper and it is used only in a single file. So just declare it there as `static` and remove from this header.

Also, the comments are useless, it's obvious what this does and what its parameters are.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 11:56 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/enclave_tf_structs.h` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_FuPD3EPnYZCeSDH_:-Nr_FuPE1I01G2EjOC7p:bi2txlt) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_tf_structs.h#L47)):*
> ```objc
> typedef struct _tf_chunk {
>     uint64_t chunk_number;
>     uint8_t data[TRUSTED_CHUNK_SIZE];
> ```

Shell we allocate memory to this array dynamically as it will be waste of 16k memory when `sgx.tf_max_chunks_in_cache` is not used in the manifest?


<!-- Sent from Reviewable.io -->

2024-02-26 13:07 UTC, dimakuv requested changes
> Reviewed 8 of 13 files at r1, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_WDUP61mdPUiJufvQ:-Nr_WDUP61mdPUiJufvR:b-rt005l) (no related file):*
Please test your PR extensively on many workloads, including multi-threaded ones.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_WIaz5vlVDzNtR-BH:-Nr_WIaz5vlVDzNtR-BI:b-oj9ec5) (no related file):*
The current PR has a cache-per-trusted-file. I wonder if we want to have a global cache for all trusted files. This will need a global lock unfortunately, and some more sophisticated `cache->key` -- currently we can get away with a simple "chunk index"; but with a global cache the key must reflect `(trusted file, chunk index)` tuple.

@mkow @kailun-qin Thoughts?

___
___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_JMoC2UHcgTDNoq9e):*
We'll need to modify this title and we'll need to add the explanatory text in the commit body.

Need to mention:
- New manifest option `sgx.tf_max_chunks_in_cache`
- That we have an explicit `common_lru_cache_dep` dependency in Meson files now
- Copy some text from Documentation, to have a quick explanation what it is and why needed

I can do it during final rebase.
___
*[`CI-Examples/nginx/nginx.manifest.template` line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_K2NwDu30MdhVEp0e:-Nr_K2NwDu30MdhVEp0f:b-fxu5f) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/CI-Examples/nginx/nginx.manifest.template#L36)):*
> ```
> sgx.max_threads = {{ '1' if env.get('EDMM', '0') == '1' else '4' }}
> 
> # Tune this parameters based on your application and system configuration for best performance
> ```

That's a useless comment. It's too generic.

Can you specify exactly why our example with Nginx requires this `48`, and what it means exactly (i.e., 48 trusted-file chunks is enough to cover common Nginx static HTTP files which will be cached by Gramine).
___
*[`common/src/meson.build` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_JFIT1et9IkUk5eLc:-Nr_JFIT1et9IkUk5eLd:b-xzhy1g) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/common/src/meson.build#L14)):*
> ```Meson
>     'init.c',
>     'location.c',
>     'lru_cache.c',
> ```

This looks wrong. Please remove from this list. You should always use `common_src_lru_cache_dep` from now on.
___
*[`Documentation/manifest-syntax.rst` line 973 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_KtXlEYLsNd2-CBCb:-Nr_KtXlEYLsNd2-CBCc:b-s16n9c) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/manifest-syntax.rst#L973)):*
> ```reStructuredText
> .. _trusted-files-max-chunks-in-cache:
> 
> Trusted files Page Cache optimization: maximum chunks in cache
> ```

Depending on the name that we will choose for the manifest option, this title will be the same as the manifest option. I.e. something like:
```
Trusted files' cache size
^^^^^^^^^^^^^^^^^^^^^^^^^
```
___
*[`Documentation/manifest-syntax.rst` line 978 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_KfvO8weTdqpmw8_4:-Nr_KfvO8weTdqpmw8_5:b88j5t1) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/manifest-syntax.rst#L978)):*
> ```reStructuredText
> ::
> 
>     sgx.tf_max_chunks_in_cache = [NUM]
> ```

Hm, now I don't like the name... I think `sgx.trusted_files_cache_size = [NUM]` would be more understandable to end users.

Let's wait for other reviewers to chime in before we change this name, especially @kailun-qin and @mkow 
___
*[`Documentation/manifest-syntax.rst` line 981 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_LMK906TaA_YxfGAm:-Nr_LMK906TaA_YxfGAn:b-ipga7) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/manifest-syntax.rst#L981)):*
> ```reStructuredText
>     (Default: 0)
> 
> This syntax specifies a limit on the number of chunks in the cache for trusted
> ```

Hm, now I understand that this "file chunks" is confusing to end users. Users should specify the actual "cache size" in KB/MB/GB, just like other sizes in the manifest.

Then Gramine internally will divide this cache size (in bytes) over the single-chunk-size to get the number of chunks, and Gramine will use this number of chunks in its code.

@kailun-qin @mkow What do you think? Will the size-in-bytes be more understandable for users?
___
*[`Documentation/manifest-syntax.rst` line 983 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_LpW9ASHdEVcmaTui:-Nr_LpW9ASHdEVcmaTuj:b-vwv4cj) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/manifest-syntax.rst#L983)):*
> ```reStructuredText
> This syntax specifies a limit on the number of chunks in the cache for trusted
> files. By default, this optimization is disabled as the limit should be
> application-specific.
> ```

There is a lot of information missing from this description:
1. What is this option exactly? (It specifies the sub-region of **each trusted file** is cached. Also, only files that are opened more than once are being cached.)
2. What is the cache eviction policy? (It is classic Least Recently Used aka LRU.)
3. When users would want to use this optimization? (When there are just a few frequently-reused files.)
4. What is the downside of this optimization? (If the files are rarely reused, then this optimization unnecessarily fills out enclave memory. Or if there are too many files, then too much memory will be spent on the cache).
___
*[`Documentation/performance.rst` line 312 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_QLZJ5fP1o0v8XYyX:-Nr_QLZJ5fP1o0v8XYyY:balyz8j) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/performance.rst#L312)):*
> ```reStructuredText
> 
> As the trusted file is read, it is split into chunks, and we compute SHA256
> hash for each chunk. Gramine doesn't implement a Page Cache feature, so it
> ```

I would remove this `doesn't implement a Page Cache feature` -- this is taken from our GitHub discussions, and I referred in that sentence to the Linux feature. I would simply start with the second half of the sentence:
```
...
hash for each chunk. Gramine doesn't have an optimization of keeping the trusted file's
content in enclave memory, which implies re-reading and re-hashing the same file contents
every time the file is read at the same offset. To address this performance bottleneck ...
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_PNNx5YznyEnBH0_e:-Nr_PNNx5YznyEnBH0_f:b-dlj0cn) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L629)):*
> ```C
> 
> static int tf_append_chunk(struct trusted_file* tf, uint8_t* chunk,
>                     uint64_t chunk_size, uint64_t chunk_number) {
> ```

Fix indentation
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_W-xGCLYVQIy7Kkt9:-Nr_W-xGCLYVQIy7KktA:bm072ps) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_f [...]

2024-03-01 12:47 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 5 of 15 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_JMoC2UHcgTDNoq9e):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We'll need to modify this title and we'll need to add the explanatory text in the commit body.

Need to mention:
- New manifest option `sgx.tf_max_chunks_in_cache`
- That we have an explicit `common_lru_cache_dep` dependency in Meson files now
- Copy some text from Documentation, to have a quick explanation what it is and why needed

I can do it during final rebase.
</blockquote></details>

Thanks
___
*[`CI-Examples/nginx/nginx.manifest.template` line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_K2NwDu30MdhVEp0e:-Nru0KKy-TwXpFOcxSzo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/CI-Examples/nginx/nginx.manifest.template#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a useless comment. It's too generic.

Can you specify exactly why our example with Nginx requires this `48`, and what it means exactly (i.e., 48 trusted-file chunks is enough to cover common Nginx static HTTP files which will be cached by Gramine).
</blockquote></details>

Done.
___
*[`common/src/meson.build` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_JFIT1et9IkUk5eLc:-Nru0N1S15UngS6nuwy5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/common/src/meson.build#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks wrong. Please remove from this list. You should always use `common_src_lru_cache_dep` from now on.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 983 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_LpW9ASHdEVcmaTui:-Nru0V8L4RANnxIsV7CC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/manifest-syntax.rst#L983)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is a lot of information missing from this description:
1. What is this option exactly? (It specifies the sub-region of **each trusted file** is cached. Also, only files that are opened more than once are being cached.)
2. What is the cache eviction policy? (It is classic Least Recently Used aka LRU.)
3. When users would want to use this optimization? (When there are just a few frequently-reused files.)
4. What is the downside of this optimization? (If the files are rarely reused, then this optimization unnecessarily fills out enclave memory. Or if there are too many files, then too much memory will be spent on the cache).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_PNNx5YznyEnBH0_e:-Nru0fg_C-u7PzcmsL7E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L629)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fix indentation
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 629 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_W-xGCLYVQIy7Kkt9:-Nru0hKA8B7Ou-nmswQh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L629)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The operations on `tf->times_first_chunk_loaded` and `tf->cache` must be protected by a spinlock, otherwise two threads working on the same file can lead to a segfault or inconsistent state.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 631 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_SLc8957toOeL5kr7:-Nru0lpQDzYEG3DpHkNK:baf96vq) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L631)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can have an integer overflow here theoretically. Since this is purely theoretical, I would smth like this:
```
    if (chunk_number == 0) {
        tf->times_first_chunk_loaded++;
        if (tf->times_first_chunk_loaded == UINT64_MAX)
            BUG(); /* should not be possible in practice */
    }
```
</blockquote></details>

I added one more check to limit  it's value to 10, hence no overflow is possible.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 632 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_PQzPDlr4-oJeYZZW:-Nru0zuN3DZ0EasYqP3v:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L632)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to explain what this logic is in a comment.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 634 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_S9fb1LZ4t8Ad0V3v:-Nru111fDEMeeI9VE8F6:betwelh) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L634)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert for better readability:
```
if (tf->times_first_chunk_loaded < 1)
```
</blockquote></details>

Did not understand it?
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 635 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_R4_E0DjGBKLV0kEu:-Nru16HO3oZD94T-t2rT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L635)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `malloc()`

You then will have to add `memset(0)` after `memcpu()`, to zero out the rest of the chunk (if the requested size was smaller than the chunk size)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 645 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_S72z5W_-w3z18zY-:-Nru17Hc4pBExJGlodqC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L645)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline after this line
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 646 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_SgQg0qKZSNfd-XtU:-Nru18oO5NOdLpP7LbIQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L646)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need the type cast
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 650 at r5](https://reviewable.io/reviews/gramineproject/gra [...]

2024-03-01 12:52 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 5 of 15 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 752 at r6](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nru3aQK0TBp20dDhCIS:-Nru3aQK0TBp20dDhCIT:bgdtkj0) ([raw file](https://github.com/gramineproject/gramine/blob/91641b24c53648552e414610ad9bd53fdc54cea1/pal/src/host/linux-sgx/enclave_framework.c#L752)):*
> ```C
>         } else {
>             /* if current chunk-to-copy only partially overlaps with the requested region-to-copy,
>             * read the file contents into a scratch buffer, verify hash and then copy only the part
> ```

Will fix indentation issue with future commit


<!-- Sent from Reviewable.io -->

2024-03-03 11:54 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 5 of 15 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 632 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_PQzPDlr4-oJeYZZW:-Ns388mh4PnMxuFvJbg9:b-aznavd) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L632)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We start adding a file to cache if file is resed for 10 times or more. We can adjustg this number based on the data from other workloads, added below data from nginx run which shows the list of file with number of times reused. I will collect similer data for other workloads as well:

``` 
No. of times file used-------------file path

4 /usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2
5 /usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libdl.so.2
5 /usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libpthread.so.0
3 /lib/x86_64-linux-gnu/libcrypt.so.1
2 /lib/x86_64-linux-gnu/libssl.so.1.1
2 /lib/x86_64-linux-gnu/libcrypto.so.1.1
3 /lib/x86_64-linux-gnu/libz.so.1
4 /usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libc.so.6
4 install/sbin/nginx
1 install/conf/nginx-gramine.conf
2 install/conf/mime.types
1 install/conf/server.crt
1 install/conf/server.key
14320000+ install/html/random/10K.1.html
```
___
*[`pal/src/host/linux-sgx/enclave_framework.c` line 635 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_R4_E0DjGBKLV0kEu:-Ns37hIZ4u7et3UCv-d6:b7vvf2a) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/pal/src/host/linux-sgx/enclave_framework.c#L635)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are `memset` and `memcpu` really required. We are filling value few line below:

```
 new_chunk->chunk_number = chunk_number;
 memcpy(new_chunk->data, chunk, chunk_size);
```


<!-- Sent from Reviewable.io -->

2024-03-04 09:31 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 5 of 15 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`Documentation/performance.rst` line 312 at r5](https://reviewable.io/reviews/gramineproject/gramine/1776#-Nr_QLZJ5fP1o0v8XYyX:-Ns7nQxMBt8Z7sr-s3f2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/17658974f684acd38bb68310474a24381550c34d/Documentation/performance.rst#L312)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this `doesn't implement a Page Cache feature` -- this is taken from our GitHub discussions, and I referred in that sentence to the Linux feature. I would simply start with the second half of the sentence:
```
...
hash for each chunk. Gramine doesn't have an optimization of keeping the trusted file's
content in enclave memory, which implies re-reading and re-hashing the same file contents
every time the file is read at the same offset. To address this performance bottleneck ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 11:35 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1776)* status: 5 of 15 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/host/linux-sgx/enclave_tf.h` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/1776#-NshHpRqCDohTVbYOGbC:-NshHpRqCDohTVbYOGbD:b-ryqdcb) ([raw file](https://github.com/gramineproject/gramine/blob/5a1f8fb6915d0d0493106317ec88711ec2622f2e/pal/src/host/linux-sgx/enclave_tf.h#L64)):*
> ```objc
>  * \brief Copy and check file contents from untrusted outside buffer to in-enclave buffer
>  *
>  * \param tf              Trusted file struct corresponding to this file.
> ```

Will fix this comment with next commit.


<!-- Sent from Reviewable.io -->

2024-09-27 12:17 UTC, sahason commented
PR #2011 is opened as the trusted file changes moved to LibOS. Closing this PR.

2024-10-01 08:01 UTC, closed without merging