[Docs] Add maintainer's manual and version script
gramineproject/gramine pull request #1788
Opened 2024-02-27 14:18 UTC by woju

## How to test this PR? 

Will really be tested during new release...

2024-02-28 07:48 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/devel/maintainer-manual.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricTJR3Iw1b2L7Z9EM:-NricTJR3Iw1b2L7Z9EN:b-8juyr9) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L20)):*
> ```reStructuredText
> https://github.com/gramineproject/gramine/issues/new?title=Release+%3Cversion%3E+TODO&body=-+%5B+%5D+draft+release+notes+%28%40%3Cowner%3E%29%0A-+%5B+%5D+draft+blogpost+%28%40%3Cowner%3E%29%0A-+%5B+%5D+draft+%23community+announcement+%28%40%3Cowner%3E%29%0A-+%5B+%5D+update+installation+instructions+%28if+a+distro+was+released+since+last+release%29+%28%40%3Cowner%3E%29%0A-+%5B+%5D+create+release+PR+%28%40%3Cowner%3E%29%0A%0Aiterate+%28update+version%2C+build+and+upload+unstable+packages%29%0A%0Afinal+stretch%3A%0A-+%5B+%5D+get+QA+signoff+%28%40%3Cowner%3E%29%0A-+%5B+%5D+approve+PR+%28%40%3Cowner%3E%29%0A-+%5B+%5D+update+version+to+final+and+push+commits+%28%40%3Cowner%3E%29%0A-+%5B+%5D+build+final+packages+%28%40%3Cowner%3E%29%0A-+%5B+%5D+upload+packages+to+release+notes+%28%40%3Cowner%3E%29%0A-+%5B+%5D+push+tag+%28%40%3Cowner%3E%29%0A-+%5B+%5D+switch+release+notes+to+pushed+tag+%28%40%3Cowner%3E%29%0A-+%5B+%5D+merge+PR+%28%40%3Cowner%3E%29%0A-+%5B+%5D+publish+release+notes+%28%40%3Cowner%3E%29%0A-+%5B+%5D+publish+blogpost+%28%40%3Cowner%3E%29%0A-+%5B+%5D+publish+on+%23community+%28%40%3Cowner%3E%29%0A
> 
> create PR
> ```

Please start titles with capital letter (because you do it in other places here)
___
*[`Documentation/devel/maintainer-manual.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricWmU-h16y5OlJ2AJ:-NricWmU-h16y5OlJ2AK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L32)):*
> ```reStructuredText
> Then set the PR on reviewable.io to be reviewed commit-by-commit.
> 
> update version in PR
> ```

ditto
___
*[`Documentation/devel/maintainer-manual.rst` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nrid2mIA-UxXpYmggMd:-Nrid2mIA-UxXpYmggMe:bajtgfz) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L37)):*
> ```reStructuredText
> .. code-block::
> 
>     git reset --hard HEAD~``
> ```

What is this syntax with double-backtick?
___
*[`Documentation/devel/maintainer-manual.rst` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridB0k6bcT9GrtCBdK:-NridB0k6bcT9GrtCBdL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L38)):*
> ```reStructuredText
> 
>     git reset --hard HEAD~``
>     scripts/release.sh X.Y~rcN``
> ```

ditto
___
*[`Documentation/devel/maintainer-manual.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricX_x1r0j-e7uiWt5:-NricX_x1r0j-e7uiWt6:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L41)):*
> ```reStructuredText
>     git push --force
> 
> tag
> ```

ditto
___
*[`Documentation/devel/maintainer-manual.rst` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridZRu2nS8YfoQrn61:-NridZRu2nS8YfoQrn62:bnt4n7g) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L65)):*
> ```reStructuredText
>     “Code signing” refers to the process of cryptographically siging your
>     contributions (commits and tags), so other people are able to mathematically
>     prove that the contribution came from the holder of particular cryptographic
> ```

`holder of a particular` (add the `a`)
___
*[`Documentation/devel/maintainer-manual.rst` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridcYu7sjDOQFRp1gn:-NridcYu7sjDOQFRp1go:b5peq7b) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L71)):*
> ```reStructuredText
> Generating key
> ^^^^^^^^^^^^^^
> First, you need to generate you key using :program:`gpg`. The key need to be "sign
> ```

`key need` -> `key needs`
___
*[`Documentation/devel/maintainer-manual.rst` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nridim26E7gDHmY7F88:-Nridim26E7gDHmY7F89:b43rmgs) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L73)):*
> ```reStructuredText
> First, you need to generate you key using :program:`gpg`. The key need to be "sign
> only"! Otherwise, if you also add encrypt capability, people will add your key
> to their MUAs and will encrypt e-mail messages to you using code signing key.
> ```

What are MUAs? Please decipher. Mail User Agent?
___
*[`scripts/release.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nrifscd0jSUBga6tGSK:-Nrifscd0jSUBga6tGSL:b-bd37vx) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/scripts/release.sh#L78)):*
> ```Shell
> "Bump "*)    commit "$V" --amend ;;
> *)                  commit "$V" ;;
> esac
> ```

I don't understand, why do you need this `case`? Why not just `bump $V; commit $V`?


<!-- Sent from Reviewable.io -->

2024-02-29 11:04 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 2 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`Documentation/devel/maintainer-manual.rst` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricTJR3Iw1b2L7Z9EM:-NroGa9c0r1tk-hI-CsB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please start titles with capital letter (because you do it in other places here)
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricWmU-h16y5OlJ2AJ:-NroGay6Aed4DrH4h-Vh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nrid2mIA-UxXpYmggMd:-NroGdzVDU9dAEJ-KOjM:bta7xry) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this syntax with double-backtick?
</blockquote></details>

It's a leftover. Removed.
___
*[`Documentation/devel/maintainer-manual.rst` line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridB0k6bcT9GrtCBdK:-NroGhe7B6CWPEQJC_4T:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NricX_x1r0j-e7uiWt5:-NroGitA88PDSWe5b5Vo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridZRu2nS8YfoQrn61:-NroGmDG3adkTTq9QBTU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`holder of a particular` (add the `a`)
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-NridcYu7sjDOQFRp1gn:-NroIL-w5bFq-eX2yWi1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`key need` -> `key needs`
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nridim26E7gDHmY7F88:-NroILIk7i7SGBNMyE7q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/Documentation/devel/maintainer-manual.rst#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are MUAs? Please decipher. Mail User Agent?
</blockquote></details>

Done.
___
*[`scripts/release.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nrifscd0jSUBga6tGSK:-NroIR5qBS7LM1OnrszJ:bvf7bmk) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/scripts/release.sh#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand, why do you need this `case`? Why not just `bump $V; commit $V`?
</blockquote></details>

For release we're creating two commits: the first one changes to version from `X.{Y-1}` to `X.Y~rcZ`, and the second one changes to `X.Ypost~UNRELEASED`. So if you're changing the commit stack from `~rcZ` to `~rc{Z+1}` (or to final `X.Y`, doesn't matter for this argument), there are two options:
- roll back two commits and recreate both of them (`git reset HEAD~2 && sed && git commit && sed && git commit`);
- roll back one commit, amend the first one and recreate the second one (`git reset HEAD~ && sed && git commit --amend && sed && git commit`).

The problem is, if you're updating from `~rcZ` to `~rc{Z+1}`, the first commit also probably contains non-trivial changes to `debian/changelog`, which can't be recreated, so `--amend` is the obvious solution, and that's what manual and the comment suggests. But if you're doing this commit stack for the first time, you need to create both commits anyway and you're not rolling back anything. So, you need to have both code paths available.

The difference is between them is detected based on title of the commit on the HEAD of the branch. If it starts with `Bump `, then we've most likely just reset the second commit and we're in the middle of the stack, so we just `--amend`. If not `Bump `, then we're creating the stack for the first time.

Do you want to have all of this in a comment?

I've fixed whitespace. Previously it said `"Bump Gramine "*`, but I removed `Gramine` to make it applicable to all repos (not just `gramineproject/gramine`, but also `gramineproject/contrib` etc.), but failed to adjust spaces.


<!-- Sent from Reviewable.io -->

2024-03-03 14:51 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 2 of 4 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-Ns3lfF3DAO9yebqQdoj:b6f4wkt) (no related file):*
Can we wait with this until https://github.com/gramineproject/gramine/pull/1784 is merged? So I could test it on the new Sphinx before merging.

___
___
*[`Documentation/devel/maintainer-manual.rst` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mFwDC5IxrWmKoUwJ:-Ns3mFwDC5IxrWmKoUwK:b-tfh184) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/Documentation/devel/maintainer-manual.rst#L70)):*
> ```reStructuredText
> 
> Generating key
> ^^^^^^^^^^^^^^
> ```

Please add en empty line here.
___
*[`Documentation/devel/DCO/index.rst` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3meAD6I25e-XaSqa4:-Ns3meAD6I25e-XaSqa5:b7iu4sx) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/Documentation/devel/DCO/index.rst#L6)):*
> ```reStructuredText
> 
>     For cryptographical “code signing”, as opposed to “signing off” your
>     commits, please refer to :doc:`../maintainer-manual`.
> ```

Could you link to the specific section there?
___
*[`scripts/release.sh` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mmqGCRzxJbJZHIJO:-Ns3mmqGCRzxJbJZHIJP:b-ond57t) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/scripts/release.sh#L3)):*
> ```Shell
> #!/bin/sh
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # SPDX-FileCopyrightText: 2024 Wojtek Porczyk <woju@invisiblethingslab.com>
> ```

We don't use this format in other files. Also, the copyright should be Intel?


<!-- Sent from Reviewable.io -->

2024-03-04 07:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 4 unresolved discussions (waiting on @woju)

___
*[`scripts/release.sh` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/1788#-Nrifscd0jSUBga6tGSK:-Ns7MkVM85mQLdmEjK90:b-7m1hnl) ([raw file](https://github.com/gramineproject/gramine/blob/e292f31f4f70025ec686abdd4502f7ac45ec5317/scripts/release.sh#L78)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For release we're creating two commits: the first one changes to version from `X.{Y-1}` to `X.Y~rcZ`, and the second one changes to `X.Ypost~UNRELEASED`. So if you're changing the commit stack from `~rcZ` to `~rc{Z+1}` (or to final `X.Y`, doesn't matter for this argument), there are two options:
- roll back two commits and recreate both of them (`git reset HEAD~2 && sed && git commit && sed && git commit`);
- roll back one commit, amend the first one and recreate the second one (`git reset HEAD~ && sed && git commit --amend && sed && git commit`).

The problem is, if you're updating from `~rcZ` to `~rc{Z+1}`, the first commit also probably contains non-trivial changes to `debian/changelog`, which can't be recreated, so `--amend` is the obvious solution, and that's what manual and the comment suggests. But if you're doing this commit stack for the first time, you need to create both commits anyway and you're not rolling back anything. So, you need to have both code paths available.

The difference is between them is detected based on title of the commit on the HEAD of the branch. If it starts with `Bump `, then we've most likely just reset the second commit and we're in the middle of the stack, so we just `--amend`. If not `Bump `, then we're creating the stack for the first time.

Do you want to have all of this in a comment?

I've fixed whitespace. Previously it said `"Bump Gramine "*`, but I removed `Gramine` to make it applicable to all repos (not just `gramineproject/gramine`, but also `gramineproject/contrib` etc.), but failed to adjust spaces.
</blockquote></details>

I'm fine with this explanation here. For historical digging, if ever needed, we'll get to your comment on GitHub.


<!-- Sent from Reviewable.io -->

2024-04-22 12:37 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 0 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-NvGTRMI66_DhPFkP3oT:b-9rk4ps) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we wait with this until https://github.com/gramineproject/gramine/pull/1784 is merged? So I could test it on the new Sphinx before merging.
</blockquote></details>

It's merged. Do you want a rebase?

___
___
*[`Documentation/devel/maintainer-manual.rst` line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mFwDC5IxrWmKoUwJ:-NvgfuyD55361qvG3n1Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/Documentation/devel/maintainer-manual.rst#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add en empty line here.
</blockquote></details>

Done.
___
*[`Documentation/devel/DCO/index.rst` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3meAD6I25e-XaSqa4:-Nw4mOqq31ufAVBmCvDu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/Documentation/devel/DCO/index.rst#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you link to the specific section there?
</blockquote></details>

Done.
___
*[`scripts/release.sh` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mmqGCRzxJbJZHIJO:-Nw4mPVPE5hoJJhrvSfK:bid1soj) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/scripts/release.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We don't use this format in other files. Also, the copyright should be Intel?
</blockquote></details>

IDK about header, I found it somewhere, maybe we should use it project wide? For now I've reverted to the version without header for consistency.

About copyright, I think this script might have been done on scaffolding time this year. Probably not Intel.


<!-- Sent from Reviewable.io -->

2024-04-25 09:33 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 0 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/maintainer-manual.rst` line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NwJ_VeC8I3MjzJf4zav:-NwJ_VeD0UJX6juwNIkg:bwa3i4v) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L9)):*
> ```reStructuredText
> Create new checklist issue (fill all ``<variable>`` before submitting):
> 
> .. new-issue:: Release <version> checklist
> ```

I'm sorry for this custom directive, but I got fed up with manual editing of the query string.


<!-- Sent from Reviewable.io -->

2024-04-28 15:44 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 0 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-Nw_MvXA1e70x9LKFRr4:b-5wconm) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's merged. Do you want a rebase?
</blockquote></details>

Yes, please.

___


<!-- Sent from Reviewable.io -->

2024-04-29 15:18 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 0 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-NweQiQa-LQBvPFfBx5L:btt4qjz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, please.
</blockquote></details>

It already is rebased. I think I rebased it when writing this second commit about verifying signatures.

___


<!-- Sent from Reviewable.io -->

2024-05-07 12:35 UTC, dimakuv requested changes
> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`Documentation/verify-sig.rst` line 115 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI-gxR2-uGQZiUDuBC:-NxI-gxR2-uGQZiUDuBD:bdlefrf) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L115)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> If you happen to have your own PGP key pair, you can choose sign the key with
> ```

`choose sign` -> `choose to sign`
___
*[`Documentation/verify-sig.rst` line 178 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI-sZ086VtdejK0lhr:-NxI-sZ086VtdejK0lhs:brg1blw) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L178)):*
> ```reStructuredText
> .. no, I don't have "0000000000000000" key
> 
> If you know what you're doing, you can use another singing command in place of
> ```

`singing` -> `signing`
___
*[`Documentation/verify-sig.rst` line 206 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI0KYi-wGjTvTxcHcC:-NxI0KYi-wGjTvTxcHcD:b-1gymkh) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L206)):*
> ```reStructuredText
>     gpg:                using EDDSA key 9C4D27D9157EF771A4283926044D9664E7A77E16
>     gpg: Good signature from "Wojciech Porczyk (Gramine code signing key) <woju@invisiblethingslab.com>" [full]
>     % git verify-tag v1.6.2
> ```

Could you add an empty line before this command?
___
*[`Documentation/verify-sig.rst` line 254 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI0Z0-0WKcdMbwWrYB:-NxI0Z0-0WKcdMbwWrYC:b-obthb9) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L254)):*
> ```reStructuredText
>     [...]
>     
>     % % git verify-commit a971e30f3430b4b8079ec42f5d035ced68130bdc
> ```

`% %` -> `%`
___
*[`Documentation/devel/maintainer-manual.rst` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1cLJ11bEZ4gluM-e:-NxI1cLJ11bEZ4gluM-f:b89juzc) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L80)):*
> ```reStructuredText
>     signature. For details, please read :doc:`DCO/index`.
> 
>     “Code signing” refers to the process of cryptographically siging your
> ```

`siging` -> `signing`
___
*[`Documentation/devel/maintainer-manual.rst` line 89 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1iPPB12Sw9_dwQgG:-NxI1iPPB12Sw9_dwQgH:b6nc5mi) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L89)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^
> 
> First, you need to generate you key using :program:`gpg`. The key needs to be
> ```

`you key` -> `your key`
___
*[`Documentation/devel/maintainer-manual.rst` line 94 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1qVzAI1zdbROCLSP:-NxI1qVzAI1zdbROCLSQ:brg1blw) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L94)):*
> ```reStructuredText
> to you using code signing key. This is not desired, the key generated for the
> purpose of code signing should not be used in any other context (e.g. e-mail or
> singing code in other projects).
> ```

`singing` -> `signing`


<!-- Sent from Reviewable.io -->

2024-05-07 13:16 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 8 of 10 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-NxIB-VA1D3njTiLPoRy:b-bc3wxe) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I enabled this PR in ReadTheDocs: https://gramine.readthedocs.io/en/woju-docs-202402/
</blockquote></details>

Adding separate versions is not needed anymore, since we build all PRs: https://gramine--1788.org.readthedocs.build/en/1788/ (you can substitute any valid number of a PR).

Webhook works, just reporting the status doesn't.

___
___
*[`Documentation/verify-sig.rst` line 115 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI-gxR2-uGQZiUDuBC:-NxI8Ygy-pmuL7Hr15Fs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`choose sign` -> `choose to sign`
</blockquote></details>

Done.
___
*[`Documentation/verify-sig.rst` line 178 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI-sZ086VtdejK0lhr:-NxI8cBlB83fb-Fzp3VA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`singing` -> `signing`
</blockquote></details>

Done.
___
*[`Documentation/verify-sig.rst` line 206 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI0KYi-wGjTvTxcHcC:-NxI8g0zDIfazQdTtZcK:brrv8u6) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line before this command?
</blockquote></details>

Just empty line, no, I don't want to, because it is (was) a single listing. I guess I can split it into two paragraphs instead. Did the same to verifying commits too.
___
*[`Documentation/verify-sig.rst` line 254 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI0Z0-0WKcdMbwWrYB:-NxI94ZU78dONVCCV-Tw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/verify-sig.rst#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`% %` -> `%`
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1cLJ11bEZ4gluM-e:-NxIBNweAJ5d5FF-IjHB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`siging` -> `signing`
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 89 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1iPPB12Sw9_dwQgG:-NxIAtCS-ky85Y-W1ibc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`you key` -> `your key`
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 94 at r3](https://reviewable.io/reviews/gramineproject/gramine/1788#-NxI1qVzAI1zdbROCLSP:-NxIAt_k2H9HIlKHxrx1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7057718458afacabbedfeb4538a044f2df89ee1f/Documentation/devel/maintainer-manual.rst#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`singing` -> `signing`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 06:33 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3lfF3DAO9yebqQdoi:-NxLtZSE3t74R4GEEXP6:b191ewb) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Adding separate versions is not needed anymore, since we build all PRs: https://gramine--1788.org.readthedocs.build/en/1788/ (you can substitute any valid number of a PR).

Webhook works, just reporting the status doesn't.
</blockquote></details>

Ah, awesome.

___


<!-- Sent from Reviewable.io -->

2024-05-19 17:48 UTC, mkow requested changes
> Reviewed 8 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 10 unresolved discussions (waiting on @woju)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFvmwn68mugbJh_0Kp):*
TODO for myself: verify commit split before the rebase.
___
*[`Documentation/index.rst` line 218 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyG18Ba1Y-INVvnfkSd:-NyG18Ba1Y-INVvnfkSe:b-q7v6aw) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/index.rst#L218)):*
> ```reStructuredText
>    devel/onboarding
>    devel/setup
>    devel/maintainer-manual
> ```

I'd push this down on the list, it's important only to very few people and will be read much less often than the other entries here.
___
*[`Documentation/verify-sig.rst` line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGJDEU7Is31enVqfcu:-NyGJDEV6_YxeOi1KLg_:b45h) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/verify-sig.rst#L58)):*
> ```reStructuredText
> 
> Then check the key fingerprint. If you're sure the key is correct, you need to
> mark it as trusted.
> ```





_Suggestion:_
```reStructuredText
Then check the key fingerprint. After ensuring the key is correct, you can
mark it as trusted.
```
___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-NyFxNUv7mBrodbfDlm6:blxfmhh) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
> ```reStructuredText
> Maintainer's manual
> ```

I think this is rather a "Release maintainer's manual"?
___
*[`Documentation/devel/maintainer-manual.rst` line 35 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGjIIq4APLxDNbTgtC:-NyGjIIq4APLxDNbTgtD:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L35)):*
> ```reStructuredText
>     - [ ] publish on #community (@<owner>)
> 
> Create PR
> ```





_Suggestion:_
```reStructuredText
Create a PR
```
___
*[`Documentation/devel/maintainer-manual.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGk31SDkZ_6Q7GF7aa:-NyGk1fP4ylt3ddCa_qA:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L47)):*
> ```reStructuredText
> Then set the PR on reviewable.io to be reviewed commit-by-commit.
> 
> Update version in PR
> ```





_Suggestion:_
```reStructuredText
Update version in the PR
```
___
*[`Documentation/devel/maintainer-manual.rst` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGnWH1-EtOWBkcxFoa:-NyGnWH1-EtOWBkcxFob:brzm8ff) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L74)):*
The meaning of it depends on the project, quoting git docs:

> The meaning of a signoff depends on the project to which you’re committing.

I'd also change the last sentence here accordingly.



_Suggestion:_
```reStructuredText
    “Signing off” is a |~| legal device for a |~| sort of signature by which you
    usually assert that you are holding copyrights to the code you're submitting (or
```
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-NyGtgH4AiW2366SNbLK:btzwoe4) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
> ```reStructuredText
> First, you need to generate your own key pair using :program:`gpg`. The key
> needs to be "sign only"! Otherwise, if you also add encrypt capability, people
> will add your key to their :abbr:`MUA (Mail User Agent)`\ s and will encrypt
> ```

I think this term is much more popular nowadays and thus doesn't need an explanation.



_Suggestion:_
```reStructuredText
email clients
```
___
*[`Documentation/devel/maintainer-manual.rst` line 192 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGw3vn-eNdSBZk8wwS:-NyGw3vn-eNdSBZk8wwT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L192)):*
> ```reStructuredText
>     git config --global gpg.program qubes-gpg-client-wrapper
> 
> and remember to set ``QUBES_GPG_DOMAIN`` envrionment variable in your shell
> ```





_Suggestion:_
```reStructuredText
environment
```
___
*[`scripts/release.sh` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mmqGCRzxJbJZHIJO:-NyGwI3_1j3nzZPomraf:bj29145) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/scripts/release.sh#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK about header, I found it somewhere, maybe we should use it project wide? For now I've reverted to the version without header for consistency.

About copyright, I think this script might have been done on scaffolding time this year. Probably not Intel.
</blockquote></details>

Then it should be ITL?


<!-- Sent from Reviewable.io -->

2024-05-23 11:42 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 7 of 10 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[`Documentation/index.rst` line 218 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyG18Ba1Y-INVvnfkSd:-NyKZgRV9uBZurC3vb1N:b9njpm5) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/index.rst#L218)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd push this down on the list, it's important only to very few people and will be read much less often than the other entries here.
</blockquote></details>

Hmm, right, it certainly should be below `coding-style`. I moved it to the bottom of technical ones, leaving only legal stuff below.
___
*[`Documentation/verify-sig.rst` line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGJDEU7Is31enVqfcu:-Ny_F6VNALTba67PyR5V:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/verify-sig.rst#L58)):*
> ```reStructuredText
> 
> Then check the key fingerprint. If you're sure the key is correct, you need to
> mark it as trusted.
> ```

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-NyKXXrACyZhwOiWR76v:bp80m6e) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this is rather a "Release maintainer's manual"?
</blockquote></details>

No, it also describes code signing which I hope will be used by all maintainers (maybe even all contributors), not just me. Also we don't have a position of "release maintainer" or "release manager", all maintainers can (eventually should be able to) do a release (i.e. sign a tag).

If you want it to be release manual, I can move the section about generating keys and configuring git to `devel/setup.rst` (right now it's only about configuring vim).
___
*[`Documentation/devel/maintainer-manual.rst` line 35 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGjIIq4APLxDNbTgtC:-NyKwvkHELtyMsj5ZLFq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L35)):*
> ```reStructuredText
>     - [ ] publish on #community (@<owner>)
> 
> Create PR
> ```

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGk31SDkZ_6Q7GF7aa:-NyKwleR-sbxRxyz8PQn:b-xjhnua) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L47)):*
> ```reStructuredText
> Then set the PR on reviewable.io to be reviewed commit-by-commit.
> 
> Update version in PR
> ```

Done.

(I also rewrote next heading to "Create a tag" to match all previous headings).
___
*[`Documentation/devel/maintainer-manual.rst` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGnWH1-EtOWBkcxFoa:-NyKXvCC45MCuvvhEzEQ:b-8bnk4e) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The meaning of it depends on the project, quoting git docs:

> The meaning of a signoff depends on the project to which you’re committing.

I'd also change the last sentence here accordingly.
</blockquote></details>

I think it should be as written, I describe what signing off means in our project. I can add "(in our project)" in some strategic place, or add a sentence in parens like >(In other projects "singing off" might have slightly different meaning, check the details with the respective project every time.)
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-NyKYUeb3hmYnBFTiBg2:bpsnghs) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this term is much more popular nowadays and thus doesn't need an explanation.
</blockquote></details>

There are different "email clients" doing different stuff, so I wanted to optimise the phraseology for precison. This is manual for maintainers, there's no need to dumb it down.
___
*[`Documentation/devel/maintainer-manual.rst` line 192 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGw3vn-eNdSBZk8wwS:-NyKwi8kE6G0GDKkg0mM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L192)):*
> ```reStructuredText
>     git config --global gpg.program qubes-gpg-client-wrapper
> 
> and remember to set ``QUBES_GPG_DOMAIN`` envrionment variable in your shell
> ```

Done.
___
*[`scripts/release.sh` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mmqGCRzxJbJZHIJO:-NyKZEv87Ssh2S-ILBhs:b8kdhf9) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/scripts/release.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then it should be ITL?
</blockquote></details>

No, in ITL we don't reassign copyrights (see Qubes repos).


<!-- Sent from Reviewable.io -->

2024-05-23 12:11 UTC, mkow requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-Ny_JxOoBR6zObGW7MQu:b-s817uz) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
> No, it also describes code signing which I hope will be used by all maintainers

I agree with that, but this document is more specific, and the title should describe its contents well - "Maintainer's manual" sounds like a very broad document about everything relating to maintaining Gramine. And at the same time, when looking at ToC you won't easily find where exactly packaging/releasing procedures are described.

So - describe the contents, not the intended reader group.
___
*[`Documentation/devel/maintainer-manual.rst` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGnWH1-EtOWBkcxFoa:-Ny_L2fVDNWVe7JbR8Sw:b-t2e9ql) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L74)):*
> I describe what signing off means in our project

That's my problem with the current version, nowhere it says that it's only about how it works in our project. Currently it sounds to me like a generic explanation of this git feature: "“Signing off” is a legal device [...] by which you assert that you are holding copyrights".

> I can add "(in our project)" in some strategic place, or add a sentence in parens like >(In other projects "singing off" might have slightly different meaning, check the details with the respective project every time.)

+1, both do the work IMO
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-Ny_Ljs7DW3ZIQLXc-9Y:b-1xi1wh) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There are different "email clients" doing different stuff, so I wanted to optimise the phraseology for precison. This is manual for maintainers, there's no need to dumb it down.
</blockquote></details>

Maybe I'm missing something, but what's the difference between MUA and email client?


<!-- Sent from Reviewable.io -->

2024-05-23 16:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 9 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-Ny_nScv05DsNnHtI0JH:bnqyps8) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> No, it also describes code signing which I hope will be used by all maintainers

I agree with that, but this document is more specific, and the title should describe its contents well - "Maintainer's manual" sounds like a very broad document about everything relating to maintaining Gramine. And at the same time, when looking at ToC you won't easily find where exactly packaging/releasing procedures are described.

So - describe the contents, not the intended reader group.
</blockquote></details>

"Code signing and release manual"? Because those 2 topics are very different, they're connected just by the fact they're intended for maintainers, so I don't thing "Maintainer's manual" is wrong.

Or I can split those in 2 documents, 'devel/release.rst` and put keygen into `devel/setup.rst`.
___
*[`Documentation/devel/maintainer-manual.rst` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGnWH1-EtOWBkcxFoa:-Ny_wGYZBYa9EgLf2jcD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I describe what signing off means in our project

That's my problem with the current version, nowhere it says that it's only about how it works in our project. Currently it sounds to me like a generic explanation of this git feature: "“Signing off” is a legal device [...] by which you assert that you are holding copyrights".

> I can add "(in our project)" in some strategic place, or add a sentence in parens like >(In other projects "singing off" might have slightly different meaning, check the details with the respective project every time.)

+1, both do the work IMO
</blockquote></details>

Done.
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-Ny_q3MmAIWeIH-9o-tb:bjqqfyl) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe I'm missing something, but what's the difference between MUA and email client?
</blockquote></details>

There are several kinds of email software that technically are clients (in the "client-server architecture" sense): MTA (Mail Transport Agent) is also a client of SMTP protocol, but it performs different role: forwards email to "server", which may be another MTA or MDA (... Delivery Agent). There are MRAs (... Retrieval Agents), which download email from MDAs, but can't show it to people, so they're closer to MTA, just with reversed polarity (they're clients of IMAP and POP3 protocols instead of SMTP). Email packages typically package several of those roles into one more or less integrated solution (Thunderbird is MUA+MRA+limited MTA capabilities, Postfix is MSA+MTA+limited MDA, and so on). For this reason email people don't like to use unqualified "client" (or "server"), because it's immediately met with "yeah, which client?".

https://en.wikipedia.org/wiki/Email_agent_(infrastructure),
https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Mail_processing_model, and diagram in https://en.wikipedia.org/wiki/Message_delivery_agent


<!-- Sent from Reviewable.io -->

2024-05-23 23:08 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-NybeM-E8VHMTPiw9cxa:b-rm1glh) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
> "Code signing and release manual"

Sounds good to me. We use code signing _only_ for the release tags, so it's not a bad idea to be placed in the very same document.
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-Nybf9YKEpAQr0hLgXF5:b-2xn8lc) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There are several kinds of email software that technically are clients (in the "client-server architecture" sense): MTA (Mail Transport Agent) is also a client of SMTP protocol, but it performs different role: forwards email to "server", which may be another MTA or MDA (... Delivery Agent). There are MRAs (... Retrieval Agents), which download email from MDAs, but can't show it to people, so they're closer to MTA, just with reversed polarity (they're clients of IMAP and POP3 protocols instead of SMTP). Email packages typically package several of those roles into one more or less integrated solution (Thunderbird is MUA+MRA+limited MTA capabilities, Postfix is MSA+MTA+limited MDA, and so on). For this reason email people don't like to use unqualified "client" (or "server"), because it's immediately met with "yeah, which client?".

https://en.wikipedia.org/wiki/Email_agent_(infrastructure),
https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Mail_processing_model, and diagram in https://en.wikipedia.org/wiki/Message_delivery_agent
</blockquote></details>

This differentiation seem to be super specific to email client developers. Also, even the links you pasted seem to say that "(e)mail client" == "MUA":
- https://en.wikipedia.org/wiki/Email_client:
  > "An **email client**, **email reader** or, more formally, **message user agent** (MUA)"
- https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Mail_processing_model
  > [...] a mail client ([mail user agent](https://en.wikipedia.org/wiki/Mail_user_agent "Mail user agent"), MUA)

I think "MUA" is a rather confusing and not a well-known term, while "email client" is clear and doesn't require any additional explanations to be understood.

@kailun-qin, @dimakuv: any preferences?


<!-- Sent from Reviewable.io -->

2024-06-03 07:19 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 4 unresolved discussions (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-NzRwwXLEop2OjoS2abt:bvim9f6) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> "Code signing and release manual"

Sounds good to me. We use code signing _only_ for the release tags, so it's not a bad idea to be placed in the very same document.
</blockquote></details>

I also like a long name "Code signing and release manual"
___
*[`Documentation/devel/maintainer-manual.rst` line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyGtgH37yV0jFjX-xim:-NzRxN-k57Z-hFAtwMfl:b-xxhfgy) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This differentiation seem to be super specific to email client developers. Also, even the links you pasted seem to say that "(e)mail client" == "MUA":
- https://en.wikipedia.org/wiki/Email_client:
  > "An **email client**, **email reader** or, more formally, **message user agent** (MUA)"
- https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Mail_processing_model
  > [...] a mail client ([mail user agent](https://en.wikipedia.org/wiki/Mail_user_agent "Mail user agent"), MUA)

I think "MUA" is a rather confusing and not a well-known term, while "email client" is clear and doesn't require any additional explanations to be understood.

@kailun-qin, @dimakuv: any preferences?
</blockquote></details>

I am fine with MUA. For example, I periodically use Mutt as a MUA (i.e., not for receiving/sending emails, but purely for constructing them), so I'm aware of the terminology and it doesn't put me off.


<!-- Sent from Reviewable.io -->

2024-06-04 21:10 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 8 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @mkow)

___
*[`Documentation/devel/maintainer-manual.rst` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFxNUu7a1x-wgdh_4K:-Nz_4Co98YIpEB4fDnxy:bmuuko0) ([raw file](https://github.com/gramineproject/gramine/blob/24651ad1280ed658f5a5bf463f36297d57b2e703/Documentation/devel/maintainer-manual.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also like a long name "Code signing and release manual"
</blockquote></details>

Done, and swapped code signing and release to match title, and because code signing will potentially be useful to more people.


<!-- Sent from Reviewable.io -->

2024-06-05 16:04 UTC, mkow reviewed
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFvmwn68mugbJh_0Kp):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: verify commit split before the rebase.
</blockquote></details>

s/before/after/


<!-- Sent from Reviewable.io -->

2024-06-05 16:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 3 files at r5, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-06-06 02:25 UTC, kailun-qin requested changes
> Reviewed 7 of 10 files at r3, 1 of 3 files at r5, 1 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 6 unresolved discussions (waiting on @mkow and @woju)

___
*[`Documentation/verify-sig.rst` line 63 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfL2yzBRtspneL7IzN:-NzfL2yzBRtspneL7IzO:bfmo78d) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L63)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> If you don't have you own PGP key pair, you can mark the key as ultimately
> ```

-> your



_Code quote:_
```reStructuredText
you
```
___
*[`Documentation/verify-sig.rst` line 123 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLWTODrkY-5lR5s40:-NzfLWTODrkY-5lR5s41:b-syxxkn) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L123)):*
> ```reStructuredText
>     This is free software: you are free to change and redistribute it.
>     There is NO WARRANTY, to the extent permitted by law.
>     
> ```

What are these spaces in this file?



_Code quote:_
```reStructuredText
···
```
___
*[`Documentation/verify-sig.rst` line 232 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLx_075rA4QPUmAye:-NzfLx_075rA4QPUmAyf:b-cvfw7o) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L232)):*
> ```reStructuredText
>     Primary key fingerprint: 9C4D 27D9 157E F771 A428  3926 044D 9664 E7A7 7E16
> 
> Which is **NOT a successful verification**, because the key might be
> ```

-> must?



_Code quote:_
```reStructuredText
might
```
___
*[`Documentation/devel/code-signing-and-releasing.rst` line 41 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfJBYq-8Gv86lWUsAc:-NzfJBYr8x2mGteZC3Uw:bmmis9m) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/devel/code-signing-and-releasing.rst#L41)):*
> ```reStructuredText
> code signing in this project.
> 
> The key needs to be RSA (at least 3072 to match overall security level in SGX)
> ```

Maybe "the key needs to offer a security strength of 128 bits"? ("the key needs to be RSA or Curve25519" reads a bit weird to me, RSA is the algo and Curve25519 is actually the curve)



_Code quote:_
```reStructuredText
The key needs to be RSA (at least 3072 to match overall security level in SGX)
```


<!-- Sent from Reviewable.io -->

2024-06-06 15:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 10 of 11 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/verify-sig.rst` line 63 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfL2yzBRtspneL7IzN:-Nzi5R1HCOtwfta3ccsC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L63)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> your
</blockquote></details>

Done.
___
*[`Documentation/verify-sig.rst` line 123 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLWTODrkY-5lR5s40:-Nzi5SNlDCnvFvhPxCm4:b-8yzx1m) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L123)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What are these spaces in this file?
</blockquote></details>

They are part of the indentation of the whole listing, are done when I indent all (so that every line of the listing can just be dedented by 4 spaces, no exceptions). RST actually does not make them mandatory (in contrast to some other markups), so I can remove them if you want.
___
*[`Documentation/verify-sig.rst` line 232 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLx_075rA4QPUmAye:-Nzi4dwuDAuQzs4U0K7J:b-6alnff) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L232)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> must?
</blockquote></details>

No, as exemplified by the listing: this is actually the correct public key (see fingerprint), but without signature and without trust bit. So it may or may not be different, the `gpg` tool just isn't sure.
___
*[`Documentation/devel/code-signing-and-releasing.rst` line 41 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfJBYq-8Gv86lWUsAc:-Nzi4DaiECf5_7RhWd2d:b-y5uhgd) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/devel/code-signing-and-releasing.rst#L41)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Maybe "the key needs to offer a security strength of 128 bits"? ("the key needs to be RSA or Curve25519" reads a bit weird to me, RSA is the algo and Curve25519 is actually the curve)
</blockquote></details>

I don't want to explain what is strength as expressed in bits and how to recalculate RSA's bit length to that theoretical strength. Recommendation of 3072 bits in RSA is mostly arbitrary and an appeal to authority, because again, I don't want to discuss bit lengths, so I defer to SGX strength (the underlying threat model is that the target is still user's data, but now the attacker wants to subvert the supply chain by forging signatures, so the signature does not need to be stronger than 3072, otherwise attacker will just attack the signature in SIGSTRUCT).

"Curve25519" specifies not only the curve, but also the field and base point, and implementations take advantage of mathematical properties that are not generally available for other curves, so it's closer to "algorithm" than to just bit length. The algorithm is "EdDSA", and the actual curve is "Ed25519", which is mathematically equivalent to Curve25519, but technically not the same (https://en.wikipedia.org/wiki/EdDSA#Ed25519). Again, I don't want to explain all of that.

"RSA" and "Curve25519" are choices available in the `--full-gen-key` menu (the menu item is with space, but most people talk about that scheme without space, https://en.wikipedia.org/wiki/Curve25519, and I think it's close enough). Notice the wording in GPG questionnaire that is technically correct: first "ECC", which is correct, this is elliptic key, and then the question "[...] which elliptic curve" is answered by "Curve25519", which is mathematically equivalent to the actual Ed25519 curve. I think they did that because of "ECC and ECC" option (sign and encrypt), where there are actually two curves, but closely related. This can be compared to RSA option, which also does not permit to generate sign and encrypt keypairs with different lengths.

So IDK, I probably can reword to say "RSA (at least 3072 bit [...]) or an elliptic key on Curve25519.", but I don't want to mention 128 bit strength, nor further mention "Edwards" or "Ed25519" or something like that, because developers who are not cryptographers might start looking for that option in the menu and won't find them. This is not a crypto handbook.


<!-- Sent from Reviewable.io -->

2024-06-07 01:45 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`Documentation/verify-sig.rst` line 123 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLWTODrkY-5lR5s40:-NzkDs2u1_JRHxIJ5gB_:bcaqqvf) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L123)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

They are part of the indentation of the whole listing, are done when I indent all (so that every line of the listing can just be dedented by 4 spaces, no exceptions). RST actually does not make them mandatory (in contrast to some other markups), so I can remove them if you want.
</blockquote></details>

Yeah, I prefer removing them, also some other trailing spaces (e.g., after `usage: SC` below)
___
*[`Documentation/verify-sig.rst` line 232 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLx_075rA4QPUmAye:-NzkDZW85XoGrSGInU-m:byl52tx) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L232)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, as exemplified by the listing: this is actually the correct public key (see fingerprint), but without signature and without trust bit. So it may or may not be different, the `gpg` tool just isn't sure.
</blockquote></details>

Right, I misread. Thanks for the explanation.
___
*[`Documentation/devel/code-signing-and-releasing.rst` line 41 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfJBYq-8Gv86lWUsAc:-NzkEP7NCvlvgQAKRmf3:bl09eds) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/devel/code-signing-and-releasing.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

or maybe "elliptic Ed25519 key (called Curve25519 in GPG)"? not sure at this point
</blockquote></details>

I see, let's not involve strength and other details then -- let's keep the wording as is.


<!-- Sent from Reviewable.io -->

2024-06-07 09:50 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/verify-sig.rst` line 123 at r8](https://reviewable.io/reviews/gramineproject/gramine/1788#-NzfLWTODrkY-5lR5s40:-Nzm5dcJDGJTSJvyARwf:bu11ahc) ([raw file](https://github.com/gramineproject/gramine/blob/a9bb55f9410df909f1e8bbfa6173355c9ba96805/Documentation/verify-sig.rst#L123)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yeah, I prefer removing them, also some other trailing spaces (e.g., after `usage: SC` below)
</blockquote></details>

Done. I hope no-one will be pasting this into `expect` scripts.


<!-- Sent from Reviewable.io -->

2024-06-07 09:53 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2024-06-08 00:52 UTC, mkow reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-06-12 07:32 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`Documentation/devel/code-signing-and-releasing.rst` line 142 at r10](https://reviewable.io/reviews/gramineproject/gramine/1788#-O-ALuYH4TWAS50FvDl3:-O-ALuYH4TWAS50FvDl4:buf6lcd) ([raw file](https://github.com/gramineproject/gramine/blob/9e07c54d0a3a608156210799ac9315b89df4993b/Documentation/devel/code-signing-and-releasing.rst#L142)):*
> ```reStructuredText
> Create new checklist issue (fill all ``<variable>`` before submitting):
> 
> .. new-issue:: Release <version> checklist
> ```

can we add "update docker image" to the checklist (so that we won't forget about that)?


<!-- Sent from Reviewable.io -->

2024-06-12 07:33 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/devel/code-signing-and-releasing.rst` line 142 at r10](https://reviewable.io/reviews/gramineproject/gramine/1788#-O-ALuYH4TWAS50FvDl3:-O-AMW2yAGcQMFngzljp:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/9e07c54d0a3a608156210799ac9315b89df4993b/Documentation/devel/code-signing-and-releasing.rst#L142)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

can we add "update docker image" to the checklist (so that we won't forget about that)?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-06-12 10:13 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 9 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/devel/code-signing-and-releasing.rst` line 142 at r10](https://reviewable.io/reviews/gramineproject/gramine/1788#-O-ALuYH4TWAS50FvDl3:-O-AvoAd-9K2vfQ5PFNx:b1csaea) ([raw file](https://github.com/gramineproject/gramine/blob/9e07c54d0a3a608156210799ac9315b89df4993b/Documentation/devel/code-signing-and-releasing.rst#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. Took liberty to add a pattern for release notes and an item there to mention distro in docker image.


<!-- Sent from Reviewable.io -->

2024-06-12 10:17 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 3 unresolved discussions (waiting on @kailun-qin, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2024-06-12 10:29 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2024-06-16 23:34 UTC, mkow reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)



<!-- Sent from Reviewable.io -->

2025-06-03 22:44 UTC, kailun-qin submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/1788#-NyFvmwn68mugbJh_0Kp:-ORrx0fDBBviByNzPCwO:be9bp3):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

s/before/after/
</blockquote></details>

Is this the only blocking comment? I think the manual is quite helpful for future releases -- can we move it forward?


<!-- Sent from Reviewable.io -->

2025-06-06 05:24 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: 6 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`scripts/release.sh` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/1788#-Ns3mmqGCRzxJbJZHIJO:-OS2fko4BtARXHv0WNzI:b2j1iw) ([raw file](https://github.com/gramineproject/gramine/blob/06a6df1aa2cd641408e818847f30b1d42fe77d94/scripts/release.sh#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, in ITL we don't reassign copyrights (see Qubes repos).
</blockquote></details>

I've removed this script, because it's dependent on distro versions, and it's applicable also to other repos (scaffolding and contrib). I'll maintain it out of tree.


<!-- Sent from Reviewable.io -->

2025-06-06 12:56 UTC, mkow requested changes
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-OS4Isp0Ett9X_GCySSz:-OS4Isp0Ett9X_GCyST-:bjcr2lu) (no related file):*
Why is `keys/RPM-GPG-KEY-gramine-2021` ascii-armored, but `keys/RPM-GPG-KEY-gramine-2024` (and others) binary?


<!-- Sent from Reviewable.io -->

2025-06-10 21:58 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1788#-OS4Isp0Ett9X_GCySSz:-OSQq8fn4po7u6dUUFSs:bc8ozd2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is `keys/RPM-GPG-KEY-gramine-2021` ascii-armored, but `keys/RPM-GPG-KEY-gramine-2024` (and others) binary?
</blockquote></details>

Because that's how I published them on https://packages.gramineproject.io/, and I think think much about it at the time. They're identical files. I can armour them only in repo and then get to answer questions "why those files are different", or armour both here and at packages.g.i and then answer questions why the key changed.


<!-- Sent from Reviewable.io -->

2025-06-10 23:35 UTC, merged