Some ASAN fixes
gramineproject/gramine pull request #18
Opened 2021-09-09 17:32 UTC by pwmarcz

## Description of the changes 

I'm working on AddressSanitizer integration (see https://github.com/gramineproject/graphene/issues/2106) and it already detected a few bugs. I haven't checked Linux-SGX yet, only Linux.

(Short status summary for this work: I think writing custom hooks is still the way to go, not trying to adapt LLVM's library. The main challenge is getting the **stack** part to work: I will probably submit the first version without it, but it's very powerful: it detects use-after-return, use-after-scope, stack buffer overflows and such. Right now I'm struggling to properly cleanup (unpoison) the stack on thread exit).

## How to test this PR? 

The tests should pass.

2021-09-09 18:24 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[common/include/list.h, line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/18#-MjAn6O94dbx3H5alWvD:-MjAn6O94dbx3H5alWvE:bfbl80e) ([raw file](https://github.com/gramineproject/gramine/blob/66d56c2455a3f297efc10b0834ab67160c0df8e9/common/include/list.h#L276)):*
> ```objc
>          /* Handle the case where the first element was removed. */                                \
>          first_iter = first_iter && (TMP) != (CURSOR) && (HEAD)->first == (TMP),                   \
>              ((TMP) != (CURSOR) && ((CURSOR) = (TMP), (TMP) = (TMP)->FIELD.next)))
> ```

I admit that I failed to parse this whole obfuscated macro, maybe someone else will be able to understand what's happening here and review it...


<!-- Sent from Reviewable.io -->

2021-09-09 18:45 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux/db_sockets.c, line 834 at r2](https://reviewable.io/reviews/gramineproject/gramine/18#-MjAeOGBDFJ0oDbwIpC8:-MjAeOGCCV9nn5ZzxEON:bfehrjd) ([raw file](https://github.com/gramineproject/gramine/blob/9c408d137b67f4195751e770998cb5bdcfceae5b/Pal/src/host/Linux/db_sockets.c#L834)):*
> ```C
> 
>     char* addrbuf = __alloca(addrlen + 1);
>     memcpy(addrbuf, addr, addrlen + 1);
> ```

Now you access `addr` out of bounds (> len).


<!-- Sent from Reviewable.io -->

2021-09-09 19:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_sockets.c, line 834 at r2](https://reviewable.io/reviews/gramineproject/gramine/18#-MjAeOGBDFJ0oDbwIpC8:-MjAz96ME-JtJ-kHO8sd:b5n6yz9) ([raw file](https://github.com/gramineproject/gramine/blob/9c408d137b67f4195751e770998cb5bdcfceae5b/Pal/src/host/Linux/db_sockets.c#L834)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now you access `addr` out of bounds (> len).
</blockquote></details>

I think it's fine, this is an old API which receives length, not buffer size. So, the nullbyte is implicit.


<!-- Sent from Reviewable.io -->

2021-09-10 08:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-09-10 09:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: 1 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/host/Linux/db_sockets.c, line 834 at r2](https://reviewable.io/reviews/gramineproject/gramine/18#-MjAeOGBDFJ0oDbwIpC8:-MjE2VLJA1JqiYXRpXEW:b-310y85) ([raw file](https://github.com/gramineproject/gramine/blob/9c408d137b67f4195751e770998cb5bdcfceae5b/Pal/src/host/Linux/db_sockets.c#L834)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it's fine, this is an old API which receives length, not buffer size. So, the nullbyte is implicit.
</blockquote></details>

But I can be explicit about it and add the null byte manually.

Also, I just realized this same code is duplicated in Linux-SGX :( I modified it in there as well (and rebased to edit the commit message).


<!-- Sent from Reviewable.io -->

2021-09-10 11:25 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-09-10 12:07 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-09-10 12:50 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/18)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-10 12:51 UTC, merged