WIP [LibOS] Move trusted and allowed files logic to LibOS
gramineproject/gramine pull request #1812
Opened 2024-03-14 12:30 UTC by dimakuv

## Description of the changes 

This is a draft that has all code that I wrote while working on the main target: moving trusted and allowed files logic from Linux-SGX PAL to LibOS. There are several unrelated changes that I detected while working on the main target; they will be separated into separate PR.

I'm submitting this commit as a draft PR just to have a back up and a convenient way to extract sub-PRs out of this huge pile of code.

TODOs:
- [ ] Introduce a new manifest option with SHA256 hash of the LibOS executable, so that Linux-SGX PAL reads this one instead of `sgx.trusted_files`. Then the LibOS hash can be removed from `sgx.trusted_files` completely as LibOS itself doesn't need it.
- [ ] REMOVE ALL LINUX-SGX PAL CODE FOR TRUSTED/ALLOWED FILES + FILE_CHECK_POLICY [EVIL LAUGH]!

## How to test this PR? 

All current tests must pass. Should be enough of testing.

2024-03-14 15:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "WIP" found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxHo6k0ufqztjjZmJU:-NsxHo6k0ufqztjjZmJV:bs1k2ed) (no related file):*
One more TODO:
- [x] Remove `PAL_OPTION_PASSTHROUGH`, it becomes redundant.

___
___
*[`libos/src/libos_init.c` line 401 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-Nsx10fnCrs5BKWhMImD:-Nsx10fnCrs5BKWhMImE:b-wz0mbv) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/libos/src/libos_init.c#L401)):*
> ```C
> 
>     RUN_INIT(init_vma);
>     RUN_INIT(init_r_debug);
> ```

This is an independent fix. Submitted as a separate PR: https://github.com/gramineproject/gramine/pull/1814
___
*[`libos/src/bookkeep/libos_vma.c` line 1498 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxXvgUBwNZKlhXRWzB:-NsxXvgUBwNZKlhXRWzC:b-1swwju) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/libos/src/bookkeep/libos_vma.c#L1498)):*
> ```C
> }
> 
> static bool vma_filter_needs_prot_refresh(struct libos_vma* vma, void* arg) {
> ```

This code (among a lot of other code) is extracted into this PR: https://github.com/gramineproject/gramine/pull/1818
___
*[`libos/src/fs/shm/fs.c` line 168 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-Nsx333cC77jX5m9BWoC:-Nsx333cC77jX5m9BWoD:b-8cppj7) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/libos/src/fs/shm/fs.c#L168)):*
> ```C
> }
> 
> static int shm_unlink(struct libos_dentry* dent) {
> ```

This is an unrelated change (well, slightly related because with this PR, `shm` filesystem definitely cannot reuse `chroot_unlink()` as the latter uses `chroot_temp_open()` which checks for trusted/allowed files).

Create a separate PR for this: https://github.com/gramineproject/gramine/pull/1815
___
*[`libos/test/ltp/manifest.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxJnuc2AEJnBCoPXgp:-NsxJnuc2AEJnBCoPXgq:b-59ppv0) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/libos/test/ltp/manifest.template#L20)):*
> ```
> 
>   # many LTP multi-process tests rely on shared-memory IPC via `mmap(MAP_SHARED, </dev/shm fd>)`
>   { type = "untrusted_shm", path = "/dev/shm", uri = "dev:/dev/shm" },
> ```

This particular change is extracted into PR: 
___
*[`libos/test/regression/test_libos.py` line 872 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-Nsx_r950cRr-qFgIKr7:-Nsx_r950cRr-qFgIKr8:bsdsy8k) ([raw file](https://github.com/gramineproject/gramine/blob/d82e885cb4adbcec876c78a0f745559cdb26aee4/libos/test/regression/test_libos.py#L872)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
>     @unittest.skip('sigaltstack isn\'t correctly implemented')
> ```

This re-enabling of the `sigaltstack` test was extracted into this PR: https://github.com/gramineproject/gramine/pull/1819


<!-- Sent from Reviewable.io -->

2024-03-15 08:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 45 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "WIP" found in commit messages' one-liners

___
*[`libos/test/regression/test_libos.py` line 872 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-Nsx_r950cRr-qFgIKr7:-Nt0Jlc5918ZWgXJ-uNb:b-7ba67w) ([raw file](https://github.com/gramineproject/gramine/blob/d82e885cb4adbcec876c78a0f745559cdb26aee4/libos/test/regression/test_libos.py#L872)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This re-enabling of the `sigaltstack` test was extracted into this PR: https://github.com/gramineproject/gramine/pull/1819
</blockquote></details>

Update: I removed this change from here, since something is broken on EDMM. Let's deal with that in the separate PR, here I'm reverting `sigaltstack` test to be skipped again.


<!-- Sent from Reviewable.io -->

2024-03-15 08:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 45 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "WIP" found in commit messages' one-liners

___
*[`pal/include/pal_internal.h` line 296 at r2](https://reviewable.io/reviews/gramineproject/gramine/1812#-Nt0K7KiCWm_UNDEJ-4v:-Nt0K7KiCWm_UNDEJ-4w:b-5araru) ([raw file](https://github.com/gramineproject/gramine/blob/3fcc9a8885f66766f28b78c74991c9c6bd9656a4/pal/include/pal_internal.h#L296)):*
> ```objc
> int _PalDebugLog(const void* buf, size_t size);
> 
> int _PalValidateEntrypoint(const void* buf, size_t size);
> ```

This is extracted into separate PR: #1820 


<!-- Sent from Reviewable.io -->

2024-07-30 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 58 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`CI-Examples/blender/Makefile` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1812#-O31evmC1f_2i9j5aMo3:-O31evmC1f_2i9j5aMo4:b-vf0a17) ([raw file](https://github.com/gramineproject/gramine/blob/eda2feaf0356870ba1e27b5bfaaabe55ceb6142e/CI-Examples/blender/Makefile#L44)):*
> ```Makefile
> 	mkdir -p $@
> 
> blender.manifest: blender.manifest.template $(BLENDER_DIR)/blender | $(RUN_DIR)
> ```

A side effect I didn't realize before: the build instructions for applications must be modified such that *all files* must already exist for the `.manifest` generation.

The same must be applied in the Examples repo, so I'll create the PR there and block on this.


<!-- Sent from Reviewable.io -->

2024-07-30 08:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 58 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`CI-Examples/blender/Makefile` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1812#-O31evmC1f_2i9j5aMo3:-O31kCGH1-OaP5AA4M4f:brq3sxj) ([raw file](https://github.com/gramineproject/gramine/blob/eda2feaf0356870ba1e27b5bfaaabe55ceb6142e/CI-Examples/blender/Makefile#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A side effect I didn't realize before: the build instructions for applications must be modified such that *all files* must already exist for the `.manifest` generation.

The same must be applied in the Examples repo, so I'll create the PR there and block on this.
</blockquote></details>

https://github.com/gramineproject/examples/pull/105 -- done here. I'll keep this comment blocking.


<!-- Sent from Reviewable.io -->

2024-07-30 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 0 of 58 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`libos/test/regression/fork_and_access_file.gdb` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1812#-O31kzsUC-3Ubkx8Q_Ub:-O31kzsVC57u3guxqQJW:bxbvtl0) ([raw file](https://github.com/gramineproject/gramine/blob/eda2feaf0356870ba1e27b5bfaaabe55ceb6142e/libos/test/regression/fork_and_access_file.gdb#L17)):*
> ```GDB
>   shell echo "WRITING NEW CONTENT IN FORK_AND_ACCESS_FILE_TESTFILE" > fork_and_access_file_testfile
> 
>   tbreak die_on_wrong_file_contents
> ```

This can be considered an independent change. This LibOS test previously relied on the Gramine's `die_or_inf_loop` function being called. However, this function is used only in SGX PAL (it makes sense to kill the SGX enclave immediately, but it seems to not make sense to kill the normal process in this way).

So I modified the LibOS test to not know/care about Gramine internals, and instead be self-contained.

This particular change can be split into a separate PR, if people want to.


<!-- Sent from Reviewable.io -->

2024-08-08 03:06 UTC, kailun-qin requested changes
> Reviewed 1 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 1 of 59 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O3jtFQ70nXJewEku_TD:b-op8bio) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that `gramine-direct` also works with Allowed and Trusted Files, we need to call this expansion function.

There is one side-effect: now both `.manifest` and `.manifest.sgx` files have exactly the same contents (previously they only differed in not-expanded vs expanded Trusted Files). This eats memory on the hard disk, so we could symlink `.manifest.sgx -> .manifest`. But on the other hand, users will most typically disregard `.manifest` file anyway and use only `.manifest.sgx`, so making the latter a symlink sounds wrong.
</blockquote></details>

It seems that we still allow `gramine-sgx-sign` to expand/hash files (if hashes not present), is this intended?
___
*[`python/gramine-manifest` line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3jlWO89R2gBhNPJaro:-O3jlWO89R2gBhNPJarp:bhib23b) ([raw file](https://github.com/gramineproject/gramine/blob/1a6511033fd41c76a07f048c1c5443f6541dfb9d/python/gramine-manifest#L35)):*
> ```
> @click.option('--chroot',
>     type=click.Path(exists=True, dir_okay=True, file_okay=False),
>     help='Measure a chroot directory, not the host filesystem')
> ```

What about https://github.com/gramineproject/gramine/blob/master/Documentation/manpages/gramine-manifest.rst?



_Code quote:_
```
@click.option('--chroot',
    type=click.Path(exists=True, dir_okay=True, file_okay=False),
    help='Measure a chroot directory, not the host filesystem')
```


<!-- Sent from Reviewable.io -->

2024-08-08 06:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 1 of 60 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O3kcqzEBvr_ape2f85b:b-nph3t) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It seems that we still allow `gramine-sgx-sign` to expand/hash files (if hashes not present), is this intended?
</blockquote></details>

Yes, this is intended. I saw no particular reason to remove that functionality from `gramine-sgx-sign`. Is there any particular concern about this?
___
*[`python/gramine-manifest` line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3jlWO89R2gBhNPJaro:-O3kdX7S0xBRpI6XYxH3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1a6511033fd41c76a07f048c1c5443f6541dfb9d/python/gramine-manifest#L35)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about https://github.com/gramineproject/gramine/blob/master/Documentation/manpages/gramine-manifest.rst?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-08 12:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 1 of 60 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3lzpHu07IIn1qIZgXC:-O3lzpHu07IIn1qIZgXD:b6pa3iw) (no related file):*
FYI: I squashed and rebased to the latest master, per request from @mkow and agreement from @kailun-qin 

___


<!-- Sent from Reviewable.io -->

2024-08-08 15:08 UTC, mkow requested changes
> Reviewed 21 of 35 files at r4, 10 of 14 files at r5, 1 of 1 files at r7, 1 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 33 of 60 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`CI-Examples/nginx/Makefile` line 56 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH6gf6IO-_6cA3Ztw:-O3mH6gf6IO-_6cA3Ztx:bne2i16) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/nginx/Makefile#L56)):*
> ```Makefile
> 		$(INSTALL_DIR)/conf/nginx-gramine.conf \
> 		$(TEST_DATA) nginx_args \
> 		$(INSTALL_DIR)/conf/server.crt
> ```

Please align with spaces, not tabs (it's not a recipe).
Also, I think it would look better if aligned to `:`?
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 80 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH21I3QWGdIL-7YUE:-O3mH21I3QWGdIL-7YUF:b-mq5h1e) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/ra-tls-secret-prov/Makefile#L80)):*
> ```Makefile
> #       should be relative to the manifest, not to current dir) - drop `cd` and `notdir`.
> secret_prov_minimal/client.manifest: secret_prov_minimal/client.manifest.template \
> 	                                 secret_prov_minimal/client
> ```

this should be aligned with spaces
___
*[`libos/test/ltp/ltp.cfg` line 252 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mNYRzBukttsI6YALG:-O3mNYRzBukttsI6YALH:bmze9pp) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/ltp.cfg#L252)):*
> ```INI
> # very long test, does thousands of forks
> [epoll01]
> timeout = 600
> ```

That's suspicious, why is this needed?
___
*[`libos/test/ltp/manifest.template` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mOfxl3dgz8I-kRjY0:-O3mOfxm7Xsxd29l7pu_:b-rzrpnt) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/manifest.template#L43)):*
> ```
>   "file:install/testcases/bin/execlp01_child",  # for execlp01 test
>   "file:install/testcases/bin/execv01_child",   # for execv01 test
>   "file:install/testcases/bin/execvp01_child",  # for execvp01 test
> ```

Why are all these needed now, but weren't before?
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O3mWO-Y7XRe5cM5Ul-i:b-lperbh) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this is intended. I saw no particular reason to remove that functionality from `gramine-sgx-sign`. Is there any particular concern about this?
</blockquote></details>

So, maybe we could drop `.manifest.sgx` altogether? It would simplify life for the users.


<!-- Sent from Reviewable.io -->

2024-08-09 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 33 of 60 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`CI-Examples/blender/Makefile` line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/1812#-O31evmC1f_2i9j5aMo3:-O3pwl7S8fOnWxPErITW:bksjjs6) ([raw file](https://github.com/gramineproject/gramine/blob/eda2feaf0356870ba1e27b5bfaaabe55ceb6142e/CI-Examples/blender/Makefile#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/gramineproject/examples/pull/105 -- done here. I'll keep this comment blocking.
</blockquote></details>

That PR was merged, resolving.
___
*[`CI-Examples/nginx/Makefile` line 56 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH6gf6IO-_6cA3Ztw:-O3pwxDM1VRNgFzJ9qiY:bprgc36) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/nginx/Makefile#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please align with spaces, not tabs (it's not a recipe).
Also, I think it would look better if aligned to `:`?
</blockquote></details>

Are you sure we want to do this? That's literally how all Makefiles in CI-Examples are written... It will be strange if only this particular snippet would have the spaces, and everything else would have the tabs.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 80 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH21I3QWGdIL-7YUE:-O3pxF-jCIN15FcceaOX:bb54486) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/ra-tls-secret-prov/Makefile#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be aligned with spaces
</blockquote></details>

What do you mean? We always need the first tab in Makefiles, and then the rest can be either tabs or spaces. In this particular case, I use spaces.
___
*[`libos/test/ltp/ltp.cfg` line 252 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mNYRzBukttsI6YALG:-O3pxR-M2mu7A2lH9Py4:b-g5shxx) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/ltp.cfg#L252)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's suspicious, why is this needed?
</blockquote></details>

Actually, good question. I assumed this is because now `gramine-direct` spends some time in reading lists of trusted/allowed files (recall that this epoll01 test does a bunch of forks, and each fork starts Gramine from scratch, including re-reading the list of trusted files). But I better profile and double-check this theory.
___
*[`libos/test/ltp/manifest.template` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mOfxl3dgz8I-kRjY0:-O3pyJjw3nBB9IUdryKR:b-2dajar) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/manifest.template#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why are all these needed now, but weren't before?
</blockquote></details>

Because `gramine-direct` just allowed to open any files before. But now `gramine-direct` behaves as `gramine-sgx`: it **disallows** all files that are not in either allowed or trusted lists. So we need to be explicit now.
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O3pyo80AsSw10J_3cI2:buvj2rw) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
> So, maybe we could drop `.manifest.sgx` altogether?

What do you mean by drop? There are still many things that are completely irrelevant in `.manifest`, like `sgx.enclave_size`. Logically they should belong in `.manifest.sgx`, unless we agree on this (big) change of "all Gramine backends are served by a single file `.manifest`".

We can definitely do this, but it's out of scope of this PR I think. And it needs some discussions, especially with @woju. 

But I think making `.manifest.sgx` a symlink to `.manifest` is an ok idea, and maybe can even be implemented in this PR.


<!-- Sent from Reviewable.io -->

2024-08-09 08:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 33 of 60 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`libos/test/ltp/ltp.cfg` line 252 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mNYRzBukttsI6YALG:-O3qI6zw3_fRH_3Masfj:b1dm22y) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/ltp.cfg#L252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, good question. I assumed this is because now `gramine-direct` spends some time in reading lists of trusted/allowed files (recall that this epoll01 test does a bunch of forks, and each fork starts Gramine from scratch, including re-reading the list of trusted files). But I better profile and double-check this theory.
</blockquote></details>

Yes, my assumption was correct. Did some `perf record`/`perf report` on this PR and on the commit right-before this PR, and I observe that TOML-related functions (to read allowed/trusted files lists and construct in-memory data structs around them) constitute much more percentage of total time.


<!-- Sent from Reviewable.io -->

2024-08-18 00:34 UTC, mkow requested changes
> Reviewed 2 of 23 files at r1, 1 of 23 files at r2, 4 of 35 files at r4, 4 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 44 of 60 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`libos/test/ltp/ltp.cfg` line 252 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mNYRzBukttsI6YALG:-O4X_SlJ4NHPuHCP94ID:b-nhlit1) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/ltp.cfg#L252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, my assumption was correct. Did some `perf record`/`perf report` on this PR and on the commit right-before this PR, and I observe that TOML-related functions (to read allowed/trusted files lists and construct in-memory data structs around them) constitute much more percentage of total time.
</blockquote></details>

Ah, right, makes sense.
___
*[`libos/test/ltp/manifest.template` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mOfxl3dgz8I-kRjY0:-O4X__Ww5cQG1S-kbK9U:by8glu0) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/ltp/manifest.template#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because `gramine-direct` just allowed to open any files before. But now `gramine-direct` behaves as `gramine-sgx`: it **disallows** all files that are not in either allowed or trusted lists. So we need to be explicit now.
</blockquote></details>

Right, we run LTP only with `PAL/Linux`.
___
*[`libos/test/regression/fork_and_access_file.c` line 22 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4XixmQEkhabxjkJOqB:-O4XixmQEkhabxjkJOqC:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/regression/fork_and_access_file.c#L22)):*
> ```C
> char g_child_buf[MAX_BUF_SIZE];
> 
> static __attribute__ ((noinline)) void die_on_wrong_file_contents(void) {
> ```





_Suggestion:_
```C
__attribute__((noinline))
```
___
*[`libos/test/regression/fork_and_access_file.c` line 22 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xj9fnCij5oNqRXX06:-O4Xj9fnCij5oNqRXX07:bys1zas) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/regression/fork_and_access_file.c#L22)):*
> ```C
> char g_child_buf[MAX_BUF_SIZE];
> 
> static __attribute__ ((noinline)) void die_on_wrong_file_contents(void) {
> ```

Can you add a comment here explaining briefly why this function is `noinline`?
___
*[`libos/test/regression/fork_and_access_file.gdb` line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/1812#-O31kzsUC-3Ubkx8Q_Ub:-O4XkDuu62KUBaWVFTKn:bw7yxat) ([raw file](https://github.com/gramineproject/gramine/blob/eda2feaf0356870ba1e27b5bfaaabe55ceb6142e/libos/test/regression/fork_and_access_file.gdb#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can be considered an independent change. This LibOS test previously relied on the Gramine's `die_or_inf_loop` function being called. However, this function is used only in SGX PAL (it makes sense to kill the SGX enclave immediately, but it seems to not make sense to kill the normal process in this way).

So I modified the LibOS test to not know/care about Gramine internals, and instead be self-contained.

This particular change can be split into a separate PR, if people want to.
</blockquote></details>

I think it's simple enough to be kept here.
___
*[`pal/include/pal/pal.h` line 328 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xl4FiEGriuE457g66:-O4Xl4FiEGriuE457g67:bszmvoj) ([raw file](https://github.com/gramineproject/gramine/blob/bf4eae4c88900d1bbfaa5a9de8baa7825e61ceb5/pal/include/pal/pal.h#L328)):*
> ```objc
> #define PAL_OPTION_EFD_SEMAPHORE   0x1 /*!< specific to `eventfd` syscall */
> #define PAL_OPTION_NONBLOCK        0x2
> #define PAL_OPTION_PASSTHROUGH     0x4 /*!< Disregard `sgx.{allowed,trusted}_files` */
> ```

Finally removed!
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O4Xsqgs7z9L66d19b-X:bnty6mm) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This part is ugly: we still want to warn users about potentially insecure manifest options in SGX PAL, but these manifest options are located in LibOS. So we have to do some small processing of LibOS-bound options here.
</blockquote></details>

Hmm, this is really dangerous, e.g. when renaming this option - which we'll do very soon - we can forget to fix up this place, which will result in a silent omission of this warning.
One solution to make this less dangerous would be to add tests for all the possible warnings.

@kailun-qin: Any other ideas? I couldn't figure out a reasonable design which prevents double parsing.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 411 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4XqHwGBIUfnnRW5tTV:-O4XqHwGBIUfnnRW5tTW:b-vkwbfe) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_main.c#L411)):*
> ```C
> extern size_t g_unused_tcs_pages_num;
> 
> static bool need_warn_about_allowed_files_usage(void) {
> ```

"need warn" is not too grammatical :P



_Suggestion:_
```C
warn_about_allowed_files_usage
```
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 168 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xp7Ic0Labl8KBxx4s:-O4Xp7Ic0Labl8KBxx4t:b-4v9953) ([raw file](https://github.com/gramineproject/gramine/blob/bf4eae4c88900d1bbfaa5a9de8baa7825e61ceb5/pal/src/host/linux-sgx/pal_streams.c#L168)):*
> ```C
>             }
>             hdl->file.chunk_hashes = hdl->file.umem = NULL; /* set up in below fixup function */
>             hdl->file.fd = host_fd;   /* correct host FD must be set for below fixup function */
> ```

Who's setting `hdl->file.fd` now? If the one memcpy-ed here is correct, then why it wasn't before, but now is?
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O4Xlpgr4Biylm9xtcY6:b6ifzlq) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
Yeah, I didn't mean in this PR, just as a longer-term goal.

> There are still many things that are completely irrelevant in `.manifest`, like `sgx.enclave_size`. Logically they should belong in `.manifest.sgx`, unless we agree on this (big) change of "all Gramine backends are served by a single file `.manifest`".

But at the same time you say:

> But I think making `.manifest.sgx` a symlink to `.manifest` is an ok idea

That means these options end up in .manifest anyways? Am I missing something?


<!-- Sent from Reviewable.io -->

2024-08-19 04:48 UTC, kailun-qin reviewed
> Reviewed 5 of 23 files at r1, 3 of 23 files at r2, 6 of 35 files at r4, 11 of 14 files at r5, 1 of 1 files at r7, 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`CI-Examples/nginx/Makefile` line 56 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH6gf6IO-_6cA3Ztw:-O4cJVTI1PUNS_l_VBh0:b1q8me4) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/nginx/Makefile#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are you sure we want to do this? That's literally how all Makefiles in CI-Examples are written... It will be strange if only this particular snippet would have the spaces, and everything else would have the tabs.
</blockquote></details>

Yeah, I also prefer a separate PR for all similar places (if we really decide to do so).
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O4cYxG5-crrpWuPtOK2:b-frs1ad) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
> [@kailun-qin](https://github.com/kailun-qin): Any other ideas? I couldn't figure out a reasonable design which prevents double parsing.

Yep, seems like nothing better...
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O4cLUq05Yy7jtA2oHhT:b-b4nlg1) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
> I saw no particular reason to remove that functionality from `gramine-sgx-sign`. Is there any particular concern about this?

Nope, I'm fine w/ it (just wanted to double check).


<!-- Sent from Reviewable.io -->

2024-08-19 08:07 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4df2F02A60fqxCZode:-O4df2F02A60fqxCZodf:bcr3mxl) (no related file):*
What about https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/python/graminelibos/manifest.py#L360?

___


<!-- Sent from Reviewable.io -->

2024-08-19 09:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4df2F02A60fqxCZode:-O4e1lEA4iUY_2YPlUEZ:b-incz6i) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/python/graminelibos/manifest.py#L360?
</blockquote></details>

Done. Good catch, not needed anymore.

___
___
*[`libos/test/regression/fork_and_access_file.c` line 22 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4XixmQEkhabxjkJOqB:-O4dfpR6-UgkMXhUKfNW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/regression/fork_and_access_file.c#L22)):*
> ```C
> char g_child_buf[MAX_BUF_SIZE];
> 
> static __attribute__ ((noinline)) void die_on_wrong_file_contents(void) {
> ```

Done.
___
*[`libos/test/regression/fork_and_access_file.c` line 22 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xj9fnCij5oNqRXX06:-O4dfplcBmRfq1RIAxE1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/libos/test/regression/fork_and_access_file.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can you add a comment here explaining briefly why this function is `noinline`?
</blockquote></details>

Done.
___
*[`pal/include/pal/pal.h` line 328 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xl4FiEGriuE457g66:-O4deFeQ2xdvZwQkhLxm:bozjq9u) ([raw file](https://github.com/gramineproject/gramine/blob/bf4eae4c88900d1bbfaa5a9de8baa7825e61ceb5/pal/include/pal/pal.h#L328)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Finally removed!
</blockquote></details>

Yes, it took us only 3 years :)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O4dyhvl6l13Alm6sA8a:b-qdo60e) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> [@kailun-qin](https://github.com/kailun-qin): Any other ideas? I couldn't figure out a reasonable design which prevents double parsing.

Yep, seems like nothing better...
</blockquote></details>

Done (currently only for `sgx.file_check_policy` and `sgx.allowed_files`). Do you want me to submit a separate PR to check all other possible warnings?
___
*[`pal/src/host/linux-sgx/pal_main.c` line 411 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4XqHwGBIUfnnRW5tTV:-O4dv0Wu1Rj5BKTm2Tii:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_main.c#L411)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"need warn" is not too grammatical :P
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 168 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4Xp7Ic0Labl8KBxx4s:-O4dzLlHC_PTpEThSr2J:b2p6he4) ([raw file](https://github.com/gramineproject/gramine/blob/bf4eae4c88900d1bbfaa5a9de8baa7825e61ceb5/pal/src/host/linux-sgx/pal_streams.c#L168)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Who's setting `hdl->file.fd` now? If the one memcpy-ed here is correct, then why it wasn't before, but now is?
</blockquote></details>

This particular line was only needed here so that we can call `fixup_file_handle_after_deserialization()`. Since we don't need that function anymore, we also don't need this particular line.

Please see my other comment which highlights where the `hdl->file.fd` is set afterwards.

Please note that we only had this (redundant) `hdl->file.fd = host_fd` line because we had a slightly weird order of  calling the helper func `fixup_file_handle_after_deserialization()` **before** a generic setting of `hdl->file.fd`.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 338 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4dzDjGAdtVeJOUybN_:-O4dzDjGAdtVeJOUybNa:bdqim8r) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_streams.c#L338)):*
> ```C
>     /* restore cargo handle's FD from the received FD-to-transfer */
>     if (hdl_hdr.has_fd) {
>         handle->generic.fd = host_fd;
> ```

To @mkow: this is the generic code that sets the `handle->file.fd` (which is aliased by a generic field `handle->generic.fd`).
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O4df1L2DS0bY-mCQUAW:bk43iqp) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
> > But I think making `.manifest.sgx` a symlink to `.manifest` is an ok idea
> 
> That means these options end up in .manifest anyways? Am I missing something?

Yes, see here: https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/python/graminelibos/manifest.py#L300

Basically, `gramine-manifest` assigns SGX-specific options too. And this tool is used to generate `.manifest` from `.manifest.template`.

That's just how we (well, Woju) implemented this. We have two tools currently: `gramine-manifest` and `gramine-sgx-sign`. The latter tool is SGX-specific but its name doesn't imply "also assign SGX-specific options". So I guess Woju decided to dump all options, SGX specific or not, into the `gramine-manifest` tool.


<!-- Sent from Reviewable.io -->

2024-08-23 15:42 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 23 files at r1, 18 of 35 files at r4, 1 of 14 files at r5, 3 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/allowed.c` line 75 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4ztWlVEhTIdmV90IaE:-O4ztWlW6kIzcuNyJhhc:b-jbzul2) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L75)):*
> ```C
>     LISTP_FOR_EACH_ENTRY(tmp, &g_allowed_file_list, list) {
>         /* must be a sub-directory or file */
>         if (path_is_equal_or_subpath(tmp, norm_path, norm_path_size - 1)) {
> ```

you are passing `norm_path_size - 1` (allocation size, overapproximate) instead of `strlen(norm_path)` (actual size) here, resulting in false negative when the path actually needs normalization
___
*[`libos/src/fs/chroot/allowed.c` line 186 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zq0VN32YpYdGWLnav:-O4zq0VN32YpYdGWLnaw:bwvf24i) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L186)):*
> ```C
>     ssize_t toml_allowed_files_cnt = toml_array_nelem(toml_allowed_files);
>     if (toml_allowed_files_cnt < 0)
>         return -EPERM;
> ```

`-EPERM`?
___
*[`libos/src/fs/chroot/allowed.c` line 187 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zq9AQ3qMK_uxq-mAL:-O4zq9AQ3qMK_uxq-mAM:b-afojlk) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L187)):*
> ```C
>     if (toml_allowed_files_cnt < 0)
>         return -EPERM;
>     if (toml_allowed_files_cnt == 0)
> ```

this is completely redundant with the below loop


<!-- Sent from Reviewable.io -->

2024-08-23 15:43 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/allowed.c` line 159 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zts7DA89DORSaTv7_:-O4zts7DA89DORSaTv7a:b9bd38z) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L159)):*
> ```C
>     }
> 
>     ret = register_allowed_file(norm_allowed_path);
> ```

I am a little concerned about stuffing all created files in the allowed_file list — the list has quadratic behavior and if an application creates a fair amount of files, this is going to hurt. should we think about alternatives?


<!-- Sent from Reviewable.io -->

2024-08-23 17:19 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 23 files at r1, 1 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/trusted.c` line 306 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-E5Bu1xyWSwu38qsJ:-O5-E5Bu1xyWSwu38qsK:b-s02nw3) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L306)):*
> ```C
> 
>     size_t path_len = strlen(path);
>     if (path_len >= URI_MAX) {
> ```

shouldn't this be `>`? the "exceeds" wording implies that
___
*[`libos/src/fs/chroot/trusted.c` line 407 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-D0vL5ICtUJ0ZZOjp:-O5-D0vL5ICtUJ0ZZOjq:b-xc2d9a) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L407)):*
> ```C
>     ssize_t toml_trusted_files_cnt = toml_array_nelem(toml_trusted_files);
>     if (toml_trusted_files_cnt < 0)
>         return -EPERM;
> ```

`EPERM`? I don't think this needs to be checked at all; if you really think it should, make it an assert.
___
*[`libos/src/fs/chroot/trusted.c` line 408 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-D8VY2IcQCqE5zDJ9:-O5-D8VY2IcQCqE5zDJA:b-9u0131) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L408)):*
> ```C
>     if (toml_trusted_files_cnt < 0)
>         return -EPERM;
>     if (toml_trusted_files_cnt == 0)
> ```

redundant condition


<!-- Sent from Reviewable.io -->

2024-08-23 17:20 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/allowed.c` line 87 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-F79r3bv0ugmUjczZ:-O5-F79r3bv0ugmUjcz_:bt2ftza) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L87)):*
> ```C
> int register_allowed_file(const char* path) {
>     size_t path_len = strlen(path);
>     if (path_len >= URI_MAX) {
> ```

likewise — should be `>`


<!-- Sent from Reviewable.io -->

2024-08-23 17:30 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 23 files at r2, 3 of 35 files at r4, 7 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5-Gg0A0NEwCDKJNh6L:b3158j4) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done (currently only for `sgx.file_check_policy` and `sgx.allowed_files`). Do you want me to submit a separate PR to check all other possible warnings?
</blockquote></details>

I'd say that these options belong to libOS and should be checked there.

there's an argument that these should be checked for SGX PAL only; I disagree — they should be checked by all PALs that actually run in confidential computing environment, and the check should also exist in the future TDX or hypothetical SEV PALs.

I propose adding a PAL call that tells you whether the PAL is considered "confidential" or not, and checking the options in libOS if the function returns true. this puts the check in libOS where it belongs (and deduplicates it across all "secure" PALs), and leaves only a single function returning a constant bool in the PAL (which we may want to use for other purposes too)


<!-- Sent from Reviewable.io -->

2024-08-23 17:32 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 23 files at r2, 2 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2024-08-27 07:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 56 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/allowed.c` line 75 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4ztWlVEhTIdmV90IaE:-O5HfqLg5vRD1UBcl7zr:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L75)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

you are passing `norm_path_size - 1` (allocation size, overapproximate) instead of `strlen(norm_path)` (actual size) here, resulting in false negative when the path actually needs normalization
</blockquote></details>

Done
___
*[`libos/src/fs/chroot/allowed.c` line 87 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-F79r3bv0ugmUjczZ:-O5Hftox9RpP8fb4Ep-6:b-p4z971) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L87)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

likewise — should be `>`
</blockquote></details>

Done. There is no particular requirement about `URI_MAX` (like, no static field or something with this size), so looks like we can put whatever check here.
___
*[`libos/src/fs/chroot/allowed.c` line 159 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zts7DA89DORSaTv7_:-O5Hg42qAHpqD5VAWvg4:b-r7u9kv) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L159)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I am a little concerned about stuffing all created files in the allowed_file list — the list has quadratic behavior and if an application creates a fair amount of files, this is going to hurt. should we think about alternatives?
</blockquote></details>

Yes, we can think about alternatives. I can imagine the following optimization:
- Split "allowed files" internally into a linked list of *allowed dirs* and a hash table of *allowed files*
- On open-file checks, first traverse the list of allowed dirs -- this is fast because the list is typically minimal, 10-20 items max
- Then check the hash table of allowed files
- On creating files, add the file to the hash table of allowed files (i.e. never to the list of allowed dirs)

Is that what you had in mind?
___
*[`libos/src/fs/chroot/allowed.c` line 186 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zq0VN32YpYdGWLnav:-O5Hhfa-CgwAwO7Squ-E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L186)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

`-EPERM`?
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 187 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zq9AQ3qMK_uxq-mAL:-O5Hhg0-5TfiOMrhsKYt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L187)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this is completely redundant with the below loop
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/trusted.c` line 306 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-E5Bu1xyWSwu38qsJ:-O5Hhl01-9yu0JGlF_c5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L306)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

shouldn't this be `>`? the "exceeds" wording implies that
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/trusted.c` line 407 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-D0vL5ICtUJ0ZZOjp:-O5HhrEm0Auf7tab9Msx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L407)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

`EPERM`? I don't think this needs to be checked at all; if you really think it should, make it an assert.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/trusted.c` line 408 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5-D8VY2IcQCqE5zDJ9:-O5HhrigCXsBOTwag3lA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/trusted.c#L408)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

redundant condition
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5HhuIm9jv9YUtVuqru:b-bp1c3r) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I'd say that these options belong to libOS and should be checked there.

there's an argument that these should be checked for SGX PAL only; I disagree — they should be checked by all PALs that actually run in confidential computing environment, and the check should also exist in the future TDX or hypothetical SEV PALs.

I propose adding a PAL call that tells you whether the PAL is considered "confidential" or not, and checking the options in libOS if the function returns true. this puts the check in libOS where it belongs (and deduplicates it across all "secure" PALs), and leaves only a single function returning a constant bool in the PAL (which we may want to use for other purposes too)
</blockquote></details>

Agreed with @mwkmwkmwk. Though this should be done in a separate PR, so I created an issue for this: https://github.com/gramineproject/gramine/issues/1981


<!-- Sent from Reviewable.io -->

2024-08-27 15:22 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 57 of 60 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/allowed.c` line 159 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zts7DA89DORSaTv7_:-O5JQ8mzE_PgN1hFT1Vv:bk7blp3) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we can think about alternatives. I can imagine the following optimization:
- Split "allowed files" internally into a linked list of *allowed dirs* and a hash table of *allowed files*
- On open-file checks, first traverse the list of allowed dirs -- this is fast because the list is typically minimal, 10-20 items max
- Then check the hash table of allowed files
- On creating files, add the file to the hash table of allowed files (i.e. never to the list of allowed dirs)

Is that what you had in mind?
</blockquote></details>

that would work, yeah


<!-- Sent from Reviewable.io -->

2024-08-28 11:26 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 35 files at r4, 10 of 14 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 57 of 60 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2024-08-28 11:42 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 23 files at r1, 1 of 35 files at r4, 1 of 14 files at r8, 2 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2024-08-28 14:01 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5OHTzj3OAPV5PhpEIc:b-yh4zy0) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Agreed with @mwkmwkmwk. Though this should be done in a separate PR, so I created an issue for this: https://github.com/gramineproject/gramine/issues/1981
</blockquote></details>

why not do it now? it has the potential to actually simplify the code with a bunch of negative diffstat


<!-- Sent from Reviewable.io -->

2024-08-28 14:32 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/src/fs/chroot/fs.c` line 51 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OIX7V8417eXQpIylA:-O5OIX7V8417eXQpIylB:bf0g5eh) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L51)):*
> ```C
> 
> static bool is_allowed_from_inode_data(struct libos_inode* inode) {
>     if (!inode->data)
> ```

redundant with assert below
___
*[`libos/src/fs/chroot/fs.c` line 101 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OJ-9x-MChwqu7NH50:-O5OJ-9x-MChwqu7NH51:b-tzwbyb) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L101)):*
> ```C
> 
>     struct allowed_file* af = get_allowed_file(strip_prefix(uri));
>     if (af || type == S_IFDIR) {
> ```

nit: could avoid `get_allowed_file` check for directories by rewriting to `if (type == S_IFDIR || get_allowed_file(strip_prefix(uri))`
___
*[`libos/src/fs/chroot/fs.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OJE10Cnf7pLJdVJLl:-O5OJE118pkCeOfN2NHr:bz6qpsw) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L110)):*
> ```C
>     if (tf) {
>         struct trusted_chunk_hash* out_chunk_hashes;
>         int ret = load_trusted_file(tf, file_size, &out_chunk_hashes);
> ```

nit: can simplify to just `&data->chunk_hashes` and remove temp variable


<!-- Sent from Reviewable.io -->

2024-08-28 14:38 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)



<!-- Sent from Reviewable.io -->

2024-08-29 08:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/allowed.c` line 159 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zts7DA89DORSaTv7_:-O5S67Pe8cn1BDUBBQyV:b-2vfql) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L159)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

that would work, yeah
</blockquote></details>

Extracted here: https://github.com/gramineproject/gramine/issues/1983

I am reluctant to add this in this PR, as it will become harder to review (compare the changes).
___
*[`libos/src/fs/chroot/fs.c` line 51 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OIX7V8417eXQpIylA:-O5S6UI65lfefNnFN2Ik:bgl7lr1) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L51)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

redundant with assert below
</blockquote></details>

Done. Looks like debugging leftover.
___
*[`libos/src/fs/chroot/fs.c` line 101 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OJ-9x-MChwqu7NH50:-O5S6rnHBLKZiXrQ7N6Q:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L101)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

nit: could avoid `get_allowed_file` check for directories by rewriting to `if (type == S_IFDIR || get_allowed_file(strip_prefix(uri))`
</blockquote></details>

Done
___
*[`libos/src/fs/chroot/fs.c` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5OJE10Cnf7pLJdVJLl:-O5S7-as2cPNF1Y6l67q:b-gnk44a) ([raw file](https://github.com/gramineproject/gramine/blob/16bfaa7fb52e3a286e615db5877876fe04ba8be9/libos/src/fs/chroot/fs.c#L110)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

nit: can simplify to just `&data->chunk_hashes` and remove temp variable
</blockquote></details>

I'm reluctant to do this, as a badly written `load_trusted_file()` could accidentally update the `data` object then and leave it in inconsistent state. I think it's a good practice to first put things in temporary variables, if there's a high chance that the function may return failure.
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5S7hi-AxnLGzst_ysk:bpmue3w) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

why not do it now? it has the potential to actually simplify the code with a bunch of negative diffstat
</blockquote></details>

This is a large change that touches a lot of unrelated places. I still prefer to do it as a follow-up PR. I'm currently working on this (based on top of this PR). In the worst case, if all reviewers will agree, I can cherry-pick the commit from that new PR into this one. But to me, the PRs work on completely different things, and to have clear Git/GitHub history, I would prefer to split them.


<!-- Sent from Reviewable.io -->

2024-08-29 10:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5S_mgsA5hVFopD7qMQ:b-8pjpkd) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a large change that touches a lot of unrelated places. I still prefer to do it as a follow-up PR. I'm currently working on this (based on top of this PR). In the worst case, if all reviewers will agree, I can cherry-pick the commit from that new PR into this one. But to me, the PRs work on completely different things, and to have clear Git/GitHub history, I would prefer to split them.
</blockquote></details>

Done here: https://github.com/gramineproject/gramine/pull/1984

So turned out not to be *that* big, so theoretically I could stash the changes into this PR. Whatever @mwkmwkmwk @mkow @kailun-qin decide, I can oblige.


<!-- Sent from Reviewable.io -->

2024-08-30 12:47 UTC, mkow requested changes
> Reviewed 3 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5YJL8k1SDQWG5hjGwD:be1kj0z) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done here: https://github.com/gramineproject/gramine/pull/1984

So turned out not to be *that* big, so theoretically I could stash the changes into this PR. Whatever @mwkmwkmwk @mkow @kailun-qin decide, I can oblige.
</blockquote></details>

Hmm, would it be possible to merge #1984 to master first? I guess that's what mwk meant, that if we ship this fix then this PR will get simpler (but I'm not entirely sure if that was her suggestion).
Anyways, that would be preferred way from my side.


<!-- Sent from Reviewable.io -->

2024-09-01 16:47 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mwkmwkmwk)

___
*[`CI-Examples/nginx/Makefile` line 56 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH6gf6IO-_6cA3Ztw:-O5iR4hW7TwVarvujQ5X:b-wlca7t) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/nginx/Makefile#L56)):*
> That's literally how all Makefiles in CI-Examples are written

I didn't find any other place in our Makefiles where we wrap the dependencies list. Anyways, won't block on this.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 80 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH21I3QWGdIL-7YUE:-O5iSpC37DOImH4emPi9:b4an00y) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/ra-tls-secret-prov/Makefile#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? We always need the first tab in Makefiles, and then the rest can be either tabs or spaces. In this particular case, I use spaces.
</blockquote></details>

No, that's for recipes. This is a line wrap from the dependecies list, and in the way you did it here it will end up misaligned if someone has different tab size settings than you.
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O5iTHCU59DWzyYSQ5d4:b8lsthy) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> > But I think making `.manifest.sgx` a symlink to `.manifest` is an ok idea
> 
> That means these options end up in .manifest anyways? Am I missing something?

Yes, see here: https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/python/graminelibos/manifest.py#L300

Basically, `gramine-manifest` assigns SGX-specific options too. And this tool is used to generate `.manifest` from `.manifest.template`.

That's just how we (well, Woju) implemented this. We have two tools currently: `gramine-manifest` and `gramine-sgx-sign`. The latter tool is SGX-specific but its name doesn't imply "also assign SGX-specific options". So I guess Woju decided to dump all options, SGX specific or not, into the `gramine-manifest` tool.
</blockquote></details>

Then I don't see why we need manifest.sgx at all. We can just remove it and always use .manifest? (and as said above, that's a change for another PR if agreed)


<!-- Sent from Reviewable.io -->

2024-09-02 01:46 UTC, mkow requested changes
> Reviewed 2 of 23 files at r1, 2 of 23 files at r2, 1 of 14 files at r5, 8 of 14 files at r8, 1 of 4 files at r9, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/allowed.c` line 12 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kN_FF9OBNf8qr-6ax:-O5kN_FF9OBNf8qr-6ay:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L12)):*
> ```C
>  *
>  * Allowed files are useful for debugging, or when files are guaranteed to have no effect on
>  * security of the execution (e.g. non-critical logs), or when the application itself protects these
> ```





_Suggestion:_
```C
non-confidential
```
___
*[`libos/src/fs/chroot/allowed.c` line 33 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kNyTz3gQtttBpKaJJ:-O5kNyTz3gQtttBpKaJK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L33)):*
> ```C
> 
> DEFINE_LISTP(allowed_file);
> static LISTP_TYPE(allowed_file) g_allowed_file_list = LISTP_INIT;
> ```





_Suggestion:_
```C
g_allowed_files_list
```
___
*[`libos/src/fs/chroot/allowed.c` line 34 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kPKsA1Hk5-G7v55dJ:-O5kPKsA1Hk5-G7v55dK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L34)):*
> ```C
> DEFINE_LISTP(allowed_file);
> static LISTP_TYPE(allowed_file) g_allowed_file_list = LISTP_INIT;
> static spinlock_t g_allowed_file_lock = INIT_SPINLOCK_UNLOCKED;
> ```





_Suggestion:_
```C
g_allowed_files_lock
```
___
*[`libos/src/fs/chroot/allowed.c` line 36 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kOBZX9Em0_hbNLsli:-O5kOBZX9Em0_hbNLslj:b-h6iqlk) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L36)):*
> ```C
> static spinlock_t g_allowed_file_lock = INIT_SPINLOCK_UNLOCKED;
> 
> static bool path_is_equal_or_subpath(const struct allowed_file* af, const char* path,
> ```

This name is confusing, which of the arguments will be treated as the subpath?



_Code quote:_
```C
path_is_equal_or_subpath
```
___
*[`libos/src/fs/chroot/allowed.c` line 36 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kOQcZ2e0izWy7FmfJ:-O5kOQcZ2e0izWy7FmfK:b9ouyci) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L36)):*
> ```C
> static spinlock_t g_allowed_file_lock = INIT_SPINLOCK_UNLOCKED;
> 
> static bool path_is_equal_or_subpath(const struct allowed_file* af, const char* path,
> ```

Does this assume that the paths are already normalized? If so, please add a comment.
___
*[`libos/src/fs/chroot/file_check_policy.c` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jYG2l2eZ8-78vSjkG:-O5jYG2m7iw-hm7U6PKc:b6qfoxx) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/file_check_policy.c#L9)):*
> ```C
> #include "toml_utils.h"
> 
> int g_file_check_policy = FILE_CHECK_POLICY_STRICT;
> ```

Please name the enum and use it via `enum name` instead of `int`.
___
*[`libos/src/fs/chroot/fs.c` line 45 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jboiJ8w-czoGy014g:-O5jboiJ8w-czoGy014h:b-fv1deq) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L45)):*
> ```C
> struct chroot_inode_data {
>     bool is_trusted;
>     bool is_allowed;
> ```

Why two bools? One is always the negation of the other, right? If you want to be explicit with the names, then I'd use an enum instead.

// Update: I see, it's used with "allow everything" via the manifest switch. Could you add a comment here explaining that? Or maybe change this into a tri-state enum? (disallowed-allowed-trusted)
___
*[`libos/src/fs/chroot/fs.c` line 302 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jub5M8_10-8l7VU0P:-O5jub5M8_10-8l7VU0Q:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L302)):*
> ```C
> 
>     mode_t perm = pal_attr.share_flags;
>     size_t file_size = (type == S_IFREG ? pal_attr.pending_size : 0);
> ```





_Suggestion:_
```C
size_t file_size = type == S_IFREG ? pal_attr.pending_size : 0;
```
___
*[`libos/src/fs/chroot/fs.c` line 538 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jzI0MBiYRrr2Gs_8-:-O5jzI0MBiYRrr2Gs_80:b-4np38o) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L538)):*
> ```C
>     if (is_trusted_from_inode_data(hdl->inode)) {
>         struct chroot_inode_data* data = hdl->inode->data;
>         ret = copy_and_verify_trusted_file(hdl->pal_handle, offset, actual_count, buf,
> ```

It's the same, but IMO this makes more sense. Or maybe make it an in-out argument, like in `PalStreamRead()`? `copy_and_verify_trusted_file()` calculates this value on its own anyways.



_Suggestion:_
```C
count
```
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 338 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4dzDjGAdtVeJOUybN_:-O5jJNOYDdLnp7ifCZdO:b-1p6f5l) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_streams.c#L338)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To @mkow: this is the generic code that sets the `handle->file.fd` (which is aliased by a generic field `handle->generic.fd`).
</blockquote></details>

Huh, this "aliasing" in `struct PAL_HANDLE` is weird. One union member doesn't start with `PAL_IDX fd;`?

Ok, I see there's a magic pair of flags in the handle header which decide whether this field is present... This is a really terrible design, will probably lead to a bug someday...


<!-- Sent from Reviewable.io -->

2024-09-02 09:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 59 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5m6R731s-pnztULReA:bvcw8vk) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, would it be possible to merge #1984 to master first? I guess that's what mwk meant, that if we ship this fix then this PR will get simpler (but I'm not entirely sure if that was her suggestion).
Anyways, that would be preferred way from my side.
</blockquote></details>

Done, I re-created #1984 on top of current master: https://github.com/gramineproject/gramine/pull/1986

I decided to create a separate PR so that we can decide which one to use better. I guess we should favor #1986.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 338 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4dzDjGAdtVeJOUybN_:-O5m5W5uEztz94I8c-zk:bz41ui6) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_streams.c#L338)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, this "aliasing" in `struct PAL_HANDLE` is weird. One union member doesn't start with `PAL_IDX fd;`?

Ok, I see there's a magic pair of flags in the handle header which decide whether this field is present... This is a really terrible design, will probably lead to a bug someday...
</blockquote></details>

Yes, the design is pretty bad. Do you want me to create an issue on this? And what would be the preferred fix -- just remove `generic.fd` and always use specific `<file|process|etc>.id` (this will result in slightly bloated code because of duplication)?
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O5m5lqb3dV4_dR4BYEt:bi0gugv) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then I don't see why we need manifest.sgx at all. We can just remove it and always use .manifest? (and as said above, that's a change for another PR if agreed)
</blockquote></details>

Well, yes, we won't need this file (other than for backwards-compatibility reasons). Do you want me to create a GitHub issue?


<!-- Sent from Reviewable.io -->

2024-09-02 11:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 53 of 60 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @mwkmwkmwk)

___
*[`CI-Examples/nginx/Makefile` line 56 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH6gf6IO-_6cA3Ztw:-O5m8GWz4YpLH23jOLNo:b-t7wn70) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/nginx/Makefile#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> That's literally how all Makefiles in CI-Examples are written

I didn't find any other place in our Makefiles where we wrap the dependencies list. Anyways, won't block on this.
</blockquote></details>

Done. Ok, my bad, I didn't realize that you're talking about wrapping the **list of dependencies**. Sorry.
___
*[`CI-Examples/ra-tls-secret-prov/Makefile` line 80 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O3mH21I3QWGdIL-7YUE:-O5m8vzh1rBInuyYxppB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/CI-Examples/ra-tls-secret-prov/Makefile#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, that's for recipes. This is a line wrap from the dependecies list, and in the way you did it here it will end up misaligned if someone has different tab size settings than you.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 12 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kN_FF9OBNf8qr-6ax:-O5m97iX5BHGluUHHVr2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L12)):*
> ```C
>  *
>  * Allowed files are useful for debugging, or when files are guaranteed to have no effect on
>  * security of the execution (e.g. non-critical logs), or when the application itself protects these
> ```

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 33 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kNyTz3gQtttBpKaJJ:-O5m9JITBQk830upja5A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L33)):*
> ```C
> 
> DEFINE_LISTP(allowed_file);
> static LISTP_TYPE(allowed_file) g_allowed_file_list = LISTP_INIT;
> ```

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 34 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kPKsA1Hk5-G7v55dJ:-O5m9Jez9JQ8050x3Tdq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L34)):*
> ```C
> DEFINE_LISTP(allowed_file);
> static LISTP_TYPE(allowed_file) g_allowed_file_list = LISTP_INIT;
> static spinlock_t g_allowed_file_lock = INIT_SPINLOCK_UNLOCKED;
> ```

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 36 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kOBZX9Em0_hbNLsli:-O5mAKTIDC0kA45sUadr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This name is confusing, which of the arguments will be treated as the subpath?
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/allowed.c` line 36 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5kOQcZ2e0izWy7FmfJ:-O5mAM9M4rFAJwT4C6td:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/allowed.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this assume that the paths are already normalized? If so, please add a comment.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/file_check_policy.c` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jYG2l2eZ8-78vSjkG:-O5mBLLP4c89IlY0xiD0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/file_check_policy.c#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please name the enum and use it via `enum name` instead of `int`.
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/fs.c` line 45 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jboiJ8w-czoGy014g:-O5mO4G8A_v2gPnOLXTg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why two bools? One is always the negation of the other, right? If you want to be explicit with the names, then I'd use an enum instead.

// Update: I see, it's used with "allow everything" via the manifest switch. Could you add a comment here explaining that? Or maybe change this into a tri-state enum? (disallowed-allowed-trusted)
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/fs.c` line 302 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jub5M8_10-8l7VU0P:-O5mBU8nASb5pDFTO_Kc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L302)):*
> ```C
> 
>     mode_t perm = pal_attr.share_flags;
>     size_t file_size = (type == S_IFREG ? pal_attr.pending_size : 0);
> ```

Done.
___
*[`libos/src/fs/chroot/fs.c` line 538 at r11](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5jzI0MBiYRrr2Gs_8-:-O5mDa6X0hhmq1jpsUmf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0132a82709c586fa3c1c138e8f3b9578cf68e821/libos/src/fs/chroot/fs.c#L538)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's the same, but IMO this makes more sense. Or maybe make it an in-out argument, like in `PalStreamRead()`? `copy_and_verify_trusted_file()` calculates this value on its own anyways.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-02 15:06 UTC, mkow requested changes
> Reviewed 5 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/allowed.c` line 159 at r9](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4zts7DA89DORSaTv7_:-O5n5rv46kKGNivjx5Q3:b-dmfob3) ([raw file](https://github.com/gramineproject/gramine/blob/025ef79cae4ba43d842d8f12473fdcea7ec4d45a/libos/src/fs/chroot/allowed.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Extracted here: https://github.com/gramineproject/gramine/issues/1983

I am reluctant to add this in this PR, as it will become harder to review (compare the changes).
</blockquote></details>

I'm fine with doing that optimization separately.
___
*[`libos/src/fs/chroot/fs.c` line 64 at r12](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5nDhb8BCbPjLol0How:-O5nDhb8BCbPjLol0Hox:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3cb3075f3460a240a7e8460840abe4b82779376e/libos/src/fs/chroot/fs.c#L64)):*
> ```C
> /* this data is set up only once (at inode creation or restore), so doesn't require locking */
> struct chroot_inode_data {
>     enum file_protection_kind file_kind;
> ```





_Suggestion:_
```C
prot_kind;
```
___
*[`libos/src/fs/chroot/fs.c` line 97 at r12](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5nAMvq3-SAajZK22SJ:-O5nAMvq3-SAajZK22SK:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3cb3075f3460a240a7e8460840abe4b82779376e/libos/src/fs/chroot/fs.c#L97)):*
> ```C
>     data->file_kind = FILE_PROTECTION_KIND_NONE;
>     if (get_allowed_file(strip_prefix(uri)))
>         data->file_kind = FILE_PROTECTION_KIND_ALLOWED;
> ```





_Suggestion:_
```C
    data->file_kind = get_allowed_file(strip_prefix(uri))
                      ? FILE_PROTECTION_KIND_ALLOWED
                      : FILE_PROTECTION_KIND_NONE;
```
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 338 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4dzDjGAdtVeJOUybN_:-O5nFhLF0yywt43UhfE7:b844w6w) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_streams.c#L338)):*
> Do you want me to create an issue on this?

Sounds good.

Regarding how to fix it - I'm not sure, I'd need to think about that more, so let's just create an issue and work on it later.
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O5nGBX368GLL-XdB5UJ:b-5wconm) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, yes, we won't need this file (other than for backwards-compatibility reasons). Do you want me to create a GitHub issue?
</blockquote></details>

Yes, please.


<!-- Sent from Reviewable.io -->

2024-09-02 18:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 58 of 60 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, @mwkmwkmwk, and @woju)

___
*[`libos/src/fs/chroot/fs.c` line 64 at r12](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5nDhb8BCbPjLol0How:-O5nv8UPEA7I87W5M4AC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3cb3075f3460a240a7e8460840abe4b82779376e/libos/src/fs/chroot/fs.c#L64)):*
> ```C
> /* this data is set up only once (at inode creation or restore), so doesn't require locking */
> struct chroot_inode_data {
>     enum file_protection_kind file_kind;
> ```

Done.
___
*[`libos/src/fs/chroot/fs.c` line 97 at r12](https://reviewable.io/reviews/gramineproject/gramine/1812#-O5nAMvq3-SAajZK22SJ:-O5nvHoy5e13VyJPUjkr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3cb3075f3460a240a7e8460840abe4b82779376e/libos/src/fs/chroot/fs.c#L97)):*
> ```C
>     data->file_kind = FILE_PROTECTION_KIND_NONE;
>     if (get_allowed_file(strip_prefix(uri)))
>         data->file_kind = FILE_PROTECTION_KIND_ALLOWED;
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_streams.c` line 338 at r8](https://reviewable.io/reviews/gramineproject/gramine/1812#-O4dzDjGAdtVeJOUybN_:-O5nxD_XB3iN_VRzoOok:b-p6iesq) ([raw file](https://github.com/gramineproject/gramine/blob/2ed3b55949931da4feecd23791bd1622ca392d98/pal/src/host/linux-sgx/pal_streams.c#L338)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Do you want me to create an issue on this?

Sounds good.

Regarding how to fix it - I'm not sure, I'd need to think about that more, so let's just create an issue and work on it later.
</blockquote></details>

Done: https://github.com/gramineproject/gramine/issues/1989
___
*[`python/gramine-manifest` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1812#-NsxaGCgDVTu-TjSQWHx:-O5ny7uiAV4Anv5ik_UD:brd8dum) ([raw file](https://github.com/gramineproject/gramine/blob/48edacb75ef42648195eb6042a9cd049df173c5b/python/gramine-manifest#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, please.
</blockquote></details>

Done, https://github.com/gramineproject/gramine/issues/1990


<!-- Sent from Reviewable.io -->

2024-09-04 17:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: 48 of 60 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, @mwkmwkmwk, and @woju)

___
*[`pal/src/host/linux-sgx/pal_main.c` line 411 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9ddZ5Y2AgdYk5LLD:-O5y-JCDBD-S7mddwnVT:beqkrk5) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L411)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This part is ugly: we still want to warn users about potentially insecure manifest options in SGX PAL, but these manifest options are located in LibOS. So we have to do some small processing of LibOS-bound options here.
</blockquote></details>

Done, this was removed (because of #1986)
___
*[`pal/src/host/linux-sgx/pal_main.c` line 485 at r4](https://reviewable.io/reviews/gramineproject/gramine/1812#-O2y9rg59N0au4yqI2V4:-O5y-ONm4rJ4v_ekI2Ed:b-qow1ld) ([raw file](https://github.com/gramineproject/gramine/blob/d4c6f52084ca4b637f1aee5459883c399e80b25b/pal/src/host/linux-sgx/pal_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I re-created #1984 on top of current master: https://github.com/gramineproject/gramine/pull/1986

I decided to create a separate PR so that we can decide which one to use better. I guess we should favor #1986.
</blockquote></details>

Done, rebased on top of #1986 


<!-- Sent from Reviewable.io -->

2024-09-08 14:44 UTC, mkow requested changes
> Reviewed 1 of 2 files at r10, 1 of 6 files at r12, 1 of 1 files at r13, 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/trusted.c` line 18 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6E3TmmAHvufhnVbpWP:-O6E3TmmAHvufhnVbpWQ:b-hafqxh) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L18)):*
> ```C
>  * each chunk (of size TRUSTED_CHUNK_SIZE) in the file. The per-chunk hashes are used for partial
>  * verification in future reads, to avoid re-verifying the whole file again or the need of caching
>  * file contents.
> ```

that's an important detail, caching parts is totally fine (and AFAIR we actually considered doing so)



_Suggestion:_
```C
the whole file contents.
```
___
*[`libos/src/fs/chroot/trusted.c` line 44 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gj_NX3-l1sV_CmatR:-O6Gj_NYDL23TECo0Yh_:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L44)):*
> ```C
> };
> 
> /* initialized once at startup, so doesn't require locking */
> ```





_Suggestion:_
```C
/* initialized once at startup and read-only afterwards, so doesn't require locking */
```
___
*[`libos/src/fs/chroot/trusted.c` line 48 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6GlNLp-N9ZffK4jm6l:-O6GlNLqEh1WvxfPOb1e:bh5ac78) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L48)):*
> ```C
> static LISTP_TYPE(trusted_file) g_trusted_file_list = LISTP_INIT;
> 
> static int read_trusted_file(PAL_HANDLE handle, void* buffer, uint64_t offset, size_t size) {
> ```

Can't we use `read_exact()` instead? (but you'd need to add `offset` arg to it)
Also, `read_trusted_file` is misleading, it's not reading a trusted file with some checks, it's just a generic file read without any verification.
___
*[`libos/src/fs/chroot/trusted.c` line 86 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gmf6QDi3yNQbMFQkk:-O6Gmf6RCaZgtGeIaGbt:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L86)):*
> ```C
>     struct trusted_file* tmp;
>     LISTP_FOR_EACH_ENTRY(tmp, &g_trusted_file_list, list) {
>         if ((tmp->path_len == norm_path_size - 1)
> ```





_Suggestion:_
```C
tmp->path_len == norm_path_size - 1
```
___
*[`libos/src/fs/chroot/trusted.c` line 97 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gn7Jo5tIupcJZ5g0r:-O6Gn7Jo5tIupcJZ5g0s:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L97)):*
> ```C
> 
> size_t get_chunk_hashes_size(size_t file_size) {
>     return (sizeof(struct trusted_chunk_hash) * UDIV_ROUND_UP(file_size, TRUSTED_CHUNK_SIZE));
> ```





_Suggestion:_
```C
return sizeof(struct trusted_chunk_hash) * UDIV_ROUND_UP(file_size, TRUSTED_CHUNK_SIZE);
```
___
*[`libos/src/fs/chroot/trusted.c` line 115 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gpif543s_1Xy5Ngoc:-O6Gpif543s_1Xy5Ngod:biq3pnx) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L115)):*
> ```C
>     memcpy(uri, URI_PREFIX_FILE, URI_PREFIX_FILE_LEN);
>     memcpy(uri + URI_PREFIX_FILE_LEN, tf->path, tf->path_len);
>     uri[URI_PREFIX_FILE_LEN + tf->path_len] = '\0';
> ```

You could use `alloc_concat()` instead.
___
*[`libos/src/fs/chroot/trusted.c` line 212 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gufny0Ahmkd9OTGys:-O6GufnzBQxFHTovd6k9:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L212)):*
> ```C
> }
> 
> int copy_and_verify_trusted_file(PAL_HANDLE handle, uint64_t offset, size_t count, uint8_t* buf,
> ```





_Suggestion:_
```C
read_and_verify_trusted_file
```
___
*[`libos/src/fs/chroot/trusted.c` line 221 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6Gv19Y8I059ihedD4c:-O6Gv19Y8I059ihedD4d:b-ylnn23) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L221)):*
> ```C
>     uint64_t end = MIN(offset + count, file_size);
>     uint64_t aligned_offset = ALIGN_DOWN(offset, TRUSTED_CHUNK_SIZE);
>     uint64_t aligned_end    = ALIGN_UP(end, TRUSTED_CHUNK_SIZE);
> ```

Why do we need that? You use it in only one place where `end` can be used instead.
___
*[`libos/src/fs/chroot/trusted.c` line 256 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6GyjsED2gh1rr4qcIG:-O6GyjsED2gh1rr4qcIH:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L256)):*
> ```C
>             buf_pos += chunk_size;
>         } else {
>             /* if current chunk-to-copy only partially overlaps with the requested region-to-copy,
> ```





_Suggestion:_
```C
chunk-to-verify
```
___
*[`libos/src/fs/chroot/trusted.c` line 352 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6H2kDJ9lYVoBrN8Tbd:-O6H2kDJ9lYVoBrN8Tbe:b-9714hx) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L352)):*
> ```C
> 
>     ret = toml_rtos(toml_trusted_sha256_raw, &toml_trusted_sha256_str);
>     if (ret < 0 || !toml_trusted_sha256_str) {
> ```

Why is this `if` different than the above one? (when parsing `toml_trusted_uri_str`)
___
*[`libos/src/fs/chroot/trusted.c` line 359 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6H2vvj1CuiQYkxhgVu:-O6H2vvj1CuiQYkxhgVv:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L359)):*
> ```C
> 
>     if (!strstartswith(toml_trusted_uri_str, URI_PREFIX_FILE)) {
>         log_error("Invalid URI [%s]: Trusted files must start with 'file:'", toml_trusted_uri_str);
> ```





_Suggestion:_
```C
"Invalid URI [%s]: Trusted files must start with '" URI_PREFIX_FILE "'"
```


<!-- Sent from Reviewable.io -->

2024-09-10 14:09 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mwkmwkmwk)

___
*[`libos/src/fs/chroot/trusted.c` line 48 at r14](https://reviewable.io/reviews/gramineproject/gramine/1812#-O6GlNLp-N9ZffK4jm6l:-O6RE_PlCsgbPOVHFfPs:b-h40a37) ([raw file](https://github.com/gramineproject/gramine/blob/778b1ce20dd78182df0328aff6e80130d481a26e/libos/src/fs/chroot/trusted.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, partially.

I cannot use `read_exact()` because that function is used for pipes/unix sockets, and explicitly has `offset = 0` argument always. The PAL pipes/sockets verify that `PalStreamRead()` must have `offset == 0`, so I would need a rather complex logic like this:
```
read_exact(..., bool is_file, uint64_t offset) {
    while (stuff to read) {
        uint64_t curr_offset = is_file ? read + offset : 0; /* pipes require offset 0 */
        PalStreamRead(..., curr_offset);
    }
}
```

This just didn't feel right, so I kept the function here as a local one, and renamed it.
</blockquote></details>

Ah, ok then.


<!-- Sent from Reviewable.io -->

2024-09-10 23:12 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 4 files at r9, 4 of 6 files at r12, 9 of 9 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-09-26 10:13 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: all files reviewed, 2 unresolved discussions (waiting on @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-09-26 12:33 UTC, kailun-qin approved these changes
> Reviewed 4 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 12:33 UTC, kailun-qin approved these changes
> Reviewed 1 of 4 files at r9, 1 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 15:05 UTC, merged