[LibOS] Move `init_r_debug()` before `init_fs()`
gramineproject/gramine pull request #1814
Opened 2024-03-14 12:55 UTC by dimakuv

## Description of the changes 

Many subsystems rely on debug metadata (in particular, the lock for debug info) to be already initialized. This is especially true for error handling paths, which may want to remove the debug info.

Extracted from #1812.

Fixes #1813.

## How to test this PR? 

See #1813.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1814)

2024-03-20 01:22 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1814#-NtORc8_D0bHl9_WuISG):*
> This is especially true for error handling paths, which may want to remove the debug info.

? I don't understand this sentence, error handling paths want to remove debug info? What do you mean by this?


<!-- Sent from Reviewable.io -->

2024-04-02 01:06 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1814#-NtORc8_D0bHl9_WuISG):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is especially true for error handling paths, which may want to remove the debug info.

? I don't understand this sentence, error handling paths want to remove debug info? What do you mean by this?
</blockquote></details>

+1

-> `Many subsystems (in particular, their error handling paths) rely on debug metadata (in particular, the lock for debug info) to be already initialized.`


<!-- Sent from Reviewable.io -->

2024-04-02 11:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1814#-NtORc8_D0bHl9_WuISG):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1

-> `Many subsystems (in particular, their error handling paths) rely on debug metadata (in particular, the lock for debug info) to be already initialized.`
</blockquote></details>

Done. Reworded as Kailun suggested, plus added a quick example.

For why this happens, see https://github.com/gramineproject/gramine/issues/1813


<!-- Sent from Reviewable.io -->

2024-04-02 12:49 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-04-12 12:36 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-12 19:23 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-Sanitizers please (unrelated `test_sign_from_pem_path_with_passphrase` error)

2024-04-12 22:03 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-13 00:24 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1814)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-13 12:08 UTC, merged