[LibOS,PAL] Emulate file-backed mmap via PAL read/write APIs
gramineproject/gramine pull request #1818
Opened 2024-03-14 15:18 UTC by dimakuv

## Description of the changes 

Previously, the `chroot` FS (plain host-backed files) used the `PalStreamMap()` PAL API for file-backed mmap. This had three problems: 1) need to implement a non-trivial `map` callback in PALs; 2) discrepancy between `map` implementations in different PALs; 3) hard to debug file-mmap bugs because they only reproduced on SGX (`gramine-sgx`) PAL and not on Linux (`gramine-direct`) PAL.

Note that other FSes already used emulated file-backed mmap: `tmpfs` and `encrypted` emulate such mmaps via `PalStreamRead()` and `PalStreamWrite()`.

This PR switches `chroot` FS to use emulated file-backed mmap. This way, `chroot` becomes similar in implementation to `tmpfs` and `encrypted` FSes. Only `shm` FS still uses `PalStreamMap()` because devices with shared memory have non-standard semantics of mmaps. Corresponding `file_map()` functions in PAL are removed.

This switch to emulated mmap uncovered several bugs:
- Underlying file may be shorter than the requested mmap size. In this case access beyond the last file-backed page must cause SIGBUS. Previously this semantics worked only on `gramine-direct` and wasn't implemented on `gramine-sgx` (with EDMM).
- As a consequence of the semantics above, file-growing `ftruncate()` on already-mmapped file must make newly extended file contents accessible. Previously it didn't work on `gramine-sgx` (with EDMM), now it is resolved via `prot_refresh_mmaped_from_file_handle()` call.
- `msync()` must update file contents with the mmapped-in-process contents, but only those parts that do not exceed the file size. Previously there was a bug that msync'ed even the exceeding parts.
- Applications expect `msync(MS_ASYNC)` to update file contents before the next app access to the file. Gramine instead ignored such requests, leading to accessing stale contents. We fix this bug by treating `MS_ASYNC` the same way as `MS_SYNC`. This bug was detected on LTP test `msync01`.

Several FS tests are enabled on SGX now. Generally, `gramine-sgx` now supports shared file-backed mappings, i.e. `mmap(MAP_SHARED)`.

Extracted from https://github.com/gramineproject/gramine/pull/1812.

## How to test this PR? 

Several new tests are enabled. Maybe some new LTP tests can be enabled (didn't check).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1818)

2024-03-15 09:05 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-20.04-musl please. Error is in the signing test:

```
tests.test_sgx_sign.test_sign_from_pem_path (from pytest)

Error Message
cryptography.exceptions.InvalidSignature
```

2024-05-23 21:54 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 0 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-NybRAuz3Pdfn-hfg-kJ:bnmpjbt) (no related file):*
it should be noted that this PR introduces a major regression: writable `MAP_SHARED` mappings that are actually shared between processes will no longer work correctly

___
___
*[`libos/src/bookkeep/libos_vma.c` line 1558 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRQD02P8LkpEw7ztX:-NybRQD02P8LkpEw7ztY:bre511d) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/bookkeep/libos_vma.c#L1558)):*
> ```C
> /* This helper function is to refresh access protections on the VMA pages of a given file handle on
>  * file-extend operations (currently only `ftruncate`). */
> int prot_refresh_mmaped_from_file_handle(struct libos_handle* hdl) {
> ```

this iterates over all VMAs we have in memory, not just VMAs belonging to this file; once we fix `write` to also call this function, this is likely to cause significant performance problems
___
*[`libos/src/fs/libos_fs_util.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRbCMAU4kjugh7rS1:-NybRbCN9DkUePRXRpGh:b-m8gsyz) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/fs/libos_fs_util.c#L255)):*
> ```C
> }
> 
> int generic_truncate(struct libos_handle* hdl, file_off_t size) {
> ```

calling the new hook only in `truncate` is not enough — file length can also be extended by a write (indeed, it is the more common case)


<!-- Sent from Reviewable.io -->

2024-06-04 11:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 0 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)

___
*[`libos/src/fs/libos_fs_util.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRbCMAU4kjugh7rS1:-NzXuXcdC0jDF6Ofh_BO:bgrqwhd) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/fs/libos_fs_util.c#L255)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

calling the new hook only in `truncate` is not enough — file length can also be extended by a write (indeed, it is the more common case)
</blockquote></details>

I agree, but we don't have this semantics even in the current implementation. So I think this PR is strictly better than what we currently have.

Also, looking at our tests and example apps, seems like no app uses such a strange pattern of `mmap()` + `write(...extend...)`. Or do you have some other scenario in mind?


<!-- Sent from Reviewable.io -->

2024-06-08 16:38 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 0 of 21 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-NzshAQn5ph8iLz3cBxA:b-e9wooy) (no related file):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

it should be noted that this PR introduces a major regression: writable `MAP_SHARED` mappings that are actually shared between processes will no longer work correctly
</blockquote></details>

So, do we actually care about this? Previously this worked only on non-SGX PAL, right?

CC: @dimakuv, @kailun-qin, @oshogbo

___
___
*[`libos/src/fs/libos_fs_util.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRbCMAU4kjugh7rS1:-Nzsg1OP2uNNiFgFi69B:b-iafwom) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/fs/libos_fs_util.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree, but we don't have this semantics even in the current implementation. So I think this PR is strictly better than what we currently have.

Also, looking at our tests and example apps, seems like no app uses such a strange pattern of `mmap()` + `write(...extend...)`. Or do you have some other scenario in mind?
</blockquote></details>

Hmm, but this shouldn't be hard to add, I think? Or maybe you're worrying about the performance if we add it to each `write()`? If it's the latter, then I think it's possible to optimize it by storing more metadata so that the overhead is negligible for files which don't have any mappings.
___
*[`libos/test/ltp/manifest.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1818#-NsxYFB_5-CZoIsHyQQO:-NzsgfyI77cb8AhO0LSv:b-ysk12u) ([raw file](https://github.com/gramineproject/gramine/blob/b0194637a854afcddc42327eed52a2ca8e4936af/libos/test/ltp/manifest.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is taken from https://github.com/gramineproject/gramine/pull/1718. So I'd say that that PR is the prerequisite of this one.

This is required because LTP uses shared file-backed mmaps without explicit msyncs or munmaps (recall that Gramine requires explicit points like `msync()` and `munmap()` to synchronize mappings with file contents).
</blockquote></details>

#1718 was merged, could you rebase? Current merge base doesn't contain it.


<!-- Sent from Reviewable.io -->

2024-06-08 18:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 0 of 21 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-Nzt47in6e-UnAvlhj1h:b-ou4tbe) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, do we actually care about this? Previously this worked only on non-SGX PAL, right?

CC: @dimakuv, @kailun-qin, @oshogbo
</blockquote></details>

Yes, previously it worked only on non-SGX PAL (i.e. in `gramine-direct`).

I would say that this was a bad experience for everyone involved:
- Users were surprised that something that works on `gramine-direct` suddenly doesn't work on `gramine-sgx`, for no good reason.
- Developers were annoyed to not being able to debug mmap-related issues under `gramine-direct`.

To me, this "major regression" is actually a win. It makes mmap behavior sane and uniform.

___
___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztAHRh-dOGBH9eZ-zE):*
TODO:
```
file-growing `ftruncate()` on
```

->

```
file-growing `write()` and `ftruncate()` on
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1558 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRQD02P8LkpEw7ztX:-Nzt5KeGCfWqa11_D0WD:b-p7qipr) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/bookkeep/libos_vma.c#L1558)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this iterates over all VMAs we have in memory, not just VMAs belonging to this file; once we fix `write` to also call this function, this is likely to cause significant performance problems
</blockquote></details>

To make the claim of @mwkmwkmwk more specific:

- The `dump_vmas()` function indeed iterates over all VMAs.
- However, this function calls a `vma_filter_needs_prot_refresh()` callback on each VMA, to verify that this VMA belongs to this file (`hdl`).
- Unfortunately, we don't maintain a per-handle list of VMAs over which we could iterate. I guess this was the crux of @mwkmwkmwk's comment.

So, I generally agree with @mwkmwkmwk, but I don't see a simple way around this O(n) logic.

Btw, I added `write()` logic now.
___
*[`libos/src/fs/libos_fs_util.c` line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRbCMAU4kjugh7rS1:-Nzt9NOF4xYueHz1p75_:b-2sfhpr) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/fs/libos_fs_util.c#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but this shouldn't be hard to add, I think? Or maybe you're worrying about the performance if we add it to each `write()`? If it's the latter, then I think it's possible to optimize it by storing more metadata so that the overhead is negligible for files which don't have any mappings.
</blockquote></details>

Done.

I forgot that we already have this metadata -- `hdl->inode->num_mmapped`. I'm using that one now.
___
*[`libos/test/ltp/manifest.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/1818#-NsxYFB_5-CZoIsHyQQO:-Nzt45A_8JYSJrlvYxq_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b0194637a854afcddc42327eed52a2ca8e4936af/libos/test/ltp/manifest.template#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

#1718 was merged, could you rebase? Current merge base doesn't contain it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-08 19:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 0 of 21 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztF8ob3DqVF7JQIbYw:-NztF8ob3DqVF7JQIbYx:bgsnwnm) (no related file):*
Did a quick perf test on my (old-ish) machine.

Runtimes of the full FS pytest suite (in Gramine debug mode, non-EDMM):

- Without PR
  - direct:	4.41 seconds
  - sgx:	84.12 seconds

- With PR
  - direct:	4.63 seconds
  - sgx:	87.66 seconds


Results look reasonable to me. I guess we'll need to do a few more perf tests (in release mode, with EDMM, on different machines) before being ready for merge.

___


<!-- Sent from Reviewable.io -->

2024-06-10 01:55 UTC, mkow requested changes
> Reviewed 10 of 19 files at r1, 6 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 16 of 21 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-NzzdRGW-GzGxJ_2Mq8v:bhqow5v) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, previously it worked only on non-SGX PAL (i.e. in `gramine-direct`).

I would say that this was a bad experience for everyone involved:
- Users were surprised that something that works on `gramine-direct` suddenly doesn't work on `gramine-sgx`, for no good reason.
- Developers were annoyed to not being able to debug mmap-related issues under `gramine-direct`.

To me, this "major regression" is actually a win. It makes mmap behavior sane and uniform.
</blockquote></details>

Ok, makes sense to me.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztF8ob3DqVF7JQIbYw:-Nzzdl6z5Ho1Mil3A1Ud:b788yza) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did a quick perf test on my (old-ish) machine.

Runtimes of the full FS pytest suite (in Gramine debug mode, non-EDMM):

- Without PR
  - direct:	4.41 seconds
  - sgx:	84.12 seconds

- With PR
  - direct:	4.63 seconds
  - sgx:	87.66 seconds


Results look reasonable to me. I guess we'll need to do a few more perf tests (in release mode, with EDMM, on different machines) before being ready for merge.
</blockquote></details>

Is the slowdown caused by some specific test(s), or distributed equally? 5% is noticable, I think it should be less (or rather: I don't see why it has to be that much). OTOH, our tests are not designed to be benchmarks, so, could you try running something more suitable?

___
___
*[`libos/include/libos_vma.h` line 136 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzzfgwlBNt7sAsnvomo:-NzzfgwlBNt7sAsnvomp:baj170q) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/include/libos_vma.h#L136)):*
> ```objc
> int reload_mmaped_from_file_handle(struct libos_handle* hdl);
> 
> /* Refresh page protections of file mappings of `hdl` */
> ```

Please add a short remark why this is needed in the first place, which is: when the file size has changed.
___
*[`libos/src/fs/libos_fs_util.c` line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-Nzzg4uIC10FB1bXwHWR:-Nzzg4uIC10FB1bXwHWS:b-ymr1p7) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L152)):*
> ```C
>         return pal_to_unix_errno(ret);
> 
>     size_t to_read_size = size;
> ```

Sounds like Yoda, I assume you meant `size_to_read`?



_Code quote:_
```C
to_read_size
```
___
*[`libos/src/fs/libos_fs_util.c` line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-Nzznukv7lrD1ZEuphjE:-Nzznukv7lrD1ZEuphjF:bol6uhy) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L152)):*
> ```C
>         return pal_to_unix_errno(ret);
> 
>     size_t to_read_size = size;
> ```

I think Linux rounds the read size (or rather: map size) up to a whole page. Probably nothing relies on this, but IMO better to emulate this exactly. Right now we're leaving the padding with zeros instead of file contents.
We probably should also add a test for this? (ideally, just a subtest in one of the existing ones)
___
*[`libos/src/fs/libos_fs_util.c` line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzziMX5AHoKxBGcuPn5:-NzziMX5AHoKxBGcuPn6:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L273)):*
> ```C
>         ret = prot_refresh_mmaped_from_file_handle(hdl);
>         if (ret < 0) {
>             log_error("refresh of page protections of mmapped regions of file failed: %s",
> ```





_Suggestion:_
```C
refreshing page protections
```
___
*[`pal/include/pal/pal.h` line 426 at r1](https://reviewable.io/reviews/gramineproject/gramine/1818#-NsxYb5d8375drflWt0a:-NzzoK2c6qlo6KiM1lV3:b-82724w) ([raw file](https://github.com/gramineproject/gramine/blob/b0194637a854afcddc42327eed52a2ca8e4936af/pal/include/pal/pal.h#L426)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We may want to rename this to `PalDeviceMap()`
</blockquote></details>

Could you do that in this PR? There aren't that many places left using it.
___
*[`pal/src/pal_rtld.c` line 555 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzzllZo0bvL5jvIhJix:-NzzllZo0bvL5jvIhJiy:b-wna0bx) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/pal/src/pal_rtld.c#L555)):*
> ```C
>             goto out;
>         }
>         ret = _PalStreamRead(handle, c->map_off, map_size, map_addr);
> ```

ditto (rounding up the read size)


<!-- Sent from Reviewable.io -->

2024-06-10 08:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 10 of 27 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-O-0LvyQ5ZD5VVTdl654:bmin9ke) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, makes sense to me.
</blockquote></details>

Done from my side

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztF8ob3DqVF7JQIbYw:-O-0L4Hx5kFgTw8LIUu2:baxan17) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is the slowdown caused by some specific test(s), or distributed equally? 5% is noticable, I think it should be less (or rather: I don't see why it has to be that much). OTOH, our tests are not designed to be benchmarks, so, could you try running something more suitable?
</blockquote></details>

Ok, here are the new results. I had a couple bugs/issues in my previous quick perf test; now I think I fixed all those issues.

1. First issue was that I ran in `debug` mode. Now I run in `release` mode.
2. Second issue (main one) was that I didn't compare the `libos/test/fs/` pytest apples-to-apples. That's because this PR enables several tests which were previously (on master) disabled. So now I have a pre-requisite -- see below -- to compare apples-to-apples.
3. Third issue that I did the test only on one machine, without EDMM. Now I also show the results with EDMM.

### Pre-requisite

We compare with current master for this PR (commit cbd30b795098cd459a3e2165e9cf56f99cf2dc65).

With this PR, to compare apples-to-apples (same total number of FS tests), need to revert Pytest files:
```
git checkout cbd30b795098cd459a3e2165e9cf56f99cf2dc65 -- \
    libos/test/fs/test_fs.py \
	libos/test/fs/test_enc.py \
	libos/test/fs/test_tmpfs.py
```

### old non-EDMM machine (fast hard disk)

- without PR
  - direct: 3.79 seconds
  - sgx: 69.75 seconds

- with PR
  - direct: 4.01 seconds
  - sgx: 69.78 seconds

### new EDMM machine (slow hard disk)

- without PR
  - direct: 9.35 seconds
  - sgx (with EDMM=1): 17.04s seconds

- with PR
  - direct: 9.38s seconds
  - sgx (with EDMM=1): 17.06s seconds

**Conclusion**: Things make sense now. First, `gramine-direct` is a bit slower now because it doesn't use the "cheaty" `mmap(..., file-fd, ...)` but always uses a generic emulate-mmap-via-read-write. Second, `gramine-sgx` has exact same performance, because nothing really changed in this PR for the SGX case (except those IF checks on write/truncate).

___
___
*[`libos/include/libos_vma.h` line 136 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzzfgwlBNt7sAsnvomo:-O-059-Z70lrhVWJG2mx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/include/libos_vma.h#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a short remark why this is needed in the first place, which is: when the file size has changed.
</blockquote></details>

Done.
___
*[`libos/src/fs/libos_fs_util.c` line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-Nzzg4uIC10FB1bXwHWR:-O-05IS74O3ilG-GdhWX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds like Yoda, I assume you meant `size_to_read`?
</blockquote></details>

Done.
___
*[`libos/src/fs/libos_fs_util.c` line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-Nzznukv7lrD1ZEuphjE:-O-06bOf0kyOoTWef7Az:b-6xxsur) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think Linux rounds the read size (or rather: map size) up to a whole page. Probably nothing relies on this, but IMO better to emulate this exactly. Right now we're leaving the padding with zeros instead of file contents.
We probably should also add a test for this? (ideally, just a subtest in one of the existing ones)
</blockquote></details>

I don't understand what you mean.

Please note that this callback function gets 4KB-aligned `addr` and `size`. I added asserts now to make it explicit.

Do these asserts clear the picture now? We (1) allocate `size` zero-filled bytes, aligned to a whole page, then we (2) read as much as possible into these allocated bytes from the underlying file, and finally we (3) PROT_NONE those pages that do not cover the read-from-file bytes (whole pages).

So in a general case, it ends up like this:
1. `size / 4KB` whole pages allocated, with proper permissions (at least Read):
   a. First N pages contain the contents of the file;
   b. The last page where file contents stop (if any) gets padded with zeros;
2. Last `size / 4KB - N` pages have PROT_NONE.

This is exactly how Linux works. In fact, I believe we have enough tests for this, because that's what Glibc and many apps rely on. But if you still want a sub-test, what should it be?
___
*[`libos/src/fs/libos_fs_util.c` line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzziMX5AHoKxBGcuPn5:-O-07t6S1PxfgjAhXd8c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L273)):*
> ```C
>         ret = prot_refresh_mmaped_from_file_handle(hdl);
>         if (ret < 0) {
>             log_error("refresh of page protections of mmapped regions of file failed: %s",
> ```

Done.
___
*[`pal/include/pal/pal.h` line 426 at r1](https://reviewable.io/reviews/gramineproject/gramine/1818#-NsxYb5d8375drflWt0a:-O-0Cii46u62ErMquovR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b0194637a854afcddc42327eed52a2ca8e4936af/pal/include/pal/pal.h#L426)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you do that in this PR? There aren't that many places left using it.
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 555 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-NzzllZo0bvL5jvIhJix:-O-0AMIzC_8flp_Leym5:b3sgui4) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/pal/src/pal_rtld.c#L555)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (rounding up the read size)
</blockquote></details>

ditto, I don't understand the comment.

Similar to another place, I added the asserts to make it explicit.

Please note that implementations of `_PalStreamRead()` won't read past the end of the file. For example, for trusted files (which the PAL entrypoint must be), we have this guardrail: https://github.com/gramineproject/gramine/blob/cbd30b795098cd459a3e2165e9cf56f99cf2dc65/pal/src/host/linux-sgx/pal_files.c#L192

Also note that below (I put a "mark" comment) our code explicitly zeroes-out the unused/unread parts of the allocated memory region.
___
*[`pal/src/pal_rtld.c` line 612 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-0BJJw-9hdSxNx0LbB:-O-0BJJw-9hdSxNx0LbC:bvhlmms) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/pal/src/pal_rtld.c#L612)):*
> ```C
>          * segment allocated via _PalVirtualMemoryAlloc() is already zeroed out) */
>         if (ALLOC_ALIGN_UP(c->data_end) > c->data_end)
>             memset((void*)c [...]

2024-06-10 16:12 UTC, mkow requested changes
> Reviewed 1 of 19 files at r1, 1 of 10 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mwkmwkmwk, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztF8ob3DqVF7JQIbYw:-O-1LCBz5DsmQw91K5lb:brt05ii) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, here are the new results. I had a couple bugs/issues in my previous quick perf test; now I think I fixed all those issues.

1. First issue was that I ran in `debug` mode. Now I run in `release` mode.
2. Second issue (main one) was that I didn't compare the `libos/test/fs/` pytest apples-to-apples. That's because this PR enables several tests which were previously (on master) disabled. So now I have a pre-requisite -- see below -- to compare apples-to-apples.
3. Third issue that I did the test only on one machine, without EDMM. Now I also show the results with EDMM.

### Pre-requisite

We compare with current master for this PR (commit cbd30b795098cd459a3e2165e9cf56f99cf2dc65).

With this PR, to compare apples-to-apples (same total number of FS tests), need to revert Pytest files:
```
git checkout cbd30b795098cd459a3e2165e9cf56f99cf2dc65 -- \
    libos/test/fs/test_fs.py \
	libos/test/fs/test_enc.py \
	libos/test/fs/test_tmpfs.py
```

### old non-EDMM machine (fast hard disk)

- without PR
  - direct: 3.79 seconds
  - sgx: 69.75 seconds

- with PR
  - direct: 4.01 seconds
  - sgx: 69.78 seconds

### new EDMM machine (slow hard disk)

- without PR
  - direct: 9.35 seconds
  - sgx (with EDMM=1): 17.04s seconds

- with PR
  - direct: 9.38s seconds
  - sgx (with EDMM=1): 17.06s seconds

**Conclusion**: Things make sense now. First, `gramine-direct` is a bit slower now because it doesn't use the "cheaty" `mmap(..., file-fd, ...)` but always uses a generic emulate-mmap-via-read-write. Second, `gramine-sgx` has exact same performance, because nothing really changed in this PR for the SGX case (except those IF checks on write/truncate).
</blockquote></details>

Ok, now it makes sense, so I'm resolving :)

___
___
*[`libos/src/bookkeep/libos_vma.c` line 1558 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRQD02P8LkpEw7ztX:-O-1p5cS1iRlUlVrqpIN:bargd10) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/bookkeep/libos_vma.c#L1558)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To make the claim of @mwkmwkmwk more specific:

- The `dump_vmas()` function indeed iterates over all VMAs.
- However, this function calls a `vma_filter_needs_prot_refresh()` callback on each VMA, to verify that this VMA belongs to this file (`hdl`).
- Unfortunately, we don't maintain a per-handle list of VMAs over which we could iterate. I guess this was the crux of @mwkmwkmwk's comment.

So, I generally agree with @mwkmwkmwk, but I don't see a simple way around this O(n) logic.

Btw, I added `write()` logic now.
</blockquote></details>

One note here: in revision `r4` of this PR it doesn't trigger on all `write()` calls, only on writes to files with mappings, so it should be reasonably fast (also, see the top-level discussion about performance).
___
*[`libos/src/bookkeep/libos_vma.c` line 1530 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1t-A7BUodUEmAfa7o:-O-1t-A86zAVGl58xeTE:b3acrxu) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1530)):*
> ```C
>         size_to_prot = 0;
>     } else {
>         if (file_size - vma_info->file_offset > vma_info->length) {
> ```

ditto (see below)
___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-1ttRi5K-z0a-kC151:b-g301n7) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
> ```C
>     if (vma_info->length - size_to_prot) {
>         ret = PalVirtualMemoryProtect(vma_info->addr + size_to_prot,
>                                       vma_info->length - size_to_prot, /*prot=*/0);
> ```

Hmm, doesn't it break some invariants that `vma_info` holds different protection information than the real memory? What e.g. about `EFAULT` checks in syscalls?
___
*[`libos/src/bookkeep/libos_vma.c` line 1599 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1lvDQAX8E2SUpDAnT:-O-1lvDR3BH0d1pkJ8lC:bfu7xwr) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1599)):*
> ```C
>         /* NOTE: Unfortunately there's a data race here: the memory can be unmapped, or remapped, by
>          * another thread by the time we get to `msync`. */
>         lock(&file->inode->lock);
> ```

Are we guaranteed here that `file->inode` exists?

```C
    /* Inode associated with this dentry, or NULL. Protected by `g_dcache_lock`. */
    struct libos_inode* inode;
```

I'm always confused by that, I'm not sure when it exists and when it doesn't...
___
*[`libos/src/bookkeep/libos_vma.c` line 1608 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1olU45i6plDQpiHmH:-O-1olU45i6plDQpiHmI:b5103g5) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1608)):*
> ```C
>             size_to_msync = 0;
>         } else {
>             if (file_size - vma_info->file_offset > vma_info->length) {
> ```

That's a very long way to write `MIN()` ;)
___
*[`libos/src/bookkeep/libos_vma.c` line 1609 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1nbso1RaGuCyxasIE:-O-1nbsp837WKIlelmHQ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1609)):*
> ```C
>         } else {
>             if (file_size - vma_info->file_offset > vma_info->length) {
>                 /* file size exceeds the mmapped part in VMA, all VMA is synced */
> ```





_Suggestion:_
```C
the whole VMA is synced */
```
___
*[`libos/src/fs/libos_fs_util.c` line 152 at r3](https://reviewable.io/reviews/gramineproject/gramine/1818#-Nzznukv7lrD1ZEuphjE:-O-1NoJDD3a-Jw3n8dBg:b4q48ft) ([raw file](https://github.com/gramineproject/gramine/blob/074b34e9fed228e5c48bb197a3540229cc142cf5/libos/src/fs/libos_fs_util.c#L152)):*
Ah, I thought this function has the same semantic as `mmap()`: (quoting `man`)

> The address addr must be a multiple of the page size (but length need not be).

Our callback actually doesn't have this semantics, so there's nothing wrong here.
___
*[`libos/src/fs/chroot/encrypted.c` line 496 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ez_41OB6-LrvPI-C:-O-1ez_41OB6-LrvPI-D:b3acrxu) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/encrypted.c#L496)):*
> ```C
> 
>     if (__atomic_load_n(&hdl->inode->num_mmapped, __ATOMIC_ACQUIRE) != 0) {
>         /* If there are any mappings for the file, this will refresh their access protections. */
> ```

ditto (see below)
___
*[`libos/src/fs/chroot/encrypted.c` line 504 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1f4Rr1ElII3TLaB9i:-O-1f4Rr1ElII3TLaB9j:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/encrypted.c#L504)):*
> ```C
>         }
> 
>         /* If there are any MAP_SHARED ma [...]

2024-06-11 08:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 22 of 27 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, @mwkmwkmwk, and @oshogbo)

___
*[`libos/src/bookkeep/libos_vma.c` line 1530 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1t-A7BUodUEmAfa7o:-O-5K7Bm4kBUNn8RLNWH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1530)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (see below)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-5EMlv1241gLQxu91g:b-kwer6y) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, doesn't it break some invariants that `vma_info` holds different protection information than the real memory? What e.g. about `EFAULT` checks in syscalls?
</blockquote></details>

Hm, there good point.

I'm afraid you're correct but there's no easy way to fix this. Our VMA subsystem is not ready for such stuff. What we would need is to be able to split and merge adjacent VMAs on these callback functions. VMA 
 splitting logic exists in our code, but merging doesn't exist, see e.g. this comment: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/src/bookkeep/libos_vma.c#L99-L104

Interestingly, we have been having this same issue for ages in our checkpoint-and-restore logic: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/src/bookkeep/libos_vma.c#L1582-L1605

TLDR:
1. Your issue is legit.
2. We can easily split VMAs into two: one with normal protections, one with NONE protections.
3. **But** we cannot merge those VMAs back together (not implemented) when the `write()` or `truncate()` grows the file further.
4. So we may end up with hundreds of adjacent VMAs, slowing down everything.
5. We had the same issue in restored VMAs (for opened files in child processes); we didn't observe any issues because of that in real-world apps.

So given the above, I think we should postpone fixing this issue (for the time when we are ready to modify VMA bookkeeping code). I wrote a corresponding FIXME comment here.
___
*[`libos/src/bookkeep/libos_vma.c` line 1599 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1lvDQAX8E2SUpDAnT:-O-5965P4y3gOpc0rPe1:b-cqva69) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1599)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are we guaranteed here that `file->inode` exists?

```C
    /* Inode associated with this dentry, or NULL. Protected by `g_dcache_lock`. */
    struct libos_inode* inode;
```

I'm always confused by that, I'm not sure when it exists and when it doesn't...
</blockquote></details>

First of all, you're looking at the wrong `inode` field. What you linked is the **dentry** field: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/include/libos_fs.h#L218-L220

But here we're using the `inode` field of the **LibOS handle**: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/include/libos_handle.h#L170-L179

If the handle has an `inode`, then it always has this inode. And we are guaranteed to have an `inode` here, because `file` handle is an actual file in this function -- we know this because this function is called from `write()` and `truncate()` callbacks in the FS subsystem.
___
*[`libos/src/bookkeep/libos_vma.c` line 1608 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1olU45i6plDQpiHmH:-O-59sxkA5t20gihvL7w:b-607egh) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1608)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's a very long way to write `MIN()` ;)
</blockquote></details>

But that was on purpose, to have explicit comments what and why we're doing. Do you want me to remove these comments? I like them.
___
*[`libos/src/bookkeep/libos_vma.c` line 1609 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1nbso1RaGuCyxasIE:-O-5AGic4qiga45yIQB0:b-nsq7n0) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1609)):*
> ```C
>         } else {
>             if (file_size - vma_info->file_offset > vma_info->length) {
>                 /* file size exceeds the mmapped part in VMA, all VMA is synced */
> ```

Done. (2x)
___
*[`libos/src/fs/chroot/encrypted.c` line 496 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ez_41OB6-LrvPI-C:-O-5BLty7y9l_AmZjztQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/encrypted.c#L496)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (see below)
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 504 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1f4Rr1ElII3TLaB9i:-O-5BMNp0KOj5XOPTpnW:b7fqj51) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/encrypted.c#L504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. But here had to rephrase a bit, to make clear it will happen for MAP_SHARED mappings only
___
*[`libos/src/fs/chroot/encrypted.c` line 537 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1e2i27zkPbHogB0RS:-O-5BRIFECWw6k68Rn4F:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/encrypted.c#L537)):*
> ```C
> 
>     if (__atomic_load_n(&hdl->inode->num_mmapped, __ATOMIC_ACQUIRE) != 0) {
>         /* If there are any mappings for the file, this will refresh their access protections. */
> ```

Done.
___
*[`libos/src/fs/chroot/fs.c` line 247 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1dxUf2kEn0J25S_g8:-O-5Bhk5214-hTVXP2nI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/fs.c#L247)):*
> ```C
> 
>     if (__atomic_load_n(&hdl->inode->num_mmapped, __ATOMIC_ACQUIRE) != 0) {
>         /* If there are any mappings for the file, this will refresh their access protections. */
> ```

Done.
___
*[`libos/src/fs/chroot/fs.c` line 255 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1entqEwVpUOZjzVCR:-O-5BiOg972MhWs-hQeW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/chroot/fs.c#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/fs/tmpfs/fs.c` line 302 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1crYvDBNUpa6FyCR3:-O-5CKKC78huWw-mK729:b-c6eni2) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/fs/tmpfs/fs.c#L302)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquo [...]

2024-06-18 18:52 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 22 of 27 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRAuz3Pdfn-hfg-kI:-O-aR-kD8J2VzM9tzTtm:bhutzpm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done from my side
</blockquote></details>

very well then

___
___
*[`libos/src/bookkeep/libos_vma.c` line 1558 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRQD02P8LkpEw7ztX:-O-gg-8NCAfl4ohFk8G1:bzfkbgk) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/bookkeep/libos_vma.c#L1558)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One note here: in revision `r4` of this PR it doesn't trigger on all `write()` calls, only on writes to files with mappings, so it should be reasonably fast (also, see the top-level discussion about performance).
</blockquote></details>

I still think we should keep all VMAs of a given `libos_handle` on a linked list; however, I'm fine with this being fixed in a separate PR
___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-geftn5eS2SboaRO_H:by0h2jj) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, there good point.

I'm afraid you're correct but there's no easy way to fix this. Our VMA subsystem is not ready for such stuff. What we would need is to be able to split and merge adjacent VMAs on these callback functions. VMA 
 splitting logic exists in our code, but merging doesn't exist, see e.g. this comment: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/src/bookkeep/libos_vma.c#L99-L104

Interestingly, we have been having this same issue for ages in our checkpoint-and-restore logic: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/src/bookkeep/libos_vma.c#L1582-L1605

TLDR:
1. Your issue is legit.
2. We can easily split VMAs into two: one with normal protections, one with NONE protections.
3. **But** we cannot merge those VMAs back together (not implemented) when the `write()` or `truncate()` grows the file further.
4. So we may end up with hundreds of adjacent VMAs, slowing down everything.
5. We had the same issue in restored VMAs (for opened files in child processes); we didn't observe any issues because of that in real-world apps.

So given the above, I think we should postpone fixing this issue (for the time when we are ready to modify VMA bookkeeping code). I wrote a corresponding FIXME comment here.
</blockquote></details>

I'd propose a somewhat different handling of this.

I think we should commit to the model of "logical" split within a single VMA: some prefix of the VMA is actually active (and has valid pages), while the rest is unmapped (and returns `SIGBUS`). This is, in fact, what our code already expects in some places — see `memfault_upcall` in `libos_signal.c`, for one.

What I would propose is:

- have a `valid_end` (exact name TBD) field added to `libos_vma` and `libos_vma_info`, which is the boundary between valid area and `SIGBUS`-producing area
- have a function in `libos_vma.c` that updates that field and calls `PalVirtualMemoryProtect` as appropriate to enforce it
- check this field in `is_in_adjacent_user_vmas` so that syscalls return `-EFAULT` as appropriate

This should ensure correct semantics without too much suffering with `split_vma`.


<!-- Sent from Reviewable.io -->

2024-06-18 19:10 UTC, mkow requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 1599 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1lvDQAX8E2SUpDAnT:-O-gjQuZ3BJNGLXdedQO:b-ckhj87) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1599)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First of all, you're looking at the wrong `inode` field. What you linked is the **dentry** field: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/include/libos_fs.h#L218-L220

But here we're using the `inode` field of the **LibOS handle**: https://github.com/gramineproject/gramine/blob/42ba4806c97937c3629a93b001cc331235d088d3/libos/include/libos_handle.h#L170-L179

If the handle has an `inode`, then it always has this inode. And we are guaranteed to have an `inode` here, because `file` handle is an actual file in this function -- we know this because this function is called from `write()` and `truncate()` callbacks in the FS subsystem.
</blockquote></details>

Ok, reading this won't be needed after implementing @mwkmwkmwk's suggestion from the discussion above (we'll be able to get this info from the vma).
___
*[`libos/src/bookkeep/libos_vma.c` line 1608 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1olU45i6plDQpiHmH:-O-gh3bA1U3dylk1ZV-h:btuqtb) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1608)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But that was on purpose, to have explicit comments what and why we're doing. Do you want me to remove these comments? I like them.
</blockquote></details>

Seems overly verbose for a trivial thing to me, but won't block on this.


<!-- Sent from Reviewable.io -->

2024-06-19 14:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 1558 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NybRQD02P8LkpEw7ztX:-O-5CYuKDC0i8zuCNZvV:bwryb7w) ([raw file](https://github.com/gramineproject/gramine/blob/739b2e19516c9fcf0757c82c602d084a7182e379/libos/src/bookkeep/libos_vma.c#L1558)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I still think we should keep all VMAs of a given `libos_handle` on a linked list; however, I'm fine with this being fixed in a separate PR
</blockquote></details>

Done. Created an issue on this: https://github.com/gramineproject/gramine/issues/1917
___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-kpTBD-MkiQxZVloH1:b-ntenon) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

I'd propose a somewhat different handling of this.

I think we should commit to the model of "logical" split within a single VMA: some prefix of the VMA is actually active (and has valid pages), while the rest is unmapped (and returns `SIGBUS`). This is, in fact, what our code already expects in some places — see `memfault_upcall` in `libos_signal.c`, for one.

What I would propose is:

- have a `valid_end` (exact name TBD) field added to `libos_vma` and `libos_vma_info`, which is the boundary between valid area and `SIGBUS`-producing area
- have a function in `libos_vma.c` that updates that field and calls `PalVirtualMemoryProtect` as appropriate to enforce it
- check this field in `is_in_adjacent_user_vmas` so that syscalls return `-EFAULT` as appropriate

This should ensure correct semantics without too much suffering with `split_vma`.
</blockquote></details>

I like the proposal from @mwkmwkmwk. @mkow @kailun-qin What do you think?

If there is no hard no to this proposal, I'll cook a PR for this. That new PR will become a blocker for this PR (which I'll need to rebase on top of that one).
___
*[`libos/src/bookkeep/libos_vma.c` line 1608 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1olU45i6plDQpiHmH:-O-krsXD6gQc3f29mKyE:b-dbiejl) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1608)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems overly verbose for a trivial thing to me, but won't block on this.
</blockquote></details>

Let's keep it like this unless some other reviewer asks to modify this to `MIN()`


<!-- Sent from Reviewable.io -->

2024-06-19 14:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-l-Mj73ZgGF8afA_SP:b-9gv58c) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the proposal from @mwkmwkmwk. @mkow @kailun-qin What do you think?

If there is no hard no to this proposal, I'll cook a PR for this. That new PR will become a blocker for this PR (which I'll need to rebase on top of that one).
</blockquote></details>

+1 from my side.
___
*[`libos/src/bookkeep/libos_vma.c` line 1608 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1olU45i6plDQpiHmH:-O-l-XOUBNPzkrZfMDBF:bb74ce2) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1608)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's keep it like this unless some other reviewer asks to modify this to `MIN()`
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2024-06-19 15:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 1548 at r4](https://reviewable.io/reviews/gramineproject/gramine/1818#-O-1ttRi5K-z0a-kC150:-O-lAj45C6YdXwc668ht:bcuqwpc) ([raw file](https://github.com/gramineproject/gramine/blob/e1bef3017290eec7318bbe0581e65fb96aa5651a/libos/src/bookkeep/libos_vma.c#L1548)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 from my side.
</blockquote></details>

+1, sounds great


<!-- Sent from Reviewable.io -->

2024-06-24 13:30 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-EDMM  please

2024-06-24 13:37 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-EDMM please

2024-06-25 17:34 UTC, mkow requested changes
> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/include/libos_vma.h` line 103 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0BsCMF6wyJIz-WGs2X:-O0BsCMF6wyJIz-WGs2Y:b-a7d4fj) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/include/libos_vma.h#L103)):*
> Looks up VMA that contains `addr` and if found, updates `vma->valid_length`.

That's a bit weird semantics IMO. It allows `addr` to point anywhere within the vma, so it's not intuitive whether the length is the length from `addr` or from the beginning of the vma.
Maybe force `addr` to always point to the beginning of the mapping?
___
*[`libos/src/libos_rtld.c` line 274 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0E0NVk413892KTb9tf:-O0E0NVk413892KTb9tg:b1enagf) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/libos_rtld.c#L274)):*
> ```C
>             return ret;
>         }
>         if (valid_size != map_size) {
> ```

Why is this correct? How does this work with large .bss sections? (see the `if` below)
___
*[`libos/src/bookkeep/libos_signal.c` line 365 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0E1_bI0hifNry41oS1:-O0E1_bJ3LWlzjF2k1V8:bmrhrng) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_signal.c#L365)):*
> ```C
>             /*
>              * If the mapping exceeds end of a file then return a SIGBUS. Actually, the host
>              * environment would most probably raise SIGBUS anyway, but Gramine PAL API fuses both
> ```

Not on the SGX PAL? There it's just a `SIGSEGV` there? (and it's SGX which is our "most probable" setup)
___
*[`libos/src/bookkeep/libos_vma.c` line 176 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Em5Gr24PEuYGXU7p-:-O0Em5Gr24PEuYGXU7p0:b-y5jgpv) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L176)):*
> ```C
>  * it's called with the VMA lock held.
>  *
>  * Returns whether the traversed range was continuously covered by VMAs. This is useful for
> ```

This needs an update, a region can now be covered by VMAs but the function can return false if some `end != valid_end`.



_Code quote:_
```C
Returns whether the traversed range was continuously covered by VMAs.
```
___
*[`libos/src/bookkeep/libos_vma.c` line 194 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0ELBtb2evLuPHp8qSv:-O0ELBtb2evLuPHp8qSw:b-f7vp7f) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L194)):*
> ```C
>     assert(vma->begin <= begin);
>     struct libos_vma* prev = NULL;
>     bool is_continuous = true;
> ```

Why is this always true? (this plus the assert above)
I don't see why is that.
___
*[`libos/src/bookkeep/libos_vma.c` line 832 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0F5O41BOc-TwTSRELn:-O0F5O41BOc-TwTSRELo:b-2bfpvz) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L832)):*
> ```C
>     new_vma->begin     = (uintptr_t)addr;
>     new_vma->end       = new_vma->begin + length;
>     new_vma->valid_end = new_vma->begin + length;
> ```

Hmm, why ignoring `file` here? `valid_end` is potentially incorrect now.

Update: I see, it's updated after the real mmap? Could you add a comment here explaining that it's temporarily wrong and should be updated after the real mmap call?
___
*[`libos/src/bookkeep/libos_vma.c` line 1126 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0F5bsN2hpXFaZoc1Vk:-O0F5bsN2hpXFaZoc1Vl:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1126)):*
> ```C
> out_found:
>     new_vma->end       = max_addr;
>     new_vma->valid_end = max_addr;
> ```

ditto
___
*[`libos/src/bookkeep/libos_vma.c` line 1418 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0EPIrgE6jIOsBMd4iB:-O0EPIrgE6jIOsBMd4iC:b-6pvid2) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1418)):*
> ```C
> 
>     spinlock_lock(&vma_tree_lock);
>     bool is_continuous = _traverse_vmas_in_range(begin, end, madvise_dontneed_visitor, &ctx);
> ```

This has different semantics now regarding `-ENOMEM` on the region after the file contents. Which one is the one Linux follows?
___
*[`libos/src/bookkeep/libos_vma.c` line 1537 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FJfzs3QLEApfWyMqG:-O0FJfzs3QLEApfWyMqH:b6bjtoh) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1537)):*
> ```C
> };
> 
> static bool vma_filter_needs_prot_refresh(struct libos_vma* vma, void* _args) {
> ```

This isn't just a "filter" anymore, it updates the traversed VMAs.



_Code quote:_
```C
vma_filter
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1553 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FG4rkBLL7_iEDryQJ:-O0FG4rkBLL7_iEDryQK:b-ncl0r4) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1553)):*
> ```C
>         return false;
> 
>     /* by default, assume that file got smaller than the offset from which VMA is mapped, all VMA is
> ```

What do you mean by "by default assume [XYZ]"? This code has to handle all possible cases? What is a "default" in this context?
___
*[`libos/src/bookkeep/libos_vma.c` line 1734 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FMqvw2NxWcAP909Kw:-O0FMqvw2NxWcAP909Kx:biyvavj) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1734)):*
> ```C
>                  *
>                  * Access beyond the last file-backed page (reflected via vma->valid_length) will
>                  * cause SIGBUS. For reducing fork latency, we send only those memory contents of
> ```

Hmm, I think this sentence doesn't make sense now? The rest of the region is inaccessible anyways, there's nothing to send from it.



_Code quote:_
```C
For reducing fork latency
```
___
*[`libos/src/sys/libos_mmap.c` line 198 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0EfsQnBXvhCf1N7a8g:-O0EfsQnBXvhCf1N7a8h:b-vg3oky) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/sys/libos_mmap.c#L198)):*
> ```C
>                 uintptr_t begin = MAX((uintptr_t)addr, (uintptr_t)vma->addr);
>                 uintptr_t end = MIN((uintptr_t)vma->addr + vma->length,
>                                     (uintptr_t)addr + length);
> ```

Accidental change?
___
*[`libos/src/sys/libos_mmap.c` line 265 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0EiOsv9l4MJKMxT4Tv:-O0EiOsv9l4MJKMxT4Tw:bl8chhn) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/sys/libos_mmap.c#L265)):*
> ```C
>             if (update_valid_length_ret < 0) {
>                 log_error("[mmap] Failed to update valid length to %lu of bookkeeped memory %p-%p!",
>                         valid_length, addr, (char*)addr + length);
> ```

wrong alignment


<!-- Sent from Reviewable.io -->

2024-06-26 09:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @mwkmwkmwk)

___
*[`libos/include/libos_vma.h` line 103 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0BsCMF6wyJIz-WGs2X:-O0IeO-D5oFrSf2q8lW0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/include/libos_vma.h#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Looks up VMA that contains `addr` and if found, updates `vma->valid_length`.

That's a bit weird semantics IMO. It allows `addr` to point anywhere within the vma, so it's not intuitive whether the length is the length from `addr` or from the beginning of the vma.
Maybe force `addr` to always point to the beginning of the mapping?
</blockquote></details>

Done.
___
*[`libos/src/libos_rtld.c` line 274 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0E0NVk413892KTb9tf:-O0IfRwQD4lfHFksElJL:b-vwi69s) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/libos_rtld.c#L274)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this correct? How does this work with large .bss sections? (see the `if` below)
</blockquote></details>

This is correct.

`map_size = c->map_end - c->start` (see several lines above). Here, `c->start` is the (page-aligned) offset at which the allocation of the segment should start. And `c->map_end` is the (page-aligned) end offset at which the allocation of the segment should stop, see https://github.com/gramineproject/gramine/blob/e95a3a12112a26edc3f0cf612cc24ce5664e373e/libos/src/libos_rtld.c#L86-L115

As for BSS sections, they end up in the memory region defined by `[c->map_end, c->alloc_end)`. See https://github.com/gramineproject/gramine/blob/e95a3a12112a26edc3f0cf612cc24ce5664e373e/libos/src/libos_rtld.c#L298-L315

---

So I could relax this check to `if (valid_size > map_size) {fail}`. But for correctly-formatted ELF files, there's no need to relax. And I don't think we want to care about wrongly formatted ELFs.
___
*[`libos/src/bookkeep/libos_signal.c` line 365 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0E1_bI0hifNry41oS1:-O0IgxsADp9q5HRd5p24:bn7dzr6) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_signal.c#L365)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not on the SGX PAL? There it's just a `SIGSEGV` there? (and it's SGX which is our "most probable" setup)
</blockquote></details>

You're right. But it's not only about SGX PAL, the same happens in direct PAL. Because we emulate this "mapping exceeds end of a file" (which in Linux is a SIGBUS condition) with the "exceeds-end-of-file part of mapping has NONE permissions" (which is a SIGSEGV condition).

So my comment is plain wrong. I guess I'll just revert to the previous comment, short and precise.
___
*[`libos/src/bookkeep/libos_vma.c` line 176 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Em5Gr24PEuYGXU7p-:-O0Ij0_dBEvg2mAnDGJw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L176)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This needs an update, a region can now be covered by VMAs but the function can return false if some `end != valid_end`.
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 194 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0ELBtb2evLuPHp8qSv:-O0IjAJP6-TbUpRv9o2i:bjnm0dr) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this always true? (this plus the assert above)
I don't see why is that.
</blockquote></details>

`_lookup_vma(begin)` is guaranteed to return a VMA which address is lower than/equal to the `begin` argument.

This looked up VMA may be completely below than the `[begin, end)` region, but this bad case is covered by the IF check above.

So the only result at this point in the code is that we have a VMA which contains the `begin` address (the VMA "covers" it). Thus `assert()` is trivially true.

So I changed this line to a more obvious `assert()` + `true`. I can revert back -- there is no difference in functionality -- but I think my version shows a clearer intent of this code.
___
*[`libos/src/bookkeep/libos_vma.c` line 832 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0F5O41BOc-TwTSRELn:-O0IlF958ObhpiTIt-3Q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L832)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, why ignoring `file` here? `valid_end` is potentially incorrect now.

Update: I see, it's updated after the real mmap? Could you add a comment here explaining that it's temporarily wrong and should be updated after the real mmap call?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1126 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0F5bsN2hpXFaZoc1Vk:-O0IlFsYDZ1IS7aT2t9n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1126)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1418 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0EPIrgE6jIOsBMd4iB:-O0IotXAAhJfn4z8o_nr:b-6b4xgy) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1418)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This has different semantics now regarding `-ENOMEM` on the region after the file contents. Which one is the one Linux follows?
</blockquote></details>

TODO:
- Add a new LibOS test that tries to access a SIGBUS part of file-backed VMA and check
- what happens on e.g. `write(<all-vma>)`
- what happens on e.g. `write(<no-sigbus-part-of-memory>)`
- what happens on e.g. `write(<only-sigbus-part-of-memory>)`
- what happens on `madvise(MADV_DONTNEED, <all-vma>)`
- what happens on `madvise(MADV_DONTNEED, <no-sigbus-part-of-memory>)`
- what happens on `madvise(MADV_DONTNEED, <only-sigbus-part-of-memory>)`
___
*[`libos/src/bookkeep/libos_vma.c` line 1537 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FJfzs3QLEApfWyMqG:-O0In0HB2zC39uUrkHIr:bmucgxf) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1537)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This isn't just a "filter" anymore, it updates the traversed VMAs.
</blockquote></details>

Done.

Wasn't sure how to best rename, so just removed the `_filter_` part. But it still doesn't reflect that the `vma->valid_end` is modified here. Any suggestions are welcome.
___
*[`libos/src/bookkeep/libos_vma.c` line 1553 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FG4rkBLL7_iEDryQJ:-O0IlmVE6OOM9aeOD0iV:b-a0q0hl) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade [...]

2024-06-26 10:58 UTC, mkow reviewed
@dimakuv: Didn't you forget to push?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818#-:-O0JBb9MBixqvqakZV33:bsm7d8s)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-06-26 14:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 26 of 36 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/test/regression/mmap_file_sigbus.c` line 12 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Jt268C6gtfuWsS4ay:-O0Jt268C6gtfuWsS4az:b-pm36c6) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L12)):*
> ```C
>  *
>  *   - Behavior when using the mmapped regions as a buffer to a syscall
>  *     - specifying the whole 2-page region succeeds (writes 1 page) (yes, that's how Linux works)
> ```

...and that's what I don't know how to support in Gramine, see inline comments in that sub-test


<!-- Sent from Reviewable.io -->

2024-06-26 14:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 26 of 36 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 184 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0JtwAUBj9krTxvas8F:-O0JtwAUBj9krTxvas8G:bdngw2u) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/src/bookkeep/libos_vma.c#L184)):*
> ```C
>  *     `write(partially-valid-vma)` Linux does not return -EFAULT but instead uses the buffer until
>  *     the first invalid address. This behavior is too cumbersome to implement in Gramine + SGX,
>  *     thus on `write(partially-valid-vma)` Gramine immediately returns -EFAULT.
> ```

Enjoy: https://yarchive.net/comp/linux/partial_reads_writes.html


<!-- Sent from Reviewable.io -->

2024-06-26 17:57 UTC, mkow requested changes
> Reviewed 8 of 10 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)

___
*[`libos/src/libos_rtld.c` line 274 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0E0NVk413892KTb9tf:-O0KbTrw9nIGjSC1ctEj:b-sjvt9p) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/libos_rtld.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is correct.

`map_size = c->map_end - c->start` (see several lines above). Here, `c->start` is the (page-aligned) offset at which the allocation of the segment should start. And `c->map_end` is the (page-aligned) end offset at which the allocation of the segment should stop, see https://github.com/gramineproject/gramine/blob/e95a3a12112a26edc3f0cf612cc24ce5664e373e/libos/src/libos_rtld.c#L86-L115

As for BSS sections, they end up in the memory region defined by `[c->map_end, c->alloc_end)`. See https://github.com/gramineproject/gramine/blob/e95a3a12112a26edc3f0cf612cc24ce5664e373e/libos/src/libos_rtld.c#L298-L315

---

So I could relax this check to `if (valid_size > map_size) {fail}`. But for correctly-formatted ELF files, there's no need to relax. And I don't think we want to care about wrongly formatted ELFs.
</blockquote></details>

Oh, wait, there's a separate `alloc_end`, I missed that, sorry. It's ok as it is then.
___
*[`libos/src/bookkeep/libos_vma.c` line 194 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0ELBtb2evLuPHp8qSv:-O0KctWGCNgZox9dJStq:b-nmhxf6) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L194)):*
> `_lookup_vma(begin)` is guaranteed to return a VMA which address is lower than/equal to the `begin` argument.

Nope, the other way around:

```C
/* Returns the vma that contains `addr`. If there is no such vma, returns the closest vma with
 * higher address. */
static struct libos_vma* _lookup_vma(uintptr_t addr) {
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1537 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FJfzs3QLEApfWyMqG:-O0Keewn4W_NsiEqxs5Y:b-o40tw) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1537)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Wasn't sure how to best rename, so just removed the `_filter_` part. But it still doesn't reflect that the `vma->valid_end` is modified here. Any suggestions are welcome.
</blockquote></details>

Maybe `vma_update_valid_ends`? And just describe the return value in the comment?
___
*[`libos/src/bookkeep/libos_vma.c` line 1553 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FG4rkBLL7_iEDryQJ:-O0KfW0JAPj_OcUiQQcs:b-tbzjaw) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1553)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This "by default assume" is meant purely to explain the `valid_length = 0;` initialization. I added an empty line to make it clear that this comment is for the next line (var init) only.

Previously I had a cascade of IFs to make it even more explicit. But it looked ugly, so I did this "init variable to some case and get rid of one level of IFs".
</blockquote></details>

Maybe put it into `else` of the top-level `if` then? Then the comment would be less confusing :)
___
*[`libos/src/bookkeep/libos_vma.c` line 179 at r8](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Kc9FnE7iPHcvlRVK0:-O0Kc9FnE7iPHcvlRVK1:bc6i1u4) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L179)):*
> ```C
>  * emulating errors in memory management syscalls.
>  */
> // TODO: Probably other VMA functions could make use of this helper.
> ```

Why removing this? Aren't there any functions which could use it?
___
*[`libos/src/bookkeep/libos_vma.c` line 1754 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KfpuB5x_ywTNpiOOz:-O0KfpuC1G0jeyb6YG1z:b-7ae3h8) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/src/bookkeep/libos_vma.c#L1754)):*
> ```C
>                  * Send file-backed memory region.
>                  *
>                  * Access beyond the last file-backed page (reflected via vma->valid_length) will
> ```

we're emulating this behavior here, it wouldn't _actually_ happen if you tried it



_Suggestion:_
```C
should
```
___
*[`libos/test/regression/mmap_file.c` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0JaozpCL-ngTGXm3A9:-O0K8J4tCiDXU0qosSvp:bmzixbo) ([raw file](https://github.com/gramineproject/gramine/blob/d0c3eb026edddb6e5a520f1890a2e43e30fd5257/libos/test/regression/mmap_file.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Currently kept this test, because more tests is better? Not sure if we want to burn this test, or keep it afloat for some time (until we're sure other tests completely cover this test).
</blockquote></details>

What is missing from the other tests? More tests isn't always better, they take CI time, need maintenance and if they are of poor quality then they cause false bug reports. So, if they aren't testing anything and contain UBs like this one, then I'd rather get rid of them.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 20 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KC_rz6D4a1er1iTMA:-O0KC_rz6D4a1er1iTMB:b4qijyq) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L20)):*
> ```C
>  *     - madvise(MADV_DONTNEED) on the second 1-page region succeeds (yes, that's how Linux works)
>  *     - accessing the first 1-page region succeeds
>  *     - accessing the second 1-page region results in SIGBUS
> ```

by "accessing" you also mean madvise? or accessing from usermode after madvise was called on the region?
___
*[`libos/test/regression/mmap_file_sigbus.c` line 36 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KCloTDelwBuFjbJxA:-O0KCloTDelwBuFjbJxB:b-30o7gh) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L36)):*
> ```C
> #include <sys/types.h>
> #include <ucontext.h>
> #include <unistd.h>
> ```

Please sort.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 40 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KCr_DClmJ84o6FGfY:-O0KCr_DClmJ84o6FGfZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L40)):*
> ```C
> #include "common.h"
> 
> #define TEST_DIR  "tmp"
> ```





_Suggestion:_
```C
TEST_DIR "tmp"
```
___
*[`libos/test/regression/mmap_file_sigbus.c` line 59 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KDL2W0DGV5wU0EmZm:-O0KDL2W0DGV5wU0EmZn:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L59)):*
> ```C
>     "ret\n"
> "ret:\n"
>     "ret\n"
> ```





_Suggestion:_
```C
"ret:\n"
    "ret\n"
```
___
*[`libos/test/regression/mmap_file_sigbus.c` line 113 at r10](https://reviewable.io/reviews/gram [...]

2024-06-27 08:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/bookkeep/libos_vma.c` line 194 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0ELBtb2evLuPHp8qSv:-O0NQes35dE2_5wM506p:b1zbs75) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `_lookup_vma(begin)` is guaranteed to return a VMA which address is lower than/equal to the `begin` argument.

Nope, the other way around:

```C
/* Returns the vma that contains `addr`. If there is no such vma, returns the closest vma with
 * higher address. */
static struct libos_vma* _lookup_vma(uintptr_t addr) {
```
</blockquote></details>

Wow, my bad, I read the comment incorrectly and though that `_lookup_vma()` returns **closes vma with a lower address**. But it's actually the **higher** address. Then my change was wrong, but surprisingly it still worked on our tests...

Anyway, I reverted all that, so not relevant anymore.
___
*[`libos/src/bookkeep/libos_vma.c` line 1537 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FJfzs3QLEApfWyMqG:-O0NdkER4Qj9F9kcrCEi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1537)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe `vma_update_valid_ends`? And just describe the return value in the comment?
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 1553 at r6](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0FG4rkBLL7_iEDryQJ:-O0NXp3o0vrYb4fvFb4x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L1553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe put it into `else` of the top-level `if` then? Then the comment would be less confusing :)
</blockquote></details>

Done.
___
*[`libos/src/bookkeep/libos_vma.c` line 179 at r8](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Kc9FnE7iPHcvlRVK0:-O0NQ5QLDzZPiFZUO1ee:bj39wdq) ([raw file](https://github.com/gramineproject/gramine/blob/7ef3f8eb801d96c836491bdd4ade8a64cb91b943/libos/src/bookkeep/libos_vma.c#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why removing this? Aren't there any functions which could use it?
</blockquote></details>

Done. I reverted this. I quickly looked through this file and didn't find any functions that would clearly benefit from this func. But on the other hand, I didn't do any thorough analysis (maybe if some func is refactored to be compatible with using this func, then it would work). So let's keep the comment until someone does a proper deep analysis.
___
*[`libos/src/bookkeep/libos_vma.c` line 184 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0JtwAUBj9krTxvas8F:-O0NctdH83vOOHS2vBsq:b-qoyzxj) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/src/bookkeep/libos_vma.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Enjoy: https://yarchive.net/comp/linux/partial_reads_writes.html
</blockquote></details>

Such a good link that I also added it elsewhere (in the LibOS regression test)
___
*[`libos/src/bookkeep/libos_vma.c` line 1754 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KfpuB5x_ywTNpiOOz:-O0NZv89CF8SBUcgEjZq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/src/bookkeep/libos_vma.c#L1754)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we're emulating this behavior here, it wouldn't _actually_ happen if you tried it
</blockquote></details>

Done.
___
*[`libos/test/regression/mmap_file.c` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0JaozpCL-ngTGXm3A9:-O0Nmq7h8sVN-tthb8OD:bpf0xl3) ([raw file](https://github.com/gramineproject/gramine/blob/d0c3eb026edddb6e5a520f1890a2e43e30fd5257/libos/test/regression/mmap_file.c#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is missing from the other tests? More tests isn't always better, they take CI time, need maintenance and if they are of poor quality then they cause false bug reports. So, if they aren't testing anything and contain UBs like this one, then I'd rather get rid of them.
</blockquote></details>

Done.

The only part that we could miss a bit was the in-child test. So I modified my new `mmap_file_sigbus` test to also check this. This old and full of UBs test is removed.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 20 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KC_rz6D4a1er1iTMA:-O0N_Jr5-dim7mWM513M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

by "accessing" you also mean madvise? or accessing from usermode after madvise was called on the region?
</blockquote></details>

Done.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 36 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KCloTDelwBuFjbJxA:-O0N_mUd1-ZxYOoRzRUv:bywvmjy) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please sort.
</blockquote></details>

Done. Also removed some unneeded headers.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 59 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KDL2W0DGV5wU0EmZm:-O0N_tI79g7fvdNGQtYQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L59)):*
> ```C
>     "ret\n"
> "ret:\n"
>     "ret\n"
> ```

Done.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 113 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KEB6f8hQ-EluHzU1m:-O0NapkU6YzPc1x3nj6Q:b-7wvev0) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this value means that the read wasn't successful?
</blockquote></details>

Done. My bad phrasing, but the meaning was correct: "Read that was supposed to be successful unexpectedly returned a value that is reserved for invalid accesses". I rephrased.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 116 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KEMLeC7nUSH-5jXJy:-O0Nb-I6DMNoEGvgXMN1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KEOeV1hrblmdkrDNj:-O0Nb4zXA0LfijFqm_x0:b-896fix) ([raw file](https://github.com/gramineproject/g [...]

2024-06-27 09:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/test/regression/mmap_file_sigbus.c` line 40 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KCr_DClmJ84o6FGfY:-O0NxXqw9rL0BzrAPa0p:b-j3j9f9) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L40)):*
> ```C
> #include "common.h"
> 
> #define TEST_DIR  "tmp"
> ```

Done. Not relevant.


<!-- Sent from Reviewable.io -->

2024-06-27 14:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/fs/tmpfs/fs.c` line 278 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nx4tN3n22vfBPLYkj:-O0P2i2c1GZ-jF5ewTex:b9wqzy8) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/libos/src/fs/tmpfs/fs.c#L278)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this code sequence (and the one in `truncate`) comes up a lot; do you think we could deduplicate them?
</blockquote></details>

Good idea, but can we do it in a follow-up PR or at least when all other comments in this PR will be resolved? This change will move quite a lot of code around, which will complicate the review process.
___
*[`pal/src/pal_rtld.c` line 558 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nxil6Eo0xA0MyfTgg:-O0P2ZwfCPLa8l_4vPWV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/pal/src/pal_rtld.c#L558)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this should verify the whole thing was actually read
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-27 14:28 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/src/fs/tmpfs/fs.c` line 278 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nx4tN3n22vfBPLYkj:-O0P5KRn3OHtj6qdibVG:bol1fu1) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/libos/src/fs/tmpfs/fs.c#L278)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good idea, but can we do it in a follow-up PR or at least when all other comments in this PR will be resolved? This change will move quite a lot of code around, which will complicate the review process.
</blockquote></details>

so be it
___
*[`pal/src/pal_rtld.c` line 105 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0P56xi8s1WhoQY1xn7:-O0P56xi8s1WhoQY1xn8:bujlm4r) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L105)):*
> ```C
>     size_t got = 0;
>     while (got < count) {
>         int64_t ret = _PalStreamRead(handle, offset, count - got, (char*)buf + got);
> ```

should be `offset + got`
___
*[`pal/src/pal_rtld.c` line 594 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0P4yQv6k3woZ0sJ8e1:-O0P4yQv6k3woZ0sJ8e2:bp645e2) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L594)):*
> ```C
>             continue;
> 
>         ret = _PalVirtualMemoryAlloc((void*)c->map_end, c->alloc_end - c->map_end, c->prot);
> ```

this is no longer needed with this approach


<!-- Sent from Reviewable.io -->

2024-06-27 14:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`libos/src/fs/tmpfs/fs.c` line 278 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nx4tN3n22vfBPLYkj:-O0PA_VFBbQgHO-Dalxt:bkq9hdd) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/libos/src/fs/tmpfs/fs.c#L278)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

so be it
</blockquote></details>

https://github.com/gramineproject/gramine/issues/1931 -- not to forget. Let me put a blocking comment so I'll do it after e.g. rebase.
___
*[`pal/src/pal_rtld.c` line 105 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0P56xi8s1WhoQY1xn7:-O0PAmjZ6rReyWn_yb9-:b-c6eni2) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L105)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

should be `offset + got`
</blockquote></details>

Done. Oops, good catch.
___
*[`pal/src/pal_rtld.c` line 594 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0P4yQv6k3woZ0sJ8e1:-O0PAqrB2FIexlbC0chs:bqc5qke) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L594)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this is no longer needed with this approach
</blockquote></details>

Why are you saying this? That's for the BSS part.

Above we mmapped only `[c->start, c->map_end)` (for data and code). Now we also mmap `[c->map_end, c->alloc_end)` which is used for BSS.

We could refactor this code to only have one `_PalVirtualMemoryAlloc()`, but then we'll lose this clarify of data+code vs BSS. Additionally, we'll need to play with page protections more...

( Same question was raised in another PR: https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV )


<!-- Sent from Reviewable.io -->

2024-06-27 18:20 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/pal_rtld.c` line 574 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0PBYgG6RZbW5Ni8u7p:-O0PvMEbBhgxIcfV3-2m:bq0ncok) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L574)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just realized that this conflicts with #1820. I think I should first merge #1820 and then get rid of this `pal_stream_read_exact()`, it won't be needed (we'll use `memcpy()` instead).
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2024-06-28 08:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 28 of 36 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`pal/src/pal_rtld.c` line 594 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0P4yQv6k3woZ0sJ8e1:-O0St6n5A8HTwXWsPUMu:b-v0p7vh) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L594)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are you saying this? That's for the BSS part.

Above we mmapped only `[c->start, c->map_end)` (for data and code). Now we also mmap `[c->map_end, c->alloc_end)` which is used for BSS.

We could refactor this code to only have one `_PalVirtualMemoryAlloc()`, but then we'll lose this clarify of data+code vs BSS. Additionally, we'll need to play with page protections more...

( Same question was raised in another PR: https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV )
</blockquote></details>

Ok, this is resolved in another PR. This issue will go away when we rebase this PR on top of #1820.


<!-- Sent from Reviewable.io -->

2024-07-25 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 22 of 36 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @mwkmwkmwk)

___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1818#-NztAHRh-dOGBH9eZ-zE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO:
```
file-growing `ftruncate()` on
```

->

```
file-growing `write()` and `ftruncate()` on
```
</blockquote></details>

Done
___
*[`-- commits` line 41 at r7](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0JaGo819bYPeAgbTwv):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do: add new LibOS test `mmap_file_sigbus`.
</blockquote></details>

Done
___
*[`pal/src/pal_rtld.c` line 574 at r13](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0PBYgG6RZbW5Ni8u7p:-O2cbxqMB_6DowuRMvjW:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/5dfb69718bb06aeae0572bd11624219fce8bc00f/pal/src/pal_rtld.c#L574)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

sounds good
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-25 14:12 UTC, mkow requested changes
> Reviewed 2 of 8 files at r11, 1 of 2 files at r13, 12 of 12 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/tmpfs/fs.c` line 278 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nx4tN3n22vfBPLYkj:-O2e5ief2cpQvkWiHG3A:b-btczik) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/libos/src/fs/tmpfs/fs.c#L278)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/issues/1931 -- not to forget. Let me put a blocking comment so I'll do it after e.g. rebase.
</blockquote></details>

 @dimakuv: That's the last blocking discussion here, right? Do you plan to create the PR now, or somewhen later, after merging?
___
*[`libos/test/regression/mmap_file_sigbus.c` line 139 at r10](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0KEkr_9m09B00B8Abx:-O2eA2J3BRRo83CFItEp:bhc4zva) ([raw file](https://github.com/gramineproject/gramine/blob/54b97ad609e073381b084d74ba8475eaa631d4a3/libos/test/regression/mmap_file_sigbus.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not sure I understand your comment. We are writing to `write_fd`, which is a separate file: created plus truncated by the `open()` couple lines above.

The contents of this file are irrelevant, it's just a temporary destination for writing. We only use it as a way to use `addr_page1` and `addr_page2` (backed by **another read-only file**) as source buffers.

We don't care if we always append to `write_fd` or we perform lseek to rewind. This file will be removed afterwards anyway (see `unlink()` below).
</blockquote></details>

Ah, sorry, I mixed up reading and writing and somehow looked at this transfer in the opposite direction. Everything looks good.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 158 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAlcyDIFfpuMlCulm:-O2eAlcyDIFfpuMlCuln:b25snh5) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L158)):*
> ```C
> 
>     if (argc != 4)
>         errx(1, "Usage: %s <path1: read-only file> <path2:write-only file> <fork?>", argv[0]);
> ```

One time you put a space after the colon and the other time you didn't.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 158 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAwSP3otMeCmRI0gv:-O2eAwSP3otMeCmRI0gw:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L158)):*
> ```C
> 
>     if (argc != 4)
>         errx(1, "Usage: %s <path1: read-only file> <path2:write-only file> <fork?>", argv[0]);
> ```





_Suggestion:_
```C
<fork|nofork>
```
___
*[`libos/test/regression/mmap_file_sigbus.c` line 162 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAzA2489-ncxIhw6V:-O2eAzA2489-ncxIhw6W:b-rbuze3) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L162)):*
> ```C
>     const char* path1 = argv[1];
>     const char* path2 = argv[2];
>     bool do_fork = strcmp(argv[3], "fork") == 0;
> ```

Please don't accept random garbage here, it's too easy to introduce unnoticed bugs this way.


<!-- Sent from Reviewable.io -->

2024-07-25 16:09 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 19 files at r1, 2 of 10 files at r3, 1 of 8 files at r11, 12 of 12 files at r15.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-07-26 11:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: 35 of 36 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/tmpfs/fs.c` line 278 at r11](https://reviewable.io/reviews/gramineproject/gramine/1818#-O0Nx4tN3n22vfBPLYkj:-O2inK75CMX8Xh92gGTf:b-v953r5) ([raw file](https://github.com/gramineproject/gramine/blob/0595e70a9201059f608d0efd1f5b6218e9e3f18d/libos/src/fs/tmpfs/fs.c#L278)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: That's the last blocking discussion here, right? Do you plan to create the PR now, or somewhen later, after merging?
</blockquote></details>

Done https://github.com/gramineproject/gramine/pull/1956
___
*[`libos/test/regression/mmap_file_sigbus.c` line 158 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAlcyDIFfpuMlCulm:-O2ifCr20Cta3gg26UQr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L158)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One time you put a space after the colon and the other time you didn't.
</blockquote></details>

Done.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 158 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAwSP3otMeCmRI0gv:-O2ifDBa8N2bW-DDTDkL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L158)):*
> ```C
> 
>     if (argc != 4)
>         errx(1, "Usage: %s <path1: read-only file> <path2:write-only file> <fork?>", argv[0]);
> ```

Done.
___
*[`libos/test/regression/mmap_file_sigbus.c` line 162 at r15](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2eAzA2489-ncxIhw6V:-O2ifj2ID97mxGb2h3Ws:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f150ac3b054b98e20675f720b074169e496d009/libos/test/regression/mmap_file_sigbus.c#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't accept random garbage here, it's too easy to introduce unnoticed bugs this way.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-26 11:42 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-28 13:25 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 46 at r17](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2tVjtpAdd9gx9vlTGT):*
@dimakuv: FYI: I changed that because the old version was ambiguous (it could also mean that "there are currently just a few FS tests in general", not that you added/enabled some in this PR).



_Code quote:_
```
A few more FS tests are enabled on SGX now.
```


<!-- Sent from Reviewable.io -->

2024-07-29 01:58 UTC, kailun-qin requested changes
> Reviewed 5 of 19 files at r1, 2 of 10 files at r3, 6 of 15 files at r4, 5 of 13 files at r6, 3 of 10 files at r9, 2 of 8 files at r11, 12 of 12 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 17 at r17](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2w9GxW15ie-EFYhuyM):*
But it's `PalDeviceMap()`?



_Code quote:_
```
Only `shm` FS still uses `PalStreamMap()`
```


<!-- Sent from Reviewable.io -->

2024-07-29 06:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 17 at r17](https://reviewable.io/reviews/gramineproject/gramine/1818#-O2w9GxW15ie-EFYhuyM):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But it's `PalDeviceMap()`?
</blockquote></details>

Done. Good catch.


<!-- Sent from Reviewable.io -->

2024-07-29 06:27 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1818)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-29 09:13 UTC, merged