[PAL] Allow to validate entrypoint ELF file separately
gramineproject/gramine pull request #1820
Opened 2024-03-15 07:22 UTC by dimakuv

## Description of the changes 

Previously, the entrypoint ELF file (`loader.entrypoint` in manifest) contents were validated during file read and file mmap, just like with all other files. In particular, Linux-SGX PAL expects the entrypoint to be marked as `sgx.trusted_files` and validates its SHA256 hash during file read/mmap.

However, future commits will move handling of `sgx.trusted_files` to the LibOS layer. Thus, file read/mmap at the PAL layer will lose validation guarantees. This commit introduces a separate `loader.entrypoint_sha256` manifest option and a corresponding logic to validate the (only required) entrypoint file. A new assumption is made now, that the only file to be loaded by PAL (and not by LibOS) is this entrypoint file; this assumption can be made because the entrypoint has no dependencies.

Extracted from #1812.

Related to https://github.com/gramineproject/gramine/pull/1716 (ideally both should be merged one after another).

## How to test this PR? 

CI is enough.

2024-03-15 07:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/1820#-Nt-zqvJ-B51d0Icx713):*
Please note that this assumption is already enforced by our PAL code: https://github.com/gramineproject/gramine/blob/e3d3aa39c11054dfa3ce1ad2ce715ec24d730f1a/pal/src/pal_rtld.c#L261-L269


<!-- Sent from Reviewable.io -->

2024-03-15 08:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 0 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1820#-Nt0HuQDAyizNoX851e0:-Nt0HuQDAyizNoX851e1:b-b13pno) ([raw file](https://github.com/gramineproject/gramine/blob/4fe78ec8c66797387aa4c469cc879102a3331f5c/pal/src/host/linux-sgx/pal_misc.c#L22)):*
> ```C
> #include "pal_linux_error.h"
> #include "seqlock.h"
> #include "sgx_arch.h"
> ```

TODO: Get rid of `sgx_arch.h` and `sgx_file_hash_t`
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 834 at r1](https://reviewable.io/reviews/gramineproject/gramine/1820#-Nt0HyHi3a37YTNn1vmw:-Nt0HyHi3a37YTNn1vmx:b-mzb610) ([raw file](https://github.com/gramineproject/gramine/blob/4fe78ec8c66797387aa4c469cc879102a3331f5c/pal/src/host/linux-sgx/pal_misc.c#L834)):*
> ```C
>     }
> 
>     if (!entrypoint_sha256_str || strlen(entrypoint_sha256_str) != sizeof(sgx_file_hash_t) * 2) {
> ```

TODO: The first clause was already checked above, remove


<!-- Sent from Reviewable.io -->

2024-03-15 09:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/pal_misc.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1820#-Nt0HuQDAyizNoX851e0:-Nt0KZDn4xLLMS8Vu91f:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/4fe78ec8c66797387aa4c469cc879102a3331f5c/pal/src/host/linux-sgx/pal_misc.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: Get rid of `sgx_arch.h` and `sgx_file_hash_t`
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 834 at r1](https://reviewable.io/reviews/gramineproject/gramine/1820#-Nt0HyHi3a37YTNn1vmw:-Nt0KZu52KOEPPMyd6s7:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/4fe78ec8c66797387aa4c469cc879102a3331f5c/pal/src/host/linux-sgx/pal_misc.c#L834)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: The first clause was already checked above, remove
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-23 00:33 UTC, mkow requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXKsxW6Efqxon9KXBN):*
that's not optional, which "allow" implies



_Suggestion:_
```
[PAL] Validate entrypoint ELF file separately
```
___
*[`pal/src/pal_rtld.c` line 659 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXlgZBE-vLx7kVlanG:-NyXlgZBE-vLx7kVlanH:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L659)):*
> ```C
>     ret = _PalStreamAttributesQueryByHandle(handle, &attr);
>     if (ret < 0) {
>         log_error("Getting size of ELF file failed");
> ```





_Suggestion:_
```C
log_error("Getting size of loader entrypoint binary failed");
```
___
*[`pal/src/pal_rtld.c` line 665 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXnjCLEJdMETaDWuQ_:-NyXnjCLEJdMETaDWuQa:b-pc30n3) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L665)):*
> ```C
>     buf = malloc(attr.pending_size);
>     if (!buf) {
>         log_error("Allocating buffer to hold ELF file of size %lu failed", attr.pending_size);
> ```

ditto - missing context _which_ ELF file
actually, same for a few other places below
___
*[`pal/src/pal_rtld.c` line 672 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXpVW_78JTYrf5TEJ5:-NyXpVW_78JTYrf5TEJ6:b-9hwg4l) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L672)):*
> ```C
>     size_t remaining = attr.pending_size;
>     while (remaining > 0) {
>         int64_t read = _PalStreamRead(handle, buf_offset, remaining, buf + buf_offset);
> ```

Everything here is wrong ;) `ret` vs `read`
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 832 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXT3xtAr891nnjgECA:-NyXT3xu1l-6BGbImbVn:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/host/linux-sgx/pal_misc.c#L832)):*
> ```C
>         log_error("Cannot find 'loader.entrypoint_sha256' in manifest");
>         ret = -PAL_ERROR_INVAL;
>         goto out;
> ```





_Suggestion:_
```C
        return -PAL_ERROR_INVAL;
```
___
*[`python/graminelibos/manifest.py` line 304 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXLdni-Sx49uwPRM7S:-NyXLdni-Sx49uwPRM7T:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/python/graminelibos/manifest.py#L304)):*
> ```Python
>         if not 'entrypoint_sha256' in loader:
>             entrypoint_tf = TrustedFile.from_realpath(uri2path(loader['entrypoint'])).ensure_hash()
>             loader.setdefault('entrypoint_sha256', entrypoint_tf.sha256);
> ```





_Suggestion:_
```Python
loader['entrypoint_sha256'] = entrypoint_tf.sha256
```


<!-- Sent from Reviewable.io -->

2024-05-23 21:58 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux/pal_misc.c` line 84 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NybSPJD5cLIQB2SvQLP:-NybSPJD5cLIQB2SvQLQ:b57aj5u) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/host/linux/pal_misc.c#L84)):*
> ```C
> 
> int _PalValidateEntrypoint(const void* buf, size_t size) {
>     __UNUSED(buf);
> ```

it isn't obvious that this should be a noop — perhaps it could be a good idea to also validate `entrypoint_sha256` here if present, so that we can test the hash logic more easily, but without raising an error if the option isn't present?


<!-- Sent from Reviewable.io -->

2024-06-03 13:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 3 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @mwkmwkmwk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXKsxW6Efqxon9KXBN):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

that's not optional, which "allow" implies
</blockquote></details>

Will do during final rebase
___
*[`pal/src/pal_rtld.c` line 659 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXlgZBE-vLx7kVlanG:-NzT8Y-x5eb_xg8AFoVw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L659)):*
> ```C
>     ret = _PalStreamAttributesQueryByHandle(handle, &attr);
>     if (ret < 0) {
>         log_error("Getting size of ELF file failed");
> ```

Done.
___
*[`pal/src/pal_rtld.c` line 665 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXnjCLEJdMETaDWuQ_:-NzT8YZm5IxyUwc2v71E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L665)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - missing context _which_ ELF file
actually, same for a few other places below
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 672 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXpVW_78JTYrf5TEJ5:-NzT9b9F6OH-PPzTmAhh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/pal_rtld.c#L672)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Everything here is wrong ;) `ret` vs `read`
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_misc.c` line 84 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NybSPJD5cLIQB2SvQLP:-NzTBD5mBYusPHKvOgPH:bpvs25f) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/host/linux/pal_misc.c#L84)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

it isn't obvious that this should be a noop — perhaps it could be a good idea to also validate `entrypoint_sha256` here if present, so that we can test the hash logic more easily, but without raising an error if the option isn't present?
</blockquote></details>

I tried it but realized we can't do it -- the Linux PAL does **not** use the mbedTLS library, thus I don't have SHA256 implementation to use...

I'm currently keeping as-is. Adding mbedTLS dep for Linux PAL seems like an unrelated task.
___
*[`pal/src/host/linux-sgx/pal_misc.c` line 832 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXT3xtAr891nnjgECA:-NzT8MuT9X4a8RarmyYw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/host/linux-sgx/pal_misc.c#L832)):*
> ```C
>         log_error("Cannot find 'loader.entrypoint_sha256' in manifest");
>         ret = -PAL_ERROR_INVAL;
>         goto out;
> ```

Done.
___
*[`python/graminelibos/manifest.py` line 304 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXLdni-Sx49uwPRM7S:-NzT8Bq_DPPq9PJDVdCB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/python/graminelibos/manifest.py#L304)):*
> ```Python
>         if not 'entrypoint_sha256' in loader:
>             entrypoint_tf = TrustedFile.from_realpath(uri2path(loader['entrypoint'])).ensure_hash()
>             loader.setdefault('entrypoint_sha256', entrypoint_tf.sha256);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-04 00:07 UTC, mkow reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-06-27 14:23 UTC, mwkmwkmwk reviewed
> Reviewed 2 of 6 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0P3jrN6viIx-pY8-sW:b-rs3g02) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
> ```C
>             continue;
> 
>         ret = _PalVirtualMemoryAlloc((void*)c->map_end, c->alloc_end - c->map_end, c->prot);
> ```

this is no longer necessary
___
*[`pal/src/host/linux/pal_misc.c` line 84 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NybSPJD5cLIQB2SvQLP:-O0P3MMt16_g5_Vt4AaX:b1z9jjt) ([raw file](https://github.com/gramineproject/gramine/blob/1fd55b5a812fbd81ae961c49e55ad5974554a5ec/pal/src/host/linux/pal_misc.c#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tried it but realized we can't do it -- the Linux PAL does **not** use the mbedTLS library, thus I don't have SHA256 implementation to use...

I'm currently keeping as-is. Adding mbedTLS dep for Linux PAL seems like an unrelated task.
</blockquote></details>

ah, oops.

let's leave it like that, then


<!-- Sent from Reviewable.io -->

2024-06-27 14:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0P9IYfDPhq_eN7stMM:b-5w1qfa) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this is no longer necessary
</blockquote></details>

Why are you saying this? That's for the BSS part.

Above we mmapped only `[c->start, c->map_end)` (for data and code). Now we also mmap `[c->map_end, c->alloc_end)` which is used for BSS.

We could refactor this code to only have one `_PalVirtualMemoryAlloc()`, but then we'll lose this clarify of data+code vs BSS. Additionally, we'll need to play with page protections more...


<!-- Sent from Reviewable.io -->

2024-06-27 18:18 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0Pue8e4BYXRy4qbRER:b-45n0yu) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are you saying this? That's for the BSS part.

Above we mmapped only `[c->start, c->map_end)` (for data and code). Now we also mmap `[c->map_end, c->alloc_end)` which is used for BSS.

We could refactor this code to only have one `_PalVirtualMemoryAlloc()`, but then we'll lose this clarify of data+code vs BSS. Additionally, we'll need to play with page protections more...
</blockquote></details>

yes, that's what I mean — we can have just one allocation above, by mapping up to `alloc_end` in one go, and relying on the 0-initialization. this should simplify the code a bit.

I don't understand the bit about page protections — the whole resulting area should have uniform protection, no?


<!-- Sent from Reviewable.io -->

2024-06-28 08:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0SsDu-2toRwVqOadYr:bmcc6gk) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

yes, that's what I mean — we can have just one allocation above, by mapping up to `alloc_end` in one go, and relying on the 0-initialization. this should simplify the code a bit.

I don't understand the bit about page protections — the whole resulting area should have uniform protection, no?
</blockquote></details>

Done.

You're right. The code got simpler. Plus I also removed a code snippet (see below) that redundantly zeroed out the memory; we don't need this explicit zero-out since we rely on the implicit zero-initialization in `PalVirtualMemoryAlloc()`.
___
*[`pal/src/pal_rtld.c` line 550 at r4](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0StkqS0xNz7D84FFXH:-O0StkqS0xNz7D84FFXI:b9dr6d8) ([raw file](https://github.com/gramineproject/gramine/blob/03cea098a9b88c4c6ba49851a510d3109d4f3af2/pal/src/pal_rtld.c#L550)):*
> ```C
> 
>         assert(IS_ALLOC_ALIGNED_PTR(map_addr));
>         assert(IS_ALLOC_ALIGNED(map_size));
> ```

FYI: These two asserts are copied from #1818, they were requested by @mkow . See https://reviewable.io/reviews/gramineproject/gramine/1818#-NzzllZo0bvL5jvIhJix


<!-- Sent from Reviewable.io -->

2024-06-28 11:37 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0TcKhrDYzTpLgefY6R:bi0gtv1) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

You're right. The code got simpler. Plus I also removed a code snippet (see below) that redundantly zeroed out the memory; we don't need this explicit zero-out since we rely on the implicit zero-initialization in `PalVirtualMemoryAlloc()`.
</blockquote></details>

nice! there's two more simplifications that can be done now:

- `map_end` is no longer needed and can be removed
- it would be easier to just store `p_filesz` instead of `data_end` (`cpy_size` is effectively recomputed `p_filesz`)


<!-- Sent from Reviewable.io -->

2024-07-01 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`pal/src/pal_rtld.c` line 570 at r3](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0P3jrN6viIx-pY8-sV:-O0h7pyuAFHS3nvcO6Sp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bcbfa34ca57b3fad1c505b023ae105636e512547/pal/src/pal_rtld.c#L570)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

nice! there's two more simplifications that can be done now:

- `map_end` is no longer needed and can be removed
- it would be easier to just store `p_filesz` instead of `data_end` (`cpy_size` is effectively recomputed `p_filesz`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 08:43 UTC, llly reviewed
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0hRQBi7-Xl-x6PIxL5:-O0hRQBi7-Xl-x6PIxL6:b-m6u1op) (no related file):*
How about using `loader.entrypoint.uri` and `loader.entrypoint.sha256`?

___


<!-- Sent from Reviewable.io -->

2024-07-01 09:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly, @mkow, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0hRQBi7-Xl-x6PIxL5:-O0hbG0w2uEzAcDuNZVS:b6y1pes) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

How about using `loader.entrypoint.uri` and `loader.entrypoint.sha256`?
</blockquote></details>

I'm a bit reluctant to deprecate `loader.entrypoint` in favor of `loader.entrypoint.uri`. (See https://gramine.readthedocs.io/en/stable/manifest-syntax.html#loader-entrypoint)

This is indeed a cleaner approach. If other reviewers agree, I can do it.

___


<!-- Sent from Reviewable.io -->

2024-07-01 19:18 UTC, mwkmwkmwk reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

___
*[`pal/src/pal_rtld.c` line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0jimnODAh1-JHc5Mwx:-O0jimnODAh1-JHc5Mwy:b-w4eplr) ([raw file](https://github.com/gramineproject/gramine/blob/005781f04910e3c87b2d08a644a0c378f82ba39b/pal/src/pal_rtld.c#L88)):*
> ```C
>     elf_addr_t alloc_end;
> 
>     /* Segment's file-image size, i.e. the exact size of the segment in ELF file */
> ```

this is not quite true given the `+ (p_vaddr - align_down(p_vaddr))` part


<!-- Sent from Reviewable.io -->

2024-07-01 19:41 UTC, mwkmwkmwk reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0hRQBi7-Xl-x6PIxL5:-O0joFps43xcutjKozz8:btvf4do) (no related file):*
> How about using `loader.entrypoint.uri` and `loader.entrypoint.sha256`?

this sounds good

___


<!-- Sent from Reviewable.io -->

2024-07-01 22:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0hRQBi7-Xl-x6PIxL5:-O0kSD9n-Vnju41UjqNG:bb73djm) (no related file):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

> How about using `loader.entrypoint.uri` and `loader.entrypoint.sha256`?

this sounds good
</blockquote></details>

SGTM

___


<!-- Sent from Reviewable.io -->

2024-07-02 10:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 3 of 58 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly, @mkow, and @mwkmwkmwk)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0hRQBi7-Xl-x6PIxL5:-O0mtF3t5GyLJ3weRW-s:bswep8e) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

Done. Had to rebase to latest master, since this PR conflicted with https://github.com/gramineproject/gramine/pull/1716

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1820#-NyXKsxW6Efqxon9KXBN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`pal/src/pal_rtld.c` line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0jimnODAh1-JHc5Mwx:-O0mE5j91FX4V_iwYTGZ:b-qudrqj) ([raw file](https://github.com/gramineproject/gramine/blob/005781f04910e3c87b2d08a644a0c378f82ba39b/pal/src/pal_rtld.c#L88)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

this is not quite true given the `+ (p_vaddr - align_down(p_vaddr))` part
</blockquote></details>

Done, reformulated. I don't know how to say it better without going into those page-alignment explanations. There is a trick for the OS kernel to effectively share pages belonging to a file from which the segments are loaded, and I don't want to describe this. See:
- https://stackoverflow.com/a/69068474/6325371
- https://stackoverflow.com/a/5105840/6325371


<!-- Sent from Reviewable.io -->

2024-07-02 15:27 UTC, mkow requested changes
> Reviewed 55 of 55 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @llly, and @mwkmwkmwk)

___
*[`pal/src/pal_main.c` line 571 at r7](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0o-lwd5NGgADe38xr-:-O0o-lwd5NGgADe38xr0:b-bukotu) ([raw file](https://github.com/gramineproject/gramine/blob/97e831c1551261ce09d9a4dd5afe18cfd52ec116/pal/src/pal_main.c#L571)):*
> ```C
>     if (ret < 0) {
>         /* didn't find `loader.entrypoint.uri`, try deprecated `loader.entrypoint`;
>          * TODO: remove this in Gramine v1.9 */
> ```

missing deprecation warning?


<!-- Sent from Reviewable.io -->

2024-07-03 02:45 UTC, llly reviewed
> Reviewed 55 of 55 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-07-03 06:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 57 of 58 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly, @mkow, and @mwkmwkmwk)

___
*[`pal/src/pal_main.c` line 571 at r7](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0o-lwd5NGgADe38xr-:-O0rEbRH2VTJyQuvlOFN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/97e831c1551261ce09d9a4dd5afe18cfd52ec116/pal/src/pal_main.c#L571)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing deprecation warning?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-03 07:55 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-07-03 17:30 UTC, mwkmwkmwk reviewed
> Reviewed 53 of 55 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`python/graminelibos/manifest.py` line 342 at r8](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0tdNcS3ULYtNpB3F-7:-O0tdNcS3ULYtNpB3F-8:b-ud3l7n) ([raw file](https://github.com/gramineproject/gramine/blob/ac1a307f9e41afb6b23cf42270b43e78a79f5f46/python/graminelibos/manifest.py#L342)):*
> ```Python
>         # `loader.entrypoint.sha256`; replace with the default LibOS
>         loader = manifest.setdefault('loader', {})
>         loader_entrypoint = loader.setdefault('entrypoint', {})
> ```

shouldn't we have legacy syntax handling here?


<!-- Sent from Reviewable.io -->

2024-07-04 07:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 55 of 59 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @llly, @mkow, and @mwkmwkmwk)

___
*[`python/graminelibos/manifest.py` line 342 at r8](https://reviewable.io/reviews/gramineproject/gramine/1820#-O0tdNcS3ULYtNpB3F-7:-O0wIGvr9WxYkyD2pi2q:b-rb1yt6) ([raw file](https://github.com/gramineproject/gramine/blob/ac1a307f9e41afb6b23cf42270b43e78a79f5f46/python/graminelibos/manifest.py#L342)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

shouldn't we have legacy syntax handling here?
</blockquote></details>

Done.

Good catch. If I have an old syntax in the manifest template, I get an error:
```shell
~/gramineproject/gramine/CI-Examples/helloworld$ git diff --unified=0
diff --git a/CI-Examples/helloworld/helloworld.manifest.template b/CI-Examples/helloworld/helloworld.manifest.template
@@ -5,0 +6 @@
+loader.entrypoint = "blabla"

~/gramineproject/gramine/CI-Examples/helloworld$ make
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
Traceback (most recent call last):
  ...
  File "/home/dimakuv/gramineproject/gramine/built-debug/lib/python3.8/site-packages/graminelibos/manifest.py", line 344, in _
_init__
    loader_entrypoint['uri'] = f'file:{_env.globals["gramine"]["libos"]}'
TypeError: 'str' object does not support item assignment
```

Fixed now.


<!-- Sent from Reviewable.io -->

2024-07-05 11:48 UTC, mwkmwkmwk reviewed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`python/graminelibos/manifest_check.py` line 62 at r9](https://reviewable.io/reviews/gramineproject/gramine/1820#-O11iChM4Zzn7osQQOXn:-O11iChNBE0zD4SMrb8q:bgxtbsx) ([raw file](https://github.com/gramineproject/gramine/blob/e4056a14b1822bbfb0f562de240caa843766dd1b/python/graminelibos/manifest_check.py#L62)):*
> ```Python
>     Required('loader'): {
>         # TODO: validator for sha256
>         Required('entrypoint'): {'uri': _uri, 'sha256': str},
> ```

should the `'uri'` also be `Required`?


<!-- Sent from Reviewable.io -->

2024-07-08 07:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: 58 of 59 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk)

___
*[`python/graminelibos/manifest_check.py` line 62 at r9](https://reviewable.io/reviews/gramineproject/gramine/1820#-O11iChM4Zzn7osQQOXn:-O1G9JvX-Tgc4mizR63p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e4056a14b1822bbfb0f562de240caa843766dd1b/python/graminelibos/manifest_check.py#L62)):*
<details><summary><i>Previously, mwkmwkmwk (Marcelina Kościelnicka) wrote…</i></summary><blockquote>

should the `'uri'` also be `Required`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 17:05 UTC, mkow approved these changes
> Reviewed 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-16 03:26 UTC, kailun-qin approved these changes
> Reviewed 3 of 6 files at r1, 52 of 55 files at r7, 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-24 14:22 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-24 15:09 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1820)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-24 18:03 UTC, merged