[PAL] Print a nice error if enclave range collides with other regions
gramineproject/gramine pull request #1826
Opened 2024-03-23 13:06 UTC by mkow

## Description of the changes 

Previously, if enclave size was very large (e.g. 2TB) its collision with some hardcoded memory regions in untrusted memory (ASan shadow map, debug info area, untrusted shared memory) caused allocation failures, leading to cryptic errors.
This commit fixes that and checks all the ranges for collisions.

The lack of these checks was _not_ a security issue, because:
- ASan range is used only in debug builds
- debug range is used also in release, but only by the untrusted PAL
- shared memory range allocation would fail in ocall_mmap_untrusted() before leaving the enclave (on pointer check)

Fixes #1787.

## How to test this PR? 

Modify some enclave size to e.g. 2TB. Outputs from my runs:

debug, 2TB, no fix:
```
> gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
fish: Job 1, 'gramine-sgx helloworld' terminated by signal SIGKILL (Forced quit)
```

asan, 2TB, no fix:

```
> gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Allocation of EPC memory failed: File exists (EEXIST)
```

debug, 2TB, fix:

```
> gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Enclave range collides with shared memory or debug range. This is most likely caused by too large enclave size.
error: load_enclave() failed with error: Invalid argument (EINVAL)
```

asan, 2TB, fix:

same as debug, because ASan range is checked afterwards and it's further in memory than debug range. After commenting out debug and shared range checks:

```
> gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Enclave range collides with ASan range. This is most likely caused by too large enclave size.
error: load_enclave() failed with error: Invalid argument (EINVAL)
```

2024-04-02 00:45 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFCtg-RHLAy5LmEI6):*
-> `PAL/Linux-SGX`



_Code quote:_
```
PAL
```
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuREo8-8wO-mekip17_):*
-> `),`



_Code quote:_
```
) 
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 284 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFTDs6HG8pT7J2qkh:-NuRFTDs6HG8pT7J2qki:b-hb45c7) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L284)):*
> ```C
>                           DBGINFO_ADDR, DBGINFO_ADDR + sizeof(struct enclave_dbginfo))) {
>         log_error("Enclave range collides with shared memory or debug range. This is most likely "
>                   "caused by too large enclave size.");
> ```

What about a more actionable message, e.g., `... Consider reducing enclave size`?



_Code quote:_
```C
        log_error("Enclave range collides with shared memory or debug range. This is most likely "
                  "caused by too large enclave size.");
```
___
*[`pal/src/host/linux-sgx/host_main.c` line 292 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRG-cA5PonhQSo2m7K:-NuRG-cA5PonhQSo2m7L:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L292)):*
> ```C
>     if (ranges_overlap(enclave->baseaddr, enclave->baseaddr + enclave->size,
>                        ASAN_SHADOW_START, ASAN_SHADOW_START + ASAN_SHADOW_LENGTH)) {
>         log_error("Enclave range collides with ASan range. This is most likely caused by too large "
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-04-02 01:20 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_main.c` line 299 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRO-Hk954IdaUnOs2A:-NuRO-Hk954IdaUnOs2B:b-rfki8w) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L299)):*
> ```C
>     #endif
> ```

redundant empty line?


<!-- Sent from Reviewable.io -->

2024-04-02 10:03 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/host_main.c` line 284 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFTDs6HG8pT7J2qkh:-NuTFScKC_lDNaOgpk_V:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L284)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about a more actionable message, e.g., `... Consider reducing enclave size`?
</blockquote></details>

+1
___
*[`pal/src/host/linux-sgx/host_main.c` line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuTFczc01j6qfYfd9-z:-NuTFczc01j6qfYfd90-:b-pwndgc) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L289)):*
> ```C
> 
>     }
>     #ifdef ASAN
> ```

We have such macro IFs starting from the first char of the line (i.e. no spaces)
___
*[`pal/src/host/linux-sgx/host_main.c` line 297 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuTFiyI5O_BC4r_YBKN:-NuTFiyI5O_BC4r_YBKO:bm41noq) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L297)):*
> ```C
>         goto out;
>     }
>     #endif
> ```

ditto (no spaces)


<!-- Sent from Reviewable.io -->

2024-04-09 01:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: 2 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFCtg-RHLAy5LmEI6):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `PAL/Linux-SGX`
</blockquote></details>

Will do at rebase.
___
*[`pal/src/host/linux-sgx/host_main.c` line 284 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFTDs6HG8pT7J2qkh:-Nv-XFo3EEn93RrNZ59e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 289 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuTFczc01j6qfYfd9-z:-Nv-XPgK5FKRfToZIssW:b-9yy7en) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have such macro IFs starting from the first char of the line (i.e. no spaces)
</blockquote></details>

Right, done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 292 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRG-cA5PonhQSo2m7K:-Nv-XRqe43fklCrxVInY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L292)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 297 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuTFiyI5O_BC4r_YBKN:-Nv-XSs03JGn1ZnWXaB0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L297)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (no spaces)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_main.c` line 299 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRO-Hk954IdaUnOs2A:-Nv-XWoUE15_1epVXbo6:b-3gnhxz) ([raw file](https://github.com/gramineproject/gramine/blob/c7400c32c21206c3858ffd1e7c3486a5b8456618/pal/src/host/linux-sgx/host_main.c#L299)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

redundant empty line?
</blockquote></details>

Oops, didn't notice, fixed. Punishment for using `--word-diff=color` when self-reviewing before pushing :grimacing: 


<!-- Sent from Reviewable.io -->

2024-04-09 04:21 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-04-09 08:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-09 08:14 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1826#-NuRFCtg-RHLAy5LmEI6):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will do at rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-04-09 09:00 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1826)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-09 11:02 UTC, merged