[Docs] Add more documentation about SGX
gramineproject/gramine pull request #1827
Opened 2024-03-24 14:24 UTC by mkow

## Description of the changes 

As in the title. Still not complete, but it's already a lot of changes, so I'd prefer to do the rest in a follow-up PR.

## How to test this PR? 

Render the docs and read.

2024-03-26 07:25 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`Documentation/sgx-intro.rst` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttS_e4ABkBZB_thcHo:-NttS_e4ABkBZB_thcHp:bylumss) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L23)):*
> ```reStructuredText
> 
> SGX is still being developed. The current (March 2024) version of CPU features
> is referred to as ":term:`SGX2`" or simply "SGX" and is more or less finalized.
> ```

can we remove this now?



_Code quote:_
```reStructuredText
and is more or less finalized
```
___
*[`Documentation/sgx-intro.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttbmBi-WIZlXQIwCQK:-NttbmBi-WIZlXQIwCQL:bkxtsek) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L40)):*
> ```reStructuredText
> security model:
> 
> - Merkle Tree for memory integrity checking was removed, each page is now signed
> ```

-> `tree`



_Code quote:_
```reStructuredText
Tree
```
___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NttcsI26PPbT7vyNSQ1:b-c22ae6) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
> ```reStructuredText
> 
> - Merkle Tree for memory integrity checking was removed, each page is now signed
>   separately.
> ```

what is this "each page is now signed separately"?



_Code quote:_
```reStructuredText
- Merkle Tree for memory integrity checking was removed, each page is now signed
  separately.
```
___
*[`Documentation/sgx-intro.rst` line 277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttXq_t8-sud7Yv8gzH:-NttXq_t8-sud7Yv8gzI:b-9q5ghx) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L277)):*
> ```reStructuredText
>    ECALL
> 
>       A function call made by non-enclave world into an enclave.
> ```

add a `special`?



_Code quote:_
```reStructuredText
function
```
___
*[`Documentation/sgx-intro.rst` line 283 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttWEm72H4pxtVkrWJd:-NttWEm72H4pxtVkrWJe:b-nyrnho) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L283)):*
> ```reStructuredText
>       An instance of SGX TEE, residing in a contiguous chunk of usermode address
>       space (``ELRANGE``) of some process on the system. Application threads
>       may enter the enclave through dedicated CPU instructions. Code running
> ```

enter and exit



_Code quote:_
```reStructuredText
enter
```
___
*[`Documentation/sgx-intro.rst` line 305 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttY90j4tROjTjE8Uot:-NttY90j4tROjTjE8Uou:bubwp8c) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L305)):*
> ```reStructuredText
>    EPCM
> 
>       An undocumented part of :term:`PRM` which holds metadata about EPC pages.
> ```

it's doc'ed in SDM volume 3 section 34.5.1 (it also gives a more precise intro)



_Code quote:_
```reStructuredText
undocumented
```
___
*[`Documentation/sgx-intro.rst` line 442 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttXvOJ1fQD6EZOo3ED:-NttXvOJ1fQD6EZOo3EE:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L442)):*
> ```reStructuredText
>    OCALL
> 
>       A function call made by an enclave to the non-enclave world.
> ```

ditto



_Code quote:_
```reStructuredText
function
```
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NttSyb85MwxH0CVRvXK:b357sbu) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
> ```reStructuredText
>    PRM
> 
>       An undocumented region of physical address space reserved by the BIOS for
> ```

I think it's documented (at least in e.g., Intel SGX Programming Reference, actually elsewhere), just not in SDM.



_Code quote:_
```reStructuredText
undocumented
```
___
*[`Documentation/sgx-intro.rst` line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttQaMq9Amxho-Kx2qh:-NttQaMq9Amxho-Kx2qi:b-28ltxy) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L541)):*
> ```reStructuredText
>       Enclave` (and the :term:`Provisioning Enclave` if required). The enclave
>       then may send the collected attestation evidence to the local or remote
>       party, which will verify the evidence and confirm the correctness of the
> ```

-> `authenticity and integrity`?



_Code quote:_
```reStructuredText
correctness
```


<!-- Sent from Reviewable.io -->

2024-04-02 11:27 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @mkow)

___
*[`Documentation/sgx-intro.rst` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttS_e4ABkBZB_thcHo:-NuTVj8W94ycYGfGFWxY:bh4zdqp) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L23)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

can we remove this now?
</blockquote></details>

I would also drop this.
___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NuTVxlw1yEX-bDdovnI:bu7d1y1) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

what is this "each page is now signed separately"?
</blockquote></details>

+1, `signed` is a weird term. IIRC, currently Intel SGX relies on Intel TME for encryption, and Intel TME uses AES-XTS. I think a safer phrase would be `each page is integrity-protected separately`
___
*[`Documentation/sgx-intro.rst` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTXzda3YFyRlGP-MQP:-NuTXzda3YFyRlGP-MQQ:b-gh3ygl) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L258)):*
> ```reStructuredText
>       principle this is a |~| special version of :term:`SDK`/:term:`PSW` that
>       has a |~| reference launch enclave and is backed by the SGX driver with
>       DCAP support.
> ```

I don't understand the last sentence at all (even in the old version). Can we just remove it, as it looks completely irrelevant to current DCAP (which is attestation only)?
___
*[`Documentation/sgx-intro.rst` line 305 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttY90j4tROjTjE8Uot:-NuTYWqO2jfmVXr3U_rH:b-f5pk9f) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L305)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

it's doc'ed in SDM volume 3 section 34.5.1 (it also gives a more precise intro)
</blockquote></details>

+1, it is documented but it is **micro-architectural** which means that Intel reserves the right to change it in future CPUs. I would just remove the word "undocumented".
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NuTYov02aIijMgil4N7:b4yafwe) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think it's documented (at least in e.g., Intel SGX Programming Reference, actually elsewhere), just not in SDM.
</blockquote></details>

+1 (remove the word "undocumented")
___
*[`Documentation/sgx-intro.rst` line 595 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTZ0sMBrl3HnghY4ND:-NuTZ0sMBrl3HnghY4NE:bn2d356) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L595)):*
> ```reStructuredText
>       after the release of the original :term:`SGX1`.
> 
>       Encompasses at least :term:`EDMM`, but is still work in progress.
> ```

I would remove this paragraph completely (it's incorrect now, and you describe it in the intro)


<!-- Sent from Reviewable.io -->

2024-04-04 10:45 UTC, woju requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NucdwT9BHNE7vjxpxHn:bl18tdq) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
> currently Intel SGX relies on Intel TME for encryption

@dimakuv Would you care to suggest a short description and/or "seealso" for Intel TME? I think this term is missing on our page.
___
*[`Documentation/sgx-intro.rst` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgqGVAxZFjHs8iLTg:-NucgqGVAxZFjHs8iLTh:b-eay6l2) ([raw file](https://github.com/gramineproject/gramine/blob/0ee48eebb24c38bdad193fa9945a3b26d4a89dc6/Documentation/sgx-intro.rst#L119)):*
> ```reStructuredText
>   https://lore.kernel.org/lkml/20191223094614.GB16710@zn.tnic/
> 
> The chronicle of kernel patchset:
> ```

[NB] IDK what others think, but I'd say this chronicle can be now removed. It was useful ~2 years ago, but one needs now to refer to this, and it's incomplete (there are more revisions after v30).
___
*[`Documentation/sgx-intro.rst` line 277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgYnH401TdEnRyj6K:-NucgYnH401TdEnRyj6L:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L277)):*
> ```reStructuredText
>    ECALL
> 
>       A function call made by non-enclave world into an enclave.
> ```





_Suggestion:_
```reStructuredText
A |~| function
```
___
*[`Documentation/sgx-intro.rst` line 297 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgL9E9sWvLw75Br6W:-NucgL9E9sWvLw75Br6X:by3ij3c) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L297)):*
> ```reStructuredText
>    EPC
> 
>       A part of :term:`PRM` used for caching enclave pages. :term:`EPC` is only
> ```

and maybe elsewhere



_Suggestion:_
```reStructuredText
A |~| part
```
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-Nucg-hA-mfakGqkJFnh:b-3d0saf) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 (remove the word "undocumented")
</blockquote></details>

If it's documented, then I think link to the docs should be in `.. seealso::`
___
*[`Documentation/devel/building.rst` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucZNOED5xkmQa3Rqcv:-NucZNOED5xkmQa3Rqcw:bkvxbje) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/devel/building.rst#L86)):*
> ```reStructuredText
>       EOF
>     udevadm trigger
> ```

One, much of that is unneeded since systemd 248 (`jammy`/22.04, PR systemd/systemd#18944 merged March 2021, so 2 months after the original section in sgx-intro was dated):
https://github.com/systemd/systemd/blob/19e980eb92d923a25f0cbc38b945c282bc5f5b1b/sysusers.d/basic.conf.in#L35
https://github.com/systemd/systemd/blob/19e980eb92d923a25f0cbc38b945c282bc5f5b1b/rules.d/50-udev-default.rules.in#L57-L58

Rules for `sgx_provision` are shipped by one of DCAP packages from `intel-sgx` repo. What you need is `gpasswd -a` for `sgx` only, and `sgx_prv` is out of scope for Gramine, this is relevant when doing provisioning. You can point to the relevant DCAP documentation.

Two, this is for installation, not only for building, so if you insist on saving something from this section, you can add `gpasswd -a $USER sgx` to installation instructions, not here (`gpasswd -a` is idempotent, no need to `2>/dev/null || :` it). But really this should be in some tutorial/intro guide, should we have one, because of that provisioning thingy, which doesn't really fit any of our documents.


<!-- Sent from Reviewable.io -->

2024-04-04 11:30 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NucrFZW6eSKMKQijYCJ:bgtd1eo) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
> Intel TME (Intel Total Memory Encryption): A memory encryption/decryption engine using an ephemeral platform key designed to encrypt memory contents exposed externally from the SoC.

This is taken from one of the official Intel docs.
___
*[`Documentation/sgx-intro.rst` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgqGVAxZFjHs8iLTg:-NucrTpV5sZmfLBFAQGg:b-gjpbho) ([raw file](https://github.com/gramineproject/gramine/blob/0ee48eebb24c38bdad193fa9945a3b26d4a89dc6/Documentation/sgx-intro.rst#L119)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

[NB] IDK what others think, but I'd say this chronicle can be now removed. It was useful ~2 years ago, but one needs now to refer to this, and it's incomplete (there are more revisions after v30).
</blockquote></details>

Yeah, I also think it can be removed now.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NucrhoR-InyWP7pHgyr:b7lr1e5) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If it's documented, then I think link to the docs should be in `.. seealso::`
</blockquote></details>

https://www.intel.com/content/dam/develop/external/us/en/documents/329298-002-629101.pdf -- see Chapter 6.11 "Interactions with memory configuration and various memory ranges"
___
*[`Documentation/devel/building.rst` line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucZNOED5xkmQa3Rqcv:-NucrsLf09OHJAWhRJAA:bl7hg1n) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/devel/building.rst#L86)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

One, much of that is unneeded since systemd 248 (`jammy`/22.04, PR systemd/systemd#18944 merged March 2021, so 2 months after the original section in sgx-intro was dated):
https://github.com/systemd/systemd/blob/19e980eb92d923a25f0cbc38b945c282bc5f5b1b/sysusers.d/basic.conf.in#L35
https://github.com/systemd/systemd/blob/19e980eb92d923a25f0cbc38b945c282bc5f5b1b/rules.d/50-udev-default.rules.in#L57-L58

Rules for `sgx_provision` are shipped by one of DCAP packages from `intel-sgx` repo. What you need is `gpasswd -a` for `sgx` only, and `sgx_prv` is out of scope for Gramine, this is relevant when doing provisioning. You can point to the relevant DCAP documentation.

Two, this is for installation, not only for building, so if you insist on saving something from this section, you can add `gpasswd -a $USER sgx` to installation instructions, not here (`gpasswd -a` is idempotent, no need to `2>/dev/null || :` it). But really this should be in some tutorial/intro guide, should we have one, because of that provisioning thingy, which doesn't really fit any of our documents.
</blockquote></details>

I would remove this completely.


<!-- Sent from Reviewable.io -->

2024-04-10 16:18 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: 0 of 2 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1827#-Nv7ms0qA53BSe6J9ZYi:-Nv7ms0rBpSC9138hvuq:bg6xymx) (no related file):*
Probably unrelated to the PR, but the preview seems broken: https://gramine--1827.org.readthedocs.build/en/1827/sgx-intro.html - the warning at the top covers the whole document.
@woju ^

___
___
*[`Documentation/sgx-intro.rst` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttS_e4ABkBZB_thcHo:-Nv7Q4l84JBW6gaK1pbY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also drop this.
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttbmBi-WIZlXQIwCQK:-Nv7QAWs56BYvCQhf1F8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L40)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `tree`
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-Nv7QIoYB-5KCRD1Zmpu:bzaedzw) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Intel TME (Intel Total Memory Encryption): A memory encryption/decryption engine using an ephemeral platform key designed to encrypt memory contents exposed externally from the SoC.

This is taken from one of the official Intel docs.
</blockquote></details>

Done.

Should I add the TME term definition to this doc?
___
*[`Documentation/sgx-intro.rst` line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgqGVAxZFjHs8iLTg:-Nv7Qe4p7gxyuPO6Cx41:b-ioa1fy) ([raw file](https://github.com/gramineproject/gramine/blob/0ee48eebb24c38bdad193fa9945a3b26d4a89dc6/Documentation/sgx-intro.rst#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I also think it can be removed now.
</blockquote></details>

I agree, done. I was thinking about it, but wasn't sure if it's already the time or not yet.
___
*[`Documentation/sgx-intro.rst` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTXzda3YFyRlGP-MQP:-Nv7R7v2-xLecUcd2oFE:bn2fwe2) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the last sentence at all (even in the old version). Can we just remove it, as it looks completely irrelevant to current DCAP (which is attestation only)?
</blockquote></details>

Right, it's weird. Should I keep that it's a special version of SDK/PSW? (please check the current version)
___
*[`Documentation/sgx-intro.rst` line 277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttXq_t8-sud7Yv8gzH:-Nv7RK3B5a6HHd_HbEvm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L277)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

add a `special`?
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 277 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgYnH401TdEnRyj6K:-Nv7RNgU7O_C_AKPWgBD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L277)):*
> ```reStructuredText
>    ECALL
> 
>       A function call made by non-enclave world into an enclave.
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 283 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttWEm72H4pxtVkrWJd:-Nv7RlKq038x380EP7d-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L283)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

enter and exit
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 297 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NucgL9E9sWvLw75Br6W:-Nv7Rrl280v577f-EB3G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L297)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

and maybe elsewhere
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 305 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttY90j4tROjTjE8Uot:-Nv7dZFT-oddjbIbiYyO:baprksl) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L305)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, it is documented but it is **micro-architectural** which means that Intel reserves the right to change it in future CPUs. I would just remove the word "undocumented".
</blockquote></details>

Hmm, you're right, I must have missed that, fixed (although it's in 34.20, not 34.5.1 in my version).
___
*[`Documentation/sgx-intro.rst` line 442 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttXvOJ1fQD6EZOo3ED:-Nv7duPM-GVQcVpuGqMp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L442)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-Nv7eOwrBVSLl49Ufj6Y:b-p4k0in) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://www.intel.com/content/dam/develop/external/us/en/documents/329298-002-629101.pdf -- see Chapter 6.11 "Interactions with memory configuration and various memory ranges"
</blockquote></details>

Hmm, does it say anything more that it exists and is configured through MSRs? I don't even see a list of its contents. The table in 3.5 (Figure 3-3) doesn't count, it lists 4 "different" regions, all marked as reserved and EPC ;) It's not even clear if EPCM is a part of it or not, or how much space is available for EPC.
___
*[`Documentation/sgx-intro.rst` line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttQaMq9Amxho-Kx2qh:-Nv7gETK6Terfyrk8YW-:b38tqqg) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L541)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `authenticity and integrity`?
</blockquote></details>

right, much better
___
*[`Documentation/sgx-intro.rst` line 595 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTZ0sMBrl3HnghY4ND:-Nv7gXM_EUDmKO_vJ5yL:b43msx2) ([raw file](https://github.com/gramineproject/gramine/blob/10448364 [...]

2024-04-11 03:02 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-Nv9evHs05MLSNyWI2_H:b-3by9zy) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
> currently Intel SGX relies on Intel TME for encryption, and Intel TME uses AES-XTS.

But AES-XTS alone does not provide integrity guarantee?

> each page is integrity-protected separately

I don't think it's in page granularity. IIRC, on Ice lake, we don't even have crypto-based integrity -- we only have memory alias checking by using ECC bits. While on sappire rapids, we have MAC-based integrity. But both should be in cache-line granularity. However, I'm not sure if it's doc'ed somewhere and pls correct me if I'm wrong.

> Should I add the TME term definition to this doc?

Maybe not? We did not mention TME anywhere and I'm not if users really want to dive into such details.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvA28hi3kTQOYJMc5JS:b-iaphxq) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
> Hmm, does it say anything more that it exists and is configured through MSRs? I don't even see a list of its contents.

It says "The exact layout of the PRM and EPC are model-specific, and depend on BIOS settings". Well, at least the terminology of PRM and simple explanations are doc'ed :).

> It's not even clear if EPCM is a part of it or not, or how much space is available for EPC.

Then it's about this sentence -- "Known to contain at least :term:`EPC` and :term:`EPCM`". But since we use the wording "known", I think we're fine here.


<!-- Sent from Reviewable.io -->

2024-04-11 06:47 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NvAsPjR501k-HvXBQwk:bhlbxnz) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
> > Should I add the TME term definition to this doc?
> 
> Maybe not? We did not mention TME anywhere and I'm not if users really want to dive into such details.

Yes, I guess we don't need to mention Intel TME. It's not directly exposed/relevant to end users.

> IIRC, on Ice lake, we don't even have crypto-based integrity -- we only have memory alias checking by using ECC bits. While on sappire rapids, we have MAC-based integrity. But both should be in cache-line granularity.

That's correct (that's also my understanding). Indeed, the `each page is now integrity-protected separately` is not absolutely correct. Maybe `enclave pages are now integrity-protected by other means`? This is vague, but also kinda highlights that this is a micro-architectural detail that may change from CPU generation to CPU generation.
___
*[`Documentation/sgx-intro.rst` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTXzda3YFyRlGP-MQP:-NvAtD8F4WLUn0sgmPQ4:bkl51h5) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L258)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Right, it's weird. Should I keep that it's a special version of SDK/PSW? (please check the current version)
</blockquote></details>

Yeah, I would remove the whole sentence (`In principle this is ...`). I don't know what this sentence means -- DCAP is just a bunch of additional libraries + tools like PCCS and PKIRetrieval. DCAP is *not* a differently compiled/distributed SDK/PSW, it's more like an add-on to the base libs/tools.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvAtof55LGZL_Q5DQTj:b9g1a0m) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Hmm, does it say anything more that it exists and is configured through MSRs? I don't even see a list of its contents.

It says "The exact layout of the PRM and EPC are model-specific, and depend on BIOS settings". Well, at least the terminology of PRM and simple explanations are doc'ed :).

> It's not even clear if EPCM is a part of it or not, or how much space is available for EPC.

Then it's about this sentence -- "Known to contain at least :term:`EPC` and :term:`EPCM`". But since we use the wording "known", I think we're fine here.
</blockquote></details>

I'm unclear, what's the discussion here? From my perspective, there is enough info in official documentation to remove the word `undocumented` -- PRM is the term used in BIOS, it is described to contain EPC and EPCM. Why it's "undocumented" then? Or I would also be fine with a rewording to `largely undocumented`.


<!-- Sent from Reviewable.io -->

2024-04-11 15:10 UTC, woju requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1827#-Nv7ms0qA53BSe6J9ZYi:-NvCE-QP2gmu35N8c0dY:b7nh5lr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Probably unrelated to the PR, but the preview seems broken: https://gramine--1827.org.readthedocs.build/en/1827/sgx-intro.html - the warning at the top covers the whole document.
@woju ^
</blockquote></details>

I wouldn't pay much attention to that, those warnings are stupid, some node inserted into parse tree and yolo: https://github.com/readthedocs/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/external_version_warning.py#L60. `doctools` parse trees react badly to such attempts. I don't think we're in business of correcting for other people's parsers.

___
___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NvCL5nt4vRAL3-w92ba:b-t92q69) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> > Should I add the TME term definition to this doc?
> 
> Maybe not? We did not mention TME anywhere and I'm not if users really want to dive into such details.

Yes, I guess we don't need to mention Intel TME. It's not directly exposed/relevant to end users.

> IIRC, on Ice lake, we don't even have crypto-based integrity -- we only have memory alias checking by using ECC bits. While on sappire rapids, we have MAC-based integrity. But both should be in cache-line granularity.

That's correct (that's also my understanding). Indeed, the `each page is now integrity-protected separately` is not absolutely correct. Maybe `enclave pages are now integrity-protected by other means`? This is vague, but also kinda highlights that this is a micro-architectural detail that may change from CPU generation to CPU generation.
</blockquote></details>

I'd err on the side of including more info, even if very specific, so I'd at least say something that this Intel TME is used for integrity protection.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvCHni393Yj_CIF--1r:b-5o0du2) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm unclear, what's the discussion here? From my perspective, there is enough info in official documentation to remove the word `undocumented` -- PRM is the term used in BIOS, it is described to contain EPC and EPCM. Why it's "undocumented" then? Or I would also be fine with a rewording to `largely undocumented`.
</blockquote></details>

I have no position about "documented" vs "undocumented" vs "partially documented" or any other variation, but "implementation specific" to me means that there isn't documentation available publicly. So IDK. All of those would be OK with sufficient explanation. Can we say "The exact layout is implementation specific, but contains at least ..."?

An in any case I'd still like this document linked, and sections 3.5 and 6.11 pointed to.
___
*[`Documentation/sgx-intro.rst` line 376 at r2](https://reviewable.io/reviews/gramineproject/gramine/1827#-NvCHJXG4OzWarRxpFo7:-NvCHJXHCBHr3OTs2BOs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c829eb2b8f792981b52c5b09d438c92e80e12b1d/Documentation/sgx-intro.rst#L376)):*
> ```reStructuredText
>    OCALL
> 
>       A special function call made by an enclave to the non-enclave world.
> ```





_Suggestion:_
```reStructuredText
A |~| special 
```


<!-- Sent from Reviewable.io -->

2024-04-11 23:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: 1 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NvEPeGH0Cxq7QmFFpIp:bozj64b) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd err on the side of including more info, even if very specific, so I'd at least say something that this Intel TME is used for integrity protection.
</blockquote></details>

So, it uses exactly the same mechanism as TDX, i.e. either no integrity at all (just a single bit in this special RAM segment, but that's also inside RAM, so it's not really defending against malicious/spoofed RAM) or this simple 26-bit MAC per cacheline? (which is also stored inside RAM)
Doesn't this mean that you can replay with cacheline granularity? (because the MAC is also stored in RAM)
If so, then IMO we should say it explicitly.
___
*[`Documentation/sgx-intro.rst` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NuTXzda3YFyRlGP-MQP:-NvENX4y5XKkkIFRaEW8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I would remove the whole sentence (`In principle this is ...`). I don't know what this sentence means -- DCAP is just a bunch of additional libraries + tools like PCCS and PKIRetrieval. DCAP is *not* a differently compiled/distributed SDK/PSW, it's more like an add-on to the base libs/tools.
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvENw6F8OfBLbM7879b:bcegofl) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
Ok, changed to "mostly undocumented".

> From my perspective, there is enough info in official documentation to remove the word `undocumented` -- PRM is the term used in BIOS, it is described to contain EPC and EPCM.

Not really, this EPCM knowledge is derived indirectly / guessed / reverse engineered. I weren't able to find this stated in the official docs. The official docs only say "PRM exists and EPC is a part of it" and that's all, which for me is basically the same as "undocumented" ;)

> Can we say "The exact layout is implementation specific, but contains at least ..."?

No, it's not about layout. We don't even know what things are a part of it and what not. Is Merkle tree in old SGX there? Is EPCM really there? etc.

> An in any case I'd still like this document linked, and sections 3.5 and 6.11 pointed to.

Does it make sense? It literally doesn't say anything except that it exists, which doesn't seem useful at all for the reader...
___
*[`Documentation/sgx-intro.rst` line 376 at r2](https://reviewable.io/reviews/gramineproject/gramine/1827#-NvCHJXG4OzWarRxpFo7:-NvENgiH1L6Vc20qgZ3O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c829eb2b8f792981b52c5b09d438c92e80e12b1d/Documentation/sgx-intro.rst#L376)):*
> ```reStructuredText
>    OCALL
> 
>       A special function call made by an enclave to the non-enclave world.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-12 08:42 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvGSQN77hEapL314uCq:b-yxv9np) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, changed to "mostly undocumented".

> From my perspective, there is enough info in official documentation to remove the word `undocumented` -- PRM is the term used in BIOS, it is described to contain EPC and EPCM.

Not really, this EPCM knowledge is derived indirectly / guessed / reverse engineered. I weren't able to find this stated in the official docs. The official docs only say "PRM exists and EPC is a part of it" and that's all, which for me is basically the same as "undocumented" ;)

> Can we say "The exact layout is implementation specific, but contains at least ..."?

No, it's not about layout. We don't even know what things are a part of it and what not. Is Merkle tree in old SGX there? Is EPCM really there? etc.

> An in any case I'd still like this document linked, and sections 3.5 and 6.11 pointed to.

Does it make sense? It literally doesn't say anything except that it exists, which doesn't seem useful at all for the reader...
</blockquote></details>

"A mostly undocumented [...]. The best docs we know are: [...]"? IDK at this point.  I'll resolve here, but I think tt wouldn't hurt to add this link. I'm neutral in this specific case, but generally I think we should include pointers to most of the relevant docs, if we know them. Or at least something that people can ddg to know more.


<!-- Sent from Reviewable.io -->

2024-04-12 11:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/sgx-intro.rst` line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttSyb85MwxH0CVRvXJ:-NvH38uR-afgsclgyflo:b-34bvt5) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L455)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"A mostly undocumented [...]. The best docs we know are: [...]"? IDK at this point.  I'll resolve here, but I think tt wouldn't hurt to add this link. I'm neutral in this specific case, but generally I think we should include pointers to most of the relevant docs, if we know them. Or at least something that people can ddg to know more.
</blockquote></details>

Dunno, in other places we don't link to relevant docs (because that would be a lot of effort and occupy quite some space) despite that it would be much more useful there than here. Here it would just be "look, we aren't lying that there are no docs", which isn't super helpful. So, I don't see why we should add a link here but not to other places.


<!-- Sent from Reviewable.io -->

2024-04-12 13:51 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NvHZm2UDKXNJsNFnJX6:b8nrfg5) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, it uses exactly the same mechanism as TDX, i.e. either no integrity at all (just a single bit in this special RAM segment, but that's also inside RAM, so it's not really defending against malicious/spoofed RAM) or this simple 26-bit MAC per cacheline? (which is also stored inside RAM)
Doesn't this mean that you can replay with cacheline granularity? (because the MAC is also stored in RAM)
If so, then IMO we should say it explicitly.
</blockquote></details>

@mkow I asked SGX experts, awaiting reply.


<!-- Sent from Reviewable.io -->

2024-04-27 23:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`Documentation/sgx-intro.rst` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/1827#-NttcsI26PPbT7vyNSQ0:-NwWuWKZ55rxJvUe6k_a:b5boab9) ([raw file](https://github.com/gramineproject/gramine/blob/104483647782276c5c32ddaef409577f7f1d42a6/Documentation/sgx-intro.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So, SGX experts explained to me:
- Yes, the mechanism for SGX is now exactly the same as used for TDX.
- Integrity and anti-replay protection from **software-based attacks** is implemented via PRMRR protections (basically, the attacker cannot access enclave pages from untrusted/other enclaves).
- Integrity and anti-replay protection from **software-based attacks on swapped out pages** was implemented in SGXv1 and is still relevant -- using Version Array pages (VA pages) used in EWB/ELD flows.
- There is no anti-replay protection from **hardware-based attacks** on any new machines.
- There is optional integrity protection from **hardware-based attacks** starting from Sapphire Rapids (but *not* on Icelake) servers. This can be enabled in BIOS (disabled by default), named smth like `SGX Integrity protection`. The status of this optional feature is reflected in SGX attestation. It uses 28 ECC bits per cache line to store the HMAC.

> Doesn't this mean that you can replay with cacheline granularity?

Yes, that's correct (assuming you're on SPR or later platform and the integrity protection is enabled in BIOS).
</blockquote></details>

Thanks for double checking this! Seems we got it right in the discussion, modulo 26 vs 28 bits (I didn't remember that detail exactly).
I updated the text, please check.


<!-- Sent from Reviewable.io -->

2024-04-29 10:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`Documentation/sgx-intro.rst` line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/1827#-NwcyWkG6zDav7J_BxGf:-NwdV1KX6I2kXt-eMyXe:br265es) ([raw file](https://github.com/gramineproject/gramine/blob/ec0ee8efd1d54d686e4f7f6e80f0a27b7aaf60fd/Documentation/sgx-intro.rst#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How do we want to go about other CPU generations and variants? I am sure we will forget about this list after a month, and won't update it.

We can add another item and say smth vague about "To learn about the protections in other Intel CPUs, please refer to corresponding official documentation."
</blockquote></details>

I'd keep it because it's hard to find it in the official docs and it's quite an important change in the security guarantees. My plan was to later update this to just say "Sapphire Rapids and newer", after we know what security model is implemented is the next iteration.


<!-- Sent from Reviewable.io -->

2024-04-29 11:31 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-04-29 11:41 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-29 15:16 UTC, woju approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-29 15:25 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-30 14:53 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-30 15:59 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1827)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-30 17:58 UTC, mkow commented
Jenkins, retest Jenkins-SGX-Sanitizers please (`tests/test_sgx_sign.py::test_sign_from_pem_path` failed, known bug)

2024-04-30 18:54 UTC, merged