[mbedtls] Upgrade mbedTLS to version 3.6.0
gramineproject/gramine pull request #1832
Opened 2024-04-02 08:45 UTC by kailun-qin

## Description of the changes 
This commit introduces the following changes along with the upgrade of mbedTLS to version 3.6.0:
* updating the sonames of mbedTLS-produced libs;
* using the uploaded release asset from the release tag instead of the GitHub-generated one to avoid the involvement of Git submodules;
* updating the subproject name from `mbedtls-mbedtls-` to `mbedtls-` in accordance with the above asset change;
* initializing PSA crypto in `ra-tls-mbedtls` example and `secret-prov` libs, required for TLS 1.3 -- enabled by default since this mbedTLS version.

This mbedTLS version includes fixes for CVE-2024-28755, CVE-2024-28836 and CVE-2024-28960.

## How to test this PR? 
CI

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1832)

2024-04-02 08:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz_KmCAxsl4e-kVkl):*
Pls see https://github.com/Mbed-TLS/mbedtls/blob/30978ec6507c0a0376ae041fa333a2f24b0c09b8/README.md#L59 and https://github.com/Mbed-TLS/mbedtls/issues/8993 for details.



_Code quote:_
```
  * using the uploaded release asset from the release tag instead of the
    GitHub-generated one to avoid the involvement of Git submodules;
```
___
*[`subprojects/mbedtls-3.6.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz5Eb57YkKwpNhBXI:-NuSz5Eb57YkKwpNhBXJ:b-k2m6ok) ([raw file](https://github.com/gramineproject/gramine/blob/98d77e70fe4695f6221fd024d007a2636263e2ec/subprojects/mbedtls-3.6.0.wrap#L4)):*
> ```
> directory = mbedtls-3.6.0
> source_url = https://github.com/Mbed-TLS/mbedtls/releases/download/v3.6.0/mbedtls-3.6.0.tar.bz2
> source_fallback_url = https://packages.gramineproject.io/distfiles/mbedtls-3.6.0.tar.bz2
> ```

@woju: would you pls help mirror this file? I'll test it afterwards.

Before that, pls take a look if the change of the release asset source url makes sense to you. Thanks!



_Code quote:_
```
https://packages.gramineproject.io/distfiles/mbedtls-3.6.0.tar.bz2
```


<!-- Sent from Reviewable.io -->

2024-04-03 03:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 0 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuX1gry268i8tSgfpqI):*
Pls see https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0 and https://github.com/Mbed-TLS/mbedtls/commit/27eb68d29588937741ed89fd4f395a37c20b2ac6 for details.



_Code quote:_
```
enabled by default since this mbedTLS version
```


<!-- Sent from Reviewable.io -->

2024-04-04 10:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 0 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`subprojects/mbedtls-3.6.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz5Eb57YkKwpNhBXI:-NucitU873-_j1oGl7Gm:b-5gvn71) ([raw file](https://github.com/gramineproject/gramine/blob/98d77e70fe4695f6221fd024d007a2636263e2ec/subprojects/mbedtls-3.6.0.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: would you pls help mirror this file? I'll test it afterwards.

Before that, pls take a look if the change of the release asset source url makes sense to you. Thanks!
</blockquote></details>

Done.
Judging by the mbedtls release (https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0), This is the Way.

Did anyone recreate this tarball to see if it's legit? (\*cough\* xz \*cough\*).


<!-- Sent from Reviewable.io -->

2024-04-04 13:34 UTC, dimakuv reviewed
> Reviewed 7 of 7 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHpeYCk0isw32Zrrk:-NudHpeYCk0isw32Zrrl:bb9s7b) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/client.c#L171)):*
> ```C
>     psa_status_t status = psa_crypto_init();
>     if (status != PSA_SUCCESS) {
>         mbedtls_fprintf(stderr, "Failed to initialize PSA Crypto implementation: %d\n",
> ```

We just use `mbedtls_printf("...")` in this example code, let's stick with this.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 174 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHa7z4bFszzv34ox9:-NudHa7z4bFszzv34oxA:bhfa40s) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/client.c#L174)):*
> ```C
>                         (int)status);
>         ret = 1;
>         goto exit;
> ```

We are in the initialization phase here, you can just do `return 1;`
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHvps4s3wF-wO_w29:-NudHvps4s3wF-wO_w2A:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/server.c#L109)):*
> ```C
>     psa_status_t status = psa_crypto_init();
>     if (status != PSA_SUCCESS) {
>         mbedtls_fprintf(stderr, "Failed to initialize PSA Crypto implementation: %d\n",
> ```

ditto
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHxU8EJu1Zp2JDHyf:-NudHxU9EsMwKCJTVinX:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/server.c#L112)):*
> ```C
>                         (int)status);
>         ret = 1;
>         goto exit;
> ```

ditto
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudIYbq4dM5IRAnfH1I:-NudIYbq4dM5IRAnfH1J:bsjed4i) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L44)):*
> ```objc
> #define MBEDTLS_SSL_CLI_C
> #define MBEDTLS_SSL_CONTEXT_SERIALIZATION
> #define MBEDTLS_SSL_PROTO_TLS1_2
> ```

Don't we want to add `MBEDTLS_SSL_PROTO_TLS1_3` and `MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE`?

I'm not sure if this is important for the in-PAL mbedtls version though...


<!-- Sent from Reviewable.io -->

2024-04-05 14:21 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 7 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 171 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHpeYCk0isw32Zrrk:-NuiaAMd-2FN0srDbpaK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/client.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We just use `mbedtls_printf("...")` in this example code, let's stick with this.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/client.c` line 174 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHa7z4bFszzv34ox9:-NuiaB326VIkb0_J1oe9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/client.c#L174)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We are in the initialization phase here, you can just do `return 1;`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHvps4s3wF-wO_w29:-NuiaC2y-_HP4S2k_V5R:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/server.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-mbedtls/src/server.c` line 112 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudHxU8EJu1Zp2JDHyf:-NuiaCLI1yCzmr_JEgdH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/CI-Examples/ra-tls-mbedtls/src/server.c#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`subprojects/mbedtls-3.6.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz5Eb57YkKwpNhBXI:-NuiaFK8DVB-0fxM5XvM:bemx1ld) ([raw file](https://github.com/gramineproject/gramine/blob/98d77e70fe4695f6221fd024d007a2636263e2ec/subprojects/mbedtls-3.6.0.wrap#L4)):*
> Did anyone recreate this tarball to see if it's legit? (\*cough\* xz \*cough\*).

:)
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudIYbq4dM5IRAnfH1I:-NuiaHkq3BUk5KkqkedC:b-chceti) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L44)):*
> I'm not sure if this is important for the in-PAL mbedtls version though...

+1, I think we should evaluate the exact impact first

> Don't we want to add `MBEDTLS_SSL_PROTO_TLS1_3` and `MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE`?

Due to the above reason, I'm not sure whether we should do this in this PR which we consider as a general upgrade.


<!-- Sent from Reviewable.io -->

2024-04-05 20:24 UTC, dimakuv reviewed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1832#-NujvjfR3kRK20LHN0Vw:-NujvjfR3kRK20LHN0Vx:bc1td9p) (no related file):*
Why is this PR marked as draft?

___
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudIYbq4dM5IRAnfH1I:-NujvblO8SHFf_8ljYfr:b-kzbyl0) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L44)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> I'm not sure if this is important for the in-PAL mbedtls version though...

+1, I think we should evaluate the exact impact first

> Don't we want to add `MBEDTLS_SSL_PROTO_TLS1_3` and `MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE`?

Due to the above reason, I'm not sure whether we should do this in this PR which we consider as a general upgrade.
</blockquote></details>

Can you add the two defines as commented out and add a TODO comment to analyze their impact?


<!-- Sent from Reviewable.io -->

2024-04-08 04:17 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 10 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1832#-NujvjfR3kRK20LHN0Vw:-NuvmfuQDhonyXwNW-4f:b-vw6t48) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this PR marked as draft?
</blockquote></details>

Because the previous version failed our ra-tls-mbedtls EPID sample (due to some issues when curl is using mbedTLS as the TLS backend). Pls see the update.

___
___
*[`-- commits` line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nuvl0Wd-6iQQmnS5Ve9):*
Pls see the check added in mbedtls since v3.6.0 -- https://github.com/Mbed-TLS/mbedtls/commit/b422cab052b51ec84758638d6783d6ba4fc60613 (https://github.com/Mbed-TLS/mbedtls/blob/v3.5.2/library/ssl_tls.c#L1357-L1359, https://github.com/Mbed-TLS/mbedtls/blob/v3.6.0/library/ssl_tls.c#L1379-L1386).

Also see the related code snippet in libcurl: https://github.com/curl/curl/blob/860cd5fc2dc8e165fadd2c19a9b7c73b3ae5069d/lib/vtls/mbedtls.c#L605-L641 for details.

I may upstream this to curl if it makes sense.



_Code quote:_
```
  * patching curl-8.7.1 (mbedTLS backend) to fix a bug of calling
    `mbedtls_ssl_setup()` without RNG provided.
```
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 44 at r4](https://reviewable.io/reviews/gramineproject/gramine/1832#-NudIYbq4dM5IRAnfH1I:-Nuvkp6tEYK43n9_QG_q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ad3f053c7effc04bb790c1616df3180dbedb4516/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add the two defines as commented out and add a TODO comment to analyze their impact?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-08 08:05 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nuvl0Wd-6iQQmnS5Ve9):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls see the check added in mbedtls since v3.6.0 -- https://github.com/Mbed-TLS/mbedtls/commit/b422cab052b51ec84758638d6783d6ba4fc60613 (https://github.com/Mbed-TLS/mbedtls/blob/v3.5.2/library/ssl_tls.c#L1357-L1359, https://github.com/Mbed-TLS/mbedtls/blob/v3.6.0/library/ssl_tls.c#L1379-L1386).

Also see the related code snippet in libcurl: https://github.com/curl/curl/blob/860cd5fc2dc8e165fadd2c19a9b7c73b3ae5069d/lib/vtls/mbedtls.c#L605-L641 for details.

I may upstream this to curl if it makes sense.
</blockquote></details>

The patch looks correct to me. Please send it to the curl community. I'd like to hear their opinion before we merge this PR (with this patch).
___
*[`subprojects/packagefiles/curl-8.7.1/compile.sh` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuwicwzEJwUlz11RWns:-NuwicwzEJwUlz11RWnt:b-fww6uw) ([raw file](https://github.com/gramineproject/gramine/blob/23c2ad6c8b7b6a34c9bc6daaffa13c1e34103983/subprojects/packagefiles/curl-8.7.1/compile.sh#L24)):*
> ```Shell
> rm -rf "$PRIVATE_DIR"
> cp -ar "$CURRENT_SOURCE_DIR" "$PRIVATE_DIR"
> patch -p1 --directory "$PRIVATE_DIR" <"$CURRENT_SOURCE_DIR"/curl-8.7.1.patch
> ```

Not blocking, but I prefer a space after `<`
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuwhoH_2aBBvxE5I4Ng:-NuwhoH_2aBBvxE5I4Nh:b-vysqfz) ([raw file](https://github.com/gramineproject/gramine/blob/23c2ad6c8b7b6a34c9bc6daaffa13c1e34103983/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L10)):*
> ```objc
> #pragma once
> 
> /* mbedTLS v3.6.0 has below related TLS 1.3 features enabled by default.
> ```

This is hard to read. Also, isn't it just a recommendation from the mbedTLS team? Maybe:
```
mbedTLS v3.6.0 recommends to enable the following TLS 1.3 features:

#define ...

These features are currently *not* enabled in mbedTLS version used for internal Gramine PAL crypto/TLS.
TODO: analyze their impact ...
```


<!-- Sent from Reviewable.io -->

2024-04-08 14:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 11 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nuvl0Wd-6iQQmnS5Ve9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The patch looks correct to me. Please send it to the curl community. I'd like to hear their opinion before we merge this PR (with this patch).
</blockquote></details>

Done, it's merged: https://github.com/curl/curl/commit/b679efc0bb62a608e067c8954e7ef3d3f04ae491. Pls see the updated comment.
___
*[`subprojects/packagefiles/curl-8.7.1/compile.sh` line 24 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuwicwzEJwUlz11RWns:-Nuy6QNY80m_7Ibj9JYl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/23c2ad6c8b7b6a34c9bc6daaffa13c1e34103983/subprojects/packagefiles/curl-8.7.1/compile.sh#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but I prefer a space after `<`
</blockquote></details>

Done.
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuwhoH_2aBBvxE5I4Ng:-Nuy62UF4coYM74O4g0N:b-ogw545) ([raw file](https://github.com/gramineproject/gramine/blob/23c2ad6c8b7b6a34c9bc6daaffa13c1e34103983/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L10)):*
> isn't it just a recommendation from the mbedTLS team?

I cannot tell it's recommended. From release note, it's just enabled by default: https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0.

Anyway, updated the wording following the suggestions (just w/o "recommends to").


<!-- Sent from Reviewable.io -->

2024-04-08 17:14 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[`-- commits` line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nuvl0Wd-6iQQmnS5Ve9):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done, it's merged: https://github.com/curl/curl/commit/b679efc0bb62a608e067c8954e7ef3d3f04ae491. Pls see the updated comment.
</blockquote></details>

Scary how fast it was merged :)


<!-- Sent from Reviewable.io -->

2024-04-13 14:40 UTC, mkow requested changes
> Reviewed 1 of 5 files at r5, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz_KmCAxsl4e-kVkl):*
> The `development` branch and the `mbedtls-3.6` long-term support branch of Mbed TLS use a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules) ([framework](https://github.com/Mbed-TLS/mbedtls-framework)). This is not needed to merely compile the library at a release tag. This is not needed to consume a release archive (zip or tar).

This sounds like building from the tags should still work, and only their development branches have submodules? (sounds weird, but that's how I understand it)
Asking because I'd prefer to rely on the repository/GitHub-autogenerated artifacts instead of manually uploaded artifacts, see e.g. the xz backdoor :) Ofc assuming this works on tags / is not too annoying to do.
___
*[`-- commits` line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/1832#-NvMs2-ABSr-x8uScEXP):*
Bugfixes for these vulns don't seem urgent, maybe we could wait for the next Curl release, so we wouldn't need to ship that additional patching of Curl?
___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/1832#-NvMqZU5CQ-SPmPwtlWK:-NvMqZU5CQ-SPmPwtlWL:b-dbm26c) ([raw file](https://github.com/gramineproject/gramine/blob/8945eddc12126ef53427384364661d5e7319f3ff/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L10)):*
> ```objc
> #pragma once
> 
> /* mbedTLS v3.6.0 enables the following TLS 1.3 features:
> ```

Otherwise it seems to contradict the next sentence.



_Suggestion:_
```objc
mbedTLS v3.6.0 by default enables the following TLS 1.3 features:
```


<!-- Sent from Reviewable.io -->

2024-04-16 21:32 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz_KmCAxsl4e-kVkl):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The `development` branch and the `mbedtls-3.6` long-term support branch of Mbed TLS use a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules) ([framework](https://github.com/Mbed-TLS/mbedtls-framework)). This is not needed to merely compile the library at a release tag. This is not needed to consume a release archive (zip or tar).

This sounds like building from the tags should still work, and only their development branches have submodules? (sounds weird, but that's how I understand it)
Asking because I'd prefer to rely on the repository/GitHub-autogenerated artifacts instead of manually uploaded artifacts, see e.g. the xz backdoor :) Ofc assuming this works on tags / is not too annoying to do.
</blockquote></details>

No, `mbedtls-3.6` is not development branch, it's for 3.6.1, 3.6.2 etc. versions. The tags are against commits on this `mbedtls-3.6` branch, and autogenerated tarballs miss the abovementioned "framework" module:
```diff
@@ -134,10 +108,12 @@
 mbedtls-3.6.0/doxygen/input/doc_tcpip.h
 mbedtls-3.6.0/doxygen/input/doc_x509.h
 mbedtls-3.6.0/doxygen/mbedtls.doxyfile
-mbedtls-3.6.0/framework/
+mbedtls-3.6.0/framework/CMakeLists.txt
+mbedtls-3.6.0/framework/exported.make
+mbedtls-3.6.0/framework/.gitignore
+mbedtls-3.6.0/framework/LICENSE
+mbedtls-3.6.0/framework/README.md
 mbedtls-3.6.0/.gitattributes
-mbedtls-3.6.0/.github/
-mbedtls-3.6.0/.github/ISSUE_TEMPLATE/
 mbedtls-3.6.0/.github/ISSUE_TEMPLATE/bug_report.md
 mbedtls-3.6.0/.github/ISSUE_TEMPLATE/config.yml
 mbedtls-3.6.0/.github/ISSUE_TEMPLATE/feature_request.md
```

So you can't build from that tarball, you can't even `git submodule update` the tree from the update tarball (because that requires working git repo). It's unusable.


<!-- Sent from Reviewable.io -->

2024-05-24 03:56 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 10 of 15 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/1832#-NvMs2-ABSr-x8uScEXP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@kailun-qin: I just merged your PR updating curl, can you update this PR accordingly and drop the patch?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-27 00:10 UTC, mkow requested changes
> Reviewed 4 of 7 files at r1, 2 of 4 files at r4, 2 of 5 files at r5, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @woju)

___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 151 at r8](https://reviewable.io/reviews/gramineproject/gramine/1832#-NyrMfhU2b61cTk-VOzD:-NyrMfhU2b61cTk-VOzE:b-ahs2r2) ([raw file](https://github.com/gramineproject/gramine/blob/60b2e076fc2876058a7ab329c0192240166814f4/tools/sgx/ra-tls/secret_prov_attest.c#L151)):*
> ```C
>         ERROR("Failed to initialize PSA Crypto implementation: %d\n", (int)status);
>         ret = -EPERM;
>         goto out;
> ```

You can't `goto out` from here, this would trigger a `mbedtls_x509_crt_free()` call on uninitialized memory (`verifier_ca_chain`);
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 211 at r8](https://reviewable.io/reviews/gramineproject/gramine/1832#-NyrNNzmBQSS1m6hcVvG:-NyrNNzmBQSS1m6hcVvH:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/60b2e076fc2876058a7ab329c0192240166814f4/tools/sgx/ra-tls/secret_prov_verify.c#L211)):*
> ```C
>         ERROR("Failed to initialize PSA Crypto implementation: %d\n", (int)status);
>         ret = -EPERM;
>         goto out;
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-05-27 01:02 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: 12 of 15 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/1832#-NvMqZU5CQ-SPmPwtlWK:-NyrZ1rx0ydHUEIpGIa1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8945eddc12126ef53427384364661d5e7319f3ff/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Otherwise it seems to contradict the next sentence.
</blockquote></details>

Done.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 151 at r8](https://reviewable.io/reviews/gramineproject/gramine/1832#-NyrMfhU2b61cTk-VOzD:-NyrZ2dd9IK2xi-7YLO3:b-o7vuhc) ([raw file](https://github.com/gramineproject/gramine/blob/60b2e076fc2876058a7ab329c0192240166814f4/tools/sgx/ra-tls/secret_prov_attest.c#L151)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You can't `goto out` from here, this would trigger a `mbedtls_x509_crt_free()` call on uninitialized memory (`verifier_ca_chain`);
</blockquote></details>

Good catch! Done.
___
*[`tools/sgx/ra-tls/secret_prov_verify.c` line 211 at r8](https://reviewable.io/reviews/gramineproject/gramine/1832#-NyrNNzmBQSS1m6hcVvG:-NyrZBiE5zJfJDodSF5-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60b2e076fc2876058a7ab329c0192240166814f4/tools/sgx/ra-tls/secret_prov_verify.c#L211)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-28 00:40 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 371 at r9](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nytgy4D39031WceZ8KV:-NywcQ8F0WkS44EI-rGz:b-3veo9b) ([raw file](https://github.com/gramineproject/gramine/blob/24503d36401904d4f81bacdd5f44e00fc1507eb4/tools/sgx/ra-tls/secret_prov_attest.c#L371)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is it legal to call it after `psa_crypto_init()` failed? I can't find any documentation on this function :/
ditto below
</blockquote></details>

Indeed, I also don't find any doc about it. But from the mbedTLS example, it's the way to be used -- pls see https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/programs/ssl/ssl_client1.c#L85-L90 and https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/programs/ssl/ssl_client1.c#L264-L282.


<!-- Sent from Reviewable.io -->

2024-05-29 01:38 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`subprojects/mbedtls-3.6.0.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1832#-NuSz5Eb57YkKwpNhBXI:-Nz0zmsM5BZicG0wuMdG:b-x5jzbl) ([raw file](https://github.com/gramineproject/gramine/blob/98d77e70fe4695f6221fd024d007a2636263e2ec/subprojects/mbedtls-3.6.0.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Did anyone recreate this tarball to see if it's legit? (\*cough\* xz \*cough\*).

:)
</blockquote></details>

I checked them, they match each other.
___
*[`tools/sgx/ra-tls/secret_prov_attest.c` line 371 at r9](https://reviewable.io/reviews/gramineproject/gramine/1832#-Nytgy4D39031WceZ8KV:-Nz0zF2V4Am6CEtBy-Cz:b-eisbt9) ([raw file](https://github.com/gramineproject/gramine/blob/24503d36401904d4f81bacdd5f44e00fc1507eb4/tools/sgx/ra-tls/secret_prov_attest.c#L371)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Indeed, I also don't find any doc about it. But from the mbedTLS example, it's the way to be used -- pls see https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/programs/ssl/ssl_client1.c#L85-L90 and https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/programs/ssl/ssl_client1.c#L264-L282.
</blockquote></details>

Ok then. I also checked the implementation: https://github.com/Mbed-TLS/mbedtls/blob/e3abb6a148c99f1ee33f79736cafd9b091ef662c/library/psa_crypto.c#L8056-L8105

and it seems to be safeguarded against such cases. Though, it still feels a bit worrying to use it like that, because there are no docs :)


<!-- Sent from Reviewable.io -->

2024-05-30 22:22 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-30 22:22 UTC, merged