[curl] Upgrade libcurl to version 8.7.1
gramineproject/gramine pull request #1833
Opened 2024-04-02 09:26 UTC by kailun-qin

## Description of the changes 
This upgrade includes fixes for several CVEs affecting libcurl, specifically:
* CVE-2024-0853 (fixed in v8.6.0);
* CVE-2024-2004, CVE-2024-2398, CVE-2024-2379, CVE-2024-2466 (fixed in v8.7.0/v8.7.1).

This commit also updates the (disabled) libcurl feature list in Gramine based on the updated minimal binary size configuration recommendations from curl.

## How to test this PR? 
CI

2024-04-02 09:28 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: 0 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NuT7myr1yh8l3lSD0pT):*
Pls see https://github.com/curl/curl/commit/57777a262a48398ca41ad4e978882d093dd64727 for details.



_Code quote:_
```
updated minimal binary size configuration recommendations
```
___
*[`subprojects/curl-8.7.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NuT7gmK3P3yyr3cYUBF:-NuT7gmK3P3yyr3cYUBG:b-va539o) ([raw file](https://github.com/gramineproject/gramine/blob/424503b5570ccdaaffec569266f78908084f5eea/subprojects/curl-8.7.1.wrap#L4)):*
> ```
> directory = curl-8.7.1
> source_url = https://curl.se/download/curl-8.7.1.tar.gz
> source_fallback_url = https://packages.gramineproject.io/distfiles/curl-8.7.1.tar.gz
> ```

@woju: Would you pls help mirror this file? Thanks!



_Code quote:_
```
https://packages.gramineproject.io/distfiles/curl-8.7.1.tar.gz
```


<!-- Sent from Reviewable.io -->

2024-04-04 08:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/curl-8.7.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NuT7gmK3P3yyr3cYUBF:-NucFkM2DCtC6GPq7e-0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/424503b5570ccdaaffec569266f78908084f5eea/subprojects/curl-8.7.1.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: Would you pls help mirror this file? Thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-04 10:14 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/curl-8.7.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NuT7gmK3P3yyr3cYUBF:-Nucac_nDJEIGQNosy3o:b-piwhbm) ([raw file](https://github.com/gramineproject/gramine/blob/424503b5570ccdaaffec569266f78908084f5eea/subprojects/curl-8.7.1.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! It works fine.


<!-- Sent from Reviewable.io -->

2024-04-04 13:21 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1833#-NudFqut1-gm3jo4rCGi:-NudFqut1-gm3jo4rCGj:b-514gpj) (no related file):*
 [CVE-2024-2466](https://github.com/advisories/GHSA-9xr6-qf7m-2jv5) seems relevant to Gramine, in particular to RA-TLS usage:

If the user supplies a URL to IAS or MAA or ITA as an IP address (hard to imagine such a situation, but we just use an envvar, so the user can write whatever including the IP), then we can hit this bug. Recall that RA-TLS relies on the authenticity of IAS/MAA/ITA web server currently.

So we may consider doing a point release of Gramine, just to cover this particular vulnerability.

___
___
*[`subprojects/packagefiles/curl-8.7.1/compile.sh` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NudFcxo6qYBhgBcclnL:-NudFcxo6qYBhgBcclnM:bdpfbc1) ([raw file](https://github.com/gramineproject/gramine/blob/424503b5570ccdaaffec569266f78908084f5eea/subprojects/packagefiles/curl-8.7.1/compile.sh#L42)):*
> ```Shell
>         --disable-doh                               \
>         --disable-file                              \
>         --disable-form-api                          \
> ```

Why didn't you add `--disable-headers-api`? It's in the list: https://github.com/curl/curl/commit/57777a262a48398ca41ad4e978882d093dd64727


<!-- Sent from Reviewable.io -->

2024-04-04 13:47 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`subprojects/packagefiles/curl-8.7.1/compile.sh` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/1833#-NudFcxo6qYBhgBcclnL:-NudMENq2OtIPM3jFbkb:bz86rpv) ([raw file](https://github.com/gramineproject/gramine/blob/424503b5570ccdaaffec569266f78908084f5eea/subprojects/packagefiles/curl-8.7.1/compile.sh#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why didn't you add `--disable-headers-api`? It's in the list: https://github.com/curl/curl/commit/57777a262a48398ca41ad4e978882d093dd64727
</blockquote></details>

I missed it somehow... Thanks for pointing this out!


<!-- Sent from Reviewable.io -->

2024-04-04 14:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-04-04 14:31 UTC, mkow approved these changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-04-04 14:56 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1833#-NudFqut1-gm3jo4rCGi:-NudZydZBftNX2ICNy1x:b-5kwy9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

[CVE-2024-2466](https://github.com/advisories/GHSA-9xr6-qf7m-2jv5) seems relevant to Gramine, in particular to RA-TLS usage:

If the user supplies a URL to IAS or MAA or ITA as an IP address (hard to imagine such a situation, but we just use an envvar, so the user can write whatever including the IP), then we can hit this bug. Recall that RA-TLS relies on the authenticity of IAS/MAA/ITA web server currently.

So we may consider doing a point release of Gramine, just to cover this particular vulnerability.
</blockquote></details>

After a quick discussion with @woju and @mkow , here is my summary:

1.  RA-TLS's `_URL` envvars are the only inputs how RA-TLS's curl can use an IP address instead of a URL. These envvars are used only in the verifier, which is considered to run in a trusted environment.
2.  The only legitimate use of an IP address is when the verifier really wants to connect to an IP address with an attestation-server certificate bound to this IP address. Which is (almost?) never seen in practice. So no legitimate uses.
3.  Since the verifier environment is considered trusted, the verifier cannot be tricked into using an IP address instead of the URL.
4. The only usages of Curl in Gramine are: verifier's connection to the IAS (for EPID scheme), to the MAA (for Azure cloud), and to the ITA (for Intel attestation service). All of them are URL-based.

Based on this summary, I think the Curl vulnerability is not relevant to us.

___


<!-- Sent from Reviewable.io -->

2024-04-05 00:42 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 06:37 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1833)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 06:40 UTC, merged