WIP Ubuntu `jammy` and `noble` (22.04 LTS and 24.04 LTS)
gramineproject/gramine pull request #1843
Opened 2024-04-11 22:15 UTC by woju

## Description of the changes 

`noble` is scheduled to be released on 25.04.2024, about 2 weeks from now. From Gramine 1.7 we'll support `noble` and `jammy` so it's about time to have those in CI. 

## How to test this PR? 

check CI

2024-04-12 11:46 UTC, woju commented
Jenkins, test this please

2024-04-12 12:06 UTC, woju commented
Jenkins, test this please

2024-04-12 13:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvHRb-r96h52nL7T6eT:bih8o3b) (no related file):*
I'm putting a blocking comment to not accidentally merge this PR (before the full cycle of validation is done, also from the Intel internal CI side). This PR will surely go in only after Gramine v1.7.

___


<!-- Sent from Reviewable.io -->

2024-04-12 14:52 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvHlBag3IU8Rymjta_B:bgur0vj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm putting a blocking comment to not accidentally merge this PR (before the full cycle of validation is done, also from the Intel internal CI side). This PR will surely go in only after Gramine v1.7.
</blockquote></details>

It should be the other way around: we shouldn't release 1.7 without merging this PR. The PR (if ready), should get merged exactly on 25.04. (`noble` release). If we'll release v1.7 after 25.04, then we'll be bound by this project's policy to support 24.04 and 22.04, irrespective of Intel's internal CI and validation.

___


<!-- Sent from Reviewable.io -->

2024-04-15 06:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvVTZBM-xZ6UcAG4Yyx:b-9tn7sg) (no related file):*
> If we'll release v1.7 after 25.04, then we'll be bound by this project's policy to support 24.04 and 22.04, irrespective of Intel's internal CI and validation.

I'm confused by this sentence. Why would merging this PR **exactly on 25.04** change anything? This PR is about adding 22.04 and 24.04, so why can't this PR be merged **after 25.04**?

___


<!-- Sent from Reviewable.io -->

2024-04-15 10:52 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvWMuwJ3mnAkUka8HA1:b-wc7i35) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> If we'll release v1.7 after 25.04, then we'll be bound by this project's policy to support 24.04 and 22.04, irrespective of Intel's internal CI and validation.

I'm confused by this sentence. Why would merging this PR **exactly on 25.04** change anything? This PR is about adding 22.04 and 24.04, so why can't this PR be merged **after 25.04**?
</blockquote></details>

Because Ubuntu 24.04 LTS is expected to be released on 25.04.2024: https://launchpad.net/ubuntu/noble, so we target the exact date. If we release 1.7 before 25.04.2024, the we're technically not bound to support noble until 1.8, but if we release 1.7 after 25.04.2024, then we release with `noble` support, so it would be unwise to release without passing CI.

___


<!-- Sent from Reviewable.io -->

2024-04-15 11:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvWQJn-4xFjL7SsmKej:bg9dhiz) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because Ubuntu 24.04 LTS is expected to be released on 25.04.2024: https://launchpad.net/ubuntu/noble, so we target the exact date. If we release 1.7 before 25.04.2024, the we're technically not bound to support noble until 1.8, but if we release 1.7 after 25.04.2024, then we release with `noble` support, so it would be unwise to release without passing CI.
</blockquote></details>

Yes, all these things I understand. What I find confusing is your statement that **this PR must be merged exactly on 25.04**. Why merging this PR after 25.04 will be a problem?

___


<!-- Sent from Reviewable.io -->

2024-04-15 11:10 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NvWRNjfAYh1Ht20UrT7:bvb5sw9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, all these things I understand. What I find confusing is your statement that **this PR must be merged exactly on 25.04**. Why merging this PR after 25.04 will be a problem?
</blockquote></details>

I guess it will not be a problem if we do the actual merge slightly after 25.04., but before subsequent release (1.7 or 1.8, whichever it will be). In any case, we need to be *ready* for merging exactly 25.04, to be ready e.g. for scenario in which we release 1.7 on 26.04.

___


<!-- Sent from Reviewable.io -->

2024-05-02 04:42 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwraU7QBpOi9P8f2a59:-NwraU7QBpOi9P8f2a5A:bsi8wcp) (no related file):*
Woju as part of the PR you seem to be renaming/removing Ubuntu20.04 but as per Ubuntu (https://wiki.ubuntu.com/Releases) , 20.04 is supported at least till April 2025. So why are we removing support for Ubuntu 20.04? 

___


<!-- Sent from Reviewable.io -->

2024-05-02 10:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv and @jinengandhi-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwraU7QBpOi9P8f2a59:-NwswQ9OAibNsYi_n2MH:b-ioedy9) (no related file):*
> 20.04 is supported at least till April 2025

By Canonical, not by us.

See https://gramine.readthedocs.io/en/latest/devel/packaging.html#packaging-and-distributing. This has always been our policy.

___


<!-- Sent from Reviewable.io -->

2024-05-02 10:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 22 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwswkS71tOevql11_ic:-NwswkS71tOevql11_id:b-bkdhej) (no related file):*
Depends on https://github.com/gramineproject/gramine/pull/1865 (`[glibc] Adjust CFLAGS` should be dropped from here after merging that PR).

___


<!-- Sent from Reviewable.io -->

2024-05-06 04:50 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 22 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwraU7QBpOi9P8f2a59:-NxBE-NI7etT7tgnvMxk:b-u5fd8v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> 20.04 is supported at least till April 2025

By Canonical, not by us.

See https://gramine.readthedocs.io/en/latest/devel/packaging.html#packaging-and-distributing. This has always been our policy.
</blockquote></details>

Why do we still have `18.04` then in Ubuntu supported distros?

___


<!-- Sent from Reviewable.io -->

2024-05-06 10:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 22 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "WIP" found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwraU7QBpOi9P8f2a59:-NxCWzQU3qshyU_7GWro:b355ghr) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

Why do we still have `18.04` then in Ubuntu supported distros?
</blockquote></details>

We just forgot to update the list there, it's not supported since long time ago (as the previous sentence there indicates).
@woju: could you update packaging.rst in this PR, to only list 22.04 and 24.04?

___


<!-- Sent from Reviewable.io -->

2024-05-07 08:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 28 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @jinengandhi-intel, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwraU7QBpOi9P8f2a59:-NxHFhicC3ihh17low9q:b-pet3ml) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We just forgot to update the list there, it's not supported since long time ago (as the previous sentence there indicates).
@woju: could you update packaging.rst in this PR, to only list 22.04 and 24.04?
</blockquote></details>

By all means.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NwswkS71tOevql11_ic:-NxHFjOTEkRnqGLNlnIL:b5txyh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Depends on https://github.com/gramineproject/gramine/pull/1865 (`[glibc] Adjust CFLAGS` should be dropped from here after merging that PR).
</blockquote></details>

I've rebased on master and dropped the patch.

___


<!-- Sent from Reviewable.io -->

2024-05-07 10:12 UTC, woju commented
Jenkins, test Jenkins-SGX-24.04 please

2024-05-07 10:30 UTC, woju commented
Jenkins, test Jenkins-SGX-24.04 please

2024-05-07 10:36 UTC, woju commented
Jenkins, test Jenkins-SGX-24.04 please

2024-05-07 10:36 UTC, woju commented
Jenkins, test Jenkins-SGX-22.04 please

2024-05-07 11:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 28 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxHlp076s1dP2P_jAIv:-NxHlp076s1dP2P_jAIw:byag1y2) (no related file):*
We want to discuss removing the support for Ubuntu 20.04 in the Gramine meetings (on Tuesday and Wednesday). Blocking until that discussion is resolved.

___


<!-- Sent from Reviewable.io -->

2024-05-08 08:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 0 of 28 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxHlp076s1dP2P_jAIv:-NxMM32z31pd6Z-JSMS0:b-p9ji5a) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We want to discuss removing the support for Ubuntu 20.04 in the Gramine meetings (on Tuesday and Wednesday). Blocking until that discussion is resolved.
</blockquote></details>

This PR as it currently stands does not remove 20.04 pipelines, so I think it should be moved forward.

___


<!-- Sent from Reviewable.io -->

2024-05-09 16:37 UTC, mkow requested changes
> Reviewed 1 of 19 files at r1, 2 of 3 files at r3, 3 of 5 files at r5, 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
TODO: review the commit split before merging
btw. in the future, @woju, plz make PRs more atomic, this one mixes a lot of stuff and is annoying to review.
___
*[`.ci/ubuntu24.04.dockerfile` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTBLrg2NdwCSeEIFTX:-NxTBLrg2NdwCSeEIFTY:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:noble
> ```





_Suggestion:_
```Dockerfile
FROM ubuntu:24.04
```
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NxTA5iP-QkpoL15cqU_:biq952s) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
> ```
> env.DOCKER_ARGS_COMMON = """
>     --env=PATH=${env.PREFIX}/bin:${env.PATH}
>     --security-opt seccomp=${env.WORKSPACE}/scripts/docker_seccomp.json
> ```

Now `docker_seccomp.json` is not tested in CI at all. Can you move this change out of this PR so we can discuss it separately?
___
*[`python/gramine-sgx-sign` line 135 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxT9JpK4_jOICHSlBqb:-NxT9JpK4_jOICHSlBqc:bg8w6to) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/python/gramine-sgx-sign#L135)):*
> ```
>         expanded = manifest.expand_all_trusted_files(chroot=chroot)
>     except FileNotFoundError as err:
>         ctx.fail(f'Missing trusted file: {err.filename!r}')
> ```

How is this related to the PR? Can you move it to a separate PR?


<!-- Sent from Reviewable.io -->

2024-05-10 08:03 UTC, dimakuv requested changes
> Reviewed 1 of 19 files at r1, 2 of 3 files at r3, 3 of 5 files at r5, 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NxWRchd9DkqchIs_D8K:b-5u5i7x) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I guess it will not be a problem if we do the actual merge slightly after 25.04., but before subsequent release (1.7 or 1.8, whichever it will be). In any case, we need to be *ready* for merging exactly 25.04, to be ready e.g. for scenario in which we release 1.7 on 26.04.
</blockquote></details>

This discussion is not relevant anymore. Gramine v1.7 was released before Ubuntu 24.04 release date, so v1.7 didn't have any support for 24.04.

The next release of Gramine (v1.8) will have support for 24.04.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxHlp076s1dP2P_jAIv:-NxWS-tj7wgNcQPt-22h:b-eqrtbp) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This PR as it currently stands does not remove 20.04 pipelines, so I think it should be moved forward.
</blockquote></details>

Yes, sounds good.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWTvfA6jvBpBepP_Zj:-NxWTvfA6jvBpBepP_Zk:bu5iind) (no related file):*
Don't you want to add:
- `check-python-platlib-ubuntu24.04.dockerfile`
- `check-python-platlib-debian12.dockerfile`

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWWTyO8hmikTNXLfLy:-NxWWTyP5tn-uuB-lsrn:byolo3d) (no related file):*
I guess moving some test configurations from 20.04 to e.g. 24.04 will be done in some future PR?

For example, we have:
- `linux-sgx-ubuntu20.04-musl.jenkinsfile` which tests Musl, and it's the only such pipeline
- `linux-direct-ubuntu20.04-gcc-debug.jenkinsfile` which tests debug build, and it's the only such pipeline
- `linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile` which tests CI-Examples applications under SGX, and it's the only such pipeline

___
___
*[`.ci/ubuntu24.04.dockerfile` line 3 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWUFKe4JRUzA9UW5I3:-NxWUFKe4JRUzA9UW5I4:b-yo6a2e) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L3)):*
> ```Dockerfile
> FROM ubuntu:noble
> 
> ENV DEBIAN_FRONTEND=noninteractive
> ```

Maybe we could do the same in other Dockerfiles? I see that Ubuntu 22.04 and 20.04 don't have this envvar, but instead embed it directly in commands.
___
*[`.ci/ubuntu24.04.dockerfile` line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWVNI-C5SknsJGHWLG:-NxWVNI06UXBW5lPzioB:b2hfdwd) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L18)):*
> ```Dockerfile
> # in dockerfile.
> RUN mkdir /debian
> COPY debian/control /debian
> ```

This is smart.

I guess you don't want to bother doing the same for Ubuntu 20.04 Dockerfile, but what about Ubuntu 22.04? Don't you want to unify the commands in Dockerfiles?
___
*[`.ci/ubuntu24.04.dockerfile` line 34 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWV6wUD68C4ssuldxC:-NxWV6wUD68C4ssuldxD:bd5a6yz) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L34)):*
> ```Dockerfile
>     'python3-pyelftools' \
>     'python3-tomli (>= 1.1.0)' \
>     'python3-tomli-w (>= 0.4.0)'
> ```

Where is `voluptuous`? https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/debian/control#L47
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NxWSiAA10JjkD8bv6vh:brgaq9w) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now `docker_seccomp.json` is not tested in CI at all. Can you move this change out of this PR so we can discuss it separately?
</blockquote></details>

+1, it would be nice to test this in CI. Did you experience any problems with our current seccomp filter? If yes, we should fix/update it, not remove the test. If you didn't experience any issues, then we can keep it + have your new comment, but in the comment we say that "could run with `unconfined` but for testing purposes, we use an explicit seccomp config"
___
*[`Documentation/devel/packaging.rst` line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWT6202jhq2by7I6qa:-NxWT6202jhq2by7I6qb:b-p5g5j8) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/Documentation/devel/packaging.rst#L10)):*
> ```reStructuredText
> Currently officially supported distributions:
> 
> - Ubuntu (24.04 LTS, 22.04 LTS);
> ```

Based on our discussions (to really remove support for Ubuntu 20.04 in v1.9) I think we should still list it as officially supported.
___
*[`python/gramine-sgx-sign` line 135 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxT9JpK4_jOICHSlBqb:-NxWTIES2kul3mF1w0bf:b-acoiac) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/python/gramine-sgx-sign#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How is this related to the PR? Can you move it to a separate PR?
</blockquote></details>

+1, this looks totally unrelated to CI changes.


<!-- Sent from Reviewable.io -->

2024-05-10 15:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 24 of 29 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NxY41_q9PPBymvrx5KM:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This discussion is not relevant anymore. Gramine v1.7 was released before Ubuntu 24.04 release date, so v1.7 didn't have any support for 24.04.

The next release of Gramine (v1.8) will have support for 24.04.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWWTyO8hmikTNXLfLy:-NxX3sN4AgABNR0_jzYV:b-offbfk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess moving some test configurations from 20.04 to e.g. 24.04 will be done in some future PR?

For example, we have:
- `linux-sgx-ubuntu20.04-musl.jenkinsfile` which tests Musl, and it's the only such pipeline
- `linux-direct-ubuntu20.04-gcc-debug.jenkinsfile` which tests debug build, and it's the only such pipeline
- `linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile` which tests CI-Examples applications under SGX, and it's the only such pipeline
</blockquote></details>

Yes. For now I wanted to have just those two pipelines, to check compilation, to limit the scope of the PR. I expect most of the problems will be related to compilation, not to tests (two problems were already found here and fixed by @oshogbo in #1865)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWTvfA6jvBpBepP_Zj:-NxX5A7Q53TrK4ziVKHF:boxi32w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to add:
- `check-python-platlib-ubuntu24.04.dockerfile`
- `check-python-platlib-debian12.dockerfile`
</blockquote></details>

Not in this PR I think.

___
___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO: review the commit split before merging
btw. in the future, @woju, plz make PRs more atomic, this one mixes a lot of stuff and is annoying to review.
</blockquote></details>

Even more annoying is waiting for review in this project, so I think I'll be submitting PRs that have related stuff (e.g. all the stuff that is needed to run a pipeline on a new distro), just properly split into atomic commits. You can always switch reviewable to review commit by commit.
___
*[`.ci/ubuntu24.04.dockerfile` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTBLrg2NdwCSeEIFTX:-NxY7C9A6rlRizVfXSg8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:noble
> ```

Done.
___
*[`.ci/ubuntu24.04.dockerfile` line 3 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWUFKe4JRUzA9UW5I3:-NxY7Eas6xQc2K7pbGK8:b-nrs7it) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we could do the same in other Dockerfiles? I see that Ubuntu 22.04 and 20.04 don't have this envvar, but instead embed it directly in commands.
</blockquote></details>

Done for 22.04. I don't want to touch 20.04.
___
*[`.ci/ubuntu24.04.dockerfile` line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWVNI-C5SknsJGHWLG:-NxY52r37ZqHKCPdLoJB:b-7gagpv) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is smart.

I guess you don't want to bother doing the same for Ubuntu 20.04 Dockerfile, but what about Ubuntu 22.04? Don't you want to unify the commands in Dockerfiles?
</blockquote></details>

I think it's impossible on Ubuntu 20.04, because `apt-get build-dep` will fail for dependencies that are not available in `focal`. I did a version for 22.04.
___
*[`.ci/ubuntu24.04.dockerfile` line 34 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWV6wUD68C4ssuldxC:-NxX4lon7_gmp1lAc36e:blr8fv2) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/.ci/ubuntu24.04.dockerfile#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where is `voluptuous`? https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/debian/control#L47
</blockquote></details>

Missed, sorry. It's in `debian/control` in `Build-Depends`, and got installed by `apt-get build-dep` above.
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NxXFKI-8_xffK5tbVxQ:b-ql4k68) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, it would be nice to test this in CI. Did you experience any problems with our current seccomp filter? If yes, we should fix/update it, not remove the test. If you didn't experience any issues, then we can keep it + have your new comment, but in the comment we say that "could run with `unconfined` but for testing purposes, we use an explicit seccomp config"
</blockquote></details>

Yes, there was a problem. Let's see what happens if I switch to newer version.
___
*[`Documentation/devel/packaging.rst` line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxWT6202jhq2by7I6qa:-NxY0asr314CyvPiiO13:b-j3wcdm) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/Documentation/devel/packaging.rst#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Based on our discussions (to really remove support for Ubuntu 20.04 in v1.9) I think we should still list it as officially supported.
</blockquote></details>

Done. I think I'll remove it when I'll remove 20.04 pipelines, which may be before 1.9 (or even before 1.8), but not right now.
___
*[`python/gramine-sgx-sign` line 135 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxT9JpK4_jOICHSlBqb:-NxY3wfs2IVfy7EerO9b:bbmco83) ([raw file](https://github.com/gramineproject/gramine/blob/b0d66f45e1fca2b5a2bfc93b6f79aacfc18bcb1d/python/gramine-sgx-sign#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, this looks totally unrelated to CI changes.
</blockquote></details>

#1880 


<!-- Sent from Reviewable.io -->

2024-05-13 07:50 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`.ci/ubuntu22.04.dockerfile` line 9 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxkuVJ45Y55aXCDLyu5:-NxkuVJ45Y55aXCDLyu6:bw7nepv) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L9)):*
> ```Dockerfile
> # Intel's RSA-2048 key signing the intel-sgx/sgx_repo repository. Expires 2027-03-20.
> # https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
> # TODO after Intel releases for noble: fix mantic to noble
> ```

This TODO is not applicable here.
___
*[`.ci/ubuntu22.04.dockerfile` line 11 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxkucKA5w6twl1_Glfj:-NxkucKA5w6twl1_Glfk:bex9k6o) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L11)):*
> ```Dockerfile
> # TODO after Intel releases for noble: fix mantic to noble
> COPY .ci/intel-sgx-deb.key /etc/apt/keyrings/intel-sgx-deb.asc
> RUN echo deb [arch=amd64 signed-by=/etc/apt/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu mantic main > /etc/apt/sources.list.d/intel-sgx.list
> ```

I think you want `jammy` instead of `mantic`
___
*[`.ci/ubuntu22.04.dockerfile` line 43 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxkv0qw3fzXgJqPcAAH:-Nxkv0qw3fzXgJqPcAAI:b-q356tg) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L43)):*
> ```Dockerfile
> # shellcheck: .ci/run-shellcheck
> # cargo: CI-Examples/rust
> # clang: FIXME
> ```

What is this FIXME? Clang is used for AddressSanitizer builds.


<!-- Sent from Reviewable.io -->

2024-05-14 11:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 24 of 29 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`.ci/ubuntu22.04.dockerfile` line 9 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxkuVJ45Y55aXCDLyu5:-NxqoHwU5wkvmOwp0WHP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This TODO is not applicable here.
</blockquote></details>

Done.
___
*[`.ci/ubuntu22.04.dockerfile` line 11 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxkucKA5w6twl1_Glfj:-NxqoIMS2E2E4JHVQ6Ov:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you want `jammy` instead of `mantic`
</blockquote></details>

Done.
___
*[`.ci/ubuntu22.04.dockerfile` line 43 at r7](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxkv0qw3fzXgJqPcAAH:-NxqoVKy-SdachssGeme:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0c230af4ff45701ab987bb898327a439be1673e2/.ci/ubuntu22.04.dockerfile#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this FIXME? Clang is used for AddressSanitizer builds.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-14 11:37 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-05-15 09:00 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 28 of 29 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NxvTXBf-fIhFL4A9q7X:b-7kanla) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, there was a problem. Let's see what happens if I switch to newer version.
</blockquote></details>

So eventually I just pass seccomp argument to `docker().inside()`. Rationale is that it depends on `node()` specifier, so I think it's fair to have it variable per-node.


<!-- Sent from Reviewable.io -->

2024-05-15 18:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 28 of 29 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`.ci/ubuntu24.04.dockerfile` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxwbtru9oKA9Yc17NnM:-Nxwbtru9oKA9Yc17NnN:b-heh13z) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu24.04.dockerfile#L9)):*
> ```Dockerfile
> # Intel's RSA-2048 key signing the intel-sgx/sgx_repo repository. Expires 2027-03-20.
> # https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
> # TODO after Intel releases for noble: fix mantic to noble
> ```

I'm putting a blocking comment for now: we need to discuss how it affects users. Technically, we should at least warn users that when they git-clone the master branch on Ubuntu 24.04, and they want to use RA-TLS (or whatever with attestation), which requires Intel SGX PSW/DCAP packages/libraries. We currently silently use 23.10-based packages for Intel SGX PSW/DCAP, but (1) end users won't know this trick, and (2) technically it's wrong to use packages from another OS distro version.


<!-- Sent from Reviewable.io -->

2024-05-16 11:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 28 of 29 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`.ci/ubuntu24.04.dockerfile` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxwbtru9oKA9Yc17NnM:-Ny02Pl66KVVQhraUuUo:b-gqj6f5) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu24.04.dockerfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm putting a blocking comment for now: we need to discuss how it affects users. Technically, we should at least warn users that when they git-clone the master branch on Ubuntu 24.04, and they want to use RA-TLS (or whatever with attestation), which requires Intel SGX PSW/DCAP packages/libraries. We currently silently use 23.10-based packages for Intel SGX PSW/DCAP, but (1) end users won't know this trick, and (2) technically it's wrong to use packages from another OS distro version.
</blockquote></details>

(2) is true for RPMs, but false for DEBs: on debian/ubuntu the packages themselves may be OK to use on different distro versions and even for different distros (like using debian packages on ubuntu and vice versa). What matters is how the packages are linked, IOW if the distro ships a package of a library with matching SONAME, incl. version if the soname is versioned. ISTM that those specific `mantic` packages are OK to use on `noble`.

(1) might be true or not, but it's not our problem that users don't know something.


<!-- Sent from Reviewable.io -->

2024-05-16 12:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: 28 of 29 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`.ci/ubuntu24.04.dockerfile` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxwbtru9oKA9Yc17NnM:-Ny0TJzC7ck4xA5cxuUu:b-t79hm5) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu24.04.dockerfile#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

(2) is true for RPMs, but false for DEBs: on debian/ubuntu the packages themselves may be OK to use on different distro versions and even for different distros (like using debian packages on ubuntu and vice versa). What matters is how the packages are linked, IOW if the distro ships a package of a library with matching SONAME, incl. version if the soname is versioned. ISTM that those specific `mantic` packages are OK to use on `noble`.

(1) might be true or not, but it's not our problem that users don't know something.
</blockquote></details>

Oh, and this is CI, not anything that we support for users. FWIW users who don't want to use `mantic` repos can recompile those libraries themselves.


<!-- Sent from Reviewable.io -->

2024-05-17 06:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow)

___
*[`.ci/ubuntu24.04.dockerfile` line 9 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nxwbtru9oKA9Yc17NnM:-Ny4IA6f-ora1WJtkiE8:b6w8coq) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu24.04.dockerfile#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oh, and this is CI, not anything that we support for users. FWIW users who don't want to use `mantic` repos can recompile those libraries themselves.
</blockquote></details>

Ok, I'm unblocking this. I added a note in our roadmap here on GitHub, that if PSW/DCAP packages are not yet released for 24.04 at the time we release Gramine v1.8, we'll need to put a note/warning in our Release Notes. I think this is a fair compromise.


<!-- Sent from Reviewable.io -->

2024-05-20 15:47 UTC, mkow requested changes
> Reviewed 3 of 5 files at r7, 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-NyLbn0Q50mg0iw9ggsT:bomyji5) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@woju: Please update the description of the PR accordingly, so it's not confusing for the people reading the merge log later.

___
___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
> You can always switch reviewable to review commit by commit.

I can't, only the first reviewer can decide about that.

> Even more annoying is waiting for review in this project

It would have gone much faster if you had split it into smaller PRs, because reviewing most of them would be trivial and we could have merged them right away (also, they wouldn't be blocked on discussions about other changes).
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-NyLfUV50eMo7NBJzXBw:begmynz) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
> ```Dockerfile
>     'python3-voluptuous'
> 
> # dependencies for various tests, CI-Examples, etc.
> ```

Why is this list so different from 24.04? Aren't we running all these tests on both?
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NyLdjSr1YAgpGmBwkVm:b-b8t6sn) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

So eventually I just pass seccomp argument to `docker().inside()`. Rationale is that it depends on `node()` specifier, so I think it's fair to have it variable per-node.
</blockquote></details>

Ok, but the original issue still stands - `docker_seccomp.json` is not tested anymore.


<!-- Sent from Reviewable.io -->

2024-05-23 12:00 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1843#-NvHRb-q4lIyCvJoWLk2:-Ny_HbMF6FaIESv44z9S:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Please update the description of the PR accordingly, so it's not confusing for the people reading the merge log later.
</blockquote></details>

Done.

___
___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> You can always switch reviewable to review commit by commit.

I can't, only the first reviewer can decide about that.

> Even more annoying is waiting for review in this project

It would have gone much faster if you had split it into smaller PRs, because reviewing most of them would be trivial and we could have merged them right away (also, they wouldn't be blocked on discussions about other changes).
</blockquote></details>

Something like new distro versions cannot be done in single commit, because things change all over the place, and you can't test end result when they aren't all merged. So it would look like a train of PRs stacked one on top of another, and to test it you'd need to rebase all subsequent PRs, which would be nightmare. You just need to review stuff, this PR was hanging for a month already.
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-Ny_HhB03tVeDS6fY_2m:b66vofl) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this list so different from 24.04? Aren't we running all these tests on both?
</blockquote></details>

Not yet. Right now I wanted to merge at least something, and more tests will be switched sometime later.
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-Ny_IhW0BVJV3DfpnbXO:bi6djc3) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but the original issue still stands - `docker_seccomp.json` is not tested anymore.
</blockquote></details>

No, it's tested in `linux-direct-ubuntu20.04-gcc-debug.jenkinsfile`, `linux-direct-ubuntu20.04-gcc-release.jenkinsfile` and `linux-direct-sanitizers.jenkinsfile`, just referenced by real path, not by symlink.


<!-- Sent from Reviewable.io -->

2024-05-23 12:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Most of these commits were simple and would be merged right away.

> You just need to review stuff, this PR was hanging for a month already.

Most of that time was spent waiting on the decision and discussion about what to do about 20.04 (which the original version of this PR was removing). And during review your response times were similar to mine.

Anyways, my point is that in that time we could have merged all these small commits and only the stuff requiring discussions would have to wait (and would be easier to review). We do that with all other features and it really makes reviewing and merging easier.
</blockquote></details>

Also, this PR still contains commits which are either unrelated or should be separate PRs - `[Docs] Update supported Ubuntu versions` (this should be a separate PR, merged after all the 24.04 work is done), `[CI] Rewrite ubuntu22.04.dockerfile for consistency` is just some refactoring, `[CI] Don't clone linux-sgx-driver on builds against upstream driver` is only a clean-up / perf improvement unrelated to 24.04.
Not sure about the others, maybe it's even more.


<!-- Sent from Reviewable.io -->

2024-05-23 14:07 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Also, this PR still contains commits which are either unrelated or should be separate PRs - `[Docs] Update supported Ubuntu versions` (this should be a separate PR, merged after all the 24.04 work is done), `[CI] Rewrite ubuntu22.04.dockerfile for consistency` is just some refactoring, `[CI] Don't clone linux-sgx-driver on builds against upstream driver` is only a clean-up / perf improvement unrelated to 24.04.
Not sure about the others, maybe it's even more.
</blockquote></details>

"rewrite 22.04" was requested in review, "update supported versions" we merge together, because usually we merge related stuff (docs and tests) together, and "don't clone linux-sgx-driver" is performance optimisation (not cleanup), because we don't need it with upstream driver. Previously it was needed for all CI pipelines apart from the VM one.
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-Ny_l-hX9eC6QiTyUmI0:bbpf1o0) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's wrong with the other tests? Was there any discussion about that anywhere?
This seems like a dangerous thing to do, we could have merged this and forget that some tests aren't running in CI anymore.
</blockquote></details>

I didn't want to start fixing them all, hoping in vain that this quick PR will be merged soon and I'll be able to start fixing tests.
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-Ny_dj4428Or4Xlf--9r:b79o7dy) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, it's a symlink. Quite confusing.
It points to an outdated policy, shouldn't we update it? If I see correctly, it's only referenced to by GSC's index.rst, right?
</blockquote></details>

I think it's liable just to be removed once we deprecate 20.04.

Yes, non-qualified is not described in this repo, we documented those with dates (see the bottom of `installation.rst`).


<!-- Sent from Reviewable.io -->

2024-05-23 14:31 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"rewrite 22.04" was requested in review, "update supported versions" we merge together, because usually we merge related stuff (docs and tests) together, and "don't clone linux-sgx-driver" is performance optimisation (not cleanup), because we don't need it with upstream driver. Previously it was needed for all CI pipelines apart from the VM one.
</blockquote></details>

I still don't see why they are here. Usually when someone requests unrelated changes which are big enough for their own commit then we do them, but in a separate PR.
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-Ny_pVGT1XUSnmNe7gbS:b-4vwlwy) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I didn't want to start fixing them all, hoping in vain that this quick PR will be merged soon and I'll be able to start fixing tests.
</blockquote></details>

Are they actually broken on 24.04 or you didn't try yet?
@kailun-qin, @dimakuv: Should we merge a partial pipeline, or fix these tests first? If the former, we need to create an issue to not forget that some tests are silently skipped on 24.04.
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-Ny_qKij7eMaCzZenFn4:b-4vaze9) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think it's liable just to be removed once we deprecate 20.04.

Yes, non-qualified is not described in this repo, we documented those with dates (see the bottom of `installation.rst`).
</blockquote></details>

Hmm, does this mean that GSC in direct mode cannot run on 24.04 currently? (because it will use the old seccomp policy)
Anyways, I agree, we should do this when dropping 20.04.


<!-- Sent from Reviewable.io -->

2024-05-24 10:54 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I still don't see why they are here. Usually when someone requests unrelated changes which are big enough for their own commit then we do them, but in a separate PR.
</blockquote></details>

I think I explained why they are in this PR. Is there anything actionable for me in this thread?
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-Nyaz6id9bRs5sAe0Lg0:b-qsdieq) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are they actually broken on 24.04 or you didn't try yet?
@kailun-qin, @dimakuv: Should we merge a partial pipeline, or fix these tests first? If the former, we need to create an issue to not forget that some tests are silently skipped on 24.04.
</blockquote></details>

Haven't tried yet.
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NyeDfsq72jFwdYsL329:b63vx0i) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, does this mean that GSC in direct mode cannot run on 24.04 currently? (because it will use the old seccomp policy)
Anyways, I agree, we should do this when dropping 20.04.
</blockquote></details>

The policy needs to be specified by the user every time, so it's up to the user to specify that newer one anyway. It's only referenced in documentation, not in the code itself.


<!-- Sent from Reviewable.io -->

2024-05-24 22:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`-- commits` line 32 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxSnNBlDHCcJgUVB1-7):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think I explained why they are in this PR. Is there anything actionable for me in this thread?
</blockquote></details>

No, only for me (see the initial message in this thread).


<!-- Sent from Reviewable.io -->

2024-05-25 00:17 UTC, kailun-qin approved these changes
> Reviewed 1 of 19 files at r1, 2 of 3 files at r3, 1 of 5 files at r5, 3 of 22 files at r6, 2 of 5 files at r7, 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @woju)

___
*[`.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile` line 8 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nyh1Y-tDhR3lVX6fjy-:-Nyh1Y-tDhR3lVX6fjy0:bnncy61) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile#L8)):*
> ```
>         "local:${env.BUILD_TAG}",
>         '-f .ci/ubuntu20.04.dockerfile .'
>     ).inside("${env.DOCKER_ARGS_COMMON} --security-opt seccomp=${env.WORKSPACE}/scripts/docker_seccomp_mar_2021.json") {
> ```

A bit off the topic, just wondering any special reason that we did not point to the seccomp profile for newer docker versions (docker_seccomp_aug_2022)?



_Code quote:_
```
docker_seccomp_mar_2021.json
```
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-Nyh4-0S9s_9AgtKELWo:b-4isiq) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
> Should we merge a partial pipeline, or fix these tests first?

I prefer the latter but I'm fine w/ the former + an issue (if it makes @woju easier).


<!-- Sent from Reviewable.io -->

2024-05-27 13:21 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[`.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile` line 8 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nyh1Y-tDhR3lVX6fjy-:-Nyu8JUU9hOrhmMx8s-s:b-rn8ayq) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

A bit off the topic, just wondering any special reason that we did not point to the seccomp profile for newer docker versions (docker_seccomp_aug_2022)?
</blockquote></details>

I don't fully understand the question. Is it "why we won't use newer (2022) seccomp for older machines"? If so, then we can't use it, because it contains references to not-yet-existing syscalls (as of the kernel that is running on the machine and/or docker runner itself). The first one that is breaking is `clone3` I think, that's what the error says, but I'm not sure if there aren't more.

If I wanted to do that, I'd need to `dist-upgrade` all the existing machines at once, and that would be problematic, because some of those don't have FLC, and it would break SGX on them. On those with FLC the newer kernel would have `upstream` driver, so I'd have to also update CI to `-Dsgx_driver=upstream` (it's `oot` at the moment), so it would quickly become a major operation, which I don't think it's in scope of this PR. I want to do it by migrating those machines into VMs one by one, and those two new pipelines do run in VMs (`node("sgx")`), but all existing (`node("sgx_slave_2.6"` and `node("nonsgx_slave")`) are bare metal.


<!-- Sent from Reviewable.io -->

2024-06-03 07:36 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

___
*[`.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile` line 8 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-Nyh1Y-tDhR3lVX6fjy-:-NzRzPDS6kxVju90fiVH:bbulekk) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile#L8)):*
> Is it "why we won't use newer (2022) seccomp for older machines"? If so, then we can't use it, because it contains references to not-yet-existing syscalls (as of the kernel that is running on the machine and/or docker runner itself).

Yes, that's what @kailun-qin meant by his question.

From my side, I confirm what @woju says -- some of our CI machines have a too-old host Linux kernel, so they can't use a newer seccomp policy because it contains unknown-to-host-Linux syscalls.
___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-NzS-fUy-EC2eVHhDRqO:bcieul) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
> Why is this list so different from 24.04? Aren't we running all these tests on both?

@mkow Did you mean "why so different from **20.04**"? As @woju explained, most of the tests are run under **20.04** currently, and only some tests run under 22.04.

I didn't see a big problem with having this partial pipeline as is in this PR, as the "forget about some tests" would be visible in the "Remove 20.04 pipeline" follow-up PR. But I'm fine with creating a small GitHub issue.

Created the issue: https://github.com/gramineproject/gramine/issues/1893
___
*[`.ci/lib/config-docker.jenkinsfile` line 6 at r6](https://reviewable.io/reviews/gramineproject/gramine/1843#-NxTA5iP-QkpoL15cqUZ:-NzS-IDg1KeYH9-xNS2f:btycu42) ([raw file](https://github.com/gramineproject/gramine/blob/b7ffa83a4203bdc2b560cbfef140c0e8ab6b7a58/.ci/lib/config-docker.jenkinsfile#L6)):*
> Hmm, does this mean that GSC in direct mode cannot run on 24.04 currently? (because it will use the old seccomp policy)

As @woju explained, GSC doesn't restrict or hard-code the seccomp policy at all. GSC doesn't even participate in this, as the user simply runs classic `docker run ...`, not anything GSC-wrapped. See documentation: https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-gramine-direct


<!-- Sent from Reviewable.io -->

2024-06-03 14:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`.ci/ubuntu22.04.dockerfile` line 36 at r9](https://reviewable.io/reviews/gramineproject/gramine/1843#-NyLfUV50eMo7NBJzXBv:-NzTXbBvA5o3NojHUteD:b-in71dn) ([raw file](https://github.com/gramineproject/gramine/blob/9475f3744abc76f1cd33f40deb18d3031702936e/.ci/ubuntu22.04.dockerfile#L36)):*
> as the "forget about some tests" would be visible in the "Remove 20.04 pipeline" follow-up PR

How would that be visible? You'd just see the old pipeline files removed, and that's all?

> Created the issue: #1893

Same as Kailun, I'd prefer if all the tests were fixed first, but I won't block on this if there's an issue created to remember about it.


<!-- Sent from Reviewable.io -->

2024-06-10 11:39 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-10 12:05 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-10 16:14 UTC, merged