[PAL] Support direct mode in Windows WSL
gramineproject/gramine pull request #1849
Opened 2024-04-18 00:29 UTC by g2flyer

## Description of the changes 

Currently Gramine does not work on Windows subsystem for linux (WSL) as WSL does not have a "/sys/devices/system/node/" folder, preventing the use of this common and convenient development platoform.   This PR remedies that by using reasonable default values if that folder does not exist.

This is a resurrection of earlier abandoned PR #679, updated to the latest version and also a bit cleaned up.

## How to test this PR? 

Usual CI should test that it doesn't break anything existing and to test on WSL, just build and run usual regression tests and some of the examples.

BTW: I've tested (successfully ;-) on WSL version 2.2.0 with kernel 5.15.150.1-microsoft-standard-WSL2  on running ubuntu 23.10. That said, i don't think specific WSL2 versions shouldn't matter much and neither should ubuntu version (beyond what is or is not generally supported by gramine).

2024-04-19 08:09 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer)

___
*[`pal/src/host/linux-common/topo_info.c` line 294 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOd-3EmobDL-ApVrx:-NvpOd-3EmobDL-ApVry:bqnz8qm) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L294)):*
> ```C
>     bool cpu_nodes_file_exists = false;
>     size_t nodes_cnt = 1;
>     /* Get the CPU node number. By default, the number is 1.
> ```

`CPU node number` -> `number of NUMA nodes on the system`
___
*[`pal/src/host/linux-common/topo_info.c` line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpNjkG7XsOBKg7Z1cD:-NvpNjkG7XsOBKg7Z1cE:b-lmeoit) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L307)):*
> ```C
>     } else {
>         cpu_nodes_file_exists = true;
>     }
> ```

This cascade of ifs feels complex. Why not a flat structure:
```
    bool cpu_nodes_file_exists = true;
    ...
    if (ret < 0 && ret != -ENOENT)
        return ret;
    if (ret == -ENOENT)
        cpu_nodes_file_exists = false;
```
___
*[`pal/src/host/linux-common/topo_info.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpORX88z_lQEhsQFPf:-NvpORX88z_lQEhsQFPg:b-4rl2x5) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L340)):*
> ```C
> 
>     if (cpu_nodes_file_exists) {
>         ret = iterate_ranges_from_file("/sys/devices/system/node/online", set_numa_node_online, numa_nodes);
> ```

Please fix limit per line (100 chars max)
___
*[`pal/src/host/linux-common/topo_info.c` line 346 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpO3Pw8F0Cyig8I21f:-NvpO3Pw8F0Cyig8I21g:b-mg65sl) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L346)):*
> ```C
>         /* If there is no node information, the (only) node must be online. */
>         numa_nodes[0].is_online = true;
>     }
> ```

I would remove these `else` branches scattered around the whole file, and instead put them in a single place:
```
if (!cpu_nodes_file_exists) {
    /* if there is no node information, imitate a single node */
    numa_nodes[0].is_online = true;
    numa_nodes[0].nr_hugepages[HUGEPAGES_2M] = 0;
    numa_nodes[0].nr_hugepages[HUGEPAGES_1G] = 0;
    distances[0] = 10; /* default on Linux 5.15 */
}
```
___
*[`pal/src/host/linux-common/topo_info.c` line 402 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOUWl6cXNmJg-Urm2:-NvpOUWl6cXNmJg-Urm3:b-4rl2x5) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L402)):*
> ```C
>                 goto fail;
> 
>             /* Since our sysfs doesn't support writes, set persistent hugepages to their default value
> ```

Please fix limit per line (100 chars max)
___
*[`pal/src/host/linux-common/topo_info.c` line 408 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOVXp4wKBY1x0S7xu:-NvpOVXp4wKBY1x0S7xv:bd46g4b) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L408)):*
> ```C
>         }
>     } else {
>         /* As node-id is by default zero we do not have to call set_node_id for synthesized mnode
> ```

`monde` -> `node`


<!-- Sent from Reviewable.io -->

2024-04-19 15:44 UTC, g2flyer reviewed
Dmitrii, thanks for your review.  I hope i did address your comments although i took the liberty of changing in slightly different ways but hopefully still captured the intention of your concern

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849#-:-Nvr0r_8DFBY90xJkzl3:b-pb8bts)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 294 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOd-3EmobDL-ApVrx:-Nvqzy8m09ELAJyL1Cm8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L294)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`CPU node number` -> `number of NUMA nodes on the system`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpNjkG7XsOBKg7Z1cD:-Nvr--yn7Y-HwsM9Cm1b:b5o0l1u) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L307)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This cascade of ifs feels complex. Why not a flat structure:
```
    bool cpu_nodes_file_exists = true;
    ...
    if (ret < 0 && ret != -ENOENT)
        return ret;
    if (ret == -ENOENT)
        cpu_nodes_file_exists = false;
```
</blockquote></details>

Yeah, i also didn't like it in its original form but was too lazy to change.  I did now make it more concise and also split the comments to separate the two parts the comment contained
___
*[`pal/src/host/linux-common/topo_info.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpORX88z_lQEhsQFPf:-Nvr-La32DqaviKAp_P5:bex50yp) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix limit per line (100 chars max)
</blockquote></details>

good catch.  I was counting that my editor applies clang-format but as i haven't touched this part of the code it didn't reformat, should be done now
___
*[`pal/src/host/linux-common/topo_info.c` line 346 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpO3Pw8F0Cyig8I21f:-Nvr0JRp2LFTXFVBi-Cl:b-i3dd4g) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove these `else` branches scattered around the whole file, and instead put them in a single place:
```
if (!cpu_nodes_file_exists) {
    /* if there is no node information, imitate a single node */
    numa_nodes[0].is_online = true;
    numa_nodes[0].nr_hugepages[HUGEPAGES_2M] = 0;
    numa_nodes[0].nr_hugepages[HUGEPAGES_1G] = 0;
    distances[0] = 10; /* default on Linux 5.15 */
}
```
</blockquote></details>

I consolidated although i didn't like the if (X) followed by if (!X) but left it an alse (but commented on what the else is.
BTW: along the same consolidation argument one could also merge the two for loops inside the iff?  But left it as is to keep patch more minimal
___
*[`pal/src/host/linux-common/topo_info.c` line 402 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOUWl6cXNmJg-Urm2:-Nvr08eh8OWzmjRnFL6I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L402)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix limit per line (100 chars max)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 408 at r1](https://reviewable.io/reviews/gramineproject/gramine/1849#-NvpOVXp4wKBY1x0S7xu:-Nvr07q8-OzXurdzDPLD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47f0e0c919917585ca7a557cced872239dda02b4/pal/src/host/linux-common/topo_info.c#L408)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`monde` -> `node`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-22 13:00 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

___
*[`pal/src/host/linux-common/topo_info.c` line 292 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4rCUu919i_KVumX8C:-Nw4rCUu919i_KVumX8D:bn0xex5) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L292)):*
> ```C
>         return ret;
> 
>     bool cpu_nodes_file_exists = false;
> ```

No need to declare the bool here, just declare & assign it below
___
*[`pal/src/host/linux-common/topo_info.c` line 297 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t1CZ5wqvo5Y-sgwm:-Nw4t1CZ5wqvo5Y-sgwn:bfwqop3) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L297)):*
> ```C
>     ret = iterate_ranges_from_file("/sys/devices/system/node/possible", get_ranges_end, &nodes_cnt);
>     if ((ret < 0) && (ret != -ENOENT)) {
>         /* Some systems do not have the file, for example, Windows Subsystem for Linux, for which we
> ```

`for example` -> `e.g.`
___
*[`pal/src/host/linux-common/topo_info.c` line 298 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t2r75yIYqIpW7Pt6:-Nw4t2r75yIYqIpW7Pt7:b-tz2c2) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L298)):*
> ```C
>     if ((ret < 0) && (ret != -ENOENT)) {
>         /* Some systems do not have the file, for example, Windows Subsystem for Linux, for which we
>          * will ignore the -ENOENT error and synthesize later a corresponding (single) numa node
> ```

No need for the word `will`
___
*[`pal/src/host/linux-common/topo_info.c` line 298 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t5k36V7L95tf33I7:-Nw4t5k36V7L95tf33I8:bj0gmf2) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L298)):*
> ```C
>     if ((ret < 0) && (ret != -ENOENT)) {
>         /* Some systems do not have the file, for example, Windows Subsystem for Linux, for which we
>          * will ignore the -ENOENT error and synthesize later a corresponding (single) numa node
> ```

`numa` -> `NUMA`
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4sWaf0s9hfCVnvVJT:-Nw4sWagBpiXDjkG_sDE:b75lddk) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L433)):*
> ```C
>                 goto fail;
>         }
>     } else {  // !cpu_nodes_file_exists
> ```

We don't use such a notation with `// !`. I suggest to just remove it.
___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4s_Eh1lDgBNPDwNl9:-Nw4s_Eh1lDgBNPDwNlA:b-ix94u6) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L435)):*
> ```C
>     } else {  // !cpu_nodes_file_exists
>         /* As node-id is by default zero we do not have to call set_node_id for synthesized node
>          * and, as above, unsupported persistent huge pages to zero */
> ```

This is hard to read and understand -- it talks about two different things. What about this:
```
/* node_id field for each CPU core is by default zero, so no need to call set_node_id() for 
 * our single synthesized node 0 */
;

/* as above, set unsupported persistent huge pages to zero */
num_nodes[0]. ...
```
___
*[`pal/src/host/linux-common/topo_info.c` line 439 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4rfS9-vvfjcLZi4Up:-Nw4rfS9-vvfjcLZi4Uq:bt1v8uv) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L439)):*
> ```C
>         numa_nodes[0].nr_hugepages[HUGEPAGES_1G] = 0;
> 
>         /* Set the distance with default value Ubuntu 22.04 kernel 5.15 for syntheized numa node */
> ```

I think Ubuntu 22.04 is not relevant (i.e. it's a default in the Linux kernel, not in OS distros)?

Also, `syntheized` has a typo. And `NUMA` should be all capital letters.

In the end:
```
/* Set the distance to a default value on Linux 5.15 for our synthesized NUMA node */
```


<!-- Sent from Reviewable.io -->

2024-04-22 17:34 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: 0 of 1 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-common/topo_info.c` line 292 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4rCUu919i_KVumX8C:-Nw5newwAA5iMtIgRGCq:bdaek36) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L292)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to declare the bool here, just declare & assign it below
</blockquote></details>

good point
___
*[`pal/src/host/linux-common/topo_info.c` line 297 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t1CZ5wqvo5Y-sgwm:-Nw5nnnY79NVRYJZOeiW:b-jgv6dw) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L297)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`for example` -> `e.g.`
</blockquote></details>

ok, moving to latin (which is probably what i would have used if i would have written the original text :-)
___
*[`pal/src/host/linux-common/topo_info.c` line 298 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t2r75yIYqIpW7Pt6:-Nw5o27LAObvaE3xGnEI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for the word `will`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 298 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4t5k36V7L95tf33I7:-Nw5o3vxDHWcZotio-Tz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`numa` -> `NUMA`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4sWaf0s9hfCVnvVJT:-Nw5oCJ3A1-L2lSb8_QE:b-v1dm0a) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L433)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't use such a notation with `// !`. I suggest to just remove it.
</blockquote></details>

I added that comment as i was a longish if clause but i didn't like to break it into two separate if (X) and if(!X) clauses. But i'm fine removing it ...
___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4s_Eh1lDgBNPDwNl9:-Nw5p6Ds5UYhqJz6fIDB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L435)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is hard to read and understand -- it talks about two different things. What about this:
```
/* node_id field for each CPU core is by default zero, so no need to call set_node_id() for 
 * our single synthesized node 0 */
;

/* as above, set unsupported persistent huge pages to zero */
num_nodes[0]. ...
```
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 439 at r2](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nw4rfS9-vvfjcLZi4Up:-Nw5pOKW1YZVij5TurJG:b-269tbh) ([raw file](https://github.com/gramineproject/gramine/blob/904505976c5644b3a057eaf2ac1523f5774fe27d/pal/src/host/linux-common/topo_info.c#L439)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Ubuntu 22.04 is not relevant (i.e. it's a default in the Linux kernel, not in OS distros)?

Also, `syntheized` has a typo. And `NUMA` should be all capital letters.

In the end:
```
/* Set the distance to a default value on Linux 5.15 for our synthesized NUMA node */
```
</blockquote></details>

googling a bit, seems this 10 is the standard normalized relative cost coming from ACPI. Changed text accordingly


<!-- Sent from Reviewable.io -->

2024-04-23 07:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-04-23 07:18 UTC, dimakuv commented
Jenkins, test this please

2024-04-28 01:42 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXEbyvDTLXsR1vtHJx):*
"in" sounds a bit like "direct mode" was a mode of WSL



_Suggestion:_
```
[PAL] Support direct mode under Windows WSL
```
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXHrzoCFVogVetO-6f):*




_Suggestion:_
```
Windows Subsystem for Linux
```
___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXHypA9tKY-O3Wd9iJ):*




_Suggestion:_
```
and default to a synthetic, sane structure.
```
___
*[`pal/src/host/linux-common/topo_info.c` line 295 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXGPCr2lkp5DnWvdcI:-NwXGPCs6iafjcEF2DI5:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L295)):*
> ```C
>     /* Get the number of NUMA nodes on the system. By default, the number is 1. */
>     ret = iterate_ranges_from_file("/sys/devices/system/node/possible", get_ranges_end, &nodes_cnt);
>     if ((ret < 0) && (ret != -ENOENT)) {
> ```





_Suggestion:_
```C
if (ret < 0 && ret != -ENOENT) {
```
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXK7VZ7jVONAjJzSdF:-NwXK7VZ7jVONAjJzSdG:bulygo3) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L433)):*
> ```C
>         }
>     } else {
>         /* Node-id for each CPU core is by default zero, so no need to call set_node_id for
> ```

Is it?



_Code quote:_
```C
Node-id for each CPU core is by default zero
```
___
*[`pal/src/host/linux-common/topo_info.c` line 434 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKNCC-glUtuBeV13P:-NwXKNCC-glUtuBeV13Q:b-w3bb40) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L434)):*
> so no need to call set_node_id for our single synthesized NUMA node

This comment is IMO misleading, `set_node_id()` sets node ID in cores, not nodes. And it's not required for setting the IDs, it's just a helper function used in the parser, you could as well just set `cores[i].node_id` manually.
___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKBFbA0DUOvHM5WQA:-NwXKBFbA0DUOvHM5WQB:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L435)):*
> ```C
>         /* Node-id for each CPU core is by default zero, so no need to call set_node_id for
>          * our single synthesized NUMA node. */
>         ;
> ```

?


<!-- Sent from Reviewable.io -->

2024-04-29 08:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXK7VZ7jVONAjJzSdF:-NwcxO3pE_tOoXcJlYDT:b-okzpoz) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Hm, indeed, is it?
https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-common/topo_info.c#L311
___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKBFbA0DUOvHM5WQA:-NwcxU0z0UIZLeED4FrR:b48do7j) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

That was a suggestion from me, to make it explicit that we don't need to do anything in the code.

Anyway, it looks like we need a proper look over cores and setting their `node_id = 0;` explicitly.


<!-- Sent from Reviewable.io -->

2024-04-29 08:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKBFbA0DUOvHM5WQA:-NwcxdGnBoUPlNwuLP05:b9skhvb) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L435)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That was a suggestion from me, to make it explicit that we don't need to do anything in the code.

Anyway, it looks like we need a proper look over cores and setting their `node_id = 0;` explicitly.
</blockquote></details>

*look -> loop


<!-- Sent from Reviewable.io -->

2024-04-29 16:36 UTC, g2flyer reviewed
Thanks for the thorough look at code and finding the -1 != 0 issue. With the exception of the commit log comments where i need further guidance, i hope i have addressed your comments

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849#-:-NwehPqG7s4EqpnIjizn:bzfsr0q)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXEbyvDTLXsR1vtHJx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"in" sounds a bit like "direct mode" was a mode of WSL
</blockquote></details>

I gladly change that but as we currently have fixups i can do that only by squashing them which is against standard practice: should i do squash or just table it and resolve once everything is approved and i will autosquash and rebase to latest master?
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXHrzoCFVogVetO-6f):*
ditto
___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXHypA9tKY-O3Wd9iJ):*
ditto
___
*[`pal/src/host/linux-common/topo_info.c` line 295 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXGPCr2lkp5DnWvdcI:-NweY1t01UwpicEJnIfj:bvx0en5) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L295)):*
> ```C
>     /* Get the number of NUMA nodes on the system. By default, the number is 1. */
>     ret = iterate_ranges_from_file("/sys/devices/system/node/possible", get_ranges_end, &nodes_cnt);
>     if ((ret < 0) && (ret != -ENOENT)) {
> ```

i know they are unnecessary but i like the imho increased readability.  But i've changed it now
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXK7VZ7jVONAjJzSdF:-NweeFKN03sRuMoXqS7z:bq6ki03) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L433)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, indeed, is it?
https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-common/topo_info.c#L311
</blockquote></details>

Aargh, good catch.  I (wrongly) trusted the original version, just extended comment with what i thought the code relies on and every test seemed to work also with -1 thought to be 0. But that's clearly not the way it should be. Should be fixed now.
___
*[`pal/src/host/linux-common/topo_info.c` line 434 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKNCC-glUtuBeV13P:-NwegSoE4w_N2SQbn5PW:bqsjvpc) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L434)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> so no need to call set_node_id for our single synthesized NUMA node

This comment is IMO misleading, `set_node_id()` sets node ID in cores, not nodes. And it's not required for setting the IDs, it's just a helper function used in the parser, you could as well just set `cores[i].node_id` manually.
</blockquote></details>

i guess I meant "to" instead of "for".  But should be moot now anyway.   BTW: also was debating on whether directly setting `node_id` instead of calling the function.  But as the function also does slightly more, e.g., test whether thread is online and for more uniformity i decided to keep the function call, 


<!-- Sent from Reviewable.io -->

2024-04-29 17:49 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @g2flyer)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXEbyvDTLXsR1vtHJx):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I gladly change that but as we currently have fixups i can do that only by squashing them which is against standard practice: should i do squash or just table it and resolve once everything is approved and i will autosquash and rebase to latest master?
</blockquote></details>

We usually either leave the comment open until the final rebase and only then fix them, or add `squash!` commits (a Git feature similar to `fixup!`). Both are fine with me.
___
*[`pal/src/host/linux-common/topo_info.c` line 295 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXGPCr2lkp5DnWvdcI:-NwewuRM3t2n68NJOJUG:b-f0o78p) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L295)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

i know they are unnecessary but i like the imho increased readability.  But i've changed it now
</blockquote></details>

For me it decreases readability - there's more parentheses to parse and match with each other, and without them we'd have a standard, idiomatic C `if` with only the most popular operators inside. It could be useful if you used some operators with less obvious ordering, like mixing `^` and `&`.
___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKBFbA0DUOvHM5WQA:-NwexncgDVXPGS5TGHP0:b-389xc6) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L435)):*
> That was a suggestion from me, to make it explicit that we don't need to do anything in the code.

That's a weird convention IMO :) If it's not clear from the comment then I'd reword the comment instead.

Anyways, not relevant anymore.

UPDATE: actually still relevant, lol :)
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r4](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwexbkdCJPj5pR9GNDv:-NwexbkdCJPj5pR9GNDw:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/e3c87007e274c9f5ef3174dad06e94288078c6b9/pal/src/host/linux-common/topo_info.c#L433)):*
> ```C
>         }
>     } else {
>         /* Set node-id of active threads to synthesized NUME node with id 0. */
> ```





_Suggestion:_
```C
/* Set node-id of active threads to the synthesized NUMA node with id 0. */
```


<!-- Sent from Reviewable.io -->

2024-04-29 18:45 UTC, g2flyer reviewed
Aargh, i did see that typo but somehow the editor's save command got lost.  That said, it also gave me an opportunity to use the `git commit ---fixup=amend:<commit-id` variant of fixups which i didn't know before that it existed :-)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849#-:-Nwf9zVBBQ9XqT7Ssn37:b-nw3xc7)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2024-04-29 18:46 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/topo_info.c` line 435 at r3](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwXKBFbA0DUOvHM5WQA:-NwfASBx0Oce7pErVXk4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4024bf8329f0db7b1d7de7095b9d702966f53054/pal/src/host/linux-common/topo_info.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> That was a suggestion from me, to make it explicit that we don't need to do anything in the code.

That's a weird convention IMO :) If it's not clear from the comment then I'd reword the comment instead.

Anyways, not relevant anymore.

UPDATE: actually still relevant, lol :)
</blockquote></details>

Done.
___
*[`pal/src/host/linux-common/topo_info.c` line 433 at r4](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwexbkdCJPj5pR9GNDv:-NwfAPjM7j8z9otZi1qz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e3c87007e274c9f5ef3174dad06e94288078c6b9/pal/src/host/linux-common/topo_info.c#L433)):*
> ```C
>         }
>     } else {
>         /* Set node-id of active threads to synthesized NUME node with id 0. */
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-29 20:08 UTC, mkow submitted a review, later dismissed
Huh, I didn't know this one, we'll see if it works with `--autosquash` when rebasing :)

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849#-:-NwfRsDq744MkiWb0PQR:bld1bl6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-04-30 04:29 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @g2flyer)

___
*[`pal/src/host/linux-common/topo_info.c` line 446 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh2jER69F0E3svWY7B:-Nwh2jER69F0E3svWY7C:b-lxia1m) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L446)):*
> ```C
>         numa_nodes[0].nr_hugepages[HUGEPAGES_1G] = 0;
> 
>         /* Set  distance for synthesized NUMA node to standard node-local value provided by ACPI
> ```

2x white spaces?



_Code quote:_
```C
Set  distance
```


<!-- Sent from Reviewable.io -->

2024-04-30 06:01 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @g2flyer)

___
*[`-- commits` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZk0ZEY3PZSQjcp2A):*
Interestingly, this line wrap is at ~90 characters. What editor does this?

Just curious, since we'll rewrap this text anyway at 75 chars per line during final merge.
___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
Shouldn't Zongmin Gu also have `Signed-off-by` line? He should, please add (I hope that the original PR had this line, so you don't need to re-ask his permission.)
___
*[`pal/src/host/linux-common/topo_info.c` line 301 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh_cE9Bh3QlXs9j58J:-Nwh_cE9Bh3QlXs9j58K:bnwepms) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L301)):*
> ```C
>         return ret;
>     }
>     bool cpu_nodes_file_exists = (ret >= 0);
> ```

Why such a name? Wouldn't it be clearer if the name was `sys_node_dir_exists`? There is no "file `nodes`", as the name implies currently.


<!-- Sent from Reviewable.io -->

2024-04-30 16:28 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`-- commits` line 31 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZk0ZEY3PZSQjcp2A):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interestingly, this line wrap is at ~90 characters. What editor does this?

Just curious, since we'll rewrap this text anyway at 75 chars per line during final merge.
</blockquote></details>

git commit --amend and vi (with no auto-wrap) as editor, inherited from original version, reformated now
___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't Zongmin Gu also have `Signed-off-by` line? He should, please add (I hope that the original PR had this line, so you don't need to re-ask his permission.)
</blockquote></details>

I actually tried that initially but git(hub) refused as it seems to check that signed-off-by matches who pushes to have more than one signed-off, hence the move to co-authored-by. 
___
*[`pal/src/host/linux-common/topo_info.c` line 301 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh_cE9Bh3QlXs9j58J:-NwjnRPU87ZDd_7Qhf1N:bisc5ih) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why such a name? Wouldn't it be clearer if the name was `sys_node_dir_exists`? There is no "file `nodes`", as the name implies currently.
</blockquote></details>

historical reasons -- keeping close to original version ... -- but i see your (good) point. Changed ..
___
*[`pal/src/host/linux-common/topo_info.c` line 446 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh2jER69F0E3svWY7B:-Nwjmxx_AYf1NByGJ1jI:b-1xnger) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L446)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

2x white spaces?
</blockquote></details>

eagle eye :-) (fixed now)


<!-- Sent from Reviewable.io -->

2024-04-30 17:33 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @kailun-qin)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I actually tried that initially but git(hub) refused as it seems to check that signed-off-by matches who pushes to have more than one signed-off, hence the move to co-authored-by.
</blockquote></details>

I think the order of signed-off lines matters here. If you specify **your sign-off** as the last item, then GitHub won't complain. At least that's how we did it before, and we never experienced issues.
___
*[`pal/src/host/linux-common/topo_info.c` line 301 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh_cE9Bh3QlXs9j58J:-Nwk39omBs_c-wvzYFem:b-ssb6jj) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L301)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

historical reasons -- keeping close to original version ... -- but i see your (good) point. Changed ..
</blockquote></details>

Still wrong... Why `_file_`? I wanted `_dir_`, that was my main point.


<!-- Sent from Reviewable.io -->

2024-04-30 17:49 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the order of signed-off lines matters here. If you specify **your sign-off** as the last item, then GitHub won't complain. At least that's how we did it before, and we never experienced issues.
</blockquote></details>

I'm quite sure i was last at that time.  But thinking of it, there is also a bit a philosophical question here?  Doesn't 'Signed-off-by' also should reflect responsibility for the code and given that the code evolved quite a bit,  it would at least to have to cross-check with Zongmin that he is fine with also signing off   (or put differently, one could argue that the co-authored-by is the all the credit and none of the blame ;-) 
___
*[`pal/src/host/linux-common/topo_info.c` line 301 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh_cE9Bh3QlXs9j58J:-Nwk5eOCE9n1KSo3kMWP:bm9b1np) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still wrong... Why `_file_`? I wanted `_dir_`, that was my main point.
</blockquote></details>

I missed that part.  However, while true that WSL does not have the whole directory, the current code doesn't not test for the directory but only a file in that directory.  So unless we also test for the (absence of the) directory i still think "file" is more appropriate than "directory" ? And adding an additional test for absence of directory doesn't seem to me to really add anything?


<!-- Sent from Reviewable.io -->

2024-05-02 06:23 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @guzongmin and @kailun-qin)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I'm quite sure i was last at that time.  But thinking of it, there is also a bit a philosophical question here?  Doesn't 'Signed-off-by' also should reflect responsibility for the code and given that the code evolved quite a bit,  it would at least to have to cross-check with Zongmin that he is fine with also signing off   (or put differently, one could argue that the co-authored-by is the all the credit and none of the blame ;-)
</blockquote></details>

@guzongmin Would you be Ok to put the Signed-off-by line in this PR?

Otherwise we'll merge this PR without your explicit sign off (which is no problem too).
___
*[`pal/src/host/linux-common/topo_info.c` line 301 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nwh_cE9Bh3QlXs9j58J:-Nwrxn2c2lDqjIgKoWce:bf5h481) ([raw file](https://github.com/gramineproject/gramine/blob/123e5a679c99fd4a426941c6180caa55784a3457/pal/src/host/linux-common/topo_info.c#L301)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I missed that part.  However, while true that WSL does not have the whole directory, the current code doesn't not test for the directory but only a file in that directory.  So unless we also test for the (absence of the) directory i still think "file" is more appropriate than "directory" ? And adding an additional test for absence of directory doesn't seem to me to really add anything?
</blockquote></details>

Ok, that's fair enough. I'm resolving; also seems that no other reviewers cared about the name, so I'm just being too picky.


<!-- Sent from Reviewable.io -->

2024-05-02 07:11 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 34 at r5](https://reviewable.io/reviews/gramineproject/gramine/1849#-NwhZura9wnTohHkz2b5):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@guzongmin Would you be Ok to put the Signed-off-by line in this PR?

Otherwise we'll merge this PR without your explicit sign off (which is no problem too).
</blockquote></details>

In private conversation, @guzongmin told me that he doesn't use WSL and didn't check if this PR works. So I guess we shouldn't add his sign off. Let's keep as is.


<!-- Sent from Reviewable.io -->

2024-05-02 13:42 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-05-02 14:16 UTC, dimakuv commented
Jenkins, test this please

2024-05-04 16:50 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/1849#-Nx3UZYM0g1X5HHiFdti):*
I hope I merged the commits messages correctly, as it was tricky: these `amend!` commits added some changes but also (accidentally) reversed some others, so it's not clear which version was intended to be the final.


<!-- Sent from Reviewable.io -->

2024-05-04 16:50 UTC, mkow commented
Jenkins, retest this please

2024-05-05 02:08 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1849)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-05 11:02 UTC, merged