[Pal] Refactor simple types, part 1 (bools, enums, strings)
gramineproject/gramine pull request #185
Opened 2021-10-29 16:33 UTC by mkow

## Description of the changes 

There's no reason for PAL API to have custom types for these, which effectively were erasing types from the API. This PR replaces them with proper C types.

The rest of the types will be changed separately.

## How to test this PR? 

CI.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/185)

2021-10-29 18:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: 99 of 100 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/185#-MnC1rl5Etjmilbum6nT):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you mention the eventfd thing in the message? It's a behavior change in terms of syscalls, and some information might be useful if things break.

Something like: "in order to make the PAL API more regular, creating eventfds is now done with two calls on host: `eventfd()` with the initial value of 0, and `write()` with the desired initial value".
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 368 at r1](https://reviewable.io/reviews/gramineproject/gramine/185#-MnByQLv9e67tqx6maoS:-MnCGJg37a6gSqEvLGWL:b-m8fqz4) ([raw file](https://github.com/gramineproject/gramine/blob/a3258abba2744f0ce417ac4f197b6e921accd15f/Pal/include/pal/pal.h#L368)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Ouch, I didn't know we have the same function for both of these things...

What about files that can be both deleted *and* shut down, like Unix sockets? I'm not sure I want to know...
</blockquote></details>

hehe :)
___
*[Pal/src/host/Linux/db_files.c, line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/185#-MnC0DHQ7VMbob7HuTPz:-MnCGsPW3N5X_XBvbR_A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a3258abba2744f0ce417ac4f197b6e921accd15f/Pal/src/host/Linux/db_files.c#L63)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unnecessary cast?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-30 10:42 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-01 09:04 UTC, dimakuv requested changes
> Reviewed 96 of 100 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/185#-MnPhp4s-XyWrHoY5HeW):*
You also changed the names of the PAL APIs: `DkSegmentRegisterSet` and `DkSegmentRegisterGet`. Please mention it in a separate paragraph here.

UPDATE: That's the only thing I'm blocking on, the rest looks fine. Feel free to do final rebase and fix this comment.


<!-- Sent from Reviewable.io -->

2021-11-01 09:51 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: 99 of 100 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/185#-MnPhp4s-XyWrHoY5HeW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also changed the names of the PAL APIs: `DkSegmentRegisterSet` and `DkSegmentRegisterGet`. Please mention it in a separate paragraph here.

UPDATE: That's the only thing I'm blocking on, the rest looks fine. Feel free to do final rebase and fix this comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-01 09:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-11-01 10:31 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-02 01:43 UTC, boryspoplawski requested changes
> Reviewed 96 of 100 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 16 unresolved discussions (waiting on @mkow)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSszmf7n-6oAHYDDKQ):*
I do not understand how custom types (e.g. typedefs) can erase types from API.
___
*[common/include/api.h, line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnStGHh002MZgEv0z3a:-MnStGHh002MZgEv0z3b:b-6lwwvl) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/common/include/api.h#L87)):*
> ```objc
> /* Note: This macro is not intended for use when nbits == BITS_IN_TYPE(type) */
> #define SET_HIGHEST_N_BITS(type, nbits) (~(((uint64_t)1 << (BITS_IN_TYPE(type) - (nbits))) - 1))
> #define WITHIN_MASK(val, mask) (((val) | (mask)) == (mask))
> ```

This evaluates `mask` twice.
___
*[LibOS/shim/include/shim_flags_conv.h, line 53 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTCV318qL6LA9hpzuN:-MnTCV318qL6LA9hpzuO:b-1cezsn) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/include/shim_flags_conv.h#L53)):*
> ```objc
>     if (flags & O_CREAT)
>         return PAL_CREATE_TRY;
>     return PAL_OPEN_EXISTING;
> ```

This was very confusing before I've read `pal.h`, so I would prefer to rename the `pal_create_mode` type (see the comment in `pal.h`).
___
*[LibOS/shim/include/shim_internal.h, line 159 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTCkgnC6iDMDjcmYr0:-MnTCkgnC6iDMDjcmYr1:bnldqdg) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/include/shim_internal.h#L159)):*
> ```objc
>  */
> static inline int create_event(AEVENTTYPE* e) {
>      return pal_to_unix_errno(DkStreamOpen(URI_PREFIX_PIPE, PAL_ACCESS_RDWR, 0, PAL_CREATE_ALWAYS,
> ```

What about the `/*arg_name=*/` before `0`?
___
*[LibOS/shim/src/shim_init.c, line 558 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTDAGL07H_ujxVSbM1:-MnTDAGL07H_ujxVSbM2:bz1mzf6) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/shim_init.c#L558)):*
> ```C
>             return -ERANGE;
> 
>         ret = DkStreamOpen(uri, PAL_ACCESS_RDWR, 0, PAL_CREATE_ALWAYS, 0, &pipe);
> ```

What about `/*arg_name=*/0`?
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTEWGR1Os0OqV46hi8:-MnTEWGR1Os0OqV46hi9:b-ih2nls) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_eventfd.c#L23)):*
> ```C
> #include "toml_utils.h"
> 
> static int create_eventfd(PAL_HANDLE* efd, uint64_t initial_count, int flags) {
> ```

Why change type? Original Linux syscall uses `unsigned int`.
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTEQnHBe3nkKt4EACc:-MnTEQnHBe3nkKt4EACd:b-2d13r6) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_eventfd.c#L60)):*
> ```C
>     if (ret < 0 || write_size != sizeof(initial_count)) {
>         log_error("eventfd: failed to set initial count");
>         return pal_to_unix_errno(ret);
> ```

In case of short write this will return `0` - success.
___
*[LibOS/shim/src/sys/shim_socket.c, line 523 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTGonP1v3_DkapnZwT:-MnTGonP1v3_DkapnZwU:bz1mzf6) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L523)):*
> ```C
> 
>     PAL_HANDLE pal_hdl = NULL;
>     ret = DkStreamOpen(qstrgetstr(&hdl->uri), PAL_ACCESS_RDWR, 0, PAL_CREATE_ALWAYS, options,
> ```

What about `/*arg_name=*/0`?
___
*[LibOS/shim/src/sys/shim_socket.c, line 813 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHF6f6oVgGlnI4uBQ:-MnTHF6f6oVgGlnI4uBR:b4udrf0) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L813)):*
> ```C
>     PAL_HANDLE pal_hdl = NULL;
>     ret = DkStreamOpen(qstrgetstr(&hdl->uri), PAL_ACCESS_RDWR, /*share_flags=*/0,
>                        /*create=*/PAL_CREATE_ALWAYS,
> ```

What does `PAL_CREATE_ALWAYS` mean here? If we already have a TCP connection to a given `ip:port` this should fail?
___
*[LibOS/shim/src/sys/shim_socket.c, line 1118 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHZzH6cizJHeiraUE:-MnTHZzH6cizJHeiraUF:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L1118)):*
> ```C
>         if (sock->sock_state == SOCK_CREATED && !pal_hdl) {
>             ret = DkStreamOpen(URI_PREFIX_UDP, PAL_ACCESS_RDWR, /*share_flags=*/0,
>                                /*create=*/PAL_CREATE_ALWAYS,
> ```

ditto
___
*[LibOS/shim/test/regression/eventfd.c, line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHqev6j-y1dIom5Hy:-MnTHqev6j-y1dIom5Hz:b-coq09p) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/test/regression/eventfd.c#L117)):*
> ```C
>                 }
>                 printf("fd set: %d\n", pollfds[i].fd);
>                 printf("efd: %d, count: %lu, errno: %d\n", pollfds[i].fd, count, errno);
> ```

This `errno` makes no sense here (`printf` might have overwrote it)...
Not blocking - existing issue.
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 53 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnT0YrsC_ubt2FbMk0m:-MnT0YrsC_ubt2FbMk0n:b-kwjdwm) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/host/Linux-common/pal_flags_conv.h#L53)):*
> ```objc
> 
> static inline int PAL_CREATE_TO_LINUX_OPEN(enum pal_create_mode create) {
>     if (create == PAL_OPEN_EXISTING)
> ```

Why not `switch (create)`?
___
*[Pal/include/pal/pal.h, line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSwAPV3X-8TWeUrgg9:-MnSwAPV3X-8TWeUrggA:b9wnvi1) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L268)):*
> ```objc
> /*! stream create mode */
> enum pal_create_mode {
>     PAL_OPEN_EXISTING,     /*!< Fail if file does not exist */
> ```

This looks weird: it's called `OPEN_EXISTING`, but it's part of create mode... Why not call it `enum pal_open_mode`?
___
*[Pal/include/pal/pal.h, line 357 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnT4SXe4pGhZIEaGkpM:-MnT4SXf3SH82X5mJW7T:b5g4smj) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L357)):*
> ```objc
>                   const char* dest);
> 
> enum pal_delete {
> ```

Hm, maybe `enum pal_delete_mode`? It would match other similar types + you use `delete_mode` as argument names everywhere.
___
*[Pal/include/pal/pal.h, line 358 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSyJ1A-aN1Fy4x0vP0:-MnSyJ1A-aN1Fy4x0vP1:b-5hxtk2) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L358)):*
> ```objc
> 
> enum pal_delete {
>     PAL_DELETE_BOTH,  /*!< delete the whole resource / shut down both directions */
> ```

`BOTH` makes sense only for sockets (where we shut down both directions). Maybe something like `_ALL`, `_ALWAYS` would be better? Or even `PAL_DELETE_NORMAL`. The current version doesn't make sense for normal files...
___
*[Pal/regression/Directory.c [...]

2021-11-04 13:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: 68 of 100 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSszmf7n-6oAHYDDKQ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand how custom types (e.g. typedefs) can erase types from API.
</blockquote></details>

If the types are like `PAL_PTR` then they can ;)
Any wording change you suggest?
___
*[common/include/api.h, line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnStGHh002MZgEv0z3a:-MnekapDCPdbzbVYXweM:bbuk18b) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/common/include/api.h#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This evaluates `mask` twice.
</blockquote></details>

Yup, because it's a macro. The caller should expect this, like with all C macros.
___
*[LibOS/shim/include/shim_internal.h, line 159 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTCkgnC6iDMDjcmYr0:-Mnel8xPCxyM5BcAVgYE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/include/shim_internal.h#L159)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about the `/*arg_name=*/` before `0`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 558 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTDAGL07H_ujxVSbM1:-MnelU510BGPFs3YNeas:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/shim_init.c#L558)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about `/*arg_name=*/0`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTEWGR1Os0OqV46hi8:-MnelWRzDwbnXWQ6vdXT:b-28y3zk) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_eventfd.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why change type? Original Linux syscall uses `unsigned int`.
</blockquote></details>

Which is PITA, because the underlying type is explicitly said to always be `uint64_t`. Probably just some historical mess, no reason to copy it to our internal implementation, we only need to have `unsigned` in the syscall handler.
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTEQnHBe3nkKt4EACc:-Mnellqt0RAn9SFslE_1:bb7m3jc) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_eventfd.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In case of short write this will return `0` - success.
</blockquote></details>

oops
___
*[LibOS/shim/src/sys/shim_socket.c, line 523 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTGonP1v3_DkapnZwT:-MnemIZ791F6YtIG8kfe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L523)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about `/*arg_name=*/0`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 813 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHF6f6oVgGlnI4uBQ:-MnemMcnAU4S0lqzBDaD:b-6yjcyy) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L813)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What does `PAL_CREATE_ALWAYS` mean here? If we already have a TCP connection to a given `ip:port` this should fail?
</blockquote></details>

It actually doesn't mean anything, because this argument is ignored for sockets. This is a result of PAL API multiplexing too many things (IMO), so we end up with nonsensical arguments like this one :/
And I didn't want to pass "0" or something like it here, because it's actually just some value of the enum, plus, I'd like to enable enum checking at some point in CI (i.e. that we use enum constants instead of numbers everywhere).
___
*[LibOS/shim/test/regression/eventfd.c, line 117 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHqev6j-y1dIom5Hy:-MneniVwAbISrhAAYJrg:b-ds00zj) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/test/regression/eventfd.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This `errno` makes no sense here (`printf` might have overwrote it)...
Not blocking - existing issue.
</blockquote></details>

I'd leave it as is, I have no idea what's happening here. We go this path only on success, so why would we print errno? This whole test should be rewritten...
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 53 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnT0YrsC_ubt2FbMk0m:-Mneozbf-afPWOy4Hles:b-sda9zx) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/host/Linux-common/pal_flags_conv.h#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `switch (create)`?
</blockquote></details>

I don't have any preference in cases like this, but if you prefer a switch then I can change it.
___
*[Pal/include/pal/pal.h, line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSwAPV3X-8TWeUrgg9:-MnepciX4UUTB1iAwJgM:b-vicypb) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L268)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This looks weird: it's called `OPEN_EXISTING`, but it's part of create mode... Why not call it `enum pal_open_mode`?
</blockquote></details>

Because it's only about file creation behavior, "open mode" sounds like it should also contain things like non-blocking or appending.
___
*[Pal/include/pal/pal.h, line 357 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnT4SXe4pGhZIEaGkpM:-MneqIhS71K73LsQwq-c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L357)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, maybe `enum pal_delete_mode`? It would match other similar types + you use `delete_mode` as argument names everywhere.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 358 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSyJ1A-aN1Fy4x0vP0:-MneqPsfD6NG8bypuQN2:b-n9ptyt) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L358)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`BOTH` makes sense only for sockets (where we shut down both directions). Maybe something like `_ALL`, `_ALWAYS` would be better? Or even `PAL_DELETE_NORMAL`. The current version doesn't make sense for normal files...
</blockquote></det [...]

2021-11-09 13:18 UTC, boryspoplawski requested changes
> Reviewed 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/185#-Mo3csD09Xa1vwanG6mN:-Mo3csD09Xa1vwanG6mO:b-qfw4x7) (no related file):*
@mkow Docs pipeline failed

---
___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSszmf7n-6oAHYDDKQ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If the types are like `PAL_PTR` then they can ;)
Any wording change you suggest?
</blockquote></details>

Maybe just remove that part? It did not erase anything w.r.t. bools and strings.
___
*[common/include/api.h, line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnStGHh002MZgEv0z3a:-Mo3pPI51zpdBY2LMnAl:b-sonxw4) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/common/include/api.h#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, because it's a macro. The caller should expect this, like with all C macros.
</blockquote></details>

Then we should remove all places that put effort in not evaluating macro arguments twice (according to your logic they are useless anyway since the caller cannot assume them)? 
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/185#-Mo3lPdiB3SYjWniqBD4:-Mo3lPdiB3SYjWniqBD5:bfhmutz) ([raw file](https://github.com/gramineproject/gramine/blob/95c4903db5f6f06622e9da629987cdfd08985381/LibOS/shim/src/sys/shim_eventfd.c#L64)):*
> ```C
>     if (write_size != sizeof(initial_count)) {
>         log_error("eventfd: interrupted while setting initial count");
>         return -EINTR;
> ```

I don't like this `EINTR` here, but since this cannot happen in legitimate case and the feature is hidden behind an insecure flag (for good reasons) then probably let's leave it.
___
*[LibOS/shim/src/sys/shim_socket.c, line 813 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHF6f6oVgGlnI4uBQ:-Mo3m3O96eenOgo3DpGe:b28vmtq) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L813)):*
Then I would just do something like `/*create=unused*/0`. The current version is very misleading.

> I'd like to enable enum checking at some point in CI

Which gcc flag enables it? I couldn't find anything.
___
*[Pal/include/pal/pal.h, line 268 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSwAPV3X-8TWeUrgg9:-Mo3dEbQCZU5j0uTKMbv:bwb4l20) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/Pal/include/pal/pal.h#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because it's only about file creation behavior, "open mode" sounds like it should also contain things like non-blocking or appending.
</blockquote></details>

Then this should be `PAL_CREATE_NEVER` or something.


<!-- Sent from Reviewable.io -->

2021-11-10 16:30 UTC, boryspoplawski requested changes
> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 813 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHF6f6oVgGlnI4uBQ:-Mo9fMai6cAxQR9NlgVJ:b-lwuzmn) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L813)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not GCC, rather some linters (clang-tidy maybe? although I'm not sure how well it works with C)
I hope this will be resolved at some point, me and @pwmarcz discussed changing the PAL API to remove this multiplexing and probably will try doing that soon.
</blockquote></details>

Okey, but the issue with the current version is still here.
Maybe just write `0` until we enable such checks. Or add an option to the enum `PAL_CREATE_DUMMY_INVALID_OPTION_IGNORE_ME_SOMETHING = 0` (we can have 2 options with the same value) as a temporary workaround.


<!-- Sent from Reviewable.io -->

2021-11-11 23:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: 72 of 100 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 813 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHF6f6oVgGlnI4uBQ:-MoGJ4dzEUJhYakLgi4M:b-k8vcra) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L813)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Okey, but the issue with the current version is still here.
Maybe just write `0` until we enable such checks. Or add an option to the enum `PAL_CREATE_DUMMY_INVALID_OPTION_IGNORE_ME_SOMETHING = 0` (we can have 2 options with the same value) as a temporary workaround.
</blockquote></details>

Ok, I went for `PAL_CREATE_IGNORED`.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1118 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnTHZzH6cizJHeiraUE:-MoGJ8Wn5ZbxIxtbEG9N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/147a3804152e2de68de78161e351dd2a6e48cfc9/LibOS/shim/src/sys/shim_socket.c#L1118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 00:16 UTC, boryspoplawski reviewed
> Reviewed 22 of 28 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-11-12 00:19 UTC, boryspoplawski reviewed
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-11-12 00:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: 92 of 100 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/185#-MnSszmf7n-6oAHYDDKQ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, will do at rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 00:33 UTC, boryspoplawski approved these changes
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-11-12 02:29 UTC, boryspoplawski approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-11-12 06:45 UTC, pwmarcz approved these changes
> Reviewed 11 of 32 files at r5, 1 of 15 files at r6, 18 of 28 files at r7, 4 of 6 files at r8, 3 of 5 files at r9, 7 of 8 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-11-12 07:52 UTC, dimakuv approved these changes
> Reviewed 11 of 32 files at r5, 1 of 15 files at r6, 18 of 28 files at r7, 4 of 6 files at r8, 3 of 5 files at r9, 7 of 8 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/185)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-12 07:56 UTC, merged