Debug statsAdd a support for debug-stats dumping and resetting on demand dump reset
gramineproject/gramine pull request #1857
Opened 2024-04-23 11:30 UTC by TejaswineeL

## Description of the changes 

Currently Gramine does not support to display the stats values if user wants to collect only for a particular duration (e.g., only during perf benchmarking runs). This PR features displaying the stats data on demand using SIGUSR1 signal. That way user can collect data only for a particular duration. This also eliminates the noise added in the stats data during the start and stop of the process.

## How to test this PR? 

Please follow the instruction [here ](https://gramine.readthedocs.io/en/latest/performance.html#enabling-per-thread-and-process-wide-sgx-stats)to enable SGX stats. Now execute the workload in Gramine SGX. Send SIGUSR1 signal using command `kill -SIGUSR1 <pid>` to dump and reset the stats. This will show the current stats values on the command line and then will reset the stats values. Example:
	1. Add below manifest options to gramine/CI-Examples/redis/redis-server.manifest.template.
	       `sgx.debug = true`
	       `sgx.enable_stats=true`
	2. Build the redis example: `make clean && make SGX=1`
	3. Run redis server: `gramine-sgx redis-server &`
	4. Get the redis server pid and run `kill -SIGUSR1 <pid>` to dump and reset the stats. 
	5. Immediately run the benchmarks using command `src/src/redis-benchmark`
	6. Once benchmark run is complete, run `kill -SIGUSR1 <pid>`  again to get the stats values corresponding to only the 
	    benchmark execution. 
	8. Summation(total) value of stats values of all the threads are displayed at the end.
	9. That’s how we get the stats values and the summation of them corresponding to the benchmark run. The stats are 
	    displayed on the command line.

Same steps can be tried with MongoDB, MySQL etc..

2024-04-29 10:11 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 0 of 3 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 203 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA-WYl9skFIzUP0_0y:-NwdGMfrC9hOpb4Ui_iI:b-ne5wb3) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TID can legitimately be `0`. Please use another struct field to determine whether this array item is a legit thread.
</blockquote></details>

   

Approach 1:

As other structures storing children thread ids are not accessible to host\_exception.c (based on the makefile),  
I propose the below:  
  
at [(https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L165)](https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L165)  
we have g\_enclave\_thread\_num keeping track of the count of tid assignment of the array thread\_tids\[\]  
I have an idea of using this variable to decide legit thread\_tids\[\] inorder to send SIGUSR1 signal  
we will be doing below changes if we go ahead with this idea.

https://github.com/TejaswineeL/gramine/blob/14a8be3adcb801ed4a9a1ff65afb178448111d86/pal/src/host/linux-sgx/host_exception.c#L197 
/* using g_enclave_thread_num in the for loop condition check */
``spinlock\_lock(&g\_enclave\_thread\_map\_lock);``
    ``for (size\_t i = 1; i < g\_enclave\_thread\_num; i++) {``
        ``int child\_tid = ((struct enclave\_dbginfo\*)DBGINFO\_ADDR)->thread\_tids\[i\];``
        ``log\_always("child tid with g\_enclave\_thread\_num %d", child\_tid);``
            ``DO\_SYSCALL(tkill, child\_tid, SIGUSR1);``
            ``signal\_counter++;``
    ``}``
``spinlock\_unlock(&g\_enclave\_thread\_map\_lock);``

https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L25
/\* removing static keyword so that we can use these variables in host\_exception.c file \*/
``spinlock\_t g\_enclave\_thread\_map\_lock = INIT\_SPINLOCK\_UNLOCKED;``
``size\_t g\_enclave\_thread\_num = 0;``

[stats_PR/changes_stats_or/gramine/pal/src/host/linux-sgx/pal_tcb.h](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_tcb.h)
/* adding below lines to the file included in host_exception.c*/
``extern size\_t g\_enclave\_thread\_num;``
``extern spinlock\_t g\_enclave\_thread\_map\_lock;``

Approach 2:

All the children thread ids are present at location /proc/pid/task. This location only stores the main process id and children thread ids.  
I can validate thread ids of the array thread\_tids\[\] with the tids present at /proc/<pid>/task during execution  
Below snippet gives us the children thread ids  
  
-defining the filepath whre we can find the children thread ids
``snprintf(filepath, sizeof(filepath), "/proc/%d/task/", g\_host\_pid);``

-Fetching the children tids from the filepath location with files

   ``struct dirent \*entry;``
   ``dir = opendir(filename);``
    ``if (dir == NULL) {``
        ``perror("Error opening directory");``
        ``return -1;``
    ``}``
    ``while ((entry = readdir(dir)) != NULL) {``
        ``if (entry->d\_type == DT\_DIR && atoi(entry->d\_name) != g\_host\_pid) {``
           ``if (strcmp(entry->d\_name, ".") == 0 || strcmp(entry->d\_name, "..") == 0) {``
                ``// Skip current directory and parent directory``
                ``continue;``
            ``}``
            ``printf(" thread id from proc %s", entry->d\_name);``
         ``}``
    ``}``
    ``closedir(dir);``

Kindly, Let us know which of the above approaches would you like.


<!-- Sent from Reviewable.io -->

2024-05-02 12:20 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 0 of 3 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 203 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA-WYl9skFIzUP0_0y:-NwtCXiK9HEeKeBJFAJQ:b-oxths3) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L203)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Approach 1:

As other structures storing children thread ids are not accessible to host\_exception.c (based on the makefile),  
I propose the below:  
  
at [(https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L165)](https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L165)  
we have g\_enclave\_thread\_num keeping track of the count of tid assignment of the array thread\_tids\[\]  
I have an idea of using this variable to decide legit thread\_tids\[\] inorder to send SIGUSR1 signal  
we will be doing below changes if we go ahead with this idea.

https://github.com/TejaswineeL/gramine/blob/14a8be3adcb801ed4a9a1ff65afb178448111d86/pal/src/host/linux-sgx/host_exception.c#L197 
/* using g_enclave_thread_num in the for loop condition check */
spinlock\_lock(&g\_enclave\_thread\_map\_lock);
    for (size\_t i = 1; i < g\_enclave\_thread\_num; i++) {
        int child\_tid = ((struct enclave\_dbginfo\*)DBGINFO\_ADDR)->thread\_tids\[i\];
        log\_always("child tid with g\_enclave\_thread\_num %d", child\_tid);
            DO\_SYSCALL(tkill, child\_tid, SIGUSR1);
            signal\_counter++;
    }
spinlock\_unlock(&g\_enclave\_thread\_map\_lock);

https://github.com/gramineproject/gramine/blob/53f5511123d51e7baf9cf98ffc7d3ad6096e6c6b/pal/src/host/linux-sgx/host_thread.c#L25
/\* removing static keyword so that we can use these variables in host\_exception.c file \*/
spinlock\_t g\_enclave\_thread\_map\_lock = INIT\_SPINLOCK\_UNLOCKED;
size\_t g\_enclave\_thread\_num = 0;

[stats_PR/changes_stats_or/gramine/pal/src/host/linux-sgx/pal_tcb.h](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_tcb.h)
/* adding below lines to the file included in host_exception.c*/
extern size\_t g\_enclave\_thread\_num;
extern spinlock\_t g\_enclave\_thread\_map\_lock;

Approach 2:

All the children thread ids are present at location /proc/pid/task. This location only stores the main process id and children thread ids.  
I can validate thread ids of the array thread\_tids\[\] with the tids present at /proc/<pid>/task during execution  
Below snippet gives us the children thread ids  
  
-defining the filepath whre we can find the children thread ids
snprintf(filepath, sizeof(filepath), "/proc/%d/task/", g\_host\_pid);

-Fetching the children tids from the filepath location with files

   struct dirent \*entry;
   dir = opendir(filename);
    if (dir == NULL) {
        perror("Error opening directory");
        return -1;
    }
    while ((entry = readdir(dir)) != NULL) {
        if (entry->d\_type == DT\_DIR && atoi(entry->d\_name) != g\_host\_pid) {
           if (strcmp(entry->d\_name, ".") == 0 || strcmp(entry->d\_name, "..") == 0) {
                // Skip current directory and parent directory
                continue;
            }
            printf(" thread id from proc %s", entry->d\_name);
         }
    }
    closedir(dir);

Kindly, Let us know which of the above approaches would you like.
</blockquote></details>

Approach1 logs
Sharing below the logs showing threads_tids[] array contents and value of g_enclave_thread_num used in approach1,

![image.png](https://files.reviewableusercontent.io/images/reviewable/56070200/kMdKh-jkGfjMuR_Q9ufc8vH1/image.png)

Here, threads_tids[0] always denotes the main thread tid (which we dont have to send SIGUSR1 signal to)threads_tids[1]  to threads_tids[5] shows the children tids. threads_tids[6] and threads_tids[7] are empty.

Approach2 
Sharing below the contents of  dir "/proc/pid/task " showing children tids

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/56070200/_SZtrhi-brTb8_hofHtQK2al/image.png)

Plan is to validate children tids got from threads_tids[] with children tids of '/proc/pid/task'

Kindly, Let us know which approach would you prefer.


<!-- Sent from Reviewable.io -->

2024-05-03 06:58 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxE3_pDV86BdQtlVRb):*
We don't use fixups to fixups. Each next fixup is supposed to be a fixup to the first (main) commit. Please check other PRs from other maintainers, who they do it.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA0rVo3cF-9rPTu51n:-Nwx9bAw8O8OvdJrsD0p:b-ipcjar) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I feel like you added a lot of unnecessary includes. Please remove the not-needed ones.
</blockquote></details>

Is `dirent.h` needed? This header is about file system directories, but you don't use them in your patch?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 203 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA-WYl9skFIzUP0_0y:-Nwx9DCBBy3qPF9MiuoH:bf4dych) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L203)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Approach1 logs
Sharing below the logs showing threads_tids[] array contents and value of g_enclave_thread_num used in approach1,

![image.png](https://files.reviewableusercontent.io/images/reviewable/56070200/kMdKh-jkGfjMuR_Q9ufc8vH1/image.png)

Here, threads_tids[0] always denotes the main thread tid (which we dont have to send SIGUSR1 signal to)threads_tids[1]  to threads_tids[5] shows the children tids. threads_tids[6] and threads_tids[7] are empty.

Approach2 
Sharing below the contents of  dir "/proc/pid/task " showing children tids

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/56070200/_SZtrhi-brTb8_hofHtQK2al/image.png)

Plan is to validate children tids got from threads_tids[] with children tids of '/proc/pid/task'

Kindly, Let us know which approach would you prefer.
</blockquote></details>

I'm sorry that I confused you. I now realized that TID 0 (= PID 0) is the kernel PID on the host Linux. So actually we're safe here, and you can consider `tid == 0` as "no actual Gramine thread".

So your code is correct, and please excuse me that you had to go research the possibilities :(
___
*[`pal/src/host/linux-sgx/host_exception.c` line 240 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA0GYU0kJ9FvsVCCFs:-NwxDM613bS7DomhfSTK:b-dcdijd) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L240)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this means that main thread does **not** reset his local stats?
</blockquote></details>

Could you answer my question? I still think that the main thread doesn't reset its local stats.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 194 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBAOI2cagXCOL-jTc:-NwxBAOI2cagXCOL-jTd:bfw1cf) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L194)):*
> ```C
> 
> static int send_sigusr1_signal_to_children(void) {
>     int signal_counter= 0;
> ```

` = ` -- add space
___
*[`pal/src/host/linux-sgx/host_exception.c` line 194 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBn7W0Wcgk2ajL7y6:-NwxBn7W0Wcgk2ajL7y7:b7d237q) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L194)):*
> ```C
> 
> static int send_sigusr1_signal_to_children(void) {
>     int signal_counter= 0;
> ```

That's a bad variable name. Please rename similar to how you have it in another func: `no_of_children`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 194 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBuhl2278qVi_22il:-NwxBuhl2278qVi_22im:b-nb6mns) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L194)):*
> ```C
> 
> static int send_sigusr1_signal_to_children(void) {
>     int signal_counter= 0;
> ```

We don't like to use `int` in cases of clearly unsigned "counter" integers. So please use `size_t`, that's the safest option.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBFJt-VxJ_ARv5mXZ:-NwxBFJt-VxJ_ARv5mX_:b-5z3de5) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L196)):*
> ```C
>     int signal_counter= 0;
> 
>     for (size_t i = 1; i < MAX_DBG_THREADS; i++) {
> ```

Why do you start with 1?

If you do this to NOT send the signal to yourself, then please add a func argument and use it for checking:
```
static int send_sigusr1_signal_to_children(int my_tid) {
    ...
    for (size_t i = 0; i < MAX_DBG_THREADS; i++) {
        int child_tid = ((struct enclave_dbginfo*)DBGINFO_ADDR)->thread_tids[i];
        if (child_tid == my_tid)
            continue;
}
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 198 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBQp6CXlKL67ydjl3:-NwxBQp6CXlKL67ydjl4:b-1e6sdq) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L198)):*
> ```C
>     for (size_t i = 1; i < MAX_DBG_THREADS; i++) {
>         int child_tid = ((struct enclave_dbginfo*)DBGINFO_ADDR)->thread_tids[i];
>         if(child_tid > 0) {
> ```

No need for `> 0`, simply:
```
if (child_tid) {
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 208 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-Nwx9mOd6Ak0IQudlnGL:-Nwx9mOd6Ak0IQudlnGM:b-1euyrk) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L208)):*
> ```C
> 
> static void dump_and_reset_stats(void)
> {
> ```

Please use our coding style in this PR. In particular, here `{` should be on the same line as the func declaration:
```
static void dump_and_reset_stats(void) {
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 209 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-Nwx9vXZ4zMjuYrKxJ_t:-Nwx9vX_Cx76qLT5mDAz:b-qn51wi) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L209)):*
> ```C
> static void dump_and_reset_stats(void)
> {
>     static atomic_int no_of_children_visited = 0;
> ```

You don't need `atomic_int` if you use `__atomic_xxx()` operations. These are two different and unrelated ways of using atomics.

Here, you can just use `int`.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 210 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxCaNP3H54Xvdv8RrC:-NwxCaNP3H54Xvdv8RrD:b-84a30a) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L210)):*
> ```C
> {
>     static atomic_int no_of_children_visited = 0;
>     static const uint64_t LOOP_ATTEMPTS_MAX = 10000;   /* rather arbitrary */
> ```

Why you keep  [...]

2024-05-03 10:32 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA0rVo3cF-9rPTu51n:-NwxooxT88LQNOTe1dcL:bhmo7rr) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is `dirent.h` needed? This header is about file system directories, but you don't use them in your patch?
</blockquote></details>

That's right. Its not needed. I will remove in the upcoming patch.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-Nw9zcA52swJ3QpNEM-d:-NwxpMwO9Y55Fn1_2qe-:bi7hguz) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this macro is declared somewhere else, why not `#include <where-it-declared.h>`?
</blockquote></details>

The Macro is declared in '#include "gdb_integration/sgx_gdb.h"'. This is already included.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 240 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA0GYU0kJ9FvsVCCFs:-NwxuXw02w6jtngzr8aT:bp7gvhl) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L240)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you answer my question? I still think that the main thread doesn't reset its local stats.
</blockquote></details>

Main thread does reset its local stats. Unconditional code snippet shown below does that.
https://github.com/gramineproject/gramine/pull/1857/files#diff-36ddf4f0901a94224ef8f08faa82ad332c9afc3ed952d5950e5597f110464ec7R235 

Here's the logs of the main thread stats dump and reset
![image.png](https://files.reviewableusercontent.io/images/reviewable/56070200/CPicHYlU7UbXnU4u2SJa-WOD/image.png)
___
*[`pal/src/host/linux-sgx/host_exception.c` line 196 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxBFJt-VxJ_ARv5mXZ:-NwxrDYc37H_XqnS1bjn:b-6ed2mi) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you start with 1?

If you do this to NOT send the signal to yourself, then please add a func argument and use it for checking:
```
static int send_sigusr1_signal_to_children(int my_tid) {
    ...
    for (size_t i = 0; i < MAX_DBG_THREADS; i++) {
        int child_tid = ((struct enclave_dbginfo*)DBGINFO_ADDR)->thread_tids[i];
        if (child_tid == my_tid)
            continue;
}
```
</blockquote></details>

Yes, 'thread_tids[0]' is the main thread id. It is the same tid to which we send 'kill -SIGUSR1' signal via command line. 
I will add the check you suggested I will use var name as 'main_tid' instead of my_tid.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 229 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxDpg76IPPh_aJOtVn:-NwxwKYl5szUUQ5UywSp:bt6dgl1) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You sure we want to print this out? Sounds rather useless, because `update_and_print_stats()` will also print an information line.
</blockquote></details>

The intention is to differentiate usual display of stats (as a result of 'sgx.enable_stats=true') from 'dump and reset' of stats (with 'kill -SIGUSR1').  Also, it will acknowledge the receival of 'kill -SIGUSR1' signal
___
*[`pal/src/host/linux-sgx/host_thread.c` line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-Nw9zNGGCv4FimVpLp_x:-Nwxzv-7567i_qFRbCUM:b-1wmjj4) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_thread.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still don't see a need in this `arch_prctl()` syscall. Why did you add it here?
</blockquote></details>

I see that without adding `arch_prctl()`, the stats are getting reset successfully. 
Removing `arch_prctl()` in the upcoming patch.


<!-- Sent from Reviewable.io -->

2024-05-08 10:30 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxMk0eKCmdB53Oq5n77:-NxMk0eKCmdB53Oq5n78:b-v153vi) (no related file):*
Please update the `Performance tuning and analysis` page in the documentation accordingly.

You can take inspiration from this patch: https://github.com/gramineproject/gramine/pull/1751/files

___
___
*[`pal/src/host/linux-sgx/host_exception.c` line 240 at r1](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwA0GYU0kJ9FvsVCCFs:-NxMikpb9XPJ8qtFdKls:bfi889o) ([raw file](https://github.com/gramineproject/gramine/blob/841c11e402ed2f39871a96fe0e80561f3935e673/pal/src/host/linux-sgx/host_exception.c#L240)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Main thread does reset its local stats. Unconditional code snippet shown below does that.
https://github.com/gramineproject/gramine/pull/1857/files#diff-36ddf4f0901a94224ef8f08faa82ad332c9afc3ed952d5950e5597f110464ec7R235 

Here's the logs of the main thread stats dump and reset
![image.png](https://files.reviewableusercontent.io/images/reviewable/56070200/CPicHYlU7UbXnU4u2SJa-WOD/image.png)
</blockquote></details>

Ok, you're right, `pal_host_tcb_reset_stats()` is called unconditionally
___
*[`pal/src/host/linux-sgx/host_exception.c` line 229 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxDpg76IPPh_aJOtVn:-NxMiwBh6kNnWETVkWxU:bxixagr) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L229)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

The intention is to differentiate usual display of stats (as a result of 'sgx.enable_stats=true') from 'dump and reset' of stats (with 'kill -SIGUSR1').  Also, it will acknowledge the receival of 'kill -SIGUSR1' signal
</blockquote></details>

Ok. Don't we want the same message on the main thread?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 248 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-Nwx7Iz1844oM7WgYwBO:-NxMj65IDKElQ2dzZIRX:b-t65dy1) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There's no need in `return` in a void function. Remove this line.
</blockquote></details>

You forgot about this comment.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 192 at r5](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxMMaF3CSVMfejZlYsj:-NxMMaF3CSVMfejZlYsk:bojdihb) ([raw file](https://github.com/gramineproject/gramine/blob/b31b7d76c9b99bb66d5439899898df7781e8442e/pal/src/host/linux-sgx/host_exception.c#L192)):*
> ```C
> 
> static size_t send_sigusr1_signal_to_children(pid_t main_tid) {
>     size_t no_of_signal_sent = 0;
> ```

`no_of_signal_sent` -> `no_of_signals_sent`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 213 at r5](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxMjAFI2vKtPuwe6IvP:-NxMjAFI2vKtPuwe6IvQ:b-cxyxzb) ([raw file](https://github.com/gramineproject/gramine/blob/b31b7d76c9b99bb66d5439899898df7781e8442e/pal/src/host/linux-sgx/host_exception.c#L213)):*
> ```C
>         size_t no_of_children = send_sigusr1_signal_to_children(g_host_pid);
> 
>         while ((__atomic_load_n(&no_of_children_visited, __ATOMIC_ACQUIRE)) < (no_of_children)) {
> ```

There's no reason to have `no_of_children` in parentheses, please remove them
___
*[`pal/src/host/linux-sgx/host_exception.c` line 219 at r5](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxMizkK6xEPw_zxMV71:-NxMizkK6xEPw_zxMV72:b-1lv1lo) ([raw file](https://github.com/gramineproject/gramine/blob/b31b7d76c9b99bb66d5439899898df7781e8442e/pal/src/host/linux-sgx/host_exception.c#L219)):*
> ```C
>         __atomic_store_n(&no_of_children_visited, 0, __ATOMIC_RELEASE);
>     } else {
>         log_always("----- DUMPTING and RESETTING SGX STATS -----");
> ```

`DUMPING` (you have a typo)
___
*[`pal/src/host/linux-sgx/host_thread.c` line 70 at r5](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxMjJJq0qLNVLRjdMiS:-NxMjJJq0qLNVLRjdMiT:b-rdfi0d) ([raw file](https://github.com/gramineproject/gramine/blob/b31b7d76c9b99bb66d5439899898df7781e8442e/pal/src/host/linux-sgx/host_thread.c#L70)):*
> ```C
>                    pid, __atomic_load_n(&g_eenter_cnt, __ATOMIC_ACQUIRE), __atomic_load_n(&g_eexit_cnt, __ATOMIC_ACQUIRE),
>                    __atomic_load_n(&g_aex_cnt, __ATOMIC_ACQUIRE), __atomic_load_n(&g_sync_signal_cnt, __ATOMIC_ACQUIRE),
>                    __atomic_load_n(&g_async_signal_cnt, __ATOMIC_ACQUIRE));
> ```

Please now re-wrap these lines to 100-chars-per-line limit.


<!-- Sent from Reviewable.io -->

2024-05-10 11:20 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 1 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 229 at r4](https://reviewable.io/reviews/gramineproject/gramine/1857#-NwxDpg76IPPh_aJOtVn:-NxXDkPQ3x6zw5STyStV:b-gn5vhi) ([raw file](https://github.com/gramineproject/gramine/blob/dfb0310318943fa14aa12c9db79ce30fcf7d5586/pal/src/host/linux-sgx/host_exception.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok. Don't we want the same message on the main thread?
</blockquote></details>

Yes we want. Adding it.


<!-- Sent from Reviewable.io -->

2024-05-10 12:45 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`Documentation/performance.rst` line 106 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXW7c72MfQsaQeWlv5:-NxXW7c72MfQsaQeWlv6:biik8hc) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/Documentation/performance.rst#L106)):*
> ```reStructuredText
>    trends.
> 
> It is also possible to reset the performance statistics interactively, using
> ```

`to reset the performance statistics` -> `to dump and reset SGX-related statistics`
___
*[`Documentation/performance.rst` line 108 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXWIzk3zOKpfVyTdGn:-NxXWIzlEmZOCz7_FtDx:b-bpylnt) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/Documentation/performance.rst#L108)):*
> ```reStructuredText
> It is also possible to reset the performance statistics interactively, using
> ``SIGUSR1`` signal. This helps to collect performance statistics only for a
> particular period e.g., skipping the Gramine startup and application
> ```

Please add a comma before `e.g.`
___
*[`Documentation/performance.rst` line 111 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXVukt58kiumiM-lGe:-NxXVukt58kiumiM-lGf:b-g3b2u9) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/Documentation/performance.rst#L111)):*
> ```reStructuredText
> initialization time and concentrating only on the actual application processing.
> Send ``SIGUSR1`` using command ``kill -SIGUSR1 <gramine-pid>``  (note the
> minus sign before <gramine-pid>). Sending multiple ``SIGUSR1`` will result
> ```

Please remove the `(note the minus sign ... )` sentence, it is not relevant here.
___
*[`Documentation/performance.rst` line 113 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXWR93-2aEY10z3bFt:-NxXWR93-2aEY10z3bFu:b91fbv0) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/Documentation/performance.rst#L113)):*
> ```reStructuredText
> minus sign before <gramine-pid>). Sending multiple ``SIGUSR1`` will result
> in a sequential dump and reset of the statistics, each dump and reset of
> statistics will be done after the previous ``SIGUSR1``.
> ```

The whole `Sending multiple ...` sentence seems redundant, as it is clear that "dump and reset" means that the statistics will be reset, and one can send a next SIGUSR1.

Please just remove the whole sentence.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 215 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXWly6DzIBF8E4sqdr:-NxXWly6DzIBF8E4sqds:b4ntz24) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/pal/src/host/linux-sgx/host_exception.c#L215)):*
> ```C
>         while ((__atomic_load_n(&no_of_children_visited, __ATOMIC_ACQUIRE)) < no_of_children) {
>             DO_SYSCALL(sched_yield);
>         }
> ```

Please add an empty line after this line
___
*[`pal/src/host/linux-sgx/host_exception.c` line 221 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXXEyE9lZBIKH_i-Fe:-NxXXEyE9lZBIKH_i-Ff:bbdgm41) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/pal/src/host/linux-sgx/host_exception.c#L221)):*
> ```C
>     } else {
>         log_always("----- DUMPING and RESETTING SGX STATS -----");
>         update_and_print_stats(/*process_wide=*/false);
> ```

Actually, when you have many child threads, won't their outputs be mixed? Looks like we need some locking here...
___
*[`pal/src/host/linux-sgx/host_exception.c` line 287 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXWwOm-lQEU5mGVTYg:-NxXWwOm-lQEU5mGVTYh:b33x15d) ([raw file](https://github.com/gramineproject/gramine/blob/c876141adb555b4669713d57c17cba6924744705/pal/src/host/linux-sgx/host_exception.c#L287)):*
> ```C
>     ret = set_signal_handler(SIGUSR1, handle_sigusr1);
>     if (ret < 0)
>         goto err;
> ```

Actually, can you move this set of signal handler to right-after `set_signal_handler(SIGCONT)`? There it would make more sense (the order of signals will be more readable).


<!-- Sent from Reviewable.io -->

2024-05-14 10:16 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 2 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 221 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXXEyE9lZBIKH_i-Fe:-NxqWV-6Euaq9UUCYq3s:bijci5o) ([raw file](https://github.com/gramineproject/gramine/blob/337d385ec9d35d4655010741658bd79f4737aed5/pal/src/host/linux-sgx/host_exception.c#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, when you have many child threads, won't their outputs be mixed? Looks like we need some locking here...
</blockquote></details>

Yes, that's right, their outputs get mixed. I added a change, where "DUMPING and RESETTING SGX STATS" log is displayed only once. The log is displayed once per ``SIGUSR1`` signal, at the start of the dumping and resetting operation.


<!-- Sent from Reviewable.io -->

2024-05-14 11:44 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`-- commits` line 27 at r7](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxquZucASRZ-4a4wWlj):*
Please don't perform git merge (and don't allow atomatic git merge). That's for the future.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 221 at r6](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxXXEyE9lZBIKH_i-Fe:-NxqtswX4bwCCxtNbJZv:b9sjlx6) ([raw file](https://github.com/gramineproject/gramine/blob/337d385ec9d35d4655010741658bd79f4737aed5/pal/src/host/linux-sgx/host_exception.c#L221)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Yes, that's right, their outputs get mixed. I added a change, where "DUMPING and RESETTING SGX STATS" log is displayed only once. The log is displayed once per ``SIGUSR`` signal, at the start of the dumping and resetting operation.
</blockquote></details>

Ok, this looks reasonable to me.


<!-- Sent from Reviewable.io -->

2024-05-14 11:51 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxqwBhB1jvPh_Z8xurM:-NxquXr26syyGztjbbyV:b-8hus56) (no related file):*
I followed the steps in the PR description and successfully tested the Redis example. For me, the PR is ready. Thanks for this effort @TejaswineeL !

___
___
*[`-- commits` line 27 at r7](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxquZucASRZ-4a4wWlj):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't perform git merge (and don't allow atomatic git merge). That's for the future.
</blockquote></details>

Accidentally put a blocking comment. Unblocking now.


<!-- Sent from Reviewable.io -->

2024-05-14 11:51 UTC, dimakuv commented
Jenkins, test this please

2024-05-15 06:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 35 at r7](https://reviewable.io/reviews/gramineproject/gramine/1857#-NxuymzZCUVmiRU-EKsx:-NxuymzZCUVmiRU-EKsy:b-jaeqsa) ([raw file](https://github.com/gramineproject/gramine/blob/c8317ba58670f437521b4c996380a1fcbe99da1e/pal/src/host/linux-sgx/host_thread.c#L35)):*
> ```C
>     static atomic_ulong g_aex_cnt          = 0;
>     static atomic_ulong g_sync_signal_cnt  = 0;
>     static atomic_ulong g_async_signal_cnt = 0;
> ```

I didn't notice this before, but all these variables use `atomic_` (C99 atomics syntax). We decided to *not* use it in new code, so please modify all these to be simple `uint64_t`:
```
    static uint64_t g_eenter_cnt       = 0;
    ...
    static uint64_t g_async_signal_cnt = 0;
```


<!-- Sent from Reviewable.io -->

2024-05-16 06:41 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-20 10:37 UTC, TejaswineeL reviewed
@dimakuv , Could you please help me understand how to fix the 2 jenkins build test failure.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857#-:-NyKZoQn2TQdOIJBkP_k:bsfxtq0)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-22 10:34 UTC, TejaswineeL reviewed
@kailun-qin I am not able to see the jenkins failure reports
Could you please help me understand how to fix the 2 jenkins build test failure

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857#-:-NyUo1t91kicNJ6sSjmB:bm3q3n0)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-22 11:54 UTC, mkow reviewed
These two pipelines are not working properly yet, please ignore. They should have been disabled, sorry.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857#-:-NyV8evX4Q3u3WETSa0l:bzcj4hy)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-23 05:22 UTC, TejaswineeL reviewed
@mkow , No worries. Dimitri has approved the changes. Could you please have a look at the PR and let me know your comments.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857#-:-NyYtDyR32EIPyLyo0rt:b-162310)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-05 07:08 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O10iEuDCo8G_R-kBKur:-O10iEuE4tsL_ewJhkVQ:b7m4jll) (no related file):*
The PR looks good to me. I'll wait for other reviewers, and when the PR will get enough approvals, I'll also test it one last time.

___


<!-- Sent from Reviewable.io -->

2024-07-11 15:18 UTC, mkow requested changes
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XJ09gCNKHYVTxGyt0):*




_Suggestion:_
```
Add support for dumping and resetting debug stats on demand
```
___
*[`Documentation/performance.rst` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XKrfk8X82lI0VnYcN:-O1XKrfk8X82lI0VnYcO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/Documentation/performance.rst#L110)):*
> ```reStructuredText
> particular period, e.g. skipping the Gramine startup and application
> initialization time and concentrating only on the actual application processing.
> Send ``SIGUSR1`` using command ``kill -SIGUSR1 <PGID>``.
> ```





_Suggestion:_
```reStructuredText
``kill -SIGUSR1 -<PGID>``
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 18 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XLRciAlAgptShSush:-O1XLRciAlAgptShSusi:b-sll32u) ([raw file](https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_exception.c#L18)):*
> ```C
>                      */
> ```

Please don't remove the spacing, keep at least one line.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XM9j_-9hFG6m0leRG:-O1XM9j_-9hFG6m0leRH:b-1eau0s) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/pal/src/host/linux-sgx/host_exception.c#L191)):*
> ```C
> }
> 
> static size_t send_sigusr1_signal_to_children(pid_t main_tid) {
> ```

Why is this needed? #1751 didn't require such logic.


<!-- Sent from Reviewable.io -->

2024-07-12 07:09 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 2 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XJ09gCNKHYVTxGyt0):*
Done
___
*[`Documentation/performance.rst` line 110 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XKrfk8X82lI0VnYcN:-O1_XyW84d1z7Zd8mmKm:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/Documentation/performance.rst#L110)):*
> ```reStructuredText
> particular period, e.g. skipping the Gramine startup and application
> initialization time and concentrating only on the actual application processing.
> Send ``SIGUSR1`` using command ``kill -SIGUSR1 <PGID>``.
> ```

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 18 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XLRciAlAgptShSush:-O1_XvXO4NGNopWZSBbA:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_exception.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't remove the spacing, keep at least one line.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XM9j_-9hFG6m0leRG:-O1_YEaz3OkAt1nfQaqY:b-l40jc0) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/pal/src/host/linux-sgx/host_exception.c#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this needed? #1751 didn't require such logic.
</blockquote></details>

 The stats are printed for a thread only when the thread receives the  ``SIGUSR1`` signal  . If we send SIGUSR1 signal to main thread on commandline, it does not automatically send it to the children threads. It will only be received by the main thread. Thats why  ``send_sigusr1_signal_to_children``makes sure that all the children thread also receive`` SIGUSR1 `` signal and every thread dumps and resets the stats. 

Its different from #1751 in terms of output where 
stats are printed per process as shown below

![image.png](https://files.reviewableusercontent.io/images/reviewable/56070200/y5MgnnxTy1Z4ipjgYXvYjDBU/image.png)


<!-- Sent from Reviewable.io -->

2024-07-13 18:30 UTC, mkow requested changes
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @TejaswineeL)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XJ09gCNKHYVTxGyt0):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Done
</blockquote></details>

That doesn't work this way, now if you try `git rebase --autosquash` git won't know to which commit it should squash that last fixup commit, because there's none matching the one-liner.
Let's just leave it as is, we'll fix that during the final rebase.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XM9j_-9hFG6m0leRG:-O1hA5DO4BgvlFH8BdId:b-3c50xd) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/pal/src/host/linux-sgx/host_exception.c#L191)):*
Please stop pasting screenshots of text...

> It will only be received by the main thread.

That's not true, Linux doesn't guarantee that - only that _some_ thread will receive it.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1hEeOp0roT5-TURfRc:b-uehe90) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
> ```C
> 
>     if (g_sgx_enable_stats)
>         dump_and_reset_stats();
> ```

This is bad, we shouldn't execute any non-trivial logic in the signal handler, otherwise you'll have the same problems as in older versions of #1751. You have _a lot_ of race conditions here, same as #1751 originally had.


<!-- Sent from Reviewable.io -->

2024-07-15 08:33 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XM9j_-9hFG6m0leRG:-O1pKSi93WhwN2vL3Kvx:bpwlzuf) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/pal/src/host/linux-sgx/host_exception.c#L191)):*
@mkow This is needed because the logic is different from #1751.

In PR #1751, all threads were dumping their info to a shared `perf.data` file on each AEX event. See https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_entry.S#L91

So to "reset" the perf.data, all that was required to be done was to close the old perf-data file and open a new perf-data file. This is enough to be done in one thread (under a lock), and all other threads would automatically pick up the new perf-data file.

In this PR, however, there are no events on which all threads "do something". So we need to generate this event ourselves, which is the SIGUSR1 signal.

Unfortunately, outside programs like `kill` do **not** have the ability to send some signal to **all threads of the same process**. (What `kill` can do is to send the signal to **all processes in the same process group**, but this chooses one thread from each process.)

So that's why we have this additional for loop -- we must trigger some event so that each thread updates and dumps its own local information (about the statistics on EENTER, EEXIT, etc). Also, this for loop guarantees "atomicity" -- the main thread waits for other threads to update their statistics and then prints the process-wide statistics.

>> It will only be received by the main thread.

> That's not true, Linux doesn't guarantee that - only that _some_ thread will receive it.

@mkow This is irrelevant for this PR, whether Linux sends the signal to the *main thread* or to *some thread* (indeed, Linux sends SIGUSR1 to some thread, not necessarily to the main thread).

But if you look at the implementation of this PR, the logic is basically "whichever thread received SIGUSR1, this thread is designated as main and broadcasts this signal to all other threads in this process". So if you want to, we can rename the `main_tid` variable to something like `this_tid`. But I think the logic is generally sound.

UPDATE: Ok, I see that `dump_and_reset_stats()` uses `g_host_pid` which **is** the main thread. I outlined the fix for this problem (and for the other problem of doing complex things in the signal handler), see my other comment.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1pMsxt7jYYl5bAzvSa:b-98jr3l) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is bad, we shouldn't execute any non-trivial logic in the signal handler, otherwise you'll have the same problems as in older versions of #1751. You have _a lot_ of race conditions here, same as #1751 originally had.
</blockquote></details>

Ok, yes, that's true...

I guess we need the following:
1. Do smth like this:
```
/* application threads on Linux can never be 0, so this "no-op" default is safe */
bool g_trigger_stats_reset = false;
int g_stats_reset_main_thread_tid = 0;

int64_t expected_tid = 0;
if (__atomic_compare_exchange_n(&g_stats_reset_main_thread, &expected_tid, 
        DO_SYSCALL(gettid), /*weak=*/false,
        __ATOMIC_ACQ_REL, __ATOMIC_RELAXED) == true) {
    /* first thread that gets SIGUSR1 -- this thread gets the signal from the host OS */
    __atomic_store_n(&g_trigger_stats_reset, true, __ATOMIC_RELEASE);
} else {
    /* child thread gets SIGUSR1 -- mark that it needs to dump the stats */
    PAL_HOST_TCB* tcb = pal_get_host_tcb();
    tcb->reset_stats = true; /* TODO: you need to introduce this new field */
}
```
2. Call `dump_and_reset_stats()` function after this line: https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_entry.S#L91 (i.e., on each AEX)
3. Modify `dump_and_reset_stats()` to:
   - reset `g_trigger_stats_reinit` and `g_stats_reset_main_thread` after all child threads are done (if `gettid()` tells us that we are the main thread)
   - reset `tcb->reset_stats = false` in each child thread (if `gettid()` tells us that we are not the main thread)


<!-- Sent from Reviewable.io -->

2024-07-15 11:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1qE2M_0FVsi_TWGSYu:b-phnkxx) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, yes, that's true...

I guess we need the following:
1. Do smth like this:
```
/* application threads on Linux can never be 0, so this "no-op" default is safe */
bool g_trigger_stats_reset = false;
int g_stats_reset_main_thread_tid = 0;

int64_t expected_tid = 0;
if (__atomic_compare_exchange_n(&g_stats_reset_main_thread, &expected_tid, 
        DO_SYSCALL(gettid), /*weak=*/false,
        __ATOMIC_ACQ_REL, __ATOMIC_RELAXED) == true) {
    /* first thread that gets SIGUSR1 -- this thread gets the signal from the host OS */
    __atomic_store_n(&g_trigger_stats_reset, true, __ATOMIC_RELEASE);
} else {
    /* child thread gets SIGUSR1 -- mark that it needs to dump the stats */
    PAL_HOST_TCB* tcb = pal_get_host_tcb();
    tcb->reset_stats = true; /* TODO: you need to introduce this new field */
}
```
2. Call `dump_and_reset_stats()` function after this line: https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_entry.S#L91 (i.e., on each AEX)
3. Modify `dump_and_reset_stats()` to:
   - reset `g_trigger_stats_reinit` and `g_stats_reset_main_thread` after all child threads are done (if `gettid()` tells us that we are the main thread)
   - reset `tcb->reset_stats = false` in each child thread (if `gettid()` tells us that we are not the main thread)
</blockquote></details>

Isn't this still racy? What if another `SIGUSR1` arrives while processing a previous `SIGUSR1`?


<!-- Sent from Reviewable.io -->

2024-07-15 13:36 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1qac_7Anqyl1aCBmXI:b-tuhcum) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
> What if another `SIGUSR1` arrives while processing a previous `SIGUSR1`?

Should we even consider this case? It's the user who sends SIGUSR1, so it becomes user responsibility not to spam the application with these signals. (And it's easy for the user to learn whether the last handling finished -- if the user sees `Total SGX stats for process`, then the user knows it is safe to send another SIGUSR1)


<!-- Sent from Reviewable.io -->

2024-07-15 13:42 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1qbfmF5_l4T_CtEJh8:b-7i34vk) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> What if another `SIGUSR1` arrives while processing a previous `SIGUSR1`?

Should we even consider this case? It's the user who sends SIGUSR1, so it becomes user responsibility not to spam the application with these signals. (And it's easy for the user to learn whether the last handling finished -- if the user sees `Total SGX stats for process`, then the user knows it is safe to send another SIGUSR1)
</blockquote></details>

I had checked this possibility with existing changes, gramine does not allow spamming of signals.
a signal is only received when it has already processed the previous signal. I did not have to add any changes for this, it was already taken care of.


<!-- Sent from Reviewable.io -->

2024-07-15 13:51 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O1qcKKvD-VQfi9LX1Du:b-lwwxiq) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
> Should we even consider this case?

Yes. We don't want to have any race conditions, especially ones which may lead to memory corruptions (I'm not sure if this one can, didn't analyze it that closely).

> It's the user who sends SIGUSR1, so it becomes user responsibility not to spam the application with these signals. (And it's easy for the user to learn whether the last handling finished -- if the user sees `Total SGX stats for process`, then the user knows it is safe to send another SIGUSR1)

a) Someone can automate it and send it from a script.
b) Something may randomly lag (e.g. because of swapping) and the user may send another signal thinking that the first one somehow didn't arrive (because they didn't see any output yet).

> I had checked this possibility with existing changes, gramine does not allow spamming of signals.  
a signal is only received when it has already processed the previous signal. I did not have to add any changes for this, it was already taken care of.

Why do you think so? There's no such mechanism here, you just install the signal handler here and that's all (in this very PR).


<!-- Sent from Reviewable.io -->

2024-07-23 08:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O2TeYkqCgahQk5eE8d6:b7bfemv) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Should we even consider this case?

Yes. We don't want to have any race conditions, especially ones which may lead to memory corruptions (I'm not sure if this one can, didn't analyze it that closely).

> It's the user who sends SIGUSR1, so it becomes user responsibility not to spam the application with these signals. (And it's easy for the user to learn whether the last handling finished -- if the user sees `Total SGX stats for process`, then the user knows it is safe to send another SIGUSR1)

a) Someone can automate it and send it from a script.
b) Something may randomly lag (e.g. because of swapping) and the user may send another signal thinking that the first one somehow didn't arrive (because they didn't see any output yet).

> I had checked this possibility with existing changes, gramine does not allow spamming of signals.  
a signal is only received when it has already processed the previous signal. I did not have to add any changes for this, it was already taken care of.

Why do you think so? There's no such mechanism here, you just install the signal handler here and that's all (in this very PR).
</blockquote></details>

So it was easier to write my own code: https://github.com/gramineproject/gramine/pull/1944

Unfortunately, there's this DEBUG vs no-DEBUG build issue. I'm not sure (1) why assembly breaks in non-DEBUG build, and (2) how we want to compile profiling support and this SGX-stats-reset support -- in DEBUG mode only, or in release mode too.


<!-- Sent from Reviewable.io -->

2024-07-30 12:29 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r11, 2 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`-- commits` line 4 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O32bE6gBlCA7WTk4X2Y):*
It should be added here that the PR was co-developed by Dmitrii Kuvaiskii (me). I will add the Co-developed and Signed-off-by lines during final merge.
___
*[`-- commits` line 62 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O32bMdZD5BHcir6MonO):*
Who is this person? Do we need to add this person to the list of Co-developed-by and Signed-off-by in the first commit message?
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 139 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O32aKqRETVVNt-ncLHi:-O32aKqSDnUsrv-4sWNY:bvdtcbs) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/enclave_ocalls.c#L139)):*
> ```C
>     }
> 
>     long result = COPY_UNTRUSTED_VALUE(&req->result);
> ```

This is taken from https://github.com/gramineproject/gramine/pull/1955

This PR will need to be rebased when that one is merged. Blocking until then.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 191 at r10](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1XM9j_-9hFG6m0leRG:-O32awXI04RNI7qGv-CZ:b-yc88xi) ([raw file](https://github.com/gramineproject/gramine/blob/7cdaacf68dde23bbfb35f1be336dbddd9d8a302b/pal/src/host/linux-sgx/host_exception.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow This is needed because the logic is different from #1751.

In PR #1751, all threads were dumping their info to a shared `perf.data` file on each AEX event. See https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_entry.S#L91

So to "reset" the perf.data, all that was required to be done was to close the old perf-data file and open a new perf-data file. This is enough to be done in one thread (under a lock), and all other threads would automatically pick up the new perf-data file.

In this PR, however, there are no events on which all threads "do something". So we need to generate this event ourselves, which is the SIGUSR1 signal.

Unfortunately, outside programs like `kill` do **not** have the ability to send some signal to **all threads of the same process**. (What `kill` can do is to send the signal to **all processes in the same process group**, but this chooses one thread from each process.)

So that's why we have this additional for loop -- we must trigger some event so that each thread updates and dumps its own local information (about the statistics on EENTER, EEXIT, etc). Also, this for loop guarantees "atomicity" -- the main thread waits for other threads to update their statistics and then prints the process-wide statistics.

>> It will only be received by the main thread.

> That's not true, Linux doesn't guarantee that - only that _some_ thread will receive it.

@mkow This is irrelevant for this PR, whether Linux sends the signal to the *main thread* or to *some thread* (indeed, Linux sends SIGUSR1 to some thread, not necessarily to the main thread).

But if you look at the implementation of this PR, the logic is basically "whichever thread received SIGUSR1, this thread is designated as main and broadcasts this signal to all other threads in this process". So if you want to, we can rename the `main_tid` variable to something like `this_tid`. But I think the logic is generally sound.

UPDATE: Ok, I see that `dump_and_reset_stats()` uses `g_host_pid` which **is** the main thread. I outlined the fix for this problem (and for the other problem of doing complex things in the signal handler), see my other comment.
</blockquote></details>

This PR now follows the approach that I outlined in #1944. Resolving this comment.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O32b0rfBoPM65v6Lae8:b-yb35rt) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Thank You @dimakuv for resolving the above issue.
</blockquote></details>

You're welcome.

FYI: I verified that this PR and #1944 have the same implementation.


<!-- Sent from Reviewable.io -->

2024-08-04 18:23 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 235 at r11](https://reviewable.io/reviews/gramineproject/gramine/1857#-O1hEeOo8nOU32eJQIfW:-O3TcHCd98CdeGdCX8MC:byj1jgh) ([raw file](https://github.com/gramineproject/gramine/blob/26c4684723bad994ab080d12cf59b3d0076852d2/pal/src/host/linux-sgx/host_exception.c#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're welcome.

FYI: I verified that this PR and #1944 have the same implementation.
</blockquote></details>

What has happened here? Why do we have two PRs with the same contents?


<!-- Sent from Reviewable.io -->

2024-08-09 00:39 UTC, mkow requested changes
> Reviewed 2 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 47 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oUXxw0GHsnvGaPZer:-O3oUXxw0GHsnvGaPZes:bq6mm3u) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L47)):*
> are dumped and reset on the next AEX.

The current implementation dumps them also on the next normal enclave entry, which means that they _must_ be dumped right now (because in all cases we'll be returning to the enclave after the return from the `SIGUSR1` handler).
___
*[`pal/src/host/linux-sgx/host_exception.c` line 52 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oV8Ar6oWL9kyoxiZY:-O3oV8Ar6oWL9kyoxiZZ:btomng1) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L52)):*
> On each AEX

Also on normal enclave entry?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O3oSl6c9DhaKanHoAXk:b63p0qu) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
> ```C
>         if (__atomic_compare_exchange_n(&g_stats_reset_leader_tid, &expected_tid,
>                                         DO_SYSCALL(gettid), /*weak=*/false,
>                                         __ATOMIC_ACQ_REL, __ATOMIC_RELAXED) == true) {
> ```

What if the current thread was interrupted in `sgx_ocall_exit()` and was chosen to be the leader? This whole feature breaks then?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O3oGC0X0CWPGwWqGiJe:b3ozbb0) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
> ```C
>      * fortunately this variable is set up even in non-debug builds */
>     for (size_t i = 0; i < MAX_DBG_THREADS; i++) {
>         int follower_tid = ((struct enclave_dbginfo*)DBGINFO_ADDR)->thread_tids[i];
> ```

This is racy, `enclave_dbginfo` may be modified concurrently while we're here.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGcMP3oBh8DTVyFA-:-O3oGcMP3oBh8DTVyFA0:bh9nqe9) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
> ```C
>      * fortunately this variable is set up even in non-debug builds */
>     for (size_t i = 0; i < MAX_DBG_THREADS; i++) {
>         int follower_tid = ((struct enclave_dbginfo*)DBGINFO_ADDR)->thread_tids[i];
> ```

`enclave_dbginfo` is intended only for GDB integration, we cannot use it in non-GDB code. This region isn't even guaranteed to exist: https://github.com/gramineproject/gramine/blob/462168cd941b748996c1d4434395c3c7500e9fdb/pal/src/host/linux-sgx/host_main.c#L605-L606
___
*[`pal/src/host/linux-sgx/host_exception.c` line 338 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oG7Pn2RQ4apCaEEUJ:-O3oG7PoEdOC__8_Wm8t:b6e0vux) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L338)):*
> ```C
>             continue;
> 
>         DO_SYSCALL(tkill, follower_tid, SIGUSR1);
> ```

This may hit a thread in another process. Use `tgkill` instead.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 345 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oIwAW09TX3xbwlIty:-O3oIwAW09TX3xbwlItz:b-sgczfe) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L345)):*
> ```C
> 
> /* called on each AEX and OCALL (in normal context), see host_entry.S */
> void dump_and_reset_stats(void) {
> ```

This name is misleading, this function most of the time _doesn't_ dump or reset stats.



_Code quote:_
```C
dump_and_reset_stats
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oTAca4qSuXxHaZT3G:-O3oTAca4qSuXxHaZT3H:btbfm00) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L363)):*
> ```C
>         size_t followers_num = send_sigusr1_to_followers(leader_tid);
> 
>         while ((__atomic_load_n(&followers_visited_num, __ATOMIC_ACQUIRE)) < followers_num)
> ```

What if one of the threads exited in the meantime? (e.g. if it was interrupted in `sgx_ocall_exit()`) Won't we inf-loop here?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 367 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oYJP94MdGLpK1dbP1:-O3oYJPA8mf2uTk-xUx0:b-vhubs8) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L367)):*
> ```C
> 
>         update_and_print_stats(/*process_wide=*/true);
>         pal_host_tcb_reset_stats();
> ```

`update_and_print_stats(/*process_wide=*/true);` above already does that (except setting `tcb->reset_stats` to `false`)
___
*[`pal/src/host/linux-sgx/host_thread.c` line 31 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oTfA_4Tpb66OVX2kP:-O3oTfA_4Tpb66OVX2kQ:bcgjvre) ([raw file](https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/pal/src/host/linux-sgx/host_thread.c#L31)):*
> ```C
> /* this function is called only on thread/process exit (never in the middle of thread exec) */
> void update_and_print_stats(bool process_wide) {
>     static atomic_ulong g_eenter_cnt       = 0;
> ```

Why this change?



_Suggestion:_
```C
static uint64_t
```
___
*[`pal/src/host/linux-sgx/host_thread.c` line 78 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oYXes9nuCB78pGcwd:-O3oYXes9nuCB78pGcwe:b-mer6or) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_thread.c#L78)):*
> ```C
>         __atomic_store_n(&g_aex_cnt, 0, __ATOMIC_RELEASE);
>         __atomic_store_n(&g_sync_signal_cnt, 0, __ATOMIC_RELEASE);
>         __atomic_store_n(&g_async_signal_cnt, 0, __ATOMIC_RELEASE);
> ```

Why did you add this zeroing here?
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 108 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oWmKm64bY_M4AeFas:-O3oWmKm64bY_M4AeFat:b-2jzlze) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/pal_tcb.h#L108)):*
> ```objc
>     int32_t last_async_event;      /* last async signal, reported to the enclave on ocall return */
>     int* start_status_ptr;         /* pointer to return value of clone_thread */
>     bool reset_stats;              /* if true, dump SGX stats and reset them on next AEX event */
> ```

Or enclave entry.



_Code quote:_
```objc
them on next AEX event *
```


<!-- Sent from Reviewable.io -->

2024-08-09 01:16 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogorMDixQy0M-bykx:-O3ogorMDixQy0M-byky:b-lebmie) (no related file):*
This code is still quite complicated (as you can see by the number of race conditions found). Do we really want this feature? It's just some performance logging which seems to be non-trivial to implement correctly. I'm especially uneasy to include this in release builds, but I'm not even sure this feature is worth the effort.

___
___
*[`pal/src/host/linux-sgx/host_entry.S` line 45 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogBNLDZxdP0S4-YWp:-O3ogBNLDZxdP0S4-YWq:b-q7iy3) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L45)):*
> ```
> 
>     movq $EENTER, %rax
>     enclu
> ```

What if a new thread is entering the enclave for the first time here and gets `SIGUSR1`? It's already on the map so the leader will be waiting for it, but this thread will enter the enclave and may exit via some blocking ocall, which won't be interrupted by `SIGUSR1` and will deadlock.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O3oczyyBMWLkp-ukmB7:b4b5dms) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
> ```
>     pushq %rbp
>     .cfi_adjust_cfa_offset 8
>     movq %rsp, %rbp
> ```

Was this a bug? That `rbp` wasn't restored?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 228 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ofTWqBbudnNkJcAiQ:-O3ofTWqBbudnNkJcAiR:b36kjmi) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L228)):*
Moving this out into a separate discussion:

> (2) how we want to compile profiling support and this SGX-stats-reset support -- in DEBUG mode only, or in release mode too.

So, why isn't this a debug-only feature? We wouldn't need to execute all this complicated logic in release builds.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 333 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3o_twz8j65ISlNSrNH:-O3o_twz8j65ISlNSrNI:b-7wghh5) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L333)):*
> ```C
>     /* we re-use DBGINFO_ADDR special variable (that is primarily used by GDB for debugging),
>      * fortunately this variable is set up even in non-debug builds */
>     for (size_t i = 0; i < MAX_DBG_THREADS; i++) {
> ```

This, but it's racy, this variable is protected by `g_enclave_thread_map_lock`.



_Suggestion:_
```C
for (size_t i = 0; i < g_enclave_thread_num; i++) {
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O3ocOLp7_d8mUaRDgfv:b-hisk4h) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is racy, `enclave_dbginfo` may be modified concurrently while we're here.
</blockquote></details>

Why not using `enclave_thread_map` instead?


<!-- Sent from Reviewable.io -->

2024-08-09 07:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_entry.S` line 45 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogBNLDZxdP0S4-YWp:-O3pq8tyCb6lasOmMqS_:b-85dpn2) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L45)):*
I do not understand the exact scenario here, let's first understand the specifics.

> What if a new thread is entering the enclave for the first time here and gets `SIGUSR1`?

Do you mean it's the **user-triggered** SIGUSR1, or the **leader-thread-triggered** SIGUSR1? From your following description, you seem to imply the leader-thread-triggered SIGUSR1, so I'll assume this.

> may exit via some blocking ocall, which won't be interrupted by `SIGUSR1`

Why would the thread be interrupted again by SIGUSR1? The thread already got SIGUSR1 and was interrupted, as you stated in your first sentence. So the thread got SIGUSR1 at that time and memorized this as `tcb->reset_stats = true`.

Now, on the very next AEX **or** OCALL, this thread will call `dump_and_reset_stats()` and will actually dump the statistics. Since you say `exit via some blocking ocall`, this is covered by newly added code under `.Lsgx_entry` -- the `dump_and_reset_stats()` function will be called before performing the OCALL.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O3prt1s34iL5uxt9o2L:b5uy055) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Was this a bug? That `rbp` wasn't restored?
</blockquote></details>

Yes and no. The RBP register is "stable" in debug mode (i.e., when GCC builds without optimizations), so the caller func saves it in its prologue and then restores it back. In release mode (GCC with optimizations), the base frame pointer can be omitted and RBP is used as any other general purpose register.

So now that we removed this code from under `ifdef DEBUG`, we have to do this. Previously, we could skip this.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 47 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oUXxw0GHsnvGaPZer:-O3psY4n9EaaWoBtDywG:b-hiyru3) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L47)):*
> The current implementation dumps them also on the next normal enclave entry

No, that's incorrect. The current implementation dumps the stats also **right-before the next OCALL**. See `.Lsgx_entry` in the asm code, and be aware that the name "sgx_entry" is totally misleading -- it means "the entry from the SGX enclave to the untrusted OCALL execution" (legacy weird name).

But it's true that I forgot to mention this "right-before executing the next OCALL in untrusted runtime" part in all this text.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 52 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oV8Ar6oWL9kyoxiZY:-O3psvHu6IO-lm_ASJPo:b9hmu75) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> On each AEX

Also on normal enclave entry?
</blockquote></details>

ditto (on enclave exit, right-before executing the OCALL)
___
*[`pal/src/host/linux-sgx/host_exception.c` line 228 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ofTWqBbudnNkJcAiQ:-O3pt0xA1Jb2DjUy6aEH:bo6c98g) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Moving this out into a separate discussion:

> (2) how we want to compile profiling support and this SGX-stats-reset support -- in DEBUG mode only, or in release mode too.

So, why isn't this a debug-only feature? We wouldn't need to execute all this complicated logic in release builds.
</blockquote></details>

We do this also in release mode because `sgx.enable_stats` always worked in release mode too. There's just nothing that requires it to be in debug mode (in contrast to e.g. profiling support, which requires debug symbols).

So this whole "let's allow this also in release mode" approach is purely for backwards-compatibility.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O3ptNwE8I81fZoipmt5:b-1dp4y2) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if the current thread was interrupted in `sgx_ocall_exit()` and was chosen to be the leader? This whole feature breaks then?
</blockquote></details>

This looks rather benign -- the SIGUSR1 event will then be just "lost" -- the current thread will exit without sending SIGUSR1 to other threads. So the SIGUSR1 event from the user will be just lost -- not amazing, but I guess we should live with this possibility.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 333 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3o_twz8j65ISlNSrNH:-O3ptwXH0p0pFTZUjyE8:b-lj3s9d) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L333)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This, but it's racy, this variable is protected by `g_enclave_thread_map_lock`.
</blockquote></details>

Yep, I think this is better. We can do this.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O3pu1grD1_oa_WW04OU:bbwbxxj) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not using `enclave_thread_map` instead?
</blockquote></details>

Yes, we can do this.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGcMP3oBh8DTVyFA-:-O3pu3fI8phreqaiVBzg:bscscqa) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`enclave_dbginfo` is intended only for GDB integration, we cannot use it in non-GDB code. This region isn't even guaranteed to exist: https://github.com/gramineproject/gramine/blob/462168cd941b748996c1d4434395c3c7500e9fdb/pal/src/host/linux-sgx/host_main.c#L605-L606
</blockquote></details>

Good point, we can move to `g_enclave_thread_map`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 338 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oG7Pn2RQ4apCaEEUJ:-O3pu9Cd3pnEAr_is8WL:b-brx22u) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L338)):*
<details><summary><i>Previously, mk [...]

2024-08-09 12:41 UTC, TejaswineeL reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogorMDixQy0M-bykx:-O3r8D1396rGmingKVeT:b-13j6k2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This code is still quite complicated (as you can see by the number of race conditions found). Do we really want this feature? It's just some performance logging which seems to be non-trivial to implement correctly. I'm especially uneasy to include this in release builds, but I'm not even sure this feature is worth the effort.
</blockquote></details>

   

Yes, it is 'once in for all' effort.
For every new workload's performance tuning, this would be that starting point of performance analysis.
Without this we would not be able to exclude the enclave loading/exit noise etc.
This will help pin-point the area of performance optimization.  
 Will it be still complicated if we enable this feature only in debug mode?  

@dimakuv  what do you think about @mkow 's above comment?

___
___
*[`pal/src/host/linux-sgx/host_exception.c` line 47 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oUXxw0GHsnvGaPZer:-O3qncRB0Y12XazSQ954:b-x4sfdi) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> The current implementation dumps them also on the next normal enclave entry

No, that's incorrect. The current implementation dumps the stats also **right-before the next OCALL**. See `.Lsgx_entry` in the asm code, and be aware that the name "sgx_entry" is totally misleading -- it means "the entry from the SGX enclave to the untrusted OCALL execution" (legacy weird name).

But it's true that I forgot to mention this "right-before executing the next OCALL in untrusted runtime" part in all this text.
</blockquote></details>

Can I reframe the statement as below 
` so that this thread's statistics are dumped and reset right-before executing the next OCALL in untrusted runtime .`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O3qr0yODAJzbqhb8rpn:b-gn7jgl) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we can do this.
</blockquote></details>

We had started with `enclave_thread_map` itself. But that approach was not useful. The point when, the `SIGUSR1` signal is received, `enclave_thread_map` does not have all the threads. `enclave_thread_map` fails to give us all the `follower_tids` (the experiment was done on MySql workload i could get only 2 thread_tid in `enclave_thread_map` out of the total 40 threads)

To avoid the race condition we can add spinlock on `DBGINFO_ADDR`
please let me know your opinion on this.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGcMP3oBh8DTVyFA-:-O3qtVgF2DF5nIkXkcz6:b-q1n1yt) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good point, we can move to `g_enclave_thread_map`
</blockquote></details>

We had started with `enclave_thread_map` itself. But that approach was not useful. The point when, the `SIGUSR1` signal is received, `enclave_thread_map` does not have all the threads. `enclave_thread_map` fails to give us all the `follower_tids`(the experiment was done on MySql workload i could get only 2 thread_tid in `enclave_thread_map` out of the total 40 threads)

To avoid the race condition we can add spinlock on `DBGINFO_ADDR`
please let me know your opinion on this.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 338 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oG7Pn2RQ4apCaEEUJ:-O3qvaor8EjyhLZ3KXIv:b-lrrow6) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L338)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I actually tried to use `tgkill` (with smth like `tgkill(getpid(), follower_tid)`), but it didn't work... We can check again what happened there.
</blockquote></details>

I will try with tgkill.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oTAca4qSuXxHaZT3G:-O3qyd6H07nPh7mQ3bia:b-w2mtjd) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L363)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we will. I'm not sure how we want to handle this special case.

I see two options:
- Periodically re-check the current number of threads (read `g_enclave_thread_num` under lock) and compare with `followers_num`, if it's different, then abort the loop and print a warning. But this is not robust -- in the meantime one thread could have died and another one could have been spawned, so the total number of threads stays the same but one SIGUSR1 is lost, and the while loop is still inifinite.
- Introduce a time out of several seconds and abort the loop with a warning after timeout expires. I prefer this solution.
</blockquote></details>

yes, will add 2nd approach.
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 108 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oWmKm64bY_M4AeFas:-O3r2F-N2yCEMDWjoMfZ:b-kf4rae) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/pal_tcb.h#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually: ...or enclave exit for an OCALL
</blockquote></details>

sure. Can I reframe it as below
`dump SGX stats and reset them on enclave exit for an OCALL`


<!-- Sent from Reviewable.io -->

2024-08-11 21:09 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogorMDixQy0M-bykx:-O41wrBpB963NJPtBPSP:btl5krt) (no related file):*
> once in for all

What do you mean by that?

___
___
*[`pal/src/host/linux-sgx/host_entry.S` line 45 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogBNLDZxdP0S4-YWp:-O423nRh1iUNEg81rlp7:b-sipd78) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I do not understand the exact scenario here, let's first understand the specifics.

> What if a new thread is entering the enclave for the first time here and gets `SIGUSR1`?

Do you mean it's the **user-triggered** SIGUSR1, or the **leader-thread-triggered** SIGUSR1? From your following description, you seem to imply the leader-thread-triggered SIGUSR1, so I'll assume this.

> may exit via some blocking ocall, which won't be interrupted by `SIGUSR1`

Why would the thread be interrupted again by SIGUSR1? The thread already got SIGUSR1 and was interrupted, as you stated in your first sentence. So the thread got SIGUSR1 at that time and memorized this as `tcb->reset_stats = true`.

Now, on the very next AEX **or** OCALL, this thread will call `dump_and_reset_stats()` and will actually dump the statistics. Since you say `exit via some blocking ocall`, this is covered by newly added code under `.Lsgx_entry` -- the `dump_and_reset_stats()` function will be called before performing the OCALL.
</blockquote></details>

Ah, lol, I didn't expect "sgx_entry" to actually be "sgx exit" 😑 See the comment added there.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O4278RJ06urL0Ppy7nh:b-ldm0oe) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
> i.e., when GCC builds without optimizations), so the caller func saves it in its prologue

That's not guaranteed anywhere.

> Previously, we could skip this.

I don't see why would enabling optimization change anything in terms of correctness of this code. SYS-V ABI and how SGX works is the same regardless of GCC optimization level.

Also, what's in that rbp? Why do we need to save it?
___
*[`pal/src/host/linux-sgx/host_entry.S` line 136 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O420Ts32cZmNxGV6Mg1:-O420Ts32cZmNxGV6Mg2:b-u6ka8t) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L136)):*
> ```
>     jmp .Ldo_ecall_callee_save
> 
> .Lsgx_entry:
> ```

Unrelated to the PR, but why is this called "sgx_entry"? This is literally enclave _exit_ handler.



_Code quote:_
```
.Lsgx_entry:
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 52 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oV8Ar6oWL9kyoxiZY:-O42G55uEWm76rKBd2Pp:b-6xlicc) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (on enclave exit, right-before executing the OCALL)
</blockquote></details>

Yup, please fix the comment then :)
___
*[`pal/src/host/linux-sgx/host_exception.c` line 228 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ofTWqBbudnNkJcAiQ:-O42AcHp4YGDQ89frDQ0:b-o1uo6y) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We do this also in release mode because `sgx.enable_stats` always worked in release mode too. There's just nothing that requires it to be in debug mode (in contrast to e.g. profiling support, which requires debug symbols).

So this whole "let's allow this also in release mode" approach is purely for backwards-compatibility.
</blockquote></details>

I'd break it then, I'd prefer to not have this whole logic in production builds.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O42BJYO8AEqCIwPhSlp:b-599qpu) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks rather benign -- the SIGUSR1 event will then be just "lost" -- the current thread will exit without sending SIGUSR1 to other threads. So the SIGUSR1 event from the user will be just lost -- not amazing, but I guess we should live with this possibility.
</blockquote></details>

But then we're left with `g_stats_reset_leader_tid` permanently set to the TID of that dead thread, completely breaking this feature until the user restarts Gramine / this process?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGcMP3oBh8DTVyFA-:-O42BtT76ellQe1w5uuG:b-akraw) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

We had started with `enclave_thread_map` itself. But that approach was not useful. The point when, the `SIGUSR1` signal is received, `enclave_thread_map` does not have all the threads. `enclave_thread_map` fails to give us all the `follower_tids`(the experiment was done on MySql workload i could get only 2 thread_tid in `enclave_thread_map` out of the total 40 threads)

To avoid the race condition we can add spinlock on `DBGINFO_ADDR`
please let me know your opinion on this.
</blockquote></details>

@TejaswineeL: Please don't copy-paste long comments between discussions.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 345 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oIwAW09TX3xbwlIty:-O42FdpxBUlQidwLjMz2:bb73djm) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L345)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, can be modified to smth like `maybe_dump_and_reset_stats()`
</blockquote></details>

SGTM
___
*[`pal/src/host/linux-sgx/host_exception.c` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oTAca4qSuXxHaZT3G:-O42C4jP9wPdDKCRI_6_:b-q7rett) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L363)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

yes, will add 2nd approach.
</blockquote></details>

No, please don't fix deadlocks by timeouts... It's essentially like fixing race conditions by adding sleep() to a few places.

Please figure out a way of implementing this which works correctly.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 367 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oYJP94MdGLpK1dbP1:-O42FOq_8tGT0qXk-Sod:badenoc) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216b [...]

2024-08-12 07:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogorMDixQy0M-bykx:-O44HmPR4pcpajHCtCx2:bd7ckvp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> once in for all

What do you mean by that?
</blockquote></details>

I think this feature is quite useful, as knowing the approximate number of EENTER/EEXIT/AEX events is useful to pinpoint a potential bottleneck. And for many workloads, the noise of these events **at startup time** (when Gramine and SGX enclave are only starting and warming up) is significant, so it's quite informative to "flush" the startup-time events first, then start the actual workload (like start the clients against the Gramine app), and then dump the events/statistics again.

So to me, the feature is quite useful, and I've seen this PR (more like the code behind it) being useful for profiling some (proprietary) applications.

If @mkow insists, we could move this feature behind the DEBUG build of Gramine. Though please pay notice that this will *break backwards compatibility*, as SGX-stats feature is currently working also in RELEASE builds. **UPDATE:** Now I see that @mkow insists on this (see other comment), so let's move this SGX-stats feature under DEBUG builds (it is still fine because it will also work under DEBUGOPTIMIZED builds, so no issues with fidelity).

___
___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O44JH6P8VQKl4Z1zAkq:bq9b9w5) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
> That's not guaranteed anywhere.

Yes, looks like you're correct and it's just how these particular versions of GCC work. So yes, we can call it a bug in the code.

> Also, what's in that rbp? Why do we need to save it?

We're in the AEX event's "landing pad". According to Intel SDM, Chapter 37.3.1 "Processor Synthetic State on Asynchronous Enclave Exit", RBP is restored from `SSA.uRBP`. So it's important to save it, as `SSA.uRBP` may be restored on EEXIT and thus should *not* be modified in the AEX code.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 136 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O420Ts32cZmNxGV6Mg1:-O44Jykc3O2_nUjECVDR:b-cypawt) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unrelated to the PR, but why is this called "sgx_entry"? This is literally enclave _exit_ handler.
</blockquote></details>

Legacy historic name. I think it comes from that weird convention that `sgx_` stood for "anything to do with untrusted runtime", and `enclave_` stood for "anything to do with trusted enclave". So I would read `sgx_entry` as "entry to the untrusted runtime".

But now of course this name is totally bogus. Noone bothered to rename it yet.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 47 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oUXxw0GHsnvGaPZer:-O44KJJV7mifaYWvYbxl:b-w5c33p) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L47)):*
<details><summary><i>Previously, TejaswineeL (Tejaswinee) wrote…</i></summary><blockquote>

Can I reframe the statement as below 
` so that this thread's statistics are dumped and reset right-before executing the next OCALL in untrusted runtime .`
</blockquote></details>

Well, it's **both** on AEX and on OCALL, so the text should be:
```
 *           this thread's statistics are dumped and reset on the next AEX or right-before
 *           executing the next OCALL in untrusted runtime.
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 228 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ofTWqBbudnNkJcAiQ:-O44Ka-_6tHfPNyA88im:b-kv2q4a) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd break it then, I'd prefer to not have this whole logic in production builds.
</blockquote></details>

Ok, sure, we can do it. I also don't have any objections to allow this only in DEBUG builds. Let me put a blocking comment.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O44LJYUDbQG6qXEtN60:b1kt47h) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But then we're left with `g_stats_reset_leader_tid` permanently set to the TID of that dead thread, completely breaking this feature until the user restarts Gramine / this process?
</blockquote></details>

Good point. We can fix this by checking if `g_stats_reset_leader_tid == current_tid` right-before exiting the thread, and if true, then resetting this value to zero and printing a warning. Would that work for you?

UPDATE: There's a more generic thread-exiting approach described in my other comment, please check.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O44Lbea3Kg7vBeAYi2G:b-qyv0fg) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
> To avoid the race condition we can add spinlock on `DBGINFO_ADDR`   please let me know your opinion on this.

No, I think @mkow is right and should *not* use DBGINFO_ADDR variable at all.

> The point when, the `SIGUSR1` signal is received, `enclave_thread_map` does not have all the threads.

This is surprising. Please double-check why that happened -- does it happen even if you're under the `g_enclave_thread_map_lock` lock?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oTAca4qSuXxHaZT3G:-O44MMuY1MT8VsczFJU_:b-xydf9) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L363)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, please don't fix deadlocks by timeouts... It's essentially like fixing race conditions by adding sleep() to a few places.

Please figure out a way of implementing this which works correctly.
</blockquote></details>

Ok, the better approach would be:
- We introduce a new variable `g_stats_reset_epoch`, and increment it on a successful wait-for-followers by the leader (in this code snippet here).
- On any thread exit, we atomically increment `g_stats_reset_epoch` (and also reset `g_stats_reset_leader_tid` if it was the TID of this exiting thread).
- In this code snippet here, we check if the epoch is still the same as it was when we started the while loop. If it changed, then we know some change in the thread-number state happened, so we break the loop with a warning.

@mkow What about this?
___
*[`pal/src/host/linux-sgx/host_exception.c` line 367 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oYJP94MdGLpK1dbP1:-O44O3-vCFtWBpYyOjRr:b-gft7h3) ([raw fi [...]

2024-08-12 14:25 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O45wWd8-5Yjw6toGBMN:bbn6bup) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> That's not guaranteed anywhere.

Yes, looks like you're correct and it's just how these particular versions of GCC work. So yes, we can call it a bug in the code.

> Also, what's in that rbp? Why do we need to save it?

We're in the AEX event's "landing pad". According to Intel SDM, Chapter 37.3.1 "Processor Synthetic State on Asynchronous Enclave Exit", RBP is restored from `SSA.uRBP`. So it's important to save it, as `SSA.uRBP` may be restored on EEXIT and thus should *not* be modified in the AEX code.
</blockquote></details>

But we restore it manually after EEXIT?
https://github.com/gramineproject/gramine/blob/0c0971cd6930400b39b42eb92656b3968ae75698/pal/src/host/linux-sgx/host_entry.S#L56
___
*[`pal/src/host/linux-sgx/host_entry.S` line 136 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O420Ts32cZmNxGV6Mg1:-O45x0882esF0fO3orEU:b-nwl7e4) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Legacy historic name. I think it comes from that weird convention that `sgx_` stood for "anything to do with untrusted runtime", and `enclave_` stood for "anything to do with trusted enclave". So I would read `sgx_entry` as "entry to the untrusted runtime".

But now of course this name is totally bogus. Noone bothered to rename it yet.
</blockquote></details>

Could you fix this? In a separate PR, ideally.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O45xuVi2vEC2IjQQ-_T:b-rbw710) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
> We can fix this by checking if `g_stats_reset_leader_tid == current_tid` right-before exiting the thread

This would still be racy, what if the signal arrives after the check?


<!-- Sent from Reviewable.io -->

2024-08-12 17:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O46hrgC3N8W39nQaKBO:b-d9fzmo) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we restore it manually after EEXIT?
https://github.com/gramineproject/gramine/blob/0c0971cd6930400b39b42eb92656b3968ae75698/pal/src/host/linux-sgx/host_entry.S#L56
</blockquote></details>

Yep, looks like we don't use `SSA.uRBP` in the current flows. Do we want to have this assumption though, that other places in our code **don't use** this particular register?
___
*[`pal/src/host/linux-sgx/host_entry.S` line 136 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O420Ts32cZmNxGV6Mg1:-O46i5zA5N662HLeUVT3:b-w03kme) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you fix this? In a separate PR, ideally.
</blockquote></details>

Done, see #1969 
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O46iNn6EPRkMG6tjRr1:bauov0a) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
> This would still be racy, what if the signal arrives after the check?

Yes, we need to additionally protect against this. We already block SIGTERM/SIGCONT on thread exiting, so we can do a similar thing for SIGUSR1: https://github.com/gramineproject/gramine/blob/0c0971cd6930400b39b42eb92656b3968ae75698/pal/src/host/linux-sgx/host_thread.c#L285-L287

Therefore, we'll have this logic on `thread_exit()`:
1. Block SIGUSR1
2. Check `g_stats_reset_leader_tid == current_tid` and reset + print a warning if true
3. Finally exit thread


<!-- Sent from Reviewable.io -->

2024-08-19 14:48 UTC, dimakuv reviewed
> Reviewed 9 of 9 files at r14, 13 of 13 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1857)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @TejaswineeL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ogorMDixQy0M-bykx:-O4ermfT2L9GDH_dzqlY:b-8z670e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this feature is quite useful, as knowing the approximate number of EENTER/EEXIT/AEX events is useful to pinpoint a potential bottleneck. And for many workloads, the noise of these events **at startup time** (when Gramine and SGX enclave are only starting and warming up) is significant, so it's quite informative to "flush" the startup-time events first, then start the actual workload (like start the clients against the Gramine app), and then dump the events/statistics again.

So to me, the feature is quite useful, and I've seen this PR (more like the code behind it) being useful for profiling some (proprietary) applications.

If @mkow insists, we could move this feature behind the DEBUG build of Gramine. Though please pay notice that this will *break backwards compatibility*, as SGX-stats feature is currently working also in RELEASE builds. **UPDATE:** Now I see that @mkow insists on this (see other comment), so let's move this SGX-stats feature under DEBUG builds (it is still fine because it will also work under DEBUGOPTIMIZED builds, so no issues with fidelity).
</blockquote></details>

Done, new version is ready for review by @mkow 

___
___
*[`libos/test/regression/multi_pthread.manifest.template` line 16 at r15](https://reviewable.io/reviews/gramineproject/gramine/1857#-O4f3lnV-kZHkHf2Z5u5:-O4f3lnW4DP-O0ZqMF3O:baai36u) ([raw file](https://github.com/gramineproject/gramine/blob/ac61ae1777986e88629b764a1d6a8d6884ea869e/libos/test/regression/multi_pthread.manifest.template#L16)):*
> ```
> sgx.debug = true
> sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
> sgx.enable_stats = true
> ```

FYI: I removed `sgx.enable_stats = true` from 4 tests, since they are also run in release mode (where Gramine now prints an error and exits).

These `sgx.enable_stats = true` lines were anyway useless. I guess they were added to test this functionality manually using these tests. Now it's removed and instead added to one file which is only run in debug mode.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oczyyBMWLkp-ukmB6:-O4f45Lp4nCmMjoWf72L:b-ep4ge8) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, looks like we don't use `SSA.uRBP` in the current flows. Do we want to have this assumption though, that other places in our code **don't use** this particular register?
</blockquote></details>

Anyway, for this PR, I reverted all the changes, leaving only calls to the new function `maybe_dump_and_reset_stats()`.

For easy review, please review from the first revision.
___
*[`pal/src/host/linux-sgx/host_entry.S` line 136 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O420Ts32cZmNxGV6Mg1:-O4f4LBTC52zUI4aBJSU:b9vcta3) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_entry.S#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, see #1969
</blockquote></details>

#1969 was merged, I'll need to rebase.
___
*[`pal/src/host/linux-sgx/host_exception.c` line 47 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oUXxw0GHsnvGaPZer:-O4eTAe17NG1bg388oZb:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, it's **both** on AEX and on OCALL, so the text should be:
```
 *           this thread's statistics are dumped and reset on the next AEX or right-before
 *           executing the next OCALL in untrusted runtime.
```
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 52 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oV8Ar6oWL9kyoxiZY:-O4eTKKy-2Z4dONBPQTo:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, please fix the comment then :)
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 228 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3ofTWqBbudnNkJcAiQ:-O4eTkRTDDrGrKbN8RP1:b-omxa6n) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, sure, we can do it. I also don't have any objections to allow this only in DEBUG builds. Let me put a blocking comment.
</blockquote></details>

Done, everything is hidden behind `ifdef DEBUG`
___
*[`pal/src/host/linux-sgx/host_exception.c` line 231 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oSl6c9DhaKanHoAXj:-O4erTj08Sk3uQn15plp:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This would still be racy, what if the signal arrives after the check?

Yes, we need to additionally protect against this. We already block SIGTERM/SIGCONT on thread exiting, so we can do a similar thing for SIGUSR1: https://github.com/gramineproject/gramine/blob/0c0971cd6930400b39b42eb92656b3968ae75698/pal/src/host/linux-sgx/host_thread.c#L285-L287

Therefore, we'll have this logic on `thread_exit()`:
1. Block SIGUSR1
2. Check `g_stats_reset_leader_tid == current_tid` and reset + print a warning if true
3. Finally exit thread
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 333 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3o_twz8j65ISlNSrNH:-O4eTzgc43KUBMTDK54Q:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L333)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, I think this is better. We can do this.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/host_exception.c` line 334 at r13](https://reviewable.io/reviews/gramineproject/gramine/1857#-O3oGC0X0CWPGwWqGiJd:-O4eTsr_E7ewe_ZTvjI6:b-ighlcf) ([raw file](https://github.com/gramineproject/gramine/blob/f09d9ec9253c829216bed01a23cdbbe970a7c1a6/pal/src/host/linux-sgx/host_exception.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> To avoid the race condition we can add spinlock on `DBGINFO_ADDR`   please let me know your opinion on this.

No, I think @mkow is right and should *not* use DBGINFO_ADDR variable at all.

> The point when, the `SIGUSR1` signal is received, `enclave_thread_map` does not have all the threads.

This is surprising. Please double-check why that happened -- does it h [...]

2024-08-19 17:01 UTC, dimakuv commented
Jenkins, test this please

2024-09-26 07:08 UTC, closed without merging