[tests] Fix signature length calculation in sgx_sign tests
gramineproject/gramine pull request #1864
Opened 2024-04-30 22:56 UTC by mkow

## Description of the changes 

Incorrect signature length calculation could cause an `InvalidSignature` exception if the signature happened to start with a 0x00 byte, resulting in random CI failures.

Fixes #1689.

## How to test this PR? 

Run `while true; python3 -m pytest -v -k 'test_sign_from_pem_path' tests/; or break; end` in Gramine root and wait. Without this PR it fails after ~64 loop iterations with:
```
tests/test_sgx_sign.py:64: in test_sign_from_pem_path
    verify_signature(data, exponent, modulus, signature, key_file)
tests/test_sgx_sign.py:50: in verify_signature
    public_key.verify(signature_bytes, data, padding.PKCS1v15(), hashes.SHA256())
/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/rsa.py:550: in verify
    _rsa_sig_verify(
/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/rsa.py:325: in _rsa_sig_verify
    raise InvalidSignature
E   cryptography.exceptions.InvalidSignature
```

2024-05-01 01:28 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1864)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-05-02 07:54 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1864)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1864#-NwsI-W_4S9umwCi8-Xx):*
What's the problem of a signature starting with a zero byte?
___
*[`tests/test_sgx_sign.py` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1864#-NwsHsg_CkJLwKxa0YjZ:-NwsHsg_CkJLwKxa0Yj_:b-1ov620) ([raw file](https://github.com/gramineproject/gramine/blob/dcf60c5fdebc3af65746f349736dd8240bab822c/tests/test_sgx_sign.py#L47)):*
> ```Python
>     assert numbers.e == exponent
>     assert numbers.n == modulus
>     signature_bytes = signature.to_bytes((modulus.bit_length() + 7) // 8, byteorder='big')
> ```

I don't understand this change. Could you explain a bit? Why `signature` length is wrong here?


<!-- Sent from Reviewable.io -->

2024-05-02 11:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1864)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1864#-NwsI-W_4S9umwCi8-Xx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the problem of a signature starting with a zero byte?
</blockquote></details>

See below.
___
*[`tests/test_sgx_sign.py` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1864#-NwsHsg_CkJLwKxa0YjZ:-Nwsxs5x1N-juUgPHOUE:bjt5k5r) ([raw file](https://github.com/gramineproject/gramine/blob/dcf60c5fdebc3af65746f349736dd8240bab822c/tests/test_sgx_sign.py#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this change. Could you explain a bit? Why `signature` length is wrong here?
</blockquote></details>

`public_key.verify()` expects a specific byte sequence as a correct signature, not a number (and that's also what the original signing function returns, but our wrapper converts it to a number, because that's needed for SGX stuff: https://github.com/gramineproject/gramine/blob/master/python/graminelibos/sgx_sign.py#L666). Here we're trying to convert it back, but incorrectly.

The problem here is that this "serialization" here produces different lengths depending on the signature. If it happens to start with 0x00, then the resulting `bytes` array is shorter than expected and the verification fails. Example: with the SGX signing parameters the key signature should always have 384 bytes (3072/8), regardless of it's specific value.


<!-- Sent from Reviewable.io -->

2024-05-02 11:16 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-02 13:44 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-02 23:42 UTC, merged