[glibc] Fix redefinition of `_FORTIFY_SOURCE`
gramineproject/gramine pull request #1865
Opened 2024-05-01 09:39 UTC by oshogbo

## Description of the changes 

The new Ubuntu release, Noble, includes a version of GCC with a spec that defines `_FORTIFY_SOURCE` when optimization is enabled:
```
$ gcc -dumpspecs | grep _FORTIFY_SOURCE
 %{!O0:%{O*:%{!D_FORTIFY_SOURCE=*:%{!U_FORTIFY_SOURCE:-D_FORTIFY_SOURCE=3}}}
```

However, some files in glibc need to be built without `_FORTIFY_SOURCE`, such as `vprintf.c`. The patch from Ubuntu Noble changes the method of undefining _FORTIFY_SOURCE to -U_FORTIFY_SOURCE. Previously it was limited only to the preprocessor (-Wp,-U_FORTIFY_SOURCE). The new method also undefines the definition from the spec.
The patch addresses some other non-standard redefinitions of _FORTIFY_SOURCE as well.

## Some useful things

### Get logs from the ubuntu/debian build (depends on the machine)
```
getbuildlog glibc last amd64
```

### Patch obtained from
- http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/glibc_2.39-0ubuntu8.1.debian.tar.xz

### Ubuntu change log
https://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.39-0ubuntu8.1/changelog

```
glibc (2.39-0ubuntu7) noble; urgency=medium

[...]
  * d/p/fix-fortify-source.patch: Fix FTBFS on Noble
[...]
 -- Simon Chopin <schopin@ubuntu.com>  Thu, 28 Mar 2024 15:16:51 +0100
```

## How to test this PR? 

Test suite.

2024-05-02 08:03 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1865)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1865#-NwsK2ANBouz8-HyqtBm:-NwsK2AO5eeElfan2Dew:b2nnuz5) (no related file):*
Please also mention this patch in this list: https://github.com/gramineproject/gramine/blob/8b91c2fcdbf1dd8d8895685f5cd047864b3489b1/subprojects/packagefiles/glibc-2.39/meson.build#L74

___
___
*[`subprojects/packagefiles/glibc-2.39/fix-fortify-source.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1865#-NwsJZ9m1eaRVW8dxPIh:-NwsJZ9m1eaRVW8dxPIi:b5ln3y2) ([raw file](https://github.com/gramineproject/gramine/blob/ba626c3cde37df939f0292d985fdb43dbab717f7/subprojects/packagefiles/glibc-2.39/fix-fortify-source.patch#L1)):*
> ```Diff
> From 73302ea9454b816d5e0a4f02bbd68df1bf2bb53d Mon Sep 17 00:00:00 2001
> ```

I verified this patch to be an exact copy of the one in the Ubuntu Noble patches (bar the differently laid out spaces).


<!-- Sent from Reviewable.io -->

2024-05-02 09:23 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1865)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1865#-NwsK2ANBouz8-HyqtBm:-NwsbKI3EiG3efNGdXWS:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also mention this patch in this list: https://github.com/gramineproject/gramine/blob/8b91c2fcdbf1dd8d8895685f5cd047864b3489b1/subprojects/packagefiles/glibc-2.39/meson.build#L74
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-05-02 10:45 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1865)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-05-03 13:03 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1865)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-03 13:04 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1865)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-03 15:43 UTC, merged