[common] Refactor Protected Files, part 4
gramineproject/gramine pull request #1869
Opened 2024-05-02 07:41 UTC by dimakuv

## Description of the changes 

This commit refactors PF code without changing functionality (part 4 in a series of commits). In particular, this commit re-orders variables, struct definitions, struct fields, typedefs, and macros for readability.

Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.

Note that this PR is based on https://github.com/gramineproject/gramine/pull/1866.

## How to test this PR? 

N/A.

2024-05-18 00:06 UTC, mkow requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.h` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7urK_6T31o1m9GkdO:-Ny7urK_6T31o1m9GkdP:b-u8usl7) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files.h#L26)):*
> ```objc
> #define PF_MAC_SIZE 16
> 
> /*! Size of the salt used in KDF (Key Derivation Function) */
> ```

But this isn't salt, it's key ID? If something, this could be a nonce, but some parts of PF code call it "key ID" instead of nonce?
___
*[`common/src/protected_files/protected_files_format.h` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7z2s73EHCI68qivxC:-Ny7z2s73EHCI68qivxD:b-7vo5ur) ([raw file](https://github.com/gramineproject/gramine/blob/112ecd22a331fa4f075174766472b826db8d3cba/common/src/protected_files/protected_files_format.h#L41)):*
> ```objc
> 
> // these are all defined as relative to node size, so we can decrease node size in tests
> // and have deeper tree
> ```

This comment sounded useful IMO.
___
*[`common/src/protected_files/protected_files_format.h` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny8-bizCtJoAwOeXRwa:-Ny8-bizCtJoAwOeXRwb:byzr2nq) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L110)):*
> ```objc
> 
>     encrypted_node_t encrypted; // encrypted data from storage (bounce buffer)
>     union {                     // decrypted data in private memory (plain buffer)
> ```

the structure itself has no control where it's located



_Code quote:_
```objc
in private memory (plain buffer)
```
___
*[`common/src/protected_files/protected_files_internal.h` line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7xSxwAIA1FOhlRAhH:-Ny7xSxwAIA1FOhlRAhI:bz4mpt4) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L25)):*
> ```objc
>     pf_key_t user_kdk_key; // KDK installed by user of PF (e.g. from Gramine manifest)
> 
>     metadata_node_t file_metadata; // plaintext and encrypted metadata from storage (bound buffer)
> ```

What does "bound buffer" mean?
___
*[`common/src/protected_files/protected_files_internal.h` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7xxep8AAzZIl8_3ha:-Ny7xxep8AAzZIl8_3hb:b-ivwbgo) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L28)):*
> root MHT node is always needed (for files bigger than 3KB)

So, not always? This comment is confusing.


<!-- Sent from Reviewable.io -->

2024-05-19 14:54 UTC, kailun-qin requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`common/src/protected_files/protected_files.h` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7urK_6T31o1m9GkdO:-NyGBvdq76DaUyjjL_By:b-mpen4z) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files.h#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this isn't salt, it's key ID? If something, this could be a nonce, but some parts of PF code call it "key ID" instead of nonce?
</blockquote></details>

+1, as the key derivation follows [NIST SP 800-108](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1.pdf) (as stated in the comment of `kdf_input_t`), the unique randomized key ID aligns more closely with the nonce in the`Context` field
___
*[`common/src/protected_files/protected_files_format.h` line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGKwOhB80FvPLu3R4r:-NyGKwOhB80FvPLu3R4s:b-s1v0l6) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L34)):*
> ```objc
> static_assert(MD_USER_DATA_SIZE == 3072, "bad struct size");
> 
> #define MAX_PAGES_IN_CACHE 48
> ```

what about just `MAX_NODES_IN_CACHE`?



_Code quote:_
```objc
#define MAX_PAGES_IN_CACHE 48
```
___
*[`common/src/protected_files/protected_files_format.h` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGIHK_8Ii3s_ZZbGuy:-NyGIHK_8Ii3s_ZZbGuz:b-ishlf7) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L116)):*
> ```objc
> } file_node_t;
> 
> // input materials for the KDF construction of NIST-SP800-108
> ```

since we mention NIST standard here, can we align all comments of fields w/ its terminologies? e.g., index -- conter



_Code quote:_
```objc
NIST-SP800-108
```
___
*[`common/src/protected_files/protected_files_format.h` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGGcad7mkEYTc2BVcl:-NyGGcad7mkEYTc2BVcm:be4qybn) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L120)):*
> ```objc
>     uint32_t index;             // always "1"
>     char label[MAX_LABEL_SIZE]; // must be NULL terminated
>     pf_keyid_t nonce;           // salt for key derivation from KDK, stored in metadata node
> ```

similar above



_Code quote:_
```objc
salt
```
___
*[`common/src/protected_files/protected_files_internal.h` line 30 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGKkxG6bfd2Yew7TnC:-NyGKkxG6bfd2Yew7TnD:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L30)):*
> ```objc
>     file_node_t root_mht; // root MHT node is always needed (for files bigger than 3KB)
> 
>     lruc_context_t* cache; // up to MAX_PAGES_IN_CACHE nodes are cached for each file
> ```

ditto



_Code quote:_
```objc
MAX_PAGES_IN_CACHE
```


<!-- Sent from Reviewable.io -->

2024-05-19 17:51 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @kailun-qin)

___
*[`common/src/protected_files/protected_files_format.h` line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGKwOhB80FvPLu3R4r:-NyGyJfxCTsoJjuufhm1:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L34)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

what about just `MAX_NODES_IN_CACHE`?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-06-03 13:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: 0 of 5 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`common/src/protected_files/protected_files.h` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7urK_6T31o1m9GkdO:-NzTFdkV6qV92SSgfVNB:buj2ntm) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files.h#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

+1, as the key derivation follows [NIST SP 800-108](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1.pdf) (as stated in the comment of `kdf_input_t`), the unique randomized key ID aligns more closely with the nonce in the`Context` field
</blockquote></details>

Done, using "nonce" now.

"Key ID" is a wrong/unused word in the Protected Files codebase. At least I don't know what it's supposed to mean.

@kailun-qin is right, my term "salt" is also incorrect. The NIST SP 800-108 standard uses the term "nonce", so let's call everything the nonce.

@mkow Please notice that a follow up PR (not yet extracted from #1841, because I'm waiting for this PR to be finalized and merged, otherwise there will be too complex rebases) will fix the rest of the comments in the Protected Files codebase.
___
*[`common/src/protected_files/protected_files_format.h` line 34 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGKwOhB80FvPLu3R4r:-NzTHfcT2H9sAiCphKGL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files_format.h` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7z2s73EHCI68qivxC:-NzTGo9H9AUtNX8U2z0F:b-km0z7g) ([raw file](https://github.com/gramineproject/gramine/blob/112ecd22a331fa4f075174766472b826db8d3cba/common/src/protected_files/protected_files_format.h#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This comment sounded useful IMO.
</blockquote></details>

But we never changed the sizes, and we don't plan to change the sizes. I don't see a point in this comment. I think our 4KB node size is now fixed in stone (especially after we modified our Slab allocator to be compatible with 4KB-nodes).
___
*[`common/src/protected_files/protected_files_format.h` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny8-bizCtJoAwOeXRwa:-NzTHKMh1lDTGM-TsG-m:b-ltrs5f) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

the structure itself has no control where it's located
</blockquote></details>

Done, rephrased
___
*[`common/src/protected_files/protected_files_format.h` line 116 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGIHK_8Ii3s_ZZbGuy:-NzTH5_U79cuFf6oPHYP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L116)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

since we mention NIST standard here, can we align all comments of fields w/ its terminologies? e.g., index -- conter
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files_format.h` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGGcad7mkEYTc2BVcl:-NzTHBDU-DFomL1ikrUz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_format.h#L120)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

similar above
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files_internal.h` line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7xSxwAIA1FOhlRAhH:-NzTHUMRCjq1XrvM_tTh:b-qpzv3j) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does "bound buffer" mean?
</blockquote></details>

Done. Typo.
___
*[`common/src/protected_files/protected_files_internal.h` line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7xxep8AAzZIl8_3ha:-NzTHXyE0_Ld5Zsk_0bc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> root MHT node is always needed (for files bigger than 3KB)

So, not always? This comment is confusing.
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files_internal.h` line 30 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-NyGKkxG6bfd2Yew7TnC:-NzTHgsW5L-hnL5oI3uJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-03 22:37 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`common/src/protected_files/protected_files_internal.h` line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/1869#-Ny7xSxwAIA1FOhlRAhH:-NzVElSmADAObq2h-7B7:b-mz5y7v) ([raw file](https://github.com/gramineproject/gramine/blob/68d66ef1cf9458059f53f5eb2f1face7338336d1/common/src/protected_files/protected_files_internal.h#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Typo.
</blockquote></details>

Ah, lol.


<!-- Sent from Reviewable.io -->

2024-06-04 01:34 UTC, kailun-qin approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-06-04 05:42 UTC, dimakuv commented
Jenkins, test this please

2024-06-04 17:15 UTC, dimakuv commented
Jenkins, test this please

2024-06-04 20:45 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-05 00:43 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-05 17:30 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-06 00:57 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-06 07:27 UTC, merged