Fix dentry of open file handles related to a rename
gramineproject/gramine pull request #1874
Opened 2024-05-07 03:39 UTC by g2flyer

During `rename`, the `dentry` of the corresponding handle is not updated, which e.g., makes `fchown` not work properly.   I did discover that during work on issue #1835 in Draft PR #1856 where i have to be able to figure out stale handles.   A corresponding test-case is added as `test_rename_fchown_fchmod` in `rename_unlink`.  An additional rename related test case `test_rename_follow` test the "flip-side" of `test_rename_replace` (the one which originally triggered me finding the bug).

## Description of the changes 

To fix that, `do_rename` iterates over open file handles and fixes any which was was pointing to the source-dentry of the rename.

PS: I'm not very "fluent" on the overall locking strategy. I didn't find anything obvious where my code violates invarients but definitely good to cross-check that  (a) using sufficents locks and (b) the implied lock prioties  `g_dcache.lock` >  `libos_handle_map.lock` > `libos_handle.lock` does not violate anything. 

## How to test this PR? 

I tested by adding the two new test-cases and then running the usual regression tests.

2024-05-07 08:32 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH8sGw98tSywAOgcVy):*
You should add the prefix `[LibOS]`.
___
*[`libos/src/sys/libos_file.c` line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9Aoz-vgiBJePMNj1:-NxH9Aoz-vgiBJePMNj2:b-mvpc2a) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L361)):*
> ```C
>     new_dent->inode = old_dent->inode;
>     old_dent->inode = NULL;
>     // also update dentry of any potentially open fd pointing to old_dent
> ```

I would suggest adding a new line before the comment.
___
*[`libos/src/sys/libos_file.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9_LhA4Xj5P-qjsir:-NxH9_LhA4Xj5P-qjsis:b-su4ibt) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L362)):*
> ```C
>     old_dent->inode = NULL;
>     // also update dentry of any potentially open fd pointing to old_dent
>     struct libos_handle_map* handle_map = get_thread_handle_map(NULL);
> ```

When we acquire the handle_map we actually assert most of the time that the handle_map was returned. Do we want to add assert here as well?
___
*[`libos/test/regression/rename_unlink.c` line 185 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHABV5AmYxDbmPXHXZ:-NxHABV6-LfMPnUuzjX0:b-wusy8j) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L185)):*
> ```C
> 
>     int fd = create_file(path1, message1, message1_len);
> ```

No need for extra space here.
___
*[`libos/test/regression/rename_unlink.c` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHAPvL6cyeTHs9Onh-:-NxHAPvM1JbUpAfz_GK0:b-w5ccs6) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L224)):*
> ```C
> 
> // NOTE: below will _not_ run correctly when directly executed unless you run as root.
> // But it should run properly in gramine when executed as normal user.
> ```

Gramine.



_Code quote:_
```C
gramine
```
___
*[`libos/test/regression/rename_unlink.c` line 228 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHAVwt5JAUIngYh9nO:-NxHAVwt5JAUIngYh9nP:b-pmp40j) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L228)):*
> ```C
>     printf("%s...\n", __func__);
> 
>     int fd = create_file(path1, message1, message1_len);
> ```

We don't need to check `fd`?
___
*[`libos/test/regression/rename_unlink.c` line 233 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHAatX0omvai5TNH8L:-NxHAatX0omvai5TNH8M:b-leo561) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L233)):*
> ```C
>         err(1, "fchown before rename");
>     if (fchmod(fd, S_IRWXU | S_IRWXG) != 0)  // Note: no other!
>         err(1, "fchmod before rename");
> ```

I would suggest new line.


<!-- Sent from Reviewable.io -->

2024-05-07 10:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOjy_BTeS5Nem7tSP:-NxHOjy_BTeS5Nem7tSQ:bctuau8) (no related file):*
For other reviewers: `fchown()` fails with ENOENT because it operates through the dentry of the handle, and if it doesn't find the inode associated with the dentry, it returns with ENOENT.

And since during `rename()`, the inode of the old dentry is NULLified (see the surrounding code in this PR), we end up in this error path: https://github.com/gramineproject/gramine/blob/80377ca17561ab0ce7bcfd59569dd49a567fddb0/libos/src/sys/libos_file.c#L297

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHPdRr5Jidko1dtQ6e:-NxHPdRr5Jidko1dtQ6f:b-qniteo) (no related file):*
While I consider this PR generally correct (we must indeed rewire the dentry of the handle), I think the problem with `fchmod()` lies elsewhere.

In particular, `fchmod()` operates on an FD, i.e. on the LibOS handle, and it's not supposed to be associated with the dentry. I created a PR that fixes this: https://github.com/gramineproject/gramine/pull/1875

Moreover, as explained in the comments, the `hdl->dentry` field is a historic artifact which should be actually completely removed, in favor of `hdl->inode`. That's also how the Linux kernel works (and how any sane kernel should work). So in general, if our Gramine codebase is ready to get rid of `hdl->dentry`, I would very gladly do **that** instead, and this PR won't be necessary.

___
___
*[`libos/src/sys/libos_file.c` line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHWoO3ARLjTiwYXJ43:-NxHWoO4DpXDcNdeKhK-:b-55ml60) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L361)):*
> ```C
>     new_dent->inode = old_dent->inode;
>     old_dent->inode = NULL;
>     // also update dentry of any potentially open fd pointing to old_dent
> ```

Please use `/*` comments style.
___
*[`libos/src/sys/libos_file.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9_LhA4Xj5P-qjsir:-NxHWrld6CbqjJVcC5RX:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L362)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

When we acquire the handle_map we actually assert most of the time that the handle_map was returned. Do we want to add assert here as well?
</blockquote></details>

+1
___
*[`libos/src/sys/libos_file.c` line 363 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHWt6xEWEFK8czkRj8:-NxHWt6xEWEFK8czkRj9:bk26y6) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L363)):*
> ```C
>     // also update dentry of any potentially open fd pointing to old_dent
>     struct libos_handle_map* handle_map = get_thread_handle_map(NULL);
>     rwlock_write_lock(&handle_map->lock);
> ```

Why write lock? Looks like we can do a read lock here.
___
*[`libos/src/sys/libos_file.c` line 370 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHX2TU6MLuocNiRxn4:-NxHX2TU6MLuocNiRxn5:b-ofbr9l) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L370)):*
> ```C
>             continue;
>         struct libos_handle* handle = fd_handle->handle;
>         if ((handle->dentry != old_dent) || (handle->inode != new_dent->inode))
> ```

`handle->dentry` must be under the `handle->lock`. Otherwise two parallel renames will have a data race: T1 will be preempted right after this check, T2 will update `handle->dentry` to a new dentry, and then T1 is scheduled back and updates again. So we loose one update.

But generally, I have a feeling that our codebase was written under the implicit assumption that `handle->dentry` is immutable. So there can be more places that don't grab a lock but simply read `handle->dentry` field, and these also must be modified -- since this PR introduces a new property that the dentry field is mutable.
___
*[`libos/test/regression/rename_unlink.c` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOLY7E3d3Y9Z2JUwj:-NxHOLY7E3d3Y9Z2JUwk:b-h2y0ob) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L3)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2021 Intel Corporation
>  *                    Paweł Marczewski <pawel@invisiblethingslab.com>
> ```

If you want to, add your name to this copyright (and update the year to 2024)
___
*[`libos/test/regression/rename_unlink.c` line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOHdd-XUOgz1HMo-G:-NxHOHdd-XUOgz1HMo-H:bsmnmn0) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L159)):*
> ```C
> 
>     should_not_exist(path1);
> ```

Looks like a random change. Please revert.
___
*[`libos/test/regression/rename_unlink.c` line 181 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHM3ZT5DI1pt_jjPXI:-NxHM3ZT5DI1pt_jjPXJ:b4zt58r) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L181)):*
> ```C
> }
> 
> static void test_rename_follow(const char* path1, const char* path2) {
> ```

Why `_follow`? Wouldn't it be better to name it `_write` or `_overwrite`?
___
*[`libos/test/regression/rename_unlink.c` line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHMLNb4wOoDhxup9uu:-NxHMLNb4wOoDhxup9uv:blqnkq2) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L224)):*
> ```C
> 
> // NOTE: below will _not_ run correctly when directly executed unless you run as root.
> // But it should run properly in gramine when executed as normal user.
> ```

Can you replace `//` comments with `/*` comments?

We mainly use `/*` comment style, but in some files you may see the old convention... But new files should be written with `/*`, and new code in files that previously used `/*` should also continue using this style.
___
*[`libos/test/regression/rename_unlink.c` line 228 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHAVwt5JAUIngYh9nO:-NxHMetf-WovxJ-qrXxB:b-smxqzz) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L228)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We don't need to check `fd`?
</blockquote></details>

+1, please check the creation of the file
___
*[`libos/test/regression/rename_unlink.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHMzOQ36mQFEOfgZ4a:-NxHMzOQ36mQFEOfgZ4b:b-jddyri) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L230)):*
> ```C
>     int fd = create_file(path1, message1, message1_len);
> 
>     if (fchown(fd, 1, 1))
> ```

You should compare it with `!= 0`, for uniformity with the rest of the code
___
*[`libos/test/regression/rename_unlink.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHN3TI2tcNnetn-Nwq:-NxHN3TJCpBgUhdyoXkq:b-yyk5ge) ([raw file](https://github.com/gramineproject/gramine/blob/ [...]

2024-05-07 12:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHPdRr5Jidko1dtQ6e:-NxI42cX7Mik4m5E-c3z:bt458ad) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

While I consider this PR generally correct (we must indeed rewire the dentry of the handle), I think the problem with `fchmod()` lies elsewhere.

In particular, `fchmod()` operates on an FD, i.e. on the LibOS handle, and it's not supposed to be associated with the dentry. I created a PR that fixes this: https://github.com/gramineproject/gramine/pull/1875

Moreover, as explained in the comments, the `hdl->dentry` field is a historic artifact which should be actually completely removed, in favor of `hdl->inode`. That's also how the Linux kernel works (and how any sane kernel should work). So in general, if our Gramine codebase is ready to get rid of `hdl->dentry`, I would very gladly do **that** instead, and this PR won't be necessary.
</blockquote></details>

@g2flyer Can you check whether #1875 fixes your issues? Then we could extract your two sub-tests in a separate PR, and then think what to do with your change of "update dentry of handle" separately -- since this is very non-trivial (as should be clear from my comments).

___


<!-- Sent from Reviewable.io -->

2024-05-07 19:08 UTC, g2flyer reviewed
Thanks for all the good comments; hope next time i sleep over pushing a PR to already fix a number of things a night and a clear head in the morning would have fixed

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874#-:-NxJRt3lC3e8RmBfdyhv:b-l3t4qn)* status: 0 of 2 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHPdRr5Jidko1dtQ6e:-NxIbFc-5xjoyr6zEZ5p:b-6sx2yp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@g2flyer Can you check whether #1875 fixes your issues? Then we could extract your two sub-tests in a separate PR, and then think what to do with your change of "update dentry of handle" separately -- since this is very non-trivial (as should be clear from my comments).
</blockquote></details>

@dimakuv Oh, i didn't see any issue with `fchmod`.  I just added that test case also for `fchmod` as it seemed somewhat conceptually related to `fchown` in that it changes metadata of a renamed file with an open handle. More importantly, to (a) test first whether it really works or not  in old code-- which from looking at code i thought and indeed it worked -- and (b) to make sure that my changes didn't screw up anything related to it.

In any case, i did successfully run and tested #1875 as-is and then merged my new test-vectors with your version and that also did pass all tests.  So your change certainly solves the `fchown` rename issue more minimally (although for my (PR #1856 / issue #1835) case i probably still will have to do the dentry fixup (but as you say needs much more thorough update regarding locking).  Regarding pulling my new tests in a separate PR, assuming your PR #1875 is merged first, wouldn't it be better to move them (after cleanup) to that PR?  Would seem to me best to keep the vectors identifying the problem together with the (immediate) fix?

___
___
*[`libos/src/sys/libos_file.c` line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9Aoz-vgiBJePMNj1:-NxJJBJD0_hJEbVWU5He:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L361)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I would suggest adding a new line before the comment.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHWoO3ARLjTiwYXJ43:-NxJJBsCB1lNLRrP1CCI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L361)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `/*` comments style.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9_LhA4Xj5P-qjsir:-NxJJSZT7iXStJMY5Hcv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L362)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 363 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHWt6xEWEFK8czkRj8:-NxJJV1iAawvAA0UknzR:b-dhvc80) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L363)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why write lock? Looks like we can do a read lock here.
</blockquote></details>

copy/paste from walk_.. but using weaker lock definitely better
___
*[`libos/src/sys/libos_file.c` line 370 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHX2TU6MLuocNiRxn4:-NxJJj0w3xzB0pQrudFL:bi0d9ac) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`handle->dentry` must be under the `handle->lock`. Otherwise two parallel renames will have a data race: T1 will be preempted right after this check, T2 will update `handle->dentry` to a new dentry, and then T1 is scheduled back and updates again. So we loose one update.

But generally, I have a feeling that our codebase was written under the implicit assumption that `handle->dentry` is immutable. So there can be more places that don't grab a lock but simply read `handle->dentry` field, and these also must be modified -- since this PR introduces a new property that the dentry field is mutable.
</blockquote></details>

Yep, i realized that also during the night that (a) the scope of lock here would have to cover also the checks and (b) i would have to find other cases of use of handle->dentry and potentially add locks there as well.   I guess would have been a good idea to sleep over it first instead of eagerly pushing a PR in the evening ;-)

For now i just due (a), add a TODO for myself for (b) and will downgrade the PR to a draft PR ...
___
*[`libos/test/regression/rename_unlink.c` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOLY7E3d3Y9Z2JUwj:-NxJLM8wDc9oATz9Wqa1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If you want to, add your name to this copyright (and update the year to 2024)
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOHdd-XUOgz1HMo-G:-NxJLb4eEqSFu1_24jMn:bgw07p0) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like a random change. Please revert.
</blockquote></details>

Aargh, relied too much on color highlights in `git diff` and overlooked this single '+'.  I guess note to self to more carefully look through git diffs. Anyway should be fixed
___
*[`libos/test/regression/rename_unlink.c` line 181 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHM3ZT5DI1pt_jjPXI:-NxJMRK5DmtMi6fdLInV:biw0d01) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L181)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `_follow`? Wouldn't it be better to name it `_write` or `_overwrite`?
</blockquote></details>

The thought that instead of on open (destination) fd being replaced by the rename (as the earlier test, here an open (source) fd "follows" the rename.   Follow is certainly not the most intuitive name but i have to admit the generic (over)write seems even less so to me.  So far now leave it as-is to hear other opinions/suggestions.
___
*[`libos/test/regression/rename_unlink.c` line 185 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHABV5AmYxDbmPXHXZ:-NxJNt5qAovejDxQMtL2:blv8ngj) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L185)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No need for extra space here.
</blockquote></details>

i kept the format from `test_rename_replace [...]

2024-05-08 06:43 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHPdRr5Jidko1dtQ6e:-NxLuSo70GnXz3yTu91-:b-5ykg9q) (no related file):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

@dimakuv Oh, i didn't see any issue with `fchmod`.  I just added that test case also for `fchmod` as it seemed somewhat conceptually related to `fchown` in that it changes metadata of a renamed file with an open handle. More importantly, to (a) test first whether it really works or not  in old code-- which from looking at code i thought and indeed it worked -- and (b) to make sure that my changes didn't screw up anything related to it.

In any case, i did successfully run and tested #1875 as-is and then merged my new test-vectors with your version and that also did pass all tests.  So your change certainly solves the `fchown` rename issue more minimally (although for my (PR #1856 / issue #1835) case i probably still will have to do the dentry fixup (but as you say needs much more thorough update regarding locking).  Regarding pulling my new tests in a separate PR, assuming your PR #1875 is merged first, wouldn't it be better to move them (after cleanup) to that PR?  Would seem to me best to keep the vectors identifying the problem together with the (immediate) fix?
</blockquote></details>

1. It was a typo when I mentioned `fchmod()` in my previous comment. I meant `fchown()`.
2. I agree that I can move your sub-tests from this PR into #1835. I will do it now.
   - After that, those tests in your PR can be reverted, keeping only the logic of `hdl->dentry` updates.

___
___
*[`libos/src/sys/libos_file.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9_LhA4Xj5P-qjsir:-NxLuueg9AMby0cJP-pa:b-55oazs) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L362)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The assert is now on the `handle_libos_call` which seems unrelated?
___
*[`libos/src/sys/libos_file.c` line 370 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHX2TU6MLuocNiRxn4:-NxLvCPP9VmZq6_bF4dY:bha11n3) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L370)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

Yep, i realized that also during the night that (a) the scope of lock here would have to cover also the checks and (b) i would have to find other cases of use of handle->dentry and potentially add locks there as well.   I guess would have been a good idea to sleep over it first instead of eagerly pushing a PR in the evening ;-)

For now i just due (a), add a TODO for myself for (b) and will downgrade the PR to a draft PR ...
</blockquote></details>

I'll keep this as blocking comment then.
___
*[`libos/test/regression/rename_unlink.c` line 185 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHABV5AmYxDbmPXHXZ:-NxLvZWmBXyFspo1KF3-:b-pwy90v) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L185)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

i kept the format from `test_rename_replace` but i agree removing the space seems more intuitive.  Fixed now.
Should i also remove the space in `test_rename_replace? (That said, i guess once you start making stuff consistent one would also have to add the test to `test_ranme_same_file` and alike which seems probably beyond what should be done in this PR).
</blockquote></details>

I don't have a strong opinion, but our general practice for tests is:
1. Try to use the same style as in the core Gramine codebase
2. But if the test is already written in another style, conform to that style
3. Or first submit a PR that refactors the test to a better style, and only then modify the test
4. But generally -- these are just tests, we don't care that much. If you would say "No, there is an empty line in other already existing sub-tests, so I'll do that as well", no one would object.


<!-- Sent from Reviewable.io -->

2024-05-08 07:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @oshogbo)

___
*[`libos/test/regression/rename_unlink.c` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxM-YIdBhoYD5AXgutx:-NxM-YIdBhoYD5AXguty:b-swl541) ([raw file](https://github.com/gramineproject/gramine/blob/e36a532774bef0ebf4bc2e0b2b9cfc9ddf1eac7c/libos/test/regression/rename_unlink.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2024 Intel Corporation
> ```

These changes were copied to #1875


<!-- Sent from Reviewable.io -->

2024-05-08 17:55 UTC, g2flyer reviewed
fixed the embarrassing copy/paste bug, removed test files as now in #1875 but also rebased on that to retain the tests and fix from there for further evolution of this (draft) PR to get locking right 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874#-:-NxOJCPUDWLRwiX2AJSg:b-4rmwkg)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH8sGw98tSywAOgcVy):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

You should add the prefix `[LibOS]`.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 362 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxH9_LhA4Xj5P-qjsir:-NxOHLQg-pYGH08UQkJ4:b7x6ecz) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L362)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The assert is now on the `handle_libos_call` which seems unrelated?
</blockquote></details>

gosh, what was i thinking (or more likely, i guess i was thinking nothing and some copy/paste got wrong although hard to see why this would have been in the copy-buffer)
___
*[`libos/test/regression/rename_unlink.c` line 185 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHABV5AmYxDbmPXHXZ:-NxOIHH35t1UzFhD8728:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't have a strong opinion, but our general practice for tests is:
1. Try to use the same style as in the core Gramine codebase
2. But if the test is already written in another style, conform to that style
3. Or first submit a PR that refactors the test to a better style, and only then modify the test
4. But generally -- these are just tests, we don't care that much. If you would say "No, there is an empty line in other already existing sub-tests, so I'll do that as well", no one would object.
</blockquote></details>

Done.
___
*[`libos/test/regression/rename_unlink.c` line 233 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHAatX0omvai5TNH8L:-NxOIsRt4m5eqYwHScY9:bbqzfa4) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/test/regression/rename_unlink.c#L233)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I would suggest new line.
</blockquote></details>

forgot to mark as done in my previous update; but now moved (in intended form) in #1875 (still showing up in this PR though through the rebase on #1875)
___
*[`libos/test/regression/rename_unlink.c` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxM-YIdBhoYD5AXgutx:-NxOHpTU23eE2CsYJD8S:b-aaxpub) ([raw file](https://github.com/gramineproject/gramine/blob/e36a532774bef0ebf4bc2e0b2b9cfc9ddf1eac7c/libos/test/regression/rename_unlink.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These changes were copied to #1875
</blockquote></details>

removed here now from my commits (although still visible as i rebased on top of 1875 so i still have the tests (as well as your fix which also affects locking strategy by removing some cases where otherwise there would have had to be additional locks)


<!-- Sent from Reviewable.io -->

2024-05-10 09:29 UTC, dimakuv reviewed
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @oshogbo)

___
*[`libos/include/libos_handle.h` line 168 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnhhpBIRDttPitHzF:-NxWnhhpBIRDttPitHzG:b-i27jv) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L168)):*
> ```objc
> 
>     struct libos_fs* fs;
>     /* dentry can change due to rename, so to secure read-access, aquire g_dcache_lock and/or
> ```

`acquire`
___
*[`libos/include/libos_handle.h` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnmPh1jOjRQ1ViY-2:-NxWnmPh1jOjRQ1ViY-3:b-l91od9) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L170)):*
> ```objc
>     /* dentry can change due to rename, so to secure read-access, aquire g_dcache_lock and/or
>      * handle->lock; to protect updates (unless during creation and deletion where unique use is
>      * guaranteed), acquire first g_dcache_lock and then handle-Lock */
> ```

Last word: I guess you meant `handle->lock`
___
*[`libos/include/libos_handle.h` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnyJP6WDoORmbKCAe:-NxWnyJP6WDoORmbKCAf:b-bs6lg) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L170)):*
> ```objc
>     /* dentry can change due to rename, so to secure read-access, aquire g_dcache_lock and/or
>      * handle->lock; to protect updates (unless during creation and deletion where unique use is
>      * guaranteed), acquire first g_dcache_lock and then handle-Lock */
> ```

Is such an order easy to guarantee in our codebase? I would imagine that we have many funcs that operate on the handle and thus perform `handle->lock`, and then in some helper funcs we may want to operate on this `dentry`. This would mean that we have to check all callers of such helper funcs and make sure they take (perhaps unnecessarily) the `g_dcache_lock`...
___
*[`libos/src/fs/libos_namei.c` line 747 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWp2uOBnL6ApwTO1no:-NxWp2uOBnL6ApwTO1np:b4rymt8) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/src/fs/libos_namei.c#L747)):*
> ```C
>     get_dentry(hdl->dentry);
>     *dir = hdl->dentry;
>     unlock(&hdl->lock);
> ```

While this additional locking doesn't seem too bad (it's only three cases uncovered in this PR -- I wonder if that's really all), this feels very brittle.

I really think it's time to try to remove `hdl->dentry` completely and only keep the `hdl->inode`. Maybe with one exception of flocks/POSIX locks -- where we can do something hacky.


<!-- Sent from Reviewable.io -->

2024-05-10 19:19 UTC, g2flyer reviewed
I think after this update the locking should be fine -- main exception is that i'm not 100% sure of semantics of g_process.fs_lock and depending on it some additional handle locks might not be necessary ... -  As part of that, though, i wonder whether dentry->inode also wouldn't have to be lock protected given that (at least) rename and unlink do modify it but we have code like `if (!dent->inode || dent->inode->type != S_IFDIR)` in `libos_syscall_fchndir`?  Also, i guess `fchdir` has the same issue as `fcntl/flock` that it is here path-based whereas in posix it is inode based, so wouldn't work with renames?  (not that my changes should have really changed anything in what works or does not work afaict)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874#-:-NxYv_vY-f5Shr03L5qz:b-y1l1x3)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/include/libos_handle.h` line 168 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnhhpBIRDttPitHzF:-NxY2MeB5isabv4BaU9c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`acquire`
</blockquote></details>

Done.
___
*[`libos/include/libos_handle.h` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnmPh1jOjRQ1ViY-2:-NxY2N7W2lIcxsIvLsGs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Last word: I guess you meant `handle->lock`
</blockquote></details>

Done.
___
*[`libos/include/libos_handle.h` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnyJP6WDoORmbKCAe:-NxY2PcnAPJUpFvqYa2B:bd011ax) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is such an order easy to guarantee in our codebase? I would imagine that we have many funcs that operate on the handle and thus perform `handle->lock`, and then in some helper funcs we may want to operate on this `dentry`. This would mean that we have to check all callers of such helper funcs and make sure they take (perhaps unnecessarily) the `g_dcache_lock`...
</blockquote></details>

i want through the dereferences of `dentry` (via vscode's intellisense) and then looked at caller and callees of these locations. Turns out intellisense was leaky and missing a few cases which i found now with help of good old `grep -r` and alike. So there are a few additional locks required.

The order g_cache_lock > hdl->lock is actually already assumed by (callers of) `populate_directory_handle` in `libnos_namei.c` as that functions requires both locks to be held and both callers in `libos_open.c` lock `g_dcache_lock` before `hdl->lock`.  So what the comment says (and what the code changes still should garantuee) should be safe
___
*[`libos/src/fs/libos_namei.c` line 747 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWp2uOBnL6ApwTO1no:-NxY3x9KEFOIp55WVygK:b-knkq4r) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/src/fs/libos_namei.c#L747)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

While this additional locking doesn't seem too bad (it's only three cases uncovered in this PR -- I wonder if that's really all), this feels very brittle.

I really think it's time to try to remove `hdl->dentry` completely and only keep the `hdl->inode`. Maybe with one exception of flocks/POSIX locks -- where we can do something hacky.
</blockquote></details>

I didn't find too many places where `hdl->dentry` was used, so probably could be removed without too much changes.  That said, with this fix here, i can get #1856 working in the sense that it is a very simple test to see whether a closed file is still visible in the filesystem (directory) or not; if `hdl->dentry' disappears the only alternative i see is to keep in the valid-root-hash-map an additional list with all open hdls pointing to a particular path and that seems more messy and complex than the current approach (and definitely requires overall more changes)


<!-- Sent from Reviewable.io -->

2024-05-13 07:41 UTC, dimakuv reviewed
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @oshogbo)

___
*[`libos/include/libos_handle.h` line 170 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWnyJP6WDoORmbKCAe:-Nxkodp_EKeyS9YMJ82q:bn9s4dr) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/include/libos_handle.h#L170)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

i want through the dereferences of `dentry` (via vscode's intellisense) and then looked at caller and callees of these locations. Turns out intellisense was leaky and missing a few cases which i found now with help of good old `grep -r` and alike. So there are a few additional locks required.

The order g_cache_lock > hdl->lock is actually already assumed by (callers of) `populate_directory_handle` in `libnos_namei.c` as that functions requires both locks to be held and both callers in `libos_open.c` lock `g_dcache_lock` before `hdl->lock`.  So what the comment says (and what the code changes still should garantuee) should be safe
</blockquote></details>

Yes, I agree, the caller of `populate_directory_handle()` already imposes such an order: https://github.com/gramineproject/gramine/blob/25056d0b8e7549d37b73f4a2c9dd90ab7c35f471/libos/src/sys/libos_open.c#L181-L204
___
*[`libos/include/libos_handle.h` line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkp0Rb5985nTmsJ__W:-Nxkp0Rb5985nTmsJ__X:b-nal8mr) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/include/libos_handle.h#L169)):*
> ```objc
>     struct libos_fs* fs;
>     /* dentry can change due to rename, so to secure read-access, acquire g_dcache_lock and/or
>      * handle->lock; to protect updates (unless during creation and deletion where unique use is
> ```

Why, for read access, you recommend to acquire any of the two locks?

I would be specific and ask to acquire `handle->lock`. I understand that both locks work, but this creates ambiguity for future devs. And technically `handle->lock` is an appropriate one in this case. So I would just change to `acquire handle->lock`
___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-NxkpXyz5eYjpxIAB31J:b-ctw3ve) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
> ```C
>     lock(&handle->lock);
>     struct libos_dentry* dent = handle->dentry;
>     unlock(&handle->lock);
> ```

This looks wrong. If the `dent` becomes unused, it may be garbage-collected before we call `pseudo_istat()`, and that function will work on a dangling pointer.

You should do this instead:
```
    int ret = -ENOENT;
    lock(&handle->lock);
    if (handle->dentry)
        ret = pseudo_istat(handle->dentry, handle->inode, buf);
    unlock(&handle->lock);
    return ret;
```

Looks like this function assumes that `handle->dentry` is initialized here, so the IF in my code snippet may be useless. One needs to analyze the callers of this func to understand if we can remove that.
___
*[`libos/src/fs/libos_namei.c` line 747 at r3](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxWp2uOBnL6ApwTO1no:-NxkqULp88KB14FMmXnF:b-y6o60h) ([raw file](https://github.com/gramineproject/gramine/blob/3edeb3de111287ad76a3dffa04d5f16da9c4be83/libos/src/fs/libos_namei.c#L747)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

I didn't find too many places where `hdl->dentry` was used, so probably could be removed without too much changes.  That said, with this fix here, i can get #1856 working in the sense that it is a very simple test to see whether a closed file is still visible in the filesystem (directory) or not; if `hdl->dentry' disappears the only alternative i see is to keep in the valid-root-hash-map an additional list with all open hdls pointing to a particular path and that seems more messy and complex than the current approach (and definitely requires overall more changes)
</blockquote></details>

Ok, I agree that removing `hdl->dentry` will be a big task, and we should take small steps. I'm unblocking this discussion, as we seem to have fixed all `hdl->dentry` places in the codebase.
___
*[`libos/src/fs/proc/thread.c` line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkqha1AVlcd6il9OQv:-Nxkqha1AVlcd6il9OQw:bf6j90b) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/proc/thread.c#L34)):*
> ```C
>         lock(&g_process.exec->lock);
>         dent = g_process.exec->dentry;
>         unlock(&g_process.exec->lock);
> ```

Same problem as discussed in another comment -- `dent` may be garbage-collected. So you need to move the `unlock()` two lines below. This is because if `get_dentry(dent)` happens under the lock, then we are guaranteed that dentry won't be freed -- Gramine will know that there is at least one caller of this object still processing.
___
*[`libos/src/sys/libos_fcntl.c` line 204 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxksBfr1HdxAN5Atkq6:-NxksBfr1HdxAN5Atkq7:b-ktjhbw) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L204)):*
> ```C
>             lock(&hdl->lock);
>             struct libos_dentry* dent = hdl->dentry;
>             unlock(&hdl->lock);
> ```

That's wrong because `file_lock_set(dent ...)` may work on a dangling pointer.

This whole code snippet looks wrong, it doesn't have any locking or `get_dentry()`. Hmm, or no, this code snippet is fine -- it takes a reference of `hdl` and assumes that `hdl->dentry` is immutable.

So yes, in this PR, we must either keep the `hdl->lock` until the very end of this case, or `get_dentry()`.
___
*[`libos/src/sys/libos_fcntl.c` line 243 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkrvu3602VQOIgns7y:-Nxkrvu3602VQOIgns7z:b3jcylw) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L243)):*
> ```C
>             lock(&hdl->lock);
>             struct libos_dentry* dent = hdl->dentry;
>             unlock(&hdl->lock);
> ```

That's wrong because `file_lock_get(dent ...)` may work on a dangling pointer.

Same notes as in the comment above.
___
*[`libos/src/sys/libos_fcntl.c` line 353 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkso5r3Oh6snMuVO5x:-Nxkso5r3Oh6snMuVO5y:bqa269k) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L353)):*
> ```C
>         .handle_id = hdl->id,
>     };
>     
> ```

Please remove spaces
___
*[`libos/src/sys/libos_fcntl.c` line 356 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxksq_XAdZNnNig3f2-:-Nxksq_XAdZNnNig3f20:b-b2cmqr) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L356)):*
> ```C
>     lock(&hdl->lock);
>     struct libos_dentry* dent = hdl->dentry;
>     unlock(&hdl->lock);
> ```

ditto, cannot unlock here, otherwise dangling pointer.
___
*[`libos/src/sys/libos_getcwd.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxksyhv1v_vZAGYvtvV:-Nxksyhv1v_vZAGYvtvW:bu6vkpw) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_getcwd.c#L87)):*
> ``` [...]

2024-05-13 16:05 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/include/libos_handle.h` line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkp0Rb5985nTmsJ__W:-NxmcAVeEK8eSab7ay4g:b-m130yc) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/include/libos_handle.h#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why, for read access, you recommend to acquire any of the two locks?

I would be specific and ask to acquire `handle->lock`. I understand that both locks work, but this creates ambiguity for future devs. And technically `handle->lock` is an appropriate one in this case. So I would just change to `acquire handle->lock`
</blockquote></details>

From a safety (& liveness) perspective either should be enough and while handle->lock would be the natural one, there were places such as in libos_syscall_ioctl which already had the `g_dcache_lock` or `libsys_syscal_mknodat`, so to minimize changes seemed to allow this also?  But of course i could add handle->locks there as well if you prefer ...
___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-NxmdGuJAVKtJS1wVsNH:b45ek37) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks wrong. If the `dent` becomes unused, it may be garbage-collected before we call `pseudo_istat()`, and that function will work on a dangling pointer.

You should do this instead:
```
    int ret = -ENOENT;
    lock(&handle->lock);
    if (handle->dentry)
        ret = pseudo_istat(handle->dentry, handle->inode, buf);
    unlock(&handle->lock);
    return ret;
```

Looks like this function assumes that `handle->dentry` is initialized here, so the IF in my code snippet may be useless. One needs to analyze the callers of this func to understand if we can remove that.
</blockquote></details>

I see what you mean.  I thought this is only to deal with cached meta-data as get_handle just increases a reference counter and put_handle doesn't invalidate (NULL) the pointers even inside or on the outside of the cases i've seen.  Maybe beyond this PR but wouldn't it be better that put_handle would get a reference to the pointer which could be NULLed iff ref count is really zero?  But short term i guess the better approach is what you hinted below is two wrap the derefence by get_dentry/put_dentry?


<!-- Sent from Reviewable.io -->

2024-05-14 07:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @oshogbo)

___
*[`libos/include/libos_handle.h` line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkp0Rb5985nTmsJ__W:-NxpuIuG9sgtZRzlvAuR:b-21v7u4) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/include/libos_handle.h#L169)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

From a safety (& liveness) perspective either should be enough and while handle->lock would be the natural one, there were places such as in libos_syscall_ioctl which already had the `g_dcache_lock` or `libsys_syscal_mknodat`, so to minimize changes seemed to allow this also?  But of course i could add handle->locks there as well if you prefer ...
</blockquote></details>

Ok, let's keep like this.
___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-Nxpv-B_Bb_su2INARid:bea9spe) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
> Maybe beyond this PR but wouldn't it be better that put\_handle would get a reference to the pointer which could be NULLed iff ref count is really zero?

This sounds pretty uncommon? I don't remember semantics like this in any reference-counting implementations I've seen. Anyway, this is something orthogonal to this PR.

> But short term i guess the better approach is what you hinted below is two wrap the derefence by get\_dentry/put\_dentry?

Yes, well, two approaches (I described both in the PR):
- In some cases, just extend the `handle->lock` to cover all related lines of code (like in this particular example here). No need to complicate with getting the reference and putting it back, just to get `stat` buffer.
- In other cases, where more stuff happens to dentry, it's better to get the reference and then drop it at func end.


<!-- Sent from Reviewable.io -->

2024-05-15 17:11 UTC, g2flyer reviewed
Ok, next try :-)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874#-:-NxxE9DAEMoOs6m4A6wL:b-ekpr2f)* status: 7 of 13 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-Nxx9yTD5GCVRFxG-DTh:b-hawqqr) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Maybe beyond this PR but wouldn't it be better that put\_handle would get a reference to the pointer which could be NULLed iff ref count is really zero?

This sounds pretty uncommon? I don't remember semantics like this in any reference-counting implementations I've seen. Anyway, this is something orthogonal to this PR.

> But short term i guess the better approach is what you hinted below is two wrap the derefence by get\_dentry/put\_dentry?

Yes, well, two approaches (I described both in the PR):
- In some cases, just extend the `handle->lock` to cover all related lines of code (like in this particular example here). No need to complicate with getting the reference and putting it back, just to get `stat` buffer.
- In other cases, where more stuff happens to dentry, it's better to get the reference and then drop it at func end.
</blockquote></details>

Moved locks, although it is a bit more complicated as `do_hstat` from `libos_stat.c` requires a lock before calling `fs_ops->hstat` for consistency of `dentry` yet other callers of `fs_ops->hstat` do not have the lock, so have to do it conditionally.    
Regarding whether we need the if or not, it looks currently a bit inconsistent: `generic_inode_hstat` has an assert(handle->inode) and is used by a number of fs as fs_ops.hstat.  Yet others, e.g., the `hstat` in `libos_fs_path.c` checks (as only action before redirecting to `generic_inode_hstat`.  Based on this i added the if as you had it to be on the safe side ....
___
*[`libos/src/fs/proc/thread.c` line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkqha1AVlcd6il9OQv:-Nxx6LKs4DBUdk6AAaUV:b-o7gkc) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/proc/thread.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same problem as discussed in another comment -- `dent` may be garbage-collected. So you need to move the `unlock()` two lines below. This is because if `get_dentry(dent)` happens under the lock, then we are guaranteed that dentry won't be freed -- Gramine will know that there is at least one caller of this object still processing.
</blockquote></details>

Yep, i release lock too early. Moving it to after the `get_dentry` should make it safe
___
*[`libos/src/sys/libos_fcntl.c` line 204 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxksBfr1HdxAN5Atkq6:-NxxC5V255yrION7kF35:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's wrong because `file_lock_set(dent ...)` may work on a dangling pointer.

This whole code snippet looks wrong, it doesn't have any locking or `get_dentry()`. Hmm, or no, this code snippet is fine -- it takes a reference of `hdl` and assumes that `hdl->dentry` is immutable.

So yes, in this PR, we must either keep the `hdl->lock` until the very end of this case, or `get_dentry()`.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_fcntl.c` line 243 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkrvu3602VQOIgns7y:-NxxC6-k5zKa6zbb_J6_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's wrong because `file_lock_get(dent ...)` may work on a dangling pointer.

Same notes as in the comment above.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_fcntl.c` line 353 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxkso5r3Oh6snMuVO5x:-NxxCxTx7tyR_oFvB7X2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L353)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove spaces
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_fcntl.c` line 356 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxksq_XAdZNnNig3f2-:-NxxCCU76MxHt6Nck9DV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_fcntl.c#L356)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, cannot unlock here, otherwise dangling pointer.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_file.c` line 370 at r1](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHX2TU6MLuocNiRxn4:-NxxDFyS5RQdUYj-Er6W:b-380qf0) ([raw file](https://github.com/gramineproject/gramine/blob/abf2ff74397fd860800f4bc17b2783695c1a5e00/libos/src/sys/libos_file.c#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll keep this as blocking comment then.
</blockquote></details>

this should be hopefully fixed now (and hence i removed the TODO, although for now leave the 'draft' as it is still rebased on #1875 which has the test cases but is not yet merged
___
*[`libos/src/sys/libos_getcwd.c` line 87 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-Nxksyhv1v_vZAGYvtvV:-NxxDt_4AHlGB2GI4Uuc:bi73oyo) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_getcwd.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto. Here you should `get_dentry()` under the lock and at the end of the func `put_dentry()`
</blockquote></details>

for other reason (discussed bug around ` if (!dent\->inode || dent\->inode\->type != S\_IFDIR) {` i switched to `g_dcache_lock` and across the whole function.
___
*[`libos/src/sys/libos_stat.c` line 217 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxktNHk7OAsc401iyi_:-Nxx-GwV45iPfoOTDXD0:bheioqv) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/sys/libos_stat.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: here we are fine because `mount` objects are immutable and are never freed.
</blockquote></details>

Rename doesn't work across mount-points, so true that mount should everywhere be the same. But you still need look as there are two dereferences from hdl->dentry?  


<!-- Sent from Reviewable.io -->

2024-06-12 16:56 UTC, g2flyer reviewed
As PR #1875 (which containing parts originally here)  is merged, i rebased this PR to a clean state (retaining, though, the fixups which were already  discussed) and moved the PR back out of draft into active state

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874#-:-O-CN4Dr1A_aLSDZKhPP:b-vi7c0f)* status: 3 of 13 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)



<!-- Sent from Reviewable.io -->

2024-06-13 08:00 UTC, dimakuv requested changes
> Reviewed 1 of 6 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: 7 of 13 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxHOjy_BTeS5Nem7tSP:-O-FXJmn4i4pRKmWXtVh:b-4fqoc9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For other reviewers: `fchown()` fails with ENOENT because it operates through the dentry of the handle, and if it doesn't find the inode associated with the dentry, it returns with ENOENT.

And since during `rename()`, the inode of the old dentry is NULLified (see the surrounding code in this PR), we end up in this error path: https://github.com/gramineproject/gramine/blob/80377ca17561ab0ce7bcfd59569dd49a567fddb0/libos/src/sys/libos_file.c#L297
</blockquote></details>

This was fixed by https://github.com/gramineproject/gramine/commit/db1d16db3b1b08c6b58673d29e5cffab8d58e1e0, already in master and in this PR. Resolving.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-O-F_wydDupXObHSvDMm:-O-F_wydDupXObHSvDMn:bnlcco0) (no related file):*
Sorry, these `libos_handle::dentry` locking fixes are getting too complicated.

Ideally, we must choose one lock to acquire; the possibility to use any of the two locks (dentry-global or handle-specific) is plain weird.

The current locks are sprinkled around functions, so it's very hard to notice and reason about. I think we should rework that to acquire the locks at the beginning of funcs and release at the end of funcs.

We definitely must **not** introduce conditional locking. Instead, if such situations arise, we need to rework the functions and their callers, possibly splitting/duplicating the funcs.

Finally, I would split this PR into a series of PRs: each PR fixing one usage of `hdl->dentry`.

I suggest we discuss what to do here in the next Gramine community meeting. I added to the agenda. I can drive that discussion, if @g2flyer won't be able to attend. See https://github.com/gramineproject/gramine/discussions/1906

___
___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-O-FZDGp-gjL_U1Evi_o:by3kwrr) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

Moved locks, although it is a bit more complicated as `do_hstat` from `libos_stat.c` requires a lock before calling `fs_ops->hstat` for consistency of `dentry` yet other callers of `fs_ops->hstat` do not have the lock, so have to do it conditionally.    
Regarding whether we need the if or not, it looks currently a bit inconsistent: `generic_inode_hstat` has an assert(handle->inode) and is used by a number of fs as fs_ops.hstat.  Yet others, e.g., the `hstat` in `libos_fs_path.c` checks (as only action before redirecting to `generic_inode_hstat`.  Based on this i added the if as you had it to be on the safe side ....
</blockquote></details>

Sorry, this is a hard no. Conditional locking is a bad smell.


<!-- Sent from Reviewable.io -->

2024-06-18 04:59 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1874)* status: 7 of 13 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1874#-O-F_wydDupXObHSvDMm:-O-d_J6s2XyubGdtePbZ:betjmqm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, these `libos_handle::dentry` locking fixes are getting too complicated.

Ideally, we must choose one lock to acquire; the possibility to use any of the two locks (dentry-global or handle-specific) is plain weird.

The current locks are sprinkled around functions, so it's very hard to notice and reason about. I think we should rework that to acquire the locks at the beginning of funcs and release at the end of funcs.

We definitely must **not** introduce conditional locking. Instead, if such situations arise, we need to rework the functions and their callers, possibly splitting/duplicating the funcs.

Finally, I would split this PR into a series of PRs: each PR fixing one usage of `hdl->dentry`.

I suggest we discuss what to do here in the next Gramine community meeting. I added to the agenda. I can drive that discussion, if @g2flyer won't be able to attend. See https://github.com/gramineproject/gramine/discussions/1906
</blockquote></details>

It's a while back and i haven't "swapped back in" all the context i have in my notes.  But thinking right now i think there is probably a bit a mixup between locks which protect the dentry pointer in the handle itself (for which the handle's lock should be the right lock) and a lock you need for reading changeable fields in the handle dereferenced dentry itself (only inode i think, which requires g_dcache_lock).   I vaguely remember i was worried that requiring both locks would give issue with circular lock-dependencies but i'm actually not sure anymore why (and how) the current strategy should have overcome that perceived problem. And neither looking at my notes during the call/lock analysis nor looking at the code right now i see why the strategy above (dentry dereference via hdl-lock and dentry->inode dereference via additional g_dcache_lock (as already required) wouldn't work. 

Regarding splitting in different PRs, i certainly can see a separate PR for the refactoring around hstat to remove the need for conditional locking.  But for the rest i'm a bit worried that splitting risks getting the big picture lost.  But then i probably don't understand how exactly you wanted to split

___
___
*[`libos/src/fs/libos_fs_pseudo.c` line 271 at r4](https://reviewable.io/reviews/gramineproject/gramine/1874#-NxkpXyz5eYjpxIAB31I:-O-dXW3z4ykwHzV_3d1K:b-ans7t4) ([raw file](https://github.com/gramineproject/gramine/blob/18fa74911396d1180a9dfb347ef2102efe95a085/libos/src/fs/libos_fs_pseudo.c#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, this is a hard no. Conditional locking is a bad smell.
</blockquote></details>

I've seen conditional locking elsewhere and it was the solution which touched fewest places.  That said, not conditional locking is not great and consistently acquiring (and documenting corresponding requirement) locking for all fs_ops->hstat definitely looks cleaner; as part probably the hstat top-level handlers also can be made more consistent/"standardized" 


<!-- Sent from Reviewable.io -->

2024-08-22 18:55 UTC, g2flyer commented
Closing this PR as a revised (simplified and cleaned-up) version of the fix is available as PR #1979

2024-08-22 18:55 UTC, closed without merging