[CI-Examples,Docs] Add `helloworld` example
gramineproject/gramine pull request #188
Opened 2021-11-02 12:03 UTC by pwmarcz

## Description of the changes 

Gramine's "quick start" guides recommended running the `helloworld` regression test, but this now requires an extra flag for Meson (`-Dtests=enabled`) that we do not want to recommend to first-time users. Instead, there's a standalone `helloworld` example.

## How to test this PR? 

Compile and run the example yourself.

2021-11-02 12:23 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[CI-Examples/helloworld/helloworld.manifest.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaDsBCXMhZ_j4azDQ:-MnVaDsBCXMhZ_j4azDR:b-lwv6fy) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L8)):*
> ```
> loader.argv0_override = "helloworld"
> 
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}"
> ```

I don't think you need `arch_libdir` at all. `/lib` should be enough for HelloWorld -- it only should use libc.so.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaJ_-2AHtDuJhpjPJ:-MnVaJ_-2AHtDuJhpjPK:b-tdz4e2) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L16)):*
> ```
> fs.mount.lib2.type = "chroot"
> fs.mount.lib2.path = "{{ arch_libdir }}"
> fs.mount.lib2.uri = "file:{{ arch_libdir }}"
> ```

ditto, please remove this mount point
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaLZf0prqNTMBfUnx:-MnVaLZf0prqNTMBfUny:bko76i7) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L24)):*
> ```
>   "file:{{ gramine.runtimedir() }}/",
>   "file:{{ arch_libdir }}/",
>   "file:/usr/{{ arch_libdir }}/",
> ```

ditto, please remove the last two lines


<!-- Sent from Reviewable.io -->

2021-11-02 12:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: 9 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[CI-Examples/helloworld/helloworld.manifest.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaDsBCXMhZ_j4azDQ:-MnVegmTBOqw2ndIVWiq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need `arch_libdir` at all. `/lib` should be enough for HelloWorld -- it only should use libc.so.
</blockquote></details>

Done.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaJ_-2AHtDuJhpjPJ:-MnVehMv8nrv5fSnpBHT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, please remove this mount point
</blockquote></details>

Done.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/188#-MnVaLZf0prqNTMBfUnx:-MnVehnuECIlY5rAz1LN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7b954f5886e321a0be0f34bae1b9159df17ee26e/CI-Examples/helloworld/helloworld.manifest.template#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, please remove the last two lines
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-02 13:11 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-03 09:13 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-04 09:39 UTC, woju approved these changes
> Reviewed 8 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-04 10:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-11-04 11:21 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/188#-MnefGoA43rcxSQ-1vVI:-MnefGoA43rcxSQ-1vVJ:bllde7w) (no related file):*
Do we want to add another example just for this?

Maybe we could describe running some other simple example instead? I still have very painful memories from having to patch all the examples on each manifest / loader change.

---


<!-- Sent from Reviewable.io -->

2021-11-04 11:28 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/188#-MnefGoA43rcxSQ-1vVI:-MnefddN-7N2grliB9l-:b-wk4cxy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we want to add another example just for this?

Maybe we could describe running some other simple example instead? I still have very painful memories from having to patch all the examples on each manifest / loader change.
</blockquote></details>

We talked about this in https://github.com/gramineproject/gramine/pull/187. I think there's value in having a "simplest possible" example, and I don't think any of the existing ones fit this use case.

We could ask people to run something like Bash or Busybox, but: they're more complicated, it might be unclear for the user what part of functionality comes from host and what's emulated, and it's kind of awkward when they don't detect the TTY and there's no prompt. 

Another option would be Python, but IMO too many things can go wrong with paths/libraries.

---


<!-- Sent from Reviewable.io -->

2021-11-04 11:36 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-11-04 11:38 UTC, woju submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/188#-MnefGoA43rcxSQ-1vVI:-MnejBV1C5kExNjnEV_P:b-2r5rlc) (no related file):*
> Do we want to add another example just for this?

It's not "just for this", it's good learning flow. Here you get to know what a manifest is. It's pity it's hidden by makefile.

---


<!-- Sent from Reviewable.io -->

2021-11-11 14:56 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/188#-MnefGoA43rcxSQ-1vVI:-MoET2tu-iZp45BaGth7:b-5cxbex) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Do we want to add another example just for this?

It's not "just for this", it's good learning flow. Here you get to know what a manifest is. It's pity it's hidden by makefile.
</blockquote></details>

Hmm, ok, I won't block on this, although I don't like it :)

---


<!-- Sent from Reviewable.io -->

2021-11-11 15:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CI-Examples/helloworld/helloworld.manifest.template, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/188#-MoEZFln6ip3CjEnr86W:-MoEZFln6ip3CjEnr86X:b-jvrx93) ([raw file](https://github.com/gramineproject/gramine/blob/983028dfcb77afe1842bdd572e3658b3f9c0758b/CI-Examples/helloworld/helloworld.manifest.template#L3)):*
> ```
> # Hello World manifest file example
> 
> loader.entrypoint = "file:{{ gramine.libos }}"
> ```

FYI: Please note that I fixed this example to use the new-style `loader.entrypoint`


<!-- Sent from Reviewable.io -->

2021-11-11 15:27 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-11 16:16 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/188)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-11 17:29 UTC, merged