[LibOS] Add `stat()` and `hstat()` callbacks to FIFOs
gramineproject/gramine pull request #1897
Opened 2024-06-05 12:52 UTC by dimakuv

## Description of the changes 

Previously, FIFO pseudo-files (named pipes) did not have callbacks of `stat()` (used on FIFO filenames) and `hstat()` (used on FIFO handles/FDs). This breaks some apps that want to double-check that the file they have opened or want to open is a FIFO, using the `stat()` or `fstat()` syscalls. There was no good reason to skip those callbacks, so this commit adds their dummy implementations.

Fixes #1896.

## How to test this PR? 

Added some sub-tests in LibOS, and activated `read03` in LTP.

2024-06-05 19:19 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1897)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/mkfifo.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1897#-NzdoXgaDtk-wMC_Z_TE:-NzdoXgaDtk-wMC_Z_TF:b-nub3ai) ([raw file](https://github.com/gramineproject/gramine/blob/6390321f235fe8a531788d3ade176631d48f57fc/libos/test/regression/mkfifo.c#L23)):*
> ```C
>     }
> 
>     struct stat buf;
> ```

I really dislike having `buf` and `buffer` in a single function at the same time.



_Suggestion:_
```C
struct stat stat_buf;
```
___
*[`libos/test/regression/mkfifo.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1897#-NzdooJp6edThGpPivoZ:-NzdooJp6edThGpPivo_:bygtoiz) ([raw file](https://github.com/gramineproject/gramine/blob/6390321f235fe8a531788d3ade176631d48f57fc/libos/test/regression/mkfifo.c#L46)):*
> ```C
>         }
> 
>         struct stat buf;
> ```

ditto, OTOH, you already have a buffer which you could use here, why another one?


<!-- Sent from Reviewable.io -->

2024-06-05 19:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1897)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/mkfifo.c` line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/1897#-NzdoXgaDtk-wMC_Z_TE:-NzdwPw-3W2DgicEJc3J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6390321f235fe8a531788d3ade176631d48f57fc/libos/test/regression/mkfifo.c#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I really dislike having `buf` and `buffer` in a single function at the same time.
</blockquote></details>

Done.
___
*[`libos/test/regression/mkfifo.c` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/1897#-NzdooJp6edThGpPivoZ:-NzdwQGw-ztfVlxbNYaN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6390321f235fe8a531788d3ade176631d48f57fc/libos/test/regression/mkfifo.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto, OTOH, you already have a buffer which you could use here, why another one?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 22:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1897)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-06-06 02:33 UTC, kailun-qin approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1897)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-06-06 15:17 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1897)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-06 17:32 UTC, merged