[common] Refactor Protected Files, part 5
gramineproject/gramine pull request #1899
Opened 2024-06-07 10:08 UTC by dimakuv

## Description of the changes 

This commit refactors PF code without changing functionality (part 5 in a series of commits). In particular, this commit moves code around, rephrases some comments, removes useless comments and empty lines, as well as renames vague `data` and `block` words to more specific `node`.

This PR supersedes #1894.

## How to test this PR? 

N/A.

2024-06-08 01:47 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 188 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpQjY_0NlWfwtZKSXB:-NzpQjYaCM2ZcR5SIEpX:bgz4v6d) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L188)):*
> ```C
> }
> 
> static bool ipf_generate_nonced_metadata_key(pf_context_t* pf, pf_key_t* output) {
> ```

I preferred the old name, "generating a key" usually means some randomness. Maybe this way?



_Suggestion:_
```C
ipf_recreate_metadata_key
```
___
*[`common/src/protected_files/protected_files.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpRhA276jt8BREoFbl:-NzpRhA38pcgPhS8qoyZ:b-9c8cyg) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L223)):*
> crypto slot of MHT node

What do you mean by that?
___
*[`common/src/protected_files/protected_files.c` line 415 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpTRug50idBCcb51HQ:-NzpTRug50idBCcb51HR:b-vayym8) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L415)):*
> ```C
>     pf_key_t key;
> 
>     // new key for metadata node encryption, saves the key nonce in metadata plaintext header
> ```

Could you do that gluing of "meta" and "data" also in all other places in PF code?



_Code quote:_
```C
metadata
```
___
*[`common/src/protected_files/protected_files.c` line 421 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpTni1DCNw_sqx96oz:-NzpTni1DCNw_sqx96p-:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L421)):*
> ```C
>     }
> 
>     // encrypt metadata part-to-be-encrypted, also updates the MAC in metadata plaintext header
> ```





_Suggestion:_
```C
// encrypt metadata part-to-be-encrypted, also updating the MAC in metadata plaintext header
```
___
*[`common/src/protected_files/protected_files.c` line 550 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpUaC54T40G96rHDmj:-NzpUaC54T40G96rHDmk:b-325ox7) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L550)):*
> ```C
>     while (lruc_size(pf->cache) > MAX_NODES_IN_CACHE) {
>         void* node = lruc_get_last(pf->cache);
>         if (node == NULL) {
> ```

I think you should have kept the assert, not the `if` - look at the loop condition.
___
*[`common/src/protected_files/protected_files.c` line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpW88B84sLekGt4LZ3:-NzpW88B84sLekGt4LZ4:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L953)):*
> ```C
>     const unsigned char* data_to_write = (const unsigned char*)ptr;
> 
>     // the first 3KB of user data is written in the metadata node's encrypted part
> ```





_Suggestion:_
```C
// the first MD_USER_DATA_SIZE bytes of user data is written in the metadata node's encrypted part
```
___
*[`common/src/protected_files/protected_files.c` line 1040 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpWT127FFP9p_55nqM:-NzpWT127FFP9p_55nqN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L1040)):*
> ```C
>     unsigned char* out_buffer = (unsigned char*)ptr;
> 
>     // the first 3KB of user data is read from the metadata node's encrypted part
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-06-08 17:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: 2 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 188 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpQjY_0NlWfwtZKSXB:-Nzsxji04d0r4ral4B74:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L188)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I preferred the old name, "generating a key" usually means some randomness. Maybe this way?
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpRhA276jt8BREoFbl:-NzsxzzhCrR-pAiK8u9P:b-j7l9ve) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L223)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> crypto slot of MHT node

What do you mean by that?
</blockquote></details>

Please see the first diagram here: https://gramine.readthedocs.io/en/dimakuv-docs-encrypted-files/devel/encfiles.html#representation-on-host-storage-and-in-sgx-enclave-memory

Each MHT node has 96 "crypto slots", for each of the corresponding data nodes. Each "crypto slot" contains two values: 16-byte key and 16-byte MAC.

So my comment says that when the data node is being encrypted, the crypto slot (here referred via the variable `gcm_crypto_data`) is filled with two values: the code above fills the key, and the encryption operation here fills the MAC.

How do you want me to reformulate? Or maybe change some names (I'll rename some variables/fields in a follow up PR.)
___
*[`common/src/protected_files/protected_files.c` line 415 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpTRug50idBCcb51HQ:-NzsymP1EICjA4yyUDbv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L415)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you do that gluing of "meta" and "data" also in all other places in PF code?
</blockquote></details>

Done.
___
*[`common/src/protected_files/protected_files.c` line 421 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpTni1DCNw_sqx96oz:-NzsysVJ9o_IGZr24k6J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L421)):*
> ```C
>     }
> 
>     // encrypt metadata part-to-be-encrypted, also updates the MAC in metadata plaintext header
> ```

Done.
___
*[`common/src/protected_files/protected_files.c` line 550 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpUaC54T40G96rHDmj:-Nzsz4YF8deIw0nQnell:b-mz7303) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L550)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think you should have kept the assert, not the `if` - look at the loop condition.
</blockquote></details>

Yeah, I'm just confused by this `pf->last_error` thing. I still don't understand what exactly it's used for.

But I agree, this particular case must have an assert, not an IF condition -- the cache cannot be empty if its size is larger than MAX_NODES_IN_CACHE constant.
___
*[`common/src/protected_files/protected_files.c` line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpW88B84sLekGt4LZ3:-Nzsza459qLc1tnpUDqr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L953)):*
> ```C
>     const unsigned char* data_to_write = (const unsigned char*)ptr;
> 
>     // the first 3KB of user data is written in the metadata node's encrypted part
> ```

Done.
___
*[`common/src/protected_files/protected_files.c` line 1040 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpWT127FFP9p_55nqM:-NzszouR4q7Sw9qZ0iS6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L1040)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-08 23:53 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpRhA276jt8BREoFbl:-NzuDsAMD9ojCx6Sx8L-:b-1ped9d) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L223)):*
But the link you pasted doesn't mention "crypto slots"? This name sounds very confusing to me, both "crypto" (are they other types of slots here? non-crypto slots?) and "slot" (do you mean an array item by it? if not, then what?).

> Each MHT node has 96 "crypto slots", for each of the corresponding data nodes. Each "crypto slot" contains two values: 16-byte key and 16-byte MAC.

The diagram you linked to lists 96+32 such entries, not 96? One type is "data" and another is "mht", I'm still not sure which is "crypto".

> How do you want me to reformulate? Or maybe change some names (I'll rename some variables/fields in a follow up PR.)

Depending what exactly you mean, but I guess it's just "corresponding {entry,array item,field} of MHT node".


<!-- Sent from Reviewable.io -->

2024-06-09 19:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 223 at r1](https://reviewable.io/reviews/gramineproject/gramine/1899#-NzpRhA276jt8BREoFbl:-NzySiJYBW82ub7d2am_:b-yojwc4) ([raw file](https://github.com/gramineproject/gramine/blob/b8227e68efb5d733e5d5458ba3e025c9b1842a8d/common/src/protected_files/protected_files.c#L223)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the link you pasted doesn't mention "crypto slots"? This name sounds very confusing to me, both "crypto" (are they other types of slots here? non-crypto slots?) and "slot" (do you mean an array item by it? if not, then what?).

> Each MHT node has 96 "crypto slots", for each of the corresponding data nodes. Each "crypto slot" contains two values: 16-byte key and 16-byte MAC.

The diagram you linked to lists 96+32 such entries, not 96? One type is "data" and another is "mht", I'm still not sure which is "crypto".

> How do you want me to reformulate? Or maybe change some names (I'll rename some variables/fields in a follow up PR.)

Depending what exactly you mean, but I guess it's just "corresponding {entry,array item,field} of MHT node".
</blockquote></details>

Done.

Yes, "crypto slots" was my invention, but I agree that we should just go with a simple "array item".


<!-- Sent from Reviewable.io -->

2024-06-10 00:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-06-11 01:26 UTC, kailun-qin approved these changes
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-06-12 14:36 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1899)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-12 14:47 UTC, merged