[PAL,LibOS,common] Convert PAL errors to negative values
gramineproject/gramine pull request #1900
Opened 2024-06-07 11:25 UTC by oshogbo

## Description of the changes 

## How to test this PR?

2024-06-10 12:24 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 0 of 76 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[`common/include/pal_error.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-15Vf_9eC79yAZZRgg:-O-15Vfa1_y5DyfpOlri:bp6iaz4) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/common/include/pal_error.h#L39)):*
> ```objc
>     PAL_ERROR_CONNFAILED_PIPE = -24,
> 
> #define PAL_ERROR_NATIVE_COUNT ((-PAL_ERROR_CONNFAILED_PIPE) + 1)
> ```

Additionally, I have changed the COUNT macro.
I think that COUNT should have the actual COUNT of the elements (including 0), and not a number of the LAST element as it did before this change.


<!-- Sent from Reviewable.io -->

2024-06-11 09:05 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 0 of 76 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-5W8Yv-wj-WATjEkpp:-O-5W8Yv-wj-WATjEkpq:b-e5074j) (no related file):*
Generally looks ok to me. I'll wait for other reviewers' opinions.

___


<!-- Sent from Reviewable.io -->

2024-06-18 17:01 UTC, mkow requested changes
> Reviewed 2 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 2 of 76 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`libos/src/libos_init.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-gH9xV7EaDI9-Q0-2K:-O-gH9xV7EaDI9-Q0-2L:b-63ah0u) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/libos/src/libos_init.c#L45)):*
> ```C
> }
> 
> #define IDX(x)	[-(x)]
> ```

tab -> spaces
please grep the whole PR for that


<!-- Sent from Reviewable.io -->

2024-06-18 17:35 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 1 of 76 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/libos_init.c` line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-gH9xV7EaDI9-Q0-2K:-O-gOTnT8gXXb5CQlulf:b3e2cig) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/libos/src/libos_init.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tab -> spaces
please grep the whole PR for that
</blockquote></details>

Thanks!
Fixed.

```
$ git show | grep $'\\t'                                                                           
+#define IDX(x) [-(x)]
+#define IDX(x) [-(x)]
```


<!-- Sent from Reviewable.io -->

2024-06-24 10:15 UTC, dimakuv requested changes
> Reviewed 74 of 76 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-5W8Yv-wj-WATjEkpp:-O08jCLE95RPJVPifGBF:b-jrev3t) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Generally looks ok to me. I'll wait for other reviewers' opinions.
</blockquote></details>

I reviewed this PR completely (it was boring :)). Looks good.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08jH4H10dwO2XcWg3I:-O08jH4H10dwO2XcWg3J:budxm5e) (no related file):*
Could we have another PR that adds asserts in strategic places that error codes are negative? Like in those unix-to-pal and pal-to-unix functions? I recall that we used to have some places with positive error codes, but these all should be fixed by now?

___
___
*[`common/include/pal_error.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-15Vf_9eC79yAZZRgg:-O08eQI451iMk2-cVXlx:b-gku7aa) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/common/include/pal_error.h#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Additionally, I have changed the COUNT macro.
I think that COUNT should have the actual COUNT of the elements (including 0), and not a number of the LAST element as it did before this change.
</blockquote></details>

Actually, can we instead rename this COUNT macro, to be uniform with the `PAL_ERROR_CRYPTO_END` below?

Thus, I suggest `PAL_ERROR_NATIVE_END PAL_ERROR_CONNFAILED_PIPE`.

Alternatively, please change `PAL_ERROR_CRYPTO_END` macro, if you like your COUNT style better.
___
*[`common/src/pal_error.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08f64J3zhdSoB8Vf-R:-O08f64J3zhdSoB8Vf-S:bf5eg8p) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/common/src/pal_error.c#L8)):*
> ```C
> 
> #define IDX(x) [-(x)]
> static const char* g_pal_error_list[] = {
> ```

What I didn't realize before is that we have this constant array that has indices like `1015`, due to PAL_ERROR_CRYPTO_xxx. This eats ~8KB of the data segment for no good reason.

Do we want to modify the indices of PAL_ERROR_CRYPTO_xxx in the header file above? To start not with 1000, but e.g. with 100.
___
*[`libos/src/libos_init.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08g0b75EilLnfMKjbq:-O08g0b75EilLnfMKjbr:btb2vkv) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/libos/src/libos_init.c#L79)):*
> ```C
> }
> 
> long pal_to_unix_errno(long err) {
> ```

Don't we want to add a TODO/FIXME comment here to get rid of `err >= 0`?
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hBryASgsiyjeOUUO:-O08hBryASgsiyjeOUUP:b94yawr) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_linux_error.h#L62)):*
> ```objc
>  * \brief Translate UNIX error code into PAL error code.
>  *
>  * The sign of the error code is preserved.
> ```

Meh, I forgot what weird stuff we had in our error handling...

Could you add a TODO/FIXME comment here to remove the "positive error number" path (and replace with asserts)?
___
*[`pal/src/host/linux/pal_main.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hRAs2IOL_7sFOL7Y:-O08hRAs2IOL_7sFOL7Z:b-bti4wr) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L120)):*
> ```C
>         /* We are super early in the init sequence, TCB is not yet set, we probably should not call
>          * any logging functions. */
>         DO_SYSCALL(exit_group, -PAL_ERROR_NOMEM);
> ```

Well, this is just weird. Can we instead use `ENOMEM`? Or even hard-code to `1`.
___
*[`pal/src/host/linux/pal_main.c` line 166 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hi8j3JxRQeapAmpp:-O08hi8j3JxRQeapAmpq:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L166)):*
> ```C
>         /* We failed to install a TCB (and haven't applied relocations yet), so no other code will
>          * work anyway */
>         DO_SYSCALL(exit_group, -PAL_ERROR_DENIED);
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08iXll6wIbeZKv0Ac3:-O08iXll6wIbeZKv0Ac4:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux-sgx/pal_linux_error.h#L62)):*
> ```objc
>  * \brief Translate UNIX error code into PAL error code.
>  *
>  * The sign of the error code is preserved.
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-06-24 11:50 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-5W8Yv-wj-WATjEkpp:-O094L7hDbMQkgJW7AZb:b-vuj8ut) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I reviewed this PR completely (it was boring :)). Looks good.
</blockquote></details>

Thank you :)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08jH4H10dwO2XcWg3I:-O093TAuBakQz73lawvX:b-ctycrz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we have another PR that adds asserts in strategic places that error codes are negative? Like in those unix-to-pal and pal-to-unix functions? I recall that we used to have some places with positive error codes, but these all should be fixed by now?
</blockquote></details>

So instead of checking and returning the right value you want to assert, have I understood correctly?

___
___
*[`common/include/pal_error.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-15Vf_9eC79yAZZRgg:-O0939fM1ilPU-o68wQX:b-g4gdoc) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/common/include/pal_error.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, can we instead rename this COUNT macro, to be uniform with the `PAL_ERROR_CRYPTO_END` below?

Thus, I suggest `PAL_ERROR_NATIVE_END PAL_ERROR_CONNFAILED_PIPE`.

Alternatively, please change `PAL_ERROR_CRYPTO_END` macro, if you like your COUNT style better.
</blockquote></details>

Maybe let's just do both?
COUNT and END?

```
#define PAL_ERROR_NATIVE_END ((-PAL_ERROR_CONNFAILED_PIPE) + 1)
#define PAL_ERROR_NATIVE_COUNT (PAL_ERROR_NATIVE_END + 1)
```

And the same for `PAL_ERROR_CRYPTO`?
___
*[`common/src/pal_error.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08f64J3zhdSoB8Vf-R:-O093iHUA4nzFgfSjw-x:b-y2x4t6) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/common/src/pal_error.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What I didn't realize before is that we have this constant array that has indices like `1015`, due to PAL_ERROR_CRYPTO_xxx. This eats ~8KB of the data segment for no good reason.

Do we want to modify the indices of PAL_ERROR_CRYPTO_xxx in the header file above? To start not with 1000, but e.g. with 100.
</blockquote></details>

It sounds reasonable for me.
@mkow ?
___
*[`libos/src/libos_init.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08g0b75EilLnfMKjbq:-O093oEy1g0OKhto_RJj:b2y19ui) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/libos/src/libos_init.c#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to add a TODO/FIXME comment here to get rid of `err >= 0`?
</blockquote></details>

So we want TODO/FIXME or we want to add asserts?
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hBryASgsiyjeOUUO:-O093uGpCExV0tmW222x:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh, I forgot what weird stuff we had in our error handling...

Could you add a TODO/FIXME comment here to remove the "positive error number" path (and replace with asserts)?
</blockquote></details>

Ditto.
___
*[`pal/src/host/linux/pal_main.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hRAs2IOL_7sFOL7Y:-O0946WtEFJ4BW-VmudJ:b-afuw9l) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, this is just weird. Can we instead use `ENOMEM`? Or even hard-code to `1`.
</blockquote></details>

Should we do it in this PR? Wouldn't changing logic here be confusing when doing a `git log`?


<!-- Sent from Reviewable.io -->

2024-06-24 13:36 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08jH4H10dwO2XcWg3I:-O09RkabE_xQ3uqP0slQ:b-qedal0) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So instead of checking and returning the right value you want to assert, have I understood correctly?
</blockquote></details>

Let's move this conversation to one of the other comments. Resolving here.

___
___
*[`common/include/pal_error.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-15Vf_9eC79yAZZRgg:-O09RpOz0nucX7GtBZIz:bkyeta5) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/common/include/pal_error.h#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Maybe let's just do both?
COUNT and END?

```
#define PAL_ERROR_NATIVE_END ((-PAL_ERROR_CONNFAILED_PIPE) + 1)
#define PAL_ERROR_NATIVE_COUNT (PAL_ERROR_NATIVE_END + 1)
```

And the same for `PAL_ERROR_CRYPTO`?
</blockquote></details>

Yeah, let's do both.
___
*[`libos/src/libos_init.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08g0b75EilLnfMKjbq:-O09RsSg4Xn0SOnvYr8z:bhrmpva) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/libos/src/libos_init.c#L79)):*
What about this:
- Add TODO/FIXME comment in this PR
- Add asserts in another PR

This way we'll have a merge conflict regardless of the order of merging of PRs, so we won't forget about modifying in any of those PRs.

> So instead of checking and returning the right value you want to assert, have I understood correctly?

I mean let's assert that the incoming `err` value is always negative, and always return a negative value. So this:
```
long pal_to_unix_errno(long err) {
    assert(err <= 0);
    return -pal_to_unix_errno_positive((unsigned long)-err);
}
```
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hBryASgsiyjeOUUO:-O09SWnkDQJr_lMPkT1F:bdpbvoh) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

ditto (see my explanation in another comment)
___
*[`pal/src/host/linux/pal_main.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hRAs2IOL_7sFOL7Y:-O09S_Ak7nOvmXOt80fE:bxfr6ar) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L120)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Should we do it in this PR? Wouldn't changing logic here be confusing when doing a `git log`?
</blockquote></details>

Yes, let's do it in another PR.


<!-- Sent from Reviewable.io -->

2024-07-01 12:17 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 72 of 76 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`common/include/pal_error.h` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/1900#-O-15Vf_9eC79yAZZRgg:-O0iAvow9LqH2Vptc5BN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ed84d07dfc383c1bcf574aec8cee79a6612fe35/common/include/pal_error.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, let's do both.
</blockquote></details>

Done.
___
*[`libos/src/libos_init.c` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08g0b75EilLnfMKjbq:-O0iBQD_Cu6OsEaBF6z5:b-n3ar9w) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/libos/src/libos_init.c#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this:
- Add TODO/FIXME comment in this PR
- Add asserts in another PR

This way we'll have a merge conflict regardless of the order of merging of PRs, so we won't forget about modifying in any of those PRs.

> So instead of checking and returning the right value you want to assert, have I understood correctly?

I mean let's assert that the incoming `err` value is always negative, and always return a negative value. So this:
```
long pal_to_unix_errno(long err) {
    assert(err <= 0);
    return -pal_to_unix_errno_positive((unsigned long)-err);
}
```
</blockquote></details>

Sounds good. :)
I will add TODO in this and add it to my todo list, after merge I will create PR. :)
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hBryASgsiyjeOUUO:-O0iCVZE4hR5ieFeeird:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (see my explanation in another comment)
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_main.c` line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hRAs2IOL_7sFOL7Y:-O0iCXn23FRUAQ8ZdD_g:b-v237id) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's do it in another PR.
</blockquote></details>

Added todo list.
___
*[`pal/src/host/linux/pal_main.c` line 166 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08hi8j3JxRQeapAmpp:-O0iDc0qBAUlIgPAvcXL:b-v237id) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux/pal_main.c#L166)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Added todo list.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08iXll6wIbeZKv0Ac3:-O0iD7_O58sprijxSb_Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/pal/src/host/linux-sgx/pal_linux_error.h#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 12:56 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)

___
*[`common/src/pal_error.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08f64J3zhdSoB8Vf-R:-O0nVtbG8mWoIq9vAwKl:b-5uas17) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/common/src/pal_error.c#L8)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It sounds reasonable for me.
@mkow ?
</blockquote></details>

Also @mwkmwkmwk


<!-- Sent from Reviewable.io -->

2024-07-02 15:46 UTC, mkow commented
*[`common/src/pal_error.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08f64J3zhdSoB8Vf-R:-O0o6vXDEQgMRdZFTDNC:b5wsszy) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/common/src/pal_error.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also @mwkmwkmwk
</blockquote></details>

Sure, sounds like a good idea.


<!-- Sent from Reviewable.io -->

2024-07-02 16:32 UTC, mkow reviewed
> Reviewed 71 of 76 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mwkmwkmwk and @oshogbo)

___
*[`pal/src/host/linux/pal_linux_error.h` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oEEgA3CchHVlKQzvi:-O0oEEgA3CchHVlKQzvj:bea8tcq) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L10)):*
> ```objc
> #include "pal_error.h"
> 
> static int unix_to_pal_error_negative(int unix_errno) {
> ```

Maybe this way? Now pal error is negative by default, so no need to write it explicitly (and writing it is even a bit confusing, because it could be interpreted as a "negated PAL_ERROR_ASDF constant").



_Suggestion:_
```objc
positive_unix_to_pal_error
```
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O0oHLsG0QYPIDk06Zh2:b-981n56) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
> ```objc
>  * \brief Translate UNIX error code into PAL error code.
>  *
>  * The sign of the error code is preserved.
> ```

btw.: this IMO won't make sense after all these error codes changes, we should simplify this later and always return PAL_* constants with their "native" signedness.
___
*[`pal/src/host/linux/pal_linux_error.h` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oDtkU9Yxfd80-exjG:-O0oDtkU9Yxfd80-exjH:b-uvblnw) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L65)):*
> ```objc
>  */
> static __attribute__((unused)) int unix_to_pal_error(int unix_errno) {
>     // TODO: The unix_errno variable should always be negative.
> ```

In this case I think we should accept both, because in POSIX return values are negative, but `errno` variable holds a positive error number. So, it's used in both ways.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oFfz-DSAt1u0LA5hq:-O0oFfz-DSAt1u0LA5hr:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux-sgx/pal_linux_error.h#L10)):*
> ```objc
> #include "pal_error.h"
> 
> static int unix_to_pal_error_negative(int unix_errno) {
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oFfMc6Gi2K_iaXkFJ:-O0oFfMc6Gi2K_iaXkFK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux-sgx/pal_linux_error.h#L65)):*
> ```objc
>  */
> static __attribute__((unused)) int unix_to_pal_error(int unix_errno) {
>     // TODO: The unix_errno variable should always be negative.
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-03 06:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @mwkmwkmwk, and @oshogbo)

___
*[`pal/src/host/linux/pal_linux_error.h` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oEEgA3CchHVlKQzvi:-O0rF4MD7J4Hwmm8vU9l:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe this way? Now pal error is negative by default, so no need to write it explicitly (and writing it is even a bit confusing, because it could be interpreted as a "negated PAL_ERROR_ASDF constant").
</blockquote></details>

+1
___
*[`pal/src/host/linux/pal_linux_error.h` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oDtkU9Yxfd80-exjG:-O0rFJVx3uqGQQMtn97b:b-2ywhj7) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In this case I think we should accept both, because in POSIX return values are negative, but `errno` variable holds a positive error number. So, it's used in both ways.
</blockquote></details>

I will be fine with accepting both positive and negative `unix_errno`, but then don't forget to remove the minus in `-unix_to_pal_error_negative()`. Because we always want to return the PAL_* constant as it is, without any negations.


<!-- Sent from Reviewable.io -->

2024-07-08 10:29 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: 73 of 76 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @mwkmwkmwk)

___
*[`common/src/pal_error.c` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1900#-O08f64J3zhdSoB8Vf-R:-O1GrvuZ-kLcrrJ8Bf__:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/db7fe9cdd35fbe4b829356ead278953bd564fd4a/common/src/pal_error.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sure, sounds like a good idea.
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_linux_error.h` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oEEgA3CchHVlKQzvi:-O1GsMXW8eKDqSQQ66yG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O0tirsC7lQfqBtbXCyX:b-3dfnb3) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

btw.: this IMO won't make sense after all these error codes changes, we should simplify this later and always return PAL_* constants with their "native" signedness.
</blockquote></details>

Added to todos.
___
*[`pal/src/host/linux/pal_linux_error.h` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oDtkU9Yxfd80-exjG:-O0tivy_3rWsZiDw4mJe:bxxzsb5) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will be fine with accepting both positive and negative `unix_errno`, but then don't forget to remove the minus in `-unix_to_pal_error_negative()`. Because we always want to return the PAL_* constant as it is, without any negations.
</blockquote></details>

Ok, let's do this in separate PR. I will drop this TODO. And I will fallowup.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 10 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oFfz-DSAt1u0LA5hq:-O1GsUoP7CJUsHExiGRI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux-sgx/pal_linux_error.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_linux_error.h` line 65 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oFfMc6Gi2K_iaXkFJ:-O0tj3SZC3NhqttoZqND:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux-sgx/pal_linux_error.h#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 06:10 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @mwkmwkmwk)



<!-- Sent from Reviewable.io -->

2024-07-09 14:20 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O1MrAlHDfdVnpRlhAhD:b-1fkar4) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Added to todos.
</blockquote></details>

TODOs where? Private or is there some issue about it? (I'd prefer an issue, but not blocking)


<!-- Sent from Reviewable.io -->

2024-07-09 14:25 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O1MsQpAC4dVg09trafe:b-1e52l2) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODOs where? Private or is there some issue about it? (I'd prefer an issue, but not blocking)
</blockquote></details>

My private... I was planing to follow up (in days) with it.


<!-- Sent from Reviewable.io -->

2024-07-30 09:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-07-30 14:19 UTC, mkow requested changes
> Reviewed 9 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`common/include/pal_error.h` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1900#-O32vwCVD66logIZR_Jq:-O32vwCVD66logIZR_Jr:b-mbo8vy) ([raw file](https://github.com/gramineproject/gramine/blob/41a53dadb81fec0d59d30746d9d5a37d03306289/common/include/pal_error.h#L10)):*
> ```objc
> #pragma once
> 
> #include <nodiscard.h>
> ```

Should be `"nodiscard.h"` and in a separate include group, because it's our custom header, not a standard one.
I didn't notice it earlier, sorry. It's also a bit separate from this PR, so it's ok if you create another PR to fix it.
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O33-Wve5wuZ7qfceeUq:b-nlggux) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

My private... I was planing to follow up (in days) with it.
</blockquote></details>

Please don't forget :) We'll be merging this now, so the next one could be that.


<!-- Sent from Reviewable.io -->

2024-07-30 15:02 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`common/include/pal_error.h` line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/1900#-O32vwCVD66logIZR_Jq:-O339JXJ9gQdnWZFnMMx:bcgkii6) ([raw file](https://github.com/gramineproject/gramine/blob/41a53dadb81fec0d59d30746d9d5a37d03306289/common/include/pal_error.h#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be `"nodiscard.h"` and in a separate include group, because it's our custom header, not a standard one.
I didn't notice it earlier, sorry. It's also a bit separate from this PR, so it's ok if you create another PR to fix it.
</blockquote></details>

Let's do another one. I don't want to smuggle any changes in such a big PR. 
___
*[`pal/src/host/linux/pal_linux_error.h` line 62 at r3](https://reviewable.io/reviews/gramineproject/gramine/1900#-O0oHLsG0QYPIDk06Zh1:-O339Rk01M0wJkFMursW:bd6wfn4) ([raw file](https://github.com/gramineproject/gramine/blob/6aa16495c6ddb3d832ae1fb6353adf9f7a2c1ebf/pal/src/host/linux/pal_linux_error.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't forget :) We'll be merging this now, so the next one could be that.
</blockquote></details>

I have double checked, still in my TODO :) 


<!-- Sent from Reviewable.io -->

2024-07-30 15:52 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-30 16:14 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-07-31 02:52 UTC, kailun-qin approved these changes
> Reviewed 56 of 76 files at r1, 1 of 2 files at r2, 2 of 3 files at r4, 16 of 17 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1900)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-31 09:10 UTC, merged