[common] Refactor Protected Files, part 6
gramineproject/gramine pull request #1907
Opened 2024-06-12 09:40 UTC by dimakuv

## Description of the changes 

This commit refactors PF code without changing functionality (part 6 in a series of commits). In particular, this commit renames ambiguous `node_number` fields/variables to `physical_node_number` or `logical_node_number`, depending on the context.

This PR supersedes https://github.com/gramineproject/gramine/pull/1894.

## How to test this PR? 

N/A.

2024-06-12 23:59 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1907)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-06-13 00:29 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1907)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1907#-O-Dy9h98XfovJGnb3pH):*
-> ambiguous



_Code quote:_
```
ambigious
```


<!-- Sent from Reviewable.io -->

2024-06-13 06:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1907)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/1907#-O-Dy9h98XfovJGnb3pH):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> ambiguous
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 06:21 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-13 07:06 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-24.04 please ("laggy system")

2024-06-16 21:19 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1907)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-16 21:22 UTC, merged