[common] Refactor Protected Files, part 7
gramineproject/gramine pull request #1908
Opened 2024-06-13 06:56 UTC by dimakuv

## Description of the changes 

This commit refactors PF code without changing functionality (part 7 in a series of commits). In particular, this commit renames:
- "key_id" to a more correct "nonce"
- "encrypted_part_plain" to "metadata_decrypted" (i.e. decrypted conents of the encrypted part of the metadata node)
- "file" to a more specific "host_file_handle"
- "file_metadata" to a more correct "metadata_node"
- "root_mht" to a more specific "root_mht_node"

This PR supersedes https://github.com/gramineproject/gramine/pull/1894.

## How to test this PR? 

N/A.

2024-06-16 22:03 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files_format.h` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-XxdpZ6PBdCjOcZHo3:-O-XxdpZ6PBdCjOcZHo4:bslfpkh) ([raw file](https://github.com/gramineproject/gramine/blob/941a6f8f3ff56d89e5a2f751d005e5b84671e8f3/common/src/protected_files/protected_files_format.h#L57)):*
> ```objc
>     uint8_t    major_version;
>     uint8_t    minor_version;
>     pf_nonce_t metadata_key_nonce;
> ```

Key nonce? Nonce is unrelated to the key itself, it sounds confusing to me. Maybe "cipher_nonce"?
___
*[`common/src/protected_files/protected_files_internal.h` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-Y3cyo5Iy-bgM_YCyG:-O-Y3cyo5Iy-bgM_YCyH:b-4k1dtb) ([raw file](https://github.com/gramineproject/gramine/blob/941a6f8f3ff56d89e5a2f751d005e5b84671e8f3/common/src/protected_files/protected_files_internal.h#L26)):*
> ```objc
> 
>     metadata_node_t metadata_node; // plaintext and encrypted metadata from storage (bounce buffer)
>     metadata_encrypted_t metadata_decrypted; // contains file path, size, etc.
> ```

Maybe `decrypted_metadata`? Sounds more natural. But I can also live with the current version if you don't like the proposal.


<!-- Sent from Reviewable.io -->

2024-06-17 06:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`common/src/protected_files/protected_files_format.h` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-XxdpZ6PBdCjOcZHo3:-O-ZqKMLEZWswh7gC_36:b-my24wc) ([raw file](https://github.com/gramineproject/gramine/blob/941a6f8f3ff56d89e5a2f751d005e5b84671e8f3/common/src/protected_files/protected_files_format.h#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Key nonce? Nonce is unrelated to the key itself, it sounds confusing to me. Maybe "cipher_nonce"?
</blockquote></details>

What I'm trying to convey here is "the nonce with which the key to encrypt the metadata node is derived". I don't think `metadata_cipher_nonce` conveys this message better.

What about one of the following:
- `metadata_nonce` (a bit vague, but simple and uniform with `metadata_gmac`)
- `metadata_nonce_for_key_derivation` (super long but very specific)
- `metadata_nonce_derive` (same as before, but shorter but more cryptic)
___
*[`common/src/protected_files/protected_files_internal.h` line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-Y3cyo5Iy-bgM_YCyG:-O-Zr0wNCUQLt3p6sIia:by0yxpk) ([raw file](https://github.com/gramineproject/gramine/blob/941a6f8f3ff56d89e5a2f751d005e5b84671e8f3/common/src/protected_files/protected_files_internal.h#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe `decrypted_metadata`? Sounds more natural. But I can also live with the current version if you don't like the proposal.
</blockquote></details>

I like the current version better, for two reasons. First, `metadata_decrypted` conveys the meaning better (at least for me): it is the metadata node's contents, but decrypted. Whereas `decrypted_metadata` sounds to me more vague, as "some metadata which was decrypted".

Second, we have `metadata_` prefix to denote everything that relates to the metadata node, not just some other metadata. So I'd like to keep all related-to-metadata-node variables/fields with this prefix.


<!-- Sent from Reviewable.io -->

2024-06-17 09:22 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files_format.h` line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-XxdpZ6PBdCjOcZHo3:-O-_V-SBB4bX7H_SrFB3:b5djm86) ([raw file](https://github.com/gramineproject/gramine/blob/941a6f8f3ff56d89e5a2f751d005e5b84671e8f3/common/src/protected_files/protected_files_format.h#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What I'm trying to convey here is "the nonce with which the key to encrypt the metadata node is derived". I don't think `metadata_cipher_nonce` conveys this message better.

What about one of the following:
- `metadata_nonce` (a bit vague, but simple and uniform with `metadata_gmac`)
- `metadata_nonce_for_key_derivation` (super long but very specific)
- `metadata_nonce_derive` (same as before, but shorter but more cryptic)
</blockquote></details>

Ah, I see. Ok, let's keep the current name then, I don't like the others.


<!-- Sent from Reviewable.io -->

2024-06-17 11:10 UTC, kailun-qin requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-_qC3R5tZB7s7EqCWK):*
-> contents



_Code quote:_
```
conents
```


<!-- Sent from Reviewable.io -->

2024-06-19 06:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/1908#-O-_qC3R5tZB7s7EqCWK):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> contents
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-19 07:00 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-19 08:42 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-22.04 please (very slow node, unrelated)

2024-06-19 09:17 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1908)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-19 14:40 UTC, merged