[common] Refactor Protected Files, part 9
gramineproject/gramine pull request #1919
Opened 2024-06-20 08:58 UTC by dimakuv

## Description of the changes 

This commit refactors PF code without changing functionality (part 9 in a series of commits, last one). In particular, this commit renames:
- ambigious "data" and "cipher" to "bytes", because "data" is already used to denote data file nodes
- "mht_key" and "mht_mac" to "root_mht_node_key" and "root_mht_node_mac"
- "size", "path", "data" to "file_size", "file_path", "file_data"

This PR supersedes https://github.com/gramineproject/gramine/pull/1894. And finally closes this series of refactorings.

## How to test this PR? 

N/A.

2024-06-21 10:52 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-06-22 01:48 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1919#-O-xbpcx0s3vF11HmXH2):*
-> ambiguous



_Code quote:_
```
ambigious
```


<!-- Sent from Reviewable.io -->

2024-06-24 08:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @kailun-qin)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/1919#-O-xbpcx0s3vF11HmXH2):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> ambiguous
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-24 09:19 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-25 00:08 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-25 07:06 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1919)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-25 09:04 UTC, merged