[Docs] Add remote attestation terminology
gramineproject/gramine pull request #1927
Opened 2024-06-27 08:42 UTC by dimakuv

## Description of the changes 

In particular, the terminology follows TCG DICE Attestation.

Extracted from #1039.

## How to test this PR? 

Check the RTD pages: *TBD*

2024-06-28 00:21 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RBYMS-xUEXOC47fg2:-O0RBYMS-xUEXOC47fg3:b-wcl8y4) (no related file):*
TODO for myself: check the rendered final version

___
___
*[`Documentation/sgx-intro.rst` line 193 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0Qz2-a1o0ZPmF3AKs3:-O0Qz2-a1o0ZPmF3AKs4:bqzquiv) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L193)):*
> ```reStructuredText
>    Attestation result
> 
>       The result of appraisal of the :term:`evidence` that was generated by the
> ```

We should IMO use simpler English, so that it's easier to read for more people (as long as the meaning stays the same).



_Suggestion:_
```reStructuredText
The result of evaluation of the :term:`evidence`
```
___
*[`Documentation/sgx-intro.rst` line 195 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R--vm9UxDeBUG_maJ:-O0R--vm9UxDeBUG_maK:b-kbfqqy) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L195)):*
> ```reStructuredText
>       The result of appraisal of the :term:`evidence` that was generated by the
>       :term:`verifier`. The attestation result is typically in the form of a
>       token (e.g., a JSON Web Token), and typically includes information about
> ```

`a token` -> `a signed token` (it is actually signed, right?)
___
*[`Documentation/sgx-intro.rst` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0QzqxzB7PT69rNLJPJ:-O0QzqxzB7PT69rNLJPK:b3d1i4g) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L200)):*
> ```reStructuredText
> 
>       As a particular example, :term:`Intel Attestation Service` generates the
>       attestation result as a custom-formatted JSON report. Other examples
> ```

What does formatting have to do with anything?



_Code quote:_
```reStructuredText
a custom-formatted JSON report
```
___
*[`Documentation/sgx-intro.rst` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R1PPe4FAVaY7Edn85:-O0R1PPe4FAVaY7Edn86:bveij7j) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L207)):*
> The evidence contains claims that prove the attester's integrity

It's not the claims that prove it? It's the hardware signature which is proving the claims.
___
*[`Documentation/sgx-intro.rst` line 212 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R1evHCEGvUQg6plQY:-O0R1evHCEGvUQg6plQZ:bp9moa0) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L212)):*
> ```reStructuredText
>       As a particular example, the attester is the Gramine SGX enclave. It
>       generates the evidence (SGX quote plus additional claims) and sends it to
>       the verifier (e.g., :term:`IAS`).
> ```

Isn't it the verifier, not the enclave, which sends it to IAS?
___
*[`Documentation/sgx-intro.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R2Mep6try4BB7J-_b:-O0R2Mep6try4BB7J-_c:bi7a0n8) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L218)):*
> that has trustworthiness properties

What does this mean?
___
*[`Documentation/sgx-intro.rst` line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R2Dv_1pg2AHKzatXt:-O0R2Dv_1pg2AHKzatXu:b-xn1g8s) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L220)):*
> ```reStructuredText
>       :term:`attester` that has trustworthiness properties, attributes or
>       identifiers that can be included in :term:`evidence`, :term:`endorsement`
>       or :term:`attestation result`.
> ```

Please add an example, e.g. a hash of TEE's initial state.
___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O0R3-KU77YhW9J4gjRj:bj42xa8) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
> ```reStructuredText
>       examples of endorsements are Certificate Revocation Lists (CRLs), minimum
>       allowed TCB date, reference MRENCLAVE/MRSIGNER of the :term:`Quoting
>       Enclave`, etc.
> ```

Am I missing something? I don't see what this list has in common with the meaning of the "endorsement" word in English... I'm really confused by this term and this description didn't help.
___
*[`Documentation/sgx-intro.rst` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R6G__2tD-Blau5tEu:-O0R5y0d8SsTSsTAGfqp:bbnjysw) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L275)):*
> ```reStructuredText
> 
>       In :term:`attestation`, the endorser creates, provisions, or transfers an
>       :term:`endorsement` to the :term:`verifier`.
> ```

So, it's kind of a database of expected TEE attributes? Can you write it more like that, or add an example?
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O0R7MZqDpMQuW8mGmSv:b8ynrsw) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
> ```reStructuredText
>    Attestation evidence
> 
>       Set of claims asserted by an attester about the :term:`Trusted Execution
> ```

That's weird, shouldn't it only cover the signature / proof? The definition doesn't seem to match the meaning of "evidence".



_Code quote:_
```reStructuredText
Set of claims
```
___
*[`Documentation/sgx-intro.rst` line 538 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R9ZzY8GxvPgIDusqj:-O0R9ZzY8GxvPgIDusqk:boytdl) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L538)):*
> ```reStructuredText
>    Relying Party
> 
>       In :term:`attestation`, the relying party accepts the :term:`attestation
> ```

accepts?
___
*[`Documentation/sgx-intro.rst` line 671 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RAD7qDBoYtPjVL3pn:-O0RAD7qDBoYtPjVL3po:bcxzjbu) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L671)):*
> the verifier receives the evidence from the attester

In IAS definition you said that it receives it from the relying party ;)
___
*[`Documentation/sgx-intro.rst` line 673 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RAronBqj9v09o9uSf:-O0RAronBqj9v09o9uSg:b-h01ohn) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L673)):*
> ```reStructuredText
>       the :term:`attester`, as well as the :term:`endorsement` from the
>       :term:`endorser`, and sends the :term:`attestation result` to the
>       :term:`relying party`. The verifier appraises the evidence to determine
> ```

simpler English please, it's already really confusing even without this



_Code quote:_
```reStructuredText
appraises
```
___
*[`Documentation/sgx-intro.rst` line 676 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RB47jCLQvT6y-36Ai:-O0RB47jCLQvT [...]

2024-06-28 09:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/sgx-intro.rst` line 193 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0Qz2-a1o0ZPmF3AKs3:-O0SuxDQBSFSr5haKosK:bnf90cz) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L193)):*
> We should IMO use simpler English

You will not like the TCG DICE Attestation document then :)

Ref: https://trustedcomputinggroup.org/wp-content/uploads/DICE-Attestation-Architecture-Version-1.1-Revision-17_1August2023.pdf
___
*[`Documentation/sgx-intro.rst` line 195 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R--vm9UxDeBUG_maJ:-O0SvJ0I3j5ozda8FraK:bkdhhlv) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a token` -> `a signed token` (it is actually signed, right?)
</blockquote></details>

Done. Yes, of course the token is signed. Any "attestation result" must be signed.
___
*[`Documentation/sgx-intro.rst` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0QzqxzB7PT69rNLJPJ:-O0SvR1I3oCVsutjxsyw:b-l247zk) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does formatting have to do with anything?
</blockquote></details>

Done, removed that phrase. I wanted to contrast that IAS uses its own ad-hoc format for Attestation evidence, whereas more modern MAA and ITA use a standard JWT (developed specifically for such purposes).
___
*[`Documentation/sgx-intro.rst` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R1PPe4FAVaY7Edn85:-O0SxObB-ifxJI920MMB:b-ws5ja5) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The evidence contains claims that prove the attester's integrity

It's not the claims that prove it? It's the hardware signature which is proving the claims.
</blockquote></details>

Done.

Nits: it's not necessarily a "hardware" signature, it's just *some* signature of a party that you trust. I mean, this definition gives a very broad explanation, not tied to Intel SGX or some other hardware TEE.
___
*[`Documentation/sgx-intro.rst` line 212 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R1evHCEGvUQg6plQY:-O0Swq7PE8J6tNd8luVo:byx61l3) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L212)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't it the verifier, not the enclave, which sends it to IAS?
</blockquote></details>

Done.

Yes, I forgot to add more details. Well, now I need to explain the Passport model vs Background check model :(

By the way, a really nice document on Passport vs Background check is found here, with diagrams: https://docs.trustauthority.intel.com/main/articles/concept-patterns.html
___
*[`Documentation/sgx-intro.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R2Mep6try4BB7J-_b:-O0SxruJAYH2eSJV_zEP:b-bjarl6) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L218)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> that has trustworthiness properties

What does this mean?
</blockquote></details>

Done. What about this human-friendly speak?
___
*[`Documentation/sgx-intro.rst` line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R2Dv_1pg2AHKzatXt:-O0Syqdh8VWKrP37Pvyw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L220)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add an example, e.g. a hash of TEE's initial state.
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O0Sz6qd7mVZK_7mcCHo:b6xq3ng) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
From TCG DICE:

> Endorsements are the possible values that the Verifier expects to find in Evidence. Endorsements are obtained from manufacturers, vendors, and other supply chain entities called Endorsers.

I'm not the one who came up with this terminology... I actually think that "Endorsement" comes from the 90s, from the TPM world.

You can think of it like this:
- Attestation evidence is a set of (possibly malicious) claims coming from the TEE
- Attestation endorsement is a set of expected-values claims coming from vendors (e.g., a hash of the Linux kernel coming from Linus Torvalds)
- Claims from attestation evidence are compared against claims in all attestation endorsements, and a new set of claims is generated -- attestation result
___
*[`Documentation/sgx-intro.rst` line 275 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R6G__2tD-Blau5tEu:-O0T0LoSDaRz7NexCgyz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L275)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, it's kind of a database of expected TEE attributes? Can you write it more like that, or add an example?
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O0T0kfE134qxGDq9e11:byxigx5) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's weird, shouldn't it only cover the signature / proof? The definition doesn't seem to match the meaning of "evidence".
</blockquote></details>

Done.

I'm not sure what exactly you meant by the comment, but I added the part about the signature.
___
*[`Documentation/sgx-intro.rst` line 538 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R9ZzY8GxvPgIDusqj:-O0T0z6M77VQeT6XR_yf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L538)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

accepts?
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 671 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RAD7qDBoYtPjVL3pn:-O0T1Sl1AfEHwFdlZCw9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L671)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> the verifier receives the evidence from the attester

In IAS definition you said that it receives it from the relying party ;)
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 673 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RAronBqj9v09o9uSf:-O0T1Tub3uVyUcfmHpGQ [...]

2024-07-01 17:08 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0jFTpiCJ21nMXxxaY9:-O0jFTpiCJ21nMXxxaYA:b80x49m) (no related file):*
@donporter: Would you maybe have some time to go over this, try to understand it and suggest some ways to simplify the descriptions and naming? It was really confusing and non-intuitive to me.

___
___
*[`Documentation/sgx-intro.rst` line 193 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0Qz2-a1o0ZPmF3AKs3:-O0fR5_BC4hVfsRSD7LI:b-7slof2) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L193)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We should IMO use simpler English

You will not like the TCG DICE Attestation document then :)

Ref: https://trustedcomputinggroup.org/wp-content/uploads/DICE-Attestation-Architecture-Version-1.1-Revision-17_1August2023.pdf
</blockquote></details>

I thoroughly enjoyed it.

![dice tcg.jpg](https://files.reviewableusercontent.io/images/reviewable/5244565/NoKtwF0QKKQ0Hi3xX2XeC50P/dice%20tcg.jpeg)
___
*[`Documentation/sgx-intro.rst` line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R2Mep6try4BB7J-_b:-O0fTfWw9c7WBJsXXwMM:b-79vvw3) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. What about this human-friendly speak?
</blockquote></details>

Much better now!
___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O0jBBRCB9gqVbwBYdWj:b-o63o4y) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From TCG DICE:

> Endorsements are the possible values that the Verifier expects to find in Evidence. Endorsements are obtained from manufacturers, vendors, and other supply chain entities called Endorsers.

I'm not the one who came up with this terminology... I actually think that "Endorsement" comes from the 90s, from the TPM world.

You can think of it like this:
- Attestation evidence is a set of (possibly malicious) claims coming from the TEE
- Attestation endorsement is a set of expected-values claims coming from vendors (e.g., a hash of the Linux kernel coming from Linus Torvalds)
- Claims from attestation evidence are compared against claims in all attestation endorsements, and a new set of claims is generated -- attestation result
</blockquote></details>

But why is a "credential" on the list? Doesn't "credentials" in IT context mean authentication data? (e.g. login+password)
I really hate this TCG DICE terminology, it's really confusing and non-intuitive... Could you try to reword this description to make it less TCG-DICE-ey and more understandable?
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O0jCfuR-ViVfR2ZUBTt:b-n6o658) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
Evidence proves claims. But here you say that _claims_ are the evidence, which seems like mistaking a theorem with its proof?

> I'm not sure what exactly you meant by the comment, but I added the part about the signature.

> That's weird, shouldn't it **only** cover the signature / proof?
___
*[`Documentation/sgx-intro.rst` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0fTN7M7GGOQopGLZk_:-O0fTN7M7GGOQopGLZka:b8l5lo3) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L217)):*
> ```reStructuredText
>       generates the evidence (SGX quote plus additional claims) and sends it
>       either directly to the verifier or to the relying party, which then will
>       forward it to the verifier (see :term:`IAS` for more details).
> ```

IAS is EPID-only, right? Does it make sense to link to it here, knowing that it will be deprecated in a few months? The rest of the example doesn't seem to rely on the attestation being EPID.



_Code quote:_
```reStructuredText
(see :term:`IAS` for more details).
```
___
*[`Documentation/sgx-intro.rst` line 310 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0j81jf1K2qdzNy4Whr:-O0j81jf1K2qdzNy4Whs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L310)):*
> ```reStructuredText
> 
>       As a particular example, :term:`Intel Provisioning Certification Service`
>       is the endorser.
> ```





_Suggestion:_
```reStructuredText
is an endorser.
```
___
*[`Documentation/sgx-intro.rst` line 567 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0jE4JS0Fp37Lcx8Yr-:-O0jE4JTCKVih8GASR7S:bnyb7sk) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L567)):*
> ```reStructuredText
>             Intel Attestation Service, another Internet service.
> 
>    Policy
> ```

Please remove it, it's too general without context. Actually, could you do the same for other glossary entries added here which are too generic? (e.g. "claim" - I'd only leave "attestation claim")
___
*[`Documentation/sgx-intro.rst` line 739 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0jFMPvD25vxFRtx5oC:-O0jFMPw00Gme-q9iwLT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L739)):*
> ```reStructuredText
>       determine attester's trustworthiness.
> 
>       As a particular example, :term:`Intel Attestation Service` is the verifier
> ```





_Suggestion:_
```reStructuredText
is a verifier
```


<!-- Sent from Reviewable.io -->

2024-07-02 10:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O0n-7Ed6ul9OVHg4PWn:b4dwkrc) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why is a "credential" on the list? Doesn't "credentials" in IT context mean authentication data? (e.g. login+password)
I really hate this TCG DICE terminology, it's really confusing and non-intuitive... Could you try to reword this description to make it less TCG-DICE-ey and more understandable?
</blockquote></details>

Done, I removed the word "credential" (I copied pasted from TCG DICE).

What else in the description is not understandable? To me, it reads ok.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O0n-IftCUokZJOs1h5o:bta4izz) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
> Evidence proves claims.

Says English dictionary? Unfortunately, TCG DICE has terminology that seems to contradict the English meanings of words. I'm not a native speaker, and I don't know the history of TPMs and TCG DICE well enough to explain what's going on here.

In TCG DICE terminology, these things are pretty clear:
- Attestation claim is a "this property has this value" atom
- Attestation evidence is a set of attestation claims, that describes the attester
- Attester generates this evidence (set of claims) and sends it to other parties

Here are relevant snippets from the TCG DICE Attestation spec:

> The Attesting Environment collects assertions, called Claims, about the trustworthiness properties of the Target Environment. Claims are packaged as Evidence by the Attesting Environment, integrity protected and authenticated. The Attesting Environment may also supply additional claims that attest the freshness and recentness of collected claims

> Evidence is a role message containing assertions, i.e., Claims, from the Attester. Evidence should contain freshness and recentness Claims that help establish Evidence relevance. For example, a Verifier supplies a nonce that can be included with the Evidence supplied by the Attester. Evidence typically describes the state of the device or entity. Normally, Evidence is collected in response to a request, i.e., challenge. Evidence may also describe historical device states, e.g., the state of the Attester during initial boot. It may also describe operational states that are dynamic and likely to change from one request to the next.
___
*[`Documentation/sgx-intro.rst` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0fTN7M7GGOQopGLZk_:-O0mzF-1Ek85m0J-LSsR:bvq8i20) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L217)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IAS is EPID-only, right? Does it make sense to link to it here, knowing that it will be deprecated in a few months? The rest of the example doesn't seem to rely on the attestation being EPID.
</blockquote></details>

Done.

Now I introduced MAA and ITA, and always refer to them first. I still keep IAS around -- we'll remove the mentions in one go, once it's completely removed.
___
*[`Documentation/sgx-intro.rst` line 310 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0j81jf1K2qdzNy4Whr:-O0muX3fByyN9_Y8H3RP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L310)):*
> ```reStructuredText
> 
>       As a particular example, :term:`Intel Provisioning Certification Service`
>       is the endorser.
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 567 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0jE4JS0Fp37Lcx8Yr-:-O0mxHc6C-rHkjQFeHjG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L567)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove it, it's too general without context. Actually, could you do the same for other glossary entries added here which are too generic? (e.g. "claim" - I'd only leave "attestation claim")
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 739 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0jFMPvD25vxFRtx5oC:-O0mvB467JJU9kN54pvI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L739)):*
> ```reStructuredText
>       determine attester's trustworthiness.
> 
>       As a particular example, :term:`Intel Attestation Service` is the verifier
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 21:52 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @donporter)

___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O1OSBjU-74sU5MvCtaV:bl5uk44) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, I removed the word "credential" (I copied pasted from TCG DICE).

What else in the description is not understandable? To me, it reads ok.
</blockquote></details>

See my proposals/questions above.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1OSSjwEEh-EWEOoXRV:b707c2p) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Evidence proves claims.

Says English dictionary? Unfortunately, TCG DICE has terminology that seems to contradict the English meanings of words. I'm not a native speaker, and I don't know the history of TPMs and TCG DICE well enough to explain what's going on here.

In TCG DICE terminology, these things are pretty clear:
- Attestation claim is a "this property has this value" atom
- Attestation evidence is a set of attestation claims, that describes the attester
- Attester generates this evidence (set of claims) and sends it to other parties

Here are relevant snippets from the TCG DICE Attestation spec:

> The Attesting Environment collects assertions, called Claims, about the trustworthiness properties of the Target Environment. Claims are packaged as Evidence by the Attesting Environment, integrity protected and authenticated. The Attesting Environment may also supply additional claims that attest the freshness and recentness of collected claims

> Evidence is a role message containing assertions, i.e., Claims, from the Attester. Evidence should contain freshness and recentness Claims that help establish Evidence relevance. For example, a Verifier supplies a nonce that can be included with the Evidence supplied by the Attester. Evidence typically describes the state of the device or entity. Normally, Evidence is collected in response to a request, i.e., challenge. Evidence may also describe historical device states, e.g., the state of the Attester during initial boot. It may also describe operational states that are dynamic and likely to change from one request to the next.
</blockquote></details>

/summon @donporter

@dimakuv: Do we have to use this term in Gramine? How widespread and "the standard" is TCG DICE? This particular name seems really bad and confusing to me.
___
*[`Documentation/sgx-intro.rst` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0fTN7M7GGOQopGLZk_:-O1NTHMy01KqM6ceE8kV:bdmpf2l) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Now I introduced MAA and ITA, and always refer to them first. I still keep IAS around -- we'll remove the mentions in one go, once it's completely removed.
</blockquote></details>

But in this entry (i.e. the entry for "Attester") the only example is EPID and it doesn't even mention that there are other ways than using IAS. Why not either removing that "(see :term:`IAS` for more details)" or describing a DCAP based scenario? If we keep the current example then we'll need to change it right away.
___
*[`Documentation/sgx-intro.rst` line 230 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OQZhr5rQqSc5Iiheo:-O1OQZhr5rQqSc5Iihep:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L230)):*
> ```reStructuredText
>       As a particular example, an Intel SGX quote (attestation evidence)
>       contains an attestation claim ``MRENCLAVE = <SHA256 hash of initial
>       enclave state>``.  Similarly, an :term:`attestation policy` installed in
> ```





_Suggestion:_
```reStructuredText
``. Similarly
```
___
*[`Documentation/sgx-intro.rst` line 293 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1ORm_A2xTK3E9chRKI:-O1ORm_A2xTK3E9chRKJ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L293)):*
> ```reStructuredText
>    Attestation endorsement
> 
>       A reference value (e.g., expected hash) that authenticates the
> ```





_Suggestion:_
```reStructuredText
describes
```
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS1D21wl3JJbyjrDQ:-O1OS1D21wl3JJbyjrDR:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
> ```reStructuredText
> 
>       A reference value (e.g., expected hash) that authenticates the
>       :term:`attester`'s identity (e.g., device identity certificate). Other
> ```





_Suggestion:_
```reStructuredText
expected :term:`attester`'s identity
```
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS5CJB3vWGA8SXdaC:-O1OS5CJB3vWGA8SXdaD:b-jidxfk) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
> ```reStructuredText
> 
>       A reference value (e.g., expected hash) that authenticates the
>       :term:`attester`'s identity (e.g., device identity certificate). Other
> ```

What is a "device identity certificate"? I never heard this term before.



_Code quote:_
```reStructuredText
(e.g., device identity certificate)
```
___
*[`Documentation/sgx-intro.rst` line 596 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OT3z22He800TzqN90:-O1OT3z22He800TzqN91:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L596)):*
> ```reStructuredText
>       party` that specifies how the :term:`attestation evidence` is evaluated by
>       the :term:`verifier` against :term:`attestation
>       endorsements<endorsement>`.  The attestation policy also specifies the
> ```





_Suggestion:_
```reStructuredText
>`. 
```
___
*[`Documentation/sgx-intro.rst` line 765 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OTP1VCQlkc-ZsDtmi:-O1OTP1VCQlkc-ZsDtmj:budx08z) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L765)):*
> ```reStructuredText
>       As a particular example, :term:`Microsoft Azure Attestation` and
>       :term:`Intel Trust Authority` are verifiers: they evaluate both the
>       hardware and the software trustworthiness. Another example would be
> ```

Only partially I think? They can't know whether a specific version of user software is good or bad.



_Code quote:_
```reStructuredText
the software trustworthiness
```


<!-- Sent from Reviewable.io -->

2024-07-10 06:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter and @mkow)

___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O1QISGSCycxAPickF_z:b-1kocbk) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

See my proposals/questions above.
</blockquote></details>

Done with the proposals above.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1QJOHY4hpjraHH99Gi:be1ia1w) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

/summon @donporter

@dimakuv: Do we have to use this term in Gramine? How widespread and "the standard" is TCG DICE? This particular name seems really bad and confusing to me.
</blockquote></details>

The same terminology is used in another standard called RATS: https://datatracker.ietf.org/doc/rfc9334/

I think at this point the terms are settled by the "attestation" community, and I see no point in inventing our own terminology.
___
*[`Documentation/sgx-intro.rst` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0fTN7M7GGOQopGLZk_:-O1QH_H3960bq0Xe8R6Z:b-wkv0w) ([raw file](https://github.com/gramineproject/gramine/blob/0e40ffd13b5f4018e96ced012ab226e9cc225366/Documentation/sgx-intro.rst#L217)):*
Done, I removed that part.

> describing a DCAP based scenario

I don't like to refer to Intel DCAP because it's not a proper end-user software. DCAP libraries/reference implementations from Intel are only a small part of the stack, and users (datacenter admins, CSPs) are supposed to write their own complete attestation solutions.
___
*[`Documentation/sgx-intro.rst` line 230 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OQZhr5rQqSc5Iiheo:-O1QHyfqBBBNQ18zEyLA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L230)):*
> ```reStructuredText
>       As a particular example, an Intel SGX quote (attestation evidence)
>       contains an attestation claim ``MRENCLAVE = <SHA256 hash of initial
>       enclave state>``.  Similarly, an :term:`attestation policy` installed in
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 293 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1ORm_A2xTK3E9chRKI:-O1QI4VZALButmdObiKV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L293)):*
> ```reStructuredText
>    Attestation endorsement
> 
>       A reference value (e.g., expected hash) that authenticates the
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS1D21wl3JJbyjrDQ:-O1QI6TABjgs2iJTooK1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
> ```reStructuredText
> 
>       A reference value (e.g., expected hash) that authenticates the
>       :term:`attester`'s identity (e.g., device identity certificate). Other
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS5CJB3vWGA8SXdaC:-O1QI6pN3hAUlHfQe7jm:bpfd602) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is a "device identity certificate"? I never heard this term before.
</blockquote></details>

Just removed it, but it's a term used in TCG DICE to refer to certificates issued for each device. Just like DCAP issues certificates for each Intel CPU, just like NVidia issues certificates for each of its GPUs, etc. Is there any other term for this?
___
*[`Documentation/sgx-intro.rst` line 596 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OT3z22He800TzqN90:-O1QIaMm73Rmb8p35CgV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L596)):*
> ```reStructuredText
>       party` that specifies how the :term:`attestation evidence` is evaluated by
>       the :term:`verifier` against :term:`attestation
>       endorsements<endorsement>`.  The attestation policy also specifies the
> ```

Done.
___
*[`Documentation/sgx-intro.rst` line 765 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OTP1VCQlkc-ZsDtmi:-O1QGl_a1GSfdqznX90s:bwuodb8) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L765)):*
> They can't know whether a specific version of user software is good or bad.

What do you mean by this exactly? Both MAA and ITA have the ability to install user-specified policies. The users are supposed to specify "golden values" for the software. So I would consider this "a specific version of user software known to be good". Do you mean something else by your comment?

User specified policies in MAA and ITA:
- https://learn.microsoft.com/en-us/azure/attestation/policy-examples
- https://docs.trustauthority.intel.com/main/articles/concept-policy-v2.html#example-policies


<!-- Sent from Reviewable.io -->

2024-07-10 11:12 UTC, woju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`Documentation/sgx-intro.rst` line 204 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0xHg_4DeElwU_htArK:-O0xHg_4DeElwU_htArL:b-dii362) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L204)):*
> ```reStructuredText
>       Service` generates the attestation result as a JSON report.
> 
>    Attester
> ```

This needs to be defined in term of "the object that we ensure integrity" by the means of attestation. Starting with the story that it's the object that sends "attestation evidence" is going into implementation details.

Also please explain why this stuff is not named "attestee", because AFAIK the common English suffixes are reversed in this case. You can say that CoCo did it this way probably to avoid confusion.

While DICE and CoCoCo "confidential terminology" are authoritative in defining nomenclature, we still can't rely on their wording, we need to explain it to people who are starting with SGX and CoCo in the first place, not for people who are up to date with SIG mailing list.


<!-- Sent from Reviewable.io -->

2024-07-10 15:13 UTC, donporter requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S-mq_4lIz7UFlx32O:-O1S-mq_4lIz7UFlx32P:b-uf75zx) (no related file):*
One higher-level suggestion: maybe group these terms by topic rather than alphabetically?  In the case of attestation, a figure with an example protocol and roles might really help, but I also understand that is more than the original goal of this PR.

___
___
*[`Documentation/glossary.rst` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1RvScz89suo1jQEQQ4:-O1RvSd--7nc9K3wDEBg:bvct9vh) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/glossary.rst#L36)):*
> ```reStructuredText
>       library automatically supports *Interoperable RA-TLS*, a specification
>       that modifies the original RA-TLS format for interoperability between
>       different TEE frameworks. For example, Gramine applications can establish
> ```

Consider reworking: For example, without Interoperable RA-TLS, an application running in Gramine would need to be using the _same_ cryptographic libraries in order to establish a secure connection with an application on a framework such as Occlum or OpenEnclave.  With the addition of Interoperable RA-TLS in version 1.8, applications in Gramine can now establish secure connections to applications in Occlum and OpenEnclave.
___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O1S5BiU7z99TWXnIsDc:bywk0r8) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done with the proposals above.
</blockquote></details>

I think endorsement is a term of art going back to the information flow literature of the 70s.  

Here's my understanding from the literature, which I _think_ is consistent with this DICE document (but help me out if I'm off):

I think the key difference between evidence and endorsement is that endorsement asserts a logical implication from the evidence.  For instance, in code with a machine checkable proof, the proof is the evidence, but the proof checker issues an endorsement that the code satisfies the specification.  

In the context of Gramine, an attestation service might take in evidence such as the firmware version on the CPU and issue an endorsement that it did not include known  exploits X, Y, and Z.

What is more explicit here is that there is a trust relationship on the verifier, who interprets the evidence upon which you are now relying.

Are we on the same page?  If this text is more intuitive, steal any of it y'all are comfortable with.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1S7lSCEqGuNstOcfBS:b-azqthy) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
> Evidence proves claims. But here you say that _claims_ are the evidence, which seems like mistaking a theorem with its proof?

Would 'assertion' be more intuitive?  I think the term 'claim' is trying to capture similar connotation here.  Using 'claim' in the context of, say a signature, implies that one doesn't know the absolute truth of the claim.  If a system is asserting that the hash of the TEE contents is X,  I don't actually know whether that assertion is true in the absolute sense, only whether I trust the person making the assertion (claim).  

In the context of a mathematical proof, in my mind assertions and claims are like lemmas: once they are proved, they are both theorems or can be steps in a chain of implications from an axiom to a different theorem.  

Does this make sense?
___
*[`Documentation/sgx-intro.rst` line 194 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Rz5Oo4qtknZ3Z_-Ui:-O1Rz5Oo4qtknZ3Z_-Uj:bcj68m3) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L194)):*
> ```reStructuredText
> 
>       The result of evaluation of the :term:`attestation evidence` that was
>       generated by the :term:`verifier`. The attestation result is typically in
> ```

It could help to avoid passive voice, and give a bit more context explicitly.  Maybe something like:

In the context of remote attestation, the :term:`verifier` issues an :term:`attestation result` after evaluating the :term:`attestation evidence` issued by the enclave CPU.  The resulting evidence is typically a signed token (e.g., a JSON Web Token)  with a public key signature that the client can check locally.  The specific contents of the result vary by attestation protocol, but typically include...
___
*[`Documentation/sgx-intro.rst` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S09qs9prE7bQabifV:-O1S09qs9prE7bQabifW:bg4bazk) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L206)):*
> ```reStructuredText
>    Attester
> 
>       In :term:`attestation`, the attester transfers the :term:`attestation
> ```

I would just start with a definition of the role, which is apparently poorly defined. :(

Maybe:

In :term:`attestation`, the :term:`attester` collects the :term:`attestation evidence` and relays it to the :term:`verifier` (either directly or indirectly).  The evidence contains ...  Different protocols specify different recipients for the attestation evidence: the :term:`passport model` has the attester present the attestation evidence directly to the verifier, whereas in the :term:`background check model` the evidence is given to the :term:`relying party`, which then forwards the attestation evidence to the verifier.
___
*[`Documentation/sgx-intro.rst` line 214 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S172TE9gAXrxzw-HZ:-O1S172TE9gAXrxzw-H_:b-rpjajg) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L214)):*
> ```reStructuredText
>       trustworthiness, as well as the signature that proves the claims.
> 
>       As a particular example, the attester is the Gramine SGX enclave. It
> ```

Rather than giving an example, I would explicitly map these terms onto the Gramine architecture.   For instance:

In Gramine, the Gramine SGX enclave serves the role of attester.  The enclave generates...
___
*[`Documentation/sgx-intro.rst` line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S2KKU9-wTKVE-3Jp6:-O1S2KKU9-wTKVE-3Jp7:b-bxjmv0) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L222)):*
> ```reStructuredText
> 
>       In :term:`attestation`, the attestation claim is a machine-readable
>       assertion about an :term:`attester` that describes security-relevant
> ```

, which
___
*[`Documentation/sgx-intro.rst` line 225 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S2ZG02G6PjdMZScq8:-O1S2ZG02G6PjdMZScq9:b7csz3d) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L225)):*
> ```reStructuredText
>       properties, attributes or identifiers that can be included in
>       :term:`attestation evidence`, :term:`attestation endorsement`  [...]

2024-07-10 17:32 UTC, donporter requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/sgx-intro.rst` line 765 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OTP1VCQlkc-ZsDtmi:-O1Sfax84xUpqub0S9mh:b-z2u5ov) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L765)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> They can't know whether a specific version of user software is good or bad.

What do you mean by this exactly? Both MAA and ITA have the ability to install user-specified policies. The users are supposed to specify "golden values" for the software. So I would consider this "a specific version of user software known to be good". Do you mean something else by your comment?

User specified policies in MAA and ITA:
- https://learn.microsoft.com/en-us/azure/attestation/policy-examples
- https://docs.trustauthority.intel.com/main/articles/concept-policy-v2.html#example-policies
</blockquote></details>

My reading of the DICE document is that the verifier's job is to determine whether the evidence is convincing, such as whether a signature could have been generated by a given key.  As a potentially separate step, the relying party takes the evidence that passes verification and applies a policy to decide whether to trust the hardware/software.

I would avoid the phrase "determines trustworthiness", since this is really more of an implicit concept, and rarely absolute.  You never really know for certain the other endpoint is trustworthy (or a meaningful risk percentage); you have some evidence and you decide to either trust it or not, based on your assessment of the evidence at hand. 

Are we on the same page?
___
*[`Documentation/sgx-intro.rst` line 622 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Sc1vWDweRua8AZt_l:-O1Sc1vWDweRua8AZt_m:bk4z5yw) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L622)):*
> ```reStructuredText
> 
>       In :term:`attestation`, the relying party receives the :term:`attestation
>       result` from the :term:`verifier`. The relying party typically manages
> ```

This sentence is a bit convoluted.  Maybe something like this (what I might say when teaching this to newbies):

In Gramine's use of attestation, the relying party is typically the end-user's client that trusts a separate attestation service.  In the literature, the term is more general, and applies to any system that trusts a verifier.

In a typical execution flow, the relying party might send a TEE an encrypted input, and after receiving attestation results from the verifier, the relying party may then decide to trust the TEE and offer access to the input data by sending a decryption key to the TEE.  

Another term for relying party ...
___
*[`Documentation/sgx-intro.rst` line 753 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Sei74EskjlbGmYLlc:-O1Sei74EskjlbGmYLld:bfpwioh) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L753)):*
> ```reStructuredText
>    Verifier
> 
>       In :term:`attestation`, the verifier receives the :term:`attestation
> ```

I would flip the order of these concepts - say what the verifier does first, then explain how the input is routed to the verifier (or just give a link to the relevant term).
___
*[`Documentation/sgx-intro.rst` line 763 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1SexulDNX9-fGalXPX:-O1SexulDNX9-fGalXPY:b67m744) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L763)):*
> ```reStructuredText
>       As a particular example, :term:`Microsoft Azure Attestation` and
>       :term:`Intel Trust Authority` are verifiers: they evaluate both the
>       hardware and the software trustworthiness. Another example would be
> ```

suggestions: ...evaluate ...trustworthiness based on evidence reported by the CPU or architectural enclaves, such as the version of the firmware on the system or a cryptographically signed report that the CPU was made by a given vendor.


<!-- Sent from Reviewable.io -->

2024-07-11 08:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S-mq_4lIz7UFlx32O:-O1ViRtp9Y4IHCTmcIrx:brtsyxc) (no related file):*
> One higher-level suggestion: maybe group these terms by topic rather than alphabetically?

That's a glossary, so I think topics must be ordered alphabetically.

> In the case of attestation, a figure with an example protocol and roles might really help, but I also understand that is more than the original goal of this PR.

I'm losing the point of what we're doing. The original ask from @mkow was to add explanations to some terminology used in Microsoft Azure Attestation and Intel Trust Authority plug-ins to our glossary in the documentation. There's a lot of documentation on MAA and ITA, as well as documentation on attestation generally, so my preferred way would be to point to that documentation.

___
___
*[`Documentation/glossary.rst` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1RvScz89suo1jQEQQ4:-O1Vk8Hb7rxR5eTp8vSM:b6o3x7o) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/glossary.rst#L36)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Consider reworking: For example, without Interoperable RA-TLS, an application running in Gramine would need to be using the _same_ cryptographic libraries in order to establish a secure connection with an application on a framework such as Occlum or OpenEnclave.  With the addition of Interoperable RA-TLS in version 1.8, applications in Gramine can now establish secure connections to applications in Occlum and OpenEnclave.
</blockquote></details>

Sorry, this suggestion doesn't make sense to me:
- What do you mean by "using the same cryptographic libraries"? The only library that we care about is the RA-TLS library, and this one is tightly integrated with Gramine, and has its own ad-hoc format for the embedded SGX Quote. There is **no ability** to inter-operate with Occlum or OpenEnclave currently: RA-TLS lib cannot be used with Occlum or OpenEnclave because of its tight integration to Gramine internals, and Occlum's or OpenEnclave's similar libraries cannot communicate with Gramine's RA-TLS because the formats are different.
- If you meant e.g. OpenSSL or mbedTLS or WolfSSL by "same cryptographic libraries", then no, this is wrong. The problem of interoperability is not at the level of crypto, but at the level of how X.509 certificates are generated and how they embed the SGX Quote.

So currently I'll keep the text as is.
___
*[`Documentation/sgx-intro.rst` line 270 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R3-KU77YhW9J4gjRi:-O1VtqN8-1M2hqs4wZcN:b-jm00f9) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L270)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I think endorsement is a term of art going back to the information flow literature of the 70s.  

Here's my understanding from the literature, which I _think_ is consistent with this DICE document (but help me out if I'm off):

I think the key difference between evidence and endorsement is that endorsement asserts a logical implication from the evidence.  For instance, in code with a machine checkable proof, the proof is the evidence, but the proof checker issues an endorsement that the code satisfies the specification.  

In the context of Gramine, an attestation service might take in evidence such as the firmware version on the CPU and issue an endorsement that it did not include known  exploits X, Y, and Z.

What is more explicit here is that there is a trust relationship on the verifier, who interprets the evidence upon which you are now relying.

Are we on the same page?  If this text is more intuitive, steal any of it y'all are comfortable with.
</blockquote></details>

Done. I used some other definitions (mostly taken from https://datatracker.ietf.org/doc/rfc9334/), but Don is right (and my initial description of Endorsements was off).
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1VuArSDNtvhsE-Qi5x:bojidyf) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

> Evidence proves claims. But here you say that _claims_ are the evidence, which seems like mistaking a theorem with its proof?

Would 'assertion' be more intuitive?  I think the term 'claim' is trying to capture similar connotation here.  Using 'claim' in the context of, say a signature, implies that one doesn't know the absolute truth of the claim.  If a system is asserting that the hash of the TEE contents is X,  I don't actually know whether that assertion is true in the absolute sense, only whether I trust the person making the assertion (claim).  

In the context of a mathematical proof, in my mind assertions and claims are like lemmas: once they are proved, they are both theorems or can be steps in a chain of implications from an axiom to a different theorem.  

Does this make sense?
</blockquote></details>

From Don's description, I still like to keep using "claims".
___
*[`Documentation/sgx-intro.rst` line 204 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0xHg_4DeElwU_htArK:-O1VnVxR9arUWmzQPf6l:bme4k77) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L204)):*
> This needs to be defined in term of "the object that we ensure integrity" by the means of attestation. Starting with the story that it's the object that sends "attestation evidence" is going into implementation details.

Done, hopefully good enough.

> Also please explain why this stuff is not named "attestee", because AFAIK the common English suffixes are reversed in this case. You can say that CoCo did it this way probably to avoid confusion.

Googling for "attestee dictionary" gives me no results. I don't think "attestee" is a real word? It's used by some blogs/papers, but I don't believe it to be a real word.

"Attester" has a reasonable meaning: One who attests, i.e., to certify by signature or oath. See https://en.wiktionary.org/wiki/attester. So, "attester" is the entity that certifies smth (its own properties). So I like "attester".
___
*[`Documentation/sgx-intro.rst` line 765 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OTP1VCQlkc-ZsDtmi:-O1VwpYBCuOq0bkyO566:b-cz25ni) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L765)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

My reading of the DICE document is that the verifier's job is to determine whether the evidence is convincing, such as whether a signature could have been generated by a given key.  As a potentially separate step, the relying party takes the evidence that passes verification and applies a policy to decide whether to trust the hardware/software.

I would avoid the phrase "determines trustworthiness", since this is really more of an implicit concept, and rarely absolute.  You never really know for certain the other endpoint is trustworthy (or a meaningful risk percentage); you have some evidence and you decide to either trust it or not, based on your assessment of the evid [...]

2024-07-11 09:16 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`Documentation/sgx-intro.rst` line 204 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0xHg_4DeElwU_htArK:-O1W3pXN1Segwc8kzU29:brkdvxs) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This needs to be defined in term of "the object that we ensure integrity" by the means of attestation. Starting with the story that it's the object that sends "attestation evidence" is going into implementation details.

Done, hopefully good enough.

> Also please explain why this stuff is not named "attestee", because AFAIK the common English suffixes are reversed in this case. You can say that CoCo did it this way probably to avoid confusion.

Googling for "attestee dictionary" gives me no results. I don't think "attestee" is a real word? It's used by some blogs/papers, but I don't believe it to be a real word.

"Attester" has a reasonable meaning: One who attests, i.e., to certify by signature or oath. See https://en.wiktionary.org/wiki/attester. So, "attester" is the entity that certifies smth (its own properties). So I like "attester".
</blockquote></details>

Good enough for me, thanks.
___
*[`Documentation/sgx-intro.rst` line 256 at r5](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1W3QuSCRtm2I7wF50b:-O1W3QuSCRtm2I7wF50c:bn8d260) ([raw file](https://github.com/gramineproject/gramine/blob/3ccc825f795eb57c5bf9de9ed276279a3f0ae858/Documentation/sgx-intro.rst#L256)):*
> ```reStructuredText
> 
>       :term:`Attestation` protocols can be grouped by which party the
>       :term:`attester` relays :term:`attestation evidence` from the TEE to; in
> ```

<code>:term:\`TEE\`</code>


<!-- Sent from Reviewable.io -->

2024-07-11 10:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, and @woju)

___
*[`Documentation/sgx-intro.rst` line 256 at r5](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1W3QuSCRtm2I7wF50b:-O1WHDBZEq9ZBtHP9oG6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3ccc825f795eb57c5bf9de9ed276279a3f0ae858/Documentation/sgx-intro.rst#L256)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

<code>:term:\`TEE\`</code>
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-11 18:07 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S-mq_4lIz7UFlx32O:-O1XNiTA4Cg6HrfRpcLu:b-rv6416) (no related file):*
> That's a glossary, so I think topics must be ordered alphabetically.

I agree. If we'd like to split this into categories, then I'd create separate pages for each and sort inside each ("sub-glossaries").

> I'm losing the point of what we're doing. The original ask from [@mkow](https://github.com/mkow) was to add explanations to some terminology used in Microsoft Azure Attestation and Intel Trust Authority plug-ins to our glossary in the documentation. There's a lot of documentation on MAA and ITA, as well as documentation on attestation generally, so my preferred way would be to point to that documentation.

+1

___
___
*[`Documentation/glossary.rst` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1RvScz89suo1jQEQQ4:-O1XXIYv-UElQ2iMtGkS:b-k88y9g) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/glossary.rst#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, this suggestion doesn't make sense to me:
- What do you mean by "using the same cryptographic libraries"? The only library that we care about is the RA-TLS library, and this one is tightly integrated with Gramine, and has its own ad-hoc format for the embedded SGX Quote. There is **no ability** to inter-operate with Occlum or OpenEnclave currently: RA-TLS lib cannot be used with Occlum or OpenEnclave because of its tight integration to Gramine internals, and Occlum's or OpenEnclave's similar libraries cannot communicate with Gramine's RA-TLS because the formats are different.
- If you meant e.g. OpenSSL or mbedTLS or WolfSSL by "same cryptographic libraries", then no, this is wrong. The problem of interoperability is not at the level of crypto, but at the level of how X.509 certificates are generated and how they embed the SGX Quote.

So currently I'll keep the text as is.
</blockquote></details>

+1 to what Dmitrii said, the difference is on a different level (and crypto libraries actually _can_ be substituted in the current RA-TLS).
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1XvC2r-kMPCSkT1WbE:bjtkkmb) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From Don's description, I still like to keep using "claims".
</blockquote></details>

I don't have a problem with "claim", but with "evidence" used as a synonym of "claim". I don't know if I'm missing either some understanding or English meaning / possible connotations of "evidence", but it seems like here it's used with a very different meaning than the one I know.
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS5CJB3vWGA8SXdaC:-O1XrOi73EPHkrweJ4JD:b-50jpqt) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just removed it, but it's a term used in TCG DICE to refer to certificates issued for each device. Just like DCAP issues certificates for each Intel CPU, just like NVidia issues certificates for each of its GPUs, etc. Is there any other term for this?
</blockquote></details>

What is this certificate, exactly? I know what's a certificate in the context of TLS, but it doesn't seem to mean something analogous here.
___
*[`Documentation/sgx-intro.rst` line 765 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OTP1VCQlkc-ZsDtmi:-O1XwrV6ATBQy1m_Ev3X:b-o60tgs) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L765)):*
> Both MAA and ITA have the ability to install user-specified policies.

Ah, I thought they are evaluated by the user.
___
*[`Documentation/sgx-intro.rst` line 196 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1XoALzDBhjSKZJQHcV:-O1XoALzDBhjSKZJQHcW:bdw83ri) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L196)):*
> ```reStructuredText
>       attestation result after evaluating the :term:`attestation evidence`
>       issued by the :term:`TEE`. The resulting evidence is typically a signed
>       token (e.g., a JSON Web Token)  with a public key signature that the
> ```

ditto for the whole PR, you add these doublespaces all the time ;)



_Suggestion:_
```reStructuredText
Token) with
```
___
*[`Documentation/sgx-intro.rst` line 315 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xtt5XEiOnHIkxtTUq:-O1Xtt5XEiOnHIkxtTUr:b-klfzow) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L315)):*
> ```reStructuredText
>       :term:`attester`'s various capabilities. Endorsements might describe the
>       ways in which the attester resists attacks, protects secrets, and measures
>       Target Environments. One example of an endorsement is a manufacturer
> ```

Why is this capitalized?



_Code quote:_
```reStructuredText
Target Environments
```
___
*[`Documentation/sgx-intro.rst` line 317 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xu3OP3yLIWxirupUZ:-O1Xu3OP3yLIWxirupU_:b-condqz) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L317)):*
> Target Environments. One example of an endorsement is a manufacturer certificate that signs a public key whose corresponding private key is only known inside the device's hardware.

Does this ever happens in any TEE? In SGX the public keys for the hardware private keys are AFAIR not known publicly.
___
*[`Documentation/sgx-intro.rst` line 801 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xw_IzAdecmkdEz_LP:-O1Xw_IzAdecmkdEz_LQ:b-hjqtwo) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L801)):*
> ```reStructuredText
>       check model` has the attester transfer the evidence to the :term:`relying
>       party` which then forwards it to the :term:`verifier` for verification
>       (the relying party performs a "background check" on the attester).
> ```

We have these flows (background-check vs passport) already described in the relevant entries, they don't seem too relevant here?


<!-- Sent from Reviewable.io -->

2024-07-15 09:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S-mq_4lIz7UFlx32O:-O1piUy-1oYCh5wLe7VP:b-7a6rg2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> That's a glossary, so I think topics must be ordered alphabetically.

I agree. If we'd like to split this into categories, then I'd create separate pages for each and sort inside each ("sub-glossaries").

> I'm losing the point of what we're doing. The original ask from [@mkow](https://github.com/mkow) was to add explanations to some terminology used in Microsoft Azure Attestation and Intel Trust Authority plug-ins to our glossary in the documentation. There's a lot of documentation on MAA and ITA, as well as documentation on attestation generally, so my preferred way would be to point to that documentation.

+1
</blockquote></details>

Done from my side (in the sense, nothing to be done)

___
___
*[`Documentation/glossary.rst` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1RvScz89suo1jQEQQ4:-O1pieLj3kNjPA3b-0iw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/glossary.rst#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to what Dmitrii said, the difference is on a different level (and crypto libraries actually _can_ be substituted in the current RA-TLS).
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1pn5oG58WJGniOO1A3:b4jv6dn) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't have a problem with "claim", but with "evidence" used as a synonym of "claim". I don't know if I'm missing either some understanding or English meaning / possible connotations of "evidence", but it seems like here it's used with a very different meaning than the one I know.
</blockquote></details>

I don't know what my next action should be now. Any idea how to move forward? @mkow 
___
*[`Documentation/sgx-intro.rst` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1OS5CJB3vWGA8SXdaC:-O1pmijUDzsUz_dmv1vS:bmzb7y2) ([raw file](https://github.com/gramineproject/gramine/blob/d8663101b6cbbebe31a4cbcdf9ea7952ca55bd97/Documentation/sgx-intro.rst#L294)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is this certificate, exactly? I know what's a certificate in the context of TLS, but it doesn't seem to mean something analogous here.
</blockquote></details>

At least for Intel, there is an Intel Provisioning Certification Service: https://api.portal.trustedservices.intel.com/provisioning-certification. You can see that it talks about normal X.509 certificates.

You can skim through this official docs: https://api.trustedservices.intel.com/documents/Intel_SGX_PCK_Certificate_CRL_Spec-1.5.pdf. It contains enough details to assure you that these are the classic X.509 certificate chains (with some SGX magic values sprinkled around). The same applies to Intel TDX afaik.
___
*[`Documentation/sgx-intro.rst` line 196 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1XoALzDBhjSKZJQHcV:-O1pkXxU7q65rFof61LB:bl396bq) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for the whole PR, you add these doublespaces all the time ;)
</blockquote></details>

Done. That's Vim auto-indent, and I still didn't master how to instruct vim not to do this...
___
*[`Documentation/sgx-intro.rst` line 315 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xtt5XEiOnHIkxtTUq:-O1plP23B2c5gKDd_pRN:btpspo) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L315)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this capitalized?
</blockquote></details>

Done. Oops, I wanted to say Trusted Execution Environment.
___
*[`Documentation/sgx-intro.rst` line 317 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xu3OP3yLIWxirupUZ:-O1plUX3BNTK0TeAHDfv:b-ufdqd6) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Target Environments. One example of an endorsement is a manufacturer certificate that signs a public key whose corresponding private key is only known inside the device's hardware.

Does this ever happens in any TEE? In SGX the public keys for the hardware private keys are AFAIR not known publicly.
</blockquote></details>

Well, yes, the reality is more like there's a special protocol (provisioning) in Intel SGX/TDX, where the new platform first talks to a special Intel service, and by <some magic> the Intel service produces the certificate that proves the identity/genuineness of this device.
___
*[`Documentation/sgx-intro.rst` line 801 at r6](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1Xw_IzAdecmkdEz_LP:-O1plFSk0lMhhysG-8K_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47e686f611b4449a8700fe62cb9a8ddf323be98e/Documentation/sgx-intro.rst#L801)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We have these flows (background-check vs passport) already described in the relevant entries, they don't seem too relevant here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-16 07:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 0 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, and @woju)

___
*[`Documentation/glossary.rst` line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1RvScz89suo1jQEQQ4:-O1uKGA07isvPO3gptWt:b-w2tv4b) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/glossary.rst#L36)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

My suggestion is really to unpack what the first sentence means by "not interoperable", perhaps with an example.  My attempts to do this are incorrect -- that is fine.  So add a sentence showing what this incompatibility means in a practical sense.  

My secondary suggestion is to make this positive.  Start with the feature Gramine does have, and then talk about the deficiency in older versions.
</blockquote></details>

Done. Reformulated.
___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1uMA5ZCF4IUH0IPXF-:b-xlq9ms) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
Again, we seem to be discussing Common English Meanings vs TCG DICE/RATS Standards Meanings. To quote TCG DICE:

> Claims are packaged as Evidence by the Attesting Environment, integrity protected and authenticated.

I think this sentence captures very well that Evidence is a set of Claims. That's not exactly "equivalent terms", but the evidence is just a bunch of claims collected together and hashed/signed. Evidence is a struct, Claims are struct fields.

While I agree that in Common English the meaning is different (evidence are atoms that prove/support claims), but in the language of the TCG DICE and RATS standards it's the other meaning. The question is: do we want to follow the TCG DICE meaning? My answer is *yes*, because that was the original purpose of this PR and the original ask: while working on the MAA and ITA plugins for RA-TLS, @mkow wanted to learn the terminology used by these frameworks.

I added a sentence now that this meaning may differ from "conversational English", but that we stick to the TCG DICE definitions for the sake of standard conformity. 
___
*[`Documentation/sgx-intro.rst` line 306 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S6fTG4lafDzmcvb07:-O1uKdWh1yZRubOpxAiX:btiey4e) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L306)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I suppose just because it might be easier to explain both terms together than separately.  But feel free not to take this one.
</blockquote></details>

Yes, I understand the motivation, but on the other hand it's a glossary, it's not a "description" document. We want to list all the terms separately.
___
*[`Documentation/sgx-intro.rst` line 200 at r7](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1qpk_a3MtaFK_Z2ndN:-O1uKXqHEqFicT0NT3rx:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/7354d808c6354e7547366a2ea52ccb25c2d48f12/Documentation/sgx-intro.rst#L200)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Nit: You don't need "such as" and "etc".  Choose one - I recommend "such as"
</blockquote></details>

Done
___
*[`Documentation/sgx-intro.rst` line 772 at r7](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1quhh-3tL4UHOg-BAE:-O1uOklV0MLoTyMdG-j7:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/7354d808c6354e7547366a2ea52ccb25c2d48f12/Documentation/sgx-intro.rst#L772)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we want to link to this term or the organization for the interested reader?  Or let them use google like the rest of us :)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-16 14:17 UTC, donporter requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1vtQQY58XY8zv_WTwW:b2msv7) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Again, we seem to be discussing Common English Meanings vs TCG DICE/RATS Standards Meanings. To quote TCG DICE:

> Claims are packaged as Evidence by the Attesting Environment, integrity protected and authenticated.

I think this sentence captures very well that Evidence is a set of Claims. That's not exactly "equivalent terms", but the evidence is just a bunch of claims collected together and hashed/signed. Evidence is a struct, Claims are struct fields.

While I agree that in Common English the meaning is different (evidence are atoms that prove/support claims), but in the language of the TCG DICE and RATS standards it's the other meaning. The question is: do we want to follow the TCG DICE meaning? My answer is *yes*, because that was the original purpose of this PR and the original ask: while working on the MAA and ITA plugins for RA-TLS, @mkow wanted to learn the terminology used by these frameworks.

I added a sentence now that this meaning may differ from "conversational English", but that we stick to the TCG DICE definitions for the sake of standard conformity.
</blockquote></details>

Maybe add a clarifying sentence like: In the TCG DICE nomenclature, the distinction between evidence and claims is that evidence is a set of signed claims.

I'm fine with using this nomenclature.  Repeating this clarification confirms to the reader that they understand this relationship correctly.
___
*[`Documentation/sgx-intro.rst` line 206 at r4](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1S09qs9prE7bQabifV:-O1vrTddEMrm0sHvTdjW:bb9tmwe) ([raw file](https://github.com/gramineproject/gramine/blob/ec4b206ace5b02702c362e597b8413db254a8db3/Documentation/sgx-intro.rst#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you commit?  I don't see any edits.


<!-- Sent from Reviewable.io -->

2024-07-16 22:45 UTC, mkow requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @woju)

___
*[`Documentation/sgx-intro.rst` line 334 at r1](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0R7MZp0TSpZqiGWg5E:-O1xhwxi3ezlgVYRHzqV:b-6d3ipy) ([raw file](https://github.com/gramineproject/gramine/blob/df82737e3f005165b72112aa906ade57cb7f921a/Documentation/sgx-intro.rst#L334)):*
> Maybe add a clarifying sentence like: In the TCG DICE nomenclature, the distinction between evidence and claims is that evidence is a set of signed claims.

+1


<!-- Sent from Reviewable.io -->

2024-07-17 14:49 UTC, donporter submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2024-07-18 12:47 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1927#-O0RBYMS-xUEXOC47fg2:-O24sT0f5FxYBH4vFoL-:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: check the rendered final version
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-07-19 02:27 UTC, kailun-qin requested changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`Documentation/glossary.rst` line 33 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27XGvf2w2V_5O755lJ:-O27XGvg2cwOds1kENyN:b55fgnt) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/glossary.rst#L33)):*
> ```reStructuredText
> 
>       Starting from v1.8, Gramine's RA-TLS library supports *Interoperable
>       RA-TLS*, a specification that modifies the original RA-TLS format for
> ```

Should we put a link to the specifications here, e.g., https://github.com/CCC-Attestation/interoperable-ra-tls/tree/main/docs?



_Code quote:_
```reStructuredText
      Starting from v1.8, Gramine's RA-TLS library supports *Interoperable
      RA-TLS*, a specification that modifies the original RA-TLS format for
```
___
*[`Documentation/sgx-intro.rst` line 231 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27l0Cf-2sJv0J93PAF:-O27l0Cf-2sJv0J93PAG:bn0r2et) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L231)):*
> ```reStructuredText
>       security-relevant properties, attributes or identifiers that can be
>       included in :term:`attestation evidence`, :term:`attestation endorsement`
>       or :term:`attestation result`.
> ```

what about attestation policies?



_Code quote:_
```reStructuredText
      included in :term:`attestation evidence`, :term:`attestation endorsement`
      or :term:`attestation result`.
```
___
*[`Documentation/sgx-intro.rst` line 302 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27YcyFBTOn6yvz3Ihi:-O27YcyFBTOn6yvz3Ihj:ba1ac4n) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L302)):*
> ```reStructuredText
>       changing memory permissions and type.
> 
>    Attestation endorsement
> ```

I think (most of) these terms are basically formalized (though slightly differently) in [IETF RATS (RFC 9334)](https://datatracker.ietf.org/doc/html/rfc9334) (well, we are disucssing the flow of RATS in some sense), maybe we want to put a link somewhere?



_Code quote:_
```reStructuredText
   Attestation endorsement
```
___
*[`Documentation/sgx-intro.rst` line 774 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27_u0z3jOp6eV4oCYj:-O27_u0z3jOp6eV4oCYk:b-4742a) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L774)):*
> ```reStructuredText
> 
>       TCG DICE is an industry standard developed by the Trusted Computing Group
>       organization. The DICE standard (ppreviously called RIoT) mandates
> ```

-> previously



_Code quote:_
```reStructuredText
ppreviously
```
___
*[`Documentation/sgx-intro.rst` line 806 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27cMlOAcco9h14IhS6:-O27cMlP9VnmqBS71dzv:bledtc7) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L806)):*
> ```reStructuredText
>       a given vendor. Another example would be :term:`Intel Attestation
>       Service`, though it only evaluates that the hardware is genuine and
>       up-to-date.
> ```

1. Is this true? Platform TCB would also contain architectural enclaves?
2. Should we mention the plan of EOL: https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/resources/sgx-ias-using-epid-eol-timeline.html?



_Code quote:_
```reStructuredText
      Service`, though it only evaluates that the hardware is genuine and
      up-to-date.
```


<!-- Sent from Reviewable.io -->

2024-07-22 06:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 0 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, @mkow, and @woju)

___
*[`Documentation/glossary.rst` line 33 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27XGvf2w2V_5O755lJ:-O2O6UsO7Pul0keJGME1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/glossary.rst#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should we put a link to the specifications here, e.g., https://github.com/CCC-Attestation/interoperable-ra-tls/tree/main/docs?
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 231 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27l0Cf-2sJv0J93PAF:-O2O6pmj5G36t7TWjZ-V:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L231)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

what about attestation policies?
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 302 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27YcyFBTOn6yvz3Ihi:-O2O7WT_63RyS14H6f1e:b-cj17db) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L302)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I think (most of) these terms are basically formalized (though slightly differently) in [IETF RATS (RFC 9334)](https://datatracker.ietf.org/doc/html/rfc9334) (well, we are disucssing the flow of RATS in some sense), maybe we want to put a link somewhere?
</blockquote></details>

Done. Wasn't sure where to add this link (I don't want to mention two standards all the time), so added a "see also" note under TCG DICE
___
*[`Documentation/sgx-intro.rst` line 774 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27_u0z3jOp6eV4oCYj:-O2O7Fp4EkTr6zyvoZj5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L774)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> previously
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 806 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27cMlOAcco9h14IhS6:-O2O7miFB29kc5bjSA5I:by3jbrs) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L806)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

1. Is this true? Platform TCB would also contain architectural enclaves?
2. Should we mention the plan of EOL: https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/resources/sgx-ias-using-epid-eol-timeline.html?
</blockquote></details>

Done. To avoid confusion, I simply removed the IAS mention.


<!-- Sent from Reviewable.io -->

2024-07-22 08:06 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`Documentation/sgx-intro.rst` line 806 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27cMlOAcco9h14IhS6:-O2OTE1GAKjcghg45vgP:b-imscvy) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L806)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. To avoid confusion, I simply removed the IAS mention.
</blockquote></details>

We have similar descriptions here: https://github.com/gramineproject/gramine/blob/fb7c676651538aeb60af6822cfdf63a626ed0c79/Documentation/sgx-intro.rst?plain=1#L628-L631, do we want to also remove this?


<!-- Sent from Reviewable.io -->

2024-07-22 13:01 UTC, donporter approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2024-07-22 17:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @donporter, @kailun-qin, and @woju)

___
*[`Documentation/sgx-intro.rst` line 806 at r9](https://reviewable.io/reviews/gramineproject/gramine/1927#-O27cMlOAcco9h14IhS6:-O2QR6dRBbW4wNY0MYPk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6e7f0f3e3c4dde876ff40199518a059abc19ba0e/Documentation/sgx-intro.rst#L806)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We have similar descriptions here: https://github.com/gramineproject/gramine/blob/fb7c676651538aeb60af6822cfdf63a626ed0c79/Documentation/sgx-intro.rst?plain=1#L628-L631, do we want to also remove this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 01:11 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-07-23 12:36 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-07-23 12:56 UTC, dimakuv reviewed
> Dismissed @woju from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Documentation/sgx-intro.rst` line 256 at r5](https://reviewable.io/reviews/gramineproject/gramine/1927#-O1W3QuSCRtm2I7wF50b:-O2UeKpXATROJNwnP9sC:b-k0oxo0) ([raw file](https://github.com/gramineproject/gramine/blob/3ccc825f795eb57c5bf9de9ed276279a3f0ae858/Documentation/sgx-intro.rst#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Dismissing @woju from this discussion as he is currently unavailable and he allowed to dismiss him in a private conversation.


<!-- Sent from Reviewable.io -->

2024-07-23 13:41 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-23 14:06 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1927)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-23 17:59 UTC, merged