[common] Update UBSan to be compatible with Clang 18
gramineproject/gramine pull request #1929
Opened 2024-06-27 12:41 UTC by dimakuv

## Description of the changes 

Newer Clang versions added more UBSan checks, in particular:
- `-fsanitize=pointer-overflow` check was extended to catch the cases where a non-zero offset is applied to a null pointer, or the result of applying the offset is a null pointer.
- `fsanitize=function`: Indirect call of a function through a function pointer of the wrong type.

This commit adds the scaffolding for the second (new) check plus fixes the places triggered by this check. This commit also fixes UBs found by the extended first check.

See:
- https://github.com/llvm/llvm-project/blob/1462605ab0a121fc2f652f178c7c13dc0179f10e/compiler-rt/lib/ubsan/ubsan_handlers.cpp#L925-L958
- https://github.com/llvm/llvm-project/blob/b579aacc30bc02e8430c0b59af644f52ece71160/compiler-rt/lib/ubsan/ubsan_handlers.h#L235-L238
- https://github.com/llvm/llvm-project/blob/b579aacc30bc02e8430c0b59af644f52ece71160/compiler-rt/lib/ubsan/ubsan_value.h#L81-L93
- https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html#undefined-behavior-sanitizer-ubsan
- https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html

## How to test this PR? 

CI is enough for older UBSan versions. To test newer UBSan versions, run on Ubuntu 24.04 (and default Clang version there, which is v18).

2024-07-01 23:35 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kZJfrABgPbILJcSLA):*
By "scaffolding", do you mean that this new feature is not fully supported after this PR?



_Code quote:_
```
This commit adds the scaffolding for the second (new) check
```
___
*[`common/src/avl_tree.c` line 523 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0k_AVa40sNNISktF4w:-O0k_AVa40sNNISktF4x:bx780km) ([raw file](https://github.com/gramineproject/gramine/blob/f05ae1cb639769d2a85526776c4f76551c79f19d/common/src/avl_tree.c#L523)):*
> ```C
>  * UBSan complains about "Indirect call of a function through a function pointer of the wrong type"
>  * because of this mismatch. However, allowing the first argument to be a pointer to any type was
>  * done on purpose; see corresponding comment in avl_tree.h. So, silence this particular complaint.
> ```

I think UBSan is technically right, we can't do the call legally after such a cast. But I'm not sure whether it's worth fixing, I don't see any easy way to do that.
___
*[`common/src/ubsan.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kaCJr8lWuarIHAs-J:-O0kaCJs4VVRtOESoF5g:b-uh0rbl) ([raw file](https://github.com/gramineproject/gramine/blob/f05ae1cb639769d2a85526776c4f76551c79f19d/common/src/ubsan.c#L170)):*
> ```C
>                                            value_handle function_pointer);
> void __ubsan_handle_function_type_mismatch_abort(struct function_type_mismatch_data* data,
>                                                  value_handle function_pointer);
> ```

What's the point of these forward declarations?
___
*[`libos/src/libos_syscalls.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kcZuLBs4p0hvUb7nT:-O0kcZuLBs4p0hvUb7nU:b-p5ptco) ([raw file](https://github.com/gramineproject/gramine/blob/f05ae1cb639769d2a85526776c4f76551c79f19d/libos/src/libos_syscalls.c#L28)):*
> ```C
>  * Variable syscall_func is of type six_args_syscall_t but points to item inside libos_syscall_table
>  * array, which has a type libos_syscall_t, thus UBSan complains about "Indirect call of a function
>  * through a function pointer of the wrong type". Silence this particular complaint.
> ```

ditto, we actually have UB, but it's not obvious how to fix it


<!-- Sent from Reviewable.io -->

2024-07-02 06:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kZJfrABgPbILJcSLA):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

By "scaffolding", do you mean that this new feature is not fully supported after this PR?
</blockquote></details>

No, it is fully supported. I meant the "necessary support", but looks like I misused the English language. I'll replace with `necessary support`.
___
*[`common/src/ubsan.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kaCJr8lWuarIHAs-J:-O0m5v2kCZf5vh8kwWBE:bw355xr) ([raw file](https://github.com/gramineproject/gramine/blob/f05ae1cb639769d2a85526776c4f76551c79f19d/common/src/ubsan.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of these forward declarations?
</blockquote></details>

If remove them, you'll get warnings/errors like this:
```
[264/939] Compiling C object pal/src/host/skeleton/libpal.so.p/.._.._.._.._common_src_ubsan.c.o
../common/src/ubsan.c:145:6: warning: no previous prototype for ‘__ubsan_handle_type_mismatch_v1’ [-Wmissing-prototypes]
  145 | void __ubsan_handle_type_mismatch_v1(struct type_mismatch_data* data, value_handle pointer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:158:6: warning: no previous prototype for ‘__ubsan_handle_type_mismatch_v1_abort’ [-Wmissing-prototypes]
  158 | void __ubsan_handle_type_mismatch_v1_abort(struct type_mismatch_data* data, value_handle pointer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:164:6: warning: no previous prototype for ‘__ubsan_handle_function_type_mismatch’ [-Wmissing-prototypes]
  164 | void __ubsan_handle_function_type_mismatch(struct function_type_mismatch_data* data,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:177:6: warning: no previous prototype for ‘__ubsan_handle_function_type_mismatch_abort’ [-Wmissing-proto
types]
```

Compilers expect either `static` function or a prototype declared first. In here, we don't have a header file (we didn't bother with it, as it is really not required for anything). And we also can't declare the funcs as `static` since the UBSan instrumentation will try to look them up.

Hence this forward declaration.


<!-- Sent from Reviewable.io -->

2024-07-02 07:26 UTC, kailun-qin approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-07-02 14:08 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: all files reviewed, 5 unresolved discussions

___
*[`common/src/ubsan.c` line 170 at r1](https://reviewable.io/reviews/gramineproject/gramine/1929#-O0kaCJr8lWuarIHAs-J:-O0nlRl1DdSvq5x43RT3:b-g6tlbe) ([raw file](https://github.com/gramineproject/gramine/blob/f05ae1cb639769d2a85526776c4f76551c79f19d/common/src/ubsan.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If remove them, you'll get warnings/errors like this:
```
[264/939] Compiling C object pal/src/host/skeleton/libpal.so.p/.._.._.._.._common_src_ubsan.c.o
../common/src/ubsan.c:145:6: warning: no previous prototype for ‘__ubsan_handle_type_mismatch_v1’ [-Wmissing-prototypes]
  145 | void __ubsan_handle_type_mismatch_v1(struct type_mismatch_data* data, value_handle pointer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:158:6: warning: no previous prototype for ‘__ubsan_handle_type_mismatch_v1_abort’ [-Wmissing-prototypes]
  158 | void __ubsan_handle_type_mismatch_v1_abort(struct type_mismatch_data* data, value_handle pointer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:164:6: warning: no previous prototype for ‘__ubsan_handle_function_type_mismatch’ [-Wmissing-prototypes]
  164 | void __ubsan_handle_function_type_mismatch(struct function_type_mismatch_data* data,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/src/ubsan.c:177:6: warning: no previous prototype for ‘__ubsan_handle_function_type_mismatch_abort’ [-Wmissing-proto
types]
```

Compilers expect either `static` function or a prototype declared first. In here, we don't have a header file (we didn't bother with it, as it is really not required for anything). And we also can't declare the funcs as `static` since the UBSan instrumentation will try to look them up.

Hence this forward declaration.
</blockquote></details>

Ah, I missed that there's no header for this file.


<!-- Sent from Reviewable.io -->

2024-07-23 01:11 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-07-23 12:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-23 12:54 UTC, merged