[PAL/Linux-SGX] Add locking around read/write on encrypted pipes
gramineproject/gramine pull request #1934
Opened 2024-07-03 13:04 UTC by dimakuv

## Description of the changes 

Pipes in Linux-SGX PAL are automatically encrypted using mbedTLS's SSL/TLS sessions (aka contexts). By design, an mbedTLS SSL/TLS context is assumed to be used within a single thread and thus does not use any locking. In Gramine, though, the pipe and its associated SSL/TLS context can be used in multiple threads. Without protecting pipe read/write operations with a lock, mbedTLS internal handling of the context would exhibit data races, leading to e.g. -EACCES in Gramine.

This bug was detected on a private workload. This bug can be considered a regression, introduced in [commit "[LibOS] Do not perform lock(&hdl->pos_lock) on non-seekable handles"](https://github.com/gramineproject/gramine/commit/ec06c32366672b3dfc19f539d16d37c6449ab4ca). That commit, among other things, removed the locking around LibOS-level pipe read/write operations; the locks were supposed to guard only "file position", which is meaningless for pipes and that's why that commit removed the locking. However, that locking (by accident) also protected the mbedTLS SSL/TLS context, and removing it resulted in some workloads failing (pipe reads/writes returning -EACCES) due to internal mbedTLS data races.

See for the mbedTLS threading discussion e.g. this thread: https://github.com/Mbed-TLS/mbedtls/issues/564

## How to test this PR? 

Detected on a private workload. ~~I don't know if it's worth it to write a LibOS test that stresses the data race.~~

Added a new LibOS test:
- without this PR:
```
~/gramineproject/gramine/libos/test/regression$ gramine-sgx pipe_race
pipe_race: error at write(pipefds[1], buf, strlen(buf)) (line 45): Permission denied: Permission denied
```

- with this PR:
```
~/gramineproject/gramine/libos/test/regression$ gramine-sgx pipe_race
TEST OK
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1934)

2024-07-05 11:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1934#-O11Y0ax2s_KSlbZVSg0:-O11Y0ax2s_KSlbZVSg1:b-j8tzdu) (no related file):*
I was informed that the fix works on that private workload. So the change itself is good.

I think I still need to create a LibOS test. Blocking myself on this.

___


<!-- Sent from Reviewable.io -->

2024-07-08 08:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1934#-O11Y0ax2s_KSlbZVSg0:-O1GUvCM3gqQbnGDf44N:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was informed that the fix works on that private workload. So the change itself is good.

I think I still need to create a LibOS test. Blocking myself on this.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-07-14 16:55 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_host.h` line 74 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m9LRRBFPL3UK3bdHX:-O1m9LRRBFPL3UK3bdHY:b-rjvw3k) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_host.h#L74)):*
> ```objc
>              * Gramine, though, the pipe and its associated SSL/TLS context can be used in multiple
>              * threads. Without protecting pipe read/write operations with a lock, mbedTLS internal
>              * handling of the context would exhibit data races, leading to e.g. -EACCES in Gramine.
> ```

I'd skip that, it's a random fallout of many levels of error propagation and may change in the future (assuming the bug would be re-introduced).



_Code quote:_
```objc
, leading to e.g. -EACCES in Gramine.
```
___
*[`pal/src/host/linux-sgx/pal_host.h` line 90 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m9l9DCThF0aNGkOA0:-O1m9l9DCThF0aNGkOA1:b-6ortet) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_host.h#L90)):*
> ```objc
>              * Since we're in PAL layer, we can only use spinlocks (not e.g. futexes). It is
>              * suboptimal (for blocking operations), but the hope is that multiple threads
>              * simultaneously operating on the pipe is a rare scenario.
> ```

Theoretically we could fix this by introducing `try_lock()` and returning `-EAGAIN` if it fails, but not sure if it's worth the effort.
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 176 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m0D-zEQMkmqd5qjQ0:-O1m0D-zEQMkmqd5qjQ1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_pipes.c#L176)):*
> ```C
>  * our end of the pipe. Typically, `pipesrv` handle is not needed after this and can be closed.
>  */
> static int pipe_waitforclient(PAL_HANDLE handle, PAL_HANDLE* client, pal_stream_options_t options) {
> ```





_Suggestion:_
```C
out_client
```
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 248 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m05ON88JnoEYtw0sd:-O1m05ON88JnoEYtw0se:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_pipes.c#L248)):*
> ```C
>  * The other end of the pipe is typically of type `pipecli`.
>  */
> static int pipe_connect(PAL_HANDLE* handle, const char* name, pal_stream_options_t options) {
> ```





_Suggestion:_
```C
out_handle
```


<!-- Sent from Reviewable.io -->

2024-07-15 06:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_host.h` line 74 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m9LRRBFPL3UK3bdHX:-O1p72eF0SBI01N2eypO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_host.h#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd skip that, it's a random fallout of many levels of error propagation and may change in the future (assuming the bug would be re-introduced).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_host.h` line 90 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m9l9DCThF0aNGkOA0:-O1p6STf0VyJ-rfaoKPt:b60a13j) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_host.h#L90)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Theoretically we could fix this by introducing `try_lock()` and returning `-EAGAIN` if it fails, but not sure if it's worth the effort.
</blockquote></details>

Yeah, I also think it is not worth the effort.
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 176 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m0D-zEQMkmqd5qjQ0:-O1p7UnTA2SuIuuuI8wB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_pipes.c#L176)):*
> ```C
>  * our end of the pipe. Typically, `pipesrv` handle is not needed after this and can be closed.
>  */
> static int pipe_waitforclient(PAL_HANDLE handle, PAL_HANDLE* client, pal_stream_options_t options) {
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 248 at r2](https://reviewable.io/reviews/gramineproject/gramine/1934#-O1m05ON88JnoEYtw0sd:-O1p8-buCp3W5YQz11VI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/38c61db002c27736095e8e9fd87899a2184b6361/pal/src/host/linux-sgx/pal_pipes.c#L248)):*
> ```C
>  * The other end of the pipe is typically of type `pipecli`.
>  */
> static int pipe_connect(PAL_HANDLE* handle, const char* name, pal_stream_options_t options) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 11:41 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-16 01:36 UTC, kailun-qin approved these changes
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-24 00:46 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1934)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-24 06:35 UTC, merged