[LibOS] Add `O_APPEND` emulation for single process
gramineproject/gramine pull request #1935
Opened 2024-07-04 08:10 UTC by dimakuv

## Description of the changes 

FIXME:
- Add all checks and return errors for incorrect O_APPEND usage
- Add libos/test/fs tests
  - Make sure that read before first write starts with pos=0 (?)
  - Make sure that read after first write starts with pos=size
  - Make sure that lseek+read in one thread and write in another thread don't lead to corrupted data (reproducer of issue #1921)
  - Make sure that all kinds of FS mounts work fine with O_APPEND
- Make it explicit that O_APPEND is currently emulated only for a single process; maybe mark O_APPEND files as poisoned in the child process

See #1921 

## How to test this PR? 

**To be done**.

2024-07-09 10:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LsdKy3vc0TfrooH65:-O1LsdKy3vc0TfrooH66:bniieoz) (no related file):*
FYI: implementation of `O_APPEND` in the Linux kernel is very simple and self-contained. I searched for `APPEND` keyword and these are the main sources:
- https://elixir.bootlin.com/linux/v6.9/source/fs/fcntl.c
- https://elixir.bootlin.com/linux/v6.9/source/fs/namei.c
- https://elixir.bootlin.com/linux/v6.9/source/fs/open.c
- https://elixir.bootlin.com/linux/v6.9/source/fs/read_write.c

I hope I covered all Linux logic on `O_APPEND` in this PR. (Note that some logic was already implemented in Gramine.)

___
___
*[`libos/src/fs/chroot/encrypted.c` line 480 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1Lwy1e6kb20upxaBs6:-O1Lwy1f7zAJi0t5XHsr:bze3a6a) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/fs/chroot/encrypted.c#L480)):*
> ```C
>     lock(&hdl->inode->lock);
> 
>     file_off_t actual_pos = (hdl->flags & O_APPEND) ? hdl->inode->size : *pos;
> ```

I admit that I don't understand the locking in these handlers... Technically, `O_APPEND` flag may be changed at runtime via `fcntl(SET_FL)`, so there must be smth like `lock(&hdl->lock)`. At the same time, I don't observe such locking in other (similar) places, and it's also confusing what needs to be locked where.

So for now I do not perform additional locking. I even wonder if `hdl->flags` can be considered thread-safe for well-behaved apps, because if some app changes the flags in one thread and e.g. writes in another thread, that's a data race and a bug in the app.
___
*[`libos/src/sys/libos_file.c` line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LwebsA8gjS7OR8QEi:-O1LwebsA8gjS7OR8QEj:bimpv2u) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/sys/libos_file.c#L445)):*
> ```C
>     }
> 
>     if (!(in_hdl->acc_mode & MAY_READ) || !(out_hdl->acc_mode & MAY_WRITE)
> ```

FYI: this change is orthogonal to this PR. Surprisingly, there was already handling of `O_APPEND` in this sendfile emulation, though it returned an incorrect error code. So I fixed this and also added two other checks. This could be moved out to a separate PR if needed.
___
*[`libos/test/fs/test_fs.py` line 136 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LxhdQ6vak-T958suw:-O1LxhdQ6vak-T958sux:b-iic0jk) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/test/fs/test_fs.py#L136)):*
> ```Python
>         self.assertIn('TEST 1 (' + file_path + ')', stdout)
>         self.assertIn('TEST 2 (' + file_path + ')', stdout)
>         self.assertIn('TEST 3 (' + file_path + ')', stdout)
> ```

FYI: Other FS tests also do things like `self.assertIn(close(...))`, but there are so many lines in the log, that I found it stupid to check each line. So just checking that sub-tests are at least started and printed out. And of course the whole test must run to successful completion.


<!-- Sent from Reviewable.io -->

2024-07-30 08:36 UTC, dimakuv commented
Jenkins, test this please (Jenkins was dead when this PR was created)

2024-10-09 18:15 UTC, efu39 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`libos/src/sys/libos_file.c` line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LwebsA8gjS7OR8QEi:-O8mQqhJEWcbaTpmtV1v:b-f36ssi) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/sys/libos_file.c#L445)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: this change is orthogonal to this PR. Surprisingly, there was already handling of `O_APPEND` in this sendfile emulation, though it returned an incorrect error code. So I fixed this and also added two other checks. This could be moved out to a separate PR if needed.
</blockquote></details>

According to [the sendfile man page](https://man7.org/linux/man-pages/man2/sendfile.2.html), it appears that the original error code -EINVAL is intended to be returned when out_hdl has the O_APPEND flag set. 
"**EINVAL**    _out\_fd_ has the **O\_APPEND** flag set.  This is not currently
              supported by **sendfile**()."


<!-- Sent from Reviewable.io -->

2024-10-29 02:45 UTC, kailun-qin requested changes
> Reviewed 1 of 7 files at r1, 15 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: 16 of 18 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @efu39)

___
*[`libos/src/sys/libos_file.c` line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LwebsA8gjS7OR8QEi:-OAL-CnNDAnpVc55CML8:bfips74) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/sys/libos_file.c#L445)):*
<details><summary><i>Previously, efu39 (Erica Fu) wrote…</i></summary><blockquote>

According to [the sendfile man page](https://man7.org/linux/man-pages/man2/sendfile.2.html), it appears that the original error code -EINVAL is intended to be returned when out_hdl has the O_APPEND flag set. 
"**EINVAL**    _out\_fd_ has the **O\_APPEND** flag set.  This is not currently
              supported by **sendfile**()."
</blockquote></details>

+1

Why change the previous check on outfd w/ `O_APPEND` to return `-EBADF` (which should return `-EINVAL`)?
___
*[`libos/src/sys/libos_open.c` line 335 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-OAKqDgR1PEAjX1vhD01:-OAKqDgS22OFkvDeQNJL:bn3546z) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/sys/libos_open.c#L335)):*
> ```C
>     /*
>      * Note that Linux has the following bug: POSIX requires that opening a file with the O_APPEND
>      * flag should have no affect on the location at which pwrite() writes data. However, on Linux,
> ```

-> effect



_Code quote:_
```C
affect
```
___
*[`libos/test/fs/read_append.c` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-OAL6_lyAd9rkAVt-ZPo:-OAL6_lyAd9rkAVt-ZPp:b9ysarz) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/test/fs/read_append.c#L36)):*
> ```C
>     printf("close(%s) OK\n", file_path);
>     if (file_size(file_path) != size)
>         fatal_error("File size is wrong (expected sizeof(buf1))\n");
> ```

This looks a bit weird -- shouldn't we print the expected and got bytes?



_Code quote:_
```C
expected sizeof(buf1)
```
___
*[`libos/test/fs/read_append.c` line 73 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-OAL7I1R4LLcnoFiHC3U:-OAL7I1R4LLcnoFiHC3V:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/test/fs/read_append.c#L73)):*
> ```C
>     printf("close(%s) OK\n", file_path);
>     if (file_size(file_path) != size * 2)
>         fatal_error("File size is wrong (expected sizeof(buf1) * 2)\n");
> ```

ditto



_Code quote:_
```C
expected sizeof(buf1) * 2
```
___
*[`libos/test/fs/read_append.c` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-OAL7K_91SPcXyZjZJX7:-OAL7K_91SPcXyZjZJX8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/test/fs/read_append.c#L105)):*
> ```C
>     printf("close(%s) OK\n", file_path);
>     if (file_size(file_path) != size * 3)
>         fatal_error("File size is wrong (expected sizeof(buf1) * 3)\n");
> ```

ditto



_Code quote:_
```C
expected sizeof(buf1) * 3
```


<!-- Sent from Reviewable.io -->

2024-10-30 01:37 UTC, kailun-qin reviewed
> This PR doesn't change this limitation of Gramine, thus `O_APPEND` writes don't work correctly (may overwrite file contents).

I think we want to log some warning when e.g., child process tries to write an `O_APPEND` fd created by parent process?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935#-:-OAQ1teKE4kh9yY9DBUL:b-ifhzq4)* status: 16 of 18 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @efu39)



<!-- Sent from Reviewable.io -->

2024-10-31 02:21 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: 16 of 18 files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1935#-OASrLSs-xWQV66D4GgQ:-OAVKu1FBKc6UlAe2MM8:b9d5l8d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin wrote:

> I think we want to log some warning when e.g., child process tries to write an `O_APPEND` fd created by parent process?

Yes, for some reason I thought I implemented that... But now I see that I didn't add this logic. Unfortunately, this is not that trivial to add here, because I'm not sure to which file types it should be applied, and whether we should keep track of the offset (like, the file was opened in APPEND mode but was never written to, and then `fork()` happens, in this case the child would be the only process that uses this file and it's actually safe).

So I decided not to implement it in this PR, as we won't have time to finalize this before I'm gone.

(For info, we mean the trick like used in secure eventfd: https://github.com/gramineproject/gramine/commit/51e99f9880052c051f8774f63af5073d82503c7d)
</blockquote></details>

Yeah, fair enough. I'm not blocking as we mentioned this single-process limitation in the doc and Gramine doesn't support multi-process operations on the same file anyhow (w/o warning logs).

___


<!-- Sent from Reviewable.io -->

2024-10-31 02:32 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: 16 of 18 files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/sys/libos_file.c` line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LwebsA8gjS7OR8QEi:-OAVP29P8Otukgpm0u5_:bnhpjbf) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/src/sys/libos_file.c#L445)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting, you're right after some quick testing on Linux.

I was confused by this Linux code: https://elixir.bootlin.com/linux/v6.11.5/source/fs/read_write.c#L1735. But apparently this code path is *not* used in `sendfile()`.

Done.
</blockquote></details>

Yeah, it looks to be checked here: https://elixir.bootlin.com/linux/v6.11.5/source/fs/splice.c#L1204.


<!-- Sent from Reviewable.io -->

2024-11-15 01:23 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1, 11 of 17 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: all files reviewed, 9 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/fs/test_fs.py` line 136 at r2](https://reviewable.io/reviews/gramineproject/gramine/1935#-O1LxhdQ6vak-T958suw:-OBhKOQZDzQ0K5wmX14w:b-geq7er) ([raw file](https://github.com/gramineproject/gramine/blob/49506611b302bae19a15ce7497c2c1dc30fd6879/libos/test/fs/test_fs.py#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Other FS tests also do things like `self.assertIn(close(...))`, but there are so many lines in the log, that I found it stupid to check each line. So just checking that sub-tests are at least started and printed out. And of course the whole test must run to successful completion.
</blockquote></details>

Fine, but please at least assert on some message which is printed at the successful exit.
___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhCxfl52-kCB0xCX-5:-OBhCxfl52-kCB0xCX-6:b-y5j2iz) (no related file):*
@kailun-qin: Could you rebase the PR, so the CI could test it on 22.04 and 24.04?
___
*[`libos/test/fs/test_tmpfs.py` line 75 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhKcw78p0kMjGgoJIO:-OBhKcw78p0kMjGgoJIP:blk4h0i) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/test_tmpfs.py#L75)):*
> ```Python
>         self.assertIn('close(' + file_path + ') RW fd2 OK', stdout)
> 
>     # overrides TC_00_FileSystem to skip verification by python
> ```

What verification? It seems to do exactly the same as the overwritten method?
___
*[`libos/test/fs/read_append.c` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhLbSC2tlZn0rvIo4e:-OBhLbSC2tlZn0rvIo4f:bsvgqek) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L5)):*
> ```C
> static void read_append(const char* file_path) {
>     const size_t size = 1024 * 1024;
>     assert(size % 2 == 0);
> ```

Could we move this closer to the first `/ 2`? Seems quite weird here.
Or better: remove it, and use instead `size / 2` and `size - size / 2` for chunk sizes.
___
*[`libos/test/fs/read_append.c` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhMucHDjvPVl9FpkSO:-OBhMucHDjvPVl9FpkSP:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L24)):*
> ```C
>     bytes_read = read(fd, buf2, size);
>     if (bytes_read != 0)
>         fatal_error("Read after append does not indicate EOF\n");
> ```





_Suggestion:_
```C
("Read after append did not indicate EOF\n");
```
___
*[`libos/test/fs/read_append.c` line 41 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhNfWgCbf0xY5qm2Pd:-OBhNfWgCbf0xY5qm2Pe:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L41)):*
> ```C
> 
> 
>     /* test 2: open file created previously (it must contain buf1), then read (this should return
> ```





_Suggestion:_
```C
open the file created previously
```
___
*[`libos/test/fs/read_append.c` line 54 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhO-ZYCdQ8gUXkSTYK:-OBhO-ZYCdQ8gUXkSTYL:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L54)):*
> ```C
>     bytes_read = read(fd, buf2, size);
>     if (bytes_read != 0)
>         fatal_error("Second read does not indicate EOF\n");
> ```





_Suggestion:_
```C
"Second read did not indicate EOF\n"
```
___
*[`libos/test/fs/read_append.c` line 78 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhOp3xA0u0IHJLrR8O:-OBhOp3xA0u0IHJLrR8P:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L78)):*
> ```C
>     printf("file_size(%s) OK\n", file_path);
> 
>     /* test 3: open file created previously (size must be sizeof(buf1) * 2) in no-append mode, reset
> ```





_Suggestion:_
```C
open the file
```


<!-- Sent from Reviewable.io -->

2024-11-15 02:27 UTC, kailun-qin approved these changes
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: all files reviewed, 9 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhCxfl52-kCB0xCX-5:-OBhchwLB7wKvKmg_F_z:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@kailun-qin: Could you rebase the PR, so the CI could test it on 22.04 and 24.04?
</blockquote></details>

Done.
___
*[`libos/test/fs/read_append.c` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhLbSC2tlZn0rvIo4e:-OBhdAwf4_DK3i0l-NTQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we move this closer to the first `/ 2`? Seems quite weird here.
Or better: remove it, and use instead `size / 2` and `size - size / 2` for chunk sizes.
</blockquote></details>

Done.
___
*[`libos/test/fs/test_tmpfs.py` line 75 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhKcw78p0kMjGgoJIO:-OBhdLqqB4jlQepS6eG7:b-s3vmft) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/test_tmpfs.py#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What verification? It seems to do exactly the same as the overwritten method?
</blockquote></details>

It's `self.assertTrue(os.path.isfile(file_path))` that we skipped -- updated the comment.
___
*[`libos/test/fs/read_append.c` line 24 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhMucHDjvPVl9FpkSO:-OBhdEJWAXXLUg62RU9h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L24)):*
> ```C
>     bytes_read = read(fd, buf2, size);
>     if (bytes_read != 0)
>         fatal_error("Read after append does not indicate EOF\n");
> ```

Done.
___
*[`libos/test/fs/read_append.c` line 41 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhNfWgCbf0xY5qm2Pd:-OBhdFh_4fEkn5_qzFD0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L41)):*
> ```C
> 
> 
>     /* test 2: open file created previously (it must contain buf1), then read (this should return
> ```

Done.
___
*[`libos/test/fs/read_append.c` line 54 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhO-ZYCdQ8gUXkSTYK:-OBhdH1X-_fdqQnA2Hwo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L54)):*
> ```C
>     bytes_read = read(fd, buf2, size);
>     if (bytes_read != 0)
>         fatal_error("Second read does not indicate EOF\n");
> ```

Done.
___
*[`libos/test/fs/read_append.c` line 78 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhOp3xA0u0IHJLrR8O:-OBhdJBC0KEi0dN6dOfI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/read_append.c#L78)):*
> ```C
>     printf("file_size(%s) OK\n", file_path);
> 
>     /* test 3: open file created previously (size must be sizeof(buf1) * 2) in no-append mode, reset
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 12:44 UTC, mkow approved these changes
> Reviewed 1 of 3 files at r3, 7 of 10 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: all files reviewed, 1 unresolved discussion

___
*[`libos/test/fs/test_tmpfs.py` line 75 at r3](https://reviewable.io/reviews/gramineproject/gramine/1935#-OBhKcw78p0kMjGgoJIO:-OBje18e-eh9mby9CVuE:bn8kfat) ([raw file](https://github.com/gramineproject/gramine/blob/a10fafcda464dfaf99e8de84235b76d2c3aab13e/libos/test/fs/test_tmpfs.py#L75)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

It's `self.assertTrue(os.path.isfile(file_path))` that we skipped -- updated the comment.
</blockquote></details>

Ah, I missed that. The comment is much better now :)


<!-- Sent from Reviewable.io -->

2024-11-16 01:25 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-16 01:32 UTC, merged