[LibOS] Add `shared_cpu_list` file to sysfs cache info
gramineproject/gramine pull request #1937
Opened 2024-07-10 10:17 UTC by dimakuv

## Description of the changes 

This is e.g. required by the gemm-common Rust crate, see `gemm-common/src/cache.rs`. Without this file, the crate logic incorrectly calculates shared-cpu count as zero and leads to a division-by-zero exception.

See:
- https://crates.io/crates/gemm-common
- https://github.com/sarah-ek/gemm/blob/8cdc1de4af69ce3fd2575b2c983fc1ccc974425f/gemm-common/src/cache.rs#L128

Detected while trying to run Candle: https://github.com/huggingface/candle/tree/0.6.0

## How to test this PR? 

Use Busybox for manual checks:

```
~/gramine-tdx/CI-Examples/busybox$ gramine-direct busybox sh
cat /sys/devices/system/cpu/cpu1/cache/index0/shared_cpu_list
1,65
cat /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_list
0-31,64-95
cat /sys/devices/system/cpu/cpu0/cache/index1/shared_cpu_list
0,64
cat /sys/devices/system/cpu/cpu100/cache/index2/shared_cpu_list
36,100
```

2024-07-14 14:16 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/fs/sys/cache_info.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1l_Kv89vAYeJtU0NjY:-O1l_Kv89vAYeJtU0NjZ:b-djf7p0) ([raw file](https://github.com/gramineproject/gramine/blob/c192d4d9b1ec7fe73e4d8977e45cb40c30a61054/libos/src/fs/sys/cache_info.c#L47)):*
> ```C
>     size_t cache_idx = topo->threads[thread_id].ids_of_caches[cache_class];
>     const struct pal_cache_info* cache = &topo->caches[cache_idx];
>     char str[PAL_SYSFS_BUF_FILESZ] = {'\0'};
> ```

The description of this constant doesn't match the usage here, please update it.



_Code quote:_
```C
PAL_SYSFS_BUF_FILESZ
```


<!-- Sent from Reviewable.io -->

2024-07-15 06:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/sys/cache_info.c` line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1l_Kv89vAYeJtU0NjY:-O1pAgYu4bkg9eBDlB6r:b-kvki1k) ([raw file](https://github.com/gramineproject/gramine/blob/c192d4d9b1ec7fe73e4d8977e45cb40c30a61054/libos/src/fs/sys/cache_info.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The description of this constant doesn't match the usage here, please update it.
</blockquote></details>

Done. I decided to do it slightly differently and introduce a new macro (since it looks like the LibOS must use its own macros).


<!-- Sent from Reviewable.io -->

2024-07-15 11:46 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/include/libos_fs_pseudo.h` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qC7u9ARkH8th_KP6e:-O1qC7u9ARkH8th_KP6f:bcwjd4i) ([raw file](https://github.com/gramineproject/gramine/blob/8b98437a905ae9335cb012dba98399d62139649c/libos/include/libos_fs_pseudo.h#L79)):*
> ```objc
> /* Used to represent cpu lists like "0-31,64-95,97".
>  * Note: Used to allocate on stack; increase with caution or use malloc instead. */
> #define PAL_SYSFS_LIST_FILESZ 512
> ```

We use "ranges" in all other places in topology implementation for that.



_Suggestion:_
```objc
PAL_SYSFS_RANGES_FILESZ
```
___
*[`libos/include/libos_fs_pseudo.h` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qCezJ2Wwjfdej7T_Y:-O1qCezJ2Wwjfdej7T_Z:b2mmgcb) ([raw file](https://github.com/gramineproject/gramine/blob/8b98437a905ae9335cb012dba98399d62139649c/libos/include/libos_fs_pseudo.h#L79)):*
> ```objc
> /* Used to represent cpu lists like "0-31,64-95,97".
>  * Note: Used to allocate on stack; increase with caution or use malloc instead. */
> #define PAL_SYSFS_LIST_FILESZ 512
> ```

Could you also use it in a few other places where `PAL_SYSFS_BUF_FILESZ` was used for ranges?


<!-- Sent from Reviewable.io -->

2024-07-15 13:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: 1 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/include/libos_fs_pseudo.h` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qC7u9ARkH8th_KP6e:-O1qcT2e7PIDnTGpDEM_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b98437a905ae9335cb012dba98399d62139649c/libos/include/libos_fs_pseudo.h#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We use "ranges" in all other places in topology implementation for that.
</blockquote></details>

Done.
___
*[`libos/include/libos_fs_pseudo.h` line 79 at r2](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qCezJ2Wwjfdej7T_Y:-O1qcTKZCZxUpNFHEi2z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b98437a905ae9335cb012dba98399d62139649c/libos/include/libos_fs_pseudo.h#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also use it in a few other places where `PAL_SYSFS_BUF_FILESZ` was used for ranges?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 13:55 UTC, mkow requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/fs/sys/cpu_info.c` line 101 at r3](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qf0KXA5WFaEHti8e2:-O1qf0KXA5WFaEHti8e3:b-4x7yln) ([raw file](https://github.com/gramineproject/gramine/blob/0b22917300706c7338172be4447a51de1f10d4dc/libos/src/fs/sys/cpu_info.c#L101)):*
> ```C
>     /* str buffer of the same size is used for all below pseudo-files; we pick the largest size for
>      * this buffer (which is presumably the size required for the "core_siblings" file) */
>     static_assert(PAL_SYSFS_RANGES_FILESZ >= PAL_SYSFS_MAP_FILESZ, "sysfs file size too small");
> ```

I think it should be max(MAP, BUF) here? At least looking at the constants descriptions. There's no range printing below.


<!-- Sent from Reviewable.io -->

2024-07-15 14:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/fs/sys/cpu_info.c` line 101 at r3](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qf0KXA5WFaEHti8e2:-O1qgFae5j3TuhEa6B7v:bb9bw7k) ([raw file](https://github.com/gramineproject/gramine/blob/0b22917300706c7338172be4447a51de1f10d4dc/libos/src/fs/sys/cpu_info.c#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should be max(MAP, BUF) here? At least looking at the constants descriptions. There's no range printing below.
</blockquote></details>

Oops, I confused `core_siblings` with `core_siblings_list`. The former prints the cpumap, the latter prints the ranges. But we don't currently implement the latter, so let me revert this change.


<!-- Sent from Reviewable.io -->

2024-07-15 14:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`libos/src/fs/sys/cpu_info.c` line 101 at r3](https://reviewable.io/reviews/gramineproject/gramine/1937#-O1qf0KXA5WFaEHti8e2:-O1qstlm6Z9YxPGLq-14:b-h25l4q) ([raw file](https://github.com/gramineproject/gramine/blob/0b22917300706c7338172be4447a51de1f10d4dc/libos/src/fs/sys/cpu_info.c#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, I confused `core_siblings` with `core_siblings_list`. The former prints the cpumap, the latter prints the ranges. But we don't currently implement the latter, so let me revert this change.
</blockquote></details>

I was looking at the actual printing calls below, not the node names. More reliable ;)


<!-- Sent from Reviewable.io -->

2024-07-16 01:52 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-24 06:57 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-24 13:34 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1937)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-24 14:13 UTC, merged