[glibc] Bump version to 2.40
gramineproject/gramine pull request #1943
Opened 2024-07-23 05:21 UTC by kailun-qin

## Description of the changes 

This glibc version includes fixes for CVE-2024-2961, CVE-2024-33599, CVE-2024-33600, CVE-2024-33601 and CVE-2024-33602.

## How to test this PR? 
CI

2024-07-23 05:25 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: 0 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2T1bOi5pZE7uQ2mWcT:-O2T1bOi5pZE7uQ2mWcU:btrdnro) ([raw file](https://github.com/gramineproject/gramine/blob/afb8a358f3d5542a41c1f2890d818596642d721a/subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch#L1)):*
> ```Diff
> From 73302ea9454b816d5e0a4f02bbd68df1bf2bb53d Mon Sep 17 00:00:00 2001
> ```

I removed this as the patch is no longer an exact copy of the one in the Ubuntu Noble patches (which applied to glibc 2.39).
___
*[`subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch` line 123 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2T20lz-gI1h3ngsqgv:-O2T20lz-gI1h3ngsqgw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/afb8a358f3d5542a41c1f2890d818596642d721a/subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch#L123)):*
> ```Diff
>  CFLAGS-wmemchr.c += $(config-cflags-wno-ignored-attributes)
> 
> base-commit: 983f34a1252de3ca6f2305c211d86530ea42010e
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-23 06:44 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2TBcYH4I71d5lzDHZR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like the first CVE (https://github.com/advisories/GHSA-22q4-f5r6-3xqw) is relevant, the others are not.
</blockquote></details>

Yes
___
*[`subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2T1bOi5pZE7uQ2mWcT:-O2TJzKR2M_5Du9RtP2I:b-ndg6js) ([raw file](https://github.com/gramineproject/gramine/blob/afb8a358f3d5542a41c1f2890d818596642d721a/subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch#L1)):*
> Why wasn't this patch applied in Glibc, do you know?

No, I don't (at this moment).

> Or Ubuntu doesn't have 2.40 yet?

Right, it doesn't have 2.40 yet.


<!-- Sent from Reviewable.io -->

2024-07-23 14:59 UTC, mkow requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2024-08-06 10:15 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`subprojects/glibc-2.40-1.wrap` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2TC6Vb9p3HvoOyeSsG:-O3bAoSL4QNFxSSwsi1f:b2myrz2) ([raw file](https://github.com/gramineproject/gramine/blob/34a97c5d7ea608ba52ef20af8da71c3f66e6d915/subprojects/glibc-2.40-1.wrap#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Can we mirror this file (https://ftp.gnu.org/gnu/glibc/glibc-2.40.tar.gz) under our packages, please?
</blockquote></details>

Done. Sure we can.
___
*[`subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2T1bOi5pZE7uQ2mWcT:-O3b8saQDTywkeYu3nzh:b2g51kh) ([raw file](https://github.com/gramineproject/gramine/blob/afb8a358f3d5542a41c1f2890d818596642d721a/subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch#L1)):*
I think the preamble should have remained, because it describes authorship of the patch and shouldn't be removed, because we need to credit the author. If you need to fix something (like `From ` mbox line), you should apply the patch to glibc repo, then rework as needed (IIUC, rebase), then `git format-patch`, and it will still contain `From:` attribution.

> Why wasn't this patch applied in Glibc, do you know?

Unless you're sure it was submitted upstream for inclusion, I'd assume it never was, so it's very likely that it wasn't merged simply because it wasn't proposed to be merged. Upstreams rarely if ever patrol distros' repos for random patches.


<!-- Sent from Reviewable.io -->

2024-08-07 01:51 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`subprojects/glibc-2.40-1.wrap` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2TC6Vb9p3HvoOyeSsG:-O3eVAe72UYRZoE-aMfx:b-wqyg4t) ([raw file](https://github.com/gramineproject/gramine/blob/34a97c5d7ea608ba52ef20af8da71c3f66e6d915/subprojects/glibc-2.40-1.wrap#L11)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. Sure we can.
</blockquote></details>

Thanks! I just tested it -- everything works fine.
___
*[`subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/1943#-O2T1bOi5pZE7uQ2mWcT:-O3eVN-I7VZn4kPvT3DB:b8zw9a9) ([raw file](https://github.com/gramineproject/gramine/blob/afb8a358f3d5542a41c1f2890d818596642d721a/subprojects/packagefiles/glibc-2.40/fix-fortify-source.patch#L1)):*
> I think the preamble should have remained, because it describes authorship of the patch and shouldn't be removed, because we need to credit the author.

Yeah, I agree.

> And is this patch applied in Ubuntu? Or Ubuntu doesn't have 2.40 yet?
> > Right, it doesn't have 2.40 yet.

Now I use the patch directly extracted from http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/glibc_2.40-1ubuntu1.debian.tar.xz, which was available yesterday (2024-08-06).


<!-- Sent from Reviewable.io -->

2024-08-07 06:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-08-08 00:07 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-08 01:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1943)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-08 05:57 UTC, merged