[LibOS] Introduce `refresh_mappings_on_file()` convenience func
gramineproject/gramine pull request #1956
Opened 2024-07-26 11:29 UTC by dimakuv

## Description of the changes 

This commit refactors repetitive invocations of file-mapping related functions `prot_refresh_mmaped_from_file_handle()` and `reload_mmaped_from_file_handle()` into a new convenience function.

Fixes #1931.

Applies on top of #1818.

## How to test this PR? 

CI is enough.

2024-07-31 02:29 UTC, kailun-qin requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35afn42yD3nzkkVzpa:-O35afn5-gt9hyrKhu59:bygrnlj) ([raw file](https://github.com/gramineproject/gramine/blob/422891600052349ebbbdd5c99146b6038f31f1fd/libos/src/bookkeep/libos_vma.c#L1715)):*
> ```C
>                               bool reload_file_contents) {
>     assert(hdl->type == TYPE_TMPFS || hdl->type == TYPE_SHM || hdl->type == TYPE_CHROOT
>             || hdl->type == TYPE_CHROOT_ENCRYPTED);
> ```

pls align



_Code quote:_
```C
            || hdl->type == TYPE_CHROOT_ENCRYPTED);
```
___
*[`libos/src/bookkeep/libos_vma.c` line 1723 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35ZVmtCP6oTWsBTk1u:-O35ZVmtCP6oTWsBTk1v:bygrnlj) ([raw file](https://github.com/gramineproject/gramine/blob/422891600052349ebbbdd5c99146b6038f31f1fd/libos/src/bookkeep/libos_vma.c#L1723)):*
> ```C
>     if (refresh_ret < 0) {
>         log_error("refreshing page protections of mmapped regions of file failed: %s",
>                 unix_strerror(refresh_ret));
> ```

pls align



_Code quote:_
```C
                unix_strerror(refresh_ret));
```
___
*[`libos/src/fs/chroot/encrypted.c` line 503 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35bP7v-diO08u5n0jZ:-O35bP7v-diO08u5n0j_:bp1rygv) ([raw file](https://github.com/gramineproject/gramine/blob/f61dbdf8a5462099a8bac6345db1908bfc31045f/libos/src/fs/chroot/encrypted.c#L503)):*
> ```C
>         }
> 
>         /* There are mappings for the file, read data from `enc` (only for MAP_SHARED mappings). */
> ```

since we removed this now, can we added it to the comment of the function prototype



_Code quote:_
```C
only for MAP_SHARED mappings
```


<!-- Sent from Reviewable.io -->

2024-07-31 07:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: 4 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35afn42yD3nzkkVzpa:-O36klc53VBynC5pqtD-:bh5eqw7) ([raw file](https://github.com/gramineproject/gramine/blob/422891600052349ebbbdd5c99146b6038f31f1fd/libos/src/bookkeep/libos_vma.c#L1715)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

pls align
</blockquote></details>

Done. Is that the alignment you wanted?
___
*[`libos/src/bookkeep/libos_vma.c` line 1723 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35ZVmtCP6oTWsBTk1u:-O36kogx6qcBgEsLkUeW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/422891600052349ebbbdd5c99146b6038f31f1fd/libos/src/bookkeep/libos_vma.c#L1723)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

pls align
</blockquote></details>

Done.
___
*[`libos/src/fs/chroot/encrypted.c` line 503 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35bP7v-diO08u5n0jZ:-O36l2VR0Sg05mQ2xj0k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f61dbdf8a5462099a8bac6345db1908bfc31045f/libos/src/fs/chroot/encrypted.c#L503)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

since we removed this now, can we added it to the comment of the function prototype
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-31 08:15 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r1](https://reviewable.io/reviews/gramineproject/gramine/1956#-O35afn42yD3nzkkVzpa:-O36pIjZ3vvQyZ80720P:b-rx3qis) ([raw file](https://github.com/gramineproject/gramine/blob/422891600052349ebbbdd5c99146b6038f31f1fd/libos/src/bookkeep/libos_vma.c#L1715)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Is that the alignment you wanted?
</blockquote></details>

yep, thanks


<!-- Sent from Reviewable.io -->

2024-08-04 21:07 UTC, mkow requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r2](https://reviewable.io/reviews/gramineproject/gramine/1956#-O3U8weV4IDnrcCEo0mV:-O3U8weV4IDnrcCEo0mW:bmcnnzs) ([raw file](https://github.com/gramineproject/gramine/blob/c65d9a9bef26bb6ee9ccbd5dc62d9f5d6be8f91c/libos/src/bookkeep/libos_vma.c#L1715)):*
> ```C
>                               bool reload_file_contents) {
>     assert(hdl->type == TYPE_TMPFS || hdl->type == TYPE_SHM || hdl->type == TYPE_CHROOT
>               || hdl->type == TYPE_CHROOT_ENCRYPTED);
> ```

indentation by 3 spaces?


<!-- Sent from Reviewable.io -->

2024-08-05 06:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r2](https://reviewable.io/reviews/gramineproject/gramine/1956#-O3U8weV4IDnrcCEo0mV:-O3WHBxO92Q70C2QQKss:b-dei2zz) ([raw file](https://github.com/gramineproject/gramine/blob/c65d9a9bef26bb6ee9ccbd5dc62d9f5d6be8f91c/libos/src/bookkeep/libos_vma.c#L1715)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

indentation by 3 spaces?
</blockquote></details>

By 2 spaces, that's what Vim recommended me. Anyway, 4 spaces now.


<!-- Sent from Reviewable.io -->

2024-08-05 10:45 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r2](https://reviewable.io/reviews/gramineproject/gramine/1956#-O3U8weV4IDnrcCEo0mV:-O3X8-Lw7IvX5FpeKVgR:b-5pffmp) ([raw file](https://github.com/gramineproject/gramine/blob/c65d9a9bef26bb6ee9ccbd5dc62d9f5d6be8f91c/libos/src/bookkeep/libos_vma.c#L1715)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By 2 spaces, that's what Vim recommended me. Anyway, 4 spaces now.
</blockquote></details>

It was 3, not 2? :P (counting from `(`, because we align to parentheses)
Now it's 5?


<!-- Sent from Reviewable.io -->

2024-08-05 10:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/src/bookkeep/libos_vma.c` line 1715 at r2](https://reviewable.io/reviews/gramineproject/gramine/1956#-O3U8weV4IDnrcCEo0mV:-O3XAkp90Ww7ly-O789g:b-pyz6hc) ([raw file](https://github.com/gramineproject/gramine/blob/c65d9a9bef26bb6ee9ccbd5dc62d9f5d6be8f91c/libos/src/bookkeep/libos_vma.c#L1715)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was 3, not 2? :P (counting from `(`, because we align to parentheses)
Now it's 5?
</blockquote></details>

Done. Lol


<!-- Sent from Reviewable.io -->

2024-08-05 11:34 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-05 13:34 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-05 23:55 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-05 23:59 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1956)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-06 00:00 UTC, merged