WIP: [CI] Test apps in the SGX sanitizers configuration
gramineproject/gramine pull request #197
Opened 2021-11-05 14:56 UTC by pwmarcz

Signed-off-by: Paweł Marczewski <pawel@invisiblethingslab.com>

## Description of the changes 

## How to test this PR?

2021-11-09 07:57 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/197)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/197#-Mo2gGB0CTO7X8opGqBb):*
So ASan and UBSan only work on PIE executables? I can't believe this. What was the exact problem? Or is it not about ASan/UBSan, but the what? Gramine-SGX is able to load non-PIE executables into SGX enclaves, so what was wrong?
___
*[LibOS/shim/src/shim_rtld.c, line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/197#-Mo2gk7CBl0F9HRtOnAF:-Mo2gk7D06xaARxzWYX7:baf11rm) ([raw file](https://github.com/gramineproject/gramine/blob/c1eef7ac117ff4827c4ec619e711c3f11cc1316c/LibOS/shim/src/shim_rtld.c#L252)):*
> ```C
> 
>         if ((ret = file->fs->fs_ops->mmap(file, &map_start, map_size, c->prot, map_flags,
>                                           c->map_off)) < 0) {
> ```

Oops :) I thought GCC/Clang warnings would catch this blooper.


<!-- Sent from Reviewable.io -->

2021-11-09 08:34 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/197)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/197#-Mo2gGB0CTO7X8opGqBb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So ASan and UBSan only work on PIE executables? I can't believe this. What was the exact problem? Or is it not about ASan/UBSan, but the what? Gramine-SGX is able to load non-PIE executables into SGX enclaves, so what was wrong?
</blockquote></details>

No, this is not about ASan/UBSan. Gramine-SGX is able to load a non-PIE executable, but only with `sgx.nonpie_executable = true` manifest option (otherwise, the enclave usually starts at too high address). I thought that forcing PIE would be a better solution than adding a manifest option.


<!-- Sent from Reviewable.io -->

2021-11-09 08:49 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/197)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/197#-Mo2gGB0CTO7X8opGqBb):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No, this is not about ASan/UBSan. Gramine-SGX is able to load a non-PIE executable, but only with `sgx.nonpie_executable = true` manifest option (otherwise, the enclave usually starts at too high address). I thought that forcing PIE would be a better solution than adding a manifest option.
</blockquote></details>

Ah, I understand now.

1. Building with Clang results in non-PIE executable (by default).
2. A non-PIE executable requires `sgx.nonpie_executable = true` in the manifest.
3. We only hit this problem now because this is the first time we try to build CI-Examples with Clang. Not relevant to sanitizers at all.


<!-- Sent from Reviewable.io -->

2021-11-09 17:49 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/197)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/shim_rtld.c, line 252 at r1](https://reviewable.io/reviews/gramineproject/gramine/197#-Mo2gk7CBl0F9HRtOnAF:-Mo4oNF46ah64KiTzta-:b-tqg2tj) ([raw file](https://github.com/gramineproject/gramine/blob/c1eef7ac117ff4827c4ec619e711c3f11cc1316c/LibOS/shim/src/shim_rtld.c#L252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops :) I thought GCC/Clang warnings would catch this blooper.
</blockquote></details>

That's why I dislike assignments inside IF.


<!-- Sent from Reviewable.io -->

2021-11-10 14:54 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/197)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-10 14:59 UTC, merged