[LibOS] Introduce `sys.fds.limit` manifest option
gramineproject/gramine pull request #1973
Opened 2024-08-14 09:33 UTC by dimakuv

## Description of the changes 

This manifest option allows to modify the original `RLIMIT_NOFILE` resource limit. There is *no* way to propagate this limit from the host; this is a deliberate design choice.

See discussion in https://github.com/gramineproject/gramine/discussions/1964.

Fixes #1576.

## How to test this PR? 

Added two LibOS tests.

2024-08-15 01:03 UTC, mkow requested changes
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: 2 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/manifest-syntax.rst` line 322 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4IY2bB2Cf1CnFA87tP:-O4IY2bB2Cf1CnFA87tQ:bfuvzvf) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/manifest-syntax.rst#L322)):*
> ```reStructuredText
> 
> This specifies the maximum number of open file descriptors in the Gramine
> process. More specifically, this is equivalent to the ``RLIMIT_NOFILE`` resource
> ```

"equivalent" sounds like "this works same as that", while this _is_ the `RLIMIT_NOFILE`. I.e. we should make it clear that this option sets that limit, so it will be visible to the app.



_Code quote:_
```reStructuredText
More specifically, this is equivalent to the ``RLIMIT_NOFILE`` resource
```
___
*[`Documentation/devel/features.md` line 2967 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4IYJtDDbk_MyJesjhN:-O4IYJtDDbk_MyJesjhO:b-rla745) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/devel/features.md#L2967)):*
> ```Markdown
> - `RLIMIT_NPROC` -- dummy, no limit by default
> - `RLIMIT_NOFILE` -- implemented, equal to `sys.fds.limit` {ref}`manifest option <sys-fds-limit>` by
>   default
> ```

Please wrap


<!-- Sent from Reviewable.io -->

2024-08-16 03:23 UTC, kailun-qin requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/rlimit_nofile.c` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4OCPEo5Uqv15v4m0fo:-O4OCPEo5Uqv15v4m0fp:b-vzdfk7) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/test/regression/rlimit_nofile.c#L10)):*
> ```C
> #include <sys/resource.h>
> #include <sys/stat.h>
> #include <sys/time.h>
> ```

Are all these headers required?


<!-- Sent from Reviewable.io -->

2024-08-19 07:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: 7 of 11 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 322 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4IY2bB2Cf1CnFA87tP:-O4dOEuI5sHngQCUHUC6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/manifest-syntax.rst#L322)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"equivalent" sounds like "this works same as that", while this _is_ the `RLIMIT_NOFILE`. I.e. we should make it clear that this option sets that limit, so it will be visible to the app.
</blockquote></details>

Done.
___
*[`Documentation/devel/features.md` line 2962 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4dOQGd2Ptg2mfd11nC:-O4dOQGd2Ptg2mfd11nD:bumasmw) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/devel/features.md#L2962)):*
> ```Markdown
> - `RLIMIT_DATA` -- implemented, affects `brk()` system call
> - `RLIMIT_STACK` -- dummy, equal to `sys.stack.size` {ref}`manifest option <stack-size>` by
>   default
> ```

To @mkow: see for example this wrapping
___
*[`Documentation/devel/features.md` line 2967 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4IYJtDDbk_MyJesjhN:-O4dOSmj4MY93L3sSaBu:buuj62d) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/devel/features.md#L2967)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap
</blockquote></details>

Wrap how? We have 100 chars per line here, and this second line (with `default`) is also wrapped correctly.
___
*[`libos/src/bookkeep/libos_handle.c` line 165 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4LPuH12bE3q2mq5rmO:-O4dOomy38tYSA4dUBeZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/src/bookkeep/libos_handle.c#L165)):*
> ```C
>     }
>     if (fds_limit_init64 < 0) {
>         log_error("'sys.fds.limit' = %ld is negative", fds_limit_init64);
> ```

Done.
___
*[`libos/src/sys/libos_getrlimit.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4LQ73y0RbWeAEZorG6:-O4dOwLE8f7RMNwY2SXg:b-wnfmk9) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/src/sys/libos_getrlimit.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This whole paragraph doesn't make much sense IMO. Gramine is like a VM, these limits concern the emulated world, why would the host matter? (especially that it may not be Linux in theory, and that there's no 1-1 mapping between in-Gramine FDs and host FDs/handles)
If you want, you can just remind here that Gramine is emulating Linux, so all the limits regard the world inside Gramine, but I'd skip this altogether.
</blockquote></details>

Done. Removed.
___
*[`libos/src/sys/libos_getrlimit.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4LR0WQ0_-bOaY376xh:-O4dRuPi7mku7rZ7JBRq:b-iiig3c) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/src/sys/libos_getrlimit.c#L28)):*
Done.

> Hmm, are we actually serializing the limits in checkpoints?

Good catch. We have it explicitly for `RLIMIT_DATA` (brk stuff): https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/libos/src/sys/libos_brk.c#L36-L40

It looks like `RLIMIT_STACK` is not used in the child process though; it seems to be always overwritten in `init_stack()`: https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/libos/src/libos_init.c#L292

I created a separate issue for `RLIMIT_STACK` bug: https://github.com/gramineproject/gramine/issues/1974
___
*[`libos/src/sys/libos_getrlimit.c` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4dUbO9D4ZwQRpaBP9W:-O4dUbO9D4ZwQRpaBP9X:b-ox1317) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/src/sys/libos_getrlimit.c#L50)):*
> ```C
> #define MQ_BYTES_MAX    819200
> 
> static struct __kernel_rlimit64 __rlim[RLIM_NLIMITS] __attribute_migratable = {
> ```

@mkow Notice how these resource limits are `__attribute_migratable`, so they will be checkpointed and migrated to the child, where they will be restored. However, the `libos_init()` code may override them if we don't put additional checks in the corresponding code snippets.
___
*[`libos/test/regression/rlimit_nofile.c` line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4OCPEo5Uqv15v4m0fo:-O4dW7UAAfTMrbRsGx-E:b-a66vdd) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/test/regression/rlimit_nofile.c#L10)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Are all these headers required?
</blockquote></details>

Done. Removed some unused headers, added the ones needed for forking.


<!-- Sent from Reviewable.io -->

2024-08-19 10:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: 7 of 11 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`libos/test/regression/test_libos.py` line 1073 at r2](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4e5cns6uHI3R6ZjRSN:-O4e5cns6uHI3R6ZjRSO:b-o7b3qs) ([raw file](https://github.com/gramineproject/gramine/blob/8d4dfa3ed7617d6154ed82667443f8bf4181faa5/libos/test/regression/test_libos.py#L1073)):*
> ```Python
>         self.assertIn("(before setrlimit) opened fd: 899", stdout)
>         self.assertIn("new RLIMIT_NOFILE soft limit: 901", stdout)
>         self.assertIn("(after setrlimit) opened fd: 900", stdout)
> ```

I must also add the check on the line `(in child, after setrlimit) opened fd`
___
*[`libos/test/regression/test_libos.py` line 1082 at r2](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4e5fYnA7U5B7xRWAg_:-O4e5fYnA7U5B7xRWAga:b-o7b3qs) ([raw file](https://github.com/gramineproject/gramine/blob/8d4dfa3ed7617d6154ed82667443f8bf4181faa5/libos/test/regression/test_libos.py#L1082)):*
> ```Python
>         self.assertIn("(before setrlimit) opened fd: 4095", stdout)
>         self.assertIn("new RLIMIT_NOFILE soft limit: 4097", stdout)
>         self.assertIn("(after setrlimit) opened fd: 4096", stdout)
> ```

I must also add the check on the line `(in child, after setrlimit) opened fd`


<!-- Sent from Reviewable.io -->

2024-08-19 10:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: 7 of 11 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/sys/libos_getrlimit.c` line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4LR0WQ0_-bOaY376xh:-O4eD11F8nlQFrrHeYK7:b-xxl56p) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/src/sys/libos_getrlimit.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

> Hmm, are we actually serializing the limits in checkpoints?

Good catch. We have it explicitly for `RLIMIT_DATA` (brk stuff): https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/libos/src/sys/libos_brk.c#L36-L40

It looks like `RLIMIT_STACK` is not used in the child process though; it seems to be always overwritten in `init_stack()`: https://github.com/gramineproject/gramine/blob/4a73025f5bf66b86362113ff8e9e9946d5af071f/libos/src/libos_init.c#L292

I created a separate issue for `RLIMIT_STACK` bug: https://github.com/gramineproject/gramine/issues/1974
</blockquote></details>

FYI: https://github.com/gramineproject/gramine/pull/1976


<!-- Sent from Reviewable.io -->

2024-08-20 23:16 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`Documentation/devel/features.md` line 2967 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4IYJtDDbk_MyJesjhN:-O4m2Qx38w0QS57XRhxo:b3hhz04) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/Documentation/devel/features.md#L2967)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrap how? We have 100 chars per line here, and this second line (with `default`) is also wrapped correctly.
</blockquote></details>

Oh wait, those `-` mislead me, it's good already.
___
*[`libos/test/regression/rlimit_nofile.c` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4m3CKw2bMtCDRNm5j7:-O4m3CKw2bMtCDRNm5j8:bdsvu8r) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/test/regression/rlimit_nofile.c#L4)):*
> ```C
> /* Copyright (C) 2024 Intel Corporation */
> 
> #include <err.h>
> ```

But you're using `errx()`, so this header is needed.


<!-- Sent from Reviewable.io -->

2024-08-21 07:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: 9 of 11 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/rlimit_nofile.c` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4m3CKw2bMtCDRNm5j7:-O4nX1RmAMeL72ZUloH_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be90a36056f59bdbedbeef63fe53ba9c8d817a12/libos/test/regression/rlimit_nofile.c#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you're using `errx()`, so this header is needed.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1073 at r2](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4e5cns6uHI3R6ZjRSN:-O4nXJw_1vkhk7xS1tKt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d4dfa3ed7617d6154ed82667443f8bf4181faa5/libos/test/regression/test_libos.py#L1073)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I must also add the check on the line `(in child, after setrlimit) opened fd`
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1082 at r2](https://reviewable.io/reviews/gramineproject/gramine/1973#-O4e5fYnA7U5B7xRWAg_:-O4nXKJQExDlJFrZq5ie:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d4dfa3ed7617d6154ed82667443f8bf4181faa5/libos/test/regression/test_libos.py#L1082)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I must also add the check on the line `(in child, after setrlimit) opened fd`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-26 10:21 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-08-26 12:02 UTC, kailun-qin approved these changes
> Reviewed 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-26 12:22 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-26 12:28 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1973)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-27 08:38 UTC, woju commented
Jenkins, test Jenkins-20.04 please

2024-08-27 09:33 UTC, woju commented
Jenkins, test Jenkins-SGX-Sanitizers please

2024-08-27 09:33 UTC, woju commented
Jenkins, test Jenkins-SGX-20.04-musl please

2024-08-27 10:50 UTC, merged