[python] `gramine-manifest`: error out on manifest check failure
gramineproject/gramine pull request #1975
Opened 2024-08-19 08:55 UTC by kailun-qin

## Description of the changes 

Any built-in manifest validation failure is now a hard error.

## How to test this PR? 

CI + manual testing w/ non-compliant manifests

2024-08-19 09:42 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-08-19 09:44 UTC, woju approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-20 23:08 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: all files reviewed, 2 unresolved discussions (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1975#-O4m1V245yN1WdcWJJXc):*
(for consistence with other commit messages)



_Suggestion:_
```
gramine-manifest: Error out on manifest check failure
```
___
*[`python/gramine-manifest` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1975#-O4m1lhb3YCyOsZN8UM7:-O4m1lhb3YCyOsZN8UM8:b8cmtld) ([raw file](https://github.com/gramineproject/gramine/blob/068699703eebc340df94bcb9d97ebf568bba65a1/python/gramine-manifest#L48)):*
> ```
>             manifest.check()
>         except voluptuous.MultipleInvalid as err:
>             click.echo(f'ERROR: failed to validate manifest (after rendering): {err!s}', err=True)
> ```

I think the old wording sounds a bit like the validation process itself failed, not that the result is negative.



_Suggestion:_
```
ERROR: manifest doesn\'t validate
```


<!-- Sent from Reviewable.io -->

2024-08-21 02:20 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1975#-O4m1V245yN1WdcWJJXc):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(for consistence with other commit messages)
</blockquote></details>

Done.
___
*[`python/gramine-manifest` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1975#-O4m1lhb3YCyOsZN8UM7:-O4mhvC51OatasEI1dOn:b-wopq1m) ([raw file](https://github.com/gramineproject/gramine/blob/068699703eebc340df94bcb9d97ebf568bba65a1/python/gramine-manifest#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the old wording sounds a bit like the validation process itself failed, not that the result is negative.
</blockquote></details>

I make "manifest" the subject of the sentence (hope it's clearer). Note that the error details are appended, e.g., `ERROR: manifest failed validation: extra keys not allowed....`.


<!-- Sent from Reviewable.io -->

2024-08-21 06:38 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`python/gramine-manifest` line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/1975#-O4m1lhb3YCyOsZN8UM7:-O4ne2At7fm7id59br07:bj2x8st) ([raw file](https://github.com/gramineproject/gramine/blob/068699703eebc340df94bcb9d97ebf568bba65a1/python/gramine-manifest#L48)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I make "manifest" the subject of the sentence (hope it's clearer). Note that the error details are appended, e.g., `ERROR: manifest failed validation: extra keys not allowed....`.
</blockquote></details>

that's also a good fix :)


<!-- Sent from Reviewable.io -->

2024-08-21 08:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1975)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-21 08:16 UTC, merged