[LibOS] Fix bug of `RLIMIT_STACK` being overwritten in child
gramineproject/gramine pull request #1976
Opened 2024-08-19 10:35 UTC by dimakuv

## Description of the changes 

Previously, the resource limit `RLIMIT_STACK` (maximum size of the process stack, in bytes) was overwritten in the child process, after fork. Thus, if the parent used `setrlimit(RLIMIT_STACK)`, the effect of this was lost in the child. This PR fixes this bug, and adds a LibOS test to verify the correct behavior.

Fixes #1974.

Noticed while reviewing #1973.

## How to test this PR? 

New LibOS test was added.

2024-08-19 10:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1976#-O4eCN0G5BBXB09RdYJm:-O4eCN0G5BBXB09RdYJn:b39qhvr) (no related file):*
This PR is based on top of #1973, thus requires that one to be merged first.

___
___
*[`libos/src/libos_init.c` line 303 at r1](https://reviewable.io/reviews/gramineproject/gramine/1976#-O4eCTz_-hFozyY-FrRl:-O4eCTza9oNx42GnlOsj:b-k17ojd) ([raw file](https://github.com/gramineproject/gramine/blob/e4de968c01b1ea03a0d7ff0209004104dc17f824/libos/src/libos_init.c#L303)):*
> ```C
>         return 0;
> 
>     stack_size = ALLOC_ALIGN_UP(stack_size);
> ```

Note that stack size doesn't need to be aligned when setting the resource limit `RLIMIT_STACK`. That's what Linux does -- it doesn't silently adjust the stack size, instead Linux just writes whatever stack size the user supplies to it.

Thus I moved this alignment of the stack further down in this function.


<!-- Sent from Reviewable.io -->

2024-10-08 16:14 UTC, efu39 reviewed
Reviewed and looks good to me.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976#-:-O8gtxwTB0hatd4mHa3Y:b-vytirp)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-10-30 02:10 UTC, kailun-qin requested changes
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/test/regression/rlimit_stack.c` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAQAFmb48J7RkAMw_IA:-OAQAFmb48J7RkAMw_IB:byquu61) ([raw file](https://github.com/gramineproject/gramine/blob/f9de8b11e8db526da0df3c3da0ca46fe7b98ba2b/libos/test/regression/rlimit_stack.c#L5)):*
> ```C
> 
> #include <errno.h>
> #include <fcntl.h>
> ```

Do we need this?



_Code quote:_
```C
#include <fcntl.h>
```
___
*[`libos/test/regression/rlimit_stack.manifest.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAQ7Z5N1OoFdtBSDDt3:-OAQ7Z5N1OoFdtBSDDt4:byquu61) ([raw file](https://github.com/gramineproject/gramine/blob/f9de8b11e8db526da0df3c3da0ca46fe7b98ba2b/libos/test/regression/rlimit_stack.manifest.template#L16)):*
> ```
> sgx.debug = true
> sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
> sgx.use_exinfo = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
> ```

Do we need this?



_Code quote:_
```
sgx.use_exinfo = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}
```


<!-- Sent from Reviewable.io -->

2024-10-30 08:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @efu39 and @kailun-qin)

___
*[`libos/test/regression/rlimit_stack.c` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAQAFmb48J7RkAMw_IA:-OART_WFEYrcpcTNJH6N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f9de8b11e8db526da0df3c3da0ca46fe7b98ba2b/libos/test/regression/rlimit_stack.c#L5)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Done.
___
*[`libos/test/regression/rlimit_stack.manifest.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAQ7Z5N1OoFdtBSDDt3:-OARU7S10N-drM2ssMFO:b-ymzz1e) ([raw file](https://github.com/gramineproject/gramine/blob/f9de8b11e8db526da0df3c3da0ca46fe7b98ba2b/libos/test/regression/rlimit_stack.manifest.template#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Done. You're right, not required.


<!-- Sent from Reviewable.io -->

2024-10-30 14:25 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-10-30 14:43 UTC, dimakuv commented
Jenkins, retest pkg-apk-alpine3.17 please

2024-10-30 23:53 UTC, mkow requested changes
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`libos/test/regression/rlimit_stack.c` line 18 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUoiSw2dGawowl3eb3:-OAUoiSw2dGawowl3eb4:bbvidh1) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L18)):*
> ```C
>     CHECK(getrlimit(RLIMIT_STACK, &rlim));
>     printf("old RLIMIT_STACK soft limit: %lu\n", (uint64_t)rlim.rlim_cur);
>     uint64_t old_lim = (uint64_t)rlim.rlim_cur;
> ```

Just delete this and use `rlim.rlim_cur` directly in the IF?
___
*[`libos/test/regression/rlimit_stack.c` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUooHP1L4Eokwmzul4:-OAUooHP1L4Eokwmzul5:b-ch72iu) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L21)):*
> ```C
> 
>     /* make sure we can increase the current soft limit */
>     if (old_lim >= (uint64_t)rlim.rlim_max)
> ```

Why the cast here?



_Code quote:_
```C
(uint64_t)
```
___
*[`libos/test/regression/rlimit_stack.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUpl0cCkjLpPV1tbI4:-OAUpl0d3Cy4Q7wOAdF9:b-v1ecg9) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L39)):*
> ```C
>         /* NOTE: we currently don't test that the stack limit is indeed enforced */
>         exit(0);
>     } else {
> ```

Why is some part of the code inside `else` block and some outside? Both always execute together.
___
*[`libos/test/regression/test_libos.py` line 1103 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUo8pb1w0ABHNIPR9R:-OAUo8pb1w0ABHNIPR9S:b-do81uo) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/test_libos.py#L1103)):*
> ```Python
>         self.assertIn("TEST OK", stdout)
> 
>     def test_165_rlimit_stack(self):
> ```

Or maybe I'm missing something?



_Suggestion:_
```Python
def test_162_rlimit_stack(self):
```


<!-- Sent from Reviewable.io -->

2024-10-31 17:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: 5 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/test/regression/rlimit_stack.c` line 18 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUoiSw2dGawowl3eb3:-OAYaki4CEdf-Oz8APzR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just delete this and use `rlim.rlim_cur` directly in the IF?
</blockquote></details>

Done.
___
*[`libos/test/regression/rlimit_stack.c` line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUooHP1L4Eokwmzul4:-OAYal1RChSQJmX-4Izp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why the cast here?
</blockquote></details>

Done.
___
*[`libos/test/regression/rlimit_stack.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUpl0cCkjLpPV1tbI4:-OAYalMk4Xr7Ce61YMO4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/rlimit_stack.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is some part of the code inside `else` block and some outside? Both always execute together.
</blockquote></details>

Done.
___
*[`libos/test/regression/test_libos.py` line 1103 at r3](https://reviewable.io/reviews/gramineproject/gramine/1976#-OAUo8pb1w0ABHNIPR9R:-OAYb1gy9EkSa1KAiCaH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3258c9ee388f2a025214d886f29e1fb0d2f0089d/libos/test/regression/test_libos.py#L1103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Or maybe I'm missing something?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-31 17:50 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-10-31 17:54 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-10-31 22:43 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-10-31 23:20 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1976)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-31 23:21 UTC, merged