[LibOS] Add missing locks around dentry->inode dereference
gramineproject/gramine pull request #1978
Opened 2024-08-22 18:49 UTC by g2flyer

## Description of the changes 

This fixes two cases where a dentry->inode derefernce was not lock-protected.  It also adds a missing call to `put_handle` during error handling and (in a separate commit) removes an unused function.

## How to test this PR? 

Usual regression tests ...

2024-08-27 08:10 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1978)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HscZi1D1LLGNnZZxU):*
Would be better to also specify in which function exactly: `in libos_syscall_fchdir() func.`
___
*[`libos/include/libos_process.h` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HrQbk6Ux-JfiXWXIK:-O5Hqk8TEEqyKjfeg9Y0:bcqr9nn) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/include/libos_process.h#L65)):*
> ```objc
> 
>     struct libos_lock children_lock;
>     struct libos_lock fs_lock; /* Note: has lower priority than g_dcache_lock. */
> ```

This is confusing wording, I would prefer a longer description:
```
    struct libos_lock children_lock;

    /* If g_dcache_lock is also required, acquire g_dcache_lock first and then fs_lock */
    struct libos_lock fs_lock;

```
___
*[`libos/src/sys/libos_getcwd.c` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5Hrk9c4u6MoEovFqRy:-O5Hrk9c4u6MoEovFqRz:ba1ue2i) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/src/sys/libos_getcwd.c#L85)):*
> ```C
>         return -EBADF;
> 
>     int ret = 0;
> ```

It's better to do like this:
```
    int ret;
    lock(&g_dcache_lock);
    ...
    ...
    ret = 0;
out:
    ...
```

This way the GCC compiler has more opportunities to detect uninitialized `ret` on code paths.
___
*[`libos/src/sys/libos_open.c` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HsIMF9WyI-GFqFN7W:-O5HsIMF9WyI-GFqFN7X:b-y2afsz) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/src/sys/libos_open.c#L377)):*
> ```C
> 
>     lock(&g_dcache_lock);
>     if (!hdl->dentry->inode) {
> ```

Is it possible that `hdl->dentry == NULL` here? Don't we want to error out on this condition too?


<!-- Sent from Reviewable.io -->

2024-08-27 21:24 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1978)* status: 2 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HscZi1D1LLGNnZZxU):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Would be better to also specify in which function exactly: `in libos_syscall_fchdir() func.`
</blockquote></details>

Done.
___
*[`libos/include/libos_process.h` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HrQbk6Ux-JfiXWXIK:-O5Ke4S531ARrqZPg0eD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/include/libos_process.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is confusing wording, I would prefer a longer description:
```
    struct libos_lock children_lock;

    /* If g_dcache_lock is also required, acquire g_dcache_lock first and then fs_lock */
    struct libos_lock fs_lock;

```
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_getcwd.c` line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5Hrk9c4u6MoEovFqRy:-O5KeL6W-PRWSNzE3XI1:bs79go2) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/src/sys/libos_getcwd.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's better to do like this:
```
    int ret;
    lock(&g_dcache_lock);
    ...
    ...
    ret = 0;
out:
    ...
```

This way the GCC compiler has more opportunities to detect uninitialized `ret` on code paths.
</blockquote></details>

There shouldn't be unitialized with above ;-)  But i see what you mean, makes sense as it can be easily overlooked to redefine it in error case.
___
*[`libos/src/sys/libos_open.c` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5HsIMF9WyI-GFqFN7W:-O5Kf5iJ5NE2x21e0UXp:b-q2c0sa) ([raw file](https://github.com/gramineproject/gramine/blob/90e907d9b00dd30fd1f26cb22a71dedc269bde20/libos/src/sys/libos_open.c#L377)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it possible that `hdl->dentry == NULL` here? Don't we want to error out on this condition too?
</blockquote></details>

In this version, hdl->dentry should still be immutable (and defined), this becomes only an issue in PR #1979 but even in that case it should always be defined


<!-- Sent from Reviewable.io -->

2024-09-01 16:32 UTC, mkow approved these changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1978)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5FctmqDqbYjyC3Ey_2:-O5FctmqDqbYjyC3Ey_3:by4gqgw) (no related file):*
TODO for myself: check commit split after the final rebase.

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5Fd1Qr0fvPubO9-sC0):*




_Suggestion:_
```
Remove an unused function
```
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5FeovS0nAVbXCxQWSY):*
nitpick: that's how we usually write such notes



_Suggestion:_
```
  Also fixes one missing call to put_handle in error handling
```
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5iHdJoD8nkDKByPQms):*
But: the places you wrapped in the lock here are _not_ dereferencing the `inode` pointer.



_Suggestion:_
```
dereferences
```


<!-- Sent from Reviewable.io -->

2024-09-03 06:31 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1978)* status: all files reviewed, 5 unresolved discussions (waiting on @g2flyer and @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5Fd1Qr0fvPubO9-sC0):*
Done
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5FeovS0nAVbXCxQWSY):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: that's how we usually write such notes
</blockquote></details>

Done
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5iHdJoD8nkDKByPQms):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But: the places you wrapped in the lock here are _not_ dereferencing the `inode` pointer.
</blockquote></details>

Done. Changed to `accesses`.
___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/gramineproject/gramine/1978#-O5Rxm-MBi0Gddsi88EX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Misses a verb, should be `[LibOS] Add missing lock ...`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-03 06:32 UTC, dimakuv commented
Jenkins, test this please

2024-09-03 09:36 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-EDMM please (PCCS cache is reactivated)

2024-09-03 15:16 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-03 17:58 UTC, merged