Fix tampering tests for protected files
gramineproject/gramine pull request #1980
Opened 2024-08-23 19:05 UTC by g2flyer

## Description of the changes 

Test `test_500_invalid` always failed as test files to decrypt _always_ had an illegal filename masking the actual intended tampering.   Fixing this in `libos/test/fs/test_enc.py` showed that a number of intended tampering use-cases in fact were uncatchable.  This PR fixes the file path in the test driver `test_nec.py`, removes ineffective tampering use-cases and adds some tampering with ciphertext on headers.

The PR also (in a separate commit) improves debuggability of python tests by optionally allow to skip the teardown of the test artifacts and run all tests for 500 instead of aborting on first failure.

## How to test this PR? 

Run usual regression tests

2024-08-26 14:48 UTC, omeg reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer)

___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 353 at r1](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5E90ZHEn1kQ3j5yh9s:-O5E90ZIDDOdSwz_i7Uj:bjzb5st) ([raw file](https://github.com/gramineproject/gramine/blob/4380c2e7eda83414ea80a56d0a375de94eee0737/tools/sgx/pf_tamper/pf_tamper.c#L353)):*
> ```C
>     /* Note: we do not test generally whether file is longer than meta_dec_file indicates, in
>      * particular we do not test it for the case where the header says it is empty.  So test only
>      * size modification which interfer with the mht tree but not with meta_dec->file_size = 0. */
> ```

modifications which interfere



_Code quote:_
```C
modification which interfer
```


<!-- Sent from Reviewable.io -->

2024-08-26 21:05 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @omeg)

___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 353 at r1](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5E90ZHEn1kQ3j5yh9s:-O5FVSwqByJa20zKyXaP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4380c2e7eda83414ea80a56d0a375de94eee0737/tools/sgx/pf_tamper/pf_tamper.c#L353)):*
<details><summary><i>Previously, omeg (Rafał Wojdyła) wrote…</i></summary><blockquote>

modifications which interfere
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-27 07:43 UTC, omeg reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-O5HmOU99UtgVfZlF8cv:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-27 07:53 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

___
*[`libos/test/fs/conftest.py` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HkoK95mmjKw-ZinAq:-O5HkoK95mmjKw-ZinAr:b-gxggqd) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/conftest.py#L6)):*
> ```Python
> 
> def pytest_addoption(parser):
>     parser.addoption("--skip-teardown", action='store_true')
> ```

This is quite useful, thanks!
___
*[`libos/test/fs/conftest.py` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmEhi0xJw-MuHbw2q:-O5HmEhi0xJw-MuHbw2r:bqrx9no) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/conftest.py#L6)):*
> ```Python
> 
> def pytest_addoption(parser):
>     parser.addoption("--skip-teardown", action='store_true')
> ```

Could you mention this flag in the README: https://github.com/gramineproject/gramine/blob/master/libos/test/fs/README.md?plain=1
___
*[`libos/test/fs/test_enc.py` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Hllca9HbcMcEPYYHE:-O5Hllca9HbcMcEPYYHF:bo4j2bz) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L180)):*
> ```Python
> 
>         # prepare valid encrypted file (largest one for maximum possible corruptions)
>         original_input = self.OUTPUT_FILES[-1]
> ```

Can we rename `original_input` to `input_path`? It's hard to read this code, too many variables.
___
*[`libos/test/fs/test_enc.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HkJP4BQxD7sD9T5QB:-O5HkJP5BllV7ORQSu14:b-1mtfy1) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L182)):*
> ```Python
>         original_input = self.OUTPUT_FILES[-1]
>         self.__encrypt_file(self.INPUT_FILES[-1], original_input)
>         shutil.copy(original_input, original_input+".save") # Save for debugging as we overwrite original below
> ```

Exceeds 100 char-per-line limit, please move the comment line above the code line
___
*[`libos/test/fs/test_enc.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HkQOU6nxBDJWEphad:-O5HkQOU6nxBDJWEphae:b-52geh1) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L182)):*
> ```Python
>         original_input = self.OUTPUT_FILES[-1]
>         self.__encrypt_file(self.INPUT_FILES[-1], original_input)
>         shutil.copy(original_input, original_input+".save") # Save for debugging as we overwrite original below
> ```

Isn't a more conventional extension `.orig`?
___
*[`libos/test/fs/test_enc.py` line 189 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Hm-THE1gZv06Ndd7_:-O5Hm-THE1gZv06Ndd7a:br2bj9s) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L189)):*
> ```Python
>         failed = False
>         for name in os.listdir(invalid_dir):
>             invalid = os.path.join(invalid_dir, name)
> ```

Please rename `invalid` to `invalid_path`
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmWYE4O-X16abrcIO:-O5HmWYE4O-X16abrcIP:b6qkswd) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L217)):*
> ```C
>     /* Note: as mentioned below in tamper_modify() for meta_dec.file_size, we mostly allow the
>      * actual file to be longer than what the header size, the only thing we require is that the
>      * file size is a multiple of PF_NODE_SIZE, so just verify this */
> ```

Confusing...

- Why do you say `mostly allow`? What is the condition when this is disallowed?
- By `we` do you mean `Gramine's encrypted filesystem`?
- `than what the header size` -- do you mean `that what is specified in the header's file size`?
- `just verify this` -- who verifies what? How is this related to this particular code here?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 274 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmwmaB9HPvPhkdHyx:-O5HmwmaB9HPvPhkdHyy:b-6po6wy) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L274)):*
> ```C
> 
> /* if update is true, also create a file with correct metadata MAC */
> #define BREAK_PLN(suffix, update, ...)                                                   \
> ```

What does `PLN` stand for? "Plaintext"? Could you please add some quick comments what each of these macros does?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 327 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HnLwbEQ3igPyDn_1g:-O5HnLwbEQ3igPyDn_1h:bh5i4es) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L327)):*
> ```C
>     BREAK_PLN("meta_plain_version_1", /*update=*/false,
>               { meta->plaintext_part.major_version = 0xff; });
>     /* Note: we only test (equality) on major version but nothing about minor_version, so no
> ```

`we` -> `Gramine's encrypted filesystem`
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HnEEy4B_-Yu3zDSAN:-O5HnEEy4B_-Yu3zDSAO:b-12rqvc) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L328)):*
> ```C
>               { meta->plaintext_part.major_version = 0xff; });
>     /* Note: we only test (equality) on major version but nothing about minor_version, so no
>      * point in tampering with meta->plaintext_part.minor_version ... */
> ```

No need for `...` at the end, it only makes the reader stop and wonder if there's some text missing.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 354 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HoPow4S7WGqMSMP_B:-O5HoPox5u-tayRQwg2s:br2jk0s) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L354)):*
> ```C
>      * particular we do not test it for the case where the header says it is empty.  So test only
>      * size modifications which interfere with the mht tree but not with meta_dec->file_size = 0. */
>     BREAK_DEC("meta_enc_size_0",    { meta_dec->file_size = g_input_size - PF_NODE_SIZE; });
> ```

Could you explain why for example this file size breaks? Isn't it less than the real file size, which is *not* caught (ignored) by Gramine's encrypted filesystem?
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 364 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HofP_1aCsFppHSII8:-O5HofP_1aCsFppHSII9:b-12rqvc) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L364)):*
> ```C
>     BREAK_DEC("meta_enc_mht_mac_1", { LAST_BYTE(meta_dec->root_mht_node_mac) ^= 0xfe; });
>     /* Note: no poing in tampering with (decrypted) meta_dec->file_data as there is no way to
>      * detect such tampering, the re-encryption would turn it in authentic (different) data .... */
> ```

No need for `...` at the end, it only makes the reader stop and wonder if there's some text missing.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 366 at r2](https://reviewable.io/reviews/gramineproject/grami [...]

2024-08-27 19:50 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: 2 of 5 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @omeg)

___
*[`libos/test/fs/conftest.py` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmEhi0xJw-MuHbw2q:-O5KEI-y1xXjCvBZs6KO:b-l4yggl) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/conftest.py#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you mention this flag in the README: https://github.com/gramineproject/gramine/blob/master/libos/test/fs/README.md?plain=1
</blockquote></details>

Good idea, done
___
*[`libos/test/fs/test_enc.py` line 180 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Hllca9HbcMcEPYYHE:-O5KGGS92uAw72FDYR8k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename `original_input` to `input_path`? It's hard to read this code, too many variables.
</blockquote></details>

Done.
___
*[`libos/test/fs/test_enc.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HkQOU6nxBDJWEphad:-O5KFIEO8gn5qdEfAn9d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't a more conventional extension `.orig`?
</blockquote></details>

Done.
___
*[`libos/test/fs/test_enc.py` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HkJP4BQxD7sD9T5QB:-O5KFJ1P0YyJPzqCd9RZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Exceeds 100 char-per-line limit, please move the comment line above the code line
</blockquote></details>

Done.
___
*[`libos/test/fs/test_enc.py` line 189 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Hm-THE1gZv06Ndd7_:-O5KGVxiCwRUlqiffJC5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/libos/test/fs/test_enc.py#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `invalid` to `invalid_path`
</blockquote></details>

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmWYE4O-X16abrcIO:-O5KIeW83iewQLOokTFV:b-wildl3) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Confusing...

- Why do you say `mostly allow`? What is the condition when this is disallowed?
- By `we` do you mean `Gramine's encrypted filesystem`?
- `than what the header size` -- do you mean `that what is specified in the header's file size`?
- `just verify this` -- who verifies what? How is this related to this particular code here?
</blockquote></details>

rephrased, hopefully clarifing it
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 274 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmwmaB9HPvPhkdHyx:-O5KJeUwABVFAhqTMySx:bl94ijy) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does `PLN` stand for? "Plaintext"? Could you please add some quick comments what each of these macros does?
</blockquote></details>

added a corresponding comment
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 327 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HnLwbEQ3igPyDn_1g:-O5KKjP5-7eA_j6GAeqK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L327)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`we` -> `Gramine's encrypted filesystem`
</blockquote></details>

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HnEEy4B_-Yu3zDSAN:-O5KKkIODmdCuDaUuxn8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L328)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `...` at the end, it only makes the reader stop and wonder if there's some text missing.
</blockquote></details>

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 354 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HoPow4S7WGqMSMP_B:-O5KL2wp9PqFtk9HWU4_:b-mwc3jl) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L354)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you explain why for example this file size breaks? Isn't it less than the real file size, which is *not* caught (ignored) by Gramine's encrypted filesystem?
</blockquote></details>

Good question. I was wondering myself and after (admittedly very quick investigation) couldn't immediately get a firm explanation.   As it was one of the second-level of defense reliability tests and not an adverserial attack, i gave up with the vague intuition that probably some inviarient in the meta-data vs data node vs data in header filling was violated ...
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 364 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HofP_1aCsFppHSII8:-O5KMkaS6Kd5z2_2RJMA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L364)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `...` at the end, it only makes the reader stop and wonder if there's some text missing.
</blockquote></details>

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 366 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Hok3U6yt4HB3AYEoq:-O5KN0mf7cQBVRd80A7M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L366)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`meta.padding` -> `meta->padding` (for consistency with other comments)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-29 07:08 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @g2flyer)

___
*[`libos/test/fs/README.md` line 22 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RscAyB7zgIidGjhwJ:-O5RscAyB7zgIidGjhwK:b-r0b3jx) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/libos/test/fs/README.md#L22)):*
> ```Markdown
> 
> Encrypted file tests assume that Gramine was built with SGX enabled (see comment
> in `test_enc.py`). 
> ```

Accidental trailing space, please remove
___
*[`libos/test/fs/README.md` line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RsoO-CkeyKL6HMbfL:-O5RsoO03GewuKzttQLo:bz585in) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/libos/test/fs/README.md#L27)):*
> ```Markdown
> pytest option `--skip-teardown` which prevents the removal of generated test
> files (in sub-directory `tmp`) and  allows to easily replicate and investigate 
> manually the test scenarios, e.g., with help of `gdb`.
> ```

A bit better rewording:
```
This test suite automatically creates files-under-test on startup and removes
them afterwards. When some test fails and you want to debug this failure, it's
more convenient to skip this automatic removal of files (and manually
investigate the test scenario, e.g. with the help of GDB). In such cases, use
the pytest option `--skip-teardown`.
```
___
*[`libos/test/fs/test_enc.py` line 183 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RtsbmBq4vAU9vib1p:-O5RtsbmBq4vAU9vib1q:br5pij4) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/libos/test/fs/test_enc.py#L183)):*
> ```Python
>         self.__encrypt_file(self.INPUT_FILES[-1], input_path)
>         # Save for debugging as we overwrite original below
>         shutil.copy(input_path, input_path+".orig")
> ```

```diff
- shutil.copy(input_path, input_path+".orig")
+ shutil.copy(input_path, input_path + '.orig')
```
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 217 at r2](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5HmWYE4O-X16abrcIO:-O5RuEQfEsj3Wjcr-0w3:b-3horpe) ([raw file](https://github.com/gramineproject/gramine/blob/a35c2d32924dba80d714238819c7d67827d0f347/tools/sgx/pf_tamper/pf_tamper.c#L217)):*
<details><summary><i>Previously, g2flyer (Michael Steiner) wrote…</i></summary><blockquote>

rephrased, hopefully clarifing it
</blockquote></details>

Thanks, this is now very clear!
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 274 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RuMcyBSw7UwhrzpuB:-O5RuMcyBSw7UwhrzpuC:bsunp0e) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L274)):*
> ```C
> } while (0)
> 
> /* Three different macros to tamper with a file
> ```

Please reformat like this (it's more common in our code base, and also easier to read imho):
```
/*
 * Three different macros ...
 * ...
 */
```
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 274 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RuV23AxEFDteXzjb0:-O5RuV23AxEFDteXzjb1:b-prml24) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L274)):*
> ```C
> } while (0)
> 
> /* Three different macros to tamper with a file
> ```

Please add `:` at the end of the sentence
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 276 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Ru_0c0UUMPGmRi8K7:-O5Ru_0c0UUMPGmRi8K8:bn70e7f) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L276)):*
> ```C
> /* Three different macros to tamper with a file
>  * - BREAK_PLN: tamper with the plaintext part of the metadata.
>  * - BREAK_DEC: tamper with the decrypted part of the metadata and re-encrypted it.
> ```

`re-encrypt` (no past tense)
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 278 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5RuhXdDlEaaUq-wefw:-O5RuhXdDlEaaUq-wefx:b-566g20) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L278)):*
> ```C
>  * - BREAK_DEC: tamper with the decrypted part of the metadata and re-encrypted it.
>  *   (Not something an adversary can do to attack the system but still tests overall reliability.)
>  * - BREAK_MHT: tamper with the MHT nodes
> ```

Please add `.` at the end of the sentence (for uniformity)
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 278 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Rulag65bakNYwv9nw:-O5Rulag65bakNYwv9nx:b5qcvfa) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L278)):*
> ```C
>  * - BREAK_DEC: tamper with the decrypted part of the metadata and re-encrypted it.
>  *   (Not something an adversary can do to attack the system but still tests overall reliability.)
>  * - BREAK_MHT: tamper with the MHT nodes
> ```

Please add a new empty line, to visually separate the list from the next paragraph.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 360 at r3](https://reviewable.io/reviews/gramineproject/gramine/1980#-O5Rwyf8-XaKigjzWN4l:-O5Rwyf8-XaKigjzWN4m:bpwcuwi) ([raw file](https://github.com/gramineproject/gramine/blob/4330b301fc1d0c0f306c34e849ef793023101f7b/tools/sgx/pf_tamper/pf_tamper.c#L360)):*
> ```C
>             '\0';  // shorten path by one character
>     });
>     /* Note: As mentioned above, Gramine's encrypted filesystem does not generally test whether a
> ```

Please remove `As mentioned above`, it was like 100 lines above, nobody will scroll to search for that place :)


<!-- Sent from Reviewable.io -->

2024-09-04 06:50 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-09-04 06:50 UTC, dimakuv commented
Jenkins, test this please

2024-11-15 17:17 UTC, mkow requested changes
Looks good, modulo some nitpicks. And sorry for the late review.

> Reviewed 2 of 4 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-OBkortjE4hrHnb6a-fi:bxi99a5)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkeVOtDUQcE6bZiE67:-OBkeVOtDUQcE6bZiE68:b-bfi7jb):*
Please add proper component tags to the commit one-liners.
___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkg2-M5mKUtQx-qv6d:-OBkg2-N0NBxGnuXfLd9:bmyzrg1):*
I guess that was the intended meaning? Or something else? I have problems understanding what you meant here.



_Suggestion:_
```
due to invalid path if didn't fail already due to plain text tampering)
```
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 359 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkoAMODzom1u-iJXRW:-OBkoAMODzom1u-iJXRX:b-h4e71y) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/tools/sgx/pf_tamper/pf_tamper.c#L359)):*
> ```C
>     BREAK_DEC("meta_enc_filename_0", { meta_dec->file_path[0] = 0; });
>     BREAK_DEC("meta_enc_filename_1", { meta_dec->file_path[0] ^= 1; });
>     BREAK_DEC("meta_enc_filename_2", {
> ```

please `assert(strlen(meta_dec->file_path) > 0)` before this test, just to be sure
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 364 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkoRl3Dw_yGZuoEdsK:-OBkoRl3Dw_yGZuoEdsL:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/tools/sgx/pf_tamper/pf_tamper.c#L364)):*
> ```C
>     });
>     /* Note: Gramine's encrypted filesystem does not generally test whether a file is longer than
>      * `meta_dec->file_size` indicates; in particular it does not test for the case where the header
> ```





_Suggestion:_
```C
what `meta_dec->file_size` indicates
```
___
*[`libos/test/fs/test_enc.py` line 182 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkiITW0cwOfWWwgcFh:-OBkiITW0cwOfWWwgcFi:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/libos/test/fs/test_enc.py#L182)):*
> ```Python
>         input_path = self.OUTPUT_FILES[-1]
>         self.__encrypt_file(self.INPUT_FILES[-1], input_path)
>         # Save for debugging as we overwrite original below
> ```





_Suggestion:_
```Python
# Save for debugging as we overwrite the original below
```


<!-- Sent from Reviewable.io -->

2024-11-18 20:37 UTC, g2flyer reviewed
I hope the change addresses your concerns.  Note I also rebased to the latest master to test against that version.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-OC-z82IEGa1TylhIUnp:b-gp3ezd)* status: 2 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @omeg)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkeVOtDUQcE6bZiE67:-OC-kphw1hs7Aw0MABmB:b-896fix):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add proper component tags to the commit one-liners.
</blockquote></details>

Done.
___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkg2-M5mKUtQx-qv6d:-OC-kqA81QbxwAO7L8kG:b-896fix):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess that was the intended meaning? Or something else? I have problems understanding what you meant here.
</blockquote></details>

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 359 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkoAMODzom1u-iJXRW:-OC-lRlQCF3lMoy8oiRg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/tools/sgx/pf_tamper/pf_tamper.c#L359)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please `assert(strlen(meta_dec->file_path) > 0)` before this test, just to be sure
</blockquote></details>

Done.
___
*[`libos/test/fs/test_enc.py` line 182 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkiITW0cwOfWWwgcFh:-OC-hvEU1VCceor6FPLJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/libos/test/fs/test_enc.py#L182)):*
> ```Python
>         input_path = self.OUTPUT_FILES[-1]
>         self.__encrypt_file(self.INPUT_FILES[-1], input_path)
>         # Save for debugging as we overwrite original below
> ```

Done.
___
*[`tools/sgx/pf_tamper/pf_tamper.c` line 364 at r4](https://reviewable.io/reviews/gramineproject/gramine/1980#-OBkoRl3Dw_yGZuoEdsK:-OC-mAeQ-B6GfPL8mFoY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3a50ad94b28fb0287a9d5f58122e77b8a9324886/tools/sgx/pf_tamper/pf_tamper.c#L364)):*
> ```C
>     });
>     /* Note: Gramine's encrypted filesystem does not generally test whether a file is longer than
>      * `meta_dec->file_size` indicates; in particular it does not test for the case where the header
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-19 20:16 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-11-20 04:43 UTC, kailun-qin approved these changes
Jenkins, test this please

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-OC6sZJ4-JbSFfjkMgcd:bkop2df)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-20 04:55 UTC, kailun-qin commented
Jenkins, test this please

2024-11-28 11:24 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-28 11:24 UTC, mkow commented
Jenkins, retest this please

2024-12-02 18:57 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1980#-OCmacEt49XubN9T8DV4:-OD7iaYx1GWOGWcDxR6Q:btuutaq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@g2flyer: I tested the PR manually on the first commit, using the `--skip-teardown` option, and the tests fail after a few of them:

```
[... all succeed up to here]
test_enc.py::TC_50_EncryptedFiles::test_500_invalid PASSED                                                                    [ 35%]
test_fs.py::TC_00_FileSystem::test_100_open_close ERROR                                                                       [ 37%]
[almost everything fails afterwards]
```

Example error:
```
______________________________________ ERROR at setup of TC_00_FileSystem.test_100_open_close _______________________________________
test_fs.py:27: in setUpClass
    os.mkdir(cls.TEST_DIR)
E   FileExistsError: [Errno 17] File exists: 'tmp'
```

btw. be careful when working on this PR, I already rebased it to the current master, so you'll need to fetch+reset before doing any changes.
</blockquote></details>

This is kindof "by design" -- it works only for an individual test case family and only on first time before environment cleanup ... -- but clearly was lacking a bit more information in the README, now added.


<!-- Sent from Reviewable.io -->

2024-12-04 00:38 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @g2flyer and @mkow)

___
*[`libos/test/fs/README.md` line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/1980#-ODE56qU-yk_mFl0Ix3t:-ODE56qU-yk_mFl0Ix3u:b7zf2hb) ([raw file](https://github.com/gramineproject/gramine/blob/bb1f8d43227dfa584dc2a52502a7eb9b874fb28b/libos/test/fs/README.md#L32)):*
> ```Markdown
> Module/TestCase family, i.e., `EncryptedFiles`, `FileSystem`, `Sync` and `Tmpfs`, and 
> (b) only for the first run. Otherwise, the lack of teardown will cause various errors 
> until you reset the test environment with a `rm -rf tmp`.  
> ```

Trailing white space?



_Code quote:_
```Markdown
··
```


<!-- Sent from Reviewable.io -->

2024-12-04 00:56 UTC, g2flyer reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @mkow)

___
*[`libos/test/fs/README.md` line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/1980#-ODE56qU-yk_mFl0Ix3t:-ODE9hlA0XM2I53rpT7j:b-xz3y34) ([raw file](https://github.com/gramineproject/gramine/blob/bb1f8d43227dfa584dc2a52502a7eb9b874fb28b/libos/test/fs/README.md#L32)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Trailing white space?
</blockquote></details>

yep, but no more ...


<!-- Sent from Reviewable.io -->

2024-12-04 02:08 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-12-12 19:12 UTC, mkow submitted a review, later dismissed
@woju: Could you please add @g2flyer to the CI whitelist?

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-ODwHF6z6HtYg5dbOrlL:b-x5425k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-12 19:12 UTC, mkow commented
Jenkins, retest this please

2024-12-13 15:14 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-12-13 15:45 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @g2flyer)

___
*[`libos/test/fs/README.md` line 31 at r10](https://reviewable.io/reviews/gramineproject/gramine/1980#-OE-gBfM6EXzYFwIiER9:-OE-gBfM6EXzYFwIiERA:b70vr4s) ([raw file](https://github.com/gramineproject/gramine/blob/e6e8d3122d8b3ea0319507a0890f46f3ec281f65/libos/test/fs/README.md#L31)):*
> ```Markdown
> (a) work successfully only when restricting tests (using option `-k`) to an individual
> Module/TestCase family, i.e., `EncryptedFiles`, `FileSystem`, `Sync` and `Tmpfs`, and
> (b) only for the first run. Otherwise, the lack of teardown will cause various errors
> ```

Sorry for seeing this late... What is the max line length we're following here? If it's 80 chars, then it exceeds the limit; if 100, then we should align for all lines.



_Code quote:_
```Markdown
(a) work successfully only when restricting tests (using option `-k`) to an individual
Module/TestCase family, i.e., `EncryptedFiles`, `FileSystem`, `Sync` and `Tmpfs`, and
(b) only for the first run. Otherwise, the lack of teardown will cause various errors
```


<!-- Sent from Reviewable.io -->

2024-12-13 15:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)

___
*[`libos/test/fs/README.md` line 31 at r10](https://reviewable.io/reviews/gramineproject/gramine/1980#-OE-gBfM6EXzYFwIiER9:-OE-id3-7xB8ZOp1dkpY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e6e8d3122d8b3ea0319507a0890f46f3ec281f65/libos/test/fs/README.md#L31)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sorry for seeing this late... What is the max line length we're following here? If it's 80 chars, then it exceeds the limit; if 100, then we should align for all lines.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-13 15:56 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-13 15:56 UTC, woju reviewed
@mkow
> Could you please add [@g2flyer](https://github.com/g2flyer) to the CI whitelist?

Done.

@g2flyer The pipelines are triggered either when you push, or when you write commit that matches the one of the regexps like this: `Jenkins, (re)?test (this|Jenkins-SGX-24\.04) please.*`. Other pipelines have its respective name in there, so you write either `this` to start everything or a particular one that failed, so it starts only one. (You can't restart proper subset of them in one message, if you want to restart 5 jobs, you need to write 5 comments).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1980#-:-OE-iGuK4JLQQH8ECGIB:b-10mypm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-19 14:42 UTC, merged