[LibOS] Move `print_warnings_on_insecure_configs()` to LibOS
gramineproject/gramine pull request #1986
Opened 2024-09-02 09:41 UTC by dimakuv

## Description of the changes 

Previously, `print_warnings_on_insecure_configs()` function was in Linux-SGX PAL. However, since almost all insecure manifest configurations are processed in the LibOS layer, it makes sense to move the printing of warnings about these configs from PAL to LibOS. This has an additional benefit of deduplicating this printing across all "confidential computing" PALs (currently there is only SGX, but in future Gramine may have TDX, AMD-SEV, etc.).

This is a recreation of #1984, rebased on top of current master (instead of `dimakuv/libos-allowed-and-trusted-files`).

Closes #1984.

## How to test this PR? 

CI is enough.

2024-09-02 10:48 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/libos_init.c` line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mKvee86LmbvnIxo0C:-O5mKvee86LmbvnIxo0D:bcn36ad) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/libos_init.c#L412)):*
> ```C
> 
>     ret = print_warnings_on_insecure_configs(!!g_pal_public_state->parent_process);
>     if (ret < 0) {
> ```

Why we need `ret`?
___
*[`libos/src/utils/warn.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mL51z6r_PxjCJKNz8:-O5mL52-3KwqdjGP3-Ht:bxx2k3t) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/utils/warn.c#L27)):*
> ```C
>     if (!manifest_fs_keys)
>         return false;
>     int ret = toml_table_nkval(manifest_fs_keys);
> ```

Do we need ret?

We might also do:
```
return ret > 0;
```


<!-- Sent from Reviewable.io -->

2024-09-02 11:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @oshogbo)

___
*[`libos/src/libos_init.c` line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mKvee86LmbvnIxo0C:-O5mPGCaDaZjzo-kULQA:b-kzglsy) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/libos_init.c#L412)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Why we need `ret`?
</blockquote></details>

What do you mean? What can we do instead? Just ignore the failure on this function? I don't think it's a good idea to ignore.
___
*[`libos/src/utils/warn.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mL51z6r_PxjCJKNz8:-O5mPLGc2uNhS8U_-Vrg:b8hirsb) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/utils/warn.c#L27)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Do we need ret?

We might also do:
```
return ret > 0;
```
</blockquote></details>

What do you mean by "do we need ret"? There can be legitimately zero keys in `fs.insecure__keys` array. Also, this is an external-library API (of the `libtomlc99` library), it can legitimately return some errors.

I agree with replacing to `return ret > 0`.


<!-- Sent from Reviewable.io -->

2024-09-02 15:04 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`libos/src/libos_init.c` line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mKvee86LmbvnIxo0C:-O5nFX2u0rUIcpjmembC:b-s86m98) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/libos_init.c#L412)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? What can we do instead? Just ignore the failure on this function? I don't think it's a good idea to ignore.
</blockquote></details>

Sorry, for not being precise.
Do we need ret variable?
Can't we just do:
```
if (print_warnings_on_insecure_configs(!!g_pal_public_state->parent_process) < 0)
```

As ret is never used.
___
*[`libos/src/utils/warn.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mL51z6r_PxjCJKNz8:-O5nFl2c9LOYIOvpg0s3:b-ddkypb) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/utils/warn.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by "do we need ret"? There can be legitimately zero keys in `fs.insecure__keys` array. Also, this is an external-library API (of the `libtomlc99` library), it can legitimately return some errors.

I agree with replacing to `return ret > 0`.
</blockquote></details>

The same - sorry for not being precise.
I meant do we need this variable, not do we need error checking? It's not used anywhere else.
We can do:
```
if (toml_table_nkval(manifest_fs_keys) <= 0)
   return false;
```

or we can change the return as we discussed.


<!-- Sent from Reviewable.io -->

2024-09-02 17:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/src/libos_init.c` line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mKvee86LmbvnIxo0C:-O5nsDd752-P-hHW84SG:bvddpc0) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/libos_init.c#L412)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sorry, for not being precise.
Do we need ret variable?
Can't we just do:
```
if (print_warnings_on_insecure_configs(!!g_pal_public_state->parent_process) < 0)
```

As ret is never used.
</blockquote></details>

Done. Got it now.
___
*[`libos/src/utils/warn.c` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mL51z6r_PxjCJKNz8:-O5nsYffD0E42p9DMPfY:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/utils/warn.c#L27)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The same - sorry for not being precise.
I meant do we need this variable, not do we need error checking? It's not used anywhere else.
We can do:
```
if (toml_table_nkval(manifest_fs_keys) <= 0)
   return false;
```

or we can change the return as we discussed.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-04 01:51 UTC, mkow requested changes
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 6 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @oshogbo)

___
*[`libos/include/libos_internal.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nLkGs3vvLVCqEjHzS:-O5nLkGs3vvLVCqEjHzT:bvch0qj) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/include/libos_internal.h#L33)):*
> ```objc
>                const char* fmt, ...) __attribute__((format(printf, 5, 6)));
> 
> int print_warnings_on_insecure_configs(bool parent_process);
> ```

This is a wrong name, the bool actually indicates whether this is a non-initial process. So, maybe negate and rename?



_Code quote:_
```objc
parent_process
```
___
*[`libos/src/libos_init.c` line 412 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5mKvee86LmbvnIxo0C:-O5nM5y5BpAkfd4PeFJ2:bal5syy) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/libos_init.c#L412)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sorry, for not being precise.
Do we need ret variable?
Can't we just do:
```
if (print_warnings_on_insecure_configs(!!g_pal_public_state->parent_process) < 0)
```

As ret is never used.
</blockquote></details>

I don't like putting such long calls inside `if`s, but it's not a strong preference.
___
*[`libos/src/fs/dev/attestation.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nMw652l0DQKHqoDuI:-O5nMw652l0DQKHqoDuJ:b9mewc9) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/fs/dev/attestation.c#L332)):*
> ```C
>     /* FIXME: Make all SGX-related names and constants more generic, based on
>      *        g_pal_public_state->confidential_computing == true */
>     if (!g_pal_public_state->confidential_computing) {
> ```

Why checking this in an attestation-specific function? Seems like a rather random place for doing that.


<!-- Sent from Reviewable.io -->

2024-09-04 06:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 3 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`libos/include/libos_internal.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nLkGs3vvLVCqEjHzS:-O5vlwcg9S_w40nDvknh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/include/libos_internal.h#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a wrong name, the bool actually indicates whether this is a non-initial process. So, maybe negate and rename?
</blockquote></details>

Done.
___
*[`libos/src/fs/dev/attestation.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nMw652l0DQKHqoDuI:-O5vl9ab-qS8rU2mBCGE:b-uqhvlr) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/fs/dev/attestation.c#L332)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why checking this in an attestation-specific function? Seems like a rather random place for doing that.
</blockquote></details>

I just wanted to double-check, for sanity. But I can remove it for now, it's not important (and not relevant to this PR anyway).


<!-- Sent from Reviewable.io -->

2024-09-04 07:07 UTC, oshogbo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986#-:-O5vr1Du7TZ5DzA1nqTm:bnfp4nl)* status: 3 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-09-04 12:13 UTC, mkow requested changes
> Reviewed 1 of 8 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5wv1mXBl2INO4wwTCJ:-O5wv1mY66Z2lBZL7PuM:b-jnbvpg) (no related file):*
Please also update `CONTRIBUTING.rst`:

> All new insecure options must be added to the Linux-SGX PAL function `print_warnings_on_insecure_configs()`.

___
___
*[`pal/src/host/linux-sgx/pal_main.c` line 480 at r3](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5wrTYa0H_gw55t1Ml5:-O5wrTYa0H_gw55t1Ml6:bolwydt) ([raw file](https://github.com/gramineproject/gramine/blob/534f60df1ee9f4f2611d22b29a965082666dfcd8/pal/src/host/linux-sgx/pal_main.c#L480)):*
> ```C
>     call_init_array();
> 
>     g_pal_public_state.confidential_computing = true;
> ```

Shouldn't we set this earlier? It doesn't depend on anything, but other calls may read it, at least in theory (e.g. something from the init array).
___
*[`libos/src/fs/dev/attestation.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nMw652l0DQKHqoDuI:-O5wqzvc0hyT0QSkzFZe:biu4ujz) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/fs/dev/attestation.c#L332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just wanted to double-check, for sanity. But I can remove it for now, it's not important (and not relevant to this PR anyway).
</blockquote></details>

If it's already guaranteed by some other code then I'd use an assert for that. But not blocking.


<!-- Sent from Reviewable.io -->

2024-09-04 12:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: 6 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5wv1mXBl2INO4wwTCJ:-O5x-12Y4y0doGN8SPNm:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also update `CONTRIBUTING.rst`:

> All new insecure options must be added to the Linux-SGX PAL function `print_warnings_on_insecure_configs()`.
</blockquote></details>

Done.

___
___
*[`libos/src/fs/dev/attestation.c` line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5nMw652l0DQKHqoDuI:-O5x-HOp-FScFjxrCJjC:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/acca9962104cc875ee162d4be3b7347ef3939631/libos/src/fs/dev/attestation.c#L332)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If it's already guaranteed by some other code then I'd use an assert for that. But not blocking.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_main.c` line 480 at r3](https://reviewable.io/reviews/gramineproject/gramine/1986#-O5wrTYa0H_gw55t1Ml5:-O5x-9EoEEgsOmAy2qPA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/534f60df1ee9f4f2611d22b29a965082666dfcd8/pal/src/host/linux-sgx/pal_main.c#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we set this earlier? It doesn't depend on anything, but other calls may read it, at least in theory (e.g. something from the init array).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 12:51 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-04 14:46 UTC, woju approved these changes
> Reviewed 3 of 8 files at r1, 3 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-04 14:56 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 16:32 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 17:01 UTC, merged