Added log_trace for raw syscall in gramine
gramineproject/gramine pull request #1991
Opened 2024-09-03 07:04 UTC by adarshan-intel

## Description of the changes 

- Logging every raw syscall helps identify how often they occur, if it's too many than that might cause performance issue but if it's rare, we can ignore the performance angle
- Printing messages for every syscall captures information about multiple raw syscalls, rather than just the first one.

## How to test this PR? 
- To build gramine, use meson and ninja commands. Then, for any workload (eg tested on pytorch), modify the manifest file to change log_level to trace, and you will see the raw syscalls.

2024-09-04 01:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @adarshan-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5uZgV3-yCoqfIydCjs):*




_Suggestion:_
```
Add log_trace for raw syscalls
```


<!-- Sent from Reviewable.io -->

2024-09-04 04:15 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5uZgV3-yCoqfIydCjs):*
Done.


<!-- Sent from Reviewable.io -->

2024-09-04 06:39 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @adarshan-intel and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vkQBv2LPt0xj-xxXS:-O5vkQBv2LPt0xj-xxXT:b-h3mpr4) (no related file):*
We have the same pattern in Linux PAL (for `gramine-direct`). I think for uniformity we want to add the same there: https://github.com/gramineproject/gramine/blob/a20d5b8339b880f79b92c4946d9eb5adfed98b66/pal/src/host/linux/pal_exception.c#L90-L93

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vkZKC6EXVH4ZyLLfp:-O5vkZKC6EXVH4ZyLLfq:b-1eun2) (no related file):*
Quickly checked on a Helloworld Golang app. Seems to work well.

___
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 234 at r2](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vk8MT-keR12HNQIfH:-O5vk8MT-keR12HNQIfI:bc2zt0e) ([raw file](https://github.com/gramineproject/gramine/blob/631cd3d517253c3dd80125bbc32f7941e56f75ac/pal/src/host/linux-sgx/pal_exception.c#L234)):*
> ```C
>         char buf[LOCATION_BUF_SIZE];
>         pal_describe_location(uc->rip, buf, sizeof(buf));
>         log_trace("Emulating raw syscall instruction with number %lu and address is %s", uc->rax,
> ```

`and address is %s` -> `at address %s`


<!-- Sent from Reviewable.io -->

2024-09-04 08:24 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vkQBv2LPt0xj-xxXS:-O5w7WvF7nFGV7iQW1dh:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have the same pattern in Linux PAL (for `gramine-direct`). I think for uniformity we want to add the same there: https://github.com/gramineproject/gramine/blob/a20d5b8339b880f79b92c4946d9eb5adfed98b66/pal/src/host/linux/pal_exception.c#L90-L93
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vkZKC6EXVH4ZyLLfp:-O5w7XVJ8lZUXa8SE48w:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Quickly checked on a Helloworld Golang app. Seems to work well.
</blockquote></details>

Done.

___
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 234 at r2](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5vk8MT-keR12HNQIfH:-O5vmDcEDwLEuo3kGz8L:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/631cd3d517253c3dd80125bbc32f7941e56f75ac/pal/src/host/linux-sgx/pal_exception.c#L234)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`and address is %s` -> `at address %s`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 09:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @mkow)

___
*[`pal/src/host/linux/pal_exception.c` line 97 at r4](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5wImbn64xaKRHn0eMN:-O5wImbn64xaKRHn0eMO:b-b0zet4) ([raw file](https://github.com/gramineproject/gramine/blob/254871b4405502b12ce8ad925129c7d8d7cfeb64/pal/src/host/linux/pal_exception.c#L97)):*
> ```C
>         pal_describe_location(ucontext_get_ip(uc), buf, sizeof(buf));
>         log_trace("Emulating raw syscall instruction with number %u at address %s",
>                   (unsigned int)info->si_syscall, buf);
> ```

Why do you need the type cast. Simply change `%u` to `%d`, and then you don't need `(unsigned int)` cast.


<!-- Sent from Reviewable.io -->

2024-09-04 09:45 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux/pal_exception.c` line 97 at r4](https://reviewable.io/reviews/gramineproject/gramine/1991#-O5wImbn64xaKRHn0eMN:-O5wQ4iDD3TeNHixdXmw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/254871b4405502b12ce8ad925129c7d8d7cfeb64/pal/src/host/linux/pal_exception.c#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need the type cast. Simply change `%u` to `%d`, and then you don't need `(unsigned int)` cast.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 11:40 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-09-04 12:53 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-04 13:20 UTC, dimakuv commented
Jenkins, test this please

2024-09-05 11:20 UTC, mkow reviewed
@adarshan-intel: Please read our contributing guidelines, especially this part: https://gramine.readthedocs.io/en/stable/devel/contributing.html#pr-life-cycle.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991#-:-O60uUCp9V6MUd0OdxFi:bro5a0v)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " and "Merge branch '" found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-05 11:40 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, all discussions resolved, "fixup! " and "Merge branch '" found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-05 11:46 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: all files reviewed, 1 unresolved discussion, "fixup! " and "Merge branch '" found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/1991#-O61-0hc8tuV_JA2oQg4):*
Shouldn't we include which component was changed (according to https://github.com/gramineproject/gramine/blob/11a3972d24edcb91ba5fd3eba1cc2cfcf9415700/Documentation/devel/coding-style.rst?plain=1#L45-L48)?



_Code quote:_
```
Add log_trace for raw syscalls
```


<!-- Sent from Reviewable.io -->

2024-09-05 12:49 UTC, dimakuv approved these changes
@adarshan-intel Please don't perform merges on PRs. We only use the rebase flow (never a merge), and we disallow to rebase/merge during working on the PR (the final rebase is done by one of the maintainers).

Anyway, I performed a final rebase now.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991#-:-O61DZCQ4jBlIs1n4grM:b-ym5vap)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/1991#-O61-0hc8tuV_JA2oQg4):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Shouldn't we include which component was changed (according to https://github.com/gramineproject/gramine/blob/11a3972d24edcb91ba5fd3eba1cc2cfcf9415700/Documentation/devel/coding-style.rst?plain=1#L45-L48)?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-05 12:58 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-05 16:33 UTC, dimakuv commented
Jenkins, test this please

2024-09-05 21:44 UTC, merged