[PAL/Linux-SGX] Remove printing of thread-local SGX statistics
gramineproject/gramine pull request #1995
Opened 2024-09-04 07:53 UTC by dimakuv

## Description of the changes 

Previously, when manifest contained `sgx.enable_stats = true`, Gramine-SGX printed not the process-wide SGX statistics, but also statistics for each thread. These thread-local SGX statistics only litter the output as (1) there are helper Gramine threads that do not correspond to any application thread, (2) there is no way to correlate the printed thread-local stats to application threads/workload execution (as stats simply print the opaque TID of the thread).

This PR removes thread-local stats and keeps only process-wide ones.

## How to test this PR? 

The Helloworld CI example (with `sgx.enable_stats = true`):

- With this PR:
```
gramineproject/gramine/CI-Examples/helloworld$ gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
----- SGX enclave loading time =     412964 microseconds -----
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world
----- Total SGX stats for process 273134 -----
  # of EENTERs:        317
  # of EEXITs:         241
  # of AEXs:           2175
  # of sync signals:   72
  # of async signals:  0
```

- Without this PR:
```
gramineproject/gramine/CI-Examples/helloworld$ gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
----- SGX enclave loading time =     410795 microseconds -----
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

----- SGX stats for thread 323750 -----
  # of EENTERs:        15
  # of EEXITs:         14
  # of AEXs:           19
  # of sync signals:   0
  # of async signals:  0
----- SGX stats for thread 323751 -----                                                                               [0/1860]
  # of EENTERs:        15
  # of EEXITs:         14
  # of AEXs:           0
  # of sync signals:   0
  # of async signals:  0
----- SGX stats for thread 323753 -----
  # of EENTERs:        15
  # of EEXITs:         14
  # of AEXs:           0
  # of sync signals:   0
  # of async signals:  0
Hello, world
----- SGX stats for thread 323754 -----
  # of EENTERs:        3
  # of EEXITs:         2
  # of AEXs:           0
  # of sync signals:   0
  # of async signals:  0
----- SGX stats for thread 323683 -----
  # of EENTERs:        269
  # of EEXITs:         197
  # of AEXs:           2162
  # of sync signals:   72
  # of async signals:  0
----- Total SGX stats for process 323683 -----
  # of EENTERs:        317
  # of EEXITs:         241
  # of AEXs:           2181
  # of sync signals:   72
  # of async signals:  0
```

2024-09-04 08:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O5w4eVB2cSFwQzEz5uF:-O5w4eVB2cSFwQzEz5uG:bygtgd0) (no related file):*
@mkow @woju @jkr0103 @kailun-qin @mwkmwkmwk What do you think about this PR? It changes user-facing (profiling) output, do we care? I am 99.9% sure no users rely on thread-local outputs.

___


<!-- Sent from Reviewable.io -->

2024-09-04 14:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O5w4eVB2cSFwQzEz5uF:-O5xPdL72fyovx0zj2DI:b-wa4x2p) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @woju @jkr0103 @kailun-qin @mwkmwkmwk What do you think about this PR? It changes user-facing (profiling) output, do we care? I am 99.9% sure no users rely on thread-local outputs.
</blockquote></details>

Feedback from @aneessahib: there were workloads where thread-local statistics were useful in debugging. However, hopefully with #1996 (the ability to reset stats on a user signal), the debugging with process-wide-only statistics will be similarly useful. So @aneessahib is Ok with both options: merging this PR and removing it.

___


<!-- Sent from Reviewable.io -->

2024-09-11 00:09 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @jkr0103, @mkow, @mwkmwkmwk, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O5w4eVB2cSFwQzEz5uF:-O6TOsDF9_99wtR1cZkk:bkrepy) (no related file):*
> there were workloads where thread-local statistics were useful in debugging

Yep, I guess so. But I'm fine w/ this PR.

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6TMxvd5elYx9gG2TiB):*
-> not only?



_Code quote:_
```
not
```


<!-- Sent from Reviewable.io -->

2024-09-16 14:00 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @jkr0103, @mwkmwkmwk, and @woju)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6uzMUt9kv6dhO88fq7):*




_Suggestion:_
```
there is no easy way
```
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6v3KEY2u6vWcMkICcd:-O6v3KEY2u6vWcMkICce:b-l3xtj1) ([raw file](https://github.com/gramineproject/gramine/blob/50de6ad721eb7f13e4ab2779d676f53a50c5288e/pal/src/host/linux-sgx/host_ocalls.c#L63)):*
> ```C
>     if (ocall_exit_args->is_exitgroup) {
>         process_exit((int)ocall_exit_args->exitcode);
>         die_or_inf_loop();
> ```

`process_exit()` is already `noreturn`
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6v0Nog0oPUAJ1QzBLL:-O6v0Nog0oPUAJ1QzBLM:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/50de6ad721eb7f13e4ab2779d676f53a50c5288e/pal/src/host/linux-sgx/pal_tcb.h#L118)):*
> ```objc
> 
> extern bool g_sgx_enable_stats;
> void update_sgx_stats(bool print_process_wide_stats);
> ```





_Suggestion:_
```objc
do_print
```


<!-- Sent from Reviewable.io -->

2024-09-16 14:36 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 6 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @jkr0103, @mwkmwkmwk, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6vFmY94Xx36rKce7wi:-O6vFmYAEDexjNBaIEg9:b51qzry) (no related file):*
> Enabling per-thread and process-wide SGX stats

`manifest-syntax.rst` also needs an update.

___


<!-- Sent from Reviewable.io -->

2024-09-17 11:11 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 6 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @jkr0103, @mwkmwkmwk, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6vFmY94Xx36rKce7wi:-O6zfOLnEwqoeMu40Azg:bgmqwn9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Enabling per-thread and process-wide SGX stats

`manifest-syntax.rst` also needs an update.
</blockquote></details>

ah, and `performance.rst` also

___


<!-- Sent from Reviewable.io -->

2024-09-18 10:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: 0 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6vFmY94Xx36rKce7wi:-O73iVgGE0TU6tOKYlcc:b-376vyb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ah, and `performance.rst` also
</blockquote></details>

Done. Good catch.

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6TMxvd5elYx9gG2TiB):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> not only?
</blockquote></details>

Will do during final rebase
___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6uzMUt9kv6dhO88fq7):*
Will do during final rebase
___
*[`pal/src/host/linux-sgx/host_ocalls.c` line 63 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6v3KEY2u6vWcMkICcd:-O73hciNAVlPM1uAe9qA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/50de6ad721eb7f13e4ab2779d676f53a50c5288e/pal/src/host/linux-sgx/host_ocalls.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`process_exit()` is already `noreturn`
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_tcb.h` line 118 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6v0Nog0oPUAJ1QzBLL:-O73hIiB3Gzlux8dx1Ff:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/50de6ad721eb7f13e4ab2779d676f53a50c5288e/pal/src/host/linux-sgx/pal_tcb.h#L118)):*
> ```objc
> 
> extern bool g_sgx_enable_stats;
> void update_sgx_stats(bool print_process_wide_stats);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 11:55 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2024-09-19 01:56 UTC, kailun-qin approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2024-09-24 14:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @kailun-qin, @mkow, and @woju)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6TMxvd5elYx9gG2TiB):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/1995#-O6uzMUt9kv6dhO88fq7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during final rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 14:17 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-09-24 14:18 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-09-24 16:54 UTC, merged