[PAL/Linux-SGX] Print SGX stats on SIGUSR1 and reset them
gramineproject/gramine pull request #1996
Opened 2024-09-04 11:34 UTC by dimakuv

## Description of the changes 

This commit adds support to dump and reset SGX-related statistics interactively, using SIGUSR1 signal. This helps to collect SGX-related statistics only for a particular period, e.g. skipping the Gramine startup and application initialization time and concentrating only on the actual application processing.

The printed-out statistics are not precise, as the "stats collecting" thread may run in parallel with other threads that update the statistics. However, this imprecise implementation is simple and enough for perf analysis.

This commit also breaks compatibility: SGX statistics can only be collected and printed when Gramine is built in debug or debugoptimized mode. However, this should not affect users as SGX stats is tailored for manual debugging and profiling sessions.

Applied on top of #1995 

Closes #1857

## How to test this PR? 

Check instructions in https://github.com/gramineproject/gramine/pull/1857

2024-09-04 11:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: 0 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`pal/src/host/linux-sgx/host_exception.c` line 194 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O5woH8n6hpu8YpIBglj:-O5woH8n6hpu8YpIBglk:b-gf6k26) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_exception.c#L194)):*
> ```C
>     if (g_sgx_enable_stats) {
>         PAL_HOST_TCB* tcb = pal_get_host_tcb();
>         __atomic_store_n(&tcb->reset_stats, true, __ATOMIC_RELAXED);
> ```

It is possible that two SIGUSR1 signals arrive one after another (or even on different threads). This is benign because the whole `collect_and_print_sgx_stats()` function is protected with a global lock.
___
*[`pal/src/host/linux-sgx/host_thread.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O5woUGI0TAcSfURiexU:-O5woUGI0TAcSfURiexV:bt0pxov) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L19)):*
> ```C
>     unsigned int    tid;
>     sgx_arch_tcs_t* tcs;
>     PAL_HOST_TCB*   tcb;
> ```

This is a bit controversial: a "SGX-stats-collecting" thread (that received SIGUSR1) is able to peek into the thread local storage of other threads. This is typically considered a bad smell (one thread reads local data of another thread), but here I think it's a reasonable trade-off: most of the accesses to the thread-local SGX counters are done on EEXIT and AEX events by the thread itself, so the memory access should be as simple as possible and as fast as possible. If we would move everything in a shared array, then we would have false cache sharing and complex memory management of the shared array.


<!-- Sent from Reviewable.io -->

2024-09-17 12:38 UTC, mkow requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6vEXop4moN_GQ0x3NY):*




_Suggestion:_
```
SGX statistics can now only be
```
___
*[`pal/src/host/linux-sgx/host_exception.c` line 285 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zvkRv54t55HEnC2mu:-O6zvkRv54t55HEnC2mv:b-3m7fgd) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_exception.c#L285)):*
> ```C
> 
>     PAL_HOST_TCB* tcb = pal_get_host_tcb();
>     if (__atomic_load_n(&tcb->reset_stats, __ATOMIC_RELAXED) == false)
> ```

Maybe just atomic exchange with `false`? Would be one line less and effectively work the same.
___
*[`pal/src/host/linux-sgx/host_thread.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O5woUGI0TAcSfURiexU:-O6zwvKe6ZR0yZXxDJty:b6x3o70) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a bit controversial: a "SGX-stats-collecting" thread (that received SIGUSR1) is able to peek into the thread local storage of other threads. This is typically considered a bad smell (one thread reads local data of another thread), but here I think it's a reasonable trade-off: most of the accesses to the thread-local SGX counters are done on EEXIT and AEX events by the thread itself, so the memory access should be as simple as possible and as fast as possible. If we would move everything in a shared array, then we would have false cache sharing and complex memory management of the shared array.
</blockquote></details>

Could you put that in a comment here? Or better, to the loop iterating over TCBs?
___
*[`pal/src/host/linux-sgx/host_thread.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zyZyO-OZ6DHaJAc0W:-O6zyZyO-OZ6DHaJAc0X:b-z0a5km) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L75)):*
> ```C
>     /* there is a small window when the thread's counters may be updated in-between reading and
>      * resetting these counters -- some SGX events will be lost; we ignore this as the number of
>      * lost events is negligible for perf analysis purposes */
> ```

Why not atomic exchange with 0 then?
___
*[`pal/src/host/linux-sgx/host_thread.c` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zrgug3TCh1_KIJqhA:-O6zrgug3TCh1_KIJqhB:b-w17gmh) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L84)):*
> ```C
> }
> 
> /* this function is called only on thread/process exit (never in the middle of thread exec) */
> ```

Then I'd add a suffix `on_thread_exit` to it (if it's important to its semantics).


<!-- Sent from Reviewable.io -->

2024-09-18 11:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: 10 of 14 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6vEXop4moN_GQ0x3NY):*
Will do during final rebase
___
*[`pal/src/host/linux-sgx/host_exception.c` line 285 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zvkRv54t55HEnC2mu:-O73k8it56TJVUL_AAYU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_exception.c#L285)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just atomic exchange with `false`? Would be one line less and effectively work the same.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/host_thread.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O5woUGI0TAcSfURiexU:-O73lIaS-8T2XZ6vHQOv:b-nnvmd2) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you put that in a comment here? Or better, to the loop iterating over TCBs?
</blockquote></details>

Done. Put in the loop.
___
*[`pal/src/host/linux-sgx/host_thread.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zyZyO-OZ6DHaJAc0W:-O73mCXG9qOxox2v9WSl:bz1wmeo) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not atomic exchange with 0 then?
</blockquote></details>

Done. True, I was being lazy.
___
*[`pal/src/host/linux-sgx/host_thread.c` line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zrgug3TCh1_KIJqhA:-O73lbC53clGGkSaiXXd:bap2yby) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then I'd add a suffix `on_thread_exit` to it (if it's important to its semantics).
</blockquote></details>

Done. It's not only thread exit but also process exit, so I decided to add `_on_exit`.


<!-- Sent from Reviewable.io -->

2024-09-18 13:47 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/1996#-O6zyZyO-OZ6DHaJAc0W:-O74LDbf7oc1JDQhUt4K:b-mzdr4e) ([raw file](https://github.com/gramineproject/gramine/blob/0e1e3a74db98122ff24049b6ce23b01e29c7f675/pal/src/host/linux-sgx/host_thread.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. True, I was being lazy.
</blockquote></details>

It's even shorter now :)


<!-- Sent from Reviewable.io -->

2024-09-19 02:11 UTC, kailun-qin approved these changes
> Reviewed 9 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-09-19 02:12 UTC, kailun-qin approved these changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-09-24 17:19 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-24 19:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7_QBnm59NdvrcQRcgl:b-kg01w5) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
> ```C
>                                               __ATOMIC_RELAXED);
>     g_async_signal_cnt += __atomic_exchange_n((uint64_t*)&tcb->async_signal_cnt, 0,
>                                               __ATOMIC_RELAXED);
> ```

Not happy about the explicit cast, but otherwise Clang complains (GCC doesn't):
```
  ../pal/src/host/linux-sgx/host_thread.c:67:27: error: address argument to atomic operation must be a pointer to integer or pointer ('atomic_ulong *' (aka '_Atomic(unsigned long) *') invalid)
      g_eenter_cnt       += __atomic_exchange_n(&tcb->eenter_cnt, 0, __ATOMIC_RELAXED);
```


<!-- Sent from Reviewable.io -->

2024-09-24 21:34 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7_wpD-1lg2iJJh4Be6:b-ghg9xt) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not happy about the explicit cast, but otherwise Clang complains (GCC doesn't):
```
  ../pal/src/host/linux-sgx/host_thread.c:67:27: error: address argument to atomic operation must be a pointer to integer or pointer ('atomic_ulong *' (aka '_Atomic(unsigned long) *') invalid)
      g_eenter_cnt       += __atomic_exchange_n(&tcb->eenter_cnt, 0, __ATOMIC_RELAXED);
```
</blockquote></details>

`atomic_ulong` is `_Atomic unsigned long`, not `_Atomic uint64_t`


<!-- Sent from Reviewable.io -->

2024-09-24 22:28 UTC, kailun-qin reviewed
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7a7dcY9dGCWBZZ74w3:b6ursmc) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
> Not happy about the explicit cast

+1 (UB from standard), but it looks to be the easiest way

> `atomic_ulong` is `_Atomic unsigned long`, not `_Atomic uint64_t`

+1


<!-- Sent from Reviewable.io -->

2024-09-25 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7c15i7CearZtZ1wk5g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Not happy about the explicit cast

+1 (UB from standard), but it looks to be the easiest way

> `atomic_ulong` is `_Atomic unsigned long`, not `_Atomic uint64_t`

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-25 08:53 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (unrelated issue, see description below)

On Jenkins-20.04, `gramine-direct ppoll01` LTP test failed:
```
/home/jenkins/workspace/graphene-20.04/libos/test/ltp/src/testcases/kernel/syscalls/ppoll/ppoll01.c:288: TFAIL: ret: 0, exp: -1, ret_errno: SUCCESS (0), exp_errno: EINTR (4)
```

I can't reproduce it locally, and I have never seen this error before. Moreover, this error has nothing to do with the current PR, as the current PR does *not* modify LTP or `gramine-direct` (aka Linux PAL) in any way.

2024-09-25 11:56 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-09-25 17:19 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7eBI7i2STS3-K40vqP:bm5qz6e) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, wait, you should just use C11 functions for that instead: https://en.cppreference.com/w/c/atomic. Then no cast will be needed.


<!-- Sent from Reviewable.io -->

2024-09-25 20:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-sgx/host_thread.c` line 73 at r4](https://reviewable.io/reviews/gramineproject/gramine/1996#-O7_QBnm59NdvrcQRcgk:-O7er8H88uvMONx9-BV4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6b5a59f4137403de942190ea291dd4872cc6b39b/pal/src/host/linux-sgx/host_thread.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, wait, you should just use C11 functions for that instead: https://en.cppreference.com/w/c/atomic. Then no cast will be needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-25 23:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 04:26 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 07:08 UTC, merged