[PAL] Fix `memory` PAL regression test for UBSan
gramineproject/gramine pull request #2003
Opened 2024-09-24 08:27 UTC by dimakuv

## Description of the changes 

Newer Clang versions (v18 and newer) added more UBSan checks that triggered UBSan on PAL regression tests. In particular, UBSan added the check "Indirect call of a function through a function pointer of the wrong type". UBSan expects all functions which can be indirectly called to be instrumented with two magic metadata values, located right-before the function in address space.

The `memory` test however does *not* add this required metadata to a dummy generated-on-the-fly function (it simply allocates some pages and copies the asm code at the beginning of the first page). Instead of adding UBSan-required metadata, we simply disable this particular check (it's a test after all, not core Gramine functionality).

References:
- https://maskray.me/blog/2022-12-18-control-flow-integrity#fsanitizefunction
- https://llvm.org/docs/LangRef.html#func-sanitize-metadata

Reported by @woju.

## How to test this PR? 

Run PAL regression tests on Ubuntu 24.04 + UBSan enabled.

2024-09-24 09:19 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YHj4v5-sqRN9SPUsI):*
Isn't it v17? (according to https://maskray.me/blog/2022-12-18-control-flow-integrity#fsanitizefunction)



_Code quote:_
```
v18
```
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YHrfGBlIwe8VJwkRg):*
Isn't it (also) because since v17`-fsanitize=function` was allowed on C code, while previously it was C++ only (based on https://reviews.llvm.org/D148827)?



_Code quote:_
```
added more UBSan checks
```


<!-- Sent from Reviewable.io -->

2024-09-24 10:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YHj4v5-sqRN9SPUsI):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Isn't it v17? (according to https://maskray.me/blog/2022-12-18-control-flow-integrity#fsanitizefunction)
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YHrfGBlIwe8VJwkRg):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Isn't it (also) because since v17`-fsanitize=function` was allowed on C code, while previously it was C++ only (based on https://reviews.llvm.org/D148827)?
</blockquote></details>

Done. Rephrased.


<!-- Sent from Reviewable.io -->

2024-09-24 11:02 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-09-24 12:03 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`pal/regression/memory.c` line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YuY-m9_al0pcw-4Ww:-O7YuY-m9_al0pcw-4Wx:b-g1qyuc) ([raw file](https://github.com/gramineproject/gramine/blob/9777dac6df61e69841c976bafbfc2174d5d22073/pal/regression/memory.c#L96)):*
> ```C
>  * to be instrumented with two magic metadata values, located right-before the function in address
>  * space. The below code does *not* add metadata (it simply allocates some pages and copies the asm
>  * code at the beginning of the first page). Instead of adding UBSan-required metadata, we simply
> ```

"asm code" -> "machine code"


<!-- Sent from Reviewable.io -->

2024-09-24 13:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`pal/regression/memory.c` line 96 at r2](https://reviewable.io/reviews/gramineproject/gramine/2003#-O7YuY-m9_al0pcw-4Ww:-O7ZJw4mCtPvijV0Os3Y:b-qs95mi) ([raw file](https://github.com/gramineproject/gramine/blob/9777dac6df61e69841c976bafbfc2174d5d22073/pal/regression/memory.c#L96)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"asm code" -> "machine code"
</blockquote></details>

Done. Also in the commit message.


<!-- Sent from Reviewable.io -->

2024-09-24 14:08 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-09-24 14:10 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 17:21 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2003)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 18:37 UTC, merged