[PAL/{Linux,Linux-SGX}] Removing buffer and describe location functions
gramineproject/gramine pull request #2015
Opened 2024-10-04 10:30 UTC by adarshan-intel

## Description of the Changes

To resolve the segmentation fault that occurs when running `PyTorch` workloads in debug mode with attestation from the contrib repository on specific machines, we propose the following modifications:

The key change consists of removing the `buffer` and the `pal_describe_location` function. This adjustment targets the segmentation fault issue introduced in pull request #1991

2024-10-04 14:08 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @adarshan-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8Mr-Kq7-tT4ulpQ-u5:-O8Mr-Kq7-tT4ulpQ-u6:b-oi687q) (no related file):*
Why does this fix the issue? What was the reason for the segfault?

___


<!-- Sent from Reviewable.io -->

2024-10-05 05:15 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8Mr-Kq7-tT4ulpQ-u5:-O8Q3vCE7L_CKxk4os3L:b489mvc) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why does this fix the issue? What was the reason for the segfault?
</blockquote></details>

Below is the error log with SIGSEGV:
```
(host_exception.c:141:handle_sync_signal) error: Unexpected segmentation fault (SIGSEGV) occurred inside untrusted PAL (libc-2.31.so+0x22941 (addr = 0x7f62e5f98941))
```

Using the above addresses we could get the functions `abort->hlt` from objdump of libc.

We tried to debug the issue using GDB to figure out the cause of `abort` call inside `libc` but issue is not reproducing with GDB, tried multiple times but always reproduces without GDB, seems like some `race` in Gramine when using `pal_describe_location` only with specific configuration.

Hence we plan to remove this function call in coming release and analyze this issue after the release.

___


<!-- Sent from Reviewable.io -->

2024-10-05 09:43 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8Mr-Kq7-tT4ulpQ-u5:-O8R1rLcCeNZ3OZUtjKa:be24qat) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Below is the error log with SIGSEGV:
```
(host_exception.c:141:handle_sync_signal) error: Unexpected segmentation fault (SIGSEGV) occurred inside untrusted PAL (libc-2.31.so+0x22941 (addr = 0x7f62e5f98941))
```

Using the above addresses we could get the functions `abort->hlt` from objdump of libc.

We tried to debug the issue using GDB to figure out the cause of `abort` call inside `libc` but issue is not reproducing with GDB, tried multiple times but always reproduces without GDB, seems like some `race` in Gramine when using `pal_describe_location` only with specific configuration.

Hence we plan to remove this function call in coming release and analyze this issue after the release.
</blockquote></details>

Please debug this, it may be something serious. This PR sounds like randomly changing code until it stops crashing...

___


<!-- Sent from Reviewable.io -->

2024-10-07 06:49 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @adarshan-intel and @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8_gCS7Czsqqestq82B):*
This should be like this:
```
[PAL/{Linux,Linux-SGX}] Do not try to describe RIP location on syscall instruction

Commit b6a2d79 ("[PAL/{Linux,Linux-SGX}] Add trace log for raw syscalls")
added a debug print for every encountered raw syscall instruction. Each print
describes what system call number is invoked and at which address in the binary.
The address is fed to the helper function `pal_describe_location(uc->rip)` which
tries to find the binary + function name and put them in human-readable form
into the provided buffer.

For some reason, the snippet used in that commit (allocating a 128-byte buffer
on signal-handling stack and calling `pal_describe_location()`) leads to a
non-deterministic memory corruption on some workloads. That bug is hardly
reproducible, and it is not fixed by e.g. increasing the signal stack size inside
Gramine. The `pal_describe_location()` control path also seems correct.

As the true root cause for this bug is not yet found, this commit introduces
a workaround: temporarily removing the stack-allocated buffer and the
correspoding `pal_describe_location()` call, and instead printing the raw
RIP value.

Signed-off-by: Adarsh Anand <adarsh.anand@intel.com>
```


<!-- Sent from Reviewable.io -->

2024-10-07 06:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @adarshan-intel and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8Mr-Kq7-tT4ulpQ-u5:-O8_jVIO44JHo04eyllO:b51sg0w) (no related file):*
> Please debug this, it may be something serious. This PR sounds like randomly changing code until it stops crashing...

We tried to debug this, but failed. The issue was (for some reason) reproducible only in a particular Ubuntu 20.04 Docker container on a particular machine.

The issue seems to be a memory corruption, as it is not deterministic. In fact, the message that Jitender and Anjali put here (`
error: Unexpected segmentation fault (SIGSEGV) occurred inside untrusted PAL`) seems to me misleading, as this error is just a manifestation of Glibc's `abort()` function that performs a HLT instruction -- and Gramine is not expecting the untrusted runtime's Glibc to execute such HLT instructions.

Anyway, experimenting with different stack sizes didn't help at all. This was my first guess: a stack buffer overflow, since we allocate a 128-byte buffer on a signal-handling stack. However, this is not the root cause.

Next theory was (and still is) that there is some incorrect locking/synchronization inside `pal_describe_location()`. But inspecting that function, I don't see anything wrong -- all sensitive operations are protected by locks. It does feel though like iterating through a GDB-specific list of loaded binaries has a bug somewhere, but I couldn't pinpoint where. This would explain both requirements for this bug: (1) the bug manifests only in debug build of Gramine, and (2) the bug is a memory corruption that seems to happen in the untrusted PAL.

This can probably be debugged in 2-3 days by a senior dev, but I am personally not taking any such requests anymore. And the time for the new Gramine release is approaching, so my recommendation would be to merge this PR, and properly debug later.

___


<!-- Sent from Reviewable.io -->

2024-10-07 07:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2015)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @adarshan-intel and @mkow)

___
*[`pal/src/host/linux/pal_exception.c` line 94 at r1](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8_mF7A8mVhZBrrjOVs:-O8_mF7A8mVhZBrrjOVt:b-jshxbm) ([raw file](https://github.com/gramineproject/gramine/blob/b239fbb5258b55db61eff5094db0262c949bb6e0/pal/src/host/linux/pal_exception.c#L94)):*
> ```C
>                        " patching your application to use Gramine syscall API.");
>         }
>         log_trace("Emulating raw syscall instruction with number %d at address %p", info->si_syscall,
> ```

Please add above this line a comment so that we don't forget in the future:
```
/* FIXME: better to use `pal_describe_location()` (see example below), but it leads to a
 *        non-deterministic bug on some workloads */
```
___
*[`pal/src/host/linux-sgx/pal_exception.c` line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/2015#-O8_mihT59yHIt6PFRgS:-O8_mihT59yHIt6PFRgT:b-4cf746) ([raw file](https://github.com/gramineproject/gramine/blob/b239fbb5258b55db61eff5094db0262c949bb6e0/pal/src/host/linux-sgx/pal_exception.c#L235)):*
> ```C
>                        " patching your application to use Gramine syscall API.");
>         }
>         log_trace("Emulating raw syscall instruction with number %lu at address %p",
> ```

ditto (addd comment)


<!-- Sent from Reviewable.io -->

2024-10-07 08:25 UTC, closed without merging

2024-10-07 08:33 UTC, adarshan-intel commented
This PR has been moved to #2017