[PAL/{Linux,Linux-SGX}] Removing buffer and pal_describe_location function
gramineproject/gramine pull request #2017
Opened 2024-10-07 08:32 UTC by adarshan-intel

## Description of the Changes

PR #1991 exposes a segmentation fault with the use of `pal_describe_location` as in below error log:
 
```
(host_exception.c:141:handle_sync_signal) error: Unexpected segmentation fault (SIGSEGV) occurred inside untrusted PAL (libc-2.31.so+0x22941 (addr = 0x7f62e5f98941))
```
 
Using the above addresses we could find the functions abort->hlt from objdump of libc.
 
We tried to debug the issue using GDB to figure out the cause of abort call inside libc but issue did not reproduced with GDB even after multiple tries.
 
Issue is consistent with Pytorch workload using curated apps (with debug build) without GDB, on a Azure VM, rarely on our lab servers.
 
Also tested by increasing the ENCLAVE_SIG_STACK_SIZE and ALT_STACK_SIZE size to 256KB but that also did not help.
 
Likely some race in Gramine when using `pal_describe_location` which we are not hitting with GDB as GDB makes the execution slow.
 
We want to remove this function call in coming release and analyze this issue after the release.

Fixes gramineproject/contrib#87

2024-10-07 09:21 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-10-07 09:21 UTC, dimakuv commented
Jenkins, test this please

2024-10-07 16:36 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @adarshan-intel and @mkow)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8aj4HE1UPMGmR9v0HX):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "control path"?
</blockquote></details>

I proposed this "control path" wording. I simply meant that the function `pal_describe_location()` calls other functions, and by inspecting all these called functions, it looked fine to me (no data races).
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8ajDvo528rvYgnQTvi):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> As the true root cause for this bug is not yet found, this commit introduces a workaround

As I said in the previous PR (#2015) I'm not ok with doing random changes without understanding what's causing the memory corruption.
</blockquote></details>

Well, true... Someone needs to debug it.


<!-- Sent from Reviewable.io -->

2024-10-08 11:56 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @adarshan-intel and @dimakuv)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8aj4HE1UPMGmR9v0HX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I proposed this "control path" wording. I simply meant that the function `pal_describe_location()` calls other functions, and by inspecting all these called functions, it looked fine to me (no data races).
</blockquote></details>

ah, you mean "control-flow path"? or something else?


<!-- Sent from Reviewable.io -->

2024-10-09 07:48 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @adarshan-intel and @mkow)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8aj4HE1UPMGmR9v0HX):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ah, you mean "control-flow path"? or something else?
</blockquote></details>

Yes, true, I meant "control flow path"


<!-- Sent from Reviewable.io -->

2024-10-14 04:44 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8aijp098W3FmCnA4w9):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need to list all the PALs as the change is in all PALs we have.
</blockquote></details>

Done.
___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8aj4HE1UPMGmR9v0HX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, true, I meant "control flow path"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-14 06:06 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2017)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/2017#-O8ajDvo528rvYgnQTvi):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, true... Someone needs to debug it.
</blockquote></details>

@mkow Will you post here the details of your debugging session, and the conclusion (most probably, to revert #1991 until a proper fix is done)?


<!-- Sent from Reviewable.io -->

2024-11-05 15:10 UTC, mkow commented
Closing this, as it's not fixing the issue (see https://github.com/gramineproject/gramine/issues/1261#issuecomment-2411152710). I'll create a proper fix and submit a PR.

2024-11-05 15:10 UTC, closed without merging