[CI-Examples] Add Nginx test data files measurements within the manifest
gramineproject/gramine pull request #2018
Opened 2024-10-07 09:41 UTC by vasanth-intel

## Description of the changes 
### Description of the problem

Commit aef087f "[[LibOS] Move trusted and allowed files logic to LibOS]" modified the Nginx `Makefile` after which it was observed that all the test data files (`install/html/random`) are generated after the manifest file generation and hence were not added as `sgx.trusted_files` in manifest.sgx file. 

Fixes #2016 

## How to test this PR? 
1. Git clone gramine repo `git clone https://github.com/gramineproject/gramine.git`.
2. Go to `CI-Examples/nginx` folder.
3. Execute `make SGX=1` command.
4. The test data files will be added as part of `sgx.trusted_files` within the manifest.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2018)

2024-10-07 16:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O8bq9Vf7Ac1DJkQDToX):*
This whole commit message would need to be changed a bit and rewrapped, we can do it during final merge.


<!-- Sent from Reviewable.io -->

2024-10-08 06:36 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-10-15 10:32 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vasanth-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Ej4uP0Prb78I12DuF:-O9Ej4uP0Prb78I12DuG:b-qz9qco) (no related file):*
How's it possible that our CI didn't detect this? It is tested under SGX...

___
___
*[`CI-Examples/nginx/Makefile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Eiol8APc9hRCaRNRq:-O9Eiol8APc9hRCaRNRr:b748hr5) ([raw file](https://github.com/gramineproject/gramine/blob/ffccc467bf135f9649d0c36174e159769e12f95e/CI-Examples/nginx/Makefile#L53)):*
> ```Makefile
> 		$(foreach mirror,$(NGINX_MIRRORS),--url $(mirror)/$(NGINX_SRC).tar.gz)
> 
> nginx.manifest: nginx.manifest.template $(INSTALL_DIR)/sbin/nginx testdata \
> ```

We shouldn't depend on a `.PHONY` target, instead it should be `$TEST_DATA` (and you need to move that variable up).


<!-- Sent from Reviewable.io -->

2024-10-15 11:19 UTC, vasanth-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`CI-Examples/nginx/Makefile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Eiol8APc9hRCaRNRq:-O9EtYPS8f97n02d3I05:b4xnm2a) ([raw file](https://github.com/gramineproject/gramine/blob/ffccc467bf135f9649d0c36174e159769e12f95e/CI-Examples/nginx/Makefile#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We shouldn't depend on a `.PHONY` target, instead it should be `$TEST_DATA` (and you need to move that variable up).
</blockquote></details>

This fix was recommended by Dmitrii as per https://github.com/gramineproject/gramine/issues/2016#issuecomment-2396014589. Any issues with the current fix?


<!-- Sent from Reviewable.io -->

2024-10-15 11:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vasanth-intel)



<!-- Sent from Reviewable.io -->

2024-10-15 12:06 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @vasanth-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Ej4uP0Prb78I12DuF:-O9F37e586jtTWSSI77Y:b2ey8a) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The reason is that Nginx falls back to a default `index.html` (which is created during Nginx build & install and which is put in trusted files).

So even though by default `benchmark-http.sh` script tries to fetch `10K.html` auto-generated page (and *not* in trusted files), the script gets back `index.html` and is still happy. You can see how Nginx on current Gramine master falls back to `index.html`:
```
$ gramine-sgx ./nginx
...

$ wget -q --no-proxy -O - http://127.0.0.1:8002 | head
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
```

(`--no-proxy` is due to my company's proxy, ignore it.)

I guess we could set up Nginx so that it doesn't fall back to `index.html` but instead returns a proper error?
</blockquote></details>

Ouch, that's pretty bad. Yeah, we should either change the config or check the file contents in the benchmark script? (the former is easier, probably)

___
___
*[`CI-Examples/nginx/Makefile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Eiol8APc9hRCaRNRq:-O9F2ffGE6ErmZjfqmcA:b-8uf5rx) ([raw file](https://github.com/gramineproject/gramine/blob/ffccc467bf135f9649d0c36174e159769e12f95e/CI-Examples/nginx/Makefile#L53)):*
> This fix was recommended by Dmitrii as per [#2016 (comment)](https://github.com/gramineproject/gramine/issues/2016#issuecomment-2396014589). Any issues with the current fix?

@vasanth-intel: I don't understand your comment, I just listed the issue above in my comment... Also, it doesn't matter who suggested something, if it's wrong then we need to fix that.

> Here's the git diff that seems to work fine:

Yup, looks good, assuming you'll also check the line with this very comment.


<!-- Sent from Reviewable.io -->

2024-10-15 14:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @mkow and @vasanth-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Ej4uP0Prb78I12DuF:-O9FTdhMDaxeLp5fLwWO:b-rlcldy) (no related file):*
> Yeah, we should either change the config or check the file contents in the benchmark script? (the former is easier, probably)

I would say it's a separate PR. (I assume that we want to merge this PR asap, and fix the benchmark script/Nginx conf later.)

___
___
*[`CI-Examples/nginx/Makefile` line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Eiol8APc9hRCaRNRq:-O9FU6no7iEL118b5vwO:b-d5ib4w) ([raw file](https://github.com/gramineproject/gramine/blob/ffccc467bf135f9649d0c36174e159769e12f95e/CI-Examples/nginx/Makefile#L53)):*
> [@dimakuv](https://github.com/dimakuv) I thought your suggestion was right and hence pointed to your comment.

Yes, I understand your confusion. Indeed, I also thought that my initial suggestion was good enough. But @mkow is right -- we already have the `TEST_DATA` dependency listed, so we just need to make this dependency work. (The `TEST_DATA` variable expands to a list of actual HTML files, and such real-file dependencies are always better than non-real PHONY dependencies.)


<!-- Sent from Reviewable.io -->

2024-10-15 14:10 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @mkow and @vasanth-intel)



<!-- Sent from Reviewable.io -->

2024-10-15 14:46 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @vasanth-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Ej4uP0Prb78I12DuF:-O9FcmqW1KFb6f0HSy9h:b7trnkb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Yeah, we should either change the config or check the file contents in the benchmark script? (the former is easier, probably)

I would say it's a separate PR. (I assume that we want to merge this PR asap, and fix the benchmark script/Nginx conf later.)
</blockquote></details>

Could you or @vasanth-intel create an issue?

___
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9FcsTr7MVuhMMe7895):*
@vasanth-intel: Please read our contributing.rst.


<!-- Sent from Reviewable.io -->

2024-10-15 15:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @vasanth-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9Ej4uP0Prb78I12DuF:-O9Fi-rY5mpYOA2cYb02:bdbdfkk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you or @vasanth-intel create an issue?
</blockquote></details>

I created an issue: https://github.com/gramineproject/gramine/issues/2035

Please note that **I was wrong initially**. The problem is not in Nginx, but in `wrk`.

In my example script above with `wget`, I forgot to add the `/remote/10K.1.html` actual URI, so wget returned `index.html` (the default URI). So my bad, drawing wrong conclusions from a wrong invocation of `wget` :(

___


<!-- Sent from Reviewable.io -->

2024-10-15 21:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @vasanth-intel)



<!-- Sent from Reviewable.io -->

2024-10-15 23:03 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, one-liner is not in imperative mood (waiting on @vasanth-intel)



<!-- Sent from Reviewable.io -->

2024-10-16 14:32 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 2 unresolved discussions (waiting on @vasanth-intel)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/2018#-O9FcsTr7MVuhMMe7895):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vasanth-intel: Please read our contributing.rst.
</blockquote></details>

@mkow You're blocking here.


<!-- Sent from Reviewable.io -->

2024-10-16 14:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @vasanth-intel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2018#-O8bq9Vf7Ac1DJkQDToX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole commit message would need to be changed a bit and rewrapped, we can do it during final merge.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-16 14:37 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @vasanth-intel)



<!-- Sent from Reviewable.io -->

2024-10-16 14:54 UTC, mkow commented
Jenkins, retest this please

2024-10-16 14:55 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2018)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-16 16:06 UTC, merged