[mbedtls] Upgrade mbedTLS to version 3.6.1
gramineproject/gramine pull request #2024
Opened 2024-10-10 06:47 UTC by kailun-qin

## Description of the changes 

This version includes fixes for three CVEs affecting Mbed TLS:
* CVE-2024-45158: severity High,
* CVE-2024-45159: severity Medium,
* CVE-2024-45157: severity Low.

## How to test this PR? 

CI.

2024-10-10 07:21 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pI-ic5IiY7GfKEMa0):*
Though we should not impacted by the CVEs (pls see below), we may still want this update to pass BDBA scans which flag the high severity CVE.



_Code quote:_
```
This version includes fixes for three CVEs affecting Mbed TLS
```
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pFwnF4hmqyw8dHgGG):*
We should not be impacted by this CVE as we do not use `mbedtls_ecdsa_der_to_raw()` or `mbedtls_ecdsa_raw_to_der()` (while it only affects applications that call these functions directly).



_Code quote:_
```
CVE-2024-45158: severity High,
```
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pGVUE6_G5AahqPn6G):*
We should not be impacted by this CVE since it only affects TLS 1.3 but we do not enable TLS 1.3 for internal Gramine PAL crypto/TLS; as for our `ra-tls-mbedtls` CI-example, we control our server certificate and do not use `keyUsage` or `extKeyUsage` extensions.



_Code quote:_
```
CVE-2024-45159: severity Medium,
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pHlJl0ydmwNXXolr6):*
We should not be impacted by this CVE as we don't enable `MBEDTLS_PSA_HMAC_DRBG_MD_TYPE`.



_Code quote:_
```
CVE-2024-45157: severity Low.
```
___
*[`subprojects/mbedtls-3.6.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pFj6A40a0DZ-uWxi5:-O8pFj6A40a0DZ-uWxi6:b-3h5e62) ([raw file](https://github.com/gramineproject/gramine/blob/ab44ea8cd7d201a1e05dd841a5208a08c7317a09/subprojects/mbedtls-3.6.1.wrap#L4)):*
> ```
> directory = mbedtls-3.6.1
> source_url = https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.1/mbedtls-3.6.1.tar.bz2
> source_fallback_url = https://packages.gramineproject.io/distfiles/mbedtls-3.6.1.tar.bz2
> ```

@woju: Would you pls help mirror this file? I'll test it afterwards. Thanks!



_Code quote:_
```
https://packages.gramineproject.io/distfiles/mbedtls-3.6.1.tar.bz2
```


<!-- Sent from Reviewable.io -->

2024-10-10 17:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`subprojects/mbedtls-3.6.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pFj6A40a0DZ-uWxi5:-O8rNg-G3cCkKwcRybrE:b-896fja) ([raw file](https://github.com/gramineproject/gramine/blob/ab44ea8cd7d201a1e05dd841a5208a08c7317a09/subprojects/mbedtls-3.6.1.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: Would you pls help mirror this file? I'll test it afterwards. Thanks!
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2024-10-10 17:55 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-10-11 09:13 UTC, woju submitted a review, later dismissed
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pI-ic5IiY7GfKEMa0):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Though we should not impacted by the CVEs (pls see below), we may still want this update to pass BDBA scans which flag the high severity CVE.
</blockquote></details>

Can you please include those explanations, why we're not affected, into the commit message itself?


<!-- Sent from Reviewable.io -->

2024-10-14 06:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: 7 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pI-ic5IiY7GfKEMa0):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can you please include those explanations, why we're not affected, into the commit message itself?
</blockquote></details>

Done.
___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/2024#-O98hWWp8NdFQSC2dZyo):*
I did't want to introduce this change as it was not required for mbedTLS source release versions < v3.6.1. Unfortunately, I haven't heard back from the mbedTLS team yet (but we're in a release phase).



_Code quote:_
```
  This commit also adds `python3-jsonschema` to Dockerfiles, which is a
  dependency for mbedTLS v3.6.1 source release. See
  https://github.com/Mbed-TLS/mbedtls/issues/6596#issuecomment-2404530040
  for more details.
```
___
*[`subprojects/mbedtls-3.6.1.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2024#-O8pFj6A40a0DZ-uWxi5:-O98hCvqDUiDYpnzIBAG:bymvf3n) ([raw file](https://github.com/gramineproject/gramine/blob/ab44ea8cd7d201a1e05dd841a5208a08c7317a09/subprojects/mbedtls-3.6.1.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Tested, everything works fine.


<!-- Sent from Reviewable.io -->

2024-10-15 11:05 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2024#-O9Ep5YQ7YAhcT-2WlAw:-O9Ep5YQ7YAhcT-2WlAx:b-8kfitn) (no related file):*
@woju: Please check this against the new 22.04+24.04 pipelines (assuming this will be merged after them).

___
___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/gramineproject/gramine/2024#-O9EpEY09OmZn5sJQZiE):*
btw, a note: that official severity for bugs is quite useless, please don't look at it. It's often set by people who don't actually fully understand the bugs, and the real severity actually depends on the specific usecases - e.g. we may not use a configuration which exposes a high-severity bug, but use one which makes a low-severity bug an RCE.

So, I wouldn't even mention the severity here, as it doesn't really matter. But not blocking.


<!-- Sent from Reviewable.io -->

2024-10-18 04:34 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/2024#-O98hWWp8NdFQSC2dZyo):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I did't want to introduce this change as it was not required for mbedTLS source release versions < v3.6.1. Unfortunately, I haven't heard back from the mbedTLS team yet (but we're in a release phase).
</blockquote></details>

Interestingly, after a quick test, mbedTLS v3.6.2 source release (https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.2/mbedtls-3.6.2.tar.bz2) does not require this dependency.


<!-- Sent from Reviewable.io -->

2024-10-18 06:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2024)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/2024#-O98hWWp8NdFQSC2dZyo):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Interestingly, after a quick test, mbedTLS v3.6.2 source release (https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.2/mbedtls-3.6.2.tar.bz2) does not require this dependency.
</blockquote></details>

So looks like we can skip v3.6.1 (this PR) and immediately merge v3.6.2 (PR #2039). Let me put a blocking comment here, to not accidentally merge this one.


<!-- Sent from Reviewable.io -->

2024-10-21 22:43 UTC, closed without merging