[mbedtls] Upgrade mbedTLS to version 3.6.2
gramineproject/gramine pull request #2039
Opened 2024-10-18 03:30 UTC by kailun-qin

## Description of the changes 

This upgrade includes fixes for four CVEs that affect Mbed TLS but not Gramine:
* CVE-2024-45158: we don't use affected functions: `mbedtls_ecdsa_der_to_raw()` or `mbedtls_ecdsa_raw_to_der()`.
* CVE-2024-45159: we don't enable TLS 1.3 for internal Gramine PAL crypto/TLS and control server certificates (that don't use `keyUsage` or `extKeyUsage` extensions) in the `ra-tls-mbedtls` CI-example.
* CVE-2024-45157: we don't enable the affected configuration: `MBEDTLS_PSA_HMAC_DRBG_MD_TYPE`.
* CVE-2024-49195: we use `mbedtls_pk_write_key_der()` with a buffer that is large enough for the content.

Closes https://github.com/gramineproject/gramine/pull/2024.

## How to test this PR? 

CI.

2024-10-18 04:38 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/2039#-O9SuH_m7-Q42RxXny6i):*
Pls see https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2024-10-1/#vulnerability and https://github.com/gramineproject/gramine/blob/5e2f18f5392204dea4cb300e21ed089f512cd581/tools/sgx/ra-tls/ra_tls_attest.c#L651-L670 for details.



_Code quote:_
```
  * CVE-2024-49195: we use `mbedtls_pk_write_key_der()` with a buffer that
    is large enough for the content.
```
___
*[`subprojects/mbedtls-3.6.2.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2039#-O9SuPjwCcyYGdJD-ZBw:-O9SuPjwCcyYGdJD-ZBx:b-hzmhg0) ([raw file](https://github.com/gramineproject/gramine/blob/5cd832c6a3fc96bcec44ab7ecb116253406df3b6/subprojects/mbedtls-3.6.2.wrap#L4)):*
> ```
> directory = mbedtls-3.6.2
> source_url = https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.2/mbedtls-3.6.2.tar.bz2
> source_fallback_url = https://packages.gramineproject.io/distfiles/mbedtls-3.6.2.tar.bz2
> ```

@woju: Sorry to bother again, but a newer mbedTLS (v3.6.2) was just released: https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2. Would you pls help mirror this file? Thanks!



_Code quote:_
```
https://packages.gramineproject.io/distfiles/mbedtls-3.6.2.tar.bz2
```


<!-- Sent from Reviewable.io -->

2024-10-18 06:59 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[`subprojects/mbedtls-3.6.2.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2039#-O9SuPjwCcyYGdJD-ZBw:-O9TPn9f5KrX5hFzrppU:b-hjnido) ([raw file](https://github.com/gramineproject/gramine/blob/5cd832c6a3fc96bcec44ab7ecb116253406df3b6/subprojects/mbedtls-3.6.2.wrap#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

@woju: Sorry to bother again, but a newer mbedTLS (v3.6.2) was just released: https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2. Would you pls help mirror this file? Thanks!
</blockquote></details>

@woju And https://packages.gramineproject.io/distfiles/mbedtls-3.6.1.tar.bz2 can be removed (as we just skip this version in favor of the newer one).


<!-- Sent from Reviewable.io -->

2024-10-22 10:20 UTC, woju approved these changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`subprojects/mbedtls-3.6.2.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2039#-O9SuPjwCcyYGdJD-ZBw:-O9nilTq2KrtkokawOSr:b-h0t2nx) ([raw file](https://github.com/gramineproject/gramine/blob/5cd832c6a3fc96bcec44ab7ecb116253406df3b6/subprojects/mbedtls-3.6.2.wrap#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju And https://packages.gramineproject.io/distfiles/mbedtls-3.6.1.tar.bz2 can be removed (as we just skip this version in favor of the newer one).
</blockquote></details>

Done. I'll keep 3.6.1, it's just 5 MB.


<!-- Sent from Reviewable.io -->

2024-10-22 22:42 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2024-10-23 02:25 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`subprojects/mbedtls-3.6.2.wrap` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2039#-O9SuPjwCcyYGdJD-ZBw:-O9rB7b389DQqxq6iWrd:bmip08r) ([raw file](https://github.com/gramineproject/gramine/blob/5cd832c6a3fc96bcec44ab7ecb116253406df3b6/subprojects/mbedtls-3.6.2.wrap#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. I'll keep 3.6.1, it's just 5 MB.
</blockquote></details>

Thanks! Tested -- everything works.


<!-- Sent from Reviewable.io -->

2024-10-24 10:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2039)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-24 10:33 UTC, merged