[LibOS] Fix memmgr free list performance bug
gramineproject/gramine pull request #2052
Opened 2024-11-07 09:19 UTC by adrianlut

[LibOS] Fix memmgr free list performance bug

Fixes the memmgr performance bug described in #2033 by changing the `CHECK_LIST_HEAD` macro in `common/include/list.h` in release mode to `(void)0`.

## Description of the changes 

To fix the issue described in #2033, this PR surrounds the `CHECK_LIST_HEAD` macro defined in 
[common/include/list.h](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/common/include/list.h) 
with `#ifdef DEBUG`. In release mode, the macro is now replaced with `(void)0`.

This macro is currently only used in `memmgr.h`. Thus, changing it directly was the simplest fix of the performance bug.

Fixes #2033

## How to test this PR?

2024-11-07 12:31 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2052)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adrianlut)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2052#-OB5Z6qX0XhH9RgJ4krr):*
Please wrap (see https://commit.style/).
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/2052#-OB5Zc2E6Z5yfl577ZkE):*
We don't reference GitHub issues in the commits, we try to keep the git repo standalone. One reason for that is that this will turn into a dangling pointer if we'd move the repository somewhere else.



_Code quote:_
```
#2033
```


<!-- Sent from Reviewable.io -->

2024-11-07 12:31 UTC, mkow commented
Jenkins, test this please

2024-11-07 13:21 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2052)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-11-07 13:21 UTC, mkow commented
Jenkins, retest this please

2024-11-12 12:42 UTC, mkow commented
Jenkins, retest this please

2024-11-12 15:56 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2052)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-14 12:25 UTC, mkow commented
Jenkins, retest this please (a lot of connectivity errors on Jenkins, e.g. `Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@258ebcb3:penguins-3-noble": Remote call on penguins-3-noble failed. The channel is closing down or has closed down`)

2024-11-14 15:03 UTC, mkow commented
Jenkins, retest Jenkins-Direct-24.04 please (connectivity issues in CI again)

2024-11-14 15:03 UTC, mkow commented
Jenkins, retest Jenkins-SGX-24.04-musl please (connectivity issues in CI again)

2024-11-14 15:25 UTC, merged