[Docs] Update pytorch docs to add support for Ubuntu 24.04
gramineproject/gramine pull request #2063
Opened 2024-11-18 09:52 UTC by adarshan-intel

## Description of the changes 
- This PR implements changes in Gramine docs caused by https://github.com/gramineproject/examples/pull/109
- Update Gramine version links
- Update the warning section to recommend using a virtual environment (venv) if running Ubuntu 24.04

## How to test this PR? 
Should be merged after https://github.com/gramineproject/examples/pull/109 is merged

2024-11-18 18:33 UTC, efu39 reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2024-11-19 05:47 UTC, adarshan-intel commented
@mkow @woju Can you review?

2024-11-27 06:12 UTC, adarshan-intel commented
@kailun-qin @mkow @woju Can you review?

2024-11-28 08:01 UTC, adarshan-intel commented
@woju @mkow Please review

2024-12-03 06:27 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODA9lr4-50D-XYS1IeS:b-kklesf):*
-> `[Docs] Update PyTorch tutorial`



_Code quote:_
```
[Docs] Update pytorch docs to add support for Ubuntu 24.04
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9zzD3v7EhkBGGTl6:-ODA9zzD3v7EhkBGGTl7:b-cklkki) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L95)):*
> ```reStructuredText
>   the compute platform).
> 
> - Gramine v1.8, with DCAP support. DCAP software infrastructure must also be
> ```

We remove the notes above but we still pin to a specific Gramine version?



_Code quote:_
```reStructuredText
Gramine v1.8
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 102 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAC9iA9SRZ6HcbpSe:-ODAAC9iA9SRZ6HcbpSf:b8dwx2v) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L102)):*
> ```reStructuredText
> .. warning::
> 
>    After running Ubuntu 24.04, it is highly recommended to use a virtual environment to manage
> ```

Is this recommended or required for Ubuntu 24.04?



_Code quote:_
```reStructuredText
After running Ubuntu 24.04, it is highly recommended to use a virtual environment
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAsAl3fqQbiZ3fxs1:-ODAAsAmDbIL8rUeEEm3:b-vsicon) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L124)):*
> ```reStructuredText
> Go to the directory with Gramine's PyTorch example::
> 
>    git clone --depth 1 --branch v1.8 https://github.com/gramineproject/examples.git
> ```

ditto (pin to specific version). And this branch does not contain your updates to the PyTorch example -- meaning that this won't actually work for Ubuntu 24.04?



_Code quote:_
```reStructuredText
--branch v1.8
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODAA9Hu28Cc-vFslemd:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
> ```reStructuredText
> repository), so let's build the secret provisioning server::
> 
>    git clone --depth 1 --branch v1.8 https://github.com/gramineproject/gramine.git
> ```

ditto



_Code quote:_
```reStructuredText
v1.8
```


<!-- Sent from Reviewable.io -->

2024-12-03 06:50 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODAEI3bCe6IWDuUYiZz:b-896fix):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `[Docs] Update PyTorch tutorial`
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9zzD3v7EhkBGGTl6:-ODAEkdyC7Ldz19WpiYd:bohwnxt) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L95)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

We remove the notes above but we still pin to a specific Gramine version?
</blockquote></details>

Done.
Removing pinning of versions
___
*[`Documentation/tutorials/pytorch/index.rst` line 102 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAC9iA9SRZ6HcbpSe:-ODAF5vh1IamH3gJLIMk:bkdas25) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L102)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Is this recommended or required for Ubuntu 24.04?
</blockquote></details>

It is a must case, so making it required
___
*[`Documentation/tutorials/pytorch/index.rst` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAsAl3fqQbiZ3fxs1:-ODAFAXx4mzBLCLkD1a5:bohwnxt) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L124)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto (pin to specific version). And this branch does not contain your updates to the PyTorch example -- meaning that this won't actually work for Ubuntu 24.04?
</blockquote></details>

Done.
Removing pinning of versions
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODAFEhq611u1QbyNfKU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-04 02:13 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`Documentation/tutorials/pytorch/index.rst` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODER5I4-yT14qgCSUKG:-ODER5I4-yT14qgCSUKH:b-5phgku) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L99)):*
> ```reStructuredText
> 
> Please refer to the `Gramine Attestation Documentation
> <https://gramine.readthedocs.io/en/latest/attestation.html>`__ for more details.
> ```

Pls align and wrap.



_Code quote:_
```reStructuredText
- Gramine with DCAP support. DCAP software infrastructure must also be
   installed.

Please refer to the `Gramine Attestation Documentation
<https://gramine.readthedocs.io/en/latest/attestation.html>`__ for more details.
```


<!-- Sent from Reviewable.io -->

2024-12-04 02:20 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODESrrZ-MRKTRxaWhDb:bfhqmln):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[`Documentation/tutorials/pytorch/index.rst` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAsAl3fqQbiZ3fxs1:-ODESjga4eHVyHpoAKsY:brnmtw3) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L124)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Removing pinning of versions
</blockquote></details>

But why remove `--depth 1`?
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODESprZ7tpcd4SmlY2C:brnmtw3) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But why remove `--depth 1`?


<!-- Sent from Reviewable.io -->

2024-12-04 10:41 UTC, woju requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @kailun-qin)

___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODGCbLJAtMzaCIc65Bz:boe37xp) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But why remove `--depth 1`?
</blockquote></details>

This is wrong: when you clone something from git without pinning to a tag, you might get newer version than packages support. Recently we had this problem with entrypoint: the option was removed from manifests in examples, but the released (packaged) version still required it, so if someone just cloned examples, they didn't work. So no, you need to keep `--branch`.

If you want this to be moved to last stable release, you can use `|stable-checkout|` like this (note `parsed-literal` instead of `::`-block):

```rst
.. parsed-literal::

   git clone --depth 1 |stable-checkout| \https://github.com/gramineproject/examples.git

```

cf.:

https://github.com/gramineproject/gramine/blob/5789620a6d04208e5803321953e09eca2c24dd7b/Documentation/run-sample-application.rst#L9-L11

I'm not sure about `examples.git`, they might be OK to just clone, so I didn't block the other discussion.
___
*[`Documentation/tutorials/pytorch/index.rst` line 88 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODGALBL7PHJN5j65Ztt:-ODGALBL7PHJN5j65Ztu:b-fmu1dp) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L88)):*
> ```reStructuredText
> -------------
> 
> - A Linux-based operating system (e.g., Ubuntu 20.04 or later)
> ```

Gramine supports 22.04 or later, please update. I know that maybe this howto works with 20.04, but we don't want people to file issues for 20.04 anymore.



_Suggestion:_
```reStructuredText
Ubuntu 22.04
```
___
*[`Documentation/tutorials/pytorch/index.rst` line 103 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODGD-MVD0E1Tg8wb8Xk:-ODGD-MW1ti7sDT13Q1a:b-aek4zj) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L103)):*
> ```reStructuredText
> .. warning::
> 
>    After running Ubuntu 24.04, it is required to use a virtual environment to manage
> ```

"After running Ubuntu 24.04" sounds weird, needs to be rephrased. Something like "If you're on a recent distro that implements PEP 668 (e.g. Debian 12, Ubuntu 24.04), it is required ..."?


<!-- Sent from Reviewable.io -->

2024-12-05 04:08 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODJwmi93FzHdP_Rm0Ou:b-896fix):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 124 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAAsAl3fqQbiZ3fxs1:-ODJyGInDviOWDlwcLX9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L124)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But why remove `--depth 1`?
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODK-4Rg0QeKC3tdM-8w:b-73lydy) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is wrong: when you clone something from git without pinning to a tag, you might get newer version than packages support. Recently we had this problem with entrypoint: the option was removed from manifests in examples, but the released (packaged) version still required it, so if someone just cloned examples, they didn't work. So no, you need to keep `--branch`.

If you want this to be moved to last stable release, you can use `|stable-checkout|` like this (note `parsed-literal` instead of `::`-block):

```rst
.. parsed-literal::

   git clone --depth 1 |stable-checkout| \https://github.com/gramineproject/examples.git

```

cf.:

https://github.com/gramineproject/gramine/blob/5789620a6d04208e5803321953e09eca2c24dd7b/Documentation/run-sample-application.rst#L9-L11

I'm not sure about `examples.git`, they might be OK to just clone, so I didn't block the other discussion.
</blockquote></details>

I believe cloning examples repo would be just fine, as of not just keeping to latest commit with depth 1 will change upon request 
___
*[`Documentation/tutorials/pytorch/index.rst` line 88 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODGALBL7PHJN5j65Ztt:-ODJwvjcBN-FwOt5t22C:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L88)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Gramine supports 22.04 or later, please update. I know that maybe this howto works with 20.04, but we don't want people to file issues for 20.04 anymore.
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODER5I4-yT14qgCSUKG:-ODJxep-4X450n4KwJ-3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L99)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls align and wrap.
</blockquote></details>

Done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 103 at r2](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODGD-MVD0E1Tg8wb8Xk:-ODJxv4Y2T6nTs9bLVdb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/aca2ee7a3e11b9ea347c4b940d26d6ba712910bf/Documentation/tutorials/pytorch/index.rst#L103)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"After running Ubuntu 24.04" sounds weird, needs to be rephrased. Something like "If you're on a recent distro that implements PEP 668 (e.g. Debian 12, Ubuntu 24.04), it is required ..."?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 12:44 UTC, woju requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODLpH4I31WQ_LfYOR8O:b-kwadt9):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, you didn't. You need to either rework the commits itself (`git commit --amend` and/or `git rebase -i --autosquash $(git merge-base HEAD origin/master)` — be careful not to move branch base, because it messes reviewer's workflow), or you need to post `amend!` commit (`git commit --fixup=amend:...`) for this review discussion to be "Done".
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODLotYW42R0qqmRChxH:b-2afeub) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I believe cloning examples repo would be just fine, as of not just keeping to latest commit with depth 1 will change upon request
</blockquote></details>

Yes, but here you clone `gramine.git` itself. As I explained, you need to specify `--branch`, either explicitly, or through `|stable-checkout|`.


<!-- Sent from Reviewable.io -->

2024-12-06 05:39 UTC, adarshan-intel commented
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODPRnfd5-zl3FF4MF8A:bopbfzh) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, but here you clone `gramine.git` itself. As I explained, you need to specify `--branch`, either explicitly, or through `|stable-checkout|`.
</blockquote></details>

Earlier, I was confused why `|stable-checkout|` was not working. Then I wrapped it with backticks (\`\`), and it worked. I believe this is what you were suggesting?


<!-- Sent from Reviewable.io -->

2024-12-06 05:46 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODPV7XU2A03oH-_m-an:bnezt58):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, you didn't. You need to either rework the commits itself (`git commit --amend` and/or `git rebase -i --autosquash $(git merge-base HEAD origin/master)` — be careful not to move branch base, because it messes reviewer's workflow), or you need to post `amend!` commit (`git commit --fixup=amend:...`) for this review discussion to be "Done".
</blockquote></details>

I have done interactive rebase.
Can you check if it is done now?


<!-- Sent from Reviewable.io -->

2024-12-06 09:12 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODQDEf48B8WEbbtwx9m:bhu6cgi) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
> Then I wrapped it with backticks (\`\`), and it worked

What you mean by working?

I think what woju was suggesting is to use the `parsed-literal` reST directive for that "git clone ..." block of text, same as here: https://github.com/gramineproject/gramine/blob/5789620a6d04208e5803321953e09eca2c24dd7b/Documentation/run-sample-application.rst?plain=1#L9-L11.


<!-- Sent from Reviewable.io -->

2024-12-06 09:30 UTC, adarshan-intel commented
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODQIaC10OLTPtD8OnND:b-wx500t) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Then I wrapped it with backticks (\`\`), and it worked

What you mean by working?

I think what woju was suggesting is to use the `parsed-literal` reST directive for that "git clone ..." block of text, same as here: https://github.com/gramineproject/gramine/blob/5789620a6d04208e5803321953e09eca2c24dd7b/Documentation/run-sample-application.rst?plain=1#L9-L11.
</blockquote></details>

Something like this?


<!-- Sent from Reviewable.io -->

2024-12-06 10:59 UTC, woju requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODQbEhOAK6-2usJjvD4:b-8gfvu1):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I have done interactive rebase.
Can you check if it is done now?
</blockquote></details>

Yes, you did rebase, but you didn't change the title of the commit as @kailun-qin asked (and then proceeded to add a couple of extra `fixup!` commits). Still not done.
___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODQYoTK8fgVDJcVpkHg:b-1g2mrp) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/140046984/FrhjTaFTvRDibkIs-EGwbprc/image.png)
But when I run `make html`, the documentation doesn’t display correctly
</blockquote></details>

Yes, that's expected: it's hidden until you tag the version and add `READTHEDOCS=1 READTHEDOCS_VERSION=stable` to `make html`. Unless you do that, it will be hidden, as it should.

There's a catch though, it currently fails without this PR: #2073.

```sh
make clean
git tag v123456-TEST
make html READTHEDOCS=1 READTHEDOCS_VERSION=stable
git tag -d v123456-TEST
firefox _build/html/index.html
```

So this particular section LGTM. I've tested it provisionally rebased on top of #2073 and it works fine (with double-colon fixed to single colon):

![image.png](https://files.reviewableusercontent.io/images/reviewable/1550337/vgAKOmSKUdOTXLN1-lmogivz/image.png)
___
*[`Documentation/tutorials/pytorch/index.rst` line 376 at r8](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODQawVQ3aFGEM-lOzt5:-ODQawVQ3aFGEM-lOzt6:b-3b80x1) ([raw file](https://github.com/gramineproject/gramine/blob/fd0d71fdcdf8700524a0c53420b1e4739d93e5df/Documentation/tutorials/pytorch/index.rst#L376)):*
> ```reStructuredText
> We will use the reference implementation of the Secret Provisioning server found
> under ``CI-Examples/ra-tls-secret-prov`` directory (in the core Gramine
> repository), so let's build the secret provisioning server::
> ```

This double colon you need to fix to single colon for the block to render properly (see screenshot in next discussion).



_Suggestion:_
```reStructuredText
server:
```


<!-- Sent from Reviewable.io -->

2024-12-09 07:17 UTC, adarshan-intel commented
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODeGbPv46M_8VEhJ7Ne:bdn3ytq):*
> Yes, you did rebase, but you didn't change the title of the commit as [@kailun-qin](https://github.com/kailun-qin) asked (and then proceeded to add a couple of extra `fixup!` commits). Still not done.

![image.png](https://files.reviewableusercontent.io/images/reviewable/140046984/2HUcjSUiXIy9TRqXP7mL_ncF/image.png)
In my commit history I can see the name, `[Docs] Update PyTorch tutorial`, this is the name which is expected right?
Or am I missing something>


<!-- Sent from Reviewable.io -->

2024-12-09 07:17 UTC, adarshan-intel commented
*[`Documentation/tutorials/pytorch/index.rst` line 376 at r8](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODQawVQ3aFGEM-lOzt5:-ODeGtDyBf51j8kA-z7y:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fd0d71fdcdf8700524a0c53420b1e4739d93e5df/Documentation/tutorials/pytorch/index.rst#L376)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This double colon you need to fix to single colon for the block to render properly (see screenshot in next discussion).
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-09 07:18 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 377 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODAA9Hu28Cc-vFslemc:-ODeH0mT0em3dPbux9Wo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/208c8acb7664bf3aa8af3a94942793a683995d26/Documentation/tutorials/pytorch/index.rst#L377)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, that's expected: it's hidden until you tag the version and add `READTHEDOCS=1 READTHEDOCS_VERSION=stable` to `make html`. Unless you do that, it will be hidden, as it should.

There's a catch though, it currently fails without this PR: #2073.

```sh
make clean
git tag v123456-TEST
make html READTHEDOCS=1 READTHEDOCS_VERSION=stable
git tag -d v123456-TEST
firefox _build/html/index.html
```

So this particular section LGTM. I've tested it provisionally rebased on top of #2073 and it works fine (with double-colon fixed to single colon):

![image.png](https://files.reviewableusercontent.io/images/reviewable/1550337/vgAKOmSKUdOTXLN1-lmogivz/image.png)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 18:00 UTC, woju requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODA9lr4-50D-XYS1IeR:-ODgZYp45dueXApFwQ4I:bx9lv9p):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

> Yes, you did rebase, but you didn't change the title of the commit as [@kailun-qin](https://github.com/kailun-qin) asked (and then proceeded to add a couple of extra `fixup!` commits). Still not done.

![image.png](https://files.reviewableusercontent.io/images/reviewable/140046984/2HUcjSUiXIy9TRqXP7mL_ncF/image.png)
In my commit history I can see the name, `[Docs] Update PyTorch tutorial`, this is the name which is expected right?
Or am I missing something>
</blockquote></details>

Ah, ok. I misread, sorry for the confusion.
___
*[`Documentation/tutorials/pytorch/index.rst` line 376 at r8](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODQawVQ3aFGEM-lOzt5:-ODgZGqt0ihNS7FM1poz:b-bkg5qi) ([raw file](https://github.com/gramineproject/gramine/blob/fd0d71fdcdf8700524a0c53420b1e4739d93e5df/Documentation/tutorials/pytorch/index.rst#L376)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not done, wrong `server::`.
___
*[`Documentation/tutorials/pytorch/index.rst` line 446 at r9](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODgZyOn8AJDAQfQU3hQ:-ODgZyOn8AJDAQfQU3hR:b-bt7uvc) ([raw file](https://github.com/gramineproject/gramine/blob/6dbdc50448a2f60bc4b8464a63cbdc8ccf445d2c/Documentation/tutorials/pytorch/index.rst#L446)):*
> ```reStructuredText
> and use them.
> 
> Now we can launch the secret provisioning server:
> ```

This was OK, please revert.



_Suggestion:_
```reStructuredText
server::
```


<!-- Sent from Reviewable.io -->

2024-12-10 05:05 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 376 at r8](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODQawVQ3aFGEM-lOzt5:-ODixAHt9rn9Rdyjhg0g:b-ynx0ny) ([raw file](https://github.com/gramineproject/gramine/blob/fd0d71fdcdf8700524a0c53420b1e4739d93e5df/Documentation/tutorials/pytorch/index.rst#L376)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not done, wrong `server::`.
</blockquote></details>

Done.
Good catch, I made changes at other place.
___
*[`Documentation/tutorials/pytorch/index.rst` line 446 at r9](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODgZyOn8AJDAQfQU3hQ:-ODiwjUx9aU0lF0cFh8N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6dbdc50448a2f60bc4b8464a63cbdc8ccf445d2c/Documentation/tutorials/pytorch/index.rst#L446)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This was OK, please revert.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 08:05 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-12-12 05:37 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 376 at r8](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODQawVQ3aFGEM-lOzt5:-ODtMqyKA0p0-00diHYo:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/fd0d71fdcdf8700524a0c53420b1e4739d93e5df/Documentation/tutorials/pytorch/index.rst#L376)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Good catch, I made changes at other place.
</blockquote></details>

Done
___
*[`Documentation/tutorials/pytorch/index.rst` line 446 at r9](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODgZyOn8AJDAQfQU3hQ:-ODtMnm5EriuLVeQSimZ:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/6dbdc50448a2f60bc4b8464a63cbdc8ccf445d2c/Documentation/tutorials/pytorch/index.rst#L446)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-12 05:40 UTC, adarshan-intel reviewed
@woju Have updated the `server:` typo at both places, any more changes TODO ?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063#-:-ODtNBIWEhXJkri8OKLD:b-bpc93o)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-12-12 17:49 UTC, woju approved these changes
No, I think it's all done, thanks!

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063#-:-ODvzNX-9YVml6Dj03bq:b-4j6qpz)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-13 01:01 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 380 at r10](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODwDkGq9-21sq-a764t:-ODxXD806XDrCzIkAWr7:b-vehqwr) ([raw file](https://github.com/gramineproject/gramine/blob/89ea11cedf6fc2bae5d33eaa2be26470538cf307/Documentation/tutorials/pytorch/index.rst#L380)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is replaced with nothing, I guess it shouldn't work like that? See https://gramine--2063.org.readthedocs.build/en/2063/run-sample-application.html.
It seems to also be broken in `run-sample-application.rst`, see https://gramine.readthedocs.io/en/stable/run-sample-application.html.
CC: @woju
</blockquote></details>

This works for the specific version: https://gramine.readthedocs.io/en/v1.8/run-sample-application.html?


<!-- Sent from Reviewable.io -->

2024-12-13 02:17 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 380 at r10](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODwDkGq9-21sq-a764t:-ODxnVKCD5ghUcLHq555:b-9owbp9) ([raw file](https://github.com/gramineproject/gramine/blob/89ea11cedf6fc2bae5d33eaa2be26470538cf307/Documentation/tutorials/pytorch/index.rst#L380)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This works for the specific version: https://gramine.readthedocs.io/en/v1.8/run-sample-application.html?
</blockquote></details>

Ok, but it seems wrong for `/en/stable/` links, it should point to the latest release?


<!-- Sent from Reviewable.io -->

2024-12-13 06:43 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`Documentation/tutorials/pytorch/index.rst` line 380 at r10](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODwDkGq9-21sq-a764t:-ODyjeIu4l9n6NkhGQb4:bqfjox1) ([raw file](https://github.com/gramineproject/gramine/blob/89ea11cedf6fc2bae5d33eaa2be26470538cf307/Documentation/tutorials/pytorch/index.rst#L380)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but it seems wrong for `/en/stable/` links, it should point to the latest release?
</blockquote></details>

Yep, it should. But our ReadTheDocs `stable` branch (which you referred to) still points to the v1.8 tagging commit w/o the `--branch` fix: https://github.com/gramineproject/gramine/pull/2073/commits/c9e2d3f7cf618b432edbc0e9035a5008093428f2 so it's still failing.


<!-- Sent from Reviewable.io -->

2024-12-13 12:30 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`Documentation/tutorials/pytorch/index.rst` line 380 at r10](https://reviewable.io/reviews/gramineproject/gramine/2063#-ODwDkGq9-21sq-a764t:-ODzzte21ZZgWGLPuMIP:b5yjjet) ([raw file](https://github.com/gramineproject/gramine/blob/89ea11cedf6fc2bae5d33eaa2be26470538cf307/Documentation/tutorials/pytorch/index.rst#L380)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yep, it should. But our ReadTheDocs `stable` branch (which you referred to) still points to the v1.8 tagging commit w/o the `--branch` fix: https://github.com/gramineproject/gramine/pull/2073/commits/c9e2d3f7cf618b432edbc0e9035a5008093428f2 so it's still failing.
</blockquote></details>

Aaaah, right, I see. Resolving then.


<!-- Sent from Reviewable.io -->

2024-12-13 15:17 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-16 05:33 UTC, adarshan-intel commented
Can we merge this?

2024-12-22 17:39 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-22 17:39 UTC, mkow commented
Jenkins, retest this please

2024-12-23 01:03 UTC, mkow commented
I'm merging this one without re-running `linux-sgx-vm-gcc-release` pipeline, it failed because of some network issue (couldn't establish TLS to busybox.net) and this PR is documentation-only.

2024-12-23 01:04 UTC, merged