[CI-Examples] Update README.md with client variable setup
gramineproject/gramine pull request #2071
Opened 2024-11-28 07:54 UTC by adarshan-intel

## Description of the changes 
Updated `README.md` in `CI-Examples/ra-tls-secret-prov` to include:

- Setup instructions and commands for `RA_TLS_MRSIGNER`, `RA_TLS_MRENCLAVE`, `RA_TLS_ISV_PROD_ID`, and `RA_TLS_ISV_SVN` environment variables.
- Added `make check_dcap` command.

For more details, refer https://github.com/gramineproject/gramine/pull/1870

If this measurement variables are not set, you may face issues such as:
```
Allowing quote status SW_HARDENING_NEEDED
getenv_critical: ERROR: A required environment variable RA_TLS_MRSIGNER is not set.
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
client_connection: ra_tls_verify_callback_results:
    attestation_scheme=2, err_loc=5, 
client_connection:     dcap.func_verify_quote_result=0x0, dcap.quote_verification_result=0xa007
make: *** [Makefile:189: check_dcap] Error 1
```
Not making changes to EPID workflow due to its EOL soon.

## How to test this PR? 
CI

2024-11-28 08:01 UTC, adarshan-intel commented
@woju @mkow Please review

2024-12-03 04:55 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9om1J0_RPi_AZm542:-OD9om1J0_RPi_AZm543:b-3319l6) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L81)):*
> ```Markdown
> 
>   For testing purposes,
>  you can set these values to `any` to skip verifying a particular measurement.
> ```

Pls wrap.



_Code quote:_
```Markdown
  For testing purposes,
 you can set these values to `any` to skip verifying a particular measurement.
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9prpz8K-oh6qwz_tn:-OD9prpz8K-oh6qwz_to:b-v7yzlb) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L81)):*
> ```Markdown
> 
>   For testing purposes,
>  you can set these values to `any` to skip verifying a particular measurement.
> ```

Why do we still want to set to `any`, given that we have that note above? Why not just `export RA_TLS_MRSIGNER=<MRSIGNER of the client enclave>`?



_Code quote:_
```Markdown
  For testing purposes,
 you can set these values to `any` to skip verifying a particular measurement.
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9rcmqEIbFSI5BUx3u:-OD9rcmqEIbFSI5BUx3v:bbbhj8u) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L135)):*
> ```Markdown
> 
> ```sh
> make check_dcap
> ```

But this not only runs all flows but also runs all three examples?



_Code quote:_
```Markdown
make check_dcap
```


<!-- Sent from Reviewable.io -->

2024-12-03 05:11 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9om1J0_RPi_AZm542:-OD9uSge0Ls1H-0ORtE0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L81)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls wrap.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9prpz8K-oh6qwz_tn:-OD9uzn97lmGDthkMhfY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L81)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why do we still want to set to `any`, given that we have that note above? Why not just `export RA_TLS_MRSIGNER=<MRSIGNER of the client enclave>`?
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/2071#-OD9rcmqEIbFSI5BUx3u:-OD9v5dL8tGbRFiQWtly:b-2aktbg) ([raw file](https://github.com/gramineproject/gramine/blob/29dc5ac7975ff1c44a972f0d7eef8cb5eeba5dde/CI-Examples/ra-tls-secret-prov/README.md#L135)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But this not only runs all flows but also runs all three examples?
</blockquote></details>

Done.
Yes it runs all 3 examples


<!-- Sent from Reviewable.io -->

2024-12-03 06:15 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 86 at r2](https://reviewable.io/reviews/gramineproject/gramine/2071#-ODA93uj5IXrTHrSqkB-:-ODA93uj5IXrTHrSqkB0:b-ur0lr7) ([raw file](https://github.com/gramineproject/gramine/blob/a25a7464a838e51f36c1e4f55fa3c734279e71f6/CI-Examples/ra-tls-secret-prov/README.md#L86)):*
> ```Markdown
> ```sh
> export RA_TLS_MRSIGNER=<MRSIGNER of the client enclave>
> export RA_TLS_MRENCLAVE=<MR_ENCLAVE of the client enclave>
> ```

-> `MRENCLAVE`



_Code quote:_
```Markdown
MR_ENCLAVE 
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 133 at r2](https://reviewable.io/reviews/gramineproject/gramine/2071#-ODA8mAl11chIt7PZuNY:-ODA8mAl11chIt7PZuNZ:b-smnf9h) ([raw file](https://github.com/gramineproject/gramine/blob/a25a7464a838e51f36c1e4f55fa3c734279e71f6/CI-Examples/ra-tls-secret-prov/README.md#L133)):*
> ```Markdown
> ```
> 
> - To run all the 3 examples in one go, you can use the following command:
> ```

-> all three (to be consistent with other places in this doc)



_Code quote:_
```Markdown
all the 3
```


<!-- Sent from Reviewable.io -->

2024-12-03 06:24 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 86 at r2](https://reviewable.io/reviews/gramineproject/gramine/2071#-ODA93uj5IXrTHrSqkB-:-ODAAvw08U7c-o61LuAO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a25a7464a838e51f36c1e4f55fa3c734279e71f6/CI-Examples/ra-tls-secret-prov/README.md#L86)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `MRENCLAVE`
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 133 at r2](https://reviewable.io/reviews/gramineproject/gramine/2071#-ODA8mAl11chIt7PZuNY:-ODABBkVEn14AFNfVPGG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a25a7464a838e51f36c1e4f55fa3c734279e71f6/CI-Examples/ra-tls-secret-prov/README.md#L133)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> all three (to be consistent with other places in this doc)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 06:28 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-04 00:40 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-12-05 06:00 UTC, adarshan-intel commented
@woju @mkow Please review

2024-12-13 15:18 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @adarshan-intel)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-_sEe5oTx-zt7_1bx:-OE-_sEe5oTx-zt7_1by:undefined):*




_Suggestion:_
```
[CI-Examples] Update README.md in RA-TLS secret provisioning example
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 105 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-aLqq3IQsoKJgcejw:-OE-aLqq3IQsoKJgcejx:b-tsqyac) ([raw file](https://github.com/gramineproject/gramine/blob/70471ad83b1570c17c2c3b482590ac4431dae8bc/CI-Examples/ra-tls-secret-prov/README.md#L105)):*
> ```Markdown
> 
> ```sh
> make app epid RA_TYPE=epid RA_CLIENT_SPID=<your SPID> \
> ```

This also is outdated.



_Code quote:_
```Markdown
epid
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 110 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-aPEb8aW0mAIPoc4R:-OE-aPEb8aW0mAIPoc4S:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/70471ad83b1570c17c2c3b482590ac4431dae8bc/CI-Examples/ra-tls-secret-prov/README.md#L110)):*
> ```Markdown
> # test encrypted files client (other examples can be tested similarly)
> cd secret_prov_pf
> RA_TLS_EPID_API_KEY=<your EPID API key> \
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-12-16 05:02 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-_sEe5oTx-zt7_1bx:-OECpxxOCRVg9FndibEU:b-896fix):*
Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 105 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-aLqq3IQsoKJgcejw:-OECq4ZO9cwoRkxhM9FP:b-nsx80n) ([raw file](https://github.com/gramineproject/gramine/blob/70471ad83b1570c17c2c3b482590ac4431dae8bc/CI-Examples/ra-tls-secret-prov/README.md#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This also is outdated.
</blockquote></details>

Done.
Have removed all references of EPID from this example
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 110 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-aPEb8aW0mAIPoc4R:-OECq5-75cDdkpyBQDJA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/70471ad83b1570c17c2c3b482590ac4431dae8bc/CI-Examples/ra-tls-secret-prov/README.md#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-16 05:32 UTC, adarshan-intel commented
Have resolved the merge conflicts introduced due to #2062

2024-12-16 05:34 UTC, adarshan-intel commented
*[`CI-Examples/ra-tls-secret-prov/README.md` line 105 at r4](https://reviewable.io/reviews/gramineproject/gramine/2071#-OE-aLqq3IQsoKJgcejw:-OECxZkNAPdLNDFRK-_R:b-eg9ad8) ([raw file](https://github.com/gramineproject/gramine/blob/70471ad83b1570c17c2c3b482590ac4431dae8bc/CI-Examples/ra-tls-secret-prov/README.md#L105)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Have removed all references of EPID from this example
</blockquote></details>

Have rebased the PR


<!-- Sent from Reviewable.io -->

2024-12-22 16:56 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 108 at r5](https://reviewable.io/reviews/gramineproject/gramine/2071#-OEjHwVLCj2ronPEM3nO:-OEjHwVMDFE2-2y1YGsr:b-ginpx0) ([raw file](https://github.com/gramineproject/gramine/blob/0b46a8b8870a1d1d1934125260b2b96133a80689/CI-Examples/ra-tls-secret-prov/README.md#L108)):*
> ```Markdown
> kill %%
> ```
> - To Run all the flows in one go, you can use the following command:
> ```

Why did you capitalize this?



_Code quote:_
```Markdown
Run
```
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 112 at r5](https://reviewable.io/reviews/gramineproject/gramine/2071#-OEjI5Ml3fRy6wkvbnZz:-OEjI5Ml3fRy6wkvbn_-:b2yoya2) ([raw file](https://github.com/gramineproject/gramine/blob/0b46a8b8870a1d1d1934125260b2b96133a80689/CI-Examples/ra-tls-secret-prov/README.md#L112)):*
> ```Markdown
> ```sh
> make check_dcap
> ```
> ```

missing newline at the end


<!-- Sent from Reviewable.io -->

2025-01-06 04:53 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 108 at r5](https://reviewable.io/reviews/gramineproject/gramine/2071#-OEjHwVLCj2ronPEM3nO:-OFtxDX2BblJAcaTvnfC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b46a8b8870a1d1d1934125260b2b96133a80689/CI-Examples/ra-tls-secret-prov/README.md#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you capitalize this?
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 112 at r5](https://reviewable.io/reviews/gramineproject/gramine/2071#-OEjI5Ml3fRy6wkvbnZz:-OFtxJtFEAru1V7jpfuN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0b46a8b8870a1d1d1934125260b2b96133a80689/CI-Examples/ra-tls-secret-prov/README.md#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing newline at the end
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-06 04:56 UTC, adarshan-intel commented
CI Test this

2025-01-06 15:11 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2025-01-06 15:12 UTC, mkow commented
Jenkins, retest this please

2025-01-06 15:24 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-07 06:51 UTC, kailun-qin commented
Jenkins, retest Jenkins-Direct-24.04 please (fdatasync01 from LTP timed out, known and unrelated to the PR)

2025-01-07 06:52 UTC, kailun-qin commented
Jenkins, retest Jenkins-Direct-24.04-Sanitizers please (ppoll01 LTP test failed, unrelated to this PR)

2025-01-07 07:38 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-07 08:18 UTC, kailun-qin commented
Jenkins, retest this please

2025-01-08 05:27 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 73 at r6](https://reviewable.io/reviews/gramineproject/gramine/2071#-OG-JqMq1fUzjKQ0uKZM:-OG3NVSf-oNLm198g_WK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6ebb82fb135933ad71ef9f00f0fa9c231aa654b0/CI-Examples/ra-tls-secret-prov/README.md#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you want nice "Note:", please make this an "alert": https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-08 06:28 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2025-01-08 09:12 UTC, woju approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2025-01-08 10:41 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-08 10:41 UTC, kailun-qin commented
Jenkins, retest this please

2025-01-09 06:36 UTC, adarshan-intel commented
We can proceed with the merge now.

2025-01-12 11:30 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-12 11:31 UTC, merged