[Docs] Fix `--branch` magic to not collide variable with sphinx tags
gramineproject/gramine pull request #2073
Opened 2024-11-29 09:26 UTC by woju

## Description of the changes 

See commit message.
Fixes: #2066

## How to test this PR? 

```sh
READTHEDOCS=1 READTHEDOCS_VERSION=stable make -C Documentation html
firefox Documentation/_build/html/run-sample-application.html
```
and look at the `git clone` invocation in the first listing. `make html` should be successful, but no `--branch` in the listing. Now:
```sh
make -C Documentation clean
git tag v123456-do-not-push
READTHEDOCS=1 READTHEDOCS_VERSION=stable make -C Documentation html
firefox Documentation/_build/html/run-sample-application.html
```
should succeed and have `--branch v123456-do-not-push` in the listing.

Remember to
```sh
git tag -d v123456-do-not-push
```
before you push.

(Before this commit `READTHEDOCS=... make` will fail as in https://readthedocs.org/projects/gramine/builds/26350000/)

2024-11-29 15:17 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2073#-OCsUhVj2xSv-lMs2PNl:-OCsUhVj2xSv-lMs2PNm:byny777):*
Why wasn't this problem detected by CI's Docs pipeline? Do I understand correctly, that it's because we don't test with `rtd_current_version == 'stable'`? Maybe we should?


<!-- Sent from Reviewable.io -->

2024-11-29 15:53 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2073)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2073#-OCsUhVj2xSv-lMs2PNl:-OCsawC6-QkJQDItkSwx:b-mtyn66):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why wasn't this problem detected by CI's Docs pipeline? Do I understand correctly, that it's because we don't test with `rtd_current_version == 'stable'`? Maybe we should?
</blockquote></details>

That's complicated, we'll have to create a testing tag for `git tag --points-at` to work. I'm not saying no, but we'd have to be careful with this tag not to push it anywhere (should someone change out CI to CD). I've pushed one possible version, see `docs.jenkinsfile`, but I'm not proud of that piece of engineering.


<!-- Sent from Reviewable.io -->

2024-12-11 22:48 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2073)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/2073#-OCsUhVj2xSv-lMs2PNl:-ODru-QW3gpjbW-AJE1W:b-8ial35):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

That's complicated, we'll have to create a testing tag for `git tag --points-at` to work. I'm not saying no, but we'd have to be careful with this tag not to push it anywhere (should someone change out CI to CD). I've pushed one possible version, see `docs.jenkinsfile`, but I'm not proud of that piece of engineering.
</blockquote></details>

I'm fine with it, assuming it detects errors like this one.


<!-- Sent from Reviewable.io -->

2024-12-12 02:35 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2073)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-12 09:55 UTC, merged