Fix some nitpicks and letfovers from other PRs
gramineproject/gramine pull request #2075
Opened 2024-12-13 15:57 UTC by mkow

## Description of the changes 

See the commits.

## How to test this PR? 

CI.

2024-12-13 16:04 UTC, woju requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-jmj-6om47oDvUQEz:-OE-jmj-6om47oDvUQF-:b-uc2577) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L19)):*
> ```C
>         /* DCAP and upstreamed version used different paths in the past. */
>         "/dev/sgx_enclave",
>         "/dev/sgx/enclave",
> ```

This one probably shouldn't go, it's the one from original DCAP driver, but still compatible, and there's no reason to remove it. Unless we want to instruct people to add custom udev rule if they use old DCAP driver, that will `SYMLINK+=` it.
___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OE-k-tu73yk7wVu8RSg:bxnzyh9) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
> ```
>         json.dump(sig_readable, output_txt, indent=4)
>     else:
>         # plaintext format imitates the legacy output of `gramine-sgx-get-token` tool
> ```

We've discussed it and resolved that it should remain, because it's still correct that this imitates this (now non-existent) tool: https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6W8vl-J2dK3hV7s4S


<!-- Sent from Reviewable.io -->

2024-12-17 20:09 UTC, chiache requested changes
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-jmj-6om47oDvUQEz:-OELCP46Dyq5SbgyuODD:b-9t6kir) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This one probably shouldn't go, it's the one from original DCAP driver, but still compatible, and there's no reason to remove it. Unless we want to instruct people to add custom udev rule if they use old DCAP driver, that will `SYMLINK+=` it.
</blockquote></details>

To me, it's okay to remove this logic if we instruct people to use the new DCAP driver. Potentially, we can add a warning if "/dev/sgx_enclave" does not exist in the system, but "/dev/sgx/enclave" does.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OELCnHh2NtZqgMQdYwv:-OELCnHh2NtZqgMQdYww:b-4umkl5) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L35)):*
> ```C
>     }
>     log_error("Cannot open SGX driver device. Please make sure you're using an up-to-date kernel "
>               "or the standalone Intel SGX kernel module is loaded.");
> ```

Why not keep this warning in case "/dev/sgx_enclave" does not exist? (i.e., ret = -ENOENT)? This warning is more informative and provide instructions to remedy the issue.


<!-- Sent from Reviewable.io -->

2024-12-22 17:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @chiache and @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-jmj-6om47oDvUQEz:-OEjP8i82p8KlEIEse8n:bbmqly0) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L19)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

To me, it's okay to remove this logic if we instruct people to use the new DCAP driver. Potentially, we can add a warning if "/dev/sgx_enclave" does not exist in the system, but "/dev/sgx/enclave" does.
</blockquote></details>

But I think we don't support kernels without the SGX driver built-in, which is incompatible with the DCAP driver?
Also, dropping the support has one more advantage IMO - we won't accidentally get bug reports for Gramine running on the older driver :)
___
*[`pal/src/host/linux-sgx/host_framework.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OELCnHh2NtZqgMQdYwv:-OEjQ8gs-tiS7mpEwg5z:b-e76ea1) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L35)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Why not keep this warning in case "/dev/sgx_enclave" does not exist? (i.e., ret = -ENOENT)? This warning is more informative and provide instructions to remedy the issue.
</blockquote></details>

But the error above has all this info, excluding the deprecated part? There's no mention about updating the kernel, because all the supported distros already have it.
___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OEjR7v73D0KMblcjoZr:b-rokock) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We've discussed it and resolved that it should remain, because it's still correct that this imitates this (now non-existent) tool: https://reviewable.io/reviews/gramineproject/gramine/2061#-OC6W8vl-J2dK3hV7s4S
</blockquote></details>

Ah, I missed that discussion. But why would we keep this comment if this tool doesn't exist anymore? It doesn't give the reader any useful information?


<!-- Sent from Reviewable.io -->

2024-12-23 19:58 UTC, chiache submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-jmj-6om47oDvUQEz:-OEp4VAP5uLsSdfKFHzm:b1z4v20) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But I think we don't support kernels without the SGX driver built-in, which is incompatible with the DCAP driver?
Also, dropping the support has one more advantage IMO - we won't accidentally get bug reports for Gramine running on the older driver :)
</blockquote></details>

I understand we don't support kernels without the SGX driver, but for usability, I think it's useful to provide warning message or hints to users who are using a wrong or incompatible kernel.
___
*[`pal/src/host/linux-sgx/host_framework.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OELCnHh2NtZqgMQdYwv:-OEp4AEbErGbXywqXr8c:b-72dp55) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the error above has all this info, excluding the deprecated part? There's no mention about updating the kernel, because all the supported distros already have it.
</blockquote></details>

I think for backward compatibility reasons, some users may be running on an older kernel that do not have this feature. In that case, they will at least know how to fix it, instead of contacting us in the channel.

Anyhow, I am not blocking this PR, but I think in general we can try to provide more warning or hint to users even if they are not exactly following our instructions.


<!-- Sent from Reviewable.io -->

2024-12-24 00:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`pal/src/host/linux-sgx/host_framework.c` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-jmj-6om47oDvUQEz:-OEq8dcOCezxLPpDUgp1:bbb7dzy) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L19)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

I understand we don't support kernels without the SGX driver, but for usability, I think it's useful to provide warning message or hints to users who are using a wrong or incompatible kernel.
</blockquote></details>

Ok, makes sense, I added more information to this error, please check now :)
___
*[`pal/src/host/linux-sgx/host_framework.c` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OELCnHh2NtZqgMQdYwv:-OEq8kcn432TipLzP7jL:bf6wbd9) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/pal/src/host/linux-sgx/host_framework.c#L35)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

I think for backward compatibility reasons, some users may be running on an older kernel that do not have this feature. In that case, they will at least know how to fix it, instead of contacting us in the channel.

Anyhow, I am not blocking this PR, but I think in general we can try to provide more warning or hint to users even if they are not exactly following our instructions.
</blockquote></details>

Added, see above.


<!-- Sent from Reviewable.io -->

2024-12-27 18:43 UTC, chiache approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2024-12-30 03:15 UTC, kailun-qin approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/2075#-OFKYFYw5EiNzb07g2qW:-OFKYFYw5EiNzb07g2qX:b-1nvsov):*
-> `deprecation`? Can be fixed during rebase.



_Code quote:_
```
depreciation
```


<!-- Sent from Reviewable.io -->

2025-01-12 11:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OGPEl8b8J13y-Lt8rz9:b-a9rxu9) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
> Possibly this one, `*-sigstruct-view`, could from now be the reference style?

Sure, fine with me.

> Can we write this down somewhere in `Documentation`?

Hmm, but where? Style guide, in a new section, "output formats"? Or somewhere else?


<!-- Sent from Reviewable.io -->

2025-01-13 02:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OGS_4q09ASzYgGoOyUI:b-da2dhb) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
> Possibly this one, `*-sigstruct-view`, could from now be the reference style?

+1

> Style guide, in a new section, "output formats"?

+1


<!-- Sent from Reviewable.io -->

2025-01-13 12:12 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OGUZToM0ziA82lOew5r:b-8iyci1) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Possibly this one, `*-sigstruct-view`, could from now be the reference style?

+1

> Style guide, in a new section, "output formats"?

+1
</blockquote></details>

Certainly not a new document. Existing style guide is fine I think, or https://gramine.readthedocs.io/en/stable/devel/contributing.html, but the latter one seems too high-level to me.


<!-- Sent from Reviewable.io -->

2025-02-02 00:23 UTC, mkow reviewed
FYI: I had to rebase the PR so the docs can successfully build, but the fixup commits were trivial, so it shouldn't be too annoying for you.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075#-:-OI30f0iAhR5FOIgWttK:b-kwu6b5)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin and @woju)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/2075#-OFKYFYw5EiNzb07g2qW:-OI31Mdy4sO4280_E8UJ:b-896fix):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `deprecation`? Can be fixed during rebase.
</blockquote></details>

Done.
___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OI3-czq9xSKWksFdCfS:bo6jhaj) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Certainly not a new document. Existing style guide is fine I think, or https://gramine.readthedocs.io/en/stable/devel/contributing.html, but the latter one seems too high-level to me.
</blockquote></details>

Done, check now.


<!-- Sent from Reviewable.io -->

2025-02-04 14:27 UTC, woju approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)

___
*[`python/gramine-sgx-sigstruct-view` line 52 at r1](https://reviewable.io/reviews/gramineproject/gramine/2075#-OE-k-tu73yk7wVu8RSf:-OIGLeRgBwYcFLCTaGbI:b-53gb7g) ([raw file](https://github.com/gramineproject/gramine/blob/2877640a06c5d14525ad1dc802860538ef4ea429/python/gramine-sgx-sigstruct-view#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done, check now.
</blockquote></details>

Nice, LGTM.


<!-- Sent from Reviewable.io -->

2025-02-06 01:49 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2075)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-02-09 01:40 UTC, merged