[Pal/Linux-SGX] Restructure sgx_quote_t to split signature from body
gramineproject/gramine pull request #219
Opened 2021-11-12 16:53 UTC by vijaydhanraj

## Description of the changes 
SGX quote returned by IAS does not contain signature and signature length fields. This might result in a buffer overflow if we accidentally end up using these fields as part of the quote. To avoid such an issue, this commit splits sgx_quote structure into sgx_quote_body and signature.

Also, modified `attestation` LibOS regression to incorporate the new sgx_quote structural change.

Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>

Fixes #113 

## How to test this PR? 
Please run LibOS regression tests. One can also run the `ra-tls-mbedtls` test as part of our CI-Examples.

2021-11-15 10:45 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY6bPdCsPiumWEzCPS:-MoY6bPe6Jag40jhNXl0:bte2ycs) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L30)):*
> ```objc
>  *  \param[in] body Buffer with quote body data.
>  */
> void display_quote_body(const sgx_quote_body_t* body);
> ```

Please rename `body` argument to `quote_body` -- to be uniform with the below function `verify_quote_enclave_attributes()`.

Don't forget to change the name in the comment for this func (above).
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY6spFD7-7ev31qXUZ:-MoY6spFD7-7ev31qXU_:b-ug78ki) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L67)):*
> ```objc
>  *
>  *  \param[in] quote_data      Quote body to verify.
>  *  \param[in] quote_size      Size of \a quote body in bytes.
> ```

Typo: `quote body` -> `quote_body` (forgot the underscore)
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY8eB76ZWeDVem5Kbn:-MoY8eB76ZWeDVem5Kbo:b-l2abqy) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L82)):*
> ```objc
>  *  \return 0 on successful verification, negative value on error.
>  */
> int verify_quote(const void* quote_data, size_t quote_size, const char* mr_signer,
> ```

You forgot to change names in this func: should be `quote_body` and `quote_body_size`. Also please change the names in the comment above.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYAxJX3I0BfUOk5NTc:-MoYAxJX3I0BfUOk5NTd:b-vab996) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L82)):*
> ```objc
>  *  \return 0 on successful verification, negative value on error.
>  */
> int verify_quote(const void* quote_data, size_t quote_size, const char* mr_signer,
> ```

Actually, we should use the real type instead of `const void*` and we can get rid of `quote_size` (because callers of this function already checked the size of the quote, no need to double-check). So the function signature should look like this:
```
int verify_quote(const sgx_quote_body_t* quote_body, const char* mr_signer, ...
```
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY7-xl6Gki7nV2B19Z:-MoY7-xl6Gki7nV2B19_:b-l1aqfg) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L86)):*
> ```C
> }
> 
> void display_quote_body(const sgx_quote_body_t* body) {
> ```

ditto (`body` -> `quote_body`)
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY7K2X6zN8jImRICXf:-MoY7K2X6zN8jImRICXg:b35urqw) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
> ```C
> 
>     // quotes from IAS reports are missing signature fields
>     if (quote_size >= sizeof(sgx_quote_body_t)) {
> ```

This change is wrong. E.g., if `quote_size` is only one byte greater than `sgx_quote_body_t`, you are **not** supposed to read `quote->signature_len` (you'll get only first byte from the quote object, the rest 3 bytes will be garbage).

So either:
- revert this change (old code was fine because `sizeof(sgx_quote_t)` covers the `signature_len` field)
- or change to something like: `if (quote_size >= sizeof(sgx_quote_body_t) + sizeof(quote->signature_len)) `
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 333 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYBOVG7imQxvlsOo28:-MoYBOVG7imQxvlsOo29:b-d7fmz2) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L333)):*
> ```C
>         ERROR("Quote: Bad size %zu < %zu\n", quote_body_size, sizeof(sgx_quote_body_t));
>         goto out;
>     }
> ```

You won't need these 5 lines if you change the signature of `verify_quote()` as I explained in the previous comment
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY9HmtDOOnPaoVB9Za:-MoY9HmtDOOnPaoVB9Zb:b-f5kquz) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L200)):*
> ```C
> }
> 
> int verify_quote_against_envvar_measurements(const void* quote_body, size_t quote_body_size) {
> ```

You forgot to update `ra_tls.h` -- argument names should be changed in that file as well.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYBX7MB9wz5vqmG6xN:-MoYBX7MB9wz5vqmG6xO:b-djhjk) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L200)):*
> ```C
> }
> 
> int verify_quote_against_envvar_measurements(const void* quote_body, size_t quote_body_size) {
> ```

Actually, we should use the real type instead of `const void*` and we can get rid of `quote_body_size` (because callers of this function already checked the size of the quote, no need to double-check). So the function signature should look like this:
```
int verify_quote_against_envvar_measurements(const sgx_quote_body_t* quote_body)
```
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYA7J0Ad1udzruTa1e:-MoYA7J0Ad1udzruTa1f:bcbwf8m) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
> ```C
>     ret = verify_ias_report_extract_quote(report, report_size, sig, sig_size,
>                                           allow_outdated_tcb, nonce, ias_pubkey,
>                                           &report_quote_body, &quote_body_size);
> ```

This renaming is wrong. You're actually extracting the full SGX quote, not just the body. Please revert these renames.

But in `verify_quote...` functions below you of course need to use the SGX quote body, so you'll need to cast there:
```
verify_quote((sgx_quote_body_t*)report_quote, ...
verify_quote_enclave_attributes((sgx_quote_body_t*)report_quote_body, ...
```


<!-- Sent from Reviewable.io -->

2021-11-16 15:47 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: 2 of 9 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY6bPdCsPiumWEzCPS:-ModC3Ev6zCQ7BstLb6k:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `body` argument to `quote_body` -- to be uniform with the below function `verify_quote_enclave_attributes()`.

Don't forget to change the name in the comment for this func (above).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY6spFD7-7ev31qXUZ:-ModCllk0GuQdQxamoTQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `quote body` -> `quote_body` (forgot the underscore)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY8eB76ZWeDVem5Kbn:-ModCnMo1HOwfjVEzyFh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to change names in this func: should be `quote_body` and `quote_body_size`. Also please change the names in the comment above.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYAxJX3I0BfUOk5NTc:-ModEit-87Rhm4EMk6uI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, we should use the real type instead of `const void*` and we can get rid of `quote_size` (because callers of this function already checked the size of the quote, no need to double-check). So the function signature should look like this:
```
int verify_quote(const sgx_quote_body_t* quote_body, const char* mr_signer, ...
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 86 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY7-xl6Gki7nV2B19Z:-ModF4kKD9RPXOqNRFUK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`body` -> `quote_body`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY7K2X6zN8jImRICXf:-ModGQpxDsipckQswdnY:bgeqfz2) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This change is wrong. E.g., if `quote_size` is only one byte greater than `sgx_quote_body_t`, you are **not** supposed to read `quote->signature_len` (you'll get only first byte from the quote object, the rest 3 bytes will be garbage).

So either:
- revert this change (old code was fine because `sizeof(sgx_quote_t)` covers the `signature_len` field)
- or change to something like: `if (quote_size >= sizeof(sgx_quote_body_t) + sizeof(quote->signature_len)) `
</blockquote></details>

Good catch. Yes, I have changed the condition to check `if (quote_size >= sizeof(sgx_quote_body_t) + sizeof(quote->signature_len))`
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 333 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYBOVG7imQxvlsOo28:-ModH8mR2gvjp4skl6BQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/common/attestation.c#L333)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You won't need these 5 lines if you change the signature of `verify_quote()` as I explained in the previous comment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoY9HmtDOOnPaoVB9Za:-ModI1Gc0lwVCsj3iU63:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to update `ra_tls.h` -- argument names should be changed in that file as well.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYBX7MB9wz5vqmG6xN:-ModIp4X2QF22F4TD_va:b-3vwnbr) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, we should use the real type instead of `const void*` and we can get rid of `quote_body_size` (because callers of this function already checked the size of the quote, no need to double-check). So the function signature should look like this:
```
int verify_quote_against_envvar_measurements(const sgx_quote_body_t* quote_body)
```
</blockquote></details>

Yes, the only user of the `quote_body_size` parameter was the `verify_quote()` function. Since we removed the `quote_body_size` parameter from `verify_quote()`, it makes sense to remove it here as well.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYA7J0Ad1udzruTa1e:-ModN-TX0qBKM3NnjdC6:b-ju8ov) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This renaming is wrong. You're actually extracting the full SGX quote, not just the body. Please revert these renames.

But in `verify_quote...` functions below you of course need to use the SGX quote body, so you'll need to cast there:
```
verify_quote((sgx_quote_body_t*)report_quote, ...
verify_quote_enclave_attributes((sgx_quote_body_t*)report_quote_body, ...
```
</blockquote></details>

I did the renaming after checking this, https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/tools/common/attestation.c#L270. Here we actually extract `isvEnclaveQuoteBody` object instead of `quote` and so the renaming seemed appropriate.


<!-- Sent from Reviewable.io -->

2021-11-17 07:52 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-Mogq4tK15wqCegKM9aY:-Mogq4tK15wqCegKM9aZ:b-q6lz8k) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.h#L67)):*
> ```objc
>  *
>  *  \param[in] quote_body      Quote body to verify.
>  *  \param[in] quote_body_size Size of \a quote_body in bytes.
> ```

We don't have this argument anymore, please remove this comment
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-MogqLN0-xLPCpk66ko7:-MogqLN0-xLPCpk66ko8:b-z8yy9h) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.c#L328)):*
> ```C
>     int ret = -1;
> 
>     sgx_quote_body_t* body = (sgx_quote_body_t*)quote_body;
> ```

This is a no-op assignment now. Please remove it and just use `quote_body` everywhere in this function.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYA7J0Ad1udzruTa1e:-Mogs43i0imHu0F5j9m1:b5vexem) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I did the renaming after checking this, https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/tools/common/attestation.c#L270. Here we actually extract `isvEnclaveQuoteBody` object instead of `quote` and so the renaming seemed appropriate.
</blockquote></details>

Ah, true. This is rather obscure, so could you add a comment before this function, smth like:
```
/* IAS returns a truncated SGX quote without signature fields (only the SGX quote body) */
```


<!-- Sent from Reviewable.io -->

2021-11-17 15:27 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-MogqLN0-xLPCpk66ko7:-MoiU5CwBlvxflEtw-D8:b9hox92) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.c#L328)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a no-op assignment now. Please remove it and just use `quote_body` everywhere in this function.
</blockquote></details>

We will get an error due to `const` qualifier of `const sgx_quote_body_t*` at the below usage,
```
sgx_report_body_t* report_body = &quote_body->report_body;
```
 So, shall we remove the `const` qualifier? I prefer to keep it the current way.


<!-- Sent from Reviewable.io -->

2021-11-17 15:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-MogqLN0-xLPCpk66ko7:-Moi_bKtE5OpefawMEHC:b-z8nf9o) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.c#L328)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We will get an error due to `const` qualifier of `const sgx_quote_body_t*` at the below usage,
```
sgx_report_body_t* report_body = &quote_body->report_body;
```
 So, shall we remove the `const` qualifier? I prefer to keep it the current way.
</blockquote></details>

Ah, I see. I really dislike the `const` rules in the C language, but ok. Resolving, I'm fine with the current version.


<!-- Sent from Reviewable.io -->

2021-11-17 16:06 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: 7 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-Mogq4tK15wqCegKM9aY:-Moic4aN69ZkRlkUwXdm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.h#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't have this argument anymore, please remove this comment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/219#-MogqLN0-xLPCpk66ko7:-Moid6yrA8UNVlG2Adkn:b-ucfkn4) ([raw file](https://github.com/gramineproject/gramine/blob/7fd1fd3dbc1962c9e06964538f2c48f1169be448/Pal/src/host/Linux-SGX/tools/common/attestation.c#L328)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I see. I really dislike the `const` rules in the C language, but ok. Resolving, I'm fine with the current version.
</blockquote></details>

Thanks.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c, line 172 at r1](https://reviewable.io/reviews/gramineproject/gramine/219#-MoYA7J0Ad1udzruTa1e:-MoiclBv6hgZRwIyTA1S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/825f22207adb2bbf109b7361d4b11336d227d23d/Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, true. This is rather obscure, so could you add a comment before this function, smth like:
```
/* IAS returns a truncated SGX quote without signature fields (only the SGX quote body) */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-18 07:59 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-18 07:59 UTC, dimakuv commented
Jenkins, test this please

2021-11-29 21:56 UTC, mkow requested changes
> Reviewed 2 of 8 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphdRNC98O30KM6cHgi:-MphdRNC98O30KM6cHgj:b3sstkc) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
> ```objc
> typedef struct _sgx_quote_t {
>     sgx_quote_body_t body;
>     uint32_t signature_len;
> ```

Does this include this field itself or not? For me it sounds like it doesn't, but the code in this PR assumes that it does.
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphddSm1xLaYsR_t8MH:-MphddSn5379UUvwxmUA:b-cictx8) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
> ```objc
> typedef struct _sgx_quote_t {
>     sgx_quote_body_t body;
>     uint32_t signature_len;
> ```

`len` -> `size` (for uniformity with our naming conventions)
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-MphbqLy8dx4JgGDwfNd:btzna8e) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
> ```objc
>  *  \return 0 on successful verification, negative value on error.
>  */
> int verify_quote(const sgx_quote_body_t* quote_body, const char* mr_signer,
> ```

Wait, why does `verify_quote()` skips the signature and blindly trusts the quote fields?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 86 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphcJIV9Hbq5XQFRVVa:-MphcJIV9Hbq5XQFRVVb:b2felz3) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L86)):*
> ```C
> }
> 
> void display_quote_body(const sgx_quote_body_t* quote_body) {
> ```

this should be `static`
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-MphchueCPhWomLgvHOd:b7c9s1q) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
> ```C
>     INFO("xeid              : ");
>     HEXDUMP(quote_body->xeid);
>     INFO("basename          : ");
> ```

`display_report_body()` indents this section, but here you miss this.
You'll also need to fix the colon below so that it's still aligned.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MphehWrBeWEL3aVIpU2:b-yp5ljn) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
> ```C
> 
>     // quotes from IAS reports are missing signature fields
>     if (quote_size >= sizeof(sgx_quote_body_t) + sizeof(quote->signature_len)) {
> ```

Ad the comment about `signature_len`: here you assume that `signature_len` includes its own size.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c, line 166 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphfmILDHf-Z3AowrBd:-MphfmILDHf-Z3AowrBe:b-26pxko) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c#L166)):*
> ```C
>     }
> 
>     sgx_quote_body_t quote_body = ((sgx_quote_t*)quote)->body;
> ```

Was it intended to copy the whole structure here?


<!-- Sent from Reviewable.io -->

2021-11-30 07:44 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: 5 of 11 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphdRNC98O30KM6cHgi:-MpjTVJN4_OpVphNbKza:b-viiakp) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this include this field itself or not? For me it sounds like it doesn't, but the code in this PR assumes that it does.
</blockquote></details>

Can you please clarify? Are you asking if the sgx quote struct includes the `signature_len` field?
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphddSm1xLaYsR_t8MH:-MpjUGTmDkTw9fz4fVE2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`len` -> `size` (for uniformity with our naming conventions)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-MpjV2VO1hlwCzchtoX4:b-sjdmnv) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, why does `verify_quote()` skips the signature and blindly trusts the quote fields?
</blockquote></details>

Callers of `verify_quote()` already validate `quote` and so we skip doing a check again.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 86 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphcJIV9Hbq5XQFRVVa:-Mpjd2eDCyNGSTfLJf7n:b-u0qeii) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be `static`
</blockquote></details>

yes agree. I also made `display_report_body()` static.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-MpjfCxKAOhccDa_D_A9:b-4c5ezp) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`display_report_body()` indents this section, but here you miss this.
You'll also need to fix the colon below so that it's still aligned.
</blockquote></details>

Good catch, done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpjhMiA73xnH9zYec44:berye6v) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ad the comment about `signature_len`: here you assume that `signature_len` includes its own size.
</blockquote></details>

Added the following comment. Does this clarify?
```
    /* quotes from IAS reports are missing signature fields. So display signature and signature_size
       fields only for dcap based quotes */
```
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c, line 166 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphfmILDHf-Z3AowrBd:-MpjiLew6fATnCeGmaLc:b-evc2kc) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c#L166)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Was it intended to copy the whole structure here?
</blockquote></details>

Changed this to a pointer.


<!-- Sent from Reviewable.io -->

2021-11-30 09:53 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphdRNC98O30KM6cHgi:-Mpjwx3d111B2Z-wucjd:b-5jue07) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can you please clarify? Are you asking if the sgx quote struct includes the `signature_len` field?
</blockquote></details>

@mkow There are two entities that use the term "SGX quote".

- The Quoting Enclave generates the full SGX quote. This full SGX quote is of `sgx_quote_t` type and lways includes `signature_len` and `signature`.
- The IAS (for EPID-based attestation) returns back the trimmed SGX quote. This trimmed SGX quote is of `sgx_quote_body_t` type (see https://api.trustedservices.intel.com/documents/IAS-API-Spec-rev-5.0.pdf, Section 3.2.2, search for `isvEnclaveQuoteBody`).
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphddSm1xLaYsR_t8MH:-MpkD7Ma3yXt6sZvfrCQ:b-hy2wtg) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm ok with this change, but just want to point out -- there are SGX API specifications from Intel where this field is called "length". I'm not sure what to do with this problem: sometimes we consider terms/keywords from specifications to be not clear or not complying to our Gramine standards -- is it fine to rename in our code?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-MpkENKjDIHV51j04UEK:biezqfd) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Callers of `verify_quote()` already validate `quote` and so we skip doing a check again.
</blockquote></details>

@mkow Do you want to rename this function to `verify_quote_body()`? I wouldn't mind that. Or what would be the suggestion?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpkExzc8HOqLt5AR-30:bxulodv) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
> here you assume that signature_len includes its own size.

@mkow Why are you saying this? `signature_len` reflects only the size of the `sgx_quote_t::signature` field. It *does not* include its own size. Maybe you didn't notice two *different* structs in the two IF checks (`sizeof(sgx_quote_body_t)` vs `sizeof(sgx_quote_t)`)?

I actually don't see much need in adding any comment at all here. But I don't mind Vijay's added comment (though @vijaydhanraj please replace `dcap based` with `DCAP-based`).
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 119 at r4](https://reviewable.io/reviews/gramineproject/gramine/219#-MpkFcwkDvKhpQQYazLj:-MpkFcwkDvKhpQQYazLk:bk8akad) ([raw file](https://github.com/gramineproject/gramine/blob/3a65628a05123add0f7718ad57cf0f8f54a7a8d6/Pal/src/host/Linux-SGX/tools/common/attestation.c#L119)):*
> ```C
>        fields only for dcap based quotes */
>     if (quote_size >= sizeof(sgx_quote_body_t) + sizeof(quote->signature_size)) {
>         INFO("signature_size     : %d (0x%x)\n", quote->signature_size, quote->signature_size);
> ```

You need to remove one space before `:` now, for nice alignment
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c, line 166 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphfmILDHf-Z3AowrBd:-MpkFoQb5CmkaYhmoaIu:b-ajrzp4) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c#L166)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed this to a pointer.
</blockquote></details>

Good catch :) Though it didn't matter much.


<!-- Sent from Reviewable.io -->

2021-11-30 12:52 UTC, mkow requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphddSm1xLaYsR_t8MH:-Mpkm7On9EPO3yI28vON:b-m8g8cv) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm ok with this change, but just want to point out -- there are SGX API specifications from Intel where this field is called "length". I'm not sure what to do with this problem: sometimes we consider terms/keywords from specifications to be not clear or not complying to our Gramine standards -- is it fine to rename in our code?
</blockquote></details>

Yeah, I assumed it's just copied from the spec, but I prefer to use our conventions for consistency.
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphdRNC98O30KM6cHgi:-MpkmGsY0NWJd2rG0UiN:bmj9h25) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
> @mkow There are two entities that use the term "SGX quote".

Yes, I know, this is what this PR is about :P

My question is whether this field is `size(signature)` or `size(signature_len || signature)`.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-MpknccABQ1RbBhoHggt:b-7rkc81) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
> Callers of `verify_quote()` already validate `quote` and so we skip doing a check again.

But _this_ function is named ~"quote verification", why should the caller _also_ verify quote, if it just called "verify quote"?

> @mkow Do you want to rename this function to `verify_quote_body()`? I wouldn't mind that. Or what would be the suggestion?

Sounds good, but it also needs and explicit comment IMO that this doesn't verify the signature. Same with `verify_quote_against_envvar_measurements()`.

> Callers of `verify_quote()` already validate `quote` and so we skip doing a check again.

Another question related to this: Do they actually do this? Just want to ensure that this function name didn't make anyone skip the additional checks.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-MpkqeDUEnWC_KJd3pyY:b98kl7x) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
> You'll also need to fix the colon below so that it's still aligned.

You didn't do this ;) The colons are misaligned now.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpkrP7IBv7AY5UwWanY:b-bygez6) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
I think you both misunderstood my comment or the code ;)

> Added the following comment. Does this clarify?

I said "Ad the comment", not "Add the comment" ;) This is the example for the discussion thread pinned at sgx_attest.h.

@dimakuv: You say "It does _not_ include its own size.". Then what's the meaning of `sizeof(sgx_quote_t) + quote->signature_size` expression if it skips `signature_size` field, a few lines below this comment? (I should have pinned the discussion there, sorry)


<!-- Sent from Reviewable.io -->

2021-11-30 13:48 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphdRNC98O30KM6cHgi:-Mpl4BVk2U0vt3CUzSw_:b-5m7pdz) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/sgx_attest.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This field is `size(signature)`.
</blockquote></details>

Ok, resolving, see explanation below.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-Mpl4HOJ-2PmWGe4CRSV:b-l8mmii) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Then what's the meaning of `sizeof(sgx_quote_t) + quote->signature_size` expression if it skips `signature_size` field

It doesn't skip `signature_size` field. Check the definition of `sgx_quote_t`:
```
typedef struct _sgx_quote_t {
    sgx_quote_body_t body;
    uint32_t signature_size;
    uint8_t signature[];
} sgx_quote_t;
```

So `sizeof(sgx_quote_t)` *already includes* the `signature_size` field. Again, I think you're confusing `sgx_quote_body_t` vs `sgx_quote_t`.
</blockquote></details>

Ahh, I see what happened. I first too a look at the `if` with `sizeof(sgx_quote_body_t) + sizeof(quote->signature_size)` and then at the one with `sizeof(sgx_quote_t) + quote->signature_size)` and didn't notice these are different lines, so I kind of took the first addend from the first one and the second from the second :) (as both `if`s look visually very similarly)

Ok, this code if fine then, sorry for confusion.


<!-- Sent from Reviewable.io -->

2021-12-01 05:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: 4 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-Mpo8ht20kFgINxmXcRJ:b-h34pny) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
Changed `verify_quote`->`verify_quote_body`, 
`verify_quote_against_envvar_measurements`-> `verify_quote_body_against_envvar_measurements` and also changed
`verify_quote_enclave_attributes` -> `verify_quote_body_enclave_attributes`

Given this do we need a comment saying that these functions do not verify the signature? PS: Quote body does not have the signature field itself in the first place.

> Another question related to this: Do they actually do this? Just want to ensure that this function name didn't make anyone skip the additional checks.

For DCAP, yes, this `sgx_qv_verify_quote` function does seem to verify the signature and returns `SGX_QL_QE_REPORT_INVALID_SIGNATURE`in case of failure. Please see https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf, pages `29-34`.

For EPID based trimmed quote, there is no `signature` or `signature_len` but we do a check on `size(sgx_quote_body_t)` before calling `verify_quote_body()`.
See here, https://github.com/gramineproject/gramine/pull/219/files#diff-7fcaed3ad7a104dd5d4e90335cab93c9f76e87fc0aea49976ab5c83d802220ddR236 and
https://github.com/gramineproject/gramine/pull/219/files#diff-2487ced5606ccff3c3343ca96f8e4cba9bbf13e03352b6634b7f5d74ad268d34R178
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-MpoMTaX62Z7_aJ64_gK:bgbo24o) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> You'll also need to fix the colon below so that it's still aligned.

You didn't do this ;) The colons are misaligned now.
</blockquote></details>

Here is the current output from `gramine-sgx_quote_dump` tool which calls `display_quote`. Does this look fine?
```
quote_body        :
 version          : 0300
 sign_type        : 0200
 epid_group_id    : 00000000
 qe_svn           : 0600
 pce_svn          : 0b00
 xeid             : 939a7233
 basename         : f79c4ca9940a0db3957f0607562125326eef0c2a45d525f19f50129800000000
report_body       :
 cpu_svn          : 04050708ffff01000000000000000000
 misc_select      : 00000000
 reserved1        : 000000000000000000000000
 isv_ext_prod_id  : 00000000000000000000000000000000
 attributes.flags : 0500000000000000
 attributes.xfrm  : e700000000000000
 mr_enclave       : ea1d8689b474c9c46ef0de6fc136222908f91bc3aa17b0d165d6ed8507fcd42d
 reserved2        : 0000000000000000000000000000000000000000000000000000000000000000
 mr_signer        : d412a4f07ef83892a5915fb2ab584be31e186e5a4f95ab5f6950fd4eb8694d7b
 reserved3        : 0000000000000000000000000000000000000000000000000000000000000000
 config_id        : 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 isv_prod_id      : 0000
 isv_svn          : 0000
 config_svn       : 0000
 reserved4        : 000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 isv_family_id    : 00000000000000000000000000000000
 report_data      : 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
signature_size    : 4288 (0x10c0)
signature         : 0a8cc7b347efe3d....
```
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-Mpo0B0O2poRArha9pPn:b-cadpkj) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ahh, I see what happened. I first too a look at the `if` with `sizeof(sgx_quote_body_t) + sizeof(quote->signature_size)` and then at the one with `sizeof(sgx_quote_t) + quote->signature_size)` and didn't notice these are different lines, so I kind of took the first addend from the first one and the second from the second :) (as both `if`s look visually very similarly)

Ok, this code if fine then, sorry for confusion.
</blockquote></details>

@dimakuv I have changed `dcap based` to `DCAP-based`. But if is not needed, I can remove it.

@mkow For future references, do you mean `And` when you say `Ad`?
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 119 at r4](https://reviewable.io/reviews/gramineproject/gramine/219#-MpkFcwkDvKhpQQYazLj:-Mpo1U8yALs58JoJ8Cjw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3a65628a05123add0f7718ad57cf0f8f54a7a8d6/Pal/src/host/Linux-SGX/tools/common/attestation.c#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to remove one space before `:` now, for nice alignment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-01 07:38 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-MpoujdPERQRC3rOuuJ_:b-ayv7gw) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed `verify_quote`->`verify_quote_body`, 
`verify_quote_against_envvar_measurements`-> `verify_quote_body_against_envvar_measurements` and also changed
`verify_quote_enclave_attributes` -> `verify_quote_body_enclave_attributes`

Given this do we need a comment saying that these functions do not verify the signature? PS: Quote body does not have the signature field itself in the first place.

> Another question related to this: Do they actually do this? Just want to ensure that this function name didn't make anyone skip the additional checks.

For DCAP, yes, this `sgx_qv_verify_quote` function does seem to verify the signature and returns `SGX_QL_QE_REPORT_INVALID_SIGNATURE`in case of failure. Please see https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf, pages `29-34`.

For EPID based trimmed quote, there is no `signature` or `signature_len` but we do a check on `size(sgx_quote_body_t)` before calling `verify_quote_body()`.
See here, https://github.com/gramineproject/gramine/pull/219/files#diff-7fcaed3ad7a104dd5d4e90335cab93c9f76e87fc0aea49976ab5c83d802220ddR236 and
https://github.com/gramineproject/gramine/pull/219/files#diff-2487ced5606ccff3c3343ca96f8e4cba9bbf13e03352b6634b7f5d74ad268d34R178


</blockquote></details>

I agree with Vijay that we don't need an explicit comment for these functions, because they already have it (`quote_body`) in their names, and these functions don't have any "access" to the signature field.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 50 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-MpouR2sCJC9pDoy65c8:-MpouR2sCJC9pDoy65c9:b-onys77) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/common/attestation.h#L50)):*
> ```objc
> 
> /*!
>  *  \brief Verify that the provided SGX quote contains expected values.
> ```

Please also fix this comment: `SGX quote contains` -> `SGX quote body contains`
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-Mpov0fC9HpAGteAq2P3:-Mpov0fC9HpAGteAq2P4:b-ob7gkd) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/common/attestation.h#L72)):*
> ```objc
> 
> /*!
>  *  \brief Verify enclave attributes of the provided SGX quote.
> ```

`SGX quote body`
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-Mpov89RCbwDe6M7YQQE:b-nbxz02) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here is the current output from `gramine-sgx_quote_dump` tool which calls `display_quote`. Does this look fine?
```
quote_body        :
 version          : 0300
 sign_type        : 0200
 epid_group_id    : 00000000
 qe_svn           : 0600
 pce_svn          : 0b00
 xeid             : 939a7233
 basename         : f79c4ca9940a0db3957f0607562125326eef0c2a45d525f19f50129800000000
report_body       :
 cpu_svn          : 04050708ffff01000000000000000000
 misc_select      : 00000000
 reserved1        : 000000000000000000000000
 isv_ext_prod_id  : 00000000000000000000000000000000
 attributes.flags : 0500000000000000
 attributes.xfrm  : e700000000000000
 mr_enclave       : ea1d8689b474c9c46ef0de6fc136222908f91bc3aa17b0d165d6ed8507fcd42d
 reserved2        : 0000000000000000000000000000000000000000000000000000000000000000
 mr_signer        : d412a4f07ef83892a5915fb2ab584be31e186e5a4f95ab5f6950fd4eb8694d7b
 reserved3        : 0000000000000000000000000000000000000000000000000000000000000000
 config_id        : 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 isv_prod_id      : 0000
 isv_svn          : 0000
 config_svn       : 0000
 reserved4        : 000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 isv_family_id    : 00000000000000000000000000000000
 report_data      : 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
signature_size    : 4288 (0x10c0)
signature         : 0a8cc7b347efe3d....
```
</blockquote></details>

This looks fine to me.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpovF_x272PZheWbC-E:bgunjr) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv I have changed `dcap based` to `DCAP-based`. But if is not needed, I can remove it.

@mkow For future references, do you mean `And` when you say `Ad`?
</blockquote></details>

Thanks, the comment is good now.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 244 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-MpovYng3WJpRpRvM9-B:-MpovYng3WJpRpRvM9-C:bb4ih04) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L244)):*
> ```C
>     sgx_quote_body_t* quote_body = (sgx_quote_body_t*)quote_from_ias;
> 
>     /* verify enclave attributes from the SGX quote */
> ```

`from the SGX quote body`


<!-- Sent from Reviewable.io -->

2021-12-01 20:14 UTC, mkow submitted a review, later dismissed
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 81 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphbqLy8dx4JgGDwfNc:-Mpr_q_379hcNg8B3TQ_:b-xe3yi9) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.h#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Vijay that we don't need an explicit comment for these functions, because they already have it (`quote_body`) in their names, and these functions don't have any "access" to the signature field.
</blockquote></details>

Ok, I'd still prefer an explicit comment, but won't block on this.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 99 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphchueCPhWomLgvHOc:-Mpra44-BgZ-1XioO0DU:b67haji) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks fine to me.
</blockquote></details>

Looks good after the fix.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpraFSr1oLuizM1ONT0:b-r68ef5) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, the comment is good now.
</blockquote></details>

@vijaydhanraj: No, I mean "with regards to", I think this is a borrowed word from latin, but not really sure, maybe I'm actually using it incorrectly... ¯\\_(ツ)_/¯


<!-- Sent from Reviewable.io -->

2021-12-02 00:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 50 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-MpouR2sCJC9pDoy65c8:-MpsR7e90NAAQxICNxuy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/common/attestation.h#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also fix this comment: `SGX quote contains` -> `SGX quote body contains`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.h, line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-Mpov0fC9HpAGteAq2P3:-MpsRATF2w5m9Q-Gj0ji:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/common/attestation.h#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`SGX quote body`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-MpsRHs_Ao8anvrAFKoc:btejdo1) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vijaydhanraj: No, I mean "with regards to", I think this is a borrowed word from latin, but not really sure, maybe I'm actually using it incorrectly... ¯\\_(ツ)_/¯
</blockquote></details>

ok got it :)
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 244 at r5](https://reviewable.io/reviews/gramineproject/gramine/219#-MpovYng3WJpRpRvM9-B:-MpsREBU6VC910aDAB4N:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/73773f8e0b3dee7fd5760617470ee0e94ff3ba1b/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`from the SGX quote body`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 00:23 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-12-02 07:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-Mpu2UevAwdff5X2Sklw:b-rcs1ud) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ok got it :)
</blockquote></details>

Yeah, `ad` sounds like a typo in `and` or `add`, and it's easy to misinterpret it. Maybe we should always replace it with "wrt" or with the full "with respect/regards to" version. I was also confused (thought you meant `add`).


<!-- Sent from Reviewable.io -->

2021-12-02 07:36 UTC, dimakuv commented
Jenkins, test this please

2021-12-02 12:03 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 117 at r3](https://reviewable.io/reviews/gramineproject/gramine/219#-MphehWrBeWEL3aVIpU1:-Mpv0YI2BC8XY_a02M_Q:b-9gefkk) ([raw file](https://github.com/gramineproject/gramine/blob/ca6fa5bcc5ff0ad5acd93b31122f9a217888edc7/Pal/src/host/Linux-SGX/tools/common/attestation.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, `ad` sounds like a typo in `and` or `add`, and it's easy to misinterpret it. Maybe we should always replace it with "wrt" or with the full "with respect/regards to" version. I was also confused (thought you meant `add`).
</blockquote></details>

Ok, will try to use "w.r.t." instead in the future.


<!-- Sent from Reviewable.io -->

2021-12-02 13:11 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-12-02 13:11 UTC, dimakuv commented
Jenkins, test this please

2021-12-02 13:15 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/219)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-02 14:00 UTC, merged