Fixes for problems found by GCC 11.2.0
gramineproject/gramine pull request #220
Opened 2021-11-12 17:59 UTC by mkow

## Description of the changes 

Still emits a warning under 11.2.0, but I'm not sure how to fix it (looks like false positive?) and it's probably not urgent:

```
../Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c:584:20: error: ‘userdata’ may be used uninitialized [-Werror=maybe-uninitialized]
  584 |             return *(long*)((void*)&userdata + (off_t)addr);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2021-11-15 08:48 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 327 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXli18-PWtVAr3j0wo:-MoXli18-PWtVAr3j0wp:b-7qsp59) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L327)):*
> ```C
>         return ret;
> 
>     fill_regs(&ud->regs, &gpr);
> ```

@mkow I think the last warning you see in GCC is because of this partial initialization of the `ud` struct. In this `peek_user()` function, we only fill the `regs` part of `ud` and leave the rest uninitialized.

So the simple fix to your warning would be to `memset(ud, 0, sizeof(*ud))` before this line.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 576 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXkWysCQDaMdSZR0R7:-MoXkWyt7HLTSVmu0Bfp:b-6pb13k) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L576)):*
> ```C
> 
>             if ((size_t)addr + sizeof(long) > sizeof(struct user_regs_struct))
>                 return host_ptrace(PTRACE_PEEKUSER, tid, addr, NULL);
> ```

We can merge this into the above (and instead of `NULL` as the last arg, simply forward `data`), for uniformity with `PTRACE_POKEUSER`


<!-- Sent from Reviewable.io -->

2021-11-15 10:47 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoYC2y_5iXtk9OHU_3V:-MoYC2y_5iXtk9OHU_3W:b4nzkaw) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/sgx_profile.c#L145)):*
> ```C
>         if (close_ret < 0)
>             log_error("sgx_profile_init: pd_close failed: %ld", close_ret);
>         g_perf_data = NULL;
> ```

Wow, good catch.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 327 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXli18-PWtVAr3j0wo:-MoYCH474LqUC5DoktMW:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L327)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I think the last warning you see in GCC is because of this partial initialization of the `ud` struct. In this `peek_user()` function, we only fill the `regs` part of `ud` and leave the rest uninitialized.

So the simple fix to your warning would be to `memset(ud, 0, sizeof(*ud))` before this line.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-11-15 15:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 327 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXli18-PWtVAr3j0wo:-MoZGpsRCwNJq61ty-Kd:b-qvz50j) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L327)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Nah, I tried this even before submitting this PR and it doesn't remove the warning :(
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 576 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXkWysCQDaMdSZR0R7:-MoZHN6m0wwuCaWz-k5l:b-cea6v8) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L576)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can merge this into the above (and instead of `NULL` as the last arg, simply forward `data`), for uniformity with `PTRACE_POKEUSER`
</blockquote></details>

Why is it correct to pass `data` instead of `NULL` in this case? I'm pretty scared of this whole file and the pile of hacks which live here, so I'd prefer not to touch too much of it without a bigger refactoring ;)


<!-- Sent from Reviewable.io -->

2021-11-15 18:19 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 327 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXli18-PWtVAr3j0wo:-MoZoiu32_KBd5U8a-3M:bngltg3) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L327)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, I tried this even before submitting this PR and it doesn't remove the warning :(
</blockquote></details>

OK, no idea then. Resolving.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 576 at r1](https://reviewable.io/reviews/gramineproject/gramine/220#-MoXkWysCQDaMdSZR0R7:-MoZoltNERopuhc9CT1Y:bw4s6gn) ([raw file](https://github.com/gramineproject/gramine/blob/36d9699e209ae7fdfbb3c18ae25c367bc4bd8d6c/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L576)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is it correct to pass `data` instead of `NULL` in this case? I'm pretty scared of this whole file and the pile of hacks which live here, so I'd prefer not to touch too much of it without a bigger refactoring ;)
</blockquote></details>

OK, let's not change anything.


<!-- Sent from Reviewable.io -->

2021-11-17 07:30 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-11-17 11:51 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/220)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-17 12:33 UTC, merged