WIP: [tests] Build LTP using Meson
gramineproject/gramine pull request #222
Opened 2021-11-15 13:44 UTC by pwmarcz

Signed-off-by: Paweł Marczewski <pawel@invisiblethingslab.com>

## Description of the changes 

## How to test this PR?

2021-11-16 08:14 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/222)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/Makefile, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/222#-Mobmnee3cEBhzx8BHzM:-Mobmnee3cEBhzx8BHzN:b2lsdws) ([raw file](https://github.com/gramineproject/gramine/blob/786d7c44de8140ecfb2c925e4a61f5c72916dc6d/LibOS/shim/test/ltp/Makefile#L28)):*
> ```Makefile
> $(INSTALLDIR)/INSTALL_SUCCESS: $(GRAMINE_PKGLIBDIR)/tests/ltp
> 	rm -rf $(INSTALLDIR)
> 	cp -r $< install/
> ```

`install/` -> `$(INSTALLDIR)` ?
___
*[subprojects/packagefiles/ltp-20200930/compile.sh, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/222#-Mobn9hQ6JiXcDES44k4:-Mobn9hQ6JiXcDES44k5:b-dnre1k) ([raw file](https://github.com/gramineproject/gramine/blob/786d7c44de8140ecfb2c925e4a61f5c72916dc6d/subprojects/packagefiles/ltp-20200930/compile.sh#L35)):*
> ```Shell
> 
> 	# `--without-modules`: kernel module tests are not meaningful for our LibOS, and building them
> 	# causes troubles on incompatible host kernels
> ```

Please replace tabs with spaces (two lines)


<!-- Sent from Reviewable.io -->

2021-11-16 12:42 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/222)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-16 17:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/222)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[meson.build, line 273 at r2](https://reviewable.io/reviews/gramineproject/gramine/222#-Modpv1oErY7-BjNtBdu:-Modpv1oErY7-BjNtBdv:b-phrhe6) ([raw file](https://github.com/gramineproject/gramine/blob/26100981b690ff22e2c06163c1c8bee5160f500e/meson.build#L273)):*
> ```Meson
> endif
> 
> if enable_tests
> ```

Actually, let me create a `-Dltp=enabled` flag for that, the compilation takes some time...


<!-- Sent from Reviewable.io -->

2021-11-24 09:23 UTC, pwmarcz commented
Closing. We've been talking about bulding these subprojects (glibc, musl, libgomp, LTP) separately from Meson, and seeing how much hacks I need in this branch, I'll leave the LTP build process in the Makefile for now.

CC @woju @boryspoplawski

2021-11-24 09:23 UTC, closed without merging