[Format] Apply clang-format to a few files
gramineproject/gramine pull request #223
Opened 2021-11-15 17:54 UTC by donporter

## Description of the changes 

Apply clang-format rules to a few files, which should be uncontroversial.  This is mostly to "denoise" output while working on issues where we don't like what clang-format does, although I may have misjudged something (i.e., the review may still be useful to catch format changes that are unappealing).

Unless people object, I'll probably do a slow trickle of these sorts of PRs, or updates to this one.

I did manually disable formatting around some inline assembly, which I assume will be uncommon to need.

## How to test this PR? 

N/A: No functional change to the code.

2021-11-16 07:55 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MobjDo2810D8TRSRKhG:-MobjDo2810D8TRSRKhH:bz7wvoz) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L22)):*
> ```objc
> 
> #ifdef __ASSEMBLER__
> /* clang-format off */
> ```

Can we remove these pragmas? Isn't there a way to ask clang-format to ignore asm snippets?

Even if there is no way to force clang-format to ignore these, can we just remove these comments (we'll have warnings about them in clang-format but we'll just ignore them -- there will be just a few of such warnings).


<!-- Sent from Reviewable.io -->

2021-11-18 19:54 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MobjDo2810D8TRSRKhG:-Mooasf3BHI_1FZfyKyC:baj47c1) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove these pragmas? Isn't there a way to ask clang-format to ignore asm snippets?

Even if there is no way to force clang-format to ignore these, can we just remove these comments (we'll have warnings about them in clang-format but we'll just ignore them -- there will be just a few of such warnings).
</blockquote></details>

We can certainly remove them if you want.  I do not see an easy option to ignore assembly snippets, but also seems like a reasonable feature request.

Bigger picture: would it be worth having some of these pragmas to be able to use clang-format on the rest of the code, or no?


<!-- Sent from Reviewable.io -->

2021-11-19 08:06 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MobjDo2810D8TRSRKhG:-MorCkqq45JZke4FECI1:b-ozdx4q) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L22)):*
> Bigger picture: would it be worth having some of these pragmas to be able to use clang-format on the rest of the code, or no?

I would say "no". I don't like putting such on/off pragmas everywhere in the code.

My understanding is that all such cases of weird clang-formatting (like the asm snippets) can be found by manual inspection, and PR authors can be asked to revert those particular clang-format changes.

Also, asm snippets should only be found in `arch/x86_64` includes and in a very few places in C code. These are not frequently touched by developers, so I just wouldn't bother adding pragmas.


<!-- Sent from Reviewable.io -->

2021-11-29 00:04 UTC, mkow reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-MpcztzN6nzI2Q4-7t-V:b82b8jz) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
> ```objc
> #define __NR_syscalls 428
> #endif
> #endif /* SHIM_SYSCALLS_H_ */
> ```

This is actually one of the clang-format bugs (I think) - it tries to keep inline comments separated from code by two spaces, but for some reason this works only for `//` comments...
Maybe it's actually a weird feature (to behave differently for both types), but I don't see how this could make sense.


<!-- Sent from Reviewable.io -->

2021-11-30 16:38 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MobjDo2810D8TRSRKhG:-MplhZLAEt_hJG42CIQ2:bmwoeqn) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Bigger picture: would it be worth having some of these pragmas to be able to use clang-format on the rest of the code, or no?

I would say "no". I don't like putting such on/off pragmas everywhere in the code.

My understanding is that all such cases of weird clang-formatting (like the asm snippets) can be found by manual inspection, and PR authors can be asked to revert those particular clang-format changes.

Also, asm snippets should only be found in `arch/x86_64` includes and in a very few places in C code. These are not frequently touched by developers, so I just wouldn't bother adding pragmas.
</blockquote></details>

Sure, I'll revert and look into other options, then.
___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-Mplh6SV2LWiHaMlKtKV:buuid0c) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is actually one of the clang-format bugs (I think) - it tries to keep inline comments separated from code by two spaces, but for some reason this works only for `//` comments...
Maybe it's actually a weird feature (to behave differently for both types), but I don't see how this could make sense.
</blockquote></details>

Just to clarify: what style do we want in this project? (1 or 2 spaces).  In reviewing the style guidelines, we do not say.  So I assume one, correct?


<!-- Sent from Reviewable.io -->

2021-11-30 16:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-MpljLWf0qNAs8m42qKh:b-x1cxpx) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Just to clarify: what style do we want in this project? (1 or 2 spaces).  In reviewing the style guidelines, we do not say.  So I assume one, correct?
</blockquote></details>

I like 2 spaces, but we didn't enforce this so far. And this is not a strong preference, let's see what other's say :)


<!-- Sent from Reviewable.io -->

2021-11-30 16:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-MplkiEREqL5gqHvcj1z:bg7khl1) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like 2 spaces, but we didn't enforce this so far. And this is not a strong preference, let's see what other's say :)
</blockquote></details>

I have no strong preference. Maybe let clang-format to choose 1 or 2 spaces for us (with its weird logic of 1 space for `/*` and 2 spaces for `//`)?


<!-- Sent from Reviewable.io -->

2021-11-30 17:24 UTC, boryspoplawski reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-Mplr4cHET86NDrgDeoE:b8nnuu1) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have no strong preference. Maybe let clang-format to choose 1 or 2 spaces for us (with its weird logic of 1 space for `/*` and 2 spaces for `//`)?
</blockquote></details>

I don't see much point in 2 spaces, specially since it leaves less space for the comment itself (by 1 char, but still :) )


<!-- Sent from Reviewable.io -->

2021-11-30 17:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-Mpls3aG6_BRiuOzTP0z:b37nipz) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't see much point in 2 spaces, specially since it leaves less space for the comment itself (by 1 char, but still :) )
</blockquote></details>

I was talking about `//` comments at the end of a line (I guess that's the only place where we use `//`)


<!-- Sent from Reviewable.io -->

2021-12-01 19:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-MprZGL12BLrVN5Gq6Za:bc7rdlc) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
> Maybe let clang-format to choose 1 or 2 spaces for us (with its weird logic of 1 space for `/*` and 2 spaces for `//`)?

Nooo, please choose either one, but be consistent :P

> I don't see much point in 2 spaces, specially since it leaves less space for the comment itself (by 1 char, but still :) )

I think the idea with 2 spaces is that it's slightly more readable / looks nicer. But I don't have strong preferences here.


<!-- Sent from Reviewable.io -->

2021-12-01 20:56 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-Mprm7Q0BJmCybgL2ELX:bif2ui4) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Maybe let clang-format to choose 1 or 2 spaces for us (with its weird logic of 1 space for `/*` and 2 spaces for `//`)?

Nooo, please choose either one, but be consistent :P

> I don't see much point in 2 spaces, specially since it leaves less space for the comment itself (by 1 char, but still :) )

I think the idea with 2 spaces is that it's slightly more readable / looks nicer. But I don't have strong preferences here.
</blockquote></details>

I'll vote 1 - similar reasoning to Borys


<!-- Sent from Reviewable.io -->

2021-12-02 07:23 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/223#-MpcztzL70LExhlVf71t:-Mpu0ctCEw3lqHTwkjnn:buif30k) ([raw file](https://github.com/gramineproject/gramine/blob/2c677c4a4ff91697aceae2afab27fbd581005fd5/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L55)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I'll vote 1 - similar reasoning to Borys
</blockquote></details>

OK, let's do 1.


<!-- Sent from Reviewable.io -->

2021-12-02 07:30 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @donporter)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/223#-Mpu28JqAd6ywACDbe9R:-Mpu28JqAd6ywACDbe9S:bwt0sum) (no related file):*
@donporter Do you want this PR to be merged, or was it more like a proof-of-concept?

---


<!-- Sent from Reviewable.io -->

2021-12-04 18:58 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/223#-Mpu28JqAd6ywACDbe9R:-Mq5nVSKEOopPPTfC39I:b6ystho) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@donporter Do you want this PR to be merged, or was it more like a proof-of-concept?
</blockquote></details>

Please merge.  Although this is pretty minor stuff, it would denoise the output of clang-format while I look into more difficult issues with clang, and makes the style of the code marginally nicer.  

This was a useful discussion to understand gaps in our style guidelines.  I'll add a note about the one space issue.

---


<!-- Sent from Reviewable.io -->

2021-12-05 18:13 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-12-06 08:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-06 08:11 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/223#-MqDmsQZEhe6_HtsKto9:-MqDmsQZEhe6_HtsKtoA:b-i6e4tq) ([raw file](https://github.com/gramineproject/gramine/blob/b5cbfffad13d151365dd52b16038446b357615f4/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L18)):*
> ```objc
> 
> /* Offsets for GS register at which entry vectors can be found */
> #define GRAMINE_SYSCALL_OFFSET 24
> ```

FYI: Please note that in the meantime `shim_entry_api.h` was renamed to `gramine_entry_api.h` and slightly changed. I applied the same fixes as before in this PR during rebase.


<!-- Sent from Reviewable.io -->

2021-12-06 11:11 UTC, mkow requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter)

___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/223#-MqER2Su0irmuRU9unVh:-MqER2Sv-u6ugGCQiRUQ:b-3juddv) ([raw file](https://github.com/gramineproject/gramine/blob/b5cbfffad13d151365dd52b16038446b357615f4/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L30)):*
> ```objc
> #else /* !__ASSEMBLER__ */
> 
> #define GRAMINE_STR(x) #x
> ```

You missed this place? (alignment fix, see the diff for `shim_entry_api.h`)


<!-- Sent from Reviewable.io -->

2021-12-06 11:43 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[LibOS/shim/include/arch/x86_64/gramine_entry_api.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/223#-MqER2Su0irmuRU9unVh:-MqEY_U_BZbyCyyVMWTM:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/b5cbfffad13d151365dd52b16038446b357615f4/LibOS/shim/include/arch/x86_64/gramine_entry_api.h#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You missed this place? (alignment fix, see the diff for `shim_entry_api.h`)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-12-06 11:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/223)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-06 12:47 UTC, merged