WIP: ASan improvements
gramineproject/gramine pull request #228
Opened 2021-11-16 16:51 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-11-17 15:22 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/fs/test_pf.py, line 175 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-MoiUM04B9mSuHvPs7Mi:-MoiUM04B9mSuHvPs7Mj:bxhjl19) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/LibOS/shim/test/fs/test_pf.py#L175)):*
> ```Python
>         self.verify_copy(stdout, stderr, self.ENCRYPTED_DIR, executable)
> 
>     # TODO: `mmap` on protected files is broken, because we fail to properly register that memory is
> ```

FYI: this is ticketed as #231.


<!-- Sent from Reviewable.io -->

2021-11-18 01:27 UTC, mkow approved these changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-18 08:30 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/asan.h, line 94 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom5xsa7VtfvwPzI_PH:-Mom5xsa7VtfvwPzI_PI:bwrmhlf) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L94)):*
> ```objc
>  * two, LLVM tries to optimize the generated code by emitting bitwise OR instead of addition in the
>  * mem-to-shadow conversion. As a result, low values (such as 1 TB) will not work correctly. A value
>  * at least as high as the shadow map length (1 << 44) should work, but it's probably better to stay
> ```

`44` -> `45`
___
*[common/include/asan.h, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom67Ef9bANFsDKwU78:-Mom67Ef9bANFsDKwU79:b1w25mp) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L108)):*
> ```objc
> #define ASAN_SHADOW_START 0x18000000000ULL /* 1.5 TB */
> #define ASAN_SHADOW_SHIFT 3
> #define ASAN_SHADOW_LENGTH (1ULL << 45)
> ```

Can you add a sentence somewhere in the above top-level comment that
```
The shadow map length is 1<<45 to cover the whole 48-bit address space:
Linux sometimes maps `vvar` and `vdso` just above 0x800000000000
(= 1<<48).
```
___
*[common/include/asan.h, line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom8tDD-nVdO1_UhnaV:-Mom8tDD-nVdO1_UhnaW:b-6l6h2o) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L119)):*
> ```objc
> #define ASAN_POISON_HEAP_LEFT_REDZONE     0xfa
> #define ASAN_POISON_HEAP_AFTER_FREE       0xfd
> #define ASAN_POISON_USER                  0xf7
> ```

From what I understand, this kind is SGX-only and means "logically marked as no-prot or freed enclave pages", is this understanding correct? Could you add a comment for this then (or a better "bug classification" message).
___
*[Pal/regression/Exception.c, line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom75574yNNCil1Vk-O:-Mom75574yNNCil1Vk-P:b30n01j) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/regression/Exception.c#L110)):*
> ```C
> }
> 
> __attribute_no_sanitize_address
> ```

Why do you disable it here? Can you put a short comment of why ASan is triggered here? Shouldn't this be marked as TODO?
___
*[Pal/regression/Memory.c, line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7C6Z3MFBj-OqYam4:-Mom7C6Z3MFBj-OqYam5:b30n01j) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/regression/Memory.c#L29)):*
> ```C
> }
> 
> __attribute_no_sanitize_address
> ```

Why do you disable it here? Can you put a short comment of why ASan is triggered here? Shouldn't this be marked as TODO?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 427 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7TMN1ShpdOasQEd1:-Mom7TMN1ShpdOasQEd2:b-vtwsyr) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/db_files.c#L427)):*
> ```C
>         *addr = allocated_enclave_pages;
>     } else {
>         /* TODO: Shouldn't we also call `get_enclave_pages` here? */
> ```

Yeah, good question. I have a feeling this code path is never triggered?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 579 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom8DC95EcS0AjyJu46:-Mom8DC95EcS0AjyJu47:bv3ebco) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/sgx_main.c#L579)):*
> ```C
>         }
>     }
> #endif
> ```

Why are you doing this? I don't get the logic here: "mark all enclave memory as inaccessible other than the free regions (heap)".

UPDATE: I incorrectly read `strcmp` check -- you're actually amrking all enclave memory as accessible, but mark free regions as inaccessible. Could you add a comment or make the `strcmp` check somehow more explicit (`!= 0`), so that future readers don't make the same mistake?


<!-- Sent from Reviewable.io -->

2021-11-18 10:40 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: 4 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/asan.h, line 94 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom5xsa7VtfvwPzI_PH:-MomGpLG90kqJ6xvH6V3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`44` -> `45`
</blockquote></details>

Done.
___
*[common/include/asan.h, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom67Ef9bANFsDKwU78:-MomHIz99g_q8bauCUQh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a sentence somewhere in the above top-level comment that
```
The shadow map length is 1<<45 to cover the whole 48-bit address space:
Linux sometimes maps `vvar` and `vdso` just above 0x800000000000
(= 1<<48).
```
</blockquote></details>

Done.
___
*[common/include/asan.h, line 119 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom8tDD-nVdO1_UhnaV:-MomIIPJ8CaU4O-xgBgG:b-3hic1c) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/common/include/asan.h#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From what I understand, this kind is SGX-only and means "logically marked as no-prot or freed enclave pages", is this understanding correct? Could you add a comment for this then (or a better "bug classification" message).
</blockquote></details>

The constant is defined by LLVM, but that's how we used it. I added comments to explain that, and improved the message.
___
*[common/include/asan.h, line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/228#-MomcAXNELctQk8FLSh9:-MomcAXNELctQk8FLShA:bpejm9d) ([raw file](https://github.com/gramineproject/gramine/blob/0af0ea5e2b9a43301a4125653b1e8b70b3326476/common/include/asan.h#L83)):*
> ```objc
> /*
>  * Parameters of the shadow memory area. Each byte of shadow memory corresponds to ASAN_SHADOW_ALIGN
>  * (by default 8) bytes of user memory. The shadow map length is 1 << 45 to cover the whole 48-bit
> ```

TODO while rebasing: I put the edits to this comment in a wrong `fixup!` commit, I will have to sort it out.
___
*[Pal/regression/Memory.c, line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7C6Z3MFBj-OqYam4:-MomVNcd9nvFWFI1-jwb:bs9z80e) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/regression/Memory.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you disable it here? Can you put a short comment of why ASan is triggered here? Shouldn't this be marked as TODO?
</blockquote></details>

I added a comment. I don't think that's a TODO, the whole point of this test is to access memory that we're not supposed to.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 427 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7TMN1ShpdOasQEd1:-MomVq1m3tXNkIguO44w:brha1z4) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/db_files.c#L427)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, good question. I have a feeling this code path is never triggered?
</blockquote></details>

It definitely is triggered, that's why I had to add the `asan_unpoison_region` below.

I described the problem in the comment. This is yet another way in which this protected files code is badly broken. When we get to reimplementing it, I think moving it out of SGX would help: nobody wouldn't be tempted to take such shortcuts as "use the memory without actually allocating it" that are possible with SGX.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 579 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom8DC95EcS0AjyJu46:-Mom_xiX3TG__FOkgi2f:b-sgwlzp) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/sgx_main.c#L579)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are you doing this? I don't get the logic here: "mark all enclave memory as inaccessible other than the free regions (heap)".

UPDATE: I incorrectly read `strcmp` check -- you're actually amrking all enclave memory as accessible, but mark free regions as inaccessible. Could you add a comment or make the `strcmp` check somehow more explicit (`!= 0`), so that future readers don't make the same mistake?
</blockquote></details>

I realized this is not right. The only range we care about (i.e. we add it to enclave, but it should not be accessed) is "free", so I changed the code to poison only that range instead.
___
*[Pal/regression/Exception.c, line 110 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom75574yNNCil1Vk-O:-MomS-K19MpxdqKi1CU2:bjis1nd) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/regression/Exception.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you disable it here? Can you put a short comment of why ASan is triggered here? Shouldn't this be marked as TODO?
</blockquote></details>

Actually, this one should not be disabled. I did it because it accesses address 0x1000 to trigger a memory fault, but that's because we poisoned that memory instead of leaving it alone.


<!-- Sent from Reviewable.io -->

2021-11-18 13:25 UTC, mkow approved these changes
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 427 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7TMN1ShpdOasQEd1:-MonCqgt06mh2FogmcQ8:b-rkdubw) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/db_files.c#L427)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It definitely is triggered, that's why I had to add the `asan_unpoison_region` below.

I described the problem in the comment. This is yet another way in which this protected files code is badly broken. When we get to reimplementing it, I think moving it out of SGX would help: nobody wouldn't be tempted to take such shortcuts as "use the memory without actually allocating it" that are possible with SGX.
</blockquote></details>

+1 to making them non-SGX-specific.


<!-- Sent from Reviewable.io -->

2021-11-22 08:04 UTC, dimakuv approved these changes
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 427 at r1](https://reviewable.io/reviews/gramineproject/gramine/228#-Mom7TMN1ShpdOasQEd1:-Mp5eTRYA1rFBVd9kJuz:b-28socr) ([raw file](https://github.com/gramineproject/gramine/blob/b652ec6d0b59b555e60d8372a70870d723536573/Pal/src/host/Linux-SGX/db_files.c#L427)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to making them non-SGX-specific.
</blockquote></details>

Heh, yes, agreed.


<!-- Sent from Reviewable.io -->

2021-11-22 11:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[common/include/asan.h, line 83 at r2](https://reviewable.io/reviews/gramineproject/gramine/228#-MomcAXNELctQk8FLSh9:-Mp6IOtvDEFTXe5KsLc-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0af0ea5e2b9a43301a4125653b1e8b70b3326476/common/include/asan.h#L83)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

TODO while rebasing: I put the edits to this comment in a wrong `fixup!` commit, I will have to sort it out.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 11:41 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-22 12:00 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/228)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-22 12:02 UTC, merged