Add musl support
gramineproject/gramine pull request #234
Opened 2021-11-20 03:58 UTC by boryspoplawski

## Description of the changes 
WIP

## How to test this PR? 
CI

2021-11-24 14:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 0 of 56 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpHRFhjEw7D-c3NxO28:-MpHRFhjEw7D-c3NxO29:bz91zjn) (no related file):*
I dislike how the meson integration turned out, but I have no better ideas. Suggestion are welcome.

---


<!-- Sent from Reviewable.io -->

2021-11-25 10:38 UTC, dimakuv requested changes
> Reviewed 36 of 50 files at r1, 9 of 13 files at r2, 3 of 3 files at r3, 4 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLeZL38HEiXcv5ZsXS:-MpLeZL38HEiXcv5ZsXT:b-4c4yyy) (no related file):*
I feel like we need to update Documentation as well... At least mention the possibility of Musl build in https://gramine.readthedocs.io/en/latest/building.html

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLelhF9LZEYuaTUfXw:-MpLelhGEGEaFzaLN3-c:byxr38d) (no related file):*
Musl seems to be quite different/incompatible from Glibc. Are there any good resources on the current state of Musl? (I worked with Musl like 5 years ago, surely it changed a lot.)

---
___
*[-- commits, line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLYtpFAIzOZQ10gxfG):*
typo: `against`
___
*[meson.build, line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLZ53FAE96NZO83l2f:-MpLZ53FAE96NZO83l2g:brlc433) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson.build#L44)):*
> ```Meson
> 
> enable_glibc = get_option('gnu-libc') == 'enabled'
> enable_musl = get_option('musl-libc') == 'enabled'
> ```

Can we have aliases to these options? I like these two names, but many people are used to `glibc` and `musl`. Typing `-Dglibc=enabled` or `-Dmusl=enabled` looks simple and easy to remember :)

UPDATE: I'm leaning towards renaming `gnu-libc` to `glibc` and `musl-libc` to `musl`. You already use these words everywhere internally. Why not use them in meson options for uniformity as well?
___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpL_HJqAbuetDWMsyA7:b-ibccmh) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
> ```Meson
>     value: 'enabled', description: 'Build patched glibc')
> option('musl-libc', type: 'combo', choices: ['disabled', 'enabled'],
>     value: 'enabled', description: 'Build patched musl-libc')
> ```

So both musl and Glibc are enabled by default? Well I guess it doesn't hurt.
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLZu5E7GA-j9sP2-oV:-MpLZu5E7GA-j9sP2-oW:b-lyn43f) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/.ci/lib/stage-build-nosgx.jenkinsfile#L10)):*
> ```
>     }
>     if (env.CC == 'clang') {
>         env.MESON_OPTIONS += ' -Dmusl-libc=disabled'
> ```

So the combination of Musl and Clang is unsupported currently? Maybe add FIXME comments in all such places?
___
*[LibOS/shim/test/regression/futex.h, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLakjE92w9BLAGul39:-MpLakjE92w9BLAGul3A:b5mn2zo) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/futex.h#L3)):*
> ```objc
> /* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
> /* Copy of "include/uapi/linux/futex.h" from the Linux kernel sources, with 2 includes commented
>  * out and sparse annotations removed. */
> ```

Shouldn't we add it to LICENSE.addendum.txt ?
___
*[LibOS/shim/test/regression/meson.build, line 140 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLb8lXBChei0hzW5mH:-MpLb8lXBChei0hzW5mI:b-ckpnig) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/meson.build#L140)):*
> ```Meson
> if host_machine.cpu_family() == 'x86_64'
>     tests += {
>         'bootstrap_cpp': {
> ```

Can you add a comment why `bootstrap_cpp` doesn't work under Musl? Is it because Musl expects other C++ related libraries?
___
*[LibOS/shim/test/regression/meson.build, line 264 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLcP8L9IIKwurkDUVa:-MpLcP8L9IIKwurkDUVb:b-h9entr) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/meson.build#L264)):*
> ```Meson
>         prefix / join_paths(install_dir, 'musl'),
>         musl_execs,
>     )
> ```

Wow. Could you add a comment that you first build LibOS tests with `musl_` prefix and then move them all to a separate musl dir, removing the `musl_` prefix? This took me a while to realize.
___
*[LibOS/shim/test/regression/test_libos.py, line 333 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLciml-_uF7kTDiBis:-MpLciml-_uF7kTDiBit:bb76mu4) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L333)):*
> ```Python
> 
> class TC_02_OpenMP(RegressionTestCase):
>     @unittest.skipIf(USES_MUSL, 'OpenMP not supported with musl')
> ```

Why?
___
*[LibOS/shim/test/regression/test_libos.py, line 456 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLcsAS7eD4STcRfQja:-MpLcsAS7eD4STcRfQjb:b-f2zc0) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L456)):*
> ```Python
>         self.assertIn('[mmapped_cwd_buf] getcwd succeeded: /', stdout)
> 
>     @unittest.skipIf(USES_MUSL, 'musl incorrectly assumes all arguments are valid')
> ```

Weird. Is this a known bug in Musl? Is there a GitHub issue or something?
___
*[LibOS/shim/test/regression/test_libos.py, line 974 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLd1-08xRHO2e7O7SW:-MpLd1-08xRHO2e7O7SX:bjvy4ys) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L974)):*
> ```Python
>         self.assertIn(' _start ()', backtrace_1)
>         self.assertIn('debug.c', backtrace_1)
>         if not USES_MUSL:
> ```

I don't even want to ask...
___
*[python/graminelibos/util_tests.py, line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLdSel09o0OGtgaEYe:-MpLdSel09o0OGtgaEYf:b-kbid9s) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/python/graminelibos/util_tests.py#L30)):*
> ```Python
>       @GRAMINE_PKGLIBDIR@ to library directory of Gramine's installation
> 
>     - `libc`: name of the libc to build agains, currently supported: 'glibc' (default), 'musl'
> ```

typo: `against`
___
*[subprojects/musl-1.2.2.wrap, line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLd_TFElq7_nE4dYA8:-MpLd_TFElq7_nE4dYA9:b-6hk06f) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/musl-1.2.2.wrap#L4)):*
> ```
> directory = musl-1.2.2
> source_url = https://musl.libc.org/releases/musl-1.2.2.tar.gz
> source_fallback_url = https://packages.grapheneproject.io/distfiles/musl-1.2.2.tar.gz
> ```

@woju Can we add Musl to our packages?
___
*[subprojects/packagefiles/musl-1.2.2/meson.build, line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLe30_-6tQIXG0PQP-:-MpLe30_-6tQIXG0PQP0:b1i0f1q) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/packagefiles/musl-1.2.2/meson.build#L48)):*
> ```Meson
>     'sh', '-c',
>     'ln -sf libc.so "${MESON_INSTALL_DESTDIR_PREFIX}/@0@"'.format(
>         join_paths(get_option('libdir'), 'gramine/runtime/musl', 'ld-musl-x86_64.so.1')),
> ```

But what about other symlinks, like `libm.so`, `libpthread.so`? Or applications built  [...]

2021-11-25 13:11 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLelhF9LZEYuaTUfXw:-MpLr29sACTUkshxVhPu:bppj29x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Musl seems to be quite different/incompatible from Glibc. Are there any good resources on the current state of Musl? (I worked with Musl like 5 years ago, surely it changed a lot.)
</blockquote></details>

Not sure what you mean.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLeZL38HEiXcv5ZsXS:-MpLtB7uAMTE8dbWBL6R:b-hhf7kr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I feel like we need to update Documentation as well... At least mention the possibility of Musl build in https://gramine.readthedocs.io/en/latest/building.html
</blockquote></details>

This is weird, I remember fixing Documentation... No idea where and how the changes disappeared.
I went through everything again, hopefully nothing missing now.

---
___
*[-- commits, line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLYtpFAIzOZQ10gxfG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `against`
</blockquote></details>

TODO: at rebase
___
*[meson.build, line 44 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLZ53FAE96NZO83l2f:-MpLyFoV9luJ_yjxOpBM:b-hfznhz) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson.build#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we have aliases to these options? I like these two names, but many people are used to `glibc` and `musl`. Typing `-Dglibc=enabled` or `-Dmusl=enabled` looks simple and easy to remember :)

UPDATE: I'm leaning towards renaming `gnu-libc` to `glibc` and `musl-libc` to `musl`. You already use these words everywhere internally. Why not use them in meson options for uniformity as well?
</blockquote></details>

I just wanted to have some common component, so it's clear that they both refer to the same "feature", but I guess it's not worth.
Done.
___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpLyypk0PjvHfwFlir9:b10sm55) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So both musl and Glibc are enabled by default? Well I guess it doesn't hurt.
</blockquote></details>

Ah, yes, that's something I wanted to talk about.
Since building musl is self contained and does not require anything more than glibc, I've set this enabled by default.
The alternative is to make this disabled by default, but I'm unsure what would be the advantages.
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLZu5E7GA-j9sP2-oV:-MpM-Sjm6IHCu4IEPr7T:biy019p) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/.ci/lib/stage-build-nosgx.jenkinsfile#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So the combination of Musl and Clang is unsupported currently? Maybe add FIXME comments in all such places?
</blockquote></details>

The problem is building tests against musl using clang, but stems from meson inflexibility. We have such a comment in "LibOS/shim/test/regression/meson.build".
___
*[LibOS/shim/test/regression/futex.h, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLakjE92w9BLAGul39:-MpM0cCZ1mRyKjeRXZPn:b1ntkei) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/futex.h#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we add it to LICENSE.addendum.txt ?
</blockquote></details>

I have no idea how this work. In theory nothing that is build using this header becomes part of the Gramine. But we have this in the very same repo.
We could also define a couple of constants ourselves and not include this header, but it was just easier.
___
*[LibOS/shim/test/regression/meson.build, line 140 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLb8lXBChei0hzW5mH:-MpM24C5DuqRoP9RJacW:bdosggx) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/meson.build#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment why `bootstrap_cpp` doesn't work under Musl? Is it because Musl expects other C++ related libraries?
</blockquote></details>

What do you mean by other? musl is a c standard library.
Done.
___
*[LibOS/shim/test/regression/meson.build, line 264 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLcP8L9IIKwurkDUVa:-MpM3Kd61uLMRTWVLg-T:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/meson.build#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wow. Could you add a comment that you first build LibOS tests with `musl_` prefix and then move them all to a separate musl dir, removing the `musl_` prefix? This took me a while to realize.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 333 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLciml-_uF7kTDiBis:-MpM4GZA5FxzU0E201Ny:b-m8r0wt) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L333)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

We would need to provide a `libomp` linked against musl.
___
*[LibOS/shim/test/regression/test_libos.py, line 456 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLcsAS7eD4STcRfQja:-MpM4bog40t42hWsWnfZ:b-c4hxy1) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L456)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Weird. Is this a known bug in Musl? Is there a GitHub issue or something?
</blockquote></details>

Sorry, this comment was wrong. It's the test that is bad, not musl. I've actually changed it (probably should have removed it, but whatever).
___
*[LibOS/shim/test/regression/test_libos.py, line 974 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLd1-08xRHO2e7O7SW:-MpM5q5eDPJ_HFxyILcI:b-hbtl1k) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L974)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't even want to ask...
</blockquote></details>

Well, I guess I should debug this. TBH I have no idea what's wrong...
___
*[python/graminelibos/util_tests.py, line 30 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLdSel09o0OGtgaEYe:-MpMB2ZM8nlSrge6gxXe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/python/graminelibos/util_tests.py#L30)):*
<details><summary><i [...]

2021-11-26 08:42 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLelhF9LZEYuaTUfXw:-MpQKz0442D_DwaG3lZG:bhlp14x) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure what you mean.
</blockquote></details>

Just wanted you to share any interesting blogs/videos/links that you found while working on this PR. My Musl knowledge is very outdated. Anyway, resolving.

---
___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpQLMw34GM1wdstxroE:b-hvcu4n) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, yes, that's something I wanted to talk about.
Since building musl is self contained and does not require anything more than glibc, I've set this enabled by default.
The alternative is to make this disabled by default, but I'm unsure what would be the advantages.
</blockquote></details>

Since you didn't encounter any problems, and there are no particular dependencies of musl, and there is no perf degradation during Gramine build, I would like to keep Musl enabled.
___
*[Documentation/building.rst, line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/234#-MpQLxeLEswvfmtUzgiM:-MpQLxeLEswvfmtUzgiN:b-e79k9w) ([raw file](https://github.com/gramineproject/gramine/blob/20e8f7d8a50c40bafc869e0332d9391fa7db6aea/Documentation/building.rst#L22)):*
> ```reStructuredText
> The build of Gramine implies building at least the first two components. The
> build of the patched C library is optional but highly recommended for
> performance reasons. Patched glibc is built by default.
> ```

Actually, both `patched glibc and patched musl` are built by default.
___
*[Documentation/building.rst, line 185 at r6](https://reviewable.io/reviews/gramineproject/gramine/234#-MpQMDGi7aT6zpBWCrL7:-MpQMDGi7aT6zpBWCrL8:bhhnnq) ([raw file](https://github.com/gramineproject/gramine/blob/20e8f7d8a50c40bafc869e0332d9391fa7db6aea/Documentation/building.rst#L185)):*
> ```reStructuredText
> 
> Set ``-Dglibc=`` or ``-Dmusl=`` options to ``disabled`` if you wish not to build
> the support for any (they are both build by default).
> ```

`both build` -> `both built`
___
*[LibOS/shim/test/regression/futex.h, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLakjE92w9BLAGul39:-MpQMWE04D6vdfjcA1Lg:brkmvs1) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/futex.h#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I have no idea how this work. In theory nothing that is build using this header becomes part of the Gramine. But we have this in the very same repo.
We could also define a couple of constants ourselves and not include this header, but it was just easier.
</blockquote></details>

Well, yeah, I guess it poses no legal issues. Firstly, it is not a part of Gramine itself (only a part of standalone tests). Secondly, this is just a header file. But maybe @mkow knows more?
___
*[LibOS/shim/test/regression/meson.build, line 140 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLb8lXBChei0hzW5mH:-MpQN1_n1FBXN4T8qNSF:bk1qa0u) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/meson.build#L140)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean by other? musl is a c standard library.
Done.
</blockquote></details>

OK. My bad, the comment was worded wrongly. I meant the other way around: C++ related libraries must depend on Musl.

Anyway, I see that it was something different: `musl-gcc` wrapper doesn't allow C++.
___
*[subprojects/packagefiles/musl-1.2.2/meson.build, line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLe30_-6tQIXG0PQP-:-MpQOdLE5x5SLSGRL1au:b-pm6lfo) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/packagefiles/musl-1.2.2/meson.build#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean? You cannot run glibc-build apps with musl.

Why would we crate such symlinks?
</blockquote></details>

Ok, I didn't realize that Musl is *that* incompatible with Glibc (in the sense that applications built against Glibc cannot be tricked to use Musl at runtime, at least without playing tricks). I read a bit about how people run Glibc-built apps on Musl-based systems, and it's not pretty:
- https://git.adelielinux.org/adelie/gcompat
- https://ch1p.io/void-linux-musl-glibc/

So ignore my comment.

(Wasn't one of the original purposes of Musl to be fully binary-compatible with Glibc, just with better internal implementation/codebase? I guess this is impossible to achieve.)


<!-- Sent from Reviewable.io -->

2021-11-26 09:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 58 of 59 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLelhF9LZEYuaTUfXw:-MpQPsg84t8kx9VAqf2x:bju8mqb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just wanted you to share any interesting blogs/videos/links that you found while working on this PR. My Musl knowledge is very outdated. Anyway, resolving.
</blockquote></details>

I just downloaded musl sources, poked a bit in configure, grepped for syscalls and that's all :)
Most of the time I've spent on this PR was fighting with meson; making musl itself work was pretty easy.

---
___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpQUGm8CxZH38hjaRP7:b-dc6edg) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since you didn't encounter any problems, and there are no particular dependencies of musl, and there is no perf degradation during Gramine build, I would like to keep Musl enabled.
</blockquote></details>

Well, it takes some time to build musl, but it's nothing compared with glibc.
___
*[Documentation/building.rst, line 22 at r6](https://reviewable.io/reviews/gramineproject/gramine/234#-MpQLxeLEswvfmtUzgiM:-MpQV5YCE-Jpaq16oBFy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/20e8f7d8a50c40bafc869e0332d9391fa7db6aea/Documentation/building.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, both `patched glibc and patched musl` are built by default.
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 185 at r6](https://reviewable.io/reviews/gramineproject/gramine/234#-MpQMDGi7aT6zpBWCrL7:-MpQVHur9CmQ2d1aHP77:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/20e8f7d8a50c40bafc869e0332d9391fa7db6aea/Documentation/building.rst#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`both build` -> `both built`
</blockquote></details>

Done.
___
*[subprojects/packagefiles/musl-1.2.2/meson.build, line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLe30_-6tQIXG0PQP-:-MpQWEzF5LSL5fZwYsig:bgqkg05) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/packagefiles/musl-1.2.2/meson.build#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I didn't realize that Musl is *that* incompatible with Glibc (in the sense that applications built against Glibc cannot be tricked to use Musl at runtime, at least without playing tricks). I read a bit about how people run Glibc-built apps on Musl-based systems, and it's not pretty:
- https://git.adelielinux.org/adelie/gcompat
- https://ch1p.io/void-linux-musl-glibc/

So ignore my comment.

(Wasn't one of the original purposes of Musl to be fully binary-compatible with Glibc, just with better internal implementation/codebase? I guess this is impossible to achieve.)
</blockquote></details>

That would be a beautiful world, where standard C library has one well defined API and ABI that every implementation adheres to...


<!-- Sent from Reviewable.io -->

2021-11-26 09:21 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[subprojects/packagefiles/musl-1.2.2/meson.build, line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLe30_-6tQIXG0PQP-:-MpQXxZ3EQw-qGuGYY46:biid2rg) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/packagefiles/musl-1.2.2/meson.build#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That would be a beautiful world, where standard C library has one well defined API and ABI that every implementation adheres to...
</blockquote></details>

Indeed. Talking about beautiful but imaginery worlds, have you seen this video: https://www.youtube.com/watch?v=36myc8wQhLo&ab_channel=USENIX ("USENIX ATC '21/OSDI '21 Joint Keynote Address-It's Time for Operating Systems to Rediscover Hardware")? Quite interesting.


<!-- Sent from Reviewable.io -->

2021-11-26 10:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[subprojects/packagefiles/musl-1.2.2/meson.build, line 48 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLe30_-6tQIXG0PQP-:-MpQh8jN8EurOqAKd8Ip:b-qhghn) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/packagefiles/musl-1.2.2/meson.build#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed. Talking about beautiful but imaginery worlds, have you seen this video: https://www.youtube.com/watch?v=36myc8wQhLo&ab_channel=USENIX ("USENIX ATC '21/OSDI '21 Joint Keynote Address-It's Time for Operating Systems to Rediscover Hardware")? Quite interesting.
</blockquote></details>

No, but I'll check it today, thanks :)


<!-- Sent from Reviewable.io -->

2021-12-01 11:28 UTC, mkow requested changes
> Reviewed 34 of 50 files at r1, 8 of 13 files at r2, 3 of 3 files at r3, 1 of 6 files at r4, 3 of 4 files at r5, 9 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 10 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[.ci/lib/stage-test.jenkinsfile, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppVqVJ77Y73nzzZ2eQ:-MppVqVJ77Y73nzzZ2eR:be4eohl) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/.ci/lib/stage-test.jenkinsfile#L32)):*
> ```
>                     export GRAMINE_MUSL=1
>                     cd LibOS/shim/test/regression
>                     # For some unknown reason it fails without this clean on sgx-18.04 pipeline
> ```

CC: @pwmarcz
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MpphHqI7U5J_Re3LV2v:bubea6v) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
> ```reStructuredText
> - The Platform Adaptation Layer, or PAL (a shared library named ``libpal.so``)
> - A patched C Library (shared library ``libc.so`` and possibly others).
>   Currently there are two options: musl and GNU C Library (glibc).
> ```

Maybe we should also mention how one chooses between glibc to musl when configuring a workload in Gramine? (i.e. what to change in the manifest, etc.)
___
*[LibOS/shim/test/regression/futex.h, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLakjE92w9BLAGul39:-MppWq9t-QQsNLlma_tH:b-e5t33z) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/futex.h#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, yeah, I guess it poses no legal issues. Firstly, it is not a part of Gramine itself (only a part of standalone tests). Secondly, this is just a header file. But maybe @mkow knows more?
</blockquote></details>

Hmm, not sure, but I think we don't need to include it in the addendum, as we don't ship it nor any deriverables (it's used only for testing).
___
*[LibOS/shim/test/regression/futex.h, line 3 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppWkhT20sqLoRXqf5t:-MppWkhT20sqLoRXqf5u:bzhiut1) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/futex.h#L3)):*
> ```objc
> /* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
> /* Copy of "include/uapi/linux/futex.h" from the Linux kernel sources, with 2 includes commented
>  * out and sparse annotations removed. */
> ```

Could you explain in the comment why can't we just include it from system headers? (I know why, I'm asking to document it)
___
*[LibOS/shim/test/regression/test_libos.py, line 153 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaTwiCZhMwLWreLAo:-MppaTwiCZhMwLWreLAp:b-m731fk) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L153)):*
> ```Python
> 
>     @unittest.skipUnless(ON_X86, 'x86-specific')
>     @unittest.skipIf(USES_MUSL, 'c++ not supported with musl')
> ```

`c++` -> `C++ is`
___
*[LibOS/shim/test/regression/test_libos.py, line 333 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaXYp2tDL4AyaBmqM:-MppaXYp2tDL4AyaBmqN:ber2vwa) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L333)):*
> ```Python
> 
> class TC_02_OpenMP(RegressionTestCase):
>     @unittest.skipIf(USES_MUSL, 'OpenMP not supported with musl')
> ```

add "is"
___
*[LibOS/shim/test/regression/test_libos.py, line 698 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppabpqBDOXWCUNDyVn:-MppabpqBDOXWCUNDyVo:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L698)):*
> ```Python
>         self.assertIn('eventfd_using_fork completed successfully', stdout)
> 
>     @unittest.skipIf(USES_MUSL, 'sched_setscheduler not supported in musl')
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-12-01 12:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 57 of 59 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mpq0B861ykqIAt2zlpJ:bgz7b4y) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, it takes some time to build musl, but it's nothing compared with glibc.
</blockquote></details>

So what do we do? Build both by default?
cc @mkow @pwmarcz 
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mpq2w6BBx0ivQpPubTY:b-ff6kpq) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe we should also mention how one chooses between glibc to musl when configuring a workload in Gramine? (i.e. what to change in the manifest, etc.)
</blockquote></details>

I don't see a good place for this. There seems to be no place in documentation where we describe how to use our built glibc.
___
*[LibOS/shim/test/regression/futex.h, line 3 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppWkhT20sqLoRXqf5t:-Mpq1CIq211pSBLl7q28:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/futex.h#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain in the comment why can't we just include it from system headers? (I know why, I'm asking to document it)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 153 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaTwiCZhMwLWreLAo:-Mpq1HjdAmnGFHUR4Qbb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`c++` -> `C++ is`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 333 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaXYp2tDL4AyaBmqM:-Mpq1eCtAG7AWTwN2wVU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L333)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

add "is"
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 698 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppabpqBDOXWCUNDyVn:-Mpq1gw7-jD6opzY2dmO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L698)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-01 17:17 UTC, woju requested changes
> Reviewed 7 of 50 files at r1, 2 of 3 files at r3, 2 of 4 files at r5, 5 of 10 files at r6, 1 of 1 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 58 of 59 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mpquf5k1jQpKYeLuJZg:b-jaky4k) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So what do we do? Build both by default?
cc @mkow @pwmarcz 
</blockquote></details>

I have nothing against building and installing musl by default. (Right now this says both are disabled, because first option is the default).
___
*[python/graminelibos/gen_jinja_env.py, line 81 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-MpqxPdY91xrsH54xBsZ:-MpqxPdZA3hVP8YbztdU:bn2n0x1) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/python/graminelibos/gen_jinja_env.py#L81)):*
> ```Python
>     env.globals['env'] = os.environ
>     env.globals['ldd'] = ldd
>     env.globals['libc'] = 'glibc'
> ```

This looks wrong, libc (and runtime flavour) is not a property of the environment. If you want it to be for a particular, use `-D`. We shouldn't add this just because this is convenient for tests.

If you need a default, you can call the `runtimedir()` function like `gramine.runtimedir(libc if libc is defined else "glibc")` or always use `-Dlibc`.
___
*[subprojects/musl-1.2.2.wrap, line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLd_TFElq7_nE4dYA8:-MpquKVxBgjIbrgezgmL:b-1v7h7v) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/subprojects/musl-1.2.2.wrap#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Can we add Musl to our packages?
</blockquote></details>

Done. The URL should say `gramineproject`.


<!-- Sent from Reviewable.io -->

2021-12-01 18:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 57 of 59 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mpr7joa0PzTlwst2zQk:bgwheiz) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I have nothing against building and installing musl by default. (Right now this says both are disabled, because first option is the default).
</blockquote></details>

?
It sets the default value to enabled.
___
*[LibOS/shim/test/regression/test_libos.py, line 974 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLd1-08xRHO2e7O7SW:-Mpr82om6HHspprDhs3T:b-a6c0m0) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/test_libos.py#L974)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I guess I should debug this. TBH I have no idea what's wrong...
</blockquote></details>

The problem most likely stems from the fact that we use host musl to build these test, but run them using our own version - they differ enough for debug info to differ.
Unless we want go back to the idea of installing headers + gcc wrappers alongside lib.so, we have to live with this.
___
*[python/graminelibos/gen_jinja_env.py, line 81 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-MpqxPdY91xrsH54xBsZ:-Mpr9aDC-D8JAeW4sXXy:b-e9i2u6) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/python/graminelibos/gen_jinja_env.py#L81)):*
> This looks wrong, libc (and runtime flavour) is not a property of the environment. If you want it to be for a particular, use -D. We shouldn't add this just because this is convenient for tests.

How do you set default values for jinja variables then? Isn't it via env?

Also we use it for SGX offsets as well.


<!-- Sent from Reviewable.io -->

2021-12-01 18:34 UTC, pwmarcz requested changes
> Reviewed 33 of 50 files at r1, 8 of 13 files at r2, 3 of 3 files at r3, 1 of 6 files at r4, 3 of 4 files at r5, 8 of 10 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 58 of 59 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mpr0km9BJ-SUGYght4X:bsmnf0t) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
It sets the default value to enabled.
</blockquote></details>

Sure, let's build both by default.

However (and not in this PR), for numerous already-discussed reasons, I strongly recommend taking these big projects (namely: 1. glibc, 2. musl, 3. gcc/libgomp, 4. ltp) OUT of Meson, so that they can be built and installed separately.

No need to move them out to a different Git repo, I think it'd be a pain to maintain a separate repo without a real benefit. Just `cd projects/glibc; make; make install`. Or even `cd projects && ./build && ./install`.
___
*[.ci/lib/stage-test.jenkinsfile, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppVqVJ77Y73nzzZ2eQ:-MprFGAF9CBgcFM7bpmN:bbqgqbm) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/.ci/lib/stage-test.jenkinsfile#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

CC: @pwmarcz
</blockquote></details>

Thanks. I was able to reproduce that. Ticketed as https://github.com/gramineproject/gramine/issues/257.

(It's not musl-specific but Ubuntu 18-specific, any rebuild of SGX manifests will trigger it).
___
*[Documentation/building.rst, line 190 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr500g5Yi8rE-1Fhzs:-Mpr500g5Yi8rE-1Fhzt:bg5rgja) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/Documentation/building.rst#L190)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> - To build test binaries, run :command:`meson -Dtests=enabled`. This is
> ```

Building the tests now requires Musl installed on host. I think this is the right place to mention it.
___
*[LibOS/shim/test/regression/meson.build, line 176 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr-soi3E3MOAjCeH-5:-Mpr-soi3E3MOAjCeH-6:bay99yp) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/meson.build#L176)):*
> ```Meson
>     musl_specs_path_cmd = run_command('sh', '-c',
>         'grep -Po -e \'-specs "\K([^"]*)\' `which musl-gcc`')
>     musl_specs_path = musl_specs_path_cmd.stdout().strip()
> ```

(If you end up keeping this...)

I think it belongs to the top-level `meson.build`.

Also, it should properly fail the Meson run if nothing is found. I didn't have musl installed and I'm now getting `cc: fatal error: cannot read spec file ‘/usr/lib/gcc/x86_64-linux-gnu/9/’: Is a directory` during Ninja build (which makes it hard to retry, because even after installing `musl` I need `meson setup --reconfigure` to "fix" it)
___
*[LibOS/shim/test/regression/sighandler_reset.c, line 5 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5Oz85qLx6QAPw8dH:-Mpr5Oz85qLx6QAPw8dI:b-8xvgsw) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/sighandler_reset.c#L5)):*
> ```C
> #include <errno.h>
> #include <signal.h>
> #include <signal.h>
> ```

Double include.
___
*[LibOS/shim/test/regression/stat_invalid_args.c, line 21 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5YsP3xVJMNEvMT_n:-Mpr5YsP3xVJMNEvMT_o:b54zndh) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/stat_invalid_args.c#L21)):*
> ```C
> 
>     /* check stat() */
>     r = syscall(SYS_stat, badpath, goodbuf);
> ```

What is this about, does musl use a different syscall? It'd be good to have a comment with explanation.
___
*[python/graminelibos/gen_jinja_env.py, line 81 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-MpqxPdY91xrsH54xBsZ:-MprFdh82PXcz5-2Fauk:brxfaj) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/python/graminelibos/gen_jinja_env.py#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This looks wrong, libc (and runtime flavour) is not a property of the environment. If you want it to be for a particular, use -D. We shouldn't add this just because this is convenient for tests.

How do you set default values for jinja variables then? Isn't it via env?

Also we use it for SGX offsets as well.
</blockquote></details>

Since this is for tests, I recommend having `gramine-test` always pass `-Dlibc=`, and not having any default. here. We already have a few variables like that (`entrypoint`, `binary_dir` etc.)


<!-- Sent from Reviewable.io -->

2021-12-01 20:38 UTC, mkow requested changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mprg8Tl2Zyfr0Z3zrbt:b-c3qc85) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sure, let's build both by default.

However (and not in this PR), for numerous already-discussed reasons, I strongly recommend taking these big projects (namely: 1. glibc, 2. musl, 3. gcc/libgomp, 4. ltp) OUT of Meson, so that they can be built and installed separately.

No need to move them out to a different Git repo, I think it'd be a pain to maintain a separate repo without a real benefit. Just `cd projects/glibc; make; make install`. Or even `cd projects && ./build && ./install`.
</blockquote></details>

+1 to building both by default
___
*[.ci/lib/stage-test.jenkinsfile, line 32 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppVqVJ77Y73nzzZ2eQ:-MprgO2yEsFyFzVUbk_p:b-83sjoh) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/.ci/lib/stage-test.jenkinsfile#L32)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Thanks. I was able to reproduce that. Ticketed as https://github.com/gramineproject/gramine/issues/257.

(It's not musl-specific but Ubuntu 18-specific, any rebuild of SGX manifests will trigger it).
</blockquote></details>

Nice!
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MprgSZ6DMxaOE9iH8pk:b-qk442u) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't see a good place for this. There seems to be no place in documentation where we describe how to use our built glibc.
</blockquote></details>

But how do you actually decide which library gets used as the user? If via manifest keys, then I guess it should be somewhere there?
___
*[LibOS/shim/test/regression/stat_invalid_args.c, line 21 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5YsP3xVJMNEvMT_n:-Mprh3GM8NZXk1WumD61:b-i4et1h) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/stat_invalid_args.c#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What is this about, does musl use a different syscall? It'd be good to have a comment with explanation.
</blockquote></details>

You mean why not just `stat()`? Then yes, `stat()` wrapper have different implementations depending on libc, so this test should really use the raw syscall (and in general, I guess conceptually most of the LibOS regression tests should probably use raw syscalls?).
Musl and glibc differed here, but I don't remember how exactly.
___
*[LibOS/shim/test/regression/test_libos.py, line 153 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaTwiCZhMwLWreLAo:-MprhZHy6JOnYJtdKkOE:b-6lwv5h) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L153)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

only partially, please also add "is"


<!-- Sent from Reviewable.io -->

2021-12-02 09:57 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MprC6Np183MHMEmSrWj:b-9anusm) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
https://mesonbuild.com/Build-options.html#combos:
> A combo allows any one of the values in the choices parameter to be selected. If no default value is set then the first value will be the default.

At least for consistency, I'd prefer to switch `choices:` order, until we change this to `type: 'feature'`.

And I agree we should take them out of meson, and also `libmbed*_gramine.so*` (not to be confused with `libmbed*_pal.a`, that should remain in meson).
___
*[python/graminelibos/gen_jinja_env.py, line 81 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-MpqxPdY91xrsH54xBsZ:-MprCh5w78bwNNIMknfW:b-e2bhy8) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/python/graminelibos/gen_jinja_env.py#L81)):*
> How do you set default values for jinja variables then? Isn't it via env?

I don't think we need global default values. If you need per-template defaults, you can do `{% if variable is not defined %}` or `{% set variable = variable if variable is defined else 'default' -%}`.

> Also we use it for SGX offsets as well.

This is something different. SGX offsets are "hardcoded", system-specific, matched to libpal.so and no one overrides them.

I think @pwmarcz's recommendation is right.


<!-- Sent from Reviewable.io -->

2021-12-02 10:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 54 of 59 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpuDQ5e89ZWTtpTAtdv:buzm3xb) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to building both by default
</blockquote></details>

Ok, then I leave it as it is.
W.r.t. building them separately: +1. For `musl` it would be easy to just `./configure ... ; make ; make install`. The problem is that we would need some dependency tracking: if we did `make; make install` unconditionally and just added the installed files as dependency in meson, everything would rebuild on each install, which means always... Anyway not for now.
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MpuE9Y4EuIUg5AHxO-e:b-h2i5qf) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But how do you actually decide which library gets used as the user? If via manifest keys, then I guess it should be somewhere there?
</blockquote></details>

What do you mean by "decide which library gets used"? It just a library, it's not different from any other files provided by the user (app, other libs, other files, etc.). You just mount it as a regular file, at a path where your app expects it to be.

In Libos/regression we use jinja templates and generate different manifests depending which one we want to use. We have close to 0 documentation of these templates (just a mention they exists and how you can render them into a normal manifest, but no description of what could be inside such a template).
___
*[Documentation/building.rst, line 190 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr500g5Yi8rE-1Fhzs:-MpuH0bX7AdhiNNOpSzW:b28n1i6) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/Documentation/building.rst#L190)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Building the tests now requires Musl installed on host. I think this is the right place to mention it.
</blockquote></details>

Added it to installing dependencies section (I think it is the right place?)
___
*[LibOS/shim/test/regression/meson.build, line 176 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr-soi3E3MOAjCeH-5:-MpuHD_E-HJQBcbFF4zI:b-w8ki4z) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/meson.build#L176)):*
> I think it belongs to the top-level meson.build.

This is a horrible hack and I would prefer that it stays hidden, buried as deep as possible.

> Also, it should properly fail the Meson run if nothing is found. 

True, done.
___
*[LibOS/shim/test/regression/sighandler_reset.c, line 5 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5Oz85qLx6QAPw8dH:-MpuJriY9i2SlPZrmpm_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/sighandler_reset.c#L5)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Double include.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/stat_invalid_args.c, line 21 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5YsP3xVJMNEvMT_n:-MpuJxoK0BcXWtUdD8k6:bc99rd8) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/stat_invalid_args.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You mean why not just `stat()`? Then yes, `stat()` wrapper have different implementations depending on libc, so this test should really use the raw syscall (and in general, I guess conceptually most of the LibOS regression tests should probably use raw syscalls?).
Musl and glibc differed here, but I don't remember how exactly.
</blockquote></details>

This test passes invalid arguments (as in invalid pointers) to the syscall, to check it's return error codes. Previous version passed these to a library function, not a syscall, which I don't think is a defined behavior (and it broke on musl, which accesses these buffers directly).

The underlying syscall was the same, but that's not important. Also these tests should probably be covered by LTP, but I don't want to mess with it in this PR.
___
*[LibOS/shim/test/regression/test_libos.py, line 153 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MppaTwiCZhMwLWreLAo:-MpuKo9720rTEd5DIrTO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/LibOS/shim/test/regression/test_libos.py#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

only partially, please also add "is"
</blockquote></details>

Done.
___
*[python/graminelibos/gen_jinja_env.py, line 81 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-MpqxPdY91xrsH54xBsZ:-MpuZAGg4Y3mfkdYqOHj:bt7mewk) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/python/graminelibos/gen_jinja_env.py#L81)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Since this is for tests, I recommend having `gramine-test` always pass `-Dlibc=`, and not having any default. here. We already have a few variables like that (`entrypoint`, `binary_dir` etc.)
</blockquote></details>

Actually we already have this. I think I've created this before we had `gramine-test`.


<!-- Sent from Reviewable.io -->

2021-12-02 10:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 54 of 59 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-MpuaQ14CZKQUcZkp5TG:bk4d238) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, then I leave it as it is.
W.r.t. building them separately: +1. For `musl` it would be easy to just `./configure ... ; make ; make install`. The problem is that we would need some dependency tracking: if we did `make; make install` unconditionally and just added the installed files as dependency in meson, everything would rebuild on each install, which means always... Anyway not for now.
</blockquote></details>

@woju But we have the default value set to enabled, I don't understand what you are talking about.
All other options have the `choices` order just as this one, so you want to have consistency with what?


<!-- Sent from Reviewable.io -->

2021-12-02 10:33 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 54 of 59 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson_options.txt, line 12 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpL_HJqAbuetDWMsyA6:-Mpud_VLEYsLOmOUnscz:b-unewg6) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/meson_options.txt#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@woju But we have the default value set to enabled, I don't understand what you are talking about.
All other options have the `choices` order just as this one, so you want to have consistency with what?
</blockquote></details>

I would like the first of "choices" to be the default, irrespective of the `value:` that actually sets the default in this case. But if everything else in this file is backwards, then I guess we can leave this as-is.
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MpufEYf0Q2IrT0k4wzR:b-veefbk) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean by "decide which library gets used"? It just a library, it's not different from any other files provided by the user (app, other libs, other files, etc.). You just mount it as a regular file, at a path where your app expects it to be.

In Libos/regression we use jinja templates and generate different manifests depending which one we want to use. We have close to 0 documentation of these templates (just a mention they exists and how you can render them into a normal manifest, but no description of what could be inside such a template).
</blockquote></details>

This place (`building.rst`) is wrong to document this, but we have manpage for `gramine-manifest`. Maybe there?
___
*[Documentation/building.rst, line 190 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr500g5Yi8rE-1Fhzs:-MpueHUP2raH0WybNNMs:bi2q7du) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/Documentation/building.rst#L190)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Added it to installing dependencies section (I think it is the right place?)
</blockquote></details>

You added it to GDB+tests section, shouldn't you have added it to the previous one?


<!-- Sent from Reviewable.io -->

2021-12-02 11:17 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/building.rst, line 190 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr500g5Yi8rE-1Fhzs:-MpunSJK-T4sfWtssBp2:b-ipy1oh) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/Documentation/building.rst#L190)):*
LGTM, especially now that it also produces an error message.

>You added it to GDB+tests section, shouldn't you have added it to the previous one?

No, this is necessary only when building tests (`-Dtests=enabled`).
___
*[LibOS/shim/test/regression/meson.build, line 176 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr-soi3E3MOAjCeH-5:-Mpunv_N5KLul0uubkgR:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/meson.build#L176)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I think it belongs to the top-level meson.build.

This is a horrible hack and I would prefer that it stays hidden, buried as deep as possible.

> Also, it should properly fail the Meson run if nothing is found. 

True, done.
</blockquote></details>

OK.
___
*[LibOS/shim/test/regression/stat_invalid_args.c, line 21 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr5YsP3xVJMNEvMT_n:-MpupFCV-gGAXzI__SEd:bh5u5zr) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/LibOS/shim/test/regression/stat_invalid_args.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This test passes invalid arguments (as in invalid pointers) to the syscall, to check it's return error codes. Previous version passed these to a library function, not a syscall, which I don't think is a defined behavior (and it broke on musl, which accesses these buffers directly).

The underlying syscall was the same, but that's not important. Also these tests should probably be covered by LTP, but I don't want to mess with it in this PR.
</blockquote></details>

OK, I see we're using raw syscalls in a few of the tests, probably no need to explain every time. Resolving.


<!-- Sent from Reviewable.io -->

2021-12-02 11:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MpuxLBY63-TrmI6ZKPB:bka57xe) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This place (`building.rst`) is wrong to document this, but we have manpage for `gramine-manifest`. Maybe there?
</blockquote></details>

But the issue is we need to document jinja templates generally, not this musl support alone.


<!-- Sent from Reviewable.io -->

2021-12-02 11:56 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mpv-0bI6uDaNi866mCv:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But the issue is we need to document jinja templates generally, not this musl support alone.
</blockquote></details>

Yes.
___
*[Documentation/building.rst, line 190 at r8](https://reviewable.io/reviews/gramineproject/gramine/234#-Mpr500g5Yi8rE-1Fhzs:-Mpv-1hP7MRokPEA3OP2:bg6zxn4) ([raw file](https://github.com/gramineproject/gramine/blob/04f9fc113ead57b5f9d4e3a035e7f0500cd791b9/Documentation/building.rst#L190)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

LGTM, especially now that it also produces an error message.

>You added it to GDB+tests section, shouldn't you have added it to the previous one?

No, this is necessary only when building tests (`-Dtests=enabled`).
</blockquote></details>

OK. Thanks for explanation.


<!-- Sent from Reviewable.io -->

2021-12-02 12:33 UTC, mkow requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mpv6Kjs8HW94dS210L9:b-8sr0p5) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

@boryspoplawski: Yup, but you need to decide _somewhere_ and _somehow_ which one you mount into the application (i.e. from Gramine binaries into the enclave FS). Right now the users have literally no place to learn about this and how to do this?


<!-- Sent from Reviewable.io -->

2021-12-02 12:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mpv7iep8kIVPSbeu09y:bf4hp54) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Yup, but you need to decide _somewhere_ and _somehow_ which one you mount into the application (i.e. from Gramine binaries into the enclave FS). Right now the users have literally no place to learn about this and how to do this?
</blockquote></details>

Or just consider a scenario: you are a user (_not_ a Gramine developer) and have an app using musl. How do you integrate it with Gramine? (I'm asking what the user will do, i.e. what will read, where they will learn about everything, etc.)


<!-- Sent from Reviewable.io -->

2021-12-02 15:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mpvh5Jc0KxpBUcOt7TB:b-fizzil) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
>  Yup, but you need to decide somewhere and somehow which one you mount into the application (i.e. from Gramine binaries into the enclave FS). 

You can mount both, no problem with that.

> Or just consider a scenario: you are a user (not a Gramine developer) and have an app using musl. How do you integrate it with Gramine? (I'm asking what the user will do, i.e. what will read, where they will learn about everything, etc.)

How do you integrate existing apps with glibc? I guess you look into an existing example and see that it uses `gramine.runtimedir()` to mount glibc inside Gramine, if you check documentation of this function, you will see that it allows you to pick which libc you want to use.

We could add an example application (to CI-Examples) using musl, but that's probably extravagance; maybe we should modify busybox example (that's a popular combo busybox+musl, I believe)?


<!-- Sent from Reviewable.io -->

2021-12-03 13:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mq-WEN8E0HpH80fVkTS:b9qv1xb) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
> if you check documentation of this function, you will see that it allows you to pick which libc you want to use.

Why would you check it?

I'd rather opt for saying that `runtimedir()` is parametrizable in some docs page about configuring workloads. I guess people won't even notice that there's such an option otherwise.

@dimakuv, @pwmarcz: What do you think?


<!-- Sent from Reviewable.io -->

2021-12-03 13:57 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 3 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mq-ZiqA0jSMKn6ulx5h:bxtsd8s) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> if you check documentation of this function, you will see that it allows you to pick which libc you want to use.

Why would you check it?

I'd rather opt for saying that `runtimedir()` is parametrizable in some docs page about configuring workloads. I guess people won't even notice that there's such an option otherwise.

@dimakuv, @pwmarcz: What do you think?
</blockquote></details>

We definitely need to add a note about Musl here: https://gramine.readthedocs.io/en/latest/manpages/gramine-manifest.html#gramine.runtimedir

Actually, we have a bunch of places where we need to add Musl (in addition to Glibc). For example: https://gramine.readthedocs.io/en/latest/devel/packaging.html?highlight=glibc

@boryspoplawski Please grep for `glibc` (case-insensitive) in our docs and add Musl there as well.
___
*[LibOS/shim/test/regression/futex.h, line 3 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLakjE92w9BLAGul39:-Mq-_DW-EC5bAKWjZxVn:b-1yejdx) ([raw file](https://github.com/gramineproject/gramine/blob/b998eb09c9d1baccc6a71446783df647afef1613/LibOS/shim/test/regression/futex.h#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, not sure, but I think we don't need to include it in the addendum, as we don't ship it nor any deriverables (it's used only for testing).
</blockquote></details>

Ok, I agree that nothing needs to be done. Resolved.


<!-- Sent from Reviewable.io -->

2021-12-03 15:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 59 of 61 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-Mq-rIFK2wsOGEKGYdjl:bx8b8w3) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
> Why would you check it?

Because you want to map libc (even glibc) inside the enclave and you've seen it in our examples? How are you going to use a function if you don't know what it does?

> I'd rather opt for saying that runtimedir() is parametrizable in some docs page about configuring workloads. I guess people won't even notice that there's such an option otherwise.

But this function is for templates only, if you write the manifest directly you need to specify paths yourself. The only place describing templates already covers this function.

@dimakuv 
> We definitely need to add a note about Musl here:
Done.

> @boryspoplawski Please grep for glibc (case-insensitive) in our docs and add Musl there as well.

I did that before submitting this PR.

> For example: https://gramine.readthedocs.io/en/latest/devel/packaging.html?highlight=glibc

I did not modify this, because I don't see much point in that paragraph. Who is it aimed at? Gramine devs? I guess that's obvious for them. Users? They not need to worry about it, if they are using a supported distribution.

Added a note there just in case you insist.


<!-- Sent from Reviewable.io -->

2021-12-05 22:32 UTC, mkow requested changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MqBh8sWDH-QHlhXINLT:-MqBh8sXA6GTWgk5Xrun:btfqtsf) (no related file):*
The docs does not compile:
```
Documentation/devel/packaging.rst:32: WARNING: undefined label: glibc
(if the link has no caption the label must precede a section header)
```

---
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MqBfgTF6cfTVCCeJXno:b-kdq1ap) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
> Because you want to map libc (even glibc) inside the enclave and you've seen it in our examples? How are you going to use a function if you don't know what it does?

You know very well that it's not how this works in practice :) People will just copy paste our examples and modify/extend them, and `gramine.runtimedir()` won't sound for them like a glibc vs musl switch. And right now it's not obvious where to find information about the setup for musl.

> But this function is for templates only, if you write the manifest directly you need to specify paths yourself. The only place describing templates already covers this function.

I don't think too many users will write manifests directly when the templates are available. And people don't read documentation for all functions they use, we should have more high-level "workflow" documentation - "what do to if you want to run an app in Gramine", not "read docs for all our functions and you'll find the one which has a "musl" switch).


<!-- Sent from Reviewable.io -->

2021-12-06 08:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 5 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MqDnnfv3VzTS0VY8lBL:b-wu9rqs) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
> we should have more high-level "workflow" documentation - "what do to if you want to run an app in Gramine", not "read docs for all our functions and you'll find the one which has a "musl" switch).

I agree but this is definitely for another PR. I'm resolving my comment since Borys added a note on Musl in the docs. We'll probably need some additional, proper documentation on Musl vs Glibc and how to choose & specify each of them.


<!-- Sent from Reviewable.io -->

2021-12-06 11:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MqEX-Zr7QCgQmBjaJDO:b-wahlm0) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> we should have more high-level "workflow" documentation - "what do to if you want to run an app in Gramine", not "read docs for all our functions and you'll find the one which has a "musl" switch).

I agree but this is definitely for another PR. I'm resolving my comment since Borys added a note on Musl in the docs. We'll probably need some additional, proper documentation on Musl vs Glibc and how to choose & specify each of them.
</blockquote></details>

Why another PR? This is just a simple paragraph e.g. in _Quick start_ under "Other example applications" or a change in an example, but with appending "-musl" to its name.


<!-- Sent from Reviewable.io -->

2021-12-06 15:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 60 of 62 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/234#-MqBh8sWDH-QHlhXINLT:-MqF9WDl-PvBHBF_tsC-:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The docs does not compile:
```
Documentation/devel/packaging.rst:32: WARNING: undefined label: glibc
(if the link has no caption the label must precede a section header)
```
</blockquote></details>

Done.

---
___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MqFGErW5oyFuU7SQWUW:bf76btf) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why another PR? This is just a simple paragraph e.g. in _Quick start_ under "Other example applications" or a change in an example, but with appending "-musl" to its name.
</blockquote></details>

Done, tho I don't think `Quick start` is the place we should be having such notes.


<!-- Sent from Reviewable.io -->

2021-12-06 15:16 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/building.rst, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/234#-MpphHqI7U5J_Re3LV2u:-MqFIuGLDEVEN0oCva9F:b6av8u) ([raw file](https://github.com/gramineproject/gramine/blob/a6b66222f490f9f27604719877c7f88e1f350e4a/Documentation/building.rst#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done, tho I don't think `Quick start` is the place we should be having such notes.
</blockquote></details>

Yup, we should refactor our docs at some point.


<!-- Sent from Reviewable.io -->

2021-12-06 15:36 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r12, 1 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 53 of 63 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[Documentation/quickstart.rst, line 136 at r12](https://reviewable.io/reviews/gramineproject/gramine/234#-MqFN_Jt7K0abL3-aDVp:-MqFN_Ju2WYp176S521f:bmhe0i2) ([raw file](https://github.com/gramineproject/gramine/blob/d3e3b65b23de46657180213e34d7deb55b7409c5/Documentation/quickstart.rst#L136)):*
> ```reStructuredText
> -------------
> 
> Most of the examples we provide use GNU C Library. If your application is build
> ```

`GNU C Library` -> `GNU C Library (glibc)`
___
*[Documentation/quickstart.rst, line 136 at r12](https://reviewable.io/reviews/gramineproject/gramine/234#-MqFNcx59rPcuO5ozn2X:-MqFNcx59rPcuO5ozn2Y:b-bial0a) ([raw file](https://github.com/gramineproject/gramine/blob/d3e3b65b23de46657180213e34d7deb55b7409c5/Documentation/quickstart.rst#L136)):*
> ```reStructuredText
> -------------
> 
> Most of the examples we provide use GNU C Library. If your application is build
> ```

`build` -> `built`


<!-- Sent from Reviewable.io -->

2021-12-06 15:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: 53 of 63 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 10 at r5](https://reviewable.io/reviews/gramineproject/gramine/234#-MpLYtpFAIzOZQ10gxfG):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 136 at r12](https://reviewable.io/reviews/gramineproject/gramine/234#-MqFN_Jt7K0abL3-aDVp:-MqFPoB4AjpnJSKd0jf7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3e3b65b23de46657180213e34d7deb55b7409c5/Documentation/quickstart.rst#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`GNU C Library` -> `GNU C Library (glibc)`
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 136 at r12](https://reviewable.io/reviews/gramineproject/gramine/234#-MqFNcx59rPcuO5ozn2X:-MqFPoRuAARtS8MgDjR8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3e3b65b23de46657180213e34d7deb55b7409c5/Documentation/quickstart.rst#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`build` -> `built`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-06 17:13 UTC, mkow approved these changes
> Reviewed 9 of 11 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-12-06 19:02 UTC, dimakuv approved these changes
> Reviewed 7 of 11 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/234)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-06 20:18 UTC, merged