Enable stack sanitization
gramineproject/gramine pull request #240
Opened 2021-11-22 14:33 UTC by pwmarcz

## Description of the changes 

This enables stack sanitization in ASan, which means mostly stack buffer overflows and use-after-scope. However, no use-after-free yet, see below.

Tracking issue: #19.

## Why not use-after-return?

It would be really nice to also detect use-after-return bugs. However, this is difficult to do at the moment: it requires replacing stack allocations with heap allocations (there are callbacks for that: `__asan_stack_{malloc,free}`), so our ASan library would need to manage that memory.

However, right now there are *two* libraries running at the same time, PAL and LibOS, each allocating its own memory. Right now each of these has its own copy of "common" code, including `asan.c`. But since the code from both libraries runs on the same stack, the ASan library for both PAL and LibOS would need to allocate and free the same memory.

I guess one solution would be to keep only the ASan library in PAL. The `__asan_*` functions will be exported by PAL, and LibOS will not contain its own copy of the callbacks, but call the ones in PAL. Then, ASan could maintain its own structures, and use `malloc` and `free` from PAL.

I'm curious to hear your opinion on this.

## How to test this PR? 

* CI should pass
* Try triggering some stack buffer overflows manually?

2021-11-22 14:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 0 of 23 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_internal.h, line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/240#-Mp73xz8B7quN_7ZXc1J:-Mp73xz8B7quN_7ZXc1K:bdpf7x7) ([raw file](https://github.com/gramineproject/gramine/blob/9a0e4b1cad5dc275e004e336e005984beb2f8324/LibOS/shim/include/shim_internal.h#L57)):*
> ```objc
>  * handling may change it).
>  *
>  * This function should be called from the LibOS stack. When AddressSanitizer is enabled, it also
> ```

FYI: despite the name, `return_from_syscall` was also called during LibOS startup, from `restore_child_context_after_clone`. This is now separated.
___
*[LibOS/shim/src/sys/shim_exec.c, line 137 at r1](https://reviewable.io/reviews/gramineproject/gramine/240#-Mp74nXGB4a9KlbmJOqG:-Mp74nXGB4a9KlbmJOqH:b6unt91) ([raw file](https://github.com/gramineproject/gramine/blob/9a0e4b1cad5dc275e004e336e005984beb2f8324/LibOS/shim/src/sys/shim_exec.c#L137)):*
> ```C
>     put_handle(hdl);
> 
>     __shim_do_execve_rtld(new_argp, new_auxv);
> ```

FYI: As far as I can tell, this "switch stacks" code is pretty old and not necessary anymore, and it causes Gramine to run on user stack which we shouldn't do. We now set up the new stack and switch to it in `execute_elf_object`.


<!-- Sent from Reviewable.io -->

2021-11-23 09:35 UTC, dimakuv requested changes
> Reviewed 19 of 23 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAq28c4zYN2qJQ86zo):*
Could you expand on this or at least give a quick example? This paragraph is intriguing but too vague.
___
*[common/include/asan.h, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpArfv-8dkFZccmDhoV:-MpArfv-8dkFZccmDhoW:bmavr3p) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L70)):*
> ```objc
>  * - Make sure code instrumented by AddressSanitizer runs *only* on stacks controlled by Gramine. If
>  *   code needs to run on user's stack, it should be all annotated with
>  *   `__attribute_no_sanitize_address` or written in assembly.
> ```

But this never happens in Gramine, right? We never share the stack with the user app (nor normal stack neither alt stack). Or am I misunderstanding?

If we never share the stack with the app, could you add a comment about this? Smth like `Note that Gramine by design never runs on user's stack; thus such an annotation should never be needed.`
___
*[common/include/asan.h, line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAsZdGB12F3zzLOuXA:-MpAsZdGB12F3zzLOuXB:b-r17qod) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L77)):*
> ```objc
>  * - When a thread abandons the current stack, it should unpoison that stack. When unpoisoning the
>  *   *current* stack, use `asan_unpoison_current_stack`, and make sure the caller is not
>  *   instrumented by ASan.
> ```

I can't parse this sentence. What do you mean by `*current* stack`? In contrast to what? What other stack could it be? Why the caller must be *not* instrumented by ASan? Please expand.

Looking at the paras below, you probably mean the "used part of the stack" by this `*current* stack`? I.e., we shouldn't unpoison the whole memory area dedicated to the stack (e.g. `0x200 - 0x400`) but only the part that contained the stack frames (e.g. `0x300 - 0x400`)?

UPDATE: Looking at `asan_unpoison_current_stack`, I guess you're recommending to use it (instead of `asan_unpoison_region`) simply because it double-checks that the unpoisoined region is indeed the current stack.
___
*[common/include/asan.h, line 166 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAu28m2iIL-tGAGQEk:-MpAu28m2iIL-tGAGQEl:b-1h1pvy) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L166)):*
> ```objc
> /* Unpoison current stack. If the current stack frame is between `addr .. addr + size`, behaves the
>  * same as `asan_unpoison_region`. Otherwise, prints a warning. */
> void asan_unpoison_current_stack(uintptr_t addr, size_t size);
> ```

So the only difference of this function from `asan_unpoison_region` is that it prints a warning if detects that the region doesn't look like a current stack? If yes, could you reword your comment along these lines (I want to see `the only difference` phrase in the comment)?
___
*[common/include/asan.h, line 209 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAuoTSDRIohxMN56dW:-MpAuoTSDRIohxMN56dX:b3h586b) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L209)):*
> ```objc
>  *
>  * Our implementation is a no-op, because it's inconvenient to determine the top of the current
>  * stack in a universal fashion. Instead, we rely on Gramine to clean up the right stack.
> ```

`we rely on ASan-specific Gramine logic`? I don't know how to phrase it better, but we're relying on our added code in several places in Gramine codebase. The current "rely on Gramine" is very vague.
___
*[common/include/asan.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAvOQg8EPf8oZqNykt:-MpAvOQg8EPf8oZqNyku:b-nus75f) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L220)):*
> ```objc
>  * - right redzone: ASAN_ALLOCA_REDZONE_SIZE bytes after partial right redzone
>  *
>  * `addr` will be aligned to ASAN_ALLOCA_REDZONE_SIZE.
> ```

`will be` -> `must be`
___
*[common/src/asan.c, line 56 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAxWrW2tugZFBXDy7i:-MpAxWrW2tugZFBXDy7j:bqig8gl) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L56)):*
> ```C
> void asan_unpoison_current_stack(uintptr_t addr, size_t size) {
>     uintptr_t top = addr;
>     uintptr_t bottom = addr + size;
> ```

Why do you even need these `top` and `bottom`? The code would be perfectly readable with `addr` and `addr + size`.

UPDATE: On the other hand, you have unformity with `__asan_allocas_unpoison`. Feel free to leave as-is, not blocking.
___
*[common/src/asan.c, line 177 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAy0LG2tdRFi9ssbqP:-MpAy0LG2tdRFi9ssbqQ:b-bim2u5) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L177)):*
> ```C
>     log_error("asan: %22s %02x", "stack mid redzone:", ASAN_POISON_STACK_MID);
>     log_error("asan: %22s %02x", "stack right redzone:", ASAN_POISON_STACK_RIGHT);
>     log_error("asan: %22s %02x", "stack after scope:", ASAN_POISON_STACK_USE_AFTER_SCOPE);
> ```

`stack use after scope`?
___
*[common/src/asan.c, line 313 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAyrJtDvAOoxIwTmec:-MpAyrJtDvAOoxIwTmed:b2veif3) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L313)):*
> ```C
>     uintptr_t left_redzone_addr = addr - ASAN_ALLOCA_REDZONE_SIZE;
>     uintptr_t end_addr = addr + size;
>     uintptr_t right_redzone_addr = ALIGN_UP(end_addr, ASAN_ALLOCA_REDZONE_SIZE) +
> ```

The name should be `right_redzone_addr_end`
___
*[common/src/asan.c, line 316 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAyeO6BI-kuHtIuxkD:-MpAyeO6BI-kuHtIuxkE:b-mqejvl) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L316)):*
> ```C
>         ASAN_ALLOCA_REDZONE_SIZE;
>     asan_poison_region(left_redzone_addr, ASAN_ALLOCA_REDZONE_SIZE, ASAN_POISON_ALLOCA_LEFT);
>     asan_poison_region(addr, right_redzone_addr - addr, ASAN_POISON_ALLOCA_RIGHT);
> ```

Why not start with `addr + size`? I understand that this also works, but `addr + size` would be cleaner.
___
*[LibOS/shim/include/shim_defs.h, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAqF7u9OvJRcF_owdM:-MpAqF7u9OvJRcF_owdN:b-43nupl) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/LibOS/shim/include/shim_defs.h#L11)):*
> ```objc
> #define ERESTARTNOHAND  514 /* Restart if no signal handler. */
> 
> /* Internal LibOS stack size: 7 pages + one guard page. */
> ```

Please update the comment as well (and explain that ASan's stack sanitization requires more stack space).
___
*[LibOS/shim/src/shim_rtld.c, line 824 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpB8b6nBx7BZm4X2fjd:-MpB8b6nBx7BZm4X2fje:bwwr11r) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/LibOS/shim/src/shim_rtld.c#L824)):*
> ```C
> 
> #ifdef ASAN
> __attribute_no_sanitize_address
> ```

I'm getting confused as to when  [...]

2021-11-23 12:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 15 of 24 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpBZD1b1QjBMcbiHZXd):*
@dimakuv As promised, some analysis:

There are 4 such GOT entries: 
```
000000257fc0  001000000006 R_X86_64_GLOB_DAT 00000000001d1000 DkSetExceptionHandler@@PAL + 0
000000257fc8  001800000006 R_X86_64_GLOB_DAT 00000000001eae80 DkStreamChangeName@@PAL + 0
000000257fd0  002400000006 R_X86_64_GLOB_DAT 00000000001e92f0 DkStreamAttributesQuer@@PAL + 0
000000257fd8  002e00000006 R_X86_64_GLOB_DAT 00000000001d9a30 DkCpuIdRetrieve@@PAL + 0
```

I'm not sure what's causing these 4 functions to behave that way. Let's try to compile this:

```sh
cd build-san
FILE=Pal/src/host/Linux-SGX/libpal.so.p/.._.._db_misc.c.o

# Rebuild, to see the exact command:
ninja -t clean $FILE
ninja -v $FILE

# Generate LLVM IR and assembly (pasting the clang invocation seen above):
clang ... -S -emit-llvm -o db_misc.ll
clang ... -S -o db_misc.s
```

The code emitted by LLVM allocates a buffer on stack, and stores a bunch of things there, including a pointer to the function itself.

```llvm
; Function Attrs: noinline nounwind optnone sanitize_address uwtable
define i32 @DkCpuIdRetrieve(i32 %leaf, i32 %subleaf, i32* %values) #0 !dbg !109 {
  ...
  store i64 ptrtoint (i32 (i32, i32, i32*)* @DkCpuIdRetrieve to i64), i64* %7
```

I'm not sure how exactly it's being used, maybe for the ASan library to track where an allocation was made?

But anyway, this gets translated to:

```asm
        movq    DkCpuIdRetrieve@GOTPCREL(%rip), %rax
```

I don't know enough about LLVM to say if this can be avoided.
___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAq28c4zYN2qJQ86zo):*
I'm not sure how to put it concisely. How about:

>The implementation requires Gramine to maintain proper hygiene when handling stack memory. Otherwise, false positives are possible: if Gramine stops using a stack (e.g. when returning from a syscall), but doesn't unpoison it, the poisoned stack memory can incorrectly trigger AddressSanitizer the next time that stack is used.
___
*[common/include/asan.h, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpArfv-8dkFZccmDhoV:-MpBL_hLCCN_1g_H3JgG:bpcrw7q) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this never happens in Gramine, right? We never share the stack with the user app (nor normal stack neither alt stack). Or am I misunderstanding?

If we never share the stack with the app, could you add a comment about this? Smth like `Note that Gramine by design never runs on user's stack; thus such an annotation should never be needed.`
</blockquote></details>

1. There were cases where we violated this: `shim_call` (fixed in #221), and `shim_do_execve_rtld` (fixed in this branch).
2. The unavoidable case is vDSO functions (which contain `GRAMINE_SYSCALL` but are written in C). And, technically, the syscall entry code also starts on the user stack.

I added a mention about vDSO.
___
*[common/include/asan.h, line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAsZdGB12F3zzLOuXA:-MpBNqOe9k9uKrOP5EIJ:b8goy4z) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L77)):*
> I can't parse this sentence. What do you mean by *current* stack? In contrast to what? What other stack could it be? 

The stack your current frame is on. You could be unpoisoning a stack "from outside", e.g. after jumping to another stack, or from another thread entirely.

>Why the caller must be not instrumented by ASan? Please expand.

I added an explanation: the caller will usually be a `noreturn` function, so we need to make sure it doesn't poison any memory after the stack is supposed to be "clean".

>Looking at the paras below, you probably mean the "used part of the stack" by this *current* stack? I.e., we shouldn't unpoison the whole memory area dedicated to the stack (e.g. 0x200 - 0x400) but only the part that contained the stack frames (e.g. 0x300 - 0x400)?

I don't mean that. I think that yes, we could only unpoison the "used" part, but we always know both the stack top and bottom, and in some scenarios we don't know what's the used part (e.g. if unpoisoning "from outside"). So it's easier to always unpoison the whole area.
___
*[common/include/asan.h, line 166 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAu28m2iIL-tGAGQEk:-MpBQb-rDWT8Eh0Hwo7X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L166)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So the only difference of this function from `asan_unpoison_region` is that it prints a warning if detects that the region doesn't look like a current stack? If yes, could you reword your comment along these lines (I want to see `the only difference` phrase in the comment)?
</blockquote></details>

Done.
___
*[common/include/asan.h, line 209 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAuoTSDRIohxMN56dW:-MpBQi0a0nIPu2DF5qJT:blh5rry) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L209)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`we rely on ASan-specific Gramine logic`? I don't know how to phrase it better, but we're relying on our added code in several places in Gramine codebase. The current "rely on Gramine" is very vague.
</blockquote></details>

Reworded ("ASan-specific logic in Gramine").
___
*[common/include/asan.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAvOQg8EPf8oZqNykt:-MpBQtkA-A0N5YddAeWd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`will be` -> `must be`
</blockquote></details>

Done.
___
*[common/src/asan.c, line 56 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAxWrW2tugZFBXDy7i:-MpBR7Q430isLNnu6zfs:bk1vmrb) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you even need these `top` and `bottom`? The code would be perfectly readable with `addr` and `addr + size`.

UPDATE: On the other hand, you have unformity with `__asan_allocas_unpoison`. Feel free to leave as-is, not blocking.
</blockquote></details>

I started out with this function taking `top` and `bottom`. But I agree, it's better to omit them entirely. (I always mix up "top" and "bottom"...)

I also modified the message to display the region as `0xabc-0xbcd`, this is what we do in other log messages.
___
*[common/src/asan.c, line 177 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAy0LG2tdRFi9ssbqP:-MpBRX2I2aBowJQn5DmX:b-o8q3on) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L177)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`stack use after scope`?
</blockquote></details>

I'd rather remove the "use" entirely (except still calling the bug "use-after [...]

2021-11-23 12:57 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpBZD1b1QjBMcbiHZXd):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

@dimakuv As promised, some analysis:

There are 4 such GOT entries: 
```
000000257fc0  001000000006 R_X86_64_GLOB_DAT 00000000001d1000 DkSetExceptionHandler@@PAL + 0
000000257fc8  001800000006 R_X86_64_GLOB_DAT 00000000001eae80 DkStreamChangeName@@PAL + 0
000000257fd0  002400000006 R_X86_64_GLOB_DAT 00000000001e92f0 DkStreamAttributesQuer@@PAL + 0
000000257fd8  002e00000006 R_X86_64_GLOB_DAT 00000000001d9a30 DkCpuIdRetrieve@@PAL + 0
```

I'm not sure what's causing these 4 functions to behave that way. Let's try to compile this:

```sh
cd build-san
FILE=Pal/src/host/Linux-SGX/libpal.so.p/.._.._db_misc.c.o

# Rebuild, to see the exact command:
ninja -t clean $FILE
ninja -v $FILE

# Generate LLVM IR and assembly (pasting the clang invocation seen above):
clang ... -S -emit-llvm -o db_misc.ll
clang ... -S -o db_misc.s
```

The code emitted by LLVM allocates a buffer on stack, and stores a bunch of things there, including a pointer to the function itself.

```llvm
; Function Attrs: noinline nounwind optnone sanitize_address uwtable
define i32 @DkCpuIdRetrieve(i32 %leaf, i32 %subleaf, i32* %values) #0 !dbg !109 {
  ...
  store i64 ptrtoint (i32 (i32, i32, i32*)* @DkCpuIdRetrieve to i64), i64* %7
```

I'm not sure how exactly it's being used, maybe for the ASan library to track where an allocation was made?

But anyway, this gets translated to:

```asm
        movq    DkCpuIdRetrieve@GOTPCREL(%rip), %rax
```

I don't know enough about LLVM to say if this can be avoided.
</blockquote></details>

Thanks. It would be interesting to see the final asm: what happens next to `%rax`? Is it simply stored on the stack, and it doesn't look like anything uses that particular stack addr? Anyway, I don't care that much; maybe I'll check it in the future.
___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAq28c4zYN2qJQ86zo):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not sure how to put it concisely. How about:

>The implementation requires Gramine to maintain proper hygiene when handling stack memory. Otherwise, false positives are possible: if Gramine stops using a stack (e.g. when returning from a syscall), but doesn't unpoison it, the poisoned stack memory can incorrectly trigger AddressSanitizer the next time that stack is used.
</blockquote></details>

I like this text. `AddressSanitizer` -> `ASan`, the rest looks good.
___
*[common/include/asan.h, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpArfv-8dkFZccmDhoV:-MpBpaen7KqMgk8_BfyJ:b-ny3bbz) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L70)):*
> The unavoidable case is vDSO functions (which contain GRAMINE_SYSCALL but are written in C).

But I don't see any `__attribute_no_sanitize_address` annotations in any vDSO code?
___
*[common/src/asan.c, line 316 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAyeO6BI-kuHtIuxkD:-MpBqrbZ9XY_f7-j9tpm:b-hbzzja) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L316)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because `addr + size` may not be aligned, and the poison/unpoison functions require it.
</blockquote></details>

OK, got it.
___
*[Pal/src/db_rtld.c, line 628 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpB38WG55P-6dSBJsJM:-MpBrHZn8XWXZ8n-MW5O:b-mgb3tw) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/Pal/src/db_rtld.c#L628)):*
> We cannot jump to a LibOS stack because LibOS allocates these for itself.

Yes, but this is a special case of LibOS init in the main thread, so we could allocate the LibOS stack here instead of during `shim_init()`. Anyway, it's not important.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 732 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpB6UXs1fEWzX3fWEvj:-MpBrg1e2SV7VUwiFj5_:b-52hw40) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/Pal/src/host/Linux-SGX/enclave_entry.S#L732)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, this assembly is pretty ugly, these parts are not even in any function :( I'm not sure what's the exact scenario in which we jump to `_restore_sgx_context` from `enclave_entry` instead of calling it from C.

Anyway, I think it's better to move this cleanup to C, it's supposed to clean up after the `noreturn` functions in `db_exception.c` anyway.
</blockquote></details>

OK, this is a much better solution.


<!-- Sent from Reviewable.io -->

2021-11-23 13:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 24 of 26 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpBZD1b1QjBMcbiHZXd):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks. It would be interesting to see the final asm: what happens next to `%rax`? Is it simply stored on the stack, and it doesn't look like anything uses that particular stack addr? Anyway, I don't care that much; maybe I'll check it in the future.
</blockquote></details>

It gets stored on stack, along with a magic value, and what looks like a debug string:

```asm
        movq    DkCpuIdRetrieve@GOTPCREL(%rip), %rax
        ...
        movq    $1102416563, 288(%rsp)  # imm = 0x41B58AB3
        leaq    .L___asan_gen_(%rip), %r9
        movq    %r9, 296(%rsp)
        movq    %rax, 304(%rsp)
        ...

.L___asan_gen_:
        .asciz  "1 32 16 7 vals:40"
        .size   .L___asan_gen_, 18
```

I searched for that magic value (0x41B58AB3), and found the part of ASan that emits this code. Apparently this is some metadata written to an alloca redzone (but only in the case of static, i.e. known size, allocations), and later read by the AddressSanitizer library. Then later we store another magic value to indicate that we returned from this stack frame.

(By the way, if you google for 0x41B58AB3, you get a bunch of ASan tracebacks :) )

```cpp
// AddressSanitizer.cpp

static const uintptr_t kCurrentStackFrameMagic = 0x41B58AB3;
static const uintptr_t kRetiredStackFrameMagic = 0x45E0360E;

void FunctionStackPoisoner::processStaticAllocas() {
  ...

  // The left-most redzone has enough space for at least 4 pointers.
  // Write the Magic value to redzone[0].
  Value *BasePlus0 = IRB.CreateIntToPtr(LocalStackBase, IntptrPtrTy);
  IRB.CreateStore(ConstantInt::get(IntptrTy, kCurrentStackFrameMagic),
                  BasePlus0);
  // Write the frame description constant to redzone[1].
  Value *BasePlus1 = IRB.CreateIntToPtr(
      IRB.CreateAdd(LocalStackBase,
                    ConstantInt::get(IntptrTy, ASan.LongSize / 8)),
      IntptrPtrTy);
  GlobalVariable *StackDescriptionGlobal =
      createPrivateGlobalForString(*F.getParent(), DescriptionString,
                                   /*AllowMerging*/ true, kAsanGenPrefix);
  Value *Description = IRB.CreatePointerCast(StackDescriptionGlobal, IntptrTy);
  IRB.CreateStore(Description, BasePlus1);
  // Write the PC to redzone[2].
  Value *BasePlus2 = IRB.CreateIntToPtr(
      IRB.CreateAdd(LocalStackBase,
                    ConstantInt::get(IntptrTy, 2 * ASan.LongSize / 8)),
      IntptrPtrTy);
  IRB.CreateStore(IRB.CreatePointerCast(&F, IntptrTy), BasePlus2);

  ...

  // (Un)poison the stack before all ret instructions.
  for (auto Ret : RetVec) {
    IRBuilder<> IRBRet(Ret);
    // Mark the current frame as retired.
    IRBRet.CreateStore(ConstantInt::get(IntptrTy, kRetiredStackFrameMagic),
                       BasePlus0);
  ...
```
___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAq28c4zYN2qJQ86zo):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like this text. `AddressSanitizer` -> `ASan`, the rest looks good.
</blockquote></details>

OK, I'll update on rebase.
___
*[common/include/asan.h, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpArfv-8dkFZccmDhoV:-MpByzZX2eh8mQC35j_a:b96nmaq) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/include/asan.h#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> The unavoidable case is vDSO functions (which contain GRAMINE_SYSCALL but are written in C).

But I don't see any `__attribute_no_sanitize_address` annotations in any vDSO code?
</blockquote></details>

You're right! I had that in an earlier revision of this code. Fixed.

(I guess this didn't cause any problems because the functions are simple enough to not need any stack sanitization).


<!-- Sent from Reviewable.io -->

2021-11-23 15:07 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpBZD1b1QjBMcbiHZXd):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It gets stored on stack, along with a magic value, and what looks like a debug string:

```asm
        movq    DkCpuIdRetrieve@GOTPCREL(%rip), %rax
        ...
        movq    $1102416563, 288(%rsp)  # imm = 0x41B58AB3
        leaq    .L___asan_gen_(%rip), %r9
        movq    %r9, 296(%rsp)
        movq    %rax, 304(%rsp)
        ...

.L___asan_gen_:
        .asciz  "1 32 16 7 vals:40"
        .size   .L___asan_gen_, 18
```

I searched for that magic value (0x41B58AB3), and found the part of ASan that emits this code. Apparently this is some metadata written to an alloca redzone (but only in the case of static, i.e. known size, allocations), and later read by the AddressSanitizer library. Then later we store another magic value to indicate that we returned from this stack frame.

(By the way, if you google for 0x41B58AB3, you get a bunch of ASan tracebacks :) )

```cpp
// AddressSanitizer.cpp

static const uintptr_t kCurrentStackFrameMagic = 0x41B58AB3;
static const uintptr_t kRetiredStackFrameMagic = 0x45E0360E;

void FunctionStackPoisoner::processStaticAllocas() {
  ...

  // The left-most redzone has enough space for at least 4 pointers.
  // Write the Magic value to redzone[0].
  Value *BasePlus0 = IRB.CreateIntToPtr(LocalStackBase, IntptrPtrTy);
  IRB.CreateStore(ConstantInt::get(IntptrTy, kCurrentStackFrameMagic),
                  BasePlus0);
  // Write the frame description constant to redzone[1].
  Value *BasePlus1 = IRB.CreateIntToPtr(
      IRB.CreateAdd(LocalStackBase,
                    ConstantInt::get(IntptrTy, ASan.LongSize / 8)),
      IntptrPtrTy);
  GlobalVariable *StackDescriptionGlobal =
      createPrivateGlobalForString(*F.getParent(), DescriptionString,
                                   /*AllowMerging*/ true, kAsanGenPrefix);
  Value *Description = IRB.CreatePointerCast(StackDescriptionGlobal, IntptrTy);
  IRB.CreateStore(Description, BasePlus1);
  // Write the PC to redzone[2].
  Value *BasePlus2 = IRB.CreateIntToPtr(
      IRB.CreateAdd(LocalStackBase,
                    ConstantInt::get(IntptrTy, 2 * ASan.LongSize / 8)),
      IntptrPtrTy);
  IRB.CreateStore(IRB.CreatePointerCast(&F, IntptrTy), BasePlus2);

  ...

  // (Un)poison the stack before all ret instructions.
  for (auto Ret : RetVec) {
    IRBuilder<> IRBRet(Ret);
    // Mark the current frame as retired.
    IRBRet.CreateStore(ConstantInt::get(IntptrTy, kRetiredStackFrameMagic),
                       BasePlus0);
  ...
```
</blockquote></details>

OK, thanks, interesting


<!-- Sent from Reviewable.io -->

2021-11-23 15:32 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpCQ4FF9ZUSKNKHQvOP:baa8n75) (no related file):*
@dimakuv What do you think about enabling use-after-return (i.e. what I wrote in the main PR comment)? This looks like a similar problem to all your attempts to link PAL and LibOS together...

---


<!-- Sent from Reviewable.io -->

2021-11-24 07:20 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpFleeR8bO2DEidRtyV:buj73lr) (no related file):*
I gave up on my attempts to link PAL and LibOS components together. It was doable, but with some hacks. For some (very incomplete) details, see my issue and PR:
- https://github.com/gramineproject/graphene/pull/2397
- https://github.com/gramineproject/graphene/issues/2382

From what I understand, you problem is that ASan-enabled compiler will insert `__asan_stack_{malloc,free}` in place of stack allocations. And since the stack is shared between PAL and LibOS components, you will need to call in this func either `pal_{malloc,free}` or `libos_{malloc,free}`. And you have no way to decide which of the two should be called for each inserted `__asan_stack_{malloc,free}`.

This was exactly the problem I tried to solve with my PR (linked above). But this was hacky as hell, and Borys loathed it.

> I guess one solution would be to keep only the ASan library in PAL. The __asan_* functions will be exported by PAL, and LibOS will not contain its own copy of the callbacks, but call the ones in PAL.

That would be reasonable. Though I'm unclear how this should work. As an example, what would happen for `__asan_stack_{malloc,free}`? You still need to LibOS-bookkeep this memory (if it was called during LibOS execution) and you should *not* LibOS-bookkeep otherwise. So don't you need a way to distinguish between LibOS and PAL anyway?

---


<!-- Sent from Reviewable.io -->

2021-11-24 08:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpFvFP1BdufE9ykBCSA:bcbvs3l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I gave up on my attempts to link PAL and LibOS components together. It was doable, but with some hacks. For some (very incomplete) details, see my issue and PR:
- https://github.com/gramineproject/graphene/pull/2397
- https://github.com/gramineproject/graphene/issues/2382

From what I understand, you problem is that ASan-enabled compiler will insert `__asan_stack_{malloc,free}` in place of stack allocations. And since the stack is shared between PAL and LibOS components, you will need to call in this func either `pal_{malloc,free}` or `libos_{malloc,free}`. And you have no way to decide which of the two should be called for each inserted `__asan_stack_{malloc,free}`.

This was exactly the problem I tried to solve with my PR (linked above). But this was hacky as hell, and Borys loathed it.

> I guess one solution would be to keep only the ASan library in PAL. The __asan_* functions will be exported by PAL, and LibOS will not contain its own copy of the callbacks, but call the ones in PAL.

That would be reasonable. Though I'm unclear how this should work. As an example, what would happen for `__asan_stack_{malloc,free}`? You still need to LibOS-bookkeep this memory (if it was called during LibOS execution) and you should *not* LibOS-bookkeep otherwise. So don't you need a way to distinguish between LibOS and PAL anyway?
</blockquote></details>

I think I don't need to use both LibOS and PAL's allocators, I can use only PAL's malloc (which would keep the "stack" objects in PAL-internal memory). Or even have `asan.c` implement its own allocator that asks PAL for pages from its internal pool.

The point is: the code does not treat these allocations as heap allocations, it does not ever call `free()` on them. So they can be fully  managed by `asan.c` without interference from outside. The problem is that (1) `asan.c` needs to exist in only one copy; (2) it needs to be able to allocate memory.

---


<!-- Sent from Reviewable.io -->

2021-11-24 09:19 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpGE3lFAjZg6EKZlzyo:b-babhd6) (no related file):*
Ah, true, so everything is simple then.

> I guess one solution would be to keep only the ASan library in PAL. The __asan_* functions will be exported by PAL, and LibOS will not contain its own copy of the callbacks, but call the ones in PAL.

Why do you actually need to move *all* `__asan_` functions to PAL and export from there? Why not just have an exception to only this `__asan_stack_malloc/free` function? PAL will export smth like `DkDebugAsanMalloc` and `DkDebugAsanFree`, and LibOS layer will use these callbacks in its `__asan_stack_malloc/free` implementations?

---


<!-- Sent from Reviewable.io -->

2021-11-24 09:41 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpGG-y6AKFlXrUw2ncO:b-1eybx8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, true, so everything is simple then.

> I guess one solution would be to keep only the ASan library in PAL. The __asan_* functions will be exported by PAL, and LibOS will not contain its own copy of the callbacks, but call the ones in PAL.

Why do you actually need to move *all* `__asan_` functions to PAL and export from there? Why not just have an exception to only this `__asan_stack_malloc/free` function? PAL will export smth like `DkDebugAsanMalloc` and `DkDebugAsanFree`, and LibOS layer will use these callbacks in its `__asan_stack_malloc/free` implementations?
</blockquote></details>

It isn't about just providing malloc/free, though. I'd need at least the `__asan_handle_no_return` callback to access the same state (it has to free/invalidate all stack allocations made so far). And possibly `asan_report` might use some information for diagnostics. So it sounds like splitting the `asan.c` library into two parts, along pretty arbitrary lines, and with extra boilerplate (callbacks, `Dk*` wrappers).

---


<!-- Sent from Reviewable.io -->

2021-11-24 12:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpGsxD75EjmIkEZMngu:b-bvytye) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It isn't about just providing malloc/free, though. I'd need at least the `__asan_handle_no_return` callback to access the same state (it has to free/invalidate all stack allocations made so far). And possibly `asan_report` might use some information for diagnostics. So it sounds like splitting the `asan.c` library into two parts, along pretty arbitrary lines, and with extra boilerplate (callbacks, `Dk*` wrappers).
</blockquote></details>

On the other hand... yeah, if PAL provided just "allocate/deallocate some memory" primitives to `asan.c`, then maybe it wouldn't be so bad. I still need some global state (at least a single pointer), but maybe that can also be provided by PAL... or just stored at the beginning of the shadow map, I guess.

---


<!-- Sent from Reviewable.io -->

2021-11-25 09:48 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpLTxll4vf_bvKkZXa6:b-denllh) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

On the other hand... yeah, if PAL provided just "allocate/deallocate some memory" primitives to `asan.c`, then maybe it wouldn't be so bad. I still need some global state (at least a single pointer), but maybe that can also be provided by PAL... or just stored at the beginning of the shadow map, I guess.
</blockquote></details>

Still sounds like quite some hacks (having a global state, exposed either through a `Dk*` function or stored at a predefined addr).

So waht would be the benefit of enabling `use-after-return` instrumentation of ASan? Like, do you know of any qualitative research on how many bugs happen due to stack escaping in C? Or do you have an intuition on this? Maybe the benefits are so small that they don't merit any solution at all.

Also, we still don't enable ASan on globals, right? Would that enablement also need additional complexity? And the same question: would the benefits outweigh the complexity introduced?

---


<!-- Sent from Reviewable.io -->

2021-11-25 10:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpLelWM4wj3gj2C0zuZ:b3mqy1g) (no related file):*
>Still sounds like quite some hacks (having a global state, exposed either through a Dk* function or stored at a predefined addr).

I know... But it's not like this is only a problem with use-after-return. Adding `describe_location` was already painful due to this PAL/LibOS split, as was this branch (I considered `asan.c` globally keeping track of what stack memory Gramine has, not sure if that would be a good solution, but right now it's not possible at all).

That's why I'm considering making the whole `asan.c` PAL-only, I suspect it would make things simpler in the long run.

>So waht would be the benefit of enabling use-after-return instrumentation of ASan? Like, do you know of any qualitative research on how many bugs happen due to stack escaping in C? Or do you have an intuition on this? Maybe the benefits are so small that they don't merit any solution at all.

I don't know of any such research. I'll try to implement this (even in a hacky way) and see if it finds any bugs in Gramine. I'm not sure what to expect, but this PR (i.e. sanitization for stack variables *before* return) already found two issues (95703473ac379170c7e72da959d24f8470366f16, d2645b4b0945df03bb8fff3f5d2ecec5cba3ada4), and we do like to over-use `alloca`. So I think it's at least worth trying.

>Also, we still don't enable ASan on globals, right? Would that enablement also need additional complexity? And the same question: would the benefits outweigh the complexity introduced?

The additional complexity needed is making sure to call initializers during startup (`.init` / `.init_array`), so it doesn't sound so bad. But here, I'm not sure if it will help much. Do we have many global variables that are not just pointers or integers?

---


<!-- Sent from Reviewable.io -->

2021-11-25 11:36 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpLsEkR23keylZUhVb_:b-xj29nt) (no related file):*
Ok, we can try a hacky solution first and see if it helps with anything.

> Do we have many global variables that are not just pointers or integers?

Well, yes. They have the prefix `g_`, and we have quite a few global vars which are structs.

---


<!-- Sent from Reviewable.io -->

2021-11-26 15:32 UTC, boryspoplawski requested changes
> Reviewed 8 of 23 files at r1, 8 of 9 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpRP2ym3bMt2AQmD9AX:b-4isidz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, we can try a hacky solution first and see if it helps with anything.

> Do we have many global variables that are not just pointers or integers?

Well, yes. They have the prefix `g_`, and we have quite a few global vars which are structs.
</blockquote></details>

I'm not sure if I understood correctly what you are talking about, but: we don't call initializers from `.init_array` - we do that manually in `shim_init`.

---
___
*[common/include/asan.h, line 70 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRR5w48NXhq0Bn0svT:-MpRR5w48NXhq0Bn0svU:b-73sw09) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L70)):*
> ```objc
>  * - Make sure code instrumented by AddressSanitizer runs *only* on stacks controlled by Gramine. If
>  *   code needs to run on user's stack (e.g. the top-level vDSO functions), it should all be
>  *   annotated with `__attribute_no_sanitize_address` or written in assembly.
> ```

1. Do we compile vdso with asan? I don't think we should ...
2. What code is run on user's stack? There should be no such place. VDSO is small exception, but it's kind of no part of Gramine (it's just delivered to the app by Gramine, but it's kind of part of the user app, like our patched glibc, etc)
___
*[common/include/asan.h, line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRYFDi2jtFSq7-jg7d:-MpRYFDjBaOLOObh0YrV:bq97kut) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L81)):*
> ```objc
>  *
>  *   This is necessary only if the jump is from the middle of a call stack. If all C functions have
>  *   returned, and the jump is from a top-level assembly wrapper, there's no need for cleanup.
> ```

I do not understand this paragraph. Do you mean that if there is no `noreturn` function and everything "just returns" to some top-level assembly wrapper (another issue: what exactly is this wrapper?) we don't need to unpoison? Actually why we don't need to?
___
*[common/include/asan.h, line 228 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRfe292Lk-bInd-1po:-MpRfe292Lk-bInd-1pp:bsfdwyt) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L228)):*
> ```objc
> 
> /* Unpoison the stack area from `top` to `bottom`. Do nothing if `top` is zero. */
> void __asan_allocas_unpoison(uintptr_t top, uintptr_t bottom);
> ```

Could we use `start` and `end`? `top` and `bottom` might be confusing
___
*[common/src/asan.c, line 316 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAyeO6BI-kuHtIuxkD:-MpRctPy3GT_B4evxyNM:b-iev2bt) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L316)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, got it.
</blockquote></details>

Could you add a comment about this? It wasn't clear to me as well.
___
*[common/src/asan.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbbQT6omaw3tdLJb5:-MpRbbQT6omaw3tdLJb6:b-7didvw) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L56)):*
> ```C
> void asan_unpoison_current_stack(uintptr_t addr, size_t size) {
>     uintptr_t frame = (uintptr_t)__builtin_frame_address(0);
>     if (!(addr <= frame && frame < addr + size)) {
> ```

I don't think this `frame` is well defined and I can imagine a situation where `frame == addr + size` is valid.
Idk what to do with this...
___
*[common/src/asan.c, line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbJ4x5-wmjbVu7gBV:-MpRbJ4y3VelfWCOshRM:b-64ddj) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L58)):*
> ```C
>     if (!(addr <= frame && frame < addr + size)) {
>         char buf[LOCATION_BUF_SIZE];
>         describe_location(RETURN_ADDR() - 1, buf, LOCATION_BUF_SIZE);
> ```

`sizeof(buf)` instead of `LOCATION_BUF_SIZE`
___
*[common/src/asan.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbwSYCVxqlvtG63EP:-MpRbwSYCVxqlvtG63EQ:byo3lb2) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L60)):*
> ```C
>         describe_location(RETURN_ADDR() - 1, buf, LOCATION_BUF_SIZE);
> 
>         log_error("asan: incorrect stack information, frame: 0x%zx, stack: 0x%zx-0x%zx",
> ```

With the new printf you can use `%#zx` :)
___
*[LibOS/shim/include/shim_internal.h, line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/240#-Mp73xz8B7quN_7ZXc1J:-MpRi7T574os-RAtTzVW:b-d6x57z) ([raw file](https://github.com/gramineproject/gramine/blob/9a0e4b1cad5dc275e004e336e005984beb2f8324/LibOS/shim/include/shim_internal.h#L57)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

FYI: despite the name, `return_from_syscall` was also called during LibOS startup, from `restore_child_context_after_clone`. This is now separated.
</blockquote></details>

But from LibOS point of view these two are the very same thing. It was called in LibOS startup, but in the child process and it was returning from a syscall (tho in a differente - new - process).
___
*[LibOS/shim/include/shim_internal.h, line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRiOxE5EflRlur4tKc:-MpRiOxE5EflRlur4tKd:b-2ojhud) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/LibOS/shim/include/shim_internal.h#L57)):*
> ```objc
>  * handling may change it).
>  *
>  * This function should be called from the LibOS stack. When AddressSanitizer is enabled, it also
> ```

What other stack could this be called from?
___
*[LibOS/shim/src/shim_init.c, line 505 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRlrMlEzSYzTowIKH5:-MpRlrMlEzSYzTowIKH6:b-b7zs61) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/LibOS/shim/src/shim_init.c#L505)):*
> ```C
>     /* At this point, the exec map has been either copied from checkpoint, or initialized in
>      * `init_loader`. */
>     execute_elf_object(/*exec_map=*/NULL, new_argp, new_auxv, /*from_libos_stack=*/false);
> ```

Wait, aren't we running on LibOS stack here?
___
*[LibOS/shim/src/shim_rtld.c, line 911 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRmFu94I0Ai2lMChT0:-MpRmFu94I0Ai2lMChT1:b-bu5lhs) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/LibOS/shim/src/shim_rtld.c#L911)):*
> ```C
> #ifdef ASAN
>     /*
>      * If we're on a PAL stack (i.e. during LibOS startup), don't bother cleaning up, we will not be
> ```

Why do we need all of these? Can't we "bother" and always unpoison it, even if it's not needed? Would be simpler...
___
*[LibOS/shim/src/vdso/arch/x86_64/vdso.c, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRn1Sb3t_J27qThOgD:-MpRn1ScCM3nMiGow_n7:bizg33s) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/LibOS/shim/src/vdso/arch/x86_64/vdso.c#L23)):*
> ```C
>     __typeof__ [...]

2021-11-27 11:29 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 12 of 26 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/240#-MpCQ4FE7wbANtz24FOD:-MpW5HAG5iLxZv0rOG5b:bq4oaxk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure if I understood correctly what you are talking about, but: we don't call initializers from `.init_array` - we do that manually in `shim_init`.
</blockquote></details>

That's right, we don't[1], and we don't even have any `.init_array` sections. But AddressSanitizer generates these: for every module that has global variables, it creates a module initializer function that calls `__asan_register_globals`, and puts these functions in the `.init_array` section. My solution is to manually call them as part of initialization.

(I have a branch with globals sanitization ready, will post PR after this - unfortunately it didn't find any new bugs. But I found out that globals sanitization also handles string literals, so I think it's worth keeping).

[1] With the exception of URTS, which is linked against Glibc, and Glibc startup code calls them.

---
___
*[common/include/asan.h, line 70 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRR5w48NXhq0Bn0svT:-MpViULL2hgSa5ILmqhr:b-te9gxn) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. Do we compile vdso with asan? I don't think we should ...
2. What code is run on user's stack? There should be no such place. VDSO is small exception, but it's kind of no part of Gramine (it's just delivered to the app by Gramine, but it's kind of part of the user app, like our patched glibc, etc)
</blockquote></details>

1. Good point. We already disable AddressSanitizer.
2. I agree there should be no such place, but until this PR, that wasn't the case (see the other discussion under this line). I reworded this comment to imply that this is not a *new* rule, but I still want to keep this comment because it's an important assumption.
___
*[common/include/asan.h, line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRYFDi2jtFSq7-jg7d:-MpVjMid4V574ZpJvN-q:b8hf138) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand this paragraph. Do you mean that if there is no `noreturn` function and everything "just returns" to some top-level assembly wrapper (another issue: what exactly is this wrapper?) we don't need to unpoison? Actually why we don't need to?
</blockquote></details>

That's exactly right. It's because ASan-instrumented functions poison parts of stack on entry/allocation, and unpoison these parts on return. So if all such functions return, the stack is cleaned up. I added that explanation here.

(AddressSanitizer also has a "use-after-return" detection mode, but that's out of scope for this branch, and it works by moving allocations out of stack).
___
*[common/include/asan.h, line 228 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRfe292Lk-bInd-1po:-MpVsfXa-K_pervUWBSq:bcvjgzp) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L228)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we use `start` and `end`? `top` and `bottom` might be confusing
</blockquote></details>

Good idea. Done.
___
*[common/src/asan.c, line 316 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAyeO6BI-kuHtIuxkD:-MpW-K1bCExcr_TkC6K5:blm9ij) ([raw file](https://github.com/gramineproject/gramine/blob/4f03217115df0620262b2a0dbe97d7c74b467874/common/src/asan.c#L316)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add a comment about this? It wasn't clear to me as well.
</blockquote></details>

I tried writing a comment, but it ended up having a few lines, so I decided there's no sense in keeping this hack "for simplicity".

Instead, I created a helper function (`asan_poison_right_redzone`), and added a comment to this function explaining why it exists.

(The same pattern, poisoning an object with right redzone, will be necessary for poisoning globals).
___
*[common/src/asan.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbbQT6omaw3tdLJb5:-MpVkYY3-MNvvzVIFW_8:b-3honnl) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think this `frame` is well defined and I can imagine a situation where `frame == addr + size` is valid.
Idk what to do with this...
</blockquote></details>

Under x86-64, gcc and clang seem to return RBP (and using this builtin this forces using RBP for frame pointer in the function, even with `-fomit-frame-pointer`).

The AdressSanitizer library takes an address of a local variable instead (`int i; frame = &i;`), do you think that's better?
___
*[common/src/asan.c, line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbJ4x5-wmjbVu7gBV:-MpVsvQN-GygCtSLHZbt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`sizeof(buf)` instead of `LOCATION_BUF_SIZE`
</blockquote></details>

Done.
___
*[common/src/asan.c, line 60 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbwSYCVxqlvtG63EP:-MpVtPid3MRrbQx2OaP0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

With the new printf you can use `%#zx` :)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 57 at r1](https://reviewable.io/reviews/gramineproject/gramine/240#-Mp73xz8B7quN_7ZXc1J:-MpVl3gL0w7VGe0yOf8t:b18d1g3) ([raw file](https://github.com/gramineproject/gramine/blob/9a0e4b1cad5dc275e004e336e005984beb2f8324/LibOS/shim/include/shim_internal.h#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But from LibOS point of view these two are the very same thing. It was called in LibOS startup, but in the child process and it was returning from a syscall (tho in a differente - new - process).
</blockquote></details>

OK.

As below, I made this function unconditionally unpoison the LibOS stack, and call it in `restore_child_context_after_clone` as well.

I still want to split it into C and assembly part - the ASan code is (at least in theory) platform-independent.
___
*[LibOS/shim/include/shim_internal.h, line 57 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRiOxE5EflRlur4tKc:-MpVkwSu0LHTnAYso_Z7:b-w4jjf1) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/LibOS/shim/include/shim_internal.h#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What other stack could this be called from?
</blockquote></details>

The PAL stack. `sh [...]

2021-11-28 18:02 UTC, boryspoplawski requested changes
> Reviewed 1 of 23 files at r1, 1 of 9 files at r3, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/asan.h, line 70 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRR5w48NXhq0Bn0svT:-MpbAMDQDTTkThCMZBYs:b-kckpv3) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L70)):*
If it wasn't the case then it was a bug.

>  except for vDSO top-level functions (compiled without ASan)

This is not an exception - functions in vdso are not run as/inside Gramine. They are called from user app.

> syscall entry code (written in assembly).

The entry code is not run on user stack - in fact it's not run on any stack at all (you can have `rsp = invalid_pointer` and it must still work).

I guess my general point is: make sure no Gramine code runs on user stack, but ASAN is not the true reason (though it requires such state of affairs).
___
*[common/include/asan.h, line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRYFDi2jtFSq7-jg7d:-MpbBmaP8ijsGx5hF_-H:bb0hd1q) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L81)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's exactly right. It's because ASan-instrumented functions poison parts of stack on entry/allocation, and unpoison these parts on return. So if all such functions return, the stack is cleaned up. I added that explanation here.

(AddressSanitizer also has a "use-after-return" detection mode, but that's out of scope for this branch, and it works by moving allocations out of stack).
</blockquote></details>

Can't we unconditionally unpoison stack on freeing (thread exit)? I don't understand why we need to bother about these edge cases
___
*[common/src/asan.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbbQT6omaw3tdLJb5:-MpbCQYLB_Jo0P5hflJd:b-4powi) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Under x86-64, gcc and clang seem to return RBP (and using this builtin this forces using RBP for frame pointer in the function, even with `-fomit-frame-pointer`).

The AdressSanitizer library takes an address of a local variable instead (`int i; frame = &i;`), do you think that's better?
</blockquote></details>

My point is I see no reason for such situation to be impossible:
```
asan_unpoison_current_stack local variables
saved rbp
return address
-----------------
f1 local variables
f1 saved rbp
f1 return address
-----------------
end of stack   <- f1 frame ptr
```
Imagine `noreturn void f1(void)`. Now it's a `noreturn` function, so it does not need to save return address and frame ptr, if it's also simple enough that it doesn't need to store local variables (e.g. they all fit in registers), then it's frame can be in fact empty. Then it could happen that `f1 frame ptr` == `asan_unpoison_current_stack frame ptr` == `end of stack` == `addr + size`.

Since changing this to `frame <= addr + size` probably isn't correct solution, if think taking the address of a local variable is a better idea, though I don't want to dig on how much of a UB is that (hopefully it's not).
___
*[common/src/asan.c, line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbFYT43QVTg0Eisf1p:-MpbFYT43QVTg0Eisf1q:bkah8ts) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L47)):*
> ```C
> static void asan_poison_right_redzone(uintptr_t addr, size_t size, size_t size_with_redzone,
>                                       uint8_t value) {
>     assert((addr & ASAN_SHADOW_MASK) == 0);
> ```

Hm, why did you change it from the simple implementation of poison(size_with_redzone) + unpoison(size)? Is it because it won't work for later usecases (globals)?
___
*[common/src/asan.c, line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbJIX5AJ7g7SBMy4S9:-MpbIZVm9Sx6qK5ECWiO:b-biyn3m) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L54)):*
> ```C
>     uintptr_t left_part_size = (addr + size) & ASAN_SHADOW_MASK;
>     if (left_part_size) {
>         *shadow_ptr = left_part_size;
> ```

This is a hard requirement of ASAN that `ASAN_SHADOW_MASK < 0x100`, right?
___
*[common/src/asan.c, line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbLV93-99glmiObeix:-MpbKP0b8W0xHybX1x4f:b-69vuh1) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L57)):*
> ```C
>         shadow_ptr++;
>     }
>     uint8_t shadow_size = (size_with_redzone - size) >> ASAN_SHADOW_SHIFT;
> ```

Why is this `uint8_t`???


<!-- Sent from Reviewable.io -->

2021-11-29 09:08 UTC, dimakuv approved these changes
> Reviewed 11 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-11-29 09:46 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 24 of 26 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[common/include/asan.h, line 70 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRR5w48NXhq0Bn0svT:-MpesHM55vE7GHjcMZgm:be0ino5) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If it wasn't the case then it was a bug.

>  except for vDSO top-level functions (compiled without ASan)

This is not an exception - functions in vdso are not run as/inside Gramine. They are called from user app.

> syscall entry code (written in assembly).

The entry code is not run on user stack - in fact it's not run on any stack at all (you can have `rsp = invalid_pointer` and it must still work).

I guess my general point is: make sure no Gramine code runs on user stack, but ASAN is not the true reason (though it requires such state of affairs).
</blockquote></details>

OK. I rephrased this as "we rely on the fact that..." to emphasize that this is not something introduced by ASan.
___
*[common/include/asan.h, line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRYFDi2jtFSq7-jg7d:-MpespcEAjfZXRhqy-wz:b-tvx0b6) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can't we unconditionally unpoison stack on freeing (thread exit)? I don't understand why we need to bother about these edge cases
</blockquote></details>

But this paragraph is not about thread exit. It's about a case where we leave a stack without exiting the thread, e.g. return from syscall, return from signal handler, jump to ELF entry address. In all these cases, nothing is freed, and we will start the execution from the beginning of this stack later.
___
*[common/src/asan.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbbQT6omaw3tdLJb5:-MpexCrmE1pHQ4VaPFs3:b-2ge89z) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

My point is I see no reason for such situation to be impossible:
```
asan_unpoison_current_stack local variables
saved rbp
return address
-----------------
f1 local variables
f1 saved rbp
f1 return address
-----------------
end of stack   <- f1 frame ptr
```
Imagine `noreturn void f1(void)`. Now it's a `noreturn` function, so it does not need to save return address and frame ptr, if it's also simple enough that it doesn't need to store local variables (e.g. they all fit in registers), then it's frame can be in fact empty. Then it could happen that `f1 frame ptr` == `asan_unpoison_current_stack frame ptr` == `end of stack` == `addr + size`.

Since changing this to `frame <= addr + size` probably isn't correct solution, if think taking the address of a local variable is a better idea, though I don't want to dig on how much of a UB is that (hopefully it's not).
</blockquote></details>

Wait. As far as I can tell, `__builtin_frame_address(0)` in `asan_unpoison_current_stack` returns the address *before* its return address ("normally the address of the first word pushed on to the stack by the function" according to GCC docs; or, empirically, the RSP value just after pushing previous RBP). So wouldn't it look like this?

```
asan_unpoison_current_stack local variables
saved rbp <--  __builtin_frame_address(0)
return address
-----------------
f1 local variables
f1 saved rbp
f1 return address
-----------------
end of stack 
```

Anyway, I changed this to address of a local variable, should be less ambiguous.
___
*[common/src/asan.c, line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbFYT43QVTg0Eisf1p:-Mpeu8Hi8h1N3GQ7Hs0v:b-2bx2lo) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L47)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, why did you change it from the simple implementation of poison(size_with_redzone) + unpoison(size)? Is it because it won't work for later usecases (globals)?
</blockquote></details>

1. The "simple" implementation wasn't self-explanatory without a lengthy comment (as pointed by you and @dimakuv), i.e. it wasn't obvious why we can't just poison `addr + size .. addr + size_with_redzone`.
2. It was a hack, and not the "obviously right" thing: it did the unnecessary work of poisoning and then un-poisoning the object.

   While I doubt it matters much for performance, it could have masked some errors: if the memory *inside* the object is poisoned before this function at the moment, something went really wrong, and we don't want to silently unpoison it.
___
*[common/src/asan.c, line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbJIX5AJ7g7SBMy4S9:-MpeuI0m3QMubveS3zlU:b6kfn6x) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a hard requirement of ASAN that `ASAN_SHADOW_MASK < 0x100`, right?
</blockquote></details>

Yes. ASan uses positive values (0 to 127) to say that memory is partially accessible, so one shadow byte cannot represent more than 128 bytes of memory.
___
*[common/src/asan.c, line 57 at r5](https://reviewable.io/reviews/gramineproject/gramine/240#-MpbLV93-99glmiObeix:-MpewFUbAKcNViAdICl5:bggc51e) ([raw file](https://github.com/gramineproject/gramine/blob/7e1985672c81c209245982b28706051e5fd83cc5/common/src/asan.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this `uint8_t`???
</blockquote></details>

Oops! Fixed, thanks. And the one above should also be `size_t`, not `uintptr_t`.


<!-- Sent from Reviewable.io -->

2021-11-29 10:19 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/asan.h, line 81 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRYFDi2jtFSq7-jg7d:-Mpf8Bhw1N9r2t2pxaT_:buh93h9) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/include/asan.h#L81)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

But this paragraph is not about thread exit. It's about a case where we leave a stack without exiting the thread, e.g. return from syscall, return from signal handler, jump to ELF entry address. In all these cases, nothing is freed, and we will start the execution from the beginning of this stack later.
</blockquote></details>

Oh, got it.
___
*[common/include/asan.h, line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/240#-Mpf8Kjc7MQrDZy2ZotH:-Mpf8Kjd7cyvBiSU0C8m:b-u7204w) ([raw file](https://github.com/gramineproject/gramine/blob/dacb2b781c11ca6264e03b5d4fbfe19b68ba3ebc/common/include/asan.h#L85)):*
> ```objc
>  *
>  * Note that we rely on the fact that no Gramine code runs on the user stack (except for vDSO, which
>  * we make sure to compile without ASan).
> ```

Again, I want to stress out that VDSO is not part of Gramine (hence it cannot be an exception), at least not more than the patched glibc. We build it together for simplicity, but in theory it should be a separate project with it's own build configuration, compiler flags etc.
___
*[common/src/asan.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/240#-MpRbbQT6omaw3tdLJb5:-MpfBg8a79D_NzFL0zxz:bs9ia55) ([raw file](https://github.com/gramineproject/gramine/blob/8a353cccf65d18a4d03a08163847b1295f27e402/common/src/asan.c#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Wait. As far as I can tell, `__builtin_frame_address(0)` in `asan_unpoison_current_stack` returns the address *before* its return address ("normally the address of the first word pushed on to the stack by the function" according to GCC docs; or, empirically, the RSP value just after pushing previous RBP). So wouldn't it look like this?

```
asan_unpoison_current_stack local variables
saved rbp <--  __builtin_frame_address(0)
return address
-----------------
f1 local variables
f1 saved rbp
f1 return address
-----------------
end of stack 
```

Anyway, I changed this to address of a local variable, should be less ambiguous.
</blockquote></details>

It's just a convention and internal detail of the compiler, what it considers a frame start and what offset from it it puts into rbp.
It was rather a theoretical problem, than practical one, but I like the current solution better.


<!-- Sent from Reviewable.io -->

2021-11-29 10:48 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: 25 of 26 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[common/include/asan.h, line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/240#-Mpf8Kjc7MQrDZy2ZotH:-MpfGiUbCevaiwEdCjLS:bkhreha) ([raw file](https://github.com/gramineproject/gramine/blob/dacb2b781c11ca6264e03b5d4fbfe19b68ba3ebc/common/include/asan.h#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Again, I want to stress out that VDSO is not part of Gramine (hence it cannot be an exception), at least not more than the patched glibc. We build it together for simplicity, but in theory it should be a separate project with it's own build configuration, compiler flags etc.
</blockquote></details>

Is your point that we should not mention vDSO at all, or that I should reword this (and if so, how)?

I'll remove the mention of vDSO for now, there's a check for ASan in there anyway.


<!-- Sent from Reviewable.io -->

2021-11-29 11:07 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/asan.h, line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/240#-Mpf8Kjc7MQrDZy2ZotH:-MpfN8r1AbeCHdtLNrcY:b-u87yip) ([raw file](https://github.com/gramineproject/gramine/blob/dacb2b781c11ca6264e03b5d4fbfe19b68ba3ebc/common/include/asan.h#L85)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is your point that we should not mention vDSO at all, or that I should reword this (and if so, how)?

I'll remove the mention of vDSO for now, there's a check for ASan in there anyway.
</blockquote></details>

Yes, I wanted not to mention it at all


<!-- Sent from Reviewable.io -->

2021-11-29 14:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/240#-MpAq28c4zYN2qJQ86zo):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll update on rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 14:05 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-29 14:06 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/240)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-29 15:07 UTC, merged