[Docs] Advise to install from repo
gramineproject/gramine pull request #244
Opened 2021-11-24 12:41 UTC by woju

## Description of the changes 

Also removed markdown support, we don't use it.

## How to test this PR? 

test the install instructions (if you haven't already)

2021-11-25 10:01 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVHaUD7RBZ1-esnpf:-MpLVHaUD7RBZ1-esnpg:b6tzmdy) (no related file):*
@woju Docs pipeline failed.

---
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpLXMuGDFJda42CC89_:b-z2rpoy) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
> ```reStructuredText
> #. Install Gramine::
> 
>       sudo apt-get install gramine
> ```

Is this package built with `-Ddcap=enabled`? Otherwise it won't work on Azure.

Btw, this may be a problem for normal environments as well. Most users would expect the installed Gramine package to support both EPID and DCAP, but Gramine default build (without `Ddcap`) only supports EPID.
___
*[Documentation/index.rst, line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVeKOD6poAfJ9LHxY:-MpLVeKPDWfo_gwQQlcg:b-3ntjrr) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/index.rst#L64)):*
> ```reStructuredText
> 
>    quickstart
>    building
> ```

You must remove this
___
*[Documentation/quickstart.rst, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVvx39B6CaVf41gxk:-MpLVvx39B6CaVf41gxl:b-l0gy6h) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L22)):*
> ```reStructuredText
> We supply a tool :doc:`manpages/is-sgx-available`, which you can use to check
> your hardware and system. It's installed together with the respective gramine
> package (see below).
> ```

Can Gramine be installed on a system that doesn't have SGX? Like, Gramine depends on some SGX SDK/PSW packages, and I'm not sure those packages can be correctly installed on a non-SGX-enabled system. Did anyone check this?

If Gramine can't be installed on a non-SGX system, then this paragraph doesn't make sense.
___
*[Documentation/quickstart.rst, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWIVG5VhB_xVp1jVT:-MpLWIVG5VhB_xVp1jVU:b-1t6x7e) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L40)):*
> ```reStructuredText
> 
>    sudo curl -fsSLo /etc/yum.repos.d/gramine.repo https://packages.gramineproject.io/rpm/gramine.repo
>    sudo dnf install gramine          # only the default, distro-provided kernel is supported
> ```

I don't understand the comment. So this corresponds to Linux 5.11+ ?
___
*[Documentation/quickstart.rst, line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLW_n_97IkZsMCSsvE:-MpLW_n_97IkZsMCSsvF:b-h2ca1d) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L54)):*
> ```reStructuredText
> ::
> 
>    git clone https://github.com/gramineproject/gramine.git
> ```

Let's add `--depth 1`
___
*[Documentation/quickstart.rst, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWi8S7HAIfXLXBjdf:-MpLWi8S7HAIfXLXBjdg:b-x58m7y) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L55)):*
> ```reStructuredText
> 
>    git clone https://github.com/gramineproject/gramine.git
>    pushd gramine/CI-Examples/helloworld >/dev/null
> ```

Why dev null? Or even why pushd (not normal cd)?
___
*[Documentation/quickstart.rst, line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWrgS-vzSmg9_iJtu:-MpLWrgS-vzSmg9_iJtv:b2z7ui6) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L68)):*
> ```reStructuredText
> 
> For more complex examples, see :file:`CI-Examples` directory.
> ```

Please add a new section title like `Other example applications`


<!-- Sent from Reviewable.io -->

2021-11-25 18:25 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: 6 of 8 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVHaUD7RBZ1-esnpf:-MpMxmNsBB0OgVK19MlQ:bm1jqa2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Docs pipeline failed.
</blockquote></details>

Yes, for `/building` as you noted below.

---
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpMxpdkDysA3aOAvsUm:b-fz7uvg) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this package built with `-Ddcap=enabled`? Otherwise it won't work on Azure.

Btw, this may be a problem for normal environments as well. Most users would expect the installed Gramine package to support both EPID and DCAP, but Gramine default build (without `Ddcap`) only supports EPID.
</blockquote></details>

No, currently they're not, but they could be. I'll revert `cloud-deployment for now.
___
*[Documentation/index.rst, line 64 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVeKOD6poAfJ9LHxY:-MpNIBTtAF46YZ7bpOsb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/index.rst#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You must remove this
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVvx39B6CaVf41gxk:-MpNIGrY1J84K7Wx1VMu:bnczh3m) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L22)):*
> Can Gramine be installed on a system that doesn't have SGX?

Yes, it can, and you can run `gramine-direct` just fine. `gramine-sgx` will fail for some reason, possibly `ENOENT` on `/dev/sgx*`. We don't specify those various dependencies for this reason. Well, I could split the packages to `gramine-direct`, `gramine-sgx{,-oot,-dcap}` and probably `gramine-common` if you wanted to have those dependencies, but in this case we would have to build, package and distribute them ourselves (otherwise installing gramine from our repo would fail for missing deps). We don't have infrastructure for this, the current one is ad-hoc for a single package.
___
*[Documentation/quickstart.rst, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWIVG5VhB_xVp1jVT:-MpNJE8j0eKw_NwhA3QP:b-37wdaw) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the comment. So this corresponds to Linux 5.11+ ?
</blockquote></details>

It's this kernel that says `4.18`, but has bucketloads of patches backported, including in-kernel sgx driver, which should be only in 5.11. The exact kernel I was talking about in https://github.com/gramineproject/gramine/commit/2f5995039ddce984967630d35f717122fc923789 commit message.

The apparent version is why the `#if` was wrong in this commit.
___
*[Documentation/quickstart.rst, line 54 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLW_n_97IkZsMCSsvE:-MpNKI2M9utLEcW2k_wI:b-80tlqk) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's add `--depth 1`
</blockquote></details>

Sure.
___
*[Documentation/quickstart.rst, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWi8S7HAIfXLXBjdf:-MpNKEkE3DA6OLGVRCpn:botu9jn) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why dev null? Or even why pushd (not normal cd)?
</blockquote></details>

This was from previous version, which had repeated `pushd`/`popd`. `>/dev/null` is needed, because each time you get the directory stack printed to stdout.
___
*[Documentation/quickstart.rst, line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWrgS-vzSmg9_iJtu:-MpNKocAEWmMwP-ZUz95:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a new section title like `Other example applications`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-25 18:27 UTC, woju commented
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpNLPanDim452Df5nAA:b40adif) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, currently they're not, but they could be. I'll revert `cloud-deployment for now.
</blockquote></details>

Hmm, but the previous instructions don't specify `-Ddcap=enabled`. Is this a bug in existing version?


<!-- Sent from Reviewable.io -->

2021-11-26 08:07 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVHaUD7RBZ1-esnpf:-MpQHIVx86qQmcBvrRvi:b-fp29vd) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, for `/building` as you noted below.
</blockquote></details>

Still failing.

---
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpQFpjvAf8QMencpD2b:b-udauab) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Hmm, but the previous instructions don't specify `-Ddcap=enabled`. Is this a bug in existing version?
</blockquote></details>

Previous instructions were buggy. Well, not "buggy" but misleading -- if you want to deploy Gramine in the cloud, you almost certainly want to use Intel SGX and SGX attestation. And in the cloud, you don't use EPID attestation these days, you always use DCAP attestation.

So even though you can run a simple HelloWorld SGX application, any *real* SGX workload will fail because Gramine is built/installed without DCAP-attestation support. The users will be perplexed by this; once they realize that this package doesn't have DCAP attestation, they'll curse us and will have to revert to the old-style "build from GitHub" way.

This is pretty bad actually... Even in QuickStart, we should advise a "feature complete" Gramine package. Since the package comes without DCAP attestation, we doom ourselves to unhappy users (who can successfully run local workloads, but as soon as they want to do SGX attestation, Gramine fails). We definitely need to revisit our packaging. @mkow @boryspoplawski @pwmarcz What do we do?
___
*[Documentation/quickstart.rst, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVvx39B6CaVf41gxk:-MpQF3yZ00CQz5u2zy3H:bed6txn) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L22)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Can Gramine be installed on a system that doesn't have SGX?

Yes, it can, and you can run `gramine-direct` just fine. `gramine-sgx` will fail for some reason, possibly `ENOENT` on `/dev/sgx*`. We don't specify those various dependencies for this reason. Well, I could split the packages to `gramine-direct`, `gramine-sgx{,-oot,-dcap}` and probably `gramine-common` if you wanted to have those dependencies, but in this case we would have to build, package and distribute them ourselves (otherwise installing gramine from our repo would fail for missing deps). We don't have infrastructure for this, the current one is ad-hoc for a single package.
</blockquote></details>

Ok. I'm fine with the current single package. Just wanted to be sure our description in the documentation makes sense.
___
*[Documentation/quickstart.rst, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLWIVG5VhB_xVp1jVT:-MpQFIzRDng4qhGiUBVa:b-edqdki) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/quickstart.rst#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's this kernel that says `4.18`, but has bucketloads of patches backported, including in-kernel sgx driver, which should be only in 5.11. The exact kernel I was talking about in https://github.com/gramineproject/gramine/commit/2f5995039ddce984967630d35f717122fc923789 commit message.

The apparent version is why the `#if` was wrong in this commit.
</blockquote></details>

OK, thanks, now I remember.
___
*[Documentation/quickstart.rst, line 55 at r2](https://reviewable.io/reviews/gramineproject/gramine/244#-MpQFU6M43z_v6-5WM4K:-MpQFU6M43z_v6-5WM4L:b382mg) ([raw file](https://github.com/gramineproject/gramine/blob/694880ca5b82d4926050b124003d77b80b8e1f69/Documentation/quickstart.rst#L55)):*
> ```reStructuredText
> 
>    git clone --depth 1 https://github.com/gramineproject/gramine.git
>    cd gramine/CI-Examples/helloworld >/dev/null
> ```

You still have `>/dev/null`


<!-- Sent from Reviewable.io -->

2021-11-26 13:11 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: 5 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLVHaUD7RBZ1-esnpf:-MpRM7UM9Vx-bCb9te-L:bbz7atn) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still failing.
</blockquote></details>

There were actually more references to this page. All fixed.

---
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpRMIUq6gX_UA02aCEe:bb01fvf) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Previous instructions were buggy. Well, not "buggy" but misleading -- if you want to deploy Gramine in the cloud, you almost certainly want to use Intel SGX and SGX attestation. And in the cloud, you don't use EPID attestation these days, you always use DCAP attestation.

So even though you can run a simple HelloWorld SGX application, any *real* SGX workload will fail because Gramine is built/installed without DCAP-attestation support. The users will be perplexed by this; once they realize that this package doesn't have DCAP attestation, they'll curse us and will have to revert to the old-style "build from GitHub" way.

This is pretty bad actually... Even in QuickStart, we should advise a "feature complete" Gramine package. Since the package comes without DCAP attestation, we doom ourselves to unhappy users (who can successfully run local workloads, but as soon as they want to do SGX attestation, Gramine fails). We definitely need to revisit our packaging. @mkow @boryspoplawski @pwmarcz What do we do?
</blockquote></details>

For now, I've reverted this page and added `-Ddcap=enabled` to the instruction. The package needs fixing, and that's actually on me, but this out of scope for this PR.
___
*[Documentation/quickstart.rst, line 55 at r2](https://reviewable.io/reviews/gramineproject/gramine/244#-MpQFU6M43z_v6-5WM4K:-MpRMt7Y2Es9-Vh2WrcP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/694880ca5b82d4926050b124003d77b80b8e1f69/Documentation/quickstart.rst#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You still have `>/dev/null`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-26 14:28 UTC, dimakuv submitted a review, later dismissed
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[-- commits, line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRdMYKDxeodiYPFiHx):*
I don't see a reason to have two links (they point to more or less the same). So I would remove the reviewable.io link from here.
___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-MpRba2oE-kVdoriRORY:bghf2l1) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
> ```reStructuredText
> the build procedures were changed. See `Building instructions
> <https://gramine.readthedocs.io/en/latest/devel/building.html>`__ for an
> up-to-date build tutorial.
> ```

Not blocking, but do we think this warning is still relevant?
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpRdAPZ9haqiHha04aF:b1z3zbe) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For now, I've reverted this page and added `-Ddcap=enabled` to the instruction. The package needs fixing, and that's actually on me, but this out of scope for this PR.
</blockquote></details>

OK, sounds good.


<!-- Sent from Reviewable.io -->

2021-11-26 15:04 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRdMYKDxeodiYPFiHx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see a reason to have two links (they point to more or less the same). So I would remove the reviewable.io link from here.
</blockquote></details>

Done and squashed and rebased.
___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-MpRjorn9f1ctCDKm2TJ:b-9ttz4n) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not blocking, but do we think this warning is still relevant?
</blockquote></details>

I don't have a strong opinion, but we can remove this now, if no-one objects, since we document installation from packages so the exact buildchain is less relevant.


<!-- Sent from Reviewable.io -->

2021-11-29 07:34 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski, @mkow, @monavij, and @pwmarcz)

___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-MpebBmWBsNcptFdPfGg:b-wb335t) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't have a strong opinion, but we can remove this now, if no-one objects, since we document installation from packages so the exact buildchain is less relevant.
</blockquote></details>

@monavij @boryspoplawski @mkow @pwmarcz ?


<!-- Sent from Reviewable.io -->

2021-11-29 08:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski, @mkow, and @monavij)

___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-MpeqG2zAA6ZTuLssLnZ:b-pnlqdy) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@monavij @boryspoplawski @mkow @pwmarcz ?
</blockquote></details>

This is a README for the Git repo, so build instructions are still relevant. But there's already a link to them below, and we've been using Meson for some time now, so I think we can remove this warning.


<!-- Sent from Reviewable.io -->

2021-11-29 12:05 UTC, mkow requested changes
> Reviewed 4 of 8 files at r1, 1 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @monavij)

___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-MpfXN5gA9sG6CfXq2d2:b-5yp84s) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a README for the Git repo, so build instructions are still relevant. But there's already a link to them below, and we've been using Meson for some time now, so I think we can remove this warning.
</blockquote></details>

+1 to removing it.
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpfXt_tBjj9M2sRWLH6:bykpu90) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
> The package needs fixing

Hmm, I thought we had 2 different packages, one for DCAP and for for EPID?


<!-- Sent from Reviewable.io -->

2021-11-29 14:29 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: 11 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @monavij)

___
*[README.rst, line 21 at r3](https://reviewable.io/reviews/gramineproject/gramine/244#-MpRba2oE-kVdoriRORX:-Mpg56SQ5XY6qIxNO4DD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c20093b5d1d35b6cecd3a86b951121b3ac1f48d1/README.rst#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to removing it.
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-Mpg1pMY5HIcKb4tVqUE:b-bpekwu) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The package needs fixing

Hmm, I thought we had 2 different packages, one for DCAP and for for EPID?
</blockquote></details>

We have different packages for *driver* (3 of them, actually, `-Dsgx_driver={upstream,dcap1.10,oot}`). This is about `-Ddcap`.


<!-- Sent from Reviewable.io -->

2021-11-29 17:15 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpgedvZ074wmt0OmYAZ:b23u7i7) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We have different packages for *driver* (3 of them, actually, `-Dsgx_driver={upstream,dcap1.10,oot}`). This is about `-Ddcap`.
</blockquote></details>

Oh, I didn't notice that this is an unrelated option (I mean, I knew this some time ago, but it's unintuitive enough that I forgot it). This seems super confusing...

@dimakuv How does this work, would it be possible to support both EPID and DCAP attestation in runtime? Does this need to be a compile-time choice?


<!-- Sent from Reviewable.io -->

2021-11-29 17:57 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpgpM2b6XobmBLxuN51:b-2ji95n) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, I didn't notice that this is an unrelated option (I mean, I knew this some time ago, but it's unintuitive enough that I forgot it). This seems super confusing...

@dimakuv How does this work, would it be possible to support both EPID and DCAP attestation in runtime? Does this need to be a compile-time choice?
</blockquote></details>

It's not mutually exclusive, just more `.so`s to compile: https://github.com/gramineproject/gramine/blob/a498b73657bf6978d7ee9df208eb018f60919e8f/Pal/src/host/Linux-SGX/tools/ra-tls/meson.build#L85. But this needs to be decided in compile time because of this dependency: https://github.com/gramineproject/gramine/blob/a498b73657bf6978d7ee9df208eb018f60919e8f/meson.build#L251-L253


<!-- Sent from Reviewable.io -->

2021-11-30 10:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpkGq0xBiE-PnOvP906:blrifee) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
> @dimakuv How does this work, would it be possible to support both EPID and DCAP attestation in runtime?

As Woju already described, yes, it is possible to support both EPID and DCAP attestation in runtime.

> Does this need to be a compile-time choice?

For the sake of simplicity yes :) The DCAP attestation library (`libsgx_dcap_quoteverify.so`)  is a dependency of the RA-TLS DCAP library.

Some context: historically, EPID attestation was first. EPID attestation can be performed purely via the AESM daemon, which Gramine supports unconditionally. Then came DCAP attestation. DCAP attestation can *not* be performed via the AESM daemon but *only* through the shared library (I don't remember the reasons).

RA-TLS has two versions (two separate libs): EPID-based and DCAP-based. When I first implemented RA-TLS, almost everyone used EPID attestation, so it made no sense to also build DCAP-based version. So I opted to build only the EPID version -- it was not only more popular, but it also didn't require any dependencies for Gramine. And I added a switch to Makefiles to also build the DCAP version if required -- almost noone used it.

These days, it is different: almost everyone uses DCAP and I'm not sure if anyone uses EPID (well, our CI does :)). So maybe it's time to enable DCAP unconditionally, and always require the `libsgx_dcap_quoteverify.so` dependency (which is shipped as one of those SGX packages on Ubuntu and RedHat)? @woju @mkow What do you think?


<!-- Sent from Reviewable.io -->

2021-11-30 11:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-Mpkco1kC-ANpODxDvZt:bkf3zo6) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> @dimakuv How does this work, would it be possible to support both EPID and DCAP attestation in runtime?

As Woju already described, yes, it is possible to support both EPID and DCAP attestation in runtime.

> Does this need to be a compile-time choice?

For the sake of simplicity yes :) The DCAP attestation library (`libsgx_dcap_quoteverify.so`)  is a dependency of the RA-TLS DCAP library.

Some context: historically, EPID attestation was first. EPID attestation can be performed purely via the AESM daemon, which Gramine supports unconditionally. Then came DCAP attestation. DCAP attestation can *not* be performed via the AESM daemon but *only* through the shared library (I don't remember the reasons).

RA-TLS has two versions (two separate libs): EPID-based and DCAP-based. When I first implemented RA-TLS, almost everyone used EPID attestation, so it made no sense to also build DCAP-based version. So I opted to build only the EPID version -- it was not only more popular, but it also didn't require any dependencies for Gramine. And I added a switch to Makefiles to also build the DCAP version if required -- almost noone used it.

These days, it is different: almost everyone uses DCAP and I'm not sure if anyone uses EPID (well, our CI does :)). So maybe it's time to enable DCAP unconditionally, and always require the `libsgx_dcap_quoteverify.so` dependency (which is shipped as one of those SGX packages on Ubuntu and RedHat)? @woju @mkow What do you think?
</blockquote></details>

Either Intel provides a repository with this package, and not just a dump of `*.deb`s somewhere on download.01.org, or I would have to package this lib myself. I'm not comfortable just copying into our repo and signing a package built by someone else. Either way we need to have clear installation instructions, adding 1-2 repos and `apt-get install`, not "oh, btw if you need DCAP attestation, `curl | dpkg -i -` also this deb".

And just by skimming, the included build scripts are a mess and it looks like the authors didn't know what they were doing: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/82662a59d7a3102d5004faf5f232066a06f306f5/QuoteGeneration/installer/linux/deb/libsgx-dcap-quote-verify/build.sh#L120


<!-- Sent from Reviewable.io -->

2021-12-01 12:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-Mpq-Zp826orvyuAG4Uq:bitetnq) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Either Intel provides a repository with this package, and not just a dump of `*.deb`s somewhere on download.01.org, or I would have to package this lib myself. I'm not comfortable just copying into our repo and signing a package built by someone else. Either way we need to have clear installation instructions, adding 1-2 repos and `apt-get install`, not "oh, btw if you need DCAP attestation, `curl | dpkg -i -` also this deb".

And just by skimming, the included build scripts are a mess and it looks like the authors didn't know what they were doing: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/82662a59d7a3102d5004faf5f232066a06f306f5/QuoteGeneration/installer/linux/deb/libsgx-dcap-quote-verify/build.sh#L120
</blockquote></details>

As per yesterday's call, seems there is a proper repo and we can use it and ship both DCAP and EPID support by default.
Should we proceed with this PR or wait for this change?


<!-- Sent from Reviewable.io -->

2021-12-01 15:36 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/cloud-deployment.rst, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/244#-MpLXMuGDFJda42CC89Z:-MpqcnoT3kkpNjQa6S8E:b-v1hmk4) ([raw file](https://github.com/gramineproject/gramine/blob/022504a38662a5f1d4b74a0d123fb96f6d22d467/Documentation/cloud-deployment.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

As per yesterday's call, seems there is a proper repo and we can use it and ship both DCAP and EPID support by default.
Should we proceed with this PR or wait for this change?
</blockquote></details>

I think we can proceed. This PR is orthogonal to "build with DCAP attestation support by default" and our packaging. And this PR currently contains correct (as of now) instructions.


<!-- Sent from Reviewable.io -->

2021-12-02 10:21 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-02 10:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/244)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-02 13:08 UTC, merged