Optimize `sendfile`
gramineproject/gramine pull request #245
Opened 2021-11-24 19:54 UTC by pwmarcz

## Description of the changes 

I looked into why the `sendfile` LTP test is so slow, and found two things:
* the buffer size is pretty small,
* `DkEventSet` in Linux PAL is pretty inefficient and always calls `futex` (Linux-SGX PAL has a waiters count, so it should be OK)

As a result, there is a lot of small `pread64` and `pwrite64` calls, each accompanied by several `futex` calls (releasing locks).

Here's a benchmark for `sendfile09` LTP test (which uses `sendfile` to copy 1 GB ranges), with `gramine-direct`, compiled in debug mode (but release numbers are pretty similar):

| version | time |
|---|---|
| Linux (no Gramine) | 1.07 s |
| master |  2.61 s |
| `DkEventSet` optimized | 1.86 s |
| 64KB buffer | 1.31 s |
| **`DkEventSet` optimized + 64KB buffer** | **1.25 s** |

(Benchmarks performed using [hyperfine](https://github.com/sharkdp/hyperfine), it's pretty neat).

## How to test this PR? 

Please read the DkEventSet code carefully.

2021-11-24 20:05 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpIX8wZ-HWlw_oZtc3w:bi9v1sc) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
> ```C
> void _DkEventSet(PAL_HANDLE handle) {
>     __atomic_store_n(&handle->event.signaled, 1, __ATOMIC_RELEASE);
>     if (__atomic_load_n(&handle->event.waiters_cnt, __ATOMIC_ACQUIRE) > 0) {
> ```

Is this enough to ensure that if `waiters_cnt` will be written a non-zero value before our store, we will see it here? Or do I need stronger consistency guarantees.


<!-- Sent from Reviewable.io -->

2021-11-25 09:33 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/245#-MpLR7c56sulOtIwAV_P:-MpLR7c56sulOtIwAV_Q:bxom7ki) (no related file):*
Nice! The previous sub-optimal behavior of `DkEventSet` may explain some of the performance overheads we observed on some Linux-PAL workloads...

---
___
*[Pal/src/host/Linux/db_events.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpLPHkG-d95tb-6M-TC:-MpLPHkHDFLwTf_Ol1Ey:b-5vdgvp) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L28)):*
> ```C
>     init_handle_hdr(HANDLE_HDR(handle), PAL_TYPE_EVENT);
>     handle->event.auto_clear = auto_clear;
>     handle->event.waiters_cnt = 0;
> ```

Please remove this line
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLQGS04YeXWSWoX18S:byodqg4) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is this enough to ensure that if `waiters_cnt` will be written a non-zero value before our store, we will see it here? Or do I need stronger consistency guarantees.
</blockquote></details>

This looks correct to me. The signaller first sets `signaled = 1` before checking `waiters_cnt`, whereas the waiter first sets `waiters_cnt` and then checks `signaled == 1`. So `signaled = 1` will be visible to the waiter (the waiter will "sync" on `waiters_cnt`).

But @boryspoplawski is much better at this stuff.


<!-- Sent from Reviewable.io -->

2021-11-25 11:23 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/245#-MpLR7c56sulOtIwAV_P:-MpLpE8I9OBrwRj8aUfu:br5e214) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice! The previous sub-optimal behavior of `DkEventSet` may explain some of the performance overheads we observed on some Linux-PAL workloads...
</blockquote></details>

I guess we're "lucky" the sendfile performance problem was so visible.

---
___
*[Pal/src/host/Linux/db_events.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpLPHkG-d95tb-6M-TC:-MpLp9y-A1CmDvdiQDqU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this line
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLmOL98PLLEdrOTeUy:bo5iy4j) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
>This looks correct to me. The signaller first sets signaled = 1 before checking waiters_cnt, whereas the waiter first sets waiters_cnt and then checks signaled == 1

Going by what's written on [cppreference](https://en.cppreference.com/w/c/atomic/memory_order) about memory ordering, setting `signaled = 1` with RELEASE ordering only means that reads/writes _before_ it cannot be reorderd after it, not the other way around...

So I still suspect I need a `SEQ_CST` somewhere. @boryspoplawski what do you think?


<!-- Sent from Reviewable.io -->

2021-11-25 11:23 UTC, boryspoplawski requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLgaY3-2_YvrI851dv:bml1lt0) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks correct to me. The signaller first sets `signaled = 1` before checking `waiters_cnt`, whereas the waiter first sets `waiters_cnt` and then checks `signaled == 1`. So `signaled = 1` will be visible to the waiter (the waiter will "sync" on `waiters_cnt`).

But @boryspoplawski is much better at this stuff.
</blockquote></details>

There is nothing stopping both the compiler and the CPU from reordering `signaled` store with `waiters_cnd` load. We need an explicit memory barrier between them.


<!-- Sent from Reviewable.io -->

2021-11-25 11:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLqEGc5_m9U3WbOVUM:b-ryazvf) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is nothing stopping both the compiler and the CPU from reordering `signaled` store with `waiters_cnd` load. We need an explicit memory barrier between them.
</blockquote></details>

Well, but then there will probably be no need to synchronize on both of these variables.
The easiest no brainer solution is to not use atomic and just wrap these 2 accesses in a spinlock.


<!-- Sent from Reviewable.io -->

2021-11-25 11:46 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLuS-d1Pg1ESw65r9d:b-a0uobq) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, but then there will probably be no need to synchronize on both of these variables.
The easiest no brainer solution is to not use atomic and just wrap these 2 accesses in a spinlock.
</blockquote></details>

I always forget that memory orderings relate to only that particular object (variable), and do not affect other variables. So ignore me. I agree with Borys that using a spinlock sounds the easiest.


<!-- Sent from Reviewable.io -->

2021-11-25 11:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 1 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpLsocJ34BHS19U-z_K:b-siqal0) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I always forget that memory orderings relate to only that particular object (variable), and do not affect other variables. So ignore me. I agree with Borys that using a spinlock sounds the easiest.
</blockquote></details>

OK, let's do a spinlock.

I did the same benchmark, and the performance is almost the same (at least in this uncontested case).


<!-- Sent from Reviewable.io -->

2021-11-25 11:54 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-11-25 13:34 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpMH3eL7Ft_zJ6JHJGX:b-97zcmh) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, let's do a spinlock.

I did the same benchmark, and the performance is almost the same (at least in this uncontested case).
</blockquote></details>

In uncontested case performance of most locking primitives is the same :)
___
*[Pal/src/host/Linux/db_events.c, line 30 at r3](https://reviewable.io/reviews/gramineproject/gramine/245#-MpMHqi0ARm4YUS0GZo7:-MpMHaSM83HBcr6vTYqD:bp0mggq) ([raw file](https://github.com/gramineproject/gramine/blob/91c68b67ca2df5e9702e6ef01e7a8b0e917dedca/Pal/src/host/Linux/db_events.c#L30)):*
> ```C
>     handle->event.auto_clear = auto_clear;
>     handle->event.waiters_cnt = 0;
>     handle->event.signaled = init_signaled ? 1 : 0;
> ```

This still needs to be an atomic store, because we are using futex on this addr.
ditto for the whole PR


<!-- Sent from Reviewable.io -->

2021-11-25 16:01 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/245#-MpIX8wZ-HWlw_oZtc3v:-MpMniQu21SQECws6FRf:b2g9868) ([raw file](https://github.com/gramineproject/gramine/blob/de5dd1e1e4ed01612aeb9ad49902a025d7bae3c3/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In uncontested case performance of most locking primitives is the same :)
</blockquote></details>

As long as there's no extra syscall involved. I'm improving the uncontested case, after all.
___
*[Pal/src/host/Linux/db_events.c, line 30 at r3](https://reviewable.io/reviews/gramineproject/gramine/245#-MpMHqi0ARm4YUS0GZo7:-MpMoqjuCLyGPt4_UgF4:b-xbqb8q) ([raw file](https://github.com/gramineproject/gramine/blob/91c68b67ca2df5e9702e6ef01e7a8b0e917dedca/Pal/src/host/Linux/db_events.c#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This still needs to be an atomic store, because we are using futex on this addr.
ditto for the whole PR
</blockquote></details>

OK, I went back to the original code for the `signaled` field.


<!-- Sent from Reviewable.io -->

2021-11-25 16:11 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-11-26 07:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-11-26 08:08 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/245)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-26 08:43 UTC, merged