[LibOS] Fix dup2 and dup3 as per the spec
gramineproject/gramine pull request #249
Opened 2021-11-26 11:31 UTC by svenkata9

Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>

## Description of the changes 
* As per the man [page](https://man7.org/linux/man-pages/man2/dup.2.html), `dup2` must return `newfd` if `oldfd` and `newfd` have the same values. Also, handling this as per the sequence listed in the man page (after checking for the validity of `oldfd`).
* Also, as per the man [page ](https://man7.org/linux/man-pages/man2/dup.2.html)`dup3` must return error `EINVAL` if `oldfd` equals `newfd`.

Fixes #180 

## How to test this PR? 
LTP tests haven't been upgraded yet. Please follow the steps listed in #180.

2021-11-26 14:37 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[LibOS/shim/src/sys/shim_dup.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpReuLS19neH9_dqqor:-MpReuLT7pWEBCRhqlxh:bimdy90) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L45)):*
> ```C
> 
>     if (oldfd == newfd)
>         return newfd;
> ```

You should also put the `hdl` handle (decrement its reference count). This is because `hdl = get_fd_handle()` above gets this handle (increments its reference count). So we need to put the handle here to avoid memory leaks. So please change to this:
```
    if (oldfd == newfd) {
        put_handle(hdl);
        return newfd;
    }
```
___
*[LibOS/shim/src/sys/shim_dup.c, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRfI9_70PFfoixPafC:-MpRfI9_70PFfoixPafD:bqdvjrb) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L70)):*
> ```C
> 
>     if (oldfd == newfd)
>         return -EINVAL;
> ```

This check is not needed, because we already have the same check above (see the very first line of this function).

You can safely remove these two lines of code you added.


<!-- Sent from Reviewable.io -->

2021-11-26 14:54 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_dup.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpReuLS19neH9_dqqor:-MpRizQrAr3hzJjicxpE:bymdal) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should also put the `hdl` handle (decrement its reference count). This is because `hdl = get_fd_handle()` above gets this handle (increments its reference count). So we need to put the handle here to avoid memory leaks. So please change to this:
```
    if (oldfd == newfd) {
        put_handle(hdl);
        return newfd;
    }
```
</blockquote></details>

Sure. I'll do.
___
*[LibOS/shim/src/sys/shim_dup.c, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRfI9_70PFfoixPafC:-MpRj-fR2LjZFo4wTMU3:bxwad8b) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This check is not needed, because we already have the same check above (see the very first line of this function).

You can safely remove these two lines of code you added.
</blockquote></details>

I think we should edit the first line to remove the check, and have it here, because if the oldfd is not valid, we need to return EBADF and then only check if its value is the same as newfd, right?


<!-- Sent from Reviewable.io -->

2021-11-26 15:40 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @svenkata9)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRt_qd-0R30lofluBJ):*
This will need update after removing changes from `dup3`. Also it's pretty vague, would be good to add something about changing return value in case of both fds being equal.
___
*[LibOS/shim/src/sys/shim_dup.c, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRfI9_70PFfoixPafC:-MpRtKNGAbKO2iPGcxv0:b63fjcm) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L70)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I think we should edit the first line to remove the check, and have it here, because if the oldfd is not valid, we need to return EBADF and then only check if its value is the same as newfd, right?
</blockquote></details>

No, Linux return `EINVAL` if both fds are equal, even if they are invalid.


<!-- Sent from Reviewable.io -->

2021-11-26 16:10 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRt_qd-0R30lofluBJ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This will need update after removing changes from `dup3`. Also it's pretty vague, would be good to add something about changing return value in case of both fds being equal.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_dup.c, line 70 at r1](https://reviewable.io/reviews/gramineproject/gramine/249#-MpRfI9_70PFfoixPafC:-MpS-ikxEE8RRhsJxNRr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6ed32d417d2b9e62f42023ec1da2bbd96d3060fd/LibOS/shim/src/sys/shim_dup.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, Linux return `EINVAL` if both fds are equal, even if they are invalid.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-26 16:17 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpS1KP1-oiBCeaP7GfN):*
This commits need to be squashed and msg taken from the 2nd. Will do at rebase.


<!-- Sent from Reviewable.io -->

2021-11-26 16:17 UTC, boryspoplawski commented
Jenkins, test this please

2021-11-27 01:59 UTC, svenkata9 commented
> > Reviewed 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)_ status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)
> 
> _[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpS1KP1-oiBCeaP7GfN):_ This commits need to be squashed and msg taken from the 2nd. Will do at rebase.

Thanks

2021-11-29 07:36 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-11-29 07:38 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpS1KP1-oiBCeaP7GfN):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This commits need to be squashed and msg taken from the 2nd. Will do at rebase.
</blockquote></details>

Thanks


<!-- Sent from Reviewable.io -->

2021-11-29 10:42 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpS1KP1-oiBCeaP7GfN):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 10:44 UTC, dimakuv commented
Jenkins, test this please

2021-11-29 10:44 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpfHjKGEiJ4fclwJiO_):*
What's wrong with reveiwable? Why does it show different commits than GH?
cc @dimakuv @mkow 


<!-- Sent from Reviewable.io -->

2021-11-29 10:45 UTC, boryspoplawski commented
Jenkins, test this please

2021-11-29 10:53 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpfHjKGEiJ4fclwJiO_):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's wrong with reveiwable? Why does it show different commits than GH?
cc @dimakuv @mkow 
</blockquote></details>

No idea.


<!-- Sent from Reviewable.io -->

2021-11-29 11:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/249#-MpfHjKGEiJ4fclwJiO_):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No idea.
</blockquote></details>

Interesting, will report this bug.


<!-- Sent from Reviewable.io -->

2021-11-29 11:44 UTC, merged

2021-11-29 11:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/249#-MpfVkuq6Uk6QowFkXTt:-MpfVkur2d5RIsZannOq:bunwjha) (no related file):*
@svenkata9 for the future: please prefix the branch name with something unique (preferably your github handle), it makes much easier to manage it (since I have to pull it locally)

---


<!-- Sent from Reviewable.io -->

2021-11-29 12:37 UTC, svenkata9 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/249)_ status: :shipit: complete! all files reviewed, all discussions resolved
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gramine/249#-MpfVkuq6Uk6QowFkXTt:-MpfVkur2d5RIsZannOq:bunwjha) (no related file):_ @svenkata9 for the future: please prefix the branch name with something unique (preferably your github handle), it makes much easier to manage it (since I have to pull it locally)

Sure, Borys. Will do.