[Pal,LibOS] rtld: Rename `l_addr`/`l_base` to `l_diff`
gramineproject/gramine pull request #255
Opened 2021-11-30 12:25 UTC by dimakuv

## Description of the changes 

Previously, `l_addr`/`l_base` field names were used to denote the "difference between virtual addresses in ELF file and actual virtual addresses in memory". This commit renames them to `l_diff` which reflects the actual meaning better.

Link to ELF spec, see page 73: https://refspecs.linuxfoundation.org/elf/elf.pdf.

## How to test this PR? 

All tests must pass, no functional change.

2021-11-30 13:37 UTC, pwmarcz reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-MpkxkLj5ClYDNzszDXV:b-51hlfh) (no related file):*
I'm still not a fan of "diff": for me, it sounds not like a difference between numbers/addresses, but something like a textual diff. And how do we use it in English? "The diff of this ELF object"? "The diff at/with which this ELF was loaded"?

Alternatives:
* @mkow suggested "base_shift"
* synonyms of "difference": "shift"? "delta"? There's "offset", but usually it means offset in file.
* synonyms of "base": "origin"? (as in: origin of coordinate system)

Not blocking, though: I'm fine with "diff" if it sounds best to you.

---


<!-- Sent from Reviewable.io -->

2021-11-30 13:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-Mpl3dmM1chNOqpbIX7s:b-zek0hy) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm still not a fan of "diff": for me, it sounds not like a difference between numbers/addresses, but something like a textual diff. And how do we use it in English? "The diff of this ELF object"? "The diff at/with which this ELF was loaded"?

Alternatives:
* @mkow suggested "base_shift"
* synonyms of "difference": "shift"? "delta"? There's "offset", but usually it means offset in file.
* synonyms of "base": "origin"? (as in: origin of coordinate system)

Not blocking, though: I'm fine with "diff" if it sounds best to you.
</blockquote></details>

I'd vote for `base_shift`

---


<!-- Sent from Reviewable.io -->

2021-11-30 15:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-MplOcYg3-hSAAF9aCy8:bhkm051) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd vote for `base_shift`
</blockquote></details>

I'm not a big fan of `base_shift`. This name is not easily recognizable (shift from the base? `shift` is a very weird word in the context of memory addresses). I suggest:
- `base_diff`
- `base_offset`
-  `addr_diff` (I vote for this)

I guess @boryspoplawski will be our tie-breaker :)

---


<!-- Sent from Reviewable.io -->

2021-11-30 18:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-Mpm6fcr84fnYrtwySp9:b3vkg0t) (no related file):*
> And how do we use it in English? "The diff of this ELF object"? "The diff at/with which this ELF was loaded"?

Non of the proposed names are any better with regard to this. I guess the reason is that it's the difference of in memory and in file base addresses, so unless your sentence contains references to both of these (in mem and in file) then any term will be missing the context.

> I'd vote for base_shift

I don't like this either, sounds like base is aligned to some power of 2 and you use "shift operator" to obtain the actual base (e.g. `encoded_base << base_shift == real_base`).

> I guess @boryspoplawski will be our tie-breaker :)

I vote for `base_diff`, but `addr_diff` will do as well.

---


<!-- Sent from Reviewable.io -->

2021-12-01 07:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-MpowdXgELguWKgKuRmF:bs4xikn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> And how do we use it in English? "The diff of this ELF object"? "The diff at/with which this ELF was loaded"?

Non of the proposed names are any better with regard to this. I guess the reason is that it's the difference of in memory and in file base addresses, so unless your sentence contains references to both of these (in mem and in file) then any term will be missing the context.

> I'd vote for base_shift

I don't like this either, sounds like base is aligned to some power of 2 and you use "shift operator" to obtain the actual base (e.g. `encoded_base << base_shift == real_base`).

> I guess @boryspoplawski will be our tie-breaker :)

I vote for `base_diff`, but `addr_diff` will do as well.
</blockquote></details>

`base_diff` it is. Will submit a fixup shortly.

---


<!-- Sent from Reviewable.io -->

2021-12-01 07:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-MpozZwt2JB649eNEzHg:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`base_diff` it is. Will submit a fixup shortly.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-12-01 10:43 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/255#-MpkxkLi3c854vrKDevi:-MppYQHt2RwuSdeGh3nt:b5rs6wm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After checking the PR it seems we had a couple of bugs, stemming from the poor name choice. Good we changed it!

---
___
*[LibOS/shim/src/shim_rtld.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppSd5h2vEiy2q89jE5:-MppS1U4AuYgUzjt4yPV:bgzj0xs) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L46)):*
> ```C
>     /*
>      * Difference between virtual addresses (p_vaddr) in ELF file and actual virtual addresses in
>      * memory. Equal to the address shared object (its first LOAD segment) is loaded at for ET_DYNs,
> ```

Isn't there (rather pathological and probably not happening in the wild) a case where the first LOAD segment has non 0 address for ET_DYNs? In such case this would not be the address where the shared object is loaded at (but well, the diff described in the first sentence).
___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MppXiZU010ZF8a0VTjJ:b-dxblqn) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
> ```C
> 
> static void remove_elf_object(struct link_map* l) {
>     remove_r_debug((void*)l->l_base_diff);
> ```

I believe this is a bug. These functions (`remove_r_debug` and `append_r_debug`) expect the address where the elf is loaded at, not `base_diff`. This would only prove that the choice of the old name was beyond broken.
This works only because in most "normal" elfs these two values (base address and `base_diff`) are equal.
___
*[LibOS/shim/src/shim_rtld.c, line 643 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppVWz8-KrTMyUOthDi:-MppVWz94pgp9U876mn-:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L643)):*
> ```C
> 
>     if (map->l_file && !qstrempty(&map->l_file->uri)) {
>         append_r_debug(qstrgetstr(&map->l_file->uri), (void*)map->l_base_diff);
> ```

ditto
___
*[LibOS/shim/src/shim_rtld.c, line 901 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYJBEBz4SIqlRnMtN:-MppYJBEBz4SIqlRnMtO:b-kc313u) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L901)):*
> ```C
>     auxp[3].a_un.a_val = g_exec_map->l_entry;
>     auxp[4].a_type     = AT_BASE;
>     auxp[4].a_un.a_val = g_interp_map ? g_interp_map->l_base_diff : 0;
> ```

ditto - this needs to be an actual address, not `base_diff`
___
*[Pal/include/pal_rtld.h, line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYbzN-FM3h9yTFlg0:-MppYbzO6m4e_W6ixuGu:b-63mdd2) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/include/pal_rtld.h#L18)):*
> ```objc
>     /*
>      * Difference between virtual addresses (p_vaddr) in ELF file and actual virtual addresses in
>      * memory. Equal to the address shared object (its first LOAD segment) is loaded at for ET_DYNs,
> ```

ditto (as in LibOS)
___
*[Pal/src/db_rtld.c, line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYr2h6NzF8_c9vmOv:-MppYr2i3NdQ1aw9eYGx:bfneerh) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L28)):*
> ```C
>  *    (via `l_base_diff`), whereas virtual addresses in EXEC binaries are hard-coded and do not need
>  *    any adjustment (thus `l_base_diff == 0x0`). The LibOS shared library is built as DYN, but some
>  *    PAL regression tests are built as EXEC, so we support both.
> ```

I would remove the last sentence, it adds nothing and might become invalid soon. Your new PAL (if/when it comes) will be an EXEC, right?
___
*[Pal/src/db_rtld.c, line 399 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppZnirAHwHEXtBsT1f:-MppZnirAHwHEXtBsT1g:b-ucy6ch) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L399)):*
> ```C
>             g_entrypoint_map.l_map_start = (ElfW(Addr))map_addr;
>             g_entrypoint_map.l_base_diff = (ehdr->e_type == ET_EXEC) ? 0x0
>                                                                      : g_entrypoint_map.l_map_start;
> ```

Shouldn't we adjust this by subtracting first (this) segments `p_vaddr`?
___
*[Pal/src/db_rtld.c, line 543 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpp_gSB4Tf2fmCxer6m:-Mpp_gSB4Tf2fmCxer6n:b-mtpqg4) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L543)):*
> ```C
> #ifdef DEBUG
>     assert(g_entrypoint_map.l_name);
>     _DkDebugMapAdd(g_entrypoint_map.l_name, (void*)g_entrypoint_map.l_base_diff);
> ```

ditto - should be address not diff
___
*[Pal/src/db_rtld.c, line 559 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpp_l6rEx1uGHK9RTbc:-Mpp_l6rEx1uGHK9RTbd:b-epy2h9) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L559)):*
> ```C
> 
>     ElfW(Addr) pal_binary_addr = (ElfW(Addr))&__ehdr_start;
>     ElfW(Addr) pal_base_diff   = pal_binary_addr;
> ```

Shouldn't this be adjusted by first load segment's `p_vaddr`?


<!-- Sent from Reviewable.io -->

2021-12-01 10:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MppbUsz8wJTr3ibfk1A:bo1phbc) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I believe this is a bug. These functions (`remove_r_debug` and `append_r_debug`) expect the address where the elf is loaded at, not `base_diff`. This would only prove that the choice of the old name was beyond broken.
This works only because in most "normal" elfs these two values (base address and `base_diff`) are equal.
</blockquote></details>

I also thought so originally, but all these functions work with `ET_EXEC` files as well (e.g., I checked this on our PAL regression tests, where most PAL files are non-pie executables, i.e., `ET_EXEC`). And with `ET_EXEC`, `l_base_diff` is zero. So all these functions seem to accept the address difference, not the address itself.

@pwmarcz Could you shed some light on these functions and their arguments?


<!-- Sent from Reviewable.io -->

2021-12-01 10:57 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MppcacP0f0J6w0ToKEl:byfptgw) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also thought so originally, but all these functions work with `ET_EXEC` files as well (e.g., I checked this on our PAL regression tests, where most PAL files are non-pie executables, i.e., `ET_EXEC`). And with `ET_EXEC`, `l_base_diff` is zero. So all these functions seem to accept the address difference, not the address itself.

@pwmarcz Could you shed some light on these functions and their arguments?
</blockquote></details>

Could you verify in GDB that they work as expected? I think this might work by accident - there is only one EXEC at a time, so only one elf will have this address == 0 (since we disallow mapping anything there normally). Maybe we do not get some symbols (or whatever this address is used for), but nothing brakes thanks to that.


<!-- Sent from Reviewable.io -->

2021-12-01 11:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MpphXY4EB3HZKAUQq59:bfg8dkt) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
> Could you verify in GDB that they work as expected?

I verified that e.g. HelloWorld is debuggable as usual. All HelloWorld symbols are there, I can put a breakpoint on `main` and I can step through it. So it looks totally fine. Or did you mean something else?


<!-- Sent from Reviewable.io -->

2021-12-01 11:47 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-Mppo0xO3LWJeX4anPsB:b-p0g58w) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Could you verify in GDB that they work as expected?

I verified that e.g. HelloWorld is debuggable as usual. All HelloWorld symbols are there, I can put a breakpoint on `main` and I can step through it. So it looks totally fine. Or did you mean something else?
</blockquote></details>

I've also checked - created an DYN ELF, which had first load segment address != 0 (unfortunately you cannot do this with ld, see the patch at https://sourceware.org/legacy-ml/binutils/2013-12/msg00081.html). Gramine loaded it without problems, debugging worked as well. Seems that this `l_addr` is not used for anything, except detecting collisions of libraries/not loading same lib twice in debug map list?


<!-- Sent from Reviewable.io -->

2021-12-01 13:45 UTC, pwmarcz reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/shim_rtld.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppSd5h2vEiy2q89jE5:-MpqBB1X3IjO9D8EHHHZ:b-gkxx3w) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't there (rather pathological and probably not happening in the wild) a case where the first LOAD segment has non 0 address for ET_DYNs? In such case this would not be the address where the shared object is loaded at (but well, the diff described in the first sentence).
</blockquote></details>

Yes, `(its first LOAD segment)` sounds wrong, and also that's why we have `l_map_start`.
___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MpqBWZB65Cib8iAmaCJ:bojezqd) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've also checked - created an DYN ELF, which had first load segment address != 0 (unfortunately you cannot do this with ld, see the patch at https://sourceware.org/legacy-ml/binutils/2013-12/msg00081.html). Gramine loaded it without problems, debugging worked as well. Seems that this `l_addr` is not used for anything, except detecting collisions of libraries/not loading same lib twice in debug map list?
</blockquote></details>

I believe all these functions already operate on "base diff" as defined currently:
* This value is used in the GDB integration, and we use it to compute section addresses that we pass to GDB. See `debug_map_gdb.py`.
* It's also used by `describe_location` to calculate symbol address: we subtract this value from the memory address, then compare it with output of `nm`. See `debug_map.c` (`debug_map_find()`).

What will _not_ work in the case you describe is unloading such objects when unmapping memory (see `shim_vma.c`), and there's a TODO there about exactly this.
___
*[LibOS/shim/src/shim_rtld.c, line 643 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppVWz8-KrTMyUOthDi:-MpqCyN72sYWGRXzGqDN:br1hn2u) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L643)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

As said above, I disagree.
___
*[Pal/src/db_rtld.c, line 543 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpp_gSB4Tf2fmCxer6m:-MpqDS7bDos-PpJEoc5t:br1hn2u) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L543)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto - should be address not diff
</blockquote></details>

As said above, I disagree.


<!-- Sent from Reviewable.io -->

2021-12-01 15:06 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MpqVsYnECW1UWVyUgnX:bwcx3j2) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I believe all these functions already operate on "base diff" as defined currently:
* This value is used in the GDB integration, and we use it to compute section addresses that we pass to GDB. See `debug_map_gdb.py`.
* It's also used by `describe_location` to calculate symbol address: we subtract this value from the memory address, then compare it with output of `nm`. See `debug_map.c` (`debug_map_find()`).

What will _not_ work in the case you describe is unloading such objects when unmapping memory (see `shim_vma.c`), and there's a TODO there about exactly this.
</blockquote></details>

All right, it makes sense, but I would rename these arguments (because atm they are just `addr`, which is clearly misleading).

Also the comment in `debug_map_gdb.py` mentions `-o <load_addr>`:
1) `load_addr` is actually okay-ish name,
2) gdb help says `-o OFFSET` and always describes this as an offset (not an address).
___
*[Pal/src/db_rtld.c, line 543 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpp_gSB4Tf2fmCxer6m:-MpqWxxS64CRSInBfeof:bkk47yg) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L543)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

As said above, I disagree.
</blockquote></details>

ditto (argument name)


<!-- Sent from Reviewable.io -->

2021-12-01 17:04 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_rtld.c, line 901 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYJBEBz4SIqlRnMtN:-Mpqw_mC6xIQ8Akk_b2K:b-juxc9y) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L901)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. From what I understand in the corresponding Linux source, you are right, this should be the actual base address (here: https://elixir.bootlin.com/linux/latest/source/fs/binfmt_elf.c#L591).

@pwmarcz It looks like `l_map_start` was not used at all in the LibOS?
</blockquote></details>

That sounds likely - the interpreter is usually from Glibc, so probably we didn't give much thought to this part.


<!-- Sent from Reviewable.io -->

2021-12-01 17:28 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppSd5h2vEiy2q89jE5:-Mpqjw-UBxNotXXFuhvT:b-lfc7dt) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about `address shared object is loaded at`?
___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-Mpqk9PN8DYj88GTDVub:b238o44) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you want me to rename the names in this PR (in a separate commit), or have a separate PR with these debug-funcs renames?
</blockquote></details>

I would even say they belong to this commit (the only one in this PR).
___
*[Pal/include/pal_rtld.h, line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYbzN-FM3h9yTFlg0:-Mpqxj0N-ltYt9SZbqUA:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/include/pal_rtld.h#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[Pal/src/db_rtld.c, line 399 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppZnirAHwHEXtBsT1f:-MpqzLsc1dv7Bfg6tukl:b-btg1c8) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L399)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I added the comment describing that `p_vaddr == 0`, otherwise this PAL rtld code would return with error.
</blockquote></details>

Isn't the fix just adding `- c->start`? I think that's even easier than explaining why we don't do it.
___
*[Pal/src/db_rtld.c, line 559 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpp_l6rEx1uGHK9RTbc:-Mpr1QT93_T1nPI6ObCF:bovzf65) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L559)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We assume that the PAL binary is `ET_DYN` with the first load segment having `p_vaddr == 0`. Actually, I don't even know how to get to the first LOAD segment in this code -- the PAL binary was loaded by the kernel (in the Linux PAL case).

I added a comment; not sure if it helps...
</blockquote></details>

Okay, but this might become a problem for your new PAL (since it's an EXEC).


<!-- Sent from Reviewable.io -->

2021-12-01 20:25 UTC, mkow reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-12-02 10:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: 0 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 46 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppSd5h2vEiy2q89jE5:-MpuPtKZ0WuYDiXdSs2Z:b-je8umi) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about `address shared object is loaded at`?
</blockquote></details>

Done. Couldn't come up with a short desc, so just removed it. Probably was not needed anyway, since the "difference between ..." already says it all.
___
*[LibOS/shim/src/shim_rtld.c, line 487 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppXiZTE-5I6jM-FYWM:-MpuZT4566FAHgMVFi-0:b-fhu8np) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/LibOS/shim/src/shim_rtld.c#L487)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would even say they belong to this commit (the only one in this PR).
</blockquote></details>

No, I don't think we should do it in this commit. I submitted a separate issue:https://github.com/gramineproject/gramine/issues/259

I first tried to fix all these debug-related functions (including `DkDebug...`), but this exploded. There is a *lot* of code where we use `addr` but in fact it means `base_diff`. We should fix it in a separate PR.
___
*[Pal/include/pal_rtld.h, line 18 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppYbzN-FM3h9yTFlg0:-MpuQ-QP8EW1IBJQGjGs:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/include/pal_rtld.h#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[Pal/src/db_rtld.c, line 399 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppZnirAHwHEXtBsT1f:-MpuTQnBAa-TK16wN8lC:b-11tm5v) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L399)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't the fix just adding `- c->start`? I think that's even easier than explaining why we don't do it.
</blockquote></details>

Done. Ok, actually I reworked it; now this code snippet looks and behaves similarly to how it's done in `shim_rtld.c`


<!-- Sent from Reviewable.io -->

2021-12-02 10:58 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-12-02 11:16 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/db_rtld.c, line 399 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppZnirAHwHEXtBsT1f:-Mpuq_IYA9SIT5zKAtIH:bi1kyu5) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L399)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Ok, actually I reworked it; now this code snippet looks and behaves similarly to how it's done in `shim_rtld.c`
</blockquote></details>

This seems to be more complicated, I expected a simple `- c->start` is enough.
___
*[Pal/src/db_rtld.c, line 385 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqiNT1u6-GFU9M4eB:-MpuqiNU71pfE6z6cZs3:b-w10ifc) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L385)):*
> ```C
>              * overwrite memory on subsequent segments.
>              *
>              * Note that we reserve memory starting from offset 0, not from c->start. This is to
> ```

Wait, this does not reserve memory - it actually maps it.
___
*[Pal/src/db_rtld.c, line 392 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqljQ8BHTt9DVBUaw:-MpuqljQ8BHTt9DVBUax:b-jjvmyh) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L392)):*
> ```C
>         }
> 
>         ret = _DkStreamMap(handle, &map_addr, c->prot | PAL_PROT_WRITECOPY, c->map_off, map_size);
> ```

Are you sure this is correct? Wouldn't it map first segment at the start of this range, regardless of it's `p_vaddr`?


<!-- Sent from Reviewable.io -->

2021-12-02 13:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/shim_rtld.c, line 386 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvF9lk0QL3p-XME5WG:-MpvF9lk0QL3p-XME5WH:b-m9l49s) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/LibOS/shim/src/shim_rtld.c#L386)):*
> ```C
>     size_t load_end = loadcmds[n_loadcmds - 1].alloc_end;
> 
>     if (ehdr->e_type == ET_DYN) {
> ```

FYI: @boryspoplawski This is where my logic in PAL mirrors the logic in LibOS now.
___
*[Pal/src/db_rtld.c, line 399 at r2](https://reviewable.io/reviews/gramineproject/gramine/255#-MppZnirAHwHEXtBsT1f:-Mpusb1i1qyFe-nxWPyR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a8ca87ce11dd8662bf34c828d171bf6bb3b1726b/Pal/src/db_rtld.c#L399)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This seems to be more complicated, I expected a simple `- c->start` is enough.
</blockquote></details>

Done.
___
*[Pal/src/db_rtld.c, line 385 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqiNT1u6-GFU9M4eB:-MpvEJN77l30TjMlL6Dw:b-8vzdg) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L385)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, this does not reserve memory - it actually maps it.
</blockquote></details>

Done. I still keep `reserve` because that's what we want to do -- reserve a sufficiently large memory region that is enough to put all LOAD segments into this region. We reserve this region via a dummy `_DkStreamMap()` because this is the only function in PAL I could find that finds some unoccupied address :(
___
*[Pal/src/db_rtld.c, line 392 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqljQ8BHTt9DVBUaw:-MpuriuJ4Q_xwWJV0lDv:b-127kg7) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L392)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Are you sure this is correct? Wouldn't it map first segment at the start of this range, regardless of it's `p_vaddr`?
</blockquote></details>

Done. You are right, I mixed everything. This is because I tried to "merge" two code paths into one:
1. Reserve a sufficiently large memory region
2. File-map the contents from each LOAD segment in the ELF file to this memory region

Now I split these two steps in two separate code snippets, and the logic makes sense now. In fact, it is the same as in LibOS (see my other comment).


<!-- Sent from Reviewable.io -->

2021-12-02 15:11 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/src/db_rtld.c, line 385 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqiNT1u6-GFU9M4eB:-MpveWIO4GWb11OmOpKf:b3vo9e4) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L385)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I still keep `reserve` because that's what we want to do -- reserve a sufficiently large memory region that is enough to put all LOAD segments into this region. We reserve this region via a dummy `_DkStreamMap()` because this is the only function in PAL I could find that finds some unoccupied address :(
</blockquote></details>

We still map the memory, not reserve it. Note that on LibOS level we merely mark the memory as taken in our memory manager, here you actually map a file there.
___
*[Pal/src/db_rtld.c, line 371 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpvf_lY-q4NpniYAF_O:-Mpvf_lZBEjJ2Dg7HWxG:bwgexqv) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L371)):*
> ```C
> 
>     if (ehdr->e_type == ET_DYN) {
>         /*
> ```

My initial comment about handling this was because I thought it's enough to add `- c->start` to one line and that's all. Since we do not support first `p_vaddr != 0` anyway, any more complicated solution is probably not worth it.
Since you've already done the work, we could have merge it, if it was correct, but I'm not really sure it is. I'll leave the decision what to do with this to you. Whatever you decide to do (keep this version or restore the old one) please keep the setting of starting address out of the loop - it's a nice cleanup :)
___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpvdzD49QU1Z_kK5mkr:b-2f6hpt) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
> ```C
>          */
>         void* map_addr = NULL;
>         ret = _DkStreamMap(handle, &map_addr, /*prot=*/0, /*offset=*/0,
> ```

How does it actually work? We map a file, which might be far smaller than the map size (in the case of first p_vaddr != 0). Doesn't this mean that `map_addr` now contain elf header?


<!-- Sent from Reviewable.io -->

2021-12-02 15:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/src/db_rtld.c, line 385 at r4](https://reviewable.io/reviews/gramineproject/gramine/255#-MpuqiNT1u6-GFU9M4eB:-Mpvm8Rt5rMuZxMIGJdN:b-rl2h6f) ([raw file](https://github.com/gramineproject/gramine/blob/a7074cce776b12fedeaa57210f3a1c4d87ec2421/Pal/src/db_rtld.c#L385)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We still map the memory, not reserve it. Note that on LibOS level we merely mark the memory as taken in our memory manager, here you actually map a file there.
</blockquote></details>

Done. Hope new comments explain what's going on better.
___
*[Pal/src/db_rtld.c, line 371 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-Mpvf_lY-q4NpniYAF_O:-MpvmIGR5PaCeDulmLto:bh8rw3p) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L371)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

My initial comment about handling this was because I thought it's enough to add `- c->start` to one line and that's all. Since we do not support first `p_vaddr != 0` anyway, any more complicated solution is probably not worth it.
Since you've already done the work, we could have merge it, if it was correct, but I'm not really sure it is. I'll leave the decision what to do with this to you. Whatever you decide to do (keep this version or restore the old one) please keep the setting of starting address out of the loop - it's a nice cleanup :)
</blockquote></details>

The latest implementation is definitely more correct (and it mirrors the LibOS rtld implementation). I prefer to keep this implementation.
___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpvjjzqBICWLKIpx2-a:bzii3h4) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How does it actually work? We map a file, which might be far smaller than the map size (in the case of first p_vaddr != 0). Doesn't this mean that `map_addr` now contain elf header?
</blockquote></details>

But we don't care about the actual contents. Yes, `map_addr` will contain the ELF header, but this is irrelevant. What's relevant is that we will later map each LOAD segment over this memory region. And the ELf header (which is in the first LOAD segment) will be at the `l_map_start` -- this is what we will use anyway.

So if say first LOAD segment has `p_vaddr = 0x1000`, then `l_map_start = 0x1000 + l_base_diff` (which is where we allocated this dummy memory region). So the ELF header will be read from the correct final address (`l_map_start = 0x1000 + l_base_diff`).

Just to reiterate: I have to use `DkStreamMap()` to get a dummy memory region at some address. I will not use the contents of this memory region at all -- they will be overwritten by the contents of `DkStreamMap(<actual LOAD segment>)` invocations below. I have to use `DkStreamMap()` here simply because we have a bug (feature?) of disallowing `DkVirtualMemoryAlloc(/*addr=*/NULL)`.

Also, pay attention that I have `/*prot=*/0` here, which means that this is a "dummy" memory region. We can't even read from it.


<!-- Sent from Reviewable.io -->

2021-12-02 16:29 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-02 18:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpwJckZ9THepP3yNV0-:bhw9j2s) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
> what are the semantics (e.g. is file 0 extended to the requested size?)

Yes, the "exceeding file size" part of the requested memory region is filled with zeros. That's the semantics of `DkStreamMap()`, similar to how file-backed `mmap()` does it. 


<!-- Sent from Reviewable.io -->

2021-12-02 19:38 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpwdlyiBsCQgPRpucLJ:b-uzg7pt) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> what are the semantics (e.g. is file 0 extended to the requested size?)

Yes, the "exceeding file size" part of the requested memory region is filled with zeros. That's the semantics of `DkStreamMap()`, similar to how file-backed `mmap()` does it. 
</blockquote></details>

cc @mkow hahaha :)


<!-- Sent from Reviewable.io -->

2021-12-03 07:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpzCZkU4J3nfNvpAAEz:b-j8mggi) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

cc @mkow hahaha :)
</blockquote></details>

I take it back. I looked at the actual `mmap()` semantics and how it is implemented in our PALs. TLDR: no consistency in our PALs.

`mmap()` semantics are as follows:
1. The part of the mapping that exceeds the file size but is still in the last page of file contents is filled with zeros.
2. The part of the mapping that exceeds the file size and also exceeds the last page of file contents produces SIGBUS on any access.

In other words, accesses to pages that contain actual file contents are allowed, all other accesses produce SIGBUS
(See e.g. https://stackoverflow.com/questions/59024621/can-i-mmap-a-file-with-length-greater-than-the-size-of-the-file).

Now how does it work in PALs:
- Linux: `DkStreamMap()` ends up in `file_map()` which simply calls host-level `mmap()`. So semantics are the same.
- Linux-SGX: `DkStreamMap()` ends up in `file_map()` which ultimately calls (for protected, allowed, trusted files) `get_enclave_pages()` which fills the whole mapping with zeros. So semantics are *different* -- SIGBUS is never triggered. (There is probably not much that can be done about this anyway, we're on SGX v1.)


<!-- Sent from Reviewable.io -->

2021-12-03 08:58 UTC, pwmarcz approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-12-03 09:07 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpzWlFIEWm2_FBxeflg:b8dszrs) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I take it back. I looked at the actual `mmap()` semantics and how it is implemented in our PALs. TLDR: no consistency in our PALs.

`mmap()` semantics are as follows:
1. The part of the mapping that exceeds the file size but is still in the last page of file contents is filled with zeros.
2. The part of the mapping that exceeds the file size and also exceeds the last page of file contents produces SIGBUS on any access.

In other words, accesses to pages that contain actual file contents are allowed, all other accesses produce SIGBUS
(See e.g. https://stackoverflow.com/questions/59024621/can-i-mmap-a-file-with-length-greater-than-the-size-of-the-file).

Now how does it work in PALs:
- Linux: `DkStreamMap()` ends up in `file_map()` which simply calls host-level `mmap()`. So semantics are the same.
- Linux-SGX: `DkStreamMap()` ends up in `file_map()` which ultimately calls (for protected, allowed, trusted files) `get_enclave_pages()` which fills the whole mapping with zeros. So semantics are *different* -- SIGBUS is never triggered. (There is probably not much that can be done about this anyway, we're on SGX v1.)
</blockquote></details>

For the context: I was laughing, because I've created a task on a CTF contest we organized last weekend, for which the solution based on the fact that you can violate the rule number 1 in your list :) Basically, there is also file page cache, so if you map a file, write beyond it on the last page, unmap, then successive mapping of this page (even in other processes) will see these changes, as long as the page stays in cache. Which basically means you cannot assume the page is zero filled.


<!-- Sent from Reviewable.io -->

2021-12-03 09:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-MpzgzTf9ajneEr3nBH9:b-o8x90q) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

For the context: I was laughing, because I've created a task on a CTF contest we organized last weekend, for which the solution based on the fact that you can violate the rule number 1 in your list :) Basically, there is also file page cache, so if you map a file, write beyond it on the last page, unmap, then successive mapping of this page (even in other processes) will see these changes, as long as the page stays in cache. Which basically means you cannot assume the page is zero filled.
</blockquote></details>

I see. True, there is a note somewhere in `man 2 mmap` about this Linux behavior.


<!-- Sent from Reviewable.io -->

2021-12-03 09:51 UTC, merged

2021-12-03 13:31 UTC, mkow reviewed
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/255)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/db_rtld.c, line 382 at r5](https://reviewable.io/reviews/gramineproject/gramine/255#-MpvdzD3-wC5hR2hOvEn:-Mq-SrDeByc9HwRE65Zh:bpyt9kx) ([raw file](https://github.com/gramineproject/gramine/blob/cdfedcc014d14159464f54e2f4052e827bed4361/Pal/src/db_rtld.c#L382)):*
> Yes, the "exceeding file size" part of the requested memory region is filled with zeros. That's the semantics of `DkStreamMap()`, similar to how file-backed `mmap()` does it.

hehe :)

> The part of the mapping that exceeds the file size but is still in the last page of file contents is filled with zeros.

This nicely explains the very low number of solves for this challenge :)


<!-- Sent from Reviewable.io -->