[LibOS] Fix FUTEX_WAKE_OP's implementation of `ANDN` operation
gramineproject/gramine pull request #265
Opened 2021-12-04 03:07 UTC by vijaydhanraj

## Description of the changes 

Current code implements `ANDN` op as NAND operation but this op according to man pages should do a complement of `oparg` and then `bitwise and` with the value of `uaddr2`. This commit fixes the issue.

2021-12-04 03:11 UTC, vijaydhanraj reviewed
Currently we do have a test for `FUTEX_WAKE_OP` as part of our LibOS regression test suite. But this tests only `FUTEX_OP_XOR` operation. Should we extend this and add a test for `FUTEX_OP_ANDN` operation as well?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265#-:-Mq2PXOX2t7Mwv9nAimj:be46etx)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2021-12-05 18:12 UTC, mkow reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqAmLHJDniv7pupEWr6:-MqAmLHKAIqAMltoHiCM:bbehtkq) (no related file):*
> Should we extend this and add a test for `FUTEX_OP_ANDN` operation as well?

Would be nice to have a test for this and other operations. Alternatively, you can check why LTP haven't detected this issue - I guess the tests which use it require shared memory so we have them disabled?

---


<!-- Sent from Reviewable.io -->

2021-12-06 08:01 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqAmLHJDniv7pupEWr6:-MqDkUAx2hV_fdaiyURH:b-w3mc9b) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Should we extend this and add a test for `FUTEX_OP_ANDN` operation as well?

Would be nice to have a test for this and other operations. Alternatively, you can check why LTP haven't detected this issue - I guess the tests which use it require shared memory so we have them disabled?
</blockquote></details>

+1. @boryspoplawski Maybe you could recommend how to add such a test?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqDkQK2BmOzi_f7rbkz:-MqDkQK39CvSSWP6yivk:b676ozr) (no related file):*
@boryspoplawski You worked on futexes. Can you look at this PR? Looks legit.

---


<!-- Sent from Reviewable.io -->

2021-12-06 12:32 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqAmLHJDniv7pupEWr6:-MqEiVPv2VkpkXcFfSWB:b-os5umw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. @boryspoplawski Maybe you could recommend how to add such a test?
</blockquote></details>

Preferably use some LTP tests that cover it (if present and possible). Otherwise, we have a `futex_wake_op.c` test which can be extended, but that would be some work (from a quick peek it would need a small refactor to allow for code reuse).

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqDkQK2BmOzi_f7rbkz:-MqEghBeB2zLKigTrX-0:b-vs1pr4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski You worked on futexes. Can you look at this PR? Looks legit.
</blockquote></details>

Looks good.

---


<!-- Sent from Reviewable.io -->

2021-12-06 14:25 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqAmLHJDniv7pupEWr6:-MqF7g7d3ToldyEuXk6m:b-komh94) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Preferably use some LTP tests that cover it (if present and possible). Otherwise, we have a `futex_wake_op.c` test which can be extended, but that would be some work (from a quick peek it would need a small refactor to allow for code reuse).
</blockquote></details>

@vijaydhanraj Could you please try to add the test scenario for `FUTEX_OP_ANDN`?

---


<!-- Sent from Reviewable.io -->

2021-12-06 15:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqAmLHJDniv7pupEWr6:-MqFJ89O0wLnv56aURw6:b-bja85q) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj Could you please try to add the test scenario for `FUTEX_OP_ANDN`?
</blockquote></details>

I did look at LTP tests, `https://github.com/linux-test-project/ltp/tree/master/testcases/kernel/syscalls/futex` and there doesn't seem to be any test scenario checking the `FUTEX_WAKE_OP ` operations. So, agree that we will need to extend our `futex_wake_op.c` test.

@dimakuv sure, I will update this PR with the test for `FUTEX_OP_ANDN` and other operations as well.

---


<!-- Sent from Reviewable.io -->

2021-12-07 07:24 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-12-07 12:20 UTC, mkow reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-12-07 13:22 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqJs9j5ClLkxxT54fKA:bxi7d37) (no related file):*
@vijaydhanraj Please do not force push, but use fixup/squash commits.

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrTGX5CEW77-ePXWt):*
This tag is wrong - the core thing was (as one-liner states) fixing a bug in `[LibOS]`
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrnnDDdv_WAr8LYM_):*
two spaces after `of`
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrq1Y7rUUWOXHcQdd):*
I would prefer `bitwise negation` instead of `complement` (I think complement depends on the domain you are in, i.e. arithmetic negation is also a "complement").
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 102 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJwJCBBnKsFmEG31A6:-MqJwJCBBnKsFmEG31A7:bu9syey) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L102)):*
> ```C
>     for (i = 0; i < THREADS1 + THREADS2; i++) {
>         while (load(&thread_state[i]) != 1) {
>             usleep(1000u);
> ```

Please use `sched_yield` here instead (this is an existing issue, but it's good time to fix it)
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJwsmXBu6x4bM43I-V:-MqJwsmXBu6x4bM43I-W:b-wt91ob) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L113)):*
> ```C
> 
>     /* Sign extend 12-bit argument to 32-bit */
>     int oparg = wakeop_arg_extend((encoded_op >> 12) & 0xfff);
> ```

I think we could pass `oparg` and `op` to this function (together with `encoded_op`) - then we wouldn't have to do all of these bit twiddling. If we also passed `oldval` - `arg1`, it would also allow for setting `futex2` in this function instead of `main` - it would be less confusing for the reader.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzNjqA-FSxFY-3Gxa:-MqJzNjqA-FSxFY-3Gxb:b3wi3lh) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L141)):*
> ```C
>             break;
>         case FUTEX_OP_ANDN:
>             if (newval != (oldval & (~oparg))) {
> ```

Superfluous parenthesis around unary operation.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 143 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzdcu-1_Kk-K-te9k:-MqJzdcu-1_Kk-K-te9l:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L143)):*
> ```C
>             if (newval != (oldval & (~oparg))) {
>                 printf("FUTEX_OP_ANDN operation failed: current value: 0x%x, expected: 0x%x\n",
>                         newval, oldval & (~oparg));
> ```

ditto
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzx6u9oSMn_ODB6m6:-MqJzx6u9oSMn_ODB6m7:bvghhm) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L162)):*
> ```C
>         fail("futex_wake_op", errno);
>     }
>     if (ret != THREADS_WAKE1 + THREADS_WAKE2) {
> ```

Hmm, please move this and the error check above to before the operation output checks (right after futex call)
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 230 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJvAaK6Ulxd-LH_az5:-MqJvAaK6Ulxd-LH_az6:b9a93ss) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L230)):*
> ```C
> int main(void) {
>     int arg1 = 0x123846;
>     int arg2 = 0xc73;
> ```

I think these 2 should always be set on per test basis.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJv4f35idQ1g3kOlus:-MqJv4f35idQ1g3kOlut:b-3ltj1t) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L236)):*
> ```C
>         switch (i) {
>             case FUTEX_OP_SET:
>                 encoded_op = FUTEX_OP(FUTEX_OP_SET, arg2, FUTEX_OP_CMP_GT, arg2);
> ```

Why all these cases use the same value for `oparg` and `cmparg`?
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 245 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqK2bb51mwsvXtSFsZw:-MqK2bb51mwsvXtSFsZx:b-sx94t7) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L245)):*
> ```C
>                 break;
>             case FUTEX_OP_ANDN:
>                 arg1 = 0x123; /* Override arg1 to something less than or equal to 0x800 */
> ```

Why it has to be `<=` `0x800` not `0xfff`?


<!-- Sent from Reviewable.io -->

2021-12-07 21:29 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqLl1dq5D9MJODRZUfl:b-gkd6b0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@vijaydhanraj Please do not force push, but use fixup/squash commits.
</blockquote></details>

Sorry, I know we don't prefer this, but I amended the commit message so had to force push. Any way to get around this?
Excuse me this time as well as I already amended the commit before seeing this comment. :(

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrTGX5CEW77-ePXWt):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This tag is wrong - the core thing was (as one-liner states) fixing a bug in `[LibOS]`
</blockquote></details>

I wanted to point out that a LibOS regression test was modified as part of this commit. What would be the appropriate tag for such a case? Is it ` [LibOS, LibOS/regression] `?
PS: For now, I have reverted to `[LibOS]`
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrnnDDdv_WAr8LYM_):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

two spaces after `of`
</blockquote></details>

Done.
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrq1Y7rUUWOXHcQdd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would prefer `bitwise negation` instead of `complement` (I think complement depends on the domain you are in, i.e. arithmetic negation is also a "complement").
</blockquote></details>

Got it, done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 102 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJwJCBBnKsFmEG31A6:-MqLbFpyDI2kc37koJOg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `sched_yield` here instead (this is an existing issue, but it's good time to fix it)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJwsmXBu6x4bM43I-V:-MqLbIod0FQCgAY6BmU9:bb4odpn) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we could pass `oparg` and `op` to this function (together with `encoded_op`) - then we wouldn't have to do all of these bit twiddling. If we also passed `oldval` - `arg1`, it would also allow for setting `futex2` in this function instead of `main` - it would be less confusing for the reader.
</blockquote></details>

OK, now I pass `encoded_op`,  `oldval`, `op` and `oparg`. Just that renamed `oldval` as `orig_val` as it is not old value until the `futex_wake_op()` is invoked.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzNjqA-FSxFY-3Gxa:-MqLbjiCDVNylHFOvfSn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Superfluous parenthesis around unary operation.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 143 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzdcu-1_Kk-K-te9k:-MqLbkg19890sBHzA_Ta:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L143)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJzx6u9oSMn_ODB6m6:-MqLboorB7N5JJ6hB1vs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L162)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, please move this and the error check above to before the operation output checks (right after futex call)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 230 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJvAaK6Ulxd-LH_az5:-MqLc1kzBk7G-kv44iYb:b-etpz3u) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L230)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think these 2 should always be set on per test basis.
</blockquote></details>

OK, passing these variables for each test case. Also renamed `arg1`->`orig_val` and `arg2`->`oparg` to be uniform across the entire test file.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJv4f35idQ1g3kOlus:-MqLcQj9A5RgFBPc-kSX:bikc8e5) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why all these cases use the same value for `oparg` and `cmparg`?
</blockquote></details>

`cmparg` is used to compare against `oldval` such that `oldval cmp cmparg` returns `true`. So just picked up `arg2` which made the conditional check be `true` without introducing new variables.

But now update all the variables for each test scenario.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 245 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqK2bb51mwsvXtSFsZw:-MqLe6k5CM0hw_TWdHYL:b-gylcnz) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L245)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why it has to be `<=` `0x800` not `0xfff`?
</blockquote></details>

Since `cmparg` can range from `-2047` to `2048` (note only 12-bits are available and sign-extended), our comparison operator for this case (`FUTEX_OP_CMP_EQ`) will never result true if `arg1` had a value of 0xfff.

But have reworded the text now. Let me know if this looks better.


<!-- Sent from Reviewable.io -->

2021-12-07 23:48 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqMCGVc1fehQuQVbYJU:b-nluu7k) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, I know we don't prefer this, but I amended the commit message so had to force push. Any way to get around this?
Excuse me this time as well as I already amended the commit before seeing this comment. :(
</blockquote></details>

You can create a squash commit and write the new commit message there

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJrTGX5CEW77-ePXWt):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I wanted to point out that a LibOS regression test was modified as part of this commit. What would be the appropriate tag for such a case? Is it ` [LibOS, LibOS/regression] `?
PS: For now, I have reverted to `[LibOS]`
</blockquote></details>

No need for this, the information in the commit message body should be enough.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 245 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqK2bb51mwsvXtSFsZw:-MqMEDfc1L15GmypC-Ji:bec5aae) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L245)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Since `cmparg` can range from `-2047` to `2048` (note only 12-bits are available and sign-extended), our comparison operator for this case (`FUTEX_OP_CMP_EQ`) will never result true if `arg1` had a value of 0xfff.

But have reworded the text now. Let me know if this looks better.
</blockquote></details>

But `0x800` sign extended is negative, so it's `-2048` to `2047`.
It's ok now
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/265#-MqMDRUF1Zbt2rWLCtSH:-MqMDRUGEhKvzot9zi8l:b-t20lxs) ([raw file](https://github.com/gramineproject/gramine/blob/16a3be999d3e881a11187b65a17a2127f2596dc4/LibOS/shim/test/regression/futex_wake_op.c#L246)):*
> ```C
>             case FUTEX_OP_ADD:
>                 orig_val = -1;
>                 oparg = 0x1f;
> ```

I'm pretty sure shift by 31 on `int` is UB (overflow).


<!-- Sent from Reviewable.io -->

2021-12-08 01:51 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqMZc8z3qbVf0iJcEFF:b545175) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can create a squash commit and write the new commit message there
</blockquote></details>

OK thanks, will do.

---
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 245 at r2](https://reviewable.io/reviews/gramineproject/gramine/265#-MqK2bb51mwsvXtSFsZw:-MqMZtQSAIrTSh7orVBf:b-br0edv) ([raw file](https://github.com/gramineproject/gramine/blob/ef7ff9a566558975a121288a6c2a197312cc358c/LibOS/shim/test/regression/futex_wake_op.c#L245)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But `0x800` sign extended is negative, so it's `-2048` to `2047`.
It's ok now
</blockquote></details>

Yes, you are right the max +ve value is `0x7ff`. So, it should be `-2048` to `2047` but I think you got my point.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/265#-MqMDRUF1Zbt2rWLCtSH:-MqM_XRU7Vs0jG9k796n:b-d3022b) ([raw file](https://github.com/gramineproject/gramine/blob/16a3be999d3e881a11187b65a17a2127f2596dc4/LibOS/shim/test/regression/futex_wake_op.c#L246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm pretty sure shift by 31 on `int` is UB (overflow).
</blockquote></details>

We do have a special case when `oparg == 31` [See here](https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_futex.c#L515). I wanted to just test this scenario. I thought the built-in function would handle overflow if not at least would return an error. But in this case, I see newval as `2147483647`.

Should we return an error for this case?


<!-- Sent from Reviewable.io -->

2021-12-08 08:17 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqO5x1q2HdjisBDuOB6:b-t4hzei) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK thanks, will do.
</blockquote></details>

By the way, I found this "create a squash commit and put a new commit message there" cumbersome (this was first started by Michal). So I simply block myself in my PRs with the note how to change the commit message -- it is more convinient. I think Borys and Pawel do the same.

So in the future, simply put a blocking comment yourself on the `Commits` meta-file in Reviewable, with the proposed text change.

---


<!-- Sent from Reviewable.io -->

2021-12-08 12:59 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqP5g7oDEzuxgcMnO_u:bie6670) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, I found this "create a squash commit and put a new commit message there" cumbersome (this was first started by Michal). So I simply block myself in my PRs with the note how to change the commit message -- it is more convinient. I think Borys and Pawel do the same.

So in the future, simply put a blocking comment yourself on the `Commits` meta-file in Reviewable, with the proposed text change.
</blockquote></details>

Yeah and I also forget to change it will doing rebase :)

---
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/265#-MqMDRUF1Zbt2rWLCtSH:-MqP61bMBkRF-_4G78_o:b6govdo) ([raw file](https://github.com/gramineproject/gramine/blob/16a3be999d3e881a11187b65a17a2127f2596dc4/LibOS/shim/test/regression/futex_wake_op.c#L246)):*
Okey, then it might be a good idea to test this.

> the built-in function

What function you have in mind?

>  But in this case, I see newval as 2147483647.

Which makes sense, `-2147483648 - 1` overflows `int`.


<!-- Sent from Reviewable.io -->

2021-12-08 12:59 UTC, boryspoplawski commented
Jenkins, test this please

2021-12-08 17:48 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/265#-MqJs9j47z3s3D7aQZGm:-MqQ8N-i5Vui5nQCPuV1:b-oovb9e) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah and I also forget to change it will doing rebase :)
</blockquote></details>

@dimakuv thanks for the suggestion will do it this way from next time.

---
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/265#-MqMDRUF1Zbt2rWLCtSH:-MqQ8b_g6W9_0H8A06Wh:bt2iw30) ([raw file](https://github.com/gramineproject/gramine/blob/16a3be999d3e881a11187b65a17a2127f2596dc4/LibOS/shim/test/regression/futex_wake_op.c#L246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Okey, then it might be a good idea to test this.

> the built-in function

What function you have in mind?

>  But in this case, I see newval as 2147483647.

Which makes sense, `-2147483648 - 1` overflows `int`.

</blockquote></details>

Had an offline chat with @boryspoplawski , there isn't any change needed here as futex syscall gets uint32_t values. So, we should be good w.r.t `UB` due to overflows.


<!-- Sent from Reviewable.io -->

2021-12-09 13:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-12-09 13:39 UTC, dimakuv commented
Jenkins, test this please

2021-12-09 13:40 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/265)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-09 14:12 UTC, merged