[LibOS/regression] Disable mounting host "/etc" in `host_root_fs` test
gramineproject/gramine pull request #271
Opened 2021-12-07 14:29 UTC by boryspoplawski

## Description of the changes 
`host_root_fs` regression test mounts whole host root directory inside Gramine. Dynamic loaders ("ld.so") tend to cache locations of dynamic libraries and hold such caches in "/etc" directory, which could brake this test.

2021-12-07 16:09 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/271)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/271#-MqKe0VH9A8t60jB38Mq:-MqKe0VH9A8t60jB38Mr:brt2f5a) ([raw file](https://github.com/gramineproject/gramine/blob/05e09b5e1212fd89af6328f1e8b4101e41886522/LibOS/shim/test/regression/host_root_fs.manifest.template#L15)):*
> ```
> fs.mount.gramine_lib.uri = "file:{{ gramine.runtimedir(libc) }}"
> 
> # overwrite host "/etc" - we don't want host-level configuration files, eg. dynamic loader caches
> ```

`eg.` -> `e.g.`


<!-- Sent from Reviewable.io -->

2021-12-08 13:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/271)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/271#-MqKQ1JbCK02oOQv-fFs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`brake` -> `break`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/271#-MqKe0VH9A8t60jB38Mq:-MqPB8tV91oL1Ex0Mp18:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/05e09b5e1212fd89af6328f1e8b4101e41886522/LibOS/shim/test/regression/host_root_fs.manifest.template#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`eg.` -> `e.g.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 13:19 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/271)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-12-08 13:20 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/271)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-12-08 13:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/271)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-08 13:49 UTC, merged