[LibOS] Uniformly calculate `st_dev` in chroot stat functions
gramineproject/gramine pull request #273
Opened 2021-12-08 13:50 UTC by boryspoplawski

## Description of the changes 
`st_dev` was calculated differently in `stat` (path stat) and `fstat` (fd stat).

2021-12-08 14:51 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/273#-MqPWhLJ77SXAoJjfm-o:-MqPWhLJ77SXAoJjfm-p:b1q9dr1) ([raw file](https://github.com/gramineproject/gramine/blob/01bb2f4985a3fd0a78c83c4b3f6b2cecfc21f47c/LibOS/shim/src/fs/tmpfs/fs.c#L161)):*
> ```C
>     buf->st_mtime = data->mtime;
>     buf->st_atime = data->atime;
>     /* TODO: change to `hash_str(dent->inode->mount->uri)` once tmpsfs supports inodes. */
> ```

Typo: should be `tmpfs`


<!-- Sent from Reviewable.io -->

2021-12-08 14:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-12-09 11:46 UTC, pwmarcz approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-12-09 14:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/273#-MqPWhLJ77SXAoJjfm-o:-MqUXmll825fbqyuGlOS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/01bb2f4985a3fd0a78c83c4b3f6b2cecfc21f47c/LibOS/shim/src/fs/tmpfs/fs.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: should be `tmpfs`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-09 14:18 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-12-09 14:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/273)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-09 14:53 UTC, merged