[Pal/Linux-SGX] Allow different masks for SGX sealing key derivation
gramineproject/gramine pull request #275
Opened 2021-12-09 11:11 UTC by dimakuv

## Description of the changes 

This PR adds three new manifest options:

- `sgx.seal_key.flags_mask` for KEYREQUEST.ATTRIBUTESMASK.FLAGS
- `sgx.seal_key.xfrm_mask` for KEYREQUEST.ATTRIBUTESMASK.XFRM
- `sgx.seal_key.misc_mask` for KEYREQUEST.MISCMASK

These new manifest options allow the user to control how the SGX sealing key is generated. This flexibility is especially important for cases where files are sealed with one version of Gramine and unsealed with another version of Gramine (differing in default attribute masks).

For a very detailed explanation of this subtle issue, please check https://github.com/gramineproject/gramine/issues/274.

Fixes #274.

## How to test this PR? 

See #274. But here is a snippet that proves this PR works:
```
$ echo 'sgx.seal_key.xfrm_mask = "ffffffffffffff1b"' >> manifest.template
$ SGX=1 gramine-test build

$ gramine-sgx sealed_file sealed_file_mrsigner.dat
READING OK
```

I'm not sure how to test this in CI. I could create a couple new tests with manifest files containing compatible/incompatible `sgx.seal_key.xfrm_mask`, `sgx.seal_key.flags_mask`, `sgx.seal_key.misc_mask`, but I don't know if it is worth it.

2021-12-15 21:53 UTC, boryspoplawski requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: 3 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr-2rpiACHJpsrNrAlg:b-ln3ood) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
> ```reStructuredText
>     sgx.seal_key.flags_mask = "[8-byte hex value]"  (default: "ffffffffffffffff")
>     sgx.seal_key.xfrm_mask  = "[8-byte hex value]"  (default: "fffffffffff9ff1b")
>     sgx.seal_key.misc_mask  = "[4-byte hex value]"  (default: "ffffffff")
> ```

Uh, why these do not have the leading `0x`? Actually why they are not just numbers (instead of hex strings)?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-0uwgA1aRL95AfdO3:-Mr-0uwgA1aRL95AfdO4:b-mwu3z6) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L28)):*
> ```C
> bool g_allowed_files_warn = false;
> 
> /* SGX's EGETKEY(SEAL_KEY) uses three masks as key-derivation material:
> ```

NP: either add an empty line at the top of this comment or remove it from the end (former preferred by me).
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-16CEBpIadiKMv9en:-Mr-16CEBpIadiKMv9eo:b-x0deya) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L33)):*
> ```C
>  *   - KEYREQUEST.MISCMASK
>  *
>  * These default masks may be replaced by used-defined ones, correspondingly:
> ```

Please add some information that the list below are manifest keys.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-1QxIAGRe-EUkeWMj:-Mr-1QxIAGRe-EUkeWMk:b-cfsjmn) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L40)):*
> ```C
> uint64_t g_seal_key_flags_mask = SGX_FLAGS_MASK_CONST;
> uint64_t g_seal_key_xfrm_mask  = SGX_XFRM_MASK_CONST;
> uint32_t g_seal_key_misc_mask  = SGX_MISCSELECT_MASK_CONST;
> ```

Shouldn't these 3 be `static`? I don't see any usages outside of this file.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2UCgB7eAzz3RfMZ4:-Mr-2UCgB7eAzz3RfMZ5:bamk4nm) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L40)):*
> ```C
> uint64_t g_seal_key_flags_mask = SGX_FLAGS_MASK_CONST;
> uint64_t g_seal_key_xfrm_mask  = SGX_XFRM_MASK_CONST;
> uint32_t g_seal_key_misc_mask  = SGX_MISCSELECT_MASK_CONST;
> ```

We do have a special type for this `sgx_misc_select_t`.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1032 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-3TqtEZEep-SULQeR:-Mr-3TqtEZEep-SULQeS:bp0htwy) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L1032)):*
> ```C
>     free(mask_str);
>     return ret;
> }
> ```

I don't like this "advanced" parsing, I think a simple number would be enough. See the comment in documentation.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1034 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-4Hqo-Ji2xdb9SSNE:-Mr-4Hqo-Ji2xdb9SSNF:b-vo6a9w) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L1034)):*
> ```C
> }
> 
> int init_seal_key(void) {
> ```

Hm, this initializes seal key material, not the key itself (if there is a difference)


<!-- Sent from Reviewable.io -->

2021-12-16 09:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: 3 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr1VAFO8go8mZjrvlPX:b-ca9sfk) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Uh, why these do not have the leading `0x`? Actually why they are not just numbers (instead of hex strings)?
</blockquote></details>

I don't like them to be represented as numbers. I think masks should have a very specific format (they must be exactly 32/64 bits in size), and allowing to specify something like `sgx.seal_key.flags_mask = 123` will be abused by users in any possible way.

Having a strict 4/8-byte hex string seems like a natural fit for the mask, and some guarantee that users won't abuse this without understanding the consequences.

I can add the prefix `0x`, no problem. But I don't want to have it as a simple TOML number. So what would you recommend?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-0uwgA1aRL95AfdO3:-Mr1Ohaa5fmK37R8xO0o:b-gu810e) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: either add an empty line at the top of this comment or remove it from the end (former preferred by me).
</blockquote></details>

Done. Always forget about this.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-16CEBpIadiKMv9en:-Mr1PIqx1kCbsrcwWQSy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add some information that the list below are manifest keys.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-1QxIAGRe-EUkeWMj:-Mr1PRps27F01Cz9N_HU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't these 3 be `static`? I don't see any usages outside of this file.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2UCgB7eAzz3RfMZ4:-Mr1UOpB9nJ2Ai4qUdax:b-9i1akp) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We do have a special type for this `sgx_misc_select_t`.
</blockquote></details>

I don't like those types too much. We have a type for MISCSELECT and thus MISCMASK, but we don't have special types for FLAGS and XFRM. So I wanted to be uniform and use standard types.

But I added two static asserts to make it explicit.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1032 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-3TqtEZEep-SULQeR:-Mr1W1j-3Z1QIV4c4-dD:b-volb2) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L1032)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this "advanced" parsing, I think a simple number would be enough. See the comment in documentation.
</blockquote></details>

See my reply there.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1034 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-4Hqo-Ji2xdb9SSNE:-Mr1Uj4L408yiZ1_fsyu:b-1ijo5) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Pal/src/host/Linux-SGX/enclave_framework.c#L1034)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, this initializes seal key material, not the key itself (if there is a difference)
</blockquote></details>

Done. Fair enough, change the name.


<!-- Sent from Reviewable.io -->

2021-12-16 14:33 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr2dGdi2BZVccTZqDS7:bvzx4v2) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like them to be represented as numbers. I think masks should have a very specific format (they must be exactly 32/64 bits in size), and allowing to specify something like `sgx.seal_key.flags_mask = 123` will be abused by users in any possible way.

Having a strict 4/8-byte hex string seems like a natural fit for the mask, and some guarantee that users won't abuse this without understanding the consequences.

I can add the prefix `0x`, no problem. But I don't want to have it as a simple TOML number. So what would you recommend?
</blockquote></details>

The main problem with the current version is that I have no idea what the endianness is. Is the first nibble pair (byte) MSB (like it was a hex encoded number) or is it LSB (like it was hex encoded string/bytes array)?
But yeah, I see some value in the fact that the size must match (e.g. you cannot remove a leading `f` accidentally).


<!-- Sent from Reviewable.io -->

2021-12-17 10:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr6zrlH7RyLbjrgpYE5:bimshx5) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The main problem with the current version is that I have no idea what the endianness is. Is the first nibble pair (byte) MSB (like it was a hex encoded number) or is it LSB (like it was hex encoded string/bytes array)?
But yeah, I see some value in the fact that the size must match (e.g. you cannot remove a leading `f` accidentally).
</blockquote></details>

This string represents a number in LSB format.

So e.g. `fffffffffff9ff1b` is `1111111111111111111111111111111111111111111110011111111100011011` in binary.

Adding `0x` prefix would suffice for you? In addition, I can add the remark in the text about LSB.


<!-- Sent from Reviewable.io -->

2021-12-17 11:38 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr7ApgQ6gWAx2ovk1Jw:b9yzfsd) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This string represents a number in LSB format.

So e.g. `fffffffffff9ff1b` is `1111111111111111111111111111111111111111111110011111111100011011` in binary.

Adding `0x` prefix would suffice for you? In addition, I can add the remark in the text about LSB.
</blockquote></details>

I know, I was just pointing out it's not clear just from the manifest documentation.

Yeah, `0x` should be enough.


<!-- Sent from Reviewable.io -->

2021-12-17 12:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: 2 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/manifest-syntax.rst, line 541 at r1](https://reviewable.io/reviews/gramineproject/gramine/275#-Mr-2rpiACHJpsrNrAlf:-Mr7IaKJ1FhUS9cchV4E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c035f7ffbd34e3fd807de018802ebed9f6742c7/Documentation/manifest-syntax.rst#L541)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I know, I was just pointing out it's not clear just from the manifest documentation.

Yeah, `0x` should be enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 17:05 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-22 11:20 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-22 13:15 UTC, mkow requested changes
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXDUwWBoUNHpVo9DGF:b-oafylw) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
> ```reStructuredText
>     sgx.seal_key.flags_mask = "[8-byte hex value]"  (default: "0xffffffffffffffff")
>     sgx.seal_key.xfrm_mask  = "[8-byte hex value]"  (default: "0xfffffffffff9ff1b")
>     sgx.seal_key.misc_mask  = "[4-byte hex value]"  (default: "0xffffffff")
> ```

If these are valid hex numbers, then why are we passing them as strings? I guess because tomlc99 doesn't handle unsigned 64-bit numbers well?
If ints are actually possible to use then it would make `update_seal_key_mask()` much simpler.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 861 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDhoi62tDJcVv0vbL:-MrXDhoi62tDJcVv0vbM:b-7fnmtc) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/db_main.c#L861)):*
> ```C
>     g_pal_internal_mem_size = extra_mem_size + PAL_INITIAL_MEM_SIZE;
> 
>     /* seal-key material initialization must come before protected-files initialization */
> ```

We need some better way to assert dependencies in initialization order, but that's a bigger problem for another time...
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXFHp364xPYLf9CD2b:-MrXFHp364xPYLf9CD2c:bktw28i) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L45)):*
> ```C
> 
> static_assert(sizeof(g_seal_key_flags_mask) + sizeof(g_seal_key_xfrm_mask) ==
>         sizeof(sgx_attributes_t), "wrong types");
> ```

This indentation seems wrong
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1051 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXGYVNBSoJFJGuo3LV:-MrXGYVNBSoJFJGuo3LW:bsowowm) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L1051)):*
> ```C
> 
>     ret = update_seal_key_mask("sgx.seal_key.flags_mask", (uint8_t*)&g_seal_key_flags_mask,
>                                sizeof(g_seal_key_flags_mask));
> ```

This won't work on big-endian machines, because `update_seal_key_mask()` always writes the output in little-endian. We can probably silently assume little-endianness here because SGX works only on little endian, but it's quite ugly.


<!-- Sent from Reviewable.io -->

2021-12-22 13:42 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXMl9sEs1j0PmXBgda:b1wfjrq) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If these are valid hex numbers, then why are we passing them as strings? I guess because tomlc99 doesn't handle unsigned 64-bit numbers well?
If ints are actually possible to use then it would make `update_seal_key_mask()` much simpler.
</blockquote></details>

See the closed conversation (here and near parsing), we already talked about this
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1051 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXGYVNBSoJFJGuo3LV:-MrXMt2-41bWGiuShF0y:b-ehv57v) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L1051)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This won't work on big-endian machines, because `update_seal_key_mask()` always writes the output in little-endian. We can probably silently assume little-endianness here because SGX works only on little endian, but it's quite ugly.
</blockquote></details>

We assume that we are running on x64 everywhere in SGX code (which is a valid assumption, I believe :smiley: ), which is always little endian.


<!-- Sent from Reviewable.io -->

2021-12-22 13:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXP9kYA4ymPqSFhRl8:b-zavtxu) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

See the closed conversation (here and near parsing), we already talked about this
</blockquote></details>

Ok, I see, although I don't know why dropping the double quotes would change anything w.r.t. readability/ambiguity of this.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1051 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXGYVNBSoJFJGuo3LV:-MrXPTnz3XZjm2KP6c0_:b-7e4uag) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L1051)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We assume that we are running on x64 everywhere in SGX code (which is a valid assumption, I believe :smiley: ), which is always little endian.
</blockquote></details>

yeah, but I don't like that this is assumed so silently here


<!-- Sent from Reviewable.io -->

2021-12-22 13:59 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXQY9j-3e3Ne8qe1Oh:b-l19un1) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I see, although I don't know why dropping the double quotes would change anything w.r.t. readability/ambiguity of this.
</blockquote></details>

There is a check that the size of this string is exactly what's expected, so if you e.g. drop one `f` then it will complain loudly. At least I think that was the reasoning of @dimakuv for this


<!-- Sent from Reviewable.io -->

2021-12-22 15:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXcnhlA2IZ75gVK2QG:b-py3w1r) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
Yes, Borys is correct, that was my reasoning. Citing myself from a previous (resolved) discussion:

> I don't like them to be represented as numbers. I think masks should have a very specific format (they must be exactly 32/64 bits in size), and allowing to specify something like `sgx.seal_key.flags_mask = 123` will be abused by users in any possible way.

Basically, I want to force users to specify all bits explicitly. If users don't (the string is too short), then my parser will fail loudly.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXFHp364xPYLf9CD2b:-MrXdXV92htCW1lsthY1:bzabb07) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This indentation seems wrong
</blockquote></details>

Done. I wasn't sure how to indent it better. I think now is good enough.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1051 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXGYVNBSoJFJGuo3LV:-MrXdyXn43hQBIbFzgs_:bs6xkwd) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L1051)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

yeah, but I don't like that this is assumed so silently here
</blockquote></details>

Done. I added a comment (in case someone will want to copy it to some big-endian machine).


<!-- Sent from Reviewable.io -->

2021-12-22 15:05 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/manifest-syntax.rst, line 542 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXDUwWBoUNHpVo9DGE:-MrXf4fm0lP8XL91W_h1:b-nec2kw) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Documentation/manifest-syntax.rst#L542)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, Borys is correct, that was my reasoning. Citing myself from a previous (resolved) discussion:

> I don't like them to be represented as numbers. I think masks should have a very specific format (they must be exactly 32/64 bits in size), and allowing to specify something like `sgx.seal_key.flags_mask = 123` will be abused by users in any possible way.

Basically, I want to force users to specify all bits explicitly. If users don't (the string is too short), then my parser will fail loudly.
</blockquote></details>

Ok, makes sense.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/275#-MrXFHp364xPYLf9CD2b:-MrXfDzS7GN323IRCbgK:b-a8jcui) ([raw file](https://github.com/gramineproject/gramine/blob/a163844ab42285fe624d57d44a53973b685ce4fa/Pal/src/host/Linux-SGX/enclave_framework.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I wasn't sure how to indent it better. I think now is good enough.
</blockquote></details>

Yup, now it's good :)


<!-- Sent from Reviewable.io -->

2021-12-22 16:20 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-23 12:15 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/275)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-23 13:19 UTC, merged