[Pal] Refactor and rename global structures
gramineproject/gramine pull request #278
Opened 2021-12-13 21:30 UTC by mkow

## Description of the changes 

The new names should better reflect what these structures really are:
- `pal_linux_state` - PAL/Linux private state
- `pal_linuxsgx_state` - PAL/Linux-SGX private state
- `pal_common_state` - common state between all PALs, private
- `pal_public_state` - common state between all PALs, but public (shared with LibOS)

I made `private` and `uncommon` attributes implicit (i.e. not added to the names when they apply, instead adding only negations), to not make the names even longer, but if you have better ideas for consistent naming then I'm open for changing them. And `pal_public_state` already breaks this (should be `pal_common_public_state`), but that would be really long :/

Renamed/removed:
- `PAL_CONTROL` - No idea where this name came from, but it's actually a part of the PAL state which is visible by LibOS, so it was renamed to `pal_public_state`.
- `pal_sec` - Another riddle-name :) Partially un-globalled, mostly migrated to `pal_linuxsgx_state`, will be finally deleted in the next PR.
- `pal_internal_state` - Renamed to `pal_common_state`.

There's also a question whether something should be a global variable in PAL or a member of one of these structs. Technically all variables could be moved to "direct" globals or all moved to those global structs, but I think it's better to split them, and the question is how exactly. I'd put in these structs +/- only the state which sounds like global to the whole PAL, not just to a single submodule. But it's quite subjective and I'm not very convinced about this approach, so I'd like to hear your ideas (and whatever we choose, this is for future PRs, not this one).

This PR also makes passing of the initial state to the start ecall more explicit (previously `pal_sec` was partially used for this and partially for storing other global state).

The next step will be moving topology information to a separate struct and getting rid of `pal_sec`.

## How to test this PR? 

CI, no functional changes intended.

2021-12-14 04:19 UTC, boryspoplawski requested changes
> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mqr05JP-FOWPDV85p1F:ba0s3z7) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
> ```objc
>     uint64_t instance_id;
> 
>     /* Both of these are obviously untrusted on SGX, but we use them only for operations on the
> ```

1) Both? There are 4 items here
2) Why did you add these here? Previous `pal_internal_state` did not have them and they seem Linux specific (as comment above states). We have `pal_linux_state` or something similar for such stuff.
___
*[Pal/regression/pal_regression.h, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr10Oi80gTNOG7z7uL:-Mqr10Oi80gTNOG7z7uM:b-p1kghz) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/regression/pal_regression.h#L10)):*
> ```objc
> 
> // TODO: this needs to be fixed, it pretends to be a variable but it actually is a function call.
> #define pal_public_state (*DkGetPalPublicState())
> ```

Why not change it now? You've changed the name, so had to modify each usage anyway. It seems like you can just `s/pal_public_state\./DkGetPublicState()->/g`
___
*[Pal/src/host/Linux/pal_linux.h, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr3itr9Sya0jpVrPPn:-Mqr3itr9Sya0jpVrPPo:bfzrsfr) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux/pal_linux.h#L30)):*
> ```objc
> 
> extern struct pal_linux_state {
>     const char**    host_environ;
> ```

Why did you move them out? They seem to belong to this struct.


<!-- Sent from Reviewable.io -->

2021-12-14 10:52 UTC, pwmarcz requested changes
>I'd put in these structs +/- only the state which sounds like global to the whole PAL, not just to a single submodule.

You mean, keep variables like `static int g_foo;` as static, but move the ones used in many modules to one of the structures?

I think it's a good approach. Especially for the host-specific globals; it would make it clearer that they're host-specific.

> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278#-:-MqsZVLbD2INNHvg59Jh:b-q4qkno)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsUiUi5kUjSx6XOxDd):*
This is a big diff, and it would take me some time to determine what exactly was renamed. Can you add more information to this message? At least the list of new structures (`pal_public_state`, `pal_common_state` etc.)
___
*[Documentation/pal/host-abi.rst, line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsSJ318bTW_oyxJJbG:-MqsSJ318bTW_oyxJJbH:b5vs0ov) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L87)):*
> ```reStructuredText
> The control block in Gramine is a structure that provides static immutable
> information about the current process and its host. The address of the control
> block is resolved via :func:`DkGetPalPublicState()` and can be memorized in a global
> ```

I'm not sure if "state" is the best name here, given that the information is immutable. I don't have a better idea, though.

By the way, are all other structures immutable as well? (After the initial setup, of course).
___
*[Pal/regression/pal_regression.h, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr10Oi80gTNOG7z7uL:-MqsTNzgCK4l7R1Ls-ar:b-4ecu02) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/regression/pal_regression.h#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not change it now? You've changed the name, so had to modify each usage anyway. It seems like you can just `s/pal_public_state\./DkGetPublicState()->/g`
</blockquote></details>

+1. At first I thought it's a global variable and you didn't add `g_`.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsULwA5JM6RcZjpwmO:-MqsULwA5JM6RcZjpwmP:bvv7fng) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/host/Linux-SGX/pal_linux.h#L35)):*
> ```objc
> 
> /* Part of Linux-SGX PAL private state which is not shared with other PALs. */
> extern struct pal_linuxsgx_state {
> ```

Looking at all this code, `{g_}pal_linuxsgx_state` is tripping me up - the `linuxsgx` part is hard to read.

Maybe `g_pal_linux_sgx_state` would be better? (I'm not sure).


<!-- Sent from Reviewable.io -->

2021-12-14 11:52 UTC, dimakuv requested changes
I agree with Pawel.

> pal_linux_state - PAL/Linux private state
> pal_linuxsgx_state - PAL/Linux-SGX private state

While I agree with the general naming scheme, this notation `pal_{name}_state` is a bit cumbersome. Technically, these structs are only used inside a PAL-specific directory (e.g. `Pal/host/Linux`), and the naming feels redundant. I would prefer a uniform name `pal_specific_state` (or something similar), where all PAL-specific fields will be located.

But I don't insist, maybe it's just me.

> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278#-:-Mqsl1q92IvDS7UhrALo:b-nt42d9)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Documentation/pal/host-abi.rst, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrwPV28sdc4iVLeFLd:-MqrwPV28sdc4iVLeFLe:b9mmsds) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L82)):*
> ```reStructuredText
>    :members:
> 
> Gramine control block
> ```

It's not really `control block` anymore, it is `Gramine PAL (public) state`. Please rename everywhere in this doc.
___
*[Documentation/pal/host-abi.rst, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrwsbDCqJLH4jagIoc:-MqrwsbDCqJLH4jagIod:bkhje52) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L90)):*
> ```reStructuredText
> variable for ease of use.
> 
> The fields of the Gramine control block are defined as follows:
> ```

This list doesn't make sense. `PAL_CONTROL` (now `pal_public_state`) is a struct that *contains* `PAL_*_INFO` fields.

I guess we need to split this list into two paragraphs. One just gives fields of `PAL_CONTROL` (now `pal_public_state`). Another one talks about sub-fields of the fields `PAL_CPU_INFO`, ...
___
*[Pal/include/pal_internal.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqrxsir5I0-QahuhLEC:-Mqrxsir5I0-QahuhLED:b-kaoqlm) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L28)):*
> ```objc
>  * Part of PAL state which is common to all PALs (trusted part, in case of TEE PALs).
>  * Most of it is actually very Linux-specific, we'll need to refactor it if we ever add a non-Linux
>  * PAL.
> ```

This can happen pretty soon :) Could you add a TODO/FIXME here?
___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-MqryABBBGJ34NlvcYHU:b-4jkv37) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) Both? There are 4 items here
2) Why did you add these here? Previous `pal_internal_state` did not have them and they seem Linux specific (as comment above states). We have `pal_linux_state` or something similar for such stuff.
</blockquote></details>

I agree with Borys. But I would go even further and completely decouple them -- you spend more LoCs explaining them in your comments than simply duplicating them (from what I see, e.g. `host_environ` is not even used in Linux-SGX PAL).

Also, in new PALs (think of Gramine-VM), we don't have "host environment variables" etc, so these fields will be useless.
___
*[Pal/include/pal/pal.h, line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrzD-YBcO0d6o_fKD8:-MqrzD-YBcO0d6o_fKD9:bpmfr80) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal/pal.h#L113)):*
> ```objc
> 
> /* Part of PAL state which is shared between all PALs and accessible (read-only) by the code run by
>  * PAL (usually our LibOS). */
> ```

`by the code run by PAL` is ambigious. Maybe `by the binary started by PAL` or `by the entrypoint loaded by PAL`?
___
*[Pal/regression/pal_regression.h, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr10Oi80gTNOG7z7uL:-MqrzcVD44XgPv-lXQmR:b-eevk75) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/regression/pal_regression.h#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

+1. At first I thought it's a global variable and you didn't add `g_`.
</blockquote></details>

+1. When I wrote that hack, I didn't want to modify any regression tests' sources (well, at that time I really hated PAL regression tests and wanted them to be removed :)). Now you modify them anyway, so let's just use the function.
___
*[Pal/src/db_main.c, line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-3jt5xDsv6EUJABX:-Mqs-3jt5xDsv6EUJABY:btz0jrh) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L29)):*
> ```C
> }
> 
> struct pal_common_state g_pal_common_state;
> ```

Maybe move it right-after includes? Right now it's weirdly situated in-between two functions.
___
*[Pal/src/db_main.c, line 529 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-Sai1CnldY1nn_x9:-Mqs-Sai1CnldY1nn_xA:b44nbsa) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L529)):*
> ```C
> 
>     g_pal_public_state.host_type       = XSTRINGIFY(HOST_TYPE);
>     g_pal_public_state.manifest_root   = g_pal_common_state.manifest_root;
> ```

Why do we need this duplication? Why not init `g_pal_public_state` immediately?
___
*[Pal/src/db_main.c, line 537 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-YS32dMibe3OO7yh:-Mqs-YS32dMibe3OO7yi:b44nbsa) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L537)):*
> ```C
>                                     &g_pal_public_state.user_address.end);
> 
>     g_pal_public_state.alloc_align = g_pal_common_state.alloc_align;
> ```

Why do we need this duplication? Why not init `g_pal_public_state` immediately?
___
*[Pal/src/host/Linux/db_main.c, line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsiXtu9jf0TMHyzr7E:-MqsiXtu9jf0TMHyzr7F:b-utao28) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/host/Linux/db_main.c#L44)):*
> ```C
> const size_t g_page_size = PRESET_PAGESIZE;
> 
> static void read_args_from_stack(void* initial_rsp, int* out_argc, const char*** out_argv,
> ```

Maybe also change a name? Like `read_info_from_stack`?
___
*[Pal/src/host/Linux/db_threading.c, line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsiwyuENBSUe_Zdm2c:-MqsiwyuENBSUe_Zdm2d:bi6dz8s) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/host/Linux/db_threading.c#L27)):*
> ```C
> 
> /* Linux PAL cannot use mmap/unmap to manage thread stacks because this may overlap with
>  * pal_public_state.user_address. Linux PAL also cannot just use malloc/free because DkThreadExit
> ```

`g_` missing?
___
*[Pal/src/host/Linux/pal_linux.h, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr3itr9Sya0jpVrPPn:-Mqsj1hJEQJXAbaYyECR:b-5kx2ei) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/Pal/src/host/Linux/pal_linux.h#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you move them out? They seem to belon [...]

2021-12-16 18:52 UTC, mkow reviewed
> You mean, keep variables like `static int g_foo`; as static, but move the ones used in many modules to one of the structures?

Yup, something like this. Ofc with possible exceptions, we'll decide case-by-case.

> I would prefer a uniform name `pal_specific_state` (or something similar), where all PAL-specific fields will be located.

I thought about something like this, but having multiple structures and functions with the same name and different contents is a bit PITA when changing the code (e.g. when grepping for something). But that's not a strong preference. What do others think?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278#-:-Mr33N7A3MkhSOGcbxi-:b-xagwu5)* status: 43 of 66 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsUiUi5kUjSx6XOxDd):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a big diff, and it would take me some time to determine what exactly was renamed. Can you add more information to this message? At least the list of new structures (`pal_public_state`, `pal_common_state` etc.)
</blockquote></details>

Done. I moved here a part of the PR description, is this enough?
___
*[Documentation/pal/host-abi.rst, line 82 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrwPV28sdc4iVLeFLd:-Mr36ezZ3Ob4B_RqOxqv:b-n7vh9r) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's not really `control block` anymore, it is `Gramine PAL (public) state`. Please rename everywhere in this doc.
</blockquote></details>

Oh, right, I missed this whole thing here.
___
*[Documentation/pal/host-abi.rst, line 87 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsSJ318bTW_oyxJJbG:-Mr37hH63NOLpXCDoJcb:b5pdo57) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L87)):*
Good point, "state" doesn't connect well with "immutable". But I'd leave it for uniformity with the naming of the rest of the global structures.

> By the way, are all other structures immutable as well? (After the initial setup, of course).

I think this is the case currently, although it may change if we add support for hot-plug in topology.
___
*[Documentation/pal/host-abi.rst, line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrwsbDCqJLH4jagIoc:-Mr3C25o94sYJNIfLPGl:b-y538cy) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Documentation/pal/host-abi.rst#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This list doesn't make sense. `PAL_CONTROL` (now `pal_public_state`) is a struct that *contains* `PAL_*_INFO` fields.

I guess we need to split this list into two paragraphs. One just gives fields of `PAL_CONTROL` (now `pal_public_state`). Another one talks about sub-fields of the fields `PAL_CPU_INFO`, ...
</blockquote></details>

What about now? I moved them into a sub-sub-sub-sub-sub-section ;) Anyways, in the next PR I want to create just a single "topology structure" to cover all of this.
___
*[Pal/include/pal_internal.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqrxsir5I0-QahuhLEC:-Mr3DvjvCIwbXMQAoYBz:bhfgl6u) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can happen pretty soon :) Could you add a TODO/FIXME here?
</blockquote></details>

Hmm, but it's not a "TODO" in the current state of the project, i.e. for me a "TODO" suggest that this is something actionable - something we should fix when we find some time for it. But here it's something which makes sense to change only after we add another PAL.
___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mr3F5Xw48LOmU82rV88:b93y6un) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
> Both? There are 4 items here

Fixed.

> Why did you add these here? Previous `pal_internal_state` did not have them and they seem Linux specific (as comment above states). We have `pal_linux_state` or something similar for such stuff.

But what do you propose? To duplicate them to both `pal_linux_state` and `pal_linuxsgx_state`?

> Also, in new PALs (think of Gramine-VM), we don't have "host environment variables" etc, so these fields will be useless.

Yeah, but adding this PAL will require much bigger rework of PAL anyways, I think.
I missed that `host_environ` and `host_pid` are used only on Linux, fixed.
___
*[Pal/include/pal/pal.h, line 113 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqrzD-YBcO0d6o_fKD8:-Mr3I9wp64Mkr_PpnZRh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal/pal.h#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`by the code run by PAL` is ambigious. Maybe `by the binary started by PAL` or `by the entrypoint loaded by PAL`?
</blockquote></details>

Done.
___
*[Pal/regression/pal_regression.h, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr10Oi80gTNOG7z7uL:-Mr3Julf1ArHWE4qOkXH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/regression/pal_regression.h#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. When I wrote that hack, I didn't want to modify any regression tests' sources (well, at that time I really hated PAL regression tests and wanted them to be removed :)). Now you modify them anyway, so let's just use the function.
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 29 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-3jt5xDsv6EUJABX:-Mr3JzsN1VDN3MCZCWuD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe move it right-after includes? Right now it's weirdly situated in-between two functions.
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 529 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-Sai1CnldY1nn_x9:-Mr3L7yb-Le7cqjGV-Dt:b-66313w) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L529)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this duplication? Why not init `g_pal_public_state` immediately?
</blockquote></details>

No idea, here I only applied the renaming. I guess it doesn't make sense, let me change it...
___
*[Pal/src/db_main.c, line 537 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqs-YS32dMibe3OO7yh:-Mr3Rkae3Y_7M_1tKX3U:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/db_main.c#L537)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this duplication? Why not init `g_pal_public_state` immediately?
</blo [...]

2021-12-17 09:52 UTC, pwmarcz approved these changes
I'd also like to have different-named structures rather than `pal_specific_state`. Not only it's easier to grep, it's also easier to read such code (you don't need to remember that because we're in this directory, *this* `pal_specific_state` has such-and-such fields), and probably also easier to talk about it.

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278#-:-Mr6kT_YCY476KOz6LDK:b-4nb0d6)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsUiUi5kUjSx6XOxDd):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done. I moved here a part of the PR description, is this enough?
</blockquote></details>

Looks good to me, thanks.
___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mr6mCJv8FpdTJNuCuO2:bj8510b) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Both? There are 4 items here

Fixed.

> Why did you add these here? Previous `pal_internal_state` did not have them and they seem Linux specific (as comment above states). We have `pal_linux_state` or something similar for such stuff.

But what do you propose? To duplicate them to both `pal_linux_state` and `pal_linuxsgx_state`?

> Also, in new PALs (think of Gramine-VM), we don't have "host environment variables" etc, so these fields will be useless.

Yeah, but adding this PAL will require much bigger rework of PAL anyways, I think.
I missed that `host_environ` and `host_pid` are used only on Linux, fixed.
</blockquote></details>

I'd also be careful about putting too much Linux-specific stuff in the common part. I agree we need to deduplicate `Linux` and `Linux-SGX` but the way to go is to use `Linux-common`.

Still, it's probably not a good solution here (we would need to add *another* global structure), so I don't have a strong opinion of what to do here. Keeping these variables duplicated is fine for me, keeping them here is also fine (as long as we revisit that once we add a non-Linux PAL).
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsULwA5JM6RcZjpwmO:-Mr6nJIH7XoKkcyMcS2T:b-42ap4u) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/host/Linux-SGX/pal_linux.h#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's a bit easier to read for me if the structure is like `{toplevel_component}_{pal_name}_{struct_purpose}`. But also no strong preference.
@boryspoplawski any thoughts?
</blockquote></details>

If nobody else is bothered by it, let's leave it this way. I agree with the argument about structure.


<!-- Sent from Reviewable.io -->

2021-12-17 10:40 UTC, dimakuv submitted a review, later dismissed
Ok, then I concur.

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278#-:-Mr6wlpKDOnAfnYGoJe8:b-p498c5)* status: all files reviewed, 3 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal_internal.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqrxsir5I0-QahuhLEC:-Mr6xKCh9hrtGI8goHcF:bs4ixp3) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but it's not a "TODO" in the current state of the project, i.e. for me a "TODO" suggest that this is something actionable - something we should fix when we find some time for it. But here it's something which makes sense to change only after we add another PAL.
</blockquote></details>

OK, fair enough.
___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mr6xd1N-WJUbzFAgXI0:bolx4vb) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'd also be careful about putting too much Linux-specific stuff in the common part. I agree we need to deduplicate `Linux` and `Linux-SGX` but the way to go is to use `Linux-common`.

Still, it's probably not a good solution here (we would need to add *another* global structure), so I don't have a strong opinion of what to do here. Keeping these variables duplicated is fine for me, keeping them here is also fine (as long as we revisit that once we add a non-Linux PAL).
</blockquote></details>

I'm fine with the current state now.


<!-- Sent from Reviewable.io -->

2021-12-17 11:26 UTC, boryspoplawski requested changes
> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, 1 unresolved discussion, "squash! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mr75VBj4cZDvmiRNsPS:b69wlcq) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
> But what do you propose? To duplicate them to both pal_linux_state and pal_linuxsgx_state?

Yes. I would move the remaining Linux specific fields to PAL specific structs (duplicating them).
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 35 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-MqsULwA5JM6RcZjpwmO:-Mr78-sO-Ze7IAbUXRm-:b-3opnz5) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/src/host/Linux-SGX/pal_linux.h#L35)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If nobody else is bothered by it, let's leave it this way. I agree with the argument about structure.
</blockquote></details>

I don't mind either version


<!-- Sent from Reviewable.io -->

2021-12-17 11:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: 59 of 66 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/include/pal_internal.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/278#-Mqr05JO3HkEe5eyUF_S:-Mr7FXfxAVlbo7dnhU55:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/672e5300fec61b9489822dfac69079b0f145724a/Pal/include/pal_internal.h#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But what do you propose? To duplicate them to both pal_linux_state and pal_linuxsgx_state?

Yes. I would move the remaining Linux specific fields to PAL specific structs (duplicating them).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 12:02 UTC, dimakuv submitted a review, later dismissed
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-12-17 12:30 UTC, boryspoplawski approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-17 14:18 UTC, pwmarcz approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-20 23:06 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-12-21 08:03 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-21 08:08 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/278)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-21 08:17 UTC, merged