Take `g_dcache_lock` in dentry-related functions
gramineproject/gramine pull request #282
Opened 2021-12-15 09:54 UTC by pwmarcz

## Description of the changes 

This commit makes holding `g_dcache_lock` mandatory when calling `path_lookupat`, `dentry_open` and dentry callbacks (`shim_d_ops`). The callbacks are now also better documented.

This is in preparation for removing the per-object dentry lock (`shim_dentry.lock`), and later, switching to inodes. It should also make the filesystem functions less prone to race conditions.

Context: #279 (inodes migration). Should also help with https://github.com/gramineproject/graphene/issues/944 (but since I touch only some of the filesystem code, I won't claim it's fixed yet).

## How to test this PR? 

I spent some time making sure the callbacks are called according to documentation; I would be grateful for a double-check.

2021-12-16 10:13 UTC, dimakuv requested changes
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dKKw3TkT8AzIfVhV:-Mr1dKKw3TkT8AzIfVhW:b-k33rnd) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L220)):*
> ```objc
> 
>     /* detach internal data from dentry */
>     int (*dput)(struct shim_dentry* dent);
> ```

How is this unused? Don't we need to free resources of `dent`?
___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1b1Wh8faEhJb3QaxY:-Mr1b1Wh8faEhJb3QaxZ:b4rd7bt) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L238)):*
> ```objc
>      * \brief Create and open a new regular file
>      *
>      * \param hdl a newly created handle
> ```

You're missing description of `dir` param.
___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dQH88xKphtZZWTX4:-Mr1dQH978LNm8hiI72F:bo89qey) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L238)):*
> ```objc
>     int (*follow_link)(struct shim_dentry* dent, char** out_target);
>     /* set up symlink name to a dentry */
>     int (*set_link)(struct shim_dentry* dent, const char* link);
> ```

This was never used?
___
*[LibOS/shim/include/shim_fs.h, line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1b8kn6-6OiNtks3Z6:-Mr1b8kn6-6OiNtks3Z7:b-qkkiqa) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L241)):*
> ```objc
>      * \param dent dentry, valid and negative
>      * \param flags open flags, including access mode (O_RDONLY / O_WRONLY / O_RDWR)
>      * \param perm permissions of the new file
> ```

No such param
___
*[LibOS/shim/include/shim_fs.h, line 242 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dSrR6cbx5CrEdXcR:-Mr1dSrR6cbx5CrEdXcS:bcpblb4) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L242)):*
> ```objc
>     /* change the mode or owner of a file; the caller has to update dentry */
>     int (*chmod)(struct shim_dentry* dent, mode_t perm);
>     int (*chown)(struct shim_dentry* dent, int uid, int gid);
> ```

We don't emulate this? I thought we have (dummy) emulation of `chown()` syscall.
___
*[LibOS/shim/include/shim_fs.h, line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1blct0PfUsst7WXYr:-Mr1blct0PfUsst7WXYs:b-z1hl2s) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L264)):*
> ```objc
>      * dentry (as in `lookup`).
>      */
>     int (*mkdir)(struct shim_dentry* dent, mode_t perm);
> ```

I'm confused here. What is `dent` -- the directory-to-be-created or the parent directory? If the former, then the caller is supposed to prepare the dentry for consumption by `mkdir()`, right? But you don't describe how it should be prepared. If the latter, then how do we know the dir name?

The previous function signature was intuitively understandable to me. The new signature I don't get without more comments.

UPDATE: Actually, `dir` was unused even in the previous code. So `dent` is a directory-to-be-created. Could you make it a bit more explicit in the comment?
___
*[LibOS/shim/include/shim_fs.h, line 271 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cOJ90sUTMTSczPoX:-Mr1cOJ90sUTMTSczPoY:b-jc39rx) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L271)):*
> ```objc
>      * \param dent dentry, valid and non-negative, must have a parent
>      *
>      * Unlinks a file under `dent`. Note that there might be handles for that file; if possible,
> ```

I don't like the word `under`. Maybe `represented by`? Or `corresponding to`?
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1c_b32wYyrEazEFmI:-Mr1c_b32wYyrEazEFmJ:b-xdvota) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L282)):*
> ```objc
>      * \brief Get file status
>      *
>      * \param dentry, valid and non-negative
> ```

You should add `\param buf`
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cmozCZYa1Pu94p2E:-Mr1cmozCZYa1Pu94p2F:bl2ysn) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L282)):*
> ```objc
>      * \brief Get file status
>      *
>      * \param dentry, valid and non-negative
> ```

`\param dentry,` -> `\param dent dentry,`
___
*[LibOS/shim/include/shim_fs.h, line 295 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cx6fAcilPCqgSc6D:-Mr1cx6fAcilPCqgSc6E:b-5gizpd) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L295)):*
> ```objc
>      *
>      * \param dent dentry, valid and non-negative, describing a symlink
>      * \param[out] out_target on success, contains link target
> ```

Ideally, we should reshuffle and rename all functions' arguments here to have `out_` prefix.

Here, you don't really need `[out]` specifier -- the arg name already tells us that.
___
*[LibOS/shim/include/shim_fs.h, line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dfz95jjXeKi6h4oV:-Mr1dfz95jjXeKi6h4oW:b-yz7ure) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L311)):*
> ```objc
>      * Changes the permissions for a file.
>      *
>      * The caller should hold `g_dcache_lock`. On success, the caller should update `dent->perm`.
> ```

`The caller should update`? Isn't it what this function is supposed to do?
___
*[LibOS/shim/include/shim_fs.h, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dsnT910b_W-1wxUe:-Mr1dsnT910b_W-1wxUf:bu4z0l1) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L321)):*
> ```objc
>      * \param new target dentry, valid, can be negative or non-negative
>      *
>      * Renames a file under `old` to the path described by `new`. Updates the fields of `new` (same
> ```

I don't like the word `under`. Maybe `described by`?
___
*[LibOS/shim/include/shim_fs.h, line 335 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1e8YmD2TpxdpfsDll:-Mr1e8YmD2TpxdpfsDlm:b-8d9nr5) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L335)):*
> ```objc
>      * \brief List all files in the directory
>      *
>      * \param dentry the dentry, must be valid, non-negative and describing a directory
> ```

`dentry` -> `dent`
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1gHEh1lJh7gw3Eje2:-Mr1gHEh1lJh7gw3Eje3:budokva) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/src/fs/shim_fs_pseudo.c#L143)):*
> ```C
>     }
>     hdl->flags = flags;
>     hdl->acc_mode = ACC_M [...]

2021-12-17 11:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: 15 of 20 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dKKw3TkT8AzIfVhV:-Mr6oCjKCuCgspMBUs_t:b-ptmoj6) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is this unused? Don't we need to free resources of `dent`?
</blockquote></details>

Yes, I think the intention was to free `dent->data` (which currently leaks), but this callback wasn't called.

I tried to fix it before, but at the time ran into problems because some filesystems had really weird ownership patterns. Now, having rewritten much of that code, I should be able to add the `dput` callback. But my plan is to remove `dent->data` and replace it with `inode->data`, so don't want to have to fix it twice.

(There's a similar issue with migrating dentry data, I also want to fix it for inodes).
___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1b1Wh8faEhJb3QaxY:-Mr6pm4l8VMCpAYXBL31:bnwfjfu) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're missing description of `dir` param.
</blockquote></details>

Right. I actually forgot to remove it: the callbacks don't use it, and there's `dent->parent` for that. Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dQH88xKphtZZWTX4:-Mr6uYev61WYltyJRBqT:b4jz2pa) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was never used?
</blockquote></details>

I think so. It would be used for the `symlink()` syscall but we never supported it. We only have symlinks in pseudo-FSes like `/proc`.
___
*[LibOS/shim/include/shim_fs.h, line 241 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1b8kn6-6OiNtks3Z6:-Mr6q6VjA8Velmsli4WO:b88ksxk) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L241)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No such param
</blockquote></details>

I forgot to rename `mode` below. Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 242 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dSrR6cbx5CrEdXcR:-Mr6vqXm9TEWW397oKy3:b-crvacy) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L242)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't emulate this? I thought we have (dummy) emulation of `chown()` syscall.
</blockquote></details>

We do, but it doesn't even call a callback (and I think that's fine).
___
*[LibOS/shim/include/shim_fs.h, line 264 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1blct0PfUsst7WXYr:-Mr6qs5q4hxaP1pEhfYp:b-3o15qk) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L264)):*
>I'm confused here. What is dent -- the directory-to-be-created or the parent directory? If the former, then the caller is supposed to prepare the dentry for consumption by `mkdir()`, right? But you don't describe how it should be prepared.

The former. I don't describe how, because this is filesystem-specific: for some filesystems, it might involve updating some stuff in `data` or handling the inode (at least for now); for others, `dent` might require no extra preparation.

All these functions (lookup, creat, mkdir) follow the same pattern: they receive a dentry, and create a new file in place pointed to by that dentry. I tried to make that more clear in the description.
___
*[LibOS/shim/include/shim_fs.h, line 271 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cOJ90sUTMTSczPoX:-Mr6rm-z4cthoCbP_Y4D:b-wgyi3t) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the word `under`. Maybe `represented by`? Or `corresponding to`?
</blockquote></details>

Changed to `described by` throughout this PR.
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1c_b32wYyrEazEFmI:-Mr6rzN59NLSi_LwC9w6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should add `\param buf`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cmozCZYa1Pu94p2E:-Mr6rzgT-jTRO6X_lb-Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`\param dentry,` -> `\param dent dentry,`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 295 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cx6fAcilPCqgSc6D:-Mr6s9yAAgwPVU2GeaMj:btm9ruc) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L295)):*
>Ideally, we should reshuffle and rename all functions' arguments here to have `out_` prefix.

If you mean `dent`, I disagree. The `dent` parameter is both read and written to, and it's usually the main object (in OOP way). Also, the rule (perhaps implicit) that I've been following is to only treat output *pointers* this way:

```c
/* these functions act on existing objects: */
int lookup(struct shim_dentry* dent);
int open(struct shim_dentry* dent, ...);
ssize_t read(..., void* buf, size_t size);

/* these functions retrieve or create new objects: */
int path_lookupat(..., struct shim_dentry** out_dent);
int follow_link(..., char** out_target);
```

>Here, you don't really need `[out]` specifier -- the arg name already tells us that.

OK, removed.
___
*[LibOS/shim/include/shim_fs.h, line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dfz95jjXeKi6h4oV:-Mr6uxdTABBGj2dwZBq6:bucmrip) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`The caller should update`? Isn't it what this function is supposed to do?
</blockquote></details>

No. The idea is that these callbacks do only filesystem-specific processing, e.g. `chmod` will call `DkStreamAttributesSetByHandle`. Any updates that we always do (like updating `perm`, or marking the dentry as valid) are done in the general FS layer: this way, there's less duplication and less opportunities to get them wrong.
___
*[LibOS/shim/include/shim_fs.h, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dsnT910b_W-1wxUe:-Mr6wEQ79su7U [...]

2021-12-17 11:59 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dKKw3TkT8AzIfVhV:-Mr7Cbm962fY44zP7_x6:b2jcqbx) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/include/shim_fs.h#L220)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, I think the intention was to free `dent->data` (which currently leaks), but this callback wasn't called.

I tried to fix it before, but at the time ran into problems because some filesystems had really weird ownership patterns. Now, having rewritten much of that code, I should be able to add the `dput` callback. But my plan is to remove `dent->data` and replace it with `inode->data`, so don't want to have to fix it twice.

(There's a similar issue with migrating dentry data, I also want to fix it for inodes).
</blockquote></details>

OK, thanks, makes sense.
___
*[LibOS/shim/include/shim_fs.h, line 295 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1cx6fAcilPCqgSc6D:-Mr7DHjp4I0dDXTNbOcG:b-1bxhqp) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L295)):*
> If you mean dent, I disagree. The dent parameter is both read and written to, and it's usually the main object (in OOP way). Also, the rule (perhaps implicit) that I've been following is to only treat output pointers this way

I agree with you. I didn't mean `dent` here. I meant e.g. `creat(hdl)` above, but I now see that all these objects are already created by the caller (so all these dent callbacks manipulate the objects in-place). So it looks like there are no other func arguments that require the `out_` prefix.
___
*[LibOS/shim/include/shim_fs.h, line 311 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1dfz95jjXeKi6h4oV:-Mr7Djqa7apJfjhdVh-x:b-4kemyk) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/include/shim_fs.h#L311)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No. The idea is that these callbacks do only filesystem-specific processing, e.g. `chmod` will call `DkStreamAttributesSetByHandle`. Any updates that we always do (like updating `perm`, or marking the dentry as valid) are done in the general FS layer: this way, there's less duplication and less opportunities to get them wrong.
</blockquote></details>

Ok, got it now.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 268 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1fPZmCD74kCVdYN14:-Mr7E9M39_YFQ_1B_h88:b8e68l4) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/src/fs/chroot/fs.c#L268)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Why don't you have `assert(locked(&g_dcache_lock));`?

Because I'm not accessing any fields that, *by current rules*, require this lock. I could add such assert, but the code here doesn't need it.

We really only require `g_dcache_lock` for dentry structure, i.e. children/siblings and possibly `state`. It's still pretty broken but I'm fixing it step by step. This commit does not change the locking *rules* except for calling the callbacks under `g_dcache_lock`.

>Is this because you still have `dent->lock` here, and you don't want to have deadlocks/weirdness by introducing another lock?

The assert wouldn't introduce any new deadlock or behavior change, right?

The `dent->lock` is here, because (by current rules) it protects `dent->inode`.

>Then your commit description and comments in `shim_d_ops` are incorrect.

Which part is incorrect? I claim to call callbacks with `g_dcache_lock`, not to change other rules for using this lock.

>Please either add some `FIXME` comments here, or make it explicit in the commit description/`shim_d_ops` that we are in transition state.

I added a comment to the top of `shim_dentry` about the current state.
</blockquote></details>

OK, understood now.
___
*[LibOS/shim/src/sys/shim_stat.c, line 276 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1iHtw8dk-Y4BhHzpf:-Mr7FWup0aHP_cxVTNK7:bi28oj5) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/src/sys/shim_stat.c#L276)):*
> It looks like I also overlooked the stat() call above.

What do you mean by this? `d_ops->stat()` call? But it looks the same to me, the old version and the new version.
___
*[LibOS/shim/src/sys/shim_stat.c, line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr7EfbG8Ksuw0lHYhLL:-Mr7EfbG8Ksuw0lHYhLM:b-qykaan) ([raw file](https://github.com/gramineproject/gramine/blob/5ad2889a3c42a76621a4d3b373b65e6f6e83b65e/LibOS/shim/src/sys/shim_stat.c#L266)):*
> ```C
>     }
>     if (!*pathname && !(flags & AT_EMPTY_PATH))
>         return -ENOENT;
> ```

But you already have this check two lines below.


<!-- Sent from Reviewable.io -->

2021-12-17 14:23 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_stat.c, line 276 at r1](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr1iHtw8dk-Y4BhHzpf:-Mr7kwhN0-iUlze1e89d:b-7e9nif) ([raw file](https://github.com/gramineproject/gramine/blob/09f3e26ff60e4a355f3722abde511d7ca72376d5/LibOS/shim/src/sys/shim_stat.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> It looks like I also overlooked the stat() call above.

What do you mean by this? `d_ops->stat()` call? But it looks the same to me, the old version and the new version.
</blockquote></details>

I meant the `d_ops->stat()` call in the "empty path" branch (`if (!*pathname))`). It was called without holding the lock.

(I wonder if there's some static analysis tool that would help us here... I heard Linux has something but I haven't looked at it).
___
*[LibOS/shim/src/sys/shim_stat.c, line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/282#-Mr7EfbG8Ksuw0lHYhLL:-Mr7knWu8Ct3DEfjdOtM:bcfilrl) ([raw file](https://github.com/gramineproject/gramine/blob/5ad2889a3c42a76621a4d3b373b65e6f6e83b65e/LibOS/shim/src/sys/shim_stat.c#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you already have this check two lines below.
</blockquote></details>

Oops! Yes, that's a leftover from when I hoped to fit this in single fuction. Removed.


<!-- Sent from Reviewable.io -->

2021-12-17 14:36 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-27 10:10 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/282)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-27 10:45 UTC, merged