[LibOS] fs_lock: Use a separate lock for all operations
gramineproject/gramine pull request #283
Opened 2021-12-15 10:24 UTC by pwmarcz

## Description of the changes 

Instead of using `shim_dentry.lock` for data stores in individual dentries, we use a global local (`g_fs_lock_lock`) for all fs_lock
related operations. This is in preparation for removing `shim_dentry.lock`.

Context: #279.

I realize that using a lock for guarding access on another object (`shim_dentry`) doesn't look nice. However, I tried the alternative (taking the global lock for dentries, `g_dcache_lock`) and it breaks because of the spaghetti in filesystem code[1]. While I could probably work around this specific issue, I think it's better to keep this module separate (i.e. using its own lock) so that it's easier to reason about.

[1] If you want to know the gory details, it was `shim_pipe`: because it uses extra file descriptor, the callback for `open` actually "closes" one of these artificial file descriptors, triggering fs_lock while we're already holding `g_dcache_lock`. Because we don't expect to be holding `g_dcache_lock` at this stage, we try to lock it for the second time. IMO `shim_pipe` breaks some implicit assumptions here, but there might be more places like this.

## How to test this PR? 

CI should be enough.

2021-12-16 10:19 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/283)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/283#-Mr1jIWWBBbNJc76dfF1:-Mr1jIWWBBbNJc76dfF2:br53th6) ([raw file](https://github.com/gramineproject/gramine/blob/7d21531b80ad69becdec9309aa3b79a3b12e6cc8/LibOS/shim/src/fs/shim_fs_lock.c#L15)):*
> ```C
> /*
>  * Global lock for the whole subsystem. Protects access to `g_fs_lock_list`, and also to dentry
>  * fields (`fs_lock and `maybe_has_fs_locks`).
> ```

Missing closing backtick in `fs_lock`
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 628 at r1](https://reviewable.io/reviews/gramineproject/gramine/283#-Mr1jpbk5PoOUzzJ557R:-Mr1jpbk5PoOUzzJ557S:b3safci) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/src/fs/shim_fs_lock.c#L628)):*
> ```C
>     *out_dents = dents;
>     return 0;
> }
> ```

I guess removing this two-phase deletion of fs locks is a huge benefit of this PR. I'm pretty sure the performance overhead of a single global lock is negligible in real-world cases.


<!-- Sent from Reviewable.io -->

2021-12-17 14:32 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/283)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/283#-Mr1jIWWBBbNJc76dfF1:-Mr7lvYs-CW5aPH2H5_t:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/7d21531b80ad69becdec9309aa3b79a3b12e6cc8/LibOS/shim/src/fs/shim_fs_lock.c#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Missing closing backtick in `fs_lock`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 628 at r1](https://reviewable.io/reviews/gramineproject/gramine/283#-Mr1jpbk5PoOUzzJ557R:-Mr7lysCET_1owyQ60Ni:b-r2hcqy) ([raw file](https://github.com/gramineproject/gramine/blob/63a73ae54c25eb0490c9fb0633d9b96db7cd72ed/LibOS/shim/src/fs/shim_fs_lock.c#L628)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess removing this two-phase deletion of fs locks is a huge benefit of this PR. I'm pretty sure the performance overhead of a single global lock is negligible in real-world cases.
</blockquote></details>

Yes, I'm happy about it. But also about untangling this module from the rest of the system, it's more independent now.

I think a global lock could have an impact on performance if an application takes many locks for various ranges of a single file (since lock operations are `O(n)` in the number of file ranges). But I'm not sure how likely that is, and anyway, to fix it we'd also need to rewrite the lock list to something else.


<!-- Sent from Reviewable.io -->

2021-12-17 14:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/283)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-27 11:03 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/283)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-27 11:31 UTC, merged