[Pal/Linux-SGX] Improve readability of enclave_entry.S
gramineproject/gramine pull request #291
Opened 2021-12-20 11:42 UTC by dimakuv

## Description of the changes 

This PR adds more explanatory comments and mends them to be more uniform across the file. All lines are re-wrapped to 80 char limit. All labels have better names; in particular, labels start with prefix `cssa0_` or `cssa1_` to indicate whether asm code is executed in SSA[0] (regular and stage-2 exception handler flows) or in SSA[1] (stage-1 exception handler flows). Finally, `ignore_exception` label was redundant and therefore removed.

## How to test this PR? 

N/A. No changes in the code itself, only comments and label names.

2021-12-20 13:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/291#-MrMwo81CyHlbUPPrKAl:-MrMwo81CyHlbUPPrKAm:bc9y4dh) (no related file):*
I don't like how amorphous this file is. Some functions are defined, but it's hard to notice if we're jumping within a function, or jumping to some code outside of any function. And sometimes we just fallthrough out of a function. Mostly it looks like flat code with GOTOs between labels. It also makes GDB debugging harder if you end up in some of these places outside any function.

On the flip side, I really like how some parts have well-documented input parameters and are treated like proper functions (usually with completely custom calling convention, ofc).

Would it be possible to give this file more structure? I'm not sure how much can be done without actually changing the code, but it'd be great if e.g. every instruction was inside of a (well-defined) function, and every `jmp` outside of a current function could be treated as a tail-call to another function (which would be clearly visible because these jump targets should be without the `.L`).

Also, I guess it would mean a change in some names. A descriptive label like `.Lcssa0_ocall_or_cssa1_exception_eexit` tells you how you ended up here, but not what the code is doing. I guess it's okay as a label *inside* a (hopefully short) function. But I'd rather have a *function* called `clear_and_eexit`, with a really clear description of how it should be called and what it does (and this function could be even moved to a separate file). The difference is introducing some abstraction.

---


<!-- Sent from Reviewable.io -->

2021-12-21 09:55 UTC, dimakuv commented
Jenkins, retest this please (internet connectivity on Glibc-2.34 download -- both URLs were unaccessible).

2021-12-21 10:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/291#-MrMwo81CyHlbUPPrKAl:-MrRQIds7mjyRHRaOzX7:bgdynn2) (no related file):*
I agree with many points of @pwmarcz. One thing I definitely don't want to do in this PR is to *touch the code*.

I considered moving separate functions in separate files (e.g., `enclave_entry` -- the EENTER entry point -- would stay in `enclave_entry.S`, everything related to `sgx_ocall()` would be in a separate file, and all helper functions would be in a third file). But it would require quite significant changes (these different flows cross-reference each other), including changes in the code itself.

TLDR: I want to start with non-functional changes only. In particular, label names and comments. I am fine to revert some of the changes, but I don't want to add any code changes (except removing dead code).

> A descriptive label like `.Lcssa0_ocall_or_cssa1_exception_eexit` tells you how you ended up here, but not what the code is doing. 

I tried to create names that have both the descriptive part ("how you ended up here") and the actionable part ("what the code is doing"). In this example, I have:
- `cssa0_ocall_or_cssa1_exception` for descriptive part ("I ended up here via OCALL flow in SSA[0] or via exception-handling flow in SSA[1]")
- `_eexit` for actionable part ("the code is going to prepare everything for EEXIT")

I can expand this label to `.Lcssa0_ocall_or_cssa1_exception_clear_and_eexit`, no problem.

---


<!-- Sent from Reviewable.io -->

2021-12-21 10:22 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/291#-MrMwo81CyHlbUPPrKAl:-MrRUoyE3srr25Vc42Lu:b-zricz) (no related file):*
>I can expand this label to `.Lcssa0_ocall_or_cssa1_exception_clear_and_eexit`, no problem.

I don't think that would help - my point was about keeping this piece of code (and others) separate and encapsulated, not exposing more details. But I guess that's for later, when we can make it into a proper function.

---


<!-- Sent from Reviewable.io -->

2021-12-21 23:06 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTr_FD99tEX1zVy3GX):*
Why `80` instead of usual `100`?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTt8-e4KSaV0rUyl7s:-MrTt8-e4KSaV0rUyl7t:b9b59xu) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L97)):*
> ```
> 	jne .Lcssa0_ocall_return
> 
> .Lcssa0_ecall:
> ```

This label is unused. Did you add it just as a code comment? If so I think we can change it to regular comment
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTu71VBVRvU9owgoxs:-MrTu71VBVRvU9owgoxt:bn3nf4p) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L210)):*
> ```
> 1:
> 
> 	# set RBX to point to SSA[0].GPRSGX region ("regular context" GPRs)
> ```

I don't think a simple mov instruction needs explanation, though the part explaining what `SGX_GPR` is might be worth leaving. Also what is "regular context"? I'm not sure if I got the part in `( )`
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU60WA9-FMRrmMFpEo:-MrU60WB85POoa9j6TId:bjd9hji) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L325)):*
> ```
> 	#        - set EINTR and forward %rip to exception handler
> 	# B. during untrusted PAL (3. - 4. in above sequence):
> 	#        - code in _DkTerminateSighandler() must handle this case
> ```

Not sure what this sentence is about - we don't have such function....
Update: ok, I've digged into some history - this can me removed, it's already solved (it was related to EINTR injection)
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 329 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU6pcR3Sl3qG3LdenN:-MrU6pcR3Sl3qG3LdenO:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L329)):*
> ```
> 	#        - ocall succeeded, forward %rip to exception handler
> 	#
> 	# TODO: _DkTerminateSighandler() mustn't lose result of successful syscall.
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 368 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU8P5E27Y70cyBZxmS:-MrU8P5E27Y70cyBZxmT:b-ja5077) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L368)):*
> ```
> 	# .Lcssa0_ocall_return_after_stack_restore, such that regular
> 	# returning-from-OCALL flow (CSSA=0) will notice the external event and will
> 	# call _DkHandleExternalEvent() to handle the async signal.
> ```

Why `async signal`? It's referred to as `exception` everywhere else
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUAJgYEf4Jy3peM5gn:-MrUAJgYEf4Jy3peM5go:b2sys6q) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L466)):*
> ```
> 	jae 1f
> 	FAIL_LOOP
> 1:
> ```

I'm confused. In some places you add such 1 time used labels just to comment the code (e.g. `.Lcssa0_ecall_enclave_or_thread_start`), in here you remove it.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 518 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUB5bT1f83XhdYMiBt:-MrUB5bT1f83XhdYMiBu:b-1w3xyv) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L518)):*
> ```
> 
> 	# Rewire SSA0: pass more args to _DkExceptionHandler():
> 	#    - pointer to sgx_cpu_context_t (SSA[0].GPRSGX.RIP, 2nd arg)
> ```

`RSI` instead of `RIP`
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 577 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUBunc4QQ2fPqEdv6x:-MrUBunc4QQ2fPqEdv6y:b-w63enm) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L577)):*
> ```
> 	.type sgx_ocall, @function
> sgx_ocall:
> .Lcssa0_ocall:
> ```

What's the point of this label?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 652 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUD6ZT-yAfwbawopJ-:-MrUD6ZT-yAfwbawopJ0:b5t8yml) ([raw file](https://github.com/gramineproject/gramine/blob/4d919534dfec67a9aba8f9a3b85119241f539101/Pal/src/host/Linux-SGX/enclave_entry.S#L652)):*
> ```
> #endif
> 
> 	# %rsp points to untrusted stack
> ```

You removed this comment, but I think it was somewhat useful


<!-- Sent from Reviewable.io -->

2021-12-22 09:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: 0 of 1 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTr_FD99tEX1zVy3GX):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `80` instead of usual `100`?
</blockquote></details>

Done. I re-wrapped to 80 because the whole file was more-or-less wrapped to 80. I guess historically. But I checked other `.S` files, and we indeed use 100 chars limit in other files. So now I wrapped to 100.
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrWQh1yEVCadoMIkuJD):*
Blocking myself: change to `re-wrapped to 100 char limit` on final rebase.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTt8-e4KSaV0rUyl7s:-MrWNDW182S2h-ZsmL_W:b-gi7r30) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This label is unused. Did you add it just as a code comment? If so I think we can change it to regular comment
</blockquote></details>

Yes, I added it as a code comment. Well, now I added a bit more code (admittedly redundant), this label is used now -- I did this for uniformity. I think it's important to have three clearly defined "beginnings of flows" -- one for SSA[1] exception, one for SSA[0] ocall return, and one for SSA[0] ecall.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTu71VBVRvU9owgoxs:-MrWO5tw7kYh1IgkbQsT:b-q008v5) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L210)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think a simple mov instruction needs explanation, though the part explaining what `SGX_GPR` is might be worth leaving. Also what is "regular context"? I'm not sure if I got the part in `( )`
</blockquote></details>

Done. `regular context` is the non-stage-1-exception context -- basically the context stored in `SSA[0]`. I explain this term in the top-level comment for this file.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 325 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU60WA9-FMRrmMFpEo:-MrWJc_u0DebpWKhPcRM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L325)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure what this sentence is about - we don't have such function....
Update: ok, I've digged into some history - this can me removed, it's already solved (it was related to EINTR injection)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 329 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU6pcR3Sl3qG3LdenN:-MrWJW_p651Z54wEdf4A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L329)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 368 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrU8P5E27Y70cyBZxmS:-MrWM7Y8DIswtsdmMpa5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L368)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `async signal`? It's referred to as `exception` everywhere else
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 466 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUAJgYEf4Jy3peM5gn:-MrWOvVA-2DjHVffMxKB:b-jewk7u) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L466)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm confused. In some places you add such 1 time used labels just to comment the code (e.g. `.Lcssa0_ecall_enclave_or_thread_start`), in here you remove it.
</blockquote></details>

I didn't see any need in this label name. We already explain what happens here in the comment (`Disallow ...`).

My logic was: if the label is just to check a simple condition (not to jump to a new flow or one of the several sub-flows), then there is no need to call it (and instead simply use 1-time labels). This case is exactly that.

An opposite example: I changed `1` to `.Lcssa0_ecall_enclave_or_thread_start` above because I wanted to highlight -- we are choosing between three different sub-flows. So I named labels for each of these three sub-flows.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 518 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUB5bT1f83XhdYMiBt:-MrWMDs23oT-8Q8H615f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L518)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`RSI` instead of `RIP`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 577 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUBunc4QQ2fPqEdv6x:-MrWMeJR5y1cdts_lxhn:beb5nqz) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L577)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this label?
</blockquote></details>

I didn't want to change the name of the `sgx_ocall()` function, but I also wanted to highlight that this is the entry point of the `cssa0_ocall ...` asm flows. Basically, for uniformity. I don't know how else to highlight this. Any recommendations?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 652 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrUD6ZT-yAfwbawopJ-:-MrWMXjp3Ce7j6mkpfC0:b9bdx0q) ([raw file](https://github.com/gramineproject/gramine/blob/4d919534dfec67a9aba8f9a3b85119241f539101/Pal/src/host/Linux-SGX/enclave_entry.S#L652)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You removed this comment, but I think it was somewhat useful
</blockquote></details>

I already have this comment as a top-level comment for label `.Lcssa0_ocall_or_cssa1_exception_eexit:`, see above.


<!-- Sent from Reviewable.io -->

2021-12-22 12:33 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 155 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrWzcWG75m6Q5dLrpOz:-MrWzcWG75m6Q5dLrpP-:b-rn4k3k) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L155)):*
> ```
> 	callq handle_ecall
> 
> 	# handle_ecall will only return when invalid parameters has been passed.
> ```

Why removed? It's a non-obvious property of that function, that it returns, but only sometimes.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTu71VBVRvU9owgoxs:-MrX-iJh2BDFRLze8AOe:b-jq3jbs) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L210)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. `regular context` is the non-stage-1-exception context -- basically the context stored in `SSA[0]`. I explain this term in the top-level comment for this file.
</blockquote></details>

Actually it states that "regular context" is `SSA[0]` and here you state that part of `SSA[0]` (GPRSGX) contains it (and these two contradict themselves). IMO you can remove the part in `( )`, it doesn't bring any new information


<!-- Sent from Reviewable.io -->

2021-12-22 15:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 155 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrWzcWG75m6Q5dLrpOz:-MrXgD7f5aaODTMX2uFS:b1jzwan) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L155)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why removed? It's a non-obvious property of that function, that it returns, but only sometimes.
</blockquote></details>

Done. Restored.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 210 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrTu71VBVRvU9owgoxs:-MrXgZkO3vAlFQn9Q_gf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/be1b4128d13a1e88408727d6cf2ff9f7b52f6665/Pal/src/host/Linux-SGX/enclave_entry.S#L210)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually it states that "regular context" is `SSA[0]` and here you state that part of `SSA[0]` (GPRSGX) contains it (and these two contradict themselves). IMO you can remove the part in `( )`, it doesn't bring any new information
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-22 16:36 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-12-27 12:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/291#-MrWQh1yEVCadoMIkuJD):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself: change to `re-wrapped to 100 char limit` on final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-12-27 13:56 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-27 14:09 UTC, merged

2021-12-29 12:38 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 276 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ovAm4W1lPT-by1y2:-Ms2ovAm4W1lPT-by1y3:bbfc3gr) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L276)):*
>  So we don't set up the stage-2 handler _DkExceptionHandler().

Hmm, missing some word before `_DkExceptionHandler()`? Or what do you mean here?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 322 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2q8yM9z7mg-bLcYBg:-Ms2q8yM9z7mg-bLcYBh:b-h9yygx) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L322)):*
> ```
> 	#   - copy rip at which the enclave was interrupted into %rax,
> 	#   - copy the boundaries between cases A, B, and C into %r11,
> 	#   - compare enclave's rip against these boundaries (%rax vs %r11).
> ```

You sometimes say `rip`, sometimes `%rip` and sometimes `RIP` (same for other regs). I prefer `RIP` and I think we use this convention in other places?
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 546 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ux8aBENOAW-BhjH3:-Ms2ux8aBENOAW-BhjH4:brfyn5n) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L546)):*
> note that stage-1 handler didn't clobber rsp

What does this mean exactly? Is RSP trusted or untrusted here?


<!-- Sent from Reviewable.io -->

2022-01-03 08:07 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 546 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ux8aBENOAW-BhjH3:-MsTyRGzAY6SNpUQPJmD:b-sm6brm) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L546)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> note that stage-1 handler didn't clobber rsp

What does this mean exactly? Is RSP trusted or untrusted here?
</blockquote></details>

RSP value is untrusted itself, and it points to untrusted stack (well, this enclave code doesn't care where RSP points to, since it never uses/modifies RSP in this flow). See also my other comment.


<!-- Sent from Reviewable.io -->

2022-01-03 08:07 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 672 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-MsTyCAY162E9MeCVDx2:-MsTyCAZDSVi8U1FkXWX:b326pur) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L672)):*
> ```
> 	#     %rax:       contains `EEXIT` code
> 	#     %rbx:       exit target
> 	#     %rsp:       untrusted stack
> ```

@mkow Please notice this: RSP points to untrusted stack (and is untrusted itself)


<!-- Sent from Reviewable.io -->

2022-01-03 08:07 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 322 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2q8yM9z7mg-bLcYBg:-MsTxudM2xcE2KPkebHI:b-33yu8o) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L322)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You sometimes say `rip`, sometimes `%rip` and sometimes `RIP` (same for other regs). I prefer `RIP` and I think we use this convention in other places?
</blockquote></details>

Yeah, there is a lot of inconsistency in our comments. Let me submit another PR where all registers have capital letters.


<!-- Sent from Reviewable.io -->

2022-01-03 08:07 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 276 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ovAm4W1lPT-by1y2:-MsTx6EE89CqwcekKhng:b9zpr1q) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  So we don't set up the stage-2 handler _DkExceptionHandler().

Hmm, missing some word before `_DkExceptionHandler()`? Or what do you mean here?
</blockquote></details>

We have two stages of exception handling:
- stage-1 is very short and is done completely in this asm file: it saves the interrupted-context `SSA[0]` on the in-enclave signal stack and it rewires `SSA[0]` to the entry point of the stage-2 handler. In this specific flow, the stage-2 handler entry point is the C function `_DkExceptionHandler()`.
- stage-2 is the actual, long, readable C function that handles the exception/signal. In this specific flow, it is the C function `_DkExceptionHandler()`. In another flow (`.Lcssa1_exception_during_enclave_run`), it is the C function `_DkHandleExternalEvent()`.

So no, I didn't miss any words. `_DkExceptionHandler()` *is* the stage-2 handler.


<!-- Sent from Reviewable.io -->

2022-01-03 09:13 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 322 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2q8yM9z7mg-bLcYBg:-MsUCiCc3ogonNsC4uaJ:bvaoyq3) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L322)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, there is a lot of inconsistency in our comments. Let me submit another PR where all registers have capital letters.
</blockquote></details>

Done in https://github.com/gramineproject/gramine/pull/305


<!-- Sent from Reviewable.io -->

2022-01-03 16:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/291)* status: all files reviewed, 3 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 276 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ovAm4W1lPT-by1y2:-MsVmJJI85ec7b3GKv5U:b-6zs2lc) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have two stages of exception handling:
- stage-1 is very short and is done completely in this asm file: it saves the interrupted-context `SSA[0]` on the in-enclave signal stack and it rewires `SSA[0]` to the entry point of the stage-2 handler. In this specific flow, the stage-2 handler entry point is the C function `_DkExceptionHandler()`.
- stage-2 is the actual, long, readable C function that handles the exception/signal. In this specific flow, it is the C function `_DkExceptionHandler()`. In another flow (`.Lcssa1_exception_during_enclave_run`), it is the C function `_DkHandleExternalEvent()`.

So no, I didn't miss any words. `_DkExceptionHandler()` *is* the stage-2 handler.
</blockquote></details>

Aaah. Then I think `_DkExceptionHandler()` should be parenthesized? Then it would be unambiguous how to parse this sentence :)
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 672 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-MsTyCAY162E9MeCVDx2:-MsVmcke-PtZpwcggDri:b-icrb8l) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L672)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Please notice this: RSP points to untrusted stack (and is untrusted itself)
</blockquote></details>

But there are actually two things:
- whether the thing _pointed at_ is trusted or not,
- and whether the pointer value itself is trusted (e.g. if its value is untrusted+unsanitized, then it may point inside the enclave memory and we need to add additional checks before using it).

And these comments doesn't make it clear for me which case we deal with here.

You actually explained this in the discussion above, but the comments in the code does not explain this (or maybe I'm missing it?). And it's pretty important to be _very_ clear everywhere about the trustedness of all the data we operate on.


<!-- Sent from Reviewable.io -->

2022-01-04 07:54 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 276 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ovAm4W1lPT-by1y2:-MsZ4E41BlFgVdcDfdB0:b-i7600n) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Aaah. Then I think `_DkExceptionHandler()` should be parenthesized? Then it would be unambiguous how to parse this sentence :)
</blockquote></details>

Done in #305 


<!-- Sent from Reviewable.io -->

2022-01-04 08:00 UTC, dimakuv commented
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 546 at r4](https://reviewable.io/reviews/gramineproject/gramine/291#-Ms2ux8aBENOAW-BhjH3:-MsZ5Xm8D9Va-RjKomWd:b-i7600n) ([raw file](https://github.com/gramineproject/gramine/blob/4b5c79951e96a00eeffa9babb2bc15b59809519d/Pal/src/host/Linux-SGX/enclave_entry.S#L546)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

RSP value is untrusted itself, and it points to untrusted stack (well, this enclave code doesn't care where RSP points to, since it never uses/modifies RSP in this flow). See also my other comment.
</blockquote></details>

Done in #305 


<!-- Sent from Reviewable.io -->