[LibOS] Improve GDB treatment of vDSO
gramineproject/gramine pull request #294
Opened 2021-12-21 11:25 UTC by pwmarcz

## Description of the changes 

This change stops GDB from trying to load vDSO as regular files, and instead loads them from process memory. As a result, GDB backtrace is fixed for stacks involving vDSO (e.g. `shim_do_gettimeofday`).

## How to test this PR? 

The GDB warnings (`file not found: .../[vdso_libos]`) should be gone.

There should be a proper backtrace for `shim_do_gettimeofday`:

```
LibOS/shim/test/regression $ GDB=1 gramine-direct gettimeofday
(gdb) break shim_do_gettimeofday
(gdb) run
...
(gdb) bt
#0  shim_do_gettimeofday (tv=0x7ffff3f692b8 <read_exact>, tz=0x0) at ../LibOS/shim/src/sys/shim_time.c:17
#1  0x00007ffff3f691b8 in shim_emulate_syscall (context=0x7ffff3efef38) at ../LibOS/shim/src/shim_syscalls.c:41
#2  0x00007ffff3f8a3ff in syscalldb () at ../LibOS/shim/src/arch/x86_64/syscallas.S:173
#3  0x00007ffff3f8a402 in __morestack () at ../LibOS/shim/src/arch/x86_64/syscallas.S:204
#4  0x000078863ce785c6 in ?? ()
#5  0x000078863ce78624 in gettimeofday ()
#6  0x0000000000401303 in main (argc=1, argv=0x78863d0eaee8) at ../LibOS/shim/test/regression/gettimeofday.c:35
#7  0x000078863c8ab147 in __libc_start_call_main (main=main@entry=0x4012d2 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x78863d0eaee8) at ../sysdeps/nptl/libc_start_call_main.h:58
#8  0x000078863c8ab20c in __libc_start_main_impl (main=0x4012d2 <main>, argc=1, argv=0x78863d0eaee8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x78863d0eaed8) at ../csu/libc-start.c:409
#9  0x000000000040115e in _start ()
```

On `master`, the backtrace breaks on entry to Gramine (`__morestack`).

Note that there is `??` in here. It corresponds to `vdso_arch_syscall` which is a `static` function inside vDSO. It's gone because we strip symbols from the vDSO binary. However, the backtrace goes on.

(I tried to keep debug info, but GDB failed to load it or even display a traceback. I think this is useful enough, there's really not much code in there).

2021-12-21 11:54 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-12-21 21:13 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/294#-MrTovSC5_d57ngRo36D):*
Isn't vDSO singular here? If it is, then `regular file and instead loads it from`


<!-- Sent from Reviewable.io -->

2021-12-22 09:01 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/294#-MrTovSC5_d57ngRo36D):*
Technically the debug maps also contain the host vDSO. GDB already knows about the host one, but we treat both the same for simplicity.

I can modify the description (during rebase) to clarify:

>This change stops GDB from trying to load LibOS vDSO and host vDSO (`[vdso_libos]` and `[vdso]`) as regular files, and instead loads them from process memory. As a result, GDB backtrace is fixed for stacks involving LibOS vDSO (e.g. `shim_do_gettimeofday`).


<!-- Sent from Reviewable.io -->

2021-12-22 11:40 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/294#-MrTovSC5_d57ngRo36D):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Technically the debug maps also contain the host vDSO. GDB already knows about the host one, but we treat both the same for simplicity.

I can modify the description (during rebase) to clarify:

>This change stops GDB from trying to load LibOS vDSO and host vDSO (`[vdso_libos]` and `[vdso]`) as regular files, and instead loads them from process memory. As a result, GDB backtrace is fixed for stacks involving LibOS vDSO (e.g. `shim_do_gettimeofday`).
</blockquote></details>

New message looks better, please change


<!-- Sent from Reviewable.io -->

2021-12-22 14:19 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/294#-MrTovSC5_d57ngRo36D):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

New message looks better, please change
</blockquote></details>

Done at rebase.


<!-- Sent from Reviewable.io -->

2021-12-22 14:24 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/294#-MrTovSC5_d57ngRo36D):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done at rebase.
</blockquote></details>

OK, resolving.


<!-- Sent from Reviewable.io -->

2021-12-22 15:06 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/294)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-22 15:08 UTC, merged