Convert `tmpfs` to use inodes
gramineproject/gramine pull request #297
Opened 2021-12-22 13:08 UTC by pwmarcz

## Description of the changes 

Next step in inodes conversion (#279). Based on open PR #282.

- Use `g_dcache_lock` for the dentry inode field
- Take `g_dcache_lock` for the whole checkpointing process
- Convert `tmpfs` to use inodes (fixes unlinking, renaming, and corner cases when migrating handles)
- Support `inode->data` (with deallocation and migration)
- Factor out some generic callbacks (seek, stat, hstat, poll)

## How to test this PR? 

CI should be enough. Some tests are now enabled for tmpfs (`send_handle`, `rename_unlink`).

2021-12-22 15:26 UTC, pwmarcz commented
Jenkins, retest Jenkins-Direct-Sanitizers please (`sendfile04` timed out, known issue, fixed on `master`, but this PR is not yet based on `master`)

2021-12-27 08:29 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MruxArTDANZQARJlA5Y:b5ysca8) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> ```C
>     struct tmpfs_checkpoint* cp;
>     size_t cp_size = sizeof(*cp) + mem->size;
>     cp = malloc(cp_size);
> ```

Why do we have this level of indirection? Why couldn't we have a pointer to the memory region, where the tmpfs file content is located? (These memory regions -- VMAs -- are checkpointed and sent to the child anyway, and are located at exactly the same addresses in the child as in the parent.)

I'm afraid that this "copy the contents of the tmpfs file into the checkpoint blob, and then restore into child's memory from the checkpoint blob" will explode on large tmpfs files. I can easily imagine some database engine creating temporary files of 10GB in size, and copying such a file during fork will most probably fail (we cap the size of the checkpoint blob).

Or maybe I misunderstand the code? I actually thought that we had FS tests for such cases (copying of pretty-big files during fork), and I would expect them to fail in our CI.
___
*[LibOS/shim/src/sys/shim_clone.c, line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruzhIs81_Rh7gwghk0:-MruzhIs81_Rh7gwghk1:b-gx66az) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/sys/shim_clone.c#L129)):*
> ```C
>                         struct shim_ipc_ids* process_ipc_ids, va_list ap) {
>     __UNUSED(ap);
>     lock(&g_dcache_lock);
> ```

It's a bit weird to grab the dcache lock here -- we will hold the lock even when we checkpoint unrelated objects (like VMAs). There is no way to grab this lock at some root-of-dcache object?

Alternatively, please put a comment that "for simplicity, we grab the dcache lock here, even though it will cover unrelated stuff".


<!-- Sent from Reviewable.io -->

2021-12-31 14:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsFg43I63UqlLkfThBl:b-pc6clq) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> Why do we have this level of indirection? Why couldn't we have a pointer to the memory region, where the tmpfs file content is located? (These memory regions -- VMAs -- are checkpointed and sent to the child anyway, and are located at exactly the same addresses in the child as in the parent.)

Wow, looks like we do that, but I'm very surprised to see this. I assumed we only copy *application*'s data, not internal LibOS memory, and that's why we need the whole checkpointing process which copies all the data.

Do we actually rely on the fact we copy all VMAs? I haven't seen anything like this in the checkpointing code. Will anything break if I exclude internal VMAs from checkpointing?

Mostly I'm just really confused. Using the memory from the checkpoint blob directly (which we do right now) already sounded like a pretty bad design, but now I hear that we also transfer the *original memory* containing the objects that we just copied to the checkpoint blob, and that sounds really broken (or at least wasteful).

As for the solution you propose:

1. While we could use this memory directly, probably bad things will happen if we `free()` it, right? It is my understanding that `free()` is a no-op only when called on memory inside the checkpoint blob, not inside these other copied VMAs.

2. If I understand correctly, the 10GB-temporary-file scenario should fail even before any of this, because we will be checkpointing the VMA that contains it, so we will try to copy it to the checkpoint blob, and that will fail. Is that right?

>Or maybe I misunderstand the code? I actually thought that we had FS tests for such cases (copying of pretty-big files during fork), and I would expect them to fail in our CI.

Not sure what tests you have in mind? If there are any, they're probably still skipped for tmpfs.
___
*[LibOS/shim/src/sys/shim_clone.c, line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruzhIs81_Rh7gwghk0:-MsFlhF44hKO6X7N-EGL:b940vjq) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/sys/shim_clone.c#L129)):*
>It's a bit weird to grab the dcache lock here -- we will hold the lock even when we checkpoint unrelated objects (like VMAs). There is no way to grab this lock at some root-of-dcache object?

While we checkpoint root of dcache, currently we don't checkpoint children (I'm not sure why, maybe there were some weird cyclic dependencies?) But we checkpoint dentries for open handles, and, recursively, all their parents. And, separately, the mount objects that also point to root dentries.

My point is, the checkpoint procedure isn't neatly split between object types. Checkpointing an object of one type can pull in other objects (e.g. VMA -> file handle -> dentry), as long as they haven't been checkpointed before. So even if I could claim that `g_dcache_lock` is needed only for a part of this operation, I think it would be pretty brittle.


<!-- Sent from Reviewable.io -->

2022-01-03 08:18 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsTzIJq5q929w16t5jw:bs5919n) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
Just a note: I don't think any one of us understands the design and implementation of Gramine checkpointing completely. It is probably the only part of Gramine that was not touched or deeply analyzed by any active developer.

> If I understand correctly, the 10GB-temporary-file scenario should fail even before any of this, because we will be checkpointing the VMA that contains it, so we will try to copy it to the checkpoint blob, and that will fail. Is that right?

No, VMAs are not copied into the checkpoint blob. They are transferred to the child process separately: https://github.com/gramineproject/gramine/blob/57e5cd3cd48db24f4bb2e8cd9d36b74d5cb2fa6b/LibOS/shim/src/shim_checkpoint.c#L214

> Wow, looks like we do that, but I'm very surprised to see this. I assumed we only copy application's data, not internal LibOS memory, and that's why we need the whole checkpointing process which copies all the data.

> Do we actually rely on the fact we copy all VMAs? I haven't seen anything like this in the checkpointing code. Will anything break if I exclude internal VMAs from checkpointing?

We need @boryspoplawski here. He re-wrote the VMA subsystem. To be honest, I don't know/remember the details of *checkpointing internal VMAs*.

> Not sure what tests you have in mind? If there are any, they're probably still skipped for tmpfs.

I mean these tests: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/fs/test_tmpfs.py

TLDR: If it turns out that checkpointing of internal VMAs is an unwanted side-effect of the current implementation, I'm fine with the current approach. We'll need to fix Gramine checkpointing in a separate series of PRs...
___
*[LibOS/shim/src/sys/shim_clone.c, line 129 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruzhIs81_Rh7gwghk0:-MsU-jzoELgjqJ5fdIE0:btkyv5q) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/sys/shim_clone.c#L129)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>It's a bit weird to grab the dcache lock here -- we will hold the lock even when we checkpoint unrelated objects (like VMAs). There is no way to grab this lock at some root-of-dcache object?

While we checkpoint root of dcache, currently we don't checkpoint children (I'm not sure why, maybe there were some weird cyclic dependencies?) But we checkpoint dentries for open handles, and, recursively, all their parents. And, separately, the mount objects that also point to root dentries.

My point is, the checkpoint procedure isn't neatly split between object types. Checkpointing an object of one type can pull in other objects (e.g. VMA -> file handle -> dentry), as long as they haven't been checkpointed before. So even if I could claim that `g_dcache_lock` is needed only for a part of this operation, I think it would be pretty brittle.
</blockquote></details>

Ah, true, I understand now. Our checkpointing is more of a hodgepodge approach: upon encountering a new LibOS object, checkpoint all its related objects.


<!-- Sent from Reviewable.io -->

2022-01-04 03:48 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsYBQy91LklP17DnUg4:bapynqd) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a note: I don't think any one of us understands the design and implementation of Gramine checkpointing completely. It is probably the only part of Gramine that was not touched or deeply analyzed by any active developer.

> If I understand correctly, the 10GB-temporary-file scenario should fail even before any of this, because we will be checkpointing the VMA that contains it, so we will try to copy it to the checkpoint blob, and that will fail. Is that right?

No, VMAs are not copied into the checkpoint blob. They are transferred to the child process separately: https://github.com/gramineproject/gramine/blob/57e5cd3cd48db24f4bb2e8cd9d36b74d5cb2fa6b/LibOS/shim/src/shim_checkpoint.c#L214

> Wow, looks like we do that, but I'm very surprised to see this. I assumed we only copy application's data, not internal LibOS memory, and that's why we need the whole checkpointing process which copies all the data.

> Do we actually rely on the fact we copy all VMAs? I haven't seen anything like this in the checkpointing code. Will anything break if I exclude internal VMAs from checkpointing?

We need @boryspoplawski here. He re-wrote the VMA subsystem. To be honest, I don't know/remember the details of *checkpointing internal VMAs*.

> Not sure what tests you have in mind? If there are any, they're probably still skipped for tmpfs.

I mean these tests: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/fs/test_tmpfs.py

TLDR: If it turns out that checkpointing of internal VMAs is an unwanted side-effect of the current implementation, I'm fine with the current approach. We'll need to fix Gramine checkpointing in a separate series of PRs...
</blockquote></details>

We do **not** checkpoint internal VMAs.


<!-- Sent from Reviewable.io -->

2022-01-04 03:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsYCK8hBQ70-mnNjbnI:b-p4nah4) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> Just a note: I don't think any one of us understands the design and implementation of Gramine checkpointing completely. It is probably the only part of Gramine that was not touched or deeply analyzed by any active developer.

I've dug into it some/long time ago, but there were always changes with more priority, so I've never finished it.

FWIW: checkpointing of VMAs and memory in general was mostly left as it was, when I rewrote VMAs subsystem.


<!-- Sent from Reviewable.io -->

2022-01-04 08:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsZ9Ugr9iep1KxMZp9D:bp3fej2) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Just a note: I don't think any one of us understands the design and implementation of Gramine checkpointing completely. It is probably the only part of Gramine that was not touched or deeply analyzed by any active developer.

I've dug into it some/long time ago, but there were always changes with more priority, so I've never finished it.

FWIW: checkpointing of VMAs and memory in general was mostly left as it was, when I rewrote VMAs subsystem.
</blockquote></details>

Indeed, we do not checkpoint internal VMAs, I just looked at the VMA checkpointing procedure. These are the relevant lines: https://github.com/gramineproject/gramine/blob/57e5cd3cd48db24f4bb2e8cd9d36b74d5cb2fa6b/LibOS/shim/src/bookkeep/shim_vma.c#L1121-L1122

@pwmarcz So I guess there is no other way to transfer tmpfs files, other than your current copy-into-checkpoint-blob? If there is no other way, then I'll resolve my comment.


<!-- Sent from Reviewable.io -->

2022-01-04 09:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MsZMFRjBwXpeCKuW88K:bfzh9mh) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed, we do not checkpoint internal VMAs, I just looked at the VMA checkpointing procedure. These are the relevant lines: https://github.com/gramineproject/gramine/blob/57e5cd3cd48db24f4bb2e8cd9d36b74d5cb2fa6b/LibOS/shim/src/bookkeep/shim_vma.c#L1121-L1122

@pwmarcz So I guess there is no other way to transfer tmpfs files, other than your current copy-into-checkpoint-blob? If there is no other way, then I'll resolve my comment.
</blockquote></details>

Memory is checkpointed using https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/shim_checkpoint.c#L129 so you probably want to use that.


<!-- Sent from Reviewable.io -->

2022-01-31 12:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-Muk2zGjB-CtFMHy7Sjn:b3reliv) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
OK, my bad, I didn't notice that we skip `VMA_INTERNAL` vmas. Too bad the code consistently claims to copy "all vmas" but that's Gramine for you :)

>Memory is checkpointed using https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/shim_checkpoint.c#L129 so you probably want to use that.

Correct me if I'm wrong, but it looks like this is for copying a region of memory _to the same address in child_ (the `receive_memory_on_stream` function uses `entry->addr` as-is). So 

1. it won't work for objects allocated by our internal `malloc()`, since we don't migrate the corresponding VMA, and
2. even if we migrated the internal VMA as well, the resulting memory would be managed by the slab allocator (e.g. I cannot `free()` it). So I don't see an easy way of using this.

I think this is a good input for redesigning the checkpointing system: ideally, _all_ serialized data should be received as a stream, and not kept in a "blob received from parent" where it can never be freed. (That would also force us to _process_ all fields, instead of using them directly with some "rebasing" hacks.)

But within the current system, I don't think we have an easy way of migrating `malloc`ed data without copying it?


<!-- Sent from Reviewable.io -->

2022-01-31 14:14 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MukTbcc6DH9k1xsLypS:bq8hs1t) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> But within the current system, I don't think we have an easy way of migrating `malloc`ed data without copying it?

Yes, I have the same impression.

> I think this is a good input for redesigning the checkpointing system: ideally, all serialized data should be received as a stream, and not kept in a "blob received from parent" where it can never be freed. (That would also force us to process all fields, instead of using them directly with some "rebasing" hacks.)

Yes, this makes sense. It's much cleaner to re-create the objects (including nested objects) from the stream, and forget about the "checkpoint blob" after the restore process is finished.


<!-- Sent from Reviewable.io -->

2022-01-31 18:11 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MulFMDp2rEwoITpZFFE:b-29yv7h) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> Too bad the code consistently claims to copy "all vmas" but that's Gramine for you :)

I think we only have `all_vma` as checkpointing function, which might be misleading.

> Correct me if I'm wrong, but it looks like this is for copying a region of memory to the same address in child

As, you're right.

> I think this is a good input for redesigning the checkpointing system: ideally, all serialized data should be received as a stream, and not kept in a "blob received from parent" where it can never be freed. (That would also force us to process all fields, instead of using them directly with some "rebasing" hacks.)

Yes, I think we already had some discussions about this (or maybe I've just talked privately with Michał, don't remember).

> But within the current system, I don't think we have an easy way of migrating malloced data without copying it?

From what I can see you just malloc this buffer so that you can copy data into it in `icheckpoint` and then copy that data into actual checkpoint and free it? Why not copy data directly into checkpoint? It should be doable in the current state, just add a checkpointing function for tmpfs inodes/data.
Disclaimer: I've not read the whole PR, maybe I'm talking nonsense.


<!-- Sent from Reviewable.io -->

2022-01-31 18:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MulO5Xo0xSYx4QffixT:b3eb07h) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> ideally, all serialized data should be received as a stream, and not kept in a "blob received from parent" where it can never be freed

And we could finally have `relloc()` then! :)


<!-- Sent from Reviewable.io -->

2022-02-01 14:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MupeNqZ6SpAkrrBnPR_:b-mlnp45) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> From what I can see you just malloc this buffer so that you can copy data into it in `icheckpoint` and then copy that data into actual checkpoint and free it? Why not copy data directly into checkpoint? It should be doable in the current state, just add a checkpointing function for tmpfs inodes/data.

I mean, I could define something like `BEGIN_CP_FUNC(tmpfs_inode)` but then I don't know how to call it based on the filesystem type. It sounds like I'd have to store a pointer to it in the filesystem callbacks (e.g. `shim_d_ops`, and I don't like where that leads (for example, both the name and the signature of that function are hidden behind macros...)

So, for the sake of sanity, I wanted to keep `icheckpoint/irestore` as a set of simple callbacks that are completely independent of the current checkpointing system. I hope it's worth it even with the extra copy.


<!-- Sent from Reviewable.io -->

2022-02-01 15:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: 4 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MupqFaS0fGDJ6lZWc_z:bz2r3ah) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> From what I can see you just malloc this buffer so that you can copy data into it in `icheckpoint` and then copy that data into actual checkpoint and free it? Why not copy data directly into checkpoint? It should be doable in the current state, just add a checkpointing function for tmpfs inodes/data.

I mean, I could define something like `BEGIN_CP_FUNC(tmpfs_inode)` but then I don't know how to call it based on the filesystem type. It sounds like I'd have to store a pointer to it in the filesystem callbacks (e.g. `shim_d_ops`, and I don't like where that leads (for example, both the name and the signature of that function are hidden behind macros...)

So, for the sake of sanity, I wanted to keep `icheckpoint/irestore` as a set of simple callbacks that are completely independent of the current checkpointing system. I hope it's worth it even with the extra copy.
</blockquote></details>

I think you can just:
```c
switch (inode->type) {
    case tmpfs:
        DO_CP(tmpfs_inode, ptr1, ptr2);
        break;
    case X:
         ....
    default:
        ...
```

Idk if it's worth


<!-- Sent from Reviewable.io -->

2022-02-02 00:59 UTC, mkow requested changes
> Reviewed 3 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurnRus7Pnd7YLzoz8v:-MurnRut3VfFXsuDjD3a:b-5i5vji) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L172)):*
> ```objc
>     bool maybe_has_fs_locks;
> 
>     struct shim_lock lock;
> ```

Do I see correctly that only `.data` is now protected by this lock? If so, maybe we should rename it to `data_lock`?
___
*[LibOS/shim/include/shim_fs.h, line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-Muromv4CmLL_DA21Z2j:-Muromv4CmLL_DA21Z2k:biwvu40) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L370)):*
> ```objc
>      * inode.
>      */
>     void (*iput)(struct shim_inode* inode);
> ```

I think the convention we use is that "put"/"get" are used for refcounted objects. Here the description suggests that this function unconditionally frees the data, so I'd rather name it like "ifree" or something similar.
___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurpUuwEQflWrF6M17-:-MurpUuwEQflWrF6M170:b-6cc28w) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L389)):*
> ```objc
>      *
>      * \param inode newly restored inode
>      * \param data checkpoint data (prepared by the `icheckpoint` callback)
> ```

[not related to this PR directly]
This Doxygen formatting of parameter description really confuses and annoys me, we need to change it. I always start with reading like here "data checkpoint data", wondering wtf and then noticing that the first "data" is the parameter name.
Doxygen website capitalizes the description to make it a bit more distinct. We could also consider just spacing it a bit, e.g. minimum 2 spaces and aligning all params descriptions together.
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurtIwC5cuyHNaoadfb:-MurtIwD-dV_Mr5MfCQC:b-npkg03) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/src/fs/shim_fs_util.c#L68)):*
> ```C
>     assert(locked(&g_dcache_lock));
> 
>     if (!dent->inode)
> ```

When is this condition possible? Shouldn't this be an assert?


<!-- Sent from Reviewable.io -->

2022-02-02 12:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: 6 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurnRus7Pnd7YLzoz8v:-MuuGWJCARqgb-czZj1t:b8l17z2) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do I see correctly that only `.data` is now protected by this lock? If so, maybe we should rename it to `data_lock`?
</blockquote></details>

Both `data` and `lock` are on their way out (filesystem-specific data, when necessary, will be stored in inode), so I'd rather not change it for now. There is a comment at the top of this structure that explains the end goal.
___
*[LibOS/shim/include/shim_fs.h, line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-Muromv4CmLL_DA21Z2j:-MuuHlIS04_YViZaZRrG:bfhyw58) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L370)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the convention we use is that "put"/"get" are used for refcounted objects. Here the description suggests that this function unconditionally frees the data, so I'd rather name it like "ifree" or something similar.
</blockquote></details>

I agree, and this convention caused problems before - someone used `dput` to implement reference counting...

Before I change, what do you think about "idrop" or "irelease"? Since this could also be about closing handles or releasing other resources, not only freeing memory.
___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurpUuwEQflWrF6M17-:-MuuIcefDL1xPzu2xE5c:bdawxqi) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

[not related to this PR directly]
This Doxygen formatting of parameter description really confuses and annoys me, we need to change it. I always start with reading like here "data checkpoint data", wondering wtf and then noticing that the first "data" is the parameter name.
Doxygen website capitalizes the description to make it a bit more distinct. We could also consider just spacing it a bit, e.g. minimum 2 spaces and aligning all params descriptions together.
</blockquote></details>

+1. "Minimum 2 spaces + align all params" sounds good, I can try it out (separately from this PR).
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurtIwC5cuyHNaoadfb:-MuuJNnODARqQTI7INsS:b-q33c9v) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/src/fs/shim_fs_util.c#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

When is this condition possible? Shouldn't this be an assert?
</blockquote></details>

Yes, I think so (there were race conditions possible before, but now we call this immediately after lookup, under `g_dcache_lock`). Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MuuJnYBDLCtmB3wlmHA:b-uv6xvt) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think you can just:
```c
switch (inode->type) {
    case tmpfs:
        DO_CP(tmpfs_inode, ptr1, ptr2);
        break;
    case X:
         ....
    default:
        ...
```

Idk if it's worth
</blockquote></details>

I thought about it, but we already have some special cases for filesystems in the "generic" checkpointing code, and they are a pain to work with. This one would be a simple dispatch, but I'd still rather avoid it.


<!-- Sent from Reviewable.io -->

2022-02-02 13:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: 6 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_util.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurtIwC5cuyHNaoadfb:-Muugd7AAaVwjOfT6gr3:b-2148mq) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/src/fs/shim_fs_util.c#L68)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, I think so (there were race conditions possible before, but now we call this immediately after lookup, under `g_dcache_lock`). Done.
</blockquote></details>

Jenkins points out an issue with synthetic dentries that actually do *not* have an inode... Let me think of a least-hacky way of handling that.


<!-- Sent from Reviewable.io -->

2022-02-02 13:58 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurnRus7Pnd7YLzoz8v:-Muuig2b6TuU7nKtwGCl:b-tyvqxt) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L172)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Both `data` and `lock` are on their way out (filesystem-specific data, when necessary, will be stored in inode), so I'd rather not change it for now. There is a comment at the top of this structure that explains the end goal.
</blockquote></details>

Ah, I missed it. Then it's fine to leave this as is.
___
*[LibOS/shim/include/shim_fs.h, line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-Muromv4CmLL_DA21Z2j:-MuuiJDP-HkIaRXswHlb:brxp9sq) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L370)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree, and this convention caused problems before - someone used `dput` to implement reference counting...

Before I change, what do you think about "idrop" or "irelease"? Since this could also be about closing handles or releasing other resources, not only freeing memory.
</blockquote></details>

Sounds good.
___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurpUuwEQflWrF6M17-:-MuuiLjTEv8xa_TVrC6Q:b4c9lyr) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

+1. "Minimum 2 spaces + align all params" sounds good, I can try it out (separately from this PR).
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2022-02-02 14:15 UTC, mkow reviewed
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-02-02 14:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: 3 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-Muromv4CmLL_DA21Z2j:-Muusx534LNG99Gw4Q9D:bxnmpli) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L370)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Changed to "idrop".
___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurpUuwEQflWrF6M17-:-MuusTeI7bmb_srTcrpM:b7adp3y) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

You're still blocking, should I change anything here?
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurtIwC5cuyHNaoadfb:-Muut4ISA7clss6tL9-C:b-sw3bs5) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/src/fs/shim_fs_util.c#L68)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Jenkins points out an issue with synthetic dentries that actually do *not* have an inode... Let me think of a least-hacky way of handling that.
</blockquote></details>

Okay... I believe the right way is to treat these synthetic nodes as not belonging to the current FS (set `dent->fs` to something else, same as we do with pipes, sockets etc.)

I added a TODO here and I'll try to fix it in a separate PR: this is a problem, but I don't think this PR makes it worse (you already can't interact with such files in various ways, their permissions are 0).


<!-- Sent from Reviewable.io -->

2022-02-02 15:49 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/gramineproject/gramine/297#-MurpUuwEQflWrF6M17-:-Muv6SwX5isj0L2pNNSj:b-p4ybu) ([raw file](https://github.com/gramineproject/gramine/blob/41f583578288eafd7f1294efe6e8122158cf3bed/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You're still blocking, should I change anything here?
</blockquote></details>

Oops, fixed.


<!-- Sent from Reviewable.io -->

2022-02-02 18:24 UTC, boryspoplawski requested changes
> Reviewed 2 of 7 files at r1, 1 of 3 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 15 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 392 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muv92JG0Eh6u8FXO3H3:-Muv92JG0Eh6u8FXO3H4:bdthlh8) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_dcache.c#L392)):*
> ```C
> void put_inode(struct shim_inode* inode) {
>     if (REF_DEC(inode->ref_count) == 0) {
>         if (inode->fs->d_ops && inode->fs->d_ops->idrop)
> ```

I wonder, is the first part of check needed? When can `fs` not have `d_ops` field?
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvE9i6CiOwf87rrVe_:-MuvE9i746EfZWmgNK8o:b864cfo) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L93)):*
> ```C
>     file_off_t pos = hdl->pos;
> 
>     lock(&hdl->inode->lock);
> ```

Is this lock ordering correct? I was under impression that you should not take any other locks while holding `handle->lock`
Also from what I can see we don't need any lock for accessing `hdl->inode`, so we should be able to move this size acquisition outside of `hdl->lock`
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 109 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvGIWhDdQOHp7dC09a:-MuvGIWhDdQOHp7dC09b:b-rn1zx9) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L109)):*
> ```C
>     int ret;
> 
>     lock(&hdl->lock);
> ```

ditto (lock order)
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 116 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvGNLd8ToNCL2z-Rnq:-MuvGNLd8ToNCL2z-Rnr:b-1vaov3) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L116)):*
> ```C
>         if (poll_type & FS_POLL_WR)
>             ret |= FS_POLL_WR;
>         if ((poll_type & FS_POLL_RD) && hdl->pos < hdl->inode->size)
> ```

Why this size check? `poll` returns that file is readable even if `pos >= size` (after all `read` will return `0` immediately).
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-MuvYfjCB2Ag-_GGNV98:ba0r5dt) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
How about this function does not allocate the buffer, but gets it from the caller. It could also be called with ptr=NULL and size=0 and then return the size needed.

> This one would be a simple dispatch, but I'd still rather avoid it.

Actually why? What's the difference of calling a function pointer vs deciding what function to call based on type, in this context?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvPoeQB7Jg05OEEdHz:-MuvPoeQB7Jg05OEEdI-:b-qy1jj1) ([raw file](https://github.com/gramineproject/gramine/blob/66f58d0cc8673ab85e333d68f3c682e8ad20bc4d/LibOS/shim/src/fs/tmpfs/fs.c#L9)):*
> ```C
> /*
>  * This file contains code for implementation of 'tmpfs' filesystem. The tmpfs files are *not*
>  * cloned during fork/clone and cannot be synchronized between processes.
> ```

Why did you drop this comment about synchronization?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvRG_J16QL9-oFt-4T:-MuvRG_J16QL9-oFt-4U:badjtjl) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L64)):*
> ```C
> }
> 
> static void tmpfs_idrop(struct shim_inode* inode) {
> ```

Which locks should be here (`inode->lock`)? Please add asserts
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 162 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muv_SjP4JahlnlRUPIe:-Muv_SjP4JahlnlRUPIf:b-nni5bf) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L162)):*
> ```C
> 
>     mode_t type = S_IFREG;
>     mode_t perm = mode & ~S_IFMT;
> ```

Previously nothing was cleared from `mode` and it was actually named `perm`. From what I can see it's indeed being passed just permission bits, without file type.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 176 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvakro85k0Eial5Az9:-Muvakro85k0Eial5AzA:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L176)):*
> ```C
> 
>     mode_t type = S_IFREG;
>     mode_t perm = mode & ~S_IFDIR;
> ```

ditto
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvc0Ow4H6yYvGSsvER:-Muvc0Ow4H6yYvGSsvES:bozpt9t) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L222)):*
> ```C
> 
> static int tmpfs_rename(struct shim_dentry* old, struct shim_dentry* new) {
>     assert(locked(&g_dcache_lock));
> ```

Shouldn't we also hold `old->inode->lock`?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 244 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvbbwX0aVzkrDiBv_5:-MuvbbwX0aVzkrDiBv_6:bvpkzbh) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L244)):*
> ```C
>     old->inode = NULL;
> 
>     new->inode->mtime = time_us / USEC_IN_SEC;
> ```

Shouldn't we copy rest of the `*time` fields?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 269 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvcICP7LkzwNlGnVx2:-MuvcICP7LkzwNlGnVx3:b-umsewg) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L269)):*
> ```C
> 
>     lock(&hdl->lock);
>     lock(&inode->lock);
> ```

ditto (locks ordering)
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 302 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvcZavDwofUOEGUHzx:-MuvcZavDwofUOEGUHzy:b-umsewg) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L302)):*
> ```C
> 
>     lock(&hdl->lock);
>     lock(&inode->lock);
> ```

ditto (locks ordering)
___
*[LibOS/shim/src/sys/shim_clone.c, line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuveJ0b4l6X71-aU72S:-MuveJ0b4l6X71-aU72T:b-datn1w) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/sys/shim_clone.c#L129)):*
> ```C
>                         struct shim_ipc_ids* process_ipc_ids, va_list ap) {
>     __UNUSED(ap);
>     lock(&g_dcache_lock);
> ```

Please add a comment here why we take this lock here.
___
*[LibOS/shim/test/regression/test_libos.py, line 238 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvepnT2CiMpYM_mmZc:-MuvepnT2CiMpYM_mmZd:b-7ke6p2) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/test/regression/test_libos.py#L238)):*
> ```Python
>             os.unlink(path)
>         try:
>             self._test_send_handle('tmp/pf/send_handle_test')
> ```

`self._test_send_handle(path)`
___
*[LibOS/shim/test/regression/test_libos.py, line 240 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvez_-BOCf5ArtE-42:-Muvez_-BOCf5ArtE-43:b-7ropln) ([raw file](https://github.com/g [...]

2022-02-03 10:15 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 392 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muv92JG0Eh6u8FXO3H3:-MuypgrU1GYwIkH0ojkB:b5uz0gf) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_dcache.c#L392)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I wonder, is the first part of check needed? When can `fs` not have `d_ops` field?
</blockquote></details>

This happens for pipe, socket etc.

(I agree it would be better to always have both `fs_ops` and `d_ops` in all filesystems, for consistency.)
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvE9i6CiOwf87rrVe_:-Muyq7C57EZQHk-VM8lb:b-8sbzrg) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this lock ordering correct? I was under impression that you should not take any other locks while holding `handle->lock`
Also from what I can see we don't need any lock for accessing `hdl->inode`, so we should be able to move this size acquisition outside of `hdl->lock`
</blockquote></details>

I wrote all this assuming exactly this lock ordering; the code in `chroot/fs.c` and `tmpfs/fs.c` also obeys that rule. I added a comment to `shim_handle.inode`.

I think here you actually to hold `hdl->lock` while checking size. Otherwise, you might have a race with `write` on the same handle. Consider concurrent `seek` and `write` operations on a handle:

```c
// thread 1:                        thread 2:
seek(hdl, -1, SEEK_END);            write(hdl, buf, 5);

// hdl->pos = 10, inode->size = 10
size = inode->size;
                                    hdl->pos += 5;
                                    hdl->size += 5;
// hdl->pos = 15, inode->size = 15
hdl->pos = size - 1;
// hdl->pos = 9, inode->size = 15
```

So the two operations end up non-serializable (`seek` couldn't have happened either before or after `write`).
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 116 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvGNLd8ToNCL2z-Rnq:-MuywqXG4BO_x-6y_i86:b-6uikbf) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this size check? `poll` returns that file is readable even if `pos >= size` (after all `read` will return `0` immediately).
</blockquote></details>

Right. As far as I can tell Gramine's `poll` always worked like this :)

But I'd rather not change the behavior in this PR: I haven't touched the poll implementation yet, and I remember it to be pretty bad, so I expect things might break. I added a TODO.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvPoeQB7Jg05OEEdHz:-MuyxLSHC5yR5YO8YPp_:bokk45c) ([raw file](https://github.com/gramineproject/gramine/blob/66f58d0cc8673ab85e333d68f3c682e8ad20bc4d/LibOS/shim/src/fs/tmpfs/fs.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you drop this comment about synchronization?
</blockquote></details>

Right, it still applies. I think I thought it was about migration.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 64 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvRG_J16QL9-oFt-4T:-MuyxdM5CcF1DxUM9sw3:b2g1jqw) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Which locks should be here (`inode->lock`)? Please add asserts
</blockquote></details>

Right, this should be called with `inode->lock`, same as `icheckpoint`. Fixed.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 162 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muv_SjP4JahlnlRUPIe:-Muyy8VuExqaJOeuQ-Hi:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L162)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Previously nothing was cleared from `mode` and it was actually named `perm`. From what I can see it's indeed being passed just permission bits, without file type.
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 176 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvakro85k0Eial5Az9:-MuyyPlj7RSxNVM-rRIx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L176)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvc0Ow4H6yYvGSsvER:-Muz-HsvBNFMyWWVk-pR:bn8458z) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L222)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we also hold `old->inode->lock`?
</blockquote></details>

For modifying time, right. Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 244 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvbbwX0aVzkrDiBv_5:-Muz-KKX5kRoicO-knYT:b-qlul6y) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/tmpfs/fs.c#L244)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we copy rest of the `*time` fields?
</blockquote></details>

We don't copy anything, we update the change time[1] after the file has been renamed. The modify time and access time remain the same.

[1] When renaming, apparently we update "change time", not "modify time". Fixed.
___
*[LibOS/shim/src/sys/shim_clone.c, line 129 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuveJ0b4l6X71-aU72S:-Muz0KoO85A6Jjfe1b0X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/sys/shim_clone.c#L129)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment here why we take this lock here.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 238 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvepnT2CiMpYM_mmZc:-Muz0tbl4_7a6F52v99Q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/test/regression/test_libos.py#L238)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`self._test_send_handle(path)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 240 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-Muvez_-BOCf5ArtE-42:-Muz0u1p07esSMGwqToc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/test/regression/test_libos.py#L240)):*
<details><summ [...]

2022-02-03 11:36 UTC, mkow submitted a review, later dismissed
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 15 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-02-03 16:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: 4 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_util.c, line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvE9i6CiOwf87rrVe_:-Mv-MY4bAynaR67BFAnc:b-g1brus) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is that rest of the code base always assumed that you can take `handle->lock`. Note we need some form of global ordering of locks, usually it's easy, because locks are private for some subsystem and you should not hold any other locks when calling functions exported/globally visible from that subsystem. `shim_handle` is one important exception - it's used across LibOS, so it was the easiest to make it this "last level"/"last taken" lock.
Maybe we can have the current version and just specify that `inode` lock is taken after `hdl`, but it's hard for me to prove that there are no cycles.
Is there any problem with taking these two locks in `inode` -> `hdl` order? From what I understand `hdl->inode` is constant and accessible without any locks.
</blockquote></details>

OK. I don't have a good intuition for what the lock ordering should be. I'm a bit worried about concurrent operations on a single file, but maybe we don't need to deal with that right now.

I reordered these two locks.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-Mv-RqKe4fh0uB82YVjo:b-d1ez68) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
>How about this function does not allocate the buffer, but gets it from the caller. It could also be called with ptr=NULL and size=0 and then return the size needed.

So, a callback that you call twice?
```c
ssize_t (*icheckpoint)(struct inode* inode, void* buf, size_t size);

ssize_t size = inode->fs->ops->icheckpoint(inode, NULL, 0);
if (size < 0)
    return size;
...
ret = inode->fs->ops->icheckpoint(inode, buf, size);
```
Looks pretty ugly... Maybe if we split it into two functions: `icheckpoint_size` and `icheckpoint`? IMO, still not worth it, but I can implement it if you want.

Ideally, I would want something like this:

```c
/* This calls some functions on `cp_store` to reserve a buffer, then writes data to it. */
int (*icheckpoint)(struct inode* inode, struct cp_store* store, void** out_buf);
```

We actually have a similar interface for the checkpoint functions (they take a "size" parameter but it's not used for anything). However, everything is hidden behind layers of macros, which is why I don't want to use it in the current state.

>Actually why? What's the difference of calling a function pointer vs deciding what function to call based on type, in this context?

Because this switch would have to be updated for every filesystem that uses this functionality. And I think it sets a bad precedent: it would be too easy to add custom behavior right inside this switch. Finally, I suspect that it would make it harder to rewrite the checkpointing subsystem when we finally get to it.


<!-- Sent from Reviewable.io -->

2022-02-03 17:36 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 84 at r1](https://reviewable.io/reviews/gramineproject/gramine/297#-MruxArTDANZQARJlA5X:-Mv-dp8_5M-FjodstX3i:bsaixbb) ([raw file](https://github.com/gramineproject/gramine/blob/3fb9cf5c6069af94c78932fff78692c329788dac/LibOS/shim/src/fs/tmpfs/fs.c#L84)):*
> IMO, still not worth it, but I can implement it if you want.

No need, was just an idea. I just don't like this additional malloc (because now we have 3 copies of the same file and if that file is big...), but if everything works, we can live with that.


<!-- Sent from Reviewable.io -->

2022-02-07 07:46 UTC, dimakuv requested changes
> Reviewed 4 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/297#-MvI6p7oBqC7fCuzkHDr):*
`iput` -> `idrop`

Please fix during final rebase.


<!-- Sent from Reviewable.io -->

2022-02-07 08:52 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 18 at r6](https://reviewable.io/reviews/gramineproject/gramine/297#-MvI6p7oBqC7fCuzkHDr):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`iput` -> `idrop`

Please fix during final rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 08:56 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-07 09:25 UTC, merged

2022-02-07 11:23 UTC, mkow reviewed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/297)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 768 at r7](https://reviewable.io/reviews/gramineproject/gramine/297#-MvIuS308KWoicM8kgmg:-MvIuS313tAm28TIsRg3:bep4l9e) ([raw file](https://github.com/gramineproject/gramine/blob/97f8e5db3d5619daed7ee58eb1b2c1c618d197a8/LibOS/shim/src/bookkeep/shim_handle.c#L768)):*
> ```C
>         if (hdl->inode) {
>             /* NOTE: Checkpointing `inode` will take `inode->lock`, so we need to do it after
>              * `hdl->lock` is released. */
> ```

Hmm, is this correct? What something inside `hdl` changes between the code above and checkpointing below, in that window where we don't have the lock?
___
*[LibOS/shim/src/fs/shim_fs_util.c, line 93 at r4](https://reviewable.io/reviews/gramineproject/gramine/297#-MuvE9i6CiOwf87rrVe_:-MvIu9Uu4OszfYcMcmTb:bccvi0c) ([raw file](https://github.com/gramineproject/gramine/blob/6efc0459200967ae77471d750e886a1186c10f23/LibOS/shim/src/fs/shim_fs_util.c#L93)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. I don't have a good intuition for what the lock ordering should be. I'm a bit worried about concurrent operations on a single file, but maybe we don't need to deal with that right now.

I reordered these two locks.
</blockquote></details>

We should implement a lockdep-like checker at some point...


<!-- Sent from Reviewable.io -->