[LibOS] Rewrite `AEVENTTYPE` and [PAL] Remove pipeprv and friends
gramineproject/gramine pull request #298
Opened 2021-12-22 14:03 UTC by boryspoplawski

## Description of the changes 
`AEVENTTYPE` was renamed to `shim_pollable_event` and rewritten. As a consequence we could get rid of `PAL_TYPE_PIPEPRV` pipes from all PALs and some complex code that only these pipes depended on.

2021-12-23 09:01 UTC, dimakuv requested changes
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MraMjES3LdQFtfq5dSI:-MraMjES3LdQFtfq5dSJ:boe029g) (no related file):*
This PR rocks!

---
___
*[LibOS/shim/src/shim_pollable_event.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraOw7W5PIw_moHrBcZ:-MraOw7W5PIw_moHrBc_:b91ugwr) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/LibOS/shim/src/shim_pollable_event.c#L28)):*
> ```C
>     if (ret < 0) {
>         log_error("%s: DkStreamOpen failed: %d", __func__, ret);
>         DkObjectClose(srv_handle);
> ```

This should be removed.
___
*[LibOS/shim/src/shim_pollable_event.c, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraOdby31ry0F2kt2xm:-MraOdby31ry0F2kt2xn:b-3gkbot) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/LibOS/shim/src/shim_pollable_event.c#L33)):*
> ```C
> 
>     PAL_HANDLE read_handle;
>     ret = DkStreamWaitForClient(srv_handle, &read_handle, PAL_OPTION_NONBLOCK);
> ```

Why is the read handle nonblocking? Aren't you supposed to block if there was no event (= no write on the other end of the pipe)?

And doesn't it mean that `wait_pollable_event()` will burn cycles instead of sleeping?
___
*[LibOS/shim/src/shim_pollable_event.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraNfYH-BdXkFASPwJu:-MraNfYH-BdXkFASPwJv:bjhzivo) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/LibOS/shim/src/shim_pollable_event.c#L45)):*
> ```C
> 
> out:;
>     int tmp_ret = DkStreamDelete(srv_handle, PAL_DELETE_ALL);
> ```

I guess you took inspiration from `shim_pipe.c: create_pipes()`.

You added this correct handling of `DkStreamDelete()` failure here. Could you also change `create_pipes()` error handling in a similar way? https://github.com/gramineproject/gramine/blob/703a4944e660173e50a55a3726bca22548a26dad/LibOS/shim/src/sys/shim_pipe.c#L92
___
*[LibOS/shim/src/shim_pollable_event.c, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraPc0X10tGkb-c1cS-:-MraPc0X10tGkb-c1cS0:b-11ytip) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/LibOS/shim/src/shim_pollable_event.c#L71)):*
> ```C
>         }
>         if (size == 0) {
>             return -EINVAL;
> ```

Is this scenario possible?
___
*[Pal/src/host/Linux/db_files.c, line 246 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraRLTt7bKqDYJQHtZG:-MraRLTu8FtIePjw4nUi:bqf9dkb) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/db_files.c#L246)):*
> ```C
> 
> static int file_attrsetbyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     int fd = handle->file.fd, ret;
> ```

Since we're here, could you split into two lines?
___
*[Pal/src/host/Linux/db_object.c, line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraS4wuDjYy8fo6fy36:-MraS4wuDjYy8fo6fy37:beyuqbk) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/db_object.c#L56)):*
> ```C
>             int fdevents = 0;
> 
>             // TODO: why does these check for flags?
> ```

Good question. I think the checks for `flags` are not needed here. We should test it one day, in a separate PR.
___
*[Pal/src/host/Linux/db_pipes.c, line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraSuSt4Q74BGpBGQWT:-MraSuSt4Q74BGpBGQWU:b-tqlenu) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/db_pipes.c#L306)):*
> ```C
>     }
> 
>     /* other types of pipes have a single underlying FD, shut it down */
> ```

This comment makes no sense now, please remove.
___
*[Pal/src/host/Linux/db_pipes.c, line 371 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraTTiT54SPvzw54IVM:-MraTTiT54SPvzw54IVN:bcth2js) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/db_pipes.c#L371)):*
> ```C
>  */
> static int pipe_attrsetbyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     if (handle->generic.fd == PAL_IDX_POISON)
> ```

You should not use `generic.fd` in this file. Now you only have one PAL type used in this file: `pipe`, so replace with `pipe.fd`.

Here and everywhere in this file (and similar file in Linux-SGX).
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-MraUG-vEhOkXLXEs2hG:b-pml52n) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/db_streams.c#L340)):*
> ```C
>         handle->generic.fd = *(int*)CMSG_DATA(control_hdr);
>     } else {
>         HANDLE_HDR(handle)->flags &= ~(PAL_HANDLE_FD_READABLE | PAL_HANDLE_FD_WRITABLE);
> ```

That's actually interesting... We disallow read/write on a handle that was sent by the parent and that doesn't have an underlying host FD. I don't think this is a good thing (maybe we will have "pseudo-handles" in the future where reads/writes are resolved purely inside the PAL?).

Maybe add a FIXME comment?
___
*[Pal/src/host/Linux/pal_host.h, line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUhBC5OS3JlzvnGzt:-MraUhBC5OS3JlzvnGzu:b1f7vm8) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux/pal_host.h#L114)):*
> ```objc
> #define PAL_HANDLE_FD_READABLE  1
> #define PAL_HANDLE_FD_WRITABLE  2
> #define PAL_HANDLE_FD_ERROR     4
> ```

Shouldn't these three be located in public PAL header (`pal/pal.h`)?
___
*[Pal/src/host/Linux-SGX/db_pipes.c, line 462 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraVKUd8qr1EOEiOBaU:-MraVKUd8qr1EOEiOBaV:b-a7d4mv) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux-SGX/db_pipes.c#L462)):*
> ```C
>  */
> static int pipe_attrsetbyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     if (handle->generic.fd == PAL_IDX_POISON)
> ```

Ditto (`generic.fd` -> `pipe.fd`)

Everywhere in this file
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 278 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraVZk3ASCoprYqLhwf:-MraVZk3ASCoprYqLhwg:bhfq6p5) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux-SGX/db_streams.c#L278)):*
> ```C
>     }
> 
>     /* construct ancillary data wtih FD-to-transfer in a control message */
> ```

typo: `with`
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 385 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraWGit3EM3xL8XBvDU:-MraWGit3EM3xL8XBvDV:b-nfflz7) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux-SGX/db_streams.c#L385)):*
> ```C
>         handle->generic.fd = host_fd;
>     } else {
>         HANDLE_HDR(handle)->flags &= ~(PAL_HANDLE_FD_READABLE | PAL_HANDLE_FD_WRITABLE);
> ```

ditto (add some FIXME comment)
___
*[Pal/src/host/Linux-SGX/pal_host.h, line 143 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraWMhJEbv38Oz0KA2x:-MraWMhJEbv38Oz0KA2y:b-astazj) ([raw file](https://github.com/gramineproject/gramine/blob/f6242a539a792bc4fde336b9b55021b339fa8f45/Pal/src/host/Linux-SGX/pal_host.h#L143)):*
> ```objc
> #define PAL_HANDLE_FD_READABLE  1
> #define PAL_HANDLE_ [...]

2021-12-23 12:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbGaMz98JBTEcB2ffx:-MrbGaMz98JBTEcB2ffy:b-hplp8e) (no related file):*
@dimakuv sorry for force-pushing after you reviewed it, but GH stashed some commits from the PR this was based on after changing base from that PR to master. No idea why, it used to work before.

---


<!-- Sent from Reviewable.io -->

2021-12-23 12:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbGaMz98JBTEcB2ffx:-MrbHFlU00UUxPIbGVPx:bsr2tyx) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv sorry for force-pushing after you reviewed it, but GH stashed some commits from the PR this was based on after changing base from that PR to master. No idea why, it used to work before.
</blockquote></details>

Forgot to mention: I did not add any changes in this push, just rebased

---


<!-- Sent from Reviewable.io -->

2021-12-23 13:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: 35 of 41 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbRXT-4BD-1rhOY3Bz:-MrbRXT-4BD-1rhOY3C-:b-ad9ktm) (no related file):*
SGX-sanitizers is failing, blocking myself until I debug it.

---
___
*[LibOS/shim/include/shim_pollable_event.h, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbM30zE6Rh2kz27JR-:-MrbM31-C9LtSwmEZ6gp:bb1llda) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/include/shim_pollable_event.h#L31)):*
> ```objc
> int wait_pollable_event(struct shim_pollable_event* event);
> int clear_pollable_event(struct shim_pollable_event* event);
> ```

I wonder: maybe it's worth adding a getter function for `read_handle` so that users of this doesn't need to use that name directly? E.g.
```
static inline PAL_HANDLE pollable_event_get_poll_handle(struct shim_pollable_event* event) {
    return event->read_handle;
}
```
___
*[LibOS/shim/src/shim_pollable_event.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraOw7W5PIw_moHrBcZ:-MrbI8Xb5-tvCN0svxzY:bw10jn4) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be removed.
</blockquote></details>

Oops, done.
___
*[LibOS/shim/src/shim_pollable_event.c, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraOdby31ry0F2kt2xm:-MrbJ0Hi5iggyg_lqSZY:b-2ucoj9) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is the read handle nonblocking? Aren't you supposed to block if there was no event (= no write on the other end of the pipe)?

And doesn't it mean that `wait_pollable_event()` will burn cycles instead of sleeping?
</blockquote></details>

If you look at the current usage of these events, you will notice they call `wait_pollable_event` only after a successful poll. This version is only temporary - next PR (which rewrites epoll), will completely remove `wait_pollable_event` and change semantics of these events. They will no longer be counting semaphores and they will provide just 3 operations: set/wakeup + clear + poll (actually just ability to use them in generic poll). Unfortunately it cannot be done atm (due to how epoll uses them).
___
*[LibOS/shim/src/shim_pollable_event.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraNfYH-BdXkFASPwJu:-MrbKqt38k8wDUKnpmyF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess you took inspiration from `shim_pipe.c: create_pipes()`.

You added this correct handling of `DkStreamDelete()` failure here. Could you also change `create_pipes()` error handling in a similar way? https://github.com/gramineproject/gramine/blob/703a4944e660173e50a55a3726bca22548a26dad/LibOS/shim/src/sys/shim_pipe.c#L92
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_pollable_event.c, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraPc0X10tGkb-c1cS-:-MrbL16cChuRDbiLY_ov:bod26ky) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this scenario possible?
</blockquote></details>

Everything is possible. Pipe could be full due to something setting events like crazy or malicious host could return `0`.
___
*[Pal/src/host/Linux/db_files.c, line 246 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraRLTt7bKqDYJQHtZG:-MrbNCrYB95ZBzM33BSh:bfjwopp) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_files.c#L246)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, could you split into two lines?
</blockquote></details>

Done.
Btw our guidelines doesn't mention this construct is not allowed.
___
*[Pal/src/host/Linux/db_object.c, line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraS4wuDjYy8fo6fy36:-MrbNPRuCuV2gAv57Feu:b-inp63c) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_object.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good question. I think the checks for `flags` are not needed here. We should test it one day, in a separate PR.
</blockquote></details>

Yes, I have plans to clean up all of these DkSomethingWait functions.
___
*[Pal/src/host/Linux/db_pipes.c, line 306 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraSuSt4Q74BGpBGQWT:-MrbOhsgD-EkYTu-Jw6J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_pipes.c#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment makes no sense now, please remove.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_pipes.c, line 371 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraTTiT54SPvzw54IVM:-MrbPBlPAVb_sOovxLch:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_pipes.c#L371)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should not use `generic.fd` in this file. Now you only have one PAL type used in this file: `pipe`, so replace with `pipe.fd`.

Here and everywhere in this file (and similar file in Linux-SGX).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-MrbPbQ0-d53GQTX0PlL:bb538bm) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's actually interesting... We disallow read/write on a handle that was sent by the parent and that doesn't have an underlying host FD. I don't think this is a good thing (maybe we will have "pseudo-handles" in the future where reads/writes are resolved purely inside the PAL?).

Maybe add a FIXME comment?
</blockquote></details>

I think these flags don't mean that the handle is not readable/writable, but the underlying host fd is (hence I put FD in the name). If it's neither writable nor readable, then there is no underlying host fd at all.
___
*[Pal/src/host/Linux/pal_host.h, line 114 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUhBC5OS3JlzvnGzt:-MrbQ1c31G4ENFZwsIzj:btso15j) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/pal_host.h#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't these three be located in public PAL header (`pal/pal.h`)?
</blockquote></details>

No, this are PAL internals. They describe host fd not  [...]

2021-12-23 14:44 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_pollable_event.h, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbM30zE6Rh2kz27JR-:-MrbioIf7yMebTZilol0:bvia9rv) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/include/shim_pollable_event.h#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I wonder: maybe it's worth adding a getter function for `read_handle` so that users of this doesn't need to use that name directly? E.g.
```
static inline PAL_HANDLE pollable_event_get_poll_handle(struct shim_pollable_event* event) {
    return event->read_handle;
}
```
</blockquote></details>

I don't see a point in this. I highly dislike these Java-style getter/setter functions.
___
*[LibOS/shim/src/shim_pollable_event.c, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraPc0X10tGkb-c1cS-:-MrbjCFDDgROgXrAXS1e:b-pw6ygd) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Everything is possible. Pipe could be full due to something setting events like crazy or malicious host could return `0`.
</blockquote></details>

Technically malicious host is not supposed to be able to return `0` since all our pipes are encrypted (now, with this PR). But I see your point.
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-Mrbjkdo8fMd6y5Uwt1S:b-stxnfb) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think these flags don't mean that the handle is not readable/writable, but the underlying host fd is (hence I put FD in the name). If it's neither writable nor readable, then there is no underlying host fd at all.
</blockquote></details>

Ah, yes, this explanation makes sense.


<!-- Sent from Reviewable.io -->

2021-12-23 22:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_pollable_event.c, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraPc0X10tGkb-c1cS-:-MrdJ2dPDvNuZgHWXksr:b1459vp) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically malicious host is not supposed to be able to return `0` since all our pipes are encrypted (now, with this PR). But I see your point.
</blockquote></details>

What encryption has to do with returning `0`? It's the length/return value, not the content itself
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-MrdJE1dBP_eoRLZ7x8F:bnk9xs7) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, yes, this explanation makes sense.
</blockquote></details>

This convention seems to be followed everywhere in codebase, but I didn't see it documented anywhere. Maybe it's time to add it (a comment), but the question is where exactly?


<!-- Sent from Reviewable.io -->

2021-12-24 19:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbRXT-4BD-1rhOY3Bz:-MrheheH7hdSalBaEe_y:b-tlo202) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

SGX-sanitizers is failing, blocking myself until I debug it.
</blockquote></details>

It seems that our mbedtls wrappers are not thread-safe. I thought we fixed that at some point? Or I might have misunderstood mbedtls code, but it seemed like it copies data on each write call to some internal buffers that are stored in context - without any locking, so 2 threads trying to call write on the very same ssl context can blow this up. Anyway, if you create an app that writes to a pipe from multiple threads it fails (with some mbedtls internal error which is translated to EPERM) on the current master.

---


<!-- Sent from Reviewable.io -->

2021-12-27 07:37 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbRXT-4BD-1rhOY3Bz:-MruoPnx9pRTwe6jbkxW:bd23m1j) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It seems that our mbedtls wrappers are not thread-safe. I thought we fixed that at some point? Or I might have misunderstood mbedtls code, but it seemed like it copies data on each write call to some internal buffers that are stored in context - without any locking, so 2 threads trying to call write on the very same ssl context can blow this up. Anyway, if you create an app that writes to a pipe from multiple threads it fails (with some mbedtls internal error which is translated to EPERM) on the current master.
</blockquote></details>

We never fixed this:
- https://github.com/gramineproject/graphene/issues/2058
- https://github.com/gramineproject/graphene/pull/2059

I had one attempt at this, but that initial attempt wasn't too good. So I got distracted by something else. Is it time to revive the effort?

---
___
*[LibOS/shim/src/shim_pollable_event.c, line 71 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraPc0X10tGkb-c1cS-:-MrunIam3gERhJdbv9xG:biw598) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/LibOS/shim/src/shim_pollable_event.c#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What encryption has to do with returning `0`? It's the length/return value, not the content itself
</blockquote></details>

Ah, yes, we're talking about the return value of the system call. Misread your comment.
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-Mrung5nAdygF8uG1AEV:bf5sd3x) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This convention seems to be followed everywhere in codebase, but I didn't see it documented anywhere. Maybe it's time to add it (a comment), but the question is where exactly?
</blockquote></details>

https://github.com/gramineproject/gramine/blob/b807fa805608f3fd9cf83a6c829472ac2f2cff99/Pal/include/pal/pal.h#L48 -- here? But in a host-agnostic way. Like, "the flags can be whatever, host decides this (typically blabla). LibOS doesn't use this field".

Actually, if these flags are host-specific, then why are these flags in the public (LibOS-visible) interface of the PAL handle? Maybe we should move `flags` to the host-specific part of PAL handles?


<!-- Sent from Reviewable.io -->

2021-12-27 15:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbRXT-4BD-1rhOY3Bz:-MrwXL736kWIIRHG2T_0:b-xebldy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We never fixed this:
- https://github.com/gramineproject/graphene/issues/2058
- https://github.com/gramineproject/graphene/pull/2059

I had one attempt at this, but that initial attempt wasn't too good. So I got distracted by something else. Is it time to revive the effort?
</blockquote></details>

Yes, I think it's time to fix it (otherwise I would have to change this PR to use something else and, frankly speaking, I have no idea what that would be), especially it affects user-facing code (like pipes). I'll try to do that in a separate PR.

---
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-MrwX5qB6j8XVfVdtWHf:buar5nm) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/blob/b807fa805608f3fd9cf83a6c829472ac2f2cff99/Pal/include/pal/pal.h#L48 -- here? But in a host-agnostic way. Like, "the flags can be whatever, host decides this (typically blabla). LibOS doesn't use this field".

Actually, if these flags are host-specific, then why are these flags in the public (LibOS-visible) interface of the PAL handle? Maybe we should move `flags` to the host-specific part of PAL handles?
</blockquote></details>

I'll try to move them, but hopefully they are not set in stone...


<!-- Sent from Reviewable.io -->

2021-12-29 00:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: 18 of 51 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-MrbRXT-4BD-1rhOY3Bz:-Ms20lRq72QWqdlk5UAx:b-5rbke) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, I think it's time to fix it (otherwise I would have to change this PR to use something else and, frankly speaking, I have no idea what that would be), especially it affects user-facing code (like pipes). I'll try to do that in a separate PR.
</blockquote></details>

I've tried doing a generic fix for this, but it turned out to be hard (probably impossible, at least without a major rewrite of PAL layer/PAL API). I ended up just adding locks around accesses to the handles in `shim_pollable_event`.

---
___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-Ms214d_-a6BiNznlRpA:b-myb25n) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll try to move them, but hopefully they are not set in stone...
</blockquote></details>

Done. Please check the newly added commit for details.


<!-- Sent from Reviewable.io -->

2021-12-29 01:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: 39 of 43 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_streams.c, line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/298#-MraUG-vEhOkXLXEs2hF:-Ms2qledDogjWVguyFk5:b-kwn7z) ([raw file](https://github.com/gramineproject/gramine/blob/6d4fe7f459257b3c202249e7d23689fb4c016a8d/Pal/src/host/Linux/db_streams.c#L340)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done. Please check the newly added commit for details.
</blockquote></details>

Moved to another PR: https://github.com/gramineproject/gramine/pull/301 (note it depends on this PR and has its commits squashed into one, so is not ready for review yet).


<!-- Sent from Reviewable.io -->

2021-12-29 07:49 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, 21 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms49SWmCNE3yCh2iC7C:bia0jwh) (no related file):*
So you still have the commit on `Move PAL_HANDLE::flags to host specific part`. Do you want to keep it here or remove, and we'll review a separate PR #301?

---
___
*[Pal/src/host/Linux/pal_host.h, line 35 at r4](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms48eZy4GT7uN3G-Rr-:-Ms48eZz54G1OwAz-oXw:bz9qbg7) ([raw file](https://github.com/gramineproject/gramine/blob/3475048e68f62a1e1b01548837e357f0d587adf6/Pal/src/host/Linux/pal_host.h#L35)):*
> ```objc
> 
>     union {
>         /* Common filed for accessing underlying host fd. See also `PAL_HANDLE_FD_READABLE`. */
> ```

typo: `field`
___
*[Pal/src/host/Linux/pal_host.h, line 116 at r4](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms48qPA08WFJud_21BE:-Ms48qPA08WFJud_21BF:bhavqrb) ([raw file](https://github.com/gramineproject/gramine/blob/3475048e68f62a1e1b01548837e357f0d587adf6/Pal/src/host/Linux/pal_host.h#L116)):*
> ```objc
> 
> /* These two flags indicate whether the underlying host fd of `PAL_HANDLE` is readable and/or
>  * writable respectively. If non of these is set, then the handle has no host-level fd. */
> ```

typo: `none`
___
*[Pal/src/host/Linux-SGX/pal_host.h, line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49Abr2uZf8m3AV4f4:-Ms49Abr2uZf8m3AV4f5:bz9qbg7) ([raw file](https://github.com/gramineproject/gramine/blob/3475048e68f62a1e1b01548837e357f0d587adf6/Pal/src/host/Linux-SGX/pal_host.h#L54)):*
> ```objc
> 
>     union {
>         /* Common filed for accessing underlying host fd. See also `PAL_HANDLE_FD_READABLE`. */
> ```

typo: `field`
___
*[Pal/src/host/Linux-SGX/pal_host.h, line 146 at r4](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49Des1Hn-U52wnips:-Ms49Des1Hn-U52wnipt:bhavqrb) ([raw file](https://github.com/gramineproject/gramine/blob/3475048e68f62a1e1b01548837e357f0d587adf6/Pal/src/host/Linux-SGX/pal_host.h#L146)):*
> ```objc
> 
> /* These two flags indicate whether the underlying host fd of `PAL_HANDLE` is readable and/or
>  * writable respectively. If non of these is set, then the handle has no host-level fd. */
> ```

typo: `none`


<!-- Sent from Reviewable.io -->

2021-12-29 07:55 UTC, dimakuv requested changes
> Reviewed 9 of 30 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms4Ait22wAwi4yQPPHp:bt7c6v7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So you still have the commit on `Move PAL_HANDLE::flags to host specific part`. Do you want to keep it here or remove, and we'll review a separate PR #301?
</blockquote></details>

Hm, I think you broke Reviewable :) It still shows the `Move PAL_HANDLE::flags to host specific part` commit, even though you removed this commit from the git history of your branch. Looks like Reviewable got confused.

If this was indeed you intention, I will unblock all my blocking comments, since they all pertain to that commit.

---


<!-- Sent from Reviewable.io -->

2021-12-29 16:33 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms61FRTB_vjdeqIJkPA:b-bigdpj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I think you broke Reviewable :) It still shows the `Move PAL_HANDLE::flags to host specific part` commit, even though you removed this commit from the git history of your branch. Looks like Reviewable got confused.

If this was indeed you intention, I will unblock all my blocking comments, since they all pertain to that commit.
</blockquote></details>

I've split that commit per @mkow request, since it was pretty unrelated to the rest of the PR, so yeah, that was the intention. I can stash it back here or leave it as it is, up to you

---


<!-- Sent from Reviewable.io -->

2021-12-29 16:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms61b9E76YngJe0QiQm:bz2cl7l) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've split that commit per @mkow request, since it was pretty unrelated to the rest of the PR, so yeah, that was the intention. I can stash it back here or leave it as it is, up to you
</blockquote></details>

Ok, I think I see what happened: look at the file matrix - the last revision is dropped, instead of a new revision with negative changes

---


<!-- Sent from Reviewable.io -->

2021-12-29 17:03 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms67zX33vJ_Qon8UBc9:b-k06w3w) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, I think I see what happened: look at the file matrix - the last revision is dropped, instead of a new revision with negative changes
</blockquote></details>

True, now I understand. It's not a bug, it's a feature :)

I'm unblocking all my comments and approving this PR then.

---


<!-- Sent from Reviewable.io -->

2021-12-29 19:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms6i5Ji-aD7nllxnto9:b9kr5cy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

True, now I understand. It's not a bug, it's a feature :)

I'm unblocking all my comments and approving this PR then.
</blockquote></details>

I'll squash without rebase - this should fix the reviewable (hopefully) without causing issues in review (overall diff should stay the same).

---


<!-- Sent from Reviewable.io -->

2021-12-29 19:58 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: 22 of 52 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms49SWmCNE3yCh2iC7B:-Ms6lOJj4Nz5Y4MKP75I:b-vt657a) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll squash without rebase - this should fix the reviewable (hopefully) without causing issues in review (overall diff should stay the same).
</blockquote></details>

Seems to be better now

---


<!-- Sent from Reviewable.io -->

2021-12-29 23:55 UTC, mkow requested changes
> Reviewed 17 of 40 files at r1, 1 of 6 files at r2, 4 of 4 files at r3, 30 of 30 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/db_object.c, line 51 at r5](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms7ZoLm4r7bn6Mbs1Wt:-Ms7ZoLm4r7bn6Mbs1Wu:b9bqn3r) ([raw file](https://github.com/gramineproject/gramine/blob/2080548429a52657f69898bf45604c42947bde9a/Pal/src/host/Linux-SGX/db_object.c#L51)):*
> ```C
>             continue;
> 
>         /* collect internal-handle FD (only if it iss readable/writable)
> ```

`iss` -> `is`


<!-- Sent from Reviewable.io -->

2021-12-30 00:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_object.c, line 51 at r5](https://reviewable.io/reviews/gramineproject/gramine/298#-Ms7ZoLm4r7bn6Mbs1Wt:-Ms7eGKAAARSF1_Rv79p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2080548429a52657f69898bf45604c42947bde9a/Pal/src/host/Linux-SGX/db_object.c#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`iss` -> `is`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-30 00:49 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-12-30 08:00 UTC, dimakuv approved these changes
> Reviewed 15 of 30 files at r5, 1 of 1 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/298)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-30 15:10 UTC, merged