[LibOS] Return a partial write in do_sendmsg if host-level write was partial
gramineproject/gramine pull request #30
Opened 2021-09-13 10:35 UTC by jkr0103

Signed-off-by: Jitender Kumar <jitender.kumar@intel.com>

## Description of the changes 
Previously, do_sendmsg iterated through all iovec buffers supplied by the user, regardless of whether the host-level write to the socket (via DkStreamWrite) was able to send the whole buffer or only part of the buffer.

This could lead to data corruptions: Graphene would send only some parts of the buffers (i.e., with gaps) but would report to the user app the total sum of sent bytes (i.e., without gaps).

This PR fixes this by simply bailing out on the first encountered host-level partial write.

## How to test this PR? 

Create a communication channel between client and server and send large size data for example 4194299 bytes multiple times.

2021-09-13 11:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTs1Mc2DoIW8rQcvAN):*
The commit message should be re-wrapped for 72 chars per line.

I can do it during the final rebase.


<!-- Sent from Reviewable.io -->

2021-09-13 11:18 UTC, dimakuv commented
Jenkins, test this please

2021-09-13 11:47 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MjTvUaK1UGySTIp_gsI:bcj056y) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
> ```C
> 
>         msg[i].msg_len = bytes;
>         total++;
> ```

Please also bail out here in case of short writes.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1619 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvuAN4cZ1QfwhKYsp:-MjTvuAOAKKkmcNRvN5x:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1619)):*
> ```C
> 
>         msg[i].msg_len = bytes;
>         total++;
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-09-13 11:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTzmky7osYtxJQJoHJ:-MjTzmky7osYtxJQJoHK:bijexud) (no related file):*
We should close these after merging:
- https://github.com/gramineproject/graphene/pull/2679
- https://github.com/gramineproject/graphene/issues/2664

---


<!-- Sent from Reviewable.io -->

2021-09-13 12:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MjU2_u76v94bmXFrhYg:b-lm4nkq) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also bail out here in case of short writes.
</blockquote></details>

@boryspoplawski Are you sure we should do this for `sendmmsg/recvmmsg`? This is what I see in the man page:
```
       The mmsghdr structure is defined in <sys/socket.h> as:

           struct mmsghdr {
               struct msghdr msg_hdr;  /* Message header */
               unsigned int  msg_len;  /* Number of received bytes for header */
           };

... The msg_len field is the number of bytes returned for the message in the entry.  This  field  has  the  same
       value as the return value of a single recvmsg(2) on the header. ...

... On success, recvmmsg() returns the **number of messages** received in msgvec...
```

To me, the current implementation looks correct.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1619 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvuAN4cZ1QfwhKYsp:-MjU2se42J8demF-yxF7:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1619)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2021-09-13 13:25 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MjUJP2O7I-LwTWj03iJ:b-c4vavl) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Are you sure we should do this for `sendmmsg/recvmmsg`? This is what I see in the man page:
```
       The mmsghdr structure is defined in <sys/socket.h> as:

           struct mmsghdr {
               struct msghdr msg_hdr;  /* Message header */
               unsigned int  msg_len;  /* Number of received bytes for header */
           };

... The msg_len field is the number of bytes returned for the message in the entry.  This  field  has  the  same
       value as the return value of a single recvmsg(2) on the header. ...

... On success, recvmmsg() returns the **number of messages** received in msgvec...
```

To me, the current implementation looks correct.
</blockquote></details>

1) It would make little sense: first partial read/write would desync all other, just like in the case of iovec in `sendmsg`.
2) I'm not familiar with all that code, but I think linux does: https://elixir.bootlin.com/linux/v5.14.3/source/net/socket.c#L2546

Probably would be good to test in practice.


<!-- Sent from Reviewable.io -->

2021-09-20 11:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-Mk1qZV4D0i4mnQuI9fc:b-77jwxt) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

linux man page say about return value:
       On success, sendmmsg() returns the number of messages sent from
       msgvec; if this is less than vlen, the caller can retry with a
       further sendmmsg() call to send the remaining messages.

but recvmmsg doesn't have similar saying about RETURN value.

I will give it a try and post the results here.

</blockquote></details>

Seems I was wrong, the current version is correct (checked empirically what Linux does). If the socket is non-blocking, one of the `do_sendmsg` should return `-EAGAIN` and correctly end the loop.


<!-- Sent from Reviewable.io -->

2021-09-20 12:03 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-Mk24ckT7mmZ0Ct0SqNP:bgzmll3) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Seems I was wrong, the current version is correct (checked empirically what Linux does). If the socket is non-blocking, one of the `do_sendmsg` should return `-EAGAIN` and correctly end the loop.
</blockquote></details>

If this is that weird, maybe we should add a test for this?


<!-- Sent from Reviewable.io -->

2021-09-23 10:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103 and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MkH5LYw5WBFc-pwV3ub:b-1127mu) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this is that weird, maybe we should add a test for this?
</blockquote></details>

I don't think there is anything weird here. Also, it will be hard/impossible to test a partial write/read (how many bytes can be received/sent depends on the host). So I don't think we should do anythin in these funcs.

@jkr0103 You mentioned that you would look into this. Any results?


<!-- Sent from Reviewable.io -->

2021-09-23 10:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103 and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MkH5vTE7TfAuHZP0TXF:be5ckt2) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think there is anything weird here. Also, it will be hard/impossible to test a partial write/read (how many bytes can be received/sent depends on the host). So I don't think we should do anythin in these funcs.

@jkr0103 You mentioned that you would look into this. Any results?
</blockquote></details>

@mkow @boryspoplawski Just to expand: I would like to merge this PR before the release. As far as this PR doesn't break anything, we should consider it mergeable. The fact that there are some other possible bugs (which looks like there are not, but even if they are) doesn't mean we should hinder this PR. In the worst case, we should open a new issue to investigate the behavior. But I'd like this PR to be merged soon-ish.


<!-- Sent from Reviewable.io -->

2021-09-23 10:46 UTC, jkr0103 commented
@dimakuv I have created cleint/server for testing partial read/write in `sendmsg` and `recvmsg` . I could hit partial read case with these test clients. Partial write case I was able to test with the grpc test suite shared by the same person who logged the bug #2664.
I tried to create tests clients for `sendmmsg` and `revcmmsg` but it was hard to repro the partial read/write scenario. I talked to Borys regarding that, he tested the scenaio from his end and already have shared outcome above.

2021-09-27 10:25 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103 and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1295 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTvUaK1UGySTIp_gsH:-MkamSFC2wP4EaE2ZzLp:b-8f68vz) ([raw file](https://github.com/gramineproject/gramine/blob/bd6e5bec231ea6ad2531f1d86291e55c60d91b0a/LibOS/shim/src/sys/shim_socket.c#L1295)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @boryspoplawski Just to expand: I would like to merge this PR before the release. As far as this PR doesn't break anything, we should consider it mergeable. The fact that there are some other possible bugs (which looks like there are not, but even if they are) doesn't mean we should hinder this PR. In the worst case, we should open a new issue to investigate the behavior. But I'd like this PR to be merged soon-ish.
</blockquote></details>

(Please note that @jkr0103 replied in the top-level comment, not here.)


<!-- Sent from Reviewable.io -->

2021-09-27 13:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/30#-MjTs1Mc2DoIW8rQcvAN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The commit message should be re-wrapped for 72 chars per line.

I can do it during the final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-09-27 16:12 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-09-27 16:42 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-09-27 17:59 UTC, dimakuv commented
Jenkins, test this please

2021-09-27 21:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/30)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-28 06:03 UTC, merged