[Pal] Move PAL_HANDLE::flags to host specific part
gramineproject/gramine pull request #301
Opened 2021-12-29 01:20 UTC by boryspoplawski

## Description of the changes 

These flags were host specific, yet defined in common `PAL_HDR`. This commit also makes `PAL_HANDLE` an opaque type that cannot be accessed from non PAL code (e.g. LibOS).

2021-12-31 00:45 UTC, mkow requested changes
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Documentation/pal/host-abi.rst, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCtBzaCzDtdkA421ph:-MsCtBzb3XXauC1LWiY4:bwygc4h) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Documentation/pal/host-abi.rst#L59)):*
> The actual memory allocated for the PAL handles may be variable-sized.

Would be good to mention `HANDLE_SIZE()` here, which is part of the API.
___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsCqHsy66_houLlT-g0:bq6a2vk) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
> ```C
>     struct shim_palhdl_entry* entry = (void*)(base + off);
> 
>     entry->handle  = *(PAL_HANDLE*)obj;
> ```

Does this always work? Are all the allocations for PAL handles present in the checkpointed memory and can't disappear for some reason? What if a handle was allocated on a stack? Does this still work then?
___
*[Pal/include/pal/pal.h, line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqw4i9xB4FBmkZ5ox:-MsCqw4i9xB4FBmkZ5oy:bts5qy0) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/include/pal/pal.h#L47)):*
> ```objc
> #define HANDLE_HDR(handle) (&((handle)->hdr))
> #define PAL_GET_TYPE(h) (HANDLE_HDR(h)->type)
> #define UNKNOWN_HANDLE(handle) (PAL_GET_TYPE(handle) >= PAL_HANDLE_TYPE_BOUND)
> ```

One of the following please:



_Suggestion (i):_
```objc
#define IS_UNKNOWN_HANDLE(handle) (PAL_GET_TYPE(handle) >= PAL_HANDLE_TYPE_BOUND)
```



_Suggestion (ii):_
```objc
#define IS_HANDLE_UNKNOWN(handle) (PAL_GET_TYPE(handle) >= PAL_HANDLE_TYPE_BOUND)
```


<!-- Sent from Reviewable.io -->

2022-01-03 07:59 UTC, dimakuv requested changes
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[Documentation/pal/host-abi.rst, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCtBzaCzDtdkA421ph:-MsTr_BjE2Z4XgnmMcf_:b-tghv6h) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Documentation/pal/host-abi.rst#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The actual memory allocated for the PAL handles may be variable-sized.

Would be good to mention `HANDLE_SIZE()` here, which is part of the API.
</blockquote></details>

Why is `HANDLE_SIZE` a part of the API? It is not used by LibOS at all.

I would argue that `HANDLE_SIZE` macro should be removed completely and replaced in all PAL code with a simple `sizeof()`.
___
*[LibOS/shim/src/shim_checkpoint.c, line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTtDmZ3DncYGhFcK6X:-MsTtDmZ3DncYGhFcK6Y:b-ezso3f) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L146)):*
> ```C
> 
> /* Checkpointing mess takes `sizeof(*obj)`, but `PAL_HANDLE` is just opaque pointer, which we do not
>  * know the size of, hence we pass a pointer to it and just dereference it here. */
> ```

To be honest, I don't get this comment. You simply renamed the checkpointing function to better reflect what kind of object it expects (it expects an opaque pointer rather than a pointer to an actual object). However, the comment talks about the size of the PAL handle. Why would you want the reader to know this detail?

What's important here is that this checkpointing function memorizes the opaque pointer to some PAL object in the list of `last_palhdl_entry`, and then another function `send_handles_on_stream()` does the actual job of checkpoint-and-send. So maybe amend your comment to reflect this?
___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsTsN6s4w8ymDCuajCC:b-oncz01) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this always work? Are all the allocations for PAL handles present in the checkpointed memory and can't disappear for some reason? What if a handle was allocated on a stack? Does this still work then?
</blockquote></details>

Yes, it always works because all these collected PAL handles are sent in the checkpoint: https://github.com/gramineproject/gramine/blob/57e5cd3cd48db24f4bb2e8cd9d36b74d5cb2fa6b/LibOS/shim/src/shim_checkpoint.c#L284

Even if a PAL handle would be allocated on stack, it would be sent via `DkSendHandle()` which serializes the handle and then reconstructs it in the child (though I'm pretty sure we do not allocate handles on stack).
___
*[Pal/regression/SendHandle.c, line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTua3FAl4Y7nSlxWfI:-MsTua3FAl4Y7nSlxWfJ:bdsjqij) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L25)):*
> ```C
> 
>             switch (i) {
>                 case 0:;
> ```

Could you add a comment `/* pipe.srv */`
___
*[Pal/regression/SendHandle.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTufND4gskBnXc3wBE:-MsTufND4gskBnXc3wBF:b5givmk) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L40)):*
> ```C
>                     break;
> 
>                 case 1:;
> ```

Could you add a comment `/* udp.srv */`
___
*[Pal/regression/SendHandle.c, line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTukpl4GLFnfo98K9_:-MsTukpl4GLFnfo98K9a:bjrm3ls) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L50)):*
> ```C
>                     break;
> 
>                 case 2:
> ```

Could you add a comment `/* file */`
___
*[Pal/src/host/Linux/db_devices.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTusUP98gN9WJwOWop:-MsTusUP98gN9WJwOWoq:br0pyss) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_devices.c#L36)):*
> ```C
>         return -PAL_ERROR_NOMEM;
> 
>     init_handle_hdr(hdl, PAL_TYPE_DEV);
> ```

I don't see a point in this function; I would prefer an explicit assignment. But this can be another clean-up PR.
___
*[Pal/src/host/Linux/db_files.c, line 347 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvHUc3T8VOdFfeeLv:-MsTvHUc3T8VOdFfeeLw:b-6x3vs3) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_files.c#L347)):*
> ```C
>         return -PAL_ERROR_NOMEM;
>     }
>     init_handle_hdr(hdl, PAL_TYPE_DIR);
> ```

Can you add an emply line before this one?
___
*[Pal/src/host/Linux/db_main.c, line 280 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvEf-8BiycapJPRFy:-MsTvEf-8BiycapJPRFz:b-6x3vs3) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_main.c#L280)):*
> ```C
>     if (!first_thread)
>         INIT_FAIL(PAL_ERROR_NOMEM, "Out of memory");
>     init_handle_hdr(first_thread, PAL_TYPE_THREAD);
> ```

Can you add an emply line before this one?
___
*[Pal/src/host/Linux/pal_host.h, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTwNTpDq28DLvSS0NY:-MsTwNTpDq28DLvSS0NZ:bl91aza) ([raw file](https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/Pal/src/host/Linux/pal_host.h#L24)):*
> ```objc
> } PAL_PIPE_NAME;
> 
> typedef struct pal_handle {
> ```

Why not keep this `pal_handle`? I think we actually want to move away from `PAL_HANDLE` in favor of `struct pal_handle` (as we do with all other such types).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 899 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvmcr6qcEulinNWgL:-MsTvmcr6qcEulinNWgM:b-6x3vs3) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux-SGX/db_main.c#L899)):*
> ```C
>         ocall_exit(1, /*is_exitgroup=*/true);
>     }
>     init_handle_hdr(first_thread, PAL_TYPE_THREAD);
> ```

Can you add an emply line before this one?
___
*[Pal/src/host/Linux-SGX/db_object.c, line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvu_h8mdwRoARNdXk:-MsTvu_h8mdwRoARNdXl:b-txqx0i) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux-SGX/db_object.c#L53)):*
> ```C
>         /* collect internal-handle FD (only if it is readable/writable)
>          * hdl might be a event/non-pollable object, simply ignore it */
>         uint32_t flags = hdl->flags;
> ```

Can we remove this `flags` var and simply use `hdl->flags`?
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 101 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTw6WB8cQflGYPQ_w3:-MsTw6WB8cQflGYPQ_w4:b-6x3vs3) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux-SGX/db_threading.c#L101)):*
> ```C
>     if (!new_thread)
>         return -PAL_ERROR_NOMEM;
>     init_handle_hdr(new_thread, PAL_TYPE_THREAD);
> ```

Can you add an emply line be [...]

2022-01-04 03:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: 25 of 31 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/pal/host-abi.rst, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCtBzaCzDtdkA421ph:-MsY-sfZ91TWRnE3Pjgp:b-rmhku4) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Documentation/pal/host-abi.rst#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is `HANDLE_SIZE` a part of the API? It is not used by LibOS at all.

I would argue that `HANDLE_SIZE` macro should be removed completely and replaced in all PAL code with a simple `sizeof()`.
</blockquote></details>

`HANDLE_SIZE()` is **not** part of the API.
___
*[LibOS/shim/src/shim_checkpoint.c, line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTtDmZ3DncYGhFcK6X:-MsY0JHjDPbKqMwrYjhk:b-q64jqr) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, I don't get this comment. You simply renamed the checkpointing function to better reflect what kind of object it expects (it expects an opaque pointer rather than a pointer to an actual object). However, the comment talks about the size of the PAL handle. Why would you want the reader to know this detail?

What's important here is that this checkpointing function memorizes the opaque pointer to some PAL object in the list of `last_palhdl_entry`, and then another function `send_handles_on_stream()` does the actual job of checkpoint-and-send. So maybe amend your comment to reflect this?
</blockquote></details>

The change I introduced is that we now pass `PAL_HANDLE*` to this function (before we passed `PAL_HANDLE`, which is also a pointer, but it's hidden behind a typedef). The reason is this macro: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/include/shim_checkpoint.h#L256 - it tries to take the size of the object. As you can see below, this size is completely ignored in this function.
Now with other changes in this commit `PAL_HANDLE` is a pointer to an incomplete type inside LibOS and as such we cannot get the size of the underlying type (because there actually is no underlying type). With this change we pass the pointer so that the macro obtains the size of the pointer, not the object. This is legal, but also makes no difference - the size is ignored anyway.
___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsY29QfAV85ikorwuST:bbz0l9p) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
I do not understand what do you mean (actually both of you)...

> Are all the allocations for PAL handles present in the checkpointed memory and can't disappear for some reason? 

What? This is happening in the parent process and it merely dereferences a handle passed by reference (via pointer).

> What if a handle was allocated on a stack? Does this still work then?

I have no idea what you are talking about. What's the difference?

`PAL_HANDLE` is an opaque object, in LibOS we have no idea what it is (it might be a number or a pointer, or whatever).
___
*[Pal/include/pal/pal.h, line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqw4i9xB4FBmkZ5ox:-MsY3N4_54Q5lvSPRNCi:b-b6hof9) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/include/pal/pal.h#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One of the following please:
</blockquote></details>

This was merely moved from a line below.
Do you want to me change it in this PR? I could have a couple more improvements, but they are all unrelated just like this proposed change.
___
*[Pal/regression/SendHandle.c, line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTua3FAl4Y7nSlxWfI:-MsY4YvGAL1edkc7Pnqr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment `/* pipe.srv */`
</blockquote></details>

Done.
___
*[Pal/regression/SendHandle.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTufND4gskBnXc3wBE:-MsY4_zj7s3JKY6CGDaj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment `/* udp.srv */`
</blockquote></details>

Done.
___
*[Pal/regression/SendHandle.c, line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTukpl4GLFnfo98K9_:-MsY4gvJ7SXgzkRuotsN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/regression/SendHandle.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment `/* file */`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTusUP98gN9WJwOWop:-MsY3eFY8ZBXDWv4JBeG:b2obmuc) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_devices.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see a point in this function; I would prefer an explicit assignment. But this can be another clean-up PR.
</blockquote></details>

It would make sense if we had more fields in the header. Some intermediate version had flags there, which `init_handle_hdr` zeroed, but I later changed it (because flags were PAL host specific) to just use `calloc` everywhere.
___
*[Pal/src/host/Linux/db_files.c, line 347 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvHUc3T8VOdFfeeLv:-MsY567S5qwXfNqH5bpr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_files.c#L347)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add an emply line before this one?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 280 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTvEf-8BiycapJPRFy:-MsY5D-x8DOCAgO7XMQQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/src/host/Linux/db_main.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add an emply line before this one?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/pal_host.h, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTwNTpDq28DLvSS0NY:-MsY5H6F3kt3jzkynfr9:b-1wblzh) ([raw file](https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/Pal/src/host/Linux/pal_host.h#L24)):*
> Why not keep this pal_handle?

Because it's not used.

> I think we actually want to move away from PAL_HANDLE in favor of struct pal_handle (as we do with all other such types).

Do we? We need to have some opaque type like (be it `PAL_HANDLE`, `pal_handle_t` or whatever else) for PAL API, so I think it wo [...]

2022-01-04 08:14 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 146 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTtDmZ3DncYGhFcK6X:-MsZ8KyY61vrXzmc4SWx:b-s3ppjj) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L146)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The change I introduced is that we now pass `PAL_HANDLE*` to this function (before we passed `PAL_HANDLE`, which is also a pointer, but it's hidden behind a typedef). The reason is this macro: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/include/shim_checkpoint.h#L256 - it tries to take the size of the object. As you can see below, this size is completely ignored in this function.
Now with other changes in this commit `PAL_HANDLE` is a pointer to an incomplete type inside LibOS and as such we cannot get the size of the underlying type (because there actually is no underlying type). With this change we pass the pointer so that the macro obtains the size of the pointer, not the object. This is legal, but also makes no difference - the size is ignored anyway.
</blockquote></details>

Ok, thanks, I understand now.
___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsZ8ZwJ5WwATCs-WQyw:b-ravffm) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand what do you mean (actually both of you)...

> Are all the allocations for PAL handles present in the checkpointed memory and can't disappear for some reason? 

What? This is happening in the parent process and it merely dereferences a handle passed by reference (via pointer).

> What if a handle was allocated on a stack? Does this still work then?

I have no idea what you are talking about. What's the difference?

`PAL_HANDLE` is an opaque object, in LibOS we have no idea what it is (it might be a number or a pointer, or whatever).
</blockquote></details>

I think Michal was confused "why this CP function doesn't checkpoint the PAL handle object at all, but instead memorizes a pointer to it". I guess Michal missed the fact that PAL handle objects are sent separately, via `DkSendHandle()`.
___
*[Pal/src/host/Linux/pal_host.h, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTwNTpDq28DLvSS0NY:-MsZ7qeS1UBKtwuL4S8A:balxxqg) ([raw file](https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/Pal/src/host/Linux/pal_host.h#L24)):*
> so I think it would like weird if we used different names in PAL and in LibOS.

Yeah, true... Ok, in this particular case it makes sense to have a typedef.
___
*[Pal/src/host/Skeleton/pal_host.h, line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTwe359jhnEDVSF1KK:-MsZ83293RZVaH0UlCnt:b1wxqox) ([raw file](https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/Pal/src/host/Skeleton/pal_host.h#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are all implementation details that are not visible in the common PAL, so we don't have to (and we should not) impose any requirements. Besides, I don't think it was a good skeleton, e.g. Windows PAL would have `fd` fields at all...

I could add a comment listing all types of handles that a new PAL might want to implement.
</blockquote></details>

Please add a comment then.


<!-- Sent from Reviewable.io -->

2022-01-04 09:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: 30 of 31 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsZPHln-ORnPOLQi3_K:b-ipoeq4) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Michal was confused "why this CP function doesn't checkpoint the PAL handle object at all, but instead memorizes a pointer to it". I guess Michal missed the fact that PAL handle objects are sent separately, via `DkSendHandle()`.
</blockquote></details>

Yeah, I think you are right.
Anyway, whatever checkpointing does with `PAL_HANDLE`s, I've not changed that - I've just changed the way one parameter is passed to this function.
___
*[Pal/src/host/Skeleton/pal_host.h, line 65 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsTwe359jhnEDVSF1KK:-MsZRGiU63jZRH1l9KLx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/Pal/src/host/Skeleton/pal_host.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 09:52 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-01-04 11:26 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/pal/host-abi.rst, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCtBzaCzDtdkA421ph:-MsZoYvSA-esJgf2vKPs:b-2u0bss) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Documentation/pal/host-abi.rst#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`HANDLE_SIZE()` is **not** part of the API.
</blockquote></details>

Ah, seems I mis-grepped for it before writing this comment, I thought that I saw an usage in LibOS.
___
*[LibOS/shim/src/shim_checkpoint.c, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqHsxBHW6J8TIEqTk:-MsZp0YKDRsl79Bojmbi:bp2oqr1) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/LibOS/shim/src/shim_checkpoint.c#L152)):*
> I think Michal was confused "why this CP function doesn't checkpoint the PAL handle object at all, but instead memorizes a pointer to it". I guess Michal missed the fact that PAL handle objects are sent separately, via `DkSendHandle()`.

Yes, this.

> I've not changed that - I've just changed the way one parameter is passed to this function.

I know, but I just had a "how is it possible that this works?!?" moment and asked ;)
___
*[Pal/include/pal/pal.h, line 47 at r1](https://reviewable.io/reviews/gramineproject/gramine/301#-MsCqw4i9xB4FBmkZ5ox:-MsZpMMU5oUXJjF7W5XK:b-3psbhp) ([raw file](https://github.com/gramineproject/gramine/blob/ab15b3c8d5de7d078b02514ac0e31e6e7f1f1860/Pal/include/pal/pal.h#L47)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This was merely moved from a line below.
Do you want to me change it in this PR? I could have a couple more improvements, but they are all unrelated just like this proposed change.
</blockquote></details>

Ah, right. Maybe in another PR? (with the other improvements you mentioned) This one looks ready for merging.


<!-- Sent from Reviewable.io -->

2022-01-04 12:15 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-01-04 12:24 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/301)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-04 13:02 UTC, merged