[LibOS] feat: emulate mlock family of syscalls
gramineproject/gramine pull request #309
Opened 2022-01-04 07:13 UTC by lead4good

Part of dotnet bringup, see #48 for details.

2022-01-04 08:40 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @lead4good)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZDYZG9Pcwnzb-guL3:-MsZDYZH16omTRKQVyPG:bxisg3x) (no related file):*
Could you also update the parser? These lines: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/shim_parser.c#L325-L328

In particular, you need to update the `.parser` field -- it must be an array with the first item being the return value, the second item -- the first argument, and so on.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZET5R2OhKh-Di5vS5:-MsZET5S8tl4R6u8cEV4:b-9lx1gp) (no related file):*
Thanks for submitting the PR! Looks good, but needs some small modifications.

When updating this PR, please remember this:
- do *not* use git-merge
- do *not* use git-rebase (we'll do it as the very last step)
- please use git-fixup (see https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash)

For reference, you can check some of our currently pending PRs -- they will give you a template on how to work on PRs. Also, we have this document: https://gramine.readthedocs.io/en/latest/devel/contributing.html

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZBx7C1shaQmgu2rz5):*
Remove `feat`. @lead4good, there is no need for you to do anything with the commit message -- we'll fix it during the final rebase.
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZC4qwAzeAkVotFphY):*
I would add some explanation in the commit message body. Smth like this:
```
Implements mlock, mlock2, munlock, mlockall, munlockall (lock and unlock memory).
These syscalls are stubbed to always return success -- Gramine cannot guarantee that
the host OS will perform lock/unlock anyway, and a malicious OS can still swap pages
anyway.

This (dummy) functionality is required by .NET workloads.
```

@lead4good, there is no need for you to do anything with the commit message -- we'll fix it during the final rebase.
___
*[LibOS/shim/include/shim_table.h, line 140 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZCzZF6qMeNEbP6H4t:-MsZCzZF6qMeNEbP6H4u:b-t6qcvv) ([raw file](https://github.com/gramineproject/gramine/blob/58ed11a969f245b502af875b120a12e2c08498d1/LibOS/shim/include/shim_table.h#L140)):*
> ```objc
> long shim_do_sched_get_priority_min(int policy);
> long shim_do_sched_rr_get_interval(pid_t pid, struct timespec* interval);
> long shim_do_mlock(const void* addr, size_t len);
> ```

`const void*` -> `unsigned long`. For the next function as well.

Please see the Linux sources: https://elixir.bootlin.com/linux/latest/source/include/linux/syscalls.h#L909

(This is not a big difference, but Gramine emulates the Linux kernel, so the Linux sources are the ultimate source of truth for us. When choosing between what's written in Glibc/manpages and what's provided by Linux sources, we always choose the latter.)
___
*[LibOS/shim/src/sys/shim_mlock.c, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZEIOR8KDFrYy_iSTt:-MsZEIOR8KDFrYy_iSTu:bpiujg2) ([raw file](https://github.com/gramineproject/gramine/blob/58ed11a969f245b502af875b120a12e2c08498d1/LibOS/shim/src/sys/shim_mlock.c#L5)):*
> ```C
>  *                    Frieder Paape <frieder@integritee.network>
>  */
> ```

Please add a top-level comment that all below syscalls are currently emulated as no-ops. Basically, copy the commit message body I proposed in another comment.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZE-7uEvJAPC9K0fLW:-MsZE-7uEvJAPC9K0fLX:b-81e81w) ([raw file](https://github.com/gramineproject/gramine/blob/58ed11a969f245b502af875b120a12e2c08498d1/LibOS/shim/src/sys/shim_mlock.c#L10)):*
> ```C
> #include "shim_table.h"
> 
> long shim_do_mlock(__attribute__((unused)) const void* addr, __attribute__((unused)) size_t len) {
> ```

Please don't use `unused` in function arguments. Instead, we use `__UNUSED()` macro like this: https://github.com/gramineproject/gramine/blob/d0af88112ce1291dd2b512145c465e07931198c3/LibOS/shim/src/sys/shim_sched.c#L227
___
*[LibOS/shim/src/sys/shim_mlock.c, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZEE995homh7tq0l-h:-MsZEE9A06zC2DH2fpZJ:b6ydhsd) ([raw file](https://github.com/gramineproject/gramine/blob/58ed11a969f245b502af875b120a12e2c08498d1/LibOS/shim/src/sys/shim_mlock.c#L14)):*
> ```C
> }
> 
> long shim_do_munlock(__attribute__((unused)) const void* addr, __attribute__((unused)) size_t len) {
> ```

ditto (use `__UNUSED` macro)
___
*[LibOS/shim/src/sys/shim_mlock.c, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZEGnn4VBFFfwP2hWa:-MsZEGnn4VBFFfwP2hWb:b6ydhsd) ([raw file](https://github.com/gramineproject/gramine/blob/58ed11a969f245b502af875b120a12e2c08498d1/LibOS/shim/src/sys/shim_mlock.c#L18)):*
> ```C
> }
> 
> long shim_do_mlockall(__attribute__((unused)) int flags) {
> ```

ditto (use `__UNUSED` macro)


<!-- Sent from Reviewable.io -->

2022-01-04 10:45 UTC, lead4good commented
@dimakuv Thanks for the review! I hope I've addressed your comments properly. I also added the mlock2 syscall which I omitted in the previous commit.

2022-01-04 10:52 UTC, dimakuv requested changes
@lead4good Please use Reviewable (there is a button in the PR description -- click it and the Reviewable plugin will open). We do *not* use classic GitHub review process.

While in the Reviewable window, don't forget to reply in comments or simply click "Done" button -- this tells the reviewers what comments you have fixed.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309#-:-MsZgfnkCwPYvbBoSQn9:b-qbmtob)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lead4good)

___
*[LibOS/shim/src/shim_parser.c, line 326 at r2](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZh55w1TrxQTWjcg3H:-MsZh55w1TrxQTWjcg3I:b5rvefc) ([raw file](https://github.com/gramineproject/gramine/blob/3fde67ae156d3fd4ead8bc5d3d5d29ed69133c56/LibOS/shim/src/shim_parser.c#L326)):*
> ```C
>                                     {parse_long_arg, parse_integer_arg, parse_pointer_arg}},
>     [__NR_mlock] = {.slow = false, .name = "mlock", .parser = {parse_long_arg,
> 			parse_pointer_arg, parse_pointer_arg}},
> ```

Please replace tabs with whitespaces. We don't use tabs.
___
*[LibOS/shim/src/shim_parser.c, line 328 at r2](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZh7em3P1NJS2U2SfJ:-MsZh7em3P1NJS2U2SfK:bll7of2) ([raw file](https://github.com/gramineproject/gramine/blob/3fde67ae156d3fd4ead8bc5d3d5d29ed69133c56/LibOS/shim/src/shim_parser.c#L328)):*
> ```C
> 			parse_pointer_arg, parse_pointer_arg}},
>     [__NR_munlock] = {.slow = false, .name = "munlock", .parser = {parse_long_arg,
> 			parse_pointer_arg, parse_pointer_arg}},
> ```

ditto (tabs)
___
*[LibOS/shim/src/shim_parser.c, line 330 at r2](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZh9DFCi8xPEzC_thA:-MsZh9DFCi8xPEzC_thB:bll7of2) ([raw file](https://github.com/gramineproject/gramine/blob/3fde67ae156d3fd4ead8bc5d3d5d29ed69133c56/LibOS/shim/src/shim_parser.c#L330)):*
> ```C
> 			parse_pointer_arg, parse_pointer_arg}},
>     [__NR_mlockall] = {.slow = false, .name = "mlockall", .parser = {parse_long_arg,
> 			parse_integer_arg}},
> ```

ditto (tabs)
___
*[LibOS/shim/src/shim_parser.c, line 570 at r2](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZhbIwDptazTIOc6zC:-MsZhbIwDptazTIOc6zD:bll7of2) ([raw file](https://github.com/gramineproject/gramine/blob/3fde67ae156d3fd4ead8bc5d3d5d29ed69133c56/LibOS/shim/src/shim_parser.c#L570)):*
> ```C
>     [__NR_membarrier] = {.slow = false, .name = "membarrier", .parser = {NULL}},
>     [__NR_mlock2] = {.slow = false, .name = "mlock2", .parser = {parse_long_arg,
> 			parse_pointer_arg, parse_pointer_arg, parse_integer_arg}},
> ```

ditto (tabs)
___
*[LibOS/shim/src/sys/shim_mlock.c, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZhiFO7mLPIJXXRERt:-MsZhiFO7mLPIJXXRERu:byedjkh) ([raw file](https://github.com/gramineproject/gramine/blob/3fde67ae156d3fd4ead8bc5d3d5d29ed69133c56/LibOS/shim/src/sys/shim_mlock.c#L10)):*
> ```C
>  * These syscalls are stubbed to always return success -- Gramine cannot guarantee that
>  * the host OS will perform lock/unlock anyway, and a malicious OS can still swap pages
>  * anyway.
> ```

Please rewrap this text to 100-char-per-line.


<!-- Sent from Reviewable.io -->

2022-01-04 11:58 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lead4good)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZws1e9zkiJKiqlBjp:-MsZws1f8EG6SOUhAYoK:b-nlrsxm) (no related file):*
The PR looks good to me now. Let's see what other reviewers say. Thanks again for contributing!

---


<!-- Sent from Reviewable.io -->

2022-01-04 11:58 UTC, dimakuv commented
Jenkins, test this please

2022-01-04 12:43 UTC, boryspoplawski requested changes
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @lead4good)

___
*[LibOS/shim/src/meson.build, line 88 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_-ch990xI5Yrl5BvN:-Ms_-ch990xI5Yrl5BvO:b-l93qly) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/meson.build#L88)):*
> ```Meson
>     'sys/shim_poll.c',
>     'sys/shim_sched.c',
>     'sys/shim_mlock.c',
> ```

Please keep these sorted.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_5uAr1Na0Pg0lug2U:-Ms_5uAr1Na0Pg0lug2V:b-ylob42) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/sys/shim_mlock.c#L16)):*
> ```C
> #include "shim_table.h"
> 
> long shim_do_mlock(unsigned long start, size_t len) {
> ```

It would be good to add parameters verification to all of these functions, especially to check if `flags` are valid. This way we will catch cases where the Linux kernel adds a flag for which this dummy no-op implementation is not sufficient.


<!-- Sent from Reviewable.io -->

2022-01-05 07:01 UTC, lead4good reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZBx7C1shaQmgu2rz5):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `feat`. @lead4good, there is no need for you to do anything with the commit message -- we'll fix it during the final rebase.
</blockquote></details>

Done.
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZC4qwAzeAkVotFphY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add some explanation in the commit message body. Smth like this:
```
Implements mlock, mlock2, munlock, mlockall, munlockall (lock and unlock memory).
These syscalls are stubbed to always return success -- Gramine cannot guarantee that
the host OS will perform lock/unlock anyway, and a malicious OS can still swap pages
anyway.

This (dummy) functionality is required by .NET workloads.
```

@lead4good, there is no need for you to do anything with the commit message -- we'll fix it during the final rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/meson.build, line 88 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_-ch990xI5Yrl5BvN:-MscncaF8EGDSCcuz3Sg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/meson.build#L88)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please keep these sorted.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_5uAr1Na0Pg0lug2U:-Msd12qm9xJ4QcMVT1Zn:b-87oyvn) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/sys/shim_mlock.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It would be good to add parameters verification to all of these functions, especially to check if `flags` are valid. This way we will catch cases where the Linux kernel adds a flag for which this dummy no-op implementation is not sufficient.
</blockquote></details>

I added checks for the mlockall flags, apparently the only existing mlock2 flag is not valid for the x86/amd64 architecture.
See also: https://patchwork.kernel.org/project/linux-parisc/patch/1439097776-27695-5-git-send-email-emunson@akamai.com/


<!-- Sent from Reviewable.io -->

2022-01-05 07:56 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_5uAr1Na0Pg0lug2U:-MsdD5UOC4PNEjd7JTlf:bsq9i7l) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/sys/shim_mlock.c#L16)):*
<details><summary><i>Previously, lead4good wrote…</i></summary><blockquote>

I added checks for the mlockall flags, apparently the only existing mlock2 flag is not valid for the x86/amd64 architecture.
See also: https://patchwork.kernel.org/project/linux-parisc/patch/1439097776-27695-5-git-send-email-emunson@akamai.com/
</blockquote></details>

From what I see in that link, `MLOCK_ONFAULT` flag for `mlock2()` is valid on x86 architecture -- it is defined in the arch-independent header `include/uapi/asm-generic/mman-common.h`. So this flag is covered for x86 as well (and from my searches on the internet, this flag is indeed used on x86 platforms).

So please add the check for this flag.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 20 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdE34T4JvZ-8OnSmKj:-MsdE34UBiu8CljI3UiP:b-35rb1n) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L20)):*
> ```C
> long shim_do_mlock(unsigned long start, size_t len) {
>     __UNUSED(start);
>     __UNUSED(len);
> ```

Since we're adding parameter verification, please add like this: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_mmap.c#L236-L238

This will cover the error case of:
```
       EINVAL (mlock(), mlock2(), and munlock()) The result of the
              addition addr+len was less than addr (e.g., the addition
              may have resulted in an overflow).
```
___
*[LibOS/shim/src/sys/shim_mlock.c, line 26 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdEHIl2ssZ4QDIp5I9:-MsdEHIl2ssZ4QDIp5IA:b-ymf2qe) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L26)):*
> ```C
> long shim_do_munlock(unsigned long start, size_t len) {
>     __UNUSED(start);
>     __UNUSED(len);
> ```

ditto (parameter verification)
___
*[LibOS/shim/src/sys/shim_mlock.c, line 46 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdEJqz7H3hYXFzJF0K:-MsdEJqz7H3hYXFzJF0L:b-ymf2qe) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L46)):*
> ```C
> long shim_do_mlock2(unsigned long start, size_t len, int flags) {
>     __UNUSED(start);
>     __UNUSED(len);
> ```

ditto (parameter verification)


<!-- Sent from Reviewable.io -->

2022-01-05 10:01 UTC, lead4good reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: 4 of 5 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 16 at r3](https://reviewable.io/reviews/gramineproject/gramine/309#-Ms_5uAr1Na0Pg0lug2U:-Msdfb7w9h8jKgObVhFd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4c287b42ff0080244c26f560c62d35212f043e00/LibOS/shim/src/sys/shim_mlock.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From what I see in that link, `MLOCK_ONFAULT` flag for `mlock2()` is valid on x86 architecture -- it is defined in the arch-independent header `include/uapi/asm-generic/mman-common.h`. So this flag is covered for x86 as well (and from my searches on the internet, this flag is indeed used on x86 platforms).

So please add the check for this flag.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 20 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdE34T4JvZ-8OnSmKj:-Msdfgiz0Bb7EeqElurx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're adding parameter verification, please add like this: https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_mmap.c#L236-L238

This will cover the error case of:
```
       EINVAL (mlock(), mlock2(), and munlock()) The result of the
              addition addr+len was less than addr (e.g., the addition
              may have resulted in an overflow).
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 26 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdEHIl2ssZ4QDIp5I9:-MsdfjN3BdvdW65kwyDo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (parameter verification)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 46 at r4](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdEJqz7H3hYXFzJF0K:-MsdfktF40toMfGITa8O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82c806266a91bf02fa93d859207a3a5681747b3d/LibOS/shim/src/sys/shim_mlock.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (parameter verification)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 10:58 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdsWxb7QgXQnqz56TJ:-MsdsWxb7QgXQnqz56TK:b-8fzzaw) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L14)):*
> ```C
>  */
> 
> #include <asm-generic/mman-common.h>
> ```

Is this header really needed? I understand that it adds `MLOCK_ONFAULT`, but I would expect this header to be already-included by `sys/mman.h`, and so there is no need to include this header explicitly.

Or maybe you need to include `asm/mman.h`? Then you could remove `sys/mman.h` as well.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdsOczDpcDKDCRtXsa:-MsdsOczDpcDKDCRtXsb:b-agvmi2) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L36)):*
> ```C
>     int unknown = flags & ~(MCL_CURRENT | MCL_FUTURE | MCL_ONFAULT);
>     if (unknown != 0) {
>         log_warning("Syscall mlockall was called with unknown flag(s): %d\n", unknown);
> ```

I think `%x` would be better than `%d`. But not blocking, it's a matter of taste (meaning: if you agree that showing a hex number will be better, please replace with `%x`, but if you don't agree, I don't mind).
___
*[LibOS/shim/src/sys/shim_mlock.c, line 50 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-Msds9dQ6-D8dSpaNVpI:-Msds9dQ6-D8dSpaNVpJ:b-agvmi2) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L50)):*
> ```C
>     int unknown = flags & ~MLOCK_ONFAULT;
>     if (unknown != 0) {
>         log_warning("Syscall mlock2 was called with unknown flag(s): %d\n", unknown);
> ```

I think `%x` would be better than `%d`. But not blocking, it's a matter of taste (meaning: if you agree that showing a hex number will be better, please replace with `%x`, but if you don't agree, I don't mind).
___
*[LibOS/shim/src/sys/shim_mlock.c, line 52 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-Msds0oCEcZLUS1V3KFA:-Msds0oCEcZLUS1V3KFB:bewa6t5) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L52)):*
> ```C
>         log_warning("Syscall mlock2 was called with unknown flag(s): %d\n", unknown);
>         return -EINVAL;
>     }
> ```

Could you add an empty line? To visually separate the two checks, for better readability.


<!-- Sent from Reviewable.io -->

2022-01-05 11:03 UTC, lead4good reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: 4 of 5 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdsWxb7QgXQnqz56TJ:-Msdts8m9yr0Q9s-S9Vr:b7bctou) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this header really needed? I understand that it adds `MLOCK_ONFAULT`, but I would expect this header to be already-included by `sys/mman.h`, and so there is no need to include this header explicitly.

Or maybe you need to include `asm/mman.h`? Then you could remove `sys/mman.h` as well.
</blockquote></details>

asm/mman.h includes both, thanks!
___
*[LibOS/shim/src/sys/shim_mlock.c, line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdsOczDpcDKDCRtXsa:-Msdtzz--y8k_fDH0u7a:b-wmf8w6) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think `%x` would be better than `%d`. But not blocking, it's a matter of taste (meaning: if you agree that showing a hex number will be better, please replace with `%x`, but if you don't agree, I don't mind).
</blockquote></details>

I will follow your suggestion.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 52 at r5](https://reviewable.io/reviews/gramineproject/gramine/309#-Msds0oCEcZLUS1V3KFA:-Msdu4Fo7PAJ8es9ywM_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/55c2aa19bd03fd426c87589ba09f01946c294c17/LibOS/shim/src/sys/shim_mlock.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line? To visually separate the two checks, for better readability.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 11:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsdvxEJ8OQJVm6kCSOw:-MsdvxEKEtchiW-4H85P:b-v9fgs0) (no related file):*
The PR looks good to me (bar the commit message, but we'll fix it during final rebase & merge). Thanks again for the PR!

---


<!-- Sent from Reviewable.io -->

2022-01-05 11:12 UTC, dimakuv commented
Jenkins, test this please

2022-01-05 11:50 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @lead4good)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 19 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse0V4OA7qCBvor1sEL:-Mse0V4OA7qCBvor1sEM:bu6dd17) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L19)):*
> ```C
> 
> long shim_do_mlock(unsigned long start, size_t len) {
>     if (!access_ok((void*)start, len)) {
> ```

Since we use `access_ok`, we have to import `api.h`.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse09EkBOK1JNK65tsM:-Mse09EkBOK1JNK65tsN:b-7y44ja) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L34)):*
> ```C
> long shim_do_mlockall(int flags) {
>     int unknown = flags & ~(MCL_CURRENT | MCL_FUTURE | MCL_ONFAULT);
>     if (unknown != 0) {
> ```

We have a handy macro for such checks: https://github.com/gramineproject/gramine/blob/84b331fe7da92675a888837eb54c2b33a3de4518/common/include/api.h#L87
___
*[LibOS/shim/src/sys/shim_mlock.c, line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse01XC1v9T0GvZbBjf:-Mse01XC1v9T0GvZbBjg:b-pyez3f) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L35)):*
> ```C
>     int unknown = flags & ~(MCL_CURRENT | MCL_FUTURE | MCL_ONFAULT);
>     if (unknown != 0) {
>         log_warning("Syscall mlockall was called with unknown flag(s): %x\n", unknown);
> ```

Please use `%#x` so that the reader knows it's a hexadecimal number.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 48 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse3o9A3SpNqCM33DKl:-Mse3o9A3SpNqCM33DKm:b-si76y2) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L48)):*
> ```C
> long shim_do_mlock2(unsigned long start, size_t len, int flags) {
>     int unknown = flags & ~MLOCK_ONFAULT;
>     if (unknown != 0) {
> ```

ditto (`WITHIN_MASK`)
___
*[LibOS/shim/src/sys/shim_mlock.c, line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse3poA5wYsAlJ973LN:-Mse3poA5wYsAlJ973LO:bjklckw) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L49)):*
> ```C
>     int unknown = flags & ~MLOCK_ONFAULT;
>     if (unknown != 0) {
>         log_warning("Syscall mlock2 was called with unknown flag(s): %x\n", unknown);
> ```

ditto (`%#x`)


<!-- Sent from Reviewable.io -->

2022-01-05 12:22 UTC, lead4good reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: 4 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 19 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse0V4OA7qCBvor1sEL:-MseATzy-TI2UAaa68UM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since we use `access_ok`, we have to import `api.h`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse09EkBOK1JNK65tsM:-MseAYmN6dlPROY-XvlR:b9m60dh) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We have a handy macro for such checks: https://github.com/gramineproject/gramine/blob/84b331fe7da92675a888837eb54c2b33a3de4518/common/include/api.h#L87
</blockquote></details>

I'm not sure if this macro helps here, as I will have to _or_ out the bits to verbosely log the unknown flags.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 35 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse01XC1v9T0GvZbBjf:-MseAUpO76IDs0qXzN6f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `%#x` so that the reader knows it's a hexadecimal number.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 48 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse3o9A3SpNqCM33DKl:-MseB7rD7J3h1YDhDYic:b9m60dh) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`WITHIN_MASK`)
</blockquote></details>

I'm not sure if this macro helps here, as I will have to _or_ out the bits to verbosely log the unknown flags.
___
*[LibOS/shim/src/sys/shim_mlock.c, line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse3poA5wYsAlJ973LN:-MseAVfT33CWllgMHQKZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`%#x`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 12:29 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)



<!-- Sent from Reviewable.io -->

2022-01-05 13:16 UTC, mkow approved these changes
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)



<!-- Sent from Reviewable.io -->

2022-01-05 13:34 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @lead4good)

___
*[LibOS/shim/src/sys/shim_mlock.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/gramine/309#-Mse09EkBOK1JNK65tsM:-MseRAEh2LwluP9KT6I1:b-m8ul1m) ([raw file](https://github.com/gramineproject/gramine/blob/b559706edd364bdd6add88ce009cf4ab3b0353db/LibOS/shim/src/sys/shim_mlock.c#L34)):*
<details><summary><i>Previously, lead4good wrote…</i></summary><blockquote>

I'm not sure if this macro helps here, as I will have to _or_ out the bits to verbosely log the unknown flags.
</blockquote></details>

You can just log `flags` - in case we ever see this message we will have to manually check which flag is this anyway.
But not blocking, this is not really important.


<!-- Sent from Reviewable.io -->

2022-01-06 12:16 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @lead4good)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZBx7C1shaQmgu2rz5):*
<details><summary><i>Previously, lead4good wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/309#-MsZC4qwAzeAkVotFphY):*
<details><summary><i>Previously, lead4good wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-01-06 12:16 UTC, dimakuv commented
Jenkins, test this please

2022-01-06 12:20 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @lead4good)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsjK0BO5giMghLNZaVv:-MsjK0BO5giMghLNZaVw:b-q9745c) (no related file):*
@lead4good: One thing we overlooked: Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can force-push if you choose the former.

---


<!-- Sent from Reviewable.io -->

2022-01-06 12:23 UTC, lead4good reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @lead4good, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/309#-MsjK0BO5giMghLNZaVv:-MsjL6EZ9cCtowRCNnWr:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@lead4good: One thing we overlooked: Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can force-push if you choose the former.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-06 12:32 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-01-06 17:41 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/309)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-06 17:46 UTC, merged

2022-01-07 13:12 UTC, stefanberger commented
Btw, we could enable a couple more ltp tests:

```
$ gramine-direct munlock01
munlock01    1  TPASS  :  test 0 passed length = 1
munlock01    2  TPASS  :  test 1 passed length = 1024
munlock01    3  TPASS  :  test 2 passed length = 1048576
munlock01    4  TPASS  :  test 3 passed length = 10485760
$ gramine-direct munlockall01
munlockall01    1  TPASS  :  munlockall() passed with return=0
$ gramine-direct mlock01
mlock01     1  TPASS  :  mlock passed
mlock01     2  TPASS  :  mlock passed
mlock01     3  TPASS  :  mlock passed
mlock01     4  TPASS  :  mlock passed
$ gramine-direct mlock04
mlock04     0  TINFO  :  locked 40960 bytes from 0x594c55400000
mlock04     1  TPASS  :  test succeeded.
$ gramine-direct mlockall01
mlockall01    1  TPASS  :  mlockall test passed for MCL_CURRENT
mlockall01    2  TPASS  :  mlockall test passed for MCL_FUTURE
mlockall01    3  TPASS  :  mlockall test passed for MCL_CURRENT|MCL_FUTURE
```

2022-01-07 14:51 UTC, boryspoplawski commented
Is it worth it? We will just add CI runtime, but in reality these test nothing...

2022-01-10 08:02 UTC, dimakuv commented
Yeah, I looked at the sources of these tests (`LibOS/shim/test/ltp/src/testcases/kernel/syscalls/munlock/munlock01.c` and so on). The sources of the tests that pass now are basically dummies; they don't test anything really. I don't mind adding these LTP tests, but they look useless for now (unlike `mlock02`, `mlock03` which actually test some real behaviors).