[Pal/Linux-SGX] Fix renaming issue with protected files
gramineproject/gramine pull request #31
Opened 2021-09-13 13:55 UTC by svenkata9

## Description of the changes 
With certain workloads involving Federated Learning, the frameworks create protected files and rename them as part of the flow. This does not work currently with protected files because every protected file maintains the path name in its metadata (stored when the file was first created) and which is checked during open to make sure the incoming path is the same as what is already stored in the metadata for this file.

This PR is to address this issue by handling rename for protected files. A normal rename call does not need the file to be open in RW mode, but since the metadata needs to be updated with the new path, we pass a special `PAL_OPTION_RENAME` flag to `DkStreamOpen` during rename and open the protected file in RW mode with required permissions, update the metadata with the new path and flush it. Then the flow goes through the one for normal file renaming. If the ocall to rename fails, we restore the metadata back to what it was earlier so the file remains usable still.

Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>

2021-09-14 07:16 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY3O7OBllu4yjrkxBw:-MjY3O7P0f7W53Hb7hwv:b-p7b1t1) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/LibOS/shim/src/fs/chroot/fs.c#L204)):*
> ```C
> 
> /* Open a temporary PAL handle for a file (used by `rename`, `unlink` etc.) */
> static int chroot_temp_open(struct shim_dentry* dent, mode_t type, PAL_HANDLE* out_palhdl, int pal_options) {
> ```

Please swap `out_palhdl` and `pal_options` places, like this:
```
static int chroot_temp_open(struct shim_dentry* dent, mode_t type, int pal_options, PAL_HANDLE* out_palhdl) {
```

This is because output arguments should be always the last ones in functions.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6EUq93qU5oQPgyER:-MjY6EUq93qU5oQPgyES:b-3wjsct) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L49)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     /* normalize uri into normpath */
> ```

FYI: You can check the snippet below for the renames I suggest.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 799 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6-HK03E9KoZuG-6M:-MjY6-HK03E9KoZuG-6N:bcbb7fc) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L799)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     char* tmp = strdup(uri);
> ```

This got very hard to understand. Let's rename everything to more meaningful names.

Please rename `tmp` to `new_path` (because that's what it is).
___
*[Pal/src/host/Linux-SGX/db_files.c, line 807 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY4Tbx2mTztI2B9w8L:-MjY4Tbx2mTztI2B9w8M:beza80p) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L807)):*
> ```C
> 
>     /* TODO: Handle the case of renaming a file that has a file handle already open, so that the
>      * file operations work on both the handles properly. */
> ```

This comment is unnecessarily long. Simply:
```
/* TODO: Handle the case of renaming a file that has a file handle already open */
```
___
*[Pal/src/host/Linux-SGX/db_files.c, line 808 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY5-aW0YTd75sc0rhF:-MjY5-aW0YTd75sc0rhG:bn5s0eg) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L808)):*
> ```C
>     /* TODO: Handle the case of renaming a file that has a file handle already open, so that the
>      * file operations work on both the handles properly. */
>     struct protected_file* pf_new;
> ```

Please move this declaration to where you initialize this variable. Like this:
```
struct protected_file* pf_new = get_protected_file(new_path);
```

There is no sense in declaring this variable here, so far away from where it is actually used.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 810 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6A6k7mR_NhRcJK3_:-MjY6A6k7mR_NhRcJK3a:b-7t3av5) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L810)):*
> ```C
>     struct protected_file* pf_new;
>     if (pf) {
>         size_t uri_size = strlen(uri) + 1;
> ```

Please rename `uri_size` to `normpath_size`
___
*[Pal/src/host/Linux-SGX/db_files.c, line 811 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6L7x9aZPXmUsdb3Y:-MjY6L7x9aZPXmUsdb3Z:bh1r6r6) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L811)):*
> ```C
>     if (pf) {
>         size_t uri_size = strlen(uri) + 1;
>         char* new_path = (char*)calloc(1, uri_size);
> ```

Please rename `new_path` to `new_normpath`
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-MjY6hWw9oAAyD4JMQ3p:bsspjkp) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
> ```C
>         if (!new_path) {
>             free(tmp);
>             return -PAL_ERROR_NOMEM;
> ```

All these error handling cases are hard to read now... Please refactor them all to use goto, like in other code snippets.

You will have smth like this in the end:
```
        if (!new_path) {
            ret = -PAL_ERROR_NOMEM;
            goto out;
        }

...

    handle->file.realpath = new_path;
    ret = 0;
out:
    free(new_normpath);
    if (ret < 0)
        free(new_path);
    return ret;
```
___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY7ngoAnAbwcwcGF3O:-MjY7ngpDL1ykFQb_Bhd:bsjx2l7) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L827)):*
> ```C
>         pf_new = get_protected_file(new_path);
>         if (!pf_new) {
>             log_warning("New path is disallowed for protected files (%s)", new_path);
> ```

This message doesn't make sense. I think what you're trying to say here is `New path during rename is not a protected directory (%s)`
___
*[Pal/src/host/Linux-SGX/db_files.c, line 848 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8YhPDIughgMelzpo:-MjY8YhPDIughgMelzpp:b-x4vtj7) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L848)):*
> ```C
>     if (ret < 0) {
>         free(tmp);
>         /* restore the original file name in pf metadata */
> ```

You should only execute this code if `pf != NULL`, otherwise you will do this "rollback PF rename" even for a regular file.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 856 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8lgi2z219Z4V6gZ4:-MjY8lgi2z219Z4V6gZ5:bm3p3jp) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L856)):*
> ```C
>     }
> 
>     /* TODO: Handle file_close for the source file during protected file rename works properly */
> ```

I can't parse this sentence.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 859 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8zGwAWhW3zHOCVMo:-MjY8zGwAWhW3zHOCVMp:b-vdc03p) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L859)):*
> ```C
>     if (pf) {
>         struct protected_file* tmp = pf;
>         pf = pf_new;
> ```

What's the point of this operation?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 860 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY9Cse3o4ItDRGU7QE:-MjY9Cse3o4ItDRGU7QF:b-ev0e14) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L860)):*
> ```C
>         struct protected_file* tmp = pf;
>         pf = pf_new;
>         ret = pf_file_close(tmp, handle);
> ```

Why do you need to close the file?


<!-- Sent from Reviewable.io -->

2021-09-14 11:49 UTC, pwmarcz reviewed
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @svenkata9)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY7ngoAnAbwcwcGF3O:-MjZ766mENiCqku-X5Kg:b-irr5uj) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L827)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This message doesn't make sense. I think what you're trying to say here is `New path during rename is not a protected directory (%s)`
</blockquote></details>

It's not necessarily a directory, though - if the target is `foo/bar`, the `sgx.protected_files` can indeed specify `foo/`, but it can also specify `foo/bar` exactly.

So maybe something like "New path during rename is not specified in 'sgx.protected_files' (%s)"?


<!-- Sent from Reviewable.io -->

2021-09-16 06:18 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: 4 of 6 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 204 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY3O7OBllu4yjrkxBw:-Mjh6mfF34CNTGN-fKAo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/LibOS/shim/src/fs/chroot/fs.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please swap `out_palhdl` and `pal_options` places, like this:
```
static int chroot_temp_open(struct shim_dentry* dent, mode_t type, int pal_options, PAL_HANDLE* out_palhdl) {
```

This is because output arguments should be always the last ones in functions.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 799 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6-HK03E9KoZuG-6M:-Mjh6kEVEfVn1MUPLHnv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L799)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This got very hard to understand. Let's rename everything to more meaningful names.

Please rename `tmp` to `new_path` (because that's what it is).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 807 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY4Tbx2mTztI2B9w8L:-Mjh6iueD3V2iI-hO1eG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L807)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is unnecessarily long. Simply:
```
/* TODO: Handle the case of renaming a file that has a file handle already open */
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 808 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY5-aW0YTd75sc0rhF:-Mjh4Y9w5JnOgsIcG23j:b-b7wh8f) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L808)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this declaration to where you initialize this variable. Like this:
```
struct protected_file* pf_new = get_protected_file(new_path);
```

There is no sense in declaring this variable here, so far away from where it is actually used.
</blockquote></details>

This cannot be done because it needs to be outside the current scope for it to be used later.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 810 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6A6k7mR_NhRcJK3_:-Mjh6onV3TLJVZvOukDd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L810)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `uri_size` to `normpath_size`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 811 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6L7x9aZPXmUsdb3Y:-Mjh6oYr8XaaPtjReVJ3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L811)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `new_path` to `new_normpath`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-Mjh5RFaB91tM_0XyC3X:b-mjr04o) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All these error handling cases are hard to read now... Please refactor them all to use goto, like in other code snippets.

You will have smth like this in the end:
```
        if (!new_path) {
            ret = -PAL_ERROR_NOMEM;
            goto out;
        }

...

    handle->file.realpath = new_path;
    ret = 0;
out:
    free(new_normpath);
    if (ret < 0)
        free(new_path);
    return ret;
```
</blockquote></details>

There is a mixture of (inner/outer) scope here. I would let it the way it is now, and refactor later.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY7ngoAnAbwcwcGF3O:-Mjh6qJ83LST3WJNWx_s:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L827)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's not necessarily a directory, though - if the target is `foo/bar`, the `sgx.protected_files` can indeed specify `foo/`, but it can also specify `foo/bar` exactly.

So maybe something like "New path during rename is not specified in 'sgx.protected_files' (%s)"?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 848 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8YhPDIughgMelzpo:-Mjh6r6-9I6lsG6_YPFl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L848)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should only execute this code if `pf != NULL`, otherwise you will do this "rollback PF rename" even for a regular file.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 856 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8lgi2z219Z4V6gZ4:-Mjh5wf88_Sti5152Pg7:bjbnpcl) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L856)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can't parse this sentence.
</blockquote></details>

Like I said most of the issues that we currently have with protected files is because of the global g_protected_files path that requires unique key and fails when the same file name is provided for multiple simultaneous operations. In this rename case, we have already enumerated and if we close it immediately, some of the issues can be avoided (like the first two cases in rename_unlink will pass only when this is closed here). Like I said earlier, it is a workaround - a proper fix will require reworking g_protected_files to search for the handle (currently it happens based on merely the name).
___
*[Pal/src/host/Linux-SGX/db_files.c, line 859 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8zGwAWhW3zHOCVMo:-Mjh6d8cCOQnKxnNGgSQ:biq8zda) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L859)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this operation?
</blockquote></details>

Explained above
___
*[Pal/src/host/Linux-SGX/db_files.c, line 860 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY9Cse3o4ItDRGU7QE:-Mjh6f214Yymg2YhWJfT:biq8zda) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L860)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuv [...]

2021-09-16 08:26 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 808 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY5-aW0YTd75sc0rhF:-MjhhfrW8m8EQsuzC6YD:bmbh9td) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L808)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

This cannot be done because it needs to be outside the current scope for it to be used later.
</blockquote></details>

You don't really use `pf_new` afterwards (after the line `if (!pf_new) {`). See my other comment.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-MjhfZ8Q-L_NWE27pt-t:b-odhh0w) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

There is a mixture of (inner/outer) scope here. I would let it the way it is now, and refactor later.
</blockquote></details>

OK, personal preference. I'm fine with this way too.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 856 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8lgi2z219Z4V6gZ4:-Mjhgklt1JLghAALRfDH:b1ot6e1) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L856)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Like I said most of the issues that we currently have with protected files is because of the global g_protected_files path that requires unique key and fails when the same file name is provided for multiple simultaneous operations. In this rename case, we have already enumerated and if we close it immediately, some of the issues can be avoided (like the first two cases in rename_unlink will pass only when this is closed here). Like I said earlier, it is a workaround - a proper fix will require reworking g_protected_files to search for the handle (currently it happens based on merely the name).
</blockquote></details>

That I can understand, but the sentence itself is not proper English (or very confusing English).

Is `Handle` a verb here? `works properly` -- what should work properly? Or something already works properly? Please rephrase.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 859 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8zGwAWhW3zHOCVMo:-Mjhh17G0S-4kLfGqRqG:b-ov66tu) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L859)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Explained above
</blockquote></details>

So in this line you're assigning `pf = pf_new`. Why? You don't use `pf` later in the code, so this new value of `pf` is unused and thus meaningless. Why can't you replace this whole IF statement with a more simple one:
```
    if (pf) {
        ret = pf_file_close(pf, handle);
        if (ret < 0)
            log_warning("pf_file_close failed during rename");
    }
```
___
*[Pal/src/host/Linux-SGX/db_files.c, line 860 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY9Cse3o4ItDRGU7QE:-MjhhSUU4R3TgER_cQMw:b-r1ga4) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L860)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Explained above
</blockquote></details>

I'm not sure I understand this, but Ok. We need to change the code of PFs anyway, because indeed there are multiple bugs when two handles for the same PF file are opened simulteneously.


<!-- Sent from Reviewable.io -->

2021-09-16 10:49 UTC, pwmarcz requested changes
> Reviewed 2 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 204 at r2](https://reviewable.io/reviews/gramineproject/gramine/31#-MjiB3mH-2u0pT1ReEM-:-MjiB3mIA7adKKjKzKAY:b-b861d0) ([raw file](https://github.com/gramineproject/gramine/blob/190ec5b377fcb2c2858514d179088e25e96f8462/LibOS/shim/src/fs/chroot/fs.c#L204)):*
> ```C
> 
> /* Open a temporary PAL handle for a file (used by `rename`, `unlink` etc.) */
> static int chroot_temp_open(struct shim_dentry* dent, mode_t type, int pal_options ,PAL_HANDLE* out_palhdl) {
> ```

There should be a space after the comma, and not before.

Also, please wrap this line to 100 characters (see [coding style](https://graphene.readthedocs.io/en/latest/devel/coding-style.html) for details).

(I recommend configuring an editor to display a line at the 100 column mark, so that you can notice when you're going over it).


<!-- Sent from Reviewable.io -->

2021-09-17 05:30 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: 4 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @svenkata9)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 204 at r2](https://reviewable.io/reviews/gramineproject/gramine/31#-MjiB3mH-2u0pT1ReEM-:-MjmDv9B6IRIP1X1apTA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/190ec5b377fcb2c2858514d179088e25e96f8462/LibOS/shim/src/fs/chroot/fs.c#L204)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

There should be a space after the comma, and not before.

Also, please wrap this line to 100 characters (see [coding style](https://graphene.readthedocs.io/en/latest/devel/coding-style.html) for details).

(I recommend configuring an editor to display a line at the 100 column mark, so that you can notice when you're going over it).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 808 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY5-aW0YTd75sc0rhF:-MjmDu3S5oVYMZKx1Yhw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L808)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't really use `pf_new` afterwards (after the line `if (!pf_new) {`). See my other comment.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 856 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8lgi2z219Z4V6gZ4:-MjmDnAY8mg23UE-vckb:b1ugump) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L856)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That I can understand, but the sentence itself is not proper English (or very confusing English).

Is `Handle` a verb here? `works properly` -- what should work properly? Or something already works properly? Please rephrase.
</blockquote></details>

I removed the comment and kept the things simple


<!-- Sent from Reviewable.io -->

2021-09-17 05:30 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: 4 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 859 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY8zGwAWhW3zHOCVMo:-MjmE1mTCdncnPbUAxk-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L859)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So in this line you're assigning `pf = pf_new`. Why? You don't use `pf` later in the code, so this new value of `pf` is unused and thus meaningless. Why can't you replace this whole IF statement with a more simple one:
```
    if (pf) {
        ret = pf_file_close(pf, handle);
        if (ret < 0)
            log_warning("pf_file_close failed during rename");
    }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 09:08 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @svenkata9)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 802 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mjn-hdN4K8X-SM0FzpV:-Mjn-hdN4K8X-SM0FzpW:b43yljt) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L802)):*
> ```C
>     if (!new_path)
>         return -PAL_ERROR_NOMEM;
> ```

One empty line can be removed. But not blocking, not too important.


<!-- Sent from Reviewable.io -->

2021-09-17 09:08 UTC, dimakuv commented
Jenkins, test this please

2021-09-17 10:29 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)



<!-- Sent from Reviewable.io -->

2021-09-20 01:30 UTC, mkow requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 11 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-Mk-kEkzDUWeW0CT3PF4:b-tlqhzk) (no related file):*
Please add proper tests to this PR.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
`Fix renaming issue with protected files` -> `Add support for renaming protected files` (it's not a bug, but a missing feature you're adding here)
___
*[Pal/include/pal/pal.h, line 300 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-algA7iRCpbtE2DFU:-Mk-algA7iRCpbtE2DFV:b34qrwn) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/include/pal/pal.h#L300)):*
> ```objc
>     PAL_OPTION_EFD_SEMAPHORE = 2, /*!< specific to `eventfd` syscall */
>     PAL_OPTION_NONBLOCK      = 4,
>     PAL_OPTION_RENAME        = 8, /*!<specific to `rename` syscall */
> ```

missing space after `<`
___
*[Pal/src/host/Linux-SGX/db_files.c, line 128 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-b_cL8T6bcdzC6O1D:-Mk-b_cL8T6bcdzC6O1E:b-akhud1) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L128)):*
> ```C
>          * so open with RDWR mode with necessary share permissions. */
>         if (pal_options & PAL_OPTION_RENAME) {
>             pal_share = PAL_SHARE_OWNER_R | PAL_SHARE_OWNER_W;
> ```

Why are you changing `pal_share` here? Isn't it ignored when we aren't creating a new file?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-Mk-cl0vD5bpRCf46fLy:b-e752m8) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
> ```
> flags |= O_RDWR;
> ```

This isn't a bitmask, but an enum written on `O_ACCMODE` bits, so you can't OR its values.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-iMbTBntM3Ov-7PBt:-Mk-iMbTBntM3Ov-7PBu:b-51uek2) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L827)):*
> ```C
>             free(new_normpath);
>             free(new_path);
>             return -PAL_ERROR_DENIED;
> ```

Please create a single return point from this function and free all the buffers there.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-Mk-l4K53wJ2a2ez0EHT:bvqtnm1) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
> ```C
>     memset(&pf->encrypted_part_plain.path, 0, sizeof(pf->encrypted_part_plain.path));
>     memcpy(pf->encrypted_part_plain.path, new_path, strlen(new_path) + 1);
> ```

What about `g_protected_files`? Isn't `get_protected_file()` returning wrong files from now on?
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1336 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fTWP9jklPa3p6qTz:-Mk-fTWP9jklPa3p6qU-:brmkydl) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1336)):*
> ```C
>         return PF_STATUS_UNINITIALIZED;
> 
>     if (!pf) {
> ```

Why would you check for this?
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1341 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fWkxD74OOaDcShtl:-Mk-fWkxD74OOaDcShtm:bzaocpk) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1341)):*
> ```C
>     }
> 
>     if (!new_path)
> ```

ditto, `NULL` is an invalid argument to this function and no callsite should ever allow it
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1344 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-f3ZL3ShI7FVKJ7XZ:-Mk-f3ZN68TFeLT4FnqD:bmphv62) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1344)):*
> ```C
>         return PF_STATUS_INVALID_PATH;
> 
>     if (strlen(new_path) > PATH_MAX_SIZE - 1) {
> ```

Why here, not in `ipf_rename_file()`?


<!-- Sent from Reviewable.io -->

2021-09-20 05:50 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: 3 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-Mk0dq2w0KeambjiUy_V:b9kcm8y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add proper tests to this PR.
</blockquote></details>

rename_unlink tests should already cover this PR also, but since there are issues with some of the tests when it comes to Protected FS, we have disabled it rather than having a separate test (which I added a while ago). Please see earlier discussions.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Fix renaming issue with protected files` -> `Add support for renaming protected files` (it's not a bug, but a missing feature you're adding here)
</blockquote></details>

Actually it is a bug.
___
*[Pal/include/pal/pal.h, line 300 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-algA7iRCpbtE2DFU:-Mk0kOZiDS21bD2nawXL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/include/pal/pal.h#L300)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space after `<`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 128 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-b_cL8T6bcdzC6O1D:-Mk0ePCD8i6PQpMacphn:b9xtyk6) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why are you changing `pal_share` here? Isn't it ignored when we aren't creating a new file?
</blockquote></details>

Without these share permissions, the write operation on this fail to succeed.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-Mk0f4vW2XYdlx09Lj0j:b-gng17b) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> flags |= O_RDWR;
> ```

This isn't a bitmask, but an enum written on `O_ACCMODE` bits, so you can't OR its values.
</blockquote></details>

Why is this then OR-ed in https://github.com/gramineproject/gramine/blob/487969c1dc1b0f27096f9d56312552e3ab6b754d/Pal/src/host/Linux-SGX/db_files.c#L42 ?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-iMbTBntM3Ov-7PBt:-Mk0fWGxALRYsImecPtz:b-8cuval) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L827)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please create a single return point from this function and free all the buffers there.
</blockquote></details>

We already discussed this in an earlier discussion. Please see that discussion. There is a mix of inner/outer scope here.  I would leave it like that and revisit later.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-Mk0flUIDpQvwid3-I68:blnjvsp) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `g_protected_files`? Isn't `get_protected_file()` returning wrong files from now on?
</blockquote></details>

It would not. It would register the file as part of rename, but this pf will have the older context.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1336 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fTWP9jklPa3p6qTz:-Mk0kQu56vu10Q_wQgfE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1336)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why would you check for this?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1341 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fWkxD74OOaDcShtl:-Mk0kIrL9Zjk5Rlihaa8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1341)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto, `NULL` is an invalid argument to this function and no callsite should ever allow it
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1344 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-f3ZL3ShI7FVKJ7XZ:-Mk0kHda-39kueXGQCJd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1344)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why here, not in `ipf_rename_file()`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-20 11:35 UTC, mkow requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-Mk1qfl96ZKyRWIncqFV:b-gs26hn) (no related file):*
> rename_unlink tests should already cover this PR

It doesn't, currently it's disabled for PF, as you said. So, currently there's no test verifying this feature.

> but since there are issues with some of the tests when it comes to Protected FS

AFAIU, Paweł disabled it just because his PR was based on master (not this PR), so the PF part couldn't work. And he expected you to enable this part of the test here.

> Please see earlier discussions.

I can't find any discussion which concludes that it's fine to merge this without tests.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Actually it is a bug.
</blockquote></details>

The only bug we had was that `DkStreamChangeName()` wasn't loudly failing when the app tried to rename a protected file. Before your PR renaming protected files was explicitly not supported and not considered in the security analysis.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-Mk1whww7djdpUhI49Ie:b-s8g4ly) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
+1 to the Dmitrii's request, it was pretty hard to analyze for me in the current form.

> There is a mix of inner/outer scope here.

What do you mean? All the return paths look the same to me, so they can be just deduplicated.

>  I would leave it like that and revisit later.

This really shouldn't take more than 10 minutes and will make this PR easier to review, so I don't see a reason to postpone it to a separate PR.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 128 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-b_cL8T6bcdzC6O1D:-Mk1u6haEer1t0LokGjx:b-z7g56x) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L128)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Without these share permissions, the write operation on this fail to succeed.
</blockquote></details>

How is this possible? The only path the `pal_share` value takes is to `ocall_open()`'s `mode` argument, then to `ms->ms_mode`, then to `sgx_ocall_open()` and then directly to the `open` syscall on the host. But `open` ignores the `mode` argument if we aren't creating a new file.
What am I missing?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-Mk1v2DV3VJdK2-Dwz26:b-7tw36c) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Why is this then OR-ed in https://github.com/gramineproject/gramine/blob/487969c1dc1b0f27096f9d56312552e3ab6b754d/Pal/src/host/Linux-SGX/db_files.c#L42 ?
</blockquote></details>

Because only `PAL_ACCESS_TO_LINUX_OPEN()` contains the access mode enum, so it's fine to OR them. Here you are ORing different access flags between each other, which doesn't make sense, because they are enum values (stored inside a larger bitmask), not bitflags.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 827 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-iMbTBntM3Ov-7PBt:-Mk1vyj3C3PHGRFc_XN7:bajg7d4) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L827)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

We already discussed this in an earlier discussion. Please see that discussion. There is a mix of inner/outer scope here.  I would leave it like that and revisit later.
</blockquote></details>

Ok, let's move the discussion to that thread.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-Mk1xWsBDo8o-f_tx3cA:b4erfki) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

It would not. It would register the file as part of rename, but this pf will have the older context.
</blockquote></details>

Sorry, but I don't understand your reply. You say "It would not", but at the same time you say "this pf will have the older context".
This seems like a bug in this PR.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1341 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fWkxD74OOaDcShtl:-Mk1xm3MCkV2GfC2gONw:b-y276oj) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1341)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, you just moved this check instead of removing it.


<!-- Sent from Reviewable.io -->

2021-09-20 15:03 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-Mk2hqOS0_oCc2AMIB4_:bnmhngr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> rename_unlink tests should already cover this PR

It doesn't, currently it's disabled for PF, as you said. So, currently there's no test verifying this feature.

> but since there are issues with some of the tests when it comes to Protected FS

AFAIU, Paweł disabled it just because his PR was based on master (not this PR), so the PF part couldn't work. And he expected you to enable this part of the test here.

> Please see earlier discussions.

I can't find any discussion which concludes that it's fine to merge this without tests.
</blockquote></details>

Sorry, I thought that is in reviewable, but it was a discussion that happed with Pawel on Slack. ("I think we can keep this whole test (rename_unlink) skipped for now, but add a TODO somewhere (SGX db_files.c) about what exactly doesn't work")

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The only bug we had was that `DkStreamChangeName()` wasn't loudly failing when the app tried to rename a protected file. Before your PR renaming protected files was explicitly not supported and not considered in the security analysis.
</blockquote></details>

Maybe the context has changed now and it is indeed a bug. Anyway, it is fixing the issue to make it work for a workload.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-Mk2gUfl8OdMFtA4tIoQ:b-hhfwl8) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to the Dmitrii's request, it was pretty hard to analyze for me in the current form.

> There is a mix of inner/outer scope here.

What do you mean? All the return paths look the same to me, so they can be just deduplicated.

>  I would leave it like that and revisit later.

This really shouldn't take more than 10 minutes and will make this PR easier to review, so I don't see a reason to postpone it to a separate PR.
</blockquote></details>

new_normpath is internal scope and new_path is external scope. We can take this up later.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 128 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-b_cL8T6bcdzC6O1D:-Mk2idjk21kv4qkMYrxL:b81qv8d) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How is this possible? The only path the `pal_share` value takes is to `ocall_open()`'s `mode` argument, then to `ms->ms_mode`, then to `sgx_ocall_open()` and then directly to the `open` syscall on the host. But `open` ignores the `mode` argument if we aren't creating a new file.
What am I missing?
</blockquote></details>

I have removed it now
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-Mk2ilIc3TulCqTXORUw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because only `PAL_ACCESS_TO_LINUX_OPEN()` contains the access mode enum, so it's fine to OR them. Here you are ORing different access flags between each other, which doesn't make sense, because they are enum values (stored inside a larger bitmask), not bitflags.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-Mk2hGvx7hJjdlS_AW-V:bj37ih5) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sorry, but I don't understand your reply. You say "It would not", but at the same time you say "this pf will have the older context".
This seems like a bug in this PR.
</blockquote></details>

get_protected_file will not return wrong files. Because the get_protected_path for the new name will be registered. When I said this pf context, I was referring to the one in this code - so it is fine.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1341 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fWkxD74OOaDcShtl:-Mk2h9dyEF0wwE9jKfud:b-ufv09p) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1341)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done, you just moved this check instead of removing it.
</blockquote></details>

I don't see a problem in having this check. Anyway, you preferred to remove it, and I have done that.


<!-- Sent from Reviewable.io -->

2021-09-21 23:28 UTC, mkow requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-Mk9eZxR7jPI6jmVk0NN:b6g0e1n) (no related file):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Sorry, I thought that is in reviewable, but it was a discussion that happed with Pawel on Slack. ("I think we can keep this whole test (rename_unlink) skipped for now, but add a TODO somewhere (SGX db_files.c) about what exactly doesn't work")
</blockquote></details>

So, your implementation doesn't pass this test? Could you fix it, so that it's actually tested? Right now we would have literally zero coverage for this feature in our tests.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Maybe the context has changed now and it is indeed a bug. Anyway, it is fixing the issue to make it work for a workload.
</blockquote></details>

This way you could classify all our features as bugfixes, as they are fixing some "issues with workloads" ;) Marking this change as a bugfix is misleading for whoever will read the commit log in the future.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-Mk9_sWO4XEWYwLjChxo:b-2dmyhq) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

new_normpath is internal scope and new_path is external scope. We can take this up later.
</blockquote></details>

Why is this a problem? You can just move `new_normpath` definition to the outer scope.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-Mk9_MMN7EsuwF9OjDwb:b-tohatn) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, now you're erasing all the other flags.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-Mk9emq39ACmR-fs-BWo:b-rosesl) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

get_protected_file will not return wrong files. Because the get_protected_path for the new name will be registered. When I said this pf context, I was referring to the one in this code - so it is fine.
</blockquote></details>

Yes, both paths are registered, but if you aren't updating the entries then you'll get the `protected_file` struct for the old file, no?
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1341 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-fWkxD74OOaDcShtl:-Mk9aWp3ANP3hPPvxw0r:b-88rm1g) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1341)):*
It's not a problem, but it makes little sense. You don't e.g. check if `new_path == (void*)-1`  or use something like `PROBE_MEM_READ()` on it to check if it actually points to some memory. It's the caller's responsibility to not pass garbage in the arguments and we can't start every function in our code with 10 checks for every possible caller's error.

> Anyway, you preferred to remove it, and I have done that.

Yup, now it's removed, so I'm resolving.


<!-- Sent from Reviewable.io -->

2021-09-22 02:11 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-MkAEBNiAl4T0CKyzC1Z:b-6i8q1o) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, your implementation doesn't pass this test? Could you fix it, so that it's actually tested? Right now we would have literally zero coverage for this feature in our tests.
</blockquote></details>

In fact, in the earlier PR, I did have a separate test added for this, but as per the review comments, I have removed since Pawel has added this rename_unlink tests. My implementation will pass two of the five tests that is part of rename_unlink, but since there are more issues, and as per the comments, I have let it remain in skipped state. We will revisit once this PR is merged and maybe selectively enable.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This way you could classify all our features as bugfixes, as they are fixing some "issues with workloads" ;) Marking this change as a bugfix is misleading for whoever will read the commit log in the future.
</blockquote></details>

Why this discussion, and you alone disagree? Where was this called out as a feature. It came as a bug from the customers, and we are addressing it? Let it remain as a bug fix for now, or if you wish, please reword it during the merge.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-MkAFD9a7EJqSaolQn3q:bx8c1nv) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this a problem? You can just move `new_normpath` definition to the outer scope.
</blockquote></details>

On one hand, we say move everything together, and on the other hand, the other part of the code still has such cases. see file_open or other part of the code. the new_normpath is very specific to pf and doesn't make sense defining it outside the scope for pf
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-MkAF-EJ2LAH--pY5tzW:b-ewymal) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done, now you're erasing all the other flags.
</blockquote></details>

This is a specific rename case which is custom. So, the flags are updated to RDWR - why not overwrite them? What else do you suggest? The file has already been checked for presence and is a pf.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-MkAFwwmD1vETsKMpRDK:b208fnu) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, both paths are registered, but if you aren't updating the entries then you'll get the `protected_file` struct for the old file, no?
</blockquote></details>

There is a bigger issue in g_protected_files maintenance and that is what we need to address. As mentioned in the earlier comments, we will take it up earlier post this rename case.


<!-- Sent from Reviewable.io -->

2021-09-22 08:47 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-MkBem_vAtYoGr4zP3eu:b-pijw9k) (no related file):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

In fact, in the earlier PR, I did have a separate test added for this, but as per the review comments, I have removed since Pawel has added this rename_unlink tests. My implementation will pass two of the five tests that is part of rename_unlink, but since there are more issues, and as per the comments, I have let it remain in skipped state. We will revisit once this PR is merged and maybe selectively enable.
</blockquote></details>

Quick content for Michal: we recently revealed a whole bunch of problems with Protected Files. This PR tries to fix one particular issue (missing renaming support for PFs) in one particular use case (from some customer).

In reality, a *proper fix* would be to re-write our PF implementation from scratch. So at this point, we have two possibilities:
1. Merge this PR more or less intact, because it covers that particular use case. And later have a comprehensive refactoring of the PF implementation.
2. Refactor PF implementation from the beginning, which will also incorporate modifications from this PR.

I understand that you want to do 2, but we currently don't have the bandwidth or anyone assigned to do this big refactoring. So we either do 1, or:
3. Keep everything as-is currently and not merge this PR.

In my opinion, we should do 1, because it at least fixes one bug for one customer and moves us closer to the "proper" renaming support.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Why this discussion, and you alone disagree? Where was this called out as a feature. It came as a bug from the customers, and we are addressing it? Let it remain as a bug fix for now, or if you wish, please reword it during the merge.
</blockquote></details>

We will reword it during the merge. I also prefer Michal's text.


<!-- Sent from Reviewable.io -->

2021-09-22 11:33 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-kEkzDUWeW0CT3PF3:-MkC9yMRBADv5xBdV5Al:b-iy61ci) (no related file):*
> I did have a separate test added for this, but as per the review comments, I have removed since Pawel has added this rename_unlink tests.

Yes, I've seen it. I believe that Paweł's intention was that you can drop this test because you'll be able to enable his. We need to test this change somehow, if it's completely lacking coverage then tools like UBSan or ASan won't be able to check it.

> We will revisit once this PR is merged and maybe selectively enable.

Why can't you selectively enable them now?

> we recently revealed a whole bunch of problems with Protected Files

Yup, I'm aware of this and have seen these discussions.

> In reality, a proper fix would be to re-write our PF implementation from scratch.

I don't agree with this, look e.g. at the problem with `get_protected_file()` - it looks like something which was introduced in this PR, that `g_protected_files` entries aren't swapped on rename and have now dangling links to other files (if I understand the change correctly). I know that we have refcounting problems in PF, but that's not a good justification to introduce even new kinds of bugs to it. And this one looks like something which was introduced in this PR and can be fixed without rewriting PF.

@dimakuv: Anyways, this discussion thread is not really about fixing bugs in this PR (for this see other discussions below), but about having literally 0 tests for it.

---
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-_AUy2WnFKGxtAiaT):*
> Why this discussion

From my review? I'm sorry, but I really don't understand your resistance here, it's just a trivial commit message change for uniformity with the rest of our development. What's the problem with this?

> and you alone disagree?

That's quite normal in reviews, that different people notice different problems. The fact that only I pointed it out doesn't mean that everyone else who did review "votes" for the current version, they may have just missed it.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-MkCDsWV1uZXZJoVGkM8:bs7ma8) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
`file_open` is quite ugly and wasn't refactored in years, it's not a good example. We should write all new code better than this.

> the new_normpath is very specific to pf and doesn't make sense defining it outside the scope for pf

Unfortunately we're using C and this is a very common thing you have to do (defining variables as "function-global"). We don't have RAII here, so if you want to have manageable cleanup you unfortunately need to move the variables to the outer scope, and that's what we do in all new code where you need some cleanup.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 130 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-cl0u02UZgGVy-zTv:-MkCD5kW6KnZbUiKj_uO:b-83e4w4) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/db_files.c#L130)):*
But it's the caller who passed `PAL_OPTION_RENAME` and _also_ chose the flags. And now you're just silently erasing them.

> What else do you suggest?

The same as I suggested from the beginning of this thread, that you just set this enum (which is encoded in a bitfield) to `O_RDWR`. There's no need to erase other values.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-MkCFAVW5cPA_NXMsy9J:bi5uxn0) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

There is a bigger issue in g_protected_files maintenance and that is what we need to address. As mentioned in the earlier comments, we will take it up earlier post this rename case.
</blockquote></details>

Wait, isn't this a problem that you introduced in this very PR, not a PF bug? You implemented swapping of files, but you don't swap their entries in `g_protected_files`, leaving dangling references. Previously there was no way to move protected files.


<!-- Sent from Reviewable.io -->

2021-09-22 12:58 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/31)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 815 at r1](https://reviewable.io/reviews/gramineproject/gramine/31#-MjY6hWw9oAAyD4JMQ3o:-MkCYE_Q6Df_AVegafQd:bvjw17s) ([raw file](https://github.com/gramineproject/gramine/blob/c165e286292feb47ac27b4536e4df2f56aa8689b/Pal/src/host/Linux-SGX/db_files.c#L815)):*
> file_open is quite ugly and wasn't refactored in years, it's not a good example. We should write all new code better than this.

+1 to this. I started refactoring this madness, but completed only 50% of the task. The code we have for files/streams/pipes in Linux-SGX PAL is still a nightmare, and we need to continue making it better.
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 378 at r3](https://reviewable.io/reviews/gramineproject/gramine/31#-Mk-l4K53wJ2a2ez0EHS:-MkCYvwH6PqDVZ0NDRAf:b-d9a8bt) ([raw file](https://github.com/gramineproject/gramine/blob/adb75ddd21137000a3dd7d43ee5561c8f6f3ce1f/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L378)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, isn't this a problem that you introduced in this very PR, not a PF bug? You implemented swapping of files, but you don't swap their entries in `g_protected_files`, leaving dangling references. Previously there was no way to move protected files.
</blockquote></details>

Damn, I just realized that we have the same problem with `g_trusted_file_list`. Please note that this list stores both allowed and trusted files. And if trusted files cannot be renamed by their nature (they are immutable, and everything regarding them is immutable), **allowed files can be renamed**. And if a file was declared as `sgx.allowed_files = "file:foo"`, then if this file is renamed and then accessed, it won't appear in the `g_trusted_file_list`, and Gramine will refuse to open it. (One can circumvent this with specifying an **allowed dir**, then all files renamed in the same dir will work fine. But this is just a workaround.)

Ok, this PR (alongside a couple other issues raised by Borys and Pawel) revealed that our current implementation of allowed/trusted/protected files is just broken in so many ways. We need proper refactoring of this whole subsystem, as a series of 5-10 PRs that fix this mess piece by piece.

Sorry, @svenkata9, but we'll need to start complete refactoring. Too many bugs uncovered. It's just simpler to burn the current code and rewrite it...


<!-- Sent from Reviewable.io -->

2022-02-07 11:29 UTC, mkow commented
I'm closing this PR, as this solution to the problem won't be merged (because it doesn't really work and is too hacky). We're starting a big redesign of protected files, which should fix issues like this one at the core (see https://github.com/gramineproject/gramine/issues/371).

2022-02-07 11:29 UTC, closed without merging