[WIP] ASan
gramineproject/gramine pull request #32
Opened 2021-09-13 14:30 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-09-13 14:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: 0 of 24 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-MjUbEi837GJr4g-vJi6:-MjUbEi837GJr4g-vJi7:bjo91hp) (no related file):*
I did not review this PR (since it's WIP), but please post bug fixes as a separate PR (once you're done).

---


<!-- Sent from Reviewable.io -->

2021-09-21 02:40 UTC, mkow requested changes
> Reviewed 10 of 24 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2XWfy7-zWjifY38Gc:-Mk2XWfy7-zWjifY38Gd:b-a9d47k) (no related file):*
> Tracking issue: #19 (but I don't consider this done yet, see "What's next")

FYI: I tweaked the checklist there to reflect the actual implementation order.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2eLPwCfx9DIyjW3Gi:-Mk2eLPwCfx9DIyjW3Gj:brle5qm) (no related file):*
> My best idea is to fork and exec add2line. This is messy, but I tried it out and it works: we can report source file, line, and function. We're doing it just before aborting the whole process anyway.

Quite hacky, but fine with me, it's just test code. And if in the future it turns out that we really need the full traceback then we can implement the GDB version.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2nKjy5RVe0KN__G99:-Mk2nKjz7sSBijTndc7O:b-bmk689) (no related file):*
> However, this also requires cleaning (unpoisoning) all stack memory that we recycle or unmap. Two problems I see with that:
>
> * There is the `shim_entry_api` for running LibOS functions from application (used mostly for glibc integration). These functions run on the user stack. I guess we should switch stacks for them as well.
> * I'm not sure which stack(s) do we use when handling signals?

This is something for @boryspoplawski to answer.

---
___
*[meson.build, line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2uXOoCVgZmJjP1Oj9:-Mk2uXOqC-YnkQg-8JmH:bsw1sfr) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L110)):*
> ```Meson
> 
> if asan
>     # TODO: When we start compiling C++ code with Meson, check for C++ compiler as well
> ```

It seems that we'll merge that change before this one, so I'm blocking to not forget about this while rebasing.
___
*[meson.build, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2uoVW-BMv-C-Ukv6d:-Mk2uoVW-BMv-C-Ukv6e:b-cb9rtu) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L120)):*
> ```Meson
>         '-mllvm', '-asan-use-after-return=0',
>         '-mllvm', '-asan-stack=0',
>         '-mllvm', '-asan-globals=0',
> ```

What about globals? Is it also hard to support? You didn't mention them in the PR description.
___
*[.ci/linux-sgx-sanitizers.jenkinsfile, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2Ycf-2wzYl2EMT1s3:-Mk2Ycf-2wzYl2EMT1s4:b-qb9j1y) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/.ci/linux-sgx-sanitizers.jenkinsfile#L16)):*
> ```
>         load '.ci/lib/config-debug.jenkinsfile'
>         load '.ci/lib/config-ubsan.jenkinsfile'
>         load '.ci/lib/config-asan.jenkinsfile'
> ```

What about `linux-direct-sanitizers.jenkinsfile`? Doesn't it need a similar change?
___
*[common/include/api.h, line 233 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2vVFM6OpO-4_ZXdl6:-Mk2vVFM6OpO-4_ZXdl7:b-y0c9jd) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/api.h#L233)):*
> ```objc
> void* __memset_chk(void* dest, int ch, size_t count, size_t dest_count);
> 
> /* Original version of functions that ASan overrides */
> ```

`version` -> `versions`
___
*[common/include/asan.h, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4YRdWDDrrRHqHsOmr:-Mk4YRdXBWeSxFpGysej:b-6mz1my) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L9)):*
> ```objc
>  * This file defines functions for address sanitization (ASan).
>  *
>  * Normally, code compiled with ASAN is linked against a special library (libasan), but that library
> ```

`ASAN` -> `ASan`
___
*[common/src/asan.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4gj9VDr41c1QJt7rh:-Mk4gj9WBcug16BhdgPs:b1ik43y) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L1)):*
> ```C
> 
> ```

missing license and copyright info
___
*[common/src/asan.c, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4v3V_AgVSTGz5oHFD:-Mk4v3Va-Fj624myRgvj:b-8jd38m) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L10)):*
> ```C
> #endif
> 
> #define RETURN_ADDR __builtin_extract_return_addr(__builtin_return_address(0))
> ```

This should probably be parenthesized? Also, I'd prefer to add empty parenthesis to the macro so that it doesn't look like a constant.
___
*[common/src/asan.c, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4xxl_2OZN0wMom2x8:-Mk4xxl_2OZN0wMom2x9:bzdr85i) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L64)):*
> ```C
>         if (asan_check(bad_addr))
>             break;
> ```

Just for sanity, could you assert `asan_check(bad_addr)` here? It's on the slow path, so it won't matter performance-wise and we unfortunately don't have for-else in C.
___
*[common/src/asan.c, line 125 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk53zPsEiZaZufeYgyl:-Mk53zPsEiZaZufeYgym:b-kkwq8u) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L125)):*
> ```C
> __attribute_no_sanitize_address
> static void asan_report(void* ip_addr, uintptr_t addr, size_t size, bool is_load) {
> ```

no need for this empty line
___
*[common/src/asan.c, line 131 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk53OdM1-5NVj6LKpY_:-Mk53OdM1-5NVj6LKpYa:b-l3mf39) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L131)):*
> ```C
> 
>     log_error("asan: %s while trying to %s %lu bytes at 0x%lx", bug_type,
>               is_load ? "load" : "store", size, addr);
> ```

Could we replace "bytes" with "%s" and use singular version for single-byte stores? Not blocking, but the reports look really nice and this was the only thing which didn't look so nicely :)
___
*[common/src/asan.c, line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk54D6k3fBPp49oZl16:-Mk54D6l8dnhVrkA2Z-p:bqgn1ti) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L132)):*
> from beginning

This was a bit confusing to me, I had to look at the code to understand beginning of what this is. Maybe something like "beginning of access" or "beginning of memory access" would be better?
___
*[common/src/asan.c, line 168 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk56gPH9Zp_mH2ed0f1:-Mk56gPH9Zp_mH2ed0f2:bfwdqdc) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L168)):*
> ```C
> }
> 
> #define ASAN_LOAD(addr, size)          \
> ```

please align this backslash
___
*[common/src/asan.c, line 171 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk578IUA-wIx1GZcDVR:-Mk578IUA-wIx1GZcDVS:b-ohn3xr) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L171)):*
> ```C
>     do {                                                \
>         if (asan_check_region(addr, size)) {            \
>             asan_report(RETURN_ADDR, addr, size, t [...]

2021-09-21 13:25 UTC, dimakuv requested changes
> Reviewed 10 of 24 files at r1, 14 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7WwZoBOqaBzbD4Vz_:-Mk7WwZoBOqaBzbD4Vza:b-e89p3v) (no related file):*
One of the most impressive PRs I've seen!

---
___
*[meson.build, line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7B1us4Cys8Qca5fb5:-Mk7B1us4Cys8Qca5fb6:b-w1bb3m) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L112)):*
> ```Meson
>     # TODO: When we start compiling C++ code with Meson, check for C++ compiler as well
>     if meson.get_compiler('c').get_id() != 'clang'
>         error('ASan is currently supported only for Clang (CC=clang)')
> ```

What is the exact reason we only support ASan on Clang?
___
*[common/include/asan.h, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7GRFX0tWYe_HRf9Xx:-Mk7GRFY-6HkyO7H58EE:b-t3ylnc) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L95)):*
> ```objc
> #define ASAN_SHADOW_START 0x7fff8000
> #define ASAN_SHADOW_SHIFT 3
> #define ASAN_SHADOW_LENGTH (1ULL << 44)
> ```

How does this work? We start our shadow memory at 2GB (`0x7fff8000`) and this shadow extends over 16TBs (1ULL << 44)??

I guess the idea is that it works for the first 2GB of code/data (because executable is typically placed there) and also for libs/stack (because they are typically allocated from bits 47-48)? But how can this work for e.g. Linux-SGX?
___
*[common/include/asan.h, line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7H9BUCM2vpAdcxI_C:-Mk7H9BVEA992N5ccE7G:b-l28hm3) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L123)):*
> ```objc
>  * Load/store callbacks:
>  *
>  * - `load` / `store`: check if an memory under given address is accessible; if not, report the
> ```

`an memory` -> `memory`
___
*[common/src/asan.c, line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7KC7824m2aXfnfbrh:-Mk7KC7824m2aXfnfbri:bvjd0yu) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L40)):*
> ```C
>     _real_memset(shadow_ptr, 0, shadow_size);
>     if (right_part_size)
>         *(shadow_ptr + shadow_size) = right_part_size;
> ```

What is this magic with the right part of the memory-region-to-unpoison?

UPDATE: Looks like this shows us how many bytes are allocated in this 8-byte "end of object" (for non-8-16-24-32-...-byte-sized objects).
___
*[common/src/asan.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7ML248f3aVYwoU0R5:-Mk7ML248f3aVYwoU0R6:bgxuhvr) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L68)):*
> ```C
>     /* If this is a partial right redzone, check the next byte */
>     if (*shadow_ptr < 0x80)
>         shadow_ptr++;
> ```

I don't get it. Why is it guaranteed that after an 8-byte partially allocated object, there will be a redzone (== shadow memory contains the description of what kind of redzone)?

Is this because you added that `padding[8]` to any allocated memory object (`memobj`), so there is always at least 8 bytes in-between allocations? And these 8 bytes are filled with `ASAN_POISON_HEAP_LEFT_REDZONE` at the host-allocation PAL level?
___
*[common/src/asan.c, line 267 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7Ra2k2sK7O8AA8s-5:-Mk7Ra2lD-69IbUTvuE_:bn5nsv7) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L267)):*
> ```C
> }
> 
> int memcmp(const void* lhs, const void* rhs, size_t count) {
> ```

What's the deal with `memcmp()`? Why is it not `__asan_memcmp`?
___
*[Pal/src/slab.c, line 81 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7UCre53mtZyGK_1xQ:-Mk7UCre53mtZyGK_1xR:bc8ljkg) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/slab.c#L81)):*
> ```C
>     }
> #ifdef ASAN
>     asan_poison_region((uintptr_t)addr, ALLOC_ALIGN_UP(size), ASAN_POISON_HEAP_LEFT_REDZONE);
> ```

This is PAL-internal memory allocation. It is different from the app+LibOS memory allocation. I wonder if we could have different `ASAN_POISON_...` macro for it? Maybe not in this PR, but in the future?
___
*[Pal/src/slab.c, line 106 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7Uh4e3ts1wwufWfUw:-Mk7Uh4f82E1OOurP3Ss:b-3a51nr) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/slab.c#L106)):*
> ```C
>         }
>         /* not a last object from low/high addresses, can't do anything about this case */
>         /* ASAN: keep the memory poisoned, because we're not returning it to the system */
> ```

I don't understand this comment. (This case is the counterpart to the above malloc case: this is memory allocated previously from the `g_mem_pool`. Why is memory in `g_mem_pool` always poisoned?)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-Mk7W6P-3DHy-l_9cmDQ:bm8tfv5) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
> ```C
>     int flags = MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE | MAP_FIXED_NOREPLACE;
>     void* addr = (void*)DO_SYSCALL(mmap, (void*)ASAN_SHADOW_START, ASAN_SHADOW_LENGTH, prot, flags,
>                                    /*fd=*/-1, /*offset=*/0);
> ```

This carves out a memory region (enclave or untrusted) starting from 2GB and till 16TB. This means that e.g. enclaves with `sgx.non_pie = true` and `sgx.enclave_size = 4G` will fail to start -- because they overlap with the shadow memory region of ASan.

Are there any other constants we could use? For example, starting shadow memory from e.g. 64GB or 1TB would be no problem at all (most enclaves I've seen have enclave size of max 32GB).

Otherwise, we have to put some explanations in the docs, that some combinations of SGX enclaves and ASan cannot work together.


<!-- Sent from Reviewable.io -->

2021-09-21 19:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7WwZoBOqaBzbD4Vz_:-Mk8jq9KDLHehq3rqrB9:bt2v3q6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One of the most impressive PRs I've seen!
</blockquote></details>

+1, great work!

---
___
*[common/include/asan.h, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7GRFX0tWYe_HRf9Xx:-Mk8kWch-ZOwvum3Kc4W:bxjfixe) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does this work? We start our shadow memory at 2GB (`0x7fff8000`) and this shadow extends over 16TBs (1ULL << 44)??

I guess the idea is that it works for the first 2GB of code/data (because executable is typically placed there) and also for libs/stack (because they are typically allocated from bits 47-48)? But how can this work for e.g. Linux-SGX?
</blockquote></details>

This relies on Linux' lazy allocation of physical memory. Note that on SGX we allocate this memory _outside_ the enclave and then just use it from inside - this is only a debugging feature, so this is perfectly fine.
___
*[common/src/asan.c, line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7KC7824m2aXfnfbrh:-Mk8lCYV54aMGV5s9OuL:b-lk96bj) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this magic with the right part of the memory-region-to-unpoison?

UPDATE: Looks like this shows us how many bytes are allocated in this 8-byte "end of object" (for non-8-16-24-32-...-byte-sized objects).
</blockquote></details>

Yup. There's a nice explanation in `asan.h` for this - "A low value (01..07) means only the first N bytes are accessible.".
___
*[common/src/asan.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7ML248f3aVYwoU0R5:-Mk8mOTs9ciA2EfzOwCC:b-21f943) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't get it. Why is it guaranteed that after an 8-byte partially allocated object, there will be a redzone (== shadow memory contains the description of what kind of redzone)?

Is this because you added that `padding[8]` to any allocated memory object (`memobj`), so there is always at least 8 bytes in-between allocations? And these 8 bytes are filled with `ASAN_POISON_HEAP_LEFT_REDZONE` at the host-allocation PAL level?
</blockquote></details>

I think this is just a heuristic - we hit an invalid access for a byte we don't have info about, so we just try to take it from the next one, hoping that it's the same. But let's wait for Paweł's answer.


<!-- Sent from Reviewable.io -->

2021-09-24 11:55 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: 22 of 29 files reviewed, 34 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2eLPwCfx9DIyjW3Gi:-MkMJv0G4gL27syfqkbC:b-hir5n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> My best idea is to fork and exec add2line. This is messy, but I tried it out and it works: we can report source file, line, and function. We're doing it just before aborting the whole process anyway.

Quite hacky, but fine with me, it's just test code. And if in the future it turns out that we really need the full traceback then we can implement the GDB version.
</blockquote></details>

Let's do it after this PR then; I have some proof-of-concept lying around but there might be some discussions about how to make it less messy.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7WwZoBOqaBzbD4Vz_:-MkMKGGu9cBjoaUjlMBa:b-ucfknh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, great work!
</blockquote></details>

Thanks!

---
___
*[meson.build, line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7B1us4Cys8Qca5fb5:-MkMKJn86YfcHm6AkC0c:btr7ype) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the exact reason we only support ASan on Clang?
</blockquote></details>

This is from memory, but:

* Obviously the `-mllvm ...` flags are Clang-specific
* Not sure if it actually supports stack sanitization, etc.
* ASan is only on the newer GCC (the one in Ubuntu 20.04). That means at least making a more specific `#ifdef` for the `no_sanitize("undefined")` attribute
* I think it uses only the `__asan_*` etc. callbacks; doesn't generate inline code (so it should be slower, but actually easier to support)

I think it wouldn't be too hard to support GCC ASan, but without a Jenkins build it's likely to break (same as our Clang support broke multiple times before we added a Jenkins build). Since it would require at least some branches (ifdefs, conditions in Meson, etc), I don't think it's worth it, because GCC sanitizers are usually weaker anyway.
___
*[meson.build, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2uoVW-BMv-C-Ukv6d:-MkMMuvB0qMjzkGW8ZD9:bzelb79) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about globals? Is it also hard to support? You didn't mention them in the PR description.
</blockquote></details>

From what I understand from `libasan` code, tracking globals is (1) being able to track origin of memory (which our integration doesn't do), and (2) setting up a red zone around globals (which might be useful to catch buffer overflows).

I think the main obstacle is supporting `.init` sections, because that's where the globals are registered (we would have to make sure the `.init` code appears in our binaries and is being run by ELF loading code). I can try after this PR.
___
*[.ci/linux-sgx-sanitizers.jenkinsfile, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2Ycf-2wzYl2EMT1s3:-MkMOUWM3Wq2p0KdNBSo:b2vckn8) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/.ci/linux-sgx-sanitizers.jenkinsfile#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `linux-direct-sanitizers.jenkinsfile`? Doesn't it need a similar change?
</blockquote></details>

Good catch! Added, I hope this doesn't break Jenkins.
___
*[common/include/api.h, line 233 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2vVFM6OpO-4_ZXdl6:-MkMOb2g2FMCg_ZtqxrC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/api.h#L233)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`version` -> `versions`
</blockquote></details>

Done.
___
*[common/include/asan.h, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4YRdWDDrrRHqHsOmr:-MkMOe9b1c1HUVQTz7CR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`ASAN` -> `ASan`
</blockquote></details>

Done.
___
*[common/include/asan.h, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7GRFX0tWYe_HRf9Xx:-MkMOf2U9w6jVPs9JOp-:b-fzx3z) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L95)):*
>How does this work? We start our shadow memory at 2GB (`0x7fff8000`) and this shadow extends over 16TBs (1ULL << 44)??

Yes.

>I guess the idea is that it works for the first 2GB of code/data (because executable is typically placed there) and also for libs/stack (because they are typically allocated from bits 47-48)? 

Yeah, looks like LLVM is betting on the fact that this area (2GB +16TB) is usually unmapped... I don't know how reliable that assumption is. 

>But how can this work for e.g. Linux-SGX?

Good point, it's going to break for larger enclaves. Let's continue in the thread for `sgx_main.c`.
___
*[common/include/asan.h, line 123 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7H9BUCM2vpAdcxI_C:-MkMTmCtCGhwQlrC_6qx:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/include/asan.h#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`an memory` -> `memory`
</blockquote></details>

Fixed.
___
*[common/src/asan.c, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4gj9VDr41c1QJt7rh:-MkMTs6T5HKYk-czjqaF:bqmjwcz) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing license and copyright info
</blockquote></details>

Added.
___
*[common/src/asan.c, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4v3V_AgVSTGz5oHFD:-MkMU3JX6yUxgOtB8qeP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should probably be parenthesized? Also, I'd prefer to add empty parenthesis to the macro so that it doesn't look like a constant.
</blockquote></details>

Done.
___
*[common/src/asan.c, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk4xxl_2OZN0wMom2x8:-MkMUT918pOw0opGjRmJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/common/src/asan.c#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just for sanity, could you assert `asan_check(bad_addr)` here? It's on the slow path, so it won't matter performance-wise and we unfortunately don't have for-else in C.
</blockquote></details>

Done.
___
*[common/src/asan.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7ML248f3aVYwoU0R5:-MkMU_-rBpcWaC7dbmqI: [...]

2021-09-24 13:08 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: 20 of 29 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-MkMughmAJy3MXOywVbY:b-4whrl5) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
> ```objc
>  *
>  * The address has to be provided to the compiler using `-mllvm -asan-mapping-offset=0x...`.
>  * BEWARE: You cannot use a power of 2, because LLVM special-cases such starting addresses and emits
> ```

Ugly, isn't it? :)

Initially, I wanted this to be configurable (compile with `-DASAN_SHADOW_START=0x...`), but because of this caveat, I think it's better to just hardcode the address here.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-MkMubDIAdNbXInVDyDf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, I tried out `sgx.enclave_size = "4G"` and it's even worse: it silently maps the enclave *over* the first 2GB of the shadow map.

Shouldn't we fail setting up the enclave if there is something already mapped there? I'm looking at `add_pages_to_enclave`, and could use `MAP_FIXED_NOREPLACE` instead of `MAP_FIXED`. Although there is also the "older drivers" section which maps pages through `ioctl` to the driver, not sure how it behaves...

I will try using a starting address of 1TB.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-25 00:36 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[meson.build, line 112 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7B1us4Cys8Qca5fb5:-MkPGKUQ0e-7wG5iJDyB:bh61y7i) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L112)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is from memory, but:

* Obviously the `-mllvm ...` flags are Clang-specific
* Not sure if it actually supports stack sanitization, etc.
* ASan is only on the newer GCC (the one in Ubuntu 20.04). That means at least making a more specific `#ifdef` for the `no_sanitize("undefined")` attribute
* I think it uses only the `__asan_*` etc. callbacks; doesn't generate inline code (so it should be slower, but actually easier to support)

I think it wouldn't be too hard to support GCC ASan, but without a Jenkins build it's likely to break (same as our Clang support broke multiple times before we added a Jenkins build). Since it would require at least some branches (ifdefs, conditions in Meson, etc), I don't think it's worth it, because GCC sanitizers are usually weaker anyway.
</blockquote></details>

+1, doesn't seem to be worth the effort
___
*[meson.build, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2uoVW-BMv-C-Ukv6d:-MkPGYkVBb4faQdxjIIa:boznrb2) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L120)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

From what I understand from `libasan` code, tracking globals is (1) being able to track origin of memory (which our integration doesn't do), and (2) setting up a red zone around globals (which might be useful to catch buffer overflows).

I think the main obstacle is supporting `.init` sections, because that's where the globals are registered (we would have to make sure the `.init` code appears in our binaries and is being run by ELF loading code). I can try after this PR.


</blockquote></details>

I see, thanks! It's definitely less important than adding support for stack buffers, but still nice to have.
___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-MkPJUtv12_uAm5FDTsz:b-hzftwd) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Ugly, isn't it? :)

Initially, I wanted this to be configurable (compile with `-DASAN_SHADOW_START=0x...`), but because of this caveat, I think it's better to just hardcode the address here.
</blockquote></details>

Hmm, why OR doesn't work in our case?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-MkPMhce7St87C8E2FzS:b-oxzbbj) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
> Shouldn't we fail setting up the enclave if there is something already mapped there?

Uh, that sounds really bad. I guess the reason to not use it was that we dropped Ubuntu 16.04 only recently, and AFAIR it was too old for it. Would you have a moment to submit a PR fixing this? You already have a test which for it :)


<!-- Sent from Reviewable.io -->

2021-09-25 07:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-MkQrXc0EMZSk8TvFEsU:b-itvy9) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, why OR doesn't work in our case?
</blockquote></details>

The formula is `shadow_start | (addr >> shift)`, so `shadow_start` must be high enough so that `(addr >> 3)` doesn't ever have that bit set. Otherwise the result will not only be different than with addition, but also it will conflate unrelated locations.

(I actually saw this break with `shadow_start == 1 TB`: ASan didn't always trigger for a buffer overflow.)

But something like `shadow_start == (1 << 44)` would work... I'll try it. LLVM code says they want to use OR whenever possible because it's faster.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-MkQuJKFB42FobpHPpQD:b-s5y23y) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Shouldn't we fail setting up the enclave if there is something already mapped there?

Uh, that sounds really bad. I guess the reason to not use it was that we dropped Ubuntu 16.04 only recently, and AFAIR it was too old for it. Would you have a moment to submit a PR fixing this? You already have a test which for it :)
</blockquote></details>

OK, I'll submit a PR.


<!-- Sent from Reviewable.io -->

2021-09-27 08:31 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-MkaNCTs7RHf1lTkA26Y:-MkaNCTs7RHf1lTkA26Z:b-v8wmqt) (no related file):*
@pwmarcz Could you please check why the Docs Jenkins failed?

---
___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-MkaKhsH-UNOuSOE8jcT:b2nu8qo) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The formula is `shadow_start | (addr >> shift)`, so `shadow_start` must be high enough so that `(addr >> 3)` doesn't ever have that bit set. Otherwise the result will not only be different than with addition, but also it will conflate unrelated locations.

(I actually saw this break with `shadow_start == 1 TB`: ASan didn't always trigger for a buffer overflow.)

But something like `shadow_start == (1 << 44)` would work... I'll try it. LLVM code says they want to use OR whenever possible because it's faster.
</blockquote></details>

We don't really care about performance of ASan, right? I am perfectly fine with the current 1.5TB shadow start.
___
*[Pal/src/slab.c, line 130 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk5BNWn-knCwYWaJVqi:-MkaMerb7gdTJVjSxseU:b-8k76km) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/slab.c#L130)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

BTW, we can just remove this `STATIC_SLAB` macro completely. Gramine doesn't work anyway with `STATIC_SLAB = 0`.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-MkaMuMj7BSPcv_HPjYU:b-11mr11) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll submit a PR.
</blockquote></details>

@mkow is exactly correct, we couldn't use `MAP_FIXED_NOREPLACE` on Ubuntu 16.04. @pwmarcz Please submit a PR.


<!-- Sent from Reviewable.io -->

2021-09-27 10:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: 16 of 29 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/32#-MkaNCTs7RHf1lTkA26Y:-MkakFKk1zpTIaV8lXPP:b-c2hh6l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz Could you please check why the Docs Jenkins failed?
</blockquote></details>

It's a problem with Python module, already resolved on master. I'll rebase the branch, we had significant changes since.

---
___
*[meson.build, line 110 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk2uXOoCVgZmJjP1Oj9:-MkarWi5D0VnQnYHUzIo:b-587tlr) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/meson.build#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It seems that we'll merge that change before this one, so I'm blocking to not forget about this while rebasing.
</blockquote></details>

Rebased and updated.
___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-Mkai-Fw4sbZQjjO4nV2:b-ru3h24) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't really care about performance of ASan, right? I am perfectly fine with the current 1.5TB shadow start.
</blockquote></details>

It would be nice to have the tests run faster... but I just checked that, and using a power of 2 (`1 << 44`) makes no significant difference for LibOS `make regression` CPU time. (Either way, the "user" time is about 2x the non-ASan case).

So I think keeping 1.5 TB is better. Since LLVM happily did the wrong thing for a _low_ power of 2, I think it's better to stay clear of that case.

I updated the comment to explain the situation better.
___
*[Pal/src/slab.c, line 130 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk5BNWn-knCwYWaJVqi:-MkaePrc52Ox9yiJRGdl:b-hvdkx6) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/slab.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, we can just remove this `STATIC_SLAB` macro completely. Gramine doesn't work anyway with `STATIC_SLAB = 0`.
</blockquote></details>

Good to know. Submitted in #95, and I can rebase either branch once the other one is merged.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-MkagWck3pNIiQO0ODly:bcyqy7) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow is exactly correct, we couldn't use `MAP_FIXED_NOREPLACE` on Ubuntu 16.04. @pwmarcz Please submit a PR.
</blockquote></details>

Actually `MAP_FIXED_NOREPLACE` is not available on Ubuntu 18.04 either... It uses glibc 2.27, which doesn't define it, and Linux 4.15, which doesn't have it yet.

I'll drop it for now, and also remove it from the ASan code.


<!-- Sent from Reviewable.io -->

2021-09-27 11:14 UTC, dimakuv approved these changes
> Reviewed 13 of 13 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-09-28 14:48 UTC, mkow submitted a review, later dismissed
> Reviewed 13 of 13 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/asan.h, line 91 at r5](https://reviewable.io/reviews/gramineproject/gramine/32#-MkMughmAJy3MXOywVbX:-Mkgr0-j6cjQcX13vYTp:b-aiwuip) ([raw file](https://github.com/gramineproject/gramine/blob/fa941375bfa3148e1066b1ea8800ac080368c755/common/include/asan.h#L91)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It would be nice to have the tests run faster... but I just checked that, and using a power of 2 (`1 << 44`) makes no significant difference for LibOS `make regression` CPU time. (Either way, the "user" time is about 2x the non-ASan case).

So I think keeping 1.5 TB is better. Since LLVM happily did the wrong thing for a _low_ power of 2, I think it's better to stay clear of that case.

I updated the comment to explain the situation better.
</blockquote></details>

Ah, I see. Weird and risky optimization...
+1 to the current version then.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1083 at r2](https://reviewable.io/reviews/gramineproject/gramine/32#-Mk7W6P-3DHy-l_9cmDP:-Mkgs9Bj1kLL_z1NH9UT:bvdcwgq) ([raw file](https://github.com/gramineproject/gramine/blob/78269e597eeeea188b9e9659234dc3e2b175f3b2/Pal/src/host/Linux-SGX/sgx_main.c#L1083)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually `MAP_FIXED_NOREPLACE` is not available on Ubuntu 18.04 either... It uses glibc 2.27, which doesn't define it, and Linux 4.15, which doesn't have it yet.

I'll drop it for now, and also remove it from the ASan code.
</blockquote></details>

Too bad :(


<!-- Sent from Reviewable.io -->

2021-09-28 15:44 UTC, pwmarcz commented
Jenkins, retest Jenkins-Direct-Sanitizers please (timeout on `fcntl14` and `sendfile09` LTP tests)

2021-09-28 15:54 UTC, mkow requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[meson.build, line 109 at r8](https://reviewable.io/reviews/gramineproject/gramine/32#-Mkh5PzZ6OWpb_bugYms:-Mkh5Pz_AktWTiyUHYNJ:ba57alx) ([raw file](https://github.com/gramineproject/gramine/blob/de42e8413d4b9a3e3382adcff156b7d8f094e5cc/meson.build#L109)):*
> ```Meson
> 
> if asan
>     if meson.get_compiler('c').get_id() != 'clang' or meson.get_compiler('cpp').get_id() != 'clang'
> ```

I just noticed this, shouldn't this be `clang++` for C++?


<!-- Sent from Reviewable.io -->

2021-09-28 16:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[meson.build, line 109 at r8](https://reviewable.io/reviews/gramineproject/gramine/32#-Mkh5PzZ6OWpb_bugYms:-Mkh7iOu6Uuu2Ktf5UTx:bezdfw3) ([raw file](https://github.com/gramineproject/gramine/blob/de42e8413d4b9a3e3382adcff156b7d8f094e5cc/meson.build#L109)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just noticed this, shouldn't this be `clang++` for C++?
</blockquote></details>

No. The "compiler ID" returned by Meson is `clang`. I checked that manually, but also otherwise it would've failed Jenkins.


<!-- Sent from Reviewable.io -->

2021-09-28 16:03 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[meson.build, line 109 at r8](https://reviewable.io/reviews/gramineproject/gramine/32#-Mkh5PzZ6OWpb_bugYms:-Mkh89U0-Yj0eqbcd0wz:bfnke39) ([raw file](https://github.com/gramineproject/gramine/blob/de42e8413d4b9a3e3382adcff156b7d8f094e5cc/meson.build#L109)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No. The "compiler ID" returned by Meson is `clang`. I checked that manually, but also otherwise it would've failed Jenkins.
</blockquote></details>

Huh, weird. And yes, you are right, it would have failed on Jenkins :)


<!-- Sent from Reviewable.io -->

2021-09-28 16:22 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/32)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-28 16:32 UTC, merged