[Pal] Remove `pal_sec` and refactor topology structures
gramineproject/gramine pull request #325
Opened 2022-01-07 11:27 UTC by mkow

## Description of the changes 

This is the core of #314 after splitting out other changes.

This is a preparation for a better topology sanitization and deduplication of PAL code.

## How to test this PR? 

CI + OpenVINO example (quoting @dimakuv: "OpenVINO is known to check sysfs. Without proper sysfs configuration, OpenVINO still works (IIRC) but is very slow."). Also, manual check for CPUID sanitization change.

2022-01-07 11:52 UTC, dimakuv requested changes
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoN0sqE3T1riiRrDAM:-MsoN0sqE3T1riiRrDAN:blz6vzy) ([raw file](https://github.com/gramineproject/gramine/blob/66840d9fd356e4c8da59ca108b7073206933a9a4/Pal/src/host/Linux-SGX/db_main.c#L248)):*
> ```C
> }
> 
> static int sanitize_cache_topology_info(PAL_CORE_CACHE_INFO* cache, int64_t cache_lvls_cnt,
> ```

A bit weird that you changed this to `cache_indices_cnt` in other places but not here. Is this intended?


<!-- Sent from Reviewable.io -->

2022-01-07 11:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 39 of 40 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 248 at r1](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoN0sqE3T1riiRrDAM:-MsoOW000cz3fmuBizNt:b-m5dwdh) ([raw file](https://github.com/gramineproject/gramine/blob/66840d9fd356e4c8da59ca108b7073206933a9a4/Pal/src/host/Linux-SGX/db_main.c#L248)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A bit weird that you changed this to `cache_indices_cnt` in other places but not here. Is this intended?
</blockquote></details>

Nah, just an omission :) Done.


<!-- Sent from Reviewable.io -->

2022-01-07 12:11 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-common/topo_info.c, line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoRV2gCnl_cwAYciNg:-MsoRV2gCnl_cwAYciNh:b-xvzr02) ([raw file](https://github.com/gramineproject/gramine/blob/5c2de17f7b5c5d70b0f874425f39865f61900b36/Pal/src/host/Linux-common/topo_info.c#L146)):*
> ```C
>     }
> 
>     for (int lvl = 0; lvl < cache_indices_cnt; lvl++) {
> ```

What about this then? Should be `idx` or `cache_index` I guess?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 250 at r2](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoRcQ411PnXrNRCCsW:-MsoRcQ411PnXrNRCCsX:b-xvzr02) ([raw file](https://github.com/gramineproject/gramine/blob/5c2de17f7b5c5d70b0f874425f39865f61900b36/Pal/src/host/Linux-SGX/db_main.c#L250)):*
> ```C
> static int sanitize_cache_topology_info(PAL_CORE_CACHE_INFO* cache, int64_t cache_indices_cnt,
>                                         int64_t cores_cnt) {
>     for (int64_t lvl = 0; lvl < cache_indices_cnt; lvl++) {
> ```

What about this then? Should be `idx` or `cache_index` I guess?


<!-- Sent from Reviewable.io -->

2022-01-07 12:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 38 of 40 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-common/topo_info.c, line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoRV2gCnl_cwAYciNg:-MsoTmWd8GK1Fb73RNrs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5c2de17f7b5c5d70b0f874425f39865f61900b36/Pal/src/host/Linux-common/topo_info.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this then? Should be `idx` or `cache_index` I guess?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 250 at r2](https://reviewable.io/reviews/gramineproject/gramine/325#-MsoRcQ411PnXrNRCCsW:-MsoTn_F2SrijOGtac6P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5c2de17f7b5c5d70b0f874425f39865f61900b36/Pal/src/host/Linux-SGX/db_main.c#L250)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this then? Should be `idx` or `cache_index` I guess?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-07 13:38 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-08 00:10 UTC, boryspoplawski requested changes
> Reviewed 38 of 40 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/325#-MsquAQT44XGdZuQ1P9x:-MsquAQT44XGdZuQ1P9y:bkzhgo) (no related file):*
Many places in this PR use `int` as index iterator type. Most of them are probably existing issue, for others not sure, since some code was moved around.
Do you want to this this in this PR?

Update: scratch that, there is a lot more of issues, we don't want to fix all of them in this PR....

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msr0D57CapndG0A3U3h:-Msr0D57CapndG0A3U3i:b5w2ywo) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/arch/x86_64/pal_topology.h#L69)):*
> ```objc
>      * from the untrusted host as a start argument (but the rest of this struct _is_ used this
>      * way). */
>     PAL_CPU_INFO cpu_info;
> ```

IMO this should be move out, not because of its origins, but because it's not really part of topology, it's kind of orthogonal.
___
*[Pal/src/host/Linux-common/topo_info.c, line 211 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsquvBpCSxhBaBj_l_Q:-MsquvBpCSxhBaBj_l_R:b4qqxrf) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-common/topo_info.c#L211)):*
> ```C
> 
>     int possible_logical_cores_cnt = get_hw_resource("/sys/devices/system/cpu/possible",
>                                                  /*count=*/true);
> ```

Wrong alignment
___
*[Pal/src/host/Linux-SGX/db_main.c, line 405 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqvthkCy6uYgMqK-nY:-MsqvthkCy6uYgMqK-nZ:bhu3qut) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L405)):*
> ```C
>     }
> 
>     /* TODO: temporary measure, remove it once sysfs topology is thoroughly validated */
> ```

What is this comment about? What exactly here is a "temporary measure"?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqwa8R0dWIeC_P8Ts5:-Msqwa8R0dWIeC_P8Ts6:b-wzbc3z) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L187)):*
> ```C
>  * through xfrm what extensions are enabled inside the enclave.
>  */
> static void sanitize_cpuid(uint32_t leaf, uint32_t subleaf, uint32_t values[4] /* in/out */) {
> ```

Maybe just write a proper comment in sphinx format?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Msqywdr5uX0-nW1blpD:b-rl9834) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
> ```C
> 
> int _DkGetTopologyInfo(PAL_TOPO_INFO* topo_info) {
>     if (!g_pal_public_state.enable_sysfs_topology) {
> ```

From what I can see parts of this feature are not hidden behind this flag anymore. Why is that?


<!-- Sent from Reviewable.io -->

2022-01-08 07:06 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
`LibOS` component is missing? Change `[Pal]` -> `[Pal,LibOS]`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqEP9R-_ONzqFTkcgo:-MsqEP9R-_ONzqFTkcgp:b-2on67a) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/LibOS/shim/src/fs/sys/cpu_info.c#L51)):*
> ```C
>     } else if (strcmp(name, "physical_package_id") == 0) {
>         snprintf(buf, sizeof(buf), "%d\n",
>                  g_pal_public_state->topo_info.cpu_to_socket[cpu_num]);
> ```

Can this be in the same line? Does it exceed 100 chars?
___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-MsqIO68Aq46uj7cQ02n:bdg44tl) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
> ```objc
> // Returns 0 on success, negative PAL code on failure
> int _DkGetCPUInfo(PAL_CPU_INFO* info);
> int _DkGetTopologyInfo(struct pal_topo_info* topo_info);
> ```

Why is a typedef struct not preferred?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msr0D57CapndG0A3U3h:-MsrEAFb1qXeC8Q-Ewqd:b-14mn62) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/arch/x86_64/pal_topology.h#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO this should be move out, not because of its origins, but because it's not really part of topology, it's kind of orthogonal.
</blockquote></details>

+1 and agree with @boryspoplawski's comment. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 687 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssITWX1r-1-PyBmp1-:-MssITWX1r-1-PyBmp10:b-bweagp) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L687)):*
> ```C
>     assert(IS_POWER_OF_2(g_pal_public_state.alloc_align));
> 
>     // TODO: change to `copy_and_sanitize_topo_info()`
> ```

Can you please clarify what this TODO means?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 840 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssPzmQ8mjoBC3oRED9:-MssPzmQ8mjoBC3oREDA:bq5icvm) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L840)):*
> ```C
> }
> 
> // TODO: Refactor and remove? Or move the parsing from db_main:pal_linux_main to here?
> ```

My vote will be to move it here so that we can maintain uniformity between Linux and Linux-SGX PAL.


<!-- Sent from Reviewable.io -->

2022-01-09 22:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 31 of 40 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/325#-MsquAQT44XGdZuQ1P9x:-Mt-pk9l8R_I-DEoUc6S:b-bo7c4v) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Many places in this PR use `int` as index iterator type. Most of them are probably existing issue, for others not sure, since some code was moved around.
Do you want to this this in this PR?

Update: scratch that, there is a lot more of issues, we don't want to fix all of them in this PR....
</blockquote></details>

Planned for the future, together with `PAL_NUM` removal from topology.

---
___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`LibOS` component is missing? Change `[Pal]` -> `[Pal,LibOS]`
</blockquote></details>

Will add at rebase.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 51 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqEP9R-_ONzqFTkcgo:-Mt-q8Y0BJZjNbSwTYlB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/LibOS/shim/src/fs/sys/cpu_info.c#L51)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can this be in the same line? Does it exceed 100 chars?
</blockquote></details>

Done.
___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt-qYNMDonCa0SPrZeS:bwynpud) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why is a typedef struct not preferred?
</blockquote></details>

I don't have a strong preference, but outside of PAL API we rather use vanilla C structs, without typedefs, so I unified it this way.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msr0D57CapndG0A3U3h:-Mt-rrCy2j76dFWfU2Yp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/arch/x86_64/pal_topology.h#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

+1 and agree with @boryspoplawski's comment. 
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 211 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsquvBpCSxhBaBj_l_Q:-Mt-rwG08dbrWsLg1PLj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-common/topo_info.c#L211)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wrong alignment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 405 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqvthkCy6uYgMqK-nY:-Mt-s0oD4uVc7NBJ008T:b-eeaft0) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this comment about? What exactly here is a "temporary measure"?
</blockquote></details>

This memset, we should just initialize all the fields anyways without a need for memset if we didn't have this feature-switch. Also, this comment was moved from `db_misc.c`.
Or maybe you think we should keep this memset even in the final version, just in case we leave something uninitialized?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 687 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssITWX1r-1-PyBmp1-:-Mt-t-gY5ohoKQEPhKM9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L687)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can you please clarify what this TODO means?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqwa8R0dWIeC_P8Ts5:-Mt-uIvV0GOY5VymfYLH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe just write a proper comment in sphinx format?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 840 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssPzmQ8mjoBC3oRED9:-Mt-xZBu3xZtLk6aPrKV:b5c4j6d) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L840)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

My vote will be to move it here so that we can maintain uniformity between Linux and Linux-SGX PAL.
</blockquote></details>

Done (changed the TODO).
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt-xccW8QR-TrcV9Pp4:by5h9og) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From what I can see parts of this feature are not hidden behind this flag anymore. Why is that?
</blockquote></details>

I think these were only half-disabled, due to their duplication (these fields were duplicated between `PAL_TOPO_INFO` and `PAL_CPU_INFO`). So, when merging I kept them enabled.


<!-- Sent from Reviewable.io -->

2022-01-09 23:16 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will add at rebase.
</blockquote></details>

But nothing changed in LibOS, so there is no need for this.
___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt04MCBDYuE3qnJyqyQ:b-hesu6g) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't have a strong preference, but outside of PAL API we rather use vanilla C structs, without typedefs, so I unified it this way.
</blockquote></details>

`typedef` only hides information, so we use it only in places where we want to hide the actual type (e.g. `PAL_HANDLE` in LibOS).
___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt050z_49mZxBwy9qDh:b-ds01o2) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
> ```objc
>     double cpu_bogomips;
>     const char* cpu_flags;
> } PAL_CPU_INFO;
> ```

Is this struct really arch agnostic?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 405 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqvthkCy6uYgMqK-nY:-Mt05WAL7eKsP8Ax6jPo:b-dvqtvl) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This memset, we should just initialize all the fields anyways without a need for memset if we didn't have this feature-switch. Also, this comment was moved from `db_misc.c`.
Or maybe you think we should keep this memset even in the final version, just in case we leave something uninitialized?
</blockquote></details>

I think it's fine to leave it, especially since it's just one time initialization.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 688 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt05duf-55Z1ogUyyaL:-Mt05duf-55Z1ogUyyaM:bx9537k) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/src/host/Linux-SGX/db_main.c#L688)):*
> ```C
> 
>     // TODO: Change to `copy_and_sanitize_topo_info()` (a single API which securely imports and
>     // sanitizes the topology description).
> ```

Please use `/* */` for multi line comments.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqwa8R0dWIeC_P8Ts5:-Mt05nkY8nXd_6AhKA_0:b4l1y2v) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you've left the comment in defintion
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt06JsM6_v1qyVG0NQi:b-n9jie2) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think these were only half-disabled, due to their duplication (these fields were duplicated between `PAL_TOPO_INFO` and `PAL_CPU_INFO`). So, when merging I kept them enabled.
</blockquote></details>

Then we should disable them as intended


<!-- Sent from Reviewable.io -->

2022-01-09 23:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 38 of 40 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But nothing changed in LibOS, so there is no need for this.
</blockquote></details>

That was my original idea (that only the callsites of PAL changed in LibOS, so '[Pal]' is enough), but I'm not sure how exactly do we interpret these tags ;)
___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt0AKRd2PG6kCVdMfnX:b29iitn) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this struct really arch agnostic?
</blockquote></details>

I think so, and somehow all PALs need to provide data for `/proc/cpuinfo`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 405 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqvthkCy6uYgMqK-nY:-Mt0Adi71wP64eIv40XN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it's fine to leave it, especially since it's just one time initialization.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 688 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt05duf-55Z1ogUyyaL:-Mt0AlvT3UIvFVSDkY9-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/src/host/Linux-SGX/db_main.c#L688)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `/* */` for multi line comments.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqwa8R0dWIeC_P8Ts5:-Mt08PfM4DSU2g2sNboE:b-p4ybu) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But you've left the comment in defintion
</blockquote></details>

Oops, fixed.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt08svt0JimG8wcAcdg:bkcy3j7) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then we should disable them as intended
</blockquote></details>

The problem is that `/proc/cpuinfo` will break then, which may break a lot of apps :/


<!-- Sent from Reviewable.io -->

2022-01-10 08:18 UTC, dimakuv approved these changes
> Reviewed 6 of 9 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That was my original idea (that only the callsites of PAL changed in LibOS, so '[Pal]' is enough), but I'm not sure how exactly do we interpret these tags ;)
</blockquote></details>

Well, something changed in LibOS -- we change the callsites. I typically interpret it as "adding `[LibOS]` prefix".
___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt22GfN83CLPBg4u2Sf:b-mx910j) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`typedef` only hides information, so we use it only in places where we want to hide the actual type (e.g. `PAL_HANDLE` in LibOS).
</blockquote></details>

I agree with Borys. We are slowly getting rid of typedefs. It unclutters our code and makes type information more visible. At least to me, it greatly helps while reading the code. In the end, we hopefully end up with only `PAL_HANDLE` being a typedef (== an opaque type).
___
*[Pal/include/pal/pal.h, line 98 at r5](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt22hPgDaPa2ZhpKu5v:-Mt22hPgDaPa2ZhpKu5w:b-uheulc) ([raw file](https://github.com/gramineproject/gramine/blob/71a7f9f4a96d0b8058549cb912870706a0f194d1/Pal/include/pal/pal.h#L98)):*
> ```objc
>     double cpu_bogomips;
>     const char* cpu_flags;
> } PAL_CPU_INFO;
> ```

Now that you moved it around completely, isn't it a good time to change it to `struct pal_cpu_info`? But not blocking.


<!-- Sent from Reviewable.io -->

2022-01-10 10:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 32 of 40 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 98 at r5](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt22hPgDaPa2ZhpKu5v:-Mt2aRea6Lg_sbsCdZtx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/71a7f9f4a96d0b8058549cb912870706a0f194d1/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that you moved it around completely, isn't it a good time to change it to `struct pal_cpu_info`? But not blocking.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 15:02 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 32 of 40 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt3Guq33QfzZ-y6IQlZ:b-ckf6h7) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Borys. We are slowly getting rid of typedefs. It unclutters our code and makes type information more visible. At least to me, it greatly helps while reading the code. In the end, we hopefully end up with only `PAL_HANDLE` being a typedef (== an opaque type).
</blockquote></details>

Got it. So, to be uniform can we remove other typedefs in `pal_topology.h`?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 687 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssITWX1r-1-PyBmp1-:-Mt3Ozg1A7WtoOTKK1sb:b-vip92p) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L687)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ah ok, so you mean to combine this copy with the sanitization of the topology info done in `parse_host_topo_info()` and `parse_advanced_host_topo_info()`. Is that right?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 840 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssPzmQ8mjoBC3oRED9:-Mt3PzjI3RhfCw3WPB9h:brjvtrh) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L840)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done (changed the TODO).
</blockquote></details>

Why not make the change as part of this PR? Is this planned for another PR?


<!-- Sent from Reviewable.io -->

2022-01-10 15:07 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt3WmFK5OlyPeLA7uuf:b-7xgjfv) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it. So, to be uniform can we remove other typedefs in `pal_topology.h`?
</blockquote></details>

I think the plan is that Michal will do it in the follow-up PRs.


<!-- Sent from Reviewable.io -->

2022-01-10 15:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt3_Kl7AaLczP-xUe1F:b-z8li7m) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the plan is that Michal will do it in the follow-up PRs.
</blockquote></details>

Yes, that's the plan, just wanted to separate trivial type changes from this refactoring.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 687 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssITWX1r-1-PyBmp1-:-Mt3_UEBAIKzJinmM-wr:b2nih0v) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_main.c#L687)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ah ok, so you mean to combine this copy with the sanitization of the topology info done in `parse_host_topo_info()` and `parse_advanced_host_topo_info()`. Is that right?
</blockquote></details>

yup
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 840 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssPzmQ8mjoBC3oRED9:-Mt3__HgBpnFXMcN4VJ-:bwg4w3a) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L840)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why not make the change as part of this PR? Is this planned for another PR?
</blockquote></details>

Yup, I planned it for another PR or maybe together with sanitization rework, didn't want to add even more changes to this PR.


<!-- Sent from Reviewable.io -->

2022-01-10 17:01 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal_internal.h, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqIO68Aq46uj7cQ02m:-Mt3vWwe30DqN2pl7P3L:beqh7lp) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/include/pal_internal.h#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, that's the plan, just wanted to separate trivial type changes from this refactoring.
</blockquote></details>

Got it, resolving.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 840 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MssPzmQ8mjoBC3oRED9:-Mt3vlC48R0gjfpzWULT:b8x4k8k) ([raw file](https://github.com/gramineproject/gramine/blob/e9303c7489df0de87c14d5ed9415462271c901e1/Pal/src/host/Linux-SGX/db_misc.c#L840)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I planned it for another PR or maybe together with sanitization rework, didn't want to add even more changes to this PR.
</blockquote></details>

OK, resolving


<!-- Sent from Reviewable.io -->

2022-01-10 21:50 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, something changed in LibOS -- we change the callsites. I typically interpret it as "adding `[LibOS]` prefix".
</blockquote></details>

And I do the other way round, specially in cases like this, where only PAL interface changed and all LibOS changes are just simple name fixups.
___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt4xTWu8q85Skv5qPR2:b-r3i8e5) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think so, and somehow all PALs need to provide data for `/proc/cpuinfo`.
</blockquote></details>

I'm pretty sure `/proc/cpuinfo` is arch specific. Also this struct used to be in arch specific header before this PR.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt4xxax5qJI2F6u4IY6:b2h3o2t) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is that `/proc/cpuinfo` will break then, which may break a lot of apps :/
</blockquote></details>

As far as I remember we had some "basic" info which was unconditionally enabled and "advanced" which was hidden behind this switch. For "basic" info `cpuid` + bogomips were enough, if I recall correctly.


<!-- Sent from Reviewable.io -->

2022-01-10 23:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)

___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt5M_H0-yaz7-rm56Im:b-x0ynfa) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm pretty sure `/proc/cpuinfo` is arch specific. Also this struct used to be in arch specific header before this PR.
</blockquote></details>

Maybe it's time to summon @stefanberger? :) How does `/proc/cpuinfo` look on ppc64 and which fields of this struct are different there?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt5MxEICTyp9tFt63Zu:b2tox3b) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
> As far as I remember we had some "basic" info which was unconditionally enabled and "advanced" which was hidden behind this switch.

That was the idea, but it seems the implementation of this switch didn't disable the duplicated entries ¯\\_(ツ)_/¯

> For "basic" info `cpuid` + bogomips were enough, if I recall correctly.

But not for `/proc/cpuinfo` at least. See e.g.:
https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/LibOS/shim/src/fs/proc/info.c#L125


<!-- Sent from Reviewable.io -->

2022-01-11 00:09 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 842 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-Msqywdr5uX0-nW1blpC:-Mt5Pkf27Qau9t0G4xxd:b-tbxc3n) ([raw file](https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux-SGX/db_misc.c#L842)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> As far as I remember we had some "basic" info which was unconditionally enabled and "advanced" which was hidden behind this switch.

That was the idea, but it seems the implementation of this switch didn't disable the duplicated entries ¯\\_(ツ)_/¯

> For "basic" info `cpuid` + bogomips were enough, if I recall correctly.

But not for `/proc/cpuinfo` at least. See e.g.:
https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/LibOS/shim/src/fs/proc/info.c#L125
</blockquote></details>

Ok, seems some info was treated as basic, passed from urts and sanitized regardless of that switch indeed...


<!-- Sent from Reviewable.io -->

2022-01-11 03:37 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt6BlU86wOo0JNZ2gIL:b-3qpdah) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe it's time to summon @stefanberger? :) How does `/proc/cpuinfo` look on ppc64 and which fields of this struct are different there?
</blockquote></details>

Some of the data structures are the same: https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-2dabf95abb6c566632f77a69a71dc16e63fedaee90cd41494a93cfa2ed0c54e3R204

proc is a bit different:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-75cff2cc5cb68dd203fb33adc05eb280f38634376e2a4686be095f136c41707eR46

diffs in test case:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-eb55ffbe8471fa1241e1aced4f9d0f1820dce3d045be97dc8b171261a013742bR128

topo info diffs:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-713ce9dc6240f95fd6e13e21ce6a56d6da07627ea2329a200c062e750696ae52R165


<!-- Sent from Reviewable.io -->

2022-01-11 17:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt997-nCNAGghip5OJI:bh2bqe6) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Some of the data structures are the same: https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-2dabf95abb6c566632f77a69a71dc16e63fedaee90cd41494a93cfa2ed0c54e3R204

proc is a bit different:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-75cff2cc5cb68dd203fb33adc05eb280f38634376e2a4686be095f136c41707eR46

diffs in test case:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-eb55ffbe8471fa1241e1aced4f9d0f1820dce3d045be97dc8b171261a013742bR128

topo info diffs:
https://github.com/stefanberger/graphene4ppc64/commit/54d9e87d320588fe772d282bc8955a4b17b6eba3#diff-713ce9dc6240f95fd6e13e21ce6a56d6da07627ea2329a200c062e750696ae52R165


</blockquote></details>

@stefanberger Thank you! These links are super helpful :)
I think it makes sense to move this structure definition to arch-specific directory, I'll try to do this in a moment.


<!-- Sent from Reviewable.io -->

2022-01-11 17:29 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt9AFga0Y7wtJu9xxtp:b67zt96) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger Thank you! These links are super helpful :)
I think it makes sense to move this structure definition to arch-specific directory, I'll try to do this in a moment.
</blockquote></details>

Just FYI: Some of the changes that you may have seen are due to SMT enabling 8(!) CPUs per core on ppc64 and test cases ended up timing out due to it being too slow to read sysfs. So it's replicating info it reads about one processor up to 7 times. Unfortunately that all caused changes that I wished to have avoided.


<!-- Sent from Reviewable.io -->

2022-01-11 20:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: 38 of 40 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/include/pal/pal.h, line 98 at r4](https://reviewable.io/reviews/gramineproject/gramine/325#-Mt050zZ77RvF1Iky6MR:-Mt9ur_57JHEqy9eSkPX:b-a8fwr7) ([raw file](https://github.com/gramineproject/gramine/blob/ab8187e46def7ca45b4de08a5fd8be741786f428/Pal/include/pal/pal.h#L98)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Just FYI: Some of the changes that you may have seen are due to SMT enabling 8(!) CPUs per core on ppc64 and test cases ended up timing out due to it being too slow to read sysfs. So it's replicating info it reads about one processor up to 7 times. Unfortunately that all caused changes that I wished to have avoided.
</blockquote></details>

Ok, I moved this struct to `pal-arch.h`.


<!-- Sent from Reviewable.io -->

2022-01-12 08:09 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And I do the other way round, specially in cases like this, where only PAL interface changed and all LibOS changes are just simple name fixups.
</blockquote></details>

Ok, however Michal decides. If Michal concurs with Borys, I'll also use this notation in the future.


<!-- Sent from Reviewable.io -->

2022-01-12 14:04 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-12 14:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/325#-MsqDlHO8IffKNsFpeXZ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, however Michal decides. If Michal concurs with Borys, I'll also use this notation in the future.
</blockquote></details>

I slightly prefer Borys' version, so I left it this way.


<!-- Sent from Reviewable.io -->

2022-01-12 14:17 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-01-12 14:24 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/325)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-12 14:49 UTC, merged