Fix
gramineproject/gramine pull request #33
Opened 2021-09-13 15:59 UTC by pwmarcz

## Description of the changes 

This fixes various small corner cases in filesystem code. As mentioned in #29, our test runner failed to detect these because the LTP test cases actually returned 0.

The LTP runner is also fixed.

Fixes #29.

The LTP tests fixed are `pwrite02`, `pwrite03` and `ftruncate03`.

## How to test this PR? 

Jenkins should pass, you can also run the above tests manually.

2021-09-13 16:50 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz and @woju)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 391 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV1EG8-ZxrBMjYpP90:-MjV1EG9BKxJ9g5x02ib:b-bdit15) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/fs/chroot/fs.c#L391)):*
> ```C
> 
>     if (count == 0) {
>         /* exit early: we allow null buffer when count is 0, and `DkStreamRead` doesn't allow it */
> ```

Why does `DkStreamRead` does not allow it? I see no reason for it...
___
*[LibOS/shim/src/fs/chroot/fs.c, line 433 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV1JY-9PKa9xwPwsVc:-MjV1JY0-T6xeZnBh1FW:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/fs/chroot/fs.c#L433)):*
> ```C
> 
>     if (count == 0) {
>         /* exit early: we allow null buffer when count is 0, and `DkStreamWrite` doesn't allow it */
> ```

ditto
___
*[LibOS/shim/src/sys/shim_open.c, line 564 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV-Cw11c0k61SKLHxI:-MjV-Cw11c0k61SKLHxJ:bnkpx3d) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/sys/shim_open.c#L564)):*
> ```C
> 
>     if (!(hdl->acc_mode & MAY_WRITE)) {
>         ret = -EINVAL;
> ```

Could you add a comment that Linux does this (instead of `EBADF` like in other places)?
___
*[LibOS/shim/src/sys/shim_open.c, line 572 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjUzp4s0PJmMdE8jjR4:-MjUzp4s0PJmMdE8jjR5:b8el4gx) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/sys/shim_open.c#L572)):*
> ```C
> 
>     if (hdl->is_dir || !fs->fs_ops->truncate) {
>         ret = -EINVAL;
> ```

`ret` is already set here. Please either set it everywhere or nowhere (i.e. unify).
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjV2TUgClHodul1Ah94:b-s6oq09) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
> ```Python
>                 raise Fail('returncode={}'.format(returncode))
>             else:
>                 # Parse output anyway: unfortunately some tests do not exit with non-zero code when
> ```

I've raised this issue already before, but was told this is done this way intentionally, tho I have no idea why.
cc @mkow @woju 
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 323 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2EYmDxXdDDqZoegs:-MjV2EYmDxXdDDqZoegt:b10v0v) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L323)):*
> ```Python
>                 # Parse output anyway: unfortunately some tests do not exit with non-zero code when
>                 # failing.
>                 self._parse_test_output()
> ```

Can't we change it to just:
```
            if must_pass is not None or returncode == 0:
                self._parse_test_output(must_pass)
            else:
                raise Fail('returncode={}'.format(returncode))
```


<!-- Sent from Reviewable.io -->

2021-09-13 16:50 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz and @woju)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 391 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV1EG8-ZxrBMjYpP90:-MjV3KQ358AoYYVZEqy3:b-jdjqoj) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/fs/chroot/fs.c#L391)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why does `DkStreamRead` does not allow it? I see no reason for it...
</blockquote></details>

I mean, why can't we make it accept `count == 0`?


<!-- Sent from Reviewable.io -->

2021-09-13 17:20 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: 0 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

___
*[LibOS/shim/src/sys/shim_open.c, line 564 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV-Cw11c0k61SKLHxI:-MjV6y655dnCYhF5QbUT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/sys/shim_open.c#L564)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add a comment that Linux does this (instead of `EBADF` like in other places)?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 572 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjUzp4s0PJmMdE8jjR4:-MjV6txn9t-0eWv69M1a:bij0fk0) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/sys/shim_open.c#L572)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`ret` is already set here. Please either set it everywhere or nowhere (i.e. unify).
</blockquote></details>

OK. I'd rather be explicit.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjV5YdZ9dvqu-URnE5i:bh83heu) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've raised this issue already before, but was told this is done this way intentionally, tho I have no idea why.
cc @mkow @woju 
</blockquote></details>

Yeah, I think this is a pretty strong argument against. LTP can't be trusted.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 323 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2EYmDxXdDDqZoegs:-MjV67Ge12B3N-FyTuki:b-nxnsb) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L323)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can't we change it to just:
```
            if must_pass is not None or returncode == 0:
                self._parse_test_output(must_pass)
            else:
                raise Fail('returncode={}'.format(returncode))
```
</blockquote></details>

Done, almost: I want it to be explicit that we're failing because of non-zero exit code.

(Also I used `not must_pass` to treat empty set the same as no `must-pass` entry).
___
*[LibOS/shim/src/fs/chroot/fs.c, line 391 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV1EG8-ZxrBMjYpP90:-MjV7IM66VYWC09MhKXC:b6196t1) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/fs/chroot/fs.c#L391)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I mean, why can't we make it accept `count == 0`?
</blockquote></details>

I assumed there was a reason, but yes, this is Graphene. If Jenkins passes, then we should be good :)


<!-- Sent from Reviewable.io -->

2021-09-13 17:28 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjVBJB-37x8u1pPN6IR:bdhazn5) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
Sorry, I did not understand your comment. What is a strong argument against what?

> LTP can't be trusted.

This is actually not LTP, but Gramine issue (shared memory does not work, yet `MAP_SHARED` is accepted, but is silently discarded). 
___
*[LibOS/shim/src/fs/chroot/fs.c, line 391 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV1EG8-ZxrBMjYpP90:-MjVBqUg6LeCl0g5RcDA:b32vir) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/src/fs/chroot/fs.c#L391)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I assumed there was a reason, but yes, this is Graphene. If Jenkins passes, then we should be good :)
</blockquote></details>

;)


<!-- Sent from Reviewable.io -->

2021-09-13 23:52 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/33#-MjWXqCRDwNVlDjLJtBj):*
trailing `(`?
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjWYbO49b_XRvS1Cdao:bluhhe4) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sorry, I did not understand your comment. What is a strong argument against what?

> LTP can't be trusted.

This is actually not LTP, but Gramine issue (shared memory does not work, yet `MAP_SHARED` is accepted, but is silently discarded). 
</blockquote></details>

Tbh I don't remember this discussion, Paweł's fix looks good.


<!-- Sent from Reviewable.io -->

2021-09-14 07:28 UTC, dimakuv approved these changes
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

___
*[LibOS/shim/src/sys/shim_open.c, line 30 at r2](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYBmba2iojc0-LqFOK:-MjYBmba2iojc0-LqFOL:busqknq) ([raw file](https://github.com/gramineproject/gramine/blob/7d8cabd80f601f671513ae8557cc7b45bf1e7836/LibOS/shim/src/sys/shim_open.c#L30)):*
> ```C
> ssize_t do_handle_read(struct shim_handle* hdl, void* buf, size_t count) {
>     if (!(hdl->acc_mode & MAY_READ))
>         return -EBADF;
> ```

For my own understanding: so it was always broken? Why does https://github.com/gramineproject/gramine/issues/29 talk only about a regression after your Inodes commit? What did Inodes commit reveal that some LTP tests started failing?


<!-- Sent from Reviewable.io -->

2021-09-14 07:31 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-MjYColu0m7bQq65VIxT:b-g4l9hg) (no related file):*
Reviewable is being weird: it doesn't show the reverted changes in `chroot_fs.c` file (though I can see them on GitHub). Anyone knows why this behavior?

---


<!-- Sent from Reviewable.io -->

2021-09-14 11:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-MjYvmBwA5nJU0Rqbhhx:bqris8q) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Reviewable is being weird: it doesn't show the reverted changes in `chroot_fs.c` file (though I can see them on GitHub). Anyone knows why this behavior?
</blockquote></details>

I'm seeing it in Reviewable: the diff is empty; the change appears when I select a range like ⊥..r1 or r1..r2.

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/33#-MjWXqCRDwNVlDjLJtBj):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

trailing `(`?
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/sys/shim_open.c, line 30 at r2](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYBmba2iojc0-LqFOK:-MjYwvWR00WRmq0ThfO8:byt8hcf) ([raw file](https://github.com/gramineproject/gramine/blob/7d8cabd80f601f671513ae8557cc7b45bf1e7836/LibOS/shim/src/sys/shim_open.c#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For my own understanding: so it was always broken? Why does https://github.com/gramineproject/gramine/issues/29 talk only about a regression after your Inodes commit? What did Inodes commit reveal that some LTP tests started failing?
</blockquote></details>

There was an additional check in `chroot/fs.c` before. I'm trying to move all these checks _out_ of individual filesystems so that there is less duplication.

(I know there is now duplication across different syscalls, but I think that's more manageable.)
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjYxBNs7Whzu9852CLP:bozyk49) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Tbh I don't remember this discussion, Paweł's fix looks good.
</blockquote></details>

I meant that the issue we encountered here is a strong argument against not parsing the output (and trusting LTP's return code). Since we now know LTP to sometimes return 0 even if some tests fail, we cannot trust the 0 return code.


<!-- Sent from Reviewable.io -->

2021-09-14 11:07 UTC, woju reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjYwy8UBWieceNUQJhI:bmw20sx) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I meant that the issue we encountered here is a strong argument against not parsing the output (and trusting LTP's return code). Since we now know LTP to sometimes return 0 even if some tests fail, we cannot trust the 0 return code.
</blockquote></details>

The parser is sh\*tty, so I didn't want to run it if it's not needed (hence if must-pass is empty, we don't, and also that's why we detect the situation when it should be removed and bother the developer). The underlying assumption was that the returncode correctly reflects the overall test result. IIUC this assumption is false? If so, this change is unfortunately correct.


<!-- Sent from Reviewable.io -->

2021-09-14 11:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 321 at r1](https://reviewable.io/reviews/gramineproject/gramine/33#-MjV2TUgClHodul1Ah93:-MjYzOEzDfsbw1R7BjM4:b-e8vtkj) ([raw file](https://github.com/gramineproject/gramine/blob/76694d3dc40ba7f59f07c16ace1333047f1c753d/LibOS/shim/test/ltp/runltp_xml.py#L321)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The parser is sh\*tty, so I didn't want to run it if it's not needed (hence if must-pass is empty, we don't, and also that's why we detect the situation when it should be removed and bother the developer). The underlying assumption was that the returncode correctly reflects the overall test result. IIUC this assumption is false? If so, this change is unfortunately correct.
</blockquote></details>

Okay, @woju explained to me the issue with `MAP_SHARED`, I agree it's Gramine's fault.

I'll add an explanation here so that it's written somewhere (instead of remaining oral knowledge).


<!-- Sent from Reviewable.io -->

2021-09-14 11:27 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-MjZ2-QuBImIL7gQLrYb:b-jf9ne) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm seeing it in Reviewable: the diff is empty; the change appears when I select a range like ⊥..r1 or r1..r2.
</blockquote></details>

In that box over file matrix, in the left column you have the number of files. Under it there''s "+1 obsolete" and you can click on "reveal".

---


<!-- Sent from Reviewable.io -->

2021-09-14 13:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-MjZOHfa9c4gPzKsSR-2:b-31avor) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In that box over file matrix, in the left column you have the number of files. Under it there''s "+1 obsolete" and you can click on "reveal".
</blockquote></details>

No, I don't have it. I know about this "obsolete" thingy in Reviewable, but in this particular PR I don't see it. I can only assume that it's because I was late to the party and haven't seen the original changes in `chroot_fs.c`, so Reviewable decided I should never learn it.

---


<!-- Sent from Reviewable.io -->

2021-09-14 14:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-MjZl8lv7LkxAIP8iBrS:b-gd33e3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, I don't have it. I know about this "obsolete" thingy in Reviewable, but in this particular PR I don't see it. I can only assume that it's because I was late to the party and haven't seen the original changes in `chroot_fs.c`, so Reviewable decided I should never learn it.
</blockquote></details>

Weird, you should have had it in ⊥..r1 if you expand the "Reverted" section. I don't like this auto-hiding.

---


<!-- Sent from Reviewable.io -->

2021-09-14 17:41 UTC, pwmarcz commented
Jenkins, retest Jenkins-Debug-18.04 please (random timeout on LTP tests, we've seen that before)

2021-09-14 18:19 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/33#-MjYColu0m7bQq65VIxS:-Mj_X4aU6tV7nxoK6-zY:b-rd7u49) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Weird, you should have had it in ⊥..r1 if you expand the "Reverted" section. I don't like this auto-hiding.
</blockquote></details>

I don't :( But whatever

---


<!-- Sent from Reviewable.io -->

2021-09-14 19:13 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-14 21:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-14 22:00 UTC, merged