[LibOS] Add dummy entries in `/proc/stat` and `/proc/cpuinfo`
gramineproject/gramine pull request #330
Opened 2022-01-11 19:34 UTC by dimakuv

## Description of the changes 

We implement a minimal set of dummy values in these two procfs pseudo-files to satisfy workloads like Python's psutil library.

This PR is based on #328 (because I was testing the `qiskit` package in Python).

## How to test this PR? 

A new LibOS regression test is added to test `/proc/stat`.

Also see #328 description of Python `qiskit` package for manual testing.

2022-01-12 01:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 0 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAb7-A63F55ghC48VN):*
I think you meant `/proc/meminfo` instead of `/proc/cpuinfo`
___
*[LibOS/shim/test/regression/proc_stat.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAn1vP8xbzeGFeaPDG:-MtAn1vP8xbzeGFeaPDH:b3hkjlf) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L97)):*
> ```C
>     }
> 
>     if (val == UINT64_MAX) {
> ```

Can we also add a check for `key` string? This shouldn't be `<none>`
___
*[LibOS/shim/test/regression/proc_stat.c, line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAnWJg6ojcrMcZVnwp:-MtAnWJg6ojcrMcZVnwq:b-amn6s6) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L145)):*
> ```C
>     }
> 
>     if (cpu_cnt == 0)
> ```

Instead of comparing with zero, it would be better to compare with the number of processors online. We have used `sysconf(_SC_NPROCESSORS_ONLN)` function to get the number of processors online.
___
*[LibOS/shim/test/regression/proc_stat.c, line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAo1222PevJpFOWvW6:-MtAo1222PevJpFOWvW7:bbibwb6) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L149)):*
> ```C
> 
>     /* next lines are 'ctxt', 'btime', 'processes', 'procs_running', 'procs_blocked' */
>     if (line[0] == '\n')
> ```

Here it should have `ctxt` right? Can we check against this instead of `\n`?

I think a better approach would be to remove the entire check below
```
    if (cpu_cnt == 0)
        errx(1, "no 'cpuX' lines found");

    /* next lines are 'ctxt', 'btime', 'processes', 'procs_running', 'procs_blocked' */
    if (line[0] == '\n')
        goto out;
    if ((rv = parse_and_check_noncpu_line(line)) != 0)
        errx(1, "checking non-cpu line failed");

    while (fgets(line, sizeof(line), fp) != NULL) {
        if (line[0] == '\n')
            goto out;
        if ((rv = parse_and_check_noncpu_line(line)) != 0)
            errx(1, "checking non-cpu line failed");
    }
```

And simply have it as below,

```
    /* next lines are 'ctxt', 'btime', 'processes', 'procs_running', 'procs_blocked' */
    do {
        if ((rv = parse_and_check_noncpu_line(line)) != 0)
            errx(1, "checking non-cpu line failed");
    } while (fgets(line, sizeof(line), fp) != NULL);
```
___
*[LibOS/shim/test/regression/proc_stat.c, line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAoW3l8aZe3Z0N61KR:-MtAoW3l8aZe3Z0N61KS:bcik3im) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L163)):*
> ```C
> out:
>     fclose(fp);
>     printf("/proc/stat test passed (found %d CPUs)\n", cpu_cnt);
> ```

We can remove the `cpu_cnt` here if we have already validated it against `sysconf(_SC_NPROCESSORS_ONLN)`
___
*[LibOS/shim/test/regression/test_libos.py, line 855 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAfsEP1FKNSvyTfqgw:-MtAfsEP1FKNSvyTfqgx:blfsaw2) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/test_libos.py#L855)):*
> ```Python
>         self.assertIn('cpuinfo test passed', stdout)
> 
>     def test_021_procstat(self):
> ```

Do we need this new test since the test is just validating when we emulate in `LibOS`? proc_common.c should test all the /proc paths including `/proc/stat`. 


<!-- Sent from Reviewable.io -->

2022-01-12 08:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 0 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAb7-A63F55ghC48VN):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think you meant `/proc/meminfo` instead of `/proc/cpuinfo`
</blockquote></details>

Done. Force-pushed since the change is minimal and shouldn't disrupt the reviewers.
___
*[LibOS/shim/test/regression/proc_stat.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAn1vP8xbzeGFeaPDG:-MtCLdjrElpwaVJlrl_K:b4e8n1) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L97)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can we also add a check for `key` string? This shouldn't be `<none>`
</blockquote></details>

Done. Also changed from `<none>` to `""`, for simplicity.
___
*[LibOS/shim/test/regression/proc_stat.c, line 145 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAnWJg6ojcrMcZVnwp:-MtCMJZYDIh358O6B4gy:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L145)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Instead of comparing with zero, it would be better to compare with the number of processors online. We have used `sysconf(_SC_NPROCESSORS_ONLN)` function to get the number of processors online.
</blockquote></details>

Done
___
*[LibOS/shim/test/regression/proc_stat.c, line 149 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAo1222PevJpFOWvW6:-MtCMcFw-qgZk7hUWOUe:b-fbg47r) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L149)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here it should have `ctxt` right? Can we check against this instead of `\n`?

I think a better approach would be to remove the entire check below
```
    if (cpu_cnt == 0)
        errx(1, "no 'cpuX' lines found");

    /* next lines are 'ctxt', 'btime', 'processes', 'procs_running', 'procs_blocked' */
    if (line[0] == '\n')
        goto out;
    if ((rv = parse_and_check_noncpu_line(line)) != 0)
        errx(1, "checking non-cpu line failed");

    while (fgets(line, sizeof(line), fp) != NULL) {
        if (line[0] == '\n')
            goto out;
        if ((rv = parse_and_check_noncpu_line(line)) != 0)
            errx(1, "checking non-cpu line failed");
    }
```

And simply have it as below,

```
    /* next lines are 'ctxt', 'btime', 'processes', 'procs_running', 'procs_blocked' */
    do {
        if ((rv = parse_and_check_noncpu_line(line)) != 0)
            errx(1, "checking non-cpu line failed");
    } while (fgets(line, sizeof(line), fp) != NULL);
```
</blockquote></details>

Done. Thanks, I sometimes forget about `do .. while` construct :)
___
*[LibOS/shim/test/regression/proc_stat.c, line 163 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAoW3l8aZe3Z0N61KR:-MtCMlNU7dEVOflJLph4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L163)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We can remove the `cpu_cnt` here if we have already validated it against `sysconf(_SC_NPROCESSORS_ONLN)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 855 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAfsEP1FKNSvyTfqgw:-MtCMnWp3KpdjrZb0Ux0:batkxxo) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/test_libos.py#L855)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Do we need this new test since the test is just validating when we emulate in `LibOS`? proc_common.c should test all the /proc paths including `/proc/stat`. 
</blockquote></details>

`proc_common` simply shows which files are present, but doesn't show the file contents. I wanted a test that will immediately fail if anything changed in the `/proc/stat` emulation. I think having this new test is good for future-proofing our emulation.


<!-- Sent from Reviewable.io -->

2022-01-12 16:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/regression/proc_stat.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAn1vP8xbzeGFeaPDG:-MtDyGErAAcpbcilx1GT:b-vymu2) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Also changed from `<none>` to `""`, for simplicity.
</blockquote></details>

Thanks, can we also combine these 2 errors into one? Something like,
```
if ((val == UINT64_MAX) || !(strcmp(key, "")) {
    fprintf(stderr, "Malformed line found! Please check this '%s'\n", line);
}
``` 

But not blocking, just a suggestion.
___
*[LibOS/shim/test/regression/test_libos.py, line 855 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAfsEP1FKNSvyTfqgw:-MtE3dyh1gpKXqOYhqsw:bv56fo0) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/test_libos.py#L855)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`proc_common` simply shows which files are present, but doesn't show the file contents. I wanted a test that will immediately fail if anything changed in the `/proc/stat` emulation. I think having this new test is good for future-proofing our emulation.
</blockquote></details>

OK, makes sense.


<!-- Sent from Reviewable.io -->

2022-01-13 08:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/regression/proc_stat.c, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/330#-MtAn1vP8xbzeGFeaPDG:-MtHWKTOEEKcgk9RWmqH:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/60030377f2ec2df9bf678d45edc677687e2405ed/LibOS/shim/test/regression/proc_stat.c#L97)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, can we also combine these 2 errors into one? Something like,
```
if ((val == UINT64_MAX) || !(strcmp(key, "")) {
    fprintf(stderr, "Malformed line found! Please check this '%s'\n", line);
}
``` 

But not blocking, just a suggestion.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-01-13 14:34 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please.

Failed with:
```
test-direct / LibOS.shim.test.ltp.test_ltp.test_ltp[fdatasync01]
test-direct / LibOS.shim.test.ltp.test_ltp.test_ltp[writev07]
```

2022-01-25 04:33 UTC, kvinwang commented on LibOS/shim/src/fs/proc/info.c
> +        },
Might need more if we also want to satisfy Rust workloads.
See here for those expecting fields:
https://docs.rs/procfs/latest/src/procfs/meminfo.rs.html#323-382

2022-01-25 08:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kvinwang)

___
*[LibOS/shim/src/fs/proc/info.c, line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/330#-Mt9cf1jLWwMGOyYmczL-r3-61:-MuFMsqL26rFfC5iN48b:b-5crbxh) ([raw file](https://github.com/gramineproject/gramine/blob/039e51d4dfa33a2a98bf45aa49313774dd131f5d/LibOS/shim/src/fs/proc/info.c#L61)):*
<details><summary><i>Previously, kvinwang wrote…</i></summary><blockquote>

Might need more if we also want to satisfy Rust workloads.
See here for those expected fields:
https://docs.rs/procfs/latest/src/procfs/meminfo.rs.html#323-382
</blockquote></details>

Done. Thanks for this.


<!-- Sent from Reviewable.io -->

2022-01-25 12:23 UTC, boryspoplawski requested changes
> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kvinwang)

___
*[LibOS/shim/src/fs/proc/info.c, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuFz97d5hLY-jeIn_A3:-MuFz97d5hLY-jeIn_A4:b89tvdm) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L23)):*
> ```C
>      * Enumerate minimal set of meminfo stats; as reference workloads that use these stats, we use:
>      *   - Python's psutil library, see source code in `psutil/_pslinux.py`
>      *   - Rust's meminfo, see source code in `procfs/meminfo.rs`
> ```

Would be good to give names of the rust crate and python lib explicitly (`procfs` and `psutil`, I believe), current version suggest like these are paths in Gramine repo. Maybe just links to source code instead of paths?
___
*[LibOS/shim/src/fs/proc/info.c, line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuFzfyg6apy9IDx4Exf:-MuFzfyh47BYhjEx2h8e:b-10hma8) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L28)):*
> ```C
>         const char* fmt;
>         unsigned long val;
>     } meminfo[] = {
> ```

This list is now super lengthy. Could you check if collapsing entries to one row each would look better and change if it does so?
Like this: `{ "MemTotal:      %8lu kB\n", g_pal_public_state->mem_total / 1024, }`, should be readable.
___
*[LibOS/shim/src/fs/proc/info.c, line 43 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG1E9j29NTVFWOS-cN:-MuG1E9k-6q02LS5yzXZ:b-rcs2e9) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L43)):*
> ```C
>         {
>             "Buffers:       %8lu kB\n",
>             /*dummy value=*/0,
> ```

Are you sure it's fine to pass `0` everywhere here? I mean, if something really uses this value, then it's likely to hit div by 0...
Otoh I see that Linux hardcodes `0` for unused fields, so maybe it's fine
___
*[LibOS/shim/src/fs/proc/info.c, line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG0yuJ0G6IrkiqNfM7:-MuG0yuK5u01r8ae4zeu:b-kp5vyv) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L91)):*
> ```C
>         {
>             "Committed_AS:  %8lu kB\n",
>             DkMemoryAvailableQuota() / 1024,
> ```

Why this value (`DkMemoryAvailableQuota()`) is passed both as free and as taken memory? `Committed_AS` vs `MemFree`
___
*[LibOS/shim/src/fs/proc/info.c, line 118 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG2HyI22WDj22zPQX-:-MuG2HyI22WDj22zPQX0:b1oxu7x) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L118)):*
> ```C
>         int ret = snprintf(str + size, max - size, meminfo[i].fmt, meminfo[i].val);
> 
>         if (size + ret >= max)
> ```

Please also add check for `ret < 0`
___
*[LibOS/shim/src/fs/proc/info.c, line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG3XF-CyeSWFGA4b7m:-MuG3XF-CyeSWFGA4b7n:b-3ndg0h) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L169)):*
> ```C
> }
> 
> #define ADD_INFO(fmt, ...)                                            \
> ```

Why did you move this macro? I think it was easier to read it, since it has some hard coded variable names inside, so it's better if it's defined after the variables.

Update: oh, you use the same macro in another function. Idk what to do whit this, it's ugly, but inlining the macro would be even worse...
___
*[LibOS/shim/src/fs/proc/info.c, line 237 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG4bB1B-wNinv5-r4s:-MuG4bB1B-wNinv5-r4t:bmt56ha) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L237)):*
> ```C
>     ADD_INFO("cpu  %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu\n", user, nice, system, idle, iowait,
>              irq, softirq, steal, guest, guest_nice);
>     for (size_t n = 0; n < g_pal_public_state->cpu_info.online_logical_cores; n++) {
> ```

You use `n` as an integer iterator in for loops? I don't want you to change anything here, just genuinely curious :)
___
*[LibOS/shim/src/fs/proc/info.c, line 248 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG4zDqBpl9Rcqajt1X:-MuG4zDqBpl9Rcqajt1Y:b-jadud2) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L248)):*
> ```C
>     ADD_INFO("procs_running %u\n", 1); /* at least this process was created */
>     ADD_INFO("procs_blocked %u\n", 0);
>     ADD_INFO("\n");
> ```

Do we need this empty line? `/proc/stat` doesn't seem to have it
___
*[LibOS/shim/test/regression/proc_stat.c, line 86 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG963L5hvw3fRMDT3b:-MuG963L5hvw3fRMDT3c:b-xbrw69) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L86)):*
> ```C
>     char key[KEYSIZE] = "";
> 
>     if (!memcmp(line, "ctxt", sizeof("ctxt") - 1)) {
> ```

Maybe add a helper function:
```c
static int compare_prefix(const char* line, const char* prefix) {
    return memcmp(line, prefix, strlen(prefix));
}
```

Alternatively you can just `sscanf(line, "ctxt %lu", &val)` and check return value (== 1 matched, otherwise didn't) and return -1 if no prefix matched.

Currently string `"ctxtabcdef 123"` matches. Not a big problem, just saying
___
*[LibOS/shim/test/regression/proc_stat.c, line 126 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6d3y79L8-N4CmmXb:-MuG6d3z2RF-mAa1Yyt7:b1e4aln) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L126)):*
> ```C
>         errx(1, "cannot read 'cpu' line");
> 
>     sscanf(line, "%s %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu\n", cpu, &ps.user, &ps.nice,
> ```

Please check return value (you assume below that it succeeded and populated fields correctly, e.g. `cpu`).
___
*[LibOS/shim/test/regression/proc_stat.c, line 142 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6jms-njvhRZlNvFv:-MuG6jms-njvhRZlNvFw:b1pkb7f) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L142)):*
> ```C
> 
>         init_procstat(&ps);
>         sscanf(line, "%s %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu\n", cpu, &ps.user, &ps.nice,
> ```

ditto (return value)
___
*[LibOS/shim/test/regression/proc_stat.c, line 142 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6r0J5oYvK_nSz41C:-MuG6r0J5oYvK_nSz41D:b26d0bi) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L142)):*
> ```C
> 
>         init_procstat(&ps);
>         sscanf(line, "%s %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu\n", cpu, &ps.user, &ps.nice,
> ```

I think `sscanf(line, "cpu%u ...", &index, ...)` should work too, then you could also verify index
___
*[LibOS/shim/test/regression/proc_stat.c, line 153 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuGAsnYDduA02BXyls1:-MuGAsnYDduA02BXyls2:b-mz2gtn) ([raw file](https://gi [...]

2022-01-26 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 6 of 9 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kvinwang)

___
*[LibOS/shim/src/fs/proc/info.c, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuFz97d5hLY-jeIn_A3:-MuHjvI67zJAZjZEw2BC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Would be good to give names of the rust crate and python lib explicitly (`procfs` and `psutil`, I believe), current version suggest like these are paths in Gramine repo. Maybe just links to source code instead of paths?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/info.c, line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuFzfyg6apy9IDx4Exf:-MuHlU4J3u5Xla7a-UB1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This list is now super lengthy. Could you check if collapsing entries to one row each would look better and change if it does so?
Like this: `{ "MemTotal:      %8lu kB\n", g_pal_public_state->mem_total / 1024, }`, should be readable.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/info.c, line 43 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG1E9j29NTVFWOS-cN:-MuHlWllCbm699WNhHeP:b-wyp2uu) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Are you sure it's fine to pass `0` everywhere here? I mean, if something really uses this value, then it's likely to hit div by 0...
Otoh I see that Linux hardcodes `0` for unused fields, so maybe it's fine
</blockquote></details>

Well, I don't know what else to put here, so...
___
*[LibOS/shim/src/fs/proc/info.c, line 91 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG0yuJ0G6IrkiqNfM7:-MuHld4f6aO3w4yDsgoH:b534m0q) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this value (`DkMemoryAvailableQuota()`) is passed both as free and as taken memory? `Committed_AS` vs `MemFree`
</blockquote></details>

What about now? This value should be closer to the definition of `Committed_AS` ("The  amount of memory presently allocated on the system. The committed memory is a sum of all of the memory which has been allocated by processes, even if it has not been "used" by them as of yet.")
___
*[LibOS/shim/src/fs/proc/info.c, line 118 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG2HyI22WDj22zPQX-:-MuHmIPfBnu977beLjbX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also add check for `ret < 0`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/info.c, line 188 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuHmOCm3bdZ0_PkTAZz:-MuHmOCm3bdZ0_PkTA_-:bqopp7c) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L188)):*
> ```C
>         return -ENOMEM;
> 
>     for (size_t n = 0; n < g_pal_public_state->cpu_info.online_logical_cores; n++) {
> ```

FYI: Borys, I just copy-pasted this code :)
___
*[LibOS/shim/src/fs/proc/info.c, line 237 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG4bB1B-wNinv5-r4s:-MuHmSLg9qalqLaK9Shr:b-nxu4j0) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L237)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You use `n` as an integer iterator in for loops? I don't want you to change anything here, just genuinely curious :)
</blockquote></details>

No, I just copy-pasted the code above, see my other comment :) I prefer `i` but don't care when I copy
___
*[LibOS/shim/src/fs/proc/info.c, line 248 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG4zDqBpl9Rcqajt1X:-MuHmaZSEB4ljEdbB_jA:b1cyhgy) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/src/fs/proc/info.c#L248)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need this empty line? `/proc/stat` doesn't seem to have it
</blockquote></details>

Done. Oops, copied too much from `/proc/cpuinfo` function above.
___
*[LibOS/shim/test/regression/proc_stat.c, line 86 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG963L5hvw3fRMDT3b:-MuKJVuS5CIJOKm7cyeV:bgfdhjl) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe add a helper function:
```c
static int compare_prefix(const char* line, const char* prefix) {
    return memcmp(line, prefix, strlen(prefix));
}
```

Alternatively you can just `sscanf(line, "ctxt %lu", &val)` and check return value (== 1 matched, otherwise didn't) and return -1 if no prefix matched.

Currently string `"ctxtabcdef 123"` matches. Not a big problem, just saying
</blockquote></details>

Done. Fixes both problems.
___
*[LibOS/shim/test/regression/proc_stat.c, line 126 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6d3y79L8-N4CmmXb:-MuKK2-m5r_BlJEmujF8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please check return value (you assume below that it succeeded and populated fields correctly, e.g. `cpu`).
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/proc_stat.c, line 142 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6jms-njvhRZlNvFv:-MuKLqon2E2rQ2MA8-Tw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L142)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (return value)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/proc_stat.c, line 142 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuG6r0J5oYvK_nSz41C:-MuKLrJ91uzR6YKmgZhB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878865c03aff2fd49e5d381f5/LibOS/shim/test/regression/proc_stat.c#L142)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think `sscanf(line, "cpu%u ...", &index, ...)` should work too, then you could also verify index
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/proc_stat.c, line 153 at r4](https://reviewable.io/reviews/gramineproject/gramine/330#-MuGAsnYDduA02BXyls1:-MuKPxfk5hmHotAclWDi:b-u7l98o) ([raw file](https://github.com/gramineproject/gramine/blob/5f727bd89e1c033878 [...]

2022-01-26 14:28 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kvinwang)

___
*[LibOS/shim/src/fs/proc/info.c, line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/330#-MuKtbMN7ibuxSE9B5kf:-MuKtbMN7ibuxSE9B5kg:b-eii1gz) ([raw file](https://github.com/gramineproject/gramine/blob/4601229226f4c9c5681d58312a79b9166d7c2f0a/LibOS/shim/src/fs/proc/info.c#L68)):*
> ```C
>     for (size_t i = 0; i < ARRAY_SIZE(meminfo); i++) {
>         int ret = snprintf(str + size, max - size, meminfo[i].fmt, meminfo[i].val);
>         if (ret < 0)
> ```

`free(str)` missing


<!-- Sent from Reviewable.io -->

2022-01-26 14:56 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kvinwang)



<!-- Sent from Reviewable.io -->

2022-01-26 14:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kvinwang)

___
*[LibOS/shim/src/fs/proc/info.c, line 68 at r5](https://reviewable.io/reviews/gramineproject/gramine/330#-MuKtbMN7ibuxSE9B5kf:-MuLsswZBzjzcj1pVkgo:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/4601229226f4c9c5681d58312a79b9166d7c2f0a/LibOS/shim/src/fs/proc/info.c#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`free(str)` missing
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-01-26 17:44 UTC, dimakuv reviewed
> Dismissed @kvinwang from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: 4 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-01-26 17:52 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/330)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-26 21:13 UTC, merged