[Pal] Support opening TTY devices with O_TRUNC flag
gramineproject/gramine pull request #332
Opened 2022-01-12 10:46 UTC by jkr0103

## Description of the changes 
Write to `/proc/self/fd/2` (which is symlink to /dev/tty) fails with `O_TRUNC` flag which translates to `DkStreamSetLength` as `setlength` function is not implemented for dev:tty devices.

This PR adds dummy function `setlength` to support O_TRUNC flag.

Fixes #303 

## How to test this PR? 

Should be able to execute below commands successfully:
```
gramine-direct busybox sh -c 'echo foo>/proc/self/fd/2'
gramine-sgx busybox sh -c 'echo foo>/proc/self/fd/2'
```
as described in link  https://github.com/gramineproject/gramine/issues/303#issuecomment-1002591818

2022-01-12 13:07 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @pwmarcz)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/332#-MtDOCqh2ZqrBfjEZrMV):*
I think the better commit message will be:
```
[Pal] Add `setlength` callback to PAL device handles

This is required to support opening TTY devices with O_TRUNC flag.
```
___
*[Pal/src/host/Skeleton/db_devices.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/332#-MtDO2Gz7h6o0SFSDX4e:-MtDO2Gz7h6o0SFSDX4f:b-2kxrbb) ([raw file](https://github.com/gramineproject/gramine/blob/022bacd58522940fd08ecc870ffe7268009c477d/Pal/src/host/Skeleton/db_devices.c#L45)):*
> ```C
> /* this dummy function is implemented to support opening TTY devices with O_TRUNC flag */
> static int64_t dev_setlength(PAL_HANDLE handle, uint64_t length) {
>     return 0;
> ```

Because we are in the Skeleton PAL (which doesn't implement even dummy stuff, but instead always returns `-PAL_ERROR_NOTIMPLEMENTED`).

So please replace with `return -PAL_ERROR_NOTIMPLEMENTED`.


<!-- Sent from Reviewable.io -->

2022-01-13 07:01 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/332#-MtDOCqh2ZqrBfjEZrMV):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think the better commit message will be:
```
[Pal] Add `setlength` callback to PAL device handles

This is required to support opening TTY devices with O_TRUNC flag.
```
</blockquote></details>

Done.
___
*[Pal/src/host/Skeleton/db_devices.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/332#-MtDO2Gz7h6o0SFSDX4e:-MtHEWzE9HYQvPVgz-uM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/022bacd58522940fd08ecc870ffe7268009c477d/Pal/src/host/Skeleton/db_devices.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Because we are in the Skeleton PAL (which doesn't implement even dummy stuff, but instead always returns `-PAL_ERROR_NOTIMPLEMENTED`).

So please replace with `return -PAL_ERROR_NOTIMPLEMENTED`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-13 08:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-01-13 08:12 UTC, dimakuv commented
Jenkins, test this please

2022-01-13 08:15 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/332#-MtHVHq5D3zA7u21Alo5:-MtHVHq62Tue_bimiqIt:bz2dvw0) (no related file):*
FYI: I manually verified that this bug fix works on the Busybox example (provided in the "How to test this PR" section). Looks good.

---


<!-- Sent from Reviewable.io -->

2022-01-17 15:28 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jkr0103, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/332#-Mtcdeyo8O0IchbRjvOE:-Mtcdeyo8O0IchbRjvOF:b3soapo) (no related file):*
From `O_TRUNC` description: `If the file is a FIFO or terminal device file, the O_TRUNC flag is ignored.` so the solution should be to ignore this flag for such handle types in LibOS.

---


<!-- Sent from Reviewable.io -->

2022-01-17 15:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/332#-Mtcdeyo8O0IchbRjvOE:-MtcfNpfD9x-2ofkszFv:becvgxn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From `O_TRUNC` description: `If the file is a FIFO or terminal device file, the O_TRUNC flag is ignored.` so the solution should be to ignore this flag for such handle types in LibOS.
</blockquote></details>

Oh wait, the problem is that this is host TTY, not LibOS one

---


<!-- Sent from Reviewable.io -->

2022-01-17 19:10 UTC, boryspoplawski requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103 and @pwmarcz)

___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtdR7ufBaWtlxVFr-3M:bfaqzhw) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
> ```C
>     __UNUSED(handle);
>     __UNUSED(length);
>     return 0;
> ```

Would be good to check if a handle is really a tty and return `-PAL_ERROR_NOTSUPPORT` otherwise.
Also we need to check `length` and return `-PAL_ERROR_INVAL` if it's `!= 0`.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 213 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR6b037wgK5DyAUg8:-MtdR6b037wgK5DyAUg9:b-dfhvcb) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux-SGX/db_devices.c#L213)):*
> ```C
>     __UNUSED(handle);
>     __UNUSED(length);
>     return 0;
> ```

ditto (tty check)


<!-- Sent from Reviewable.io -->

2022-01-18 08:14 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jkr0103, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/332#-Mtcdeyo8O0IchbRjvOE:-MtgEx179uoazQZEesx3:b-dwk0a2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Oh wait, the problem is that this is host TTY, not LibOS one
</blockquote></details>

Yes, it's about behavior of the LibOS created `fd[0]`, `fd[1]`, `fd[2]`.

---
___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtgEV515FaYx747lLHo:b-xsisuu) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Would be good to check if a handle is really a tty and return `-PAL_ERROR_NOTSUPPORT` otherwise.
Also we need to check `length` and return `-PAL_ERROR_INVAL` if it's `!= 0`.
</blockquote></details>

- Looking at the other code in this file, we have "checks if a handle is really a tty" like this:
```
    if (HANDLE_HDR(handle)->type != PAL_TYPE_DEV)
        return -PAL_ERROR_INVAL;
```

(In other words, they return `-PAL_ERROR_INVAL`.)

I suggest to use the same check as in other places in this file.

- I agree with Borys's comment on checking `length`.


<!-- Sent from Reviewable.io -->

2022-01-18 08:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @jkr0103, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/332#-Mtcdeyo8O0IchbRjvOE:-MtgFu0q-eInM-yvlNrq:b-wtvgep) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it's about behavior of the LibOS created `fd[0]`, `fd[1]`, `fd[2]`.
</blockquote></details>

Yeah, I've got completely confused because there was no `tty` inside `dev` emulation file in LibOS. Turns out it's added later via some mounts.

---
___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtgG2en2DvOeeuJatK3:b-l2zhji) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- Looking at the other code in this file, we have "checks if a handle is really a tty" like this:
```
    if (HANDLE_HDR(handle)->type != PAL_TYPE_DEV)
        return -PAL_ERROR_INVAL;
```

(In other words, they return `-PAL_ERROR_INVAL`.)

I suggest to use the same check as in other places in this file.

- I agree with Borys's comment on checking `length`.
</blockquote></details>

Ideally we would check not only if type is `PAL_TYPE_DEV` but also if it's really a `tty`. Probably need to get the uri from handle and compare? Not sure, you need to find the good solution :)


<!-- Sent from Reviewable.io -->

2022-01-18 08:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jkr0103, and @pwmarcz)

___
*[Pal/src/host/Linux/db_devices.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtgISY290PhkzSRjSHa:-MtgISY290PhkzSRjSHb:b-jgj62) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L32)):*
> ```C
>     assert(WITHIN_MASK(options, PAL_OPTION_MASK));
> 
>     PAL_HANDLE hdl = calloc(1, HANDLE_SIZE(dev));
> ```

FYI: @boryspoplawski If you look at this function, you can see that we don't memorize `uri` anywhere. Which is probably a bad thing, but definitely not for this PR.
___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtgIAsT4NlUV1xhp9ic:b-8voh01) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ideally we would check not only if type is `PAL_TYPE_DEV` but also if it's really a `tty`. Probably need to get the uri from handle and compare? Not sure, you need to find the good solution :)
</blockquote></details>

Unfortunately, we don't have a URI or any other "name" field for device handles: https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux/pal_host.h#L64-L67

In my other comment, you can see that we don't even try to memorize the name/uri anywhere upon device-handle creation.


<!-- Sent from Reviewable.io -->

2022-01-18 10:23 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jkr0103, and @pwmarcz)

___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtghAxc9KBvAY9BWln6:b-u6brqv) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
> -PAL_ERROR_INVAL
can we have below check for tty device, I see similar kind of check in same file?
`
    if (handle->dev.fd < 0 || handle->dev.fd > 2)
        return -PAL_ERROR_NOTSUPPORT;
`


<!-- Sent from Reviewable.io -->

2022-01-18 10:35 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @jkr0103, and @pwmarcz)

___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-Mtgk-8QEOfvMNEDlJSC:b-5vqz3d) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

> -PAL_ERROR_INVAL
can we have below check for tty device, I see similar kind of check in same file?
`
    if (handle->dev.fd < 0 || handle->dev.fd > 2)
        return -PAL_ERROR_NOTSUPPORT;
`
</blockquote></details>

Yes, I think we can also add such a check. So I would recommend the following change:
```
    if (HANDLE_HDR(handle)->type != PAL_TYPE_DEV)
        return -PAL_ERROR_INVAL;

    if (!(handle->dev.fd == 0 || handle->dev.fd == 1))
        return -PAL_ERROR_NOTSUPPORT;
```


<!-- Sent from Reviewable.io -->

2022-01-18 11:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/src/host/Linux/db_devices.c, line 203 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR7ufBaWtlxVFr-3L:-MtgsEBO7VZNcgaglKb_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux/db_devices.c#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I think we can also add such a check. So I would recommend the following change:
```
    if (HANDLE_HDR(handle)->type != PAL_TYPE_DEV)
        return -PAL_ERROR_INVAL;

    if (!(handle->dev.fd == 0 || handle->dev.fd == 1))
        return -PAL_ERROR_NOTSUPPORT;
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 213 at r2](https://reviewable.io/reviews/gramineproject/gramine/332#-MtdR6b037wgK5DyAUg8:-MtgsFSC9W_s43IGLWtO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/34cbc11bb583bb8c82b26152d828a402316a8e68/Pal/src/host/Linux-SGX/db_devices.c#L213)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (tty check)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 11:17 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-01-18 11:20 UTC, boryspoplawski commented
Jenkins, test this please

2022-01-18 12:23 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-01-18 12:30 UTC, dimakuv commented
Jenkins, test this please

2022-01-18 13:18 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-01-18 13:34 UTC, merged