[Pal] Unify sanitizing and copying operation of topology information
gramineproject/gramine pull request #339
Opened 2022-01-14 17:30 UTC by vijaydhanraj

## Description of the changes 
As described in the title.

## How to test this PR? 
Please run `sysfs_common` test as part of the LibOS regression test suite.

2022-01-14 17:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/339#-MtOdagvCmSj_UcO8x0o:-MtOdagvCmSj_UcO8x0p:bwuqua4) (no related file):*
To reduce the boilerplate code, @mkow has a few suggestions. We can introduce these as a separate PR if needed by the maintainers.

---


<!-- Sent from Reviewable.io -->

2022-01-15 02:22 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 491 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQLD4c77xHE6d2XyKW:-MtQLD4c77xHE6d2XyKX:bp86zy7) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L491)):*
> ```C
> 
>     /* Extract topology information from untrusted pointer. Note this is only a shallow copy
>      * and we use this a temp variable to do deep copy into `topo_info` struct part of
> ```

`this a temp`

Either "this" or "a".
___
*[Pal/src/host/Linux-SGX/db_main.c, line 545 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQOypZASn8Fx_DQeMp:-MtQOypZASn8Fx_DQeMq:b-p3ugpp) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L545)):*
> ```C
>     }
> 
>     /* TODO: Move at the end along with other trusted copy operation once enable_sysfs_topology
> ```

I'm not sure if I understand this, you mean "_to_ the end" probably?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 553 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQPkGYCCvN92PqFPEh:-MtQPkGZC1RiEiAC69gj:b-yj7ffe) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L553)):*
> ```C
>     g_pal_public_state.topo_info.cpu_to_socket = cpu_to_socket;
> 
>     /* Advance host topology information */
> ```

`Advance` -> `Advanced`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQR9gz313mH9r9rtZ8:-MtQR9gz313mH9r9rtZ9:b-xlmtki) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L561)):*
> ```C
>     cnt = sanitize_hw_resource_count(temp_topo_info.online_logical_cores, /*ordered=*/true);
>     if (cnt < 0 || online_logical_cores_cnt != (size_t)cnt) {
>         log_error("Malformed online cores string from host");
> ```

`string from host` -> `string received from the host` (ditto in other places)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 566 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQRUI9BQWMuagsIvhg:-MtQRUI9BQWMuagsIvhh:brzd11o) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L566)):*
> ```C
> 
>     cnt = sanitize_hw_resource_count(temp_topo_info.possible_logical_cores, /*ordered=*/true);
>     if (cnt < 0 || possible_logical_cores_cnt!= (size_t)cnt) {
> ```

missing space before `!=`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 566 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQRa2-6IEeu-KrEyuT:-MtQRa206Z4-4DO7hLnn:blstlmw) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L566)):*
> ```
> possible_logical_cores_cnt != (size_t)cnt
> ```

I'd actually swap the sides, it's `cnt` which varies and we compare it to the expected value, not the other way. Ditto for other places with `cnt`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 613 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQUpPyAV11Ey3jBoP1:-MtQUpPyAV11Ey3jBoP2:b-klm4ee) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L613)):*
> ```C
> 
>         if (!sgx_copy_to_enclave(cache_info, cache_idx_cnt * sizeof(PAL_CORE_CACHE_INFO),
>                                  temp_topo_info.core_topology[i].cache,
> ```

`temp_topo_info.core_topology` pointer is untrusted, you cannot dereference it
___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-MtQVKnl5X5SJbpjaUDE:b-pmid1s) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
> ```C
> 
>         /* important to bind core_topology with cache_info before sanitize_core_topology_info() */
>         core_topology[i].cache = cache_info;
> ```

For other reviews: This was a bug, only `core_topology[0]` was set before.


<!-- Sent from Reviewable.io -->

2022-01-15 20:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 491 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQLD4c77xHE6d2XyKW:-MtUHo3G2fZoEGxKQhzp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L491)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`this a temp`

Either "this" or "a".
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 545 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQOypZASn8Fx_DQeMp:-MtUHqfqEymRwGOQxsDX:b-1dacbw) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L545)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if I understand this, you mean "_to_ the end" probably?
</blockquote></details>

I meant the end of this function. Basically, wanted to first do all the sanitization and then finally club all the copying operations. Also, changed `at`->`to`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 553 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQPkGYCCvN92PqFPEh:-MtUJ8m_1sWRDPnTzCiL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Advance` -> `Advanced`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 561 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQR9gz313mH9r9rtZ8:-MtUJU778zG5_ls97LZA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L561)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`string from host` -> `string received from the host` (ditto in other places)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 566 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQRUI9BQWMuagsIvhg:-MtUKPVrEEl9am_XoJ7n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L566)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space before `!=`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 566 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQRa2-6IEeu-KrEyuT:-MtUKOJn8hVVsLt4U4KQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L566)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> possible_logical_cores_cnt != (size_t)cnt
> ```

I'd actually swap the sides, it's `cnt` which varies and we compare it to the expected value, not the other way. Ditto for other places with `cnt`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 613 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQUpPyAV11Ey3jBoP1:-MtUKLGlDcLxV26wFIux:blnfmxg) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L613)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`temp_topo_info.core_topology` pointer is untrusted, you cannot dereference it
</blockquote></details>

Got it, done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-MtUKSA92prFklNO4oPe:b-ezre4j) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For other reviews: This was a bug, only `core_topology[0]` was set before.
</blockquote></details>

Yes, found this issue during sysfs refactoring and introduced the fix as part of the unmerged PR #106. Thought we can do this as part of this PR. Should I fix this as a separate PR or add something as part of the commit message?


<!-- Sent from Reviewable.io -->

2022-01-15 22:17 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 613 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQUpPyAV11Ey3jBoP1:-MtUnTRCAy-SgrlccAYl:b-c7ygub) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L613)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, done.
</blockquote></details>

Not done, you still dereference it?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-MtUnZw875rb9C7TEyWr:b62rsqb) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, found this issue during sysfs refactoring and introduced the fix as part of the unmerged PR #106. Thought we can do this as part of this PR. Should I fix this as a separate PR or add something as part of the commit message?
</blockquote></details>

Leave it here, but just mention in the commit message please.
I also found this bug when reviewing the previous sysfs PR, but just decided that we need to implement everything from scratch and didn't write a note about it. I guess I should have, we could easily miss it this time as it's hard to spot.


<!-- Sent from Reviewable.io -->

2022-01-17 01:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 613 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQUpPyAV11Ey3jBoP1:-Mt_NDGvC5nHxf55pkZG:bn3ttle) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L613)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done, you still dereference it?
</blockquote></details>

yes, you are right. Tried the following but again here I deference untrusted `cache` pointer.
```
         PAL_CORE_TOPO_INFO* core_topo_info = temp_topo_info.core_topology + i;
-        if (!sgx_copy_to_enclave(cache_info, cache_idx_cnt * sizeof(PAL_CORE_CACHE_INFO),
-                                 core_topo_info->cache,
+        size_t cache_offset = offsetof(PAL_CORE_TOPO_INFO, cache);
+        PAL_CORE_CACHE_INFO* cache =
+            *((PAL_CORE_CACHE_INFO**)((char*)core_topo_info + cache_offset));
+        if (!sgx_copy_to_enclave(cache_info, cache_idx_cnt * sizeof(PAL_CORE_CACHE_INFO), cache,
                                  cache_idx_cnt * sizeof(PAL_CORE_CACHE_INFO))) {
             log_error("Copying cache_info into the enclave failed");
             return -1;
```

So simply used the shallow pointer `cache` present in the trusted `core_topology` variable to copy the contents.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-Mt_N3bD2lBQfRU7Rbd0:bd11enw) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Leave it here, but just mention in the commit message please.
I also found this bug when reviewing the previous sysfs PR, but just decided that we need to implement everything from scratch and didn't write a note about it. I guess I should have, we could easily miss it this time as it's hard to spot.
</blockquote></details>

Sure, will update the commit message during the final rebase. Have blocked myself.


<!-- Sent from Reviewable.io -->

2022-01-17 08:03 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 485 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaurvY2zeJjxECs2YD:-MtaurvY2zeJjxECs2YE:bnmiw6t) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L485)):*
> ```C
> 
> /* This function doesn't clean up resources on failure: we terminate the process anyway. */
> static int copy_and_sanitize_topo_info(struct pal_topo_info *uptr_topo_info,
> ```

Wrong alignment of asterisk, should be: `struct pal_topo_info* uptr_topo_info`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-MtaxTrCBEJWY7MbaeAa:bmmt99i) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
> ```C
>     }
> 
>     size_t physical_cores_per_socket = temp_topo_info.physical_cores_per_socket;
> ```

These variables should have the suffix `_cnt`, for uniformity with others. Can we rename them in this PR?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 525 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxhAEB0kXU0dbPBDy:-MtaxhAEB0kXU0dbPBDz:b-8jl1v9) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L525)):*
> ```C
> 
>     /* Allocate enclave memory to store "logical core -> socket" mappings */
>     size_t* cpu_to_socket = malloc(online_logical_cores_cnt * sizeof(*cpu_to_socket));
> ```

Now that we have suffix `_cnt` for "number of X" fields, maybe we should also introduce suffix `_arr` for array fields?

I would call this variable `cpu_to_socket_arr` then (and `topo_info.cpu_to_socket_arr` correspondingly).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 545 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxAXO3I8f3ontfZfW:-MtaxAXO3I8f3ontfZfX:bi948mz) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L545)):*
> ```C
>     }
> 
>     /* TODO: Move to the end along with other trusted copy operation once enable_sysfs_topology
> ```

`to the end` -> `to the end of this function`
`operation` -> `operations`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 559 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtayPGDBxEGnQ5TS1tc:-MtayPGDBxEGnQ5TS1td:b-ng24f1) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L559)):*
> ```C
>     }
> 
>     cnt = sanitize_hw_resource_count(temp_topo_info.online_logical_cores, /*ordered=*/true);
> ```

Similarly, I would like to have a suffix here `_str`. So this field will become `temp_topo_info.online_logical_cores_str`.

With these suffixes (`_str`, `_cnt`, `_arr`), I find it much easier to reason about what is trusted (or untrusted and thus needs sanitization) and what is not.

But before @vijaydhanraj starts implementing this change, I want to know @mkow opinion: is it worth it? Or we'll change those fields in the follow-up PRs anyway?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 577 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazBJG81aq_EE0zxeS:-MtazBJH0LE1lWt9yVjD:b4r8owj) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L577)):*
> ```C
>     }
> 
>     cnt = sanitize_hw_resource_count(temp_topo_info.online_nodes, /*ordered=*/true);
> ```

ditto (`_str` suffix)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtazhh24d65eE3JXNFt:-Mtazhh24d65eE3JXNFu:b-dcwp6e) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L583)):*
> ```C
>     }
> 
>     PAL_CORE_TOPO_INFO* core_topology = (PAL_CORE_TOPO_INFO*)malloc(online_logical_cores_cnt *
> ```

`core_topology_arr`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtazl2S8ixeqY2jfTr-:-Mtazl2S8ixeqY2jfTr0:bqdpbvi) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L584)):*
> ```C
> 
>     PAL_CORE_TOPO_INFO* core_topology = (PAL_CORE_TOPO_INFO*)malloc(online_logical_cores_cnt *
>                                                                     sizeof(PAL_CORE_TOPO_INFO));
> ```

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*core_topology)`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 590 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazotMEPpQ-UwCVTNr:-MtazotMEPpQ-UwCVTNs:bqdpbvi) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L590)):*
> ```C
>     }
> 
>     if (!sgx_copy_to_enclave(core_topology, online_logical_cores_cnt * sizeof(PAL_CORE_TOPO_INFO),
> ```

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*core_topology)`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 592 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazpZ37Ws9tlrvuVOe:-MtazpZ37Ws9tlrvuVOf:btx3b6w) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L592)):*
> ```C
>     if (!sgx_copy_to_enclave(core_topology, online_logical_cores_cnt * sizeof(PAL_CORE_TOPO_INFO),
>                              temp_topo_info.core_topology,
>                              online_logical_cores_cnt * sizeof(PAL_CORE_TOPO_INFO))) {
> ```

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*temp_topo_info.core_topology)`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 597 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-8Ox1eQtZCS1-6fm:-Mtb-8Ox1eQtZCS1-6fn:b1o95h5) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L597)):*
> ```C
>     }
> 
>     size_t cache_idx_cnt = temp_topo_info.cache_indices_cnt;
> ```

Why not use the same name as in the field? `cache_idx_cnt` -> `cache_indices_cnt`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 605 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-cNp--BV5GjWBwls:-Mtb-cNp--BV5GjWBwlt:b-hnyo6x) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L605)):*
> ```C
>     /* Copy cache info for each online core */
>     for (size_t i = 0; i < online_logical_cores_cnt; i++) {
>         PAL_CORE_CACHE_INFO* cache_info = (PAL_CORE_CACHE_INFO*)malloc(cache_idx_cnt *
> ```

`cache_info_arr`?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 606 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-Qd32I-iNgcYppnt:-Mtb-Qd32I-iNgcYppnu:b-hqu5ss) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L606)):*
> ```C
>     for (size_t i = 0; i < online_logical_cores_cnt; i++) {
>         PAL_CORE_CACHE_INFO* cache_info = (PAL_CORE_CACHE_INFO*)malloc(cache_idx_cnt *
>                                                                        sizeof(PAL_CORE_CACHE_INFO));
> ```

`sizeof(PAL_CORE_CACHE_INFO)` -> `sizeof(*cache_info)`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 612 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-k1x9PU0ARYJMhhz:-Mtb-k1x9PU0ARYJMhi-:b-wzkndq) [...]

2022-01-17 11:44 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 525 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxhAEB0kXU0dbPBDy:-Mtbi7mFDaj_dO9P610k:b-7eicxk) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L525)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we have suffix `_cnt` for "number of X" fields, maybe we should also introduce suffix `_arr` for array fields?

I would call this variable `cpu_to_socket_arr` then (and `topo_info.cpu_to_socket_arr` correspondingly).
</blockquote></details>

+1 to `_arr` in data structures crossing the trust border, it will make the bugs like the one with cache more visible
___
*[Pal/src/host/Linux-SGX/db_main.c, line 559 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtayPGDBxEGnQ5TS1tc:-MtbiNHk44Womr7uyqJI:b-fig7c0) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L559)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Similarly, I would like to have a suffix here `_str`. So this field will become `temp_topo_info.online_logical_cores_str`.

With these suffixes (`_str`, `_cnt`, `_arr`), I find it much easier to reason about what is trusted (or untrusted and thus needs sanitization) and what is not.

But before @vijaydhanraj starts implementing this change, I want to know @mkow opinion: is it worth it? Or we'll change those fields in the follow-up PRs anyway?
</blockquote></details>

I'd skip `_str`, as we plan to remove all passing via strings here. But +1 to `_arr` (but only for such volatile interfaces).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 621 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb0JcPABOIi5ZGoNCI:-MtblTAu7vt6mToaUw_F:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L621)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, why don't we name the field `cache_info` instead of `cache`? More specifically, `cache_info_arr`.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-01-18 02:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: 0 of 7 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 485 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaurvY2zeJjxECs2YD:-MtdPxmoCtw46Fh65m95:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong alignment of asterisk, should be: `struct pal_topo_info* uptr_topo_info`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-MtdPzNc2eL_u0C0AJP0:b-pkol8w) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These variables should have the suffix `_cnt`, for uniformity with others. Can we rename them in this PR?
</blockquote></details>

It will be confusing if we suffix `_cnt` next to the socket like `physical_cores_per_socket_cnt`. It might be understood as socket count. So have renamed it as `physical_cores_cnt_per_socket`. But this variable is very self-explanatory, and I feel doesn't need the `_cnt` suffix.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 525 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxhAEB0kXU0dbPBDy:-Mtesrh_5-1u00CUNghQ:b-mir0cf) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L525)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to `_arr` in data structures crossing the trust border, it will make the bugs like the one with cache more visible
</blockquote></details>

yes, created a new commit for the naming changes.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 545 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxAXO3I8f3ontfZfW:-MtdSNS34sdapHkQLLS8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L545)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to the end` -> `to the end of this function`
`operation` -> `operations`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 577 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazBJG81aq_EE0zxeS:-Mtet410DqhMtDnB4bJb:b-9x3qf7) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L577)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`_str` suffix)
</blockquote></details>

will be removed, so we can skip
___
*[Pal/src/host/Linux-SGX/db_main.c, line 583 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtazhh24d65eE3JXNFt:-MtetAw0AppzaO7sDKGQ:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L583)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`core_topology_arr`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 584 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtazl2S8ixeqY2jfTr-:-MtdY3sS5du2dr05_RQN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L584)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*core_topology)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 590 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazotMEPpQ-UwCVTNr:-MtdY65h6GEZOgtoYyRU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L590)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*core_topology)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 592 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazpZ37Ws9tlrvuVOe:-MtdUJjn7-RedFfzxU1-:brzbaj1) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L592)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(PAL_CORE_TOPO_INFO)` -> `sizeof(*temp_topo_info.core_topology)`
</blockquote></details>

I think this might cause a buffer overflow if the untrusted `*temp_topo_info.core_topology` is bigger than `*core_topology`. So have used `sizeof(*core_topology)`. Also, we don't want to deference the untrusted pointer, right?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 597 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-8Ox1eQtZCS1-6fm:-MtdV3JCCdIRYLRH_EfS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L597)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not use the same name as in the field? `cache_idx_cnt` -> `cache_indices_cnt`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 605 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-cNp--BV5GjWBwls:-Mtetbi0DvGfdCkFyTNZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L605)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`cache_info_arr`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 606 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-Qd32I-iNgcYppnt:-MtdYKXa8E8Nu9l2aCJ1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L606)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(PAL_CORE_CACHE_INFO)` -> `sizeof(*cache_info)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 612 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-k1x9PU0ARYJMhhz:-MtdW42177o5w90Qshw_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L612)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`is` -> `are`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 613 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-UKhBXkPuNrRVbCT:-MtdW6xACwMSnijWCQVT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L613)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(PAL_CORE_CACHE_INFO)` -> `sizeof(*cache_info)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 615 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-VES0XiQfhi_yLFx:-MtdW8By12PSSGO8trxy:b-pt64m) ([raw file](https:// [...]

2022-01-18 08:07 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/339#-MtgDEiGEuA6cOpPGhF5:-MtgDEiGEuA6cOpPGhF6:b88ik2x) ([raw file](https://github.com/gramineproject/gramine/blob/4e29fa1e1ccb6b15b9428d97ed0af40b4438ac49/Pal/src/host/Linux-common/topo_info.c#L139)):*
> ```C
> 
> static int get_cache_topo_info(size_t cache_indices_cnt, size_t core_idx,
>                                PAL_CORE_CACHE_INFO** cache_info_arr) {
> ```

I would prefer to rename differently:
- func argument to `out_cache_info_arr`
- local variable to `cache_info_arr`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-Mtg9dPdBzZGeHoxWd9Y:b-yu3qvz) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

It will be confusing if we suffix `_cnt` next to the socket like `physical_cores_per_socket_cnt`. It might be understood as socket count. So have renamed it as `physical_cores_cnt_per_socket`. But this variable is very self-explanatory, and I feel doesn't need the `_cnt` suffix.
</blockquote></details>

I don't like both of your proposals. I definitely want a suffix `_cnt` (not somewhere in the middle of the name).

The current name `physical_cores_per_socket` may be interpreted as a two-dimensional array: `physical_cores_per_socket = [ [1,3,5], [2,4,6] ]` -- which cores belong to which socket. In fact, this would be the most logical explanation for this variable name...

But I agree that simply adding a suffix results in `physical_cores_per_socket_cnt`, which may be misunderstood as socket count. What about renaming it to `per_socket_physical_cores_cnt` which reads as "per-socket number of physical cores".
___
*[Pal/src/host/Linux-SGX/db_main.c, line 559 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtayPGDBxEGnQ5TS1tc:-MtgCCEv5gvt8t6vdL4O:b-z94a11) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L559)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd skip `_str`, as we plan to remove all passing via strings here. But +1 to `_arr` (but only for such volatile interfaces).
</blockquote></details>

OK, so we are skipping `_str` but adding `_arr` and `_cnt`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 592 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazpZ37Ws9tlrvuVOe:-MtgCQyo0P5ctyHloTSN:bt5efa2) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L592)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think this might cause a buffer overflow if the untrusted `*temp_topo_info.core_topology` is bigger than `*core_topology`. So have used `sizeof(*core_topology)`. Also, we don't want to deference the untrusted pointer, right?
</blockquote></details>

No, see my explanation above. I still want `sizeof(*temp_topo_info.core_topology)`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 615 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-VES0XiQfhi_yLFx:-MtgCfQc1pnQ_daIv8k5:b2nhky0) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L615)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here the pointer is untrusted and shouldn't be dereferenced. So have used `sizeof(*cache_info)`
</blockquote></details>

No.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 639 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb11Mv1wEviwKSwiCH:-MtgCrBaBvnD1yQNKGiX:b2nhky0) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L639)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

used `sizeof(*numa_topology)` instead of `sizeof(*temp_topo_info.numa_topology)`. Please see earlier comments on the reasoning.
</blockquote></details>

No.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 657 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb2S0d7Bp-ouZfqMxF:-MtgCvva-q1J0fC7riAY:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L657)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

As @mkow mentioned, the plan is to get rid of all the strings in the upcoming PRs, so `_str` can be ignored.
</blockquote></details>

OK.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 535 at r4](https://reviewable.io/reviews/gramineproject/gramine/339#-MtgBhAh-xgWNfkmGueF:-MtgBhAh-xgWNfkmGueG:bdvxdrn) ([raw file](https://github.com/gramineproject/gramine/blob/4e29fa1e1ccb6b15b9428d97ed0af40b4438ac49/Pal/src/host/Linux-SGX/db_main.c#L535)):*
> ```C
>                              online_logical_cores_cnt * sizeof(*cpu_to_socket_arr),
>                              temp_topo_info.cpu_to_socket_arr,
>                              online_logical_cores_cnt * sizeof(*cpu_to_socket_arr))) {
> ```

You don't need to remove `sizeof(*temp_topo_info.cpu_to_socket)`, you can keep it like this.

The asterisk (`*`) inside `sizeof()` is special, it doesn't mean a dereference at runtime. It means "take the pointed-to type to calculate the size". So it is perfectly legal and normal to do here (basically, `sizeof` is a compile-time thing, it never has any runtime consequences).


<!-- Sent from Reviewable.io -->

2022-01-18 13:27 UTC, mkow requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/339#-MtgDEiGEuA6cOpPGhF5:-MtgdfIUEjObDmsXlgrM:b7j5j07) ([raw file](https://github.com/gramineproject/gramine/blob/4e29fa1e1ccb6b15b9428d97ed0af40b4438ac49/Pal/src/host/Linux-common/topo_info.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to rename differently:
- func argument to `out_cache_info_arr`
- local variable to `cache_info_arr`
</blockquote></details>

+1, we definitely can't have both `cache_info_arr` and `cache_info_array` in the same function, it's super confusing
___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-MtgeqWW63zFzj9Fyaxh:b-hjultw) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
> The current name `physical_cores_per_socket` may be interpreted as a two-dimensional array: `physical_cores_per_socket = [ [1,3,5], [2,4,6] ]` -- which cores belong to which socket. In fact, this would be the most logical explanation for this variable name...

Hmm, for me "per" implies the count. If this was a map from socket to cores then it would be `socket_to_physical_cores` (like e.g. `cpy_to_socket` array).

So, I'd rather keep `physical_cores_per_socket`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 592 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazpZ37Ws9tlrvuVOe:-Mtgh1gz07aCVAfA0v42:bicak53) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L592)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, see my explanation above. I still want `sizeof(*temp_topo_info.core_topology)`.
</blockquote></details>

@dimakuv is right, `sizeof` is compile-time. Also, if `sizeof` was running in runtime, then how would it know the real size of `temp_topo_info.core_topology`?


<!-- Sent from Reviewable.io -->

2022-01-18 22:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 139 at r4](https://reviewable.io/reviews/gramineproject/gramine/339#-MtgDEiGEuA6cOpPGhF5:-MtjIuCL0B4EwcId7FJ2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4e29fa1e1ccb6b15b9428d97ed0af40b4438ac49/Pal/src/host/Linux-common/topo_info.c#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, we definitely can't have both `cache_info_arr` and `cache_info_array` in the same function, it's super confusing
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-MtjIwVg1vSDxFQK7RDE:b-ieliro) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The current name `physical_cores_per_socket` may be interpreted as a two-dimensional array: `physical_cores_per_socket = [ [1,3,5], [2,4,6] ]` -- which cores belong to which socket. In fact, this would be the most logical explanation for this variable name...

Hmm, for me "per" implies the count. If this was a map from socket to cores then it would be `socket_to_physical_cores` (like e.g. `cpy_to_socket` array).

So, I'd rather keep `physical_cores_per_socket`.
</blockquote></details>

@dimakuv, is it fine if we leave this variable as is?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 592 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtazpZ37Ws9tlrvuVOe:-MtjJNRf-Q0WnOk6mFHH:bk2ukbs) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L592)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv is right, `sizeof` is compile-time. Also, if `sizeof` was running in runtime, then how would it know the real size of `temp_topo_info.core_topology`?
</blockquote></details>

yes, reverted the change.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 615 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb-VES0XiQfhi_yLFx:-MtjJSCMDdK6LP6nuU5b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L615)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 639 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-Mtb11Mv1wEviwKSwiCH:-MtjJVZC69MqrFkBF_JW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L639)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 535 at r4](https://reviewable.io/reviews/gramineproject/gramine/339#-MtgBhAh-xgWNfkmGueF:-MtjJ8ltE5XdLUU_-IHL:bgu03gi) ([raw file](https://github.com/gramineproject/gramine/blob/4e29fa1e1ccb6b15b9428d97ed0af40b4438ac49/Pal/src/host/Linux-SGX/db_main.c#L535)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need to remove `sizeof(*temp_topo_info.cpu_to_socket)`, you can keep it like this.

The asterisk (`*`) inside `sizeof()` is special, it doesn't mean a dereference at runtime. It means "take the pointed-to type to calculate the size". So it is perfectly legal and normal to do here (basically, `sizeof` is a compile-time thing, it never has any runtime consequences).
</blockquote></details>

Got it, thanks for the clarification. I have reverted the change.


<!-- Sent from Reviewable.io -->

2022-01-18 23:20 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-01-18 23:21 UTC, mkow commented
Jenkins, retest this please

2022-01-19 07:30 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 518 at r3](https://reviewable.io/reviews/gramineproject/gramine/339#-MtaxTrCBEJWY7MbaeA_:-MtlEJ6E6GL7Xntugd9P:b-6ajeua) ([raw file](https://github.com/gramineproject/gramine/blob/35270ee9f32081cf6f89307276e644e35895ee67/Pal/src/host/Linux-SGX/db_main.c#L518)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv, is it fine if we leave this variable as is?
</blockquote></details>

OK, let's keep it as is.


<!-- Sent from Reviewable.io -->

2022-01-19 10:29 UTC, mkow approved these changes
> Reviewed all commit messages.
> Dismissed @vijaydhanraj from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-MtlrUN4E7yE6ee5X3yt:b-lteajw) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure, will update the commit message during the final rebase. Have blocked myself.
</blockquote></details>

Ok, I've done this myself as I was rebasing the PR.


<!-- Sent from Reviewable.io -->

2022-01-19 10:29 UTC, mkow commented
Jenkins, retest this please

2022-01-19 10:53 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-01-19 11:38 UTC, dimakuv approved these changes
> Dismissed @vijaydhanraj from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-01-19 14:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/339)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 620 at r1](https://reviewable.io/reviews/gramineproject/gramine/339#-MtQVKnl5X5SJbpjaUDD:-Mtmg16q5jM9iLsjQELg:b134aby) ([raw file](https://github.com/gramineproject/gramine/blob/4b3affd8bb163dd079cc95328b792fc3e134a6c3/Pal/src/host/Linux-SGX/db_main.c#L620)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I've done this myself as I was rebasing the PR.
</blockquote></details>

Thanks @mkow , appreciate it!


<!-- Sent from Reviewable.io -->

2022-01-20 00:28 UTC, merged