[WIP] epoll
gramineproject/gramine pull request #340
Opened 2022-01-15 01:20 UTC by boryspoplawski

## Description of the changes 

## How to test this PR?

2022-01-15 05:01 UTC, boryspoplawski commented
Jenkins, retest this please

2022-01-24 11:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuArM0W9UiL8StqNT69:-MuArM0W9UiL8StqNT6A:b-7fi2jv) (no related file):*
TODO: add a comprehensive epoll test(s)

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuArOAgDyD-Hfm7jd31:-MuArOAgDyD-Hfm7jd32:b8n0wj8) (no related file):*
TODO: make sure all epoll issues are fixed + grep GH issues for epoll +  add fixes # on GH

---


<!-- Sent from Reviewable.io -->

2022-01-24 14:13 UTC, dimakuv requested changes
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 6 of 7 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
I like this para. But can we add some kind of bullet list after this para, as to how epoll works now (at a very high level), and what are its current limitations?
___
*[LibOS/shim/include/shim_handle.h, line 157 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBC3BEDTXNtHQ4wKUZ:-MuBC3BEDTXNtHQ4wKU_:b-ngprwl) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_handle.h#L157)):*
> ```objc
> DEFINE_LISTP(shim_epoll_waiter);
> struct shim_epoll_handle {
>     struct shim_lock lock;
> ```

Why do we need an additional lock if we already have `shim_handle::lock`? Could you add which fields are protected with this lock, and how is this better than simply using `shim_handle::lock`.

UPDATE: There is an explanation in `struct shim_epoll_item`. Can you make a comment-reference to that struct in `shim_epoll.c`?
___
*[LibOS/shim/include/shim_internal.h, line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBEGO7-oIXuO7mvErC:-MuBEGO7-oIXuO7mvErD:b8pztcv) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L232)):*
> ```objc
> 
> /*!
>  * \brief Wakeup all threads waiting on epolls which \p handle is associated with
> ```

Could you make a separation between epolls (`TYPE_EPOLL` handles) and "handles which are polled" (`TYPE_SOCK`, `TYPE_PIPE`, etc.) more clear in your PR? For example, in this comment it's hard to understand what this `shim_handle` actually is.

Maybe add smth like `For example, if a TYPE_PIPE handle becomes readable, this function must be called.`
___
*[LibOS/shim/include/shim_internal.h, line 234 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBDraqDgjmUpQ7G4lK:-MuBDraqDgjmUpQ7G4lL:b-ye7f2p) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L234)):*
> ```objc
>  * \brief Wakeup all threads waiting on epolls which \p handle is associated with
>  *
>  * \param handle handle to wakup waiters of
> ```

`wakup` -> `wakeup`
___
*[LibOS/shim/include/shim_internal.h, line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBFkxD6MgQAifYWsA_:-MuBFkxD6MgQAifYWsAa:bhw1qzm) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L236)):*
> ```objc
>  * \param handle handle to wakup waiters of
>  */
> void update_epolls(struct shim_handle* handle);
> ```

Shouldn't this be renamed to `wakeup_epolls()`?
___
*[LibOS/shim/include/shim_internal.h, line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBF7qNBv1jhlJjgdPj:-MuBF7qNBv1jhlJjgdPk:brqxhgo) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L238)):*
> ```objc
> void update_epolls(struct shim_handle* handle);
> /*!
>  * \brief Delete all epoll items associated with the pair \p fd and \p handle
> ```

Can you give an example when this function needs to be called?

Also, I guess we cannot use `get_fd_handle()` inside `delete_epoll_items_for_fd()` because this function is called after `fd` is detached? I mean, why can't we drop the second argument (`handle`)?

Do I understand correctly that this function will call `update_epolls()` automatically?
___
*[LibOS/shim/include/shim_internal.h, line 243 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBE2KK8N3o26gP7paM:-MuBE2KK8N3o26gP7paN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L243)):*
> ```objc
>  * \param handle handle which \p fd referred to
>  */
> void delete_epoll_items_for_fd(int fd, struct shim_handle* handle);
> ```

ditto
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 347 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBGevw2LPaX6jzLOAF:-MuBGevxATQZQ0ro3uPB:b-itzo7w) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L347)):*
> ```C
>     }
>     INIT_LISTP(&new_handle->epoll_items);
>     new_handle->epoll_items_count = 0;
> ```

Are you just doing it for sanity? You already have `memset(0)` above.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 746 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBI-QODTanDggtJ-0g:-MuBI-QODTanDggtJ-0h:bsu2hjt) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L746)):*
> ```C
> 
>         INIT_LISTP(&new_hdl->epoll_items);
>         new_hdl->epoll_items_count = 0;
> ```

I guess all these references "epoll handles <-> epoll_items <-> handles" are actually restored in some RS func of `shim_epoll.c`? And here this is more of an initialization for sanity. Maybe add a comment `epoll_items will be restored in RS(...)`?

UPDATE: After taking a glance at checkpoint and restore funcs in `shim_epoll.c`, I'm even more confused. Maybe you could add some top-level comment on the checkpoint-and-restore of epoll items?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 804 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBJTnb5gGKokBGeeNU:-MuBJTnb5gGKokBGeeNV:b-41vcmk) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L804)):*
> ```C
>                 return -ENOMEM;
>             }
>             CP_REBASE(epoll->waiters);
> ```

The child doesn't inherit information on the waiters of epoll?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 42 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBPPq65oCCEqNuzmPs:-MuBPPq65oCCEqNuzmPt:b-mtlcp7) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/sys/shim_epoll.c#L42)):*
> ```C
> DEFINE_LIST(shim_epoll_waiter);
> struct shim_epoll_waiter {
>     LIST_TYPE(shim_epoll_waiter) list;
> ```

`// shim_epoll_handle->waiters` ? Or you didn't add the comment because it's obvious?


<!-- Sent from Reviewable.io -->

2022-01-24 21:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 2 of 7 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like this para. But can we add some kind of bullet list after this para, as to how epoll works now (at a very high level), and what are its current limitations?
</blockquote></details>

It's not very informative, but I've felt weird with just empty commit message body :)
Not sure what details you want to have here, as most interesting parts stem from Linux epoll interface not our implementation details, but maybe something like:
```
Some implementation details:
the most important structure is `shim_epoll_item` which holds one entry on epoll list. Each entry associates some fd
(and LibOS handle referred by that fd) to an epoll instance.
```
Ugh, I don't know what else to put there, without going into low-level details...

I'm not aware of any architectural limitations (i.e. most/all of missing functionality should be implementable with the current design, ignoring any performance issues).
___
*[LibOS/shim/include/shim_handle.h, line 157 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBC3BEDTXNtHQ4wKUZ:-MuC8cPl1MBNgt8hKvWp:b-qy3uc2) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_handle.h#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need an additional lock if we already have `shim_handle::lock`? Could you add which fields are protected with this lock, and how is this better than simply using `shim_handle::lock`.

UPDATE: There is an explanation in `struct shim_epoll_item`. Can you make a comment-reference to that struct in `shim_epoll.c`?
</blockquote></details>

Done.

We do not use `handle->lock` directly, because we cannot take 2 such locks at the same time (which we need for correct implementation). There is a general, but not explicitly written anywhere, assumption that `handle->lock` is "last level" lock, i.e. we should be able to take it holding any other locks.
___
*[LibOS/shim/include/shim_internal.h, line 232 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBEGO7-oIXuO7mvErC:-MuCzkaH9q4zxDeF36cB:b-r3y70g) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you make a separation between epolls (`TYPE_EPOLL` handles) and "handles which are polled" (`TYPE_SOCK`, `TYPE_PIPE`, etc.) more clear in your PR? For example, in this comment it's hard to understand what this `shim_handle` actually is.

Maybe add smth like `For example, if a TYPE_PIPE handle becomes readable, this function must be called.`
</blockquote></details>

Done.
Generally speaking it's: `handle` -> "handle which is polled/added to epoll", `epoll handle`/`epoll` - handle referring to an epoll instance. If such distinction is not held somewhere, then it's a bug (tho I didn't find such place).
___
*[LibOS/shim/include/shim_internal.h, line 234 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBDraqDgjmUpQ7G4lK:-MuCR3Ry3eL0LDquArf9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L234)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`wakup` -> `wakeup`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 236 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBFkxD6MgQAifYWsA_:-MuCxdMxEUaYYK1F-giv:bdyuder) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L236)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be renamed to `wakeup_epolls()`?
</blockquote></details>

True, I guess the old version meant that epoll lists need to be updated, but it's done by the waiters, this function merely wakes them up. I went with `interrupt_epolls` to match `_interrupt_epoll_waiters`
___
*[LibOS/shim/include/shim_internal.h, line 238 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBF7qNBv1jhlJjgdPj:-MuD-LBKAdZA7AuxEBpd:b337v5g) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L238)):*
> Can you give an example when this function needs to be called?

Only example is `detach_fd` - this is the only place it needs to be called.

> Also, I guess we cannot use get_fd_handle() inside delete_epoll_items_for_fd() because this function is called after fd is detached? I mean, why can't we drop the second argument (handle)?

Exactly.

> Do I understand correctly that this function will call update_epolls() automatically?

Yes, though it will just do the same work as `update_epolls` does, not call it directly.
___
*[LibOS/shim/include/shim_internal.h, line 243 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBE2KK8N3o26gP7paM:-MuD-oVbDnAV81UrQkmv:b2ni46t) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

hm?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 347 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBGevw2LPaX6jzLOAF:-MuD00M28HH3s7uKkosX:bkebdr1) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L347)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are you just doing it for sanity? You already have `memset(0)` above.
</blockquote></details>

Well, I've just added a new field, so I've also added the initialization, didn't think about the memset. I can remove it if you want, it's superfluous. 
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 746 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBI-QODTanDggtJ-0g:-MuD0eq6C7LxpKR3_KRE:b-98871n) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L746)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess all these references "epoll handles <-> epoll_items <-> handles" are actually restored in some RS func of `shim_epoll.c`? And here this is more of an initialization for sanity. Maybe add a comment `epoll_items will be restored in RS(...)`?

UPDATE: After taking a glance at checkpoint and restore funcs in `shim_epoll.c`, I'm even more confused. Maybe you could add some top-level comment on the checkpoint-and-restore of epoll items?
</blockquote></details>

No, this initialization is not for sanity, it's required.
We checkpoint `epoll_items` list inside "epoll handle" checkpointing (line 755 in this file) and all items are linked to appropriate `handle->epoll_items` list there. If something is not on that list, then we don't have to checkpoint it (it's a reference to some item that was already deleted from epoll), hence it's never linked into this list.

Added small comment here and in `shim_epoll.c`.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 804 at r2] [...]

2022-01-24 23:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 2 of 7 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-MuDQ0vr4LrWsGCSg7Cq:bg9lqxk) (no related file):*
TODO: sometimes jenkins runs out of PAL memory - need to debug it

---


<!-- Sent from Reviewable.io -->

2022-01-25 10:34 UTC, dimakuv requested changes
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 6 of 7 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not very informative, but I've felt weird with just empty commit message body :)
Not sure what details you want to have here, as most interesting parts stem from Linux epoll interface not our implementation details, but maybe something like:
```
Some implementation details:
the most important structure is `shim_epoll_item` which holds one entry on epoll list. Each entry associates some fd
(and LibOS handle referred by that fd) to an epoll instance.
```
Ugh, I don't know what else to put there, without going into low-level details...

I'm not aware of any architectural limitations (i.e. most/all of missing functionality should be implementable with the current design, ignoring any performance issues).
</blockquote></details>

Maybe just add what you wrote in the comment?
```
In this rework, the most important structure is `shim_epoll_item`
which holds one entry on epoll list. Each entry associates some fd
(and LibOS handle referred by that fd) to an epoll instance.

The implementation closely follows the Linux epoll interface with
its quirks. We are not aware of any architectural limitations imposed
by this implementation (i.e., all currently missing functionality
should be implementable with the current design).
```
___
*[LibOS/shim/include/shim_internal.h, line 243 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBE2KK8N3o26gP7paM:-MuFUY7F4z7738Z8AOqb:bu86akq) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/include/shim_internal.h#L243)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

hm?
</blockquote></details>

I don't know what I meant :)
___
*[LibOS/shim/include/shim_internal.h, line 236 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFUD8_A1JlXNTN9_3v:-MuFUD8_A1JlXNTN9_3w:bxfg40z) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/include/shim_internal.h#L236)):*
> ```objc
>  * \param handle handle to wakeup waiters of
>  *
>  * Currently the only usage of this function is on socket handles thare were just connected (in
> ```

`thare` -> `that`
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 347 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBGevw2LPaX6jzLOAF:-MuFUdzZCt1DgqF1GcDN:b4h7ljz) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L347)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I've just added a new field, so I've also added the initialization, didn't think about the memset. I can remove it if you want, it's superfluous. 
</blockquote></details>

OK, I'm fine with the current code, who cares.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 804 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBJTnb5gGKokBGeeNU:-MuFVZsm2U0oCErqplGt:bgw1c7c) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/bookkeep/shim_handle.c#L804)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would it? These are threads waiting on an epoll, threads are not copied over on fork.
</blockquote></details>

True, got it.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 487 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFhNb9D8dPX5sZo7Zh:-MuFhNb9D8dPX5sZo7Zi:biwpbe7) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/bookkeep/shim_handle.c#L487)):*
> ```C
>     if (!ref_count) {
>         assert(hdl->epoll_items_count == 0);
>         assert(LISTP_EMPTY(&hdl->epoll_items));
> ```

Shouldn't you check the lists `info.epoll.waiters` and `info.epoll.items` if `hdl->type == TYPE_EPOLL`?

If I understand correctly, `info.epoll.items` list must be empty at this point (because this list consists of `shim_epoll_item`s, and they hold a reference on this epoll handle, so this epoll handle cannot be freed until all corresponding `shim_epoll_item`s are removed).

But with `info.epoll.waiters`, I am unsure.

UPDATE: I see that `shim_epoll.c: epoll_close()` does all this, and it is called in here (via `fs_ops->close()` callback). Ok, so we are covered. I'm still fuzzy why `assert(LISTP_EMPTY(&epoll->waiters))` holds though. Isn't it possible that there are some pending waiters on this epoll while it's being removed?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 499 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFjMqWA4FdLmbp3pa-:-MuFjMqXEUzhR-KfhSFh:b89mgk0) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/bookkeep/shim_handle.c#L499)):*
> ```C
>             free(hdl->info.sock.peek_buffer);
>             hdl->info.sock.peek_buffer = NULL;
>         }
> ```

BTW, this logic of freeing the `peek_buffer` shouldn't be here, instead it should have been in `close` or `hput` callback of SOCK handle...
___
*[LibOS/shim/src/sys/shim_epoll.c, line 42 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBPPq65oCCEqNuzmPs:-MuFVv9Y7OA2jxAy6G8A:b-wbif8o) ([raw file](https://github.com/gramineproject/gramine/blob/42f2c6ffa3e4707f2f69bd63effd9879d5e190ed/LibOS/shim/src/sys/shim_epoll.c#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I thought there is no confusion here. Added a comment though. Used `::` to indicate that it's a `struct_type::member` not `variable->struct_member`, idk if such distinction is clear
</blockquote></details>

OK, it's clear to me.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFmqnW8HVA1OSqmlLH:-MuFmqnW8HVA1OSqmlLI:bvdl12x) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L5)):*
> ```C
>  * Copyright (C) 2022 Intel Corporation
>  *                    Borys Popławski <borysp@invisiblethingslab.com>
>  */
> ```

The following diagram helped me in reviewing the code:
```
                                     +-----------------------------+
                                     |                             |
                                     |  shim_epoll_item            |
                                     |                             | item in the interest list of epoll instance
                                     |    epoll_list   +-------------------------------------------------+
 item in the list of epoll instances |                             |     guarded by handle::epoll::lock  |
+---------------------------------------+ handle_list              |                                     |
|    guarded by handle::lock         |                             |                                     |
|                                    |    epoll_handle +-------------+                                   |
|                                    |                             | |                                   |
|                                  v----+ handle                   | +->+----------------------------+   |
|                             [...]

2022-01-25 12:27 UTC, mkow commented
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe just add what you wrote in the comment?
```
In this rework, the most important structure is `shim_epoll_item`
which holds one entry on epoll list. Each entry associates some fd
(and LibOS handle referred by that fd) to an epoll instance.

The implementation closely follows the Linux epoll interface with
its quirks. We are not aware of any architectural limitations imposed
by this implementation (i.e., all currently missing functionality
should be implementable with the current design).
```
</blockquote></details>

@dimakuv: IMO the description of the structures and how they work should rather go to the comments in the code than here.


<!-- Sent from Reviewable.io -->

2022-01-25 12:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 6 of 7 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
> with its quirks.

I didn't say that. There were some that were hard to mimic, but they were also so weird that nothing sane would use them anyway (tho I didn't keep a list of them).
___
*[LibOS/shim/include/shim_internal.h, line 236 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFUD8_A1JlXNTN9_3v:-MuGDAwf-jFdm9NUXdVM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/include/shim_internal.h#L236)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`thare` -> `that`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 487 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFhNb9D8dPX5sZo7Zh:-MuGDQZf1s0sW4bNn53F:b-trij7d) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/bookkeep/shim_handle.c#L487)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you check the lists `info.epoll.waiters` and `info.epoll.items` if `hdl->type == TYPE_EPOLL`?

If I understand correctly, `info.epoll.items` list must be empty at this point (because this list consists of `shim_epoll_item`s, and they hold a reference on this epoll handle, so this epoll handle cannot be freed until all corresponding `shim_epoll_item`s are removed).

But with `info.epoll.waiters`, I am unsure.

UPDATE: I see that `shim_epoll.c: epoll_close()` does all this, and it is called in here (via `fs_ops->close()` callback). Ok, so we are covered. I'm still fuzzy why `assert(LISTP_EMPTY(&epoll->waiters))` holds though. Isn't it possible that there are some pending waiters on this epoll while it's being removed?
</blockquote></details>

If there's a waiter, then it must hold a reference to the epoll handle, so no, it's not possible.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 499 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFjMqWA4FdLmbp3pa-:-MuGDcFh-TJ4GUAVd-M0:bqog80t) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/bookkeep/shim_handle.c#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, this logic of freeing the `peek_buffer` shouldn't be here, instead it should have been in `close` or `hput` callback of SOCK handle...
</blockquote></details>

Agreed
___
*[LibOS/shim/src/sys/shim_epoll.c, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFmqnW8HVA1OSqmlLH:-MuGE1QKEcmP1FOZ-1v_:b3697z7) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The following diagram helped me in reviewing the code:
```
                                     +-----------------------------+
                                     |                             |
                                     |  shim_epoll_item            |
                                     |                             | item in the interest list of epoll instance
                                     |    epoll_list   +-------------------------------------------------+
 item in the list of epoll instances |                             |     guarded by handle::epoll::lock  |
+---------------------------------------+ handle_list              |                                     |
|    guarded by handle::lock         |                             |                                     |
|                                    |    epoll_handle +-------------+                                   |
|                                    |                             | |                                   |
|                                  v----+ handle                   | +->+----------------------------+   |
|                                  | |                             |    |                            |   |
|  +----------------------------+<-+ |    fd                       |    |  shim_handle (epoll)       |   |
|  |                            |    |                             |    |                            |   |
|  |  shim_handle (pipe,sock,..)|    +-----------------------------+    |    epoll_items list        |   |
|  |                            |                                       |                            |   |
+-----> epoll_items list        |        +-------------------------+    |    shim_epoll_handle epoll |   |
   |                            |        |                         |    |                            |   |
   |    lock                    |        |  shim_epoll_waiter      | +--------> waiters list         |   |
   |                            |        |                         | |  |                            |   |
   |                            |        |    list +-----------------+  |       items   list <-----------+
   |                            |        |                         |    |                            |
   +----------------------------+        |    event                |    |       lock                 |
                                         |                         |    |                            |
                                         +-------------------------+    +----------------------------+
```

If you feel it's useful, please add it as the top-level comment. I can also make it slightly more dense, if you want me to do this work.
</blockquote></details>

Wow, nice, added, thanks!
___
*[LibOS/shim/src/sys/shim_epoll.c, line 47 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFeWFa-a5yT-6iyV40:-MuGGn916-0OpL-WG8Dy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment `/* Guarded by `epoll_handle->info.epoll.lock`. */`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 126 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFlYfn9WWT2ASIAe1p:-MuGGwyx5b0OV1XxdEO3:b-7x7dn4) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unrelated to this PR, but I forgot why `|| was_partial` is considered correct.

With edge-triggered (ET) epoll, Gramine must merge all same-type (e.g. EPOLLIN) events until all available data was processed. In other words, if the data was not yet consumed completely by the app, we shouldn't wakeup on epoll_wait.

For example, if `pipe_read()` consumed only half of available data-to-read, there shouldn't be a need for EPOLLIN event. However, in our current code the `pipe_read()` function will call `maybe_epoll_et_trigger(/*was_partial=*/true)`. And so `handle->needs_et_poll_in` is set to true, which will force `epoll_wait()` to wake up its caller. But isn't it contradictory to the definition of ET epoll?

Am I mistaken somewhere? Or maybe we introduced this `was_partial` arg as a relaxation (i.e., it is still technically correct though produces an additional wake up)?
</blockquote></details>

If app sees a partial read, then it knows the [...]

2022-01-25 14:32 UTC, dimakuv requested changes
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 5 of 7 files reviewed, 43 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGBG-j-NNgyr2U8CBj:-MuGBG-j-NNgyr2U8CBk:bqli8ac) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L139)):*
> ```C
> /* Make sure we have an owned reference to `item` when calling this function, as it unlinks `item`
>  * from all lists (hence dropping these references). This means we cannot rely on borrowing
>  * a reference when traversing one of item's lists. */
> ```

I understand the first sentence. But I don't understand the second sentence. What exactly are you trying to say/prevent future devs from doing?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 146 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGCfJi7U4KvwUoUgCb:-MuGCfJi7U4KvwUoUgCc:b-gw6t6o) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L146)):*
> ```C
> 
>     lock(&handle->lock);
>     if (!LIST_EMPTY(item, handle_list)) {
> ```

This check is a protection against a data race, when two threads would try to delete the same fd-handle pair?

I'm asking because I would assume that this func is called only after we checked that the epoll item is registered in some epoll instance, and so it must be removed. Thus, in normal case (without data races) the `item->handle_list` field will always be non-empty, and this check is redundant.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 149 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGDglsCsP1eYOJGKcK:-MuGDglsCsP1eYOJGKcL:by3grck) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L149)):*
> ```C
>         LISTP_DEL_INIT(item, &handle->epoll_items, handle_list);
>         put_epoll_item(item);
>         handle->epoll_items_count--;
> ```

Can you move this line before `put_epoll_item()`? Easier to read.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 153 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGDrEK2KTN_RpownPI:-MuGDrEK2KTN_RpownPJ:b-wumvka) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L153)):*
> ```C
>     unlock(&handle->lock);
> 
>     if (!LIST_EMPTY(item, epoll_list)) {
> ```

Same question -- is this protection against a data race?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 154 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGE2DFBRBhMK4SdZID:-MuGE2DFBRBhMK4SdZIE:b2s26q4) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L154)):*
> ```C
> 
>     if (!LIST_EMPTY(item, epoll_list)) {
>         LISTP_DEL(item, &epoll->items, epoll_list);
> ```

Why not `LISTP_DEL_INIT()` as above? Isn't it a bug -- now another thread may race on this dangling `item->epoll_list`, and the above `if LIST_EMPTY` check will segfault or something.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 161 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGEtIV7iDI-pf5_Hu3:-MuGEtIW27e4Y2xVM5uJ:bg3clah) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L161)):*
> ```C
> 
> /* This should be called once there is no possibility of adding new epoll items with this `fd` and
>  * `handle`. */
> ```

Could you expand a bit on this comment? I guess the only (current) case is when we close the fd (either directly via `close` or indirectly via e.g. `unmap`), right after the actual detouchment of this fd from the handle?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 173 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGFnt9A736ZdlB56Db:-MuGFnt9A736ZdlB56Dc:b9hlj7j) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L173)):*
> ```C
>             if (item->fd == fd) {
>                 to_unlink = item;
>                 get_epoll_item(item);
> ```

Did you forget `break;` here?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 236 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGIMdgCICGumdLbwF5:-MuGIMdgCICGumdLbwF6:bnjbw21) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L236)):*
> ```C
>         }
>         /* We do not support `EPOLLEXCLUSIVE`, but a no-op implementation is correct (although not
>          * the most performant), so we allow for it. */
> ```

Shouldn't we add a TODO comment about this somewhere in this file? Maybe as a top-level comment, like:
```
/*
 * The following epoll features are not yet implemented:
 *   - EPOLLEXCLUSIVE (allowed but ignored, may lead to subpar perf due to the thundering herd problem)
 *   - ...
 */
```
___
*[LibOS/shim/src/sys/shim_epoll.c, line 246 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGIskD4XZDtyQtHYeK:-MuGIskD4XZDtyQtHYeL:b-4a2tpm) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L246)):*
> ```C
>                   "EPOLL_NEEDS_REARM bit occupied by another epoll event");
> 
>     int ret = 0;
> ```

Why `= 0`? I would prefer to remove it, so the compiler can complain if there are bad return paths.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 262 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKQBtBnpq_aj3C7yB:-MuGKQBtBnpq_aj3C7yC:b-hsxl9x) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L262)):*
> ```C
>         /* We do not support `EPOLLET` for eventfd, because our current handling of `EPOLLET` works
>          * only for normal fds (like pipes or sockets). It should be fine to just ignore it - it
>          * should still be correct, just maybe less performant. */
> ```

Is it really fine? Ignoring EPOLLET, at least on pipes and sockets, may lead to hangs -- i.e., incorrect and unexpected-by-app behavior. But I don't know about the details of eventfd functionining (and I don't care now), maybe you are right.

If you're not sure if this is really correct, maybe leave a FIXME/TODO comment?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKvyJEIGfjo7_2tRQ:-MuGKvyJEIGfjo7_2tRR:b-xz49gb) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L273)):*
> ```C
>     struct shim_epoll_item* item;
>     LISTP_FOR_EACH_ENTRY(item, &epoll->items, epoll_list) {
>         if (item->fd == fd && item->handle == handle) {
> ```

Actually, what can it mean if `item->fd == fd` but `item->handle != handle`? Isn't it a bug? Maybe you should check only `fd` and assert on the `handle`?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 318 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGMnl83U1h8IG2ks61:-MuGMnl83U1h8IG2ks62:b-xz49gb) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L318)):*
> ```C
>     struct shim_epoll_item* item;
>     LISTP_FOR_EACH_ENTRY(item, &epoll->items, epoll_list) {
>         if (item->fd == fd && item->handle == handle) {
> ```

Actually, what can it mean if `item->fd == fd` but `item->handle != handle`? Isn't it [...]

2022-01-25 14:39 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 5 of 7 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> with its quirks.

I didn't say that. There were some that were hard to mimic, but they were also so weird that nothing sane would use them anyway (tho I didn't keep a list of them).
</blockquote></details>

Ignore the "quirks" part and drop the description of the struct. See my other comments, I suggest to add some things in the commit message.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 487 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFhNb9D8dPX5sZo7Zh:-MuGeOo_D6zpB9LoskY5:bwkf2jg) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/bookkeep/shim_handle.c#L487)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If there's a waiter, then it must hold a reference to the epoll handle, so no, it's not possible.
</blockquote></details>

Yes, now I see that the waiter is registered during `epoll_wait()`, when the reference on the epoll handle is grabbed. There is another place (in `epoll_close()`) where you could add this comment.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFmqnW8HVA1OSqmlLH:-MuGenM_1ijMEgNUBl1o:bqj90ko) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wow, nice, added, thanks!
</blockquote></details>

You changed the arrow directions in the lists. I find it weird, but ok.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 126 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFlYfn9WWT2ASIAe1p:-MuGf7ge71JyJZxRYx2u:byf31gn) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If app sees a partial read, then it knows there weren't any more data available at the moment. Linux returns all it can (up to the requested size), it does not randomly return half of the data that is available immediately.
Hence after a partial read app may consider this ET event as handled.
</blockquote></details>

Ah, true, my bad. My logic was kinda reversed. Thanks for explanation!


<!-- Sent from Reviewable.io -->

2022-01-25 14:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 5 of 7 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGfNWa8zPnZ1l8CYsi:-MuGfNWa8zPnZ1l8CYsj:bhi8p3g) (no related file):*
Review done. Are you planning any follow ups? In particular, for:
- select and poll reworks (are these even needed?)
- epoll_wait: timeout value update

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGf_A25wUuD7ZlcGNh:-MuGf_A25wUuD7ZlcGNi:bam9xgu) (no related file):*
Any new LTP tests enabled?

---


<!-- Sent from Reviewable.io -->

2022-01-26 13:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 5 of 7 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGfNWa8zPnZ1l8CYsi:-MuHPo_k7lHpXR3CKps6:b-b8oacw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Review done. Are you planning any follow ups? In particular, for:
- select and poll reworks (are these even needed?)
- epoll_wait: timeout value update
</blockquote></details>

select and poll rework - did not plan these, probably needed (as in would be nice to have them), though I've never heard of any real world apps having problems with them

epoll_wait - it's actually not it, but `DkStreamsEventWait` which needs changes - this I would like to do, there is some room for improvement there

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGf_A25wUuD7ZlcGNh:-MuHQIwb6R0D-QMMGRp-:bjuc3sa) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any new LTP tests enabled?
</blockquote></details>

No, there are not many of them and some are disabled due to the c states issue. There is one big epoll test, but parts of it fail due to https://github.com/gramineproject/graphene/issues/1717 (not really an epoll issue) and it takes super long time in Gramine, because it forks ~10k times (so 7s native vs 90s or something like that in Gramine).

I have an TODO item above to add a LibOS/regression test.

---
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ignore the "quirks" part and drop the description of the struct. See my other comments, I suggest to add some things in the commit message.
</blockquote></details>

Hmm, which comments? I've not seen any suggesting things to add in commit msg (only comments in code)
___
*[LibOS/shim/src/sys/shim_epoll.c, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFmqnW8HVA1OSqmlLH:-MuHRhVU1kT2ek0nq8j2:b-ghloxa) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You changed the arrow directions in the lists. I find it weird, but ok.
</blockquote></details>

I've changed them so that the arrow goes from the list head to the list element. I've found it weird that a list element pointed to the list head so I've changed them :) Maybe just remove arrows and use `+` everywhere?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGBG-j-NNgyr2U8CBj:-MuHSogp6osP_qIdNXaf:b-2qc94c) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I understand the first sentence. But I don't understand the second sentence. What exactly are you trying to say/prevent future devs from doing?
</blockquote></details>

Check `do_epoll_del`. There we traverse a list of items and call `_unlink_epoll_item` on one of them. In such scenarios it's common to just call a function on a refcounted object without getting a reference to it, as we kind of borrow the one from the list. If we removed `get_epoll_item` before calling this function and `item` was **not** on any epoll, then unlink from `handle_list` could put the last reference and free `item`, which we would still try to use (e.g. to check if it's linked on an epoll).
Update: now I see the above example kind of makes no sense, as if we came from `do_epoll_del` then this `item` must be linked on some epoll... Anyway, it's cleaner to have such requirement.
Generally my point was when calling this function you should hold a reference to `item`, not just rely on the fact that you somehow got the `item` pointer, so there was some reference to it (because in face this function can drop that reference).
___
*[LibOS/shim/src/sys/shim_epoll.c, line 146 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGCfJi7U4KvwUoUgCb:-MuHUuGr7kBgyllpP9Pv:b-gbm2gm) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This check is a protection against a data race, when two threads would try to delete the same fd-handle pair?

I'm asking because I would assume that this func is called only after we checked that the epoll item is registered in some epoll instance, and so it must be removed. Thus, in normal case (without data races) the `item->handle_list` field will always be non-empty, and this check is redundant.
</blockquote></details>

You could have `close(fd)` and `epoll_ctl(epoll_fd, EPOLL_DEL, fd, ...)` at the same time. Each of these two needs to take locks in different order, so there always might be a race on unlinking, so we have to check.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 149 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGDglsCsP1eYOJGKcK:-MuHW2OzBu2wsSKQEIWs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you move this line before `put_epoll_item()`? Easier to read.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 153 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGDrEK2KTN_RpownPI:-MuHVo6JBVWOtHIBwQef:bvogiv) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same question -- is this protection against a data race?
</blockquote></details>

same answer - yes
___
*[LibOS/shim/src/sys/shim_epoll.c, line 154 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGE2DFBRBhMK4SdZID:-MuHW-N3EMbNhypJZTNW:blvxt0m) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `LISTP_DEL_INIT()` as above? Isn't it a bug -- now another thread may race on this dangling `item->epoll_list`, and the above `if LIST_EMPTY` check will segfault or something.
</blockquote></details>

This code was once inside epoll_del, which did not need this init, but in such generic function it's needed indeed - yes, it's was bug
___
*[LibOS/shim/src/sys/shim_epoll.c, line 161 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGEtIV7iDI-pf5_Hu3:-MuHWWfR3kwoz4nb1YxV:bjsq7wk) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you expand a bit on this comment? I guess the only (current) case is when we close the fd (either directly via `close` or indirectly via e.g. `unmap`), right after the actual detouchment of this fd from the handle?
</blockquote></details>

Not sure what `unmap` has to do with it.
I've moved this comment t [...]

2022-01-26 14:50 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGfNWa8zPnZ1l8CYsi:-MuLdF1n8sFPyRXPgyuf:b-6zqklu) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

select and poll rework - did not plan these, probably needed (as in would be nice to have them), though I've never heard of any real world apps having problems with them

epoll_wait - it's actually not it, but `DkStreamsEventWait` which needs changes - this I would like to do, there is some room for improvement there
</blockquote></details>

Agreed with select and poll reworks -- I also don't remember any issues reported.

epoll_wait timeout -- would be nice to improve it (I assume it's a minor PR), but also really low priority.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGf_A25wUuD7ZlcGNh:-MuLdczY1atPGl27wn5z:b-s74a80) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, there are not many of them and some are disabled due to the c states issue. There is one big epoll test, but parts of it fail due to https://github.com/gramineproject/graphene/issues/1717 (not really an epoll issue) and it takes super long time in Gramine, because it forks ~10k times (so 7s native vs 90s or something like that in Gramine).

I have an TODO item above to add a LibOS/regression test.
</blockquote></details>

OK. Then we need a couple epoll tests in LibOS/regression.

---
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, which comments? I've not seen any suggesting things to add in commit msg (only comments in code)
</blockquote></details>

I meant the text that you put in the `shim_epoll.c` top-level comment. But then, I'm not sure if this duplication makes sense. Feel free to ignore my request.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuFmqnW8HVA1OSqmlLH:-MuLeCE0-2vvWsQzfILu:bgq8bk2) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've changed them so that the arrow goes from the list head to the list element. I've found it weird that a list element pointed to the list head so I've changed them :) Maybe just remove arrows and use `+` everywhere?
</blockquote></details>

Nah, it looks good right now.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGBG-j-NNgyr2U8CBj:-MuLjD947cm7sqi3xuXU:bt3azlx) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L139)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Check `do_epoll_del`. There we traverse a list of items and call `_unlink_epoll_item` on one of them. In such scenarios it's common to just call a function on a refcounted object without getting a reference to it, as we kind of borrow the one from the list. If we removed `get_epoll_item` before calling this function and `item` was **not** on any epoll, then unlink from `handle_list` could put the last reference and free `item`, which we would still try to use (e.g. to check if it's linked on an epoll).
Update: now I see the above example kind of makes no sense, as if we came from `do_epoll_del` then this `item` must be linked on some epoll... Anyway, it's cleaner to have such requirement.
Generally my point was when calling this function you should hold a reference to `item`, not just rely on the fact that you somehow got the `item` pointer, so there was some reference to it (because in face this function can drop that reference).
</blockquote></details>

OK. I feel like this second sentence is redundant, but let's keep it.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 161 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGEtIV7iDI-pf5_Hu3:-MuLjfDDCyFGGb52f0da:bs63nh) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure what `unmap` has to do with it.
I've moved this comment to this function declaration in header.
The only use case is detaching fd from fds map
Let me know what more information should I add (though probably in the header not here).
</blockquote></details>

"was detached from fds map" is what I wanted to see in the comment.

You're right, `unmap` has nothing to do with it. I confused the *file description* (shim handle) that is refcounted on mmap/munmap with the *file descriptor* (fd).
___
*[LibOS/shim/src/sys/shim_epoll.c, line 262 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKQBtBnpq_aj3C7yB:-MuLqNJ37VfGOiSSt33P:b-284ds8) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L262)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How can ignoring EPOLLET lead to a hang?
</blockquote></details>

Ah, I see my confusion. My thought process was reversed: if we wouldn't implement EPOLLET callbacks (that set `need_et_poll_*`) on pipes/sockets, then we could have a hang... Meh, whatever, that was my brainfart.

Anyway, yes, the only problem is that we can wakeup too many threads by ignoring EPOLLET, leading to worse performance.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKvyJEIGfjo7_2tRQ:-MuLkm5e1WkaIVcxtfVE:bsl3ov0) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L273)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`epoll_add(fd)` -> `close(fd)` -> `fd = open/accept/socket` -> `epoll_add(fd)`
</blockquote></details>

I guess you also implied in this example that the preliminary step is `fd = dup(orig_fd)`. Otherwise `close(fd)` would remove the handle with its fd from the `epoll->items` list, and last `epoll_add(fd)` would never hit my questioned case.

But going back to the original question. What actually happens in your scenario in Linux? The second `epoll_add(fd)` succeeds, and the first added `fd` becomes `EBADF`? Do we emulate the same behavior?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 472 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGT-Rk1vr7NaVW0OAa:-MuLmOvi49Ges2xW68Yx:b5zf3ha) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L472)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Are we sure we can club failed allocations like this? 

Yes?

> Wouldn't something bogus happen if the very first malloc() failed, and then we continued to the second malloc(), and this would lead to exploitable bugs in the memory allocator?

Wait, what? Why? How?

</blockquote></details>

Hm, you are right. `malloc()` is supposed to maintain correct state when it returns errors (including `-EN [...]

2022-01-27 13:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/340#-MuBB1Z85fwM9Yhwz0S8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I meant the text that you put in the `shim_epoll.c` top-level comment. But then, I'm not sure if this duplication makes sense. Feel free to ignore my request.
</blockquote></details>

I think the comment in code is enough, commit message is just to let you know what's inside that commit and to help you grep all commits. There is no need for implementation details and in this case I think everything except "epoll was reworked" is an implementation detail...
___
*[LibOS/shim/src/sys/shim_epoll.c, line 146 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGCfJi7U4KvwUoUgCb:-MuLycV92tQvB0crEDLJ:b-rtgd2o) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L146)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You could have `close(fd)` and `epoll_ctl(epoll_fd, EPOLL_DEL, fd, ...)` at the same time. Each of these two needs to take locks in different order, so there always might be a race on unlinking, so we have to check.
</blockquote></details>

Actually currently an item is either on both lists or on none, but I would still leave this distinction.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 262 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKQBtBnpq_aj3C7yB:-MuLzITh9rkgeKmYFlv-:bqmol43) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L262)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I see my confusion. My thought process was reversed: if we wouldn't implement EPOLLET callbacks (that set `need_et_poll_*`) on pipes/sockets, then we could have a hang... Meh, whatever, that was my brainfart.

Anyway, yes, the only problem is that we can wakeup too many threads by ignoring EPOLLET, leading to worse performance.
</blockquote></details>

Actually I think for non-semaphore eventfds EPOLLET makes no sense (i.e. is a no-op). For semaphores I do not see usage either - generally speaking I don't know why would you use EPOLLET and eventfds...
___
*[LibOS/shim/src/sys/shim_epoll.c, line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKvyJEIGfjo7_2tRQ:-MuMJSqO7rX4JtQLtfYJ:b-9tznqs) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L273)):*
> I guess you also implied in this example that the preliminary step is fd = dup(orig_fd). 

Nope, I didn't mean that,  I meant that close + open can happen asynchronously. It turns out that this cannot happen, since we are synchronized by `fds_map->lock`, which is held through all of `delete_epoll_items_for_fd`.

>  What actually happens in your scenario in Linux? 

Noting in particular, everything just works (succeeds).

> The second epoll_add(fd) succeeds, and the first added fd becomes EBADF? Do we emulate the same behavior?

I do not understad, what do you meany by "the first added fd becomes EBADF?"
___
*[LibOS/shim/src/sys/shim_epoll.c, line 491 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGUPT6EN6DWQdslYYo:-MuMNBBy7Ussmgw6AYTt:bj6pq41) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L491)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should still add to the commit message that we added support for such and such flags?
</blockquote></details>

Maybe. What would be the use of it? Only thing I can think of is to grep commit messages, but I think one would grep for "epoll" anyway.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 726 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGde0KChnBC-bOG7yP:-MuLwhZ12XQibx_ccBjD:bntgilk) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L726)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll resolve this comment for now as it is not a problem (only maybe a redundant check).
</blockquote></details>

Ok, so currently an item is either on both lists or none. Since we checkpoint items from an epoll, it must be on `epoll_list` - removed this check.
But I've left the check below - I want to leave the possibility of unlinking an item just from handle list (may come useful one day and currently the only cost is couple of `if (is_empty)`).
___
*[LibOS/shim/src/sys/shim_epoll.c, line 15 at r5](https://reviewable.io/reviews/gramineproject/gramine/340#-MuLeatF9c4H9uA0tEv5:-MuLyL8AA6roR_pKyK9D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5c877e5c868921e4555257fad2396b0f8f3cd86d/LibOS/shim/src/sys/shim_epoll.c#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe rephrase to `cannot add epoll to another epoll instance ...`? Or `adding ... is not supported - ...`. Current version reads weird.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/340#-MuLemqO2UqFMDydn_7P:-MuLyRgVEe_6uyL0w-jG:b-tcpqt6) ([raw file](https://github.com/gramineproject/gramine/blob/5c877e5c868921e4555257fad2396b0f8f3cd86d/LibOS/shim/src/sys/shim_epoll.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `limitation`
</blockquote></details>

Done. Btw somehow you've left this as non-blocking comment.


<!-- Sent from Reviewable.io -->

2022-01-27 13:49 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_epoll.c, line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKvyJEIGfjo7_2tRQ:-MuQi6FWAZBfwZu_WST_:bodtiz6) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L273)):*
Ah, you mean a race between closing the `fd` and opening a new fd (that re-uses the same fd number). Understood now. So the case of `item->fd == fd && item->handle != handle` can happen during this race -- the new fd is already re-used but the epoll item for the old handle (with the same fd number) is not yet deleted.

> I do not understad, what do you meany by "the first added fd becomes EBADF?"

Ignore me, I incorrectly thought that if `fd` is closed but the underlying handle is still used (by some other fd), then this fd will not be detouched from the epoll instance. Which is of course not true.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 491 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGUPT6EN6DWQdslYYo:-MuQlSfL3VZDv-bQAps1:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L491)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe. What would be the use of it? Only thing I can think of is to grep commit messages, but I think one would grep for "epoll" anyway.
</blockquote></details>

OK
___
*[LibOS/shim/src/sys/shim_epoll.c, line 17 at r5](https://reviewable.io/reviews/gramineproject/gramine/340#-MuLemqO2UqFMDydn_7P:-MuQhKMf3-J17ivZ-iWO:b2km23x) ([raw file](https://github.com/gramineproject/gramine/blob/5c877e5c868921e4555257fad2396b0f8f3cd86d/LibOS/shim/src/sys/shim_epoll.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done. Btw somehow you've left this as non-blocking comment.
</blockquote></details>

That's because Reviewable changes it to non-blocking when the sentence starts with `typo`.


<!-- Sent from Reviewable.io -->

2022-01-27 20:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 5 of 15 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuArM0W9UiL8StqNT69:-MuSHSmV-cWcv5SAWytW:baim0c) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: add a comprehensive epoll test(s)
</blockquote></details>

Some tests added, more to come

---
___
*[LibOS/shim/src/sys/shim_epoll.c, line 273 at r3](https://reviewable.io/reviews/gramineproject/gramine/340#-MuGKvyJEIGfjo7_2tRQ:-MuSHcY4CFkrpCJrfEex:b-uhsf5e) ([raw file](https://github.com/gramineproject/gramine/blob/289049776a05480ab4683586eb36079c58d19ec3/LibOS/shim/src/sys/shim_epoll.c#L273)):*
> during this race -- the new fd is already re-used but the epoll item for the old handle (with the same fd number) is not yet deleted.

Yes, though in practice I don't think that can happen in Gramine (due to fds_map lock), but that's out of scope from this file so we shouldn't depend on it.


<!-- Sent from Reviewable.io -->

2022-01-28 09:47 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 173 at r6](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1B261HNLRSb_raBZ:-MuV1B261HNLRSb_raB_:bzckhx5) ([raw file](https://github.com/gramineproject/gramine/blob/77f583c01bba5fae031cd41e54fb78fa6e417ff9/LibOS/shim/src/sys/shim_epoll.c#L173)):*
> ```C
> 
> void maybe_epoll_et_trigger(struct shim_handle* handle, int ret, bool in, bool was_partial) {
>     if (ret == -EAGAIN || ret == -EWOULDBLOCK || was_partial) {
> ```

Why did you remove `EWOULDBLOCK`?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 619 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuUzstK2yixHdjEAsFI:-MuUzstK2yixHdjEAsFJ:btmhx) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/src/sys/shim_epoll.c#L619)):*
> ```C
>         }
> 
>         /* Round robin returned events to help avoid starvation scenarios. If there was
> ```

You introduced this `epoll->last_returned_index` because of `maxevents`, right? Otherwise you could have `epoll_wait(maxevents=1)` on an epoll instance of 10 items, and it would always be the first item reported, and never the later 9 items. Is this a scenario you hit in some real-world workload?
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 75 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1a6iEc_Zvlx3TMVU:-MuV1a6iEc_Zvlx3TMVV:b6lm3ct) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_epollet.c#L75)):*
> ```C
>     if (close(efd) < 0) {
>         err(1, "close");
>     }
> ```

Can you add a newline after this?
___
*[LibOS/shim/test/regression/epoll_test.c, line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1j-SAC-6SQbeZvdw:-MuV1j-SAC-6SQbeZvdx:b-9u3p81) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L8)):*
> ```C
> #include <sys/epoll.h>
> #include <unistd.h>
> #include <stdio.h>
> ```

Not sorted
___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-MuV239p9LhGeoNrdnLn:b-bu5b8f) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
> ```C
>     errx(1, "%d: " msg, __LINE__, ##args)
> 
> #define ARRAY_LEN(arr) (sizeof(arr) / sizeof(arr[0]))
> ```

Can we rename to `ARRAY_SIZE`? This is the macro we have in Gramine, so it would be more uniform (even though it is a separate app).
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-MuV2KWQ0RJnlyVaNNzJ:beilqki) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
> ```C
> 
> static uint64_t wait_event(int epfd, struct epoll_event* possible_events,
>                            size_t possible_events_len) {
> ```

`possible_events_len` -> `possible_events_cnt`
___
*[LibOS/shim/test/regression/epoll_wait_timeout.c, line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV3v8A46c8o1l-yQWE:-MuV3v8BBlKrqly9oYFF:bnm93fq) ([raw file](https://github.com/gramineproject/gramine/blob/51f9eae739d25993c557b650b9d6e77a32a67ad5/LibOS/shim/test/regression/epoll_wait_timeout.c#L124)):*
> ```C
>     }
> 
>     printf("epoll_wait test passed\n");
> ```

So the whole point of this test was to create a listening socket and wait for any incoming connections (which were none)? And not even check that we returned due to the timeout... Amazing. Thanks for deleting it.


<!-- Sent from Reviewable.io -->

2022-01-28 16:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 14 of 17 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 187 at r8](https://reviewable.io/reviews/gramineproject/gramine/340#-MuWTP1gAVd6tJaS08At:-MuWTP1h1ITogSfCB_dC:bugz3sk) ([raw file](https://github.com/gramineproject/gramine/blob/60321f7e28bf12e707f36fae1fe20c4a16ea13ae/LibOS/shim/src/sys/shim_epoll.c#L187)):*
> ```C
>                  * reported by epoll only once, even if there is no read from eventfd.
>                  * To handle such usage pattern, we mark eventfd as read-epollet-pollable on each
>                  * write - we assume that eventfd is not shared between processes.
> ```

Sorry, I don't get the pattern exactly. Could you explain on a particular example? Why on an eventfd write we mark this eventfd as read-pollable? I can't wrap my head around it.


<!-- Sent from Reviewable.io -->

2022-01-30 16:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 14 of 17 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-Mufn6hgECq-7aOqykkZ:b-baif2v) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: sometimes jenkins runs out of PAL memory - need to debug it
</blockquote></details>

The culprit is: https://github.com/gramineproject/gramine/issues/365
This PR creates a pollable event per epoll_wait call, such event consists of two PAL pipes, so we leak two thread structures per epoll_wait.
No idea how to fix it fast... (I'll think about creating a per thread event instead of per epoll_wait call event, that's the only idea I have for a workaround)

---
___
*[LibOS/shim/src/sys/shim_epoll.c, line 173 at r6](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1B261HNLRSb_raBZ:-MuWK15r-H0h2-QtO1Md:b-8ex61o) ([raw file](https://github.com/gramineproject/gramine/blob/77f583c01bba5fae031cd41e54fb78fa6e417ff9/LibOS/shim/src/sys/shim_epoll.c#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove `EWOULDBLOCK`?
</blockquote></details>

It's the same as EAGAIN on Linux (actually on all modern OSes).
___
*[LibOS/shim/src/sys/shim_epoll.c, line 619 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuUzstK2yixHdjEAsFI:-MuWKCXBCFzKRsvZ4vVy:b522cgo) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/src/sys/shim_epoll.c#L619)):*
>  Is this a scenario you hit in some real-world workload?

No, but noticed Linux handles it in such a way and there even is a comment about it in manpages. I've figured it might be something useful to have, especially since it wasn't hard to implement.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 187 at r8](https://reviewable.io/reviews/gramineproject/gramine/340#-MuWTP1gAVd6tJaS08At:-MuX0E8G3VWtB78p3m4d:blfcre7) ([raw file](https://github.com/gramineproject/gramine/blob/60321f7e28bf12e707f36fae1fe20c4a16ea13ae/LibOS/shim/src/sys/shim_epoll.c#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I don't get the pattern exactly. Could you explain on a particular example? Why on an eventfd write we mark this eventfd as read-pollable? I can't wrap my head around it.
</blockquote></details>

Because since we wrote to it, then epoll should return it's readable (there is data to read). Note that eventfd is just one handle (unlike pipe or socket, which have two ends) - we read and write from and to the same handle.
Example usage is:
```
add eventfd to epoll as EPOLLET
T1: start epoll_wait()
T2: write(eventfd, 1)
T1: end epoll_wait() - return eventfd is readable
T1: start epoll_wait() - it goes to sleep, even though eventfd is still readable - thanks to EPOLLET
T2: write(eventfd, 1)
T1: end epoll_wait() - return eventfd is readable
...
```
___
*[LibOS/shim/test/regression/epoll_epollet.c, line 75 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1a6iEc_Zvlx3TMVU:-MuWK_otC5qeWgairwvN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_epollet.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a newline after this?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/epoll_test.c, line 8 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV1j-SAC-6SQbeZvdw:-MuWKdAy00alD65WjhT5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not sorted
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-MuWKeVH60FG6i4Y_BT0:bs29ctd) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to `ARRAY_SIZE`? This is the macro we have in Gramine, so it would be more uniform (even though it is a separate app).
</blockquote></details>

But it's not size of the array, it's length...
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-MuWKidq9maghePHXLX3:bes3v1s) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`possible_events_len` -> `possible_events_cnt`
</blockquote></details>

What's wrong with `len`?
___
*[LibOS/shim/test/regression/epoll_wait_timeout.c, line 124 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV3v8A46c8o1l-yQWE:-MuWKl7b71thT6fJW5XC:b5enye4) ([raw file](https://github.com/gramineproject/gramine/blob/51f9eae739d25993c557b650b9d6e77a32a67ad5/LibOS/shim/test/regression/epoll_wait_timeout.c#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So the whole point of this test was to create a listening socket and wait for any incoming connections (which were none)? And not even check that we returned due to the timeout... Amazing. Thanks for deleting it.
</blockquote></details>

Yeah, it did not really test anything...


<!-- Sent from Reviewable.io -->

2022-01-30 18:56 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 11 of 17 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuArM0W9UiL8StqNT69:-MugL5Mk-KIaD_CwTadr:b1h6v25) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Some tests added, more to come
</blockquote></details>

Done. Not really super comprehensive, but I didn't know what else to test.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuArOAgDyD-Hfm7jd31:-MugLCtIAfsVQfAeEKEs:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: make sure all epoll issues are fixed + grep GH issues for epoll +  add fixes # on GH
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-31 07:53 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-Muj5WFE53gBKGbthTZA:b-b57qdi) (no related file):*
> No idea how to fix it fast... (I'll think about creating a per thread event instead of per epoll_wait call event, that's the only idea I have for a workaround)

I don't like your workaround. And this is a huge problem now, since `epoll_wait()` can be called forever, so sooner or later all Gramine apps will run out of memory due to this leak.

I have an idea to bound this leak in this particular case. I will introduce a list of pending "helper thread structures" (used to create PAL pipes in the SGX case), and I'll add `_DkThreadExit(&list.clear_thread_exit)` here: https://github.com/gramineproject/gramine/blob/c4c88f9bc1db53460774cd8adb07267236cef039/Pal/src/host/Linux-SGX/db_pipes.c#L47?plain=1 instead of `return 0`. This way each helper thread will be marked as definitely exited in this list (when the exit event actually happens).

And we'll run garbage collection on this list every time somewhere around this line: https://github.com/gramineproject/gramine/blob/c4c88f9bc1db53460774cd8adb07267236cef039/Pal/src/host/Linux-SGX/db_pipes.c#L229?plain=1.

This shouldn't be slow because the list is not expected to grow more than 2-3 items at a time.

From what I see, you did a similar trick here: https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/LibOS/shim/src/ipc/shim_ipc_worker.c#L44?plain=1

Let me try to cook this PR real fast.

---
___
*[LibOS/shim/src/sys/shim_epoll.c, line 187 at r8](https://reviewable.io/reviews/gramineproject/gramine/340#-MuWTP1gAVd6tJaS08At:-Muj0AqyExYF4_xtwbOP:bxz597x) ([raw file](https://github.com/gramineproject/gramine/blob/60321f7e28bf12e707f36fae1fe20c4a16ea13ae/LibOS/shim/src/sys/shim_epoll.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because since we wrote to it, then epoll should return it's readable (there is data to read). Note that eventfd is just one handle (unlike pipe or socket, which have two ends) - we read and write from and to the same handle.
Example usage is:
```
add eventfd to epoll as EPOLLET
T1: start epoll_wait()
T2: write(eventfd, 1)
T1: end epoll_wait() - return eventfd is readable
T1: start epoll_wait() - it goes to sleep, even though eventfd is still readable - thanks to EPOLLET
T2: write(eventfd, 1)
T1: end epoll_wait() - return eventfd is readable
...
```
</blockquote></details>

Thanks, now I understand.
___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-Muj0LZi2oDX6YbGfkLN:bpk55na) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it's not size of the array, it's length...
</blockquote></details>

OK, I won't block, but we need to sort this kind of naming with @mkow (for the future, so to write uniform code).
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-Muj0UjJ-pPN4RZinv5B:bpk55na) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's wrong with `len`?
</blockquote></details>

OK, I won't block, but we need to sort this kind of naming with @mkow (for the future, so to write uniform code).


<!-- Sent from Reviewable.io -->

2022-01-31 11:16 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-MujqMWJA659F7r7RZtz:b-fshtbv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> No idea how to fix it fast... (I'll think about creating a per thread event instead of per epoll_wait call event, that's the only idea I have for a workaround)

I don't like your workaround. And this is a huge problem now, since `epoll_wait()` can be called forever, so sooner or later all Gramine apps will run out of memory due to this leak.

I have an idea to bound this leak in this particular case. I will introduce a list of pending "helper thread structures" (used to create PAL pipes in the SGX case), and I'll add `_DkThreadExit(&list.clear_thread_exit)` here: https://github.com/gramineproject/gramine/blob/c4c88f9bc1db53460774cd8adb07267236cef039/Pal/src/host/Linux-SGX/db_pipes.c#L47?plain=1 instead of `return 0`. This way each helper thread will be marked as definitely exited in this list (when the exit event actually happens).

And we'll run garbage collection on this list every time somewhere around this line: https://github.com/gramineproject/gramine/blob/c4c88f9bc1db53460774cd8adb07267236cef039/Pal/src/host/Linux-SGX/db_pipes.c#L229?plain=1.

This shouldn't be slow because the list is not expected to grow more than 2-3 items at a time.

From what I see, you did a similar trick here: https://github.com/gramineproject/gramine/blob/afb79315989557d5ed9f94224563da9a23a1bfaf/LibOS/shim/src/ipc/shim_ipc_worker.c#L44?plain=1

Let me try to cook this PR real fast.
</blockquote></details>

@boryspoplawski I created PR #366 that should fix this problem. Could you please rebase it on top of your epoll PR and check it?

---


<!-- Sent from Reviewable.io -->

2022-01-31 12:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 12 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-Muk0IQo0XqQ-0RwFON4:b-k11egp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I created PR #366 that should fix this problem. Could you please rebase it on top of your epoll PR and check it?
</blockquote></details>

I'll check it out. In the mean time, I've rebased + squashed (since I need to do that for testing anyway)

---
___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-Muk0W214_aKZa9tgysM:bg7r59l) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I won't block, but we need to sort this kind of naming with @mkow (for the future, so to write uniform code).
</blockquote></details>

Don't we already have the convention that `size` means actual size in bytes and `len` means number of objects?
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-Muk0h45Dp0aKJ0QJbeb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I won't block, but we need to sort this kind of naming with @mkow (for the future, so to write uniform code).
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-01-31 12:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-Muk2aq85ONW562csdKC:b-wtpjt4) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we already have the convention that `size` means actual size in bytes and `len` means number of objects?
</blockquote></details>

I don't think so.


<!-- Sent from Reviewable.io -->

2022-01-31 12:46 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/340#-MuDQ0vr4LrWsGCSg7Cp:-Muk9mp21LRPjdbjLjV8:b-o330wr) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll check it out. In the mean time, I've rebased + squashed (since I need to do that for testing anyway)
</blockquote></details>

#366 does fix the problem, thanks.
Keeping this blocked until we rebase on top of it

---


<!-- Sent from Reviewable.io -->

2022-01-31 15:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: 16 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_async.c, line 38 at r11](https://reviewable.io/reviews/gramineproject/gramine/340#-MukkmJR2-BuciQ5wVEN:-MukkmJR2-BuciQ5wVEO:b-hzxksw) ([raw file](https://github.com/gramineproject/gramine/blob/329303900c5bd21796b5c9c5c18c0605f493da40/LibOS/shim/src/shim_async.c#L38)):*
> ```C
> static struct shim_lock async_worker_lock;
> 
> /* TODO: use async_worker_thread->pollable_event instead */
> ```

This turned out to be not easy, this file is weird and needs some work.


<!-- Sent from Reviewable.io -->

2022-01-31 16:06 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-01-31 16:52 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-01-31 18:06 UTC, mkow reviewed
> Reviewed 1 of 10 files at r7, 1 of 4 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-MulCBcC34QoYqLcg8df:b-qaptg8) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think so.
</blockquote></details>

+1 to `ARRAY_LEN` or `ARRAY_CNT`, we use `size` for byte-size.
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-MulCS89EhvenwHReHx1:bxjab3h) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I prefer `_cnt` (e.g. for uniformity), but `_len` is also acceptable for me.


<!-- Sent from Reviewable.io -->

2022-01-31 18:24 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/epoll_test.c, line 21 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV239p9LhGeoNrdnLm:-MulN9_N2rLlquC7v_MA:b-c4ubmx) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to `ARRAY_LEN` or `ARRAY_CNT`, we use `size` for byte-size.
</blockquote></details>

I wouldn't even know what `array count` means...
___
*[LibOS/shim/test/regression/epoll_test.c, line 24 at r7](https://reviewable.io/reviews/gramineproject/gramine/340#-MuV2KWQ0RJnlyVaNNzI:-MulLd6ODdl_u0Fiiy9h:bupu4e8) ([raw file](https://github.com/gramineproject/gramine/blob/79e7a1afecafe20c1a9c6e89d7f27d777a12349c/LibOS/shim/test/regression/epoll_test.c#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer `_cnt` (e.g. for uniformity), but `_len` is also acceptable for me.
</blockquote></details>

I prefer `_len`.
You've changed recently a lot of usages to `_cnt` and still the usages are similar:
```
$ git grep -ho -e '[a-zA-Z0-9_-]*_cnt' | sort | uniq | wc -l
66
$ git grep -ho -e '[a-zA-Z0-9_-]*_len' | sort | uniq | wc -l
60
```
so no idea what uniformity you talk about.


<!-- Sent from Reviewable.io -->

2022-01-31 18:44 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/340)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-01-31 19:20 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 2/5)

2022-01-31 19:47 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 3/5)

2022-01-31 20:19 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 4/5)

2022-01-31 21:15 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 5/5)

2022-01-31 21:45 UTC, merged