[Pal/Linux-SGX] Skip trusted-files verification on mmap past file end
gramineproject/gramine pull request #346
Opened 2022-01-19 13:20 UTC by dimakuv

## Description of the changes 

There was a bug in Gramine-SGX implementation of trusted files: invocation of `mmap(..., <trusted-file-fd>, <offset-past-file-end>)` crashed Gramine process. Such an invocation can happen during checkpoint restore in the child process. This commit fixes this bug by skipping content verification on such mmap and simply returning success.

For my previous failed attempt to fix this bug, see #328 and #336 and #338.

## How to test this PR? 

This bug was found on Python's qiskit package (it led to a segfault on SGX PAL).

This PR adds new LibOS regression test to catch this bug. The test also checks protected-files logic: it was not affected by this bug but we still add such check for future-proofing.

Also see descriptions in #328.

2022-01-19 13:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/test/regression/test_libos.py, line 661 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmWpsK-DETYXPmZAuB:-MtmWpsK-DETYXPmZAuC:bsk7wlk) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/LibOS/shim/test/regression/test_libos.py#L661)):*
> ```Python
>     @unittest.skipUnless(HAS_SGX,
>         'Protected files are only available with SGX')
>     def test_053_mmap_file_backed_protected(self):
> ```

FYI: This test is not really needed, but I added it to prevent future bugs in SGX protected files.

If people think that this is not needed, I'll happily remove this test.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 574 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmX-wC2a_IL_9cGdAU:-MtmX-wC2a_IL_9cGdAV:bx65xr4) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L574)):*
> ```C
>             /* file ended before all mmapped memory was filled -- remaining memory must be zeroed */
>             memset(mem + end, 0, size - end);
>         }
> ```

FYI: We left the not-backed-by-trusted-file-contents part of mmap with garbage, now I fixed this.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 598 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmXBjI6hICYqoUunfC:-MtmXBjI6hICYqoUunfD:bosmboa) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L598)):*
> ```C
>             /* file ended before all mmapped memory was filled -- remaining memory must be zeroed */
>             memset(mem + bytes_read, 0, size - bytes_read);
>         }
> ```

FYI: This is just a cosmetic change, for uniformity with the above code snippet.


<!-- Sent from Reviewable.io -->

2022-01-19 15:27 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmm0UZCImy4Ztjx5Ol):*
This sentence (and commit one liner) sound very dangerous (while PR content isn't). This PR doesn't "skip content verification" - it adds initialization to regions without any content.
___
*[LibOS/shim/test/regression/mmap_file_backed.c, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmwM057u3UIwOJeUy4:-MtmwM057u3UIwOJeUy5:b-cgt1d2) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/LibOS/shim/test/regression/mmap_file_backed.c#L51)):*
> ```C
>      * info and all corresponding memory contents to the child. These VMAs contain two VMAs that
>      * were split from the file-backed mmap above: the first VMA with the lower part (backed by file
>      * contents) and the second VMA with a single page (not backed by file contents).
> ```

NP: first VMA is/may be only partially backed by the file content, i.e. part of one of the pages may be not backed + one whole page may be not backed completely (if `file_size % page_size == 0`)
___
*[LibOS/shim/test/regression/mmap_file_backed.c, line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmwi6_8lD2Jx_5_kzN:-Mtmwi6_8lD2Jx_5_kzO:b3cz9ey) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/LibOS/shim/test/regression/mmap_file_backed.c#L68)):*
> ```C
> 
>         if (!WIFEXITED(st) || WEXITSTATUS(st) != 0)
>             errx(1, "abnormal child termination: %d\n", st);
> ```

no need for the new line
___
*[Pal/src/host/Linux-SGX/db_files.c, line 550 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmnd7Z7Nkfk2K9_sDi:-Mtmnd7Z7Nkfk2K9_sDj:b950cvx) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L550)):*
> ```C
>              * pages (for sanity) and return success */
>             memset(mem, 0, size);
>             return 0;
> ```

Shouldn't we also do `*addr = mem`?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmnfVv4udiZUUGpMJ7:-MtmnfVv4udiZUUGpMJ8:bt006ng) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L551)):*
> ```C
>             memset(mem, 0, size);
>             return 0;
> ```

empty line
___
*[Pal/src/host/Linux-SGX/db_files.c, line 571 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmq_yM5sCitsLcLUjP:-Mtmq_yM5sCitsLcLUjQ:bfp4i5f) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L571)):*
> ```C
>         }
> 
>         if ((off_t)size > end) {
> ```

Shouldn't this be `size > end - offset`?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 573 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmqfLp2nIM6Q_YBufc:-MtmqfLp2nIM6Q_YBufd:b-bf4m4e) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L573)):*
> ```C
>         if ((off_t)size > end) {
>             /* file ended before all mmapped memory was filled -- remaining memory must be zeroed */
>             memset(mem + end, 0, size - end);
> ```

ditto (`end` is offset in file not in memory)


<!-- Sent from Reviewable.io -->

2022-01-20 08:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmm0UZCImy4Ztjx5Ol):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This sentence (and commit one liner) sound very dangerous (while PR content isn't). This PR doesn't "skip content verification" - it adds initialization to regions without any content.
</blockquote></details>

Done. Rebased to fix this.
___
*[LibOS/shim/test/regression/mmap_file_backed.c, line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmwM057u3UIwOJeUy4:-MtqY4qK-SomJKvOoHcz:byqdt4w) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/LibOS/shim/test/regression/mmap_file_backed.c#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: first VMA is/may be only partially backed by the file content, i.e. part of one of the pages may be not backed + one whole page may be not backed completely (if `file_size % page_size == 0`)
</blockquote></details>

Done. I didn't want to go into these details, but I added a small phrase on this.
___
*[LibOS/shim/test/regression/mmap_file_backed.c, line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmwi6_8lD2Jx_5_kzN:-MtqYCiM1o7BMQD6j-3q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/LibOS/shim/test/regression/mmap_file_backed.c#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

no need for the new line
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 550 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmnd7Z7Nkfk2K9_sDi:-MtqZ5Se0mdDPrQMSuQQ:b-qsx7u6) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L550)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we also do `*addr = mem`?
</blockquote></details>

Done. Oops.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 551 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmnfVv4udiZUUGpMJ7:-MtqZRzNEBZS4azkeaRG:bsdspeg) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L551)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

empty line
</blockquote></details>

Done. Looks like I was sleepy yesterday.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 571 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-Mtmq_yM5sCitsLcLUjP:-Mtq_Sg132hImYScgFYq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L571)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `size > end - offset`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 573 at r1](https://reviewable.io/reviews/gramineproject/gramine/346#-MtmqfLp2nIM6Q_YBufc:-Mtq_SzpCb95CjSVebON:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bb87d7a1bcf98ca26b617149c9978a1916ff45e8/Pal/src/host/Linux-SGX/db_files.c#L573)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`end` is offset in file not in memory)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 08:49 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-01-21 00:52 UTC, mkow approved these changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-21 00:55 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-01-21 00:56 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/346)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-21 01:22 UTC, merged