[Pal/Linux-SGX] Disallow rename operation on protected files
gramineproject/gramine pull request #352
Opened 2022-01-20 10:29 UTC by svenkata9

Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>

## Description of the changes 
Disallowing renaming operation on protected files to avoid issues like #345

Fixes #345 (temporarily)

## How to test this PR?

2022-01-20 11:31 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 810 at r1](https://reviewable.io/reviews/gramineproject/gramine/352#-MtrFApQ7In3It5u2Y1m:-MtrFApQ7In3It5u2Y1n:bv3j3ga) ([raw file](https://github.com/gramineproject/gramine/blob/67a187612304410b52c99475ec356be01bebfd95/Pal/src/host/Linux-SGX/db_files.c#L810)):*
> ```C
>     struct protected_file* pf = get_protected_file(handle->file.realpath);
> 
>     if(pf) {
> ```

Please add a space between `if` and `(pf)`
___
*[Pal/src/host/Linux-SGX/db_files.c, line 817 at r1](https://reviewable.io/reviews/gramineproject/gramine/352#-MtrF0uD0ihNvLQ8vcon:-MtrF0uD0ihNvLQ8vcoo:b-nmtqfk) ([raw file](https://github.com/gramineproject/gramine/blob/67a187612304410b52c99475ec356be01bebfd95/Pal/src/host/Linux-SGX/db_files.c#L817)):*
> ```C
>     if (strcmp(type, URI_TYPE_FILE))
>         return -PAL_ERROR_INVAL;
> ```

Could you move your new code here, after `strcmp` check? This looks cleaner: we first check that the type is indeed a FILE type, and then we check if this file is a protected file.


<!-- Sent from Reviewable.io -->

2022-01-21 06:46 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 810 at r1](https://reviewable.io/reviews/gramineproject/gramine/352#-MtrFApQ7In3It5u2Y1m:-MtvNBbBAOTHWeIugmxt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/67a187612304410b52c99475ec356be01bebfd95/Pal/src/host/Linux-SGX/db_files.c#L810)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space between `if` and `(pf)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 817 at r1](https://reviewable.io/reviews/gramineproject/gramine/352#-MtrF0uD0ihNvLQ8vcon:-MtvNEFpBiHlvTKMNUJf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/67a187612304410b52c99475ec356be01bebfd95/Pal/src/host/Linux-SGX/db_files.c#L817)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move your new code here, after `strcmp` check? This looks cleaner: we first check that the type is indeed a FILE type, and then we check if this file is a protected file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 08:07 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-21 08:07 UTC, dimakuv commented
Jenkins, test this please

2022-01-21 11:57 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-25 17:11 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-01-25 19:24 UTC, mkow commented
Jenkins, retest this please

2022-01-25 19:24 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/352)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-25 22:08 UTC, merged