[LibOS] Add support for temporary changing of signal mask by syscalls
gramineproject/gramine pull request #354
Opened 2022-01-20 17:30 UTC by boryspoplawski

## Description of the changes 
This is used by e.g. `sigsuspend`, `pselect` and `ppoll`. Note that `epoll_pwait` is not changed, since it will be reworked in a follow up PR.

2022-01-20 19:22 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/354#-Mtsrx61EKYVyJp70z1y:-Mtsrx6258CTXlWb51rH:b-qfgwgp) (no related file):*
Any LTPs which could be enabled now?

---
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 589 at r1](https://reviewable.io/reviews/gramineproject/gramine/354#-MtssY-x-AGjpCW1kNCz:-MtssY-y2p6WtV7W6c6I:b-4bubra) ([raw file](https://github.com/gramineproject/gramine/blob/f1f607e4c658c3bd000feb06612386a1e1216738/LibOS/shim/src/bookkeep/shim_signal.c#L589)):*
> ```C
>     lock(&current->lock);
>     current->saved_sigmask = current->signal_mask;
>     current->has_saved_sigmask = true;
> ```

Could you assert here that `current->has_saved_sigmask` is false?


<!-- Sent from Reviewable.io -->

2022-01-20 20:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/354#-Mtsrx61EKYVyJp70z1y:-Mtt7GCH9NHQa54PUzZy:b311x94) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any LTPs which could be enabled now?
</blockquote></details>

Nope. Most of the related tests that are yet not on are blocked due to the C state issue

---
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 589 at r1](https://reviewable.io/reviews/gramineproject/gramine/354#-MtssY-x-AGjpCW1kNCz:-Mtt7PjlEE1WNHAULkYl:b-695dwt) ([raw file](https://github.com/gramineproject/gramine/blob/f1f607e4c658c3bd000feb06612386a1e1216738/LibOS/shim/src/bookkeep/shim_signal.c#L589)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you assert here that `current->has_saved_sigmask` is false?
</blockquote></details>

But why? There is no such requirement (tho it's true)


<!-- Sent from Reviewable.io -->

2022-01-20 23:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 589 at r1](https://reviewable.io/reviews/gramineproject/gramine/354#-MtssY-x-AGjpCW1kNCz:-MtttgwX8VxFlAkRGs12:b-ilnrtb) ([raw file](https://github.com/gramineproject/gramine/blob/f1f607e4c658c3bd000feb06612386a1e1216738/LibOS/shim/src/bookkeep/shim_signal.c#L589)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But why? There is no such requirement (tho it's true)
</blockquote></details>

Wouldn't this be a bug if you saved the mask twice when handling some syscall? It would erase the original mask then. But maybe I don't understand fully how this works.


<!-- Sent from Reviewable.io -->

2022-01-21 01:29 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-21 11:58 UTC, dimakuv requested changes
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_thread.h, line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtvpJ00DCiEgf0U1XK9:-MtvpJ00DCiEgf0U1XKA:b-qhbr8x) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/include/shim_thread.h#L93)):*
> ```objc
>     __sigset_t signal_mask;
>     __sigset_t saved_sigmask; // old mask; accessible only by the current thread
>     bool has_saved_sigmask; // true if the above mask was set and needs to be restored
> ```

NP: Can we use `/* */` for comments, and also align them?
___
*[LibOS/shim/src/shim_syscalls.c, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwKOD36UnEGDKn8fg6:-MtwKOD36UnEGDKn8fg7:bafsusv) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/shim_syscalls.c#L70)):*
> ```C
>         unlock(&current->lock);
>         current->has_saved_sigmask = false;
>     }
> ```

Do I understand the logic correctly here, on the example of `ppoll()`:

- Syscall will execute with updated sigmask (argument to `ppoll`).

- If a non-blocked signal arrived during syscall, then `handle_signal()` will set up the sigframe such that the app sighandler will execute with signalmask `sa->sa_mask` and upon app sighandler return the sigmask will be reset to `current->saved_sigmask` (which is the sigmask before syscall execution). The code snippet in here will not be executed (because `current->has_saved_sigmask == false`).

- If there was no non-blocked signal during syscall, then the code snippet in here will be executed, and we will return from syscall with the sigmask reset to `current->saved_sigmask` (which is the sigmask before syscall execution).

Is my understanding correct? I believe your changes are correct, just want to understand the flows better.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 567 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwHDue9Mu7njd1g2kN:-MtwHDue9Mu7njd1g2kO:braim37) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/bookkeep/shim_signal.c#L567)):*
> ```C
>     assert(set);
>     assert(locked(&thread->lock));
>     assert(thread == get_cur_thread() || !thread->pal_handle);
> ```

When does this happen when `!thread->pal_handle` ?
___
*[LibOS/shim/src/sys/shim_poll.c, line 206 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwI389Btc1Lflx1AWW:-MtwI389Btc1Lflx1AWX:bxqdabp) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/sys/shim_poll.c#L206)):*
> ```C
> 
> long shim_do_poll(struct pollfd* fds, unsigned int nfds, int timeout_ms) {
>     if (!is_user_memory_writable(fds, sizeof(*fds) * nfds))
> ```

NP: Could you flip to `nfds * sizeof(*fds)`, for uniformity.


<!-- Sent from Reviewable.io -->

2022-01-22 02:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: 7 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_thread.h, line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtvpJ00DCiEgf0U1XK9:-MtzZukPDoQe7pzACfsl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/include/shim_thread.h#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

NP: Can we use `/* */` for comments, and also align them?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_syscalls.c, line 70 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwKOD36UnEGDKn8fg6:-Mtz_5Ip6_35FFhjUgk5:b-u68agb) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/shim_syscalls.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do I understand the logic correctly here, on the example of `ppoll()`:

- Syscall will execute with updated sigmask (argument to `ppoll`).

- If a non-blocked signal arrived during syscall, then `handle_signal()` will set up the sigframe such that the app sighandler will execute with signalmask `sa->sa_mask` and upon app sighandler return the sigmask will be reset to `current->saved_sigmask` (which is the sigmask before syscall execution). The code snippet in here will not be executed (because `current->has_saved_sigmask == false`).

- If there was no non-blocked signal during syscall, then the code snippet in here will be executed, and we will return from syscall with the sigmask reset to `current->saved_sigmask` (which is the sigmask before syscall execution).

Is my understanding correct? I believe your changes are correct, just want to understand the flows better.
</blockquote></details>

correctamundo
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 589 at r1](https://reviewable.io/reviews/gramineproject/gramine/354#-MtssY-x-AGjpCW1kNCz:-Mtz_SWU3fiy7-A1skHF:b-6g8t36) ([raw file](https://github.com/gramineproject/gramine/blob/f1f607e4c658c3bd000feb06612386a1e1216738/LibOS/shim/src/bookkeep/shim_signal.c#L589)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't this be a bug if you saved the mask twice when handling some syscall? It would erase the original mask then. But maybe I don't understand fully how this works.
</blockquote></details>

I guess it would be
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 567 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwHDue9Mu7njd1g2kN:-Mtz_Ha35MsXamAz4jlQ:b-9vwzs5) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/bookkeep/shim_signal.c#L567)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When does this happen when `!thread->pal_handle` ?
</blockquote></details>

In thread initialization, when the struct is created, but the thread is not yet spawned (and hence there is no `pal_handle`)
___
*[LibOS/shim/src/sys/shim_poll.c, line 206 at r2](https://reviewable.io/reviews/gramineproject/gramine/354#-MtwI389Btc1Lflx1AWW:-Mtz_a7O82_9HURC8mgU:b-i06mr1) ([raw file](https://github.com/gramineproject/gramine/blob/b083f20fcf8b8656bcbfec7df7ab9a9335fe44bb/LibOS/shim/src/sys/shim_poll.c#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

NP: Could you flip to `nfds * sizeof(*fds)`, for uniformity.
</blockquote></details>

I didn't want to change much in poll, this file needs more attention, but done.


<!-- Sent from Reviewable.io -->

2022-01-22 12:53 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-01-22 16:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-01-22 16:24 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-01-22 17:03 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/354)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-22 17:07 UTC, merged