Refactor sysfs to improve sanitization
gramineproject/gramine pull request #355
Opened 2022-01-22 05:15 UTC by vijaydhanraj

## Description of the changes 
This PR refactors sysfs to improve sanitization. It fixes issues 1, 2 listed as part of gramineproject/graphene#2105.

This supersedes PR #106 and I have closed the PR.

## How to test this PR? 
Please run `sysfs_common` and `proc_common` regression tests. Also, `openvino` benchmark using the TBB library can be used to validate the changes.

2022-01-22 14:16 UTC, mkow commented
Jenkins, test this please

2022-01-22 15:15 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-Mu1LIdhEVqkDHVFBXWx:-Mu1LIdiAADjdJubbZWh:bchclqj) (no related file):*
From AddressSanitizer:

```
[LibOS.shim.test.regression.test_libos.TC_40_FileSystem.test_040_sysfs]

error: asan: heap-buffer-overflow while trying to store 8 bytes at 0xf766cb8
error: asan: the bad address is 0xf766cb8 (0 from beginning of access)
error: asan: location: create_socket_range_from_core at db_main.c, libpal.so+0x1149bd
error: asan: (for a full traceback, use GDB with a breakpoint at "pal_abort")
error: asan:
error: asan: shadow bytes around the bad address:
error: asan:   0x18001eecd50: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd60: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd70: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan: =>0x18001eecd90: fa fa 00 00 fa fa 00[fa]fa fa fa fa fa fa fa fa
error: asan:   0x18001eecda0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:
error: asan: shadow byte legend (1 shadow byte = 8 application bytes):
error: asan:           addressable: 00
error: asan: partially addressable: 01..07
error: asan:     heap left redzone: fa
error: asan:     freed heap region: fd
error: asan:    stack left redzone: f1
error: asan:     stack mid redzone: f2
error: asan:   stack right redzone: f3
error: asan:     stack after scope: f8
error: asan:   alloca left redzone: ca
error: asan:  alloca right redzone: cb
error: asan:        global redzone: f9
error: asan:         user-poisoned: f7
```

---


<!-- Sent from Reviewable.io -->

2022-01-23 01:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-Mu1LIdhEVqkDHVFBXWx:-Mu3WHWYBdcJsqOstp88:bxvnub2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

From AddressSanitizer:

```
[LibOS.shim.test.regression.test_libos.TC_40_FileSystem.test_040_sysfs]

error: asan: heap-buffer-overflow while trying to store 8 bytes at 0xf766cb8
error: asan: the bad address is 0xf766cb8 (0 from beginning of access)
error: asan: location: create_socket_range_from_core at db_main.c, libpal.so+0x1149bd
error: asan: (for a full traceback, use GDB with a breakpoint at "pal_abort")
error: asan:
error: asan: shadow bytes around the bad address:
error: asan:   0x18001eecd50: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd60: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd70: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan:   0x18001eecd80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
error: asan: =>0x18001eecd90: fa fa 00 00 fa fa 00[fa]fa fa fa fa fa fa fa fa
error: asan:   0x18001eecda0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:   0x18001eecdd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
error: asan:
error: asan: shadow byte legend (1 shadow byte = 8 application bytes):
error: asan:           addressable: 00
error: asan: partially addressable: 01..07
error: asan:     heap left redzone: fa
error: asan:     freed heap region: fd
error: asan:    stack left redzone: f1
error: asan:     stack mid redzone: f2
error: asan:   stack right redzone: f3
error: asan:     stack after scope: f8
error: asan:   alloca left redzone: ca
error: asan:  alloca right redzone: cb
error: asan:        global redzone: f9
error: asan:         user-poisoned: f7
```
</blockquote></details>

Thanks, @mkow. Can you please tell me how to reproduce this locally?

I tried the following:
```
1. export CC=clang-9 CXX=clang++-9 AS=clang-9
2. meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Dsgx_driver=upstream -Dsgx_driver_include_path="" -Dtests=enabled -Ddcap=enabled -Dasan=enabled
```

This results in the error below,
```
LibOS/shim/test/regression/meson.build:176:8: ERROR: Problem encountered: Compiling tests is currently unsupported with Musl and compilers other than GCC. You need to either disable Musl (-Dmusl=disabled) or use GCC (CC=gcc)
```

So as suggested in the error, added `-Dmusl=disabled`

```
meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Dsgx_driver=upstream -Dsgx_driver_include_path="" -Dtests=enabled -Ddcap=enabled -Dasan=enabled -Dmusl=disabled
```

This worked fine but `ninja -C build/` failed with the following error,
```
ninja: build stopped: subcommand failed.
```

Also, I see messages like these in the log,
```
[34/721] Compiling C object Pal/regression/Pie.p/Pie.c.o
FAILED: Pal/regression/Pie.p/Pie.c.o 
clang-9 -IPal/regression/Pie.p -IPal/regression -I../Pal/regression -I../Pal/include/pal -I../Pal/include/arch/x86_64 -I../Pal/include/arch/x86_64/Linux -Icommon/include -I../common/include -I../common/include/arch/x86_64 -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O0 -g -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wnull-dereference -DDEBUG -fPIE -fsanitize=address -fno-sanitize-link-runtime -mllvm -asan-mapping-offset=0x18000000000 -DASAN -mllvm -asan-use-after-return=0 -fno-stack-protector -fno-builtin -nostdlib -Wno-unused-parameter -fPIE -MD -MQ Pal/regression/Pie.p/Pie.c.o -MF Pal/regression/Pie.p/Pie.c.o.d -o Pal/regression/Pie.p/Pie.c.o -c ../Pal/regression/Pie.c
clang: error: unknown argument: '-fno-sanitize-link-runtime'
```

---


<!-- Sent from Reviewable.io -->

2022-01-23 01:47 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-Mu1LIdhEVqkDHVFBXWx:-Mu3aubDDtO9PZkf7SvP:b-pxaxos) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, @mkow. Can you please tell me how to reproduce this locally?

I tried the following:
```
1. export CC=clang-9 CXX=clang++-9 AS=clang-9
2. meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Dsgx_driver=upstream -Dsgx_driver_include_path="" -Dtests=enabled -Ddcap=enabled -Dasan=enabled
```

This results in the error below,
```
LibOS/shim/test/regression/meson.build:176:8: ERROR: Problem encountered: Compiling tests is currently unsupported with Musl and compilers other than GCC. You need to either disable Musl (-Dmusl=disabled) or use GCC (CC=gcc)
```

So as suggested in the error, added `-Dmusl=disabled`

```
meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Dsgx_driver=upstream -Dsgx_driver_include_path="" -Dtests=enabled -Ddcap=enabled -Dasan=enabled -Dmusl=disabled
```

This worked fine but `ninja -C build/` failed with the following error,
```
ninja: build stopped: subcommand failed.
```

Also, I see messages like these in the log,
```
[34/721] Compiling C object Pal/regression/Pie.p/Pie.c.o
FAILED: Pal/regression/Pie.p/Pie.c.o 
clang-9 -IPal/regression/Pie.p -IPal/regression -I../Pal/regression -I../Pal/include/pal -I../Pal/include/arch/x86_64 -I../Pal/include/arch/x86_64/Linux -Icommon/include -I../common/include -I../common/include/arch/x86_64 -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O0 -g -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wnull-dereference -DDEBUG -fPIE -fsanitize=address -fno-sanitize-link-runtime -mllvm -asan-mapping-offset=0x18000000000 -DASAN -mllvm -asan-use-after-return=0 -fno-stack-protector -fno-builtin -nostdlib -Wno-unused-parameter -fPIE -MD -MQ Pal/regression/Pie.p/Pie.c.o -MF Pal/regression/Pie.p/Pie.c.o.d -o Pal/regression/Pie.p/Pie.c.o -c ../Pal/regression/Pie.c
clang: error: unknown argument: '-fno-sanitize-link-runtime'
```

</blockquote></details>

I think the below should fix the issue, but want to test with both `ASan` and `UBSan` before pushing the changes.
```
diff --git a/Pal/src/host/Linux-SGX/db_main.c b/Pal/src/host/Linux-SGX/db_main.c
index dc41346f..144a69f5 100644
--- a/Pal/src/host/Linux-SGX/db_main.c
+++ b/Pal/src/host/Linux-SGX/db_main.c
@@ -372,8 +372,8 @@ static int create_socket_range_from_core(struct pal_res_range_info* socket_info_
 
     if (socket_id != prev_socket_id) {
         socket_info_arr[socket_id].range_cnt++;
-        size_t new_size = sizeof(new_size) * socket_info_arr[socket_id].range_cnt;
-        size_t old_size = new_size - sizeof(old_size);
+        size_t new_size = sizeof(struct pal_range_info) * socket_info_arr[socket_id].range_cnt;
+        size_t old_size = new_size - sizeof(struct pal_range_info);
         struct pal_range_info* tmp = malloc(new_size);
         if (!tmp)
             return -1;
``` 

---


<!-- Sent from Reviewable.io -->

2022-01-23 11:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-Mu1LIdhEVqkDHVFBXWx:-Mu5iroa7x8nU3DnR3kl:bemu0ai) (no related file):*
> ```
> clang: error: unknown argument: '-fno-sanitize-link-runtime'
> ```

Try clang10, yours is probably too old and doesn't support this flag yet.

---


<!-- Sent from Reviewable.io -->

2022-01-24 03:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-Mu1LIdhEVqkDHVFBXWx:-Mu93g6LBjJjl0Iju4F0:b-tdq17c) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> clang: error: unknown argument: '-fno-sanitize-link-runtime'
> ```

Try clang10, yours is probably too old and doesn't support this flag yet.
</blockquote></details>

Thanks, installed `clang-12` and was able to repro the issue. Tested with the above patch and it resolves the issue.

---


<!-- Sent from Reviewable.io -->

2022-01-24 08:13 UTC, dimakuv commented
Jenkins, test this please

2022-01-24 12:35 UTC, dimakuv requested changes
> Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 124 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABLtm1JGUK3Oi2B1o):*
`Linux_SGX` -> `Linux-SGX`
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABQ1ODBusPYlZuBDK):*
`...unify` -> `...and unify`
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABTzX1QxaA2lM6K-M):*
`PAL` -> `PALs`
___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABdxV6LQnP2_JUmfa):*
Actually, I would just remove this sentence and immediately start with 1., 2., 3.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADzx9ER7zz1vFxI-T:-MuADzx9ER7zz1vFxI-U:bci2r3a) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
> ```objc
> /* Converts an integer to a string, optionally appending a given single-letter unit suffix
>  * (see enum size_multiplier for possible values).
>  * Note: This function adds a newline at end of the string. */
> ```

`at the end`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuACnr_DuR3XMmFb7Ta:-MuACnr_DuR3XMmFb7Tb:b-5r4mjz) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
> ```objc
>  * Note: This function adds a newline at end of the string. */
> int sys_convert_int_to_sizestr(size_t val, enum size_multiplier size_mult, char* str,
>                                size_t buf_size);
> ```

We have inconsistency in naming: `str` and `buf_size`. I suggest to replace `str` -> `buf`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADvlQ0ceZuHOGVHdt:-MuADvlQ0ceZuHOGVHdu:bci2r3a) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
> ```objc
> /* Converts struct pal_res_range_info to a string representation.
>  * Example output when sep == ',': "10-63,68,70-127".
>  * Note: This function adds a newline at end of the string. */
> ```

`at the end`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADDFUC7YN3tFtyASz:-MuADDFUC7YN3tFtyAT-:bkjkscp) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
> ```objc
>  * Note: This function adds a newline at end of the string. */
> int sys_convert_ranges_to_str(const struct pal_res_range_info* resource_range_info, char* str,
>                               size_t buf_size, const char* sep);
> ```

ditto (`buf`)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADGajAaVlnQ8QgRP2:-MuADGajAaVlnQ8QgRP3:b-i9q70t) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
> ```objc
>  * Note: This function adds a newline at end of the string. */
> int sys_convert_ranges_to_str(const struct pal_res_range_info* resource_range_info, char* str,
>                               size_t buf_size, const char* sep);
> ```

Can we move `sep` before `str` and `buf_size` (to become a second argument, not the last one)?

This is more easy on the eyes: we will have two input arguments first, and then two arguments refering to the buffer.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADyl-5RpXqB286yDH:-MuADyl-5RpXqB286yDI:bci2r3a) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L227)):*
> ```objc
>  * on the possible cores count in the system.
>  * Example output for 64 cores in total and ranges 0-15,48-55: "00ff0000,0000ffff".
>  * Note: This function adds a newline at end of the string. */
> ```

`at the end`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 229 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADFZZ3_R2sb6bnvaQ:-MuADFZZ3_R2sb6bnvaR:bkjkscp) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L229)):*
> ```objc
>  * Note: This function adds a newline at end of the string. */
> int sys_convert_ranges_to_cpu_bitmap_str(const struct pal_res_range_info* resource_range_info, char* str,
>                                          size_t buf_size);
> ```

ditto (`buf`)
___
*[LibOS/shim/src/fs/proc/info.c, line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAEY5S9cSNVHT4pCno:-MuAEY5T-x5NOfXlnSdI:b-lx9btg) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/proc/info.c#L129)):*
> ```C
>         if (g_pal_public_state->enable_sysfs_topology) {
>             ADD_INFO("physical id\t: %zu\n", ti->core_topology_arr[i].socket_id);
>         }
> ```

Can we have an `else` clause? It is very unexpected that if sysfs is disabled, then there will be no `physical id` string at all.

Maybe simply `ADD_INFO("physical id\t: %zu\n", 0);` is good enough for now (i.e., we have only one socket)?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 35 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAQlmXAeKFvNXamC70:-MuAQlmXAeKFvNXamC71:bki78ew) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/sys/cache_info.c#L35)):*
> ```C
>         ret = sys_convert_ranges_to_cpu_bitmap_str(&cache_info->shared_cpu_map, str, sizeof(str));
>     } else if (strcmp(name, "level") == 0) {
>         ret = sys_convert_int_to_sizestr(cache_info->level, MULTIPLIER_NONE, str, sizeof(str));
> ```

Why do you use your special function here, instead of a simple:
```
    ret = snprintf(str, sizeof(str), "%zu\n", cache_info->level);
```

Same for the below cases (coherency line size, number of sets, ...)
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAR6gB126jZ5Qz7h1X:-MuAR6gB126jZ5Qz7h1Y:b-eq14ug) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/sys/cache_info.c#L39)):*
> ```C
>         switch (cache_info->type) {
>             case CACHE_TYPE_DATA:
>                 ret = snprintf(str, sizeof(str), "%s", "Data\n");
> ```

`\n` is typically added to the format string, so please change to this:
```
    ret = snprintf(str, sizeof(str), "%s\n", "Data");
```

Same for the below two cases.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAVvkB1d7T-cxZt5cZ:-MuAVvkB1d7T-cxZt5c_:bb4e5p4) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/sys/cache_info.c#L67)):*
> ```C
> 
>     if (ret < 0)
>         return ret;
> ```

Please add an empty line after this, a bit hard to read otherwise
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAVugOC0FKWbc_0xkw:-MuAVugOC0FKWbc_0xkx:bb4e5p4) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf [...]

2022-01-24 12:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 125 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 181 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuA_11a0KEfcBGB6YQz:-MuA_11a0KEfcBGB6YR-:b-9pr5f) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/src/host/Linux-common/topo_info.c#L181)):*
> ```C
>     for (size_t i = 0; i < res_info->range_cnt; i++) {
>         if (res_info[i].ranges_arr)
>             free(res_info[i].ranges_arr);
> ```

??? How can this work? Instead of this for loop, it should be simply:
```
    if (res_info->ranges_arr)
        free(res_info->ranges_arr);
```


<!-- Sent from Reviewable.io -->

2022-01-24 16:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 125 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuBn5lTBk8EVDROvEta:b-gdto6p) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
Migrating the discussion from https://github.com/gramineproject/gramine/pull/106 again:

@mkow:

> Why does this multiplier even exists? Wasn't the idea that what host passes should be as simple and normalized as possible? Why not just pass the number of bytes everywhere and just in that int->str function shorten it if it's divisible by some size unit? (for specific rounding rules please check the kernel source)
> 
> With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".
> 
> And another problem: what if the untrusted host gives you `LONG_MAX` gigabytes? I think in some places you'll just pass it to the app without erroring out, because you never needed to multiply it, so there was no chance for overflow detection (which will certainly happen in the user app then).

@vijaydhanraj:

> > Why does this multiplier even exists?
> 
> We have a multiplier because we exactly need to know how the normal kernel is representing the strings. For example, on reading `/sys/devices/system/cpu/cpu2/cache/index3/size` we get `49152K`. Now this can be represented as `48M` or `49152K` and in this case, kernel chose the latter representation, and we need to give the same to the end-user.
> 
> > With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".
> 
> Please see the earlier comment.
> 
> > And another problem: what if the untrusted host gives you `LONG_MAX` gigabytes?
> 
> Please see here (lines 263-267) https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R263, I do multiply the size qualifier and check the limits when sanitizing so we shouldn't be running into overflow issues in this case. If you see the issue somewhere, please point me to it.

@mkow:

> And finally my next reply: (i.e. from this review iteration)
> 
> > in this case, kernel chose the latter representation
> 
> The problem is that it's the untrusted kernel (or actually just host, not necessarily kernel) which chose these. We can't rely on it choosing proper specifiers.
> 
> > https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R263
> 
> This link doesn't work (or at least is not pointing me to any particular place in the PR).

@vijaydhanraj:

> > The problem is that it's the untrusted kernel (or actually just host, not necessarily kernel) which chose these. We can't rely on it choosing proper specifiers.
> 
> yes agree, that is why we take the values passed by the untrusted host and then run a sanitization check on it. This way we can ensure that the untrusted host is not passing garbage or malicious value and maintain the representation as the host.
> 
> > This link doesn't work (or at least is not pointing me to any particular place in the PR).
> Please see here, https://github.com/gramineproject/gramine/pull/106/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R259, lines 259-262

@mkow:

> > yes agree, that is why we take the values passed by the untrusted host and then run a sanitization check on it. This way we can ensure that the untrusted host is not passing garbage or malicious value and maintain the representation as the host.
> 
> But as I said, you aren't sanitizing the unit, e.g. `1000000000K` passes the current sanitization if I'm not mistaken.
> 
> > Please see here, https://github.com/gramineproject/gramine/pull/106/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R259, lines 259-262
> 
> Same, this links to the whole PR diff for me. Can you just give me the filename and the line in current revision?

[end of old quotes]

I still think we should normalize the data and just pass a single number instead of number + unit. The unit is untrusted, so you can't say that we need to follow the host kernel - we don't know what the host kernel really emits.


<!-- Sent from Reviewable.io -->

2022-01-25 00:40 UTC, mkow requested changes
> Reviewed 2 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 128 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuDexfA267TAGLqYpVT:bx9qs1y) (no related file):*
@vijaydhanraj Could you move the first two commits into a separate PR? They are trivial and we should be able do merge them quickly.

---
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDalBkDqDyi_mEs1h3):*
`direcly` -> `directly`
___
*[-- commits, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDbuOk0VO1Oq3s0qtJ):*
I'd change this description, the whole idea of this change is not just to pass integers instead of strings, but to use more normalized and clean representation of the topology data on the trusted<->untrusted boundary, so that we can reason about its correctness easier.


<!-- Sent from Reviewable.io -->

2022-01-25 18:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuHMF111JPKhfWLH8iH:bdktj8) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vijaydhanraj Could you move the first two commits into a separate PR? They are trivial and we should be able do merge them quickly.
</blockquote></details>

Sure @mkow, I will create a new PR with those 2 commits. I will remove those commits from this PR before final rebase. There are lot of discussions here and so don't want to force push.

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABLtm1JGUK3Oi2B1o):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Linux_SGX` -> `Linux-SGX`
</blockquote></details>

Blocked myself. Will do this as part of the final rebase.
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABQ1ODBusPYlZuBDK):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...unify` -> `...and unify`
</blockquote></details>

Blocked myself. Will do this as part of the final rebase.
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABTzX1QxaA2lM6K-M):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`PAL` -> `PALs`
</blockquote></details>

Blocked myself. Will do this as part of the final rebase.
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDalBkDqDyi_mEs1h3):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`direcly` -> `directly`
</blockquote></details>

Blocked myself. Will do this as part of the final rebase.
___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABdxV6LQnP2_JUmfa):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I would just remove this sentence and immediately start with 1., 2., 3.
</blockquote></details>

Blocked myself. Will do this as part of the final rebase.
___
*[-- commits, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDbuOk0VO1Oq3s0qtJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd change this description, the whole idea of this change is not just to pass integers instead of strings, but to use more normalized and clean representation of the topology data on the trusted<->untrusted boundary, so that we can reason about its correctness easier.
</blockquote></details>

How about the following? 
```
This commit creates a clean representation of topology data on the trusted<->untrusted boundary, so that we can easily verify its correctness. The following are done:
        1. Refactor sysfs code to convert CPU/NUMA information from
           Linux-formatted strings to integers in untrusted PAL.
        2. Copy and sanitize CPU/NUMA information based on untrusted
           integers to trusted PAL.
        3. Convert the trusted CPU/NUMA information from integers back
           to Linux-formatted strings in LibOS.
```
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADzx9ER7zz1vFxI-T:-MuCn3cD3GlsbAdKtVOW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`at the end`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuACnr_DuR3XMmFb7Ta:-MuCo9vY0YVY-cKSkQ3A:b4f2nu9) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have inconsistency in naming: `str` and `buf_size`. I suggest to replace `str` -> `buf`.
</blockquote></details>

I think it will be better to change `buf_size` -> `str_size` as it seems to fit with the function names. So have changed it this way. This will also align with what we had discussed before regarding the naming of the char buffers.

Let me know if you want to revert it to `buf` and `buf_size`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 220 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADvlQ0ceZuHOGVHdt:-MuCpKWN49kvlB0LaOF1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`at the end`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADDFUC7YN3tFtyASz:-MuCpNBT7qPfWlbN7j5X:b-h5oyu1) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`buf`)
</blockquote></details>

Done, but renamed `buf_size` -> `str_size`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADGajAaVlnQ8QgRP2:-MuCshaq9GhBMl8pRenQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we move `sep` before `str` and `buf_size` (to become a second argument, not the last one)?

This is more easy on the eyes: we will have two input arguments first, and then two arguments refering to the buffer.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADyl-5RpXqB286yDH:-MuCsihuDgEbwwwFX6u3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`at the end`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 229 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuADFZZ3_R2sb6bnvaQ:-MuCslLBCT4wTJPZk-wK:b-yopm0t) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`buf`)
</blockquote></details>

Done, but renamed `buf_size` -> `str_size`.
___
*[LibOS/shim/src/fs/proc/info.c, line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAEY5S9cSNVHT4pCno:-MuCtSXL9IL_zSQVINMp:b-gpkb0x) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/proc/info.c#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we have an `else` clause? It is very unexpected that if sysfs is disabled, then there will be no `physical id` string at all.

Maybe simply `ADD_INFO("physical id\t: %zu\n" [...]

2022-01-25 19:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 13 of 21 files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuHeXUq7qADKXfjA3TT:b-2bylzb) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure @mkow, I will create a new PR with those 2 commits. I will remove those commits from this PR before final rebase. There are lot of discussions here and so don't want to force push.
</blockquote></details>

Pulled out the first 2 commits and created https://github.com/gramineproject/gramine/pull/360

---


<!-- Sent from Reviewable.io -->

2022-01-25 20:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 13 of 21 files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABLtm1JGUK3Oi2B1o):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocked myself. Will do this as part of the final rebase.
</blockquote></details>

Done as part of PR 360 
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABQ1ODBusPYlZuBDK):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocked myself. Will do this as part of the final rebase.
</blockquote></details>

Done as part of PR 360 
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuABTzX1QxaA2lM6K-M):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocked myself. Will do this as part of the final rebase.
</blockquote></details>

Done as part of PR 360 
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDalBkDqDyi_mEs1h3):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocked myself. Will do this as part of the final rebase.
</blockquote></details>

Done as part of PR 360 


<!-- Sent from Reviewable.io -->

2022-01-25 22:47 UTC, mkow commented
___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuIP9C1ED8Na3xorKgu:b-a7g7cs) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
> why do you say only the unit is untrusted? Even the value is untrusted right?

By unit I mean "in which unit we'll display this value to the user". And the unstrusted host may select some impossible combinations, like the ones I already listed in this very conversation.

> Also, for cache size, the expectation of the application will be a value followed by unit. By normalizing we are changing this format.

I don't want you to change the format in sysfs for the app, but to change the format on the untrusted interface.


<!-- Sent from Reviewable.io -->

2022-01-26 00:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 13 of 21 files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuIjWHm4sLpdQzobljt:b-ln5itz) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
> But as I said, you aren't sanitizing the unit, e.g. 1000000000K passes the current sanitization if I'm not mistaken

So, this is the problem. And to address this you are suggesting removing the size multiplier and keeping the value. For example, if the value was `4K` you want to store as `4096`in the untrusted PAL. Copy to it trusted PAL and run sanitization on this and when application queries this value, LibOS will change `4096` to `4K` format.

Is my understanding correct?


<!-- Sent from Reviewable.io -->

2022-01-26 00:35 UTC, mkow commented
___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuInWYa5dXRKzryXlwH:btih660) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> But as I said, you aren't sanitizing the unit, e.g. 1000000000K passes the current sanitization if I'm not mistaken

So, this is the problem. And to address this you are suggesting removing the size multiplier and keeping the value. For example, if the value was `4K` you want to store as `4096`in the untrusted PAL. Copy to it trusted PAL and run sanitization on this and when application queries this value, LibOS will change `4096` to `4K` format.

Is my understanding correct?
</blockquote></details>

Yes, exactly.


<!-- Sent from Reviewable.io -->

2022-01-26 01:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 13 of 21 files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuIreyO1hyHrWFKJBjD:b-k8rml9) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, exactly.
</blockquote></details>

Got it. So currently I store `4` and `K` that I read from untrusted PAL. But in the trusted PAL, I first check if the multiplier is such `K` is valid. Then I multiply the value which is 4 times `K` and then check we don't end with huge numbers like as you have pointed in your example. If the multiplied value (4096) is within range, I keep the value and the size multiplier else I throw an error. 

Please see the below logic
```
        size_t multiplier = 1;
        if (cache_info_arr[lvl].size_multiplier == MULTIPLIER_KB)
            multiplier = 1024;
        else if (cache_info_arr[lvl].size_multiplier == MULTIPLIER_MB)
            multiplier = 1024 * 1024;
        else if (cache_info_arr[lvl].size_multiplier == MULTIPLIER_GB)
            multiplier = 1024 * 1024 * 1024;

        size_t cache_size;
        if (__builtin_mul_overflow(cache_info_arr[lvl].size, multiplier, &cache_size))
            return -1;

        if (!IS_IN_RANGE_INCL(cache_size, 1, 1 << 30))
            return -1;
```


<!-- Sent from Reviewable.io -->

2022-01-26 01:05 UTC, mkow commented
___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuIu-SFB9UOMh26EUO_:b-3sct47) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
> Got it. So currently I store `4` and `K` [...]

Yes, you currently do it differently, that's why we have this whole discussion. What's your point/question?


<!-- Sent from Reviewable.io -->

2022-01-26 07:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 13 of 21 files reviewed, 127 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuKBS1P1YvmW6B5mh-Q:b-t41314) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Got it. So currently I store `4` and `K` [...]

Yes, you currently do it differently, that's why we have this whole discussion. What's your point/question?
</blockquote></details>

It turns out that Linux kernel always displays cache size in terms of KB. This makes things simpler for us and we can remove the `size qualifier`. As suggested by @mkow, cache size is sanitized after multiplying with 1024 and when the application requests, LibOS converts the value to `xK` format.

Please see here, https://elixir.bootlin.com/linux/v5.13/source/drivers/base/cacheinfo.c#L380
and https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu

```
size:
			the total cache size in kB
```


<!-- Sent from Reviewable.io -->

2022-01-26 10:21 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 29 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuACnr_DuR3XMmFb7Ta:-MuKaG0I-8KtLxHhCaNz:b-yag5tb) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think it will be better to change `buf_size` -> `str_size` as it seems to fit with the function names. So have changed it this way. This will also align with what we had discussed before regarding the naming of the char buffers.

Let me know if you want to revert it to `buf` and `buf_size`.
</blockquote></details>

Ok, I'm fine with `str_size` of course. Just wanted consistency in naming.
___
*[LibOS/shim/src/fs/proc/info.c, line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAEY5S9cSNVHT4pCno:-MuKaaTj1fju7ST4smfc:bcpphxf) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/proc/info.c#L129)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This will be incorrect as most servers have more than 1 socket. We anyway only print a selected few values. So, unless an application is failing, or we are breaking something in Gramine, I wouldn't suggest adding a dummy value. 
</blockquote></details>

OK, I see your point. Hopefully we'll remove this `enable_sysfs_topology` soon anyway.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuBn5lS3hHbG6D34ou6:-MuKc62c8dD7jA0P7A34:b43o50e) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L27)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

It turns out that Linux kernel always displays cache size in terms of KB. This makes things simpler for us and we can remove the `size qualifier`. As suggested by @mkow, cache size is sanitized after multiplying with 1024 and when the application requests, LibOS converts the value to `xK` format.

Please see here, https://elixir.bootlin.com/linux/v5.13/source/drivers/base/cacheinfo.c#L380
and https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu

```
size:
			the total cache size in kB
```


</blockquote></details>

LGTM, I like it, we now removed a lot of code.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 52 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuALgN6ENK9uRmrYrmS:-MuKcQ6MElSqGgAy_aLy:b-sc2eo3) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L52)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I wanted to make this explicit. After a few months, I myself might miss this :). But I can remove it if it is too obvious.
</blockquote></details>

OK, let's keep it if it helps developers.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuANLGv-iW4RXyi8M8K:-MuKcoFD5c4Fa6mzpGfT:b8fyhgs) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

By uninitialized, I mean some garbage value. We don't read this from the host as the file is not present. Also, when the application queries for this path, we return `-ENOENT` from LibOS.
```
$ cat /sys/devices/system/cpu/cpu0/online                                                                                 
cat: /sys/devices/system/cpu/cpu0/online: No such file or directory
```

>  reasonable to always set is_logical_core_online = 1

Given this why set `is_logical_core_online` to 1?

I put this as a reminder comment, but if it is confusing, we can remove it.

</blockquote></details>

Maybe rephrase to a more verbose:
```
/* Core 0 is always online (and thus there is no file `/sys/devices/system/cpu/cpu0/online`),
 * so we leave is_logical_core_online for core 0 uninitialized */
```

What I constantly forget is that `cpu0/online` file doesn't exist, and I think this should be mentioned in this comment.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 99 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAP2tdCS7Mk05VmteC:-MuKdbNW78sjCpFnumMH:bkhxvo5) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L99)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think you are getting confused with `sockets` and `NUMA nodes`. A socket is a physical package, this is dictated by the hardware/VMM.  A NUMA node is a software abstraction to split resources.  We can have n NUMA nodes within a socket. See this, https://www.open-mpi.org/projects/hwloc/lstopo/images/2XeonSPv2+msc.v2.1.png, where we have 2 sockets and each socket, has 2 NUMA nodes.

yes, I use `sockets_cnt` during socket sanitization.
</blockquote></details>

OK, thanks. Yes, I was confusing sockets to be the same as NUMA nodes. Thanks for the clarification.
___
*[Pal/src/host/Linux-common/topo_info.c, line 101 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAcHxX7PO8DXESeK0V:-MuKfOxEESNnr3bimQTE:b178oix) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/src/host/Linux-common/topo_info.c#L101)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

A few of the lines exceeded 100 chars and I needed to wrap them. So added this helper variable.

Removed it.

</blockquote></details>

OK, I understand the reasoning (I guess in the old code it was more useful). The new version looks better to me.
___
*[Pal/src/host/Linux-common/topo_info.c, line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAaHNX9MfeAZfHruWj:-MuKfnxw844Y8rK3J9Hk:b2w25i) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/src/host/Linux-common/topo_info.c#L119)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Unless we encounter files with `\t`, it is better not to add it. So far, I haven't seen the need.
</blockquote></details>

But you have a check for `\t` 20 lines above (see my other comment).
___
*[Pal/src/host/Linux-common/topo_info.c, line 266 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAdWr67o2k-e8Wr-qK:-MuKge8N6fALjiDMChHU:b-vh4vpt) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/src/host/Linux-common/topo_info.c#L266)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`PAL_SYSFS_BUF_FILESZ` is only 64, but here we end up with strings with larger lengths. We could use `PAL_SYSFS_MAP_FILESZ` but the name is confusing in this context.

We can either leave it or put some other macro length of the filename.

</blockquote></details>

LGTM, you added a new macro.
___
*[Pal/src/host/Linux-common/topo_info.c, line 336 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAdmdv44sJojEHj-KQ:-MuKh3YS0M3ZzQlt5kPc:b-bpilr0 [...]

2022-01-27 02:42 UTC, mkow requested changes
> Reviewed 12 of 21 files at r1, 1 of 8 files at r3, 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 64 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[-- commits, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDbuOk0VO1Oq3s0qtJ):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about the following? 
```
This commit creates a clean representation of topology data on the trusted<->untrusted boundary, so that we can easily verify its correctness. The following are done:
        1. Refactor sysfs code to convert CPU/NUMA information from
           Linux-formatted strings to integers in untrusted PAL.
        2. Copy and sanitize CPU/NUMA information based on untrusted
           integers to trusted PAL.
        3. Convert the trusted CPU/NUMA information from integers back
           to Linux-formatted strings in LibOS.
```
</blockquote></details>

Looks better.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLBB2EDuF0KsmZ4Reb:-MuLBB2EDuF0KsmZ4Rec:b-11rk94) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
> ```objc
>  * Example output for 64 cores in total and ranges 0-15,48-55: "00ff0000,0000ffff".
>  * Note: This function adds a newline at the end of the string. */
> int sys_convert_ranges_to_cpu_bitmap_str(const struct pal_res_range_info* resource_range_info, char* str,
> ```

please fix wrapping
___
*[LibOS/shim/src/fs/proc/info.c, line 129 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAEY5S9cSNVHT4pCno:-MuIQgoG4wQeGFiOMjGd:bl7bat1) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/LibOS/shim/src/fs/proc/info.c#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I see your point. Hopefully we'll remove this `enable_sysfs_topology` soon anyway.
</blockquote></details>

I also prefer skipping it than printing wrong value.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLDiqrEhHsoKcWGvVy:-MuLDiqrEhHsoKcWGvVz:b-kdnjx7) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/cache_info.c#L45)):*
> ```C
>                 break;
>             case CACHE_TYPE_UNIFIED:
>                 ret = snprintf(str, sizeof(str), "%s\n", "Unified");
> ```

What's the point of `"%s\n", "Unified"`? Please simplify here and above.
___
*[LibOS/shim/src/fs/sys/fs.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLbDEqDvV-2UDzp6QC:-MuLbDEqDvV-2UDzp6QD:b-nf4vgx) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L21)):*
> ```C
>     size_t range_cnt = resource_range_info->range_cnt;
>     size_t offset = 0;
>     for (size_t i = 0; i < range_cnt; i++) {
> ```

You leave `str` uninitialized and return success for empty ranges list.
___
*[LibOS/shim/src/fs/sys/fs.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLfxlt969S563712Hn:-MuLfxlt969S563712Ho:bln2r6j) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L56)):*
> ```
> BITS_TO_INTS
> ```

`bitmap` is not an array of `int`s
___
*[LibOS/shim/src/fs/sys/fs.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLk3bMCATHVi9yrw1G:-MuLk3bMCATHVi9yrw1H:bfmd7hg) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L75)):*
> ```C
>     /* Convert cpumask to strings */
>     size_t offset = 0;
>     for (size_t j = cpumask_cnt; j > 0; j--) {
> ```

Please assert that `cpumask_cnt > 0`, it should always be true, but otherwise this function unintuitively returns incorrect results.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuANLGv-iW4RXyi8M8K:-MuNhm3n66jMTHqn1gBT:b-cnceko) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe rephrase to a more verbose:
```
/* Core 0 is always online (and thus there is no file `/sys/devices/system/cpu/cpu0/online`),
 * so we leave is_logical_core_online for core 0 uninitialized */
```

What I constantly forget is that `cpu0/online` file doesn't exist, and I think this should be mentioned in this comment.
</blockquote></details>

+1 to Dmitrii's proposal
___
*[Pal/include/arch/x86_64/pal_topology.h, line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuIlbLB4PZkb9CCZDAo:-MuIlbLB4PZkb9CCZDAp:beb6lsi) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L4)):*
> ```objc
> /* Copyright (C) 2022 Intel Corporation
>  *                    Michał Kowalczyk <mkow@invisiblethingslab.com>
>  * Copyright (C) 2022 Intel Corporation
> ```

You don't have to duplicate this line, see how we do this in other files.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuIm3HA6_86i6wefeAc:-MuIm3HA6_86i6wefeAd:b-h65eg4) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L11)):*
> ```objc
> #define PAL_TOPOLOGY_H
> 
> /* Used to represent buffers having numeric values with unit suffixes. E.g "1024576K".
> ```

`E.g` -> `E.g.`
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuInSvt7psdHdXjxQPr:-MuInSvt7psdHdXjxQPs:b-w3foko) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L11)):*
> ```objc
> #define PAL_TOPOLOGY_H
> 
> /* Used to represent buffers having numeric values with unit suffixes. E.g "1024576K".
> ```

`suffixes. E` -> `suffixes, e`
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMBspkCDBr1GV2zM_J:-MuMBspl8DqPBwGTQPHy:b-q0pdde) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L11)):*
> ```objc
> #define PAL_TOPOLOGY_H
> 
> /* Used to represent buffers having numeric values with unit suffixes. E.g "1024576K".
> ```

Also, isn't this outdated now?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuLhcsGECnSnq59bi2P:b-wbepzv) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
> ```objc
> struct pal_range_info {
>     size_t start;
>     size_t end;
> ```

inclusive or exclusive?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 43 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuME85aCPxmKc1UXwAo:-MuME85aCPxmKc1UXwAp:baqwt9q) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L43)):*
> ```objc
> 
> struct pal_res_range_info {
>     /* Total number of resources present. Eg. if output o [...]

2022-01-27 07:22 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 15 of 21 files reviewed, 64 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLBB2EDuF0KsmZ4Reb:-MuOco6QEogKMKEyJI4N:b7t2mh1) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix wrapping
</blockquote></details>

Are you suggesting having text until `100 chars`? If so, I purposefully put "Example..." in a separate line so that it will be easier to read. Is this ok?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLDiqrEhHsoKcWGvVy:-MuPE-wKBYKbzq7suq3P:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/cache_info.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of `"%s\n", "Unified"`? Please simplify here and above.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLbDEqDvV-2UDzp6QC:-MuOzkd8BY2damPEqevA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You leave `str` uninitialized and return success for empty ranges list.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLfxlt969S563712Hn:-MuP-3Nf-1NaHvK6psEe:b-f2uj5c) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> BITS_TO_INTS
> ```

`bitmap` is not an array of `int`s
</blockquote></details>

Changed it to `BITS_TO_UINT32S`
___
*[LibOS/shim/src/fs/sys/fs.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLk3bMCATHVi9yrw1G:-MuP-P9RB-0vjF3Eb9A_:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please assert that `cpumask_cnt > 0`, it should always be true, but otherwise this function unintuitively returns incorrect results.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuANLGv-iW4RXyi8M8K:-MuMK2lY8uhltAJPWEGe:b-lg4hyr) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/include/arch/x86_64/pal_topology.h#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe rephrase to a more verbose:
```
/* Core 0 is always online (and thus there is no file `/sys/devices/system/cpu/cpu0/online`),
 * so we leave is_logical_core_online for core 0 uninitialized */
```

What I constantly forget is that `cpu0/online` file doesn't exist, and I think this should be mentioned in this comment.
</blockquote></details>

sure, let me add this comment.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuIlbLB4PZkb9CCZDAo:-MuP6yXf148VTpY8vlMK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You don't have to duplicate this line, see how we do this in other files.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuIm3HA6_86i6wefeAc:-MuP7dc92PMjw-ZFRPWk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`E.g` -> `E.g.`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/355#-MuInSvt7psdHdXjxQPr:-MuP7e_VA6Hc_kBFqLl4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/331ba3614e503105a07b5d5cd55f1dd2ecf3bd5b/Pal/include/arch/x86_64/pal_topology.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`suffixes. E` -> `suffixes, e`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMBspkCDBr1GV2zM_J:-MuP7f_lBRzA1SyqbVO7:b-mb23s) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Also, isn't this outdated now?
</blockquote></details>

This is still valid when we read the cache size from the host which is numeric with suffix format.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuP7wmS-rNl5g6NT23_:bxogcpn) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

inclusive or exclusive?
</blockquote></details>

This is inclusive.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 43 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuME85aCPxmKc1UXwAo:-MuP8g26EQ_IJ_MunYd6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Eg.` -> `E.g.`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 43 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMEdqa5GIasx3qPbXU:-MuP8h4f1WLak-oqQxuE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`were` -> `was`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMEBAXAUs4U0OaoOMn:-MuP8kum40eXyTZgjRns:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Eg.` -> `E.g.`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMEhGZE_HH3ic4hAqN:-MuP8mq-50h2vaWcTE7r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L47)):*
<details><summary><i>Previously, mkow (M [...]

2022-01-27 10:05 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 64 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLk3bMCATHVi9yrw1G:-MuPaT1A4QpJ33uLH9JA:b-49588z) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L75)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see Michal's requested change.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuPadJ76jZNlrv-gwLR:b-3hkk9i) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is inclusive.
</blockquote></details>

I guess Michal wants a comment like this:
```
struct pal_range_info {
    size_t start;
    size_t end;  /* inclusive, e.g., start = 0 and end = 1 has two items (0 and 1) */
```
___
*[Pal/include/arch/x86_64/pal_topology.h, line 72 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuONZVA6et2GeN-HWap:-MuPc1kOAuKvITpR2pl-:b-pk369a) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, `bool` would be most appropriate here but we use a common function `get_hw_resource_value()` to read the values from files. This function takes `size_t pointer` as a parameter to store the read value(s).  So set this variable as `size_t` instead of `bool`.
</blockquote></details>

I wouldn't care much about the actual type here... So I'm fine with Vijay's approach.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 60 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPbK7s7knmEnnL7uwo:-MuPbK7s7knmEnnL7uwp:b-c91uj0) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/include/arch/x86_64/pal_topology.h#L60)):*
> ```objc
>     size_t level;
>     enum cache_type type;
>     /* We store cache size is in bytes. But cache size is usually displayed in KB format. Please do
> ```

`is in bytes` -> `in bytes`
___
*[Pal/include/arch/x86_64/pal_topology.h, line 60 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPbRpXDKfe1FBJncaL:-MuPbRpXDKfe1FBJncaM:b-fqibfw) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/include/arch/x86_64/pal_topology.h#L60)):*
> ```objc
>     size_t level;
>     enum cache_type type;
>     /* We store cache size is in bytes. But cache size is usually displayed in KB format. Please do
> ```

Weird phrasing, I suggest:
```
/* We store cache size in bytes, but it is typically displayed in KB (e.g., "256K"), so for output
 * it should be converted to KBs. See https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu */
```
___
*[Pal/src/host/Linux-common/topo_info.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuKg2sc69k9oaAoooO_:-MuPcKbaAkH7zG84mxGB:b-e6gxv9) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L48)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The overflow should be caught by the earlier function `__builtin_mul_overflow` right?

In this case, it is not overflowing, as `val` is of type `long` and can hold a larger value on a 64-bit system and if it is a 32-bit system, shouldn't have a value greater than `INT_MAX`.  

This check was intended for 64-bit systems where we don't end up with unrealistically large values and so limit to `INT_MAX`. Note: In trusted PAL we do check for such limits, but this will also help in untrusted PAL case as well.

If you feel this is redundant and not needed for untrusted PAL case, I can remove this check itself.
</blockquote></details>

No, it's fine then. Resolving.
___
*[Pal/src/host/Linux-common/topo_info.c, line 125 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuODavB8B8gJqE57YkM:-MuPdaGQ1Vt6ReGfekPP:b-zcvphm) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L125)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes agree, but will do this optimization in a separate PR. Have added a `TODO` to capture this effort.
For this release let us target this basic version of adding each range at a time.

</blockquote></details>

Agreed with Vijay.
___
*[Pal/src/host/Linux-common/topo_info.c, line 103 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPcw2K6JG5TYtjMNIO:-MuPcw2K6JG5TYtjMNIP:b-3sb2yu) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-common/topo_info.c#L103)):*
> ```C
>             }
> 
>             out_info->resource_cnt++;
> ```

Actually, I would prefer to have:
```
out_info->resource_cnt = total_cnt;
```

This way it's clear why you did the check for overflow.
___
*[Pal/src/host/Linux-common/topo_info.c, line 117 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPdGb02RXeX7TvrYd9:-MuPdGb02RXeX7TvrYdA:b-821ydi) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-common/topo_info.c#L117)):*
> ```C
>             size_t diff = end_val - start_val;
>             size_t total_cnt;
>             if (__builtin_add_overflow(out_info->resource_cnt, diff, &total_cnt) ||
> ```

Shouldn't you replace `diff` with `diff + 1` here?

Alternatively, you can add `+ 1` to the `diff = ...` above.
___
*[Pal/src/host/Linux-common/topo_info.c, line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPdDZn21y347Lv4LHM:-MuPdDZn21y347Lv4LHN:b-3sb2yu) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-common/topo_info.c#L122)):*
> ```C
>                 goto fail;
>             }
>             out_info->resource_cnt += diff + 1; /* +1 because of inclusive range */
> ```

Actually, I would prefer to have:
```
out_info->resource_cnt = total_cnt;
```

This way it's clear why you did the check for overflow.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 128 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuAhM2a178M048Of798:-MuPon4vB9JwICjjrXoD:b-pwce34) ([raw file](https://github.com/gramineproject/gramine/blob/79d2bf3405f806c6eaa2f93cf0712989e57d9a2b/Pal/src/host/Linux-SGX/db_main.c#L128)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks for the nice explanation! Sure, will create a separate PR and fix these. 

Now, I have removed all the `READ_ONCE()` and took the shallow copy approach. The code looks more readable with shallow copy :)
</blockquote></details>

You added the shallow copy? where? I don't see it.

Or did you add the shallow copy to the caller of this function, and now the first argument of this function (`untrusted_src`) points to the trusted in-enclave values (`ranges_arr`, `range_cnt`, `resource_cnt`)? If so, you should change the name of the argument (`untrusted_src` -> `src`).

UPDATE: Ok, so you indeed supply a [...]

2022-01-27 16:46 UTC, mkow requested changes
> Reviewed 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLBB2EDuF0KsmZ4Reb:-MuQBawX7wTo3_z3xzAa:b-e21aac) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Are you suggesting having text until `100 chars`? If so, I purposefully put "Example..." in a separate line so that it will be easier to read. Is this ok?
</blockquote></details>

I mean only the function signature, `char* str` is wrapped. You should see this on Reviewable if you configured line length to 100 in it.
___
*[LibOS/shim/src/fs/sys/fs.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLbDEqDvV-2UDzp6QC:-MuQGvY37k2j-XsAA5Yk:b-q8o9n0) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L21)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why do _both_ now?
Instead of what you did maybe just add `str[0] = '\0'`? There's no reason to fail on empty range if we can trivially make it work correctly for it.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuQHlp0CoYir_tcvrKJ:b-dyyx5v) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess Michal wants a comment like this:
```
struct pal_range_info {
    size_t start;
    size_t end;  /* inclusive, e.g., start = 0 and end = 1 has two items (0 and 1) */
```
</blockquote></details>

Yes, I ofc know which one is the case, this was the question from the point of a reader of our codebase. It's not clear from the header until you read the implementation.
Ad the comment: Please do as Dima suggested, but maybe without this example, "inclusive" is not a complex term which would require lengthy explanations.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuODR7F5fjMM2YV6OAD:-MuQIK9J2RCCB9yCZ5EY:b-hgbkgs) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L49)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

why? I want to mention the variable name which is `range_cnt`
</blockquote></details>

? I want you to change the variable name. I don't understand your response here...
___
*[Pal/include/arch/x86_64/pal_topology.h, line 52 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMFLEp0GJRM2Ssw4Ee:-MuQIf0G4zRSvMhDmb-X:boecfai) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L52)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`[{0, 15}, {21, 21}, {32, 63}]` is this fine?
</blockquote></details>

Looks good now.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMFpZn9u3UmSh0lTfE:-MuQIiY8C3aYr5yolSap:b-rpmpkc) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, this is a valid case.
</blockquote></details>

As before, I've read the whole PR so I know, but other developers reading this header in the future won't and the current comment doesn't make it clear how this works.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMHq1WAc95UwJEgC_C:-MuRKPkW-4SVGny1Ae-i:b-ka6iu1) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The comment is incorrect, I do store the value in bytes. Changed comment as below,
```
    /* We store cache size is in bytes. But cache size is usually displayed in KB format. Please do
     * the needful conversion.
     * Pls ref: https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu */
```
</blockquote></details>

Then please just drop the whole comment, I don't see why "how we usually print this value in sysfs" could have any importance here.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 72 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuONZVA6et2GeN-HWap:-MuRKoFM5VB2tuZG0ZgF:b-k68d39) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wouldn't care much about the actual type here... So I'm fine with Vijay's approach.
</blockquote></details>

Then just use `get_hw_resource_value()` on a temporary variable and then assign to `is_logical_core_online`. `size_t` makes no sense here and this is a global structure, it should be as clean and intuitive as possible.
___
*[Pal/src/host/Linux-common/topo_info.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuKg2sc69k9oaAoooO_:-MuRJJLd0RFU7ax4hjYM:bwx6qpi) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L48)):*
> If you feel this is redundant and not needed for untrusted PAL case, I can remove this check itself.

I don't see any point in doing these checks here, especially that nothing should break if the value is bigger than this.
___
*[Pal/src/host/Linux-common/topo_info.c, line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuO3eEhCyJHupNkpX3-:-MuRLFdy5uDPoXUwsIGd:bg6qup) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L58)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Is this `1-5,10-15,20,30-31` better?
</blockquote></details>

Why not just change "6" to "7" in your original example? The new one is much more complicated but doesn't really provide any more information than the original.
___
*[Pal/src/host/Linux-common/topo_info.c, line 185 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOG5RoCkU6o0Gz5eo4:-MuRNSnC3h1ikV8MWV0L:bgbg3g8) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L185)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Reworded as 
```
/* Updates `cache_indices_cnt` with number of cache levels present on the system by counting
 * "indexX" dir entries under `/sys/devices/system/cpu/cpuX/cache`. Returns 0 on success and
 * negative UNIX error code on failure. */
```
</blockquote></details>

It's not really correct now, "to update something" slightly implies reading and then refreshing some value. Here we just return  [...]

2022-01-27 20:04 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 12 of 21 files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLBB2EDuF0KsmZ4Reb:-MuRaP5c87hRXbYFQrUz:b2f3mj8) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean only the function signature, `char* str` is wrapped. You should see this on Reviewable if you configured line length to 100 in it.
</blockquote></details>

yes got it, thanks.
___
*[LibOS/shim/src/fs/sys/fs.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLbDEqDvV-2UDzp6QC:-MuRhAUMCA9427bX6wt9:bctn24y) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do _both_ now?
Instead of what you did maybe just add `str[0] = '\0'`? There's no reason to fail on empty range if we can trivially make it work correctly for it.
</blockquote></details>

Sorry, I don't understand. Are you saying it is fine to pass an empty string back to the application? This function basically converts ranges to strings, and I feel if the range is empty, we should not return success. 

Converted `memset(str, 0, str_size)` -> `str[0] = '\0'` although I still prefer `memset()` :).
___
*[LibOS/shim/src/fs/sys/fs.c, line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLk3bMCATHVi9yrw1G:-MuQywRS9VyvHY-6iv4P:buzmr5r) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see Michal's requested change.
</blockquote></details>

Sorry I put the check in a different place in `db_main.c`, but it is not actually needed there. Fixed it here.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuR-Xow5n1uXxEHrog8:b-t9opso) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, I ofc know which one is the case, this was the question from the point of a reader of our codebase. It's not clear from the header until you read the implementation.
Ad the comment: Please do as Dima suggested, but maybe without this example, "inclusive" is not a complex term which would require lengthy explanations.
</blockquote></details>

oh ok :). Added the comment.

This comment confused me :) I was not sure if it was a question or a suggestion. Next time just say, add a comment.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 49 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuODR7F5fjMM2YV6OAD:-MuRlMSwCMMSb4AEM8N9:b-qdsaj3) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

? I want you to change the variable name. I don't understand your response here...
</blockquote></details>

I misunderstood your comment. I thought you meant to change the comment.
Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMFpZn9u3UmSh0lTfE:-MuRm5UkC4oq-fQmrp5W:b2mll65) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

As before, I've read the whole PR so I know, but other developers reading this header in the future won't and the current comment doesn't make it clear how this works.
</blockquote></details>

Yes, please say "add an example in the comment". I was not sure if it was a question or a suggestion.

I have updated the example to show touching ranges. Is this `[{0, 15}, {16, 30}, {31, 31}]` example fine? 
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMHq1WAc95UwJEgC_C:-MuRnddz8pqL8zS_Am_K:bm3yqt3) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then please just drop the whole comment, I don't see why "how we usually print this value in sysfs" could have any importance here.
</blockquote></details>

OK, done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 72 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuONZVA6et2GeN-HWap:-MuRpcE14FgdF3z9jx6-:bm3yqt3) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then just use `get_hw_resource_value()` on a temporary variable and then assign to `is_logical_core_online`. `size_t` makes no sense here and this is a global structure, it should be as clean and intuitive as possible.
</blockquote></details>

OK, done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 60 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPbK7s7knmEnnL7uwo:-MuR0dWD9PY_jMR4w6tj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/include/arch/x86_64/pal_topology.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`is in bytes` -> `in bytes`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 60 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPbRpXDKfe1FBJncaL:-MuR1PPC1Ong7jd2A2M3:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/include/arch/x86_64/pal_topology.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Weird phrasing, I suggest:
```
/* We store cache size in bytes, but it is typically displayed in KB (e.g., "256K"), so for output
 * it should be converted to KBs. See https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu */
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuKg2sc69k9oaAoooO_:-MuRqs7t2ld1Fa1LOXdH:b-pwssgr) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If you feel this is redundant and not needed for untrusted PAL case, I can remove this check itself.

I don't see any point in doing these checks here, especially that nothing should break if the value is bigger than this.
</blockquote></details>

Nothing will break but we can have bizarre values which will trickle down to trusted PAL and then fail. This was for catching the issue in the untrusted PAL itself and failing.

But I have removed the checks. 
___
*[Pal/src/host/ [...]

2022-01-28 00:59 UTC, mkow requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLbDEqDvV-2UDzp6QC:-MuSeByjDmqp1ibbeW9i:bj6onhg) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/LibOS/shim/src/fs/sys/fs.c#L21)):*
> Are you saying it is fine to pass an empty string back to the application?

We probably won't do this because we sanitize the data, but it seems more intuitive to me that printing an empty list gives you an empty string, rather than erroring out. But I won't block on this.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuLhcsFEJ_kxqQSkFz-:-MuSf3rE4rYHl8slkHM6:bok1na0) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

oh ok :). Added the comment.

This comment confused me :) I was not sure if it was a question or a suggestion. Next time just say, add a comment.
</blockquote></details>

But I don't want you to blindly copy-paste my suggestions without thinking ;) You should read them, look at the code and think whether they make sense and what does they mean (e.g.: "oh, this is actually unclear, I should add a comment" or maybe "I already have a comment about this, but you probably just missed it" or "maybe instead it's better to rename this variable?").
___
*[Pal/include/arch/x86_64/pal_topology.h, line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMFpZn9u3UmSh0lTfE:-MuSftBLALZuWuQmG-TM:b-1it7i) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, please say "add an example in the comment". I was not sure if it was a question or a suggestion.

I have updated the example to show touching ranges. Is this `[{0, 15}, {16, 30}, {31, 31}]` example fine? 
</blockquote></details>

Better, but now the example has no holes in the ranges, which _are_ allowed. Reading it you can get an impression that the ranges have to be adjacent.
___
*[Pal/src/host/Linux-common/topo_info.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuKg2sc69k9oaAoooO_:-MuSgOk4AqKw_ID0eCsG:b-tp5t60) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L48)):*
> This was for catching the issue in the untrusted PAL itself and failing.

But this is pointless, we need to duplicate these checks anyways in trusted PAL. And on non-TEE PALs these values are trusted.
___
*[Pal/src/host/Linux-common/topo_info.c, line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuO3eEhCyJHupNkpX3-:-MuSggZgAQEHoN-cCrj4:bgh8mgp) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L58)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I thought having an individual value at the extremes made you think it was exclusive.  So made it as a range. But I don't understand how changing `6`->`7` will help. Please explain. 

I have changed it to `7` now.
</blockquote></details>

Because specifying `3-5,6` makes no sense if the ranges are inclusive, you'd have `3-6` instead then. But if the ends were exclusive, then `3-5,6` would make sense.
___
*[Pal/src/host/Linux-common/topo_info.c, line 185 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOG5RoCkU6o0Gz5eo4:-MuShgZH-fXiyvOEFVTX:bwmksoa) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L185)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about now?
```
/* This function stores the number of cache levels present on the system by counting "indexX" dir
 * entries under `/sys/devices/system/cpu/cpuX/cache`in `out_cache_indices_cnt`. Returns 0 on
 * success and negative UNIX error code on failure. */
```

Also renamed name the out variable as `out_cache_indices_cnt`.

If this is not clear, please suggest your text and I will work it in.
</blockquote></details>

Looks ok, but you're missing a space before `in`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 239 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOK4tzADhnoWk58XLh:-MuSiMJV1917yCdafj-Y:bhtqj3x) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L239)):*
> Wait, are you saying that the C-string lengths (`strlen`) don't account for null byte and so this is not a `LEN` but `SIZE`?

Yes, `strlen()` doesn't count the null byte, but it's a bit unrelated. It's just our convention that we use "len" for C-string length and "size" for C-string byte-size.

> But I read C-string as "Hello", which does include the null byte and not compare it with the return value of `strlen()`.

I don't understand what you wanted to say here ;)
___
*[Pal/src/host/Linux-common/topo_info.c, line 312 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOMB714nO9bbRwJpHF:-MuSixUr9-ZtPtE6mUsV:bcfhzve) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L312)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can we have larger than `2147483647` online cores? I set this as an upper limit to catch such ridiculously large values which will finally fail in trusted PAL because we have limit checks there. Idea was to catch such inconsistencies earlier and return.

But I have removed these checks.
</blockquote></details>

It can only mask missing verification in the trusted code and is just code duplication because we already check it there.
___
*[Pal/src/host/Linux-common/topo_info.c, line 103 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPcw2K6JG5TYtjMNIO:-MuShGIJ21SE34s5eed1:b-jvitjg) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-common/topo_info.c#L103)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This will exceed `100 chars` so used a temp variable for better readability.
</blockquote></details>

Hmm, it easily fits in 100 chars for me?

```C
            if (__builtin_add_overflow(out_info->resource_cnt, 1, &out_info->resource_cnt)) {
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 165 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPqAQCEAF7yZDoqCdn:-MuSwWDZ7KlEva1Q49K9:b-bus6rw) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L165)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Waaait, what was wrong with the old code? Why `READ_ONCE()` here?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 208 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPuiX04FrhjYT-Izq2:-MuSwvA93QW9sTMWxgqm:bbv287a) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f6 [...]

2022-01-28 04:29 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 18 of 21 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 54 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuMFpZn9u3UmSh0lTfE:-MuTfRVI3YeWbd14h10I:bgav992) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/include/arch/x86_64/pal_topology.h#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Better, but now the example has no holes in the ranges, which _are_ allowed. Reading it you can get an impression that the ranges have to be adjacent.
</blockquote></details>

OK, made the ranges discontinuous.
___
*[Pal/src/host/Linux-common/topo_info.c, line 58 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuO3eEhCyJHupNkpX3-:-MuTfnnO0nPzb1YT21Ps:b-uv4ta) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because specifying `3-5,6` makes no sense if the ranges are inclusive, you'd have `3-6` instead then. But if the ends were exclusive, then `3-5,6` would make sense.
</blockquote></details>

Thanks for the clarification.
___
*[Pal/src/host/Linux-common/topo_info.c, line 185 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOG5RoCkU6o0Gz5eo4:-MuTguL17NqFeKzMp0qE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks ok, but you're missing a space before `in`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 239 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOK4tzADhnoWk58XLh:-MuTV_9JAA5PhegVsqKg:b55xptt) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L239)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Wait, are you saying that the C-string lengths (`strlen`) don't account for null byte and so this is not a `LEN` but `SIZE`?

Yes, `strlen()` doesn't count the null byte, but it's a bit unrelated. It's just our convention that we use "len" for C-string length and "size" for C-string byte-size.

> But I read C-string as "Hello", which does include the null byte and not compare it with the return value of `strlen()`.

I don't understand what you wanted to say here ;)
</blockquote></details>

I was trying to reason out why you would suggest `_SIZE` instead of `_LEN` :)
___
*[Pal/src/host/Linux-common/topo_info.c, line 312 at r4](https://reviewable.io/reviews/gramineproject/gramine/355#-MuOMB714nO9bbRwJpHF:-MuTVn8Z79gw99laNgfP:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/de251e7220e7b435368d3513394f64d7d118d530/Pal/src/host/Linux-common/topo_info.c#L312)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It can only mask missing verification in the trusted code and is just code duplication because we already check it there.
</blockquote></details>

OK.
___
*[Pal/src/host/Linux-common/topo_info.c, line 103 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPcw2K6JG5TYtjMNIO:-MuTgbHV9qMq4DOOWCQl:bd3wl71) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-common/topo_info.c#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, it easily fits in 100 chars for me?

```C
            if (__builtin_add_overflow(out_info->resource_cnt, 1, &out_info->resource_cnt)) {
```
</blockquote></details>

oh my bad, removed the temporary variable.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 165 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPqAQCEAF7yZDoqCdn:-MuTjooSCSrlQ5cdV7KP:b8fnytw) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Waaait, what was wrong with the old code? Why `READ_ONCE()` here?
</blockquote></details>

The issue here is `temp_topo_info` is a shallow copied object and so the `core_topo_arr` is still an untrusted pointer. So, to prevent compiler optimization `READ_ONCE()` is used.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 263 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPw4EH1b2YWt5TNh56:-MuTkODO2xnVJkUJU0Ji:b-93cq4l) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L263)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Same reason for using `READ_ONCE()` in `sgx_copy_core_topo_to_enclave()`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSkwfe59Pjam57DWUh:-MuTiOLm1JtAGBqF_6JX:bosiwfe) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this TODO, what is incorrectly accessed here? You added it at a line which looks correct.
</blockquote></details>

Here`uptr_src` is an untrusted pointer and we don't want the compiler to do any optimization to it. So added the `TODO`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 131 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT6iBL5hCKEUpt97Qg:-MuTVxqa0e7VCitut02T:b-6n2w9z) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if untrusted host sets `src->ranges_cnt` to 0x8000000000000001?
</blockquote></details>

Good point, this might result in a DOS attack. How about adding an upper limit check for `ranges_cnt`? But I am not sure what should be the upper limit?

```
 static int copy_resource_range_to_enclave(struct pal_res_range_info* src,
                                           struct pal_res_range_info* dest) {
+    if (src->ranges_cnt > UINT16_MAX)
+        return -1;
+
     struct pal_range_info* ranges_arr = malloc(src->ranges_cnt * sizeof(*ranges_arr));
     if (!ranges_arr) {
         log_error("Range allocation failed");
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 262 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT-p9x7V__WK7jGI0m:-MuT_fPQEjhF0yyEcrI0:bph80y7) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why printing an error here? We don't do this in other cases when we run out of memory, we should just print this in a single place, somewhere top-level.
ditto for other places like this
</blockquote></details>

If we remove all the printing, and something fails we end up with this message `Failed to copy and sanitize topology information`. This is not helpful. I think these logs are really needed esp. for topology cases where we have multiple levels of function calls. The only place where I haven [...]

2022-01-28 08:41 UTC, dimakuv requested changes
> Reviewed 6 of 9 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 138 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPtQBtAJheJzyBumhc:-MuUmkpj9hKYzSQHw3xE:bebyb7q) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L138)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I was wrong. You don't need it here, because you do not *dereference* `src->ranges_arr` (which is an untrusted pointer) and thus there is no untrusted memory access happenning. You only dereference `src` which is a trusted pointer. So you don't need `READ_ONCE()`, just remove it.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 165 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPqAQCEAF7yZDoqCdn:-MuUnTqK95OEliJaIpk_:b8sftrc) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L165)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The issue here is `temp_topo_info` is a shallow copied object and so the `core_topo_arr` is still an untrusted pointer. So, to prevent compiler optimization `READ_ONCE()` is used.
</blockquote></details>

Yes, sorry, Vijay. Please revert `READ_ONCE(untrusted_src)` -> `untrusted_src`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 208 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPuiX04FrhjYT-Izq2:-MuUncb9BxxgxM3oCF6U:b-81g93b) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L208)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Rule of thumb: always add READ_ONCE to the third argument of sgx_copy_to_enclave().

Uhmmm?
</blockquote></details>

Please revert.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 263 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPw4EH1b2YWt5TNh56:-MuUoOhS3Vx7tjDIg7LU:b-n67mzv) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L263)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Same reason for using `READ_ONCE()` in `sgx_copy_core_topo_to_enclave()`
</blockquote></details>

Please revert
___
*[Pal/src/host/Linux-SGX/db_main.c, line 739 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPzKqi4bvN60hitnXT:-MuUpviI2nyEueitHy3I:b-n67mzv) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L739)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Please revert
___
*[Pal/src/host/Linux-SGX/db_main.c, line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSkwfe59Pjam57DWUh:-MuUm5ruDznX9VA6r-Ig:bk0kulj) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L88)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here`uptr_src` is an untrusted pointer and we don't want the compiler to do any optimization to it. So added the `TODO`
</blockquote></details>

See my other comment here, I was an idiot and explained you not 100% correctly :(
___
*[Pal/src/host/Linux-SGX/db_main.c, line 262 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT-p9x7V__WK7jGI0m:-MuUnocV1jAyjLsGli-_:b-ld0p8e) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L262)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If we remove all the printing, and something fails we end up with this message `Failed to copy and sanitize topology information`. This is not helpful. I think these logs are really needed esp. for topology cases where we have multiple levels of function calls. The only place where I haven't added error prints is in the `realloc` flows as we plan to clean this up in a separate PR.  If needed I can add error prints, there too.

The other function where we do `malloc` and don't print error on failure is `make_argv_list()`. This is a small function, and a top-level error message makes sense here.

But if reviewers strongly feel otherwise, I can remove it.
</blockquote></details>

I was actually fine with this error.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 909 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSvCaZ74c5JBeErbid:-MuUpzII4ZDDrGe0ze2D:b-mv9avb) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L909)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There isn't untrusted access. I have updated my comment.
</blockquote></details>

Please revert this comment (delete it)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 923 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSvFrn6Gqin1HJRylq:-MuUq2DQ2tD-_XHFrYSl:b-mv9avb) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L923)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Updated my comment.
</blockquote></details>

Please revert this comment (delete it)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 90 at r7](https://reviewable.io/reviews/gramineproject/gramine/355#-MuUjWS7CdJ5BtJsXVsS:-MuUjWS7CdJ5BtJsXVsT:br4oozu) ([raw file](https://github.com/gramineproject/gramine/blob/a7084206f8927fbdce03adf28ef6d875e264ae32/Pal/src/host/Linux-SGX/db_main.c#L90)):*
> ```C
> 
>     /* TODO: Fix potential compiler optimization of untrusted pointer `uptr_src` by adding
>      * `READ_ONCE()`. */
> ```

Oops, sorry Vijay. This was my blunder. I got it wrong.

So, the rule should be: if the third argument of `sgx_copy_to_enclave()` contains a *dereference* of an untrusted pointer (i.e., contains memory access through an untrusted pointer), only then we need to add `READ_ONCE()`. (Because this is what the macro `READ_ONCE()` does -- it accesses memory only once).

In this case -- like in some other cases (I marked them all in this PR) -- I was wrong and I recommended you this redundant `READ_ONCE()`. In this particular case, the third argument is simply `uptr_src` -- which doesn't do any memory access, but simply this pointer value is passed to the function. So there is no need in `READ_ONCE()`.

Please remove this TODO comment.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 470 at r7](https://reviewable.io/reviews/gramineproject/gramine/355#-MuUo_f8BMHVbE7lbwkZ:-MuUo_f8BMHVbE7lbwk_:bacd4mz) ([raw file](https://github.com/gramineproject/gramine/blob/a7084206f8927fbdce03adf28ef6d875e264ae32/Pal/src/host/Linux-SGX/db_main.c#L470)):*
> ```C
>         if (idx != 0) {     /* core 0 is always online */
>             bool is_core_online = core_topo_arr[idx].is_logical_core_online;
>             if (is_core_online != false && is_core_online != true) {
> ```

Wait, this doesn't make sense anymore :) Booleans can only have `false` and `true` values, nothing else, so this if is meaningless now.

I suggest to simply remove this check on `is_logical_core_online` comple [...]

2022-01-28 15:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuWF9wjCrMJkFAnWvJT:bs3eiuw) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Pulled out the first 2 commits and created https://github.com/gramineproject/gramine/pull/360
</blockquote></details>

@mkow, @dimakuv Please let me know if I can rebase and update the commit log.

---
___
*[Pal/src/host/Linux-SGX/db_main.c, line 138 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPtQBtAJheJzyBumhc:-MuWD8ZlAhkU-vG3RR8c:bner5nb) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L138)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I was wrong. You don't need it here, because you do not *dereference* `src->ranges_arr` (which is an untrusted pointer) and thus there is no untrusted memory access happenning. You only dereference `src` which is a trusted pointer. So you don't need `READ_ONCE()`, just remove it.
</blockquote></details>

Reverted the change.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 165 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPqAQCEAF7yZDoqCdn:-MuWDL_F7uDTMem093yt:bner5nb) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, sorry, Vijay. Please revert `READ_ONCE(untrusted_src)` -> `untrusted_src`.
</blockquote></details>

Reverted the change.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 208 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPuiX04FrhjYT-Izq2:-MuWDRnM9KaCj281ThYU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L208)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 263 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPw4EH1b2YWt5TNh56:-MuWDVbG9LNCX1Rf5qfe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 739 at r5](https://reviewable.io/reviews/gramineproject/gramine/355#-MuPzKqi4bvN60hitnXT:-MuWDaKf5DH0_EqWOGMv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83454412bf5bdf6d4f62157e486e0a60edc944b4/Pal/src/host/Linux-SGX/db_main.c#L739)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 88 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSkwfe59Pjam57DWUh:-MuWE-1TBnUguUq0zHOp:bdse7) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comment here, I was an idiot and explained you not 100% correctly :(
</blockquote></details>

I have reverted the comment.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 909 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSvCaZ74c5JBeErbid:-MuWDpJ-2siQ6Moq7gtq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L909)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert this comment (delete it)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 923 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuSvFrn6Gqin1HJRylq:-MuWDrig4BLPZZMMVUaG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L923)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert this comment (delete it)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 90 at r7](https://reviewable.io/reviews/gramineproject/gramine/355#-MuUjWS7CdJ5BtJsXVsS:-MuW9y9E19lv0E9awmJO:bls3n4t) ([raw file](https://github.com/gramineproject/gramine/blob/a7084206f8927fbdce03adf28ef6d875e264ae32/Pal/src/host/Linux-SGX/db_main.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry Vijay. This was my blunder. I got it wrong.

So, the rule should be: if the third argument of `sgx_copy_to_enclave()` contains a *dereference* of an untrusted pointer (i.e., contains memory access through an untrusted pointer), only then we need to add `READ_ONCE()`. (Because this is what the macro `READ_ONCE()` does -- it accesses memory only once).

In this case -- like in some other cases (I marked them all in this PR) -- I was wrong and I recommended you this redundant `READ_ONCE()`. In this particular case, the third argument is simply `uptr_src` -- which doesn't do any memory access, but simply this pointer value is passed to the function. So there is no need in `READ_ONCE()`.

Please remove this TODO comment.
</blockquote></details>

OK, so when we pass an untrusted pointer, basically a local copy of it is made on the callee stack/registers and so it is safe but if we end up referencing it, then there is a chance the untrusted pointer's value can be modified. Is my assumption correct?

I have reverted the change.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 470 at r7](https://reviewable.io/reviews/gramineproject/gramine/355#-MuUo_f8BMHVbE7lbwkZ:-MuW9YkbDpdBXKinKC-D:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a7084206f8927fbdce03adf28ef6d875e264ae32/Pal/src/host/Linux-SGX/db_main.c#L470)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, this doesn't make sense anymore :) Booleans can only have `false` and `true` values, nothing else, so this if is meaningless now.

I suggest to simply remove this check on `is_logical_core_online` completely. All these 7 lines.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 15:29 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 90 at r7](https://reviewable.io/reviews/gramineproject/gramine/355#-MuUjWS7CdJ5BtJsXVsS:-MuWIBvJ-7PdB8eyIDSA:bt0ofmk) ([raw file](https://github.com/gramineproject/gramine/blob/a7084206f8927fbdce03adf28ef6d875e264ae32/Pal/src/host/Linux-SGX/db_main.c#L90)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, so when we pass an untrusted pointer, basically a local copy of it is made on the callee stack/registers and so it is safe but if we end up referencing it, then there is a chance the untrusted pointer's value can be modified. Is my assumption correct?

I have reverted the change.
</blockquote></details>

Yes, your assumption is correct.


<!-- Sent from Reviewable.io -->

2022-01-28 15:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuWIXCP-jzN6SJSFiwf:b-i6zkf8) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow, @dimakuv Please let me know if I can rebase and update the commit log.
</blockquote></details>

From my side, looks good. Wait for Michal's approval.

---


<!-- Sent from Reviewable.io -->

2022-01-28 15:43 UTC, mkow requested changes
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuWHlM2-lNscQ9n1wGl:bnhwgp2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From my side, looks good. Wait for Michal's approval.
</blockquote></details>

Not yet, I'm still verifying the sanitization and checks in the trusted part.

---
___
*[Pal/src/host/Linux-SGX/db_main.c, line 131 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT6iBL5hCKEUpt97Qg:-MuWJl0_2Bp1czxcH9Bx:b5h8k9f) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L131)):*
> this might result in a DOS attack

SGX server's owner can do this also by just shutting down the server? DoS attacks are not a threat in SGX security model.

This bug is not about DoS, but memory corruption inside the enclave.

```C
    if (src->ranges_cnt > UINT16_MAX)
        return -1;
```

This looks like a hacky workaround, please use proper compiler builtins for checking overflows.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 138 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTEMHG8-SLSZauEksJ:-MuTEMHH1AvlykWBcJhw:b-agkks1) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L138)):*
> ```C
> 
>     /* Even though `src` points to a safe in-enclave object, the `src->ranges_arr` pointer is
>      * untrusted and may maliciously point to inside the enclave; thus need to use
> ```

`to inside the enclave` -> `inside the enclave`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 153 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTFvBe4xtCRRWD6AWO:-MuTFvBe4xtCRRWD6AWP:b-c9mb21) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L153)):*
> ```C
> }
> 
> static int sgx_copy_core_topo_to_enclave(struct pal_core_topo_info* untrusted_src,
> ```

In other places we use `uptr_` instead of `untrusted_`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 749 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTDm678pk1DxgsArtW:-MuTDm678pk1DxgsArtX:b-lnrco9) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L749)):*
> ```C
> 
>     struct pal_topo_info* topo_info = &g_pal_public_state.topo_info;
>     memset(topo_info, 0, sizeof(*topo_info));
> ```

What's the point of zeroing it? It's a global structure, it's zero-initialized.


<!-- Sent from Reviewable.io -->

2022-01-28 17:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 131 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT6iBL5hCKEUpt97Qg:-MuWSSmj56hsy3PGxe2m:b5z8xx7) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> this might result in a DOS attack

SGX server's owner can do this also by just shutting down the server? DoS attacks are not a threat in SGX security model.

This bug is not about DoS, but memory corruption inside the enclave.

```C
    if (src->ranges_cnt > UINT16_MAX)
        return -1;
```

This looks like a hacky workaround, please use proper compiler builtins for checking overflows.
</blockquote></details>

I missed the overflow point here. IIUC, you are referring to `src->ranges_cnt * sizeof(*ranges_arr)` issue rather than the value of `src->ranges_cnt` itself. Please correct me if I misunderstood.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 138 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTEMHG8-SLSZauEksJ:-MuWZWRV-rBBoiJEx7Ke:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L138)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`to inside the enclave` -> `inside the enclave`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 153 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTFvBe4xtCRRWD6AWO:-MuWaFL2BRhNYORuBr7S:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In other places we use `uptr_` instead of `untrusted_`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 749 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTDm678pk1DxgsArtW:-MuWbZgZ0E3CsW9-3qep:bq5er2y) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L749)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of zeroing it? It's a global structure, it's zero-initialized.
</blockquote></details>

I retained this approach of clearing the global from earlier PR. Should I delete this?

Recall this discussion from PR #325 
```
Pal/src/host/Linux-SGX/db_main.c, line 405 at r3 (raw file):

Previously, boryspoplawski (Borys Popławski) wrote…
What is this comment about? What exactly here is a "temporary measure"?

This memset, we should just initialize all the fields anyways without a need for memset if we didn't have this feature-switch. Also, this comment was moved from db_misc.c.
Or maybe you think we should keep this memset even in the final version, just in case we leave something uninitialized?
```


<!-- Sent from Reviewable.io -->

2022-01-28 22:49 UTC, mkow requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 131 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuT6iBL5hCKEUpt97Qg:-MuXpukX3LYP5cnsCUrP:b3mft2v) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L131)):*
> I missed the overflow point here.

Hmm, but there's only overflow here, there's no other problem?

> IIUC, you are referring to [...]

To both, the overflow is possible because `src->ranges_cnt` is untrusted.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 749 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTDm678pk1DxgsArtW:-MuXqwOYBQN5KpOyxxAq:bwlvyes) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L749)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I retained this approach of clearing the global from earlier PR. Should I delete this?

Recall this discussion from PR #325 
```
Pal/src/host/Linux-SGX/db_main.c, line 405 at r3 (raw file):

Previously, boryspoplawski (Borys Popławski) wrote…
What is this comment about? What exactly here is a "temporary measure"?

This memset, we should just initialize all the fields anyways without a need for memset if we didn't have this feature-switch. Also, this comment was moved from db_misc.c.
Or maybe you think we should keep this memset even in the final version, just in case we leave something uninitialized?
```
</blockquote></details>

I guess I just missed that this is a global variable when writing it or just copied too much code from somewhere where it wasn't obvious that it's a global ¯\\_(ツ)_/¯
It doesn't make sense, so please remove it.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 146 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuXqA3P4Pkv8JDV0lII:-MuXqA3P4Pkv8JDV0lIJ:bd7ypex) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L146)):*
> ```C
>      * `sgx_copy_to_enclave()` function */
>     if (!sgx_copy_to_enclave(ranges_arr, src->ranges_cnt * sizeof(*ranges_arr),
>                              src->ranges_arr, src->ranges_cnt * sizeof(*src->ranges_arr))) {
> ```

please use `range_arr_size` in both places here


<!-- Sent from Reviewable.io -->

2022-01-29 01:05 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MuYBu0BAMCUG7jJ7kWl:b444ngt) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
> ```C
>         return -1;
>     }
>     ret = sanitize_hw_resource_range(&topo_info->online_logical_cores, 1, 1 << 16, 0, 1 << 16);
> ```

What if `online_logical_cores` is not a subset of `possible_logical_cores`? I can't find any checks for this.


<!-- Sent from Reviewable.io -->

2022-01-29 01:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 777 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYN0wVEYUUk6u38uqL:-MuYN0wVEYUUk6u38uqM:bl3ncrd) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L777)):*
> ```C
>     size_t online_logical_cores_cnt = topo_info->online_logical_cores.resource_cnt;
>     size_t possible_logical_cores_cnt = topo_info->possible_logical_cores.resource_cnt;
>     if (online_logical_cores_cnt > possible_logical_cores_cnt) {
> ```

@mkow are you looking for this check?


<!-- Sent from Reviewable.io -->

2022-01-29 01:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 777 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYN0wVEYUUk6u38uqL:-MuYQ4Vh39C1xGEAfblM:b-nh4okt) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L777)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow are you looking for this check?
</blockquote></details>

This check only checks the number of cores, it's not what I was asking about ;)


<!-- Sent from Reviewable.io -->

2022-01-29 01:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 777 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYN0wVEYUUk6u38uqL:-MuYSTOLEcCA1XYWqadp:b-fqbwai) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L777)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This check only checks the number of cores, it's not what I was asking about ;)
</blockquote></details>

OK, you mean if `possible_logical_cores` has a range of `0-8` and `online_logical_cores` has a range of `20-23`? If so, we don't have this check.

Without core offlining support, our assumption is that cores always start with `0` until `online_logical_cores_cnt` which in this example is `4`. So, what will happen is, we will end up getting topology information of cores `0-3`.

Do you think adding such a check might help address any security concerns?


<!-- Sent from Reviewable.io -->

2022-01-29 14:40 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 20 of 21 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 749 at r6](https://reviewable.io/reviews/gramineproject/gramine/355#-MuTDm678pk1DxgsArtW:-MuaFq_n9luBg3IAVRxJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a0b10eeb03f04067b0470e190c6410a4754098a8/Pal/src/host/Linux-SGX/db_main.c#L749)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess I just missed that this is a global variable when writing it or just copied too much code from somewhere where it wasn't obvious that it's a global ¯\\_(ツ)_/¯
It doesn't make sense, so please remove it.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 146 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuXqA3P4Pkv8JDV0lII:-MuaFfQOBRSrjp2vpK4M:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please use `range_arr_size` in both places here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-30 12:43 UTC, mkow requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-Muf-jp94nAEEJ6burcv:bvlseib) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
// migrating the discussion to the proper thread

> Do you think adding such a check might help address any security concerns?

Without this check we expose inconsistent data. Looking at one list you get one thing, and at the other you get another, both contradicting each other.


<!-- Sent from Reviewable.io -->

2022-01-30 16:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MufeFfP15ZC7bmozK7H:b6ej7af) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
Just using the example from the other thread,
>  possible_logical_cores has a range of 0-8 and online_logical_cores has a range of 20-23

On such a compromised system, even if `/sys/devices/system/cpu/online` says `20-23`, when application tries to open `/sys/devices/system/cpu/cpu21/online`, it will fail as `LibOS` maintains the same convention as `trusted PAL` that all cores start at `0` and go up to `online_logical_cores_cnt  - 1`.

```
if (pseudo_parse_ulong(&name[prefix_len], **total - 1**, &n) < 0)
   return -ENOENT;
```

Regarding inconsistent view between `untrusted host` and `SGX`, we anyway don't care because the untrusted host can modify any information. Also, we don't have checkpointing and restoring topology info yet, which can lead to each enclave having a different view of the topology.

If you want, I can add this check but based on Gitter chat looks like you already have a proposal for this and plan to push a commit. So, I will hold off from pushing any changes.


<!-- Sent from Reviewable.io -->

2022-01-30 17:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MufySMCC7DJAfvR571u:b-j4xlvp) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
I think I'm missing something, if we allow CPUs to be only from 0 to `online_logical_cores_cnt - 1` then why do we even store `/sys/devices/system/cpu/online` as ranges? It always has to be just a single range, from 0 to `online_logical_cores_cnt - 1`, the we can just not store this redundant information at all?

> Regarding inconsistent view between untrusted host and SGX, [...]

Yes, that's right, but that's not my point, my point is about internal inconsistencies between the data we expose to the app.

> If you want, I can add this check but based on Gitter chat looks like you already have a proposal for this and plan to push a commit. So, I will hold off from pushing any changes.

Yes, I'll do this to speed things up for the release, but there are many things I don't understand here, so please watch discussions under this PR :)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-MufAfXLCWe856USEq44:b-7un2kp) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
> ```C
>     /* Virtual environments such as QEMU may assign each core to a separate socket/package with
>      * one or more NUMA nodes. So we check against the number of online logical cores. */
>     if (!IS_IN_RANGE_INCL(topo_info->sockets_cnt, 1, online_logical_cores_cnt)) {
> ```

Can't you have more sockets than online CPUs? E.g. when all cores from some socket are turned off.


<!-- Sent from Reviewable.io -->

2022-01-30 17:50 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-Mug5npt9N_yYS_Q-ksV:b-x5e7m9) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
> ```C
>          * example: /sys/devices/system/cpu/cpu1/cache/index1/shared_cpu_map: 00000000,00000002 */
>         int ret = sanitize_hw_resource_range(&cache_info_arr[lvl].shared_cpu_map, 1, max_limit, 0,
>                                              online_logical_cores_cnt);
> ```

`cache_info_arr[lvl].shared_cpu_map` is another list which may include non-existing cores


<!-- Sent from Reviewable.io -->

2022-01-30 18:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MugEtb61GkGUV1w1CyO:b-b8b137) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I'm missing something, if we allow CPUs to be only from 0 to `online_logical_cores_cnt - 1` then why do we even store `/sys/devices/system/cpu/online` as ranges? It always has to be just a single range, from 0 to `online_logical_cores_cnt - 1`, the we can just not store this redundant information at all?

> Regarding inconsistent view between untrusted host and SGX, [...]

Yes, that's right, but that's not my point, my point is about internal inconsistencies between the data we expose to the app.

> If you want, I can add this check but based on Gitter chat looks like you already have a proposal for this and plan to push a commit. So, I will hold off from pushing any changes.

Yes, I'll do this to speed things up for the release, but there are many things I don't understand here, so please watch discussions under this PR :)
</blockquote></details>

Sure, please go ahead.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-Mug9yov1YwlQb0fDnBC:bxckj13) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cache_info_arr[lvl].shared_cpu_map` is another list which may include non-existing cores
</blockquote></details>

Yes, we don't check the range subsets/offlined cores.  This was intended for core offlining PR. Currently, we make sure that the range of cores as part of the `share_cpu_map` is not greater than the total `online_logical_cores_cnt`.

For example, if we have shared_cpu_map (LLC) range as `0-31`, and the online cores are `0-8`, then we fail. But if `shared_cpu_map ` were like `0-1, 7-8` (with cores 2-6 non-existing) we don't fail.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-Mug42HU6OKUk76aTe4-:b-pgvg5n) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can't you have more sockets than online CPUs? E.g. when all cores from some socket are turned off.
</blockquote></details>

I don't think the kernel will expose them. I did a quick test on my ICX system which has 2 sockets and each having 32 cores. I offlined all the cores except core 0 and this is the output of `lscpu`. Also, I don't think `sysfs` exposes any path to show the total sockets count. (other tool like `dmidecode` may expose the total socket count but we don't use this)
```
Architecture:         x86_64
CPU op-mode(s):       32-bit, 64-bit
Byte Order:           Little Endian
CPU(s):               64
On-line CPU(s) list:  0
Off-line CPU(s) list: 1-63
Thread(s) per core:   1
Core(s) per socket:   1
Socket(s):            1
NUMA node(s):         2
Vendor ID:            GenuineIntel
CPU family:           6
Model:                106
Model name:           Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
Stepping:             6
CPU MHz:              2200.000
BogoMIPS:             4400.00
Virtualization:       VT-x
L1d cache:            48K
L1i cache:            32K
L2 cache:             1280K
L3 cache:             49152K
NUMA node0 CPU(s):    0
NUMA node1 CPU(s):    
```


<!-- Sent from Reviewable.io -->

2022-01-30 21:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MugnqWB57ysQzhM4-Zz:b-y5i07l) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure, please go ahead.
</blockquote></details>

What about my question?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MugnUD76k14ZQvsE-Kl:b-h0jfz2) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
>  This was intended for core offlining PR.

But I thought the idea was that right now we'll refuse to start if some cores in topology are declared as offlined, not that we'll expose inconsistent data to the app. Especially exposing indexes which point to nothing.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-Mugqapz6EE-2FlfgdDR:bmyo31a) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I don't think the kernel will expose them. I did a quick test on my ICX system which has 2 sockets and each having 32 cores. I offlined all the cores except core 0 and this is the output of `lscpu`. Also, I don't think `sysfs` exposes any path to show the total sockets count. (other tool like `dmidecode` may expose the total socket count but we don't use this)
```
Architecture:         x86_64
CPU op-mode(s):       32-bit, 64-bit
Byte Order:           Little Endian
CPU(s):               64
On-line CPU(s) list:  0
Off-line CPU(s) list: 1-63
Thread(s) per core:   1
Core(s) per socket:   1
Socket(s):            1
NUMA node(s):         2
Vendor ID:            GenuineIntel
CPU family:           6
Model:                106
Model name:           Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
Stepping:             6
CPU MHz:              2200.000
BogoMIPS:             4400.00
Virtualization:       VT-x
L1d cache:            48K
L1i cache:            32K
L2 cache:             1280K
L3 cache:             49152K
NUMA node0 CPU(s):    0
NUMA node1 CPU(s):    
```

</blockquote></details>

I see, thanks for checking, seems they are indeed hidden. But other interesting thing is that the node1 cpu list is empty, so we should allow empty ranges?


<!-- Sent from Reviewable.io -->

2022-01-30 22:03 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-Muh-eOI0qdzggv4hCr5:blsuf5v) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
> ```objc
> struct pal_numa_topo_info {
>     struct pal_res_range_info cpumap;
>     struct pal_res_range_info distance;
> ```

What does this represent? I think on Linux it's not a list of ranges, but a list of integers? (distances to each other node)


<!-- Sent from Reviewable.io -->

2022-01-31 00:54 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MuhUcE_0xvubH4aJhC3:bo0vo56) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does this represent? I think on Linux it's not a list of ranges, but a list of integers? (distances to each other node)
</blockquote></details>

Actually, this field almost completely lacks sanitization, the only thing which is sanitized is `resource_cnt` field, which is a self-declared (not verified with the list of ranges) sum of the ranges which has to equal to `online_nodes_cnt`. Everything else can be arbitrary.
That's why it passes the tests... I was wondering how it's even possible that the tests are passing despite the ranges being unsorted here (that's the case now on my server).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 601 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MuhaOIyBQ_QgYmD568Z:-MuhaOIyBQ_QgYmD568_:bk980m6) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L601)):*
> ```C
>     }
> 
>     if (total_cores_in_numa != online_logical_cores_cnt) {
> ```

That's not enough, this sanitization misses verification against online and possible cores list. Non-existent indices will pass it.


<!-- Sent from Reviewable.io -->

2022-01-31 02:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MuhjXJ12OvMu2gSSkAv:b-cmd6rz) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, this field almost completely lacks sanitization, the only thing which is sanitized is `resource_cnt` field, which is a self-declared (not verified with the list of ranges) sum of the ranges which has to equal to `online_nodes_cnt`. Everything else can be arbitrary.
That's why it passes the tests... I was wondering how it's even possible that the tests are passing despite the ranges being unsorted here (that's the case now on my server).
</blockquote></details>

yes, these are integers like `10 20` or `20 10` basically denoting the numa distances. Unlike other ranges like `core_siblings` we don't call `sanitize_hw_resource_range()` to sanitize this. This is because `distance` can vary from system to system. All we want is to store the distance count. But again, this will raise the question of why store in `pal_res_range_info` type.  It is because I wanted to use a common function like `get_hw_resource_range()` to read from the untrusted host which only returns a value of `pal_res_range_info` type.

Other fields like `ranges_cnt` and `ranges_arr` are don't care as far as distance is concerned.

This isn't a range although it is stored in `pal_res_range_info`. So, it will be treated as individual values instead of range and can be unsorted.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-Muht6T800Nm5KyRjUW_:bv6gynd) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about my question?
</blockquote></details>

Sorry missed it, this was done to create the bare bones for supporting core offlining. I didn't want to keep changing the architecture.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MuhnMt678HnNX9hdWMs:byx206t) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  This was intended for core offlining PR.

But I thought the idea was that right now we'll refuse to start if some cores in topology are declared as offlined, not that we'll expose inconsistent data to the app. Especially exposing indexes which point to nothing.
</blockquote></details>

This case typically arises when cores are offline right, and as you pointed out, it might not lead to inconsistent data but maybe a performance issue. So, this was left until we have proper core offlining support.

We check `resource_cnt` and `range_cnt` are not `0` for `shared_cpu_map`. So, we will not have empty indexes but missing cores. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 601 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MuhaOIyBQ_QgYmD568Z:-Muhrg_J2j97t2SWz_6J:b-tg7fvo) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L601)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not enough, this sanitization misses verification against online and possible cores list. Non-existent indices will pass it.
</blockquote></details>

Yes, we should add a range subset check which will ensure that each core in `numa node` is a subset of `online_cores`. Since we are planning to add `online_logical_cores` being a subset of `possible_logical_cores` check, the above should be good.

I think if we add a single function to check if one range is a subset of another, we could use it for all these cases.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-MuhtlAH7Fpndbxn3-Z2:b-2frwb) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I see, thanks for checking, seems they are indeed hidden. But other interesting thing is that the node1 cpu list is empty, so we should allow empty ranges?
</blockquote></details>

yes, we can change the limits when we call `sanitize_hw_resource_range()` and also need to tweak this function to add a special check for `numa` which can have empty `range_cnt`. But again, let us keep this for core offlining PR.


<!-- Sent from Reviewable.io -->

2022-01-31 02:51 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MuhzGfj41Jty_E14ay2:b-jhdmh4) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, these are integers like `10 20` or `20 10` basically denoting the numa distances. Unlike other ranges like `core_siblings` we don't call `sanitize_hw_resource_range()` to sanitize this. This is because `distance` can vary from system to system. All we want is to store the distance count. But again, this will raise the question of why store in `pal_res_range_info` type.  It is because I wanted to use a common function like `get_hw_resource_range()` to read from the untrusted host which only returns a value of `pal_res_range_info` type.

Other fields like `ranges_cnt` and `ranges_arr` are don't care as far as distance is concerned.

This isn't a range although it is stored in `pal_res_range_info`. So, it will be treated as individual values instead of range and can be unsorted.
</blockquote></details>

What if untrusted PAL sets the ranges to something where `start != end`? I think you'll print output in invalid format in `/sys/devices/system/node/node<n>/distance`?
Also, I really dislike this hack, i.e. "recycling" structures for something completely different than they were intended to. Here we just want a list of integers, so we should use a list of integers.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-Mui0w6zDF7CIxQipE6W:b2jmkal) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry missed it, this was done to create the bare bones for supporting core offlining. I didn't want to keep changing the architecture.
</blockquote></details>

But right now we allow `online_logical_cores` ranges which are different than `[0; online_logical_cores_cnt)]`? So, such ranges pass sanitization but are actually unsupported and cause a lot of inconsistencies.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-Mui-_nF7BgQbhwwDoEB:b443cok) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
> as you pointed out, it might not lead to inconsistent data but maybe a performance issue

I didn't say this. I said that right now we allow inconsistent data, e.g. containing invalid core indices.

> We check `resource_cnt` and `range_cnt` are not `0` for `shared_cpu_map`. So, we will not have empty indexes but missing cores.

I didn't say empty (and btw, `0` is not "empty", "0" is just a zero index), I said indices pointing nowhere - e.g. indices which doesn't point to any core.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 601 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MuhaOIyBQ_QgYmD568Z:-Mui0X0u3BVX8_MlMI3Z:b-ng5e9p) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L601)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we should add a range subset check which will ensure that each core in `numa node` is a subset of `online_cores`. Since we are planning to add `online_logical_cores` being a subset of `possible_logical_cores` check, the above should be good.

I think if we add a single function to check if one range is a subset of another, we could use it for all these cases.
</blockquote></details>

Yup, I think it will solve at least this specific issue.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-Mui1cjp7WDjDpeeMYRc:bjxtfd4) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, we can change the limits when we call `sanitize_hw_resource_range()` and also need to tweak this function to add a special check for `numa` which can have empty `range_cnt`. But again, let us keep this for core offlining PR.
</blockquote></details>

Why not just accept empty ranges?


<!-- Sent from Reviewable.io -->

2022-01-31 04:04 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MuiGUV54dBc7AKy5tRk:bhfzrjl) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not yet, I'm still verifying the sanitization and checks in the trusted part.
</blockquote></details>

@mkow I have captured the following changes:
1. Check`online_logical_cores` is a subset of `possible_logical_cores`.
2. Check `shared_cpu_map` is a subset of `online_logical_cores`.
3. Check cores in each numa node is a subset of `online_logical_cores`.
4. Change numa distance type from `pal_res_range_info` to `list of integers`
5. Allow empty numa nodes but I still prefer to fail for this case. 

I'm not sure if you already have these changes, but if not please do let me know. I can get started and have something for you to review by tomorrow morning.

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MuiArs41vcFRNNGi3a-:b2xvp7d) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
> What if untrusted PAL sets the ranges to something where start != end? I think you'll print output in invalid format in /sys/devices/system/node/node<n>/distance?

Yes, you are correct, we will print invalid format.

> Also, I really dislike this hack, i.e. "recycling" structures for something completely different than they were intended to. Here we just want a list of integers, so we should use a list of integers.

I can clean this up and have it as a list of integers. This will also solve the invalid printing format.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-Mui5at57QhTeVkLLnqP:br4jtgu) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But right now we allow `online_logical_cores` ranges which are different than `[0; online_logical_cores_cnt)]`? So, such ranges pass sanitization but are actually unsupported and cause a lot of inconsistencies.
</blockquote></details>

I think we agreed that for this issue we need to add `online_logical_cores` being a subset of `possible_logical_cores` check. In addition, I suggest we also have a check for `possible_logical_cores` such that we only allow `range_cnt` to be 1 and the `ranges_arr` always start from `0` until `max cores`.

PS: `possible_logical_cores` will only have `0-max cores` even if we offline cores. So `resource_cnt` will be `n` cores, `range_cnt` will be `1` and `range_arr` will only have one range starting from `0` until `max cores`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MuiCCScDKbDQ2Jyi0V9:b-6dviwm) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
> I didn't say this. I said that right now we allow inconsistent data, e.g. containing invalid core indices.

True :) I interpreted it incorrectly. Typically applications don't check if a cpu shares a cache or not. It will end up using this inconsistent data, with the downside being performance due to incorrect `cpu<->cache` mapping.  Here again, if we make sure `shared_cpu_map` is a subset of `online_logical_cores` we can make sure the data is consistent. But even with such a check, the attacker can make `share_cpu_map` a subset of `online_logical_cores` but map different caches to different cores which will still cause performance issues.

> I didn't say empty (and btw, 0 is not "empty", "0" is just a zero index), I said indices pointing nowhere - e.g. indices which doesn't point to any core.

It can't be indices that don't point to any core as we create a bitmap from the `range_arr`. So, an index if set will either point to a core that truly shares the cache or point to a core that doesn't share the cache (compromised system) or that core is not for that cache.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-Mui7onL2-CR1Pm5rlxH:b-blmbij) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just accept empty ranges?
</blockquote></details>

The numa nodes will only be empty if we offline cores or the attacker has compromised the system. Right now, we don't have proper offlining support to properly validate this case and so I suggested we fail if the numa node is empty. This is the current behavior.


<!-- Sent from Reviewable.io -->

2022-01-31 08:36 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-01-31 14:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MukR2tS95ltlTjU-urq:b93kka) (no related file):*
> I started working on this and will try to solve at least some of the issues. We discussed this with maintainers and will just merge what we have (because it's still much better than the old code) but will need to keep it under the insecure/experimental flag until we make sure that everything is really validated.

OK, sounds good. So, do you want me to merge the fixups and rebase them to the latest master? or do you have some changes to push?

> And these issues are probably not everything, I still keep finding issues and it's quite hard to tell from the current implementation whether everything is already consistent or not. I'll try to change the code/structures to make verification part simpler and easier to prove.

Sure, we can keep the discussions active.

---
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MukTNzh1f9EEOo3MTH7:b-5imhow) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure if that's enough: you trim the range in sysfs printing to `[0; online_logical_cores_cnt)`but in sanitization allow other ranges as well. So, effectively we'll expose the more complex ranges (visible e.g. in counts of resources) but will trim the available info in cpu directory to `ranges SET-AND [0; online_logical_cores_cnt)`.
</blockquote></details>

Can you please give an example of the failure case? It will be easier to understand your case.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MukSxiw7zhTq1HHVGiy:bmm1nbj) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> It will end up using this inconsistent data, with the downside being performance

or memory corruption, depending on the app's implementation.

Performance is not an issue, the host can always deny resources.

> It can't be indices that don't point to any core as we create a bitmap from the `range_arr`. So, an index if set will either point to a core that truly shares the cache or point to a core that doesn't share the cache (compromised system) or that core is not for that cache.

But where do we verify that `cache_info_arr[lvl].shared_cpu_map` contains only valid indices?
</blockquote></details>

I don't think we can verify this without reading CPUID leaf `0x4` on each core.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-MukOpGsBDnozzL27UaY:br127oe) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
> There's no "compromised system" here, the host owner is the attacker.

By "compromised system", I mean the integrity of the system is lost. It could be due to an attacker who could be a host owner or not.

> I don't think there will be anything in the current sanitization that breaks if we remove this check.

How do we differentiate the case where the attacker has willfully tampered and made the node empty Vs truly empty due to offlined cores? Might again lead to inconsistent data?


<!-- Sent from Reviewable.io -->

2022-01-31 15:36 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-MukdhErAmWnmgUtvdX5:ba7jw9q) (no related file):*
> OK, sounds good. So, do you want me to merge the fixups and rebase them to the latest master? or do you have some changes to push?

I have some changes which I'm still working on, but I can submit them as a follow-up PR, this code is behind the "experimental" flag, so it should be fine to merge the non-polished version for now.

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MukkgSf0pDWKi38JKZg:bw8elzg) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> What if untrusted PAL sets the ranges to something where start != end? I think you'll print output in invalid format in /sys/devices/system/node/node<n>/distance?

Yes, you are correct, we will print invalid format.

> Also, I really dislike this hack, i.e. "recycling" structures for something completely different than they were intended to. Here we just want a list of integers, so we should use a list of integers.

I can clean this up and have it as a list of integers. This will also solve the invalid printing format.
</blockquote></details>

I'll do it in a separate PR.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MukfepuA4w4gieiaD5G:bo0u3cg) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can you please give an example of the failure case? It will be easier to understand your case.
</blockquote></details>

`online_logical_cores = [[0, 1], [5,6]]` and `online_logical_cores_cnt = 4`, the structures in PAL will say that  there are 4 CPUs, but sysfs will show only two of them? Or maybe I'm missing something? Actually, don't you have 2 different numbering for cores? I.e. a different one in ranges and a different one in path component names? (i.e. "cpu<n>").
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MukeMWe5Dn0wGCLX1Vq:bo7ziu4) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I don't think we can verify this without reading CPUID leaf `0x4` on each core.
</blockquote></details>

By "valid" I meant "consistent with other information we present to the app", e.g. the list of online CPUs.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-MukkzqH7Ho8onQHgM3q:b34pqz8) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
> By "compromised system", I mean the integrity of the system is lost. It could be due to an attacker who could be a host owner or not.

We don't assume any integrity of the host, there's nothing to be "lost".

> How do we differentiate the case where the attacker has willfully tampered and made the node empty Vs truly empty due to offlined cores? Might again lead to inconsistent data?

No, why would it have to lead to inconsistent data? We fully control what we present to the application, we can make it fully consistent.


<!-- Sent from Reviewable.io -->

2022-01-31 18:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: 12 of 21 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDexfA267TAGLqYpVS:-Mukuiqg2oeFPuUW3VuI:bzbb4x2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> OK, sounds good. So, do you want me to merge the fixups and rebase them to the latest master? or do you have some changes to push?

I have some changes which I'm still working on, but I can submit them as a follow-up PR, this code is behind the "experimental" flag, so it should be fine to merge the non-polished version for now.
</blockquote></details>

Rebased to the latest master and pushed the changes.

---
___
*[-- commits, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/355#-MuDbuOk0VO1Oq3s0qtJ):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks better.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 82 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Muh-eOI0qdzggv4hCr4:-MukvEoSBOSNWoepHPRi:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/include/arch/x86_64/pal_topology.h#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'll do it in a separate PR.
</blockquote></details>

OK.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MulBcoF7VrMS3OLuSg9:bp8x9qw) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*

> I think we agreed that for this issue we need to add online_logical_cores being a subset of possible_logical_cores check. In addition, I suggest we also have a check for possible_logical_cores such that we only allow range_cnt to be 1 and the ranges_arr always start from 0 until max cores.
PS: possible_logical_cores will only have 0-max cores even if we offline cores. So resource_cnt will be n cores, range_cnt will be 1 and range_arr will only have one range starting from 0 until max cores.

With the above changes, and `online_logical_cores = [[0, 1], [5,6]]` shouldn't gramine start up fail as `possible_logical_cores_cnt > online_logical_cores_cnt`?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 401 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-Mug5nps7fD9rY3tMi6a:-MukvHaA2qyJSwT1s5iQ:b-e0catg) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L401)):*
OK, that we can make sure by checking the list of cores that are part of `share_cpu_map` is a subset of `online_logical_cores`. This we already established right? 

> But even with such a check, the attacker can make share_cpu_map a subset of online_logical_cores but map different caches to different cores which will still cause performance issues.

This we cannot verify without proper `cpuid` checks.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 601 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MuhaOIyBQ_QgYmD568Z:-MulEWoPC9NDrQdEYQLM:b2nhktp) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L601)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I think it will solve at least this specific issue.
</blockquote></details>

OK.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 798 at r10](https://reviewable.io/reviews/gramineproject/gramine/355#-MufAfXK5bz2zxarhjd5:-MulAsoa6wd497uM3MJ_:brciglk) ([raw file](https://github.com/gramineproject/gramine/blob/9c491f4c8be602ec2920eaec39ff7b12c81492c7/Pal/src/host/Linux-SGX/db_main.c#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> By "compromised system", I mean the integrity of the system is lost. It could be due to an attacker who could be a host owner or not.

We don't assume any integrity of the host, there's nothing to be "lost".

> How do we differentiate the case where the attacker has willfully tampered and made the node empty Vs truly empty due to offlined cores? Might again lead to inconsistent data?

No, why would it have to lead to inconsistent data? We fully control what we present to the application, we can make it fully consistent.
</blockquote></details>

yes, I take back, there wouldn't be inconsistent data.  We can add this check.


<!-- Sent from Reviewable.io -->

2022-01-31 18:46 UTC, mkow commented
Jenkins, retest this please

2022-01-31 18:57 UTC, dimakuv commented
@vijaydhanraj Jenkins fails like this:
```
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../Pal/src/host/Linux-common/topo_info.c: In function ‘get_core_topo_info’:
../Pal/src/host/Linux-common/topo_info.c:334:50: error: ‘/online’ directive output may be truncated writing 7 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  334 |             snprintf(filename, sizeof(filename), "%s/online", dirname);
      |                                                  ^~~~~~~~~~~
../common/include/api_fortified.h:54:86: note: in definition of macro ‘snprintf’
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |                                                                                      ^~~
../Pal/src/host/Linux-common/topo_info.c:334:53: note: format string is defined here
  334 |             snprintf(filename, sizeof(filename), "%s/online", dirname);
      |                                                     ^~~~~~~
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../common/include/api_fortified.h:54:5: note: ‘__builtin___snprintf_chk’ output between 8 and 135 bytes into a destination of size 128
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:334:13: note: in expansion of macro ‘snprintf’
  334 |             snprintf(filename, sizeof(filename), "%s/online", dirname);
      |             ^~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:345:46: error: ‘/topology/core_id’ directive output may be truncated writing 17 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  345 |         snprintf(filename, sizeof(filename), "%s/topology/core_id", dirname);
      |                                              ^~~~~~~~~~~~~~~~~~~~~
../common/include/api_fortified.h:54:86: note: in definition of macro ‘snprintf’
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |                                                                                      ^~~
../Pal/src/host/Linux-common/topo_info.c:345:49: note: format string is defined here
  345 |         snprintf(filename, sizeof(filename), "%s/topology/core_id", dirname);
      |                                                 ^~~~~~~~~~~~~~~~~
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../common/include/api_fortified.h:54:5: note: ‘__builtin___snprintf_chk’ output between 18 and 145 bytes into a destination of size 128
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:345:9: note: in expansion of macro ‘snprintf’
  345 |         snprintf(filename, sizeof(filename), "%s/topology/core_id", dirname);
      |         ^~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:350:46: error: ‘/topology/core_siblings_list’ directive output may be truncated writing 28 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  350 |         snprintf(filename, sizeof(filename), "%s/topology/core_siblings_list", dirname);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/include/api_fortified.h:54:86: note: in definition of macro ‘snprintf’
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |                                                                                      ^~~
../Pal/src/host/Linux-common/topo_info.c:350:49: note: format string is defined here
  350 |         snprintf(filename, sizeof(filename), "%s/topology/core_siblings_list", dirname);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../common/include/api_fortified.h:54:5: note: ‘__builtin___snprintf_chk’ output between 29 and 156 bytes into a destination of size 128
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:350:9: note: in expansion of macro ‘snprintf’
  350 |         snprintf(filename, sizeof(filename), "%s/topology/core_siblings_list", dirname);
      |         ^~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:355:46: error: ‘/topology/thread_siblings_list’ directive output may be truncated writing 30 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  355 |         snprintf(filename, sizeof(filename), "%s/topology/thread_siblings_list", dirname);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/include/api_fortified.h:54:86: note: in definition of macro ‘snprintf’
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |                                                                                      ^~~
../Pal/src/host/Linux-common/topo_info.c:355:49: note: format string is defined here
  355 |         snprintf(filename, sizeof(filename), "%s/topology/thread_siblings_list", dirname);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../common/include/api_fortified.h:54:5: note: ‘__builtin___snprintf_chk’ output between 31 and 158 bytes into a destination of size 128
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:355:9: note: in expansion of macro ‘snprintf’
  355 |         snprintf(filename, sizeof(filename), "%s/topology/thread_siblings_list", dirname);
      |         ^~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:360:46: error: ‘/topology/physical_package_id’ directive output may be truncated writing 29 bytes into a region of size between 1 and 128 [-Werror=format-truncation=]
  360 |         snprintf(filename, sizeof(filename), "%s/topology/physical_package_id", dirname);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/include/api_fortified.h:54:86: note: in definition of macro ‘snprintf’
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |                                                                                      ^~~
../Pal/src/host/Linux-common/topo_info.c:360:49: note: format string is defined here
  360 |         snprintf(filename, sizeof(filename), "%s/topology/physical_package_id", dirname);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../common/include/api.h:446,
                 from ../Pal/src/host/Linux-common/topo_info.c:14:
../common/include/api_fortified.h:54:5: note: ‘__builtin___snprintf_chk’ output between 30 and 157 bytes into a destination of size 128
   54 |     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Pal/src/host/Linux-common/topo_info.c:360:9: note: in expansion of macro ‘snprintf’
  360 |         snprintf(filename, sizeof(filename), "%s/topology/physical_pa [...]

2022-01-31 22:19 UTC, mkow commented
Jenkins, retest this please

2022-01-31 22:20 UTC, vijaydhanraj commented
Thanks @dimakuv, tested with GCC 9.4 and was able to reproduce this issue. Fixed it now.
Thanks @mkow for restarting the tests.

2022-01-31 22:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MumDdvR3v5AWH1lkap1:bnh0cap) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we can set `possible_logical_cores_cnt` to something large? I didn't even use it in the example above.
</blockquote></details>

I mean without core offlining `online_logical_core_cnt` should be equal to `possible_logical_cores_cnt`. So, if we have holes in `online_logical_cores` as you mentioned in your example, it should fail.


<!-- Sent from Reviewable.io -->

2022-01-31 22:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MumG3p7DL-Omdhhq1xB:b-q757n5) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I mean without core offlining `online_logical_core_cnt` should be equal to `possible_logical_cores_cnt`. So, if we have holes in `online_logical_cores` as you mentioned in your example, it should fail.
</blockquote></details>

But we don't have such a check and I think we only discussed checking if `online_logical_core_cnt` is a subset of `possible_logical_cores_cnt`, not checking for equality.


<!-- Sent from Reviewable.io -->

2022-01-31 22:45 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MumGazDEo7bTciYjQDh:bkk0jd2) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we don't have such a check and I think we only discussed checking if `online_logical_core_cnt` is a subset of `possible_logical_cores_cnt`, not checking for equality.
</blockquote></details>

We already have this `possible_logical_cores_cnt > online_logical_cores_cnt` which will catch the example you showed. But we should change this to equality check until proper core offlining support is added. 


<!-- Sent from Reviewable.io -->

2022-01-31 23:27 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 769 at r9](https://reviewable.io/reviews/gramineproject/gramine/355#-MuYBu0BAMCUG7jJ7kWk:-MumSHMsCRsTDNTtk7zJ:b8umfco) ([raw file](https://github.com/gramineproject/gramine/blob/b2ccb9b4fb97d1bc19102ad32b20c5a2df84bcab/Pal/src/host/Linux-SGX/db_main.c#L769)):*
> We already have this `possible_logical_cores_cnt > online_logical_cores_cnt` which will catch the example you showed.

It won't, my example allows specifying more possible cores, so that this check passes.

> But we should change this to equality check until proper core offlining support is added.

Better to just check for equality of both lists. But we can do this later.


<!-- Sent from Reviewable.io -->

2022-02-01 07:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10, 2 of 9 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/355)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-01 07:49 UTC, merged