[LibOS] Add UID and GID to manifest
gramineproject/gramine pull request #37
Opened 2021-09-14 10:30 UTC by dzygann

This implementation enables Gramine to run an executable with another user than root.
This becomes very handy in case of executables, which shouldn't run with the root user.
The implementation of this feature sets also the effective uid/gid to the value,
which is defined in the manifest for the directive loader.uid/gid

This topic has been discussed in the issue [2632](https://github.com/gramineproject/graphene/issues/2632)

Signed-off-by: Denis Zygann <denis@zygann.de>

2021-09-14 12:06 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dzygann)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ80mVD4A2AddOUEVd):*
Please don't use "enables Gramine", it's a bit misleading. Maybe "allows Gramine to run" ?
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ91tK14CwpAI3q0lR):*
"sets also" -> "also sets"
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ8___5MRg1YaALm7I):*
We generally use backticks (`) to indicate code/manifest/whatever variables, constants etc. So this would be
```
for the directive `loader.uid`/`loader.gid`.
```
___
*[Documentation/manifest-syntax.rst, line 188 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9VsJ2smnoXdHqMrQ:-MjZ9VsJ2smnoXdHqMrR:bs8obat) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L188)):*
> ```reStructuredText
>    (Default: 0)
> 
> This specifies the user/group ID which will be used to run the executable in Gramine.
> ```

This sounds kind of misleading - one might think that these are host-level IDs. Maybe `This specifies the initial, Gramine emulated user/group ID.` ?
___
*[Documentation/manifest-syntax.rst, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9NpPEO-KBpWdIdGV:-MjZ9NpQ9pKFe0SZnKoB:bawb5f6) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L191)):*
> ```reStructuredText
> These specified values are also used for the effective user/group ID. By default the
> executable is running as root user (0). If the value is < 0 Gramine stops with an
> "Invalid Argument" error.
> ```

"Must be positive." would be enough (instead of the last sentence).
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 153 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAN2A2CNR9026GPXB:-MjZAN2A2CNR9026GPXC:b-sdqcrx) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L153)):*
> ```C
>     __atomic_store_n(&g_process.pgid, g_process.pid, __ATOMIC_RELEASE);
> 
>     /* Default user and group ids are `0` and already set. */
> ```

This comment can now be removed.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAVGt15XdG3WE3T3q:-MjZAVGuDvU8B88as8rQ:b-rlvbh2) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L161)):*
> ```C
>         put_thread(cur_thread);
>         return -EINVAL;
>     }
> ```

We need to validate that:
1) `uid_int64` is non negative
2) `uid_int64` is not greater than `IDTYPE_MAX`
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAiTd0MxiDcyRnp6a:-MjZAiTd0MxiDcyRnp6b:bpwcgql) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
> ```C
>         put_thread(cur_thread);
>         return -EINVAL;
>     }
> ```

ditto (for `gid_int64`)
___
*[LibOS/shim/test/regression/test_libos.py, line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZB6JN4UWGDGh6b62O:-MjZB6JN4UWGDGh6b62P:bkd5vq) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/test_libos.py#L109)):*
> ```Python
> 
>     def test_105_uid_and_gid_from_file(self):
>         stdout, _ = self.run_binary(['uid_gid.c'])
> ```

This should be the binary, not source code. How did it even work?
___
*[LibOS/shim/test/regression/uid_gid.c, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBT2q0yhFggcFkgH-:-MjZBT2q0yhFggcFkgH0:blc9cj6) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L4)):*
> ```C
> #include <stdio.h>
> #include <sys/types.h>
> #include <stdlib.h>
> ```

Please sort includes.
___
*[LibOS/shim/test/regression/uid_gid.c, line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZB_3F4pCNAIYCTqHT:-MjZB_3F4pCNAIYCTqHU:b-gh1t8a) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L11)):*
> ```C
>     uid_t euid = geteuid();
> 
>     if(uid != 80085 && euid != 80085) {
> ```

Space after `if`
___
*[LibOS/shim/test/regression/uid_gid.c, line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBfY6ACw9l5i4Az8P:-MjZBfY6ACw9l5i4Az8Q:b-8t3c8i) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L11)):*
> ```C
>     uid_t euid = geteuid();
> 
>     if(uid != 80085 && euid != 80085) {
> ```

This should be `||` not `&&`.
___
*[LibOS/shim/test/regression/uid_gid.c, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBd8VEml11QlGbLUR:-MjZBd8W9LZiIUd364ST:bx4ulrt) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L18)):*
> ```C
>     uid_t egid = getegid();
> 
>     if(gid != 1337 && egid != 1337) {
> ```

ditto (space and `||`)


<!-- Sent from Reviewable.io -->

2021-09-14 12:07 UTC, pwmarcz requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBWIu-N98w0TZ952U:-MjZBWIv450n392yl0Ie:b-91k96u) (no related file):*
Does this influence file owner as reported by Graphene? I think it should, and it's worth mentioning in documentation (and testing in the `uid_gid` test).

---
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAbUL5xOFOdUtDmrq:-MjZAbUL5xOFOdUtDmrr:bja2jhh) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L171)):*
> ```C
>     }
> 
>     cur_thread -> uid = uid_int64;
> ```

No spaces around `->`.
___
*[LibOS/shim/test/regression/manifest.template, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9wZ16fxNiYzy2kcf:-MjZ9wZ16fxNiYzy2kcg:b-prmz3w) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/manifest.template#L6)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> # for uid_gid test
> ```

I think it's better to override uid/gid only for this one binary. Can you create a separate manifest?
___
*[LibOS/shim/test/regression/test_libos.py, line 109 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAJ4K1evazuSK9z7y:-MjZAJ4K1evazuSK9z7z:b-7f1zdb) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/test_libos.py#L109)):*
> ```Python
> 
>     def test_105_uid_and_gid_from_file(self):
>         stdout, _ = self.run_binary(['uid_gid.c'])
> ```

This looks like it won't work: it should be `uid_gid`.

(You can run `make regression` to check if the Python code runs, or `.../Scripts/run-pytest -k test_105` to run this one test through Python).
___
*[LibOS/shim/test/regression/uid_gid.c, line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9HJy4_wRuzdzctGP:-MjZ9HJy4_wRuzdzctGQ:b-afwrad) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L11)):*
> ```C
>     uid_t euid = geteuid();
> 
>     if(uid != 80085 && euid != 80085) {
> ```

1337 is ok, I guess, but I don't think we want values like [80085](https://www.urbandictionary.com/define.php?term=80085) in our code :)

Can you change to something more neutral? 1338 should be ok.


<!-- Sent from Reviewable.io -->

2021-09-14 17:48 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBWIu-N98w0TZ952U:-Mj_PAdk2By7D8WSHgUH:b-acqkj1) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Does this influence file owner as reported by Graphene? I think it should, and it's worth mentioning in documentation (and testing in the `uid_gid` test).
</blockquote></details>

But then again, it's more complicated - we should _probably_ report user-created / mounted files as our uid/gid, and /sys/ as belonging to root, and for /proc/ it depends on the file... so maybe if it's not necessary for #2632, we shouldn't bother?

 What do others think? @dimakuv @mkow @boryspoplawski 

---


<!-- Sent from Reviewable.io -->

2021-09-14 19:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @dzygann, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBWIu-N98w0TZ952U:-Mj_l4Sd-KWNVT7BOzSH:b-mlnuf6) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

But then again, it's more complicated - we should _probably_ report user-created / mounted files as our uid/gid, and /sys/ as belonging to root, and for /proc/ it depends on the file... so maybe if it's not necessary for #2632, we shouldn't bother?

 What do others think? @dimakuv @mkow @boryspoplawski 
</blockquote></details>

Well, this kind of makes no sense in Graphene. We do not check any privileges, have 0 access or capabilities checks, so your app is allowed to do everything, regardless of uids and file ownership. That's why I don't like this approach of changing the UID, but afaik you cannot run postgres otherwise. I don't think there is much point in setting file ownership to process IDs at creation time, after all what application checks file ownership, instead of just trying to open the file?

---


<!-- Sent from Reviewable.io -->

2021-09-15 07:30 UTC, dimakuv requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dzygann, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBWIu-N98w0TZ952U:-MjcHKtIBQ3cn0cKkGi0:b-qw62j4) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, this kind of makes no sense in Graphene. We do not check any privileges, have 0 access or capabilities checks, so your app is allowed to do everything, regardless of uids and file ownership. That's why I don't like this approach of changing the UID, but afaik you cannot run postgres otherwise. I don't think there is much point in setting file ownership to process IDs at creation time, after all what application checks file ownership, instead of just trying to open the file?
</blockquote></details>

I agree with Borys. I would prefer to keep permissions flat (all files can be accessed by the user, whatever its uid/gid is). And make all "change user/group" operations effectively nops. Let's not bother.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcM6ArDiXADfngwbX1:-MjcM6ArDiXADfngwbX2:b-q24buv) (no related file):*
Any particular reason you set `effective user ID/group ID` as well? I guess it's fine, just want to understand the reasoning behind this.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcHmXo5tj-hC_s84LY):*
I would prefer to be even more explicit:
```
[LibOS] Add `loader.uid` and `loader.gid` manifest options
```
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcHzrc-MqNTHqaeZ6q):*
This sentence is a bit too loose :)

I would reword like this: `By default, Gramine uses the root user (uid = gid = 0), which may cause some apps to refuse to run.`
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIQ08-zD9hX40FIe4):*
The sentence is too verbose. Simply: `We also set effective UID/GID to the same value as UID/GID respectively.`

Whatever modification to your sentence you choose, please don't use the word `directive` -- we use `manifest option` instead.
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIcLTDBIbld6JxfBz):*
Also, you forgot the dot at the end.
___
*[Documentation/manifest-syntax.rst, line 179 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcInEh-yow00vrW5DV:-MjcInEh-yow00vrW5DW:b2tq5tg) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L179)):*
> ```reStructuredText
> precedence.
> 
> Add User ID and Group ID
> ```

Please remove `Add`
___
*[Documentation/manifest-syntax.rst, line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIwTq6ZTgjTa5eCMC:-MjcIwTq6ZTgjTa5eCMD:b-tz99eo) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L190)):*
> ```reStructuredText
> This specifies the user/group ID which will be used to run the executable in Gramine.
> These specified values are also used for the effective user/group ID. By default the
> executable is running as root user (0). If the value is < 0 Gramine stops with an
> ```

`is running` -> `runs`

`(0)` -> `(uid = gid = 0)`
___
*[Documentation/manifest-syntax.rst, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9NpPEO-KBpWdIdGV:-MjcJ30GEXhHL0Qdr9yA:bv698l9) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L191)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

"Must be positive." would be enough (instead of the last sentence).
</blockquote></details>

+1 to Borys's suggestion, but better "Must be non-negative."
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAbUL5xOFOdUtDmrq:-MjcJSGPAolecTeaB15G:b-kvka8) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L171)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No spaces around `->`.
</blockquote></details>

Wait, how did this even compile?

UPDATE: Ok, apparently this is allowed in C. But anyway, please change.
___
*[LibOS/shim/test/regression/manifest.template, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9wZ16fxNiYzy2kcf:-MjcKq6h0zOOVgpl4WlL:bldpiz) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/manifest.template#L6)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think it's better to override uid/gid only for this one binary. Can you create a separate manifest?
</blockquote></details>

+1 to Pawel's suggestion
___
*[LibOS/shim/test/regression/test_libos.py, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcLIz-EkbhD-p_VBUV:-MjcLIz-EkbhD-p_VBUW:b-r1piar) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/test_libos.py#L108)):*
> ```Python
>             os.remove('env_test_input')
> 
>     def test_105_uid_and_gid_from_file(self):
> ```

`_from_file` suffix is not needed here, just remove this suffix
___
*[LibOS/shim/test/regression/uid_gid.c, line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9HJy4_wRuzdzctGP:-MjcLXQp4Gw3xNgvGyat:b-hxhaj) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L11)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

1337 is ok, I guess, but I don't think we want values like [80085](https://www.urbandictionary.com/define.php?term=80085) in our code :)

Can you change to something more neutral? 1338 should be ok.
</blockquote></details>

+1, definitely no `80085`. I prefer `42` and `24`, but whatever magic numbers you choose, they should be not offensive :)
___
*[LibOS/shim/test/regression/uid_gid.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcLqhU-syHy9ea98Gq:-MjcLqhU-syHy9ea98Gr:b-f4e6xy) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L12)):*
> ```C
> 
>     if(uid != 80085 && euid != 80085) {
>         errx(EXIT_FAILURE, "UID is not equal to the value in the the manifest");
> ```

`UID is not equal to the value...` -> `UID/effective UID are not equal to the value...`
___
*[LibOS/shim/test/regression/uid_gid.c, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcLzfyDh_d3looSqQY:-MjcLzfyDh_d3looSqQZ:bxt8o1w) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/uid_gid.c#L19)):*
> ```C
> 
>     if(gid != 1337 && egid != 1337) {
>         errx(EXIT_FAILURE, "GID is not equal to the value in the the manifest");
> ```

`GID is not equal to the value...` -> `GID/effective GID are not equal to the value...`


<!-- Sent from Reviewable.io -->

2021-09-15 09:10 UTC, pwmarcz reviewed
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dzygann, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZBWIu-N98w0TZ952U:-MjchYVJAX37biWCgIEp:b-7ph1rs) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Borys. I would prefer to keep permissions flat (all files can be accessed by the user, whatever its uid/gid is). And make all "change user/group" operations effectively nops. Let's not bother.
</blockquote></details>

OK, thanks. Resolving, no need to do anything here.

---


<!-- Sent from Reviewable.io -->

2021-09-15 19:08 UTC, dzygann commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcM6ArDiXADfngwbX1:-MjeJHKg-xSkMZCXC5mU:b-jv376v) (no related file):*
> particular reason you set effective user ID/group ID as well?

Yes, I have tested the change with the Postgres DB. It was complaining that I still trying to run it with the root user. After changing also the effective ID's the error disappeared. 

---


<!-- Sent from Reviewable.io -->

2021-09-15 21:37 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @dzygann, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfMFNC74hwYpjHlUvK:-MjfMFNC74hwYpjHlUvL:bcw5fho) (no related file):*
Please do not amend/force push in the middle of the review. `git` has a nice `--fixup` option, please use it :) For the future, also do not rebase, it will be done before merging (squash all fixups + rebase).
Also when you fix some review commends, please respond on reviewable; it has a nice "Done." button you can press, if you just did what reviewer asked for (otherwise, please just respond).

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
`is can be` ?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNP9V1iSWPo441dE8:-MjfNP9V1iSWPo441dE9:b-177m7t) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/src/bookkeep/shim_thread.c#L170)):*
> ```C
> 
>     if (uid_int64 < 0 || uid_int64 > IDTYPE_MAX || gid_int64 < 0 || gid_int64 > IDTYPE_MAX) {
>         log_error("UID or GID is either < 0 or > %u", IDTYPE_MAX);
> ```

Nitpick: would be helpful to print which one does not pass the validation and print it's value.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-MjfNyzoEsx8nsOMGSOu:b6e9nun) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"
> loader.insecure__use_cmdline_argv = true
> ```

We do not use `argv` in this test so this is not needed. You will need to add `argv0` override though.


<!-- Sent from Reviewable.io -->

2021-09-16 02:25 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 7 of 8 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfMFNC74hwYpjHlUvK:-MjgLp2k8womjUzITLpQ:b-m5s4kg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please do not amend/force push in the middle of the review. `git` has a nice `--fixup` option, please use it :) For the future, also do not rebase, it will be done before merging (squash all fixups + rebase).
Also when you fix some review commends, please respond on reviewable; it has a nice "Done." button you can press, if you just did what reviewer asked for (otherwise, please just respond).
</blockquote></details>

Hi,
thanks for the hints. I didn't know the fixup feature in git and I'm not familiar with reviewable, but I will :)
Regarding the fixup approach, I can see that there is a hash before the fixup keyword. I can't see it on my local machine. Is it correct or did I screw up something?

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcHmXo5tj-hC_s84LY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to be even more explicit:
```
[LibOS] Add `loader.uid` and `loader.gid` manifest options
```
</blockquote></details>

Done.
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ80mVD4A2AddOUEVd):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please don't use "enables Gramine", it's a bit misleading. Maybe "allows Gramine to run" ?
</blockquote></details>

Changed to allows Gramine to run..
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcHzrc-MqNTHqaeZ6q):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence is a bit too loose :)

I would reword like this: `By default, Gramine uses the root user (uid = gid = 0), which may cause some apps to refuse to run.`
</blockquote></details>

Done.
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ91tK14CwpAI3q0lR):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

"sets also" -> "also sets"
</blockquote></details>

Done.
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ8___5MRg1YaALm7I):*
> y use backticks (`) to ind
Ok
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIQ08-zD9hX40FIe4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The sentence is too verbose. Simply: `We also set effective UID/GID to the same value as UID/GID respectively.`

Whatever modification to your sentence you choose, please don't use the word `directive` -- we use `manifest option` instead.
</blockquote></details>

Done.
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIcLTDBIbld6JxfBz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, you forgot the dot at the end.
</blockquote></details>

Done.
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`is can be` ?
</blockquote></details>

Done.
___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/37#-MjgO9A20C0NRpBKClu0):*
Is this right with the hash before the fixup keyword?
___
*[Documentation/manifest-syntax.rst, line 179 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcInEh-yow00vrW5DV:-MjgOGC_Bcwr9Zv7B--H:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Add`
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 188 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9VsJ2smnoXdHqMrQ:-MjgOIQK31PQntakbY6H:bzgrikw) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L188)):*
> ounds kind of misleading - one might th
Done.
___
*[Documentation/manifest-syntax.rst, line 190 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcIwTq6ZTgjTa5eCMC:-MjgOK210dHBrKqUTFf-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`is running` -> `runs`

`(0)` -> `(uid = gid = 0)`
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 191 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZ9NpPEO-KBpWdIdGV:-MjgOPA82PAbz4A-monl:b-nf13t6) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/Documentation/manifest-syntax.rst#L191)):*
> Must be non-negative.
Changed to "Must be non-negative."
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 153 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAN2A2CNR9026GPXB:-MjgOSXgE8Q1A9bcNhmo:b-s4xxc8) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L153)):*
> is comment can now
Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 161 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAVGt15XdG3WE3T3q:-MjgOUAW1yQ8h-GHKqze:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to validate that:
1) `uid_int64` is non negative
2) `uid_int64` is not greater than `IDTYPE_MAX`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAiTd0MxiDcyRnp6a:-MjgPFpp1oDtHp4esosI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (for `gid_int64`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 171 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAbUL5xOFOdUtDmrq:-MjgPOGw0eHB25TkgJdj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, how did this even compile?

UPDATE: Ok, apparently this is allowed in C. But anyway, please change.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 108 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcLIz-EkbhD-p_VBUV:-MjgPib828T6EcHxV453:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/test/regression/test_libos.py#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote… [...]

2021-09-16 03:37 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 6 of 8 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNP9V1iSWPo441dE8:-MjgXOIO7z24v0rcIUW2:b-wbg0z4) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/src/bookkeep/shim_thread.c#L170)):*
> uld be helpful to print which o
Is this okay? 
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-MjgfWlV3mwZnGHJayq3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We do not use `argv` in this test so this is not needed. You will need to add `argv0` override though.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-16 08:12 UTC, dimakuv requested changes
> Reviewed 3 of 6 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dzygann, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjcM6ArDiXADfngwbX1:-MjheTlG0P1eaHYShAA_:bc79gkq) (no related file):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

> particular reason you set effective user ID/group ID as well?

Yes, I have tested the change with the Postgres DB. It was complaining that I still trying to run it with the root user. After changing also the effective ID's the error disappeared. 
</blockquote></details>

Read a bit more about effective UID/GID. Legit.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfMFNC74hwYpjHlUvK:-MjhW3M604b9hmBEPsJI:by5dau7) (no related file):*
Just to expand on this misunderstanding with amend/force push.

We asked Denis to change the commit message significantly. Changing the commit message is not possible without amend and then force-push. Even though it is frowned upon to do git-amend / git-rebase / git force-push, there was no other way for Denis to satisfy our comments on the commit messages. And we didn't indicate that "please don't fix the commit messages now, we will fix them during the final git rebase". So Denis was right to just go and amend the commit message and force-push.

> Regarding the fixup approach, I can see that there is a hash before the fixup keyword. I can't see it on my local machine. Is it correct or did I screw up something?

You did everything correctly. The hash before the fixup keyword is added by the Reviewable web page. It's not really in your git commit messages, it's just Reviewable being smart-ass.

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. Borys meant that you have a typo `This is can be...`. You should change it to proper English `This can be...`

But let's not do it now. As explained above, let's not do any git-amend / git-rebase now, but we'll postpone this to the final rebase.
___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/37#-MjgO9A20C0NRpBKClu0):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Is this right with the hash before the fixup keyword?
</blockquote></details>

Yes, this is normal. Reviewable adds it.
___
*[-- commits, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhXeKO0Idv7bqwLr1T):*
If you're curious: all commit messages in `fixup` commits are actually discarded. (That's the point of fixup commits -- they modify the code of previous commits, thus their commit messages are useless and will be discarded.) So the text you have here is redundant, but it doesn't hurt -- git will automatically remove this text during git-rebase.
___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-MjhY5Gb31XMijj-pgVL:b9gfbl5) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
> ```reStructuredText
> 
> This specifies the initial, Gramine emulated user/group ID and effective user/group ID.
> It must be non-negative. By default it runs as root user (uid = gid = 0).
> ```

`By default it runs as root user` -> `It defaults to the root user` (current version sounds weird; who runs? ID runs?)
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAiTd0MxiDcyRnp6a:-MjhZDHL3J6mmWaZ8eaj:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNP9V1iSWPo441dE8:-MjhYdboEbNPRFGR8-QG:b-in19e4) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/src/bookkeep/shim_thread.c#L170)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

> uld be helpful to print which o
Is this okay? 
</blockquote></details>

What is `%li`? I didn't know prinf-formatting supports this :) We always use `%ld`, please change.

Also, users prefer to read in normal English, not math English :) So I suggest to rephrase:
```
'loader.uid' (%ld) is negative or greater than %u"
```

Also note that we use `'` and not the backtick in Gramine messages.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhYSnO-vJEQ7U0WAid:-MjhYSnO-vJEQ7U0WAie:bjpecre) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
> ```C
>     }
> 
>     if (uid_int64 < 0 || uid_int64 > IDTYPE_MAX ) {
> ```

You have a redundant space before `)`. Please remove.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mjh_2tr2w4aVas5VuaW:b-lfquh9) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Some things here are wrong. See https://github.com/gramineproject/graphene/blob/master/LibOS/shim/test/regression/attestation.manifest.template as an example.

- You have an explicit name of this test: `uid_gid`. You should use this name for `libos.entrypoint` and `loader.argv0_override`
- You need to add `sgx.trusted_files` -- at least `graphene.runtimedir()` and your binary `uid_gid`

Did you test this under SGX? You can do `make SGX=1 sgx-tokens` and then `make SGX=1 regression` to check if your new test works in SGX. I bet it currently doesn't pass.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-Mjh_bWCEuZM6jPZevOI:-Mjh_bWD3hHVGtxk1o5A:birm7lp) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/LibOS/shim/test/regression/uid_gid.manifest.template#L12)):*
> ```
> fs.mount.lib.path = "/lib"
> fs.mount.lib.uri = "file:{{ graphene.runtimedir() }}"
> ```

Please don't leave empty lines at the end of files.


<!-- Sent from Reviewable.io -->

2021-09-16 10:38 UTC, pwmarcz requested changes
> Reviewed 4 of 6 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-16 11:22 UTC, boryspoplawski reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

___
*[-- commits, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhXeKO0Idv7bqwLr1T):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If you're curious: all commit messages in `fixup` commits are actually discarded. (That's the point of fixup commits -- they modify the code of previous commits, thus their commit messages are useless and will be discarded.) So the text you have here is redundant, but it doesn't hurt -- git will automatically remove this text during git-rebase.
</blockquote></details>

But note that the commit one-liner must mach exactly (except for the `fixup!` part), because they are matched based on it when squashing later on.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNP9V1iSWPo441dE8:-MjiJwAIBR2RJU_U4nmH:b-mrjr3m) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/src/bookkeep/shim_thread.c#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `%li`? I didn't know prinf-formatting supports this :) We always use `%ld`, please change.

Also, users prefer to read in normal English, not math English :) So I suggest to rephrase:
```
'loader.uid' (%ld) is negative or greater than %u"
```

Also note that we use `'` and not the backtick in Gramine messages.
</blockquote></details>

It does support `i`, but we use `d` everywhere.
FWIW: I don't mind the current version (with `>` `<`).


<!-- Sent from Reviewable.io -->

2021-09-16 18:45 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 5 of 8 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. Borys meant that you have a typo `This is can be...`. You should change it to proper English `This can be...`

But let's not do it now. As explained above, let's not do any git-amend / git-rebase now, but we'll postpone this to the final rebase.
</blockquote></details>

It was done by the commit before ... Somehow it came back into the message ... Thanks for fixing it later!
___
*[-- commits, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhXeKO0Idv7bqwLr1T):*
> ote that the commit one-liner mu
Thanks for the input!
___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-Mjjurq62kdSoqaV1LPN:bshj3rl) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`By default it runs as root user` -> `It defaults to the root user` (current version sounds weird; who runs? ID runs?)
</blockquote></details>

I hope this sounds more clearly
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r1](https://reviewable.io/reviews/gramineproject/gramine/37#-MjZAiTd0MxiDcyRnp6a:-Mjjv4vV-qoD9ZFtcNAB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0ebefdb3d0460607ab30e3cf94451826370ff1c9/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 170 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNP9V1iSWPo441dE8:-Mjjv3e8BWXhkFPIDmSG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/src/bookkeep/shim_thread.c#L170)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It does support `i`, but we use `d` everywhere.
FWIW: I don't mind the current version (with `>` `<`).
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 169 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhYSnO-vJEQ7U0WAid:-Mjjv1Ct64gsM-enr2BQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/LibOS/shim/src/bookkeep/shim_thread.c#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a redundant space before `)`. Please remove.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mjj9ACqETesDFXJOeGL:b-vexvru) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
> u test this under SGX? Yo
Nope, I didn't test under SGX. I did "graphene-direct" test, only. 
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-Mjh_bWCEuZM6jPZevOI:-Mjj9Oob9eAdjsOsg0qV:bm1ddea) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/LibOS/shim/test/regression/uid_gid.manifest.template#L12)):*
> don't leave empty lines 
ok


<!-- Sent from Reviewable.io -->

2021-09-17 07:06 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dzygann, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-MjmYadk5tv_mVyUHUpP:b-qesd5n) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

I hope this sounds more clearly
</blockquote></details>

`to the root user` -> `as the root user` (I think this is more correct English)

Also, please re-wrap your text to 80 chars per line. We use 100 chars per line in our C/Python/Makefile code, but 80 chars per line for Documentation. (The reason being: documentation is intended for "normal" reading, and people's eyes find it easier to read less chars per line. Science!)
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-MjmZoMb3c1AH50N5WDw:b-4piusb) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

> u test this under SGX? Yo
Nope, I didn't test under SGX. I did "graphene-direct" test, only. 
</blockquote></details>

Out of curiousity: you don't have access to an SGX-enabled machine?
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 16 at r5](https://reviewable.io/reviews/gramineproject/gramine/37#-MjmZPLX8tnq0aC4n1iu:-MjmZPLX8tnq0aC4n1iv:bkiwzmj) ([raw file](https://github.com/gramineproject/gramine/blob/fa04ace622d0d234b9c3d4c8d348e3733dd5b078/LibOS/shim/test/regression/uid_gid.manifest.template#L16)):*
> ```
>   "file:{{ graphene.runtimedir() }}/",
>   "file:uid_gid"
> ]
> ```

Here you have a "not-finished" line. Doesn't look good.

(I actually don't know why this happens for some people. I use the Vim editor, and I've never encountered this thingy myself. Is this something that other editors do, somehow remove the final `\n` in the file?)


<!-- Sent from Reviewable.io -->

2021-09-17 10:28 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 16 at r5](https://reviewable.io/reviews/gramineproject/gramine/37#-MjmZPLX8tnq0aC4n1iu:-MjnI1II22g1dNEirGKG:bip8snk) ([raw file](https://github.com/gramineproject/gramine/blob/fa04ace622d0d234b9c3d4c8d348e3733dd5b078/LibOS/shim/test/regression/uid_gid.manifest.template#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here you have a "not-finished" line. Doesn't look good.

(I actually don't know why this happens for some people. I use the Vim editor, and I've never encountered this thingy myself. Is this something that other editors do, somehow remove the final `\n` in the file?)
</blockquote></details>

I think it's often an editor option ("require final newline", "empty line at end of file" and such).


<!-- Sent from Reviewable.io -->

2021-09-17 14:13 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)

___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

It was done by the commit before ... Somehow it came back into the message ... Thanks for fixing it later!
</blockquote></details>

Still not done. Let's fix this at the final rebase.


<!-- Sent from Reviewable.io -->

2021-09-18 13:06 UTC, dzygann commented
___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-Mjt-bHm4lZQfEDl-i6o:b-fv3bsq) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to the root user` -> `as the root user` (I think this is more correct English)

Also, please re-wrap your text to 80 chars per line. We use 100 chars per line in our C/Python/Makefile code, but 80 chars per line for Documentation. (The reason being: documentation is intended for "normal" reading, and people's eyes find it easier to read less chars per line. Science!)
</blockquote></details>

Done. Thanks for the additional description why to do that.


<!-- Sent from Reviewable.io -->

2021-09-18 13:12 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 6 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mjt0nXL-6hzyX5i1ESi:byruvpf) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Out of curiousity: you don't have access to an SGX-enabled machine?
</blockquote></details>

I have a SGX-enabled machine :) It has a Intel(R) Core(TM) i5-8400T CPU. Unfortunately, it supports SGX 1, only. Do you have a recommendation, if I would like to buy a new one?
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 16 at r5](https://reviewable.io/reviews/gramineproject/gramine/37#-MjmZPLX8tnq0aC4n1iu:-Mjt-zx64RSYmnHK5cKU:b-8jslx0) ([raw file](https://github.com/gramineproject/gramine/blob/fa04ace622d0d234b9c3d4c8d348e3733dd5b078/LibOS/shim/test/regression/uid_gid.manifest.template#L16)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think it's often an editor option ("require final newline", "empty line at end of file" and such).
</blockquote></details>

I found an option in the setting: ... ends with a line break 


<!-- Sent from Reviewable.io -->

2021-09-19 18:57 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)

___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-MjzPjPYEJVTHYiAS2PP:bfhqml6) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done. Thanks for the additional description why to do that.
</blockquote></details>

Not done.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-MjzPpcY9Q6-fZHZYMeU:bdn2qt4) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

I have a SGX-enabled machine :) It has a Intel(R) Core(TM) i5-8400T CPU. Unfortunately, it supports SGX 1, only. Do you have a recommendation, if I would like to buy a new one?
</blockquote></details>

Why is that one not enough? 


<!-- Sent from Reviewable.io -->

2021-09-19 18:58 UTC, boryspoplawski commented
Jenkins, test this please.

2021-09-20 04:25 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 7 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

___
*[Documentation/manifest-syntax.rst, line 189 at r4](https://reviewable.io/reviews/gramineproject/gramine/37#-MjhY5Gb31XMijj-pgVK:-Mk0R53DAkcslEFhNnLX:bfkocnz) ([raw file](https://github.com/gramineproject/gramine/blob/decfc2f034b5f485141c15b0ceb8170d6003da03/Documentation/manifest-syntax.rst#L189)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Right, thanks! Now, it should be done :)
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mk0RG6_4r20WOn_dOkL:b678fal) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
> is that one not en
It works fine. I'm asking out of curiosity.


<!-- Sent from Reviewable.io -->

2021-09-20 12:45 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-20 12:50 UTC, boryspoplawski commented
On the previous run `uid_and_git` test (added by this PR) timed out on `jenkins-sgx-sanitizers` pipeline. No idea how's that possible.

2021-09-20 13:38 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk2Q4W67KrB77ccspym:-Mk2Q4W70chK2fACLDt3:b-2j9z49) (no related file):*
@dzygann the newly added test fails (time-outs) on SGX-sanitizers pipeline, please debug. You can get the setup from `.ci` directory; generally speaking this is Gramine compiled in debug mode with SGX support, using clang and with some sanitizers enabled. 

---


<!-- Sent from Reviewable.io -->

2021-09-21 05:41 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk2Q4W67KrB77ccspym:-Mk5rIRk7NF8KamS0zbv:b-lrjupi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dzygann the newly added test fails (time-outs) on SGX-sanitizers pipeline, please debug. You can get the setup from `.ci` directory; generally speaking this is Gramine compiled in debug mode with SGX support, using clang and with some sanitizers enabled. 
</blockquote></details>

Hi @boryspoplawski I'm not familiar with this approach. Can you explain it a little bit more in detail, which steps I have to do? 

---


<!-- Sent from Reviewable.io -->

2021-09-21 08:38 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.c, line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UofvAHgNEZrewCeh:-Mk6UofvAHgNEZrewCei:b-t51j28) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L12)):*
> ```C
> 
>     if (uid != 1338 || euid != 1338) {
>         errx(EXIT_FAILURE, "UID/effective UID are not equal to the value in the the manifest");
> ```

You have `the the`, please remove one
___
*[LibOS/shim/test/regression/uid_gid.c, line 19 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UsE2BNZ71npeCE8E:-Mk6UsE2BNZ71npeCE8F:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L19)):*
> ```C
> 
>     if (gid != 1337 || egid != 1337) {
>         errx(EXIT_FAILURE, "GID/effective GID are not equal to the value in the the manifest");
> ```

ditto
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mk6UVHc7KjFCivBRBoN:b9vgv24) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

> is that one not en
It works fine. I'm asking out of curiosity.
</blockquote></details>

No need to buy a new machine. I was just surprused why you didn't run this test under `graphene-sgx`?


<!-- Sent from Reviewable.io -->

2021-09-21 08:39 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-Sanitizers please (timed out on the newly added `uid_and_git` test; weird and doesn't seem related, let's retry several times)

2021-09-21 08:49 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfNyzoEsx8nsOMGSOt:-Mk6XMI9DSJwigU6yOHy:bhsk1gm) ([raw file](https://github.com/gramineproject/gramine/blob/b53f5512845637a027715b94ea5cdd7142adab7b/LibOS/shim/test/regression/uid_gid.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to buy a new machine. I was just surprused why you didn't run this test under `graphene-sgx`?
</blockquote></details>

I didn't test it in the proper way. Next time I will!


<!-- Sent from Reviewable.io -->

2021-09-21 23:42 UTC, boryspoplawski requested changes
@dimakuv what's the point of retrying? It fails consistently (and even if it didn't then failing 2 times is enough to try to debug this)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Mk7u1Q-0MiknlaWkS9k:bj6m3oh)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk2Q4W67KrB77ccspym:-Mk9iTzfEDFnLrb3fD-M:b-896f7s) (no related file):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Hi @boryspoplawski I'm not familiar with this approach. Can you explain it a little bit more in detail, which steps I have to do? 
</blockquote></details>

You have configuration file `.ci/linux-sgx-sanitizers.jenkinsfile` which is run on the faulty pipeline. From there you can extract how exactly Gramine is built, but generally the differences (from normal build) are: enabled UBSAN and clang instead of gcc.

---


<!-- Sent from Reviewable.io -->

2021-09-22 08:37 UTC, dimakuv reviewed
@boryspoplawski I was surprised that this PR triggered some bug and wanted to check if it really fails consistently.

And let's be realistic, new contributors won't be able to debug a UBSan-enabled Clang-built Graphene (no offense @dzygann). So it's us who will end up debugging this :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkBd993Ap0XmyF4ka-n:b-qsixyr)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-22 11:52 UTC, mkow reviewed
Why not? If I remember correctly they are not in hurry, so this may be a good opportunity for them to learn something ;)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkCLFeX1wMva9Sbl8ha:b-t6ztbi)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-22 17:02 UTC, boryspoplawski reviewed
Yeah, it might take time, but would be a good opportunity to learn about Gramine, it's internals and how fun debugging it is :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkDS5pEElBo-3cpLRVL:bwyyy0w)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-22 19:40 UTC, dzygann reviewed
Hi,
I did the following steps in the root directory of graphene:
`make clean`
`make DEBUG="1" SGX="1" CC="clang" CXX="clang++" AS="clang" UBSAN="1" -j`

During the build the following error came up: 

```
config.status: executing default commands
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
(CC=gcc CXX=g++ AS=gcc make -C glibc-build 2>&1 > build.log) && touch glibc-build/Build.success
<built-in>:351:10: fatal error: 'cet.h' file not found
#include "cet.h"
         ^~~~~~~
1 error generated.
<built-in>:351:10: fatal error: 'cet.h' file not found
#include "cet.h"
         ^~~~~~~
1 error generated.
<built-in>:351:10: fatal error: 'cet.h' file not found
#include "cet.h"
         ^~~~~~~
1 error generated.
<built-in>:351:10: fatal error: 'cet.h' file not found
#include "cet.h"
         ^~~~~~~
1 error generated.
<built-in>:351:10: fatal error: 'cet.h' file not found
#include "cet.h"
         ^~~~~~~
... and so on...
```
It seems that not all properties work properly, because it tries to compile the code still with the gcc.
What I'm doing wrong?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkDwFGj9GmLvLAQ5vD2:b-9gt2u5)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-22 22:41 UTC, boryspoplawski reviewed
It tries to build `glibc` with `gcc` which is expected - we have `gcc` hardcoded there, as you cannot build it otherwise.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkEeJd67wCOuV0nO6Hh:bmx40u4)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-23 09:23 UTC, dimakuv reviewed
As Borys mentioned, we build Glibc with GCC not Clang (particular reasons don't matter).

But I'm surprised by this error -- what did you change in your Gramine to trigger this error? Did you update to the newer commit in the repo? How could it work for you before, and fails now?

Anyway, maybe you should just install/update the `libgcc` package? Not sure if this link helps you: https://github.com/KhronosGroup/Vulkan-Loader/issues/301. I couldn't find much more than that on Google. But if you're interested, `cet.h` is the header file for the rather-new Intel CET technology.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkGxBY65Fxyh8zqR2pQ:b-mlroi1)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-27 20:53 UTC, dzygann commented
Hi,
I pulled the current repo into my local repo and I could run the make command without any issues anymore.
When I run the `ninja -C build/` command I get the following error:

```
../Pal/src/host/Linux/meson.build:37:0: ERROR: C shared or static library 'gramine-lib' not found

A full log can be found at /home/developer/workspaces/graphene/build/meson-logs/meson-log.txt
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/developer/workspaces/graphene /home/developer/workspaces/graphene/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed

```

The log output: 
```
Compiler stdout:
 install: /usr/lib/gcc/x86_64-linux-gnu/9/
programs: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/9/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/9/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/

Compiler stderr:

Library cjson found: NO

Executing subproject cJSON-1.7.12

Project name: cJSON
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C compiler for the build machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
Build targets in project: 2
Subproject cJSON-1.7.12 finished.


../Pal/src/host/Linux/meson.build:37:0: ERROR: C shared or static library 'gramine-lib' not found
```

I can circumvent the issue, when I run the `make DEBUG="1"` command and then call the `meson` and the `ninja` command again.

Now, I don't know what I have to do to analyse the sanitizer issue.
                                                                                                                        





<!-- Sent from Reviewable.io -->

2021-09-28 06:08 UTC, dimakuv reviewed
@dzygann But were you able to build Gramine with Clang? You had problems with it before.

The output that you showed now is for `gcc 9.3.0`.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Mkf-yp8Dy2jkG6YfPUy:b5iy1kv)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-28 07:19 UTC, pwmarcz reviewed
>Now, I don't know what I have to do to analyse the sanitizer issue.

See [Additional build options](https://gramine.readthedocs.io/en/latest/building.html#additional-build-options) in the documentation, you need to build with UBSan (`UBSAN=1` for make, `-Dubsan=enabled` for meson).

You should build with Clang, though (`export CC=clang CXX=clang++` before running make and meson), because that's what the sanitizers build on Jenkins does (and Clang's sanitizers find more issues than GCC's).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MkfElJd0Xq-YOP7H5as:bdu8nzn)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-29 09:17 UTC, dzygann commented
@dimakuv No, I did a rebase with the current version and then I ran the `make DEBUG=1 SGX=1 CC=clang CXX=clang++ UBSAN=1 -j` command.

@pwmarcz Thanks for the hint with the export command! That makes the make call much smaller. 
I also added the`UBSAN=1` and `-Dubsan=enabled` arguments to the build process.

I ran `make regression SGX=1 UBSAN=1 -j` and it works on my machine.

```
developer@OptiPlex-3070:~/workspaces/graphene/LibOS/shim/test/regression$ make regression SGX=1 UBSAN=1 -j
rm -f libos-regression.xml
make libos-regression.xml
make[1]: Entering directory '/home/developer/workspaces/graphene/LibOS/shim/test/regression'
../../../../Scripts/run-pytest --junit-xml libos-regression.xml -v test_libos.py
============================================================================================================================= test session starts =============================================================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/developer/workspaces/graphene/LibOS/shim/test/regression
collected 115 items                                                                                                                                                                                                                                                           

test_libos.py::TC_00_Unittests::test_000_spinlock PASSED                                                                                                                                                                                                                [  0%]
test_libos.py::TC_00_Unittests::test_010_shim_run_test PASSED                                                                                                                                                                                                           [  1%]
test_libos.py::TC_00_Unittests::test_020_ubsan PASSED                                                                                                                                                                                                                   [  2%]
test_libos.py::TC_01_Bootstrap::test_001_helloworld PASSED                                                                                                                                                                                                              [  3%]
test_libos.py::TC_01_Bootstrap::test_100_basic_bootstrapping PASSED                                                                                                                                                                                                     [  4%]
test_libos.py::TC_01_Bootstrap::test_101_basic_bootstrapping_five_arguments PASSED                                                                                                                                                                                      [  5%]
test_libos.py::TC_01_Bootstrap::test_102_argv_from_file PASSED                                                                                                                                                                                                          [  6%]
test_libos.py::TC_01_Bootstrap::test_103_env_from_host PASSED                                                                                                                                                                                                           [  6%]
test_libos.py::TC_01_Bootstrap::test_104_env_from_file PASSED                                                                                                                                                                                                           [  7%]
test_libos.py::TC_01_Bootstrap::test_105_basic_bootstrapping_static PASSED                                                                                                                                                                                              [  8%]
test_libos.py::TC_01_Bootstrap::test_106_basic_bootstrapping_pie PASSED                                                                                                                                                                                                 [  9%]
test_libos.py::TC_01_Bootstrap::test_107_uid_and_gid PASSED              <-- works                                                                                                                                                                                               [ 10%]
test_libos.py::TC_01_Bootstrap::test_110_basic_bootstrapping_cpp PASSED                                                                                                                                                                                                 [ 11%]
test_libos.py::TC_01_Bootstrap::test_200_exec PASSED                                                                                                                                                                                                                    [ 12%]
test_libos.py::TC_01_Bootstrap::test_201_exec_same PASSED     

other test...

----------------------------------------------------------------------------------- generated xml file: /home/developer/workspaces/graphene/LibOS/shim/test/regression/libos-regression.xml -----------------------------------------------------------------------------------
=========================================================================================================================== short test summary info ===========================================================================================================================
FAILED test_libos.py::TC_04_Attestation::test_000_attestation - subprocess.CalledProcessError: Command '['attestation']' returned non-zero exit status 1.
FAILED test_libos.py::TC_04_Attestation::test_001_attestation_stdio - subprocess.CalledProcessError: Command '['attestation', 'test_stdio']' returned non-zero exit status 1.
FAILED test_libos.py::TC_50_GDB::test_000_gdb_backtrace - AssertionError: None is not true : backtrace 1 not found in GDB output
FAILED test_libos.py::TC_50_GDB::test_010_regs_x86_64 - subprocess.CalledProcessError: Command '['debug_regs-x86_64']' returned non-zero exit status 1.
============================================================================================================ 4 failed, 107 passed, 4 skipped in 399.40s (0:06:39) =============================================================================================================
make[1]: *** [Makefile:187: libos-regression.xml] Error 1
make[1]: Leaving directory '/home/developer/workspaces/graphene/LibOS/shim/test/regression'
make: *** [Makefile:184: regression] Error 2
             
```


There are four failed tests, but I don't think that they are related to this issue. Maybe to some misconfiguration or missing features on my machine. 





<!-- Sent from Reviewable.io -->

2021-09-29 10:57 UTC, dzygann commented
> ake regression SGX=1 UBSAN=1 -j and it works on my machine.
I could reproduce the issue. 



```

================================================================================================================================== FAILURES ===================================================================================================================================
____________________________________________________________________________________________________________________ TC_01_Bootstrap.test_107_uid_and_gid _____________________________________________________________________________________________________________________

self = <test_libos.TC_01_Bootstrap testMethod=test_107_uid_and_gid>, args = ['uid_gid'], timeout = 20, prefix = [], kwds = {}, process = <subprocess.Popen object at 0x7f816f866a90>

    def run_binary(self, args, *, timeout=None, prefix=None, **kwds):
        timeout = (max(self.DEFAULT_TIMEOUT, timeout) if timeout is not None
            else self.DEFAULT_TIMEOUT)
    
        if not self.loader_path.exists():
            self.fail('loader ({}) not found'.format(self.loader_path))
        if not self.libpal_path.exists():
            self.fail('libpal ({}) not found'.format(self.libpal_path))
    
        if prefix is None:
            prefix = []
    
        with subprocess.Popen(
                [*prefix, fspath(self.loader_path), fspath(self.libpal_path), 'init', *args],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                preexec_fn=os.setpgrp,
                **kwds) as process:
            try:
>               stdout, stderr = process.communicate(timeout=timeout)

../../../../Scripts/regression.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x7f816f866a90>, input = None, timeout = 20

    def communicate(self, input=None, timeout=None):
        """Interact with process: Send data to stdin and close it.
        Read data from stdout and stderr, until end-of-file is
        reached.  Wait for process to terminate.
    
        The optional "input" argument should be data to be sent to the
        child process, or None, if no data should be sent to the child.
        communicate() returns a tuple (stdout, stderr).
    
        By default, all communication is in bytes, and therefore any
        "input" should be bytes, and the (stdout, stderr) will be bytes.
        If in text mode (indicated by self.text_mode), any "input" should
        be a string, and (stdout, stderr) will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode
        is triggered by setting any of text, encoding, errors or
        universal_newlines.
        """
    
        if self._communication_started and input:
            raise ValueError("Cannot send input after starting communication")
    
        # Optimization: If we are not worried about timeouts, we haven't
        # started communicating, and we have one or zero pipes, using select()
        # or threads is unnecessary.
        if (timeout is None and not self._communication_started and
            [self.stdin, self.stdout, self.stderr].count(None) >= 2):
            stdout = None
            stderr = None
            if self.stdin:
                self._stdin_write(input)
            elif self.stdout:
                stdout = self.stdout.read()
                self.stdout.close()
            elif self.stderr:
                stderr = self.stderr.read()
                self.stderr.close()
            self.wait()
        else:
            if timeout is not None:
                endtime = _time() + timeout
            else:
                endtime = None
    
            try:
>               stdout, stderr = self._communicate(input, endtime, timeout)

/usr/lib/python3.8/subprocess.py:1028: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x7f816f866a90>, input = None, endtime = 63119.500296559, orig_timeout = 20

    def _communicate(self, input, endtime, orig_timeout):
        if self.stdin and not self._communication_started:
            # Flush stdio buffer.  This might block, if the user has
            # been writing to .stdin in an uncontrolled fashion.
            try:
                self.stdin.flush()
            except BrokenPipeError:
                pass  # communicate() must ignore BrokenPipeError.
            if not input:
                try:
                    self.stdin.close()
                except BrokenPipeError:
                    pass  # communicate() must ignore BrokenPipeError.
    
        stdout = None
        stderr = None
    
        # Only create this mapping if we haven't already.
        if not self._communication_started:
            self._fileobj2output = {}
            if self.stdout:
                self._fileobj2output[self.stdout] = []
            if self.stderr:
                self._fileobj2output[self.stderr] = []
    
        if self.stdout:
            stdout = self._fileobj2output[self.stdout]
        if self.stderr:
            stderr = self._fileobj2output[self.stderr]
    
        self._save_input(input)
    
        if self._input:
            input_view = memoryview(self._input)
    
        with _PopenSelector() as selector:
            if self.stdin and input:
                selector.register(self.stdin, selectors.EVENT_WRITE)
            if self.stdout and not self.stdout.closed:
                selector.register(self.stdout, selectors.EVENT_READ)
            if self.stderr and not self.stderr.closed:
                selector.register(self.stderr, selectors.EVENT_READ)
    
            while selector.get_map():
                timeout = self._remaining_time(endtime)
                if timeout is not None and timeout < 0:
                    self._check_timeout(endtime, orig_timeout,
                                        stdout, stderr,
                                        skip_check_and_raise=True)
                    raise RuntimeError(  # Impossible :)
                        '_check_timeout(..., skip_check_and_raise=True) '
                        'failed to raise TimeoutExpired.')
    
                ready = selector.select(timeout)
>               self._check_timeout(endtime, orig_timeout, stdout, stderr)

/usr/lib/python3.8/subprocess.py:1869: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x7f816f866a90>, endtime = 63119.500296559, orig_timeout = 20, stdout_seq = [], stderr_seq = [], skip_check_and_raise = False

    def _check_timeout(self, endtime, orig_timeout, stdout_seq, stderr_seq,
                       skip_check_and_raise=False):
        """Convenience for checking if a timeout has expired."""
        if endtime is None:
            return
        if skip_check_and_raise or _time() > endtime:
>           raise TimeoutExpired(
                    self.args, orig_timeout,
                    output=b''.join(stdout_seq) if stdout_seq else None,
                    stderr=b''.join(stderr_seq) if stderr_seq else None)
E           subprocess.TimeoutExpired: Command '['/usr/local/lib/x86_64-linux-gnu/graphene/sgx/loader', '/usr/local/lib/x86_64-linux-gnu/graphene/sgx/libpal.so', 'init', 'uid_gid']' timed out after 20 seconds

/usr/lib/python3.8/subprocess.py:1072: Time [...]

2021-09-29 12:48 UTC, dzygann reviewed
I could find a solution where this error does not occur anymore. 
In the manifest, I added the option `sgx.nonpie_binary = true`. Locally it works. 

I don't understand why this option enables clang to run the binary and why it works in gcc OOTB?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MklZoRO1WfUW7yrEbqh:b-qqtqsl)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-29 12:54 UTC, pwmarcz reviewed
Can you check what happens using GDB? If you run the program with `GDB=1 gramine-direct uid_gid`, you'll be able to Ctrl-C when the program hangs and check the backtrace (`backtrace` command).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MklbCUs75LU0tYXv1DS:bz0jcqp)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)



<!-- Sent from Reviewable.io -->

2021-09-29 13:13 UTC, dzygann commented
If I run the direct mode as you mentioned I get the following error:
```
developer@OptiPlex-3070:~/workspaces/graphene/LibOS/shim/test/regression$ GDB=1 graphene-direct uid_gid
Reading symbols from /usr/local/lib/x86_64-linux-gnu/graphene/direct/loader...
[graphene_linux_gdb.py] Loading common/language_gdb.py...
[graphene_linux_gdb.py] Loading common/pagination_gdb.py...
[graphene_linux_gdb.py] Loading common/debug_map_gdb.py...
[graphene_linux_gdb.py] Loading common/graphene.gdb...
(gdb) run
Starting program: /usr/local/lib/x86_64-linux-gnu/graphene/direct/loader /usr/local/lib/x86_64-linux-gnu/graphene/direct/libpal.so init uid_gid
error: ubsan: null pointer passed as an argument declared to never be null
error: ubsan: ../Pal/src/host/Linux/db_threading.c:61:9
[Inferior 1 (process 168119) exited with code 0203]
```

Do I have to pass some more arguments?





<!-- Sent from Reviewable.io -->

2021-09-29 13:18 UTC, pwmarcz reviewed
So under GDB it didn't hang, but you have a message from UBSan. Good!

To find out more about what happens, you can set a catchpoint for exit (`catch syscall exitgroup`) or a breakpoint for abort function (`break pal_abort`). Can you find out why "null pointer passed as an argument declared to never be null"?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MklgiYW6j0wqQIoGZel:b-1aofwt)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)



<!-- Sent from Reviewable.io -->

2021-10-02 12:53 UTC, dzygann reviewed
Hi 
can we retest the CI? I would like to see, if adding the `sgx.nonpie_binary = true` option fix the issue also remote.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Ml01FqC5ARL08nPx4nb:b-6eujfu)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)



<!-- Sent from Reviewable.io -->

2021-10-02 13:25 UTC, mkow commented
Jenkins, test this please

2021-10-02 13:26 UTC, mkow reviewed
Here you go

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Ml0AdYF21LCBWxPYm6V:bukz1x0)* status: 7 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)



<!-- Sent from Reviewable.io -->

2021-10-02 16:09 UTC, dzygann reviewed
This is weird. All of them are failing now. What happened? 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Ml0kKkJAg_keJYY7vT2:b8ke0ke)* status: 7 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.c, line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UofvAHgNEZrewCeh:-Ml0k3moBWQCq-fe_E6s:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have `the the`, please remove one
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/uid_gid.c, line 19 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UsE2BNZ71npeCE8E:-Ml0k49SB4gwyQb5Bzt0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-02 17:15 UTC, pwmarcz reviewed
Right, unfortunately our Jenkins instance is not visible to outside, sorry about that.

It looks like compilation is failing because we recently renamed all instances of `graphene` to `gramine` (as part of project name change). And Jenkins is testing the result of merging your code.

I think you should rebase your branch on newest master; and do the renames in your files, of course. (There is also one more change: we now have `sgx.debug = true` in all our templates.)

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Ml0t2_g4aAX4XIdgO3T:b-aoruqc)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk2Q4W67KrB77ccspym:-Ml0zUqOBCgm75HoskbJ:b-55zg37) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You have configuration file `.ci/linux-sgx-sanitizers.jenkinsfile` which is run on the faulty pipeline. From there you can extract how exactly Gramine is built, but generally the differences (from normal build) are: enabled UBSAN and clang instead of gcc.
</blockquote></details>

It looks like the error was a side-effect of not specifying `sgx.nonpie_binary = true` in the manifest, and not related to this change at all.

(And unlike GCC, Clang produces non-PIE binaries by default...)

---


<!-- Sent from Reviewable.io -->

2021-10-02 17:17 UTC, dimakuv requested changes
Our Jenkins is stupid. It automatically tries to merge your branch into master branch, and tests this:
```
Commit message: "Merge e476c8f110914f7e62767e1039d25f4003747b6e into 0e61d7ea023ded04a14291448898050c1e84f504"
```

There is no way to switch this stupid feature in Jenkins. So this bad merge resulted in this failure:
```
jinja2.exceptions.UndefinedError: 'graphene' is undefined
../../../../Scripts/manifest.mk:8: recipe for target 'uid_gid.manifest' failed
```

The only way to fix it is to rebase your PR on top of the current latest master. Otherwise Jenkins will try to merge every time, and your stuff will fail every time. So please rebase your PR (`git rebase master` and then you'll need to fix the problematic merges manually).

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-Ml0zrl9-cNr4tURylZi:ba6uw0q)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 1 at r8](https://reviewable.io/reviews/gramineproject/gramine/37#-Ml1-HJUEPLzyNb_OWdl:-Ml1-HJUEPLzyNb_OWdm:bczmmm5) ([raw file](https://github.com/gramineproject/gramine/blob/e476c8f110914f7e62767e1039d25f4003747b6e/LibOS/shim/test/regression/uid_gid.manifest.template#L1)):*
> ```
> loader.preload = "file:{{ graphene.libos }}"
> ```

This is why Jenkins is failing -- you still have the old `graphene` word here. Recently, we changed everything to "gramine" (see examples in the latest master branch).


<!-- Sent from Reviewable.io -->

2021-10-04 16:53 UTC, dzygann reviewed
Okay, I did the rebase. Let's try it again :)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MlBCjT7DgORLE1JrIjf:b-mt77ic)* status: 2 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 1 at r8](https://reviewable.io/reviews/gramineproject/gramine/37#-Ml1-HJUEPLzyNb_OWdl:-MlBCcef882mPfVJ-cs3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e476c8f110914f7e62767e1039d25f4003747b6e/LibOS/shim/test/regression/uid_gid.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is why Jenkins is failing -- you still have the old `graphene` word here. Recently, we changed everything to "gramine" (see examples in the latest master branch).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 17:12 UTC, boryspoplawski commented
Jenkins, retest this please

2021-10-04 17:16 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)

___
*[LibOS/shim/test/regression/uid_gid.c, line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UofvAHgNEZrewCeh:-MlBIJeo8sMS5q6cqtQN:b-8nyi3w) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L12)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[LibOS/shim/test/regression/uid_gid.c, line 19 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UsE2BNZ71npeCE8E:-MlBIMsECFW1boLu7GmW:bfhqml6) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L19)):*
<details><summary><i>Previously, dzygann (Denis Zygann) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2021-10-04 18:30 UTC, dzygann reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: 7 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @dzygann, and @pwmarcz)

___
*[LibOS/shim/test/regression/uid_gid.c, line 12 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UofvAHgNEZrewCeh:-MlBYehcDwMdWTj9Dr5S:bur5wks) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Now, it should be done.
___
*[LibOS/shim/test/regression/uid_gid.c, line 19 at r7](https://reviewable.io/reviews/gramineproject/gramine/37#-Mk6UsE2BNZ71npeCE8E:-MlBW9hiEdFrdw33cgQz:bur5wks) ([raw file](https://github.com/gramineproject/gramine/blob/69788a0ffba1b7507c949fa99b41100e73c9ece4/LibOS/shim/test/regression/uid_gid.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Now, it should be done.


<!-- Sent from Reviewable.io -->

2021-10-04 18:44 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @dzygann)

___
*[-- commits, line 65 at r10](https://reviewable.io/reviews/gramineproject/gramine/37#-MlBbFF1EUARSoPPjb-t):*
FYI: this message will be dropped anyway, no need to add it (it's how fixup commits work, their content is just amended, the message is discarded). Also there is a handy `--fixup=commit_hash` parameter to `git commit` which you can use (it will create a correct commit msg oneliner)


<!-- Sent from Reviewable.io -->

2021-10-04 18:44 UTC, boryspoplawski commented
Jenkins, retest this please

2021-10-05 06:17 UTC, dimakuv approved these changes
> Reviewed 5 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-10-05 06:20 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MlE5vesEhByTVDb8f92:-MlE5vesEhByTVDb8f93:bds3vd6) (no related file):*
The PR looks good to me now. Thanks for this effort! (Now let's wait for other reviewers, they may still have some comments.)

---
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 18 at r10](https://reviewable.io/reviews/gramineproject/gramine/37#-MlE5Xh6DHPBjKGOiTST:-MlE5Xh6DHPBjKGOiTSU:b-1yghyl) ([raw file](https://github.com/gramineproject/gramine/blob/3736f4d688e9dff6703dcc34dd09244de70ef91c/LibOS/shim/test/regression/uid_gid.manifest.template#L18)):*
> ```
> sgx.trusted_files = [
>   "file:{{ gramine.runtimedir() }}/",
>   "file:uid_gid"
> ```

We typically put a comma at the end of such lists in manifest files, so I would prefer:
```
  "file:uid_gid",
```

This makes it easier to append more lines to trusted files, and is also valid in TOML. But not blocking, feel free to ignore.


<!-- Sent from Reviewable.io -->

2021-10-05 13:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MlE5vesEhByTVDb8f92:-MlFamqU64L4jxN8x3sO:b2mtpk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me now. Thanks for this effort! (Now let's wait for other reviewers, they may still have some comments.)
</blockquote></details>

Except for commit message (which we will fix at rebase) looks good

---


<!-- Sent from Reviewable.io -->

2021-10-05 15:07 UTC, pwmarcz approved these changes
> Reviewed 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dzygann)



<!-- Sent from Reviewable.io -->

2021-10-05 17:34 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MlE5vesEhByTVDb8f92:-MlGWI0uCnH59XWruBoH:bb6un1j) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Except for commit message (which we will fix at rebase) looks good
</blockquote></details>

Done

---
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/37#-MjfLwWT2Hi9lEM58ekM):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still not done. Let's fix this at the final rebase.
</blockquote></details>

Done. Also rephrased.
___
*[LibOS/shim/test/regression/uid_gid.manifest.template, line 18 at r10](https://reviewable.io/reviews/gramineproject/gramine/37#-MlE5Xh6DHPBjKGOiTST:-MlGWGo509HxViISUcJU:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/3736f4d688e9dff6703dcc34dd09244de70ef91c/LibOS/shim/test/regression/uid_gid.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We typically put a comma at the end of such lists in manifest files, so I would prefer:
```
  "file:uid_gid",
```

This makes it easier to append more lines to trusted files, and is also valid in TOML. But not blocking, feel free to ignore.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-05 17:39 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-05 17:50 UTC, dimakuv commented
Jenkins, test this please

2021-10-05 19:20 UTC, dzygann commented
The sanitizer runs again into an issue... Can anyone tell me what went wrong?

2021-10-05 20:31 UTC, boryspoplawski submitted a review, later dismissed
@dzygann Jenkins failed to checkout the repo, probably due todays problem with Github.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37#-:-MlH8m_c6mSRsgaD0XRK:bo4z7md)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-06 06:24 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-10-06 06:24 UTC, dimakuv commented
Jenkins, test this please

2021-10-06 10:52 UTC, merged

2021-10-06 10:52 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dzygann)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/37#-MlKDtdf-VI9-JO-uh7x:-MlKDtdg423o6wzZkd9P:b-dnil2v) (no related file):*
Blocking for some time, need to figure out smth with @dzygann (privately)

---


<!-- Sent from Reviewable.io -->