[Docs] Fixing an error in Prepare signing key section in Quick Start Guide
gramineproject/gramine pull request #378
Opened 2022-02-03 11:53 UTC by jinengandhi-intel

## Description of the changes 
Command for Prepare signing key in Quick Start Guide assumes we already have a gramine directory inside `"$HOME"/.config/` without which it throws a `No such file or directory` error. This commit adds the command to create that `gramine` dir.

Link to Quick Start Guide: https://gramine.readthedocs.io/en/latest/quickstart.html#prepare-a-signing-key

Fixes: #377 

## How to test this PR?

2022-02-03 11:57 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/378#-MuzRC727Lcn3oNtubqA):*
`Fixing` -> `Fix`
`Prepare signing key` -> `"Prepare a signing key"`
not period at the end


<!-- Sent from Reviewable.io -->

2022-02-03 12:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel)



<!-- Sent from Reviewable.io -->

2022-02-04 02:35 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/378#-MuzRC727Lcn3oNtubqA):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Fixing` -> `Fix`
`Prepare signing key` -> `"Prepare a signing key"`
not period at the end
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 11:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-02-04 12:36 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-04 18:39 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/378#-Mv5-YR43pgoMMGPqRrY:-Mv5-YR43pgoMMGPqRrZ:b-khngb1) (no related file):*
@jinengandhi-intel: In the future please name your branches according to our scheme (`nick/change-description`), it will make it easier to rebase them for us.

---


<!-- Sent from Reviewable.io -->

2022-02-04 20:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-07 01:18 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-07 01:19 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/378)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/378#-MvGkxDD4dgtd5D6rbrz):*
This is a bit too long, I think `[Docs] Add a missing instruction in Quick Start Guide` would do. But not blocking.


<!-- Sent from Reviewable.io -->

2022-02-07 01:25 UTC, merged