[LibOS] Correct RDTSC instruction drift with system clock more often
gramineproject/gramine pull request #38
Opened 2021-09-14 10:39 UTC by aneessahib

## Description of the changes 
On some systems - the RDTSC and the system clock drifts away from each other significantly, that at higher gaps (above 100ms), rdtsc falls behind, and this gets flagged by LTP. Currently the correction is done every 10 seconds #define TSC_REFINE_INIT_TIMEOUT_USECS 10000000 .  The timeout is now reduced to 50ms. This satisfies LTP drift thresholds, and does not impact performance either(tested with SPECpower and Redis).

Fixes #2666 - https://github.com/gramineproject/graphene/issues/2666 

## How to test this PR?

2021-09-14 13:06 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZPBdc17Zord6YJfeM):*
You forgot to add the `Signed-off-by` line (the DCO thing). Please add it, by rebasing and editing your commit.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZPKN8BOH-kjnpTwoN:-MjZPKN8BOH-kjnpTwoO:b-6sz3v1) ([raw file](https://github.com/gramineproject/gramine/blob/8f5b5507c8b19dd6141b63167412a7bdb7135812/Pal/src/host/Linux-SGX/db_misc.c#L31)):*
> ```C
> #include "toml.h"
> 
> #define TSC_REFINE_INIT_TIMEOUT_USECS 50000
> ```

Please add a comment like you have in the PR description -- we need to explain this magical number, otherwise someone in the future will change it back to 10 seconds :)

Also, why exactly 50 ms? Why not 100 ms? Or why not 1 sec? This also should be explained, even if only with one phrase, in the comment.


<!-- Sent from Reviewable.io -->

2021-09-14 14:29 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZPKN8BOH-kjnpTwoN:-MjZhVDQ1AmXDQdM0nTp:b-uic4kf) ([raw file](https://github.com/gramineproject/gramine/blob/8f5b5507c8b19dd6141b63167412a7bdb7135812/Pal/src/host/Linux-SGX/db_misc.c#L31)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, sounds good now.


<!-- Sent from Reviewable.io -->

2021-09-14 14:29 UTC, dimakuv commented
Jenkins, test this please

2021-09-14 15:00 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZPKN8BOH-kjnpTwoN:-MjZoSvuAxqNpsq7C61X:bhk3j9q) ([raw file](https://github.com/gramineproject/gramine/blob/8f5b5507c8b19dd6141b63167412a7bdb7135812/Pal/src/host/Linux-SGX/db_misc.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, sounds good now.
</blockquote></details>

So, 100ms was not enough for LTP to pass? 50ms sounds like a lot.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZo2HeB7LuV9pFzE3D:-MjZo2HfAzGVyDLz9MwA:b-1i1acg) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
> ```C
> 
> /* The timeout of 50ms was found to be a safe TSC drift correction periodicity based on results from multiple systems.
>  * Any higher or lower could pose risks of negative clock derivation or performance hit respectively.
> ```

Please rewrap to 100 chars per line max
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZoBN6CsudDv33oaSn:-MjZoBN6CsudDv33oaSo:b-1xbdh) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
> ```
> negative clock derivation
> ```

What "derivation" means in this context? I don't think this is a proper word to describe what you wanted to?


<!-- Sent from Reviewable.io -->

2021-09-14 15:41 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZPKN8BOH-kjnpTwoN:-MjZxOSb06eMUvMOR1Ug:b-im6chw) ([raw file](https://github.com/gramineproject/gramine/blob/8f5b5507c8b19dd6141b63167412a7bdb7135812/Pal/src/host/Linux-SGX/db_misc.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, 100ms was not enough for LTP to pass? 50ms sounds like a lot.
</blockquote></details>

nope, 100 failed sometimes. 50 brought it home :) . Fortunately, there was no perf impact to some of our heavy workloads either. 
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZoBN6CsudDv33oaSn:-MjZv6NqBFNSC3E-UCMi:b-8tjqnp) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> negative clock derivation
> ```

What "derivation" means in this context? I don't think this is a proper word to describe what you wanted to?
</blockquote></details>

Derivation refers to deriving (or calculation of) the time from ticks returned from RDTSC. What we are trying to say here is the time thus derived could have a negative (read backward) drift compared to the system time. So.. how about we say "negative time drift"
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZo2HeB7LuV9pFzE3D:-MjZxuq2Ca1K9DqtqfFg:bkb6j90) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please rewrap to 100 chars per line max
</blockquote></details>

will do once we align on the wording. 


<!-- Sent from Reviewable.io -->

2021-09-14 15:44 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZoBN6CsudDv33oaSn:-MjZy_VxCO2FJf_MH117:boe8y6o) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Derivation refers to deriving (or calculation of) the time from ticks returned from RDTSC. What we are trying to say here is the time thus derived could have a negative (read backward) drift compared to the system time. So.. how about we say "negative time drift"
</blockquote></details>

negative time offset? :)


<!-- Sent from Reviewable.io -->

2021-09-14 15:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZoBN6CsudDv33oaSn:-MjZyj2g9bzG2rxQInmX:b-xd3ebm) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

negative time offset? :)
</blockquote></details>

"negative time drift" is good :)


<!-- Sent from Reviewable.io -->

2021-09-14 16:07 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZo2HeB7LuV9pFzE3D:-Mj_2xmP13MAeHvKOqGl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

will do once we align on the wording. 
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 32 at r2](https://reviewable.io/reviews/gramineproject/gramine/38#-MjZoBN6CsudDv33oaSn:-Mj_2yS2DwYkwfanAjb_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/12182f723305ceffafecd4788cc96b0aa233df5b/Pal/src/host/Linux-SGX/db_misc.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"negative time drift" is good :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-14 16:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-09-14 16:09 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-09-14 16:09 UTC, dimakuv commented
Jenkins, test this please

2021-09-14 16:14 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-17 14:50 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-17 15:51 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-09-17 15:51 UTC, mkow commented
Jenkins, retest this please

2021-09-17 16:05 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-09-17 17:16 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/38)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-17 23:19 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (`apps.LTP.writev07` timed out, wasn't able to reproduce it even under heavy load and 100k runs...)

2021-09-18 00:17 UTC, mkow commented
Jenkins, retest Jenkins-Direct-Sanitizers please (another timeout, this time on `test_libos.TC_01_Bootstrap.test_220_send_handle` - again, I can't reproduce locally...)

2021-09-18 00:35 UTC, mkow commented
Jenkins, retest this please (let's try a few times to ensure that it's stable - 0/5)

2021-09-18 01:00 UTC, mkow commented
Jenkins, retest this please (1/5)

2021-09-18 13:28 UTC, mkow commented
Jenkins, retest this please (2/5)

2021-09-18 14:45 UTC, mkow commented
Jenkins, retest this please (3/5)

2021-09-18 16:49 UTC, mkow commented
Jenkins, retest this please (4/5)

2021-09-18 17:47 UTC, mkow commented
Ok, 5 runs without hitting this problem again, so it's probably unrelated to the PR (and very rare). Merging.

2021-09-18 17:48 UTC, merged