WIP: [LibOS] Replace DENTRY_SYNTHETIC with a separate filesystem
gramineproject/gramine pull request #383
Opened 2022-02-07 13:11 UTC by pwmarcz

Previously, synthetic files were created as special dentries with
DENTRY_SYNTHETIC flag set. These dentries were marked as belonging to a
filesystem (typically "chroot") but weren't really initialized by it. As
a result, they could break assumptions made by that filesystem (e.g. about
`dent->inode` existing).

This change treats synthetic files same as other special files (named
pipes and sockets). We set `dent->fs` to mark them as belonging to a
separate filesystem, and all operations for the file are forwarded to
that filesystem.

In addition, for simplicity we only create synthetic directories. If the
user mounts something else than a directory, the synthetic mountpoint
can still be a directory: it will be shadowed by the mounted file
anyway.

Signed-off-by: Paweł Marczewski <pawel@invisiblethingslab.com>

## Description of the changes 

## How to test this PR?

2022-02-08 09:25 UTC, dimakuv requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNdZ5f57TtsQsLfj9D:-MvNdZ5f57TtsQsLfj9E:b6u7c2a) (no related file):*
Not relevant to this PR, but do I understand correctly that you still need to add inodes to https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/fs/shim_fs_pseudo.c ?

---
___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNXPV8BSrxwp_ie-Ts):*
`we only create synthetic directories` -- I'm not sure how to parse this sentence. Do you mean that the only type of objects belonging to the "synth" filesystem are directories (not files)? If yes, please rephrase.
___
*[LibOS/shim/src/fs/shim_fs_synthetic.c, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNb45N1E3ISe2edU9h:-MvNb45O66RytUw6h1ce:b1p25yo) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/shim_fs_synthetic.c#L14)):*
> ```C
>  * shadowed by the mounted directory, "/usr" will remain visible for the user.
>  *
>  * Operations on synthetic files are handled by `synthetic_builtin_fs` defined below. It should be
> ```

`files` -> `directories` (for consistency with the rest of the text)
___
*[LibOS/shim/src/fs/shim_namei.c, line 257 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNYgQD4kvlOsRrQg_0:-MvNYgQD4kvlOsRrQg_1:b-260tlz) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/shim_namei.c#L257)):*
> ```C
>          */
>         if (lookup->flags & LOOKUP_MAKE_SYNTHETIC) {
>             lookup->dent->state &= ~DENTRY_NEGATIVE;
> ```

Don't you want to add an assert that this is `!is_final || has_slash`?
___
*[LibOS/shim/src/fs/shim_namei.c, line 259 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNZ-Ye6NS_5wo2GCG4:-MvNZ-Ye6NS_5wo2GCG5:bvjr6tz) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/shim_namei.c#L259)):*
> ```C
>             lookup->dent->state &= ~DENTRY_NEGATIVE;
>             mode_t type = S_IFDIR;
>             mode_t perm = PERM_r_xr_xr_x;
> ```

Why do you need these helper vars `type` and `perm`? Why not just hard-code in the func arguments?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 324 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNcCG43Gy4eEvKvPVg:-MvNcCG43Gy4eEvKvPVh:bssnrsh) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/chroot/fs.c#L324)):*
> ```C
> static ssize_t chroot_read(struct shim_handle* hdl, void* buf, size_t count) {
>     assert(hdl->type == TYPE_CHROOT);
> ```

Why do you add `assert(dent->inode)` in some functions but not e.g. here?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 254 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNcnwD9n0UGlmGrKiI:-MvNcnwD9n0UGlmGrKiJ:bssnrsh) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/tmpfs/fs.c#L254)):*
> ```C
> static ssize_t tmpfs_read(struct shim_handle* hdl, void* buf, size_t size) {
>     ssize_t ret;
> ```

Why do you add `assert(dent->inode)` in some functions but not e.g. here?
___
*[LibOS/shim/src/sys/shim_file.c, line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNZUtU9A9abaCAOxsm:-MvNZUtU9A9abaCAOxsn:bgeggfm) ([raw file](https://github.com/gramineproject/gramine/blob/ae6e6099a4c7bf6c14a11348e8f5719c882f43ab/LibOS/shim/src/sys/shim_file.c#L141)):*
> ```C
>     if (dent->fs && dent->fs->d_ops && dent->fs->d_ops->unlink) {
>         if ((ret = dent->fs->d_ops->unlink(dent)) < 0)
>             goto out;
> ```

Why was it previously like this? Because there could be a SYNTHETIC dir on which `chroot_unlink()` failed?

Or is it a separate bug fix?
___
*[LibOS/shim/test/regression/tests.toml, line 97 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNZrzS2wl3y_Fo42B0:-MvNZrzS2wl3y_Fo42B1:b-vbkl4m) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/test/regression/tests.toml#L97)):*
> ```TOML
>   "spinlock",
>   "stat_invalid_args",
>   "synthetic",
> ```

What about https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/regression/tests_musl.toml ? Please add there as well.


<!-- Sent from Reviewable.io -->

2022-02-10 11:06 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNXPV8BSrxwp_ie-Ts):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

How about:

>In addition, the only type of synthetic files that we create are directories.
</blockquote></details>

Yes, thanks, this is a good rephrasing.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 324 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNcCG43Gy4eEvKvPVg:-MvYIKtt7NduKy7G2JOD:bkclf7z) ([raw file](https://github.com/gramineproject/gramine/blob/85dbb7f1f21e8cb1fc39b60c7f09267c19244ab5/LibOS/shim/src/fs/chroot/fs.c#L324)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Well, there's no `dent` here :)

I added asserts to functions that work on dentries, because a dentry object is reusable, and (even after these `DENTRY_SYNTHETIC` dentries are gone) it could e.g. correspond to a path without a file.

For the functions that work on handles, like this one, the corresponding assertion would be `hdl->inode`, but I'm not sure if I should bother: basically it checks whether the handle has been correctly initialized.
</blockquote></details>

Ah, got it.
___
*[LibOS/shim/src/sys/shim_file.c, line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNZUtU9A9abaCAOxsm:-MvYIufv0TNNB7j0BChs:b-w8lczs) ([raw file](https://github.com/gramineproject/gramine/blob/ae6e6099a4c7bf6c14a11348e8f5719c882f43ab/LibOS/shim/src/sys/shim_file.c#L141)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually this fixes a weird bug: you could just `rmdir` many directories like `/proc/1`. Should I mention it in commit message? Or commit it separately?
</blockquote></details>

I see. Could you extract it in a separate commit?


<!-- Sent from Reviewable.io -->

2022-02-10 11:24 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNXPV8BSrxwp_ie-Ts):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, thanks, this is a good rephrasing.
</blockquote></details>

Done (I rebased the branch to create a separate commit for `rmdir` bugfix below).
___
*[LibOS/shim/src/sys/shim_file.c, line 141 at r1](https://reviewable.io/reviews/gramineproject/gramine/383#-MvNZUtU9A9abaCAOxsm:-MvYMevH41CJ9ibD91KE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ae6e6099a4c7bf6c14a11348e8f5719c882f43ab/LibOS/shim/src/sys/shim_file.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see. Could you extract it in a separate commit?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-10 12:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/383#-MvYTvco2HcRjBZF98EJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `for`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-10 12:35 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-14 14:10 UTC, mkow requested changes
> Reviewed 11 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, 2 unresolved discussions (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_synthetic.c, line 25 at r4](https://reviewable.io/reviews/gramineproject/gramine/383#-MvsQXom804c16er8nCK:-MvsQXon3Ehj1V_2V3e0:bjr8dpw) ([raw file](https://github.com/gramineproject/gramine/blob/d258c4be45ea3a8ce332ac23c33d759a5f829d26/LibOS/shim/src/fs/shim_fs_synthetic.c#L25)):*
> ```C
>     assert(!dent->inode);
> 
>     dent->type = type;
> ```

Shouldn't we assert here `type == S_IFDIR`?
___
*[LibOS/shim/test/regression/synthetic.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/383#-MvsYdEG7TdAsTkVgDvl:-MvsYdEG7TdAsTkVgDvm:bfur1f3) ([raw file](https://github.com/gramineproject/gramine/blob/d258c4be45ea3a8ce332ac23c33d759a5f829d26/LibOS/shim/test/regression/synthetic.c#L21)):*
> ```C
> #include <string.h>
> #include <sys/types.h>
> #include <sys/stat.h>
> ```

please sort


<!-- Sent from Reviewable.io -->

2022-02-14 16:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: 14 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_fs_synthetic.c, line 25 at r4](https://reviewable.io/reviews/gramineproject/gramine/383#-MvsQXom804c16er8nCK:-Mvt4l_K2wLdHItEOJVL:b-6q0v9l) ([raw file](https://github.com/gramineproject/gramine/blob/d258c4be45ea3a8ce332ac23c33d759a5f829d26/LibOS/shim/src/fs/shim_fs_synthetic.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we assert here `type == S_IFDIR`?
</blockquote></details>

I'd rather not. This code doesn't rely on it, there's nothing in this file preventing the caller from using the filesystem for other dummy nodes.
___
*[LibOS/shim/test/regression/synthetic.c, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/383#-MvsYdEG7TdAsTkVgDvl:-Mvt59K9BlJoM-ZdVQgi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d258c4be45ea3a8ce332ac23c33d759a5f829d26/LibOS/shim/test/regression/synthetic.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 16:45 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_fs_synthetic.c, line 25 at r4](https://reviewable.io/reviews/gramineproject/gramine/383#-MvsQXom804c16er8nCK:-Mvt6Nzq7RtiNtZJV3xX:b8gpy9w) ([raw file](https://github.com/gramineproject/gramine/blob/d258c4be45ea3a8ce332ac23c33d759a5f829d26/LibOS/shim/src/fs/shim_fs_synthetic.c#L25)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'd rather not. This code doesn't rely on it, there's nothing in this file preventing the caller from using the filesystem for other dummy nodes.
</blockquote></details>

Ah, I thought it's not supported by the code in this file. If it is then it's fine.


<!-- Sent from Reviewable.io -->

2022-02-15 07:26 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/383)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-15 07:28 UTC, merged