[common] Fix mbedtls configuration mismatch
gramineproject/gramine pull request #389
Opened 2022-02-08 14:35 UTC by pwmarcz

## Description of the changes 

This ensures that userspace programs using the mbedtls library (e.g. `gramine-sgx-pf-crypt`) use the same configuration flags as the the mbedtls library itself.

The problem was that the Meson build applied a patch to a copy of `mbedtls/config.h`, but the programs included the unpatched version. As a result, the both sides disagreed about size of some data structures, causing `gramine-sgx-pf-crypt` to crash (when compiled with Clang in release mode).

## How to test this PR? 

This is one of the issues reported in #208 (https://github.com/gramineproject/gramine/issues/208#issuecomment-1032270427). If you compile Gramine with Clang in release or debugoptimized mode, the FS tests will fail:

```
$ SGX=1 gramine-test pytest test_pf.py
...
E   subprocess.CalledProcessError: Command '['gramine-sgx-pf-crypt', 'decrypt', '-w', 'tmp/wrap-key', '-i', 'tmp/pf_output/0', '-o', 'tmp/pf_output/0.dec']' died with <Signals.SIGSEGV: 11>.
...
```

The crash should be fixed with this PR (remember to `rm subprojects/mbedtls-mbedtls-2.26.0 -rf` before rebuilding!)

## Details

Here's the problematic code (in `pf_util.c`):

```c
pf_status_t mbedtls_aes_gcm_decrypt(const pf_key_t* key, const pf_iv_t* iv, const void* aad,
                                    size_t aad_size, const void* input, size_t input_size,
                                    void* output, const pf_mac_t* mac) {
    pf_status_t status = PF_STATUS_CALLBACK_FAILED;

    mbedtls_gcm_context gcm;
    mbedtls_gcm_init(&gcm);
```

If you disassemble this code (in `libsgx_util.so`), you'll notice that `gcm` has size of `0x1a0`. GDB also confirms this. However, `mbedtls_gcm_init` zeroes out `0x1a8` bytes. When compiled with Clang in release mode, this happens to wipe the saved value of RBX register.

This is because the following structure (part of `mbedtls_gcm_context`) has a conditionally defined field:
```c
typedef struct mbedtls_cipher_context_t
{
...
#if defined(MBEDTLS_CMAC_C)
    /** CMAC-specific context. */
    mbedtls_cmac_context_t *cmac_ctx;
#endif
```

Our patch enabled `MBEDTLS_CMAC_C` in an include file (`mbedtls/config.h`), but the patch was applied in the Meson build directory. The rest of Gramine was compiled with the unpatched version of the include file.

2022-02-08 15:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/389#-MvOq4UnA5hwucPv6aOp):*
Typo: `the the`
___
*[subprojects/packagefiles/mbedtls/meson.build, line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/389#-MvOqfju3m_ceuDtR-Jw:-MvOqfjvErNDvUKuxyvq:bmc4ugp) ([raw file](https://github.com/gramineproject/gramine/blob/e425cd6c28d6542891d84d6161528a545030616e/subprojects/packagefiles/mbedtls/meson.build#L85)):*
> ```Meson
>     link_with: [mbedtls_libs[1], mbedtls_libs[3], mbedtls_libs[5]],
>     include_directories: mbedtls_inc,
>     compile_args: '-DMBEDTLS_CONFIG_FILE="mbedtls/config-gramine.h"',
> ```

So this is the main change in this PR, right? This tells other Gramine tools (what you call "userspace programs") to use the correct header files, with `MBEDTLS_CMAC_C`-augmented data structs.


<!-- Sent from Reviewable.io -->

2022-02-08 16:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/389#-MvOq4UnA5hwucPv6aOp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `the the`
</blockquote></details>

Fixed.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/389#-MvOqfju3m_ceuDtR-Jw:-MvP8YeJ0EhhwlDNQCUR:b-crp8mp) ([raw file](https://github.com/gramineproject/gramine/blob/e425cd6c28d6542891d84d6161528a545030616e/subprojects/packagefiles/mbedtls/meson.build#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So this is the main change in this PR, right? This tells other Gramine tools (what you call "userspace programs") to use the correct header files, with `MBEDTLS_CMAC_C`-augmented data structs.
</blockquote></details>

That's right. The same happens below, with `config-pal.h`.


<!-- Sent from Reviewable.io -->

2022-02-08 18:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-14 02:26 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq24kR9r2AoO7bY9v5:-Mvq24kR9r2AoO7bY9v6:btjvq7b) (no related file):*
@dimakuv: So, when can we get rid of these hacks? You mentioned that some newer release of mbedtls will have this enabled by default?

---
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq202b0Dkj8KTtVKW4:-Mvq202c2rD-X7BkNuWa:b-jhyvtf) ([raw file](https://github.com/gramineproject/gramine/blob/ef6b7a2dc13f7441d26962f2b3814f31f0b09b44/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L20)):*
> ```objc
> #include "mbedtls/check_config.h"
> 
> #endif /* MBEDTLS_CONFIG_GRAMINE_H */
> ```

This doesn't match the value at the top


<!-- Sent from Reviewable.io -->

2022-02-14 09:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq24kR9r2AoO7bY9v5:-MvrTp6_4oEtBlruBuhP:b-m3cd1b) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: So, when can we get rid of these hacks? You mentioned that some newer release of mbedtls will have this enabled by default?
</blockquote></details>

Unfortunately, the latest release of mbedTLS (v2.28 from December 2021) still doesn't have support for SSL context serialization for TLS sessions. See https://github.com/ARMmbed/mbedtls/blob/8b3f26a5ac38d4fdccbc5c5366229f3e01dafcc0/library/ssl_tls.c#L6304

---
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq202b0Dkj8KTtVKW4:-MvrUUIL5qZ9N_fvXMr5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ef6b7a2dc13f7441d26962f2b3814f31f0b09b44/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't match the value at the top
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 10:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq202b0Dkj8KTtVKW4:-MvrjM0v9ZpaMolom6_E:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/ef6b7a2dc13f7441d26962f2b3814f31f0b09b44/subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-02-14 11:20 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/389)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/389#-Mvq24kR9r2AoO7bY9v5:-Mvrx_g0-Bji6Q34IXnz:b32vhv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unfortunately, the latest release of mbedTLS (v2.28 from December 2021) still doesn't have support for SSL context serialization for TLS sessions. See https://github.com/ARMmbed/mbedtls/blob/8b3f26a5ac38d4fdccbc5c5366229f3e01dafcc0/library/ssl_tls.c#L6304
</blockquote></details>

:(

---


<!-- Sent from Reviewable.io -->

2022-02-14 11:32 UTC, merged