[common,Pal,LibOS] Clean up superfluous and out-of-date headers
gramineproject/gramine pull request #395
Opened 2022-02-10 16:04 UTC by kailun-qin

## Description of the changes 

There are superfluous/unused header includes, some out-of-date ones associated w/ TODOs, also some confusing/inaccurate ones (not addressed in this patch). We may have a better way/rule to do this.

## How to test this PR?

2022-02-11 08:31 UTC, dimakuv requested changes
> Reviewed 145 of 145 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvbtprK-uqDOYZZ2l4X:-MvbtprK-uqDOYZZ2l4Y:bmfunz3) (no related file):*
Awesome PR! Looks correct (I didn't verify everything but only the simple files, plus those files that I know well).

@kailun-qin How did you collect these unused header includes? Did you use some tool? Or did you manually analyze them?

---
___
*[common/src/string/memcmp.c, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvbpa3eBxGDcGNGjnyj:-Mvbpa3eBxGDcGNGjnyk:bo6qmc4) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/common/src/string/memcmp.c#L3)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> 
> #include <stdint.h>
> ```

Shouldn't we include `stddef.h` which defines `size_t`? @mkow @boryspoplawski @pwmarcz 


<!-- Sent from Reviewable.io -->

2022-02-11 09:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvbtprK-uqDOYZZ2l4X:-Mvc4Hq7C2Qo3S1NoOKK:b-dvcac4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome PR! Looks correct (I didn't verify everything but only the simple files, plus those files that I know well).

@kailun-qin How did you collect these unused header includes? Did you use some tool? Or did you manually analyze them?
</blockquote></details>

I used a hybrid mode. I tried to apply some tools but none is 100% applicable/accurate to our case, so I manually analyzed most of them.

---
___
*[common/src/string/memcmp.c, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvbpa3eBxGDcGNGjnyj:-Mvc5y_H1eshDHNdkrOn:b6wulfj) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/common/src/string/memcmp.c#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we include `stddef.h` which defines `size_t`? @mkow @boryspoplawski @pwmarcz 
</blockquote></details>

Yes, we should actually add `#include <stddef.h>` for `size_t`.
Note that this is not the only case that we miss some (explicit) header includes. I noticed quite a few more but did not intend to address these in this PR as I mentioned in the description.
I think we could firstly clean up the unneeded ones (which should any way ease our future effort), then make a consensus/rule on how we add includes (which may take some time as some may relate w/ the header/API structure), after that we can add/correct the "missing" (not explicitly included) ones.


<!-- Sent from Reviewable.io -->

2022-02-11 11:43 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[common/src/string/memcmp.c, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvbpa3eBxGDcGNGjnyj:-Mvca9_w95x_TuuaClLB:b-fuk0nw) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/common/src/string/memcmp.c#L3)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yes, we should actually add `#include <stddef.h>` for `size_t`.
Note that this is not the only case that we miss some (explicit) header includes. I noticed quite a few more but did not intend to address these in this PR as I mentioned in the description.
I think we could firstly clean up the unneeded ones (which should any way ease our future effort), then make a consensus/rule on how we add includes (which may take some time as some may relate w/ the header/API structure), after that we can add/correct the "missing" (not explicitly included) ones.

</blockquote></details>

Sounds good. I'm approving then.


<!-- Sent from Reviewable.io -->

2022-02-11 16:25 UTC, mkow requested changes
good work, thanks!

> Reviewed 145 of 145 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395#-:-MvdRs3_DycmZrWAs-kh:b-2h0n2j)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvbtprK-uqDOYZZ2l4X:-MvdaPyV5bKgFwKTZm_F:b-6hq8jv) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I used a hybrid mode. I tried to apply some tools but none is 100% applicable/accurate to our case, so I manually analyzed most of them.
</blockquote></details>

Yeah, I think in C you don't really have a better way :(

---
___
*[LibOS/shim/src/shim_call.c, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdSZYJ-tvUv5qQcoYj:-MvdSZYK-VaXiyaghT6B:b-e2gfz1) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_call.c#L9)):*
> ```C
> 
> #include <linux/errno.h>
> #include <limits.h>
> ```

I think we need this one for `INT_MAX` used in `run_test_ubsan_int_overflow()`.
___
*[LibOS/shim/src/shim_debug.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTYBr5WG7DjfLlDSN:-MvdTYBr5WG7DjfLlDSO:bl6ttyw) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L12)):*
> ```C
>  */
> 
> #include "list.h"
> ```

This one is needed for `DEFINE_LISTP()` and similar.
___
*[LibOS/shim/src/shim_debug.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTgcf34jzZSbZbGTq:-MvdTgcf34jzZSbZbGTr:b-6q8dh0) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L15)):*
> ```C
> #include "pal.h"
> #include "shim_checkpoint.h"
> #include "shim_lock.h"
> ```

And this one for `create_lock()`


<!-- Sent from Reviewable.io -->

2022-02-11 17:44 UTC, boryspoplawski requested changes
> Reviewed 12 of 145 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[common/src/string/memcmp.c, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvbpa3eBxGDcGNGjnyj:-MvdKKAI9BrSaVxb4AEj:b-pmjyes) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/common/src/string/memcmp.c#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds good. I'm approving then.
</blockquote></details>

Yup, we should.
___
*[common/src/string/memset.c, line 27 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdKq0XD3kBqQW7C559:-MvdKq0XD3kBqQW7C55A:b-wfqj1b) ([raw file](https://github.com/gramineproject/gramine/blob/13623d9a39542d20594100947c6ef0205d76a613/common/src/string/memset.c#L27)):*
> ```C
>      * Intel 64 and IA-32 Architectures Optimization Reference Manual
>      */
>     __asm__ volatile("rep stosb" : "+D"(d), "+c"(count) : "a"((uint8_t)ch) : "cc", "memory");
> ```

We could change `uint8_t` -> `char` here and drop `stdint.h` include, but not blocking.
___
*[LibOS/shim/include/shim_checkpoint.h, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdLWUp8AYK1BhhOtMw:-MvdLWUp8AYK1BhhOtMx:bkcclbv) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/include/shim_checkpoint.h#L15)):*
> ```objc
> 
> #include "pal.h"
> #include "shim_defs.h"
> ```

If we drop this, then we should move `CP_INIT_VMA_SIZE` from it to there (where I think it belongs).
___
*[LibOS/shim/include/shim_utils.h, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdrLkw2n-KroXgKvwk:-MvdrLkw2n-KroXgKvwl:b-42omua) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/include/shim_utils.h#L9)):*
> ```objc
> #include "api.h"
> #include "list.h"
> #include "pal.h"
> ```

Do we need `pal.h` and `api.h` here? I don't see why would we...
___
*[LibOS/shim/src/shim_debug.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvdsc8y21NBKagE7A_o:-Mvdsc8y21NBKagE7A_p:bum2zsr) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L16)):*
> ```C
> #include "shim_checkpoint.h"
> #include "shim_lock.h"
> #include "shim_types.h"
> ```

This is needed for `struct shim_lock`
Actually that type should be in `shim_lock.h`, but that's another story.


<!-- Sent from Reviewable.io -->

2022-02-12 02:02 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_checkpoint.h, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdLWUp8AYK1BhhOtMw:-MvfeGXREI15-Z8FOyAM:bvq8bd4) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/include/shim_checkpoint.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If we drop this, then we should move `CP_INIT_VMA_SIZE` from it to there (where I think it belongs).
</blockquote></details>

Actually, `shim_checkpoint.c` has included `shim_vma.h` which has `shim_def.h` in it. Any suggestion?
___
*[LibOS/shim/include/shim_utils.h, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdrLkw2n-KroXgKvwk:-MvfXzeu4LqhMVxYe5mk:b-smgpqi) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/include/shim_utils.h#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need `pal.h` and `api.h` here? I don't see why would we...
</blockquote></details>

Looks like we need `pal.h` for PAL_HANDLE and `api.h` for TIME_NS_IN_US etc.
___
*[LibOS/shim/src/shim_call.c, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdSZYJ-tvUv5qQcoYj:-MvfZZp62q5KaqkozjD3:b6fbwe7) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_call.c#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we need this one for `INT_MAX` used in `run_test_ubsan_int_overflow()`.
</blockquote></details>

Good catch! Yes, I did not check carefully the logic in `#ifdef UBSAN`.
___
*[LibOS/shim/src/shim_debug.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTYBr5WG7DjfLlDSN:-MvfcnG1AWzS-wjpczZf:b-8a1tz7) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This one is needed for `DEFINE_LISTP()` and similar.
</blockquote></details>

Yep, `list.h` is actually included in `shim_utils.h`. That's why I only left the include of `shim_utils.h` (a bit misleading...). WDYT?
___
*[LibOS/shim/src/shim_debug.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTgcf34jzZSbZbGTq:-Mvfbm9n0QxOk2jNMhi5:b-veshfy) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And this one for `create_lock()`
</blockquote></details>

`shim_lock.h` is included in `shim_handle.h` which is thus included in `shim_util.h`. For the same reason above...
___
*[LibOS/shim/src/shim_debug.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvdsc8y21NBKagE7A_o:-Mvfb4nm12GRpB7mCgHE:belcgva) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is needed for `struct shim_lock`
Actually that type should be in `shim_lock.h`, but that's another story.
</blockquote></details>

Yep, `shim_types.h` is actually included in `shim_utils.h`. For the same reason above...


<!-- Sent from Reviewable.io -->

2022-02-12 02:20 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_debug.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTYBr5WG7DjfLlDSN:-Mvfh5JJ0JCyBRDeYhws:b-ko1f9o) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L12)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yep, `list.h` is actually included in `shim_utils.h`. That's why I only left the include of `shim_utils.h` (a bit misleading...). WDYT?
</blockquote></details>

Despite looking like this, `shim_utils.h` is not meant to be a "include me to get all other random headers included"-type header ;) We just have some random function declarations there, and `list.h` seems to be actually unused there, so it should be removed from it.
The only "bulk include" headers we have are `pal.h` and `api.h`, but mostly due to historic reasons and because we didn't refactor them yet :)
___
*[LibOS/shim/src/shim_debug.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTgcf34jzZSbZbGTq:-Mvfi3uJCZ9ygiuKDQv2:bx0hi2m) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L15)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

`shim_lock.h` is included in `shim_handle.h` which is thus included in `shim_util.h`. For the same reason above...
</blockquote></details>

But we can't rely on `shim_handle.h` to include it (it's not a part of its "interface"), you need to include directly all the headers you need.


<!-- Sent from Reviewable.io -->

2022-02-14 01:55 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_checkpoint.h, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdLWUp8AYK1BhhOtMw:-MvpuGrI1XHSeOM0vP03:b-2txrx6) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/include/shim_checkpoint.h#L15)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Actually, `shim_checkpoint.c` has included `shim_vma.h` which has `shim_def.h` in it. Any suggestion?
</blockquote></details>

Agree, moving `CP_INIT_VMA_SIZE` to `shim_checkpoint.h` and hence drop `shim_defs.h`.
___
*[LibOS/shim/src/shim_debug.c, line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTYBr5WG7DjfLlDSN:-Mvplr_s5KLGy2JkXrI2:b-mqvozk) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Despite looking like this, `shim_utils.h` is not meant to be a "include me to get all other random headers included"-type header ;) We just have some random function declarations there, and `list.h` seems to be actually unused there, so it should be removed from it.
The only "bulk include" headers we have are `pal.h` and `api.h`, but mostly due to historic reasons and because we didn't refactor them yet :)
</blockquote></details>

Thanks! I've made `list.h` and `shim_lock.h` back.
___
*[LibOS/shim/src/shim_debug.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-MvdTgcf34jzZSbZbGTq:-Mvpmaxi-1eZPZ9n6xFp:bukgwpo) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we can't rely on `shim_handle.h` to include it (it's not a part of its "interface"), you need to include directly all the headers you need.
</blockquote></details>

Thanks, totally agree. :)
___
*[LibOS/shim/src/shim_debug.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvdsc8y21NBKagE7A_o:-Mvpo8BV6ZuDtH49RlIq:b7217fb) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L16)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yep, `shim_types.h` is actually included in `shim_utils.h`. For the same reason above...
</blockquote></details>

There is a circular dependency between `shim_lock.h` and `shim_thread.h`on `struct shim_lock` so that we cannot simply move it out of `shim_types.h`.
I'm moving back `shim_types.h` and let's address the above question in a follow-up patch.


<!-- Sent from Reviewable.io -->

2022-02-14 02:06 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-14 02:06 UTC, mkow commented
Jenkins, test this please

2022-02-14 09:55 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-14 16:45 UTC, boryspoplawski requested changes
> Reviewed 69 of 145 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @kailun-qin)

___
*[LibOS/shim/src/shim_debug.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvdsc8y21NBKagE7A_o:-Mvrsmr27JEzDwwO6rQb:b-4a9elk) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L16)):*
Ah, that would explain some things...

> let's address the above question in a follow-up patch

Sure!

Please sort the headers here, they got mixed
___
*[LibOS/shim/src/shim_parser.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvrtxfG9-LqdOqbVX8D:-MvrtxfG9-LqdOqbVX8E:bfacqs2) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_parser.c#L25)):*
> ```C
> #include "pal_error.h"
> #include "shim_internal.h"
> #include "shim_syscalls.h"
> ```

This include is needed for some syscalls numbers (see the comment in that header).
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvrvZzDDNo282ZThQXB:-MvrvZzDDNo282ZThQXC:b-mno6c6) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/bookkeep/shim_pid.c#L16)):*
> ```C
> #include "shim_lock.h"
> #include "shim_types.h"
> #include "shim_utils.h"
> ```

This one brings `malloc` and `free` (`api.h` does the same, but it's not included in here, it's all one big mess)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvsANsf9y9tKI6K-zSt:-MvsANsf9y9tKI6K-zSu:b-pb6558) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/fs/chroot/fs.c#L31)):*
> ```C
> #include "shim_lock.h"
> #include "shim_thread.h"
> #include "shim_utils.h"
> ```

ditto (malloc)
___
*[LibOS/shim/src/sys/shim_getuid.c, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4-eH6edf-I3tREwy:-Mvt4-eH6edf-I3tREwz:b2n70zs) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_getuid.c#L7)):*
> ```C
>  */
> 
> #include "api.h"
> ```

This provides `malloc()`
___
*[LibOS/shim/src/sys/shim_getuid.c, line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt3mnpApUypeOE_r7s:-Mvt3mnpApUypeOE_r7t:be7vxpo) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_getuid.c#L13)):*
> ```C
> #include "shim_table.h"
> #include "shim_thread.h"
> #include "shim_types.h"
> ```

NP: in theory we need this for `uit_t` which we use in one of the functions (inside, not in declaration)
___
*[LibOS/shim/src/sys/shim_poll.c, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4XGoDsPdhhA9tzQA:-Mvt4XGoDsPdhhA9tzQB:b-pb6558) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_poll.c#L20)):*
> ```C
> #include "shim_table.h"
> #include "shim_thread.h"
> #include "shim_utils.h"
> ```

ditto (malloc)
___
*[LibOS/shim/src/sys/shim_socket.c, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt540LCOta2PBv-Osl:-Mvt540LCOta2PBv-Osm:bk5xi8x) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_socket.c#L11)):*
> ```C
> #include <asm/socket.h>
> #include <errno.h>
> #include <linux/fcntl.h>
> ```

I think this one was used for `O_NONBLOCK`
___
*[LibOS/shim/src/sys/shim_socket.c, line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4lFOE6UvWIjUtw2i:-Mvt4lFOE6UvWIjUtw2j:b-pb6558) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_socket.c#L28)):*
> ```C
> #include "shim_signal.h"
> #include "shim_table.h"
> #include "shim_utils.h"
> ```

ditto (malloc)


<!-- Sent from Reviewable.io -->

2022-02-14 17:30 UTC, boryspoplawski requested changes
> Reviewed 64 of 145 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[Pal/src/host/Linux/db_rtld.c, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt9iLB7z6oyYMIKofC:-Mvt9iLB7z6oyYMIKofD:b-vyha3y) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux/db_rtld.c#L20)):*
> ```C
> #include "elf/elf.h"
> #include "pal.h"
> #include "pal_internal.h"
> ```

I think this header provides definitions for all `_DkXXXXX` functions
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvtEMHX9RNQ9-r4S-hd:-MvtEMHZDjIXc_ugArku:b-smv1db) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/db_threading.c#L8)):*
> ```C
>  */
> 
> #include <stddef.h> /* needed by <linux/signal.h> for size_t */
> ```

What about this one?
___
*[Pal/src/host/Linux-SGX/sgx_syscall.h, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvtGMTa4K-YKfUe73p7:-MvtGMTbBI2xpyXDbLV7:bbpqchf) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/sgx_syscall.h#L4)):*
> ```objc
> #define SGX_SYSCALL_H_
> 
> #include "syscall.h"
> ```

I think it was intended so that this header exports all `DO_SYSCALL*` macros


<!-- Sent from Reviewable.io -->

2022-02-15 04:12 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: 120 of 146 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/shim_parser.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvrtxfG9-LqdOqbVX8D:-MvvTWbx2r7tjyB59Q2n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_parser.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This include is needed for some syscalls numbers (see the comment in that header).
</blockquote></details>

Done.



_Code quote:_
```C
shim_syscalls.h
```
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvrvZzDDNo282ZThQXB:-MvvTs7FEF-SBC84EEga:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/bookkeep/shim_pid.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This one brings `malloc` and `free` (`api.h` does the same, but it's not included in here, it's all one big mess)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvsANsf9y9tKI6K-zSt:-MvvS8w9CfYD8-9QfOjD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/fs/chroot/fs.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (malloc)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_getuid.c, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4-eH6edf-I3tREwy:-MvvUFs619xthGOjk0CI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_getuid.c#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This provides `malloc()`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_getuid.c, line 13 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt3mnpApUypeOE_r7s:-MvvURTZCoaDdsAY0D4l:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_getuid.c#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: in theory we need this for `uit_t` which we use in one of the functions (inside, not in declaration)
</blockquote></details>

Done.



_Code quote:_
```C
#include "api.h"
```
___
*[LibOS/shim/src/sys/shim_poll.c, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4XGoDsPdhhA9tzQA:-MvvRvmI0VlpwZ8CT5Um:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_poll.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (malloc)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt540LCOta2PBv-Osl:-MvvRRGKEnTroU6k7_MD:b60r506) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_socket.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this one was used for `O_NONBLOCK`
</blockquote></details>

Yes, done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 28 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt4lFOE6UvWIjUtw2i:-MvvRqjSAonEcQVqJqli:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/sys/shim_socket.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (malloc)
</blockquote></details>

Done.



_Code quote:_
```C
#include "shim_utils.h"
```
___
*[Pal/src/host/Linux/db_rtld.c, line 20 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvt9iLB7z6oyYMIKofC:-MvvQwbj9bnJMXA5KOi4:b-9f087b) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux/db_rtld.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this header provides definitions for all `_DkXXXXX` functions
</blockquote></details>

Yep, done.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvtEMHX9RNQ9-r4S-hd:-MvvQ322-iMKKGrXXKDc:b-sycm8y) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/db_threading.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about this one?
</blockquote></details>

I think it's for `NULL`. Removed the comment as it's not appropriate.
___
*[LibOS/shim/src/shim_debug.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/395#-Mvdsc8y21NBKagE7A_o:-MvvNy5o2soR91ipUue9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/LibOS/shim/src/shim_debug.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, that would explain some things...

> let's address the above question in a follow-up patch

Sure!

Please sort the headers here, they got mixed
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_syscall.h, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/395#-MvtGMTa4K-YKfUe73p7:-MvvPM7t0ZuxKrbGmjZl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d/Pal/src/host/Linux-SGX/sgx_syscall.h#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it was intended so that this header exports all `DO_SYSCALL*` macros
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 04:14 UTC, kailun-qin commented
Resolved conflicts and rebased.

2022-02-15 07:10 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwCf0C-qBtCgUvxZ-e:-MvwCf0C-qBtCgUvxZ-f:bgz4prp) (no related file):*
@kailun-qin For the future: please do not rebase PRs. We will do that when merging the PR (or ask you to do so), in the mean time it just bloats the review

---


<!-- Sent from Reviewable.io -->

2022-02-15 07:32 UTC, dimakuv commented
Jenkins, test this please

2022-02-15 07:49 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-MvwLqCq-r5umawBvbFM:bied8eu) (no related file):*
@kailun-qin Gramine build failed with:
```
../LibOS/shim/src/fs/shim_namei.c: In function ‘lookup_enter_dentry’:
../LibOS/shim/src/fs/shim_namei.c:254:65: error: ‘PERM_r_xr_xr_x’ undeclared (first use in this function)
             ret = synthetic_setup_dentry(lookup->dent, S_IFDIR, PERM_r_xr_xr_x);
                                                                 ^~~~~~~~~~~~~~
```

Please fix.

---


<!-- Sent from Reviewable.io -->

2022-02-15 08:25 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: 145 of 146 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-MvwTuM72a9-1korkHBa:boxnw4e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Gramine build failed with:
```
../LibOS/shim/src/fs/shim_namei.c: In function ‘lookup_enter_dentry’:
../LibOS/shim/src/fs/shim_namei.c:254:65: error: ‘PERM_r_xr_xr_x’ undeclared (first use in this function)
             ret = synthetic_setup_dentry(lookup->dent, S_IFDIR, PERM_r_xr_xr_x);
                                                                 ^~~~~~~~~~~~~~
```

Please fix.
</blockquote></details>

Done. It's quite interesting that my patch is based on a older commit (329a12f15baf3efa1ce25cf2419a3e5af3c9b156) but CI is testing agains a newer one (02e445c489707a2e33d945b3c1ae40eeb366a971). :)

---


<!-- Sent from Reviewable.io -->

2022-02-15 09:01 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-MvwasEq-iP16KRoj_17:b-syiofg) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done. It's quite interesting that my patch is based on a older commit but CI is testing agains a newer one. :)
</blockquote></details>

We use Jenkins in our CI. Jenkins is known to merge PRs into the current tip of the repository: if the merge succeeds, then Jenkins tests against the "tip + PR changes", if the merge has conflicts, then Jenkins backs off and tests the PR changes only.

There is no way around this weird Jenkins feature. Because of this feature, we sometimes need to rebase PRs for no good reason, but just to make Jenkins stop this behavior.

---


<!-- Sent from Reviewable.io -->

2022-02-15 09:01 UTC, dimakuv commented
Jenkins, test this please

2022-02-15 09:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-MvwiUczD5pG9pVbxy61:b-d4fob6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We use Jenkins in our CI. Jenkins is known to merge PRs into the current tip of the repository: if the merge succeeds, then Jenkins tests against the "tip + PR changes", if the merge has conflicts, then Jenkins backs off and tests the PR changes only.

There is no way around this weird Jenkins feature. Because of this feature, we sometimes need to rebase PRs for no good reason, but just to make Jenkins stop this behavior.
</blockquote></details>

AFAIK, this is possible to disable, but in my opinion this feature is good to have: if your PR is going to break the master branch after merging (or rebasing!), it's good to know about this as early as possible.

---


<!-- Sent from Reviewable.io -->

2022-02-15 11:06 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-15 11:08 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-Mvx39c09KZZI1xpaHQ1:br1uwbv) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

AFAIK, this is possible to disable, but in my opinion this feature is good to have: if your PR is going to break the master branch after merging (or rebasing!), it's good to know about this as early as possible.
</blockquote></details>

I disagree: when I want to test a PR, I want to test the exact code I submitted, not some random merge of what Jenkins thinks is what I want.

---


<!-- Sent from Reviewable.io -->

2022-02-15 13:36 UTC, mkow submitted a review, later dismissed
> Reviewed 25 of 26 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-15 15:16 UTC, mkow commented
Jenkins, retest this please

2022-02-15 15:18 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/395)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/395#-MvwLqCq-r5umawBvbFL:-Mvxv_-y28kfe5gIBiZs:b46g1er) (no related file):*
Yup, I agree with Borys. I hate this feature, but AFAIR it wasn't possible to disable it? I remember at least a few cases where we were debugging runtime failures on tests just to notice after an hour that Jenkins was running different code than we were debugging.

> if your PR is going to break the master branch after merging (or rebasing!), it's good to know about this as early as possible.

Ad this: When merging to `master` we always fast forward to a commit tested in CI, so the only thing this can give us is earlier detection. But I think the damage caused by running unexpected code and then wasting time is bigger than this ;)

---


<!-- Sent from Reviewable.io -->

2022-02-15 16:38 UTC, merged