[LibOS] Convert `fs.mount` to an array
gramineproject/gramine pull request #411
Opened 2022-02-16 12:39 UTC by pwmarcz

## Description of the changes 

This converts the `fs.mount` manifest key to an array instead of table. Similar to `sgx.{trusted,allowed,protected}_files`, an array can be parsed more efficiently. It's also more natural, because order matters when specifying mount points.

The old (table) syntax is still accepted, but triggers a deprecation warning.

This commit converts the main manifest for regression tests. Other manifests will be converted later.

In addition, Gramine now allows omitting the `type` key (with "chroot" as default) and the `uri` key (so that it's easier to use the `tmpfs` filesystem).

Issue: #23 (although we might want to close it after the deprecated syntax is gone).

Prerequisite for #371: new syntax for trusted/protected files.

## How to test this PR? 

The `manifest.template` in LibOS regression tests should exercise the new code. You can modify it to check how things fail.

2022-02-16 17:47 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 335 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2PvAV7F8Fn-2ddJdT:-Mw2PvAV7F8Fn-2ddJdU:bzgg607) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L335)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^
> 
> ::
> ```

It was already like this before, but could you use TOML syntax highlighting here?
___
*[Documentation/manifest-syntax.rst, line 342 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2Q84r7LLEi0OOI9k7:-Mw2Q84r7LLEi0OOI9k8:bwub6i8) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L342)):*
> ```reStructuredText
>     ]
> 
>     # or, as separate sections:
> ```

I'd rather move this comment to normal text and split these snippets into two (it will be more visible that these are alternatives, not just one long snippet).
___
*[Documentation/manifest-syntax.rst, line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2QmhU8NWLNIRSz5bu:-Mw2QmhU8NWLNIRSz5bv:b-j4dup8) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L383)):*
> ```reStructuredText
>   host-level files. The tmpfs files are created under ``[PATH]`` (this path is
>   empty on Gramine instance startup) and are destroyed when a Gramine instance
>   terminates. The ``[URI]`` parameter is always ignored, and can be omitted.
> ```

Maybe we should actually error out on this? (after some grace period with only a warning)



_Code quote:_
```reStructuredText
and can be omitted
```
___
*[LibOS/shim/src/fs/shim_fs.c, line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2c-9v22ZKpArm1cxg:-Mw2c-9w7d1ofI9PviW8:b-a2c3rw) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L309)):*
> ```C
> }
> 
> static int mount_others_from_toml_array(void) {
> ```

What does this "others" mean here and in the function above? I was always puzzled by this `mount_one_other`.
___
*[LibOS/shim/src/fs/shim_fs.c, line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2cXsM3uYBoBubhBSg:-Mw2cXsN1WOraXeGFccs:b-eew34f) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L332)):*
> ```C
>         }
> 
>         /* Prepare a key for `mount_one_other`, so that it in case of errors it will display paths
> ```

Too many "it"s?



_Code quote:_
```C
it in case of errors it will
```


<!-- Sent from Reviewable.io -->

2022-02-17 10:06 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 342 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2Q84r7LLEi0OOI9k7:-Mw62nR43162fHjs0mKh:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L342)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather move this comment to normal text and split these snippets into two (it will be more visible that these are alternatives, not just one long snippet).
</blockquote></details>

+1
___
*[Documentation/manifest-syntax.rst, line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw634Yr5nybnwtMgW3g:-Mw634Yr5nybnwtMgW3h:bo83vof) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L361)):*
> ```reStructuredText
> The ``fs.mount`` option is a TOML array of tables. As shown in the examples
> above, you can either specify its value using the inline syntax, or use multiple
> ``[[fs.mount]]`` sections.
> ```

Why is this paragraph useful? I think it only duplicates the example above. Developers (who know TOML) won't get anything new from this para, and casual users will only get confused. So I think we should remove this para.
___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw63Ic-4N5dnjZDMIkc:-Mw63Ic-4N5dnjZDMIkd:b-ulyjcu) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L366)):*
> ```reStructuredText
>    If you use the inline table syntax (``{ ... }``), each table should fit in
>    a single line. While multi-line tables are currently accepted by Gramine,
>    they are not valid TOML and Gramine might disallow them in the future.
> ```

I would remove this note as well. This is a controversial feature of TOML, and chances are high that it will be the TOML spec that will allow this, not Gramine that will disallow this. Anyway, the users don't read these fine prints anyway, they just look at the examples under `CI-Examples` :)
___
*[LibOS/shim/src/fs/shim_fs.c, line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw65DDaDnelxvspAFpa:-Mw65DDaDnelxvspAFpb:b-j6csfm) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L120)):*
> ```C
>         ret = mount_fs("chroot", fs_root_uri, "/");
>     } else {
>         ret = mount_fs(fs_root_type, fs_root_uri ?: "", "/");
> ```

What is this `fs_root_uri ?: ""`? This case is like this:
```
fs_root_type = "tmpfs"
fs_root_uri = NULL
```

I guess you're replacing NULL with an empty string to not deal with a NULL corner case?
___
*[LibOS/shim/src/fs/shim_fs.c, line 208 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw6798M8cL5o7TL6EQX:-Mw6798M8cL5o7TL6EQY:b-xwor97) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L208)):*
> ```C
>         ret = mount_fs("chroot", mount_uri, mount_path);
>     } else {
>         ret = mount_fs(mount_type, mount_uri ?: "", mount_path);
> ```

ditto (why empty string instead of NULL?)
___
*[LibOS/shim/src/fs/shim_fs.c, line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw673bTAB3FCdjeGHS8:-Mw673bTAB3FCdjeGHS9:bja6p0k) ([raw file](https://github.com/gramineproject/gramine/blob/b571f2a3efda7d20db958ea1a7880b109acaa9c0/LibOS/shim/src/fs/shim_fs.c#L218)):*
> ```C
>             "Root mount / already exists, verify that there are no duplicate mounts in manifest\n"
>             "(note that root / is automatically mounted in Gramine and can be changed via "
>             "'fs.root' manifest entry).\n");
> ```

Why did you remove this?
___
*[LibOS/shim/src/fs/shim_fs.c, line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw675sq0ECUf_gNs1sv:-Mw675sq0ECUf_gNs1sw:bja6p0k) ([raw file](https://github.com/gramineproject/gramine/blob/b571f2a3efda7d20db958ea1a7880b109acaa9c0/LibOS/shim/src/fs/shim_fs.c#L224)):*
> ```C
> 
>     if (!strcmp(mount_path, ".") || !strcmp(mount_path, "..")) {
>         log_error("Mount points '.' and '..' are not allowed, remove them from manifest.");
> ```

Why did you remove this?
___
*[LibOS/shim/test/regression/manifest.template, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw64L0CAtZd83T_jvG6:-Mw64L0CAtZd83T_jvG7:b-eozsn3) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/test/regression/manifest.template#L18)):*
> ```
>   { path = "/usr/{{ arch_libdir }}", uri = "file:/usr/{{ arch_libdir }}" },
>   { path = "/bin", uri = "file:/bin" },
>   { type = "tmpfs", path = "/mnt/tmpfs" },
> ```

Maybe separate this `tmpfs` entry with a newline? For readability.
___
*[LibOS/shim/test/regression/manifest.template, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw647upA92rbO_35qPA:-Mw647uq0DQ6_xEhSr37:byr4dgo) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/test/regression/manifest.template#L19)):*
> ```
>   { path = "/bin", uri = "file:/bin" },
>   { type = "tmpfs", path = "/mnt/tmpfs" },
> ]
> ```

Could we indent `uri` fields at the same level, so it's easier to read?

Right now it's messy and very hard to read: https://github.com/gramineproject/gramine/blob/pawel/mount-array-2/LibOS/shim/test/regression/manifest.template


<!-- Sent from Reviewable.io -->

2022-02-17 11:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: 0 of 3 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 335 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2PvAV7F8Fn-2ddJdT:-Mw67_geAOVbGeb2-cTi:bjd0a75) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L335)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was already like this before, but could you use TOML syntax highlighting here?
</blockquote></details>

Done (the `highlight` directive at the top).
___
*[Documentation/manifest-syntax.rst, line 342 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2Q84r7LLEi0OOI9k7:-Mw6KNp01GtRmcKXhB9V:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L342)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 361 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw634Yr5nybnwtMgW3g:-Mw6Hd401lbyPET-XH5a:b-gij58x) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L361)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this paragraph useful? I think it only duplicates the example above. Developers (who know TOML) won't get anything new from this para, and casual users will only get confused. So I think we should remove this para.
</blockquote></details>

OK, I agree it doesn't add much.
___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw63Ic-4N5dnjZDMIkc:-Mw6Hi0UCgNSCUhoLPCi:bf6hzq1) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L366)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this note as well. This is a controversial feature of TOML, and chances are high that it will be the TOML spec that will allow this, not Gramine that will disallow this. Anyway, the users don't read these fine prints anyway, they just look at the examples under `CI-Examples` :)
</blockquote></details>

The actual problem here is that we disallow a trailing comma in tables. This will work in Gramine:

```toml
fs.mount = [
  {
    path = "/bin",
    uri = "file:/usr/bin"
  },
]
```

This will break with a cryptic message from the Python library (when parsed by `gramine-manifest`):

```toml
fs.mount = [
  {
    path = "/bin",
    uri = "file:/usr/bin",
  },
]
```

If I don't discourage multi-line tables here, I think I need to at least add a warning about the traling comma. Do you think that's a better option?
___
*[Documentation/manifest-syntax.rst, line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2QmhU8NWLNIRSz5bu:-Mw67vJzDDuJ5mbzwGTJ:b-divrjv) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe we should actually error out on this? (after some grace period with only a warning)
</blockquote></details>

Should we? I don't think it hurts us to allow it, and it only makes the rules/code more complicated.
___
*[LibOS/shim/src/fs/shim_fs.c, line 120 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw65DDaDnelxvspAFpa:-Mw69K40CVwOKkQmHDiG:b-y8c3p0) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `fs_root_uri ?: ""`? This case is like this:
```
fs_root_type = "tmpfs"
fs_root_uri = NULL
```

I guess you're replacing NULL with an empty string to not deal with a NULL corner case?
</blockquote></details>

That's right. This parameter goes to the individual filesystems (chroot, pseudo-FS) and I don't want them all to check against NULL too.
___
*[LibOS/shim/src/fs/shim_fs.c, line 218 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw673bTAB3FCdjeGHS8:-Mw6A_IM8BvpByV76OO8:bz2frhb) ([raw file](https://github.com/gramineproject/gramine/blob/b571f2a3efda7d20db958ea1a7880b109acaa9c0/LibOS/shim/src/fs/shim_fs.c#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this?
</blockquote></details>

Right, this should stay (I reworded it though).
___
*[LibOS/shim/src/fs/shim_fs.c, line 224 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw675sq0ECUf_gNs1sv:-Mw6B17FB6UHbmGbfEEh:b70rxma) ([raw file](https://github.com/gramineproject/gramine/blob/b571f2a3efda7d20db958ea1a7880b109acaa9c0/LibOS/shim/src/fs/shim_fs.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this?
</blockquote></details>

That one was by accident too. I restored it.

Actually, this rule is kind of arbitrary. As discussed on Gitter, I'd like to deprecate all relative paths: they are interpreted relative to root anyway.
___
*[LibOS/shim/src/fs/shim_fs.c, line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2c-9v22ZKpArm1cxg:-Mw6D2Zo7LOS15OIbJwo:b-6rcgzn) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does this "others" mean here and in the function above? I was always puzzled by this `mount_one_other`.
</blockquote></details>

Filesystems other than the root one (`fs.root`). I can't think of a better name now, but I can change if you suggest one. :)
___
*[LibOS/shim/src/fs/shim_fs.c, line 332 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2cXsM3uYBoBubhBSg:-Mw6DQbg3ht-Q5pujwyx:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L332)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Too many "it"s?
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/test/regression/manifest.template, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw64L0CAtZd83T_jvG6:-Mw6KKMG4NCNATBc2JAK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/test/regression/manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe separate this `tmpfs` entry with a newline? For readability.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/manifest.template, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw647upA92rbO_35qPA:-Mw6JBtO3CgRMi4C9deY:b-6assxz) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/test/regression/manifest.template#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we indent `uri` fields at the same level, so it's easier to read?

Right now it's messy and very hard to read: https://github.com/gramineproject/gramine/blob/pawel/mount-array-2/LibOS/shi [...]

2022-02-17 11:54 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw63Ic-4N5dnjZDMIkc:-Mw6WKSrAWTEBxHsqEZK:b-rf0xae) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L366)):*
> If I don't discourage multi-line tables here, I think I need to at least add a warning about the traling comma. Do you think that's a better option?

Yes, I would prefer this warning (about the trailing comma).
___
*[LibOS/shim/test/regression/manifest.template, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw647upA92rbO_35qPA:-Mw6WxooEwf8RBSU2XeQ:b6mufu3) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/test/regression/manifest.template#L19)):*
>  Adding a new path will likely mean having to realign the whole array, and break git diff/blame in the process.

That's a good point. Let's not re-align then, but keep your current version.

> If the inline syntax is hard to read without such special formatting, maybe that means we should not use it? We can instead use the multi-line syntax (but it's non-standard, and annoying because of the trailing comma thing), or TOML sections.

No, the current version is definitely better than the verbose TOML sections. I like it very much that this manifest is short and crisp.


<!-- Sent from Reviewable.io -->

2022-02-17 12:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: 2 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/manifest-syntax.rst, line 366 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw63Ic-4N5dnjZDMIkc:-Mw6fynOAqYPkVSrY0dh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L366)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> If I don't discourage multi-line tables here, I think I need to at least add a warning about the traling comma. Do you think that's a better option?

Yes, I would prefer this warning (about the trailing comma).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-17 14:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-02-17 16:06 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/manifest-syntax.rst, line 335 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2PvAV7F8Fn-2ddJdT:-Mw7Q4DG0IpHJJZwdNAS:ble5wou) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L335)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done (the `highlight` directive at the top).
</blockquote></details>

Sorry, I actually cannot :) See the TODO I added.

Probably the best solution is to change the "meta-syntax" in this file, but I'm out of ideas, and I don't want to solve it right now...


<!-- Sent from Reviewable.io -->

2022-02-17 16:41 UTC, mkow reviewed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 335 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2PvAV7F8Fn-2ddJdT:-Mw7VlVV9YvUHxVxQCl8:b-sq4802) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L335)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sorry, I actually cannot :) See the TODO I added.

Probably the best solution is to change the "meta-syntax" in this file, but I'm out of ideas, and I don't want to solve it right now...
</blockquote></details>

Ah, too bad :( Let's leave it for later then.
___
*[Documentation/manifest-syntax.rst, line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2QmhU8NWLNIRSz5bu:-Mw7WeriElH8XLCFG62J:b-71dndh) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L383)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Should we? I don't think it hurts us to allow it, and it only makes the rules/code more complicated.
</blockquote></details>

My idea was that it could prevent user mistakes / confusion when they misunderstand how it works and set it, but then it's silently ignored. But not blocking.
___
*[LibOS/shim/src/fs/shim_fs.c, line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2c-9v22ZKpArm1cxg:-Mw7YYnA8DalZwbXhmE_:bcvdwit) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L309)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Filesystems other than the root one (`fs.root`). I can't think of a better name now, but I can change if you suggest one. :)
</blockquote></details>

Maybe just `nonroot`?


<!-- Sent from Reviewable.io -->

2022-02-17 17:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/manifest-syntax.rst, line 383 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2QmhU8NWLNIRSz5bu:-Mw7hGYg71GPh_sNlLd0:b-6m8qwa) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/Documentation/manifest-syntax.rst#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

My idea was that it could prevent user mistakes / confusion when they misunderstand how it works and set it, but then it's silently ignored. But not blocking.
</blockquote></details>

OK. I want to leave it like this for now, because this section of manifest is going to change anyway (with trusted/protected files) and keeping the rules simple will help me refactor. But let's watch out for user problems.
___
*[LibOS/shim/src/fs/shim_fs.c, line 309 at r1](https://reviewable.io/reviews/gramineproject/gramine/411#-Mw2c-9v22ZKpArm1cxg:-Mw7hmdE2TzsVyhFRYRt:b-k1y5pj) ([raw file](https://github.com/gramineproject/gramine/blob/6987eb795adcedc0539f58e37c7dc4fb41d4a5b1/LibOS/shim/src/fs/shim_fs.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just `nonroot`?
</blockquote></details>

OK. Done.


<!-- Sent from Reviewable.io -->

2022-02-17 17:29 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-18 07:20 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-18 10:14 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-02-18 10:23 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/411)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-18 10:28 UTC, merged