Convert `fifo` and `socket` filesystems to use inodes
gramineproject/gramine pull request #414
Opened 2022-02-16 16:46 UTC by pwmarcz

## Description of the changes 

This PR converts the remaining filesystems to inodes. I finally got rid of the ugly stash-FDs-in-pointer hack. In fact, we're already able to remove `data` and `lock` fields from dentry.

The next step will be to drastically simplify the dentry object, and replace most uses with inode.

## How to test this PR? 

Jenkins.

2022-02-17 11:14 UTC, pwmarcz commented
Jenkins, retest Jenkins-Debug-18.04 please (`fdatasync01` and `writev07` tests timing out again)

2022-02-17 20:56 UTC, mkow requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 687 at r1](https://reviewable.io/reviews/gramineproject/gramine/414#-Mw8CEe597kk6Sya4l2c:-Mw8CEe597kk6Sya4l2d:b-t6nlzt) ([raw file](https://github.com/gramineproject/gramine/blob/9d9f9bd5598b19ba2fb241fd08e69dfa8e29cf0a/LibOS/shim/include/shim_fs.h#L687)):*
> ```
> Resets the following dentry fields: [...], `data`, [...]
> ```

Didn't you just remove it? ;)


<!-- Sent from Reviewable.io -->

2022-02-18 09:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 687 at r1](https://reviewable.io/reviews/gramineproject/gramine/414#-Mw8CEe597kk6Sya4l2c:-MwB6mxV6AbT-ykBxcma:b-r5uj9b) ([raw file](https://github.com/gramineproject/gramine/blob/9d9f9bd5598b19ba2fb241fd08e69dfa8e29cf0a/LibOS/shim/include/shim_fs.h#L687)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Resets the following dentry fields: [...], `data`, [...]
> ```

Didn't you just remove it? ;)
</blockquote></details>

Good point! I split the removal out to a separate commit, and forgot to remove it from here. Fixed.


<!-- Sent from Reviewable.io -->

2022-02-19 17:08 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-21 11:11 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 168 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQtOan8BWh38b-5DaF:-MwQtOao-YjoA5RXe5z8:bw6j1l0) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/shim_dcache.c#L168)):*
> ```C
> 
>     dent->state = 0;
>     dent->fs = dent->mount ? dent->mount->fs : NULL;
> ```

How is it possible that `dent->mount` is NULL? Is it during the very-first dentry initialization?
___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwQv0fdEK1bgYN9QwHC:b-vmoysi) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
> ```C
>  *
>  * It would be better to store the temporary handles directly, without allocating FDs for them.
>  * However, using FDs makes it easier to checkpoint a named pipe.
> ```

Interesting. So theoretically Gramine can leak FDs (i.e., have holes in the FD map) if the user app never actually opens the named pipe?
___
*[LibOS/shim/src/fs/socket/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQxaVnCeVru-iQlhsB:-MwQxaVnCeVru-iQlhsC:b-h5ajcx) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/socket/fs.c#L19)):*
> ```C
> #include "stat.h"
> 
> int socket_setup_dentry(struct shim_dentry* dent, mode_t perm) {
> ```

Is this only for UNIX domain sockets (we also call them "UNIX sockets" in the code)? If yes, maybe rename to `unix_socket_setup_dentry`? Otherwise it looks weird.
___
*[LibOS/shim/src/sys/shim_socket.c, line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQx-gL1NBMIArROhfN:-MwQx-gL1NBMIArROhfO:b-t8nxv8) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/sys/shim_socket.c#L445)):*
> ```C
> 
> /*
>  * Retrieve or create a socket dentry at `path`. Used inside `bind()` and `connect()`.
> ```

`a socket dentry` -> `a UNIX socket dentry`
___
*[LibOS/shim/src/sys/shim_socket.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQyTbn8g9j6qz6zko8:-MwQyTboCNfRxZBirafA:b-mra3d2) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/sys/shim_socket.c#L598)):*
> ```C
>         if (sock->domain == AF_UNIX) {
>             if (sock->addr.un.dentry) {
>                 /* TODO: This leaves a file at `dentry` when we failed to bind. */
> ```

You mean that there will be a dangling file on the host in this case? (Because we don't call `unlink` here.)


<!-- Sent from Reviewable.io -->

2022-02-22 10:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 168 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQtOan8BWh38b-5DaF:-MwVwXgL0VHIPJ2kvs-e:be0ocru) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/shim_dcache.c#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is it possible that `dent->mount` is NULL? Is it during the very-first dentry initialization?
</blockquote></details>

Yes, the very first dentry is unfortunately without a mount, so we don't guarantee `dent->mount` to be there. (In practice this function should never be called on such a dentry, but I think it's better not to rely on that).
___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwVxEBYCNq3CD_LjuWs:bjnial7) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting. So theoretically Gramine can leak FDs (i.e., have holes in the FD map) if the user app never actually opens the named pipe?
</blockquote></details>

Yes. And in practice a process will open only one end of the pipe, unfortunately.

It would be nice to fix that. Maybe after we do something with the checkpointing system?
___
*[LibOS/shim/src/fs/socket/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQxaVnCeVru-iQlhsB:-MwVxma5E3P8-Q-rjCaF:b-ny7ax5) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/socket/fs.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this only for UNIX domain sockets (we also call them "UNIX sockets" in the code)? If yes, maybe rename to `unix_socket_setup_dentry`? Otherwise it looks weird.
</blockquote></details>

OK. It looks a bit weird to me since the filesystem is called `socket`, but it's probably better than explaining the same thing in the comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 445 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQx-gL1NBMIArROhfN:-MwVy7HW5gcONN0bAUN5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/sys/shim_socket.c#L445)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`a socket dentry` -> `a UNIX socket dentry`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQyTbn8g9j6qz6zko8:-MwVy7pBB5bgBBraB8Ne:bk3oy35) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/sys/shim_socket.c#L598)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You mean that there will be a dangling file on the host in this case? (Because we don't call `unlink` here.)
</blockquote></details>

Not on host, it's an in-memory-only file, but the application will see it.


<!-- Sent from Reviewable.io -->

2022-02-22 11:05 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwW5i8cCi67cqgwHJb_:bl6hr9j) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. And in practice a process will open only one end of the pipe, unfortunately.

It would be nice to fix that. Maybe after we do something with the checkpointing system?
</blockquote></details>

Sure. Checkpointing seems like a roadblock more and more.
___
*[LibOS/shim/src/sys/shim_socket.c, line 598 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQyTbn8g9j6qz6zko8:-MwW5u-s68sviw6ycFQb:bkq973u) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/sys/shim_socket.c#L598)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Not on host, it's an in-memory-only file, but the application will see it.
</blockquote></details>

Ok, got it.


<!-- Sent from Reviewable.io -->

2022-02-22 13:18 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwWZlCZ-keHivHEWE02:b-ruf06b) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sure. Checkpointing seems like a roadblock more and more.
</blockquote></details>

Hmm, I think we should start documenting what problems exactly we have with checkpointing, there's even no meta-issue for this yet. Any volunteer? I didn't have that many problems with them as you, so I'm not the best person to write all of that down ;)


<!-- Sent from Reviewable.io -->

2022-02-22 14:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwWrYiV6ltWMBpFg7JM:b-e9n1ga) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nah, why we need to write it now. When someone is assigned this task, we can start collecting the thoughts in Gitter/GitHub.
</blockquote></details>

I mean documenting problems with it, not proposing solutions. Better to document when we hit them, in half a year we'll forget all the specific cases where checkpointing was limiting us (but they will be crucial for designing a proper new version).


<!-- Sent from Reviewable.io -->

2022-02-22 15:15 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/pipe/fs.c, line 19 at r2](https://reviewable.io/reviews/gramineproject/gramine/414#-MwQv0fdEK1bgYN9QwHB:-MwX-4J09bOZZOh6zRrs:b-gtqzrr) ([raw file](https://github.com/gramineproject/gramine/blob/82cd7c812f414518d8f14474877a156280a75d73/LibOS/shim/src/fs/pipe/fs.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I mean documenting problems with it, not proposing solutions. Better to document when we hit them, in half a year we'll forget all the specific cases where checkpointing was limiting us (but they will be crucial for designing a proper new version).
</blockquote></details>

@mkow @pwmarcz  I started https://github.com/gramineproject/gramine/issues/423, let's dump all things related to checkpointing there


<!-- Sent from Reviewable.io -->

2022-02-22 18:01 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/414)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-22 18:52 UTC, merged