[LibOS/Pal] pass timeout value with correct type `struct timeval` to `setsockopt` syscall
gramineproject/gramine pull request #415
Opened 2022-02-17 06:35 UTC by jkr0103

## Description of the changes 
`setsockopt` syscall fails with socket options `SO_RCVTIMEO` and `SO_SNDTIMEO`. Argument for socket options `SO_RCVTIMEO` and `SO_SNDTIMEO` is a `struct timeval` but `int` type was used which causes the `setsockopt` syscall failure.

Changing the argument type to `struct timeval` from `int` with these socket options fixes the issue.

Fixes#[341](https://github.com/gramineproject/gramine/issues/341)

## How to test this PR? 
Added regression test in `gramine/LibOS/shim/test/regression/tcp_ipv6_v6only.c`
execute the test `tcp_ipv6_v6only` to verify the fix

2022-02-17 09:02 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5s9mkErmp9wwxN09D:-Mw5s9ml1s83v9cqmzrH:b8ejvrg) (no related file):*
We need to also fix `receivetimeout` and `sendtimeout` fields in all of Gramine codebase.

1. We must rename to `receivetimeout_us` and `sendtimeout_us`, so it's clear these variables are in microsecond units.
2. We must use `uint64_t` as their type everywhere (right now it's a wild mix of `PAL_NUM` and `int`).

The places where to fix these fields:
- https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux/pal_host.h#L87-L88?plain=1
- https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/Pal/src/host/Linux-SGX/linux_types.h#L124?plain=1
- https://github.com/gramineproject/gramine/blob/9d9f4cd9d0f6ef08519c4598d1a34b9625065c74/Pal/src/host/Linux-SGX/pal_host.h#L108-L109?plain=1
- https://github.com/gramineproject/gramine/blob/21f164183017f532de77cb781de1592a1e15913a/Pal/include/pal/pal.h#L423?plain=1

(Please check if these are all the places where we need to rename + change type for these fields.)

So for example in https://github.com/gramineproject/gramine/blob/66881cca331402825cf1b5f8c4f949a2c758892b/Pal/src/host/Linux/pal_host.h#L87-L88?plain=1 we'll replace to these lines:
```
            uint64_t receivetimeout_us;
            uint64_t sendtimeout_us;
```

---
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5rTAODwSRIg6SPxx8):*
I'll fix this message during rebase.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1811 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5syls-9Iur3LagwXZ:-Mw5syls-9Iur3LagwX_:b-r602r3) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/LibOS/shim/src/sys/shim_socket.c#L1811)):*
> ```C
>     bool need_set_attr = false;
>     int intval = *((int*)optval);
>     struct timeval tv  = *(struct timeval*)optval;
> ```

You can't do it here, unconditionally. You're reading `optval` (which may be a 4-byte integer object) as a 16-byte `struct timeval` object, so it may lead to segfaults and buffer overflows. Please remove from here, see my other comment.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1855 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5tBgGETn5_prFBBaI:-Mw5tBgGETn5_prFBBaJ:bescrp) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/LibOS/shim/src/sys/shim_socket.c#L1855)):*
> ```C
>                     need_set_attr = true;
>                 }
>                 break;
> ```

You need to move the `tv` declaration in these two cases. I suggest to refactor like this:
```
            case SO_RCVTIMEO:
                /* fallthrough */
            case SO_SNDTIMEO: {
                struct timeval tv = *(struct timeval*)optval;
                uint64_t timeout_us = tv.tv_sec * TIME_US_IN_S + tv.tv_usec;

                if (optname == SO_RCVTIMEO && timeout_us != attr->socket.receivetimeout_us) {
                    attr->socket.receivetimeout_us = timeout_us;
                    need_set_attr = true;
                }
                if (optname == SO_SNDTIMEO && timeout_us != attr->socket.sendtimeout_us) {
                    attr->socket.sendtimeout_us = timeout_us;
                    need_set_attr = true;
                }
                break;
            }
```
___
*[Pal/src/host/Linux/db_sockets.c, line 970 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uZnt90uTA6TeDciZ:-Mw5uZnt90uTA6TeDci_:bkyde3h) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux/db_sockets.c#L970)):*
> ```C
> 
>     int fd = handle->sock.fd, ret, val;
>     struct timeval tv = {0};
> ```

Please move this variable declaration to each of the `receivetimeout` and `sendtimeout` code blocks.
___
*[Pal/src/host/Linux/db_sockets.c, line 981 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uAzDAd-4fjWA2K7q:-Mw5uAzDAd-4fjWA2K7r:b56thri) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux/db_sockets.c#L981)):*
> ```C
>     }
> 
>         if (attr->socket.linger != handle->sock.linger) {
> ```

Please de-indent this whole block (remove first 4 spaces from each line)
___
*[Pal/src/host/Linux/db_sockets.c, line 1016 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uLkt2G31QfNhrwQz:-Mw5uLku2tHVT9PARGsh:bqf6rzx) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux/db_sockets.c#L1016)):*
> ```C
>         if (attr->socket.receivetimeout != handle->sock.receivetimeout) {
>             tv.tv_sec = attr->socket.receivetimeout / TIME_US_IN_S;
>             tv.tv_sec = attr->socket.receivetimeout % TIME_US_IN_S;
> ```

`tv.tv_sec` -> `tv.tv_usec`
___
*[Pal/src/host/Linux/db_sockets.c, line 1017 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uQo_5yXB5qJOhn0m:-Mw5uQoa8FNt03PVQC6l:b-yy0nkj) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux/db_sockets.c#L1017)):*
> ```C
>             tv.tv_sec = attr->socket.receivetimeout / TIME_US_IN_S;
>             tv.tv_sec = attr->socket.receivetimeout % TIME_US_IN_S;
>             ret = DO_SYSCALL(setsockopt, fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(struct timeval));
> ```

`sizeof(struct timeval)` -> `sizeof(tv)`
___
*[Pal/src/host/Linux/db_sockets.c, line 1027 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uTXg4ZlXEq9bCCYC:-Mw5uTXg4ZlXEq9bCCYD:b-yy0nkj) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux/db_sockets.c#L1027)):*
> ```C
>             tv.tv_sec  = attr->socket.sendtimeout / TIME_US_IN_S;
>             tv.tv_usec = attr->socket.sendtimeout % TIME_US_IN_S;
>             ret = DO_SYSCALL(setsockopt, fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(struct timeval));
> ```

`sizeof(struct timeval)` -> `sizeof(tv)`
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 728 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5ug2HDMrZz1WQdUGu:-Mw5ug2HDMrZz1WQdUGv:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux-SGX/db_sockets.c#L728)):*
> ```C
> 
>     int fd = handle->sock.fd, ret, val;
>     struct timeval tv = {0};
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 738 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uktr0poXLuUUaE75:-Mw5uktr0poXLuUUaE76:bcb00wu) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux-SGX/db_sockets.c#L738)):*
> ```C
>     }
> 
>         struct __kernel_linger {
> ```

ditto (de-indent)
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 775 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5uhA49w4NSN72wOj-:-Mw5uhA5846F1DSslnDu:b-d4xivg) ([raw file](https://github.com/gramineproject/gramine/blob/6737c4d658cc75df1414df7e2ab7e72d04b945ff/Pal/src/host/Linux-SGX/db_sockets.c#L775)):*
> ```C
>             tv.tv_sec = attr->socket.receivetimeout / TIME_US_IN_S;
>             tv.tv_usec = attr->socket.receivetimeout % TIME_US_IN_S;
>             ret = ocall_setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(struct timeval));
> ```

ditto (`sizeof`)
___
*[Pal/src/host/Linux-SGX/db_sockets.c, line 785 at r1](https://reviewable.io/reviews/gramin [...]

2022-02-18 07:53 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1803 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAkzrA36L9pgJtoAwl:-MwAkzrA36L9pgJtoAwm:b509qdm) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L1803)):*
> ```C
>     attr->socket.tcp_cork       = false;
>     attr->socket.tcp_keepalive  = false;
>     attr->socket.tcp_nodelay    = false;
> ```

Can you please re-align this block of variable assignments? I mean the same place of `=` on each line:
```
    attr->socket.linger            = 0;
    attr->socket.receivetimeout_us = 0;
    attr->socket.sendtimeout_us    = 0;
    attr->socket.tcp_cork          = false;
    .. and so on
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 2145 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlcnB1iModLga8TQ4:-MwAlcnB1iModLga8TQ5:b-j1f3nw) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2145)):*
> ```C
>                 break;
>             case SO_RCVTIMEO: {
>                 struct timeval *tv;
> ```

Wrong alignment of `*` symbol -- must be left-aligned.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2146 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAliDBAsukc9Jcj972:-MwAliDBAsukc9Jcj973:b-252jag) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2146)):*
> ```C
>             case SO_RCVTIMEO: {
>                 struct timeval *tv;
>                 tv = (struct timeval*)optval;
> ```

Why not just combine these two lines into one? :)

```
struct timeval* tv = (struct timeval*)optval;
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 2149 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlvIBE3caDqqhirA5:-MwAlvIBE3caDqqhirA6:betlf2u) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2149)):*
> ```C
>                 tv->tv_sec  = attr.socket.receivetimeout_us / TIME_US_IN_S;
>                 tv->tv_usec = attr.socket.receivetimeout_us % TIME_US_IN_S;
>                 *optlen = sizeof(struct timeval);
> ```

Please replace with simply `sizeof(*tv)`
___
*[LibOS/shim/src/sys/shim_socket.c, line 2153 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlfcq07OdTvJwQe1e:-MwAlfcq07OdTvJwQe1f:b-j1f3nw) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2153)):*
> ```C
>             }
>             case SO_SNDTIMEO: {
>                 struct timeval *tv;
> ```

Wrong alignment of `*` symbol -- must be left-aligned.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2154 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAloP62yVyZouJqQWf:-MwAloP62yVyZouJqQWg:b-252jag) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2154)):*
> ```C
>             case SO_SNDTIMEO: {
>                 struct timeval *tv;
>                 tv = (struct timeval*)optval;
> ```

Why not just combine these two lines into one? :)

```
struct timeval* tv = (struct timeval*)optval;
```
___
*[LibOS/shim/src/sys/shim_socket.c, line 2157 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAm19G1MMTj0gu4VX4:-MwAm19G1MMTj0gu4VX5:betlf2u) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2157)):*
> ```C
>                 tv->tv_sec = attr.socket.sendtimeout_us / TIME_US_IN_S;
>                 tv->tv_usec = attr.socket.sendtimeout_us % TIME_US_IN_S;
>                 *optlen = sizeof(struct timeval);
> ```

Please replace with simply `sizeof(*tv)`
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAmPuj5AQUVFhxKNKa:-MwAmPuj5AQUVFhxKNKb:b-ahuit2) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L16)):*
> ```C
> #define SRV_IPV4 "127.0.0.1"
> #define PORT     11112
> const time_t TIMEOUT = 5;
> ```

Please just use a macro: `#define TIMEOUT 5`

The type `time_t` is typically used to represent *actual time* (number of seconds elapsed from 1970). So it's a bit misleading to use `time_t` in your context.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAmhFuCGkNe2SJzZ9k:-MwAmhFuCGkNe2SJzZ9l:bkivkze) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L75)):*
> ```C
>     struct timeval tv = {0};
>     socklen_t optlen = sizeof(tv);
>     tv.tv_sec = TIMEOUT;
> ```

You can remove this line and augment the previous line with:
```
struct timeval tv = { .tv_sec = TIMEOUT };
```

(note that `tv_usec` will be initialized to zero implicitly)
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnXxp2i5701NBfSJp:-MwAnXxp2i5701NBfSJq:b-fxfbki) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L91)):*
> ```C
>         return 1;
>     }
>     if (tv.tv_sec != TIMEOUT) {
> ```

Please also add the following checks: ` || tv.tv_usec != 0 || optlen != sizeof(tv)`
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnjTgDvXK9wipsTOr:-MwAnjTgDvXK9wipsTOs:bdfhu7s) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L95)):*
> ```C
>         return 1;
>     }
> ```

Before the second `getsockopt()`, you need to reset the timeval and optlen variables for sanity:
```
    tv.tv_sec  = 0;
    tv.tv_usec = 0;
    optlen = sizeof(tv);
```
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 100 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnikhEiReoUvpWb7M:-MwAnikhEiReoUvpWb7N:b-fxfbki) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L100)):*
> ```C
>         return 1;
>     }
>     if (tv.tv_sec != TIMEOUT) {
> ```

Please also add the following checks: ` || tv.tv_usec != 0 || optlen != sizeof(tv)`
___
*[Pal/src/host/Linux/db_sockets.c, line 271 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAo1eY5hjKqn0I7YGO:-MwAo1eY5hjKqn0I7YGP:b18e7sp) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/Pal/src/host/Linux/db_sockets.c#L271)):*
> ```C
>     hdl->sock.receivetimeout_us = 0;
>     hdl->sock.sendtimeout_us    = 0;
>     hdl->sock.tcp_cork       = false;
> ```

Please re-align this code block (around `=`)
___
*[Pal/src/host/Linux/db_sockets.c, line 935 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAo4NyAVA0rsR_TyIr:-MwAo4NyAVA0rsR_TyIs:b18e7sp) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/Pal/src/host/Linux/db_sockets.c#L935)):*
> ```C
>     attr->socket.linger         = handle->sock.linger;
>     attr->socket.receivebuf     = handle->sock.receivebuf;
>     attr->socket.sen [...]

2022-02-18 08:57 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: 4 of 8 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1803 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAkzrA36L9pgJtoAwl:-MwB1hqWC_ZRWii8dkZV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L1803)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you please re-align this block of variable assignments? I mean the same place of `=` on each line:
```
    attr->socket.linger            = 0;
    attr->socket.receivetimeout_us = 0;
    attr->socket.sendtimeout_us    = 0;
    attr->socket.tcp_cork          = false;
    .. and so on
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2145 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlcnB1iModLga8TQ4:-MwB1jZI7k0i3AhQ1zeC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong alignment of `*` symbol -- must be left-aligned.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2146 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAliDBAsukc9Jcj972:-MwB1kZt7o8ZbHqoMSae:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just combine these two lines into one? :)

```
struct timeval* tv = (struct timeval*)optval;
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2149 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlvIBE3caDqqhirA5:-MwB1mSpBSFyaNdd_gXs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace with simply `sizeof(*tv)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2153 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAlfcq07OdTvJwQe1e:-MwB1n4x9AeGSZPTjcrQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong alignment of `*` symbol -- must be left-aligned.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2154 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAloP62yVyZouJqQWf:-MwB1oO04hB_nH4irywD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just combine these two lines into one? :)

```
struct timeval* tv = (struct timeval*)optval;
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 2157 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAm19G1MMTj0gu4VX4:-MwB1pSb9t41W8pHUmYY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/src/sys/shim_socket.c#L2157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace with simply `sizeof(*tv)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAmPuj5AQUVFhxKNKa:-MwB1rBUDe5fxluoLcPK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please just use a macro: `#define TIMEOUT 5`

The type `time_t` is typically used to represent *actual time* (number of seconds elapsed from 1970). So it's a bit misleading to use `time_t` in your context.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 75 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAmhFuCGkNe2SJzZ9k:-MwB1tTs4adig3jlC3DF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can remove this line and augment the previous line with:
```
struct timeval tv = { .tv_sec = TIMEOUT };
```

(note that `tv_usec` will be initialized to zero implicitly)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 91 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnXxp2i5701NBfSJp:-MwB1vcnAzLQkyCHbwsw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add the following checks: ` || tv.tv_usec != 0 || optlen != sizeof(tv)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnjTgDvXK9wipsTOr:-MwB1xJQCzdCVDP0u9NV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Before the second `getsockopt()`, you need to reset the timeval and optlen variables for sanity:
```
    tv.tv_sec  = 0;
    tv.tv_usec = 0;
    optlen = sizeof(tv);
```
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/tcp_ipv6_v6only.c, line 100 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAnikhEiReoUvpWb7M:-MwB1yav1aFTfFD7fZcY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/LibOS/shim/test/regression/tcp_ipv6_v6only.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add the following checks: ` || tv.tv_usec != 0 || optlen != sizeof(tv)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_sockets.c, line 271 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAo1eY5hjKqn0I7YGO:-MwB20Sc8hJ2is607Irl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/Pal/src/host/Linux/db_sockets.c#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-align this code block (around `=`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_sockets.c, line 935 at r2](https://reviewable.io/reviews/gramineproject/gramine/415#-MwAo4NyAVA0rsR_TyIr:-MwB226LASo-2axNnHaY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/36361d1a3e4fe625c812c58e3814261f71297267/Pal/src/host/Linux/db_sockets.c#L935)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-align this code block (arou [...]

2022-02-21 10:09 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1846 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQjtzoDUnwiHpRpFw3:-MwQjtzoDUnwiHpRpFw4:b-rcwjon) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1846)):*
> ```C
>             case SO_SNDTIMEO: {
>                 struct timeval tv   = *(struct timeval*)optval;
>                 uint64_t timeout_us = tv.tv_sec * TIME_US_IN_S + tv.tv_usec;
> ```

FYI: For other reviewers: we will need to add checks on the sufficient size of `optval` and the overflow of `tv -> timeout_us` convertion, but I think these checks and the corresponding error codes should happen in `shim_do_setsockopt()` and `shim_do_getsockopt()` functions and not in these internal functions. In other words, I believe this PR is fine, and we'll need a follow-up PR at some point to add such checks in `shim_do_*` funcs.


<!-- Sent from Reviewable.io -->

2022-02-21 10:09 UTC, dimakuv commented
Jenkins, test this please

2022-02-21 10:55 UTC, pwmarcz requested changes
> Reviewed 4 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1842 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQqoqM-iclNWwYU6zq:-MwQqoqN6c4nuQiexp7C:b5kcuof) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1842)):*
> ```C
>                 }
>                 break;
>             case SO_RCVTIMEO:
> ```

Combining these cases makes the code less readable: below, there are `if (optname == SO_RCVTIMEO)` and `if (optname == SO_SNDTIMEO)` blocks, so hardly any code is shared anyway.

Can you split the code into two separate cases, same as in `shim_do_getsockopt` below?
___
*[LibOS/shim/src/sys/shim_socket.c, line 1846 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQjtzoDUnwiHpRpFw3:-MwQrTDD1zUjRuU3uhnO:b-tzq5se) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1846)):*
Can we have a TODO saying that we don't validate buffer size? Both here and in `shim_do_getsockopt`.

Same for the `timeout_us` conversion.

(By the way, `optval` is not required to be aligned, right? That would mean we're not allowed to assign through a pointer at all, just use `memcpy`. Again, I suggest to add a TODO).

>I think these checks and the corresponding error codes should happen in `shim_do_setsockopt()` and `shim_do_getsockopt()` functions and not in these internal functions.

Even if this internal function does not validate the size, I think it should take a size parameter, if only to assert that it's big enough (not necessarily in this PR).
___
*[LibOS/shim/src/sys/shim_socket.c, line 1854 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQrKAI7eq7B0n527xg:-MwQrKAI7eq7B0n527xh:b9o5esy) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1854)):*
> ```C
>                     attr->socket.sendtimeout_us = timeout_us;
>                 }
>                 need_set_attr = true;
> ```

This should set `need_set_attr` only if the attribute was different, right?


<!-- Sent from Reviewable.io -->

2022-02-22 14:22 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1854 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQrKAI7eq7B0n527xg:-MwWnNOX6fjSXmbaLaZU:b-fmev7y) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1854)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This should set `need_set_attr` only if the attribute was different, right?
</blockquote></details>

+1, that's true.


<!-- Sent from Reviewable.io -->

2022-02-22 16:43 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: 7 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1842 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQqoqM-iclNWwYU6zq:-MwXJ5NK-9YT9i0NNCwd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1842)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Combining these cases makes the code less readable: below, there are `if (optname == SO_RCVTIMEO)` and `if (optname == SO_SNDTIMEO)` blocks, so hardly any code is shared anyway.

Can you split the code into two separate cases, same as in `shim_do_getsockopt` below?

</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1846 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQjtzoDUnwiHpRpFw3:-MwXJ7SPE3iefSUhr_E6:b6t4mr4) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1846)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can we have a TODO saying that we don't validate buffer size? Both here and in `shim_do_getsockopt`.

Same for the `timeout_us` conversion.

(By the way, `optval` is not required to be aligned, right? That would mean we're not allowed to assign through a pointer at all, just use `memcpy`. Again, I suggest to add a TODO).

>I think these checks and the corresponding error codes should happen in `shim_do_setsockopt()` and `shim_do_getsockopt()` functions and not in these internal functions.

Even if this internal function does not validate the size, I think it should take a size parameter, if only to assert that it's big enough (not necessarily in this PR).


</blockquote></details>

I have added TODO at single place.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1854 at r3](https://reviewable.io/reviews/gramineproject/gramine/415#-MwQrKAI7eq7B0n527xg:-MwXJIjn5NSYaiESfVpZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3dbca712d35e47519e90f52e7c2e251940698022/LibOS/shim/src/sys/shim_socket.c#L1854)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, that's true.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-22 18:09 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1848 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXasLi3ObyK995VSdb:-MwXasLi3ObyK995VSdc:bvk4jv1) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1848)):*
> ```C
>             function and not in these internal functions. optval is not required to be aligned
>             which means memcpy should be used instead of assignment through pointer. Same TODO is
>             applicable to shim_do_getsockopt function*/
> ```

A bit cleaner version:
```
/*
 * TODOs:
 *   -  Check for sufficient size of `optval` and overflow of `tv->timeout_us` convertion
 *      in both cases (SO_RCVTIMEO and SO_SNDTIMEO); probably add these checks in
 *      shim_do_setsockopt and shim_do_getsockopt instead of this internal func.
 *   -  `optval` may be not aligned, so should do memcpy() instead of pointer deref.
 */
```

Please re-align this to 100-line char limit.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1850 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXaupX-MvtB_Ce7ITr:-MwXaupX-MvtB_Ce7ITs:bqwzwtr) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1850)):*
> ```C
>             applicable to shim_do_getsockopt function*/
>             case SO_RCVTIMEO: {
>                 struct timeval tv   = *(struct timeval*)optval;
> ```

Actually, this alignment around `=` looks ugly. Let's remove redundant spaces before `=`, and leave only one space.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1859 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXaytl77DlQ9CuqHcC:-MwXaytl77DlQ9CuqHcD:bqwzwtr) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1859)):*
> ```C
>             }
>             case SO_SNDTIMEO: {
>                 struct timeval tv   = *(struct timeval*)optval;
> ```

Actually, this alignment around `=` looks ugly. Let's remove redundant spaces before `=`, and leave only one space.


<!-- Sent from Reviewable.io -->

2022-02-22 23:31 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: 7 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1848 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXasLi3ObyK995VSdb:-MwYlVAp0QqeEvx-thhp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1848)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A bit cleaner version:
```
/*
 * TODOs:
 *   -  Check for sufficient size of `optval` and overflow of `tv->timeout_us` convertion
 *      in both cases (SO_RCVTIMEO and SO_SNDTIMEO); probably add these checks in
 *      shim_do_setsockopt and shim_do_getsockopt instead of this internal func.
 *   -  `optval` may be not aligned, so should do memcpy() instead of pointer deref.
 */
```

Please re-align this to 100-line char limit.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1850 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXaupX-MvtB_Ce7ITr:-MwYlXQwBSn7o2qozHlq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1850)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, this alignment around `=` looks ugly. Let's remove redundant spaces before `=`, and leave only one space.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1859 at r4](https://reviewable.io/reviews/gramineproject/gramine/415#-MwXaytl77DlQ9CuqHcC:-MwYlYb0DykB1biknpFg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/267c5fe7f4877ce134f2baa55271a63c1f595401/LibOS/shim/src/sys/shim_socket.c#L1859)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, this alignment around `=` looks ugly. Let's remove redundant spaces before `=`, and leave only one space.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-23 08:23 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-02-23 08:23 UTC, dimakuv commented
Jenkins, test this please

2022-02-23 08:27 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2022-02-23 08:56 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/415#-Mw5rTAODwSRIg6SPxx8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll fix this message during rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-23 09:25 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/415)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-23 09:40 UTC, dimakuv commented
Jenkins, test this pleae

2022-02-23 09:40 UTC, dimakuv commented
Jenkins, test this please

2022-02-23 10:33 UTC, merged