Convert manifests to new mount format
gramineproject/gramine pull request #417
Opened 2022-02-18 10:35 UTC by pwmarcz

## Description of the changes 

Follow-up to #411. Converts remaining manifests and documentation.

For the manifests, I used editor automation (regexp replace + a macro), but some manual adjustments were also necessary.

## How to test this PR? 

Read it carefully.

Here are some checks I did to find what to convert:
* `git grep 'fs\.mount\.'` - old table syntax
* `git grep 'path = "[^/]'` - non-absolute paths (but also shows paths with variables like `"{{ arch_libdir }}/..."`)
* `git grep 'type = "chroot"'` - should not be necessary anymore

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/417)

2022-02-21 10:34 UTC, dimakuv requested changes
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQn95b0U_xstuzeRoZ:-MwQn95c8da5aC0KeCwz:b-etem69) (no related file):*
Do you plan to do the same change in the GSC and Examples repos?

...On the other hand, we probably should keep it as-is at least until the next release, otherwise GSC and Examples will fail with older Gramine versions. Can you please create a GitHub issue for each of these repos, and mention that GSC and Examples should be converted after v1.2 is released (or even v1.3, not sure)?

---
___
*[CI-Examples/blender/blender.manifest.template, line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQodAiEPr8oipC7GOR:-MwQnl3H8EOD1Skhu17X:b-swco7r) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/blender/blender.manifest.template#L20)):*
> ```
>   { path = "/blender_lib", uri = "file:{{ blender_dir }}/lib" },
>   { path = "/usr/{{ arch_libdir }}", uri = "file:/usr/{{ arch_libdir }}" },
>   { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
> ```

Can we swap these two lines? We have these two lines in a different (and more intuitive) order in other manifest files.
___
*[CI-Examples/python/python.manifest.template, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQoM186NyQ4z-yP25L:-MwQoM186NyQ4z-yP25M:b-60ilf0) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/python/python.manifest.template#L22)):*
> ```
>   { path = "{{ python.stdlib }}", uri = "file:{{ python.stdlib }}" },
>   { path = "{{ python.distlib }}", uri = "file:{{ python.distlib }}" },
>   { path = "/tmp", uri = "file:/tmp" },
> ```

I wonder if this works with `tmpfs`? If yes, maybe replace it (in a separate commit)? Not blocking.
___
*[LibOS/shim/test/ltp/manifest.template, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpmth3CWqYVd6xR01:-MwQpmth3CWqYVd6xR02:by9pr81) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L10)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> fs.root.uri = "file:{{ binary_dir }}"
> ```

How is it possible that there is no `fs.root.path`? Is it `/` by default? Maybe add it here explicitly?
___
*[LibOS/shim/test/ltp/manifest.template, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpJT35JpQzBZwX3L-:-MwQpJT35JpQzBZwX3L0:bpkgwwf) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L14)):*
> ```
> fs.mount = [
>   { path = "/etc", uri = "file:/etc" },
>   { path = "/dev/shm", uri = "file:/tmp" },
> ```

Do we want to add some comment on this trick? Here we back the pseudo-files to create shared memory regions by the actual files under host-OS path `/tmp`.
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpxLh8jRbUHE4MEYc:-MwQpxLh8jRbUHE4MEYd:b-30ewy0) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/regression/host_root_fs.manifest.template#L13)):*
> ```
>   { path = "/lib", uri = "file:{{ gramine.runtimedir(libc) }}" },
>   # overwrite host "/etc" - we don't want host-level configuration files, e.g. dynamic loader caches
>   { type = "tmpfs", path = "/etc", uri = "file:unused" },
> ```

Why do you keep `uri` here? To check this syntax?
___
*[Pal/regression/Bootstrap6.manifest.template, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQqBID-vW5REryAJ7N:-MwQqBID-vW5REryAJ7O:bc1rc0l) ([raw file](https://github.com/gramineproject/gramine/blob/a0812673205c21a2c5cb669d72ce177ff6f5ef68/Pal/regression/Bootstrap6.manifest.template#L7)):*
> ```
> loader.argv0_override = "{{ entrypoint }}"
> 
> fs.mount.root.uri = "file:"
> ```

Do you know what was that? This couldn't be used, right, since it is a LibOS-only construct?


<!-- Sent from Reviewable.io -->

2022-02-21 10:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQn95b0U_xstuzeRoZ:-MwQsb1p4jguf2-Vcpow:bze75uh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you plan to do the same change in the GSC and Examples repos?

...On the other hand, we probably should keep it as-is at least until the next release, otherwise GSC and Examples will fail with older Gramine versions. Can you please create a GitHub issue for each of these repos, and mention that GSC and Examples should be converted after v1.2 is released (or even v1.3, not sure)?
</blockquote></details>

I'd say it should be v1.2 for both repos (they track the most recent release).

---


<!-- Sent from Reviewable.io -->

2022-02-21 12:01 UTC, mkow requested changes
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR4nkD4XpSgg48NzfX:-MwR4nkD4XpSgg48NzfY:bothdln) (no related file):*
Please grep for `mount.`, there's a hit in `toml_utils.h` (only partially relevant, `fs.mount.smth` is used as an example in a comment).

---
___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwR2G7Y5eDzeh4Qryxd:b7sbxxt) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> fs.mount = [
> ```

Just noticed this: Wouldn't it make more sense if this was named `fs.mounts`? (plural; probably not for this PR)



_Code quote:_
```
fs.mount
```
___
*[Documentation/manpages/gramine-manifest.rst, line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR5r0HClF2_PXTv48J:-MwR5r0HClF2_PXTv48K:boqqljw) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/Documentation/manpages/gramine-manifest.rst#L95)):*
> ```reStructuredText
> 
>    fs.mount = [
>      { path = "/lib",  uri = "file:{{ gramine.runtimedir() }}" },
> ```

Double space
___
*[LibOS/shim/test/fs/manifest.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR69wr97Hzr-47rmMn:-MwR69wr97Hzr-47rmMo:bh5ol3k) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/fs/manifest.template#L9)):*
> ```
> fs.mount = [
>   { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
>   { path = "/{{ entrypoint }}", uri = "file:{{ binary_dir }}/{{ entrypoint }}" },
> ```

Shouldn't we ensure that entrypoint is absolute in `gramine-manifest`, instead of manually inserting a slash here?
Ditto for all other places like this one.



_Code quote:_
```
"/{{ entrypoint }}"
```
___
*[LibOS/shim/test/regression/attestation.manifest.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR6zk23esLwxuDe8KI:-MwR6zk23esLwxuDe8KJ:b-p526qk) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/regression/attestation.manifest.template#L8)):*
> ```
> loader.insecure__use_cmdline_argv = true
> 
> # Keep the deprecated `fs.mount` syntax for test purposes
> ```

Could you add "TODO: Update after v1.3 release" to make it easier to find later?
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpxLh8jRbUHE4MEYc:-MwR8Qup1BlUaoK6ccdS:b-19dzpg) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/regression/host_root_fs.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you keep `uri` here? To check this syntax?
</blockquote></details>

If that's the case, then please add a comment about it.


<!-- Sent from Reviewable.io -->

2022-02-21 12:30 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: 37 of 45 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQn95b0U_xstuzeRoZ:-MwQx11GEAN_6-QRb4bp:b-rl0mbn) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd say it should be v1.2 for both repos (they track the most recent release).
</blockquote></details>

I agree it should be v1.2. Ticketed: https://github.com/gramineproject/gsc/issues/46, https://github.com/gramineproject/examples/issues/17.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR4nkD4XpSgg48NzfX:-MwRE3W73w_h2F7s17IU:b-t3bmji) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please grep for `mount.`, there's a hit in `toml_utils.h` (only partially relevant, `fs.mount.smth` is used as an example in a comment).
</blockquote></details>

I changed these examples to `fs.root.uri`.

---
___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwRAYry42Qz7S9K2a1U:b-7xdp4r) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed this: Wouldn't it make more sense if this was named `fs.mounts`? (plural; probably not for this PR)
</blockquote></details>

I like `fs.mount`. I don't think migrating from "mount" to "mounts" is a good idea, especially since we are not actually changing any "singular" thing to a "plural" thing, just a table to an array.

Also, "mounts" are not a thing according to our documentation, and IMO this would look akward (we use "mountpoints" or "mounted filesystems").

I'm interpreting this `mount` as a verb, not as a noun, i.e. "here's a list of things to mount".
___
*[CI-Examples/blender/blender.manifest.template, line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQodAiEPr8oipC7GOR:-MwQxEia7ot1Eo_FWsAK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/blender/blender.manifest.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we swap these two lines? We have these two lines in a different (and more intuitive) order in other manifest files.
</blockquote></details>

Done.
___
*[CI-Examples/python/python.manifest.template, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQoM186NyQ4z-yP25L:-MwQyGIQBDvptZRGjg52:b-l1gx0o) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/python/python.manifest.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wonder if this works with `tmpfs`? If yes, maybe replace it (in a separate commit)? Not blocking.
</blockquote></details>

I think it works. I added a commit.
___
*[Documentation/manpages/gramine-manifest.rst, line 95 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR5r0HClF2_PXTv48J:-MwRBv1xErUIeHpmDHNg:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/Documentation/manpages/gramine-manifest.rst#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Double space
</blockquote></details>

Fixed.
___
*[LibOS/shim/test/fs/manifest.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR69wr97Hzr-47rmMn:-MwRC-e0ELtuwqccFxWQ:b3pvrms) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/fs/manifest.template#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we ensure that entrypoint is absolute in `gramine-manifest`, instead of manually inserting a slash here?
Ditto for all other places like this one.
</blockquote></details>

`{{ entrypoint }}` is also used relative to `{{ binary_dir }}`. Passing it with a slash would work, but I think it's cleaner to treat the `entrypoint` variable as file name, not as an absolute path inside Gramine.
___
*[LibOS/shim/test/ltp/manifest.template, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpmth3CWqYVd6xR01:-MwQyJTQ1mE3lP_j2x1f:b-ev9a9o) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is it possible that there is no `fs.root.path`? Is it `/` by default? Maybe add it here explicitly?
</blockquote></details>

`fs.root` is a special manifest key for mounting `/`, so there is no such key as `fs.root.path`.
___
*[LibOS/shim/test/ltp/manifest.template, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpJT35JpQzBZwX3L-:-MwQyq4v7ibvckUMCLy7:be5ot6n) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add some comment on this trick? Here we back the pseudo-files to create shared memory regions by the actual files under host-OS path `/tmp`.
</blockquote></details>

Actually, I don't think it does anythng, LTP apparently falls back to creating a file in `/tmp`. I removed the mount (committed separately) and all tests still pass.

`tst_test.c` in LTP sources:

```c
        if (access("/dev/shm", F_OK) == 0) {
                snprintf(shm_path, sizeof(shm_path), "/dev/shm/ltp_%s_%d",
                         tid, getpid());
        } else {
                char *tmpdir;

                if (!tst_tmpdir_created())
                        tst_tmpdir();

                tmpdir = tst_get_tmpdir();
                snprintf(shm_path, sizeof(shm_path), "%s/ltp_%s_%d",
                         tmpdir, tid, getpid());
                free(tmpdir);
        }

        ipc_fd = open(shm_path, O_CREAT | O_EXCL | O_RDWR, 0600);
        if (ipc_fd < 0)
                tst_brk(TBROK | TERRNO, "open(%s)", shm_path);
        SAFE_CHMOD(shm_path, 0666);

        SAFE_FTRUNCATE(ipc_fd, size);

        results = SAFE_MMAP(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, ipc_fd, 0);
```
___
*[LibOS/shim/test/regression/attestation.manifest.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR6zk23esLwxuDe8KI:-MwRCdo9EEJZdbVBZm5j:bwpjq76) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/regression/attestation.manifest.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add "TODO: Update after v1.3 release" to make it easier to find later?
</blockquote></details>

I added a TODO, but mention "two versions after v1.2", same as TODOs in the code that implements the old syntax.

(I was hesitant to mention "v1.3" or "v1.4" since we had some disagreements recently regarding whether we should follow semantic versioning... which would mean having to bump one of the next versions to v2).
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 13 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpxLh8jRbUHE4MEYc:-MwREaO74HU51jJaO9VY:b-31plab) ([raw file](https: [...]

2022-02-21 13:04 UTC, dimakuv requested changes
> Reviewed 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwRMRdJ2A1Jd7I9YOHB:b-5m17zi) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I don't think migrating from "mount" to "mounts" is a good idea, especially since we are not actually changing any "singular" thing to a "plural" thing, just a table to an array.

It's actually a bit orthogonal to this PR, I think that in general this should be plural to be more "grammar correct". I.e. it's not that it should be plural because you made this change, previously I also disliked it, I'm just using the opportunity of changing the syntax to include more changes while we're doing it.

> Also, "mounts" are not a thing according to our documentation, and IMO this would look akward (we use "mountpoints" or "mounted filesystems").

I consider "mount" as a shorthand for "mount point".

> I'm interpreting this `mount` as a verb, not as a noun, i.e. "here's a list of things to mount".

The problem I have with this way of looking at it is that TOML is a declarative language, so here we're actually _specifying a list of mounts_.
</blockquote></details>

I also like `fs.mounts`. And I agree with Michal that since we're changing all manifest files anyway in this PR, maybe we'll also add this synonym? I actually like the idea.
___
*[LibOS/shim/test/ltp/manifest.template, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpmth3CWqYVd6xR01:-MwRNQ0C3CXQWRn7458Q:b-omlypu) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`fs.root` is a special manifest key for mounting `/`, so there is no such key as `fs.root.path`.
</blockquote></details>

Ok. But please see my other comment (another manifest file erroneously uses `fs.root.path`).

Also, then this line in GSC is totally useless? https://github.com/gramineproject/gsc/blob/6a905d753c1b243ee66b0266d542f6a790f279ed/templates/entrypoint.common.manifest.template#L10
___
*[LibOS/shim/test/ltp/manifest.template, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpJT35JpQzBZwX3L-:-MwRMs0_6WlxsmkZ4FGJ:b-92zb4p) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L14)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, I don't think it does anythng, LTP apparently falls back to creating a file in `/tmp`. I removed the mount (committed separately) and all tests still pass.

`tst_test.c` in LTP sources:

```c
        if (access("/dev/shm", F_OK) == 0) {
                snprintf(shm_path, sizeof(shm_path), "/dev/shm/ltp_%s_%d",
                         tid, getpid());
        } else {
                char *tmpdir;

                if (!tst_tmpdir_created())
                        tst_tmpdir();

                tmpdir = tst_get_tmpdir();
                snprintf(shm_path, sizeof(shm_path), "%s/ltp_%s_%d",
                         tmpdir, tid, getpid());
                free(tmpdir);
        }

        ipc_fd = open(shm_path, O_CREAT | O_EXCL | O_RDWR, 0600);
        if (ipc_fd < 0)
                tst_brk(TBROK | TERRNO, "open(%s)", shm_path);
        SAFE_CHMOD(shm_path, 0666);

        SAFE_FTRUNCATE(ipc_fd, size);

        results = SAFE_MMAP(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, ipc_fd, 0);
```

</blockquote></details>

Wow. Thanks for checking. And we had it from the dawn of times, and I always believed it...
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/417#-MwRNLur4mohZ7nglGU7:-MwRNLur4mohZ7nglGU8:b-uil7pz) ([raw file](https://github.com/gramineproject/gramine/blob/668693cbe28482a7a4bf534a25949b45e44f3a4c/LibOS/shim/test/regression/host_root_fs.manifest.template#L7)):*
> ```
> loader.env.LD_LIBRARY_PATH = "/lib"
> 
> fs.root.path = "/"
> ```

Please remove this then (see my other comment).
___
*[Pal/regression/Bootstrap6.manifest.template, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQqBID-vW5REryAJ7N:-MwRN82s1X8msRytk1XA:bm8c3sg) ([raw file](https://github.com/gramineproject/gramine/blob/a0812673205c21a2c5cb669d72ce177ff6f5ef68/Pal/regression/Bootstrap6.manifest.template#L7)):*
> (it's like this in the first commit in `graphene`)

The infamous first commit of Graphene! So many memories.


<!-- Sent from Reviewable.io -->

2022-02-21 14:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: 44 of 45 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwRj-gV1YPJS9gvjrm7:b-96i83l) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also like `fs.mounts`. And I agree with Michal that since we're changing all manifest files anyway in this PR, maybe we'll also add this synonym? I actually like the idea.
</blockquote></details>

Okay. But then I don't think there should be any synonym, just single way of doing things. We're changing the syntax anyway, so we can allow `fs.mounts`  only. Is that OK?

(Of course, the deprecated `fs.mount.xyz` stays the same for now).
___
*[LibOS/shim/test/ltp/manifest.template, line 10 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpmth3CWqYVd6xR01:-MwRknZE-iZUVj1xQigb:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok. But please see my other comment (another manifest file erroneously uses `fs.root.path`).

Also, then this line in GSC is totally useless? https://github.com/gramineproject/gsc/blob/6a905d753c1b243ee66b0266d542f6a790f279ed/templates/entrypoint.common.manifest.template#L10
</blockquote></details>

Yes.
___
*[LibOS/shim/test/ltp/manifest.template, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwQpJT35JpQzBZwX3L-:-MwRkrpCEaPpNtLNsSba:b-mfr1cp) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/LibOS/shim/test/ltp/manifest.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wow. Thanks for checking. And we had it from the dawn of times, and I always believed it...
</blockquote></details>

Maybe some older version of LTP needed it?
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/417#-MwRNLur4mohZ7nglGU7:-MwRl-Ed1abp7Il0a1LF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/668693cbe28482a7a4bf534a25949b45e44f3a4c/LibOS/shim/test/regression/host_root_fs.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this then (see my other comment).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 15:09 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwRoadvCXzv7NWxll8t:b26vr8a) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
> I don't think there should be any synonym, just single way of doing things.

Definitely, +1 from my side, I never wanted it to be a synonym, just to rename this option :P


<!-- Sent from Reviewable.io -->

2022-02-21 15:34 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: 6 of 48 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwRugK1-3qa-FVctFoK:b9ndkq) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I don't think there should be any synonym, just single way of doing things.

Definitely, +1 from my side, I never wanted it to be a synonym, just to rename this option :P
</blockquote></details>

Done (and rebased: I put the rename to `fs.mounts` as first commit).

Quick check: `git grep 'fs\.mount[^s]'` should not show anything surprising.


<!-- Sent from Reviewable.io -->

2022-02-21 16:16 UTC, mkow submitted a review, later dismissed
> Reviewed 42 of 42 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-02-22 08:02 UTC, dimakuv approved these changes
> Reviewed 39 of 42 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwVQYTTCQIjtY6PIPIe:bpwudtw) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done (and rebased: I put the rename to `fs.mounts` as first commit).

Quick check: `git grep 'fs\.mount[^s]'` should not show anything surprising.
</blockquote></details>

OK, I'm happy with this solution. I just proposed a synonym (alias) because I thought it would be very cumbersome to have a TOML table `fs.mount` and a TOML array `fs.mounts`. But looks like it is not cumbersome to implement.


<!-- Sent from Reviewable.io -->

2022-02-22 08:04 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 8 files at r2, 3 of 42 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-22 08:18 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-22 10:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-02-22 13:10 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/417)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CI-Examples/bash/manifest.template, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/417#-MwR2G7Y5eDzeh4Qryxc:-MwWWftnAGyMyZX5pF2k:b-wlns0s) ([raw file](https://github.com/gramineproject/gramine/blob/1bddf522eabe1b2dda35cc9ccc0f84c6881ece20/CI-Examples/bash/manifest.template#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I'm happy with this solution. I just proposed a synonym (alias) because I thought it would be very cumbersome to have a TOML table `fs.mount` and a TOML array `fs.mounts`. But looks like it is not cumbersome to implement.
</blockquote></details>

Ah, this is where the "alias" came from, I thought that Paweł was thinking that I suggested aliasing them :) (and I missed that Dmitrii's post included this)


<!-- Sent from Reviewable.io -->

2022-02-22 13:11 UTC, merged