[Pal,LibOS] Add arch_prctl XSTATE component permission options for AMX
gramineproject/gramine pull request #418
Opened 2022-02-18 13:54 UTC by dongx1x

From linux kernel v5.16, Advanced Matrix Extensions (AMX) is in upstream with XFD handled permission control, expose the APIs and add the permission for XFD handling the #NM exception, refer 3.2.6 in
https://software.intel.com/content/dam/develop/external/us/en/documents-tps/architecture-instruction-set-extensions-programming-reference.pdf

Signed-off-by: Dong, Xiaocheng <xiaocheng.dong@intel.com>

## Description of the changes 
Expose more arch_prctl XSTATE component permission APIs for AMX

## How to test this PR? 
Running AMX enabled workloads in a AMX enabled system

2022-02-18 20:26 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/418)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dongx1x)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/418#-MwDUcNqAeSmC2uF5opJ:-MwDUcNqAeSmC2uF5opK:bw5ncqb) (no related file):*
1. This PR just blindly forwards `arch_prctl` syscall to host OS, with no verification whatsoever.
2. What's the point? From what I understand you cannot enter an enclave which requests bit in XFRM that are not currently enabled. This means that everything that an enclave requires must be enabled prior to first EENTER and enabling anything later on is pointless. Hence there is no need for this syscall at all.

---


<!-- Sent from Reviewable.io -->

2022-02-21 02:09 UTC, dongx1x commented
Hi @boryspoplawski , thanks for the review, I submit this PR because latest AMX implementation added [permission controls for dynamic XSTATE components](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/arch/x86/kernel/fpu/xstate.c?h=v5.16&id=db8268df0983adc2bb1fb48c9e5f7bfbb5f617f3), and workloads like oneDNN accelerated by AMX have [this syscall](https://github.com/oneapi-src/oneDNN/commit/bd3f7bca5bcc14275eb1485c475685a4372539ab) now, and would fail in Gramine, so:
1. The syscall would read or change current thead.fpu.perm, and allocate more XSATE memory if needed, what do you think we should verify in Gramine? I am new to develop Gramine, any suggestion is appreciated.
2. Do syscall once before EENTER is because this will add permission to the thread of `loader`, and the child process will [inherit its permission](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/x86/kernel/fpu/core.c?h=v5.16#n518), then all the exception could be handled by XFD handler.

You can try to run latest AI workloads in Gramine in latest kernel (>5.16) in a AMX enabled system to check the failures. 
Thanks.

2022-02-21 08:20 UTC, dimakuv reviewed
@dongx1x Thanks for the PR! I am actually aware on the AMX feature, and I recently got into the same problem of Linux 5.16 requiring additional enabling of this feature (via `arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA)`).

In addition to your links, this one is also very good: https://lwn.net/Articles/874846/

However, as @boryspoplawski mentions, this PR actually does two things:
1. Enables the AMX feature on Linux 5.16 (via `arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA)` during `create_enclave()`). This enables the AMX feature unconditionally for the Linux-SGX PAL of Gramine.
2. Blindly forwards `arch_prctl()` syscall from the app through Gramine to the host, with no verification.

I think that item 1 is meaningful, but item 2 is wrong (as Borys also mentions).

I propose the following scheme:
1. In Linux-SGX PAL: We enable the AMX feature via `arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA)` based on the setting of `secs->attributes.xfrm` AMX TILE bit.
2. In Linux PAL: We enable the AMX feature via `arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA)` *unconditionally*, because we don't have anything to give us a hint whether the app on top of Gramine will use AMX or not. Linux is smart enough to not actually enable AMX immediately -- this only happens on the first AMX instruction (which results in #NM, and the Linux exception handler finally enables AMX at this point.
3. In LibOS: we *emulate* `ARCH_GET_XCOMP_SUPP`, `ARCH_GET_XCOMP_PERM`, `ARCH_REQ_XCOMP_PERM` commands. For now, we can just emulate them by quering the CPUID (`DkCpuIdRetrieve()`) on the AMX leaf, and report only the AMX leaf (these commands are not used for anything else anyway currently).

@dongx1x Do you want to try to implement this, or should I do it (based on your PR)?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/418#-:-MwQFprU37AeNVCU6WH2:b92tk89)* status: 0 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dongx1x)



<!-- Sent from Reviewable.io -->

2022-02-21 08:45 UTC, dongx1x commented
@dimakuv Please help to do that, in case I did not get your points clearly, I am still new to Gramine, thanks!

2022-02-21 08:55 UTC, dimakuv commented
> @dimakuv Please help to do that, in case I did not get your points clearly, I am still new to Gramine, thanks!

@dongx1x Sorry, I didn't understand what exactly you want us to do.

1. Do you want *me* to implement it based on your PR (I will create a new PR).
2. Or do you want to implement my proposed solution in your PR?

If you choose (1), then you don't need to do anything. I will take your PR as a baseline and re-implement it according to my comments.

If you choose (2), then I suggest you to close this PR and create a new PR. In the new PR, please follow my solution I outlined in my comments. If you have questions on how exactly to implement this PR, please ask specific questions.

2022-02-21 10:29 UTC, dongx1x commented
I choose option (2), I want to try to do that and I have questions to follow your comments:

- For _3_ in your proposal, do you mean to emulate `ARCH_GET_XCOMP_SUPP` and `ARCH_GET_XCOMP_PERM` by querying CPUID AMX leaf? The `ARCH_REQ_XCOMP_PERM` will go to Linux PAL or Linux-SGX PAL in my understanding.
- For _1_ and _2_, I only need add a condition for Linux-SGX PAL based on this PR, correct?

2022-02-21 12:44 UTC, dimakuv commented
> - For _3_ in your proposal, do you mean to emulate `ARCH_GET_XCOMP_SUPP` and `ARCH_GET_XCOMP_PERM` by querying CPUID AMX leaf?

Yes. Actually, not the CPUID AMX leaf, but the `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 -- it returns the AMX bits (17 and 18) if AMX is present and enabled in the SGX enclave, so we can simply use this info.

> The `ARCH_REQ_XCOMP_PERM` will go to Linux PAL or Linux-SGX PAL in my understanding.

No. It will be a no-op and simply:
- return success if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA)` *and* CPUID leaf `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 returns the AMX bits in EAX register.
- return `-EINVAL` if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA)` *and* CPUID leaf `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 does *not* the AMX bits in EAX register.
- return `-EOPNOTSUPP` if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, something-else)`.

Please note: in my proposal, LibOS *never* forwards `arch_prctl()` to the PAL.

> For _1_ and _2_, I only need add a condition for Linux-SGX PAL based on this PR, correct?

For _1_, you can take the code from this PR, yes.

For _2_, you can take the same code from this PR, but without the `if secs.xfrm ...` check.

P.S. For more context, please see https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/db_misc.c#L187 and that file in general -- it has a lot of code and explanations on how we treat CPUID leaves and the AMX feature.

2022-02-21 14:32 UTC, dongx1x commented
> > * For _3_ in your proposal, do you mean to emulate `ARCH_GET_XCOMP_SUPP` and `ARCH_GET_XCOMP_PERM` by querying CPUID AMX leaf?
> 
> Yes. Actually, not the CPUID AMX leaf, but the `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 -- it returns the AMX bits (17 and 18) if AMX is present and enabled in the SGX enclave, so we can simply use this info.
> 
> > The `ARCH_REQ_XCOMP_PERM` will go to Linux PAL or Linux-SGX PAL in my understanding.
> 
> No. It will be a no-op and simply:
> 
> * return success if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA)` _and_ CPUID leaf `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 returns the AMX bits in EAX register.
> * return `-EINVAL` if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA)` _and_ CPUID leaf `EXTENDED_STATE_LEAF` (0xD) with subleaf 0x0 does _not_ the AMX bits in EAX register.
> * return `-EOPNOTSUPP` if the call is `arch_prctl(ARCH_REQ_XCOMP_PERM, something-else)`.
> 
> Please note: in my proposal, LibOS _never_ forwards `arch_prctl()` to the PAL.
> 
> > For _1_ and _2_, I only need add a condition for Linux-SGX PAL based on this PR, correct?
> 
> For _1_, you can take the code from this PR, yes.
> 
> For _2_, you can take the same code from this PR, but without the `if secs.xfrm ...` check.
> 
> P.S. For more context, please see https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/db_misc.c#L187 and that file in general -- it has a lot of code and explanations on how we treat CPUID leaves and the AMX feature.

Thanks @dimakuv , I got your point. In your proposal, LibOS will handle all the syscalls (from SGX or not), without any ocall or real syscall to host, only thing we need to do is enable AMX once in the `"loader"`, if so, I will implement it and create a new PR after some tests.

2022-02-21 14:57 UTC, dimakuv commented
> Thanks @dimakuv , I got your point. In your proposal, LibOS will handle all the syscalls (from SGX or not), without any ocall or real syscall to host, only thing we need to do is enable AMX once in the "loader", if so, I will implement it and create a new PR after some tests.

That's exactly correct. Thanks for doing this.

One immediate request, when you will be preparing the new PR: please add error-checking paths everywhere. For example, in your current PR, you added this snippet:
```c
    if (secs->attributes.xfrm & (1 << AMX_TILEDATA))
        DO_SYSCALL(arch_prctl, ARCH_REQ_XCOMP_PERM, AMX_TILEDATA);
```

I would like to see error checking on the result of the syscall here. I understand that you do *not* check for errors on purpose -- because you want to proceed even on older Linux systems that do not implement this syscall. But you need more precise error checking, like this:
```c
    if (secs->attributes.xfrm & (1 << AMX_TILEDATA)) {
        ret = DO_SYSCALL(arch_prctl, ARCH_REQ_XCOMP_PERM, AMX_TILEDATA);
        if (ret < 0 && ret != -EINVAL && ret != -EOPNOTSUPP) {
            log_error("arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA) failed: %d", ret);
            return ret;
        }
        /* if ret is EINVAL or EOPNOTSUPP, then we are on older/patched Linux with no need for
         * arch_prctl-style AMX enablement; simply ignore this syscall */
    }
```

2022-02-22 10:12 UTC, dongx1x commented
New PR created #422 , close this PR

2022-02-22 10:12 UTC, closed without merging