[Docs] Improve and unify Doxygen comments, part 1
gramineproject/gramine pull request #420
Opened 2022-02-21 02:27 UTC by mkow

## Description of the changes 

Please check if it looks good, if so then I'll update the rest of the docs (probably in parts).

2022-02-21 12:29 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[common/include/toml_utils.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREeqY5tax_ceVo98v:-MwREeqZCBWaeTn0oAHy:b-c917q7) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L33)):*
> ```objc
> 
> /*!
>  * \brief  Find an integer key-value in TOML manifest.
> ```

`Finds`
___
*[common/include/toml_utils.h, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREipY27diHARnB6jW:-MwREipY27diHARnB6jX:b-c917q7) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L46)):*
> ```objc
> 
> /*!
>  * \brief  Find a string key-value in TOML manifest.
> ```

`Finds`
___
*[common/include/toml_utils.h, line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwRElr_5TAeT-TssCD0:-MwRElr_5TAeT-TssCD1:b-c917q7) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L58)):*
> ```objc
> 
> /*!
>  * \brief  Find a "size" string key-value in TOML manifest (parsed via `parse_size_str()`).
> ```

`Finds`
___
*[Documentation/devel/howto-doc.rst, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREyYe0oRw0zo5VB73:-MwREyYe0oRw0zo5VB74:b-esxlw3) ([raw file](https://github.com/gramineproject/gramine/blob/23bc8ecfe82eef05608423746ad32227bf79913e/Documentation/devel/howto-doc.rst#L159)):*
> ```reStructuredText
>        *
>        * This function returns a number augmented by the Answer to the Ultimate
>        * Question of Life, the Universe, and Everything.
> ```

I'll miss this reference to Adams, but I see why you chose a different example.


<!-- Sent from Reviewable.io -->

2022-02-21 12:38 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[common/include/toml_utils.h, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREeqY5tax_ceVo98v:-MwRHCqjA0fULO2NdaL1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Finds`
</blockquote></details>

Done.
___
*[common/include/toml_utils.h, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREipY27diHARnB6jW:-MwRHE777KcikVSuM_Qn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Finds`
</blockquote></details>

Done.
___
*[common/include/toml_utils.h, line 58 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwRElr_5TAeT-TssCD0:-MwRHEkz2HFbpxXdixUh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/79e62300407fb1e9f595222bcd7b941cdd162bb6/common/include/toml_utils.h#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Finds`
</blockquote></details>

Done.
___
*[Documentation/devel/howto-doc.rst, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/420#-MwREyYe0oRw0zo5VB73:-MwRHFi55B390ydvHHMx:b-opsqvf) ([raw file](https://github.com/gramineproject/gramine/blob/23bc8ecfe82eef05608423746ad32227bf79913e/Documentation/devel/howto-doc.rst#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll miss this reference to Adams, but I see why you chose a different example.
</blockquote></details>

Yeah, unfortunately it wasn't really helpful/informative here.


<!-- Sent from Reviewable.io -->

2022-02-21 12:58 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-23 11:48 UTC, pwmarcz requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaLdat8G0qGnZ7Z0w5:-MwaLdat8G0qGnZ7Z0w6:brt7fsv) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/api.h#L211)):*
> ```objc
>  * \param[out]  out_end    On success, set to the rest of string.
>  *
>  * \returns  0 on success, negative on failure.
> ```

I would prefer -1, not "negative". Most of our functions return negative error codes (POSIX or PAL...) on failure, some don't distinguish between errors and return only -1, I think it's better to be explicit and say we return -1 here.
___
*[common/include/spinlock.h, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaOpQM9UL4MaU6ctAY:-MwaOpQM9UL4MaU6ctAZ:b5n443i) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/spinlock.h#L10)):*
> ```objc
> #define _SPINLOCK_H
> 
> #include <errno.h>
> ```

`<errno.h>` is from glibc (and defines the `errno` global/macro), I think in no-stdlib setting we should include `<asm/errno.h>`.
___
*[Documentation/devel/howto-doc.rst, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaMV8LEe5ga1MbfLMA:-MwaMV8LEe5ga1MbfLMB:b-sozhf9) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/Documentation/devel/howto-doc.rst#L162)):*
> ```reStructuredText
>        *
>        * \returns  Sum of the arguments. Sometimes a longer description is needed,
>        *           then is should be wrapped and aligned like this.
> ```

Typo: `is -> it`
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaNBKy40lBEhuonNtH:-MwaNBKy40lBEhuonNtI:b-lzzbs4) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/Pal/src/host/Linux-SGX/enclave_ocalls.c#L93)):*
> ```C
>      *   (OCALL is not done, ret == -EAGAIN, let's wait on futex) */
> 
>     if (ret == -EAGAIN) {
> ```

I don't like this, it suggests there might be other errors that we will ignore. Either we keep open the possibility of other errors than `-EAGAIN`, and do something to handle them here, or (IMO better in this case) `spinlock_lock_timeout` should still return only 0 or -1.

(I don't like this `timedout`, but my preferred refactoring would be to keep the -1 return code, and check `if (ret < 0)` here).


<!-- Sent from Reviewable.io -->

2022-02-23 14:17 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 5 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[common/include/api.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaLdat8G0qGnZ7Z0w5:-MwapDVu4z9WmomEEmok:b-u61wo2) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/api.h#L211)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I would prefer -1, not "negative". Most of our functions return negative error codes (POSIX or PAL...) on failure, some don't distinguish between errors and return only -1, I think it's better to be explicit and say we return -1 here.
</blockquote></details>

I was mostly afraid that if we say in _some_ functions that -1 means an error, then it's quite easy to accidentally forward a retval from a subfunction and then do `if (ret == -1)` in another place, resulting in not noticing the failure. So, I'd prefer to have uniform "negative means failure" everywhere.

Ad. POSIX vs PAL vs random error codes: I plan to make them type-safe, I did some experiments and it seems to be possible in C with enough warnings enabled (see https://godbolt.org/z/zMvb3Mqar), so, soon there should be no risk of interpreting -1 as some enum.
___
*[common/include/spinlock.h, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaOpQM9UL4MaU6ctAY:-MwaqMXB1Vu2g5fsf9Ge:b-dmz11w) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/spinlock.h#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`<errno.h>` is from glibc (and defines the `errno` global/macro), I think in no-stdlib setting we should include `<asm/errno.h>`.
</blockquote></details>

Done (removed because of the other discussion).
___
*[Documentation/devel/howto-doc.rst, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaMV8LEe5ga1MbfLMA:-MwaqR9-BXT_AtHpaxCZ:b-ugcbwe) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/Documentation/devel/howto-doc.rst#L162)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Typo: `is -> it`
</blockquote></details>

Heh, I read this 3 times and it still wasn't enough to spot this :)
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 93 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaNBKy40lBEhuonNtH:-MwaqoB-0XzMfve-7zV-:b-nec2kw) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/Pal/src/host/Linux-SGX/enclave_ocalls.c#L93)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't like this, it suggests there might be other errors that we will ignore. Either we keep open the possibility of other errors than `-EAGAIN`, and do something to handle them here, or (IMO better in this case) `spinlock_lock_timeout` should still return only 0 or -1.

(I don't like this `timedout`, but my preferred refactoring would be to keep the -1 return code, and check `if (ret < 0)` here).
</blockquote></details>

Ok, makes sense.


<!-- Sent from Reviewable.io -->

2022-02-24 13:29 UTC, pwmarcz requested changes
> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaLdat8G0qGnZ7Z0w5:-MwfsBAl6fbX5vEBRH1Y:b-8e88b1) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/api.h#L211)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I was mostly afraid that if we say in _some_ functions that -1 means an error, then it's quite easy to accidentally forward a retval from a subfunction and then do `if (ret == -1)` in another place, resulting in not noticing the failure. So, I'd prefer to have uniform "negative means failure" everywhere.

Ad. POSIX vs PAL vs random error codes: I plan to make them type-safe, I did some experiments and it seems to be possible in C with enough warnings enabled (see https://godbolt.org/z/zMvb3Mqar), so, soon there should be no risk of interpreting -1 as some enum.
</blockquote></details>

OK, I understand why we might want not to promise -1 exactly. But I'm still worried that somebody might forward this value (e.g. `return ret;`) thinking it's a POSIX error code.

So I would prefer something else than "negative": in some places we say "negative error code", so which sounds really similar. But I don't have a better suggestion, so I'm unblocking.
___
*[common/include/spinlock.h, line 85 at r3](https://reviewable.io/reviews/gramineproject/gramine/420#-MwftQxZAO0ZIfGCmYib:-MwftQxZAO0ZIfGCmYic:b-2hd6ip) ([raw file](https://github.com/gramineproject/gramine/blob/00ee8626b0350928bfc62b41387a6d7d3a8d0924/common/include/spinlock.h#L85)):*
> ```objc
>  * \brief Try to acquire spinlock.
>  *
>  * \returns  0 if acquiring the lock succeeded, 1 if it was already taken.
> ```

Can you change this function to return -1 for consistency with the one below?

(This is unused btw, maybe we don't need it?)


<!-- Sent from Reviewable.io -->

2022-02-24 13:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/spinlock.h, line 85 at r3](https://reviewable.io/reviews/gramineproject/gramine/420#-MwftQxZAO0ZIfGCmYib:-MwfxWJU8fDiL0N8qt2L:b-bopbiu) ([raw file](https://github.com/gramineproject/gramine/blob/00ee8626b0350928bfc62b41387a6d7d3a8d0924/common/include/spinlock.h#L85)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you change this function to return -1 for consistency with the one below?

(This is unused btw, maybe we don't need it?)
</blockquote></details>

Good catch!
Not sure whether to keep it or remove, it's a library and having such API probably makes sense overall...


<!-- Sent from Reviewable.io -->

2022-02-24 14:41 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-25 01:18 UTC, boryspoplawski reviewed
> Reviewed 3 of 8 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwiMnM9DQPYIL12OD1x:b-t7up1x) (no related file):*
I personally find two spaces after `\param` redundant (unlike after arg name, where it looks nice) - it does not improve readability and just takes space.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNM1oD59ROcmuGR-w:-MwiNM1oD59ROcmuGR-x:bpdvc1a) (no related file):*
I've put all comments as non-blocking, since it's late in the review process and already rebased.

---
___
*[common/include/api.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaLdat8G0qGnZ7Z0w5:-MwiLPryEYJsECF_Yoj-:b8ya8nq) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/api.h#L211)):*
> Ad. POSIX vs PAL vs random error codes: I plan to make them type-safe, I did some experiments and it seems to be possible in C with enough warnings enabled (see https://godbolt.org/z/zMvb3Mqar), so, soon there should be no risk of interpreting -1 as some enum.

It's not so easy. If you do `enum { A=1; B; }`, then we would have to return `-A` and we get no type checking. If you do `enum { A = -1;}` then we get an ugly convention like `return PAL_ERROR_AAAA;` and you don't even know if it's positive or negative (check mbedtls sources for how it looks, they use that convention).

> OK, I understand why we might want not to promise -1 exactly. But I'm still worried that some1body might forward this value (e.g. return ret;) thinking it's a POSIX error code.

Fortunately `1` is `EPERM` so nothing bad should happen (it's not like `EINTR` or something).
___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwiNrad7MP4AXJaz5ud:bf7m5a7) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
> ```objc
> 
> /*!
>  * \brief  Converts a string to number.
> ```

Why did you change all `\brief` to 3rd person? Old version matched our conventions (e.g. commit message, which describes commit content, just like this comment describes a function).
ditto for the whole PR
___
*[common/include/spinlock.h, line 85 at r3](https://reviewable.io/reviews/gramineproject/gramine/420#-MwftQxZAO0ZIfGCmYib:-MwiN93X3Ofv7RrjeKQP:bhulxdi) ([raw file](https://github.com/gramineproject/gramine/blob/00ee8626b0350928bfc62b41387a6d7d3a8d0924/common/include/spinlock.h#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good catch!
Not sure whether to keep it or remove, it's a library and having such API probably makes sense overall...
</blockquote></details>

I would vote for removing it. 
___
*[common/include/spinlock.h, line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiOOMa1QZwISd0beWT:-MwiOOMa1QZwISd0beWU:b-4yh3ez) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/spinlock.h#L126)):*
> ```objc
>  * \param  iterations  Number of iterations (tries) after which this function times out.
>  *
>  * \returns  0 if acquiring the lock succeeded, negative if timed out.
> ```

Do we treat timeout as an error (since you've changed to a negative value)? I thought of it as just another possible outcome of this function, which is not an error, so `1` (positive value) made sense.

Update: after looking at usages - this should just return `bool`.
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwiQKmcCmGFdde3zqKh:bijxua7) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
> ```C
>  * \brief  Core printf implementation.
>  *
>  * \param       write_callback  Function called on each generated chunk of data.
> ```

I think the old version (no capital letter and no dot at the end) looks better when rendered in docs.
___
*[common/src/printf.c, line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQAtS5AjaYFWqxrF8:-MwiQAtS5AjaYFWqxrF9:b-vhf770) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L64)):*
> ```C
>  * \param       ap              List of optional variadic arguments.
>  * \param[out]  out_size        Total size of written data (sum of sizes passed to all \p
>  *                              write_callback invocations).
> ```

I would move `\p` to the new line. It probably renders ok, but is weird to read.
___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRGf-8H5c1v7Y_v2n:-MwiRGf09A0XZi4D_wCC:ba4l0qp) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
> ```reStructuredText
>        * \param  second  Second addend.
>        *
>        * \returns  Sum of the arguments. Sometimes a longer description is needed,
> ```

Is it grammatically correct? I would change `Sometimes` -> `If`/`When`
___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-MwiRWOH2klKlD9hHGDk:b3gz93t) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
> ```reStructuredText
>        * \param  second  Second addend.
>        *
>        * \returns  Sum of the arguments. Sometimes a longer description is needed,
> ```

This is not correctly wrapped (line length).


<!-- Sent from Reviewable.io -->

2022-02-25 10:34 UTC, pwmarcz reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwkOgOW64du8I87QmEL:bobkxun) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I personally find two spaces after `\param` redundant (unlike after arg name, where it looks nice) - it does not improve readability and just takes space.
</blockquote></details>

I think I asked for it at some point. It looks more readable to me, but I don't care too much.

But keep in mind  it should be consistent with spacing after `\returns` and `\brief`. This PR mostly does that, but I see at least of `\brief` with one space (in `spinlock.h`).

---
___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwkQbHu6t6sl_MYAfKK:b-43h6qb) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you change all `\brief` to 3rd person? Old version matched our conventions (e.g. commit message, which describes commit content, just like this comment describes a function).
ditto for the whole PR
</blockquote></details>

Actually, yes, +1 to that. The current style (imperative `\brief`, longer description in 3rd person) looks natural to me.


<!-- Sent from Reviewable.io -->

2022-02-25 10:45 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwkTlZv1cALQ_cpZ7B6:b-j11zlp) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, yes, +1 to that. The current style (imperative `\brief`, longer description in 3rd person) looks natural to me.
</blockquote></details>

I don't care, so whatever you decide on.


<!-- Sent from Reviewable.io -->

2022-02-25 11:26 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwkbpSCDRcXPYsl_SPW:bhh95b4) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think I asked for it at some point. It looks more readable to me, but I don't care too much.

But keep in mind  it should be consistent with spacing after `\returns` and `\brief`. This PR mostly does that, but I see at least of `\brief` with one space (in `spinlock.h`).
</blockquote></details>

I would remove it from `\ret` and `\brief` too - I believe the original intent was to make `\param arg something` less confusing, so that you don't mistake `arg` as part of the sentence

---


<!-- Sent from Reviewable.io -->

2022-02-25 14:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 6 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwlEQAT9jzhH7Ajse0L:bq1n4o3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove it from `\ret` and `\brief` too - I believe the original intent was to make `\param arg something` less confusing, so that you don't mistake `arg` as part of the sentence
</blockquote></details>

I'm rather neutral on this, but it should be either a double space after all `\tags` or always single (as Borys proposed).

@dimakuv What's your preference?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNM1oD59ROcmuGR-w:-MwlEiBwBcO5oGltVj-R:bv8x6jz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've put all comments as non-blocking, since it's late in the review process and already rebased.
</blockquote></details>

No hurry, let's resolve them first.

---
___
*[common/include/api.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/gramine/420#-MwaLdat8G0qGnZ7Z0w5:-MwlFcfTCUI9AvWX2jUX:b-rxlnz0) ([raw file](https://github.com/gramineproject/gramine/blob/cd33828c895fee19a9445a480bcd5244da73e813/common/include/api.h#L211)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Ad. POSIX vs PAL vs random error codes: I plan to make them type-safe, I did some experiments and it seems to be possible in C with enough warnings enabled (see https://godbolt.org/z/zMvb3Mqar), so, soon there should be no risk of interpreting -1 as some enum.

It's not so easy. If you do `enum { A=1; B; }`, then we would have to return `-A` and we get no type checking. If you do `enum { A = -1;}` then we get an ugly convention like `return PAL_ERROR_AAAA;` and you don't even know if it's positive or negative (check mbedtls sources for how it looks, they use that convention).

> OK, I understand why we might want not to promise -1 exactly. But I'm still worried that some1body might forward this value (e.g. return ret;) thinking it's a POSIX error code.

Fortunately `1` is `EPERM` so nothing bad should happen (it's not like `EINTR` or something).
</blockquote></details>

Hmm, good point, not sure what to do with the negative values...
___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwlEod4Br4GvEmMjltt:bq1oxgo) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't care, so whatever you decide on.
</blockquote></details>

I think for functions it feels more natural to use this form, because the comment describes what a function does "in general", without binding to a specific point in time. With commits it's a bit different, commit history is more like a list of changes/commands applied in order to the source.
___
*[common/include/spinlock.h, line 85 at r3](https://reviewable.io/reviews/gramineproject/gramine/420#-MwftQxZAO0ZIfGCmYib:-MwlFopTADPPHzyx_cwD:bl1h72v) ([raw file](https://github.com/gramineproject/gramine/blob/00ee8626b0350928bfc62b41387a6d7d3a8d0924/common/include/spinlock.h#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would vote for removing it. 
</blockquote></details>

Ok, done.
___
*[common/include/spinlock.h, line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiOOMa1QZwISd0beWT:-MwlKd3xCoZzGjxlHeyp:bblcrog) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/spinlock.h#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we treat timeout as an error (since you've changed to a negative value)? I thought of it as just another possible outcome of this function, which is not an error, so `1` (positive value) made sense.

Update: after looking at usages - this should just return `bool`.
</blockquote></details>

Yeah, I consider it to be an equivalent of `-EAGAIN` - function failed to do what was asked, and the reason for failure is a timeout.
Bool also sounds ok for me, but let's ask @pwmarcz what he thinks about it.
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwlLF-G6q_2j6aBlx_S:b-ws59ol) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think the old version (no capital letter and no dot at the end) looks better when rendered in docs.
</blockquote></details>

I agree, but tbh I mostly read this directly in the code, where the capital letter help a lot visually.
@pwmarcz, @dimakuv: Any opinions on this?
___
*[common/src/printf.c, line 64 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQAtS5AjaYFWqxrF8:-MwlMGuD40IeG8PZarND:bfbq99i) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would move `\p` to the new line. It probably renders ok, but is weird to read.
</blockquote></details>

Good point, done.
___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRGf-8H5c1v7Y_v2n:-MwlMQQL51Q3P593MMx3:bd9r2av) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it grammatically correct? I would change `Sometimes` -> `If`/`When`
</blockquote></details>

Hmm, I think it's correct, but maybe changing `then`-> `in such a case` would help?


<!-- Sent from Reviewable.io -->

2022-02-25 15:28 UTC, pwmarcz reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 6 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwlQDcj79Pp0KCn9INo:b-lsl9vn) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think for functions it feels more natural to use this form, because the comment describes what a function does "in general", without binding to a specific point in time. With commits it's a bit different, commit history is more like a list of changes/commands applied in order to the source.
</blockquote></details>

Looking for precedents:

* I see Doxygen examples with 3rd person
* Linux doesn't seem to use a consistent style (their guide says just to write a "brief description")
* Xen project seems to prefer the current style (brief in 2nd person, description in 3rd person)
* Linux and BSD man pages use the current style (brief: `close - close a file descriptor`, then later `close() closes a file descriptor, so that...`)
* Rust uses 3rd person only (e.g. `pub fn clear(...) - Truncates this String, removing all contents.`), but doesn't seem to have any "brief" section at all, just a paragraph of description)
* Ruby also uses 3rd person only (e.g. `clear -> self - Remove the contents of self`), but also doesn't have a brief section
* Python ([https://www.python.org/dev/peps/pep-0257/](PEP 257)) doesn't talk about the grammatical form, but has examples in the imperative (e.g. `Return the pathname...`, `Do X and return a list.`)
* Javadoc style guide [explicitly says to use 3rd person, not imperative](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html), but AFAIK also doesn't describe a separate "brief" section

To summarize: I have some examples where a "brief" section uses 2nd person imperative, and description uses 3rd person (Xen, Linux and BSD man pages, Python). Using 3rd person for the "brief" section seems pretty rare (although there are projects that do not have this line at all).

Most relevant/prominent seems to be the example of man pages.


<!-- Sent from Reviewable.io -->

2022-02-25 15:36 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwlPxV539VXmEaO1eLv:bgz4f1n) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
> commit history is more like a list of changes/commands applied in order to the source.

Agreed, and commit message is describing these changes, or putting in your words: describes what a commit does "in general".
___
*[common/include/spinlock.h, line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiOOMa1QZwISd0beWT:-MwlRBbO1uRD2RFmSxcf:bxevakx) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/spinlock.h#L126)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I consider it to be an equivalent of `-EAGAIN` - function failed to do what was asked, and the reason for failure is a timeout.
Bool also sounds ok for me, but let's ask @pwmarcz what he thinks about it.
</blockquote></details>

In this case it's not really that function failed, we literally asked it to spin for a given timeout...
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwlV_qoDiBKpImx3sJB:bc0c8tq) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I agree, but tbh I mostly read this directly in the code, where the capital letter help a lot visually.
@pwmarcz, @dimakuv: Any opinions on this?
</blockquote></details>

With double space I don't mind this even in the source


<!-- Sent from Reviewable.io -->

2022-02-25 15:44 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwlY0n47Rqeihklf-sr:b2mc9kh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm rather neutral on this, but it should be either a double space after all `\tags` or always single (as Borys proposed).

@dimakuv What's your preference?
</blockquote></details>

I liked a single space for `\ret` and `\brief`. My opinion is the same as Borys's.

---
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwlYPGTDBz5JNAqzgjP:bed91xw) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

With double space I don't mind this even in the source
</blockquote></details>

I like the capital letter.


<!-- Sent from Reviewable.io -->

2022-02-25 15:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[common/include/spinlock.h, line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiOOMa1QZwISd0beWT:-MwlYOGg0AgfGFsx8jII:buqzh44) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/spinlock.h#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In this case it's not really that function failed, we literally asked it to spin for a given timeout...
</blockquote></details>

I like the idea of using bool (true for success, right?). In other instances where we return -1 (mostly parsing) the failure is more obvious and unrecoverable.

As I said before, using `-EAGAIN` here kind of suggests that this function might fail in other ways which we should handle.


<!-- Sent from Reviewable.io -->

2022-02-25 15:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-Mwl_wO33DyFo851PULJ:b7da3fv) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the capital letter.
</blockquote></details>

With the capital letter, it's easier to write multi-sentence parameter descriptions (but do we ever do that?) But I don't mind either way.


<!-- Sent from Reviewable.io -->

2022-02-25 18:03 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 0 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiMnM9DQPYIL12OD1w:-MwlzXfT2V7xq8oma0qY:bo5krl4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I liked a single space for `\ret` and `\brief`. My opinion is the same as Borys's.
</blockquote></details>

Ok, then I'm changing it to a single space. Please check the new version and see if it looks better.

---
___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-Mwln3K26OZMWCgiQBUB:b18rspe) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
> > commit history is more like a list of changes/commands applied in order to the source.
> 
> Agreed, and commit message is describing these changes, or putting in your words: describes what a commit does "in general".

Commit message body: yes (but for this I think we don't have a uniform convention). For one-liners it's IMO different, you usually view them as a log of changes done to the codebase, so we use imperative mood.

Anyways, this seem to be mostly a matter of taste, so let's just vote who likes which style more and use the most preferred one. I prefer 3rd person and Borys prefers imperative mood. @dimakuv, @pwmarcz: Please vote :)
___
*[common/include/spinlock.h, line 126 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiOOMa1QZwISd0beWT:-MwltCZS-tonr56Mc-d5:b-5n3e9t) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/spinlock.h#L126)):*
> true for success, right?

Yup, definitely this way. Done.

> Yeah, and I wouldn't even call it a fail, it's a legitimate and expected timeout.

I consider this as a failure. IMO if it could also fail for other reasons (e.g. OOM), then we'd just return `-EAGAIN` and `-ENOMEM`.
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwlyXNBA_gKbEWvFoSm:bwfc97z) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we should not write multi-sentence descriptions here, they are supposed to be brief
</blockquote></details>

Sometimes we do when function semantic is non-trivial, see e.g. `parse_size_str()` in this very PR.
___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-MwlzE2UElMOysvcxGZn:b-4uytkp) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not correctly wrapped (line length).
</blockquote></details>

Will fix depending on the resolution of the other discussion on this line.


<!-- Sent from Reviewable.io -->

2022-02-25 20:04 UTC, boryspoplawski reviewed
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwmRPf1-tLvLe1CXQ-d:b-69r4dq) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> > commit history is more like a list of changes/commands applied in order to the source.
> 
> Agreed, and commit message is describing these changes, or putting in your words: describes what a commit does "in general".

Commit message body: yes (but for this I think we don't have a uniform convention). For one-liners it's IMO different, you usually view them as a log of changes done to the codebase, so we use imperative mood.

Anyways, this seem to be mostly a matter of taste, so let's just vote who likes which style more and use the most preferred one. I prefer 3rd person and Borys prefers imperative mood. @dimakuv, @pwmarcz: Please vote :)
</blockquote></details>

From prev comments seems like @pwmarcz prefers imperative and @dimakuv doesn't care.
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-MwmSzEz-kTaf29LVc5i:b-5mrvh6) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sometimes we do when function semantic is non-trivial, see e.g. `parse_size_str()` in this very PR.
</blockquote></details>

One could argue that the 2nd sentence should be moved to the extended description below.
___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRGf-8H5c1v7Y_v2n:-MwmTHTc8-qo9JUh8UBa:browqqx) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I think it's correct, but maybe changing `then`-> `in such a case` would help?
</blockquote></details>

Idk, it just reads weird to me


<!-- Sent from Reviewable.io -->

2022-02-26 09:27 UTC, pwmarcz reviewed
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwpJyqy5dEhzuPbh5mK:b-fcopys) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From prev comments seems like @pwmarcz prefers imperative and @dimakuv doesn't care.
</blockquote></details>

Yes, I prefer imperative for brief and 3rd person for description. Both as a matter of taste, and because it seems to be more common (when a project has a "brief" line, they generally use imperative for it).


<!-- Sent from Reviewable.io -->

2022-02-28 10:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-MwzpQ6YDG48sCwb5_DU:bsjp30x) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, I prefer imperative for brief and 3rd person for description. Both as a matter of taste, and because it seems to be more common (when a project has a "brief" line, they generally use imperative for it).
</blockquote></details>

I don't care.


<!-- Sent from Reviewable.io -->

2022-03-01 22:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 2 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 204 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiNrad7MP4AXJaz5uc:-Mx6U7kT3WFW8m1KzHCX:bd0ucch) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/include/api.h#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't care.
</blockquote></details>

Ok, changed to imperative then.
___
*[common/src/printf.c, line 59 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiQKmcCmGFdde3zqKg:-Mx5IJVOBiddxaog_ww3:bdo2q0z) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/common/src/printf.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

One could argue that the 2nd sentence should be moved to the extended description below.
</blockquote></details>

I prefer to keep it at the arg if it directly explain this very argument.


<!-- Sent from Reviewable.io -->

2022-03-01 23:30 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-MwmTD2l8nFhuwkgz3Td:bjto253) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will fix depending on the resolution of the other discussion on this line.
</blockquote></details>

Still incorrect?


<!-- Sent from Reviewable.io -->

2022-03-01 23:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx6pnAr7xGf3i4D_Feo:b-y0skhx) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still incorrect?
</blockquote></details>

Then what's "correct"? You mean I should wrap like it was a source file and ` * ` was at position 0 in it?


<!-- Sent from Reviewable.io -->

2022-03-01 23:51 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx6sm3GAHS1OwybRlXk:b-qjefn) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then what's "correct"? You mean I should wrap like it was a source file and ` * ` was at position 0 in it?
</blockquote></details>

I meant `(line length)`- to wrap it to 100 chars - it's in `.rst` but it's an example C source.
Idk about position of `*`, but probably yes, assume it's `0`, so like make line limit `108`


<!-- Sent from Reviewable.io -->

2022-03-02 09:09 UTC, pwmarcz reviewed
> Reviewed 5 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx8pjSv2FmrmaL2JchY:bswqjwn) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The line limit here is not `108`, and I am very much opposed to this suggestion (if I understood Borys correctly). How am I supposed to set up my Vim to automatically figure out that some lines are 100 chars and some 108?

The current version has a limit of 100 chars, and I prefer to keep like this.
</blockquote></details>

This is C source in our coding style (column limit 100) embedded inside reST (column limit 80), moved 6 characters to the right (notice the position of `/*` and `int`). I think two choices are appropriate:

1. Keep this wrapped at 80 characters, so that it's easy to edit in this file.
2. Keep this wrapped at 106 characters (not 108), so that the code block, which we display to the user, is wrapped to 100 characters.

I think the second choice is more "correct", since this is supposed to show our coding style. But it's also pretty inconvenient to edit, and maybe we need a (reST) comment explaining the column limit:

```
#. Prefer Qt-style ``/*!`` and ``\param``:

   ..
      Please keep the following code block wrapped at 100 characters (plus left margin):
      ....................................................................................................|

   .. code-block:: c

      /*!
       * \brief Sum two integers.

```


<!-- Sent from Reviewable.io -->

2022-03-02 09:13 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx8tgVXBElpmgN8ehlM:b-e669uu) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is C source in our coding style (column limit 100) embedded inside reST (column limit 80), moved 6 characters to the right (notice the position of `/*` and `int`). I think two choices are appropriate:

1. Keep this wrapped at 80 characters, so that it's easy to edit in this file.
2. Keep this wrapped at 106 characters (not 108), so that the code block, which we display to the user, is wrapped to 100 characters.

I think the second choice is more "correct", since this is supposed to show our coding style. But it's also pretty inconvenient to edit, and maybe we need a (reST) comment explaining the column limit:

```
#. Prefer Qt-style ``/*!`` and ``\param``:

   ..
      Please keep the following code block wrapped at 100 characters (plus left margin):
      ....................................................................................................|

   .. code-block:: c

      /*!
       * \brief Sum two integers.

```
</blockquote></details>

Why are we doing this? What will it solve? How do we verify this limit during code reviews?

I have a strong feeling we're doing some bike shedding here. Why not just go with the easiest option (a single char limit for each file type).


<!-- Sent from Reviewable.io -->

2022-03-02 09:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx8u1Qi0oeZlrpd6UYR:b-gers2u) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
> Why are we doing this? What will it solve?

Make the example consistent with other recommendations. We ask contributors to wrap at 100 columns, they should see code wrapped at 100 columns here. (They will probably read the HTML, so they don't care about how the reST source looks like).

>How do we verify this limit during code reviews?

To be clear, I'm not proposing to make a 106 column rule in such cases. I think we can make an exception for this code snippet (because it's supposed to show wrapping) and wrap everything else in our documentation at 80 columns. Hopefully, there won't be many snippets that even need wrapping.

But wrapping this one at 80 columns is fine for me, too.


<!-- Sent from Reviewable.io -->

2022-03-02 09:43 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx8zp-13Frtq8Aiex-q:b1muxfb) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> Why are we doing this? What will it solve?

Make the example consistent with other recommendations. We ask contributors to wrap at 100 columns, they should see code wrapped at 100 columns here. (They will probably read the HTML, so they don't care about how the reST source looks like).

>How do we verify this limit during code reviews?

To be clear, I'm not proposing to make a 106 column rule in such cases. I think we can make an exception for this code snippet (because it's supposed to show wrapping) and wrap everything else in our documentation at 80 columns. Hopefully, there won't be many snippets that even need wrapping.

But wrapping this one at 80 columns is fine for me, too.
</blockquote></details>

Yeah, typo, I meant `106` not `108`.

@dimakuv as @pwmarcz explained the idea is that this is an C code example that users will read in HTML. If we left the old wrapping (`80`), then such example wouldn't go through a review when copy-pasted...


<!-- Sent from Reviewable.io -->

2022-03-02 10:42 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-Mx9DHuo9hcavrfWVa16:b-q5inqz) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, typo, I meant `106` not `108`.

@dimakuv as @pwmarcz explained the idea is that this is an C code example that users will read in HTML. If we left the old wrapping (`80`), then such example wouldn't go through a review when copy-pasted...
</blockquote></details>

Ah, this discussion is purely for this particular "C code embedded in RST file" case. Thanks and sorry for confusion.


<!-- Sent from Reviewable.io -->

2022-03-02 14:57 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-MxA6r72DiHuhogXxodj:bpflcp2) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, this discussion is purely for this particular "C code embedded in RST file" case. Thanks and sorry for confusion.
</blockquote></details>

Not blocking, but @mkow please consider leaving a comment for the next person that tries to reformat this code :) (Either the one I suggested above, or something shorter)


<!-- Sent from Reviewable.io -->

2022-03-02 23:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Documentation/devel/howto-doc.rst, line 161 at r5](https://reviewable.io/reviews/gramineproject/gramine/420#-MwiRWOH2klKlD9hHGDj:-MxC2HjDDdTiHjdvWUJg:bqmjwcz) ([raw file](https://github.com/gramineproject/gramine/blob/032e709a38fb4672dc9048b9f25c96ff8078f457/Documentation/devel/howto-doc.rst#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 and blocking :)
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2022-03-02 23:57 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-03 10:17 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-03 12:35 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-03-03 12:40 UTC, pwmarcz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420#-:-MxEmoD2CQXUKOGY6p9o:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-03-03 12:42 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/420)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-03 13:08 UTC, merged