[Pal,LibOS] Emulate arch_prctl XSTATE component permission for AMX
gramineproject/gramine pull request #422
Opened 2022-02-22 10:11 UTC by dongx1x

## Description of the changes 
**Scheme:**
1. In Linux-SGX PAL: We enable the AMX feature via arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA) based on the setting of secs->attributes.xfrm AMX TILE bit.
2. In Linux PAL: We enable the AMX feature via arch_prctl(ARCH_REQ_XCOMP_PERM, AMX_TILEDATA) unconditionally, because we don't have anything to give us a hint whether the app on top of Gramine will use AMX or not. Linux is smart enough to not actually enable AMX immediately -- this only happens on the first AMX instruction (which results in #NM, and the Linux exception handler finally enables AMX at this point.
3. In LibOS: we emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM commands. For now, we can just emulate them by quering the CPUID (DkCpuIdRetrieve()) on the AMX leaf, and report only the AMX leaf (these commands are not used for anything else anyway currently).

Discuss here: #418 

## How to test this PR? 
Running AMX enabled workloads in a AMX enabled system

2022-02-22 10:13 UTC, dongx1x commented
@dimakuv please help review this PR, thanks!

2022-02-22 13:19 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dongx1x)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwW9K0sEVOzhYglI-lk):*
I would rephrase to this:
```
[Pal,LibOS] Add AMX-relevant `{GET,REQ}_XCOMP` commands to `arch_prctl()` emulation

Intel Advanced Matrix Extensions (AMX) are enabled in Linux kernel v5.16. This enablement
is opt-in for processes: a process that intends to use AMX must verify AMX availability with
`syscall(arch_prctl, ARCH_GET_XCOMP_PERM)` and set the AMX permission bit with
`syscall(arch_prctl, ARCH_REQ_XCOMP_PERM)`. Without this opt-in, any AMX-related
instruction triggers an #NM exception, and the process gets SIGILL.

With this commit, Linux PAL unconditionally sets the AMX permission on Gramine startup; it
may result in slightly worse performance but we do it for simplicity. Linux-SGX PAL sets the AMX
permission only if `AMX_TILEDATA` bit is set in the SECS.ATTRIBUTES.XFRM (i.e., the enclave
allows AMX support). LibOS emulates `{GET,REQ}_XCOMP` commands in `arch_prctl()` syscall
effectively as no-ops: LibOS queries CPUID whether AMX is supported and returns success if it is
(and a corresponding error code if AMX is not supported by the host/enclave).

Note that on Linux kernel prior to v5.16, Gramine may enable the AMX hardware feature and
use it. This should be fine because Gramine allocates large-enough signal frames for AMX
state and correctly saves/restores the whole XSAVE area, including AMX.
```

(Of course, the above text should be re-aligned to 72-char line limit)

We don't need to add a reference to the Intel SDM document in the commit message. A reference in the code comment is enough.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXAp11Pg8xvertM96:-MwWXAp11Pg8xvertM97:b-yyt7uz) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L15)):*
> ```C
> #include "shim_tcb.h"
> 
> #define CPUID_LEAF_XSAVE 0x0000000d
> ```

Rename to `EXTENDED_STATE_LEAF` and please move this macro here: https://github.com/gramineproject/gramine/blob/0affeefe376143614dd1122096ef8e79c782cc58/common/include/arch/x86_64/cpu.h#L20?plain=1

Also, please remove a similar macro from here, to avoid duplication: https://github.com/gramineproject/gramine/blob/0affeefe376143614dd1122096ef8e79c782cc58/Pal/src/host/Linux-SGX/db_misc.c#L33?plain=1
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXUhnDqVvmjkHwYjx:-MwWXUhnDqVvmjkHwYjy:b1chvvh) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L18)):*
> ```C
> 
> long shim_do_arch_prctl(int code, unsigned long addr) {
>     unsigned int value[4];
> ```

`unsigned int values[CPUID_WORD_NUM];`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXiMl7jxImVGwEKDw:-MwWXiMl7jxImVGwEKDx:bz7dn47) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L31)):*
> ```C
> 
>         /* Emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM by
>          * querying CPUID, it's safe because the "loader" has requested AMX permission
> ```

`the "loader" has requested AMX permission` -> `PAL already requested AMX permission at startup`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXqhv2xY-6fHn1HdV:-MwWXqhv2xY-6fHn1HdW:b-ufwadl) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L32)):*
> ```C
>         /* Emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM by
>          * querying CPUID, it's safe because the "loader" has requested AMX permission
>          */
> ```

Please don't use this style of comments: either have the first and the last lines "empty", or have both first and last lines filled with text.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYIRI8w3BWxnNO9W1:-MwWYIRI8w3BWxnNO9W2:btc79y4) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L36)):*
> ```C
>         case ARCH_GET_XCOMP_PERM:
>             ret = DkCpuIdRetrieve(CPUID_LEAF_XSAVE, 0, value);
>             if ( ret < 0) {
> ```

`( ret < 0)` -> `(ret < 0)`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYVx501h7yisTydFZ:-MwWYVx501h7yisTydF_:bablukm) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L37)):*
> ```C
>             ret = DkCpuIdRetrieve(CPUID_LEAF_XSAVE, 0, value);
>             if ( ret < 0) {
>                 log_warning("CPUID retrieve faild: %d", ret);
> ```

Let's simply remove this logging, it's not that helpful.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYgMKApkpqo19WRiX:-MwWYgMKApkpqo19WRiY:bo27nax) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L40)):*
> ```C
>                 return pal_to_unix_errno(ret);
>             }
>             *(unsigned long*)addr = value[CPUID_WORD_EAX] | ((uint64_t)value[CPUID_WORD_EDX] << 32);
> ```

`unsigned long` -> `uint64_t` (based on this description: https://lkml.org/lkml/2021/10/26/233, it should be uint64 type explicitly)
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYv5o2fj8bceTNp6K:-MwWYv5o2fj8bceTNp6L:b-63sfrp) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L41)):*
> ```C
>             }
>             *(unsigned long*)addr = value[CPUID_WORD_EAX] | ((uint64_t)value[CPUID_WORD_EDX] << 32);
>             return 0;
> ```

Please add an empty line after this one, for readability
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWZ-962y98OZCfvEgu:-MwWZ-962y98OZCfvEgv:b-qybeib) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L44)):*
> ```C
>         case ARCH_REQ_XCOMP_PERM:
>             /* The request must be the highest state component number related to that facility,
>              * current kernel only support to AMX_TILEDATA (18) */
> ```

`current kernel only support to AMX_TILEDATA (18)` -> `current Linux kernel supports only AMX_TILEDATA (bit 18)`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWZFjq5oPRIggCJn6_:-MwWZFjq5oPRIggCJn6a:bryvl0r) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L46)):*
> ```C
>              * current kernel only support to AMX_TILEDATA (18) */
>             if (addr != AMX_TILEDATA)
>             {
> ```

We don't use such style, please move this `{` to the previous line
___
*[LibOS [...]

2022-02-23 08:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 1 of 9 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @dongx1x)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mw_gKX0DjH4Lh7jsBeg:-Mw_gKX14fQz0ziSz0xG:b-rehsxm) (no related file):*
@dongx1x Please read our Onboarding page on how to work on a PR: https://gramine.readthedocs.io/en/latest/devel/onboarding.html#typical-gramine-development-flows. Please pay attention to steps 7-12 in that list.

Concretely, please use the Reviewable plugin in our GitHub repo to work on comments. The Reviewable plugin is opened when you click on the big purple "Reviewable" button in the PR description. This plugin is easy to use, I suggest to read the docs: https://reviewable.io/

When you want to reply to some comment from a reviewer, in Reviewable you go to the appropriate comment and either click "Done" button or leave a text reply. Please do it for my comments.

Many reviewers only get notifications on PRs when something changes in the Reviewable status. So if you don't use Reviewable, reviewers may simply not notice that you modified your PR.

---


<!-- Sent from Reviewable.io -->

2022-02-23 13:14 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 1 of 9 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @dongx1x)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mw_gKX0DjH4Lh7jsBeg:-MwahNi0AX8acCHTGn5F:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@dongx1x Please read our Onboarding page on how to work on a PR: https://gramine.readthedocs.io/en/latest/devel/onboarding.html#typical-gramine-development-flows. Please pay attention to steps 7-12 in that list.

Concretely, please use the Reviewable plugin in our GitHub repo to work on comments. The Reviewable plugin is opened when you click on the big purple "Reviewable" button in the PR description. This plugin is easy to use, I suggest to read the docs: https://reviewable.io/

When you want to reply to some comment from a reviewer, in Reviewable you go to the appropriate comment and either click "Done" button or leave a text reply. Please do it for my comments.

Many reviewers only get notifications on PRs when something changes in the Reviewable status. So if you don't use Reviewable, reviewers may simply not notice that you modified your PR.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-02-23 13:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 1 of 9 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @dongx1x)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mw_gKX0DjH4Lh7jsBeg:-Mwaj4Pw5lfMUfuTUAuB:bnjduhj) (no related file):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@dongx1x What about all my other comments? Please also mark them all as "Done" (or leave comments if you didn't implement some of my comments).

---


<!-- Sent from Reviewable.io -->

2022-02-23 13:54 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 1 of 9 files reviewed, 29 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mw_gKX0DjH4Lh7jsBeg:-MwakZwkClo_rawSf3lU:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@dongx1x What about all my other comments? Please also mark them all as "Done" (or leave comments if you didn't implement some of my comments).
</blockquote></details>

Done.

---
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwW9K0sEVOzhYglI-lk):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would rephrase to this:
```
[Pal,LibOS] Add AMX-relevant `{GET,REQ}_XCOMP` commands to `arch_prctl()` emulation

Intel Advanced Matrix Extensions (AMX) are enabled in Linux kernel v5.16. This enablement
is opt-in for processes: a process that intends to use AMX must verify AMX availability with
`syscall(arch_prctl, ARCH_GET_XCOMP_PERM)` and set the AMX permission bit with
`syscall(arch_prctl, ARCH_REQ_XCOMP_PERM)`. Without this opt-in, any AMX-related
instruction triggers an #NM exception, and the process gets SIGILL.

With this commit, Linux PAL unconditionally sets the AMX permission on Gramine startup; it
may result in slightly worse performance but we do it for simplicity. Linux-SGX PAL sets the AMX
permission only if `AMX_TILEDATA` bit is set in the SECS.ATTRIBUTES.XFRM (i.e., the enclave
allows AMX support). LibOS emulates `{GET,REQ}_XCOMP` commands in `arch_prctl()` syscall
effectively as no-ops: LibOS queries CPUID whether AMX is supported and returns success if it is
(and a corresponding error code if AMX is not supported by the host/enclave).

Note that on Linux kernel prior to v5.16, Gramine may enable the AMX hardware feature and
use it. This should be fine because Gramine allocates large-enough signal frames for AMX
state and correctly saves/restores the whole XSAVE area, including AMX.
```

(Of course, the above text should be re-aligned to 72-char line limit)

We don't need to add a reference to the Intel SDM document in the commit message. A reference in the code comment is enough.
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXAp11Pg8xvertM96:-MwakbfbAopYgW7WQKVM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rename to `EXTENDED_STATE_LEAF` and please move this macro here: https://github.com/gramineproject/gramine/blob/0affeefe376143614dd1122096ef8e79c782cc58/common/include/arch/x86_64/cpu.h#L20?plain=1

Also, please remove a similar macro from here, to avoid duplication: https://github.com/gramineproject/gramine/blob/0affeefe376143614dd1122096ef8e79c782cc58/Pal/src/host/Linux-SGX/db_misc.c#L33?plain=1
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 18 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXUhnDqVvmjkHwYjx:-MwakdSAB2dCQZ5m6mGA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`unsigned int values[CPUID_WORD_NUM];`
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXiMl7jxImVGwEKDw:-MwakhfSC0Q0nPkeRJgu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the "loader" has requested AMX permission` -> `PAL already requested AMX permission at startup`
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 32 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWXqhv2xY-6fHn1HdV:-Mwakg57BikZL0JQoBOh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use this style of comments: either have the first and the last lines "empty", or have both first and last lines filled with text.
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYIRI8w3BWxnNO9W1:-MwakjYz730imfujSMcv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`( ret < 0)` -> `(ret < 0)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYVx501h7yisTydFZ:-Mwakk5S4WeP9GYLnEra:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's simply remove this logging, it's not that helpful.
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 40 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYgMKApkpqo19WRiX:-MwapyFlEYpfEOJGJ9C5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`unsigned long` -> `uint64_t` (based on this description: https://lkml.org/lkml/2021/10/26/233, it should be uint64 type explicitly)
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWYv5o2fj8bceTNp6K:-Mwaktgy6mwhc97pOo1G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this one, for readability
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 44 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWZ-962y98OZCfvEgu:-Mwaq1-K78sljE4phykc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`current kernel only support to AMX_TILEDATA (18)` -> `current Linux kernel supports only AMX_TILEDATA (bit 18)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/422#-MwWZFjq5oPRIggCJn6_:-MwakuXj-IaI5ps7w715:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9228c170b4eb5b6dc00283dbeaa5b26f597c0e83/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L46)):*
<details><summary><i>Previously, [...]

2022-02-23 15:11 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dongx1x)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mw_gKX0DjH4Lh7jsBeg:-Mwb5b7ECtU6p8rl1IZK:bpaj3m5) (no related file):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please don't use the `git rebase` flow unless absolutely necessary. To address some comments or fix some bugs, please use instead `git fixup`. See the "Onboarding" page of Gramine for how to correctly work on PRs to this project.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwb7ghX1Dohtxu7jsV0:-Mwb7ghX1Dohtxu7jsV1:bsxiot1) (no related file):*
Looks good to me, let's see what our (no AMX) CI thinks about it. I'll also test quickly on my AMX machine.

---


<!-- Sent from Reviewable.io -->

2022-02-23 15:25 UTC, dimakuv commented
Jenkins, test this please

2022-02-23 15:49 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`fdatasync01` LTP test timed out, known problem)

2022-02-23 18:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 5 files at r1, 6 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dongx1x)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbaZ1P6_95lfmqA1V8:-MwbaZ1P6_95lfmqA1V9:b-rmg70e) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L60)):*
> ```objc
>  * commands. See
>  * https://elixir.bootlin.com/linux/v5.16/source/arch/x86/include/uapi/asm/prctl.h */
> #if !defined(ARCH_GET_XCOMP_SUPP)
> ```

We generally use `ifndef` in such cases
___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbasGbAoa-ZEY9o65u:-MwbasGbAoa-ZEY9o65v:bgicstm) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L61)):*
> ```objc
>  * https://elixir.bootlin.com/linux/v5.16/source/arch/x86/include/uapi/asm/prctl.h */
> #if !defined(ARCH_GET_XCOMP_SUPP)
> #define ARCH_GET_XCOMP_SUPP 0x1021
> ```

Why these are defined in `shim_syscalls.h`? These are not syscall numbers.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgkKI-T1CXHjnl-OW:-MwbgkKI-T1CXHjnl-OX:bvhfy54) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L17)):*
> ```C
> long shim_do_arch_prctl(int code, unsigned long addr) {
>     unsigned int values[CPUID_WORD_NUM];
>     unsigned int amx_mask;
> ```

This should be moved to the place it's used (there is only one)
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 31 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwblArx-8e4u1yGxPn1:-MwblArx-8e4u1yGxPn2:b-xlait5) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L31)):*
> ```C
>          * querying CPUID, it's safe because the PAL already requested AMX permission
>          * at startup */
>         case ARCH_GET_XCOMP_SUPP:
> ```

Please add a comment clarifying that supported and currently enabled sets are always the same in Gramine (because PAL always enables all it can at startup).
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbi4zn-TU2TMvS5qPZ:-Mwbi4zn-TU2TMvS5qP_:b-8o5bd5) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L33)):*
> ```C
>         case ARCH_GET_XCOMP_SUPP:
>         case ARCH_GET_XCOMP_PERM:
>             ret = DkCpuIdRetrieve(EXTENDED_STATE_LEAF, 0, values);
> ```

`0` -> appropriate value from enum
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbjUvf7qRjK2lgTj91:-MwbjUvf7qRjK2lgTj92:b-6tchzv) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L37)):*
> ```C
>                 return pal_to_unix_errno(ret);
>             }
>             *(uint64_t*)addr = values[CPUID_WORD_EAX] | ((uint64_t)values[CPUID_WORD_EDX] << 32);
> ```

First check that `is_user_memory_writable(addr, sizeof(uint64_t))`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 48 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbjuMTDU2SkuilBYOs:-MwbjuMTDU2SkuilBYOt:b665z3a) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L48)):*
> ```C
>             }
> 
>             ret = DkCpuIdRetrieve(EXTENDED_STATE_LEAF, 0, values);
> ```

ditto (0)
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwbkJmJ1-UBw8m9pgNO:bgghcqk) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
> ```C
>             }
> 
>             amx_mask = (1 << AMX_TILECFG) | (1 << AMX_TILEDATA);
> ```

Isn't it enough to check `AMX_TILEDATA`?
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkWeaAvlbN8yo6LJs:-MwbkWeaAvlbN8yo6LJt:b-ucpuj7) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L55)):*
> ```C
>             amx_mask = (1 << AMX_TILECFG) | (1 << AMX_TILEDATA);
>             if ((values[CPUID_WORD_EAX] & amx_mask) != amx_mask) {
>                 log_warning("AMX is not supported on this CPU (XSAVE bits are 0x%x)",
> ```

`0x%x` -> `%#x`
___
*[Pal/include/host/Linux-common/syscall.h, line 43 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgQLL42GhL_IS7CLo:-MwbgQLL42GhL_IS7CLp:b-algu54) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/include/host/Linux-common/syscall.h#L43)):*
> ```objc
>  * commands. See
>  * https://elixir.bootlin.com/linux/v5.16/source/arch/x86/include/uapi/asm/prctl.h */
> #if !defined(ARCH_GET_XCOMP_SUPP)
> ```

ditto (ifndef)
___
*[Pal/include/host/Linux-common/syscall.h, line 44 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgRq39xFmM1bKK4TT:-MwbgRq39xFmM1bKK4TU:b-v78ffu) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/include/host/Linux-common/syscall.h#L44)):*
> ```objc
>  * https://elixir.bootlin.com/linux/v5.16/source/arch/x86/include/uapi/asm/prctl.h */
> #if !defined(ARCH_GET_XCOMP_SUPP)
> #define ARCH_GET_XCOMP_SUPP 0x1021
> ```

ditto (these do not belong to this header)
___
*[Pal/src/host/Linux/db_main.c, line 243 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbg0Tr1KCw4I8GGB1A:-Mwbg0Tr1KCw4I8GGB1B:buozrwh) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux/db_main.c#L243)):*
> ```C
>          * EOPNOTSUPP, then we are on older/patched Linux with no need for arch_prctl-style AMX
>          * enablement, simply ignore the result of this syscall. */
>         ret = DO_SYSCALL(arch_prctl, ARCH_REQ_XCOMP_PERM, AMX_TILEDATA);
> ```

This should be hidden behind `#ifdef __x86_64__`
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwbfcNgBiFBgV_K5sYR:b-pultt9) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
> ```C
>      * (we examine  enclave's SECS.ATTRIBUTES.XFRM). It's enough to do it once: child processes
>      * will inherit the permission, but here for simplicity we call it in every child process as
>      * well. If arch_prctl() returns EINVAL or EOPNOTSUPP, then we are on older/patched Linux with
> ```

What do you mean by `patched`?


<!-- Sent from Reviewable.io -->

2022-02-23 18:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dongx1x)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbasGbAoa-ZEY9o65u:-Mwbqb4M0cXZ03zqQO0U:bn8ru4e) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why these are defined in `shim_syscalls.h`? These are not syscall numbers.
</blockquote></details>

@boryspoplawski Where would you propose to put them? It was me who recommended this header file, because I don't know what would be the best place for these defs... Would you propose a new separate header?
___
*[Pal/include/host/Linux-common/syscall.h, line 44 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgRq39xFmM1bKK4TT:-Mwbqn1oC2L66cwBtgnU:bn8ru4e) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/include/host/Linux-common/syscall.h#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (these do not belong to this header)
</blockquote></details>

@boryspoplawski Where would you propose to put them? It was me who recommended this header file, because I don't know what would be the best place for these defs... Would you propose a new separate header?
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwbqqYq-6ZFH_MiWAie:b-axswqm) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean by `patched`?
</blockquote></details>

@boryspoplawski  At Intel, we have a bunch of Linux systems with e.g. v5.12 and a set of patches on top. One of them being (some intermediate) AMX patch, which has slightly different semantics as the final version of AMX code in the upstream v5.16. We want to support these custom Linux systems as well, that's why we mention this.


<!-- Sent from Reviewable.io -->

2022-02-24 08:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dongx1x)

___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbasGbAoa-ZEY9o65u:-MwepLCQBUQ0uReknpO8:bpsqarc) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Either a new header or `LibOS/shim/include/arch/x86_64/shim_types-arch.h`, or directly in `LibOS/shim/src/arch/x86_64/shim_arch_prctl.c`
</blockquote></details>

I prefer `LibOS/shim/src/arch/x86_64/shim_arch_prctl.c`. @dongx1x Please move this snippet from this header file to that C file.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 31 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwblArx-8e4u1yGxPn1:-MwepUfn-nYgum3iegoA:by043ug) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment clarifying that supported and currently enabled sets are always the same in Gramine (because PAL always enables all it can at startup).
</blockquote></details>

To make Borys's request more specific, I suggest to add like this:
```
        /* Emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM by
         * querying CPUID, it's safe because the PAL already requested AMX permission
         * at startup. Note that supported and currently enabled sets are always the
         * same in Gramine (because PAL always enables all it can at startup). */

```
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MweplMCAJ0KBhy9GUnF:b4nw4s8) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't it enough to check `AMX_TILEDATA`?
</blockquote></details>

I think it's reasonable to check both AMX bits -- AMX must always come with both these bits enabled. So I see no reason why to check only one bit. (I mean, checking two bits is the most logical thing to do if we want to check AMX enablement, otherwise the reader will be surprised.)
___
*[Pal/include/host/Linux-common/syscall.h, line 44 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgRq39xFmM1bKK4TT:-MweqcUO9gVOabQf_zMG:b4mckug) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/include/host/Linux-common/syscall.h#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Probably a separate header or duplicate them and put in host specific headers
</blockquote></details>

To satisfy Borys's request, @dongx1x I suggest you to move this snippet (twice) to these files:
- `Pal/include/arch/x86_64/Linux/pal_host-arch.h`
-  `Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h`
___
*[Pal/src/host/Linux/db_main.c, line 242 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MweqJ1U2Zj0ghrMSybC:-MweqJ1U2Zj0ghrMSybD:bl43yeh) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux/db_main.c#L242)):*
> ```C
>          * child processes will inherit the permission. If arch_prctl() returns EINVAL or
>          * EOPNOTSUPP, then we are on older/patched Linux with no need for arch_prctl-style AMX
>          * enablement, simply ignore the result of this syscall. */
> ```

@dongx1x Please remove the `If arch_prctl() returns EINVAL ...` sentence completely.

See other comment for the discussion of this decision.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MweqA2c2Gcnuf-RDmJ3:b9pqak8) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This sentence in the comment makes no sense if you are not aware of what you described. I would just remove it
</blockquote></details>

Fair enough. @dongx1x Please remove the `If arch_prctl() returns EINVAL ...` sentence completely.


<!-- Sent from Reviewable.io -->

2022-02-24 10:41 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @dongx1x)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwfJCZs2kItcPHVt43L:b-ud0kjc) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it's reasonable to check both AMX bits -- AMX must always come with both these bits enabled. So I see no reason why to check only one bit. (I mean, checking two bits is the most logical thing to do if we want to check AMX enablement, otherwise the reader will be surprised.)
</blockquote></details>

But we are checking if what user requested is satisfied and user requested only bit `AMX_TILEDATA` (so I fail to see how checking both is the most logical thing to do).
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwfJZ09BYpJz-s2UEEO:bu5gtjq) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Fair enough. @dongx1x Please remove the `If arch_prctl() returns EINVAL ...` sentence completely.
</blockquote></details>

But we need some description why we can sometimes ignore the result


<!-- Sent from Reviewable.io -->

2022-02-24 11:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dongx1x)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwfPym_8CYvQFmM7igb:b-e2kroh) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we are checking if what user requested is satisfied and user requested only bit `AMX_TILEDATA` (so I fail to see how checking both is the most logical thing to do).
</blockquote></details>

Hm. Yeah, you're right. The most logical thing is to only check `AMX_TILEDATA` bit. @dongx1x Please update accordingly.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwfQ6R_5hS79jZmlVO9:b-k9hxt0) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we need some description why we can sometimes ignore the result
</blockquote></details>

@boryspoplawski So do you want to *remove* this sentence or you want to *modify* this sentence?

If you want to modify this sentence, does this rewording work for you?
```
     * well. Some deployment environments run Linux systems earlier than v5.16 but with 
     * an AMX-specific patch; this patch doesn't introduce `arch_prctl(ARCH_REQ_XCOMP_PERM)`
     * syscall so an attempt to call it may return EINVAL, EOPNOTSUPP or ENOSYS. In this case,
     * we simply ignore the result of this syscall. */
```


<!-- Sent from Reviewable.io -->

2022-02-24 11:21 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dongx1x)

___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwfRO4j5RJG8qzYvm9a:bty9wfk) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski So do you want to *remove* this sentence or you want to *modify* this sentence?

If you want to modify this sentence, does this rewording work for you?
```
     * well. Some deployment environments run Linux systems earlier than v5.16 but with 
     * an AMX-specific patch; this patch doesn't introduce `arch_prctl(ARCH_REQ_XCOMP_PERM)`
     * syscall so an attempt to call it may return EINVAL, EOPNOTSUPP or ENOSYS. In this case,
     * we simply ignore the result of this syscall. */
```
</blockquote></details>

Sorry, I wasn't clear. I wanted to remove `/patched` from the sentence, but if you think this information is useful to some users, then modifying is also fine.

Btw, I would also like to stress that I very much dislike the idea of supporting (here: handling specific set of return values) some custom patch set, which we cannot even check/read. This sets a dangerous precedence.


<!-- Sent from Reviewable.io -->

2022-02-25 09:53 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 3 of 11 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwb7ghX1Dohtxu7jsV0:-MwkHl_M3tYqmXdqBg0-:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My AMX machine reported:
```
$ gramine-direct ./amxtest
error: PAL failed at ../Pal/src/host/Linux/db_main.c:pal_linux_main:245 (exitcode = 6, reason=Requesting AMX permission failed)

$ gramine-sgx ./amxtest
error: Requesting AMX permission failed: -38
error: Creating enclave failed: -38
```

This is because we don't account for `-ENOSYS` (`-38`) in our checks. I added corresponding comments. Please fix them.
</blockquote></details>

Done.

---
___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 60 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbaZ1P6_95lfmqA1V8:-MwkGTPoAgL8PXKGk2fn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We generally use `ifndef` in such cases
</blockquote></details>

Done.
___
*[LibOS/shim/include/arch/x86_64/shim_syscalls.h, line 61 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbasGbAoa-ZEY9o65u:-MwkGWe35DFQsIVnyXP6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/include/arch/x86_64/shim_syscalls.h#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I prefer `LibOS/shim/src/arch/x86_64/shim_arch_prctl.c`. @dongx1x Please move this snippet from this header file to that C file.
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbgkKI-T1CXHjnl-OW:-MwkGYTH3dniV0lhlKAQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This should be moved to the place it's used (there is only one)
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 31 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwblArx-8e4u1yGxPn1:-MwkICJv4GU9z7bjLlbt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To make Borys's request more specific, I suggest to add like this:
```
        /* Emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM by
         * querying CPUID, it's safe because the PAL already requested AMX permission
         * at startup. Note that supported and currently enabled sets are always the
         * same in Gramine (because PAL always enables all it can at startup). */

```
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbi4zn-TU2TMvS5qPZ:-MwkGtDjAS1-rjZ28oy2:b-vo56l6) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`0` -> appropriate value from enum
</blockquote></details>

Done. Added a new `enum extended_state_sub_leaf`
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 37 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbjUvf7qRjK2lgTj91:-MwkH5knCpl87aOMpaTD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

First check that `is_user_memory_writable(addr, sizeof(uint64_t))`
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 48 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbjuMTDU2SkuilBYOs:-MwkH6z02IhN6IkUcou3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (0)
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwkH8OL8ht_-liK78sn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm. Yeah, you're right. The most logical thing is to only check `AMX_TILEDATA` bit. @dongx1x Please update accordingly.
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 55 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkWeaAvlbN8yo6LJs:-MwkH9TH66fHpIZkp4g4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`0x%x` -> `%#x`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 242 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MweqJ1U2Zj0ghrMSybC:-MwkHMC265sZXRFF4B0i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux/db_main.c#L242)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@dongx1x Please remove the `If arch_prctl() returns EINVAL ...` sentence completely.

See other comment for the discussion of this decision.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 243 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbg0Tr1KCw4I8GGB1A:-MwkHNWaET-Aa48NKkEC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux/db_main.c#L243)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This should be hidden behind `#ifdef __x86_64__`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 244 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbCTUKCe4dP5GRtbzo:-MwkHPyH9FJwQxMPR9FP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux/db_main.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add `&& ret != -ENOSYS` here. I hit this error on the AMX-patched Linux kernel v5.12.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwkH_OA4yHrIqh_Cj_q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L [...]

2022-02-25 10:42 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dongx1x)

___
*[common/include/arch/x86_64/cpu.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRAFo96NSwTsDF2hV:-MwkRAFo96NSwTsDF2hW:b-q7gvvg) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L30)):*
> ```objc
>  * n = 0: bitmap of all the user state components that can be managed using the XSAVE feature set
>  * n = 1: bitmap of extensions of XSAVE feature set
>  * n > 1: details (size and offset) of each state component, we can reuse `enum cpu_extension`
> ```

`we can reuse ...` -> `where n corresponds to ...`
___
*[common/include/arch/x86_64/cpu.h, line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkR6w2COTkXOmsx0Ft:-MwkR6w2COTkXOmsx0Fu:bar7rzb) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L31)):*
> ```objc
>  * n = 1: bitmap of extensions of XSAVE feature set
>  * n > 1: details (size and offset) of each state component, we can reuse `enum cpu_extension`
>  * For more informations, see CPUID description in Intel SDM, Vol. 2A, Chapter 3.2. */
> ```

`informations` -> `information`
___
*[common/include/arch/x86_64/cpu.h, line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRNkg0wWYQFLsyM3w:-MwkRNkg0wWYQFLsyM3x:b-v4ngyd) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L34)):*
> ```objc
> enum extended_state_sub_leaf {
>     EXTENDED_STATE_FEATURES = 0,
>     EXTENDED_STATE_EXTENSIONS = 1,
> ```

Please add suffix `_SUBLEAF` to both of these constants.
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSotE2S9wzw_H5T3O:-MwkSotE2S9wzw_H5T3P:b-94cpe8) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L23)):*
> ```objc
> /* Linux v5.16 supports Intel AMX. To enable this feature, Linux added several XSTATE-related
>  * arch_prctl() commands. To support Gramine on older Linux kernels, we explicitly define these
>  * commands. See
> ```

`we explicitly define these commands` -> `we explicitly define the required ARCH_REQ_XCOMP_PERM command`
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSinq5ZjucuHwdz60:-MwkSinr4Dt2c-cjVr34:bsa44no) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L33)):*
> ```objc
> #ifndef ARCH_REQ_XCOMP_PERM
> #define ARCH_REQ_XCOMP_PERM 0x1023
> #endif
> ```

In reality, we only need `ARCH_REQ_XCOMP_PERM` in the PAL code. Let's remove the other two completely.
___
*[Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h, line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSx2W2K397iEuhms5:-MwkSx2W2K397iEuhms6:b-94cpe8) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h#L12)):*
> ```objc
> /* Linux v5.16 supports Intel AMX. To enable this feature, Linux added several XSTATE-related
>  * arch_prctl() commands. To support Gramine on older Linux kernels, we explicitly define these
>  * commands. See
> ```

`we explicitly define these commands` -> `we explicitly define the required ARCH_REQ_XCOMP_PERM command`
___
*[Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSndEDEd1GACGlY5X:-MwkSndEDEd1GACGlY5Y:bsa44no) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h#L21)):*
> ```objc
> #endif
> #ifndef ARCH_REQ_XCOMP_PERM
> #define ARCH_REQ_XCOMP_PERM 0x1023
> ```

In reality, we only need `ARCH_REQ_XCOMP_PERM` in the PAL code. Let's remove the other two completely.
___
*[Pal/src/host/Linux/db_main.c, line 243 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkT4WrCpHAoj72r_hY:-MwkT4WrCpHAoj72r_hZ:bi9qf2p) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/src/host/Linux/db_main.c#L243)):*
> ```C
>          * child processes will inherit the permission. If arch_prctl() returns EINVAL, EOPNOTSUPP
>          * or ENOSYS, then we are on older/patched Linux with no need for arch_prctl-style AMX
>          * enablement, simply ignore the result of this syscall. */
> ```

Actually, we already give very detailed explanations in the other, Linux-SGX file. Let's keep this comment very short:
```
        /* Linux v5.16 introduced support for Intel AMX feature. Any process must opt-in for AMX
         * by issuing an AMX-permission request, so call arch_prctl() to request AMX permission
         * unconditionally. For more details, see similar code in Linux-SGX PAL. */
```
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 201 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbfcNgBiFBgV_K5sYQ:-MwkSBxY5flAvsYbKwwc:bbtgnp3) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/Pal/src/host/Linux-SGX/sgx_framework.c#L201)):*
> Btw, I would also like to stress that I very much dislike the idea of supporting (here: handling specific set of return values) some custom patch set, which we cannot even check/read. This sets a dangerous precedence.

Yeah, I know... 


<!-- Sent from Reviewable.io -->

2022-02-25 11:07 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 6 of 11 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[common/include/arch/x86_64/cpu.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRAFo96NSwTsDF2hV:-MwkYEMbDxPgkCREmI8f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`we can reuse ...` -> `where n corresponds to ...`
</blockquote></details>

Done.
___
*[common/include/arch/x86_64/cpu.h, line 31 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkR6w2COTkXOmsx0Ft:-MwkYGmUEwnHrpLxjdKj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`informations` -> `information`
</blockquote></details>

Done.
___
*[common/include/arch/x86_64/cpu.h, line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRNkg0wWYQFLsyM3w:-MwkYSC22qD65ArEmt2g:b-ycpgf2) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add suffix `_SUBLEAF` to both of these constants.
</blockquote></details>

How about EXTENDED_STATE_SUBLEAF_*?
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 23 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSotE2S9wzw_H5T3O:-MwkYlC03evgrJKjJ6K5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`we explicitly define these commands` -> `we explicitly define the required ARCH_REQ_XCOMP_PERM command`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 33 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSinq5ZjucuHwdz60:-MwkYmJSAaX63LcPxEBx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In reality, we only need `ARCH_REQ_XCOMP_PERM` in the PAL code. Let's remove the other two completely.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h, line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSx2W2K397iEuhms5:-MwkYo1970qFFHp9xUxj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`we explicitly define these commands` -> `we explicitly define the required ARCH_REQ_XCOMP_PERM command`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h, line 21 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkSndEDEd1GACGlY5X:-MwkYqzA5LYO4lbbjRgv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In reality, we only need `ARCH_REQ_XCOMP_PERM` in the PAL code. Let's remove the other two completely.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 243 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkT4WrCpHAoj72r_hY:-MwkYyiI-7vVdblq4Pbf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/Pal/src/host/Linux/db_main.c#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, we already give very detailed explanations in the other, Linux-SGX file. Let's keep this comment very short:
```
        /* Linux v5.16 introduced support for Intel AMX feature. Any process must opt-in for AMX
         * by issuing an AMX-permission request, so call arch_prctl() to request AMX permission
         * unconditionally. For more details, see similar code in Linux-SGX PAL. */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-25 11:14 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dongx1x)

___
*[-- commits, line 32 at r5](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwk_-V31NunJy5bAF3m):*
Please don't do a `fixup` of a `fixup`. Always point to the actual base commit to which you do the fixup.

It's ok to continue doing fixups of a latest fixup *for this PR* (since you already started doing this), otherwise you'll get confused on the ordering. But for the future, please keep just "one level" of fixups.
___
*[common/include/arch/x86_64/cpu.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRAFo96NSwTsDF2hV:-Mwk_6og3JMKfn2t47oP:bq5s8sq) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L30)):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please also align the second line to start under `details`, otherwise it's hard to read
___
*[common/include/arch/x86_64/cpu.h, line 34 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRNkg0wWYQFLsyM3w:-Mwk_ESW2idByQ23wt1V:bh943f3) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L34)):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

How about EXTENDED_STATE_SUBLEAF_*?
</blockquote></details>

Yes, looks good.


<!-- Sent from Reviewable.io -->

2022-02-25 11:26 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 10 of 11 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 32 at r5](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwk_-V31NunJy5bAF3m):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't do a `fixup` of a `fixup`. Always point to the actual base commit to which you do the fixup.

It's ok to continue doing fixups of a latest fixup *for this PR* (since you already started doing this), otherwise you'll get confused on the ordering. But for the future, please keep just "one level" of fixups.
</blockquote></details>

OK
___
*[common/include/arch/x86_64/cpu.h, line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkRAFo96NSwTsDF2hV:-Mwkbzxf6Zu81FkSp8N9:bdvg1w4) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/common/include/arch/x86_64/cpu.h#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also align the second line to start under `details`, otherwise it's hard to read
</blockquote></details>

Done, you are right


<!-- Sent from Reviewable.io -->

2022-02-25 12:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-25 12:18 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @dongx1x)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbi4zn-TU2TMvS5qPZ:-MwkMfmEEqlyaO4QkuNK:bygdqpa) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L33)):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done. Added a new `enum extended_state_sub_leaf`
</blockquote></details>

I thought we already had something
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwkLdNv8cRal2dyMy_F:b-p8vc) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now it's not really a mask, just one bit and we can simplify the condition and remove the variable
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 41 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkKwCH0zZNfQqPbN--:-MwkKwCH0zZNfQqPbN-0:b5tki0t) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L41)):*
> ```C
>             return pal_to_unix_errno(DkSegmentBaseGet(PAL_SEGMENT_FS, (unsigned long*)addr));
> 
>         /* Emulate ARCH_GET_XCOMP_SUPP, ARCH_GET_XCOMP_PERM, ARCH_REQ_XCOMP_PERM by
> ```

Please rewrap this comment to 100 chars per line


<!-- Sent from Reviewable.io -->

2022-02-25 12:53 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 10 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-Mwbi4zn-TU2TMvS5qPZ:-Mwktzg1BCd-soF712uN:b4o10gm) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought we already had something
</blockquote></details>

I searched and did not find a appropriate one, looks like we are using numeric parameter to `DkCpuIdRetrieve` directly, do you have any suggestion?
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwkwNAR9Ne4oLyoUyOq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now it's not really a mask, just one bit and we can simplify the condition and remove the variable
</blockquote></details>

Done.
___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 41 at r4](https://reviewable.io/reviews/gramineproject/gramine/422#-MwkKwCH0zZNfQqPbN--:-Mwktwd22SL5KwB4gwl-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4fc6031c11ddbab6ea545b233f8f49601977f5f9/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please rewrap this comment to 100 chars per line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-25 14:09 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwlBgnvAaPsnYgMSTxJ:b-tg2ndq) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, dongx1x wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`!= (1 << AMX_TILEDATA)` part is not needed, just negate the left side.


<!-- Sent from Reviewable.io -->

2022-02-25 14:28 UTC, dongx1x reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: 10 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/arch/x86_64/shim_arch_prctl.c, line 53 at r3](https://reviewable.io/reviews/gramineproject/gramine/422#-MwbkJmJ1-UBw8m9pgNN:-MwlGzff1iJ1BTR-CAlP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1fcd1b45c5be524d1005cad99c910ebfd9a9c44a/LibOS/shim/src/arch/x86_64/shim_arch_prctl.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`!= (1 << AMX_TILEDATA)` part is not needed, just negate the left side.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-25 15:00 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-25 15:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-25 15:37 UTC, dimakuv commented
Jenkins, test this please

2022-02-25 16:02 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-MwlbRML9dicv-IK-nca:-MwlbRMM59vBsSXtxiyw:bbay9op) (no related file):*
Verified on my local AMX machine, the PR works.

@dongx1x Did you verify on an AMX machine with Linux 5.16, that this latest version of your PR works?

---


<!-- Sent from Reviewable.io -->

2022-02-26 17:51 UTC, dongx1x commented
Hi @dimakuv , I verified latest version of this PR with Linux 5.16, it works. But I found another issue, in Linux 5.16, the cpu features only kept `amx_tile` for AMX: https://elixir.bootlin.com/linux/v5.16/source/arch/x86/include/asm/cpufeatures.h#L302, maybe we should change  https://github.com/gramineproject/gramine/blob/master/python/graminelibos/sgx_get_token.py#L20 to align with it

2022-02-28 09:51 UTC, dimakuv submitted a review, later dismissed
@dongx1x I agree with you that `amx_tile` is a better indicator. Please change https://github.com/gramineproject/gramine/blob/master/python/graminelibos/sgx_get_token.py#L20 to align with this.

I also verified it on my AMX-patched Linux 5.12, this `amx_tile` string is also present in this patched Linux version. So we can rely on `amx_tile` on all Linux versions.

Please add a git fixup commit with this change to this PR.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422#-:-MwzjBcv8rMWpc7T4Chj:b-ldlazw)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-28 12:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-02-28 12:31 UTC, dimakuv commented
Jenkins, test this please

2022-02-28 13:48 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mx-ZfQa2Zk-KR3C9k0k:-Mx-ZfQa2Zk-KR3C9k0l:bs2gkxr) (no related file):*
@dongx1x Please do not force push / rebase in the middle of review. You can read more about our contributing guidelines here: https://gramine.readthedocs.io/en/latest/devel/contributing.html

---


<!-- Sent from Reviewable.io -->

2022-03-01 08:38 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mx-ZfQa2Zk-KR3C9k0k:-Mx3_dsG6MkN-iIItbet:bkta4zw) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dongx1x Please do not force push / rebase in the middle of review. You can read more about our contributing guidelines here: https://gramine.readthedocs.io/en/latest/devel/contributing.html
</blockquote></details>

@dongx1x Please also *never* use `git merge`.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/422#-Mx3cG-d5iocnGGnNxVA:-Mx3cG-e3QULqk9NMxcM:b-jmnbqe) (no related file):*
I rebased to the final version and verified manually that this PR works on patched Linux 5.12. Everything looks good, ready for merge. @dongx1x Please don't touch this PR anymore, we'll merge it ourselves.

---


<!-- Sent from Reviewable.io -->

2022-03-01 08:39 UTC, dimakuv commented
Jenkins, test this please

2022-03-01 08:43 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/422)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-01 09:13 UTC, merged