[Pal,common,CI-Examples] Update mbedTLS from version 2.26.0 to 3.1.0
gramineproject/gramine pull request #426
Opened 2022-02-24 06:49 UTC by kailun-qin

## Description of the changes 

## How to test this PR?

2022-02-24 09:22 UTC, dimakuv requested changes
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 1 of 16 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf1PoB98-yuDaDgbtE:-Mwf1PoB98-yuDaDgbtF:b9ih1dl) (no related file):*
Awesome work! Thanks.

I left a couple quick comments, I'll do a proper review later.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf1Cp_8lIY83vOKTlK:-Mwf1Cp_8lIY83vOKTlL:bivruj8) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/CI-Examples/ra-tls-mbedtls/src/certs.h#L28)):*
> ```objc
> 
> /* TEST_SRV_CRT_RSA_SHA256_PEM */
> const char mbedtls_test_srv_crt[] =                                        \
> ```

Where did you take these values from?

mbedTLS doesn't provide the convenience file `mbedtls/certs.h` (with these certs hard-coded) anymore?
___
*[common/src/crypto/config.h, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf0jQs1E31_ngWXJc_:-Mwf0jQs1E31_ngWXJca:bcnerdc) ([raw file](https://github.com/gramineproject/gramine/blob/90da396067e2530ade39e2cc1eb4273137271ed0/common/src/crypto/config.h#L1)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

I'm confused. This file was not used at all?

Also @pwmarcz 
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf0s017SrDOChcZfuh:-Mwf0s017SrDOChcZfui:b1pov9d) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/gramine.patch#L5)):*
> ```Diff
> 
> diff --git a/library/ssl_tls.c b/library/ssl_tls.c
> index d868e4965..5c58def39 100644
> ```

Sorry but could you re-generate this patch with `--full-index`? We always use complete hashes instead of shortened versions, for future-proof.
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf15Dn9o8jRa2jdpEF:-Mwf15Dn9o8jRa2jdpEG:b67f07p) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L38)):*
> ```objc
> #define MBEDTLS_PLATFORM_C
> #define MBEDTLS_RSA_C
> #define MBEDTLS_SHA224_C
> ```

Could you give some context why you added this?
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h, line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf17XT1PObLm0tTdTt:-Mwf17XT1PObLm0tTdTu:b67f07p) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L56)):*
> ```objc
> int snprintf(char* buf, size_t buf_size, const char* fmt, ...);
> 
> #define MBEDTLS_PLATFORM_MEMORY
> ```

Could you give some context why you added this?


<!-- Sent from Reviewable.io -->

2022-02-24 13:41 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 1 of 16 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[common/src/crypto/config.h, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf0jQs1E31_ngWXJc_:-Mwfw7O_9CQg4xaklHV4:b-l8au0n) ([raw file](https://github.com/gramineproject/gramine/blob/90da396067e2530ade39e2cc1eb4273137271ed0/common/src/crypto/config.h#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm confused. This file was not used at all?

Also @pwmarcz 
</blockquote></details>

Oh. I haven't seen it before. I think it was used when we built using Makefiles, and we lost track of it during the Meson migration. And that's how the "non-PAL" mbedtls configuration started using the default mbedtls config.

Anyway, the current situation is:
* there are two versions of this library: command-line tools and Gramine, but they're confusingly named `-gramine` and `-pal`
* the `-gramine` version uses standard config with one extra flag
* the `-pal` version specifies has a completely custom config

So it'd be nice to clean up.


<!-- Sent from Reviewable.io -->

2022-02-25 10:06 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 1 of 16 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf1Cp_8lIY83vOKTlK:-MwkDdbL-yKkuuRfwfVA:b-9c0p4f) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/CI-Examples/ra-tls-mbedtls/src/certs.h#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where did you take these values from?

mbedTLS doesn't provide the convenience file `mbedtls/certs.h` (with these certs hard-coded) anymore?
</blockquote></details>

According to [Mbed TLS 3.0.0 release notes](https://github.com/ARMmbed/mbedtls/releases):
`Remove certs module from the API.
Transfer keys and certificates embedded in the library to the test
component. This contributes to minimizing library API and discourages
users from using unsafe keys in production.`
___
*[common/src/crypto/config.h, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf0jQs1E31_ngWXJc_:-MwkE0YD4nF471mDu0ED:bx86iue) ([raw file](https://github.com/gramineproject/gramine/blob/90da396067e2530ade39e2cc1eb4273137271ed0/common/src/crypto/config.h#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh. I haven't seen it before. I think it was used when we built using Makefiles, and we lost track of it during the Meson migration. And that's how the "non-PAL" mbedtls configuration started using the default mbedtls config.

Anyway, the current situation is:
* there are two versions of this library: command-line tools and Gramine, but they're confusingly named `-gramine` and `-pal`
* the `-gramine` version uses standard config with one extra flag
* the `-pal` version specifies has a completely custom config

So it'd be nice to clean up.
</blockquote></details>

Thanks for checking this!
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf0s017SrDOChcZfuh:-MwkE3h6EMu8ciYnWRGH:b-1eh3wi) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/gramine.patch#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry but could you re-generate this patch with `--full-index`? We always use complete hashes instead of shortened versions, for future-proof.
</blockquote></details>

Sure, done.
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h, line 38 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf15Dn9o8jRa2jdpEF:-MwkEMvX6kF0SXzU_XzG:b-gp4erw) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you give some context why you added this?
</blockquote></details>

It is a prerequisite in 3.1.0: https://github.com/ARMmbed/mbedtls/blob/v3.1.0/include/mbedtls/check_config.h#L593, as in 2.26.0 there's no SHA224.
___
*[subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h, line 56 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf17XT1PObLm0tTdTt:-MwkEkE_AC5EZcdF0BKp:bxfs0co) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you give some context why you added this?
</blockquote></details>

It is required for CALLOC, FREE etc., pls kindly see https://github.com/ARMmbed/mbedtls/blob/v3.1.0/include/mbedtls/check_config.h#L405 for details.


<!-- Sent from Reviewable.io -->

2022-02-25 10:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 1 of 16 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 103 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkLV8A7eNgOCrocp0m:-MwkLV8A7eNgOCrocp0n:bxfccuw) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/subprojects/packagefiles/mbedtls/gramine.patch#L103)):*
> ```Diff
> diff --git a/library/ssl_tls.c b/library/ssl_tls.c
> index d868e496507b035b7f40ff4ecdc5d9109be93899..5c58def39b1c12404148b6b6c0080273e78fc928 100644
> --- a/library/ssl_tls.c
> ```

`library/Makefile` diff first, then`library/ssl_tls.c` diff seems to be the right order auto-generated by `git diff`.
I was manually changing the order last time (1st commit) for easier review.



_Code quote:_
```Diff
library/Makefile
```


<!-- Sent from Reviewable.io -->

2022-02-25 10:46 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 1 of 16 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwkS7_O6sz5c1LQOxty:bacpd4c) (no related file):*
Is there a specific reason why we want to upgrade mbedtls? 3.x is not packaged for any significant distro (https://repology.org/project/mbedtls/versions), EPEL, bookworm (Debian testing), jammy (to be Ubuntu 22.04LTS) all have 2.28. If there isn't any compelling reason (and the reason was not given in patch description or at least PR), I'd suggest to wait for distros to package, then drop `_gramine` flavour altogether and instead rely on distro-packaged `.so` (AFAIU we need our version for CMAC for RA-TLS, which is disabled by default in 2.x, but enabled in 3.x). Optimally we should only keep our internal `_pal` flavour.

---


<!-- Sent from Reviewable.io -->

2022-02-25 11:10 UTC, dimakuv requested changes
> Reviewed 14 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> Dismissed @kailun-qin from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwkVG1w67NCd72_nfKM:b-hawcdk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is there a specific reason why we want to upgrade mbedtls? 3.x is not packaged for any significant distro (https://repology.org/project/mbedtls/versions), EPEL, bookworm (Debian testing), jammy (to be Ubuntu 22.04LTS) all have 2.28. If there isn't any compelling reason (and the reason was not given in patch description or at least PR), I'd suggest to wait for distros to package, then drop `_gramine` flavour altogether and instead rely on distro-packaged `.so` (AFAIU we need our version for CMAC for RA-TLS, which is disabled by default in 2.x, but enabled in 3.x). Optimally we should only keep our internal `_pal` flavour.
</blockquote></details>

I would prefer to update mbedTLS periodically to the latest version. Gramine is a security-first project, and shipping it with an older version of a crypto library doesn't sound right.

---
___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkXjS36gffMHM573Nl:-MwkXjS36gffMHM573Nm:bttr22u) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/common/src/crypto/adapters/mbedtls_adapter.c#L25)):*
> ```C
> int _DkRandomBitsRead(void* buffer, size_t size);
> 
> /* This is declared in mbedtls library/entropy_poll.h, but that can't be included here. */
> ```

Why cannot be included?
___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkXlOx5qT8ouutO-1g:-MwkXlOx5qT8ouutO-1h:b-kts921) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/common/src/crypto/adapters/mbedtls_adapter.c#L27)):*
> ```C
> /* This is declared in mbedtls library/entropy_poll.h, but that can't be included here. */
> int mbedtls_hardware_poll(void *data,
>                           unsigned char *output, size_t len, size_t *olen);
> ```

This is not according to our coding style. Please:
- align `*` to the left
- aling to 100-char limit per line (so, it will be all in one line)
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c, line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkYXoa6THGth3giwW-:-MwkYXoa6THGth3giwW0:b-el3833) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L24)):*
> ```C
> #include <string.h>
> 
> #include "mbedtls/mbedtls_config.h"
> ```

Shouldn't this be `#include "mbedtls/build_info.h"`?


<!-- Sent from Reviewable.io -->

2022-02-25 11:48 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwkfR6Z5Q4smBCEARMH:b-71ppjx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to update mbedTLS periodically to the latest version. Gramine is a security-first project, and shipping it with an older version of a crypto library doesn't sound right.
</blockquote></details>

Unless there are security fixes there, I don't think we need to upgrade to the latest version just for the sake of latest version (and the patch description didn't mention any problems with the current version). Especially for `_gramine` user-facing flavour, it's not our responsibility to package our dependency. If the user has a problem with distro-packaged binaries, s/he can either build a package from sources, or bug the distro maintainers. We do it for convenience, because we need a certain non-default configuration, but otherwise we're not in business of packaging a distro.

---


<!-- Sent from Reviewable.io -->

2022-02-25 12:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwklYW_DAzWVWBxpnIt:b-iczg4g) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Unless there are security fixes there, I don't think we need to upgrade to the latest version just for the sake of latest version (and the patch description didn't mention any problems with the current version). Especially for `_gramine` user-facing flavour, it's not our responsibility to package our dependency. If the user has a problem with distro-packaged binaries, s/he can either build a package from sources, or bug the distro maintainers. We do it for convenience, because we need a certain non-default configuration, but otherwise we're not in business of packaging a distro.
</blockquote></details>

Of course there were security fixes in-between 2.26 and 3.1: https://github.com/ARMmbed/mbedtls/releases

I'm not sure I understand your point. Do you mean that Gramine shouldn't periodically update its dependencies like mbedTLS, Glibc, Musl, just because things seem to work? Every new release comes with bug fixes and security fixes.

Or do you mean that you would want to see two things:
- For our CI-Examples, we shouldn't download and patch mbedTLS (as we do now, see the Makefile) -- but `MBEDTLS_CMAC_C` is not yet supported on e.g. the default mbedTLS on Ubuntu 18.04, so what else can we do
- For Gramine itself, we should download and patch mbedTLS anyway, and this is clearly a good idea to upgrade to the latest version

In both these cases, I see no reason to *not* update the version of mbedTLS.

---


<!-- Sent from Reviewable.io -->

2022-02-25 12:47 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwknIcFAucBjX53ED6H:b8r96v3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Of course there were security fixes in-between 2.26 and 3.1: https://github.com/ARMmbed/mbedtls/releases

I'm not sure I understand your point. Do you mean that Gramine shouldn't periodically update its dependencies like mbedTLS, Glibc, Musl, just because things seem to work? Every new release comes with bug fixes and security fixes.

Or do you mean that you would want to see two things:
- For our CI-Examples, we shouldn't download and patch mbedTLS (as we do now, see the Makefile) -- but `MBEDTLS_CMAC_C` is not yet supported on e.g. the default mbedTLS on Ubuntu 18.04, so what else can we do
- For Gramine itself, we should download and patch mbedTLS anyway, and this is clearly a good idea to upgrade to the latest version

In both these cases, I see no reason to *not* update the version of mbedTLS.
</blockquote></details>

I think we should aim to eventually remove `_gramine` flavour once CMAC becomes available in distro packaged versions. For that, we'll need distro-packaged version to be no older than ours at the point of removal, therefore we need to stop fast-forwarding our version, otherwise distros will never catch up with us.

You're almost right that every release comes with bugfixes: the catch is that every release *in a branch* does this. This is an important distinction. There's no obvious point in updating to latest version as sorted by just the numbers, because mbedtls doesn't have linear version history. Unless demonstrated by e.g. new features we intend to use, there's no reason to update to 3.1 over 2.28.

In this very case, if the security is the only reason, it would be better to update to 2.28.0, which, judging by release notes (https://github.com/ARMmbed/mbedtls/releases/tag/v2.28.0) also contains the security fix in 3.1.0, and is a LTS branch, promised to be fixed until the end of 2024 (unlike 3.1, which does not carry this promise: https://github.com/ARMmbed/mbedtls/releases/tag/v3.1.0). After that, we can restrict ourselves to update only within 2.28, which should be possible for about 3 years with minimal effor. I hope that during those 3 years distros will package some 3.x version and then we'll be able to switch to that.

Until then, we're condemned to distribute `_gramine` flavour one way or another, and yeah, 18.04 goes out of the window in 2 months, but 20.04 will still need this workaround.

The internal version for differs only in that we need to patch it anyway, so we can't drop it entirely from our buildsystem. But the rationale about gaining nothing by chasing 3.1 still stands: we can possibly avoid some effort in porting the patches to newer versions by sticking to 2.28 for 3 years, unless there would be some considerable gain from some newer version (like if they upstreamed the patch for example).

---


<!-- Sent from Reviewable.io -->

2022-02-25 14:09 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mwl9cDgAV1Y-4XfmVwx:b-do3dmo) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think we should aim to eventually remove `_gramine` flavour once CMAC becomes available in distro packaged versions. For that, we'll need distro-packaged version to be no older than ours at the point of removal, therefore we need to stop fast-forwarding our version, otherwise distros will never catch up with us.

You're almost right that every release comes with bugfixes: the catch is that every release *in a branch* does this. This is an important distinction. There's no obvious point in updating to latest version as sorted by just the numbers, because mbedtls doesn't have linear version history. Unless demonstrated by e.g. new features we intend to use, there's no reason to update to 3.1 over 2.28.

In this very case, if the security is the only reason, it would be better to update to 2.28.0, which, judging by release notes (https://github.com/ARMmbed/mbedtls/releases/tag/v2.28.0) also contains the security fix in 3.1.0, and is a LTS branch, promised to be fixed until the end of 2024 (unlike 3.1, which does not carry this promise: https://github.com/ARMmbed/mbedtls/releases/tag/v3.1.0). After that, we can restrict ourselves to update only within 2.28, which should be possible for about 3 years with minimal effor. I hope that during those 3 years distros will package some 3.x version and then we'll be able to switch to that.

Until then, we're condemned to distribute `_gramine` flavour one way or another, and yeah, 18.04 goes out of the window in 2 months, but 20.04 will still need this workaround.

The internal version for differs only in that we need to patch it anyway, so we can't drop it entirely from our buildsystem. But the rationale about gaining nothing by chasing 3.1 still stands: we can possibly avoid some effort in porting the patches to newer versions by sticking to 2.28 for 3 years, unless there would be some considerable gain from some newer version (like if they upstreamed the patch for example).
</blockquote></details>

So, it looks like:

* We should use a supported version, which is currently either 2.28 or 3.1
* In order to switch to a distro-packaged version in the future, we will need to upgrade to some 3.x version anyway
* 2.28 has long term support

So we either 
* switch to 3.1, and keep updating to 3.1.1, 3.2, 3.3... as bug fixes and new versions come out, or
* switch to 2.28, and keep updating to 2.28.1, 2.28.2... as bug fixes come out, then update to 3.x.

Using an LTS version sounds easier right now, but could make the future upgrade more painful if there are many incompatibilities.

---


<!-- Sent from Reviewable.io -->

2022-02-26 01:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 14 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwncrXFB_AG6texol98:b-dzdihg) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

So, it looks like:

* We should use a supported version, which is currently either 2.28 or 3.1
* In order to switch to a distro-packaged version in the future, we will need to upgrade to some 3.x version anyway
* 2.28 has long term support

So we either 
* switch to 3.1, and keep updating to 3.1.1, 3.2, 3.3... as bug fixes and new versions come out, or
* switch to 2.28, and keep updating to 2.28.1, 2.28.2... as bug fixes come out, then update to 3.x.

Using an LTS version sounds easier right now, but could make the future upgrade more painful if there are many incompatibilities.
</blockquote></details>

I agree w/ @pwmarcz. The summary is clear.

Personally I don't have a strong opinion on 3.x v.s. 2.28. But from Gramines's pespective (since if consider the other distros/projects, some have updated to 3.x - e.g., Zephyr, some may not), I see no strong reason to not update.

Feature wise, TLS1.3 (which is a long-time demanded feature, also a missing piece in comparison w/ openssl, wolfssl etc.) can probably be a good reason, as an MVP has already been included in 3.1.0 (https://github.com/ARMmbed/mbedtls/blob/v3.1.0/docs/architecture/tls13-support.md) so it'll likely be supported in 3.x beyond.

---
___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkXjS36gffMHM573Nl:-Mwnb9AU4j1dKDFtVVfK:b-1ss3ua) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/common/src/crypto/adapters/mbedtls_adapter.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why cannot be included?
</blockquote></details>

Indeed, we don't actually need the declaration here.
Note that `mbedtls/entropy_poll.h`is not supplied by mbedTLS neither and define`MBEDTLS_ENTROPY_HARDWARE_ALT` should be fine (see https://github.com/ARMmbed/mbedtls/blob/v3.1.0/include/mbedtls/mbedtls_config.h#L459).
___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 27 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkXlOx5qT8ouutO-1g:-MwnU7lZ2YvosHz9165B:bss4a2b) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/common/src/crypto/adapters/mbedtls_adapter.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not according to our coding style. Please:
- align `*` to the left
- aling to 100-char limit per line (so, it will be all in one line)
</blockquote></details>

Removed.



_Code quote:_
```C
mbedtls_hardware_poll
```
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c, line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkYXoa6THGth3giwW-:-MwnUqsD4f_WiQ7ge_QH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/04b3f55b46984fff138a11fa439bc72020d3dc83/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be `#include "mbedtls/build_info.h"`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-28 10:34 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwzrzQ601Xl4zwsNcBZ:b-mej6lo) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I agree w/ @pwmarcz. The summary is clear.

Personally I don't have a strong opinion on 3.x v.s. 2.28. But from Gramines's pespective (since if consider the other distros/projects, some have updated to 3.x - e.g., Zephyr, some may not), I see no strong reason to not update.

Feature wise, TLS1.3 (which is a long-time demanded feature, also a missing piece in comparison w/ openssl, wolfssl etc.) can probably be a good reason, as an MVP has already been included in 3.1.0 (https://github.com/ARMmbed/mbedtls/blob/v3.1.0/docs/architecture/tls13-support.md) so it'll likely be supported in 3.x beyond.

</blockquote></details>

I agree with @kailun-qin that moving to 3.x is a major win: iiuc, TLS 1.3 will *not* be available in mbedTLS 2.28 (the documentation on TLS 1.3 support is really sparse, and for some reason mbedTLS developers are very secretive about this, but this was my impression after reading the link above).

---
___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 266 at r3](https://reviewable.io/reviews/gramineproject/gramine/426#-MwzsxTlE98RPYbq8XF1:-MwzsxTlE98RPYbq8XF2:bly2dxh) ([raw file](https://github.com/gramineproject/gramine/blob/d1b8c22ef5e25fa608692f9d93fd27af0b9dcea7/common/src/crypto/adapters/mbedtls_adapter.c#L266)):*
> ```C
> }
> 
> int mbedtls_hardware_poll(void* data, unsigned char* output, size_t len, size_t* olen) {
> ```

Can you please add a comment here:
```
/* mbedTLS library will use this implementation of a hardware entropy collector, see
 * https://github.com/ARMmbed/mbedtls/blob/v3.1.0/include/mbedtls/mbedtls_config.h#L459 */
```


<!-- Sent from Reviewable.io -->

2022-03-01 13:57 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[common/src/crypto/adapters/mbedtls_adapter.c, line 266 at r3](https://reviewable.io/reviews/gramineproject/gramine/426#-MwzsxTlE98RPYbq8XF1:-Mx4lNhC1D4s2UpLklHA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d1b8c22ef5e25fa608692f9d93fd27af0b9dcea7/common/src/crypto/adapters/mbedtls_adapter.c#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you please add a comment here:
```
/* mbedTLS library will use this implementation of a hardware entropy collector, see
 * https://github.com/ARMmbed/mbedtls/blob/v3.1.0/include/mbedtls/mbedtls_config.h#L459 */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 08:13 UTC, dimakuv commented
Jenkins, test this please

2022-03-02 10:27 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-Mx8hx28B6s940WWyt1Y:-Mx99hswBfrnHiHBC1M4:byx3swr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Our Jenkins on Gramine-SGX build fails like this:
```
FAILED: Pal/src/host/Linux-SGX/libpal.so.p/db_memory.c.o 
cc -IPal/src/host/Linux-SGX/libpal.so.p -IPal/src/host/Linux-SGX -I../Pal/src/host/Linux-SGX -IPal/include -I../Pal/include -I../Pal/include/pal -I../Pal/include/arch/x86_64 -Icommon/include -I../common/include -I../common/include/arch/x86_64 -I../Pal/include/arch/x86_64/Linux -I../Pal/include/host/Linux-common -IPal/src/host/Linux-SGX/protected-files -I../Pal/src/host/Linux-SGX/protected-files -Isubprojects/uthash-2.1.0/src -I../subprojects/uthash-2.1.0/src -Isubprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 -I../subprojects/mbedtls-mbedtls-3.1.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -fPIC '-DMBEDTLS_CONFIG_FILE="mbedtls/config-pal.h"' -DCRYPTO_USE_MBEDTLS -DIN_PAL -fno-builtin -DHOST_TYPE=Linux-SGX -Wno-gnu-alignof-expression -fno-stack-protector -DIN_ENCLAVE -MD -MQ Pal/src/host/Linux-SGX/libpal.so.p/db_memory.c.o -MF Pal/src/host/Linux-SGX/libpal.so.p/db_memory.c.o.d -o Pal/src/host/Linux-SGX/libpal.so.p/db_memory.c.o -c ../Pal/src/host/Linux-SGX/db_memory.c
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:0,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
                 from ../common/include/api.h:10,
                 from ../Pal/src/host/Linux-SGX/db_memory.c:8:
../common/include/api_fortified.h:54:45: error: expected declaration specifiers or ‘...’ before numeric constant
     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
                                             ^
../subprojects/mbedtls-mbedtls-3.1.0/include/mbedtls/config-pal.h:54:5: note: in expansion of macro ‘snprintf’
 int snprintf(char* buf, size_t buf_size, const char* fmt, ...);
     ^~~~~~~~
In file included from ../common/include/api.h:447:0,
                 from ../Pal/src/host/Linux-SGX/db_memory.c:8:
../common/include/api_fortified.h:39:24: error: expected declaration specifiers or ‘...’ before ‘__builtin_object_size’
 #define __api_bos(ptr) __builtin_object_size(ptr, __USE_FORTIFY_LEVEL > 1)
                        ^
../common/include/api_fortified.h:54:70: note: in expansion of macro ‘__api_bos’
     __builtin___snprintf_chk(buf, buf_size, __USE_FORTIFY_LEVEL - 1, __api_bos(buf), fmt)
                                                                      ^~~~~~~~~
../subprojects/mbedtls-mbedtls-3.1.0/include/mbedtls/config-pal.h:54:5: note: in expansion of macro ‘snprintf’
 int snprintf(char* buf, size_t buf_size, const char* fmt, ...);
     ^~~~~~~~
cc1: error: unrecognized command line option ‘-Wno-gnu-alignof-expression’ [-Werror]
cc1: all warnings being treated as errors
```

Please analyze and fix.
</blockquote></details>

Not able to reproduce locally... Pls kindly see if the fix makes sense.

---


<!-- Sent from Reviewable.io -->

2022-03-02 14:52 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 16 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-Mx8hx28B6s940WWyt1Y:-MxA1DrBCHvNW5ezgYzj:b-nbqepe) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not able to reproduce locally... Pls kindly see if the fix makes sense.
</blockquote></details>

This still fails for me. To reproduce, build Gramine in release mode (`--buildtype=release`). The problem is that these declarations collide with `api_fortified.h` which redefines a number of functions as macros. Unfortunately, it happens only when `_FORTIFY_SOURCE` is enabled, and gcc doesn't enable it at optimization level 0 (our debug builds).

One workaround would be:

```diff
+/* Prevent conflict with `api_fortified.h` which might redefine `snprintf` as macro */
+#ifndef API_H
 void* calloc(size_t num, size_t size);
 void free(void*);
 int snprintf(char* buf, size_t buf_size, const char* fmt, ...)
     __attribute__((format(printf, 3, 4)));
+#endif
```

A more straightforward, but annoying, solution would be to define your own `mbedtls_snprintf()` and call `snprintf()` inside it.

Also, there is one more warning:

```
../common/src/crypto/adapters/mbedtls_adapter.c:268:5: error: no previous prototype for ‘mbedtls_hardware_poll’ [-Werror=missing-prototypes]
  268 | int mbedtls_hardware_poll(void* data, unsigned char* output, size_t len, size_t* olen) {
      |     ^~~~~~~~~~~~~~~~~~~~~
```

This will fail CI, because it compiles code with `--werror`.

Please also enable `--werror` when compiling: we merged a change recently that [disables it by default](https://github.com/gramineproject/gramine/pull/409) in the source distribution, but we ask contributors to enable it.

---


<!-- Sent from Reviewable.io -->

2022-03-03 00:40 UTC, mkow requested changes
> Reviewed 1 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxC8vn-D24mVuKOe7y5:b-5u6v8i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @kailun-qin that moving to 3.x is a major win: iiuc, TLS 1.3 will *not* be available in mbedTLS 2.28 (the documentation on TLS 1.3 support is really sparse, and for some reason mbedTLS developers are very secretive about this, but this was my impression after reading the link above).
</blockquote></details>

+1 to using the newest available release.

This is probably controversial, but I don't really believe in backporting security fixes to old releases, this is more like an illusion for vendors which really wanted to have stable versions, so they got them.
A lot of security fixes aren't backported, just for the mere reason that developers usually can't tell if a bug has security implications or not, and at the same time, they won't just backport all bugfixes. Just to give some examples: both Windows and Linux have this problem and you can find security bugs in their LTSes by diffing what changes in the most recent version but wasn't changed in the LTS.
This is also one of the reasons why I'm against supporting any Gramine version other than the most recent release.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxCCJud2TCCS9OnA3PU:bc97v9c) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
> ```objc
>     "4AgahOxIxXx2gxJnq3yfkJfIjwf0s2DyP0kY2y6Ua1OeomPeY9mrIS4tCuDQ6LrE\r\n" \
>     "TB6l9VGoxJL4fyHnZb8L5gGvnB1bbD8cL6YPaDiOhcRseC9vBiEuVg==\r\n"         \
>     "-----END RSA PRIVATE KEY-----\r\n";
> ```

Why have you added these? Previously we didn't hardcode any private keys here, and I'm feeling anxious about having such things, as people may accidentally ship them to production - better to generate test keys during build instead of hardcoding in the source.


<!-- Sent from Reviewable.io -->

2022-03-03 00:43 UTC, mkow commented
Jenkins, retest this please

2022-03-03 01:37 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxCPCqP77U_R8g777OA:b-c073yi) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you added these? Previously we didn't hardcode any private keys here, and I'm feeling anxious about having such things, as people may accidentally ship them to production - better to generate test keys during build instead of hardcoding in the source.
</blockquote></details>

Previously we were leveraging test keys in mbedtls: https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/src/server.c#L36, which are also hardcoded and are exactly the same here. Now they are moving into mbedtls tests https://github.com/ARMmbed/mbedtls/blob/v3.1.0/tests/include/test/certs.h so that we cannot easily reference them any more.


<!-- Sent from Reviewable.io -->

2022-03-03 01:41 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 15 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxCQlorDBeu4E9WnpeU:b-vtytev) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Previously we were leveraging test keys in mbedtls: https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/src/server.c#L36, which are also hardcoded and are exactly the same here. Now they are moving into mbedtls tests https://github.com/ARMmbed/mbedtls/blob/v3.1.0/tests/include/test/certs.h so that we cannot easily reference them any more.
</blockquote></details>

Also, it seems that we did something similar (though hardcoded in files) for ra-tls-secret-prov. I suggest we address this separately for both if needed.


<!-- Sent from Reviewable.io -->

2022-03-03 09:05 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/426#-Mwf1Cp_8lIY83vOKTlK:-MxE-sbT-c55UXq-nfVp:b-5ww664) ([raw file](https://github.com/gramineproject/gramine/blob/c742f632146a2de5b443cad18cfc4aea5de73146/CI-Examples/ra-tls-mbedtls/src/certs.h#L28)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

According to [Mbed TLS 3.0.0 release notes](https://github.com/ARMmbed/mbedtls/releases):
`Remove certs module from the API.
Transfer keys and certificates embedded in the library to the test
component. This contributes to minimizing library API and discourages
users from using unsafe keys in production.`
</blockquote></details>

@mkow Please also see this resolved comment.
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxE-yyRCtudbVq6Mtbe:b-rjr195) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Also, it seems that we did something similar (though hardcoded in files) for ra-tls-secret-prov. I suggest we address this separately for both if needed.
</blockquote></details>

@mkow These are the same keys as used previously. Note that we have a HUGE warning when we detect these keys: 
- https://github.com/gramineproject/gramine/blob/76d8285ce71c6af33f6e9a288c90517a06e88973/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov.h#L6
- https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L182


<!-- Sent from Reviewable.io -->

2022-03-03 14:55 UTC, mkow requested changes
> Reviewed 11 of 16 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxFD8zyDs4fl86PeUj0:b-m0k03g) (no related file):*
I tried instructions from the README.md and it seems that the native case stopped to work: (yes, I did start the server, but maybe I missed something else?)
```
> ./client native
[ using normal TLS flows ]

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x7100

Last error was: -28928 - SSL - Bad input parameters to function
```

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFE65V5efqn5q_VI-e:-MxFE65V5efqn5q_VI-f:b-54g62l) (no related file):*
The SGX version seems to also be broken for me:
```
> gramine-sgx ./server epid
<snip>
  . Seeding the random number generator... ok

  . Creating the RA-TLS server cert and key... failed
  !  ra_tls_create_key_and_crt_der returned -16640

Last error was: -16640 - RSA - Input data contains invalid padding and is rejected
```

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF-0da0Ymqcn6vb8-L:-MxF-0db8UaTzo7UUNzR:b-hvn4jz) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L9)):*
> ```objc
>  *  Copyright (C) 2006-2015, ARM Limited, All Rights Reserved
>  *                2022, Intel Corporation
>  *  SPDX-License-Identifier: Apache-2.0
> ```

If we use SPDX then we don't need that boilerplate below. Also, I think SPDX must be the first line in the file, but please verify with SPDX specs.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c, line 183 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9PeX2JA0HJ7ZkZmm:-MxF9PeX2JA0HJ7ZkZmn:b-l5agf) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L183)):*
> ```C
>         printf("%s", SECRET_PROVISION_WARNING_TEST_CERTS);
> 
>     ret = mbedtls_pk_parse_keyfile(&srvkey, key_path, /*password=*/NULL, mbedtls_ctr_drbg_random, &ctr_drbg);
> ```

Please wrap this line
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9pSo6En01vJKaKy3:-MxF9pSo6En01vJKaKy4:b3oehtg) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/subprojects/packagefiles/mbedtls/gramine.patch#L4)):*
> ```Diff
> # progress via issue https://github.com/ARMmbed/mbedtls/issues/3141.
> 
> diff --git a/library/Makefile b/library/Makefile
> ```

Could you move this hunk back to where it was before in this diff file? Quite hard to review and check what this commit changes here.


<!-- Sent from Reviewable.io -->

2022-03-03 15:42 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxFQmbtA8wisx260Dz7:briog1n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tried instructions from the README.md and it seems that the native case stopped to work: (yes, I did start the server, but maybe I missed something else?)
```
> ./client native
[ using normal TLS flows ]

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x7100

Last error was: -28928 - SSL - Bad input parameters to function
```
</blockquote></details>

I tested native and dcap locally and it seems to work fine for me.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF-0da0Ymqcn6vb8-L:-MxFQt6TDN4ncQDBo75V:bb8at4x) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If we use SPDX then we don't need that boilerplate below. Also, I think SPDX must be the first line in the file, but please verify with SPDX specs.
</blockquote></details>

There are similar issues in other files around, should we address them all together in a separate one?
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c, line 183 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9PeX2JA0HJ7ZkZmm:-MxFRcAA4_NBHYoitUQD:b807pu8) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L183)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap this line
</blockquote></details>

Sure, will update in the next version.
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9pSo6En01vJKaKy3:-MxFR7B06gDchZuGQWti:b-vwawxi) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/subprojects/packagefiles/mbedtls/gramine.patch#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you move this hunk back to where it was before in this diff file? Quite hard to review and check what this commit changes here.
</blockquote></details>

Yep I can certainly do that. But it seems that `Makefile` before `ssl_tls.c` is the default order for git. If we move this manually which means we may need to do this again for the following updates.


<!-- Sent from Reviewable.io -->

2022-03-03 15:47 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxFS_eaBQBcWX6JZXXV:b3z5u07) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I tested native and dcap locally and it seems to work fine for me.
</blockquote></details>

Question: doesn't our CI cover the examples?

---


<!-- Sent from Reviewable.io -->

2022-03-03 18:18 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxFzZYN5qCbK2BSAK63:b-3ng34z) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Question: doesn't our CI cover the examples?
</blockquote></details>

Yes, but only SGX+epid. See https://github.com/gramineproject/gramine/blob/29f127542a4d81a8b461f05a4b36344d89bed3fa/.ci/lib/stage-test-sgx.jenkinsfile#L86-L98.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF-0da0Ymqcn6vb8-L:-MxFzo2G41jpOaCeG8Rt:b-l4a1ai) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

There are similar issues in other files around, should we address them all together in a separate one?
</blockquote></details>

Please do. But this specific file was created in this PR, so please fix this one here.
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9pSo6En01vJKaKy3:-MxG--690EF2rU5pdsUm:bsy8xlz) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/subprojects/packagefiles/mbedtls/gramine.patch#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Yep I can certainly do that. But it seems that `Makefile` before `ssl_tls.c` is the default order for git. If we move this manually which means we may need to do this again for the following updates.
</blockquote></details>

I'm not sure if there's any defined order, it's probably just directory iteration order? (which is not defined on Linux I think)


<!-- Sent from Reviewable.io -->

2022-03-04 01:13 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxHMKWZ3BPcU1jH11ua:bqdrla7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, but only SGX+epid. See https://github.com/gramineproject/gramine/blob/29f127542a4d81a8b461f05a4b36344d89bed3fa/.ci/lib/stage-test-sgx.jenkinsfile#L86-L98.
</blockquote></details>

Got it, thanks. Then I think we are fine for having covered all three cases: native, epid and dcap.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF-0da0Ymqcn6vb8-L:-MxHPnUm0iR_jT0-gIIT:b-sssxa) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please do. But this specific file was created in this PR, so please fix this one here.
</blockquote></details>

Done.

According to SPDX specs, the boilerplate below is not required w/ short identifiers and SPDX is not required to be the first line in the file. Pls kindly see https://spdx.dev/wp-content/uploads/sites/41/2020/04/using_spdx_license_list_short_identifiers.pdf for details.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c, line 183 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9PeX2JA0HJ7ZkZmm:-MxHSPdv96iDoVJQ3J5x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L183)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sure, will update in the next version.
</blockquote></details>

Done.
___
*[subprojects/packagefiles/mbedtls/gramine.patch, line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF9pSo6En01vJKaKy3:-MxHSS-b30bQm6x7nuxk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/subprojects/packagefiles/mbedtls/gramine.patch#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure if there's any defined order, it's probably just directory iteration order? (which is not defined on Linux I think)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 01:22 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 14 of 17 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 9 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxF-0da0Ymqcn6vb8-L:-MxHVw0-3pcOblcCB5XF:bm8pt8g) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.

According to SPDX specs, the boilerplate below is not required w/ short identifiers and SPDX is not required to be the first line in the file. Pls kindly see https://spdx.dev/wp-content/uploads/sites/41/2020/04/using_spdx_license_list_short_identifiers.pdf for details.
</blockquote></details>

Anyway, though not required, I tried to align the format w/ the other files in Gramine.


<!-- Sent from Reviewable.io -->

2022-03-04 08:37 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxJ3TNt4Lxg5b3fwyk3:bpfh3xg) (no related file):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Got it, thanks. Then I think we are fine for having covered all three cases: native, epid and dcap.
</blockquote></details>

@mkow I just tested this PR (I git-cloned to a separate dir, so I built everything from clean slate completely). All native + DCAP flows work fine for me. Maybe you had some dirty state left over, and your binaries got tangled with old mbedTLS code and new mbedTLS code?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFE65V5efqn5q_VI-e:-MxJ3is7EpqbBGQt_sbR:b-ass2vc) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The SGX version seems to also be broken for me:
```
> gramine-sgx ./server epid
<snip>
  . Seeding the random number generator... ok

  . Creating the RA-TLS server cert and key... failed
  !  ra_tls_create_key_and_crt_der returned -16640

Last error was: -16640 - RSA - Input data contains invalid padding and is rejected
```
</blockquote></details>

@mkow I haven't seen such an error in my life. I suspect you have some incompatibility in client and server apps; maybe you have old and new mbedTLS versions jumbled up?

---


<!-- Sent from Reviewable.io -->

2022-03-04 08:38 UTC, dimakuv commented
Jenkins, test this please

2022-03-04 12:20 UTC, mkow requested changes
> Reviewed 2 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxJq4IjCyg5Tn3JwjYj:bzdcc1u) (no related file):*
I cleaned the directory to the state where `git clean -dfxn` doesn't show anything and I still get this error. The native example doesn't even depend on Gramine, it should really work...
What's interesting is that I see that both `client` and `server` link to my _system_ mbedtls, not the one downloaded here:
```
> ldd client
[...]
	libmbedcrypto_gramine.so.6 => /usr/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.6 (0x00007fc2e18e4000)
	libmbedtls_gramine.so.13 => /usr/lib/x86_64-linux-gnu/libmbedtls_gramine.so.13 (0x00007fc2e18a4000)
	libmbedx509_gramine.so.1 => /usr/lib/x86_64-linux-gnu/libmbedx509_gramine.so.1 (0x00007fc2e1880000)
[...]
```

But: they are compiled against the downloaded headers.

---


<!-- Sent from Reviewable.io -->

2022-03-04 13:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxK6NCZ3XiXLmX44oS8:b-a7813y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I cleaned the directory to the state where `git clean -dfxn` doesn't show anything and I still get this error. The native example doesn't even depend on Gramine, it should really work...
What's interesting is that I see that both `client` and `server` link to my _system_ mbedtls, not the one downloaded here:
```
> ldd client
[...]
	libmbedcrypto_gramine.so.6 => /usr/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.6 (0x00007fc2e18e4000)
	libmbedtls_gramine.so.13 => /usr/lib/x86_64-linux-gnu/libmbedtls_gramine.so.13 (0x00007fc2e18a4000)
	libmbedx509_gramine.so.1 => /usr/lib/x86_64-linux-gnu/libmbedx509_gramine.so.1 (0x00007fc2e1880000)
[...]
```

But: they are compiled against the downloaded headers.
</blockquote></details>

@mkow You have some incorrect environment. Here is mine:
```
~/tmp/mbedtls31/gramine/CI-Examples/ra-tls-mbedtls$ ldd client
        linux-vdso.so.1 (0x00007ffd6b3ee000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6c0f072000)
        libmbedcrypto_gramine.so.11 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.11 (0x00007f6c0ede9000)
        libmbedtls_gramine.so.17 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedtls_gramine.so.17 (0x00007f6c0ebbb000)
        libmbedx509_gramine.so.4 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedx509_gramine.so.4 (0x00007f6c0e9ab000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6c0e5ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6c0f47c000)
```

I assume you forgot to do `export PKG_CONFIG_PATH= ...` which forces GCC to use our mbedTLS.

---


<!-- Sent from Reviewable.io -->

2022-03-04 13:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxKBKJf4b2qaF1JHx1i:b4d52e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow You have some incorrect environment. Here is mine:
```
~/tmp/mbedtls31/gramine/CI-Examples/ra-tls-mbedtls$ ldd client
        linux-vdso.so.1 (0x00007ffd6b3ee000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6c0f072000)
        libmbedcrypto_gramine.so.11 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.11 (0x00007f6c0ede9000)
        libmbedtls_gramine.so.17 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedtls_gramine.so.17 (0x00007f6c0ebbb000)
        libmbedx509_gramine.so.4 => /home/dimakuv/tmp/mbedtls31/gramine/built-debug/lib/x86_64-linux-gnu/libmbedx509_gramine.so.4 (0x00007f6c0e9ab000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6c0e5ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6c0f47c000)
```

I assume you forgot to do `export PKG_CONFIG_PATH= ...` which forces GCC to use our mbedTLS.
</blockquote></details>

Why do you say "forgot"? I was following the "Quick Start" from the readme, I don't see anything about it there.

---


<!-- Sent from Reviewable.io -->

2022-03-04 14:10 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxKF77ZCs3pnDnedg1r:b-zh1m5j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do you say "forgot"? I was following the "Quick Start" from the readme, I don't see anything about it there.
</blockquote></details>

I mean, you seem to build this branch of Gramine *locally* (without installing globally), and thus you need to specify the *local* versions of the three envvar paths, described here in the table: https://gramine.readthedocs.io/en/latest/devel/building.html#additional-build-options

Note that you have old versions of mbedTLS libraries in your system-wide path, e.g. `/usr/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.6`. But you need to build Gramine and this example with the locally installed mbedTLS libraries.

---


<!-- Sent from Reviewable.io -->

2022-03-04 14:11 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxKGE_s9CxOH7Atr385:bkmj6fp) (no related file):*
> Why do you say "forgot"? I was following the "Quick Start" from the readme, I don't see anything about it there.

It's not about the example's README, it's about the general environment of locally-installed Gramine.

---


<!-- Sent from Reviewable.io -->

2022-03-04 15:00 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxKJDi08B6Mh40Rus9v:blotkx9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Why do you say "forgot"? I was following the "Quick Start" from the readme, I don't see anything about it there.

It's not about the example's README, it's about the general environment of locally-installed Gramine.
</blockquote></details>

Hmm, that may be the cause, I had other variables set, but not `PKG_CONFIG_PATH`. I think in some older version we didn't have this pkgconfig there. And this step is _native_, so I didn't expect it to depend on Gramine. Anyways, works now :)

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFE65V5efqn5q_VI-e:-MxKP5YuBGcHhsfTTN5b:b-knmq2q) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I haven't seen such an error in my life. I suspect you have some incompatibility in client and server apps; maybe you have old and new mbedTLS versions jumbled up?
</blockquote></details>

It was the same problem as above, works now.

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxKQF0k7GBwtXxBuU50:b-3cq4l6) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow These are the same keys as used previously. Note that we have a HUGE warning when we detect these keys: 
- https://github.com/gramineproject/gramine/blob/76d8285ce71c6af33f6e9a288c90517a06e88973/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov.h#L6
- https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L182
</blockquote></details>

Hmm, how do you actually trigger this warning? This hardcoded cert seems to be used only in one code path in this example, and I'm not sure to which scenario it corresponds to and how to trigger it.


<!-- Sent from Reviewable.io -->

2022-03-04 15:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxKSSvlDku_dRhzKVCR:b-f20688) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, how do you actually trigger this warning? This hardcoded cert seems to be used only in one code path in this example, and I'm not sure to which scenario it corresponds to and how to trigger it.
</blockquote></details>

Interestingly, I can get to the path which uses these certs when running natively, but I don't get any warnings then.


<!-- Sent from Reviewable.io -->

2022-03-07 07:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxFD8zyDs4fl86PeUj-:-MxYFkCo64E7ey52pNb9:b5gr76y) (no related file):*
> And this step is native, so I didn't expect it to depend on Gramine.

This step is not exactly native, because it explicitly links against Gramine-specific version of mbedTLS: https://github.com/gramineproject/gramine/blob/29f127542a4d81a8b461f05a4b36344d89bed3fa/CI-Examples/ra-tls-mbedtls/Makefile#L72

---
___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxYGe46BYHj3Ic92dAk:b9nji8e) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Interestingly, I can get to the path which uses these certs when running natively, but I don't get any warnings then.
</blockquote></details>

@mkow You are right. This warning is printed only in the Secret Prov library (which is used in https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov example). This warning is not printed in the RA-TLS library (which is in this PR).

Do you want to add this warning in this RA-TLS-MBEDTLS example as well? I think this makes sense. It's weird that we have the warning in `ra-tls-secret-prov` but we don't have it in `ra-tls-mbedtls`.


<!-- Sent from Reviewable.io -->

2022-03-07 11:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxZ3Hq_BFsqJo6YgLwr:b-6li0o5) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow You are right. This warning is printed only in the Secret Prov library (which is used in https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov example). This warning is not printed in the RA-TLS library (which is in this PR).

Do you want to add this warning in this RA-TLS-MBEDTLS example as well? I think this makes sense. It's weird that we have the warning in `ra-tls-secret-prov` but we don't have it in `ra-tls-mbedtls`.
</blockquote></details>

Doesn't this fail prove my point that we really shouldn't hardcode any keys in the source, even for testing only? ;) Users could actually use that key because the warning was bugged...


<!-- Sent from Reviewable.io -->

2022-03-07 12:33 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxZMOcmDIUbaaTTQcZf:b-b8pu9x) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Doesn't this fail prove my point that we really shouldn't hardcode any keys in the source, even for testing only? ;) Users could actually use that key because the warning was bugged...
</blockquote></details>

@mkow Do you mean that we should delete these example certs and put the instructions how to create some dummy keypair + cert chain in the README?

Anyway, this is orthogonal to this PR. How do you want to proceed with this PR?


<!-- Sent from Reviewable.io -->

2022-03-07 12:40 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxZNIAB3F6jvN4WX3YR:b-iay1ec) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
> Do you mean that we should delete these example certs and put the instructions how to create some dummy keypair + cert chain in the README?

No, just generate them during build (if the user didn't supply any).

> Anyway, this is orthogonal to this PR. How do you want to proceed with this PR?

I'd prefer to keep it blocked until we have a solution to this (as it should be quick and simple). It's partially-related IMO, as we change a significant part of mbedtls interactions here.
@kailun-qin Could you do this? If the change is small then you can just add it to this PR, otherwise create another one which depends on this one.


<!-- Sent from Reviewable.io -->

2022-03-08 10:15 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-Mxd0PYw8uXxU3AD7CXq:b-5u1hoc) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Do you mean that we should delete these example certs and put the instructions how to create some dummy keypair + cert chain in the README?

No, just generate them during build (if the user didn't supply any).

> Anyway, this is orthogonal to this PR. How do you want to proceed with this PR?

I'd prefer to keep it blocked until we have a solution to this (as it should be quick and simple). It's partially-related IMO, as we change a significant part of mbedtls interactions here.
@kailun-qin Could you do this? If the change is small then you can just add it to this PR, otherwise create another one which depends on this one.
</blockquote></details>

Ok, I agree with Michal, we could do it: add Makefile targets to create a localhost dummy keypair + cert chain.


<!-- Sent from Reviewable.io -->

2022-03-09 06:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 13 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/src/certs.h, line 101 at r6](https://reviewable.io/reviews/gramineproject/gramine/426#-MxCCJud2TCCS9OnA3PT:-MxhFqg54-WRPwIdArQ5:bgq9rcs) ([raw file](https://github.com/gramineproject/gramine/blob/7427cdeaf14de3d71e7a94f6ef03af39ac623988/CI-Examples/ra-tls-mbedtls/src/certs.h#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I agree with Michal, we could do it: add Makefile targets to create a localhost dummy keypair + cert chain.
</blockquote></details>

Done. PTAL, thanks!


<!-- Sent from Reviewable.io -->

2022-03-09 08:01 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/Makefile, line 45 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhaaM10Zjs8ycdV57n:-MxhaaM10Zjs8ycdV57o:b-c252fw) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/Makefile#L45)):*
> ```Makefile
> 	openssl req -new -key ssl/server.key -out ssl/server.csr -config ssl/ca_config.conf
> 	openssl x509 -req -days 360 -in ssl/server.csr -CA ssl/ca.crt -CAkey ssl/ca.key -CAcreateserial -out ssl/server.crt
> endif
> ```

Why so complicated, with a PHONY target and an `ifeq`? Why not simply:
```
ssl/server.crt:
	openssl genrsa -out ssl/ca.key 2048
	openssl req -x509 -new -nodes -key ssl/ca.key -sha256 -days 1024 -out ssl/ca.crt -config ssl/ca_config.conf
	openssl genrsa -out ssl/server.key 2048
	openssl req -new -key ssl/server.key -out ssl/server.csr -config ssl/ca_config.conf
	openssl x509 -req -days 360 -in ssl/server.csr -CA ssl/ca.crt -CAkey ssl/ca.key -CAcreateserial -out ssl/server.crt
```

And in the rule for `app`, it will be simply: `app: ssl/server.crt ...`
___
*[CI-Examples/ra-tls-mbedtls/Makefile, line 200 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-Mxhb4hG6Z8zehknikzJ:-Mxhb4hG6Z8zehknikzK:b-xw1wpx) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/Makefile#L200)):*
> ```Makefile
> .PHONY: distclean
> distclean: clean
> 	$(RM) -r mbedtls/ *.tar.gz
> ```

Please also add `ssl/ca.*` and `ssl/server.*` here.
___
*[CI-Examples/ra-tls-mbedtls/src/client.c, line 122 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhbJmIB6RiNhaKR36P:-MxhbJmIB6RiNhaKR36Q:b3vh7q6) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/src/client.c#L122)):*
> ```C
>     const char* pers = "ssl_client1";
>     bool in_sgx = getenv_client_inside_sgx();
>     const char* ca_crt_path = "ssl/ca.crt";
> ```

I would prefer to have a macro: `#DEFINE SERVER_CA_CRT_PATH "ssl/ca.crt"` instead of this.
___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 62 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhbVVP28Q1KKjpgaDS:-MxhbVVP28Q1KKjpgaDT:bhekmk3) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/src/server.c#L62)):*
> ```C
>     const char* ca_crt_path = "ssl/ca.crt";
>     const char* srv_crt_path = "ssl/server.crt";
>     const char* srv_key_path = "ssl/server.key";
> ```

I would prefer to have three macros instead of these three vars. Rationale: macros are described at the top of the file and generally much more readable than const vars.


<!-- Sent from Reviewable.io -->

2022-03-09 08:40 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: 16 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[CI-Examples/ra-tls-mbedtls/Makefile, line 45 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhaaM10Zjs8ycdV57n:-MxhpU3V6YjlE5JVcoiY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/Makefile#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why so complicated, with a PHONY target and an `ifeq`? Why not simply:
```
ssl/server.crt:
	openssl genrsa -out ssl/ca.key 2048
	openssl req -x509 -new -nodes -key ssl/ca.key -sha256 -days 1024 -out ssl/ca.crt -config ssl/ca_config.conf
	openssl genrsa -out ssl/server.key 2048
	openssl req -new -key ssl/server.key -out ssl/server.csr -config ssl/ca_config.conf
	openssl x509 -req -days 360 -in ssl/server.csr -CA ssl/ca.crt -CAkey ssl/ca.key -CAcreateserial -out ssl/server.crt
```

And in the rule for `app`, it will be simply: `app: ssl/server.crt ...`
</blockquote></details>

Done.
___
*[CI-Examples/ra-tls-mbedtls/Makefile, line 200 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-Mxhb4hG6Z8zehknikzJ:-MxhpTGOAlvWEyIeNx6w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/Makefile#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add `ssl/ca.*` and `ssl/server.*` here.
</blockquote></details>

Done.
___
*[CI-Examples/ra-tls-mbedtls/src/client.c, line 122 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhbJmIB6RiNhaKR36P:-MxhpM_VBD2kApV8B0Kl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/src/client.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to have a macro: `#DEFINE SERVER_CA_CRT_PATH "ssl/ca.crt"` instead of this.
</blockquote></details>

Done.
___
*[CI-Examples/ra-tls-mbedtls/src/server.c, line 62 at r9](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhbVVP28Q1KKjpgaDS:-MxhpLGE9u6VExqd5ZAn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7063dc6f97b6fbeeba57086d695d942778611f5f/CI-Examples/ra-tls-mbedtls/src/server.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to have three macros instead of these three vars. Rationale: macros are described at the top of the file and generally much more readable than const vars.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-09 09:26 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhzmgU3LuYhfvClvf2:-MxhzmgU3LuYhfvClvf3:b-daw9d3) (no related file):*
We'll need a follow-up PR to remove the files from https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/certs and replace them with Makefile rules to generate them with `openssl` commands.

---


<!-- Sent from Reviewable.io -->

2022-03-09 09:26 UTC, dimakuv commented
Jenkins, test this please

2022-03-09 14:26 UTC, mkow approved these changes
> Reviewed 3 of 6 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2022-03-09 15:06 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mxj4K8_1vR2Xfz1lqoG:b-iw3h76) (no related file):*
> I agree with @kailun-qin that moving to 3.x is a major win: iiuc, TLS 1.3 will not be available in mbedTLS 2.28

Is there any demonstrable interest in this, or is it just a guess?

> (the documentation on TLS 1.3 support is really sparse, and for some reason mbedTLS developers are very secretive about this, but this was my impression after reading the link above).

They call it "MVP": https://github.com/ARMmbed/mbedtls/blob/4579a972bf60f8de78c074b88d871b95a8a7e48a/docs/architecture/tls13-support.md, so I'm not surprised no one got around to writing docs.

WRT backporting: I guess we're not qualified to judge if the maintainers of the project in question do the good or bad job at maintaining security posture of their own project. Some bugfixes are not backported simply because the bug was introduced in a later version/branch. I haven't seen any actual data to support the statement that older branches of mbedtls are less secure than most recent release.

I'm pushing back against this for compatibility reasons: 1) update to 3.0 is incompatible (BTW I haven't seen an argument that existing workloads will still work after this PR, if not, we need to bump gramine major version); 2) I don't want to end up with a situation where we're forced to update mbedtls to incompatible version from under our users, because 3.1 will get out of support and next version will change something important (the blame will be ours, because we changed mbedtls version). LTS branches promise to delay such a scenario for longer.

---


<!-- Sent from Reviewable.io -->

2022-03-10 07:41 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxmkTB0EeExh_ErKYl-:b-49dvbu) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I agree with @kailun-qin that moving to 3.x is a major win: iiuc, TLS 1.3 will not be available in mbedTLS 2.28

Is there any demonstrable interest in this, or is it just a guess?

> (the documentation on TLS 1.3 support is really sparse, and for some reason mbedTLS developers are very secretive about this, but this was my impression after reading the link above).

They call it "MVP": https://github.com/ARMmbed/mbedtls/blob/4579a972bf60f8de78c074b88d871b95a8a7e48a/docs/architecture/tls13-support.md, so I'm not surprised no one got around to writing docs.

WRT backporting: I guess we're not qualified to judge if the maintainers of the project in question do the good or bad job at maintaining security posture of their own project. Some bugfixes are not backported simply because the bug was introduced in a later version/branch. I haven't seen any actual data to support the statement that older branches of mbedtls are less secure than most recent release.

I'm pushing back against this for compatibility reasons: 1) update to 3.0 is incompatible (BTW I haven't seen an argument that existing workloads will still work after this PR, if not, we need to bump gramine major version); 2) I don't want to end up with a situation where we're forced to update mbedtls to incompatible version from under our users, because 3.1 will get out of support and next version will change something important (the blame will be ours, because we changed mbedtls version). LTS branches promise to delay such a scenario for longer.
</blockquote></details>

Hm. We're getting stuck in this discussion.

I suggest the following next steps:
1. @kailun-qin Could you prepare a separate (and completely unrelated to our current debate) PR that removes `certs.h` header from `ra-tls-mbedtls` and `ra-tls-secret-prov` examples and replaces them with auto-generated ones? In other words, could you extract this patch from this PR, augment `ra-tls-secret-prov` similarly, and submit a new PR? This part is not controversial and will be quickly merged.
2. @mkow What about we update to 2.28 (this should be a trivial development effort, much less than this PR), and "preserve" this PR for future times?

---


<!-- Sent from Reviewable.io -->

2022-03-10 09:07 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mxn4D3p4zySwJIW_Ghs:b-6gnd6c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm. We're getting stuck in this discussion.

I suggest the following next steps:
1. @kailun-qin Could you prepare a separate (and completely unrelated to our current debate) PR that removes `certs.h` header from `ra-tls-mbedtls` and `ra-tls-secret-prov` examples and replaces them with auto-generated ones? In other words, could you extract this patch from this PR, augment `ra-tls-secret-prov` similarly, and submit a new PR? This part is not controversial and will be quickly merged.
2. @mkow What about we update to 2.28 (this should be a trivial development effort, much less than this PR), and "preserve" this PR for future times?
</blockquote></details>

Made a quick one at https://github.com/gramineproject/gramine/pull/451. See if it helps, thanks.

---


<!-- Sent from Reviewable.io -->

2022-03-11 13:29 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxodW3RDrs0-C-dQ_LA:bal144w) (no related file):*
> WRT backporting: I guess we're not qualified to judge if the maintainers of the project in question do the good or bad job at maintaining security posture of their own project. Some bugfixes are not backported simply because the bug was introduced in a later version/branch. I haven't seen any actual data to support the statement that older branches of mbedtls are less secure than most recent release.

It's the other way around: the default is that backporting security fixes in any non-trivial codebase is super-hard and only approximate. If you want to use an older version then you should have some solid data that the maintainers are actually super careful about backporting and also, actually analyze normal bugfixes in terms of security implications. If we don't know this, then we should use the most recent release, especially considering that the whole point of Gramine is security.

> BTW I haven't seen an argument that existing workloads will still work after this PR, if not, we need to bump gramine major version

Why would they stop working? It's Gramine using this mbedtls internally, not the workloads.

---


<!-- Sent from Reviewable.io -->

2022-03-11 14:37 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MwlIGcl-Vs7QAR5NgtX:bubj375) (no related file):*
> Why would they stop working? It's Gramine using this mbedtls internally, not the workloads.

Libratls uses this also, and it's supplied to users. IIUC users are expected to link against both libratls and our version of mbedtls to set up a TLS connection in enclave which presents X.509 cert with attestation material. Then the enclave uses mbedtls' API to normally pump the TLS pipe. So no, this is very much user-facing.

Why would they stop working: what about the changes to `server.c` and `client.c`? Aren't they needed so this example workload won't stop working?

---


<!-- Sent from Reviewable.io -->

2022-03-11 14:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxtPwzr34mxy-_J7A_C:bb1zmg3) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Why would they stop working? It's Gramine using this mbedtls internally, not the workloads.

Libratls uses this also, and it's supplied to users. IIUC users are expected to link against both libratls and our version of mbedtls to set up a TLS connection in enclave which presents X.509 cert with attestation material. Then the enclave uses mbedtls' API to normally pump the TLS pipe. So no, this is very much user-facing.

Why would they stop working: what about the changes to `server.c` and `client.c`? Aren't they needed so this example workload won't stop working?
</blockquote></details>

I think we use mbedTLS twice: A) for our internal Gramine use (e.g. encrypted pipes) B) for external stuff (e.g. RATLS). These are completely two different usages; we use the same mbedTLS version for simplicity, but in theory they could be both different versions.
For point A) I believe we need a custom patch, so we are stuck with manually compiling mbedTLS (and this won't change anytime soon). For B) we could use distro version as long as it supports CMAC. So the answer for question "is this user-facing" is both yes and no.
Since due to A) we need to compile manually, then I vote for using latest version possible.

(I didn't review the PR, just chiming in this discussion)

---


<!-- Sent from Reviewable.io -->

2022-03-11 14:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxtTht72j3dPgrewCfx:b-2jdzp1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we use mbedTLS twice: A) for our internal Gramine use (e.g. encrypted pipes) B) for external stuff (e.g. RATLS). These are completely two different usages; we use the same mbedTLS version for simplicity, but in theory they could be both different versions.
For point A) I believe we need a custom patch, so we are stuck with manually compiling mbedTLS (and this won't change anytime soon). For B) we could use distro version as long as it supports CMAC. So the answer for question "is this user-facing" is both yes and no.
Since due to A) we need to compile manually, then I vote for using latest version possible.

(I didn't review the PR, just chiming in this discussion)
</blockquote></details>

I'm not sure that even in B) this is user-facing. IMO ra-tls libraries should link statically to our custom mbedtls, so that they won't interfere with the mbedtls used by the app (which may be both newer or older than we ourselves use).

---


<!-- Sent from Reviewable.io -->

2022-03-11 15:21 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxtUZdK2lr55NdkpNsc:b22j92m) (no related file):*
>  IMO ra-tls libraries should link statically to our custom mbedtls

Yes, both this and distro-provided CMAC-enabled version are viable solutions (well, distro version currently not, because no distro provides such version yet), but until either happens, our version of mbedtls faces the user.

---


<!-- Sent from Reviewable.io -->

2022-03-11 15:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxtcOCn-0bWtJ-sTB7g:b-qo233r) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

>  IMO ra-tls libraries should link statically to our custom mbedtls

Yes, both this and distro-provided CMAC-enabled version are viable solutions (well, distro version currently not, because no distro provides such version yet), but until either happens, our version of mbedtls faces the user.
</blockquote></details>

I checked and currently the libraries don't collide with user apps, because we renamed them to have `_gramine` suffix. And even if it collided, then we still should just update and the users would need to adopt (but that's not actually the case).

---


<!-- Sent from Reviewable.io -->

2022-03-11 16:13 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-MxtjLtPARXZCH7I40d6:b-ahgat9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I checked and currently the libraries don't collide with user apps, because we renamed them to have `_gramine` suffix. And even if it collided, then we still should just update and the users would need to adopt (but that's not actually the case).
</blockquote></details>

Sonames don't collide, but symbols inside do collide, and you need to be linked against our version for libratls. Or am I misunderstanding things?

---


<!-- Sent from Reviewable.io -->

2022-03-11 16:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mxtm4K47o4Z6bXGIItF:bt80mly) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Sonames don't collide, but symbols inside do collide, and you need to be linked against our version for libratls. Or am I misunderstanding things?
</blockquote></details>

If symbols collide you already have a problem

---


<!-- Sent from Reviewable.io -->

2022-03-11 16:29 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @kailun-qin, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mxtnivi1O5FoxlIZnXe:b-q300gk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If symbols collide you already have a problem
</blockquote></details>

No, why? They just link against our version only.

---


<!-- Sent from Reviewable.io -->

2022-03-11 16:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-Mxtqe4v7g-fGyVwYnb1:b-emyglu) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, why? They just link against our version only.
</blockquote></details>

Then what collides with what?

---


<!-- Sent from Reviewable.io -->

2022-03-14 08:38 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-My6Yg0R-3nVeh_J-Ma0:b-uqnsw5) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then what collides with what?
</blockquote></details>

Borys's description of our two usages of mbedTLS is absolutely correct. Usage A *is not* user-facing because this version of mbedTLS is statically compiled into the Linux-SGX PAL. Usage B *is* currently user-facing because we use dynamic linking for RA-TLS and Secret Prov libraries. But as Michal mentions, this doesn't need to be so -- RA-TLS and Secret Prov libraries could use static linking to "hide" `mbedtls_gramine` dependency completely (and also hide the symbols, so no collisions ever happen).

So I think everyone here agrees that all Gramine-provided shared libraries must **link mbedTLS statically**. Currently in Gramine, we have only two such libraries: RA-TLS and Secret Prov.

@kailun-qin Would you be interested in creating such a PR, that changes RA-TLS and Secret Prov build process to statically link `mbedtls_gramine` libs?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MxhzmgU3LuYhfvClvf2:-My6Xd_M6K5j1Jy4jsQM:b-q0l33b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We'll need a follow-up PR to remove the files from https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/certs and replace them with Makefile rules to generate them with `openssl` commands.
</blockquote></details>

Resolving since this was done in https://github.com/gramineproject/gramine/pull/451.

---


<!-- Sent from Reviewable.io -->

2022-03-14 11:20 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/426)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/426#-MwkS7_O6sz5c1LQOxtx:-My78n7n2d3FjTXWbrBl:b-8f9a5l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys's description of our two usages of mbedTLS is absolutely correct. Usage A *is not* user-facing because this version of mbedTLS is statically compiled into the Linux-SGX PAL. Usage B *is* currently user-facing because we use dynamic linking for RA-TLS and Secret Prov libraries. But as Michal mentions, this doesn't need to be so -- RA-TLS and Secret Prov libraries could use static linking to "hide" `mbedtls_gramine` dependency completely (and also hide the symbols, so no collisions ever happen).

So I think everyone here agrees that all Gramine-provided shared libraries must **link mbedTLS statically**. Currently in Gramine, we have only two such libraries: RA-TLS and Secret Prov.

@kailun-qin Would you be interested in creating such a PR, that changes RA-TLS and Secret Prov build process to statically link `mbedtls_gramine` libs?
</blockquote></details>

Made a quick one at https://github.com/gramineproject/gramine/pull/456. PTAL and see if it's what you expect. Thanks.

---


<!-- Sent from Reviewable.io -->

2022-08-01 13:24 UTC, dimakuv commented
This was superseded by https://github.com/gramineproject/gramine/pull/796, which was merged already. Closing.

2022-08-01 13:24 UTC, closed without merging