[LibOS] Move fully to inodes
gramineproject/gramine pull request #428
Opened 2022-02-24 14:38 UTC by pwmarcz

## Description of the changes 

This change removes the `state` dentry field, and uses the `inode` field directly: a dentry is either positive (with inode) or negative (without inode). Dentry fields describing the file (`type`, `perm`) are also gone.

As a consequence, negative lookups are no longer cached: a negative dentry only means that a file is not known to exist.

## How to test this PR? 

Jenkins should be enough.

## What's next

Cleanup: using inode as a parameter should simplify the implementation of individual filesystems.

2022-02-25 12:35 UTC, dimakuv requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkplWq5V3PMw_2yQbv:-MwkplWq5V3PMw_2yQbw:b-16ajgx) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L238)):*
> ```objc
>      * \brief Unlink a file
>      *
>      * \param dent dentry, full, must have a parent
> ```

`full`? Why not just `postive`?
___
*[LibOS/shim/include/shim_fs.h, line 243 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkpiOa9EhZC1BoNjVE:-MwkpiOa9EhZC1BoNjVF:b-j8h05x) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L243)):*
> ```objc
>      * possible, they should still work.
>      *
>      * The caller should hold `g_dcache_lock`. On success, the caller detach the inode from the
> ```

`the caller should detach`
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkpww03FtrO4Qb-tIs:-Mwkpww03FtrO4Qb-tIt:b3cyp9f) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L282)):*
> ```objc
>      *
>      * The caller should hold `g_dcache_lock`. On success, the caller should update
>      * `dent->inode->perm`.
> ```

Is this one of the TODOs for the follow-up PR? That `chmod()` will use `inode` instead of this?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkqaq0-_66ILYempAe:-Mwkqaq0-_66ILYempAf:bc4ebyl) ([raw file](https://github.com/gramineproject/gramine/blob/90da396067e2530ade39e2cc1eb4273137271ed0/LibOS/shim/src/fs/shim_dcache.c#L455)):*
> ```C
>         buf_puts(&buf, "M");
>     } else if (!dent->parent) {
>         buf_puts(&buf, "*");
> ```

Why did you remove these two?
___
*[LibOS/shim/src/fs/shim_fs.c, line 557 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkr6bB5VMpk7DJCHGI:-Mwkr6bB5VMpk7DJCHGJ:b-3uohml) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/src/fs/shim_fs.c#L557)):*
> ```C
>          * directly. */
>         mount_point = g_dentry_root;
>         get_dentry(g_dentry_root);
> ```

How did it work before? Why did you have to add this new case?
___
*[LibOS/shim/src/fs/shim_namei.c, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkrZyd4tvVYyJTxOj9:-MwkrZyd4tvVYyJTxOjA:b-83jra) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/src/fs/shim_namei.c#L130)):*
> ```C
>     if (cur_dent != *dent) {
>         get_dentry(cur_dent);
>         put_dentry(*dent);
> ```

Any reason you swapped these two places?


<!-- Sent from Reviewable.io -->

2022-02-25 13:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: 16 of 18 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwl-WzP1lLNnCcUsQt_:-Mwl-WzP1lLNnCcUsQta:b-854t8t) (no related file):*
This PR conflicts with #425 (marking dentries as deleted) and #420 (Doxygen formatting). It looks like both will be merged sooner, so I will be rebasing this PR afterwards.

---
___
*[LibOS/shim/include/shim_fs.h, line 238 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkplWq5V3PMw_2yQbv:-Mwl0A6lE3J3W9Bw5eI3:b-ykpbyv) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`full`? Why not just `postive`?
</blockquote></details>

My mistake, fixed (this is a leftover from an earlier version of this patch, where I considered "empty/full" instead of "negative/positive").
___
*[LibOS/shim/include/shim_fs.h, line 243 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkpiOa9EhZC1BoNjVE:-Mwl0KXC0kzdgmfco3Os:bj3eoea) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the caller should detach`
</blockquote></details>

Fixed, thanks.
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkpww03FtrO4Qb-tIs:-Mwl0PYI5Yqa5SxcrG6M:bynsz1o) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this one of the TODOs for the follow-up PR? That `chmod()` will use `inode` instead of this?
</blockquote></details>

Possibly. I was thinking also about `lookup`, which right now has to create an inode and attach it to a dentry, and it could just create an inode.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 455 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkqaq0-_66ILYempAe:-Mwl1zFrBHJdQ5mFqKO-:bkl6vsa) ([raw file](https://github.com/gramineproject/gramine/blob/90da396067e2530ade39e2cc1eb4273137271ed0/LibOS/shim/src/fs/shim_dcache.c#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove these two?
</blockquote></details>

I removed it, because I thought it duplicates the information I added to root dentries recently (e.g. `bin/ (chroot "file:/bin")`): you already see where the root dentry is, and the one above it is the mountpoint.

But looking at the output again, I think it's still helpful to have the mountpoint marked with "M": mountpoints are special because they're shadowed by the mounted filesystem.

Example:
```
[P1:T1:helloworld] [ synth   2] 040555 dr-x      usr/
[P1:T1:helloworld] [ synth   2] 040555 dr-x        lib/
[P1:T1:helloworld] [ synth   2] 040555 dr-x M        x86_64-linux-gnu/
[P1:T1:helloworld] [chroot   1] 040755 drwx            x86_64-linux-gnu/ (chroot "file:/usr//lib/x86_64-linux-gnu")
[P1:T1:helloworld] [ synth   2] 040555 dr-x M    bin/
[P1:T1:helloworld] [chroot   1] 040755 drwx        bin/ (chroot "file:/bin")
[P1:T1:helloworld] [ synth   2] 040555 dr-x      mnt/
[P1:T1:helloworld] [ synth   2] 040555 dr-x M      tmpfs/
[P1:T1:helloworld] [ tmpfs   1] 040700 drwx          tmpfs/ (tmpfs "")
```
___
*[LibOS/shim/src/fs/shim_fs.c, line 557 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkr6bB5VMpk7DJCHGI:-Mwl2jSC7VSYpbFm5rtr:b776573) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/src/fs/shim_fs.c#L557)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How did it work before? Why did you have to add this new case?
</blockquote></details>

This is a consequence of adding the rule that "if a file exists, it must have an inode". All filesystems follow this rule, but for `g_dentry_root` we just marked the dentry with `DENTRY_VALID` flag so that it can be looked up. After all, nobody will make any operations on this dentry, because it's going to be shadowed by the mounted filesystem.

After this refactoring, we can't get away with that anymore (and there's not even a flag to set anymore). I could create a fake inode for `g_dentry_root`, but I want inodes to belong to a mounted filesystem (`inode->mount != NULL`), and here there isn't any. So the easiest way forward is to say that this file does not exist.
___
*[LibOS/shim/src/fs/shim_namei.c, line 130 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-MwkrZyd4tvVYyJTxOj9:-Mwl3u1-3y5zAj1AYopL:bd7cord) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/src/fs/shim_namei.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any reason you swapped these two places?
</blockquote></details>

In the previous version, I was tempted to leave out the `if (cur_dent != *dent)` condition in order to simplify this function. But if `put_dentry` is first, that actually can break: if `cur_dent == *dent`, then we can end up deallocating the dentry.

So, even though it doesn't matter as long as the condition is in place, I slightly prefer the current order.


<!-- Sent from Reviewable.io -->

2022-02-25 14:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: 16 of 18 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkpww03FtrO4Qb-tIs:-MwlD9Iu7aS8SyQGlSwa:b6pw4uw) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L282)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Possibly. I was thinking also about `lookup`, which right now has to create an inode and attach it to a dentry, and it could just create an inode.
</blockquote></details>

Oh, but if you mean "the caller should update `dent->inode->perm`", this is actually done in this PR.


<!-- Sent from Reviewable.io -->

2022-02-28 12:36 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwl-WzP1lLNnCcUsQt_:-Mx-JDJX3Wy7sjtRd9HU:bd3r3aq) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This PR conflicts with #425 (marking dentries as deleted) and #420 (Doxygen formatting). It looks like both will be merged sooner, so I will be rebasing this PR afterwards.
</blockquote></details>

#425 will be merged very soon, so yeah.

---
___
*[LibOS/shim/include/shim_fs.h, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwkpww03FtrO4Qb-tIs:-Mx-JQOA0xItMvNIhIbZ:b9ibncq) ([raw file](https://github.com/gramineproject/gramine/blob/8c8b6627b0094823a3c4255df43c3eac145ca66a/LibOS/shim/include/shim_fs.h#L282)):*
> Oh, but if you mean "the caller should update dent->inode->perm", this is actually done in this PR.

No, your first reply was the one I was asking about :) Resolving.


<!-- Sent from Reviewable.io -->

2022-02-28 17:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: 16 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwl-WzP1lLNnCcUsQt_:-Mx0Q2L92wYwHQoTrG0P:b-8g6v4f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

#425 will be merged very soon, so yeah.
</blockquote></details>

Rebased after #425.

---


<!-- Sent from Reviewable.io -->

2022-03-01 07:43 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/428#-Mx3QjmKCKvQ6cQIufwO):*
What is this? The fixup commit belongs to the wrong commit...


<!-- Sent from Reviewable.io -->

2022-03-01 08:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/428#-Mx3QjmKCKvQ6cQIufwO):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? The fixup commit belongs to the wrong commit...
</blockquote></details>

My bad. I think I used `@^` instead of `@` for fixup. Will fix during next rebase (after #420 is merged).


<!-- Sent from Reviewable.io -->

2022-03-01 23:01 UTC, mkow approved these changes
> Reviewed 14 of 18 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-03-03 14:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: 17 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/428#-Mwl-WzP1lLNnCcUsQt_:-MxF9jUP5VRc51yG9zms:bp7syz1) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Rebased after #425.
</blockquote></details>

And rebased after #420.

---
___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/428#-Mx3QjmKCKvQ6cQIufwO):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

My bad. I think I used `@^` instead of `@` for fixup. Will fix during next rebase (after #420 is merged).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 14:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-03 14:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/428)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-03 15:12 UTC, merged