[Python] Change Python scripts' shebang to `/usr/bin/python3`
gramineproject/gramine pull request #429
Opened 2022-02-24 15:30 UTC by dimakuv

## Description of the changes 

Gramine Python utilities should use the system-wide Python interpreter instead of the local version of Python (which may not have system-wide-installed Python packages). This was detected in GSC when running the default Python Ubuntu Docker image.

## How to test this PR? 

Test GSC with our Python example: https://gramine.readthedocs.io/projects/gsc/en/latest/#example

2022-02-25 14:15 UTC, mkow requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBPlnCQoSF4lApaIu:-MwlBPlp4iOh7evuOVFP:b9r8cei) (no related file):*
IMO we should document and explain this workaround in a short comment after each shebang. If I understand correctly, this is a hack to circumvent some popular broken Docker images.

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
I don't like this description, it sounds like we did something wrong and are fixing a bug, while in fact we're adding a workaround for broken Docker images.



_Code quote:_
```
Gramine Python utilities should use the system-wide Python interpreter
```
___
*[Pal/gdb_integration/debug_map_gdb.py, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlCCYC3Pl1_7DnSng5:-MwlCCYC3Pl1_7DnSng6:bbjqcpw) ([raw file](https://github.com/gramineproject/gramine/blob/f8727b80f282f6030ca55088a20669a4843578fa/Pal/gdb_integration/debug_map_gdb.py#L1)):*
> ```Python
> #!/usr/bin/python3
> ```

Do we need a shebang here? It's not even executable.
___
*[Pal/src/host/Linux/gdb_integration/gramine_linux_gdb.py, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlDn4FD3es7Cng8eZX:-MwlDn4G4dXS-bIdN2FP:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f8727b80f282f6030ca55088a20669a4843578fa/Pal/src/host/Linux/gdb_integration/gramine_linux_gdb.py#L1)):*
> ```Python
> #!/usr/bin/python3
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-02-25 14:42 UTC, woju submitted a review, later dismissed
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBPlnCQoSF4lApaIu:-MwlJgMg7DCGmbvmoOAe:b-hxqs3c) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO we should document and explain this workaround in a short comment after each shebang. If I understand correctly, this is a hack to circumvent some popular broken Docker images.
</blockquote></details>

Nope, `/usr/bin/python3` is perfectly fine shebang, though its less recommended than `/usr/bin/env python3`, because of *BSD. https://docs.python.org/3/using/unix.html#miscellaneous

---


<!-- Sent from Reviewable.io -->

2022-02-28 10:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 16 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBPlnCQoSF4lApaIu:-Mwzkzsr9Mqo5Cb22FTB:b-3l6h30) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Nope, `/usr/bin/python3` is perfectly fine shebang, though its less recommended than `/usr/bin/env python3`, because of *BSD. https://docs.python.org/3/using/unix.html#miscellaneous
</blockquote></details>

I'm currently not adding comments, as per Woju's reply. If Michal still insists, I can add.

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like this description, it sounds like we did something wrong and are fixing a bug, while in fact we're adding a workaround for broken Docker images.
</blockquote></details>

For the final rebase, I'll change to:
```
The default Python Docker image uses a custom version of Python, and this image
sets PATH to this custom version. This is a "broken" practice, which leads to packages
installed via e.g. `apt install` not being available to the custom version of Python.
For more info, see "Multiple Python versions in the image" section at
https://hub.docker.com/_/python. This was detected in GSC.

To support this and similar popular Docker images, we use a workaround of specifying
the system-wide Python version for Gramine Python utilities.
```

Sounds good?
___
*[Pal/gdb_integration/debug_map_gdb.py, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlCCYC3Pl1_7DnSng5:-Mwzml0X6YIfKSt5reW1:b4s704h) ([raw file](https://github.com/gramineproject/gramine/blob/f8727b80f282f6030ca55088a20669a4843578fa/Pal/gdb_integration/debug_map_gdb.py#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we need a shebang here? It's not even executable.
</blockquote></details>

Done.

I checked that GDB still works.
___
*[Pal/src/host/Linux/gdb_integration/gramine_linux_gdb.py, line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlDn4FD3es7Cng8eZX:-Mwzmo7U7y8zX_RIBn1i:b4s704h) ([raw file](https://github.com/gramineproject/gramine/blob/f8727b80f282f6030ca55088a20669a4843578fa/Pal/src/host/Linux/gdb_integration/gramine_linux_gdb.py#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

I checked that GDB still works.


<!-- Sent from Reviewable.io -->

2022-02-28 15:21 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 16 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-Mx-uo81608Ppwif_ZNy:-Mx-uo828qgCE5AI92fM:b-otj2f6) (no related file):*
So, seems we decided to `sed` this path instead? See https://github.com/gramineproject/gramine/issues/431 and our discussions on priv.

---


<!-- Sent from Reviewable.io -->

2022-02-28 15:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 16 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-Mx-uo81608Ppwif_ZNy:-Mx-vkdq58Y4Q_60QRQW:b-h2614y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, seems we decided to `sed` this path instead? See https://github.com/gramineproject/gramine/issues/431 and our discussions on priv.
</blockquote></details>

What does it mean? I think it's a typo, but I asked @woju in that issue.

---


<!-- Sent from Reviewable.io -->

2022-03-11 08:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 16 of 19 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBPlnCQoSF4lApaIu:-MxrzsbzALFT9O8-NPTU:b-wh3frz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm currently not adding comments, as per Woju's reply. If Michal still insists, I can add.
</blockquote></details>

Done, added in `coding-style.rst`.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/429#-Mx-uo81608Ppwif_ZNy:-MxrzfJJCsg_ay3x2aJZ:b-598l8w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean? I think it's a typo, but I asked @woju in that issue.
</blockquote></details>

In private conversation, it seems that Woju and Pawel are for hardcoded path. Michal hates this solution but reluctantly agrees to green-light this PR. I hope we finished this discussion, at least for now.

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For the final rebase, I'll change to:
```
The default Python Docker image uses a custom version of Python, and this image
sets PATH to this custom version. This is a "broken" practice, which leads to packages
installed via e.g. `apt install` not being available to the custom version of Python.
For more info, see "Multiple Python versions in the image" section at
https://hub.docker.com/_/python. This was detected in GSC.

To support this and similar popular Docker images, we use a workaround of specifying
the system-wide Python version for Gramine Python utilities.
```

Sounds good?
</blockquote></details>

I will change the last paragraph to this:
```
To support this and similar popular Docker images, we specify the system-wide
Python version for Gramine Python utilities (using the hardcoded path in shebang).
```


<!-- Sent from Reviewable.io -->

2022-03-11 12:50 UTC, woju approved these changes
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will change the last paragraph to this:
```
To support this and similar popular Docker images, we specify the system-wide
Python version for Gramine Python utilities (using the hardcoded path in shebang).
```
</blockquote></details>

Not blocking, but I wouldn't concentrate on docker, rather on custom python installations ("custom" meaning not provided by distro), whether packaged in docker or otherwise. If you compiled CPython from source and installed as `/usr/local/bin/python3`, it would be similarly broken for `env` shebangs. The original commit message is actually good.


<!-- Sent from Reviewable.io -->

2022-03-11 13:31 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/coding-style.rst, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/429#-MxtALCn0Tx5VgkyrkXC:-MxtALCn0Tx5VgkyrkXD:b-pszly8) ([raw file](https://github.com/gramineproject/gramine/blob/152ddc1927f8d344c6952794913b3782673ef3ba/Documentation/devel/coding-style.rst#L164)):*
> ```reStructuredText
> #. Executable Python scripts must use the shebang with the hardcoded path to
>    system Python. Since Gramine currently supports Debian/Ubuntu and
>    CentOS/RHEL/Fedora distros, the shebang must be ``#!/usr/bin/python3``.
> ```

Please explain why.


<!-- Sent from Reviewable.io -->

2022-03-14 08:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 18 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not blocking, but I wouldn't concentrate on docker, rather on custom python installations ("custom" meaning not provided by distro), whether packaged in docker or otherwise. If you compiled CPython from source and installed as `/usr/local/bin/python3`, it would be similarly broken for `env` shebangs. The original commit message is actually good.
</blockquote></details>

I will change to this text during final rebase:
```
Custom Python installations ("custom" meaning not provided by distro)
lead to a problem where packages installed via e.g. `apt install` are not
available to this custom Python. This was an issue for Gramine because
Gramine Python utilities used the custom Python installation previously
(via `#!/usr/bin/env python3` shebang), and thus couldn't locate
system-wide-installed Python packages.

This commit changes Gramine Python utilities to use the system-wide
Python installation (via the hardcoded path `#!/usr/bin/python3`) instead
of the custom one.

This was detected in GSC when running the default Python Ubuntu Docker
image. This Docker image uses a custom version of Python, and this image
sets PATH to this custom version. For more info, see "Multiple Python versions
in the image" section at https://hub.docker.com/_/python.
```
___
*[Documentation/devel/coding-style.rst, line 164 at r3](https://reviewable.io/reviews/gramineproject/gramine/429#-MxtALCn0Tx5VgkyrkXC:-My6WVnI3oy1pGLV4Vxl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/152ddc1927f8d344c6952794913b3782673ef3ba/Documentation/devel/coding-style.rst#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please explain why.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 18:25 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-04-04 22:13 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-04-05 12:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: 17 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/429#-MwlBnK4-gRNacJIjG39):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will change to this text during final rebase:
```
Custom Python installations ("custom" meaning not provided by distro)
lead to a problem where packages installed via e.g. `apt install` are not
available to this custom Python. This was an issue for Gramine because
Gramine Python utilities used the custom Python installation previously
(via `#!/usr/bin/env python3` shebang), and thus couldn't locate
system-wide-installed Python packages.

This commit changes Gramine Python utilities to use the system-wide
Python installation (via the hardcoded path `#!/usr/bin/python3`) instead
of the custom one.

This was detected in GSC when running the default Python Ubuntu Docker
image. This Docker image uses a custom version of Python, and this image
sets PATH to this custom version. For more info, see "Multiple Python versions
in the image" section at https://hub.docker.com/_/python.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 12:53 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/429)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-05 13:14 UTC, merged