[Docs] Improve and unify Doxygen comments, part 2
gramineproject/gramine pull request #439
Opened 2022-03-03 21:46 UTC by mkow

## Description of the changes 

Another chunk of changes following https://github.com/gramineproject/gramine/pull/420.

2022-03-03 23:39 UTC, boryspoplawski requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5ZEQDJ15b1eCeRDU:-MxH5ZEQDJ15b1eCeRDV:bsh1n74) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_fs_pseudo.h#L159)):*
> ```objc
>  * \param[out] out_value  On success, set to the parsed number.
>  *
>  * \returns 0 on success, -1 on failure.
> ```

Afaik we have not settled on this yet.
`\return` or `\returns`?
cc @dimakuv @pwmarcz

I don't mind either.
___
*[LibOS/shim/include/shim_internal.h, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5yIY8kRxOADnKgRB:-MxH5yIY8kRxOADnKgRC:b-qh7aa1) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_internal.h#L73)):*
> ```objc
> noreturn void restore_child_context_after_clone(struct shim_context* context);
> /*!
>  * \brief Creates a signal frame.
> ```

`Creates` -> `Create`
___
*[LibOS/shim/include/shim_internal.h, line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH64gGDrEPMZowI7jq:-MxH64gGDrEPMZowI7jr:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_internal.h#L100)):*
> ```objc
> void restart_syscall(PAL_CONTEXT* context, uint64_t syscall_nr);
> /*!
>  * \brief Restores a sigreturn context
> ```

ditto
___
*[LibOS/shim/include/shim_thread.h, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH6UHUBJuGJLNmM3Db:-MxH6UHV2wDnySjQubVz:b-t4s5m) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_thread.h#L152)):*
> ```objc
> 
> /*!
>  * \brief Allocates new ID.
> ```

`Allocates new` -> `Allocate a new`
___
*[LibOS/shim/include/shim_thread.h, line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH6eSLCt6b27iFUaAH:-MxH6eSLCt6b27iFUaAI:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_thread.h#L164)):*
> ```objc
> IDTYPE get_new_id(IDTYPE move_ownership_to);
> /*!
>  * \brief Releases (frees) previously allocated ID.
> ```

ditto
___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxH7YFm-xl-d0hWv9Da:b-gvyuh1) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
> ```objc
>  * \param         offset  Offset to read at. If \p handle is a file, \p offset must be specified at
>  *                        each call.
>  * \param[in,out] count   Size of \p buffer. On success the number of bytes read will be written to
> ```

I would leave `contains`, as this is a pointer, not size directly.
___
*[Pal/include/pal/pal.h, line 328 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7fVEABGsBvSvihvT:-MxH7fVFEVjN7nFK2DzN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L328)):*
> ```objc
>  * \param         offset  Offset to write to. If \p handle is a file, \p offset must be specified at
>  *                        each call.
>  * \param[in,out] count   Size of \p buffer. On success the number of bytes written will be written
> ```

ditto
___
*[Pal/include/pal/pal.h, line 698 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH8gaBCxUS60bBXk8G:-MxH8gaBCxUS60bBXk8H:bmx2b44) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L698)):*
> ```objc
> /*!
>  * \brief Return the amount of currently available memory for LibOS/application usage.
>  *
> ```

Empty line left?


<!-- Sent from Reviewable.io -->

2022-03-04 00:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 8 of 11 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5ZEQDJ15b1eCeRDU:-MxHAQnp5lUCJuklRWFj:bd6xfvo) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_fs_pseudo.h#L159)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Afaik we have not settled on this yet.
`\return` or `\returns`?
cc @dimakuv @pwmarcz

I don't mind either.
</blockquote></details>

I prefer `\returns`, as you see from my changes ;)
___
*[LibOS/shim/include/shim_internal.h, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5yIY8kRxOADnKgRB:-MxHAjDvB56S6Ua-T46O:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_internal.h#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`Creates` -> `Create`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 100 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH64gGDrEPMZowI7jq:-MxHAkwc7E9lKOLbQgMw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_internal.h#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 152 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH6UHUBJuGJLNmM3Db:-MxHAstn7SOy7d_niXxt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_thread.h#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`Allocates new` -> `Allocate a new`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 164 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH6eSLCt6b27iFUaAH:-MxHBBQ53o4Uoz8X-KMz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_thread.h#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxHBJ337ZmXvt4C-A3D:bz3yxiv) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would leave `contains`, as this is a pointer, not size directly.
</blockquote></details>

I know it's more technically correct that way, but it seemed overly long to me ("on function call should contain"). Any ideas how to make it precise without that long boilerplate?
___
*[Pal/include/pal/pal.h, line 698 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH8gaBCxUS60bBXk8G:-MxHDRDH9vHSVaaPeCri:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L698)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Empty line left?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-04 08:10 UTC, dimakuv requested changes
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5ZEQDJ15b1eCeRDU:-MxIvq8r7QKA_plA3mvI:bjmtonx) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_fs_pseudo.h#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer `\returns`, as you see from my changes ;)
</blockquote></details>

Why do you say we have not settled on `\return` vs `\returns`? https://github.com/gramineproject/gramine/pull/420/files -- that PR uses `\returns` everywhere, so we should stick with it.
___
*[LibOS/shim/include/shim_ipc.h, line 60 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIyNzI6xU8B2H4NbwU:-MxIyNzJ9eXGdmNbB2SR:bb6un5n) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_ipc.h#L60)):*
> ```objc
> 
> /*!
>  * \brief Initialize the IPC worker thread
> ```

Dot?
___
*[LibOS/shim/include/shim_ipc.h, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIyOy684VXbiI8CfH3:-MxIyOy684VXbiI8CfH4:bb6un5n) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_ipc.h#L64)):*
> ```objc
> int init_ipc_worker(void);
> /*!
>  * \brief Terminate the IPC worker thread
> ```

Dot?
___
*[LibOS/shim/include/shim_signal.h, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwRul1CAfTixEuRFi:-MxIwRul1CAfTixEuRFj:byo954u) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_signal.h#L162)):*
> ```objc
>  * \param setsize   Size of `__sigset_t`.
>  *
>  * \return `0` on success, negative error code on failure.
> ```

`\returns`
___
*[LibOS/shim/include/shim_thread.h, line 299 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwe1w4Q5e3e7hMvIS:-MxIwe1w4Q5e3e7hMvIT:bgw2ojf) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_thread.h#L299)):*
> ```objc
>  * \param thread  Thread for which to allocate a new stack.
>  *
>  * On success returns `0`, on failure - negative error code.
> ```

```
\returns `0` on success, negative error code on failure.
```
___
*[Pal/include/pal/pal.h, line 171 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwrwGEbAo2TCY0CzP:-MxIwrwGEbAo2TCY0CzQ:b-a18g8) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L171)):*
> ```objc
> 
> /*!
>  * \brief This API deallocates a previously allocated memory mapping.
> ```

`Deallocate a ...`
___
*[Pal/include/pal/pal.h, line 290 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwzgD2haI2bAM27ZM:-MxIwzgD2haI2bAM27ZN:b7jfhp5) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L290)):*
> ```objc
> 
> /*!
>  * \brief Blocks until a new connection is accepted and returns the PAL handle for the connection.
> ```

`Block ... and return ...`
___
*[Pal/include/pal/pal.h, line 368 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxMG53bP6eZaSby6v:-MxIxMG53bP6eZaSby6w:b2ah49k) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L368)):*
> ```objc
>  * \brief Unmap virtual memory that is backed by a file stream.
>  *
>  * `addr` and `size` must be aligned at the allocation alignment
> ```

Please add a dot here.
___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxIxTs09KyFnDQprxiZ:bxu5h4f) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
> ```objc
>  * \brief Send a PAL handle over another handle.
>  *
>  * Currently, the handle that is used to send cargo must be a process handle.
> ```

Shouldn't this sentence be after all doxygen stuff?
___
*[Pal/include/pal/pal.h, line 402 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxZ8yCLB6vSAK1juz:-MxIxZ8yCLB6vSAK1jv-:bxu5h4f) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L402)):*
> ```objc
>  * \brief This API receives a handle over another handle.
>  *
>  * TODO: document usage and parameters.
> ```

Shouldn't this sentence be after all doxygen stuff?
___
*[Pal/include/pal/pal.h, line 490 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxhQP9HooE1Bh5acp:-MxIxhQP9HooE1Bh5acq:b-7ua8tj) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L490)):*
> ```objc
> 
> /*!
>  * \brief Sets the CPU affinity of a thread.
> ```

`Set`
___
*[Pal/include/pal/pal.h, line 493 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxg2g5dbNlA5T6AnZ:-MxIxg2g5dbNlA5T6An_:bxu5h4f) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L493)):*
> ```objc
>  *
>  * All bit positions exceeding the count of host CPUs are ignored. Returns an error if no CPUs were
>  * selected.
> ```

Shouldn't this sentence be after all doxygen stuff?
___
*[Pal/include/pal/pal.h, line 504 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxl1T0JXFKC3OXmB8:-MxIxl1T0JXFKC3OXmB9:b-7uhwnv) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L504)):*
> ```objc
> 
> /*!
>  * \brief Gets the CPU affinity of a thread.
> ```

`Get`
___
*[Pal/include/pal/pal.h, line 508 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxnX93pC3nEg6RM9Z:-MxIxnX93pC3nEg6RM9_:bxu5h4f) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L508)):*
> ```objc
>  * This function assumes that \a cpumask_size is valid and greater than 0. Also, \a cpumask_size
>  * must be able to fit all the processors in the host and must be aligned by sizeof(long). For
>  * example, if the host supports 4 CPUs, \a cpumask_size should be 8 bytes.
> ```

Shouldn't this sentence be after all doxygen stuff?
___
*[Pal/include/pal/pal.h, line 666 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIy2YH9C7Ip5XF_Vd9:-MxIy2YH9C7Ip5XF_VdA:bb71nyg) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L666)):*
> ```objc
>  * \param[out] buffer  Output buffer.
>  * \param[in]  size    \p buffer size.
>  * 
> ```

Oops
___
*[Pal/include/pal/pal.h, line 711 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIy8XO3BVJpMlv3vsP:-MxIy8XO3BVJpMlv3vsQ:b-zg1e9b) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L711)):*
> ```objc
>  *
>  * The caller may specify `*user_report_data_size`, `*target_info_size`, and `*report_size` as 0
>  * and other fields as NULL to get PAL-enforced sizes of these three structs.
> ```

Should these sentences be below all doxygen?
___
*[Pal/include/pal/pal.h, line 739 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIyBZt6gRi0ibb_SHX:-MxIyBZu354bQe5H-T8R:b-zg1e9b)  [...]

2022-03-04 08:35 UTC, pwmarcz requested changes
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5ZEQDJ15b1eCeRDU:-MxIzkdwAs1WcJD0YBCd:b-wuuu14) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_fs_pseudo.h#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say we have not settled on `\return` vs `\returns`? https://github.com/gramineproject/gramine/pull/420/files -- that PR uses `\returns` everywhere, so we should stick with it.
</blockquote></details>

Yes, I think we decided at some point that `\returns` reads smoother.
___
*[LibOS/shim/include/shim_process.h, line 95 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ0Rmg5j2YcjXP4o1x:-MxJ0Rmg5j2YcjXP4o1y:b9fhfco) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_process.h#L95)):*
> ```objc
>  * \param pid  PID of the process to check.
>  *
>  * \returns `true` if the process \p pid is found in the zombie list of `g_process`.
> ```

IMO this was better as-is. It's good to have `\returns` where it's not obvious _which_ thing is returned, or in which format. This paragraph talks more about the _behavior_ (and the "format" of the return value is pretty obvious).
___
*[LibOS/shim/include/shim_signal.h, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ-OjI1tmZuOJfgGqn:-MxJ-OjI1tmZuOJfgGqo:b-ulbf5x) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_signal.h#L120)):*
> ```objc
>  * \param use_altstack  True if alternative stack should be used.
>  *
>  * \returns value to be used as a new stack pointer in the signal handler, depending on the current
> ```

I think we wrap sections like this so that the description is all indented to the right of `\returns`.

But I don't think it's appropriate to convert this whole paragraph to a `\returns`, it's too long. If you want to have a `\returns`, use it as a shorter summary:

```c
/*
 * ...
 * \returns New stack pointer.
 * 
 * Returns value to be used as a new stack pointer in the signal handler, depending on the current
 * thread's settings.
 */
```
___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxJ2Ein5P8g4U23BSnY:b-wqrpo5) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know it's more technically correct that way, but it seemed overly long to me ("on function call should contain"). Any ideas how to make it precise without that long boilerplate?
</blockquote></details>

I'd even say "On success, will be set to the number of bytes read".

These inout params are ugly, let's get rid of them sometime...
___
*[Pal/include/pal/pal.h, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ1HlE8eZi3YrSu3vQ:-MxJ1HlF9JXlDDJR1JYT:b-4f5eja) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L156)):*
> ```objc
>  * \brief Allocate virtual memory for the library OS and zero it out.
>  *
>  * \param[in,out] addr_ptr    `*addr_ptr` can be any valid address aligned at the allocation
> ```

Too long! How about:

```c
/*
 * \param[in,out] addr_ptr  `*addr_ptr` should contain requested address, or NULL. On success, 
                             it will be set to the allocated address.
 ...
 */
```

And then move this longer description of function behavior to a paragraph below.


<!-- Sent from Reviewable.io -->

2022-03-04 11:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 6 of 11 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/include/shim_ipc.h, line 60 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIyNzI6xU8B2H4NbwU:-MxJa5yu7wi_Sv0BUl9q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_ipc.h#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Dot?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIyOy684VXbiI8CfH3:-MxJaFMP52sCCSDmCAvP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Dot?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_signal.h, line 120 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ-OjI1tmZuOJfgGqn:-MxJadl68VEzdPA84Hqu:b-qghcsc) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_signal.h#L120)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think we wrap sections like this so that the description is all indented to the right of `\returns`.

But I don't think it's appropriate to convert this whole paragraph to a `\returns`, it's too long. If you want to have a `\returns`, use it as a shorter summary:

```c
/*
 * ...
 * \returns New stack pointer.
 * 
 * Returns value to be used as a new stack pointer in the signal handler, depending on the current
 * thread's settings.
 */
```
</blockquote></details>

Yes, we indent this way, I just missed it :) Anyways, reverted.
___
*[LibOS/shim/include/shim_signal.h, line 162 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwRul1CAfTixEuRFi:-MxJbTWvC_Eg9dX8DZ9u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_signal.h#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`\returns`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 299 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwe1w4Q5e3e7hMvIS:-MxJbevO8SjT2SMJ92rM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/LibOS/shim/include/shim_thread.h#L299)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
\returns `0` on success, negative error code on failure.
```
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxJf9Vb7WXNZHu1CU4k:b-s77mmg) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'd even say "On success, will be set to the number of bytes read".

These inout params are ugly, let's get rid of them sometime...
</blockquote></details>

Done (but still open to changes if Borys insists on the other version).
___
*[Pal/include/pal/pal.h, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ1HlE8eZi3YrSu3vQ:-MxJdERt6E9JlOfxepuw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L156)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Too long! How about:

```c
/*
 * \param[in,out] addr_ptr  `*addr_ptr` should contain requested address, or NULL. On success, 
                             it will be set to the allocated address.
 ...
 */
```

And then move this longer description of function behavior to a paragraph below.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 171 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwrwGEbAo2TCY0CzP:-MxJdNNe84zkMummbjiA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Deallocate a ...`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 290 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIwzgD2haI2bAM27ZM:-MxJecSS6A9NOaXWhgtW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L290)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Block ... and return ...`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 368 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxMG53bP6eZaSby6v:-MxJgIwIEPcNZt6za51Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L368)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot here.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxJgaRLDQ1ct2xAeTKM:b-o4wydd) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this sentence be after all doxygen stuff?
</blockquote></details>

Fixed, although there are more problems here: this sentence should actually be at the first argument, which is missing from the `\param` list, but I'm deeply confused by this description and semantics of this function, so no idea how to fix it.
It states "Send a PAL handle over another handle" and "the handle that is used to send cargo must be a process handle" at the same time. So, is `handle` parameter the destination "address" or the pipe to use for sending?
___
*[Pal/include/pal/pal.h, line 402 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxZ8yCLB6vSAK1juz:-MxJhHhVBDA0OY8GrVGd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L402)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this sentence be after all doxygen stuff?
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 490 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxhQP9HooE1Bh5acp:-MxJhKN6Eq8Fz7yJN_vo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L490)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Set`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 493 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxg2g5dbNlA5T6AnZ:-MxJhQiWB8RS9AekrPr0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L493)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this sentence be after all doxygen stuff?
</blockquote></details>

Done.
___
*[Pal/ [...]

2022-03-04 12:05 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxJoB6H-IJ4rCUaZ0-L:bizb5ea) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Fixed, although there are more problems here: this sentence should actually be at the first argument, which is missing from the `\param` list, but I'm deeply confused by this description and semantics of this function, so no idea how to fix it.
It states "Send a PAL handle over another handle" and "the handle that is used to send cargo must be a process handle" at the same time. So, is `handle` parameter the destination "address" or the pipe to use for sending?
</blockquote></details>

The `handle` parameter is the pipe to use for sending (of PAL type `process`). This pipe contains the destination address (the child process) in itself.

The `cargo` parameter is a PAL handle to be marshalled and sent to the destination.


<!-- Sent from Reviewable.io -->

2022-03-04 12:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH5ZEQDJ15b1eCeRDU:-MxJlqCA2cY8i0hrqGNF:b-q444ql) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/LibOS/shim/include/shim_fs_pseudo.h#L159)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, I think we decided at some point that `\returns` reads smoother.
</blockquote></details>

I don't remember any explicit discussions about it (and there is no in #420).

Seems like everybody prefers `\returns`, so it's settled then
___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxJnpuR62wImwTYo92U:b-toeexi) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
> Done (but still open to changes if Borys insists on the other version).

How about simply `Cointains size of \p buffer.` as the first sentence?
> These inout params are ugly, let's get rid of them sometime...

I disagree, they are very handy and easy to use when you write a loop (to make sure all bytes are written).
___
*[Pal/include/pal/pal.h, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ1HlE8eZi3YrSu3vQ:-MxJnKEg8RHH5D1k91Nb:bnwwbr5) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NP: no comma before `or`


<!-- Sent from Reviewable.io -->

2022-03-04 12:43 UTC, pwmarcz approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-03-04 12:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 10 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/include/pal/pal.h, line 307 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7YFm-xl-d0hWv9D_:-MxJxs7i-3V5pGuPHVF6:b-70jbh) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L307)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Done (but still open to changes if Borys insists on the other version).

How about simply `Cointains size of \p buffer.` as the first sentence?
> These inout params are ugly, let's get rid of them sometime...

I disagree, they are very handy and easy to use when you write a loop (to make sure all bytes are written).
</blockquote></details>

Done. I also don't hate in+out args, mostly because other solutions would probably be uglier.
___
*[Pal/include/pal/pal.h, line 328 at r1](https://reviewable.io/reviews/gramineproject/gramine/439#-MxH7fVEABGsBvSvihvT:-MxJy3DB6Z6rzjZOq_4g:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/47c25ba4041abfda5068b4c4191c9fc5882f9f5a/Pal/include/pal/pal.h#L328)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxJ1HlE8eZi3YrSu3vQ:-MxJxiNY9jKINKe2EeTQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L156)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: no comma before `or`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxJyHdk3Q-_TWJcqBPk:b-7v6ra3) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
> pipe to use for sending (of PAL type `process`).

Wait, so it's a pipe or a process handle? I'm confused.


<!-- Sent from Reviewable.io -->

2022-03-04 12:56 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxK-1FkAnHWpEEHVYbW:b7fmy0e) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> pipe to use for sending (of PAL type `process`).

Wait, so it's a pipe or a process handle? I'm confused.
</blockquote></details>

I think process handle is a pipe underneath.


<!-- Sent from Reviewable.io -->

2022-03-04 13:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxK6shw6MD5DQ16TOFv:b-qfs86g) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think process handle is a pipe underneath.
</blockquote></details>

It is a process handle. But the process handle is nothing more than a pipe (it uses the host pipe underneath, as Borys mentioned). In other words, the process handle is a pipe with a fancy name -- for no specific reason other than to easily distinguish it from other pipes.


<!-- Sent from Reviewable.io -->

2022-03-04 14:13 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 9 of 14 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/include/pal/pal.h, line 391 at r2](https://reviewable.io/reviews/gramineproject/gramine/439#-MxIxTs09KyFnDQprxiY:-MxKBlQc3ynGqOswr3Tv:b-ea42a6) ([raw file](https://github.com/gramineproject/gramine/blob/6c0340b7282f0641c1432def24a61b99ac780e8a/Pal/include/pal/pal.h#L391)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It is a process handle. But the process handle is nothing more than a pipe (it uses the host pipe underneath, as Borys mentioned). In other words, the process handle is a pipe with a fancy name -- for no specific reason other than to easily distinguish it from other pipes.
</blockquote></details>

Ok, check the new version.


<!-- Sent from Reviewable.io -->

2022-03-04 14:33 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-04 14:36 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-07 07:32 UTC, dimakuv requested changes
> Reviewed 2 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/pal_internal.h, line 184 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHSRSBuoUAPi2msY7:-MxYHSRSBuoUAPi2msY8:b-f9420p) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal_internal.h#L184)):*
> ```objc
> int _DkStreamGetName(PAL_HANDLE handle, char* buf, size_t size);
> const char* _DkStreamRealpath(PAL_HANDLE hdl);
> int _DkSendHandle(PAL_HANDLE target_process, PAL_HANDLE cargo);
> ```

Aren't you supposed to change this arg name in all PALs?
___
*[Pal/include/pal/pal.h, line 393 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHO6kBCLiw9bI2qVC:-MxYHO6kBCLiw9bI2qVD:b7vpwhi) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal/pal.h#L393)):*
> ```objc
>  * \brief Send a PAL handle to a process.
>  *
>  * \param handle  The handle to the target process where \p cargo will be sent.
> ```

The param name is wrong (`handle` -> `target_process`)
___
*[Pal/include/pal/pal.h, line 407 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHe8g3p87nOtK-Qoi:-MxYHe8g3p87nOtK-Qoj:b-joyxxz) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal/pal.h#L407)):*
> ```objc
>  * TODO: document usage and parameters.
>  */
> int DkReceiveHandle(PAL_HANDLE handle, PAL_HANDLE* cargo);
> ```

If you're fixing `DkSendHandle`, then you must also fix this one (similarly).


<!-- Sent from Reviewable.io -->

2022-03-07 11:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 9 of 15 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/include/pal_internal.h, line 184 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHSRSBuoUAPi2msY7:-MxYz7mz-1IasFB8DlFt:b-a4wcvi) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal_internal.h#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't you supposed to change this arg name in all PALs?
</blockquote></details>

Oops. Done.
___
*[Pal/include/pal/pal.h, line 393 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHO6kBCLiw9bI2qVC:-MxYzP1-EEJz7lhM71o1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal/pal.h#L393)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The param name is wrong (`handle` -> `target_process`)
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 407 at r5](https://reviewable.io/reviews/gramineproject/gramine/439#-MxYHe8g3p87nOtK-Qoi:-MxZ1oSPDqqDiVTUYM_-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1f65c037264d8ff99092207afed44f24a0387937/Pal/include/pal/pal.h#L407)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

If you're fixing `DkSendHandle`, then you must also fix this one (similarly).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 12:30 UTC, dimakuv requested changes
> Reviewed 3 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 12 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Pal/src/db_streams.c, line 512 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZLr-X-M3kdWUJsNEW:-MxZLr-YEWZ2T0dTLZ0m:bl7phmn) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/db_streams.c#L512)):*
> ```C
>     }
> 
>     return _DkSendHandle(target_process, cargo);
> ```

But you don't change the name of the argument of this PAL-specific function. Is this on purpose?
___
*[Pal/src/db_streams.c, line 521 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZLvGC-zWfDbvHqWlM:-MxZLvGC-zWfDbvHqWlN:bl7phmn) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/db_streams.c#L521)):*
> ```C
> 
>     *out_cargo = NULL;
>     return _DkReceiveHandle(source_process, out_cargo);
> ```

But you don't change the name of the argument of this PAL-specific function. Is this on purpose?


<!-- Sent from Reviewable.io -->

2022-03-07 12:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 12 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[Pal/src/db_streams.c, line 512 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZLr-X-M3kdWUJsNEW:-MxZN0Ay1MSXRbkEF_HH:b-xx7f40) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/db_streams.c#L512)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you don't change the name of the argument of this PAL-specific function. Is this on purpose?
</blockquote></details>

Hmm? I did change it?


<!-- Sent from Reviewable.io -->

2022-03-07 12:56 UTC, dimakuv approved these changes
> Reviewed 3 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/src/db_streams.c, line 512 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZLr-X-M3kdWUJsNEW:-MxZRjV7A_V70t9879xb:bdbxuin) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/db_streams.c#L512)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm? I did change it?
</blockquote></details>

Ah, Reviewable tricked me :) It doesn't show the newly-added file in fixup commits. Now I see.


<!-- Sent from Reviewable.io -->

2022-03-07 14:07 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_streams.c, line 303 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZgPyM62HbWv5xefye:-MxZgPyN0QhMdf6b-8jP:baa5568) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/host/Linux-SGX/db_streams.c#L303)):*
> ```C
> }
> 
> /* If `source_process` has an SSL context (i.e., its stream is encrypted), then cargo is sent
> ```

Nitpick: is this comment important? Maybe the mention of "possibly encrypted" in the code below is enough. Same for `_DkSendHandle` above.


<!-- Sent from Reviewable.io -->

2022-03-07 16:50 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-03-07 22:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: 14 of 15 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_streams.c, line 303 at r6](https://reviewable.io/reviews/gramineproject/gramine/439#-MxZgPyM62HbWv5xefye:-MxaXRy52EW2Mu4ykN9h:b-6j135x) ([raw file](https://github.com/gramineproject/gramine/blob/3f438ea6e7c0d83f749f877d0c9c958a7cfcfdc3/Pal/src/host/Linux-SGX/db_streams.c#L303)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nitpick: is this comment important? Maybe the mention of "possibly encrypted" in the code below is enough. Same for `_DkSendHandle` above.
</blockquote></details>

Fine with me, will drop it.


<!-- Sent from Reviewable.io -->

2022-03-07 23:26 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-03-08 08:25 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-03-08 09:57 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/439)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-08 10:01 UTC, merged