[LibOS] Pass file offset to `read` and `write` callbacks
gramineproject/gramine pull request #449
Opened 2022-03-09 14:49 UTC by pwmarcz

## Description of the changes 

Instead of using the handle position, `read` and `write` receive file position as a parameter (and might choose to update it). This is a similar design to Linux internals.

As a result, there's no need to emulate operations like `pread` using `seek`, and filesystem callbacks can be simpler.

This is in preparation for adding another filesystem (for protected files).

## How to test this PR? 

CI.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/449)

2022-03-10 08:16 UTC, dimakuv requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_handle.h, line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-MxmoqQf-tqBp9gmwHHN:-MxmoqQf-tqBp9gmwHHO:b-syi38) ([raw file](https://github.com/gramineproject/gramine/blob/df038d82705bef4f3e0b6aa9bf8262cc11c2d250/LibOS/shim/include/shim_handle.h#L235)):*
> ```objc
>     /* Lock for handle position (`pos`). Intended for operations that change the position (e.g.
>      * `read`, `seek` but not `pread`). This lock should be taken *before* `shim_handle.lock` and
>      * `shim_inode.lock`. */
> ```

Why can't we protect `pos` via `shim_handle.lock`? Why this complexity of a new lock? For speed?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 364 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-MxmrAWZ0ZiD_D2XkwIR:-MxmrAWZ0ZiD_D2XkwIS:b-gi0ozf) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/LibOS/shim/src/fs/chroot/fs.c#L364)):*
> ```C
>         goto out;
>     }
>     assert(count <= actual_count);
> ```

How did this work before? Is it because we always hit the case `count == actual_count`?
___
*[LibOS/shim/src/sys/shim_file.c, line 509 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-Mxmsmed3XHmqKlXhUb9:-Mxmsmed3XHmqKlXhUbA:b-b8ii6m) ([raw file](https://github.com/gramineproject/gramine/blob/df038d82705bef4f3e0b6aa9bf8262cc11c2d250/LibOS/shim/src/sys/shim_file.c#L509)):*
> ```C
> 
>     if (offset) {
>         *offset = pos_in;
> ```

Maybe we should keep the comment? The behavior of `sendfile()` is not that obvious. (Maybe a shorter comment would do.)


<!-- Sent from Reviewable.io -->

2022-03-10 13:47 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: 13 of 14 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_handle.h, line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-MxmoqQf-tqBp9gmwHHN:-MxnsWgj3vVc6ucmzo7q:b-9nwhnb) ([raw file](https://github.com/gramineproject/gramine/blob/df038d82705bef4f3e0b6aa9bf8262cc11c2d250/LibOS/shim/include/shim_handle.h#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why can't we protect `pos` via `shim_handle.lock`? Why this complexity of a new lock? For speed?
</blockquote></details>

`shim_handle.lock` is not compatible with the current use:

* during `read` syscall, we want exclusive access for the whole `read` callback,
* during `readv` syscall, we want exclusive access *during multiple `read` callbacks* (since the whole `readv` is supposed to be atomic),
* during `pread` syscall, we should allow multiple `read` callbacks at the same time.

To allow simultaneous `pread` syscalls, we cannot take `shim_handle.lock` for the whole `read` callback.

I we don't care about `pread`, we could use `shim_handle.lock`, but to ensure `readv` is atomic, the *caller* (not the callback) would have to take the lock. However, as discussed in one of the earlier PRs (https://github.com/gramineproject/gramine/pull/297#pullrequestreview-870948537), we want `shim_handle.lock` to be the last lock in the hierarchy. That would mean the callbacks cannot take *any* locks (e.g. they cannot lock the inode to update metadata).

AFAICT, Linux does a similar thing: [struct file](https://elixir.bootlin.com/linux/latest/source/include/linux/fs.h#L962) has `f_lock` and `f_pos_lock` fields.

(Basically, I trust that design, because I tried to come up with something simpler and I failed).
___
*[LibOS/shim/src/fs/chroot/fs.c, line 364 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-MxmrAWZ0ZiD_D2XkwIR:-MxnxmreECF9lH8-LxlJ:b-f30awt) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/LibOS/shim/src/fs/chroot/fs.c#L364)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How did this work before? Is it because we always hit the case `count == actual_count`?
</blockquote></details>

Yeah, I think so... It's easier to hit `actual_count < count` during read (because of EOF), but this is write.
___
*[LibOS/shim/src/sys/shim_file.c, line 509 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-Mxmsmed3XHmqKlXhUb9:-Mxo-l7l011ROfLtrH7t:b-yj1hik) ([raw file](https://github.com/gramineproject/gramine/blob/df038d82705bef4f3e0b6aa9bf8262cc11c2d250/LibOS/shim/src/sys/shim_file.c#L509)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should keep the comment? The behavior of `sendfile()` is not that obvious. (Maybe a shorter comment would do.)
</blockquote></details>

Right. It's actually more tricky: I should also update the offset in file handle.

The relevant part of manpage is a bit verbose, but I'd rather add it in full than risk paraphrasing it.


<!-- Sent from Reviewable.io -->

2022-03-11 07:41 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_handle.h, line 235 at r1](https://reviewable.io/reviews/gramineproject/gramine/449#-MxmoqQf-tqBp9gmwHHN:-MxrtrBt5knesskfsJtR:b-e1jt32) ([raw file](https://github.com/gramineproject/gramine/blob/df038d82705bef4f3e0b6aa9bf8262cc11c2d250/LibOS/shim/include/shim_handle.h#L235)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`shim_handle.lock` is not compatible with the current use:

* during `read` syscall, we want exclusive access for the whole `read` callback,
* during `readv` syscall, we want exclusive access *during multiple `read` callbacks* (since the whole `readv` is supposed to be atomic),
* during `pread` syscall, we should allow multiple `read` callbacks at the same time.

To allow simultaneous `pread` syscalls, we cannot take `shim_handle.lock` for the whole `read` callback.

I we don't care about `pread`, we could use `shim_handle.lock`, but to ensure `readv` is atomic, the *caller* (not the callback) would have to take the lock. However, as discussed in one of the earlier PRs (https://github.com/gramineproject/gramine/pull/297#pullrequestreview-870948537), we want `shim_handle.lock` to be the last lock in the hierarchy. That would mean the callbacks cannot take *any* locks (e.g. they cannot lock the inode to update metadata).

AFAICT, Linux does a similar thing: [struct file](https://elixir.bootlin.com/linux/latest/source/include/linux/fs.h#L962) has `f_lock` and `f_pos_lock` fields.

(Basically, I trust that design, because I tried to come up with something simpler and I failed).
</blockquote></details>

Thanks. I understood the point about " the caller (not the callback) would have to take the lock" and the problem with this ("`shim_handle.lock` to be the last lock"). An interesting problem.
___
*[LibOS/shim/src/sys/shim_file.c, line 474 at r2](https://reviewable.io/reviews/gramineproject/gramine/449#-Mxrulb88ts-KttYPR_Y:-Mxrulb88ts-KttYPR_Z:b-4ihk23) ([raw file](https://github.com/gramineproject/gramine/blob/26a4eeeebd5dcf8bda0b080eb5a12e75ad4fcb67/LibOS/shim/src/sys/shim_file.c#L474)):*
> ```C
>         pos_in = in_hdl->pos;
>         unlock(&in_hdl->pos_lock);
>     }
> ```

Looks like we don't have any test that would use `sendfile()` with `offset = NULL` and then verifies the position in the file? (Otherwise your first iteration of this PR would fail.)

Could you check if maybe we can enable some `sendfile` test in LTP that checks this? And/or write a new LibOS test?


<!-- Sent from Reviewable.io -->

2022-03-11 19:00 UTC, mkow approved these changes
> Reviewed 13 of 14 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_file.c, line 448 at r3](https://reviewable.io/reviews/gramineproject/gramine/449#-MxuHcFd9HSTJZAMog0t:-MxuHcFd9HSTJZAMog0u:b-qrpih9) ([raw file](https://github.com/gramineproject/gramine/blob/903cf98b3ea2edb2cc98924287df07111679e6f9/LibOS/shim/src/sys/shim_file.c#L448)):*
> ```C
> 
>     /*
>      * `man sendfile` says:
> ```

Not blocking, but not sure if we should quote `man` as a guidance on how syscalls work - it describes the libc wrappers which often have different semantics and often not all the differences/nuances are described in the "C library/kernel differences" section.


<!-- Sent from Reviewable.io -->

2022-03-14 08:42 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-14 09:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/sys/shim_file.c, line 448 at r3](https://reviewable.io/reviews/gramineproject/gramine/449#-MxuHcFd9HSTJZAMog0t:-My6d0Kd1D3M1AVC-SDz:b-gno2us) ([raw file](https://github.com/gramineproject/gramine/blob/903cf98b3ea2edb2cc98924287df07111679e6f9/LibOS/shim/src/sys/shim_file.c#L448)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not blocking, but not sure if we should quote `man` as a guidance on how syscalls work - it describes the libc wrappers which often have different semantics and often not all the differences/nuances are described in the "C library/kernel differences" section.
</blockquote></details>

OK. I'm not against quoting the man page in general, because often it's the _only_ piece of documentation we have, and if the explanation is well-written and accurate, it might be better to provide it verbatim.

But here, I think a rephrasing will be much simpler.


<!-- Sent from Reviewable.io -->

2022-03-14 09:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-14 11:48 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-03-14 12:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-03-14 12:50 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/449)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-14 13:17 UTC, merged