[Pal/Linux-SGX] Update tools to use IAS API v4
gramineproject/gramine pull request #453
Opened 2022-03-10 12:57 UTC by dimakuv

## Description of the changes 

Previously, Gramine tools (including RA-TLS) used IAS API v3. This version is deprecated and will be EOLed on 16. August 2022. This commit updates Gramine to IAS API v4; the only difference is that Advisory URL & IDs are returned in HTTP response body (in v3, they are returned in HTTP response headers).

## How to test this PR? 

I tested manually on my machine.

1. Test with `ra-tls-mbedtls`:
```
~/gramineproject/gramine/CI-Examples/ra-tls-mbedtls$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
        RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_EPID_API_KEY=<my-key> ./client epid
  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake...
IAS report: signature verified correctly
IAS report: allowing quote status GROUP_OUT_OF_DATE
            [ advisory URL: https://security-center.intel.com ]
            [ advisory IDs: ["INTEL-SA-00477", "INTEL-SA-00381", "INTEL-SA-00389", "INTEL-SA-00320", "INTEL-SA-00329", "INTEL$
SA-00220", "INTEL-SA-00270", "INTEL-SA-00293", "INTEL-SA-00233", "INTEL-SA-00203", "INTEL-SA-00106", "INTEL-SA-00115", "INTEL$
SA-00135"] ]
 ok
  . Verifying peer X.509 certificate... ok
```

2. Test with a pre-generated EPID quote of some SGX enclave on my machine and Gramine tools:
```
$ gramine-sgx-ias-request --api-key <my-key>report --quote-path quote-epid.dat \
        --report-path report.dat --sig-path sig.dat  --cert-path cert.dat
IAS submission successful

$ gramine-sgx-ias-verify-report --report-path report.dat --sig-path sig.dat --allow-outdated-tcb
IAS report: signature verified correctly
IAS report: allowing quote status GROUP_OUT_OF_DATE
            [ advisory URL: https://security-center.intel.com ]
            [ advisory IDs: ["INTEL-SA-00477", "INTEL-SA-00381", "INTEL-SA-00389", "INTEL-SA-00320", "INTEL-SA-00329", "INTEL-SA-00220", "INTEL-SA-00270", "INTEL-SA-00293", "INTEL-SA-00233", "INTEL-SA-00203", "INTEL-SA-00106", "INTEL-SA-00115", "INTEL-SA-00135"] ]
verify_quote_body_enclave_attributes: Quote: DEBUG bit in enclave attributes is set
```

2022-03-10 13:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/453#-MxnuN-e5WuP_qjSnM6N:-MxnuN-fDl0eEslhKhmE:b-edtop5) (no related file):*
References:
- https://www.intel.com/content/dam/develop/public/us/en/documents/sgx-attestation-api-spec.pdf -- new version (v4)
- https://api.trustedservices.intel.com/documents/IAS-API-Spec-rev-5.0.pdf -- old version (v3)

In particular, compare sections 3.2.

---


<!-- Sent from Reviewable.io -->

2022-03-11 22:17 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuzgmB2xbc-epG6Kvb:-MxuzgmB2xbc-epG6Kvc:bfhm1d2) (no related file):*
> $ gramine-sgx-ias-request --api-key <my-key>report --quote-path quote-epid.dat \

Something's wrong here? (near "report") But I guess it's just "report" which should be moved to the beginning of the cmdline?

---
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-MxuOycY3RW1clb8V4j-:b-dyf7od) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
> ```reStructuredText
>       Path to save IAS certificate to (optional).
> 
>    .. option:: -a, --advisory-path
> ```

What's the reason to remove this option? (I mean, I'm not against, just asking for the reason)
Also, the commit message doesn't mention it.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 253 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxulQGxBDOaOqGExMcM:-MxulQGxBDOaOqGExMcN:b4ueo54) ([raw file](https://github.com/gramineproject/gramine/blob/31451470a2385f80bc761a954912a688d2dbfbc9/Pal/src/host/Linux-SGX/tools/common/attestation.c#L253)):*
> ```C
>         cJSON* ids_node = cJSON_GetObjectItem(json, "advisoryIDs");
>         if (ids_node && ids_node->type == cJSON_Array) {
>             char* ids_str = cJSON_Print(ids_node);
> ```

This may fail.



_Code quote:_
```C
cJSON_Print(ids_node)
```
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 219 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxutocSA10SeGRGa0yL:-MxutocSA10SeGRGa0yM:b-g7pwan) ([raw file](https://github.com/gramineproject/gramine/blob/31451470a2385f80bc761a954912a688d2dbfbc9/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L219)):*
> ```C
>     /* below function verifies `isvEnclaveQuoteStatus` returned in the IAS attestation report; it
>      * fails if the SGX quote is invalid or if the EPID group/private key/signature is revoked (see
>      * www.intel.com/content/dam/develop/public/us/en/documents/sgx-attestation-api-spec.pdf) */
> ```

please add "https://"


<!-- Sent from Reviewable.io -->

2022-03-14 09:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: 4 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuzgmB2xbc-epG6Kvb:-My6alCu4SRtxQQqp6th:bfiai0n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> $ gramine-sgx-ias-request --api-key <my-key>report --quote-path quote-epid.dat \

Something's wrong here? (near "report") But I guess it's just "report" which should be moved to the beginning of the cmdline?
</blockquote></details>

Done. Yes, incorrect copy-paste :)

---
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-My6dPOUArycy9qcb2PH):*
I will add a second para like this:
```
IAS advisory URL & IDs were previously returned in HTTP response *headers*, so they had to be
extracted separately and saved in a separate file by `gramine-sgx-ias-request` utility. Now they
are returned in the HTTP reponse body (more specifically, in the *IAS report*), so they are extracted
together with the rest of the information into the `--report-path` file. Thus, the `--advisory-path`
command-line option is removed from `gramine-sgx-ias-request`.
```
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-My6cWzW2ngIHlwNwIRx:b-5ab5sw) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the reason to remove this option? (I mean, I'm not against, just asking for the reason)
Also, the commit message doesn't mention it.
</blockquote></details>

These IAS security advisories were previously returned in HTTP response *headers*, so they had to be extracted separately and saved in a separate file (in IAS v3).

Now these IAS security advisories are returned in the HTTP reponse body (more specifically, in the *IAS report*). So they are extracted together with the rest of the information in the `--report-path` file (in IAS v4).

You can see it in my example in the PR description:
- `gramine-sgx-ias-request` utility saves the IAS security advisories into the `report.dat` file
-  `gramine-sgx-ias-verify-report` utility reads these IAS security advisories this `report.dat` file
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 253 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxulQGxBDOaOqGExMcM:-My6c1sp1Sw97ualph89:b-81mnwe) ([raw file](https://github.com/gramineproject/gramine/blob/31451470a2385f80bc761a954912a688d2dbfbc9/Pal/src/host/Linux-SGX/tools/common/attestation.c#L253)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This may fail.
</blockquote></details>

Done. I didn't want to `goto fail` on this failure, so decided to just add a check.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c, line 219 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxutocSA10SeGRGa0yL:-My6bWRH791MYChGLTq7:b-3050s8) ([raw file](https://github.com/gramineproject/gramine/blob/31451470a2385f80bc761a954912a688d2dbfbc9/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c#L219)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please add "https://"
</blockquote></details>

Done. I didn't want to get over 100-char limit.


<!-- Sent from Reviewable.io -->

2022-03-14 13:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-My7aNfv3Nh1pG-RpSDo:b-na5z4x) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't get this. How we got the information is totally independent of what ways to save/display it we offer to the user.
</blockquote></details>

Now I don't understand you. Previously, in IAS v3, advisories (URL & IDs) were provided separately. Now, in IAS v4, advisories are embedded in another object (IAS attestation report). So there is no need now to have a separate file.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 253 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxulQGxBDOaOqGExMcM:-My7bFx-1wJHwK-cxhr3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/31451470a2385f80bc761a954912a688d2dbfbc9/Pal/src/host/Linux-SGX/tools/common/attestation.c#L253)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, we can't do this - in this version on OOM we will silently skip printing security issues...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 17:04 UTC, boryspoplawski reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-My8Mef51sYtpVtcErNn:b5329zc) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now I don't understand you. Previously, in IAS v3, advisories (URL & IDs) were provided separately. Now, in IAS v4, advisories are embedded in another object (IAS attestation report). So there is no need now to have a separate file.
</blockquote></details>

I think that @mkow's point is that where the IAS security advisories where extracted from does matter (it's an implementation detail), the user should get the full info (and contents of this `report.dat` are opaque to them anyway).

But I also do not understand what's the point of this discussion, i.e. is there something else to be done except adding info into commit message?


<!-- Sent from Reviewable.io -->

2022-03-14 21:57 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-My9PiHL3APoyxNfjkE0:b-dh3hj0) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
> is there something else to be done except adding info into commit message?

It's rather a question whether or not we want to keep this functionality (i.e. allow dumping the advisories to a file). I'm neutral to it because I haven't really used this tool in a while, but maybe there are some usages.
Anyways, the discussion started because Dmitrii did "I removed this thing from the backend, so I had to remove this unrelated option from the frontend", so I asked what's going on here :)
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 256 at r3](https://reviewable.io/reviews/gramineproject/gramine/453#-My9QYjA1aDrug-5VUpj:-My9QYjA1aDrug-5VUpk:bwdd670) ([raw file](https://github.com/gramineproject/gramine/blob/4b8ced7b26b6264eee94a51a8908bdb75ec249c4/Pal/src/host/Linux-SGX/tools/common/attestation.c#L256)):*
> ```C
>             if (!ids_str) {
>                 ERROR("IAS report: out-of-memory during reading advisoryIDs\n");
>                 goto out;
> ```

You need to set `ret` when jumping there.


<!-- Sent from Reviewable.io -->

2022-03-15 08:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-MyBe1g42pTdrUlAQZvn:b-e622tq) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
> It's rather a question whether or not we want to keep this functionality (i.e. allow dumping the advisories to a file). I'm neutral to it because I haven't really used this tool in a while, but maybe there are some usages.

But we keep this functionality. Advisories are still dumped into a file, but they are dumped into an already-existing `--report-path` file. Why would we want to duplicate the functionality, and dump the advisories also in a second file?

Is it because we don't want to surprise users that the advisories file is suddenly not created anymore, and there is no `--advisory-path` option now? But I'm pretty sure nobody cares about this utility, and nobody will complain that the `--advisory-path` option was removed.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 256 at r3](https://reviewable.io/reviews/gramineproject/gramine/453#-My9QYjA1aDrug-5VUpj:-MyBdrwm3yfDb4OEN68d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b8ced7b26b6264eee94a51a8908bdb75ec249c4/Pal/src/host/Linux-SGX/tools/common/attestation.c#L256)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You need to set `ret` when jumping there.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 21:45 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-MyCpnwb7Il3UUuU7eik:b-9bd4mz) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
> Advisories are still dumped into a file, but they are dumped into an already-existing `--report-path` file.

Ah, I thought this report is binary (you call it `report.dat` in your instructions which IMO implies binary format) and that this feature originally was to dump the advisories in user-readable form. Seems it's not the case, so we can remove it.


<!-- Sent from Reviewable.io -->

2022-03-17 07:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-My6dPOUArycy9qcb2PH):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will add a second para like this:
```
IAS advisory URL & IDs were previously returned in HTTP response *headers*, so they had to be
extracted separately and saved in a separate file by `gramine-sgx-ias-request` utility. Now they
are returned in the HTTP reponse body (more specifically, in the *IAS report*), so they are extracted
together with the rest of the information into the `--report-path` file. Thus, the `--advisory-path`
command-line option is removed from `gramine-sgx-ias-request`.
```
</blockquote></details>

Done
___
*[Documentation/manpages/gramine-sgx-ias-request.rst, line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/453#-MxuOycY3RW1clb8V4iz:-MyLj6zF3HIYMI5FQ715:b-kp22kf) ([raw file](https://github.com/gramineproject/gramine/blob/7846eccb5c226e9c6aa8775058d43506c6ad7cfd/Documentation/manpages/gramine-sgx-ias-request.rst#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Advisories are still dumped into a file, but they are dumped into an already-existing `--report-path` file.

Ah, I thought this report is binary (you call it `report.dat` in your instructions which IMO implies binary format) and that this feature originally was to dump the advisories in user-readable form. Seems it's not the case, so we can remove it.
</blockquote></details>

Yeah, that's not the case.


<!-- Sent from Reviewable.io -->

2022-03-17 11:41 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/453)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-17 13:02 UTC, merged