[CI-Examples] Extend helloworld example to use secure cmdline args
gramineproject/gramine pull request #460
Opened 2022-03-16 03:05 UTC by vijaydhanraj

## Description of the changes 

This PR extends `helloworld` CI-Example to showcase the usage of passing command-line arguments securely to the application running inside the enclave. It also adds documentation on the usage of `gramine-argv-serializer` tool.

## How to test this PR? 
Please run the `helloworld` example as part of `CI-Examples`.

2022-03-16 08:27 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[CI-Examples/helloworld/helloworld.c, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGoECZEeLe2hwbfN8u:-MyGoECZEeLe2hwbfN8v:b-z6bki9) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.c#L4)):*
> ```C
> 
> int main(int argc, char* argv[]) {
>     printf("Hello, world! Your secure arguments are: \n");
> ```

Please put this new `Your secure arguments ...` string in a separate `printf()`, for better readability.
___
*[CI-Examples/helloworld/helloworld.c, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGpSjf03-Y6CozkCD_:-MyGpSjf03-Y6CozkCDa:bkqfk1u) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.c#L5)):*
> ```C
> int main(int argc, char* argv[]) {
>     printf("Hello, world! Your secure arguments are: \n");
>     for (int i = 0; i < argc; i++) {
> ```

Typically `argv[0]` is printed separately and it contains the name of the executable. So I would change your loop into two statements:
1. Print "name of the executable: " + `argv[0]`
2. Loop from 1 to `argc`, "rest of arguments: ".
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGoo650j0Lu4wzv9_y:-MyGoo650j0Lu4wzv9_z:boxavkx) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.manifest.template#L6)):*
> ```
> libos.entrypoint = "helloworld"
> loader.log_level = "{{ log_level }}"
> loader.argv0_override = "helloworld"
> ```

This is not used now, please remove.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGotsp3JWoo-gUE4V7:-MyGotsp3JWoo-gUE4V8:bhstto6) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.manifest.template#L9)):*
> ```
> 
> # Use `gramine-argv-serializer` to generate the file containing secure arguments.
> # Example: gramine-argv-serializer Gramine says hi! > helloworld_secure_args
> ```

The first argument (`argv[0]`) is typically the name of the executable (in our case, `helloworld`). I would suggest then this:
```
Example: gramine-argv-serializer helloworld Gramine says hi! > helloworld_secure_args
```
___
*[CI-Examples/helloworld/helloworld_secure_args, line 0 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGp2kXEHLKb2W45keG:-MyGp2kaEikdie2nnIYm:b-qx92z6) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld_secure_args#L0)):*
Please remove this file and add a new target in Makefile to create this file. Otherwise it's just some opaque blob, incomprehensible to a new user of Gramine.
___
*[Documentation/conf.py, line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGlvf16dxGfrDTLsHm:-MyGlvf16dxGfrDTLsHn:b4s0pvn) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/conf.py#L176)):*
> ```Python
>     ('manpages/gramine-sgx-sign', 'gramine-sgx-sign', 'Gramine SIGSTRUCT generator', [author], 1),
>     ('manpages/is-sgx-available', 'is-sgx-available', 'Check SGX compatibility', [author], 1),
>     ('manpages/gramine-argv-serializer', 'gramine-argv-serializer', 'Serialize command line arguments', [author], 1),
> ```

Please sort (so `gramine-argv-serializer` will be right-before `gramine-manifest`)
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGmTfoElAV54hF_-zC:-MyGmTfoElAV54hF_-zD:b-5bwwt8) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
> ```reStructuredText
> `gramine-argv-serializer` serializes the command line arguments and displays it
> on the terminal. Typically the output is redirected to a file which can be
> used as a trusted or a protected file and point to ``loader.argv_src_file``. For
> ```

`and point to ...` sounds weird. I suggest:
```
used as a trusted or a protected file. To use this file as a source of command line arguments
in Gramine, specify this file path in `loader.argv_src_file``.
```
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGnLcB9ncnFmYGnd-R:-MyGnLcC8Fe06CU2Szhs:bwcn2yv) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L19)):*
> ```reStructuredText
> used as a trusted or a protected file and point to ``loader.argv_src_file``. For
> more information on the usage, please refer to :doc:`../manifest-syntax`.
> ```

I would also mention this example of usage: https://github.com/gramineproject/gramine/blob/d4a218a1e2a4fade1cb4dbaa791d3a022153bb1c/LibOS/shim/test/regression/test_libos.py#L87

I guess you can just add this link and mention that this is how to use the utility from Python.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGmlLj7-oYQZQazYRX:-MyGmlLj7-oYQZQazYRY:bxp0pfl) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L33)):*
> ```reStructuredText
> 
>     $ gramine-argv-serializer Gramine says hi!
>     Graminesayshi!%
> ```

I suggest to show the example with redirection instead of this one (outputting to the terminal is confusing):
```
$ gramine-argv-serializer Gramine says hi! > gramine_secure_args.txt
```
___
*[tools/argv_serializer.c, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGn5481J96Prkz1vFD:-MyGn5481J96Prkz1vFE:b4m1dlm) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/tools/argv_serializer.c#L21)):*
> ```C
> 
> static void usage(const char* exec) {
>     printf("Usage: %s <command line arguments seperated by space>\n", exec);
> ```

`separated`
___
*[tools/argv_serializer.c, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGngF77bqUZ3N7X_gn:-MyGngF77bqUZ3N7X_go:b-dsh4px) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/tools/argv_serializer.c#L21)):*
> ```C
> 
> static void usage(const char* exec) {
>     printf("Usage: %s <command line arguments seperated by space>\n", exec);
> ```

Actually, `separated by space` is not exactly correct. Command line arguments can also be in quotes (`argument_1 "this is argument 2" argument3`). So maybe just remove the part `separated by space`? We expect users to know how to specify command-line arguments.


<!-- Sent from Reviewable.io -->

2022-03-16 10:37 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyHHsEREf5wr19tJewM:b-7zvt4m) (no related file):*
IMO `helloworld` example should be as concise as possible and **not** showcase Gramine's features. For this reason I'm against augmenting it with "secure cmdline args" usage.

That being said, maybe there is another example we can augment instead?

---


<!-- Sent from Reviewable.io -->

2022-03-16 12:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyHlXPmCMjSdGNJl6Iw:bqwgpce) (no related file):*
Actually, +1 to Borys.

> That being said, maybe there is another example we can augment instead?

I think the most obvious candidate is Nginx because all its configuration is read from the `conf/nginx-gramine.conf` file and not from the command line. So I nominate Nginx: https://github.com/gramineproject/gramine/tree/master/CI-Examples/nginx

---


<!-- Sent from Reviewable.io -->

2022-03-16 13:46 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyHxsZW-RxkKaHzvL13:b-vfkwgw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, +1 to Borys.

> That being said, maybe there is another example we can augment instead?

I think the most obvious candidate is Nginx because all its configuration is read from the `conf/nginx-gramine.conf` file and not from the command line. So I nominate Nginx: https://github.com/gramineproject/gramine/tree/master/CI-Examples/nginx
</blockquote></details>

+1, didn't we even discuss this on the call? `helloworld` should be minimal, I'd rather expand some other example, especially that we have a lot of examples where this would make sense (they even have a comment saying that production versions of them should use trusted argv).

---


<!-- Sent from Reviewable.io -->

2022-03-16 14:44 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyHmuND98jeXnI-Pee5:b-clv2ak) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, didn't we even discuss this on the call? `helloworld` should be minimal, I'd rather expand some other example, especially that we have a lot of examples where this would make sense (they even have a comment saying that production versions of them should use trusted argv).
</blockquote></details>

OK, let me augment the Nginx example and update this PR. 
@mkow Yes you did mention but I thought you wanted me to submit the PR first and then wanted to discuss further. But maybe I misunderstood.

---


<!-- Sent from Reviewable.io -->

2022-03-18 05:32 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 1 of 12 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyQMs7RBhEPdwpZsH-S:b-e89j1v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I'm pretty sure that I was against modifying the hello world example and rather wouldn't suggest implementing it if I don't like it, but I don't remember that conversation precisely.
</blockquote></details>

As suggested, I have added the trusted argv use case to `nginx` example.

I went a little further and replaced `ab` benchmark with `wrk2` as recommended in the `nginx` example readme. But with `wrk2` I did run into an issue with `gramine-direct` as well as `gramine-sgx`. I hit this assertion, https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_socket.c#L1450 with `https` use case. `http` works fine.

Since `lightpd` also uses the same script `benchmark-http.sh` which in turn uses`ab` benchmark. Tested this example with `wrk2` and Gramine fails with the below error.
```
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
```

Please note the native runs using the `wrk2` benchmark runs without any issues. I haven't spent time debugging these issues, but I can create github issues and assign it to myself for further debugging if these are not known issues.

---
___
*[CI-Examples/helloworld/helloworld.c, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGoECZEeLe2hwbfN8u:-MyQPbsV75ZHt5j8mQtD:bdv89gc) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put this new `Your secure arguments ...` string in a separate `printf()`, for better readability.
</blockquote></details>

Not applicable anymore.
___
*[CI-Examples/helloworld/helloworld.c, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGpSjf03-Y6CozkCD_:-MyQPfLCByLAFJYFck4l:bdv89gc) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.c#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typically `argv[0]` is printed separately and it contains the name of the executable. So I would change your loop into two statements:
1. Print "name of the executable: " + `argv[0]`
2. Loop from 1 to `argc`, "rest of arguments: ".
</blockquote></details>

Not applicable anymore.
___
*[Documentation/conf.py, line 176 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGlvf16dxGfrDTLsHm:-MyQRHen5kGvNJmYUhLf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/conf.py#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort (so `gramine-argv-serializer` will be right-before `gramine-manifest`)
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGmTfoElAV54hF_-zC:-MyQRp0PChXAge51eGir:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`and point to ...` sounds weird. I suggest:
```
used as a trusted or a protected file. To use this file as a source of command line arguments
in Gramine, specify this file path in `loader.argv_src_file``.
```
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGnLcB9ncnFmYGnd-R:-MyQTRtR-UZ7GdlOHWjN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also mention this example of usage: https://github.com/gramineproject/gramine/blob/d4a218a1e2a4fade1cb4dbaa791d3a022153bb1c/LibOS/shim/test/regression/test_libos.py#L87

I guess you can just add this link and mention that this is how to use the utility from Python.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGmlLj7-oYQZQazYRX:-MyQSd9UCkibEjevkdeG:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/Documentation/manpages/gramine-argv-serializer.rst#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to show the example with redirection instead of this one (outputting to the terminal is confusing):
```
$ gramine-argv-serializer Gramine says hi! > gramine_secure_args.txt
```
</blockquote></details>

Done.
___
*[tools/argv_serializer.c, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGn5481J96Prkz1vFD:-MyQTXdb5w772Wmufw45:b8wjagp) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/tools/argv_serializer.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`separated`
</blockquote></details>

Rephrased the sentence and removed `separated`.
___
*[tools/argv_serializer.c, line 21 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGngF77bqUZ3N7X_gn:-MyQTiUz0yphB61xUsLZ:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/tools/argv_serializer.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, `separated by space` is not exactly correct. Command line arguments can also be in quotes (`argument_1 "this is argument 2" argument3`). So maybe just remove the part `separated by space`? We expect users to know how to specify command-line arguments.
</blockquote></details>

Done.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGoo650j0Lu4wzv9_y:-MyQPshA0S-XpRlpHXLi:b9dby3f) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.manifest.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not used now, please remove.
</blockquote></details>

Since we are not changing the `helloworld` example, I am not sure if we want to remove this. Please let me know if you want me to remove this syntax.
___
*[CI-Examples/helloworld/helloworld.manifest.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/460#-MyGotsp3JWoo-gUE4V7:-MyQQdJlDwXHbvwN9PzV:bdv89gc) ([raw file](https://github.com/gramineproject/gramine/blob/2520ba6d5402d1066525cf715b7cdb553bd50f1b/CI-Examples/helloworld/helloworld.manifest.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The first argument (`argv[0]`) is typically the name of the executable (in our case, ` [...]

2022-03-18 07:26 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyQrzwL434ZnX8mXmr_:bkbh276) (no related file):*
>  But with wrk2 I did run into an issue with gramine-direct as well as gramine-sgx.

This is surprising, I remember that `wrk2` worked fine in all cases (direct or sgx, http or https). Something change in the meantime...

> I haven't spent time debugging these issues, but I can create github issues and assign it to myself for further debugging if these are not known issues.

@boryspoplawski is working on a complete sockets rewrite, so testing this case should be added to his plate. I would *not* touch the sockets subsystem in Gramine currently, while Borys is changing its code anyway.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtWTx-XlfbIH-RB3j:-MyQtWTx-XlfbIH-RB3k:b7ginyf) (no related file):*
For the `wrk2` change, our CI scripts must be updated to install it. Currently, our CI installs and uses `ab`: 
- https://github.com/gramineproject/gramine/blob/c2548d6ad1e47683606b15a21b90ae6bd24df623/.ci/ubuntu20.04.dockerfile#L5
- https://github.com/gramineproject/gramine/blob/c2548d6ad1e47683606b15a21b90ae6bd24df623/.ci/lib/stage-test-direct.jenkinsfile#L81

---
___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQsvuyDKaAWItFBbvK):*
Can we split this in a separate PR? It's completely orthogonal and also controversial (since HTTPS doesn't work in `wrk2`). It will be hard to review two independent commits in one PR. So please split.
___
*[CI-Examples/helloworld/helloworld.c, line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtB_SE0oU4dVDDiRd:-MyQtB_SE0oU4dVDDiRe:bflyorh) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/CI-Examples/helloworld/helloworld.c#L3)):*
> ```C
> #include <stdio.h>
> 
> int main(int argc, char* argv[]) {
> ```

Can we revert this too? Otherwise it's weird that this commit has a completely unrelated change.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuCDhE9zH6EeHVMro:-MyQuCDhE9zH6EeHVMrp:b4koran) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L21)):*
> ```reStructuredText
> For more information on the usage, please refer to :doc:`../manifest-syntax`.
> 
> To use this utility from python, please refer to,
> ```

Please remove the `,` after `refer to`
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuGbl6h1LLRrUC5z5:-MyQuGbl6h1LLRrUC5z6:bn1on2t) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L21)):*
> ```reStructuredText
> For more information on the usage, please refer to :doc:`../manifest-syntax`.
> 
> To use this utility from python, please refer to,
> ```

`To use this utility from python` -> `For an example on how to use this utility from Python`
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuOSY-KU8jJS3xqYu:-MyQuOSY-KU8jJS3xqYv:b-s05chg) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L22)):*
> ```reStructuredText
> 
> To use this utility from python, please refer to,
> https://github.com/gramineproject/gramine/blob/master/LibOS/shim/test/regression/test_libos.py
> ```

This file is huge. Please give a permalink to a particular line. I also suggest to hide the URL link itself, using the hyperlink syntax of RST.
___
*[tools/argv_serializer.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuq9sAEno6eXQtG-C:-MyQuq9sAEno6eXQtG-D:b-gzy6ep) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/tools/argv_serializer.c#L25)):*
> ```C
> 
>     if (argc == 1)
>         usage(argv[0]);
> ```

These two lines are deadcode (you have a wider check above).


<!-- Sent from Reviewable.io -->

2022-03-18 20:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyHHsEREf5wr19tJewL:-MyTVlf-0c8k3Q8CXjwT:b-ordcbj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>  But with wrk2 I did run into an issue with gramine-direct as well as gramine-sgx.

This is surprising, I remember that `wrk2` worked fine in all cases (direct or sgx, http or https). Something change in the meantime...

> I haven't spent time debugging these issues, but I can create github issues and assign it to myself for further debugging if these are not known issues.

@boryspoplawski is working on a complete sockets rewrite, so testing this case should be added to his plate. I would *not* touch the sockets subsystem in Gramine currently, while Borys is changing its code anyway.
</blockquote></details>

Sure, got it.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtWTx-XlfbIH-RB3j:-MyTXlLO1Xz86U5ZnnDc:b-2g804f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For the `wrk2` change, our CI scripts must be updated to install it. Currently, our CI installs and uses `ab`: 
- https://github.com/gramineproject/gramine/blob/c2548d6ad1e47683606b15a21b90ae6bd24df623/.ci/ubuntu20.04.dockerfile#L5
- https://github.com/gramineproject/gramine/blob/c2548d6ad1e47683606b15a21b90ae6bd24df623/.ci/lib/stage-test-direct.jenkinsfile#L81
</blockquote></details>

Done, but we need to install the wrk2 from sources. Does this need manual installation on each CI system?
 I followed the steps mentioned in this link, https://github.com/giltene/wrk2/wiki/Installing-wrk2-on-Linux to install.

---
___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQsvuyDKaAWItFBbvK):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we split this in a separate PR? It's completely orthogonal and also controversial (since HTTPS doesn't work in `wrk2`). It will be hard to review two independent commits in one PR. So please split.
</blockquote></details>

Done. Created #465 to track usage of `wrk2`.     
___
*[CI-Examples/helloworld/helloworld.c, line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtB_SE0oU4dVDDiRd:-MyTMnD93dAOp7VbxEcv:bklgit7) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/CI-Examples/helloworld/helloworld.c#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we revert this too? Otherwise it's weird that this commit has a completely unrelated change.
</blockquote></details>

yes, missed this one.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuCDhE9zH6EeHVMro:-MyT89nKC3VEmpGNWnEx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the `,` after `refer to`
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 21 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuGbl6h1LLRrUC5z5:-MyT8Bvh4zlb2bN11_3F:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`To use this utility from python` -> `For an example on how to use this utility from Python`
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuOSY-KU8jJS3xqYu:-MyT8Gp70-fsetcJft63:b-927644) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This file is huge. Please give a permalink to a particular line. I also suggest to hide the URL link itself, using the hyperlink syntax of RST.
</blockquote></details>

We might have an issue with an incorrect/stale link in the documentation when the `test_libos.py` changes. So, think it is better to just point to the file. But I have replaced the URL link with hyperlink syntax.
___
*[tools/argv_serializer.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuq9sAEno6eXQtG-C:-MyTMNXuEtiGY1fC52cf:bq1thgx) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/tools/argv_serializer.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two lines are deadcode (you have a wider check above).
</blockquote></details>

yes, removed this dead code.


<!-- Sent from Reviewable.io -->

2022-04-04 07:37 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtWTx-XlfbIH-RB3j:-MznT9s_7VXH5JfOb7Mk:b-mgdp5m) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done, but we need to install the wrk2 from sources. Does this need manual installation on each CI system?
 I followed the steps mentioned in this link, https://github.com/giltene/wrk2/wiki/Installing-wrk2-on-Linux to install.

</blockquote></details>

What do you mean by "manual installation on each CI system"? Each CI job runs in its own Docker container, so you need to add the installation steps of `wrk2` into each Dockerfile (the links I gave above).

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MznUi0J76-7A_oON780:-MznUi0J76-7A_oON781:b-lmchgf) (no related file):*
Please also update the README: https://github.com/gramineproject/gramine/blob/f7e2a7793e2031d5feec0f1faf5f30ba9320bf5e/CI-Examples/nginx/README.md

It currently contains lines:
```
gramine-direct ./nginx -c conf/nginx-gramine.conf &
gramine-sgx ./nginx -c conf/nginx-gramine.conf &
```

But in reality, Gramine ignores the arguments given in the command-line. So please remove it (and add in the README somewhere that Nginx uses `loader.argv_src_file`).

---


<!-- Sent from Reviewable.io -->

2022-04-04 19:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 11 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtWTx-XlfbIH-RB3j:-MzpUFjBAA8zmxkPODSF:b-grbel4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by "manual installation on each CI system"? Each CI job runs in its own Docker container, so you need to add the installation steps of `wrk2` into each Dockerfile (the links I gave above).
</blockquote></details>

`wrk2` isn't a package like `ab`. We need to clone the source, `make` the sources, and then copy the binary to `/usr/local/bin`. I wasn't sure if this could be done in the dockerfile and assumed it needed manual installation. 

But I think this comment applies to https://github.com/gramineproject/gramine/pull/465 right? In this PR we simply extend the example to use secure command-line arguments without changing the benchmark tool.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MznUi0J76-7A_oON780:-MzpdK0X9Ul4SOsF5cJS:bs1zp2u) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also update the README: https://github.com/gramineproject/gramine/blob/f7e2a7793e2031d5feec0f1faf5f30ba9320bf5e/CI-Examples/nginx/README.md

It currently contains lines:
```
gramine-direct ./nginx -c conf/nginx-gramine.conf &
gramine-sgx ./nginx -c conf/nginx-gramine.conf &
```

But in reality, Gramine ignores the arguments given in the command-line. So please remove it (and add in the README somewhere that Nginx uses `loader.argv_src_file`).
</blockquote></details>

yes, I have added a note in the `README`.

---


<!-- Sent from Reviewable.io -->

2022-04-05 06:13 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQtWTx-XlfbIH-RB3j:-MzsLLwTAkoyrNSvbjsM:bq4fg2j) (no related file):*
> But I think this comment applies to #465 right? 

Right. This comment doesn't apply to the current PR anymore.

---


<!-- Sent from Reviewable.io -->

2022-04-05 06:13 UTC, dimakuv commented
Jenkins, test this please

2022-04-05 06:34 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MzsQW732WwmIzf0v9cx:-MzsQW732WwmIzf0v9cy:bt38gfa) (no related file):*
@vijaydhanraj Something doesn't work here, the CI complains like this:
```
+ make start-gramine-server
gramine-direct ./nginx
error: PAL failed at ../Pal/src/db_main.c:pal_main:453 (exitcode = 9, reason=Cannot load arguments from 'loader.argv_src_file')
Makefile:127: recipe for target 'start-gramine-server' failed
```

Please debug this and fix.

---


<!-- Sent from Reviewable.io -->

2022-04-05 17:36 UTC, dimakuv commented
Jenkins, test this please

2022-04-05 20:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 11 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MzsQW732WwmIzf0v9cx:-MzvJsK24Odx7x_VjIjg:bttd1i5) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I wasn't generating the file containing secure arguments (`nginx_secure_args`) for the `gramine-direct` case. Fixed it now. Can you please restart the Jenkins?
</blockquote></details>

Now CI complains like this:
```
+ ./Scripts/gitignore-test
================================================================================
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? CI-Examples/nginx/nginx_secure_args
Entering 'LibOS/shim/test/ltp/src'
Entering 'LibOS/shim/test/ltp/src/testcases/kernel/mce-test'
================================================================================
```

Looks like you forgot to rm this file in Makefile and/or add this file to gitignore

---


<!-- Sent from Reviewable.io -->

2022-04-05 20:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 11 of 13 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/460#-MzsQW732WwmIzf0v9cx:-MzvQknV7efp8QU4niRv:b-5yclcr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now CI complains like this:
```
+ ./Scripts/gitignore-test
================================================================================
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? CI-Examples/nginx/nginx_secure_args
Entering 'LibOS/shim/test/ltp/src'
Entering 'LibOS/shim/test/ltp/src/testcases/kernel/mce-test'
================================================================================
```

Looks like you forgot to rm this file in Makefile and/or add this file to gitignore
</blockquote></details>

Thanks, yes, I missed adding the generated file to `.gitignore` list.

---


<!-- Sent from Reviewable.io -->

2022-04-06 08:00 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-04-06 08:01 UTC, dimakuv commented
Jenkins, test this please

2022-04-06 17:28 UTC, boryspoplawski requested changes
> Reviewed 1 of 7 files at r1, 2 of 11 files at r2, 2 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[CI-Examples/nginx/.gitignore, line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzjplA6rD5MzxwM7ZN:-MzzjplA6rD5MzxwM7ZO:b-rlcsvl) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/.gitignore#L8)):*
> ```ignore
> /ssl/ca.*
> /ssl/server.*
> /nginx_secure_args
> ```

Please sort
___
*[CI-Examples/nginx/README.md, line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzlsOO42htTzZjTQmz:-MzzlsOO42htTzZjTQn-:b-ozql9z) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/README.md#L30)):*
> ```Markdown
> 
> # Run Nginx in non-SGX Gramine against HTTP and HTTPS benchmarks.
> # Note: The command-line arguments are securely passed using
> ```

Not sure if `securely` has any meaning in this case, not blocking though. 
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzrMjp5m6DIaAN6Nt6:-MzzrMjp5m6DIaAN6Nt7:b-u0zy8m) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L1)):*
> ```reStructuredText
> .. program:: gramine-argv-serializer
> ```

Please add a tag here (`.. _gramine-argv-serializer:`) and reference it in `manifest-syntax.rst` - it reference the program now.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsnsFCYTCfnbgs9Aj:-MzzsnsFCYTCfnbgs9Ak:b-1qsb4j) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L10)):*
> ```reStructuredText
> ========
> 
> :command:`gramine-argv-serializer` [*OPTION*]
> ```

Arguments missing. Probably add another usage line, as `-h` and args are mutually exclusive.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsZrc4DPc28wIQXiN:-MzzsZrc4DPc28wIQXiO:b-ov7fdk) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L16)):*
> ```reStructuredText
> 
> `gramine-argv-serializer` serializes the command line arguments and displays it
> on the terminal. Typically the output is redirected to a file which can be
> ```

It merely outputs it to stdout, it has nothing to do with terminals.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzuNEFAfwdf4aTOqDP:-MzzuNEFAfwdf4aTOqDQ:b-qnmu3a) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
> ```reStructuredText
> `gramine-argv-serializer` serializes the command line arguments and displays it
> on the terminal. Typically the output is redirected to a file which can be
> used as a trusted or a protected file. To use this file as a source of command
> ```

I would join these two sentences into one, e.g. `Typically the output is redirected to a file, which can be specified as a trusted or protected file in Gramine and used as a source of command line arguments using ``loader.argv_src_file`` manifest option.`
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsJb6DWofb0Qe2p-2:-MzzsJb71GLYJM44O4GC:bijekki) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L36)):*
> ```reStructuredText
> .. code-block:: sh
> 
>     $ gramine-argv-serializer Gramine says hi! > gramine_secure_args.txt
> ```

Please remove `$`, you cannot put that into sh...
Also this isn't how you use this tool - you need the binary name (argv0) before args.
___
*[tools/argv_serializer.c, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztyjD0sRsEdNth7rR:-MzztyjD0sRsEdNth7rS:bdk7ku9) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L10)):*
> ```C
>  */
> 
> #include <stdbool.h>
> ```

Why is this needed?
___
*[tools/argv_serializer.c, line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztI_d7bFQYnw-hycp:-MzztI_eA6zzme_V_X83:b-kqs6po) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L15)):*
> ```C
> 
> static void usage(const char* exec) {
>     printf("Usage: %s <executable name followed by command line arguments>\n", exec);
> ```

Maybe `%s "executable name" ["arg1"]...`?
___
*[tools/argv_serializer.c, line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztBX63owfyAOqwqd-:-MzztBX75vAhoJii1oVK:b-h4en4x) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L21)):*
> ```C
>     if (argc < 2) {
>         usage(argv[0]);
>         return -1;
> ```

`-1` -> `1`


<!-- Sent from Reviewable.io -->

2022-04-07 00:24 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[CI-Examples/nginx/.gitignore, line 8 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzjplA6rD5MzxwM7ZN:-N--49PXBJy0TIFHN8Km:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/.gitignore#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please sort
</blockquote></details>

Done.
___
*[CI-Examples/nginx/README.md, line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzlsOO42htTzZjTQmz:-N--4Jcg5h4hIoBm9oDC:b5a1nsi) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/README.md#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure if `securely` has any meaning in this case, not blocking though. 
</blockquote></details>

I added this as the arguments will be passed to Gramine in a trusted file at least in this example.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzrMjp5m6DIaAN6Nt6:-N--gj9e47oCg4y-UAoz:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a tag here (`.. _gramine-argv-serializer:`) and reference it in `manifest-syntax.rst` - it reference the program now.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsnsFCYTCfnbgs9Aj:-N-07MTP9_Sck0IMqK2f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Arguments missing. Probably add another usage line, as `-h` and args are mutually exclusive.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 16 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsZrc4DPc28wIQXiN:-N-01KFI70WX4PDsqY0L:bttz4dh) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It merely outputs it to stdout, it has nothing to do with terminals.
</blockquote></details>

slightly reworded to use `stdout` instead of `terminal`.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzuNEFAfwdf4aTOqDP:-N--z5vP5uDhrH4UawsD:ba8j6v9) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would join these two sentences into one, e.g. `Typically the output is redirected to a file, which can be specified as a trusted or protected file in Gramine and used as a source of command line arguments using ``loader.argv_src_file`` manifest option.`
</blockquote></details>

How about this?
`Typically the output is redirected to a file, which can be used as a trusted or a protected file and the path is specified in ``loader.argv_src_file`` to pass the command line arguments to Gramine.`
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 36 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsJb6DWofb0Qe2p-2:-N-07HtFAXl-h5_9NzZi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove `$`, you cannot put that into sh...
Also this isn't how you use this tool - you need the binary name (argv0) before args.
</blockquote></details>

Done.
___
*[tools/argv_serializer.c, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztyjD0sRsEdNth7rR:-N--pSoa-vrjyQ5XhjKF:b-9frl32) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Not needed, missed to remove it.
___
*[tools/argv_serializer.c, line 15 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztI_d7bFQYnw-hycp:-N--pRUhDhg562xPXYY8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `%s "executable name" ["arg1"]...`?
</blockquote></details>

Done.
___
*[tools/argv_serializer.c, line 21 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzztBX63owfyAOqwqd-:-N--pPu8051AY7lsonyI:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/tools/argv_serializer.c#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`-1` -> `1`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 00:44 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[CI-Examples/nginx/README.md, line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzlsOO42htTzZjTQmz:-N-0R1UF30H17piLiyG6:btuf4fh) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/README.md#L30)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I added this as the arguments will be passed to Gramine in a trusted file at least in this example.
</blockquote></details>

We don't have trusted files in `gramine-direct`.
___
*[Documentation/manifest-syntax.rst, line 135 at r7](https://reviewable.io/reviews/gramineproject/gramine/460#-N-0RT8Z6eZITelUvWij:-N-0RT8Z6eZITelUvWik:beulw4k) ([raw file](https://github.com/gramineproject/gramine/blob/83e818440d538c34f8554c31be24a3069ab85c00/Documentation/manifest-syntax.rst#L135)):*
> ```reStructuredText
> ``loader.insecure__use_cmdline_argv`` (insecure in almost all cases) or point
> ``loader.argv_src_file`` to a file containing output of
> :ref:`gramine-argv-serializer<gramine-argv-serializer>`
> ```

You removed `.` from the end.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsnsFCYTCfnbgs9Aj:-N-0RkgM3igPZ9JxvNHV:b-acbxzs) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L10)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But as I said, we cannot use both options and args at the same time

Update: after seeing the C program: I think we should remove these options completely. They are pretty useless and just add unnecessary bloat to the docs.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzuNEFAfwdf4aTOqDP:-N-0S3wg9SDJFuAcTQFc:bnsotk7) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about this?
`Typically the output is redirected to a file, which can be used as a trusted or a protected file and the path is specified in ``loader.argv_src_file`` to pass the command line arguments to Gramine.`
</blockquote></details>

It's unclear what's `the path` in this sentence and what actually is `loader.argv_src_file`.
___
*[tools/argv_serializer.c, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/460#-N-0SpTj3_QqO81_CS09:-N-0SpTj3_QqO81_CS0A:b-s3ypzx) ([raw file](https://github.com/gramineproject/gramine/blob/83e818440d538c34f8554c31be24a3069ab85c00/tools/argv_serializer.c#L18)):*
> ```C
> 
> int main(int argc, char* argv[]) {
>     if (argc < 2 || !strcmp(argv[1], "-h") || !strcmp(argv[1], "--help")) {
> ```

Please don't go this way, parsing command line in this program is to simple to correctly handle all cases (what if I want my executable to be name `-h`?). Just leave `argc < 2` check.


<!-- Sent from Reviewable.io -->

2022-04-07 01:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[CI-Examples/nginx/README.md, line 30 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzlsOO42htTzZjTQmz:-N-0YPL7-bMKY64gr-mG:bb5124z) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/CI-Examples/nginx/README.md#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We don't have trusted files in `gramine-direct`.
</blockquote></details>

Got it, I will remove this.
___
*[Documentation/manifest-syntax.rst, line 135 at r7](https://reviewable.io/reviews/gramineproject/gramine/460#-N-0RT8Z6eZITelUvWij:-N-0YabmDG0fGohPguKP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/83e818440d538c34f8554c31be24a3069ab85c00/Documentation/manifest-syntax.rst#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You removed `.` from the end.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 10 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzsnsFCYTCfnbgs9Aj:-N-0Ycpp4aG1iRzKFeWj:bxw96k) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But as I said, we cannot use both options and args at the same time

Update: after seeing the C program: I think we should remove these options completely. They are pretty useless and just add unnecessary bloat to the docs.
</blockquote></details>

yes agree, I will remove it.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/460#-MzzuNEFAfwdf4aTOqDP:-N-0bArb6UC4WUNNrWBB:bgaved8) ([raw file](https://github.com/gramineproject/gramine/blob/8c095bc625baba2bf5a508027f3f890c14b2071a/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's unclear what's `the path` in this sentence and what actually is `loader.argv_src_file`.
</blockquote></details>

Modified as below. If you want me to revert to your earlier suggestion will do.
```
Typically, the output is redirected to a file that can be used as a trusted or a protected file and this file path can be pointed to ``loader.argv_src_file`` manifest option for passing command-line arguments to Gramine.
```
___
*[tools/argv_serializer.c, line 18 at r7](https://reviewable.io/reviews/gramineproject/gramine/460#-N-0SpTj3_QqO81_CS09:-N-0cWbi0_iRTSFlqNjq:b-whyows) ([raw file](https://github.com/gramineproject/gramine/blob/83e818440d538c34f8554c31be24a3069ab85c00/tools/argv_serializer.c#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please don't go this way, parsing command line in this program is to simple to correctly handle all cases (what if I want my executable to be name `-h`?). Just leave `argc < 2` check.
</blockquote></details>

agree, have removed it.


<!-- Sent from Reviewable.io -->

2022-04-07 01:41 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-04-07 06:47 UTC, dimakuv approved these changes
> Reviewed 1 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-04-07 06:47 UTC, dimakuv commented
Jenkins, test this please

2022-04-07 12:09 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1, 4 of 11 files at r2, 3 of 6 files at r3, 1 of 1 files at r5, 1 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[CI-Examples/nginx/.gitignore, line 4 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2sYNH0dFmBtHg55uk:-N-2sYNI-YQYvYirJVSh:bz19bsy) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/CI-Examples/nginx/.gitignore#L4)):*
> ```ignore
> /install/*
> /nginx-*/*
> /nginx_secure_args
> ```

I'd drop "secure" from this name, it's just a file with arguments, there's nothing "secure" in it.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuOSY-KU8jJS3xqYu:-N-2uy8r00jmSZzq7C1n:b-pj5wka) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L22)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We might have an issue with an incorrect/stale link in the documentation when the `test_libos.py` changes. So, think it is better to just point to the file. But I have replaced the URL link with hyperlink syntax.
</blockquote></details>

Please replace this with the path from repo root instead, this documentation is not always read in the context of repository (e.g. when built from tarball).
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tl7k4m2ZorOXkdpa:-N-2tl7k4m2ZorOXkdpb:bjsqby3) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
> ```reStructuredText
> ===========
> 
> `gramine-argv-serializer` serializes the command line arguments and displays it
> ```

`displays` -> `prints`

Usually it won't be displayed anywhere.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tyZB6BYzQED2m365:-N-2tyZB6BYzQED2m366:b-q5i6r0) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L20)):*
> ```reStructuredText
> to stdout. Typically, the output is redirected to a file that can be used as a
> trusted or a protected file and this file path can be pointed to
> ``loader.argv_src_file`` manifest option for passing command-line arguments to
> ```

(sorry for that "null" at the diff's end, seems to be a Reviewable bug)



_Suggestion:_
```reStructuredText
to stdout. The result is intended to be redirected to a file that can be used as a
trusted or a protected file and ``loader.argv_src_file`` manifest option pointed to it.
```
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2vKA_Bic4cBFOfhY_:-N-2vKA_Bic4cBFOfhYa:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L32)):*
> ```reStructuredText
> .. code-block:: sh
> 
>    gramine-argv-serializer "binary_name" "arg1" "arg2" > gramine_secure_args.txt
> ```

ditto



_Code quote:_
```reStructuredText
secure_
```
___
*[tools/argv_serializer.c, line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tWqqCqWBInNAMKqK:-N-2tWqqCqWBInNAMKqL:b-tl6xuq) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/tools/argv_serializer.c#L14)):*
> ```C
> 
> static void usage(const char* exec) {
>     printf("Usage: %s \"executable name\" [\"arg1\"]...\n", exec);
> ```

Please undo this, the lack of usage printing was on purpose - otherwise you can't create an empty argv array.


<!-- Sent from Reviewable.io -->

2022-04-07 16:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[CI-Examples/nginx/.gitignore, line 4 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2sYNH0dFmBtHg55uk:-N-3j1GHAz_RWVh8JQQ4:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/CI-Examples/nginx/.gitignore#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop "secure" from this name, it's just a file with arguments, there's nothing "secure" in it.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 17 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tl7k4m2ZorOXkdpa:-N-3jJlb3dm6FImgEO4E:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`displays` -> `prints`

Usually it won't be displayed anywhere.
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tyZB6BYzQED2m365:-N-3kSXGCy3Cnsz9OxI5:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(sorry for that "null" at the diff's end, seems to be a Reviewable bug)
</blockquote></details>

Done.
___
*[Documentation/manpages/gramine-argv-serializer.rst, line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2vKA_Bic4cBFOfhY_:-N-3l-gBDElPdek2TlhQ:b-w45wul) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, also added a note saying the arguments can be empty strings
___
*[tools/argv_serializer.c, line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tWqqCqWBInNAMKqK:-N-3lpMIEL8kLuYYbcUv:b-i4om0v) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/tools/argv_serializer.c#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please undo this, the lack of usage printing was on purpose - otherwise you can't create an empty argv array.
</blockquote></details>

Instead of removing it, how about add this note as well?

```
Usage: gramine-argv-serializer ["arg0"] ["arg1"]...
       Typically, "arg0" is your application name followed by
       other command-line parameters but these strings can be
       empty as well based on your application requirements.
```


<!-- Sent from Reviewable.io -->

2022-04-07 16:59 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tyZB6BYzQED2m365:-N-3x-6y3ez6u2PUZf7o:bzfy08r) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L20)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`to stdout. to stdout.`
___
*[tools/argv_serializer.c, line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tWqqCqWBInNAMKqK:-N-3xbdBAUtrXzy7bYxO:bxxtap2) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/tools/argv_serializer.c#L14)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Instead of removing it, how about add this note as well?

```
Usage: gramine-argv-serializer ["arg0"] ["arg1"]...
       Typically, "arg0" is your application name followed by
       other command-line parameters but these strings can be
       empty as well based on your application requirements.
```
</blockquote></details>

The problem is not with strings being empty, but the whole argv array. At the moment if you write `gramine-argv-serializer > file` it will error out instead of producing a file with empty argv serialized (which happens to be an empty file, but that's an implementation detail).


<!-- Sent from Reviewable.io -->

2022-04-07 17:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tyZB6BYzQED2m365:-N-43XTYBCdHRZ1QPYQx:b-7rl0jd) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/Documentation/manpages/gramine-argv-serializer.rst#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`to stdout. to stdout.`
</blockquote></details>

done.
___
*[tools/argv_serializer.c, line 14 at r8](https://reviewable.io/reviews/gramineproject/gramine/460#-N-2tWqqCqWBInNAMKqK:-N-46cxu13WtB35xAzBv:bssjr15) ([raw file](https://github.com/gramineproject/gramine/blob/8ff38779d4e951a08ee75e7d432e339f9199c871/tools/argv_serializer.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is not with strings being empty, but the whole argv array. At the moment if you write `gramine-argv-serializer > file` it will error out instead of producing a file with empty argv serialized (which happens to be an empty file, but that's an implementation detail).
</blockquote></details>

I see. You are referring to the `exec` family use case where the where argv array can be empty.

Reverted it to the original. 


<!-- Sent from Reviewable.io -->

2022-04-07 19:49 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-07 19:50 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-08 00:14 UTC, mkow requested changes
> Reviewed 3 of 5 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 34 at r10](https://reviewable.io/reviews/gramineproject/gramine/460#-N-5WG_e9x79AD7WctZ1:-N-5WG_e9x79AD7WctZ2:b-694yjs) ([raw file](https://github.com/gramineproject/gramine/blob/8038d17144d0f06024fff9659886a634708f26ef/Documentation/manpages/gramine-argv-serializer.rst#L34)):*
> ```reStructuredText
> .. note ::
> 
>    The arguments can be empty as well based on your application requirements.
> ```

This sounds like talking about passing an array of empty strings, not an empty list. I'd rather omit this whole note, doesn't seem useful to me.



_Code quote:_
```reStructuredText
The arguments can be empty as well based on your application requirements.
```


<!-- Sent from Reviewable.io -->

2022-04-08 00:42 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 13 of 14 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 34 at r10](https://reviewable.io/reviews/gramineproject/gramine/460#-N-5WG_e9x79AD7WctZ1:-N-5bhrn7PIU-jZh2JA9:b-qki79u) ([raw file](https://github.com/gramineproject/gramine/blob/8038d17144d0f06024fff9659886a634708f26ef/Documentation/manpages/gramine-argv-serializer.rst#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This sounds like talking about passing an array of empty strings, not an empty list. I'd rather omit this whole note, doesn't seem useful to me.
</blockquote></details>

ok, removed it.


<!-- Sent from Reviewable.io -->

2022-04-08 07:17 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-08 10:11 UTC, mkow reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-08 10:16 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-08 16:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuOSY-KU8jJS3xqYu:-N-906NV5vYWw3L8hTt9:bb2ok7d) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please replace this with the path from repo root instead, this documentation is not always read in the context of repository (e.g. when built from tarball).
</blockquote></details>

Missed addressing this comment, but what is the repo root path? Is it the permalink, https://github.com/gramineproject/gramine/blob/dac983b14d3b58c6d0ad6313fca21160d95ae23b/LibOS/shim/test/regression/test_libos.py? or the raw path like https://raw.githubusercontent.com/gramineproject/gramine/master/LibOS/shim/test/regression/test_libos.py or something else? Can you please clarify?


<!-- Sent from Reviewable.io -->

2022-04-08 17:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Documentation/manpages/gramine-argv-serializer.rst, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/460#-MyQuOSY-KU8jJS3xqYu:-N-98X9gDuzUT3OV8H5L:b-2qjavc) ([raw file](https://github.com/gramineproject/gramine/blob/9e6a6d6ee4ea69fda04a86d66a21e859cf5c8409/Documentation/manpages/gramine-argv-serializer.rst#L22)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Missed addressing this comment, but what is the repo root path? Is it the permalink, https://github.com/gramineproject/gramine/blob/dac983b14d3b58c6d0ad6313fca21160d95ae23b/LibOS/shim/test/regression/test_libos.py? or the raw path like https://raw.githubusercontent.com/gramineproject/gramine/master/LibOS/shim/test/regression/test_libos.py or something else? Can you please clarify?
</blockquote></details>

Thanks @mkow for the clarification. I have updated the path.


<!-- Sent from Reviewable.io -->

2022-04-08 17:20 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-08 19:08 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-11 07:13 UTC, dimakuv approved these changes
> Reviewed 3 of 5 files at r9, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-11 07:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-04-11 07:18 UTC, dimakuv commented
Jenkins, test this please

2022-04-11 08:34 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/460)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-11 08:37 UTC, merged