[Pal/Linux-SGX] Add `sgx.disable_[cpu-feature]` manifest options
gramineproject/gramine pull request #461
Opened 2022-03-16 08:49 UTC by dimakuv

## Description of the changes 

This PR adds three new manifest options: `sgx.disable_avx`, `sgx.disable_avx512`, `sgx.disable_amx`. Setting each of these options to `true` disables the corresponding CPU feature inside the SGX enclave even if this CPU feature is available on the system: this may improve enclave performance because this CPU feature will *not* be saved and restored during enclave entry/exit.

This PR is a re-creation of https://github.com/gramineproject/gramine/pull/321, since it turned out to be useful for performance. Without disclosing any perf numbers, I performed a set of micro-benchmarks and they prove that disabling Intel AMX inside of the enclave (when it is available on the machine but is not needed by the app inside the enclave) gives a measurable performance boost (for the worst-case scenarios). So this change actually is beneficial.

## How to test this PR? 

I will test this PR manually on the AMX-enabled machine.

2022-03-16 09:10 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`LibOS.shim.test.ltp.test_ltp.test_ltp[fcntl14_64]` and `LibOS.shim.test.ltp.test_ltp.test_ltp[fdatasync01]` timed out, unrelated)

2022-03-16 13:56 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/461#-MyHzB-X1tYH-x9tRR4Q:-MyHzB-X1tYH-x9tRR4R:benm8ea) (no related file):*
But the description of #321 says:

> ~For example, disabling Intel AMX may improve performance of some workloads by around 5%.~ UPDATE: The previous statement turned out to be false. It seems that this PR doesn't provide any perf improvement. I am closing it and may resurrect in the future if this PR turns out to be useful for anything.

So, what happened in the meantime? And how can I verify this?

---


<!-- Sent from Reviewable.io -->

2022-03-16 14:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/461#-MyHzB-X1tYH-x9tRR4Q:-MyI2_1EEJC9uC0OzAjV:b-2hnmhl) (no related file):*
> So, what happened in the meantime?

I did more performance tests on Intel AMX. In particular, I wrote a microbenchmark; you can find this microbenchmark here: https://github.com/gramineproject/gramine/commit/1451bb6543e6e6af02668996261197b37644927e (it is under `CI-Examples/amxtest`). The microbenchmark provides some numbers on perf overhead, but I cannot publish them.

> And how can I verify this?

If you want to test the AMX disable/enable manifest options, you'll need an AMX-enabled machine. Do you have access to one?

If you don't have an AMX-enabled machine, you can check AVX and/or AVX512, in a similar way I show in the `How to test this PR?` section (i.e., you will see different XSAVE size and features).

---


<!-- Sent from Reviewable.io -->

2022-09-01 14:11 UTC, boryspoplawski requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 567 at r1](https://reviewable.io/reviews/gramineproject/gramine/461#-NAtNakC2agRTaYFMNDe:-NAtNakC2agRTaYFMNDf:b6g3cji) ([raw file](https://github.com/gramineproject/gramine/blob/c90a38e76e2fdfae36a8b4b4732782a9c265dce6/Documentation/manifest-syntax.rst#L567)):*
> ```reStructuredText
> Gramine doesn't disallow this, but the feature will be disabled in such case.
> For example, setting both ``sgx.require_avx = true`` and ``sgx.disable_avx =
> true`` will result in the SGX enclave running with AVX disabled.
> ```

This makes no sense to me.
Why not use something like:
```
sgx.avx = ["required","disabled","default"]
```
?


<!-- Sent from Reviewable.io -->

2022-09-01 14:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 567 at r1](https://reviewable.io/reviews/gramineproject/gramine/461#-NAtNakC2agRTaYFMNDe:-NAtPu7X9aler_DXWSMI:bwawe19) ([raw file](https://github.com/gramineproject/gramine/blob/c90a38e76e2fdfae36a8b4b4732782a9c265dce6/Documentation/manifest-syntax.rst#L567)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This makes no sense to me.
Why not use something like:
```
sgx.avx = ["required","disabled","default"]
```
?
</blockquote></details>

The shortest review you've done yet :)

Yes, I could do that, and it is cleaner. But one question: do we want to keep the old `sgx.require_avx` manifest option (deprecate but keep it), or do we remove it?


<!-- Sent from Reviewable.io -->

2022-09-01 14:24 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 567 at r1](https://reviewable.io/reviews/gramineproject/gramine/461#-NAtNakC2agRTaYFMNDe:-NAtQiMs1G4h_ZJXbpGK:b-w7scqh) ([raw file](https://github.com/gramineproject/gramine/blob/c90a38e76e2fdfae36a8b4b4732782a9c265dce6/Documentation/manifest-syntax.rst#L567)):*
> The shortest review you've done yet :)

Well, I've skipped (not reviewed yet) most of the PR for now :)

> But one question: do we want to keep the old sgx.require_avx manifest option (deprecate but keep it), or do we remove it?

Well, I guess we have to keep it for backward compatibility (for one version)? 


<!-- Sent from Reviewable.io -->

2022-09-01 14:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 567 at r1](https://reviewable.io/reviews/gramineproject/gramine/461#-NAtNakC2agRTaYFMNDe:-NAtRAGM3x7FJXbhvPWD:b-jmn2mv) ([raw file](https://github.com/gramineproject/gramine/blob/c90a38e76e2fdfae36a8b4b4732782a9c265dce6/Documentation/manifest-syntax.rst#L567)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The shortest review you've done yet :)

Well, I've skipped (not reviewed yet) most of the PR for now :)

> But one question: do we want to keep the old sgx.require_avx manifest option (deprecate but keep it), or do we remove it?

Well, I guess we have to keep it for backward compatibility (for one version)? 
</blockquote></details>

Sounds good. This will require a lot of clunky code, but I guess that's life. I'll update this PR soon-ish.

@boryspoplawski Should I rebase to the latest master? Or maybe even close this PR, and create a new one, with your comment on `sgx.avx` and based on current master?


<!-- Sent from Reviewable.io -->

2022-09-01 14:44 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/461)* status: 2 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 567 at r1](https://reviewable.io/reviews/gramineproject/gramine/461#-NAtNakC2agRTaYFMNDe:-NAtUq-g5msx5dxQIlXG:b-z01f88) ([raw file](https://github.com/gramineproject/gramine/blob/c90a38e76e2fdfae36a8b4b4732782a9c265dce6/Documentation/manifest-syntax.rst#L567)):*
> . This will require a lot of clunky code, but I guess that's life. 

Why is that? Doesn't sound so bad, just one or two ifs in python.

> Should I rebase to the latest master? Or maybe even close this PR, and create a new one

I don't mind either - I did not review much so I can either check full diff here or at new PR, doesn't matter to me


<!-- Sent from Reviewable.io -->

2022-09-02 11:42 UTC, dimakuv commented
Closed in favor of https://github.com/gramineproject/gramine/pull/877 (rebased and improved version)

2022-09-02 11:42 UTC, closed without merging