Add first version of encrypted mounts
gramineproject/gramine pull request #462
Opened 2022-03-16 11:39 UTC by pwmarcz

## Description of the changes 

This adds `type = "encrypted"` mounts according to the design in #371. They do not have all the features of protected files yet, but the change is already pretty big.

## How to test this PR? 

I will eventually convert all the tests that use protected files. For now, the `send_handle` test covers a simple scenario: opening, writing and then reading a file. (Also, it already correctly sends the handle to child process even if the file is deleted - something the old protected files could not do).

2022-03-17 13:00 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMxG-52Gxdy8OhJ__K:-MyMxG-52Gxdy8OhJ__L:bnlszcb) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L8)):*
> ```objc
> /*
>  * This module implements encrypted files. It is a wrapper around the platform-independent
>  * `protected_files` module, and PAL handles.
> ```

I need some kind of a diagram that explains the relationships between:
- FS mounts (that each "encrypted" mount points to the encryption key in `data`)
- inodes (that each "encrypted" inode points to the `shim_encrypted_file` object in `data`)
- the relationship between `shim_handle`, `shim_encrypted_file`, `pf_context`, `pal_handle`

Currently, it is very hard for me to understand which objects are created together, which objects are destroyed together, which objects have which lifetimes, etc.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUF9JD15aAou75Zol:-MyMUF9JD15aAou75Zom:b-jydnwj) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L106)):*
> ```objc
> 
> /*
>  * \brief Deallocate an encrypted file.
> ```

Does it basically `free(enc)`? It's a counterpart to `encrypted_file_new_open()` and `encrypted_file_new_create()`, right?

No need to change anything, just double-checking.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 115 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUavj8Bleu8LHQrkz:-MyMUavj8Bleu8LHQrl-:b-mept9i) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L115)):*
> ```objc
>  * \brief Increase the use count of an encrypted file.
>  *
>  * This increases `use_count`, and makes sure that the file is open.
> ```

`...and makes sure that the file is open` -- I don't get this part.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUijN7qOIm6r1F_3a:-MyMUijN7qOIm6r1F_3b:b-51yiyx) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L122)):*
> ```objc
>  * \brief Decrease the use count of an encrypted file.
>  *
>  * This decreases `use_count`, and closes the file if it reaches 0.
> ```

Why can't `encrypted_file_destroy()` be merged into this function (when `use_count == 0`)?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 32 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMcVwzCJN-3HXQTTv7:-MyMcVwzCJN-3HXQTTv8:blq8tea) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L32)):*
> ```C
>         int ret = DkStreamRead(pal_handle, offset + buffer_offset, &count, buffer + buffer_offset,
>                                /*source=*/NULL, /*size=*/0);
>         if (ret == PAL_ERROR_INTERRUPTED)
> ```

Shouldn't this be `-PAL_ERROR_INTERRUPTED` (with minus)?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMcbfC8FH6yEFfHv4q:-MyMcbfDCoJW7Ek_Y-Jn:blq8tea) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L62)):*
> ```C
>         int ret = DkStreamWrite(pal_handle, offset + buffer_offset, &count,
>                                 (void*)(buffer + buffer_offset), /*dest=*/NULL);
>         if (ret == PAL_ERROR_INTERRUPTED)
> ```

Shouldn't this be `-PAL_ERROR_INTERRUPTED` (with minus)?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 145 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMg0WV-iC4iZNHI6TH:-MyMg0WV-iC4iZNHI6TI:b-8zk9wn) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L145)):*
> ```C
> #endif
> 
> static int encrypted_file_open(struct shim_encrypted_file* enc, PAL_HANDLE pal_handle, bool create,
> ```

I desperately need a comment explaining the relationships between `shim_encrypted_file`, `PAL_HANDLE`, `pf_context` and `shim_handle`. Which of these are 1:1, which are shared among objects?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 166 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMeaBe-gZuZqolVowI:-MyMeaBe-gZuZqolVowJ:b-qa609l) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L166)):*
> ```C
>     if (ret < 0) {
>         log_warning("%s: DkStreamAttributesQueryByHandle failed: %d", __func__, ret);
>         DkObjectClose(pal_handle);
> ```

What is there was a `pal_handle` provided as a func argument? Then this function's failure has a side-effect of closing this file handle. Was that your intention?

I see that you don't close the PAL handle on the below error path, so looks like an inconsistency.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 178 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMfKGC09agYQarJBRx:-MyMfKGDAUsj5Qa9ZlSg:bjbqi5w) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L178)):*
> ```C
>         return -EACCES;
>     }
>     pf_status_t pfs = pf_open(pal_handle, path, size, PF_FILE_MODE_READ | PF_FILE_MODE_WRITE,
> ```

I understand that the underlying PAL handle should be opened for read + write. But why do you set the PF-specific mode for read + write? I think at this level, you can specify only the correct subset of modes.

Or is it because this `pf` context is shared among several shim handles/fds -- some of them may be opened for read, some for write?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MyMgn1778wUYS7ffB4q:bp6ln2o) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
> ```C
>                      &cb_random, cb_debug_ptr);
> 
>     /* Parse `fs.keys.*` */
> ```

`keys` -> `insecure__keys`
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMhIF12Td2Jdf7Mh6Z:-MyMhIF12Td2Jdf7Mh6_:b654c0w) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L250)):*
> ```C
>             goto out;
>         }
>         assert(key_str);
> ```

Please add an empty line after this assert.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 296 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMiKhxAHrCFzJZy7zc:-MyMiKhxAHrCFzJZy7zd:b-m6nquu) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L296)):*
> ```C
>     struct shim_encrypted_files_key* key = get_or_create_key(name);
> 
>     /* TODO: load special keys (MRENCLAVE, MRSIGNER) here */
> ```

It shouldn't happen in this function (after all, this func may never be called if there are no `fs.insecure__keys` array in the manifest).

Instead, special keys should be loaded during `init_encrypted_files()`.
___
*[LibOS/shim/sr [...]

2022-03-18 10:34 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 26 of 29 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMxG-52Gxdy8OhJ__K:-MyRJy9-9nxMIK7ZjHmb:b-cltkq9) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I need some kind of a diagram that explains the relationships between:
- FS mounts (that each "encrypted" mount points to the encryption key in `data`)
- inodes (that each "encrypted" inode points to the `shim_encrypted_file` object in `data`)
- the relationship between `shim_handle`, `shim_encrypted_file`, `pf_context`, `pal_handle`

Currently, it is very hard for me to understand which objects are created together, which objects are destroyed together, which objects have which lifetimes, etc.
</blockquote></details>

I am no good at diagrams, but I added a longer explanation (to the `encrypted.c` file which actually manages these objects). Does that help?
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 106 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUF9JD15aAou75Zol:-MyRMCPz4AfWZ06xWElq:bb77ufg) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it basically `free(enc)`? It's a counterpart to `encrypted_file_new_open()` and `encrypted_file_new_create()`, right?

No need to change anything, just double-checking.
</blockquote></details>

Yes.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 115 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUavj8Bleu8LHQrkz:-MyRMNG6EFSMtzVpb9tO:b-uy6ve6) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...and makes sure that the file is open` -- I don't get this part.
</blockquote></details>

Changed to "and opens the file if `use_count` was 0".
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUijN7qOIm6r1F_3a:-MyRMR1QDJ-N0gkjhPm7:b-paetsy) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why can't `encrypted_file_destroy()` be merged into this function (when `use_count == 0`)?
</blockquote></details>

Because the file can be open again later. I added "Note that the file can be open and closed multiple times before it's destroyed" above.

This is the reason why I'm calling the variable `use_count`, not `ref_count`: it is not tied to the object's lifetime. Maybe the operations also should be called something else than `get/put`? But I can't think of a better name.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 32 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMcVwzCJN-3HXQTTv7:-MyRN8uQAx_ZGelrI9Sp:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be `-PAL_ERROR_INTERRUPTED` (with minus)?
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 62 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMcbfC8FH6yEFfHv4q:-MyRNAjN440QmOIsqhTC:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be `-PAL_ERROR_INTERRUPTED` (with minus)?
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 145 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMg0WV-iC4iZNHI6TH:-MyRNEV85u0Cr8DO2lFX:b-b9i04g) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I desperately need a comment explaining the relationships between `shim_encrypted_file`, `PAL_HANDLE`, `pf_context` and `shim_handle`. Which of these are 1:1, which are shared among objects?
</blockquote></details>

* A `PAL_HANDLE` and `pf_context_t` are owned by `shim_encrypted_file`, as long as the file is open.
* A `shim_handle` doesn't keep any data.

Let me know if the comments I just added clarify the situation. 

(This module doesn't know anything about `shim_handle` or the rest of the filesystem, btw, I hope that's clear).
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 166 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMeaBe-gZuZqolVowI:-MyRORkMDXZoYHUycZqL:b-ad7myn) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L166)):*
> What is there was a pal_handle provided as a func argument?

This is for checkpointing. I added a comment.

>Then this function's failure has a side-effect of closing this file handle. Was that your intention?

Yes, in this case, we fail to start the process anyway.

>I see that you don't close the PAL handle on the below error path, so looks like an inconsistency.

Right. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 178 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMfKGC09agYQarJBRx:-MyRPeNk1JEd80adJ2yQ:bxa2ykp) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L178)):*
> Or is it because this pf context is shared among several shim handles/fds -- some of them may be opened for read, some for write?

Yes.

And renaming (which we do not support yet, but we're going to) should also work on read-only handles.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MyRQ6_BEwRHgb2zy5lj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`keys` -> `insecure__keys`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMhIF12Td2Jdf7Mh6Z:-MyRQ8WM5Pz46JgwHics:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L250)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this assert.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 296 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMiKhxAHrCFzJZy7zc:-MyRQKFzBVRBI9QBEqU7:b-jq1852) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L296)):*
<det [...]

2022-03-18 12:20 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 8 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMxG-52Gxdy8OhJ__K:-MyRtIHV8Cb2FF--wNrQ:bp7e5zh) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I am no good at diagrams, but I added a longer explanation (to the `encrypted.c` file which actually manages these objects). Does that help?
</blockquote></details>

Yes, this helps. Thanks.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 122 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMUijN7qOIm6r1F_3a:-MyRvulz8WobhM4KzQkL:boes371) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/include/shim_fs_encrypted.h#L122)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because the file can be open again later. I added "Note that the file can be open and closed multiple times before it's destroyed" above.

This is the reason why I'm calling the variable `use_count`, not `ref_count`: it is not tied to the object's lifetime. Maybe the operations also should be called something else than `get/put`? But I can't think of a better name.
</blockquote></details>

I understand now. The names are a bit misleading, but I also cannot come up with anything better.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/462#-MyRtqH_5nXBii08nX2k:-MyRtTk89gMg4eAQYp-c:b-516e0s) ([raw file](https://github.com/gramineproject/gramine/blob/3ac64366d6ede5a172f0be7c29eca4113662e6bf/LibOS/shim/include/shim_fs_encrypted.h#L40)):*
> ```objc
> /*
>  * Represents a specific encrypted file. The file is open as long as `use_count` is greater than 0.
>  * Note that the file can be open and closed multiple times before it's destroyed.
> ```

Ok, I'm starting to understand the logic behind the separation into different files.

This file (`shim_fs_encrypted.h`) is an FS-subsystem-agnostic wrapper for common/protected-files:
- it adds an additional layer of `shim_encrypted_files_key` around `pf_key`, and
- it adds an additional layer of `shim_encrypted_file` around `pf_context_t` + PAL handle

The former struct allows to put all PF keys in a linked list (as well as tag them with names). The latter struct allows to keep the association <PF key - filename - PF context - PAL handle> in one logical object.

Or, mapping it to the current PAL implementation of PFs:
- the former struct corresponds to (and makes more generic) https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/protected-files/protected_files.h#L30-L33
- the latter struct corresponds to https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/enclave_pf.h#L54-L62

This separation is also why you don't mention inodes here -- you want this header file to be completely FS-agnostic.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 296 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMiKhxAHrCFzJZy7zc:-MyRwuwODaPWLz_ADOV9:bpre4za) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L296)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This function is also called during mount. I was planning to do it like this:
* the user specifies a key named `_sgx_mrenclave`
* the mount callback (`chroot_encrypted_mount`) will call `get_encrypted_files_key("_sgx_mrenclave")`, 
* here, we notice the `_` prefix, and call a PAL function like `DkGetSpecialKey("_sgx_mrenclave")`.

In `init_encrypted_files` we don't know which keys to load: we could parse the mounts table _again_, have a hardcoded list of all special keys in LibOS, or ask PAL for a list of all supported special keys. Neither of these option sounds better to me.
</blockquote></details>

Got it. Yes, the mount callback is a good idea, now I understand.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 429 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMm8Rl36BtxOdOxG5W:-MyRxPbd1utdNWuUlulR:bza97lq) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L429)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe... But the error conditions (see `protected_files.h`) are very much specific to this library.
</blockquote></details>

This is also true. Still, having a `pf_failure_to_unix_errno()` function instead of `-EACCES` will definitely be an improvement, even if we won't be able to mount all PF error conditions to UNIX codes.
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 17 at r6](https://reviewable.io/reviews/gramineproject/gramine/462#-MyRy5JS2opNEYxyuLvO:-MyRy5JS2opNEYxyuLvP:bsfh2fk) ([raw file](https://github.com/gramineproject/gramine/blob/3ac64366d6ede5a172f0be7c29eca4113662e6bf/LibOS/shim/src/fs/chroot/encrypted.c#L17)):*
> ```C
>  * - Inodes (`shim_inode`, for regular files) hold a `shim_encrypted_file` object. This object lives
>  *   as long as the inode, but is kept *open* only as long as there are `shim_handle` objects
>  *   corresponding to it. We use `encrypted_file_{get,put}` operations to maintain that invariant.
> ```

This paragraph is what I was missing. Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2022-03-18 13:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/462#-MyRtqH_5nXBii08nX2k:-MyS5bb80PJiFsx2QXdy:b-wyzb9u) ([raw file](https://github.com/gramineproject/gramine/blob/3ac64366d6ede5a172f0be7c29eca4113662e6bf/LibOS/shim/include/shim_fs_encrypted.h#L40)):*
Right. This module is an equivalent of `enclave_pf.c`, and it's not dependent on the rest of LibOS (well, except for manifest parsing).

>the former struct corresponds to (and makes more generic) https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/protected-files/protected_files.h#L30-L33

Yes. These globals are actually _also_ part of `enclave_pf.c`, and probably were declared in `protected_files.h` by mistake. We'll remove them soon anyway.


<!-- Sent from Reviewable.io -->

2022-03-29 00:54 UTC, mkow requested changes
> Reviewed 11 of 11 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 8 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 899 at r6](https://reviewable.io/reviews/gramineproject/gramine/462#-MzI2x0w6kEwA7XNUo9y:-MzI2x0xBYMSyQm4Zwce:b-sgslr0) ([raw file](https://github.com/gramineproject/gramine/blob/3ac64366d6ede5a172f0be7c29eca4113662e6bf/LibOS/shim/include/shim_fs.h#L899)):*
> ```objc
>  * If `type` is KEEP_URI_PREFIX, we keep the URI prefix from mount URI.
>  */
> int chroot_dentry_uri(struct shim_dentry* dent, mode_t type, char** out_uri);
> ```

It was like this before, but this argument was very confusing to me, I couldn't easily tell if it's a standard POSIX enum/type or ours, and what values can be used there. Seems to be some weird mix of our `KEEP_URI_PREFIX` and standard `S_IF*` values, which sounds problematic, because we can't ensure the lack of collisions (i.e. that none of the `S_IF*` values is 0).



_Code quote (i):_
```objc
#define KEEP_URI_PREFIX 0
```



_Code quote (ii):_
```objc
mode_t type
```



_Code quote (iii):_
```objc
If `type` is KEEP_URI_PREFIX
```
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MzI8Neu6Gy2MGzYKL7R:bdduc8j) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We also need to add this to the security warnings printed at the start.


<!-- Sent from Reviewable.io -->

2022-03-29 11:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 26 of 30 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 899 at r6](https://reviewable.io/reviews/gramineproject/gramine/462#-MzI2x0w6kEwA7XNUo9y:-MzKT6ZL7jtGlSYqc7dn:b-ws4t77) ([raw file](https://github.com/gramineproject/gramine/blob/3ac64366d6ede5a172f0be7c29eca4113662e6bf/LibOS/shim/include/shim_fs.h#L899)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was like this before, but this argument was very confusing to me, I couldn't easily tell if it's a standard POSIX enum/type or ours, and what values can be used there. Seems to be some weird mix of our `KEEP_URI_PREFIX` and standard `S_IF*` values, which sounds problematic, because we can't ensure the lack of collisions (i.e. that none of the `S_IF*` values is 0).
</blockquote></details>

OK. This is actually needed in exactly one case, so I'll remove this `KEEP_URI_PREFIX` entirely.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MzKWhth0E3x-RmHmC4l:bwmrykk) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We also need to add this to the security warnings printed at the start.
</blockquote></details>

It's probably a mistake that these warnings are implemented for Linux-SGX specifically... and actually we don't warn on `sgx.insecure__protected_files_key` at all. Anyway, added both.


<!-- Sent from Reviewable.io -->

2022-03-31 00:52 UTC, mkow requested changes
> Reviewed 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 46 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzQOrWE1uD61BYItFHJ:-MzQOrWE1uD61BYItFHK:bd2n8gb) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/include/shim_fs_encrypted.h#L46)):*
> ```objc
>  */
> struct shim_encrypted_file {
>     unsigned int use_count;
> ```

Why not `size_t`?



_Code quote:_
```objc
unsigned int
```
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 67 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzQR-e71rp8sIfilDBa:-MzQR-e81042Q-AjRTg6:b-3xbj03) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/include/shim_fs_encrypted.h#L67)):*
> ```objc
>  * Sets `*out_key` to a key with a given name. Note that the key might not be set yet (see
>  * `struct shim_encrypted_files_key`).
>  */
> ```

Could you document the object ownership here? I guess it _doesn't_ pass the ownership of `**out_key` to the caller?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MzQ7gmXDGqxqmO9AIlj:b-jqvr4h) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's probably a mistake that these warnings are implemented for Linux-SGX specifically... and actually we don't warn on `sgx.insecure__protected_files_key` at all. Anyway, added both.
</blockquote></details>

Hard to say, some PALs technically may not be security-relevant (e.g. Linux PAL now, or some compat PALs used to run Linux ELFs outside of Linux). Also, on a different TEE the set of insecure configs may be different.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 107 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzS9EtL831ww-T6HbYg:-MzS9EtMDPK4cDf5joc6:b19chaw) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L107)):*
> ```C
> static pf_status_t cb_aes_gcm_encrypt(const pf_key_t* key, const pf_iv_t* iv, const void* aad,
>                                       size_t aad_size, const void* input, size_t input_size,
>                                       void* output, pf_mac_t* mac) {
> ```

Please add `out_` prefix to the out args.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 119 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSADty22E02VaPnjaZ:-MzSADty22E02VaPnja_:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L119)):*
> ```C
> static pf_status_t cb_aes_gcm_decrypt(const pf_key_t* key, const pf_iv_t* iv, const void* aad,
>                                       size_t aad_size, const void* input, size_t input_size,
>                                       void* output, const pf_mac_t* mac) {
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 154 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSB8W1BQ30Ep2mRARM:-MzSB8W1BQ30Ep2mRARN:b-pzim2w) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L154)):*
> ```C
>     assert(!enc->pf);
> 
>     const char* path = enc->uri + static_strlen(URI_PREFIX_FILE);
> ```

Could you assert here that `enc->uri` indeed starts with `URI_PREFIX_FILE`?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 301 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSFSuW3IUVJOsjO6kW:-MzSFSuW3IUVJOsjO6kX:bel6baw) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L301)):*
> ```C
>     lock(&g_keys_lock);
> 
>     struct shim_encrypted_files_key* key = get_or_create_key(name);
> ```

Shouldn't we return an error if `key == NULL`?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 356 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSIrQbA-KC4HkMBlpc:-MzSIrQcDjTqmNSyrYYR:bwbi73o) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L356)):*
> ```C
> 
>     enc->uri = strdup(uri);
>     if (!uri) {
> ```

should be `enc->uri`
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 535 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSM4rW2O_yAmLx2ymw:-MzSM4rW2O_yAmLx2ymx:b-bghtq7) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L535)):*
> ```C
>      *
>      * TODO: Once we can change the keys through `/dev/attestation`, this will not be enough: we'll
>      * need to copy the current key value. Convert this to `DEFINE_CP_FUNC(encrypted_file_key)` etc.
> ```

Hmm, so, this doesn't work if the PF key was set after remote attestation? This is the most standard use for PF, I think.
If so, I assume this fix is just left for the other part of the rewrite?
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 17 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSN7KX0M1-d5-SgzTH:-MzSN7KX0M1-d5-SgzTI:b4u2ora) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/chroot/encrypted.c#L17)):*
> ```C
>  * - Inodes (`shim_inode`, for regular files) hold a `shim_encrypted_file` object. This object lives
>  *   as long as the inode, but is kept *open* only as long as there are `shim_handle` objects
>  *   corresponding to it. We use `encrypted_file_{get,put}` operations to maintain that invariant.
> ```

Actually, why doesn't it have the same lifetime as its inode? Optimization to not keep the handle open unnecessarily?


<!-- Sent from Reviewable.io -->

2022-03-31 12:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 28 of 30 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 46 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzQOrWE1uD61BYItFHJ:-MzUpgUN1OeYpn3ppGDx:b2rah3u) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/include/shim_fs_encrypted.h#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `size_t`?
</blockquote></details>

Makes sense. Changed.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 67 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzQR-e71rp8sIfilDBa:-MzUq6MW5UKbonxL3ihr:byvyago) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/include/shim_fs_encrypted.h#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you document the object ownership here? I guess it _doesn't_ pass the ownership of `**out_key` to the caller?
</blockquote></details>

Yes. Done.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 107 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzS9EtL831ww-T6HbYg:-MzUqhz8D7N1W0kmIdVa:b-wdxae4) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L107)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add `out_` prefix to the out args.
</blockquote></details>

These seem to be `output` and `mac`. Are you proposing to rename them to `out_output` and `out_mac`? I'm not sure if it will make things more readable. Maybe the fact that they're non-`const` pointers is enough?

(AFAIK, by convention we didn't label output _buffers_ as `out_`, but mostly parameters that are double-star pointers).
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 301 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSFSuW3IUVJOsjO6kW:-MzUrpAV7gqi3FwjWBc1:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L301)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we return an error if `key == NULL`?
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 356 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSIrQbA-KC4HkMBlpc:-MzUs-brAO_arsob6fMi:bpfugyi) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L356)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `enc->uri`
</blockquote></details>

Right, thanks.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 535 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSM4rW2O_yAmLx2ymw:-MzUs1oG-_D26gR9BlDL:b-2sbuv6) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L535)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, so, this doesn't work if the PF key was set after remote attestation? This is the most standard use for PF, I think.
If so, I assume this fix is just left for the other part of the rewrite?
</blockquote></details>

That's right, this will be needed soon, but I didn't want to make this PR bigger.
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 17 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSN7KX0M1-d5-SgzTH:-MzUsDv60CB9AsjOYdj5:b-dvhl6q) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/chroot/encrypted.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why doesn't it have the same lifetime as its inode? Optimization to not keep the handle open unnecessarily?
</blockquote></details>

Yes. Right now, we do not delete dentries/inodes for existing files, so we would keep open handles for the whole lifetime of a process. And even a `stat` is enough to trigger opening such a file (since you need to decrypt the header to check real size).


<!-- Sent from Reviewable.io -->

2022-03-31 12:36 UTC, mkow reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 107 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzS9EtL831ww-T6HbYg:-MzUy8K01GSkKCY4ciOF:btt2yic) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L107)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

These seem to be `output` and `mac`. Are you proposing to rename them to `out_output` and `out_mac`? I'm not sure if it will make things more readable. Maybe the fact that they're non-`const` pointers is enough?

(AFAIK, by convention we didn't label output _buffers_ as `out_`, but mostly parameters that are double-star pointers).
</blockquote></details>

Hmm, right, makes sense.


<!-- Sent from Reviewable.io -->

2022-03-31 12:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 29 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 154 at r7](https://reviewable.io/reviews/gramineproject/gramine/462#-MzSB8W1BQ30Ep2mRARM:-MzV0U_sETqhY7mrzgHz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/330aac1dc345d360cdf3e1fb90bc2e1489422492/LibOS/shim/src/fs/shim_fs_encrypted.c#L154)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you assert here that `enc->uri` indeed starts with `URI_PREFIX_FILE`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-31 13:10 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-04 11:41 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r7, 1 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 218 at r5](https://reviewable.io/reviews/gramineproject/gramine/462#-MyMgn1778wUYS7ffB4p:-MzoJnki8L_x7QgmwvyP:biqz2dl) ([raw file](https://github.com/gramineproject/gramine/blob/13681092bbf5cdefb425d9932493672d672d6a44/LibOS/shim/src/fs/shim_fs_encrypted.c#L218)):*
> It's probably a mistake that these warnings are implemented for Linux-SGX specifically... and actually we don't warn on `sgx.insecure__protected_files_key` at all. Anyway, added both.

Oops, this was my mistake, I forgot to add that key to the warning list. Thanks for noticing this.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 141 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoKYZq0wGEC81JXm6-:-MzoKYZq0wGEC81JXm60:bcl23s2) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/LibOS/shim/src/fs/chroot/fs.c#L141)):*
> ```C
>      * The only exception is when this is the root dentry of a "dev:" mount, i.e. a directly mounted
>      * device. This is because PAL recognizes a special "dev:tty" device, which needs to be referred
>      * to by this exact URI (and "file:tty" will not work).
> ```

Well, this probably can be (should be?) fixed at the PAL level, somewhere in `db_devices.c`. This whole logic is a bit weird, but at least it would be uniform for all PAL object types. Not blocking, just thinking out loud.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 676 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoLXcA6uILUfZX-ljX:-MzoLXcA6uILUfZX-ljY:b-hoh39n) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L676)):*
> ```C
>         goto out;
>     if (protected_files_key_str) {
>         free(protected_files_key_str);
> ```

We have a difference between how we treat `log_level_str` and `protected_files_key_str` strings (former is freed in out path, latter is freed immediately). Can we converge on one option? I would prefer the former.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 739 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMbGUEfOnfOOK-E9h:-MzoMbGUEfOnfOOK-E9i:bnr75a9) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L739)):*
> ```C
>     if (enable_sysfs_topo)
>         log_always("  - fs.experimental__enable_sysfs_topology = true "
>                    "(forwarding sysfs topology from untrusted host to the app)");
> ```

I would move this to be the last one. Then we'll have all options related to FS close to each other.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 742 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMOOPE23MlZbkk1tp:-MzoMOOPE23MlZbkk1tq:b-f0xo8i) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L742)):*
> ```C
> 
>     if (protected_files_key)
>         log_always("  - sgx.insecure__protected_files_key = \"...\" "
> ```

I think you need one more space at the end here, to align with all other strings.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 746 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMoLu-9Xmqt5Px7Gi:-MzoMoLu-9Xmqt5Px7Gj:bym18w1) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L746)):*
> ```C
> 
>     if (encrypted_files_keys)
>         log_always("  - fs.insecure__keys.* = \"...\"              "
> ```

Why this syntax? Why not `fs.insecure__keys = [ ... ]`?


<!-- Sent from Reviewable.io -->

2022-04-04 12:44 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 29 of 30 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 141 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoKYZq0wGEC81JXm6-:-MzoYFv-4fR7Lj-gfkEA:brgwhnx) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/LibOS/shim/src/fs/chroot/fs.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, this probably can be (should be?) fixed at the PAL level, somewhere in `db_devices.c`. This whole logic is a bit weird, but at least it would be uniform for all PAL object types. Not blocking, just thinking out loud.
</blockquote></details>

Actually, I'm not sure why the "devices" subsystem even exists, since you can open devices using `file:`, and PAL will still report they are `FILE_TYPE_DEV`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 676 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoLXcA6uILUfZX-ljX:-MzoYuDY0CaDoOTgUYNf:b-y19eik) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L676)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a difference between how we treat `log_level_str` and `protected_files_key_str` strings (former is freed in out path, latter is freed immediately). Can we converge on one option? I would prefer the former.
</blockquote></details>

Makes sense. I moved the free to the out path.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 739 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMbGUEfOnfOOK-E9h:-MzoZFEK-Jub27rOISka:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L739)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move this to be the last one. Then we'll have all options related to FS close to each other.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 742 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMOOPE23MlZbkk1tp:-MzoZWc56ud-YP4kHOjk:biw8y1v) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L742)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you need one more space at the end here, to align with all other strings.
</blockquote></details>

Right. Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 746 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMoLu-9Xmqt5Px7Gi:-MzoZ_4m5ogN6KAa_v1D:b-pezeyd) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L746)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this syntax? Why not `fs.insecure__keys = [ ... ]`?
</blockquote></details>

The keys are a table, not an array. And while this syntax is not documented yet, I think it should be documented as `fs.insecure__keys.[KEY] = "..."`, not as inline table: for a single key, inline table is unnecessary, and for multiple keys, it's annoying to use (due to lack of trailing comma). That's why I don't think `{ ... }` is better here, either.


<!-- Sent from Reviewable.io -->

2022-04-04 13:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 141 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoKYZq0wGEC81JXm6-:-Mzokkps9ODs0u1Qs6zB:b141jut) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/LibOS/shim/src/fs/chroot/fs.c#L141)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, I'm not sure why the "devices" subsystem even exists, since you can open devices using `file:`, and PAL will still report they are `FILE_TYPE_DEV`.
</blockquote></details>

Yeah, this is yet another (rather small) thing that deserves some refactoring.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 746 at r10](https://reviewable.io/reviews/gramineproject/gramine/462#-MzoMoLu-9Xmqt5Px7Gi:-Mzol9yH9a7_tIuOf-lD:b-nec2kw) ([raw file](https://github.com/gramineproject/gramine/blob/57dbcf16a5a076b681183ea953e529ee31498329/Pal/src/host/Linux-SGX/db_main.c#L746)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The keys are a table, not an array. And while this syntax is not documented yet, I think it should be documented as `fs.insecure__keys.[KEY] = "..."`, not as inline table: for a single key, inline table is unnecessary, and for multiple keys, it's annoying to use (due to lack of trailing comma). That's why I don't think `{ ... }` is better here, either.
</blockquote></details>

Ok, makes sense.


<!-- Sent from Reviewable.io -->

2022-04-05 10:50 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 628 at r11](https://reviewable.io/reviews/gramineproject/gramine/462#-MztKiTe5aTAt9UyUBHa:-MztKiTf9MjUcpJRFxrx:be5mn52) ([raw file](https://github.com/gramineproject/gramine/blob/51ac6b5f01f344c5b4edf73d1665251c5e0d3961/Pal/src/host/Linux-SGX/db_main.c#L628)):*
> ```C
>     bool protected_files_key  = false;
>     bool encrypted_files_keys = false;
>     bool enable_sysfs_topo    = false;
> ```

Could you undo these change which move the sysfs related IFs around? I'm removing them in the sysfs rework and this will generate a lot of conflicts.


<!-- Sent from Reviewable.io -->

2022-04-05 10:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: 29 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 628 at r11](https://reviewable.io/reviews/gramineproject/gramine/462#-MztKiTe5aTAt9UyUBHa:-MztNBOKA2xpoUk7QoSy:b2p9zqj) ([raw file](https://github.com/gramineproject/gramine/blob/51ac6b5f01f344c5b4edf73d1665251c5e0d3961/Pal/src/host/Linux-SGX/db_main.c#L628)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you undo these change which move the sysfs related IFs around? I'm removing them in the sysfs rework and this will generate a lot of conflicts.
</blockquote></details>

OK. (CC @dimakuv)


<!-- Sent from Reviewable.io -->

2022-04-05 11:39 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 628 at r11](https://reviewable.io/reviews/gramineproject/gramine/462#-MztKiTe5aTAt9UyUBHa:-MztWPIp8RzQBAsVnQ5_:bxkepqz) ([raw file](https://github.com/gramineproject/gramine/blob/51ac6b5f01f344c5b4edf73d1665251c5e0d3961/Pal/src/host/Linux-SGX/db_main.c#L628)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. (CC @dimakuv)
</blockquote></details>

No problem for me. Approved.


<!-- Sent from Reviewable.io -->

2022-04-05 14:27 UTC, dimakuv approved these changes
> Reviewed 9 of 10 files at r14, 2 of 3 files at r16, 12 of 12 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-04-05 14:39 UTC, mkow approved these changes
> Reviewed 9 of 10 files at r14, 2 of 3 files at r16, 12 of 12 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/462)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-05 14:40 UTC, merged