[CI-Examples] Update benchmark-http.sh script to use wrk2 benchmark
gramineproject/gramine pull request #465
Opened 2022-03-18 20:04 UTC by vijaydhanraj

## Description of the changes 

The `benchmark-http.sh` script uses the Apache Benchmark (ab) under the hood. At least the default version of ab shipped with Ubuntu 18.04 (v2.3) does not work correctly with Nginx and HTTPS (it fails on KeepAlive HTTPS requests). So updated the script to use `wrk2`. Secondly, the median calculation in the script is broken and this PR addresses the issue. This PR also adds APIs to parse and convert throughput and latency metrics with SI units to plain numbers.  (Note: `wrk2` shows the results with SI units.)
 
## How to test this PR? 
Please run `nginx` or `ligttpd` as part of our `CI-Examples`

## Expected results
The results file should display median throughput and latency correctly.

## Actual results without this PR.
When `LOOP = 1` which is the default case, we see only zeros.
```
cat result-220321-091419                                                                                                                   
0,0
0,0
0,0
0,0
0,0
0,0
0,0
0,0
0,0
```

When `LOOP = 2`, the median of two iterations (average value) should be shown but only the smallest of the two loops are shown. Please see below:
```
Run1:
ab -k -n 10000 -c 256 127.0.0.1:8002/random/10K.1.html
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests
concurrency=256, throughput=14279.47, latency=17.928, failed=0

Run2:
ab -k -n 10000 -c 256 127.0.0.1:8002/random/10K.1.html
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests
concurrency=256, throughput=14233.03, latency=17.986, failed=0

cat result-220321-091548                                                                                                      
14233.03,17.928 ===================> Shows the smallest values of both runs instead of median.
```

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/465)

2022-03-18 20:06 UTC, vijaydhanraj reviewed
Replaced ab benchmark with wrk2 as recommended in the nginx example readme. But with wrk2 I did run into an issue with gramine-direct as well as gramine-sgx. I hit this assertion, https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_socket.c#L1450 with https use case. http works fine.

Since lightpd also uses the same script benchmark-http.sh which in turn usesab benchmark. Tested this example with wrk2 and Gramine fails with the below error.
```
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
2022-03-18 00:36:10: connections.c.919) connection closed - read failed: Permission denied
```
Please note the native runs using the wrk2 benchmark runs without any issues.

@dimakuv @boryspoplawski, I have captured the issue with `wrk2` here as well.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-MyTcPCn-CS9dbESGnJW:bh514hh)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2022-03-18 20:23 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MyTgWRm2IcplfYRfmIJ:-MyTgWRn-55S1sFaXKup:b-s3a3um) (no related file):*
This PR lacks description why we actually need it. Such description needs to be put in the commit message.

---


<!-- Sent from Reviewable.io -->

2022-03-18 20:25 UTC, boryspoplawski reviewed
That code is buggy, not sure what can we do about it right now.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-MyTh3D71XP9rEFDHNjb:b-zh6t2u)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-03-18 21:13 UTC, vijaydhanraj reviewed
I see 2 options:
1. Keep this PR on hold until socket refactoring is done.
2. Review and merge the PR as even before this PR `https` test failed with `ab` benchmarking tool for `nginx` example. For `lighttpd` example we should tell our users not to use this script and instead run the test using `curl` or `wget` option.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-MyTqbBnE41U9vTqk5yd:bg5wyml)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MyTgWRm2IcplfYRfmIJ:-MyTqT-00hFz_9MBjDdv:b-chisqb) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This PR lacks description why we actually need it. Such description needs to be put in the commit message.
</blockquote></details>

I have updated the PR description. Please take a look.

---


<!-- Sent from Reviewable.io -->

2022-04-04 07:24 UTC, dimakuv requested changes
I suggest to put this PR on hold. The Big Sockets Rewrite is coming (from Borys), and then we will be able to remove all those warnings from web-browser examples.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-MznSLwV1ynQ-4J73xm3:b-loxlxt)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

___
*[.ci/ubuntu18.04.dockerfile, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSCUv3UrsFSFtM6kb:-MznSCUv3UrsFSFtM6kc:b22jk6) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu18.04.dockerfile#L6)):*
> ```Dockerfile
> # Add steps here to set up dependencies
> RUN apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y \
>     apache2-utils \
> ```

You will need to add steps to install `wrk2` in here. Otherwise CI will fail.
___
*[.ci/ubuntu20.04.dockerfile, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSJzM0tWAk1hBIOio:-MznSJzM0tWAk1hBIOip:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu20.04.dockerfile#L5)):*
> ```Dockerfile
> # Add steps here to set up dependencies
> RUN apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y \
>     apache2-utils \
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-04-04 19:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[.ci/ubuntu18.04.dockerfile, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSCUv3UrsFSFtM6kb:-MzpxF0GCIP2xRC1IJq_:b-38n2n7) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu18.04.dockerfile#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You will need to add steps to install `wrk2` in here. Otherwise CI will fail.
</blockquote></details>

`wrk2` isn't a package like `ab`. We need to clone the source, `make` the sources, and then copy the binary to `/usr/local/bin`. I wasn't sure if this could be done in the dockerfile and assumed it needed manual installation. 

Do the steps below work for our CI? (PS: I haven't tried this before and just based on some readings online have put together the steps)
```
RUN git clone https://username:password@github.com/giltene/wrk2.git

RUN cd wrk2
RUN make

RUN cp wrk /usr/local/bin
RUN cd..
```


<!-- Sent from Reviewable.io -->

2022-04-05 06:10 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

___
*[.ci/ubuntu18.04.dockerfile, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSCUv3UrsFSFtM6kb:-MzsKapL0jzPFVPsl-ot:b-77ryt3) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu18.04.dockerfile#L6)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`wrk2` isn't a package like `ab`. We need to clone the source, `make` the sources, and then copy the binary to `/usr/local/bin`. I wasn't sure if this could be done in the dockerfile and assumed it needed manual installation. 

Do the steps below work for our CI? (PS: I haven't tried this before and just based on some readings online have put together the steps)
```
RUN git clone https://username:password@github.com/giltene/wrk2.git

RUN cd wrk2
RUN make

RUN cp wrk /usr/local/bin
RUN cd..
```
</blockquote></details>

Looks reasonable, but you don't need to prepend every new command with `RUN`, you can just string them together using `&&`. For inspiration, see https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.common.compile.template

- `git clone https://username:password@github.com/giltene/wrk2.git` -- you don't need the `username:password` here.

- Why do you need `cp wrk /usr/local/bin`? Is that the installation procedure for `wrk2`? Surprising :)

- `cd..` -- here you have a typo (forgot the space)


<!-- Sent from Reviewable.io -->

2022-04-05 16:27 UTC, vijaydhanraj reviewed
Sure.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-MzuY-u45Z1cI5y4T6We:b-80tlqk)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[.ci/ubuntu18.04.dockerfile, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSCUv3UrsFSFtM6kb:-MzuXUOG5kXi9R0bkZ9J:bmhiuvt) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu18.04.dockerfile#L6)):*
Thanks for the pointer and the suggestions. I have added the installation steps in the dockerfile.

> Why do you need cp wrk /usr/local/bin? Is that the installation procedure for wrk2? Surprising :)

yes, that is what their wiki page suggests. https://github.com/giltene/wrk2/wiki/Installing-wrk2-on-Linux#ubuntudebian-clean-box
___
*[.ci/ubuntu20.04.dockerfile, line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/465#-MznSJzM0tWAk1hBIOio:-MzuYPzm18Zdp4yD7vGN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/.ci/ubuntu20.04.dockerfile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 07:59 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MzxsRTU439QnfGVPY4l:-MzxsRTVByn8VCHQEUwr:b-6ofett) (no related file):*
The PR looks good to me. Blocking only because we agreed to wait for Borys's Big Sockets Rewrite.

---


<!-- Sent from Reviewable.io -->

2022-05-13 21:55 UTC, boryspoplawski commented
@vijaydhanraj Could you check what happens on https://github.com/gramineproject/gramine/pull/579 ?

2022-05-13 23:34 UTC, vijaydhanraj reviewed
Rebased this PR to latest master. `Commit ID: 80be43132c257e3b85c28847732f4bb989c4eb5d`

Without patch #579 , see the error below for both`gramine-direct` and `graine-sgx` with `https` use case.

```
../common_tools/benchmark-http.sh https://127.0.0.1:8444
wrk -c 100 -d 30 -t 1 -R 10000 https://127.0.0.1:8444/random/10K.1.html
[P5:T5:nginx] assert failed ../LibOS/shim/src/sys/shim_socket.c:1448 total_bytes < peek_buffer->end - peek_buffer->start
[P1:shim] error: Child process (vmid: 0x5) got disconnected
assert failed ../Pal/src/db_object.c:51 !UNKNOWN_HANDLE(handle_array[i])
[1]  + 102777 exit 131   gramine-sgx ./nginx
```

With patch #579, both`gramine-direct` and `gramine-sgx` seem to just stop without showing any error. `wrk2` output redirected to a result file is empty which is not the case with `http` test.

I did try to enable debug traces but even this doesn't show any errors, but the test doesn't seem to be complete. Please see the attached logs.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465#-:-N1zeA7REGHqeKIlWnpA:b-rj5pwn)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-05-13 23:34 UTC, vijaydhanraj commented
[sgx-nginx_https_test.txt](https://github.com/gramineproject/gramine/files/8691741/sgx-nginx_https_test.txt)
[direct-nginx_https_test.txt](https://github.com/gramineproject/gramine/files/8691743/direct-nginx_https_test.txt)

2022-05-13 23:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N1zn3AdAQwudMnUWpiz:bxkksle) (no related file):*
@vijaydhanraj hard to say, there is nothing in the log, you would need to run it with `all` log_level. But judging where it failed before I suspect it's `MSG_PEEK`, which is not yet implemented

___


<!-- Sent from Reviewable.io -->

2022-05-14 00:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N1zv3JUAWfmetjThJ4l:b-qqaae1) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@vijaydhanraj hard to say, there is nothing in the log, you would need to run it with `all` log_level. But judging where it failed before I suspect it's `MSG_PEEK`, which is not yet implemented
</blockquote></details>

There is an error log generated (found this path after enabling `all` trace :)). I have attached both logs, hope this helps.
Based on a quick glance `shim_recvfrom` seems to fail with `-ENOSYS`.

___


<!-- Sent from Reviewable.io -->

2022-05-14 00:31 UTC, vijaydhanraj commented
[error.log](https://github.com/gramineproject/gramine/files/8691880/error.log)
[sgx-nginx_https_test_all.zip](https://github.com/gramineproject/gramine/files/8691883/sgx-nginx_https_test_all.zip)

2022-05-14 16:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N22Ni5H9y353eYcpIbK:b-ix7wpp) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There is an error log generated (found this path after enabling `all` trace :)). I have attached both logs, hope this helps.
Based on a quick glance `shim_recvfrom` seems to fail with `-ENOSYS`.

</blockquote></details>

Thanks. This is indeed missing `MSG_PEEK`. Will need to add it (hoped it can wait for a follow up PR, but seems it used by nginx)

___


<!-- Sent from Reviewable.io -->

2022-05-15 04:21 UTC, gstrauss commented
lighttpd responds quite quickly to wrk requests in many different standard OS environments.  If there is something lighttpd could do better in the gramine environment, please let me know.

2022-05-15 15:15 UTC, boryspoplawski commented
@gstrauss Thanks! For now we need to add all missing functionality to Gramine :)

2022-05-19 12:29 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N2RHVEx1VKSrheb9yD3:b-ufy4fm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Just a note: yes, `MSG_PEEK` is a functionality required by many known workloads. I remember adding it like a year ago, for some workload (maybe it was Nginx). Anyway, what I'm trying to say is that is makes sense to add `MSG_PEEK` directly in your Big Sockets Rewrite PR, not in a follow-up PR.
</blockquote></details>

@vijaydhanraj Could you check now? I added support for `MSG_PEEK` (though some corner cases are not supported, but I think we will have to live with it).

___


<!-- Sent from Reviewable.io -->

2022-05-19 15:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N2RrlYWB5oCU5DmesWP:b-m3risn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@vijaydhanraj Could you check now? I added support for `MSG_PEEK` (though some corner cases are not supported, but I think we will have to live with it).
</blockquote></details>

@boryspoplawski I kept the same environment, which is same commit ID `80be43132c257e3b85c28847732f4bb989c4eb5d` and applied this PR. On top of this, I applied your patch #579. 

With this environment, I see both `gramine-direct` and `gramine-sgx` pass now with `https` use case which was failing before. I also tested with `http` use case and this works as well. 

So, PR #579 fixes the issue.

___


<!-- Sent from Reviewable.io -->

2022-05-19 16:19 UTC, boryspoplawski requested changes
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N1zn3AdAQwudMnUWpiy:-N2RvVvm3_faILaElzH-:br6vt1b) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@boryspoplawski I kept the same environment, which is same commit ID `80be43132c257e3b85c28847732f4bb989c4eb5d` and applied this PR. On top of this, I applied your patch #579. 

With this environment, I see both `gramine-direct` and `gramine-sgx` pass now with `https` use case which was failing before. I also tested with `http` use case and this works as well. 

So, PR #579 fixes the issue.
</blockquote></details>

Good to hear, thanks for checking

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2Ryua2DPeTkLz5o0HO):*
`units` -> `prefixes` 
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2S46tD1UcmkdSW2Ekm:b-y55y26) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Actually, after I started reviewing this: can we rewrite it to python? bash is annoying...
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RxYGk8uHdu87_t9sP:-N2RxYGlC0OPkAS3aHsx:banos05) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L14)):*
> ```Shell
> DOWNLOAD_HOST=$1
> DOWNLOAD_FILE=random/10K.1.html
> CONNECTIONS=100
> ```

Could you make all of this overwritable via env variables? (i.e. use `${X:-y}` substitution)
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2RyR8k1odF8qLcMOz7:b-9gz5uw) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
> ```Shell
> REQUESTS=10000
> DURATION=30
> CONCURRENCY_LIST=${CONCURRENCY_LIST:-"1 2 4 8 16 32 64"}
> ```

Why shrink the list?
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S2AB-7U8kgICCyUsu:-N2S2AB-7U8kgICCyUsv:baj8n41) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L24)):*
> ```Shell
>     local THROUGHPUT_STR=$1
>     local THROUGHPUT_VAL=$(echo ${THROUGHPUT_STR} | tr -cd '.[0-9]')
>     local THROUGHPUT_UNIT=$(echo ${THROUGHPUT_STR} | tr -dc '[A-za-z]')
> ```

```sh
local THROUGHPUT_VAL=0
local THROUGHPUT_UNIT=""
if [[ "$1" =~ ^([0-9]*)(\.[0-9]*)?([kMG]?)$ ]]; then
    THROUGHPUT_VAL="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
    THROUGHPUT_UNIT=${BASH_REMATCH[3]}
fi
```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4_LJ1lloVvTzPSIb:-N2S0GkT7JFZhhi5kGAN:b32vwxq) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L29)):*
> ```Shell
>         THROUGHPUT=$THROUGHPUT_VAL
>     elif [ "$THROUGHPUT_UNIT" = "k" ]; then
>         THROUGHPUT=`echo "{$THROUGHPUT_VAL*1000}" | bc`
> ```

```THROUGHPUT=`bc <<< "$THROUGHPUT_VAL*1000"` ```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4nbl4x73ZWgEVztx:-N2S4nbmDLI01d9CB9S9:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L31)):*
> ```Shell
>         THROUGHPUT=`echo "{$THROUGHPUT_VAL*1000}" | bc`
>     elif [ "$THROUGHPUT_UNIT" = "M" ]; then
>         THROUGHPUT=`echo "{$THROUGHPUT_VAL*1000000}" | bc`
> ```

ditto
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4pCv0hZmbomTEAjV:-N2S0QOA-wx40cJpHTdj:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L33)):*
> ```Shell
>         THROUGHPUT=`echo "{$THROUGHPUT_VAL*1000000}" | bc`
>     elif [ "$THROUGHPUT_UNIT" = "G" ]; then
>         THROUGHPUT=`echo "{$THROUGHPUT_VAL*1000000000}" | bc`
> ```

ditto
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4vVN45YtqOIUetcb:-N2S4vVN45YtqOIUetcc:b-n5x0pr) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L41)):*
> ```Shell
> }
> 
> latency_in_milliseconds() {
> ```

same comments as above apply to this function
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyM9_8SwJ8bCmAMF3:-N2RyM9_8SwJ8bCmAMF4:b2s2ria) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L72)):*
> ```Shell
>         wrk -c "$CONNECTIONS" -d "$DURATION" -t "$CONCURRENCY" -R "$REQUESTS" "$DOWNLOAD_HOST/$DOWNLOAD_FILE" > OUTPUT || exit $?
> 
>         sleep 5
> ```

What is this?
___
*[`CI-Examples/nginx/README.md` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RxFON76O3VHnu2Yno:-N2RxFON76O3VHnu2Ynp:bly1wqa) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/nginx/README.md#L11)):*
> ```Markdown
> sudo apt-get install -y build-essential libssl-dev zlib1g-dev
> ```
> NOTE: The "benchmark-http.sh" script uses the wrk Benchmark (wrk2) under the
> ```

`benchmark` (no capital letter)


<!-- Sent from Reviewable.io -->

2022-05-20 08:22 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 1 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2Ryua2DPeTkLz5o0HO):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`units` -> `prefixes` 
</blockquote></details>

you meant `suffixes` right?
Also rebased to the latest master and did a force push.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2UuKO595Q4HAJ6K2zQ:bq4qrm3) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, after I started reviewing this: can we rewrite it to python? bash is annoying...
</blockquote></details>

Sure, is it fine if I do this rewrite in a separate PR? If needed I can create an issue and assign it to myself.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RxYGk8uHdu87_t9sP:-N2V6uSl1kpenPGO0Vzu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you make all of this overwritable via env variables? (i.e. use `${X:-y}` substitution)
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2V4sdW4ka2FM8Hsqb_:bz4vqzx) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why shrink the list?
</blockquote></details>

with `wrk2`, the number of connections `-c` must be greater than the number of threads `-t`. I set the connection limit as `100` and so reduced the `CONCURRENCY_LIST` as tests were taking ~5mins to complete. But I have increased the connections to `300` and set the number of threads to the original list. 
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 24 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S2AB-7U8kgICCyUsu:-N2VVVQcBhA4LZQzG3IW:b-y01cqo) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

```sh
local THROUGHPUT_VAL=0
local THROUGHPUT_UNIT=""
if [[ "$1" =~ ^([0-9]*)(\.[0-9]*)?([kMG]?)$ ]]; then
    THROUGHPUT_VAL="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
    THROUGHPUT_UNIT=${BASH_REMATCH[3]}
fi
```
</blockquote></details>

Thanks, done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 29 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4_LJ1lloVvTzPSIb:-N2VVYEA-dLJqq5uDkD3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

```THROUGHPUT=`bc <<< "$THROUGHPUT_VAL*1000"` ```
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4nbl4x73ZWgEVztx:-N2VVZ_k2LQCsYfPWia7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4pCv0hZmbomTEAjV:-N2VV_gBEQnUNIVn7n6J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 41 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S4vVN45YtqOIUetcb:-N2VVaeV-FbmN8S10K3m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

same comments as above apply to this function
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyM9_8SwJ8bCmAMF3:-N2VB8Cr62OKvjGrDEdS:bcaxrza) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

I wasn't sure so retained this sleep value as it was in the original test. Could it be to quiesce between runs?
___
*[`CI-Examples/nginx/README.md` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RxFON76O3VHnu2Yno:-N2VB6uQ-lcQAictpH6z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/nginx/README.md#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`benchmark` (no capital letter)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-20 11:44 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 1 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2WGuVn1QVYBiHa1IdB:b-jd11ea) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure, is it fine if I do this rewrite in a separate PR? If needed I can create an issue and assign it to myself.
</blockquote></details>

If that's the plan, then I guess there's no point in finishing this PR? Maybe you could just create a new one, which rewrites this script in Python?


<!-- Sent from Reviewable.io -->

2022-05-20 12:31 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2Ryua2DPeTkLz5o0HO):*
@vijaydhanraj don't rebase in the middle of the review.
Also changing commit messages can be done on the final rebase before merge.

> you meant suffixes right?

No, I meant prefixes, because if you talk about SI then they are about prefixes to units, e.g. `ms`, `kg`. See https://en.wikipedia.org/wiki/Metric_prefix
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2WPbOa0JCU54rpBqBk:bk5mmvd) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If that's the plan, then I guess there's no point in finishing this PR? Maybe you could just create a new one, which rewrites this script in Python?
</blockquote></details>

Definitely in a separate PR, but there is no point in having both: either we proceed with this one or create a new one with python rewrite.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2WQ1ZV3N7iU0f6M6uN:b-uljfxf) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

with `wrk2`, the number of connections `-c` must be greater than the number of threads `-t`. I set the connection limit as `100` and so reduced the `CONCURRENCY_LIST` as tests were taking ~5mins to complete. But I have increased the connections to `300` and set the number of threads to the original list. 
</blockquote></details>

Well, if they take too long we might not want that, so CI doesn't take too long. Could you give us some numbers, how long does it take to run this (in both versions)? Also some machines in CI are pretty weak (NUCs I think), so it will be even slower than on normal server CPU.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 72 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyM9_8SwJ8bCmAMF3:-N2WRbhj4dqBUMNxaFHw:b-r382ha) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I wasn't sure so retained this sleep value as it was in the original test. Could it be to quiesce between runs?
</blockquote></details>

Yeah, I guess. This is not what we want, but I'm not sure how to tackle this atm, so unblocking.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 47 at r3](https://reviewable.io/reviews/gramineproject/gramine/465#-N2WRJAy3oQG_NJEmjqg:-N2WRJAy3oQG_NJEmjqh:b2hc1ql) ([raw file](https://github.com/gramineproject/gramine/blob/e829d14015b952f8b6c5227ce5b497840e41488f/CI-Examples/common_tools/benchmark-http.sh#L47)):*
> ```Shell
>     local LATENCY_VAL=0
>     local LATENCY_UNIT=""
>     if [[ "$1" =~ ^([0-9]*)(\.[0-9]*)?([umsh]*)$ ]]; then
> ```

The last group should be `(us|ms|s|m|h)`. If just a plain number (without units at the end) is also valid then also add `?` after that group


<!-- Sent from Reviewable.io -->

2022-05-23 04:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2Ryua2DPeTkLz5o0HO):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@vijaydhanraj don't rebase in the middle of the review.
Also changing commit messages can be done on the final rebase before merge.

> you meant suffixes right?

No, I meant prefixes, because if you talk about SI then they are about prefixes to units, e.g. `ms`, `kg`. See https://en.wikipedia.org/wiki/Metric_prefix
</blockquote></details>

Got it, thanks. I have updated the commit message.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2X2aiNCQegiDfq43QS:b-1468zb) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Definitely in a separate PR, but there is no point in having both: either we proceed with this one or create a new one with python rewrite.
</blockquote></details>

We have spent some time reviewing this PR and I think it is close to ready. Given this, I prefer to proceed with this one as it addresses the issues we were primarily targeting to solve, that is to use `wrk` benchmark and fix the median calculation. Python rewrite is nice to have, and I can take this up after completing other small pending PRs that were dependent on sysfs.

This is just my thought and will let the maintainers decide.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2Yw-aw6Ye6-9ZzkrKF:b-s92wsp) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, if they take too long we might not want that, so CI doesn't take too long. Could you give us some numbers, how long does it take to run this (in both versions)? Also some machines in CI are pretty weak (NUCs I think), so it will be even slower than on normal server CPU.
</blockquote></details>

I do have the `-d` duration option set to 30 seconds, so with `CONCURRENCY_LIST` being 9, the run takes ~5min even on the NUC platform. 
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 47 at r3](https://reviewable.io/reviews/gramineproject/gramine/465#-N2WRJAy3oQG_NJEmjqg:-N2Yz4mi57OgDEmoj6CU:b-a69ikn) ([raw file](https://github.com/gramineproject/gramine/blob/e829d14015b952f8b6c5227ce5b497840e41488f/CI-Examples/common_tools/benchmark-http.sh#L47)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The last group should be `(us|ms|s|m|h)`. If just a plain number (without units at the end) is also valid then also add `?` after that group
</blockquote></details>

Done and yes, I have added `?` as we can have just a plain number.


<!-- Sent from Reviewable.io -->

2022-05-23 07:47 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2jsGpUAZfdCG5ZKswx:b4oojny) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We have spent some time reviewing this PR and I think it is close to ready. Given this, I prefer to proceed with this one as it addresses the issues we were primarily targeting to solve, that is to use `wrk` benchmark and fix the median calculation. Python rewrite is nice to have, and I can take this up after completing other small pending PRs that were dependent on sysfs.

This is just my thought and will let the maintainers decide.


</blockquote></details>

To be honest, why do we care about this script?

I would prefer to update it here, in this PR, once, and forget about it forever. Ideally, I would just remove it and use normal benchmarks instead of this ad-hoc random script.


<!-- Sent from Reviewable.io -->

2022-05-23 14:23 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2lHYOl2S5EYUiZ8C2D:b-wmgksn) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, why do we care about this script?

I would prefer to update it here, in this PR, once, and forget about it forever. Ideally, I would just remove it and use normal benchmarks instead of this ad-hoc random script.
</blockquote></details>

Sure, let's finish this then
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2lHjQvCr9zxonklX-P:b-5bpxql) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I do have the `-d` duration option set to 30 seconds, so with `CONCURRENCY_LIST` being 9, the run takes ~5min even on the NUC platform. 
</blockquote></details>

And could you check the shorter version? How much is the difference?


<!-- Sent from Reviewable.io -->

2022-05-23 15:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2lOkVC856Z712Ux3Vd:b-v1zohf) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, let's finish this then
</blockquote></details>

@dimakuv the script is to trim unnecessary output and present the relevant information to the end-user. So, we might need it.

@boryspoplawski you mean to remove this script?
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2lO8igDkJbNiqUPQxy:b-a4c48i) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And could you check the shorter version? How much is the difference?
</blockquote></details>

On my NUC it takes a little over 4mins, like 4mins and 10 or 15s if we reduce the list by removing `128` and `256`.


<!-- Sent from Reviewable.io -->

2022-05-23 15:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2lSgZp8wpmvIDDfbQF:b-k3omyw) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv the script is to trim unnecessary output and present the relevant information to the end-user. So, we might need it.

@boryspoplawski you mean to remove this script?
</blockquote></details>

Just in case, to clarify: I'm fine with this PR. I'm only blocking on my top-level comment: this should be merged after the Borys's #579.


<!-- Sent from Reviewable.io -->

2022-05-24 00:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2nNY_rAkTAZvbLG5Tm:b-wqgep4) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just in case, to clarify: I'm fine with this PR. I'm only blocking on my top-level comment: this should be merged after the Borys's #579.
</blockquote></details>

I meant that we can go on with this PR, since we decided not to rewrite this to python (now or ever)
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2nNerw04Uutd3YiBKQ:boucbfe) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

On my NUC it takes a little over 4mins, like 4mins and 10 or 15s if we reduce the list by removing `128` and `256`.
</blockquote></details>

4min vs 15s? That's a huge difference (but not unexpected). Idk, we need to decide on something. Maybe a middle ground of just removing `256`? I would expect this to take a minute in such case
cc @dimakuv @mkow 


<!-- Sent from Reviewable.io -->

2022-05-24 00:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2nOaSf5fG9r7KV21ET:b-rd1x7k) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

4min vs 15s? That's a huge difference (but not unexpected). Idk, we need to decide on something. Maybe a middle ground of just removing `256`? I would expect this to take a minute in such case
cc @dimakuv @mkow 
</blockquote></details>

my bad, I meant anywhere between 4mins 10sec to 4 min 15sec so at most we save a minute if we don't include `128` and `256`  


<!-- Sent from Reviewable.io -->

2022-05-24 00:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MzxsRTU439QnfGVPY4l:-N2nQH8TCp0BThNGwI2Q:b-78k9bt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me. Blocking only because we agreed to wait for Borys's Big Sockets Rewrite.
</blockquote></details>

Approve from me as well, except it needs to wait for that PR

___
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2nPuWyB8RAT2tTSbsk:bqpuclg) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

my bad, I meant anywhere between 4mins 10sec to 4 min 15sec so at most we save a minute if we don't include `128` and `256`  
</blockquote></details>

Oh, then let's have them, that's not that bad.
I thought this might exponentially increase the runtime, but it's seems not to be the case, at least at this scale


<!-- Sent from Reviewable.io -->

2022-05-24 06:48 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 71 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2ooeKk9MeyTu5gQcVJ:-N2ooeKk9MeyTu5gQcVK:bul84li) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu18.04.dockerfile#L71)):*
> ```Dockerfile
>     zlib1g-dev
> 
> # Install wrk2 benchmark. This benchmark is used in `nginx` and `lighttpd` CI-Examples.
> ```

...and `rust` example (this was added in the meantime)
___
*[`.ci/ubuntu20.04.dockerfile` line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2oojh817fLWL-V1tVB:-N2oojh817fLWL-V1tVC:bul84li) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu20.04.dockerfile#L75)):*
> ```Dockerfile
>     zlib1g-dev
> 
> # Install wrk2 benchmark. This benchmark is used in `nginx` and `lighttpd` CI-Examples.
> ```

...and `rust` example (this was added in the meantime)
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2RyR8k1odF8qLcMOz6:-N2onsUWB4koyMZVae9D:bdwxfon) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L17)):*
> Well, if they take too long we might not want that, so CI doesn't take too long. Could you give us some numbers, how long does it take to run this (in both versions)? Also some machines in CI are pretty weak (NUCs I think), so it will be even slower than on normal server CPU.

In our CI, we overwrite this list to contain only `1 32` (for faster execution):
- https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/.ci/lib/stage-test-sgx.jenkinsfile#L58
- https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/.ci/lib/stage-test-direct.jenkinsfile#L72

So for CI, what we have here doesn't matter. The current version (that doesn't change the list and keeps 128 and 256) is fine with me.


<!-- Sent from Reviewable.io -->

2022-05-25 05:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 71 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2ooeKk9MeyTu5gQcVJ:-N2taivbEkfaBicvI06F:blnfmxg) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu18.04.dockerfile#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...and `rust` example (this was added in the meantime)
</blockquote></details>

Got it, done.
___
*[`.ci/ubuntu20.04.dockerfile` line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2oojh817fLWL-V1tVB:-N2taoQBCL8rhUJ8YN54:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu20.04.dockerfile#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...and `rust` example (this was added in the meantime)
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/465#-N2S46tD1UcmkdSW2Ekl:-N2tb6YPDsiyDXEi9a_j:brujztc) ([raw file](https://github.com/gramineproject/gramine/blob/de6c62de9bb7e14a9925af4b078f8e77112198b3/CI-Examples/common_tools/benchmark-http.sh#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant that we can go on with this PR, since we decided not to rewrite this to python (now or ever)
</blockquote></details>

OK, thanks.


<!-- Sent from Reviewable.io -->

2022-05-25 14:26 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 71 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2ooeKk9MeyTu5gQcVJ:-N2vaoFuAyXDnHcK94YP:bptk23m) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu18.04.dockerfile#L71)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, done.
</blockquote></details>

Actually what's the point of listing all places which use it? Maybe just mention that it's used in `benchmark-http.sh`
___
*[`.ci/ubuntu20.04.dockerfile` line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2oojh817fLWL-V1tVB:-N2vb0_15DDW3KNiE-8I:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu20.04.dockerfile#L75)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-05-26 02:20 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 5 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 71 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2ooeKk9MeyTu5gQcVJ:-N2y9YdH-oFMjpjhslyP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu18.04.dockerfile#L71)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually what's the point of listing all places which use it? Maybe just mention that it's used in `benchmark-http.sh`
</blockquote></details>

Done.
___
*[`.ci/ubuntu20.04.dockerfile` line 75 at r4](https://reviewable.io/reviews/gramineproject/gramine/465#-N2oojh817fLWL-V1tVB:-N2y9_3s2wLuJsTUYTy7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9d008a0dc220bd2e03b83d4b9c0c73c683d55c11/.ci/ubuntu20.04.dockerfile#L75)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-03 15:08 UTC, boryspoplawski reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-06-17 21:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MzxsRTU439QnfGVPY4l:-N4ncwA95RlZzfW04xkh:b-x77jf3) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Approve from me as well, except it needs to wait for that PR
</blockquote></details>

All right, #579 merged. @vijaydhanraj please rebase to the newest master

___


<!-- Sent from Reviewable.io -->

2022-06-17 22:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 5 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-MzxsRTU439QnfGVPY4l:-N4nmRab5Oq9FBfyncjw:bk6za2x) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right, #579 merged. @vijaydhanraj please rebase to the newest master
</blockquote></details>

Thanks @boryspoplawski, done.

___


<!-- Sent from Reviewable.io -->

2022-06-17 23:54 UTC, mkow commented
Jenkins, retest this please

2022-06-18 00:20 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1, 1 of 6 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N4o5YMs0WdS-xNnlHV6:bbs0zr4) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
> ```Dockerfile
> 
> # Install wrk2 benchmark. This benchmark is used in `benchmark-http.sh`.
> RUN git clone https://github.com/giltene/wrk2.git \
> ```

Please pin to a specific commit, not "whatever happens to be right now on master".
___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5ejh-zkq87ortqk3:-N4o5ejh-zkq87ortqk4:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu20.04.dockerfile#L76)):*
> ```Dockerfile
> 
> # Install wrk2 benchmark. This benchmark is used in `benchmark-http.sh`.
> RUN git clone https://github.com/giltene/wrk2.git \
> ```

ditto
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 83 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o7iDeB3o6vgDvvm_M:-N4o7iDeB3o6vgDvvm_N:b-90sfmu) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L83)):*
> ```Shell
>         THROUGHPUT=$(throughput_in_bytes $THROUGHPUT_STR)
>         if [ "$THROUGHPUT" = "0" ]; then
>             echo "Throughput is empty!"; exit 1;
> ```

Empty? Didn't you just check it to be zero?



_Code quote:_
```Shell
Throughput is empty!
```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 89 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o7vgS1HPWEWu9m0bv:-N4o7vgS1HPWEWu9m0bw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L89)):*
> ```Shell
>         LATENCY=$(latency_in_milliseconds $LATENCY_STR)
>         if [ "$LATENCY" = "0" ]; then
>             echo "Latency is empty!"; exit 1;
> ```

ditto



_Code quote:_
```Shell
Latency is empty!
```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 99 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o81nh7-pZLb2HRBtc:-N4o81nh7-pZLb2HRBtd:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L99)):*
> ```Shell
>             LATENCIES[$CONCURRENCY]="${LATENCIES[$CONCURRENCY]} $LATENCY"
>         fi
>         echo "Run:$(($RUN+1)) Concurrency:$CONCURRENCY Per thread Throughput(bytes) = $THROUGHPUT, Latency(ms) = $LATENCY"
> ```





_Suggestion:_
```Shell
Throughput (bytes)
```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 99 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o8FHk8Q6z7UMAB36N:-N4o86z4044na1GIt8Ze:bkp42o3) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L99)):*
> ```Shell
>             LATENCIES[$CONCURRENCY]="${LATENCIES[$CONCURRENCY]} $LATENCY"
>         fi
>         echo "Run:$(($RUN+1)) Concurrency:$CONCURRENCY Per thread Throughput(bytes) = $THROUGHPUT, Latency(ms) = $LATENCY"
> ```

Please unify, you use both `key:val` and `key = val` in the same log line.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 108 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o94kt8Bk95SPhfH-L:-N4o94kt8Bk95SPhfH-M:b-jb3uso) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L108)):*
> ```Shell
> do
>     THROUGHPUT=$(echo "${THROUGHPUTS[$CONCURRENCY]}" | tr " " "\n" | sort -n | awk '{a[NR]=$0}END{if(NR%2==1)print a[(NR + 1)/2];else print (a[NR/2]+a[NR/2 + 1])/2}')
>     LATENCY=$(echo "${LATENCIES[$CONCURRENCY]}" | tr " " "\n" | sort -n | awk '{a[NR]=$0}END{if(NR%2==1)print a[(NR + 1)/2];else print (a[NR/2]+a[NR/2 + 1])/2}')
> ```

Is this actually correct?

Also, @vijaydhanraj: next time you start writing a Bash script which is longer than 10 lines you should stop and switch to a language which is less obfuscated and hacky, this script is really unreadable.



_Code quote:_
```Shell
print a[(NR + 1)/2]
```
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 110 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o9ZUs4e0qebWV40_I:-N4o9ZUs4e0qebWV40_J:b62r0uv) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L110)):*
> ```Shell
>     LATENCY=$(echo "${LATENCIES[$CONCURRENCY]}" | tr " " "\n" | sort -n | awk '{a[NR]=$0}END{if(NR%2==1)print a[(NR + 1)/2];else print (a[NR/2]+a[NR/2 + 1])/2}')
>     printf "Concurrency = %3d: Per Thread Median Througput(bytes) = %9.3f, Latency(ms) = %9.3f\n" \
>         "$CONCURRENCY" "$THROUGHPUT" "$LATENCY" | tee -a $RESULT
> ```

ditto (formatting)


<!-- Sent from Reviewable.io -->

2022-06-20 09:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 4 of 7 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N5-264pAyjEOUouJF5w:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please pin to a specific commit, not "whatever happens to be right now on master".
</blockquote></details>

Done.
___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5ejh-zkq87ortqk3:-N5-283A9-TuO60GWCNG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 83 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o7iDeB3o6vgDvvm_M:-N5-2AufBVnILys-QVOS:b1qe4yg) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Empty? Didn't you just check it to be zero?
</blockquote></details>

Changed to zero.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 89 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o7vgS1HPWEWu9m0bv:-N5-1r4cEgxmNc8bt0H1:bbig7g2) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Changed to zero.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 99 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o81nh7-pZLb2HRBtc:-N5-1uBmB7e0DD3m49bx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L99)):*
> ```Shell
>             LATENCIES[$CONCURRENCY]="${LATENCIES[$CONCURRENCY]} $LATENCY"
>         fi
>         echo "Run:$(($RUN+1)) Concurrency:$CONCURRENCY Per thread Throughput(bytes) = $THROUGHPUT, Latency(ms) = $LATENCY"
> ```

Done.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 99 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o8FHk8Q6z7UMAB36N:-N5-1vntEO7NG-Aa7ErA:baj0c5i) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please unify, you use both `key:val` and `key = val` in the same log line.
</blockquote></details>

Followed `key = val` pattern.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 108 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o94kt8Bk95SPhfH-L:-N5-MWsI4fpx14OJbAbE:bn4i3fp) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L108)):*
>Is this actually correct?

Do you see any issues?

>next time you start writing a Bash script which is longer than 10 lines you should stop and switch to a language which is less obfuscated and hacky, this script is really unreadable.

Yes, agree. If needed I can create an issue for this rewrite and get back to it when I have some cycles.
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 110 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o9ZUs4e0qebWV40_I:-N5-21VD96M-xBFKEI6S:bwrccm2) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L110)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (formatting)
</blockquote></details>

Done, added spaces before brackets.


<!-- Sent from Reviewable.io -->

2022-06-20 11:36 UTC, mkow requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N5-sJ8I-ItDsmEFdkVL:b-q99vls) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`reset --hard`? Why not just `checkout`?
___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r8](https://reviewable.io/reviews/gramineproject/gramine/465#-N5-sbRI5QnitPMS-lHO:-N5-sbRJ5MU_jf8qXx1S:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/75641516d381a1473e0bb15be67a9ad9513f0028/.ci/ubuntu18.04.dockerfile#L72)):*
> ```Dockerfile
> 
> # Install wrk2 benchmark. This benchmark is used in `benchmark-http.sh`.
> RUN git clone https://github.com/giltene/wrk2.git \
> ```





_Suggestion:_
```Dockerfile
git clone --depth 1 https://github.com/giltene/wrk2.git
```
___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5ejh-zkq87ortqk3:-N5-skF_EQhK_VBLKTKt:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r8](https://reviewable.io/reviews/gramineproject/gramine/465#-N5-sjb15SDVzeUs8Iuw:-N5-sjb24RLD0OY6waoL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/75641516d381a1473e0bb15be67a9ad9513f0028/.ci/ubuntu20.04.dockerfile#L76)):*
> ```Dockerfile
> 
> # Install wrk2 benchmark. This benchmark is used in `benchmark-http.sh`.
> RUN git clone https://github.com/giltene/wrk2.git \
> ```

ditto
___
*[`CI-Examples/common_tools/benchmark-http.sh` line 108 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o94kt8Bk95SPhfH-L:-N5-stR6DTF5tkkGruUB:b-g5w30p) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L108)):*
> Do you see any issues?

Doesn't it _always_ pick a wrong element in this case?

> Yes, agree. If needed I can create an issue for this rewrite and get back to it when I have some cycles.

Nah, if we already reviewed most of it then we can keep it for now.


<!-- Sent from Reviewable.io -->

2022-06-20 15:52 UTC, mkow reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 108 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o94kt8Bk95SPhfH-L:-N50o8OY7SQbX_zZ1z7P:b-3kdbgu) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L108)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> Doesn't it always pick a wrong element in this case?

It does seem to do the right thing. I tried 3 cases where I set the loop = 1, 3, and 4 and in all the cases I do see the median picked properly.
```
LOOP=1 ../common_tools/benchmark-http.sh http://127.0.0.1:8002
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 1 Per thread Throughput (bytes) = 10640.00, Latency (ms) = 1.86
1 1.86
Concurrency =   1: Per Thread Median Througput (bytes) = 10640.000, Latency (ms) =     1.860
```

```
LOOP=3 ../common_tools/benchmark-http.sh http://127.0.0.1:8002
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 1 Per thread Throughput (bytes) = 10570.00, Latency (ms) = 1.86
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 2 Concurrency = 1 Per thread Throughput (bytes) = 10600.00, Latency (ms) = 1.29
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 3 Concurrency = 1 Per thread Throughput (bytes) = 10730.00, Latency (ms) = 1.93
1 1.29
2 1.86
3 1.93
Concurrency =   1: Per Thread Median Througput (bytes) = 10600.000, Latency (ms) =     1.860
```

```
LOOP=4 ../common_tools/benchmark-http.sh http://127.0.0.1:8002
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 1 Per thread Throughput (bytes) = 10580.00, Latency (ms) = 1.20
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 2 Concurrency = 1 Per thread Throughput (bytes) = 10600.00, Latency (ms) = 1.37
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 3 Concurrency = 1 Per thread Throughput (bytes) = 10690.00, Latency (ms) = 1.71
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 4 Concurrency = 1 Per thread Throughput (bytes) = 10700.00, Latency (ms) = 1.92
1 1.20
2 1.37
3 1.71
4 1.92
Concurrency =   1: Per Thread Median Througput (bytes) = 10645.000, Latency (ms) =     1.540
```

>Nah, if we already reviewed most of it then we can keep it for now.

ok sounds good.
</blockquote></details>

Umm, wait, are arrays in `awk` indexed from 1 maybe? That would explain why it works...


<!-- Sent from Reviewable.io -->

2022-06-20 17:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`CI-Examples/common_tools/benchmark-http.sh` line 108 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o94kt8Bk95SPhfH-L:-N517-D39pwQgv5a74fm:b2wdgse) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/CI-Examples/common_tools/benchmark-http.sh#L108)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, `awk` indexes array from 1.
</blockquote></details>

Ok, then this is even less readable than I thought...


<!-- Sent from Reviewable.io -->

2022-06-22 12:27 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r7, 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N4sjr9l8MgoVFxvKSHg:b-u8g0d8) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed to `checkout`
</blockquote></details>

1. `checkout` won't work with `--depth 1` (unless it's the top commit on master, but then it's pointless and will break as soon as something changes).
2. What's wrong with using master here? I would expect that project to be rather stable
___
*[`.ci/ubuntu20.04.dockerfile` line 76 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5ejh-zkq87ortqk3:-N5ANCL8ENkLzYZIflda:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu20.04.dockerfile#L76)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-06-22 12:31 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N5AO5OFBy1zCM2bAEbJ:b-almej4) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. `checkout` won't work with `--depth 1` (unless it's the top commit on master, but then it's pointless and will break as soon as something changes).
2. What's wrong with using master here? I would expect that project to be rather stable
</blockquote></details>

1. Oh, right, didn't notice this. We can drop `--depth 1` then.
2. We want to pin to a specific version, same as we do will all downloads.


<!-- Sent from Reviewable.io -->

2022-06-22 17:29 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N5BSEEN8l0Ju1fsdx0S:b4dxa46) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
Sorry, my comment got mixed with the earlier response.

>What's wrong with using master here? I would expect that project to be rather stable

 @mkow, @boryspoplawski's observation is true. They are indeed stable and haven't merged any PR since Sept 2019. So, in future if they have any, we should adopt them as they might have valid fixes. So, using master here should be fine.

Please confirm which way you prefer and I can do it.


<!-- Sent from Reviewable.io -->

2022-06-22 17:45 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[`.ci/ubuntu18.04.dockerfile` line 72 at r7](https://reviewable.io/reviews/gramineproject/gramine/465#-N4o5YMr7NO_WcC4jOnB:-N5BUimd7JGEbBEoVdJ7:b-31dec3) ([raw file](https://github.com/gramineproject/gramine/blob/0fa06fd6a52d53d9bc57d01c02829cb7d6964955/.ci/ubuntu18.04.dockerfile#L72)):*
> They are indeed stable and haven't merged any PR since Sept 2019.

No commits on master for 3 years? You mean "dead", not "stable" ;)

> So, in future if they have any, we should adopt them as they might have valid fixes.

Yes, we will adopt them, by updating the commit hash here. And they may also contain accidental or intended API changes, and then our CI will break.

> So, using master here should be fine.

No, it's not fine. We don't want to suddenly have all our CI failing because someone from some random project started merging pull requests without thorough testing.

So, just drop this `--depth 1` and that's all.


<!-- Sent from Reviewable.io -->

2022-06-22 20:28 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-06-22 20:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N5C5rb_6eZzTppPi3w_:-N5C5rb_6eZzTppPi3wa:b-59aokl) (no related file):*
@vijaydhanraj: `./.ci/run-shellcheck` failed on your script, please fix.

___


<!-- Sent from Reviewable.io -->

2022-06-22 21:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N5C5rb_6eZzTppPi3w_:-N5CGMh_0OWDQW9-12mn:b-weyodi) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vijaydhanraj: `./.ci/run-shellcheck` failed on your script, please fix.
</blockquote></details>

Thanks @mkow. I have fixed the issues; can you please restart Jenkins?

Didn't know we had this tool, works very nicely.

___


<!-- Sent from Reviewable.io -->

2022-06-22 22:02 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: 4 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/465#-N5C5rb_6eZzTppPi3w_:-N5CQlAdEmD4AWpeOlTo:bfgzhew) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Another failure now:
```
23:40:17  + LOOP=1 CONCURRENCY_LIST=1 32 ../common_tools/benchmark-http.sh 127.0.0.1:3000
23:40:17  wrk -c 300 -d 30 -t 1 -R 10000 127.0.0.1:3000/random/10K.1.html
23:40:17  invalid URL: 127.0.0.1:3000/random/10K.1.html
```
</blockquote></details>

I think I have addressed the issue.

___


<!-- Sent from Reviewable.io -->

2022-06-22 23:34 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-23 08:16 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-06-23 11:23 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-06-23 11:27 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/465)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-23 12:03 UTC, merged