[Pal/Linux-SGX] Enable SGX hotspots profiling with Intel(R) VTune Pro…
gramineproject/gramine pull request #478
Opened 2022-03-29 12:01 UTC by svenkata9

…filer

Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>

## Description of the changes 
This PR enables SGX hotspots profiling with Intel&reg; VTune&trade; Profiler.

## How to test this PR? 
- Install Intel&reg; VTune&trade; Profiler from [here ](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/installation.html).
- Build Gramine with ``-Dvtune_sgx_profiling=enabled -Dvtune_sdk_path=<VTune SDK installation path>``.
- Add ``sgx.vtune_profiling = true`` to the manifest.
- Run your application under vtune.

   ``vtune -collect sgx-hotspots -- gramine-sgx <workload>``
      
   It will output the data collected to a directory of the format ``r000sgxhs``.

- To view the report, run ``vtune -report hotspots -r <vtune data collection output directory>``

- Alternatively, the report can be viewed in Install Intel&reg; VTune&trade; Profiler also.

![image](https://user-images.githubusercontent.com/29835993/160606444-fc845d20-d966-4572-9bf8-fc20fd3190e8.png)

2022-03-29 13:00 UTC, svenkata9 commented
Just a quick comment: The screenshot is from an older version of Gramine (had to go to Make to enable it first to avoid Meson issues). But, it works perfectly well with the latest master.

2022-03-29 13:44 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKlWY14RoIKNSp9a97:-MzKu3onAEScupG3qMx7:be736ln) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, why would we need this, if we already have full perf support? Not saying I'm against this as the change is quite small, but would like to hear why we should bother supporting another tool.
</blockquote></details>

First it was requested by many internal Intel teams. And, why would we not add support to a popular perf tool. Is that a problem. I have also requested more features to the internal team.

And, we also had a TODO to support this (please see Documentation changes)

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKm-RV6W8Xx54L1aU4:-MzKuIVV-HT5v5S8UbPN:bxou8a9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

From looking at the screenshot, this integration looks partial at best. It says that 38% of the runtime was spent "outside any known module". Why would you use it instead of perf, where everything works well?
</blockquote></details>

The outside of any known module could be the stripped versions of the binary itself. This was run against bash

---


<!-- Sent from Reviewable.io -->

2022-03-29 16:02 UTC, pwmarcz commented
I would suggest another way: if you want to use VTune, maybe you can open the `perf` traces that Gramine-SGX already produces? Importing these files [seems to be already supported by VTune](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/analyze-performance/manage-result-files/importing-results-to-gui.html#importing-results-to-gui_GUID-D04DB66A-5CD9-4E7D-AB0A-2137CC659449).

I'm not sure if VTune will open these files in their current shape. We might need to modify Gramine to output more data (see [sgx_perf_data.c](https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/sgx_perf_data.c)). But still, from the maintenance perspective, that sounds like a far better option than adding a whole new conditionally-built subsystem.

2022-03-30 02:10 UTC, svenkata9 reviewed
I have tried this before with our perf traces and it didn't. And, the current implementation is not a whole lot - does not bring in a lot of new code, and I have even abstracted the dependencies to the external installation unlike some other software integrating the vtune sdk code inside the repo.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478#-:-MzN_Pm36uJFy9HkeVFb:b8olmwv)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKm-RV6W8Xx54L1aU4:-MzN_0k06qf4EVjs4JK3:bmt6n7f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why there's no LibOS code on the listing then?
</blockquote></details>

Because they aren't the hotspots.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKlWY14RoIKNSp9a97:-MzN_6Rg7tNeSs0NQk7c:b-nfa8qz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> why would we not add support to a popular perf tool

Because it requires additional maintenance.

> And, we also had a TODO to support this

True, but that's not an argument for adding it, it only says that in the past someone made a note that it may be nice to add it ;) This doesn't waive the need for evaluation whether we really want to add this functionality or not.
</blockquote></details>

I would still add because it is much controlled in a fashion that if someone wants it they can enable during the build. And, we had many requests from internal teams for this support. There are multiple datapoints from these.

---


<!-- Sent from Reviewable.io -->

2022-03-30 07:48 UTC, pwmarcz reviewed
I am not surprised that VTune doesn't work with the current version of the perf traces, what I'm saying is it could be made to work. 

If the feature is not broken in VTune, it opens *actual* traces recorded by perf, so it's a matter of comparing these two formats and finding out what needs to be added.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478#-:-MzOl1LMC9pdBIPdrmmW:b-7iq2cg)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-03-30 13:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKm-RV6W8Xx54L1aU4:-MzPw-X15BYQ6LrOrI34:b-uewz1z) (no related file):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Because they aren't the hotspots.
</blockquote></details>

Not even 0.1% of execution time spent in LibOS? That doesn't sound plausible.
Have you actually verified that you are able to see anything from LibOS or the app when it has symbols?

---


<!-- Sent from Reviewable.io -->

2022-03-31 14:36 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 0 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKm-RV6W8Xx54L1aU4:-MzVOJW95WbMJfzzw09F:b-mr4akr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not even 0.1% of execution time spent in LibOS? That doesn't sound plausible.
Have you actually verified that you are able to see anything from LibOS or the app when it has symbols?
</blockquote></details>

I think I am missing something.  I guess mostly will need to add  explicit mapping for the individual binaries inside the enclave. Just the start/end address of the enclave doesn't seem to automatically map it. I will check.

---


<!-- Sent from Reviewable.io -->

2022-04-11 11:35 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 3 of 10 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKm-RV6W8Xx54L1aU4:-N-NOYoJ4Yx__XuXEC-O:bf66zc7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Michal is right, you don't add in-enclave binaries during runtime. The only in-enclave binary you add (explicitly) is the Linux-SGX PAL binary.

See my comments.
</blockquote></details>

This is fixed now. Reporting all the binaries to VTune.

---
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoP6v_DGpNANkQVtNl:-N-NOqWM2Z00rjSlDcrx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_enclave.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see why you need an `#include` since you already define the required function explictly. I would say just remove this code snippet, and add the required stuff into the below code snippets (see my other comments).

The `g_enable_vtune_profiling` variable can be moved out of the `VTUNE_SGX_PROFILING` macro, because who cares (it will always be false if there is no macro defined, but this is no problem).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoPLNn8JMuB1rH48lZ:-N-NOsF5CLudLEFkK02_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_enclave.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I propose to remove the top code snippet and just declare the needed function here:

```
#ifdef VTUNE_SGX_PROFILING
        if (g_enable_vtune_profiling) {
            extern void __itt_fini_ittlib(void);
            __itt_fini_ittlib();
        }
#endif
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 81 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoP_A9EJV5ZAeAZ-1K:-N-NOu-w7CrgJo2rC3oH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_enclave.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I propose to remove the top code snippet and just declare the needed function here:

```
#ifdef VTUNE_SGX_PROFILING
        if (g_enable_vtune_profiling) {
            extern void __itt_fini_ittlib(void);
            __itt_fini_ittlib();
        }
#endif
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoQ80U4mdosYLOSNyQ:-N-NOuia6b_o6mqf0oFB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_main.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need these three includes, just remove them.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoQ5m6CKEz9C04fZTD:-N-NOvJaAEOLYMkHgM6F:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_main.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're not using this function at all.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 563 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoQEd96xEr_5kTshte:-N-NOwVCBKYzOg6UL2S0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_main.c#L563)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of `#include ...` where this function is declared, you could just do `extern int __itt_module_load(...)`, similar to what you did with `__itt_fini_ittlib`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 563 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoQjI38YJxVeceZ3Ho:-N-NOyI50H7lLpW87IAd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_main.c#L563)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is actually the most important line in this PR. You're adding the Linux-SGX PAL binary to the list of "known binaries to track" by VTune.

This is why in your screenshot, we only see the Linux-SGX PAL binary's symbols, and not the symbols of other binaries -- the LibOS binary (`libsysdb.so`) and the application binary (e.g., `helloworld`). You should also add those binary's symbols to VTune's list of "known binaries to track".

We have special functions where you should add this: https://github.com/gramineproject/gramine/blob/af52e46a49994655ca6933dadd1b1d185738859c/Pal/src/host/Linux-SGX/sgx_profile.c#L301

And actually, you won't then need this code snippet because our already-existing `perf` integration calls this function on the PAL binary.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1031 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoQWECErIkLoYxf0dC:-N-NP-9-979j0eQDd9gE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_main.c#L1031)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would you need to collect VTune perf samples if Gramine failed? I think you can revert this change.

Note that `ecall_enclave_start()` above returns only when something went wrong, i.e., Gramine failed.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 34 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoPpqb4efJ90yVJqsJ:-N-NP0TL0QR837FIWXzo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_exception.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 157 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoPtpE4jN7H9MZvC-l:-N-NP1pT30e-GqhBN9Em:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_exception.c#L157)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would you need to collect VTune perf samples if Gramine failed? I think you can revert this change.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 263 at r1](https://reviewable.io/reviews/gramineproject/gramine/478#-MzoPypg-vlU3zLZ6Ljy:-N-NP2nh9y37_dJL12Qt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39463c706a8504bd06105a270430abe4fe7f8b5/Pal/src/host/Linux-SGX/sgx_exception.c#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would you need to collect VTune perf samples if Gramine failed? I think you can revert this change.
 [...]

2022-04-11 11:36 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 3 of 10 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-MzKlWY14RoIKNSp9a97:-N-NPCZn7R3InIImrJlr:bb77ufg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would be actually happy to see integration with VTune. It's not bad to have two popular perf tools. Moreover, VTune is very much SGX aware, so may be more robust than our custom `perf` integration.
</blockquote></details>

Yes.

---


<!-- Sent from Reviewable.io -->

2022-04-12 11:43 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @svenkata9)

___
*[meson.build, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SZHOr7UdUC0t25CtR:-N-SZHOr7UdUC0t25CtS:bn5safn) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L33)):*
> ```Meson
> direct = get_option('direct') == 'enabled'
> sgx = get_option('sgx') == 'enabled'
> vtune_sgx_profiling = get_option('vtune_sgx_profiling') == 'enabled'
> ```

Please rename to simply `vtune`. The options for Meson build should be short and easy to remember. And `vtune` has an obvious meaning, so doesn't need additional words.
___
*[meson.build, line 155 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SZcvX1sRn_KzLF5zZ:-N-SZcvX1sRn_KzLF5z_:buq50ey) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L155)):*
> ```Meson
> 
>   if vtune_sgx_profiling
>     add_project_arguments('-DVTUNE_SGX_PROFILING', language: 'c')
> ```

I suggest to rename the macro to `DSGX_VTUNE_PROFILE`.
___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-S_0kLC6VM5Sg5KB5H:bk7j0vn) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
> ```Meson
>   if vtune_sgx_profiling
>     add_project_arguments('-DVTUNE_SGX_PROFILING', language: 'c')
>     vtune_sdk_default_path = '/opt/intel/oneapi/vtune/2022.1.0/sdk'
> ```

Please remove this helper variable and just use this path directly below.
___
*[meson_options.txt, line 38 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_CNr1bN7xV9wzSQj:-N-S_CNr1bN7xV9wzSQk:bctk0kj) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson_options.txt#L38)):*
> ```Meson
> 
> option('vtune_sgx_profiling', type: 'combo', choices: ['disabled', 'enabled'],
>     description: 'Enable profiling with vtune for gramine-sgx (aka Linux-SGX)')
> ```

`...VTune for Gramine with SGX`
___
*[meson_options.txt, line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_Rkd9PC-4A3kQ92U:-N-S_Rkd9PC-4A3kQ92V:b-jejk62) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson_options.txt#L40)):*
> ```Meson
>     description: 'Enable profiling with vtune for gramine-sgx (aka Linux-SGX)')
> option('vtune_sdk_path', type: 'string',
>     description: 'Path to the VTune SDK installation path')
> ```

Please remove last `path` word, now you have a duplication
___
*[Documentation/manifest-syntax.rst, line 852 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SV51s8ctr510apz6h:-N-SV51s8ctr510apz6i:b-6cvxfs) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L852)):*
> ```reStructuredText
>    all samples are taken.
> 
> SGX profiling with Intel(R) VTune(TM) Profiler
> ```

Btw, do we need to call it like this in our documentation? Can we skip all these copyright symbols and just write `Intel VTune Profiler`? Looks ugly.
___
*[Documentation/manifest-syntax.rst, line 857 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SX-Rn2dF15J1mKuwp:-N-SX-Rn2dF15J1mKuwq:b-kp489f) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L857)):*
> ```reStructuredText
> ::
> 
>     sgx.vtune_profiling = [true|false]
> ```

For consistency, can we rename it to `sgx.vtune_profile`?
___
*[Documentation/manifest-syntax.rst, line 862 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SX43H3pTIabhJvJe7:-N-SX43H3pTIabhJvJe8:b-v36pva) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L862)):*
> ```reStructuredText
> This syntax specifies whether to enable SGX profiling with Intel(R) VTune(TM)
> Profiler. Gramine must be compiled with ``DEBUG=1`` or ``DEBUGOPT=1`` for this
> option to work (the latter is advised).
> ```

How does this manifest option work with `sgx.profile.*` options? Are they completely independent? Or some `sgx.profile.*` options should be specified in order for `sgx.vtune_profiling` to work? Or maybe `sgx.vtune_profiling` and `sgx.profile.*` are contradicting, and only one of them can be specified?

Please add some explanation on this.
___
*[Documentation/devel/performance.rst, line 580 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SXfbn3VMwQs3B80Hf:-N-SXfbn3VMwQs3B80Hg:b-kqxq4n) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L580)):*
> ```reStructuredText
> 
> #. Compile Gramine with
>    ``-Dvtune_sgx_profiling=enabled -Dvtune_sdk_path=<VTune SDK install path>``.
> ```

I'd prefer `Dvtune_sgx_profile` (for uniformity with other namings)
___
*[Documentation/devel/performance.rst, line 582 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SVTO6Dw55EKKsNyD0:-N-SVTO6Dw55EKKsNyD1:b-5hqvus) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L582)):*
> ```reStructuredText
>    ``-Dvtune_sgx_profiling=enabled -Dvtune_sdk_path=<VTune SDK install path>``.
> 
>    If ``vtune_sdk_path`` is not provided, Gramine will take the default VTune
> ```

`will take` -> `will use`
___
*[Documentation/devel/performance.rst, line 587 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SXltbC0_NCi92N0IX:-N-SXltbC0_NCi92N0IY:b5ola9i) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L587)):*
> ```reStructuredText
> #. Add ``sgx.vtune_profiling = true`` to the manifest.
> 
> #. Run your application under vtune.
> ```

`vtune` -> `VTune`
___
*[Documentation/devel/performance.rst, line 595 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SVZPc9bm6ejU08SHT:-N-SVZPc9bm6ejU08SHU:b-f7842f) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L595)):*
> ```reStructuredText
> #. To view the report, run
>    ``vtune -report hotspots -r <vtune data collection output directory>`` or use
>    Intel(R) VTune(TM) Profiler GUI application
> ```

Please add a dot at the end.
___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYhXN2PALszE-yj-E:-N-SYhXO0cpmLsiDoRod:btl57rw) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L7)):*
> ```Meson
> )
> 
> vtune_inc = ['']
> ```

I think it should be just an empty list (not a list with one empty string):
```
vtune_inc = []
```
___
*[Pal/src/host/Linux-SGX/meson.build, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYvyO08RBJFLQ5ERT:-N-SYvyO08RBJFLQ5ERU:b-vhceuk) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L14)):*
> ```Meson
>     vtune_sdk_include_dir = vtune_sdk_path + '/include'
>     vtune_sdk_ittnotify_include_dir = vtune_sdk_path + '/src/ittnotify'
>     vtune_ittnotify_lib = 'ittnotify'
> ```

Can you embed these 4 helper variables directly into the below statements? I don't see a need for these variables.
___
*[P [...]

2022-04-12 12:30 UTC, pwmarcz reviewed
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @svenkata9)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N-ShZBj4JZ3V8z1Yefe:b-bnecf2) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
> ```C
> #ifdef VTUNE_SGX_PROFILING
>             if (g_enable_vtune_profiling)
>                 __itt_module_load((void*)addr + mapstart, (void*) addr + mapend - 1, path);
> ```

These addresses do not specify the whole binary, only the executable segment, and the information about file offset is lost. Does this actually work? Intel's documentation calls these parameters "start and end addresses for the module", which I don't understand.


<!-- Sent from Reviewable.io -->

2022-04-12 13:36 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/meson.build, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SxUxH7OmqGjRJqJhL:-N-SxUxH7OmqGjRJqJhM:b-bybawd) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L10)):*
> ```Meson
> vtune_ldflags = []
> 
> if vtune_sgx_profiling
> ```

all those should be joined with `/` or `join_path()`, not `+`
___
*[Pal/src/host/Linux-SGX/meson.build, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYW3aDq3nEVHnG08K:-N-SxcJ13DQ9tjOkwqyr:bt54sxf) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not combine this into the previous line:
```
vtune_ldflags = ['-L' + vtune_sdk_lib_dir, '-l' + vtune_ittnotify_lib, '-ldl']
```
</blockquote></details>

Because those should really be `dependency()` or at least `cc.find_library()` and passed via `link_with: `, not `link_args:`.

https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library

Also, this dependency management should be together with all other libraries in toplevel `meson.build`.


<!-- Sent from Reviewable.io -->

2022-04-12 13:58 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N-T2hSi0EU3g9lPCQY9:b2byca3) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

These addresses do not specify the whole binary, only the executable segment, and the information about file offset is lost. Does this actually work? Intel's documentation calls these parameters "start and end addresses for the module", which I don't understand.
</blockquote></details>

This works well from what I have seen. The VTune profiler GUI is able to map the data to the exact point in the code. For example, this one for _real_memset
![image.png](https://files.reviewableusercontent.io/images/reviewable/29835993/YiXorRL-wTDH30z9Ma6lVFzr/image.png)


<!-- Sent from Reviewable.io -->

2022-04-13 09:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N-XI9477I7d2WJ66QI-:bix4l9v) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
OK. Thanks for checking that!

>What do you mean by this exactly?

I mean that we notify VTune that, say, "a memory range from 0x11000 to 0x11fff belongs to `glibc.so`", but not _where_ in the `glibc.so` file is that range. But apparently VTune is able to figure that out.


<!-- Sent from Reviewable.io -->

2022-04-13 11:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N-X_IRn1Ud5kqobC1i7:budjno0) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. Thanks for checking that!

>What do you mean by this exactly?

I mean that we notify VTune that, say, "a memory range from 0x11000 to 0x11fff belongs to `glibc.so`", but not _where_ in the `glibc.so` file is that range. But apparently VTune is able to figure that out.
</blockquote></details>

Yes, apparently VTune figures it out automatically. Maybe VTune assumes only one executable segment in the ELF file (can there be more actually, according to the ELF standard?), and just assumes that the memory range maps to this executable segment (so VTune knows the offset inside `glibc.so` that corresponds to this memory range).


<!-- Sent from Reviewable.io -->

2022-04-13 11:38 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 2 of 10 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson.build, line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SZHOr7UdUC0t25CtR:-N-WoyjDBCTl7WQC1PsG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename to simply `vtune`. The options for Meson build should be short and easy to remember. And `vtune` has an obvious meaning, so doesn't need additional words.
</blockquote></details>

Done.
___
*[meson.build, line 155 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SZcvX1sRn_KzLF5zZ:-N-Wp-Hf60jPP6248rNC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to rename the macro to `DSGX_VTUNE_PROFILE`.
</blockquote></details>

Done.
___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-Waeoi5ciXRP3iLZxP:bchkv8l) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The default should be in `meson_options.txt`. We do this default paths dance for sgx driver, because there are three drivers and each has it's own default. Here it's not needed, you have only one default.
</blockquote></details>

I have removed the variable, and directly used the path.

@woju BTW, the SGX driver related paths are not in meson_options.txt, but they are in ``meson.build``, in case you want to move them ``meson_options.txt``
___
*[meson_options.txt, line 38 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_CNr1bN7xV9wzSQj:-N-Wp_bSEAmv2yVIvNGu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson_options.txt#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...VTune for Gramine with SGX`
</blockquote></details>

Done.
___
*[meson_options.txt, line 40 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_Rkd9PC-4A3kQ92U:-N-WpaiY9TQuctw4D7wr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson_options.txt#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove last `path` word, now you have a duplication
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 857 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SX-Rn2dF15J1mKuwp:-N-WprGGDHW_DH-_SYc4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L857)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For consistency, can we rename it to `sgx.vtune_profile`?
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 862 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SX43H3pTIabhJvJe7:-N-WdHdj9wZqHY-0tuSa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L862)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does this manifest option work with `sgx.profile.*` options? Are they completely independent? Or some `sgx.profile.*` options should be specified in order for `sgx.vtune_profiling` to work? Or maybe `sgx.vtune_profiling` and `sgx.profile.*` are contradicting, and only one of them can be specified?

Please add some explanation on this.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 580 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SXfbn3VMwQs3B80Hf:-N-WptGO5VbwqTD8ZKSN:bpf94t0) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L580)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer `Dvtune_sgx_profile` (for uniformity with other namings)
</blockquote></details>

Ignoring this comment, and taking the previous one and using -Dvtune
___
*[Documentation/devel/performance.rst, line 582 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SVTO6Dw55EKKsNyD0:-N-WpxC06wwtDqFmxDmq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L582)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`will take` -> `will use`
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 587 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SXltbC0_NCi92N0IX:-N-XhqlGEOEvoWX2zqP0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L587)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`vtune` -> `VTune`
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 595 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SVZPc9bm6ejU08SHT:-N-XhqNt2RdqpnhFlg6q:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/devel/performance.rst#L595)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/meson.build, line 7 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYhXN2PALszE-yj-E:-N-XhtbjArH16d4fAV5c:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it should be just an empty list (not a list with one empty string):
```
vtune_inc = []
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/meson.build, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SxUxH7OmqGjRJqJhL:-N-Xhs5o8cJ0j90DwPVb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

all those should be joined with `/` or `join_path()`, not `+`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/meson.build, line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYvyO08RBJFLQ5ERT:-N-XfWqJ-pwXS3Ie9UU1:ba455hu) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you embed these 4 helper variables directly into the below statements? I don't see a need for these variables.
</blockquote></details>

It includes merging/joining on the base SDK path with the corresponding subdirectories. It would look uglier if is is used directly. However, I [...]

2022-04-13 23:33 UTC, woju requested changes
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 3 of 10 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-_DpTR3GWxuZwswqMq:b-oj3z1t) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I have removed the variable, and directly used the path.

@woju BTW, the SGX driver related paths are not in meson_options.txt, but they are in ``meson.build``, in case you want to move them ``meson_options.txt``
</blockquote></details>

No, I just explained why defaults for SGX driver paths need to be in `meson.build`. But `vtune_sdk_path` don't need to have this default here, you can remove `if vtune_sdk_path == ''` below and move default value to `meson_options.txt`.
___
*[Documentation/manifest-syntax.rst, line 852 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SV51s8ctr510apz6h:-N-_FNVz7H-sHJqBPapb:b-wkvube) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L852)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, do we need to call it like this in our documentation? Can we skip all these copyright symbols and just write `Intel VTune Profiler`? Looks ugly.
</blockquote></details>

Yes, we should skip them. AFAIK we don't do that elsewhere.
___
*[Pal/src/host/Linux-SGX/meson.build, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYW3aDq3nEVHnG08K:-N-_BVNf-70Mfkbo8Go-:byyt165) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L22)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I didn't get this, and would need your help if there is a better way to do it.
</blockquote></details>

Please look in toplevel `meson.build` how the external libraries are discovered. TL;DR first you need to locate the library using `cc.find_library()` and then the resulting object needs to be passed in `dependencies:` argument to `library()` or `executable()` (I erroneously wrote `link_with:` previously, that was a mistake).

Alternatively, if the library supplies pkg-config file or cmake equivalent, you can use `dependency()`.

For example, please see what happens with `libcurl_dep`:
https://github.com/gramineproject/gramine/blob/c14dce0dffc9db090e1d8316f729007207ab9b54/meson.build#L223-L260
https://github.com/gramineproject/gramine/blob/c14dce0dffc9db090e1d8316f729007207ab9b54/Pal/src/host/Linux-SGX/tools/common/meson.build#L19-L24

Now because your library is in non-standard directory, you might need to pass some additional arguments to `find_library`. (See the documentation linked in the last comment).


<!-- Sent from Reviewable.io -->

2022-04-14 01:53 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 3 of 10 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-_lONzEI1MusnMmSso:b-su0l0z) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, I just explained why defaults for SGX driver paths need to be in `meson.build`. But `vtune_sdk_path` don't need to have this default here, you can remove `if vtune_sdk_path == ''` below and move default value to `meson_options.txt`.
</blockquote></details>

I see. I have now directly assigning based on the other comment.
___
*[Documentation/manifest-syntax.rst, line 852 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SV51s8ctr510apz6h:-N-_lYxS-6MuAJWD-5VI:b-qjtx3f) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Documentation/manifest-syntax.rst#L852)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, we should skip them. AFAIK we don't do that elsewhere.
</blockquote></details>

I've removed it.
___
*[Pal/src/host/Linux-SGX/meson.build, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYW3aDq3nEVHnG08K:-N-_kxUNEcxOwDpYIWlx:b-f4o4ex) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L22)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please look in toplevel `meson.build` how the external libraries are discovered. TL;DR first you need to locate the library using `cc.find_library()` and then the resulting object needs to be passed in `dependencies:` argument to `library()` or `executable()` (I erroneously wrote `link_with:` previously, that was a mistake).

Alternatively, if the library supplies pkg-config file or cmake equivalent, you can use `dependency()`.

For example, please see what happens with `libcurl_dep`:
https://github.com/gramineproject/gramine/blob/c14dce0dffc9db090e1d8316f729007207ab9b54/meson.build#L223-L260
https://github.com/gramineproject/gramine/blob/c14dce0dffc9db090e1d8316f729007207ab9b54/Pal/src/host/Linux-SGX/tools/common/meson.build#L19-L24

Now because your library is in non-standard directory, you might need to pass some additional arguments to `find_library`. (See the documentation linked in the last comment).
</blockquote></details>

I tried to do this when I started this effort. But, I couldn't figure out how to make the dependencies apply only when -Dvtune is passed during the build? So, I settled with the current one.


<!-- Sent from Reviewable.io -->

2022-04-14 07:04 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @svenkata9, and @woju)

___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-asAv9DbO7H-svFztD:b-2co8p) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I see. I have now directly assigning based on the other comment.
</blockquote></details>

@svenkata9 Which other comment do you mean? Woju suggests to add something like this in `meson_options.txt`:
```
option('vtune_sdk_path', type: 'string',
    value: '/opt/intel/oneapi/vtune/2022.1.0/sdk',
    description: 'Path to the VTune SDK installation')
```

Note the added `value` field -- now Meson will use this value as the default. And in this code (`meson.build`), you simply do:
```
  if vtune
    add_project_arguments('-DSGX_VTUNE_PROFILE', language: 'c')
    vtune_sdk_path = get_option('vtune_sdk_path')
  endif
```

This should work.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r3](https://reviewable.io/reviews/gramineproject/gramine/478#-N-aqxuk3CiZboCyiide:-N-aqxul4_E-wfK8oXJX:bkq9v0l) ([raw file](https://github.com/gramineproject/gramine/blob/911f504387fd8324ca9469590154faece337a732/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
> ```C
> #ifndef SGX_VTUNE_PROFILE
>     if (g_vtune_profile_enabled) {
>         log_always("Gramine is not built with VTune support. sgx.vtune_profiling setting in manifest will have no impact.");
> ```

A better wording:
```
Gramine was not built with VTune support, 'sgx.vtune_profile'  manifest option has no impact.
```
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SWSfh6MCULFyeOZ2z:-N-as1PLD8l9gWiyEpAX:b-4bxgf) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L31)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I get a linker error.
</blockquote></details>

Which one exactly? I don't see why my approach wouldn't work in this file... It worked in all other files.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N-arT895bCTxgyP5PfD:be7p1xz) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

We do like this in the code where we loop through the entries in the ph and register every mapstart and mapend with VTune. So, in case there is more than one, we will invoke itt_module_load to add/register multiple entries and their corresponding range with vtune automatically, right?

https://github.com/gramineproject/gramine/blob/af52e46a49994655ca6933dadd1b1d185738859c/Pal/src/host/Linux-SGX/sgx_profile.c#L359
</blockquote></details>

Yes, sure, we have a loop here that iterates through all executable segments (code segments). But then we have Pawel's question: how can VTune distinguish which of the several executable segments belongs to which "part' of the code? As Pawel noticed, VTune's `__itt_module_load()` doesn't ask for an offset in the `path` file, so VTune gets no hint as to which of the several parts of the code this particular mapped region belongs to. So I made an assumption that VTune only considers the first executable segment, and ignores the rest (if any, which is atypical for ELF applications).


<!-- Sent from Reviewable.io -->

2022-04-14 07:30 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @svenkata9)

___
*[Pal/src/host/Linux-SGX/meson.build, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYW3aDq3nEVHnG08K:-N-axXar-1REGqwIhygU:b-7653ux) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L22)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I tried to do this when I started this effort. But, I couldn't figure out how to make the dependencies apply only when -Dvtune is passed during the build? So, I settled with the current one.
</blockquote></details>

Why can't you put those under `if vtune`? Cf. SGX-only dependencies are under `if sgx`.


<!-- Sent from Reviewable.io -->

2022-04-19 05:38 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 6 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[meson.build, line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-S_0kLC6VM5Sg5KB5G:-N-vMLjk1xqgAMXGMrbN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/meson.build#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@svenkata9 Which other comment do you mean? Woju suggests to add something like this in `meson_options.txt`:
```
option('vtune_sdk_path', type: 'string',
    value: '/opt/intel/oneapi/vtune/2022.1.0/sdk',
    description: 'Path to the VTune SDK installation')
```

Note the added `value` field -- now Meson will use this value as the default. And in this code (`meson.build`), you simply do:
```
  if vtune
    add_project_arguments('-DSGX_VTUNE_PROFILE', language: 'c')
    vtune_sdk_path = get_option('vtune_sdk_path')
  endif
```

This should work.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/meson.build, line 22 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SYW3aDq3nEVHnG08K:-N0-JnT388z6JF0XqXoW:bq13wow) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/meson.build#L22)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why can't you put those under `if vtune`? Cf. SGX-only dependencies are under `if sgx`.
</blockquote></details>

Please check it. I think I have addressed this according to the expectations.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r3](https://reviewable.io/reviews/gramineproject/gramine/478#-N-aqxuk3CiZboCyiide:-N-vJoaO3pHOMMketxZo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/911f504387fd8324ca9469590154faece337a732/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A better wording:
```
Gramine was not built with VTune support, 'sgx.vtune_profile'  manifest option has no impact.
```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SWSfh6MCULFyeOZ2z:-N-vJpKyEKxRawAOmwve:b6rwv3l) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Which one exactly? I don't see why my approach wouldn't work in this file... It worked in all other files.
</blockquote></details>

```gramine1/build/../Pal/src/host/Linux-SGX/sgx_profile.c:380: undefined reference to `__itt_module_load'.```

This function has been defined as void ITTAPI __itt_module_load in ittnotify.h. ITTAPI is defined as __cdecl or __attribute__ ((cdecl)). I tried even providing it explicitly. It didn't work. Just including #include "ittnotify.h" makes it work. I tried the loadA version which is what it gets expanded too as well.

The other one is __fini_itt is not defined anywhere, so perhaps it just matches whatever is in the libittnotify.a That's my best guess.


<!-- Sent from Reviewable.io -->

2022-04-19 05:39 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 6 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0-K9G_2ZGaumkeoDS-:b-v3ag4m) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
> ```Meson
>       vtune_dep = cc.find_library('ittnotify', dirs: join_paths(vtune_sdk_path, 'lib64'), required: true)
>       dl_dep = cc.find_library('dl', required: true)
>   endif
> ```

FYI, I have removed unnecessary variables and directly using join_paths. I guess it is fine.


<!-- Sent from Reviewable.io -->

2022-04-19 08:39 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @svenkata9, and @woju)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0-x8gg5W2orRxfIikn:b-r63jqj) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

FYI, I have removed unnecessary variables and directly using join_paths. I guess it is fine.
</blockquote></details>

This looks good to me. Let's wait for the expert's opinion. @woju ?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 721 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-xS2EEYbpjNT6NdTB:-N0-xS2EEYbpjNT6NdTC:b-zehvz4) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/Pal/src/host/Linux-SGX/sgx_main.c#L721)):*
> ```C
>             "Detected EPID remote attestation parameters 'ra_client_spid' and/or "
>             "'ra_client_linkable' in the manifest but no 'remote_attestation' parameter. "
>             "Please add 'sgx.remote_attestation = true' to the manifest.");
> ```

FYI: Here's an example on how to split the message into several 100-char-max lines.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-xMGHDnsYwbaukfXv:-N0-xMGHDnsYwbaukfXw:bl5mfo5) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
> ```C
> #ifndef SGX_VTUNE_PROFILE
>     if (g_vtune_profile_enabled)
>         log_always("Gramine was not built with VTune profiling support, 'sgx.vtune_profile' manifest option has no impact.");
> ```

Could you split into two lines, because we have a 100 characters-per-line limit?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SWSfh6MCULFyeOZ2z:-N0-xzDYBDsOeOJYZniA:b-t7iyif) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L31)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

```gramine1/build/../Pal/src/host/Linux-SGX/sgx_profile.c:380: undefined reference to `__itt_module_load'.```

This function has been defined as void ITTAPI __itt_module_load in ittnotify.h. ITTAPI is defined as __cdecl or __attribute__ ((cdecl)). I tried even providing it explicitly. It didn't work. Just including #include "ittnotify.h" makes it work. I tried the loadA version which is what it gets expanded too as well.

The other one is __fini_itt is not defined anywhere, so perhaps it just matches whatever is in the libittnotify.a That's my best guess.
</blockquote></details>

I think this should work:
```
__attribute__((__cdecl__)) void __itt_module_load(void* start, void* end, char* path);
```

Could you try it, instead of this `#include`? I still don't get what the exact problem is. If it doesn't work, can you copy-paste the error message from GCC/ninja?


<!-- Sent from Reviewable.io -->

2022-04-19 14:59 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 8 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-xMGHDnsYwbaukfXv:-N01K8PFCqBEhZURQoBQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you split into two lines, because we have a 100 characters-per-line limit?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SWSfh6MCULFyeOZ2z:-N01K9in6X84cAIgJllp:bof8ktc) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this should work:
```
__attribute__((__cdecl__)) void __itt_module_load(void* start, void* end, char* path);
```

Could you try it, instead of this `#include`? I still don't get what the exact problem is. If it doesn't work, can you copy-paste the error message from GCC/ninja?
</blockquote></details>

As discussed and as we found, this requirement to include ittnotify.h comes because itt_module_load is a macro that is expanded in this header.


<!-- Sent from Reviewable.io -->

2022-04-19 14:59 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 8 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N01KUow7ZJiUxC_0IYY:b-1zsy98) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks good to me. Let's wait for the expert's opinion. @woju ?
</blockquote></details>

@woju Please let me know.


<!-- Sent from Reviewable.io -->

2022-04-20 05:59 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @svenkata9, and @woju)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-xMGHDnsYwbaukfXv:-N04YH4J5ioN52Wz1MKe:bb9g1gh) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please add a space after `,` (otherwise the message will be printed ugly: `...support,'sgx.vtune_profile' ...`)
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-SWSfh6MCULFyeOZ2z:-N04YSmSD8jSjkhMU07j:bu89416) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L31)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

As discussed and as we found, this requirement to include ittnotify.h comes because itt_module_load is a macro that is expanded in this header.
</blockquote></details>

Yes, there is a whole chain of macros which we decided not to decipher and not to touch.


<!-- Sent from Reviewable.io -->

2022-04-20 06:11 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 9 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 746 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-xMGHDnsYwbaukfXv:-N04a6AuDtwca9QYfXYi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/Pal/src/host/Linux-SGX/sgx_main.c#L746)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space after `,` (otherwise the message will be printed ugly: `...support,'sgx.vtune_profile' ...`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-20 06:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-N04l7j8667jzz-xdg5j:-N04l7j8667jzz-xdg5k:b5p9r5z) (no related file):*
The PR looks good to me. I'll wait for other reviewers, and then I'd like to test the final version myself.

---


<!-- Sent from Reviewable.io -->

2022-04-22 13:57 UTC, woju reviewed
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0GWgPy9NyTU1NyTZjH:br1xr9e) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

@woju Please let me know.
</blockquote></details>

Not blocking, but if `ittnotify` always goes together with those include directories, you can do this:

```meson
dl_dep = cc.find_library(...)
vtune_dep = declare_dependency(
    dependencies: [
        cc.find_library(...),
        dl_dep,
    ],
    include_directories: include_directories(...),
)
```

If you do this, you don't need to separately add `vtune_inc` everywhere.

Docs: https://mesonbuild.com/Reference-manual_functions.html#declare_dependency


<!-- Sent from Reviewable.io -->

2022-04-22 14:27 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0GeSraAQ_GOUjY7VuN:bxcojn4) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not blocking, but if `ittnotify` always goes together with those include directories, you can do this:

```meson
dl_dep = cc.find_library(...)
vtune_dep = declare_dependency(
    dependencies: [
        cc.find_library(...),
        dl_dep,
    ],
    include_directories: include_directories(...),
)
```

If you do this, you don't need to separately add `vtune_inc` everywhere.

Docs: https://mesonbuild.com/Reference-manual_functions.html#declare_dependency
</blockquote></details>

(since you think it is not blocking), Coud you approve for proceeding with the current way (it still is within if vtune), and update later (if at all it is required)? 


<!-- Sent from Reviewable.io -->

2022-04-22 14:39 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0GhAEA1EtkhCLy3gRH:b2vt3t2) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

(since you think it is not blocking), Coud you approve for proceeding with the current way (it still is within if vtune), and update later (if at all it is required)? 
</blockquote></details>

Do you have any good reason to go with the current approach of separate `vtune_inc`? For example, will it be necessary to use one without another? If not, I'd suggest fixing it now and not leaving it to "update later".


<!-- Sent from Reviewable.io -->

2022-04-22 15:18 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 8 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[meson.build, line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/478#-N0-K9G_2ZGaumkeoDRz:-N0GqQIdAepnlftd1TbG:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/d39d13be4aa92fd2d5f7dff9ca3967bebfb1abcb/meson.build#L275)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do you have any good reason to go with the current approach of separate `vtune_inc`? For example, will it be necessary to use one without another? If not, I'd suggest fixing it now and not leaving it to "update later".
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-22 16:55 UTC, woju reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 9 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-N04l7j8667jzz-xdg5j:-N0GYmBVE4SZ_cd7_PAE:b-w1zct4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me. I'll wait for other reviewers, and then I'd like to test the final version myself.
</blockquote></details>

For meson, LGTM.

---


<!-- Sent from Reviewable.io -->

2022-04-25 07:40 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-11 14:30 UTC, svenkata9 commented
@mkow Could you review this?

2022-05-12 23:21 UTC, mkow requested changes
> Reviewed 3 of 8 files at r3, 1 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @svenkata9)

___
*[`Documentation/devel/performance.rst` line 563 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUxan9aUDYDst6MVl:-N1uUxan9aUDYDst6MVm:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L563)):*
> ```reStructuredText
> .. _vtune-sgx-profiling:
> 
> Profiling SGX hotspots with ``Intel VTune Profiler``
> ```





_Suggestion:_
```reStructuredText
Intel VTune Profiler
```
___
*[`Documentation/devel/performance.rst` line 566 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUozM0nlw05cZQ02l:-N1uUozN-CL11JL21UTd:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L566)):*
> ```reStructuredText
> ----------------------------------------------------
> 
> This section describes how to use `vtune
> ```





_Suggestion:_
```reStructuredText
VTune
```
___
*[`Documentation/devel/performance.rst` line 570 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUsKm0vtxAkYfQMoS:-N1uUsKn6Y91J7Nnct6D:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L570)):*
> ```reStructuredText
> profiler to find SGX hotspots.
> 
> Installing ``vtune``
> ```





_Suggestion:_
```reStructuredText
VTune
```
___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N1uVJfV0sQ9Blq8PR6F:b-8c0y68) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
> ```reStructuredText
>    ``vtune -collect sgx-hotspots -- gramine-sgx <workload>``
> 
>    It will output the data collected to a directory of the format ``r000sgxhs``.
> ```

I don't understand this. Which part of ``r000sgxhs`` is the constant part and which is the changing? (I assume some is changing, because you called it "format").



_Code quote:_
```reStructuredText
of the format ``r000sgxhs``
```
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N1uZMuVCSbdglevFlxo:b-90q3h1) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, sure, we have a loop here that iterates through all executable segments (code segments). But then we have Pawel's question: how can VTune distinguish which of the several executable segments belongs to which "part' of the code? As Pawel noticed, VTune's `__itt_module_load()` doesn't ask for an offset in the `path` file, so VTune gets no hint as to which of the several parts of the code this particular mapped region belongs to. So I made an assumption that VTune only considers the first executable segment, and ignores the rest (if any, which is atypical for ELF applications).
</blockquote></details>

That would mean that it can't resolve data symbols?
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 379 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uYnvxBstDHKKTu52Z:-N1uYnvxBstDHKKTu52_:b-tcvhxr) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Pal/src/host/Linux-SGX/sgx_profile.c#L379)):*
> ```C
> #ifdef SGX_VTUNE_PROFILE
>             if (g_vtune_profile_enabled)
>                 __itt_module_load((void*)addr + mapstart, (void*) addr + mapend - 1, path);
> ```

misleading formatting



_Suggestion:_
```C
(void*)addr
```


<!-- Sent from Reviewable.io -->

2022-05-13 03:30 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 8 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/performance.rst` line 563 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUxan9aUDYDst6MVl:-N1vSazPD6UL5IMdbXPw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L563)):*
> ```reStructuredText
> .. _vtune-sgx-profiling:
> 
> Profiling SGX hotspots with ``Intel VTune Profiler``
> ```

Done.
___
*[`Documentation/devel/performance.rst` line 566 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUozM0nlw05cZQ02l:-N1vSbXc6X8lLKCE_o5b:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L566)):*
> ```reStructuredText
> ----------------------------------------------------
> 
> This section describes how to use `vtune
> ```

Done.
___
*[`Documentation/devel/performance.rst` line 570 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uUsKm0vtxAkYfQMoS:-N1vScV84290jLayFW6x:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L570)):*
> ```reStructuredText
> profiler to find SGX hotspots.
> 
> Installing ``vtune``
> ```

Done.
___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N1vSdLW-XW7ruaW1piI:b-gy8v2v) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this. Which part of ``r000sgxhs`` is the constant part and which is the changing? (I assume some is changing, because you called it "format").
</blockquote></details>

I thought it is obvious, but since you are asking the 000 part is variable because when you run a fresh collection with vtune, this number gets incremented.
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N1vSvHb1pSkvl7hulBC:b-nne7nt) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That would mean that it can't resolve data symbols?
</blockquote></details>

I don't know what you mean. So far it is able to resolve all the symbols.
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 379 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uYnvxBstDHKKTu52Z:-N1vSqD0064RZhNArJbW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Pal/src/host/Linux-SGX/sgx_profile.c#L379)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

misleading formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 07:57 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N1wO_m958hSs3gNBZ0k:b9330m6) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I thought it is obvious, but since you are asking the 000 part is variable because when you run a fresh collection with vtune, this number gets incremented.
</blockquote></details>

Yeah, I think it's pretty obvious that `000` is changing. The rest stands for `Report 000 SGX HotSpots`.
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N1wP-T86l_KNkQn_7ta:bjmospw) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
> That would mean that it can't resolve data symbols?

From what I remember about those VTune runs (it was a month ago already), indeed the data symbols were there. I don't really know *how* it is done, but my theory is that VTune deduces all the information from these two inputs: the filename of the binary and the virtual address at which the code segment starts in program memory. Technically, it is then easy to calculate the base address where the binary is loaded in program memory, apply offsets and thus arrive to all data symbols' addresses.

I'll try to discuss this with VTune developers to learn more.


<!-- Sent from Reviewable.io -->

2022-05-13 11:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @svenkata9)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/478#-N04l7j8667jzz-xdg5j:-N1x6UOf57aVVi2zr-2M:b4tkfjo) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For meson, LGTM.
</blockquote></details>

I tested this PR myself, looks good. I left a couple final comments, based on my tests.

___
___
*[`meson_options.txt` line 40 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x08ruD-a31fRlXazl:-N1x08ruD-a31fRlXazm:b-s27dq1) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/meson_options.txt#L40)):*
> ```Meson
>     description: 'Enable profiling with VTune for Gramine with SGX')
> option('vtune_sdk_path', type: 'string',
>     value: '/opt/intel/oneapi/vtune/2022.1.0/sdk',
> ```

We should not hard-code this specific version. VTune has a user-friendly symlink to the specific version, so please use this one:
```
    value: '/opt/intel/oneapi/vtune/latest/sdk',
```
___
*[`Documentation/manifest-syntax.rst` line 862 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x5-6L4A44e8JzXTZA:-N1x5-6L4A44e8JzXTZB:b18dh5f) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/Documentation/manifest-syntax.rst#L862)):*
> ```reStructuredText
> This syntax specifies whether to enable SGX profiling with Intel VTune Profiler.
> Gramine must be compiled with ``DEBUG=1`` or ``DEBUGOPT=1`` for this option to
> work (the latter is advised).
> ```

Please also add this sentence:
```
The application manifest must contain ``sgx.debug = true``.
```
___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N1x3H_d9t3nadbevq1s:bx01bgc) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I think it's pretty obvious that `000` is changing. The rest stands for `Report 000 SGX HotSpots`.
</blockquote></details>

There is also a `-r <path>` option in VTune which allows to choose whatever file path name. Just for your information.
___
*[`Documentation/devel/performance.rst` line 585 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x0Mhq8Q5gH6oIv2em:-N1x0Mhr3_iWJw9AjFQ7:b-l81xaa) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/Documentation/devel/performance.rst#L585)):*
> ```reStructuredText
>    installation path.
> 
> #. Add ``sgx.vtune_profile = true`` to the manifest.
> ```

Please expand to
```
#. Add ``sgx.vtune_profile = true`` and ``sgx.debug = true`` to the manifest.
```

Without `sgx.debug`, I got an empty report, and Gramine complained like this:
```
error: Reading TCS.FLAGS.DBGOPTIN failed: -5
error: load_enclave() failed with error -5
```


<!-- Sent from Reviewable.io -->

2022-05-13 11:38 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 7 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`meson_options.txt` line 40 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x08ruD-a31fRlXazl:-N1xAYxe7pJ1pl6MoD6e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/meson_options.txt#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should not hard-code this specific version. VTune has a user-friendly symlink to the specific version, so please use this one:
```
    value: '/opt/intel/oneapi/vtune/latest/sdk',
```
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 862 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x5-6L4A44e8JzXTZA:-N1xA_-K0kwsJ0vGNaOx:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/Documentation/manifest-syntax.rst#L862)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add this sentence:
```
The application manifest must contain ``sgx.debug = true``.
```
</blockquote></details>

Done.
___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N1x9B3H9wYora8XPh18:b-ilt6y3) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is also a `-r <path>` option in VTune which allows to choose whatever file path name. Just for your information.
</blockquote></details>

Yeah, I know, but then if I write all these things, it will be like explaining the basics of vtune. So, I limited myself to the basic options. Even vtune's getting started has only the standard options
___
*[`Documentation/devel/performance.rst` line 585 at r8](https://reviewable.io/reviews/gramineproject/gramine/478#-N1x0Mhq8Q5gH6oIv2em:-N1xAmmTB6YivBMD25XA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a32643d343da34e6b6b048c59ec40eb5a0f036dd/Documentation/devel/performance.rst#L585)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please expand to
```
#. Add ``sgx.vtune_profile = true`` and ``sgx.debug = true`` to the manifest.
```

Without `sgx.debug`, I got an empty report, and Gramine complained like this:
```
error: Reading TCS.FLAGS.DBGOPTIN failed: -5
error: load_enclave() failed with error -5
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 11:52 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-13 11:52 UTC, dimakuv commented
Jenkins, test this please

2022-05-15 00:51 UTC, mkow requested changes
> Reviewed 2 of 7 files at r2, 1 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @svenkata9)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N24Af5T7gAgBEv9r5Mp:b-y93sgr) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
I'd rather write `r<report_num>sgxhs` then.

> Yeah, I think it's pretty obvious that `000` is changing. The rest stands for `Report 000 SGX HotSpots`.

But you still need to guess this, and around the number you have letters which seem completely random (or at least were to me when I read them the first time).
___
*[`Pal/src/host/Linux-SGX/sgx_profile.c` line 380 at r2](https://reviewable.io/reviews/gramineproject/gramine/478#-N-ShZBj4JZ3V8z1Yefd:-N24BRCbAbOffY-XomO4:b7dov05) ([raw file](https://github.com/gramineproject/gramine/blob/b63e84e7ef4d6ab5c11fea142589852bc8343167/Pal/src/host/Linux-SGX/sgx_profile.c#L380)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> That would mean that it can't resolve data symbols?

From what I remember about those VTune runs (it was a month ago already), indeed the data symbols were there. I don't really know *how* it is done, but my theory is that VTune deduces all the information from these two inputs: the filename of the binary and the virtual address at which the code segment starts in program memory. Technically, it is then easy to calculate the base address where the binary is loaded in program memory, apply offsets and thus arrive to all data symbols' addresses.

I'll try to discuss this with VTune developers to learn more.
</blockquote></details>

Yeah, maybe it just starts parsing ELF headers at the start address and completely ignores the size, dunno.


<!-- Sent from Reviewable.io -->

2022-05-15 03:00 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N24ciNc3-d6EHNxxVs9:b8hcqtg) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
Why are we obsessed over this (format)? Someone who chooses VTune to profile is assumed to know this information, or can go through vtune documentation if they need more clarity on the results directory or anything related to vtune for that matter. In fact, vtune documentation itself doesn't delve much, and we have provided at least some level of information here on where the results would go. Please be considerate. I would like to leave it at this.

Below is a snippet from the VTune documentation. People don't debate what is the default directory etc., Is this a blocker for you to approve this PR?

>> This command runs the hotspots analysis in the hardware event-based sampling mode for a Linux myApp application, writes the result to the default directory, and outputs a summary report by default.


<!-- Sent from Reviewable.io -->

2022-05-15 10:16 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @svenkata9)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N26C3ozDEJJnIkdTh93:b-rvqikg) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
> obsessed

? I just pointed out a place which was confusing for me when I read it and suggested a less abiguous wording.

> In fact, vtune documentation itself doesn't delve much

I don't want you to write a paragraph about this format, but to change a single word.

> Below is a snippet from the VTune documentation. People don't debate what is the default directory etc.,

I don't see how VTune docs and their conventions relate to our docs, plus, whether this quote is reasonable depends on the context there (e.g. maybe this "default directory" is explained somewhere already).


<!-- Sent from Reviewable.io -->

2022-05-15 11:43 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N26WNooAdnm2zQH0GXH:b-2vnv27) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> obsessed

? I just pointed out a place which was confusing for me when I read it and suggested a less abiguous wording.

> In fact, vtune documentation itself doesn't delve much

I don't want you to write a paragraph about this format, but to change a single word.

> Below is a snippet from the VTune documentation. People don't debate what is the default directory etc.,

I don't see how VTune docs and their conventions relate to our docs, plus, whether this quote is reasonable depends on the context there (e.g. maybe this "default directory" is explained somewhere already).
</blockquote></details>

You probably raised an issue, which we clarified already. Like I said, this will be clear for those who are reading the documentation on where to look for, for the results. In addition, they can always refer to vtune directly, because we are limiting our documentation to basics of capturing - explaining more than that, I feel and believe, does not fit in the scope of Gramine's documentation. So, I will just leave it at this current way that it looks like. Thanks.


<!-- Sent from Reviewable.io -->

2022-05-15 11:48 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N26Xcwe8pJb5fjEhmDV:b-rnlew9) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

You probably raised an issue, which we clarified already. Like I said, this will be clear for those who are reading the documentation on where to look for, for the results. In addition, they can always refer to vtune directory, because we are limiting our documentation to basics of capturing - explaining more than that, I feel and believe, does not fit in the scope of Gramine's documentation. So, I will just leave it at this current way that it looks like. Thanks.
</blockquote></details>

Further when you start the collection with vtune, you'll see that vtune notifies the user where the reports are output. So, I don't see a need to explain or change this. If I had just written without the word format, that is misleading. But, I added that word specifically to let the users know where they can look for for the results if he is new to using this tool.


<!-- Sent from Reviewable.io -->

2022-05-15 15:04 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @svenkata9)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N27EBlbE39fyr90xl7w:b-uqvlgd) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
> explaining more than that, I feel and believe, does not fit in the scope of Gramine's documentation
> I don't see a need to explain or change this

But I'm not asking you to add any explanations or extensive documentation, just to change a single word which was confusing/ambiguous to me. And I suggested a replacement word which isn't ambiguous.


<!-- Sent from Reviewable.io -->

2022-05-16 02:00 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N29__I38bNHqU4Tk3uj:b-y5yt2o) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> explaining more than that, I feel and believe, does not fit in the scope of Gramine's documentation
> I don't see a need to explain or change this

But I'm not asking you to add any explanations or extensive documentation, just to change a single word which was confusing/ambiguous to me. And I suggested a replacement word which isn't ambiguous.
</blockquote></details>

I don't think the current one looks ambiguous. On top of that, I think it will look ugly by putting this as r<000>sgxhs. We are complicating a thing that people can understand straightforward. Why don't we let this commit go with what it has now, and see how many people have trouble in figuring this out, and update later if required?


<!-- Sent from Reviewable.io -->

2022-05-16 06:28 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N2AXSKd4qy5LNjbKqZJ:b-rtcndl) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I don't think the current one looks ambiguous. On top of that, I think it will look ugly by putting this as r<000>sgxhs. We are complicating a thing that people can understand straightforward. Why don't we let this commit go with what it has now, and see how many people have trouble in figuring this out, and update later if required?
</blockquote></details>

@svenkata9 @mkow To resolve this discussion, maybe we simply add my explanation in parentheses, like this:
```
It will output the data collected to a directory of the format ``r000sgxhs/`` (the format stands for
"Report 000, SGX HotSpots" where "000" is the report number).
```

This will resolve Michal's confusion and will give very clear explanation on this magic letters-and-numbers format. This is also sufficiently short to put in our docs.

We should agree on some fix here and move on with this PR. Hope my suggestion is fine with you both.


<!-- Sent from Reviewable.io -->

2022-05-16 06:49 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N2AbPeC71dLQS6uC1_T:b901qpc) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@svenkata9 @mkow To resolve this discussion, maybe we simply add my explanation in parentheses, like this:
```
It will output the data collected to a directory of the format ``r000sgxhs/`` (the format stands for
"Report 000, SGX HotSpots" where "000" is the report number).
```

This will resolve Michal's confusion and will give very clear explanation on this magic letters-and-numbers format. This is also sufficiently short to put in our docs.

We should agree on some fix here and move on with this PR. Hope my suggestion is fine with you both.
</blockquote></details>

To be honest, I am little uncomfortable, @dimakuv, for even mentioning what you suggested. Two reasons (1) when you run, VTune will output a message where the results are stored. (2) If we had blindly left it at for the user to figure out where the output went, there is a reason to explain all this. The user will see r001sgxhs, or r123sgxhs and he is not going to stop looking into those directories. We are assuming that we will have someone that knows this when he chooses to run with vtune (same as perf), not really layman.


<!-- Sent from Reviewable.io -->

2022-05-16 07:06 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 9 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N2AfVk84InY_M1oj7CO:b-72wt7r) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

To be honest, I am little uncomfortable, @dimakuv, for even mentioning what you suggested. Two reasons (1) when you run, VTune will output a message where the results are stored. (2) If we had blindly left it at for the user to figure out where the output went, there is a reason to explain all this. The user will see r001sgxhs, or r123sgxhs and he is not going to stop looking into those directories. We are assuming that we will have someone that knows this when he chooses to run with vtune (same as perf), not really layman.
</blockquote></details>

I am uncomfortable with explaining the format r000sgxhs. So, I have modified the command line to include `-result-dir`. I personally do not prefer this because there is a probably of people using reverse-search to run the same collect command from the history, and it can overwrite the previous results. So, I would rather prefer vtune to manage naming of the directories (and vtune will indicate where it is outputting the results). I have made this change to include `-result-dir` only for the sake of resolving this deadlock.


<!-- Sent from Reviewable.io -->

2022-05-16 07:10 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: 9 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N2AgCmr6_hUV0yiu4sf:b-5j2ttj) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

I am uncomfortable with explaining the format r000sgxhs. So, I have modified the command line to include `-result-dir`. I personally do not prefer this because there is a probably of people using reverse-search to run the same collect command from the history, and it can overwrite the previous results. So, I would rather prefer vtune to manage naming of the directories (and vtune will indicate where it is outputting the results). I have made this change to include `-result-dir` only for the sake of resolving this deadlock.
</blockquote></details>

Okay. I see that vtune poses an error now if you specify the same directory. `vtune: Fatal error: The specified result directory already contains result data. Provide another result directory.`

So, we should be okay with this change. If someone who is very well familiar with vtune, wants to run without -result-dir, they can still do that. Hope that concludes this discussion.


<!-- Sent from Reviewable.io -->

2022-05-16 08:02 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/devel/performance.rst` line 591 at r7](https://reviewable.io/reviews/gramineproject/gramine/478#-N1uVJfUBU2JBywD8_jn:-N2AsggM1PgONxPtgXkA:b-9k4c5i) ([raw file](https://github.com/gramineproject/gramine/blob/4b6512e3e88a3cadc51744aa5fe27d7a4c73b3a6/Documentation/devel/performance.rst#L591)):*
<details><summary><i>Previously, svenkata9 (Sankaranarayanan Venkatasubramanian) wrote…</i></summary><blockquote>

Okay. I see that vtune poses an error now if you specify the same directory. `vtune: Fatal error: The specified result directory already contains result data. Provide another result directory.`

So, we should be okay with this change. If someone who is very well familiar with vtune, wants to run without -result-dir, they can still do that. Hope that concludes this discussion.
</blockquote></details>

The change looks good to me, and should resolve this deadlocked discussion


<!-- Sent from Reviewable.io -->

2022-05-16 15:19 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-05-16 16:30 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/478)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-16 19:36 UTC, merged