[Pal] Add missing syscall to close fds.
gramineproject/gramine pull request #479
Opened 2022-03-30 02:58 UTC by lzha101

Signed-off-by: Zhang Lili <lili.z.zhang@intel.com>

## Description of the changes 
Seems the two file descriptors (enclave->token and enclave->sigfile) will not be used after the call initialize_enclave().   Close the fds for resource recycling.

## How to test this PR?

2022-03-30 03:12 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/479#-MzNnZc192Goo7AKbZJL:-MzNnZc192Goo7AKbZJM:b-tl45kd) ([raw file](https://github.com/gramineproject/gramine/blob/841a58bf0dc7f3a61854f959146cbaeb964ba4b5/Pal/src/host/Linux-SGX/sgx_main.c#L953)):*
> ```C
> 
>     DO_SYSCALL(close, enclave->token);
>     DO_SYSCALL(close, enclave->sigfile);
> ```

Since they are not used, they should rather be removed completely from `enclave` structure and passed directly to `initialize_enclave`


<!-- Sent from Reviewable.io -->

2022-03-30 03:28 UTC, lzha101 commented
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)
> 
> _[Pal/src/host/Linux-SGX/sgx_main.c, line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/479#-MzNnZc192Goo7AKbZJL:-MzNnZc192Goo7AKbZJM:b-tl45kd) ([raw file](https://github.com/gramineproject/gramine/blob/841a58bf0dc7f3a61854f959146cbaeb964ba4b5/Pal/src/host/Linux-SGX/sgx_main.c#L953)):_
> 
> > ```c
> >     DO_SYSCALL(close, enclave->token);
> >     DO_SYSCALL(close, enclave->sigfile);
> > ```
> 
> Since they are not used, they should rather be removed completely from `enclave` structure and passed directly to `initialize_enclave`

Thanks for the comments. Agree that they can be removed from `enclave` structure. How about directly moving the logic to `initialize_enclave()` instead of passing the fds to `initialize_enclave()`?

2022-03-30 03:37 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/479#-MzNnZc192Goo7AKbZJL:-MzNtbtdB6tbMTWd_Eb7:bdcw1s9) ([raw file](https://github.com/gramineproject/gramine/blob/841a58bf0dc7f3a61854f959146cbaeb964ba4b5/Pal/src/host/Linux-SGX/sgx_main.c#L953)):*
<details><summary><i>Previously, lzha101 wrote…</i></summary><blockquote>

Thanks for the comments. Agree that they can be removed from `enclave` structure. How about directly moving the logic to `initialize_enclave()` instead of passing the fds to `initialize_enclave()`?
</blockquote></details>

Sounds like a good idea


<!-- Sent from Reviewable.io -->

2022-03-30 06:23 UTC, lzha101 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)
> 
> _[Pal/src/host/Linux-SGX/sgx_main.c, line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/479#-MzNnZc192Goo7AKbZJL:-MzNtbtdB6tbMTWd_Eb7:bdcw1s9) ([raw file](https://github.com/gramineproject/gramine/blob/841a58bf0dc7f3a61854f959146cbaeb964ba4b5/Pal/src/host/Linux-SGX/sgx_main.c#L953)):_
> 
> Previously, lzha101 wrote…
> Sounds like a good idea

I've updated the code. Please take a look. Thanks.

2022-04-01 06:47 UTC, lzha101 commented
> > Reviewed 2 of 2 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)_ status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)
> 
> _[-- commits, line 1 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVbywQ4-XHTFikhjpS):_ Please do not force push, use fixup commits instead. The commit message can be changed on final rebase (which we will do before merging), you can post new commit message as a comment in reviewable.
> 
> _[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVcFuE42cnquiVwb_j):_ Wrong tag (in `[]`) and this is too long for a one line. How about:
> 
> ```
> [Pal/Linux-SGX] Remove `sigfile` and `token` from `struct pal_enclave`
> 
> These two fields were used locally in one function only.
> ```
> 
> If you think this commit message is fine you don't have to do anything, we will change it before merging this PR (on final rebase).
> 
> _[Pal/src/host/Linux-SGX/sgx_main.c, line 953 at r1](https://reviewable.io/reviews/gramineproject/gramine/479#-MzNnZc192Goo7AKbZJL:-MzVfrWy7J9t_wBUJsCx:br06oxi) ([raw file](https://github.com/gramineproject/gramine/blob/841a58bf0dc7f3a61854f959146cbaeb964ba4b5/Pal/src/host/Linux-SGX/sgx_main.c#L953)):_
> 
> Previously, lzha101 wrote…
> Looks good, thanks!
> 
> _[Pal/src/host/Linux-SGX/sgx_main.c, line 208 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVbZLtCl934pOxb-_v:-MzVbZLtCl934pOxb-_w:b-43sqie) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L208)):_
> 
> > ```c
> >     char* sig_path = NULL;
> >     char* token_path = NULL;
> >     int sigfile = -1, token = -1;
> > ```
> 
> I would rename these to `sig_fd` and `token_fd`.
> 
> _[Pal/src/host/Linux-SGX/sgx_main.c, line 258 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVfFV01K4deZxKvuvi:-MzVfFV01K4deZxKvuvj:b-zfpjzv) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L258)):_
> 
> > ```c
> >             "Cannot open token %s. Use gramine-sgx-get-token on the runtime host or run "
> >             "`make SGX=1 sgx-tokens` in the Gramine source to create the token file.",
> >             token_path);
> > ```
> 
> While we are here, please rewrap this to:
> 
> ```c
>         log_error("Cannot open token %s. Use gramine-sgx-get-token on the runtime host or run "      
>                   "`make SGX=1 sgx-tokens` in the Gramine source to create the token file.",         
>                   token_path);
> ```

I cannot access the `reviewable` (maybe network problem).  Sorry for force-push again. Will use fixup next time. :)

The comments are fixed in the latest commit. Please take a look.

2022-04-01 15:57 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @lzha101)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 258 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVfFV01K4deZxKvuvi:-Mz_pWexAx9UdCx_4qOV:b-ohouqx) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L258)):*
> I cannot access the reviewable (maybe network problem).

Please try to fix that, we use it for all reviews

> The comments are fixed in the latest commit. Please take a look.

This comment is still incorrectly wrapped (2nd and 3rd row are misaligned).
Btw, I recommend reading https://gramine.readthedocs.io/en/latest/devel/contributing.html if you have not done so yet.


<!-- Sent from Reviewable.io -->

2022-04-02 02:18 UTC, lzha101 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVcFuE42cnquiVwb_j):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wrong tag (in `[]`) and this is too long for a one line. How about:
```
[Pal/Linux-SGX] Remove `sigfile` and `token` from `struct pal_enclave`

These two fields were used locally in one function only.
```

If you think this commit message is fine you don't have to do anything, we will change it before merging this PR (on final rebase).
</blockquote></details>

The commit message looks good to me
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 208 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVbZLtCl934pOxb-_v:-MzbxrRh13IW334TLa_J:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L208)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would rename these to `sig_fd` and `token_fd`.
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 258 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVfFV01K4deZxKvuvi:-MzbrcuU5Df5tRJDqhpe:b-pcoxhu) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L258)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I cannot access the reviewable (maybe network problem).

Please try to fix that, we use it for all reviews

> The comments are fixed in the latest commit. Please take a look.

This comment is still incorrectly wrapped (2nd and 3rd row are misaligned).
Btw, I recommend reading https://gramine.readthedocs.io/en/latest/devel/contributing.html if you have not done so yet.
</blockquote></details>

Thanks.  Fixed in the latest commit.


<!-- Sent from Reviewable.io -->

2022-04-02 17:12 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-04-04 12:41 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lzha101)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 208 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVbZLtCl934pOxb-_v:-MzoZpMjDzsvPzChF9OF:b-dub3w5) ([raw file](https://github.com/gramineproject/gramine/blob/e699720e16be7442160c976f0c79739f31530258/Pal/src/host/Linux-SGX/sgx_main.c#L208)):*
<details><summary><i>Previously, lzha101 wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

I still see `sigfile_fd`. Borys requested to rename to `sig_fd`. Anyway, Borys approved, and I don't mind. So nothing to change here.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/479#-Mzo_dgl5l7MEHXjExbv:-Mzo_dgl5l7MEHXjExbw:b-hspevw) ([raw file](https://github.com/gramineproject/gramine/blob/d41b78540908c8d23f35a2c3aa46ab82396229e9/Pal/src/host/Linux-SGX/sgx_main.c#L256)):*
> ```C
>     if (token_fd < 0) {
>         log_error("Cannot open token %s. Use gramine-sgx-get-token on the runtime host or run "
>                   "`make SGX=1 sgx-tokens` in the Gramine source to create the token file.",
> ```

This line is stale, we don't have `sgx-tokens` anymore. I'll fix it myself during final rebase, no need to do anything.


<!-- Sent from Reviewable.io -->

2022-04-04 12:41 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lzha101)



<!-- Sent from Reviewable.io -->

2022-04-04 12:42 UTC, dimakuv commented
Jenkins, test this please

2022-04-04 13:23 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`LibOS.shim.test.ltp.test_ltp.test_ltp[fdatasync01]` timed out, unrelated)

2022-04-04 22:26 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 2 unresolved discussions, period found at the end of a one-liner, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @lzha101)



<!-- Sent from Reviewable.io -->

2022-04-05 11:18 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/479#-Mzo_dgl5l7MEHXjExbv:-MztRaGc79yM2K5sn_Tk:bfhqmln) ([raw file](https://github.com/gramineproject/gramine/blob/d41b78540908c8d23f35a2c3aa46ab82396229e9/Pal/src/host/Linux-SGX/sgx_main.c#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line is stale, we don't have `sgx-tokens` anymore. I'll fix it myself during final rebase, no need to do anything.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2022-04-05 11:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/479#-MzVcFuE42cnquiVwb_j):*
<details><summary><i>Previously, lzha101 wrote…</i></summary><blockquote>

The commit message looks good to me
</blockquote></details>

Done as part of final rebase.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/479#-Mzo_dgl5l7MEHXjExbv:-MztRTovEtBKOrHwTWbZ:b-wpmau6) ([raw file](https://github.com/gramineproject/gramine/blob/d41b78540908c8d23f35a2c3aa46ab82396229e9/Pal/src/host/Linux-SGX/sgx_main.c#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done. Forgot at the first rebase.


<!-- Sent from Reviewable.io -->

2022-04-05 11:19 UTC, dimakuv commented
Jenkins, test this please

2022-04-05 11:19 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/479)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-04-05 12:39 UTC, merged