[Docs] Add admonition about master branch
gramineproject/gramine pull request #481
Opened 2022-03-30 15:06 UTC by woju

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>

## Description of the changes 

There were a few reports from people who used `/en/latest` documentation against v1.1 packaged version and got confused, because things got changed (last one was #477).

Let's add a warning to `/en/latest`.

## How to test this PR?

2022-03-30 17:24 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Documentation/_templates/layout.html, line 3 at r2](https://reviewable.io/reviews/gramineproject/gramine/481#-MzQqVUNDeHFc8mFfVh_:-MzQqVUNDeHFc8mFfVha:b-vm4jvm) ([raw file](https://github.com/gramineproject/gramine/blob/c0bea4b549594a62c56beba8cf69a2db20e6f734/Documentation/_templates/layout.html#L3)):*
> ```HTML
> {% extends '!layout.html' %}
> {% block document %}
> {% if READTHEDOCS and (current_version == 'latest' or current_version.startswith('woju')) %}
> ```

The other part of conditional is meant for demo. I'll remove it when you'll fine with the admonition. Blocking until removed.


<!-- Sent from Reviewable.io -->

2022-04-01 16:07 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_sFiGE3pdwC4g5juO:-Mz_sFiGE3pdwC4g5juP:b-mxd5t7) (no related file):*
While we are here, could you add an instruction to checkout appropriate tag in https://gramine.readthedocs.io/en/latest/quickstart.html ?

---
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_rofh9TxW6wSil4p-):*
Is there any other reason for this than then blocking comment below?


<!-- Sent from Reviewable.io -->

2022-04-01 16:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_sFiGE3pdwC4g5juO:-Mz_vTMt1fQdzgVxJPBV:b7p781n) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

While we are here, could you add an instruction to checkout appropriate tag in https://gramine.readthedocs.io/en/latest/quickstart.html ?
</blockquote></details>

You mean in `git clone` to get `helloworld` example?

---
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_rofh9TxW6wSil4p-):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is there any other reason for this than then blocking comment below?
</blockquote></details>

No, just this commit will be amended to edit the condition.


<!-- Sent from Reviewable.io -->

2022-04-01 16:33 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_sFiGE3pdwC4g5juO:-Mz_yJq321PGuDNhjeP2:b-is8h8j) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You mean in `git clone` to get `helloworld` example?
</blockquote></details>

precisely 

---


<!-- Sent from Reviewable.io -->

2022-04-01 16:37 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_sFiGE3pdwC4g5juO:-Mz_ypfAEPNQg0CNfaxa:be08h0b) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

precisely 
</blockquote></details>

This is in the middle of rst, so I'll have to invent some creative approach. I'll check if I can do this in a not too hacky way.

---


<!-- Sent from Reviewable.io -->

2022-04-01 16:39 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/481#-Mz_sFiGE3pdwC4g5juO:-Mz_zalf5oPejyRflNZ8:bgye4cq) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is in the middle of rst, so I'll have to invent some creative approach. I'll check if I can do this in a not too hacky way.
</blockquote></details>

Maybe just add a paragraph describing how to get the installed Gramine version (probably from apt) and then to checkout such tag (equal to the installed version).

---


<!-- Sent from Reviewable.io -->

2022-04-04 00:31 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[Documentation/_templates/layout.html, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/481#-MzlyieW-k7LA0YbTyUX:-MzlyieX-qDBLBDFXoBA:b-wd3p3o) ([raw file](https://github.com/gramineproject/gramine/blob/c0bea4b549594a62c56beba8cf69a2db20e6f734/Documentation/_templates/layout.html#L10)):*
> ```HTML
>         master branch. If you installed Gramine from packages, documentation
>         for the stable version is available at
>         <a href="https://gramine.rtfd.io/en/stable/">https://gramine.rtfd.io/en/stable/</a>.
> ```

Please use `readthedocs.io`


<!-- Sent from Reviewable.io -->

2022-04-04 06:27 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-04-05 15:47 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Documentation/_templates/layout.html, line 10 at r2](https://reviewable.io/reviews/gramineproject/gramine/481#-MzlyieW-k7LA0YbTyUX:-MzuOlQjEN1TXwd_rvBt:bt4vpq) ([raw file](https://github.com/gramineproject/gramine/blob/c0bea4b549594a62c56beba8cf69a2db20e6f734/Documentation/_templates/layout.html#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

rtfd.io is perfectly fine: https://docs.readthedocs.io/en/latest/automatic-redirects.html#rtfd-io

Unless you object to the "f" letter.
</blockquote></details>

The latter, although originally I also wasn't sure about the former.


<!-- Sent from Reviewable.io -->

2022-04-06 07:48 UTC, dimakuv approved these changes
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-04-06 16:37 UTC, boryspoplawski requested changes
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[Documentation/conf.py, line 94 at r3](https://reviewable.io/reviews/gramineproject/gramine/481#-MzzixGZ7uMGlqPk8wmk:-MzzixGZ7uMGlqPk8wml:b-rbzykp) ([raw file](https://github.com/gramineproject/gramine/blob/53ae57e111304e3bce5d7dc9dbcc79a9cc4b3ed1/Documentation/conf.py#L94)):*
> ```Python
>                     ['git', 'tag', '--points-at']).decode().strip().split()
>                 if tag.startswith('v')]
>             print(tags)
> ```

Isn't this a leftover debug print?


<!-- Sent from Reviewable.io -->

2022-04-06 19:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Documentation/conf.py, line 94 at r3](https://reviewable.io/reviews/gramineproject/gramine/481#-MzzixGZ7uMGlqPk8wmk:-N--JGNk1fwceU7dvQ84:b-9i1kur) ([raw file](https://github.com/gramineproject/gramine/blob/53ae57e111304e3bce5d7dc9dbcc79a9cc4b3ed1/Documentation/conf.py#L94)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't this a leftover debug print?
</blockquote></details>

Done. Yes it was. :/


<!-- Sent from Reviewable.io -->

2022-04-06 19:22 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-06 21:46 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-07 01:03 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-07 01:39 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-07 06:38 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/481)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-07 06:39 UTC, merged