[CI-Examples] Add an async Rust example
gramineproject/gramine pull request #495
Opened 2022-04-05 12:14 UTC by NieDzejkob

Rust's async runtime has triggered bugs in our epoll in the past.
This example will serve as a smoke-test in this area, as well as
point users to the manifest settings that are necessary.

## How to test this PR? 

1. `cd CI-Examples/rust`
2. `make start-gramine-server SGX=1`
3. In another terminal: `curl localhost:3000`
4. Make sure the CI config changes work

2022-04-05 16:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-MzuUFXQ42v-L38nAWni:-MzuUFXQ42v-L38nAWnj:brdtl8c) (no related file):*
I didn't review this PR yet, but do we want this to be in CI-Examples or in a separate https://github.com/gramineproject/examples repo?

I guess the idea here is that (a) we show a non-trivial Rust workload, (b) we test epoll corner cases. I think I'm ok with this example being in CI-Examples (in the core repo). But are these packages and the build process lightweight for our CI? How many seconds/minutes it takes to download Rust and all required crates, and how much time it takes to load the Rust SGX enclave and run the workload?

---


<!-- Sent from Reviewable.io -->

2022-04-05 17:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-MzuUFXQ42v-L38nAWni:-MzugUrG6sbIeOYeDFay:bmnuffa) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't review this PR yet, but do we want this to be in CI-Examples or in a separate https://github.com/gramineproject/examples repo?

I guess the idea here is that (a) we show a non-trivial Rust workload, (b) we test epoll corner cases. I think I'm ok with this example being in CI-Examples (in the core repo). But are these packages and the build process lightweight for our CI? How many seconds/minutes it takes to download Rust and all required crates, and how much time it takes to load the Rust SGX enclave and run the workload?
</blockquote></details>

I'd like to have this in CI because it covert a lot of code paths which aren't exposed by other tests.
Let's start the CI and check how long does it take.

---


<!-- Sent from Reviewable.io -->

2022-04-05 17:09 UTC, mkow commented
Jenkins, test this please

2022-04-05 18:41 UTC, woju commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-MzuUFXQ42v-L38nAWni:-Mzv0x7SBc75zGaamIkW:bi6sae5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd like to have this in CI because it covert a lot of code paths which aren't exposed by other tests.
Let's start the CI and check how long does it take.
</blockquote></details>

That was pretty quick:

```
+ cd CI-Examples/rust
+ make -j8
cargo build --release
make: cargo: Command not found
Makefile:22: recipe for target 'build-rust' failed
make: *** [build-rust] Error 127
```

---


<!-- Sent from Reviewable.io -->

2022-04-05 19:40 UTC, woju commented
Jenkins, test this please

2022-04-05 20:42 UTC, woju commented
Jenkins, test this please

2022-04-05 21:23 UTC, woju commented
Jenkins, test this please

2022-04-05 21:34 UTC, woju commented
Jenkins, test this please

2022-04-05 22:38 UTC, woju commented
gramine-{18.04,20.04}, gramine-debug-20.04:
```
+ cd CI-Examples/rust
+ make -j8
cargo build --release
gramine-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dself_exe=target/release/rust \
	rust.manifest.template rust.manifest
    Updating crates.io index
 Downloading crates ...
  Downloaded autocfg v1.1.0
  Downloaded bytes v1.1.0
  Downloaded fnv v1.0.7
  Downloaded cfg-if v1.0.0
  Downloaded futures-channel v0.3.21
  Downloaded futures-task v0.3.21
  Downloaded futures-sink v0.3.21
  Downloaded futures-core v0.3.21
  Downloaded futures-util v0.3.21
  Downloaded httpdate v1.0.2
  Downloaded httparse v1.6.0
  Downloaded http-body v0.4.4
  Downloaded http v0.2.6
  Downloaded hashbrown v0.11.2
  Downloaded lazy_static v1.4.0
  Downloaded itoa v1.0.1
  Downloaded indexmap v1.8.1
  Downloaded libc v0.2.121
  Downloaded syn v1.0.90
  Downloaded socket2 v0.4.4
  Downloaded smallvec v1.8.0
  Downloaded slab v0.4.6
  Downloaded signal-hook-registry v1.4.0
  Downloaded want v0.3.0
  Downloaded h2 v0.3.13
  Downloaded tracing-attributes v0.1.20
  Downloaded tracing v0.1.32
  Downloaded tokio v1.17.0
  Downloaded tokio-util v0.7.1
  Downloaded hyper v0.14.18
  Downloaded unicode-xid v0.2.2
  Downloaded try-lock v0.2.3
  Downloaded tracing-core v0.1.24
  Downloaded tower-service v0.3.1
  Downloaded tokio-macros v1.7.0
  Downloaded scopeguard v1.1.0
  Downloaded quote v1.0.17
  Downloaded proc-macro2 v1.0.36
  Downloaded pin-utils v0.1.0
  Downloaded pin-project-lite v0.2.8
  Downloaded parking_lot_core v0.9.2
  Downloaded parking_lot v0.12.0
  Downloaded once_cell v1.10.0
  Downloaded num_cpus v1.13.1
  Downloaded mio v0.8.2
  Downloaded memchr v2.4.1
  Downloaded log v0.4.16
  Downloaded lock_api v0.4.7
   Compiling libc v0.2.121
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.36
   Compiling cfg-if v1.0.0
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.90
   Compiling log v0.4.16
   Compiling parking_lot_core v0.9.2
   Compiling pin-project-lite v0.2.8
   Compiling futures-core v0.3.21
   Compiling smallvec v1.8.0
   Compiling bytes v1.1.0
   Compiling scopeguard v1.1.0
   Compiling memchr v2.4.1
   Compiling futures-task v0.3.21
   Compiling lazy_static v1.4.0
   Compiling fnv v1.0.7
   Compiling once_cell v1.10.0
   Compiling futures-util v0.3.21
   Compiling itoa v1.0.1
   Compiling httparse v1.6.0
   Compiling futures-channel v0.3.21
   Compiling pin-utils v0.1.0
   Compiling hashbrown v0.11.2
   Compiling futures-sink v0.3.21
   Compiling slab v0.4.6
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling httpdate v1.0.2
   Compiling lock_api v0.4.7
   Compiling indexmap v1.8.1
   Compiling tracing-core v0.1.24
   Compiling http v0.2.6
   Compiling want v0.3.0
   Compiling quote v1.0.17
   Compiling socket2 v0.4.4
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.8.2
   Compiling num_cpus v1.13.1
   Compiling parking_lot v0.12.0
   Compiling http-body v0.4.4
   Compiling tokio-macros v1.7.0
   Compiling tracing-attributes v0.1.20
   Compiling tokio v1.17.0
   Compiling tracing v0.1.32
   Compiling tokio-util v0.7.1
   Compiling h2 v0.3.13
   Compiling hyper v0.14.18
   Compiling rust v0.1.0 (/home/jenkins/workspace/graphene-18.04/CI-Examples/rust)
    Finished release [optimized] target(s) in 49.79s
+ ../../Scripts/wait_for_server 60 127.0.0.1 8002
+ make -j8 start-gramine-server
cargo build --release
+ LOOP=1 CONCURRENCY_LIST=1 32 ../common_tools/benchmark-http.sh 127.0.0.1:3000
ab -k -n 10000 -c 1 127.0.0.1:3000/random/10K.1.html
apr_socket_recv: Connection refused (111)
    Finished release [optimized] target(s) in 0.03s
gramine-direct rust
```

gramine-debug-18.04, gramine-debug-sanitizers, :
```
+ cd CI-Examples/rust
+ make -j8
cargo build
gramine-manifest \
	-Dlog_level=debug \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dself_exe=target/debug/rust \
	rust.manifest.template rust.manifest
error: failed to get `hyper` as a dependency of package `rust v0.1.0 (/home/jenkins/workspace/graphene-debug-18.04/CI-Examples/rust)`

Caused by:
  failed to create directory `/leeroy/.cargo/registry/index/github.com-1ecc6299db9ec823`

Caused by:
  Permission denied (os error 13)
Makefile:14: recipe for target 'build-rust' failed
make: *** [build-rust] Error 101
```

gramine-sgx-{18.04,20.04}-apps, gramine-sgx-sanitizers:
```
+ cd CI-Examples/rust
+ make -j8
cargo build --release
gramine-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dself_exe=target/release/rust \
	rust.manifest.template rust.manifest
make: *** No rule to make target 'target/release/rust', needed by 'rust.manifest.sgx'.  Stop.
make: *** Waiting for unfinished jobs....
    Updating crates.io index
 Downloading crates ...
  Downloaded cfg-if v1.0.0
  Downloaded fnv v1.0.7
  Downloaded futures-core v0.3.21
  Downloaded futures-sink v0.3.21
  Downloaded futures-channel v0.3.21
  Downloaded bytes v1.1.0
  Downloaded futures-task v0.3.21
  Downloaded itoa v1.0.1
  Downloaded lazy_static v1.4.0
  Downloaded httparse v1.6.0
  Downloaded lock_api v0.4.7
  Downloaded num_cpus v1.13.1
  Downloaded pin-utils v0.1.0
  Downloaded log v0.4.16
  Downloaded indexmap v1.8.1
  Downloaded scopeguard v1.1.0
  Downloaded signal-hook-registry v1.4.0
  Downloaded pin-project-lite v0.2.8
  Downloaded tower-service v0.3.1
  Downloaded tokio-macros v1.7.0
  Downloaded proc-macro2 v1.0.36
  Downloaded parking_lot_core v0.9.2
  Downloaded hashbrown v0.11.2
  Downloaded try-lock v0.2.3
  Downloaded parking_lot v0.12.0
  Downloaded want v0.3.0
  Downloaded socket2 v0.4.4
  Downloaded memchr v2.4.1
  Downloaded http v0.2.6
  Downloaded unicode-xid v0.2.2
  Downloaded autocfg v1.1.0
  Downloaded tracing-attributes v0.1.20
  Downloaded slab v0.4.6
  Downloaded h2 v0.3.13
  Downloaded mio v0.8.2
  Downloaded tracing-core v0.1.24
  Downloaded tokio-util v0.7.1
  Downloaded syn v1.0.90
  Downloaded tracing v0.1.32
  Downloaded hyper v0.14.18
  Downloaded futures-util v0.3.21
  Downloaded tokio v1.17.0
  Downloaded libc v0.2.121
  Downloaded smallvec v1.8.0
  Downloaded quote v1.0.17
  Downloaded once_cell v1.10.0
  Downloaded httpdate v1.0.2
  Downloaded http-body v0.4.4
   Compiling libc v0.2.121
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.90
   Compiling log v0.4.16
   Compiling futures-core v0.3.21
   Compiling pin-project-lite v0.2.8
   Compiling parking_lot_core v0.9.2
   Compiling scopeguard v1.1.0
   Compiling bytes v1.1.0
   Compiling smallvec v1.8.0
   Compiling memchr v2.4.1
   Compiling futures-task v0.3.21
   Compiling lazy_static v1.4.0
   Compiling futures-util v0.3.21
   Compiling itoa v1.0.1
   Compiling once_cell v1.10.0
   Compiling fnv v1.0.7
   Compiling futures-sink v0.3.21
   Compiling hashbrown v0.11.2
   Compiling futures-channel v0.3.21
   Compiling pin-utils v0.1.0
   Compiling httparse v1.6.0
   Compiling try-lock v0.2.3
   Compiling slab v0.4.6
   Compiling tower-service v0.3.1
   Compiling httpdate v1.0.2
   Compiling tracing-core v0.1.24
   Compiling http v0.2.6
   Compiling lock_api v0.4.7
   Compiling indexmap v1.8.1
   Compiling want v0.3.0
   Compiling quote v1.0.17
   Compiling socket2 v0.4.4
   Compiling num_cpus v1.13.1
   Compiling mio v0.8.2
   Compiling signal-hook-registry v1.4.0
   Compiling parking_lot v0.12.0
   Compiling http-body v0.4.4
   Compiling tracing-attributes v0.1.20
   Compiling tokio-macros v1.7.0
   Compiling tokio v1.17.0
   Compiling tracing v0.1.32
   Compiling tokio-util v0.7.1
   Compiling h2 v0.3.13
   Compiling hyper v0.14.18
   Compiling rust v0.1.0 (/home/jenkins/workspace/graphene-sgx-18.04-apps/CI-Examples/rust)
    Finished release [optimized] target(s) in 37.70s
```

@NieDzejkob ^

2022-04-06 07:52 UTC, NieDzejkob commented
```
Caused by:
  failed to create directory `/leeroy/.cargo/registry/index/github.com-1ecc6299db9ec823`

Caused by:
  Permission denied (os error 13)
```

Huh, any idea what might be happening here? Are all the {sgx,nosgx}-{debug,nodebug} builds done at the same time in the same container and causing some weird race condition? I have no idea what might be causing this, especially considering that this part is no different from all the other builds where that did work. And it doesn't look like a typical one-off spurious error, either.

Pushed a fix for the other issues.

2022-04-06 09:08 UTC, dimakuv requested changes
> Huh, any idea what might be happening here?

Weird, I also don't know how this can happen.

> Are all the {sgx,nosgx}-{debug,nodebug} builds done at the same time in the same container and causing some weird race condition?

Definitely not in the same container. Each job runs in its own container, and thus each job has its own FS.

> Reviewed 6 of 9 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-Mzy7IjX9E4oSUEPe4Kw:b6hh6ac)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[CI-Examples/rust/.gitignore, line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy7B-Z1PdwXhADjWQh:-Mzy7B-Z1PdwXhADjWQi:b-u2ema9) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/.gitignore#L1)):*
> ```ignore
> target
> ```

Shouldn't it have `/` at the beginning?
___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-Mzy5q9n-_Luj6rsfC7g:b-b9sfxh) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
> ```TOML
> # This file is automatically @generated by Cargo.
> # It is not intended for manual editing.
> version = 3
> ```

I'm unsure about whether we want to add `Cargo.lock` to this example. Does it really make sense to set the versions in stone? I mean, this is not an app/package ready for deployment, it's a source code that we build.

On the other hand, if suddenly one of the dependencies updates its implementation to use something unsupported in Gramine (like `inotify`), the example will fail. Yeah, ok, I see the rationale behind adding this file here. Resolving.
___
*[CI-Examples/rust/Cargo.toml, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxveEI6IF1RNT_37_u:-MzxveEI6IF1RNT_37_v:b4vy2nv) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.toml#L2)):*
> ```TOML
> [package]
> name = "rust"
> ```

Wouldn't it be better to have a more specific name, like `rust-hyper-http-server`?
___
*[CI-Examples/rust/Makefile, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy6hLZ1borw29GApeI:-Mzy6hL_BLeP9fIOll5C:b-ggtet4) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Makefile#L25)):*
> ```Makefile
> 
> SELF_EXE = target/release/rust
> endif
> ```

Isn't there a simpler way? Why can't we define `BUILD_MODE="debug"|"release"` based on the `DEBUG` envvar, and then do something like:
```
.PHONY: build-rust
build-rust:
	cargo build --$(BUILD_MODE)

SELF_EXE = target/$(BUILD_MODE)/rust
```
___
*[CI-Examples/rust/Makefile, line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy76L21xRyTT8zjjAe:-Mzy76L21xRyTT8zjjAf:bqxcnq0) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Makefile#L57)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) -rf *.token *.sig *.manifest.sgx *.manifest target/ OUTPUT
> ```

`OUTPUT` is not used in this example?
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxvTsS5MhTky8NkCH2:-MzxvTsS5MhTky8NkCH3:be6pwtk) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
> ```Markdown
> Makefile and a template for generating the manifest. The example application is
> an HTTP server based on `hyper`, to also serve as a test for Gramine's `epoll`
> implementation, as Rust's async runtimes used to trigger bugs in it.
> ```

That's way too concise :)

Please add a `QuickStart` section similar to other CI-examples.
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxw5zRCH0up1MIu5B_:-Mzxw5zRCH0up1MIu5Ba:bakqxln) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
> ```Markdown
> Makefile and a template for generating the manifest. The example application is
> an HTTP server based on `hyper`, to also serve as a test for Gramine's `epoll`
> implementation, as Rust's async runtimes used to trigger bugs in it.
> ```

Please add a note that this example hardcodes localhost and port 3000, and does *not* take any command-line arguments.
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxwo2o5wMDMRwoAVbF:-Mzxwo2o5wMDMRwoAVbG:bg00y4o) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
> ```Markdown
> Makefile and a template for generating the manifest. The example application is
> an HTTP server based on `hyper`, to also serve as a test for Gramine's `epoll`
> implementation, as Rust's async runtimes used to trigger bugs in it.
> ```

Actually, I'd prefer for this README to mimick Nginx and Lighttpd READMEs. In particular, to specify how to run the test (`http-benchmark`) manually on this Rust example.
___
*[CI-Examples/rust/rust.manifest.template, line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxvu2-9BIhSl9cMvV6:-Mzxvu2-9BIhSl9cMvV7:b-kfubxi) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L9)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}"
> loader.env.RUST_BACKTRACE = "full"
> ```

Why is this important? Maybe at least add a comment as to why we specify this envvar here?
___
*[CI-Examples/rust/rust.manifest.template, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxwGPP3dzMQMuCkiGd:-MzxwGPP3dzMQMuCkiGe:b-86soy3) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L17)):*
> ```
> 
> sgx.debug = true
> sgx.nonpie_binary = true
> ```

Rust generates non-PIE binaries? Why is this option here?
___
*[CI-Examples/rust/src/main.rs, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxwXmQCpCyIgUlNKar:-MzxwXmQCpCyIgUlNKas:b8x592f) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/src/main.rs#L11)):*
> ```XML
> 
> // If you wish to use a multithreaded runtime, then depending on how many CPU cores your
> // host has, you might need to adjust sgx.thread_num in the manifest.
> ```

I would want this to be duplicated in the manifest file... Like, having an explicit `sgx.thread_num = 4` in the manifest + this comment.


<!-- Sent from Reviewable.io -->

2022-04-06 11:05 UTC, woju reviewed
You can't assume anything outside `$WORKDIR` is writable by CI scripts. I don't know `cargo`, but looking by the path this seems like local cache for package manager? If so, this should be overridden.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-MzyXfb4CqeYqGIS7kTw:bsu17yn)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-04-06 12:10 UTC, NieDzejkob reviewed
Huh. Weird that it didn't fail on any other builds, then. Pushed a fix for that.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-MzykgzJAt6saXICKzAY:b-kjgd49)* status: 4 of 12 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[CI-Examples/rust/.gitignore, line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy7B-Z1PdwXhADjWQh:-Mzyk85SAsRqZTfYplrP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/.gitignore#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it have `/` at the beginning?
</blockquote></details>

Done.
___
*[CI-Examples/rust/Cargo.toml, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxveEI6IF1RNT_37_u:-MzyQZxw8hk9_AP-xKR0:bde5d0r) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.toml#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it be better to have a more specific name, like `rust-hyper-http-server`?
</blockquote></details>

Good point. Do you think the name of the directory should change as well?
___
*[CI-Examples/rust/Makefile, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy6hLZ1borw29GApeI:-MzyRfxg4nQ6rePOQtK_:b-xgz4le) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Makefile#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't there a simpler way? Why can't we define `BUILD_MODE="debug"|"release"` based on the `DEBUG` envvar, and then do something like:
```
.PHONY: build-rust
build-rust:
	cargo build --$(BUILD_MODE)

SELF_EXE = target/$(BUILD_MODE)/rust
```
</blockquote></details>

Done. `--debug` is not a thing, but there is `--profile [dev|release]`.
___
*[CI-Examples/rust/Makefile, line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy76L21xRyTT8zjjAe:-MzyRqtV1g1I4u5h6EdC:b-fr556n) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Makefile#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`OUTPUT` is not used in this example?
</blockquote></details>

Actually, the benchmark script does use it. I've updated the makefile to also remove the `result-*` it generates, like the nginx and lighttpd examples.
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxvTsS5MhTky8NkCH2:-Mzyfk8K7ixklgxdBxC_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's way too concise :)

Please add a `QuickStart` section similar to other CI-examples.
</blockquote></details>

Done.
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxw5zRCH0up1MIu5B_:-Mzyfk_O-yM_TqSqztqh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a note that this example hardcodes localhost and port 3000, and does *not* take any command-line arguments.
</blockquote></details>

Done.
___
*[CI-Examples/rust/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxwo2o5wMDMRwoAVbF:-Mzyfljc0LqVmGZktXbv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I'd prefer for this README to mimick Nginx and Lighttpd READMEs. In particular, to specify how to run the test (`http-benchmark`) manually on this Rust example.
</blockquote></details>

Done.
___
*[CI-Examples/rust/src/main.rs, line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxwXmQCpCyIgUlNKar:-MzykNLf1jrXbloHkaNX:b-4fl1dq) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/src/main.rs#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would want this to be duplicated in the manifest file... Like, having an explicit `sgx.thread_num = 4` in the manifest + this comment.
</blockquote></details>

Yeah, now that you mention it, it'd probably be better to specify `worker_threads = 4` too — this generalizes better than only one thread.
___
*[CI-Examples/rust/rust.manifest.template, line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxvu2-9BIhSl9cMvV6:-MzySL9b3uXgO4Zke0mz:b5uf8g3) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this important? Maybe at least add a comment as to why we specify this envvar here?
</blockquote></details>

This makes debugging easier, but we could consider this a leftover of me figuring out how to get this to work. I can remove it if you prefer.
___
*[CI-Examples/rust/rust.manifest.template, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxwGPP3dzMQMuCkiGd:-MzySlnm6cQ-J0VSeUyi:b-xle284) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Rust generates non-PIE binaries? Why is this option here?
</blockquote></details>

In my testing it is not necessary. Interestingly, however, the same holds for the `helloworld` example, and it nevertheless does set `nonpie_binary = true`.

I suspect that this might depend on how the build host's linker is set up, in which case either this should be set as is, or the `helloworld` example should remove it too, as Rust uses the linker from the system toolchain.


<!-- Sent from Reviewable.io -->

2022-04-06 12:23 UTC, mkow commented
Jenkins, retest this please

2022-04-06 12:46 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzyt9NC8I3KqD1Cbo2r:-Mzyt9NC8I3KqD1Cbo2s:b7ew4rf) (no related file):*
New CI problem, now about the cleanup and gitignore:
```
+ ./Scripts/clean-check
================================================================================
                ERROR: Source tree is not unchanged after clean:
--------------------------------------------------------------------------------
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test: CARGO_HOME
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: OUTPUT
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: result-220406-123507
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: rust-hyper-http-server.manifest
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: rust-hyper-http-server.manifest.sgx
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: rust-hyper-http-server.sig
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: rust-hyper-http-server.token
Only in /tmp/graphene-sgx-20.04-apps.clean-check.test/CI-Examples/rust: target
================================================================================
```

---
___
*[CI-Examples/rust/Cargo.toml, line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxveEI6IF1RNT_37_u:-MzytHtsEgQuHJe3nEqT:b5yubvq) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.toml#L2)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Good point. Do you think the name of the directory should change as well?
</blockquote></details>

Nah, the name of the directory is fine. We have similar logic with e.g. Python.
___
*[CI-Examples/rust/Makefile, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy6hLZ1borw29GApeI:-MzytavY9ODar0qpk6Bv:brq62gh) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Makefile#L25)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Done. `--debug` is not a thing, but there is `--profile [dev|release]`.
</blockquote></details>

Looks much nicer, thanks!
___
*[CI-Examples/rust/rust.manifest.template, line 9 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzxvu2-9BIhSl9cMvV6:-MzytsIo1D-vvlRkKXZ2:bn2cuzj) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L9)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

This makes debugging easier, but we could consider this a leftover of me figuring out how to get this to work. I can remove it if you prefer.
</blockquote></details>

Let's keep it, but please add a comment to it, smth like `# for easier debugging, not strictly needed to run this workload`
___
*[CI-Examples/rust/rust.manifest.template, line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-MzxwGPP3dzMQMuCkiGd:-Mzyu3qu8U2-pgKjmeXw:b1w9rv3) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/rust.manifest.template#L17)):*
> Rust uses the linker from the system toolchain

Ok, since it is so, let's keep the `nonpie_binary = true` option. Let's be on the safe side.


<!-- Sent from Reviewable.io -->

2022-04-06 14:13 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzz3-Jw4lsHe5nVLsY7:-MzzChsQ5yFVagLEFf35:bj2krsb) ([raw file](https://github.com/gramineproject/gramine/blob/5a85d74cbf2cc2aeea0a781202736fb062629f0b/.ci/lib/stage-clean-check.jenkinsfile#L36)):*
> Perhaps looping over CI-Examples would require less maintenance?

Nah, it's not that we add new CI-Examples every month. And as you mentioned, not all CI-Examples are run in CI.

> Interestingly, busybox is missing from this list. Looks like that example doesn't get run in CI.

IIRC, this is on purpose. Busybox is not run because we have a similar Bash example. And we have Busybox in CI-Examples because it is a very handy tool to examine the Gramine virtual environment (browsing through the Gramine FS, threads, processes, etc).
___
*[CI-Examples/rust/Makefile, line 4 at r4](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzz0fOj7VEb2QofCLwp:-MzzDFrY2zL5xhQgoZA6:b-ygi6qi) ([raw file](https://github.com/gramineproject/gramine/blob/5d627cc29340501332c510e65cbcad26fa6c4845/CI-Examples/rust/Makefile#L4)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

The name `rust-hyper-http-server` now repeats quite a lot in the Makefile. Do we want to make a variable for that? I don't think there's any prior art in the other examples for this, though...
</blockquote></details>

I have no problems reading it.


<!-- Sent from Reviewable.io -->

2022-04-06 14:35 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzyt9NC8I3KqD1Cbo2r:-MzzIC_QDiwdLv4zJbvy:btla52o) (no related file):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay, looks like another script needed editing. Fixed.
</blockquote></details>

Still some problems:
```
+ ./Scripts/gitignore-test
================================================================================
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? CI-Examples/rust/OUTPUT
?? CI-Examples/rust/result-220406-142448
Entering 'LibOS/shim/test/ltp/src'
Entering 'LibOS/shim/test/ltp/src/testcases/kernel/mce-test'
================================================================================
```

---


<!-- Sent from Reviewable.io -->

2022-04-06 15:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-04-06 15:31 UTC, dimakuv commented
Jenkins, test this please

2022-04-08 17:48 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, 2 of 3 files at r3, 6 of 8 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[.ci/lib/stage-clean-check.jenkinsfile, line 36 at r5](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzz3-Jw4lsHe5nVLsY7:-MzzD20_5ksxAT_OO0cU:b-l7hxnr) ([raw file](https://github.com/gramineproject/gramine/blob/5a85d74cbf2cc2aeea0a781202736fb062629f0b/.ci/lib/stage-clean-check.jenkinsfile#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Perhaps looping over CI-Examples would require less maintenance?

Nah, it's not that we add new CI-Examples every month. And as you mentioned, not all CI-Examples are run in CI.

> Interestingly, busybox is missing from this list. Looks like that example doesn't get run in CI.

IIRC, this is on purpose. Busybox is not run because we have a similar Bash example. And we have Busybox in CI-Examples because it is a very handy tool to examine the Gramine virtual environment (browsing through the Gramine FS, threads, processes, etc).
</blockquote></details>

Hmm, but I think it should either be added here or moved to `examples` repo. The current state made more sense before we renamed this directory to "CI-Examples".
Maybe we should add it to the tests with a similar testing script as we have with `bash`?
Whatever we choose, it's for another PR.


<!-- Sent from Reviewable.io -->

2022-04-10 18:32 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-10 18:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-JkYXHADLRX-4A-PKp:-N-JkYXHADLRX-4A-PKq:b-9wi6y5) (no related file):*
@woju: Something's wrong with Jenkins' `Docs` pipeline:
> ERROR: /var/lib/jenkins/workspace/pkg-deb-debian11@script/5595d197f61a2d658ec3f921746af078d44a8b2fbddc73388c4a80d387ad4d15/.ci/pkg-deb-debian11.jenkinsfile not found

See https://leeroy.cs.unc.edu/job/pkg-deb-debian11/1/console.

---


<!-- Sent from Reviewable.io -->

2022-04-10 19:42 UTC, woju commented
Jenkins, test Docs please

2022-04-10 19:43 UTC, woju commented
Jenkins, test pkg-deb-debian11

2022-04-10 19:44 UTC, woju commented
Jenkins, test pkg-deb-debian11 please

2022-04-10 19:50 UTC, mkow commented
Jenkins, retest this please

2022-04-11 07:08 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-MRL1Q3hUikizveiOg:-N-MRL1R342tNDUEzk0E:bavn6n5) (no related file):*
@niedzejkob Somehow, the Rust example failed on Jenkins-18.04-SGX-apps and SGX-sanitizers pipelines. Here is the snippet how they fail:
```
Timeout set to expire in 15 min
[Pipeline] {
[Pipeline] sh
+ cd CI-Examples/rust
+ make -j8
cargo build --profile release
gramine-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dself_exe=target/release/rust-hyper-http-server \
	rust-hyper-http-server.manifest.template rust-hyper-http-server.manifest
    Updating crates.io index
 Downloading crates ...
  Downloaded fnv v1.0.7
  Downloaded futures-core v0.3.21
  Downloaded futures-sink v0.3.21
  Downloaded futures-channel v0.3.21
  Downloaded futures-task v0.3.21
  Downloaded futures-util v0.3.21
  Downloaded http v0.2.6
  Downloaded hashbrown v0.11.2
  Downloaded itoa v1.0.1
  Downloaded lock_api v0.4.7
  Downloaded num_cpus v1.13.1
  Downloaded log v0.4.16
  Downloaded pin-utils v0.1.0
  Downloaded memchr v2.4.1
  Downloaded pin-project-lite v0.2.8
  Downloaded scopeguard v1.1.0
  Downloaded signal-hook-registry v1.4.0
  Downloaded quote v1.0.17
  Downloaded proc-macro2 v1.0.36
  Downloaded once_cell v1.10.0
  Downloaded try-lock v0.2.3
  Downloaded tracing-attributes v0.1.20
  Downloaded unicode-xid v0.2.2
  Downloaded tokio-macros v1.7.0
  Downloaded tracing-core v0.1.24
  Downloaded cfg-if v1.0.0
  Downloaded autocfg v1.1.0
  Downloaded smallvec v1.8.0
  Downloaded indexmap v1.8.1
  Downloaded tower-service v0.3.1
  Downloaded http-body v0.4.4
  Downloaded lazy_static v1.4.0
  Downloaded httparse v1.6.0
  Downloaded parking_lot v0.12.0
  Downloaded bytes v1.1.0
  Downloaded hyper v0.14.18
  Downloaded slab v0.4.6
  Downloaded mio v0.8.2
  Downloaded h2 v0.3.13
  Downloaded socket2 v0.4.4
  Downloaded parking_lot_core v0.9.2
  Downloaded syn v1.0.90
  Downloaded tracing v0.1.32
  Downloaded tokio-util v0.7.1
  Downloaded want v0.3.0
  Downloaded tokio v1.17.0
  Downloaded libc v0.2.121
  Downloaded httpdate v1.0.2
   Compiling libc v0.2.121
   Compiling proc-macro2 v1.0.36
   Compiling autocfg v1.1.0
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.90
   Compiling log v0.4.16
   Compiling parking_lot_core v0.9.2
   Compiling pin-project-lite v0.2.8
   Compiling futures-core v0.3.21
   Compiling memchr v2.4.1
   Compiling bytes v1.1.0
   Compiling smallvec v1.8.0
   Compiling scopeguard v1.1.0
   Compiling futures-task v0.3.21
   Compiling lazy_static v1.4.0
   Compiling itoa v1.0.1
   Compiling fnv v1.0.7
   Compiling futures-util v0.3.21
   Compiling once_cell v1.10.0
   Compiling futures-sink v0.3.21
   Compiling httparse v1.6.0
   Compiling pin-utils v0.1.0
   Compiling hashbrown v0.11.2
   Compiling futures-channel v0.3.21
   Compiling slab v0.4.6
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling httpdate v1.0.2
   Compiling tracing-core v0.1.24
   Compiling http v0.2.6
   Compiling lock_api v0.4.7
   Compiling indexmap v1.8.1
   Compiling want v0.3.0
   Compiling quote v1.0.17
   Compiling signal-hook-registry v1.4.0
   Compiling num_cpus v1.13.1
   Compiling socket2 v0.4.4
   Compiling mio v0.8.2
   Compiling parking_lot v0.12.0
   Compiling http-body v0.4.4
   Compiling tracing-attributes v0.1.20
   Compiling tokio-macros v1.7.0
   Compiling tokio v1.17.0
   Compiling tracing v0.1.32
   Compiling tokio-util v0.7.1
   Compiling h2 v0.3.13
   Compiling hyper v0.14.18
   Compiling rust-hyper-http-server v0.1.0 (/home/jenkins/workspace/graphene-sgx-18.04-apps/CI-Examples/rust)
    Finished release [optimized] target(s) in 40.88s
gramine-sgx-sign \
	--manifest rust-hyper-http-server.manifest \
	--output rust-hyper-http-server.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  8
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
Memory:
    000000000fff6000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffb6000-000000000fff6000 [REG:RW-] (ssa) measured
    000000000ffae000-000000000ffb6000 [TCS:---] (tcs) measured
    000000000ffa6000-000000000ffae000 [REG:RW-] (tls) measured
    000000000ff66000-000000000ffa6000 [REG:RW-] (stack) measured
    000000000ff26000-000000000ff66000 [REG:RW-] (stack) measured
    000000000fee6000-000000000ff26000 [REG:RW-] (stack) measured
    000000000fea6000-000000000fee6000 [REG:RW-] (stack) measured
    000000000fe66000-000000000fea6000 [REG:RW-] (stack) measured
    000000000fe26000-000000000fe66000 [REG:RW-] (stack) measured
    000000000fde6000-000000000fe26000 [REG:RW-] (stack) measured
    000000000fda6000-000000000fde6000 [REG:RW-] (stack) measured
    000000000fd96000-000000000fda6000 [REG:RW-] (sig_stack) measured
    000000000fd86000-000000000fd96000 [REG:RW-] (sig_stack) measured
    000000000fd76000-000000000fd86000 [REG:RW-] (sig_stack) measured
    000000000fd66000-000000000fd76000 [REG:RW-] (sig_stack) measured
    000000000fd56000-000000000fd66000 [REG:RW-] (sig_stack) measured
    000000000fd46000-000000000fd56000 [REG:RW-] (sig_stack) measured
    000000000fd36000-000000000fd46000 [REG:RW-] (sig_stack) measured
    000000000fd26000-000000000fd36000 [REG:RW-] (sig_stack) measured
    000000000f6fa000-000000000f74f000 [REG:R-X] (code) measured
    000000000f94e000-000000000fd26000 [REG:RW-] (data) measured
    0000000000010000-000000000f6fa000 [REG:RWX] (free)
Measurement:
    b2d2d59a5238d59eb48c8b0c5a7e3dfbfa0898cbd39c017ecb83a5cdab8ff704
gramine-sgx-get-token \
	--output rust-hyper-http-server.token --sig rust-hyper-http-server.sig
Attributes:
    mr_enclave:  b2d2d59a5238d59eb48c8b0c5a7e3dfbfa0898cbd39c017ecb83a5cdab8ff704
    mr_signer:   92b77ad58af96e1331aad159b4f627bba5025be88f865eea8fa85c0aff476760
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000006
    attr.xfrm:   0000000000000007
    mask.flags:  ffffffffffffffff
    mask.xfrm:   fffffffffff9ff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     3d292e3576d43d3886f509291b5ab37e...
    exponent:    3
    signature:   a9d39f3183350cdb6df0e13c9df17523...
    date:        2022-04-10
+ ../../Scripts/wait_for_server 60 127.0.0.1 3000
+ make -j8 start-gramine-server
cargo build --profile release
    Finished release [optimized] target(s) in 0.02s
gramine-sgx-sign \
	--manifest rust-hyper-http-server.manifest \
	--output rust-hyper-http-server.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  8
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
Memory:
    000000000fff6000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffb6000-000000000fff6000 [REG:RW-] (ssa) measured
    000000000ffae000-000000000ffb6000 [TCS:---] (tcs) measured
    000000000ffa6000-000000000ffae000 [REG:RW-] (tls) measured
    000000000ff66000-000000000ffa6000 [REG:RW-] (stack) measured
    000000000ff26000-000000000ff66000 [REG:RW-] (stack) measured
    000000000fee6000-000000000ff26000 [REG:RW-] (stack) measured
    000000000fea6000-000000000fee6000 [REG:RW-] (stack) measured
    000000000fe66000-000000000fea6000 [REG:RW-] (stack) measured
    000000000fe26000-000000000fe66000 [REG:RW-] (stack) measured
    000000000fde6000-000000000fe26000 [REG:RW-] (stack) measured
    000000000fda6000-000000000fde6000 [REG:RW-] (stack) measured
    000000000fd96000-000000000fda6000 [REG:RW-] (sig_stack) measured
    000000000fd86000-000000000fd96000 [REG:RW-] (sig_stack) measured
    000000000fd76000-000000000fd86000 [REG:RW-] (sig_stack) measured
    000000 [...]

2022-04-11 14:22 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-JkYXHADLRX-4A-PKp:-N-Nz1BC7zOEzmzoaG2c:b-ollqbu) (no related file):*
> See https://leeroy.cs.unc.edu/job/pkg-deb-debian11/1/console.

This looks like a link to `pkg-deb-debian11` pipeline to me.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N-NzL_mDt_61Q8ABmbs:b-ue54mv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@niedzejkob: I think v1.0 should fail, as it was before epoll rework.
</blockquote></details>

Or any commit before 9d9f4cd9d0f6ef08519c4598d1a34b9625065c74

---
___
*[CI-Examples/rust/src/main.rs, line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Np-BF-LLdrpl0qtZ-:-N-O-2Pt-37SNW2DouM6:b-8ge0u1) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/src/main.rs#L10)):*
The thing is that it probably accepts both versions, so there is no one guideline.

> I like // more, but we've already had this dispute.

Did we? I don't remember that particular one, but we had so many that I might have forgotten :)


<!-- Sent from Reviewable.io -->

2022-04-11 15:23 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-JkYXHADLRX-4A-PKp:-N-OBE1s4mJLxoM5d5FJ:b-cw839e) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> See https://leeroy.cs.unc.edu/job/pkg-deb-debian11/1/console.

This looks like a link to `pkg-deb-debian11` pipeline to me.
</blockquote></details>

Weird, I'm pretty sure that's where the "Docs" pipeline link on GitHub lead me. Not sure if it's possible to check this now, as the status checks for this commit were overridden multiple times by re-triggering Jenkins.

---
___
*[CI-Examples/rust/src/main.rs, line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Np-BF-LLdrpl0qtZ-:-N-OCf7-7rpBIYZ12P-n:b2y41gt) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/src/main.rs#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The thing is that it probably accepts both versions, so there is no one guideline.

> I like // more, but we've already had this dispute.

Did we? I don't remember that particular one, but we had so many that I might have forgotten :)
</blockquote></details>

I think we did have it. My arguments for `//` are that it takes less space for one-liners / in-line comments (2 chars instead of 4) and `//` comments can be nested, contrary to `/**/` (I like to comment out some chunks when debugging with `/**/`, but it doesn't work if that section already contains `/**/` comments).


<!-- Sent from Reviewable.io -->

2022-04-11 17:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-JkYXHADLRX-4A-PKp:-N-Ob6Ge3O6LIQcKsAwQ:b-rcssn4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Weird, I'm pretty sure that's where the "Docs" pipeline link on GitHub lead me. Not sure if it's possible to check this now, as the status checks for this commit were overridden multiple times by re-triggering Jenkins.
</blockquote></details>

Yes, this pipeline was reporting status as if it was "Docs" pipeline. You can see in the console log:

```
Setting status of fc27584747da914f8c904b9f53270f2d43b093eb to FAILURE with url https://leeroy.cs.unc.edu/job/pkg-deb-debian11/1 and message: 'Build finished. '
Using context: Docs
```

It's now fixed.

---


<!-- Sent from Reviewable.io -->

2022-04-11 22:22 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-MRL1Q3hUikizveiOg:-N-Pe5i09f_HGeH9Jooz:b-3atqwu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@niedzejkob Somehow, the Rust example failed on Jenkins-18.04-SGX-apps and SGX-sanitizers pipelines. Here is the snippet how they fail:
```
Timeout set to expire in 15 min
[Pipeline] {
[Pipeline] sh
+ cd CI-Examples/rust
+ make -j8
cargo build --profile release
gramine-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dself_exe=target/release/rust-hyper-http-server \
	rust-hyper-http-server.manifest.template rust-hyper-http-server.manifest
    Updating crates.io index
 Downloading crates ...
  Downloaded fnv v1.0.7
  Downloaded futures-core v0.3.21
  Downloaded futures-sink v0.3.21
  Downloaded futures-channel v0.3.21
  Downloaded futures-task v0.3.21
  Downloaded futures-util v0.3.21
  Downloaded http v0.2.6
  Downloaded hashbrown v0.11.2
  Downloaded itoa v1.0.1
  Downloaded lock_api v0.4.7
  Downloaded num_cpus v1.13.1
  Downloaded log v0.4.16
  Downloaded pin-utils v0.1.0
  Downloaded memchr v2.4.1
  Downloaded pin-project-lite v0.2.8
  Downloaded scopeguard v1.1.0
  Downloaded signal-hook-registry v1.4.0
  Downloaded quote v1.0.17
  Downloaded proc-macro2 v1.0.36
  Downloaded once_cell v1.10.0
  Downloaded try-lock v0.2.3
  Downloaded tracing-attributes v0.1.20
  Downloaded unicode-xid v0.2.2
  Downloaded tokio-macros v1.7.0
  Downloaded tracing-core v0.1.24
  Downloaded cfg-if v1.0.0
  Downloaded autocfg v1.1.0
  Downloaded smallvec v1.8.0
  Downloaded indexmap v1.8.1
  Downloaded tower-service v0.3.1
  Downloaded http-body v0.4.4
  Downloaded lazy_static v1.4.0
  Downloaded httparse v1.6.0
  Downloaded parking_lot v0.12.0
  Downloaded bytes v1.1.0
  Downloaded hyper v0.14.18
  Downloaded slab v0.4.6
  Downloaded mio v0.8.2
  Downloaded h2 v0.3.13
  Downloaded socket2 v0.4.4
  Downloaded parking_lot_core v0.9.2
  Downloaded syn v1.0.90
  Downloaded tracing v0.1.32
  Downloaded tokio-util v0.7.1
  Downloaded want v0.3.0
  Downloaded tokio v1.17.0
  Downloaded libc v0.2.121
  Downloaded httpdate v1.0.2
   Compiling libc v0.2.121
   Compiling proc-macro2 v1.0.36
   Compiling autocfg v1.1.0
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.90
   Compiling log v0.4.16
   Compiling parking_lot_core v0.9.2
   Compiling pin-project-lite v0.2.8
   Compiling futures-core v0.3.21
   Compiling memchr v2.4.1
   Compiling bytes v1.1.0
   Compiling smallvec v1.8.0
   Compiling scopeguard v1.1.0
   Compiling futures-task v0.3.21
   Compiling lazy_static v1.4.0
   Compiling itoa v1.0.1
   Compiling fnv v1.0.7
   Compiling futures-util v0.3.21
   Compiling once_cell v1.10.0
   Compiling futures-sink v0.3.21
   Compiling httparse v1.6.0
   Compiling pin-utils v0.1.0
   Compiling hashbrown v0.11.2
   Compiling futures-channel v0.3.21
   Compiling slab v0.4.6
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling httpdate v1.0.2
   Compiling tracing-core v0.1.24
   Compiling http v0.2.6
   Compiling lock_api v0.4.7
   Compiling indexmap v1.8.1
   Compiling want v0.3.0
   Compiling quote v1.0.17
   Compiling signal-hook-registry v1.4.0
   Compiling num_cpus v1.13.1
   Compiling socket2 v0.4.4
   Compiling mio v0.8.2
   Compiling parking_lot v0.12.0
   Compiling http-body v0.4.4
   Compiling tracing-attributes v0.1.20
   Compiling tokio-macros v1.7.0
   Compiling tokio v1.17.0
   Compiling tracing v0.1.32
   Compiling tokio-util v0.7.1
   Compiling h2 v0.3.13
   Compiling hyper v0.14.18
   Compiling rust-hyper-http-server v0.1.0 (/home/jenkins/workspace/graphene-sgx-18.04-apps/CI-Examples/rust)
    Finished release [optimized] target(s) in 40.88s
gramine-sgx-sign \
	--manifest rust-hyper-http-server.manifest \
	--output rust-hyper-http-server.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  8
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
Memory:
    000000000fff6000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffb6000-000000000fff6000 [REG:RW-] (ssa) measured
    000000000ffae000-000000000ffb6000 [TCS:---] (tcs) measured
    000000000ffa6000-000000000ffae000 [REG:RW-] (tls) measured
    000000000ff66000-000000000ffa6000 [REG:RW-] (stack) measured
    000000000ff26000-000000000ff66000 [REG:RW-] (stack) measured
    000000000fee6000-000000000ff26000 [REG:RW-] (stack) measured
    000000000fea6000-000000000fee6000 [REG:RW-] (stack) measured
    000000000fe66000-000000000fea6000 [REG:RW-] (stack) measured
    000000000fe26000-000000000fe66000 [REG:RW-] (stack) measured
    000000000fde6000-000000000fe26000 [REG:RW-] (stack) measured
    000000000fda6000-000000000fde6000 [REG:RW-] (stack) measured
    000000000fd96000-000000000fda6000 [REG:RW-] (sig_stack) measured
    000000000fd86000-000000000fd96000 [REG:RW-] (sig_stack) measured
    000000000fd76000-000000000fd86000 [REG:RW-] (sig_stack) measured
    000000000fd66000-000000000fd76000 [REG:RW-] (sig_stack) measured
    000000000fd56000-000000000fd66000 [REG:RW-] (sig_stack) measured
    000000000fd46000-000000000fd56000 [REG:RW-] (sig_stack) measured
    000000000fd36000-000000000fd46000 [REG:RW-] (sig_stack) measured
    000000000fd26000-000000000fd36000 [REG:RW-] (sig_stack) measured
    000000000f6fa000-000000000f74f000 [REG:R-X] (code) measured
    000000000f94e000-000000000fd26000 [REG:RW-] (data) measured
    0000000000010000-000000000f6fa000 [REG:RWX] (free)
Measurement:
    b2d2d59a5238d59eb48c8b0c5a7e3dfbfa0898cbd39c017ecb83a5cdab8ff704
gramine-sgx-get-token \
	--output rust-hyper-http-server.token --sig rust-hyper-http-server.sig
Attributes:
    mr_enclave:  b2d2d59a5238d59eb48c8b0c5a7e3dfbfa0898cbd39c017ecb83a5cdab8ff704
    mr_signer:   92b77ad58af96e1331aad159b4f627bba5025be88f865eea8fa85c0aff476760
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000006
    attr.xfrm:   0000000000000007
    mask.flags:  ffffffffffffffff
    mask.xfrm:   fffffffffff9ff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     3d292e3576d43d3886f509291b5ab37e...
    exponent:    3
    signature:   a9d39f3183350cdb6df0e13c9df17523...
    date:        2022-04-10
+ ../../Scripts/wait_for_server 60 127.0.0.1 3000
+ make -j8 start-gramine-server
cargo build --profile release
    Finished release [optimized] target(s) in 0.02s
gramine-sgx-sign \
	--manifest rust-hyper-http-server.manifest \
	--output rust-hyper-http-server.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  8
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
Memory:
    000000000fff6000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffb6000-000000000fff6000 [REG:RW-] (ssa) measured
    000000000ffae000-000000000ffb6000 [TCS:---] (tcs) measured
    000000000ffa6000-000000000ffae000 [REG:RW-] (tls) measured
    000000000ff66000-000000000ffa6000 [REG:RW-] (stack) measured
    000000000ff26000-000000000ff66000 [REG:RW-] (stack) measured
    000000000fee6000-000000000ff26000 [REG:RW-] (stack) measured
    000000000fea6000-000000000fee6000 [REG:RW-] (stack) measured
    000000000fe66000-000000000fea6000 [REG:RW-] (stack) measured
    000000000fe26000-000000000fe66000 [REG:RW-] (stack) measured
    000000000fde6000-000000000fe26000 [REG:RW-] (stack) measured
    000000000fda6000-000000000fde6000 [REG:RW-] (stack) measured
    000000000fd96000-000000000fda6000 [REG:RW-] (sig_stack) measured
    000000000fd86000-000000000fd96000 [REG:RW-] (sig [...]

2022-04-12 00:01 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 9 of 13 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N-Pq4qJ23R_fxpgHpbi:bn4qcgo) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or any commit before 9d9f4cd9d0f6ef08519c4598d1a34b9625065c74
</blockquote></details>

Tried testing on `9d9f4cd^` and for some reason that version of Gramine has trouble finding the dynamic linker, failing with
```
[P1:T1:rust-hyper-http-server] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:rust-hyper-http-server] debug: find_interp: searching for interpreter: /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
[P1:T1:rust-hyper-http-server] error: Error during shim_init() in init_elf_objects (-2)
```
Considering the current mystery failure on CI, I won't bother digging further into this error for now.

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 89 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Ne2ik1VXwXyA21FcX:-N-Q03-i4HxoqJsAsMZz:bmhpd1m) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/.ci/lib/stage-test-direct.jenkinsfile#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why different timeout from all other examples?
Update: ok, probably copy pasted from SGX pipelines. It's bigger then because it might take much longer to spawn whole enclave, than a simple Linux process.
</blockquote></details>

Yup, copy-paste. Fixed.


<!-- Sent from Reviewable.io -->

2022-04-12 00:30 UTC, mkow reviewed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-JkYXHADLRX-4A-PKp:-N-Q7DY84Y-BKUgShzft:b-dj9lkg) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, this pipeline was reporting status as if it was "Docs" pipeline. You can see in the console log:

```
Setting status of fc27584747da914f8c904b9f53270f2d43b093eb to FAILURE with url https://leeroy.cs.unc.edu/job/pkg-deb-debian11/1 and message: 'Build finished. '
Using context: Docs
```

It's now fixed.
</blockquote></details>

Good to know I'm not going crazy :)

---
___
*[CI-Examples/rust/Makefile, line 20 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Njk1QE2HmfW2KIE_x:-N-Q807Q1mGR72k1y45M:bblzrda) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L20)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

It merely shells out to cargo to verify that the binary is up-to-date. Apart from a subprocess being spawned, the computation being done here is similar.

Another option for integrating Cargo into other build-systems is the dep-file it generates at `$(SELF_EXE).d`. This is what I'm using from Meson on another WIP branch, but I don't think the cost-benefit ratio makes the same sense here.

I'm not sure how advanced we want to make the `Makefile`s in our examples. One annoying issue already is that changing the settings such as `DEBUG=1` doesn't trigger an appropriate rebuild. If anything, we should spend the complexity budget on fixing that, and not on golfing down a single `fork+execve`.

I pushed a comment to clarify that we're not rebuilding every time.
</blockquote></details>

I'm fine with the current version, we can't do much better without complicating the makefile significantly or hardcoding source dependencies.
___
*[CI-Examples/rust/Makefile, line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N-Q8UP61AmE02P-9YXb:bkn7fza) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
> You can check other examples (e.g. `redis`) how we express grouped targets

Oh no, these memories are painful...
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 36 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NoYhJ1KQ_3n_QSyJg:-N-QA6JhAWYdM0T8gz7S:b8hdex0) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/rust-hyper-http-server.manifest.template#L36)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Do we have any documentation on that? I think we should link it here.
</blockquote></details>

Hmm, seems to be missing. We should have it documented here: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#number-of-threads. Any volunteer?
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 31 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Q8spP8tOasIi4YlBs:-N-Q8spP8tOasIi4YlBt:b-6as4r) ([raw file](https://github.com/gramineproject/gramine/blob/5c06bbddef4a1af0e3b21b97c2b91f89468747ef/CI-Examples/rust/rust-hyper-http-server.manifest.template#L31)):*
> ```
> # currently relies on the host in an insecure manner. This setting isn't
> # suitable for production deployment, but works well as a stopgap during
> # development while a proper implementation in Gramine is brewing.
> ```

nitpick: rather "being brewed"? although I'm not sure ;)



_Code quote:_
```
is brewing
```


<!-- Sent from Reviewable.io -->

2022-04-12 07:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-MRL1Q3hUikizveiOg:-N-Ri6HGDLmYhSGlgBvM:b-p0zi63) (no related file):*
>It used to be the merge commit, but I thought we switched that off recently. @pwmarcz did we in the end? I see Jenkins reporting "Build started for merge commit."

We switched that off, and it works. If you look at Jenkins pages for the builds (https://leeroy.cs.unc.edu/job/graphene-sgx-18.04-apps/5918/, https://leeroy.cs.unc.edu/job/graphene-sgx-sanitizers/1338/), and logs for these builds, they check out the exact commit from PR (fc27584747da914f8c904b9f53270f2d43b093eb), not the merge commit.

As for the bug, to me it sounds like something occuring randomly, not configuration-specific. I would try to trigger it with Gramine logs enabled.

---


<!-- Sent from Reviewable.io -->

2022-04-12 08:54 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-MRL1Q3hUikizveiOg:-N-RxpzB6TiD1ooY0QpB:b-all1rt) (no related file):*
> As for the bug, to me it sounds like something occuring randomly, not configuration-specific. I would try to trigger it with Gramine logs enabled.

My point was, if it doesnt repo (which it apparently does not), using the same configuration as Jenkins when it triggered the bug is the best bet.

---
___
*[-- commits, line 24 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RqJYA1pJBHRESKfuq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can this be a problem of Jenkins?
</blockquote></details>

The failed pipelines (at least one of them) as in release mode, so most likely not (at least not entirely).
___
*[CI-Examples/rust/Makefile, line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RqgH53U1pvIvXKb27:-N-RySw32dnWXSmB-YMb:buf9txn) ([raw file](https://github.com/gramineproject/gramine/blob/5c06bbddef4a1af0e3b21b97c2b91f89468747ef/CI-Examples/rust/Makefile#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's a strange comment to have. Why would this matter? It only seems confusing.

I would prefer to have the comment here that says that we always build Rust app in release mode because otherwise it's super-slow.
</blockquote></details>

@dimakuv this comment is about target and deps tracking, not compilation mode. The point is that we don't have any dependencies in makefile and let cargo decide if something needs to be rebuilt.


<!-- Sent from Reviewable.io -->

2022-04-12 10:50 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 11 of 13 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @pwmarcz)

___
*[-- commits, line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RZ3ZA1cZvNw7cJc0O):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this a different commit? The original code is added in the very same PR...
I would just squash it to the first one
</blockquote></details>

It seemed like a rationale for the change is necessary, but I'm fine with squashing this when merging. I added a comment in the Makefile itself.
___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N-SEgkJCL8XdkuzSYOO:bekw2oj) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I assume that such update should have no breaking changes? In such case why would developers want to pin very exact version (I mean, it's nice to be able to, but why that's the default)?
</blockquote></details>

They shouldn't have any breaking changes, but you probably still want to run your tests before you ship it. And if it does break, the git history of `Cargo.lock` lets you know what versions were being used before the update that broke things.
___
*[CI-Examples/rust/Makefile, line 23 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NiigD5Jd086j6vCPQ:-N-SFIRx8XkHOTvxKR3p:bupdgln) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done, but does not matter anymore
</blockquote></details>

Ah, I first pushed the change that does that, then switched it back in the commit that removes the `CARGO_TARGET` expansion. Anyway, it's fine now.
___
*[CI-Examples/rust/Makefile, line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RqgH53U1pvIvXKb27:-N-SMq0B5jVNG8-yUoBw:b-wdnbch) ([raw file](https://github.com/gramineproject/gramine/blob/5c06bbddef4a1af0e3b21b97c2b91f89468747ef/CI-Examples/rust/Makefile#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv this comment is about target and deps tracking, not compilation mode. The point is that we don't have any dependencies in makefile and let cargo decide if something needs to be rebuilt.
</blockquote></details>

Expanded to clarify.
___
*[CI-Examples/rust/src/main.rs, line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Np-BF-LLdrpl0qtZ-:-N-SNTGv5tQp4YPA4V61:b-vv107q) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/src/main.rs#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

They also write that you should have comments at most `MIN(80, your_line_limit)` characters long, which I find weird and not really useful.
Anyway, given my lack of rust experience, I'll follow whatever they guide to (at least for now).
</blockquote></details>

Yeah, that part is something I haven't heard of before. The use of `//`, on the other hand, is universally prevalent and easily noticeable, so it's the kind of thing that'd immediately stand out if we decided to go with `/**/` in our code.
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 31 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Q8spP8tOasIi4YlBs:-N-SND9i7-sNkw14fiMC:b-ie3079) ([raw file](https://github.com/gramineproject/gramine/blob/5c06bbddef4a1af0e3b21b97c2b91f89468747ef/CI-Examples/rust/rust-hyper-http-server.manifest.template#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to "being brewed".
</blockquote></details>

"being brewed" feels weird regarding how I've seen the idiom used, changed to "being worked on".


<!-- Sent from Reviewable.io -->

2022-04-12 11:10 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-12 11:11 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @NieDzejkob, and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-04-13 10:09 UTC, pwmarcz commented
Jenkins, retest this please (I'm trying to add timestamps to Jenkins logs, maybe they'll be useful here)

2022-04-13 11:33 UTC, pwmarcz commented
Jenkins, retest this please

2022-04-13 16:48 UTC, pwmarcz commented
Update: After some investigation on Jenkins (we added timestamps to build logs!), it seems that the failure is not a hangup, the job is just pretty slow on some builds.

Slow: https://leeroy.cs.unc.edu/job/graphene-sgx-18.04-apps/5949/console

```
00:10:58.556  + LOOP=1 CONCURRENCY_LIST=1 32 ../common_tools/benchmark-http.sh 127.0.0.1:3000
00:10:58.556  ab -k -n 10000 -c 1 127.0.0.1:3000/random/10K.1.html
00:14:50.049  Completed 1000 requests
00:18:56.590  Completed 2000 requests
00:23:18.133  Completed 3000 requests
00:25:15.223  Cancelling nested steps due to timeout
00:25:15.225  Sending interrupt signal to process
00:25:24.578  Terminated
```

Fast: https://leeroy.cs.unc.edu/job/graphene-sgx-20.04-apps/2455/consoleFull

```
00:13:49.570  + LOOP=1 CONCURRENCY_LIST=1 32 ../common_tools/benchmark-http.sh 127.0.0.1:3000
00:13:49.570  ab -k -n 10000 -c 1 127.0.0.1:3000/random/10K.1.html
00:14:36.261  Completed 1000 requests
00:15:22.981  Completed 2000 requests
00:16:01.837  Completed 3000 requests
00:16:48.541  Completed 4000 requests
00:17:35.319  Completed 5000 requests
00:18:14.070  Completed 6000 requests
00:19:00.802  Completed 7000 requests
00:19:47.509  Completed 8000 requests
00:20:26.264  Completed 9000 requests
00:21:12.971  Completed 10000 requests
00:21:12.971  Finished 10000 requests
00:21:14.349  concurrency=1, throughput=22.73, latency=44.003, failed=0
```

2022-04-13 18:05 UTC, NieDzejkob reviewed
We have traced this to a pathological condition in the malloc implementation caused by Gramine immediately backing all allocations in full. This should now be fixed.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-N-Z4r_J6yegDq8qzxN2:b-eljaey)* status: 12 of 13 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @NieDzejkob, and @pwmarcz)

___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N-UlvoOA_RaD_lQcy4R:b-y1sahw) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But if you keep `Cargo.lock` in git then you keep always using it. Unless you explicitly update `Cargo.lock` at which point you should also run tests.
</blockquote></details>

Yup, that's right.
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 36 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NoYhJ1KQ_3n_QSyJg:-N-Z4lkx6i77SL_qdPH9:b-7koi0g) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/rust-hyper-http-server.manifest.template#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @boryspoplawski @niedzejkob Here we go: https://github.com/gramineproject/gramine/pull/518
</blockquote></details>

Added a link.


<!-- Sent from Reviewable.io -->

2022-04-14 07:19 UTC, dimakuv requested changes
@pwmarcz Thanks for adding the timestamps. I took a look at a couple random Jenkins jobs, looks very cool.

@niedzejkob Could you explain a bit more? I'd be curious to know the details.

> Reviewed 1 of 4 files at r8, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-N-aua2c7W3fM6rQwwXw:bcb5omy)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @NieDzejkob, and @pwmarcz)

___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 17 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-avVlLDN80kkCHazaU:-N-avVlLDN80kkCHazaV:b-lbzskw) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L17)):*
> ```
> #
> # Thus, unless 64M * thread_count fits comfortably in sgx.enclave_size, we need to
> # limit the number of arenas allocated.
> ```

Which made me notice that `sgx.enclave_size` is not defined in this manifest file. Maybe we'll define it here explicitly (it is currently 256MB which is the default)? Otherwise the reader may be confused -- the option is mentioned but not defined...

I won't mind to have a slighter bigger enclave size also -- maybe 512MB. But if you see that this workload definitely fits into 256MB, then feel free to use 256MB.


<!-- Sent from Reviewable.io -->

2022-04-14 09:38 UTC, boryspoplawski requested changes
@dimakuv https://github.com/gramineproject/gramine/issues/342#issuecomment-1014508833

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-N-bOTva5COxW2N8GM_F:b-a3zrog)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N-bPoC3AvgMD362DbHx:bdppb2r) (no related file):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Tried testing on `9d9f4cd^` and for some reason that version of Gramine has trouble finding the dynamic linker, failing with
```
[P1:T1:rust-hyper-http-server] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:rust-hyper-http-server] debug: find_interp: searching for interpreter: /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
[P1:T1:rust-hyper-http-server] error: Error during shim_init() in init_elf_objects (-2)
```
Considering the current mystery failure on CI, I won't bother digging further into this error for now.
</blockquote></details>

Probably different manifest option was used back then (`loeader.preaload` instead of `loader.entrypoint`, I think)

---
___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N-bQ5QU6J34MGOiN6sp:b807dan) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Yup, that's right.
</blockquote></details>

So what's the final argument for keeping Cargo.lock?
___
*[CI-Examples/rust/Makefile, line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N-Rdt_I6ABCOHQRxQXE:b4dlkoc) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> You can check other examples (e.g. `redis`) how we express grouped targets

Oh no, these memories are painful...
</blockquote></details>

Maybe, but we also need to fix it here.
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 13 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-bQkQI1TKE6OidVFqw:-N-bQkQI1TKE6OidVFqx:b3lxcnc) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L13)):*
> ```
> # Due to fundamental SGX limitations, this is not the case when running under
> # Gramine-SGX, and all allocations are immediately fully backed. This doesn't work
> # too well when all threads allocate 64 MiB of virtual memory and cause everything
> ```

Well, the thread itself might be doing just `malloc(1)`, but internal implementation actually issues a 64M mmap.
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 17 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-avVlLDN80kkCHazaU:-N-bQc5t34k18EuBirMo:bmkl7rj) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Which made me notice that `sgx.enclave_size` is not defined in this manifest file. Maybe we'll define it here explicitly (it is currently 256MB which is the default)? Otherwise the reader may be confused -- the option is mentioned but not defined...

I won't mind to have a slighter bigger enclave size also -- maybe 512MB. But if you see that this workload definitely fits into 256MB, then feel free to use 256MB.
</blockquote></details>

I would just add the default to make it clear.


<!-- Sent from Reviewable.io -->

2022-04-14 10:58 UTC, pwmarcz requested changes
> Reviewed 2 of 2 files at r2, 1 of 3 files at r3, 4 of 8 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 2 of 4 files at r8, 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N-bfCAa9ntxvfcNlW_o:b-ngazo2) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So what's the final argument for keeping Cargo.lock?
</blockquote></details>

I'm not familiar with Rust practices specifically, but I believe the general practice for other languages (Python, Ruby, JS) is:

* do not pin dependency versions in a distributed package (e.g. library that others may use), so that users may use the latest ones,
* pin dependencies when you're deploying the project yourself, so that you know exactly what you're deploying (and it's the same thing that you tested).
* when testing the package on CI, I've seen it done both ways: if you test in order to later deploy (or release a binary, I guess), you definitely want the versions pinned; otherwise, you might unpin them so that the build fails immediately when a breaking dependency is released.

Since we're not going to deploy or release this example project, I believe it's more useful NOT to have the lock file here. This way, we don't need to periodically update the lock file, and we'll be immediately notified if for some reason things break with newer dependency versions. (And if we need to know the breaking versions, the build log should contain them.)
___
*[CI-Examples/rust/rust-hyper-http-server.manifest.template, line 10 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-bejcz5dmAoafdfusi:-N-bejd-AC-MLayryTbQ:b-jl7a3q) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L10)):*
> ```
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}"
> 
> # The default malloc settings assume that virtual memory is virtually unlimited.
> ```

This is glibc malloc, right? Can you mention that here? From reading this, it's not obvious which piece of software is the problem, and what reads the `MALLOC_ARENA_MAX` variable (and I believe you can also compile Rust binaries that use musl).


<!-- Sent from Reviewable.io -->

2022-04-19 08:31 UTC, dimakuv reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[CI-Examples/rust/Cargo.lock, line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N0-wSxd03uBW5PJiNEH:br19ns) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not familiar with Rust practices specifically, but I believe the general practice for other languages (Python, Ruby, JS) is:

* do not pin dependency versions in a distributed package (e.g. library that others may use), so that users may use the latest ones,
* pin dependencies when you're deploying the project yourself, so that you know exactly what you're deploying (and it's the same thing that you tested).
* when testing the package on CI, I've seen it done both ways: if you test in order to later deploy (or release a binary, I guess), you definitely want the versions pinned; otherwise, you might unpin them so that the build fails immediately when a breaking dependency is released.

Since we're not going to deploy or release this example project, I believe it's more useful NOT to have the lock file here. This way, we don't need to periodically update the lock file, and we'll be immediately notified if for some reason things break with newer dependency versions. (And if we need to know the breaking versions, the build log should contain them.)
</blockquote></details>

+1 to Pawel. I vote for removing this file.


<!-- Sent from Reviewable.io -->

2022-05-04 15:13 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @pwmarcz)

___
*[`CI-Examples/rust/Cargo.lock` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N-b_Bbd8WUCpO-Q6rZk:b-lylq07) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Pawel. I vote for removing this file.
</blockquote></details>

I suppose one case where this might become problematic is if someone tries using the example from the tarball of a Gramine release. Though the chance an update breaks something is quite low in the first place, and I believe we encourage using the examples from latest master anyway?

I'd also argue that by keeping the versions used in git, there's more tooling to work with the data, but since it's unlikely we'll need it in the first place, I'm not insisting.

Removed the file in latest revision.
___
*[`CI-Examples/rust/Makefile` line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N1E6q4N67VAXFTfOjT6:b-jv1dny) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe, but we also need to fix it here.
</blockquote></details>

Okay, I modified the `helloworld` and `rust` examples to use this Makefile construction. The former is mostly motivated by the fact that I believe we'd rather keep the explanation comment in one place, as opposed to duplicating it everywhere — and I wrote a longer explanation than what was there before.

After we review and merge this change, I'm planning on submitting another PR with analogous changes to all the other examples, for consistency.
___
*[`CI-Examples/rust/rust-hyper-http-server.manifest.template` line 10 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-bejcz5dmAoafdfusi:-N1EEEHu7GzfsJmRRqj8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is glibc malloc, right? Can you mention that here? From reading this, it's not obvious which piece of software is the problem, and what reads the `MALLOC_ARENA_MAX` variable (and I believe you can also compile Rust binaries that use musl).
</blockquote></details>

Done.
___
*[`CI-Examples/rust/rust-hyper-http-server.manifest.template` line 13 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-bQkQI1TKE6OidVFqw:-N1EEEgH6o-A1-26l0Ek:b-60qme) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, the thread itself might be doing just `malloc(1)`, but internal implementation actually issues a 64M mmap.
</blockquote></details>

Good point. I have expanded the comment to clarify this, as well as some other points. The comment then grew to the point that I decided to move it into the documentation.
___
*[`CI-Examples/rust/rust-hyper-http-server.manifest.template` line 17 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-avVlLDN80kkCHazaU:-N1EE9jtDMipiZflqLPk:b-hj2gdn) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would just add the default to make it clear.
</blockquote></details>

Is this still a concern when we're now merely linking to the documentation?


<!-- Sent from Reviewable.io -->

2022-05-04 15:51 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 9 of 17 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N1EkE0l3s33VRSw5rzE:bagk6ny) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Probably different manifest option was used back then (`loeader.preaload` instead of `loader.entrypoint`, I think)
</blockquote></details>

I have managed to run the example on old Gramine with the following changes:
```
diff --git a/CI-Examples/rust/Makefile b/CI-Examples/rust/Makefile
index 2b73e1b4..7d0a19de 100644
--- a/CI-Examples/rust/Makefile
+++ b/CI-Examples/rust/Makefile
@@ -44,6 +44,7 @@ rust-hyper-http-server.manifest.sgx rust-hyper-http-server.sig: sgx_sign
 .INTERMEDIATE: sgx_sign
 sgx_sign: rust-hyper-http-server.manifest build-rust
        gramine-sgx-sign \
+               --key $(HOME)/.config/gramine/enclave-key.pem \
                --manifest $< \
                --output $<.sgx
 
diff --git a/CI-Examples/rust/rust-hyper-http-server.manifest.template b/CI-Examples/rust/rust-hyper-http-server.manifest.template
index 7179749c..5074246f 100644
--- a/CI-Examples/rust/rust-hyper-http-server.manifest.template
+++ b/CI-Examples/rust/rust-hyper-http-server.manifest.template
@@ -1,5 +1,7 @@
 # Rust manifest example
 
+loader.preload = "file:{{ gramine.libos }}"
+
 loader.entrypoint = "file:{{ gramine.libos }}"
 libos.entrypoint = "{{ self_exe }}"
 loader.log_level = "{{ log_level }}"
@@ -13,6 +15,14 @@ loader.env.MALLOC_ARENA_MAX = "1"
 # For easier debugging — not strictly required to run this workload
 loader.env.RUST_BACKTRACE = "full"
 
+fs.mount.lib.type = "chroot"
+fs.mount.lib.path = "/lib"
+fs.mount.lib.uri = "file:{{ gramine.runtimedir() }}"
+
+fs.mount.arch_libdir.type = "chroot"
+fs.mount.arch_libdir.path = "/lib"
+fs.mount.arch_libdir.uri = "file:{{ arch_libdir }}"
+
 fs.mounts = [
   { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
   { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
```

The bug, however, doesn't reproduce. @woju says that the bugs were hard to trigger in the first place, so I'm not sure whether it's worth it to dig through this further. I'd think that the example is valuable regardless, considering the other concerns it uncovered.

---


<!-- Sent from Reviewable.io -->

2022-05-04 16:19 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 7 of 8 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @NieDzejkob, and @woju)

___
*[`CI-Examples/rust/Makefile` line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N1Eqoe382f0kQ92wAIY:btermfn) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay, I modified the `helloworld` and `rust` examples to use this Makefile construction. The former is mostly motivated by the fact that I believe we'd rather keep the explanation comment in one place, as opposed to duplicating it everywhere — and I wrote a longer explanation than what was there before.

After we review and merge this change, I'm planning on submitting another PR with analogous changes to all the other examples, for consistency.
</blockquote></details>

Wow, I didn't know about that. I think this explains why some of these Makefiles were breaking for me and, I needed to run them multiple times (I have a global `MAKEFLAGS=-j8` on my machine).


<!-- Sent from Reviewable.io -->

2022-05-04 16:24 UTC, dimakuv requested changes
> Reviewed 7 of 8 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @NieDzejkob, and @woju)

___
*[`CI-Examples/helloworld/Makefile` line 38 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EpXP50d5WEfask3us:-N1EpXP50d5WEfask3ut:b-5rp6aj) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/CI-Examples/helloworld/Makefile#L38)):*
> ```Makefile
> # that make will consider the source tree up-to-date even if the sgx_sign file doesn't exist,
> # as long as the other dependencies check out. This is in contrast to .PHONY, which would
> # be rebuilt on every invocation of make.
> ```

FYI: This is a great explanation!
___
*[`CI-Examples/rust/Makefile` line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N1EqQM3BejMcEd4nE2N:b-yvsgwn) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay, I modified the `helloworld` and `rust` examples to use this Makefile construction. The former is mostly motivated by the fact that I believe we'd rather keep the explanation comment in one place, as opposed to duplicating it everywhere — and I wrote a longer explanation than what was there before.

After we review and merge this change, I'm planning on submitting another PR with analogous changes to all the other examples, for consistency.
</blockquote></details>

+1, also to our companion repo: https://github.com/gramineproject/examples
___
*[`Documentation/devel/performance.rst` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1ErFo_8h-UIjwOkayi:-N1ErFo_8h-UIjwOkayj:b-il8o65) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L359)):*
> ```reStructuredText
> different under SGX, we do not implement the overcommit mechanism provided
> by the Linux kernel, and fully back each allocation with physical memory
> the moment the memory is requested by the application.
> ```

This sounds weird. Intel SGX v1 simply doesn't support on-demand allocation of pages. I would just simplify to `Intel SGX v1 hardware forces Gramine to fully back each allocation ...`.
___
*[`Documentation/devel/performance.rst` line 371 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Es-KIDhbyPH1_TJL0:-N1Es-KIDhbyPH1_TJL1:bhv6feb) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L371)):*
> ```reStructuredText
> 
> All together, this means that, unless ``64M * (application's thread count)`` fits
> comfortably in sgx.enclave_size, ``malloc`` will be much slower than it should be,
> ```

I would put `sgx.enclave_size` in double-quotes and remove them from `malloc` (since you don't put malloc in double-quotes in other places).
___
*[`Documentation/devel/performance.rst` line 376 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EsO452XyofH_KXJUu:-N1EsO452XyofH_KXJUv:b-xubjgi) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L376)):*
> ```reStructuredText
> 
> One way to solve this is to limit the number of threads that are allowed to have
> their own arena, with the following setting::
> ```

Maybe mention that `1` in this example is the number of threads, and *not* TRUE.
___
*[`CI-Examples/rust/Cargo.lock` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/495#-Mzy5q9m2aMDqMUCl0-e:-N1Ep-170NfCwkik9EP9:b-24aifo) ([raw file](https://github.com/gramineproject/gramine/blob/f80c032fe9e07049c1f0dea0bd2918862af3e2c0/CI-Examples/rust/Cargo.lock#L3)):*
> I suppose one case where this might become problematic is if someone tries using the example from the tarball of a Gramine release

Gramine release tarballs are *not* packed with `CI-Examples`. Gramine tarballs have only the core Gramine itself.
___
*[`CI-Examples/rust/rust-hyper-http-server.manifest.template` line 17 at r11](https://reviewable.io/reviews/gramineproject/gramine/495#-N-avVlLDN80kkCHazaU:-N1Esig0A6Rwt6_i5_vZ:b-wctyi1) ([raw file](https://github.com/gramineproject/gramine/blob/6133308adc404b6fd53d8c975bc95d514c3d5741/CI-Examples/rust/rust-hyper-http-server.manifest.template#L17)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Is this still a concern when we're now merely linking to the documentation?
</blockquote></details>

Not a concern for me. I'm resolving this comment.


<!-- Sent from Reviewable.io -->

2022-05-04 18:11 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @NieDzejkob, and @woju)

___
*[`CI-Examples/blender/Makefile` line 50 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EhqrA9F_TiU9fg7Vk:-N1EhqrA9F_TiU9fg7Vl:b-292upp) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/blender/Makefile#L50)):*
> ```Makefile
> 		$< >$@
> 
> # See the helloworld example for details on this Makefile hack.
> ```

What's the point of this change? The description was as short as the reference to some other place.
Upate: ok, you've added a lengthier explanation there. Still IMO the short version here was nice, maybe just leave it and reference the other (e.g. `For more details please refer to "helloworld" example`)
___
*[`CI-Examples/helloworld/Makefile` line 30 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Ek_tl8SVM7Llwg64g:-N1Ek_tl8SVM7Llwg64h:b-aw0e4n) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L30)):*
> ```Makefile
> # "Rules with Grouped Targets" (`&:`), however make on Ubuntu <= 20.04 doesn't support it.
> #
> # Simply using a normal rule with "two outputs" is equivalent to creating separate rules
> ```

`s/output/target/`
___
*[`CI-Examples/helloworld/Makefile` line 35 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Eke9G4EbZPJOiEnnG:-N1Eke9G4EbZPJOiEnnH:b-8qdq) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L35)):*
> ```Makefile
> #
> # As a workaround, we use a dummy intermediate target, and mark both files as depending on it, to
> # get the dependency graph we want. We mark this dummy target as .INTERMEDIATE, which means
> ```

Do we want this description of `.INTERMEDIATE` here? Not saying no, but this is just a normal feature of Make, we don't explain every each one of them...
___
*[`CI-Examples/redis/Makefile` line 89 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Em9324PrK8fyTlhLL:-N1Em9324PrK8fyTlhLM:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/redis/Makefile#L89)):*
> ```Makefile
> # not where it was built.
> 
> # See the helloworld example for details on this Makefile hack.
> ```

ditto
___
*[`Documentation/devel/performance.rst` line 362 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FF6zv0jLkmj8SxVRU:-N1FF6zv0jLkmj8SxVRV:b-m7s0l6) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L362)):*
> ```reStructuredText
> 
> Moreover, the total amount of memory available to each process needs to be
> declared before the enclave gets started, which makes running out of available
> ```

Hmm, is this document SGX specific? The name doesn't suggest it, but seems it only talks about SGX.
Update: ok, this whole doc seems SGX specific.
___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1FFcST95fbRPaTdzOK:b-srr4ke) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
> ```reStructuredText
> comfortably in sgx.enclave_size, ``malloc`` will be much slower than it should be,
> on some of the threads involved, because each call will now cause multiple
> relatively expensive calls to ``mmap``.
> ```

I would mention that this happens if all threads call `malloc` (which sometimes isn't the case).
___
*[`Documentation/devel/performance.rst` line 381 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFqwA0Wu43rgDuOEh:-N1FFqwA0Wu43rgDuOEi:b1rtvsv) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L381)):*
> ```reStructuredText
> 
> This does have its own performance implications, but the impact is much smaller
> than the pathological behavior described above.
> ```

Please add a reference to `man mallopt(3)` somewhere.
___
*[`Documentation/devel/performance.rst` line 385 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FGEBGDuDpOkibRP9L:-N1FGEBGDuDpOkibRP9M:b-cboz1a) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L385)):*
> ```reStructuredText
> Another solution would be to set ``sgx.enclave_size`` to a much higher value,
> to accomodate each thread creating its own arena. Do keep in mind, however, that
> each process in the enclave will consume its own lot of ``sgx.enclave_size``.
> ```

What is `each process in the enclave`?
___
*[`Documentation/devel/performance.rst` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1ErFo_8h-UIjwOkayi:-N1FEXkf7YMtEqZZ4bXk:b42oqxr) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L359)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sounds weird. Intel SGX v1 simply doesn't support on-demand allocation of pages. I would just simplify to `Intel SGX v1 hardware forces Gramine to fully back each allocation ...`.
</blockquote></details>

+1, this explanation doesn't make sense to me. Also it's not true on `Linux` PAL (where there are no virtual memory constraints).
___
*[`Documentation/devel/performance.rst` line 376 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EsO452XyofH_KXJUu:-N1FFjzU8KOt42lgjqPx:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L376)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe mention that `1` in this example is the number of threads, and *not* TRUE.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-05-04 18:15 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @NieDzejkob, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N1FGpf94m3bGYjYKeIv:byr0gqc) (no related file):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

I have managed to run the example on old Gramine with the following changes:
```
diff --git a/CI-Examples/rust/Makefile b/CI-Examples/rust/Makefile
index 2b73e1b4..7d0a19de 100644
--- a/CI-Examples/rust/Makefile
+++ b/CI-Examples/rust/Makefile
@@ -44,6 +44,7 @@ rust-hyper-http-server.manifest.sgx rust-hyper-http-server.sig: sgx_sign
 .INTERMEDIATE: sgx_sign
 sgx_sign: rust-hyper-http-server.manifest build-rust
        gramine-sgx-sign \
+               --key $(HOME)/.config/gramine/enclave-key.pem \
                --manifest $< \
                --output $<.sgx
 
diff --git a/CI-Examples/rust/rust-hyper-http-server.manifest.template b/CI-Examples/rust/rust-hyper-http-server.manifest.template
index 7179749c..5074246f 100644
--- a/CI-Examples/rust/rust-hyper-http-server.manifest.template
+++ b/CI-Examples/rust/rust-hyper-http-server.manifest.template
@@ -1,5 +1,7 @@
 # Rust manifest example
 
+loader.preload = "file:{{ gramine.libos }}"
+
 loader.entrypoint = "file:{{ gramine.libos }}"
 libos.entrypoint = "{{ self_exe }}"
 loader.log_level = "{{ log_level }}"
@@ -13,6 +15,14 @@ loader.env.MALLOC_ARENA_MAX = "1"
 # For easier debugging — not strictly required to run this workload
 loader.env.RUST_BACKTRACE = "full"
 
+fs.mount.lib.type = "chroot"
+fs.mount.lib.path = "/lib"
+fs.mount.lib.uri = "file:{{ gramine.runtimedir() }}"
+
+fs.mount.arch_libdir.type = "chroot"
+fs.mount.arch_libdir.path = "/lib"
+fs.mount.arch_libdir.uri = "file:{{ arch_libdir }}"
+
 fs.mounts = [
   { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
   { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
```

The bug, however, doesn't reproduce. @woju says that the bugs were hard to trigger in the first place, so I'm not sure whether it's worth it to dig through this further. I'd think that the example is valuable regardless, considering the other concerns it uncovered.
</blockquote></details>

There were not hard to trigger. Just run server in Gramine and while loop with curl on host.

---


<!-- Sent from Reviewable.io -->

2022-05-04 23:23 UTC, mkow requested changes
> Reviewed 7 of 8 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @NieDzejkob, and @woju)

___
*[`-- commits` line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RZ3ZA1cZvNw7cJc0O):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it's not really a change, this PR introduces it. Comment in Makefile is enoguh.

TODO: squash at final rebase
</blockquote></details>

+1, it doesn't make sense to have commit X and commit Y which fixes something in X in one PR. Just merge the fixed thing ;)
___
*[`CI-Examples/helloworld/Makefile` line 35 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Eke9G4EbZPJOiEnnG:-N1GH0ywExIEStTClr1L:b-yddbop) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we want this description of `.INTERMEDIATE` here? Not saying no, but this is just a normal feature of Make, we don't explain every each one of them...
</blockquote></details>

I'd keep it, these special names in Make are quite unintuitive to me w.r.t. their precise semantics (`INTERMEDIATE` vs `SECONDARY` vs `PRECIOUS` etc.) and I always need to google them.
___
*[`CI-Examples/rust/src/main.rs` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-Np-BF-LLdrpl0qtZ-:-N1GJBSs2XpevSJ4RFnU:bew3q08) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/src/main.rs#L10)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Yeah, that part is something I haven't heard of before. The use of `//`, on the other hand, is universally prevalent and easily noticeable, so it's the kind of thing that'd immediately stand out if we decided to go with `/**/` in our code.
</blockquote></details>

+1, I'd also skip that part with comment wrapping, but keep `//`.
___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1GLq64Bt2YlCFNv00f:b-tn09kf) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would mention that this happens if all threads call `malloc` (which sometimes isn't the case).
</blockquote></details>

Isn't this a super-rare corner case? Only in some low-level C code you can find a thread which doesn't do any allocations, I think?
If it's super-rare, then I'd rather omit this for brevity.
___
*[`Documentation/devel/performance.rst` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GKkY51aK9uixKhR_z:-N1GKkY51aK9uixKhRa-:baj6gh0) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L363)):*
> which makes running out of available memory is more of a concern than usual

Something went wrong here.
___
*[`Documentation/devel/performance.rst` line 366 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GL2Hm38TKgcxpkfUL:-N1GL2Hm38TKgcxpkfUM:b-fbeml3) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L366)):*
> ```reStructuredText
> with support for SGXv2's EDMM).
> 
> To put a final nail in the coffin, glibc will retry allocating a per-thread
> ```

This doesn't connect well with the previous paragraph, it seems to be a gap in the story - you didn't mention that when the vmem is depleted glibc doesn't just abort after failing to create an arena, but falls back to `mmap()` for each allocation (my first naive intuition would be that it just aborts or returns `NULL` from `malloc`).
___
*[`Documentation/devel/performance.rst` line 371 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Es-KIDhbyPH1_TJL0:-N1GJecn7mhpuMk3pq4l:bn6y4os) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L371)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would put `sgx.enclave_size` in double-quotes and remove them from `malloc` (since you don't put malloc in double-quotes in other places).
</blockquote></details>

You mean double-backticks, I guess? Anyways, I'd keep `malloc` formatted, it's a function name after all.
___
*[`Documentation/devel/performance.rst` line 389 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GMh3l6lfK6ct-uD4n:-N1GMh3l6lfK6ct-uD4o:b-gzo0ew) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L389)):*
> ```reStructuredText
> better performance than when limiting ``MALLOC_ARENA_MAX``.
> 
> See also: `Issue #342 <https://github.com/gramineproject/gramine/issues/342>`_.
> ```

I know this is related, but do we really want to link to an issue full of console screenshots in our docs? It's an anti-example of how one should report issues :/


<!-- Sent from Reviewable.io -->

2022-05-04 23:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @woju)

___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1GQCmK5iEDLX4QML5b:b-61plin) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this a super-rare corner case? Only in some low-level C code you can find a thread which doesn't do any allocations, I think?
If it's super-rare, then I'd rather omit this for brevity.
</blockquote></details>

It's so super rare, that we have never noticed it outside of rust/tokio code.


<!-- Sent from Reviewable.io -->

2022-05-04 23:36 UTC, boryspoplawski commented
Jenkins, test this please

2022-05-05 06:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @woju)

___
*[`Documentation/devel/performance.rst` line 385 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FGEBGDuDpOkibRP9L:-N1HpiPr-YT2qgpdXoE9:b8hluiw) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L385)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is `each process in the enclave`?
</blockquote></details>

Yeah, intuitively we understand that you mean `each spawned process creates its own enclave and thus consumes its own lot of ...`. Please rephrase to something like this.
___
*[`Documentation/devel/performance.rst` line 371 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Es-KIDhbyPH1_TJL0:-N1HpSB5AOcSA6jV-EPm:bpiowjd) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L371)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You mean double-backticks, I guess? Anyways, I'd keep `malloc` formatted, it's a function name after all.
</blockquote></details>

Yes, I meant double-backticks, sorry.

Malloc is not formatted in other places, but I won't insist.
___
*[`Documentation/devel/performance.rst` line 389 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GMh3l6lfK6ct-uD4n:-N1HpxsZB66wLL205u0k:bpnm65f) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L389)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know this is related, but do we really want to link to an issue full of console screenshots in our docs? It's an anti-example of how one should report issues :/
</blockquote></details>

We can edit the description of the issue to be a perfect example of how to report bugs :)


<!-- Sent from Reviewable.io -->

2022-05-05 13:16 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @NieDzejkob, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N1JM6T28SUen0TrLPlv:-N1JM6T28SUen0TrLPlw:bq9h6ih) (no related file):*
Jenkins failed because `Cargo.lock` is not removed in "clean" stage on CI

---


<!-- Sent from Reviewable.io -->

2022-05-05 22:36 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 12 of 17 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NnT04-KMnOyU5utwR:-N1L7UO7D88ceZGgFqnp:brlq0bz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There were not hard to trigger. Just run server in Gramine and while loop with curl on host.
</blockquote></details>

Okay, that did it. Triggered within a few hundred requests on old Gramine, and worked fine on master. Weirdly enough, actually running a benchmark with `ab` did not suffice. I guess the load can't be too high to have it trigger.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/495#-N1JM6T28SUen0TrLPlv:-N1L8jWWCgyhK9l4r5NW:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Jenkins failed because `Cargo.lock` is not removed in "clean" stage on CI
</blockquote></details>

Done.

---
___
*[`-- commits` line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RZ3ZA1cZvNw7cJc0O):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, it doesn't make sense to have commit X and commit Y which fixes something in X in one PR. Just merge the fixed thing ;)
</blockquote></details>

Yeah, makes sense. Do we want to keep this unresolved as a merge-time reminder?
___
*[`CI-Examples/blender/Makefile` line 50 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EhqrA9F_TiU9fg7Vk:-N1LBN3xDFKVO6qs084k:biudapz) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/blender/Makefile#L50)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this change? The description was as short as the reference to some other place.
Upate: ok, you've added a lengthier explanation there. Still IMO the short version here was nice, maybe just leave it and reference the other (e.g. `For more details please refer to "helloworld" example`)
</blockquote></details>

Hmm, now that I take another look, the old comment does seem like a good concise explanation of what's happening. Yesterday, when I didn't know what's going on, it only confused me, which is why I wrote the longer explanation in the first place. Restored the short descriptions.
___
*[`CI-Examples/helloworld/Makefile` line 30 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Ek_tl8SVM7Llwg64g:-N1LC-k28ppDOmnat4qa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`s/output/target/`
</blockquote></details>

Done.
___
*[`CI-Examples/helloworld/Makefile` line 38 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1EpXP50d5WEfask3us:-N1L95lM20PSg3IWNw33:b-ucfknh) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/CI-Examples/helloworld/Makefile#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This is a great explanation!
</blockquote></details>

Thanks!
___
*[`CI-Examples/redis/Makefile` line 89 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Em9324PrK8fyTlhLL:-N1LC0pIBrEU8eESuHZr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/redis/Makefile#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`CI-Examples/rust/Makefile` line 37 at r7](https://reviewable.io/reviews/gramineproject/gramine/495#-N-NlN3jChkW2crR0Ygh:-N1LC_7A7H7jrPI51ZBJ:bszm633) ([raw file](https://github.com/gramineproject/gramine/blob/fc27584747da914f8c904b9f53270f2d43b093eb/CI-Examples/rust/Makefile#L37)):*
> Wow, I didn't know about that. I think this explains why some of these Makefiles were breaking for me and, I needed to run them multiple times.

Glad that's solved then. Now that you mention this, it'd be good to clarify that this applies to parallel `make` only.
___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1LHPc6-bHEhSm98fOB:bri8bcx) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's so super rare, that we have never noticed it outside of rust/tokio code.
</blockquote></details>

I don't have the data to back this up, but I'd expect that threads that don't call `malloc` at all are rare, and it's just that `malloc` isn't as performance sensitive in other applications, so nobody investigated.
___
*[`Documentation/devel/performance.rst` line 381 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFqwA0Wu43rgDuOEh:-N1LIEpM9h3ZPx7MS-Dj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L381)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a reference to `man mallopt(3)` somewhere.
</blockquote></details>

Done.
___
*[`Documentation/devel/performance.rst` line 385 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FGEBGDuDpOkibRP9L:-N1LIrJ2Bi32Pg-4v6Xj:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L385)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, intuitively we understand that you mean `each spawned process creates its own enclave and thus consumes its own lot of ...`. Please rephrase to something like this.
</blockquote></details>

Done.
___
*[`Documentation/devel/performance.rst` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1ErFo_8h-UIjwOkayi:-N1LDwaK5QIIkRFwhsZ0:bbjideb) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L359)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1, this explanation doesn't make sense to me. Also it's not true on `Linux` PAL (where there are no virtual memory constraints).
</blockquote></details>

Ah, you're right. Had a brain-fart with what exactly is and isn't possible. Rewrote this part.
___
*[`Documentation/devel/performance.rst` line 363 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GKkY51aK9uixKhR_z:-N1LGp5l9i3omKui49wH:bl165iv) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L363)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> which makes running out of available memory is more of a concern than usual

Something went wrong here.
</blockquote></details>

Reworded in new revision.
___
*[`Documentation/devel/performance.rst` line 366 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GL2Hm38TKgcxpkfUL:-N1LGld9CvINQVKmFrMB:bygl2sb) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd5168 [...]

2022-05-05 23:00 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[`-- commits` line 20 at r8](https://reviewable.io/reviews/gramineproject/gramine/495#-N-RZ3ZA1cZvNw7cJc0O):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Yeah, makes sense. Do we want to keep this unresolved as a merge-time reminder?
</blockquote></details>

Yes, I'll resolve once we do it (on the final rebase)
___
*[`CI-Examples/helloworld/Makefile` line 30 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Ek_tl8SVM7Llwg64g:-N1LOjae8g0PFLc_6a4H:b-m1u9ze) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L30)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant `s/output/target/g` ;)
___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1LQTDh7l6voGXe3o4b:b-msdyp0) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
> ```reStructuredText
> 
> When this happens, calls to ``malloc`` won't fail, as the allocator will
> fallback to the main thread's arena, or request a smaller mapping. However,
> ```

I think it just always fallbacks to `mmap` to server this `malloc` request. Thay are usually small, so it juts maps one page, which works.
___
*[`Documentation/devel/performance.rst` line 363 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQuLw2cQvmxXYO7dL:-N1LQuLw2cQvmxXYO7dM:bw2hgzo) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L363)):*
> ```reStructuredText
> When this happens, calls to ``malloc`` won't fail, as the allocator will
> fallback to the main thread's arena, or request a smaller mapping. However,
> glibc will retry allocating the area each time ``malloc`` gets called, perhaps
> ```

`s/area/arena`


<!-- Sent from Reviewable.io -->

2022-05-06 00:13 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1Lh8Si7zePEEmpX-di:b1s2w5e) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

I don't have the data to back this up, but I'd expect that threads that don't call `malloc` at all are rare, and it's just that `malloc` isn't as performance sensitive in other applications, so nobody investigated.
</blockquote></details>

@niedzejkob's explanation seems more plausible to me, although it's still just a speculation ¯\\_(ツ)_/¯
___
*[`Documentation/devel/performance.rst` line 366 at r13](https://reviewable.io/reviews/gramineproject/gramine/495#-N1GL2Hm38TKgcxpkfUL:-N1Lh20PAZrJH0RF84gF:b-dcbopc) ([raw file](https://github.com/gramineproject/gramine/blob/93c8fbd516832fa814535b5d92d17dd806d3050b/Documentation/devel/performance.rst#L366)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Right, added that in.
</blockquote></details>

Much better now, thanks!


<!-- Sent from Reviewable.io -->

2022-05-06 01:34 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[`CI-Examples/helloworld/Makefile` line 30 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1Ek_tl8SVM7Llwg64g:-N1Lmwvv-1uPB1R5G3Sh:b-n2rqlg) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/CI-Examples/helloworld/Makefile#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant `s/output/target/g` ;)
</blockquote></details>

Welp. Fixed that now.
___
*[`Documentation/devel/performance.rst` line 373 at r12](https://reviewable.io/reviews/gramineproject/gramine/495#-N1FFcSS8l47IRdxlwlP:-N1Lzu2b1XTeK6nAQVBq:b-wk9n2m) ([raw file](https://github.com/gramineproject/gramine/blob/4a3ea500daeab9c1a1b70ed8f537ae7ddc306ac6/Documentation/devel/performance.rst#L373)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@niedzejkob's explanation seems more plausible to me, although it's still just a speculation ¯\\_(ツ)_/¯
</blockquote></details>

The new revision mentions that a few paragraphs up.
___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1Ly9BF3xQP9wx7eWxg:bgd1f7j) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it just always fallbacks to `mmap` to server this `malloc` request. Thay are usually small, so it juts maps one page, which works.
</blockquote></details>

Okay, so I decided to write a test case to verify this. The results are very, very weird.

Firstly, turns out glibc wants to align the arena to 64MB, and it feels strongly enough about this that it will unmap the memory it got and try again.

Also, perhaps depending on ASLR since it's nondeterministic, you can trigger the issue with just one thread (beyond the `main` thread, which uses `sbrk`).

Then, when the arena doesn't get allocated, glibc will allocate a full page for each allocation, which wastes most of the memory on fragmentation if the sizes passed to malloc are small.

It's also weird that in this failure mode, allocations take about 40ms. Even knowing about the multiple calls to mmap, this feels suspiciously long. Or perhaps that's just what a 64MB memset takes? O_o

The code I used:

```c
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void * f(void * x) {
    fprintf(stderr, "Allocating\n");
    for(int i = 0; i < 500; i++) {
        //fprintf(stderr, "Allocating on side thread %d\n", (int)x);
        void * buf = malloc(256);
        if (i < 5 || i % 100 == 0) {
            fprintf(stderr, "%d -> %p\n", i, buf);
        }
    }
    fprintf(stderr, "Done\n");
    while(1);
}

int main(void) {
    fprintf(stderr, "Allocating on main thread\n");
    void * buf = malloc(256);
    fprintf(stderr, "Main thread %p\n", buf);
    for (int i = 0; i < 1; i++) {
        pthread_t thread;
        pthread_create(&thread, NULL, f, (void*)i);
    }
    while(1);
}

```
___
*[`Documentation/devel/performance.rst` line 363 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQuLw2cQvmxXYO7dL:-N1Lmah3-WHBLVmuAMin:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L363)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`s/area/arena`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 06:27 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 5 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-06 06:27 UTC, dimakuv commented
Jenkins, test this please

2022-05-06 09:57 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1Nn1c83Gol8CVxyFs7:b-1hcok3) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
> Or perhaps that's just what a 64MB memset takes?

Well, inside enclaves it's possible if it triggered some page faults, which are super-slow to handle here.

Try with `sgx.preheat_enclave = true` and start measuring time only after it was preheated (e.g. in app's `main()`).


<!-- Sent from Reviewable.io -->

2022-05-06 13:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1OUi98E4bmJ_boDTu0:b-292wgc) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

The performance stays constant throughout the allocation loop. Preheating the enclave makes no difference.
</blockquote></details>

Ok, I have no more good guesses.


<!-- Sent from Reviewable.io -->

2022-05-06 13:16 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1OVGPN23w2YOqSNwFN:bm9vg0c) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I have no more good guesses.
</blockquote></details>

Okay, I bumped the allocation count much more, and after about 10k allocations, the addresses jump up to another part of the address space. It speeds up somewhat when that happens.

The comment above `bkeep_mmap_any_in_range` mentions something about a worst-case `O(n)` complexity. This might be what's happening here.

Another issue is how glibc has 99% allocator overhead outside the main thread for low `ulimit -v`. That sounds like something worth reporting upstream...


<!-- Sent from Reviewable.io -->

2022-05-06 16:20 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1P8ogC3ogWwc4L3Q-f:b-okid6c) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
> Firstly, turns out glibc wants to align the arena to 64MB, and it feels strongly enough about this that it will unmap the memory it got and try again.

What it does is it tries to allocate 2x the size of arena and carve out an aligned chunk out of it. If the allocation fails, it tries to mmap just the required size in hope that the address will be aligned "by chance". Since that's rarely the case, it goes on, unallocates that and serves the request directly from mmap.

Generally speaking I think we are going too much into details here. I don't think that many people reading this will be interested in glibc internals. Also I think if someone encounters performance issues with glibc's malloc, they would just try different allocator (e.g. tcmalloc).

This para is still wrong/inaccurate.


<!-- Sent from Reviewable.io -->

2022-05-07 14:16 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 16 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 362 at r14](https://reviewable.io/reviews/gramineproject/gramine/495#-N1LQTDg7-u0VcoH8NsS:-N1Ts0qCCtIbkannibKl:b-cufdne) ([raw file](https://github.com/gramineproject/gramine/blob/dc516ecbedb43c710498e65c5deb90d94d3b28db/Documentation/devel/performance.rst#L362)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Firstly, turns out glibc wants to align the arena to 64MB, and it feels strongly enough about this that it will unmap the memory it got and try again.

What it does is it tries to allocate 2x the size of arena and carve out an aligned chunk out of it. If the allocation fails, it tries to mmap just the required size in hope that the address will be aligned "by chance". Since that's rarely the case, it goes on, unallocates that and serves the request directly from mmap.

Generally speaking I think we are going too much into details here. I don't think that many people reading this will be interested in glibc internals. Also I think if someone encounters performance issues with glibc's malloc, they would just try different allocator (e.g. tcmalloc).

This para is still wrong/inaccurate.
</blockquote></details>

Okay, it should be fine now.


<!-- Sent from Reviewable.io -->

2022-05-07 15:05 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 380 at r16](https://reviewable.io/reviews/gramineproject/gramine/495#-N1U2DPr3ZAGzIUx3qQW:-N1U2DPr3ZAGzIUx3qQX:b-mo5mfp) ([raw file](https://github.com/gramineproject/gramine/blob/201be2e8d28487745aafa741180910de18dba36f/Documentation/devel/performance.rst#L380)):*
> ```reStructuredText
>     # Only the main thread can have its own malloc arena.
>     loader.env.MALLOC_ARENA_MAX = "1"
>     # Only four threads may have their own arena.
> ```

I think arenas are shared between threads i.e. no thread `owns` it.


<!-- Sent from Reviewable.io -->

2022-05-09 06:23 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-09 10:58 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: 16 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @NieDzejkob)

___
*[`Documentation/devel/performance.rst` line 380 at r16](https://reviewable.io/reviews/gramineproject/gramine/495#-N1U2DPr3ZAGzIUx3qQW:-N1cSPEp08vdg5FzKFjw:b-78036y) ([raw file](https://github.com/gramineproject/gramine/blob/201be2e8d28487745aafa741180910de18dba36f/Documentation/devel/performance.rst#L380)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think arenas are shared between threads i.e. no thread `owns` it.
</blockquote></details>

Looks like you're right, in that the malloc implementation does contain code responsible for sharing arenas between threads as a fallback. Revised to make the wording less specific ;)


<!-- Sent from Reviewable.io -->

2022-05-09 11:20 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-09 11:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-09 13:08 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-05-09 13:11 UTC, boryspoplawski approved these changes
> Squashed and rebased.

Not rebased, at least not to the newest master.

> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495#-:-N1cwQGl-TCs9T3g3h4h:bi7upsa)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-09 13:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-09 14:06 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/495)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-09 14:50 UTC, merged