[LibOS] Support renaming encrypted files
gramineproject/gramine pull request #497
Opened 2022-04-05 16:13 UTC by pwmarcz

## Description of the changes 

This adds rename support for encrypted files. The lowest layer is much like the old implementation in #31, but thanks to encrypted files being in LibOS, the issues mentioned there do not appear:

* it's possible to rename a file that is currently open
* it's not possible to rename a file "into" or "out of" encrypted files (since rename works only within a mounted filesystem)
* this shouldn't introduce problems with reference counting

Part of protected files redesign (#371).

Note that this does *not* affect `sgx.protected_files`, which still uses the old subsystem (we'll switch once the new one has all the same features).

## How to test this PR? 

The `rename_unlink` test is enabled for encrypted files. It tests various scenarios for deleting and renaming a file, possibly overwriting another file, keeping an open handle to the now-unlinked file, etc.

I also performed a manual test using the Python example:

```toml
fs.mounts = [
  { type = "encrypted", path = "/enc", uri = "file:enc" },
]
fs.insecure__keys.default = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

```py
from pathlib import Path
import os

Path('enc/a').write_text('Hello world')
os.rename('enc/a', 'enc/b')
print(Path('enc/b').read_text())
```

2022-04-06 09:31 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy8jEF2qqa2rp23nLL):*
Could you add the co-author + signed-off-by `Sankaranarayanan Venkatasubramanian sankaranarayanan.venkatasubramanian@intel.com`? He did https://github.com/gramineproject/gramine/pull/31/ originally.
___
*[CI-Examples/python/python.manifest.template, line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy8doa2stvcI2wO-fm:-Mzy8doa2stvcI2wO-fn:b-33o5f4) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/CI-Examples/python/python.manifest.template#L23)):*
> ```
> 
>   { type = "tmpfs", path = "/tmp" },
>   { type = "encrypted", path = "/enc", uri = "file:enc" },
> ```

Leftover from a debugging session?
___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-Mzy9WIk6VyVK7kuBuiL:b6f55i5) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
> ```C
>     memcpy(pf->encrypted_part_plain.path, new_path, new_path_size);
>     pf->need_writing = true;
> ```

Hm, what about calling `ipf_internal_flush()`? This was in the original PR https://github.com/gramineproject/gramine/pull/31.

Unless I'm missing something, we should do this flush operation. Otherwise another process/thread trying to open this file will still see the old `path` in the PF metadata and will fail (because the `new_path` of the file doesn't correspond to the old `path` in the file's metadata).
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 540 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyB_PL8Q-FGoXBmc_K:-MzyB_PL8Q-FGoXBmc_L:b-oqv8p6) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/shim_fs_encrypted.c#L540)):*
> ```C
>     }
> 
>     ret = DkStreamChangeName(enc->pal_handle, new_uri);
> ```

Is it always guaranteed that we have a `enc->pal_handle`? I thought it was possible to have the `enc` object without the open PAL handle. Couldn't there be a situation when we want to rename an encrypted file that is not actively used?

Compare e.g. with your implementation of a classic `chroot_rename()` -- there you actually open a temporary PAL handle for the rename-operation sake.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 555 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyAfwd1Qyyc_t9L3Ai:-MzyAfwd1Qyyc_t9L3Aj:bm5ne88) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/shim_fs_encrypted.c#L555)):*
> ```C
>     }
> 
>     enc->uri = new_uri_copy;
> ```

What about the old `enc->uri`? You don't free it. Won't you have a memory leak?
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 284 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyB6Ba2IvyZxvh0Ln2:-MzyB6Ba2IvyZxvh0Ln3:b-m54axm) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/chroot/encrypted.c#L284)):*
> ```C
>     ret = chroot_dentry_uri(new, old->inode->type, &new_uri);
>     if (ret < 0)
>         return 0;
> ```

What does this mean? Why do you return success?
___
*[LibOS/shim/test/regression/test_libos.py, line 606 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyC78A5bTu1fdVrsTw:-MzyC78BEMy-ffbVpte6:bwjfttt) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/test/regression/test_libos.py#L606)):*
> ```Python
>         self.assertIn('TEST OK', stdout)
> 
>     @unittest.skip('Protected files do not support renaming yet')
> ```

This comment is confusing now. I understand that here we mean "PFs as implemented in Linux-SGX PAL", and below we mean "PFs (Encrypted Files) as implemented in LibOS". Could you add some explanation to this comment, like `(as implemented in Linux-SGX PAL)`?


<!-- Sent from Reviewable.io -->

2022-04-06 09:42 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyEanD5zx0je1APP8_:-MzyEanD5zx0je1APP8a:b-v4vgzt) (no related file):*
> it's not possible to rename a file "into" or "out of" encrypted files (since rename works only within a mounted filesystem)

Actually, isn't this a general problem that our rename works only within a single mount? The issue is that in a normal OS, a single mount is a huge beast covering the whole `/`, but in Gramine, a single mount is typically a sub-dir like `/etc` or `/tmp` or `<current-working-dir>`. So the unmodified application may try to `rename()` from e.g. `/tmp` into a `/etc`, which would work in a normal OS but will fail in Gramine -- and nothing could be done about it...

---


<!-- Sent from Reviewable.io -->

2022-04-06 11:52 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: 1 of 7 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyEanD5zx0je1APP8_:-MzyXJw_2AXhms4Ew1ZP:b8f5c6i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> it's not possible to rename a file "into" or "out of" encrypted files (since rename works only within a mounted filesystem)

Actually, isn't this a general problem that our rename works only within a single mount? The issue is that in a normal OS, a single mount is a huge beast covering the whole `/`, but in Gramine, a single mount is typically a sub-dir like `/etc` or `/tmp` or `<current-working-dir>`. So the unmodified application may try to `rename()` from e.g. `/tmp` into a `/etc`, which would work in a normal OS but will fail in Gramine -- and nothing could be done about it...
</blockquote></details>

Unfortunately I don't see a non-hacky way of doing such "cross-mount" renames, especially if we want to keep open handles for these files (which we support now), or do something more complicated like renaming directories (which we *don't* support yet).

But I'm not sure if this will be a common use-case: you would need two directories that are read-write for the application, *not* something like `/etc` or `/usr` which will be read-only. `/tmp` is also not a good example, since on normal systems it's usually also a separate mount.

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy8jEF2qqa2rp23nLL):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add the co-author + signed-off-by `Sankaranarayanan Venkatasubramanian sankaranarayanan.venkatasubramanian@intel.com`? He did https://github.com/gramineproject/gramine/pull/31/ originally.
</blockquote></details>

OK. I added a squash commit.
___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-MzyZZN76VUkn_jpAuwd:b-36dz68) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, what about calling `ipf_internal_flush()`? This was in the original PR https://github.com/gramineproject/gramine/pull/31.

Unless I'm missing something, we should do this flush operation. Otherwise another process/thread trying to open this file will still see the old `path` in the PF metadata and will fail (because the `new_path` of the file doesn't correspond to the old `path` in the file's metadata).
</blockquote></details>

Yeah, I think it makes sense to flush here. Read/write operations do not flush, but this one is different because it can render the file unopenable.

Unfortunately there is still a window between updating the header and actually renaming the file, I don't think we can get rid of that. But this is generally the problem with protected files, concurrent accesses are not going to work well.

BTW: this only matters for multiple processes. Multiple threads use the same `pf` object, and take a lock.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 540 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyB_PL8Q-FGoXBmc_K:-MzyerSOAugYeWTF-wW6:bajidib) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/shim_fs_encrypted.c#L540)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it always guaranteed that we have a `enc->pal_handle`? I thought it was possible to have the `enc` object without the open PAL handle. Couldn't there be a situation when we want to rename an encrypted file that is not actively used?

Compare e.g. with your implementation of a classic `chroot_rename()` -- there you actually open a temporary PAL handle for the rename-operation sake.
</blockquote></details>

Yes, `enc` object doesn't have to be open, but all these functions (flush, read, write, rename...) operate on `enc` objects that are open. There are two states:
* open: `enc->pf` and `enc->pal_handle` present, `enc->use_count > 0`,
* closed: both NULL, `enc->use_count == 0`.

The caller (`chroot_encrypted_rename`) ensures the file is open (at least temporarily) by calling `encrypted_file_get/put`. It's done this way because we need to keep exactly 1 handle per file (so, unlike `chroot_rename`, we cannot create a separate one).
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 555 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyAfwd1Qyyc_t9L3Ai:-MzygIs3BVqEUQlQaNDN:b532zhp) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/shim_fs_encrypted.c#L555)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about the old `enc->uri`? You don't free it. Won't you have a memory leak?
</blockquote></details>

Right, I must have lost it in refactoring. Fixed.
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 284 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyB6Ba2IvyZxvh0Ln2:-MzygPUd64SZsCXUeD6z:b-pp879s) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/src/fs/chroot/encrypted.c#L284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this mean? Why do you return success?
</blockquote></details>

Oh, that's a dumb typo... Fixed.
___
*[LibOS/shim/test/regression/test_libos.py, line 606 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyC78A5bTu1fdVrsTw:-MzygcPl1Dg0bY8qJL42:b-ozffqi) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/LibOS/shim/test/regression/test_libos.py#L606)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is confusing now. I understand that here we mean "PFs as implemented in Linux-SGX PAL", and below we mean "PFs (Encrypted Files) as implemented in LibOS". Could you add some explanation to this comment, like `(as implemented in Linux-SGX PAL)`?
</blockquote></details>

I intend for the new feature to be consistently called "encrypted files", but right, there's also the library which is still called "protected files". I updated according to your suggestion.
___
*[CI-Examples/python/python.manifest.template, line 23 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy8doa2stvcI2wO-fm:-MzyZVvV2nMyOLl-lb-e:bgwt35a) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/CI-Examples/python/python.manifest.template#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Leftover from a debugging session?
</blockquote></details>

Yes. Fixed.


<!-- Sent from Reviewable.io -->

2022-04-06 12:03 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/497#-MzyEanD5zx0je1APP8_:-MzyjqvZEmhnxEXjZy8g:b9912gm) (no related file):*
> But I'm not sure if this will be a common use-case: you would need two directories that are read-write for the application, not something like /etc or /usr which will be read-only. /tmp is also not a good example, since on normal systems it's usually also a separate mount.

Yes, I know, my examples suck. But you got my point. Anyway, let's finish this discussion, as you think that such support would be hacky.

---
___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-MzykGAnBx_SehbdUDIl:bqcr3nz) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
> Unfortunately there is still a window between updating the header and actually renaming the file, I don't think we can get rid of that. But this is generally the problem with protected files, concurrent accesses are not going to work well.

Yes, that's true.


<!-- Sent from Reviewable.io -->

2022-04-07 07:34 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners

___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-N-1vDNU4J0v5b6jQfdA:b-ahbzby) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Unfortunately there is still a window between updating the header and actually renaming the file, I don't think we can get rid of that. But this is generally the problem with protected files, concurrent accesses are not going to work well.

Yes, that's true.
</blockquote></details>

I suppose we could fix that by starting a dedicated "file server" enclave, microkernel-style. You could even coordinate the enclaves such that a file being accessed by only one process is owned by that process and can be manipulated directly.

Not sure how much that'd affect performance, though. Seems like only open/close would suffer in the uncontended case? Such an implementation probably wouldn't be too straightforward, though.


<!-- Sent from Reviewable.io -->

2022-04-07 23:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners

___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-N-5OJ3dAoy80X5DNWjU:b-j9bnxc) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

I suppose we could fix that by starting a dedicated "file server" enclave, microkernel-style. You could even coordinate the enclaves such that a file being accessed by only one process is owned by that process and can be manipulated directly.

Not sure how much that'd affect performance, though. Seems like only open/close would suffer in the uncontended case? Such an implementation probably wouldn't be too straightforward, though.
</blockquote></details>

@niedzejkob It's a hard topic, @pwmarcz already tried to tackle this up, but decided to leave it for later. See https://github.com/gramineproject/graphene/pull/2267. He should be able to elaborate more about the technical problems with this.


<!-- Sent from Reviewable.io -->

2022-04-08 10:40 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners

___
*[common/src/protected_files/protected_files.c, line 1271 at r1](https://reviewable.io/reviews/gramineproject/gramine/497#-Mzy9WIk6VyVK7kuBuiK:-N-7j-xzCovLCSSEdEqq:bxno01q) ([raw file](https://github.com/gramineproject/gramine/blob/cd1f1d32f010c98e5e2248d3a743badb8d28db18/common/src/protected_files/protected_files.c#L1271)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@niedzejkob It's a hard topic, @pwmarcz already tried to tackle this up, but decided to leave it for later. See https://github.com/gramineproject/graphene/pull/2267. He should be able to elaborate more about the technical problems with this.
</blockquote></details>

Yes. The attempt linked by @mkow is actually more complicated: I wanted to have something that works locally for the uncontested case. See also https://github.com/oscarlab/graphene/issues/2158 for more background.

But the end result is that I'm really not proud of this: it ended up way too complicated, and is basically abandoned for now.

The "server" architecture you mentioned is done for POSIX locks implementation (fcntl); the main process works as a server and other processes always refer to it. It still needs some improvement (see https://github.com/oscarlab/graphene/issues/2517) but I think this is basically the way to go for many "multi-process" features.

Still, I wouldn't touch this until we have a good use case that we want to enable.


<!-- Sent from Reviewable.io -->

2022-04-08 19:37 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/src/protected_files/protected_files.h, line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/497#-N-9SfFT53ATFM7GKXvi:-N-9SfFT53ATFM7GKXvj:bcck2kg) ([raw file](https://github.com/gramineproject/gramine/blob/ed56556dd4f8e5d0ae1cd2419fe6dd14e966f7a9/common/src/protected_files/protected_files.h#L264)):*
> ```objc
> 
> /*!
>  * \brief Rename a PF
> ```

missing period
___
*[common/src/protected_files/protected_files.h, line 267 at r2](https://reviewable.io/reviews/gramineproject/gramine/497#-N-9SZyDC6A7EVvoPyEp:-N-9SZyDC6A7EVvoPyEq:bsomu2n) ([raw file](https://github.com/gramineproject/gramine/blob/ed56556dd4f8e5d0ae1cd2419fe6dd14e966f7a9/common/src/protected_files/protected_files.h#L267)):*
> ```objc
>  *
>  * \param [in] pf PF context
>  * \param [in] new_path New path
> ```

no space after `\param` + please align (basically, needs an update to our new, more consistent doxycomment style)


<!-- Sent from Reviewable.io -->

2022-04-11 09:31 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/src/protected_files/protected_files.h, line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/497#-N-9SfFT53ATFM7GKXvi:-N-Mx7JFA2nBTC33emsi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ed56556dd4f8e5d0ae1cd2419fe6dd14e966f7a9/common/src/protected_files/protected_files.h#L264)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing period
</blockquote></details>

Done.
___
*[common/src/protected_files/protected_files.h, line 267 at r2](https://reviewable.io/reviews/gramineproject/gramine/497#-N-9SZyDC6A7EVvoPyEp:-N-Mx7xh-0kQUp5VdH24:b-wccgd7) ([raw file](https://github.com/gramineproject/gramine/blob/ed56556dd4f8e5d0ae1cd2419fe6dd14e966f7a9/common/src/protected_files/protected_files.h#L267)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after `\param` + please align (basically, needs an update to our new, more consistent doxycomment style)
</blockquote></details>

I updated this whole comment to our new style (and omitted the `\return PF status` as useless, it's obvious from the return type).


<!-- Sent from Reviewable.io -->

2022-04-11 10:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-11 11:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-11 11:10 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/497)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-11 11:19 UTC, merged

2022-04-12 11:04 UTC, dimakuv commented
@RodgerZhu Only the appended part will be encrypted. Everything shouldn't be re-encrypted. But because Protected Files use Merkle Hash Trees (MHT), some parts of the file will be re-hashed (but *not* re-encrypted).