Support multiple keys in encrypted files
gramineproject/gramine pull request #504
Opened 2022-04-07 15:07 UTC by pwmarcz

## Description of the changes 

This allows mounting encrypted files with `key = "..."` parameter. In addition, the keys can be now updated by application, by writing to `/dev/attestation/keys/<name>`.

This PR also fixes #502 (so that the above update has correct error handling).

## How to test this PR? 

The LibOS regression tests explicitly use `key = "custom"` now. There is also a test that checks if we can set a key, if errors are handled, and if the update persists after a fork.

2022-04-08 00:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/504#-N-5T7vp7l3ekvSkVAUs:-N-5T7vqCE11UT40uvLc:b5r2e6s) (no related file):*
> This PR also fixes #502 (so that the above update has correct error handling).

Could you split this out into a separate PR? We could merge it quickly, as we already agree on the solution and it's not too much code. And the feature implemented in the rest of this PR is non-trivial, so it may take a while to review.

---


<!-- Sent from Reviewable.io -->

2022-04-08 08:55 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
Actually, this commit can be also moved to a separate PR (where `struct shim_mount_params` doesn't have the field `key`).

This would be simpler to review. I'm not insisting though.
___
*[LibOS/shim/test/regression/tests.toml, line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NCgZ7EmQmx1SidGq:-N-7NCgZ7EmQmx1SidGr:bs8zt4c) ([raw file](https://github.com/gramineproject/gramine/blob/03dae25b06441ccc205243737dab841d2c379345/LibOS/shim/test/regression/tests.toml#L53)):*
> ```TOML
>   "host_root_fs",
>   "init_fail",
>   "keys",
> ```

Forgot about musl-based tests?


<!-- Sent from Reviewable.io -->

2022-04-08 09:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/504#-N-5T7vp7l3ekvSkVAUs:-N-7Wftk2bcYUcCnvuuE:b8trxsf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This PR also fixes #502 (so that the above update has correct error handling).

Could you split this out into a separate PR? We could merge it quickly, as we already agree on the solution and it's not too much code. And the feature implemented in the rest of this PR is non-trivial, so it may take a while to review.
</blockquote></details>

Done: https://github.com/gramineproject/gramine/pull/508

I'll remove this commit when the other one is merged.

---
___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, this commit can be also moved to a separate PR (where `struct shim_mount_params` doesn't have the field `key`).

This would be simpler to review. I'm not insisting though.
</blockquote></details>

Done: https://github.com/gramineproject/gramine/pull/508

I'll remove this commit when the other one is merged.
___
*[LibOS/shim/test/regression/tests.toml, line 53 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NCgZ7EmQmx1SidGq:-N-7ZsuMEOD8fTbKSgHZ:b-3d4zvp) ([raw file](https://github.com/gramineproject/gramine/blob/03dae25b06441ccc205243737dab841d2c379345/LibOS/shim/test/regression/tests.toml#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot about musl-based tests?
</blockquote></details>

Yes, I did :) This is fixed now.


<!-- Sent from Reviewable.io -->

2022-04-08 09:54 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done: https://github.com/gramineproject/gramine/pull/508

I'll remove this commit when the other one is merged.
</blockquote></details>

I don't see the change. And why do you move it to the already-existing PR #508? Note that I'm talking about a different commit than Michal meant.


<!-- Sent from Reviewable.io -->

2022-04-08 10:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see the change. And why do you move it to the already-existing PR #508? Note that I'm talking about a different commit than Michal meant.
</blockquote></details>

Oh, sorry, that's a different one.

OK, I'll split this as well :)


<!-- Sent from Reviewable.io -->

2022-04-08 10:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh, sorry, that's a different one.

OK, I'll split this as well :)
</blockquote></details>

Submitted as #510.

I'll rebase this PR after these two PRs are.


<!-- Sent from Reviewable.io -->

2022-04-08 10:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Submitted as #510.

I'll rebase this PR after these two PRs are.
</blockquote></details>

*are merged.


<!-- Sent from Reviewable.io -->

2022-04-11 12:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 0 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/504#-N-5T7vp7l3ekvSkVAUs:-N-N_bxb4WXVv6pucJ39:b-ljdtp8) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done: https://github.com/gramineproject/gramine/pull/508

I'll remove this commit when the other one is merged.
</blockquote></details>

That's merged now, and I removed the commit from this PR.

---
___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/gramineproject/gramine/504#-N-7NTXbAYnYSdGiVai-):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

*are merged.
</blockquote></details>

That PR is merged now, and this commit only adds the `key` parameter now.


<!-- Sent from Reviewable.io -->

2022-04-11 14:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 5 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/504#-N-5T7vp7l3ekvSkVAUs:-N-NwvoaD-2jQFNO0x4F:bdp6ddu) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also update the description of this PR.
</blockquote></details>

Done (I removed the part about fixing #502, since the fix was merged separately).

---
___
*[LibOS/shim/test/regression/manifest.template, line 20 at r3](https://reviewable.io/reviews/gramineproject/gramine/504#-N-NbiWi7PfsitEafC8C:-N-Nxiod76rf8miY-At8:b-atoxqx) ([raw file](https://github.com/gramineproject/gramine/blob/0b9d1bd9846d4f27fe97db9398720e139761c6cd/LibOS/shim/test/regression/manifest.template#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather use something like `some_custom_name` to clearly indicate to the users that these are arbitrary, not some magic names with special handling in Gramine.
</blockquote></details>

Renamed to `my_custom_key`, I hope that looks sufficiently non-built-in.


<!-- Sent from Reviewable.io -->

2022-04-12 07:51 UTC, dimakuv requested changes
> Reviewed 5 of 18 files at r1, 1 of 1 files at r2, 6 of 11 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 67 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RaL8h14kOe4ZUjlHp:-N-RaL8h14kOe4ZUjlHq:b1izri3) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/include/shim_fs_encrypted.h#L67)):*
> ```objc
>  * \brief Retrieve a key.
>  *
>  * Returns a key with a given name, or NULL if it has not been created yet. Note that the even if
> ```

`Note that the even` -> `Note that even`
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 68 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RbJhu3Ux63xO-dIFM:-N-RbJhu3Ux63xO-dIFN:b-e5i4ri) ([raw file](https://github.com/gramineproject/gramine/blob/e567372e1510a2636c4cbd966b9f81033e0f47af/LibOS/shim/include/shim_fs_encrypted.h#L68)):*
> ```objc
>  * `struct shim_encrypted_files_key`).
>  *
>  * This does not pass ownership of `*out_key`: the key objects are still managed by this module.
> ```

Isn't this comment important to keep?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 324 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RcKad6o0Xa_DQp8Vj:-N-RcKad6o0Xa_DQp8Vk:b-lagd3h) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/shim_fs_encrypted.c#L324)):*
> ```C
>         int ret = callback(key, arg);
>         if (ret < 0)
>             return ret;
> ```

You should unlock first.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 667 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rehf4DkCHk1heGa4E:-N-Rehf4DkCHk1heGa4F:b5qgueq) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/shim_fs_encrypted.c#L667)):*
> ```C
> 
>     struct shim_encrypted_files_key* key;
>     int ret = get_or_create_encrypted_files_key(migrated_key->name, &key);
> ```

So instead of using the inside-checkpoint-blob `migrated_key` object, you're creating a new `key` object, add it to the list anew, and copy the contents from `migrated_key`. This is on purpose, right?
___
*[LibOS/shim/src/fs/dev/attestation.c, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rh6Gg29tkeW9UjKdW:-N-Rh6Gg29tkeW9UjKdX:b5vhyn5) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L16)):*
> ```C
>  * correctly synchronize concurrent accesses to the pseudo-files. We expect attestation flows to
>  * be generally single-threaded and therefore do not introduce synchronization here.
>  */
> ```

Maybe add some TODO to remove:
- `g_pf_key_hex`
- `pfkey_load`
- `pfkey_save`
___
*[LibOS/shim/src/fs/dev/attestation.c, line 299 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rg1xz8DaixWxIZv4G:-N-Rg1y-DPqjiR2hEIMn:b4vz34e) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L299)):*
> ```C
> static int key_list_names_callback(struct shim_encrypted_files_key* key, void* arg) {
>     struct key_list_names_data* data = arg;
>     return data->callback(key->name, data->arg);
> ```

Why so complicated? You now have a callback that calls another callback. Can't you just specify `list_encrypted_files_keys(readdir_callback_t callback, ...)` as a function signature and use a single indirection?
___
*[LibOS/shim/src/fs/dev/attestation.c, line 339 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RhPwOAF1_CJOdaHrF:-N-RhPwOAF1_CJOdaHrG:b-g7el06) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L339)):*
> ```C
> 
>     if (size != KEY_HEX_LEN) {
>         log_debug("/dev/attestation/protected_files_key: invalid length");
> ```

That's actually `/dev/attestation/keys/`
___
*[LibOS/shim/src/fs/dev/attestation.c, line 360 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rk0SQ9DzKssS3Su-v:-N-Rk0SQ9DzKssS3Su-w:bc8lc2x) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L360)):*
> ```C
> 
>     if (!strcmp(g_pal_public_state->host_type, "Linux-SGX")) {
>         struct pseudo_node* user_report_data = pseudo_add_str(attestation, "user_report_data", NULL);
> ```

Can we add some `log_debug()` message here? Would be nice to tell something like
```
host is Linux-SGX, adding SGX-specific attestation files: report, quote, etc.
```
___
*[LibOS/shim/test/regression/keys.c, line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Ris2Y5bxoI6H8wAMA:-N-Ris2Y5bxoI6H8wAMB:bqoy2j5) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/keys.c#L18)):*
> ```C
> #include "rw_file.h"
> 
> #define KEY_PATH "/dev/attestation/keys/my_custom_key"
> ```

Can you add a comment to look for this key and its original value in `manifest.template`?
___
*[LibOS/shim/test/regression/keys.c, line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RiaV72mfh9Jdhs2sk:-N-RiaV72mfh9Jdhs2sl:b-z4b53z) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/keys.c#L36)):*
> ```C
> 
>     if (strcmp(key, expected_key)) {
>         errx(1, "%s: wrong key: expected %s, got %s", desc, key, expected_key);
> ```

Reorder `key` and `expected_key` arguments -- your string wants them in different order
___
*[LibOS/shim/test/regression/manifest.template, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RjUAG3yEr5ounfyal:-N-RjUAG3yEr5ounfyam:bj2riut) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/manifest.template#L47)):*
> ```
> ]
> 
> fs.insecure__keys.my_custom_key = "00112233445566778899aabbccddeeff"
> ```

What about we also specify the `default` key, and augment the test above to check it as well?

This way, we'll additionally test two things:
- The linked list of keys
- The checkpoint-restore of even those keys that didn't have the associated file (`/dev/attestation/keys/default`) opened/written to.
___
*[LibOS/shim/test/regression/manifest.template, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rjr0w8jnE-R__rBUj:-N-Rjr0w8jnE-R__rBUk:bhxk7na) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/manifest.template#L47)):*
> ```
> ]
> 
> fs.insecure__keys.my_custom_key = "00112233445566778899aabbccddeeff"
> ```

Maybe also add a comment to `see the keys.c test`?


<!-- Sent from Reviewable.io -->

2022-04-12 08:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 14 of 19 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs_encrypted.h, line 67 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RaL8h14kOe4ZUjlHp:-N-RlYEE7VUHoNSK0ph9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/include/shim_fs_encrypted.h#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Note that the even` -> `Note that even`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 68 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RbJhu3Ux63xO-dIFM:-N-RluJh43Ei2htZMZLy:beep1e7) ([raw file](https://github.com/gramineproject/gramine/blob/e567372e1510a2636c4cbd966b9f81033e0f47af/LibOS/shim/include/shim_fs_encrypted.h#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't this comment important to keep?
</blockquote></details>

Right. Restored.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 324 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RcKad6o0Xa_DQp8Vj:-N-Rm6Sq1p5oFuK8zJuo:blgeayk) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/shim_fs_encrypted.c#L324)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should unlock first.
</blockquote></details>

Ouch. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 667 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rehf4DkCHk1heGa4E:-N-Rn7mN4ruVnK5QehYN:b-98meve) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/shim_fs_encrypted.c#L667)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So instead of using the inside-checkpoint-blob `migrated_key` object, you're creating a new `key` object, add it to the list anew, and copy the contents from `migrated_key`. This is on purpose, right?
</blockquote></details>

Yes, this is on purpose. I think it deserves a comment - I added one.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rh6Gg29tkeW9UjKdW:-N-RnSSe9Jf9PD99Fdce:bovmuaa) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add some TODO to remove:
- `g_pf_key_hex`
- `pfkey_load`
- `pfkey_save`
</blockquote></details>

Isn't it too early for that? The current system ("protected files") is not even deprecated yet.

I agree that these need to be removed eventually, but first we'll need to switch all these APIs to use encrypted keys (e.g. `pfkey_load` will call `key_load` for the `"default"` key... or even the file could become a symlink), and document `type = "encrypted"` to be the right way of using the feature.

Then, I think, will be the right time to start the deprecation period, and add TODOs to delete all of these compatibility shims.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 299 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rg1xz8DaixWxIZv4G:-N-RojZCE9UPJC92ycU6:b-lpfr01) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L299)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why so complicated? You now have a callback that calls another callback. Can't you just specify `list_encrypted_files_keys(readdir_callback_t callback, ...)` as a function signature and use a single indirection?
</blockquote></details>

I regret the boilerplate, but I'd rather keep the module (`shim_fs_encrypted.[ch]`) independent from the rest of LibOS, and using the `readdir_callback_t` type breaks that.

I guess I could say that `list_encrypted_files_keys` actually works on *names*, and declare it to take a callback of form `int (*callback)(const char* name, void* arg)`, which happens to be the same type as `readdir_callback_t`. The types would be even enforced by compiler.

But still, I don't think this would be a good situation, the coupling is essentially still there: if we ever change how `readdir` works, now we also have to either reach into `shim_fs_encrypted.[ch]` and change it as well, or rewrite the code here.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 339 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RhPwOAF1_CJOdaHrF:-N-RrI6ICEfOs6-5wUXX:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L339)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's actually `/dev/attestation/keys/`
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 360 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rk0SQ9DzKssS3Su-v:-N-RrUZa1IddK1fqsaGe:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add some `log_debug()` message here? Would be nice to tell something like
```
host is Linux-SGX, adding SGX-specific attestation files: report, quote, etc.
```
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/keys.c, line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Ris2Y5bxoI6H8wAMA:-N-RsBVXD96s6ubhj7jW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/keys.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment to look for this key and its original value in `manifest.template`?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/keys.c, line 36 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RiaV72mfh9Jdhs2sk:-N-RsFA08jPcbIlOP83P:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/keys.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Reorder `key` and `expected_key` arguments -- your string wants them in different order
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/test/regression/manifest.template, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-RjUAG3yEr5ounfyal:-N-RtyZ06aaXxmGLaZeo:bax2gw6) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/test/regression/manifest.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about we also specify the `default` key, and augment the test above to check it as well?

This way, we'll additionally test two things:
- The linked list of keys
- The checkpoint-restore of even those keys that didn't have the associated file (`/dev/attestation/keys/default`) opened/written to.
</blockquote></details>

OK. Updated.
___
*[LibOS/shim/test/regression/manifest.template, line 47 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rjr0w8jnE-R__rBUj:-N-Ru1KEDsjuax6ZyvMP:b-896fix) ([raw file](https://gith [...]

2022-04-12 11:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/dev/attestation.c, line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rh6Gg29tkeW9UjKdW:-N-SS64HA9PBmFekEDRb:b-gniufx) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L16)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Isn't it too early for that? The current system ("protected files") is not even deprecated yet.

I agree that these need to be removed eventually, but first we'll need to switch all these APIs to use encrypted keys (e.g. `pfkey_load` will call `key_load` for the `"default"` key... or even the file could become a symlink), and document `type = "encrypted"` to be the right way of using the feature.

Then, I think, will be the right time to start the deprecation period, and add TODOs to delete all of these compatibility shims.
</blockquote></details>

OK, hope we won't forget to remove all these things.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 299 at r4](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Rg1xz8DaixWxIZv4G:-N-SSAtR0SP7TrtFl-ef:b-xy91cl) ([raw file](https://github.com/gramineproject/gramine/blob/4ace5ae7b8b37ec43d2b43e8ee4b04583e24687c/LibOS/shim/src/fs/dev/attestation.c#L299)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I regret the boilerplate, but I'd rather keep the module (`shim_fs_encrypted.[ch]`) independent from the rest of LibOS, and using the `readdir_callback_t` type breaks that.

I guess I could say that `list_encrypted_files_keys` actually works on *names*, and declare it to take a callback of form `int (*callback)(const char* name, void* arg)`, which happens to be the same type as `readdir_callback_t`. The types would be even enforced by compiler.

But still, I don't think this would be a good situation, the coupling is essentially still there: if we ever change how `readdir` works, now we also have to either reach into `shim_fs_encrypted.[ch]` and change it as well, or rewrite the code here.
</blockquote></details>

Ok, I see, you want to keep `shim_fs_encrypted.h` completely separated.


<!-- Sent from Reviewable.io -->

2022-04-14 12:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 13 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/504#-N-Y8EWbEluvxPrnOWKK:-N-bxY2FDjX4fKZ7FEg_:b-896fix) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

TODO: as discussed in #520, I'll convert `/dev/attestation/keys/*` files to use binary data instead of hex.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-04-14 12:55 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 18 of 19 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 204 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c61AW2_aXv7AaNYIq:-N-c61AXE5nOJxb95SB1:ba15nt9) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/src/fs/shim_fs_encrypted.c#L204)):*
> ```C
>         log_warning("%s: wrong key length (%zu instead of %zu)", __func__, len,
>                     (size_t)(PF_KEY_SIZE * 2));
>         return -1;
> ```

Why not just `-EINVAL`?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 213 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c63IR4AfGI1auFwJV:-N-c63IR4AfGI1auFwJW:ba15nt9) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/src/fs/shim_fs_encrypted.c#L213)):*
> ```C
>         if (hi < 0 || lo < 0) {
>             log_warning("%s: unexpected character encountered", __func__);
>             return -1;
> ```

Why not just `-EINVAL`?
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 285 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c64cn2m_zYq8DTuR1:-N-c64cn2m_zYq8DTuR2:b-cafcsx) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/src/fs/shim_fs_encrypted.c#L285)):*
> ```C
>         if (ret < 0) {
>             log_error("Cannot parse key 'fs.insecure__keys.%s' as a hex key", name);
>             ret = -EINVAL;
> ```

If you change the error code in the function, you won't need this
___
*[LibOS/shim/test/regression/keys.c, line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7FpxDU36dzXpjwzS:-N-c7Fpy9ozhv3u-T6QV:bnbe9dj) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L39)):*
> ```C
>     0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77};
> 
> static void format_key(char buf[static KEY_STR_SIZE], const pf_key_t* key) {
> ```

What does this mean: `char buf[static KEY_STR_SIZE]`? The first time I see this construct.
___
*[LibOS/shim/test/regression/keys.c, line 82 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7tpT8nGTUQugx9bE:-N-c7tpT8nGTUQugx9bF:bdzs92u) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L82)):*
> ```C
>     expect_key("before writing key", CUSTOM_KEY_PATH, &custom_key);
> 
>     ssize_t n = posix_file_write(CUSTOM_KEY_PATH, (char*)&new_custom_key,
> ```

Can you add a comment that this key-write is invalid because the size is too small?
___
*[LibOS/shim/test/regression/keys.c, line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7rNlDKz_kztFsRko:-N-c7rNlDKz_kztFsRkp:b-npvjj2) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L85)):*
> ```C
>                                  sizeof(new_custom_key) - 1);
>     if (n >= 0 || (n < 0 && errno != EACCES))
>         err(1, "writing invalid key: expected EACCES");
> ```

Can you add an empty line after this?


<!-- Sent from Reviewable.io -->

2022-04-15 09:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 14 of 19 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c-J4e4Jl3io2aTUqK:-N-g_HNJCjkfH1IpA1mR:b-ofdaz5) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs.h#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe `key_name` instead? Would be less ambiguous and still not overly long.
</blockquote></details>

Makes sense. Renamed.

We still want the manifest syntax to be `{ ..., key = "foo" }`, not `{ ..., key_name = "foo" }`, right?
___
*[LibOS/shim/include/shim_fs_encrypted.h, line 93 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c16kC1AFgw30UQ-bY:-N-gXZo_09DEJc5Y0qaJ:bi2vmjc) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs_encrypted.h#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

new? copy-paste error, I guess?
</blockquote></details>

Right, it's current value. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 204 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c61AW2_aXv7AaNYIq:-N-gXidxAUGU2cwzs_pJ:bectrkb) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/src/fs/shim_fs_encrypted.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `-EINVAL`?
</blockquote></details>

This is consistent with other "parse" type functions (there's one in `pseudo`, and some in `api.h`, like `parse_size_str` or `str_to_ulong`) - they don't really return error codes because there's only one type of error possible, so I think it's better to just treat it as success/failure.
___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 673 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c6lLjEdUJMkKGJ35X:-N-gYK24Dez1M-g5zOKM:b-ge9bpt) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/src/fs/shim_fs_encrypted.c#L673)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I assume we can't use `update_encrypted_files_key()` here because the key may not be set, right?
</blockquote></details>

Yeah... I could do `if (is_set) update_encrypted_files_key()`, and it would probably work (if the key is not set in parent, that means the child won't have initialized it either), but that's unobvious and brittle. I feel better about copying data directly.
___
*[LibOS/shim/test/regression/keys.c, line 39 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7FpxDU36dzXpjwzS:-N-gYoMD1SLSmc6BZF0R:b9gugvi) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In C and C++ you can basically put `static` in any place in the code and it's a valid construct, although it has a different meaning in each of them.
https://hamberg.no/erlend/posts/2013-02-18-static-array-indices.html
</blockquote></details>

As I understand, this means that `buf` is a [valid pointer to at least KEY_STR_SIZE elements](https://stackoverflow.com/questions/18362315/static-size-of-array-in-c99).

Sadly, this doesn't make GCC warn on passing a smaller array or NULL (although when caller is in the same file, it will warn anyway). So basically it's for documentation purposes.
___
*[LibOS/shim/test/regression/keys.c, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-cCGgB4QVXzr0HEzpB:-N-gYyS77CYdtEeypKaE:b-vmlnd7) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> 01234567890

:thinking:
</blockquote></details>

Haha :) Good thing it's only a test. Fixed.
___
*[LibOS/shim/test/regression/keys.c, line 53 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-cCoF_4o8vba33vXqL:-N-gZFBfCuYCdqR-0Fbv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L53)):*
> ```C
>     pf_key_t key;
> 
>     ssize_t n = posix_file_read(path, (char*)key, sizeof(key));
> ```

Done.
___
*[LibOS/shim/test/regression/keys.c, line 56 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-cCzNa8gXbv-6LbnqH:-N-gZLLbCJ9zc3xNU_fT:b-9ui3n2) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L56)):*
> ```C
>     if (n < 0)
>         err(1, "%s: error reading %s", desc, path);
>     if (n < (ssize_t)sizeof(key))
> ```

I  agree. Done.
___
*[LibOS/shim/test/regression/keys.c, line 82 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7tpT8nGTUQugx9bE:-N-gZZ1r6fyf1dxEOS_m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment that this key-write is invalid because the size is too small?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/keys.c, line 85 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c7rNlDKz_kztFsRko:-N-gZ_N35Vwso3eJn0F5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add an empty line after this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-18 00:32 UTC, mkow reviewed
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c-J4e4Jl3io2aTUqK:-N-u3VTk8eQ2hb4EngAP:b3icr4h) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs.h#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Makes sense. Renamed.

We still want the manifest syntax to be `{ ..., key = "foo" }`, not `{ ..., key_name = "foo" }`, right?
</blockquote></details>

Good question, I think I actually prefer the latter, but not super strongly.
@boryspoplawski, @dimakuv ^
___
*[LibOS/shim/test/regression/keys.c, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-cCGgB4QVXzr0HEzpB:-N-u4ADv80ktU4D2L7D9:buneo1x) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/test/regression/keys.c#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Haha :) Good thing it's only a test. Fixed.
</blockquote></details>

Yeah, but people sometimes copy code from tests to the main codebase :)


<!-- Sent from Reviewable.io -->

2022-04-18 18:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c-J4e4Jl3io2aTUqK:-N-xqrzrCsPcCt3i-jA9:b6b6w67) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs.h#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good question, I think I actually prefer the latter, but not super strongly.
@boryspoplawski, @dimakuv ^
</blockquote></details>

I did not review the whole PR (should I?) so I need more context - that's an identifier for a key, so that we can pick appropriate key from specific `/dev` entry, right? If that's correct, then I would prefer `key_name` or `key_id` - just `key` sounds like an inline key or a path to a file containing it.


<!-- Sent from Reviewable.io -->

2022-04-19 08:48 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c-J4e4Jl3io2aTUqK:-N0-ze0K6BWoV6OPFyD0:b-4ghb44) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs.h#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not review the whole PR (should I?) so I need more context - that's an identifier for a key, so that we can pick appropriate key from specific `/dev` entry, right? If that's correct, then I would prefer `key_name` or `key_id` - just `key` sounds like an inline key or a path to a file containing it.
</blockquote></details>

I agree with Michal and Borys that `key_name` is less ambigious. So I vote for this rename in the manifest syntax as well. (I don't like `key_id`, because IDs for me are some random numbers, but here we're talking about human-readable human-defined names.)


<!-- Sent from Reviewable.io -->

2022-04-19 11:01 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: 12 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 40 at r6](https://reviewable.io/reviews/gramineproject/gramine/504#-N-c-J4e4Jl3io2aTUqK:-N00Tysu5CU1iA_GqwbM:b-hfgn1z) ([raw file](https://github.com/gramineproject/gramine/blob/7c5550d1a7dd5c5aaf2a3679121de783b8058000/LibOS/shim/include/shim_fs.h#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Michal and Borys that `key_name` is less ambigious. So I vote for this rename in the manifest syntax as well. (I don't like `key_id`, because IDs for me are some random numbers, but here we're talking about human-readable human-defined names.)
</blockquote></details>

OK. I changed the manifest syntax to `key_name` as well.


<!-- Sent from Reviewable.io -->

2022-04-19 13:33 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 7 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-19 13:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 7 files at r8, 1 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-19 14:23 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-19 14:28 UTC, dimakuv approved these changes
> Reviewed 2 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/504)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-19 15:34 UTC, merged