[pkg] Initial `debian/`
gramineproject/gramine pull request #512
Opened 2022-04-08 22:14 UTC by woju

## Description of the changes 

Packaging files for debian

## How to test this PR? 

Install dependencies, then `debuild`.
New job in CI should pass.

2022-04-11 08:15 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 0 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N-Mg4pG-XtGsLeg_oNy:-N-Mg4pH5XT2UyVnuVan:b1iy673) (no related file):*
Is this the automated version of the steps that you do manually for each new Gramine release (on Debian/Ubuntu)?

---


<!-- Sent from Reviewable.io -->

2022-04-11 10:13 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 0 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N-Mg4pG-XtGsLeg_oNy:-N-N4f0g3pF2ZD45-Xk4:b-fvft47) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this the automated version of the steps that you do manually for each new Gramine release (on Debian/Ubuntu)?
</blockquote></details>

Yes, this is part of that. I have this `debian/` directory, which I add to a repo checkout and add an entry to the `changelog`. (Current version doesn't use a repo directly, but extracts a tarball, and also several other parts like headers for sgx drivers, which are not yet packaged, hence the relevant binary packages are commented out in `control` and `rules`).

Also there's repo management missing from this PR, because the packaged need to be uploaded to packages.gramineproject.io and the repo needs to be signed.

---


<!-- Sent from Reviewable.io -->

2022-06-29 03:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 0 of 26 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5hQjKJ19YOUxdXyOup:b-m5e0ig) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please, no `debian/` in top level dir. From the scripts I see we can have `packaging` (or something) and then `debian` there, cant we?
</blockquote></details>

Not really. In the end I'd have to either 1) reassemble the tarball layout manually (which would get ugly, fast), or 2) keep debian directory in parallel *branch* like gpb does (https://wiki.debian.org/PackagingWithGit), which for people who doesn't know is pretty much undiscoverable. Just having `debian/` with `3.0 (native)` format, like all the tooling expects, is the cleanest way.

___


<!-- Sent from Reviewable.io -->

2022-06-29 08:10 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 0 of 26 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5iUdvLCNnhZFSDXY0V:b-5rhmf5) (no related file):*
> reassemble the tarball layout manually (

But you do that already. One more `cp` :)

> keep debian directory in parallel branch

This sounds actually reasonable. Each rebase will be fast forward (since this just would add `debian` dir).

Generally I'm against having a top level dir for one distro, this sounds bad.
cc @dimakuv @mkow wdyt?

___


<!-- Sent from Reviewable.io -->

2022-06-29 08:14 UTC, dimakuv requested changes
> Reviewed 7 of 12 files at r1, 6 of 19 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5iR6-08GuUWiOEM-nD:b-1mo5pn) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> reassemble the tarball layout manually (

But you do that already. One more `cp` :)

> keep debian directory in parallel branch

This sounds actually reasonable. Each rebase will be fast forward (since this just would add `debian` dir).

Generally I'm against having a top level dir for one distro, this sounds bad.
cc @dimakuv @mkow wdyt?
</blockquote></details>

I had the same question as @boryspoplawski , but looks like this is the cleanest way.

Since I'm no expert, I slightly prefer Borys's suggestion for a parallel branch.

___
___
*[`debian/control` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iSwNb2B-YDzkfs3LY:-N5iSwNb2B-YDzkfs3LZ:b-h8a3kd) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L49)):*
> ```
> Package: gramine-ratls-dcap
> Architecture: amd64
> Description: A lightweight guest OS designed to run a single application
> ```

Shouldn't this be different? Like `DCAP-based Remote Attestation TLS (RA-TLS) library for Gramine`
___
*[`debian/control` line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iT5R3CL4UJLf1DJZx:-N5iT5R3CL4UJLf1DJZy:b-fi24kl) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L57)):*
> ```
> Package: gramine-ratls-epid
> Architecture: amd64
> Description: A lightweight guest OS designed to run a single application
> ```

Shouldn't this be different? Like `EPID-based Remote Attestation TLS (RA-TLS) library for Gramine`
___
*[`debian/control` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTKvr7mRh77Kcuxub:-N5iTKvr7mRh77Kcuxuc:b8ybkg8) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L80)):*
> ```
> # gramine-oot
> #
> #Package: gramine-dcap-ratls-dcap
> ```

Why do we need this package? Can't `gramine-ratls-dcap` be a generic one, because it doesn't care about the underlying core Gramine (`gramine` or `gramine-dcap`, it doesn't matter for this package)?
___
*[`debian/control` line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTCG_-TTGeu8uiQn5:-N5iTCG_-TTGeu8uiQn6:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L82)):*
> ```
> #Package: gramine-dcap-ratls-dcap
> #Architecture: amd64
> #Description: A lightweight guest OS designed to run a single application
> ```

ditto
___
*[`debian/control` line 88 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTaq79CsZa_bUCtFA:-N5iTaq79CsZa_bUCtFB:b8ybkg8) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L88)):*
> ```
> ##libc6 (>= 2.28),
> #
> #Package: gramine-dcap-ratls-epid
> ```

Why do we need this package? Can't `gramine-ratls-dcap` be a generic one, because it doesn't care about the underlying core Gramine (`gramine` or `gramine-dcap`, it doesn't matter for this package)?
___
*[`debian/control` line 90 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTDdmAvZ7a-AbYE4w:-N5iTDdmAvZ7a-AbYE4x:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L90)):*
> ```
> #Package: gramine-dcap-ratls-epid
> #Architecture: amd64
> #Description: A lightweight guest OS designed to run a single application
> ```

ditto
___
*[`debian/copyright` line 36 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iUDwP9OwX4XrkAXXO:-N5iUDwP9OwX4XrkAXXP:b-j2p4ab) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/copyright#L36)):*
> ```
> 
> Files:
>  Pal/include/arch/x86_64/Linux/sigcontext.h
> ```

The file paths changed now. Here, the change was `Pal/` -> `pal/`.
___
*[`debian/copyright` line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iULBE2snKeNBllMHM:-N5iULBF8GZzoh7kr17o:boptmj9) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/copyright#L50)):*
> ```
> License: Apache-2.0
> 
> Files: Pal/src/host/Linux-SGX/enclave_xstate.c
> ```

The file paths changed now. Here, the change was `Pal/` -> `pal/` and `Linux-SGX` -> `linux-sgx`.
___
*[`debian/rules` line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iVYMB0yIwYux-M58q:-N5iVYMB0yIwYux-M58r:bgp84qi) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L57)):*
> ```
> #		$(MESONARGS) \
> #		-Dsgx_driver=dcap1.10 \
> #		-Dsgx_driver_include_path=$(DEBIANDIR)/../SGXDataCenterAttestationPrimitives/driver/linux/include \
> ```

How is it supposed to work? I guess you'll need to add cloning this repo in `.ci/debian` Dockerfile?
___
*[`debian/rules` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iVmS5Cek9LUgmRtze:-N5iVmS6ERtl_Lpr2uef:bgp84qi) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L63)):*
> ```
> #		$(MESONARGS) \
> #		-Dsgx_driver=oot \
> #		-Dsgx_driver_include_path=$(DEBIANDIR)/../linux-sgx-driver \
> ```

How is it supposed to work? I guess you'll need to add cloning this repo in `.ci/debian` Dockerfile?
___
*[`debian/rules` line 91 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iW45JC1fLM-5NLCL4:-N5iW45JC1fLM-5NLCL5:b3ks6it) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L91)):*
> ```
> #	mv \
> #		$(DEBIANDIR)/gramine-dcap/usr/lib/x86_64-linux-gnu/libra_tls_verify_dcap* \
> #		$(DEBIANDIR)/gramine-dcap-ratls-dcap/usr/lib/x86_64-linux-gnu
> ```

Technically this is not needed. `gramine-ratls-dcap` package is compatible with `gramine-dcap`. So I suggest to remove these packages `gramine-dcap-ratls-dcap` and `gramine-dcap-ratls-epid`.
___
*[`debian/rules` line 105 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iWJN76rTNXa0WwWGD:-N5iWJN76rTNXa0WwWGE:bkotb5o) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L105)):*
> ```
> 	:
> 
> # TODO run tests
> ```

What kind of tests do you plan to add? As part of this PR or a follow up?
___
*[`debian/source/include-binaries` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iUq3N0_JSNaLGhQeg:-N5iUq3N0_JSNaLGhQeh:b-mea7cp) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/source/include-binaries#L1)):*
> ```
> Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.so
> ```

This will change after rebase to `pal/src/host/linux-sgx/gdb_integration/sgx_gdb.so`

Actually, why does it work now? You already rebased.


<!-- Sent from Reviewable.io -->

2022-06-29 14:33 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5jqsUJ1OmQoygVHTqY:b-apyx0o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I had the same question as @boryspoplawski , but looks like this is the cleanest way.

Since I'm no expert, I slightly prefer Borys's suggestion for a parallel branch.
</blockquote></details>

I'm also against top-level files for each distro, this can generate a lot of garbage in the top-level in long term.
Anyways, @boryspoplawski was playing with it today (packaging without `debian/`), please let us know about the results ;)

___
___
*[`debian/changelog` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5js7LeBzUZsbSLxgWz:-N5js7LeBzUZsbSLxgX-:byej7bh) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/changelog#L49)):*
> ```
>  -- Wojtek Porczyk <woju@invisiblethingslab.com>  Tue, 24 May 2022 20:00:00 +0200
> 
> gramine (1.2~rc1-1) UNRELEASED; urgency=medium
> ```

Why include entries which were never released? How does it differ from merging PRs with `!fixup` commits? ;)


<!-- Sent from Reviewable.io -->

2022-06-29 15:44 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5k6mLO3JBIjpU5Dc8a:bvzl5t1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm also against top-level files for each distro, this can generate a lot of garbage in the top-level in long term.
Anyways, @boryspoplawski was playing with it today (packaging without `debian/`), please let us know about the results ;)
</blockquote></details>

I did not really play with anything, just read how it works / manuals.
These tools require `debian/` in top-level dir, but at the packaging time. For example there is a format with uses two tars: one with source and one with debian specific stuff (that top-level dir + optional patches). We could use that (similarly to how this PR uses meson dist)

___


<!-- Sent from Reviewable.io -->

2022-06-29 15:48 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 21 of 26 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5jKkpm6zV4staQkW3n:b-erx5dy) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not really play with anything, just read how it works / manuals.
These tools require `debian/` in top-level dir, but at the packaging time. For example there is a format with uses two tars: one with source and one with debian specific stuff (that top-level dir + optional patches). We could use that (similarly to how this PR uses meson dist)
</blockquote></details>

The problem with separate branch is, it's hard to test things that need to change in parallel (in `debian/` and outside), like here where I add `Scripts/makedist.sh` outside of `debian/`. This is really meant for packagers that are distinct from upstream, as it's usual for distributions where only a minority of packages the upstream belongs to distro. Here we package ourselves.

___
___
*[`debian/changelog` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5js7LeBzUZsbSLxgWz:-N5k0AEBACBuOB6aCMjP:b-pf20cf) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/changelog#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why include entries which were never released? How does it differ from merging PRs with `!fixup` commits? ;)
</blockquote></details>

They were released (they were built and sent to QA). There's no point in removing them, esp. when something was fixed in the meantime.

Normally (in `3.0 (quilt)`) entries in `debian/changelog` are in addition to usual commits, because you can change something in `debian/` (like, different compile options to meson or fixed dependencies without changing binaries). Then you have the same source tarball (archived from the same tag) and only revision (after `-`) changes. Here in testing we have `3.0 (native)` so we don't have revisions, but still we need at least one changelog entry, because that's where the current version is parsed.
___
*[`debian/control` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iSwNb2B-YDzkfs3LY:-N5k2QD47CG_0sS_IyGl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be different? Like `DCAP-based Remote Attestation TLS (RA-TLS) library for Gramine`
</blockquote></details>

Done.
___
*[`debian/control` line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iT5R3CL4UJLf1DJZx:-N5k2QdLAA3muY6usCwD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be different? Like `EPID-based Remote Attestation TLS (RA-TLS) library for Gramine`
</blockquote></details>

Done.
___
*[`debian/control` line 80 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTKvr7mRh77Kcuxub:-N5k2e_PEP_wnXzgDRCu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this package? Can't `gramine-ratls-dcap` be a generic one, because it doesn't care about the underlying core Gramine (`gramine` or `gramine-dcap`, it doesn't matter for this package)?
</blockquote></details>

Done.
___
*[`debian/control` line 82 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTCG_-TTGeu8uiQn5:-N5k2f7B4TlF-PgFJzSl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`debian/control` line 88 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTaq79CsZa_bUCtFA:-N5jLZ4fAOtvhaueyDBG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this package? Can't `gramine-ratls-dcap` be a generic one, because it doesn't care about the underlying core Gramine (`gramine` or `gramine-dcap`, it doesn't matter for this package)?
</blockquote></details>

Done.
___
*[`debian/control` line 90 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iTDdmAvZ7a-AbYE4w:-N5k2mN5-7tv9GfMutCU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/control#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`debian/copyright` line 36 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iUDwP9OwX4XrkAXXO:-N5jqLak8wu0Wk7gzNmO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/copyright#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The file paths changed now. Here, the change was `Pal/` -> `pal/`.
</blockquote></details>

Done.
___
*[`debian/copyright` line 50 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iULBE2snKeNBllMHM:-N5jqK5T6Bluesrez3WO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/copyright#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The file paths changed now. Here, the change was `Pal/` -> `pal/` and `Linux-SGX` -> `linux-sgx`.
</blockquote></details>

Done.
___
*[`debian/rules` line 57 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iVYMB0yIwYux-M58q:-N5jNHwT0Wy5KrrwE1Ms:b-cepka0) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is it supposed to work? I guess you'll need to add cloning this repo in `.ci/debian` Dockerfile?
</blockquote></details>

This is from other `.orig.` tarballs (https://packages.gramineproject.io/pool/main/g/gramine/, search: `1.2.orig`). Yes, those would have to be downloaded and unpacked. Not now, here I'd like to merge MVP.
___
*[`debian/rules` line 63 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iVmS5Cek9LUgmRtze:-N5jPWIaCDD3bay49Ldc:bnj7hl0) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is it supposed to work? I guess you'll need to add cloning this repo in `.ci/debian` Dockerfile?
</blockquote></details>

same as above
___
*[`debian/rules` line 91 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iW45JC1fLM-5NLCL4:-N5k3W4QBt1KMKwHzxmt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/rules#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></sum [...]

2022-06-30 06:50 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N5nKuD-0ymqlSxAcIRe:b-29yy8b) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The problem with separate branch is, it's hard to test things that need to change in parallel (in `debian/` and outside), like here where I add `Scripts/makedist.sh` outside of `debian/`. This is really meant for packagers that are distinct from upstream, as it's usual for distributions where only a minority of packages the upstream belongs to distro. Here we package ourselves.
</blockquote></details>

For the record: I'm fine with any conclusion on this.

___
___
*[`debian/rules` line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMvVv-1Nf9E86h9pG:-N5nMvVv-1Nf9E86h9pH:b-eqkvje) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L30)):*
> ```
> 		debian/gramine-ratls-* \
> 		debian/gramine-dcap \
> 		debian/gramine-dcap-ratls-* \
> ```

This is a leftover now?
___
*[`debian/rules` line 80 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMjM-1YkWROfsCbXw:-N5nMjM-1YkWROfsCbXx:bszvy5p) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L80)):*
> ```
> 		$(DEBIANDIR)/gramine-ratls-epid/usr/lib/x86_64-linux-gnu \
> 		$(DEBIANDIR)/gramine-dcap-ratls-dcap/usr/lib/x86_64-linux-gnu \
> 		$(DEBIANDIR)/gramine-dcap-ratls-epid/usr/lib/x86_64-linux-gnu
> ```

These two lines are left-overs now?
___
*[`debian/rules` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMln56UlXsrCtNNyG:-N5nMln56UlXsrCtNNyH:bektbb8) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L89)):*
> ```
> 		$(DEBIANDIR)/gramine-ratls-epid/usr/lib/x86_64-linux-gnu
> #	rm -f \
> #		$(DEBIANDIR)/gramine-{dcap,oot}/usr/lib/x86_64-linux-gnu/libra_tls_verify_epid*
> ```

Why do you need this removal?
___
*[`debian/source/include-binaries` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iUq3N0_JSNaLGhQeg:-N5nMT9B5UEOChHXcwgx:b-wxa8q9) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/source/include-binaries#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Hmm, IDK. This was copied verbatim from current packaging, I don't know why it was. It might have been a leftover. Let's see what will happen if I remove it.
</blockquote></details>

Ok. Looks like nothing bad happened, the pkg-deb pipeline succeeded.


<!-- Sent from Reviewable.io -->

2022-06-30 17:56 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`debian/rules` line 30 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMvVv-1Nf9E86h9pG:-N5pigA36QgWUVJUtpT_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a leftover now?
</blockquote></details>

Done.
___
*[`debian/rules` line 80 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMjM-1YkWROfsCbXw:-N5pinz23XuaZ8H5_MYM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two lines are left-overs now?
</blockquote></details>

Done.
___
*[`debian/rules` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/512#-N5nMln56UlXsrCtNNyG:-N5piop06jPFij6v77Bk:b-e6jzwy) ([raw file](https://github.com/gramineproject/gramine/blob/7e87f5130d5b485148d46ccad7044a2d4fc372b3/debian/rules#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this removal?
</blockquote></details>

Because otherwise there would be file conflicts on installation. `gramine-ratls-epid` already contains those files, and after last revison, `gramine-{oot,dcap}` `Recommends: gramine-ratls-epid`.
___
*[`debian/source/include-binaries` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5iUq3N0_JSNaLGhQeg:-N5pk-0M5EhISw71hres:b-3gnbfw) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/source/include-binaries#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok. Looks like nothing bad happened, the pkg-deb pipeline succeeded.
</blockquote></details>

Yes. I've read through log and found nothing about it.


<!-- Sent from Reviewable.io -->

2022-07-01 07:49 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-06 18:41 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6JkyKT8VXd8yJvEudB:bdnt0o4) (no related file):*
> It's the moment/procedure you use to crate debs.

There's not a single one, is as vague as "compilation time". There are builds in CI, there are builds on devs laptop, etc. Those use slightly different configs and setups, depending on exact needs.

> Why? We could have a script doing all of these (like literally 3 lines of bash).

This script would get in your way if you wanted to do something other than CI. Imagine you'd be confined to only `meson setup` stanzas in jenkinsfiles.

> Why do we care? We are the ones preparing the packages, we can do it however we want.

Because we don't want to reinvent packaging tools which are already developed. So we use tools provided by someone else.

> And I don't want to have some repo tooling specific stuff in top level dir.

I don't get it. Everyone who has upstream packages does it this way, only we have to do things in convoluted ways because you want `ls | wc -l` to be one less?

We already have plenty of tool-specific toplevel directory entries. I count at least 6:
```
.clang-format
.dir-locals.el
.github
.pylintrc
pytest.ini
.readthedocs.yaml
```
and this doesn't include `.git{,ignore,modules}`, `meson*` and `Makefile`.

___


<!-- Sent from Reviewable.io -->

2022-07-06 19:11 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6JrkwjC6v7SycIG0nP:b3ztm08) (no related file):*
> There's not a single one, is as vague as "compilation time".

"compilation time" is not vague, just as this isn't. 

> There are builds in CI, there are builds on devs laptop, etc. Those use slightly different configs and setups, depending on exact needs.

What does different config and setup has to do with this? "compilation time" (just as packaging) doesn't mention one arbitrary config or whatever. Your point doesn't make any sense to me here.

> This script would get in your way if you wanted to do something other than CI. Imagine you'd be confined to only meson setup stanzas in jenkinsfiles.

What? If you can do `debuild` then you can also do `sh package.sh`

> Because we don't want to reinvent packaging tools which are already developed.

If they suck of course we want to.

> So we use tools provided by someone else.

What I proposed is all done using exiting debian tooling and well supported by it.

> Everyone who has upstream packages does it this way.

Pardon my English, but this is bullshit. First repo that came to my mind and we use: https://github.com/Mbed-TLS/mbedtls/tree/development I could give 1000 examples of popular project not having it.

> We already have plenty of tool-specific toplevel directory entries. I count at least 6:

- ` .clang-format` - I would move it somewhere else or assume we won't have any other formatting tools.
- `.dir-locals.el` - this one should be deleted (we can add this to docs if needed).
- `.github`, `.gitignore` etc - these are special - we use git with Github. If we move to svn we will delete those.
- `.pylintrc` - same as clang-format
- `pytest.ini` - no idea why we have it here (not together with tests)
- `.readthedocs.yaml` - why this is not in `Documentation`?
- `meson*`, `Makefile` - this is our build system, it's part of the project.

___


<!-- Sent from Reviewable.io -->

2022-07-06 20:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6K6r-Z4RTBJ3tjQRd1:b-59puao) (no related file):*
> First repo that came to my mind and we use: https://github.com/Mbed-TLS/mbedtls/tree/development I could give 1000 examples of popular project not having it.

They're not packaging at all, it's distro who does it for them (https://salsa.debian.org/debian/mbedtls). Same as most of ~50k projects packaged by Debian. But until and unless distros pick us up, we either do packaging ourselves, or not have packages at all.

Actually, I know one repo that has valid case: kernel. There's no `debian/`, it's assembled in makefiles (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/scripts/package/mkdebian?h=v5.18.9), but they have a valid use case: it needs to be encapsulated in buildsystem (not the other way around) because of Kconfig. We aren't remotely related to this usecase.

> What? If you can do debuild then you can also do sh package.sh

The questions is, if you can do `sh package.sh`, can you also do either `debuild` or `dpkg-buildpackage`, whatever you choose? If not, something's broken.

For us, doing `sh package.sh` would be a major impediment, because some people might want to run debuild, some might want to run pdebuild, some might want to run `dpkg-buildpackage`, and some might even like to directly invoke `debian/rules`. Having `package.sh` would stand in the way of people doing valid things, but unforseen by you.

This is also the answer to this question:

> What does different config and setup has to do with this? "compilation time" (just as packaging) doesn't mention one arbitrary config or whatever. Your point doesn't make any sense to me here.

What you propose is not to build packages from the repo, but to make it mandatory to build from an artifact (this intermediary tarball or tarballs). What we can do in my version is to build directly from the repo. We won't do it in CI, but it's very convenient to rebuild package without cleaning if you did just a small change. You'd be very sad if I'd force you to do 10 min rebuild whole project on a small change instead of just `ninja -C build`, which only rebuilds what's needed in nearly no time.

> .clang-format - I would move it somewhere else or assume we won't have any other formatting tools.
> .pylintrc - same as clang-format

Yeah, if only they didn't apply to the whole repo.

> .dir-locals.el - this one should be deleted (we can add this to docs if needed).

Nope, this is per-directory configuration of emacs. You can't have it somewhere else, unless you want to copy it to all subdirectories.

> .github, .gitignore etc - these are special - we use git with Github. If we move to svn we will delete those.

Yeah, if we packaged for something else than Ubuntu, we might have different packaging files. But here we are.

> pytest.ini - no idea why we have it here (not together with tests)
> .readthedocs.yaml - why this is not in Documentation?
 
Same as everything else: there's a tool that expects a config file to be in the root directory of the project. Why pytest.ini is not together with tests: because there are tests is multiple subdirectories.

> meson*, Makefile - this is our build system, it's part of the project.

All of those files are part of our project, you just rarely touch them. What you're proposing is making life significantly harder for people who are doing different things that you do in this project. If it would help you, you can think of `debian/` as the next stage of the build system.

> If they suck of course we want to.

If the only reason is they don't perfectly fit your æsthetics, then I have a different definition of "suck". Those tools have their own set of problems, but what's being discussed here is not one of them. 

___


<!-- Sent from Reviewable.io -->

2022-07-06 21:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6KHhpp48lMxCth0uh7:b-5m838u) (no related file):*
> But until and unless distros pick us up, we either do packaging ourselves, or not have packages at all.

Good we agree on that. Since we do it ourselves, we can do it as we want, so no problem here.

> For us, doing sh package.sh would be a major impediment, because some people might want to run debuild, some might want to run pdebuild, some might want to run dpkg-buildpackage, and some might even like to directly invoke debian/rules. Having package.sh would stand in the way of people doing valid things, but unforseen by you.

Some people might want to use bazel to build Gramine. Am I stopping them from doing so? No. Do we support it? No.
If they want, they can easily inspect our 3 line shell script and adjust it to their needs. I do not need to foresee anything here.

> What you propose is not to build packages from the repo, but to make it mandatory to build from an artifact (this intermediary tarball or tarballs). 

Yes. We need to sacrifice something, because these debian tools are not flexible.

> We won't do it in CI, but it's very convenient to rebuild package without cleaning if you did just a small change.

Is it really the case? Why do you even apply any non-constant changes/patches to packaged binaries?

> You'd be very sad if I'd force you to do 10 min rebuild whole project on a small change instead of just ninja -C build, which only rebuilds what's needed in nearly no time.

Afaik this is ccache at work and it will work correctly, even if you unpack the tarball to a different dir with different names.

> Yeah, if only they didn't apply to the whole repo.

So? They can be passed as arguments to these tools and can very well lie in a different dir.

>>  .dir-locals.el - this one should be deleted (we can add this to docs if needed).
>
> Nope, this is per-directory configuration of emacs. You can't have it somewhere else, unless you want to copy it to all subdirectories.

"delete" means it's moved to "/dev/null" and yes, I can have it there.
By moving to docs I meant inlining it in: https://gramine.readthedocs.io/en/stable/devel/setup.html 

>>  .github, .gitignore etc - these are special - we use git with Github. If we move to svn we will delete those.
>
> Yeah, if we packaged for something else than Ubuntu, we might have different packaging files. But here we are.

That's likely we will. But it's almost certain we won't migrate to svn.

> Same as everything else: there's a tool that expects a config file to be in the root directory of the project. Why pytest.ini is not together with tests: because there are tests is multiple subdirectories.

I don't know about readthedocs, but for pytest that's problem with our setup: we have tests scattered around whole repo instead of one directory.

> All of those files are part of our project

I just exactly said that they are part of our project, not sure what's your point.

>  you just rarely touch them.

I've touched them enough to know what's the deal with them.

> What you're proposing is making life significantly harder for people who are doing different things that you do in this project.

Yeah, doing `cd packaging/debian ; sh package.sh` is **siginifacantly** harder than doing `debuild`

> If it would help you, you can think of debian/ as the next stage of the build system.

And you can stop thinking about packaging and its tooling as the one and only source of truth and "how things should be done".

> If the only reason is they don't perfectly fit your æsthetics, then I have a different definition of "suck". Those tools have their own set of problems, but what's being discussed here is not one of them.

So, you are saying that hardcoding paths in your tools is good thing to do? Let's hardcode the installation prefix then, why not.

___


<!-- Sent from Reviewable.io -->

2022-07-06 22:45 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6KQ3t97FYDNfMduOxf:b-qhbrbv) (no related file):*
> Good we agree on that. Since we do it ourselves, we can do it as we want, so no problem here.

There are people who might want to rebuild the packages independently and use other tools (like `debuild` vs `pdebuild`). So it's not entirely correct to say "we do as we want".

> Some people might want to use bazel to build Gramine. Am I stopping them from doing so? No. Do we support it? No.
> If they want, they can easily inspect our 3 line shell script and adjust it to their needs. I do not need to foresee anything here.

> Yes. We need to sacrifice something, because these debian tools are not flexible.

OK. Next PR will make it impossible to do incremental rebuilds, you'll always have to rebuild from tarball the whole project and gcc also. What for? No-one knows. But we need to make sacrifices! For animal protection reasons it won't be a goat so clearly it will have to be the time of the developers.

> Is it really the case? Why do you even apply any non-constant changes/patches to packaged binaries?

Every time someone changes dependencies, like it happened today: #701. Which reminds me that it will need to be fixed when rebasing on top of that. (Added a note).

> You'd be very sad if I'd force you to do 10 min rebuild whole project on a small change instead of just ninja -C build, which only rebuilds what's needed in nearly no time.
> 
> Afaik this is ccache at work and it will work correctly, even if you unpack the tarball to a different dir with different names.

No, it's mostly dependency tracking.

> So? They can be passed as arguments to these tools and can very well lie in a different dir.

Mostly not, and even if so, why do we need to make other people's life harder?

> By moving to docs I meant inlining it in: https://gramine.readthedocs.io/en/stable/devel/setup.html

This file is a convenience to EMACS users to make it easier to them to adhere to our coding style. So that I don't use EMACS doesn't mean I need to advocate to make EMACS users' life harder (*it's already hard enough^M/me runs*).

What I generally dislike in your attitude is that you dismiss the concerns of other developers and call their tools various names if they can't hide their footprints so that you don't have to see them. I wan't the exact opposite of "we do as we want". Our project is not that special that we need to break everyone's workflow for no real reason.

> That's likely we will. But it's almost certain we won't migrate to svn.

Yes, so what's the problem?

> I don't know about readthedocs, but for pytest that's problem with our setup: we have tests scattered around whole repo instead of one directory.

Yes, you don't know about readthedocs, so let me just put this link here: https://docs.readthedocs.io/en/stable/config-file/v2.html?highlight=root+directory+of+your+project.

For pytest it needs to be in the root of the project so `norecursedirs = ` works. People will run pytest in the root of the project, even if all the tests will be in `tests/`.

> I just exactly said that they are part of our project, not sure what's your point.

I mean all those 12+ files, not only meson* and Makefile.

> I've touched them enough to know what's the deal with them.

> Yeah, doing cd packaging/debian ; sh package.sh is siginifacantly harder than doing debuild

How do you propose to allow people to directly run `debian/rules build`? How do you make `apt-get build-dep ./` work? (the first one will make iteration much faster, the latter will make it possible to get rid of the duplicated dependency list in gsc, which currently makes it necessary to do synced changes like gramineproject/gsc#72).

What you propose doesn't make difference only in a single case, but there are many other use cases which clearly you didn't think through. Closely adhering to guidelines makes it significantly easier to interoperate with various external setups. Otherwise we behave like a "f*cking primadonna"s (https://lore.kernel.org/lkml/CA+55aFyZSr4G2a1X5+EeSgKGtZvzBfBg0D0L39g-DB9TLi+ZEw@mail.gmail.com/), thinking the world revolves around us.
 
> And you can stop thinking about packaging and its tooling as the one and only source of truth and "how things should be done".

It's not the only way how things should be done, but if you'd like gramine to be reproducible (it's one of the long term goals), there aren't good alternatives than to rely on distro's experience and tooling, if only because it's distros who are most experienced in RB.

I can keep packaging outside the repo, no problem for now, but there will be problems like the last-minute mbedtls fcntl snafu just before 1.2, which wasn't detected precisely because we didn't test packaging. That's what I'm really after. There's already a next problem on a radar, if you build rust code on a distro which has rustc supporting edition 2021, then it fails to load on older distros because of some glibc symbol versions. I don't even know how to test for such problems without building actual distro packages.

> So, you are saying that hardcoding paths in your tools is good thing to do? Let's hardcode the installation prefix then, why not.

Installation prefix is different, because there are valid use cases to have different prefixes. But for some paths there aren't any good alternatives to hardcoding. For example, why is `.git/` hardcoded? Git clearly >sucks, >it's not flexible and we need to >reinvent it, >why not. And it's only one tool, not as many as debian has, and expecting them all to be configurable this way is not practical.

(also, in `CI-Examples/` prefix is mostly hardcoded, `$ARCH_LIBDIR` is a lie and doesn't work on non-Debian/Ubuntu systems).

___
___
*[`debian/control` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/512#-N6KeMHe9gbd0mvQ7_bN:-N6KeMHf85k0vjdURqrL:bsd9yya) ([raw file](https://github.com/gramineproject/gramine/blob/21d450e4eb45be61ad6fc46ef2ea06d507a961d5/debian/control#L4)):*
> ```
> Priority: optional
> Maintainer: Wojtek Porczyk <woju@invisiblethingslab.com>
> Build-Depends: debhelper (>= 11),
> ```

Note to self: when rebasing, fix Build-Depends: wrt #701


<!-- Sent from Reviewable.io -->

2022-07-06 22:57 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6KhvVF-UUYhlwZ2v5H:bxx76rw) (no related file):*
> There are people who might want to rebuild the packages independently and use other tools (like debuild vs pdebuild). So it's not entirely correct to say "we do as we want".

Then they are free to do so. They can copy `debian` to top level dir if they really wish so. We are not blocking anything.

> OK. Next PR will make it impossible to do incremental rebuilds, you'll always have to rebuild from tarball the whole project and gcc also.

And such PR won't be merged, so don't bother.

> What for? No-one knows. But we need to make sacrifices! For animal protection reasons it won't be a goat so clearly it will have to be the time of the developers.

You are just wasting my time now. If this discussion reached such level I won't bother responding anymore.

___


<!-- Sent from Reviewable.io -->

2022-07-07 09:40 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6N-oKJ-YfuhguI7MCI:b-3ns0uv) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> There are people who might want to rebuild the packages independently and use other tools (like debuild vs pdebuild). So it's not entirely correct to say "we do as we want".

Then they are free to do so. They can copy `debian` to top level dir if they really wish so. We are not blocking anything.

> OK. Next PR will make it impossible to do incremental rebuilds, you'll always have to rebuild from tarball the whole project and gcc also.

And such PR won't be merged, so don't bother.

> What for? No-one knows. But we need to make sacrifices! For animal protection reasons it won't be a goat so clearly it will have to be the time of the developers.

You are just wasting my time now. If this discussion reached such level I won't bother responding anymore.
</blockquote></details>

@boryspoplawski @woju We got stuck in this discussion. Can we stop it and choose one option? We can simply vote (the reviewers of this PR).

I vote for @woju's approach. We can have a top-level `debian/` directory. I trust Woju's expertise in this question.

@mkow @oshogbo ?

___


<!-- Sent from Reviewable.io -->

2022-07-07 10:17 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-N6N93_VEff8XTdJTCxE:bj1prbu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski @woju We got stuck in this discussion. Can we stop it and choose one option? We can simply vote (the reviewers of this PR).

I vote for @woju's approach. We can have a top-level `debian/` directory. I trust Woju's expertise in this question.

@mkow @oshogbo ?
</blockquote></details>

I'm strongly against `debian/` at top-level, I don't want to have a top-level dir for each distro we'll support. We should have a separate directory, like `packaging` with all this stuff, to make it organized better. And I wasn't convinced by woju's arguments.

___


<!-- Sent from Reviewable.io -->

2022-07-07 20:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`debian/control` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/512#-N6KeMHe9gbd0mvQ7_bN:-N6PF0Wo-ldFvbv7VTKM:bb68di3) ([raw file](https://github.com/gramineproject/gramine/blob/21d450e4eb45be61ad6fc46ef2ea06d507a961d5/debian/control#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Note to self: when rebasing, fix Build-Depends: wrt #701
</blockquote></details>

#735


<!-- Sent from Reviewable.io -->

2022-08-01 16:45 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`debian/control` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/512#-N6KeMHe9gbd0mvQ7_bN:-N8PI6td-fBIo8wzmxtR:bb68dnd) ([raw file](https://github.com/gramineproject/gramine/blob/21d450e4eb45be61ad6fc46ef2ea06d507a961d5/debian/control#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

#735
</blockquote></details>

#799


<!-- Sent from Reviewable.io -->

2022-09-24 15:44 UTC, meithecatte reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-NCk2neS9cxjM755Lrpp:b-9gpgym) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm strongly against `debian/` at top-level, I don't want to have a top-level dir for each distro we'll support. We should have a separate directory, like `packaging` with all this stuff, to make it organized better. And I wasn't convinced by woju's arguments.
</blockquote></details>

For what it's worth, I agree with @woju. He has enough experience with the tooling around this to understand the cost of trying to hide `debian/` inside a subdirectory, and he's the one who'll have to bear the cost of this decision. For most of us, it's just a question of aesthetics. And frankly, hiding `debian/` in a subdirectory is not an elegant solution when you need to copy it back out to the top-level every time you want to use it.

Realistically, we won't ever support enough distros for top-level directories like `debian/` to be a problem. I'd estimate that this count will be 2 in the long run — it's overwhelmingly likely that if we get funding to support a specific distribution, it'll be either based on apt or rpm.

___


<!-- Sent from Reviewable.io -->

2022-10-13 08:01 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @woju)

___
*[`debian/control` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/512#-N6KeMHe9gbd0mvQ7_bN:-NEFM7Cu-PUGpoKXfP48:b-gacl7p) ([raw file](https://github.com/gramineproject/gramine/blob/21d450e4eb45be61ad6fc46ef2ea06d507a961d5/debian/control#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

#799
</blockquote></details>

@woju You're blocking here. Is this still relevant? Looks like you updated the sources to reflect these updates.


<!-- Sent from Reviewable.io -->

2022-10-13 08:51 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`debian/control` line 4 at r5](https://reviewable.io/reviews/gramineproject/gramine/512#-N6KeMHe9gbd0mvQ7_bN:-NEFXLPr7stPY3JPpbJY:b-elxzeq) ([raw file](https://github.com/gramineproject/gramine/blob/21d450e4eb45be61ad6fc46ef2ea06d507a961d5/debian/control#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju You're blocking here. Is this still relevant? Looks like you updated the sources to reflect these updates.
</blockquote></details>

Yes, it's done. Thanks.


<!-- Sent from Reviewable.io -->

2022-10-13 09:07 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-10-28 08:29 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @oshogbo, and @woju)

___
*[`debian/gramine-ratls-dcap.install` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/512#-NFSggoU3-0KzIN8Yue6:-NFSggoU3-0KzIN8Yue7:b-rrx39h) ([raw file](https://github.com/gramineproject/gramine/blob/2321ed61c7ef473bda7d5ea2b454102c69f1f675/debian/gramine-ratls-dcap.install#L4)):*
> ```
> usr/lib/x86_64-linux-gnu/libsecret_prov_verify_dcap*
> usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libra_tls_verify_dcap*
> usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libsecret_prov_verify_dcap*
> ```

What does this mean exactly? Why do we have these libs 2x (one is the symlink to the other)? Was there a specific reason to put libs in the two locations?
___
*[`debian/gramine-ratls-epid.install` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/512#-NFSgruRDlj4n_QlJP8m:-NFSgruRDlj4n_QlJP8n:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2321ed61c7ef473bda7d5ea2b454102c69f1f675/debian/gramine-ratls-epid.install#L4)):*
> ```
> usr/lib/x86_64-linux-gnu/libsecret_prov_verify_epid*
> usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libra_tls_verify_epid*
> usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libsecret_prov_verify_epid*
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-10-28 09:32 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`debian/gramine-ratls-dcap.install` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/512#-NFSggoU3-0KzIN8Yue6:-NFSt9mgAEbPLAuCe1BA:b-i0heg6) ([raw file](https://github.com/gramineproject/gramine/blob/2321ed61c7ef473bda7d5ea2b454102c69f1f675/debian/gramine-ratls-dcap.install#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this mean exactly? Why do we have these libs 2x (one is the symlink to the other)? Was there a specific reason to put libs in the two locations?
</blockquote></details>

This file means that after installing to `DESTDIR=debian/tmp`, those files are taken out of `gramine` package and put in `gramine-ratls-dcap` (like filename). There is no functional change to previous revision, but there I did it manually in `debian/rules`, in `override_dh_auto_install` target, because I had three builddirs and couldn't just move the files with this declarative mechanism. Now we have one builddir and things will be simpler. (That's also related to why I bumped compat level from 11 to 13: compat 13 has an automatic check called `dh_missing` that all the files are really declared as packaged, something similar to `%files` in rpm, and now I can easily use it).

The files are are 2x, because `/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc` is `{{ gramine.runtimedir() }}` used inside gramine, and `/usr/lib/x86_64-linux-gnu` is for normal applications (attestors). If this is incorrect, it should be fixed in `tools/sgx/ra-tls/meson.build`, where the symlink is created in the first place.
___
*[`debian/gramine-ratls-epid.install` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/512#-NFSgruRDlj4n_QlJP8m:-NFSuwVC6lk9YZOJGnlV:b-9g2gzx) ([raw file](https://github.com/gramineproject/gramine/blob/2321ed61c7ef473bda7d5ea2b454102c69f1f675/debian/gramine-ratls-epid.install#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto, but `gramine-ratls-epid` package


<!-- Sent from Reviewable.io -->

2022-10-28 09:58 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @oshogbo)

___
*[`debian/gramine-ratls-dcap.install` line 4 at r7](https://reviewable.io/reviews/gramineproject/gramine/512#-NFSggoU3-0KzIN8Yue6:-NFT0rONE-n0r_lP6Oax:bvl6v3q) ([raw file](https://github.com/gramineproject/gramine/blob/2321ed61c7ef473bda7d5ea2b454102c69f1f675/debian/gramine-ratls-dcap.install#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This file means that after installing to `DESTDIR=debian/tmp`, those files are taken out of `gramine` package and put in `gramine-ratls-dcap` (like filename). There is no functional change to previous revision, but there I did it manually in `debian/rules`, in `override_dh_auto_install` target, because I had three builddirs and couldn't just move the files with this declarative mechanism. Now we have one builddir and things will be simpler. (That's also related to why I bumped compat level from 11 to 13: compat 13 has an automatic check called `dh_missing` that all the files are really declared as packaged, something similar to `%files` in rpm, and now I can easily use it).

The files are are 2x, because `/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc` is `{{ gramine.runtimedir() }}` used inside gramine, and `/usr/lib/x86_64-linux-gnu` is for normal applications (attestors). If this is incorrect, it should be fixed in `tools/sgx/ra-tls/meson.build`, where the symlink is created in the first place.
</blockquote></details>

Thanks! I understand now.


<!-- Sent from Reviewable.io -->

2022-11-21 21:20 UTC, mkow requested changes
> Reviewed 3 of 12 files at r1, 2 of 19 files at r2, 10 of 13 files at r3, 3 of 5 files at r4, 1 of 5 files at r6, 9 of 10 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-NHR04Yv9bG7BrVzDYFU:b5gr8fq) (no related file):*
<details><summary><i>Previously, meithecatte (Maja Kądziołka) wrote…</i></summary><blockquote>

For what it's worth, I agree with @woju. He has enough experience with the tooling around this to understand the cost of trying to hide `debian/` inside a subdirectory, and he's the one who'll have to bear the cost of this decision. For most of us, it's just a question of aesthetics. And frankly, hiding `debian/` in a subdirectory is not an elegant solution when you need to copy it back out to the top-level every time you want to use it.

Realistically, we won't ever support enough distros for top-level directories like `debian/` to be a problem. I'd estimate that this count will be 2 in the long run — it's overwhelmingly likely that if we get funding to support a specific distribution, it'll be either based on apt or rpm.
</blockquote></details>

Ok, I had a talk with woju and here's how I understand the situation: we actually have 4 different problems with packages:
- DEB tooling wants to have `/debian` at top-level. It's possible to just have a script which prepares repo to the expected form, but there are some weird debian tools which you point directly at a repository or a tarball, and we generate the tarball using `meson dist`, which doesn't know about our script (but it has some hooking mechanism, also, we could just run the script before `meson dist`?). But woju's argument against was that external people packaging Gramine won't read our packaging READMEs/docs and won't know about this script.
- RPM tooling requires that in the whole repository there's only a single `.spec` file. That's not the case for Gramine, because we have LTP as a submodule, which contains a `.spec` file. We can either have a preparation script which deletes it, or place some configs in `$HOME` of the builder user (sic!) to circumvent the problem. Or move LTP to a Meson subproject.
- DEB tooling doesn't support multiple `/debian` config dirs for different packages, which will be a problem when we add other backends. Right now the packaging is using quite an incorrect assumption, that CPU architecture implies PAL. This will break e.g. when we implement SEV or TDX backends. @woju's response was that we can build all PALs from a single `/debian`, but then select a subset of produced results for each package. This should work, but it means that e.g. to build PAL/Linux-SGX package one will need to also build PAL/Linux-SEV, which may or may not be a problem, dunno.
- We are going to have a bunch of cloud/vendor-specific plugins. @woju wants them each in a separate repository because again, packaging tooling is limited. But I don't see why can't we solve it same as above, by selecting a subset of outputs.

@woju: Is this description accurate?

Overall I'm really disappointed with how limited are these tools and would prefer to have `prepare.sh` in each `packaging/<distro>/` and require people to run it before packaging tools, to keep the ugliness at the very place where it's required and not propagate it to higher layers (same as when we implement a broken Linux syscall - we don't push these hacks to the PAL API layer, even when it's easier that way).
Anyways, my proposal is to do a call/chat and decide what to do with all these issues.

___
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
wrong component tags (here and above)
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPJD9EEAx-hdop83M):*
This should be one commit in the final version of the PR (we usually merge tests and features in a single commit).
___
*[`.ci/debian11.dockerfile` line 9 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsTQOY-6-mamaU-J5N:-NFsTQOY-6-mamaU-J5O:b-4x1puc) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/.ci/debian11.dockerfile#L9)):*
> ```Dockerfile
> RUN apt-get install -y ca-certificates
> 
> # Intel's RSA-1024 key signing intel-sgx/sgx_repo below. Expires 2023-05-24.
> ```

Please add an entry to your calendar to remember to update it on time.



_Code quote:_
```Dockerfile
Expires 2023-05-24.
```
___
*[`debian/changelog` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5js7LeBzUZsbSLxgWz:-NFsRn-L4GIlHMuCxNTW:bmwbwd7) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/changelog#L49)):*
> they were built and sent to QA

But that happened completely in private (between you and Jinen).

> There's no point in removing them

The point is to reduce information noise, i.e. don't include information which is not useful to anyone, this way making important information (like the changes in the officially released packages) more visible. Same as squashing all typo fixes from commit history before merging to `master`.

But I won't block on this.
___
*[`debian/control` line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyNIE2i3QukDyL1bn:-NHPyNIE2i3QukDyL1bo:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L32)):*
> ```
> Package: gramine
> Architecture: amd64
> Description: A lightweight guest OS designed to run a single application
> ```





_Suggestion:_
```
A lightweight usermode guest OS designed to run a single Linux application
```
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHPydcM7qLJDIGuBw5i:b-cynqu5) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
> ```
>  gramine (= ${binary:Version}),
>  libsgx-dcap-quote-verify,
> #libc6 (>= 2.28),
> ```

what's the point of this comment?
___
*[`debian/control` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyiaz4Ou8YrjtB_8w:-NHPyiaz4Ou8YrjtB_8x:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L64)):*
> ```
> Depends:
>  gramine (= ${binary:Version}),
> #libc6 (>= 2.28),
> ```

ditto
___
*[`debian/rules` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQIvst3RUR4eFCuRZR:-NHQIvsu-WFyKe81FKNM:b-5sfqkc) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L8)):*
> ```
> # see FEATURE AREAS in dpkg-buildflags(1)
> #
> # we need to completely disable LDFLAGS until completely retiring makefiles
> ```

Only `Documentation/` left, right?
___
*[`debian/rules` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQJ7mU7ODGXHmdoNV9:-NHQJ7mV65W5Krn8JaIv:b-4k7ckb) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L19)):*
> ```
> export DEB_OBJCFLAGS_MAINT_SET =
> export DEB_OBJCXXFLAGS_MAINT_SET =
> ```

Almost all targets in this file are missing `.PHONY`
___
*[`debian/rules` line 47 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHR2v6y-VyXBz599eev:-NHR2v6zAV8JQHMZBxmW:b-kzjdsf) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L47)):*
> ```
> 	$(MAKE) -C Documentation man
> 
> override_dh_strip override_dh_mak [...]

2022-11-21 22:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-NHRBW7FCZ7GMM2XLEHV:bcc6qa0) (no related file):*
> But woju's argument against was that external people packaging Gramine won't read our packaging READMEs/docs and won't know about this script.

But if they don't read out docs, then they don't care about our scripts and want to bring their own `debian/`? Generally people packaging external projects are used to getting a tarball with project code **without** `debian/`.

> DEB tooling doesn't support multiple /debian config dirs for different packages, which will be a problem when we add other backends. Right now the packaging is using quite an incorrect assumption, that CPU architecture implies PAL. This will break e.g. when we implement SEV or TDX backends. @woju's response was that we can build all PALs from a single /debian, but then select a subset of produced results for each package. This should work, but it means that e.g. to build PAL/Linux-SGX package one will need to also build PAL/Linux-SEV, which may or may not be a problem, dunno.

For me this sounds like enough arguments to discard the idea of top-level debian.

___


<!-- Sent from Reviewable.io -->

2022-11-22 10:34 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 11 unresolved discussions (waiting on @oshogbo and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/512#-N5fjoxPBUK4mYWJ4p6e:-NHTt8vK4j_ZJOj6KH2v:b-8n6ngo) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But woju's argument against was that external people packaging Gramine won't read our packaging READMEs/docs and won't know about this script.

But if they don't read out docs, then they don't care about our scripts and want to bring their own `debian/`? Generally people packaging external projects are used to getting a tarball with project code **without** `debian/`.

> DEB tooling doesn't support multiple /debian config dirs for different packages, which will be a problem when we add other backends. Right now the packaging is using quite an incorrect assumption, that CPU architecture implies PAL. This will break e.g. when we implement SEV or TDX backends. @woju's response was that we can build all PALs from a single /debian, but then select a subset of produced results for each package. This should work, but it means that e.g. to build PAL/Linux-SGX package one will need to also build PAL/Linux-SEV, which may or may not be a problem, dunno.

For me this sounds like enough arguments to discard the idea of top-level debian.
</blockquote></details>

Looking at the four problems, it looks like for each of these the best solution would be to have a `prepare.sh` helper script, that packaging folks should run before actual DEB tooling.

I second @mkow's idea of `packaging/<distro>/prepare.sh` helper script.

___


<!-- Sent from Reviewable.io -->

2022-11-23 15:57 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 28 of 31 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPJD9EEAx-hdop83M):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be one commit in the final version of the PR (we usually merge tests and features in a single commit).
</blockquote></details>

No problem. Can you do it at rebase+merge?
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong component tags (here and above)
</blockquote></details>

Can you `reword` at rebase+squash+merge (with the changes in for the other comment)?
___
*[`.ci/debian11.dockerfile` line 9 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsTQOY-6-mamaU-J5N:-NH_8-KQ5mWE_fsZhi3E:b-bh5bnx) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/.ci/debian11.dockerfile#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add an entry to your calendar to remember to update it on time.
</blockquote></details>

Done. (You can check in my ITL calendar).
___
*[`debian/changelog` line 49 at r3](https://reviewable.io/reviews/gramineproject/gramine/512#-N5js7LeBzUZsbSLxgWz:-NH_8Lyq-ZI-j66OT1FL:b-p72h2l) ([raw file](https://github.com/gramineproject/gramine/blob/95cb670e6534551d53f93f4e1cf418f04fa2bcfc/debian/changelog#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> they were built and sent to QA

But that happened completely in private (between you and Jinen).

> There's no point in removing them

The point is to reduce information noise, i.e. don't include information which is not useful to anyone, this way making important information (like the changes in the officially released packages) more visible. Same as squashing all typo fixes from commit history before merging to `master`.

But I won't block on this.
</blockquote></details>

OK, I've squashed most of them, preserving important entries.
___
*[`debian/control` line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyNIE2i3QukDyL1bn:-NH_AhI2ACnJCfvu_HPQ:b63cnae) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L32)):*
> ```
> Package: gramine
> Architecture: amd64
> Description: A lightweight guest OS designed to run a single application
> ```

Done. (This was copied from README I think, so maybe we want to change it also there?)
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHRe1n69SPc7jvE5il2:b-sgu1g3) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's the point of this comment?
</blockquote></details>

For some time I've included manual dependency against glibc (normally it's added with `dh_shlibdeps`, but I've disabled that, because the tool was confused by runtimedir, see explanation below). But there was some problem with it and I've commented out this dependency at `1.2~rc1-6`, which coincided with the patch against fcntl (see changelog entry). I don't recall the specifics, why it says 2.28 and why I've removed it after all.

If you have a suggestion for a dependency against glibc, I'd be grateful for one. I suspect there should be `<=` dependency against some current version, and also `>>` so too old glibcs (which would break like this fcntl problem) are also rejected, but I'm not sure about exact versions, so I didn't fix this in this initial PR.
___
*[`debian/control` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyiaz4Ou8YrjtB_8w:-NH_8zxe2Qpv-w1iLXQR:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`debian/rules` line 8 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQIvst3RUR4eFCuRZR:-NHRcIb99SRLNOlldr4O:b-35k8z0) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Only `Documentation/` left, right?
</blockquote></details>

This comment is now wrong. It was referring to our own Makefiles which were sensitive to externally set `CFLAGS` (`CFLAGS` had to be `unset`, not even set to empty, because of a funny way we were doing `include`s and recursionzzxxx). In one of the previous revisions there was a stanza with `unset`. Removed.

`Documentation/Makefile` is fine, `Makefile` there was created by `sphinx-quickstart` and doesn't recurse in that funny way, and I don't want to remove it, because you can rebuild documentation by `make html` or `make man`, not `python3 -m sphinx ...`.
___
*[`debian/rules` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQJ7mU7ODGXHmdoNV9:-NHRbzbz4-1wmGmTuW-A:bkybhby) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Almost all targets in this file are missing `.PHONY`
</blockquote></details>

I don't want to add it. People don't set `.PHONY` on targets in `debian/rules`, debhelper does not require them and also `dh` introspects this makefile to check if some of the targets exist and if exist, if they are empty. This file is run only in very specific ways (by dh), so it's not needed.
___
*[`debian/rules` line 47 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHR2v6y-VyXBz599eev:-NHRdTeeCLIAIpskNK9b:bq3whot) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's this? ditto below
</blockquote></details>

Those targets change or disable several of the steps which in default setup are part of building a binary package. That the target is empty means those steps are not attempted (cf. nonempty `override_dh_auto_build` above, which does something *other* than the default, but in our case first runs the default and the does something additional).

- `dh_strip` strips all ELFs, and I'm not sure what it exactly did, but something was broken. Didn't investigate, just disabled it.
- `dh_makeshlibs` and `dh_shlibdeps` collectively do several things around shared libraries like mapping sonames in ELFs to install-time dependencies in APT and processing during installation (ldconfig). Those break on runtimedir. The side effect is that our dependencies are incomplete (we're missing some basic stuff like glibc which is always installed on `amd64`) and manual (I need to add `libsomething` dependencies manually to `Depends:`), but that's OK.
- `dh_dwz` runs dwz, a tool which also messes with ELFs and debugging symbols, I don't understand exactly what it does, so I've disabled it.
- `dh_fixperms` does `chmod -x` on all `.so`s (among other things), and that broke `gramine-direct` (in direct pal and loader are the same ELF, just symlinked, therefore `.so` needs to be executable).
- `dh_ [...]

2022-11-24 10:43 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 28 of 31 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`debian/control` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHb8tzP-x3hIm-uHbtC:-NHb8tzP-x3hIm-uHbtD:b-3dgigo) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L43)):*
> ```
>  python3-protobuf (>= 3.12),
>  python3-pyelftools,
>  python3-toml (>= 0.10),
> ```

```
 python3-tomli (>= 1.1.0),
 python3-tomli-w (>= 0.4.0),
```

wrt #995

also `Build-Depends:`

@dimakuv plz confirm the versions


<!-- Sent from Reviewable.io -->

2022-11-24 10:53 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 11 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`debian/control` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHb8tzP-x3hIm-uHbtC:-NHdG7IV8J7BL0aVmktC:be6nkvc) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L43)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```
 python3-tomli (>= 1.1.0),
 python3-tomli-w (>= 0.4.0),
```

wrt #995

also `Build-Depends:`

@dimakuv plz confirm the versions
</blockquote></details>

I confirm the versions.


<!-- Sent from Reviewable.io -->

2022-11-24 12:38 UTC, mkow requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can you `reword` at rebase+squash+merge (with the changes in for the other comment)?
</blockquote></details>

Sure.
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPJD9EEAx-hdop83M):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No problem. Can you do it at rebase+merge?
</blockquote></details>

Sure.
___
*[`debian/control` line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyNIE2i3QukDyL1bn:-NHd_VOP-Rf5Mrfdg2Dw:b-t4z0ne) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done. (This was copied from README I think, so maybe we want to change it also there?)
</blockquote></details>

Probably not, in the README it's explained in more detail in the text which directly follows it. Here you don't have it.
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHd_mTA84RzZNd0-2gJ:bplayg6) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For some time I've included manual dependency against glibc (normally it's added with `dh_shlibdeps`, but I've disabled that, because the tool was confused by runtimedir, see explanation below). But there was some problem with it and I've commented out this dependency at `1.2~rc1-6`, which coincided with the patch against fcntl (see changelog entry). I don't recall the specifics, why it says 2.28 and why I've removed it after all.

If you have a suggestion for a dependency against glibc, I'd be grateful for one. I suspect there should be `<=` dependency against some current version, and also `>>` so too old glibcs (which would break like this fcntl problem) are also rejected, but I'm not sure about exact versions, so I didn't fix this in this initial PR.
</blockquote></details>

Hard to say what dependency we need here. But please either:
- Include the right dependency - but this is hard,
- Remove this comment entirely,
- Add a comment explaining why is this commented out.

The current version is very confusing if someone reads it without reading this whole review.
___
*[`debian/rules` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQJ7mU7ODGXHmdoNV9:-NHdaQwJ0_i6uSXTpW5m:b-97i5jv) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't want to add it. People don't set `.PHONY` on targets in `debian/rules`, debhelper does not require them and also `dh` introspects this makefile to check if some of the targets exist and if exist, if they are empty. This file is run only in very specific ways (by dh), so it's not needed.
</blockquote></details>

Still, I'd prefer to comply with how Make works and don't rely on additional assumptions how other tools work on it. I mean, this is a trivial change and makes this file obviously correct.
___
*[`debian/rules` line 47 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHR2v6y-VyXBz599eev:-NHdcJJO8vO91xLDcz7L:b-bj7b71) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L47)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Those targets change or disable several of the steps which in default setup are part of building a binary package. That the target is empty means those steps are not attempted (cf. nonempty `override_dh_auto_build` above, which does something *other* than the default, but in our case first runs the default and the does something additional).

- `dh_strip` strips all ELFs, and I'm not sure what it exactly did, but something was broken. Didn't investigate, just disabled it.
- `dh_makeshlibs` and `dh_shlibdeps` collectively do several things around shared libraries like mapping sonames in ELFs to install-time dependencies in APT and processing during installation (ldconfig). Those break on runtimedir. The side effect is that our dependencies are incomplete (we're missing some basic stuff like glibc which is always installed on `amd64`) and manual (I need to add `libsomething` dependencies manually to `Depends:`), but that's OK.
- `dh_dwz` runs dwz, a tool which also messes with ELFs and debugging symbols, I don't understand exactly what it does, so I've disabled it.
- `dh_fixperms` does `chmod -x` on all `.so`s (among other things), and that broke `gramine-direct` (in direct pal and loader are the same ELF, just symlinked, therefore `.so` needs to be executable).
- `dh_auto_test` runs buildsystem-specific "tests", in our case of `--with=meson+ninja` that would be `meson test` (or `ninja test` on older compat level), but we don't have tests in meson. In theory that would run 0 tests, successfully, but in the future we probably want to run `CI-Examples/helloworld` in either `gramine-direct` or `gramine-sgx`, depending on HW. So this is TODO and disabled for now.

Those tools probably can be tweaked to ignore selected files, but I didn't bother. If you want any of those explanations as comments in the file, I can do it.

There are other steps (the list depends on "compat level", ours is 13 right now, see `debhelper-compat` in `debian/control`), the list is in build log (see `dh_something` before and This is just a comment. after meson build), but they are either needed or harmless no-ops.
</blockquote></details>

Hmmmm, how is it possible that this line disables anything? It does _not_ define empty recipes for these targets, it only _adds_ 0 dependencies to them. To define an empty recipe in Make you need to state at least one command, in such cases usually `@:`. Is some serious Make abuse happening here?


<!-- Sent from Reviewable.io -->

2022-11-25 13:20 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: 30 of 31 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`debian/control` line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyNIE2i3QukDyL1bn:-NHiGUY0DmPPoywZZWQs:bwsq6fl) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Probably not, in the README it's explained in more detail in the text which directly follows it. Here you don't have it.
</blockquote></details>

`Description:` is two part, subject as first line and long description in the rest, very similar to git commit or doxygen comment. We can have a few paragraphs there, and we probably should. For now it's just subject. I'll leave it like this for now.
___
*[`debian/control` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHb8tzP-x3hIm-uHbtC:-NHiw6nV9TQRs4ch909V:br6rxlu) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I confirm the versions.
</blockquote></details>

Blocking until #995 is merged, then I'll rebase on top of that and will add those deps.
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHijXj59gasnUkqi6Bt:b2il92o) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hard to say what dependency we need here. But please either:
- Include the right dependency - but this is hard,
- Remove this comment entirely,
- Add a comment explaining why is this commented out.

The current version is very confusing if someone reads it without reading this whole review.
</blockquote></details>

I've added them as TODO.
___
*[`debian/rules` line 19 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHQJ7mU7ODGXHmdoNV9:-NHiviAO5JwnA6VDLzgJ:byrq2m7) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still, I'd prefer to comply with how Make works and don't rely on additional assumptions how other tools work on it. I mean, this is a trivial change and makes this file obviously correct.
</blockquote></details>

see below
___
*[`debian/rules` line 47 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHR2v6y-VyXBz599eev:-NHfrI9i8io_b5MzjgOa:b39jgnf) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/rules#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmmmm, how is it possible that this line disables anything? It does _not_ define empty recipes for these targets, it only _adds_ 0 dependencies to them. To define an empty recipe in Make you need to state at least one command, in such cases usually `@:`. Is some serious Make abuse happening here?
</blockquote></details>

`dh $@` just exits 0: https://salsa.debian.org/debian/debhelper/-/blob/64cec8bc64baaec24b724ea920314256469b2bc4/dh#L647 if you accidentaly ran them anyway (like if you explicitly called `debian/rules override_dh_auto_test`, which from "proper Make" POV is theoretically a valid thing to do, but in practice never happens).

But yes, this makefile is introspected to see if those `override_dh_*` targets are defined and if so, if they're nonempty. This is documented: https://manpages.debian.org/bullseye/debhelper/dh.1.en.html#Completely_empty_targets

And that's how it's done: https://salsa.debian.org/debian/debhelper/-/blob/64cec8bc64baaec24b724ea920314256469b2bc4/lib/Debian/Debhelper/SequencerUtil.pm#L234

This is also why `.PHONY:` is irrelevant, and would look weird to people who are used to writing `debian/rules`. `.PHONY:` is required only if you have one of the *sequence* values (i. e. what goes as argument to `debian/rules` invocation and as `$@` argument to `dh`) as a file/directory created as part of build process. *sequence* is one of `build-arch`, `build-indep`, `build`, `clean`, `install-indep`, `install-arch`, `install`, `binary-arch`, `binary-indep`, and `binary` (from those, `build` stands out, because it's a common name of the builddir). This case is even discussed in Debian Policy: https://www.debian.org/doc/debian-policy/ch-source.html#id30, but we don't need it, because by default with `--with=meson+ninja` builddir is named `obj-x86_64-linux-gnu` or sth (cf. `.gitignore`).

Generally speaking, this file is not "proper Make" (even if it's executed by real Make) and usual guidelines don't apply. Moreover, it's defined how you are allowed to run this file (`$PWD` must be in repo toplevel and the invocation is `debian/rules $sequence`, cf. https://www.debian.org/doc/debian-policy/ch-source.html#main-building-script-debian-rules; if you didn't use debhelper, it didn't need to be Makefile at all, which historically was allowed).


<!-- Sent from Reviewable.io -->

2022-11-27 01:47 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 6 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`debian/control` line 43 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHb8tzP-x3hIm-uHbtC:-NHqk6xaE0swDlRaDNC7:ba6gyet) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L43)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Blocking until #995 is merged, then I'll rebase on top of that and will add those deps.
</blockquote></details>

It was just merged.
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHqkOCR0QmKAQ5u5j4k:bovp0l3) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I've added them as TODO.
</blockquote></details>

Nitpick: `TODO:` (to match the style in other places)


<!-- Sent from Reviewable.io -->

2022-11-28 11:26 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPJD9EEAx-hdop83M):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.
___
*[`debian/control` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPydcM7qLJDIGuBw5h:-NHxwkomBzInOT60iWZh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nitpick: `TODO:` (to match the style in other places)
</blockquote></details>

Done.
___
*[`debian/control` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NHPyiaz4Ou8YrjtB_8w:-NHxwlTw0-odfbTOmXdP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/eff80603da665166b7ca087668b39ca68f50552a/debian/control#L64)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-28 19:16 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 5 unresolved discussions (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-11-30 17:07 UTC, mkow requested changes
> Reviewed 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo and @woju)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We previously used `packaging` tag, I don't see any `pkg` in the commit log, please change


<!-- Sent from Reviewable.io -->

2022-11-30 17:12 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @oshogbo)

___
*[`-- commits` line 7 at r8](https://reviewable.io/reviews/gramineproject/gramine/512#-NFsPGwE6yStUoYtcd9E):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We previously used `packaging` tag, I don't see any `pkg` in the commit log, please change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-30 17:13 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-11-30 17:51 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/512)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-11-30 19:48 UTC, boryspoplawski approved these changes

2022-12-02 00:50 UTC, merged