Rewrite sysfs topology support
gramineproject/gramine pull request #530
Opened 2022-04-16 22:03 UTC by mkow

## Description of the changes

This PR completely rewrites all three parts of sysfs topology handling:
- parsing sysfs files on the host (`topo_info.c`),
- passing them to LibOS, possibly across a security boundary (`Linux-SGX/db_main.c`),
- generating sysfs files inside LibOS based on the topology information (`fs/sys/*`).

The overall idea of the rewrite is to simplify and normalize the data structures passing through the untrusted interface, to ensure they are properly handled and sanitized. Effectively, this PR shifts as much complexity as possible to either untrusted side or to the part working on already sanitized, in-enclave data.

The reason for this change is the number of security issues found in the old code and review difficulty of sanitization in the old approach (despite multiple review passes I kept finding new issues).

I plan some more changes for future PRs, but they aren't strictly related to the code changed here (e.g. adding a proper test suite for sysfs topology).

Fixes #483.
Fixes https://github.com/gramineproject/graphene/issues/2105.

## Functional changes

- Added support for offline CPU threads (but no hot-plug, the state is snapshotted at the start).
- `/sys/devices/system/cpu/cpu<n>/topology/core_id` values have changed - they aren't socket-local anymore, but are globally unique. This shouldn't matter, as this node is documented in Linux as "the hardware platform’s identifier (rather than the kernel’s). The actual value is architecture and platform dependent.".

## Rough edges

The worst part of this PR is probably `Linux-common/topo_info.c`, but I don't see any other way to write this. This is something where we just need lambdas, but C doesn't have them. Anyways, if you have some ideas how to make it better, then please add them to the review.

Also, please be careful when reading the code around topology structures. `pal_cpu_thread_info` and `pal_numa_node_info` fields are valid _only_ for online nodes. Technically, we could remove offline nodes and pretend they don't exist (as we don't support hot-plug and probably never will), but that won't make the implementation any simpler (because we'd need to translate indices in parser code).

## Useful links for reviewers

- https://www.kernel.org/doc/html/latest/admin-guide/cputopology.html
- https://www.kernel.org/doc/html/latest/admin-guide/abi-stable.html

## sysfs mysteries

The format used in Linux sysfs is quite obscure and the documentation is partial at best. Things I don't know:
- What's the different between "die" and "package" in their terminology?
- Can a NUMA node actually be turned offline? I never succeeded in shutting down one, even after shutting down all CPUs inside the node it shows up as online on `node/online` list. If that's the case, then what's the purpose of `node/online` on Linux?

## How to test this PR?

This PR requires extensive testing, although it should be quite safe to merge - it contains less assumptions than the old implementation, at the same time refusing all internally inconsistent topology data. Despite this, there may be something I didn't think of :)

To anyone reading this who has some unusual environment (i.e. something more than boring 8-threaded single CPU) and have a moment: please try out this branch, just starting Gramine built from it on any binary should be enough. If you have more time, checking if contents of `/sys/devices/system/` make sense would be helpful.

I'm especially looking for:
- machines with more than 1 NUMA node,
- virtualized environments,
- machines with non-default configuration (e.g. some CPUs shut down or disabled).

2022-04-16 22:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 75 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oQXE-704g159eNOCH:-N-oQXE-704g159eNOCI:b-qww0lv) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/include/shim_fs_pseudo.h#L75)):*
> ```objc
> /* Used to represent cpumaps like "00000000,ffffffff,00000000,ffffffff".
>  * Note: Used to allocate on stack; increase with caution or use malloc instead. */
> #define PAL_SYSFS_MAP_FILESZ 256
> ```

FYI: This was moved from `pal_topology.h` (this is a more appropriate place for it).
___
*[Pal/include/arch/x86_64/pal_topology.h, line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oQhlG0ssCTB0GHYn5:-N-oQhlG0ssCTB0GHYn6:by4nco6) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L14)):*
> ```objc
> /* Used to represent buffers having numeric values and unit suffixes if present, e.g. "1024576K".
>  * NOTE: Used to allocate on stack; increase with caution or use malloc instead. */
> #define PAL_SYSFS_BUF_FILESZ (256+2)
> ```

FYI: The old value was too small for cases where a lot of CPU threads were disabled.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oQxZmEbA5DbuNQqjP:-N-oQxZmEbA5DbuNQqjQ:bh8smva) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L17)):*
> ```objc
> 
> /* Max number of caches (such as L1i, L1d, L2, etc.) supported. */
> #define MAX_CACHES 4
> ```

FYI: Hardcoded cap to avoid nesting dynamic arrays.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 116 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oP_hT5mJI1jHRXefl:-N-oP_hT5mJI1jHRXefm:b-mj4f7l) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L116)):*
> ```C
> }
> 
> /* Without this, `(int)imported_bool` may actually return something outside of {0, 1}. */
> ```

FYI: This was missing from the old code.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 209 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oQ6oFAuS1QmRSyakF:-N-oQ6oFAuS1QmRSyakG:bci5307) ([raw file](https://github.com/gramineproject/gramine/blob/9fe875a1d4dc966b8789cd3db298d746fa58cefb/Pal/src/host/Linux-SGX/db_main.c#L209)):*
> ```C
>         if (!sgx_copy_to_enclave(temp_cache_info_arr,
>                                  cache_indices_cnt * sizeof(*temp_cache_info_arr),
>                                  temp_core_topo_arr->cache_info_arr,
> ```

FYI: That was another bug in the old code I found while rewriting - it missed indexing and always copied information about cache 0.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N-oT1xQ7dv4DlWvoYeR:b-3t9i44) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
> ```C
>     struct pal_cpu_core_info*   cores      = sgx_import_array_to_enclave(shallow_topo_info.cores,      sizeof(*cores),      cores_cnt);
>     struct pal_socket_info*     sockets    = sgx_import_array_to_enclave(shallow_topo_info.sockets,    sizeof(*sockets),    sockets_cnt);
>     struct pal_numa_node_info*  numa_nodes = sgx_import_array_to_enclave(shallow_topo_info.numa_nodes, sizeof(*numa_nodes), numa_nodes_cnt);
> ```

Left unwrapped to make this more tabular (easier to verify that everything is copied and verified).


<!-- Sent from Reviewable.io -->

2022-04-18 07:40 UTC, vijaydhanraj reviewed
With cores offlined, I see the following tests failing when running `LibOS` regression tests.
```
test_libos.py::TC_30_Syscall::test_101_sched_set_get_cpuaffinity FAILED 
test_libos.py::TC_30_Syscall::test_102_pthread_set_get_affinity FAILED
test_libos.py::TC_40_FileSystem::test_021_procstat FAILED 
test_libos.py::TC_40_FileSystem::test_040_sysfs FAILED

```
Can you please pull out the support for offline cores into a separate PR?

Also, `core_id` seems to be incorrectly printed. For example, on my system,
```
cat /sys/devices/system/cpu/cpu42/topology/core_id                                                                                 
10
```

But we end up printing,
```
/sys/devices/system/cpu/cpu42/topology/core_id: file
[/sys/devices/system/cpu/cpu42/topology/core_id] 4
```

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530#-:-N-vYw-h3QSfOIllAMPS:b-r6muba)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-18 13:32 UTC, mkow reviewed
@vijaydhanraj: Please use Reviewable threads for discussions, you raised 3 different topics in a single comment ;)

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530#-:-N-wqYHZAlOU1pVCQY1L:b31i84)* status: 0 of 20 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N-wqX7v4jVmkdTaseqo:bnpdf92) (no related file):*
> Also, `core_id` seems to be incorrectly printed. For example, on my system,

Please read the PR description ;)

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqj7O8_tFuOGFDXgD:-N-wqj7O8_tFuOGFDXgE:b-zfxg8q) (no related file):*
> With cores offlined, I see the following tests failing when running `LibOS` regression tests.

Yup, I'm aware of this and plan to completely rewrite topology tests in upcoming PRs.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wr-hhC4LQIcp5_B0t:-N-wr-hhC4LQIcp5_B0u:b-rjg7da) (no related file):*
> Can you please pull out the support for offline cores into a separate PR?

It's not something I could "pull out", I'd need to reimplement this PR without offlining, and then add the current version on top of it. Also, what's the reason to not include it here? It's not a significant part of it.

---


<!-- Sent from Reviewable.io -->

2022-04-18 15:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 0 of 20 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N-xCXS-3gR2nuZUjhZ6:b-36h6l2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Also, `core_id` seems to be incorrectly printed. For example, on my system,

Please read the PR description ;)
</blockquote></details>

Yes, I did but couldn't get this `they aren't socket-local anymore`. Can you please clarify this? Maybe I missed something, but the documentation simply says it is hardware platform’s identifier and the value is architecture and platform dependent.

Since Linux keeps this value local to the socket, why change this?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqj7O8_tFuOGFDXgD:-N-xEQhP2ivGzH4fZyDj:b2nhktp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> With cores offlined, I see the following tests failing when running `LibOS` regression tests.

Yup, I'm aware of this and plan to completely rewrite topology tests in upcoming PRs.
</blockquote></details>

OK.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wr-hhC4LQIcp5_B0t:-N-xETsU4-6LX1D2G8nX:b-lpmqol) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Can you please pull out the support for offline cores into a separate PR?

It's not something I could "pull out", I'd need to reimplement this PR without offlining, and then add the current version on top of it. Also, what's the reason to not include it here? It's not a significant part of it.
</blockquote></details>

This PR has a lot of change to consume, so preferred to review/understand a new feature such as core offling as a separate PR even though it is small.

---


<!-- Sent from Reviewable.io -->

2022-04-18 17:48 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 0 of 20 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N-xl73rBHLNOHkdSy5y:b-oo3vy8) (no related file):*
Socket-local means that the IDs can repeat between different sockets on Linux.

> Since Linux keeps this value local to the socket, why change this?

This makes the implementation much simpler.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wr-hhC4LQIcp5_B0t:-N-xlUb4780CRmbmhUFc:bjzy4ak) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This PR has a lot of change to consume, so preferred to review/understand a new feature such as core offling as a separate PR even though it is small.
</blockquote></details>

But it's not separate to these changes. I'd need to actually reimplement a lot of the code to remove this support, e.g. remove `is_online` fields from the structures and all the code which operates on it. All of these structs are designed now to support this. I'd write this code differently if I didn't have to support offline threads and nodes.

Also, please keep in mind that the old code had partial support for offline threads - it had these `is_online` fields and kept the `online` cpu masks, but other places missed proper handling of those.

---


<!-- Sent from Reviewable.io -->

2022-04-19 10:26 UTC, pwmarcz requested changes
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 19 of 20 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 45 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N005Aod6izBDK8EWRYU:-N005Aoe5OgS8-h-D4l6:bdycpio) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L45)):*
> ```C
>     if (buf_pos + 2 > buf_size)
>         return -EOVERFLOW;
>     buf[buf_pos] =   '\n';
> ```

If you want to align these two lines, shouldn't `=` be aligned?
___
*[LibOS/shim/src/fs/sys/fs.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N007h0b2v-cQlw3FKnq:-N007h0b2v-cQlw3FKnr:ba2d1ow) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L59)):*
> ```C
>     uint32_t word = 0;
>     while (1) {
>         if (pos < count /* handle count == 0 gracefully */
> ```

There are two places where `count == 0` complicates things: here, and in the `pos` initialization above. Have you considered an early return instead? Something like (with error handling, of course):

```c
if (count == 0) {
    strcpy(buf, "0\n");
    return 0;
}
...
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 63 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N006jQT9aFBrmIOeEYE:-N006jQT9aFBrmIOeEYF:bk0b2v7) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L63)):*
> ```C
>             word |= (1 << pos % 32);
>         if (pos % 32 == 0) {
>             if (count <= 32) // Linux sysfs quirk in small bitmasks case
> ```

Can you explain that the quirk is about no leading zeroes? Also, by convention, we use braces in such cases (`if` with `else`), and I'd feel safer seeing them here too.

Formatting suggestion:

```c
if (count <= 32) {
    /* Linux sysfs quirk: small bitmasks are printed without leading zeroes */
    ret = snprintf(buf, buf_size, "%x\n", word); // pos == 0, loop exits afterwards
} else {
    ret = snprintf(buf + buf_pos, buf_size - buf_pos, "%08x%c", 
                   word, pos != 0 ? ',' : '\n');
}
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 107 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N009rCZCWYNVvdVRtsT:-N009rCZCWYNVvdVRtsU:b-nm88d1) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L107)):*
> ```C
>             }
>         }
>         *out_total = found ? total + 1 : 0; // +1 to convert max index to elements count
> ```

The variable name `total` does not make sense now, since it's actually max index. I'd suggest either renaming `total` to `max` (but you'd need to initialize it to `(size_t)-1`? or use signed var?), or setting it to `total = MAX(total, j + 1)` above.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N00Bs6O3f9P8rEpvvgz:blluao7) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
> ```objc
> 
>     size_t core_id; // containing core; index into pal_topo_info::cores
>     size_t caches_ids[MAX_CACHES]; // indices into pal_topo_info::caches, -1 if not present
> ```

`cache_ids` would be more natural, IMO.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 103 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00BDXn1tS7QsZWLAnX:-N00BDXn1tS7QsZWLAnY:bc37geb) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L103)):*
> ```objc
>     struct pal_numa_node_info* numa_nodes;
> 
>     /* Has `numa_nodes_cnt` x `numa_nodes_cnt` elements.
> ```

Nit: `` `numa_nodes_cnt * numa_nodes_cnt` ``?
___
*[Pal/src/db_main.c, line 531 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00C6Sz0jp6_bjdajS6:-N00C6Sz0jp6_bjdajS7:bcshnoe) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/db_main.c#L531)):*
> ```C
>     g_pal_public_state.mem_total = _DkMemoryQuota();
> 
>     if (toml_key_exists(g_pal_public_state.manifest_root,
> ```

Add TODO for removing this two versions from now?
___
*[Pal/src/host/Linux-common/topo_info.c, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00C_c65yhM2wOi27LB:-N00C_c65yhM2wOi27LC:b-gcfthn) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-common/topo_info.c#L30)):*
> ```C
> 
>     char* end;
>     long val = strtol(buf, &end, 10);
> ```

There's no overflow handling here (strtol will return `LONG_MAX`). Also, we'll happily parse an empty string. Use our `str_to_ulong`?

Same applies to other uses of `strtol` in this file. I know the files are technically "trusted" in this code, but maybe it won't hurt to be a bit more strict.x
___
*[Pal/src/host/Linux-common/topo_info.c, line 48 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DTWQDY3wHh1SA-kT:-N00DTWQDY3wHh1SA-kU:b-e76jl) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-common/topo_info.c#L48)):*
> ```C
> }
> 
> static int read_numbers_from_file(const char* path, size_t* out_arr, size_t count) {
> ```

How do we expect the numbers to be separated? Spaces? A comment would be good, e.g. `/* Read a space-separated list of numbers */`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00KJRY1oMa2Yn1kmDj:-N00KJRY1oMa2Yn1kmDk:b5mr3e6) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L200)):*
> ```C
> 
>     for (size_t i = 0; i < topo_info->numa_nodes_cnt; i++) {
>         // Note: Linux doesn't guarantee that distance i -> i is 0, so we aren't checking this.
> ```

To me, this comment suggests that 0 is expected/common but not guaranteed on all systems. I was surprised to learn that's not the case: on all systems I checked, this distance is 10. Maybe you can rephrase?


<!-- Sent from Reviewable.io -->

2022-04-19 13:26 UTC, dimakuv requested changes
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 54 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N001uyr8anoLqGxOhmD:b3tntwr) (no related file):*
> > Since Linux keeps this value local to the socket, why change this?
> 
> This makes the implementation much simpler.

Well, the main question is -- do any real-world applications rely on this "socket-local" `coreid` as implemented in Linux on "normal platforms" (I guess this "socket-local" logic in Linux is for x86-64 machines).

Even though it may be wrong to assume "socket-local" logic, if some app or library like `hwloc` relies on this, then we need to mirror what Linux provides. I guess just running OpenVINO and PyTorch should be enough to check this?

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wr-hhC4LQIcp5_B0t:-N002mGV8fa5UoYnoOnR:b-n0ubui) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it's not separate to these changes. I'd need to actually reimplement a lot of the code to remove this support, e.g. remove `is_online` fields from the structures and all the code which operates on it. All of these structs are designed now to support this. I'd write this code differently if I didn't have to support offline threads and nodes.

Also, please keep in mind that the old code had partial support for offline threads - it had these `is_online` fields and kept the `online` cpu masks, but other places missed proper handling of those.
</blockquote></details>

Looks like we have to review this PR as-is.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0058NaET3zKds8chj9:-N0058NaET3zKds8chjA:bnomxd3) (no related file):*
Hint for reviewers:
- `threads` means "hyperthreads" (aka "logical cores")
- `cores` means "CPU cores" (aka "physical cores")

---
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N0036wsDXDqse6dd7qx):*
`them` is wrong because it means `sysfs files`. You don't pass the files, you pass the topology information. So maybe `passing them` -> `passing the parsed topology information`
___
*[LibOS/shim/src/fs/proc/info.c, line 147 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N005TxyA7EFA-PXi2Hq:-N005Txz9N2BXn0JgRxh:b2nwi9m) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/proc/info.c#L147)):*
> ```C
>         if (!thread->is_online)
>             /* Offline cores are skipped in cpuinfo, with gaps in numbering. */
>             continue;
> ```

Please add `{` and `}` around this code block
___
*[LibOS/shim/src/fs/proc/info.c, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N005u9n6lWefiX0xDPr:-N005u9n6lWefiX0xDPs:bbu4tlf) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/proc/info.c#L159)):*
> ```C
>         ADD_INFO("physical id\t: %zu\n", core->socket_id);
> 
>         /* Linux keeps this numbering cpu-local, but we can use a different one, and it's documented
> ```

`cpu-local` -> `socket-local`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00A2Rv7l0sNstuSWQ6:-N00A2Rv7l0sNstuSWQ7:b-ul6fky) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
> ```C
> struct callback_arg {
>     size_t cache_id_to_match; // index in global caches list (topo_info->caches[])
>     size_t cache_type; // cache type/level (index in caches_ids[])
> ```

This is super-confusing, because there is also a `cache_type` enum (which has `DATA`, `INSTRUCTION`, `UNIFIED`).

But your `cache_type` actually corresponds to the `index0`, `index1`, `index2`, etc. files. Please rename, at least to `cache_type_level`.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N00Cusb9OKW7c2w6w76:bbrhfkn) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
> ```C
> };
> 
> static bool is_same_cache(size_t pos, const void* _callback_arg) {
> ```

In these callback functions, the first argument is sometimes:
- `ind` (that's also the arg name in the header file)
- `pos`
- `thread_id` (i.e., a specific name rather than generic)

Could you unify to one format? I prefer `ind` or specific names (like `thread_id`), but not `pos`.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N0072Qp8McNOc04iKuj:-N0072Qp8McNOc04iKuk:bqevdcl) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L24)):*
> ```C
> static bool is_same_cache(size_t pos, const void* _callback_arg) {
>     const struct callback_arg* callback_arg = _callback_arg;
>     const struct pal_cpu_thread_info* ti = &g_pal_public_state->topo_info.threads[pos];
> ```

`ti` -> `thread`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DS094MjqrsgDdyn3:-N00DS094MjqrsgDdyn4:b-z0mbie) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
> ```C
> 
> static bool is_online(size_t ind, const void* _topo_info) {
>     struct pal_topo_info* topo_info = (struct pal_topo_info*)_topo_info;
> ```

We have a convension of calling this variable `ti`. In this PR, you mix `ti` to sometimes be "topo info" and sometimes "CPU thread info".
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DyTC12eXMIcpEKxK:-N00DyTC12eXMIcpEKxL:b-81p27e) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
> ```C
> 
> static bool is_online(size_t ind, const void* _topo_info) {
>     struct pal_topo_info* topo_info = (struct pal_topo_info*)_topo_info;
> ```

In below callback funcs, you directly use `g_pal_public_state->topo_info` global var. I would suggest to use this global var here for uniformity (and pass NULL in the caller).
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DVD46xOVsKzFtwm3:-N00DVD46xOVsKzFtwm4:b-tf4pts) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L28)):*
> ```C
> int sys_cpu_general_load(struct shim_dentry* dent, char** out_data, size_t* out_size) {
>     int ret;
>     const struct pal_topo_info* topo_info = &g_pal_public_state->topo_info;
> ```

We have a convension of calling this variable `ti`.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00EQxJEk68WXx_96WN:-N00EQxJEk68WXx_96WO:bqevdcl) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L49)):*
> ```C
> static bool is_in_same_core(size_t thread_id, const void* _arg) {
>     size_t arg_id = *(const size_t*)_arg;
>     struct pal_cpu_thread_info* ti = &g_pal_public_state->topo_info.threads[thread_id];
> ```

`ti` -> `thread`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00ET9a8s4DFwoQynvk:-N00ET9a8s4DFwoQynvl:bqevd [...]

2022-04-19 18:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 54 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02-U3m3ubfnNSq6nwR:-N02-U3m3ubfnNSq6nwS:b-awvef6) (no related file):*
I tested this PR on three machines, both `gramine-direct` and `gramine-sgx`, using LibOS tests and manual Busybox sessions:
1. My development machine with 12 cores, one socket, one NUMA domain
2. A testing machine with 144 cores, two sockets, two NUMA domains (3 cores `isolated` but not `offline`)
3. A testing machine with >200 cores, two sockets, two NUMA domains

Everything works as expected, except some LibOS tests on machine 2. The problem is similar to Vijay's problem above.

---


<!-- Sent from Reviewable.io -->

2022-04-19 21:17 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 12 of 20 files reviewed, 52 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N013O50Ew46TLSUZTFV:b-duln06) (no related file):*
> Well, the main question is -- do any real-world applications rely on this "socket-local" `coreid` as implemented in Linux on "normal platforms" (I guess this "socket-local" logic in Linux is for x86-64 machines).

I don't think so, it's probably a raw value extracted from ACPI tables and vendor-specific in practice.

> I guess just running OpenVINO and PyTorch should be enough to check this?

@dimakuv: Do you know who to ask to test these? I know you had/have some users of them, so they could try some real workloads on this PR.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0058NaET3zKds8chj9:-N013aEe1AVd-GIrWrs2:bb7867z) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hint for reviewers:
- `threads` means "hyperthreads" (aka "logical cores")
- `cores` means "CPU cores" (aka "physical cores")
</blockquote></details>

Yup.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02-U3m3ubfnNSq6nwR:-N02_Whv7dU8N7-iZ1lz:b-qur568) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tested this PR on three machines, both `gramine-direct` and `gramine-sgx`, using LibOS tests and manual Busybox sessions:
1. My development machine with 12 cores, one socket, one NUMA domain
2. A testing machine with 144 cores, two sockets, two NUMA domains (3 cores `isolated` but not `offline`)
3. A testing machine with >200 cores, two sockets, two NUMA domains

Everything works as expected, except some LibOS tests on machine 2. The problem is similar to Vijay's problem above.
</blockquote></details>

Thanks! Yes, these tests are very strict about the host machine and often doesn't work.

---
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N0036wsDXDqse6dd7qx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`them` is wrong because it means `sysfs files`. You don't pass the files, you pass the topology information. So maybe `passing them` -> `passing the parsed topology information`
</blockquote></details>

+1, will fix during rebase
___
*[LibOS/shim/src/fs/proc/info.c, line 147 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N005TxyA7EFA-PXi2Hq:-N013wID2pWgOynWS3VE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/proc/info.c#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `{` and `}` around this code block
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/info.c, line 159 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N005u9n6lWefiX0xDPr:-N0147KREpZaIrLnUQIv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/proc/info.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`cpu-local` -> `socket-local`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00A2Rv7l0sNstuSWQ6:-N014ZQs8Lb32AjrH8jc:b-o1582u) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is super-confusing, because there is also a `cache_type` enum (which has `DATA`, `INSTRUCTION`, `UNIFIED`).

But your `cache_type` actually corresponds to the `index0`, `index1`, `index2`, etc. files. Please rename, at least to `cache_type_level`.
</blockquote></details>

I know... This was a part of the PR where I got really stuck because of this clash of the names and I still have no idea how to fix it. Unfortunately I can't use `cache_type_level`, because this is _not_ the cache level - same as with "type", we already have a "level" field in the cache struct, and it's different than this index (consider L1i and L1d).
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N015BU2-n83g24OWNYh:b-ar7bru) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In these callback functions, the first argument is sometimes:
- `ind` (that's also the arg name in the header file)
- `pos`
- `thread_id` (i.e., a specific name rather than generic)

Could you unify to one format? I prefer `ind` or specific names (like `thread_id`), but not `pos`.
</blockquote></details>

Sure, but will wait for @pwmarcz opinion on this to avoid changing it twice ;) @pwmarcz: which form do you prefer?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DS094MjqrsgDdyn3:-N015RLMB95jRpqYnAMJ:b-uajfgj) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a convension of calling this variable `ti`. In this PR, you mix `ti` to sometimes be "topo info" and sometimes "CPU thread info".
</blockquote></details>

Yeah, but I didn't care about this much in 2/3 lines-long functions, as it's obvious there. I can unify one way or the other, but let's wait for @pwmarcz input on this to not do it twice.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DyTC12eXMIcpEKxK:-N017-t2A3y8JQAEn2Nf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In below callback funcs, you directly use `g_pal_public_state->topo_info` global var. I would suggest to use this global var here for uniformity (and pass NULL in the caller).
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 61 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Exic1ATGdemX6pt3:-N02I32H6-Vveh3YVaK0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the above file, you called this `thread_id`. Please unify.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00F9Hd60KSf3sOyNJR:-N02I4xO3OtsTY17fJ9E:bkhbgvz) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

:( Way too many aliases for the same object. `thread`, `ti`, and now `thread_info`... Please stick to one name. I prefer `thread`.
</blockquote></details>

Yeah, that happens if writing something [...]

2022-04-19 23:36 UTC, boryspoplawski requested changes
> Reviewed 12 of 20 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 60 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oVrX77l4AAxpRnz2:-N02oVrX77l4AAxpRnz3:b-va0l58) (no related file):*
FYI: I did not review this PR thoroughly, just skimmed over it.

---
___
*[Documentation/manifest-syntax.rst, line 879 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02jYmb5xisL85RT4Gx:-N02jYmb5xisL85RT4Gy:b-xmx9bi) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L879)):*
> ```reStructuredText
>     (Default: false)
> 
> This feature is now enabled by default and the option was removed.
> ```

I think we should keep this disabled for now and enable once we are sure everything is ok (e.g. once we have a proper test suite and we run multiple real life workloads on different cpu configurations).
___
*[LibOS/shim/src/fs/proc/info.c, line 167 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02mUHd6Toqj7An8NF0:-N02mUHd6Toqj7An8NF1:b-8ogsb4) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/proc/info.c#L167)):*
> ```C
>         for (size_t j = 0; j < ti->cores_cnt; j++) // slow, but shouldn't matter
>             if (ti->cores[j].socket_id == core->socket_id)
>                 cores_in_socket++;
> ```

These are two statements (albeit nested), so I would prefer braces, at least around `for`.
Not blocking as we have no clear code guidelines for this case. I personally prefer braces everywhere (even in single statement if/for).
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N02nPBx-b2th8kxOvG1:b-v68i0p) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sure, but will wait for @pwmarcz opinion on this to avoid changing it twice ;) @pwmarcz: which form do you prefer?
</blockquote></details>

What is `ind`? If that's an abbreviation for `index`, then I think standard ones are `i`, `id` and `idx`. Never seen `ind`.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N02oDlK-9fqBbEETef8:bncl2tl) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
> ```C
>                 break;
>             default:
>                 assert(!"Should be unreachable");
> ```

What is this suppose to be? I mean, it's unreachable, but there is code behind it...
___
*[LibOS/shim/src/fs/sys/fs.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N007h0b2v-cQlw3FKnq:-N02tFU70zmPmRgNuvd5:b-7vkglu) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I was thinking about this, but unfortunately the snippet which Paweł pasted is too simple to be correct ;)
The correct version is less nice:
```C
if (count == 0) {
    if (buf_size < 3)
        return -EOVERFLOW;
    strcpy(buf, "0\n");
    return 0;
}
```

Do you prefer this version or sticking with the current solution?
</blockquote></details>

+1 to change.
___
*[LibOS/shim/src/fs/sys/fs.c, line 61 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02rl8EC0Y_yTjBGh2a:-N02rl8EC0Y_yTjBGh2b:b-dhwjr7) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/fs.c#L61)):*
> ```C
>         if (pos < count /* handle count == 0 gracefully */
>                 && is_present(pos, callback_arg))
>             word |= (1 << pos % 32);
> ```

Why bracket around?
___
*[LibOS/shim/src/fs/sys/node_info.c, line 68 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02uUo5AcndALzMB_pw:-N02uUo5AcndALzMB_px:brtot0l) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/node_info.c#L68)):*
> ```C
>     const struct pal_topo_info* topo_info = &g_pal_public_state->topo_info;
>     const struct pal_numa_node_info* numa_topo = &topo_info->numa_nodes[node_id];
>     char str[PAL_SYSFS_MAP_FILESZ] = {'\0'};
> ```

Just `0` please.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 78 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N03-EoZCJL9HuuPPkMt:-N03-EoZCJL9HuuPPkMu:b-xdtq4u) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L78)):*
> ```objc
>  * consistency when crossing untrusted -> trusted boundary.
>  *
>  * It's also kept as flat as possible (no nested pointers), to make mishandling it during
> ```

What do you mean by `no nested pointers`?
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N032tvG9ZpuFuLG6taK:b-n5vhs9) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
> ```C
> }
> 
> // Not suitable for untrusted inputs! (due to overflows and liberal parsing)
> ```

I thought that all functions in this file are used on trusted data/files?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 148 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00yqS51gjehvRvCF7f:-N037zvPEECLbAgkwg_U:br0sdl9) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but the old version required such checks due to its design (problems with int overflows everywhere).
Not sure whether we actually want to check such things, technically having more threads is valid and topology libraries should support it well. Same with cache types or levels, socket counts and many more.

@boryspoplawski: Do you think it's worth capping these to some hardcoded limits?
</blockquote></details>

If there is no problem security-wise (i.e. this code can correctly handle cases like 1 core with 1024 threads), I wouldn't bother.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N038yiL3ypg2NTufhhX:b-e06mjc) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the idea is to keep this code easy to review, not just review it once in a single point in time and then make it less verifiable. I think this is a place where it's better to not follow our wrapping rules.
</blockquote></details>

I wouldn't call this readable: 
![screen.png](https://files.reviewableusercontent.io/images/reviewable/5228082/pJbOZMGet3XSHmqpKPpdO76w/screen.png)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N033xzW06X9Etk0ZiT8:bxa2lrq) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/ [...]

2022-04-20 06:50 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 36 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N04b6ZG3bNZCBRLkHQN:b-ousur0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Well, the main question is -- do any real-world applications rely on this "socket-local" `coreid` as implemented in Linux on "normal platforms" (I guess this "socket-local" logic in Linux is for x86-64 machines).

I don't think so, it's probably a raw value extracted from ACPI tables and vendor-specific in practice.

> I guess just running OpenVINO and PyTorch should be enough to check this?

@dimakuv: Do you know who to ask to test these? I know you had/have some users of them, so they could try some real workloads on this PR.
</blockquote></details>

@vijaydhanraj Could you try OpenVINO? I also asked others to test this PR.

---
___
*[Documentation/manifest-syntax.rst, line 879 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02jYmb5xisL85RT4Gx:-N04c8GX9wPJMN_djiGm:b-yp5uqq) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L879)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we should keep this disabled for now and enable once we are sure everything is ok (e.g. once we have a proper test suite and we run multiple real life workloads on different cpu configurations).
</blockquote></details>

That's what we are currently doing (running this PR on many configs).
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00A2Rv7l0sNstuSWQ6:-N04cRYa-0AvpyiPLNOI:b-gfehmf) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know... This was a part of the PR where I got really stuck because of this clash of the names and I still have no idea how to fix it. Unfortunately I can't use `cache_type_level`, because this is _not_ the cache level - same as with "type", we already have a "level" field in the cache struct, and it's different than this index (consider L1i and L1d).
</blockquote></details>

Yeah, I understand. But we need at least some way of differentiation -- right now we have two different things with the exact same name `cache_type`.
- Either rename this field to `cache_kind` or `cache_class`
- Or rename the enum to `cache_type_str`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N04cuWIDcseurEuRe8Z:b-20rioc) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is `ind`? If that's an abbreviation for `index`, then I think standard ones are `i`, `id` and `idx`. Never seen `ind`.
</blockquote></details>

We have `i` for loops, `id` for IDs, and `idx` for non-callback variables. So at least from the perspective of "unique names", `ind` was fine with me.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DS094MjqrsgDdyn3:-N04j0W9EUuRXrJ0_mU9:bt3fzaq) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but I didn't care about this much in 2/3 lines-long functions, as it's obvious there. I can unify one way or the other, but let's wait for @pwmarcz input on this to not do it twice.
</blockquote></details>

It was pretty hard to review this PR because of this.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00F9Hd60KSf3sOyNJR:-N04dUva5lCJn1TA5pR2:btlehia) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, that happens if writing something takes so much time, hard to be consistent :)
@pwmarcz: What's your preference? I also like `thread`.
</blockquote></details>

I should note that in the PAL layer (during parsing and sanitization), Michal uses `thread` as well. So I vote for this one.
___
*[LibOS/shim/src/fs/sys/fs.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N007h0b2v-cQlw3FKnq:-N04do8D0bxLK_ZQCY3g:bgozj66) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to change.
</blockquote></details>

I still prefer this change, so +1.
___
*[LibOS/shim/src/fs/sys/node_info.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Z97b4skwHsJ8PipL:-N04eHQLCdvVzI5uel1X:b-7wusti) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/node_info.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I already have exactly this at `numa_distance_matrix`'s declaration. Should I also add it here?
</blockquote></details>

Actually, ignore me. It doesn't deserve the comment. After reading this PR once completely, I don't have problems with this code.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N04edgV7kbaw2a6-YTY:bua95vy) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But is it actually correct? Doesn't "cache IDs" mean "a bunch of IDs of one, particular cache" and "caches IDs" mean "a bunch of IDs of a bunch of caches"? I admit I quite struggle with this pattern in English, maybe our native could comment on this? :) /summon @donporter
</blockquote></details>

Good point. I'm find then with the current (weird) version, because now I'll always remember that it is "IDs of different caches".
___
*[Pal/include/arch/x86_64/pal_topology.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00fCpuAc14cgvrGurP:-N04exiK5yPGTYXbU_ze:b-n3tpst) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The threads in pal_topo_info must correspond to the host threads exactly (otherwise our sched_setaffinity() won't work correctly)

Not really, we could e.g. have a translation layer and this way remove the need for `is_online` fields entirely. And `sched_setaffinity()` would use it to translate the mapping to the right host ID.

I'd rather keep such a comment in _some_ version, because IMO it's an important distinction that we keep threads and nodes 1-1 with the host, but not other parts.

Maybe @pwmarcz has an idea how to wri [...]

2022-04-20 06:55 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @vijaydhanraj)

___
*[Documentation/manifest-syntax.rst, line 871 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jpWU-TkGbBy03XaK:-N04jpWU-TkGbBy03XaL:b-htnwya) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L871)):*
> ```reStructuredText
> replaced with the ``fs.mounts`` TOML array.
> 
> Experimental sysfs topology support
> ```

Maybe also add `(deprecated syntax)`, for uniformity with the above one?
___
*[Documentation/manifest-syntax.rst, line 877 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jmzD8xp3GJh4YFL1:-N04jmzD8xp3GJh4YFL2:b-54twmx) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L877)):*
> ```reStructuredText
> 
>     fs.experimental__enable_sysfs_topology = [true|false]
>     (Default: false)
> ```

It was pointed out to me that this `Default` is confusing; if you skim through the documentation, you may get a feeling that sysfs enablement is false -- and people love to skim through documentation :)

I suggest we just remove this line?


<!-- Sent from Reviewable.io -->

2022-04-20 11:31 UTC, pwmarcz approved these changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

___
*[Documentation/manifest-syntax.rst, line 871 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jpWU-TkGbBy03XaK:-N05IB1t0Qk3q5V5I12S:b-4yuync) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L871)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe also add `(deprecated syntax)`, for uniformity with the above one?
</blockquote></details>

+1, I'd also add that it will make this section easier to understand out of context (without seeing the "Deprecated options" header above).
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00F9Hd60KSf3sOyNJR:-N05IzVs4fToW_Oj_f6t:bnoj676) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should note that in the PAL layer (during parsing and sanitization), Michal uses `thread` as well. So I vote for this one.
</blockquote></details>

`thread` sounds good - it might be misleading in a wider codebase (that actually handles LibOS threads), but it'd be a "local" convention here.

If you want to be consistent, then also `topo_info` -> `topo`, etc.?
___
*[LibOS/shim/src/fs/sys/fs.c, line 59 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N007h0b2v-cQlw3FKnq:-N05JkkO8bEWhW7UJ5_Q:boq385v) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/fs.c#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still prefer this change, so +1.
</blockquote></details>

I did say "with error handling" :) I still think it's a good idea.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N05KJKaCwpJO-RtrKJA:bfr70as) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good point. I'm find then with the current (weird) version, because now I'll always remember that it is "IDs of different caches".
</blockquote></details>

That's not a natural reading for me, probably since I don't expect one object to have multiple IDs. Generally, I'd expect a name like `foos` to mean an array of multiple `foo` objects, and `foo_ids` to mean an array of IDs of multiple `foo` objects.

But my objection is mostly because a name with double plural is more suprising and easier to get wrong (and there's nothing really "exceptional" about this case that would justify it).
___
*[Pal/include/arch/x86_64/pal_topology.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00fCpuAc14cgvrGurP:-N05MGkjCG7P42A9tF-i:bjrkdqe) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I agree with the possible "translation layer", at which point my logic will become invalid. I'm resolving my comment.
</blockquote></details>

It's confusing to see this comment for cores and sockets, but nothing for threads and NUMA nodes. It *suggests* that they are numbered the same as on host, but you cannot confirm that by looking at this file.

So, I suggest a corresponding comment for these, e.g. "Threads are currently numbered the same as on host." Alternatively, you can add comments above fields of main struct (`pal_topo_info`), so that it's easier to read it all.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 76 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00gJqG0YqOFV5cVa0a:-N05P0Oh03sRLBvSkno1:blpvdie) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add something like `normalized (i.e., with no data redundancy), to ensure ...`? The "normalized" word by itself doesn't lead to assosiations with database normalization, at least for me.
</blockquote></details>

My attempt to make this clearer:

"""
We store the processor topology in a series of flat arrays, and use IDs (array indices) for relationships between objects, much like in a relational database. This serves two purposes:

* There's no data redundancy, so it's easier to verify the data when crossing untrusted -> trusted boundary.

* There are no nested pointers, so it's harder to mishandle the data during sanitization. To copy the data, you just need to copy all the arrays.
"""
___
*[Pal/src/host/Linux-common/topo_info.c, line 30 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00C_c65yhM2wOi27LB:-N05XK6l3xrcbivmBlOT:b-q7rcfo) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-common/topo_info.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wasn't sure what to do here, the problem with `str_to_ulong()` is that it accepts `0x` prefix which we don't expect here. So, both ways seemed imperfect, and this code works on trusted data, so I just decided to leave it as is. But I can change it if you prefer `str_to_ulong()` with its problems.
</blockquote></details>

The prefix is accepted only for base 16, though? And we expect base 10 here.

I think `str_to_ulong` would be slightly better (you get to skip the check for empty string, i.e. `buf == end`) but I'm not blocking.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00KJRY1oMa2Yn1kmDj:-N05jGtE0d11MOHDeoeS:b-vs1pr4) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's definitely expected, at least for me. I still can't make any sense of this 10 I see there. Added a clarification, is it better now?
</blockquote></details>

Looks good.


<!-- Sent from Reviewable.io -->

2022-04-20 16:36 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N06DuvH97LP5GeK9JXP:b-5fzzpy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj Could you try OpenVINO? I also asked others to test this PR.
</blockquote></details>

I did look at `hwloc` code which is used by `OpenVINO` and they use `core_id` to identify sibling threads. This is under the assumption that `core_id` of the sibling threads is always between the siblings. Based on this they create a core object with all the sibling threads. 

I haven't completely finished looking at the PR, but I see that the same `core_id` is being assigned to sibling threads.

But I am not sure how other Linux libraries/apps may use the `core_id`. For example, there could be a usage scenario where a library or app could use `core_id` to detect the number of sockets. This might not crash the application but could impact performance which is hard to catch just by running any application unless someone has profiled the application. 

Why not read the `/sys/devices/system/cpu/cpuX/topology/core_id` and set as the `core_id`? There is a check for this anyway in the trusted PAL.

---


<!-- Sent from Reviewable.io -->

2022-04-21 01:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 11 of 20 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N08BOwFCGT4dwZTftww:bw2i7yo) (no related file):*
> I did look at `hwloc` code which is used by `OpenVINO` and they use `core_id` to identify sibling threads. This is under the assumption that `core_id` of the sibling threads is always between the siblings. Based on this they create a core object with all the sibling threads.

Could you point me to relevant places in their code? Sounds suspicious, as Linux explicitly documents this as a hw/platform specific ID. Also, what do you mean by "is always between the siblings", precisely?

> Why not read the `/sys/devices/system/cpu/cpuX/topology/core_id` and set as the `core_id`? There is a check for this anyway in the trusted PAL.

I didn't do this exactly because Linux docs said that I shouldn't do it :) But the situation gets more complicated if some popular libraries are abusing this interface.

---
___
*[Documentation/manifest-syntax.rst, line 871 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jpWU-TkGbBy03XaK:-N05h_aq-s_iZigBHGOg:bgirqbv) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L871)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

+1, I'd also add that it will make this section easier to understand out of context (without seeing the "Deprecated options" header above).
</blockquote></details>

But waaait, the note above is not what you (I think) think it is - it's clarifying that this is a deprecation of this particular syntax (and not `fs.mount` itself). Here the case is different, we're removing the whole option.

IMO this section is short enough that the readers will always see that big "Deprecated options" heading when reading these points.
___
*[Documentation/manifest-syntax.rst, line 877 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jmzD8xp3GJh4YFL1:-N05htDX7a3vmfiuxID4:bfbq99i) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L877)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It was pointed out to me that this `Default` is confusing; if you skim through the documentation, you may get a feeling that sysfs enablement is false -- and people love to skim through documentation :)

I suggest we just remove this line?
</blockquote></details>

Good point, done.
___
*[Documentation/manifest-syntax.rst, line 879 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02jYmb5xisL85RT4Gx:-N05iLW4AR0dkXZuJJ1T:buv58fu) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L879)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's what we are currently doing (running this PR on many configs).
</blockquote></details>

@boryspoplawski: That was my original plan, but after finishing the implementation it turned out that it's actually more tolerant for weird configs than the old one (modulo internally inconsistent / impossible ones), so I think we can enable it by default after some more testing (which is happening right now).
___
*[LibOS/shim/src/fs/proc/info.c, line 167 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02mUHd6Toqj7An8NF0:-N05jDS90Qb5jSGWk2-Z:bmwwn2b) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/proc/info.c#L167)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are two statements (albeit nested), so I would prefer braces, at least around `for`.
Not blocking as we have no clear code guidelines for this case. I personally prefer braces everywhere (even in single statement if/for).
</blockquote></details>

Added, although I prefer to not have them on one-liners. Compilers nowadays warn if you accidentally write things like:
```C
if (...)
    asdf;
    qwer;
```

so it's not as unsafe as it was in the old days.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00A2Rv7l0sNstuSWQ6:-N05mOUc7bXRPHrZKqWv:bydmhv7) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I understand. But we need at least some way of differentiation -- right now we have two different things with the exact same name `cache_type`.
- Either rename this field to `cache_kind` or `cache_class`
- Or rename the enum to `cache_type_str`
</blockquote></details>

`cache_class` seems less bad, done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N0072Qp8McNOc04iKuj:-N08EF454Dulbx5PmdP3:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`ti` -> `thread`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N05n6afEFFbb-3RoZvg:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this suppose to be? I mean, it's unreachable, but there is code behind it...
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DS094MjqrsgDdyn3:-N08F-P-AiVt0ZCTIxsU:b-ilp660) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It was pretty hard to review this PR because of this.
</blockquote></details>

Done (although here the code you wanted me to change was removed in the meantime).
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 28 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00DVD46xOVsKzFtwm3:-N08F94I1fkTLVH8-ywa:b-omnmto) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have a convension of calling this variable `ti`.
</blockquote></details>

Done (differently, see the discussion).
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 49 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00EQxJEk68WXx_96WN:-N08Frs_1fBW-ej1YKzP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`ti` -> `thread`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00ET9a8s4DFwoQynvk:-N08Fu9oDQYmhHo [...]

2022-04-21 06:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 11 of 20 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N09aVBO0dFDrv-7j5YV:bh6y7ed) (no related file):*
https://github.com/open-mpi/hwloc/blob/master/hwloc/topology-linux.c#L4526. Please look from line 4514.
Here is an old github link talking about this change, https://github.com/open-mpi/hwloc/commit/21472ebd675862c2c092dc5e6dbfabbcbbbbe03c, and how they differentiate between x86 and AMD.

> what do you mean by "is always between the siblings"

Sorry, this is a typo, I meant
` This is under the assumption that core_id of the sibling threads is always the same`. The word "same" was missed earlier.

> gets more complicated if some popular libraries are abusing this interface.

Many might not know they are incorrectly using it. For them, Linux is the standard reference :)

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N09hEMWE1nLnWsKTB7j:b-2axgnk) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> ```objc
>      * offline cores and thus skip `is_online` here. */
> 
>     size_t socket_id;
> ```

Why not move this variable to the `pal_cpu_thread_info` struct? This tells which socket (physical_id) the thread/core belongs to, right?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N08rITRAnbEDH2DCQYv:b-7p6s22) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
> ```objc
> // TODO: move info from struct pal_cpu_info to here
> struct pal_socket_info {
>     /* We have our own numbering of sockets (not taken from the host), so we can just ignore
> ```

Why do we say our own numbering of sockets? From the code, it looks like we are emulating Linux.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08lpg-Dk863EqXgy9y:-N08lpg-Dk863EqXgy9z:b-of6vb2) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L65)):*
> ```objc
>      * offline sockets and thus skip `is_online` from here. */
> 
>     size_t node_id;
> ```

wait why do we want to store NUMA `node_id` is stored in a socket struct?
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N08305i19_j1ba8S4Fn:b-tpht7l) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but this one is especially liberal, like the lack of checking whether in `A-B` form `A < B`.
</blockquote></details>

But the input `/sys/devices/system/..` paths on the host are untrusted right?
___
*[Pal/src/host/Linux-common/topo_info.c, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08WDf18wtJJ7SI8TMY:-N08WDf18wtJJ7SI8TMZ:b-wxg4rc) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L98)):*
> ```C
>             } else {
>                 // range
>                 for (size_t i = prev; i <= (size_t)val; i++) {
> ```

Should we fail for improper ranges like `1, 2, 7-3` instead of continuing?
___
*[Pal/src/host/Linux-common/topo_info.c, line 205 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08VBPdBoVSSJrtAX6L:-N08VBPdBoVSSJrtAX6M:bni2zdl) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L205)):*
> ```C
> }
> 
> static int get_ranges_end(size_t ind, void* _arg) {
> ```

This might incorrectly calculate the count if we have complex ranges like 1,5-7,8?
___
*[Pal/src/host/Linux-common/topo_info.c, line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09lTPw3E63hJ1yWImG:-N09lTPw3E63hJ1yWImH:b-6w7ga0) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L255)):*
> ```C
> static int set_cache_id(size_t ind, void* _args) {
>     struct set_cache_id_args* args = _args;
>     if (!args->threads[ind].is_online)
> ```

Isn't this check redundant?
___
*[Pal/src/host/Linux-common/topo_info.c, line 272 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09j0wx7j5J7Ghou2_8:-N09j0wx7j5J7Ghou2_9:b1al0e9) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L272)):*
> ```C
>     if (!args->threads[thr_ind].is_online)
>         return 0;
>     args->sockets[args->cores[args->threads[thr_ind].core_id].socket_id].node_id = args->id_to_set;
> ```

The naming is incorrect. Sockets and NUMA nodes are different. One socket could have many NUMA nodes when sub-numa clustering is enabled.
Please see this fig, https://www.open-mpi.org/projects/hwloc/lstopo/images/2XeonSPv2+msc.v2.1.png
___
*[Pal/src/host/Linux-common/topo_info.c, line 278 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08gE050ZcLq27ucnkr:-N08gE050ZcLq27ucnks:b-84art8) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L278)):*
> ```C
> int get_topology_info(struct pal_topo_info* topo_info) {
>     size_t threads_cnt = 0;
>     int ret = iterate_ranges_from_file("/sys/devices/system/cpu/possible", get_ranges_end, &threads_cnt);
> ```

It would be better to use the count from `/sys/devices/system/cpu/online` to allocate resources like cache, cores, and sockets as they are valid only if the core is online.
___
*[Pal/src/host/Linux-common/topo_info.c, line 314 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09naDI27-HwnG2pIiq:-N09naDI27-HwnG2pIir:bykoy3t) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L314)):*
> ```C
>     ret = iterate_ranges_from_file("/sys/devices/system/cpu/online", set_thread_online, threads);
>     if (ret < 0)
>         return ret;
> ```

goto fail?
___
*[Pal/src/host/Linux-common/topo_info.c, line 318 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09ncPM6wJfMvf83f52:-N09ncPM6wJfMvf83f53:bykoy3t) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L318)):*
> ```C
>                                    numa_nodes);
>     if (ret < 0)
>         return ret;
> ```

goto fail?


<!-- Sent from Reviewable.io -->

2022-04-21 08:40 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 871 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N04jpWU-TkGbBy03XaK:-N0AE1at51m_AK5nVoZ_:b32w0x) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Documentation/manifest-syntax.rst#L871)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But waaait, the note above is not what you (I think) think it is - it's clarifying that this is a deprecation of this particular syntax (and not `fs.mount` itself). Here the case is different, we're removing the whole option.

IMO this section is short enough that the readers will always see that big "Deprecated options" heading when reading these points.
</blockquote></details>

OK
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 85 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00FjfVCPuzwkSESW3F:-N0AElTN2K5dX4H_W86E:bwogloq) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done (but using Paweł's suggestion, still open to discussion if you don't like it).
</blockquote></details>

No, I actually like Pawel's suggestion. Reads much better now.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N0AGSc22jscKrGGySkB:b-r5tcbq) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For this single part you're supposed to expand your wrap-ruler a bit ;)

> I don't see how readability worsens when these lines are wrapped.

This is how:
```C
    struct pal_cache_info*      caches     = sgx_import_array_to_enclave(shallow_topo_info.caches,
                                                                         sizeof(*caches),
                                                                         caches_cnt);
    struct pal_cpu_thread_info* threads    = sgx_import_array_to_enclave(shallow_topo_info.threads,
                                                                         sizeof(*threads),
                                                                         threads_cnt);
    struct pal_cpu_core_info*   cores      = sgx_import_array_to_enclave(shallow_topo_info.cores,
                                                                         sizeof(*cores),
                                                                         cores_cnt);
    struct pal_socket_info*     sockets    = sgx_import_array_to_enclave(shallow_topo_info.sockets,
                                                                         sizeof(*sockets),
                                                                         sockets_cnt);
    struct pal_numa_node_info*  numa_nodes = sgx_import_array_to_enclave(
        shallow_topo_info.numa_nodes, sizeof(*numa_nodes), numa_nodes_cnt);
```

or

```C
    struct pal_cache_info* caches = sgx_import_array_to_enclave(
        shallow_topo_info.caches, sizeof(*caches), caches_cnt);
    struct pal_cpu_thread_info* threads = sgx_import_array_to_enclave(
        shallow_topo_info.threads, sizeof(*threads), threads_cnt);
    struct pal_cpu_core_info* cores = sgx_import_array_to_enclave(
        shallow_topo_info.cores, sizeof(*cores), cores_cnt);
    struct pal_socket_info* sockets = sgx_import_array_to_enclave(
        shallow_topo_info.sockets, sizeof(*sockets), sockets_cnt);
    struct pal_numa_node_info* numa_nodes = sgx_import_array_to_enclave(
        shallow_topo_info.numa_nodes, sizeof(*numa_nodes), numa_nodes_cnt);
```

When it's a single line you just read it as a table where only `caches` -> `threads` -> `cores` -> `sockets` -> `numa_nodes` word should change and it's very easy too see that there aren't any other accidental changes nor a change missing (this code is super repetitive, so I could have accidentally left some reference to `threads` in the `cores` line).

Anyways, if you really don't like it I can change it. But for me in the current version it's super obvious that there aren't any copy-paste errors, and in none of the above ones it is (I'd need to read them slowly one by one and diff with each other).
And this is a security-critical part, it should be as simple as possible to reason about it.
</blockquote></details>

Well, your first wrapping snippet is very easy to read for me. So I'd prefer that. Let's see what @boryspoplawski and @pwmarcz think.


<!-- Sent from Reviewable.io -->

2022-04-21 12:03 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0AqgX_4kc5gaJrJaI4:b-88v5xl) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have `i` for loops, `id` for IDs, and `idx` for non-callback variables. So at least from the perspective of "unique names", `ind` was fine with me.
</blockquote></details>

I just don't see the need for another one. What do you mean by "`idx` for non-callback variables"? 
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N0AqMem7se2GA9VKxVX:b71biz4) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Wouldn't just omitting `default` have the same effect?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ArRUM27G-d_M2ukes:-N0ArRUM27G-d_M2uket:b-hcg6vc) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/LibOS/shim/src/fs/sys/cpu_info.c#L33)):*
> ```C
> 
>     if (strcmp(name, "online") == 0) {
>         ret = sys_print_as_ranges(str, sizeof(str), topo->threads_cnt, is_online, NULL);
> ```

From what I can see, `sys_print_as_ranges` now doesn't use callback args anymore. Maybe there is some room for simplification?
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0AucoJ5bGgI6OtGUIf:bhuakry) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

But the input `/sys/devices/system/..` paths on the host are untrusted right?
</blockquote></details>

@mkow but this doesn't really affect the fact that **all** of these functions are suitable for trusted data only. It just reads weirdly, like some previous function **was** suitable for untrusted stuff.
___
*[Pal/src/host/Linux-common/topo_info.c, line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Au3yIAhdWbzMNcx7-:-N0Au3yJCItn5t4O2nAY:b-u4ukp7) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/Pal/src/host/Linux-common/topo_info.c#L25)):*
> ```C
> 
>     ssize_t ret = DO_SYSCALL(read, fd, buf, count);
>     DO_SYSCALL(close, fd);
> ```

We should check the retval here as well and have this cumbersome logic of what to do on double-errors which never happen in practice :)
___
*[Pal/src/host/Linux-common/topo_info.c, line 98 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0AwXd62ymUb54RH-pU:-N0AwXd62ymUb54RH-pV:bao1gt5) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/Pal/src/host/Linux-common/topo_info.c#L98)):*
> ```C
>         const char* parse_end;
>         unsigned long val;
>         ret = str_to_ulong(buf_it, 10, &val, &parse_end);
> ```

This is slightly different from the old version in that it will error out once we reach the end of the string (even if something before was parsed correctly). But I see you've also added a check for a newline in the loop. Does that mean that the buffer always ends with `\n` and we not need to worry here about buffer ending?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N0Azm8CE-d7QiV4kgnH:bwcbph8) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, your first wrapping snippet is very easy to read for me. So I'd prefer that. Let's see what @boryspoplawski and @pwmarcz think.
</blockquote></details>

I like the first snippet as well (optionally joining the 2nd and 3rd line, idk if it would be better).

How I verify these lines is check that variable name matches the type and then verify that variable name matches the function parameters. For the first part these are all equivalent, but for the second the current sparse version is worse. Theoretically the 2nd snipped would be the best for that, but it looks so weird that it's harder for me to read.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N0Ax9QKDCxoa7JWNGRV:b-2n6ufy) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-SGX/db_main.c#L119)):*
> Nope, AFAIR there's an if for unsigned char in the standard, so the current version is equivalent to your suggestion no. 2.

Ah, right, brain lags...

> although it doesn't have security implications here, it 

I think it does, because the compiler might decide to do nothing here e.g. if the byte falue is `0x11`, because it's already a valid `true`. Of course that's a far fetched example.


Idk what to do. Maybe just `*(unsigned char*)ptr &= 1;`?


<!-- Sent from Reviewable.io -->

2022-04-21 12:06 UTC, pwmarcz reviewed
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 73 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00F9Hd60KSf3sOyNJR:-N0Axpdr6neGnfYzMZQb:bkxh51k) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cpu_info.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.

> If you want to be consistent, then also `topo_info` -> `topo`, etc.?

This is a bit different case, because `topo_info` is a field name in `g_pal_public_state`, which is global and we need a more precise name. So, the places which use `topo_info` local are just 1-1 mirroring the field name.
Despite this I changed it in some places, please take a look.
</blockquote></details>

Ah, right, `topo` is the main structure, and the others are individual objects. I don't mind either way.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 55 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00fCpuAc14cgvrGurP:-N0AyGTe-esWEVrJ953c:b-vs1pr4) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done, although I prefer to keep the comments at the structures, because the ones about the lack of `is_online` fields wouldn't make sense at `pal_topo_info`. But maybe I just misunderstood your proposal ;)
</blockquote></details>

Looks good.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0AydIC93x02cNVLZxj:bc9l3jc) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why not move this variable to the `pal_cpu_thread_info` struct? This tells which socket (physical_id) the thread/core belongs to, right?
</blockquote></details>

To keep data consistentx - if it's in thread, then two threads belonging to the same core could belong to different sockets (and we'd have to either allow it, or add more validation).
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0AzATX7IZUyCKYxFtC:b-ay40po) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

But the input `/sys/devices/system/..` paths on the host are untrusted right?
</blockquote></details>

We're running this in URTS / outer PAL, so from this code's perspective these files are trusted (and inner PAL will validate the parsed result).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N0B-BZGCo05asWv1-n7:b-w7q294) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I like the first snippet as well (optionally joining the 2nd and 3rd line, idk if it would be better).

How I verify these lines is check that variable name matches the type and then verify that variable name matches the function parameters. For the first part these are all equivalent, but for the second the current sparse version is worse. Theoretically the 2nd snipped would be the best for that, but it looks so weird that it's harder for me to read.
</blockquote></details>

PR version looks OK, *second* example from comment looks OK, I don't like the *first* example from comment (especially since it looks like `numa_nodes` breaks past the column limit anyway).


<!-- Sent from Reviewable.io -->

2022-04-22 00:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 19 of 20 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N0Af6b782mfyJOSdU6-:bavobgm) (no related file):*
>  `This is under the assumption that core_id of the sibling threads is always the same`. The word "same" was missed earlier.

But it _is_ the same for sibling threads right now?

> Many might not know they are incorrectly using it. For them, Linux is the standard reference :)

But it is Linux which forbids this. If it's a reference and they rely on the numbers being socket-local, then they aren't really taking Linux as a reference, rather some specific hardware.

> https://github.com/open-mpi/hwloc/blob/master/hwloc/topology-linux.c#L4526. Please look from line 4514.
Here is an old github link talking about this change, open-mpi/hwloc@21472eb, and how they differentiate between x86 and AMD.

I don't see anything wrong in this code, they seem to use `core_id` correctly? I.e. only for comparison whether two threads belong to the same core, not as any index in something.

---
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N0BYdM_BSOmLei9EjWT:b-fvh53r) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wouldn't just omitting `default` have the same effect?
</blockquote></details>

Nope, without `default` it would be legal for the code to not hit any of the cases, and with it the compiler can assume that it's not possible. And in more practical terms, things like UBSAN will emit `fail()` here.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ArRUM27G-d_M2ukes:-N0BZHzr-d5J632vL2S_:b-vxsj4c) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/LibOS/shim/src/fs/sys/cpu_info.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

From what I can see, `sys_print_as_ranges` now doesn't use callback args anymore. Maybe there is some room for simplification?
</blockquote></details>

Hmm, I could remove it, but I think that:
- it's likely that we will need it back soon when adding more files to our emulated sysfs (we only have a few right now)
- it's a pattern we use in many other places for lambda-like constructs (callback func + `void*` arg for it)

Not saying no, but what @dimakuv and @pwmarcz think?
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N0Ar98d-bD7Qp79mRX-:b-sq7kx2) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why do we say our own numbering of sockets? From the code, it looks like we are emulating Linux.
</blockquote></details>

Linux doesn't have any numbering of the sockets exposed in sysfs, I think.
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0Dc7W6712V-C5mIapR:b-5mpl2u) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We're running this in URTS / outer PAL, so from this code's perspective these files are trusted (and inner PAL will validate the parsed result).
</blockquote></details>

@boryspoplawski: So, what do you propose? IMO it would be good to somehow highlight this function as "more unsafe" than others, just in case it gets reused somewhere else. But I'm not gonna die on this hill, if you insist I can just drop this comment ;)
___
*[Pal/src/host/Linux-common/topo_info.c, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08WDf18wtJJ7SI8TMY:-N0AxxwP1jILo34dF52h:b-ozqew4) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L98)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Should we fail for improper ranges like `1, 2, 7-3` instead of continuing?
</blockquote></details>

No, the inputs are trusted, we don't have to check them.
___
*[Pal/src/host/Linux-common/topo_info.c, line 205 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08VBPdBoVSSJrtAX6L:-N0Ay8R5Cc8Cgi2y2LMu:b50p3x8) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L205)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This might incorrectly calculate the count if we have complex ranges like 1,5-7,8?
</blockquote></details>

But it doesn't calculate the count, it looks for the end of all the ranges (as its name indicates).
___
*[Pal/src/host/Linux-common/topo_info.c, line 255 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09lTPw3E63hJ1yWImG:-N0Ayn9U8BCozDmJQQ4Y:b-hn1ppj) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L255)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Isn't this check redundant?
</blockquote></details>

Right, removed.
___
*[Pal/src/host/Linux-common/topo_info.c, line 278 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08gE050ZcLq27ucnkr:-N0DcZViC7jptRjAzHm2:btu12dr) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L278)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

It would be better to use the count from `/sys/devices/system/cpu/online` to allocate resources like cache, cores, and sockets as they are valid only if the core is online.
</blockquote></details>

I wouldn't bother, this would add more code and almost never provide any benefit - usually you don't have any threads taken offline. Better to just wait for realloc implementation. Also, see the comment at the end - the difference in size is really negligible.
___
*[Pal/src/host/Linux-common/topo_info.c, line 314 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09naDI27-HwnG2pIiq:-N0DdFDg73tRiHICWE3z:b-8ouz0j) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L314)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

goto fail?
</blockquote></details>

Good catch, too much copy-paste.
___
*[Pal/src/host/Linux-common/topo_info.c, line 318 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09ncPM6wJfMvf83f52:-N0DdHEfCzzCYTM7in7K:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L318)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

goto fail?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c [...]

2022-04-22 06:07 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 19 of 20 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N0Eo4uB3M7THmaTTil9:b-a29yvl) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  `This is under the assumption that core_id of the sibling threads is always the same`. The word "same" was missed earlier.

But it _is_ the same for sibling threads right now?

> Many might not know they are incorrectly using it. For them, Linux is the standard reference :)

But it is Linux which forbids this. If it's a reference and they rely on the numbers being socket-local, then they aren't really taking Linux as a reference, rather some specific hardware.

> https://github.com/open-mpi/hwloc/blob/master/hwloc/topology-linux.c#L4526. Please look from line 4514.
Here is an old github link talking about this change, open-mpi/hwloc@21472eb, and how they differentiate between x86 and AMD.

I don't see anything wrong in this code, they seem to use `core_id` correctly? I.e. only for comparison whether two threads belong to the same core, not as any index in something.
</blockquote></details>

yes, `hwloc` isn't misusing it. But I'm not sure how others might perceive the `core_id` interpretation. Anyways if this is the way we want, I am fine.

---
___
*[Pal/include/arch/x86_64/pal_topology.h, line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0EpM0A8UeZ324btzN-:b-y6d5t6) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> if it's in thread, then two threads belonging to the same core could belong to different sockets 

why? I understand this struct holds information about all threads (logical processors) present in the system and the socket_id is thread-specific information.

Also, socket_id is computed based on `core_siblings_list` which does include thread siblings as well. So not sure we need any additional checks.
```
cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list                                                                                                                                          
0-31,64-95
```
```
cat /sys/devices/system/cpu/cpu0/topology/thread_siblings_list                                                                                                                                        
0,64
```
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N0Eiax08vu-ZqtCY-v6:bj5610i) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Linux doesn't have any numbering of the sockets exposed in sysfs, I think.
</blockquote></details>

They do have `/sys/devices/system/cpu/cpuX/topology/physical_package_id` which corresponds to a physical socket number, but the actual value is architecture and platform dependent.
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0C9MkKExyfyGNM0RUo:bszqmsb) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We're running this in URTS / outer PAL, so from this code's perspective these files are trusted (and inner PAL will validate the parsed result).
</blockquote></details>

hmm but I am not sure about this liberal parsing. For example, `possible` cpus could result in `thread_cnt` being 10,000,000 which can also pass the overflow check in trusted PAL but not sure if it is valid. So, my thought is why proceed to trusted PAL if we already know in untrusted PAL of insane inputs.
___
*[Pal/src/host/Linux-common/topo_info.c, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08WDf18wtJJ7SI8TMY:-N0Eluwl6U5p4-7C9TDZ:b-1lwx6i) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, the inputs are trusted, we don't have to check them.
</blockquote></details>

Sorry, I don't understand. Aren't we reading and operating on string values from the host `/sys/..` path? How is this trusted?
___
*[Pal/src/host/Linux-common/topo_info.c, line 205 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08VBPdBoVSSJrtAX6L:-N0EmeVz6ObPTKf6kNnX:b-od4apg) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L205)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it doesn't calculate the count, it looks for the end of all the ranges (as its name indicates).
</blockquote></details>

But isn't the usage to find the count of `possible` cores? I think the assumption here is end of range + 1 is the total count of the resource. This can be incorrect if we have ranges as shown in the example.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0CJb25DoRO1b3M28mE:b-7vri1x) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
> ```C
>     struct pal_topo_info* topo_info = &g_pal_public_state.topo_info;
> 
>     size_t caches_cnt     = shallow_topo_info.caches_cnt;
> ```

Any reason to remove the range checks for the count variables? We could end up with insanely high values for the count.


<!-- Sent from Reviewable.io -->

2022-04-22 07:02 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02-U3m3ubfnNSq6nwR:-N0F1fcmBFZnIojTlM76:b-dfoqui) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thanks! Yes, these tests are very strict about the host machine and often doesn't work.
</blockquote></details>

I tested this PR on an SGX-enabled VM that looks like this:
```
$ hwloc-ls
Machine (15GB total)
  NUMANode L#0 (P#0 15GB)
  Package L#0 + L3 L#0 (16MB) + L2 L#0 (4096KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  Package L#1 + L3 L#1 (16MB) + L2 L#1 (4096KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  Package L#2 + L3 L#2 (16MB) + L2 L#2 (4096KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  Package L#3 + L3 L#3 (16MB) + L2 L#3 (4096KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  Package L#4 + L3 L#4 (16MB) + L2 L#4 (4096KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
  Package L#5 + L3 L#5 (16MB) + L2 L#5 (4096KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
  Package L#6 + L3 L#6 (16MB) + L2 L#6 (4096KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
  Package L#7 + L3 L#7 (16MB) + L2 L#7 (4096KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
```

As you can see, this is the "weird" topology, with one CPU core per package (socket). But all of them belong to the same NUMA node.

This PR works as expected. I tested some benchmarks and looked at `/sys/` directories and files manually via busybox.

---
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0F2Po4CAZZ2cdUBbho:b2sn09g) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
> What do you mean by "idx for non-callback variables"?

Just that Michal used `idx` for "big" functions, and used some other name (`pos`, `ind`) for these small callback functions. Not sure if Michal did this on purpose though :)
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 33 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ArRUM27G-d_M2ukes:-N0F2vw5EoHkv19u7aA5:b-4w7kjj) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/LibOS/shim/src/fs/sys/cpu_info.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I could remove it, but I think that:
- it's likely that we will need it back soon when adding more files to our emulated sysfs (we only have a few right now)
- it's a pattern we use in many other places for lambda-like constructs (callback func + `void*` arg for it)

Not saying no, but what @dimakuv and @pwmarcz think?
</blockquote></details>

Yes, we should keep the last argument. Even if only for uniformity with the rest of the code (especially with `sys_print_as_bitmask()`).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N0F3zGjDMKGkqdZ0MUr:b-9vds0m) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, so we have a tie here?
</blockquote></details>

I am resolving my comment. Not too important for me, so as others choose.


<!-- Sent from Reviewable.io -->

2022-04-22 08:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N-wqX7v4jVmkdTaseqn:-N0FEVuf47an7ctkqd8W:b-h7p1lw) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, `hwloc` isn't misusing it. But I'm not sure how others might perceive the `core_id` interpretation. Anyways if this is the way we want, I am fine.
</blockquote></details>

If no popular library is abusing this interface then the current version is fine.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02-U3m3ubfnNSq6nwR:-N0FEsYYCG5ptB12Z5mG:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tested this PR on an SGX-enabled VM that looks like this:
```
$ hwloc-ls
Machine (15GB total)
  NUMANode L#0 (P#0 15GB)
  Package L#0 + L3 L#0 (16MB) + L2 L#0 (4096KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  Package L#1 + L3 L#1 (16MB) + L2 L#1 (4096KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  Package L#2 + L3 L#2 (16MB) + L2 L#2 (4096KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  Package L#3 + L3 L#3 (16MB) + L2 L#3 (4096KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  Package L#4 + L3 L#4 (16MB) + L2 L#4 (4096KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
  Package L#5 + L3 L#5 (16MB) + L2 L#5 (4096KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
  Package L#6 + L3 L#6 (16MB) + L2 L#6 (4096KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
  Package L#7 + L3 L#7 (16MB) + L2 L#7 (4096KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
```

As you can see, this is the "weird" topology, with one CPU core per package (socket). But all of them belong to the same NUMA node.

This PR works as expected. I tested some benchmarks and looked at `/sys/` directories and files manually via busybox.
</blockquote></details>

Thanks!

---
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0FF1AJ0c6rVVpERGmN:b-vyjejd) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> What do you mean by "idx for non-callback variables"?

Just that Michal used `idx` for "big" functions, and used some other name (`pos`, `ind`) for these small callback functions. Not sure if Michal did this on purpose though :)
</blockquote></details>

Hmm, I think I did this rather accidentally, or for some indirect causes ;)
___
*[Pal/include/arch/x86_64/pal_topology.h, line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0AqppA9OPP0c4wc_zb:bocs9ir) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> socket_id is computed based on `core_siblings_list`

It completely doesn't matter how is it retrieved on the untrusted host. This code receives a pointer to `pal_topo_info` in unstrusted memory and has to somehow deal with it.

> socket_id is thread-specific information

Rather core-specific?

Anyways, as Paweł said, if we'd do as you say then you'd introduce redundancy / violate normalized form of the data. It would make it possible to have two sibling threads belonging to different sockets, which should be impossible, so we'd need to manually check for this case, making sanitization more complex.
See https://en.wikipedia.org/wiki/Database_normalization.
___
*[Pal/include/arch/x86_64/pal_topology.h, line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N0FGA4HDHSFHe_x1iOB:b9au98k) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

They do have `/sys/devices/system/cpu/cpuX/topology/physical_package_id` which corresponds to a physical socket number, but the actual value is architecture and platform dependent.
</blockquote></details>

`physical_package_id` is a hardware ID, not Linux numbering, and it doesn't have to be any nice "index".
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0FGTqQ4uSxMtUZPt3x:b-1gayel) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

hmm but I am not sure about this liberal parsing. For example, `possible` cpus could result in `thread_cnt` being 10,000,000 which can also pass the overflow check in trusted PAL but not sure if it is valid. So, my thought is why proceed to trusted PAL if we already know in untrusted PAL of insane inputs.
</blockquote></details>

But here we are in untrusted part, whatever we check here doesn't matter at all for the enclave.
___
*[Pal/src/host/Linux-common/topo_info.c, line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08WDf18wtJJ7SI8TMY:-N0FGpDNEM64_GRwYxkC:b-coty9s) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L98)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, I don't understand. Aren't we reading and operating on string values from the host `/sys/..` path? How is this trusted?
</blockquote></details>

From the perspective of this code it's trusted. Same as we don't verify here whether the syscalls we call don't try to hack us somehow, because here we are in ordinary, non-enclave code.
___
*[Pal/src/host/Linux-common/topo_info.c, line 205 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08VBPdBoVSSJrtAX6L:-N0FHGoT3QmCmiRT1g7z:bakk74q) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L205)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

But isn't the usage to find the count of `possible` cores? I think the assumption here is end of range + 1 is the total count of the resource. This can be incorrect if we have ranges as shown in the example.
</blockquote></details>

No, this is used just to cap the allocation of the arrays. If `possible` is missing some indices then they will be exposed as offline inside the LibOS (because `online` has to be a subset of `possible`).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0FHuoxBvPZzRZFuagm:b-ajdma4) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Any reason to remove the range checks for the count variables? We could end up with insanely high values for the count.
</blockquote></details>

There was a discussion about this already somewhere in this review and we decided that if we don't know any concrete example why this would be a  [...]

2022-04-22 12:01 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0Fz7vdAmG4lQJwIfzg:b26gfir) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I think I did this rather accidentally, or for some indirect causes ;)
</blockquote></details>

So if there isn't any specific reasoning behind this, I wouldn't introduce another abbreviation (`ind`) since the usual would work.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N0FzL0h7tSXJp365Ozn:b2xdvin) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
> Nope, without default it would be legal for the code to not hit any of the cases, and with it the compiler can assume that it's not possible.

That's nonsense. You've literally told the compiler that it can **never** hit `default` here. It will just remove this whole case.
___
*[Pal/src/host/Linux-common/topo_info.c, line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0G6MPU9GP1sRzChXlx:b-yqltbt) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But here we are in untrusted part, whatever we check here doesn't matter at all for the enclave.
</blockquote></details>

@mkow I would either put some comment on the top of this file or simply remove this one - it doesn't really add any information, just confuses (I dislike the notion of "more unsafe" :) )
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N-oT1xQ7dv4DlWvoYeQ:-N0G7cfE7b4qbEeJnkCA:b-q5tv6q) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/src/host/Linux-SGX/db_main.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am resolving my comment. Not too important for me, so as others choose.
</blockquote></details>

Ok, I'm resolving as well, since there is no clear winner.


<!-- Sent from Reviewable.io -->

2022-04-26 07:38 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0ZmqVh4FAkuqQCiqXa:bfxp1uv) (no related file):*
I tried offling one node completely and see enclave create failing. This is not related to this PR but with this PR we do have an opportunity to test this configuration.
```
Config:
NUMA node0 CPU(s):    0-31,64-95
NUMA node1 CPU(s):
```

```
Error:
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: ECREATE failed in enclave creation ioctl (errno = -14)
error: Creating enclave failed: -14
error: load_enclave() failed with error -14
```

@mkow @dimakuv have you tried this config to be working?

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0ZbfWz5xBnXq09iFux:bzgkc89) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
> ```C
>         }
>     } else if (strcmp(name, "size") == 0) {
>         ret = snprintf(str, sizeof(str), "%zuK\n", cache->size >> 10);
> ```

Cache size is multiplied by `1024` only if `K` unit is present but here we append `K` by default.
1. Either we fix this to follow the untrusted PAL logic Or
2. Change untrusted PAL to make sure `K` is always present when reading cache size.

Based on kernel documentation, https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu, size is always is expressed in `KB` so my preference is 2.
```		
size:
	the total cache size in kB
```
___
*[`LibOS/shim/src/fs/sys/fs.c` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Zdxc93quGy3uvnwsZ:-N0Zdxc93quGy3uvnws_:b-zcpd8o) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/fs.c#L27)):*
> ```C
>         size_t range_end = i; // exclusive
> 
>         if (range_start == range_end)
> ```

when do we hit this case?
___
*[`LibOS/shim/src/fs/sys/fs.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Ze89G3ub97KS9SvPi:-N0Ze89G3ub97KS9SvPj:byyrtj2) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/fs.c#L43)):*
> ```C
>         buf_pos += ret;
>     }
>     if (buf_pos + 2 > buf_size)
> ```

A comment would be better as to why we are adding `2` and checking for overflow but not blocking.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0ZVg_52VPaGvTuMGX8:bahy8br) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
> ```C
>     size_t core_id   = g_pal_public_state->topo_info.threads[pos].core_id;
>     size_t socket_id = g_pal_public_state->topo_info.cores[core_id].socket_id;
>     size_t node_id   = g_pal_public_state->topo_info.sockets[socket_id].node_id;
> ```

Here the assumption is that there is only one node inside a socket. This might not be true for the sub-numa clustering case.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0YTD3vEowP_zgfxSpn:b-mrm5p6) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> Rather core-specific?

The reason I said it is thread-specific is we can just offline sibling threads and the socket information is still available for the other sibling when we do `/proc/cpuinfo`.

> It would make it possible to have two sibling threads belonging to different sockets

How about something like the below? With this, we can ensure a thread is present only in one socket as we have `threads[i].socket_id == (size_t)-1` check.
```
        if (threads[i].socket_id == (size_t)-1) {
            /* Insert new socket to the list. */
            snprintf(path, sizeof(path),
                     "/sys/devices/system/cpu/cpu%zu/topology/core_siblings_list", i);
            ret = iterate_ranges_from_file(path, set_socket_id, &(struct set_socket_id_args) {
                .threads = threads,
                .id_to_set = sockets_cnt,
            });
            if (ret < 0)
                goto fail;
            sockets_cnt++;
        }
```

In the trusted PAL, the verification remains the same, that is check against `sockets_cnt` just that instead of looping over `cores_cnt` we loop over `threads_cnt`.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N0Ra5dfANOFUF2CPrQL:b-fi8dpz) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`physical_package_id` is a hardware ID, not Linux numbering, and it doesn't have to be any nice "index".
</blockquote></details>

OK, we can leave it, but typically they start from `0 until n-1 sockets`
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XrINq6RoXaDlUrVFJ:-N0XrINq6RoXaDlUrVFK:b-cp6uu7) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/include/arch/x86_64/pal_topology.h#L14)):*
> ```objc
> /* Used to represent buffers having numeric values and unit suffixes if present, e.g. "1024576K".
>  * NOTE: Used to allocate on stack; increase with caution or use malloc instead. */
> #define PAL_SYSFS_BUF_FILESZ (256+2)
> ```

out of curiosity why `256+2` and not `258`? Also, can we just round it to something like `300`? `258` seems oddly specific to a particular path.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0XqLF65qcMrSaCnx_f:b6m8ugo) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
> ```C
>         numa_nodes[i].is_online = false;
> 
>     ret = iterate_ranges_from_file("/sys/devices/system/cpu/online", set_thread_online, threads);
> ```

Can buffer overflow occur with the following scenario? Say for example, `possible` cores are `0-5` and `online` cores are `0-100`, we could write beyond the allocated buffer.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 316 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqUm08CBYXfHmgjUc:-N0XqUm08CBYXfHmgjUd:b-op8ti6) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L316)):*
> ```C
>     if (ret < 0)
>         goto fail;
>     ret = iterate_ranges_from_file("/sys/devices/system/node/online", set_numa_node_online,
> ```

buffer overflow?
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0ZNbvQ3xPqhcCxFZxQ:bfidfdm) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There was a discussion about this already somewhere in this review and we decided that if we don't know any concrete example why this would be a problem,  [...]

2022-04-26 07:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N02-U3m3ubfnNSq6nwR:-N0ZroNL87D2p0uN9w2j:b-88j3kw) (no related file):*
One more update, from Jinen:

> we ran OpenVino with the PR and we didn’t notice any degradation as compared to the perf numbers from Gramine 1.1.

So everything looks good, in terms of performance.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0ZrzVq6aDw_HLxopUy:b-5ol88u) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I tried offling one node completely and see enclave create failing. This is not related to this PR but with this PR we do have an opportunity to test this configuration.
```
Config:
NUMA node0 CPU(s):    0-31,64-95
NUMA node1 CPU(s):
```

```
Error:
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: ECREATE failed in enclave creation ioctl (errno = -14)
error: Creating enclave failed: -14
error: load_enclave() failed with error -14
```

@mkow @dimakuv have you tried this config to be working?

</blockquote></details>

I never tried to offline one NUMA node.

But this happens even on master Gramine, right? This `ECREATE failed` error implies that the problem is not even with Gramine, but with the Intel SGX driver. At least I can't imagine why Gramine would fail at this point (even before the enclave is created).

---


<!-- Sent from Reviewable.io -->

2022-04-26 15:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0aQIm23o1km5tpbbkH:bqhj8td) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I never tried to offline one NUMA node.

But this happens even on master Gramine, right? This `ECREATE failed` error implies that the problem is not even with Gramine, but with the Intel SGX driver. At least I can't imagine why Gramine would fail at this point (even before the enclave is created).
</blockquote></details>

Not on master Gramine as we currently don't support core offling but once we have the PR merged it might crop up.
But yes, agree that this isn't related to Gramine but Intel SGX driver.

I just wanted to confirm with everyone before raising an issue in the SGX Linux kernel mailing list.

---


<!-- Sent from Reviewable.io -->

2022-04-27 13:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N02oDlK-9fqBbEETef7:-N0fDuT2AFIfte8itmTk:bdlb4v2) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/LibOS/shim/src/fs/sys/cache_info.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Nope, without default it would be legal for the code to not hit any of the cases, and with it the compiler can assume that it's not possible.

That's nonsense. You've literally told the compiler that it can **never** hit `default` here. It will just remove this whole case.
</blockquote></details>

Ah, nevermind


<!-- Sent from Reviewable.io -->

2022-04-27 14:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0fA1dG4GX0ichdCAbi:b-czwsd0) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So if there isn't any specific reasoning behind this, I wouldn't introduce another abbreviation (`ind`) since the usual would work.
</blockquote></details>

Please decide on something with @dimakuv (and maybe others) and I'll do the change, as I don't have any strong preference here.
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0fFkJ_7X13JfpzmADb:bpul1d3) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
> only if `K` unit is present

present where? I append "K" here, so the printed result is correct.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Zdxc93quGy3uvnwsZ:-N0fJdSUAflEBVKFPvR_:bv40l28) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/fs.c#L27)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

when do we hit this case?
</blockquote></details>

When `i < count && is_present(i, callback_arg)` was false before the first iteration.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 43 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Ze89G3ub97KS9SvPi:-N0fK-Q09Pk6Xn6_cAvN:bc2218r) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/fs.c#L43)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

A comment would be better as to why we are adding `2` and checking for overflow but not blocking.
</blockquote></details>

IMO too trivial for a comment, you literally have these 2 bytes filled below, right after this `if`.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0fOsi1B-8ZR9unPg0B:b2xmuyu) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> The reason I said it is thread-specific is we can just offline sibling threads and the socket information is still available for the other sibling when we do `/proc/cpuinfo`.

Did you actually verify this? What's wrong with the current `/proc/cpuinfo` contents?

> How about something like the below? With this, we can ensure a thread is present only in one socket as we have `threads[i].socket_id == (size_t)-1` check.

Why would I change the data structure, just to be forced to add those 10 lines of sanitization code? The only difference is that with your version I need more sanitization logic.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 62 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08rITRAnbEDH2DCQYu:-N0fPjGUCKq4Pv4VS6-X:b-pedvqp) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L62)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, we can leave it, but typically they start from `0 until n-1 sockets`
</blockquote></details>

Where "typically" means "on the hardware we tested, but the documentation says that you shouldn't rely on this".
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XrINq6RoXaDlUrVFJ:-N0fNVhs0ndofd-IkoaN:bv5wcom) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/include/arch/x86_64/pal_topology.h#L14)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

out of curiosity why `256+2` and not `258`? Also, can we just round it to something like `300`? `258` seems oddly specific to a particular path.
</blockquote></details>

To mark that the 2 bytes are for the newline and nullbyte. I'm neutral on this, if you really don't like the current form then I can change it.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0fQDOz2jl1DHxq3k8A:b2nhky0) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can buffer overflow occur with the following scenario? Say for example, `possible` cores are `0-5` and `online` cores are `0-100`, we could write beyond the allocated buffer.
</blockquote></details>

No.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 316 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqUm08CBYXfHmgjUc:-N0fQJsWCphk-kXq7i74:b2nhky0) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L316)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

buffer overflow?
</blockquote></details>

No.
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0fRQoy6FskkHekumaK:b-jh01m0) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Say the untrusted host is able to manipulate the `cores_cnt` (`cores` buffer is allocated based on this count) and sets it to a small value but`core_id` is much greater. Given this, can we run into a buffer overrun for the below case?
`&topo_info->cores[thread_info->core_id];`
</blockquote></details>

And where do we do this `&topo_info->cores[thread_info->core_id];`?
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1896 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZRowE3DsAKp2_nSrJ:-N0fTB6s0RCKmLODJ6qu:b8pmwm4) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1896)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Can `threads_cnt` be manipulated and change the `invalid_bits` resulting in affinitizing threads to different cores? We are using `threads_cnt` without any sanitization here.
</blockquote></details>

? The untrusted host can set affinity however it wants to.


<!-- Sent from Reviewable.io -->

2022-04-27 14:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0fV_Bb0fahJx589lvP:boycs3) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please decide on something with @dimakuv (and maybe others) and I'll do the change, as I don't have any strong preference here.
</blockquote></details>

Ok, then I vote for `idx`.


<!-- Sent from Reviewable.io -->

2022-04-27 15:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 17 of 20 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0fZWfR8kCnD99sBoqv:b-4mr08n) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Not on master Gramine as we currently don't support core offling but once we have the PR merged it might crop up.
But yes, agree that this isn't related to Gramine but Intel SGX driver.

I just wanted to confirm with everyone before raising an issue in the SGX Linux kernel mailing list.
</blockquote></details>

How did you manage to offline a whole node?
Anyways, this doesn't seem to be a problem with the current implementation but with the driver.

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0fenbX16qVGdmxCel1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, then I vote for `idx`.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N032tvG9ZpuFuLG6taJ:-N0fbfU894C0JD8Oblqm:bdtfnuz) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@mkow I would either put some comment on the top of this file or simply remove this one - it doesn't really add any information, just confuses (I dislike the notion of "more unsafe" :) )
</blockquote></details>

Ok, moved to the top.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 25 at r3](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Au3yIAhdWbzMNcx7-:-N0fbJL-C9r1Gpj_5kk2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a850e978e7fe93c3d6cfe7864eff878c5c694f55/Pal/src/host/Linux-common/topo_info.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should check the retval here as well and have this cumbersome logic of what to do on double-errors which never happen in practice :)
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N0fc1Sd1xRsMgfV7fp1:bga5sja) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-SGX/db_main.c#L119)):*
> Idk what to do. Maybe just `*(unsigned char*)ptr &= 1;`?

This doesn't work if `true` is `0x10` ;) I'm afraid there's no good solution here :/ Maybe I'll just assert for 0 and 1, so we will be able to notice weird compiler+platform combinations?


<!-- Sent from Reviewable.io -->

2022-04-27 20:10 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 17 of 20 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0gc2fC5tvxYRIOd--O:bkdhpzj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How did you manage to offline a whole node?
Anyways, this doesn't seem to be a problem with the current implementation but with the driver.
</blockquote></details>

No, I didn't offline a node but all the cores in a node. Basically, an empty node. Before raising an issue with the 
Linux driver, want to make sure if someone else can repro the issue.

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0fcH3eAR20Q8pdmeiU:b-elnzve) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> only if `K` unit is present

present where? I append "K" here, so the printed result is correct.
</blockquote></details>

In `get_hw_resource_value()` there is a check like below which multiplies by `1024` only if `K` is present.
```
    if (*end == 'K') {
        if (__builtin_mul_overflow(val, 1024, &val))
            return -EOVERFLOW;
    }

```

But here you seem to be always dividing by `1024`. What if the size didn't have a `K` unit?

So that is why suggested approach 2, where we fail if `K` unit is not present in `cache_size` and this part of the code remains valid.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0Zdxc93quGy3uvnwsZ:-N0gBaKr4QMA6QyUET9y:be4761s) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/fs.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

When `i < count && is_present(i, callback_arg)` was false before the first iteration.
</blockquote></details>

Thanks, got it. This will hit when `online` cores are`0-126` and `possible` cores are `0-127`.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0gSG5z8HbM2pYFGNW6:bhy83dr) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> Did you actually verify this? What's wrong with the current /proc/cpuinfo contents?

Yes I did, but the point I am trying to make is not the contents of /proc/cpuinfo` are displayed correctly or incorrectly` but `socket_id` is represented for a thread even if its sibling is disabled. This shows `socket_id` isn't core specific but a thread.

Siblings for threads `32-63` are removed.
```
NUMA node0 CPU(s):    0-31,64-95
NUMA node1 CPU(s):    32-63
```

> Why would I change the data structure,

Why add a struct when it is not needed?

> The only difference is that with your version I need more sanitization logic.

In the current implementation, the only check we have is against the `socket_cnt` right? This could be retained when the `socket_id` is moved to `pal_cpu_thread_info` from `pal_cpu_core_info`. 

If the question is how to ensure that 2 thread siblings don't show different `socket_id`, won't a check `threads[i].socket_id == (size_t)-1` like this help? I think this is the same logic you apply to ensure that 2 cores belonging to the same socket don't show different `socket_id`
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XrINq6RoXaDlUrVFJ:-N0gJUlxA4gCjCyIqht3:bqrsclx) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/include/arch/x86_64/pal_topology.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To mark that the 2 bytes are for the newline and nullbyte. I'm neutral on this, if you really don't like the current form then I can change it.
</blockquote></details>

Yes, please change and may also increase the buffer size may to `300`?
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0gWj-Z9pJR-aZp9Am3:bk61ke8) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No.
</blockquote></details>

This is a case where the untrusted host has modified the contents of `/sys/devices/system/cpu/possible` to show `0-5` but `/sys/devices/system/cpu/online` still shows `0-100`. 

In this scenario, `threads_cnt` would be `6` and we would malloc(6 * sizeof(*threads) but `set_thread_online()` can index any value from `0-100` in `threads` array.

Can you please explain? 
___
*[`Pal/src/host/Linux-common/topo_info.c` line 316 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqUm08CBYXfHmgjUc:-N0gYiRH2hCv47JUiter:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L316)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No.
</blockquote></details>

ditto
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0gZPs6EqFQ6OLXUngQ:b-2weuze) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
> topo_info->cores[thread_info->core_id]

Not sure if this link works for you, https://github.com/gramineproject/gramine/pull/530/files#diff-81c3b4d88c8cb35eadac14e576da8ece5f7251e59e23b3dfab634a4d40dee98aR89

But this is done in `sys_cpu_load_topology()`
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1896 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZRowE3DsAKp2_nSrJ:-N0gblhR7mDfQrK8fFO2:b-hbzzja) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1896)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

? The untrusted host can set affinity however it wants to.
</blockquote></details>

OK, got it.


<!-- Sent from Reviewable.io -->

2022-04-27 21:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 16 of 20 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0h-ZCE0cNFwDPOUxbK:b-kznobl) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, I didn't offline a node but all the cores in a node. Basically, an empty node. Before raising an issue with the 
Linux driver, want to make sure if someone else can repro the issue.
</blockquote></details>

But this doesn't offline a node. I tried the same and Linux showed this node as online, just without any CPUs.

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0gwxrn7_JZAZm0sOFv:b-1t3jlj) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

In `get_hw_resource_value()` there is a check like below which multiplies by `1024` only if `K` is present.
```
    if (*end == 'K') {
        if (__builtin_mul_overflow(val, 1024, &val))
            return -EOVERFLOW;
    }

```

But here you seem to be always dividing by `1024`. What if the size didn't have a `K` unit?

So that is why suggested approach 2, where we fail if `K` unit is not present in `cache_size` and this part of the code remains valid.
</blockquote></details>

`cache->size` is always in bytes. I don't understand the problem here.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0gxCiRE_jVjLj6Cr9E:b-l5pqgg) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here the assumption is that there is only one node inside a socket. This might not be true for the sub-numa clustering case.
</blockquote></details>

Hmm, interesting. Do you maybe have a server+kernel supporting this? Was this already upstreamed in Linux? I'd like to see what sysfs shows in this case.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0gzIVw66j3XW10m8YI:b-79fmkn) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> but `socket_id` is represented for a thread even if its sibling is disabled. This shows `socket_id` isn't core specific but a thread.

? The reasoning used here doesn't make any sense to me.

> Why add a struct when it is not needed?

It's here to make the sanitization trivial.

> I think this is the same logic you apply to ensure that 2 cores belonging to the same socket don't show different `socket_id`

The very point of this whole data structure construction is that _there's no logic_ in the sanitizer, only checking if the indices are valid. The rest is enforced by the data format.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XrINq6RoXaDlUrVFJ:-N0gxXh_DsBQFT5_VBKV:b22bbp) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/include/arch/x86_64/pal_topology.h#L14)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, please change and may also increase the buffer size may to `300`?
</blockquote></details>

Why 300? It's not "round", 256 or 512 is round. I'll use 512, as these sometimes may be big when threads are offlined.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0gyY8aD8V_cut176YU:b9pi3n0) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is a case where the untrusted host has modified the contents of `/sys/devices/system/cpu/possible` to show `0-5` but `/sys/devices/system/cpu/online` still shows `0-100`. 

In this scenario, `threads_cnt` would be `6` and we would malloc(6 * sizeof(*threads) but `set_thread_online()` can index any value from `0-100` in `threads` array.

Can you please explain? 
</blockquote></details>

Vijay, this code runs _outside the enclave_. Why would the host kernel attack it?
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0gyuny0SN1ZRzVdv22:b777mm1) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> topo_info->cores[thread_info->core_id]

Not sure if this link works for you, https://github.com/gramineproject/gramine/pull/530/files#diff-81c3b4d88c8cb35eadac14e576da8ece5f7251e59e23b3dfab634a4d40dee98aR89

But this is done in `sys_cpu_load_topology()`
</blockquote></details>

But `sys_cpu_load_topology()` is always called after we already did `sanitize_topo_info()`.


<!-- Sent from Reviewable.io -->

2022-04-27 22:24 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 22 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Cusb9OKW7c2w6w75:-N0h3rIZ8ODYDS87uWmU:bu6puzc) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FWIW: for me `pos` was fine, just `ind` seemed weird and unnecessary. Anyway, looks good
___
*[`Pal/src/host/Linux-common/topo_info.c` line 27 at r7](https://reviewable.io/reviews/gramineproject/gramine/530#-N0h54Hm7n_jdNVSsbvp:-N0h54Hm7n_jdNVSsbvq:bjcc7e3) ([raw file](https://github.com/gramineproject/gramine/blob/4ac1bee0dd02702809018840d4ddc6a449fb4eca/Pal/src/host/Linux-common/topo_info.c#L27)):*
> ```C
>     ssize_t ret = DO_SYSCALL(read, fd, buf, count);
>     long close_ret = DO_SYSCALL(close, fd);
>     if (ret == 0 && close_ret < 0)
> ```

I think we usually do `!ret`, but if you did this intentionally, I'm fine, not blocking here.
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N0h5_6630pDcpQh4cTt:b-tdpklj) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-SGX/db_main.c#L119)):*
> This doesn't work if true is 0x10 

But `true` must be `1` (that's in standard, I believe).


<!-- Sent from Reviewable.io -->

2022-04-27 23:50 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`Pal/src/host/Linux-SGX/db_main.c` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N0hQ75N8eVKVRmoPnzw:b7x76k8) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-SGX/db_main.c#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This doesn't work if true is 0x10 

But `true` must be `1` (that's in standard, I believe).
</blockquote></details>

As discussed on gitter, `!!READ_ONCE` should do the trick here


<!-- Sent from Reviewable.io -->

2022-04-28 00:04 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 19 of 20 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

___
*[`Pal/src/host/Linux-common/topo_info.c` line 27 at r7](https://reviewable.io/reviews/gramineproject/gramine/530#-N0h54Hm7n_jdNVSsbvp:-N0hTkl4EDEHxhX6jCf-:b-um50qz) ([raw file](https://github.com/gramineproject/gramine/blob/4ac1bee0dd02702809018840d4ddc6a449fb4eca/Pal/src/host/Linux-common/topo_info.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think we usually do `!ret`, but if you did this intentionally, I'm fine, not blocking here.
</blockquote></details>

Yeah, I slightly prefer this version.
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 119 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N033xzW06X9Etk0ZiT7:-N0hTfUW1ka9uON66mCn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-SGX/db_main.c#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As discussed on gitter, `!!READ_ONCE` should do the trick here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-28 00:07 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-28 00:07 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-28 03:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 11 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0i2mcx2dP_S8Iye0Vh:b-uxs6ik) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this doesn't offline a node. I tried the same and Linux showed this node as online, just without any CPUs.
</blockquote></details>

Yes, this doesn't offline the nodes, it simply makes the node empty with no cores. Did you run into the enclave creation failure when using an empty node config with this PR?

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0i3Sh77d66uNR87M5t:b-xhfqrx) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cache->size` is always in bytes. I don't understand the problem here.
</blockquote></details>

In untrusted PAL, when reading the cache size we honor `K` unit suffix and multiply the value read by 1024. This is done only if `K` suffix is present.

But in trusted PAL as indicated here, the code assumes we have multiplied by `1024` and so divides the value by `1024` and appends `K` suffix. This is incorrect if the cache size didn't have `K` suffix in the first place.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0hoiPQ8trSzb5XN4pV:b-afvlpe) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, interesting. Do you maybe have a server+kernel supporting this? Was this already upstreamed in Linux? I'd like to see what sysfs shows in this case.
</blockquote></details>

I don't but I have sent you the contact who was testing this configuration with Gramine.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0hpyQd9M74S5I2Ql0w:bekrx05) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
The current structure is built under the assumption that associates `socket_id` with a core. I am trying to understand why not associate it with a thread as apps usually use logical processors (that is hardware threads).

> The very point of this whole data structure construction is that there's no logic in the sanitizer, only checking if the indices are valid. The rest is enforced by the data format.

Even in the approach suggested, the construction of `socket_id` is just the same as it was before. It makes sure that for a given thread index, the socket info is not populated before setting its value and so we rule out 2 sibling threads having different `socket_id`. Isn't logic the same as with core? So, why will this make the sanitization more complex? Checking the indices should suffice here as well.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 14 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XrINq6RoXaDlUrVFJ:-N0hotvR1RNlSKaC4jYI:bcprese) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/include/arch/x86_64/pal_topology.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why 300? It's not "round", 256 or 512 is round. I'll use 512, as these sometimes may be big when threads are offlined.
</blockquote></details>

sure, `512` works too. Just wanted to round it off.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0huz6V0tZEDEZS2KE3:b-1uh23l) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Vijay, this code runs _outside the enclave_. Why would the host kernel attack it?
</blockquote></details>

We are not sure to what extent the host will be comprised, right? So why expose things like these? Isn't it better to keep the attack surface minimal?
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0i2P5R8I24izdUVMes:b-silsey) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But `sys_cpu_load_topology()` is always called after we already did `sanitize_topo_info()`.
</blockquote></details>

That is the whole point, we don't sanitize the count variables. We simply use the value passed from the untrusted host.  


<!-- Sent from Reviewable.io -->

2022-04-28 07:18 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0is3fvBTzr2umxLVFj:bgfg1od) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
> This is incorrect if the cache size didn't have K suffix in the first place.

@vijaydhanraj What do you mean? We have the following invariants in this code:
1. Gramine always keeps `cache->size` in bytes (not KBs).
2. Gramine always prints the cache size with the `K` suffix.

To enforce 1, Gramine will check for suffix `K` on the host: if there is a suffix, Gramine will save the number from the host as-is, if there is no suffix, Gramine will multiply this number by 1024.

To enforce 2, Gramine always divides `cache->size` by 1024.

I see no problem.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0itWFX-hYYeuh691If:b-llikmq) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I don't but I have sent you the contact who was testing this configuration with Gramine.
</blockquote></details>

Btw, we can add a TODO/XXX note in the header with topo info definitions about this. Just to proceed further with this PR.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0iuh2P3qncYbkgY_eV:bcnlrow) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The current structure is built under the assumption that associates `socket_id` with a core. I am trying to understand why not associate it with a thread as apps usually use logical processors (that is hardware threads).

> The very point of this whole data structure construction is that there's no logic in the sanitizer, only checking if the indices are valid. The rest is enforced by the data format.

Even in the approach suggested, the construction of `socket_id` is just the same as it was before. It makes sure that for a given thread index, the socket info is not populated before setting its value and so we rule out 2 sibling threads having different `socket_id`. Isn't logic the same as with core? So, why will this make the sanitization more complex? Checking the indices should suffice here as well.





</blockquote></details>

I also don't understand @vijaydhanraj's points. We have these two options:
1. Current one, with associations `thread -> core` and `core -> socket`
2. Vijay's proposed one, with associations `thread -> core` and `thread -> socket`

On a theoretical level, the second option is wrong because it doesn't follow normalization rules (i.e., it adds redundancy).

On a pratical level, it means that the second option -- as Pawel mentioned -- allows for 2 sibling threads to belong to the same core (i.e., two siblings) but at the same time to belong to 2 different sockets. At our struct representation level, it would look like this:
- `thread1 -> core1` and `thread1 -> socket1`
- `thread2 -> core1` and `thread2 -> socket2`

This assosiation is possible with the second option, and is impossible with the first option. Obviously, this assosiation doesn't make practical sense -- it is impossible for one physical CPU core to belong to two different sockets at the same time.

That's why the first option (currently implemented by Michal) is preferred. The structure itself doesn't allow for such a corner case to occur.

The reasoning that "apps usually use logical processors" is irrelevant here.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08lpg-Dk863EqXgy9y:-N0iwpVt13YOT51BFdl2:bcht2a7) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L65)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

wait why do we want to store NUMA `node_id` is stored in a socket struct?
</blockquote></details>

I guess here you're talking about the possibility of Sub NUMA Clustering? You raised this issue in another thread, so I suggest to resolve this thread (and concentrate our discussions in the other one).
___
*[`Pal/src/host/Linux-common/topo_info.c` line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08WDf18wtJJ7SI8TMY:-N0ixhdR9XzaPggNa_sj:b-riictu) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

From the perspective of this code it's trusted. Same as we don't verify here whether the syscalls we call don't try to hack us somehow, because here we are in ordinary, non-enclave code.
</blockquote></details>

Just to make it clear.

1. This particular function is used to read untrusted values from the untrusted host.
2. Later the results of this function are verified and sanitized, when these results are copied into the enclave.

Only step 2 needs to have validations and checks. Step 1 is purely "untrusted work on untrusted values", so we just don't care about having checks and validations at this step 1.

Another way to think of it: this function is executed in out-of-enclave untrusted world. So the malicious OS could anyway change this function's execution in any way, including skipping some code or skipping the whole function entirely. There is no sense in adding checks to this code if the malicious OS can simply tweak the `RIP` register to jump over them.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 272 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09j0wx7j5J7Ghou2_8:-N0iy_iG89y_3Bu61HIR:b-pgqeii) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/src/host/Linux-common/topo_info.c#L272)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The naming is incorrect. Sockets and NUMA nodes are different. One socket could have many NUMA nodes when sub-numa clustering is enabled.
Please see this fig, https://www.open-mpi.org/projects/hwloc/lstopo/images/2XeonSPv2+msc.v2.1.png

</blockquote></details>

Let's resolve this comment and keep the discussion on Sub NUMA Clustering in a single thread (above).
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0iypmzDvxBhwD1A4Lp:bazda5q) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
@vijaydhanraj I agree that having some sanity checks (like checking for error codes on function returns) is meaningful even in untrusted code. Simply because such situations are possible on a benign host (e.g., the host may be genuinely out of physical memory, or some file may be genuinely corrupted on the hard drive).

But adding complex checks to verify *all possible behaviors* is counter-productive. There is no situation when a benign Linux kernel re [...]

2022-04-28 10:51 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 12 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0jloQz2dnvY2H0Ppya:b-dtuwhg) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
> Isn't logic the same as with core? So, why will this make the sanitization more complex? Checking the indices should suffice here as well.

Because in your version this logic has to be added to the sanitization inside enclave, which is security critical. In my approach all the complexity stays outside the enclave and sanitization is trivial.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0jmN6pCM4PNeUGrFGX:b-n6hydv) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
> We are not sure to what extent the host will be comprised, right? So why expose things like these? Isn't it better to keep the attack surface minimal?

No, this is not an attack surface.
Again: why would the kernel attack this code in such a complex way, while it can just overwrite it arbitrarily?


<!-- Sent from Reviewable.io -->

2022-04-28 17:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0l-K6JD-XBcov1hdZo:b6fnxut) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This is incorrect if the cache size didn't have K suffix in the first place.

@vijaydhanraj What do you mean? We have the following invariants in this code:
1. Gramine always keeps `cache->size` in bytes (not KBs).
2. Gramine always prints the cache size with the `K` suffix.

To enforce 1, Gramine will check for suffix `K` on the host: if there is a suffix, Gramine will save the number from the host as-is, if there is no suffix, Gramine will multiply this number by 1024.

To enforce 2, Gramine always divides `cache->size` by 1024.

I see no problem.
</blockquote></details>

My point is we seem to print `K` even if the host didn't have it. Resolving, as this is fine with everyone.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0l-rAM69FnaKM6i2If:brxp9sq) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, we can add a TODO/XXX note in the header with topo info definitions about this. Just to proceed further with this PR.
</blockquote></details>

Sounds good.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 57 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N09hEMWE1nLnWsKTB7i:-N0lH_gB9wols-wSHR3f:bw7vnt3) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L57)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Isn't logic the same as with core? So, why will this make the sanitization more complex? Checking the indices should suffice here as well.

Because in your version this logic has to be added to the sanitization inside enclave, which is security critical. In my approach all the complexity stays outside the enclave and sanitization is trivial.
</blockquote></details>

Thanks, resolving.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 65 at r2](https://reviewable.io/reviews/gramineproject/gramine/530#-N08lpg-Dk863EqXgy9y:-N0l-zZ66tJpqu3jkR26:b7kys2l) ([raw file](https://github.com/gramineproject/gramine/blob/df5464a2abb1c1ba6edc863f81e2490dfd36fdc6/Pal/include/arch/x86_64/pal_topology.h#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess here you're talking about the possibility of Sub NUMA Clustering? You raised this issue in another thread, so I suggest to resolve this thread (and concentrate our discussions in the other one).
</blockquote></details>

yes, resolving this one.
___
*[`Pal/src/host/Linux-common/topo_info.c` line 313 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0XqLF65qcMrSaCnx_e:-N0l0ZTD3iMyIf14C0wS:b-7lishy) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/Pal/src/host/Linux-common/topo_info.c#L313)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We are not sure to what extent the host will be comprised, right? So why expose things like these? Isn't it better to keep the attack surface minimal?

No, this is not an attack surface.
Again: why would the kernel attack this code in such a complex way, while it can just overwrite it arbitrarily?
</blockquote></details>

OK, resolving.
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 224 at r4](https://reviewable.io/reviews/gramineproject/gramine/530#-N0CJb25DoRO1b3M28mD:-N0l1_E87tvE4FgNJF0g:btjkwlq) ([raw file](https://github.com/gramineproject/gramine/blob/2dee65716535874e6e3e7f9388adaaacb6c99105/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj I specified the point where we do a sanitization check of `thread->core_id` regarding `cores_cnt`. This check precludes a buffer overrun as you mentioned. Similarly for other cases, like `caches_cnt`.

What we could have is starvation of memory if say `cores_cnt` is 1,000,000,000. Then the enclave will try to import this enormously huge `cores[]` array, and will run out of memory. Well, this is denial of service / starvation of resources. Intel SGX technology cannot do anything about this case.
</blockquote></details>

Thanks for the pointer, I missed it.


<!-- Sent from Reviewable.io -->

2022-04-28 20:57 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Pal/include/arch/x86_64/pal_topology.h` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N0lxGP_4eG70VOcLi0F:b-j37rcf) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's not a natural reading for me, probably since I don't expect one object to have multiple IDs. Generally, I'd expect a name like `foos` to mean an array of multiple `foo` objects, and `foo_ids` to mean an array of IDs of multiple `foo` objects.

But my objection is mostly because a name with double plural is more suprising and easier to get wrong (and there's nothing really "exceptional" about this case that would justify it).
</blockquote></details>

Haha.  I think this is where an apostrophe is what you want to disambiguate that this is a plural possessive: "caches' ids".  Alas, I don't think apostrophes can be used in C variables. :(


<!-- Sent from Reviewable.io -->

2022-04-29 06:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0o4gY-1RkVJeJIDsvn:bijdt6e) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
> My point is we seem to print K even if the host didn't have it.

The host not having a `K` may indicate two things:
1. The host is buggy but benign -- in this case, it makes sense for Gramine to represent the cache size in a correct format (with a 'K' suffix), ignoring the incorrect format on the host.
2. The host is malicious and skipped `K` on purpose -- this case is indistinguishable from case 1, so Gramine should do the same as in case 1.

The alternative would be for Gramine to fail loudly if it reads a cache size without a `K` from the host. But this is unnecessarily strict, given case 1 is theoretically possible.
___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N0o5I2K8mZK-Kt9uCPt:bohtl2e) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

@mkow Could you add this comment? I hope we'll find a machine soon to test this Sub NUMA Clustering feature.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N0o5T_L7_AXnoDlgGxF:b-mupap8) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Haha.  I think this is where an apostrophe is what you want to disambiguate that this is a plural possessive: "caches' ids".  Alas, I don't think apostrophes can be used in C variables. :(
</blockquote></details>

Looks like `ids_of_caches` is the best option here.


<!-- Sent from Reviewable.io -->

2022-04-29 10:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 15 of 20 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0orB2_ENA-h-zEsR3M:b7vur7j) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, this doesn't offline the nodes, it simply makes the node empty with no cores. Did you run into the enclave creation failure when using an empty node config with this PR?
</blockquote></details>

I did the same (`echo 0 | sudo tee /sys/devices/system/node/node1/cpu*/online`) and everything works.

---
___
*[`LibOS/shim/src/fs/sys/cache_info.c` line 72 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZbfWz5xBnXq09iFuw:-N0lJhdU7Fcd9BITES6x:b-xrbxtz) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/cache_info.c#L72)):*
> My point is we seem to print `K` even if the host didn't have it. Resolving, as this is fine with everyone.

And I don't get what's the problem with this.
___
*[`Pal/include/arch/x86_64/pal_topology.h` line 50 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N00Bs6O3f9P8rEpvvgy:-N0osXFY69VQxLS14P_0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8d1c57d4895c9e853c3f514e8611a982985d6c5e/Pal/include/arch/x86_64/pal_topology.h#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like `ids_of_caches` is the best option here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-29 10:45 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-29 11:05 UTC, dimakuv reviewed
> Reviewed 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-04-29 15:43 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZmqVh4FAkuqQCiqX_:-N0pyV74CsJamociwB56:b-uw887i) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I did the same (`echo 0 | sudo tee /sys/devices/system/node/node1/cpu*/online`) and everything works.
</blockquote></details>

OK, then it may be my setup issue. Thanks for checking. We should be good here.

---


<!-- Sent from Reviewable.io -->

2022-05-02 14:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N140b1-3tABvU-UkeUK:bsk76et) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Could you add this comment? I hope we'll find a machine soon to test this Sub NUMA Clustering feature.
</blockquote></details>

I got a machine with Sub NUMA Clustering feature (SNC). The machine looks like this:
```
$ lscpu
Architecture: x86_64
CPU(s): 224
On-line CPU(s) list: 0-223
Thread(s) per core: 2
Core(s) per socket: 56
Socket(s): 2
NUMA node(s): 8

$ lstopo-no-graphics
Machine (252GB total)
  Package L#0 + L3 L#0 (105MB)
    Group0 L#0
      NUMANode L#0 (P#0 31GB)
      L2 L#0 (2048KB) + L1d L#0 (48KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#112)
        ...
    Group0 L#1
      NUMANode L#1 (P#1 31GB)
      L2 L#14 (2048KB) + L1d L#14 (48KB) + L1i L#14 (32KB) + Core L#14
        PU L#28 (P#14)
        PU L#29 (P#126)
        ...
  ...
  Package L#1 + L3 L#1 (105MB)
    Group0 L#4
      NUMANode L#4 (P#4 31GB)
      L2 L#56 (2048KB) + L1d L#56 (48KB) + L1i L#56 (32KB) + Core L#56
        PU L#112 (P#56)
        PU L#113 (P#168)
        ...
    ...
    Group0 L#6
      NUMANode L#6 (P#6 31GB)
      L2 L#84 (2048KB) + L1d L#84 (48KB) + L1i L#84 (32KB) + Core L#84
        PU L#168 (P#84)
        PU L#169 (P#196)
        ...
    Group0 L#7
      NUMANode L#7 (P#7 31GB)
      L2 L#98 (2048KB) + L1d L#98 (48KB) + L1i L#98 (32KB) + Core L#98
        PU L#196 (P#98)
        PU L#197 (P#210)
        ...

$ cat /sys/devices/system/node/node
node0/ node1/ node2/ node3/ node4/ node5/ node6/ node7/

$ cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

$  cat /sys/devices/system/node/node7/distance
21 21 21 21 12 12 12 10
```

- HelloWorld runs fine in both `gramine-direct` and `gramine-sgx` modes. I actually expected any Gramine workload to fail...

- Busybox: `gramine-direct busybox sh`:
```
cat /sys/devices/system/cpu/online
0-223

cat /sys/devices/system/cpu/cpu0/cache/index0/shared_cpu_map
00000000,00000000,00000000,00010000,00000000,00000000,00000001

cat /sys/devices/system/cpu/cpu0/cache/index3/shared_cpu_map
00000000,000000ff,ffffffff,ffff0000,00000000,00ffffff,ffffffff

cat /sys/devices/system/cpu/cpu1/cache/index0/shared_cpu_map
00000000,00000000,00000000,00020000,00000000,00000000,00000002

cat /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_map
00000000,000000ff,ffffffff,ffff0000,00000000,00ffffff,ffffffff

cat /sys/devices/system/cpu/cpu223/cache/index0/shared_cpu_map
80000000,00000000,00000000,00008000,00000000,00000000,00000000

cat /sys/devices/system/cpu/cpu223/cache/index3/shared_cpu_map
ffffffff,ffffff00,00000000,0000ffff,ffffffff,ff000000,00000000

cat /sys/devices/system/node/online
0-7

cat /sys/devices/system/node/node0/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000  // OH NO

cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

cat /sys/devices/system/node/node1/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000  // OH NO

...

cat /sys/devices/system/node/node6/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000

cat /sys/devices/system/node/node7/cpumap
ffffffff,ffffff00,00000000,0000ffff,ffffffff,ff000000,00000000  // HMMM

cat /sys/devices/system/node/node7/distance
21 21 21 21 12 12 12 10
```

- Busybox: `gramine-sgx busybox sh` -- same as above.


<!-- Sent from Reviewable.io -->

2022-05-02 14:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N144qXJ2-dATcq6wbX6:bro9362) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I got a machine with Sub NUMA Clustering feature (SNC). The machine looks like this:
```
$ lscpu
Architecture: x86_64
CPU(s): 224
On-line CPU(s) list: 0-223
Thread(s) per core: 2
Core(s) per socket: 56
Socket(s): 2
NUMA node(s): 8

$ lstopo-no-graphics
Machine (252GB total)
  Package L#0 + L3 L#0 (105MB)
    Group0 L#0
      NUMANode L#0 (P#0 31GB)
      L2 L#0 (2048KB) + L1d L#0 (48KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#112)
        ...
    Group0 L#1
      NUMANode L#1 (P#1 31GB)
      L2 L#14 (2048KB) + L1d L#14 (48KB) + L1i L#14 (32KB) + Core L#14
        PU L#28 (P#14)
        PU L#29 (P#126)
        ...
  ...
  Package L#1 + L3 L#1 (105MB)
    Group0 L#4
      NUMANode L#4 (P#4 31GB)
      L2 L#56 (2048KB) + L1d L#56 (48KB) + L1i L#56 (32KB) + Core L#56
        PU L#112 (P#56)
        PU L#113 (P#168)
        ...
    ...
    Group0 L#6
      NUMANode L#6 (P#6 31GB)
      L2 L#84 (2048KB) + L1d L#84 (48KB) + L1i L#84 (32KB) + Core L#84
        PU L#168 (P#84)
        PU L#169 (P#196)
        ...
    Group0 L#7
      NUMANode L#7 (P#7 31GB)
      L2 L#98 (2048KB) + L1d L#98 (48KB) + L1i L#98 (32KB) + Core L#98
        PU L#196 (P#98)
        PU L#197 (P#210)
        ...

$ cat /sys/devices/system/node/node
node0/ node1/ node2/ node3/ node4/ node5/ node6/ node7/

$ cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

$  cat /sys/devices/system/node/node7/distance
21 21 21 21 12 12 12 10
```

- HelloWorld runs fine in both `gramine-direct` and `gramine-sgx` modes. I actually expected any Gramine workload to fail...

- Busybox: `gramine-direct busybox sh`:
```
cat /sys/devices/system/cpu/online
0-223

cat /sys/devices/system/cpu/cpu0/cache/index0/shared_cpu_map
00000000,00000000,00000000,00010000,00000000,00000000,00000001

cat /sys/devices/system/cpu/cpu0/cache/index3/shared_cpu_map
00000000,000000ff,ffffffff,ffff0000,00000000,00ffffff,ffffffff

cat /sys/devices/system/cpu/cpu1/cache/index0/shared_cpu_map
00000000,00000000,00000000,00020000,00000000,00000000,00000002

cat /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_map
00000000,000000ff,ffffffff,ffff0000,00000000,00ffffff,ffffffff

cat /sys/devices/system/cpu/cpu223/cache/index0/shared_cpu_map
80000000,00000000,00000000,00008000,00000000,00000000,00000000

cat /sys/devices/system/cpu/cpu223/cache/index3/shared_cpu_map
ffffffff,ffffff00,00000000,0000ffff,ffffffff,ff000000,00000000

cat /sys/devices/system/node/online
0-7

cat /sys/devices/system/node/node0/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000  // OH NO

cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

cat /sys/devices/system/node/node1/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000  // OH NO

...

cat /sys/devices/system/node/node6/cpumap
00000000,00000000,00000000,00000000,00000000,00000000,00000000

cat /sys/devices/system/node/node7/cpumap
ffffffff,ffffff00,00000000,0000ffff,ffffffff,ff000000,00000000  // HMMM

cat /sys/devices/system/node/node7/distance
21 21 21 21 12 12 12 10
```

- Busybox: `gramine-sgx busybox sh` -- same as above.
</blockquote></details>

Just for the reference, the *actual* values on the host:
```
cat /sys/devices/system/node/node0/cpumap
00000000,00000000,00000000,3fff0000,00000000,00000000,00003fff

cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

cat /sys/devices/system/node/node1/cpumap
00000000,00000000,00000fff,c0000000,00000000,00000000,0fffc000

...

cat /sys/devices/system/node/node6/cpumap
0003fff0,00000000,00000000,00000003,fff00000,00000000,00000000

cat /sys/devices/system/node/node7/cpumap
fffc0000,00000000,00000000,0000fffc,00000000,00000000,00000000

cat /sys/devices/system/node/node7/distance
21 21 21 21 12 12 12 10
```


<!-- Sent from Reviewable.io -->

2022-05-03 00:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N16LtK80meq9ETqyVdE:bszsbru) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
Thanks for checking!

> HelloWorld runs fine in both `gramine-direct` and `gramine-sgx` modes. I actually expected any Gramine workload to fail...

Yes, that was expected, it should just cause unoptimal scheduling, not breaking of anything.

The output you pasted for my current code for `/sys/devices/system/node/node<id>/cpumap` seems impossible. Are you sure that you checked all the nodes between 1 and 6 and they are all 0? That should be impossible if all CPUs are online, i.e. the current code should ensure that all these masks OR to the mask containing all online CPUs from the system.

In the meantime, I'll adjust the PR to support SNC, should be rather easy.


<!-- Sent from Reviewable.io -->

2022-05-03 05:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N17UCEG7oJBdFu1UDwu:b-wpfpbb) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
>  Are you sure that you checked all the nodes between 1 and 6 and they are all 0? That should be impossible if all CPUs are online, i.e. the current code should ensure that all these masks OR to the mask containing all online CPUs from the system.

Sorry, I didn't check all the nodes between 1 and 6, I got lazy. You're right, they all can't contain 0.

Unfortunately, I don't have access to this SNC-enabled system right now (I need to request access and wait for my turn). So I can't give the Gramine outputs for other nodes currently.


<!-- Sent from Reviewable.io -->

2022-05-04 06:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N1Ck1D6E9jtqB6sWFI4:b-ac6era) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>  Are you sure that you checked all the nodes between 1 and 6 and they are all 0? That should be impossible if all CPUs are online, i.e. the current code should ensure that all these masks OR to the mask containing all online CPUs from the system.

Sorry, I didn't check all the nodes between 1 and 6, I got lazy. You're right, they all can't contain 0.

Unfortunately, I don't have access to this SNC-enabled system right now (I need to request access and wait for my turn). So I can't give the Gramine outputs for other nodes currently.
</blockquote></details>

I got the SNC-enabled system again (same one, same config).

I used Michal's private fork where he tests the changes that enable correct SNC in Gramine. **Everything works as expected**. Below is a snippet of running `gramine-direct busybox sh`:
```
cat /sys/devices/system/node/online
0-7

cat /sys/devices/system/node/node0/cpumap
00000000,00000000,00000000,3fff0000,00000000,00000000,00003fff

cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

cat /sys/devices/system/node/node1/cpumap
00000000,00000000,00000fff,c0000000,00000000,00000000,0fffc000

cat /sys/devices/system/node/node2/cpumap
00000000,00000000,03fff000,00000000,00000000,000003ff,f0000000

cat /sys/devices/system/node/node3/cpumap
00000000,000000ff,fc000000,00000000,00000000,00fffc00,00000000

cat /sys/devices/system/node/node4/cpumap
00000000,003fff00,00000000,00000000,0000003f,ff000000,00000000

cat /sys/devices/system/node/node5/cpumap
0000000f,ffc00000,00000000,00000000,000fffc0,00000000,00000000

cat /sys/devices/system/node/node6/cpumap
0003fff0,00000000,00000000,00000003,fff00000,00000000,00000000

cat /sys/devices/system/node/node7/cpumap
fffc0000,00000000,00000000,0000fffc,00000000,00000000,00000000
```

Exactly the same results are obtained with `gramine-sgx busybox sh`.


<!-- Sent from Reviewable.io -->

2022-05-04 08:40 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 16 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`LibOS/shim/src/fs/sys/node_info.c` line 54 at r5](https://reviewable.io/reviews/gramineproject/gramine/530#-N0ZVg_52VPaGvTuMGX7:-N1DDNdMEoAsgXD6bLju:b-ydx8ni) ([raw file](https://github.com/gramineproject/gramine/blob/112c38566c282bc2f13cd391018bb5267755f604/LibOS/shim/src/fs/sys/node_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I got the SNC-enabled system again (same one, same config).

I used Michal's private fork where he tests the changes that enable correct SNC in Gramine. **Everything works as expected**. Below is a snippet of running `gramine-direct busybox sh`:
```
cat /sys/devices/system/node/online
0-7

cat /sys/devices/system/node/node0/cpumap
00000000,00000000,00000000,3fff0000,00000000,00000000,00003fff

cat /sys/devices/system/node/node0/distance
10 12 12 12 21 21 21 21

cat /sys/devices/system/node/node1/cpumap
00000000,00000000,00000fff,c0000000,00000000,00000000,0fffc000

cat /sys/devices/system/node/node2/cpumap
00000000,00000000,03fff000,00000000,00000000,000003ff,f0000000

cat /sys/devices/system/node/node3/cpumap
00000000,000000ff,fc000000,00000000,00000000,00fffc00,00000000

cat /sys/devices/system/node/node4/cpumap
00000000,003fff00,00000000,00000000,0000003f,ff000000,00000000

cat /sys/devices/system/node/node5/cpumap
0000000f,ffc00000,00000000,00000000,000fffc0,00000000,00000000

cat /sys/devices/system/node/node6/cpumap
0003fff0,00000000,00000000,00000003,fff00000,00000000,00000000

cat /sys/devices/system/node/node7/cpumap
fffc0000,00000000,00000000,0000fffc,00000000,00000000,00000000
```

Exactly the same results are obtained with `gramine-sgx busybox sh`.
</blockquote></details>

Thanks! Just pushed the changes here.


<!-- Sent from Reviewable.io -->

2022-05-04 09:01 UTC, dimakuv reviewed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-04 09:01 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-04 10:16 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 5 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-04 10:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: 18 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/530#-N0036wsDXDqse6dd7qx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, will fix during rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-04 11:13 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-04 11:47 UTC, pwmarcz approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/530)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-04 12:05 UTC, merged