[LibOS] Don't use PAL trusted/protected files in `encrypted` fs
gramineproject/gramine pull request #534
Opened 2022-04-19 16:09 UTC by pwmarcz

## Description of the changes 

The new mount syntax supersedes `sgx.{allowed,trusted,protected}_files`, and the `encrypted` filesystem should always create "passthrough" PAL handles. This is ensured by introducing a special option to `DkStreamOpen`.

(I think that this option is temporary - if we manage to move all of trusted/protected files to LibOS, then all PAL handles will be "passthrough").

## How to test this PR? 

The LibOS regression tests worked only because we mounted `tmp/enc`, and we happened to include `tmp/` in the list of allowed files. Instead, the tests for encrypted files use a separate host directory (`tmp_enc/`).

2022-04-19 22:36 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N02xNAxCcBEG_eRiDgL:-N02xNAxCcBEG_eRiDgM:biwaiko) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/LibOS/shim/src/fs/chroot/encrypted.c#L282)):*
> ```C
>     int ret = chroot_dentry_uri(dent, dent->inode->type, &uri);
>     if (ret < 0)
>         goto out;
> ```

I'd feel better if this was `return ret` instead. I don't like having any assumptions about ret-by-arg values in case of failure.
___
*[Pal/include/pal/pal.h, line 261 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N02wwNW5q5SsHqZwfNc:-N02wwNXDv44UrovxqA7:bsysufg) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/Pal/include/pal/pal.h#L261)):*
> ```objc
> #define PAL_OPTION_NONBLOCK        4
> #define PAL_OPTION_DUALSTACK       8 /*!< Create dual-stack socket (opposite of IPV6_V6ONLY) */
> #define PAL_OPTION_PASSTHROUGH    16 /*!< Disregard `sgx.{allowed,trusted,protected}_files` */
> ```

Could you use hex here?


<!-- Sent from Reviewable.io -->

2022-04-20 09:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: 7 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N04nyhR9KKE96MsFiIl:-N05CkoC2p2xJC1IO6TD:b-o9gx76) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/LibOS/shim/src/fs/chroot/encrypted.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this needed here (we're opening a dir, so it should end up in `dir_open()` of PAL's file handling)? Or you added it just for consistency?
</blockquote></details>

You're right, it's only for consistency. Would you prefer me to pass 0 here? I'm not very attached to either choice, this one just seemed less surprising.
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 274 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N04ohRHDvBMB4i6yRO4:-N05Deuh3yO6V3GHpkFd:bcvjgzp) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/LibOS/shim/src/fs/chroot/encrypted.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The only reason we introduce this function is to specify `PAL_OPTION_PASSTHROUGH`? Can you specify this in the NOTE or TODO comment, that we can safely move back to the generic `chroot_unlink()` callback once this PASSTHROUGH option is removed?
</blockquote></details>

Good idea. Done.
___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 282 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N02xNAxCcBEG_eRiDgL:-N05Dn1M8HUrDwG7EtHf:b-k1y5pj) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/LibOS/shim/src/fs/chroot/encrypted.c#L282)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd feel better if this was `return ret` instead. I don't like having any assumptions about ret-by-arg values in case of failure.
</blockquote></details>

OK. Done.
___
*[Pal/include/pal/pal.h, line 261 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N02wwNW5q5SsHqZwfNc:-N05E81h38hGQW3jkeo1:babrut3) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/Pal/include/pal/pal.h#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you use hex here?
</blockquote></details>

Makes sense. I converted all these to hex.


<!-- Sent from Reviewable.io -->

2022-04-20 09:40 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/chroot/encrypted.c, line 255 at r1](https://reviewable.io/reviews/gramineproject/gramine/534#-N04nyhR9KKE96MsFiIl:-N05Kp-h-PjiicEu8ipJ:btrzzuz) ([raw file](https://github.com/gramineproject/gramine/blob/9aee3aeb427413804ec2f4c8caeaba0dae6989d5/LibOS/shim/src/fs/chroot/encrypted.c#L255)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You're right, it's only for consistency. Would you prefer me to pass 0 here? I'm not very attached to either choice, this one just seemed less surprising.
</blockquote></details>

No, I'm fine with the current version.


<!-- Sent from Reviewable.io -->

2022-04-20 11:00 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-20 11:08 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-04-20 11:13 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/534)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-20 12:09 UTC, merged