[LibOS] Support special keys (MRENCLAVE, MRSIGNER) in `encrypted` fs
gramineproject/gramine pull request #539
Opened 2022-04-20 12:13 UTC by pwmarcz

## Description of the changes 

Key names beginning with `_` are considered special, and PAL is queried for these keys. This is used for SGX MRENCLAVE and MRSIGNER keys.

If a key is not supported by the current PAL, mounting will still succeed (but files will not be readable). This way, manifests using these PAL-host-specific keys can still be loaded when using other PAL hosts.

(This design is as discussed in #371).

## How to test this PR? 

The existing tests for MRENCLAVE and MRSIGNER keys now also check the new implementation.

2022-04-21 07:57 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/539)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 390 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A4gBm4cxmKRmy9c6d:-N0A4gBn6DpVlq6CrVS6:b-bilzdk) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/LibOS/shim/src/fs/shim_fs_encrypted.c#L390)):*
> ```C
>         } else if (ret == -PAL_ERROR_NOTIMPLEMENTED) {
>             log_warning("Special key \"%s\" is not supported by current PAL. Mounts using this key "
>                         "will not work.", name);
> ```

I think this doesn't deserve a warning level. Maybe `log_debug`? Otherwise it will be rather annoying for users.
___
*[Pal/include/pal/pal.h, line 764 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A5aFR92r4WpTf6uvp:-N0A5aFR92r4WpTf6uvq:b-4bydaf) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/Pal/include/pal/pal.h#L764)):*
> ```objc
>  * remote attestation and secret provisioning, before the user application starts.
>  */
> int DkSetProtectedFilesKey(const char* pf_key_hex);
> ```

Can you add either here, or somewhere in GitHub (your meta-issue?) that this is deprecated and should be removed as part of the "move away from PFs in PAL", and that it should be removed in Gramine v1.4.

Or maybe I forgot how you planned to support the "old manifest syntax"? Did you plan to emulate the old manifest syntax with your new LibOS implementation, or did you plan for these two to live together until v1.4?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A6NxlDuEJVE2x72ee:-N0A6NxlDuEJVE2x72ef:b3k2r0f) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/Pal/src/host/Linux-SGX/db_misc.c#L632)):*
> ```C
>     sgx_key_128bit_t sgx_key;
> 
>     if (*key_size < sizeof(key))
> ```

Wait what? Shouldn't it be `sizeof(sgx_key)`?


<!-- Sent from Reviewable.io -->

2022-04-21 14:05 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/539)* status: 9 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs_encrypted.c, line 390 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A4gBm4cxmKRmy9c6d:-N0BNc020P9YbIoa0qVE:b3pjast) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/LibOS/shim/src/fs/shim_fs_encrypted.c#L390)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this doesn't deserve a warning level. Maybe `log_debug`? Otherwise it will be rather annoying for users.
</blockquote></details>

Yeah, on some manifests this message will appear every time you're running `gramine-direct`, that's annoying. Changed to `log_debug`.
___
*[Pal/include/pal/pal.h, line 764 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A5aFR92r4WpTf6uvp:-N0BO8AP2qGNu6SWBgwD:br4uzx7) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/Pal/include/pal/pal.h#L764)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add either here, or somewhere in GitHub (your meta-issue?) that this is deprecated and should be removed as part of the "move away from PFs in PAL", and that it should be removed in Gramine v1.4.

Or maybe I forgot how you planned to support the "old manifest syntax"? Did you plan to emulate the old manifest syntax with your new LibOS implementation, or did you plan for these two to live together until v1.4?
</blockquote></details>

Actually, no, the plan is to remove this soon, and just support the old syntax (`sgx.protected_files`) in the new feature.

That's quite a lot of code to remove, so I don't want to add TODOs everywhere. I added a comment in the issue: https://github.com/gramineproject/gramine/issues/371#issuecomment-1105254159
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 632 at r1](https://reviewable.io/reviews/gramineproject/gramine/539#-N0A6NxlDuEJVE2x72ee:-N0BR76Q40d6lw9KhaN7:b-hbyrol) ([raw file](https://github.com/gramineproject/gramine/blob/d574e3b3f3722be45b4812d4423b706c08a6cb2d/Pal/src/host/Linux-SGX/db_misc.c#L632)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait what? Shouldn't it be `sizeof(sgx_key)`?
</blockquote></details>

My mistake. Fixed.


<!-- Sent from Reviewable.io -->

2022-04-21 14:14 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/539)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-26 08:44 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/539)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-26 10:54 UTC, merged