[tests] Introduce entrypoint tests
gramineproject/gramine pull request #541
Opened 2022-04-21 11:55 UTC by oshogbo

## Description of the changes
Add NASM compiler to the project - I believe we will want to move
from GCC assembly to NASM in the future, so this is the first step.
The second change adds tests for entry point.
These tests verify the process initialisation state as described
in section 3.4 of System V Application Binary Interface.

## How to test this PR?
`
gramine-test pytest
gramine-test --sgx pytest
`

2022-04-24 21:47 UTC, boryspoplawski requested changes
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SHPeW22WwpRlZY54S:-N0SHPeW22WwpRlZY54T:b579qqu) (no related file):*
@woju Could you review the meson stuff?

---
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SFTSZ-vXSLXDR1Oul):*
I would mention these are for x64 somewhere
___
*[`LibOS/shim/test/abi_x86_64/atexit_func.asm` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SLyMV9BIkztx-IvaL:-N0SLyMW5UHJkDZDVWml:b3kre) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/atexit_func.asm#L14)):*
> ```m68k
> 
> _start:
>     ; mov   rdi, rdx ; XXX:osho
> ```

?
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMCJp7Cd8D-L7RoDL:-N0SMCJp7Cd8D-L7RoDM:b-49tfae) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L8)):*
> ```C
> /* We have to add a function declaration to avoid warnings.
>  * This function is used with NASM, so creating a header is pointless.
>  */
> ```

We generally either use empty line at the beginning and end of the comment, or nowhere.
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SN92q0N65ekwUbBm_:-N0SN92q0N65ekwUbBma:bgpotj5) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L11)):*
> ```C
> int gramine_strcmp(const char* orig, const char* new);
> 
> int gramine_strcmp(const char* orig, const char* new) {
> ```

Care to explain the variable naming? Never seen such - this compares two strings, what does `new` mean in that context?
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMNDkDaxBqYFkcpAl:-N0SMNDkDaxBqYFkcpAm:bnkxws3) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L12)):*
> ```C
> 
> int gramine_strcmp(const char* orig, const char* new) {
>     if (orig == new)
> ```

Pointless check?
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMQd89Zd0miRq6l99:-N0SMQd89Zd0miRq6l9A:bjwroxr) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L15)):*
> ```C
>         return 0;
> 
>     while (*orig != '\0' && *new != '\0' && *orig == *new) {
> ```

Please don't use `\0`, they are a bit error prone. Just `0` is equivalent. Also you can just remove the comparison completely (just `*orig && ...`).
Or even shorten to `while (*orig && *orig == *new)`
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SR2bG8eZ9azozqtEE:-N0SR2bG8eZ9azozqtEF:bzi4g2n) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L20)):*
> ```C
>     }
> 
>     return *orig != *new;
> ```

Maybe `*new - *orig` to be compatible with normal `strcmp`? But that would require to change all checks in asm to `cmp rdi, 0`
___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0SKOav75abjPLEBd_K:b-fk28fh) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
> ```m68k
> section   .text
> 
> gramine_exit:
> ```

Why not just `exit`?
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0STqC32r_oWZs5sT8s:-N0STqC32r_oWZs5sT8t:b-o4v7j3) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L9)):*
> ```m68k
> ; | X|   RC|   PC| R| R|PM|UM|OM|ZM|DM|IM|
> ; +--+--+--+--+--+--+--+--+--+--+--+--+--+
> ; The MXCSR should be set as follow:
> ```

`MXCSR` -> `x87 FPU CW`
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SVTF839ysvun2Pgau:-N0SVTF839ysvun2Pgav:bxk4kaw) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L11)):*
> ```m68k
> ; The MXCSR should be set as follow:
> ; +--+--+--+--+--+--+--+--+--+--+--+--+--+
> ; | X|    0| 1  1| X| X| 1| 1| 1| 1| 1| 1|
> ```

`0 0` for `RC`? Now it looks like it's one bit
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SXfZQ1rKcq4-PBerT:-N0SXfZQ1rKcq4-PBerU:b-3ith3k) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L20)):*
> ```m68k
> 
> _start:
>     fstcw [rsp]
> ```

NP: `fnstcw`
___
*[`LibOS/shim/test/abi_x86_64/Makefile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SGHZx7FqwvkFFZ4r8:-N0SGHZx7FqwvkFFZ4r9:bxxgck1) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/Makefile#L1)):*
> ```Makefile
> # Disable implicit rules so that Make doesn't try to compile the binaries.
> ```

Why do we need this file?
___
*[`LibOS/shim/test/abi_x86_64/meson.build` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SI5AX04-vTWsLrNeJ:-N0SI5AX04-vTWsLrNeK:b-bc01m1) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/meson.build#L6)):*
> ```Meson
> )
> 
> tests = {
> ```

All these "configs" are the same, maybe just use them unconditionally?
___
*[`LibOS/shim/test/abi_x86_64/mxcsr.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SWMVq6BU8TeYlWtXZ:-N0SWMVq6BU8TeYlWtX_:b-xrpi7e) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/mxcsr.asm#L11)):*
> ```m68k
> ; The MXCSR should be set as follow:
> ; +--+--+--+--+--+--+--+--+--+---+--+--+--+--+--+--+
> ; | 0|    0| 1| 1| 1| 1| 1| 1|  0| X| X| X| X| X| X|
> ```

ditto (`0 0` for `RC`)
___
*[`LibOS/shim/test/abi_x86_64/mxcsr.asm` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SXJ0C8ICstvW7f-4z:-N0SXJ0C8ICstvW7f-5-:bk4fknf) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/mxcsr.asm#L24)):*
> ```m68k
> 
>     mov     edi, [rsp]
>     shr     rdi, 6
> ```

Why this shift? We mask + check below anyway, might as well just mask these.
___
*[`LibOS/shim/test/abi_x86_64/rflags.asm` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SLFEI57JaOPQmrl8_:-N0SLFEI57JaOPQmrl8a:begbehf) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/rflags.asm#L6)):*
> ```m68k
> 
> ; The rFlags should be cleared.
> ; Verify OF, DF, SF, ZF, AF, PF, CF
> ```

What about the rest (e.g. AC)?
___
*[`LibOS/shim/test/abi_x86_64/stack_argc1.asm` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SOUvJ-nVumZEFxzej:-N0SOUvJ-nVumZEFxzek:b-48puqd) ([raw file](https://github.com/gra [...]

2022-04-25 08:24 UTC, dimakuv requested changes
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 31 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0Uj-q47jXxAoMAPS0Q:-N0Uj-q53iTA26OL0Ogo:b-kuej2g) (no related file):*
There is at least the "Cloud Deployment" file in our Documentation that needs to be updated with `nasm` installation. Please grep for all `apt install`s in our documentation, and add nasm where required.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UjCGI0keP4uKbPZe_:-N0UjCGJB2aNdQCTI1FU:blvhc18) (no related file):*
A change to add `nasm` installation should be added in the GSC tool: https://github.com/gramineproject/gsc. @oshogbo Could you add such a PR? It should go into the Dockerfiles, both for Ubuntu and CentOS.

I understand that currently `nasm` is used purely for tests, so GSC may ignore this (because GSC builds Gramine without `-Dtests`, afair). But you want to rewrite our assembly in NASM, so this will be required.

---
___
*[`LibOS/shim/test/meson.build` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UoL8S8iJ3ACfX1Rvr:-N0UoL8S8iJ3ACfX1Rvs:bx7yi36) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/meson.build#L2)):*
> ```Meson
> if host_machine.cpu_family() == 'x86_64'
>     subdir('abi_x86_64')
> ```

I don't remember how our CI works with these LibOS tests. Will they be automatically run? Or do we need to tweak the files in `.ci/`?
___
*[`LibOS/shim/test/abi_x86_64/manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UlJsYCrVRG3lvsQnh:-N0UlJsYCrVRG3lvsQni:bsfij3e) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/manifest.template#L4)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> 
> loader.argv0_override = "{{ entrypoint }}"
> ```

Do we need this if we have the below manifest option? I don't think so, but I don't remember the exact details.
___
*[`LibOS/shim/test/abi_x86_64/manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UlUSj57Sn4q3osBPs:-N0UlUSj57Sn4q3osBPt:b-hi737f) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/manifest.template#L14)):*
> ```
> sgx.nonpie_binary = true
> sgx.debug = true
> sgx.thread_num = 2
> ```

Why exactly 2? Does this even work, because Gramine's LibOS creates at least the IPC thread and also at least one pipe (which leads to one helper handshake thread). I would expect that the minimum value should be `3`. And for sanity, I'd set it to `4` or even `8`.
___
*[`LibOS/shim/test/abi_x86_64/meson.build` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SI5AX04-vTWsLrNeJ:-N0Um0rs02ZkwQbIrqfW:b-9px752) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/meson.build#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All these "configs" are the same, maybe just use them unconditionally?
</blockquote></details>

+1, I don't think we'll have tests that will need some other configs in this directory.
___
*[`LibOS/shim/test/abi_x86_64/stack.asm` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0Umk7m80JlSv8Cq6sP:-N0Umk7m80JlSv8Cq6sQ:b-q5wzne) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/stack.asm#L17)):*
> ```m68k
> 
>     mov   rax, rsp
>     and   rax, 15
> ```

I'd prefer `0xF`, but not blocking
___
*[`LibOS/shim/test/abi_x86_64/stack_argc1.asm` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SOUvJ-nVumZEFxzej:-N0UnTdZ1DRKigUH67X-:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/stack_argc1.asm#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How about we remove `stack_argc*` tests and check these in `stack_argv`? I don't see a point in splitting these.
</blockquote></details>

+1
___
*[`LibOS/shim/test/abi_x86_64/test_entrypoint.py` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SNOJe2V7lo_0BsCTp:-N0Unpss0u-QoxMaM0IL:b-qxrgma) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/test_entrypoint.py#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we want to run these in CI?
cc @dimakuv @mkow 
I would say yes, but each of these would spawn an enclave and lengthen CI running time...
</blockquote></details>

Yes, I'd like to run these in the CI.

To reduce the running time, I would decrease the number of tests. For example, the five stack tests can be merged into one.


<!-- Sent from Reviewable.io -->

2022-04-25 09:56 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: 6 of 19 files reviewed, 31 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0Uj-q47jXxAoMAPS0Q:-N0V8K56DLgD8S8nyDNi:b-fx0f7u) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is at least the "Cloud Deployment" file in our Documentation that needs to be updated with `nasm` installation. Please grep for all `apt install`s in our documentation, and add nasm where required.
</blockquote></details>

I think I addressed all of them.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UjCGI0keP4uKbPZe_:-N0V8PGKDf2mNUNviDQw:b-p1hp26) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A change to add `nasm` installation should be added in the GSC tool: https://github.com/gramineproject/gsc. @oshogbo Could you add such a PR? It should go into the Dockerfiles, both for Ubuntu and CentOS.

I understand that currently `nasm` is used purely for tests, so GSC may ignore this (because GSC builds Gramine without `-Dtests`, afair). But you want to rewrite our assembly in NASM, so this will be required.
</blockquote></details>

I will add it, thanks!

---
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SFTSZ-vXSLXDR1Oul):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would mention these are for x64 somewhere
</blockquote></details>

Good idea. Thanks!
___
*[`LibOS/shim/test/abi_x86_64/atexit_func.asm` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SLyMV9BIkztx-IvaL:-N0UoBYtBwNtwCOLZiKK:bj6ywnv) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/atexit_func.asm#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

My bad sorry.
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 8 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMCJp7Cd8D-L7RoDL:-N0Uv-hh25dE8ACxESx7:b-ilqjos) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We generally either use empty line at the beginning and end of the comment, or nowhere.
</blockquote></details>

Fixed thanks.
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SN92q0N65ekwUbBm_:-N0UoS8G30xBNedO8ucr:bkgp4bw) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Care to explain the variable naming? Never seen such - this compares two strings, what does `new` mean in that context?
</blockquote></details>

I added the name to represent the test naming.
`orig` -  original - the string we want it to be
`new` - the string we have
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMNDkDaxBqYFkcpAl:-N0UoIfj-LbXZfQ1g040:b-piust2) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L12)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Pointless check?
</blockquote></details>

It's optimization - if pointers are identical, there is no point in checking them.
If you prefer, I can remove it.
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMQd89Zd0miRq6l99:-N0UpQVM6QU3MI7yDmAh:b-dmvfhi) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please don't use `\0`, they are a bit error prone. Just `0` is equivalent. Also you can just remove the comparison completely (just `*orig && ...`).
Or even shorten to `while (*orig && *orig == *new)`
</blockquote></details>

I prefer to check the values explicitly. When you do it, the intention is very obvious. If the project has a different policy, I can change that.

I also prefer to use the same type for checking data. As char represents characters, IMHO, it makes more sense to compare it to `\0` as this also represents a character. That said, I will change it. 
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SR2bG8eZ9azozqtEE:-N0UpGCe0X4xmokERuJs:bsfrpi2) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `*new - *orig` to be compatible with normal `strcmp`? But that would require to change all checks in asm to `cmp rdi, 0`
</blockquote></details>

Yea, I was thinking about that. 
But figure out that I'm just interested in results.
As well I expect to use this only in the tests suit, so not sure if we wan't to change this,
___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0Upe3B8Y73tdyuOUtq:bpkk9c9) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not just `exit`?
</blockquote></details>

In both cases (exit and strcmp) I wanted to highlight that this is not the glibc/libc version of exit and that it's our implementation for tests.
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 9 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0STqC32r_oWZs5sT8s:-N0Uq3Cw94dbBQFFwKRu:b-ucfkn4) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`MXCSR` -> `x87 FPU CW`
</blockquote></details>

Thanks.
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SVTF839ysvun2Pgau:-N0Uq4JrDUz6iET8nAsD:bt2vr1b) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`0 0` for `RC`? Now it looks like it's one bit
</blockquote></details>

Fixed.
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SXfZQ1rKcq4-PBerT:-N0UqGYs3Lm9JFKvTMeI:b-12hr94) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L20)):*
> fnstcw

Why we want fnstcw?
___
*[`LibOS/shim/test/abi_x86_64/Makefile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SGHZx7FqwvkFFZ4r8:-N0UqJsH7jLvG2ngabWl:b-eu0rc4) ([raw file](https://github.com/g [...]

2022-04-25 13:19 UTC, boryspoplawski requested changes
> Reviewed 13 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0ViTjX24QRGxN2N3-9:-N0ViTjY-tHyoLSV1_W4:brjvhqd) (no related file):*
Please don't force push. Some more info: https://gramine.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle
For commit message changes we wither add the new version as a comment in reviewable or use squash commit with new content and some TODO banner.

---
___
*[`LibOS/shim/test/meson.build` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UoL8S8iJ3ACfX1Rvr:-N0VjhiTBJ5W87uvfQOY:b-efgwzl) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/meson.build#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't remember how our CI works with these LibOS tests. Will they be automatically run? Or do we need to tweak the files in `.ci/`?
</blockquote></details>

We would need to add them in `.ci/lib/stage-test.jenkinsfile`
___
*[`LibOS/shim/test/meson.build` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/541#-N0VjlRS8kXOyZi0xOW9:-N0VjlRS8kXOyZi0xOWA:bflp6ix) ([raw file](https://github.com/gramineproject/gramine/blob/8a0fac1f052d77806ac5ab4949e9affb3e6287f1/LibOS/shim/test/meson.build#L1)):*
> ```Meson
> if host_machine.cpu_family() == 'x86_64'
> ```

Actually, could you split this (I mean directory) into `abi/arch/x86_64` or `abi/x86_64`?
___
*[`LibOS/shim/test/abi_x86_64/atexit_func.asm` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/541#-N0VkVGs-p0iJhRGfkHG:-N0VkVGtEhj1xArznPn4:b2iy875) ([raw file](https://github.com/gramineproject/gramine/blob/8a0fac1f052d77806ac5ab4949e9affb3e6287f1/LibOS/shim/test/abi_x86_64/atexit_func.asm#L6)):*
> ```m68k
> 
> ; rdx contains a function pointer that the application should register with atexit.
> ; We decided to set rdx to NULL.
> ```

I think this needs a broader explanation (unclear to me if `we` means writer of this test or Gramine). Maybe something like: `Gramine sets rdx to NULL - it does not use this feature at all.`
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMNDkDaxBqYFkcpAl:-N0Vl1LO20zjSAZhcsh4:b-gtyz4o) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L12)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It's optimization - if pointers are identical, there is no point in checking them.
If you prefer, I can remove it.
</blockquote></details>

I don't mind, just I see no point in optimizing this code (because you could go further and just use `rep cmpsb`)
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMQd89Zd0miRq6l99:-N0VnfkG44f46khm_knf:b-dgizyl) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L15)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I prefer to check the values explicitly. When you do it, the intention is very obvious. If the project has a different policy, I can change that.

I also prefer to use the same type for checking data. As char represents characters, IMHO, it makes more sense to compare it to `\0` as this also represents a character. That said, I will change it. 
</blockquote></details>

But char is also just 8 bit (possibly signed or unsigned) integer :)

The whole codebase omits `!= 0`, but I'm not sure if we have any policy on that.
cc @mkow @dimakuv 
I personally prefer to omit them.
___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0VoJwp2E-T5S-X8qPW:b-b15cu5) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

In both cases (exit and strcmp) I wanted to highlight that this is not the glibc/libc version of exit and that it's our implementation for tests.
</blockquote></details>

The thing is you are not exiting Gramine here, you are just exiting the app, which goes into Gramine code emulating the `exit` syscall.
___
*[`LibOS/shim/test/abi_x86_64/fpu_control_word.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SXfZQ1rKcq4-PBerT:-N0VoYg-CYnmFdcChyzY:b-wqnsov) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/fpu_control_word.asm#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> fnstcw

Why we want fnstcw?
</blockquote></details>

Why we want to handle exceptions here?
___
*[`LibOS/shim/test/abi_x86_64/Makefile` line 1 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SGHZx7FqwvkFFZ4r8:-N0VohRPDlP6WpwfZhQa:bli3r48) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/Makefile#L1)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

TBH I don't know.
I assumed it's for the user not to make on these tests, as it was done historically.
I assumed that this was a template for the tests directory.
The same file is in `LibOS/shim/test/fs`, `LibOS/shim/test/regression`.
These files was added in: `ad85fe95c43fd583f7fa53a5f170383a5fcd8536`
</blockquote></details>

It was for historical reasons, mostly not to tweak with CI configs. Not needed for new code.
___
*[`LibOS/shim/test/abi_x86_64/manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UlUSj57Sn4q3osBPs:-N0VpDoy2KamxYW9UmjO:bn7t45s) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/manifest.template#L14)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sorry but the reason *why* `2` is sufficient it's outside my current knowledge.
However, it did work, or I did something wrong while running the tests:

```
$ grep thread_num manifest.template 
sgx.thread_num = 2
$ gramine-test --sgx pytest
collected 9 items                                                                                                                           

test_entrypoint.py .........                                                                                                          [100%]
```

I will increase it to 4.
</blockquote></details>

`2` was enough: 1 for main thread, 1 for IPC worker. There are no pipes created (no fork, no pipe). Or maybe you meant the one that IPC worker uses? It's just a "server" pipe, it wait's for new remove connections from other enclaves.
___
*[`LibOS/shim/test/abi_x86_64/rflags.asm` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SLFEI57JaOPQmrl8_:-N0Vpr5N0Gg5mOcpWXbK:b-50ya9k) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/rflags.asm#L6)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

According to this:
https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf

AC is undefined.
![image.png](https://files.reviewable [...]

2022-04-25 14:17 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: 6 of 20 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/test/meson.build` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/541#-N0VjlRS8kXOyZi0xOW9:-N0W4RgrCc2j3WnRTHUR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a0fac1f052d77806ac5ab4949e9affb3e6287f1/LibOS/shim/test/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, could you split this (I mean directory) into `abi/arch/x86_64` or `abi/x86_64`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-25 17:09 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: 19 of 22 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @oshogbo, and @pwmarcz)

___
*[`LibOS/shim/test/meson.build` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UoL8S8iJ3ACfX1Rvr:-N0Wgl69EFJcJep7rnCo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/meson.build#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We would need to add them in `.ci/lib/stage-test.jenkinsfile`
</blockquote></details>

Done.
___
*[`LibOS/shim/test/meson.build` line 1 at r3](https://reviewable.io/reviews/gramineproject/gramine/541#-N0VjlRS8kXOyZi0xOW9:-N0WQYNWCifLnIIjNDqp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a0fac1f052d77806ac5ab4949e9affb3e6287f1/LibOS/shim/test/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`LibOS/shim/src/arch/meson.build` for reference
</blockquote></details>

Done.
___
*[`LibOS/shim/test/abi/x86_64/stack_arg.asm` line 45 at r4](https://reviewable.io/reviews/gramineproject/gramine/541#-N0WGtdXCGnymUiq-CH-:-N0WQhl3AElR0ocUfKbU:bb6uran) ([raw file](https://github.com/gramineproject/gramine/blob/b61ef57563383c1b1142b19fdcb2cbfed7151c69/LibOS/shim/test/abi/x86_64/stack_arg.asm#L45)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this? Why not simply `mov rsi, ...`?
</blockquote></details>

Duh!
___
*[`LibOS/shim/test/abi_x86_64/test_entrypoint.py` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SNOJe2V7lo_0BsCTp:-N0WgcVp2xLS5Mf_9S6r:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/test_entrypoint.py#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then they need to be added to appropriate file in `.ci` configs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-25 17:15 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @pwmarcz)

___
*[`.ci/lib/stage-test.jenkinsfile` line 2 at r5](https://reviewable.io/reviews/gramineproject/gramine/541#-N0WhYIy7RYOagQDbr-t:-N0WhYIy7RYOagQDbr-u:b-661qnz) ([raw file](https://github.com/gramineproject/gramine/blob/938a1a7531b7d87b54f5a1ae056570fb892b627d/.ci/lib/stage-test.jenkinsfile#L2)):*
> ```
> stage('test') {
>     timeout(time: 15, unit: 'MINUTES') {
> ```

Please move it to the end or before `fs` tests, so it's logically sorted (now we have LibOS -> PAL -> LibOS tests...)
___
*[`.ci/lib/stage-test.jenkinsfile` line 7 at r5](https://reviewable.io/reviews/gramineproject/gramine/541#-N0WhPR_6kX-ehntpUvO:-N0WhPRaEh6IZ3VB8YQw:b-8dgfu8) ([raw file](https://github.com/gramineproject/gramine/blob/938a1a7531b7d87b54f5a1ae056570fb892b627d/.ci/lib/stage-test.jenkinsfile#L7)):*
> ```
>                 cd LibOS/shim/test/abi/x86_64
>                 gramine-test build -v
>                 python3 -m pytest -v --junit-xml fs.xml
> ```

`fs.xml`?


<!-- Sent from Reviewable.io -->

2022-04-25 17:19 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: 21 of 22 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @oshogbo, and @pwmarcz)

___
*[`.ci/lib/stage-test.jenkinsfile` line 2 at r5](https://reviewable.io/reviews/gramineproject/gramine/541#-N0WhYIy7RYOagQDbr-t:-N0Wj1xo-HkmyVYnznX2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/938a1a7531b7d87b54f5a1ae056570fb892b627d/.ci/lib/stage-test.jenkinsfile#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move it to the end or before `fs` tests, so it's logically sorted (now we have LibOS -> PAL -> LibOS tests...)
</blockquote></details>

Done.
___
*[`.ci/lib/stage-test.jenkinsfile` line 7 at r5](https://reviewable.io/reviews/gramineproject/gramine/541#-N0WhPR_6kX-ehntpUvO:-N0Wj1mN21lgKRpdeOzT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/938a1a7531b7d87b54f5a1ae056570fb892b627d/.ci/lib/stage-test.jenkinsfile#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`fs.xml`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-25 17:31 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-25 20:03 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0XJO7u48klFOJ80wgk:-N0XJO7v59ESdzti5rgc:bpajwhf) (no related file):*
You need to install `nasm` in dockerfiles in `.ci` dir (this is why jenkins failed)

---


<!-- Sent from Reviewable.io -->

2022-04-25 20:07 UTC, boryspoplawski reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-04-25 20:07 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-25 20:50 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, and @pwmarcz)



<!-- Sent from Reviewable.io -->

2022-04-25 20:50 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-26 07:25 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, 12 of 14 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UjCGI0keP4uKbPZe_:-N0Zfh2E4oDNM7OKp8Fs:b-qsary5) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I will add it, thanks!
</blockquote></details>

I'm blocking this PR until we merge the corresponding GSC PR https://github.com/gramineproject/gsc/pull/55.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0Zk_I2E_YpMpGsD_7Z:-N0Zk_I2E_YpMpGsD_7_:b-yjt3k2) (no related file):*
Our Jenkins CI fails with at the cleanup step:
```
23:06:59  + gramine-test -C LibOS/shim/test/abi/x86_64 clean
23:06:59  Usage: gramine-test [OPTIONS] COMMAND [ARGS]...
23:06:59  Try "gramine-test --help" for help.
23:06:59  
23:06:59  Error: Invalid value for "--conf-file-name" / "-n": File "tests.toml" does not exist.
```

Please fix.

---
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMQd89Zd0miRq6l99:-N0Zgle_8xWX-M8WnvgB:b-lksmc1) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But char is also just 8 bit (possibly signed or unsigned) integer :)

The whole codebase omits `!= 0`, but I'm not sure if we have any policy on that.
cc @mkow @dimakuv 
I personally prefer to omit them.
</blockquote></details>

We don't have a particular policy on omitting these equality-with-zero checks. But I agree with Borys -- in this case, `while (*orig && *orig == *new)` reads the best for me.

Sometimes, especially in Pawel's code, we use `!= 0` for clarity. I think we never use `!= '\0'`, and `!= 0x00` also reads strange to me. So either `!= 0` or omitting is the best for me.
___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0ZhZWX4BNQ1m7tH1eg:by1gq5h) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not even "Gramne version of exit" - these test should be fine to run on bare Linux host.

>  Would you be happy with "app_exit" and "app_strcmp"?

Idk, either that or just make them behave like standard versions and name accordingly.
@dimakuv @mkow @pwmarcz wdyt?
</blockquote></details>

I like the idea of the prefix, so I wouldn't go with just `exit()`.

At the same time, I had no problems with `gramine_exit()` as the "version of exit() for Gramine testing purposes". But if this name is confusing, then I vote for `test_exit()` or `app_exit()`. Btw, `test_` prefix is used in the LTP test suite, so maybe we should use the prefix `test_`, for uniformity?
___
*[`LibOS/shim/test/abi_x86_64/manifest.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UlJsYCrVRG3lvsQnh:-N0ZiL3gBL_4EBWmQKjp:b-q5spfa) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/manifest.template#L4)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If I understand correctly, if we give only `insecure__use_cmdline_argv`, the `argv[0]` will have an absolute path to the binary.
This makes it harder to check if the value is correct.

</blockquote></details>

Ah, good point. Actually, can you add a comment about this? Mentioning that this is especially important for `stack_arg` test case, because we hard-code the expected argv.
___
*[`LibOS/shim/test/abi_x86_64/manifest.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UlUSj57Sn4q3osBPs:-N0ZihCMEhDS1Cd9JbZF:b1xlis7) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/manifest.template#L14)):*
> Or maybe you meant the one that IPC worker uses? It's just a "server" pipe, it wait's for new remove connections from other enclaves.

Yes, that's what I was thinking of. Thanks for the explanation, I forgot this detail.


<!-- Sent from Reviewable.io -->

2022-04-26 09:42 UTC, woju requested changes
> Reviewed 2 of 19 files at r1, 1 of 1 files at r3, 4 of 14 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @oshogbo, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SHPeW22WwpRlZY54S:-N0_Bz-GBMfTISGt79tS:b4wlhcs) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@woju Could you review the meson stuff?
</blockquote></details>

Done.

If you're asking about `nasm_gen`, meson favours passing `.s` to gcc, and gcc favours GAS syntax, so if you want intel syntax, you need this generator stuff. The approach looks correct and may have even been stolen from meson test cases (possibly indirectly): https://github.com/mesonbuild/meson/tree/8ed151bbd786d2c52e6ea7b7cfe3147fc41ec041/test%20cases/nasm/1%20configure%20file

---
___
*[`meson.build` line 57 at r8](https://reviewable.io/reviews/gramineproject/gramine/541#-N0_BfbYD82WQcWmSPQ7:-N0_BfbYD82WQcWmSPQ8:b-6r0chi) ([raw file](https://github.com/gramineproject/gramine/blob/ef379f8a79f07fb258aa8a68a1436c775e94da2a/meson.build#L57)):*
> ```Meson
> pkgconfig = import('pkgconfig')
> 
> nasm = find_program('nasm')
> ```

`nasm_prog = ` please, or just inline below (`nasm_gen = generator(find_program(...), ...)`)
___
*[`LibOS/shim/test/abi/x86_64/test_entrypoint.py` line 3 at r8](https://reviewable.io/reviews/gramineproject/gramine/541#-N0_Emx9Aff-Xhc2fxct:-N0_Emx9Aff-Xhc2fxcu:bvlnux5) ([raw file](https://github.com/gramineproject/gramine/blob/ef379f8a79f07fb258aa8a68a1436c775e94da2a/LibOS/shim/test/abi/x86_64/test_entrypoint.py#L3)):*
> ```Python
> #!/usr/bin/env python3
> 
> from graminelibos.regression import (
> ```

parens are unnecessary, this should be 1 line
___
*[`LibOS/shim/test/abi_x86_64/meson.build` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SI5AX04-vTWsLrNeJ:-N0_E1MX4kX3NVmnnHcY:bpse6lh) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/meson.build#L6)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Do you plan to ever use all the optional features here? Because if not, the loop below can still be greatly shortened.


<!-- Sent from Reviewable.io -->

2022-04-26 14:38 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @oshogbo, @pwmarcz, and @woju)

___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0aHyC74YeGfGWaICwM:b-hgb03t) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the idea of the prefix, so I wouldn't go with just `exit()`.

At the same time, I had no problems with `gramine_exit()` as the "version of exit() for Gramine testing purposes". But if this name is confusing, then I vote for `test_exit()` or `app_exit()`. Btw, `test_` prefix is used in the LTP test suite, so maybe we should use the prefix `test_`, for uniformity?
</blockquote></details>

`test_` looks nice to me.

`gramine_exit` was confusing to me, because in the reviewable a file which used it came before the file that defined it (and later when somebody spots it in the source, it will be probably the usage as well). I thought it's some weird way of exiting Gramine without issuing a syscall (e.g. something like the ubsan/asan tests we have).


<!-- Sent from Reviewable.io -->

2022-04-26 20:57 UTC, mkow requested changes
> Reviewed 1 of 19 files at r1, 1 of 1 files at r3, 9 of 14 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @oshogbo, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0UjCGI0keP4uKbPZe_:-N0bYCYy50IsfjtQxLRb:bpq0uxf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm blocking this PR until we merge the corresponding GSC PR https://github.com/gramineproject/gsc/pull/55.
</blockquote></details>

@dimakuv: it was merged today.

---
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SMQd89Zd0miRq6l99:-N0baTpn7e6_KgGkHjJa:bppdppc) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L15)):*
> The whole codebase omits != 0, but I'm not sure if we have any policy on that.

I'm neutral on this (and yes, we don't have any official policy on this).
___
*[`LibOS/shim/test/abi_x86_64/common.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SR2bG8eZ9azozqtEE:-N0bai_rCf30h1GUmAJk:b-tlb1gv) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yea, I was thinking about that. 
But figure out that I'm just interested in results.
As well I expect to use this only in the tests suit, so not sure if we wan't to change this,
</blockquote></details>

I'd change the name to something like `test_str_neq` to not resemble the original function if we aren't going to preserve the original semantics.
___
*[`LibOS/shim/test/abi_x86_64/test_entrypoint.py` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SNOJe2V7lo_0BsCTp:-N0be1r8DsS3jWS-aVkK:bplet6j) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/test_entrypoint.py#L7)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, we definitely want to run these in CI.


<!-- Sent from Reviewable.io -->

2022-04-27 06:43 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/541#-N0Zk_I2E_YpMpGsD_7Z:-N0dk1by64_ZkxTuZpA_:b-u1o1z7) (no related file):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I created a PR for this issue: https://github.com/gramineproject/gramine/pull/551
</blockquote></details>

This PR will need to be rebased on top of current master now.

---
___
*[`LibOS/shim/test/abi_x86_64/meson.build` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SI5AX04-vTWsLrNeJ:-N0dkdFD7YaloNEqtRNH:b-4wwo61) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/meson.build#L6)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Yes I do, but I can shortened it for know if this is a problem.
</blockquote></details>

I'd prefer to keep these optional features, for future.


<!-- Sent from Reviewable.io -->

2022-04-27 10:55 UTC, boryspoplawski reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @oshogbo, @pwmarcz, and @woju)



<!-- Sent from Reviewable.io -->

2022-04-27 10:55 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-27 12:34 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: 16 of 26 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[`LibOS/shim/test/abi_x86_64/common.c` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SR2bG8eZ9azozqtEE:-N0f01t-CptEraM327TP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/common.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd change the name to something like `test_str_neq` to not resemble the original function if we aren't going to preserve the original semantics.
</blockquote></details>

Done.
___
*[`LibOS/shim/test/abi_x86_64/exit.asm` line 11 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SKOauC3t0WpQQTChM:-N0f03646elzo-x07b6A:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/exit.asm#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`test_` looks nice to me.

`gramine_exit` was confusing to me, because in the reviewable a file which used it came before the file that defined it (and later when somebody spots it in the source, it will be probably the usage as well). I thought it's some weird way of exiting Gramine without issuing a syscall (e.g. something like the ubsan/asan tests we have).
</blockquote></details>

Done.
___
*[`LibOS/shim/test/abi_x86_64/meson.build` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/541#-N0SI5AX04-vTWsLrNeJ:-N0es9CS8M7Pb1X-585X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/6910812e677744bfa7876e7d55a1f6b96dc0f5c5/LibOS/shim/test/abi_x86_64/meson.build#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer to keep these optional features, for future.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 12:50 UTC, dimakuv approved these changes
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @woju)



<!-- Sent from Reviewable.io -->

2022-04-27 12:50 UTC, dimakuv commented
Jenkins, test this please

2022-04-27 12:55 UTC, mkow approved these changes
> Reviewed 3 of 13 files at r2, 1 of 14 files at r4, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)



<!-- Sent from Reviewable.io -->

2022-04-27 13:02 UTC, boryspoplawski approved these changes
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-04-27 13:14 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-04-27 13:15 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-27 13:53 UTC, woju submitted a review, later dismissed
> Reviewed 3 of 4 files at r9, 1 of 10 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-04-27 14:02 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-04-27 14:03 UTC, boryspoplawski commented
Jenkins, test this please

2022-04-27 14:11 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/541)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-27 14:38 UTC, merged