[pal/linux-sgx]use MAP_FIXED_NOREPLACE instead of MAP_FIXED
gramineproject/gramine pull request #543
Opened 2022-04-22 06:41 UTC by JunjunGu1

Signed-off-by: junjungu <junjun.gu@intel.com>

## Description of the changes 
gramine-sgx uses MAP_FIXED flag to reserve memory for enclave.
If requested memory range collides with an existing mapping, MAP_FIXED will clobber the existing mapped range, and MAP_FIXED_NOREPLACE will fail withe error EEXIST.
So it's better to use MAP_FIXED_NOREPLACE instead of MAP_FIXED.

## How to test this PR?

2022-04-22 07:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @JunjunGu1)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0F4NPg534-vOK1CuFO:b-x7kdfk) (no related file):*
@boryspoplawski What was your stance on `MAP_FIXED_NOREPLACE`? I think this flag was introduced in newer Linux kernels, so we didn't want to use it?

---


<!-- Sent from Reviewable.io -->

2022-04-22 07:31 UTC, JunjunGu1 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0F947x8RS1-ZkFdN36:b-xov6o4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski What was your stance on `MAP_FIXED_NOREPLACE`? I think this flag was introduced in newer Linux kernels, so we didn't want to use it?
</blockquote></details>

MAP_FIXED_NOREPLACE is introduced since Linux 4.17, the os supported by gramine should support this flag

---


<!-- Sent from Reviewable.io -->

2022-04-22 09:18 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0FYqAsCZP2y_LUaaAh:b-ravrtm) (no related file):*
<details><summary><i>Previously, JunjunGu1 (JunjunGu1) wrote…</i></summary><blockquote>

MAP_FIXED_NOREPLACE is introduced since Linux 4.17, the os supported by gramine should support this flag
</blockquote></details>

We still support Ubuntu 18.04 which doesn't have it, that's why we don't use it (we even already had a PR adding this, but it failed on 18.04).

---


<!-- Sent from Reviewable.io -->

2022-04-22 11:09 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0FxHlpDIsHd2e_Ep2R:b-cn8pc9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We still support Ubuntu 18.04 which doesn't have it, that's why we don't use it (we even already had a PR adding this, but it failed on 18.04).
</blockquote></details>

Yup, we wanted to do that long time ago, but were unable due to too old kernels on some distros (namely Ubuntu18.04 with kernel 4.15).

---


<!-- Sent from Reviewable.io -->

2022-04-22 11:31 UTC, woju commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0G1M5yCQKKuQgensTB:b-nv6n2k) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yup, we wanted to do that long time ago, but were unable due to too old kernels on some distros (namely Ubuntu18.04 with kernel 4.15).
</blockquote></details>

https://ubuntu.com/blog/ubuntu-22-04-lts-released, which means we can drop 18.04 now (when someone gets around to switch CI)

---


<!-- Sent from Reviewable.io -->

2022-04-22 12:03 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0G8mPICVI-Ft4fXU3V:b-cflumh) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://ubuntu.com/blog/ubuntu-22-04-lts-released, which means we can drop 18.04 now (when someone gets around to switch CI)
</blockquote></details>

How does that affect our 2 releases warning policy? I mean, you wouldn't be able to build and run Gramine on ubuntu18.04 anymore (not only unsupported - it just wouldn't work).

---


<!-- Sent from Reviewable.io -->

2022-04-22 13:14 UTC, woju commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0GORJB1qfdHa5vanf9:bhshusb) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How does that affect our 2 releases warning policy? I mean, you wouldn't be able to build and run Gramine on ubuntu18.04 anymore (not only unsupported - it just wouldn't work).
</blockquote></details>

Which "warning" policy? I think we have distro support policy which states we support last 2 releases. Yesterday, bionic (18.04) became third last release, so we don't guarantee anything would work on it.

---


<!-- Sent from Reviewable.io -->

2022-04-22 13:27 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0GRqJsCxfRkBOKjbd2:buvqrvl) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Which "warning" policy? I think we have distro support policy which states we support last 2 releases. Yesterday, bionic (18.04) became third last release, so we don't guarantee anything would work on it.
</blockquote></details>

I meant breaking changes. If we introduce one, we are supposed to make the old version work as well for some time. Idk it this applies to this case.
cc @dimakuv @mkow 

---


<!-- Sent from Reviewable.io -->

2022-04-22 13:31 UTC, woju commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0GSbxG0ZT69MjlKWyc:b-orn12g) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant breaking changes. If we introduce one, we are supposed to make the old version work as well for some time. Idk it this applies to this case.
cc @dimakuv @mkow 
</blockquote></details>

IIUC this is orthogonal. If this change won't break anything on a supported distro, then it's OK to commit it now (apart from CI).

---


<!-- Sent from Reviewable.io -->

2022-04-25 07:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0UhRUsCr4nrcai9CYG:b-229fa) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IIUC this is orthogonal. If this change won't break anything on a supported distro, then it's OK to commit it now (apart from CI).
</blockquote></details>

Actually, why do we care about `MAX_FIXED_NOREPLACE` at all? What is the real-world case when this is necessary? @junjungu1 was there a particular bug/failure that you observed in Gramine, or is it more of a theoretical fix?

I wouldn't like to break stock Ubuntu 18.04 just yet. Especially if there is no good practical reason for it.

---


<!-- Sent from Reviewable.io -->

2022-04-25 08:42 UTC, JunjunGu1 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0Uofno-9nZf9xeHAl4:bycjrix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we care about `MAX_FIXED_NOREPLACE` at all? What is the real-world case when this is necessary? @junjungu1 was there a particular bug/failure that you observed in Gramine, or is it more of a theoretical fix?

I wouldn't like to break stock Ubuntu 18.04 just yet. Especially if there is no good practical reason for it.
</blockquote></details>

I don't see any problem that Gramine has with MAP_FIXED in ubuntu. 
We used to meet a problem in fedora when we mmap enclave to a low address with MAP_FIXED with SGX SDK . 
So I thought it's better to use MAP_FIXED_NOREPLACE.
Gramine doesn't support fedora and still wants to support ubuntu 18.04.
So I will close the pr.

---


<!-- Sent from Reviewable.io -->

2022-04-25 08:43 UTC, closed without merging

2022-04-26 01:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/543)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0YVnm1CrIlWywYOKfX:bjx79li) (no related file):*
I agree with @woju on this, distro support is orthogonal to features deprecation. We support only 2 latest Ubuntu LTSes, which means that at the time of a release the sources+build published in it will work on the 2 latest (at the time of publishing) LTSes.

Feature deprecation is different, because this isn't something known in advance to the users, so after implementing such a change we need to keep backward compatibility for some time so that the users may adjust to the changes.

> Actually, why do we care about `MAX_FIXED_NOREPLACE` at all?

Because `MAX_FIXED` is a huge footgun. We want to notice it if we accidentally overwrite some memory, instead of silently continuing.

Anyways, this change needs to wait until we drop 18.04 support (will happen somewhen in upcoming weeks/months).

---


<!-- Sent from Reviewable.io -->

2022-04-26 06:42 UTC, dimakuv commented
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/543#-N0F4NPg534-vOK1CuFN:-N0ZaYbf7s3W71WN75zO:b-p97voi) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I agree with @woju on this, distro support is orthogonal to features deprecation. We support only 2 latest Ubuntu LTSes, which means that at the time of a release the sources+build published in it will work on the 2 latest (at the time of publishing) LTSes.

Feature deprecation is different, because this isn't something known in advance to the users, so after implementing such a change we need to keep backward compatibility for some time so that the users may adjust to the changes.

> Actually, why do we care about `MAX_FIXED_NOREPLACE` at all?

Because `MAX_FIXED` is a huge footgun. We want to notice it if we accidentally overwrite some memory, instead of silently continuing.

Anyways, this change needs to wait until we drop 18.04 support (will happen somewhen in upcoming weeks/months).
</blockquote></details>

@mkow During our Gramine meeting on Monday (you weren't there), we agreed on the following principle: Ubuntu 18.04 will be still supported and packaged for Gramine v1.2. But we specify in the RELEASE NOTES and everywhere else that Gramine v1.3 will drop support for 18.04 (because we promise support only for 2 last releases).

I think it makes sense, and we actually have a nice way to warn users (through RELEASE NOTES).

---


<!-- Sent from Reviewable.io -->