[LibOS] Implement `mmap` for encrypted and tmpfs files
gramineproject/gramine pull request #550
Opened 2022-04-26 10:16 UTC by pwmarcz

## Description of the changes 

This adds support for "emulated" memory mappings in LibOS. Memory is written back to the file using a new `msync` callback.

This (and #539) bring us to feature parity with SGX protected files, so the next step will be to replace the old implementation (see issue: #371).

## How to test this PR? 

There is a new LibOS regression test, `mmap_file_emulated`, that checks reading and writing an emulated file. In addition, some tmpfs tests are now unskipped.

2022-04-27 08:02 UTC, dimakuv requested changes
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dn46I6D47pt44YEgZ):*
`on an` -> `on`
___
*[`LibOS/shim/include/shim_fs.h` line 113 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dpfUZ76to_szX7vcx:-N0dpfUZ76to_szX7vcy:ba5r8bq) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/include/shim_fs.h#L113)):*
> ```objc
>      */
>     int (*msync)(struct shim_handle* hdl, void* addr, size_t size, int prot, int flags,
>                 uint64_t offset);
> ```

Why do we need `prot` argument here? UPDATE: Ok, because we can have a write-only protection and we want to read the contents of the VMA to write them into the file. So we memorize the original protections, then add R and perform msync, then restore original protections.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1266 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dtRzF1VfJgdG8kbgT:-N0dtRzF1VfJgdG8kbgU:bfzd0t4) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/bookkeep/shim_vma.c#L1266)):*
> ```C
> }
> 
> static int _msync_all(uintptr_t begin, uintptr_t end, struct shim_handle* hdl) {
> ```

Looks like a potentially very slow operation because it iterates through *all* VMAs every time it's called. I guess nothing can be done about it, but do you think it can be a perf bottleneck? I can imagine big applications with thousands of VMAs allocated...
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1285 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dsdSfC7hDV9OcvCr4:-N0dsdSfC7hDV9OcvCr5:b-tb9y3o) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/bookkeep/shim_vma.c#L1285)):*
> ```C
>         uintptr_t msync_end = MIN(end, (uintptr_t)vma_info->addr + vma_info->length);
>         ret = file->fs->fs_ops->msync(file, (void*)msync_begin, msync_end - msync_begin,
>                                       vma_info->prot, vma_info->flags, vma_info->file_offset);
> ```

It's unclear to me if any data races are possible here. Say you collected the relevant VMAs into the `vma_infos` array and started calling `msync()` on each of these VMAs. What if another thread unmapped this VMA, mapped another VMA in the same memory range, and now your `msync()` writes wrong values back into the file?

Hm, on the other hand, looks like it's normal behavior of Linux, where no guarantees for such cases are given for `msync`.
___
*[`LibOS/shim/src/fs/shim_fs_mem.c` line 98 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dod_98Z0z4JdgD5bn:-N0dod_A4U2DYzhJQq3q:ba7c6xj) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/shim_fs_mem.c#L98)):*
> ```C
>     assert((size_t)size <= buf_size);
>     if (buf_size != mem->buf_size) {
>         int ret = mem_file_resize(mem, buf_size);
> ```

Actually, what happens if the user supplies `size = 0`? Won't we end up with `buf_size = 0` and then `mem_file_resize()` will fail with `-ENOMEM`? Which is not how truncate is supposed to work.
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dw8JE0PoH4ms-b7-x:-N0dw8JE0PoH4ms-b7-y:blxay93) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/shim_fs_util.c#L173)):*
> ```C
>         assert((size_t)count <= read_size);
>         read_size -= count;
>         read_addr += count;
> ```

Technically we shouldn't use `void*` because it doesn't allow pointer arithmetic. We should technically use `char*`, but I don't insist.
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 195 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dwqjr05liiZfmX5nl:-N0dwqjr05liiZfmX5nm:b-k570fe) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/shim_fs_util.c#L195)):*
> ```C
> int generic_emulated_msync(struct shim_handle* hdl, void* addr, size_t size, int prot, int flags,
>                            uint64_t offset) {
>     assert(!(flags & MAP_PRIVATE));
> ```

Well, you could add more flags here, e.g. `ANONYMOUS`. Why did you decide on this particular assert?
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dxcI8Ep5yHB2ddB9R:-N0dxcI8Ep5yHB2ddB9S:br0ijio) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/shim_fs_util.c#L222)):*
> ```C
>         }
> 
>         if (count == 0)
> ```

Can this happen?
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 227 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0e1bdwEKXK3OsTkwwY:-N0e1bdwEKXK3OsTkwwZ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/shim_fs_util.c#L227)):*
> ```C
>         assert((size_t)count <= write_size);
>         write_size -= count;
>         write_addr += count;
> ```

ditto
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dxxjE1y3c3sln-IS2:-N0dxxjE1y3c3sln-IS3:b-1r30gf) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L31)):*
> ```C
>  * - truncate (the current `truncate` operation works only for extending the file, support for
>  *   truncation needs to be added to the `protected_files` module)
>  * - flush all files on process exit
> ```

Why didn't you implement it in this PR? It will be a follow-up?
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 373 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dyOon7_KbV8kRvKCt:-N0dyOon7_KbV8kRvKCu:b-6t68v8) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L373)):*
> ```C
>     assert(hdl->inode->type == S_IFREG);
> 
>     int ret = msync_handle(hdl);
> ```

I'm confused here. Why do we have both `msync_handle()` and `encrypted_file_flush()`? Aren't they doing the same?
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 405 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dmV8g8j6MAb67ggxh:-N0dmV8g8j6MAb67ggxi:b-qwa7gh) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L405)):*
> ```C
> 
>     lock(&hdl->inode->lock);
>     int ret = encrypted_file_read(enc, buf, count, *pos, &actual_count);
> ```

Ouch. So this bug went unnoticed because the only user of this callback was `shim_do_read()` (which anyhow supplies `&hdl->pos` in the `pos` argument)? And now you added the `mmap` emulation that uses this callback too, but from an arbitrary `pos`, and that's how you exposed the bug?

Same question for the bug in `chroot_encrypted_write()` below.
___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0dzAQYCMVlZuV1EX1P:b7h4847) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
> ```C
>    are currently not flexible enough for correct tmpfs implementation. In particular, shim_do_mmap()
>    pre-allocates memory region at a specific address ( [...]

2022-04-27 13:10 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1266 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dtRzF1VfJgdG8kbgT:-N0f4EotAu6KFvMnn6uG:b-ee5lx6) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/bookkeep/shim_vma.c#L1266)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You're right. I used the function for dumping *all* VMAs, but it can be adapted to dump all VMAs in range (and they're stored in an AVL tree, so lookup will be cheap). Fixed.
</blockquote></details>

Awesome solution!
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1285 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dsdSfC7hDV9OcvCr4:-N0f4LKC6ooxsq8xdxiO:b-nuglgy) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/bookkeep/shim_vma.c#L1285)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, unfortunately... This `msync` could write wrong values, or even crash if the memory is unmapped by another thread.

I don't see an easy way around it: VMA operations take a lock, but you cannot do anything while holding that lock (since even `malloc` might trigger mapping more memory).
</blockquote></details>

Yep. Anyway, resolved.
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dxxjE1y3c3sln-IS2:-N0f50wbD4RTnRkbP_SR:b-1hcu2r) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L31)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, I'm not sure how to even do that. I would like to call `flush()` on all the handles in the process, but do we have a list of them? There is the "handle map" which maps FDs to handles, but we might keep some open handles _without_ FDs in the memory mappings (if someone did `mmap()` and then `close()`).
</blockquote></details>

Oh no. @boryspoplawski @mkow Do you know how we can collect all handles, even the ones without an atteched FD?

But anyway, I think this is for a follow-up PR.
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 373 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dyOon7_KbV8kRvKCt:-N0f6DRw-mB6znSCbfwQ:b-tkbjoj) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L373)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`flush` is a callback for the `sync` system call, and it's supposed to also flush file mappings. We could call `chroot_encrypted_msync` here, but we don't know what mappings we should call it on (and I thought it would be better NOT to duplicate this information in handle). So we call `msync_handle`, means basically "find all shared mappings of this file and call `msync` on them".
</blockquote></details>

Ok. Pawel's explanation didn't help me much, but I explained it to myself like this:

- `msync_handle()` ends up in `ipf_write()` -- which performs memcpy from mmapped memory region into the corresponding nodes of the protected/encrypted file (i.e., from the mmap memory region into the file-blocks-in-plaintext memory region)
- `encrypted_file_flush()` ends up in `ipf_internal_flush()` -- which performs writes of file-blocks-in-plaintext into the host-level files.

So we have two levels of indirection here: first sync from mmap region to file-blocks region, then sync from file-blocks region to host-level file. That's why two functions are used together.

Maybe will be helpful for other reviewers or for future.
___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0f7Hoi1zN9DHN6zijP:b-f0b3ft) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's possible, but unlike Linux, they will not be synchronized: if you modify one, the other will stay the same.

I added a second mapping to the test.
</blockquote></details>

Wait, but is it Ok?
___
*[`LibOS/shim/test/regression/mmap_file_emulated.c` line 69 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0e0u2vBTZIYe9yquGx:-N0f85Ww9vfaJsT3q9J3:b-z27p04) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/test/regression/mmap_file_emulated.c#L69)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I added a second mapping with offset != 0. This covers the following cases: two mappings, shared/private, and different offsets.
</blockquote></details>

Thanks, looks awesome!


<!-- Sent from Reviewable.io -->

2022-04-27 21:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: 8 of 17 files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`LibOS/shim/include/shim_fs.h` line 89 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fdNEU7nvJdXHzWOdA:-N0gXdIS1lehfX6CR4_y:b-dywzp5) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this artificial disallowance of `NULL`?
Update: is it because it's passed as is to PAL API which still requires it?
</blockquote></details>

Yes. PAL interprets NULL as "use any address".
___
*[`LibOS/shim/include/shim_fs.h` line 91 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fBPlS7WZ8UK1Hk95z:-N0gXl7d6hB9QLR47O1G:bidrs83) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why these are `PAL_PROT_*`??
Update: from what I can see these are Linux prot, not PAL...
</blockquote></details>

Right. Fixed.
___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0evIM64zw9GYqLQqq0:-N0gXtIs8BOyJlnBe0rm:btx8cls) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please comment all args. 
</blockquote></details>

OK, they're the same as `mmap` though. I modified the description to make that clear.
___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0gYLcg6SeDKWV-_ebg:b-fntqhz) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need `flags` argument?
</blockquote></details>

See the implementation. We sometimes need to call PAL to change permissions, and that requires both `prot` and `flags`:

```c
pal_prot_flags_t pal_prot = LINUX_PROT_TO_PAL(prot, flags);
```
___
*[`LibOS/shim/include/shim_vma.h` line 131 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fFZbb0J1LGuaB51RO:-N0gYd28DWpZPKd_UHjj:bnjk5qx) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_vma.h#L131)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this? In which cases we need to call msync based on handle not address range?
</blockquote></details>

When the user requests to sync a specific handle, using the `sync` syscall (our `flush` callback).
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1119 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fNhHO-pAwfonXdw8X:-N0gYxtV6sGXhtE1NVnB:b-3ga6w5) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How is this case possible?
</blockquote></details>

My mistake, somehow I thought `_lookup_vma` returns the VMA *before* address, not after. Removed.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1173 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fOJyc9B66_D4xjAzX:-N0gZfsl4SEvDAbGZ2kw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1173)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `UINTPTR_MAX`.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1174 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fOfNUBcdXgBcvmYLW:-N0g_4Wu5f0ScIEvKHmz:bkmmaxw) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1174)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No need for `&` with function pointers.
</blockquote></details>

I thought we use `&` for clarity; I pretty universally used it in my code so far and nobody complained (most notably, all the code where we setup pseudofs). On the other hand, I see @mkow not using `&` in his sysfs code with callbacks.

Removed `&` for now.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1246 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fPYRfAnltXnVjnGtU:-N0gaOOh1OJiXdVWd-y-:b-rvgp81) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this case possible? We check for `MAP_ANONYMOUS` above.
</blockquote></details>

Yeah, it makes sense that `vma->file` would always be present. I wasn't sure because this module never enforces or documents this, so we depend on callers.

Replaced with assertion.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1252 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fPhvmA28yj9oVmC8x:-N0gcSPnES1tewPg3xVs:b-2la1kx) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we need a lock for this?
Conceptually we shouldn't, but on the current master I think it's required, but I'm not sure.
</blockquote></details>

Yeah, we still modify it in socket code. I'll add a lock and a TODO here.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1261 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0f_2MJ9lAPaP4AHhDt:-N0gdwvkCCTVsYrKmjzQ:b-25y4ak) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1261)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please assert that `begin` and `end` are page aligned.
</blockquote></details>

OK. This is a bit awkward because of `UINTPTR_MAX`, but I don't know how to do it better.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1261 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0faZJH2mrg32AENycx:-N0ge47x5icsST9VcuqS:b-mwhan6) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1261)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We usually use names with leading underscore to highlight functions which must be called with *some* locks taken.
Not blocking - this is rather informal convention.
</blockquote></details>

I called this `_msync_all` back when I actually had a function called `msync_all` (it wasn't about a lock, but about defining a helper function). That's not necessary now, so I'm removing the underscore.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1265 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fQ6aa3zSHTkzUcDC5:-N0ge3M-7Y0i3VR4yU4F:b-896fix) ([raw file](https://github.com/gramineproject/gra [...]

2022-04-27 22:52 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[`LibOS/shim/include/shim_fs.h` line 89 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fdNEU7nvJdXHzWOdA:-N0h7P944YsmGwKQnwnS:b-81la7d) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L89)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. PAL interprets NULL as "use any address".
</blockquote></details>

Right
___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0h7lQz58ptc9FK7XAa:b-gr11qm) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

See the implementation. We sometimes need to call PAL to change permissions, and that requires both `prot` and `flags`:

```c
pal_prot_flags_t pal_prot = LINUX_PROT_TO_PAL(prot, flags);
```
</blockquote></details>

Not sure how much of an implementation details it is, but they only care for `MAP_PRIVATE`, which we know to be false in `msync`.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1174 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fOfNUBcdXgBcvmYLW:-N0h8KSvEOrcSr0t8hjC:b3od7gn) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1174)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I thought we use `&` for clarity; I pretty universally used it in my code so far and nobody complained (most notably, all the code where we setup pseudofs). On the other hand, I see @mkow not using `&` in his sysfs code with callbacks.

Removed `&` for now.
</blockquote></details>

Hmm, I guess we have no official policy and it's a matter of preference. Should have mentioned it, but not blocked, my bad.
I personally prefer no `&`, because these are function pointers, and that should be clear from the name itself and the `&` is not needed, like, we already know it's a function/pointer.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1252 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fPhvmA28yj9oVmC8x:-N0h8yqB8-Ni9W1gPxsZ:brtjszr) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1252)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, we still modify it in socket code. I'll add a lock and a TODO here.
</blockquote></details>

Hmmm, actually, are we allowed to take any locks here? We are inside vmas traversing function, under global vma lock, I think.
In reality `acc_mode` can't change for anything other than sockets, so maybe we can just ignore the lock, leave a `XXX` describing the situation, to be removed when we clear semantics of accessing `acc_mode` (which we should do after sockets rewrite)
wdyt? Above I assumed that only sockets are the issue.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1261 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0f_2MJ9lAPaP4AHhDt:-N0h9k8N6GTxZYLJhNvI:b-fgak3n) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1261)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. This is a bit awkward because of `UINTPTR_MAX`, but I don't know how to do it better.
</blockquote></details>

Right. But I guess it's ok
___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 373 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dyOon7_KbV8kRvKCt:-N0hAmaX6cKOnBtRHpap:bs7bmwu) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L373)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`encrypted_file_flush` only works with the encrypted-file object. It has no idea that we're *also* keeping emulated mappings (and in fact, does not depend on `shim_handle` or `shim_vma` or anything else in the system; it just takes care of that one object).

I added comments here to explain that better.
</blockquote></details>

Well, I'm not familiar with the new PF implementation, so I would have to check it out. Resolving.
___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0hBHkx4VtiXIFAyEmi:b-ddchhy) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What do you mean? Emulated mappings should work exactly the same for tmpfs and encrypted fs:

- it is possible to have many mappings of a single file,
- the mappings are *not* updated automatically, we just fill them on mmap and write back to file on mmap.

This is not "correct", but a useful approximation, and what we always had for protected files.
</blockquote></details>

I guess nothing really relies on mapping the same file twice? Maybe the current version won't hurt anybody, idk


<!-- Sent from Reviewable.io -->

2022-04-28 06:26 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1252 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fPhvmA28yj9oVmC8x:-N0ioIwN7ZtILnMEFnQH:bl9kz12) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmmm, actually, are we allowed to take any locks here? We are inside vmas traversing function, under global vma lock, I think.
In reality `acc_mode` can't change for anything other than sockets, so maybe we can just ignore the lock, leave a `XXX` describing the situation, to be removed when we clear semantics of accessing `acc_mode` (which we should do after sockets rewrite)
wdyt? Above I assumed that only sockets are the issue.
</blockquote></details>

+1. I don't like the idea of having a lock in this function. I think we can safely assume that after the previous check on `msync` callback existence, we can be sure that it's a file handle and then its `acc_mode` is never changed. We can add a comment about this.
___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0iq40q7OUcApl_huHs:bd16fb7) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess nothing really relies on mapping the same file twice? Maybe the current version won't hurt anybody, idk
</blockquote></details>

Yeah, nobody ever complained about this. So I think this is not a realistic scenario. Indeed, why would an app want to map the same file twice. I'm resolving.


<!-- Sent from Reviewable.io -->

2022-04-28 08:36 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: 15 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0jCk200171GptRssgd:b-6x95oc) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure how much of an implementation details it is, but they only care for `MAP_PRIVATE`, which we know to be false in `msync`.
</blockquote></details>

Oooh, actually, the PAL mapping should not be shared. The Linux-SGX PAL ignores that distinction anyway, but we don't want Linux PAL to create a shared region between processes. So right, the `flags` parameter will be unused here.

I still want to leave the parameter, because:
- it makes for a nice symmetry with the `mmap` callback: they have the same parameters, omitting just one of them would be surprising,
- we get to have an `assert` that we're not flushing a Gramine-level `MAP_PRIVATE` mapping.
___
*[`LibOS/shim/src/bookkeep/shim_vma.c` line 1252 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fPhvmA28yj9oVmC8x:-N0jG_hA2jktoaWgyIg7:b-v5ffb) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/src/bookkeep/shim_vma.c#L1252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. I don't like the idea of having a lock in this function. I think we can safely assume that after the previous check on `msync` callback existence, we can be sure that it's a file handle and then its `acc_mode` is never changed. We can add a comment about this.
</blockquote></details>

Oh, right, this is under `vma_tree_lock`, I shouldn't do that.

Changed as suggested.
___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0jCQzS2fLp0Nw3anXG:bmdlpfw) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
>Indeed, why would an app want to map the same file twice.

Well, there's the [magic ring buffer trick](https://abhinavag.medium.com/a-fast-circular-ring-buffer-4d102ef4d4a3) :)


<!-- Sent from Reviewable.io -->

2022-04-28 08:44 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/fs/tmpfs/fs.c` line 295 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dzAQYCMVlZuV1EX1O:-N0jKb9oA2SPJZFN8uM9:bybvs81) ([raw file](https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/src/fs/tmpfs/fs.c#L295)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Indeed, why would an app want to map the same file twice.

Well, there's the [magic ring buffer trick](https://abhinavag.medium.com/a-fast-circular-ring-buffer-4d102ef4d4a3) :)
</blockquote></details>

One `memcpy` instead of two `memcpy`s to allow the compiler to apply vectorization optimizations? Wow, I wonder if people are actually using such tricks to squeze out an additional... 0.001% performance? But maybe I'm wrong, maybe it's useful somewhere.


<!-- Sent from Reviewable.io -->

2022-04-28 15:36 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0kmoeFEp_V0QxJlGHz:b-z2bb8f) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
Ok, let's leave it.

> we don't want Linux PAL to create a shared region between processes

Why is that? Ideally most of the PALs should support shared mappings, so should msync. I guess some of filesystems (e.g. tmpfs) are fully emulated and as such won't create a shared mapping, but that's not part of this interface.
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 147 at r5](https://reviewable.io/reviews/gramineproject/gramine/550#-N0knqqE46xzA9wMzVLu:-N0knqqE46xzA9wMzVLv:b-u3nel9) ([raw file](https://github.com/gramineproject/gramine/blob/f1cbf1987379aa5ba839385e1baee0fd71df9886/LibOS/shim/src/fs/shim_fs_util.c#L147)):*
> ```C
>     int ret;
> 
>     /* The underlying PAL mapping should always be private. */
> ```

I think this deserves more explanation, i.e. why it should be private
___
*[`LibOS/shim/src/fs/shim_fs_util.c` line 206 at r5](https://reviewable.io/reviews/gramineproject/gramine/550#-N0knyf4BUzJLULBX2Hd:-N0knyf4BUzJLULBX2He:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/f1cbf1987379aa5ba839385e1baee0fd71df9886/LibOS/shim/src/fs/shim_fs_util.c#L206)):*
> ```C
>     unlock(&hdl->inode->lock);
> 
>     /* The underlying PAL mapping should always be private. */
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-04-28 17:42 UTC, mkow reviewed
> Reviewed 1 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[`LibOS/shim/src/fs/chroot/encrypted.c` line 31 at r2](https://reviewable.io/reviews/gramineproject/gramine/550#-N0dxxjE1y3c3sln-IS2:-N0lEcpQ2VREWBAedLng:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/9c41ea9c475fc3622cc8ea9bf0aaf7b49e688366/LibOS/shim/src/fs/chroot/encrypted.c#L31)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-04-29 08:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: 16 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0oCoAq3gZHyZ956CSv:b-yzw8m) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, let's leave it.

> we don't want Linux PAL to create a shared region between processes

Why is that? Ideally most of the PALs should support shared mappings, so should msync. I guess some of filesystems (e.g. tmpfs) are fully emulated and as such won't create a shared mapping, but that's not part of this interface.
</blockquote></details>

I agree that this interface (mmap, msync) should include `flags`, and allow shared mappings.

I meant that the current *implementation* of emulated mappings (exactly the case you mention) should probably not share the underlying mappings between processes. It could end up flushing changes made by another process, and I'm not sure if it's a good idea.

However, I just realized that **it actually doesn't matter**: even if we create a shared anonymous mapping, it won't really be shared with another process. LibOS in the child process will just create an identical mapping during checkpoint restore.

So I think both solutions (using `LINUX_PROT_TO_PAL(prot, flags)` and using `LINUX_PROT_TO_PAL(prot, MAP_PRIVATE)`) make some sense. I prefer to use the first one, for simplicity: we do the same elsewhere, and I don't want a special case here that actually has zero effect.


<!-- Sent from Reviewable.io -->

2022-04-29 10:49 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0ovqqs2BmJ2s2TBejU:b-sh6pky) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree that this interface (mmap, msync) should include `flags`, and allow shared mappings.

I meant that the current *implementation* of emulated mappings (exactly the case you mention) should probably not share the underlying mappings between processes. It could end up flushing changes made by another process, and I'm not sure if it's a good idea.

However, I just realized that **it actually doesn't matter**: even if we create a shared anonymous mapping, it won't really be shared with another process. LibOS in the child process will just create an identical mapping during checkpoint restore.

So I think both solutions (using `LINUX_PROT_TO_PAL(prot, flags)` and using `LINUX_PROT_TO_PAL(prot, MAP_PRIVATE)`) make some sense. I prefer to use the first one, for simplicity: we do the same elsewhere, and I don't want a special case here that actually has zero effect.
</blockquote></details>

But these are 2 different versions, because (as per comment) `flags` **must** contain `MAP_SHARED` (not `MAP_PRIVATE`).


<!-- Sent from Reviewable.io -->

2022-04-29 10:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0ow8ot0SslHC7Lhl8F:bqeczwp) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But these are 2 different versions, because (as per comment) `flags` **must** contain `MAP_SHARED` (not `MAP_PRIVATE`).
</blockquote></details>

I mean, one day, when we have a fully working shared mappings on *some* PALs, how do one find that these places needs to be fixed? Or maybe the  wouldn't need to be?


<!-- Sent from Reviewable.io -->

2022-04-29 10:52 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`LibOS/shim/include/shim_fs.h` line 112 at r3](https://reviewable.io/reviews/gramineproject/gramine/550#-N0fCudh948XAoxrD3a4:-N0oworc-bBFQR-uXTS_:bb3pwio) ([raw file](https://github.com/gramineproject/gramine/blob/496c28fccfda5df189b14ac514fab9683e8f8e89/LibOS/shim/include/shim_fs.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I mean, one day, when we have a fully working shared mappings on *some* PALs, how do one find that these places needs to be fixed? Or maybe the  wouldn't need to be?
</blockquote></details>

Ok, I guess these are implementations of `mmap` and `msync`, so they will need to be revisited then.


<!-- Sent from Reviewable.io -->

2022-04-29 11:03 UTC, dimakuv approved these changes
> Reviewed 4 of 9 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/550)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-29 11:32 UTC, merged