[LibOS] Reimplement call to elf entrypoint
gramineproject/gramine pull request #569
Opened 2022-05-06 07:42 UTC by oshogbo

## Description of the changes 
As mentioned in https://github.com/gramineproject/gramine/pull/541, we would like to convert an AT&T assembly to Intel one. As I was working mainly with the entrypoint, I think this is an excellent start to experiment with it. Gramine already has all entrypoint tests, so it is easier to verify that this change doesn't break anything.

We don't set a register to any particular addresses, as the ABI document doesn't require that. After this change, the value of registers hasn't been changed.

## How to test this PR?
```
gramine-test -C LibOS/shim/test/abi/x86_64/ pytest
gramine-test --sgx -C LibOS/shim/test/abi/x86_64/ pytest

gramine-test -C LibOS/shim/test/fs pytest
gramine-test --sgx -C LibOS/shim/test/fs pytest
gramine-test -C LibOS/shim/test/regression pytest
gramine-test --sgx -C LibOS/shim/test/regression pytest
```

2022-05-06 10:04 UTC, mkow commented
Jenkins, test this please

2022-05-06 11:25 UTC, mkow reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`LibOS/shim/src/arch/x86_64/shim_elf_entry.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/569#-N1NqACuEvKfWyOyTZmW:-N1O6Jjw6mF8jopQ3S9N:bsrdllb) ([raw file](https://github.com/gramineproject/gramine/blob/4fb988e33ef625b512737735e8805244a0ec72d9/LibOS/shim/src/arch/x86_64/shim_elf_entry.asm#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

It just to have the same register values like before previous entrypoint jmp.
But we can remove it.
</blockquote></details>

What "previous entrypoint jump"?


<!-- Sent from Reviewable.io -->

2022-05-06 16:49 UTC, boryspoplawski requested changes
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/569#-N1NqFK_1SemkMdcO1t6:-N1PAIwG1zPT6B9antiY:b-cklrg4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Forgot about this in the previous PRs, but: What extension do we want to use for NASM sources? I think `.nasm` would be better, as assembly syntaxes are all assembler-specific.
</blockquote></details>

Ah, yes. `.nasm` sounds good to me.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/569#-N1PDtsq-V22nENa8gvC:-N1PDtsq-V22nENa8gvD:b-arqt4n) (no related file):*
@stefanberger heads up, we are changing some arch specific files/functions, moving some stuff to assembly files.
Actually, now I realized that `nasm` is x86 specific... Maybe we should change it to `default_asm` in `meson` or something? Or maybe changing the extension to `.nasm` would allow us to specify in meson that all files with `.nasm` should be compiles by `nasm` and remove all these ifs we have now?
cc @mkow 

---
___
*[`LibOS/shim/include/arch/x86_64/shim_internal-arch.h` line 8 at r2](https://reviewable.io/reviews/gramineproject/gramine/569#-N1PBMMVB2hIrQ769zXZ:-N1PBMMVB2hIrQ769zX_:b3lho7i) ([raw file](https://github.com/gramineproject/gramine/blob/e6b7f17d837852d53f98ed7884d29c39daa81af9/LibOS/shim/include/arch/x86_64/shim_internal-arch.h#L8)):*
> ```objc
> #include "elf.h"
> 
> noreturn void call_elf_entry(elf_addr_t entry, void* argp);
> ```

I think this should go into arch independent header.
___
*[`LibOS/shim/src/arch/x86_64/shim_elf_entry.asm` line 14 at r2](https://reviewable.io/reviews/gramineproject/gramine/569#-N1PGA41BM3juUiWo2sa:-N1PGA41BM3juUiWo2sb:b-xhe8b2) ([raw file](https://github.com/gramineproject/gramine/blob/e6b7f17d837852d53f98ed7884d29c39daa81af9/LibOS/shim/src/arch/x86_64/shim_elf_entry.asm#L14)):*
> ```m68k
> global    call_elf_entry
> 
> call_elf_entry:
> ```

It would be good to have a comment with C declaration here (to know the args and types).
___
*[`LibOS/shim/src/arch/x86_64/shim_elf_entry.asm` line 16 at r2](https://reviewable.io/reviews/gramineproject/gramine/569#-N1PFZNb0cPmCb9Xuf9L:-N1PFZNc1NvY8D3510O8:b-npc3e3) ([raw file](https://github.com/gramineproject/gramine/blob/e6b7f17d837852d53f98ed7884d29c39daa81af9/LibOS/shim/src/arch/x86_64/shim_elf_entry.asm#L16)):*
> ```m68k
> call_elf_entry:
>     xor     rdx, rdx ; set RDX to 0
>     push    0
> ```

`0x202` is the default value. x86 will silently set those for you, but it would be more "correct" to set it :)


<!-- Sent from Reviewable.io -->

2022-05-09 06:28 UTC, dimakuv approved these changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-05-09 14:26 UTC, stefanberger reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`LibOS/shim/src/meson.build` line 105 at r2](https://reviewable.io/reviews/gramineproject/gramine/569#-N1d59fK7sV-jWVdx3JM:-N1dCeeLDDwi0sKLSJz-:b-m3bp6t) ([raw file](https://github.com/gramineproject/gramine/blob/e6b7f17d837852d53f98ed7884d29c39daa81af9/LibOS/shim/src/meson.build#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, I think this whole list should be arch specific. We do not impose any particular restrictions on the file types and names here, except that they must implement a bunch of functions. Whether these are implemented in C, asm or javascript doesn't really matther (ok, I might have gone to far with js)
</blockquote></details>

Ok, then let's resolve this in another PR.


<!-- Sent from Reviewable.io -->

2022-05-10 15:53 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/arch/x86_64/shim_elf_entry.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/569#-N1NqACuEvKfWyOyTZmW:-N1ierio5JkWac7Af1dV:b81oc4e) ([raw file](https://github.com/gramineproject/gramine/blob/4fb988e33ef625b512737735e8805244a0ec72d9/LibOS/shim/src/arch/x86_64/shim_elf_entry.asm#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What "previous entrypoint jump"?
</blockquote></details>

The previous version of entrypoint jump (the C/macro one), sets up rax to value of rdi. Its our specific things but I didn't want to change any functional thing here.
But at this point I'm not sure if it makes any sense.


<!-- Sent from Reviewable.io -->

2022-05-10 15:55 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @oshogbo)

___
*[`LibOS/shim/src/arch/x86_64/shim_elf_entry.asm` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramine/569#-N1NqACuEvKfWyOyTZmW:-N1ifbXpAfPuEGYPGNzT:b-6z605q) ([raw file](https://github.com/gramineproject/gramine/blob/4fb988e33ef625b512737735e8805244a0ec72d9/LibOS/shim/src/arch/x86_64/shim_elf_entry.asm#L20)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

The previous version of entrypoint jump (the C/macro one), sets up rax to value of rdi. Its our specific things but I didn't want to change any functional thing here.
But at this point I'm not sure if it makes any sense.
</blockquote></details>

It's not needed, you can remove it.


<!-- Sent from Reviewable.io -->

2022-05-12 20:34 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: 4 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`LibOS/shim/include/shim_internal.h` line 290 at r3](https://reviewable.io/reviews/gramineproject/gramine/569#-N1tG_YP7wJcJlpQPeHE:-N1ty-Pb74AJvDOWRERD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/798062f38a61b953685fea5c59eae6968075afde/LibOS/shim/include/shim_internal.h#L290)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It doesn't have to be `Assembly`
</blockquote></details>

Done.
___
*[`LibOS/shim/src/arch/x86_64/meson.build` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/569#-N1tHAAC86QogaYxXPwp:-N1ty0MC-1wZnRqW1F-Y:b-1wa1ah) ([raw file](https://github.com/gramineproject/gramine/blob/798062f38a61b953685fea5c59eae6968075afde/LibOS/shim/src/arch/x86_64/meson.build#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can't we somehow have all `.nasm` files processes by `nasm_gen`? Like globally in Meson
</blockquote></details>

Not really :( At least I don't know any method.
Maybe instead of defining the type, we can use such notion:
```
libos_sources_arch = files(
    'shim_arch_prctl.c',
    nasm_gen.process('shim_elf_entry.nasm'),
    'shim_context.c',
    'shim_table.c',
    'start.S',
    'syscallas.S',
)
```


<!-- Sent from Reviewable.io -->

2022-05-12 21:24 UTC, stefanberger reviewed
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-05-12 21:30 UTC, boryspoplawski approved these changes
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/arch/x86_64/meson.build` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/569#-N1tHAAC86QogaYxXPwp:-N1uALIR8qJnwoi016Ia:b-mw9unm) ([raw file](https://github.com/gramineproject/gramine/blob/798062f38a61b953685fea5c59eae6968075afde/LibOS/shim/src/arch/x86_64/meson.build#L3)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Not really :( At least I don't know any method.
Maybe instead of defining the type, we can use such notion:
```
libos_sources_arch = files(
    'shim_arch_prctl.c',
    nasm_gen.process('shim_elf_entry.nasm'),
    'shim_context.c',
    'shim_table.c',
    'start.S',
    'syscallas.S',
)
```
</blockquote></details>

Idk, I'm fine with both. For this particular case I prefer the snipped you posted, but not sure how would it look like if we got more `.nasm` files. Up to you.


<!-- Sent from Reviewable.io -->

2022-05-12 21:30 UTC, boryspoplawski commented
Jenkins, test this please

2022-05-12 22:23 UTC, mkow requested changes
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N1uLovwBnH31VnEL5IV:b-8bewk9) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
> ```objc
>  *
>  * \param entry Address defined in the elf entry point.
>  * \param argp Pointer to the initial stack, contains program arguments and environment.
> ```

Please align these (see https://gramine.readthedocs.io/en/latest/devel/howto-doc.html#preferred-doxygen-style).


<!-- Sent from Reviewable.io -->

2022-05-13 08:04 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/569#-N1PDtsq-V22nENa8gvC:-N1wR1BADMdZmIl-pF3z:bfskvdk) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Thanks for letting me know. Maybe you should then conditionally add those nasm files x86_64 and I would do something similar with ppc64 code but have them compiled by gcc or so.

```
if host_machine.cpu_family() == 'x86_64'
   [...]
endif
```

</blockquote></details>

@stefanberger https://github.com/gramineproject/gramine/pull/573 -- this was merged recently.

___


<!-- Sent from Reviewable.io -->

2022-05-13 11:57 UTC, stefanberger reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569#-:-N1xGs9n9yEtDxoeL7x_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-05-13 19:12 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N1ym_fL7vib9aYuNAJm:bptt83) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please align these (see https://gramine.readthedocs.io/en/latest/devel/howto-doc.html#preferred-doxygen-style).
</blockquote></details>

@mkow wait, that example has misaligned comments :) The problem seem to be that the rendered font is not monospaced

@oshogbo recently we adopted a style (which you can see in the repo and the linked example, but before rendering) where we put two spaces after variable name (before comment)


<!-- Sent from Reviewable.io -->

2022-05-13 19:42 UTC, stefanberger reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-05-15 00:59 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N24D6W42PLDzJY3cr1G:b9z8qzs) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@mkow wait, that example has misaligned comments :) The problem seem to be that the rendered font is not monospaced

@oshogbo recently we adopted a style (which you can see in the repo and the linked example, but before rendering) where we put two spaces after variable name (before comment)
</blockquote></details>

@boryspoplawski: Hmm, for me it renders in monospace.

@oshogbo: This is still not done (not enough spaces after `entry`).


<!-- Sent from Reviewable.io -->

2022-05-15 01:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N24Hv4I8cyd5ngSr1yx:bg38bo9) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Hmm, for me it renders in monospace.

@oshogbo: This is still not done (not enough spaces after `entry`).
</blockquote></details>

@mkow weird
![screen.png](https://files.reviewableusercontent.io/images/reviewable/5228082/pUOSjc32h_koGRjQXGfV7zJA/screen.png)


<!-- Sent from Reviewable.io -->

2022-05-15 01:29 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N24JZ8z9MqvLzwCFivX:bdekgbp) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@mkow weird
![screen.png](https://files.reviewableusercontent.io/images/reviewable/5228082/pUOSjc32h_koGRjQXGfV7zJA/screen.png)

</blockquote></details>

Hehe, your font _is_ monospace, but for some reason something decided to use a ligature for "fi".
@woju ^


<!-- Sent from Reviewable.io -->

2022-05-15 01:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N24LrctC9TfPv-9IRxe:bdqv3n3) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hehe, your font _is_ monospace, but for some reason something decided to use a ligature for "fi".
@woju ^
</blockquote></details>

Seems like a firefox on linux thing: https://github.com/BlueBrain/sphinx-bluebrain-theme/issues/36


<!-- Sent from Reviewable.io -->

2022-05-15 01:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N24MGIj4qE7zneRhvRG:bhkjqao) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Seems like a firefox on linux thing: https://github.com/BlueBrain/sphinx-bluebrain-theme/issues/36
</blockquote></details>

Probably adding stealing that commit and adding to our css would solve this


<!-- Sent from Reviewable.io -->

2022-05-16 06:21 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)

___
*[`LibOS/shim/include/shim_internal.h` line 292 at r5](https://reviewable.io/reviews/gramineproject/gramine/569#-N2AWTwSCjdA6vevZGaR:-N2AWTwTBU5wGncwvZqS:b-mucp8g) ([raw file](https://github.com/gramineproject/gramine/blob/3ff77dfb21d72686031022ec0d4c9246fdc569de/LibOS/shim/include/shim_internal.h#L292)):*
> ```objc
>  * \brief Jump to the defined entry point.
>  *
>  * \param entry Address defined in the elf entry point.
> ```

This is still not according to the guideline -- there must be at least two spaces between the variable name and its description.


<!-- Sent from Reviewable.io -->

2022-05-16 12:35 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @oshogbo, and @woju)

___
*[`LibOS/shim/include/shim_internal.h` line 293 at r4](https://reviewable.io/reviews/gramineproject/gramine/569#-N1uLovwBnH31VnEL5IU:-N1xH8Ax0q-fSzWQ6uMQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9740deec199decc503828603fb679ac57d359070/LibOS/shim/include/shim_internal.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please align these (see https://gramine.readthedocs.io/en/latest/devel/howto-doc.html#preferred-doxygen-style).
</blockquote></details>

Done.
___
*[`LibOS/shim/src/arch/x86_64/meson.build` line 3 at r3](https://reviewable.io/reviews/gramineproject/gramine/569#-N1tHAAC86QogaYxXPwp:-N1xGoCP7Tg60O_x1C1i:bocrn1w) ([raw file](https://github.com/gramineproject/gramine/blob/798062f38a61b953685fea5c59eae6968075afde/LibOS/shim/src/arch/x86_64/meson.build#L3)):*
> libos_sources_arch = files(
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

>     'shim_arch_prctl.c',
>     nasm_gen.process('shim_elf_entry.nasm'),
>     'shim_context.c',
>     'shim_table.c',
>     'start.S',
>     'syscallas.S',
</details>
> )
Oh it seems that this won't work as nasm_gen.process already produces the object so we can't pass it to the file().
This means we would need to do something like:
```
> libos_sources_arch = files(
    'shim_arch_prctl.c',
    'shim_context.c',
    'shim_table.c',
    'start.S',
    'syscallas.S',
) + nasm_gen.process('shim_elf_entry.nasm')
```
So I will leave it as it is.


<!-- Sent from Reviewable.io -->

2022-05-16 12:40 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo and @woju)



<!-- Sent from Reviewable.io -->

2022-05-16 13:39 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-05-16 13:40 UTC, dimakuv commented
Jenkins, test this please

2022-05-16 15:15 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-05-16 15:23 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-16 15:24 UTC, mkow commented
Jenkins, retest this please

2022-05-16 15:59 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/569)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-16 16:08 UTC, merged