[common] Create DO_ONCE
gramineproject/gramine pull request #572
Opened 2022-05-09 13:02 UTC by NieDzejkob

## Description of the changes

In #525, @boryspoplawski suggested that a macro like this would be too complicated to be worthwhile. Having actually drafted an implementation, I don't think it looks too bad. In fact, I believe this turns the preferred approach of doing something once per enclave into something you have a chance of remembering.

## How to test this PR?

You may run a program that triggers once of the warnings that make use of `DO_ONCE`, and verify that the warning, indeed, happens once. For example:

```c
#include <stdint.h>
#include <sys/mman.h>

int main(void) {
    unsigned char output[16];
    uintptr_t addr = (uintptr_t) main;
    addr &= ~0xfff;
    mincore((void*)addr, 4096, output);
    mincore((void*)addr, 4096, output);
    mincore((void*)addr, 4096, output);
    return 0;
}
```

2022-05-09 13:23 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxJ4M3ZU6APQuaZJc:-N1cxJ4M3ZU6APQuaZJd:binux35) (no related file):*
> In #525, @boryspoplawski suggested that a macro like this would be too complicated to be worthwhile.

That was about passing a block of code into the macro

---
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
This deserves at least a one sentence explaining what is that and what it does.
Also please append `macro` to the oneliner
___
*[`common/include/api.h` line 195 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cy6LK9-SBlrkgePzF:-N1cy6LL3j-yg9SvUVtx:bdqoj0o) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L195)):*
> ```objc
> #define IS_IN_RANGE_INCL(value, start, end) (((value) < (start) || (value) > (end)) ? false : true)
> 
> /* Each occurence of this macro in the source code will returns `true` only once per enclave.
> ```

What enclave? This is common code.
___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1cyHWS8yeY3vcrK-Xs:b-d9gfa9) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
> ```objc
>  * as memory ordering is concerned. In particular, since there isn't any synchronization to
>  * signal when an `if (DO_ONCE)` block is done executing, returning `false` doesn't constitute
>  * any guarantees about the variables modified within the `if (DO_ONCE)` block. */
> ```

What's the point of this comment? We do not explain on every function/macro that it does guarantee any ordering for the rest of the code.
___
*[`common/include/api.h` line 201 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxj9KEHZaFhGGkeCx:-N1cxj9KEHZaFhGGkeCy:bl2chmn) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L201)):*
> ```objc
>  * signal when an `if (DO_ONCE)` block is done executing, returning `false` doesn't constitute
>  * any guarantees about the variables modified within the `if (DO_ONCE)` block. */
> #define DO_ONCE ({ static uint8_t first = 0; __atomic_exchange_n(&first, 1, __ATOMIC_RELAXED) == 0; })
> ```

`DO_ONCE()`. This looks like a constant, not a piece of code.


<!-- Sent from Reviewable.io -->

2022-05-09 13:24 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1czQSR6WUQrNamtIQT:bvgahfj) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this comment? We do not explain on every function/macro that it does guarantee any ordering for the rest of the code.
</blockquote></details>

\***does not**


<!-- Sent from Reviewable.io -->

2022-05-09 14:29 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Sure thing, should I force-push and change that or is there a better approach?
</blockquote></details>

Add a squash commit with something like: `TODO: new commit message:` and new commit message below. Just remember that the part after `squash!` must match the oneliner here

I propose the new oneliner to be: `[common] Create DO_ONCE() macro`
___
*[`common/include/api.h` line 195 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cy6LK9-SBlrkgePzF:-N1dC9gLEypz0PzVc-3h:bbtww1l) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L195)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Fair enough. I wanted to stress that nothing like a sync between all the processes. Is `s/enclave/process/` general enough?
</blockquote></details>

Yeah, it's ok
___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1dCJ7l3lXw9PHPI6rQ:bpd45ve) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Yes, we do not explain it everywhere, but this macro has the rough shape of a synchronization primitive, so I believe it's not exactly unwarranted.

The point of the comment is to (attempt to) convey my understanding as to why `__ATOMIC_RELAXED` is enough here.
</blockquote></details>

But memory ordering of this access has nothing to with synchronization of the whole block. If you used `__ATOMIC_SEQ_CST` or did a full memory barrier, the result would be exactly the same - no synchronization  on stuff used in the code block.


<!-- Sent from Reviewable.io -->

2022-05-09 15:33 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1dS06VAdUjtRikaycp:b-mpgmvj) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
> ```C
>     /* If process_exit is invoked multiple times, only a single invocation proceeds past this
>      * point. */
>     if (!DO_ONCE()) {
> ```

Considering this usage, perhaps a name like `FIRST_TIME()` would be better?


<!-- Sent from Reviewable.io -->

2022-05-09 15:36 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @NieDzejkob)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1dS8zk0-R3x2XiKKjl:b-m4ilev) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But memory ordering of this access has nothing to with synchronization of the whole block. If you used `__ATOMIC_SEQ_CST` or did a full memory barrier, the result would be exactly the same - no synchronization  on stuff used in the code block.
</blockquote></details>

Yes. And because there is no synchronization on stuff used within the block, we don't need any guarantees on how accesses to `first` will be ordered relative to anything else.

Do you think you can write a better explanation?


<!-- Sent from Reviewable.io -->

2022-05-09 17:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1doK-50OrtPGWZCfav:br9v6yv) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
> And because there is no synchronization on stuff used within the block.

This is false, we cannot assume that. There might be.


<!-- Sent from Reviewable.io -->

2022-05-09 20:51 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @NieDzejkob, and @pwmarcz)

___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1e_qEJ3VdZyw12kGcj:b-2szbj7) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Considering this usage, perhaps a name like `FIRST_TIME()` would be better?
</blockquote></details>

I'm fine with both names.
@boryspoplawski, @dimakuv, @pwmarcz: ^


<!-- Sent from Reviewable.io -->

2022-05-09 21:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @NieDzejkob, and @pwmarcz)

___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1ekegQ9COOuaWlxDt_:be6orxk) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with both names.
@boryspoplawski, @dimakuv, @pwmarcz: ^
</blockquote></details>

I prefer `DO_ONCE`, but very, very slightly.


<!-- Sent from Reviewable.io -->

2022-05-10 07:15 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @NieDzejkob, and @pwmarcz)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Add a squash commit with something like: `TODO: new commit message:` and new commit message below. Just remember that the part after `squash!` must match the oneliner here

I propose the new oneliner to be: `[common] Create DO_ONCE() macro`
</blockquote></details>

Another simpler approach to this is to block yourself here in Reviewable, with a comment like "Change the commit message to `Bla bla bla`". I prefer this way to `squash!` commits.
___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1gnjZO7lytYd14zBXl:bifmd3f) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> And because there is no synchronization on stuff used within the block.

This is false, we cannot assume that. There might be.
</blockquote></details>

I too think that this explanation is too verbose. I think we can keep the first sentence (`We use ...`). But we can drop the second sentence (`In particular ...`).

Basically, we just want to give a hint to future readers that we indeed intended to use `__ATOMIC_RELAXED`. We don't want to explain each and every detail in our code.
___
*[`common/include/api.h` line 198 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1gnf225GrBHfXFDVvk:-N1gnf225GrBHfXFDVvl:brt3h2z) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/common/include/api.h#L198)):*
> ```objc
>  *
>  * We use __ATOMIC_RELAXED here, as a consistent ordering within the accesses to `first` is enough
>  * for us — if we return `false`, that doesn't actually guarantee anything meaningful as far
> ```

`if we return` -> `if this macro returns`
___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1goPMk5DXLSu3SNdA0:b-1a9gdv) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I prefer `DO_ONCE`, but very, very slightly.
</blockquote></details>

I strongly prefer `FIRST_TIME()`, because this particular case of `if (!DO_ONCE())` is not human-readable.


<!-- Sent from Reviewable.io -->

2022-05-10 08:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @NieDzejkob)

___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1h8Tw5EpCSPMb1nv8N:blm0rwz) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I strongly prefer `FIRST_TIME()`, because this particular case of `if (!DO_ONCE())` is not human-readable.
</blockquote></details>

It wasn't obvious to when `DO_ONCE` returns true and when false. So yes, `FIRST_TIME` sounds better. Or some other name that suggests "this invocation returns true only the first time around".


<!-- Sent from Reviewable.io -->

2022-05-10 14:31 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Another simpler approach to this is to block yourself here in Reviewable, with a comment like "Change the commit message to `Bla bla bla`". I prefer this way to `squash!` commits.
</blockquote></details>

TODO: New commit message:

```
[common] Create a FIRST_TIME macro

Create a macro that encapsulates executing a code segment only when it is first reached.
```
___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1iNFxCBQ7KYuTXJNuj:b6vcn38) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I too think that this explanation is too verbose. I think we can keep the first sentence (`We use ...`). But we can drop the second sentence (`In particular ...`).

Basically, we just want to give a hint to future readers that we indeed intended to use `__ATOMIC_RELAXED`. We don't want to explain each and every detail in our code.
</blockquote></details>

Okay, I've made the explanation more concise.
___
*[`common/include/api.h` line 198 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1gnf225GrBHfXFDVvk:-N1iN7krA7mz7G7-AFJt:b-cjxref) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/common/include/api.h#L198)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`if we return` -> `if this macro returns`
</blockquote></details>

Okay, applied the equivalent in the new wording.
___
*[`LibOS/shim/src/sys/shim_exit.c` line 156 at r2](https://reviewable.io/reviews/gramineproject/gramine/572#-N1dS06VAdUjtRikayco:-N1iMb3J9hZj1HG_Utli:bht3ek6) ([raw file](https://github.com/gramineproject/gramine/blob/1e84aaaee8fac12f75af7fc4971aaaeacef713db/LibOS/shim/src/sys/shim_exit.c#L156)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It wasn't obvious to when `DO_ONCE` returns true and when false. So yes, `FIRST_TIME` sounds better. Or some other name that suggests "this invocation returns true only the first time around".
</blockquote></details>

Changed to `FIRST_TIME`.


<!-- Sent from Reviewable.io -->

2022-05-10 16:04 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-10 18:20 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Suggested change: `This macro encapsulates executing a code segment only when it is reached for the first time.`
</blockquote></details>

Okay.
___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1jBJRA8_10uC_OLzXM:by8uhw8) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
I am referring to

> All modifications to any particular atomic variable occur in a total order that is specific to this one atomic variable.

(from https://en.cppreference.com/w/cpp/atomic/memory_order)

`consistent` being "the same for all threads"

> I still dislike having this comment

Memory ordering is a genuinely tricky aspect of the code, and I don't think trying to reduce the comments on it is a good idea.


<!-- Sent from Reviewable.io -->

2022-05-10 19:26 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1jNG3s3-zhtiH_zA3r:bvcm0g5) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
> Memory ordering is a genuinely tricky aspect of the code, and I don't think trying to reduce the comments on it is a good idea.

That's the problem here - you start talking about memory ordering in a place that should have nothing to do with it. As you pointed out, this gives 0 guarantees on memory ordering - why even mention it? Seeing a comment like this rings bells, like something fishy is going on here, need to be careful.

But maybe it's just me, I'm unblokcing, I'll leave this to others.
cc @dimakuv @mkow 


<!-- Sent from Reviewable.io -->

2022-05-10 19:55 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1jX_lxC7MwlZ6i2o2x:b-9jwwrb) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Memory ordering is a genuinely tricky aspect of the code, and I don't think trying to reduce the comments on it is a good idea.

That's the problem here - you start talking about memory ordering in a place that should have nothing to do with it. As you pointed out, this gives 0 guarantees on memory ordering - why even mention it? Seeing a comment like this rings bells, like something fishy is going on here, need to be careful.

But maybe it's just me, I'm unblokcing, I'll leave this to others.
cc @dimakuv @mkow 
</blockquote></details>

What do you mean? Atomics are involved, you need to pick the memory ordering they should use, therefore memory ordering is involved.


<!-- Sent from Reviewable.io -->

2022-05-10 20:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1jbsPO71LQT-D5oWPL:b-fwk340) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

What do you mean? Atomics are involved, you need to pick the memory ordering they should use, therefore memory ordering is involved.
</blockquote></details>

This is ordering w.r.t. other memory accesses, which we do not care about at all.


<!-- Sent from Reviewable.io -->

2022-05-10 21:27 UTC, mkow submitted a review, later dismissed
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1jp_FP4ExSUkcKpKBn:b3jtet2) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is ordering w.r.t. other memory accesses, which we do not care about at all.
</blockquote></details>

I'm neutral on this. I agree that `__ATOMIC_RELAXED` triggers a red light when reading, but it's also true that here we don't have anything relying on it.


<!-- Sent from Reviewable.io -->

2022-05-11 06:28 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/api.h` line 200 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cyHWS8yeY3vcrK-Xr:-N1lmeHI4ydxGjrPk8VQ:b-mpn66a) ([raw file](https://github.com/gramineproject/gramine/blob/79bc4cc056069a07fbaf926231e1ce07ddb1c0f5/common/include/api.h#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this. I agree that `__ATOMIC_RELAXED` triggers a red light when reading, but it's also true that here we don't have anything relying on it.
</blockquote></details>

I'm fine with this comment. Basically, I would only highlight the fact that we use `__ATOMIC_RELAXED` to perform the "guarded" block of code only once, but there are no synchronization guarantees on that block of code. The current comment highlights this, though in a slightly more verbose way :) Anyway, this is a nice hint to a future developer, I don't see any problems with this text.


<!-- Sent from Reviewable.io -->

2022-05-11 06:28 UTC, dimakuv commented
Jenkins, test this please

2022-05-11 07:04 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-11 07:05 UTC, dimakuv commented
Jenkins, test this please

2022-05-11 08:59 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-11 11:46 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: all files reviewed, 1 unresolved discussion (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-11 11:56 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/572)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/572#-N1cxsgP3iFSQ3xYKO1S):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2022-05-11 12:00 UTC, merged