[Pal/Linux-SGX] On SIGILL, specify where in app code it happened
gramineproject/gramine pull request #577
Opened 2022-05-11 13:36 UTC by dimakuv

## Description of the changes 

The user may use this hint to disassemble the app binaries and find the offending instruction.

## How to test this PR? 

I didn't add a new test because I don't think it deserves it. Here is my manual testing:

- Add `ud2` in Helloworld:
```diff
diff --git a/LibOS/shim/test/regression/helloworld.c b/LibOS/shim/test/regression/helloworld.c
 int main(int argc, char** argv) {
     printf("Hello world!\n");
+    __asm__ volatile("ud2\n");
     return 0;
 }
```

- Run this test with at least `loader.log_level = "warning"`, you'll see:
```
warning: Unknown or illegal instruction executed (at 0x4004fb)
```

- Look at the Helloworld executable:
```bash
gramine/built-debug/lib/x86_64-linux-gnu/gramine/tests/libos/regression$
objdump -D helloworld | grep 4004fb

  4004fb:       0f 0b                   ud2
```

2022-05-11 13:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Pal/src/host/Linux-SGX/db_exception.c` line 174 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nKVJF5wL8QJvYtdZ6:-N1nKVJF5wL8QJvYtdZ7:bdxzwcp) ([raw file](https://github.com/gramineproject/gramine/blob/aee873466d9e63f3dad13079f9a4e679d5dae9d7/Pal/src/host/Linux-SGX/db_exception.c#L174)):*
> ```C
>         return false;
>     }
>     log_error("Unknown or illegal instruction executed");
> ```

FYI: I change from `error` to `warning` level, because this may leak info about the app binaries.


<!-- Sent from Reviewable.io -->

2022-05-11 13:55 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nMVdY-hYoRaeDvZhD):*
Suggested oneliner: `Print instruction address on SIGILL`.
Or at least use imperative mood.
___
*[`Pal/src/host/Linux-SGX/db_exception.c` line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nMyXMB3kBMd4qbX6n:-N1nMyXN98MGqoW0p4va:b-rnrxc2) ([raw file](https://github.com/gramineproject/gramine/blob/0c0811fe8d1869c00016c32bea9a6e43037898be/Pal/src/host/Linux-SGX/db_exception.c#L177)):*
> ```C
>     char buf[LOCATION_BUF_SIZE];
>     pal_describe_location(uc->rip, buf, sizeof(buf));
>     log_warning("Unknown or illegal instruction executed (at %s)", buf);
> ```

I would remove parens


<!-- Sent from Reviewable.io -->

2022-05-11 14:23 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please

- failed with `Command ['gramine-direct', 'fdatasync01'] timed out after 30 s`
- failed with `Command ['gramine-direct', 'writev07'] timed out after 30 s`

These failures are unrelated to the PR.

2022-05-15 00:54 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`Pal/src/host/Linux-SGX/db_exception.c` line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nMyXMB3kBMd4qbX6n:-N24CPgOAslKiLEthHve:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/0c0811fe8d1869c00016c32bea9a6e43037898be/Pal/src/host/Linux-SGX/db_exception.c#L177)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove parens
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-05-16 06:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nMVdY-hYoRaeDvZhD):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Suggested oneliner: `Print instruction address on SIGILL`.
Or at least use imperative mood.
</blockquote></details>

Done. Since this whole PR is tiny, I git-amended to incorporate this feedback.
___
*[`Pal/src/host/Linux-SGX/db_exception.c` line 177 at r1](https://reviewable.io/reviews/gramineproject/gramine/577#-N1nMyXMB3kBMd4qbX6n:-N2AVOm05M5-JA21NBqr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0c0811fe8d1869c00016c32bea9a6e43037898be/Pal/src/host/Linux-SGX/db_exception.c#L177)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 08:34 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-16 10:28 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-16 11:13 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-05-16 11:15 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/577)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-16 11:54 UTC, merged