Rewrite sockets
gramineproject/gramine pull request #579
Opened 2022-05-11 18:50 UTC by boryspoplawski

## Description of the changes 
WIP

2022-05-13 00:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 55 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1udtHL7iqySvzvQoMV:-N1udtHL7iqySvzvQoMW:bcllow9) (no related file):*
TODO: add fixes for all fixed issues

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uib_28XlYUWNI0aDj:-N1uib_28XlYUWNI0aDk:b-cy294p) (no related file):*
TODO: add an issue with leftovers for follow up PRs (though after main review is done)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N1uizLLDf5W9FqZjVyJ:b-3tr7w1) (no related file):*
TODO: rewrite PAL regression tests (at least `SendHandle` and add one for testing TCP + UDP communication)

___
___
*[`LibOS/shim/src/bookkeep/shim_handle.c` line 753 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ud9gR2lAcEH-2-3NO:-N1ud9gS8tNvxd7at5H8:b5y95rh) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/bookkeep/shim_handle.c#L753)):*
> ```C
> 
>         if (hdl->type == TYPE_SOCK) {
>             /* TODO: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> ```

No idea what to do with this one.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 64 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1udgOA8DgE1C_sjZG6:-N1udgOA8DgE1C_sjZG7:b-z9mz3k) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/fs/socket/fs.c#L64)):*
> ```C
>     memset(stat, 0, sizeof(*stat));
> 
>     /* TODO: what do we put in `dev` and `ino`? */
> ```

Is it important? I guess something might look at this info... Otoh it's a handle, not an inode, so why would it?
___
*[`LibOS/shim/src/fs/socket/fs.c` line 71 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1udcHl6R0-DoK5Sgql:-N1udcHl6R0-DoK5Sgqm:b-wrcsd7) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/fs/socket/fs.c#L71)):*
> ```C
>     stat->st_blksize = PAGE_SIZE;
> 
>     /* TODO: maybe set `st_size` - query PAL for pending size? */
> ```

I wouldn't bother, if nothing uses that info.
___
*[`LibOS/shim/src/net/ip.c` line 289 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ueKHiAFsj9UySfFAK:-N1ueKHiAFsj9UySfFAL:bzgp4r5) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/ip.c#L289)):*
> ```C
> }
> 
> // TODO: maybe inline all functions used here? or at least join them into one - they contain
> ```

These function first query PAL, then change one option, then update stuff via PAL API.
So either:
A) we leave it as it is
B) create one function (maybe even inline it here) with a nested switch.
C) ?
___
*[`LibOS/shim/src/net/ip.c` line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uegOh-ej5QNmKoisv:-N1uegOh-ej5QNmKoisw:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/ip.c#L370)):*
> ```C
> }
> 
> // TODO: maybe inline all functions used here? or at least join them into one - they contain
> ```

ditto
___
*[`LibOS/shim/src/net/unix.c` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uemVK7LN5hxSzs1VF:-N1uemVK7LN5hxSzs1VG:b-ey12xr) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/unix.c#L11)):*
> ```C
>  */
> 
> // TODO: Pathname UNIX sockets are not visible on the filesystem. Is that a problem?
> ```

In this version UNIX socket do not create an entry in FS. I don't think we need it for anything, but I'm not sure. Only thing I could think of was that some apps might get confused when trying to `unlink` the socket after being done with it.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 429 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ukKN0ExP_EX8XOecb:-N1ukKN1-u95IMghDmZ8:b-6qn02p) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/sys/shim_socket.c#L429)):*
> ```C
> out:
>     if (ret == -EINTR) {
>         /* XXX: timeout could have been changed in the meantime. Do we care? Antyhing we can do
> ```

We cannot hold the lock protecting this field for the whole accept (especially since it might be blocking)
___
*[`LibOS/shim/src/sys/shim_socket.c` line 452 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ufHwH3ZaP84tdwPil:-N1ufHwH3ZaP84tdwPim:b-6lzyp6) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/sys/shim_socket.c#L452)):*
> ```C
> }
> 
> /* TODO: non blocking connect should set `last_error` after actually connecting (or failing to)
> ```

Currently PAL APIs always block on connect, waiting for it to finish (just like the old version worked). How bad is that? The problem is I have no idea how to implement that in Gramine - this connect happens asynchronously **outside of** Gramine...
___
*[`LibOS/shim/src/sys/shim_socket.c` line 766 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ufgkW-1OnxQEVz4Ww:-N1ufgkW-1OnxQEVz4Wx:b-fqe8kg) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/sys/shim_socket.c#L766)):*
> ```C
>         }
>         return -ENOSYS;
> #if 0
> ```

Implementing `MSG_PEEK` turned out to be more cumbersome than expected, so I've left it missing for now. We need to check if anything real-life requires it.
Problems:
- UDP (SOCK_DGRAM) peeking - I'm not even sure what are the semantics where there are 2 datagrams...
- UDP - the host OS kernel will discard a datagram, even if we read only a part of it; if an app does a peek of 32 bytes, we read 32 bytes here and the actual packet was longer, it's now gone and we have no way to obtain the rest; maybe we could workaround this by always peeking >= MAX_DATAGRAM_SIZE, but uhhh...
- if a socket is blocking, we've already peeked some data and the app requests more, what do we do? if we always return the partial data, app might deadlock, maybe it awaits for more data doing peeks (I'm too afraid to even think about how this interacts with `EPOLLET`); if we peek for more, well, there might not be more and we just blocked - we would have to add a per call `is_blocking` argument - that would be nice, but is that portable? to expect that from every PAL
- concurrency - we would need all reads to be done under a lock - it's not doable otherwise (e.g. read + peek at the same time)
___
*[`Pal/include/pal_internal.h` line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uiR_a5KwyemSY9zwM:-N1uiR_b8YFIA0yv1Oxe:bnq81jj) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/include/pal_internal.h#L39)):*
> ```objc
> extern struct pal_public_state g_pal_public_state;
> 
> // TODO: clean unused stuff
> ```

For a follow up PR. TODO: add this to an issue summarizing leftovers from this PR.
___
*[`Pal/include/pal_internal.h` line 114 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uinxKAywYKsj0bjda:-N1uinxKAywYKsj0bjdb:b834nn0) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/include/pal_internal.h#L114)):*
> ```objc
>         return NULL;
>     if (handle->hdr.ops) {
>         /* TODO: remove this hack or (preferably) add this for every type of handle. */
> ```

I think we should follow this approach everywhere and get rid of all the stringly-typed interfaces.
___
*[`Pal/include/pal/pal.h` line 36 at r2](https://reviewable.io/reviews/gramineproj [...]

2022-05-13 00:13 UTC, boryspoplawski commented
Jenkins, retest this please (just testing, all was green)

2022-05-13 23:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 55 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1udtHL7iqySvzvQoMV:-N1ziThy1NImyPDIka5q:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: add fixes for all fixed issues
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-05-14 16:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 55 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 766 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ufgkW-1OnxQEVz4Ww:-N22O9qNEDjY-URnsvE1:b72hbcu) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/sys/shim_socket.c#L766)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Implementing `MSG_PEEK` turned out to be more cumbersome than expected, so I've left it missing for now. We need to check if anything real-life requires it.
Problems:
- UDP (SOCK_DGRAM) peeking - I'm not even sure what are the semantics where there are 2 datagrams...
- UDP - the host OS kernel will discard a datagram, even if we read only a part of it; if an app does a peek of 32 bytes, we read 32 bytes here and the actual packet was longer, it's now gone and we have no way to obtain the rest; maybe we could workaround this by always peeking >= MAX_DATAGRAM_SIZE, but uhhh...
- if a socket is blocking, we've already peeked some data and the app requests more, what do we do? if we always return the partial data, app might deadlock, maybe it awaits for more data doing peeks (I'm too afraid to even think about how this interacts with `EPOLLET`); if we peek for more, well, there might not be more and we just blocked - we would have to add a per call `is_blocking` argument - that would be nice, but is that portable? to expect that from every PAL
- concurrency - we would need all reads to be done under a lock - it's not doable otherwise (e.g. read + peek at the same time)
</blockquote></details>

Ok, `nginx` uses `MSG_PEEK` on stream sockets in nonblocking mode, seems we need this now.


<!-- Sent from Reviewable.io -->

2022-05-15 01:29 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 60 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N24K7Cv8EHrf4I2rGSR:b5tdqxa) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: rewrite PAL regression tests (at least `SendHandle` and add one for testing TCP + UDP communication)
</blockquote></details>

`SendHandle` rewritten. Do we want some more tests, or is this one enough (it also tests some simple communication, the only thing not checked is address retrieval).

___


<!-- Sent from Reviewable.io -->

2022-05-19 09:35 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 60 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 589 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2QdDzH62B0rtkdgtsu:-N2QdDzH62B0rtkdgtsv:bzbf90h) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L589)):*
> ```C
>         return -ENOTSOCK;
>     }
>     if (!WITHIN_MASK(flags, MSG_NOSIGNAL)) {
> ```

The checking is incorrect.  It means only `MSG_NOSIGNAL` can be supported. All other flags are not supported.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 742 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qe8lC-lLfpOrNO8ul:-N2Qe8lC-lLfpOrNO8um:b4qooyy) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L742)):*
> ```C
>         return -ENOTSOCK;
>     }
>     if (!WITHIN_MASK(flags, MSG_PEEK)) {
> ```

The checking is incorrect.  It means only `MSG_PEEK` is supported. All other flags are not supported.
___
*[`LibOS/shim/test/regression/test_libos.py` line 1202 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qef--A3SQhWFWREQV:-N2QWnOBAZdGDWNj8mRH:b7q8mx1) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/test/regression/test_libos.py#L1202)):*
> ```Python
>             os.remove("u")
> 
>         stdout, _ = self.run_binary(['unix'])
> ```

unix test case exit with error.
```
[P2:T2:unix] warning: error clearing POSIX locks: -3
[P2:T2:unix] error: Sending IPC process-exit notification failed: -104
[P2:T2:unix] warning: IPC pid release failed
debug: DkProcessExit: Returning exit code 1
```


<!-- Sent from Reviewable.io -->

2022-05-19 11:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 60 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @llly)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 589 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2QdDzH62B0rtkdgtsu:-N2R5cxi1BBcF7d-_ROt:b-hqrse0) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L589)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

The checking is incorrect.  It means only `MSG_NOSIGNAL` can be supported. All other flags are not supported.
</blockquote></details>

It is correct, only this flag is supported.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 742 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qe8lC-lLfpOrNO8ul:-N2R5g_56YkTfTIPPktM:b-5l8ixc) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L742)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

The checking is incorrect.  It means only `MSG_PEEK` is supported. All other flags are not supported.
</blockquote></details>

It is correct, only this flag is supported.
There will also be `MSG_DONTWAIT`, but I'm waiting for CI to be fixed before I submit a patch with it.
___
*[`LibOS/shim/test/regression/test_libos.py` line 1202 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qef--A3SQhWFWREQV:-N2R8-N8B26SB9lLURqW:b-i0o6l8) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/test/regression/test_libos.py#L1202)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

unix test case exit with error.
```
[P2:T2:unix] warning: error clearing POSIX locks: -3
[P2:T2:unix] error: Sending IPC process-exit notification failed: -104
[P2:T2:unix] warning: IPC pid release failed
debug: DkProcessExit: Returning exit code 1
```
</blockquote></details>

It works for me and it works in CI. Any more info? The log you've pasted dosn't help much.


<!-- Sent from Reviewable.io -->

2022-05-19 13:40 UTC, boryspoplawski commented
Jenkins, retest this please (fixed an issue with jenkins)

2022-05-19 14:12 UTC, boryspoplawski commented
Jenkins, retest this please (fixed an issue with jenkins)

2022-05-20 03:31 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 61 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @llly)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 742 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qe8lC-lLfpOrNO8ul:-N2UUqo6D3gKeoYgcrnJ:bb7g6h3) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L742)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It is correct, only this flag is supported.
There will also be `MSG_DONTWAIT`, but I'm waiting for CI to be fixed before I submit a patch with it.
</blockquote></details>

Coped from log of a Java netty app `shim_recvfrom(292, 0x79951bbd0, 0x400, 0, 0x79951afa0, 0x79951afc0) = 0x43`.  flag `0x400` MSG_SYN can be ignored, but syscall should not return error.
___
*[`LibOS/shim/test/regression/test_libos.py` line 1202 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qef--A3SQhWFWREQV:-N2UGuE34bbg_TqBhGu5:b-8o93ed) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/test/regression/test_libos.py#L1202)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It works for me and it works in CI. Any more info? The log you've pasted dosn't help much.
</blockquote></details>

That's the issue of test app and CI. return value of test app is not checked. No problem for this PR.


<!-- Sent from Reviewable.io -->

2022-05-20 12:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 61 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @llly)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 742 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qe8lC-lLfpOrNO8ul:-N2WL-hgAlbku9tplwRr:b8kwd7l) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L742)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Coped from log of a Java netty app `shim_recvfrom(292, 0x79951bbd0, 0x400, 0, 0x79951afa0, 0x79951afc0) = 0x43`.  flag `0x400` MSG_SYN can be ignored, but syscall should not return error.
</blockquote></details>

The log you posted doesn't use any flags (`0`) and returns a successful value.
But the kernel indeed seem to ignore invalid flags (both non-existent and completely unused like `MSG_SYN`). Did you really encounter this in some app? I would expect that apps do not add random flags... I guess I'll have to change this to fail on explicitly unsupported flags and allow all others (including invalid), but this is weird, what if new kernel version adds a new flag?
___
*[`LibOS/shim/test/regression/test_libos.py` line 1202 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qef--A3SQhWFWREQV:-N2WKoqB3WdsYpP9mioU:b-8dahq1) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/test/regression/test_libos.py#L1202)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

That's the issue of test app and CI. return value of test app is not checked. No problem for this PR.
</blockquote></details>

Not sure what you are saying. Is this example failing in some setup? I have no repro (neither local nor in CI).


<!-- Sent from Reviewable.io -->

2022-05-23 03:35 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 0 of 61 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @llly)

___
*[`LibOS/shim/src/sys/shim_socket.c` line 742 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qe8lC-lLfpOrNO8ul:-N2i_cAjADDLEGk-XRHG:b-9i5tj0) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/src/sys/shim_socket.c#L742)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The log you posted doesn't use any flags (`0`) and returns a successful value.
But the kernel indeed seem to ignore invalid flags (both non-existent and completely unused like `MSG_SYN`). Did you really encounter this in some app? I would expect that apps do not add random flags... I guess I'll have to change this to fail on explicitly unsupported flags and allow all others (including invalid), but this is weird, what if new kernel version adds a new flag?
</blockquote></details>

My example is wrong. I didn't run a real app to reproduce it. `fail on explicitly unsupported flags`, that's what I like. It's better to pass existing CI cases instead of removing cases because existing CI cases have same behavior on Gramine and native OS.
___
*[`LibOS/shim/test/regression/test_libos.py` line 1202 at r3](https://reviewable.io/reviews/gramineproject/gramine/579#-N2Qef--A3SQhWFWREQV:-N2icLAnBhRyWN4Z3OSQ:bsgk6ev) ([raw file](https://github.com/gramineproject/gramine/blob/a40a7e72b7016aaa47af0486af6cda0896c32ebe/LibOS/shim/test/regression/test_libos.py#L1202)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure what you are saying. Is this example failing in some setup? I have no repro (neither local nor in CI).
</blockquote></details>

This test app fork and doesn't `waitpid(-1,NULL,0);`. When parent process exits before child,  child in gramine exits with exit code 1, while child in native OS exits with exit code 0.   CI doesn't check exit code nor catch it.


<!-- Sent from Reviewable.io -->

2022-05-23 15:07 UTC, dimakuv requested changes
> Reviewed 22 of 54 files at r1, 3 of 10 files at r2, 7 of 11 files at r3, 15 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 47 of 61 files reviewed, 80 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N2jyGZb2qYOaJLwAcgL:bsb6zhy) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`SendHandle` rewritten. Do we want some more tests, or is this one enough (it also tests some simple communication, the only thing not checked is address retrieval).
</blockquote></details>

I don't like PAL regression tests, so I would not add anything new.

The minimum testing of new `DkSocket*` functions you already have in `SendHandle`. The rest we can test via LibOS tests.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lR3em8hslQicZbDU8:-N2lR3em8hslQicZbDU9:bbc9mse) (no related file):*
TODO(myself): finish review. LibOS main code and all Linux-SGX PAL are left.

Borys, if possible, please give me one more day to finish this review, and then push the fixups.

___
___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
`your first-born children are missing` is too creepy. Maybe add `(c) James Mickens`? (And I'm not joking: an unprepared reader may be very confused, and at least we give a hint that these are the words of wisdom from a well-known person.)
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k922zA6B6XNIdypk4):*
`sockets`
___
*[`-- commits` line 19 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kAb8W0A8t0MT_fDjS):*
FYI: Not that anyone cares, but `virtio-vsock` driver specification also follows this design. So it's a good fit even for actual ring-0 implementation.
___
*[`common/include/api.h` line 390 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kB0GLEDgEdSNZGv3L:-N2kB0GLEDgEdSNZGv3M:brc60r8) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/include/api.h#L390)):*
> ```objc
> #define URI_TYPE_DIR      "dir"
> #define URI_TYPE_PIPE     "pipe"
> #define URI_TYPE_PIPE_SRV "pipe.srv"
> ```

Why should pipes be different? We emulate them via UNIX domain sockets, and use the same POSIX/BSD sockets syscalls. I would expect the pipes code to be re-implemented in the same way as TCP/UDP.

Just a discussion point. Surely not for this PR, can be a follow up.

UPDATE: Ok, this is because we assume that UNIX domain sockets are too Linux-specific and may not be available on e.g. Windows. So we actually want to emulate as much as possible through a simpler abstraction of pipes. We may re-write pipes code, but not remove it completely in favor of UNIX domain sockets (implemented over `DkSocket*` APIs).
___
*[`common/src/socket_utils.c` line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kD3-u9iJe1gJ8F6s6:-N2kD3-u9iJe1gJ8F6s7:b3knyzz) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/src/socket_utils.c#L18)):*
> ```C
>             *linux_addr_len = sizeof(linux_addr->ss_family);
>             break;
>         case IPV4:;
> ```

I would prefer to have a `PAL_` prefix: `PAL_IPV4`, `PAL_IPV6`, etc.
___
*[`common/src/socket_utils.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kDdzhBNf_fCMa0oTg:-N2kDdzhBNf_fCMa0oTh:boqqljw) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/src/socket_utils.c#L28)):*
> ```C
>             struct sockaddr_in6* sa_ipv6 = (struct sockaddr_in6*)linux_addr;
>             sa_ipv6->sin6_family = AF_INET6;
>             sa_ipv6->sin6_flowinfo =  pal_addr->ipv6.flowinfo;
> ```

Double space
___
*[`LibOS/shim/include/shim_handle.h` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kGv9gBXz7vvR7Bxc2:-N2kGv9gBXz7vvR7Bxc3:b-3x7l21) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L74)):*
> ```objc
>     SOCK_BOUND,
>     SOCK_CONNECTED,
>     SOCK_LISTENING,
> ```

Shouldn't there be a `SOCK_CLOSING` state -- it marks that the socket is being shutdown but is still readable/writable (some data flows through one end)? If you don't have this state, can you correctly emulate `SHUT_RD` and `SHUT_WR`?

UPDATE: Ok, you're probably just looking at `read_shutdown` and `write_shutdown` fields of the socket object.
___
*[`LibOS/shim/include/shim_handle.h` line 78 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kHGmo9fixEtPtlQhJ:-N2kHGmo9fixEtPtlQhK:b-tznk73) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L78)):*
> ```objc
> 
> /*
>  * Accecss to `state`, `remote_addr`, `remote_addrlen`, `local_addr`, `local_addrlen, `last_error`,
> ```

`Access`
___
*[`LibOS/shim/include/shim_handle.h` line 84 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kHimZ5yTmbgA4fxIF:-N2kHimZ5yTmbgA4fxIG:b-xw1n38) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L84)):*
> ```objc
>  * stream reads (see the comment in `do_recvmsg` in "LibOS/shim/src/sys/shim_socket.c").
>  * `pal_handle` should be accessed using atomic operations. It can be NULL. Once it's set, it cannot
>  * change anymore.
> ```

You don't mention `was_bound` field -- how is it protected?

Actually, the rest of the fields are intuitively clear to me, but the purpose of `was_bound` is unclear. Could you add a comment? It probably has to do with UDP sockets, right?
___
*[`LibOS/shim/include/shim_handle.h` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kgaNH9dDG0nWKJVBb:-N2kgaNH9dDG0nWKJVBc:brmgig8) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L89)):*
> ```objc
>     struct shim_lock lock;
>     struct shim_sock_ops* ops;
>     PAL_HANDLE pal_handle;
> ```

So now we have two PAL handles:
- `hdl->pal_handle`
- `hdl->info.sock.pal_handle`

What is the difference between them? Why not just always use the former one?
___
*[`LibOS/shim/include/shim_socket.h` line 1 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kIgsuALWJzf7HAKeo:-N2kIgsuALWJzf7HAKep:b-jyiyvb) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L1)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

Btw, this is so surprising that this header didn't exist before. This was an interesting experiment -- trying to treat sockets the same as other files. Similarly to "let's not use inodes", this experiment failed.
___
*[`LibOS/shim/include/shim_socket.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kJWBI0u4EUPZ1NBJ8:-N2kJWBI0u4EUPZ1NBJ9:b-ai3cio) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L9)):*
> ```objc
> #include "shim_handle.h"
> 
> #define SHIM_SOCK_MAX_CONNS 4096
> ```

This name is misleading. You're only using this constant for `backlog` in `listen()`. So maybe rename to `SHIM_SOCK_MAX_PENDING_CONNS`?
___
*[`LibOS/shim/include/shim_socket.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kJm0H802_Yyh8dmL1:-N2kJm0H802_Yyh8dmL2:bwpgqp1) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb [...]

2022-05-23 17:57 UTC, dimakuv requested changes
> Reviewed 2 of 24 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 49 of 61 files reviewed, 91 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @llly)

___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ujTgh4kbTvNvwCC9Q:-N2lsqvJBCdFdEXdzm3F:buw5w0s) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/src/host/Linux-SGX/db_sockets.c#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It would be good to have these, it wouldn't even be that slow (because we cache the values), but we would need to add `getsockopt` ocall.
</blockquote></details>

Maybe fetch it during Gramine startup and move these two values into `g_pal_linux_sgx_state` fields?

Adding a new OCALL just to learn these two values doesn't seem reasonable.
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 68 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lrpPB5d7Bu4u1aaAo:-N2lrpPB5d7Bu4u1aaAp:b-oz6qda) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L68)):*
> ```C
>     }
> 
>     init_handle_hdr(handle, PAL_TYPE_SOCKET);
> ```

ditto (explicit assignments)
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 156 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lul_q8csGTeYDK-wt:-N2lul_q8csGTeYDK-wu:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L156)):*
> ```C
>         linux_type |= SOCK_NONBLOCK;
>     }
>     linux_type |= SOCK_CLOEXEC;
> ```

ditto
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 233 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lwwTlCHEYEovQW8Rb:-N2lwwTlCHEYEovQW8Rc:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L233)):*
> ```C
>     size_t linux_addrlen = sizeof(sa_storage);
>     int flags = options & PAL_OPTION_NONBLOCK ? SOCK_NONBLOCK : 0;
>     flags |= SOCK_CLOEXEC;
> ```

ditto
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m-28c9IIRfmm_oVIZ:-N2m-28c9IIRfmm_oVI_:b-rkp4l6) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L300)):*
> ```C
>     attr->nonblocking = handle->sock.is_nonblocking;
> 
>     int ret = ocall_fionread(handle->sock.fd);
> ```

This is pretty bad performance-wise. This was like this before this PR, but can we add a TODO here? I wonder if we could do something better than an OCALL each time.
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 327 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m0Sr7BdVAeyZVVHS9:-N2m0Sr7BdVAeyZVVHSA:bkc49hx) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L327)):*
> ```C
> 
>     if (attr->nonblocking != handle->sock.is_nonblocking) {
>         int ret = ocall_fsetnonblock(handle->sock.fd, attr->nonblocking);
> ```

I wonder if we should maybe have a generic OCALL that takes a dict of attributes with their values and sets them all at once? Instead of these separate OCALLs as we have now... But this is just a thought, not for this PR.

UPDATE: On second thought, no, this is too complicated. Some values may be not basic, but complex structs. Copying a dict of complex structs in/out of the enclave will be unnecessarily complex. Ignore my comment.
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 478 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m1dtrE0OKywco0LoZ:-N2m1dtrE0OKywco0Lo_:b3m76tc) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L478)):*
> ```C
>                   && SAME_TYPE(pal_iov->iov_len, iov->iov_len)
>                   && offsetof(struct pal_iovec, iov_len) == offsetof(struct iovec, iov_len),
>                   "not compatible");
> ```

Why did you malloc in Linux PAL, but here you just cast? Both ways are fine with me, but why a difference?
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 480 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m2HKBCD6p6_yNmTi9:-N2m2HKBCD6p6_yNmTiA:b-3pk6eh) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L480)):*
> ```C
>                   "not compatible");
>     ssize_t ret = ocall_send(handle->sock.fd, iov, iov_len, addr ? &sa_storage : NULL,
>                              linux_addrlen, NULL, 0);
> ```

Could you add `/*control msg = */` stuff for the last two args?
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 501 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m2V_P0VtgcxEvD6sa:-N2m2V_P0VtgcxEvD6sb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L501)):*
> ```C
>                   && SAME_TYPE(pal_iov->iov_len, iov->iov_len)
>                   && offsetof(struct pal_iovec, iov_len) == offsetof(struct iovec, iov_len),
>                   "not compatible");
> ```

ditto
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 503 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m2Z-j5XxAS26KocXq:-N2m2Z-j5XxAS26KocXr:b3a3a81) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L503)):*
> ```C
>                   "not compatible");
>     ssize_t ret = ocall_recv(handle->sock.fd, iov, iov_len, addr ? &sa_storage : NULL,
>                              &linux_addrlen, NULL, NULL, is_nonblocking ? MSG_DONTWAIT : 0);
> ```

Could you add `/*control msg = */` stuff for the pre-last two args?
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 576 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m2tlhEgeJNrRoIjdJ:-N2m2tlhEgeJNrRoIjdK:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_sockets.c#L576)):*
> ```C
> };
> 
> /* God have mercy on us all. */
> ```

ditto
___
*[`Pal/src/host/Linux-SGX/db_streams.c` line 51 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2m31p9EVaw6SnPAePM:-N2m31p9EVaw6SnPAePN:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/db_streams.c#L51)):*
> ```C
>      * no handle type has more than one such field, and some have none */
>     /* XXX: some of these have pointers inside, yet the content is not serialized. How does it even
>      * work? Probably unused. Or pure luck. */
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-05-24 00:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 49 of 61 files reviewed, 91 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lR3em8hslQicZbDU8:-N2nP2zk2JZwn1TMUEb6:bsjdi8q) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): finish review. LibOS main code and all Linux-SGX PAL are left.

Borys, if possible, please give me one more day to finish this review, and then push the fixups.
</blockquote></details>

Sure, let me know when you've looked at it all

___


<!-- Sent from Reviewable.io -->

2022-05-24 12:13 UTC, dimakuv requested changes
> Reviewed 4 of 54 files at r1, 1 of 11 files at r3, 7 of 24 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 133 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @llly)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N2lR3em8hslQicZbDU8:-N2pz3k_2fUUTC5SBR-D:b-i4zqe2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, let me know when you've looked at it all
</blockquote></details>

Done with the review.

___
___
*[`LibOS/shim/include/shim_handle.h` line 84 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kHimZ5yTmbgA4fxIF:-N2pj_Tf90-ma-dtynKF:b-gezxnd) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't mention `was_bound` field -- how is it protected?

Actually, the rest of the fields are intuitively clear to me, but the purpose of `was_bound` is unclear. Could you add a comment? It probably has to do with UDP sockets, right?
</blockquote></details>

UPDATE: `was_bound` is used to distinguish between a socket that was bound (`bind()` called on this socket) and then later disconnected (it still stays bound to the same local address) vs a socket that was never bound. Please add some quick comment about it.
___
*[`LibOS/shim/src/net/ip.c` line 289 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ueKHiAFsj9UySfFAK:-N2pFr4K3KkPCERySo7N:b-stcsud) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/ip.c#L289)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These function first query PAL, then change one option, then update stuff via PAL API.
So either:
A) we leave it as it is
B) create one function (maybe even inline it here) with a nested switch.
C) ?
</blockquote></details>

The code is readable as is, and I see no perf issues with the current approach. So I vote for A.
___
*[`LibOS/shim/src/net/ip.c` line 370 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uegOh-ej5QNmKoisv:-N2pGgrQD5S4gIEOK92p:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/ip.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`LibOS/shim/src/net/ip.c` line 55 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2p9irxClAQmuQj6b2C:-N2p9irxClAQmuQj6b2D:b-zb02xv) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L55)):*
> ```C
>             /* UDP sockets are ready for communication instantly. */
>             handle->info.sock.read_shutdown = false;
>             handle->info.sock.write_shutdown = false;
> ```

Is this some implicit logic? Why shutdown booleans are relevant to the comment "ready for communication"?
___
*[`LibOS/shim/src/net/ip.c` line 82 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pAPny8dAbkHnOeRHt:-N2pAPny8dAbkHnOeRHu:b-mak85t) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L82)):*
> ```C
>                 return -EINVAL;
>             }
>             addrlen = sizeof(*addr);
> ```

What's the point of this assignment?
___
*[`LibOS/shim/src/net/ip.c` line 92 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pASgR8y9pbCaLWIhH:-N2pASgR8y9pbCaLWIhI:b-mak85t) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L92)):*
> ```C
>                 return -EINVAL;
>             }
>             addrlen = sizeof(*addr6);
> ```

What's the point of this assignment?
___
*[`LibOS/shim/src/net/ip.c` line 125 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pAz7e4W3EufB5DpiF:-N2pAz7e4W3EufB5DpiG:buls27d) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L125)):*
> ```C
> 
> static int accept(struct shim_handle* handle, bool is_nonblocking,
>                   struct shim_handle** client_ptr) {
> ```

`out_client`
___
*[`LibOS/shim/src/net/ip.c` line 167 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pCcxP-41Pbunl8uS1:-N2pCcxP-41Pbunl8uS2:b988cto) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L167)):*
> ```C
>     lock(&handle->info.sock.lock);
>     client_sock->local_addrlen = handle->info.sock.local_addrlen;
>     memcpy(&client_sock->local_addr, &handle->info.sock.local_addr, client_sock->local_addrlen);
> ```

Is this how it works? The local address of the "accepted" socket is exactly the same as the one of the listening socket? Including the port number?

UPDATE: Yes, this is how it works.
___
*[`LibOS/shim/src/net/ip.c` line 318 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pGIe_A8EBuVRkjWY4:-N2pGIe_A8EBuVRkjWY5:bnvwllk) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L318)):*
> ```C
> }
> 
> static int get_sock_tcp_option(struct shim_handle* handle, int optname, void* optval, size_t* len) {
> ```

Aren't you supposed to check that `*len >= sizeof(val)` ? Otherwise buffer overflow may happen.
___
*[`LibOS/shim/src/net/ip.c` line 346 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pG_V_4EdgIJS8lLrS:-N2pG_V_4EdgIJS8lLrT:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L346)):*
> ```C
> 
> static int get_sock_ipv6_option(struct shim_handle* handle, int optname, void* optval,
>                                 size_t* len) {
> ```

ditto
___
*[`LibOS/shim/src/net/ip.c` line 399 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pH15WA0DjLRUQVZLu:-N2pH15XCp4xhkBvCOsJ:b-niwl71) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L399)):*
> ```C
> }
> 
> static int send(struct shim_handle* handle, struct iovec* iov, size_t iov_len, size_t* size_out,
> ```

`out_size`
___
*[`LibOS/shim/src/net/ip.c` line 408 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pHDFp2eGVSGYVUdbF:-N2pHDFp2eGVSGYVUdbG:bmq2xio) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L408)):*
> ```C
>     switch (sock->type) {
>         case SOCK_STREAM:
>             /* TCP sockets ignore destionation address - they must have been connected. */
> ```

`destination` (typo)
___
*[`LibOS/shim/src/net/ip.c` line 474 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pIRHT22UV3z4tZk_l:-N2pIRHT22UV3z4tZk_m:b-niwl71) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L474)):*
> ```C
> }
> 
> static int recv(struct shim_handle* handle, struct iovec* iov, size_t iov_len, size_t* size_out,
> ```

`out_size`
___
*[`LibOS/shim/src/net/ip.c` line 482 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pI78V7G7VQrGP4-0i:-N2pI78V7G7VQrGP4-0j:b-ebq062) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L482)):*
> ```C
>             /* TCP - not interested in remote address ( [...]

2022-05-25 15:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 35 of 61 files reviewed, 129 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @llly, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N2r71bqDanOLqXvLyU5:b-6qvoq6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like PAL regression tests, so I would not add anything new.

The minimum testing of new `DkSocket*` functions you already have in `SendHandle`. The rest we can test via LibOS tests.
</blockquote></details>

I think it's easier to test all corner cases there than go via normal syscalls and LibOS.

___
___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`your first-born children are missing` is too creepy. Maybe add `(c) James Mickens`? (And I'm not joking: an unprepared reader may be very confused, and at least we give a hint that these are the words of wisdom from a well-known person.)
</blockquote></details>

Well, actually maybe we should just remove it and have a normal commit message.
___
*[`common/include/api.h` line 390 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kB0GLEDgEdSNZGv3L:-N2r7XkX10X2XT7DWcow:b-jo43uy) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/include/api.h#L390)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why should pipes be different? We emulate them via UNIX domain sockets, and use the same POSIX/BSD sockets syscalls. I would expect the pipes code to be re-implemented in the same way as TCP/UDP.

Just a discussion point. Surely not for this PR, can be a follow up.

UPDATE: Ok, this is because we assume that UNIX domain sockets are too Linux-specific and may not be available on e.g. Windows. So we actually want to emulate as much as possible through a simpler abstraction of pipes. We may re-write pipes code, but not remove it completely in favor of UNIX domain sockets (implemented over `DkSocket*` APIs).
</blockquote></details>

Yes, exactly
___
*[`common/src/socket_utils.c` line 18 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kD3-u9iJe1gJ8F6s6:-N2r8Ua0ABLo_OYd7RK9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/src/socket_utils.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to have a `PAL_` prefix: `PAL_IPV4`, `PAL_IPV6`, etc.
</blockquote></details>

Done.
___
*[`common/src/socket_utils.c` line 28 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kDdzhBNf_fCMa0oTg:-N2r8bM44Fd3vDrzKOe1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/common/src/socket_utils.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Double space
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_handle.h` line 74 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kGv9gBXz7vvR7Bxc2:-N2r8g31786nD3fMXfEl:b-il4hws) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't there be a `SOCK_CLOSING` state -- it marks that the socket is being shutdown but is still readable/writable (some data flows through one end)? If you don't have this state, can you correctly emulate `SHUT_RD` and `SHUT_WR`?

UPDATE: Ok, you're probably just looking at `read_shutdown` and `write_shutdown` fields of the socket object.
</blockquote></details>

Yes, after `shutdown` the socket is still in the old state.
___
*[`LibOS/shim/include/shim_handle.h` line 78 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kHGmo9fixEtPtlQhJ:-N2r94bh9W8bUMMxBUTG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Access`
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_handle.h` line 84 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kHimZ5yTmbgA4fxIF:-N2rVv1T9nIqVgAdrSkc:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

UPDATE: `was_bound` is used to distinguish between a socket that was bound (`bind()` called on this socket) and then later disconnected (it still stays bound to the same local address) vs a socket that was never bound. Please add some quick comment about it.
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_handle.h` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kgaNH9dDG0nWKJVBb:-N2rVwruAohp8qs-siNm:brl32wu) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So now we have two PAL handles:
- `hdl->pal_handle`
- `hdl->info.sock.pal_handle`

What is the difference between them? Why not just always use the former one?
</blockquote></details>

Sockets never have the first one. The rest of the codebase assumes that `handle->pal_handle` never changes, but `info.sock.pal_handle` can change (in a limited way though, described in the comment above).
I had a discussion with @pwmarcz about this and it seems that `pal_handle` should be type specific - a lot of `shim_handle`s won't even have it. We might want to remote the generic one completely at some point.
___
*[`LibOS/shim/include/shim_socket.h` line 9 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kJWBI0u4EUPZ1NBJ8:-N2rZ9B11vaU1ebj35tE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This name is misleading. You're only using this constant for `backlog` in `listen()`. So maybe rename to `SHIM_SOCK_MAX_PENDING_CONNS`?
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_socket.h` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kJm0H802_Yyh8dmL1:-N2rYvsqE5KLR5luLQta:b-wm2it4) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Was that a TODO? You can remove it now.
</blockquote></details>

Yes it was, missed it somehow.
___
*[`LibOS/shim/include/shim_socket.h` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kJt3lBdAQFSL5GDVd:-N2rZIrr99vq0Q7IPCtE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`can assume` -> `assumes`

`already` (typo)
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_socket.h` line 43 at r4](https: [...]

2022-05-25 18:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 35 of 61 files reviewed, 129 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @llly, and @pwmarcz)

___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1346 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2p0ZjW2YAP7MYGPgLi:-N2wQcym0xbDgnpbY_-K:b8hscsy) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1346)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It definitely should be
</blockquote></details>

But also truns out it was there for a reason - it reserved enough space for output arg. Anyway, fixed


<!-- Sent from Reviewable.io -->

2022-05-25 18:41 UTC, boryspoplawski commented
Jenkins, retest Jenkins-20.04 please (`fcntl14` timed out, unrelated)

2022-05-30 13:26 UTC, dimakuv requested changes
> Reviewed 25 of 26 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N3K8KG81EaexEOCNwhY:b-t9uy5y) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it's easier to test all corner cases there than go via normal syscalls and LibOS.
</blockquote></details>

So you want to write a new PAL test? I have no strong opinion.

___
___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, actually maybe we should just remove it and have a normal commit message.
</blockquote></details>

That's another solution :)
___
*[`LibOS/shim/include/shim_handle.h` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kgaNH9dDG0nWKJVBb:-N3JqhZ78t2RX78O0ihU:budgwhz) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sockets never have the first one. The rest of the codebase assumes that `handle->pal_handle` never changes, but `info.sock.pal_handle` can change (in a limited way though, described in the comment above).
I had a discussion with @pwmarcz about this and it seems that `pal_handle` should be type specific - a lot of `shim_handle`s won't even have it. We might want to remote the generic one completely at some point.
</blockquote></details>

Thanks, interesting to know. Yes, I agree that `pal_handle` should be type-specific. Maybe create a GitHub issue so that we don't forget about it, and link this comment of yours there?
___
*[`LibOS/shim/include/shim_socket.h` line 101 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kLsLX7st4-Ct1HMvu:-N3JrG7iCGgC_gobxMJA:b-cf8cuk) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_socket.h#L101)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's also for `MSG_PEEK` (actually mainly for it, `MSG_DONTWAIT` was just a nice addition).
I'm not sure what to add here. I've added `This is useful for issuing a nonblocking recv on a blocking socket.` but then realized that it's just repeating the previous sentences...
</blockquote></details>

Yeah, whatever. Most of my comments are self-explained after reading through the code, and probably there's no other way to explain the logic behind these. I'm resolving this.
___
*[`LibOS/shim/src/bookkeep/shim_handle.c` line 753 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ud9gR2lAcEH-2-3NO:-N3Js4kW6f6TcgkW_h15:b-lsnsqg) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/bookkeep/shim_handle.c#L753)):*
> I don't like this, but there might be no other option...

Yes, the code that you pasted, that's what I meant. Well, we need to do *something* here, right? At the very least, removing this `aaa` would be fine :)

> Oh, and I just realized we do not release any locks on error returns...

Amazing, right? The macro madness in checkpointing needs to be removed.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 70 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kjTGr3UvofDf6niRy:-N3JspcV8SKxDlyu-sVH:b7yuntc) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I'm not sure anymore. I think this comment is from the times when I thought that FIFOs (at the LibOS level) are also emulated through your new Sockets PAL API. But it is not so -- FIFOs are still emulated through the Pipes PAL API. So ignore this.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 80 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kjlZD9MzgvYW8oQMo:-N3JtHwq3COlYv5ebeO9:bsyj5el) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think there is any logic. It's more like I've started putting it everywhere, then I've stopped doing that. I don't think they are useful, should I remove them?
</blockquote></details>

I would remove them.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 92 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kkG-HEer-bKHyHtkm:-N3JttfYDhq6MKgyoZ7n:b8dtrhf) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L92)):*
I'm getting confused. When you say `UNIX sockets`, do you mean "BSD (POSIX) sockets" or "UNIX domain sockets (UDS)"?

In particular, this phrase is confusing:

> UNIX sockets are emulated via other means and actually might not be real sockets

Do you mean that in host Linux, UNIX domain sockets are implemented in a different way than other sockets? And so they don't have the same options, or behave differently on those options?
___
*[`LibOS/shim/src/fs/socket/fs.c` line 96 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kkmlv4DEDb1JJZHmN:-N3JuqQ8EkXh9QvoCfU6:b-a4igxl) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There's an explanation (short I admit, but there is nothing more to say) in `shim_handle.h` near `struct shim_sock_handle`
</blockquote></details>

OK, so to remind myself: this PAL handle pointer is set only once, so the only transition possible is `NULL -> object`. So no use-after-free is possible.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 119 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2klo4NAN8SilgDkHoF:-N3JvT2hBns7HGFxsyH7:bddkpuu) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L119)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

True, this comment is misleading/wrong. The issue here is:
- `handle` is just a copy of original handle, let's call it `orig_handle`,
- there was `memcpy(handle, orig_handle, good_size)`
- so `sock->peek.buf` is just the same as `orig_handle->info.sock.peek.buf`,
- we probably would want to copy that data here (i.e. allocate a new buffer and copy it), but we cannot take `orig_handle->info.sock.recv_lock` (well, we also cannot allocate a new buffer).
</blockquote></details>

Got it. Could you rewrite the comment? Smth like this:
```
/* XXX: this should actually copy the data, but:
 * - `handle` is a copy of original handle `orig_handle`,
 * - to copy the `orig_handle->info.sock.peek.buf` data, we need to acquire `orig_handle->info.sock.recv_lock`
 *   but we already hold `orig_handle->lock` (and have no access to `orig_handle` anyway)
 * - moreover, we have no way of allocating memory in the checkpointing blob here for this data */
```
___
*[`LibOS/shim/src/fs/socket/fs.c` line 91 at r6](https://reviewable.io/reviews/gramineproject/grami [...]

2022-05-30 23:29 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 49 of 61 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uizLLDf5W9FqZjVyI:-N3KxfZv5i-lfdYIfkr1:b-5ndv7j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So you want to write a new PAL test? I have no strong opinion.
</blockquote></details>

Well, I'm lazy so no (as we already have some socket tests there). Just wanted to get your opinion first.

___
___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's another solution :)
</blockquote></details>

TODO: change this paragraph to:
```
The old version was full of bugs and barely readable. After the          
inability to overcome another limiation, we decided it is hopeless to    
fix and augment the old version and a complete rewrite is needed.
```
___
*[`LibOS/shim/include/shim_handle.h` line 89 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kgaNH9dDG0nWKJVBb:-N3L4V4DBu34VQfM2tir:b-g40ptj) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/include/shim_handle.h#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, interesting to know. Yes, I agree that `pal_handle` should be type-specific. Maybe create a GitHub issue so that we don't forget about it, and link this comment of yours there?
</blockquote></details>

Done (#620)
___
*[`LibOS/shim/src/bookkeep/shim_handle.c` line 753 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ud9gR2lAcEH-2-3NO:-N3LmYVF7rpzXGg1bob6:baetyzb) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/bookkeep/shim_handle.c#L753)):*
> At the very least, removing this aaa would be fine :)

Well, "aaa" was just to make sure we do something about it before merging and it doesn't get lost :)
___
*[`LibOS/shim/src/fs/socket/fs.c` line 80 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kjlZD9MzgvYW8oQMo:-N3LpqyA3I48jykHnXPh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove them.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 92 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kkG-HEer-bKHyHtkm:-N3LqU0v77-hNUGEHDv6:b-zi69i5) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L92)):*
"UNIX domain sockets" (although never heard of UDS acronym). I've never heard of anyone calling BSD sockets that name, though they are also called POSIX sockets - maybe here's the confusion.

> Do you mean that in host Linux, UNIX domain sockets are implemented in a different way than other sockets? And so they don't have the same options, or behave differently on those options?

Yes (and I expect it to be the same on other PALs as well). Currently (and I did not change that interface in this PR) we have options like `receivetimeout_us` which are handled on generic socket level - if UNIX domain socket is not connected it has no `pal_handle` and setting such option would fail. I guess the biggest problem could be `nonblocking` - this option I expect is sometimes set and it is more likely set before connect...
___
*[`LibOS/shim/src/fs/socket/fs.c` line 119 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2klo4NAN8SilgDkHoF:-N3LuwiI87-XCoq1Jvyr:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Got it. Could you rewrite the comment? Smth like this:
```
/* XXX: this should actually copy the data, but:
 * - `handle` is a copy of original handle `orig_handle`,
 * - to copy the `orig_handle->info.sock.peek.buf` data, we need to acquire `orig_handle->info.sock.recv_lock`
 *   but we already hold `orig_handle->lock` (and have no access to `orig_handle` anyway)
 * - moreover, we have no way of allocating memory in the checkpointing blob here for this data */
```
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 91 at r6](https://reviewable.io/reviews/gramineproject/gramine/579#-N3JuQM731GLc3b-gH-8:-N3LpzBcAGkmSTfEnKth:beey0dx) ([raw file](https://github.com/gramineproject/gramine/blob/07baae20e871e90040475c1a7de176d1d31f2d5a/LibOS/shim/src/fs/socket/fs.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we started talking about what `UNIX sockets` mean for you, I noticed that you use this in log messages like this one. But this callback is a generic one for all kinds of sockets, why do you specify `UNIX socket` here?
</blockquote></details>

Because this case is only possible for `UNIX sockets`. Every other kind (e.g. IP/TCP) always has `info.sock.pal_handle` set.
___
*[`LibOS/shim/src/net/ip.c` line 289 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ueKHiAFsj9UySfFAK:-N3M-sva7IAqHL7jIMzd:b6sz63g) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/ip.c#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Your call. I find it fine as is.
</blockquote></details>

Ok, I'll leave it then
___
*[`LibOS/shim/src/net/ip.c` line 55 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2p9irxClAQmuQj6b2C:-N3LzT0i4jQr5yRvf_uG:b-jzaqru) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the case of misleading names. Won't it be more readable if you rename these vars to `can_be_read` and `can_be_written` and negate all the booleans you have in this PR? So in this code snippet, it will look like this:
```
            /* UDP sockets are ready for communication instantly. */
            handle->info.sock.can_be_read = true;
            handle->info.sock.can_be_written = true;
```

This reads to me much more naturally than the current version.
</blockquote></details>

Done. Please verify I did not mess up the negations (I double checked them, but...)
___
*[`LibOS/shim/src/net/unix.c` line 11 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uemVK7LN5hxSzs1VF:-N3M0FzfDtP0rvseadkw:b-2ojg2x) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/LibOS/shim/src/net/unix.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Then maybe just rephrase a TODO comment, and we'll be done with it?
</blockquote></details>

ok, done
___
*[`LibOS/shim/src/net/unix.c` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pNgIt7wh1OSTHfUWC:-N3M1FzO7gwmLJbXpIr1:brqfa2y) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/unix.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oh, this is an important piec [...]

2022-05-31 07:26 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: change this paragraph to:
```
The old version was full of bugs and barely readable. After the          
inability to overcome another limiation, we decided it is hopeless to    
fix and augment the old version and a complete rewrite is needed.
```
</blockquote></details>

`limitation` (typo).

The new version is not as poetic, but to the point :)
___
*[`LibOS/shim/src/fs/socket/fs.c` line 92 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kkG-HEer-bKHyHtkm:-N3NvdTc6g6R9aUodRHE:buqk2ou) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/fs/socket/fs.c#L92)):*
>  this option I expect is sometimes set and it is more likely set before connect...

Well, I guess we'll learn about it in the near future then, now that we have a hard error code on this scenario.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 91 at r6](https://reviewable.io/reviews/gramineproject/gramine/579#-N3JuQM731GLc3b-gH-8:-N3NvH3t5sZ-uXM_ccNd:b-4hvi0m) ([raw file](https://github.com/gramineproject/gramine/blob/07baae20e871e90040475c1a7de176d1d31f2d5a/LibOS/shim/src/fs/socket/fs.c#L91)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because this case is only possible for `UNIX sockets`. Every other kind (e.g. IP/TCP) always has `info.sock.pal_handle` set.
</blockquote></details>

Got it.
___
*[`LibOS/shim/src/net/unix.c` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pNgIt7wh1OSTHfUWC:-N3NwXcr0SCHQkOiUCzL:b-sln8ar) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/unix.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, I don't remember why this couldn't be guarded by `handle->lock` instead... There were some issues with that approach, but I don't remember what they were (maybe they are gone now?)
This sounds like something we might want to have documented
</blockquote></details>

Feel free to add a FIXME/XXX comment about this in `shim_handle.h`
___
*[`LibOS/shim/src/net/unix.c` line 227 at r7](https://reviewable.io/reviews/gramineproject/gramine/579#-N3Nwq4_9hLP3niuF7Eo:-N3Nwq4_9hLP3niuF7Ep:b98rfaq) ([raw file](https://github.com/gramineproject/gramine/blob/925e967c6e527a7b5db19b8e27edf6a8b064802c/LibOS/shim/src/net/unix.c#L227)):*
> ```C
>     lock(&handle->lock);
>     /* TODO: this is racy. For now `setflags` in "fs/socket/fs.c" explicitly fails, so this will
>      * always be `0`, but we need to fix this at some point. */
> ```

Do you mean that if UNIX sockets would support setting `O_NONBLOCK` on a non-bound socket, then there would be a race?

That's because `setflags()` callback doesn't require a `handle->lock`, right? Wouldn't the easy solution be to guard `setflags()` with this lock then?
___
*[`LibOS/shim/test/regression/tcp_msg_peek.c` line 97 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2kqMP2AkLtGEUXZAQG:-N3NyarsE3XFjorcN0P9:btbwstv) ([raw file](https://github.com/gramineproject/gramine/blob/5ee0fc364712dbee1bd88cd029562acf6dc99468/LibOS/shim/test/regression/tcp_msg_peek.c#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes. Actually I can easily add it (just mimic what we have in `recv`, but for now nothing used it. Should I? The current version is a bit weird (asymmetric), but adding this gives 0 value
</blockquote></details>

I don't think anything ever needed it in `sendto()`, it's probably totally useless. So nothing to do now.
___
*[`Pal/include/pal/pal.h` line 301 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2ksuMC0J8btQmDsRaz:-N3NyzqQ5G7ghLoWGiPs:bkbmryd) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/include/pal/pal.h#L301)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The whole point of PAL interface is to be small and succinct, and having a separate function for one particular kind of objects goes against this philosophy.

IMHO this is a misunderstanding. If there are 1000 different objects, each having different implementation of a function, but it's just hidden behind one interface (*cough* `DkStreamOpen` *cough*) it's not any better than having each of the functions named differently. Having everything hidden behind one function doesn't make PAL small or succinct.

This is exactly the reasoning behind introducing new function to PAL API in this PR. I could stash them all in `DkStreamOpen` or similar, but that would be counter productive. 
</blockquote></details>

I get your point, but in this particular case this function (`DkStreamWaitForClient()`) seems like a good candidate for removal. The LibOS code needs to be analyzed, if we could remove it.


<!-- Sent from Reviewable.io -->

2022-05-31 12:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`limitation` (typo).

The new version is not as poetic, but to the point :)
</blockquote></details>

Well, art could be misunderstood, :)
___
*[`LibOS/shim/src/net/unix.c` line 127 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pNgIt7wh1OSTHfUWC:-N3P7koY8lfVV99le4qJ:bi5vt5u) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/unix.c#L127)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Feel free to add a FIXME/XXX comment about this in `shim_handle.h`
</blockquote></details>

After analyzing the current version it seems that we could use `handle->lock` (`handle->info.sock.lock` would be more intuitive, but won't work). Should I change? I don't mind either version, both need special casing. Atomic do not cause contention though :)
___
*[`LibOS/shim/src/net/unix.c` line 227 at r7](https://reviewable.io/reviews/gramineproject/gramine/579#-N3Nwq4_9hLP3niuF7Eo:-N3P8tOx9nxwGuluZ05m:b-9dicdi) ([raw file](https://github.com/gramineproject/gramine/blob/925e967c6e527a7b5db19b8e27edf6a8b064802c/LibOS/shim/src/net/unix.c#L227)):*
> Do you mean that if UNIX sockets would support setting O_NONBLOCK on a non-bound socket, then there would be a race?

Yes

> That's because setflags() callback doesn't require a handle->lock, right? Wouldn't the easy solution be to guard setflags() with this lock then?

No, `setflags` is done under `handle->lock`. The problem is with the window between setting options here and calling `DkStreamOpen` after releasing lock below.
___
*[`Pal/include/pal/pal.h` line 301 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2ksuMC0J8btQmDsRaz:-N3P9Olh4y0349HntiWf:b590q6n) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/include/pal/pal.h#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I get your point, but in this particular case this function (`DkStreamWaitForClient()`) seems like a good candidate for removal. The LibOS code needs to be analyzed, if we could remove it.
</blockquote></details>

But we need a way to create a pipe between two processes and I see no way of doing that, other than what we have right now (on a high level) - one process initiates a connection (pipe creation) and other one accepts it (acknowledges their end of the pipe), so to me it looks like we need `DkStreamWaitForClient` or something similar.


<!-- Sent from Reviewable.io -->

2022-06-01 09:30 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`Pal/include/pal/pal.h` line 301 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2ksuMC0J8btQmDsRaz:-N3TaRQQ9DzG0l6uapGA:b-5c5y0s) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/include/pal/pal.h#L301)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The best example are UNIX sockets - they allow for two unrelated processes to connect (and use PAL pipes).
Also we allow for connecting arbitrary processes in IPC, whic also uses PAL pipes. `mkfifo` is probably another example (though I"ve never looked at it, maybe it does something else).
</blockquote></details>

Yes, you are right, I give up here.


<!-- Sent from Reviewable.io -->

2022-06-02 02:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 47 of 62 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`common/src/socket_utils.c` line 34 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3Uv8Si6yfrXiTR5fcp:-N3WHUwC3q9jjhYnjIuS:b-voa8gv) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/common/src/socket_utils.c#L34)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

A little bit more details than `"ops"` ?
</blockquote></details>

I would even remove this string, it serves no purpose (we get file + line at compile time anyway), but it's not allowed in c11.
___
*[`common/src/socket_utils.c` line 51 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UvG0Z6xvbnXghZ6qx:-N3WLILj0Nt8vtExvFW8:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/common/src/socket_utils.c#L51)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

ditto
___
*[`common/src/socket_utils.c` line 69 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UvES80tdcOQSfrQ6S:-N3WLL5435qd_Ekp2k1W:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/common/src/socket_utils.c#L69)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

ditto
___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N3WLVgX15hZD4fuTcMp:b-xaxvyz) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Small nit if you want, we can put which lock is used which with field next to field.
Something like:
```
/* (L) Protected by `shim_lock lock;` */

enum shim_sock_state state; /* (L) */
```
</blockquote></details>

Hmm, I don't particularly like this `(L)` and adding a full sentence would cause a lot of unnecessary text and make it even less readable...
But I like the idea of putting such info near variables, not on the top.
Mixed feelings here. What do others think? @dimakuv @mkow 
___
*[`LibOS/shim/src/fs/socket/fs.c` line 2 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V3DZq98B0KK9LXdT4:-N3WMsor7r3Blqkcu8w8:b-hqcv04) ([raw file](https://github.com/gramineproject/gramine/blob/5ee0fc364712dbee1bd88cd029562acf6dc99468/LibOS/shim/src/fs/socket/fs.c#L2)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Are you sure you can just drop this copyright?
</blockquote></details>

Why not? This is only a hint, it doesn't describe who actually holds copyright of the content of this file. Besides, I've thrown this whole file out of the window and wrote it from scratch. The interface here did not change, so there might be some similarities.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 107 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V47UrBcArJqEHspra:-N3WObaJ4eIgEwkg5QVa:b-qb5lle) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/fs/socket/fs.c#L107)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Maybe just:
```
return pal_to_unix_errno(ret);
``
And drop:
```
ret = 0;
```
and
```
ret = pal_to_unix_errno(ret);
```
```

</blockquote></details>

Please fix the message, not sure what you are proposing.
___
*[`LibOS/shim/src/net/ip.c` line 25 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V0OIgBcv5hO9bNoKW:-N3WPKci7g9ascQJQRvN:brtil3) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L25)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

If I understand correctly this is when we think the we expect `familly` ex. `AF_INET` but then it turns out that the family is different I'm not sure if EAFNOSUPPORT is correct error code. 
</blockquote></details>

Why do you mean by "correct"? I just did what Linux does.
___
*[`LibOS/shim/src/net/ip.c` line 222 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V5C_FB9LVlrAi2zUp:-N3WPSRP1S9ZhuZVcAsr:b4o0drh) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L222)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

```
return pal_to_unix_errno(
   DkSocketConnect(sock->pal_handle, &pal_ip_addr, /*local_addr=*/NULL)
);
```
</blockquote></details>

IMO the proposed version looks uglier.
___
*[`LibOS/shim/src/net/ip.c` line 250 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V5OnE2mohseut2pMZ:-N3WPX4E6O7Ml1wBxqQ9:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L250)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto?
</blockquote></details>

ditto
___
*[`LibOS/shim/src/net/ip.c` line 319 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V6juwB00vjce4Lw78:-N3WQKRJ6p5Fr9CuDu2-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L319)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

```
val = attr.socket.tcp_cork;
```
Wont be casted to 0/1?
</blockquote></details>

Done.
___
*[`LibOS/shim/src/net/ip.c` line 347 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V7-jGDn9l7bh6NrXD:-N3WQLdu0JuNLk1rOdw2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L347)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/net/unix.c` line 32 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V7i5BDNqZ48v-6_im:-N3WQN2s3HTrueHXhLCA:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/unix.c#L32)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

More details?
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-06-02 07:44 UTC, dimakuv requested changes
> Reviewed 14 of 15 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N3YFl7B3ugvJSMvkoTz:b-3x7r70) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, I don't particularly like this `(L)` and adding a full sentence would cause a lot of unnecessary text and make it even less readable...
But I like the idea of putting such info near variables, not on the top.
Mixed feelings here. What do others think? @dimakuv @mkow 
</blockquote></details>

I don't see how this helps. I would be against such a convention.
___
*[`LibOS/shim/src/fs/socket/fs.c` line 2 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V3DZq98B0KK9LXdT4:-N3YG2nW68rrBtaJ4jDM:buag8qx) ([raw file](https://github.com/gramineproject/gramine/blob/5ee0fc364712dbee1bd88cd029562acf6dc99468/LibOS/shim/src/fs/socket/fs.c#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not? This is only a hint, it doesn't describe who actually holds copyright of the content of this file. Besides, I've thrown this whole file out of the window and wrote it from scratch. The interface here did not change, so there might be some similarities.
</blockquote></details>

Yes, we routinely do this on complete rewrites.
___
*[`LibOS/shim/src/net/ip.c` line 222 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V5C_FB9LVlrAi2zUp:-N3YGJgs99d96RJ4KDjM:bdeowmz) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/net/ip.c#L222)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO the proposed version looks uglier.
</blockquote></details>

Yes, I also don't like this proposed version.
___
*[`LibOS/shim/test/regression/udp.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YLurX1U1UcmDeLrzR:-N3YLurX1U1UcmDeLrzS:b-lv0gsp) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L58)):*
> ```C
>         err(EXIT_FAILURE, "recvmsg 1");
>     }
>     if ((size_t)size != iovec.iov_len) {
> ```

Wouldn't it make more sense to check against `sizeof(buf) / 2` or even more explicitly against `PACKET_SIZE / 2`?

Because in theory you're checking the return value of the syscall against the argument to the syscall -- the syscall implementation may be incorrect enough so that it modified both values, and both these values are equal to each other but are not equal to the actual expected `PACKET_SIZE / 2`.
___
*[`LibOS/shim/test/regression/udp.c` line 75 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YMKt85PUXcSuCtz16:-N3YMKt85PUXcSuCtz17:b6hw4ti) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L75)):*
> ```C
>     if (msg.msg_flags != MSG_TRUNC) {
>         errx(EXIT_FAILURE, "wrong flags returned 1: %d", msg.msg_flags);
>     }
> ```

Since we're checking `MSG_TRUNC`, what about we send a third packet that is small enough and thus doesn't set up the out flag `MSG_TRUNC`? You're currently missing this test case.

Otherwise the recv implementation in Gramine may always set up `MSG_TRUNC` on UDP (even for small packets), and this test will not catch this erroneous implementation.
___
*[`LibOS/shim/test/regression/udp.c` line 98 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YMfv52ZLn4VGvfvoh:-N3YMfv66QokIuHTke0z:b-l6qf3) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L98)):*
> ```C
>         .sin_port = htons(PORT),
>         .sin_addr = {
>             /* TODO: remove this once Ubuntu 18.04 is deprecated. */
> ```

What's the deal with this?
___
*[`Pal/include/pal/pal.h` line 585 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHd7p94Al8UocU2Mx:-N3YHd7qCzim_sPXTgAf:bm483qs) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/include/pal/pal.h#L585)):*
> ```objc
>  * \param      iov_len         Length of \p iov array.
>  * \param[out] out_total_size  On success contains the number of bytes received (TCP) or the size of
>  *                             the packed (UDP), which might be greater than the total size of
> ```

`packed` -> `packet`
___
*[`Pal/src/host/Linux/db_sockets.c` line 529 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHqH85zGdXA71goFJ:-N3YHqH85zGdXA71goFK:b-y0g1uh) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux/db_sockets.c#L529)):*
> ```C
>     unsigned int flags = is_nonblocking ? MSG_DONTWAIT : 0;
>     if (handle->sock.type == PAL_SOCKET_UDP) {
>         flags |= MSG_TRUNC;
> ```

Ah, interesting. So at the PAL level, you always request to return the actual datagram size, but "tweak" it at the LibOS layer (depending on the user-supplied flags). Maybe add a comment about this behavior?
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 511 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YIA6Y6HflmYxuBfWe:-N3YIA6Y6HflmYxuBfWf:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/db_sockets.c#L511)):*
> ```C
>     unsigned int flags = is_nonblocking ? MSG_DONTWAIT : 0;
>     if (handle->sock.type == PAL_SOCKET_UDP) {
>         flags |= MSG_TRUNC;
> ```

ditto
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N3YKyJG-458fYoaJ8Hq:b-qaljha) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
> ```C
>     }
> 
>     retval = ret_size;
> ```

This is technically not needed because above you have `size_t ret_size = retval;`. Do you just want to be explicit here? I'm not blocking.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1505 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKYzL78yS1Dgg8-NC:-N3YKYzL78yS1Dgg8-ND:bh1bblh) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1505)):*
> ```C
>     sgx_reset_ustack(old_ustack);
>     if (is_obuf_mapped)
>         ocall_munmap_untrusted_cache(obuf, ALLOC_ALIGN_UP(size), need_munmap);
> ```

Oops, you may leak memory here because `size` could be updated to `ret_size` (which could be less than original `size`).

I suggest to create a new variable and not reuse `size`, smth like this:
```
    size_t size_to_copy = MIN(size, ret_size);
    char* urts_buf = READ_ONCE(ms->ms_buf);
    size_t urts_buf_idx = 0;
    for (size_t i = 0; i < iov_len && urts_buf_idx < size_to_copy ; i++) {
        size_t this_size = MIN(size_to_copy - urts_buf_idx, iov[i].iov_len);
        if (!sgx_copy_to_enclave(iov[i].iov_base, iov[i].iov_len,
                                 urts_buf + urts_buf_idx, this_size)) {
            retval = -EPERM;
            goto out;
        }
        urts_buf_idx += this_size;
    }

```


<!-- Sent f [...]

2022-06-02 16:37 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/test/regression/udp.c` line 58 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YLurX1U1UcmDeLrzR:-N3_9HvW1A4gxKEFZhuX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it make more sense to check against `sizeof(buf) / 2` or even more explicitly against `PACKET_SIZE / 2`?

Because in theory you're checking the return value of the syscall against the argument to the syscall -- the syscall implementation may be incorrect enough so that it modified both values, and both these values are equal to each other but are not equal to the actual expected `PACKET_SIZE / 2`.
</blockquote></details>

Done.
___
*[`LibOS/shim/test/regression/udp.c` line 75 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YMKt85PUXcSuCtz16:-N3_DntVE_j0Rfsskyu5:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're checking `MSG_TRUNC`, what about we send a third packet that is small enough and thus doesn't set up the out flag `MSG_TRUNC`? You're currently missing this test case.

Otherwise the recv implementation in Gramine may always set up `MSG_TRUNC` on UDP (even for small packets), and this test will not catch this erroneous implementation.
</blockquote></details>

Done.
___
*[`LibOS/shim/test/regression/udp.c` line 98 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YMfv52ZLn4VGvfvoh:-N3_DqpO-yw_4GdMAwvX:bjckpd2) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/LibOS/shim/test/regression/udp.c#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the deal with this?
</blockquote></details>

No idea, CI on 18.04 failed with an error that `.sin_addr` is not initialized. Must be some kind of bug, since it was implicitly 0 initialized.
___
*[`Pal/include/pal/pal.h` line 585 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHd7p94Al8UocU2Mx:-N3_EBWt-98KSnMiEasX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/include/pal/pal.h#L585)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`packed` -> `packet`
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux/db_sockets.c` line 529 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHqH85zGdXA71goFJ:-N3_EGIy4X0mwuNKYpdn:brw5uzz) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux/db_sockets.c#L529)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, interesting. So at the PAL level, you always request to return the actual datagram size, but "tweak" it at the LibOS layer (depending on the user-supplied flags). Maybe add a comment about this behavior?
</blockquote></details>

Yes, this seemed like a simplest approach.
We have such comment in `DkSocketRecv`:
```
 * \param[out] out_total_size  On success contains the number of bytes received (TCP) or the size of
 *                             the packet (UDP), which might be greater than the total size of
 *                             buffers in \p iov array.
```
Or you wanted me to add a commen also here?
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N3_EheK7GGOEEAHsMbv:b8ruu89) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is technically not needed because above you have `size_t ret_size = retval;`. Do you just want to be explicit here? I'm not blocking.
</blockquote></details>

Yes, I just didn't want to track whether `retval` has changed or not, explicitly setting this seemed to ease the reading of this code.
Update: does not apply anymore, removed it.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1505 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKYzL78yS1Dgg8-NC:-N3_FsDW-8Qp49fLrC8W:b-app8o) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1505)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, you may leak memory here because `size` could be updated to `ret_size` (which could be less than original `size`).

I suggest to create a new variable and not reuse `size`, smth like this:
```
    size_t size_to_copy = MIN(size, ret_size);
    char* urts_buf = READ_ONCE(ms->ms_buf);
    size_t urts_buf_idx = 0;
    for (size_t i = 0; i < iov_len && urts_buf_idx < size_to_copy ; i++) {
        size_t this_size = MIN(size_to_copy - urts_buf_idx, iov[i].iov_len);
        if (!sgx_copy_to_enclave(iov[i].iov_base, iov[i].iov_len,
                                 urts_buf + urts_buf_idx, this_size)) {
            retval = -EPERM;
            goto out;
        }
        urts_buf_idx += this_size;
    }

```
</blockquote></details>

Ugh, yeah.
Done.


<!-- Sent from Reviewable.io -->

2022-06-03 07:40 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/test/regression/udp.c` line 38 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3cTT_o5s9kF5tEFRBI:-N3cTT_o5s9kF5tEFRBJ:bzl0sm) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/regression/udp.c#L38)):*
> ```C
>         .expected_return_value = PACKET_SIZE / 2, .expected_flags = 0,
>     },
> };
> ```

Starts to look more and more like LTP tests.

Heh, one day we'll decide to refactor our tests, and it will end up with some monstrosity as in LTP, with its helper funcs and macros.
___
*[`Pal/src/host/Linux/db_sockets.c` line 529 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHqH85zGdXA71goFJ:-N3cUgGxCrNJD5qLmte_:buffqfn) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux/db_sockets.c#L529)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, this seemed like a simplest approach.
We have such comment in `DkSocketRecv`:
```
 * \param[out] out_total_size  On success contains the number of bytes received (TCP) or the size of
 *                             the packet (UDP), which might be greater than the total size of
 *                             buffers in \p iov array.
```
Or you wanted me to add a commen also here?
</blockquote></details>

I would like to have some quick comment here (may be just a reference to the `DkSocketRecv` top-level comment)


<!-- Sent from Reviewable.io -->

2022-06-03 22:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 60 of 62 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`Pal/src/host/Linux/db_sockets.c` line 529 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YHqH85zGdXA71goFJ:-N3fdKX9DmNa8eSKpBzM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux/db_sockets.c#L529)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would like to have some quick comment here (may be just a reference to the `DkSocketRecv` top-level comment)
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_sockets.c` line 511 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YIA6Y6HflmYxuBfWe:-N3fdLtu5lQsx1Y7MiPu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/db_sockets.c#L511)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-05 04:14 UTC, boryspoplawski commented
Jenkins, retest this please (just making noise for another PR)

2022-06-05 07:20 UTC, boryspoplawski commented
Jenkins, retest this please (just making noise for another PR)

2022-06-07 06:42 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-06-07 21:45 UTC, mkow requested changes
Only LibOS left, posting my comments so far.

> Reviewed 9 of 54 files at r1, 2 of 10 files at r2, 8 of 11 files at r3, 2 of 24 files at r4, 11 of 26 files at r5, 3 of 12 files at r7, 6 of 15 files at r9, 3 of 3 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579#-:-N4-5rbX6Sr4XD6eYIDq:b-2999y4)* status: all files reviewed, 49 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eWfjX4uSF6O9jz_Mg:-N3eWfjYBQbV8OHbfo58:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
> ```C
>     static_assert(SAME_TYPE(family, linux_addr->ss_family)
>                   && offsetof(struct sockaddr_storage, ss_family) == 0, "oops");
>     /* Cannot use `&linux_addr->ss_family` because `linux_addr` might be missaligned. */
> ```





_Suggestion:_
```C
misaligned
```
___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eXOeo8uUkZjRkS7zy:-N3eXOeo8uUkZjRkS7zz:bfk0bo6) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
> ```C
>     static_assert(SAME_TYPE(family, linux_addr->ss_family)
>                   && offsetof(struct sockaddr_storage, ss_family) == 0, "oops");
>     /* Cannot use `&linux_addr->ss_family` because `linux_addr` might be missaligned. */
> ```

Why can it be misaligned? `struct sockaddr_storage` has alignment requirement at least as big as `ss_family`.
___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N4-5TkK2InBD9fCAnqc:bftxhlp) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see how this helps. I would be against such a convention.
</blockquote></details>

The current long comment is pretty hard to parse and use, so I really like @oshogbo's idea (modulo the details, you can change that `(L)` to anything you prefer).
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 1635 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3epRvA0B8pSsE2IHcC:-N3epRvA0B8pSsE2IHcD:b-dktj78) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L1635)):*
> ```INI
> # subtest 3: Linux ignores invalid address in recvfrom for stream sockets
> # subtest 6: Requires MSG_OOB support.
> # subtest 7: Requires MSG_ERRQUEUE support (skip MSG_ERRQUEUE test, it's supported from 3.17).
> ```

I don't understand what you meant here. 3.17 is Linux version? If so, what does it have to do with Gramine?
ditto below



_Code quote:_
```INI
Requires MSG_ERRQUEUE support (skip MSG_ERRQUEUE test, it's supported from 3.17).
```
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 2063 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3erpEX0Co65qdq2Ezm:-N3erpEX0Co65qdq2Ezn:bs0j7g0) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L2063)):*
> ```INI
> skip = yes
> 
> # SO_OOBINLINE not supported
> ```

Maybe prefix with "subtest 4: "?
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 2078 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3esMJKBDkeExxwv_WT:-N3esMJKBDkeExxwv_WU:b-lorz2j) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L2078)):*
> ```INI
> skip = yes
> 
> # subtest 1: regression test for a CVE, runs only on 32bit mode
> ```

(or "on 32-bit x86")



_Suggestion:_
```INI
in 32-bit mode
```
___
*[`Pal/include/pal/pal.h` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ui0MxCaJvaIdoD2No:-N3ezLuL-wlKSEKJrUU6:b-mkf3yr) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/include/pal/pal.h#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, if the changes are too big to incorporate them in this PR. But I think we should at least have a plan on how to solve it - otherwise maybe  the socket interfaces need to be tweaked.
@mkow any ideas?
</blockquote></details>

We could move it to its own header?
___
*[`Pal/include/pal/pal.h` line 38 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eMPa370GHh9zzUM4O:-N3eMPa370GHh9zzUM4P:b-rllozj) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L38)):*
> ```objc
> /* TODO: dependency order is UGHMMMM */
> enum pal_socket_domain {
>     PAL_DISCONNECT,
> ```

Could we use `PAL_DISCONNECTED` instead? Using a verb here is a bit confusing.
___
*[`Pal/include/pal/pal.h` line 520 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3f-sDwC-nMqr0WXwwa:-N3f-sDwC-nMqr0WXwwb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L520)):*
> ```objc
> 
> /*!
>  * \biref Turn a socket into listening one.
> ```





_Suggestion:_
```objc
into a listening one
```
___
*[`Pal/include/pal/pal.h` line 589 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3f1NZk7gWmklM4Q_8U:-N3f1NZk7gWmklM4Q_8V:b3nnw9j) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L589)):*
> ```objc
>  * \param[out] addr            Source address. Can be NULL to ignore the source address.
>  * \param      is_nonblocking  If `true` this request should not block. Otherwise just use whatever
>  *                             mode the handle is in.
> ```

With this semantic I'd rather call it `force_nonblocking`. Right now `is_nonblocking = false` doesn't mean that this recv is nonblocking.



_Code quote:_
```objc
 * \param      is_nonblocking  If `true` this request should not block. Otherwise just use whatever
 *                             mode the handle is in.
```
___
*[`Pal/regression/pal_regression.h` line 15 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eb60v6gxyHJmz11ry:-N3eb60v6gxyHJmz11rz:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/pal_regression.h#L15)):*
> ```objc
>     __typeof__(x) _x = (x);                                         \
>     if (_x < 0) {                                                   \
>         pal_printf("Error at %s (line %d): %d\n", #x, __LINE__, x); \
> ```





_Suggestion:_
```objc
pal_printf("Error at %s (line %d): %d\n", #x, __LINE__, _x);
```
___
*[`Pal/regression/send_handle.c` line 6 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3ecOda5gblXDffsiEM:-N3ecOda5gblXDffsiEN:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L6)):*
> ```C
> 
> #define MSG "Some message."
> #define MSG_SIZE static_strlen(MSG)
> ```





_Suggestion:_
```C
#define MSG_SIZE (static_strlen(MSG))
```
___
*[`Pal/regression/send_handle.c` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3egfo656IedYsQ--r5:-N3egfo7B0G76jlmvsVR:bapwy6w) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L9)):*
> ```C
> #define PORT 1337
> 
> static vo [...]

2022-06-08 02:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 48 of 63 files reviewed, 49 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eWfjX4uSF6O9jz_Mg:-N4-fj106fOv3LoKkfm6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
> ```C
>     static_assert(SAME_TYPE(family, linux_addr->ss_family)
>                   && offsetof(struct sockaddr_storage, ss_family) == 0, "oops");
>     /* Cannot use `&linux_addr->ss_family` because `linux_addr` might be missaligned. */
> ```

Done.
___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eXOeo8uUkZjRkS7zy:-N4-g57jAfhK1jqffbCY:b-d0omf9) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why can it be misaligned? `struct sockaddr_storage` has alignment requirement at least as big as `ss_family`.
</blockquote></details>

`linux_addr` might be misaligned, because we sometimes pass different type - actually just user pointer (see the comment above).
___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N4-hAfJ15UxyCEcHRi2:bemq4yc) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The current long comment is pretty hard to parse and use, so I really like @oshogbo's idea (modulo the details, you can change that `(L)` to anything you prefer).
</blockquote></details>

@mkow but the devil's in the detail here.
Not sure if I like this:
```c
struct shim_sock_handle {
    struct shim_lock lock;
    struct shim_sock_ops* ops; // Does not change
    /* This field should be accessed using atomic operations. It can be NULL. Once it's set, it
     * cannot change anymore. */
    PAL_HANDLE pal_handle;
    int domain; // Does not change
    int type; // Does not change
    int protocol; // Does not change
    enum shim_sock_state state; // Protected by `lock`
    struct sockaddr_storage remote_addr; // Protected by `lock`
    size_t remote_addrlen; // Protected by `lock`
    struct sockaddr_storage local_addr; // Protected by `lock`
    size_t local_addrlen; // Protected by `lock`
    struct {
        char* buf;
        size_t buf_size;
        size_t data_size;
    } peek;  // Protected by `recv_lock`
    /* This lock also ensures proper ordering of stream reads (see the comment in `do_recvmsg` in
     * "LibOS/shim/src/sys/shim_socket.c"). */
    struct shim_lock recv_lock;
    unsigned int last_error; // Protected by `lock`
    uint64_t sendtimeout_us; // Protected by `lock`
    uint64_t receivetimeout_us; // Protected by `lock`
    /* This field denotes whether the socket was ever bound. */
    bool was_bound; // Protected by `lock`
    bool can_be_read; // Protected by `lock`
    bool can_be_written; // Protected by `lock`
};
```
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 1635 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3epRvA0B8pSsE2IHcC:-N4-jO3z-lrQ0C8qjtDa:bduxjjp) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L1635)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand what you meant here. 3.17 is Linux version? If so, what does it have to do with Gramine?
ditto below
</blockquote></details>

This is the message LTP prints when skipping this test. I think we report some lower version in VDSO, so LTP skips this tests (regardless whether we actually support this flag). Not sure how to make this cleaner.
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 2063 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3erpEX0Co65qdq2Ezm:-N4-lr7-8M7rDvijQY6y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L2063)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe prefix with "subtest 4: "?
</blockquote></details>

Done.
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 2078 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3esMJKBDkeExxwv_WT:-N4-m0JK1zkiv8LZc1TJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L2078)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(or "on 32-bit x86")
</blockquote></details>

Done.
___
*[`Pal/include/pal/pal.h` line 36 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1ui0MxCaJvaIdoD2No:-N4-m4Rp7FthykotGPwa:brs0nn0) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/include/pal/pal.h#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We could move it to its own header?
</blockquote></details>

Yes, though it won't solve the underlying issue (which we probably will hit again, sooner or later). The main problem here is that we have some types that use `PAL_HANDLE`, which is defined in `pal_host.h`, but that header also uses some common PAL types...
Putting this in a separate header is imho the same as keeping them here inline. Thinking more about this, I don't think there is another solution, we have to live with this.
___
*[`Pal/include/pal/pal.h` line 38 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eMPa370GHh9zzUM4O:-N4-o3CXEIdF4Hfqes8N:b5acrj3) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we use `PAL_DISCONNECTED` instead? Using a verb here is a bit confusing.
</blockquote></details>

Yes, but if you look at the usage, it's kind of a command to `DkSocketConnect` to disconnect the socket. It's just stashed together with the domain, as we repurpose the address field, just like Linux does (the other option I see is introducing another PAL call `DkSocketDisconnect`, but it sounds excessive).
___
*[`Pal/include/pal/pal.h` line 520 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3f-sDwC-nMqr0WXwwa:-N4-oxVVCbsNhBR-bv1n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L520)):*
> ```objc
> 
> /*!
>  * \biref Turn a socket into listening one.
> ```

Done.
___
*[`Pal/include/pal/pal.h` line 589 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3f1NZk7gWmklM4Q_8U:-N4-p4Sz3VuHnVk7k_O8:b-th4zij) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L589)):*
> Right now `is_nonblocking = false` doesn't mean that this recv is nonblocking.

Well, yes, why would it? Or that was a typo and you meant blocking? Then yes.
Anyway, I like `force_nonblockin`, so done.
___
*[`Pal/regression/pal_regression.h` line 15 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eb60v6gxyHJmz11ry:-N4-qwxl06-duyzKJWiB:b-oz8o77) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/pal_regress [...]

2022-06-08 23:47 UTC, mkow requested changes
> Reviewed 1 of 54 files at r1, 15 of 15 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eXOeo8uUkZjRkS7zy:-N42SvUeCcmBvYBZSxFY:bb7fkiu) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`linux_addr` might be misaligned, because we sometimes pass different type - actually just user pointer (see the comment above).
</blockquote></details>

Hmm, is it legal to have it in a `struct sockaddr_storage*` pointer then? (in terms of UBs)
___
*[`LibOS/shim/include/shim_socket.h` line 102 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N42rkdmB9nAmm2ZOpnJ:-N42rkdmB9nAmm2ZOpnK:bmqkwy3) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L102)):*
> ```objc
>      *                                truncation has happened.
>      * \param         is_nonblocking  If `true` this request should not block. Otherwise just use
>      *                                whatever mode the handle is in.
> ```

You missed this one. Please grep the whole PR.



_Code quote:_
```objc
     * \param         is_nonblocking  If `true` this request should not block. Otherwise just use
     *                                whatever mode the handle is in.
```
___
*[`LibOS/shim/test/ltp/ltp.cfg` line 1635 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3epRvA0B8pSsE2IHcC:-N42TIGx6C1lcejFq4NR:b-8hq0px) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/LibOS/shim/test/ltp/ltp.cfg#L1635)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is the message LTP prints when skipping this test. I think we report some lower version in VDSO, so LTP skips this tests (regardless whether we actually support this flag). Not sure how to make this cleaner.
</blockquote></details>

Aaah, with double quotes it makes much more sense. Didn't know that was a quote from somewhere.
___
*[`Pal/include/pal/pal.h` line 38 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eMPa370GHh9zzUM4O:-N42TrJw3wYeYOEtKQS1:b-jdy16y) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, but if you look at the usage, it's kind of a command to `DkSocketConnect` to disconnect the socket. It's just stashed together with the domain, as we repurpose the address field, just like Linux does (the other option I see is introducing another PAL call `DkSocketDisconnect`, but it sounds excessive).
</blockquote></details>

Hmm, weird, but won't block here because I'm not sure how to rewrite it.
___
*[`Pal/include/pal/pal.h` line 589 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3f1NZk7gWmklM4Q_8U:-N42UCE_1taHG80NWEry:b117f5n) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/include/pal/pal.h#L589)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Right now `is_nonblocking = false` doesn't mean that this recv is nonblocking.

Well, yes, why would it? Or that was a typo and you meant blocking? Then yes.
Anyway, I like `force_nonblockin`, so done.
</blockquote></details>

Yup, I meant "blocking", sorry.
___
*[`Pal/regression/send_handle.c` line 6 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3ecOda5gblXDffsiEM:-N42pjUDB30xFqXdt7ZZ:b-bbyf3r) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This has the highest precedence (it's either a function call or a macro which then must have the parens)...
If you really want, I can add them
</blockquote></details>

Technically it's not the highest, because despite being in the first precedence group, this group binds left-to-right. So, `.` and `->` take precedence.
Not that it practically matters, but for sanity I prefer to ensure our macros can't be parsed weirdly.
___
*[`Pal/regression/send_handle.c` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3egfo656IedYsQ--r5:-N42rHvWAO81N2NzM2w8:b-pi9plc) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wdym? `git grep DkStreamWrite Pal/regression/` doesn't show anything
</blockquote></details>

Ah, ok, they differ in the underlying write call.
___
*[`Pal/src/host/Linux/db_sockets.c` line 83 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3vWLc1Dt9x4ZeXQXW-:-N42sMr_9oUbH0TepnOA:bjn07sx) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please fix this also in other similar places (other PAL and `DkSocketCreate()`)
___
*[`Pal/src/host/Linux/db_sockets.c` line 210 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3vZh5CAyvLKz63n25c:-N42suFQ9iPWMBRS3M2S:b-pn54b0) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L210)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think we have such convention for simple pointers, e.g. we write `char* buf` not `char* out_buf`.
</blockquote></details>

I think this is in cases where it's very obvious that `buf` is the output. Here it isn't, and if `client_addr` was input-only, then this signature would look the same (maybe except of order of the args).
___
*[`Pal/src/host/Linux/db_sockets.c` line 318 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3yH_MOBHUuwPLQeT4B:-N42uTEl-fUMJH0BxNag:byogc94) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L318)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, this was made as part of the API, forgot to remote this TODO.
</blockquote></details>

Where? I couldn't find it.
___
*[`Pal/src/host/Linux/db_sockets.c` line 608 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3y_5rMB9_CGtbRLJyp:-N42vSSsD-aeTp9ZpUwI:bcoqg3o) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L608)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about `fixup_socket_handle_after_deserialize`? Pretty long though...
Btw, the name originates from times when this function had multiple args and actually took an `char*` argument + size.
</blockquote></details>

I like it, we don't use it in many places, so it's not a problem that it's long.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https:// [...]

2022-06-09 16:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`common/src/socket_utils.c` line 52 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3eXOeo8uUkZjRkS7zy:-N47ylJN9F1dTZ8hL-iq:b-mi82na) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/common/src/socket_utils.c#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, is it legal to have it in a `struct sockaddr_storage*` pointer then? (in terms of UBs)
</blockquote></details>

Well, it isn't :) Whoever designed these socket interfaces with mulitplexing multiple types in one argument was evil.
Anyway, fixed.
___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N48A4zN0BviQk6VppwA:bxrxwm7) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I vehemently dislike it.
</blockquote></details>

@mkow ^
___
*[`LibOS/shim/include/shim_socket.h` line 102 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N42rkdmB9nAmm2ZOpnJ:-N48BQxo4bunsLQ1R31h:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You missed this one. Please grep the whole PR.
</blockquote></details>

Done.
___
*[`Pal/regression/send_handle.c` line 6 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3ecOda5gblXDffsiEM:-N48CTCMD3GXKfvarbVg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Technically it's not the highest, because despite being in the first precedence group, this group binds left-to-right. So, `.` and `->` take precedence.
Not that it practically matters, but for sanity I prefer to ensure our macros can't be parsed weirdly.
</blockquote></details>

Done.
___
*[`Pal/regression/send_handle.c` line 9 at r11](https://reviewable.io/reviews/gramineproject/gramine/579#-N3egfo656IedYsQ--r5:-N48CocdEPYI_YCd8OFF:bnom3o3) ([raw file](https://github.com/gramineproject/gramine/blob/11fdb467983d786121c86067f7addb522a7a1b00/Pal/regression/send_handle.c#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, ok, they differ in the underlying write call.
</blockquote></details>

But which 4 functions you meant? I couldn't find anything even looking manually (except `buf_write_all`, but it's completely different)
I would be good to deduplicate if there is something
___
*[`Pal/src/host/Linux/db_sockets.c` line 83 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3vWLc1Dt9x4ZeXQXW-:-N48E4uRD-qqjeilibRu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix this also in other similar places (other PAL and `DkSocketCreate()`)
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux/db_sockets.c` line 210 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3vZh5CAyvLKz63n25c:-N48EeKc5A6_NDf73Kdk:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L210)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this is in cases where it's very obvious that `buf` is the output. Here it isn't, and if `client_addr` was input-only, then this signature would look the same (maybe except of order of the args).
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux/db_sockets.c` line 318 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3yH_MOBHUuwPLQeT4B:-N48EjOD9_CR83INHigx:b-a1v3uh) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L318)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where? I couldn't find it.
</blockquote></details>

See other (closed) discussions at this line
___
*[`Pal/src/host/Linux/db_sockets.c` line 608 at r13](https://reviewable.io/reviews/gramineproject/gramine/579#-N3y_5rMB9_CGtbRLJyp:-N48FPZR9e5Jes-yS7Ia:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/87504d4bbc40da17159e26368205d362b70ba3a2/Pal/src/host/Linux/db_sockets.c#L608)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like it, we don't use it in many places, so it's not a problem that it's long.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N48FeYL3_G6XnA1Z5dH:bvkfi40) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, that's ugly. Why not an out argument?
</blockquote></details>

No idea, I did not write this ocall. I would assume to have the correspondence between ocalls and their unrelying functions, i.e. `ocall_recv` behaves as close to the normal `recv` syscall as possible, but that's just a guess.


<!-- Sent from Reviewable.io -->

2022-06-09 19:34 UTC, mkow requested changes
> Reviewed 3 of 54 files at r1, 1 of 24 files at r4, 1 of 26 files at r5, 1 of 12 files at r7, 1 of 15 files at r9, 14 of 15 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 62 of 63 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N48MFZCDk4877cjNoZ0:b-6hhx6g) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@mkow ^
</blockquote></details>

I rather thought about something like this:
```C
struct shim_sock_handle {
    /* [C] - No locking needed, constant after initialization.
     * [A] - Should be accessed only using atomic operations. Once set, cannot change
     *       anymore.
     * [L] - Protected by `lock`.
     * [R] - Protected by `recv_lock`.
     */
    /*   */ struct shim_lock lock;
    /*[C]*/ struct shim_sock_ops* ops;
    
    /*[A]*/ PAL_HANDLE pal_handle; // Can be NULL
    /*[C]*/ int domain;
    /*[C]*/ int type;
    /*[C]*/ int protocol;
    /*[L]*/ enum shim_sock_state state;
    /*[L]*/ struct sockaddr_storage remote_addr;
    /*[L]*/ size_t remote_addrlen;
    /*[L]*/ struct sockaddr_storage local_addr;
    /*[L]*/ size_t local_addrlen;
    /*[R]*/ struct {
    /*[R]*/     char* buf;
    /*[R]*/     size_t buf_size;
    /*[R]*/     size_t data_size;
    /*[R]*/ } peek;
            /* This lock also ensures proper ordering of stream reads (see the comment in
             * `do_recvmsg` in "LibOS/shim/src/sys/shim_socket.c"). */
    /*   */ struct shim_lock recv_lock;
    /*[L]*/ unsigned int last_error;
    /*[L]*/ uint64_t sendtimeout_us;
    /*[L]*/ uint64_t receivetimeout_us;
    /*[L]*/ bool was_bound; // Denotes whether the socket was ever bound.
    /*[L]*/ bool can_be_read;
    /*[L]*/ bool can_be_written;
};
```
A bit ASCII-arty, but IMO *much* more readable than this super long sentence at the top of the struct we have now.
___
*[`LibOS/shim/include/shim_socket.h` line 36 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48E-av671iNClzX3-k:-N48E-av671iNClzX3-l:b1531ip) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L36)):*
> ```objc
>      * \brief Accept a connection on a listening handle.
>      *
>      * \param handle           Handle in listening mode.
> ```

Could you assert this in the handlers?

Also, probably should be "A handle" (same in other places in this file).



_Code quote:_
```objc
Handle in listening mode.
```
___
*[`LibOS/shim/include/shim_socket.h` line 38 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48EkFUEfXftPBtP27i:-N48EkFUEfXftPBtP27j:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L38)):*
> ```objc
>      * \param handle           Handle in listening mode.
>      * \param is_nonblocking   `true` if the new handle is to be set in nonblocking mode.
>      * \param[out] client_ptr  On success contains the new handle.
> ```





_Suggestion:_
```objc
out_client
```
___
*[`LibOS/shim/include/shim_socket.h` line 38 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48Eppk12YJtZvhjlQW:-N48Eppk12YJtZvhjlQX:b-yuut19) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L38)):*
> ```objc
>      * \param handle           Handle in listening mode.
>      * \param is_nonblocking   `true` if the new handle is to be set in nonblocking mode.
>      * \param[out] client_ptr  On success contains the new handle.
> ```

please fix alignment after `\param` (and also grep the whole PR for this issue)
___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N48GbdeA0qFWyCHB9vK:b-i5vq0v) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
> ```objc
>      * \param      iov_len   Length of \p iov.
>      * \param[out] out_size  On success contains the number of bytes sent.
>      * \param      addr      Address to send to. May be NULL.
> ```

What happens then? Please document.



_Code quote:_
```objc
May be NULL.
```
___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 848 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48YCde4-kYgB8LKFM4:-N48YCde4-kYgB8LKFM5:bmdf2qh) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/bookkeep/shim_signal.c#L848)):*
> ```C
> 
> bool is_eintr_like(int ret) {
>     switch (ret) {
> ```

Could you assert that `ret <= 0`? Just to be sure that we never accidentally pass a positive errno.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N48daISBY9UmvEyr7PY:bheb44i) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting, I never noticed that the peer's address may be truncated by these functions. Now I know.
</blockquote></details>

@boryspoplawski: Maybe worth a comment saying that this is what Linux does? Having this weird behavior implicitly in the code may make readers think that this could be a bug.
Ditto for `unix.c`.
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N48couk0fbdPdhrEJ3t:bvgg9q4) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
> ```C
> /*
>  * Implementation of IPv4 and IPv6 sockets.
>  * `handle->info.sock.pal_handle` is always set, hence does not need atomicity on accesses.
> ```

This seem to contradict what's written in `shim_handle.h`. Or maybe you mean here that IPv4 and IPv6 sockets _specifically_ have stronger guarantees about this field, hence no locks? If so, I'd reword this comment to say this more explicitly.
___
*[`LibOS/shim/src/net/ip.c` line 27 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48ePz_4vYZqoAC1LOy:-N48ePz_4vYZqoAC1LOz:bkm3s92) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L27)):*
> ```C
>                 return -EAFNOSUPPORT;
>             }
>             *addrlen = sizeof(struct sockaddr_in);
> ```

Why are we returning this size? There's only one callsite which uses this (`connect()`) and there it looks dangerous - we may access more bytes than `size_t addrlen` passed to `connect()`. This may be fine if we assume that the caller of `connect()` has to make sure that `addrlen` is valid, but then what's the point of overwriting it here? We either rely that it's correct or not.
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N48hPnv0qpQvrjQWA-o:b-713fpr) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
> ```C
> }
> 
> static int create(struct shim_handle* handle) {
> ```

Wouldn't both the interface and the code here be cleaner if socket domain and type were passed as arguments, instead  [...]

2022-06-09 22:07 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 50 of 63 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N49-qA219lQ_BNVf-Bj:b-j1i9g4) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I rather thought about something like this:
```C
struct shim_sock_handle {
    /* [C] - No locking needed, constant after initialization.
     * [A] - Should be accessed only using atomic operations. Once set, cannot change
     *       anymore.
     * [L] - Protected by `lock`.
     * [R] - Protected by `recv_lock`.
     */
    /*   */ struct shim_lock lock;
    /*[C]*/ struct shim_sock_ops* ops;
    
    /*[A]*/ PAL_HANDLE pal_handle; // Can be NULL
    /*[C]*/ int domain;
    /*[C]*/ int type;
    /*[C]*/ int protocol;
    /*[L]*/ enum shim_sock_state state;
    /*[L]*/ struct sockaddr_storage remote_addr;
    /*[L]*/ size_t remote_addrlen;
    /*[L]*/ struct sockaddr_storage local_addr;
    /*[L]*/ size_t local_addrlen;
    /*[R]*/ struct {
    /*[R]*/     char* buf;
    /*[R]*/     size_t buf_size;
    /*[R]*/     size_t data_size;
    /*[R]*/ } peek;
            /* This lock also ensures proper ordering of stream reads (see the comment in
             * `do_recvmsg` in "LibOS/shim/src/sys/shim_socket.c"). */
    /*   */ struct shim_lock recv_lock;
    /*[L]*/ unsigned int last_error;
    /*[L]*/ uint64_t sendtimeout_us;
    /*[L]*/ uint64_t receivetimeout_us;
    /*[L]*/ bool was_bound; // Denotes whether the socket was ever bound.
    /*[L]*/ bool can_be_read;
    /*[L]*/ bool can_be_written;
};
```
A bit ASCII-arty, but IMO *much* more readable than this super long sentence at the top of the struct we have now.
</blockquote></details>

I dislike every version (including the one we have right now), so I'll let you guys decide :)
___
*[`LibOS/shim/include/shim_socket.h` line 36 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48E-av671iNClzX3-k:-N490TFo25N1HOeZu4My:b-meb0p8) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L36)):*
> Could you assert this in the handlers?

Yes, but this would require taking a lock, so pretty annoying, like:
```c
assert( ({
    lock(&handle->info.sock.lock);
    enum shim_sock_state state = handle->info.sock.state;
    unlock(&handle->info.sock.lock);
    state == SOCK_LISTENING;
}));
```
Not sure if it's worth, since only usage of this function pointer explicitly checks it (`do_accept` in `shim_socket.c`).
___
*[`LibOS/shim/include/shim_socket.h` line 38 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48EkFUEfXftPBtP27i:-N49CPVw9QnZJmHH9421:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L38)):*
> ```objc
>      * \param handle           Handle in listening mode.
>      * \param is_nonblocking   `true` if the new handle is to be set in nonblocking mode.
>      * \param[out] client_ptr  On success contains the new handle.
> ```

Done.
___
*[`LibOS/shim/include/shim_socket.h` line 38 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48Eppk12YJtZvhjlQW:-N49CyvE9sp-3SLUzqRX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment after `\param` (and also grep the whole PR for this issue)
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N49ELI14DDOGyH_tySc:b-o5v9wv) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What happens then? Please document.
</blockquote></details>

Nothing happens. It's up to this function being called, to decide what to do.
___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 848 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48YCde4-kYgB8LKFM4:-N49EZGP3kylXgWPhByW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/bookkeep/shim_signal.c#L848)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you assert that `ret <= 0`? Just to be sure that we never accidentally pass a positive errno.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N49Jwiq-aKF94ONt2l7:bc11yeh) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
Done.

>  Ditto for unix.c.

? `unix.c` does not use addr at all.
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N49GjVEAV520CNGx7uw:b6sk11s) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
> Or maybe you mean here that IPv4 and IPv6 sockets specifically have stronger guarantees about this field, hence no locks

Yes. Not sure what you want me to put here - this whole file is about IPv4 and IPv6 sockets.
___
*[`LibOS/shim/src/net/ip.c` line 27 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48ePz_4vYZqoAC1LOy:-N49H5Ag99zIEPm2ITm-:blyy9is) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why are we returning this size? There's only one callsite which uses this (`connect()`) and there it looks dangerous - we may access more bytes than `size_t addrlen` passed to `connect()`. This may be fine if we assume that the caller of `connect()` has to make sure that `addrlen` is valid, but then what's the point of overwriting it here? We either rely that it's correct or not.
</blockquote></details>

What? We check `*addrlen < sizeof(struct sockaddr_in)` above. This never increases the size, it can only shrink it.
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N49Hbbp-H9R7AdE3Yzb:b-g6pen8) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't both the interface and the code here be cleaner if socket domain and type were passed as arguments, instead of being underhandedly passed in `handle` fields? ;)
OTOH, a lot of other fields is already being initialized in that `create_sock_handle()`, so this reduces duplication... Maybe then change this callback name to `create_pal_handle`?
Dunno, but my overall impression from reading this function was that it's weird :)
</blockquote></details>

Quoting the header:
```
    /*!
     * \brief Verify the socket handle and initialize type specific fields.
     *
     * This callback assumes that \p handle is already correctly initialized.
    [...]

2022-06-09 23:17 UTC, mkow requested changes
> Reviewed 12 of 12 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 62 of 63 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_socket.h` line 36 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48E-av671iNClzX3-k:-N49cjLE6iXM9Bv9VRGm:b9ekrs3) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Could you assert this in the handlers?

Yes, but this would require taking a lock, so pretty annoying, like:
```c
assert( ({
    lock(&handle->info.sock.lock);
    enum shim_sock_state state = handle->info.sock.state;
    unlock(&handle->info.sock.lock);
    state == SOCK_LISTENING;
}));
```
Not sure if it's worth, since only usage of this function pointer explicitly checks it (`do_accept` in `shim_socket.c`).
</blockquote></details>

Ok, probably not worth it then.
___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N49ctxy9jj6i8qUHDN-:b3cquf9) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nothing happens. It's up to this function being called, to decide what to do.
</blockquote></details>

But this is a common interface which all of these functions implement, and it is documented here. Also, you document the meaning of this field if non-NULL ("An address to send to"), but omit the meaning if NULL.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N49hFJf--tWHojDzGsL:b-r7xdc5) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.

>  Ditto for unix.c.

? `unix.c` does not use addr at all.
</blockquote></details>

But it has a similar truncations in 2 other places?
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N49eVHV02fgFtE4Qbxm:bf9iili) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Or maybe you mean here that IPv4 and IPv6 sockets specifically have stronger guarantees about this field, hence no locks

Yes. Not sure what you want me to put here - this whole file is about IPv4 and IPv6 sockets.
</blockquote></details>

e.g. something like: (otherwise it sounds like a bug/divergence from the abstract interface header)



_Suggestion:_
```C
is always set in IPv4 and IPv6 implementations
```
___
*[`LibOS/shim/src/net/ip.c` line 27 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48ePz_4vYZqoAC1LOy:-N49fT7Q0iED2F75Pu58:b-q94t7b) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What? We check `*addrlen < sizeof(struct sockaddr_in)` above. This never increases the size, it can only shrink it.
</blockquote></details>

Ah, ok, didn't notice that it's only one way.
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N49fjtt36UoPxMMP_j-:b1x5mxk) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
> `create_pal_handle` is not it

Why? Having both "initialization" and "creation" steps is quite confusing to me, because these words are usually +/- synonyms (except that "creation" sometimes means "allocation+initialization").
@dimakuv: Any thoughts here?
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N49g8YUD5vyTyICsEYU:b-kibmqq) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is rooted to deeply in me, I'll never get used to it.
Is this even our official guideline? We don't have it anywhere and google c++ guidelines (which I believe we use in the parts we do not cover ourselves) uses preincrement: https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement
</blockquote></details>

Google guide uses postincrement because it's for C++, in which it matters. In C it seems a bit weird to me, and we already use `i++` almost everywhere, so it would be nice to be uniform.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 828 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48IvWs3j-eGegHIEkU:-N49jwM2EYvNFR6HiSL8:bk1wpa4) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/sys/shim_socket.c#L828)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It might be bigger only for `SOCK_DGRAM` (UDP) and here we only handle `SOCK_STREAM` (TCP) hence it cannot be bigger.
</blockquote></details>

Could you then assert that it didn't change? Or pass a copy there. These assumptions are currently very implicit in the code.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N49j7TK8SMeXLzOsqvw:bk1lrab) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea, I did not write this ocall. I would assume to have the correspondence between ocalls and their unrelying functions, i.e. `ocall_recv` behaves as close to the normal `recv` syscall as possible, but that's just a guess.
</blockquote></details>

You just rewrote most of it, including a change to its arguments ;) Don't we want to make it more uniform with the rest of the codebase, where we don't mix error code with retval?


<!-- Sent from Reviewable.io -->

2022-06-09 23:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 62 of 63 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N49maX4DQAVd4Rb5E9p:b5pa5rv) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
> But this is a common interface which all of these functions implement, and it is documented here. 

Yes - so no function implementing this interface can assume that `addr` is present. It might not be.

> you document the meaning of this field if non-NULL ("An address to send to"), but omit the meaning if NULL.

Do you want me to write that if it's NULL then the address is not provided, like this?

`An address to send to. May be NULL (no address provided).`

Otherwise I have no idea what you want me to do.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N49ra7X9PgoHilC5WhW:b-ma6kr1) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it has a similar truncations in 2 other places?
</blockquote></details>

Which are?
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N49nfxg7zphCwbh-83i:b-p3d0tb) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
But the previous sentence states this file is all about IPv5 and IPv6. This is just a repetition...

> otherwise it sounds like a bug/divergence from the abstract interface header

Because it is a divergence. Code outside of this file does not know about it (i.e. it always uses atomics, even if the socket is IPv4 one).
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N49oOu7AMSUCEequA6O:b-e5uujo) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
> Why?

Because this callback does also other things, picking one arbitrary and putting it in the name sounds weird.

If something is to be changed the it's the interface name (this particular implementation too, but only as a result) - from what you described is the `create` name you don't like, since it does verification and initialization (partial).
Maybe just call it `initialize`?
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N49pVS28oL7YztOYov1:bl2s7wi) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
> Google guide uses postincrement because it's for C++, in which it matters. 

Yes, but this is only *one* of the reasons it states that it uses it. 

> we already use i++ almost everywhere

Because you always keep telling me to change :)
___
*[`LibOS/shim/src/sys/shim_socket.c` line 828 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48IvWs3j-eGegHIEkU:-N49sFb61Y0fJmxoq3aZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/sys/shim_socket.c#L828)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you then assert that it didn't change? Or pass a copy there. These assumptions are currently very implicit in the code.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N49s_Y7B6cu8jYqfA6M:b-mteo5b) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
> You just rewrote most of it, including a change to its arguments

I just changed the argument to be `iov` (well, and added flags), so size calculations changed, but otherwise it's the same.

> Don't we want to make it more uniform with the rest of the codebase, where we don't mix error code with retval?

Yeah, but then I would need to change rest of the ocalls to be like that (it would be too weird to have `send` or `read` with different api)...


<!-- Sent from Reviewable.io -->

2022-06-10 00:32 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 62 of 63 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N49uCr2BtLBezx4sOX8:bh1ufcg) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But this is a common interface which all of these functions implement, and it is documented here. 

Yes - so no function implementing this interface can assume that `addr` is present. It might not be.

> you document the meaning of this field if non-NULL ("An address to send to"), but omit the meaning if NULL.

Do you want me to write that if it's NULL then the address is not provided, like this?

`An address to send to. May be NULL (no address provided).`

Otherwise I have no idea what you want me to do.
</blockquote></details>

What I mean is that reading this documentation leaves the reader unsure what you meant - you say that it may be `NULL`, but doesn't say what happens then, and as its user you have to know this. "no address provided" doesn't help, that's basically the definition of "NULL", and what I'd want to know reading this signature is what semantic "sending to no address" has.
Actually, from reading the code, even the "An address to send to" part seems misleading, as some implementations (e.g. unix sockets) completely ignore this argument? So, for them it's not the address where the data will be sent, it's just ignored and another destination is used.
For me such documentation was really confusing, as I didn't know the implementation when reading it (and in general, documentation's purpose is to be clear without the need of reading the whole implementation yourself).
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N4A-AWhA28BL6TL-g5e:blsnsb4) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Which are?
</blockquote></details>

`bind()` and `connect()` seem to do the same.
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N49xUAFAwIeToGJZGJg:bqpujc9) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
> But the previous sentence states this file is all about IPv5 and IPv6. This is just a repetition...

That this _file_ is IPv4 and IPv6, yes. But the next sentence doesn't say that "in this file `handle->info.sock.pal_handle` is always set", it says "`handle->info.sock.pal_handle` is always set" - i.e. my first understanding of this was that this is a general property of `handle->info.sock.pal_handle` field of which you want to remind the reader here. And that's why I suggested adding " in IPv4 and IPv6 implementations".
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N49yXe65QJOF38loW9D:b-4h5q7l) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
> If something is to be changed the it's the interface name

I assumed we would change both.

`initialize` is better, but it's still confusing that part of the initialization is inlined in `create_sock_handle()` and part happens here. What's the key by which these parts were split? Could we reflect it somehow in the name of the interface? (i.e. something like `initialize_XYZ`)
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N49zdqR40B6hdGAULln:b34dxwu) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
> Yes, but this is only one of the reasons it states that it uses it.

The other is about the return value, which we don't use ;) It also says: "The tradition developed, in C, of using post-increment, even when the expression value is not used, especially in for loops."

> Because you always keep telling me to change :)

Yup, so that we have uniform style in the code :)
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N4A-Kk24JYtLwF5tfPx:bmyzpmm) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> You just rewrote most of it, including a change to its arguments

I just changed the argument to be `iov` (well, and added flags), so size calculations changed, but otherwise it's the same.

> Don't we want to make it more uniform with the rest of the codebase, where we don't mix error code with retval?

Yeah, but then I would need to change rest of the ocalls to be like that (it would be too weird to have `send` or `read` with different api)...
</blockquote></details>

Ok, we can leave it for later then, but I wouldn't mind changing this single ocall to decrease the number of functions which break our conventions.


<!-- Sent from Reviewable.io -->

2022-06-10 01:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 62 of 63 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N4A8vRe02UOUUjG1u5E:b-s0wrpj) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
> but doesn't say what happens then

Because it's up to the implementation to decide. Users of this don't know and they assume nothing.

> and as its user you have to know this. 

No, you actually don't.

> what I'd want to know reading this signature is what semantic "sending to no address" has.

But there is no semantic. It's up to the function implemented, the "backend" to decide what to do with this information.
There is **no** common semantic here. And no strings attached - callers assume nothing about it either.

> Actually, from reading the code, even the "An address to send to" part seems misleading, as some implementations (e.g. unix sockets) completely ignore this argument? 

Yes, because that's the semantics of this argument for UNIX sockets. For TCP it's the same - just ignore. And for UDP it's different. And if we ever implement something else it might be different. There is no common thing except it's an address and it might be there or might not be.
And this is what is documented here.

> For me such documentation was really confusing, as I didn't know the implementation when reading it (and in general, documentation's purpose is to be clear without the need of reading the whole implementation yourself).

This is documentation of an interface, so it documents the requirements and things you can assume about it.

> as I didn't know the implementation when reading it 

There are many implementations not a single one.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N4ADc_XDx1dHAp97prd:b-eml5jo) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`bind()` and `connect()` seem to do the same.
</blockquote></details>

For `bind()` and `connect()` address is an input argument, how could they truncate it...
___
*[`LibOS/shim/src/net/ip.c` line 8 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48couk0fbdPdhrEJ3s:-N4AB0KhDyeUkSoftZDT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> But the previous sentence states this file is all about IPv5 and IPv6. This is just a repetition...

That this _file_ is IPv4 and IPv6, yes. But the next sentence doesn't say that "in this file `handle->info.sock.pal_handle` is always set", it says "`handle->info.sock.pal_handle` is always set" - i.e. my first understanding of this was that this is a general property of `handle->info.sock.pal_handle` field of which you want to remind the reader here. And that's why I suggested adding " in IPv4 and IPv6 implementations".
</blockquote></details>

Done.
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N4ABG0b6hLcTKf3FRid:b-xf0ppr) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
> What's the key by which these parts were split? 

`\brief (...) and initialize type specific fields.`
Type here means type of socket, i.e. ip, unix etc.
Currently all sockets share all fields (might change if we add other types, idk), but some fields are initialized differently by different types (e.g. here you have `pal_handle`, `can_be_read`...)
There is no common part about implementations of this interface, except that they all verify *some* fields (to check if they match what this type of the socket expects) and initialize *some* (or rather change the default values to some specific for a given type, because all fields are already initialized).
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4ACgEv6mi9xRMgYwa3:b-5djyc) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
> The other is about the return value, which we don't use

The other? This is the one one you were talking about, that it matters whether you need the return value and actually which value.
It also says: "This can result in code that is (...) harder to read." (about postfix)

> Yup, so that we have uniform style in the code :)

We can also uniformly use preincrement :)
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1500 at r10](https://reviewable.io/reviews/gramineproject/gramine/579#-N3YKyJG-458fYoaJ8Hp:-N4AECoC5r8HL0wuas7K:b-489rs3) ([raw file](https://github.com/gramineproject/gramine/blob/d2ff245bb1db80e0d557da862fdc4290a04393a1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1500)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, we can leave it for later then, but I wouldn't mind changing this single ocall to decrease the number of functions which break our conventions.
</blockquote></details>

I don't like the idea of changing just one, let's do this cleanly in another PR


<!-- Sent from Reviewable.io -->

2022-06-10 08:01 UTC, dimakuv reviewed
> Reviewed 3 of 15 files at r15, 11 of 12 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N4B_Lo47iOChYw3rhb7:b-nui1iu) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I dislike every version (including the one we have right now), so I'll let you guys decide :)
</blockquote></details>

I am with Borys on this. I find it unreadable still.
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N4BaUBU2zz4kgwb6Q8h:bnr4mua) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> What's the key by which these parts were split? 

`\brief (...) and initialize type specific fields.`
Type here means type of socket, i.e. ip, unix etc.
Currently all sockets share all fields (might change if we add other types, idk), but some fields are initialized differently by different types (e.g. here you have `pal_handle`, `can_be_read`...)
There is no common part about implementations of this interface, except that they all verify *some* fields (to check if they match what this type of the socket expects) and initialize *some* (or rather change the default values to some specific for a given type, because all fields are already initialized).
</blockquote></details>

I don't have problems with `shim_sock_ops::create`. It's a short name that means "do some creation/initialization steps specific to this socket type". Why make it longer?
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4Baw7z96b59CngRXms:bz1qfjq) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The other is about the return value, which we don't use

The other? This is the one one you were talking about, that it matters whether you need the return value and actually which value.
It also says: "This can result in code that is (...) harder to read." (about postfix)

> Yup, so that we have uniform style in the code :)

We can also uniformly use preincrement :)
</blockquote></details>

Bikeshedding...


<!-- Sent from Reviewable.io -->

2022-06-11 16:25 UTC, mkow requested changes
> Reviewed 3 of 54 files at r1, 1 of 26 files at r5, 1 of 1 files at r13, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N4DFz9_Ck2vbKMvy4gZ:b-d71o11) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am with Borys on this. I find it unreadable still.
</blockquote></details>

Ok, but Borys' stance is that all the versions are bad so he's leaving the decision up to us ;) So, does it mean that you want me to decide, or that you prefer the current version?
___
*[`LibOS/shim/include/shim_socket.h` line 81 at r14](https://reviewable.io/reviews/gramineproject/gramine/579#-N48GbdeA0qFWyCHB9vJ:-N4IY9O2CGnhoF99Xdu0:b-6fvl5u) ([raw file](https://github.com/gramineproject/gramine/blob/72b71052ac310e53fe2965e48b50bc6330eae51f/LibOS/shim/include/shim_socket.h#L81)):*
> the "backend" to decide what to do with this information.

I know, but the current documentation doesn't say that.

> > and as its user you have to know this.
>
> No, you actually don't.

I think the user actually has to know this, but rather in terms of "if the underlying socket is TCP, the the semantic is XYZ, if it's UDP, then ASDF, ...". It's just you who assumed that it works in a particular way when using this function to implement syscalls and you actually rely on its semantics to implement them.
Please at least document that this argument is completely up to the backend for interpretation, especially, considering that it's not "an address to sent to", because some backends accept it being non-NULL, but ignore the contents.
___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N4DFHEx5ArzynxQ_nPE:b33g77c) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

For `bind()` and `connect()` address is an input argument, how could they truncate it...
</blockquote></details>

It's also returned, although less explicitly: (through `sock->remote_addrlen`)
```C
    sock->remote_addrlen = MIN(addrlen, sizeof(struct sockaddr_un));
    memcpy(&sock->remote_addr, addr, sock->remote_addrlen);
```
___
*[`LibOS/shim/src/net/ip.c` line 46 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48hPnv0qpQvrjQWA-n:-N4DDsP-4TVBbtpnfoHf:bd9pv48) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't have problems with `shim_sock_ops::create`. It's a short name that means "do some creation/initialization steps specific to this socket type". Why make it longer?
</blockquote></details>

Ok, if there's nothing in common then I'm unblocking, as I don't have a good idea for the rename. But it's still quite confusing to me ¯\\_(ツ)_/¯
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4DEeN3CD_ECPwl1ZqK:brer9hb) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
:)

> We can also uniformly use preincrement :)

244 occurrences of `i++` vs 8 of `++i` on master, easier to unify to post-incrementation :P
___
*[`LibOS/shim/src/sys/shim_epoll.c` line 329 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4FAjBNCY8Ex0g8MDUN:-N4FAjBOBD-euHlcCi8j:b-712ym2) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_epoll.c#L329)):*
> ```C
>     REF_SET(new_item->ref_count, 1);
> 
>     lock(&handle->lock);
> ```

Why do we need this lock? Looking at the declaration of `struct shim_handle` it seems that `acc_mode` is not covered by the lock?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 32 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4FEESz4zV8AolfBH4b:-N4FEESz4zV8AolfBH4c:bnx4280) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L32)):*
> ```C
>  *  |     |                        |     +-------------------+               |
>  *  |     |                        V     |                                   |
>  *  |     +---------------------> CONNECTED <--------------------------------+
> ```

Why not a straight line up front `CONNECTED` to `BOUND`? Looks unnecessarily complicated right now.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 316 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I65VYEyOOt9K1JtRn:-N4I65VYEyOOt9K1JtRo:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L316)):*
> ```C
> 
>     if ((unsigned int)backlog > SHIM_SOCK_MAX_PENDING_CONNS) {
>         /* Linux kernel verifies `backlog` this way. */
> ```





_Suggestion:_
```C
/* Linux kernel caps `backlog` this way. */
```
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4I72Sp2lx3foeDSQ4z:b-7009g9) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
> ```C
> 
>     sock->state = SOCK_LISTENING;
>     sock->can_be_read = true;
> ```

How does this work? Why setting `can_be_read`, but not `can_be_written`? What's the semantics of reading from a listening socket?



_Code quote:_
```C
sock->can_be_read = true;
```
___
*[`LibOS/shim/src/sys/shim_socket.c` line 587 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4IFjdHBBP-IVzQoAdE:-N4IFjdHBBP-IVzQoAdF:battd0c) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L587)):*
> ```C
> 
> ssize_t do_sendmsg(struct shim_handle* handle, struct iovec* iov, size_t iov_len, void* addr,
>                    size_t addrlen, unsigned int flags) {
> ```

I don't like that you're mixing here the error code and the number of bytes send. Could you return the latter by a pointer argument?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 1399 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4IVibQ7Vw_FXiiSSpY:-N4IVibQ7Vw_FXiiSSpZ:bgdyb7s) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L1399)):*
> ```C
>             break;
>         case SO_LINGER:
>             value.linger.l_onoff = attr.socket.linger;
> ```

Not `attr.socket.linger ? 1 : 0`?



_Suggestion:_
```C
value.linger.l_onoff = attr.socket.linger ? 1 : 0;
```
___
*[`LibOS/shim/src/sys/shim_wrappers.c` line 79 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4FDYK22C_48FakDI9g:-N4FDYK22C_48FakDI9h:bbib32d) ([raw file](https://github.com/gramineproject/gramine/blob/5ee0fc364712dbee1bd88cd029562acf6dc99468/LibOS/shim/src/sys/shim_wrappers.c#L79)):*
> ```C
> 
> /*
>  * The problem here is that we have to guarantee atomic writev
> ```

Doesn't this problem still exist for handle types which has `.write( [...]

2022-06-13 07:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/include/shim_handle.h` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3UwQ5mBKaAFqn2qsgn:-N4Qy8wF1Vm9ja18VjxL:bkeh9z4) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/include/shim_handle.h#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but Borys' stance is that all the versions are bad so he's leaving the decision up to us ;) So, does it mean that you want me to decide, or that you prefer the current version?
</blockquote></details>

I prefer the current version.


<!-- Sent from Reviewable.io -->

2022-06-14 07:06 UTC, dimakuv reviewed
> Reviewed 6 of 6 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)



<!-- Sent from Reviewable.io -->

2022-06-14 11:06 UTC, mkow requested changes
> Reviewed 6 of 6 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N4WoQ9bCf29xUPacmH_:b-mqs5kr) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
> This is not visible to the user app.

But it _is_ visible via `getpeername`? I.e. it will return truncated address even if the user supplied larger buffer on the `getpeername` call.

>  Also that case is a bit different - here we do not return part of the address, because the user supplied output buffer is to small, in UNIX sockets case we just cap the max input address size. We do the same in this file (line 28). Should I comment all of them?

Yup, but the pattern is similar in the manner of truncating the address, but succeeding despite this. I'd add a comment to highlight that this behavior is on purpose. IMO this is weird enough that it deserves the comments.
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4WoFwh-oEwe9VEaM6L:bcx9hd7) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
> This looks bad, that we do not follow our own style guidelines...

How are we "not following" our guidelines, if this thing is just omitted there?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4Ws4OL-UCC353E4e7W:b-v6t5ip) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`can_be_read` means that read-like operation can be done on this socket - `recv` or `accept` (actually it's currently ignored in `recv`, but that's not important). Similar to semantics of readable in poll/epoll/select.

> What's the semantics of reading from a listening socket?

None, you cannot do that.
</blockquote></details>

I don't understand. Here we'll have a sock which has both `state == SOCK_LISTENING` and `can_be_read == true`. Seems like a contradiction to what you just said? What am I missing?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 587 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4IFjdHBBP-IVzQoAdE:-N4WsVb5EXL3fXl-Kk6e:b-zfmjxi) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L587)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure I can, but is there any point in it? The return value goes directly to user app in most cases and syscalls return size and error codes together...
</blockquote></details>

Maybe a comment then why are we breaking our convention here? It's not directly the syscall handler, so it's not obvious why it breaks it.


<!-- Sent from Reviewable.io -->

2022-06-14 17:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 61 of 64 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/net/ip.c` line 511 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2pJOOh-HBUpFG9U4Wn:-N4Y1G-D8z8STgl_18YI:b-uj12wb) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/LibOS/shim/src/net/ip.c#L511)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is not visible to the user app.

But it _is_ visible via `getpeername`? I.e. it will return truncated address even if the user supplied larger buffer on the `getpeername` call.

>  Also that case is a bit different - here we do not return part of the address, because the user supplied output buffer is to small, in UNIX sockets case we just cap the max input address size. We do the same in this file (line 28). Should I comment all of them?

Yup, but the pattern is similar in the manner of truncating the address, but succeeding despite this. I'd add a comment to highlight that this behavior is on purpose. IMO this is weird enough that it deserves the comments.
</blockquote></details>

Idk, it's common I believe, to return the real address and truncate (if user provided buffer is too small), see `snprintf` for example.
Added a comment to all places I remembered.
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4Y-yIt-xKbp0E0FmjO:bwnxzme) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This looks bad, that we do not follow our own style guidelines...

How are we "not following" our guidelines, if this thing is just omitted there?
</blockquote></details>

Don't we defer to google guidelines in cases not explicitly mentioned in our docs?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4YBGAjB-8KhO7yc2mt:b-vydhoi) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
> which has both state == SOCK_LISTENING and can_be_read == true

Which means `accept` on it is valid operation. You can call `shutdown` on it and then `accept` won't work.

> What am I missing?

Most likely that there is a small cheating done w.r.t. verification of socket state in `send` and `recv`. There is basically none. This is due to:
A) We cannot hold `sock->lock` for the whole read/write operation. If we took it, checked the state, released and only then issued PAL read/write, then that check was quite useless - concurrent operation could have changed it anyway.
B) There is not much to check - socket can be almost in any state (e.g. udp can be new, bound or connected)
___
*[`LibOS/shim/src/sys/shim_socket.c` line 587 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4IFjdHBBP-IVzQoAdE:-N4YFBLv0hiqqqPwGWQi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L587)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe a comment then why are we breaking our convention here? It's not directly the syscall handler, so it's not obvious why it breaks it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 21:10 UTC, mkow requested changes
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4YwtWl8Dw9aj7mUp73:bcpeaag) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we defer to google guidelines in cases not explicitly mentioned in our docs?
</blockquote></details>

Partially, because some of them don't match C world nicely. I'd say we rather follow their high-level guidances (like "no cutting letters from words to abbreviate them if that's not a common abbreviation") than low-level formatting rules.
___
*[`LibOS/shim/src/net/unix.c` line 25 at r20](https://reviewable.io/reviews/gramineproject/gramine/579#-N4Z-F2x2YpNceR3YR5N:-N4Z-F2x2YpNceR3YR5O:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/a4c914ae077dffb45851d09bfea430c04aeace67/LibOS/shim/src/net/unix.c#L25)):*
> ```C
> 
> /*!
>  * \brief Verify UNIX socket address and convert it to an unique socket name
> ```





_Suggestion:_
```C
a unique socket name.
```
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4Z0l_NCq91pPk78PI8:b3werbj) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
> Which means `accept` on it is valid operation. You can call `shutdown` on it and then `accept` won't work.

Ok, I missed that it's `accept` _OR_ `recv`, not _AND_. Isn't `can_be_read` misleading then? I mean, in a year or two we'll probably think that `can_be_read == true` means that you can call `read`/`recv` on it? Maybe `can_be_read_or_accept` would be better?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 478 at r20](https://reviewable.io/reviews/gramineproject/gramine/579#-N4Z1u-AEsgqPZLcqshU:-N4Z1u-AEsgqPZLcqshV:bu0htkd) ([raw file](https://github.com/gramineproject/gramine/blob/a4c914ae077dffb45851d09bfea430c04aeace67/LibOS/shim/src/sys/shim_socket.c#L478)):*
> ```C
> 
>     /* We need to take `recv_lock` just in case we free `peek` buffer in `disconnect` case.
>      * This should hurt though - nothing should be calling `recv` concurrently anyway. */
> ```

Missing "not"?



_Code quote:_
```C
This should hurt though
```


<!-- Sent from Reviewable.io -->

2022-06-15 00:24 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4ZVO8D7CLQoO5RZVzN:b-701d8a) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Partially, because some of them don't match C world nicely. I'd say we rather follow their high-level guidances (like "no cutting letters from words to abbreviate them if that's not a common abbreviation") than low-level formatting rules.
</blockquote></details>

That sounds like a rather arbitrary interpretation
___
*[`LibOS/shim/src/net/unix.c` line 25 at r20](https://reviewable.io/reviews/gramineproject/gramine/579#-N4Z-F2x2YpNceR3YR5N:-N4Z_MmD4eBX4pECCIUH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a4c914ae077dffb45851d09bfea430c04aeace67/LibOS/shim/src/net/unix.c#L25)):*
> ```C
> 
> /*!
>  * \brief Verify UNIX socket address and convert it to an unique socket name
> ```

Done.
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4Zb3Cy2Z75jw0BsPTo:b-y0semx) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Which means `accept` on it is valid operation. You can call `shutdown` on it and then `accept` won't work.

Ok, I missed that it's `accept` _OR_ `recv`, not _AND_. Isn't `can_be_read` misleading then? I mean, in a year or two we'll probably think that `can_be_read == true` means that you can call `read`/`recv` on it? Maybe `can_be_read_or_accept` would be better?
</blockquote></details>

The first version was named `read_shutdown` to indicate that it's mostly modified by `shutdown`, but it's also used in some other cases (e.g. not connected TCP socket), so the name was changed.
You can think of `accept` as a read on a listening socket :) Well, that's what it is, actually. I dont like `can_be_read_or_accepted`, it gives the impression that the socket can be both read and accepted on
___
*[`LibOS/shim/src/sys/shim_socket.c` line 478 at r20](https://reviewable.io/reviews/gramineproject/gramine/579#-N4Z1u-AEsgqPZLcqshU:-N4Zj0af5IRDzs0CWzdB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a4c914ae077dffb45851d09bfea430c04aeace67/LibOS/shim/src/sys/shim_socket.c#L478)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Missing "not"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 06:22 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 61 of 64 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`LibOS/shim/src/fs/socket/fs.c` line 107 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V47UrBcArJqEHspra:-N4a-QPL0C7LaohXal-E:b-fmbfug) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/fs/socket/fs.c#L107)):*
> return pal_to_unix_errno(ret);
Sorry.
I'm suggesting something like:
```
    ret = 0;
    if (attr.nonblocking != nonblocking) {
        attr.nonblocking = nonblocking;
        ret = DkStreamAttributesSetByHandle(pal_handle, &attr);
    }
    return pal_to_unix_errno(ret);;
```

The pal_to_unix_errno(0) return a 0.


<!-- Sent from Reviewable.io -->

2022-06-15 12:20 UTC, mythi commented
Some end-user feedback: I gave this branch a try with a static Go binary that seems to fail with `net.Listen("unix", "/tmp/foo.sock")`:

```
[P1:T1:enclave-cc.bin] trace: ---- shim_socket(UNIX, SOCK_NONBLOCK|SOCK_CLOEXEC|STREAM, 0) = 0x3                                                                                                                                                                                                           [P1:T1:enclave-cc.bin] trace: ---- shim_openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|0x80000, 0000) = -2
[P1:T1:enclave-cc.bin] trace: ---- shim_setsockopt(3, 1, 2, 0xc0002d7af4, 4) = -22
[P1:T1:enclave-cc.bin] trace: ---- shim_close(3) = 0x0
[P1:T1:enclave-cc.bin] trace: ---- shim_write(1, 0xc000214300, 0x3f) ...
error: listen unix /tmp/foo.sock: setsockopt: invalid argument
```

2022-06-15 13:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 61 of 64 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4bZ2Cz9o6FuybIbZoy:bhxf3an) (no related file):*
@mythi From the log you've pasted seems that the code is setting `SO_REUSEADDR` on a UNIX socket - this is meaningless, that option is completely ignored there. Could you modify the code not to set it?
There is a slight discrepancy between Gramine and Linux - we fail, Linux ignores it. 

___
___
*[`LibOS/shim/src/fs/socket/fs.c` line 107 at r8](https://reviewable.io/reviews/gramineproject/gramine/579#-N3V47UrBcArJqEHspra:-N4bXw6n1gI5dSzjJaIY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2da2b3843ff80933d4c1b624f161b953a9a51781/LibOS/shim/src/fs/socket/fs.c#L107)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> return pal_to_unix_errno(ret);
Sorry.
I'm suggesting something like:
```
    ret = 0;
    if (attr.nonblocking != nonblocking) {
        attr.nonblocking = nonblocking;
        ret = DkStreamAttributesSetByHandle(pal_handle, &attr);
    }
    return pal_to_unix_errno(ret);;
```

The pal_to_unix_errno(0) return a 0.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 14:41 UTC, dimakuv reviewed
> Reviewed 1 of 3 files at r20, 3 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @mythi, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4bmM0v4pcB1V_4y8Z-:b-bxv1yj) (no related file):*
> There is a slight discrepancy between Gramine and Linux - we fail, Linux ignores it.

Could you remind why can't we follow Linux for this? Is it because we have some generic logic in Gramine, and we'll need to "circumvent" this logic to support this weird case?

___
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4bnNin4KFBDAqTT51i:b-x07cvd) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The first version was named `read_shutdown` to indicate that it's mostly modified by `shutdown`, but it's also used in some other cases (e.g. not connected TCP socket), so the name was changed.
You can think of `accept` as a read on a listening socket :) Well, that's what it is, actually. I dont like `can_be_read_or_accepted`, it gives the impression that the socket can be both read and accepted on
</blockquote></details>

I'm with Borys on this, `read` is how people refer to `accept()` on a listening socket. Think of `poll/select` -- you can specify the `read` event on the listening socket. So I definitely prefer to keep the current short name `can_be_read`.


<!-- Sent from Reviewable.io -->

2022-06-15 15:10 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4btPf80n0m0wjhUOMe:btq29c) (no related file):*
> Could you modify the code not to set it?

It's possible but not very straightforward. I will test if that helps anyway. But I think it's worth pointing out that this may not be something everybody could do...

___


<!-- Sent from Reviewable.io -->

2022-06-15 15:45 UTC, mkow requested changes
> Reviewed 3 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4bwj4YBavnRc1WXb9E:bn6mm24) (no related file):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

> Could you modify the code not to set it?

It's possible but not very straightforward. I will test if that helps anyway. But I think it's worth pointing out that this may not be something everybody could do...
</blockquote></details>

Yeah, we should ignore it if Linux does.
But I think Borys point was more like: "this looks like a bug in your app", just poorly worded ;) But I may be wrong.

___
___
*[`LibOS/shim/src/net/ip.c` line 432 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48neOgBRyAjUfMYR-M:-N4c0Pth-6Go6joOnam3:b-ivkpm) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/ip.c#L432)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That sounds like a rather arbitrary interpretation
</blockquote></details>

Mayhaps ¯\\_(ツ)_/¯
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4c0cNO9ZCzXhIUUIdC:b-jks8kr) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
> `read` is how people refer to `accept()` on a listening socket

Umm, in an object which has a `recv` method I definitely interpret `can_be_read` as "can I call .recv() on this". But I won't block on this if you both prefer the current version. Just saying that this was super confusing for me when reviewing this PR.


<!-- Sent from Reviewable.io -->

2022-06-15 23:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 60 of 64 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4crVDfAlljk4jNjlKa:b-jev5t6) (no related file):*
>  But I think Borys point was more like: "this looks like a bug in your app", just poorly worded ;) But I may be wrong.

Well, not sure if a bug, but a useless thing to do.

@mythi So this is just go net package doing this - nothing you can change

> Could you remind why can't we follow Linux for this? 

@dimakuv we can, just not sure how easy it will be with the current design (hopefully easy) - I kind of expected `SOL_SOCKET` options to be "backend" (socket type) agnostic, but well, they arent.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4dTFZ64TGZ__a3b5Yf:-N4dTFZ64TGZ__a3b5Yg:b-x9vovb) (no related file):*
TODO (add to list): create a private structure in `net/ip.c` caching socket options similar to reuseaddr in generic socket handle. Maybe also add `void* private` to generic socket handle for storing this info.

___
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4csJP9EPrEeB08zgQP:b-gqlc7t) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `read` is how people refer to `accept()` on a listening socket

Umm, in an object which has a `recv` method I definitely interpret `can_be_read` as "can I call .recv() on this". But I won't block on this if you both prefer the current version. Just saying that this was super confusing for me when reviewing this PR.
</blockquote></details>

I just don't like `can_be_read_or_accepted`, to me it's more confusing than explanatory.
I'll try to add some comments in the header, maybe that will help.


<!-- Sent from Reviewable.io -->

2022-06-15 23:09 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 60 of 64 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4dc4b42e46_0xY2rpw:b-jkf9ml) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

>  But I think Borys point was more like: "this looks like a bug in your app", just poorly worded ;) But I may be wrong.

Well, not sure if a bug, but a useless thing to do.

@mythi So this is just go net package doing this - nothing you can change

> Could you remind why can't we follow Linux for this? 

@dimakuv we can, just not sure how easy it will be with the current design (hopefully easy) - I kind of expected `SOL_SOCKET` options to be "backend" (socket type) agnostic, but well, they arent.
</blockquote></details>

Ok, added support fro this. @mythi could you check if it works for you?

___


<!-- Sent from Reviewable.io -->

2022-06-16 03:08 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 60 of 64 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4eQF9U46lvyHr2hyV3:b-oucgmv) (no related file):*
> @mythi So this is just go net package doing this - nothing you can change

It is possible to specify a custom "ListenConfig" and I was going to give it a try (just to confirm it works). Perhaps my code/use-case is special (and the ListenConfig approach would be preferred) since no-one has not seen it before. Anyway, I can confirm your latest commit makes this to work too (thanks!).

___


<!-- Sent from Reviewable.io -->

2022-06-16 09:54 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`LibOS/shim/src/net/ip.c` line 406 at r23](https://reviewable.io/reviews/gramineproject/gramine/579#-N4fubAH5sJ4TJk5_xfB:-N4fubAH5sJ4TJk5_xfC:bqn3xhu) ([raw file](https://github.com/gramineproject/gramine/blob/1bbccde4eb881f5f927685159519d0f9154df5d4/LibOS/shim/src/net/ip.c#L406)):*
> ```C
> 
>     switch (level) {
>         case IPPROTO_IP:
> ```

It's a bit weird that you have this assymetry now in `set` and `get` functions (former has `SOL_SOCKET` handling, latter doesn't). But I understand that we don't need any special handling for `get`s -- we already cached the value in `sock.reuseaddr` so we can do it in the generic function in `shim_socket.c`.

Anyway, I don't see how to make it less confusing (like adding a comment). I think it is understandable from reading the code.
___
*[`LibOS/shim/src/net/unix.c` line 311 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48tKnE5h6QJyuRCTtX:-N4fvp6yBlgWvsKSHtll:b8uy0t5) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/unix.c#L311)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

So what is the conclusion on this?
___
*[`LibOS/shim/src/net/unix.c` line 288 at r23](https://reviewable.io/reviews/gramineproject/gramine/579#-N4fvEaG4ofOqAOe1m1f:-N4fvEaH2gA3tebOZ4HY:b-cmdjov) ([raw file](https://github.com/gramineproject/gramine/blob/1bbccde4eb881f5f927685159519d0f9154df5d4/LibOS/shim/src/net/unix.c#L288)):*
> ```C
>                 return -EINVAL;
>             }
>             memcpy(&val, optval, sizeof(val));
> ```

Can we have uniformity with the func in `ip.c`? That one has a nice structure, with
```
    /* All currently supported options use `int`. */
    ...
```

Please reformat as there, with `break` and setting `reuseaddr = !!val` right before `return 0`.


<!-- Sent from Reviewable.io -->

2022-06-16 12:23 UTC, mkow reviewed
> Reviewed 4 of 4 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @oshogbo)

___
*[`LibOS/shim/src/net/unix.c` line 311 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48tKnE5h6QJyuRCTtX:-N4gSXBi5xCJPWBCllbD:b-syiah8) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/unix.c#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So what is the conclusion on this?
</blockquote></details>

Borys changed all other places, but I think he missed this one?
___
*[`LibOS/shim/src/sys/shim_socket.c` line 351 at r18](https://reviewable.io/reviews/gramineproject/gramine/579#-N4I72Sp2lx3foeDSQ4y:-N4gSiPU063OOWLxlwNe:bths6hu) ([raw file](https://github.com/gramineproject/gramine/blob/c0782406e5a3204a82aa7b07de9d2d6627561cde/LibOS/shim/src/sys/shim_socket.c#L351)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I just don't like `can_be_read_or_accepted`, to me it's more confusing than explanatory.
I'll try to add some comments in the header, maybe that will help.
</blockquote></details>

Ok, it's a bit better now.


<!-- Sent from Reviewable.io -->

2022-06-16 15:55 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4hCurW2Rdnv5PnZ17D:bcn5pzk) (no related file):*
> Anyway, I can confirm your latest commit makes this to work too (thanks!).

one update after I continued testing: the socket I create does not show up on the host (`/tmp`). The `fs.mounts` is correct because normal directories created by the same app show up OK.

___


<!-- Sent from Reviewable.io -->

2022-06-16 16:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4hFfO09UrE2tkU5IRi:b2roakw) (no related file):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

> Anyway, I can confirm your latest commit makes this to work too (thanks!).

one update after I continued testing: the socket I create does not show up on the host (`/tmp`). The `fs.mounts` is correct because normal directories created by the same app show up OK.
</blockquote></details>

That's a known limitation of the current code, see the comment at the top of `LibOS/shim/src/net/unix.c`.
Is this something critical to your app, or were you just testing everything out?

___


<!-- Sent from Reviewable.io -->

2022-06-16 16:58 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4hO3PM8-gQQnlf7Dp6:b-gwf0qo) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's a known limitation of the current code, see the comment at the top of `LibOS/shim/src/net/unix.c`.
Is this something critical to your app, or were you just testing everything out?
</blockquote></details>

Yes, as @mkow said it's not visible on host FS. That shouldn't be a problem though - two Gramine processes can connect to it and host processes wouldn't be able to connect to it anyway (because we have a seamless encryption of UNIX sockets).

I've checked `ListenConfig` before and it only had two options (keepalive and something I dont remember), none of them allowed changing reuseaddr behavior.

___
___
*[`LibOS/shim/src/net/ip.c` line 406 at r23](https://reviewable.io/reviews/gramineproject/gramine/579#-N4fubAH5sJ4TJk5_xfB:-N4hOZ_C5LO1UIkI2F2P:bxuhwkc) ([raw file](https://github.com/gramineproject/gramine/blob/1bbccde4eb881f5f927685159519d0f9154df5d4/LibOS/shim/src/net/ip.c#L406)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's a bit weird that you have this assymetry now in `set` and `get` functions (former has `SOL_SOCKET` handling, latter doesn't). But I understand that we don't need any special handling for `get`s -- we already cached the value in `sock.reuseaddr` so we can do it in the generic function in `shim_socket.c`.

Anyway, I don't see how to make it less confusing (like adding a comment). I think it is understandable from reading the code.
</blockquote></details>

Yeah, I didn't want to duplicate the code. It might change if we ever implement the TODO from top level comment (adding a private struct holding options, different for IP and UNIX sockets).
___
*[`LibOS/shim/src/net/unix.c` line 311 at r15](https://reviewable.io/reviews/gramineproject/gramine/579#-N48tKnE5h6QJyuRCTtX:-N4hQgLB-kIdVbkK7nKY:bic0g6r) ([raw file](https://github.com/gramineproject/gramine/blob/4b7af1733eb4341271f9d177ce329d58210028b2/LibOS/shim/src/net/unix.c#L311)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Borys changed all other places, but I think he missed this one?
</blockquote></details>

Done. This time I've grepped whole repo and changed all of them (2 were not introduced by this PR, but in files that should not introduce more conflicts, so I stashed them here).
___
*[`LibOS/shim/src/net/unix.c` line 288 at r23](https://reviewable.io/reviews/gramineproject/gramine/579#-N4fvEaG4ofOqAOe1m1f:-N4hPZkb6nWuTVRHMHzR:b-r7za4b) ([raw file](https://github.com/gramineproject/gramine/blob/1bbccde4eb881f5f927685159519d0f9154df5d4/LibOS/shim/src/net/unix.c#L288)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we have uniformity with the func in `ip.c`? That one has a nice structure, with
```
    /* All currently supported options use `int`. */
    ...
```

Please reformat as there, with `break` and setting `reuseaddr = !!val` right before `return 0`.
</blockquote></details>

Done. Partially. I do not understand the part: ```and setting `reuseaddr = !!val` right before return 0.```. We have to set it inside switch, and then we either `return 0` (so no `break`) or have `break` but then setting is not right before `return`.


<!-- Sent from Reviewable.io -->

2022-06-16 21:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 60 of 66 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4iSRfM60aHsX0LXD7R:b-759tuq) (no related file):*
> my use case was to run a gRPC server that takes client commands from the host.

Not sure what exactly you are doing, but are you sure that it's secure? But I don't know your exact usecase, so maybe, who knows. Anyway, it won't work, unless you can change it to use IP (v4 or v6) sockets, like TCP or UDP, but then please make sure sending malicious commands (host can easily do that) isn't an issue for you.

> Something like this is possible but I did not go back to check it with the previous behavior anymore:

This wouldn't work, it just turns off `SO_REUSEADDR`. That option is a complete no-op on UNIX sockets and as such was not supported (before the recent changes).

___


<!-- Sent from Reviewable.io -->

2022-06-16 22:23 UTC, mkow reviewed
> Reviewed 6 of 6 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-17 05:10 UTC, mythi reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4bZ2Cz9o6FuybIbZox:-N4k1zyd2hg0DLbyfbBU:b9ipvh5) (no related file):*
> This wouldn't work, it just turns off SO_REUSEADDR. That option is a complete no-op on UNIX sockets and as such was not supported (before the recent changes).

Right, I came to the same conclusion myself. Looking at `strace` notice Go enables it first and then just allows me to disable ;-)

On my use-case, yes it's safe. I'll see what I can do with IP sockets. Thanks for all the comments!

___


<!-- Sent from Reviewable.io -->

2022-06-17 09:58 UTC, dimakuv reviewed
> Reviewed 2 of 6 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`LibOS/shim/src/net/unix.c` line 288 at r23](https://reviewable.io/reviews/gramineproject/gramine/579#-N4fvEaG4ofOqAOe1m1f:-N4l5FIk6kuTwv_if-KM:b-j7ije4) ([raw file](https://github.com/gramineproject/gramine/blob/1bbccde4eb881f5f927685159519d0f9154df5d4/LibOS/shim/src/net/unix.c#L288)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done. Partially. I do not understand the part: ```and setting `reuseaddr = !!val` right before return 0.```. We have to set it inside switch, and then we either `return 0` (so no `break`) or have `break` but then setting is not right before `return`.
</blockquote></details>

Yes, my last part of the comment was nonsense. It's good now.


<!-- Sent from Reviewable.io -->

2022-06-17 09:58 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uib_28XlYUWNI0aDj:-N4l5QBe1shSqcIaP-Gd:b-28rsev) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: add an issue with leftovers for follow up PRs (though after main review is done)
</blockquote></details>

Done (#657).

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/579#-N4dTFZ64TGZ__a3b5Yf:-N4l5Q_Y8otOsAhnFVhP:b-28rsev) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO (add to list): create a private structure in `net/ip.c` caching socket options similar to reuseaddr in generic socket handle. Maybe also add `void* private` to generic socket handle for storing this info.
</blockquote></details>

Done (#657).

___
___
*[`Pal/include/pal_internal.h` line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/579#-N1uiR_a5KwyemSY9zwM:-N4l5NAa5A8VHw1OumF0:b-28rsev) ([raw file](https://github.com/gramineproject/gramine/blob/93ab82e03c900ce2278828a9d42b8a4bcbce677f/Pal/include/pal_internal.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a reminder for you to do this.
</blockquote></details>

Done (#657).
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.h` line 56 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2ouq1i9x5cNsLVQ2rl:-N4l5OL-3NtwfFHHpJgh:b-28rsev) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/enclave_ocalls.h#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow At some point we had a vague idea of introducing a generic "batch of OCALLs" logic. But that idea went nowhere, and also this may be not possible to implement in a nice and generic way at all.

Anyway, yes, I agree that having such "batched OCALL" is not hard to review and may be beneficial for performance. Let's leave this discussion for now.
</blockquote></details>

Done (#657).
___
*[`Pal/src/host/Linux-SGX/enclave_ocalls.c` line 1137 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2p-WCLATK2ZEqRL9Ba:-N4l5I8s0dhqcXFVhb35:b-28rsev) ([raw file](https://github.com/gramineproject/gramine/blob/5d898fbb5114fdc0aca35c92bf52142734412037/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1137)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Blocking, to add this to leftovers/todo list
</blockquote></details>

Done (#657).


<!-- Sent from Reviewable.io -->

2022-06-17 11:26 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: 58 of 66 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k9Lyb0Gk_4ICHaN7b):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, art could be misunderstood, :)
</blockquote></details>

Done.
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/579#-N2k922zA6B6XNIdypk4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sockets`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-17 15:46 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/579)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-06-17 21:25 UTC, merged