[Pal,LibOS] Add checkpoint-and-restore support for sysfs
gramineproject/gramine pull request #583
Opened 2022-05-13 02:04 UTC by vijaydhanraj

## Description of the changes 
This PR adds checkpoint-and-restore support for sysfs. It addresses issue 3 listed as part of https://github.com/gramineproject/graphene/issues/2105

## How to test this PR? 
Please run PAL/LibOS regression tests.

2022-05-13 02:07 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/583#-N1v9QiH-RWqfvySPleI:-N1v9QiI-rubzFU16lSZ:b-emd839) (no related file):*
Should we add a test case for this feature?

I did do a quick check by overriding the double_fork test as below and the test case passed.
```
diff --git a/LibOS/shim/test/regression/double_fork.c b/LibOS/shim/test/regression/double_fork.c
index e248f417..1abc41a9 100644
--- a/LibOS/shim/test/regression/double_fork.c
+++ b/LibOS/shim/test/regression/double_fork.c
@@ -22,12 +22,17 @@
 #include <sys/wait.h>
 #include <unistd.h>
 
+#include "dump.h"
 #include "futex.h"
 
 static pid_t main_pid;
 
 static void do_grandchild(int fd) {
     char c = 0;
+    if (dump_path("/sys") < 0) {
+        err(1, "grandchild sysfs");
+    }
+
     if (read(fd, &c, 1) != 1 || c != 'a') {
         err(1, "grandchild read");
     }
```

___


<!-- Sent from Reviewable.io -->

2022-05-13 17:07 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 4 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/583#-N1v9QiH-RWqfvySPleI:-N1y6L5w0OCnqZSXxveZ:beqtkxb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you also check that the dumped info is correct in the child/grandchild? That it's not all zeros?
</blockquote></details>

Yes, that was my first check. I didn't cross-check each and every sysfs path but randomly checked a few paths and they were correct. 

I do see the error messages below but don't think they are related to sysfs checkpointing and restore changes.
```
[P3:T33:double_fork] error: Failed to send IPC msg to 2: -32
[P3:T33:double_fork] error: Sending IPC process-exit notification failed: -32
```


___
___
*[`LibOS/shim/src/fs/sys/fs.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wk_nj2dx3QYrn5CVP:-N1yEPFQE-5aTyDswTmC:b-av0d1y) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function is guaranteed to be called only once, so you can remove this `GET_FROM_CP_MAP`, this check, `ADD_TO_CP_MAP`, the `else` branch, and the two lines for `objp`.

See my other comment below.
</blockquote></details>

Yes removed `GET_FROM_CP_MAP` and `ADD_TO_CP_MAP` and also the `else` part but we need to keep the `objp` so that the new `caches` is properly updated. 
___
*[`LibOS/shim/src/fs/sys/fs.c` line 313 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkkpxDrZZKolRcAfq:-N1yEnVfDk7cC2tfSDnK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 340 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkllR8p_kGsSYDPsi:-N1yEopHEgb__491vYVQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 367 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkn7L7I3I-_fUgVRt:-N1yEqPW674Eva5Kfb7G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L367)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 394 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wko2N4e_3cG4WV0a6:-N1yExjM9WQNitll7kxZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L394)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 415 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wlQnE26n_VF_u9o3A:-N1yEz_nBOycI4Ixv7Le:bhz7r4y) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L415)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this assert is misleading. I would just remove it.
</blockquote></details>

I think having `assert` is good but agree the `__UNUSED` was misleading. I have removed it here and in all the other sub `CP` functions.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 421 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkooXBuyfnKtAZRfk:-N1yFJ4F2FJvsuJfYoeY:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L421)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 445 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wjhJrCP0tPJHsDk50:-N1yFLph1-9tohgBBFXt:b60r506) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L445)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please just use `g_pal_public_state->topo_info` explicitly in this function, **not** the `obj` argument. See my other comment below.
</blockquote></details>

Yes, done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 449 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wk3zw5Rs4AhR2x3aD:-N1yFUQzC9wpPwwDuHuh:b-4nf699) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L449)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need for this `off` check -- this function is guaranteed to be called only once (via `DEFINE_MIGRATE`). Just remove this and the previous line, and also remove the `else` branch.

For an example, see `BEGIN_CP_FUNC(loaded_elf_objects)` in `shim_rtld.c`
</blockquote></details>

Thanks for the pointer, done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 451 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkO5_3UlP5zyXageQ:-N1y7g9t8b10BNz4syzG:b-955yz7) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L451)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This also won't be needed when you remove the `off` check.
</blockquote></details>

Yes, correct. Removed it.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1whoEE8250IW3xzGZ2:-N1yFbgz2o4ySwInxIdx:b-826vgr) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap in 100 chars
</blockquote></details>

For me, it shows 98 chars so felt wrapping was not needed here. Can you please check again?
___
*[`LibOS/shim/src/fs/sys/fs.c` line 468 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wkSor89mQaRXHR8Hw:-N1yFnT465TSEfDbGSp_:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L468)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two lines are not needed, because we never call this function with `objp`.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N1yFx--CMHRSfuccZrh:bxcx6v1) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you also assert `!topo_info->numa_distance_matrix` ?
</blockquote></details>

Since `numa_nodes` and `numa_distance_matrix` are dependent on ` [...]

2022-05-13 17:13 UTC, vijaydhanraj commented
Oh, why is GitHub rendering reviewable comments this way? Any thoughts?

2022-05-13 19:22 UTC, boryspoplawski commented
> Oh, why is GitHub rendering reviewable comments this way? Any thoughts?

You have added tripple backtick at the end twice, which confused the syntax. I've taken the liberty of editing it (removed unnecessary ```

2022-05-13 21:14 UTC, vijaydhanraj reviewed
ah I see, thanks @boryspoplawski. Appreciate the help!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583#-:-N1zGO9wBTOL60vihOXa:b61uyf5)* status: 4 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-05-15 01:13 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 4 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/583#-N1v9QiH-RWqfvySPleI:-N24FYE67zuVFd8jFqB2:bfn6x6g) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, that was my first check. I didn't cross-check each and every sysfs path but randomly checked a few paths and they were correct. 

I do see the error messages below but don't think they are related to sysfs checkpointing and restore changes.
```
[P3:T33:double_fork] error: Failed to send IPC msg to 2: -32
[P3:T33:double_fork] error: Sending IPC process-exit notification failed: -32
```  
```

</blockquote></details>

I wouldn't add such a test - you don't even verify the output, so it's not too useful (same as the sysfs topology tests we already have).

___
___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N24GUxf3m8XDalBZ9fw:bwqtxpz) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> Since `numa_nodes` and `numa_distance_matrix` are dependent on `numa_nodes_cnt` both should be NULL if the `cnt` was zero

No, why would they _have_ to be `NULL`?


<!-- Sent from Reviewable.io -->

2022-05-15 01:50 UTC, mkow requested changes
> Reviewed 4 of 9 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 8 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`Pal/include/pal/pal.h` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wgCBADe9ge5wr1CUd:-N24NABdE-a7C-sXdlyb:b-f4de2p) ([raw file](https://github.com/gramineproject/gramine/blob/aee873466d9e63f3dad13079f9a4e679d5dae9d7/Pal/include/pal/pal.h#L131)):*
> now `g_pal_public_state` becomes a pointer to a _non-constant_ object

But that's not what `const` means in C.
```C
int x = 5;
const int* ptr = &x;
x = 10;
```


<!-- Sent from Reviewable.io -->

2022-05-15 15:23 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 8 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1whoEE8250IW3xzGZ2:-N27Iw4T3LCzjwB1y4OM:b-l9qul9) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L460)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

For me, it shows 98 chars so felt wrapping was not needed here. Can you please check again?
</blockquote></details>

+1 to Vijay, this line doesn't need rewrapping (at least in r2 of this PR).
___
*[`LibOS/shim/src/fs/sys/fs.c` line 517 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wlfC78O7CpaA4wpCV:-N27J3m27JiufE8lFHgf:bysq23) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L517)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we can, and I am open to modifying it either way.
</blockquote></details>

I'd prefer memcpy, but see my other comment.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N27IXuU6N5tN5kP7p1Y:-N27IXuU6N5tN5kP7p1Z:b6bjlxt) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L409)):*
> ```C
> END_CP_FUNC(topo_info)
> 
> BEGIN_RS_FUNC(topo_info) {
> ```

Why is this change so complicated? Can't you just send one blob with all the arrays copied inside, point the array pointers to them and the to `CP_REBASE()` on retrieval?


<!-- Sent from Reviewable.io -->

2022-05-16 09:07 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wk_nj2dx3QYrn5CVP:-N2B011C8SFTMZ9AVtcT:b1noz2k) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L286)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes removed `GET_FROM_CP_MAP` and `ADD_TO_CP_MAP` and also the `else` part but we need to keep the `objp` so that the new `caches` is properly updated. 
</blockquote></details>

Looks good. Yes, you are right, `objp` assignment is needed, I was wrong.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 460 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1whoEE8250IW3xzGZ2:-N2B1lKW-tE95ZoTcuLe:b-lh01no) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L460)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to Vijay, this line doesn't need rewrapping (at least in r2 of this PR).
</blockquote></details>

After the change, it is now 98, so it's good now.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2B6h4L5ep_TzPn-YZG:b-f4kbwq) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Since `numa_nodes` and `numa_distance_matrix` are dependent on `numa_nodes_cnt` both should be NULL if the `cnt` was zero

No, why would they _have_ to be `NULL`?
</blockquote></details>

I didn't understand Michal's point, but this code will be modified anyway, given our discussions above.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 281 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B0Eds91Wf1kD6aqGL:-N2B0Eds91Wf1kD6aqGM:bk957no) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L281)):*
> ```C
>     assert(size == sizeof(struct pal_cache_info));
> 
>     struct pal_cache_info* caches = (struct pal_cache_info*)obj;
> ```

Actually, now that I read @mkow's comment and looking at the code, I wonder -- why do we split these "copy caches/threads/cores/etc" memory copies into separate `BEGIN_CP_FUNC()` functions?

We can simply inline all this code into the main function `BEGIN_CP_FUNC(topo_info)`. Thus, we'll remove a lot of boilerplate code, and we won't have these 4-5 helper checkpoint functions.

So basically, you can simply copy this code from `BEGIN_CP_FUNC(caches)` into `BEGIN_CP_FUNC(topo_info)` and remove the now-redundant things like assignments to `objp`. You'll still need those `ADD_CP_OFFSET(caches_size)` and `ADD_CP_FUNC_ENTRY(off)` statements, but they will be all in the main function.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2B3tFbA__WQ6vdUo5K:b-iug4um) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
> ```C
>     struct pal_cache_info* new_caches = NULL;
> 
>     size_t caches_cnt = g_pal_public_state->topo_info.caches_cnt;
> ```

Actually, what happens when `caches_cnt == 0`? I think the rest of the code will break (I'm sure `ADD_CP_OFFSET` behaves incorrectly when it is given `0`). The best would be to skip all this logic then, and simply do `objp = NULL`.

Same for all other helper functions (threads, cores, ...).
___
*[`LibOS/shim/src/fs/sys/fs.c` line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N27IXuU6N5tN5kP7p1Y:-N2B4K8f8S0Sv5ypnGBD:blm1j2w) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L409)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this change so complicated? Can't you just send one blob with all the arrays copied inside, point the array pointers to them and the to `CP_REBASE()` on retrieval?
</blockquote></details>

Hm, this is also possible. I suggested (comment above) to inline all these helper checkpoint functions into the main `topo_info` function.

But Michal suggests to go even further and do something like this:
```
BEGIN_CP_FUNC(topo_info) {
    ...
    size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info) +
        topo_info->caches_cnt * sizeof(struct pal_cache_info) +
        topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info) +
        ... and so on ...);

    new_topo_info = (struct pal_topo_info*)(base + off);
    *new_topo_info = *topo_info;

    struct pal_cache_info* caches = (struct pal_cache_info*)(base + off + sizeof(struct pal_topo_info));
    memcpy(caches, topo_info->caches, topo_info->caches_cnt * sizeof(struct pal_cache_info));
    new_topo_info->caches = caches;

    ... same for threads, for cores, for NUMA, ...
}
```

To be honest, I'm not sure that this code is easier to read than what I proposed (the inlined helper functions).

On the other hand, the restore function (`BEGIN_RS_FUNC(topo_info)`) will be indeed trivial. Something like this:
```
    struct pal_topo_info* topo_info = (void*)(base + GET_CP_FUNC_ENTRY());
    CP_REBASE(topo_info->caches);
    CP_REBASE(topo_info->threads);
    ...
    memcpy(&g_pal_public_state->topo_info, topo_info, sizeof(struct pal_topo_info) +
        topo_info->caches_cnt * sizeof(struct pal_cache_info) +
        topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info) + ...);
```

(Note that if `topo_info->caches == NULL`, the `CP_REBASE` macro becomes a no-op, so everything works.)

Yeah, ok, @mkow's version is actually more concise and thus better.
___
*[`Pal/include/pal/pal.h` line 131 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wgCBADe9ge5wr1CUd:-N2B3IEl9ec49GdX36Kf:bd3a0y1) ([raw file](https://github.com/gramineproject/gramine/blob/aee873466d9e63f3dad13079f9a4e679d5dae9d7/Pal/include/pal/pal.h#L131)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> now `g_pal_public_state` becomes a pointer to a _non-constant_ object

But that's not what `const` means in C.
```C
int x = 5;
const int* ptr = &x;
x = 10;
```
</blockquote></details>

@mkow Yeah, I wasn't precise in my comment. The object can change, but it is not allowed to *change the object values through the const pointer*. Which is exactly the case in this PR (and the reason for removal of `const`).
___
*[`Pal/include/pal/pal.h` line 132 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3CRH5y-TBOT49pLY:-N2B3CRH5y-TBOT49pLZ:b-souras) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/Pal/include/pal/pal.h#L132)):*
> ```objc
> 
> /* We cannot mark this as returning a pointer to `const` object, because LibOS can
>  * change `pal_public_state.topo_info` during  checkpoint restore in the child */
> ```

Please remove double space between `during` and `checkpoint`
___
*[`Pal/src/host/Linux-SGX/db_main.c` line 577 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wek-EEchLbxVbDydz:-N2B2VX134m5kA1JBgkr:b-h9e0xh) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/Pal/src/host/Linux-SGX/db_main.c#L577)):*
<details><summary><i>Previously, dimaku [...]

2022-05-16 11:10 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-05-16 21:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 7 of 9 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/583#-N1v9QiH-RWqfvySPleI:-N2DZtygCi4rxNrAILUz:bn1ynjf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't add such a test - you don't even verify the output, so it's not too useful (same as the sysfs topology tests we already have).
</blockquote></details>

No, I wasn't going to add this diff as a test case. I just wanted to show how I validated the changes and wanted to get your thoughts if we needed to add a new test case.

___
___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2D__tGBE4F2XRTAlum:bkqvva0) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
Yes @mkow is correct both pointers need not be NULL. From the code, it looks like they will be at least `base + sizeof(struct shim_cp_entry)`. 

> Shouldn't you also assert !topo_info->numa_distance_matrix 

But we don't need an additional assert because if the count is `zero` then we fail and exit with ` assert(!topo_info->numa_nodes);` The assert in the next line won't even be executed.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 517 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wlfC78O7CpaA4wpCV:-N2Dby1B1vcqcMJPjHvj:b-dxfrec) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L517)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer memcpy, but see my other comment.
</blockquote></details>

Sure, used `memcpy`
___
*[`LibOS/shim/src/fs/sys/fs.c` line 281 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B0Eds91Wf1kD6aqGL:-N2DOKJCDqii4_NxAdFP:biznube) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L281)):*
I split it as this was more readable to me.

>  Thus, we'll remove a lot of boilerplate code, and we won't have these 4-5 helper checkpoint functions.

We will end up removing just `ADD_CP_FUNC_ENTRY(off);` and the `objp` and yes the `cp` functions. But feel inlining will just bloat one single function. I prefer to keep the function small when possible. 
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2D-0zi4t-XpC-bsMW5:b-lts84) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO the code should handle 0 counts correctly, if it doesn't then we need to fix it.
</blockquote></details>

I did do a quick check and the code does seem to work fine. If the `cnt` is zero `ADD_CP_OFFSET` adds at a minimum `sizeof(struct shim_cp_entry)`. So, we should be good here with no overwrites.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N27IXuU6N5tN5kP7p1Y:-N2DMmdX0sIgCErMJX2B:bizx1zb) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L409)):*
What is complicated? The suggested approach, at least to me, doesn't look either concise or readable as we must manually offset for each variable which can be prone to error if we change the `pal_topo_info` struct in the future. See the code below.  

```
diff --git a/LibOS/shim/src/fs/sys/fs.c b/LibOS/shim/src/fs/sys/fs.c
index 4259470c..381784fd 100644
--- a/LibOS/shim/src/fs/sys/fs.c
+++ b/LibOS/shim/src/fs/sys/fs.c
@@ -391,16 +391,69 @@ BEGIN_CP_FUNC(topo_info) {
     struct pal_topo_info* topo_info = &g_pal_public_state->topo_info;
     struct pal_topo_info* new_topo_info = NULL;
 
-    size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info));
+    size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info) +
+                               topo_info->caches_cnt * sizeof(struct pal_cache_info) +
+                               topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info) +
+                               topo_info->cores_cnt * sizeof(struct pal_cpu_core_info) +
+                               topo_info->sockets_cnt * sizeof(struct pal_socket_info) +
+                               topo_info->numa_nodes_cnt * sizeof(struct pal_numa_node_info) +
+                               topo_info->numa_nodes_cnt * topo_info->numa_nodes_cnt *
+                               sizeof(size_t));
+    //size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info));
     new_topo_info = (struct pal_topo_info*)(base + off);
     *new_topo_info = *topo_info;
 
-    DO_CP(caches, topo_info->caches, &new_topo_info->caches);
-    DO_CP(threads, topo_info->threads, &new_topo_info->threads);
-    DO_CP(cores, topo_info->cores, &new_topo_info->cores);
-    DO_CP(sockets, topo_info->sockets, &new_topo_info->sockets);
-    DO_CP(numa_nodes, topo_info->numa_nodes, &new_topo_info->numa_nodes);
-    DO_CP(numa_distances, topo_info->numa_distance_matrix, &new_topo_info->numa_distance_matrix);
+    //DO_CP(caches, topo_info->caches, &new_topo_info->caches);
+    struct pal_cache_info* caches = (struct pal_cache_info*)(base + off + sizeof(struct pal_topo_info));
+    memcpy(caches, topo_info->caches, topo_info->caches_cnt * sizeof(struct pal_cache_info));
+    new_topo_info->caches = caches;
+
+    //DO_CP(threads, topo_info->threads, &new_topo_info->threads);
+    struct pal_cpu_thread_info* threads = (struct pal_cpu_thread_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info));
+    memcpy(threads, topo_info->threads, topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info));
+    new_topo_info->threads = threads;
+
+    //DO_CP(cores, topo_info->cores, &new_topo_info->cores);
+    struct pal_cpu_core_info* cores = (struct pal_cpu_core_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info) +
+                                            sizeof(struct pal_cpu_thread_info));
+    memcpy(cores, topo_info->cores, topo_info->cores_cnt * sizeof(struct pal_cpu_core_info));
+    new_topo_info->cores = cores;
+
+    //DO_CP(sockets, topo_info->sockets, &new_topo_info->sockets);
+    struct pal_socket_info* sockets = (struct pal_socket_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info) +
+                                            sizeof(struct pal_cpu_thread_info) +
+                                            sizeof(struct pal_cpu_core_info));
+    memcpy(sockets, topo_info->sockets, topo_info->sockets_cnt * sizeof(struct pal_socket_info));
+    new_topo_info->sockets = sockets;
+
+    //DO_CP(numa_nodes, topo_info->numa_nodes, &new_topo_info->numa_nodes);
+    struct pal_numa_node_info* numa_nodes = (struct pal_numa_node_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info) +
+                                            sizeof(struct pal_cpu_thread_info) +
+                                            sizeof(struct pal_cpu_core_info) +
+            [...]

2022-05-17 06:20 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2FeQVSEx22VcAgzQyD:b-ie1kn7) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes @mkow is correct both pointers need not be NULL. From the code, it looks like they will be at least `base + sizeof(struct shim_cp_entry)`. 

> Shouldn't you also assert !topo_info->numa_distance_matrix 

But we don't need an additional assert because if the count is `zero` then we fail and exit with ` assert(!topo_info->numa_nodes);` The assert in the next line won't even be executed.
</blockquote></details>

I actually very much prefer to have NULL pointers when `cnt == 0`. My proposed code in the above comment ensures this.

So, if we use my code, we can simplify this restore (RS) function to the trivial:
```
    struct pal_topo_info* topo_info = (void*)(base + GET_CP_FUNC_ENTRY());
    CP_REBASE(topo_info->caches);
    CP_REBASE(topo_info->threads);
    ...
    memcpy(&g_pal_public_state->topo_info, topo_info, sizeof(*topo_info));
```

In other words, we can skip the checks and asserts because we are guaranteed (by the construction of checkpoint functions) that when the corresponding `cnt == 0`, then the corresponding pointer is `NULL`.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2Fb77X13rDl7UCa7N8:b-tihf6w) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I did do a quick check and the code does seem to work fine. If the `cnt` is zero `ADD_CP_OFFSET` adds at a minimum `sizeof(struct shim_cp_entry)`. So, we should be good here with no overwrites.
</blockquote></details>

Thanks for checking, but then it doesn't make much sense to have some dummy unused regions of checkpoint memory (of size `sizeof(struct shim_cp_entry)`). Why not just skip the step and return NULL when `cnt == 0`? This is much cleaner than adding some uninitialized memory blob into the checkpoint.

I suggest the refactoring like this:
```
BEGIN_CP_FUNC(caches) {
    assert(size == sizeof(struct pal_cache_info));

    size_t caches_cnt = g_pal_public_state->topo_info.caches_cnt;
    if (caches_cnt == 0) {
        *objp = NULL;
        return;
    }

    size_t caches_size = caches_cnt * sizeof(struct pal_cache_info);
    size_t off = ADD_CP_OFFSET(caches_size);
    struct pal_cache_info* new_caches = (struct pal_cache_info*)(base + off);
    memcpy(new_caches, g_pal_public_state->topo_info.caches, caches_size);

    ADD_CP_FUNC_ENTRY(off);
    *objp = (void*)new_caches;
}
END_CP_FUNC_NO_RS(caches)
```

This also has a side benefit that if `cnt` is zero, then the corresponding array is definitely NULL (in your current version, the array points to some uninitialized blob inside the checkpoint).
___
*[`LibOS/shim/src/fs/sys/fs.c` line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N27IXuU6N5tN5kP7p1Y:-N2FeGAz8CTnjpI5Hkfi:b-hf2v5) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L409)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

What is complicated? The suggested approach, at least to me, doesn't look either concise or readable as we must manually offset for each variable which can be prone to error if we change the `pal_topo_info` struct in the future. See the code below.  

```
diff --git a/LibOS/shim/src/fs/sys/fs.c b/LibOS/shim/src/fs/sys/fs.c
index 4259470c..381784fd 100644
--- a/LibOS/shim/src/fs/sys/fs.c
+++ b/LibOS/shim/src/fs/sys/fs.c
@@ -391,16 +391,69 @@ BEGIN_CP_FUNC(topo_info) {
     struct pal_topo_info* topo_info = &g_pal_public_state->topo_info;
     struct pal_topo_info* new_topo_info = NULL;
 
-    size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info));
+    size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info) +
+                               topo_info->caches_cnt * sizeof(struct pal_cache_info) +
+                               topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info) +
+                               topo_info->cores_cnt * sizeof(struct pal_cpu_core_info) +
+                               topo_info->sockets_cnt * sizeof(struct pal_socket_info) +
+                               topo_info->numa_nodes_cnt * sizeof(struct pal_numa_node_info) +
+                               topo_info->numa_nodes_cnt * topo_info->numa_nodes_cnt *
+                               sizeof(size_t));
+    //size_t off = ADD_CP_OFFSET(sizeof(struct pal_topo_info));
     new_topo_info = (struct pal_topo_info*)(base + off);
     *new_topo_info = *topo_info;
 
-    DO_CP(caches, topo_info->caches, &new_topo_info->caches);
-    DO_CP(threads, topo_info->threads, &new_topo_info->threads);
-    DO_CP(cores, topo_info->cores, &new_topo_info->cores);
-    DO_CP(sockets, topo_info->sockets, &new_topo_info->sockets);
-    DO_CP(numa_nodes, topo_info->numa_nodes, &new_topo_info->numa_nodes);
-    DO_CP(numa_distances, topo_info->numa_distance_matrix, &new_topo_info->numa_distance_matrix);
+    //DO_CP(caches, topo_info->caches, &new_topo_info->caches);
+    struct pal_cache_info* caches = (struct pal_cache_info*)(base + off + sizeof(struct pal_topo_info));
+    memcpy(caches, topo_info->caches, topo_info->caches_cnt * sizeof(struct pal_cache_info));
+    new_topo_info->caches = caches;
+
+    //DO_CP(threads, topo_info->threads, &new_topo_info->threads);
+    struct pal_cpu_thread_info* threads = (struct pal_cpu_thread_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info));
+    memcpy(threads, topo_info->threads, topo_info->threads_cnt * sizeof(struct pal_cpu_thread_info));
+    new_topo_info->threads = threads;
+
+    //DO_CP(cores, topo_info->cores, &new_topo_info->cores);
+    struct pal_cpu_core_info* cores = (struct pal_cpu_core_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info) +
+                                            sizeof(struct pal_cpu_thread_info));
+    memcpy(cores, topo_info->cores, topo_info->cores_cnt * sizeof(struct pal_cpu_core_info));
+    new_topo_info->cores = cores;
+
+    //DO_CP(sockets, topo_info->sockets, &new_topo_info->sockets);
+    struct pal_socket_info* sockets = (struct pal_socket_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                                            sizeof(struct pal_cache_info) +
+                                            sizeof(struct pal_cpu_thread_info) +
+                                            sizeof(struct pal_cpu_core_info));
+    memcpy(sockets, topo_info->sockets, topo_info->sockets_cnt * sizeof(struct pal_socket_info));
+    new_topo_info->sockets = sockets;
+
+    //DO_CP(numa_nodes, topo_info->numa_nodes, &new_topo_info->numa_nodes);
+    struct pal_numa_node_info* numa_nodes = (struct pal_numa_node_info*)(base + off +
+                                            sizeof(struct pal_topo_info) +
+                         [...]

2022-05-17 15:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2HXOuc6ljwzpvbNHPz:bomv294) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I actually very much prefer to have NULL pointers when `cnt == 0`. My proposed code in the above comment ensures this.

So, if we use my code, we can simplify this restore (RS) function to the trivial:
```
    struct pal_topo_info* topo_info = (void*)(base + GET_CP_FUNC_ENTRY());
    CP_REBASE(topo_info->caches);
    CP_REBASE(topo_info->threads);
    ...
    memcpy(&g_pal_public_state->topo_info, topo_info, sizeof(*topo_info));
```

In other words, we can skip the checks and asserts because we are guaranteed (by the construction of checkpoint functions) that when the corresponding `cnt == 0`, then the corresponding pointer is `NULL`.
</blockquote></details>

From the code, we can see that `CP_REBASE` doesn't fail if a checkpoint pointer is NULL. So, if `cnt` is zero we will end up with empty values. So, it is better to have a `cnt == 0` check here and fail immediately.

Below is the output from such a scenario with `double_fork` test trying to print `sysfs` data.
```
/sys: directory
/sys/devices: directory
/sys/devices/system: directory
/sys/devices/system/cpu: directory
/sys/devices/system/cpu/online: file
[/sys/devices/system/cpu/online] 
/sys/devices/system/cpu/possible: file
[/sys/devices/system/cpu/possible] 
/sys/devices/system/node: directory
/sys/devices/system/node/online: file
[/sys/devices/system/node/online] 
/sys/devices/system/node/possible: file
[/sys/devices/system/node/possible] TEST OK
```
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2HWTAu9hx67lDXBbbn:b-eij5r9) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for checking, but then it doesn't make much sense to have some dummy unused regions of checkpoint memory (of size `sizeof(struct shim_cp_entry)`). Why not just skip the step and return NULL when `cnt == 0`? This is much cleaner than adding some uninitialized memory blob into the checkpoint.

I suggest the refactoring like this:
```
BEGIN_CP_FUNC(caches) {
    assert(size == sizeof(struct pal_cache_info));

    size_t caches_cnt = g_pal_public_state->topo_info.caches_cnt;
    if (caches_cnt == 0) {
        *objp = NULL;
        return;
    }

    size_t caches_size = caches_cnt * sizeof(struct pal_cache_info);
    size_t off = ADD_CP_OFFSET(caches_size);
    struct pal_cache_info* new_caches = (struct pal_cache_info*)(base + off);
    memcpy(new_caches, g_pal_public_state->topo_info.caches, caches_size);

    ADD_CP_FUNC_ENTRY(off);
    *objp = (void*)new_caches;
}
END_CP_FUNC_NO_RS(caches)
```

This also has a side benefit that if `cnt` is zero, then the corresponding array is definitely NULL (in your current version, the array points to some uninitialized blob inside the checkpoint).
</blockquote></details>

Yes, we now set the pointer to NULL if `cnt` is zero. But the code is inlined now and removed this function.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 409 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N27IXuU6N5tN5kP7p1Y:-N2HglNL7S8kKmSg7XMW:b-wuboxt) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L409)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> What is complicated? The suggested approach, at least to me, doesn't look either concise or readable as we must manually offset for each variable which can be prone to error if we change the pal_topo_info struct in the future. See the code below.

> The inline approach is better, but we will simply bloat a single function over a few functions. I prefer the current implementation over both suggestions but if you insist, I will change to using this blob approach.

Please take a look at https://github.com/boryspoplawski/gramine/commit/34cf2f6d0fc6481bc3a07d4a2a4db09195de91a8#diff-9e25c4e2e0ea819880c207dd80fa7acbeec1f5d1d822502427abd1c2b70a71e4
It's one function approach, IMO quite readable and much, much shorter.
</blockquote></details>

Thanks @boryspoplawski. Yes, I have used the inline approach now. There are 2 changes, one is we need to copy `*_cnt` variables. And second is I have kept the check for `*_cnt > 0`. Please see my other comment on this.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 281 at r3](https://reviewable.io/reviews/gramineproject/gramine/583#-N2FdDWP1PG6SofYqCR4:-N2HTz7w6jn8ycU7DHvh:b28ne93) ([raw file](https://github.com/gramineproject/gramine/blob/5b5d0936e2cda47c0e41a133836dbb94d7272bd0/LibOS/shim/src/fs/sys/fs.c#L281)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here I don't like that you take `caches` from the input argument `obj`, but then you take `caches_cnt` from the global variable `g_pal_public_state`. I know that both end up using the same object (the global `g_pal_public_state`), but this is not easy to see for future reader.

I suggest to explicitly use the global variable and mark `obj` as unused. See my proposed code in the comment below.
</blockquote></details>

Inlined the code and removed this function.


<!-- Sent from Reviewable.io -->

2022-05-17 16:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2HqchDAwt8kEglB6iz:b-jqcv58) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is much cleaner than adding some uninitialized memory blob into the checkpoint.

What uninitialized blob? If `count` is 0 then why anything would fail? I completely fail to see why we should have a special handling for 0 sizes anywhere.
</blockquote></details>

Is `count == 0` a valid case for any of the topology objects? 


<!-- Sent from Reviewable.io -->

2022-05-17 18:33 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2IHYySCFP8GWASMJmG:b-mfhvae) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

From the code, we can see that `CP_REBASE` doesn't fail if a checkpoint pointer is NULL. So, if `cnt` is zero we will end up with empty values. So, it is better to have a `cnt == 0` check here and fail immediately.

Below is the output from such a scenario with `double_fork` test trying to print `sysfs` data.
```
/sys: directory
/sys/devices: directory
/sys/devices/system: directory
/sys/devices/system/cpu: directory
/sys/devices/system/cpu/online: file
[/sys/devices/system/cpu/online] 
/sys/devices/system/cpu/possible: file
[/sys/devices/system/cpu/possible] 
/sys/devices/system/node: directory
/sys/devices/system/node/online: file
[/sys/devices/system/node/online] 
/sys/devices/system/node/possible: file
[/sys/devices/system/node/possible] TEST OK
```
</blockquote></details>

Please remove all these checks, there is no point in having them. `CP_REBASE` works on `NULL` correctly.


<!-- Sent from Reviewable.io -->

2022-05-17 18:46 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2IJkgk5RkzyPa6XC_h:b-5ebbbc) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove all these checks, there is no point in having them. `CP_REBASE` works on `NULL` correctly.
</blockquote></details>

Sorry if I wasn't clear earlier. I am not saying the `count == 0` can cause an issue with `CP_REBASE` and yes it works fine with `NULL`. But `count == 0` is invalid for any of the topology objects and our topo info could be empty as shown in the earlier comment. The check is to catch this case and fail right away.


<!-- Sent from Reviewable.io -->

2022-05-17 18:54 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2IMY1Z75XyH7-lyDz4:b-ang6y5) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry if I wasn't clear earlier. I am not saying the `count == 0` can cause an issue with `CP_REBASE` and yes it works fine with `NULL`. But `count == 0` is invalid for any of the topology objects and our topo info could be empty as shown in the earlier comment. The check is to catch this case and fail right away.
</blockquote></details>

1. You don't fail anywhere, you merely added an `assert`.
2. If `count == 0` is invalid, then how can it happen here? There is no such flow in the code, it's impossible.


<!-- Sent from Reviewable.io -->

2022-05-17 19:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2IOH6N0BclMsViKHCF:b-6oamd8) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> 1. You don't fail anywhere, you merely added an assert

Yes correct we don't fail in a release build but in debug build it helps.

> 2. If count == 0 is invalid, then how can it happen here? There is no such flow in the code, it's impossible.

If there was a bug in the checkpointing and restoring code, the count could be zero.
But if you think this is redundant and count will always be greater than `zero`, then shall we also remove the `*_cnt` check in the checkpointing flow as well?
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2IPyg-6WGWT5Be8fKy:btezais) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Is `count == 0` a valid case for any of the topology objects? 
</blockquote></details>

Shall we remove these `*_cnt` checks as well?


<!-- Sent from Reviewable.io -->

2022-05-17 19:37 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2IVs2UBKYCk2ynvj68:bpnbgm4) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> Yes correct we don't fail in a release build but in debug build it helps.

Helps in what way?

> If there was a bug in the checkpointing and restoring code, the count could be zero.

And the pointer would be not `NULL`? Then these asserts will pass.

>  But if you think this is redundant and count will always be greater than zero, then shall we also remove the *_cnt check in the checkpointing flow as well?

Just assume that `count` can be `0` in a legitimate case, everything will be simpler. I see no point in special casing here. In the checkpointing flow above it's different, because it doesn't create the metadata, but if `ADD_CP_OFFSET` works well with `0` then yes, we can remove them.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2IVJF9DZdC8CiW4QU1:bbzo3lt) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Shall we remove these `*_cnt` checks as well?
</blockquote></details>

Not sure if `ADD_CP_OFFSET` works well with `0` and even if it does, this check gets rid of the unnecessary metadata in the checkpointing blob.


<!-- Sent from Reviewable.io -->

2022-05-17 22:04 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2J1-3nDLrhgPUr43Q2:br5bc1x) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> No, if we maintain the code as it is now when count == 0 the corresponding pointer will be NULL as we don't add it to the checkpoint and the assert will fail.

But you explicitly said this is a case of a bug when `count` is changed to `0`.

> Not sure what will be simpler. But if count == 0 is a legitimate case and say for example threads_cnt is zero, then /proc/cpuinfo will show no entries. These cannot be empty as there should be at least core 0 online and we should see its information /proc entry. Also, many other things like set/get affinity and /sys/ will break too.

We don't care for these here. The code will be simpler / less complicated, because it will contain less ifs and less lines.

> My suggestion is if we conclude count == 0 is a legitimate case, then let us keep the checks and assert. 

What? If it's legitimate case, then your code breaks it, because it asserts that `count == 0, pointer == NULL` is invalid.


<!-- Sent from Reviewable.io -->

2022-05-17 23:07 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2JFpR_-4GBusCtX3zO:b-1ne5p2) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> No, if we maintain the code as it is now when count == 0 the corresponding pointer will be NULL as we don't add it to the checkpoint and the assert will fail.

But you explicitly said this is a case of a bug when `count` is changed to `0`.

> Not sure what will be simpler. But if count == 0 is a legitimate case and say for example threads_cnt is zero, then /proc/cpuinfo will show no entries. These cannot be empty as there should be at least core 0 online and we should see its information /proc entry. Also, many other things like set/get affinity and /sys/ will break too.

We don't care for these here. The code will be simpler / less complicated, because it will contain less ifs and less lines.

> My suggestion is if we conclude count == 0 is a legitimate case, then let us keep the checks and assert. 

What? If it's legitimate case, then your code breaks it, because it asserts that `count == 0, pointer == NULL` is invalid.
</blockquote></details>

@vijaydhanraj: Think why you don't check here that `numa_distance_matrix` is reciprocal, that all the pointers are properly aligned, or that `topo_info->caches_cnt * sizeof(*topo_info->caches)` doesn't overflow, and 50 other technically valid checks which you could also do here.
With your logic adding all of them here would be a good idea, "to catch this logically impossible condition at least in debug mode".
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2JCGEuEZxZwGYm6wEb:bcbtkt3) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
> Is `count == 0` a valid case for any of the topology objects?

Then why don't you check here that `numa_distance_matrix` is reciprocal? It's also an invalid case. Or that all the pointers are properly aligned? Or that `topo_info->caches_cnt * sizeof(*topo_info->caches)` doesn't overflow?
Answering this question will help you understand why checking for `count == 0` makes no sense here.

> Not sure if `ADD_CP_OFFSET` works well with `0` and even if it does, this check gets rid of the unnecessary metadata in the checkpointing blob.

It should work, if not we should fix it because it may cause troubles in other places. Ad additional data: it's a rather negligible gain, I prefer less IFs in the code.


<!-- Sent from Reviewable.io -->

2022-05-17 23:53 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2JKmGMAHdYh5-qObya:b7ejbfs) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> But you explicitly said this is a case of a bug when count is changed to 0.

I think there is some confusion in the way I described it. What I meant is if `count==0`, then the `assert` will be triggered as pointer will be `NULL`

> What? If it's legitimate case, then your code breaks it, because it asserts that count == 0, pointer == NULL is invalid

Sorry for the confusion. By "legitimate" I meant that there can be a possibility of "count" being zero. Basically, we are not saying `count == 0` is impossible and will never be true. In that case, we can have the check/assert. 

@mkow, I didn't add this check from the perspective of sanitization/validation. I added the check for `count` from the perspective of checkpointing and restoring. If the count is zero, then everything will succeed but the user can end up with incorrect/empty entries. I wanted to catch this case.

But if `count == 0` can never be true then we can remove these checks/asserts.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2JPxorC9pOeHGvYgvZ:b1hz7as) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
> Answering this question will help you understand why checking for count == 0 makes no sense here.

Please see my other comment.

> It should work, if not we should fix it because it may cause troubles in other places. Ad additional data: it's a rather negligible gain, I prefer less IFs in the code.

@mkow looks like you are saying `count == 0` can never be true. And you suggest removing the `if` checks from both checkpointing/resorting flows. Can you please confirm?


<!-- Sent from Reviewable.io -->

2022-05-18 00:02 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2JS_bq4A7PAtMWTDiS:b-90nbxr) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> @mkow, I didn't add this check from the perspective of sanitization/validation. I added the check for `count` from the perspective of checkpointing and restoring. If the count is zero, then everything will succeed but the user can end up with incorrect/empty entries. I wanted to catch this case.

In what sense they are "incorrect"? How this "incorrect" is different from e.g. non-reciprocality of `numa_distance_matrix` or other cases I mentioned?
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2JS4Qq2MvjxVomc8BV:b-nasvds) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
> @mkow looks like you are saying count == 0 can never be true. And you suggest removing the if checks from both checkpointing/resorting flows. Can you please confirm?

It can't be, but that's not my point. My point is that these checks make no sense and you can just remove them. This code should not rely/assume such things about the data, because why would it? It only makes it more complicated and mixes different abstraction layers.


<!-- Sent from Reviewable.io -->

2022-05-18 02:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2JpzYl6-NnaAa23K5w:b-46ywk) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> @mkow, I didn't add this check from the perspective of sanitization/validation. I added the check for `count` from the perspective of checkpointing and restoring. If the count is zero, then everything will succeed but the user can end up with incorrect/empty entries. I wanted to catch this case.

In what sense they are "incorrect"? How this "incorrect" is different from e.g. non-reciprocality of `numa_distance_matrix` or other cases I mentioned?
</blockquote></details>

Take `threads_cnt` for example, we fail with `-PAL_ERROR_INVAL` if it was `zero`. But in this case, if there was an issue with checkpointing/restore logic and `threads_cnt` was `zero` we continue without any failure. 
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2JmcJI6iLHf8RVjZ_G:b-e1otaz) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> @mkow looks like you are saying count == 0 can never be true. And you suggest removing the if checks from both checkpointing/resorting flows. Can you please confirm?

It can't be, but that's not my point. My point is that these checks make no sense and you can just remove them. This code should not rely/assume such things about the data, because why would it? It only makes it more complicated and mixes different abstraction layers.
</blockquote></details>

OK, I have removed the checks and asserts from both the checkpointing and restoring functions.


<!-- Sent from Reviewable.io -->

2022-05-18 06:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2KoIli52Efqayythhz:b5lrxg3) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Take `threads_cnt` for example, we fail with `-PAL_ERROR_INVAL` if it was `zero`. But in this case, if there was an issue with checkpointing/restore logic and `threads_cnt` was `zero` we continue without any failure. 
</blockquote></details>

I can't follow this discussion any more. I think the discussion moved to a general "at which point there are too many `assert` statements in the code". I think it's a matter of taste, but I definitely don't want to drag this PR over this issue.

But looking at the current code, the logic raises questions for me.

- During checkpoint we do this:
```
    new_topo_info->caches = (void*)(base + ADD_CP_OFFSET(caches_size));
```

If `new_topo_info->caches_cnt` is zero, then `new_topo_info->caches` is a pointer to some garbage.

- During restore we do this:
```
    CP_REBASE(topo_info->caches);
```

So the `topo_info->caches` continues to be a pointer to some garbage.

I guess what @mkow is saying is: "Who cares what the value of `caches` pointer is when the `caches_cnt == 0`. All Gramine code is written in such a way as to ignore the `caches` pointer when the corresponding `caches_cnt` is zero. We can have garbage in that pointer, and we don't care."

If the above statement is fine with everyone, let's agree on this and stop the discussion.

I am fine with the above statement.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2Kl2va2QYrNjBb0dgQ:bdpsw0e) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, I have removed the checks and asserts from both the checkpointing and restoring functions.
</blockquote></details>

I guess we resolved this particular thread and decided to remove checks on `count == 0`.

But I would like to point out to @mkow that `ADD_CP_OFFSET` doesn't work correctly with `0` size, see https://github.com/gramineproject/gramine/blob/e6b697521a35ae24809d79237ad814ca497b3470/LibOS/shim/include/shim_checkpoint.h#L154

When I say "doesn't work correctly", I mean that there will be a dummy object created inside the checkpoint blob, and this dummy object will never be used (so the "incorrectness" is that we lose memory on smth that is never used).

Of course, as @mkow mentions, we should actually fix this macro. But this is a story for another PR (actually, a huge change, because you can't just change one macro in the checkpointing subsystem, it needs to be completely rewritten).


<!-- Sent from Reviewable.io -->

2022-05-18 10:33 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2LXGblDXixjQm_gaBA:bhgqjlu) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> we fail with `-PAL_ERROR_INVAL` if it was `zero`

Where?

> I think it's a matter of taste

No, here it's a matter of logic and consistency in the codebase. Choosing a random subset of topology properties we want and checking them here makes no sense. Either we do full sanitization here (but what for?) or we don't do anything.

> So the `topo_info->caches` continues to be a pointer to some garbage.

Not really, it's a pointer to 0 bytes of that garbage.

> All Gramine code is written in such a way as to ignore the `caches` pointer when the corresponding `caches_cnt` is zero.

This isn't a property of our code specifically, that's how C works. If you have a pointer to a zero-sized allocation then you're allowed to touch exactly zero bytes through that pointer.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 284 at r2](https://reviewable.io/reviews/gramineproject/gramine/583#-N2B3tFbA__WQ6vdUo5J:-N2LWOVuB8meQd_y1Nga:b-s1r4du) ([raw file](https://github.com/gramineproject/gramine/blob/a582b9b70b7e1b4a0d18f0a48b2300f5cba90f84/LibOS/shim/src/fs/sys/fs.c#L284)):*
> (so the "incorrectness" is that we lose memory on smth that is never used).

That's not incorrect, just suboptimal memory-wise, which seems negligible in this case. Especially that this case shouldn't even happen in practice, so there's no point in optimizing it right now.
___
*[`LibOS/shim/src/fs/sys/fs.c` line 314 at r5](https://reviewable.io/reviews/gramineproject/gramine/583#-N2Lhvfx9UnRb8IHeenY:-N2Lhvfx9UnRb8IHeenZ:bcbzhp2) ([raw file](https://github.com/gramineproject/gramine/blob/18672ec24263bd20934199c37163a8298fb24378/LibOS/shim/src/fs/sys/fs.c#L314)):*
> ```C
> 
>     size_t numa_dm_size = topo_info->numa_nodes_cnt * topo_info->numa_nodes_cnt
>                             * sizeof(*topo_info->numa_distance_matrix);
> ```

Please indent by 2 spaces less.


<!-- Sent from Reviewable.io -->

2022-05-18 11:06 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2Lq1aX232Bms_34K7-:b23camb) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
Thanks @mkow . I actually didn't know that the C standard has this to say:

> If the size of the space requested is zero, the behavior is implementation-defined: either a null pointer is returned to indicate an error, or the behavior is as if the size were some nonzero value, **except that the returned pointer shall not be used to access an object**. § 7.22.3

Anyway, I'm fine with the current implementation.


<!-- Sent from Reviewable.io -->

2022-05-18 11:48 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-05-18 13:05 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-05-18 13:17 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 314 at r5](https://reviewable.io/reviews/gramineproject/gramine/583#-N2Lhvfx9UnRb8IHeenY:-N2MJBnvAkBA2ePXGtZI:b-xxs03s) ([raw file](https://github.com/gramineproject/gramine/blob/18672ec24263bd20934199c37163a8298fb24378/LibOS/shim/src/fs/sys/fs.c#L314)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please indent by 2 spaces less.
</blockquote></details>

I'm on it.


<!-- Sent from Reviewable.io -->

2022-05-18 13:24 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> Dismissed @vijaydhanraj from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[`LibOS/shim/src/fs/sys/fs.c` line 314 at r5](https://reviewable.io/reviews/gramineproject/gramine/583#-N2Lhvfx9UnRb8IHeenY:-N2MKkpOCMBpGyca8tOH:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/18672ec24263bd20934199c37163a8298fb24378/LibOS/shim/src/fs/sys/fs.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm on it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 13:25 UTC, dimakuv commented
Jenkins, test this plesae

2022-05-18 13:25 UTC, dimakuv commented
Jenkins, test this please (made a typo the last time)

2022-05-18 13:27 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-18 13:30 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-18 14:05 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2MTecQ9B00gUOuMZXE:bky9yxe) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
> Where?

I was referring to this, https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/db_main.c#L141


<!-- Sent from Reviewable.io -->

2022-05-18 14:12 UTC, merged

2022-05-18 14:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/583)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`LibOS/shim/src/fs/sys/fs.c` line 504 at r1](https://reviewable.io/reviews/gramineproject/gramine/583#-N1wiLIxCznxWWe3DL-9:-N2MYCLI4TA0TasDGb7K:b-yewod9) ([raw file](https://github.com/gramineproject/gramine/blob/7e8558650069d5b4dcfad8fb7b79818589e02c45/LibOS/shim/src/fs/sys/fs.c#L504)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> Where?

I was referring to this, https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/db_main.c#L141
</blockquote></details>

But this is a part of sanitization? How does this differ from 30 other checks in that function, which you didn't include here?


<!-- Sent from Reviewable.io -->