[Docs,CI-Examples] Document the SPID parameter
gramineproject/gramine pull request #585
Opened 2022-05-15 14:20 UTC by NieDzejkob

## Description of the changes 

The way one was supposed to run RA-TLS was confusing before. Explain what an SPID is, how to obtain one, and link to that documentation in the READMEs of relevant examples.

## How to test this PR?

Follow the instructions and verify they're clear.

2022-05-15 15:06 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/585#-N27DxeX8NIZvmC61rAF:-N27DxeX8NIZvmC61rAG:bllkohd) (no related file):*
Looks like I forgot the sign-off line in the commit message. I'll add it when rebasing.

I've set up a git hook following https://lubomir.github.io/en/2016-05-04-signoff-hooks.html to avoid this in the future.

___


<!-- Sent from Reviewable.io -->

2022-05-16 09:44 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEzcuDAMq2HK9K9a9:-N2BEzcuDAMq2HK9K9aA:bgeoq61) (no related file):*
We have the same problem with our Python example: https://github.com/NieDzejkob/gramine/tree/NieDzejkob/spid-docs/CI-Examples/python

More specifically, with the recently added `sgx-quote.py` script -- it also uses SGX remote attestation and requires SPID and co. in case of EPID scheme. Please update there too.

___
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BBODLEyZbaC5CmG5Y:-N2BBODLEyZbaC5CmG5Z:b-afb5ci) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L60)):*
> ```Markdown
> 
> Moreover, we set `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1`, to allow performing
> the tests without up-to-date microcode. As the name of this setting suggests,
> ```

`without up-to-date microcode` is a bit too... specific. In fact, the EPID/DCAP attestation infrastructure may return "outdated" status because of different reasons. Maybe a more vague `...performing the tests on platforms known to be outdated`?
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BCfas5WGco8uEHMHZ:-N2BCfat-YL_7W6LxG5I:b443y3b) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L68)):*
> ```Markdown
> In most of the examples below, you need to tell the client what values it should
> expect for `mr_enclave`, `mr_signer`, `isv_prod_id` and `isv_svn`. They will get
> printed by `gramine-sgx-get-token` when generating `server.token`.
> ```

Caching the outputs of `gramine-sgx-get-token` is not the only way to get these values. There are multiple ways (though Gramine doesn't yet have a simple tool to print all these values, which is a shame but noone has the bandwidth to create such a tool):
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/python/scripts/sgx-quote.py
- https://github.com/gramineproject/gramine/issues/242#issuecomment-977672047
- https://gramine.readthedocs.io/en/latest/python/api.html
- simply hexdump `server.token` and decipher its contents, based on Intel SDM tables

So maybe rephrase this last sentence to smth like `One way to obtain these values is to memorize the output of gramine-sgx-get-token ...`.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEYD5CfghdDbU-RuX:-N2BEYD5CfghdDbU-RuY:b-3lfuil) ([raw file](https://github.com/gramineproject/gramine/blob/80be43132c257e3b85c28847732f4bb989c4eb5d/CI-Examples/ra-tls-mbedtls/README.md#L78)):*
> ```Markdown
> # replace dummy values with your SPID, linkable setting, API key, MRENCLAVE, etc!
> make clean
> RA_CLIENT_SPID=12345678901234567890123456789012 RA_CLIENT_LINKABLE=0 make app epid
> ```

Well, I'm sad that we have to make it painfully obvious for users that `1234...` is not a real value, but that's life.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BDpwKEKgrDvy51oPl:-N2BDpwKEKgrDvy51oPm:bvo8yn7) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L88)):*
> ```Markdown
> 
>   IAS attestation requires API keys for interacting with Intel's servers. Obtain
>   below. Moreover the client needs to know what values for
> ```

What does it mean `Obtain below`? I don't understand this sentence.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BDtES2jUSGITpDJxu:-N2BDtES2jUSGITpDJxv:b-q6tqrt) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L88)):*
> ```Markdown
> 
>   IAS attestation requires API keys for interacting with Intel's servers. Obtain
>   below. Moreover the client needs to know what values for
> ```

`what values for it should expect` -> `what values it should expect`
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 90 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BDknb8tj1_CPyO70P:-N2BDknb8tj1_CPyO70Q:bsdd0s) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L90)):*
> ```Markdown
>   below. Moreover the client needs to know what values for
>   it should expect, they will get printed by
>   `gramine-sgx-get-token` during compilation.
> ```

Please put this whole para in `()`. Also, the line wrapping is weird here.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEKCVB_qkvkLHfDYx:-N2BEKCVB_qkvkLHfDYy:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L36)):*
> ```Markdown
> 
> Moreover, we set `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1`, to allow performing
> the tests without up-to-date microcode. As the name of this setting suggests,
> ```

ditto
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEFRtCjZgcfPXJ_7E:-N2BEFRtCjZgcfPXJ_7F:b-hnmnbt) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L67)):*
> ```Markdown
> - Secret Provisioning flows, EPID-based (IAS) attestation:
> 
>   For EPID-based (IAS) attestation, you will need to provide an [SPID and the corresponding IAS API keys][spid].
> ```

You forgot to add the `[spid]` web link, so it currently doesn't render.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEMS95h0Yzw2E6Dox:-N2BEMS95h0Yzw2E6Doy:b5c8tg0) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L67)):*
> ```Markdown
> - Secret Provisioning flows, EPID-based (IAS) attestation:
> 
>   For EPID-based (IAS) attestation, you will need to provide an [SPID and the corresponding IAS API keys][spid].
> ```

ditto (whole para inside `()`)
___
*[`Documentation/sgx-intro.rst` line 484 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2B9ojPB4dnni6C3-EP:-N2B9ojPB4dnni6C3-EQ:b-ctyxn) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/Documentation/sgx-intro.rst#L484)):*
> ```reStructuredText
>       you want to prevent sybil attacks), keep in mind that a new identity can
>       be generated by performing an epoch reset. The previous identity will
>       then become inaccessible, though.
> ```

This paragraph is going into exotic details. Maybe just remove this paragraph? Recommending to perform an epoch reset to hide your identity is an overkill -- one should just use unlinkable quotes if they want to hide the identity.
___
*[`Documentation/sgx-intro.rst` line 488 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2B91Cn6cdbpSr2VqOS:-N2B91Co0rxcomUrf8_0:b-pcnsf5) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/Documentation/sgx-intro.rst#L488)):*
> ```reStructuredText
>       The attestation mode being used can be chosen by the application enclave,
>       but if :term:`EPID` attestation is being us [...]

2022-05-18 14:55 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: 0 of 4 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEzcuDAMq2HK9K9a9:-N2MZm9p7X2pdTdIYdxw:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have the same problem with our Python example: https://github.com/NieDzejkob/gramine/tree/NieDzejkob/spid-docs/CI-Examples/python

More specifically, with the recently added `sgx-quote.py` script -- it also uses SGX remote attestation and requires SPID and co. in case of EPID scheme. Please update there too.
</blockquote></details>

Done.

___
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BBODLEyZbaC5CmG5Y:-N2E0I_Y8gmD6Q-D6YrB:b-b1z2d6) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`without up-to-date microcode` is a bit too... specific. In fact, the EPID/DCAP attestation infrastructure may return "outdated" status because of different reasons. Maybe a more vague `...performing the tests on platforms known to be outdated`?
</blockquote></details>

Indeed, more vague could work, but I think we'd want to point to some relevant documentation in this case.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 68 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BCfas5WGco8uEHMHZ:-N2MYm2d1LRmUOsR8vz7:b-eowr3y) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Caching the outputs of `gramine-sgx-get-token` is not the only way to get these values. There are multiple ways (though Gramine doesn't yet have a simple tool to print all these values, which is a shame but noone has the bandwidth to create such a tool):
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/python/scripts/sgx-quote.py
- https://github.com/gramineproject/gramine/issues/242#issuecomment-977672047
- https://gramine.readthedocs.io/en/latest/python/api.html
- simply hexdump `server.token` and decipher its contents, based on Intel SDM tables

So maybe rephrase this last sentence to smth like `One way to obtain these values is to memorize the output of gramine-sgx-get-token ...`.
</blockquote></details>

Clarified.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 78 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEYD5CfghdDbU-RuX:-N2E1a0u-OPXJhRhTL5i:bovun8k) ([raw file](https://github.com/gramineproject/gramine/blob/80be43132c257e3b85c28847732f4bb989c4eb5d/CI-Examples/ra-tls-mbedtls/README.md#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, I'm sad that we have to make it painfully obvious for users that `1234...` is not a real value, but that's life.
</blockquote></details>

`SPID` isn't actually that explicit as to what it is, and without that knowledge it might as well be a valid, if not optimal value, much like `ffeeddccbb...` is a valid cryptographic key which we use in some examples.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 88 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BDpwKEKgrDvy51oPl:-N2E16zL6crAuJDe46KA:b-jm9e5l) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean `Obtain below`? I don't understand this sentence.
</blockquote></details>

Whoops, looks like an editing mishap. These are leftovers from when I moved this information above, to give it a wider scope, so to speak. Removed.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEFRtCjZgcfPXJ_7E:-N2E2O5oBRVAc5Hvp2Od:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to add the `[spid]` web link, so it currently doesn't render.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 67 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEMS95h0Yzw2E6Dox:-N2E2OU9EpV3wYXA-0ag:b-57kxgi) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (whole para inside `()`)
</blockquote></details>

Okay. Inspired by this remark I changed the formatting a bit, to not make it a separate paragraph.
___
*[`Documentation/sgx-intro.rst` line 484 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2B9ojPB4dnni6C3-EP:-N2E2vgX9hytjX-qFuQE:bctppf3) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/Documentation/sgx-intro.rst#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This paragraph is going into exotic details. Maybe just remove this paragraph? Recommending to perform an epoch reset to hide your identity is an overkill -- one should just use unlinkable quotes if they want to hide the identity.
</blockquote></details>

See reworded text.
___
*[`Documentation/sgx-intro.rst` line 488 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2B91Cn6cdbpSr2VqOS:-N2E3Sp0-z8w_EaCg2Eh:b3vju4q) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/Documentation/sgx-intro.rst#L488)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This phrasing is confusing. Linkable/unlinkable quotes are only relevant to the EPID attestation scheme, and **not** to the ECDSA/DCAP attestation scheme.

So please make it explicit that linkable/unlinkable option makes sense only when using EPID.

For reference, I like the short explanations on EPID and DCAP here: https://eprint.iacr.org/2018/902.pdf, Section 2.1.
</blockquote></details>

Okay, I am now realizing that `DCAP` refers specifically to a mode of operation of Intel's launch enclaves and the surrounding infrastructure, and not just any attestation mechanism done with FLC.
___
*[`Documentation/sgx-intro.rst` line 536 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BAlumBy1OQsuC9Gev:-N2MX8dqERoS205t7Iy3:b-1mz6pn) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/Documentation/sgx-intro.rst#L536)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The link to `EPID` is currently meaningless -- the EPID description is more like a stub than an actual description. Maybe you can also expand on the EPID (and DCAP) terms in this PR? You can take inspiration from https://eprint.iacr.org/2018/902.pdf, Section 2.1, which does a good job at succinctly explaining the differences.
</blockquote></details>

Okay, I have expanded that section somewhat based on my understanding of the description you linked. 
___
*[`Documentation/sgx-intro.rst` line 542 at r1](https://reviewable.io/reviews/gramineproject/gr [...]

2022-05-19 12:02 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BBODLEyZbaC5CmG5Y:-N2R8d-t5EV19L5jdOjZ:b-qcisyy) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L60)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Indeed, more vague could work, but I think we'd want to point to some relevant documentation in this case.
</blockquote></details>

So here are the gory details: https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/tools/common/attestation.c#L238-L242

So, `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` actually covers a bunch of warnings returned by IAS/DCAP service: `GROUP_OUT_OF_DATE`, `CONFIGURATION_NEEDED`, `SW_HARDENING_NEEDED`, `CONFIGURATION_AND_SW_HARDENING_NEEDED`.

These warnings are described here: https://api.trustedservices.intel.com/documents/IAS-API-Spec-rev-4.0.pdf, see Table 4.2.1 on pages 17-19.

Some exerpts:
- GROUP_OUT_OF_DATE – The EPID signature of the ISV enclave QUOTE has been verified correctly, but the TCB level of SGX platform is outdated (for further details see Advisory IDs). The platform has not been identified as compromised and thus it is not revoked. It is up to the Service Provider to decide whether or not to trust the content of the QUOTE, and whether or not to trust the platform performing the attestation to protect specific sensitive information. 
- CONFIGURATION_NEEDED - The EPID signature of the ISV enclave QUOTE has been verified correctly, but additional configuration of SGX platform may be needed (for further details see Advisory IDs). The platform has not been identified as compromised and thus it is not revoked. It is up to the Service Provider to decide whether or not to trust the content of the QUOTE, and whether or not to trust the platform performing the attestation to protect specific sensitive information.

By the way, I don't see `SW_HARDENING_NEEDED` and `CONFIGURATION_AND_SW_HARDENING_NEEDED` in that document. At the same time, I can find them on the internet. Not sure if these statuses are deprecated or something, and don't have time to dig deeper into this.
___
*[`Documentation/sgx-intro.rst` line 306 at r2](https://reviewable.io/reviews/gramineproject/gramine/585#-N2RBCFbCuKWKFqK3aio:-N2RBCFbCuKWKFqK3aip:b-yq59oz) ([raw file](https://github.com/gramineproject/gramine/blob/72d74f6d78d48880326e8e8051073a76d556bde6/Documentation/sgx-intro.rst#L306)):*
> ```reStructuredText
>       the same hardware or not.
> 
>       If your security models depends on enforcing that the identifiers are
> ```

`models` -> `model`


<!-- Sent from Reviewable.io -->

2022-05-21 00:06 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: 1 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BBODLEyZbaC5CmG5Y:-N2Yus6l3-i-Nlh9PUwe:b-xihkbr) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So here are the gory details: https://github.com/gramineproject/gramine/blob/master/Pal/src/host/Linux-SGX/tools/common/attestation.c#L238-L242

So, `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE` actually covers a bunch of warnings returned by IAS/DCAP service: `GROUP_OUT_OF_DATE`, `CONFIGURATION_NEEDED`, `SW_HARDENING_NEEDED`, `CONFIGURATION_AND_SW_HARDENING_NEEDED`.

These warnings are described here: https://api.trustedservices.intel.com/documents/IAS-API-Spec-rev-4.0.pdf, see Table 4.2.1 on pages 17-19.

Some exerpts:
- GROUP_OUT_OF_DATE – The EPID signature of the ISV enclave QUOTE has been verified correctly, but the TCB level of SGX platform is outdated (for further details see Advisory IDs). The platform has not been identified as compromised and thus it is not revoked. It is up to the Service Provider to decide whether or not to trust the content of the QUOTE, and whether or not to trust the platform performing the attestation to protect specific sensitive information. 
- CONFIGURATION_NEEDED - The EPID signature of the ISV enclave QUOTE has been verified correctly, but additional configuration of SGX platform may be needed (for further details see Advisory IDs). The platform has not been identified as compromised and thus it is not revoked. It is up to the Service Provider to decide whether or not to trust the content of the QUOTE, and whether or not to trust the platform performing the attestation to protect specific sensitive information.

By the way, I don't see `SW_HARDENING_NEEDED` and `CONFIGURATION_AND_SW_HARDENING_NEEDED` in that document. At the same time, I can find them on the internet. Not sure if these statuses are deprecated or something, and don't have time to dig deeper into this.
</blockquote></details>

Okay, how about now?
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/585#-N2WWtgw00fzeyv02fKs:-N2YvX7z8wY-VfkuL4YI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72d74f6d78d48880326e8e8051073a76d556bde6/CI-Examples/ra-tls-mbedtls/README.md#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please stylize+spell them the same way as in Intel manuals for easier grepping. Same for all other places in this PR.
</blockquote></details>

Done.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BEKCVB_qkvkLHfDYx:-N2YvZ5J9p7PoiMzQZid:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-secret-prov/README.md#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/sgx-intro.rst` line 306 at r2](https://reviewable.io/reviews/gramineproject/gramine/585#-N2RBCFbCuKWKFqK3aio:-N2Yve4A96KJsBJljFL1:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/72d74f6d78d48880326e8e8051073a76d556bde6/Documentation/sgx-intro.rst#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`models` -> `model`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-21 00:19 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/585#-N2WWtgw00fzeyv02fKs:-N2YyvT1A8mV15hirrhE:bd8s8os) ([raw file](https://github.com/gramineproject/gramine/blob/72d74f6d78d48880326e8e8051073a76d556bde6/CI-Examples/ra-tls-mbedtls/README.md#L67)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, what about other places?


<!-- Sent from Reviewable.io -->

2022-05-21 00:22 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: 3 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramine/585#-N2WWtgw00fzeyv02fKs:-N2Yz_hCDw7dLrrwuslo:b-e8n5zj) ([raw file](https://github.com/gramineproject/gramine/blob/72d74f6d78d48880326e8e8051073a76d556bde6/CI-Examples/ra-tls-mbedtls/README.md#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done, what about other places?
</blockquote></details>

My bad, should be all now.


<!-- Sent from Reviewable.io -->

2022-05-21 00:24 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-21 09:30 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 60 at r1](https://reviewable.io/reviews/gramineproject/gramine/585#-N2BBODLEyZbaC5CmG5Y:-N2_waL5-FvP53WMI6hE:b-c1sv8z) ([raw file](https://github.com/gramineproject/gramine/blob/43b5409dcfa5c7023a9dd680e6eec18d122e2f7f/CI-Examples/ra-tls-mbedtls/README.md#L60)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay, how about now?
</blockquote></details>

Looks good to me now.
___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 61 at r4](https://reviewable.io/reviews/gramineproject/gramine/585#-N2_wYjZ1vbh-XXp7lk_:-N2_wYjZ1vbh-XXp7lka:b-8bq3so) ([raw file](https://github.com/gramineproject/gramine/blob/0b8549fd70c843982dcaad670daaabe68a75ac88/CI-Examples/ra-tls-mbedtls/README.md#L61)):*
> ```Markdown
> Moreover, we set `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1`, to allow performing
> the tests when some of Intel's security advisories haven't been addressed (for
> example, when the microcode or architectual enclaves aren't fully up-to-date).
> ```

Typo: `architectural`. I'll fix during final rebase.
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 37 at r4](https://reviewable.io/reviews/gramineproject/gramine/585#-N2_wvC8Bt0zgh6EtOt9:-N2_wvC8Bt0zgh6EtOtA:bxajxys) ([raw file](https://github.com/gramineproject/gramine/blob/0b8549fd70c843982dcaad670daaabe68a75ac88/CI-Examples/ra-tls-secret-prov/README.md#L37)):*
> ```Markdown
> Moreover, we set `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1`, to allow performing
> the tests when some of Intel's security advisories haven't been addressed (for
> example, when the microcode or architectual enclaves aren't fully up-to-date).
> ```

Typo: `architectural`


<!-- Sent from Reviewable.io -->

2022-05-21 09:35 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @NieDzejkob)

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 61 at r4](https://reviewable.io/reviews/gramineproject/gramine/585#-N2_wYjZ1vbh-XXp7lk_:-N2_xXIc0avtmbBFkBo9:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/0b8549fd70c843982dcaad670daaabe68a75ac88/CI-Examples/ra-tls-mbedtls/README.md#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `architectural`. I'll fix during final rebase.
</blockquote></details>

Done
___
*[`CI-Examples/ra-tls-secret-prov/README.md` line 37 at r4](https://reviewable.io/reviews/gramineproject/gramine/585#-N2_wvC8Bt0zgh6EtOt9:-N2_xpi05_FujSXI5b8e:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/0b8549fd70c843982dcaad670daaabe68a75ac88/CI-Examples/ra-tls-secret-prov/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `architectural`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-21 09:36 UTC, dimakuv commented
Jenkins, test this please

2022-05-21 09:37 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: all files reviewed, 1 unresolved discussion (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-21 12:51 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/585)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CI-Examples/ra-tls-mbedtls/README.md` line 61 at r4](https://reviewable.io/reviews/gramineproject/gramine/585#-N2_wYjZ1vbh-XXp7lk_:-N2af4_gBR5OC61z73b6:bw552x7) ([raw file](https://github.com/gramineproject/gramine/blob/0b8549fd70c843982dcaad670daaabe68a75ac88/CI-Examples/ra-tls-mbedtls/README.md#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Whoops, thanks!


<!-- Sent from Reviewable.io -->

2022-05-21 20:25 UTC, merged