[Pal/Linux-SGX] Provide RA_TLS_*=any, warn when the variable is unset
gramineproject/gramine pull request #586
Opened 2022-05-15 16:33 UTC by NieDzejkob

## Description of the changes 

Silently ignoring missing environment variables could turn a simple typo into a security-critical misconfiguration. Provide a more explicit way of ignoring a particular part of the SGX measurement and warn when an environment variable is simply missing.

Also detect and warn when neither mr_signer nor mr_enclave are specified.

## How to test this PR? 

Run the `ra-tls-mbedtls` example with some of the environment variables missing or set to `any` and observe the output.

Run `ra-tls-secret-prov` and note that the warnings are not printed, as a custom verification callback is used.

2022-05-16 10:18 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BFTzM51G4DUl7t2fP):*
Please wrap `RA_TLS_*=any` in backticks, for readability
___
*[`Documentation/attestation.rst` line 319 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BFgSo11TIUUc9WPuB:-N2BFgSp3ND5cjjTrM1h:b-vo7xwa) ([raw file](https://github.com/gramineproject/gramine/blob/64dfd30d3d755d9cf6ad867ccf7d899175efdb74/Documentation/attestation.rst#L319)):*
> ```reStructuredText
>   this ``ISV_PROD_ID``. This is a decimal string.
> - ``RA_TLS_ISV_SVN`` -- verify that the attesting enclave has this
>   ``ISV_SVN``. This is a decimal string.
> ```

Please rewrap to 80 chars.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BMfwX9kwx0ouutcwh:-N2BMfwX9kwx0ouutcwi:b-u29pci) ([raw file](https://github.com/gramineproject/gramine/blob/64dfd30d3d755d9cf6ad867ccf7d899175efdb74/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L93)):*
> ```C
>         INFO("WARNING: Neither " RA_TLS_MRSIGNER " nor " RA_TLS_MRENCLAVE " are specified. "
>              "This will accept any enclave and provides no security whatsoever. "
>              "This configuration does not make sense and will become an error in the future.\n");
> ```

But what if the user explicitly set like this:
```
RA_TLS_MRSIGNER=any
RA_TLS_MRENCLAVE=any
```

This will also become a hard error in the future, according to your check. But such an invocation (with the above envvars) is pretty explicit, so maybe the user actually wants this (for whatever reason, like debugging any enclave)? Or do we still consider this a hard error, and never-ever allow such a configuration, even if the user insists?


<!-- Sent from Reviewable.io -->

2022-05-16 22:36 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BFTzM51G4DUl7t2fP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap `RA_TLS_*=any` in backticks, for readability
</blockquote></details>

Okay, TODO when rebasing.
___
*[`Documentation/attestation.rst` line 319 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BFgSo11TIUUc9WPuB:-N2E-BtLEbVfUflhYhBn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/64dfd30d3d755d9cf6ad867ccf7d899175efdb74/Documentation/attestation.rst#L319)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap to 80 chars.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c` line 93 at r1](https://reviewable.io/reviews/gramineproject/gramine/586#-N2BMfwX9kwx0ouutcwh:-N2DzfxJ3xHeRGik6Xtx:bkzc8e5) ([raw file](https://github.com/gramineproject/gramine/blob/64dfd30d3d755d9cf6ad867ccf7d899175efdb74/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But what if the user explicitly set like this:
```
RA_TLS_MRSIGNER=any
RA_TLS_MRENCLAVE=any
```

This will also become a hard error in the future, according to your check. But such an invocation (with the above envvars) is pretty explicit, so maybe the user actually wants this (for whatever reason, like debugging any enclave)? Or do we still consider this a hard error, and never-ever allow such a configuration, even if the user insists?
</blockquote></details>

Okay, this is a good point. This is explicit enough and might have a usecase when debugging. I've removed the claim that it will become an error.


<!-- Sent from Reviewable.io -->

2022-05-17 06:22 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-17 06:22 UTC, dimakuv commented
Jenkins, test this please

2022-05-20 12:18 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/586#-N2WN38D0whcTYUGw-Ad):*
(sounds more natural to me this way)



_Suggestion:_
```
is not set
```
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/586#-N2WNi8Q5K_dqb5sKo88):*
That's how they are stylized/spelled in the official docs and I'd stick to this, for easier grepping.



_Suggestion:_
```
MRSIGNER nor MRENCLAVE
```
___
*[`Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c` line 33 at r2](https://reviewable.io/reviews/gramineproject/gramine/586#-N2WOFG4-SyAxe3kxHOR:-N2WOFG4-SyAxe3kxHOS:b-a4iy4m) ([raw file](https://github.com/gramineproject/gramine/blob/71ac89af78afa84305b037f93b888654c76c0b96/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c#L33)):*
> ```C
>             "This is deprecated and will become an error in the future. "
>             "If you wish to accept any value, please specify %s=any explicitly.\n",
>             name, name);
> ```

We rather wrap this way:



_Suggestion:_
```C
        INFO("WARNING: The default enclave verification hook is being used, but %s is not set. "
             "This is deprecated and will become an error in the future. "
             "If you wish to accept any value, please specify %s=any explicitly.\n",
             name, name);
```


<!-- Sent from Reviewable.io -->

2022-05-20 12:30 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-20 12:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-05-20 12:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/586#-N2WNi8Q5K_dqb5sKo88):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Okay. Merged all the commit message suggestions into the description of the fixup commit.
</blockquote></details>

Please use `squash` commits for this. When using `autosquash`, `fixup` will discard the commit message, while `squash` will prompt you to fix it.


<!-- Sent from Reviewable.io -->

2022-05-20 12:35 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gramine/586#-N2WNi8Q5K_dqb5sKo88):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `squash` commits for this. When using `autosquash`, `fixup` will discard the commit message, while `squash` will prompt you to fix it.
</blockquote></details>

Okay, will keep that in mind next time.


<!-- Sent from Reviewable.io -->

2022-05-20 12:47 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-20 12:47 UTC, mkow commented
Jenkins, retest this please

2022-05-20 13:04 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/586)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-05-20 17:29 UTC, merged