[LibOS] Only compile checks for SA_RESTORER flag on x86_64
gramineproject/gramine pull request #597
Opened 2022-05-23 11:16 UTC by stefanberger

SA_RESTORER is not used on all architectures and therefore only check
for this flag on x86_64 for now.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

2022-05-23 11:20 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/597#-N2kdK7ZAJjzjJUmooS-:-N2kdK7ZAJjzjJUmooS0:btu87xv) (no related file):*
FYI: The PPC64 port is doing well. I have syscall handling via seccomp also working now and I am trying to reduce the diffs between upstream and my repo as much as possible.

___


<!-- Sent from Reviewable.io -->

2022-05-24 00:32 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/597#-N2kdK7ZAJjzjJUmooS-:-N2nSfY563Lh1GZN3oRv:b-hjmlsw) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

FYI: The PPC64 port is doing well. I have syscall handling via seccomp also working now and I am trying to reduce the diffs between upstream and my repo as much as possible.
</blockquote></details>

Nice! I had some TODOs especially to clear parts of CPU specific code (and properly share this between LibOS and PAL), but that never reached the top of the queue. Maybe it's time to revive those ideas...

___
___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2nTOCO8vcU-__0gRNf:bqudr2c) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
> ```C
>     if (handler != SIG_IGN) {
>         /* User provided handler. */
> #if defined(__x86_64__)
> ```

I think this deserves a proper fix (and then this assert could be completely removed). How do you handle the `sa->sa_restorer` access below in PPC?
TODO for me: make sure this access is the only reason we required `SA_RESTORER`
___
*[`LibOS/shim/src/sys/shim_sigaction.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTI-o1tRDZd0j2tCv:-N2nTI-o1tRDZd0j2tCw:b-5coivt) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/sys/shim_sigaction.c#L43)):*
> ```C
> #if defined(__x86_64__)
>     if (act && !(act->sa_flags & SA_RESTORER)) {
>         /* XXX: This might not be true for all architectures (but is for x86_64)...
> ```

This comment can now be removed, please stash it into this PR


<!-- Sent from Reviewable.io -->

2022-05-24 01:49 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2njfZA01Qq9yHWxNb8:b-wvwnld) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this deserves a proper fix (and then this assert could be completely removed). How do you handle the `sa->sa_restorer` access below in PPC?
TODO for me: make sure this access is the only reason we required `SA_RESTORER`
</blockquote></details>

I ignore the restorer. On ppc64 we return from the handler via a call to rt_sigreturn.

Code is here: https://github.com/stefanberger/gramine4ppc64/blob/100ae81c1522179e61857cf00e2c279e78c7676f/LibOS/shim/src/arch/ppc64/shim_context.c#L284
___
*[`LibOS/shim/src/sys/shim_sigaction.c` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTI-o1tRDZd0j2tCv:-N2nje6v00TVFecdNDrO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/sys/shim_sigaction.c#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This comment can now be removed, please stash it into this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 01:53 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/597#-N2kdK7ZAJjzjJUmooS-:-N2nkmaU4mYVrqNZkzkC:by8r3uv) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nice! I had some TODOs especially to clear parts of CPU specific code (and properly share this between LibOS and PAL), but that never reached the top of the queue. Maybe it's time to revive those ideas...
</blockquote></details>

Larger diffs in the code for /proc/cpu display and test cases for example.  All architectures may be a bit different here. 
Besides that I still have an issue with the ELF relocation code that I need to look into again...

___


<!-- Sent from Reviewable.io -->

2022-05-24 07:03 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/597#-N2orkTD3ANSfLeMMHau):*
Slight reordering: `[LibOS] Compile checks for SA_RESTORER flag only on x86_64`


<!-- Sent from Reviewable.io -->

2022-05-24 11:55 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/gramine/597#-N2orkTD3ANSfLeMMHau):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Slight reordering: `[LibOS] Compile checks for SA_RESTORER flag only on x86_64`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 12:15 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-05-24 14:30 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/597#-N2kdK7ZAJjzjJUmooS-:-N2qRPyX717qM8R7lOoB:b-k8ltx6) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Larger diffs in the code for /proc/cpu display and test cases for example.  All architectures may be a bit different here. 
Besides that I still have an issue with the ELF relocation code that I need to look into again...

</blockquote></details>

Yeah, for /proc/cpu there will be differences, so all we can do is make it more manageable on different archs.

___
___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qSmcC5-u-wAD1SPNX:b-cip1vh) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I ignore the restorer. On ppc64 we return from the handler via a call to rt_sigreturn.

Code is here: https://github.com/stefanberger/gramine4ppc64/blob/100ae81c1522179e61857cf00e2c279e78c7676f/LibOS/shim/src/arch/ppc64/shim_context.c#L284
</blockquote></details>

On x64 return from signals is also done via sigreturn. From what I can see ppc64 and x64 behave in the exact same way here - pointer to a stub/wrapper issuing `rt_sigreturn` is passed in `sa_restorer` field by the user app (usually that's libc).


<!-- Sent from Reviewable.io -->

2022-05-24 14:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qTo5E8hOXAP5gsn8q:b-w1bnsd) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On x64 return from signals is also done via sigreturn. From what I can see ppc64 and x64 behave in the exact same way here - pointer to a stub/wrapper issuing `rt_sigreturn` is passed in `sa_restorer` field by the user app (usually that's libc).
</blockquote></details>

I don't think you need this: https://github.com/stefanberger/gramine4ppc64/blob/866eecb057cb9db19efaf150b0a3ab9426b14264/LibOS/shim/src/arch/ppc64/shim_context.c#L239
Is this assert failing for you in some cases? Is really `sa_restorer` missing somethimes?


<!-- Sent from Reviewable.io -->

2022-05-24 14:50 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qV3m85vwRNEhzvNAZ:bal2ec9) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think you need this: https://github.com/stefanberger/gramine4ppc64/blob/866eecb057cb9db19efaf150b0a3ab9426b14264/LibOS/shim/src/arch/ppc64/shim_context.c#L239
Is this assert failing for you in some cases? Is really `sa_restorer` missing somethimes?
</blockquote></details>

If I activate the assert `         assert(sa->sa_flags & SA_RESTORER);` I get the following errors:

```
FAILED test_libos.py::TC_01_Bootstrap::test_205_double_fork - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'doub...
FAILED test_libos.py::TC_01_Bootstrap::test_404_sigprocmask_pending - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_050_mmap - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file']' ...
FAILED test_libos.py::TC_30_Syscall::test_051_mmap_sgx - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file...
FAILED test_libos.py::TC_30_Syscall::test_090_sighandler_reset - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 's...
FAILED test_libos.py::TC_30_Syscall::test_091_sigaction_per_process - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_092_sighandler_sigpipe - AssertionError: False is not true
FAILED test_libos.py::TC_30_Syscall::test_094_signal_multithread - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', ...
FAILED test_libos.py::TC_30_Syscall::test_096_sighandler_contextswitch - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'i...
FAILED test_libos.py::TC_31_Syscall::test_010_syscall_restart - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'sy...
```

So that flag is not set.

If I now introduce an assert like this:
```
@@ -803,6 +803,7 @@ bool handle_signal(PAL_CONTEXT* context) {
         set_sig_mask(current, &new_mask);
         unlock(&current->lock);

+        assert(sa->sa_restorer != NULL);
         prepare_sigframe(context, &signal.siginfo, handler, sa->sa_restorer,
                          !!(sa->sa_flags & SA_ONSTACK), &old_mask);

```

I get again lots of errors:


```
FAILED test_libos.py::TC_01_Bootstrap::test_205_double_fork - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'doub...
FAILED test_libos.py::TC_01_Bootstrap::test_404_sigprocmask_pending - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_050_mmap - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file']' ...
FAILED test_libos.py::TC_30_Syscall::test_051_mmap_sgx - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file...
FAILED test_libos.py::TC_30_Syscall::test_090_sighandler_reset - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 's...
FAILED test_libos.py::TC_30_Syscall::test_091_sigaction_per_process - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_092_sighandler_sigpipe - AssertionError: False is not true
FAILED test_libos.py::TC_30_Syscall::test_094_signal_multithread - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', ...
FAILED test_libos.py::TC_30_Syscall::test_096_sighandler_contextswitch - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'i...
FAILED test_libos.py::TC_31_Syscall::test_010_syscall_restart - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'sy...
```


<!-- Sent from Reviewable.io -->

2022-05-24 15:00 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2q_AJVCNsRheMPTC-L:bnhodc4) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

If I activate the assert `         assert(sa->sa_flags & SA_RESTORER);` I get the following errors:

```
FAILED test_libos.py::TC_01_Bootstrap::test_205_double_fork - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'doub...
FAILED test_libos.py::TC_01_Bootstrap::test_404_sigprocmask_pending - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_050_mmap - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file']' ...
FAILED test_libos.py::TC_30_Syscall::test_051_mmap_sgx - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file...
FAILED test_libos.py::TC_30_Syscall::test_090_sighandler_reset - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 's...
FAILED test_libos.py::TC_30_Syscall::test_091_sigaction_per_process - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_092_sighandler_sigpipe - AssertionError: False is not true
FAILED test_libos.py::TC_30_Syscall::test_094_signal_multithread - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', ...
FAILED test_libos.py::TC_30_Syscall::test_096_sighandler_contextswitch - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'i...
FAILED test_libos.py::TC_31_Syscall::test_010_syscall_restart - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'sy...
```

So that flag is not set.

If I now introduce an assert like this:
```
@@ -803,6 +803,7 @@ bool handle_signal(PAL_CONTEXT* context) {
         set_sig_mask(current, &new_mask);
         unlock(&current->lock);

+        assert(sa->sa_restorer != NULL);
         prepare_sigframe(context, &signal.siginfo, handler, sa->sa_restorer,
                          !!(sa->sa_flags & SA_ONSTACK), &old_mask);

```

I get again lots of errors:


```
FAILED test_libos.py::TC_01_Bootstrap::test_205_double_fork - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'doub...
FAILED test_libos.py::TC_01_Bootstrap::test_404_sigprocmask_pending - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_050_mmap - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file']' ...
FAILED test_libos.py::TC_30_Syscall::test_051_mmap_sgx - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'mmap_file...
FAILED test_libos.py::TC_30_Syscall::test_090_sighandler_reset - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 's...
FAILED test_libos.py::TC_30_Syscall::test_091_sigaction_per_process - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init...
FAILED test_libos.py::TC_30_Syscall::test_092_sighandler_sigpipe - AssertionError: False is not true
FAILED test_libos.py::TC_30_Syscall::test_094_signal_multithread - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', ...
FAILED test_libos.py::TC_30_Syscall::test_096_sighandler_contextswitch - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'i...
FAILED test_libos.py::TC_31_Syscall::test_010_syscall_restart - subprocess.CalledProcessError: Command '['/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader', '/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so', 'init', 'sy...
```


</blockquote></details>

Hmm, indeed, ppc64 does have `sa_restorer`, but completely ignores it: https://elixir.bootlin.com/linux/latest/source/arch/powerpc/kernel/signal_64.c#L915


<!-- Sent from Reviewable.io -->

2022-05-24 15:03 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qa4LtEVKt2L8P2vAC:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, indeed, ppc64 does have `sa_restorer`, but completely ignores it: https://elixir.bootlin.com/linux/latest/source/arch/powerpc/kernel/signal_64.c#L915
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 15:06 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qa3dR9e-0ofsrgt7z:bs91h8d) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, checked now, `SA_RESTORER` was required here only because we blindly pass `sa_restorer` below. What we should do is remove this assert, pass `sa->sa_flags & SA_RESTORER ? sa->sa_restorer : NULL` below and let the arch code handle this correctly. It will work both there for x64 and in your pcc64 version.
Could you change this PR?


<!-- Sent from Reviewable.io -->

2022-05-24 15:25 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[`LibOS/shim/src/bookkeep/shim_signal.c` line 750 at r1](https://reviewable.io/reviews/gramineproject/gramine/597#-N2nTOCO8vcU-__0gRNe:-N2qf3oo6Q8Tw9ldc0jg:b-j9zbza) ([raw file](https://github.com/gramineproject/gramine/blob/bc85f2219728373e43faf23ed91fa587cca3cc85/LibOS/shim/src/bookkeep/shim_signal.c#L750)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, checked now, `SA_RESTORER` was required here only because we blindly pass `sa_restorer` below. What we should do is remove this assert, pass `sa->sa_flags & SA_RESTORER ? sa->sa_restorer : NULL` below and let the arch code handle this correctly. It will work both there for x64 and in your pcc64 version.
Could you change this PR?
</blockquote></details>

Done. Force-pushed.


<!-- Sent from Reviewable.io -->

2022-05-24 15:37 UTC, boryspoplawski commented
Jenkins, test this please

2022-05-25 00:29 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-30 06:35 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-30 13:53 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-05-30 13:53 UTC, dimakuv commented
Jenkins, test this please

2022-05-30 13:54 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-30 13:55 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/597)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-30 14:51 UTC, merged