[common & PAL] Restrict a #define anda a function to x86_64
gramineproject/gramine pull request #601
Opened 2022-05-23 21:34 UTC by stefanberger

This PR provides 2 patches that restrict a #define and a function to only be used and built when building for x86_64.

2022-05-24 00:24 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
These commie messages lack a `[component]` part. Can be fixed at the final rebase.
Proposed versions:
```[Pal] Define `DkCpuIdRetrieve` only for x86_64```
``` [mbedtls] Define `MBEDTLS_HAVE_X86_64` only when building for x86_64``` - not sure what the tag supposed to be here...
___
*[`Pal/src/db_misc.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nRWIP2SIAu23Qd-GD:-N2nRWIP2SIAu23Qd-GE:bvwe2v3) ([raw file](https://github.com/gramineproject/gramine/blob/c7c2a8d119a8d3d12a1cc2d2dc26b64fdff09beb/Pal/src/db_misc.c#L37)):*
> ```C
> }
> 
> #if defined(__x86_64__)
> ```

For the future: we probably need some more structured approach. Probably define a different per arch PAL API header (which would be included in `pal.h` for convenience) and also move actual implementation of such functions to per arch files.


<!-- Sent from Reviewable.io -->

2022-05-24 00:24 UTC, boryspoplawski commented
Jenkins, test this please

2022-05-24 06:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These commie messages lack a `[component]` part. Can be fixed at the final rebase.
Proposed versions:
```[Pal] Define `DkCpuIdRetrieve` only for x86_64```
``` [mbedtls] Define `MBEDTLS_HAVE_X86_64` only when building for x86_64``` - not sure what the tag supposed to be here...
</blockquote></details>

The proposed text looks good to me. The tag `[mbedtls]` is fine.
___
*[`Pal/src/db_misc.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nRWIP2SIAu23Qd-GD:-N2opDKQ9A2xdMk3G7Sw:b32v57) ([raw file](https://github.com/gramineproject/gramine/blob/c7c2a8d119a8d3d12a1cc2d2dc26b64fdff09beb/Pal/src/db_misc.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

For the future: we probably need some more structured approach. Probably define a different per arch PAL API header (which would be included in `pal.h` for convenience) and also move actual implementation of such functions to per arch files.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-05-24 06:52 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`Command ['gramine-direct', 'fcntl14'] timed out after 60 s`, unrelated to this PR)

2022-05-24 12:00 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The proposed text looks good to me. The tag `[mbedtls]` is fine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 12:16 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

- `[PAL]` -> `[Pal]`

- Instead of single-quotes, you should use backticks

Both these things you can fix now (by force-pushing), or we can fix ourselves


<!-- Sent from Reviewable.io -->

2022-05-24 12:40 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

- `[PAL]` -> `[Pal]`

- Instead of single-quotes, you should use backticks

Both these things you can fix now (by force-pushing), or we can fix ourselves
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 13:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine/601#-N2nQfwa8vlqEyiNDqQb):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Looks good now.


<!-- Sent from Reviewable.io -->

2022-05-24 13:42 UTC, dimakuv commented
Jenkins, test this please

2022-05-24 14:08 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-05-25 00:16 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-27 23:32 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-27 23:33 UTC, mkow commented
Jenkins, retest this please

2022-05-27 23:41 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-28 17:57 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/601)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-28 18:56 UTC, merged