[LibOS] Add support for `getcpu` syscall
gramineproject/gramine pull request #609
Opened 2022-05-26 02:13 UTC by vijaydhanraj

## Description of the changes 

This PR was dependent on sysfs rewrite. Now that it is done, reviving this PR.

This commit adds an approx. implementation of `getcpu` syscall that returns a random set bit from cpu affinity mask associated
with calling thread and its corresponding NUMA node.

`pthread_set_get_affinity` regression test is extended to validate this implementation. This commit also enables the
`getcpu01` ltp test for non-SGX case.

Closes https://github.com/gramineproject/graphene/pull/2331

## How to test this PR? 
Please run `pthread_set_get_affinity` LibOS regression test.

2022-05-30 08:50 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1s4923A5opvStQ2O:-N3J1s4923A5opvStQ2P:b-33xr3l) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L230)):*
> ```C
>     __UNUSED(unused);
> 
>     int ret = 0;
> ```

Let's do `int ret;`, without initializing to zero. The newer GCC versions can then perform additional checks that `ret` was set in all exiting paths.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J6RMCA0RSOScLHOxo:-N3J6RMCA0RSOScLHOxp:bfsg1ov) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L258)):*
> ```C
>     unsigned int idx = 0;
>     while (idx < max_cpu_bitmask) {
>         num_bits = count_ulong_bits_set(mask[idx]);
> ```

Why do we use `count_ulong_bits_set()` if we only need to check whether this long is empty (`== 0`) or not (`!= 0`)?

Also see my comment/proposal below.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3J5dgw9m7d6TTcrCPv:bimfkt7) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
> ```C
>          * us to the nth_setbit after nth_setbit iterations. */
>         cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
>     }
> ```

I forgot how our discussion ended in the previous version of this PR.

But why can't we simply choose a random CPU, and not the "random CPU in the first non-empty long"? Wouldn't it easier and more straight-forward, smth like this:
```
    size_t mask_idx = 0;
    size_t nth_setbit = rand_num % threads_cnt;

    /* At each iteration, find the lowest bit set in cpu mask and unset it; this will bring
     * us to the nth_setbit after nth_setbit iterations. */
    size_t i = 0;
    while (i < nth_setbit) {
        if (mask[mask_idx] == 0) {
            mask_idx++;
            /* TODO: check that we don't overflow mask */
            continue;
        }

        mask[mask_idx] = mask[mask_idx] & ~(1UL << __builtin_ctzl(mask[mask_idx]));
        i++;
    }

unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) + BITS_IN_TYPE(unsigned long) * mask_idx;    
```
___
*[`LibOS/shim/test/regression/pthread_set_get_affinity.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1QA7CdEcjzlFit9j:-N3J1QA7CdEcjzlFit9k:bg58e88) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/test/regression/pthread_set_get_affinity.c#L37)):*
> ```C
>     int ret = syscall(SYS_getcpu, &cpu, &node);
>     if (ret < 0)
>         err(EXIT_FAILURE, "sched_getcpu failed!");
> ```

`sched_getcpu` -> `getcpu`
___
*[`LibOS/shim/test/regression/pthread_set_get_affinity.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1YeHC7U-IOlpXqXY:-N3J1YeHC7U-IOlpXqXZ:b-qez5qy) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/test/regression/pthread_set_get_affinity.c#L39)):*
> ```C
>         err(EXIT_FAILURE, "sched_getcpu failed!");
> 
>     printf("Thread %ld is running on cpu: %d, node: %d\n", syscall(SYS_gettid), cpu, node);
> ```

The formatters for `cpu` and `node` must be `%u` (not `%d`)


<!-- Sent from Reviewable.io -->

2022-05-30 17:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 1 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 230 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1s4923A5opvStQ2O:-N3KyIEM0kq2sp6Pucbu:b-mws381) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's do `int ret;`, without initializing to zero. The newer GCC versions can then perform additional checks that `ret` was set in all exiting paths.
</blockquote></details>

Sure, I would also like to add a `ret = 0` before returning as well even though all the `DK*` functions return `0` on success. Just in case the return values of `Dk*`functions change in the future.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J6RMCA0RSOScLHOxo:-N3Kz3Zv9w59FXLCri_c:bul8bq9) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we use `count_ulong_bits_set()` if we only need to check whether this long is empty (`== 0`) or not (`!= 0`)?

Also see my comment/proposal below.
</blockquote></details>

For either approach (please see my response), we need `count_ulong_bits_set()` to count the number of cores that are part of the thread's affinity list. We then select any random core from that list.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3KZodyC_q1RBd_9S4W:b-3ejvc6) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
> I forgot how our discussion ended in the previous version of this PR.

I don't think we had any conclusion. IIRC, we discussed two options:
1. Find the first non-empty `cpumask` and select a random bit set from it.
2. Count all the cores present (bit set) in the `cpumask` and then randomly set a CPU from it.

>But why can't we simply choose a random CPU, and not the "random CPU in the first non-empty long"? Wouldn't it easier and more straight-forward, smth like this:

The code snippet below aligns with option 2. Yes, we can do it either way but I preferred option 1, as we can stop right after we find a non-empty `cpumask` as we just need to return a random CPU present in the thread's affinity and not keep iterating futher.

With the suggested code, I don't think we can randomly select any core from `threads_cnt`. We first need to find the cores that are part of the thread's affinity list and then select any random core from that. So, the code will look something like the below which is very similar to my current implementation just that we will do more iterations now given that we find a random core from the entire cpumask. 

```
    unsigned int num_bits = 0;
    unsigned int idx = 0;
    while (idx < max_cpu_bitmask) {
        num_bits += count_ulong_bits_set(mask[idx]);
        idx++;
    }
    
    /* There should be at least one bit set as part of the cpu affinity mask otherwise host is
       malicious. */
    if (num_bits == 0) {
        ret = -EINVAL;
        goto out;
    }
    
    /* Generate a random number and use it to find a random bit set in the first non-empty
     * unsigned long of the cpu affinity mask. */
    unsigned long rand_num = 0;
    ret = DkRandomBitsRead(&rand_num, sizeof(rand_num));
    if (ret < 0) {
        ret = pal_to_unix_errno(ret);
        goto out;
    }
    
    unsigned int nth_setbit = rand_num % num_bits;
    
    /* At each iteration, find the lowest bit set in cpu mask and unset it; this will bring
     * us to the nth_setbit after nth_setbit iterations. */
    size_t i = 0;
    while (i < nth_setbit) {
        if (mask[mask_idx] == 0) {
            mask_idx++;
            /* TODO: check that we don't overflow mask */
            continue;
        }

        mask[mask_idx] = mask[mask_idx] & ~(1UL << __builtin_ctzl(mask[mask_idx]));
        i++;
    }
    
    unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) + BITS_IN_TYPE(unsigned long) * mask_idx; 
```
___
*[`LibOS/shim/test/regression/pthread_set_get_affinity.c` line 37 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1QA7CdEcjzlFit9j:-N3KxoCS6vRR3lU4jIwz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sched_getcpu` -> `getcpu`
</blockquote></details>

Done.
___
*[`LibOS/shim/test/regression/pthread_set_get_affinity.c` line 39 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J1YeHC7U-IOlpXqXY:-N3KxuRYEXMP974wnLug:b-31b510) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The formatters for `cpu` and `node` must be `%u` (not `%d`)
</blockquote></details>

Yes, you are right. Fixed it.


<!-- Sent from Reviewable.io -->

2022-05-30 20:23 UTC, mkow requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 260 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LcD31BEEp_W5aTWg-:-N3LcD31BEEp_W5aTWg0:b-7a03rh) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L260)):*
> ```C
>         num_bits = count_ulong_bits_set(mask[idx]);
>         if (num_bits)
>             break;
> ```

If you removed this `if`, changed `=` above to `+=` and added a two-line `while` in the loop below, then you'd get solution which properly picks a random CPU from the whole affinity mask. So, +/- same complexity and less weird behavior :)
___
*[`LibOS/shim/src/sys/shim_sched.c` line 262 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LbuKiEQUdWpE0wTRg:-N3LbuKiEQUdWpE0wTRh:batv3ox) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L262)):*
> ```C
>             break;
>         idx++;
>      }
> ```

wrong indentation
___
*[`LibOS/shim/src/sys/shim_sched.c` line 265 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LWycxC-ohIwLnXD3m:-N3LWycxC-ohIwLnXD3n:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L265)):*
> ```C
> 
>     /* There should be at least one bit set as part of the cpu affinity mask otherwise host is
>        malicious. */
> ```





_Suggestion:_
```C
    /* There should be at least one bit set as part of the cpu affinity mask otherwise host is
     * doing something malicious. */
```


<!-- Sent from Reviewable.io -->

2022-05-31 03:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3NFJCz33V3kCrU0SZb:b-1uqial) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> I forgot how our discussion ended in the previous version of this PR.

I don't think we had any conclusion. IIRC, we discussed two options:
1. Find the first non-empty `cpumask` and select a random bit set from it.
2. Count all the cores present (bit set) in the `cpumask` and then randomly set a CPU from it.

>But why can't we simply choose a random CPU, and not the "random CPU in the first non-empty long"? Wouldn't it easier and more straight-forward, smth like this:

The code snippet below aligns with option 2. Yes, we can do it either way but I preferred option 1, as we can stop right after we find a non-empty `cpumask` as we just need to return a random CPU present in the thread's affinity and not keep iterating futher.

With the suggested code, I don't think we can randomly select any core from `threads_cnt`. We first need to find the cores that are part of the thread's affinity list and then select any random core from that. So, the code will look something like the below which is very similar to my current implementation just that we will do more iterations now given that we find a random core from the entire cpumask. 

```
    unsigned int num_bits = 0;
    unsigned int idx = 0;
    while (idx < max_cpu_bitmask) {
        num_bits += count_ulong_bits_set(mask[idx]);
        idx++;
    }
    
    /* There should be at least one bit set as part of the cpu affinity mask otherwise host is
       malicious. */
    if (num_bits == 0) {
        ret = -EINVAL;
        goto out;
    }
    
    /* Generate a random number and use it to find a random bit set in the first non-empty
     * unsigned long of the cpu affinity mask. */
    unsigned long rand_num = 0;
    ret = DkRandomBitsRead(&rand_num, sizeof(rand_num));
    if (ret < 0) {
        ret = pal_to_unix_errno(ret);
        goto out;
    }
    
    unsigned int nth_setbit = rand_num % num_bits;
    
    /* At each iteration, find the lowest bit set in cpu mask and unset it; this will bring
     * us to the nth_setbit after nth_setbit iterations. */
    size_t i = 0;
    while (i < nth_setbit) {
        if (mask[mask_idx] == 0) {
            mask_idx++;
            /* TODO: check that we don't overflow mask */
            continue;
        }

        mask[mask_idx] = mask[mask_idx] & ~(1UL << __builtin_ctzl(mask[mask_idx]));
        i++;
    }
    
    unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) + BITS_IN_TYPE(unsigned long) * mask_idx; 
```


</blockquote></details>

@mkow I think you are suggesting something like the above the code right?
___
*[`LibOS/shim/src/sys/shim_sched.c` line 260 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LcD31BEEp_W5aTWg-:-N3NFQhD1dgwTXmiQNAq:b-23dbdh) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L260)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you removed this `if`, changed `=` above to `+=` and added a two-line `while` in the loop below, then you'd get solution which properly picks a random CPU from the whole affinity mask. So, +/- same complexity and less weird behavior :)
</blockquote></details>

Please see the other thread where I have added some code. I think you are referring to a similar approach.


<!-- Sent from Reviewable.io -->

2022-05-31 06:58 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 258 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J6RMCA0RSOScLHOxo:-N3NtxNh-DBZ7yNdgIlz:b-ey7pr0) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L258)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

For either approach (please see my response), we need `count_ulong_bits_set()` to count the number of cores that are part of the thread's affinity list. We then select any random core from that list.
</blockquote></details>

You are right.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3Nt9u9-n9UfTtedkjI:bby2r3c) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
> With the suggested code, I don't think we can randomly select any core from threads_cnt. We first need to find the cores that are part of the thread's affinity list and then select any random core from that. 

Yes, sorry, you are right. I forgot that `threads_cnt` gives a number of *all* CPU logical cores. But what we need here is the number of *possible* CPU logical cores for this software thread (which is limited by the affinity list).

So yes, then your code snippet is more correct. I actually like your snippet, because as Michal puts it -- it has "less weird" behavior. So can we change to option 2 then?


<!-- Sent from Reviewable.io -->

2022-05-31 10:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3OiqDlCHcpQ7JWK3_7:b-39mdsa) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> With the suggested code, I don't think we can randomly select any core from threads_cnt. We first need to find the cores that are part of the thread's affinity list and then select any random core from that. 

Yes, sorry, you are right. I forgot that `threads_cnt` gives a number of *all* CPU logical cores. But what we need here is the number of *possible* CPU logical cores for this software thread (which is limited by the affinity list).

So yes, then your code snippet is more correct. I actually like your snippet, because as Michal puts it -- it has "less weird" behavior. So can we change to option 2 then?
</blockquote></details>

@vijaydhanraj: The proposed snippet looks good overall, modulo:
- The first `while` can now be shortened to a `for` loop.
- This `/* TODO: check that we don't overflow mask */` is not needed, it's not possible to overflow it.
- The second `while` should also be a `for` loop.
- The `if` in the second while should be `while` (right now this snippet is incorrect).


<!-- Sent from Reviewable.io -->

2022-05-31 14:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 286 at r1](https://reviewable.io/reviews/gramineproject/gramine/609#-N3J5dgw9m7d6TTcrCPu:-N3PSmFlCTxCSTvTN9IJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/bb391b5bec0995972698e5333c008ce38428cf8a/LibOS/shim/src/sys/shim_sched.c#L286)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, will switch to option 2 and send an updated patch.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 262 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LbuKiEQUdWpE0wTRg:-N3PSZED2LVVC4Cugu00:bbegwmr) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Not applicable with the recent change.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 265 at r2](https://reviewable.io/reviews/gramineproject/gramine/609#-N3LWycxC-ohIwLnXD3m:-N3PSkUi0WG7lDaE9BZZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/59358d7bea1e6a96a7b6266f5bb1921a3c25e16c/LibOS/shim/src/sys/shim_sched.c#L265)):*
> ```C
> 
>     /* There should be at least one bit set as part of the cpu affinity mask otherwise host is
>        malicious. */
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-05-31 15:54 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3PfpvqAeEm2_u-utYY:btib5jw) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
> ```C
> 
>     if (node) {
>         size_t core_id = g_pal_public_state->topo_info.threads[cpu_current].core_id;
> ```

Security vuln here: `cpu_current` may be bigger than `threads_cnt` or point to an offline thread, because the affinity mask is just forwarded from the host. This will cause us to leak enclave memory to the attacker.
The core issue is that we don't emulate the affinity in LibOS/PAL and just blindly trust the host that it will return consistent information. Could you create another PR to fix it? It should be rather simple, we should keep the affinity inside LibOS and only additionally ask the host to synchronize the real one with the one held in LibOS structures.


<!-- Sent from Reviewable.io -->

2022-05-31 23:54 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3REh7d7z__KD-MbEQ6:b6aca1j) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
Got it, thanks. Alternatively, can we add something like the below to address this issue? Since this is the only function where we directly use the output of `DkThreadGetCpuAffinity()` within LibOS. 
```
diff --git a/LibOS/shim/src/sys/shim_sched.c b/LibOS/shim/src/sys/shim_sched.c
index 4e41a22a5..3b51a3a75 100644
--- a/LibOS/shim/src/sys/shim_sched.c
+++ b/LibOS/shim/src/sys/shim_sched.c
@@ -287,6 +287,14 @@ long shim_do_getcpu(unsigned* cpu, unsigned* node, struct getcpu_cache* unused)
     unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) +
                                BITS_IN_TYPE(unsigned long) * mask_idx;
 
+    /* Since the cpu affinity mask is untrusted (forwarded from host) ensure `cpu_current` is a
+     * valid core that is online. */
+    if (cpu_current >= threads_cnt ||
+            !g_pal_public_state->topo_info.threads[cpu_current].is_online) {
+        ret = -EINVAL;
+        goto out;
+    }
+
     if (cpu)
         *cpu = cpu_current;
```

>disallow the app to accidentally set affinity to an offline core

Based on my quick check, I see that Linux sched get/set affinity calls fail if we try to affinitize application on an offlined core.


<!-- Sent from Reviewable.io -->

2022-06-01 00:06 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3R_4C2AmATdKbZv7E-:b3p3pm) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, thanks. Alternatively, can we add something like the below to address this issue? Since this is the only function where we directly use the output of `DkThreadGetCpuAffinity()` within LibOS. 
```
diff --git a/LibOS/shim/src/sys/shim_sched.c b/LibOS/shim/src/sys/shim_sched.c
index 4e41a22a5..3b51a3a75 100644
--- a/LibOS/shim/src/sys/shim_sched.c
+++ b/LibOS/shim/src/sys/shim_sched.c
@@ -287,6 +287,14 @@ long shim_do_getcpu(unsigned* cpu, unsigned* node, struct getcpu_cache* unused)
     unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) +
                                BITS_IN_TYPE(unsigned long) * mask_idx;
 
+    /* Since the cpu affinity mask is untrusted (forwarded from host) ensure `cpu_current` is a
+     * valid core that is online. */
+    if (cpu_current >= threads_cnt ||
+            !g_pal_public_state->topo_info.threads[cpu_current].is_online) {
+        ret = -EINVAL;
+        goto out;
+    }
+
     if (cpu)
         *cpu = cpu_current;
```

>disallow the app to accidentally set affinity to an offline core

Based on my quick check, I see that Linux sched get/set affinity calls fail if we try to affinitize application on an offlined core.
</blockquote></details>

No, please fix the issue at the core. IFying it here will only delay the moment when we accidentally do exactly the same somewhere else and introduce a security vuln.


<!-- Sent from Reviewable.io -->

2022-06-01 00:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3R_qClBBIEr4FpYMcx:b-pbo3rq) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, please fix the issue at the core. IFying it here will only delay the moment when we accidentally do exactly the same somewhere else and introduce a security vuln.
</blockquote></details>

Sure, will create another PR to address the affinity issue.


<!-- Sent from Reviewable.io -->

2022-06-01 10:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3Tjf8R-sBgnQ1VyKDe:b-pwflgd) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
> During `getaffinity` syscall, validate that the returned-from-host (via `DkThreadGetCpuAffinity`) CPU mask is a subset (? smth like this) of `shim_thread->cpumask`. Here we need to carefully check the man pages on what is the correct behavior (e.g., what if the user-supplied CPU mask included an offlined CPU). Also, at this point, `shim_thread->cpumask` needs to be updated to the corrected value.

No, getaffinity should just return the in-LibOS mask. And it's not "a cache" - from our LibOS perspective _that_ is the true affinity.

> This `getcpu` syscall should also have a validation after `DkThreadGetCpuAffinity`. Probably we need a wrapper function around `DkThreadGetCpuAffinity`, so that we don't have duplicated code.

Not if `DkThreadGetCpuAffinity` is handled entirely in LibOS (and probably removed from PAL API?).


<!-- Sent from Reviewable.io -->

2022-06-01 10:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3TqJEHE_6nlOllX-ME:btl0g5f) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
@mkow But Gramine itself can be run with smth like `cpuset -c 0-3 gramine-sgx ...`, which restricts the affinities of threads already, and is *not* reflected in `/sys/` files. But it *will* be reflected in `DkThreadGetCpuAffinity()`.

This way of running Gramine is used sometimes, especially for performance benchmarking purposes. If Gramine doesn't recognize this, we could end up with app inside Gramine having a totally wrong understanding of the schedulable cores.

Thinking about it... Maybe I'm wrong? But I see this in `man setcpu`:

> This can result in these other  calls  [`sched_setaffinity`] returning  an  error,  if  for example, such a call ends up requesting an empty set of CPUs or memory nodes, after that request is  restricted to the invoking process's cpuset.

Well, this needs some investigation... Why is Linux so hard.


<!-- Sent from Reviewable.io -->

2022-06-01 16:05 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3UyEWZDePLzDTYfJ7N:b-eqm489) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
Thanks @mkow @dimakuv for the clarification. Is calling `DkThreadGetCpuAffinity` during LibOS initialization to determine the default affinity of the thread? If so, can't we set it to`0xFFF..F` meaning affinitized to run on all cores as `cpuset` takes higher precedence over setting the affinity programmatically? We can then remove the `DkThreadGetCpuAffinity` PAL API. 

>>This can result in these other calls [sched_setaffinity] returning an error, if for example, such a call ends up requesting an empty set of CPUs or memory nodes, after that request is restricted to the invoking process's cpuset.

This I think is a user error and better not handled in Gramine. A legit user who restricts the application affinity using `cpuset` should be aware of setting the right affinity programmatically.


<!-- Sent from Reviewable.io -->

2022-06-01 17:58 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3VN1hoCbw_7D_1bUn5:b-oyfcab) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks @mkow @dimakuv for the clarification. Is calling `DkThreadGetCpuAffinity` during LibOS initialization to determine the default affinity of the thread? If so, can't we set it to`0xFFF..F` meaning affinitized to run on all cores as `cpuset` takes higher precedence over setting the affinity programmatically? We can then remove the `DkThreadGetCpuAffinity` PAL API. 

>>This can result in these other calls [sched_setaffinity] returning an error, if for example, such a call ends up requesting an empty set of CPUs or memory nodes, after that request is restricted to the invoking process's cpuset.

This I think is a user error and better not handled in Gramine. A legit user who restricts the application affinity using `cpuset` should be aware of setting the right affinity programmatically.
</blockquote></details>

Had an offline chat with @dimakuv and did a few experiments to check if we need to store `DkThreadGetCpuAffinity` during LibOS initialization and it looks like we do need this.

First experiment: Get default affinity on a 128-core system.
```
Default thread affinity using pthread_getaffinity_np: cpumask[0] = 0xffffffffffffffff, cpumask[1] = 0xffffffffffffffff
Default thread affinity using sched_getaffinity: cpumask[0] = 0xffffffffffffffff, cpumask[1] = 0xffffffffffffffff
```

As we can see both `pthread_getaffinity_np1` and `sched_getaffinity` show the thread affinitized to all the cores in the system.

Second experiment: Limit affinity using `numactl -C 0-3 gramine-direct test-app`
```
Default thread affinity using pthread_getaffinity_np: cpumask[0] = 0xf, cpumask[1] = 0x0
Default thread affinity using sched_getaffinity: cpumask[0] = 0xf, cpumask[1] = 0x0
```

Here we can see that both `pthread_getaffinity_np` and `sched_getaffinity` show the restrictive affinity set by `numactl`.

From the second experiment, we can conclude that `DkThreadGetCpuAffinity` needs to be called during LibOS initialization and the affinity stored else we might end up returning incorrect affinity to the user.

Found this https://serverfault.com/questions/625146/difference-between-taskset-and-cpuset useful to understand the difference between `taskset` vs `cpuset`.


<!-- Sent from Reviewable.io -->

2022-06-01 22:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3WRt4W3hB0XA3vzF2S:bwutaai) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
> If so, can't we set it to `0xFFF..F` meaning affinitized to run on all cores as `cpuset` takes higher precedence over setting the affinity programmatically? We can then remove the `DkThreadGetCpuAffinity` PAL API.
 
No, we can't, because that's the very thing we want to prevent by this change - to disallow the affinity mask to contain non-existent CPU threads.


<!-- Sent from Reviewable.io -->

2022-06-02 05:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3Xt8I20y7tfXhHJ86i:b-pnje2y) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> If so, can't we set it to `0xFFF..F` meaning affinitized to run on all cores as `cpuset` takes higher precedence over setting the affinity programmatically? We can then remove the `DkThreadGetCpuAffinity` PAL API.
 
No, we can't, because that's the very thing we want to prevent by this change - to disallow the affinity mask to contain non-existent CPU threads.
</blockquote></details>

Sorry, what I meant was to have default affinity set during thread initialization which is all available processors after removing the offlined and non-existent cores. So, this will be a legit mask having all the available cores. But even if we manage to do this, it will not work as users can launch Gramine app with a specific affinity using `numactl`and LibOS would be totally oblivious to this. So, I do agree that `DkThreadGetCpuAffinity` needs to be called during LibOS initialization and the affinity stored. This is what I had experimented and posted..  


<!-- Sent from Reviewable.io -->

2022-06-02 11:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3ZGS5j-FT3GJ8DTCng:b-5okqwr) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, what I meant was to have default affinity set during thread initialization which is all available processors after removing the offlined and non-existent cores. So, this will be a legit mask having all the available cores. But even if we manage to do this, it will not work as users can launch Gramine app with a specific affinity using `numactl`and LibOS would be totally oblivious to this. So, I do agree that `DkThreadGetCpuAffinity` needs to be called during LibOS initialization and the affinity stored. This is what I had experimented and posted..  
</blockquote></details>

Ok, makes more sense now ;)


<!-- Sent from Reviewable.io -->

2022-06-03 07:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 294 at r3](https://reviewable.io/reviews/gramineproject/gramine/609#-N3Pft0eDvcO0PD4gOKT:-N3cV2lu5Jjym7_et1pb:b-eqevsx) ([raw file](https://github.com/gramineproject/gramine/blob/c215a36e5522a02f8a6fd16e438863e7af664779/LibOS/shim/src/sys/shim_sched.c#L294)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, makes more sense now ;)
</blockquote></details>

@mkow @dimakuv Created PR https://github.com/gramineproject/gramine/pull/631 to address the issue. Can you please take a look?


<!-- Sent from Reviewable.io -->

2022-08-02 17:58 UTC, dimakuv commented
@vijaydhanraj We should rebase this PR, right?

2022-08-02 18:16 UTC, vijaydhanraj commented
@dimakuv Yes correct. Working on it.

2022-08-04 01:41 UTC, vijaydhanraj reviewed
Rebased and forced pushed the changes. PTAL.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609#-:-N8aVdji-oeaP2ydtJy2:b-j4i8rd)* status: 0 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-08-04 07:40 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 254 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bgIB-8hHgcumDbsNV:-N8bgIB0C_cxRkMRDMYq:bk9bq03) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L254)):*
> ```C
>         return -EFAULT;
> 
>     /* Allocate memory to hold the thread's cpu affinity mask. */
> ```

`to hold the` -> `to hold the copy of the`
___
*[`libos/src/sys/libos_sched.c` line 261 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bgirQAJglYfRAbVd5:-N8bgirQAJglYfRAbVd6:bhl21nk) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L261)):*
> ```C
> 
>     lock(&thread->lock);
>     memcpy(mask, thread->cpu_affinity_mask, GET_CPU_MASK_LEN() * sizeof(unsigned long));
> ```

`sizeof(unsigned long)` -> `sizeof(thread->cpu_affinity_mask)`
___
*[`libos/src/sys/libos_sched.c` line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bhI868c9R30UG3c1V:-N8bhI868c9R30UG3c1W:b-iqstvh) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L275)):*
> ```C
>         ret = -EINVAL;
>         goto out;
>     }
> ```

`num_bits == 0` shouldn't be possible anymore. There will always be at least one bit set in the cpu affinity mask. Please remove this check (+ the comment) and do simply:
```
assert(num_bits);
```
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8bk9lz3BJdneheuL-a:b-n1fbx5) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
> ```C
> 
>     unsigned int cpu_current = __builtin_ctzl(mask[mask_idx]) +
>                                BITS_IN_TYPE(unsigned long) * mask_idx;
> ```

Sorry, I know that we've discussed this so many times, but I still find it extremely hard to understand your logic. Let's rewrite it to be simpler. This is the 10-th time I look at this code and I get lost.

I suggest an algorithm like this:
```
/* we know num_bits and rand_num */
cpu_bit_idx = rand_num % num_bits;

mask_idx = 0;
while (cpu_bit_idx > count_ulong_bits_set(mask[idx])) {
    cpu_bit_idx -= count_ulong_bits_set(mask[idx]);
    mask_idx++;
}

cpu_idx = 0;
for (; cpu_idx < BITS_IN_TYPE(__typeof__(*mask)); cpu_idx++) {
    if (mask[mask_idx] & (1ul << cpu_idx)) {
        if (!cpu_bit_idx)
            break;
        cpu_bit_idx--;
    }
}

cpu_current = BITS_IN_TYPE(__typeof__(*mask)) * mask_idx + cpu_idx;
```

Something like this.


<!-- Sent from Reviewable.io -->

2022-08-04 11:55 UTC, boryspoplawski requested changes
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8cgh3rDeL0L1Tt5gmA:b-5jpj5h) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
> ```C
>     /* Allocate memory to hold the thread's cpu affinity mask. */
>     struct libos_thread* thread = get_cur_thread();
>     unsigned long* mask = malloc(GET_CPU_MASK_LEN() * sizeof(thread->cpu_affinity_mask));
> ```

Why do we need to copy the array?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N8chAdb0PTIIVoGkZ9S:b-4og447) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
> ```C
>         err(EXIT_FAILURE, "getcpu failed!");
> 
>     printf("Thread %ld is running on cpu: %u, node: %u\n", syscall(SYS_gettid), cpu, node);
> ```

We should verify that the returned values are correct (e.g. within current affinity mask)


<!-- Sent from Reviewable.io -->

2022-08-04 18:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8dz4fb-2rwMyueYkkQ:b1c41na) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need to copy the array?
</blockquote></details>

We can directly use `thread->cpu_affinity_mask` but we may need to hold the lock until we identify a random set bit in the mask. So preferred to copy it locally.
___
*[`libos/src/sys/libos_sched.c` line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bhI868c9R30UG3c1V:-N8e-0yL7-RiXB4AUAj8:b-9r1dhp) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`num_bits == 0` shouldn't be possible anymore. There will always be at least one bit set in the cpu affinity mask. Please remove this check (+ the comment) and do simply:
```
assert(num_bits);
```
</blockquote></details>

yes correct, will change it to an `assert`.
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8e-5XpE5yR9XqafYpC:b-sacxtn) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I know that we've discussed this so many times, but I still find it extremely hard to understand your logic. Let's rewrite it to be simpler. This is the 10-th time I look at this code and I get lost.

I suggest an algorithm like this:
```
/* we know num_bits and rand_num */
cpu_bit_idx = rand_num % num_bits;

mask_idx = 0;
while (cpu_bit_idx > count_ulong_bits_set(mask[idx])) {
    cpu_bit_idx -= count_ulong_bits_set(mask[idx]);
    mask_idx++;
}

cpu_idx = 0;
for (; cpu_idx < BITS_IN_TYPE(__typeof__(*mask)); cpu_idx++) {
    if (mask[mask_idx] & (1ul << cpu_idx)) {
        if (!cpu_bit_idx)
            break;
        cpu_bit_idx--;
    }
}

cpu_current = BITS_IN_TYPE(__typeof__(*mask)) * mask_idx + cpu_idx;
```

Something like this.
</blockquote></details>

This logic has an issue.
For example, if we have a system with 128 cores and if the thread affinity was set to only the last core, cpu 127 then cpu mask will be,
`mask[idx=0] = 0x0` and `mask[idx=1] = 0x8000000000000000`.

Now `cpu_bit_idx` will be `zero` as `num_bits` is `1` and it will skip the `cpu_bit_idx > count_ulong_bits_set(mask[mask_idx])` check as `mask[mask_idx=0 ]` is `zero`. Due to this `mask_idx` will not be incremented and we will run the `for loop` incrementing `cpu_idx`. Since mask[0] is `zero` `cpu_idx` will end up being `64` and not `127`.

To avoid this issue, I introduced the `while loop` which will first consume all the empty masks which have no cpus. And the rest is the same logic as before where we keep clearing the set bits until `nth_setbit`. Then use the built-in to find the cpu index.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N8e5U6CD4MCEBfpFknR:b-l7i66s) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should verify that the returned values are correct (e.g. within current affinity mask)
</blockquote></details>

yes, will add the check.


<!-- Sent from Reviewable.io -->

2022-08-04 23:01 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8eptqHEBAzfpRkgw4L:be6wdag) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
> we may need to hold the lock 

Yes we have to.

> So preferred to copy it locally.

But why?
___
*[`libos/src/sys/libos_sched.c` line 261 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bgirQAJglYfRAbVd5:-N8eq66I-ETawalNR_Ua:bc9ob83) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L261)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(unsigned long)` -> `sizeof(thread->cpu_affinity_mask)`
</blockquote></details>

`sizeof(*thread->cpu_affinity_mask)`
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8f4SQw6Hfp_RDzHHgD:bz1q9ku) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This logic has an issue.
For example, if we have a system with 128 cores and if the thread affinity was set to only the last core, cpu 127 then cpu mask will be,
`mask[idx=0] = 0x0` and `mask[idx=1] = 0x8000000000000000`.

Now `cpu_bit_idx` will be `zero` as `num_bits` is `1` and it will skip the `cpu_bit_idx > count_ulong_bits_set(mask[mask_idx])` check as `mask[mask_idx=0 ]` is `zero`. Due to this `mask_idx` will not be incremented and we will run the `for loop` incrementing `cpu_idx`. Since mask[0] is `zero` `cpu_idx` will end up being `64` and not `127`.

To avoid this issue, I introduced the `while loop` which will first consume all the empty masks which have no cpus. And the rest is the same logic as before where we keep clearing the set bits until `nth_setbit`. Then use the built-in to find the cpu index.
</blockquote></details>

https://github.com/boryspoplawski/gramine/tree/borys/test_get_cpu similar to what @dimakuv proposed, works and imo is shorter and cleaner than this version.


<!-- Sent from Reviewable.io -->

2022-08-05 00:54 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8fPbaY8xaUv0OJ49TK:b-d7h1xj) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> we may need to hold the lock 

Yes we have to.

> So preferred to copy it locally.

But why?
</blockquote></details>

Didn't want to block any other thread from getting/setting this thread's cpu affinity. From man pages, it looks like `Linux makes a best effort to make this call as fast as possible. ` so preferred not to hold the lock.

Another thing to note from the man page is that `The information placed in cpu is guaranteed to be current only at the time of the call.` So right after this call the affinity can change.
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8fSCPu1K8UDjTn9Ypl:bircq6n) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

https://github.com/boryspoplawski/gramine/tree/borys/test_get_cpu similar to what @dimakuv proposed, works and imo is shorter and cleaner than this version.
</blockquote></details>

Thanks @boryspoplawski but the code still has minor issues. 
1. Incorrect CPU is computed due to this, `idx = __builtin_ctzl(x) + i * sizeof(*thread->cpu_affinity_mask);`. 
It should be `idx = __builtin_ctzl(x) + i * BITS_IN_TYPE(__typeof__(*thread->cpu_affinity_mask));` IIUC.

2.  This assert `assert(idx < GET_CPU_MASK_LEN() * sizeof(*thread->cpu_affinity_mask));` will be triggered if idx is greater than `16`. 
It should have been, `assert(idx < GET_CPU_MASK_LEN() * BITS_IN_TYPE(__typeof__(*thread->cpu_affinity_mask)));`

Since the majority of maintainers feel current logic is hard to comprehend, I will switch to the proposed logic after fixing the issues.


<!-- Sent from Reviewable.io -->

2022-08-05 10:27 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8hXJJw89QUTFEBVBUu:bihpjc6) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
> Didn't want to block any other thread from getting/setting this thread's cpu affinity. 

I would expect threads to get/set only their own affinity, most of the time at least.

> From man pages, it looks like Linux makes a best effort to make this call as fast as possible. so preferred not to hold the lock.

But holding the lock doesn't make this operation longer. `malloc` + `memcpy` on the other hand do.

> Another thing to note from the man page is that The information placed in cpu is guaranteed to be current only at the time of the call. So right after this call the affinity can change.

Yes. And how's that related?
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8hXcobBX16n1NUBRr7:b-4pauva) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks @boryspoplawski but the code still has minor issues. 
1. Incorrect CPU is computed due to this, `idx = __builtin_ctzl(x) + i * sizeof(*thread->cpu_affinity_mask);`. 
It should be `idx = __builtin_ctzl(x) + i * BITS_IN_TYPE(__typeof__(*thread->cpu_affinity_mask));` IIUC.

2.  This assert `assert(idx < GET_CPU_MASK_LEN() * sizeof(*thread->cpu_affinity_mask));` will be triggered if idx is greater than `16`. 
It should have been, `assert(idx < GET_CPU_MASK_LEN() * BITS_IN_TYPE(__typeof__(*thread->cpu_affinity_mask)));`

Since the majority of maintainers feel current logic is hard to comprehend, I will switch to the proposed logic after fixing the issues.


</blockquote></details>

Yes, this code was not thoroughly tested. It should have `sizeof(*thread->cpu_affinity_mask)` replaced with `BITS_IN_TYPE(...)` as you noted.


<!-- Sent from Reviewable.io -->

2022-08-05 16:24 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8ik4Wp4lXBgoKx9ogp:b-5jo0wf) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
> But holding the lock doesn't make this operation longer. malloc + memcpy on the other hand do.

I would expect `memcpy` to be faster as it simply uses this `rep movsb` instruction but agree that `memcpy` might be more expensive. 

> Yes. And how's that related?

Holding the lock, made me assume you wanted to hold any changes to affinity to ensure `getcpu` returned the most accurate cpu and node of the calling thread. So, pointed out `getcpu` doesn't guarantee this.

I see your point and will use `thread->cpu_affinity_mask` instead of locally allocating memory.


<!-- Sent from Reviewable.io -->

2022-08-06 21:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 254 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bgIB-8hHgcumDbsNV:-N8o1j-KCVhiljlamQrf:bwz17z3) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to hold the` -> `to hold the copy of the`
</blockquote></details>

Not applicable as the code is changed.
___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8o1omh-axzY9nxpO2V:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> But holding the lock doesn't make this operation longer. malloc + memcpy on the other hand do.

I would expect `memcpy` to be faster as it simply uses this `rep movsb` instruction but agree that `memcpy` might be more expensive. 

> Yes. And how's that related?

Holding the lock, made me assume you wanted to hold any changes to affinity to ensure `getcpu` returned the most accurate cpu and node of the calling thread. So, pointed out `getcpu` doesn't guarantee this.

I see your point and will use `thread->cpu_affinity_mask` instead of locally allocating memory.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 261 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bgirQAJglYfRAbVd5:-N8o1MdEBR87hqFy6-9P:b-qfk3zp) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L261)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`sizeof(*thread->cpu_affinity_mask)`
</blockquote></details>

Not applicable as the code is changed.
___
*[`libos/src/sys/libos_sched.c` line 275 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bhI868c9R30UG3c1V:-N8o1siK85k38QX2y7vQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L275)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes correct, will change it to an `assert`.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N8o1T9-76nKuHhkUy5O:b-42cp6g) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, this code was not thoroughly tested. It should have `sizeof(*thread->cpu_affinity_mask)` replaced with `BITS_IN_TYPE(...)` as you noted.
</blockquote></details>

Implemented the proposed logic. One minor change is to start `nth_setbit` from `1` instead of `0` as I feel this is more readable.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N8o1vE8CZHST2YqGWM0:bnla61g) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, will add the check.
</blockquote></details>

I have added the check but noticed that `ltp` does the same check. Given this do we still want this change?


<!-- Sent from Reviewable.io -->

2022-08-12 02:44 UTC, vijaydhanraj reviewed
@boryspoplawski @mkow any other feedback on this PR?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609#-:-N9EvyMcD6WyGvzw1kox:bqwxqeb)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2022-08-12 22:32 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 256 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8cgh3rDeL0L1Tt5gm9:-N8pF22x22E-OhgKR15T:b77gzly) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L256)):*
> I would expect memcpy to be faster as it simply uses this rep movsb instruction but agree that memcpy might be more expensive.

Faster than what?

> Holding the lock, made me assume you wanted to hold any changes to affinity to ensure getcpu returned the most accurate cpu and node of the calling thread. So, pointed out getcpu doesn't guarantee this.

That makes no sense, it can change right after we release the lock.
___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N9J8_ykBFVfVIQNmkrP:b-3x50vg) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Implemented the proposed logic. One minor change is to start `nth_setbit` from `1` instead of `0` as I feel this is more readable.
</blockquote></details>

To the contrary, it's less readable. We start at `0` index virtually everywhere.
___
*[`libos/src/sys/libos_sched.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6cqh3D4V6mz3u2zn:-N9J6cqh3D4V6mz3u2zo:b-op8bu) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L254)):*
> ```C
>         return -EFAULT;
> 
>     /* Allocate memory to hold the thread's cpu affinity mask. */
> ```

What is this comment about?
___
*[`libos/src/sys/libos_sched.c` line 257 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6p1t0qtr8DKmfZ7A:-N9J6p1t0qtr8DKmfZ7B:b2nh8oq) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L257)):*
> ```C
>     struct libos_thread* thread = get_cur_thread();
> 
>     /* Generate a random number and use it to find a random bit set in the first non-empty
> ```

???
___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-N9J7Uxh3CBHlUK4tom_:b98vjjm) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
> ```C
>     /* CPU affinity mask is basically an array of unsigned long(s). Below logic randomly selects a
>      * bit set from the threads's cpu affinity mask and returns it to the user. */
>     unsigned int num_bits = 0;
> ```

Why this is `unsigned int`?
___
*[`libos/src/sys/libos_sched.c` line 269 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Ci00loIoQkEkpy3:-N9J7Ci00loIoQkEkpy4:bg3xsqz) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L269)):*
> ```C
>      * bit set from the threads's cpu affinity mask and returns it to the user. */
>     unsigned int num_bits = 0;
>     for (unsigned int idx = 0; idx < GET_CPU_MASK_LEN(); idx++)
> ```

1. We use `size_t` for indexes
2. We usually use `i` for in loops (but not blocking on this)
___
*[`libos/src/sys/libos_sched.c` line 272 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7aVd9kD89a42ATXP:-N9J7aVd9kD89a42ATXQ:b98vjjm) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L272)):*
> ```C
>         num_bits += count_ulong_bits_set(thread->cpu_affinity_mask[idx]);
>     assert(num_bits);
>     unsigned int nth_setbit = rand_num % num_bits + 1;
> ```

Why this is `unsigned int`?
___
*[`libos/src/sys/libos_sched.c` line 272 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J8IzFDAWPtxCesYmm:-N9J8IzFDAWPtxCesYmn:b8xcq58) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L272)):*
> ```C
>         num_bits += count_ulong_bits_set(thread->cpu_affinity_mask[idx]);
>     assert(num_bits);
>     unsigned int nth_setbit = rand_num % num_bits + 1;
> ```

This `+1` makes no sense, it only makes things harder.
___
*[`libos/src/sys/libos_sched.c` line 281 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J8BiB6pkt3MBlZEoa:-N9J8BiB6pkt3MBlZEob:bbut1f4) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L281)):*
> ```C
>         } else {
>             unsigned long cpumask = thread->cpu_affinity_mask[i];
>             /* Mask out `nth_setbit` lowest bits. */
> ```

This comment is not true. You mask `nth_setbit - 1` bits.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N9JA5CW8Cf1_jeQdvH1:b56syxz) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have added the check but noticed that `ltp` does the same check. Given this do we still want this change?
</blockquote></details>

I just noticed this set's only one bit in mask - this is not really a good test...
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-N9J9etrCer14xBSnupd:bm17gqb) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
> ```C
> 
>     while (thread_args->iterations != 0)
>         thread_args->iterations--;
> ```

This loop is completely wrong and can be optimized away. What's the point of it?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9and9IQ0r5Ja7yak:-N9J9and9IQ0r5Ja7yal:b-9vbg2k) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L40)):*
> ```C
> 
>     /* Preempt the thread to ensure parent can set its affinity before invoking `getcpu` */
>     sleep(1);
> ```

Please no sleeps. There are ways to do it correctly...


<!-- Sent from Reviewable.io -->

2022-08-12 23:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6cqh3D4V6mz3u2zn:-N9JDUuT5fbwUzKrKKLD:b-v0tav6) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L254)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is this comment about?
</blockquote></details>

Earlier I had used `malloc` so @dimakuv suggested this wording change but now we directly use `thread->cpu_affinity_mask` and this comment is stale.
___
*[`libos/src/sys/libos_sched.c` line 257 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6p1t0qtr8DKmfZ7A:-N9JEGfHAoFcxhHl6NOq:bx7h1ix) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L257)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

???
</blockquote></details>


How about `/* Generate a random number and use it to find a random bit set in the cpu affinity mask. */`?

Or do you propose to remove it?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N9JGXP77T03mTCITl2o:b-udyt72) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I just noticed this set's only one bit in mask - this is not really a good test...
</blockquote></details>

Shall I create a new LibOS regression test with multiple CPUs set as part of the affinity and revert all the changes in `pthread_set_get_affinity`?

New test case:
1. Set affinity for 2 CPUs (or 4 to be safer when running on a NUC machine). If hardcoding is not preferred, we can run the set the affinity on half of all online CPUs.
2. Get affinity to verify if the affinity is set properly,
3. Call `getcpu`to get the current CPU and add a check which ensures the CPU returned is part of the affinity set.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-N9JExojCCUMFkLGIY6j:b-d0uptr) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This loop is completely wrong and can be optimized away. What's the point of it?
</blockquote></details>

The test case has 2 values for iteration. When triggered manually it is set to a large value `10000000000` so that we can observe the set affinity using `top/htop` tool.

This was a `volatile` I had removed it when I moved it to the `thread_args` struct. I will add `volatile` qualifier back.


<!-- Sent from Reviewable.io -->

2022-08-12 23:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-N9JJ7Je2doFWdS4VJ-J:b-gmtos4) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is `unsigned int`?
</blockquote></details>

Felt `unsigned int` is enough to hold the value. Is `size_t` preferred?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N9JJsG-Be4YjMNdyF0C:b-w1i0yj) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Shall I create a new LibOS regression test with multiple CPUs set as part of the affinity and revert all the changes in `pthread_set_get_affinity`?

New test case:
1. Set affinity for 2 CPUs (or 4 to be safer when running on a NUC machine). If hardcoding is not preferred, we can run the set the affinity on half of all online CPUs.
2. Get affinity to verify if the affinity is set properly,
3. Call `getcpu`to get the current CPU and add a check which ensures the CPU returned is part of the affinity set.
</blockquote></details>

Update: We could just have a single thread do the mentioned steps to remove synchronization complexities.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9and9IQ0r5Ja7yak:-N9JJWdOBxFmoAXIza0-:bmace7z) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please no sleeps. There are ways to do it correctly...
</blockquote></details>

Yes, we could introduce some synchronization here to ensure first the affinity is set and then call `getcpu`. But please see the other comment where I propose to write a new test case.


<!-- Sent from Reviewable.io -->

2022-08-16 22:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 257 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6p1t0qtr8DKmfZ7A:-N9MmXi2DcSlh9YBaSBm:b-4x3jzv) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L257)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>


How about `/* Generate a random number and use it to find a random bit set in the cpu affinity mask. */`?

Or do you propose to remove it?
</blockquote></details>

I propose not to have comments that are applicable to the code that was already removed.
As we have a comment explaining stuff below, this one is completely unnecessary (even if it was fixed to be correct).
___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-N9coeSH9QVpLUc2G7OI:b-9z1vji) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Felt `unsigned int` is enough to hold the value. Is `size_t` preferred?
</blockquote></details>

Why `unsigned short` wouldn't be enough to hold the value?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N9cq7Cv0_WVFn6FkOnl:bbiv122) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Update: We could just have a single thread do the mentioned steps to remove synchronization complexities.
</blockquote></details>

It's nice to test setting affinity from another thread, so I would stick to this test.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-N9coyXp8454afPkCpN3:b-fvcl1t) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
> The test case has 2 values for iteration. When triggered manually it is set to a large value 10000000000 so that we can observe the set affinity using top/htop tool.

That's completely wrong. This loop will be removed when compiled with `-O2`.

> This was a volatile I had removed it when I moved it to the thread_args struct. I will add volatile qualifier back.

Please do not.


<!-- Sent from Reviewable.io -->

2022-08-17 16:49 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 4 of 6 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 300 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8bk9lz3BJdneheuL-_:-N9eNSlDDAdwise8_XjE:bana7ez) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/src/sys/libos_sched.c#L300)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To the contrary, it's less readable. We start at `0` index virtually everywhere.
</blockquote></details>

OK, starting from `0th` index.
___
*[`libos/src/sys/libos_sched.c` line 257 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6p1t0qtr8DKmfZ7A:-N9eBPTSAXK6hmeYtTWc:b-s0pdq1) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L257)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I propose not to have comments that are applicable to the code that was already removed.
As we have a comment explaining stuff below, this one is completely unnecessary (even if it was fixed to be correct).
</blockquote></details>

Yes, this was redundant. Removed it.
___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-N9eBzdfDpRQiiS5Jt3n:b-jt7dve) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `unsigned short` wouldn't be enough to hold the value?
</blockquote></details>

Yeah `0-65535` should be good enough but I think `size_t` might be better as it is also the return type for `count_ulong_bits_set`.

But I have switched to `unsigned short`.
___
*[`libos/src/sys/libos_sched.c` line 269 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Ci00loIoQkEkpy3:-N9eGfwO0UxZsTPL3nua:b-8ei6k9) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L269)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. We use `size_t` for indexes
2. We usually use `i` for in loops (but not blocking on this)
</blockquote></details>

I have changed accordingly.
___
*[`libos/src/sys/libos_sched.c` line 272 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7aVd9kD89a42ATXP:-N9eGk0C61bPl0Apg1F4:b-ick6dx) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L272)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is `unsigned int`?
</blockquote></details>

Changed to `unsigned short`.
___
*[`libos/src/sys/libos_sched.c` line 272 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J8IzFDAWPtxCesYmm:-N9eH2KI8BvRyMlvGuA9:b-qogjx9) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L272)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This `+1` makes no sense, it only makes things harder.
</blockquote></details>

OK, I reverted to start from `0th` position. 
___
*[`libos/src/sys/libos_sched.c` line 281 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J8BiB6pkt3MBlZEoa:-N9eL0Bs3CBO0OnMs5z6:bha5vob) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L281)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This comment is not true. You mask `nth_setbit - 1` bits.
</blockquote></details>

Since starting from `0th` position this comment becomes true.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r4](https://reviewable.io/reviews/gramineproject/gramine/609#-N8chAdb0PTIIVoGkZ9R:-N9g63Nm3OWR4qD5BnXs:b-b9c9hz) ([raw file](https://github.com/gramineproject/gramine/blob/204f361aad54e044aeb9e4e656ce33efd87f4645/libos/test/regression/pthread_set_get_affinity.c#L39)):*
OK, will use the same test case.

>I just noticed this set's only one bit in mask - this is not really a good test...

I now affinitize the thread to 2 cpus. For example, thread 1 is affinitized to cpus 0,1 and thread 2 to 2,3 and so on.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-N9eNv8nCPimCn2P5nsO:b-gxw7u8) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The test case has 2 values for iteration. When triggered manually it is set to a large value 10000000000 so that we can observe the set affinity using top/htop tool.

That's completely wrong. This loop will be removed when compiled with `-O2`.

> This was a volatile I had removed it when I moved it to the thread_args struct. I will add volatile qualifier back.

Please do not.
</blockquote></details>

Little confused you mean not to remove the volatile qualifier, right?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9and9IQ0r5Ja7yak:-N9g69mH9f1UkdefW7gH:b-ey5h87) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L40)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we could introduce some synchronization here to ensure first the affinity is set and then call `getcpu`. But please see the other comment where I propose to write a new test case.
</blockquote></details>

Moved the barrier before `getcpu` call as it will serve the purpose of holding all the child threads until the parent sets their affinity.


<!-- Sent from Reviewable.io -->

2022-08-23 07:44 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6cqh3D4V6mz3u2zn:-NA8YBJ2CZPUNnnqfwbW:braf0i1) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L254)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Earlier I had used `malloc` so @dimakuv suggested this wording change but now we directly use `thread->cpu_affinity_mask` and this comment is stale.
</blockquote></details>

Please remove the comment.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-NA8cgtK52gqxcbC4X3z:b-nmpe4d) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Little confused you mean not to remove the volatile qualifier, right?
</blockquote></details>

@boryspoplawski Do you want this loop to be removed completely? As Vijay said, this is for quick manual checks when you start this test for a long time and check `htop` in parallel.

If this loop can stay, maybe just `volatile asm("pause" : : : "memory");` in the loop body?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 40 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9and9IQ0r5Ja7yak:-NA8derFCRVc-z2GMlYP:b-4o8tqg) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L40)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Moved the barrier before `getcpu` call as it will serve the purpose of holding all the child threads until the parent sets their affinity.
</blockquote></details>

Looks correct to me.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NA8c0r76SdgjWDc5X5k:b5mk80y) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
> ```C
>         err(EXIT_FAILURE, "getcpu failed!");
> 
>     unsigned long cpumask = (1UL << cpu);
> ```

Please add a check/assert that `cpu` is less than or equal to 32.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 76 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8cHV-CODlX5iR_yrj:-NA8cHV0EpjgBR0_4Msq:b-i67lwj) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L76)):*
> ```C
> 
>     /* Below logic affinitizes each thread to 2 cores. So limiting to 32 cores so that we can store
>      * the affinity within a single unsigned long */
> ```

How does the first sentence related to the second sentence? Just leave the second sentence here:
```
/* Limit to 32 cores so that we can store the affinity within a single unsigned long */
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c8L40i6r0uCXRCCe:-NA8c8L40i6r0uCXRCCf:bbrlo53) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L77)):*
> ```C
>     /* Below logic affinitizes each thread to 2 cores. So limiting to 32 cores so that we can store
>      * the affinity within a single unsigned long */
>     numprocs = (numprocs > 32) ? 32: numprocs;
> ```

This one liner is hard to read. Simply:
```
if (numprocs > 32)
    numprocs = 32;
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NA8e0-JCPw4pCSHopEM:bickyj5) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
> ```C
>         } else {
>             CPU_SET(i * 2, &cpus);
>             CPU_SET(i * 2 + 1, &cpus);
> ```

What if there are 3 CPUs on the system? Won't the check for affinity break?


<!-- Sent from Reviewable.io -->

2022-08-23 08:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 270 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8qk-12lXQ24NkElee:-NA8qk-12lXQ24NkElef:b93wgo) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/src/sys/libos_sched.c#L270)):*
> ```C
>         num_bits += count_ulong_bits_set(thread->cpu_affinity_mask[i]);
>     assert(num_bits);
>     unsigned short nth_setbit = rand_num % num_bits;
> ```

I dislike the name `nth_setbit` now. Because it can be equal to `0`, and "zero-th bit should be set" makes no gramatical sense.

I think Borys used `target_bit`, let's rename to this.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8pSq11U3P9uNRpc4J:-NA8pSq11U3P9uNRpc4K:bvns0cq) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

I think we should re-think this test and re-write it accordingly.

Some high-level questions that we need to agree on:
1. Do we need the "manual checking with `htop`" in this test? I think not anymore -- this scenario only complicates the test, and if someone really needs manual checking, well, the person can augment this test locally.
2. To which CPU cores do we want software threads to be affinized? I was actually fine with "one thread affinitized to one core". Otherwise the logic of choosing these cores is complicated (what if some cores are offline? what if we have an odd number of cores? etc)
3. Do we want to limit the number of detected CPU cores (and exclude hyper-threads)? I would say no, just use the returned number of CPU cores + limit to e.g. 32 cores (for simplicity of working with affinity masks).

@boryspoplawski What do you think?


<!-- Sent from Reviewable.io -->

2022-08-23 11:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-NA9IHpwAf17-EZu02fl:b-n51th1) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yeah `0-65535` should be good enough but I think `size_t` might be better as it is also the return type for `count_ulong_bits_set`.

But I have switched to `unsigned short`.
</blockquote></details>

The answer to the question is negative and no, it's not good enough. Please use `size_t`.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-NA9JcCV2xgBOIjxwk1r:b-gxjcwp) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Do you want this loop to be removed completely? As Vijay said, this is for quick manual checks when you start this test for a long time and check `htop` in parallel.

If this loop can stay, maybe just `volatile asm("pause" : : : "memory");` in the loop body?
</blockquote></details>

Yes, please remove it.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8pSq11U3P9uNRpc4J:-NA9NFSnCgl_MuRaWpsI:bm2zkng) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we should re-think this test and re-write it accordingly.

Some high-level questions that we need to agree on:
1. Do we need the "manual checking with `htop`" in this test? I think not anymore -- this scenario only complicates the test, and if someone really needs manual checking, well, the person can augment this test locally.
2. To which CPU cores do we want software threads to be affinized? I was actually fine with "one thread affinitized to one core". Otherwise the logic of choosing these cores is complicated (what if some cores are offline? what if we have an odd number of cores? etc)
3. Do we want to limit the number of detected CPU cores (and exclude hyper-threads)? I would say no, just use the returned number of CPU cores + limit to e.g. 32 cores (for simplicity of working with affinity masks).

@boryspoplawski What do you think?
</blockquote></details>

1) No, I don't think we need it.
2) How about `MIN(2, online_cpus)` random cores?
3) No, we do not. But I also don't see how limiting to 32 helps with anything.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 25 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA9LVIKC_Bj9V13UXY3:-NA9LVIKC_Bj9V13UXY4:b-8mwciu) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L25)):*
> ```C
> 
> struct parent_to_child_args {
>     unsigned int thread_affinity;
> ```

Why is this `unsigned int`?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NA9L2JH8ah2vL01CTrO:b-o1at2o) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a check/assert that `cpu` is less than or equal to 32.
</blockquote></details>

Why 32? `sizeof(cpumask) * 8` and only less (not equal). And assert is not enough.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 92 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA9MTca3cmEKvA3LOZ0:-NA9MTca3cmEKvA3LOZ1:bk54qy2) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L92)):*
> ```C
>     uint64_t iterations = argc > 1 ? atol(argv[1]) : 10000000000;
> 
>     struct parent_to_child_args thread_args[numprocs];
> ```

Please no VLAs (unless necessary)
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NA9MZxv2MnTRY5dP2Mu:b-obhldl) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What if there are 3 CPUs on the system? Won't the check for affinity break?
</blockquote></details>

What if there is odd number of CPUs (not necessarily 3)? What if some CPUs are offline? This will break.


<!-- Sent from Reviewable.io -->

2022-08-23 23:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 4 of 6 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 254 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J6cqh3D4V6mz3u2zn:-NA9wE676fPqupzPi_5o:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the comment.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 268 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7Uxh3CBHlUK4tomZ:-NA9z8hY6Ilat6pEUKbd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L268)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The answer to the question is negative and no, it's not good enough. Please use `size_t`.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 272 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J7aVd9kD89a42ATXP:-NA9zAtr3_5svC5o-UVG:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/src/sys/libos_sched.c#L272)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed to `unsigned short`.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 270 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8qk-12lXQ24NkElee:-NA9zFBI99AnaRaEwZWI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/src/sys/libos_sched.c#L270)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I dislike the name `nth_setbit` now. Because it can be equal to `0`, and "zero-th bit should be set" makes no gramatical sense.

I think Borys used `target_bit`, let's rename to this.
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 37 at r5](https://reviewable.io/reviews/gramineproject/gramine/609#-N9J9etrCer14xBSnupc:-NAA-e7F5S6dlHeaVcSK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/171d6bf2229fad7749c1b368d68b5386b9797560/libos/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, please remove it.
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 1 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8pSq11U3P9uNRpc4J:-NABlsa_3-2O4sloL57_:bvanrpm) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L1)):*
> No, I don't think we need it.

I have removed the logic for "manual checking with htop"

>>To which CPU cores do we want software threads to be affinized? I was actually fine with "one thread affinitized to one core". Otherwise the logic of choosing these cores is complicated (what if some cores are offline? what if we have an odd number of cores? etc)
>
>How about MIN(2, online_cpus) random cores?

Please see my other comment and I think this should not be a problem because I limit the number of threads to half of the cores online and this should help us affinitize a thread to 2 cores. So if we have 2 or more cores then this `  numprocs = (numprocs >= 2) ? numprocs/2 : 1;` should help. And if there is only 1 core, I only set affinity on one core anyway.


>>Do we want to limit the number of detected CPU cores (and exclude hyper-threads)? I would say no, just use the returned number of CPU cores + limit to e.g. 32 cores (for simplicity of working with affinity masks).
>
>No, we do not. But I also don't see how limiting to 32 helps with anything.

Actually we are not limiting the number of cores but the number of threads. By limiting the number of threads to 32, and each thread has affinity set to 2 cores, we can have the entire mask within a `unsigned long`. And as @dimakuv mentioned, this just simplifies working with cpumasks. 
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 25 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA9LVIKC_Bj9V13UXY3:-NA9zh7t-xySO9j4aclc:bib94ut) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this `unsigned int`?
</blockquote></details>

It should be `unsigned long`.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NAAYnPn0G5DzyIHyPhi:b-hdho0u) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why 32? `sizeof(cpumask) * 8` and only less (not equal). And assert is not enough.
</blockquote></details>

Yes, the `cpu` can be between `0-63` but do we need a check/assert for this? The code should fail if the returned `cpumask` contains any `cpu` which is not part of the `thread_args->thread_affinity`. And the check below takes care of it.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 73 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NABfNLF8fAsrexbxQ3v:-NABfNLF8fAsrexbxQ3w:b-98bqum) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L73)):*
> ```C
> 
>     /* Affinitize threads to alternate logical processors to do a quick check from htop manually */
>     numprocs = (numprocs >= 2) ? numprocs/2 : 1;
> ```

Please note I have renamed `numprocs` ->`numthreads` as it is more appropriate. With this premise,

@dimakuv @boryspoplawski, even if some cores are offlined or we have an odd number of cores, this logic should ensure we have at least have 2 cores to affinitize a thread.

For example, if we have 3 cores, then the number of threads created will be 1 and we affinitize cores 0,1 to this thread.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 76 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8cHV-CODlX5iR_yrj:-NAAadfn-kXmgJf3ncmY:b-tjhpq) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does the first sentence related to the second sentence? Just leave the second sentence here:
```
/* Limit to 32 cores so that we can store the affinity within a single unsigned long */
```
</blockquote></details>

Actually the first part of this comment belongs to the earlier line where I divide `numprocs` by 2. I have added some more clear comment there and have removed it from here as suggested.

Also, renamed `numprocs` -> `numthreads` which i think makes more sense as we are dealing with the number of threads.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 77 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c8L40i6r0uCXRCCe:-NABYxo14Wrj7VmNx0AF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba [...]

2022-08-24 00:50 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 278 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACF_9e9kqpNLKPlMTT:-NACF_9f-hBozBqJQgIZ:bxuag3t) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/src/sys/libos_sched.c#L278)):*
> ```C
>         } else {
>             unsigned long cpumask = thread->cpu_affinity_mask[i];
>             /* Mask out `nth_setbit` lowest bits. */
> ```

forgot about this
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NACHR4t8JAiLZ1X5VAd:b-akih2q) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, the `cpu` can be between `0-63` but do we need a check/assert for this? The code should fail if the returned `cpumask` contains any `cpu` which is not part of the `thread_args->thread_affinity`. And the check below takes care of it.
</blockquote></details>

Shifting by more than the bitsize is UB.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NACJ5q38Sv7wo7NqfbR:b-tgwiq) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please see the other comment where I have tagged you. I think it should address this problem.
</blockquote></details>

No, it does not address the problem. What if you have 8 cores, but only 0 and 5-7 are online?
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 48 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACI6Lp0KU8XWscajAQ:-NACI6Lp0KU8XWscajAR:b-c14kdu) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/test/regression/pthread_set_get_affinity.c#L48)):*
> ```C
>     if ((cpumask & thread_args->thread_affinity) == 0) {
>         errx(EXIT_FAILURE, "Expected cpumask = %ld returned cpumask = %d",
>              thread_args->thread_affinity, cpu);
> ```

This is not cpumask



_Code quote:_
```C
cpu
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 109 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACImR4-0MBhuZaF3Bm:-NACImR4-0MBhuZaF3Bn:b-tlgtc3) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/test/regression/pthread_set_get_affinity.c#L109)):*
> ```C
>         }
> 
>         thread_args[i].thread_affinity = set_affinity;
> ```

There is no point in wrapping this in a struct, you can pass it directly.


<!-- Sent from Reviewable.io -->

2022-08-24 04:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NAD6TQc0nKTAS8mq98D:b-mxluuu) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shifting by more than the bitsize is UB.
</blockquote></details>

Got it, will add the check.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NAD6g5r0C-LIEd26KQp:b-g2a0vt) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it does not address the problem. What if you have 8 cores, but only 0 and 5-7 are online?
</blockquote></details>

yes, you are right. The current solution only takes care of the odd number of cores issue and not offlined cores.

How about we do this?
1. Find the total number of online cores and divide it by 2. This is the number of threads to spawn and each of the threads will be affinitized to 2 cores.
2. Get the `default thread affinity mask` for the parent. This should contain all the cores online. (By default a thread is affinitized to all the cores in the system).
3. Iterate over the `default affinity mask` and find the first 2 set cores. We can use `CPU_ISSET()` for this.
4. Copy these 2 cores into a `new cpumask` and set the thread's affinity. Also, we clear the set cores bits from the `default thread affinity mask` using `CPU_CLR()` so that the next thread is not affinitized to the same cores.
5. Pass the `new cpumask` to the child and check if the cpu returned from `getcpu` is part of the affinity mask.
6. Test succeeds if the cpu is part of the mask, else it fails.
7. We continue this logic for `numthreads` times.


<!-- Sent from Reviewable.io -->

2022-08-24 07:45 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NADnMt1EXehc1ivyvUD:b-9fbm6v) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, you are right. The current solution only takes care of the odd number of cores issue and not offlined cores.

How about we do this?
1. Find the total number of online cores and divide it by 2. This is the number of threads to spawn and each of the threads will be affinitized to 2 cores.
2. Get the `default thread affinity mask` for the parent. This should contain all the cores online. (By default a thread is affinitized to all the cores in the system).
3. Iterate over the `default affinity mask` and find the first 2 set cores. We can use `CPU_ISSET()` for this.
4. Copy these 2 cores into a `new cpumask` and set the thread's affinity. Also, we clear the set cores bits from the `default thread affinity mask` using `CPU_CLR()` so that the next thread is not affinitized to the same cores.
5. Pass the `new cpumask` to the child and check if the cpu returned from `getcpu` is part of the affinity mask.
6. Test succeeds if the cpu is part of the mask, else it fails.
7. We continue this logic for `numthreads` times.
</blockquote></details>

I'm generally fine with this proposed solution.

In step 1 though, the number of threads-to-spawn must be limited via `MANIFEST_SGX_THREAD_CNT - (INTERNAL_THREAD_CNT + MAIN_THREAD_CNT)`, same as now. Otherwise, you may exceed `sgx.thread_num` on big-ish systems and this test will fail.

@boryspoplawski What do you think?


<!-- Sent from Reviewable.io -->

2022-08-24 12:42 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NAErw3N8yaSZR7iDq2J:b-fspay2) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
> In step 1 though, the number of threads-to-spawn must be limited via MANIFEST_SGX_THREAD_CNT - (INTERNAL_THREAD_CNT + MAIN_THREAD_CNT), same as now. 

Yes, will keep this same as now.


<!-- Sent from Reviewable.io -->

2022-08-24 12:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NAEtXfj3Hs2wKOx7ubF:bnjzwcm) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> In step 1 though, the number of threads-to-spawn must be limited via MANIFEST_SGX_THREAD_CNT - (INTERNAL_THREAD_CNT + MAIN_THREAD_CNT), same as now. 

Yes, will keep this same as now.
</blockquote></details>

On a high level looks good.


<!-- Sent from Reviewable.io -->

2022-08-24 20:32 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 4 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 278 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACF_9e9kqpNLKPlMTT:-NAGPE6102aKalC6zMe2:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/src/sys/libos_sched.c#L278)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

forgot about this
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 49 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8c0r76SdgjWDc5X5j:-NAGPHij6-1koo6Bt-fu:b49atl1) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L49)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, will add the check.
</blockquote></details>

Removed this shifting logic and used CPU_* MACROs.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 105 at r6](https://reviewable.io/reviews/gramineproject/gramine/609#-NA8e0-JCPw4pCSHopEL:-NAGP94QEWtaVMSvEz1d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b33009b8a1cc225ba2ece38c1391da1a3950db5f/libos/test/regression/pthread_set_get_affinity.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On a high level looks good.
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 48 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACI6Lp0KU8XWscajAQ:-NAGPX124hT_9AMrBwsJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/test/regression/pthread_set_get_affinity.c#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not cpumask
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 109 at r7](https://reviewable.io/reviews/gramineproject/gramine/609#-NACImR4-0MBhuZaF3Bm:-NAGPBBNAn09PIsF8OOf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/fdca33d52846973262c0959c712fbea766d2d50d/libos/test/regression/pthread_set_get_affinity.c#L109)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is no point in wrapping this in a struct, you can pass it directly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 22:15 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGqMq96bVR4UL75mSs:-NAGpQ338jbeZoXVxy0B:b-dwvw0m) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L39)):*
> ```C
> 
>     cpu_set_t* thread_cpuaffinity = (cpu_set_t*)args;
>     cpu_set_t cpumask;
> ```

This needs to be cleared first.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 42 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGq8g358ffGWbUIfGa:-NAGq8g358ffGWbUIfGb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L42)):*
> ```C
>     CPU_SET(cpu, &cpumask);
>     CPU_AND(&cpumask, &cpumask, thread_cpuaffinity);
>     if (!CPU_COUNT(&cpumask)) {
> ```





_Suggestion:_
```C
    if (!CPU_ISSET(cpu, thread_cpuaffinity)) {
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGuhrB0GIdN0nie1bV:-NAGuhrB0GIdN0nie1bW:b19u9vo) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L64)):*
> ```C
>         CPU_OR(set_cpumask, set_cpumask, online_cpumask);
>         return 0;
>     }
> ```

All of this is not really useful, please remove it.



_Code quote:_
```C
    int online_cores_from_mask = CPU_COUNT(online_cpumask);
    if (online_cores_from_mask == 0)
        return -1;

    CPU_ZERO(set_cpumask);
    if (online_cores_from_mask <= 2) {
        CPU_OR(set_cpumask, set_cpumask, online_cpumask);
        return 0;
    }
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 107 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGse6v-A571cmWW3zA:-NAGse6v-A571cmWW3zB:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L107)):*
> ```C
>      * also set MANIFEST_SGX_THREAD_CNT to the same value.
>      */
>     long numthreads = min(online_cores, (MANIFEST_SGX_THREAD_CNT -
> ```





_Suggestion:_
```C
size_t
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGswU-CMb3pN_8ucfD:-NAGswU-CMb3pN_8ucfE:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L112)):*
> ```C
>     /* Each thread will be affinitized to run on 2 distinct cores. So reduce the number of threads
>      * to half of cores. */
>     numthreads = (numthreads >= 2) ? numthreads/2 : 1;
> ```





_Suggestion:_
```C
numthreads = MAX(numthreads / 2, 1);
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 124 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGt7u9CHZ0dF5-oJpN:-NAGt7u9CHZ0dF5-oJpO:b-a7maxt) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L124)):*
> ```C
>     }
> 
>     /* Validate parent set/get affinity for child */
> ```

Please move this comment before loop, or even remove it (it's not useful).
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 127 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtK19-Rf459Csp0iA:-NAGtK19-Rf459Csp0iB:bke6jvv) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L127)):*
> ```C
>     cpu_set_t* set_cpumask = malloc(numthreads * sizeof(*set_cpumask));
>     if (!set_cpumask) {
>         free(threads);
> ```

Actually, please remove all these `free` which are before `errx` - they are pointless anyway and just bloat the code.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 132 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtWFW9NF2AAkM3rGv:-NAGtWFX39rTuj49QeTp:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L132)):*
> ```C
> 
>     cpu_set_t get_cpumask;
>     for (long i = 0; i < numthreads; i++) {
> ```





_Suggestion:_
```C
size_t
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 141 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtlSP7w1xnUYsXGaY:-NAGtlSP7w1xnUYsXGaZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L141)):*
> ```C
>         }
> 
>         ret = pthread_create(&threads[i], NULL, dowork, (void*)&set_cpumask[i]);
> ```





_Suggestion:_
```C
&set_cpumask[i]
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 163 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGu7MyArGG2qclPE6P:-NAGu7MyArGG2qclPE6Q:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L163)):*
> ```C
>         }
> 
>         if (!CPU_EQUAL_S(sizeof(set_cpumask[i]), &set_cpumask[i], &get_cpumask)) {
> ```





_Suggestion:_
```C
if (!CPU_EQUAL(&set_cpumask[i], &get_cpumask)) {
```


<!-- Sent from Reviewable.io -->

2022-08-25 00:41 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: 5 of 6 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 39 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGqMq96bVR4UL75mSs:-NAHHo9I8h8ZnODmdfCg:b7l1f7r) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This needs to be cleared first.
</blockquote></details>

Using `CPU_ISSET` as suggested so this is not applicable as the variable itself is removed.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 42 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGq8g358ffGWbUIfGa:-NAHJ-0_56SGObNs55BZ:b-bd1hkw) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L42)):*
> ```C
>     CPU_SET(cpu, &cpumask);
>     CPU_AND(&cpumask, &cpumask, thread_cpuaffinity);
>     if (!CPU_COUNT(&cpumask)) {
> ```

Yes, this is better. Done. 
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 64 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGuhrB0GIdN0nie1bV:-NAHJBaJ9JQjyx7oZ98J:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All of this is not really useful, please remove it.
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 107 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGse6v-A571cmWW3zA:-NAHKUt59_w3WU5ObM3G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L107)):*
> ```C
>      * also set MANIFEST_SGX_THREAD_CNT to the same value.
>      */
>     long numthreads = min(online_cores, (MANIFEST_SGX_THREAD_CNT -
> ```

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 112 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGswU-CMb3pN_8ucfD:-NAHM1O17UoU-jiVPZfp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L112)):*
> ```C
>     /* Each thread will be affinitized to run on 2 distinct cores. So reduce the number of threads
>      * to half of cores. */
>     numthreads = (numthreads >= 2) ? numthreads/2 : 1;
> ```

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 124 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGt7u9CHZ0dF5-oJpN:-NAHM9311R119-uLkJl7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L124)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this comment before loop, or even remove it (it's not useful).
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 127 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtK19-Rf459Csp0iA:-NAHMj8553Za7aSendhP:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, please remove all these `free` which are before `errx` - they are pointless anyway and just bloat the code.
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 132 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtWFW9NF2AAkM3rGv:-NAHMoEU1rVP4OIgvG9y:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L132)):*
> ```C
> 
>     cpu_set_t get_cpumask;
>     for (long i = 0; i < numthreads; i++) {
> ```

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 141 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGtlSP7w1xnUYsXGaY:-NAHN1tQ6jbJU-WPSB2i:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L141)):*
> ```C
>         }
> 
>         ret = pthread_create(&threads[i], NULL, dowork, (void*)&set_cpumask[i]);
> ```

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 163 at r8](https://reviewable.io/reviews/gramineproject/gramine/609#-NAGu7MyArGG2qclPE6P:-NAHNHZVCZ6R-AfCqbhF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/5d440f0c4ab0a7de6994b546ab228ef4ee94409f/libos/test/regression/pthread_set_get_affinity.c#L163)):*
> ```C
>         }
> 
>         if (!CPU_EQUAL_S(sizeof(set_cpumask[i]), &set_cpumask[i], &get_cpumask)) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 07:02 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 16 at r9](https://reviewable.io/reviews/gramineproject/gramine/609#-NAInhNi5lYxDnnAxIsq:-NAInhNi5lYxDnnAxIsr:bx2u6zq) ([raw file](https://github.com/gramineproject/gramine/blob/1a5435a531fd8f836fd228fae211d93d5cdff203/libos/test/regression/pthread_set_get_affinity.c#L16)):*
> ```C
> #include <stdio.h>
> #include <stdlib.h>
> #include <sys/param.h>
> ```

FYI: I like this new version of the test!


<!-- Sent from Reviewable.io -->

2022-08-25 11:30 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-08-25 11:31 UTC, boryspoplawski commented
Jenkins, test this please

2022-08-25 19:19 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-08-25 19:20 UTC, boryspoplawski commented
Jenkins, test this please

2022-08-26 08:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/ubsan.c` line 130 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NAOIBG-7OhVyDN1b5Id:-NAOIBG-7OhVyDN1b5Ie:b-f201gu) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/common/src/ubsan.c#L130)):*
> ```C
>                        "null pointer returned from function declared to never return null")
> UBSAN_SIMPLE_HANDLER_1(invalid_builtin,
>                        "passing invalid argument to builtin %ld")
> ```

FYI: for history, Vijay added this handler because otherwise UBSan complained like this:
```
gramine/build/../libos/src/sys/libos_sched.c:283: undefined reference to `__ubsan_handle_invalid_builtin_abort'
```

This happens on this PR because the `pthread_get_set_affinity` LibOS regression test now uses `__builtin_ctzl()` GCC builtin function. And this function has special treatment in UBSan, see https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20170724/199351.html

So by adding this builtin, we glue our UBSan implementation with the common UBSan library, and when UBSan at compile-time looks at the `pthread_get_set_affinity` code, it can correctly instrument the `__builtin_ctzl()` function and add a check with a call to `__ubsan_handle_invalid_builtin_abort()`. (At least that's my general understanding of how it works, details may diverge.)


<!-- Sent from Reviewable.io -->

2022-09-06 10:05 UTC, mkow requested changes
> Reviewed 4 of 6 files at r4, 1 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 27 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHCT_rAV4Cyk7TyLc4:-NBHCT_rAV4Cyk7TyLc5:b-8sa4ga) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L27)):*
> ```C
> pthread_barrier_t barrier;
> 
> static void* dowork(void* args) {
> ```

(it was like this before, but please fix)



_Suggestion:_
```C
do_work
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 41 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHCQPfD0KrBbiN-bHD:-NBHCQPg9OJ5yn02cngc:bl8chhn) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L41)):*
> ```C
>     if (!CPU_ISSET(cpu, thread_cpuaffinity)) {
>         errx(EXIT_FAILURE, "cpu = %d is not part of thread %ld affinity mask", cpu,
>                             syscall(SYS_gettid));
> ```

wrong alignment
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 94 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHEssR4GqX41rvLEjZ:-NBHEssR4GqX41rvLEj_:b-lonj8b) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L94)):*
> ```C
>      * also set MANIFEST_SGX_THREAD_CNT to the same value.
>      */
>     size_t numthreads = MIN(online_cores, (MANIFEST_SGX_THREAD_CNT -
> ```

We usually move the trailing operator to the next line
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHF5EOCKN0FVJn4-Ws:-NBHF5EOCKN0FVJn4-Wt:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L117)):*
> ```C
>     cpu_set_t get_cpumask;
>     for (size_t i = 0; i < numthreads; i++) {
>         /* Find cores that will be affinitized to this thread. */
> ```





_Suggestion:_
```C
Select cores that will be affinitized to this thread.
```
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 120 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHF8IE5KYM0F_Br4ad:-NBHF8IE5KYM0F_Br4ae:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L120)):*
> ```C
>         ret = select_thread_cpu_affinity(&set_cpumask[i], &online_cpumask);
>         if (ret < 0) {
>             errx(EXIT_FAILURE, "Cannot find cores to affinitize threads");
> ```





_Suggestion:_
```C
Cannot select cores to affinitize threads
```


<!-- Sent from Reviewable.io -->

2022-09-06 14:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`libos/test/regression/pthread_set_get_affinity.c` line 27 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHCT_rAV4Cyk7TyLc4:-NBHyKIp4JjtzTZqMhkQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(it was like this before, but please fix)
</blockquote></details>

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 41 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHCQPfD0KrBbiN-bHD:-NBI-SrN3EY-2e1-Wf1n:b-mlrcup) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wrong alignment
</blockquote></details>

I have aligned to matching parenthesis. If this is incorrect, can you please suggest it? I am not too sure about this.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 94 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHEssR4GqX41rvLEjZ:-NBI0yB-1_WIrFdD33sL:bo3vl6y) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L94)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We usually move the trailing operator to the next line
</blockquote></details>

Thanks, done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 117 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHF5EOCKN0FVJn4-Ws:-NBI1BUl6Fbox_jnZChT:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L117)):*
> ```C
>     cpu_set_t get_cpumask;
>     for (size_t i = 0; i < numthreads; i++) {
>         /* Find cores that will be affinitized to this thread. */
> ```

Done.
___
*[`libos/test/regression/pthread_set_get_affinity.c` line 120 at r10](https://reviewable.io/reviews/gramineproject/gramine/609#-NBHF8IE5KYM0F_Br4ad:-NBI1LyuE9S5q3kQ-RcL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/405e2cef6a5fb2e44b996582eccd8038f5db3c29/libos/test/regression/pthread_set_get_affinity.c#L120)):*
> ```C
>         ret = select_thread_cpu_affinity(&set_cpumask[i], &online_cpumask);
>         if (ret < 0) {
>             errx(EXIT_FAILURE, "Cannot find cores to affinitize threads");
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 14:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-06 14:48 UTC, dimakuv commented
Jenkins, test this please

2022-09-06 14:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-06 17:02 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-09-06 18:01 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/609)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-06 18:02 UTC, dimakuv commented
Jenkins, test this please

2022-09-06 18:36 UTC, merged