[CI-Examples] Do not rebuild the rust example on reach run
gramineproject/gramine pull request #627
Opened 2022-06-02 15:43 UTC by boryspoplawski

## Description of the changes 
Previously Makefile rule running the example contained a dependency on the actual example app file. We use `cargo` to build it, but we do not track any dependencies (for simplicity). This resulted in `cargo build` being issued each time this example is run and sometimes caused timeouts in CI.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/627)

2022-06-02 15:49 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/627#-N3_5bBO4G2EdS5vJs3S:-N3_5bBP2aodO5oOcf4V:b56twp4) (no related file):*
Wait, why does `cargo` take so much time when there's nothing to be done? I don't like that `start-gramine-server` is missing a dependency now.
CC: @niedzejkob.

___


<!-- Sent from Reviewable.io -->

2022-06-02 16:46 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/627#-N3_5bBO4G2EdS5vJs3S:-N3_HDhyCaI9CjGNScmh:brfo064) (no related file):*
> Wait, why does cargo take so much time when there's nothing to be done? 

Normally it does not, but clearly sometimes it does, no idea why. Or is it `cargo` or our Jenkins machines...

> I don't like that start-gramine-server is missing a dependency now.

IMHO it is not missing anything. This is just a wrapper for spawning Gramine (basically it decides whether to use SGX version, based on env variables), it's in Makefile just for convenience.

___


<!-- Sent from Reviewable.io -->

2022-06-02 21:11 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2022-06-02 21:56 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/627#-N3_5bBO4G2EdS5vJs3S:-N3aPXhb3OTz7z7yxGDQ:b-ycnogv) (no related file):*
> Normally it does not, but clearly sometimes it does, no idea why. Or is it cargo or our Jenkins machines...

I'm somewhat perplexed as to what's happening during those 12 seconds, but I don't care enough to find out.

It seems like teaching Make when it needs to run Cargo is actually worth it, then. I'll open an alternative PR for that.

___


<!-- Sent from Reviewable.io -->

2022-06-03 07:13 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/627#-N3_5bBO4G2EdS5vJs3S:-N3cPI299HWc2tQ8vbRc:b4nshpa) (no related file):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

> Normally it does not, but clearly sometimes it does, no idea why. Or is it cargo or our Jenkins machines...

I'm somewhat perplexed as to what's happening during those 12 seconds, but I don't care enough to find out.

It seems like teaching Make when it needs to run Cargo is actually worth it, then. I'll open an alternative PR for that.
</blockquote></details>

So we're closing this PR in favor of #628 ?

___


<!-- Sent from Reviewable.io -->

2022-06-03 17:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/627)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/627#-N3_5bBO4G2EdS5vJs3S:-N3eE-u-DIzYPktFshG0:b-sdbg58) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So we're closing this PR in favor of #628 ?
</blockquote></details>

If it looks good (haven't check it yet), then yes.
Otoh while we are here we could decide what are the intended semantics of `make gramine-start-server` (we have it in may places) - should it rebuild the example if needed or not? I think it can, assuming we have good deps tracking (which we should have after the other PR)

___


<!-- Sent from Reviewable.io -->

2022-06-03 19:18 UTC, closed without merging