[LibOS] Emulate get cpu affinity
gramineproject/gramine pull request #631
Opened 2022-06-03 07:37 UTC by vijaydhanraj

## Description of the changes 
This commit stores per thread cpu affinity in the LibOS and returns it when queried from the user after validation. This is done as the cpu affinity returned from the host cannot be trusted.

## How to test this PR? 
Please run `LibOS` and `PAL` regression tests.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/631)

2022-06-03 11:41 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 0 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKQvgEy3ziy0Gpx-k):*




_Suggestion:_
```
Emulate CPU affinity in LibOS
```
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dK_hk5yr85OZ22A1B:-N3dK_hk5yr85OZ22A1C:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
> ```objc
>     struct shim_lock lock;
> 
>     /* Current cpu affinity mask for this thread. CPU Affinity for 2048 cores can be supported. */
> ```





_Suggestion:_
```objc
CPU affinity up to 2048
```
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKctf4N3gqx02XzXB:-N3dKctf4N3gqx02XzXC:b-sis0vf) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
> ```objc
>     struct shim_lock lock;
> 
>     /* Current cpu affinity mask for this thread. CPU Affinity for 2048 cores can be supported. */
> ```

Please unify casing everywhere in this PR, you seem to be choosing lower/upper case randomly.



_Suggestion:_
```objc
CPU
```
___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N3dMKX18u1-Q2vK9a_7:b-zhdcgu) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
> ```objc
>  *                is validated first before the update.
>  *
>  * \param cpumask_size Size (in bytes) of the cpumask. This is set to 0, when the mask needs to be
> ```

Why is this size in bytes when `cpumask` is an array of `unsigned long`s? This makes no sense...



_Code quote:_
```objc
Size (in bytes) of the cpumask
```
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLseA4dn_HpQrK5nX:-N3dLseA4dn_HpQrK5nY:b-3945xf) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
> ```objc
>  *
>  * \param cpumask_size Size (in bytes) of the cpumask. This is set to 0, when the mask needs to be
>  *                     obtained from the untrusted host.
> ```

Please format (see our docs)
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N3dMWCcDacsTtor-Eze:b4fesfk) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
> ```
> This is set to 0, when the mask needs to be obtained from the untrusted host.
> ```

This semantic is super obscure, please remove this weird case from here.
___
*[`LibOS/shim/include/shim_thread.h` line 355 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLqc6BQDLlfAS6ct0:-N3dLqc6BQDLlfAS6ct1:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L355)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_cpuaffinity_mask(struct shim_thread* cur_thread, unsigned int cpumask_size,
> ```





_Suggestion:_
```objc
thread
```
___
*[`LibOS/shim/include/shim_thread.h` line 355 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLz8pE4ndxE0mINea:-N3dLz8pE4ndxE0mINeb:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L355)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_cpuaffinity_mask(struct shim_thread* cur_thread, unsigned int cpumask_size,
> ```





_Suggestion:_
```objc
size_t
```


<!-- Sent from Reviewable.io -->

2022-06-03 15:20 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 0 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKQvgEy3ziy0Gpx-k):*
Blocking myself. Will do this before the final rebase.
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dK_hk5yr85OZ22A1B:-N3dxowT3N13NupyqM9Z:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
> ```objc
>     struct shim_lock lock;
> 
>     /* Current cpu affinity mask for this thread. CPU Affinity for 2048 cores can be supported. */
> ```

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKctf4N3gqx02XzXB:-N3dyePH97i1o73NYusb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please unify casing everywhere in this PR, you seem to be choosing lower/upper case randomly.
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N3e-WuxBDYfzZRlfar_:beudvxx) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this size in bytes when `cpumask` is an array of `unsigned long`s? This makes no sense...
</blockquote></details>

These are the types for set/get affinity function, and they do pass cpumask size in bytes and the cpu affinity as `unsigned long`. I have kept the same types for this function as well.

https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html (note: `cpu_set_t ` is array of unsigned longs). Also in our code, https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_sched.c#L143

Any suggestions? 
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N3e0GNz7Ud5fnDWqw9s:b2crg29) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> This is set to 0, when the mask needs to be obtained from the untrusted host.
> ```

This semantic is super obscure, please remove this weird case from here.
</blockquote></details>

This function handles 2 cases 1) to get affinity and then update the `thread->cpumask` and 2) directly update the `thread->cpumask` with values passed to it. For the 1st case, we do pass `cpumask_size` as `0`. Felt this might need more documentation and added it.

But it looks like this is self-explanatory for the code. I have removed it.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLseA4dn_HpQrK5nX:-N3e3mAZA1rj662dE5Le:b92lxuc) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please format (see our docs)
</blockquote></details>

Have aligned the parameters as in https://gramine.readthedocs.io/en/latest/devel/howto-doc.html#preferred-doxygen-style. Please let me know if I missed anything.
___
*[`LibOS/shim/include/shim_thread.h` line 355 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLqc6BQDLlfAS6ct0:-N3e4CER1cbcdu_L2HP9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L355)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_cpuaffinity_mask(struct shim_thread* cur_thread, unsigned int cpumask_size,
> ```

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 355 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLz8pE4ndxE0mINea:-N3e4g9XCG-EePk4IBwL:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L355)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_cpuaffinity_mask(struct shim_thread* cur_thread, unsigned int cpumask_size,
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 07:41 UTC, dimakuv requested changes
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 135 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wyBQn6mU_MQYBpSWo:-N3wyBQn6mU_MQYBpSWp:bczgb4f) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L135)):*
> ```objc
>     struct shim_lock lock;
> 
>     /* Current CPU affinity mask for this thread. CPU Affinity up to 2048 cores can be supported. */
> ```

`CPU Affinity up to` -> `CPU affinity up to` (small letter `a`)
___
*[`LibOS/shim/include/shim_thread.h` line 136 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wyMrm8BYH9zy98Re9:-N3wyMrm8BYH9zy98ReA:b-8931km) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L136)):*
> ```objc
> 
>     /* Current CPU affinity mask for this thread. CPU Affinity up to 2048 cores can be supported. */
>     uint64_t cpumask[32];
> ```

Actually, can we move this new field before `ref_count` and `lock`? Those two fields are logically the "last ones".
___
*[`LibOS/shim/include/shim_thread.h` line 347 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wzGJh7TpdaNXQNW5H:-N3wzGJh7TpdaNXQNW5I:beraewf) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L347)):*
> ```objc
>  *
>  * \param cpumask       If NULL, CPU affinity is obtained from the host and then updated to thread
>  *                      else the mask that is passed from untrusted host is updated. In both cases
> ```

`else the mask that is passed from untrusted host is updated` -- this doesn't sound right.

Are we talking about case 2, when `thread->cpu_mask` is directly updated by the value of `cpumask`? If yes, then I suggest to rephrase to:
```
else this mask is used to update the thread's current mask.
```
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 139 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x1eeg6bEToPDt1whZ:-N3x1eeg6bEToPDt1wh_:b-zgzba0) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L139)):*
> ```C
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(threads_cnt) * sizeof(unsigned long);
> 
>     memset(thread->cpumask, 0, sizeof(thread->cpumask));
> ```

Please don't update `thread->cpumask` here, before you do any operations. It is a bad smell to have side-effects in case of errors (which can happen in the current case). Please move this line right-before the final memcpy.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x1uHk3-_ddi0Yzscg:-N3x1uHlEhq5tpNoINGD:bbt3p12) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
> ```C
>     memset(thread->cpumask, 0, sizeof(thread->cpumask));
> 
>     if (!cpumask_size) {
> ```

Why do you care about `cpumask_size`? In reality, you should check whether `cpumask == NULL`. I suggest to rewrite like this:
```
if (!cpumask) {
    assert(cpumask_size == 0);
    ...
```
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x52-Z2J7SBPjHREqw:-N3x52-Z2J7SBPjHREqx:b47e2yh) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
> ```C
>         if (!cpumask)
>             return -ENOMEM;
> ```

As I mentioned in the another comment, you should just add a new helper bool. And then you can also update `cpumask_size` here:
```
cpumask_allocated = true;
cpumask_size = bitmask_size_in_bytes;
```

This will make all the rest of the logic in this function much simpler.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x3F3pAoQt2zfRiMZM:-N3x3F3pAoQt2zfRiMZN:b-tpqpco) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L154)):*
> ```C
>     }
> 
>     /* Verify the cpu affinity from untrusted host */
> ```

`Verify validity of the CPU affinity (e.g., that it contains at least one online core)`
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 168 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x5PYP0fGvmsIz_1cD:-N3x5PYQ0oz44bp1l8KA:b-a8dg4o) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L168)):*
> ```C
> 
>     size_t idx = 0;
>     for (size_t i = 0; i < cnt; i++) {
> ```

Instead of calculating `cnt` above, you can simply do it here as:
```
for (size_t i = 0; i < MIN(threads_cnt, cpumask_size * BITS_IN_BYTE); i++) {
```
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x4ZRn18dphbvK7srt:-N3x4ZRn18dphbvK7sru:bu0c54) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L173)):*
Why do you fail with error?

`man sched_setaffinity` says:

> After  a  call to sched_setaffinity(), the set of CPUs on which the thread will actually run is the intersection of the set specified in the mask argument and the set of CPUs actually present on the system.

Also about the `EINVAL`:

> The affinity bit mask mask contains no processors that are currently physically on the system ...

So, you're not supposed to fail. You're supposed to clean this bit in the final `thread->cpumask`.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 179 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x5fuaEFF6YRWEaXx7:-N3x5fuaEFF6YRWEaXx8:b-3u0xr4) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L179)):*
> ```C
>     }
> 
>     memcpy(thread->cpumask, cpumask, mask_size);
> ```

Instead of introducing a new variable `mask_size`, you could simply use `cpumask_size` here.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 186 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x2dcK5WdCn-_aezSG:-N3x2dcL4bLUwEC6M4zF:b-rhf98z) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L186)):*
> ```C
>         free(cpumask);
>         cpumask = NULL;
>     }
> ```

First of all, `cpumask = NULL` is redundant and useless. Just remove it.

Second of all, the logic "if user-supplied mask size is zero, then I must have allocated the cpumask internally and now must free it" is very contrived. I suggest to add a `bool cpumask_allocated = false` and set it to true after `malloc()` and check for it here. A bit more verbose, but much more user-friendly.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 282 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x00ie06YQH9uTuQRX:-N3x00if9VTpsQ6v71s7:b-4llj1) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L282)):*
> ```C
>     add_thread(cur_thread);
> 
>     ret = update_thread_cpuaffinity_mask(cur_thread, 0, NULL);
> ```

Here and everywhere: please add arg names `...my_thread, /*cpumask_size=*/0, /*cpumask=*/NULL);`
___
*[`LibOS/shim/src/bookkeep/shim [...]

2022-06-07 12:32 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dK_hk5yr85OZ22A1B:-N3y8MEQ4gyk1RgBZs25:bfhqml6) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKctf4N3gqx02XzXB:-N3y8_xK9FzxazvfB4zq:bfhqml6) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N3y7djaE_dnQahlrbLh:b-igu7hl) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

These are the types for set/get affinity function, and they do pass cpumask size in bytes and the cpu affinity as `unsigned long`. I have kept the same types for this function as well.

https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html (note: `cpu_set_t ` is array of unsigned longs). Also in our code, https://github.com/gramineproject/gramine/blob/master/LibOS/shim/src/sys/shim_sched.c#L143

Any suggestions? 
</blockquote></details>

This makes little sense here. As a reader/user of this function it's super hard to guess what's the semantics of it (e.g. can I pass 3-bytes long mask?). The syscalls have such signatures to make the parameter security checks easier, here you don't have such an argument.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N3y7Fzb7IdjndmyeSpg:b-d3hft3) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
> This function handles 2 cases

I know, that's what I mean. This is actually a mixture of two independent functionalities, selected by a magic value in one of the arguments, which is really obscure.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLseA4dn_HpQrK5nX:-N3y8BtG6v-yCzt_MsDa:b-p1w4ue) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Have aligned the parameters as in https://gramine.readthedocs.io/en/latest/devel/howto-doc.html#preferred-doxygen-style. Please let me know if I missed anything.
</blockquote></details>

Yes, you added empty lines between them. Please read the example in the docs carefully.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x4ZRn18dphbvK7srt:-N3y7-dD5s8bAX9Tk5cg:b13wzth) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you fail with error?

`man sched_setaffinity` says:

> After  a  call to sched_setaffinity(), the set of CPUs on which the thread will actually run is the intersection of the set specified in the mask argument and the set of CPUs actually present on the system.

Also about the `EINVAL`:

> The affinity bit mask mask contains no processors that are currently physically on the system ...

So, you're not supposed to fail. You're supposed to clean this bit in the final `thread->cpumask`.
</blockquote></details>

Or rather: fail only when the intersection is empty.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x5p6B-8xpok_6m-v-:-N3y6cKz7iHcgssVNlno:b-geslgl) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/sys/shim_sched.c#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to take a lock `lock(thread->lock)` before calling this function and release the lock after it.

Reason: `shim_do_sched_setaffinity()` modifies `thread->cpumask` field. You have no locking that would protect this field currently. So if two threads call this function simulteneously with the same `pid`, then your `thread->cpumask` may get tangled.
</blockquote></details>

Would be nice to add `assert(locked(...))` to `update_thread_cpuaffinity_mask()` then.


<!-- Sent from Reviewable.io -->

2022-06-07 14:14 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x4ZRn18dphbvK7srt:-N3yHutZERysLIeBAHld:bpevfmj) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L173)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Or rather: fail only when the intersection is empty.
</blockquote></details>

Yes, that's what I meant, Michal is right.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 172 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x5p6B-8xpok_6m-v-:-N3yVtkY9c1bR5K9eQU9:b-9y56oq) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/sys/shim_sched.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Would be nice to add `assert(locked(...))` to `update_thread_cpuaffinity_mask()` then.
</blockquote></details>

@mkow We can't/shouldn't. Because this function is called also in the "thread creation" functions, where there is no need to take the lock (or the function may be called even before the thread lock is created). So I think we shouldn't put this restriction here.


<!-- Sent from Reviewable.io -->

2022-06-08 10:33 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 0 of 4 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dK_hk5yr85OZ22A1B:-N40X1XtEsnYfcKR4KHD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKctf4N3gqx02XzXB:-N40b4eXAaeWjS_rD8h-:bfhmd2k) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

yes missed 2 places in `shim_thread.c` file. Blocked myself and will check again before the final rebase as well.
___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N41guQ7E5FCabhG2mX0:biy9ube) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This makes little sense here. As a reader/user of this function it's super hard to guess what's the semantics of it (e.g. can I pass 3-bytes long mask?). The syscalls have such signatures to make the parameter security checks easier, here you don't have such an argument.
</blockquote></details>

@mkow @dimakuv How do we want to proceed here? Is the current implementation better?
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dLseA4dn_HpQrK5nX:-N40csll2s4901WYZMUT:b-gw19pv) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, you added empty lines between them. Please read the example in the docs carefully.
</blockquote></details>

ah I see, removed the empty lines.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N41j2V04L73JgKrv4Jk:biljqfp) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I was fine with a single function. But Michal is in favor of 2 functions, so let's do 2 functions. Will be clearer for sure.
</blockquote></details>

I have created 2 functions 1) `set_host_thread_cpuaffinity_mask` which only takes `shim_thread*` as argument. This function reads the CPU affinity from the host and updates the thread cpumask and 2) `set_user_thread_cpuaffinity_mask` which takes the user supplied `cpumask` and `cpumask_size` and updates the thread cpumask.

We validate both the masks in a slightly different way for each of the functions.
___
*[`LibOS/shim/include/shim_thread.h` line 135 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wyBQn6mU_MQYBpSWo:-N40XH67Dc63zOfx0I9w:b-n4gsgw) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`CPU Affinity up to` -> `CPU affinity up to` (small letter `a`)
</blockquote></details>

Thanks, missed it earlier.
___
*[`LibOS/shim/include/shim_thread.h` line 136 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wyMrm8BYH9zy98Re9:-N40c0qeC4hsqyHU85Wd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, can we move this new field before `ref_count` and `lock`? Those two fields are logically the "last ones".
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 347 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3wzGJh7TpdaNXQNW5H:-N41mqtY3KBrc2CS8Dtp:bmdw7i5) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/include/shim_thread.h#L347)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`else the mask that is passed from untrusted host is updated` -- this doesn't sound right.

Are we talking about case 2, when `thread->cpu_mask` is directly updated by the value of `cpumask`? If yes, then I suggest to rephrase to:
```
else this mask is used to update the thread's current mask.
```
</blockquote></details>

not applicable.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 139 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x1eeg6bEToPDt1whZ:-N40gV7C9MLEAK2GEjVu:b-qy3qbu) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't update `thread->cpumask` here, before you do any operations. It is a bad smell to have side-effects in case of errors (which can happen in the current case). Please move this line right-before the final memcpy.
</blockquote></details>

yes, done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x1uHk3-_ddi0Yzscg:-N41j8Eo9CjykQoeXQDD:bvik6kq) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you care about `cpumask_size`? In reality, you should check whether `cpumask == NULL`. I suggest to rewrite like this:
```
if (!cpumask) {
    assert(cpumask_size == 0);
    ...
```
</blockquote></details>

As discussed, split into 2 functions and now we no longer need to check the `cpumask_size`
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x52-Z2J7SBPjHREqw:-N41jULM5mNIGCtoT4GD:bnavnjv) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As I mentioned in the another comment, you should just add a new helper bool. And then you can also update `cpumask_size` here:
```
cpumask_allocated = true;
cpumask_size = bitmask_size_in_bytes;
```

This will make all the rest of the logic in this function much simpler.
</blockquote></details>

I don't think this is applicable to the new implementation.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 154 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x3F3pAoQt2zfRiMZM:-N40gopp4xgMczmS_Vlh:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i>< [...]

2022-06-09 10:09 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N46rxH6Dx1Vee97LDy-:b32d42u) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow @dimakuv How do we want to proceed here? Is the current implementation better?
</blockquote></details>

I was actually fine with the current logic: size in bytes, cpumask in ulongs...

I will let Michal decide how exactly he wants the args to be.
___
*[`LibOS/shim/include/shim_thread.h` line 348 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46s6Wz30HRqLrcbBjG:-N46s6Wz30HRqLrcbBjH:b-59qjoa) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L348)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int set_host_thread_cpuaffinity_mask(struct shim_thread* thread);
> ```

I don't like the names, they are hard to understand. "Set the thread's CPU mask on the host"? That's not what this function does, but the name implies it.

I suggest `init_thread_cpuaffinity_mask_from_host`. Long, but tells exactly what this func does.
___
*[`LibOS/shim/include/shim_thread.h` line 360 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46sb6K0d1Qntp_xa1f:-N46sb6K0d1Qntp_xa1g:bj4o72c) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L360)):*
> ```objc
>  */
> int set_user_thread_cpuaffinity_mask(struct shim_thread* thread, size_t cpumask_size,
>                                      unsigned long* cpumask);
> ```

I suggest a name `update_thread_cpuaffinity_mask`
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 173 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x4ZRn18dphbvK7srt:-N46wBXX54S2-SQ1k5V-:b-nzjxle) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/bookkeep/shim_thread.c#L173)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

When we initialize the `thread->cpumask` with the cpumask returned from the host, I think we should fail if the host returned a cpumask containing offlined core.

We can see this from my test where I offlined a few cores (32-48) and called the pthread_getaffinity_np/sched_getaffinity. The cpumask doesn't contain any offlined cores.

```
Default thread affinity using pthread_getaffinity_np: cpumask[0] = 0xfffe0000ffffffff, cpumask[1] = 0xffffffffffffffff
Default thread affinity using sched_getaffinity: cpumask[0] = 0xfffe0000ffffffff, cpumask[1] = 0xffffffffffffffff
```

But do agree that when the user passes a cpumask using pthread_setaffinity_np/sched_setaffinity, it can contain offlined cores but we simply remove the offlined cores before updating `thread->cpumask`.

```
pthread_setaffinity_np: numprocs = 128, cpumask[0] = 0xffffffffffffffff, cpumask[1] = 0xffffffffffffffff
pthread_getaffinity_np: numprocs = 128, cpumask[0] = 0xfffe0000ffffffff, cpumask[1] = 0xffffffffffffffff
sched_setaffinity: numprocs = 128, cpumask[0] = 0xffffffffffffffff, cpumask[1] = 0xffffffffffffffff
sched_getaffinity: numprocs = 128, cpumask[0] = 0xfffe0000ffffffff, cpumask[1] = 0xffffffffffffffff
```

Please let me know what you think.
</blockquote></details>

OK, I like your approach. You're correct, your current logic is good.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 134 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46tlDPD0ZfTTCCFSnb:-N46tlDPD0ZfTTCCFSnc:b-nidn3o) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L134)):*
> ```C
> 
> int set_host_thread_cpuaffinity_mask(struct shim_thread* thread) {
>     assert(locked(&thread->lock));
> ```

No need for this anymore in this function, please see my other comments.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46uLdo5YPEHr5nGdEO:-N46uLdp4mjljO5v38gd:b-epcpvx) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L139)):*
> ```C
>     size_t threads_cnt = g_pal_public_state->topo_info.threads_cnt;
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(threads_cnt) * sizeof(unsigned long);
> ```

Your `thread->cpumask` is only 32 bytes long, which means 2048 CPU threads max. Without additional checks on this limit, your `memcpy()` at the end of this function may overflow the `thread->cpumask` buffer.

So please add smth like this here:
```
if (bitmask_size_in_bytes > sizeof(thread->cpumask)) {
    log_error("Current platform has more cores (%lu) than Gramine can support in cpumask (%lu)",
              threads_cnt, sizeof(thread->cpumask) * BITS_IN_BYTE);
    return -EOVERFLOW;
}
```
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46vgoI-XS7Vy6UlAtY:-N46vgoI-XS7Vy6UlAtZ:bzf8uib) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L187)):*
> ```C
>         if (cpumask[idx] & 1UL << (i % BITS_IN_TYPE(unsigned long))) {
>             if (!g_pal_public_state->topo_info.threads[i].is_online) {
>                 /* cpumask contains a CPU that is currently offline, remove it from the cpumask*/
> ```

Please add a space before `*/`
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 195 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46vtxK22zjkPvkjjdL:-N46vtxK22zjkPvkjjdM:bg14bju) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L195)):*
> ```C
>     }
> 
>     /* Intersection of offlined cores and the user supplied mask is empty so return an error. */
> ```

`offlined` -> `online`

Also please remove `so return an error` -- it is obvious from the code
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 297 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46thvw-FeRpINwhgeq:-N46thvw-FeRpINwhger:bvbpobb) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L297)):*
> ```C
>     add_thread(cur_thread);
> 
>     lock(&cur_thread->lock);
> ```

You don't need locking anymore because you're using the function (`set_host_thread_cpuaffinity_mask`) that is only called during thread initialization. So there are no other users/threads that could access `thread->cpu_mask` simulteneously. Thus, no need for locking around this function.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46svBe7zP2SsuPKxSi:-N46svBe7zP2SsuPKxSj:bvbpobb) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/sys/shim_clone.c#L87)):*
> ```C
>     add_thread(my_thread);
> 
>     lock(&my_thread->lock);
> ```

You don't need locking anymore because you're using the function (`set_host_thread_cpuaffinity_mask`) that is only called during thread initialization. So there are no other users/threads that could access `thread->cpu_mask` simulteneously [...]

2022-06-10 06:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 1 of 4 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46s6Wz30HRqLrcbBjG:-N4B43oNDbq9hCIlvG_u:b7hetid) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the names, they are hard to understand. "Set the thread's CPU mask on the host"? That's not what this function does, but the name implies it.

I suggest `init_thread_cpuaffinity_mask_from_host`. Long, but tells exactly what this func does.
</blockquote></details>

How about we remove the mask and call it `init_thread_cpuaffinit_from_host`? And call the other function `set_thread_cpuaffinity_from_user`?
___
*[`LibOS/shim/include/shim_thread.h` line 360 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46sb6K0d1Qntp_xa1f:-N4B4pqxB86ZIt7JkPH2:be9ul3q) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest a name `update_thread_cpuaffinity_mask`
</blockquote></details>

I prefer to add `user` suffix to the function name as the cpuaffinity we update is from the user and is also closer in naming style to the other function. So, propose `set_thread_cpuaffinity_from_user` or `update_thread_cpuaffinity_from_user`. Wdyt?
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 134 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46tlDPD0ZfTTCCFSnb:-N4B8_-z0TZcUm7jB9_G:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for this anymore in this function, please see my other comments.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 139 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46uLdo5YPEHr5nGdEO:-N4AvpsPEZAJ8X6-v6Zy:b-83fpoa) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Your `thread->cpumask` is only 32 bytes long, which means 2048 CPU threads max. Without additional checks on this limit, your `memcpy()` at the end of this function may overflow the `thread->cpumask` buffer.

So please add smth like this here:
```
if (bitmask_size_in_bytes > sizeof(thread->cpumask)) {
    log_error("Current platform has more cores (%lu) than Gramine can support in cpumask (%lu)",
              threads_cnt, sizeof(thread->cpumask) * BITS_IN_BYTE);
    return -EOVERFLOW;
}
```
</blockquote></details>

Good catch, you are right. I have added the check.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 187 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46vgoI-XS7Vy6UlAtY:-N4Ay8wl6M2poo-QogYM:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space before `*/`
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 195 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46vtxK22zjkPvkjjdL:-N4AyVd421gJz5s7kNYv:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L195)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`offlined` -> `online`

Also please remove `so return an error` -- it is obvious from the code
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 297 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46thvw-FeRpINwhgeq:-N4B8WMk8f3-ydXiVf_p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/bookkeep/shim_thread.c#L297)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need locking anymore because you're using the function (`set_host_thread_cpuaffinity_mask`) that is only called during thread initialization. So there are no other users/threads that could access `thread->cpu_mask` simulteneously. Thus, no need for locking around this function.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46svBe7zP2SsuPKxSi:-N4AyycV1xH6JWteCvJG:b-fjnwl5) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/src/sys/shim_clone.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need locking anymore because you're using the function (`set_host_thread_cpuaffinity_mask`) that is only called during thread initialization. So there are no other users/threads that could access `thread->cpu_mask` simulteneously. Thus, no need for locking around this function.
</blockquote></details>

Yes, agree there is no contention here as it is only called during thread initialization.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 219 at r2](https://reviewable.io/reviews/gramineproject/gramine/631#-N3x68N5AJ6pxuHic8s_:-N4B2bPb5FXj2m4PBPAX:b8kji1f) ([raw file](https://github.com/gramineproject/gramine/blob/157ea817a0dc549309654ba68f52a38231d3f165/LibOS/shim/src/sys/shim_sched.c#L219)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

ah my bad, done.


<!-- Sent from Reviewable.io -->

2022-06-10 07:30 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46s6Wz30HRqLrcbBjG:-N4BVjra7uHhyuWtkzGK:b-boye7i) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about we remove the mask and call it `init_thread_cpuaffinit_from_host`? And call the other function `set_thread_cpuaffinity_from_user`?
</blockquote></details>

Ok, yes, these names sound good to me. Please use them. But as you proposed, for the second function I prefer `update_thread_cpuaffinity_from_user`.
___
*[`LibOS/shim/include/shim_thread.h` line 360 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46sb6K0d1Qntp_xa1f:-N4BVq4901ior85_871w:b-vb71l0) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L360)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I prefer to add `user` suffix to the function name as the cpuaffinity we update is from the user and is also closer in naming style to the other function. So, propose `set_thread_cpuaffinity_from_user` or `update_thread_cpuaffinity_from_user`. Wdyt?
</blockquote></details>

Yes, I like `update_thread_cpuaffinity_from_user`.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r4](https://reviewable.io/reviews/gramineproject/gramine/631#-N4BW5vM7EZi73p3UA4m:-N4BW5vN1_FpsbicT42S:b8us9o) ([raw file](https://github.com/gramineproject/gramine/blob/2be82265eb307117e5d30b76e2c38d056d3bb08b/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
> ```C
>     if (bitmask_size_in_bytes > sizeof(thread->cpumask)) {
>         log_error("Current platform has more cores (%lu) than Gramine can support in cpumask (%lu)",
>               threads_cnt, sizeof(thread->cpumask) * BITS_IN_BYTE);
> ```

Please re-align


<!-- Sent from Reviewable.io -->

2022-06-13 03:32 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 0 of 4 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46s6Wz30HRqLrcbBjG:-N4Q35D645Mv5yZwZqv8:bs7wumb) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, yes, these names sound good to me. Please use them. But as you proposed, for the second function I prefer `update_thread_cpuaffinity_from_user`.
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 360 at r3](https://reviewable.io/reviews/gramineproject/gramine/631#-N46sb6K0d1Qntp_xa1f:-N4Q38La8j4OG-I6i_iP:b-a384qa) ([raw file](https://github.com/gramineproject/gramine/blob/729c7f55ec6088508b20f54e2cb2d1e2d104d019/LibOS/shim/include/shim_thread.h#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I like `update_thread_cpuaffinity_from_user`.
</blockquote></details>

yes done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r4](https://reviewable.io/reviews/gramineproject/gramine/631#-N4BW5vM7EZi73p3UA4m:-N4Q3gXlDx4NbXUVxo8f:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2be82265eb307117e5d30b76e2c38d056d3bb08b/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-align
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 07:28 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r5](https://reviewable.io/reviews/gramineproject/gramine/631#-N4Qx-xv39J9yYFLJS6O:-N4Qx-xv39J9yYFLJS6P:b-41h0j) ([raw file](https://github.com/gramineproject/gramine/blob/6c91bc3fb807cb9d542d2c7b32f32bb7b9031984/LibOS/shim/include/shim_thread.h#L348)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int init_thread_cpuaffinit_from_host(struct shim_thread* thread);
> ```

`init_thread_cpuaffinit_from_host` -> `init_thread_cpuaffinity_from_host` (missed the `y`)


<!-- Sent from Reviewable.io -->

2022-06-13 23:16 UTC, mkow requested changes
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 2 of 4 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4UH_vZ9hiexLgZxKiy:b-ekjg2u) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
> Is the current implementation better?

But you did not change the arguments. Please just pass array + its length, as all code everywhere does, instead of this weird convention.
___
*[`LibOS/shim/include/shim_thread.h` line 348 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4ULPTTBpNWDWhzPTTw:-N4ULPTTBpNWDWhzPTTx:bd868hk) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L348)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int init_thread_cpuaffinity_from_host(struct shim_thread* thread);
> ```

(or if you really want to keep that "cpu", then add underscore afterwards)



_Suggestion:_
```objc
init_thread_affinity_from_host
```
___
*[`LibOS/shim/include/shim_thread.h` line 354 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIEpd6Z2gddrEhyx-:-N4UIEpd6Z2gddrEhyx0:b228yug) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L354)):*
> ```objc
>  *
>  * \param thread        Thread whose CPU affinity needs to be updated.
>  * \param cpumask       CPU affinity mask passed from the user.
> ```

What does this mean?



_Code quote:_
```objc
from the user
```
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIH_x7RNuHnCQKBlW:-N4UIH_x7RNuHnCQKBlX:bmvw6g9) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L359)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_cpuaffinity_from_user(struct shim_thread* thread, size_t cpumask_size,
> ```

Why not just `set_thread_affinity`?
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 155 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UKebf6VhM9bEuhfN8:-N4UKebf6VhM9bEuhfN9:bqbn7z1) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/src/bookkeep/shim_thread.c#L155)):*
> ```C
>         goto out;
>     }
> ```

Doesn't this code belong to PAL, in particular: PAL/Linux-SGX? We do +/- all other sanitizations in there.



_Code quote:_
```C
/* Verify validity of the CPU affinity (e.g., that it contains at least one online core) */
```


<!-- Sent from Reviewable.io -->

2022-06-14 19:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 2 of 4 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4XLBJM-yTKn1velExz:b-lt3gyy) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Is the current implementation better?

But you did not change the arguments. Please just pass array + its length, as all code everywhere does, instead of this weird convention.
</blockquote></details>

This is tricky because the end-user can pass a `cpumask` pointer but can provide a size that is lesser than the `cpumask`. Linux doesn't fail for such cases for `sched_setaffinity`. Because of this, we cannot get the correct `cpumask` size and might not set the affinity the end-user actually intended. Secondly, this isn't a static array so we cannot use our macros like `ARRAY_SIZE` to determine the actual length of the array.

For example, with the below code our current implementation will always choose 2 cpus between `0-31` (numprocs = 2 in this case) but if we don't use the `4` bytes passed from the user, we may not be able to use the right affinity. 

```
diff --git a/LibOS/shim/test/regression/pthread_set_get_affinity.c b/LibOS/shim/test/regression/pthread_set_get_affinity.c
index e3ffecbee..be49d96fd 100644
--- a/LibOS/shim/test/regression/pthread_set_get_affinity.c
+++ b/LibOS/shim/test/regression/pthread_set_get_affinity.c
@@ -69,6 +69,9 @@ int main(int argc, const char** argv) {
     for (long i = 0; i < numprocs; i++) {
         CPU_ZERO(&cpus);
         CPU_ZERO(&get_cpus);
+        for (int j = 3; j < 128; j++)
+            CPU_SET(j, &cpus);
+
         CPU_SET(i*2, &cpus);
 
         ret = pthread_create(&threads[i], NULL, dowork, (void*)&iterations);
@@ -77,7 +80,7 @@ int main(int argc, const char** argv) {
             errx(EXIT_FAILURE, "pthread_create failed!");
         }
 
-        ret = pthread_setaffinity_np(threads[i], sizeof(cpus), &cpus);
+        ret = pthread_setaffinity_np(threads[i], 4, &cpus);
         if (ret != 0) {
             free(threads);
             errx(EXIT_FAILURE, "pthread_setaffinity_np failed for child!");
@@ -89,7 +92,7 @@ int main(int argc, const char** argv) {
             errx(EXIT_FAILURE, "pthread_getaffinity_np failed for child!");
         }
 
-        if (!CPU_EQUAL_S(sizeof(cpus), &cpus, &get_cpus)) {
+        if (!CPU_EQUAL_S(4, &cpus, &get_cpus)) {
             free(threads);
             errx(EXIT_FAILURE, "get cpuset is not equal to set cpuset on proc: %ld", i);
         }
```
___
*[`LibOS/shim/include/shim_thread.h` line 348 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4ULPTTBpNWDWhzPTTw:-N4X8M9Z9Xm8P7JalcTc:b-96xrei) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(or if you really want to keep that "cpu", then add underscore afterwards)
</blockquote></details>

Changed to `init_thread_affinity_from_host`.
___
*[`LibOS/shim/include/shim_thread.h` line 354 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIEpd6Z2gddrEhyx-:-N4X8euC5pYB14p9jiiS:bhm4ei1) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L354)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What does this mean?
</blockquote></details>

By `user` I mean the end-user who tries to set/update thread affinity by calling `sched_setaffinity` function from their application. Instead of `user` would `application` be more clear?
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIH_x7RNuHnCQKBlW:-N4XyuxAAajnlPzWon53:byjre5v) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just `set_thread_affinity`?
</blockquote></details>

@dimakuv preferred to use `update` so I changed this to `update_thread_affinity_from_user` removing `cpu`. Is this fine? I am open to either `set/update`.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 155 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UKebf6VhM9bEuhfN8:-N4XzJu1CGjcoXAJEAFB:bwx2t9o) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/src/bookkeep/shim_thread.c#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Doesn't this code belong to PAL, in particular: PAL/Linux-SGX? We do +/- all other sanitizations in there.
</blockquote></details>

Yes makes sense, I have moved it to PAL/Linux-SGX.


<!-- Sent from Reviewable.io -->

2022-06-15 16:02 UTC, mkow requested changes
> Reviewed 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 1 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4bkK2s5oPzvBj1j0Oz:b-xinu1) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
> a size that is lesser than the `cpumask`

I don't understand, what do you mean? `cpumask` is a pointer passed to this function...

This example doesn't help much, because you're using a different (higher-level) API there, I don't know how it maps to syscalls.
But I guess what you want to say is that it's legal to pass byte size which is not a multiply of `sizeof(ulong)`?
If so this makes my point even stronger...

> I was actually fine with the current logic: size in bytes, cpumask in ulongs...

@dimakuv: I guess you didn't expect that size may not be a multiple of `sizeof(ulong)`? That was my original point, that this API is weird and confusing, and you don't know if this case is legal or not.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N4c4XJeBwphiJZ2MHJP:bni6hey) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
Now it's fine.

> I was fine with a single function. But Michal is in favor of 2 functions, so let's do 2 functions. Will be clearer for sure.

A strong veto from my side for introducing any patterns like this to our codebase. I.e. magic parameter values (in a very unsuspicious parameter - "size") which completely change semantics of the function.
___
*[`LibOS/shim/include/shim_thread.h` line 354 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIEpd6Z2gddrEhyx-:-N4biO1P5a4efakxboXv:b8ewjuj) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L354)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

By `user` I mean the end-user who tries to set/update thread affinity by calling `sched_setaffinity` function from their application. Instead of `user` would `application` be more clear?
</blockquote></details>

Ah, I thought you mean the user of this function (i.e. the caller) and it didn't make much sense. Maybe "user application"?
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIH_x7RNuHnCQKBlW:-N4bjjkB74dw3qaaMgpT:b929lqq) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv preferred to use `update` so I changed this to `update_thread_affinity_from_user` removing `cpu`. Is this fine? I am open to either `set/update`.
</blockquote></details>

I'm fine with `update` instead of `set`, but I'd drop this `_from_user`, IMO it's more confusing than helping.


<!-- Sent from Reviewable.io -->

2022-06-15 16:15 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4c7PUY46LTyq-ljpLF:be63ssj) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> a size that is lesser than the `cpumask`

I don't understand, what do you mean? `cpumask` is a pointer passed to this function...

This example doesn't help much, because you're using a different (higher-level) API there, I don't know how it maps to syscalls.
But I guess what you want to say is that it's legal to pass byte size which is not a multiply of `sizeof(ulong)`?
If so this makes my point even stronger...

> I was actually fine with the current logic: size in bytes, cpumask in ulongs...

@dimakuv: I guess you didn't expect that size may not be a multiple of `sizeof(ulong)`? That was my original point, that this API is weird and confusing, and you don't know if this case is legal or not.
</blockquote></details>

@mkow Yes, I didn't expect the size *not* to be a multiple of `sizeof(ulong)`. Yes, I agree now, the API is confusing in this sense.
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N4c7WtS0L_DJR4KCMX_:b7g9ud) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it's fine.

> I was fine with a single function. But Michal is in favor of 2 functions, so let's do 2 functions. Will be clearer for sure.

A strong veto from my side for introducing any patterns like this to our codebase. I.e. magic parameter values (in a very unsuspicious parameter - "size") which completely change semantics of the function.
</blockquote></details>

@mkow I'm ok with this rule for our codebase. But I'd like to note that this pattern is quite typical, the mbedTLS lib is the first example that comes to mind, see https://siliconlabs.github.io/Gecko_SDK_Doc/mbedtls/html/base64_8h.html#a1e8abeb72a244acb346fc4ac3083886c (read the `note` there).
___
*[`LibOS/shim/include/shim_thread.h` line 354 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIEpd6Z2gddrEhyx-:-N4c7DQmDYCwUBi8UyRq:btgg7oc) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L354)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I thought you mean the user of this function (i.e. the caller) and it didn't make much sense. Maybe "user application"?
</blockquote></details>

Well, `_user_app` then, not the whole `_user_application`
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIH_x7RNuHnCQKBlW:-N4c7sI0Cv_-qjN1ZEws:biwu48n) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with `update` instead of `set`, but I'd drop this `_from_user`, IMO it's more confusing than helping.
</blockquote></details>

I'm fine with either `_from_user_app` or just dropping `_from_user`. Let's go with Michal's suggestion of dropping it.
___
*[`Pal/src/host/Linux/db_threading.c` line 273 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c87HbDYc1bg46imN_:-N4c87HbDYc1bg46imNa:bvrramm) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L273)):*
> ```C
>             if (!g_pal_public_state.topo_info.threads[i].is_online) {
>                 /* cpumask contains a CPU that is currently offline */
>                 ret = -EINVAL;
> ```

You can't return UNIX error codes in PAL code. Please replace with `-PAL_ERROR_INVAL`.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N4c8IU6CAP7lNxl74IE:ba51k3n) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
> ```C
>             }
>         }
>     }
> ```

Well, technically you don't need it in Linux PAL -- it is not about security anyway. @mkow Do you want to keep this verification here, or should we remove it from Linux PAL?
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8Fm0-RtbW2rmSZNu:-N4c8Fm0-RtbW2rmSZNv:bvrramm) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
> ```C
>             if (!g_pal_public_state.topo_info.threads[i].is_online) {
>                 /* cpumask contains a CPU that is currently offline */
>                 ret = -EINVAL;
> ```

You can't return UNIX error codes in PAL code. Please replace with `-PAL_ERROR_INVAL`.


<!-- Sent from Reviewable.io -->

2022-06-15 17:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4cASv03qstx4zHb84b:b-svcf0l) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
> I don't understand, what do you mean? cpumask is a pointer passed to this function...
@mkow your suggestion was to pass array + its length right? And you rightly noted that it is legal to pass byte size which is not a multiply of sizeof(ulong). Given this how do we exactly know the valid cpumask_size?

In the example, what I am trying to show is that we can set all the bits that is `1024` in cpumask pointer but user can pass only 4 bytes meaning keep the affinity restricted to the first `0-31` cores.

We receive a pointer to this struct
```
typedef struct
{
  __cpu_mask __bits[__CPU_SETSIZE / __NCPUBITS];
} cpu_set_t;
```

Update: Had a quick chat with @dimakuv and he proposes to use a function signature like,
```
int update_thread_affinity_from_user(struct shim_thread* thread, size_t cores_to_set, size_t cpumask_size, unsigned long* cpumask);
```

Where,
`cores_to_set` is in bytes -- This is the same as what was called cpumask_size previously.
`cpumask_size` is the count in ulongs of the cpumask object. Basically round to the nearest ulong from size in bytes.

Does this proposal look fine to you? One thing I am not sure if we may not end up using `cpumask_size` as we already have the actual bytes to copy in `cores_to_set`.

Please note, I am fine with the doing the change, but want to make sure if this is expected.


<!-- Sent from Reviewable.io -->

2022-06-16 06:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4fFfvNCFDvrgz7yQ2S:bd73bn4) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
I think @mkow's confusion is that the current function signature looks like this:
```
...
 * \param cpumask_size  Size (in bytes) of the cpumask.
 * \param cpumask       CPU affinity mask passed from the user.
 */
int update_thread_affinity_from_user(struct shim_thread* thread, size_t cpumask_size,
                                     unsigned long* cpumask);
```

So looking at this signature and comments, a user thinks: good, the array of ulongs `cpumask` is passed to this function, and the size of this array (in bytes) is `cpumask_size`. That's literally what the `\param` comment says.

But now @vijaydhanraj says that `cpumask_size` is **not** the size of the array, but actually more like a "that's how many bytes we'd like to update in the `cpumask` object". So two problems here:
1. The comment for `cpumask_size` is plain wrong.
2. There is no argument for the *actual size* of the `cpumask` object.
    - This is always a bad smell to *not* provide the full size of the object as an additional argument.
    - This means that currently the function *assumes* that the "how many bytes we'd like to update in the `cpumask` object" is *always* less than the size of the object (otherwise we can have buffer overflow!).
    - But imagine a Gramine developer in 2025, looking at this function. He may think, good, it looks like this function expects the "how many bytes we'd like to update" argument, so let me supply some really big number here and hope that the function has checks that modify this number to an appropriate one for the `cpumask` object. And the developer has a right to think so -- there is no explanation in the function comments that this is illegal.
    - But if the function would have an additional argument that contains *the actual size* of the `cpumask` object, then it is intuitively understandable what this function expects and how it behaves.

> `cpumask_size` is the count in ulongs of the cpumask object. Basically round to the nearest ulong from size in bytes.

I don't remember whether I said this "round to the nearest ulong"... This is incorrect. This should be the actual size of the `cpumask` object.

> One thing I am not sure if we may not end up using `cpumask_size` as we already have the actual bytes to copy in `cores_to_set`.

You'll have to use `cpumask_size` to check for a buffer overflow. You'll add lines like this in the beginning of the func:
```
if (cores_to_set > cpumask_size * 8) {
    /* user supplied more cores to set than is actually possible to hold in the cpumask */
    return -EINVAL;
}
```


<!-- Sent from Reviewable.io -->

2022-06-16 12:38 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N4gTuFF8xsyJ31YMRUG:b-384jz7) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
Vijay, the problem is that you say you pass an array of ulongs, but then you also say that its size can be 3 bytes. If something's size is 3 bytes, then it's not an array of unsigned longs.
I'm still confused what's happening in this function and I'm not really sure if my current understanding is correct. That's not how a public API should work.

>  `cpumask_size` is the count in ulongs of the cpumask object. Basically round to the nearest ulong from size in bytes.

Eh, please be more accurate / diligent in these descriptions, otherwise we'll never get anywhere. In this one sentence you:
- Named the variable `cpumask_size` - which in Gramine's codebase convention means that it's a byte-size
- Then you say that it is "the count in ulongs"
- And then you again indicate that it's actually a byte-size: "round to the nearest ulong from size in bytes"
___
*[`LibOS/shim/include/shim_thread.h` line 351 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMWCcDacsTtor-Ezd:-N4gVZY7CVngp2fX8mM5:b-7fjmwa) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L351)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I'm ok with this rule for our codebase. But I'd like to note that this pattern is quite typical, the mbedTLS lib is the first example that comes to mind, see https://siliconlabs.github.io/Gecko_SDK_Doc/mbedtls/html/base64_8h.html#a1e8abeb72a244acb346fc4ac3083886c (read the `note` there).
</blockquote></details>

That pattern is different - passing NULL as buffer just to learn what's the expected output size. Here passing `size=0` completely changes function's behavior.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N4gW7Cm5B3dLGBkvwke:bfemv6j) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, technically you don't need it in Linux PAL -- it is not about security anyway. @mkow Do you want to keep this verification here, or should we remove it from Linux PAL?
</blockquote></details>

Yeah, I don't see any point in this check here.


<!-- Sent from Reviewable.io -->

2022-06-20 07:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 350 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dMKX18u1-Q2vK9a_6:-N5--AzT3VpBVMAUEZ8l:b84jf3h) ([raw file](https://github.com/gramineproject/gramine/blob/48d559275e7d5c538ad9dcf615c6ee05e2e5561d/LibOS/shim/include/shim_thread.h#L350)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Vijay, the problem is that you say you pass an array of ulongs, but then you also say that its size can be 3 bytes. If something's size is 3 bytes, then it's not an array of unsigned longs.
I'm still confused what's happening in this function and I'm not really sure if my current understanding is correct. That's not how a public API should work.

>  `cpumask_size` is the count in ulongs of the cpumask object. Basically round to the nearest ulong from size in bytes.

Eh, please be more accurate / diligent in these descriptions, otherwise we'll never get anywhere. In this one sentence you:
- Named the variable `cpumask_size` - which in Gramine's codebase convention means that it's a byte-size
- Then you say that it is "the count in ulongs"
- And then you again indicate that it's actually a byte-size: "round to the nearest ulong from size in bytes"
</blockquote></details>

Had an offline chat with @mkow and @dimakuv. It was decided that we will change the type of cpumask from array of unsigned longs to array of uint8_t. This was passing bytes makes sense.
`int update_thread_affinity(struct shim_thread* thread, size_t cpumask_size, uint8_t* cpumask);`
___
*[`LibOS/shim/include/shim_thread.h` line 354 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIEpd6Z2gddrEhyx-:-N4yh46jDn6yXvaqKoUt:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L354)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This discussion in only about wording in this documentation line ;)
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r6](https://reviewable.io/reviews/gramineproject/gramine/631#-N4UIH_x7RNuHnCQKBlW:-N4yeU27A89UkPk--RoO:bs7glge) ([raw file](https://github.com/gramineproject/gramine/blob/4f240bba03289b9ed71cf874c3b13f0793c3bcbd/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with either `_from_user_app` or just dropping `_from_user`. Let's go with Michal's suggestion of dropping it.
</blockquote></details>

As suggested renamed to `update_thread_affinity`
___
*[`Pal/src/host/Linux/db_threading.c` line 273 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c87HbDYc1bg46imN_:-N4yhWcf5Eb-6lNMbibK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can't return UNIX error codes in PAL code. Please replace with `-PAL_ERROR_INVAL`.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N4yfL4i4mmfe8fMaFtJ:b4n91mm) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I don't see any point in this check here.
</blockquote></details>

I thought we wanted to move this check from LibOS to PAL as it would be more appropriate. But now we want to remove the check?
Don't we want to fail if the malicious host returned a cpumask containing offlined cores?

@dimakuv can you please clarify?
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8Fm0-RtbW2rmSZNu:-N4yhVON8cCcCmNSVgWf:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can't return UNIX error codes in PAL code. Please replace with `-PAL_ERROR_INVAL`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-20 11:28 UTC, mkow requested changes
> Reviewed 1 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 360 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-rWDM5w9T0jO7TgEK:-N5-rWDN6ycnuAkOmnJL:b-iejz8g) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/include/shim_thread.h#L360)):*
> ```objc
>  */
> int update_thread_affinity(struct shim_thread* thread, size_t cpumask_size,
>                            uint8_t* cpumask);
> ```

Please pass the array pointer first, that's what most of such places do.


<!-- Sent from Reviewable.io -->

2022-06-20 15:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 360 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-LjDV6shgI_kIco_h:-N50SXjn9b5GXBIL8IcX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/include/shim_thread.h#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it can be re-wrapped to 100 chars, so that everything is on one line.
</blockquote></details>

Done.
___
*[`LibOS/shim/include/shim_thread.h` line 360 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-rWDM5w9T0jO7TgEK:-N50SYmp44r4UbpBdxQl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/include/shim_thread.h#L360)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please pass the array pointer first, that's what most of such places do.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N50SwjIBJugnyJeF2Jl:b-ljvvkb) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why so complicated? Why couldn't you just do `update_thread_affinity(thread, cpumask_size, (uint8_t*)user_mask_ptr)` and be happy?
</blockquote></details>

Actually, I didn't think about it. But did test with typecasting and everything works fine. 
Thanks @dimakuv, this is much simpler. I just added the comments on why we do the typecasting.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N50Vv4H8m_GZgGZLKVu:b13vezw) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Don't we want to fail if the malicious host returned a cpumask containing offlined cores?

This file is `Linux/db_threading.c` -- we are in the Linux PAL. The Linux PAL is **not** about security. That's why we're asking to remove your code from this file only.
</blockquote></details>

If we remove this check here, we don't have a check elsewhere. I think what you are missing is that this check was removed from `init_thread_affinity_from_host` and moved to PAL based on a comment from @mkow. If we remove it from here, there is no check to verify the affinity passed from the host.

So, should I move this check in the LibOS then?


<!-- Sent from Reviewable.io -->

2022-06-20 15:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 3 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N50gSveENWgdQ0SBQyL:b-py54c8) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Actually, I didn't think about it. But did test with typecasting and everything works fine. 
Thanks @dimakuv, this is much simpler. I just added the comments on why we do the typecasting.
</blockquote></details>

This is UB.


<!-- Sent from Reviewable.io -->

2022-06-20 15:30 UTC, mkow requested changes
> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N50jA-kDuNhqKaO4OBr:bh23ju3) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
> ```objc
>  * \param thread        Thread whose CPU affinity needs to be updated.
>  * \param cpumask       CPU affinity mask to be updated.
>  * \param cpumask_cnt   Count of cpumask bytes to be updated.
> ```

That's not true.



_Code quote:_
```objc
Count of cpumask bytes to be updated.
```
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N50io6q8Ajgr2-udgr3:bo1aju0) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If we remove this check here, we don't have a check elsewhere. I think what you are missing is that this check was removed from `init_thread_affinity_from_host` and moved to PAL based on a comment from @mkow. If we remove it from here, there is no check to verify the affinity passed from the host.

So, should I move this check in the LibOS then?
</blockquote></details>

But how a check inside `Linux/db_threading.c` can protect Linux-SGX PAL? I don't understand your point.


<!-- Sent from Reviewable.io -->

2022-06-20 15:45 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N50lnq_EvAF6Kxq-Tz7:b1u4mj0) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not true.
</blockquote></details>

How about I just change the `cpumask_size`->`cpumsk_cnt` and keep the comment same, that is `Size (in bytes) of the cpumask.`? 
___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N50kWIc0vllW2_gLQtK:b-f4r5rh) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is UB.
</blockquote></details>

ah I see. Thanks @boryspoplawski 
@dimakuv shall I revert to the earlier change? 
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N50knX-8hQp_3yOKmBy:btopg5r) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But how a check inside `Linux/db_threading.c` can protect Linux-SGX PAL? I don't understand your point.
</blockquote></details>

Ah my bad. I thought @dimakuv wanted me to remove this check in both Linux PAL/Linux-SGX PAL. Looks like we want to remove the check only in Linux PAL and not Linux-SGX PAL.


<!-- Sent from Reviewable.io -->

2022-06-20 17:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N5145k2Aq9XJXGjYUjp:b-725xu6) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

? This comment will be even more wrong than the current one...
</blockquote></details>

How about `Count of cpumask elements to be updated`? Would appreciate your proposal if you think this isn't fine.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N513q9t2NoWCmUs-d2m:b7s55pq) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, Dmitrii explicitly said "technically you don't need it in Linux PAL".
</blockquote></details>

Got it, will remove the check only from Linux PAL.


<!-- Sent from Reviewable.io -->

2022-06-20 17:21 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N517Hh-CnZFTGD4nDo5:b-lw7uyr) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about `Count of cpumask elements to be updated`? Would appreciate your proposal if you think this isn't fine.
</blockquote></details>

Why not just "Number of elements in \p cpumask array"? That was the whole idea of this change, to have just a pointer and number of elements...


<!-- Sent from Reviewable.io -->

2022-06-20 20:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N51reVA6hldo53kR_78:b-npn5ia) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, will use the suggested text. I was under the impression that we didn't want to use `number` as we replaced `num_*` with `*_cnt`. So was trying to use the word `count`.
</blockquote></details>

Both are fine IMO in the documentation (the `_cnt` convention is to have predictable variable names), just don't suggest that this is a byte-size (it's technically the same value here, but what we want to have is the typical C pattern where you pass an array as argument as ptr+elem_cnt).


<!-- Sent from Reviewable.io -->

2022-06-23 09:03 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5Emuvs5Vo_Ayt7LmbI:b-2yltyh) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ah I see. Thanks @boryspoplawski 
@dimakuv shall I revert to the earlier change? 
</blockquote></details>

@boryspoplawski Why a UB?
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N5EnBZDBIEuRRmJG8w8:b-b1v8y8) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, will remove the check only from Linux PAL.
</blockquote></details>

Yes, please, remove the check only from Linux PAL.


<!-- Sent from Reviewable.io -->

2022-06-23 13:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5FmGaDB4vtDApoMK-Q:b-h1x6w7) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Casting a pointer to a different type and dereferencing it is a UB. Unless it's `char*`. Here I see a comment about `uint8_t`, which technically is UB, but in practice this is just a typedef to `unsigned char` so it should be fine (and I don't see how it could be something else).
</blockquote></details>

@boryspoplawski: The problem here (at least if Vijay didn't mess up the details) is that it wasn't ever an array of unsigned longs - it's legal to pass e.g. just 3 bytes in it. So, this syscall signature is just completely wrong in Linux?


<!-- Sent from Reviewable.io -->

2022-06-23 14:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5FtuYyAUEPp00BfDKO:byzhw3i) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did a quick look: it is indeed size in bytes, but linux has basically this:
```c
expected_size = BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long);
if (size < expected_size) {
    size = 0;
    clear_mask(&mask);
 } else if (size > expected_size) {
    size = expected_size;
}
memcpy(&mask, user_provided_mask, size);
```
Which effectively means that user can provide any size, but it's immediately changed to some sane value.
</blockquote></details>

@boryspoplawski can you please confirm if the size is set to `0` when `size < expected_size`. I am looking at this, https://elixir.bootlin.com/linux/v5.11/source/kernel/sched/core.c#L6569 and https://elixir.bootlin.com/linux/v5.11/source/kernel/sched/core.c#L6541.

I see that they just leave the size as it is if `size < expected_size` and simply do a `copy_from_user()` for that requested size.


<!-- Sent from Reviewable.io -->

2022-06-23 14:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5Fv3-n1fu3RWYlbT4S:b5vvrqs) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@boryspoplawski can you please confirm if the size is set to `0` when `size < expected_size`. I am looking at this, https://elixir.bootlin.com/linux/v5.11/source/kernel/sched/core.c#L6569 and https://elixir.bootlin.com/linux/v5.11/source/kernel/sched/core.c#L6541.

I see that they just leave the size as it is if `size < expected_size` and simply do a `copy_from_user()` for that requested size.
</blockquote></details>

Ah, true, it's not set to `0`. They just copy the part of the buffer.


<!-- Sent from Reviewable.io -->

2022-06-23 15:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5G7_Gi32qNvQbxNtwA:bujhnom) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, true, it's not set to `0`. They just copy the part of the buffer.
</blockquote></details>

Thanks @boryspoplawski , so can we conclude it is safe to type cast here as uint8_t is an unsigned char?


<!-- Sent from Reviewable.io -->

2022-06-23 15:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5GBwt8CYViZU103PIW:b2nhswy) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks @boryspoplawski , so can we conclude it is safe to type cast here as uint8_t is an unsigned char?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2022-06-23 21:02 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 355 at r9](https://reviewable.io/reviews/gramineproject/gramine/631#-N50jA-j8lPj0Tfk8ewC:-N5HKqS12QcgfzB83AyM:biiwpzw) ([raw file](https://github.com/gramineproject/gramine/blob/90ad55328bd7a2974d32887819e7fe0df507476a/LibOS/shim/include/shim_thread.h#L355)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Both are fine IMO in the documentation (the `_cnt` convention is to have predictable variable names), just don't suggest that this is a byte-size (it's technically the same value here, but what we want to have is the typical C pattern where you pass an array as argument as ptr+elem_cnt).
</blockquote></details>

Got it. Just to be consistent, I have used `Count` in of `Number`.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 200 at r8](https://reviewable.io/reviews/gramineproject/gramine/631#-N5-MTrY8MwiLNiIYIjW:-N5HLoKL4fjHldmqDrsv:b-cfgl7f) ([raw file](https://github.com/gramineproject/gramine/blob/8a087ad9d31eb540abb600989c6d17e42c53969e/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Thanks, I will keep the current code.
___
*[`Pal/src/host/Linux/db_threading.c` line 276 at r7](https://reviewable.io/reviews/gramineproject/gramine/631#-N4c8IU6CAP7lNxl74ID:-N5HKYCvEAX-RhDrkiZS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/345fea255ba2a47d3cc249c4f8b9260811e45703/Pal/src/host/Linux/db_threading.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please, remove the check only from Linux PAL.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-24 08:23 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5HNMXf4UQ_xzObk5jV:-N5Jn9K_AW2BE3XUhIZX:b-gkivxs) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow @dimakuv can I merge all the fixups and rebase and, in the process, fix the commit message?
</blockquote></details>

No, why do you want to do this? The review process is not yet finished.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5JnCFmCIxp8fQ2x9O1:-N5JnCFmCIxp8fQ2x9O2:b-k7ixhi) (no related file):*
@vijaydhanraj Please fix the bug:
```
23:06:47  ../Pal/src/host/Linux/db_threading.c: In function ‘_DkThreadGetCpuAffinity’:
23:06:47  ../Pal/src/host/Linux/db_threading.c:266:1: error: expected declaration or statement at end of input
23:06:47   };
23:06:47   ^
23:06:47  ../Pal/src/host/Linux/db_threading.c:264:19: error: unused variable ‘g_thread_ops’ [-Werror=unused-variable]
23:06:47   struct handle_ops g_thread_ops = {
23:06:47                     ^~~~~~~~~~~~
```

I'm sorry to be harsh, but as part of your latest fixup you removed the closing `}` of the function body. This would be trivially detected if you would just do `ninja -C build` on your commit before pushing to GitHub. **This is basic sanity check**, and it's not acceptible to push PRs that don't even build on Linux PAL.

___


<!-- Sent from Reviewable.io -->

2022-06-24 15:43 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5JnCFmCIxp8fQ2x9O1:-N5LEiGS8VUWDE6ShGw5:b-nyaddg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj Please fix the bug:
```
23:06:47  ../Pal/src/host/Linux/db_threading.c: In function ‘_DkThreadGetCpuAffinity’:
23:06:47  ../Pal/src/host/Linux/db_threading.c:266:1: error: expected declaration or statement at end of input
23:06:47   };
23:06:47   ^
23:06:47  ../Pal/src/host/Linux/db_threading.c:264:19: error: unused variable ‘g_thread_ops’ [-Werror=unused-variable]
23:06:47   struct handle_ops g_thread_ops = {
23:06:47                     ^~~~~~~~~~~~
```

I'm sorry to be harsh, but as part of your latest fixup you removed the closing `}` of the function body. This would be trivially detected if you would just do `ninja -C build` on your commit before pushing to GitHub. **This is basic sanity check**, and it's not acceptible to push PRs that don't even build on Linux PAL.
</blockquote></details>

Apologies, it is my bad. I usually build and run the regression tests but this time I copied the code from our master to revert to the original change. And since I copied the code, my overconfident brain thought why to build as I didn't introduce any new change. 

Sorry for the lackadaisical approach here. Will be careful.

___


<!-- Sent from Reviewable.io -->

2022-06-27 02:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 5 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5HNMXf4UQ_xzObk5jV:-N5XyVGt5FH-DEGk1chd:b-l2ymfm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, why do you want to do this? The review process is not yet finished.
</blockquote></details>

I thought we were almost done with the review, and so felt this would be a good time to fix the commit message (I had blocked myself), so suggested rebasing. But I will wait for the review to get done.

___
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 175 at r11](https://reviewable.io/reviews/gramineproject/gramine/631#-N5Y-dYyBKZ_yFjkYx91:-N5Y-dYyBKZ_yFjkYx92:bbx794u) ([raw file](https://github.com/gramineproject/gramine/blob/9e604314091ef55358fd47019f07b47c12abbc8c/LibOS/shim/src/bookkeep/shim_thread.c#L175)):*
> ```C
>     for (size_t i = 0; i < MIN(threads_cnt, cpumask_cnt * BITS_IN_BYTE); i++) {
>         idx = i / BITS_IN_TYPE(uint8_t);
>         if (cpumask[idx] & 1UL << (i % BITS_IN_TYPE(uint8_t))) {
> ```

Would it be better to change`1UL` to either `1U` or `(uint8_t)1`?


<!-- Sent from Reviewable.io -->

2022-06-27 08:40 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5ZJFwV2B2-IKauqNBw:-N5ZJFwV2B2-IKauqNBx:b1jai1t) (no related file):*
LTP failed, please debug:
```
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:88: TINFO: system has 8 processor(s).
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:72: TFAIL: No cpus enabled in mask
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:39: TPASS: sched_getaffinity() failed: EFAULT (14)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:39: TPASS: sched_getaffinity() failed: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/safe_file_ops.c:144: TBROK: Failed to open FILE '/proc/sys/kernel/pid_max' for reading at /home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/tst_pid.c:34: ENOENT (2)
```

```
command: ['gramine-direct', 'sched_getaffinity01']
must_pass: [1, 2, 3]
returncode: 3
passed: [2, 3]
failed: [1, 4]
```

___
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 175 at r11](https://reviewable.io/reviews/gramineproject/gramine/631#-N5Y-dYyBKZ_yFjkYx91:-N5ZIrya04RnOVaBTjX3:bkxofcx) ([raw file](https://github.com/gramineproject/gramine/blob/9e604314091ef55358fd47019f07b47c12abbc8c/LibOS/shim/src/bookkeep/shim_thread.c#L175)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Would it be better to change`1UL` to either `1U` or `(uint8_t)1`?
</blockquote></details>

`1U` sounds better to me. Here and the line below as well.


<!-- Sent from Reviewable.io -->

2022-06-27 23:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5ZJFwV2B2-IKauqNBw:-N5bOq9n6gvtdzkuuddU:basyvvt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LTP failed, please debug:
```
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:88: TINFO: system has 8 processor(s).
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:72: TFAIL: No cpus enabled in mask
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:39: TPASS: sched_getaffinity() failed: EFAULT (14)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/sched_getaffinity/sched_getaffinity01.c:39: TPASS: sched_getaffinity() failed: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/safe_file_ops.c:144: TBROK: Failed to open FILE '/proc/sys/kernel/pid_max' for reading at /home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/tst_pid.c:34: ENOENT (2)
```

```
command: ['gramine-direct', 'sched_getaffinity01']
must_pass: [1, 2, 3]
returncode: 3
passed: [2, 3]
failed: [1, 4]
```
</blockquote></details>

The root cause is, when forking, the parent's cpu affinity mask was not being set in the child. This resulted in no cpus being set in the child's cpu affinity mask. I have fixed this now and all the Linux PAL LTP tests have passed. Also, the LibOS and PAL regression tests pass.

___
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 175 at r11](https://reviewable.io/reviews/gramineproject/gramine/631#-N5Y-dYyBKZ_yFjkYx91:-N5bOoA052ahLPBJ0m-u:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/9e604314091ef55358fd47019f07b47c12abbc8c/LibOS/shim/src/bookkeep/shim_thread.c#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`1U` sounds better to me. Here and the line below as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-28 09:37 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5dcbw63TumoyknLcyA:-N5dcbw79AiBXRgKUwte:bb0zas7) (no related file):*
Now AddressSanitizer found some buffer overflow:
```
[P1:T1:openmp] error: asan: heap-buffer-overflow while trying to load 1048576 bytes at 0x7ffff373c448
[P1:T1:openmp] error: asan: the bad address is 0x7ffff373c560 (280 from beginning of access)
[P1:T1:openmp] error: asan: location: shim_do_sched_getaffinity at shim_sched.c, libsysdb.so+0x49b16e
[P1:T1:openmp] error: asan: (for a full traceback, use GDB with a breakpoint at "shim_abort")
[P1:T1:openmp] error: asan:
[P1:T1:openmp] error: asan: shadow bytes around the bad address:
[P1:T1:openmp] error: asan:   0x117ffe6e7860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[P1:T1:openmp] error: asan:   0x117ffe6e7870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[P1:T1:openmp] error: asan:   0x117ffe6e7880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[P1:T1:openmp] error: asan:   0x117ffe6e7890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[P1:T1:openmp] error: asan: =>0x117ffe6e78a0: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
[P1:T1:openmp] error: asan:   0x117ffe6e78b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[P1:T1:openmp] error: asan:   0x117ffe6e78c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[P1:T1:openmp] error: asan:   0x117ffe6e78d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[P1:T1:openmp] error: asan:   0x117ffe6e78e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[P1:T1:openmp] error: asan:
[P1:T1:openmp] error: asan: shadow byte legend (1 shadow byte = 8 application bytes):
[P1:T1:openmp] error: asan:           addressable: 00
[P1:T1:openmp] error: asan: partially addressable: 01..07
[P1:T1:openmp] error: asan:     heap left redzone: fa
[P1:T1:openmp] error: asan:     freed heap region: fd
[P1:T1:openmp] error: asan:    stack left redzone: f1
[P1:T1:openmp] error: asan:     stack mid redzone: f2
[P1:T1:openmp] error: asan:   stack right redzone: f3
[P1:T1:openmp] error: asan:     stack after scope: f8
[P1:T1:openmp] error: asan:   alloca left redzone: ca
[P1:T1:openmp] error: asan:  alloca right redzone: cb
[P1:T1:openmp] error: asan:        global redzone: f9
[P1:T1:openmp] error: asan:         user-poisoned: f7
```

This is in the OpenMP LibOS regression test. Please check.

___
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 190 at r12](https://reviewable.io/reviews/gramineproject/gramine/631#-N5derT242Rh8G2k9OWZ:-N5derT3AsvHwqPy6l6W:b58lb2a) ([raw file](https://github.com/gramineproject/gramine/blob/e5d9221b9ab25462c186fea41f0b3b67cde67bc3/LibOS/shim/src/bookkeep/shim_thread.c#L190)):*
> ```C
> 
>     memset(thread->cpumask, 0, sizeof(thread->cpumask));
>     memcpy(thread->cpumask, cpumask, MIN(sizeof(thread->cpumask), cpumask_cnt));
> ```

Funny, we actually have my proposed fix for AddressSanitizer here. But seems like we forgot to apply the same to `sched_getaffinity()`. See my other comments.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 228 at r12](https://reviewable.io/reviews/gramineproject/gramine/631#-N5deE0wAO6HBQG7Doak:-N5deE0wAO6HBQG7Doal:b-5j33ot) ([raw file](https://github.com/gramineproject/gramine/blob/e5d9221b9ab25462c186fea41f0b3b67cde67bc3/LibOS/shim/src/sys/shim_sched.c#L228)):*
> ```C
>     memset(user_mask_ptr, 0, cpumask_size);
>     lock(&thread->lock);
>     memcpy(user_mask_ptr, thread->cpumask, cpumask_size);
> ```

I guess AddressSanitizer fails here. This is most probably because `sizeof(thread->cpumask) < cpumask_size`, i.e., Gramine's limit on 2048 bits is less than the user-supplied `cpumask_size`. This leads to buffer overrun during memory copy, and ASan notices this.

We should replace `cpumask_size` with smth like `MIN(cpumask_size, sizeof(thread->cpumask))`.


<!-- Sent from Reviewable.io -->

2022-06-29 04:56 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 5 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5dcbw63TumoyknLcyA:-N5hYvgj9Kxf6cD_sOBd:bb6p4lt) (no related file):*
>  

___
___
*[`LibOS/shim/src/sys/shim_sched.c` line 228 at r12](https://reviewable.io/reviews/gramineproject/gramine/631#-N5deE0wAO6HBQG7Doak:-N5hg--V433eF6AI7Flw:bgaf3pj) ([raw file](https://github.com/gramineproject/gramine/blob/e5d9221b9ab25462c186fea41f0b3b67cde67bc3/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess AddressSanitizer fails here. This is most probably because `sizeof(thread->cpumask) < cpumask_size`, i.e., Gramine's limit on 2048 bits is less than the user-supplied `cpumask_size`. This leads to buffer overrun during memory copy, and ASan notices this.

We should replace `cpumask_size` with smth like `MIN(cpumask_size, sizeof(thread->cpumask))`.
</blockquote></details>

Yes, you might be right, and this could be a buffer over-read case. I have made this change. But I am not able to reproduce the exact error. I switched to clang and used the following build command.
```
export CC=clang-12 CXX=clang++-12 AS=clang-12
meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Dtests=enabled -Dsgx_driver=upstream -Dsgx_driver_include_path="" -Ddcap=enabled -Dubsan=enabled -Dasan=enabled -Dmusl=disabled
```

But when I run the `openmp` test get a different error,
```
OMP: Error #178: Function Can't open SHM2 failed:
OMP: System error #2: No such file or directory
```

So will push this change and try to start the jenkins test and check again.


<!-- Sent from Reviewable.io -->

2022-06-29 04:59 UTC, vijaydhanraj commented
Jenkins, test this please.

2022-06-29 06:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N5dcbw63TumoyknLcyA:-N5i3hzP1VUuE5XdAPRg:bydr65g) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

>  
</blockquote></details>

The new version works fine now.

___


<!-- Sent from Reviewable.io -->

2022-06-29 21:41 UTC, boryspoplawski requested changes
> Reviewed 1 of 5 files at r8, 1 of 2 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lK1Tx6eho8tkqHePA:-N5lK1TyE7RqAEdo_bc6:bb1g0rl) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L348)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int init_thread_affinity_from_host(struct shim_thread* thread);
> ```

Why do we need this function? This should be run only once, for the first thread.
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKQbu1yAxKseXCSR3:-N5lKQbu1yAxKseXCSR4:b1lo45f) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L359)):*
> ```objc
>  * \returns `0` on success and negative error code on failure.
>  */
> int update_thread_affinity(struct shim_thread* thread, uint8_t* cpumask, size_t cpumask_cnt);
> ```

Why do we need this function? It won't be ever used outside of the one place it's used at the moment (syscall setting affinity).
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lNm5C-Cz92kveABXO:-N5lNm5C-Cz92kveABXP:b-4gq05o) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
> ```C
>     if (bitmask_size_in_bytes > sizeof(thread->cpumask)) {
>         log_error("Current platform has more cores (%lu) than Gramine can support in cpumask (%lu)",
>                   threads_cnt, sizeof(thread->cpumask) * BITS_IN_BYTE);
> ```

What's the point of this `BITS_IN_BYTES`, it cannot be `!= 8`.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lO7Fc31KudnBBfzfl:-N5lO7Fc31KudnBBfzfm:b-v2nr1h) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
> ```C
> 
>     /* Allocate memory to hold the thread's CPU affinity mask. */
>     unsigned long* cpumask = malloc(bitmask_size_in_bytes);
> ```

Since we allocate the mask anyway, why don't we store it in the `thread` struct instead of artificially limiting it and keeping a static, constant size array there?
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOaq12Q01tamUkEyx:-N5lOaq12Q01tamUkEyy:bzc383) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L166)):*
> ```C
> 
> int update_thread_affinity(struct shim_thread* thread, uint8_t* cpumask, size_t cpumask_cnt) {
>     assert(locked(&thread->lock));
> ```

Please document all required locks (in addition to this assert).
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 171 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOhhhBJf9k7IrhNHm:-N5lOhhhBJf9k7IrhNHn:b64zja6) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L171)):*
> ```C
>     size_t threads_cnt = g_pal_public_state->topo_info.threads_cnt;
> 
>     size_t idx = 0;
> ```

Please move to inside the loop.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 174 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lHOpGBr9fskM-JUKQ:-N5lHOpGBr9fskM-JUKR:b-a70z0j) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L174)):*
> ```C
>     size_t cores_cnt = 0;
>     for (size_t i = 0; i < MIN(threads_cnt, cpumask_cnt * BITS_IN_BYTE); i++) {
>         idx = i / BITS_IN_TYPE(uint8_t);
> ```

Why we are using `BITS_IN_TYPE` here and `BITS_IN_BYTE` above?
What's even the point of these? We do not support anything (and come on, we never will) not having `8` bits in byte.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 178 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lP2c92X3pXde7Ao08:-N5lP2c92X3pXde7Ao09:b-dxfknt) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L178)):*
> ```C
>             if (!g_pal_public_state->topo_info.threads[i].is_online) {
>                 /* cpumask contains a CPU that is currently offline, remove it from the cpumask */
>                 cpumask[idx] &= ~(1U << (i % BITS_IN_TYPE(uint8_t)));
> ```

Won't this edit a user app provided memory? It's wrong and also this memory can be read-only.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKxFk0FIPwSTzPvvZ:-N5lKxFk0FIPwSTzPvv_:bb1tb5t) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L87)):*
> ```C
>     add_thread(my_thread);
> 
>     int ret = init_thread_affinity_from_host(my_thread);
> ```

Why this inits it from the host? Shouldn't this be exactly the same as the parent?
___
*[`LibOS/shim/src/sys/shim_clone.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lLUFU8HKlVcdt7-rc:-N5lLUFU8HKlVcdt7-rd:b91zbhw) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L166)):*
> ```C
>     /* Linux sets the same cpu affinity mask for the forked child as the parent. Following the same
>      * convention here by copying the parent's cpu affinity mask to the child. */
>     memset(thread->cpumask, 0, sizeof(thread->cpumask));
> ```

What's the point of this memset? It's immediately overwritten below.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 168 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lLthm0jXLra43QCRU:-N5lLthm0jXLra43QCRV:b6selcg) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L168)):*
> ```C
>     memset(thread->cpumask, 0, sizeof(thread->cpumask));
>     lock(&self->lock);
>     memcpy(thread->cpumask, self->cpumask, sizeof(thread->cpumask));
> ```

Why this is here? Why not in `get_new_thread` as the rest of fields that are inherited from the parent?
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5lN0rl8qT_U_LfgYLG:bdvx7t3) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
> ```C
>     }
> 
>     lock(&thread->lock);
> ```

This is not atomic. Two threads issuing this syscall can race to an inconsistent state (libos vs host OS), because PAL API call is outside of this lock.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 182 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJnIu08eILbwkegN0:-N5lJnIu08eILbwkegN1:bg4lb5s) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L182)):*
> ```C
>     size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;
> 
>     /* Verify validity of the CPU affinity (e.g., that it contains no offlined cores) */
> ```

`,` not needed, `.` missing at the  [...]

2022-06-30 07:27 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lK1Tx6eho8tkqHePA:-N5mw4b6DO_v0FNFUJ_9:bx232kb) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this function? This should be run only once, for the first thread.
</blockquote></details>

Are you suggesting to inline this function? This function is also called when we create a thread. For example, `pthread_create()` will call this function. 
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKQbu1yAxKseXCSR3:-N5mxeYNEETmcoWZqvZ4:bog7f24) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this function? It won't be ever used outside of the one place it's used at the moment (syscall setting affinity).
</blockquote></details>

You are right, this is only called from `shim_do_sched_getaffinity`. We could have inlined this function in `shim_sched.c` but if you note this function just updates a thread's cpu affinity mask and nothing related to scheduling per se. So, kept this function in `shim_thread.c`

But if you feel we need to inline this, we can do it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lNm5C-Cz92kveABXO:-N5mzKYN-NA-7LzxleP_:b-48qkq) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this `BITS_IN_BYTES`, it cannot be `!= 8`.
</blockquote></details>

Are you suggesting we remove `BITS_IN_BYTES` macro and simply have `8`?
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lO7Fc31KudnBBfzfl:-N5n1SHj8fL5WmDuzQKq:b-qr10iz) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since we allocate the mask anyway, why don't we store it in the `thread` struct instead of artificially limiting it and keeping a static, constant size array there?
</blockquote></details>

Allocating the `cpumask` statically is just for ease of use. If we allocate dynamically, we might also need to keep track of how many elements can be stored, making error checking a little more complex. Secondly, when forking we simply copy the mask of the parent to the child and this function will not be called. So, we might need to allocate dynamically even in `do_clone_new_vm` flow. Thirdly, we might need to make sure the allocation is freed when the thread is terminated.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOaq12Q01tamUkEyx:-N5n3ykX7AaGxhUf8URP:bkzcjdq) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L166)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please document all required locks (in addition to this assert).
</blockquote></details>

By document you mean to add something like `The caller of this function must hold the thread lock` in header file where we have the function description right?

Also, I need to add a similar comment in the caller function as well. 
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 174 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lHOpGBr9fskM-JUKQ:-N5n8rhX8aQLhsjFggaS:bd3638h) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L174)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why we are using `BITS_IN_TYPE` here and `BITS_IN_BYTE` above?
What's even the point of these? We do not support anything (and come on, we never will) not having `8` bits in byte.
</blockquote></details>

Please clarify. Do you want to remove this macro?
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 178 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lP2c92X3pXde7Ao08:-N5n9PC4-srALQxOWVVY:b-hlv7r0) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L178)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Won't this edit a user app provided memory? It's wrong and also this memory can be read-only.
</blockquote></details>

You are right, I will create a local copy and then pass it to the helper function.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKxFk0FIPwSTzPvvZ:-N5nGyiHEhQSPQBNLSY_:b-kka2h5) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this inits it from the host? Shouldn't this be exactly the same as the parent?
</blockquote></details>

Yes, we shouldn't init from the host but just copy the parent's cpumask. I did this when we fork but missed it here.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lLUFU8HKlVcdt7-rc:-N5nJnk4CIZNy7oP9SnE:bs28hqi) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L166)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this memset? It's immediately overwritten below.
</blockquote></details>

Yes, it is not needed here, will remove it.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 168 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lLthm0jXLra43QCRU:-N5nJrw0AWTyOPgHN9J7:b-kctv6j) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is here? Why not in `get_new_thread` as the rest of fields that are inherited from the parent?
</blockquote></details>

Yes this is better to have as it will help both for cloning as well as forking case. I will also remove the setting the host affinity (`init_thread_affinity_from_host`) from `clone_implementation_wrapper()`.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5nP0082y_G1_M6ZIxo:b3yl6w0) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
So the reason this lock was added is to handle a case where if two threads call this function simultaneously with the same  [...]

2022-06-30 11:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lK1Tx6eho8tkqHePA:-N5oDEMa-AV5RNTYQ7sM:b-ntjphj) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L348)):*
> pthread_create()

What?

> This function is also called when we create a thread.

Why? See my other comments.
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKQbu1yAxKseXCSR3:-N5oDSqyCg71K7YW1ERP:b-nn6mse) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

You are right, this is only called from `shim_do_sched_getaffinity`. We could have inlined this function in `shim_sched.c` but if you note this function just updates a thread's cpu affinity mask and nothing related to scheduling per se. So, kept this function in `shim_thread.c`

But if you feel we need to inline this, we can do it.
</blockquote></details>

Yes, we don't need to have it as a separate function.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lNm5C-Cz92kveABXO:-N5oDYK8DuDZfWoUmF_E:blj0jbq) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Are you suggesting we remove `BITS_IN_BYTES` macro and simply have `8`?
</blockquote></details>

Yes. Not blocking as other reviewers seemed to be fine with it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lO7Fc31KudnBBfzfl:-N5oDhHo4khVoicUNel5:bopelyl) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
>  If we allocate dynamically, we might also need to keep track of how many elements can be stored, making error checking a little more complex. 

We already keep such info in topology structures.

>  Secondly, when forking we simply copy the mask of the parent to the child and this function will not be called.

We have a function **specifically** for this. It's even in this file.

> So, we might need to allocate dynamically even in do_clone_new_vm flow.

No need, this should be done when creating `struct shim_thread`.

> Thirdly, we might need to make sure the allocation is freed when the thread is terminated.

Yes, we have a `put_thread` exactly for this.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOaq12Q01tamUkEyx:-N5oFdAo67L-P3_RCmYc:b-hc3g94) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L166)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

By document you mean to add something like `The caller of this function must hold the thread lock` in header file where we have the function description right?

Also, I need to add a similar comment in the caller function as well. 
</blockquote></details>

No, just the header.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 174 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lHOpGBr9fskM-JUKQ:-N5oFkjO0JpSKz--qWvJ:b-r6gsyw) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L174)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please clarify. Do you want to remove this macro?
</blockquote></details>

I'm asking why we have this discrepancy and why we use this macro at all
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5oG5jM2jHNkfqVK-NS:b-6b2par) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

So the reason this lock was added is to handle a case where if two threads call this function simultaneously with the same `pid`, then `thread->cpumask` may get tangled. But I think `pid` is a little misleading. If we see the notes section in `sched_setaffinity` it states that ```
The value returned from a call to gettid(2) can be passed in the argument pid
```

So pid is actually tid which is unique for each thread. So, looks like we might not need this lock here. 
@dimakuv given this can we remove the lock?

>because PAL API call is outside of this lock.

@boryspoplawski I am not sure if I fully understand your comment. At least while updating the thread cpumask (`update_thread_affinity`), there is no PAL API involved right?
```

</blockquote></details>

1. Please look at the message before you post it, it's unreadable (you messed the markdown syntax).
2. Two threads can issue this syscall at the same time, and since PAL API call is not synchronized between them (it's done outside of the lock), we can end up with host OS affinity set from the first call and LibOS saving the one from the second call.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 184 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJ3xREPECco9PbWHg:-N5oHeqb3w5G2rfk1ftv:b9gmp5j) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L184)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, for `sched_getaffinity` we fail if `cpumask_size * sizeof(long)` is less than `threads_cnt` . Please see here, https://github.com/gramineproject/gramine/blob/master/libos/src/sys/shim_sched.c#L189
</blockquote></details>

Please add an assert then (I missed this is what we have described in the interface).


<!-- Sent from Reviewable.io -->

2022-06-30 20:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lK1Tx6eho8tkqHePA:-N5q6UeUE71pH-H911hh:b4l1dht) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> pthread_create()

What?

> This function is also called when we create a thread.

Why? See my other comments.
</blockquote></details>

Yes, we can remove this function and inline as we no longer need to get host affinity when cloning a thread but will use the parent's affinity mask.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lO7Fc31KudnBBfzfl:-N5qBE3V2JLTppG_a1hT:b-q3bbr6) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
> We have a function specifically for this. It's even in this file.

Are you referring to `alloc_new_thread()` for allocating the cpumask?

Thanks for the pointers, I will allocate the `thread->cpumask` dynamically. 
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5qEw6A-NAGPhSyysu_:bddy4jw) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
>1. Please look at the message before you post it, it's unreadable (you messed the markdown syntax).

Sorry about it. Let me post my original response again with more clarification.

So, the reason this lock was added is to handle a case where if two threads call this function simultaneously with the same pid, then `thread->cpumask` may get tangled. But I think `pid` is a little misleading. If we see the notes section in `sched_setaffinity` man page it states that,
 
```
The value returned from a call to gettid(2) can be passed in the argument pid.
```

And `gettid` man page states that,
```
gettid() returns the caller's thread ID (TID).  In a single-threaded process, the thread ID is equal to the process ID (PID, as returned by getpid(2)).  In a multithreaded process, all threads have the same PID, but each one has a unique TID
```

So pid is actually tid which is unique for each thread. So, looks like we might not need this lock here.
@dimakuv given this can we remove the lock? 


>2. Two threads can issue this syscall at the same time, and since PAL API call is not synchronized between them (it's done outside of the lock), we can end up with host OS affinity set from the first call and LibOS saving the one from the second call.

@boryspoplawski based on the above comment, do you think there is the possibility of race?


<!-- Sent from Reviewable.io -->

2022-06-30 22:50 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5qnT1L4ADdXP6o5R0k:bbt54bu) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

>1. Please look at the message before you post it, it's unreadable (you messed the markdown syntax).

Sorry about it. Let me post my original response again with more clarification.

So, the reason this lock was added is to handle a case where if two threads call this function simultaneously with the same pid, then `thread->cpumask` may get tangled. But I think `pid` is a little misleading. If we see the notes section in `sched_setaffinity` man page it states that,
 
```
The value returned from a call to gettid(2) can be passed in the argument pid.
```

And `gettid` man page states that,
```
gettid() returns the caller's thread ID (TID).  In a single-threaded process, the thread ID is equal to the process ID (PID, as returned by getpid(2)).  In a multithreaded process, all threads have the same PID, but each one has a unique TID
```

So pid is actually tid which is unique for each thread. So, looks like we might not need this lock here.
@dimakuv given this can we remove the lock? 


>2. Two threads can issue this syscall at the same time, and since PAL API call is not synchronized between them (it's done outside of the lock), we can end up with host OS affinity set from the first call and LibOS saving the one from the second call.

@boryspoplawski based on the above comment, do you think there is the possibility of race?


</blockquote></details>

Yes there is. 5 lines above you call `DkThreadSetCpuAffinity`, it's not guarded by the lock. It can happen in two threads at the same time.


<!-- Sent from Reviewable.io -->

2022-07-01 00:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N5r5rq29MuLkeQ-sYf3:blh8qxj) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes there is. 5 lines above you call `DkThreadSetCpuAffinity`, it's not guarded by the lock. It can happen in two threads at the same time.
</blockquote></details>

Had an offline chat with Borys and the scenario is like this:
2 threads are trying to set the affinity for another thread at the same time. Given this, the race can arise when,
1. thread 1 is setting the host affinity by calling `DkThreadSetCpuAffinity` 
2. thread 2 is setting the host affinity by calling `DkThreadSetCpuAffinity` 
3. thread 2 is saving affinity in LibOS.
4. thread 1 is saving affinity in LibOS.

To avoid this issue, how about we first take the thread->lock for the thread whose affinity needs to be updated, then update the host OS affinity, then save the affinity in LibOS and then release the lock.

```
lock(&thread->lock);
/* Set host OS affinty */
DkThreadSetCpuAffinity();
/* Save the affinity in LibOS */
update_thread_affinity();
unlock(&thread->lock);
```


<!-- Sent from Reviewable.io -->

2022-07-04 07:30 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKxFk0FIPwSTzPvvZ:-N675hLq4tdCxpiKY8i8:brksfu6) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L87)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we shouldn't init from the host but just copy the parent's cpumask. I did this when we fork but missed it here.
</blockquote></details>

Ah, true, we missed it.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N676Nb5AZYIUEC_-dnb:b-nrnt0b) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Had an offline chat with Borys and the scenario is like this:
2 threads are trying to set the affinity for another thread at the same time. Given this, the race can arise when,
1. thread 1 is setting the host affinity by calling `DkThreadSetCpuAffinity` 
2. thread 2 is setting the host affinity by calling `DkThreadSetCpuAffinity` 
3. thread 2 is saving affinity in LibOS.
4. thread 1 is saving affinity in LibOS.

To avoid this issue, how about we first take the thread->lock for the thread whose affinity needs to be updated, then update the host OS affinity, then save the affinity in LibOS and then release the lock.

```
lock(&thread->lock);
/* Set host OS affinty */
DkThreadSetCpuAffinity();
/* Save the affinity in LibOS */
update_thread_affinity();
unlock(&thread->lock);
```


</blockquote></details>

Yes, the proposal by Vijay looks correct. Please do it.


<!-- Sent from Reviewable.io -->

2022-07-06 03:43 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 1 of 6 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/include/shim_thread.h` line 348 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lK1Tx6eho8tkqHePA:-N6GSqgOEniY0_JoHGXP:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L348)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we can remove this function and inline as we no longer need to get host affinity when cloning a thread but will use the parent's affinity mask.
</blockquote></details>

Done
___
*[`LibOS/shim/include/shim_thread.h` line 359 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKQbu1yAxKseXCSR3:-N6GSu1IDReNGSUZFAmD:b-fbgqcy) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/include/shim_thread.h#L359)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, we don't need to have it as a separate function.
</blockquote></details>

Inlined this function.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 141 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lNm5C-Cz92kveABXO:-N6GT-F4ANZCgtPYOnfC:b-mbemeg) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L141)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes. Not blocking as other reviewers seemed to be fine with it.
</blockquote></details>

Left this MACRO as is.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 146 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lO7Fc31KudnBBfzfl:-N6GT49X79CmssSGXHc6:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L146)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> We have a function specifically for this. It's even in this file.

Are you referring to `alloc_new_thread()` for allocating the cpumask?

Thanks for the pointers, I will allocate the `thread->cpumask` dynamically. 


</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOaq12Q01tamUkEyx:-N6GT90N1TQEKAynCpAZ:b89l7q5) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L166)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, just the header.
</blockquote></details>

Since I have inlined the function, this is no longer applicable.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 171 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lOhhhBJf9k7IrhNHm:-N6GTJ2P3iikw_Q27xeK:bo8ddoc) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L171)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move to inside the loop.
</blockquote></details>

Inlined this as part of `shim_do_sched_setaffinity` but have moved the declaration inside the loop.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 174 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lHOpGBr9fskM-JUKQ:-N6GUAeeC_OK0i0vHenn:b-qv05ah) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L174)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm asking why we have this discrepancy and why we use this macro at all
</blockquote></details>

Keeping this Macro as is for this PR.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 178 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lP2c92X3pXde7Ao08:-N6GUGMZBTmwdbNYqt8M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/bookkeep/shim_thread.c#L178)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

You are right, I will create a local copy and then pass it to the helper function.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 173 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lN0rl8qT_U_LfgYLF:-N6GUs_x1a1YXyAQb2i9:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_sched.c#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the proposal by Vijay looks correct. Please do it.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 182 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJnIu08eILbwkegN0:-N6GUvMS-pFwxmY92slq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`,` not needed, `.` missing at the end.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 183 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJjwS-8frEmwFbu0D:-N6GV1ZJ8YKlYu7K4gZz:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L183)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this into the loop.
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 184 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJ3xREPECco9PbWHg:-N6GYh7-CzWmeb8d3DRV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L184)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add an assert then (I missed this is what we have described in the interface).
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJet94X7M9sj7AAV8:-N6GV3AOCxV3sd4dmzJq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Good catch, will add it.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 87 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lKxFk0FIPwSTzPvvZ:-N6GUha8-ys3QFjd1TpZ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/LibOS/shim/src/sys/shim_clone.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, true, we missed it.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_clone.c` line 166 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lLUFU8HKlVcdt7-rc:-N6GUktzEn99ODpvxT0D:b-896fix) ([raw file](https://github.com/gramineproject/gram [...]

2022-07-06 04:00 UTC, vijaydhanraj commented
Jenkins, test this please.

2022-07-06 11:58 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 80 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IIiXbDlLammEnxLja:-N6IIiXbDlLammEnxLjb:bg9nunn) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L80)):*
> ```C
>     INIT_LIST_HEAD(thread, list);
>     /* default value as sigalt stack isn't specified yet */
>     thread->signal_altstack.ss_flags = SS_DISABLE;
> ```

Please move these four lines right-before `return 0;`. This way we'll have a more readable flow of this function: first allocate all objects, then initialize the other fields.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 87 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IIP4a6gIDAQtGV8L9:-N6IIP4a6gIDAQtGV8LA:b-ulbpez) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L87)):*
> ```C
>     thread->cpumask = calloc(1, bitmask_size_in_bytes);
>     if (!thread->cpumask)
>         return NULL;
> ```

You forgot to free the already-allocated things. Please do:
```
    if (!thread->cpumask) {
        destroy_pollable_event(&thread->pollable_event);
        destroy_lock(&thread->lock);
        free(thread);        
        return NULL;
    }
```
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 217 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJPZi7qFwNEmadwFF:-N6IJPZi7qFwNEmadwFG:b-key44o) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L217)):*
> ```C
>     if (ret < 0) {
>         put_thread(cur_thread);
>         return pal_to_unix_errno(ret);;
> ```

Since we're here, could you fix this typo: `;;` -> `;`
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 231 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJNZe-FLS_35lAbN-:-N6IJNZe-FLS_35lAbN0:b-8zakv1) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L231)):*
> ```C
> 
>     set_cur_thread(cur_thread);
>     add_thread(cur_thread);
> ```

Please move these two lines right-before `return 0;`. This way we'll have a more readable flow of this function: first allocate all objects, then initialize the other fields.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 321 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJtto10hT0H21iavh:-N6IJtto10hT0H21iavi:b-xakji5) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L321)):*
> ```C
> 
>     /* Linux sets the same cpu affinity mask for the forked/cloned child as the parent. Following
>      * the same convention here by copying the parent's cpu affinity mask to the child. */
> ```

To be honest, this comment sounds redundant. I would just remove it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 609 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IK8xH20Lu1ZyELqBE:-N6IK8xI6rC0I0YDycF4:bh6h8m8) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L609)):*
> ```C
>         size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
>                                        sizeof(unsigned long);
>         new_thread->cpumask = (unsigned long*)(base +  ADD_CP_OFFSET(bitmask_size_in_bytes));
> ```

`base +  ` -> `base + ` (remove one redundant space)
___
*[`LibOS/shim/src/sys/shim_sched.c` line 178 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IKdUQE5JeTnGGdQes:-N6IKdUQE5JeTnGGdQet:bp4mtyk) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L178)):*
> ```C
>     if (!cpumask) {
>         put_thread(thread);
>         return -ENOMEM;
> ```

Instead of these two lines, you should do:
```
    ret = -ENOMEM;
    goto out;
```
___
*[`LibOS/shim/src/sys/shim_sched.c` line 207 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ILiHQ0MrfRZXlBJnO:-N6ILiHQ0MrfRZXlBJnP:b9kwyxn) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L207)):*
> ```C
>      * previous affinity before copying the new affinity. */
>     memset(thread->cpumask, 0, bitmask_size_in_bytes);
>     memcpy(thread->cpumask, user_mask_ptr, MIN(bitmask_size_in_bytes, cpumask_size));
> ```

`user_mask_ptr` -> `cpumask`

You need to update the thread's cpumask with "intersection of the set specified in the mask argument and the set of CPUs actually present on the system". Not just the mask argument.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 212 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ILyD-3yrdInQl2x5G:-N6ILyD-3yrdInQl2x5H:btihnb5) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L212)):*
> ```C
> out:
>     unlock(&thread->lock);
>     put_thread(thread);
> ```

You forgot to `free(cpumask)`
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJet94X7M9sj7AAV8:-N6IMam3-F0ycLtu9Q09:b-ne5p5l) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, even simpler: `return -PAL_ERROR_INVAL;`

And at the end of the function, simply `return 0;`
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IMjSIAGitWKE2aDDV:-N6IMjSJ0eu85peWTQTR:b-vzmshk) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/Pal/src/host/Linux-SGX/db_threading.c#L183)):*
> ```C
> 
>     assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);
>     /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
> ```

This is not very readable:
```
    size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;

    assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);
    /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
```

Please rearrange the empty line like this:
```
    size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;
    assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);

    /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
```


<!-- Sent from Reviewable.io -->

2022-07-06 16:22 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 80 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IIiXbDlLammEnxLja:-N6IpOaV7FXDTtaKjoo-:b7qt91b) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move these four lines right-before `return 0;`. This way we'll have a more readable flow of this function: first allocate all objects, then initialize the other fields.
</blockquote></details>

Yes, makes sense. Moved `cpumask` allocation right after the thread allocation.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 87 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IIP4a6gIDAQtGV8L9:-N6Ipk15-qZ2YLwCJaIm:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to free the already-allocated things. Please do:
```
    if (!thread->cpumask) {
        destroy_pollable_event(&thread->pollable_event);
        destroy_lock(&thread->lock);
        free(thread);        
        return NULL;
    }
```
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 217 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJPZi7qFwNEmadwFF:-N6Iqw-u-ezlQxIMmhb0:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, could you fix this typo: `;;` -> `;`
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 231 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJNZe-FLS_35lAbN-:-N6IsdIU50LVcLnZUR2e:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move these two lines right-before `return 0;`. This way we'll have a more readable flow of this function: first allocate all objects, then initialize the other fields.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 321 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IJtto10hT0H21iavh:-N6Iukw-1TKvixzEkuGM:baixsut) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L321)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, this comment sounds redundant. I would just remove it.
</blockquote></details>

sure, removed it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 609 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IK8xH20Lu1ZyELqBE:-N6Iv2nK-YjR-vP0B0nu:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/bookkeep/shim_thread.c#L609)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`base +  ` -> `base + ` (remove one redundant space)
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 178 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IKdUQE5JeTnGGdQes:-N6IwwxQ33qmBMSJZlN2:b-o7fnca) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of these two lines, you should do:
```
    ret = -ENOMEM;
    goto out;
```
</blockquote></details>

I moved the allocation out of the lock. This simplifies freeing of resources.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 207 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ILiHQ0MrfRZXlBJnO:-N6J-CF85h9ZbA4iHON8:bpq51te) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`user_mask_ptr` -> `cpumask`

You need to update the thread's cpumask with "intersection of the set specified in the mask argument and the set of CPUs actually present on the system". Not just the mask argument.
</blockquote></details>

Yes, I missed it. I added a comment to not miss this again.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 212 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ILyD-3yrdInQl2x5G:-N6J0N5k39i6A_B_PV83:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/LibOS/shim/src/sys/shim_sched.c#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to `free(cpumask)`
</blockquote></details>

Done.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJet94X7M9sj7AAV8:-N6J9Jht28S6enSFeTuZ:b63an0c) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, even simpler: `return -PAL_ERROR_INVAL;`

And at the end of the function, simply `return 0;`
</blockquote></details>

`return 0` might not be correct as `sched_getaffinity` can return the number of bytes copied into the mask buffer. So, instead of `break`, I simply `return -PAL_ERROR_INVAL`.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 183 at r14](https://reviewable.io/reviews/gramineproject/gramine/631#-N6IMjSIAGitWKE2aDDV:-N6J0U1QE3GJKzqOam_I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8b9576971f366c65a785d4d60a9c2b1ea9e8a47c/Pal/src/host/Linux-SGX/db_threading.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not very readable:
```
    size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;

    assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);
    /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
```

Please rearrange the empty line like this:
```
    size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;
    assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);

    /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 20:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/sys/shim_sched.c` line 182 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JlO6J8yQdwl_rcLhP:-N6KC3eZ5VtdSiETRhZM:b-jr9oc7) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/sys/shim_sched.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What? You cal `DkThreadSetCpuAffinity` **before** any verification.
</blockquote></details>

We do have preliminary checks, https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_sched.c#L177 right?

If the host is untrusted, it can alter the affinity mask as it may please. So, I have not added the offline check.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJet94X7M9sj7AAV8:-N6KBbfLBql5LWEe1g4G:bqrcs7p) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And our documentation of this function states: `\returns 0 on success, negative error code on failure`. Please fix.
</blockquote></details>

I see, will fix it.


<!-- Sent from Reviewable.io -->

2022-07-07 01:09 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 4 of 7 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 65 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JeThq0uq8tS5lOms2:-N6K_LZMBun1vSBwJYBI:b32n8ta) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/bookkeep/shim_thread.c#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This comment is pointless. The purpose of this field should be explained in the struct definition.
</blockquote></details>

Removed it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 66 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JgZcNAWAN_K2iG0SH:-N6K_NU3DPhL3oHp8-dW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/bookkeep/shim_thread.c#L66)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK makes sense. We don't set and use the affinity mask for these threads anyway. I will just do allocation in `get_new_thread ` and `init_main_thread`.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 233 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6Jhsm2BFDVv6OLCXzm:-N6Kf6FE8uZ7nHf7vaB6:b32n8ta) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/bookkeep/shim_thread.c#L233)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this comment? It just states what the code does.
</blockquote></details>

Removed it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 420 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JiQOv1l_yt27fBpQm:-N6Kf8ev2Vnfc5eMhB3M:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/bookkeep/shim_thread.c#L420)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This `if` is useless, remove it please (`free` works on `NULL`)
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 168 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JkAj1CDS40NU9m4k6:-N6Kai4b5MT48qCe7YX4:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/sys/shim_sched.c#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`malloc` is enough, we immediately overwrite the memory.
</blockquote></details>

Done.
___
*[`LibOS/shim/src/sys/shim_sched.c` line 182 at r15](https://reviewable.io/reviews/gramineproject/gramine/631#-N6JlO6J8yQdwl_rcLhP:-N6KHFS8D7Ks7kJwXQBz:b5tnkcm) ([raw file](https://github.com/gramineproject/gramine/blob/a69f362f5dc3c2f6ec041a251ca13378cd84fa48/LibOS/shim/src/sys/shim_sched.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I have no idea what you are trying to say.
Just please move these checks before call to `DkThreadSetCpuAffinity`.
</blockquote></details>

I was trying to reason why the offline check was needed before we call `DkThreadSetCpuAffinity`. If the host is not malicious it does this check anyway and if the host is malicious, any value we pass can be overridden.

But I have made the change as suggested.


<!-- Sent from Reviewable.io -->

2022-07-07 08:15 UTC, boryspoplawski requested changes
> Reviewed 2 of 3 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 152 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6McfjlDczR1xRuJPJt:-N6McfjlDczR1xRuJPJu:b-ohjams) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/LibOS/shim/src/bookkeep/shim_thread.c#L152)):*
> ```C
>     }
> 
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
> ```

Why it's here?  Please move to right before call to `DkThreadGetCpuAffinity`
___
*[`LibOS/shim/src/sys/shim_sched.c` line 214 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6Mi-Oz0gx7zvP-F1pn:-N6Mi-P-BXxMgGjs2Tgj:b-8wrpka) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/LibOS/shim/src/sys/shim_sched.c#L214)):*
> ```C
>     ret = 0;
> out:
>     free(cpumask);
> ```

NP: please move free after unlock
___
*[`Pal/include/pal/pal.h` line 511 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6MiAa33Ia7ViVUOfEF:-N6MiAa33Ia7ViVUOfEG:b-qdpcz4) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/Pal/include/pal/pal.h#L511)):*
> ```objc
>  * \param cpu_mask      Pointer to hold the current CPU mask.
>  *
>  * \returns number of bytes copied into the `cpu_mask` on success, negative error code on failure.
> ```

What's the point?
1) We return sizes via out argument, we do not mix them with error codes
2) No caller needs this value.
I would rather fix this function, the docs were fine (it's the implementation that was buggy).


<!-- Sent from Reviewable.io -->

2022-07-07 10:10 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r15, 2 of 3 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`Pal/include/pal/pal.h` line 511 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6MiAa33Ia7ViVUOfEF:-N6N7Z_b3xCJSscnz5gY:bl4la0c) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/Pal/include/pal/pal.h#L511)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point?
1) We return sizes via out argument, we do not mix them with error codes
2) No caller needs this value.
I would rather fix this function, the docs were fine (it's the implementation that was buggy).
</blockquote></details>

+1 to Borys's point 2. Just `return 0` on success in this function.
___
*[`Pal/src/host/Linux-SGX/db_threading.c` line 189 at r13](https://reviewable.io/reviews/gramineproject/gramine/631#-N5lJet94X7M9sj7AAV8:-N6N7ms7DzmYhsNv1F9c:bo68jl5) ([raw file](https://github.com/gramineproject/gramine/blob/b7eefc7389dca486420bf75a5e6c85272e783ad1/Pal/src/host/Linux-SGX/db_threading.c#L189)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I see, will fix it.
</blockquote></details>

As Borys mentioned in the other comment, there are no callers that use this return value. So it's easier to keep the documentation as it was and change the return value to just `return 0`.


<!-- Sent from Reviewable.io -->

2022-07-07 19:04 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 152 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6McfjlDczR1xRuJPJt:-N6P0gnlDlETgSSFmfgn:b-hbzzja) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/LibOS/shim/src/bookkeep/shim_thread.c#L152)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm talking about this whole block (together with malloc)
</blockquote></details>

OK, got it.
___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 327 at r18](https://reviewable.io/reviews/gramineproject/gramine/631#-N6P0vlR7bLeLFYqagnD:-N6P0vlR7bLeLFYqagnE:bhdh35n) ([raw file](https://github.com/gramineproject/gramine/blob/ebe4d8411367ce55cfddd86fd8106ae78fc7907b/LibOS/shim/src/bookkeep/shim_thread.c#L327)):*
> ```C
>     set_handle_map(thread, map);
> 
>     memcpy(thread->cpumask, cur_thread->cpumask, bitmask_size_in_bytes);
> ```

@boryspoplawski Do you prefer moving initialization of `bitmask_size_in_byte` and `malloc` before the `memcpy` as well? Or can we avoid it here due to the lock?


<!-- Sent from Reviewable.io -->

2022-07-07 19:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 327 at r18](https://reviewable.io/reviews/gramineproject/gramine/631#-N6P0vlR7bLeLFYqagnD:-N6P4Dvg1S6_w4dkc9ad:b-cp004o) ([raw file](https://github.com/gramineproject/gramine/blob/ebe4d8411367ce55cfddd86fd8106ae78fc7907b/LibOS/shim/src/bookkeep/shim_thread.c#L327)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@boryspoplawski Do you prefer moving initialization of `bitmask_size_in_byte` and `malloc` before the `memcpy` as well? Or can we avoid it here due to the lock?
</blockquote></details>

No, here it's fine, we have a nice logical split of allocate then initialize and this memcpy has to stay under lock, no need to move malloc under it.


<!-- Sent from Reviewable.io -->

2022-07-07 19:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 6 of 7 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`LibOS/shim/src/bookkeep/shim_thread.c` line 152 at r17](https://reviewable.io/reviews/gramineproject/gramine/631#-N6McfjlDczR1xRuJPJt:-N6PDhW71dmmoUOFIX1k:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ceb9455b120e51d51bfb34c73273ad848b918207/LibOS/shim/src/bookkeep/shim_thread.c#L152)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, got it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 20:31 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-07-08 07:01 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-07-10 20:13 UTC, mkow requested changes
> Reviewed 8 of 10 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 10 of 12 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKQvgEy3ziy0Gpx-k):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`-- commits` line 2 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6XocK21JKkCncFJOfb):*




_Suggestion:_
```
[LibOS]
```
___
*[`-- commits` line 5 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6XoqbfDK8AVxs-lfpN):*




_Suggestion:_
```
  This commit implements storing per-thread CPU affinity in the LibOS
  and returning it when queried from the user (after validation).
```
___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6dhX_m-AepidOrkGcQ:b-c4xwo1) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
> ```objc
> 
>     /* Current CPU affinity mask for this thread. */
>     uint64_t* cpumask;
> ```

What's the size of this array? Could you just store it in another field?
___
*[`libos/src/bookkeep/libos_thread.c` line 223 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dcTYD2eFUPvGcCf18:-N6dcTYD2eFUPvGcCf19:bhets32) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L223)):*
> ```C
>     cur_thread->pal_handle = g_pal_public_state->first_thread;
> 
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
> ```

By "size" we always mean "size in bytes" in Gramine codebase. Ditto for all other places.



_Code quote:_
```C
bitmask_size_in_bytes
```
___
*[`libos/src/bookkeep/libos_thread.c` line 227 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ddnmz4Y20TCppZoRe:-N6ddnmz4Y20TCppZoRf:bwc5xei) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L227)):*
> ```C
>     cur_thread->cpumask = malloc(bitmask_size_in_bytes);
>     if (!cur_thread->cpumask) {
>         log_error("Cannot allocate cpumask for the initial thread!");
> ```

We don't print errors in other places like this, if we printed a custom error on all possible failure paths at the lowest level then 1/4 of our code lines would start with `log_error(...)`.
___
*[`libos/src/sys/libos_sched.c` line 178 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6diMaS-3sj2Z4RCOwh:-N6diMaS-3sj2Z4RCOwi:ba6wyf2) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L178)):*
> ```C
>     /* Verify validity of the CPU affinity (e.g. that it contains at least one online core). */
>     size_t threads_cnt = g_pal_public_state->topo_info.threads_cnt;
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(threads_cnt) * sizeof(unsigned long);
> ```

You have both `cpumask_size` and `bitmask_size` in this function, which are synonyms, but actually have different values (and their real meanings).
___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N6dio5n3_oBrU5SN8dH:b2n2b70) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
> ```C
>         if (cpumask[idx] & 1UL << (i % BITS_IN_TYPE(unsigned long))) {
>             if (!g_pal_public_state->topo_info.threads[i].is_online) {
>                 /* cpumask contains a CPU that is currently offline, remove it from the cpumask */
> ```

We have more than one CPU mask in this function.



_Suggestion (i):_
```C
`cpumask`
```



_Suggestion (ii):_
```C
`cpumask`
```
___
*[`libos/src/sys/libos_sched.c` line 231 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dern-4aAOzyZYjADy:-N6dern-4aAOzyZYjADz:bmnp8qn) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L231)):*
> ```C
>     /* Linux kernel bitmap is based on long. So according to its implementation, round up the result
>      * to sizeof(long) */
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(threads_cnt) * sizeof(long);
> ```

ditto (local variable naming)
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 174 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dfjXM7ZcmbFNVIemK:-N6dfjXM7ZcmbFNVIemL:b-ftuubw) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L174)):*
> ```C
> }
> 
> int _PalThreadGetCpuAffinity(PAL_HANDLE thread, size_t cpumask_size, unsigned long* cpu_mask) {
> ```

"size" means "size in bytes" in our codebase



_Suggestion:_
```C
unsigned long* cpu_mask, size_t cpumask_cnt
```
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 180 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dg7op9kvQ6hnytD4E:-N6dg7op9kvQ6hnytD4F:beccmrb) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L180)):*
> ```C
> 
>     size_t threads_cnt = g_pal_public_state.topo_info.threads_cnt;
>     assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);
> ```

This assert is wrong, you're comparing byte size to bit size.



_Code quote:_
```C
assert(cpumask_size * sizeof(unsigned long) >= threads_cnt);
```
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 186 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhHdY0nF4LJHUx_wp:-N6dhHdY0nF4LJHUx_wq:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L186)):*
> ```C
>         size_t idx = i / BITS_IN_TYPE(unsigned long);
>         if (cpu_mask[idx] & 1UL << (i % BITS_IN_TYPE(unsigned long))) {
>             if (!g_pal_public_state.topo_info.threads[i].is_online) {
> ```





_Suggestion:_
```C
&& !g_pal_public_state.topo_info.threads[i].is_online) {
```


<!-- Sent from Reviewable.io -->

2022-07-10 20:56 UTC, boryspoplawski reviewed
> Reviewed 6 of 10 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6dqf6r55MyrPjkZIMB:b-7y1ukx) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the size of this array? Could you just store it in another field?
</blockquote></details>

It's constant - taken from topology structs.


<!-- Sent from Reviewable.io -->

2022-07-10 21:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6dzhxl2T2iQPUGKEMw:bj8mm4f) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's constant - taken from topology structs.
</blockquote></details>

I know, because I just read that whole PR. But I won't know this in a month when reading this header, especially considering that this size isn't directly taken from topology - it's calculated from it (and these calculations are duplicated in many places).


<!-- Sent from Reviewable.io -->

2022-07-10 23:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6eLsymAZHBoiTXp-Y-:b-hzyc8z) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know, because I just read that whole PR. But I won't know this in a month when reading this header, especially considering that this size isn't directly taken from topology - it's calculated from it (and these calculations are duplicated in many places).
</blockquote></details>

But there is no point in storing the length in here if it's the same for all threads.
At most add a global variable or define


<!-- Sent from Reviewable.io -->

2022-07-11 06:50 UTC, dimakuv requested changes
> Reviewed 5 of 10 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`-- commits` line 2 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6XocK21JKkCncFJOfb):*
@vijaydhanraj You probably got confused that we renamed the `LibOS/` directory to `libos/`.

This was only about *directory renaming*. The component's name is still written as `LibOS` (Library OS), including in our comments and commit messages. Only the directory is written with all-small letters.
___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6fyyCZ5V-qKJr8ML1B:bn557ga) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But there is no point in storing the length in here if it's the same for all threads.
At most add a global variable or define
</blockquote></details>

...Or add a comment here:
```
/* Current CPU affinity mask for this thread; its size is calculated at runtime to hold
 * `g_pal_public_state->topo_info.threads_cnt` bits. */
```
___
*[`libos/src/bookkeep/libos_thread.c` line 223 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dcTYD2eFUPvGcCf18:-N6fzuSxBgqMXmje2SPT:b-t1hmpt) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L223)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

By "size" we always mean "size in bytes" in Gramine codebase. Ditto for all other places.
</blockquote></details>

...deciphering Michal's comment: @vijaydhanraj please rename to simply `bitmask_size`.
___
*[`libos/src/bookkeep/libos_thread.c` line 224 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-Wxf6q4EEhv1kJ9g:-N6g-Wxf6q4EEhv1kJ9h:b-4lvlme) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L224)):*
> ```C
> 
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
>                                    sizeof(unsigned long);
> ```

Your cpumask is of type `uint64_t*`, so here you should also use `sizeof(uint64_t)` for uniformity of types.

Here and everywhere else in this PR.
___
*[`libos/src/bookkeep/libos_thread.c` line 227 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ddnmz4Y20TCppZoRe:-N6g-79EC1-sWfcFR2SR:bazyja6) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L227)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We don't print errors in other places like this, if we printed a custom error on all possible failure paths at the lowest level then 1/4 of our code lines would start with `log_error(...)`.
</blockquote></details>

...deciphering Michal's comment: we typically do not print errors on `malloc()`, because this error will propagate to the upper levels, and we'll end up with `ENOMEM` error message anyway.
___
*[`libos/src/bookkeep/libos_thread.c` line 282 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-QCCA966EhEYF75F:-N6g-QCCA966EhEYF75G:b-q36e7x) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L282)):*
> ```C
>     }
> 
>     size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
> ```

ditto (simply `bitmask_size`)
___
*[`libos/src/bookkeep/libos_thread.c` line 611 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-VaW7oiUVtwpBrih:-N6g-VaW7oiUVtwpBrii:b-q36e7x) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L611)):*
> ```C
>         }
> 
>         size_t bitmask_size_in_bytes = BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) *
> ```

ditto (simply `bitmask_size`)
___
*[`libos/src/sys/libos_sched.c` line 178 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6diMaS-3sj2Z4RCOwh:-N6g093X1K-PYkdIyUyF:bh7qpz9) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You have both `cpumask_size` and `bitmask_size` in this function, which are synonyms, but actually have different values (and their real meanings).
</blockquote></details>

Maybe `bitmask_size` -> `thread_cpumask_size`?
___
*[`libos/src/sys/libos_sched.c` line 231 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dern-4aAOzyZYjADy:-N6g0FWd7xRm1vV5eBtP:bh7qpz9) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L231)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (local variable naming)
</blockquote></details>

Maybe `bitmask_size` -> `thread_cpumask_size`?


<!-- Sent from Reviewable.io -->

2022-07-11 11:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6gyXEs4DzYWL3TnOym:b-ds6zuh) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
> But there is no point in storing the length in here if it's the same for all threads.
> At most add a global variable or define

The point is to have explicit size saved here, instead of recalculating it in 5 different places. I'd be fine with just a comment if it was directly taken from some other variable, but here you need non-obvious calculations.
I don't think these 8 bytes used per thread matter, and we gain much safer and saner memory operations.
___
*[`libos/src/bookkeep/libos_thread.c` line 223 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dcTYD2eFUPvGcCf18:-N6gzRGhBUlF_DXTU4by:b-5ebo7e) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...deciphering Michal's comment: @vijaydhanraj please rename to simply `bitmask_size`.
</blockquote></details>

@dimakuv but it's not just about this place, the whole PR has this problem.


<!-- Sent from Reviewable.io -->

2022-07-11 12:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6h7R9c7o7mV7q2Hg80:ber4dq1) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> But there is no point in storing the length in here if it's the same for all threads.
> At most add a global variable or define

The point is to have explicit size saved here, instead of recalculating it in 5 different places. I'd be fine with just a comment if it was directly taken from some other variable, but here you need non-obvious calculations.
I don't think these 8 bytes used per thread matter, and we gain much safer and saner memory operations.
</blockquote></details>

And how is that better from storing this in a global variable? 


<!-- Sent from Reviewable.io -->

2022-07-11 12:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6hF5o-7NjLKBZEfcZ2:b-x8eywh) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And how is that better from storing this in a global variable? 
</blockquote></details>

It would also be acceptable for me, but seems more complicated (it would be placed somewhere else, so you'd need a comment in both places to "connect" these two variables). I just really like the straightforward convention of having array_ptr+elem_count next to each other (both in structures and function signatures), it's simple, readable, and hard to make errors in it.


<!-- Sent from Reviewable.io -->

2022-07-13 02:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 8 of 12 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKQvgEy3ziy0Gpx-k):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

@mkow are you referring to the `libos` component name?
___
*[`-- commits` line 2 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6XocK21JKkCncFJOfb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj You probably got confused that we renamed the `LibOS/` directory to `libos/`.

This was only about *directory renaming*. The component's name is still written as `LibOS` (Library OS), including in our comments and commit messages. Only the directory is written with all-small letters.
</blockquote></details>

Yes, you are right, I thought we also should rename the components that way. But I have fixed this now. Sorry for the force push.
___
*[`-- commits` line 5 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6XoqbfDK8AVxs-lfpN):*
Reworded as suggested.
___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N6ozAikAww3ARW3GQw8:b-771cou) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It would also be acceptable for me, but seems more complicated (it would be placed somewhere else, so you'd need a comment in both places to "connect" these two variables). I just really like the straightforward convention of having array_ptr+elem_count next to each other (both in structures and function signatures), it's simple, readable, and hard to make errors in it.
</blockquote></details>

I have created a new field as part of `libos_thread` struct to store the `cpumask` size.
___
*[`libos/src/bookkeep/libos_thread.c` line 223 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dcTYD2eFUPvGcCf18:-N6ozfju5xh-Nwe2_nEW:b-kfxqv2) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L223)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv but it's not just about this place, the whole PR has this problem.
</blockquote></details>

Removed this variable and used the one stored as part of `libos_thread` struct.
___
*[`libos/src/bookkeep/libos_thread.c` line 224 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-Wxf6q4EEhv1kJ9g:-N6p0LjUCyEjjAh2w6z7:b9pqy8d) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Your cpumask is of type `uint64_t*`, so here you should also use `sizeof(uint64_t)` for uniformity of types.

Here and everywhere else in this PR.
</blockquote></details>

I have changed this to `unsigned long*` from `uint64_t*` to be uniform.
___
*[`libos/src/bookkeep/libos_thread.c` line 227 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6ddnmz4Y20TCppZoRe:-N6ofM5NBDeDU0ur0Nwk:bx84jzj) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

...deciphering Michal's comment: we typically do not print errors on `malloc()`, because this error will propagate to the upper levels, and we'll end up with `ENOMEM` error message anyway.
</blockquote></details>

Got it, I have removed the error logs.
___
*[`libos/src/bookkeep/libos_thread.c` line 282 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-QCCA966EhEYF75F:-N6p0OixEWvxL10tzJ6Z:b-av8wyb) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (simply `bitmask_size`)
</blockquote></details>

Removed this and used the cpumask size stored as part of `libos_thread` struct.
___
*[`libos/src/bookkeep/libos_thread.c` line 611 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6g-VaW7oiUVtwpBrih:-N6p0Z761fGISY99dos5:bi8vwcd) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/bookkeep/libos_thread.c#L611)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (simply `bitmask_size`)
</blockquote></details>

Removed this and used the cpumask size stored as part of `libos_thread` struct.
___
*[`libos/src/sys/libos_sched.c` line 178 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6diMaS-3sj2Z4RCOwh:-N6og3riBpfxcmzSJAH8:b-19fhe4) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe `bitmask_size` -> `thread_cpumask_size`?
</blockquote></details>

I have renamed the user-supplied `cpumask_size` to `user_mask_size` and instead of calculating `bitmask_size`, access it from `libos_thread` struct. 
___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N6omwo_4vqeGdMyXv_q:bl8rc4u) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We have more than one CPU mask in this function.
</blockquote></details>

I think you are getting confused between `user_mask_ptr` which is a user-supplied cpumask vs `cpumask` which is a local copy of the user-supplied cpumask.

Note that, once the local copy is made, we no longer use `user_mask_ptr`. So `cpumask` in this comment refers to the local copy.

How about we change the comment as below?
```
 /* User-supplied cpumask contains a CPU that is currently offline, so remove it from the local copy `cpumask` */
```
___
*[`libos/src/sys/libos_sched.c` line 231 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dern-4aAOzyZYjADy:-N6op6LtExnZMFSCXt7b:b-njwk2t) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe `bitmask_size` -> `thread_cpumask_size`?
</blockquote></details>

Removed this and used the one stored as part of the `libos_thread` struct.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 174 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dfjXM7ZcmbFNVIemK:-N6owLSzDujelUR-DfQD:byddj0o) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L174)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"size" means "size in bytes" in our codebase
</blockquote></details>

`cpumask_size` is the size in bytes.

Please note I haven't modified this as part of this PR. I know our preference now is `array + c [...]

2022-07-13 07:41 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N6qTzps4H7GmPePqccl:b-rq4zvs) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think you are getting confused between `user_mask_ptr` which is a user-supplied cpumask vs `cpumask` which is a local copy of the user-supplied cpumask.

Note that, once the local copy is made, we no longer use `user_mask_ptr`. So `cpumask` in this comment refers to the local copy.

How about we change the comment as below?
```
 /* User-supplied cpumask contains a CPU that is currently offline, so remove it from the local copy `cpumask` */
```
</blockquote></details>

FWIW, I like the comment proposed by Vijay.
___
*[`libos/src/sys/libos_sched.c` line 144 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUv9B9ChMQz6QvXDd:-N6qUv9CD7O8NJIyZTna:bh7w9pf) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L144)):*
> ```C
> }
> 
> long libos_syscall_sched_setaffinity(pid_t pid, unsigned int user_mask_size,
> ```

Now we have a discrepancy in names for `libos_syscall_sched_setaffinity` function -- the other name, somewhere in our LibOS header files -- is still `cpumask_size`. So ideally we need to update the name also there, in the header file.

But at this point I would just wait for opinion from @mkow, not to re-do the same work several times.
___
*[`libos/src/sys/libos_sched.c` line 220 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qVDuO4fBlFR4c9iiZ:-N6qVDuO4fBlFR4c9ii_:b-52q89p) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L220)):*
> ```C
> }
> 
> long libos_syscall_sched_getaffinity(pid_t pid, unsigned int user_mask_size,
> ```

ditto (discrepancy in the argument name)
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 190 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUh9gEwx9_jnhXgZ_:-N6qUh9gEwx9_jnhXgZa:bc126dd) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/pal/src/host/linux-sgx/pal_threading.c#L190)):*
> ```C
>                 return -PAL_ERROR_INVAL;
>             }
>         }
> ```

These four lines have a wrong indentation now. Please shift them to the left by 4 spaces.


<!-- Sent from Reviewable.io -->

2022-07-13 16:13 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 144 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUv9B9ChMQz6QvXDd:-N6sKJtI3Q7AYrwkSKfo:b-gatwvh) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L144)):*
>Now we have a discrepancy in names for libos_syscall_sched_setaffinity

Yes, I will update the function declaration as well once Michal confirms.


<!-- Sent from Reviewable.io -->

2022-07-20 15:16 UTC, mkow requested changes
> Reviewed 1 of 5 files at r14, 1 of 4 files at r18.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7RA4Ij8BGYlFgnIf6y:bnwmw2h) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have created a new field as part of `libos_thread` struct to store the `cpumask` size.
</blockquote></details>

But you again introduced that problem which we discussed at the beginning of the review - now you have a `type* array` and `size_t array_size`, which is very confusing (e.g. can `array_size` not be a multiple of `sizeof(type)`?). Please store and use elements count instead everywhere.


<!-- Sent from Reviewable.io -->

2022-07-20 15:24 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7RByoHAY8QDbNzmRR2:b-72y8vt) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
> I just really like the straightforward convention of having array_ptr+elem_count next to each other (both in structures and function signatures), it's simple, readable, and hard to make errors in it.

If you have length saved, then it looks like it can be different in different threads. Then what if it's bigger than expected (the value derived from topo info)? What if it's smaller?
To me saving this in thread struct is more complicated and more confusing.


<!-- Sent from Reviewable.io -->

2022-07-20 23:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7SsE677exXGk8S4G-k:bv17o1y) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
Just to make it clear to others reading this thread: There are two things here, which are orthogonal:
- Whether the size of a cpu mask array should be passed as byte size or element count - here I believe that everyone agrees that it should be the number of elements.
- Whether to save the size of `cpumask`, and if so, then where? (the alternative is to calculate it in all sites which use it) Here I strongly want it to be saved somewhere, I prefer it next to `cpumask`, but I could also accept a global (although I like it less).

> If you have length saved, then it looks like it can be different in different threads.

Yup, that's the only real downside I see about this approach, but I still prefer it for readability.

> Then what if it's bigger than expected (the value derived from topo info)? What if it's smaller?

But you can have these problems also when it's saved globally?


<!-- Sent from Reviewable.io -->

2022-07-21 10:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7VBa0e9HadTStiRWke:b-nghdyh) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
> Whether the size of a cpu mask array should be passed as byte size or element count - here I believe that everyone agrees that it should be the number of elements.

Yes (at least I do)

> Yup, that's the only real downside I see about this approach, but I still prefer it for readability.

But to me it decreases readability, because now I have to think why the code is correct and why this value matches what's expected.

> But you can have these problems also when it's saved globally?

Yes, to some extent - at least there is only one global value, which indicates it's the same for all threads.
There's also option of macro function, that would return the expected value, e.g.
```c
#define SOMETHING() (BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) * sizeof(unsigned long))
```
I dislike all proposed options (all of them have issues), but I think I prefer the macro the most.


<!-- Sent from Reviewable.io -->

2022-07-21 13:00 UTC, mkow reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/631#-N3dKQvgEy3ziy0Gpx-k):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow are you referring to the `libos` component name?
</blockquote></details>

I think you applied only a half of the suggestion above and despite this posted "Done.".
___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7Vplsw0x4jDCyId0UH:b-cy1hwz) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Whether the size of a cpu mask array should be passed as byte size or element count - here I believe that everyone agrees that it should be the number of elements.

Yes (at least I do)

> Yup, that's the only real downside I see about this approach, but I still prefer it for readability.

But to me it decreases readability, because now I have to think why the code is correct and why this value matches what's expected.

> But you can have these problems also when it's saved globally?

Yes, to some extent - at least there is only one global value, which indicates it's the same for all threads.
There's also option of macro function, that would return the expected value, e.g.
```c
#define SOMETHING() (BITS_TO_LONGS(g_pal_public_state->topo_info.threads_cnt) * sizeof(unsigned long))
```
I dislike all proposed options (all of them have issues), but I think I prefer the macro the most.
</blockquote></details>

I'm ok with a macro. Not great, not terrible, at least much better than the version with copy-pasted calculations.


<!-- Sent from Reviewable.io -->

2022-07-22 05:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @michal, and @mkow)

___
*[`libos/include/libos_thread.h` line 132 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dhX_m-AepidOrkGcP:-N7Z-Mdh7axxzczzDwN9:b-nd6hp0) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/include/libos_thread.h#L132)):*
> Whether the size of a cpu mask array should be passed as byte size or element count - here I believe that everyone agrees that it should be the number of elements.

Created a CPU affinity clean-up commit, which ensures array + cnt behavior for cpumask and its size.

>Whether to save the size of cpumask, and if so, then where? (the alternative is to calculate it in all sites which use it) Here I strongly want it to be saved somewhere, I prefer it next to cpumask, but I could also accept a global (although I like it less).

Created a global MACRO and defined it in `libos_thread.h`
___
*[`libos/src/sys/libos_sched.c` line 178 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6diMaS-3sj2Z4RCOwh:-N7YwZTU7_6DnM8sBx_Y:b-8g1v3u) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L178)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have renamed the user-supplied `cpumask_size` to `user_mask_size` and instead of calculating `bitmask_size`, access it from `libos_thread` struct. 
</blockquote></details>

The size field is removed now, and as suggested using a MACRO. 
___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N7YutwC61uzFCXQCzKh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FWIW, I like the comment proposed by Vijay.
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 144 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUv9B9ChMQz6QvXDd:-N7YwL8B3GrTAHyTyFg8:b-8cugob) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L144)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

>Now we have a discrepancy in names for libos_syscall_sched_setaffinity

Yes, I will update the function declaration as well once Michal confirms.
</blockquote></details>

Looks like @Michal is neutral on this so I have updated the header files.
___
*[`libos/src/sys/libos_sched.c` line 220 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qVDuO4fBlFR4c9iiZ:-N7YvvuC8PKgnIoYPCp5:b-w45367) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (discrepancy in the argument name)
</blockquote></details>

I have updated the header.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 174 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dfjXM7ZcmbFNVIemK:-N7ZJzy7AjyhSAR-TeOk:b-e35fqs) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L174)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`cpumask_size` is the size in bytes.

Please note I haven't modified this as part of this PR. I know our preference now is `array + cnt` but IIRC, this was done because the raw set /get affinity syscall requires mask parameter of type `unsigned long`. 

If needed I can create a separate PR to clean up both PAL set/get affinity. Also, it looks like you want to reorder `cpu_mask` and `cpumask_size` which can also be addressed as part of the proposed clean-up PR.
</blockquote></details>

Created a new commit to address this.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 190 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUh9gEwx9_jnhXgZ_:-N7YqMXjEpdF8SR9XK-p:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/pal/src/host/linux-sgx/pal_threading.c#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These four lines have a wrong indentation now. Please shift them to the left by 4 spaces.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-22 08:48 UTC, dimakuv requested changes
> Reviewed 11 of 12 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 18 of 19 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 174 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4RNyCfP5OKm4CQEe:-N7_4RNyCfP5OKm4CQEf:b-qrjvpy) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L174)):*
> ```C
>         return -ENOMEM;
>     }
>     memcpy(cpumask, (uint8_t*)user_mask_ptr, user_mask_size);
> ```

You don't need an explicit cast here.
___
*[`libos/src/sys/libos_sched.c` line 256 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4lta6r8rFbsoNd4a:-N7_4lta6r8rFbsoNd4b:b-165p8w) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L256)):*
> ```C
>     memset(user_mask_ptr, 0, user_mask_size);
>     lock(&thread->lock);
>     memcpy((uint8_t*)user_mask_ptr, thread->cpumask, MIN(user_mask_size, cpumask_size));
> ```

No need for explicit typecast.


<!-- Sent from Reviewable.io -->

2022-07-22 15:32 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 18 of 19 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/src/sys/libos_sched.c` line 174 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4RNyCfP5OKm4CQEe:-N7aXBjr0pqHm5Spijzs:brjflfx) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L174)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need an explicit cast here.
</blockquote></details>

Got it, as it will be cast to `void*` anyway. Will fix this as part of the next commit.
___
*[`libos/src/sys/libos_sched.c` line 256 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4lta6r8rFbsoNd4a:-N7aWySS1WL7REG0O5qO:by0hs5x) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for explicit typecast.
</blockquote></details>

Will fix this as part of the next commit.


<!-- Sent from Reviewable.io -->

2022-07-22 19:24 UTC, mkow requested changes
> Reviewed 11 of 12 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 19 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGNNaDTYcB5BFCxvR):*




_Suggestion:_
```
weird
```
___
*[`-- commits` line 23 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGTrH59mmK4sat9cV):*
double space



_Code quote:_
```
parameters  in
```
___
*[`-- commits` line 24 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGVoq5drbVOVXEeaT):*
Why is this a separate commit? Now we'll have one commit adding thing implemented in some way and another commit, in the same PR, changing the way it's implemented.
___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N7bItXw0rct9vriPxvN:b57mqol) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
> Note that, once the local copy is made, we no longer use `user_mask_ptr`. So `cpumask` in this comment refers to the local copy.

Yes, I know this, but getting to this conclusion required reading this whole functions and analyzing it. All of this just to understand which mask of the two you probably meant by "the cpumask".

Anyways, looks good, but:



_Suggestion:_
```C
                 /* User-supplied cpumask contains a CPU that is currently offline, so remove it
                  * from the local copy (`cpumask`) */
```
___
*[`libos/src/sys/libos_sched.c` line 144 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUv9B9ChMQz6QvXDd:-N7bHUdj1978Bri14NFG:bvf6brg) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L144)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Looks like @Michal is neutral on this so I have updated the header files.
</blockquote></details>

FYI: You just pinged some rando on GitHub ;)

I'm fine with this rename.
___
*[`libos/src/sys/libos_sched.c` line 174 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4RNyCfP5OKm4CQEe:-N7bI5sGBpJccn9Q8y42:b-oq2x99) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L174)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it, as it will be cast to `void*` anyway. Will fix this as part of the next commit.
</blockquote></details>

Is this memcpy correct? What about endianness?
If the kernel is using this array as an array of unsigned longs instead of bytes then this will result in different masks on different architectures. Please check how the mask is actually interpreted by the kernel and user libraries.
___
*[`pal/src/host/linux/pal_threading.c` line 254 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bKgWtEYp80cxbpfCd:-N7bKgWtEYp80cxbpfCe:b-ecb1a7) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/pal/src/host/linux/pal_threading.c#L254)):*
> ```C
> int _PalThreadSetCpuAffinity(PAL_HANDLE thread, uint8_t* cpu_mask, size_t cpumask_size) {
>     int ret = DO_SYSCALL(sched_setaffinity, thread->thread.tid, cpumask_size,
>                          (unsigned long*)((void*)cpu_mask));
> ```

ditto: is this really used as an array of bytes by the kernel? (i.e. what about endianness and, basically, opaqueness of number format when stored as bytes)
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 174 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dfjXM7ZcmbFNVIemK:-N7bL7c68JLgE_P2U2YA:bb1qnjr) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L174)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Created a new commit to address this.
</blockquote></details>

You practically rewrote these functions, so it's definitely in-scope for this PR.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 184 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bLOQg15CUCmbm6D7e:-N7bLOQh43McpVDGRcoe:b-7kuxdq) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/pal/src/host/linux-sgx/pal_threading.c#L184)):*
> ```C
>     /* Verify validity of the CPU affinity (e.g. that it contains no offlined cores). */
>     for (size_t i = 0; i < threads_cnt; i++) {
>         size_t idx = i / BITS_IN_TYPE(uint8_t);
> ```

Here you use `BITS_IN_TYPE(uint8_t)`, but a few lines above `BITS_IN_BYTE`. Please unify.


<!-- Sent from Reviewable.io -->

2022-07-23 23:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`-- commits` line 19 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGNNaDTYcB5BFCxvR):*
Looks like we want to drop this commit and merge into 1. So, blocking myself on the change if we still want to do a separate commit.
___
*[`-- commits` line 23 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGTrH59mmK4sat9cV):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Blocking myself.
___
*[`-- commits` line 24 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGVoq5drbVOVXEeaT):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this a separate commit? Now we'll have one commit adding thing implemented in some way and another commit, in the same PR, changing the way it's implemented.
</blockquote></details>

OK, will drop this commit and merge into 1.
___
*[`libos/src/sys/libos_sched.c` line 144 at r21](https://reviewable.io/reviews/gramineproject/gramine/631#-N6qUv9B9ChMQz6QvXDd:-N7c6dbCEHhDotAkOozc:b9tt97m) ([raw file](https://github.com/gramineproject/gramine/blob/0a6ff2ba1f73c5450ad24d10aca9af17a79c2a47/libos/src/sys/libos_sched.c#L144)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: You just pinged some rando on GitHub ;)

I'm fine with this rename.
</blockquote></details>

yes, realized it after adding my comment :)
___
*[`libos/src/sys/libos_sched.c` line 174 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4RNyCfP5OKm4CQEe:-N7h6oIP-tDZwaaYkcsz:b-f0ppll) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L174)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this memcpy correct? What about endianness?
If the kernel is using this array as an array of unsigned longs instead of bytes then this will result in different masks on different architectures. Please check how the mask is actually interpreted by the kernel and user libraries.
</blockquote></details>

IIUC, the kernel does use it as an array of unsigned longs. So, the current approach will have issues when running on a big-endian system.

How about we introduce APIs like below to explicitly convert from `uint8_t*` to `uint64_t*`? This can help with the endianness issue.

```
static void copy_uint8_ptr_to_uint64_ptr (uint8_t* src, uint64_t* dest, size_t len) {
    int idx = -1; /* To avoid incrementing idx when i = 0 */
    memset(dest, 0, len);
    for (int i = 0; i < len; i++) {
        idx = (i % sizeof(uint64_t)) ? idx : (idx + 1);
        size_t shift = (i % sizeof(uint64_t)) * BITS_IN_BYTE;
        dest[idx] = dest[idx] | ((uint64_t)src[i] << shift);
    }
}
```
```
static void copy_uint64_ptr_to_uint8_ptr (uint64_t* src, uint8_t* dest, size_t len) {
    memset(dest, 0, len);
    int idx = -1; /* To avoid incrementing idx when i = 0 */
    for (int i = 0; i < len; i++) {
        idx = (i % sizeof(uint64_t)) ? idx : (idx + 1);
        size_t shift = (i % sizeof(uint64_t)) * BITS_IN_BYTE;
        dest[i] = (src[idx] >> shift) & 0xff;
    }
}
```

Then replace `memcpy` with `copy_uint64_ptr_to_uint8_ptr(user_mask_ptr, cpumask, user_mask_size);`
___
*[`pal/src/host/linux/pal_threading.c` line 254 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bKgWtEYp80cxbpfCd:-N7h8yKNDmIuXxYm7J_U:b-5qo5hx) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/pal/src/host/linux/pal_threading.c#L254)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto: is this really used as an array of bytes by the kernel? (i.e. what about endianness and, basically, opaqueness of number format when stored as bytes)
</blockquote></details>

No, kernel uses it as an array of `unsigned long`. So, we will have issues with endianness.

Introducing `copy_uint8_ptr_to_uint64_ptr` before the syscall might help.

But do we really want to add such APIs? Can we make an exception for sched set/get affinity calls and simply add a comment in `libos_thread.h` where we declare the `cpumask`? If we keep `cpumask` as an `unsigned long` we can avoid the new commit and adding such APIs.

Currently for set affinity call,
1. In `LibOS`we need convert from uint64_t* to uint8_t*.
2. Copy into the mask into `thread->cpumask`.
3. Then we pass the `uint8_t*` to `PAL` layer which again converts this back to `uint64_t*`.

And then for get affinity call,
1. Convert cpumask that is stored as unit8_t* to uint64_t*
2. Copy it to user buffer upto the requested size. 

Except for validation checks we don't manipulate `cpumask` within Gramine. Agree that `array+cnt` is the right way but feel that in this case it might add more confusion.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 174 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dfjXM7ZcmbFNVIemK:-N7h9PuQ9zpx21BKV3x4:bxz957m) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/pal/src/host/linux-sgx/pal_threading.c#L174)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You practically rewrote these functions, so it's definitely in-scope for this PR.
</blockquote></details>

I was referring to the function signatures for sched set/get affinity in both `LibOS` and `PAL` which weren't using `array + cnt` pattern and the new commit is just trying to fix it. But I am fine merging it into one commit.


<!-- Sent from Reviewable.io -->

2022-07-24 11:19 UTC, boryspoplawski requested changes
> Reviewed 1 of 12 files at r22.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7jvTv91onaHeCSesRW:b-78rzm9) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
> ```objc
> 
>     /* Current CPU affinity mask for this thread. */
>     uint8_t* cpumask;
> ```

Why did you change the type of this array? Now we have all kinds of problems with endianess. This should be the same type everywhere (`unsigned long` is what syscall uses, I believe).


<!-- Sent from Reviewable.io -->

2022-07-25 14:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7pesMe4dyMii6Y6Cyd:b-pp877g) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you change the type of this array? Now we have all kinds of problems with endianess. This should be the same type everywhere (`unsigned long` is what syscall uses, I believe).
</blockquote></details>

`unsigned long` was causing confusion as we will have type* array and size_t array_size. Therefore, I created a second commit and tried to fix this, but it looks like this is causing more complications with the endianness.  So, we have 2 options,

1. Add a comment here that clearly explains why we are not using `array + cnt` and continue using `unsigned long`.
2. Keep using `uint8_t*` which adheres to `array + cnt` but brings in additional complexity.

My preference is to use option 1.


<!-- Sent from Reviewable.io -->

2022-07-25 14:41 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7pnQzXC2qFybo734JV:b-b67mer) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
> unsigned long was causing confusion as we will have type* array and size_t array_size

If you use `count` instead of `size` it should not be confusing?


<!-- Sent from Reviewable.io -->

2022-07-25 15:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7pv3qj0VQzlcoQjezi:b7yvwlm) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> unsigned long was causing confusion as we will have type* array and size_t array_size

If you use `count` instead of `size` it should not be confusing?
</blockquote></details>

Sorry, can you please clarify where to use `count` instead of `size`?
Please note that currently we only store the cpumask in `struct libos_thread` and the size is a global variable.


<!-- Sent from Reviewable.io -->

2022-07-25 15:27 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7py-kG1rEER3QkAMjX:bz48fym) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, can you please clarify where to use `count` instead of `size`?
Please note that currently we only store the cpumask in `struct libos_thread` and the size is a global variable.
</blockquote></details>

I quoted the sentence I was responding to


<!-- Sent from Reviewable.io -->

2022-07-25 18:53 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 19 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGNNaDTYcB5BFCxvR):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Looks like we want to drop this commit and merge into 1. So, blocking myself on the change if we still want to do a separate commit.
</blockquote></details>

Based on the discussion, we don't want this commit.
___
*[`-- commits` line 23 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGTrH59mmK4sat9cV):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Blocking myself.
</blockquote></details>

Not applicable as the commit is removed.
___
*[`-- commits` line 24 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bGVoq5drbVOVXEeaT):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, will drop this commit and merge into 1.
</blockquote></details>

Commit is not applicable, so removed it.
___
*[`libos/include/libos_thread.h` line 136 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7jvTv91onaHeCSesRV:-N7qXS3REBSNDDJgA0b-:b-hrh4xz) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/include/libos_thread.h#L136)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I quoted the sentence I was responding to
</blockquote></details>

Had an offline chat with @boryspoplawski and @mkow. We don't want to change the type of `cpumask`, that is keep this as `unsigned long` but round off the allocation to size of `unsigned long`.
___
*[`libos/src/sys/libos_sched.c` line 184 at r20](https://reviewable.io/reviews/gramineproject/gramine/631#-N6dio5n3_oBrU5SN8dG:-N7qU5ojBWkVe8ZzatfD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3016e00700d128cda22706e7f6cd329cc974745f/libos/src/sys/libos_sched.c#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Note that, once the local copy is made, we no longer use `user_mask_ptr`. So `cpumask` in this comment refers to the local copy.

Yes, I know this, but getting to this conclusion required reading this whole functions and analyzing it. All of this just to understand which mask of the two you probably meant by "the cpumask".

Anyways, looks good, but:
</blockquote></details>

Done.
___
*[`libos/src/sys/libos_sched.c` line 174 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4RNyCfP5OKm4CQEe:-N7qY4mF6W5WXW1KuGnB:b-j9ka8d) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L174)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

IIUC, the kernel does use it as an array of unsigned longs. So, the current approach will have issues when running on a big-endian system.

How about we introduce APIs like below to explicitly convert from `uint8_t*` to `uint64_t*`? This can help with the endianness issue.

```
static void copy_uint8_ptr_to_uint64_ptr (uint8_t* src, uint64_t* dest, size_t len) {
    int idx = -1; /* To avoid incrementing idx when i = 0 */
    memset(dest, 0, len);
    for (int i = 0; i < len; i++) {
        idx = (i % sizeof(uint64_t)) ? idx : (idx + 1);
        size_t shift = (i % sizeof(uint64_t)) * BITS_IN_BYTE;
        dest[idx] = dest[idx] | ((uint64_t)src[i] << shift);
    }
}
```
```
static void copy_uint64_ptr_to_uint8_ptr (uint64_t* src, uint8_t* dest, size_t len) {
    memset(dest, 0, len);
    int idx = -1; /* To avoid incrementing idx when i = 0 */
    for (int i = 0; i < len; i++) {
        idx = (i % sizeof(uint64_t)) ? idx : (idx + 1);
        size_t shift = (i % sizeof(uint64_t)) * BITS_IN_BYTE;
        dest[i] = (src[idx] >> shift) & 0xff;
    }
}
```

Then replace `memcpy` with `copy_uint64_ptr_to_uint8_ptr(user_mask_ptr, cpumask, user_mask_size);`

</blockquote></details>

Reverted the patch, so not applicable.
___
*[`libos/src/sys/libos_sched.c` line 256 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7_4lta6r8rFbsoNd4a:-N7qYP182OCh8xZS7wEV:b-j9ka8d) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/libos/src/sys/libos_sched.c#L256)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Will fix this as part of the next commit.
</blockquote></details>

Reverted the patch, so not applicable.
___
*[`pal/src/host/linux/pal_threading.c` line 254 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bKgWtEYp80cxbpfCd:-N7qYRgf4JZNe5driJwg:b-j9ka8d) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/pal/src/host/linux/pal_threading.c#L254)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, kernel uses it as an array of `unsigned long`. So, we will have issues with endianness.

Introducing `copy_uint8_ptr_to_uint64_ptr` before the syscall might help.

But do we really want to add such APIs? Can we make an exception for sched set/get affinity calls and simply add a comment in `libos_thread.h` where we declare the `cpumask`? If we keep `cpumask` as an `unsigned long` we can avoid the new commit and adding such APIs.

Currently for set affinity call,
1. In `LibOS`we need convert from uint64_t* to uint8_t*.
2. Copy into the mask into `thread->cpumask`.
3. Then we pass the `uint8_t*` to `PAL` layer which again converts this back to `uint64_t*`.

And then for get affinity call,
1. Convert cpumask that is stored as unit8_t* to uint64_t*
2. Copy it to user buffer upto the requested size. 

Except for validation checks we don't manipulate `cpumask` within Gramine. Agree that `array+cnt` is the right way but feel that in this case it might add more confusion.



</blockquote></details>

Reverted the patch, so not applicable.
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 184 at r22](https://reviewable.io/reviews/gramineproject/gramine/631#-N7bLOQg15CUCmbm6D7e:-N7qUKE7CK9M3x2ln5PI:bb6ubk1) ([raw file](https://github.com/gramineproject/gramine/blob/05619a30ec02a0d558b199e35d832f484b1314ff/pal/src/host/linux-sgx/pal_threading.c#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Here you use `BITS_IN_TYPE(uint8_t)`, but a few lines above `BITS_IN_BYTE`. Please unify.
</blockquote></details>

Not applicable, as I have reverted the last commit.


<!-- Sent from Reviewable.io -->

2022-07-26 08:56 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 8 of 19 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[`libos/src/sys/libos_sched.c` line 180 at r23](https://reviewable.io/reviews/gramineproject/gramine/631#-N7th5MX3_jddmi4HaY0:-N7th5MX3_jddmi4HaY1:b-uszn7s) ([raw file](https://github.com/gramineproject/gramine/blob/41f9f3b36d17dd250e3ac83f6a8275ec0e496508/libos/src/sys/libos_sched.c#L180)):*
> ```C
>     size_t threads_cnt = g_pal_public_state->topo_info.threads_cnt;
>     size_t cores_cnt = 0;
>     for (size_t i = 0; i < MIN(threads_cnt, user_mask_size * BITS_IN_BYTE); i++) {
> ```

This is still wrong and won't work on non-little-endian machines.



_Code quote:_
```C
MIN(threads_cnt, user_mask_size * BITS_IN_BYTE)
```
___
*[`libos/src/sys/libos_sched.c` line 201 at r23](https://reviewable.io/reviews/gramineproject/gramine/631#-N7thHN79vpkFmSrwZ9Z:-N7thHN79vpkFmSrwZ9_:brtd2m1) ([raw file](https://github.com/gramineproject/gramine/blob/41f9f3b36d17dd250e3ac83f6a8275ec0e496508/libos/src/sys/libos_sched.c#L201)):*
> ```C
> 
>     lock(&thread->lock);
>     ret = PalThreadSetCpuAffinity(thread->pal_handle, user_mask_size, cpumask);
> ```

And here you're still passing weird sizes (potentially not divisible by `sizeof(ulong)` to PAL.
___
*[`pal/src/host/linux/pal_threading.c` line 252 at r23](https://reviewable.io/reviews/gramineproject/gramine/631#-N7tfmgfC7eWYP-_c3vl:-N7tfmgfC7eWYP-_c3vm:bwo2nli) ([raw file](https://github.com/gramineproject/gramine/blob/41f9f3b36d17dd250e3ac83f6a8275ec0e496508/pal/src/host/linux/pal_threading.c#L252)):*
> ```C
> }
> 
> int _PalThreadSetCpuAffinity(PAL_HANDLE thread, size_t cpumask_size, unsigned long* cpu_mask) {
> ```

Now you *again* reintroduced this problem with array+arr_bytesize instead of array+arr_count...



_Code quote:_
```C
size_t cpumask_size, unsigned long* cpu_mask
```
___
*[`pal/src/host/linux-sgx/pal_threading.c` line 169 at r23](https://reviewable.io/reviews/gramineproject/gramine/631#-N7tg5PzBcuLPT6xfuWa:-N7tg5PzBcuLPT6xfuWb:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/41f9f3b36d17dd250e3ac83f6a8275ec0e496508/pal/src/host/linux-sgx/pal_threading.c#L169)):*
> ```C
> }
> 
> int _PalThreadSetCpuAffinity(PAL_HANDLE thread, size_t cpumask_size, unsigned long* cpu_mask) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-07-26 09:19 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 8 of 19 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N7tmYi-4F8f-3GYI33C:-N7tmYi-4F8f-3GYI33D:b-9f7gvs) (no related file):*
Looking at the latest comments from @mkow, it looks like this PR is not converging to anything yet (after 23 revisions).

I think we should change the strategy here. My understanding is that Vijay got a bit stuck with choosing the correct types and sizes to pass, and there is significant misunderstanding of what the reviewers (Michal and Borys) want.

I propose for @boryspoplawski or @mkow to take over this PR and drive it to conclusion. @vijaydhanraj can swap the role and become a reviewer for their changes.

@boryspoplawski @mkow @vijaydhanraj Does this plan sound good to you? Let's finish this PR soon, and move on to other tasks. Please ack.

___


<!-- Sent from Reviewable.io -->

2022-07-26 09:27 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 8 of 19 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N7tmYi-4F8f-3GYI33C:-N7tpK7eE_9drwoRj6se:b-9gv58c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looking at the latest comments from @mkow, it looks like this PR is not converging to anything yet (after 23 revisions).

I think we should change the strategy here. My understanding is that Vijay got a bit stuck with choosing the correct types and sizes to pass, and there is significant misunderstanding of what the reviewers (Michal and Borys) want.

I propose for @boryspoplawski or @mkow to take over this PR and drive it to conclusion. @vijaydhanraj can swap the role and become a reviewer for their changes.

@boryspoplawski @mkow @vijaydhanraj Does this plan sound good to you? Let's finish this PR soon, and move on to other tasks. Please ack.
</blockquote></details>

+1 from my side.

___


<!-- Sent from Reviewable.io -->

2022-07-26 13:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/631)* status: 16 of 19 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/631#-N7tmYi-4F8f-3GYI33C:-N7ulrEG2UvyXNR_G85O:b-z1fbzu) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I could take it over, ack from me
</blockquote></details>

Yes please, ack from my side.

___


<!-- Sent from Reviewable.io -->

2022-07-29 17:04 UTC, closed without merging