[LTP] Run timeout-prone tests with unbufferred output
gramineproject/gramine pull request #632
Opened 2022-06-03 22:11 UTC by NieDzejkob

## Description of the changes 

To diagnose the LTP tests that sometimes time out, modify the test script such that CI timestamps each subtest getting executed. This will tell us if it's a hang, or if the machine is just slightly too slow for the current timeout values.
 
## How to test this PR? 

CI should suffice.

2022-06-04 16:01 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @NieDzejkob)

___
*[`LibOS/shim/test/ltp/test_ltp.py` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jRfEZ3nOVpw7ORWtw:-N3jRfE_7uh4tF6rWWz-:b-tbavlt) ([raw file](https://github.com/gramineproject/gramine/blob/5f09fb0fdfc4e5053e3a0d247b5c6db5e79a6995/LibOS/shim/test/ltp/test_ltp.py#L196)):*
> ```Python
>     logging.info('must_pass: %s', list(must_pass) if must_pass else 'all')
> 
>     if section.name in ['fcntl14', 'fdatasync01']:
> ```

Do we want to merge it, or rather just run a few times in CI until we hit the bug?


<!-- Sent from Reviewable.io -->

2022-06-04 16:01 UTC, mkow commented
Jenkins, test this please

2022-06-04 16:54 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jbO9C2vF4Z7SLDh0p:-N3jbO9C2vF4Z7SLDh0q:b-5he1f5) (no related file):*
Prompted by `pytest`, I have refactored the code somewhat. It still triggers the warning, but the code duplication is reduced somewhat. Not sure whether it is an improvement.

___
___
*[`LibOS/shim/test/ltp/test_ltp.py` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jRfEZ3nOVpw7ORWtw:-N3jcH4Z6PNCDp-D2yLp:b-pljm9u) ([raw file](https://github.com/gramineproject/gramine/blob/5f09fb0fdfc4e5053e3a0d247b5c6db5e79a6995/LibOS/shim/test/ltp/test_ltp.py#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we want to merge it, or rather just run a few times in CI until we hit the bug?
</blockquote></details>

If the bug turns out to be hard to trigger, I think merging it would be a better use of our resources. However, if we take a look at which machines were used when it triggered before, I'd wager we can trigger it again pretty soon — and even if not, we'll see how long each subtest takes. I'm kinda hoping that it's just barely below the timeout on the good days.


<!-- Sent from Reviewable.io -->

2022-06-04 16:55 UTC, mkow commented
Jenkins, retest this please

2022-06-04 18:33 UTC, mkow commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-04 20:21 UTC, mkow commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-04 21:48 UTC, mkow commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-04 22:53 UTC, mkow commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 03:23 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 04:17 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 05:29 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 07:20 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 08:50 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 10:07 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 11:45 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 14:22 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 15:13 UTC, boryspoplawski commented
Jenkins, retest this please (trying to hit the CI lag bug)

2022-06-05 19:15 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/test/ltp/test_ltp.py` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jRfEZ3nOVpw7ORWtw:-N3pHRpJ6tQUwrI4ZxBa:bpmy1bk) ([raw file](https://github.com/gramineproject/gramine/blob/5f09fb0fdfc4e5053e3a0d247b5c6db5e79a6995/LibOS/shim/test/ltp/test_ltp.py#L196)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

If the bug turns out to be hard to trigger, I think merging it would be a better use of our resources. However, if we take a look at which machines were used when it triggered before, I'd wager we can trigger it again pretty soon — and even if not, we'll see how long each subtest takes. I'm kinda hoping that it's just barely below the timeout on the good days.
</blockquote></details>

Perhaps this would be easier to merge if we specified the list of testcases as an environment variable that would be set in the CI config?


<!-- Sent from Reviewable.io -->

2022-06-05 23:21 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`LibOS/shim/test/ltp/test_ltp.py` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jRfEZ3nOVpw7ORWtw:-N3qA0Sl0frlz5PkYYDT:b-ok9aso) ([raw file](https://github.com/gramineproject/gramine/blob/5f09fb0fdfc4e5053e3a0d247b5c6db5e79a6995/LibOS/shim/test/ltp/test_ltp.py#L196)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Perhaps this would be easier to merge if we specified the list of testcases as an environment variable that would be set in the CI config?
</blockquote></details>

I like this idea! Sounds less hacky and also quite useful for the future :)


<!-- Sent from Reviewable.io -->

2022-06-06 14:30 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`LibOS/shim/test/ltp/test_ltp.py` line 196 at r1](https://reviewable.io/reviews/gramineproject/gramine/632#-N3jRfEZ3nOVpw7ORWtw:-N3tPweDBIRc3CFsAFsQ:b-dde3o) ([raw file](https://github.com/gramineproject/gramine/blob/5f09fb0fdfc4e5053e3a0d247b5c6db5e79a6995/LibOS/shim/test/ltp/test_ltp.py#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like this idea! Sounds less hacky and also quite useful for the future :)
</blockquote></details>

Okay, I've moved the actual list of problematic tests to the CI config.


<!-- Sent from Reviewable.io -->

2022-06-06 14:35 UTC, boryspoplawski commented
Jenkins, test this please

2022-06-06 21:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-07 06:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-07 13:19 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/632#-N3yEAUH4cNRMqJDaxTJ):*
This fixup is for a wrong commit
___
*[`-- commits` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/632#-N3yEFX_1qDLDxLqLnVD):*
ditto


<!-- Sent from Reviewable.io -->

2022-06-07 19:15 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/632#-N3yEAUH4cNRMqJDaxTJ):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This fixup is for a wrong commit
</blockquote></details>

Ah, my bad. Looks like my git workflow is not ideal. To fix during rebase&merge.
___
*[`-- commits` line 16 at r4](https://reviewable.io/reviews/gramineproject/gramine/632#-N3yEFX_1qDLDxLqLnVD):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2022-06-08 06:02 UTC, dimakuv commented
@NieDzejkob Can you squash and rebase this PR? It is the next one in the merge queue.

2022-06-08 11:57 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-06-08 11:57 UTC, boryspoplawski commented
Jenkins, test this please

2022-06-08 12:07 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-06-08 12:54 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/632)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-08 12:55 UTC, merged