[Docs] Describe new `SECRET_PROVISION_SET_KEY` envvar in attestation
gramineproject/gramine pull request #643
Opened 2022-06-09 09:45 UTC by dimakuv

## Description of the changes 

Commit "[Pal/Linux-SGX] Adapt for the new encrypted files API" deprecated the `SECRET_PROVISION_SET_PF_KEY` envvar and introduced the new `SECRET_PROVISION_SET_KEY` envvar instead. However, that commit forgot to update the Attestation documentation page.

The mentioned commit:
- https://github.com/gramineproject/gramine/commit/fbfd07c522a0b190c0a97158ea406e35c82fa0e0
- https://github.com/gramineproject/gramine/pull/587

## How to test this PR? 

N/A.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/643)

2022-06-09 09:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/643#-N46r0Nk5oC7bfJyQbmh:-N46r0Nk5oC7bfJyQbmi:byplyju) (no related file):*
@niedzejkob You wrote the PR #587. Could you review my PR, as you're the most familiar with it?

___


<!-- Sent from Reviewable.io -->

2022-06-09 10:54 UTC, NieDzejkob reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 451 at r1](https://reviewable.io/reviews/gramineproject/gramine/643#-N473V1t9eESFlzUh1-s:-N473V1u-RKW-bmO8N9a:b-5xybh0) ([raw file](https://github.com/gramineproject/gramine/blob/8e81e6313fd5688b9961797fe5e02da3c540e14c/Documentation/attestation.rst#L451)):*
> ```reStructuredText
> .. note::
>    Previously, ``SECRET_PROVISION_SET_PF_KEY = 1/true/TRUE`` was used for
>    setting the default encryption key, and Gramine still supports that
> ```

Perhaps
```
setting the ``default`` encryption key,
```
to put more emphasis on the new name of the key?


<!-- Sent from Reviewable.io -->

2022-06-09 11:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`Documentation/attestation.rst` line 451 at r1](https://reviewable.io/reviews/gramineproject/gramine/643#-N473V1t9eESFlzUh1-s:-N47CZtQAxw41iWDp-wU:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e81e6313fd5688b9961797fe5e02da3c540e14c/Documentation/attestation.rst#L451)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Perhaps
```
setting the ``default`` encryption key,
```
to put more emphasis on the new name of the key?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 11:27 UTC, NieDzejkob reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-09 11:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/643#-N47DK4YE_jGzIfWzk1U:-N47DK4Z0VK30d9_pCgm:be8issb) (no related file):*
@niedzejkob Since you can't explicitly approve PRs (I hope "yet"), could you use the "LGTM" button to show your approval? Otherwise Reviewable and GitHub simply show that you "looked at a PR".

___


<!-- Sent from Reviewable.io -->

2022-06-09 12:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/643#-N47O7rg-ZlMNyNQ3BQ3:-N47O7rg-ZlMNyNQ3BQ4:b457xks) (no related file):*
FYI: We have this deprecated `SECRET_PROVISION_SET_PF_KEY` also in `Documentation/tutorials/pytorch/index.rst`, but it's already being worked on in https://github.com/gramineproject/gramine/pull/635.

___
___
*[`Documentation/attestation.rst` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47PkYb0Vd1YRnlKD6V:-N47PkYb0Vd1YRnlKD6W:b-9azqwg) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L442)):*
> ```reStructuredText
>   will be provisioned into the Gramine enclave as the secret. For example,
>   setting this environment variable to ``default`` will install the provisioned
>   key as the default encryption key for encrypted files. The key must be a
> ```

I know it was already there, but this is IMO confusing: it sounds like the user has to provide that key in the specified format, while what we really mean is that RA-TLS passes the key to the user app in this format.



_Code quote:_
```reStructuredText
The key must be
```
___
*[`Documentation/attestation.rst` line 452 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47Q77F22VfB2QNPJ8K:-N47Q77F22VfB2QNPJ8L:b-rcu0f9) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L452)):*
> ```reStructuredText
>    Previously, ``SECRET_PROVISION_SET_PF_KEY = 1/true/TRUE`` was used for
>    setting the ``default`` encryption key, and Gramine still supports that
>    environment variable for backward compatibility.
> ```

Please add that this is only temporary and it's deprecated, aka we'll remove it soon. Now it sounds like we plan to support it for quite some time.


<!-- Sent from Reviewable.io -->

2022-06-09 21:58 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-12 21:29 UTC, NieDzejkob reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47PkYb0Vd1YRnlKD6V:-N4Om-L60WUjdNhfVtw7:bb505pp) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L442)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I simply removed this sentence, because this detail doesn't matter here, in this description.
</blockquote></details>

No, this specifies that the key sent through RA-TLS should be in hex, and that Gramine will pass it through `parse_hex` before putting it into `/dev/attestation/keys/<key_name>`. The fact that it is sent this way is the responsibility of the user — in the `ra-tls-secret-prov` example, encoding the key into hex is done in the example `src/server.c`.

The RA-TLS API itself supports sending raw bytes, and without this sentence, it is reasonable to assume that one should send the key unencoded.

The secret provisioning library only processes the secret in any way when this env var is set, so I don't see where else to document this.


<!-- Sent from Reviewable.io -->

2022-06-13 07:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @NieDzejkob)

___
*[`Documentation/attestation.rst` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47PkYb0Vd1YRnlKD6V:-N4QvrAz-eyN6SAsT7zL:b88vuow) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L442)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

No, this specifies that the key sent through RA-TLS should be in hex, and that Gramine will pass it through `parse_hex` before putting it into `/dev/attestation/keys/<key_name>`. The fact that it is sent this way is the responsibility of the user — in the `ra-tls-secret-prov` example, encoding the key into hex is done in the example `src/server.c`.

The RA-TLS API itself supports sending raw bytes, and without this sentence, it is reasonable to assume that one should send the key unencoded.

The secret provisioning library only processes the secret in any way when this env var is set, so I don't see where else to document this.
</blockquote></details>

Ok, I restored the sentence and changed `The key must be a 32-char...` to `The key will be sent (by the secret provisioning service) as a 32-char...`.


<!-- Sent from Reviewable.io -->

2022-06-14 18:02 UTC, NieDzejkob reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/attestation.rst` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47PkYb0Vd1YRnlKD6V:-N4d0eBr6vjOhGunCyDO:b-dav5t1) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L442)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I restored the sentence and changed `The key must be a 32-char...` to `The key will be sent (by the secret provisioning service) as a 32-char...`.
</blockquote></details>

Still, we're placing a requirement on the user here, so I think `The key (must|should|shall) be sent` would be more appropriate.


<!-- Sent from Reviewable.io -->

2022-06-15 09:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

___
*[`Documentation/attestation.rst` line 442 at r2](https://reviewable.io/reviews/gramineproject/gramine/643#-N47PkYb0Vd1YRnlKD6V:-N4aiagK9Acs1xfYWiDX:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2884921bbdabcff55126cfd321f6072f0a185e1f/Documentation/attestation.rst#L442)):*
<details><summary><i>Previously, NieDzejkob (Jakub Kądziołka) wrote…</i></summary><blockquote>

Still, we're placing a requirement on the user here, so I think `The key (must|should|shall) be sent` would be more appropriate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 12:57 UTC, NieDzejkob reviewed
New revision <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643#-:-N4bR0RhBPrWEMHG7pC9:b-31dq38)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-19 10:04 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-19 10:10 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/643)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-20 07:02 UTC, merged