[LibOS,PAL] Clean up hex parsing
gramineproject/gramine pull request #644
Opened 2022-06-09 13:03 UTC by dimakuv

## Description of the changes 

This commit removes macros `BYTES2HEXSTR` and `ALLOCA_BYTES2HEXSTR`, as well as introduces the `hex2bytes()` function instead of ad-hoc code snippets in LibOS and PAL codebase.

I promised this during the review of https://github.com/gramineproject/gramine/pull/638.

## How to test this PR? 

N/A.

2022-06-09 17:42 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`common/include/hex.h` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48UD508Va9vsyX43BE:-N48UD508Va9vsyX43BF:bjahphx) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L15)):*
> ```objc
> #include "api.h"
> 
> static inline char* bytes2hex(const void* bytes, size_t bytes_size, char* hex, size_t hex_size) {
> ```

Why does it return `char*` instead of error code or `bool`?
___
*[`common/include/hex.h` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48UOec3aC_hAPvIHqy:-N48UOec3aC_hAPvIHqz:b-ck2yhn) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L19)):*
> ```objc
>         return NULL;
> 
>     static const char* ch = "0123456789abcdef";
> ```

Maybe some better name? `alphabet`? I personally use `alph` in such places, but idk if it's good abbrev.
___
*[`common/include/hex.h` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VGwP9M391vYqjC9M:-N48VGwP9M391vYqjC9N:brsffqd) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L31)):*
> ```objc
> 
> static inline int8_t hex2dec(char hex) {
>     if (hex >= 'A' && hex <= 'F')
> ```

Could you change all these if's to have comparisons "ascending", like `'A' <= hex && hex <= 'F'`
___
*[`common/include/hex.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VUiCC_isXbaNdnRG:-N48VUiCC_isXbaNdnRH:b-4nknjn) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L33)):*
> ```objc
>     if (hex >= 'A' && hex <= 'F')
>         return hex - 'A' + 10;
>     else if (hex >= 'a' && hex <= 'f')
> ```

`{ }` missing everywhere here
___
*[`common/include/hex.h` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48WaSp7FUCBg7-kNtX:-N48WaSp7FUCBg7-kNtY:bhtieqv) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L41)):*
> ```objc
> }
> 
> static inline void* hex2bytes(const char* hex, size_t hex_size, void* bytes, size_t bytes_size) {
> ```

ditto (return type -  `char*`)
___
*[`common/include/hex.h` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48YCqQ6g32T08Y4U6e:-N48YCqQ6g32T08Y4U6f:b-qj5zh9) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L41)):*
> ```objc
> }
> 
> static inline void* hex2bytes(const char* hex, size_t hex_size, void* bytes, size_t bytes_size) {
> ```

Hmm, we do not require `hex` to be null terminated, so I guess it's easier to just pass the length here?
___
*[`common/include/hex.h` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VkQcAtG_gchodNwU:-N48VkQcAtG_gchodNwV:b6l57no) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L42)):*
> ```objc
> 
> static inline void* hex2bytes(const char* hex, size_t hex_size, void* bytes, size_t bytes_size) {
>     if (hex_size < bytes_size * 2 + 1)
> ```

wait, this is wrong
1. It should check if `hex_size % 2 == 0`
2. `if (bytes_size < hex_size / 2) fail`


<!-- Sent from Reviewable.io -->

2022-06-10 07:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: 4 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`common/include/hex.h` line 15 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48UD508Va9vsyX43BE:-N4BWfFa-LbtlsEXufjS:b-l6z0gh) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why does it return `char*` instead of error code or `bool`?
</blockquote></details>

Do we really want this? With the current scheme, we can do this:
```
pal_printf("Hex test 1 is %s\n", bytes2hex(x, sizeof(x), hex_buf, sizeof(hex_buf)));
```

If you don't like that we may return NULL, I can replace the below IF with an assert. Because all callers anyway check that the sizes are "good", and this IF check is redundant here. And so we can just have this condition as a contract of this function.
___
*[`common/include/hex.h` line 19 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48UOec3aC_hAPvIHqy:-N4BXN8cD2q_g93QGqwI:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe some better name? `alphabet`? I personally use `alph` in such places, but idk if it's good abbrev.
</blockquote></details>

Done.
___
*[`common/include/hex.h` line 31 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VGwP9M391vYqjC9M:-N4BXW_V6m8MSyNCzJKW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you change all these if's to have comparisons "ascending", like `'A' <= hex && hex <= 'F'`
</blockquote></details>

Done.
___
*[`common/include/hex.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VUiCC_isXbaNdnRG:-N4BXma_EQMPV7pA8GTz:b8p8x12) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`{ }` missing everywhere here
</blockquote></details>

Done. Never understood your love for `{ }`. Is there a particular reason why you want to have it here? All these if-bodies are one-liners.
___
*[`common/include/hex.h` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48WaSp7FUCBg7-kNtX:-N4BXuyv1YuXsc8Xq-tI:botk4uq) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (return type -  `char*`)
</blockquote></details>

ditto (let's resolve the discussion in that other thread first)
___
*[`common/include/hex.h` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48YCqQ6g32T08Y4U6e:-N4BYdUTC8kSvsJbVR0b:b-2gnoqe) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, we do not require `hex` to be null terminated, so I guess it's easier to just pass the length here?
</blockquote></details>

Done. I wanted to do that first but then we are loosing uniformity with `bytes2hex()`. On the other hand, these are pretty different functions anyway, so I agree.
___
*[`common/include/hex.h` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VkQcAtG_gchodNwU:-N4BYocW34VwgJNiPj1h:b-dshhl9) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

wait, this is wrong
1. It should check if `hex_size % 2 == 0`
2. `if (bytes_size < hex_size / 2) fail`
</blockquote></details>

Done. You are right, your proposal is better.


<!-- Sent from Reviewable.io -->

2022-06-13 06:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`common/include/hex.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VUiCC_isXbaNdnRG:-N4QqBCT24xt745yRgKt:bjiymda) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Is there a particular reason why you want to have it here? 

It's more readable (to me at least?) and our coding guidelines (actually google cpp ones, to which we defer) requires it
</blockquote></details>

OK, I'll try to use it everywhere now, maybe excluding error handling two-liners:
```
if (ret < 0)
    return ret;
```

(I don't remember anyone using `{ }` in this case.)
___
*[`common/include/hex.h` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VkQcAtG_gchodNwU:-N4QqRJA-FYYi3_9wmFr:bjad38f) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I mean, the old one had comparison in wrong direction :)
</blockquote></details>

Yes. I meant your check on the even-ness of the length of the hex string.


<!-- Sent from Reviewable.io -->

2022-06-13 16:41 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[`common/include/hex.h` line 33 at r1](https://reviewable.io/reviews/gramineproject/gramine/644#-N48VUiCC_isXbaNdnRG:-N4Suv410pG44pqU9cH-:b679km9) ([raw file](https://github.com/gramineproject/gramine/blob/a3ac5640547c57e3229011ca167b6307a19971cc/common/include/hex.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I'll try to use it everywhere now, maybe excluding error handling two-liners:
```
if (ret < 0)
    return ret;
```

(I don't remember anyone using `{ }` in this case.)
</blockquote></details>

Yeah, it explicitly allows omitting them on oneliners, which do not have `else` clause. I personally write them even in such cases, but never point this in reviews.


<!-- Sent from Reviewable.io -->

2022-06-15 13:22 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-15 13:55 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/644)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-15 16:00 UTC, merged