[LibOS,Pal] Add flexible device-specific IOCTL support
gramineproject/gramine pull request #671
Opened 2022-06-21 17:27 UTC by dimakuv

## Description of the changes 

TODO: explain.

TODO: test with dummy device; add CI pipeline; add many tests.

TODO: this commit doesn't have `onlyif`.

TODO: this commit doesn't have caching of sub-regions.

TODO: this commit doesn't have caching of IOCTL TOML definitions.

TODO: if reviewers think this is still too much functionality for the first commit, I can strip off (a) string hashes, (b) pointer-arrays with size > 1.

## How to test this PR? 

TODO: add tests and 22.04 bare-metal CI pipeline.

2022-07-25 12:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 0 of 20 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-N7pM5DNA3-I3oO_VbON:-N7pM5DO5mO4PZbGKy3o:b-5y73is) (no related file):*
FYI: Rebased this PR to the latest master (to accommodate dir/file renames).

___


<!-- Sent from Reviewable.io -->

2022-10-13 11:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NEG7wsR8eWMGta1p4Og:-NEG7wsVCwLSbQbvCmFc:b-b35ahx) (no related file):*
@woju We are ready to start reviewing this PR. For this, we need to enable at least one CI machine with bare-metal Ubuntu 22.04 as the host OS (**no VMs**). Can we work on this?

___


<!-- Sent from Reviewable.io -->

2022-10-24 10:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 2 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NF8Okp8-L2J9deeqoM6:-NF8Okp9CxZcgvCMm3lY:b-wdmmcu) (no related file):*
This PR depends on https://github.com/gramineproject/gramine/pull/995. Otherwise Jenkins fails (see the explanation here: https://github.com/gramineproject/gramine/issues/990)

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEllQ-YBSlrgincyjMq):*
Will do during the final rebase.
___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would explain more precisely what you mean by "insecure". I would also mention that untrusted host can change arguments as it wishes, no matter how you use this feature.
</blockquote></details>

What about this text:
```
  The newly added `ioctl()` syscall emulation on device-backed file
  descriptors is pass-through. It is insecure by itself since the
  emulation only passes the arguments to and from the untrusted memory:
    - ioctl arguments are passed as-is from the app to the untrusted host,
      without encryption; this may lead to leaks of secret data;
    - untrusted host can change ioctl arguments as it wishes when passing
      them from Gramine to the device and back.

  It is the responsibility of the app developer to correctly use ioctls,
  with security implications in mind. In particular, ioctl arguments should
  be encrypted or integrity-protected with a key pre-shared between
  Gramine and the device.
```


<!-- Sent from Reviewable.io -->

2022-10-24 12:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 0 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NEG7wsR8eWMGta1p4Og:-NF93KdT4jY2hUC1Cb8M:bew85oa) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju We are ready to start reviewing this PR. For this, we need to enable at least one CI machine with bare-metal Ubuntu 22.04 as the host OS (**no VMs**). Can we work on this?
</blockquote></details>

@woju Ping.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NElgHo5-tfWn9qJDYOk:-NF8vjq1635aHtwHfwGl:b-9xkzlg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You use `ioctl()`,`IOCTL` and `ioctl`, would be good to unify.
</blockquote></details>

Done. I only found the occurences in `log_error()` cases -- there I replaced `ioctl` to `IOCTL`.

In all other instances, I seem to correctly use `IOCTL` as the name of the feature. And sometimes I use `ioctl()` when I want to highlight the system call itself (not just the feature of IOCTLs).

___
___
*[`Documentation/manifest-syntax.rst` line 773 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElib5z9uNlDlxoJEHZ:-NF8drtY0MT46iuvLBXt:bni7wes) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L773)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `request code`? Not sure which one descries it better.
</blockquote></details>

I just followed `man ioctl`, which calls the arg as `request`. So to me, `request` is sensible.
___
*[`Documentation/manifest-syntax.rst` line 778 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElBA2JD36T_o61sD3G:-NF8edbR4Oz9bVCE2zGQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L778)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is `arg` argument? 3rd argument to `ioctl` syscall? Please be more precise here
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 781 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElj6Ne9xx0F1PV9HA6:-NF8glaK7gCd28OHIc-X:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L781)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is a "memory (sub-)region"?
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NF8mvxwEb2n-72D6Ioq:bbju6e3) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ugh, can't we use size uniformly, i.e. in case of arrays just hole the size of the array, not length?
</blockquote></details>

This is very hard to calculate and very hard to reason about. Also, if you've seen some IOCTL usages, it is almost always the case that arrays are specified as "length of the array" and never as "total size of the array". I can show some DRM (Direct Rendering Manager) examples to you, if you want to see some examples.

In other words, I'm mimicking how applications typically use IOCTL structs.

But I agree that I'm overloading this key `size`. If you want to, I can introduce another key `count` which will only be meaningful for `ptr`. But then it will get a bit complicated:
- `ptr` may be used with `count` (by default `count=1`)
- `count` without a `ptr` must be a syntax error
- `size` with a `ptr` must be a syntax error

Would this proposal be better than overloading `size` for pointers and non-pointers?

Maybe I should even give a name to this key like `array_count`.
___
*[`Documentation/manifest-syntax.rst` line 806 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElkg5R6Ta7mgnmmYO1:-NF8hOT1DhnyS2lI0HLc:bwgnhc0) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L806)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is this field always in bytes or is it also affected by `unit`?
</blockquote></details>

Done. It is always in bytes.

But if it's complicated for understanding, I can make it be affected by `unit`.
___
*[`Documentation/manifest-syntax.rst` line 819 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEllq4r4JrJo0qPixcu:-NF8i36B9EbExcA8_fQY:b-w0z910) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L819)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why special case it? Isn't in this context a pointer the same as pointer to an array of length == 1 (which is the default)?
</blockquote></details>

Yes, that's what I do internally in the code.

I just thought that for normal users, it is hard to understand the concept of `pointer == array[1]`. Even C docs are fuzzy about this (or well, what people write on the internet about C arrays vs pointers). So the current text seemed more approripate to me than some strict statement like "`ptr` points to an array of memory regions, with a length of 1 by default".

I added an explainer, does this help?
___
*[`Documentation/manifest-syntax.rst` line 824 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElnSI0A66txPn_OBhW:-NF8k_W38yWKASfouczh:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L824)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add some C code with some struct(s) definitions here, that would match the example below.
I assume it's something like:
```
struct st1 {
    struct st2* ptr;
};

struct st2 {
    char buf[0x1000];
} aligned(0x1000);
```

</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElm8nh2VYd_kMEqVKX:-NF8kZku5FPGBd1ZoINN:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you split this into multiple lines? I think it would be easier to read, e.g.:
```
sgx.ioctl_structs.st1 = [
    {
        ptr = [
            {
                name="nested_region",
                align=4096,
                size=4096,
                type="out"
            },
        ]
    },
]
```
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NF8mQTFDgwG6oFiCf5v:b-tqzc3e) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why ptr is an TOML array of length == 1, not the dict directly? From the description above I underst [...]

2022-10-24 21:30 UTC, boryspoplawski requested changes
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 2 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this text:
```
  The newly added `ioctl()` syscall emulation on device-backed file
  descriptors is pass-through. It is insecure by itself since the
  emulation only passes the arguments to and from the untrusted memory:
    - ioctl arguments are passed as-is from the app to the untrusted host,
      without encryption; this may lead to leaks of secret data;
    - untrusted host can change ioctl arguments as it wishes when passing
      them from Gramine to the device and back.

  It is the responsibility of the app developer to correctly use ioctls,
  with security implications in mind. In particular, ioctl arguments should
  be encrypted or integrity-protected with a key pre-shared between
  Gramine and the device.
```
</blockquote></details>

LGTM
The last para doesn't seem to be needed imo (it's commit message not docs and previous para already describes what are the risks), but it also can stay
___
*[`Documentation/manifest-syntax.rst` line 773 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElib5z9uNlDlxoJEHZ:-NF9pAZX7FHXEGAWCa-N:b-t8wfvr) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L773)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just followed `man ioctl`, which calls the arg as `request`. So to me, `request` is sensible.
</blockquote></details>

And kernel uses `cmd` as argument name and `command number`, `request number`, `code` and many others to refer to it.
To me `request` sounds like the whole operation i.e. code + argument issued on a specific device.
___
*[`Documentation/manifest-syntax.rst` line 778 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElBA2JD36T_o61sD3G:-NF9qC_e97CSzJELx6O0:b-k5jvc7) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L778)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would remove `argp` name, it lacks the context here (you seem to be following man, but it has the function signature, so it makes sense to use such names there; here it does not). IMO just `Each IOCTL struct describes the memory layout of the third argument to the ``ioctl`` system call (typically...`
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NF9rQMz5Vqz8NDkataW:b-6qky2m) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is very hard to calculate and very hard to reason about. Also, if you've seen some IOCTL usages, it is almost always the case that arrays are specified as "length of the array" and never as "total size of the array". I can show some DRM (Direct Rendering Manager) examples to you, if you want to see some examples.

In other words, I'm mimicking how applications typically use IOCTL structs.

But I agree that I'm overloading this key `size`. If you want to, I can introduce another key `count` which will only be meaningful for `ptr`. But then it will get a bit complicated:
- `ptr` may be used with `count` (by default `count=1`)
- `count` without a `ptr` must be a syntax error
- `size` with a `ptr` must be a syntax error

Would this proposal be better than overloading `size` for pointers and non-pointers?

Maybe I should even give a name to this key like `array_count`.
</blockquote></details>

IMO there's no good option here and we have to live with some inconsistencies. To me the only sensible options are:
- `size` - has the problem of being non-intuitive for arrays,
- `length` - technically with unit=1B, `length` is correct description of `size`, but it's counter intuitive to provide size of objects in `length` field
___
*[`Documentation/manifest-syntax.rst` line 819 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEllq4r4JrJo0qPixcu:-NF9ysi3BnwxnXm5CmFR:br445kj) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L819)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, that's what I do internally in the code.

I just thought that for normal users, it is hard to understand the concept of `pointer == array[1]`. Even C docs are fuzzy about this (or well, what people write on the internet about C arrays vs pointers). So the current text seemed more approripate to me than some strict statement like "`ptr` points to an array of memory regions, with a length of 1 by default".

I added an explainer, does this help?
</blockquote></details>

The differences in C are between `char*` and `char[]`. Here you always have `char*` and just manipulate the length. I guess only `not just a pointer` is confusing to me, but with additional explanation it's at least clear after reading the whole paragraph, so I'm unblocking.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFAeCPE8l9O3F3ET5eD:b64744v) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, your understanding is not correct. I updated the example to make it more pronounced.

The `ptr` points to a memory region, and this memory region may contain not one but several sub-regions. So we must first specify that we point to a memory region (via TOML array syntax `[ ]`), then we must specify each sub-region one by one (via TOML dict syntax `{ }`).
</blockquote></details>

Ok I got it. I understood it correctly that `ptr` is just one "thing", what I've missed is that a "memory region" is described as a TOML array (`[ ]`).

So a quick summary:
- each struct is described by an array of items,
- each item is described by a dict and corresponds to a element n C struct declaration list,
- each item/dict has keys as described above (`size`, `name`, ...),
- if an item is actually a pointer and memory that it points to needs to be copied, `ptr = ` key is used; this key has either name of another struct or the struct definition inlined.

Is that correct?
So what you call "memory region" corresponds to a whole struct description and "sub-region" to what I've called an "item" above? Or actually "sub-region" could theoretically be multiple "items" as long as they are consecutive and have matching in-out params

Actually, wouldn't it be easier to just call everything an object? I.e. use `object` or just `struct`/`structure` in place of all `memory region`s and  actually not use `memory sub-region` at all? What would be downsides of this?
___
*[`Documentation/manifest-syntax.rst` line 817 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFAbc1p9xpCs5yhXVX7:-NFAbc1p9xpCs5yhXVX8:b-yatb35) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L817)):*
> ```reStruc [...]

2022-10-25 12:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 0 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

LGTM
The last para doesn't seem to be needed imo (it's commit message not docs and previous para already describes what are the risks), but it also can stay
</blockquote></details>

Ok, I will remove the last paragraph. Moved to documentation (aparently I forgot to add notes about security in the docs).
___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFD_ppO7HJ2ikIKb9-e):*
I'll need to change to `request_code`
___
*[`Documentation/manifest-syntax.rst` line 773 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElib5z9uNlDlxoJEHZ:-NFD_W_G3BXc7AMv8MYZ:b-5ba8bu) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L773)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And kernel uses `cmd` as argument name and `command number`, `request number`, `code` and many others to refer to it.
To me `request` sounds like the whole operation i.e. code + argument issued on a specific device.
</blockquote></details>

Done, switched to `request_code`
___
*[`Documentation/manifest-syntax.rst` line 778 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElBA2JD36T_o61sD3G:-NFDoKr7EdfoyaqNpQCo:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L778)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove `argp` name, it lacks the context here (you seem to be following man, but it has the function signature, so it makes sense to use such names there; here it does not). IMO just `Each IOCTL struct describes the memory layout of the third argument to the ``ioctl`` system call (typically...`
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NFDojZG8p7M7v_v1OXo:b-6f0fy2) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO there's no good option here and we have to live with some inconsistencies. To me the only sensible options are:
- `size` - has the problem of being non-intuitive for arrays,
- `length` - technically with unit=1B, `length` is correct description of `size`, but it's counter intuitive to provide size of objects in `length` field
</blockquote></details>

Let me keep it as-is for now and wait for others' opinions (if any)
___
*[`Documentation/manifest-syntax.rst` line 819 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEllq4r4JrJo0qPixcu:-NFDtAk39ZMNuqzsNEUc:b-fga52i) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L819)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The differences in C are between `char*` and `char[]`. Here you always have `char*` and just manipulate the length. I guess only `not just a pointer` is confusing to me, but with additional explanation it's at least clear after reading the whole paragraph, so I'm unblocking.
</blockquote></details>

Done. I removed this `not only a pointer` part.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFDws23BODCWw7ha0oV:b18da6t) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
> Or actually "sub-region" could theoretically be multiple "items" as long as they are consecutive and have matching in-out params

This is exactly correct. In fact, that's how I declared many DRM IOCTLs in my tests.

For example, consider this DRM IOCTL: https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/drm.h#L96. It can be described as a single sub-region, with `size = 2*4`. There is no benefit in splitting into four sub-regions.

On the other hand, we have DRM IOCTLs like this: https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/drm.h#L114. it contains the field `padding`, which must have `direction = "none"`, to avoid any memory leaks. So here you have to create three sub-regions: one for consequtive `next` + `prev` + `in_use`, one for `padding` and one for `age`.

> Actually, wouldn't it be easier to just call everything an object?

First, "object" is an overloaded term. Second, I wanted to make it explicit that we're taking about "regions of enclave memory". Third, I don't think that my example above (with `drm_tex_region` that has a field `padding`) will make sense with the word "object" (`padding` is an object? doesn't sound right).
___
*[`Documentation/manifest-syntax.rst` line 817 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFArGWtBCqAADhp0i6x:-NFDpEn87ZzOlqrfcpj1:bjlf3pn) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L817)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this `[ ]` syntax here, it suggest a TOML array, whereas it's just one of the listed strings
</blockquote></details>

We use this syntax in all places in this file (i.e., to list possible values for all other manifest options). But I agree, it's confusing. Let me change it here.

What should we do about the other manifest options? Should we fix them as well in a separate PR?
___
*[`Documentation/manifest-syntax.rst` line 817 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFAbc1p9xpCs5yhXVX7:-NFDq7v02KBsAEBRBdgk:b-ucrj5i) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L817)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`type` doesn't make sense to me in this context. Maybe `direction` or `io` or `rw` (but the last would probably require values to be changed to `read`/`write`)
</blockquote></details>

Done. Chose `direction`.
___
*[`Documentation/manifest-syntax.rst` line 824 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFAqrNU1mG6L1-5WEXl:-NFDsw1h7TkdpqoehCHl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L824)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`[ ]` suggest that there's array of "memory regions", while it's an inlined one (it's the "memory region" itself, that's a TOML array)
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 843 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFAt6d92jLDRYyyYYN_:-NFDwTrRED6Mqwa_8kJ_:baym7y3) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L843)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This makes no sense, if we have `buf_size`, then this [...]

2022-10-25 16:17 UTC, boryspoplawski requested changes
> Reviewed 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 2 of 22 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFErzihCX6zaPaCslXm:b-ftwici) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
>  There is no benefit in splitting into four sub-regions.

I would say otherwise, that there is no much gain in joining them into one. I think most people will use some kind of script to translate the structs into this description (or maybe even we should provide one in the future) and even doing this manually isn't much of a problem.

> First, "object" is an overloaded term.

True, but this case is one of the less controversial cases, e.g. `struct X* some_object = malloc(sizeof(*some_object)));`

> Second, I wanted to make it explicit that we're taking about "regions of enclave memory". 

To me whole enclave memory is a "region". Idk, I find the current naming non-intuitive, but let's hear from others. cc @mkow 

>  (padding is an object? doesn't sound right

It's not really padding, it's an object that's named `padding`, because that's the role it serves, but from C points of view it's not different from `in_use` field/object.
___
*[`Documentation/manifest-syntax.rst` line 817 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFArGWtBCqAADhp0i6x:-NFEr0a12jcJHG5jvsov:b-10e6e6) ([raw file](https://github.com/gramineproject/gramine/blob/21fa8020f97a0c1b2fc3ca7b2b3f559103b0cee3/Documentation/manifest-syntax.rst#L817)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We use this syntax in all places in this file (i.e., to list possible values for all other manifest options). But I agree, it's confusing. Let me change it here.

What should we do about the other manifest options? Should we fix them as well in a separate PR?
</blockquote></details>

I didn't look at them, but if they are confusing (i.e. it's not clear that they are **not** talking about TOML ararys), then I would change them. Maybe we should use `<abc>` or something else? Maybe just create an issue or discuss this on the next call?


<!-- Sent from Reviewable.io -->

2022-10-27 21:27 UTC, boryspoplawski requested changes
> Reviewed 3 of 20 files at r1, 12 of 18 files at r2, 2 of 2 files at r3, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 20 of 22 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/device_ioctl.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOqh5c7oLVV4QFmpwu:-NFOqh5c7oLVV4QFmpwv:b-8wqpov) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L1)):*
> ```C
> #include <alloca.h>
> ```

I don't see `alloca` being used
___
*[`libos/test/regression/device_ioctl.c` line 19 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOr-SF7ueitIuNa2K0:-NFOr-SF7ueitIuNa2K1:brfcn0e) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L19)):*
> ```C
> #define STRING_IOCTL_REPLACED "He$$0 w0r$d via i0ct$s\n"
> 
> struct gramine_test_dev_ioctl_write {
> ```

We shouldn't duplicate these struct and defines. Since we require the device to be installed, we can also require the headers.
___
*[`libos/test/regression/device_ioctl.c` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOtQXK0KJRtqU68GFN:-NFOtQXK0KJRtqU68GFO:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L65)):*
> ```C
>                                                  struct gramine_test_dev_ioctl_replace_list)
> 
> int main(int argc, char* argv[]) {
> ```





_Suggestion:_
```C
int main(void)
```
___
*[`libos/test/regression/device_ioctl.c` line 70 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOtb0IDGbRm6gq6rMo:-NFOtb0J3R4mZNUlNtVU:b-r0v1le) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L70)):*
> ```C
>     char buf[64];
> 
>     int devfd = open("/dev/gramine_test_dev", O_RDWR);
> ```

You can reduce a lot of boilerplate from this file using `CHECK` macro
___
*[`libos/test/regression/device_ioctl.c` line 76 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOufmv7DIQja9INRU4:-NFOufmw3g26e2viQjGT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L76)):*
> ```C
>     /* test 1 -- use write() and read() syscalls */
>     bytes = posix_fd_write(devfd, STRING_READWRITE, sizeof(STRING_READWRITE));
>     if (bytes < 0)
> ```





_Suggestion:_
```C
bytes != sizeof(STRING_READWRITE)
```
___
*[`libos/test/regression/device_ioctl.c` line 84 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOuz-zAklzv3KaSM1x:-NFOuz-zAklzv3KaSM1y:bphgt9j) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L84)):*
> ```C
>     if (offset < 0)
>         err(1, "/dev/gramine_test_dev ioctl(GRAMINE_TEST_DEV_IOCTL_REWIND)");
>     if (offset > 0)
> ```

I would just change this and remove the check above (this error message prints the return value anyway)



_Suggestion:_
```C
if (offset != 0)
```
___
*[`libos/test/regression/device_ioctl.c` line 90 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOvJRl8QydaVaPaimY:-NFOvJRl8QydaVaPaimZ:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L90)):*
> ```C
>     memset(&buf, 0, sizeof(buf));
>     bytes = posix_fd_read(devfd, buf, sizeof(buf) - 1);
>     if (bytes < 0)
> ```





_Suggestion:_
```C
bytes != sizeof(STRING_READWRITE)
```
___
*[`libos/test/regression/device_ioctl.c` line 108 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOw1Yd9aWp_U2PXs24:-NFOvbbP0HxbFEAUbY4y:b-yvp3r5) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L108)):*
> ```C
>     if (ret < 0)
>         err(1, "/dev/gramine_test_dev ioctl(GRAMINE_TEST_DEV_IOCTL_CLEAR)");
> ```

Maybe also use `GRAMINE_TEST_DEV_IOCTL_GETSIZE` here to confirm it returns `0` now?
___
*[`libos/test/regression/device_ioctl.c` line 150 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxpp6--0VX-k_8BOb:-NFOxpp703l6GeOPSRBs:b-z7om5x) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L150)):*
> ```C
>                 "(returned: %ld)", sizeof(STRING_IOCTL), devfd_size);
> 
>     /* test 3 -- use complex ioctl(GRAMINE_TEST_DEV_IOCTL_REPLACE_ARR) syscall */
> ```

Maybe `with complex struct as an argument`? The syscall itself is just the same (i.e. `ioctl(fd, cmd, pointer)`)
___
*[`libos/test/regression/device_ioctl.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOy0Eu3SUslhGqdD5d:-NFOy0EvEnqOm7HpVp5H:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L156)):*
> ```C
>     };
>     struct gramine_test_dev_ioctl_replace_arr replace_arr = {
>         .replacements_cnt = 2,
> ```





_Suggestion:_
```C
ARRAY_LEN(replace_arr)
```
___
*[`libos/test/regression/device_ioctl.c` line 164 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxiL6-SwVbte8eL-q:-NFOxiL6-SwVbte8eL-r:b-myg5q9) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L164)):*
> ```C
> 
>     memset(buf, 0, sizeof(buf));
>     read_arg.off = 0;
> ```

Please reassign `read_arg`, at least to make sure `copied` is reset.



_Suggestion:_
```C
read_arg = (struct gramine_test_dev_ioctl_read){
    .buf_size = sizeof(buf) - 1,
    .buf      = buf,
};
```
___
*[`libos/test/regression/device_ioctl.c` line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOwUFoEOjTxRQKJc6L:-NFOwUFoEOjTxRQKJc6M:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L172)):*
> ```C
>              STRING_IOCTL_REPLACED);
> 
>     /* test 4 -- use complex ioctl(GRAMINE_TEST_DEV_IOCTL_REPLACE_LIST) syscall */
> ```

ditto
___
*[`libos/test/regression/device_ioctl.c` line 187 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxm5jCebpZAn4Ug2I:-NFOx8Ib3W8ImTTpNLEQ:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L187)):*
> ```C
> 
>     memset(buf, 0, sizeof(buf));
>     read_arg.off = 0;
> ```

ditto
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NFP1bhbASr8pdcMgG9Q:b-qif1q4) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
> ```
> ]
> 
> sgx.nonpie_binary = true
> ```

Why this?
___
*[`libos/test/regression/device_ioctl.manifest.template` line 23 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP2E3A2OxRcLmzDDgF:-NFP2E3A2OxRcLmzDDgG:b-7nte21) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L23)):*
> ```
> 
> # for IOCTLs without an argument (or with integer argument)
> sgx.ioctl_structs.gramine_test_dev_ioctl_dummy = [ ]
> ```

Not needed anymore?
___
*[`libos/test/regr [...]

2022-10-31 11:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 10 of 22 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/regression/device_ioctl.c` line 1 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOqh5c7oLVV4QFmpwu:-NFhY0vI3Bgz2IzDHfel:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't see `alloca` being used
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 19 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOr-SF7ueitIuNa2K0:-NFhY1R28QfUSZ2WOW5a:biby8zi) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We shouldn't duplicate these struct and defines. Since we require the device to be installed, we can also require the headers.
</blockquote></details>

Done. See also corresponding changes in https://github.com/gramineproject/device-testing-tools/pull/3
___
*[`libos/test/regression/device_ioctl.c` line 65 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOtQXK0KJRtqU68GFN:-NFhY8zN8PH0AQ2sxdAJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L65)):*
> ```C
>                                                  struct gramine_test_dev_ioctl_replace_list)
> 
> int main(int argc, char* argv[]) {
> ```

Done.
___
*[`libos/test/regression/device_ioctl.c` line 70 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOtb0IDGbRm6gq6rMo:-NFhhVcK2zscAJ01jyl7:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can reduce a lot of boilerplate from this file using `CHECK` macro
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 76 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOufmv7DIQja9INRU4:-NFhZM_Q0eXCBe0dKm44:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L76)):*
> ```C
>     /* test 1 -- use write() and read() syscalls */
>     bytes = posix_fd_write(devfd, STRING_READWRITE, sizeof(STRING_READWRITE));
>     if (bytes < 0)
> ```

Done.
___
*[`libos/test/regression/device_ioctl.c` line 84 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOuz-zAklzv3KaSM1x:-NFhZUajDfQR6uxIjZ9t:bxx4cs4) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L84)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would just change this and remove the check above (this error message prints the return value anyway)
</blockquote></details>

Done. Not just removed the check above but wrapped it into `CHECK()`.
___
*[`libos/test/regression/device_ioctl.c` line 90 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOvJRl8QydaVaPaimY:-NFhZeim7sH9eueJC9-m:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L90)):*
> ```C
>     memset(&buf, 0, sizeof(buf));
>     bytes = posix_fd_read(devfd, buf, sizeof(buf) - 1);
>     if (bytes < 0)
> ```

Done.
___
*[`libos/test/regression/device_ioctl.c` line 108 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOw1Yd9aWp_U2PXs24:-NFh_-881fMlRiykFlMy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe also use `GRAMINE_TEST_DEV_IOCTL_GETSIZE` here to confirm it returns `0` now?
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 150 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxpp6--0VX-k_8BOb:-NFh_EEaCmeYCwVSRXeA:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L150)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `with complex struct as an argument`? The syscall itself is just the same (i.e. `ioctl(fd, cmd, pointer)`)
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 156 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOy0Eu3SUslhGqdD5d:-NFh_NtrDo3d7A9obKaa:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L156)):*
> ```C
>     };
>     struct gramine_test_dev_ioctl_replace_arr replace_arr = {
>         .replacements_cnt = 2,
> ```

Done.
___
*[`libos/test/regression/device_ioctl.c` line 164 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxiL6-SwVbte8eL-q:-NFh_oVcBwaG3oecJAuk:b6lvory) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please reassign `read_arg`, at least to make sure `copied` is reset.
</blockquote></details>

Done.

I'm not sure what you want to do with `copied`. Do you just want it to be reset? Or do you also want to check this field after the IOCTL?
___
*[`libos/test/regression/device_ioctl.c` line 172 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOwUFoEOjTxRQKJc6L:-NFh_wEt3hG92mSbVFQy:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L172)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 187 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxm5jCebpZAn4Ug2I:-NFha42A0dzwyLDqO7EF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NFhaPmD9hsV6Z54ltPg:b-i3wqkj) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this?
</blockquote></details>

It's just set in all our regression tests. Not needed, but helpful in debugging (one base address less to change from debug session to debug session).
___
*[`libos/test/regression/device_ioctl.manifest.template` line 23 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP2E3A2OxRcLmzDDgF:-NFhayde3NTIV51JlIVH:b-2kosvg) ([raw file](https://github.com/gramineproject/gr [...]

2022-10-31 18:02 UTC, boryspoplawski requested changes
> Reviewed 10 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 19 of 22 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/device_ioctl.c` line 164 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFOxiL6-SwVbte8eL-q:-NFiku3S0uxuPpi1hV7e:br4lnll) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.c#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

I'm not sure what you want to do with `copied`. Do you just want it to be reset? Or do you also want to check this field after the IOCTL?
</blockquote></details>

Sorry, I thought it was used to in some checks below, but seems it's not.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NFilBFZChnNf4pwVvRp:b-nv1qfx) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's just set in all our regression tests. Not needed, but helpful in debugging (one base address less to change from debug session to debug session).
</blockquote></details>

It's set in `mnifest.template` in LibOS regression tests, because we have one template for multiple tests and some of them need this option. Here it's not needed.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 27 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP2FZ8DsfWmfDsKnH3:-NFiliXy7ugLdTsrsLEV:bgy325t) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. Do you think it's only confusing, and I should remove this "empty-array" syntax completely?
</blockquote></details>

Yes, I don't see why anybody would want to use it (create some dummy structs), if they can simply write `""` or even omit this field.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 66 at r6](https://reviewable.io/reviews/gramineproject/gramine/671#-NFimhf04OLIZZtVb7ip:-NFimhf04OLIZZtVb7iq:bh1mv5c) ([raw file](https://github.com/gramineproject/gramine/blob/59b09b7e0eed69d907f78263cc5d8bd82cb37fab/libos/test/regression/device_ioctl.manifest.template#L66)):*
> ```
> 
> sgx.ioctl_structs.gramine_test_dev_ioctl_replace_list = [
>     { size = 2, units = 1, direction = "out" },    # src, dst; `units` is just for testing
> ```

If it's for testing, then maybe do `size = 1, units = 2`, because `units = 1` is the default
___
*[`libos/test/regression/meson.build` line 19 at r6](https://reviewable.io/reviews/gramineproject/gramine/671#-NFinDzA5rm3RgGYLul4:-NFinDzA5rm3RgGYLul5:b-ybxokc) ([raw file](https://github.com/gramineproject/gramine/blob/59b09b7e0eed69d907f78263cc5d8bd82cb37fab/libos/test/regression/meson.build#L19)):*
> ```Meson
>         'include_directories': include_directories(
>             # for `gramine_test_dev_ioctl.h`
>             '/usr/local/include/',
> ```

This path is included by default
___
*[`pal/include/pal/pal.h` line 874 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQGHGJ2Nnmu62kZ6kY:-NFj20l-87Edxv_S_J0B:bo9cat8) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/include/pal/pal.h#L874)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

comma still there
___
*[`pal/include/pal/pal.h` line 883 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQHKH0CVwhO7sOjoop:-NFj1cywC7mmpPg6t4U8:b-y68gdw) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/include/pal/pal.h#L883)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, though I guess our codebase is absolutely not ready for 32-bit archs anyway.
</blockquote></details>

I wouldn't say absolutely, there would be issues definitely, especially with the old code, but it should be doable (though with much effort).
___
*[`pal/src/host/linux/pal_devices.c` line 224 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQIRolC_Op4REgqGMk:-NFj2N8_7dKakoZesks_:b-kg50ad) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux/pal_devices.c#L224)):*
> I guess you missed the fact that many IOCTLs return some this-ioctl-specific positive value, and not just zero.

No, I was just confused why it returns device-specific return values via `out_ret` but error codes, which can also be device-specific, directly.

Generally this whole feature will make no sense on non-Linux PALs (because original ioctl requests come from a Linux app), so it's hard for me to reason about conventions here.


<!-- Sent from Reviewable.io -->

2022-10-31 22:16 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 20 of 22 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`libos/test/regression/device_ioctl.c` line 1 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFk6IGJ9lL8gLZZFtnS:-NFk6IGJ9lL8gLZZFtnT:bjwq7yn) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/libos/test/regression/device_ioctl.c#L1)):*
> ```C
> #define _GNU_SOURCE /* for loff_t */
> ```

Actually, shouldn't we use `off_t` for user facing API (ioctls)? TBH I not sure what are the rules here, which type should be used where...


<!-- Sent from Reviewable.io -->

2022-11-01 02:29 UTC, boryspoplawski requested changes
> Reviewed 1 of 18 files at r2, 1 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 67 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 225 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkDtMk3ETeEbczEGHa:-NFkDtMk3ETeEbczEGHb:b-vd89w9) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L225)):*
> ```C
> 
> /*
>  * Code below describes the deep-copy syntax in the TOML manifest used for copying complex nested
> ```

This read weirdly for me (deep-copy syntax?), maybe:



_Suggestion:_
```C
Code below describes the TOML syntax of the manifest entries used for deep-copying complex nested
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 228 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkN5bb7vS316OTrP8Q:-NFkN5bb7vS316OTrP8R:bog5ark) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L228)):*
> ```C
>  * objects out and inside the SGX enclave. This syntax is currently used for IOCTL emulation. This
>  * syntax is generic enough to describe any memory layout for deep copy of IOCTL structs.
>  *
> ```

I would add a note here, that "high level"/"syntax" description is in "manifest syntax" docs.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 236 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkG0z30botrnKFg49k:-NFkG0z30botrnKFg49l:b-4nz7cz) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L236)):*
> ```C
>  *
>  *   alignas(128) struct root obj;
>  *   ioctl(devfd, _IOWR(DEVICE_MAGIC, DEVICE_FUNC, struct root), &obj);
> ```

Just so you are able to refer it below



_Suggestion:_
```C
DEV_IOCTL_NUMBER
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 249 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkFZ9_BZsj6DCB7YDq:-NFkFZ9_BZsj6DCB7YDr:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L249)):*
> ```C
>  * occurences of chars "x" and "y" in the Pascal string.
>  *
>  * The corresponding deep-copy syntax in TOML looks like this:
> ```





_Suggestion:_
```C
The corresponding manifest entries describing this structs look like this:
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 252 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkFhxyBGl96tutzZD7:-NFkFhxyBGl96tutzZD8:b-oaoau2) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L252)):*
> ```C
>  *
>  *   sgx.ioctl_structs.ROOT_FOR_DEVICE_FUNC = [
>  *     { align = 128, ptr = [ {name="pascal-str-len", size=1, direction="out"},
> ```

Please add more spaces (especially around `=`).
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 254 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkHYJ9-oKYG0ba6C-5:-NFkHYJ9-oKYG0ba6C-6:b-vsqfzd) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L254)):*
> ```C
>  *     { align = 128, ptr = [ {name="pascal-str-len", size=1, direction="out"},
>  *                            {name="pascal-str", size="pascal-str-len", direction="out"} ] },
>  *     { ptr = [ {name="c-str", size="c-str-len", direction="in"} ], size = 1 },
> ```

This looks wrong to me. Am I missing something?



_Code quote:_
```C
size = 1 
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 255 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkI4MW3bq0ObX9CkfQ:-NFkI4MW3bq0ObX9CkfR:bjy619) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L255)):*
> ```C
>  *                            {name="pascal-str", size="pascal-str-len", direction="out"} ] },
>  *     { ptr = [ {name="c-str", size="c-str-len", direction="in"} ], size = 1 },
>  *     { name = "c-str-len", size = 8, unit = 1, adjust = 0, direction = "inout" },
> ```

These make it only more confusing. This is not docs trying to describe all possible options, so I would just remove them



_Code quote:_
```C
 unit = 1, adjust = 0, 
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 256 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkHs5M-w8wyP_WgkZX:-NFkHs5M-w8wyP_WgkZY:bj3ma0t) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L256)):*
> ```C
>  *     { ptr = [ {name="c-str", size="c-str-len", direction="in"} ], size = 1 },
>  *     { name = "c-str-len", size = 8, unit = 1, adjust = 0, direction = "inout" },
>  *     { size = 2, direction = "in" }
> ```

Wait, why is this `size = 2`?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 257 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkHtz30ENtDaJ5Rjgz:-NFkHtz44TSJIillrGxi:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L257)):*
> ```C
>  *     { name = "c-str-len", size = 8, unit = 1, adjust = 0, direction = "inout" },
>  *     { size = 2, direction = "in" }
>  *     { size = 2, direction = "in" }
> ```

ditto
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 260 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkG7tP54YlLsn4xT39:-NFkG7tQ5Bp7pq343sja:b-efy5e0) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L260)):*
> ```C
>  *   ]
>  *
>  *   sgx.allowed_ioctls.DEVICE_FUNC.request_code = <DEVICE_MAGIC hex>
> ```

If you rename above then you could refer to it also here.
Note that in your example `DEVICE_MAGIC` is just some constant, which is used as argument to ioctl-number creating macros (like `_IOW`), so this is a misleading.



_Suggestion:_
```C
DEV_IOCTL_NUMBER
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 268 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkO7mN4_8FQqCvgXzn:-NFkO7mN4_8FQqCvgXzo:bvb4pz8) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L268)):*
> ```C
>  *  2. Each sub-region of one memory region is represented as a TOML table (`{}`).
>  *  3. Each sub-region may be a pointer (`ptr`) to another memory region. In this case, the value of
>  *     `ptr` is a TOML-array representation of that other memory region. The `ptr` sub-region always
> ```

It can also be a name of another struct/memory region, right?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 269 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkOCK431mXFuV1ixPZ:-NFkOCK431mXFuV1ixP_:bhmldzs) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L269)):*
> ```C
>  *  3. Each sub-region may be a pointer (`ptr`) to another memory region. In this case, the value of
>  *     `ptr` is a TOML-array representation of that other memory region. The `ptr` sub-region always
>  *     has size of 8B (assuming x86-64) and doesn't have an in/out direction.  The `size` field of
> ```

Actually, why is size hardcoded? `8B` is a good default, but why it cannot be overwritten explicitly?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 270 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkOicq-EQpV_EDUMo_:-NFkO [...]

2022-11-01 19:25 UTC, mkow requested changes
> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 73 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
> ioctl arguments are passed as-is from the app to the untrusted host, without encryption

This IMO sounds misleading, encryption wouldn't change anything if the destination is the host. It may be read as "if you do a TLS tunnel with the driver then you're fine".

> In particular, ioctl arguments should be encrypted or integrity-protected with a key pre-shared between Gramine and the device.

This isn't always true, depends on the specific case. Please change to "In most cases" or something like that.

Otherwise looks good.
___
*[`-- commits` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoX8I1984Kb99hg4Dg):*
Wouldn't it be a better design to have this in LibOS? I.e. not backend-specific.



_Code quote:_
```
On the Linux-SGX PAL
```
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NFob6gnA8j8JM6V72-S:b-udqcz4) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me keep it as-is for now and wait for others' opinions (if any)
</blockquote></details>

I'd go with separate names, but maybe `size` and `array_len` / `array_cnt` instead of what you proposed to make the distinction more obvious (users may not know our source code convention about "size" meaning "byte-size").
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NFoZeZb7Pumqgf5Xmi1:b-3ovak9) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
> ```reStructuredText
>     sgx.ioctl_structs.[identifier] = [memory-layout-format]
> 
>     sgx.allowed_ioctls.[identifier].request_code = [NUM]
> ```

What's the point of this ID? Shouldn't this be an array?



_Code quote:_
```reStructuredText
sgx.allowed_ioctls.[identifier].request_code = [NUM]
```
___
*[`Documentation/manifest-syntax.rst` line 775 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFo_Gj30ffUS81-eX9F:-NFo_Gj30ffUS81-eX9G:bopdgd) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L775)):*
> Each IOCTL entry may also contain a reference to an IOCTL struct in the ``struct`` field.

What happens if it doesn't have it?
___
*[`Documentation/manifest-syntax.rst` line 812 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFobkTY1nV6-1b47lUm:-NFobkTY1nV6-1b47lUn:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L812)):*
> ```reStructuredText
>   default. Unit of measurement must be a constant integer. For example,
>   ``size = "strlen"`` and ``unit = 2`` denote a wide-char string (where each
>   character is 2B long) of a dynamically calculated length.
> ```





_Suggestion:_
```reStructuredText
dynamically specified length
```
___
*[`Documentation/manifest-syntax.rst` line 887 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFodNvW7V87QeAwF0pn:-NFodNvXCVMp99WRf2Py:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L887)):*
> ```reStructuredText
>    themselves in SGX environments:
> 
>        - IOCTL arguments are passed as-is from the app to the untrusted host,
> ```

ditto



_Code quote:_
```reStructuredText
       - IOCTL arguments are passed as-is from the app to the untrusted host,
         without encryption; this may lead to leaks of enclave data.
```
___
*[`Documentation/manifest-syntax.rst` line 890 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFodcD4De8C9fnwAkzK:-NFodcD4De8C9fnwAkzL:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L890)):*
> ```reStructuredText
>          without encryption; this may lead to leaks of enclave data.
>        - Untrusted host can change IOCTL arguments as it wishes when passing
>          them from Gramine to the device and back.
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-11-01 22:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 73 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoX8I1984Kb99hg4Dg):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't it be a better design to have this in LibOS? I.e. not backend-specific.
</blockquote></details>

Idk, this whole feature doesn't make much sense, if the host isn't Linux...
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NFpK5eC6uae0TRYdkqm:b-vvowd7) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd go with separate names, but maybe `size` and `array_len` / `array_cnt` instead of what you proposed to make the distinction more obvious (users may not know our source code convention about "size" meaning "byte-size").
</blockquote></details>

I'll copy my comment from code part, so we don't split this discussion:

"So, to continue the discussion from docs, this is a bit confusing. Maybe we should have size mean the size of the pointer and a new length parameter, which would describe length of the array?"
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NFpJ6DHAL2azXZO2lVJ:bomwxu0) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of this ID? Shouldn't this be an array?
</blockquote></details>

You need to somehow tie struct to ioctl request code. So either this or and array of pairs (which I guess means array of 2-size lists in TOML). IMO this is more readable.
___
*[`Documentation/manifest-syntax.rst` line 775 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFo_Gj30ffUS81-eX9F:-NFpJUXc7VIc3icv1Qem:bcqa6i1) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L775)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Each IOCTL entry may also contain a reference to an IOCTL struct in the ``struct`` field.

What happens if it doesn't have it?
</blockquote></details>

It's passed as is (i.e. just the value is forwarded to host, whatever that value is). I swear it was described somewhere....


<!-- Sent from Reviewable.io -->

2022-11-02 00:06 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 73 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoX8I1984Kb99hg4Dg):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, this whole feature doesn't make much sense, if the host isn't Linux...
</blockquote></details>

Hmmm, good point. But it's also not really SGX-specific, rather TEE-specific. Maybe the code should go to Linux-common then?
But I won't block here, I missed that it's indeed host-Linux-specific.
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NFpZb7QAiE6HlcnLfsJ:b-auwhvn) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll copy my comment from code part, so we don't split this discussion:

"So, to continue the discussion from docs, this is a bit confusing. Maybe we should have size mean the size of the pointer and a new length parameter, which would describe length of the array?"
</blockquote></details>

That also sounds good to me.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFpcVcj4M_bR5zrrvxq:b-s0gw0h) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
Hmm, both versions sound equally understandable to me. I agree that using name "object" is a bit confusing when used for a padding field. Maybe just use "chunk" or something like this instead of "region"?

> > There is no benefit in splitting into four sub-regions.
>
> I would say otherwise, that there is no much gain in joining them into one. I think most people will use some kind of script to translate the structs into this description (or maybe even we should provide one in the future) and even doing this manually isn't much of a problem.

Hmm, this discussion is rather orthogonal to the naming issue? It's just about wondering how users will describe their structs with the currently available syntax?
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NFpWOMN2HQqW1OmpHO4:byin5zu) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You need to somehow tie struct to ioctl request code. So either this or and array of pairs (which I guess means array of 2-size lists in TOML). IMO this is more readable.
</blockquote></details>

But here you need to invent some unique name for each entry, which e.g. for old trusted files/mounts syntax was quite annoying (e.g. it was very easy to make copy-paste errors).
Why not an array of pairs? Using `[[ ]]` TOML syntax it should be quite readable? The example from the docs would change this way:

```Toml
sgx.allowed_ioctls.io1.request_code = 0x12345678
sgx.allowed_ioctls.io1.struct = "ioctl_read"

sgx.allowed_ioctls.io2.request_code = 0x87654321
sgx.allowed_ioctls.io2.struct = "ioctl_read"
```
->
```Toml
[[sgx.allowed_ioctls]]
request_code = 0x12345678
struct = "ioctl_read"

[[sgx.allowed_ioctls]]
request_code = 0x87654321
struct = "ioctl_read"
```
___
*[`Documentation/manifest-syntax.rst` line 775 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFo_Gj30ffUS81-eX9F:-NFpXPWDBR2ERjCyPT0k:bd6iu1j) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L775)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's passed as is (i.e. just the value is forwarded to host, whatever that value is). I swear it was described somewhere....
</blockquote></details>

Yeah, it is, but this place alone sounds weird. I'd add something like "in case the third (or whichever it was) ioctl argument is intended to be translated by Gramine" to the end.


<!-- Sent from Reviewable.io -->

2022-11-02 00:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 85 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 385 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpX--bE2K7wquJrCrR:-NFpX--bE2K7wquJrCrS:b-89l48e) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L385)):*
> ```C
> 
> /* finds a sub region with name `sub_region_name` among `sub_regions` and reads the value in it */
> static int get_sub_region_value(struct sub_region* sub_regions, size_t sub_regions_cnt,
> ```

This function actually gets only value of regions which is a size of another region (or more precisely an integer). The name does not imply this at all.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 396 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpdqPg9ovJctevk7nc:-NFpdqPg9ovJctevk7nd:b-e48x3p) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L396)):*
> ```C
>                           sub_regions[idx].name_hash, sub_region_name_hash)) {
>             /* found corresponding sub region, read its value */
>             if (!sub_regions[idx].encl_addr || sub_regions[idx].encl_addr == (void*)-1) {
> ```

How can this even this addr be `-1`? Why don't you check `-2` too?



_Code quote:_
```C
-1
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 413 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpWOOU5dE1Ssx7frzG:-NFpWOOU5dE1Ssx7frzH:be0klh2) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L413)):*
> ```C
>                           "legitimate size: 1, 2, 4 or 8 bytes)", sub_regions[idx].name);
>                 return -PAL_ERROR_INVAL;
>             }
> ```

Why not



_Suggestion:_
```C
            if (sub_regions[idx].size > 8) {
                log_error("blablabla", sub_regions[idx].name);
                return -PAL_ERROR_INVAL;
            }
            *out_value = 0;
            memcpy(out_value, sub_regions[idx].encl_addr, sub_region[idx].size);
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 424 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkvU4f55vAb6bHNrKA:-NFphILGBSk8Y3WyKNuM:bsbjewn) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L424)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This function is quite big. Could it be split into multiple? I've not reviewed it yet, so maybe it makes no sense to do so.
</blockquote></details>

Ok, I give up, it's impossible to reason about variables, their lifetime and what is what, it's too long. Please refactor/split it.
I did more general review of it, without the details for now
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 435 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpXtxuDR5FayfWjIYg:-NFpXtxuDR5FayfWjIYh:bh9s135) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L435)):*
> ```C
> 
>     assert(pal_get_enclave_tcb()->ioctl_scratch_space);
>     struct mem_region* mem_regions = (struct mem_region*)pal_get_enclave_tcb()->ioctl_scratch_space;
> ```

Why this function gets `sub_regions` as an argument (which is this scratch space + some offset) and `mem_regions` directly from tcb? Please unify (preferably both as arguments).
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 452 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFp_hZhCm0gfVsTj3Ls:-NFp_hZhCm0gfVsTj3Lt:b-ucgkch) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L452)):*
> ```C
>             cur_encl_addr = cur_mem_region->encl_addr;
> 
>         size_t cur_mem_region_first_sub_region = sub_regions_cnt;
> ```

This is not a region, but an index? Even to not yet populated region, I believe



_Code quote:_
```C
cur_mem_region_first_sub_region 
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 453 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpamhbEt0j1a0I9_2N:-NFpamhbEt0j1a0I9_2O:b-p50cov) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L453)):*
> ```C
> 
>         size_t cur_mem_region_first_sub_region = sub_regions_cnt;
> ```

Please add `assert(toml_array_nelem(cur_mem_region->toml_array) >= 0);`
Actually is it even checked anywhere?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 477 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpdyVV8fGstW_tUVfV:-NFpdyVV8fGstW_tUVfW:b-i801d4) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L477)):*
> ```C
> 
>             cur_sub_region->encl_addr = cur_encl_addr;
>             if (!cur_encl_addr || cur_encl_addr == (void*)-1) {
> ```

How can this addr be `-1`?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 480 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpkIA_8f0TPtfbmNIX:-NFpkIA_8f0TPtfbmNIY:b-z7wgni) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L480)):*
> ```C
>                 /* enclave address is invalid, user provided bad struct */
>                 ret = -PAL_ERROR_DENIED;
>                 goto out;
> ```

Isn't `name` and `name_size` undefined here? It will be `free`ed after this `goto out`.
This applies to many other `goto`s in this function. Please just split it into multiple smaller ones, will be much easier to spot such problems.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NFpgkTKC_YL6ywXlAkN:b-yq2vam) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> ```C
>                     if (!strcmp(sub_region_name, "this")) {
>                         /* special case of `{ptr="this"}` -- ptr to object of the IOCTL root type */
>                         sub_region_ptr_arr = root_toml_array;
> ```

Hmmm, so `this` doesn't mean this struct/memory region, but the first one defined? What if:
```
struct A {
    struct B* ptr;
};

struct B {
   ...
    struct B* this;
};
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 510 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpiwe61wvC9UJ-eMme:-NFpiwe61wvC9UJ-eMmf:b5z29hp) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L510)):*
> ```C
>                     } else {
>                         size_t idx;
>                         ret = get_sub_region_idx(sub_regions, sub_regions_cnt, sub_region_name,
> ```

Wait, isn't `sub_region_name` actually a name of another memory region?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 511 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpfDNP3dt1bV5H8TE9:-NFpfDNP3dt1bV5H8TEA:b-3umkum) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L511)):*
> ```C
>                         size_t idx;
>                         ret = get_sub_region_idx(sub_regions, sub_regions_cnt, sub_region_name,
>                                 hash [...]

2022-11-02 00:39 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 85 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFplRtYCN8RZfgaP0DZ:b8rbnfj) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, both versions sound equally understandable to me. I agree that using name "object" is a bit confusing when used for a padding field. Maybe just use "chunk" or something like this instead of "region"?

> > There is no benefit in splitting into four sub-regions.
>
> I would say otherwise, that there is no much gain in joining them into one. I think most people will use some kind of script to translate the structs into this description (or maybe even we should provide one in the future) and even doing this manually isn't much of a problem.

Hmm, this discussion is rather orthogonal to the naming issue? It's just about wondering how users will describe their structs with the currently available syntax?
</blockquote></details>

But depending on how you describe the struct, the naming might change (e.g. `object` would make 0 sense if it was supposed to describe two consecutive fields of a struct). So not really orthogonal.


<!-- Sent from Reviewable.io -->

2022-11-03 15:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 85 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ioctl arguments are passed as-is from the app to the untrusted host, without encryption

This IMO sounds misleading, encryption wouldn't change anything if the destination is the host. It may be read as "if you do a TLS tunnel with the driver then you're fine".

> In particular, ioctl arguments should be encrypted or integrity-protected with a key pre-shared between Gramine and the device.

This isn't always true, depends on the specific case. Please change to "In most cases" or something like that.

Otherwise looks good.
</blockquote></details>

@mkow What about this improved text.

```
  The newly added `ioctl()` syscall emulation on device-backed file
  descriptors is pass-through. It is insecure by itself since the
  emulation only passes the arguments to and from the untrusted memory:
    - ioctl arguments are passed as-is from the app to the untrusted host,
      which may lead to leaks of secret data;
    - untrusted host can change ioctl arguments as it wishes when passing
      them from Gramine to the device and back.

  It is the responsibility of the app developer to correctly use ioctls,
  with security implications in mind. In most cases, ioctl arguments should
  be encrypted or integrity-protected with a key pre-shared between
  Gramine and the device.
```
___
*[`-- commits` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoX8I1984Kb99hg4Dg):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmmm, good point. But it's also not really SGX-specific, rather TEE-specific. Maybe the code should go to Linux-common then?
But I won't block here, I missed that it's indeed host-Linux-specific.
</blockquote></details>

I suggest I continue with the PR as-is for now, and either before merge or after merge (in a follow-up PR) I can move to e.g. Linux-common.
___
*[`Documentation/manifest-syntax.rst` line 798 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElk7xJ2j9A9CyFe3vh:-NFy4eb6-MIu_utHrcit:b-ffm4v4) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L798)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That also sounds good to me.
</blockquote></details>

Done. Now we have `size` for normal objects (non-pointers) and `array_len` for arrays (pointers).

I see no reason to have an additional `size` keyword for pointers/arrays, because they are currently always 8 bytes in size. So I simply error out when I detect this keyword on pointers.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NFxS8W6C0mWrpvAWMXD:b-3u1vka) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But depending on how you describe the struct, the naming might change (e.g. `object` would make 0 sense if it was supposed to describe two consecutive fields of a struct). So not really orthogonal.
</blockquote></details>

I don't like the word "chunk". Chunks are fixed-sized in my mind, and that's not true in our case.

I'm still leaning towards my current "region" + "sub-region" terminology. By the way, if we would go with "objects", would we have "objects" and "sub-objects"? Or would we have "objects" and "object fields"?
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NFy4bF-29rdQ8KsOzWT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But here you need to invent some unique name for each entry, which e.g. for old trusted files/mounts syntax was quite annoying (e.g. it was very easy to make copy-paste errors).
Why not an array of pairs? Using `[[ ]]` TOML syntax it should be quite readable? The example from the docs would change this way:

```Toml
sgx.allowed_ioctls.io1.request_code = 0x12345678
sgx.allowed_ioctls.io1.struct = "ioctl_read"

sgx.allowed_ioctls.io2.request_code = 0x87654321
sgx.allowed_ioctls.io2.struct = "ioctl_read"
```
->
```Toml
[[sgx.allowed_ioctls]]
request_code = 0x12345678
struct = "ioctl_read"

[[sgx.allowed_ioctls]]
request_code = 0x87654321
struct = "ioctl_read"
```
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 775 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFo_Gj30ffUS81-eX9F:-NFxR53XCf_eGbZnsRyS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L775)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, it is, but this place alone sounds weird. I'd add something like "in case the third (or whichever it was) ioctl argument is intended to be translated by Gramine" to the end.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 812 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFobkTY1nV6-1b47lUm:-NFxRuwqAJ9sYWO3faUn:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L812)):*
> ```reStructuredText
>   default. Unit of measurement must be a constant integer. For example,
>   ``size = "strlen"`` and ``unit = 2`` denote a wide-char string (where each
>   character is 2B long) of a dynamically calculated length.
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 887 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFodNvW7V87QeAwF0pn:-NFxScTS0POPb75d23kp:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L887)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 890 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFodcD4De8C9fnwAkzK:-NFxScsH9IMjsvpdkVZd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L890)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 1 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFk6IGJ9lL8gLZZFtnS:-NFxahKO8BZpjI3iZUZK:b-zh9ufx) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/libos/test/regression/device_ioctl.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, shouldn't we use `off_t` for user facing API (ioctls)? TBH I not sure what are the rules here, which type should be used where...
</blockquote></details>

From what I gather, `loff_t` is fine to use in userspace apps.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/review [...]

2022-11-04 15:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 16 of 22 files reviewed, 85 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 252 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkFhxyBGl96tutzZD7:-NG0xW561wPwqLE35klT:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L252)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add more spaces (especially around `=`).
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 332 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkTUa34lMkuLWh5Due:-NG165Ls3LQEnGrGifTK:b-3fnn53) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L332)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

misaligned comment
</blockquote></details>

Done. That's on purpose because other comments then will exceed 100-char-limit. I think it is ok in this case.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NG16CsF-fsoT1qBh2Gg:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why signed?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 336 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkU6Th-anNuQxc2ylq:-NG16DoCCpx6VQYsUvFz:b-t8mgj1) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L336)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Reworked this into a `struct dynamic_value`.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 339 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUK2X8U575U1MZfLN:-NG16Qv_Ddrb56JUzPil:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L339)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 343 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUWJx0VIVxDoRPap8:-NG2Bk-t8TqEVH2nqs_p:bklim0m) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L343)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm surprised. Shouldn't this be `struct mem_region*`?
I've not yet read rest of the code, but from the description I would expect it
</blockquote></details>

Well, not, because we create `struct mem_region*` on the fly.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 346 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUnYhD2czvXSXYE4A:-NG16Uqz-DmRXQ7GGIxb:bqauw0u) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L346)):*
> ```C
> };
> 
> static inline uint64_t hash(char* str) {
> ```

Done. I removed the string hashes for now, to simplify the PR. This was giving me some substantial perf benefits, so I may re-introduce it in follow-up PRs. I left some FIXME comments to remember this.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 351 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkV0KB0DZiSGowsJ3b:-NG16drFCbgmQhUXLSMy:b-j3j9f9) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L351)):*
> ```C
>     char c;
>     while ((c = *str++))
>         hash = ((hash << 5) + hash) + c;
> ```

Done. Not relevant.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 358 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkY4-36jQcrf3HUpml:-NG16f8XE4y8x3gAg7S8:b-j3j9f9) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L358)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We literally check this in the line above...
</blockquote></details>

Done. Not relevant.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 367 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFktk3g0Wb4JnKCv4ke:-NG16hCbAAr9wkrT6oHp:b2lk7cv) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L367)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't understand this. Maybe it gets cleaner when I read the usage.
</blockquote></details>

Should I expand the comment? This is basically for the cases of arrays: then each new sub region has the same name (the array item name), but when we call this function, we need to get the *last* item of the array. Well, I don't know how to explain it exactly, it's like what IOCTL structs do.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 374 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkrVAJ8Fc-e83BGcOD:-NG179n73AzjgNIOikUQ:bo8zy3) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L374)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Description above, and more importantly the name of this function do not imply this requirement...
</blockquote></details>

Done. You're right, I moved this check out of this func, it doesn't belong here but to the caller.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 385 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpX--bE2K7wquJrCrR:-NG1zVRq5j4C2EE-vJ09:b-if2ncd) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L385)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This function actually gets only value of regions which is a size of another region (or more precisely an integer). The name does not imply this at all.
</blockquote></details>

Done. This function was removed, and its usages were inlined.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 396 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpdqPg9ovJctevk7nc:-NG18PjeAsMnftT-9RbO:bd2qoet) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L396)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How can this even this addr be `-1`? Why don't you check `-2` too?
</blockquote></details>

Done. Removed it. It was for some LTP tests (iirc), because they tend to supply `-1` as a wrong pointer, just for testing.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 413 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpWOOU5dE1Ssx7frzG:-NG1AK2UC0GXfKiHzceE:b-46pcr0) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/s [...]

2022-11-07 02:09 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 64 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 10 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoX8I1984Kb99hg4Dg):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest I continue with the PR as-is for now, and either before merge or after merge (in a follow-up PR) I can move to e.g. Linux-common.
</blockquote></details>

+1, let's not change that in the middle of review
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NGDuZdN5fJ75563i9cj:br2phmx) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
I don't like "chunk" either.

> if we would go with "objects", would we have "objects" and "sub-objects"? Or would we have "objects" and "object fields"?

"sub-objects" sound weird. I would say we could just use `memory region` -> `struct` and `memory sub-region` -> `struct member`/`struct element`.
After reading it so many times, I already got used to "memory region", but it wasn't obvious at the first glance (at least to me). I'm unblocking.

Btw, you already use "object": `a pointer to a complex nested`**`object`**`passed to the device`
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NGDtF8R5EpzoaEotn6l:b3lzzzb) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? Definitely not in the docs (didn't look at the code yet).
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NGE-VPr8Q1RYNtJqve3:b-bldhlr) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Tried to remove it, but I can't -- GCC (at least current GCC on my Ubuntu 20.04) creates a non-PIE executable by default. I can change this in `meson.build` of course, but do we want to?
</blockquote></details>

Idk then. Since we need to use some option somewhere (i.e. defaults won't do), I would say we should have non-pie, but I wont' block.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 66 at r6](https://reviewable.io/reviews/gramineproject/gramine/671#-NFimhf04OLIZZtVb7ip:-NGE0MQ38ckKXtB75O-b:btol76z) ([raw file](https://github.com/gramineproject/gramine/blob/59b09b7e0eed69d907f78263cc5d8bd82cb37fab/libos/test/regression/device_ioctl.manifest.template#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Lol, so there was a typo with `s` at the end and it didn't work? :)
___
*[`libos/test/regression/device_ioctl.manifest.template` line 50 at r8](https://reviewable.io/reviews/gramineproject/gramine/671#-NGE0ed76j15d08Lk_i9:-NGE0ed76j15d08Lk_iA:bmbe3u2) ([raw file](https://github.com/gramineproject/gramine/blob/0814aaae9ceb1930408a074fd8bc6b775795e96c/libos/test/regression/device_ioctl.manifest.template#L50)):*
> ```
> ]
> 
> sgx.allowed_ioctls = [
> ```

Nice, this is both cleaner and more concise!
___
*[`pal/include/pal/pal.h` line 874 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQGHGJ2Nnmu62kZ6kY:-NGE2IIh2KVvUaM20Riv:b85m2sd) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/include/pal/pal.h#L874)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Though I was taught to always put comma after `e.g.` and `i.e.`.
</blockquote></details>

I've never heard of such rule, never seen it and just checked a few online dictionaries - nothing used `,`.
___
*[`pal/src/host/linux/pal_devices.c` line 224 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQIRolC_Op4REgqGMk:-NGEUaTf6WGNjkAe7BZU:b-gjmuve) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux/pal_devices.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> No, I was just confused why it returns device-specific return values via `out_ret` but error codes, which can also be device-specific, directly.

Ah, I see your point. You mean that error codes can be also considered as "IOCTL return values", and thus shouldn't have special treatment.

I think this breaks Gramine conventions? Gramine always expects Pal functions to return PAL error codes (and everything less than 0 is considered an error code), so I don't know how to make it better than currently.
</blockquote></details>

My proposed version still kept Gramine conventions. I just wanted to return Linux error values via `out_ret`, i.e. remove assumption that `*out_ret >= 0`. Idk if that's better.
cc @mkow 
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 269 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkOCK431mXFuV1ixPZ:-NGE47DL8cDkDOPsg9Ne:ba0s7vb) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point of overwriting the pointer size? Why should we allow this?
</blockquote></details>

In case we moved this feature to generic code and because in code the change is as simple as changing `8`/`sizeof()` to some variable `meory_region_size` or whatever it's named, which we already have.
I don't care much though so unblocking.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 275 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkPmpvAZrEof-30WPg:-NGE4pp--atppX6dAYrH:bph8sf0) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Or equal
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 282 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkR0JK7VkEZ9XlbqAP:-NGE5LDJE0-z-cp0-Sko:b-9eatjy) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I don't get your comment. When I talk about `pointer sub-regions`, I mean literally the 8-byte memory cell where the address is stored (the pointer value).
</blockquote></details>

`as to point to the copied-out` - I understood this means that the new value - the new pointer - points to untrusted memory (region) which was copied-out.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 299 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkSwuF4WxGh0m4TEMS:-NGE6-Ek2aygidx0q0Q3:b6cooz7) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L299)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></sum [...]

2022-11-07 14:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 19 of 22 files reviewed, 63 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/671#-NGHSM3_CU3yQvsigbpr):*
I will remove `[id]` from `allowed_ioctls` -- they are a TOML array now, not a TOML table.
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NGGDZXr1EsGa0oOjKSm:b-fgjw3j) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
> Btw, you already use "object": `a pointer to a complex nested object passed to the device`

Well, I use it in the context of the `ioctl` system call, as used in the C language. So there I'm only using the word `object` because of the C terminology. After that, I switch to out TOML-manifest terminology where I (hopefully) always use the term `memory region`.

Let @mkow be our tie-breaker :) We have two variants:
1. Current `memory regions` + `memory sub-regions`
2. `structs` + `struct members`

UPDATE: After doing another round of fixes, I'm really into `mem_regions` and `sub_regions` names in the code. I'd vote for using them.
___
*[`Documentation/manifest-syntax.rst` line 767 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFoZeZb7Pumqgf5Xmi0:-NGGCKJ_1Um4jU1BhMEw:b-v8ze4a) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/Documentation/manifest-syntax.rst#L767)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done? Definitely not in the docs (didn't look at the code yet).
</blockquote></details>

Done, oops, forgot about the docs.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NGGEJX94Go0l551DRo7:bbotq0m) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk then. Since we need to use some option somewhere (i.e. defaults won't do), I would say we should have non-pie, but I wont' block.
</blockquote></details>

I'll leave as is, this is an orthogonal issue anyway.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 66 at r6](https://reviewable.io/reviews/gramineproject/gramine/671#-NFimhf04OLIZZtVb7ip:-NGGENQC7mvQ9WWohWzO:b3kpm6d) ([raw file](https://github.com/gramineproject/gramine/blob/59b09b7e0eed69d907f78263cc5d8bd82cb37fab/libos/test/regression/device_ioctl.manifest.template#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Lol, so there was a typo with `s` at the end and it didn't work? :)
</blockquote></details>

Yes :) So it was good that you asked me to test.
___
*[`pal/src/host/linux/pal_devices.c` line 224 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQIRolC_Op4REgqGMk:-NGGEdoK9FWIhHRDfaEc:b-3cpkbz) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux/pal_devices.c#L224)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

My proposed version still kept Gramine conventions. I just wanted to return Linux error values via `out_ret`, i.e. remove assumption that `*out_ret >= 0`. Idk if that's better.
cc @mkow 
</blockquote></details>

Yes, I'm neutral on this. I can do both ways. Let's wait for Michal.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 269 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkOCK431mXFuV1ixPZ:-NGGEoiT5Jg8ZyEGFzJS:b-1a04zy) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L269)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In case we moved this feature to generic code and because in code the change is as simple as changing `8`/`sizeof()` to some variable `meory_region_size` or whatever it's named, which we already have.
I don't care much though so unblocking.
</blockquote></details>

I still feel like it's shooting ourselves in the foot. Currently I error out with a loud error message when I see `{ ptr = ..., size = ...}`.

If we allow `{ ptr = ..., size = 5}`, then it will sometimes work (when addr value fits into 5 bytes), and sometimes not, so good luck debugging such bloopers...
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 275 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkPmpvAZrEof-30WPg:-NGGJAtc2HHA1c4euBWw:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L275)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or equal
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 282 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkR0JK7VkEZ9XlbqAP:-NGGJT140F3b2bfFJ_-p:b-bv3h5d) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L282)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`as to point to the copied-out` - I understood this means that the new value - the new pointer - points to untrusted memory (region) which was copied-out.
</blockquote></details>

Done. I see, you didn't like that I only talk about `copied-out` and not talking about `copied-in` (both are possible of course). I replaced with `corresponding`, to avoid this under-specification.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 299 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkSwuF4WxGh0m4TEMS:-NGGJdch5O6Bj4ft3_ut:b-9m78ap) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L299)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It was never described anywhere that there are any "default values", so I assumed (and I guess everyone would) that they are undefined.
</blockquote></details>

Yeah, the default values are purely because `untrusted_mmap()` returns all-zeroed memory region.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NGGKozs7kWLNZuyf4t5:bmkomsv) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `size_t`?
</blockquote></details>

I wasn't sure because we update it in the code like this: `size = size * unit + adjust`. So we're mixing types, and I'm unsure what's the best way of handling this. Anyway, currently changed to `size_t`, but what should be the type of `unit` and `adjust` then? Is it normal to keep them as is?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 346 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUnYhD2czvXSXYE4A:-NGGLL6eDNxoxuZdf2zB:b-4lgjto) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L346)):*
<details><summary><i>Previously, [...]

2022-11-07 23:12 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NGINiCQAJBhrtx0UM3k:b-u0kfjm) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wasn't sure because we update it in the code like this: `size = size * unit + adjust`. So we're mixing types, and I'm unsure what's the best way of handling this. Anyway, currently changed to `size_t`, but what should be the type of `unit` and `adjust` then? Is it normal to keep them as is?
</blockquote></details>

IMO `unit` should be `size_t` and `adjust` either `off_t` (or some other offset type) or `int64_t` or just `long`
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGJHESnElXglJdDwoyO:b-in7rz6) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we never have such cross-referenced `struct A` and `struct B` in the manifest (see my other comment). So technically `IOCTL struct's root memory layout` can only refer to a single point.

Anyway, I currently changed `"this"` to `"root"`.
</blockquote></details>

So in what cases we need this special case of `root`? Why cant we just name the very first entry and use that name (making sure it's unique across whole nested object)?
Also if we leave this `root`, we should state somewhere that you cannot name any field like that, i.e. that name is reserved.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 568 at r8](https://reviewable.io/reviews/gramineproject/gramine/671#-NGEbsZ71DEaoTCH-MZb:-NGJDMpREeffReGu3Nov:bcx6ja6) ([raw file](https://github.com/gramineproject/gramine/blob/0814aaae9ceb1930408a074fd8bc6b775795e96c/pal/src/host/linux-sgx/pal_devices.c#L568)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Added to the top level comment, to the description of the `size` keyword.

But I think you incorrectly assumed here that **only the current memory region is searched**. That's why you only mentioned `flexible array members`. In fact, also other cases are supported (where the size is declared in another, outer memory region). See my example in other comment.
</blockquote></details>

Ah, forgot this feature also works for normal pointers.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 765 at r8](https://reviewable.io/reviews/gramineproject/gramine/671#-NGEmaBsE4_RZLlmHqbp:-NGJIW-U7vw96r19h8JN:b80q4mv) ([raw file](https://github.com/gramineproject/gramine/blob/0814aaae9ceb1930408a074fd8bc6b775795e96c/pal/src/host/linux-sgx/pal_devices.c#L765)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Alignment is used when allocating *untrusted memory regions*. The *in-enclave memory regions* are already considered aligned.

Or do you want me to add a check to verify that the in-enclave memory region is correctly aligned (when we found `align` keyword)?
</blockquote></details>

Nah, its' fine
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 283 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGJEMKfB9VW4KScmSRR:-NGJEMKfB9VW4KScmSRS:b7m8miu) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L283)):*
> ```C
>  *     can be flexible-size (like the two strings). In the latter case, the `size` field contains a
>  *     name of a sub-region where the actual size is stored. Note that this referenced sub-region
>  *     must come *before* the sub-region with such flexible-size `size`.
> ```

Would be good to add a comment why is this always possible.
Also does it mean it's impossible to use struct like:
```
struct obj {
    char* data;
    struct metadata {
        size_t size;
        size_t alignment;
        size_t features_bitmap_len;
        uint8_t features_bitmap[];
    }* metadata;
};
```
?
This is a bit convoluted example though.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 596 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGIUkL07EOOynpDvOg_:-NGIUkL07EOOynpDvOga:bmkitq5) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L596)):*
> ```C
>     mem_regions_cnt++;
> 
>     /* collecting memory regions and their sub-regions must use breadth-first search to dynamically
> ```

Please also add the search must be top-to-bottom


<!-- Sent from Reviewable.io -->

2022-11-08 08:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 21 of 22 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NGLPC8rApjKichOmndg:byf6h32) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

IMO `unit` should be `size_t` and `adjust` either `off_t` (or some other offset type) or `int64_t` or just `long`
</blockquote></details>

Done. Changed to `size_t unit`, but kept `int64_t adjust`.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGLPxdH717DtX8LNtV7:bsnxnm8) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So in what cases we need this special case of `root`? Why cant we just name the very first entry and use that name (making sure it's unique across whole nested object)?
Also if we leave this `root`, we should state somewhere that you cannot name any field like that, i.e. that name is reserved.
</blockquote></details>

https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/libos/test/regression/device_ioctl.manifest.template#L44-L48

We can't name the first entry (by which I guess you mean the very first sub-region? In the example case, `{ size = 1, unit = 2, direction = "out" }`). Because the first entry is **not** a pointer sub-region.

What we could do is to use the name of the IOCTL struct itself instead of hard-coded `root`. In the example case, the name will be `gramine_test_dev_ioctl_replace_list`. I can change to this if you want to.

UPDATE: Added checks that `root` is the reserved name, and sub-regions cannot use this name.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 283 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGJEMKfB9VW4KScmSRR:-NGLOMBvCNSrtoSs8jhP:b3y7k1j) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L283)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Would be good to add a comment why is this always possible.
Also does it mean it's impossible to use struct like:
```
struct obj {
    char* data;
    struct metadata {
        size_t size;
        size_t alignment;
        size_t features_bitmap_len;
        uint8_t features_bitmap[];
    }* metadata;
};
```
?
This is a bit convoluted example though.
</blockquote></details>

Done.

Yes, you are right, this struct will not be possible (if we're talking about `metadata::size` being the size specifier for `data` buffer). In my experiments (and like generally, in life) I haven't seen such structs.

If we'll ever face this struct, we'll need to add a second pass to the `size` field, similarly to how we do it with `array_len`. But I don't want to do it without necessity.

Do you want me to add your example and the explanation that it **doesn't work** somewhere in this top-level comment?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 596 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGIUkL07EOOynpDvOg_:-NGLPUzg0OsJ6Eoq4d5R:b-z5ogdd) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L596)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also add the search must be top-to-bottom
</blockquote></details>

Done. I added though I don't understand what exactly you mean by this :) Could you elaborate a bit? Google doesn't know what "top to bottom search" is.


<!-- Sent from Reviewable.io -->

2022-11-08 17:16 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NGNCyKW9-OJBQUEvlW5:b-ec8tma) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Changed to `size_t unit`, but kept `int64_t adjust`.
</blockquote></details>

What about `align`?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGNE0Hp59dBI0srGOoI:b-b6fa2t) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/libos/test/regression/device_ioctl.manifest.template#L44-L48

We can't name the first entry (by which I guess you mean the very first sub-region? In the example case, `{ size = 1, unit = 2, direction = "out" }`). Because the first entry is **not** a pointer sub-region.

What we could do is to use the name of the IOCTL struct itself instead of hard-coded `root`. In the example case, the name will be `gramine_test_dev_ioctl_replace_list`. I can change to this if you want to.

UPDATE: Added checks that `root` is the reserved name, and sub-regions cannot use this name.
</blockquote></details>

Why can't we? Docs say:
```
 ``name`` is an optional name for this sub-region; mainly used to find
  length-specifying fields and nested memory regions.
```
1) It doesn't specify `name` is only usable with `ptr` entries.
2) It even says "mainly", which indicates there are other usages.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 283 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGJEMKfB9VW4KScmSRR:-NGNCGXJ9b89RDwzxtGG:b2nhknk) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L283)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Yes, you are right, this struct will not be possible (if we're talking about `metadata::size` being the size specifier for `data` buffer). In my experiments (and like generally, in life) I haven't seen such structs.

If we'll ever face this struct, we'll need to add a second pass to the `size` field, similarly to how we do it with `array_len`. But I don't want to do it without necessity.

Do you want me to add your example and the explanation that it **doesn't work** somewhere in this top-level comment?
</blockquote></details>

Nah
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 596 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGIUkL07EOOynpDvOg_:-NGNDKqZ300DxGUUsoHl:bgjt149) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L596)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I added though I don't understand what exactly you mean by this :) Could you elaborate a bit? Google doesn't know what "top to bottom search" is.
</blockquote></details>

Well, if you look at TOML representation of a region, you scan it top-to-bottom :) Though now I think of this, it's the docs that are imprecise (that len must come before the buffer it's length it describes) and this assumption is not needed? I.e. reversing the search would still work, wouldn't it (i.e. from last sub-region to first)?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGNCLLL8F0HFhLTYHHJ:bt69l7a) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
> ```C
>  *     always put the size specifier before the buffer, either in the same memory region (e.g. as in
>  *     flexible array members in C) or in the "outer" memory region (e.g. a header struct with the
>  *     size specifier is the root memory region and the buffer is the nested memory region).
> ```

That's not exactly true. This is a valid example:
```
struct A {
    char* data;
    size_t len;
};
```
but it is supported - `data` becomes a `ptr` entry, with it's own `{ }` scope (TOML map), which is nested to `len`, so everything works.
BTW, this is why I didn't insist of changing the workings of this feature - because such example still work, only some more convoluted do not.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 410 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNDE4a3i_eiIIgjIry:-NGNDE4a3i_eiIIgjIrz:b-ddephd) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L410)):*
> ```C
> 
>     if (*out_name && strcmp(*out_name, "root") == 0) {
>         log_error("IOCTL: memory sub-region cannot use name 'root' (it is reserved)");
> ```

`free(*out_name);` missing.


<!-- Sent from Reviewable.io -->

2022-11-09 09:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 21 of 22 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkUMdOEAIojtse4lT1:-NGQjVyY2ks-NVtZnXtV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L335)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about `align`?
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGQlxua-Sd7-RQHkVid:b-j4jrug) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why can't we? Docs say:
```
 ``name`` is an optional name for this sub-region; mainly used to find
  length-specifying fields and nested memory regions.
```
1) It doesn't specify `name` is only usable with `ptr` entries.
2) It even says "mainly", which indicates there are other usages.
</blockquote></details>

I mean of course we can name the first sub-region. Names can be used for any sub-region, no limitations here (though names are only useful for size/array len fields).

But orthogonal to this, what do you propose? I don't get it. Let's take our example:
```
sgx.ioctl_structs.gramine_test_dev_ioctl_replace_list = [ 
     { name = "use-me-please", size = 1, unit = 2, direction = "out" },  # src, dst; `unit` is just for testing 
     { size = 3, adjust = 3, direction = "none" },                       # 6-byte pad; `adjust` is just for testing 
     { ptr = "use-me-please" },                                          # next 
 ] 
```

How does naming of the first sub-region help? It just makes pointer point to the first sub-region, which is... not understable? Pointer should always point to the memory region, not sub-region.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 596 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGIUkL07EOOynpDvOg_:-NGQjl4a76AACiPcXvYk:b-pqvu99) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L596)):*
> that len must come before the buffer it's length it describes

Looks like we again have a problem with terminology. What do you imply by "len must come before the buffer"?

If we talk in terms of our TOML syntax, then `len` sub-region must be one of these:
1. Come in the same memory region as `buf` *and* before the `buf` sub-region (top-to-bottom).
2. Come in another memory region -- in an *outer* memory region. This is guaranteed by the BFS.

Actually, I think now I understand what you meant by `top-to-bottom breadth-first`.

>  the docs that are imprecise

Which parts exactly? I tried to be quite specific in the comments in this file. And in the ReadTheDocs, I don't mention this requirement at all.

> reversing the search would still work, wouldn't it (i.e. from last sub-region to first)?

I assume you mean searching through sub-regions inside the same memory region? No, we cannot reverse the search -- sub-regions are identified and parsed on the fly, so if `buf` sub-region comes before `len` sub-region, then the search during `buf` size resolution will not find the `len` sub-region. (But also this example is meaningless because nobody writes C structs like this.)

What we can do (and do for `array_len`) is to delay the resolution of `array_len` until all sub-regions inside the same memory region are collected. This is meaningful because array length *after* array itself happens in C structs.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGQiSRR586evkaiLzRM:b-of88l1) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
Yes, your example and your understanding is correct. But this is also what I'm trying to explain the text here:

> ... real-world IOCTL structs always put the size specifier before the buffer, ... in the "outer" memory region (e.g. a header struct with the size specifier is the root memory region and the buffer is the nested memory region).

Here I call `struct A` with its `len` sub-region as the "outer" memory region (the "header struct", and `len` is inthe root memory region). Whereas `data` is in the inner memory region (nested memory region). So we're talking about the exact same scenario.

What is the problem in my description? Maybe it's the phrase `header struct`? If yes, I can rephrase to this:

> (e.g. the size specifier is located in the root memory region and the buffer is located in the nested memory region).
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 410 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNDE4a3i_eiIIgjIry:-NGQjetSCL3LvNtkKZ4n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L410)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`free(*out_name);` missing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-09 11:48 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRCVaoDwFgMmqA5mkw:b4026ma) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> Pointer should always point to the memory region, not sub-region.

How they can point to memory regions, if that's explicitly disallowed by the rules (i.e. that only subregion can have a name)? Like in nested case, you have to put the name of the first subregion, that's the only way. How that differs from the above example? I don't understand.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 596 at r9](https://reviewable.io/reviews/gramineproject/gramine/671#-NGIUkL07EOOynpDvOg_:-NGRBj210xgrriw5OG5D:bltchlw) ([raw file](https://github.com/gramineproject/gramine/blob/d01bbe623273530ba1aa694f3693e1f09a354460/pal/src/host/linux-sgx/pal_devices.c#L596)):*
> What do you imply by "len must come before the buffer"?

See the discussion above (top comment in this file)

> Which parts exactly? 

Sorry, meant the comment in code above, not RST.

TBH I got lost in this discussion, resolving, nothing super important anyway.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGRA0YG89hJcUHws2Ev:blwkudl) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, your example and your understanding is correct. But this is also what I'm trying to explain the text here:

> ... real-world IOCTL structs always put the size specifier before the buffer, ... in the "outer" memory region (e.g. a header struct with the size specifier is the root memory region and the buffer is the nested memory region).

Here I call `struct A` with its `len` sub-region as the "outer" memory region (the "header struct", and `len` is inthe root memory region). Whereas `data` is in the inner memory region (nested memory region). So we're talking about the exact same scenario.

What is the problem in my description? Maybe it's the phrase `header struct`? If yes, I can rephrase to this:

> (e.g. the size specifier is located in the root memory region and the buffer is located in the nested memory region).
</blockquote></details>

The problem is that you state: `real-world IOCTL structs always put the size specifier before the buffer`, which is not true. Also this whole text sounds like there is a 1-1 correspondence between mem-subregion and struct member (and there is not, e.g. `ptr` entries).


<!-- Sent from Reviewable.io -->

2022-11-09 12:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRGozG21tPxp5-lY3T:b-r8fpbe) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> How they can point to memory regions, if that's explicitly disallowed by the rules (i.e. that only subregion can have a name)?

Yes, ok, my wording was sloppy. The actual rule is like this:
1. `ptr` may point to the memory region via the inline TOML-table syntax (` { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" }`)
2. or `ptr` may point to another pointer which in turn points to the memory region (` { ptr = "ptr1", name = "ptr2" }`)

(In the example above, `"ptr2"` name is useless, just to make it more explicit that we have two C struct fields, one is `ptr1` another is `ptr2`.)

> Like in nested case, you have to put the name of the first subregion, that's the only way.

No, that's not how it is done in this PR. We put the name of the **pointer sub-region that points to a memory region**.

So to summarize, here is the example with two pointers pointing to objects with the same memory layout:
```
sgx.ioctl_structs.blabla = [
    { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" },
    { ptr = "ptr1", name = "ptr2" }
]
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGRGcIWAktBZ0ZlvhuG:b5o3z33) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is that you state: `real-world IOCTL structs always put the size specifier before the buffer`, which is not true. Also this whole text sounds like there is a 1-1 correspondence between mem-subregion and struct member (and there is not, e.g. `ptr` entries).
</blockquote></details>

Done. What about now?


<!-- Sent from Reviewable.io -->

2022-11-09 12:23 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRL2d7EpUX8tHS9Dnn:b66jizg) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> How they can point to memory regions, if that's explicitly disallowed by the rules (i.e. that only subregion can have a name)?

Yes, ok, my wording was sloppy. The actual rule is like this:
1. `ptr` may point to the memory region via the inline TOML-table syntax (` { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" }`)
2. or `ptr` may point to another pointer which in turn points to the memory region (` { ptr = "ptr1", name = "ptr2" }`)

(In the example above, `"ptr2"` name is useless, just to make it more explicit that we have two C struct fields, one is `ptr1` another is `ptr2`.)

> Like in nested case, you have to put the name of the first subregion, that's the only way.

No, that's not how it is done in this PR. We put the name of the **pointer sub-region that points to a memory region**.

So to summarize, here is the example with two pointers pointing to objects with the same memory layout:
```
sgx.ioctl_structs.blabla = [
    { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" },
    { ptr = "ptr1", name = "ptr2" }
]
```
</blockquote></details>

I'm completely lost. Can you provide a C struct and manifest description of that struct (TOML like above)?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGRKzmwDHtSSHHZLD7n:bxw02r7) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. What about now?
</blockquote></details>

What about a push? :)


<!-- Sent from Reviewable.io -->

2022-11-09 12:32 UTC, dimakuv commented
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRM7nEEwjK2bSDHp3W:bs803vt) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm completely lost. Can you provide a C struct and manifest description of that struct (TOML like above)?
</blockquote></details>

In C:
```c
struct sub { /* contents are irrelevant */
    int x;
    int y;
};

struct blabla {
    struct sub* ptr1;
    struct sub* ptr2;
}
```

Corresponding TOML struct:
```
sgx.ioctl_structs.blabla = [
    { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" },
    { ptr = "ptr1", name = "ptr2" }
]
```


<!-- Sent from Reviewable.io -->

2022-11-09 12:35 UTC, dimakuv commented
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRN5eT2H_W718Htae3:b-82qk9z) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In C:
```c
struct sub { /* contents are irrelevant */
    int x;
    int y;
};

struct blabla {
    struct sub* ptr1;
    struct sub* ptr2;
}
```

Corresponding TOML struct:
```
sgx.ioctl_structs.blabla = [
    { ptr = [ {subregion1}, {subregion2} ], name = "ptr1" },
    { ptr = "ptr1", name = "ptr2" }
]
```
</blockquote></details>

Well, ok, you may wonder why we're even doing this indirection. Let me show you the concrete example why I had to introduce this.

In C, we have a `drm_i915_gem_context_param`:
- https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/i915_drm.h#L1927
- https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/i915_drm.h#L102

Corresponding TOML struct (removed some fluff, we only care about `extension_block`):
```
sgx.ioctl_structs.drm_i915_gem_context_param = [
    {size=4, type="out"}, # ctx_id
    {size=4, type="inout", name="size"},
    {size=8, type="out", name="param"},
    ...
    {onlyif="param == 0xa", ptr=[                  # value I915_CONTEXT_PARAM_ENGINES
         {name="extension_block", ptr=[
             # common header struct i915_user_extension (base field)
             {ptr="extension_block"}, # next_extension
             {name="extension_name", size=4, type="out"},
             {size=4, type="out"}, # extension_flags
             {size=4, unit=4, type="out"}, # extension_rsvd2
             ...
         ]},
         ...
       ] },
]
```


<!-- Sent from Reviewable.io -->

2022-11-09 12:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 21 of 22 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 286 at r10](https://reviewable.io/reviews/gramineproject/gramine/671#-NGNCLLK9lZI6729B3A9:-NGRM3ly6uLXl42yjhJ1:b-q023xu) ([raw file](https://github.com/gramineproject/gramine/blob/1db6cd92bcfb1f2819789802f5be4af1c05cef42/pal/src/host/linux-sgx/pal_devices.c#L286)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What about a push? :)
</blockquote></details>

Done, lol


<!-- Sent from Reviewable.io -->

2022-11-09 12:47 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRPG5BDKzJP_kOmPFI:be707s1) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, ok, you may wonder why we're even doing this indirection. Let me show you the concrete example why I had to introduce this.

In C, we have a `drm_i915_gem_context_param`:
- https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/i915_drm.h#L1927
- https://elixir.bootlin.com/linux/latest/source/include/uapi/drm/i915_drm.h#L102

Corresponding TOML struct (removed some fluff, we only care about `extension_block`):
```
sgx.ioctl_structs.drm_i915_gem_context_param = [
    {size=4, type="out"}, # ctx_id
    {size=4, type="inout", name="size"},
    {size=8, type="out", name="param"},
    ...
    {onlyif="param == 0xa", ptr=[                  # value I915_CONTEXT_PARAM_ENGINES
         {name="extension_block", ptr=[
             # common header struct i915_user_extension (base field)
             {ptr="extension_block"}, # next_extension
             {name="extension_name", size=4, type="out"},
             {size=4, type="out"}, # extension_flags
             {size=4, unit=4, type="out"}, # extension_rsvd2
             ...
         ]},
         ...
       ] },
]
```
</blockquote></details>

Why can't we have `sgx_ioctl_structs.blabla_extension_block = [ TOML describint C struct here ]` and then refer that by `name="blabla_extension_block"`?
To me the current solution is a bit nonsensical. We refer to a type via name of another variable (sub-region), which has the same type... Why can't we just refer to the name directly? That could be named `type="struct_type"`, not to confuse with scenarios like referring to a filed with size (where `name=...` could be still used). Note that in your example `type` is what we call `direction` now, so name clashes here.


<!-- Sent from Reviewable.io -->

2022-11-09 12:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRR_H74cSm5IKUPlrW:bbh6ajk) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why can't we have `sgx_ioctl_structs.blabla_extension_block = [ TOML describint C struct here ]` and then refer that by `name="blabla_extension_block"`?
To me the current solution is a bit nonsensical. We refer to a type via name of another variable (sub-region), which has the same type... Why can't we just refer to the name directly? That could be named `type="struct_type"`, not to confuse with scenarios like referring to a filed with size (where `name=...` could be still used). Note that in your example `type` is what we call `direction` now, so name clashes here.
</blockquote></details>

I wanted to have each IOCTL struct to be completely self-defined. But we could change it if people find my current solution unintuitive.

So what you want is smth like this, closer to how structs are declared in C, right?
```
sgx.ioctl_structs.extension_block = [
    { whatever 1 },
    { whatever 2 },
]

sgx.ioctl_structs.drm_i915_gem_context_param = [
    {size=4, type="out"}, # ctx_id
    {size=4, type="inout", name="size"},
    {size=8, type="out", name="param"},
    ...
    {onlyif="param == 0xa", ptr=[                  # value I915_CONTEXT_PARAM_ENGINES
         { ptr="extension_block" }
         },
         ...
       ] },
]
```

Or in my simpler example, it will look like this:
```
sgx.ioctl_structs.sub = [
    {size=4, type="out"}, # x
    {size=4, type="out"}, # y
]

sgx.ioctl_structs.blabla = [
    { ptr = "sub" },
    { ptr = "sub" }
]
```

Do I understand correctly? I can do it, I now also think that it has less complexity.

Btw, I don't need any kind of `type` keyword in my new examples. Why?


<!-- Sent from Reviewable.io -->

2022-11-09 13:13 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRUYok9KSLILLCVYi3:b-a9vc6q) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> Do I understand correctly? I can do it, I now also think that it has less complexity.

Yes, but please think about all corner cases, so that it doesn't turn out that it has different problems.
Also are there cases like:
```
struct A {
    int x;
    char* ptr; // Always points somewhere into buf, must be updated when copying in to or out of the enclave
    char buf[0x100];
};
```
?

> Btw, I don't need any kind of type keyword in my new examples. Why?

```
    #    here  V
    {size=4, type="out"}, # ctx_id
```


<!-- Sent from Reviewable.io -->

2022-11-09 13:20 UTC, dimakuv commented
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRXdGY93rWDEjLo31g:b-yedap5) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Do I understand correctly? I can do it, I now also think that it has less complexity.

Yes, but please think about all corner cases, so that it doesn't turn out that it has different problems.
Also are there cases like:
```
struct A {
    int x;
    char* ptr; // Always points somewhere into buf, must be updated when copying in to or out of the enclave
    char buf[0x100];
};
```
?

> Btw, I don't need any kind of type keyword in my new examples. Why?

```
    #    here  V
    {size=4, type="out"}, # ctx_id
```
</blockquote></details>

```
struct A {
    int x;
    char* ptr; // Always points somewhere into buf, must be updated when copying in to or out of the enclave
    char buf[0x100];
};
```
->
```
sgx.ioctl_structs.A = [
    { size = 4, direction = "inout" },      # x
    { size = 8, direction = "inout" },      # ptr
    { size = 0x100, direction = "inout" },  # buf
]
```

Is that what you're asking about?


<!-- Sent from Reviewable.io -->

2022-11-09 13:21 UTC, dimakuv commented
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRYA5_4YeYvqO1dHYS:b-230s5u) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
struct A {
    int x;
    char* ptr; // Always points somewhere into buf, must be updated when copying in to or out of the enclave
    char buf[0x100];
};
```
->
```
sgx.ioctl_structs.A = [
    { size = 4, direction = "inout" },      # x
    { size = 8, direction = "inout" },      # ptr
    { size = 0x100, direction = "inout" },  # buf
]
```

Is that what you're asking about?
</blockquote></details>

I still don't understand you original remark about `type` for pointer sub-regions. I don't think this `type` keyword is needed at all.


<!-- Sent from Reviewable.io -->

2022-11-09 13:42 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRbdmb1QNmTvEPVjRL:b3ke7js) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> Is that what you're asking about?

No, if you do it like that, `ptr` will point into original in enclave memory. But I guess this example is not really needed, nothing would use such weird convention. Circular buffers for example, would probably be implemented with indices.

> I still don't understand you original remark about type for pointer sub-regions. I don't think this type keyword is needed at all.

Doesn't matter. `ptr = "type_name"` is ok


<!-- Sent from Reviewable.io -->

2022-11-09 13:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 19 of 22 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 507 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFpgkTKC_YL6ywXlAkM:-NGRfu_n3xWixx6AQVzo:bje409l) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L507)):*
> No, if you do it like that, `ptr` will point into original in enclave memory. But I guess this example is not really needed, nothing would use such weird convention. Circular buffers for example, would probably be implemented with indices.

Ah, you're right! Yes, this case is unsupported. All IOCTLs (DRM ones) that I've seen always use either an `index` or an `offset`.

Also, the `ptr = "ioctl_struct_name"` is done now. I don't see any corner cases.


<!-- Sent from Reviewable.io -->

2022-11-09 15:35 UTC, boryspoplawski reviewed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-11-10 14:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux/pal_devices.c` line 224 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQIRolC_Op4REgqGMk:-NGWrl4a9Q96bLu92xZk:bgigyme) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux/pal_devices.c#L224)):*
> @boryspoplawski: But what do you propose to return from the function? You didn't include this part in the snippet.

Wdym? PAL API functions have a pretty well defined return values, so it would conform to that, i.e. return `0` on success and `-PAL_ERROR` on failures. Note these statuses would reflect only code in PAL, i.e. not `ioctl` itself (like argument validation etc).


<!-- Sent from Reviewable.io -->

2023-02-10 11:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NNuzGrZ5Ebp_cyVyowc:-NNuzGrZ5Ebp_cyVyowd:bs7i3yx) (no related file):*
By the way, an interesting consequence of current `dev` files implementation in Gramine.

We typically write like this (see example in this PR), to enable a device inside Gramine:
```
fs.mounts = [
  { path = "/dev/gramine_test_dev", uri = "dev:/dev/gramine_test_dev" },
]
```

Sometimes, however, the device name is not known in advance (some devices like to have suffixes like `/dev/tty42`), and this name differs from one machine to the other. Currently, Gramine's FS code doesn't allow to open *any* device; the device name must be hard-coded in the manifest as above.

I am not sure we want to change this behavior... I see one workaround for such a problem: request Gramine deployers to prepare their machines -- to create symlinks from the actual device name to the hard-coded name in the manifest. E.g. the deployers must perform smth like `ln -s /dev/actual_device_name_42 /dev/gramine_test_dev` on each machine.

___


<!-- Sent from Reviewable.io -->

2023-04-24 07:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 6 of 22 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NEG7wsR8eWMGta1p4Og:-NTm2Jie5zob4YCv7Aiv:btn2m48) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Ping.
</blockquote></details>

This was done and requires merging of these PRs:
- https://github.com/gramineproject/gramine/pull/1032
- https://github.com/gramineproject/device-testing-tools/pull/7

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NF8Okp8-L2J9deeqoM6:-NTm28MG2o9E_fYmyQ4k:b-hx3hr8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR depends on https://github.com/gramineproject/gramine/pull/995. Otherwise Jenkins fails (see the explanation here: https://github.com/gramineproject/gramine/issues/990)
</blockquote></details>

Done. #995 was merged long time ago.

___
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEllQ-YBSlrgincyjMq):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during the final rebase.
</blockquote></details>

Done
___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NElh9X15DY3CnHHBEr9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow What about this improved text.

```
  The newly added `ioctl()` syscall emulation on device-backed file
  descriptors is pass-through. It is insecure by itself since the
  emulation only passes the arguments to and from the untrusted memory:
    - ioctl arguments are passed as-is from the app to the untrusted host,
      which may lead to leaks of secret data;
    - untrusted host can change ioctl arguments as it wishes when passing
      them from Gramine to the device and back.

  It is the responsibility of the app developer to correctly use ioctls,
  with security implications in mind. In most cases, ioctl arguments should
  be encrypted or integrity-protected with a key pre-shared between
  Gramine and the device.
```
</blockquote></details>

Done
___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/gramineproject/gramine/671#-NFD_ppO7HJ2ikIKb9-e):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll need to change to `request_code`
</blockquote></details>

Done. I didn't go into details of specific fields in `sgx.allowed_ioctls` items.
___
*[`-- commits` line 15 at r8](https://reviewable.io/reviews/gramineproject/gramine/671#-NGHSM3_CU3yQvsigbpr):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will remove `[id]` from `allowed_ioctls` -- they are a TOML array now, not a TOML table.
</blockquote></details>

Done
___
*[`libos/test/regression/device_ioctl.manifest.template` line 13 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFP1bhbASr8pdcMgG9P:-NTm7u9a9AoLqpBiSF6Y:b-wmmdxv) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/libos/test/regression/device_ioctl.manifest.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll leave as is, this is an orthogonal issue anyway.
</blockquote></details>

UPDATE: this was removed on the rebase, since this `sgx.nonpie_binary` option was removed from Gramine completely.
___
*[`libos/test/regression/device_ioctl.manifest.template` line 4 at r13](https://reviewable.io/reviews/gramineproject/gramine/671#-NTm7zVyEUbV212HxDjz:-NTm7zVyEUbV212HxDk-:bnkm2ku) ([raw file](https://github.com/gramineproject/gramine/blob/0e9532f1dfb13fcc230b5355eae22c8f37563177/libos/test/regression/device_ioctl.manifest.template#L4)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> 
> loader.argv0_override = "{{ entrypoint }}"
> ```

UPDATE: this was removed on the rebase, since this `loader.argv0_override` option was removed from Gramine completely.
___
*[`pal/src/host/linux-sgx/enclave_ocalls.c` line 1993 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQJJ1Z1s8JxhgnnwnL:-NTm7fsq0Ux4x8vo0iZT:bb6un1j) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux-sgx/enclave_ocalls.c#L1993)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. Blocked myself.
</blockquote></details>

Done
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 748 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkwqlT0uxiN2_ph2Vh:-NTmAsh0-Gw3UWewiNhu:bgkiczx) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L748)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

UPDATE: Using `sgx_copy_from_enclave()` now
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 766 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkxs_dCuITn7Fle51b:-NTmAqFs2-ugf6irT6if:bgkiczx) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L766)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

UPDATE: Using `sgx_copy_from_enclave()` now
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 852 at r13](https://reviewable.io/reviews/gramineproject/gramine/671#-NTmAv-V5xUOm6jonBgx:-NTmAv-V5xUOm6jonBgy:b-d5rhgc) ([raw file](https://github.com/gramineproject/gramine/blob/0e9532f1dfb13fcc230b5355eae22c8f37563177/pal/src/host/linux-sgx/pal_devices.c#L852)):*
> ```C
>         if (sub_regions[i].direction == DIRECTION_IN
>                 || sub_regions[i].direction == DIRECTION_INOUT) {
>             bool ret = sgx_copy_to_enclave(sub_regions[i].enclave_addr, sub_regions[i].size,
> ```

NOTE: we already used the protected version of the copy-to-enclave function, so no changed were required here.


<!-- Sent from Reviewable.io -->

2023-04-24 09:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 6 of 22 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NEG7wsR8eWMGta1p4Og:-NTmXqEA6jBcXdSnOMFi:b-c60ytk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was done and requires merging of these PRs:
- https://github.com/gramineproject/gramine/pull/1032
- https://github.com/gramineproject/device-testing-tools/pull/7
</blockquote></details>

This current PR requires #1032 to be merged first (so that our CI passes without failures). Blocking on this.

@mkow Please note that you'll need to review #1032 also, otherwise this PR can't survive our Jenkins.

___


<!-- Sent from Reviewable.io -->

2023-05-04 12:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 4 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NEG7wsR8eWMGta1p4Og:-NUakJM91KqybGIejTHn:b-uu28cd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This current PR requires #1032 to be merged first (so that our CI passes without failures). Blocking on this.

@mkow Please note that you'll need to review #1032 also, otherwise this PR can't survive our Jenkins.
</blockquote></details>

Done. PR #1032 was merged, and I rebased this PR on top.

___


<!-- Sent from Reviewable.io -->

2023-05-04 12:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 4 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NUaoK1E7M6ZVC8uVfY9:-NUaoK1F3pA_3ZP1AnlX:b-56yxjf) (no related file):*
FYI: I verified manually that Jenkins correctly runs the `device_ioctl` test. This PR is not a draft anymore, and can be reviewed.

___


<!-- Sent from Reviewable.io -->

2023-05-04 14:22 UTC, dimakuv commented
Jenkins, retest Docs please (networking issues)

2023-05-04 14:23 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (networking issues)

2023-05-04 14:24 UTC, dimakuv commented
Jenkins, retest Jenkins-Direct-Sanitizers please (networking issues)

2023-05-04 14:35 UTC, dimakuv commented
Jenkins, retest Docs please (networking issues)

2023-05-04 14:35 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (networking issues)

2023-05-05 13:03 UTC, dimakuv commented
Jenkins, retest check-python-platlib please (networking issues from yesterday)

2023-05-05 13:03 UTC, dimakuv commented
Jenkins, retest pkg-rpm-almalinux8  please (networking issues from yesterday)

2023-05-08 08:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 4 of 24 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NUuWrY1BWa_dMVvgWbb:-NUuWrY1BWa_dMVvgWbc:b-q0evkh) (no related file):*
At the request of @aneessahib, I'm adding a negative test `dev_ioctl_fail` to our CI. Currently as a fixup commit, WIP...

___
___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUuNnyHE5sJlnmInQJ9):*
TODO: Add a note on a second test (`device_ioctl_fail`) that tests the failure if no allowed IOCTLs.


<!-- Sent from Reviewable.io -->

2023-05-08 12:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 4 of 24 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NUuWrY1BWa_dMVvgWbb:-NUvKLH7BdzaxUzmH1xe:beq0z3w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

At the request of @aneessahib, I'm adding a negative test `dev_ioctl_fail` to our CI. Currently as a fixup commit, WIP...
</blockquote></details>

Ok, I tested that the test works, and that our CI fails if the test fails. I'm rebasing the fixup commits into one fixup, to not have too much noise in this PR.

___


<!-- Sent from Reviewable.io -->

2023-05-10 00:12 UTC, mkow requested changes
> Reviewed 1 of 18 files at r2, 1 of 6 files at r8, 2 of 16 files at r14, 8 of 9 files at r16, 3 of 5 files at r17, 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 16 of 24 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsejSU-TbrXev3xrUw):*
Sounds weird to me, is this a real construct in English? I'd rather say "is located" or "can be found".



_Code quote:_
```
is found in companion repo
```
___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 12 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1qXXD1bBQBsQEaPRk:-NV1qXXD1bBQBsQEaPRl:bpk8n21) ([raw file](https://github.com/gramineproject/gramine/blob/85d0689e135cbded345e5753eb0afe02b974de74/.ci/lib/stage-build-sgx-vm.jenkinsfile#L12)):*
> ```
>         {
>            echo '#!/bin/sh'
>            echo 'if test -n $SGX; then GRAMINE=gramine-sgx; else GRAMINE=gramine-direct; fi'
> ```

Why dropping this? How does it work now?



_Code quote:_
```
echo 'if test -n $SGX; then GRAMINE=gramine-sgx; else GRAMINE=gramine-direct; fi'
```
___
*[`Documentation/manifest-syntax.rst` line 826 at r3](https://reviewable.io/reviews/gramineproject/gramine/671#-NEln7Vw-_Ntm-tt3T2U:-NUsnG_O173Lj3MGC_4K:b-yp1bze) ([raw file](https://github.com/gramineproject/gramine/blob/d3b65ab395d26d6e4293b94a1a09abad0caab464/Documentation/manifest-syntax.rst#L826)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Btw, you already use "object": `a pointer to a complex nested object passed to the device`

Well, I use it in the context of the `ioctl` system call, as used in the C language. So there I'm only using the word `object` because of the C terminology. After that, I switch to out TOML-manifest terminology where I (hopefully) always use the term `memory region`.

Let @mkow be our tie-breaker :) We have two variants:
1. Current `memory regions` + `memory sub-regions`
2. `structs` + `struct members`

UPDATE: After doing another round of fixes, I'm really into `mem_regions` and `sub_regions` names in the code. I'd vote for using them.
</blockquote></details>

I'm fine with `memory regions` + `memory sub-regions`.
___
*[`Documentation/manifest-syntax.rst` line 824 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUshklh3AR0Yzz5ZxUd:-NUshklh3AR0Yzz5ZxUe:b1d1gi6) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L824)):*
> ```reStructuredText
> call (typically a pointer to a complex nested object passed to the device).
> Description of the memory layout is required for a deep copy of the IOCTL
> struct. We use the term *memory region* to denote a separate contiguous region
> ```

(this is only for ioctl passthrough, not the whole Gramine)



_Suggestion:_
```reStructuredText
Here we use the term *memory region*
```
___
*[`Documentation/manifest-syntax.rst` line 839 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslv1M-ASfR_QFwGqS:-NUslv1M-ASfR_QFwGqT:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L839)):*
> ```reStructuredText
> - ``name`` is an optional name for this sub-region; mainly used to find
>   length-specifying fields and nested memory regions.
> - ``align`` is an optional alignment of the memory region; may be specified only
> ```





_Suggestion:_
```reStructuredText
``alignment``
```
___
*[`Documentation/manifest-syntax.rst` line 841 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsidJeA248XNNNApy9:-NUsidJeA248XNNNApyA:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L841)):*
> ```reStructuredText
> - ``align`` is an optional alignment of the memory region; may be specified only
>   in the first sub-region of a memory region (all other sub-regions are
>   contigious with the first sub-region, so specifying their alignment doesn't
> ```





_Suggestion:_
```reStructuredText
contiguous
```
___
*[`Documentation/manifest-syntax.rst` line 849 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsj5H1BjCb8nirhUaT:-NUsj5H1BjCb8nirhUaU:bczk1h8) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L849)):*
> ```reStructuredText
>   that will be calculated dynamically during IOCTL execution based on the
>   sub-region named ``strlen``, whereas ``size = 16`` denotes a sub-region of
>   size 16B. Note that ``ptr`` sub-regions must *not* specify the ``size`` field.
> ```

But at the beginning you say that this field is mandatory?



_Code quote:_
```reStructuredText
Note that ``ptr`` sub-regions must *not* specify the ``size`` field.
```
___
*[`Documentation/manifest-syntax.rst` line 854 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslriAB6KhG9zTfvXU:-NUslriAB6KhG9zTfvXV:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L854)):*
> ```reStructuredText
>   ``size = "strlen"`` and ``unit = 2`` denote a wide-char string (where each
>   character is 2B long) of a dynamically specified length.
> - ``adjust`` is an optional integer adjustment for ``size`` (always specified in
> ```





_Suggestion:_
```reStructuredText
``adjustment``
```
___
*[`Documentation/manifest-syntax.rst` line 861 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsjo0m823CnO-kmt93:-NUsjo0m823CnO-kmt94:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L861)):*
> ```reStructuredText
>   cannot be specified with non-``ptr`` regions.
> - ``direction = "none" | "out" | "in" | "inout"`` is an optional direction of
>   copy for this sub-region. For example, ``direction = "out"`` denotes a
> ```





_Suggestion:_
```reStructuredText
- ``direction = "none" | "out" | "in" | "inout"`` is an optional direction of
  copy for this sub-region (from the app point of view). For example, ``direction = "out"`` denotes a
```
___
*[`Documentation/manifest-syntax.rst` line 871 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsk_ODAh_YYk0osbx_:-NUsk_OEEon3TgJcPF8w:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L871)):*
> ```reStructuredText
>   specifies a pointer to another, nested memory region. This field is required
>   when describing complex IOCTL structs. Such pointer memory region always has
>   the implicit size of 8B, and the pointer value is always rewired to the memory
> ```





_Suggestion:_
```reStructuredText
is always rewired by Gramine
```
___
*[`Documentation/manifest-syntax.rst` line 874 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUskhaA8BUDLj89HcDW:-NUskhaA8BUDLj89HcDX:b-5nmy5n) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L874)):*
> ```reStructuredText
>   region in untrusted memory (containing a corresponding nested memory region).
>   If ``ptr`` is specified together with ``array_len``, it describes an array of
>   these memory regions. (In other words, ``ptr`` is an array of memory regions
> ```

ditto for the parenthesis



_Suggestion:_
```reStructuredText
  If ``ptr`` is specified together with ``array_len [...]

2023-05-10 00:40 UTC, mkow reviewed
> Reviewed 2 of 11 files at r6, 6 of 16 files at r14, 1 of 9 files at r16.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 23 of 24 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`pal/src/host/linux/pal_devices.c` line 224 at r5](https://reviewable.io/reviews/gramineproject/gramine/671#-NFQIRolC_Op4REgqGMk:-NV24OfyEhV9Lzmdz3yh:bagov5a) ([raw file](https://github.com/gramineproject/gramine/blob/1205599d4d1937e7377bc0f3a9a992635b62ae85/pal/src/host/linux/pal_devices.c#L224)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> @boryspoplawski: But what do you propose to return from the function? You didn't include this part in the snippet.

Wdym? PAL API functions have a pretty well defined return values, so it would conform to that, i.e. return `0` on success and `-PAL_ERROR` on failures. Note these statuses would reflect only code in PAL, i.e. not `ioctl` itself (like argument validation etc).
</blockquote></details>

Ok, I think Borys' proposal makes sense if we're actually just passing through the whole syscall.


<!-- Sent from Reviewable.io -->

2023-05-10 08:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 23 of 24 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 12 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1qXXD1bBQBsQEaPRk:-NV3dqN_A1axSA2dnAAp:bb1b2j9) ([raw file](https://github.com/gramineproject/gramine/blob/85d0689e135cbded345e5753eb0afe02b974de74/.ci/lib/stage-build-sgx-vm.jenkinsfile#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why dropping this? How does it work now?
</blockquote></details>

Previously, I just ran the tests using `gramine-direct helloworld`/`gramine-sgx helloworld` and relied on the fact that they return 0 on success. That's why I had this helper variable `GRAMINE`.

Now I'm simply re-using the `gramine-test pytest` functionality to run these tests. I had to do this for two reasons:
1. It is a cleaner approach to run tests then to just run raw binaries.
2. I introduced the new test called `device_ioctl_fail` where the correct result is the **failure** of the test, and that the test prints a specific failure message. This would be hard to verify using simple bash and running a raw binary. So it dictated the use of `gramine-test pytest`.

Now how does `gramine-test pytest` know whether it should run `gramine-direct` or `gramine-sgx`? Well, we propagate the env variable `SGX` into the VM and ultimately into this bash script: https://github.com/gramineproject/gramine/blob/c7fe3f017b9b94fdeb90f84016c006ed7bc683e4/.ci/lib/stage-test-vm.jenkinsfile#L9

Also, `gramine-test` tool itself knows about this `SGX` variable and chooses the correct flows when `SGX=1`: https://github.com/gramineproject/gramine/blob/c7fe3f017b9b94fdeb90f84016c006ed7bc683e4/python/gramine-test#L19
___
*[`libos/test/regression/device_ioctl.c` line 29 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1u66jAegSNJU0b7WH:-NV3fDcx7o52cs-NlUYr:b-ofrdn8) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/device_ioctl.c#L29)):*
> Shouldn't device passthrough make all FD operations also pass through?

Well, that's currently not implemented and that's not the purpose of this PR. But I agree, it would be better to have such a passthrough, though it would require some non-trivial changes to the LibOS FS subsystem.

Do you want me to create a GitHub issue about this?
___
*[`libos/test/regression/test_libos.py` line 1048 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1z4U2Ea11Tq10Bfjz:-NV3fZk1CvZlYtsTEMfs:b-pu7cii) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/test_libos.py#L1048)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not this way? Seems more standard.
</blockquote></details>

I felt that this way would be more readable, but sure.


<!-- Sent from Reviewable.io -->

2023-05-10 12:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 23 of 24 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`.ci/lib/stage-build-sgx-vm.jenkinsfile` line 12 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1qXXD1bBQBsQEaPRk:-NV4cscE5ZXbNqePZLoV:b-1oycbo) ([raw file](https://github.com/gramineproject/gramine/blob/85d0689e135cbded345e5753eb0afe02b974de74/.ci/lib/stage-build-sgx-vm.jenkinsfile#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Previously, I just ran the tests using `gramine-direct helloworld`/`gramine-sgx helloworld` and relied on the fact that they return 0 on success. That's why I had this helper variable `GRAMINE`.

Now I'm simply re-using the `gramine-test pytest` functionality to run these tests. I had to do this for two reasons:
1. It is a cleaner approach to run tests then to just run raw binaries.
2. I introduced the new test called `device_ioctl_fail` where the correct result is the **failure** of the test, and that the test prints a specific failure message. This would be hard to verify using simple bash and running a raw binary. So it dictated the use of `gramine-test pytest`.

Now how does `gramine-test pytest` know whether it should run `gramine-direct` or `gramine-sgx`? Well, we propagate the env variable `SGX` into the VM and ultimately into this bash script: https://github.com/gramineproject/gramine/blob/c7fe3f017b9b94fdeb90f84016c006ed7bc683e4/.ci/lib/stage-test-vm.jenkinsfile#L9

Also, `gramine-test` tool itself knows about this `SGX` variable and chooses the correct flows when `SGX=1`: https://github.com/gramineproject/gramine/blob/c7fe3f017b9b94fdeb90f84016c006ed7bc683e4/python/gramine-test#L19
</blockquote></details>

Ah, didn't know `gramine-test` also respects this env variable.
___
*[`libos/test/regression/device_ioctl.c` line 29 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1u66jAegSNJU0b7WH:-NV4dMLm7rhIriYK8sv0:b-cp77u2) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/device_ioctl.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Shouldn't device passthrough make all FD operations also pass through?

Well, that's currently not implemented and that's not the purpose of this PR. But I agree, it would be better to have such a passthrough, though it would require some non-trivial changes to the LibOS FS subsystem.

Do you want me to create a GitHub issue about this?
</blockquote></details>

If you think it's indeed better then please create an issue + document the limitation in the documentation in this PR.
___
*[`libos/test/regression/test_libos.py` line 1048 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1z4U2Ea11Tq10Bfjz:-NV4dZhO8xqf8MFVlYBT:b-vi0mbj) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/test_libos.py#L1048)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I felt that this way would be more readable, but sure.
</blockquote></details>

I'm used to `\(` and I had to stop and think for a moment when I saw `[(]`.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 228 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV27XQVErgjweMxH9Sa:-NV27XQVErgjweMxH9Sb:b-whty7q) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L228)):*
> ```C
>  * Code below describes the TOML syntax of the manifest entries used for deep-copying complex nested
>  * objects out and inside the SGX enclave. This syntax is currently used for IOCTL emulation. This
>  * syntax is generic enough to describe any memory layout for deep copy of IOCTL structs.
> ```

You can't describe _any_ possible data layout with the current format. Just the most common ones.



_Code quote:_
```C
is generic enough to describe any memory layout for deep copy of IOCTL structs.
```


<!-- Sent from Reviewable.io -->

2023-05-11 23:56 UTC, mkow requested changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 49 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NVCABUZAOA3zXEeIfcQ:-NUdaQaREo5SbEtSik79:bf3wjxu) (no related file):*
@kailun-qin, could you also take a look at this PR? The parsing code is so complex and monotonous that I don't trust my review.

___
___
*[`libos/test/regression/test_libos.py` line 1050 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVC7m-Z6EJPMxIPKqDl:-NVC7m-_3SnjVB7bpgeO:b-b41bqi) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/test_libos.py#L1050)):*
> ```Python
>             self.assertRegex(stdout, r'ioctl[(]devfd, GRAMINE_TEST_DEV_IOCTL_REWIND[)].*'
>                                      r'Function not implemented')
> ```

Could you add some negative tests for parsing of these structs? So that ASan gets more coverage - e.g. wrong types of elements, empty arrays/tables, negative or super big numbers, etc.).
The parsing logic is really complex and the only tests we have are super simple.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 269 at r7](https://reviewable.io/reviews/gramineproject/gramine/671#-NFkOCK431mXFuV1ixPZ:-NV71G5p3gZ7uFIr5eWu:b-rf6z5j) ([raw file](https://github.com/gramineproject/gramine/blob/d3a3087a4123319e64e144e4bb07cac9eec87f4c/pal/src/host/linux-sgx/pal_devices.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still feel like it's shooting ourselves in the foot. Currently I error out with a loud error message when I see `{ ptr = ..., size = ...}`.

If we allow `{ ptr = ..., size = 5}`, then it will sometimes work (when addr value fits into 5 bytes), and sometimes not, so good luck debugging such bloopers...
</blockquote></details>

I'm rather neutral on this, but we'll need to change it when moving to a more generic place.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 236 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV4f_6I15pjlJYvFw-0:-NV4f_6I15pjlJYvFw-1:b-gfhgul) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L236)):*
> ```C
>  *   struct pascal_str { uint8_t len; char str[]; };
>  *   struct c_str { char str[]; };
>  *   struct root { struct pascal_str* s1; struct c_str* s2; uint64_t s2_len; int8_t x; int8_t y; };
> ```

It's not really a C-string if you represent it as a pointer and length? ;)



_Code quote:_
```C
struct c_str* s2; uint64_t s2_len
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 244 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV4g93_ColhcdCK7QW-:-NV4g93_ColhcdCK7QW0:b-iy46fn) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L244)):*
> ```C
>  * contains two pointers to other objects (pascal-style string and a C-style string) and embeds two
>  * integers `x` and `y`. The two strings reside in separate memory regions in enclave memory. Note
>  * that the max possible length of the C-style string is stored in the `s2_len` field of the root
> ```

Why is it called "s2 len" then, if it's not the length of the string, but the buffer allocation size?



_Code quote:_
```C
the max possible length of the C-style string is stored in the `s2_len` field
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 271 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV79QAQDCj-dPssE2oq:-NV79QAQDCj-dPssE2or:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L271)):*
> ```C
>  *   ]
>  *
>  * One can observe the following rules in this TOML syntax:
> ```





_Suggestion:_
```C
The current TOML syntax has the following rules/limitations:
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 278 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV75XM7DiIMSTD-Faq9:-NV75XM7DiIMSTD-FaqA:b94ameu) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L278)):*
> ```C
>  *     `ptr` is a TOML-array representation of that other memory region or a TOML string with the
>  *     name of another memory region. The `ptr` sub-region always has size of 8B (assuming x86-64)
>  *     and doesn't have an in/out direction.  The `array_len` field specifies the number of adjacent
> ```

I think we decided to not do double-space-after-period at some point? I'm neutral on this, but would like to be consistent.



_Code quote:_
```C
.  
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 279 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV762g82IdHtfwkNfrr:-NV762g82IdHtfwkNfrs:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L279)):*
> ```C
>  *     name of another memory region. The `ptr` sub-region always has size of 8B (assuming x86-64)
>  *     and doesn't have an in/out direction.  The `array_len` field specifies the number of adjacent
>  *     memory regions that this pointer points to (i.e. the length of an array).
> ```





_Suggestion:_
```C
i.e. the length of the array
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 287 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV78fvNDK-KuomjrSJ-:-NV78fvNDK-KuomjrSJ0:b-nzwq4b) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L287)):*
> ```C
>  *     sub-region, either in the same memory region (e.g. as in flexible array members in C) or in
>  *     the "outer" memory region (e.g. the size specifier is located in the root memory region and
>  *     the buffer is located in the nested memory region).
> ```

This is just a limitation of the current parser, right? Normally if the array is referenced via a pointer then it should be fine, but a bit harder to parse (I guess) if the size is located after the pointer?
If that's the case, would be good to include this in the comment.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 335 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7B7qw439lQYYpV_Sw:-NV7B7qw439lQYYpV_Sx:bgi1ca) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L335)):*
> or a special "pointer" sub-region

Stale comment? There's no such value in this enum.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 344 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7BaozA5KIZAY5et9b:-NV7BaozA5KIZAY5et9c:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L344)):*
> ```C
> 
> struct mem_region {
>     toml_array_t* toml_mem_region; /* describes contigious sub_regions in this mem_region */
> ```





_Suggestion:_
```C
contiguous
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 344 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7BmFi9oJ0j79LVyKw:-NV7BmFi9oJ0j79LVyKx:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L344)):*
> ```C
> 
> struct mem_region {
>     toml_array_t* toml_mem_region; /* describes contigious sub_regions in this mem_region */
> ```





_Suggestion:_
```C
sub-regions in this mem-region
```
_ [...]

2023-05-12 15:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 14 of 26 files reviewed, 47 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsejSU-TbrXev3xrUw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds weird to me, is this a real construct in English? I'd rather say "is located" or "can be found".
</blockquote></details>

Will do at final rebase.
___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUuNnyHE5sJlnmInQJ9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: Add a note on a second test (`device_ioctl_fail`) that tests the failure if no allowed IOCTLs.
</blockquote></details>

TODO: And on the third test.
___
*[`Documentation/manifest-syntax.rst` line 824 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUshklh3AR0Yzz5ZxUd:-NVEwfMj9_Be3vah2fR8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L824)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(this is only for ioctl passthrough, not the whole Gramine)
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 839 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslv1M-ASfR_QFwGqS:-NVEx0GN7rDkpdSkg9j-:bksit0z) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L839)):*
> ```reStructuredText
> - ``name`` is an optional name for this sub-region; mainly used to find
>   length-specifying fields and nested memory regions.
> - ``align`` is an optional alignment of the memory region; may be specified only
> ```

What do you mean? The key is called `align`. Do you suggest to rename the key?
___
*[`Documentation/manifest-syntax.rst` line 841 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsidJeA248XNNNApy9:-NVExAXP0Lj-N6QtuR66:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L841)):*
> ```reStructuredText
> - ``align`` is an optional alignment of the memory region; may be specified only
>   in the first sub-region of a memory region (all other sub-regions are
>   contigious with the first sub-region, so specifying their alignment doesn't
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 849 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsj5H1BjCb8nirhUaT:-NVExRBs2z5B4-WucHqw:bqphbth) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L849)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But at the beginning you say that this field is mandatory?
</blockquote></details>

Done. Removed the word `mandatory`.
___
*[`Documentation/manifest-syntax.rst` line 854 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslriAB6KhG9zTfvXU:-NVExUUWCK_4SnAuMUbe:b-fxjo93) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L854)):*
> ```reStructuredText
>   ``size = "strlen"`` and ``unit = 2`` denote a wide-char string (where each
>   character is 2B long) of a dynamically specified length.
> - ``adjust`` is an optional integer adjustment for ``size`` (always specified in
> ```

What do you mean? The key is called `adjust`. Do you suggest to rename the key?
___
*[`Documentation/manifest-syntax.rst` line 861 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsjo0m823CnO-kmt93:-NVExivsDHi_88n4x-SO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L861)):*
> ```reStructuredText
>   cannot be specified with non-``ptr`` regions.
> - ``direction = "none" | "out" | "in" | "inout"`` is an optional direction of
>   copy for this sub-region. For example, ``direction = "out"`` denotes a
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 871 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsk_ODAh_YYk0osbx_:-NVExwLeCh1Q37-O_RHJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L871)):*
> ```reStructuredText
>   specifies a pointer to another, nested memory region. This field is required
>   when describing complex IOCTL structs. Such pointer memory region always has
>   the implicit size of 8B, and the pointer value is always rewired to the memory
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 874 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUskhaA8BUDLj89HcDW:-NVEyE-m04eUeDGfP7MJ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L874)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for the parenthesis
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 877 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslGAQ31akAOGGlgLa:-NVEz4KL49Xujqwk3V3I:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L877)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use `.. code-block:: C` (but I'm not sure if this syntax is exactly correct) to highlight this snippet.
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 882 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsn_zBC2BeyUPmWBIE:-NVF-2b_AkP6dHkwQhGq:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L882)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think this is a valid C syntax?
</blockquote></details>

Done.
___
*[`Documentation/manifest-syntax.rst` line 925 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsoaIsAnyNJAyEsUyi:-NVF-W-REh7k0tN2xUIS:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L925)):*
> ```reStructuredText
> 
> .. note ::
>    IOCTLs for device communication are pass-through and thus insecure by
> ```

Done.
___
*[`Documentation/manifest-syntax.rst` line 875 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1xWmF129T-3H76RfX:-NVEyWoF0m4qA4EtjbKV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/Documentation/manifest-syntax.rst#L875)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add that this may be recursive with `NULL` value being a guard, which allows describing linked lists.
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl.c` line 29 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV1u66jAegSNJU0b7WH:-NVF1U_d30KFqNVmN2me:b-p6ijch) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/libos/test/regression/device_ioctl.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you think it's indeed better then p [...]

2023-05-15 06:00 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 14 of 26 files reviewed, 66 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`Documentation/manifest-syntax.rst` line 839 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslv1M-ASfR_QFwGqS:-NVRvkSsDDiTnVEEkWWP:b-8tuxhq) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L839)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? The key is called `align`. Do you suggest to rename the key?
</blockquote></details>

Looks reasonable since the other fields are nouns.
___
*[`Documentation/manifest-syntax.rst` line 838 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVRuLEr6edppejyn943:-NVRuLEr6edppejyn944:b6jic9q) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L838)):*
> ```reStructuredText
> 
> - ``name`` is an optional name for this sub-region; mainly used to find
>   length-specifying fields and nested memory regions.
> ```

sub-regions? (we should try to not mix the term `field` and `sub-region`)



_Code quote:_
```reStructuredText
fields
```
___
*[`Documentation/manifest-syntax.rst` line 843 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVRtVaTD80Y4mwewerw:-NVRtVaUCY_4anpkU5sP:b2niczw) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L843)):*
> ```reStructuredText
>   contiguous with the first sub-region, so specifying their alignment doesn't
>   make sense).
> - ``size`` is a size of this sub-region. The ``size`` field may be a string with
> ```

the



_Code quote:_
```reStructuredText
a
```
___
*[`Documentation/manifest-syntax.rst` line 844 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVRu-rDEAjRKYkai2TL:-NVRu-rDEAjRKYkai2TM:bnf6giv) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L844)):*
> ```reStructuredText
>   make sense).
> - ``size`` is a size of this sub-region. The ``size`` field may be a string with
>   the name of another field that contains the size value or an integer with the
> ```

sub-region? 



_Code quote:_
```reStructuredText
field
```
___
*[`Documentation/manifest-syntax.rst` line 859 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVRxXMfAsKEbVV2l0ua:-NVRxXMfAsKEbVV2l0ub:bx337vl) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L859)):*
> ```reStructuredText
>   results in a total size of 4B.
> - ``array_len`` denotes the number of items in the ``ptr`` array. This field
>   cannot be specified with non-``ptr`` regions.
> ```

Is it better that we move this after `ptr`? Also, we should state that it's optional and its default vaule (as the other fields do).



_Code quote:_
```reStructuredText
- ``array_len`` denotes the number of items in the ``ptr`` array. This field
  cannot be specified with non-``ptr`` regions.
```
___
*[`Documentation/manifest-syntax.rst` line 859 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSnZiW36W8k3fde6nl:-NVSnZiW36W8k3fde6nm:b-xm42pf) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L859)):*
> ```reStructuredText
>   results in a total size of 4B.
> - ``array_len`` denotes the number of items in the ``ptr`` array. This field
>   cannot be specified with non-``ptr`` regions.
> ```

sub-regions



_Code quote:_
```reStructuredText
regions
```
___
*[`Documentation/manifest-syntax.rst` line 932 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS-STwA2iHjl1H8C26:-NVS-STwA2iHjl1H8C27:boyukb2) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/Documentation/manifest-syntax.rst#L932)):*
> ```reStructuredText
>    insecure by themselves in SGX environments:
> 
>        - IOCTL arguments are passed as-is from the app to the untrusted host,
> ```

This renders a bit wrong. Or you intended this way?
___
*[`libos/src/sys/libos_ioctl.c` line 48 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS1xV31pb6Z8yh0sfi:-NVS1xV44l6jx9OpH3XT:bz98777) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/libos/src/sys/libos_ioctl.c#L48)):*
> ```C
>     unlock(&g_dcache_lock);
> 
>     if (is_host_dev) {
> ```

Any special reason that we invoke this PAL call before sanity checks (in the SWITCH below)?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 440 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7DzeXBKBoCGWujKt8:-NVSIcHb8pnTHowxxj56:b625l92) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L440)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why? `align == 0` means "no need for alignment". Isn't it valid?
</blockquote></details>

Shouldn't it alignment be a power of two (i.e., 0 is invalid)?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 794 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVCD2k56XM1uWFCackB:-NVSrPU07gPRaUstHleM:b-pudfek) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L794)):*
> Why do you say that `memset(some-untrusted-region, 0)` is not secure?

Intel-SA-00615 (all writes to untrusted memory from within the enclave must be done in 8-byte chunks aligned to 8-bytes boundary)?
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 252 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS4u8ZCNaswf8QKpDQ:-NVS4u8ZCNaswf8QKpDR:b-6ps86b) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L252)):*
> ```C
>  * IOCTL could for example be used to convert a Pascal string into a C string (C string will be
>  * truncated to user-specified `s2_size` if greater than this limit), and find the indices of the
>  * first occurences of chars "x" and "y" in the Pascal string.
> ```

occurrences



_Code quote:_
```C
occurences
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 266 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS9mm_5QCGXWad5ZLF:-NVS9mm_5QCGXWad5ZLG:bclp8gj) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L266)):*
> ```C
>  *     { name = "c-str-size", size = 8, direction = "inout" },
>  *     { size = 1, direction = "in" }
>  *     { size = 1, direction = "in" }
> ```

So it's two SRs or one SR?



_Code quote:_
```C
 *     { size = 1, direction = "in" }
 *     { size = 1, direction = "in" }
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 282 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS9vCN1FAVr-5c_Joj:-NVS9vCN1FAVr-5c_Jok:b2h2n4s) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L282)):*
> ```C
>  *     and doesn't have an in/out direction. The `array_len` field specifies the number of adjacent
>  *     memory regions that this pointer points to (i.e. the length of the array).
>  *  4. Sub-regions can be fixed-size (like the last sub-region containing two bytes `x` and `y`) or
> ```

So it's two SRs or one  [...]

2023-05-15 10:31 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 14 of 26 files reviewed, 66 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NVCABUZAOA3zXEeIfcQ:-NVTwwrK4xv5ZyMwiVrU:b-roanii) (no related file):*
> could you also take a look at this PR?

@mkow I did a first pass on the PR and made some comments/questions. I'll finish the rest and follow up all discussions.

___


<!-- Sent from Reviewable.io -->

2023-05-18 00:47 UTC, mkow requested changes
> Reviewed 6 of 12 files at r21, 6 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`Documentation/manifest-syntax.rst` line 839 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUslv1M-ASfR_QFwGqS:-NVaoBEnEQZyh5Ggn7sx:bpnndbc) ([raw file](https://github.com/gramineproject/gramine/blob/4d73f74e8663ce8aac423cd4f359b57a5258744a/Documentation/manifest-syntax.rst#L839)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, as Kailun said, almost all others are nouns (and a verb doesn't make much sense as a struct field name).
___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 33 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVeetjM9cgezr-BhETG:-NVeetjM9cgezr-BhETH:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/libos/test/regression/device_ioctl_parse_fail.manifest.template#L33)):*
> ```
> ]
> 
> # Buffer is defined before its size is defined (parser doesn't "know" when buffer ends and fails)
> ```





_Suggestion:_
```
parser doesn't "know" where buffer ends and fails
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 244 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV4g93_ColhcdCK7QW-:-NVegKHN2YyXSXYwsiqM:bpeq7r5) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L244)):*
Maybe `s2_buf_size`? Or `s2_alloc_size`? It still sounds like it was the length of the passed string, but this time counting the NULL byte.
And yes, this example is really contrived, that's why I want to make the naming/description better - I had troubles understanding what's happening here.

> and its actual size

This still sounds like you're talking about the size of the string, not the allocation size of the buffer holding it.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 287 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV78fvNDK-KuomjrSJ-:-NVehWCJ8GW8YeI2cVBp:b-whg5re) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L287)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Though maybe this comment is not needed, because I think there are no legitimate cases where it would be possible, see below.

> a bit harder to parse (I guess) if the size is located after the pointer?

I'm not sure I understand you. The size after the **pointer** is not a problem -- the pointer is 8-byte-sized always, and the **array this pointer points to** is always a nested memory region, so it will always be "after" the size, because we do Breadth First Search (in other words, when the parser gets to the array, the parser already parsed and resolved the size).
</blockquote></details>

The BFS order was what was missing, I thought you're talking about top-down order (probably the default in standard English text).
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 440 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7DzeXBKBoCGWujKt8:-NVekbCR5HmMMab2WDHb:blnho5i) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L440)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, ok, `align==0` doesn't make sense. Done.
</blockquote></details>

Yeah, "alignment" means what the address is divisible by, so zero doesn't make sense.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 479 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV7GeE99YxzidhHsvUT:-NVelFByCENO54SAZOf8:b8d57yi) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L479)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I considered this, but if you look at the current code, there are too many level of functions. So we'd need to drag this `toml_ioctl_structs` object through a bunch of functions, just for this single usage. I don't find it "clean".

I could introduce some kind of the `ioctl_parsing_state` struct which would contain all these helpers and be populated across these functions -- but this also sounds like overkill (just for a single `toml_ioctl_structs`?).

Also note that this PR intentionally doesn't introduce any performance optimizations. This will be a follow-up work (see PR description).
</blockquote></details>

Ok, let's keep it as it is then.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 588 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVC1g_x6ifhl4eO_24L:-NVelZHXE_p69o49uLPj:b4e0uhp) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L588)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. What does BOF mean?
</blockquote></details>

Buffer OverFlow
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 770 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVCCXwJ0a8g0Ns_B9mE:-NVg-TWG5DNOMpKdxx_m:b7atv7l) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L770)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, it's not a bug. To be honest, I don't understand your problem.

Here we're protecting against the following case:
```c
    struct ioctl_blabla {
        char* arr_of_bufs[10];
    }

    struct ioctl_blabla x;
    x.arr_of_bufs[0] = 0x42; // points to mem region, must also parse it
    x.arr_of_bufs[1] = NULL; // this doesn't point to any mem region, so must be skipped
    x.arr_of_bufs[2] = 0x24; // points to mem region, must also parse it
```
</blockquote></details>

This check is either true for all iterations or always false for all of them. It doesn't depend on `k` or any other loop-related variable, that's why it looks suspicious, especially that you need some calculations to check it. Is this intended? If so, then it's a rather weird construct... Why not move it out of the loop?

Actually, this loop does exactly nothing if the check is false, shouldn't it cover the whole loop then? I.e.:

```C
void* mem_region_addr = *((void**)sub_regions[i].enclave_addr);
if (mem_region_addr) {
    for (size_t k = 0; k < sub_regions[i].array_len.value; k++) {
        [...]
    }
}

```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 789 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVC8iYn0RsxSxQ99dg7:-NVg1nP98iW3uYYlSFO-:brpjxn5) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L789)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Not sure I understand what exactly you want, but hopefully this.
</blockquote></details>

Yes, this. Otherwise we'll end up with dangling pointers saved there, which are easy to accidentally misuse.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 680 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVfzD0H1C7RPskJItpN:-NVfzD0H1C7RPskJItpO:b-ze0icc) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devic [...]

2023-05-19 04:14 UTC, kailun-qin requested changes
> Reviewed 1 of 11 files at r6, 6 of 16 files at r14, 3 of 9 files at r16, 1 of 5 files at r17, 6 of 12 files at r21, 6 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/src/sys/libos_ioctl.c` line 48 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVS1xV31pb6Z8yh0sfi:-NVlqZhJ9psF9Yoojdwa:b-gn6hcg) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/libos/src/sys/libos_ioctl.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The only sanity check that we have below is the `is_user_memory_writable(arg)` one. But this is not applicable here -- some IOCTLs do not specify the `arg` at all, some IOCTLs have it read-only, some IOCTLs have it write-only. We can't know how to check `arg` in a general case. That's why I didn't add any checks.
</blockquote></details>

Make sense, thanks for the explanation!
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 396 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSDtwl66qH71_N05lO:-NVls6AZ7G-TaIBaUyTe:b-gxztsp) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L396)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think we want to document it, as I have never seen a real-life IOCTL that would specify sub-regions in incorrect order.
</blockquote></details>

Fair enough.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 443 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSjBv62-8WLlT4qXE3:-NVlsJzZC5hoyRbAA185:bnfuwxs) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L443)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `8`? But you're right, `0` didn't make sense. I modified the default value to `1`.
</blockquote></details>

Just giving an example, I'm fine w/ `1`.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 481 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSLWgB0oyu9x0IwqkD:-NVltAYL3OYgJOc2N8Yj:bcr5s2o) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L481)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This means that there's no `ptr` field at all in this sub-region (recall that `toml_string_in()` returns a NULL string if it doesn't find the key). So it's a success -- in the sense that there is no nested memory region (i.e., the current sub-region is a non-ptr sub-region).
</blockquote></details>

Got it, thanks!
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 614 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSicXP9WRMw4ecGYMR:-NVltGfY5dusevtCuNt0:b-aer914) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L614)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

"Before" means in the BFS order. In this example, the `{ name = "buf_size" }` sub-region is located in the **outer** memory region, and the `{ size = "buf_size" }` sub-region (which references the former sub-region) is located in the **inner** memory region.

Thus, `{ name = "buf_size" }` comes before `{ size = "buf_size" }`.

I added a quick comment in that `Note that this ...` sentence.
</blockquote></details>

Thanks for the clarification for `BFS order`. Looks good to me now.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 716 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSlUbPEyS7T_GRgSKd:-NVltYV25tfX6VjSKjeg:b-rehwbk) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L716)):*
> Was it a typo?

Ah, it was a typo.

> Did you mean "the `array_len` field only makes sense together with the `ptr` field"?

Yes

> I can add such a check, if that's what you wanted. Done.

Thanks!
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 781 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSY4Pg4ByfSxwkFJ4d:-NVltxZ23V-lgjx1I3uL:bfopja8) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L781)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why? It is needed, because we overwrite `sub_regions[i].array_len` object immediately afterwards (and thus we would lose the reference to the previously allocated `sub_regions[i].array_len.sub_region_name`).
</blockquote></details>

Yes, you are right -- I misread it.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 953 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSxwZM-DyJUJxtBp3F:-NVlubVv6NuTPhQv8Y5x:b-wht4k0) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L953)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd say yes. This covers the case like this: `sgx.allowed_ioctls = [ ]` (empty set). In this case, it looks reasonable to me to return `-ENOSYS` ("I don't know this IOCTL") rather than `-EINVAL` ("I couldn't parse this IOCTL correctly").
</blockquote></details>

OK, make sense!
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 310 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm-3_T6Eal9MuMyHu8:-NVm-3_T6Eal9MuMyHu9:b-jr24yc) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L310)):*
> ```C
>  *      struct root (MR1)                   |       deep-copied struct (aligned at 128B)
>  *      +----------------------+            |       +-----------------------------+
>  *  +----+ pascal_str* s1      |     SR1    |    +----+ pascal_str* s1    (MR1)   |
> ```

nit: align the text right
```
+----+ pascal_str* s1      (MR1) |
```



_Code quote:_
```C
+----+ pascal_str* s1    (MR1)   |
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 853 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6r0i-W3w2vLrB0RB:-NVm6r0i-W3w2vLrB0RC:b-qj7zn2) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L853)):*
> ```C
>             bool ret = sgx_copy_from_enclave(cur_untrusted_addr, sub_regions[i].enclave_addr,
>                                              sub_regions[i].size);
>             if (!ret)
> ```

Why not simply
```
if (!sgx_from_to_enclave())
    return ...
```



_Code quote:_
```C
            bool ret = sgx_copy_from_enclave(cur_untrusted_addr, sub_regions[i].enclave_addr,
                                             sub_regions[i].size);
            if (!ret)
```
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 874 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6xrv6ST8_rPRf2Cr:-NVm6xrv6ST8_rPRf2Cs:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L874)):*
> ```C
>                                                      sizeof(void*));
>                     if (!ret)
>                         return -PAL_ERROR_DENIED;
> ```

ditto



_Code quote:_
```C
                    [...]

2023-05-19 10:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 24 of 26 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 33 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVeetjM9cgezr-BhETG:-NVnO3MCELfUxdKvRS5-:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/libos/test/regression/device_ioctl_parse_fail.manifest.template#L33)):*
> ```
> ]
> 
> # Buffer is defined before its size is defined (parser doesn't "know" when buffer ends and fails)
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 244 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NV4g93_ColhcdCK7QW-:-NVnP8tvBav5D7LebBtQ:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L244)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe `s2_buf_size`? Or `s2_alloc_size`? It still sounds like it was the length of the passed string, but this time counting the NULL byte.
And yes, this example is really contrived, that's why I want to make the naming/description better - I had troubles understanding what's happening here.

> and its actual size

This still sounds like you're talking about the size of the string, not the allocation size of the buffer holding it.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 770 at r20](https://reviewable.io/reviews/gramineproject/gramine/671#-NVCCXwJ0a8g0Ns_B9mE:-NVnRH3h3jf1VcuETZM_:b2rmson) ([raw file](https://github.com/gramineproject/gramine/blob/b88af7baa0e235285c08a2a349d45b497669f068/pal/src/host/linux-sgx/pal_devices.c#L770)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This check is either true for all iterations or always false for all of them. It doesn't depend on `k` or any other loop-related variable, that's why it looks suspicious, especially that you need some calculations to check it. Is this intended? If so, then it's a rather weird construct... Why not move it out of the loop?

Actually, this loop does exactly nothing if the check is false, shouldn't it cover the whole loop then? I.e.:

```C
void* mem_region_addr = *((void**)sub_regions[i].enclave_addr);
if (mem_region_addr) {
    for (size_t k = 0; k < sub_regions[i].array_len.value; k++) {
        [...]
    }
}

```
</blockquote></details>

Done. Sorry, I thought that by "loop" and "iterations" you mean the outer `while` loop. But you mean the inner `for` loop. Yes, you are right. Fixed according to your proposal.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 680 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVfzD0H1C7RPskJItpN:-NVnPqsx9HQLE2htnsCW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L680)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fold to `} else if (...) {`.
</blockquote></details>

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 835 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVgAIJ2Ed5ubQF44FZI:-NVnR_G15yqkjHPDzxgB:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L835)):*
> ```C
>                                          void* untrusted_addr) {
>     /* we rely on the fact that the untrusted memory region was zeroed out: we can simply "jump
>      * over" untrusted memory when doing alignment and when direction of copy is in or none */
> ```

Done.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 853 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6r0i-W3w2vLrB0RB:-NVnRlCk0bR1se3Tqz8N:b-ykfrfe) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L853)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why not simply
```
if (!sgx_from_to_enclave())
    return ...
```
</blockquote></details>

In my opinion, your proposed construct **obscures the intention** here -- I want to make it very explicit that it this point, we make the actual copy. I would prefer to keep the code as is. It looks weird, but that's exactly my intention -- the reader should "stop" on this line and think what happens here.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 874 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6xrv6ST8_rPRf2Cr:-NVnS3rRD52ZMMlg57CP:b-xfglqw) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L874)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto (I want it written in this weird very explicit way)
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 893 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6Oiv1_HvGG3Cbo8x:-NVnSAI5AP3TzKK4RNrf:b-xfglqw) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L893)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why not simply
```
if (!sgx_copy_to_enclave())
    return ...
```
</blockquote></details>

ditto (I want it written in this weird very explicit way)
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 914 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVgH4TUEqLUS9vQimYi:-NVnSOo19j-N8p4fpwte:b-plwdhq) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L914)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems wrong: `toml_rtos()` failed, but you still call `free()` on its result (`ioctl_struct_str`).
</blockquote></details>

Done. Though it wasn't wrong -- if `toml_rtos()` fails then it doesn't modify `ioctl_struct_str` which was set to `NULL` beforehand. So `free()` would be just a no-op.
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 1031 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVg4qKxE16Bir0w8y7Q:-NVnSmOq6cLt0A5gtfmb:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L1031)):*
> ```C
>     for (size_t i = 0; i < sub_regions_cnt; i++) {
>         /* overapproximation since alignment doesn't necessarily increase sub-region's size */
>         untrusted_size += sub_regions[i].size + sub_regions[i].alignment;
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-05-19 10:38 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 15 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 853 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVm6r0i-W3w2vLrB0RB:-NVnZdxs3u6walqsvnSB:b-jo4rm2) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L853)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In my opinion, your proposed construct **obscures the intention** here -- I want to make it very explicit that it this point, we make the actual copy. I would prefer to keep the code as is. It looks weird, but that's exactly my intention -- the reader should "stop" on this line and think what happens here.
</blockquote></details>

OK I see. Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2023-05-19 11:01 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 33 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVeetjM9cgezr-BhETG:-NVneyF74vX3mXCe53m9:bfhqmln) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/libos/test/regression/device_ioctl_parse_fail.manifest.template#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2023-05-19 11:02 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 15 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/regression/device_ioctl_parse_fail.manifest.template` line 33 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVeetjM9cgezr-BhETG:-NVnf2SY10KYhTjYv0Fl:b-y6uk55) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/libos/test/regression/device_ioctl_parse_fail.manifest.template#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Update: Oops, its done, excuse me for my blindness


<!-- Sent from Reviewable.io -->

2023-05-19 11:25 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 716 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSlUbPEyS7T_GRgSKd:-NVnjBJ94T-RFeevpYwU:b61iwym) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L716)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> Was it a typo?

Ah, it was a typo.

> Did you mean "the `array_len` field only makes sense together with the `ptr` field"?

Yes

> I can add such a check, if that's what you wanted. Done.

Thanks!
</blockquote></details>

I re-read this. The added check only ensures that non-`ptr` field cannot specify `array_len`. But since we're still calling `get_sub_region_array_len()` here so we'll always have a default `array_len` assigned to the current sub-region?


<!-- Sent from Reviewable.io -->

2023-05-19 11:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 25 of 26 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-sgx/pal_devices.c` line 716 at r21](https://reviewable.io/reviews/gramineproject/gramine/671#-NVSlUbPEyS7T_GRgSKd:-NVnmKKwENVGuAaZisXs:br6wbt0) ([raw file](https://github.com/gramineproject/gramine/blob/494a0fde52bb6e2326d08b2b6fcfa73e690f4176/pal/src/host/linux-sgx/pal_devices.c#L716)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I re-read this. The added check only ensures that non-`ptr` field cannot specify `array_len`. But since we're still calling `get_sub_region_array_len()` here so we'll always have a default `array_len` assigned to the current sub-region?
</blockquote></details>

Done. You are correct. This is a bit weird. I added a comment explaining that this is a benign (though unnecessary) invocation. I think the comment is easier than adding IF checks here.


<!-- Sent from Reviewable.io -->

2023-05-19 11:46 UTC, kailun-qin approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 25 of 26 files reviewed, 15 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2023-05-26 00:24 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/671#-NNuzGrZ5Ebp_cyVyowc:-NWKR3wp3-JQJSwUpZ0I:bc1ibdm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, an interesting consequence of current `dev` files implementation in Gramine.

We typically write like this (see example in this PR), to enable a device inside Gramine:
```
fs.mounts = [
  { path = "/dev/gramine_test_dev", uri = "dev:/dev/gramine_test_dev" },
]
```

Sometimes, however, the device name is not known in advance (some devices like to have suffixes like `/dev/tty42`), and this name differs from one machine to the other. Currently, Gramine's FS code doesn't allow to open *any* device; the device name must be hard-coded in the manifest as above.

I am not sure we want to change this behavior... I see one workaround for such a problem: request Gramine deployers to prepare their machines -- to create symlinks from the actual device name to the hard-coded name in the manifest. E.g. the deployers must perform smth like `ln -s /dev/actual_device_name_42 /dev/gramine_test_dev` on each machine.
</blockquote></details>

I wouldn't change this, it makes dangerous configuration of Gramine easier than the safe one.

___
___
*[`pal/src/host/linux-sgx/pal_devices.c` line 914 at r22](https://reviewable.io/reviews/gramineproject/gramine/671#-NVgH4TUEqLUS9vQimYi:-NWKQREQ-zCCSELULrsf:boq8uue) ([raw file](https://github.com/gramineproject/gramine/blob/0035e6f7a570a9c3bb0c0d7cfb07dcb41f0daf96/pal/src/host/linux-sgx/pal_devices.c#L914)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Though it wasn't wrong -- if `toml_rtos()` fails then it doesn't modify `ioctl_struct_str` which was set to `NULL` beforehand. So `free()` would be just a no-op.
</blockquote></details>

That's what we do as a convention in Gramine, not sure if other libraries are also that sane ;)


<!-- Sent from Reviewable.io -->

2023-05-29 12:53 UTC, dimakuv reviewed
> Dismissed @boryspoplawski from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-30 07:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 17 of 26 files reviewed, 2 unresolved discussions (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUuNnyHE5sJlnmInQJ9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: And on the third test.
</blockquote></details>

Done
___
*[`-- commits` line 27 at r16](https://reviewable.io/reviews/gramineproject/gramine/671#-NUsejSU-TbrXev3xrUw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do at final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-30 09:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: 25 of 26 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 30 at r25](https://reviewable.io/reviews/gramineproject/gramine/671#-NWftTQ61FolzQegWkFa):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `IOCTL structs` maybe? The third test is not exactly checking on the manifest "formatting" IMO.
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl_parse_fail.c` line 1 at r25](https://reviewable.io/reviews/gramineproject/gramine/671#-NWfr1nhE0yptuwstdPg:-NWfy3_C6ZVIowOwivSq:b-tn4jeh) ([raw file](https://github.com/gramineproject/gramine/blob/ba1eb854f70a4cd2fd1d5171f4602d6e04519686/libos/test/regression/device_ioctl_parse_fail.c#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

Yes, required, otherwise:
```
In file included from ../libos/test/regression/device_ioctl_parse_fail.c:12:
../libos/test/regression/gramine_test_dev_ioctl.h:16:5: error: unknown type name ‘loff_t’
```
___
*[`libos/test/regression/device_ioctl_parse_fail.c` line 5 at r25](https://reviewable.io/reviews/gramineproject/gramine/671#-NWfr3qt4ggt_xrgTuN_:-NWfyW5T6Y9_33zzU-gO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba1eb854f70a4cd2fd1d5171f4602d6e04519686/libos/test/regression/device_ioctl_parse_fail.c#L5)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/regression/device_ioctl_parse_fail.c` line 7 at r25](https://reviewable.io/reviews/gramineproject/gramine/671#-NWfrGKvDHau0EJD65OH:-NWfyWTR74-x3Dh8mBrs:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ba1eb854f70a4cd2fd1d5171f4602d6e04519686/libos/test/regression/device_ioctl_parse_fail.c#L7)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 09:47 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-05-31 14:42 UTC, mkow approved these changes
> Reviewed 9 of 9 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/671)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-31 14:43 UTC, merged