[CI] Add bash bc tool to CI systems
gramineproject/gramine pull request #693
Opened 2022-06-29 03:06 UTC by vijaydhanraj

## Description of the changes 

Additionally, this commit also increases max-connections value for `lighttpd` workload in CI-Examples. This was done to remove the following log messages:

```
server.c.980) [note] sockets disabled, connection limit reached
server.c.973) [note] sockets enabled again
```

## How to test this PR? 
Please run `lighttpd` workload as part of the `CI-Examples`

2022-06-29 06:02 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-06-29 06:02 UTC, dimakuv commented
Jenkins, test this please

2022-06-29 14:53 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-06-29 18:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @jinengandhi-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iXYub-fQxu2zJAbza):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What does `bc` has to do with `bash`?
Suggestion: ```[CI] Install missing `bc` tool```
</blockquote></details>

Yes, they are not related but I used the `bc` tool in our bash script. I have changed the commit message as suggested.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Removal of "log messages" should never be the reason. Why do we need this change? Why do we need so many connections? From what I can see we only use `300` connections.
</blockquote></details>

Without changing the max connections limit, the server emits the following messages. Felt this might clobber the logs we might capture in our CI. @jinengandhi-intel can provide some more details.

```
2022-06-29 18:01:55: server.c.980) [note] sockets disabled, connection limit reached
2022-06-29 18:01:55: server.c.973) [note] sockets enabled again
2022-06-29 18:01:55: server.c.980) [note] sockets disabled, connection limit reached
2022-06-29 18:01:55: server.c.973) [note] sockets enabled again
.
.
```

I did try to set the max connections to `300` in the `lighttpd` conf file but these messages were still being printed. But I have reduced this limit to `500` from `2048`. Would this be fine?
___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5kiJ3FEOAk6JhSUc-W:-N5kiJ3FEOAk6JhSUc-X:b-dq0x6k) ([raw file](https://github.com/gramineproject/gramine/blob/100b87d45746141479f130a47408dd890e95c09a/CI-Examples/lighttpd/lighttpd-generic.conf#L4)):*
> ```
> #server.event-handler          = "linux-sysepoll"
> 
> server.max-connections = 2048
> ```

I can revert the max connection change if we are fine with the above log messages. 


<!-- Sent from Reviewable.io -->

2022-06-29 21:00 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Without changing the max connections limit, the server emits the following messages. Felt this might clobber the logs we might capture in our CI. @jinengandhi-intel can provide some more details.

```
2022-06-29 18:01:55: server.c.980) [note] sockets disabled, connection limit reached
2022-06-29 18:01:55: server.c.973) [note] sockets enabled again
2022-06-29 18:01:55: server.c.980) [note] sockets disabled, connection limit reached
2022-06-29 18:01:55: server.c.973) [note] sockets enabled again
.
.
```

I did try to set the max connections to `300` in the `lighttpd` conf file but these messages were still being printed. But I have reduced this limit to `500` from `2048`. Would this be fine?
</blockquote></details>

We just should debug why messages appear if they are not wanted, not tweak options so that they disappear.


<!-- Sent from Reviewable.io -->

2022-06-29 22:20 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We just should debug why messages appear if they are not wanted, not tweak options so that they disappear.
</blockquote></details>

Th sockets get disable because `srv->conns.used >= srv->max_conn`,
```
static void server_load_check (server *srv) {
    /* check if hit limits for num fds used or num connections */
    if (srv->cur_fds > srv->max_fds_hiwat || srv->conns.used >= srv->max_conns)
        server_sockets_disable(srv);
}
```

I added debug prints and `lighttpd` calculates the `max_conn` to be `274`. Since we set the connections as `300`, the log message is printed. 

There are 2 options,
1. We set the number of connections to something less than `274` like `270` in https://github.com/gramineproject/gramine/blob/master/CI-Examples/common_tools/benchmark-http.sh#L14 instead of `300`
2. Or update the `lighttdp-generic.conf` to increase the max connections.

In this PR, I have taken option 2.

Please let me know which option is preferred or if you have any other suggestions.


<!-- Sent from Reviewable.io -->

2022-06-30 08:25 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel and @vijaydhanraj)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Th sockets get disable because `srv->conns.used >= srv->max_conn`,
```
static void server_load_check (server *srv) {
    /* check if hit limits for num fds used or num connections */
    if (srv->cur_fds > srv->max_fds_hiwat || srv->conns.used >= srv->max_conns)
        server_sockets_disable(srv);
}
```

I added debug prints and `lighttpd` calculates the `max_conn` to be `274`. Since we set the connections as `300`, the log message is printed. 

There are 2 options,
1. We set the number of connections to something less than `274` like `270` in https://github.com/gramineproject/gramine/blob/master/CI-Examples/common_tools/benchmark-http.sh#L14 instead of `300`
2. Or update the `lighttdp-generic.conf` to increase the max connections.

In this PR, I have taken option 2.

Please let me know which option is preferred or if you have any other suggestions.
</blockquote></details>

I think Borys just wants you to change the commit message such that it explains that our `benchmark-http.sh` test uses 300 connections, but Lighttpd by default sets the connection limit to around 270.

So please suggest the rewrite (or git-rebase, since this PR is trivial), and then Borys's request should be satisfied.
___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5kiJ3FEOAk6JhSUc-W:-N5nhjbA9N1Rf_-V_QZd:b-bedbix) ([raw file](https://github.com/gramineproject/gramine/blob/100b87d45746141479f130a47408dd890e95c09a/CI-Examples/lighttpd/lighttpd-generic.conf#L4)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I can revert the max connection change if we are fine with the above log messages. 
</blockquote></details>

I don't like 500. `1024` sounds like a more reasonable default.


<!-- Sent from Reviewable.io -->

2022-06-30 08:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel and @vijaydhanraj)

___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/693#-N5nhuWw-P3xCUdxycgv:-N5nhuWw-P3xCUdxycgw:bissn7n) ([raw file](https://github.com/gramineproject/gramine/blob/21a9fec3224383ddd505ea26d41f06cd2d037e18/CI-Examples/lighttpd/lighttpd-generic.conf#L4)):*
> ```
> #server.event-handler          = "linux-sysepoll"
> 
> server.max-connections        = 500
> ```

Also, no need to add all those spaces. You can also change the lines above to remove the redundant spaces.


<!-- Sent from Reviewable.io -->

2022-06-30 09:44 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel and @vijaydhanraj)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Borys just wants you to change the commit message such that it explains that our `benchmark-http.sh` test uses 300 connections, but Lighttpd by default sets the connection limit to around 270.

So please suggest the rewrite (or git-rebase, since this PR is trivial), and then Borys's request should be satisfied.
</blockquote></details>

@dimakuv No, I wanted to verify that this is not an issue / bug (like Gramine leaking connections or something), but just a legitimate resource limit we hit and @vijaydhanraj just did that.
And now, yes, the conclusion should be put into the commit message (instead of "we do this to remove log messages")


<!-- Sent from Reviewable.io -->

2022-06-30 18:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @jinengandhi-intel)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5iY-2A4vW_c53ciNmw):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv No, I wanted to verify that this is not an issue / bug (like Gramine leaking connections or something), but just a legitimate resource limit we hit and @vijaydhanraj just did that.
And now, yes, the conclusion should be put into the commit message (instead of "we do this to remove log messages")
</blockquote></details>

Reworded the commit message, please take a look.
___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/693#-N5kiJ3FEOAk6JhSUc-W:-N5pKJrpCHa2mgxNXqkF:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/100b87d45746141479f130a47408dd890e95c09a/CI-Examples/lighttpd/lighttpd-generic.conf#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like 500. `1024` sounds like a more reasonable default.
</blockquote></details>

Done.
___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 4 at r2](https://reviewable.io/reviews/gramineproject/gramine/693#-N5nhuWw-P3xCUdxycgv:-N5pKM5JDb5fhoD9GJbK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/21a9fec3224383ddd505ea26d41f06cd2d037e18/CI-Examples/lighttpd/lighttpd-generic.conf#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Also, no need to add all those spaces. You can also change the lines above to remove the redundant spaces.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-01 08:02 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel and @vijaydhanraj)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/693#-N5slT5N-v_MhurzBKYn):*
```
  Additionally, observed that Lighttpd workload in our CI-Examples
  set the default maximum number of allowed connections  to `274`
  but our benchmarking tool uses up to `300` connections, resulting
  in the following log message:
```


<!-- Sent from Reviewable.io -->

2022-07-01 08:59 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2022-07-01 11:50 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/693#-N5t_u2j3xBlrUUb2sGK:-N5t_u2j3xBlrUUb2sGL:bjouj8b) ([raw file](https://github.com/gramineproject/gramine/blob/4f1828e3e79e1bf755c7dcb4f719d342cee0e57b/CI-Examples/lighttpd/lighttpd-generic.conf#L2)):*
> ```
> server.event-handler = "select"
> # server.event-handler = "linux-sysepoll"
> ```

FYI: I think this was intended originally (to not have the space here). There's a convention that normal comments have a space and commented out code doesn't (so that you can see the difference easier).
But I don't care about this much.



_Code quote:_
```
# server.event-handler
```


<!-- Sent from Reviewable.io -->

2022-07-03 16:44 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/gramineproject/gramine/693#-N5slT5N-v_MhurzBKYn):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
  Additionally, observed that Lighttpd workload in our CI-Examples
  set the default maximum number of allowed connections  to `274`
  but our benchmarking tool uses up to `300` connections, resulting
  in the following log message:
```
</blockquote></details>

Done.
___
*[`CI-Examples/lighttpd/lighttpd-generic.conf` line 2 at r3](https://reviewable.io/reviews/gramineproject/gramine/693#-N5t_u2j3xBlrUUb2sGK:-N63uO1M8h9af0k6wiIc:b-boj3py) ([raw file](https://github.com/gramineproject/gramine/blob/4f1828e3e79e1bf755c7dcb4f719d342cee0e57b/CI-Examples/lighttpd/lighttpd-generic.conf#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: I think this was intended originally (to not have the space here). There's a convention that normal comments have a space and commented out code doesn't (so that you can see the difference easier).
But I don't care about this much.
</blockquote></details>

Thanks, got it. I saw the other comment `server.max-keep-alive-requests` which had space and thought that was the intended way. I have corrected this.


<!-- Sent from Reviewable.io -->

2022-07-03 16:49 UTC, vijaydhanraj commented
Jenkins, test this please.

2022-07-03 22:30 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-07-04 07:01 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski and @vijaydhanraj)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/gramineproject/gramine/693#-N67-h7N9_ShFze3oqNq):*
`set` -> `sets`. Can be done for final merge.
___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/gramineproject/gramine/693#-N67-nC79U3-SPkqrywS):*
Better to remove these triple-backticks and instead use a 4-line indentation. Can be done for final merge.


<!-- Sent from Reviewable.io -->

2022-07-04 13:19 UTC, dimakuv commented
Jenkins, test this please

2022-07-04 13:23 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/693)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-04 14:04 UTC, merged