[Pal/Linux] Remove unused `handle.file.map_start`
gramineproject/gramine pull request #695
Opened 2022-06-29 06:19 UTC by kailun-qin

Fixes https://github.com/gramineproject/gramine/issues/694

Signed-off-by: Kailun Qin <kailun.qin@intel.com>

2022-06-29 08:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/695#-N5i_VdE8Q0JsqwQtoxE):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It would be good to have actual struct name here
</blockquote></details>

You can post the intended commit message here, or if you think the proposed change is fine just let us know, we will fix during final rebase.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/695#-N5ia7a34OvMszthJap6):*
This can be removed, we do not keep track of issues in commit messages. The problem and the fix should be described inline (but here it's simple so that the commit oneliner is enough).


<!-- Sent from Reviewable.io -->

2022-06-29 08:54 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/695#-N5i_VdE8Q0JsqwQtoxE):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can post the intended commit message here, or if you think the proposed change is fine just let us know, we will fix during final rebase.
</blockquote></details>

Moved the issue description here, please kindly help adjust if needed.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine/695#-N5ia7a34OvMszthJap6):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This can be removed, we do not keep track of issues in commit messages. The problem and the fix should be described inline (but here it's simple so that the commit oneliner is enough).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-29 09:12 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/695#-N5ih6VQEuCcUoePMnaj:-N5ih6VQEuCcUoePMnak:baeezta) (no related file):*
Oh, and btw please do not force push :)
If you need to change the commit message (like in this PR) we usually do it in either of 2 options:
A) Just write the new commit message as a comment on reviewable. We will the adjust it when doing final rebase when merging.
B) `squash` commit with the new commit message (example: https://github.com/gramineproject/gramine/commit/de4acbf54d53d84de24f5497386965986e07a776)

___


<!-- Sent from Reviewable.io -->

2022-06-29 09:12 UTC, boryspoplawski commented
Jenkins, test this please

2022-06-29 09:36 UTC, kailun-qin commented
> B) `squash` commit with the new commit message (example: [de4acbf](https://github.com/gramineproject/gramine/commit/de4acbf54d53d84de24f5497386965986e07a776))

Great to know, will do, many thanks!

2022-06-29 14:59 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/695#-N5jxQfs550CvSqLTsy7):*
Please instead of commit hashes use commit one-liners (hopefully they are also unique). I don't like using hashes because they may change someday (e.g. we had to rewrite history once to drop 300MB of binary blobs from the initial hacky history of the project). Also, `gramineproject/graphene` is GitHub-specific, and some day in the future we may be using a different git hosting and then these will turn into dangling links (i.e. there's no context here which mentions GitHub). Or rename the organization. Or something similar ;)


<!-- Sent from Reviewable.io -->

2022-06-30 02:00 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gramine/695#-N5jxQfs550CvSqLTsy7):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please instead of commit hashes use commit one-liners (hopefully they are also unique). I don't like using hashes because they may change someday (e.g. we had to rewrite history once to drop 300MB of binary blobs from the initial hacky history of the project). Also, `gramineproject/graphene` is GitHub-specific, and some day in the future we may be using a different git hosting and then these will turn into dangling links (i.e. there's no context here which mentions GitHub). Or rename the organization. Or something similar ;)
</blockquote></details>

Thanks, added a squash message.


<!-- Sent from Reviewable.io -->

2022-06-30 08:08 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nckfO-jQb1DZ_5wNJ):*
`Pal/Linux` -> `PAL/Linux`. We used `Pal` before, but couple weeks ago we decided to use the proper `PAL` in our text and commit messages (all capital letters, because it is an abbreviation for Platform Adaptation Layer). Can be done during final rebase.
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nd3bV2bzf6rx1T4jl):*
To be honest, I wouldn't care about that super-old commit `Load forked executable ...`.

I would just rephrase to:
```
  `file.map_start` in `PAL_HANDLE` was initially introduced to load executables at
  the same address as in the parent during fork emulation, but this logic was later 
  overridden by commit "[Pal,LibOS] Handle entrypoint in LibOS". The field is not used
  any more so that we remove it.
```

Also note that we prefer double-quotes instead of backticks for commit titles.


<!-- Sent from Reviewable.io -->

2022-06-30 08:08 UTC, dimakuv commented
Jenkins, test this please

2022-06-30 08:24 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nckfO-jQb1DZ_5wNJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Pal/Linux` -> `PAL/Linux`. We used `Pal` before, but couple weeks ago we decided to use the proper `PAL` in our text and commit messages (all capital letters, because it is an abbreviation for Platform Adaptation Layer). Can be done during final rebase.
</blockquote></details>

Got it, thanks!
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nd3bV2bzf6rx1T4jl):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, I wouldn't care about that super-old commit `Load forked executable ...`.

I would just rephrase to:
```
  `file.map_start` in `PAL_HANDLE` was initially introduced to load executables at
  the same address as in the parent during fork emulation, but this logic was later 
  overridden by commit "[Pal,LibOS] Handle entrypoint in LibOS". The field is not used
  any more so that we remove it.
```

Also note that we prefer double-quotes instead of backticks for commit titles.
</blockquote></details>

Thanks, it looks better. Let me know if I need another squash commit.


<!-- Sent from Reviewable.io -->

2022-06-30 12:31 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 2 unresolved discussions, "squash! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-06-30 15:42 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nckfO-jQb1DZ_5wNJ):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Got it, thanks!
</blockquote></details>

Done.
___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/gramineproject/gramine/695#-N5nd3bV2bzf6rx1T4jl):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, you don't need to create new squash commits. I will keep my blocking comments, and whoever does the final rebase & merge will fix according to them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-30 15:43 UTC, boryspoplawski commented
Jenkins, test this please

2022-06-30 15:50 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-06-30 17:10 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/695)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-30 17:11 UTC, merged