[Pal] Move shared functions to Linux-common header
gramineproject/gramine pull request #697
Opened 2022-06-29 07:14 UTC by kailun-qin

`file_stat_type`, `file_attrcopy` and `is_dot_or_dotdot` are shared between
pal/linux and pal/linux-sgx, hence can be moved to Linux-common header.

Fixes https://github.com/gramineproject/gramine/issues/696

Signed-off-by: Kailun Qin <kailun.qin@intel.com>

2022-06-29 08:50 UTC, boryspoplawski requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ib3629GmUTpoUjwn2):*
`pal/linux` -> `Linux PAL`
`pal/linux-sgx` -> `Linux-SGX PAL`

Again, if you feel the proposed changes are fine you don't have to do anything, we can do it on the final rebase (when merging).
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5iauqZ4FAtebsAlG7S):*
This line should be removed (we do not link to GH issues in commit messages).
___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5ibjx_7SvAn9D1cvRa:b26mpov) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
> ```objc
> int get_gramine_unix_socket_addr(uint64_t instance_id, const char* name,
>                                  struct sockaddr_un* out_addr);
> ```

Please refrain from adding function implementation in headers, we do this very rarely when necessary (because missing LTO support in our codebase).
What about unifying `db_files.c` from both Linux PALs (like https://github.com/gramineproject/gramine/pull/433)? Or these files are too different and we would just move some functions like in this PR? If the latter then maybe just create a new `.c` file or append them to a existing one we have in Linux-common.
This is still not the time for a big Linux PALs consolidation (as we are changing repo layout / file names), but soon should be doable. 


<!-- Sent from Reviewable.io -->

2022-06-29 09:10 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ib3629GmUTpoUjwn2):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`pal/linux` -> `Linux PAL`
`pal/linux-sgx` -> `Linux-SGX PAL`

Again, if you feel the proposed changes are fine you don't have to do anything, we can do it on the final rebase (when merging).
</blockquote></details>

I'm fine w/ it. Thanks!
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5iauqZ4FAtebsAlG7S):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This line should be removed (we do not link to GH issues in commit messages).
</blockquote></details>

Got it. Pls also help do it
___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5ihIrzBf_EbgA--HmK:b-39qnsy) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please refrain from adding function implementation in headers, we do this very rarely when necessary (because missing LTO support in our codebase).
What about unifying `db_files.c` from both Linux PALs (like https://github.com/gramineproject/gramine/pull/433)? Or these files are too different and we would just move some functions like in this PR? If the latter then maybe just create a new `.c` file or append them to a existing one we have in Linux-common.
This is still not the time for a big Linux PALs consolidation (as we are changing repo layout / file names), but soon should be doable. 
</blockquote></details>

emm... I think we can definitely unify `db_files.c` more for both Linux PALs, but this needs more evaluation while doing something like https://github.com/gramineproject/gramine/pull/433 (later). Just saw this one on my team's task list so made a quick fix.
I'm fine w/ fixing this in the PAL consolidation.


<!-- Sent from Reviewable.io -->

2022-06-29 09:21 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5ikc2tC1iqPX3YFieF:b-7deqtj) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

emm... I think we can definitely unify `db_files.c` more for both Linux PALs, but this needs more evaluation while doing something like https://github.com/gramineproject/gramine/pull/433 (later). Just saw this one on my team's task list so made a quick fix.
I'm fine w/ fixing this in the PAL consolidation.
</blockquote></details>

Well, I'm fine with merging this before, but I dislike having these functions in header, feel like `pal/src/host/linux-common/file_utils.c` or a new file is a better place.
cc @dimakuv @mkow wdyt?


<!-- Sent from Reviewable.io -->

2022-06-29 15:43 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5k5Y1_4Q-tXJ1uVID4):*




_Suggestion:_
```
[PAL]
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5iauqZ4FAtebsAlG7S):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Got it. Pls also help do it
</blockquote></details>

Reason for this: We want to keep the git repo self-contained, in case we moved to another hosting someday.
___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5k7L20-7dylS38mITr:b8f4kud) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I'm fine with merging this before, but I dislike having these functions in header, feel like `pal/src/host/linux-common/file_utils.c` or a new file is a better place.
cc @dimakuv @mkow wdyt?
</blockquote></details>

Yeah, why not placing these in `pal/src/host/linux-common/file_utils.c`? Is there any downside of this?


<!-- Sent from Reviewable.io -->

2022-06-30 02:36 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5k5Y1_4Q-tXJ1uVID4):*
Done.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ib3629GmUTpoUjwn2):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'm fine w/ it. Thanks!
</blockquote></details>

Done.



_Code quote:_
```
[Pal] Move shared functions to Linux-common header
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5iauqZ4FAtebsAlG7S):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Reason for this: We want to keep the git repo self-contained, in case we moved to another hosting someday.
</blockquote></details>

Done.
___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5mLg16E-JRjyhy1oMU:b-r5ov3q) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, why not placing these in `pal/src/host/linux-common/file_utils.c`? Is there any downside of this?
</blockquote></details>

These are static inline functions. Do we really want to place them in `pal/src/host/linux-common/file_utils.c` and used multiple places?


<!-- Sent from Reviewable.io -->

2022-06-30 10:16 UTC, boryspoplawski reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-30 10:30 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "squash! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`pal/include/host/linux-common/linux_utils.h` line 51 at r1](https://reviewable.io/reviews/gramineproject/gramine/697#-N5ibjx_7SvAn9D1cvR_:-N5o8lBS47wOM1b4xApf:bion0w8) ([raw file](https://github.com/gramineproject/gramine/blob/e296d4e475f3a8aab4f005ffcce4a84bb6a844c4/pal/include/host/linux-common/linux_utils.h#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no problem in placing them to `pal/src/host/linux-common/file_utils.c`. I agree that they shouldn't be in the header file.

> These are static inline functions.

We should make them non-static non-inline then. No problem in that.
</blockquote></details>

Currently `pal/src/host/linux-common/file_utils.c` is designed for urts only: https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-common/meson.build#L7. It also includes some syscall dependencies. So place them directly into `file_utils.c` may incur some errors.


<!-- Sent from Reviewable.io -->

2022-06-30 11:18 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-30 11:23 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`pal/src/host/linux-common/file_utils_common.c` line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oLMni8ZEC7nRNLxev:-N5oLMni8ZEC7nRNLxew:b-ouivu) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/file_utils_common.c#L34)):*
> ```C
> bool is_dot_or_dotdot(const char* name) {
>     return (name[0] == '.' && !name[1]) || (name[0] == '.' && name[1] == '.' && !name[2]);
> }
> ```

Meh, this function doesn't belong to this "files info" source. Maybe just remove this function and inline its usages?
___
*[`pal/src/host/linux-common/meson.build` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oKaK-6WzLcClTE5A3:-N5oKaK-6WzLcClTE5A4:bb0zlvi) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/meson.build#L4)):*
> ```Meson
>     'bogomips.c',
>     'gramine_unix_socket_addr.c',
>     'file_utils_common.c',
> ```

But this list is for in-enclave-only files (in Linux-SGX PAL). At the same time, this file will be used in Linux PAL.

 So the name should be different. I suggest `file_info.c`.


<!-- Sent from Reviewable.io -->

2022-06-30 15:26 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/file_utils_common.c` line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oLMni8ZEC7nRNLxev:-N5pBQfd049hXoq1gybn:bg2ibf2) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/file_utils_common.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh, this function doesn't belong to this "files info" source. Maybe just remove this function and inline its usages?
</blockquote></details>

Well, direct inline might make the logic not readable...
___
*[`pal/src/host/linux-common/meson.build` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oKaK-6WzLcClTE5A3:-N5pBS2yB0rHgdQSNBVF:bi36jd1) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/meson.build#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this list is for in-enclave-only files (in Linux-SGX PAL). At the same time, this file will be used in Linux PAL.

 So the name should be different. I suggest `file_info.c`.
</blockquote></details>

Seems better, will do.


<!-- Sent from Reviewable.io -->

2022-07-01 07:42 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`pal/src/host/linux-common/file_utils_common.c` line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oLMni8ZEC7nRNLxev:-N5shAU1-JK315tizJ4-:b-i5pqwj) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/file_utils_common.c#L34)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Well, direct inline might make the logic not readable...
</blockquote></details>

I *strongly* dislike this function in this file.

I suggest to put it here: https://github.com/gramineproject/gramine/blob/master/common/src/path.c, and add its declaration to `api.h`. It is a general function that may be useful not only in PAL, but also in LibOS component, so it makes sense to move this function to "common".


<!-- Sent from Reviewable.io -->

2022-07-01 08:08 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`pal/src/host/linux-common/file_utils_common.c` line 34 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oLMni8ZEC7nRNLxev:-N5smmq91qoO3eoiNS6l:b-wpcjh6) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/file_utils_common.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I *strongly* dislike this function in this file.

I suggest to put it here: https://github.com/gramineproject/gramine/blob/master/common/src/path.c, and add its declaration to `api.h`. It is a general function that may be useful not only in PAL, but also in LibOS component, so it makes sense to move this function to "common".
</blockquote></details>

Thanks for the suggestion. Make great sense to me. Done.
___
*[`pal/src/host/linux-common/meson.build` line 4 at r3](https://reviewable.io/reviews/gramineproject/gramine/697#-N5oKaK-6WzLcClTE5A3:-N5smlDm9tXMVUTwISBE:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/31de909f67c5ee67527f99255864002f02c8c8de/pal/src/host/linux-common/meson.build#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Seems better, will do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-01 08:46 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-01 10:10 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`common/src/path.c` line 167 at r4](https://reviewable.io/reviews/gramineproject/gramine/697#-N5tE10ECGHAKTE9vWEb:-N5tE10ECGHAKTE9vWEc:bmev3qz) ([raw file](https://github.com/gramineproject/gramine/blob/ae6f107c81133c122f09da3213a7b7c1c4eeff16/common/src/path.c#L167)):*
> ```C
> }
> 
> bool is_dot_or_dotdot(const char* name) {
> ```

Since we make this function shared now, it would make sense to use it in LibOS as well. There are a few places doing `strcmp` with `.` and `..`.


<!-- Sent from Reviewable.io -->

2022-07-01 10:59 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`common/src/path.c` line 167 at r4](https://reviewable.io/reviews/gramineproject/gramine/697#-N5tE10ECGHAKTE9vWEb:-N5tP_s7EiMSxExG4qR7:by6eyol) ([raw file](https://github.com/gramineproject/gramine/blob/ae6f107c81133c122f09da3213a7b7c1c4eeff16/common/src/path.c#L167)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since we make this function shared now, it would make sense to use it in LibOS as well. There are a few places doing `strcmp` with `.` and `..`.
</blockquote></details>

@kailun-qin Do you think you could prepare such a follow-up PR (once this PR is merged)?


<!-- Sent from Reviewable.io -->

2022-07-01 11:03 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`common/src/path.c` line 167 at r4](https://reviewable.io/reviews/gramineproject/gramine/697#-N5tE10ECGHAKTE9vWEb:-N5tQSJs8V9DLkmcDNI5:b-eqyci5) ([raw file](https://github.com/gramineproject/gramine/blob/ae6f107c81133c122f09da3213a7b7c1c4eeff16/common/src/path.c#L167)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin Do you think you could prepare such a follow-up PR (once this PR is merged)?
</blockquote></details>

Sure, I can look into that.


<!-- Sent from Reviewable.io -->

2022-07-04 07:23 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`libos/src/fs/shim_fs.c` line 250 at r5](https://reviewable.io/reviews/gramineproject/gramine/697#-N5u0mR0BIYllIVoXmPm:-N674dtUDWew6CJ_wICk:b-l72h0) ([raw file](https://github.com/gramineproject/gramine/blob/5b44b739ce73bf4f35ba221d8a4b0da842e4582f/libos/src/fs/shim_fs.c#L250)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This is the only place where we have both `common_inc` and `common_dep`. There are other places like libos/test, pf_util using similar logic, but that would introduce common dependencies. Well, I'm not sure if that would fit the intention.
</blockquote></details>

Yes, let's touch only the LibOS source code. So nothing else to be replaced.


<!-- Sent from Reviewable.io -->

2022-07-04 13:09 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-05 23:12 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r1, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-05 23:15 UTC, mkow commented
Jenkins, retest this please

2022-07-05 23:16 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-06 00:07 UTC, boryspoplawski approved these changes
> Reviewed 5 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-06 06:38 UTC, dimakuv approved these changes
> Reviewed 5 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: all files reviewed, 1 unresolved discussion (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2022-07-06 06:39 UTC, dimakuv approved these changes
> Dismissed @kailun-qin from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/697)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 06:39 UTC, merged