[tests] Log timestamps within Python
gramineproject/gramine pull request #700
Opened 2022-06-29 14:29 UTC by NieDzejkob

## Description of the changes

In #632, I attempted to add log timestamps to the intermittently-failing tests (`fcntl14` and `fdatasync01`, for example). As we've later discovered (see discussion on #642), the approach of live-piping the output and having CI timestamp it is not viable, as `pytest-xdist` doesn't support running tests with stdout capture disabled.

Therefore I change the strategy to logging timestamps within Python while the output is being pumped around. Then the output gets printed, with the timestamps, when a test fails. This has the additional benefit of not having to list the problematic tests anywhere.

Closes #642.

## How to test this PR?

Try running a test with `-s` (e.g. `python3 -m pytest -v -k fcntl14 -s`, cf. [the docs on running LTP tests](https://gramine.readthedocs.io/en/latest/devel/contributing.html#ltp)), observe the timestamps getting added to the output.

2022-06-30 08:20 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @NieDzejkob)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/700#-N5ng-hM0CyEkJSu4Y0j):*
Please remove the commit hash, we just use commit one-liners. See also discussion in https://github.com/gramineproject/gramine/pull/695.

Can be done at final rebase.


<!-- Sent from Reviewable.io -->

2022-06-30 11:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-06-30 11:59 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/700#-N5oTl7g0zHg82Y7zMy-:-N5oTl7g0zHg82Y7zMy0:b-uv014k) (no related file):*
Jenkins failed

___


<!-- Sent from Reviewable.io -->

2022-06-30 12:06 UTC, NieDzejkob reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/700#-N5oTl7g0zHg82Y7zMy-:-N5oVAmb3YG7RgA1Kz9k:b-hgvqch) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Jenkins failed
</blockquote></details>

It failed because busybox.net was down at the time. Can we do something to not download those during CI on each run?

___


<!-- Sent from Reviewable.io -->

2022-06-30 12:20 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/700#-N5oTl7g0zHg82Y7zMy-:-N5oYVD6Dqkseo0VdEmx:b-s5gqsq) (no related file):*
> It failed because busybox.net was down at the time.

But we have a fallback for our own site, which should not be down. 

___


<!-- Sent from Reviewable.io -->

2022-06-30 12:37 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/700#-N5oTl7g0zHg82Y7zMy-:-N5obGOa1UFCwU2-XzhA:by2rl46) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> It failed because busybox.net was down at the time.

But we have a fallback for our own site, which should not be down. 
</blockquote></details>

https://github.com/gramineproject/gramine/pull/710 should fix this issue - it was too many retries per host

___


<!-- Sent from Reviewable.io -->

2022-06-30 12:37 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-18.04-apps please (download timeout)

2022-06-30 13:28 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-07-01 08:08 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @NieDzejkob)



<!-- Sent from Reviewable.io -->

2022-07-01 08:13 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/gramineproject/gramine/700#-N5ng-hM0CyEkJSu4Y0j):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the commit hash, we just use commit one-liners. See also discussion in https://github.com/gramineproject/gramine/pull/695.

Can be done at final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-01 08:47 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/700)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-01 11:53 UTC, merged