modify to log_debug inside init_stack function
gramineproject/gramine pull request #707
Opened 2022-06-30 08:43 UTC by billionairiam

## Description of the changes 
At the start, Gramine often outputs allocating stack at 0

## How to test this PR? 
Now the log work correctly!

debug: Gramine was built from commit: 1.2post-UNRELEASED
debug: Host: Linux
debug: LibOS xsave_enabled 1, xsave_size 0x440(1088), xsave_features 0x1f
debug: Initial VMA region 0x7ffff3efd000-0x7ffff3fd1000 (LibOS) bookkeeped
debug: Initial VMA region 0x7ffff3fd2000-0x7ffff7fd2000 (pal_init_pool) bookkeeped
debug: Initial VMA region 0x7ffff7fd6000-0x7ffff7fd8000 (vdso) bookkeeped
debug: Initial VMA region 0x7ffff7fd2000-0x7ffff7fd6000 (vvar) bookkeeped
debug: Initial VMA region 0x7ffff3fd1000-0x7ffff3fd2000 (pal_internal_me) bookkeeped
debug: ASLR top address adjusted to 0x42ef1b19e000
debug: Shim loaded at 0x7ffff3efd000, ready to initialize
debug: mounting "file:." (chroot) under /
debug: mounting "proc" (pseudo) under /proc
debug: mounting "dev" (pseudo) under /dev
debug: mounting "dev:tty" (chroot) under /dev/tty
debug: mounting "sys" (pseudo) under /sys
debug: Creating pipe: pipe.srv:62816d9b5911aa3bca1594124e44c1b5f3a4b4c9d0193259f485c3fc72868321
[P1:T1:] debug: mounting "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib
[P1:T1:helloworld] debug: Creating pipe: pipe.srv:daf39d5d89be1d966e8a2ccd5c1b3e4def8083bbd12531bcb1ce1e275e922f07
**[P1:T1:helloworld] debug: Allocating stack at 0x42ef1b15e000 (size = 262144)**
[P1:T1:helloworld] debug: loading "file:./helloworld"
[P1:T1:helloworld] debug: append_r_debug: adding file:./helloworld at 0x42ef1b158000
[P1:T1:helloworld] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:helloworld] debug: loading "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:helloworld] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2 at 0x42ef1b11f000
[P1:T1:helloworld] debug: Creating pipe: pipe.srv:1
[P1:T1:helloworld] debug: Creating pipe: pipe.srv:78dfd182bac10f1da10e6cc7616b1ecf5e8abdeb0f3aec65671b02c35bd0e3f9
[P1:T1:helloworld] debug: LibOS initialized
[P1:T1:helloworld] debug: append_r_debug: adding file:[vdso_libos] at 0x42ef1b11e000
[P1:shim] debug: IPC worker started
[P1:T1:helloworld] warning: Not supported flag (0x3001) passed to arch_prctl
[P1:T1:helloworld] debug: glibc register library /lib/libc.so.6 loaded at 0x42ef1af22000
[P1:T1:helloworld] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libc.so.6 at 0x42ef1af22000
[P1:T1:helloworld] warning: Unsupported system call rseq
Hello, world
[P1:T1:helloworld] debug: ---- shim_exit_group (returning 0)
[P1:T1:helloworld] debug: clearing POSIX locks for pid 1
[P1:T1:helloworld] debug: sync client shutdown: closing handles
[P1:T1:helloworld] debug: sync client shutdown: waiting for confirmation
[P1:T1:helloworld] debug: sync client shutdown: finished
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:helloworld] debug: process 1 exited with status 0

2022-06-30 12:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nv1yA12NF0kQQcOXX:-N5obftr4jTkjflYXuN0:b415wn8) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And overall, @billionairiam: please read the whole https://gramine.readthedocs.io/en/latest/devel/contributing.html carefully before contributing.
</blockquote></details>

And: https://gramine.readthedocs.io/en/latest/devel/onboarding.html

___


<!-- Sent from Reviewable.io -->

2022-07-01 07:41 UTC, guzongmin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5sgAeY7sByH8Gp16w3:-N5sgAeY7sByH8Gp16w4:bbe6dfu) (no related file):*
In the current modification, the log would be printed only when the stack is successfully allocated. Is it reasonable to print something in the error path? (Maybe the error would be printed after the function return. I am not sure. Just a suggestion.)  

___


<!-- Sent from Reviewable.io -->

2022-07-01 08:06 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @billionairiam and @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5sgAeY7sByH8Gp16w3:-N5smLK4BTjfKykOe4J7:brrfyty) (no related file):*
<details><summary><i>Previously, guzongmin (Zongmin.Gu) wrote…</i></summary><blockquote>

In the current modification, the log would be printed only when the stack is successfully allocated. Is it reasonable to print something in the error path? (Maybe the error would be printed after the function return. I am not sure. Just a suggestion.)  
</blockquote></details>

The error will be printed on function return, in one of the caller functions. Also, the only error that can happen is out-of-memory (`ENOMEM`), which is almost impossible to happen at initialization time. So I wouldn't bother adding a print on the error path.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5smsLb3e3hweRQ613n:-N5smsLb3e3hweRQ613o:b-8x2pv8) (no related file):*
@billionairiam Please use Reviewable to have discussions and also **mark your modifications**. Reviewers need to know that you finished with your changes, which you need to mark as "Done" in Reviewable.

___
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N5smjJIE2RaWGAouiYV):*
Please read our Contributing guide and use proper git fixup commits in the future.


<!-- Sent from Reviewable.io -->

2022-07-04 01:50 UTC, billionairiam reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv and @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5sgAeY7sByH8Gp16w3:-N65t1JH72soVr0bn4-Z:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The error will be printed on function return, in one of the caller functions. Also, the only error that can happen is out-of-memory (`ENOMEM`), which is almost impossible to happen at initialization time. So I wouldn't bother adding a print on the error path.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5smsLb3e3hweRQ613n:-N65t0gP1rOF0XoCQfFh:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@billionairiam Please use Reviewable to have discussions and also **mark your modifications**. Reviewers need to know that you finished with your changes, which you need to mark as "Done" in Reviewable.
</blockquote></details>

Done.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nvscw04DK5BHTXzlC):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please read our guidelines: https://gramine.readthedocs.io/en/latest/devel/contributing.html

In particular, the part about commit messages: https://gramine.readthedocs.io/en/latest/devel/contributing.html#reviewing-guidelines
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nw3K68_l4uWHanphN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest the commit title
```
[LibOS] Move "Allocated stack" log message to after `allocate_stack()`
```
</blockquote></details>

Done.
___
*[`libos/src/shim_init.c` line 301 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nvWZH1shHtMfsx6a1:-N65tUfREVbNj8EzLUGK:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53a5fec4ad774e3c0757c7b85b2ec9ec39a7e126/libos/src/shim_init.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can this compile? You don't have the `size` variable, you only have `stack_size` variable.
</blockquote></details>

Done.
___
*[`libos/src/shim_init.c` line 301 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nvbRS3-x22m3yz4dI:-N65tW__D86igv7OJv_d:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53a5fec4ad774e3c0757c7b85b2ec9ec39a7e126/libos/src/shim_init.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It doesn't make sense to have this message here. Please move to after the check for `ENOMEM`. So I suggest like this:
```
    void* stack = allocate_stack(stack_size, ALLOC_ALIGNMENT, /*user=*/true);
    if (!stack)
        return -ENOMEM;

    log_debug("Allocated stack at %p (size = %ld)", stack, size);
```

Also note that I changed `Allocating` -> `Allocated`.
</blockquote></details>

Done.
___
*[`libos/src/shim_init.c` line 302 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nvBLO6SzdD1k_Jb_j:-N65tBtB0GrqdWjUNPgl:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/53a5fec4ad774e3c0757c7b85b2ec9ec39a7e126/libos/src/shim_init.c#L302)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the whitespace. You accidentally added 4 spaces here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 06:40 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @dimakuv and @guzongmin)



<!-- Sent from Reviewable.io -->

2022-07-04 06:40 UTC, dimakuv commented
Jenkins, test this please

2022-07-04 15:28 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @billionairiam, @dimakuv, and @guzongmin)

___
*[`libos/src/shim_init.c` line 303 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N68ojupA8h9KmhH1EEn:-N68ojupA8h9KmhH1EEo:b-jirts) ([raw file](https://github.com/gramineproject/gramine/blob/a99da8ade48cc2ffa573d02b8823c931449e0549/libos/src/shim_init.c#L303)):*
> ```C
>         return -ENOMEM;
> 
>     log_debug("Allocated stack at %p (size = %ld)", stack, stack_size);
> ```

Could we have the size printed in hexadecimal too? like `%#lx`


<!-- Sent from Reviewable.io -->

2022-07-05 00:55 UTC, billionairiam commented
> > Reviewed 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)_ status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), period found at the end of a one-liner (waiting on @billionairiam, @dimakuv, and @guzongmin)
> 
> _[`libos/src/shim_init.c` line 303 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N68ojupA8h9KmhH1EEn:-N68ojupA8h9KmhH1EEo:b-jirts) ([raw file](https://github.com/gramineproject/gramine/blob/a99da8ade48cc2ffa573d02b8823c931449e0549/libos/src/shim_init.c#L303)):_
> 
> > ```c
> >         return -ENOMEM;
> > 
> >     log_debug("Allocated stack at %p (size = %ld)", stack, stack_size);
> > ```
> 
> Could we have the size printed in hexadecimal too? like `%#lx`

For consistency with source code, I think we don't need do that.

2022-07-05 06:52 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "Merge branch '" found in commit messages' one-liners (waiting on @billionairiam, @boryspoplawski, @dimakuv, and @guzongmin)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/707#-N6C6ahk4ohhv24oBthg):*
What is this? Please never use `git merge`. Gramine development uses the `git rebase` model, and we do rebases **only after all reviews are done**. Please see https://gramine.readthedocs.io/en/stable/devel/contributing.html and https://gramine.readthedocs.io/en/stable/devel/onboarding.html

The reasoning: you're making the life of reviewers harder. Now I as a reviewer need to review this PR from the beginning, because the name of the file changed. The rule is simple: stay on the same base commit, do not merge the master and do not rebase, and use `git commit --fixup` to produce fixup commits.

You can observe other PRs in the Gramine repo and pay attention how authors use fixup commits.
___
*[`libos/src/shim_init.c` line 303 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N68ojupA8h9KmhH1EEn:-N6C6uk589QZG_jlLDW2:bwxa9a0) ([raw file](https://github.com/gramineproject/gramine/blob/a99da8ade48cc2ffa573d02b8823c931449e0549/libos/src/shim_init.c#L303)):*
<details><summary><i>Previously, billionairiam wrote…</i></summary><blockquote>

For consistency with source code, I think we don't need do that.
</blockquote></details>

@billionairiam What do you mean? For consistency with which code? I think it's a reasonable request from Borys.


<!-- Sent from Reviewable.io -->

2022-07-05 07:18 UTC, billionairiam commented
> > Reviewed 2 of 2 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)_ status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "Merge branch '" found in commit messages' one-liners (waiting on @billionairiam, @boryspoplawski, @dimakuv, and @guzongmin)
> 
> _[`-- commits` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/707#-N6C6ahk4ohhv24oBthg):_ What is this? Please never use `git merge`. Gramine development uses the `git rebase` model, and we do rebases **only after all reviews are done**. Please see https://gramine.readthedocs.io/en/stable/devel/contributing.html and https://gramine.readthedocs.io/en/stable/devel/onboarding.html
> 
> The reasoning: you're making the life of reviewers harder. Now I as a reviewer need to review this PR from the beginning, because the name of the file changed. The rule is simple: stay on the same base commit, do not merge the master and do not rebase, and use `git commit --fixup` to produce fixup commits.
> 
> You can observe other PRs in the Gramine repo and pay attention how authors use fixup commits.
> 
> _[`libos/src/shim_init.c` line 303 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N68ojupA8h9KmhH1EEn:-N6C6uk589QZG_jlLDW2:bwxa9a0) ([raw file](https://github.com/gramineproject/gramine/blob/a99da8ade48cc2ffa573d02b8823c931449e0549/libos/src/shim_init.c#L303)):_
> 
> Previously, billionairiam wrote…
> @billionairiam What do you mean? For consistency with which code? I think it's a reasonable request from Borys.

Many logs print the size information use `%ld` , I didn't found a size variable printed in hexadecima from the source code.

2022-07-05 07:39 UTC, billionairiam commented
> > Reviewed 2 of 2 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)_ status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "Merge branch '" found in commit messages' one-liners (waiting on @billionairiam, @boryspoplawski, @dimakuv, and @guzongmin)
> 
> _[`-- commits` line 13 at r3](https://reviewable.io/reviews/gramineproject/gramine/707#-N6C6ahk4ohhv24oBthg):_ What is this? Please never use `git merge`. Gramine development uses the `git rebase` model, and we do rebases **only after all reviews are done**. Please see https://gramine.readthedocs.io/en/stable/devel/contributing.html and https://gramine.readthedocs.io/en/stable/devel/onboarding.html
> 
> The reasoning: you're making the life of reviewers harder. Now I as a reviewer need to review this PR from the beginning, because the name of the file changed. The rule is simple: stay on the same base commit, do not merge the master and do not rebase, and use `git commit --fixup` to produce fixup commits.
> 
> You can observe other PRs in the Gramine repo and pay attention how authors use fixup commits.
> 
> _[`libos/src/shim_init.c` line 303 at r2](https://reviewable.io/reviews/gramineproject/gramine/707#-N68ojupA8h9KmhH1EEn:-N6C6uk589QZG_jlLDW2:bwxa9a0) ([raw file](https://github.com/gramineproject/gramine/blob/a99da8ade48cc2ffa573d02b8823c931449e0549/libos/src/shim_init.c#L303)):_
> 
> Previously, billionairiam wrote…
> @billionairiam What do you mean? For consistency with which code? I think it's a reasonable request from Borys.

You are right, Basically the size that needs to be aligned is should be printed in hexadecimal.

2022-07-05 08:09 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "Merge branch '" and "fixup! " found in commit messages' one-liners (waiting on @billionairiam, @boryspoplawski, @dimakuv, and @guzongmin)



<!-- Sent from Reviewable.io -->

2022-07-05 12:36 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 2 unresolved discussions, "Merge branch '" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @guzongmin)



<!-- Sent from Reviewable.io -->

2022-07-05 12:49 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @guzongmin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nw3K68_l4uWHanphN):*
<details><summary><i>Previously, billionairiam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-05 12:57 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 1 unresolved discussion (waiting on @guzongmin)



<!-- Sent from Reviewable.io -->

2022-07-05 12:58 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 2 unresolved discussions (waiting on @billionairiam and @guzongmin)

___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/707#-N6DR5QSC8db5JvgqDUB):*
We need this to be added by the author, cannot do this ourselves (even if we are sure it's true)


<!-- Sent from Reviewable.io -->

2022-07-06 01:10 UTC, billionairiam reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @guzongmin)

___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/gramineproject/gramine/707#-N6DR5QSC8db5JvgqDUB):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need this to be added by the author, cannot do this ourselves (even if we are sure it's true)
</blockquote></details>

I acknowledge the use of this signed-off-by line


<!-- Sent from Reviewable.io -->

2022-07-06 01:11 UTC, billionairiam reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @guzongmin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nw3K68_l4uWHanphN):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I acknowledge the use of this signed-off-by line


<!-- Sent from Reviewable.io -->

2022-07-06 01:22 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 1 unresolved discussion (waiting on @guzongmin)



<!-- Sent from Reviewable.io -->

2022-07-06 01:27 UTC, billionairiam reviewed
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, 1 unresolved discussion (waiting on @guzongmin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/707#-N5nv1yA12NF0kQQcOXX:-N6G6_N62P6UlQ6Fb0qj:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And: https://gramine.readthedocs.io/en/latest/devel/onboarding.html
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-06 03:55 UTC, guzongmin reviewed
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 06:41 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 06:59 UTC, dimakuv commented
Jenkins, test this please

2022-07-06 06:59 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-07-06 11:54 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 12:25 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/707)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 12:32 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please

2022-07-06 12:53 UTC, merged