[PAL/Linux-SGX] Set pipe handle as nonblocking only after TLS handshake
gramineproject/gramine pull request #715
Opened 2022-07-01 09:03 UTC by boryspoplawski

## Description of the changes 
Linux SGX PAL pipes are encrypted using TLS. This requires performing a handshake when they are created. If the pipe is to be nonblocking, we make it so only after the handshake, not to waste time on send/recv ocalls returning `EAGAIN` (no data on nonblocking fd).

2022-07-01 10:03 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 178 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tBpOOCxXEm_WaSNUe:-N5tBpOOCxXEm_WaSNUf:b-86lc1m) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L178)):*
> ```C
>         return -PAL_ERROR_DENIED;
> 
>     assert(WITHIN_MASK(options, PAL_OPTION_NONBLOCK | PAL_OPTION_CLOEXEC));
> ```

Hm, if you're adding this assert, then you should add it to all funcs in this file...
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tC8Ix488-wt1ECs5w:-N5tC8Ix488-wt1ECs5x:b-2unuv7) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L182)):*
> ```C
>     /* We do not take `nonblocking` into account here - it will be set after the TLS handshake below
>      * if needed. */
>     int ret = ocall_accept(handle->pipe.fd, /*addr=*/NULL, /*addrlen=*/NULL, SOCK_CLOEXEC);
> ```

Why do you unconditionally add `SOCK_CLOEXEC`?
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 222 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tCWI5Aut9_o32MMIR:-N5tCWI5Aut9_o32MMIS:blfbq2x) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L222)):*
> ```C
>         if (ret < 0) {
>             log_error("Failed to set handle as non-blocking: %d", ret);
>             _PalProcessExit(1);
> ```

You shouldn't kill the process here, but instead
```
        ocall_close(clnt->pipe.fd);
        free(clnt);
        return unix_to_pal_error(ret);
```

Actually, since you're modifying this, then it makes sense to introduce `goto out` in this func.


<!-- Sent from Reviewable.io -->

2022-07-01 11:11 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 178 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tBpOOCxXEm_WaSNUe:-N5tRkZv7y6s_79m-bE5:b-z1znmo) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L178)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But... why?
</blockquote></details>

For uniformity. You added here but not added to `pipe_connect()` -- even though you modified that function as well.
___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 182 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tC8Ix488-wt1ECs5w:-N5tS5cG6eNWMNpRPeH8:b-vjy6cc) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We do that for all fds
</blockquote></details>

Ok, now I see that.


<!-- Sent from Reviewable.io -->

2022-07-01 11:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 178 at r2](https://reviewable.io/reviews/gramineproject/gramine/715#-N5tBpOOCxXEm_WaSNUe:-N5t_3Jm9Ju2VNTFUsyd:bow38sw) ([raw file](https://github.com/gramineproject/gramine/blob/c9927abd3f11dcf37784dd938246a467f5492b2e/pal/src/host/linux-sgx/pal_pipes.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity. You added here but not added to `pipe_connect()` -- even though you modified that function as well.
</blockquote></details>

Because this function assumed that (due to `PAL_OPTION_TO_LINUX_OPEN`) and others did not.
Anyway added.


<!-- Sent from Reviewable.io -->

2022-07-01 11:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-07 14:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 182 at r4](https://reviewable.io/reviews/gramineproject/gramine/715#-N6O4UZD5gsFI2xyn8xp:-N6O4UZD5gsFI2xyn8xq:b-6vezw7) ([raw file](https://github.com/gramineproject/gramine/blob/86ccc429d3a91673b0d359daf8877896424445a8/pal/src/host/linux-sgx/pal_pipes.c#L182)):*
> ```C
>     /* We do not take `nonblocking` into account here - it will be set after the TLS handshake below
>      * if needed. */
>     int ret = ocall_accept(handle->pipe.fd, /*addr=*/NULL, /*addrlen=*/NULL, SOCK_CLOEXEC);
> ```

Hmm, you now ignore whether `PAL_OPTION_CLOEXEC` was set or not. Why? It's also not mentioned in the commit message, was this change even intended?



_Code quote:_
```C
SOCK_CLOEXEC
```


<!-- Sent from Reviewable.io -->

2022-07-07 15:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 182 at r4](https://reviewable.io/reviews/gramineproject/gramine/715#-N6O4UZD5gsFI2xyn8xp:-N6OA69r77kdS7BW8AGb:bq5prpj) ([raw file](https://github.com/gramineproject/gramine/blob/86ccc429d3a91673b0d359daf8877896424445a8/pal/src/host/linux-sgx/pal_pipes.c#L182)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, you now ignore whether `PAL_OPTION_CLOEXEC` was set or not. Why? It's also not mentioned in the commit message, was this change even intended?
</blockquote></details>

1. You can see a closed discussion at this line
2. Yes it was intentional

We always set `X_CLOEXEC` on all fds. `PAL_OPTION_CLOEXEC` is useless - we always send all fds to the child process via checkpointing. I have removing this on my TODO list, we even talked about it already. I'm just waiting for all the repo renames to be submitted and merged (which will happend ~soon) and I'll create a PR removing it.


<!-- Sent from Reviewable.io -->

2022-07-07 15:12 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`pal/src/host/linux-sgx/pal_pipes.c` line 182 at r4](https://reviewable.io/reviews/gramineproject/gramine/715#-N6O4UZD5gsFI2xyn8xp:-N6OCoaZ3jHwTTNVEIR0:b-bcik8v) ([raw file](https://github.com/gramineproject/gramine/blob/86ccc429d3a91673b0d359daf8877896424445a8/pal/src/host/linux-sgx/pal_pipes.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. You can see a closed discussion at this line
2. Yes it was intentional

We always set `X_CLOEXEC` on all fds. `PAL_OPTION_CLOEXEC` is useless - we always send all fds to the child process via checkpointing. I have removing this on my TODO list, we even talked about it already. I'm just waiting for all the repo renames to be submitted and merged (which will happend ~soon) and I'll create a PR removing it.
</blockquote></details>

Ah, right. We need to finally remove this option, it's confusing me each time I see it.


<!-- Sent from Reviewable.io -->

2022-07-08 21:29 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/715)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-08 21:54 UTC, merged