[LibOS] Add seek/tell/truncate test
gramineproject/gramine pull request #718
Opened 2022-07-01 11:35 UTC by oshogbo

## Description of the changes 

The goal of this test is to verify that Gramine doesn't change file offset after truncation.

## How to test this PR? 

This is a test.
```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```

2022-07-01 12:05 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`libos/test/fs/meson.build` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/718#-N5tdQxu1jcxZuuMuISJ:-N5tdQxu1jcxZuuMuISK:ba981vc) ([raw file](https://github.com/gramineproject/gramine/blob/43d6a30109ed1f796b3b7530828bb5401089cee1/libos/test/fs/meson.build#L46)):*
> ```Meson
>     'read_write': {},
>     'seek_tell': {},
>     'seek_tell_truncate': {},
> ```

Do we need another test? Can't we augment `seek_tell`? I haven't looked at both tests, so I have no idea, please check :)


<!-- Sent from Reviewable.io -->

2022-07-01 12:13 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[`libos/test/fs/meson.build` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/718#-N5tdQxu1jcxZuuMuISJ:-N5teCbm0yFZfP-TKaN2:bs9itbl) ([raw file](https://github.com/gramineproject/gramine/blob/43d6a30109ed1f796b3b7530828bb5401089cee1/libos/test/fs/meson.build#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need another test? Can't we augment `seek_tell`? I haven't looked at both tests, so I have no idea, please check :)
</blockquote></details>

I think `seek_tell` is a little bit different "type" of test.
First of all `seek_tell_truncate` doesn't depend on the external files, it creates one. (Which IRC was your suggestion).
This test also run multiple times with different arguments, where to seek, how large chunk truncate and so on.
IMHO I would keep them separated.


<!-- Sent from Reviewable.io -->

2022-07-04 08:00 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`libos/test/fs/meson.build` line 46 at r1](https://reviewable.io/reviews/gramineproject/gramine/718#-N5tdQxu1jcxZuuMuISJ:-N67DFpQ8TwrdOWjMxMk:b-1zrhfj) ([raw file](https://github.com/gramineproject/gramine/blob/43d6a30109ed1f796b3b7530828bb5401089cee1/libos/test/fs/meson.build#L46)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think `seek_tell` is a little bit different "type" of test.
First of all `seek_tell_truncate` doesn't depend on the external files, it creates one. (Which IRC was your suggestion).
This test also run multiple times with different arguments, where to seek, how large chunk truncate and so on.
IMHO I would keep them separated.
</blockquote></details>

I agree with @oshogbo, the tests are too different. `seek_tell` looks like this: https://github.com/gramineproject/gramine/blob/master/libos/test/fs/seek_tell.c
___
*[`libos/test/fs/seek_tell_truncate.c` line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67Bi4u1gHf8DZ_cEl7:-N67Bi4u1gHf8DZ_cEl8:bkbohs1) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/seek_tell_truncate.c#L39)):*
> ```C
> 
>     pos = tell_fd(path, fd);
>     printf("tell(%s) output position OK: %zd\n", path, pos);
> ```

You have three identical messages about `tell()`, differing only in the `pos` number. Maybe add some distinction, like `first tell(%s)`, `second tell(%s)`, ... ?

Otherwise if `file_pos == file_truncate` in some test, then Python's `assertIn` will just work on the first-found message.
___
*[`libos/test/fs/test_fs.py` line 243 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67AZ6d9A4cfYg6DX-o:-N67AZ6d9A4cfYg6DX-p:ba48l3f) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L243)):*
> ```Python
>         self.do_truncate_test(65537, 65536)
> 
>     def verify_seek_teel_truncate(self, file_out, file_size, file_pos, file_truncate):
> ```

`teel` -> `tell`
___
*[`libos/test/fs/test_fs.py` line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67AIcT9CL9gCrZF8WB:-N67AIcT9CL9gCrZF8WC:b-fhpgl4) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L264)):*
> ```Python
>         self.assertIn(f"close({file_out}) OK", stdout)
> 
>     def test_141_file_seek_tell_truncate(self):
> ```

Why not put this test right-after `seek_tell` test: https://github.com/gramineproject/gramine/blob/3f7f4d04736dd0891d421777f906070c51ad2a70/libos/test/fs/test_fs.py#L147

We even have an unused range of numbers that we can assign to the test: `test_116_file_seek_tell_truncate`
___
*[`libos/test/fs/test_fs.py` line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67Cnq2BGpxOa385bEr:-N67Cnq3E6HXJpEMIF0r:b4f4tkn) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L269)):*
> ```Python
>         self.verify_seek_teel_truncate(f"{file_path}a", 0, 0, 100)
>         self.verify_seek_teel_truncate(f"{file_path}b", 512, 512, 0)
>         self.verify_seek_teel_truncate(f"{file_path}c", 512, 256, 0)
> ```

I'd prefer these two "truncate to zero" tests to be moved after "truncate to 65536" -- this way your `XXX` comment will make more sense.


<!-- Sent from Reviewable.io -->

2022-07-04 11:26 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[`libos/test/fs/seek_tell_truncate.c` line 39 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67Bi4u1gHf8DZ_cEl7:-N67tIBL9M4BNIm9viOv:bu32q95) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/seek_tell_truncate.c#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have three identical messages about `tell()`, differing only in the `pos` number. Maybe add some distinction, like `first tell(%s)`, `second tell(%s)`, ... ?

Otherwise if `file_pos == file_truncate` in some test, then Python's `assertIn` will just work on the first-found message.
</blockquote></details>

Oh, thats a good point. Thank you.
___
*[`libos/test/fs/test_fs.py` line 243 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67AZ6d9A4cfYg6DX-o:-N67tHY9ERZh8ndlp1FO:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`teel` -> `tell`
</blockquote></details>

Done.
___
*[`libos/test/fs/test_fs.py` line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67AIcT9CL9gCrZF8WB:-N67tQC871hAyzosqRKl:b-ox1769) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L264)):*
> test_116_file_seek_tell_truncate

If I understand correctly, these numbers define the order of execution.
So my idea was that we wanted to test first seek/tell, then truncate, and finally, seek/tell/truncate.
But I don't have a strong opinion here.
___
*[`libos/test/fs/test_fs.py` line 269 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67Cnq2BGpxOa385bEr:-N67tkh-9-ZwvrcIYqVi:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer these two "truncate to zero" tests to be moved after "truncate to 65536" -- this way your `XXX` comment will make more sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 11:29 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[`libos/test/fs/test_fs.py` line 264 at r2](https://reviewable.io/reviews/gramineproject/gramine/718#-N67AIcT9CL9gCrZF8WB:-N67yHwD1t7yqdeVsyTk:bk6ps7m) ([raw file](https://github.com/gramineproject/gramine/blob/40e9c510cb6d5ab931d11feb0ca3c6924630c3de/libos/test/fs/test_fs.py#L264)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> test_116_file_seek_tell_truncate

If I understand correctly, these numbers define the order of execution.
So my idea was that we wanted to test first seek/tell, then truncate, and finally, seek/tell/truncate.
But I don't have a strong opinion here.
</blockquote></details>

Ah, I see your logic now. Makes sense. Resolving this comment.


<!-- Sent from Reviewable.io -->

2022-07-04 15:53 UTC, boryspoplawski requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/seek_tell_truncate.c` line 5 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68sOMZ0PXe79UGGOza:-N68sOMZ0PXe79UGGOzb:bm4c6ra) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L5)):*
> ```C
> #define CHUNK_SIZE 512
> 
> static void setup_files(const char* path, size_t size) {
> ```

It sets up one file, so should be singular form?
___
*[`libos/test/fs/seek_tell_truncate.c` line 12 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68uBhJBUAA4AwxCFBX:-N68uBhJBUAA4AwxCFBY:b-vtikn) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L12)):*
> ```C
>     write_fd(path, fd, buf, size);
> 
>     close_fd(path, fd);
> ```

free of `buf` missing
___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N68stsg0TYJ1TDN7nQi:b9gtpdk) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
> ```C
> }
> 
> static void seek_truncate(const char* path, size_t file_pos, size_t file_truncate) {
> ```

I don't find all the printfs in this function that useful, you might consider removing them (but I do not insist)
___
*[`libos/test/fs/seek_tell_truncate.c` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68soUHBkm43xsq7V69:-N68soUHBkm43xsq7V6A:b4a63i9) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L23)):*
> ```C
> 
>     off_t pos = tell_fd(path, fd);
>     printf("first tell(%s) output position OK: %zd\n", path, pos);
> ```

Please check that `pos` matches the requested `file_pos`
___
*[`libos/test/fs/seek_tell_truncate.c` line 26 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tdXvDzWaUOg_hFLP:-N68tdXvDzWaUOg_hFLQ:b-1jvzo1) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L26)):*
> ```C
> 
>     if (ftruncate(fd, file_truncate) != 0) {
>         fatal_error("Failed to truncate file %s to %zd: %s\n", path, file_truncate,
> ```

`zd` -> `zu`
___
*[`libos/test/fs/seek_tell_truncate.c` line 27 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tROS2c34KXO17wVc:-N68tROTDGt-c9-QO_9W:bakgoup) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L27)):*
> ```C
>     if (ftruncate(fd, file_truncate) != 0) {
>         fatal_error("Failed to truncate file %s to %zd: %s\n", path, file_truncate,
>                     strerror(errno));
> ```

You can just use `%m` instead
___
*[`libos/test/fs/seek_tell_truncate.c` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tGct1c4Py4uY6fLa:-N68tGcuCPJUQJo6UuGj:b-qbnmnn) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L32)):*
> ```C
> 
>     pos = tell_fd(path, fd);
>     printf("second tell(%s) output position OK: %zd\n", path, pos);
> ```

Please check that `pos` matches what's exepcted
___
*[`libos/test/fs/seek_tell_truncate.c` line 36 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68uIrRCDm0ygibvZwP:-N68uIrS-hLvHOqakVG-:b-4thuul) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L36)):*
> ```C
>     void* buf = alloc_buffer(CHUNK_SIZE);
>     fill_random(buf, CHUNK_SIZE);
>     write_fd(path, fd, buf, CHUNK_SIZE);
> ```

`buf` not freed
___
*[`libos/test/fs/seek_tell_truncate.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tqa6ES49s_MqZLOL:-N68tqa6ES49s_MqZLOM:b-z16w21) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L39)):*
> ```C
> 
>     pos = tell_fd(path, fd);
>     printf("third tell(%s) output position OK: %zd\n", path, pos);
> ```

ditto (verify `pos`)
___
*[`libos/test/fs/test_fs.py` line 256 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68sapP4QYk-yHvISeU:-N68sapP4QYk-yHvISeV:b295ils) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/test_fs.py#L256)):*
> ```Python
> 
>         self.assertNotIn('ERROR: ', stderr)
>         self.assertIn(f"open({file_out}) output OK", stdout)
> ```

What's the point of checking these messages here? The test itself should detect potential errors and quit with error.


<!-- Sent from Reviewable.io -->

2022-07-04 18:58 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N69ZERz6enYiT5Me7a_:b-1lmmox) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

For what I understand other tests, the idea is to print each step, and the verification happens in python.
</blockquote></details>

But why, what's the point if we can simply verify it here and have the test self contained instead of split between two different parts.
___
*[`libos/test/fs/seek_tell_truncate.c` line 24 at r4](https://reviewable.io/reviews/gramineproject/gramine/718#-N69ZYJZ3AznYK5sk49s:-N69ZYJZ3AznYK5sk49t:b-dlnfsg) ([raw file](https://github.com/gramineproject/gramine/blob/2a64a2d3b63706d20425ffb0d618a60aee8222a5/libos/test/fs/seek_tell_truncate.c#L24)):*
> ```C
> 
>     off_t pos = tell_fd(path, fd);
>     printf("first tell(%s) output position OK: %zu\n", path, pos);
> ```

This change is wrong, `off_t` is signed
___
*[`libos/test/fs/seek_tell_truncate.c` line 32 at r4](https://reviewable.io/reviews/gramineproject/gramine/718#-N69ZlS-EVYhMNrMnIxn:-N69ZlS-EVYhMNrMnIxo:b-7ropln) ([raw file](https://github.com/gramineproject/gramine/blob/2a64a2d3b63706d20425ffb0d618a60aee8222a5/libos/test/fs/seek_tell_truncate.c#L32)):*
> ```C
> 
>     pos = tell_fd(path, fd);
>     printf("second tell(%s) output position OK: %zu\n", path, pos);
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-07-04 19:01 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N69_Y12-md7ASNdP_Z_:bt8b0t) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But why, what's the point if we can simply verify it here and have the test self contained instead of split between two different parts.
</blockquote></details>

summon @dimakuv @mkow 


<!-- Sent from Reviewable.io -->

2022-07-04 19:03 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/fs/seek_tell_truncate.c` line 24 at r4](https://reviewable.io/reviews/gramineproject/gramine/718#-N69ZYJZ3AznYK5sk49s:-N69a0-P0I0NYiYIq2Ho:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2a64a2d3b63706d20425ffb0d618a60aee8222a5/libos/test/fs/seek_tell_truncate.c#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This change is wrong, `off_t` is signed
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell_truncate.c` line 32 at r4](https://reviewable.io/reviews/gramineproject/gramine/718#-N69ZlS-EVYhMNrMnIxn:-N69a26j1i1l5Ktx3BBW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/2a64a2d3b63706d20425ffb0d618a60aee8222a5/libos/test/fs/seek_tell_truncate.c#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 20:03 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2022-07-05 08:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N6CPPIs-i5N7bqBeB9D:btfwi3j) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

summon @dimakuv @mkow 
</blockquote></details>

I generally prefer @boryspoplawski's way: keep the test self-checking, and basically have just `run_binary()` and `assertIn("TEST OK")` in Python.

That said, we started adopting this policy recently, and we only did this for LibOS `regression/` tests. Maybe it's a good time to start moving to this way in all other tests as well.

Since how exactly the tests are executed is low priority, I am not blocking. If we want to be strict with new tests, then I agree with Borys. If we don't want to spend much time on this, I would just leave the current test as is.


<!-- Sent from Reviewable.io -->

2022-07-05 13:06 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N6DSUTS0YEHBHFZU-Ps:b5j9pyl) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
> That said, we started adopting this policy recently, and we only did this for LibOS regression/ tests. 

Well, not true, we use it everywhere else as well.

> If we want to be strict with new tests, then I agree with Borys. If we don't want to spend much time on this, I would just leave the current test as is.

I wouldn't spend time on rewriting existing tests just for the sake of it, that's pointless. But any new tests (or if you rewrite existing ones for other reasons) should follow the preferred way (if we agree on one).


<!-- Sent from Reviewable.io -->

2022-07-05 16:33 UTC, mkow requested changes
> Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @oshogbo)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N6EAxwf3uk4Y0PxN0zn:bybcqa3) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> That said, we started adopting this policy recently, and we only did this for LibOS regression/ tests. 

Well, not true, we use it everywhere else as well.

> If we want to be strict with new tests, then I agree with Borys. If we don't want to spend much time on this, I would just leave the current test as is.

I wouldn't spend time on rewriting existing tests just for the sake of it, that's pointless. But any new tests (or if you rewrite existing ones for other reasons) should follow the preferred way (if we agree on one).
</blockquote></details>

I'm neutral on this as long as the exit code is always non-zero for a failed test (which isn't the case now?).
___
*[`libos/test/fs/seek_tell_truncate.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/718#-N6EC5ew19RSvqyHnhzL:-N6EC5ew19RSvqyHnhzM:undefined) ([raw file](https://github.com/gramineproject/gramine/blob/b0b61d86b4457999ab6663b491d1ff63e25f6914/libos/test/fs/seek_tell_truncate.c#L47)):*
> ```C
> 
> int main(int argc, char* argv[]) {
>     if (argc < 4)
> ```





_Suggestion:_
```C
argc < 5
```


<!-- Sent from Reviewable.io -->

2022-07-06 10:43 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: 2 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @oshogbo)

___
*[`libos/test/fs/seek_tell_truncate.c` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68stsg0TYJ1TDN7nQh:-N6I1RbS2DcOeiOWO_XW:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm neutral on this as long as the exit code is always non-zero for a failed test (which isn't the case now?).
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell_truncate.c` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68soUHBkm43xsq7V69:-N6I5rps14aO6Bt7bUaD:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L23)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell_truncate.c` line 32 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tGct1c4Py4uY6fLa:-N6I5sSlDBlXZT48hH6n:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L32)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`libos/test/fs/seek_tell_truncate.c` line 39 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68tqa6ES49s_MqZLOL:-N6I5tFmEB_L1HTNkneR:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/seek_tell_truncate.c#L39)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`libos/test/fs/test_fs.py` line 256 at r3](https://reviewable.io/reviews/gramineproject/gramine/718#-N68sapP4QYk-yHvISeU:-N6I5xT30XciheeGt_s8:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/8e7115f1e1791f29d4d96cab2219310269a2c95a/libos/test/fs/test_fs.py#L256)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I don't have any opinion about it. 
This is how all the fs tests are build, they don't verify the correctness just print the value and the python is verifying correctness. I just used the same schema.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 10:44 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: 2 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/fs/seek_tell_truncate.c` line 47 at r5](https://reviewable.io/reviews/gramineproject/gramine/718#-N6EC5ew19RSvqyHnhzL:-N6I6-eV-7Ibj40AqGsV:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/b0b61d86b4457999ab6663b491d1ff63e25f6914/libos/test/fs/seek_tell_truncate.c#L47)):*
> ```C
> 
> int main(int argc, char* argv[]) {
>     if (argc < 4)
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 13:21 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`libos/test/fs/test_fs.py` line 255 at r6](https://reviewable.io/reviews/gramineproject/gramine/718#-N6IesRVCqqwhuLgwQU8:-N6IekWd2YOmRsFWlZvB:b-rkamlu) ([raw file](https://github.com/gramineproject/gramine/blob/ed9c051a1361b7bb2c7919bfede3adc85f72bcbc/libos/test/fs/test_fs.py#L255)):*
> ```Python
>         ])
> 
>         self.assertNotIn('ERROR: ', stderr)
> ```

This is rather useless - if the test prints `ERROR` it also exits with non-zero return code, which we verify.
I would rather add a print before final `return 0` and verify it here (so that we know the test reached the end and it's not just accidentally returned zero).


<!-- Sent from Reviewable.io -->

2022-07-07 08:15 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/718#-N6IHCtrDB3VXONLJ-nK:-N6MiSd84hZfSp_sFiqA:bvrhdb6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins failed, please verify
</blockquote></details>

Looks like the problem was in redundant Python code, and Pylint complained. You resolved it, so I'm unblocking.

___


<!-- Sent from Reviewable.io -->

2022-07-07 10:12 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-07-07 17:40 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: 2 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[`libos/test/fs/test_fs.py` line 255 at r6](https://reviewable.io/reviews/gramineproject/gramine/718#-N6IesRVCqqwhuLgwQU8:-N6OjnsE11uVeaxmDwub:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/ed9c051a1361b7bb2c7919bfede3adc85f72bcbc/libos/test/fs/test_fs.py#L255)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is rather useless - if the test prints `ERROR` it also exits with non-zero return code, which we verify.
I would rather add a print before final `return 0` and verify it here (so that we know the test reached the end and it's not just accidentally returned zero).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 18:38 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-07 21:54 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-08 07:06 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-08 13:49 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-07-08 19:28 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/718)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-08 21:00 UTC, merged