[common] Drop offset from the protected file structure
gramineproject/gramine pull request #719
Opened 2022-07-01 11:36 UTC by oshogbo

## Description of the changes 

The `offset` field supposed to represent the current file position (user's view). This isn't true. The actual offset of the file is kept in the LibOS, not in the protected files. We can observe this when `lseek(2)` is used. Also there isn't any API that allows us to get a current offset from protected file structure. The offset is changed when the LibOS wants to read/write the data.

This field is ambiguous, so it's better to remove it and pass the requested offset to each function.

## How to test this PR? 

```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```

2022-07-04 07:43 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/719#-N679WsL049xoEtFzQ39:-N679WsL049xoEtFzQ3A:b-pqt1eo) (no related file):*
Nice cleanup! Thanks.

___
___
*[`common/src/protected_files/protected_files.c` line 659 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678Ue4AIsQCQrLtfu4:-N678Ue4AIsQCQrLtfu5:bpb4og7) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L659)):*
> ```C
> // seek to a specified file offset from the beginning
> // seek beyond the current size is supported if the file is writable,
> // the file is then extended with zeros (Intel SGX SDK implementation didn't support extending)
> ```

This comment is now stale. Either rewrite or simply remove.
___
*[`common/src/protected_files/protected_files.c` line 762 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678jiV4NOZ_iRqcMWr:-N678jiV4NOZ_iRqcMWs:b-a7zcha) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L762)):*
> ```C
>     while (data_left_to_write > 0) {
>         file_node_t* file_data_node = NULL;
>         // return the data node of the current offset, will read it from disk or create new one
> ```

`of the current offset` -- this is stale now
___
*[`common/src/protected_files/protected_files.c` line 770 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N6781hc9Vu3gTQnzBOd:-N677llrC6UbvBXONSl1:b-8qzgv8) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L770)):*
> ```C
>         }
> 
>         uint64_t offset_in_node = (size_t)((offset - MD_USER_DATA_SIZE) % PF_NODE_SIZE);
> ```

`(size_t)` -> `(uint64_t)`

Actually, where is there a type cast at all?
___
*[`common/src/protected_files/protected_files.c` line 843 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678p3AC2RY14pRkWfy:-N678p3AC2RY14pRkWfz:b-a7zcha) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L843)):*
> ```C
>     while (data_left_to_read > 0) {
>         file_node_t* file_data_node = NULL;
>         // return the data node of the current offset, will read it from disk if needed
> ```

`of the current offset` -- this is stale now


<!-- Sent from Reviewable.io -->

2022-07-04 08:35 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`common/src/protected_files/protected_files.c` line 659 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678Ue4AIsQCQrLtfu4:-N67KQdo11l-b_7zp8Fd:b-896fix) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L659)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is now stale. Either rewrite or simply remove.
</blockquote></details>

Done.



_Code quote:_
```C
ipf_check_offset
```
___
*[`common/src/protected_files/protected_files.c` line 762 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678jiV4NOZ_iRqcMWr:-N67Kbgx9U3G34jiDaZr:blc9vlv) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L762)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`of the current offset` -- this is stale now
</blockquote></details>

I'm not sure about that, in this loop we are changing the offset.
Or maybe just an `offset` will make it more obvious?



_Code quote:_
```C
data_left_to_write
```
___
*[`common/src/protected_files/protected_files.c` line 770 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N6781hc9Vu3gTQnzBOd:-N67KrHx-ZgTPYuTk6Gd:b-3mc3p4) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L770)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`(size_t)` -> `(uint64_t)`

Actually, where is there a type cast at all?
</blockquote></details>

Nice catch thank you.
___
*[`common/src/protected_files/protected_files.c` line 843 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678p3AC2RY14pRkWfy:-N67Ksji2LMrcpGDNQ01:bs4q9op) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L843)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`of the current offset` -- this is stale now
</blockquote></details>

Ditto.


<!-- Sent from Reviewable.io -->

2022-07-04 08:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`common/src/protected_files/protected_files.c` line 762 at r1](https://reviewable.io/reviews/gramineproject/gramine/719#-N678jiV4NOZ_iRqcMWr:-N67PhtZCcGL6BhogIMg:b-hcg9gc) ([raw file](https://github.com/gramineproject/gramine/blob/3b4884decbe0450a05b84394080f57425938f2a0/common/src/protected_files/protected_files.c#L762)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I'm not sure about that, in this loop we are changing the offset.
Or maybe just an `offset` will make it more obvious?
</blockquote></details>

Ok, I get it now -- the comment is not about the `pf->offset` really, but more about the fact that we read data nodes related to the `[ptr, size)` region, and the current value of the offset represents a corresponding data node. Resolving.


<!-- Sent from Reviewable.io -->

2022-07-05 16:45 UTC, mkow requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 676 at r2](https://reviewable.io/reviews/gramineproject/gramine/719#-N6ECzSc4H7Kcsnaax4I:-N6ECzSc4H7Kcsnaax4J:b1dqnpw) ([raw file](https://github.com/gramineproject/gramine/blob/f7e0f8a5dabf68d0bb1e09fc8c7504f2c3b2e204/common/src/protected_files/protected_files.c#L676)):*
> ```C
> 
>     if (result)
>         pf->end_of_file = false;
> ```

I don't like this - the function name is "check_something", but it actually modifies the internal state of the object.



_Code quote (i):_
```C
static bool ipf_check_offset(pf_context_t* pf, uint64_t new_offset)
```



_Code quote (ii):_
```C
pf->end_of_file = false;
```
___
*[`common/src/protected_files/protected_files.c` line 1081 at r2](https://reviewable.io/reviews/gramineproject/gramine/719#-N6EEBU78hC0gudF2mb8:-N6EEBU8Bnd8pbd33Q94:b-amtzk) ([raw file](https://github.com/gramineproject/gramine/blob/f7e0f8a5dabf68d0bb1e09fc8c7504f2c3b2e204/common/src/protected_files/protected_files.c#L1081)):*
> ```C
>     // bytes per MHT node
>     if ((offset - MD_USER_DATA_SIZE) % (ATTACHED_DATA_NODES_COUNT * PF_NODE_SIZE) == 0 &&
>          offset == pf->encrypted_part_plain.size) {
> ```

Please keep it indented like before.


<!-- Sent from Reviewable.io -->

2022-07-05 22:58 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @oshogbo)

___
*[`common/src/protected_files/protected_files.c` line 676 at r2](https://reviewable.io/reviews/gramineproject/gramine/719#-N6ECzSc4H7Kcsnaax4I:-N6FZje3BBC35zxG97-7:b-80bqi8) ([raw file](https://github.com/gramineproject/gramine/blob/f7e0f8a5dabf68d0bb1e09fc8c7504f2c3b2e204/common/src/protected_files/protected_files.c#L676)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

What would you say about `eval`?
</blockquote></details>

I don't like `eval`, in literally all programming languages which have it in their standard libraries is means executing some code passed as an argument.
Maybe `ipf_update_after_seek`? Or something in this direction.


<!-- Sent from Reviewable.io -->

2022-07-06 10:50 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`common/src/protected_files/protected_files.c` line 676 at r2](https://reviewable.io/reviews/gramineproject/gramine/719#-N6ECzSc4H7Kcsnaax4I:-N6I6_Og3LILpCotQ0SU:b-f2zrqn) ([raw file](https://github.com/gramineproject/gramine/blob/f7e0f8a5dabf68d0bb1e09fc8c7504f2c3b2e204/common/src/protected_files/protected_files.c#L676)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like `eval`, in literally all programming languages which have it in their standard libraries is means executing some code passed as an argument.
Maybe `ipf_update_after_seek`? Or something in this direction.
</blockquote></details>

I liked an `eval`, as a short version of `evaluate` -- `evaluate offset`.
But I understand your point :)
Done.


<!-- Sent from Reviewable.io -->

2022-07-06 11:34 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-06 12:41 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`common/src/protected_files/protected_files.c` line 676 at r2](https://reviewable.io/reviews/gramineproject/gramine/719#-N6ECzSc4H7Kcsnaax4I:-N6IWhVB6Rg8jRjfeXyT:b-88h4x2) ([raw file](https://github.com/gramineproject/gramine/blob/f7e0f8a5dabf68d0bb1e09fc8c7504f2c3b2e204/common/src/protected_files/protected_files.c#L676)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I liked an `eval`, as a short version of `evaluate` -- `evaluate offset`.
But I understand your point :)
Done.
</blockquote></details>

Yeah, I also understand yours, but the problem was that "eval" usually means something else and can be confusing IMO ;)


<!-- Sent from Reviewable.io -->

2022-07-06 13:44 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-07-06 13:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/719)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 14:23 UTC, merged